DayZ Scripts: NoiseAIEvaluate Class Reference
NoiseAIEvaluate Class Reference
Static Private Member Functions
static float GetNoiseMultiplier (DayZPlayerImplement playerImplement)
static float GetNoiseReduction (Weather weather)
static float GetNoiseMultiplierByPlayerSpeed (DayZPlayerImplement playerImplement)
static float GetNoiseMultiplierByShoes (DayZPlayerImplement playerImplement)
static float GetNoiseMultiplierBySurface (DayZPlayerImplement playerImplement)
Static Private Attributes
static float SURFACE_NOISE_WEIGHT = 0.25
Member Function Documentation
GetNoiseMultiplier()
static float GetNoiseMultiplier (DayZPlayerImplement playerImplement) inline static private
References GetNoiseMultiplierByPlayerSpeed(), GetNoiseMultiplierByShoes(), GetNoiseMultiplierBySurface(), and SURFACE_NOISE_WEIGHT.
Referenced by DayZPlayer::OnStepEvent(), and ProcessNoiseComponents().
GetNoiseMultiplierByPlayerSpeed()
static float GetNoiseMultiplierByPlayerSpeed (DayZPlayerImplement playerImplement) inline static private
References PlayerConstants::AI_NOISE_CROUCH_RUN, PlayerConstants::AI_NOISE_IDLE, PlayerConstants::AI_NOISE_ROLL, PlayerConstants::AI_NOISE_RUN, PlayerConstants::AI_NOISE_SPRINT, PlayerConstants::AI_NOISE_WALK, and AITargetCallbacksPlayer::StanceToMovementIdxTranslation().
Referenced by GetNoiseMultiplier(), and ShowCoefsDbg().
GetNoiseMultiplierByShoes()
static float GetNoiseMultiplierByShoes (DayZPlayerImplement playerImplement) inline static private
References PlayerConstants::AI_NOISE_SHOES_BOOTS, PlayerConstants::AI_NOISE_SHOES_NONE, and PlayerConstants::AI_NOISE_SHOES_SNEAKERS.
Referenced by GetNoiseMultiplier(), and ShowCoefsDbg().
GetNoiseMultiplierBySurface()
static float GetNoiseMultiplierBySurface (DayZPlayerImplement playerImplement) inline static private
Referenced by GetNoiseMultiplier(), and ShowCoefsDbg().
GetNoiseReduction()
static float GetNoiseReduction (Weather weather) inline static private
References Weather::GetNoiseReductionByWeather().
Referenced by DayZPlayer::CommandHandler(), GenerateAINoiseAtPosition(), GenerateCarHornAINoise(), Heating(), ActionCloseDoors::OnEndServer(), ActionCloseFence::OnEndServer(), ActionOpenDoors::OnEndServer(), ActionOpenFence::OnEndServer(), DayZPlayer::OnStepEvent(), AlarmClock_ColorBase::OnUpdate(), KitchenTimer::OnUpdate(), OnWork(), OnWorkStart(), ItemBase::PlayCatchNoise(), ProcessNoiseComponents(), DayZPlayer::ProcessSoundEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZPlayer::ProcessWeaponEvent(), and ShowCoefsDbg().
Field Documentation
SURFACE_NOISE_WEIGHT
float SURFACE_NOISE_WEIGHT = 0.25 static private
Referenced by GetNoiseMultiplier().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/SensesAIEvaluate.c