DayZ Scripts: WeaponStateBase Class Reference
WeaponStateBase Class Reference
represent weapon state base
Private Member Functions
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
void RifleChambering (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void RifleEjectCasing (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void RifleReChambering (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void RemoveNewMagazineFromInventory (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
override void OnEntry (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void WeaponAttachMagazine (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
void WeaponChamberFromAttMag (Weapon_Base w=NULL, WeaponStateBase parent=NULL, int action=-1, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
void WeaponChamberFromInnerMag (Weapon_Base w=NULL, WeaponStateBase parent=NULL, int action=-1, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
void WeaponChamberFromAttMagOnExit (Weapon_Base w=NULL, WeaponStateBase parent=NULL, int action=-1, int actionType=-1)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
source of the cartridge
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool IsWaitingForActionFinish ()
waiting for active animation action/actionType finish
void WeaponChambering (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
bool FindNextFreeMuzzle (int currentMuzzle, out int nextMuzzle)
override void OnEntry (WeaponEventBase e)
void WeaponMagnumChambering (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int startActionType=-1, int endActionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool IsWaitingForActionFinish ()
void LoopedChambering (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int startActionType=-1, int endActionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void LoopedChamberingEjectLast (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int startActionType=-1, int endActionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void WeaponCharging (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override bool IsWaitingForActionFinish ()
override void OnEntry (WeaponEventBase e)
destination of the cartridge
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override void OnEntry (WeaponEventBase e)
destination of the cartridge
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void WeaponChargingInnerMag (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
void WeaponChargingMultiple (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
void WeaponChargingStretch (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void WeaponDetachingMag (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void WeaponEjectBullet (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void WeaponEjectCasing (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
override void OnEntry (WeaponEventBase e)
void WeaponEjectCasingMultiMuzzle (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
override void OnEntry (WeaponEventBase e)
override bool IsWaitingForActionFinish ()
void WeaponEjectAllMuzzles (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
override void OnEntry (WeaponEventBase e)
override bool IsWaitingForActionFinish ()
void WeaponFireAndChamberNext (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnUpdate (float dt)
override void OnExit (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
void WeaponFireAndChamberNextFromInnerMag (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnUpdate (float dt)
override void OnExit (WeaponEventBase e)
void WeaponFireLast (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
void WeaponRechamber (Weapon_Base w=NULL, WeaponStateBase parent=NULL, int actionEject=-1, int actionTypeEject=-1, int actionLoad=-1, int actionTypeLoad=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void DetachOldMagazine (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
override void OnEntry (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override void OnEntry (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void AttachNewMagazine (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
override bool IsWaitingForActionFinish ()
override void OnEntry (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool IsWaitingForActionFinish ()
void WeaponReplacingMagAndChamberNext (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void WeaponStartAction (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
specific action sub-type
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
void WeaponStateBase (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
internal state id used for load/restore
void SetParentState (WeaponStateBase parent)
allows construction of hierarchical state machine
WeaponStateBase GetParentState ()
bool HasFSM ()
WeaponFSM GetFSM ()
void SetInternalStateID (int i)
int GetInternalStateID ()
bool SaveCurrentFSMState (ParamsWriteContext ctx)
bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
bool ProcessEvent (WeaponEventBase e)
void AddTransition (WeaponTransition t)
adds transition into m_fsm transition table
void OnEntry (WeaponEventBase e)
void OnUpdate (float dt)
void OnAbort (WeaponEventBase e)
void OnExit (WeaponEventBase e)
bool IsWaitingForActionFinish ()
bool IsIdle ()
idle state does not expect any animation events
bool IsBoltOpen ()
void OnSubMachineChanged (WeaponStateBase src, WeaponStateBase dst)
called when sub-machine has changed its state
void OnStateChanged (WeaponStateBase src, WeaponStateBase dst)
called on current state when state machine has changed its state
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool IsWaitingForActionFinish ()
void WeaponUnjamming (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
Private Attributes
WeaponActions m_action
int m_actionType
action to be played
Magazine m_srcMagazine
destination of the ejected cartridge
ref WeaponStateBase m_start
source of the cartridge
ref WeaponEjectCasing m_eject
ref WeaponChambering_Cartridge m_chamber
ref WeaponChambering_W4T m_w4t
ref WeaponStartAction m_start
ref BulletHide_W4T m_hideB
Magazine m_dstMagazine
ref WeaponEjectBullet_Cartridge m_eject
Magazine m_newMagazine
magazine that will be detached
ref InventoryLocation m_newSrc
magazine that will be removed from inventory
ref AttachNewMagazine m_attach
ref WeaponChamberFromAttMag_W4T m_chamber
ref WeaponCharging_CK m_onCK
float m_damage
string m_type
string m_magazineType
ref InventoryLocation m_srcMagazinePrevLocation
source of the cartridge
int m_startActionType
int m_endActionType
ref WeaponEjectAllMuzzles m_eject
ref WeaponCylinderRotate m_rotate
ref WeaponChambering_Base m_chamber
ref LoopedChambering_Wait4ShowBullet2 m_w4sb2
ref WeaponStartAction m_endLoop
ref WeaponChamberFromInnerMag_W4T m_chamberFromInnerMag
ref WeaponCharging_Start m_start
ref WeaponEjectBullet_Cartridge_W4T m_onBE
ref WeaponEjectCasing_W4T m_onBEFireOut
ref WeaponChamberFromInnerMag_W4T m_chamber
Magazine m_magazine
ref InventoryLocation m_dst
magazine that will be detached
ref WeaponDetachingMag_Store m_store
ref MagazineHide_W4T m_hideM
ref WeaponEjectBullet_Start m_start
destination of the cartridge
ref WeaponEjectBullet_Cartridge_W4T m_eject
float m_dtAccumulator
ref WeaponFire m_fire
ref WeaponFireWithEject m_fire
int m_actionEject
int m_actionTypeEject
int m_actionLoad
int m_actionTypeLoad
ref WeaponEjectBullet m_eje
source of the loaded cartridge
ref WeaponChambering m_loa
Magazine m_oldMagazine
ref InventoryLocation m_newDst
magazine that will be detached
ref DetachOldMagazine m_detach
ref OldMagazineHide m_hideOld
ref SwapOldAndNewMagazine m_swapMags
ref AttachNewMagazine_W4T m_attach
Weapon_Base m_weapon
WeaponStateBase m_parentState
weapon that this state relates to
ref WeaponFSM m_fsm
hierarchical parent state of this state (or null)
int m_InternalID = -1
nested state machine (or null)
float m_jamTime
ref WeaponUnjamming_Start m_start
ref WeaponUnjamming_Cartridge_W4T m_eject
ref WeaponUnjamming_W4T m_w4t
Detailed Description
represent weapon state base
Class comes with entry/update/abort/exit hooks that can be overriden in custom states
Class is ready for hierarchic composition, i.e. this state having a sub-machine running under hood. If no m_fsm member is configured, class acts as ordinary plain finite machine state.
Definition at line 1 of file BulletHide.c.
Constructor & Destructor Documentation
WeaponStateBase()
void WeaponStateBase (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
internal state id used for load/restore
Definition at line 17 of file WeaponStateBase.c.
References m_parentState, and m_weapon.
Member Function Documentation
AddTransition()
AddTransition (WeaponTransition t) inline private
adds transition into m_fsm transition table
Definition at line 89 of file WeaponStateBase.c.
References Error(), HasFSM(), m_fsm, and m_weapon.
AttachNewMagazine()
void AttachNewMagazine (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 219 of file WeaponReplacingMagAndChamberNext.c.
DetachOldMagazine()
void DetachOldMagazine (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 10 of file WeaponReplacingMagAndChamberNext.c.
References m_oldMagazine.
FindNextFreeMuzzle()
bool FindNextFreeMuzzle (int currentMuzzle, out int nextMuzzle) inline private
Definition at line 886 of file WeaponChambering.c.
References m_weapon, and Math::WrapInt().
Referenced by OnEntry().
GetFSM()
WeaponFSM GetFSM () inline private
Definition at line 29 of file WeaponStateBase.c.
References m_fsm.
GetInternalStateID()
int GetInternalStateID () inline private
Definition at line 32 of file WeaponStateBase.c.
References m_InternalID.
Referenced by HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::FindStateForInternalID(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::GetInternalStateID(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentUnstableFSMState(), and HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SetInternalID().
GetParentState()
GetParentState () inline private
Returns
state that owns this sub-state (or null if plain state)
Definition at line 26 of file WeaponStateBase.c.
References m_parentState.
HasFSM()
bool HasFSM () inline private
Definition at line 28 of file WeaponStateBase.c.
References m_fsm.
Referenced by AddTransition(), IsWaitingForActionFinish(), LoadCurrentFSMState(), OnAbort(), OnEntry(), OnUpdate(), ProcessEvent(), and SaveCurrentFSMState().
IsBoltOpen()
IsBoltOpen () inline private
Returns
true if weapon bolt is open
Definition at line 163 of file WeaponStateBase.c.
Referenced by WeaponParticlesBase::CheckBoltStateCondition().
IsIdle()
IsIdle () inline private
idle state does not expect any animation events
Returns
true if this state is idle
Definition at line 158 of file WeaponStateBase.c.
Referenced by LoadCurrentFSMState(), and SaveCurrentFSMState().
IsWaitingForActionFinish() [1/9]
IsWaitingForActionFinish () inline private
waiting for active animation action/actionType finish
Returns
true if this state or active substate is waiting for finish signal
Definition at line 365 of file WeaponChambering.c.
IsWaitingForActionFinish() [2/9]
override bool IsWaitingForActionFinish () inline private
Definition at line 9 of file WeaponChamberingLooped.c.
IsWaitingForActionFinish() [3/9]
override bool IsWaitingForActionFinish () inline private
Definition at line 66 of file WeaponCharging.c.
IsWaitingForActionFinish() [4/9]
override bool IsWaitingForActionFinish () inline private
Definition at line 45 of file WeaponEjectCasingAndChamberFromAttMag.c.
IsWaitingForActionFinish() [5/9]
override bool IsWaitingForActionFinish () inline private
Definition at line 117 of file WeaponEjectCasingAndChamberFromAttMag.c.
IsWaitingForActionFinish() [6/9]
override bool IsWaitingForActionFinish () inline private
Definition at line 225 of file WeaponReplacingMagAndChamberNext.c.
IsWaitingForActionFinish() [7/9]
override bool IsWaitingForActionFinish () inline private
Definition at line 328 of file WeaponReplacingMagAndChamberNext.c.
IsWaitingForActionFinish() [8/9]
bool IsWaitingForActionFinish () inline private
Definition at line 152 of file WeaponStateBase.c.
References HasFSM(), and m_fsm.
IsWaitingForActionFinish() [9/9]
override bool IsWaitingForActionFinish () inline private
Definition at line 161 of file WeaponUnjamming.c.
LoadCurrentFSMState() [1/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 87 of file RifleChambering.c.
References Error(), m_srcMagazine, m_weapon, and Serializer::Read().
LoadCurrentFSMState() [2/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 106 of file RifleReChambering.c.
References Error(), m_srcMagazine, m_weapon, and Serializer::Read().
LoadCurrentFSMState() [3/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 82 of file WeaponAttachMagazine.c.
References Error(), m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [4/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 55 of file WeaponChambering.c.
References Error(), m_srcMagazine, m_weapon, and Serializer::Read().
LoadCurrentFSMState() [5/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 593 of file WeaponChambering.c.
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [6/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 1172 of file WeaponChambering.c.
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [7/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 250 of file WeaponChamberingLooped.c.
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [8/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 510 of file WeaponChamberingLooped.c.
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [9/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 110 of file WeaponCharging.c.
References Error(), m_weapon, and Serializer::Read().
LoadCurrentFSMState() [10/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 170 of file WeaponCharging.c.
References Error(), m_weapon, and Serializer::Read().
LoadCurrentFSMState() [11/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 77 of file WeaponDetachingMag.c.
References Error(), m_dst, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [12/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 183 of file WeaponDetachingMag.c.
References Error(), m_dst, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [13/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 125 of file WeaponEjectBullet.c.
References Error(), m_weapon, and Serializer::Read().
LoadCurrentFSMState() [14/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 88 of file WeaponReChamber.c.
References Error(), m_srcMagazine, m_weapon, and Serializer::Read().
LoadCurrentFSMState() [15/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 86 of file WeaponReplacingMagAndChamberNext.c.
References Error(), m_oldMagazine, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [16/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 191 of file WeaponReplacingMagAndChamberNext.c.
References Error(), m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [17/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 307 of file WeaponReplacingMagAndChamberNext.c.
References Error(), m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [18/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 571 of file WeaponReplacingMagAndChamberNext.c.
References Error(), m_oldMagazine, m_weapon, and Serializer::Read().
LoadCurrentFSMState() [19/20]
bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 54 of file WeaponStateBase.c.
References Error(), HasFSM(), IsIdle(), LogManager::IsWeaponLogEnable(), m_fsm, m_weapon, and wpnDebugSpam().
LoadCurrentFSMState() [20/20]
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 134 of file WeaponUnjamming.c.
References Error(), m_weapon, and Serializer::Read().
LoopedChambering()
void LoopedChambering (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int startActionType = -1, int endActionType = -1) inline private
Definition at line 27 of file WeaponChamberingLooped.c.
References m_action, m_chamber, m_eject, m_endActionType, m_endLoop, m_start, m_startActionType, m_w4sb2, and m_weapon.
LoopedChamberingEjectLast()
void LoopedChamberingEjectLast (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int startActionType = -1, int endActionType = -1) inline private
Definition at line 286 of file WeaponChamberingLooped.c.
References m_action, m_chamber, m_eject, m_endActionType, m_endLoop, m_start, m_startActionType, m_w4sb2, and m_weapon.
OnAbort() [1/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 62 of file RifleChambering.c.
References m_srcMagazine.
OnAbort() [2/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 74 of file RifleReChambering.c.
References m_srcMagazine.
OnAbort() [3/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 46 of file WeaponAttachMagazine.c.
OnAbort() [4/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 190 of file WeaponAttachMagazine.c.
References DayZPlayerUtils(), Error(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnAbort() [5/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 454 of file WeaponChambering.c.
References DayZPlayerUtils(), vector::DistanceSq(), Error(), InventoryLocation::GetPos(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationCanMoveEntity(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnAbort() [6/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 1092 of file WeaponChambering.c.
References DayZPlayerUtils(), vector::DistanceSq(), Error(), InventoryLocation::GetPos(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationCanMoveEntity(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnAbort() [7/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 170 of file WeaponChamberingLooped.c.
References DayZPlayerUtils(), vector::DistanceSq(), Error(), InventoryLocation::GetPos(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationCanMoveEntity(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnAbort() [8/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 431 of file WeaponChamberingLooped.c.
References DayZPlayerUtils(), vector::DistanceSq(), Error(), InventoryLocation::GetPos(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationCanMoveEntity(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnAbort() [9/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 85 of file WeaponCharging.c.
OnAbort() [10/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 145 of file WeaponCharging.c.
OnAbort() [11/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 24 of file WeaponDetachingMag.c.
References m_dst.
OnAbort() [12/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 100 of file WeaponEjectBullet.c.
OnAbort() [13/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 67 of file WeaponFireAndChamberNext.c.
References m_weapon.
OnAbort() [14/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 21 of file WeaponReplacingMagAndChamberNext.c.
References m_oldMagazine.
OnAbort() [15/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 153 of file WeaponReplacingMagAndChamberNext.c.
OnAbort() [16/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 260 of file WeaponReplacingMagAndChamberNext.c.
References DayZPlayerUtils(), Error(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnAbort() [17/18]
override void OnAbort (WeaponEventBase e) inline private
Definition at line 502 of file WeaponReplacingMagAndChamberNext.c.
References DayZPlayerUtils(), Error(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), m_oldMagazine, WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnAbort() [18/18]
void OnAbort (WeaponEventBase e) inline private
Definition at line 129 of file WeaponStateBase.c.
References HasFSM(), LogManager::IsWeaponLogEnable(), m_fsm, m_weapon, and wpnDebugPrint().
OnEntry() [1/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 3 of file BulletHide.c.
References m_weapon.
OnEntry() [2/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 3 of file BulletShow.c.
References m_weapon.
OnEntry() [3/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 18 of file BulletShow.c.
References m_weapon.
OnEntry() [4/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 3 of file MagazineHide.c.
OnEntry() [5/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 3 of file MagazineShow.c.
References m_weapon.
OnEntry() [6/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 42 of file RifleChambering.c.
References LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_magazine, m_srcMagazine, m_srcMagazine, m_weapon, and wpnDebugPrint().
OnEntry() [7/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 43 of file RifleReChambering.c.
References DayZPlayerUtils(), Error(), GetGame(), CGame::IsMultiplayer(), CGame::IsServer(), LogManager::IsWeaponLogEnable(), m_chamber, m_dstMagazine, m_eject, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_weapon, and wpnDebugPrint().
OnEntry() [8/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 12 of file WeaponAttachMagazine.c.
References Error(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), WeaponEventBase::m_player, m_weapon, InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [9/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 163 of file WeaponAttachMagazine.c.
References Error(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_weapon, InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [10/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 8 of file WeaponChamberFromAttMag.c.
References m_weapon, and pushToChamberFromAttachedMagazine().
OnEntry() [11/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 29 of file WeaponChamberFromAttMag.c.
References m_weapon, and pushToChamberFromInnerMagazine().
OnEntry() [12/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 417 of file WeaponChambering.c.
References Error(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [13/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 902 of file WeaponChambering.c.
References FindNextFreeMuzzle(), m_weapon, and Print().
OnEntry() [14/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 994 of file WeaponChambering.c.
References Error(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, Print(), InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [15/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 73 of file WeaponChamberingLooped.c.
References Error(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, Print(), InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [16/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 336 of file WeaponChamberingLooped.c.
References Error(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, Print(), InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [17/38]
override void OnEntry (WeaponEventBase e) inline private
destination of the cartridge
Definition at line 73 of file WeaponCharging.c.
References ejectBulletAndStoreInMagazine(), WeaponEventBase::m_player, and m_weapon.
OnEntry() [18/38]
override void OnEntry (WeaponEventBase e) inline private
destination of the cartridge
Definition at line 129 of file WeaponCharging.c.
References ejectBulletAndStoreInMagazine(), WeaponEventBase::m_player, and m_weapon.
OnEntry() [19/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 255 of file WeaponCharging.c.
OnEntry() [20/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 327 of file WeaponCharging.c.
OnEntry() [21/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 11 of file WeaponDetachingMag.c.
References Error(), m_dst, and m_weapon.
OnEntry() [22/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 138 of file WeaponDetachingMag.c.
References Class::CastTo(), LogManager::IsWeaponLogEnable(), m_dst, m_dst, WeaponEventBase::m_magazine, m_magazine, and wpnDebugPrint().
OnEntry() [23/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 85 of file WeaponEjectBullet.c.
References LogManager::IsWeaponLogEnable(), m_dstMagazine, m_eject, WeaponEventBase::m_magazine, m_weapon, and wpnDebugPrint().
OnEntry() [24/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 6 of file WeaponEjectCasingAndChamberFromAttMag.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
OnEntry() [25/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 27 of file WeaponEjectCasingAndChamberFromAttMag.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
OnEntry() [26/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 61 of file WeaponEjectCasingAndChamberFromAttMag.c.
References ejectBulletAndStoreInMagazine(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnEntry() [27/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 31 of file WeaponFireAndChamberNext.c.
References m_dtAccumulator.
OnEntry() [28/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 31 of file WeaponFireAndChamberNextFromInnerMag.c.
References m_dtAccumulator.
OnEntry() [29/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 31 of file WeaponFireLast.c.
References m_dtAccumulator.
OnEntry() [30/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 35 of file WeaponReChamber.c.
References DayZPlayerUtils(), Error(), LogManager::IsWeaponLogEnable(), m_dstMagazine, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_weapon, and wpnDebugPrint().
OnEntry() [31/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 16 of file WeaponReplacingMagAndChamberNext.c.
OnEntry() [32/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 126 of file WeaponReplacingMagAndChamberNext.c.
References InventoryLocation::DumpToStringNullSafe(), Error(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), WeaponEventBase::m_player, m_weapon, InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [33/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 230 of file WeaponReplacingMagAndChamberNext.c.
References Error(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), WeaponEventBase::m_player, m_weapon, InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [34/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 406 of file WeaponReplacingMagAndChamberNext.c.
References Class::CastTo(), Error(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), m_oldMagazine, WeaponEventBase::m_player, m_weapon, InventoryLocation::SetAttachment(), InventoryLocation::SetItem(), and wpnDebugPrint().
OnEntry() [35/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 15 of file WeaponStartAction.c.
References Error(), HumanCommandWeapons::GetRunningAction(), HumanCommandWeapons::GetRunningActionType(), HumanCommandAdditives(), HumanCommandWeapons::IsActionFinished(), LogManager::IsWeaponLogEnable(), m_action, WeaponEventBase::m_player, HumanCommandWeapons::StartAction(), WeaponActionTypeToString(), and wpnDebugPrint().
OnEntry() [36/38]
void OnEntry (WeaponEventBase e) inline private
Definition at line 103 of file WeaponStateBase.c.
References HasFSM(), LogManager::IsWeaponLogEnable(), m_fsm, m_weapon, and wpnDebugPrint().
OnEntry() [37/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 77 of file WeaponUnjamming.c.
References ejectBulletAndStoreInMagazine(), string::Empty, WeaponEventBase::m_player, and m_weapon.
OnEntry() [38/38]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 212 of file WeaponUnjamming.c.
References m_dtAccumulator, m_dtAccumulator, m_jamTime, and m_start.
OnExit() [1/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 10 of file BulletHide.c.
OnExit() [2/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 10 of file BulletShow.c.
OnExit() [3/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 25 of file BulletShow.c.
OnExit() [4/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 9 of file MagazineHide.c.
OnExit() [5/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 10 of file MagazineShow.c.
OnExit() [6/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 68 of file RifleChambering.c.
References m_srcMagazine.
OnExit() [7/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 81 of file RifleReChambering.c.
References m_srcMagazine.
OnExit() [8/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 54 of file WeaponAttachMagazine.c.
References m_weapon.
OnExit() [9/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 17 of file WeaponChamberFromAttMag.c.
OnExit() [10/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 38 of file WeaponChamberFromAttMag.c.
OnExit() [11/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 50 of file WeaponChamberFromAttMag.c.
References m_weapon, and pushToChamberFromAttachedMagazine().
OnExit() [12/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 514 of file WeaponChambering.c.
References DayZPlayerUtils(), vector::DistanceSq(), Error(), InventoryLocation::GetPos(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationCanMoveEntity(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnExit() [13/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 1032 of file WeaponChambering.c.
References DayZPlayerUtils(), vector::DistanceSq(), Error(), InventoryLocation::GetPos(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationCanMoveEntity(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnExit() [14/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 111 of file WeaponChamberingLooped.c.
References DayZPlayerUtils(), vector::DistanceSq(), Error(), InventoryLocation::GetPos(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationCanMoveEntity(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnExit() [15/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 372 of file WeaponChamberingLooped.c.
References DayZPlayerUtils(), vector::DistanceSq(), Error(), InventoryLocation::GetPos(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationCanMoveEntity(), GameInventory::LocationSyncMoveEntity(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnExit() [16/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 91 of file WeaponCharging.c.
OnExit() [17/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 151 of file WeaponCharging.c.
OnExit() [18/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 259 of file WeaponCharging.c.
OnExit() [19/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 331 of file WeaponCharging.c.
OnExit() [20/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 32 of file WeaponDetachingMag.c.
References Error(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), m_dst, m_weapon, and wpnDebugPrint().
OnExit() [21/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 157 of file WeaponDetachingMag.c.
References m_dst.
OnExit() [22/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 106 of file WeaponEjectBullet.c.
OnExit() [23/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 60 of file WeaponFireAndChamberNext.c.
References m_dtAccumulator.
OnExit() [24/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 55 of file WeaponFireAndChamberNextFromInnerMag.c.
References m_dtAccumulator.
OnExit() [25/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 38 of file WeaponFireLast.c.
References m_dtAccumulator.
OnExit() [26/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 62 of file WeaponReChamber.c.
OnExit() [27/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 28 of file WeaponReplacingMagAndChamberNext.c.
References DayZPlayerUtils(), Error(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), m_oldMagazine, WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnExit() [28/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 163 of file WeaponReplacingMagAndChamberNext.c.
OnExit() [29/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 281 of file WeaponReplacingMagAndChamberNext.c.
OnExit() [30/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 455 of file WeaponReplacingMagAndChamberNext.c.
References DayZPlayerUtils(), Error(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), GameInventory::LocationSyncMoveEntity(), m_oldMagazine, WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnExit() [31/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 47 of file WeaponStartAction.c.
OnExit() [32/34]
void OnExit (WeaponEventBase e) inline private
Definition at line 143 of file WeaponStateBase.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
OnExit() [33/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 110 of file WeaponUnjamming.c.
References string::Empty.
OnExit() [34/34]
override void OnExit (WeaponEventBase e) inline private
Definition at line 225 of file WeaponUnjamming.c.
References m_dtAccumulator.
OnStateChanged()
OnStateChanged (WeaponStateBase src, WeaponStateBase dst) inline private
called on current state when state machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
Definition at line 177 of file WeaponStateBase.c.
OnSubMachineChanged()
OnSubMachineChanged (WeaponStateBase src, WeaponStateBase dst) inline private
called when sub-machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
Definition at line 170 of file WeaponStateBase.c.
OnUpdate() [1/3]
override void OnUpdate (float dt) inline private
Definition at line 38 of file WeaponFireAndChamberNext.c.
References Class::CastTo(), HumanInputController::IsAttackButton(), m_dtAccumulator, and m_weapon.
OnUpdate() [2/3]
override void OnUpdate (float dt) inline private
Definition at line 38 of file WeaponFireAndChamberNextFromInnerMag.c.
References Class::CastTo(), HumanInputController::IsAttackButton(), m_dtAccumulator, and m_weapon.
OnUpdate() [3/3]
void OnUpdate (float dt) inline private
Definition at line 119 of file WeaponStateBase.c.
References HasFSM(), and m_fsm.
ProcessEvent()
bool ProcessEvent (WeaponEventBase e) inline private
Definition at line 80 of file WeaponStateBase.c.
References HasFSM(), and m_fsm.
RemoveNewMagazineFromInventory()
void RemoveNewMagazineFromInventory (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 6 of file WeaponAttachMagazine.c.
RifleChambering()
void RifleChambering (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 12 of file RifleChambering.c.
References m_action, m_chamber, m_eject, m_start, and m_weapon.
RifleEjectCasing()
void RifleEjectCasing (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 10 of file RifleEjectCasing.c.
References m_action, m_eject, m_start, and m_weapon.
RifleReChambering()
void RifleReChambering (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 13 of file RifleReChambering.c.
References m_action, m_chamber, m_eject, m_start, and m_weapon.
SaveCurrentFSMState() [1/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 74 of file RifleChambering.c.
References Error(), m_srcMagazine, m_weapon, and Serializer::Write().
Referenced by HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentFSMState().
SaveCurrentFSMState() [2/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 88 of file RifleReChambering.c.
References Error(), m_srcMagazine, m_weapon, and Serializer::Write().
SaveCurrentFSMState() [3/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 63 of file WeaponAttachMagazine.c.
References Error(), m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [4/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
source of the cartridge
Definition at line 27 of file WeaponChambering.c.
References Error(), m_srcMagazine, m_weapon, and Serializer::Write().
SaveCurrentFSMState() [5/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 574 of file WeaponChambering.c.
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [6/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 1152 of file WeaponChambering.c.
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [7/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 230 of file WeaponChamberingLooped.c.
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [8/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 491 of file WeaponChamberingLooped.c.
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [9/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 97 of file WeaponCharging.c.
References Error(), m_weapon, and Serializer::Write().
SaveCurrentFSMState() [10/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 157 of file WeaponCharging.c.
References Error(), m_weapon, and Serializer::Write().
SaveCurrentFSMState() [11/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 58 of file WeaponDetachingMag.c.
References Error(), m_dst, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [12/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 164 of file WeaponDetachingMag.c.
References Error(), m_dst, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [13/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 112 of file WeaponEjectBullet.c.
References Error(), m_weapon, and Serializer::Write().
SaveCurrentFSMState() [14/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 70 of file WeaponReChamber.c.
References Error(), m_srcMagazine, m_weapon, and Serializer::Write().
SaveCurrentFSMState() [15/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 65 of file WeaponReplacingMagAndChamberNext.c.
References Error(), m_oldMagazine, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [16/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 171 of file WeaponReplacingMagAndChamberNext.c.
References Error(), m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [17/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 288 of file WeaponReplacingMagAndChamberNext.c.
References Error(), m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [18/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 545 of file WeaponReplacingMagAndChamberNext.c.
References Error(), m_oldMagazine, m_weapon, and Serializer::Write().
SaveCurrentFSMState() [19/20]
bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 34 of file WeaponStateBase.c.
References HasFSM(), IsIdle(), LogManager::IsWeaponLogEnable(), m_fsm, m_weapon, and wpnDebugSpam().
SaveCurrentFSMState() [20/20]
override bool SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 116 of file WeaponUnjamming.c.
References Error(), m_weapon, and Serializer::Write().
SetInternalStateID()
void SetInternalStateID (int i) inline private
Definition at line 31 of file WeaponStateBase.c.
References m_InternalID.
Referenced by HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SetInternalID().
SetParentState()
SetParentState (WeaponStateBase parent) inline private
allows construction of hierarchical state machine
Definition at line 22 of file WeaponStateBase.c.
References m_parentState.
WeaponAttachMagazine()
void WeaponAttachMagazine (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 125 of file WeaponAttachMagazine.c.
References m_action, m_chamber, m_eject, m_start, m_weapon, and WeaponGuardHasAmmo().
WeaponChamberFromAttMag()
void WeaponChamberFromAttMag (Weapon_Base w = NULL, WeaponStateBase parent = NULL, int action = -1, int actionType = -1) inline private
Definition at line 5 of file WeaponChamberFromAttMag.c.
WeaponChamberFromAttMagOnExit()
void WeaponChamberFromAttMagOnExit (Weapon_Base w = NULL, WeaponStateBase parent = NULL, int action = -1, int actionType = -1) inline private
Definition at line 47 of file WeaponChamberFromAttMag.c.
WeaponChamberFromInnerMag()
void WeaponChamberFromInnerMag (Weapon_Base w = NULL, WeaponStateBase parent = NULL, int action = -1, int actionType = -1) inline private
Definition at line 26 of file WeaponChamberFromAttMag.c.
WeaponChambering()
void WeaponChambering (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 381 of file WeaponChambering.c.
References m_action, m_chamber, m_eject, m_start, and m_weapon.
Referenced by WeaponRechamber().
WeaponCharging()
void WeaponCharging (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 14 of file WeaponCharging.c.
References m_action, m_chamber, m_eject, m_start, m_weapon, and WeaponGuardHasAmmo().
WeaponChargingInnerMag()
void WeaponChargingInnerMag (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 206 of file WeaponCharging.c.
References m_action, m_chamber, m_start, and m_weapon.
WeaponChargingMultiple()
void WeaponChargingMultiple (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 281 of file WeaponCharging.c.
References m_action, m_chamber, m_start, m_weapon, and WeaponGuardHasAmmo().
WeaponChargingStretch()
void WeaponChargingStretch (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 348 of file WeaponCharging.c.
References m_action, m_start, and m_weapon.
WeaponDetachingMag()
void WeaponDetachingMag (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 112 of file WeaponDetachingMag.c.
References m_action, m_start, and m_weapon.
WeaponEjectAllMuzzles()
void WeaponEjectAllMuzzles (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 59 of file WeaponEjectCasingAndChamberFromAttMag.c.
Referenced by WeaponMagnumChambering().
WeaponEjectBullet()
void WeaponEjectBullet (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 50 of file WeaponEjectBullet.c.
References m_action, m_chamber, m_eject, m_start, m_weapon, and WeaponGuardHasAmmo().
Referenced by WeaponRechamber().
WeaponEjectCasing()
void WeaponEjectCasing (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 4 of file WeaponEjectCasingAndChamberFromAttMag.c.
WeaponEjectCasingMultiMuzzle()
void WeaponEjectCasingMultiMuzzle (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 25 of file WeaponEjectCasingAndChamberFromAttMag.c.
WeaponFireAndChamberNext()
void WeaponFireAndChamberNext (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 9 of file WeaponFireAndChamberNext.c.
References m_action, and m_weapon.
WeaponFireAndChamberNextFromInnerMag()
void WeaponFireAndChamberNextFromInnerMag (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 9 of file WeaponFireAndChamberNextFromInnerMag.c.
References m_action, and m_weapon.
WeaponFireLast()
void WeaponFireLast (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 10 of file WeaponFireLast.c.
References m_action, and m_weapon.
WeaponMagnumChambering()
void WeaponMagnumChambering (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int startActionType = -1, int endActionType = -1) inline private
Definition at line 941 of file WeaponChambering.c.
References m_action, m_chamber, m_eject, m_endActionType, m_endLoop, m_start, m_startActionType, m_w4sb2, m_weapon, and WeaponEjectAllMuzzles().
WeaponRechamber()
void WeaponRechamber (Weapon_Base w = NULL, WeaponStateBase parent = NULL, int actionEject = -1, int actionTypeEject = -1, int actionLoad = -1, int actionTypeLoad = -1) inline private
Definition at line 15 of file WeaponReChamber.c.
References m_weapon, WeaponChambering(), and WeaponEjectBullet().
WeaponReplacingMagAndChamberNext()
void WeaponReplacingMagAndChamberNext (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 357 of file WeaponReplacingMagAndChamberNext.c.
References m_action, m_chamber, m_eject, m_start, m_weapon, and WeaponGuardHasAmmo().
WeaponStartAction()
void WeaponStartAction (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
specific action sub-type
Definition at line 9 of file WeaponStartAction.c.
References m_action.
WeaponUnjamming()
void WeaponUnjamming (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 180 of file WeaponUnjamming.c.
References m_action, m_chamber, m_eject, m_start, m_weapon, and WeaponGuardHasAmmo().
Field Documentation
m_action
WeaponActions m_action private
Definition at line 3 of file RifleChambering.c.
m_actionEject
int m_actionEject private
Definition at line 5 of file WeaponReChamber.c.
m_actionLoad
int m_actionLoad private
Definition at line 7 of file WeaponReChamber.c.
m_actionType
int m_actionType private
action to be played
Definition at line 4 of file RifleChambering.c.
m_actionTypeEject
int m_actionTypeEject private
Definition at line 6 of file WeaponReChamber.c.
m_actionTypeLoad
int m_actionTypeLoad private
Definition at line 8 of file WeaponReChamber.c.
m_attach [1/2]
ref AttachNewMagazine m_attach private
Definition at line 120 of file WeaponAttachMagazine.c.
m_attach [2/2]
ref AttachNewMagazine_W4T m_attach private
Definition at line 347 of file WeaponReplacingMagAndChamberNext.c.
m_chamber [1/4]
ref WeaponChamberFromAttMag_W4T m_chamber private
Definition at line 9 of file RifleChambering.c.
m_chamber [2/4]
ref WeaponChamberFromAttMag_W4T m_chamber private
Definition at line 121 of file WeaponAttachMagazine.c.
m_chamber [3/4]
ref WeaponChambering_Base m_chamber private
Definition at line 936 of file WeaponChambering.c.
m_chamber [4/4]
ref WeaponChamberFromInnerMag_W4T m_chamber private
Definition at line 204 of file WeaponCharging.c.
m_chamberFromInnerMag
ref WeaponChamberFromInnerMag_W4T m_chamberFromInnerMag private
Definition at line 284 of file WeaponChamberingLooped.c.
m_damage
float m_damage private
Definition at line 22 of file WeaponChambering.c.
m_detach
ref DetachOldMagazine m_detach private
Definition at line 344 of file WeaponReplacingMagAndChamberNext.c.
m_dst
ref InventoryLocation m_dst private
magazine that will be detached
detached magazine
Definition at line 9 of file WeaponDetachingMag.c.
Referenced by OnEntry().
m_dstMagazine
Magazine m_dstMagazine private
Definition at line 5 of file RifleReChambering.c.
Referenced by OnEntry().
m_dtAccumulator
float m_dtAccumulator private
Definition at line 6 of file WeaponFireAndChamberNext.c.
Referenced by OnEntry().
m_eje
ref WeaponEjectBullet m_eje private
source of the loaded cartridge
Definition at line 12 of file WeaponReChamber.c.
m_eject [1/5]
ref WeaponEjectCasing m_eject private
Definition at line 8 of file RifleChambering.c.
m_eject [2/5]
ref WeaponEjectBullet_Cartridge m_eject private
Definition at line 9 of file RifleReChambering.c.
m_eject [3/5]
ref WeaponEjectAllMuzzles m_eject private
Definition at line 934 of file WeaponChambering.c.
m_eject [4/5]
ref WeaponEjectBullet_Cartridge_W4T m_eject private
Definition at line 46 of file WeaponEjectBullet.c.
m_eject [5/5]
ref WeaponUnjamming_Cartridge_W4T m_eject private
Definition at line 176 of file WeaponUnjamming.c.
m_endActionType
int m_endActionType private
Definition at line 929 of file WeaponChambering.c.
m_endLoop
ref WeaponStartAction m_endLoop private
Definition at line 938 of file WeaponChambering.c.
m_fire [1/2]
ref WeaponFire m_fire private
Definition at line 7 of file WeaponFireAndChamberNext.c.
m_fire [2/2]
ref WeaponFireWithEject m_fire private
Definition at line 8 of file WeaponFireLast.c.
m_fsm
ref WeaponFSM m_fsm private
hierarchical parent state of this state (or null)
Definition at line 14 of file WeaponStateBase.c.
Referenced by AddTransition(), GetFSM(), HasFSM(), IsWaitingForActionFinish(), LoadCurrentFSMState(), OnAbort(), OnEntry(), OnUpdate(), ProcessEvent(), and SaveCurrentFSMState().
m_hideB
ref BulletHide_W4T m_hideB private
Definition at line 8 of file RifleEjectCasing.c.
m_hideM
ref MagazineHide_W4T m_hideM private
Definition at line 110 of file WeaponDetachingMag.c.
m_hideOld
ref OldMagazineHide m_hideOld private
Definition at line 345 of file WeaponReplacingMagAndChamberNext.c.
m_InternalID
int m_InternalID = -1 private
nested state machine (or null)
Definition at line 15 of file WeaponStateBase.c.
Referenced by GetInternalStateID(), and SetInternalStateID().
m_jamTime
float m_jamTime private
Definition at line 173 of file WeaponUnjamming.c.
Referenced by OnEntry().
m_loa
ref WeaponChambering m_loa private
Definition at line 13 of file WeaponReChamber.c.
m_magazine
Magazine m_magazine private
Definition at line 8 of file WeaponDetachingMag.c.
Referenced by OnEntry().
m_magazineType
string m_magazineType private
Definition at line 24 of file WeaponChambering.c.
m_newDst
ref InventoryLocation m_newDst private
magazine that will be detached
magazine that will be attached
new magazine from inventory that will be attached
magazine that will be dropped on abort
Definition at line 8 of file WeaponReplacingMagAndChamberNext.c.
m_newMagazine
Magazine m_newMagazine private
magazine that will be detached
Definition at line 3 of file WeaponAttachMagazine.c.
m_newSrc
ref InventoryLocation m_newSrc private
magazine that will be removed from inventory
Definition at line 4 of file WeaponAttachMagazine.c.
m_oldMagazine
Magazine m_oldMagazine private
Definition at line 7 of file WeaponReplacingMagAndChamberNext.c.
m_onBE
ref WeaponEjectBullet_Cartridge_W4T m_onBE private
Definition at line 200 of file WeaponCharging.c.
m_onBEFireOut
ref WeaponEjectCasing_W4T m_onBEFireOut private
Definition at line 201 of file WeaponCharging.c.
m_onCK
ref WeaponCharging_CK m_onCK private
Definition at line 122 of file WeaponAttachMagazine.c.
m_parentState
WeaponStateBase m_parentState private
weapon that this state relates to
Definition at line 13 of file WeaponStateBase.c.
Referenced by GetParentState(), SetParentState(), and WeaponStateBase().
m_rotate
ref WeaponCylinderRotate m_rotate private
Definition at line 935 of file WeaponChambering.c.
m_srcMagazine
Magazine m_srcMagazine private
destination of the ejected cartridge
Definition at line 5 of file RifleChambering.c.
Referenced by OnEntry().
m_srcMagazinePrevLocation
ref InventoryLocation m_srcMagazinePrevLocation private
source of the cartridge
Definition at line 373 of file WeaponChambering.c.
m_start [1/5]
ref WeaponStartAction m_start private
source of the cartridge
detached magazine destination
source of the loaded cartridge
Definition at line 7 of file RifleChambering.c.
m_start [2/5]
ref WeaponStartAction m_start private
Definition at line 6 of file RifleEjectCasing.c.
m_start [3/5]
ref WeaponCharging_Start m_start private
Definition at line 9 of file WeaponCharging.c.
m_start [4/5]
ref WeaponEjectBullet_Start m_start private
destination of the cartridge
Definition at line 45 of file WeaponEjectBullet.c.
m_start [5/5]
ref WeaponUnjamming_Start m_start private
Definition at line 175 of file WeaponUnjamming.c.
m_startActionType
int m_startActionType private
Definition at line 928 of file WeaponChambering.c.
m_store
ref WeaponDetachingMag_Store m_store private
Definition at line 109 of file WeaponDetachingMag.c.
m_swapMags
ref SwapOldAndNewMagazine m_swapMags private
Definition at line 346 of file WeaponReplacingMagAndChamberNext.c.
m_type
string m_type private
Definition at line 23 of file WeaponChambering.c.
m_w4sb2
ref LoopedChambering_Wait4ShowBullet2 m_w4sb2 private
Definition at line 937 of file WeaponChambering.c.
m_w4t [1/2]
ref WeaponChambering_W4T m_w4t private
Definition at line 10 of file RifleChambering.c.
m_w4t [2/2]
ref WeaponUnjamming_W4T m_w4t private
Definition at line 177 of file WeaponUnjamming.c.
m_weapon
Weapon_Base m_weapon private
Definition at line 12 of file WeaponStateBase.c.
Referenced by AddTransition(), LoadCurrentFSMState(), OnAbort(), OnEntry(), OnExit(), SaveCurrentFSMState(), and WeaponStateBase().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Firearms/FSM/States/BulletHide.c
P:/scripts/4_World/Entities/Firearms/FSM/States/RifleChambering.c
P:/scripts/4_World/Entities/Firearms/FSM/States/RifleEjectCasing.c
P:/scripts/4_World/Entities/Firearms/FSM/States/RifleReChambering.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponAttachMagazine.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponChambering.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponChamberingLooped.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponCharging.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponDetachingMag.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponEjectBullet.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponEjectCasingAndChamberFromAttMag.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponFireAndChamberNext.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponFireAndChamberNextFromInnerMag.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponFireLast.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponReChamber.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponReplacingMagAndChamberNext.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponStartAction.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponStateBase.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponUnjamming.c
P:/scripts/4_World/Entities/Firearms/FSM/States/BulletShow.c
P:/scripts/4_World/Entities/Firearms/FSM/States/MagazineHide.c
P:/scripts/4_World/Entities/Firearms/FSM/States/MagazineShow.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponChamberFromAttMag.c