DayZ Scripts: UndergroundBunkerTrigger Class Reference
UndergroundBunkerTrigger Class Reference
Private Member Functions
void Init (UndergroundBunkerTriggerData data)
override protected void OnEnterClientEvent (TriggerInsider insider)
override protected void OnLeaveClientEvent (TriggerInsider insider)
Private Attributes
string m_LinkedDoorSelection
Member Function Documentation
Init()
void Init (UndergroundBunkerTriggerData data) inline private
References UndergroundBunkerTriggerData::m_LinkedDoorSelection, m_LinkedDoorSelection, m_Type, and UndergroundBunkerTriggerData::m_Type.
Referenced by Land_WarheadStorage_Main::SpawnTriggers().
OnEnterClientEvent()
override protected void OnEnterClientEvent (TriggerInsider insider) inline private
References TriggerInsider::GetObject().
OnLeaveClientEvent()
override protected void OnLeaveClientEvent (TriggerInsider insider) inline private
References TriggerInsider::GetObject().
Field Documentation
m_LinkedDoorSelection
string m_LinkedDoorSelection private
Referenced by UndergroundBunkerHandlerClient::CalculateEyeAccoTarget(), and Init().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ScriptedEntities/Triggers/UndergroundBunkerTrigger.c