DayZ Scripts: HandsArea Class Reference
HandsArea Class Reference
Private Member Functions
void HandsArea (LayoutHolder parent)
bool IsSwapActive ()
bool IsCombineActive ()
override ScrollWidget GetScrollWidget ()
override void UpdateSelectionIcons ()
override void UpdateInterval ()
override void SetLayoutName ()
override void SetParentWidget ()
override void OnShow ()
override void Refresh ()
void DraggingOverHandsPanel (Widget w, int x, int y, Widget receiver)
void OnHandsPanelDropReceived (Widget w, int x, int y, Widget receiver)
Private Attributes
protected ScrollWidget m_Scroller
protected ref HandsContainer m_HandsContainer
protected ref SizeToChild m_HandsResizer
protected bool m_ShouldChangeSize = true
Detailed Description
Definition at line 1 of file HandsArea.c.
Constructor & Destructor Documentation
HandsArea()
void HandsArea (LayoutHolder parent) inline private
Definition at line 9 of file HandsArea.c.
References m_HandsContainer, m_HandsResizer, and m_Scroller.
Member Function Documentation
DraggingOverHandsPanel()
void DraggingOverHandsPanel (Widget w, int x, int y, Widget receiver) inline private
Definition at line 105 of file HandsArea.c.
References ItemManager::GetCenterDropzone(), GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), name, ColorManager::RED_COLOR, string::Replace(), and ColorManager::SetColor().
Referenced by DraggingOverHandsPanel().
GetScrollWidget()
override ScrollWidget GetScrollWidget () inline private
Definition at line 42 of file HandsArea.c.
References m_Scroller.
IsCombineActive()
bool IsCombineActive () inline private
Definition at line 32 of file HandsArea.c.
IsSwapActive()
bool IsSwapActive () inline private
Definition at line 22 of file HandsArea.c.
OnHandsPanelDropReceived()
void OnHandsPanelDropReceived (Widget w, int x, int y, Widget receiver) inline private
Definition at line 145 of file HandsArea.c.
References GetGame(), ItemPreviewWidget::GetItem(), CGame::GetPlayer(), GetPlayer(), name, and string::Replace().
Referenced by OnHandsPanelDropReceived().
OnShow()
override void OnShow () inline private
Definition at line 93 of file HandsArea.c.
References m_HandsContainer, and HandsContainer::OnShow().
Refresh()
override void Refresh () inline private
Definition at line 99 of file HandsArea.c.
References m_ShouldChangeSize, and UpdateSelectionIcons().
Referenced by Refresh(), and Reset().
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 83 of file HandsArea.c.
References WidgetLayoutName::HandsArea.
SetParentWidget()
override void SetParentWidget () inline private
Definition at line 88 of file HandsArea.c.
References m_Parent.
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 54 of file HandsArea.c.
References InventoryMenu(), m_HandsContainer, m_HandsResizer, m_Scroller, m_ShouldChangeSize, HandsContainer::UpdateInterval(), x, and y.
Referenced by UpdateInterval().
UpdateSelectionIcons()
override void UpdateSelectionIcons () inline private
Definition at line 47 of file HandsArea.c.
Referenced by Refresh().
Field Documentation
m_HandsContainer
protected ref HandsContainer m_HandsContainer private
Definition at line 4 of file HandsArea.c.
Referenced by HandsArea(), OnShow(), and UpdateInterval().
m_HandsResizer
protected ref SizeToChild m_HandsResizer private
Definition at line 5 of file HandsArea.c.
Referenced by HandsArea(), and UpdateInterval().
m_Scroller
protected ScrollWidget m_Scroller private
Definition at line 3 of file HandsArea.c.
Referenced by GetScrollWidget(), HandsArea(), and UpdateInterval().
m_ShouldChangeSize
protected bool m_ShouldChangeSize = true private
Definition at line 7 of file HandsArea.c.
Referenced by Refresh(), and UpdateInterval().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Areas/HandsArea.c