DayZ Scripts: Debug Class Reference
Debug Class Reference
Static Private Member Functions
static string GetDebugName (Managed entity)
static void InitCanvas ()
static void ClearCanvas ()
static void CanvasDrawLine (float x1, float y1, float x2, float y2, float width, int color)
static void CanvasDrawPoint (float x1, float y1, int color)
Draws a "point" on the screen at x,y coordinates Debug.ClearCanvas(); for(int i = 0; i < 700;i++) { float val = i/700; float y = Easing.EaseInOutExpo(val); Debug.CanvasDrawPoint(i,y*700,ARGBF(0.6, 1, 1, 1)); }.
static void Init ()
static void DestroyAllShapes ()
static void RemoveShape (out Shape shape)
static void Log (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message with normal prio.
static void ActionLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void SymptomLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void InventoryMoveLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void InventoryReservationLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void InventoryHFSMLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void BleedingChancesLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void TriggerLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void ParticleLog (string message=LOG_DEFAULT, Managed caller=null, string function="", Managed entity=null)
static void TFLog (string message=LOG_DEFAULT, TestFramework caller=null, string function="")
static void WeightLog (string message=LOG_DEFAULT, Managed caller=null, string function="", Managed entity=null)
static void MeleeLog (Entity entity, string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT)
static void WeatherLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void LogInfo (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message with normal prio.
static void LogWarning (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message as warning message.
static void LogError (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message as error message.
static void LogArrayInt (array< int > arr=NULL, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void LogArrayString (array< string > arr=NULL, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void ReceivedLogMessageFromServer (string message)
static void ClearScriptLogs ()
static Shape DrawBox (vector pos1, vector pos2, int color=0x1fff7f7f)
static Shape DrawBoxEx (vector pos1, vector pos2, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.NOZWRITE)
static Shape DrawCube (vector pos, float size=1, int color=0x1fff7f7f)
static Shape DrawSphere (vector pos, float size=1, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE)
static Shape DrawFrustum (float horizontalAngle, float verticalAngle, float length, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.WIREFRAME)
static Shape DrawCylinder (vector pos, float radius, float height=1, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE)
static array< Shape > DrawCone (vector pos, float lenght, float halfAngle, float offsetAngle, int color=0xFFFFFFFF, int flags=0)
static Shape DrawLine (vector from, vector to, int color=0xFFFFFFFF, int flags=0)
static Shape DrawLines (vector[] positions, int count, int color=0xFFFFFFFF, int flags=0)
static Shape DrawArrow (vector from, vector to, float size=0.5, int color=0xFFFFFFFF, int flags=0)
static void GetBaseConfigClasses (out TStringArray base_classes)
Returns some of base config classes strings like CfgVehicles, CfgWeapons, etc. for searching purposes.
static void GetFiltredConfigClasses (string search_string, out TStringArray filtered_classes, bool only_public=true)
Returns config classes containing search_string in name.
static private void LogMessage (string level, string plugin, string entity, string author, string label, string message)
DEPRECATED.
static private void SaveLog (string log_message)
static void ClearLogs ()
static string GetFileName ()
static private string GetDate ()
Static Private Attributes
static private const string LOG_DEBUG = "Debug"
static private const string LOG_DEBUG_ACTION = "Action"
static private const string LOG_DEBUG_SYMPTOM = "Symptom"
static private const string LOG_DEBUG_INV_MOVE = "Inv Move"
static private const string LOG_DEBUG_INV_RESERVATION = "Inv Rrsv"
static private const string LOG_DEBUG_INV_HFSM = "HFSM"
static private const string LOG_DEBUG_BLEEDING_CHANCES = "Bleeding"
static private const string LOG_DEBUG_TRIGGER = "Trigger"
static private const string LOG_DEBUG_PARTICLE = "Particle"
static private const string LOG_DEBUG_TF = "TestFramework"
static private const string LOG_DEBUG_WEIGHT = "Weight"
static private const string LOG_DEBUG_MELEE = "Melee"
static private const string LOG_DEBUG_WEATHER = "Weather"
static private const string LOG_INFO = "Info"
static private const string LOG_WARNING = "Warning"
static private const string LOG_ERROR = "Error"
static private const string LOG_DEFAULT = "n/a"
static private ref array< Shape > m_DebugShapes
static Widget m_DebugLayoutCanvas
static CanvasWidget m_CanvasDebug
static private bool m_EnabledLogs
Member Function Documentation
ActionLog()
static void ActionLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
References LOG_DEBUG_ACTION, and LogMessage().
Referenced by ActionManagerClient::ActionStart(), EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), AnimatedActionBase::Do(), AnimatedActionBase::End(), ActionInput::Init(), ActionInteractBaseCB::InitActionComponent(), ActionBaseCB::Interrupt(), ActionManagerClient::LockInventory(), OnActionEnd(), AnimatedActionBase::OnAnimationEvent(), ActionInteractBaseCB::OnAnimationEvent(), ActionContinuousBase::OnEndAnimationLoop(), ActionBaseCB::OnFinish(), ActionContinuousBase::OnFinishProgress(), ActionContinuousBase::OnStartAnimationLoop(), ActionManagerClient::ProcessActionInputEnd(), ActionManagerClient::ProcessActionRequestEnd(), ActionInput::SetInput(), SetupAction(), Start(), ActionManagerServer::StartDeliveredAction(), ActionManagerClient::UnlockInventory(), and ActionManagerServer::Update().
BleedingChancesLog()
static void BleedingChancesLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
References LOG_DEBUG_BLEEDING_CHANCES, and LogMessage().
Referenced by BleedChanceData::CalculateBleedChance(), and BleedingSourcesManagerBase::ProcessHit().
CanvasDrawLine()
static void CanvasDrawLine (float x1, float y1, float x2, float y2, float width, int color) inline static private
References InitCanvas(), and m_CanvasDebug.
Referenced by CanvasDrawPoint().
CanvasDrawPoint()
static void CanvasDrawPoint (float x1, float y1, int color) inline static private
Draws a "point" on the screen at x,y coordinates Debug.ClearCanvas(); for(int i = 0; i < 700;i++) { float val = i/700; float y = Easing.EaseInOutExpo(val); Debug.CanvasDrawPoint(i,y*700,ARGBF(0.6, 1, 1, 1)); }.
References CanvasDrawLine().
ClearCanvas()
static void ClearCanvas () inline static private
References m_CanvasDebug.
ClearLogs()
static void ClearLogs () inline static private
References CloseFile(), FileExist(), FPrintln(), GetFileName(), and OpenFile().
Referenced by ScriptConsoleEnfScriptTab::Clear(), ScriptConsoleOutputTab::Clear(), and ClearScriptLogs().
ClearScriptLogs()
static void ClearScriptLogs () inline static private
References ClearLogs().
DestroyAllShapes()
static void DestroyAllShapes () inline static private
References m_DebugShapes.
DrawArrow()
static Shape DrawArrow (vector from, vector to, float size = 0.5, int color = 0xFFFFFFFF, int flags = 0) inline static private
References m_DebugShapes, and Shape.
Referenced by Component::DebugDirectionDraw(), PluginBase::DrawDebugs(), DrawDebugShape(), SceneObject::EditorLineAdd(), and UIScriptedMenu::Update().
DrawBox()
static Shape DrawBox (vector pos1, vector pos2, int color = 0x1fff7f7f) inline static private
References DrawBoxEx().
Referenced by Component::DebugBBoxDraw(), Transport::DebugFreeAreaAtDoor(), EntityAI::DebugFreeAreaAtDoor(), DrawDebugCollisionBox(), and SceneObject::EditorShapeAdd().
DrawBoxEx()
static Shape DrawBoxEx (vector pos1, vector pos2, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP|ShapeFlags.NOZWRITE) inline static private
References m_DebugShapes, and Shape.
Referenced by DrawBox().
DrawCone()
static array< Shape > DrawCone (vector pos, float lenght, float halfAngle, float offsetAngle, int color = 0xFFFFFFFF, int flags = 0) inline static private
References Math3D::ConePoints(), Math::Cos(), DrawLine(), vector::Normalized(), Math::Sin(), and Vector().
DrawCube()
static Shape DrawCube (vector pos, float size = 1, int color = 0x1fff7f7f) inline static private
References m_DebugShapes, and Shape.
DrawCylinder()
static Shape DrawCylinder (vector pos, float radius, float height = 1, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE) inline static private
References m_DebugShapes, and Shape.
Referenced by PluginBase::DrawDebugs().
DrawFrustum()
static Shape DrawFrustum (float horizontalAngle, float verticalAngle, float length, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP|ShapeFlags.WIREFRAME) inline static private
References m_DebugShapes, and Shape.
DrawLine()
static Shape DrawLine (vector from, vector to, int color = 0xFFFFFFFF, int flags = 0) inline static private
DrawLine \nFlags:
ShapeFlags.NOZBUFFER
ShapeFlags.NOZUPDATE
ShapeFlags.DOUBLESIDE
ShapeFlags.WIREFRAME
ShapeFlags.TRANSP
ShapeFlags.ONCE
ShapeFlags.NOOUTLINE
ShapeFlags.NOCULL
References m_DebugShapes, and Shape.
Referenced by CalculateEyeAccoTarget(), DrawCone(), WeaponDebug::DrawLineOfFire(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), PluginBase::EditorUpdateRuler(), GatherSurfaces(), and GetMeleeTargetEx().
DrawLines()
static Shape DrawLines (vector[] positions, int count, int color = 0xFFFFFFFF, int flags = 0) inline static private
References m_DebugShapes, and Shape.
Referenced by WeaponDebug::OnPostFrameUpdate().
DrawSphere()
static Shape DrawSphere (vector pos, float size = 1, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE) inline static private
References m_DebugShapes, and Shape.
Referenced by CalculateEyeAccoTarget(), WeaponDebug::DrawBarrelMemoryPoints(), DrawDebugShape(), WeaponDebug::DrawEyePoint(), WeaponDebug::DrawLineOfFire(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), PluginBase::EditorUpdateRuler(), Hologram::GetProjectionEntityPosition(), PluginBase::OnUpdate(), and SpookyEventBase::Perform().
GetBaseConfigClasses()
static void GetBaseConfigClasses (out TStringArray base_classes) inline static private
Returns some of base config classes strings like CfgVehicles, CfgWeapons, etc. for searching purposes.
Parameters
base_classes out TStringArray Array containing some of base config classes
References CFG_AMMO, CFG_MAGAZINESPATH, CFG_NONAI_VEHICLES, CFG_SOUND_SETS, CFG_SOUND_SHADERS, CFG_SOUND_TABLES, CFG_SURFACES, CFG_VEHICLESPATH, CFG_WEAPONSPATH, and CFG_WORLDS.
Referenced by UIPopupScript::ClearHierarchy(), UIPopupScript::FindInHierarchy(), GetFiltredConfigClasses(), and ScriptConsoleConfigTab::Init().
GetDate()
static private string GetDate () inline static private
References GetHourMinuteSecond(), and GetYearMonthDay().
Referenced by LogMessage().
GetDebugName()
static string GetDebugName (Managed entity) inline static private
GetFileName()
static string GetFileName () inline static private
References CFG_FILE_SCRIPT_LOG_EXT.
Referenced by ClearLogs(), ScriptConsoleOutputTab::ReloadOutput(), and SaveLog().
GetFiltredConfigClasses()
static void GetFiltredConfigClasses (string search_string, out TStringArray filtered_classes, bool only_public = true) inline static private
Returns config classes containing search_string in name.
Parameters
search_string string String to search in class names
filtered_classes out TStringArray Array containing filtered classes based on search_string
only_public bool Set to true to return only public classes, set to false to return all filtered classes
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), string::Contains(), GetBaseConfigClasses(), GetGame(), and string::ToLower().
Init()
static void Init () inline static private
References m_DebugShapes.
Referenced by CGame::DayZGame().
InitCanvas()
static void InitCanvas () inline static private
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_CanvasDebug, and m_DebugLayoutCanvas.
Referenced by CanvasDrawLine().
InventoryHFSMLog()
static void InventoryHFSMLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
References LOG_DEBUG_INV_HFSM, and LogMessage().
Referenced by HandActionBase::Action(), HandEventBase::CanPerformEvent(), HandEventSwap::CanPerformEvent(), HandEventBase::CanPerformEventEx(), HandEventBase::CheckRequest(), HandEventSwap::CheckRequest(), HandEventBase::CheckRequestSrc(), HandGuardBase::GuardCondition(), HandGuardHasItemInEvent::GuardCondition(), HandleHandEvent(), HandleTakeToDst(), HandStateBase::OnAbort(), HandStateBase::OnEntry(), HandStartAction::OnEntry(), and HumanInventoryWithFSM::ProcessHandEvent().
InventoryMoveLog()
static void InventoryMoveLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
References LOG_DEBUG_INV_MOVE, and LogMessage().
Referenced by GameInventory::AddInventoryReservationEx(), GameInventory::ClearInventoryReservationEx(), GameInventory::ExtendInventoryReservationEx(), ForceSwapEntities(), HandleForceSwapEntities(), HandleSwapEntities(), HandleTakeToDst(), StoreInputForRemotes(), SwapEntities(), TakeToDst(), TryAcquireTwoInventoryJuncturesFromServer(), ValidateDestroy(), ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().
InventoryReservationLog()
static void InventoryReservationLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
References LOG_DEBUG_INV_RESERVATION, and LogMessage().
Referenced by CGame::AddInventoryJunctureEx(), CGame::ClearJunctureEx(), and TryAcquireTwoInventoryJuncturesFromServer().
Log()
static void Log (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message with normal prio.
Parameters
msg string Debug message for print
Returns
void None
Debug.Log("Hello World");
>> [Log]: Hello World;
References LOG_DEBUG, and LogMessage().
Referenced by InventoryItem::AddAction(), RecipeBase::ApplyModificationsResults(), Managed::BleedingIndicator(), PluginRecipesManagerBase::CallbackGenerateCache(), ChangePPEMaterial(), CheckContactCache(), PlayerSpawnHandler::CreateChildItem(), PPEManagerStatic::CreateManagerStatic(), DamageCrew(), Debug(), RecipeBase::Do(), ScriptConsoleItemsTab::DrawItems(), SpookyArea::EEInit(), EOnPostSimulate(), KeysToUIElements::GetKeyToUIElement(), GetName(), PlayerSpawnPreset::GetRandomCharacterType(), Managed::GetRequester(), Managed::GetRequester(), Managed::GetRequesterID(), Managed::GetRequesterTypename(), LogTemplates::GetTemplate(), GetValue(), ManBase::HideHairSelections(), MissionBase::InvokeOnConnect(), MissionBase::InvokeOnDisconnect(), PlayerSpawnPreset::IsValid(), IsValid(), PlayerSpawnPresetDiscreteItemSetSlotData::IsValid(), MessageReceiverBase::Log(), Entity::Log(), PluginBase::Log(), Environment::LogDryWetProcess(), BloodTypes::MatchBloodCompatibility(), Entity::OnAction(), ManBase::OnConnect(), OnContact(), ManBase::OnDisconnect(), MissionBase::OnEvent(), ActionDigInStash::OnFinishProgressServer(), Icon::OnPerformRecipe(), ManBase::OnReconnect(), DayZPlayer::OnSoundEvent(), DayZPlayer::OnStepEvent(), OpenAndSwitchLambda::OnSuccess(), OnUpdate(), RecipeBase::PerformRecipe(), MissionBase::PlayerControlDisable(), PlayerAgentPool::PrintAgents(), PrintOut(), PluginRecipesManagerBase::PrintResultMasks(), ItemBase::PrintSlots(), PlayerSpawnHandler::ProcessCargoEquipment(), PlayerSpawnHandler::ProcessSlotsEquipment(), InventoryLocation::ReadFromContext(), GameplayEffectsData::RegisterData(), KeysToUIElements::RegisterKeyToUIElement(), LogTemplates::RegisterLogTamplate(), Managed::RegisterRequester(), PluginBase::Repair(), ManBase::Save(), PPERequesterBase::SetRequesterUpdating(), SetRequestUpdating(), SetupAnimation(), PlayerSpawnHandler::SpawnComplexChildrenItems(), PlayerSpawnHandler::SpawnDiscreteSlotItemSet(), RecipeBase::SpawnItems(), PlayerSpawnHandler::SpawnSimpleChildrenItems(), TranslateAndValidateSlot(), and Managed::VerifyRequester().
LogArrayInt()
static void LogArrayInt (array< int > arr = NULL, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
References string::Get(), LOG_DEBUG, LogMessage(), and string::ToString().
LogArrayString()
static void LogArrayString (array< string > arr = NULL, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
References string::Get(), LOG_DEBUG, and LogMessage().
Referenced by PrintOut().
LogError()
static void LogError (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message as error message.
Parameters
msg string Debug message for error print
Returns
void None
Debug.LogError("Hello World, this is error log");
>> [Error]: Hello World, this is error log
References LOG_ERROR, and LogMessage().
Referenced by EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), ActionCollectBloodTargetLambda::CopyOldPropertiesToNew(), TanLeatherLambda::CopyOldPropertiesToNew(), ReplaceItemWithNewLambda::CopyOldPropertiesToNew(), DeveloperFreeCamera::DisableFreeCamera(), DeveloperFreeCamera::EnableFreeCamera(), FireworksLauncherClientEvent::FireworksLauncherClientEvent(), Entity::GetDefaultHitComponent(), Entity::GetDefaultHitPosition(), Entity::GetDefaultHitPositionComponent(), Entity::GetHitComponentForAI(), FireworksLauncherClientEvent::GetShotPos(), Entity::GetSuitableFinisherHitComponents(), LogError(), Entity::LogError(), Component::LogErrorBadCompType(), Component::LogThisError(), Component::LogWarningAlredyExist(), Normalize(), OnStoreLoad(), SymptomManager::OnSymptomExit(), OpenItem::OpenAndSwitch(), PlaySound(), InventoryItem::SetQuantity(), and Tick().
LogInfo()
static void LogInfo (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message with normal prio.
Parameters
msg string Debug message for print
Returns
void None
Debug.Log("Hello World");
>> [Log]: Hello World;
References LOG_INFO, and LogMessage().
Referenced by LogInfo().
LogMessage()
static private void LogMessage (string level, string plugin, string entity, string author, string label, string message) inline static private
DEPRECATED.
References CALL_ID_SEND_LOG, CallMethod(), string::Format(), GetDate(), GetGame(), LogManager::IsLogsEnable(), CGame::IsMultiplayer(), CGame::IsServer(), and SaveLog().
Referenced by ActionLog(), BleedingChancesLog(), InventoryHFSMLog(), InventoryMoveLog(), InventoryReservationLog(), Log(), LogArrayInt(), LogArrayString(), LogError(), LogInfo(), LogWarning(), MeleeLog(), ParticleLog(), SymptomLog(), TFLog(), TriggerLog(), and WeatherLog().
LogWarning()
static void LogWarning (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message as warning message.
Parameters
msg string Debug message for warning print
Returns
void None
Debug.LogWarning("Hello World, this is warning log");
>> [Warning]: Hello World, this is warning log
References LOG_WARNING, and LogMessage().
Referenced by Entity::CanDisplayAttachmentSlot(), Component::LogThisWarning(), LogWarning(), Entity::LogWarning(), and DeveloperTeleport::TeleportAtCursor().
MeleeLog()
static void MeleeLog (Entity entity, string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT) inline static private
References GetDebugName(), LOG_DEBUG_MELEE, and LogMessage().
ParticleLog()
static void ParticleLog (string message = LOG_DEFAULT, Managed caller = null, string function = "", Managed entity = null) inline static private
References GetDebugName(), LOG_DEBUG_PARTICLE, and LogMessage().
Referenced by PMTF::PrintActiveStats(), PMTF::PrintPMStats(), TestInvalidSize(), and TestOwnership().
ReceivedLogMessageFromServer()
static void ReceivedLogMessageFromServer (string message) inline static private
References LogManager::IsLogsEnable(), and SaveLog().
Referenced by PluginBase::OnRPCServerLogRecieved().
RemoveShape()
static void RemoveShape (out Shape shape) inline static private
References m_DebugShapes, and Shape.
Referenced by PluginBase::CleanupDebugShapes(), WeaponDebug::DrawLineOfFire(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), WeaponDebug::RemoveAllShapes(), and RemoveDebugShape().
SaveLog()
static private void SaveLog (string log_message) inline static private
References CALL_ID_SCR_CNSL_ADD_PRINT, Dispatcher::CallMethod(), CloseFile(), FPrintln(), GetDispatcher(), GetFileName(), OpenFile(), CachedObjectsParams::PARAM1_STRING, and Print().
Referenced by LogMessage(), and ReceivedLogMessageFromServer().
SymptomLog()
static void SymptomLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
References LOG_DEBUG_SYMPTOM, and LogMessage().
Referenced by SymptomBase::OnGetActivatedClient(), SymptomBase::OnGetActivatedServer(), SymptomBase::OnGetDeactivatedClient(), and SymptomBase::OnGetDeactivatedServer().
TFLog()
static void TFLog (string message = LOG_DEFAULT, TestFramework caller = null, string function = "") inline static private
References GetDebugName(), LOG_DEBUG_TF, and LogMessage().
Referenced by TFModule::PrintResult(), EnProfilerTests::TestClassCountData(), EnProfilerTests::TestClassTimeData(), EnProfilerTests::TestFuncTimeData(), and EnProfilerTests::TestModule().
TriggerLog()
static void TriggerLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
References LOG_DEBUG_TRIGGER, and LogMessage().
Referenced by Trigger::AddInsider(), TriggerEvents::Enter(), TriggerEvents::Leave(), Trigger::RemoveInsider(), TriggerEvents::Stay(), TriggerEvents::StayFinish(), TriggerEvents::StayStart(), and Trigger::UpdateInsiders().
WeatherLog()
static void WeatherLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
References LogManager::IsWeatherLogEnabled(), LOG_DEBUG_WEATHER, and LogMessage().
Referenced by WorldData::WeatherOnBeforeChange().
WeightLog()
static void WeightLog (string message = LOG_DEFAULT, Managed caller = null, string function = "", Managed entity = null) inline static private
Field Documentation
LOG_DEBUG
private const string LOG_DEBUG = "Debug" static private
Referenced by Log(), LogArrayInt(), and LogArrayString().
LOG_DEBUG_ACTION
private const string LOG_DEBUG_ACTION = "Action" static private
Referenced by ActionLog().
LOG_DEBUG_BLEEDING_CHANCES
private const string LOG_DEBUG_BLEEDING_CHANCES = "Bleeding" static private
Referenced by BleedingChancesLog().
LOG_DEBUG_INV_HFSM
private const string LOG_DEBUG_INV_HFSM = "HFSM" static private
Referenced by InventoryHFSMLog().
LOG_DEBUG_INV_MOVE
private const string LOG_DEBUG_INV_MOVE = "Inv Move" static private
Referenced by InventoryMoveLog().
LOG_DEBUG_INV_RESERVATION
private const string LOG_DEBUG_INV_RESERVATION = "Inv Rrsv" static private
Referenced by InventoryReservationLog().
LOG_DEBUG_MELEE
private const string LOG_DEBUG_MELEE = "Melee" static private
Referenced by MeleeLog().
LOG_DEBUG_PARTICLE
private const string LOG_DEBUG_PARTICLE = "Particle" static private
Referenced by ParticleLog().
LOG_DEBUG_SYMPTOM
private const string LOG_DEBUG_SYMPTOM = "Symptom" static private
Referenced by SymptomLog().
LOG_DEBUG_TF
private const string LOG_DEBUG_TF = "TestFramework" static private
Referenced by TFLog().
LOG_DEBUG_TRIGGER
private const string LOG_DEBUG_TRIGGER = "Trigger" static private
Referenced by TriggerLog().
LOG_DEBUG_WEATHER
private const string LOG_DEBUG_WEATHER = "Weather" static private
Referenced by WeatherLog().
LOG_DEBUG_WEIGHT
private const string LOG_DEBUG_WEIGHT = "Weight" static private
LOG_DEFAULT
private const string LOG_DEFAULT = "n/a" static private
LOG_ERROR
private const string LOG_ERROR = "Error" static private
Referenced by LogError().
LOG_INFO
private const string LOG_INFO = "Info" static private
Referenced by LogInfo().
LOG_WARNING
private const string LOG_WARNING = "Warning" static private
Referenced by LogWarning().
m_CanvasDebug
CanvasWidget m_CanvasDebug static private
Referenced by CanvasDrawLine(), ClearCanvas(), and InitCanvas().
m_DebugLayoutCanvas
Widget m_DebugLayoutCanvas static private
Referenced by InitCanvas().
m_DebugShapes
private ref array<Shape> m_DebugShapes static private
Referenced by DestroyAllShapes(), DrawArrow(), DrawBoxEx(), DrawCube(), DrawCylinder(), DrawFrustum(), DrawLine(), DrawLines(), DrawSphere(), Init(), and RemoveShape().
m_EnabledLogs
private bool m_EnabledLogs static private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/Debug.c