DayZ Scripts: ActionPlugTargetIntoThis Class Reference
ActionPlugTargetIntoThis Class Reference
Private Member Functions
void ActionPlugTargetIntoThis ()
override void CreateConditionComponents ()
override bool Can (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool IsDeploymentAction ()
override void OnExecuteServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
void Process (ActionData action_data)
Private Attributes
bool m_Retoggle
Constructor & Destructor Documentation
ActionPlugTargetIntoThis()
void ActionPlugTargetIntoThis () inline private
References AnimatedActionBase::m_CommandUID, m_Retoggle, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References ItemBase::IsElectricAppliance().
Can()
override bool Can (PlayerBase player, ActionTarget target, ItemBase item) inline private
References m_Retoggle.
CreateConditionComponents()
override void CreateConditionComponents () inline private
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
IsDeploymentAction()
override bool IsDeploymentAction () inline private
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
References m_Retoggle.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
References Process().
Process()
void Process (ActionData action_data) inline private
References ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
Referenced by OnExecuteServer().
Field Documentation
m_Retoggle
bool m_Retoggle private
Referenced by ActionPlugTargetIntoThis(), Can(), and OnExecuteClient().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionPlugTargetIntoThis.c