DayZ Scripts: P:/scripts/3_Game/EffectManager.c File Reference
EffectManager.c File Reference
Data Structures
class SEffectManager
Manager class for managing Effect (EffectParticle, EffectSound)
class ParticleEffecterParameters
class ParticleEffecter
Functions
void EffecterParameters (string type, float lifespan)
void EffecterBase ()
void Init (int id, EffecterParameters parameters)
void DecreaseLifespan (float timeSlice)
void SetLifespan (float lifespan)
void Start ()
void Stop ()
void Reactivate ()
void Process ()
override int GetHideIconMask ()
void EffectParticleGeneral ()
void SetParticle (int particleID)
override void SetParticleID (int id)
Variables
class SEffectManager NONE = -1
class SEffectManager START = -1
class SEffectManager STOP = -1
class SEffectManager REACTIVATE0 = -1
class SEffectManager m_EffecterType = -1
float m_Lifespan
ParticleEffecterParameters NOT_DEFINED_LIFESPAN = -1
protected int m_ID
protected int m_Command = EffecterCommands.NONE
protected int m_CommandSync = EffecterCommands.NONE
ParticleEffecter m_LastParticleID
Function Documentation
DecreaseLifespan()
void DecreaseLifespan (float timeSlice)
References SEffectManager::DestroyEffecterParticleServer(), m_ID, m_Lifespan, and NOT_DEFINED_LIFESPAN.
EffecterBase()
void EffecterBase ()
Referenced by SEffectManager::Cleanup(), SEffectManager::CreateParticleServer(), SEffectManager::DestroyEffecterParticleServer(), SEffectManager::OnUpdate(), ActionFishingNew::PlaySplashEffectSynced(), SEffectManager::ReactivateParticleServer(), SEffectManager::ReinitParticleServer(), SEffectManager::StartParticleServer(), and SEffectManager::StopParticleServer().
EffecterParameters()
void EffecterParameters (string type, float lifespan)
References EffecterParameters(), m_EffecterType, and m_Lifespan.
Referenced by EffecterParameters().
EffectParticleGeneral()
void EffectParticleGeneral ()
Referenced by ParticleEffecter::OnVariablesSynchronized(), OnVariablesSynchronized(), and ~TreeEffecter().
GetHideIconMask()
override int GetHideIconMask ()
Init()
void Init (int id, EffecterParameters parameters)
References m_ID, and SetLifespan().
Process()
void Process ()
References GetGame(), and OnVariablesSynchronized().
Referenced by ActionDetachFromTarget::OnExecute(), ActionDetachPowerSourceFromPanel::OnExecuteClient(), ActionPlugIn::OnExecuteClient(), ActionDetachPowerSourceFromPanel::OnExecuteServer(), ActionPlantSeed::OnExecuteServer(), ActionPlugIn::OnExecuteServer(), ActionPlugTargetIntoThis::OnExecuteServer(), Reactivate(), ParticleEffecter::SetParticle(), SetRadius(), Start(), Stop(), and HeatComfortAnimHandler::Update().
Reactivate()
void Reactivate ()
References m_CommandSync, and Process().
SetLifespan()
void SetLifespan (float lifespan)
References m_Lifespan.
Referenced by Init().
SetParticle()
void SetParticle (int particleID)
References IsPlaying(), EffectParticle::SetParticleID(), EffectParticle::Start(), and EffectParticle::Stop().
SetParticleID()
override void SetParticleID (int id)
References m_LastParticleID.
Start()
void Start ()
References m_CommandSync, and Process().
Stop()
void Stop ()
References m_CommandSync, and Process().
Variable Documentation
m_Command
protected int m_Command = EffecterCommands.NONE
Referenced by ParticleEffecter::OnVariablesSynchronized(), and OnVariablesSynchronized().
m_CommandSync
protected int m_CommandSync = EffecterCommands.NONE
Referenced by ParticleEffecter::OnVariablesSynchronized(), OnVariablesSynchronized(), Reactivate(), Start(), and Stop().
m_EffecterType
class SEffectManager m_EffecterType = -1
Referenced by EffecterParameters().
m_ID
protected int m_ID
m_LastParticleID
ParticleEffecter m_LastParticleID
Referenced by SetParticleID().
m_Lifespan
protected float m_Lifespan
Referenced by DecreaseLifespan(), EffecterParameters(), and SetLifespan().
NONE
class SEffectManager NONE = -1
NOT_DEFINED_LIFESPAN
ParticleEffecterParameters NOT_DEFINED_LIFESPAN = -1
Referenced by DecreaseLifespan().
REACTIVATE0
class SEffectManager REACTIVATE0 = -1
START
class SEffectManager START = -1
STOP
class SEffectManager STOP = -1