DayZ Scripts: ParticleEffecter Class Reference
ParticleEffecter Class Reference
Private Member Functions
void ParticleEffecter (int lifespan)
override void Init (int id, EffecterParameters parameters)
void SetParticle (int particleID)
override void OnVariablesSynchronized ()
void ~ParticleEffecter ()
Private Attributes
protected int m_ParticleEffectID = -1
protected int m_ParticleEffectIDSync = -1
protected ref EffectParticleGeneral m_Effect = null
Constructor & Destructor Documentation
ParticleEffecter()
void ParticleEffecter (int lifespan) inline private
~ParticleEffecter()
void ~ParticleEffecter () inline private
References SEffectManager::DestroyEffect(), and m_Effect.
Member Function Documentation
Init()
override void Init (int id, EffecterParameters parameters) inline private
References ParticleEffecterParameters::m_ParticleID, and SetParticle().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References EffectParticleGeneral(), m_Command, m_CommandSync, m_Effect, m_ParticleEffectID, m_ParticleEffectIDSync, and SEffectManager::PlayInWorld().
SetParticle()
void SetParticle (int particleID) inline private
References m_ParticleEffectIDSync, and Process().
Referenced by Init().
Field Documentation
m_Effect
protected ref EffectParticleGeneral m_Effect = null private
Referenced by OnVariablesSynchronized(), and ~ParticleEffecter().
m_ParticleEffectID
protected int m_ParticleEffectID = -1 private
Referenced by OnVariablesSynchronized().
m_ParticleEffectIDSync
protected int m_ParticleEffectIDSync = -1 private
Referenced by OnVariablesSynchronized(), and SetParticle().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/EffectManager.c