DayZ Scripts: ScriptedWidgetEventHandler Class Reference
ScriptedWidgetEventHandler Class Reference
Widget UI system
map: item x vector(index, width, height)
Private Member Functions
bool OnClick (Widget w, int x, int y, int button)
bool OnModalResult (Widget w, int x, int y, int code, int result)
bool OnDoubleClick (Widget w, int x, int y, int button)
bool OnSelect (Widget w, int x, int y)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnFocus (Widget w, int x, int y)
bool OnFocusLost (Widget w, int x, int y)
bool OnMouseEnter (Widget w, int x, int y)
bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
bool OnMouseWheel (Widget w, int x, int y, int wheel)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnMouseButtonUp (Widget w, int x, int y, int button)
bool OnController (Widget w, int control, int value)
control is one of ControlID
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnKeyUp (Widget w, int x, int y, int key)
bool OnKeyPress (Widget w, int x, int y, int key)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnDrag (Widget w, int x, int y)
bool OnDragging (Widget w, int x, int y, Widget reciever)
bool OnDraggingOver (Widget w, int x, int y, Widget reciever)
bool OnDrop (Widget w, int x, int y, Widget reciever)
bool OnDropReceived (Widget w, int x, int y, Widget reciever)
bool OnResize (Widget w, int x, int y)
bool OnChildAdd (Widget w, Widget child)
bool OnChildRemove (Widget w, Widget child)
bool OnUpdate (Widget w)
bool OnEvent (EventType eventType, Widget target, int parameter0, int parameter1)
void OnWidgetScriptInit (Widget w)
bool ResizeParentToChild ()
bool ResizeParentToChild (out bool changed_size, int limit=-1, bool immedUpdate=true)
void ContextMenu ()
void ~ContextMenu ()
void Init (Widget layoutRoot)
void Show (int x, int y)
void ShowBackdrop (bool show)
void Hide ()
bool IsVisible ()
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
void Add (string label, Class obj, string fn_name, Param params)
void AddEx (string label, int labelColor, Class obj, string funcName, Param params)
void Remove (int index)
int Count ()
void Clear ()
void OnItemEnter (InventoryGrid grid, Widget w, int row, int col)
void OnItemLeave (InventoryGrid grid, Widget w)
void OnItemDrag (InventoryGrid grid, Widget w, int row, int col)
void OnItemDraggingOver (InventoryGrid grid, Widget w, int row, int col)
void OnItemDrop (InventoryGrid grid, Widget w, int row, int col)
void OnItemDropReceived (InventoryGrid grid, Widget w, int row, int col)
void OnItemClick (InventoryGrid grid, Widget w, int row, int col)
void OnItemLeftClick (InventoryGrid grid, Widget w, int row, int col)
void OnItemRightClick (InventoryGrid grid, Widget w, int row, int col)
void OnItemDoubleClick (InventoryGrid grid, Widget w, int row, int col)
int GetItemColor (ScriptedWidgetEventHandler grid, InventoryItem item)
int GetQuickbarItemColor (InventoryGrid grid, InventoryItem item)
vector GetItemSize (InventoryGrid grid, InventoryItem item)
string GetItemQuantityText (InventoryItem item)
int HasItemQuantity (InventoryItem item)
float GetItemQuantity (InventoryItem item)
int GetItemQuantityMax (InventoryItem item)
int GetItemCount (InventoryItem item)
bool CanAddItemInHandToInventory ()
void InventoryGrid ()
protected void OnWidgetScriptInit (Widget w)
bool CanAddItemInHandToInventory ()
override bool OnUpdate (Widget w)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnDrop (Widget w, int x, int y, Widget reciever)
int GetCol (Widget w)
int GetColFromBg (Widget w)
int GetGridSize ()
void SetGridSize (int size)
bool IsValidPos (int index)
override bool OnDrag (Widget w, int x, int y)
override bool OnDraggingOver (Widget w, int x, int y, Widget reciever)
override bool OnDropReceived (Widget w, int x, int y, Widget reciever)
TItemsMap GetItems ()
Widget GetItem (int index)
Widget GetItemBackground (int index)
Widget GetRoot ()
void SetItemColor (InventoryItem item, int color)
void SetController (InventoryGridController controller)
InventoryGridController GetController ()
void GenerateQuickBarBackgroundTiles (int count)
void UpdateQuickbarItems (TItemsMap items)
void UpdateItems (TItemsMap items, bool show_quantity, bool show_temperature)
void UpdateQuantityItems ()
void UpdateTemperatureItems ()
void RefreshQuickbarItemVariables (InventoryItem item, vector data)
void RefreshItemVariables (InventoryItem item, vector data, bool show_quantity, bool show_temperature)
void AddItem (InventoryItem item, vector data, vector rotation)
void SetItem (InventoryItem item, vector data, vector rotation)
protected void ResetItemWidget (Widget item_w, int width, int height)
void ResetItem (InventoryItem item)
bool HasItem (InventoryItem item)
void RemoveItem (InventoryItem item)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
void ActionTargetsCursor ()
void ~ActionTargetsCursor ()
void SetHealthVisibility (bool state)
void SetQuantityVisibility (bool state)
void SetInteractXboxIcon (string imageset_name, string image_name)
DEPRECATED.
void SetContinuousInteractXboxIcon (string imageset_name, string image_name)
void SetSingleXboxIcon (string imageset_name, string image_name)
void SetContinuousXboxIcon (string imageset_name, string image_name)
protected void SetXboxIcon (string name, string imageset_name, string image_name)
protected void SetControllerIcon (string pWidgetName, string pInputName)
protected void OnWidgetScriptInit (Widget w)
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
private void UpdateControllerInputIcons ()
Loads icons from the latest keybinds.
private void UpdatePCIconsVisibility ()
Contains logic for icon set switching (Gamepad/M&K)
protected void PrepareCursorContent ()
protected void BuildFixedCursor ()
protected void BuildFloatingCursor (bool forceRebuild)
override bool OnUpdate (Widget w)
protected void HideWidget ()
void Update ()
protected void ShowXboxHidePCIcons (string widget, bool show_xbox_icon)
protected vector TransformToScreenPos (vector pWorldPos)
transform world pos to screen pos (related to parent widget size)
protected void GetOnScreenPosition (out float x, out float y)
protected bool IsComponentInSelection (array< Selection > selection, string compName)
protected void GetPlayer ()
protected void GetActionManager ()
protected void GetActions ()
get actions from Action Manager
protected void GetTarget ()
protected string GetActionDesc (ActionBase action)
protected string GetItemDesc (ActionBase action)
protected int GetItemHealth ()
protected void GetItemQuantity (out int q_type, out float q_cur, out int q_min, out int q_max)
protected void GetItemCargoCount (out int cargoCount)
returns number of items in cargo for targeted entity
protected void SetItemDesc (string descText, int cargoCount, string itemWidget, string descWidget)
protected void SetItemHealth (int health, string itemWidget, string healthWidget, bool enabled)
protected void SetItemQuantity (int type, float current, int min, int max, string itemWidget, string quantityPBWidget, string quantityTextWidget, bool enabled)
protected void SetActionWidget (ActionBase action, string descText, string actionWidget, string descWidget)
protected void SetMultipleInteractAction (string multiActionsWidget, string multiActionsWidget_NotSelect)
shows arrows near the interact action if there are more than one available
protected void SetMultipleContinuousInteractAction (string multiActionsWidget, string multiActionsWidget_NotSelect)
protected void SetMultipleItemAction (string multiActionsWidget, string multiActionsWidget_NotSelect)
protected void SetMultipleContinuousItemAction (string multiActionsWidget, string multiActionsWidget_NotSelect)
protected void SetInteractActionIcon (string actionWidget, string actionIconFrameWidget, string actionIconWidget, string actionIconTextWidget)
protected void CheckRefresherFlagVisibility (Object object)
protected int AttachmentsWithInventoryOrCargoCount (notnull GameInventory inventory)
protected IngameHud GetHud ()
void CTEvent (int index, int actor, Widget root, bool walk, CameraToolsMenu parent)
void ~CTEvent ()
void Play ()
void Stop ()
bool IsTime (float start_time, float end_time)
void SetEventTime (float time)
void SetEventType (int type)
float GetEventTime ()
int GetEventType ()
int GetEventActor ()
bool GetEventWalk ()
void Select ()
void Unselect ()
void CTKeyframe (int index, vector pos, vector orient, float int_value, float fov, float dof, int pin, float time_before, Widget root, CameraToolsMenu parent)
void ~CTKeyframe ()
float GetInterpTime ()
void SetPin (int pin)
int GetPin ()
void SetFOV (float fov)
float GetFOV ()
void SetDOF (float dof)
float GetDOF ()
void SetPosition (vector pos)
void SetOrientation (vector orient)
vector GetPosition ()
vector GetOrientation ()
void SetTimeBefore (float time)
void SetInterpTime (float time)
void Select ()
void Unselect ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnFocus (Widget w, int x, int y)
bool IsFocusable (Widget w)
void ~CTObjectFollower ()
void CreateFollowedObject (string type)
void DestroyFollowedObject ()
void Update (float timeslice)
EntityAI GetObj ()
void SetPosition (vector position)
void SetRotation (vector dir)
vector GetPosition ()
vector GetRotation ()
void UpdatePos ()
Function updating the position of the tracker widget.
void Show ()
void Hide ()
void Fade (bool fade)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
void ContinuousActionProgress ()
void ~ContinuousActionProgress ()
protected void OnWidgetScriptInit (Widget w)
protected void Update ()
private void GetPlayer ()
private void GetActionManager ()
private void GetActions ()
private void SetProgress (float progress)
void HudDebugEventHandler (HudDebug hud_debug)
HudDebug GetHudDebug ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnSelect (Widget w, int x, int y)
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
override bool OnModalResult (Widget w, int x, int y, int code, int result)
override bool OnChange (Widget w, int x, int y, bool finished)
void PlayerListEntryScriptedWidget (Widget parent, string name, string uid, bool show_permissions, PlayerListScriptedWidget tab)
void ~PlayerListEntryScriptedWidget ()
Widget GetButtonWidget ()
void LoadPermissions (BiosPrivacyPermissionResultArray results)
string GetUID ()
bool IsMuted ()
bool IsGloballyMuted ()
void SetMute (bool mute)
void ToggleMute ()
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void Focus ()
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
bool IsLocalPlayer ()
void Select (bool notify=true)
void Deselect ()
void PlayerListScriptedWidget (Widget parent, string header_text="")
void ~PlayerListScriptedWidget ()
void FocusFirst ()
void Reload (SyncPlayerList player_list)
bool IsEmpty ()
void OnLoadServersAsync (ref GetServersResult result_list, EBiosError error, string response)
void Reload (BiosFriendInfoArray player_list)
void Reload (BiosPrivacyUidResultArray player_list)
void ReloadLocal (map< string, bool > player_list)
PlayerListEntryScriptedWidget FindEntryByWidget (Widget button)
string FindPlayerByWidget (Widget button)
void AddPlayer (string name, string UID, bool show_permissions)
void RemovePlayer (string UID)
bool IsMuted (string UID)
bool IsGloballyMuted (string UID)
void SetMute (string UID, bool mute)
void ToggleMute (string UID)
PlayerListEntryScriptedWidget GetSelectedPlayer ()
void SelectPlayer (PlayerListEntryScriptedWidget entry)
void ScrollToEntry (PlayerListEntryScriptedWidget entry)
void UpdateInterval ()
void SetLayoutName ()
void SetImmedUpdate ()
void OnSelectAction (ItemBase item, int actionId)
void ShowActionMenu (InventoryItem item)
void LayoutHolder (LayoutHolder parent)
void ~LayoutHolder ()
LayoutHolder GetRoot ()
void SetParentWidget ()
LayoutHolder GetParent ()
void SetActive (bool active)
void SetLastActive ()
void SetFirstActive ()
bool IsActive ()
Widget GetMainWidget ()
Widget GetRootWidget ()
bool IsDisplayable ()
bool IsVisible ()
void OnShow ()
void OnHide ()
void Refresh ()
void InspectItem (EntityAI item)
void UpdateSelectionIcons ()
void PrepareOwnedTooltip (EntityAI item, int x=0, int y=0)
void PrepareOwnedSlotsTooltip (Widget w, string name, string desc, int x=0, int y=0)
void HideOwnedTooltip ()
void HideOwnedSlotsTooltip ()
void ItemActionsWidget ()
void ~ItemActionsWidget ()
void SetInteractXboxIcon (string imageset_name, string image_name)
DEPRECATED.
void SetContinuousInteractXboxIcon (string imageset_name, string image_name)
void SetSingleXboxIcon (string imageset_name, string image_name)
void SetContinuousXboxIcon (string imageset_name, string image_name)
protected void SetXboxIcon (string name, string imageset_name, string image_name)
protected void SetControllerIcon (string pWidgetName, string pInputName)
protected void ShowXboxHidePCIcons (string widget, bool show_xbox_icon)
protected void OnWidgetScriptInit (Widget w)
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
private void UpdateControllerInputIcons ()
Loads icons from the latest keybinds.
private void UpdatePCIconsVisibility ()
Contains logic for icon set switching (Gamepad/M&K)
protected void BuildCursor ()
protected void Update ()
protected void GetPlayer ()
protected void GetActionManager ()
protected void GetActions ()
protected void GetEntityInHands ()
protected string GetActionDesc (ActionBase action)
protected string GetItemDesc (EntityAI entity)
protected int GetItemHealth ()
protected void GetItemQuantity (out int q_type, out float q_cur, out int q_min, out int q_max)
protected string GetRadioFrequency ()
protected void SetItemDesc (EntityAI entity, string descText, string itemWidget, string descWidget)
protected void SetItemHealth (int health, string itemWidget, string healthWidget, bool enabled)
protected void SetItemQuantity (int type, float current, int min, int max, string itemWidget, string quantityPBWidget, string quantityTextWidget, bool enabled)
protected void SetWeaponQuantity (int chamber, int mag, string itemWidget, string quantityPBWidget, string quantityTextWidget, bool enabled)
protected void SetWeaponModeAndZeroing (string itemWidget, string upWidget, string downWidget, bool enabled)
protected string WeaponModeTextTemp ()
protected void SetRadioFrequency (string freq, string itemWidget, string upWidget, string downWidget, bool enabled)
protected void SetActionWidget (ActionBase action, string descText, string actionWidget, string descWidget)
protected void SetMultipleInteractAction (string multiActionsWidget)
shows arrows near the interact action if there are more than one available
protected void SetMultipleContinuousInteractAction (string multiActionsWidget)
shows arrows near the interact action if there are more than one available
protected void SetMultipleItemAction (string multiActionsWidget)
protected void SetMultipleContinuousItemAction (string multiActionsWidget)
shows arrows near the interact action if there are more than one available
protected void SetInteractActionIcon (string actionWidget, string actionIconFrameWidget, string actionIconWidget, string actionIconTextWidget)
protected void CheckRefresherFlagVisibility ()
protected void CheckForActionWidgetOverrides ()
protected IngameHud GetHud ()
void TutorialKeybinds (Widget parent, TutorialsMenu menu)
bool SetElementTitle (UAInput pInput, int iDeviceFlags, out string output)
assemble all active bindings at widget element
bool SetElementModifier (UAInput pInput, out string output)
Determine the active limiter of the bindings (currently unreliable, multiple limiters can be active on key combos!)
void ~TutorialKeybinds ()
string GetLayoutName ()
void CreditsElement (int index, Widget parent)
void DropdownPrefab (Widget root, string text="")
void RefreshContent ()
int AddElement (string text, Widget content=null)
void RemoveElement (int index)
void Close ()
void SetText (string text)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
void UiHintPanel (Widget parent_widget)
void ~UiHintPanel ()
private void LoadContentList ()
private void BuildLayout (Widget parent_widget)
private void PopulateLayout ()
private void SetHintHeadline ()
private void SetHintDescription ()
private void SetHintImage ()
private void SetHintPaging ()
private void RandomizePageIndex ()
private void ShowNextPage ()
private void ShowPreviousPage ()
private void StartSlideshow ()
private void SlideshowThread ()
private void StopSlideShow ()
private void RestartSlideShow ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void KeybindingElement (int key_index, Widget parent, KeybindingsGroup group)
string GetLayoutName ()
bool IsChanged ()
bool IsAlternateChanged ()
array< int > GetChangedBinds ()
array< int > GetChangedAlternateBinds ()
void SetElementTitle (ButtonWidget btnWidget, UAInput pInput, int iDeviceFlags)
void Reload ()
void Reload (array< int > custom_binds, bool is_alternate)
void StartEnteringKeybind ()
void CancelEnteringKeybind ()
void StartEnteringAlternateKeybind ()
void CancelEnteringAlternateKeybind ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void KeybindingElementNew (int key_index, Widget parent, KeybindingsContainer group)
string GetLayoutName ()
bool IsChanged ()
bool IsAlternateChanged ()
array< int > GetChangedBinds ()
array< int > GetChangedAlternateBinds ()
void SetElementTitle (ButtonWidget btnWidget, UAInput pInput, int iDeviceFlags)
void Reload ()
void Reload (array< int > custom_binds, bool is_alternate)
void StartEnteringKeybind ()
void CancelEnteringKeybind ()
void StartEnteringAlternateKeybind ()
void CancelEnteringAlternateKeybind ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void KeybindingsGroup (int index, Input input, Widget parent, KeybindingsMenu menu)
string GetLayoutName ()
void InitPresets (int index, Widget parent, Input input)
void OnSelectKBPreset (int index)
void OnSelectConsolePreset (int index)
void ReloadProfiles ()
void AddSubgroup (Widget parent, Input input)
void AddAction (int index, Widget parent, Input input)
void ReloadAction (int index)
bool IsEnteringKeyBind ()
void ClearKeybind (int key_index)
void ClearAlternativeKeybind (int key_index)
void StartEnteringKeybind (int key_index)
void CancelEnteringKeybind ()
void StartEnteringAlternateKeybind (int key_index)
void CancelEnteringAlternateKeybind ()
bool IsChanged ()
void Apply ()
void Reset ()
void ResetEx (bool forced=false)
void Update (float timeslice)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
void MainMenuNewsfeed (Widget root)
void ShowNewsfeed ()
void HideNewsfeed ()
void OpenDLC ()
void OpenDiscord ()
void OpenFeedback ()
void OpenForums ()
void OpenTwitter ()
void OpenYoutube ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
void ColorRed (Widget w, int x, int y)
void ColorWhite (Widget w, Widget enterW, int x, int y)
void MainMenuStats (Widget root)
void ShowStats ()
void HideStats ()
void UpdateStats ()
protected string GetTimeString (float total_time)
protected string GetDistanceString (float total_distance, bool meters_only=false)
protected string GetValueString (float total_value, bool show_decimals=false)
void ModsMenuDetailed (array< ref ModInfo > data, Widget parent, ModsMenuTooltip tooltip, UIScriptedMenu menu_parent)
void ~ModsMenuDetailed ()
void Open ()
void Close ()
bool IsOpen ()
ModInfo GetHighlighted ()
void HighlightFirst ()
void Highlight (ModInfo mod_ref)
void ScrollToMod (ModInfo mod_ref)
void Select (ModInfo mod_ref, bool show)
void PrepareTooltip (ModInfo mod_ref)
void ShowTooltip ()
void HideTooltip ()
void LoadEntries (array< ref ModInfo > data)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
void ModsMenuDetailedEntry (ModInfo data, Widget parent, ModsMenuDetailed parent_menu)
void ~ModsMenuDetailedEntry ()
Widget GetWidget ()
void Select ()
void Deselect ()
void LoadData ()
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void ModsMenuSimple (array< ref ModInfo > data, Widget parent, ModsMenuDetailed detail_menu)
void ~ModsMenuSimple ()
void LoadEntries (array< ref ModInfo > data)
void Select (ModInfo mod)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
void ModsMenuSimpleEntry (ModInfo data, int index, Widget parent, ModsMenuSimple parent_menu)
void ~ModsMenuSimpleEntry ()
void LoadData ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
void ModsMenuTooltip (Widget parent)
void ~ModsMenuTooltip ()
void ShowTooltip (ModInfo mod_ref)
void HideTooltip ()
void OptionsMenuControls (Widget parent, Widget details_root, GameOptions options, OptionsMenu menu)
string GetLayoutName ()
void EnterKeybindingMenu ()
void Focus ()
Focuses the first viable item.
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
bool TextMapUpdateWidget (int key)
bool IsChanged ()
void Apply ()
void Revert ()
void SetToDefaults ()
void UpdateMouseInvertView (int index)
void UpdateMouseVSensitivity (float value)
void UpdateMouseHSensitivity (float value)
void UpdateMouseAimModVSensitivity (float value)
void UpdateMouseAimModHSensitivity (float value)
void ReloadOptions ()
void SetOptions (GameOptions options)
void ToggleDependentOptions (int mode, bool state)
void InitDependentOptionsVisibility ()
void FillTextMap ()
void ColorRed (Widget w)
void ColorWhite (Widget w, Widget enterW)
void OptionsMenuGame (Widget parent, Widget details_root, GameOptions options, OptionsMenu menu)
void ~OptionsMenuGame ()
string GetLayoutName ()
void Focus ()
bool IsChanged ()
void Apply ()
void Revert ()
void SetToDefaults ()
void ReloadOptions ()
void SetOptions (GameOptions options)
void ToggleDependentOptions (int mode, bool state)
void InitDependentOptionsVisibility ()
protected void UpdateLanguageOption (int new_index)
protected void UpdatePauseOption (int new_index)
protected void UpdateFOVOption (float new_value)
protected void UpdateHUDOption (int new_index)
protected void UpdateBleedingIndication (int new_index)
protected void UpdateConnectivityInfo (int newIndex)
protected void UpdateCrosshairOption (int new_index)
protected void UpdateQuickbarOption (int new_index)
protected void UpdateGameOption (int new_index)
protected void UpdateAdminOption (int new_index)
protected void UpdatePlayerOption (int new_index)
protected void UpdateServerInfoOption (int new_index)
IngameHud GetHud ()
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
protected void OnBleedingIndicationChanged (bool state)
bool TextMapUpdateWidget (int key)
void FillTextMap ()
void OptionsMenuSounds (Widget parent, Widget details_root, GameOptions options, OptionsMenu menu)
void ~OptionsMenuSounds ()
string GetLayoutName ()
void Focus ()
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
bool TextMapUpdateWidget (int key)
void OnVonStateEvent ()
void OnPartyChatChangedEvent ()
void UpdateWasMicCapturing ()
bool IsChanged ()
void Apply ()
void Revert ()
void SetToDefaults ()
void ReloadOptions ()
void SetOptions (GameOptions options)
void ToggleDependentOptions (int mode, bool state)
void InitDependentOptionsVisibility ()
void UpdateMaster (float value)
void UpdateEffects (float value)
void UpdateVOIP (float value)
void UpdateVOIPThreshold (float value)
void UpdateMusic (float value)
void UpdateInputMode (int newIndex)
void UpdateAudioLevel ()
void FillTextMap ()
void OptionsMenuVideo (Widget parent, Widget details_root, GameOptions options, OptionsMenu menu)
void ~OptionsMenuVideo ()
void InitSelectors ()
string GetLayoutName ()
void Focus ()
void ReloadOptions ()
bool IsChanged ()
void Apply ()
void Revert ()
void SetToDefaults ()
void SetOptions (GameOptions options)
void ToggleDependentOptions (int mode, bool state)
void InitDependentOptionsVisibility ()
void RefreshCustom ()
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void OnOptionChanged ()
void OnOverallQualityChanged (int value)
void OnDisplayModeChanged (int value)
void OnResolutionChanged (int value)
void OnBrightnessChanged (float value)
void OnVSyncChanged (float value)
void OnColorDepthChanged (int value)
void OnObjectDetailChanged (int value)
void OnTerrainDetailChanged (int value)
void OnTextureDetailChanged (int value)
void OnShadowDetailChanged (int value)
void OnTextureFilteringChanged (int value)
void OnTerrainSurfaceDetailChanged (int value)
void OnPPAAChanged (int value)
void OnHWAAChanged (int value)
void OnATOCChanged (int value)
void OnAOChanged (int value)
void OnPPQualityChanged (int value)
void OnSSRQualityChanged (int value)
override bool OnFocus (Widget w, int x, int y)
bool TextMapUpdateWidget (int key)
void FillTextMap ()
void ~OptionSelectorBase ()
Widget GetParent ()
bool IsFocusable (Widget w)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
void Focus ()
void Enable ()
void Disable ()
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ColorDisabled (Widget w)
void ButtonSetColor (Widget w, int color)
void ColorHighlightConsole (Widget w)
void ColorNormalConsole (Widget w)
void ColorDisabledConsole (Widget w)
void ButtonSetColorConsole (Widget w, int color)
void ButtonSetAlphaAnimConsole (Widget w)
void ButtonSetTextColorConsole (Widget w, int color)
void ServerBrowserEntry (Widget parent, int index, ServerBrowserTab tab)
void ~ServerBrowserEntry ()
Widget GetRoot ()
void Show (bool show)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void Focus ()
void ServerListFocus (bool focus)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsOnline ()
bool IsFocusable (Widget w)
void FillInfo (GetServersResultRow server_info)
void UpdateEntry ()
void SetName (string name)
void SetPasswordLocked (bool locked)
void SetPopulation (int population, int slots)
void SetSlots (int slots)
void SetPing (int ping)
void SetTime (string time, float multiplier)
void SetShard (int shard)
void SetMapName (string mapName)
void SetCharacterAlive (string char_alive)
void SetFriends (string friends_text)
void SetMode (int mode)
void SetBattleye (bool battleye)
void SetIP (string ip)
string GetIP ()
int GetPort ()
string GetServerID ()
string GetMapToRun ()
string GetMapName ()
void SetFavorite (bool favorite)
void SetAcceleration (float mult)
void SetModded (bool is_modded)
void SetServerMapName ()
void SetMods (array< string > mods)
void SetMouseAndKeyboard (bool is_mkenabled)
void SetIsOnline (bool isOnline)
bool ToggleFavorite ()
bool ToggleExpand ()
bool SetExpand (bool expand)
void Select (bool notify=true)
void Deselect ()
void UpdateColors ()
void Preview (Widget w, int x, int y)
void Darken (Widget w, int x, int y)
void Lighten (Widget w, Widget enterW, int x, int y)
void ServerBrowserFilterContainer (Widget root, ServerBrowserTab parent)
void OnFilterChanged ()
void LoadFilters ()
void SaveFilters ()
void ResetFilters ()
bool PingIsSet ()
bool FavoriteIsSet ()
bool PreviouslyIsSet ()
bool ProcessIntoIPAddress (out string potential_ip)
Removes all characters from the given string whirh are NOT a number, '.' or ':'. Returns true if any change was done to the input text.
bool LimitTextBoxCharacterCount (out string text, int max_length)
Limits the given text to 'max_length' character count. Returns true if any change was done to the input.
string GenerateValidIP (string potential_ip)
Attempts to generate a valid IP address & port from the given string in format like this: "192.168.0.2:2503". If the process fails, then an empty string is returned.
bool GenerateValidFilter (out string potential_filter)
Turns any given string into a more convenient filter (limits character count, forces lowercase, trims empty spaces).
void OnSortChanged (int value)
void Focus ()
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnFocus (Widget w, int x, int y)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
GetServersInput GetFilterOptionsPC ()
GetServersInput GetFilterOptionsConsoles ()
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
void Init ()
void OnWidgetScriptInit (Widget w)
void AlignTabbers ()
int AddTab (string name)
void RemoveTab (int index)
Widget GetTab (int index)
int GetTabCount ()
bool CanSwitchTab ()
void SetCanSwitch (bool value)
void PerformSwitchTab (int index)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnChildAdd (Widget w, Widget child)
override bool OnChildRemove (Widget w, Widget child)
void EnableTabControl (int index, bool enable)
void SelectTabControl (int index)
void SelectTabPanel (int index)
void DeselectTabControl (int index)
void DeselectTabPanel (int index)
void DeselectAll ()
void NextTab ()
void PreviousTab ()
int GetSelectedIndex ()
void RefreshTab (bool performInitAlignment=false)
protected void UpdateControlsElements ()
void DisableTabs (bool disable)
useful if we want to disable actual tabs for whatever reason
void ObjectFollower ()
void ~ObjectFollower ()
protected void OnWidgetScriptInit (Widget w)
void SetTarget (Object obj)
override bool OnUpdate (Widget w)
void Update ()
protected void GetOnScreenPosition (out float x, out float y)
void ~ProfileOptionsUI ()
void Attach (int profileOption, array< Widget > widget_array)
void Deattach ()
void Init ()
void SetValue ()
override bool OnClick (Widget w, int x, int y, int button)
void SetButtonStates (int index)
array< Widget > GetWidgetArray ()
int GetProfileOption ()
void ProjectedCrosshair ()
void ~ProjectedCrosshair ()
void OnWidgetScriptInit (Widget w)
protected void Update ()
Update.
protected void GetPlayer ()
protected void GetCrosshairPosition ()
Private Attributes
reference string m_ChildName
reference float m_HorizontalOffset
reference float m_VerticalOffset
reference bool m_ResizeHorizontal
reference bool m_ResizeVertical
protected Widget m_Root
protected Widget m_Child
private Widget m_context_menu_root_widget
private Widget m_context_menu_panel_widget
private ref array< ref CallQueueContext > m_commands
private int m_max_item_width
private int m_count
const int ITEMS_COUNT = 27
reference bool m_IsDebugOutput
protected ref map< int, Widget > m_BackgroundWidgets
protected ref map< int, Widget > m_ItemWidgets
protected ref TItemsMap m_Items
protected InventoryGridController m_Controller
protected int m_GridSize
protected bool m_IsMouseLeftDown
protected bool m_CanAddItemInHandToInventory
private Widget m_on_drag_item
private int m_col
PluginDayZInfectedDebug m_pPluginInfectedDebug
PluginItemDiagnostic m_Owner
protected PlayerBase m_Player
protected ActionTarget m_Target
protected ref ATCCachedObject m_CachedObject
protected Object m_DisplayInteractTarget
protected ActionBase m_Interact
protected ActionBase m_ContinuousInteract
protected ActionBase m_Single
protected ActionBase m_Continuous
protected ActionManagerClient m_AM
protected IngameHud m_Hud
protected UAIDWrapper m_UseActionWrapper
protected int m_InteractActionsNum
protected int m_ContinuousInteractActionsNum
protected int m_ItemActionsNum
protected int m_ContinuousItemActionsNum
protected m_SelectedActionCategory
protected bool m_HealthEnabled
protected bool m_QuantityEnabled
protected bool m_FixedOnPosition
protected bool m_Hidden
protected Widget m_Container
protected Widget m_ItemLeft
protected float m_MaxWidthChild
widget width
protected float m_RootWidth
protected float m_RootHeight
protected int m_Index
protected int m_ActorIndex
protected int m_EventType
protected float m_EventTime
protected CameraToolsMenu m_Menu
protected TextWidget m_IndexWidget
protected EditBoxWidget m_EventActorWidget
protected EditBoxWidget m_EventTimeWidget
protected EditBoxWidget m_EventTypeWidget
protected CheckBoxWidget m_EventWalkWidget
protected HumanCommandActionCallback m_Callback
protected float m_InterpTime
protected float m_TotalTimeBefore
protected vector m_Position
protected vector m_Orientation
protected EditBoxWidget m_InterpTimeWidget
protected EditBoxWidget m_FOVWidget
protected EditBoxWidget m_DOFWidget
protected EditBoxWidget m_PinWidget
protected TextWidget m_TotalTimeWidget
protected Widget m_FollowerRoot
protected Widget m_FollowerButton
protected EntityAI m_FollowedObject
protected float m_MaxFade
protected float m_MinFade
reference string RadialBarWidgetName
protected ActionBase m_Action
protected int m_ActionState
protected ActionManagerBase m_AM
protected ref WidgetFadeTimer m_FadeTimer
protected bool m_Faded
protected float m_InitProgress
protected float m_Speed
protected Widget m_RadialWidget
protected ImageWidget m_LoaderImage
ref RadialProgressBar m_Radial
HudDebug m_HudDebug
protected string m_Name
protected string m_UID
protected bool m_Mute
protected bool m_GlobalMute
protected TextWidget m_PlayerName
protected ImageWidget m_PlayerAvatar
protected ImageWidget m_MicrophoneIcon
protected ImageWidget m_MuteIcon
protected ButtonWidget m_PlayerButton
protected PlayerListScriptedWidget m_Tab
protected bool m_Selected
protected ScrollWidget m_ScrollContainer
protected Widget m_Content
protected ref map< string, ref PlayerListEntryScriptedWidget > m_Entries
protected int m_TotalEntries
protected PlayerListEntryScriptedWidget m_SelectedEntry
protected Widget m_MainWidget
protected Widget m_RootWidget
protected Widget m_ParentWidget
protected LayoutHolder m_Parent
protected string m_LayoutName
protected bool m_IsActive
protected bool m_ImmedUpdate
protected bool m_TooltipOwner
protected EntityAI m_am_entity1
protected EntityAI m_am_entity2
protected EntityAI m_EntityInHands
protected Widget m_DetailsRoot
protected TutorialsMenu m_Menu
protected Widget m_Parent
protected ScrollWidget m_Scroller
protected Widget m_ContentContainer
protected ref array< Widget > m_Content = new array<Widget>
protected Widget m_Button
protected Widget m_Holder
protected TextWidget m_Text
protected ImageWidget m_ImageExpand
protected ImageWidget m_ImageCollapse
protected bool m_IsExpanded
ref ScriptInvoker m_OnSelectItem = new ScriptInvoker()
private const int m_SlideShowDelay = 25000
private const string m_RootPath = "Gui/layouts/new_ui/hints/in_game_hints.layout"
private const string m_DataPath = "Scripts/data/hints.json"
private Widget m_RootFrame
private Widget m_SpacerFrame
private ButtonWidget m_UiLeftButton
private ButtonWidget m_UiRightButton
private RichTextWidget m_UiDescLabel
private TextWidget m_UiHeadlineLabel
private ImageWidget m_UiHintImage
private TextWidget m_UiPageingLabel
private ref array< ref HintPage > m_ContentList
private int m_PageIndex
protected KeybindingsGroup m_Group
protected TextWidget m_ElementName
protected TextWidget m_ElementModifier
protected ButtonWidget m_PrimaryBindButton
protected ButtonWidget m_AlternativeBindButton
protected Widget m_PrimaryClear
protected Widget m_AlternativeClear
protected int m_ElementIndex
protected bool m_IsEdited
protected bool m_IsAlternateEdited
protected ref array< int > m_CustomBind
protected ref array< int > m_CustomAlternateBind
protected ref Timer m_EntryTimer = new Timer(CALL_CATEGORY_GUI)
protected KeybindingsContainer m_Container
protected KeybindingsMenu m_Menu
protected ref map< int, ref KeybindingElement > m_KeyWidgets
protected int m_CurrentSettingKeyIndex = -1
protected int m_CurrentSettingAlternateKeyIndex = -1
protected ref DropdownPrefab m_KBDropdown
protected Widget m_DLDLC
protected Widget m_Discord
protected Widget m_Feedback
protected Widget m_DayZForum
protected Widget m_Twitter
protected Widget m_Youtube
protected TextWidget m_MainText1
protected TextWidget m_MainText2
protected TextWidget m_MainText3
protected TextWidget m_SecText1
protected TextWidget m_SecText2
protected TextWidget m_SecText3
protected Widget m_TimeSurvived
protected TextWidget m_TimeSurvivedValue
protected Widget m_PlayersKilled
protected TextWidget m_PlayersKilledValue
protected Widget m_InfectedKilled
protected TextWidget m_InfectedKilledValue
protected Widget m_DistanceTraveled
protected TextWidget m_DistanceTraveledValue
protected Widget m_LongRangeShot
protected TextWidget m_LongRangeShotValue
protected Widget m_CloseButton
protected ScrollWidget m_Scroll
protected ref map< ref ModInfo, ref ModsMenuDetailedEntry > m_Data
protected ModInfo m_Highlighted
protected UIScriptedMenu m_Menu
protected ModsMenuTooltip m_Tooltip
protected ref Timer m_TooltipTimer
protected ModInfo m_TooltipMod
protected Widget m_Detail
protected ImageWidget m_IconSmall
protected ImageWidget m_IconCollapse
protected TextWidget m_Name
protected ImageWidget m_IconBig
protected MultilineTextWidget m_Author
protected TextWidget m_Version
protected RichTextWidget m_ActionWebsite
protected RichTextWidget m_ActionPurchase
protected RichTextWidget m_Description
protected ModInfo m_Data
protected ModsMenuDetailed m_ParentMenu
protected bool m_IsOpen
protected Widget m_MoreButton
protected ref map< ModInfo, ref ModsMenuSimpleEntry > m_Data
protected ModsMenuDetailed m_DetailMenu
protected ButtonWidget m_ModButton
protected ImageWidget m_Icon
protected Widget m_Hover
protected bool m_HasLogoOver
protected ModsMenuSimple m_ParentMenu
protected RichTextWidget m_Text
protected Widget m_SettingsRoot
protected Widget m_DetailsBodyDefault
protected Widget m_DetailsBodyConnectivity
protected TextWidget m_DetailsLabel
protected RichTextWidget m_DetailsText
protected GridSpacerWidget m_Keybindings
protected GameOptions m_Options
protected OptionsMenu m_Menu
protected ref SwitchOptionsAccess m_KeyboardOption
protected ref SwitchOptionsAccess m_AimHelperOption
protected ref OptionSelectorMultistate m_KeyboardSelector
protected ref OptionSelectorMultistate m_AimHelperSelector
protected ref SwitchOptionsAccess m_Mouse_InvertOption
protected ref NumericOptionsAccess m_Mouse_VSensitivityOption
protected ref NumericOptionsAccess m_Mouse_HSensitivityOption
protected ref NumericOptionsAccess m_Mouse_AimMod_VSensitivityOption
protected ref NumericOptionsAccess m_Mouse_AimMod_HSensitivityOption
protected ref OptionSelectorMultistate m_Mouse_InvertSelector
protected ref OptionSelectorSlider m_Mouse_VSensitivitySelector
protected ref OptionSelectorSlider m_Mouse_HSensitivitySelector
protected ref OptionSelectorSlider m_Mouse_AimMod_VSensitivitySelector
protected ref OptionSelectorSlider m_Mouse_AimMod_HSensitivitySelector
protected ref NumericOptionsAccess m_ControllerLS_VSensitivityOption
protected ref NumericOptionsAccess m_ControllerLS_HSensitivityOption
protected ref NumericOptionsAccess m_ControllerLS_VehicleMod_HSensitivityOption
protected ref SwitchOptionsAccess m_ControllerRS_InvertOption
protected ref NumericOptionsAccess m_ControllerRS_VSensitivityOption
protected ref NumericOptionsAccess m_ControllerRS_HSensitivityOption
protected ref NumericOptionsAccess m_ControllerRS_CurvatureOption
protected ref NumericOptionsAccess m_ControllerRS_AimMod_VSensitivityOption
protected ref NumericOptionsAccess m_ControllerRS_AimMod_HSensitivityOption
protected ref NumericOptionsAccess m_ControllerRS_AimMod_CurvatureOption
protected ref OptionSelectorSlider m_ControllerLS_VSensitivitySelector
protected ref OptionSelectorSlider m_ControllerLS_HSensitivitySelector
protected ref OptionSelectorSlider m_ControllerLS_VehicleMod_HSensitivitySelector
protected ref OptionSelectorMultistate m_ControllerRS_InvertSelector
protected ref OptionSelectorSlider m_ControllerRS_VSensitivitySelector
protected ref OptionSelectorSlider m_ControllerRS_HSensitivitySelector
protected ref OptionSelectorSlider m_ControllerRS_CurvatureSelector
protected ref OptionSelectorSlider m_ControllerRS_AimMod_VSensitivitySelector
protected ref OptionSelectorSlider m_ControllerRS_AimMod_HSensitivitySelector
protected ref OptionSelectorSlider m_ControllerRS_AimMod_CurvatureSelector
protected ref map< int, ref Param2< string, string > > m_TextMap
protected ButtonWidget m_QuickbarButton
protected ref NumericOptionsAccess m_FOVOption
protected ref ListOptionsAccess m_LanguageOption
protected ref ListOptionsAccess m_PauseOption
protected ref OptionSelectorMultistate m_LanguageSelector
protected ref OptionSelectorSlider m_FOVSelector
protected ref OptionSelectorMultistate m_ShowHUDSelector
protected ref OptionSelectorMultistate m_ShowCrosshairSelector
protected ref OptionSelectorMultistate m_ShowQuickbarSelector
protected ref OptionSelectorMultistate m_ShowGameSelector
protected ref OptionSelectorMultistate m_ShowAdminSelector
protected ref OptionSelectorMultistate m_ShowPlayerSelector
protected ref OptionSelectorMultistate m_ShowServerInfoSelector
protected ref OptionSelectorMultistate m_BleedingIndication
protected ref OptionSelectorMultistate m_ConnectivityInfo
protected ref OptionSelectorMultistate m_PauseSelector
protected ref NumericOptionsAccess m_MasterOption
protected ref NumericOptionsAccess m_EffectsOption
protected ref NumericOptionsAccess m_VOIPOption
protected ref NumericOptionsAccess m_VOIPThresholdOption
protected ref NumericOptionsAccess m_MusicOption
protected ref ListOptionsAccess m_InputModeOption
protected ref OptionSelectorSlider m_MasterSelector
protected ref OptionSelectorSlider m_EffectsSelector
protected ref OptionSelectorSlider m_VOIPSelector
protected ref OptionSelectorLevelMarker m_VOIPThresholdSelector
protected ref OptionSelectorSlider m_MusicSelector
protected ref OptionSelectorMultistate m_InputModeSelector
protected ref Timer m_AudioLevelTimer
protected MissionGameplay m_MissionGameplay
protected VONManagerBase m_VonManager
private bool m_WasMicCapturing
protected ref OptionSelectorMultistate m_OverallQualitySelector
protected ref OptionSelectorMultistate m_DisplayModeSelector
protected ref OptionSelectorMultistate m_ResolutionSelector
protected ref OptionSelectorSlider m_BrightnessSelector
protected ref OptionSelectorMultistate m_VSyncSelector
protected ref OptionSelectorMultistate m_ObjectDetailSelector
protected ref OptionSelectorMultistate m_TerrainDetailSelector
protected ref OptionSelectorMultistate m_TextureDetailSelector
protected ref OptionSelectorMultistate m_ShadowDetailSelector
protected ref OptionSelectorMultistate m_TextureFilteringSelector
protected ref OptionSelectorMultistate m_TerrainSurfaceDetailSelector
protected ref OptionSelectorMultistate m_PPAASelector
protected ref OptionSelectorMultistate m_HWAASelector
protected ref OptionSelectorMultistate m_ATOCSelector
protected ref OptionSelectorMultistate m_AOSelector
protected ref OptionSelectorMultistate m_PPQualitySelector
protected ref OptionSelectorMultistate m_SSRQualitySelector
protected ref ListOptionsAccess m_OverallQualityOption
protected ref ListOptionsAccess m_DisplayModeOption
protected ref ListOptionsAccess m_ResolutionOption
protected ref NumericOptionsAccess m_BrightnessOption
protected ref ListOptionsAccess m_VSyncOption
protected ref ListOptionsAccess m_ObjectDetailOption
protected ref ListOptionsAccess m_TerrainDetailOption
protected ref ListOptionsAccess m_TextureDetailOption
protected ref ListOptionsAccess m_ShadowDetailOption
protected ref ListOptionsAccess m_TextureFilteringOption
protected ref ListOptionsAccess m_TerrainSurfaceDetailOption
protected ref ListOptionsAccess m_PPAAOption
protected ref ListOptionsAccess m_HWAAOption
protected ref ListOptionsAccess m_ATOCOption
protected ref ListOptionsAccess m_AOOption
protected ref ListOptionsAccess m_PPQualityOption
protected ref ListOptionsAccess m_SSRQualityOption
protected int m_SelectorType = 0
protected bool m_Enabled
protected ScriptedWidgetEventHandler m_ParentClass
ref ScriptInvoker m_OptionFocused = new ScriptInvoker
ref ScriptInvoker m_OptionUnfocused = new ScriptInvoker
ref ScriptInvoker m_AttemptOptionChange = new ScriptInvoker
ref ScriptInvoker m_OptionChanged = new ScriptInvoker
protected Widget m_Favorite
protected Widget m_Expand
protected TextWidget m_ServerName
protected TextWidget m_ServerPopulation
protected TextWidget m_ServerSlots
protected TextWidget m_ServerPing
protected ImageWidget m_ServerTime
protected ImageWidget m_ServerLock
protected ImageWidget m_ServerModIcon
protected ImageWidget m_ServerMaKIcon
protected TextWidget m_ServerShard
protected TextWidget m_ServerCharacterAlive
protected TextWidget m_ServerFriends
protected TextWidget m_ServerMode
protected TextWidget m_ServerBattleye
protected TextWidget m_ServerIP
protected TextWidget m_ServerAcceleration
protected TextWidget m_ServerMap
protected TextWidget m_ServerMods
protected ButtonWidget m_ServerModsExpand
protected ref array< string > m_Mods
protected bool m_IsFavorited
protected bool m_IsOnline
protected ref GetServersResultRow m_ServerData
protected ServerBrowserTab m_Tab
protected bool m_FirstExpand = true
ref map< string, string > m_Options = new map<string, string>
protected EditBoxWidget m_SearchByName
protected EditBoxWidget m_SearchByIP
ref OptionSelectorMultistate m_CharacterAliveFilter
ref OptionSelectorMultistate m_SortingFilter
ref OptionSelectorMultistate m_RegionFilter
ref OptionSelectorMultistate m_PingFilter
ref OptionSelector m_DLCFilter
ref OptionSelector m_FavoritedFilter
ref OptionSelector m_FriendsPlayingFilter
ref OptionSelector m_BattleyeFilter
ref OptionSelector m_PasswordFilter
ref OptionSelector m_WhitelistFilter
ref OptionSelector m_KeyboardFilter
ref OptionSelector m_PreviouslyPlayedFilter
ref OptionSelector m_VersionMatchFilter
ref OptionSelector m_FullServerFilter
ref OptionSelector m_ThirdPersonFilter
ref OptionSelector m_PublicFilter
ref OptionSelector m_AcceleratedTimeFilter
protected bool m_FirstInit = true
protected Widget m_TabControlsRoot
protected int m_TabsCount
protected ref map< int, Widget > m_TabControls
protected ref map< int, Widget > m_Tabs
protected int m_SelectedIndex
protected float m_ResolutionMultiplier
protected bool m_CanSwitch
ref ScriptInvoker m_OnTabSwitch = new ScriptInvoker()
ref ScriptInvoker m_OnAttemptTabSwitch = new ScriptInvoker()
ref Timer m_InitTimer
reference int m_PivotYOffset
protected Object m_TargetObject
protected bool m_Visible
int m_profileOption
Widget m_widget
ref array< Widget > m_widget_array
protected bool m_Debug
protected Weapon_Base m_Weapon
Static Private Attributes
static protected bool m_IgnoredBool
static int ITEM_COLOR_QUICKBAR_NORMAL = 0x0AFFFFFF
static int ITEM_COLOR_QUICKBAR_H_GOOD = 0x2A6e980d
static int ITEM_COLOR_QUICKBAR_H_BAD = 0x2A980d0d
static int ITEM_COLOR_QUICKBAR_I_BAD = 0x2A986e0d
static int ITEM_COLOR_NORMAL = 0x0AFFFFFF
static int ITEM_COLOR_DRAG = 0x0AFFFFFF
static const float SLIDER_STEP = 0.025
Detailed Description
map: item x vector(index, width, height)
Deprecated.
Definition at line 528 of file EnWidgets.c.
Constructor & Destructor Documentation
~ContextMenu()
void ~ContextMenu () inline private
Definition at line 17 of file ContextMenu.c.
References Clear(), and m_context_menu_root_widget.
~ActionTargetsCursor()
void ~ActionTargetsCursor () inline private
Definition at line 111 of file ActionTargetsCursor.c.
~CTEvent()
void ~CTEvent () inline private
Definition at line 38 of file CTEvent.c.
References m_Root.
~CTKeyframe()
void ~CTKeyframe () inline private
Definition at line 45 of file CTKeyframe.c.
References m_Root.
~CTObjectFollower()
void ~CTObjectFollower () inline private
Definition at line 15 of file CTObjectFollower.c.
~ContinuousActionProgress()
void ~ContinuousActionProgress () inline private
Definition at line 38 of file ContinuousActionProgress.c.
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Remove(), and Update().
~PlayerListEntryScriptedWidget()
void ~PlayerListEntryScriptedWidget () inline private
Definition at line 37 of file PlayerListEntryScriptedWidget.c.
References m_Root.
~PlayerListScriptedWidget()
void ~PlayerListScriptedWidget () inline private
Definition at line 22 of file PlayerListScriptedWidget.c.
References m_Root.
~LayoutHolder()
void ~LayoutHolder () inline private
Definition at line 113 of file LayoutHolder.c.
References m_RootWidget.
~ItemActionsWidget()
void ~ItemActionsWidget () inline private
Definition at line 57 of file ItemActionsWidget.c.
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Remove(), and Update().
~TutorialKeybinds()
void ~TutorialKeybinds () inline private
Definition at line 163 of file ControlMappingKeybinds.c.
~UiHintPanel()
void ~UiHintPanel () inline private
Definition at line 48 of file UiHintPanel.c.
References StopSlideShow().
~ModsMenuDetailed()
void ~ModsMenuDetailed () inline private
Definition at line 33 of file ModsMenuDetailed.c.
References m_Root.
~ModsMenuDetailedEntry()
void ~ModsMenuDetailedEntry () inline private
Definition at line 53 of file ModsMenuDetailedEntry.c.
References m_Root.
~ModsMenuSimple()
void ~ModsMenuSimple () inline private
Definition at line 19 of file ModsMenuSimple.c.
References m_Root.
~ModsMenuSimpleEntry()
void ~ModsMenuSimpleEntry () inline private
Definition at line 38 of file ModsMenuSimpleEntry.c.
References m_ModButton.
~ModsMenuTooltip()
void ~ModsMenuTooltip () inline private
Definition at line 12 of file ModsMenuTooltip.c.
References m_Root.
~OptionsMenuGame()
void ~OptionsMenuGame () inline private
Definition at line 135 of file OptionsMenuGame.c.
References g_Game.
~OptionsMenuSounds()
void ~OptionsMenuSounds () inline private
Definition at line 111 of file OptionsMenuSounds.c.
References CGame::EnableMicCapture(), GetGame(), VONManagerBase::m_OnPartyChatChangedEvent, VONManagerBase::m_OnVonStateEvent, and ScriptInvoker::Remove().
~OptionsMenuVideo()
void ~OptionsMenuVideo () inline private
Definition at line 137 of file OptionsMenuVideo.c.
References CGame::EndOptionsVideo(), and GetGame().
~OptionSelectorBase()
void ~OptionSelectorBase () inline private
Definition at line 16 of file OptionSelectorBase.c.
References m_Root.
~ServerBrowserEntry()
void ~ServerBrowserEntry () inline private
Definition at line 87 of file ServerBrowserEntry.c.
References m_Root.
~ObjectFollower()
void ~ObjectFollower () inline private
Definition at line 15 of file ObjectFollower.c.
~ProfileOptionsUI()
void ~ProfileOptionsUI () inline private
Definition at line 3 of file ProfileOptionsUI.c.
References Deattach().
~ProjectedCrosshair()
void ~ProjectedCrosshair () inline private
Definition at line 21 of file ProjectedCrosshair.c.
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Remove(), and Update().
Member Function Documentation
ActionTargetsCursor()
void ActionTargetsCursor () inline private
Definition at line 88 of file ActionTargetsCursor.c.
References GetGame(), GetHud(), UAInputAPI::GetInputByID(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), UAInput::GetPersistentWrapper(), GetUApi(), ScriptInvoker::Insert(), m_AM, m_Hud, OnInputDeviceChanged(), and OnInputPresetChanged().
Add()
void Add (string label, Class obj, string fn_name, Param params) inline private
Definition at line 161 of file ContextMenu.c.
References AddEx().
AddAction()
void AddAction (int index, Widget parent, Input input) inline private
Definition at line 105 of file KeybindingsGroup.c.
References KeybindingElement().
Referenced by AddSubgroup().
AddElement()
int AddElement (string text, Widget content = null) inline private
Definition at line 64 of file DropdownPrefab.c.
References GetGame(), and m_Root.
Referenced by array::AddSubgroup().
AddEx()
void AddEx (string label, int labelColor, Class obj, string funcName, Param params) inline private
Definition at line 166 of file ContextMenu.c.
References Count(), string::Length(), and string::ToUpper().
Referenced by Add().
AddItem()
void AddItem (InventoryItem item, vector data, vector rotation) inline private
Definition at line 650 of file InventoryGrid.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), ItemPreviewWidget::GetItem(), GetItemBackground(), CGame::GetWorkspace(), RefreshItemVariables(), ResetItemWidget(), Math::Round(), ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetModelOrientation(), and ItemPreviewWidget::SetView().
Referenced by UpdateItems(), and UpdateQuickbarItems().
AddPlayer()
void AddPlayer (string name, string UID, bool show_permissions) inline private
Definition at line 175 of file PlayerListScriptedWidget.c.
References name, PlayerListEntryScriptedWidget(), and UID.
Referenced by Reload().
AddSubgroup()
void AddSubgroup (Widget parent, Input input) inline private
Definition at line 87 of file KeybindingsGroup.c.
References AddAction(), WorkspaceWidget::CreateWidgets(), UAInputAPI::GetActiveInputs(), GetGame(), GetUApi(), and CGame::GetWorkspace().
Referenced by array::CreateSubgroups(), and KeybindingsGroup().
AddTab()
int AddTab (string name) inline private
Definition at line 161 of file TabberUI.c.
References AlignTabbers(), WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Root, and name.
AlignTabbers()
void AlignTabbers () inline private
Definition at line 108 of file TabberUI.c.
References m_ResolutionMultiplier, x, and y.
Referenced by AddTab(), EnableTabControl(), Init(), NextTab(), OnChildAdd(), OnChildRemove(), PerformSwitchTab(), and PreviousTab().
Apply() [1/5]
void Apply () inline private
Definition at line 177 of file KeybindingsGroup.c.
References UAInput::AddAlternative(), UAInput::AlternativeCount(), UAInput::BindComboByHash(), UAInput::ClearDeviceBind(), UAInputAPI::GetInputByID(), and GetUApi().
Apply() [2/5]
void Apply () inline private
Definition at line 357 of file OptionsMenuControls.c.
References Input::EnableMouseAndKeyboard(), Focus(), g_Game, GetGame(), CGame::GetInput(), CGame::GetUIManager(), m_Menu, and UIManager::ShowUICursor().
Apply() [3/5]
void Apply () inline private
Definition at line 176 of file OptionsMenuGame.c.
References ErrorEx, g_Game, GetGame(), GetHud(), GetInput(), MENU_INGAME, mission, OnBleedingIndicationChanged(), and Mission::ResetGUI().
Apply() [4/5]
void Apply () inline private
Definition at line 259 of file OptionsMenuSounds.c.
Apply() [5/5]
void Apply () inline private
Definition at line 260 of file OptionsMenuVideo.c.
Attach()
void Attach (int profileOption, array< Widget > widget_array) inline private
Definition at line 8 of file ProfileOptionsUI.c.
References Init().
AttachmentsWithInventoryOrCargoCount()
protected int AttachmentsWithInventoryOrCargoCount (notnull GameInventory inventory) inline private
Definition at line 1272 of file ActionTargetsCursor.c.
References CargoBase::GetItemCount().
Referenced by GetItemCargoCount().
BuildCursor()
protected void BuildCursor () inline private
weapon specific
transmitter/PAS specific
Definition at line 130 of file ItemActionsWidget.c.
References GetActionDesc(), GetItemDesc(), GetItemHealth(), GetItemQuantity(), GetRadioFrequency(), SetActionWidget(), SetInteractActionIcon(), SetItemDesc(), SetItemHealth(), SetItemQuantity(), SetMultipleContinuousInteractAction(), SetMultipleContinuousItemAction(), SetMultipleInteractAction(), SetMultipleItemAction(), SetRadioFrequency(), SetWeaponModeAndZeroing(), and SetWeaponQuantity().
Referenced by Update().
BuildFixedCursor()
protected void BuildFixedCursor () inline private
Definition at line 221 of file ActionTargetsCursor.c.
References GetScreenSize(), m_Root, PrepareCursorContent(), x, and y.
Referenced by Update().
BuildFloatingCursor()
protected void BuildFloatingCursor (bool forceRebuild) inline private
Get OnScreenPos when forced or targeted component differs
in case of cached item, all above is reused except the position
Definition at line 233 of file ActionTargetsCursor.c.
References Math::Ceil(), GetOnScreenPosition(), m_Root, m_Target, PrepareCursorContent(), and TransformToScreenPos().
Referenced by Update().
BuildLayout()
private void BuildLayout (Widget parent_widget) inline private
Definition at line 62 of file UiHintPanel.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), and CGame::GetWorkspace().
Referenced by UiHintPanel().
ButtonSetAlphaAnimConsole()
void ButtonSetAlphaAnimConsole (Widget w) inline private
Definition at line 274 of file OptionSelectorBase.c.
ButtonSetColor()
void ButtonSetColor (Widget w, int color) inline private
Definition at line 220 of file OptionSelectorBase.c.
ButtonSetColorConsole()
void ButtonSetColorConsole (Widget w, int color) inline private
Definition at line 269 of file OptionSelectorBase.c.
ButtonSetTextColorConsole()
void ButtonSetTextColorConsole (Widget w, int color) inline private
Definition at line 287 of file OptionSelectorBase.c.
CanAddItemInHandToInventory() [1/2]
bool CanAddItemInHandToInventory () inline private
Definition at line 29 of file InventoryGrid.c.
CanAddItemInHandToInventory() [2/2]
bool CanAddItemInHandToInventory () inline private
Definition at line 73 of file InventoryGrid.c.
References m_CanAddItemInHandToInventory.
CancelEnteringAlternateKeybind() [1/3]
void CancelEnteringAlternateKeybind () inline private
Definition at line 225 of file KeybindingElement.c.
References Reload().
CancelEnteringAlternateKeybind() [2/3]
void CancelEnteringAlternateKeybind () inline private
Definition at line 223 of file KeybindingElementNew.c.
References Reload().
CancelEnteringAlternateKeybind() [3/3]
void CancelEnteringAlternateKeybind () inline private
Definition at line 156 of file KeybindingsGroup.c.
CancelEnteringKeybind() [1/3]
void CancelEnteringKeybind () inline private
Definition at line 214 of file KeybindingElement.c.
References Reload().
CancelEnteringKeybind() [2/3]
void CancelEnteringKeybind () inline private
Definition at line 212 of file KeybindingElementNew.c.
References Reload().
CancelEnteringKeybind() [3/3]
void CancelEnteringKeybind () inline private
Definition at line 140 of file KeybindingsGroup.c.
CanSwitchTab()
bool CanSwitchTab () inline private
Definition at line 200 of file TabberUI.c.
References m_CanSwitch.
Referenced by NextTab(), OnMouseButtonUp(), and PreviousTab().
CheckForActionWidgetOverrides()
protected void CheckForActionWidgetOverrides () inline private
Definition at line 703 of file ItemActionsWidget.c.
References ActionBase(), ActionManagerBase(), and Class::CastTo().
Referenced by Update().
CheckRefresherFlagVisibility() [1/2]
protected void CheckRefresherFlagVisibility () inline private
Definition at line 689 of file ItemActionsWidget.c.
References m_Player, and m_Root.
Referenced by Update().
CheckRefresherFlagVisibility() [2/2]
protected void CheckRefresherFlagVisibility (Object object) inline private
Definition at line 1262 of file ActionTargetsCursor.c.
References Class::CastTo(), m_Player, and m_Root.
Clear()
void Clear () inline private
Definition at line 208 of file ContextMenu.c.
Referenced by Hide(), and ~ContextMenu().
ClearAlternativeKeybind()
void ClearAlternativeKeybind (int key_index) inline private
Definition at line 128 of file KeybindingsGroup.c.
References m_Menu.
ClearKeybind()
void ClearKeybind (int key_index) inline private
Definition at line 123 of file KeybindingsGroup.c.
References m_Menu.
Close() [1/2]
void Close () inline private
Definition at line 94 of file DropdownPrefab.c.
References m_IsExpanded, m_IsExpanded, m_Parent, and m_Root.
Referenced by OnMouseButtonUp().
Close() [2/2]
void Close () inline private
Definition at line 45 of file ModsMenuDetailed.c.
References Highlight(), and m_Root.
ColorDisabled()
void ColorDisabled (Widget w) inline private
Definition at line 196 of file OptionSelectorBase.c.
References ARGB().
ColorDisabledConsole()
void ColorDisabledConsole (Widget w) inline private
Definition at line 256 of file OptionSelectorBase.c.
References ARGB().
ColorHighlight()
void ColorHighlight (Widget w) inline private
Definition at line 164 of file OptionSelectorBase.c.
References ARGB().
ColorHighlightConsole()
void ColorHighlightConsole (Widget w) inline private
Definition at line 230 of file OptionSelectorBase.c.
References ARGB().
ColorNormal()
void ColorNormal (Widget w) inline private
Definition at line 172 of file OptionSelectorBase.c.
References ARGB().
ColorNormalConsole()
void ColorNormalConsole (Widget w) inline private
Definition at line 243 of file OptionSelectorBase.c.
References ARGB().
ColorRed() [1/2]
void ColorRed (Widget w) inline private
Definition at line 661 of file OptionsMenuControls.c.
References ARGB(), Class::CastTo(), and SetFocus().
ColorRed() [2/2]
void ColorRed (Widget w, int x, int y) inline private
Definition at line 182 of file MainMenuNewsfeed.c.
References ARGB(), and SetFocus().
Referenced by OnFocus(), and OnMouseEnter().
ColorWhite() [1/2]
void ColorWhite (Widget w, Widget enterW) inline private
Definition at line 672 of file OptionsMenuControls.c.
References ARGB(), and Class::CastTo().
ColorWhite() [2/2]
void ColorWhite (Widget w, Widget enterW, int x, int y) inline private
Definition at line 212 of file MainMenuNewsfeed.c.
References ARGB().
Referenced by OnFocusLost(), and OnMouseLeave().
ContextMenu()
void ContextMenu () inline private
Definition at line 11 of file ContextMenu.c.
ContinuousActionProgress()
void ContinuousActionProgress () inline private
Definition at line 21 of file ContinuousActionProgress.c.
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), m_Action, m_AM, and Update().
Count()
int Count () inline private
Definition at line 202 of file ContextMenu.c.
Referenced by AddEx(), and AttachmentCategoriesContainer::InitGhostSlots().
CreateFollowedObject()
void CreateFollowedObject (string type) inline private
Definition at line 21 of file CTObjectFollower.c.
References GetGame(), m_Orientation, m_Position, SetPosition(), and SetRotation().
CreditsElement()
void CreditsElement (int index, Widget parent) inline private
Definition at line 5 of file CreditsElement.c.
CTEvent()
void CTEvent (int index, int actor, Widget root, bool walk, CameraToolsMenu parent) inline private
Definition at line 19 of file CTEvent.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Menu, and m_Root.
CTKeyframe()
void CTKeyframe (int index, vector pos, vector orient, float int_value, float fov, float dof, int pin, float time_before, Widget root, CameraToolsMenu parent) inline private
Definition at line 19 of file CTKeyframe.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Menu, m_Orientation, m_Position, m_Root, SetDOF(), SetFOV(), SetInterpTime(), and SetPin().
Darken()
void Darken (Widget w, int x, int y) inline private
Definition at line 731 of file ServerBrowserEntry.c.
References ARGB(), m_Favorite, m_Root, and UpdateColors().
Referenced by OnFocus(), OnMouseButtonUp(), and UpdateEntry().
Deattach()
void Deattach () inline private
Definition at line 26 of file ProfileOptionsUI.c.
Referenced by ~ProfileOptionsUI().
Deselect() [1/3]
void Deselect () inline private
Definition at line 215 of file PlayerListEntryScriptedWidget.c.
Referenced by OnFocusLost(), and OnMouseLeave().
Deselect() [2/3]
void Deselect () inline private
Definition at line 76 of file ModsMenuDetailedEntry.c.
References ARGBF(), m_Root, and Widget::SetImage().
Deselect() [3/3]
void Deselect () inline private
Definition at line 664 of file ServerBrowserEntry.c.
References Lighten(), and m_Root.
DeselectAll()
void DeselectAll () inline private
Definition at line 377 of file TabberUI.c.
References DeselectTabControl(), and DeselectTabPanel().
Referenced by RefreshTab().
DeselectTabControl()
void DeselectTabControl (int index) inline private
Definition at line 350 of file TabberUI.c.
References ARGB().
Referenced by DeselectAll(), and PerformSwitchTab().
DeselectTabPanel()
void DeselectTabPanel (int index) inline private
Definition at line 368 of file TabberUI.c.
Referenced by DeselectAll(), and PerformSwitchTab().
DestroyFollowedObject()
void DestroyFollowedObject () inline private
Definition at line 28 of file CTObjectFollower.c.
References GetGame(), and CGame::ObjectDelete().
Disable()
void Disable () inline private
Definition at line 151 of file OptionSelectorBase.c.
References OptionSelectorBase::ColorDisabledConsole(), and m_Parent.
DisableTabs()
void DisableTabs (bool disable) inline private
useful if we want to disable actual tabs for whatever reason
Definition at line 480 of file TabberUI.c.
DropdownPrefab()
void DropdownPrefab (Widget root, string text = "") inline private
Definition at line 18 of file DropdownPrefab.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Parent, m_Root, m_Text, RefreshContent(), and SetText().
Referenced by InitPresets().
Enable()
void Enable () inline private
Definition at line 138 of file OptionSelectorBase.c.
References OptionSelectorBase::ColorNormal(), OptionSelectorBase::ColorNormalConsole(), and m_Parent.
EnableTabControl()
void EnableTabControl (int index, bool enable) inline private
Definition at line 305 of file TabberUI.c.
References AlignTabbers(), and m_Root.
EnterKeybindingMenu()
void EnterKeybindingMenu () inline private
Definition at line 216 of file OptionsMenuControls.c.
References m_Menu, and MENU_KEYBINDINGS.
Referenced by OnMouseButtonUp().
Fade()
void Fade (bool fade) inline private
Definition at line 127 of file CTObjectFollower.c.
FavoriteIsSet()
bool FavoriteIsSet () inline private
Definition at line 232 of file ServerBrowserFilterContainer.c.
FillInfo()
void FillInfo (GetServersResultRow server_info) inline private
Definition at line 264 of file ServerBrowserEntry.c.
References m_Root, SetAcceleration(), SetBattleye(), SetCharacterAlive(), SetExpand(), SetFavorite(), SetFriends(), SetIP(), SetMapName(), SetModded(), SetMode(), SetMouseAndKeyboard(), SetName(), SetPasswordLocked(), SetPing(), SetPopulation(), SetServerMapName(), SetShard(), SetSlots(), and SetTime().
FillTextMap() [1/4]
void FillTextMap () inline private
Definition at line 634 of file OptionsMenuControls.c.
Referenced by OptionsMenuControls(), OptionsMenuGame(), OptionsMenuSounds(), and OptionsMenuVideo().
FillTextMap() [2/4]
void FillTextMap () inline private
Definition at line 536 of file OptionsMenuGame.c.
FillTextMap() [3/4]
void FillTextMap () inline private
Definition at line 390 of file OptionsMenuSounds.c.
FillTextMap() [4/4]
void FillTextMap () inline private
Definition at line 607 of file OptionsMenuVideo.c.
FindEntryByWidget()
PlayerListEntryScriptedWidget FindEntryByWidget (Widget button) inline private
Definition at line 143 of file PlayerListScriptedWidget.c.
References UID.
FindPlayerByWidget()
string FindPlayerByWidget (Widget button) inline private
Definition at line 159 of file PlayerListScriptedWidget.c.
References UID.
Focus() [1/8]
void Focus () inline private
Definition at line 137 of file PlayerListEntryScriptedWidget.c.
References m_Root, and OnFocus().
Referenced by Apply(), and SetToDefaults().
Focus() [2/8]
void Focus () inline private
Focuses the first viable item.
Definition at line 222 of file OptionsMenuControls.c.
Focus() [3/8]
void Focus () inline private
Definition at line 153 of file OptionsMenuGame.c.
References SetFocus().
Focus() [4/8]
void Focus () inline private
Definition at line 136 of file OptionsMenuSounds.c.
References SetFocus().
Focus() [5/8]
void Focus () inline private
Definition at line 240 of file OptionsMenuVideo.c.
References SetFocus().
Focus() [6/8]
void Focus () inline private
Definition at line 129 of file OptionSelectorBase.c.
References m_Parent, m_Root, and SetFocus().
Focus() [7/8]
void Focus () inline private
Definition at line 201 of file ServerBrowserEntry.c.
References m_Root, and SetFocus().
Focus() [8/8]
void Focus () inline private
Definition at line 385 of file ServerBrowserFilterContainer.c.
References SetFocus().
FocusFirst()
void FocusFirst () inline private
Definition at line 27 of file PlayerListScriptedWidget.c.
References SetFocus().
GenerateQuickBarBackgroundTiles()
void GenerateQuickBarBackgroundTiles (int count) inline private
Definition at line 382 of file InventoryGrid.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Root, and ToString().
GenerateValidFilter()
bool GenerateValidFilter (out string potential_filter) inline private
Turns any given string into a more convenient filter (limits character count, forces lowercase, trims empty spaces).
Definition at line 353 of file ServerBrowserFilterContainer.c.
References LimitTextBoxCharacterCount().
Referenced by OnChange().
GenerateValidIP()
string GenerateValidIP (string potential_ip) inline private
Attempts to generate a valid IP address & port from the given string in format like this: "192.168.0.2:2503". If the process fails, then an empty string is returned.
Definition at line 281 of file ServerBrowserFilterContainer.c.
References string::Split(), and string::ToString().
GetActionDesc() [1/2]
protected string GetActionDesc (ActionBase action) inline private
Definition at line 739 of file ActionTargetsCursor.c.
Referenced by BuildCursor(), and PrepareCursorContent().
GetActionDesc() [2/2]
protected string GetActionDesc (ActionBase action) inline private
Definition at line 272 of file ItemActionsWidget.c.
References string::Empty.
GetActionManager() [1/3]
protected void GetActionManager () inline private
Definition at line 670 of file ActionTargetsCursor.c.
References Class::CastTo(), m_AM, and m_Player.
Referenced by Update(), and Update().
GetActionManager() [2/3]
private void GetActionManager () inline private
Definition at line 116 of file ContinuousActionProgress.c.
References Class::CastTo(), m_AM, and m_Player.
GetActionManager() [3/3]
protected void GetActionManager () inline private
Definition at line 221 of file ItemActionsWidget.c.
References m_AM, and m_Player.
GetActions() [1/3]
protected void GetActions () inline private
get actions from Action Manager
Definition at line 683 of file ActionTargetsCursor.c.
References ContinuousDefaultActionInput(), m_AM, m_Player, and m_Target.
Referenced by Update().
GetActions() [2/3]
private void GetActions () inline private
Definition at line 126 of file ContinuousActionProgress.c.
References m_Action, and m_AM.
GetActions() [3/3]
protected void GetActions () inline private
Definition at line 229 of file ItemActionsWidget.c.
References ContinuousDefaultActionInput(), m_AM, and m_Player.
GetButtonWidget()
Widget GetButtonWidget () inline private
Definition at line 42 of file PlayerListEntryScriptedWidget.c.
References m_PlayerButton.
GetChangedAlternateBinds() [1/2]
array< int > GetChangedAlternateBinds () inline private
Definition at line 60 of file KeybindingElement.c.
References m_CustomAlternateBind.
GetChangedAlternateBinds() [2/2]
array< int > GetChangedAlternateBinds () inline private
Definition at line 59 of file KeybindingElementNew.c.
References m_CustomAlternateBind.
GetChangedBinds() [1/2]
array< int > GetChangedBinds () inline private
Definition at line 55 of file KeybindingElement.c.
References m_CustomBind.
GetChangedBinds() [2/2]
array< int > GetChangedBinds () inline private
Definition at line 54 of file KeybindingElementNew.c.
References m_CustomBind.
GetCol()
int GetCol (Widget w) inline private
Definition at line 222 of file InventoryGrid.c.
Referenced by OnDoubleClick(), OnDrag(), OnDraggingOver(), OnDropReceived(), OnMouseButtonDown(), OnMouseButtonUp(), and OnMouseEnter().
GetColFromBg()
int GetColFromBg (Widget w) inline private
Definition at line 234 of file InventoryGrid.c.
GetController()
InventoryGridController GetController () inline private
Definition at line 377 of file InventoryGrid.c.
References m_Controller.
GetCrosshairPosition()
protected void GetCrosshairPosition () inline private
Definition at line 69 of file ProjectedCrosshair.c.
References Class::CastTo(), m_Player, m_Visible, and m_Weapon.
Referenced by Update().
GetDistanceString()
protected string GetDistanceString (float total_distance, bool meters_only = false) inline private
Definition at line 114 of file MainMenuStats.c.
References GetValueString(), and Math::Round().
Referenced by UpdateStats().
GetDOF()
float GetDOF () inline private
Definition at line 82 of file CTKeyframe.c.
GetEntityInHands()
protected void GetEntityInHands () inline private
Definition at line 256 of file ItemActionsWidget.c.
References m_Player.
Referenced by Update().
GetEventActor()
int GetEventActor () inline private
Definition at line 113 of file CTEvent.c.
Referenced by Play(), and Stop().
GetEventTime()
float GetEventTime () inline private
Definition at line 102 of file CTEvent.c.
References m_EventTime.
GetEventType()
int GetEventType () inline private
Definition at line 108 of file CTEvent.c.
Referenced by Play().
GetEventWalk()
bool GetEventWalk () inline private
Definition at line 118 of file CTEvent.c.
GetFilterOptionsConsoles()
GetServersInput GetFilterOptionsConsoles () inline private
Definition at line 556 of file ServerBrowserFilterContainer.c.
References string::Length(), GetServersInput::m_RowsPerPage, SERVER_BROWSER_PAGE_SIZE, string::Split(), string::Substring(), and string::ToInt().
GetFilterOptionsPC()
GetServersInput GetFilterOptionsPC () inline private
Definition at line 446 of file ServerBrowserFilterContainer.c.
References string::Length(), GetServersInput::m_RowsPerPage, SERVER_BROWSER_PAGE_SIZE, string::Substring(), and string::ToInt().
GetFOV()
float GetFOV () inline private
Definition at line 72 of file CTKeyframe.c.
GetGridSize()
int GetGridSize () inline private
Definition at line 239 of file InventoryGrid.c.
References m_GridSize.
GetHighlighted()
ModInfo GetHighlighted () inline private
Definition at line 56 of file ModsMenuDetailed.c.
References m_Highlighted.
GetHud() [1/3]
protected IngameHud GetHud () inline private
Definition at line 1296 of file ActionTargetsCursor.c.
References GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
Referenced by ActionTargetsCursor(), Apply(), and ItemActionsWidget().
GetHud() [2/3]
protected IngameHud GetHud () inline private
Definition at line 717 of file ItemActionsWidget.c.
References GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
GetHud() [3/3]
IngameHud GetHud () inline private
Definition at line 431 of file OptionsMenuGame.c.
References GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
GetHudDebug()
HudDebug GetHudDebug () inline private
Definition at line 13 of file HudDebug.c.
References m_HudDebug.
Referenced by OnChange(), and OnClick().
GetInterpTime()
float GetInterpTime () inline private
Definition at line 50 of file CTKeyframe.c.
References m_InterpTime, and string::ToFloat().
GetIP()
string GetIP () inline private
Definition at line 498 of file ServerBrowserEntry.c.
GetItem()
Widget GetItem (int index) inline private
Definition at line 338 of file InventoryGrid.c.
GetItemBackground()
Widget GetItemBackground (int index) inline private
Definition at line 347 of file InventoryGrid.c.
Referenced by AddItem(), RefreshItemVariables(), RefreshQuickbarItemVariables(), RemoveItem(), ResetItem(), and SetItem().
GetItemCargoCount()
protected void GetItemCargoCount (out int cargoCount) inline private
returns number of items in cargo for targeted entity
default cargo count
Definition at line 928 of file ActionTargetsCursor.c.
References AttachmentsWithInventoryOrCargoCount(), Class::CastTo(), m_DisplayInteractTarget, and m_Target.
Referenced by PrepareCursorContent().
GetItemColor()
int GetItemColor (ScriptedWidgetEventHandler grid, InventoryItem item) inline private
Definition at line 15 of file InventoryGrid.c.
GetItemCount()
int GetItemCount (InventoryItem item) inline private
Definition at line 28 of file InventoryGrid.c.
GetItemDesc() [1/2]
protected string GetItemDesc (ActionBase action) inline private
Definition at line 751 of file ActionTargetsCursor.c.
References m_DisplayInteractTarget, m_Target, LOD::NAME_FIRE, LOD::NAME_VIEW, and EntityAI::ShowZonesHealth().
Referenced by BuildCursor(), and PrepareCursorContent().
GetItemDesc() [2/2]
protected string GetItemDesc (EntityAI entity) inline private
Definition at line 280 of file ItemActionsWidget.c.
GetItemHealth() [1/2]
protected int GetItemHealth () inline private
Definition at line 824 of file ActionTargetsCursor.c.
References m_DisplayInteractTarget, m_Target, LOD::NAME_FIRE, and LOD::NAME_VIEW.
Referenced by BuildCursor(), and PrepareCursorContent().
GetItemHealth() [2/2]
protected int GetItemHealth () inline private
Definition at line 288 of file ItemActionsWidget.c.
GetItemQuantity() [1/3]
float GetItemQuantity (InventoryItem item) inline private
Definition at line 26 of file InventoryGrid.c.
Referenced by BuildCursor(), and PrepareCursorContent().
GetItemQuantity() [2/3]
protected void GetItemQuantity (out int q_type, out float q_cur, out int q_min, out int q_max) inline private
Definition at line 904 of file ActionTargetsCursor.c.
References Class::CastTo(), QuantityConversions::GetItemQuantity(), QuantityConversions::HasItemQuantity(), m_DisplayInteractTarget, and m_Target.
GetItemQuantity() [3/3]
protected void GetItemQuantity (out int q_type, out float q_cur, out int q_min, out int q_max) inline private
Definition at line 296 of file ItemActionsWidget.c.
References QuantityConversions::GetItemQuantity(), QuantityConversions::HasItemQuantity(), and QUANTITY_PROGRESS.
GetItemQuantityMax()
int GetItemQuantityMax (InventoryItem item) inline private
Definition at line 27 of file InventoryGrid.c.
GetItemQuantityText()
string GetItemQuantityText (InventoryItem item) inline private
Definition at line 24 of file InventoryGrid.c.
GetItems()
TItemsMap GetItems () inline private
Definition at line 333 of file InventoryGrid.c.
References m_Items.
GetItemSize()
vector GetItemSize (InventoryGrid grid, InventoryItem item) inline private
Definition at line 20 of file InventoryGrid.c.
References Vector().
GetLayoutName() [1/8]
string GetLayoutName () inline private
Definition at line 168 of file ControlMappingKeybinds.c.
Referenced by KeybindingElement(), KeybindingElementNew(), array::KeybindingsContainer(), KeybindingsGroup(), OptionsMenuControls(), OptionsMenuGame(), OptionsMenuSounds(), OptionsMenuVideo(), and TutorialKeybinds().
GetLayoutName() [2/8]
string GetLayoutName () inline private
Definition at line 40 of file KeybindingElement.c.
GetLayoutName() [3/8]
string GetLayoutName () inline private
Definition at line 39 of file KeybindingElementNew.c.
GetLayoutName() [4/8]
string GetLayoutName () inline private
Definition at line 36 of file KeybindingsGroup.c.
GetLayoutName() [5/8]
string GetLayoutName () inline private
Definition at line 207 of file OptionsMenuControls.c.
GetLayoutName() [6/8]
string GetLayoutName () inline private
Definition at line 144 of file OptionsMenuGame.c.
GetLayoutName() [7/8]
string GetLayoutName () inline private
Definition at line 125 of file OptionsMenuSounds.c.
GetLayoutName() [8/8]
string GetLayoutName () inline private
Definition at line 229 of file OptionsMenuVideo.c.
GetMainWidget()
Widget GetMainWidget () inline private
Definition at line 156 of file LayoutHolder.c.
Referenced by Container::CheckHeaderDragability().
GetMapName()
string GetMapName () inline private
Definition at line 518 of file ServerBrowserEntry.c.
References string::ToLower().
Referenced by SetServerMapName().
GetMapToRun()
string GetMapToRun () inline private
Definition at line 513 of file ServerBrowserEntry.c.
GetObj()
EntityAI GetObj () inline private
Definition at line 41 of file CTObjectFollower.c.
GetOnScreenPosition() [1/2]
protected void GetOnScreenPosition (out float x, out float y) inline private
kept for backward compatibility
Get memory LOD from p3d
save selection from memory lod
cache current object and the widget world pos
doors/handles
single vertex in selection
multiple vertices in selection
cache current object and the widget world pos
do not store component index for doors/handles
ladders handling
cache current object and the widget world pos
do not store component index for ladders
Definition at line 453 of file ActionTargetsCursor.c.
References Math::AbsFloat(), string::Contains(), vector::DistanceSq(), GetActionComponentNameList(), GetName(), LOD::GetSelections(), GetType(), IsComponentInSelection(), IsComponentInSelection(), IsInventoryItem(), m_Player, m_Target, LOD::NAME_MEMORY, TransformToScreenPos(), x, y, and vector::Zero.
Referenced by BuildFloatingCursor(), and Update().
GetOnScreenPosition() [2/2]
protected void GetOnScreenPosition (out float x, out float y) inline private
Definition at line 61 of file ObjectFollower.c.
References GetGame(), CGame::GetScreenPos(), GetScreenSize(), m_PivotYOffset, m_TargetObject, x, and y.
GetOrientation()
vector GetOrientation () inline private
Definition at line 102 of file CTKeyframe.c.
References m_Orientation.
GetParent() [1/2]
LayoutHolder GetParent () inline private
Definition at line 138 of file LayoutHolder.c.
References m_Parent.
GetParent() [2/2]
Widget GetParent () inline private
Definition at line 21 of file OptionSelectorBase.c.
References m_Parent.
GetPin()
int GetPin () inline private
Definition at line 62 of file CTKeyframe.c.
GetPlayer() [1/4]
protected void GetPlayer () inline private
Definition at line 665 of file ActionTargetsCursor.c.
References Class::CastTo(), GetGame(), GetPlayer(), and m_Player.
Referenced by GetPlayer(), GetPlayer(), Update(), and Update().
GetPlayer() [2/4]
private void GetPlayer () inline private
Definition at line 111 of file ContinuousActionProgress.c.
References Class::CastTo(), GetGame(), GetPlayer(), and m_Player.
GetPlayer() [3/4]
protected void GetPlayer () inline private
Definition at line 216 of file ItemActionsWidget.c.
References Class::CastTo(), GetGame(), GetPlayer(), and m_Player.
GetPlayer() [4/4]
protected void GetPlayer () inline private
Definition at line 64 of file ProjectedCrosshair.c.
References Class::CastTo(), GetGame(), GetPlayer(), and m_Player.
GetPort()
int GetPort () inline private
Definition at line 503 of file ServerBrowserEntry.c.
GetPosition() [1/2]
vector GetPosition () inline private
Definition at line 97 of file CTKeyframe.c.
References m_Position.
Referenced by OnUpdate().
GetPosition() [2/2]
vector GetPosition () inline private
Definition at line 68 of file CTObjectFollower.c.
References m_Position, and SetPosition().
GetProfileOption()
int GetProfileOption () inline private
Definition at line 94 of file ProfileOptionsUI.c.
References m_profileOption.
GetQuickbarItemColor()
int GetQuickbarItemColor (InventoryGrid grid, InventoryItem item) inline private
Definition at line 19 of file InventoryGrid.c.
GetRadioFrequency()
protected string GetRadioFrequency () inline private
Definition at line 322 of file ItemActionsWidget.c.
References Class::CastTo().
Referenced by BuildCursor().
GetRoot() [1/3]
Widget GetRoot () inline private
Definition at line 355 of file InventoryGrid.c.
References m_Root.
GetRoot() [2/3]
LayoutHolder GetRoot () inline private
Definition at line 119 of file LayoutHolder.c.
References m_Parent.
GetRoot() [3/3]
Widget GetRoot () inline private
Definition at line 92 of file ServerBrowserEntry.c.
References m_Root.
GetRootWidget()
Widget GetRootWidget () inline private
Definition at line 161 of file LayoutHolder.c.
References m_RootWidget.
GetRotation()
vector GetRotation () inline private
Definition at line 77 of file CTObjectFollower.c.
GetSelectedIndex()
int GetSelectedIndex () inline private
Definition at line 446 of file TabberUI.c.
References m_SelectedIndex.
GetSelectedPlayer()
PlayerListEntryScriptedWidget GetSelectedPlayer () inline private
Definition at line 242 of file PlayerListScriptedWidget.c.
References m_SelectedEntry.
GetServerID()
string GetServerID () inline private
Definition at line 508 of file ServerBrowserEntry.c.
GetTab()
Widget GetTab (int index) inline private
Definition at line 190 of file TabberUI.c.
GetTabCount()
int GetTabCount () inline private
Definition at line 195 of file TabberUI.c.
GetTarget()
protected void GetTarget () inline private
Definition at line 721 of file ActionTargetsCursor.c.
References ItemBase::IsTakeable(), m_AM, m_Player, and m_Target.
Referenced by Update().
GetTimeString()
protected string GetTimeString (float total_time) inline private
Definition at line 76 of file MainMenuStats.c.
References GetValueString().
Referenced by UpdateStats().
GetUID()
string GetUID () inline private
Definition at line 66 of file PlayerListEntryScriptedWidget.c.
References m_UID.
GetValueString()
protected string GetValueString (float total_value, bool show_decimals = false) inline private
Definition at line 140 of file MainMenuStats.c.
References string::Get(), string::IndexOf(), string::Length(), string::Substring(), float::ToString(), and string::TrimInPlace().
Referenced by GetDistanceString(), GetTimeString(), and UpdateStats().
GetWidget()
Widget GetWidget () inline private
Definition at line 58 of file ModsMenuDetailedEntry.c.
References m_Root.
GetWidgetArray()
array< Widget > GetWidgetArray () inline private
Definition at line 89 of file ProfileOptionsUI.c.
References m_widget_array.
HasItem()
bool HasItem (InventoryItem item) inline private
Definition at line 744 of file InventoryGrid.c.
HasItemQuantity()
int HasItemQuantity (InventoryItem item) inline private
Definition at line 25 of file InventoryGrid.c.
Hide() [1/2]
void Hide () inline private
Definition at line 116 of file ContextMenu.c.
References Clear().
Referenced by OnMouseButtonDown(), and OnMouseLeave().
Hide() [2/2]
void Hide () inline private
Definition at line 122 of file CTObjectFollower.c.
HideNewsfeed()
void HideNewsfeed () inline private
Definition at line 59 of file MainMenuNewsfeed.c.
References m_Root.
HideOwnedSlotsTooltip()
void HideOwnedSlotsTooltip () inline private
Definition at line 234 of file LayoutHolder.c.
References ItemManager::GetInstance(), and ItemManager::HideTooltipSlot().
HideOwnedTooltip()
void HideOwnedTooltip () inline private
Definition at line 225 of file LayoutHolder.c.
References ItemManager::GetInstance(), and ItemManager::HideTooltip().
HideStats()
void HideStats () inline private
Definition at line 46 of file MainMenuStats.c.
References m_Root.
HideTooltip() [1/2]
void HideTooltip () inline private
Definition at line 156 of file ModsMenuDetailed.c.
HideTooltip() [2/2]
void HideTooltip () inline private
Definition at line 30 of file ModsMenuTooltip.c.
References m_Root, and m_Text.
HideWidget()
protected void HideWidget () inline private
Definition at line 287 of file ActionTargetsCursor.c.
References m_Root.
Referenced by Update().
Highlight()
void Highlight (ModInfo mod_ref) inline private
Definition at line 66 of file ModsMenuDetailed.c.
References string::Get(), m_Data, and ScrollToMod().
Referenced by Close(), and HighlightFirst().
HighlightFirst()
void HighlightFirst () inline private
Definition at line 61 of file ModsMenuDetailed.c.
References Highlight(), and m_Data.
HudDebugEventHandler()
void HudDebugEventHandler (HudDebug hud_debug) inline private
Definition at line 8 of file HudDebug.c.
Init() [1/3]
void Init () inline private
Definition at line 44 of file TabberUI.c.
References AlignTabbers(), Error(), GetGame(), GetInput(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), GetScreenSize(), ScriptInvoker::Insert(), m_Root, m_TabsCount, OnInputDeviceChanged(), OnInputDeviceChanged(), OnInputPresetChanged(), SelectTabControl(), UpdateControlsElements(), x, and y.
Referenced by Attach(), OnWidgetScriptInit(), and OnWidgetScriptInit().
Init() [2/3]
void Init () inline private
Definition at line 43 of file ProfileOptionsUI.c.
References Class::CastTo(), and g_Game.
Init() [3/3]
void Init (Widget layoutRoot) inline private
Definition at line 24 of file ContextMenu.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), and CGame::GetWorkspace().
InitDependentOptionsVisibility() [1/4]
void InitDependentOptionsVisibility () inline private
Definition at line 630 of file OptionsMenuControls.c.
Referenced by OptionsMenuGame().
InitDependentOptionsVisibility() [2/4]
void InitDependentOptionsVisibility () inline private
Definition at line 358 of file OptionsMenuGame.c.
InitDependentOptionsVisibility() [3/4]
void InitDependentOptionsVisibility () inline private
Definition at line 344 of file OptionsMenuSounds.c.
InitDependentOptionsVisibility() [4/4]
void InitDependentOptionsVisibility () inline private
Definition at line 343 of file OptionsMenuVideo.c.
InitPresets()
void InitPresets (int index, Widget parent, Input input) inline private
Definition at line 41 of file KeybindingsGroup.c.
References DropdownPrefab(), Input::GetCurrentProfile(), Input::GetProfileName(), and Input::GetProfilesCount().
Referenced by KeybindingsGroup().
InitSelectors()
void InitSelectors () inline private
Definition at line 142 of file OptionsMenuVideo.c.
References m_Root.
Referenced by OptionsMenuVideo().
InspectItem()
void InspectItem (EntityAI item) inline private
Definition at line 197 of file LayoutHolder.c.
References GetGame(), Mission::GetHud(), CGame::GetMission(), InventoryMenu(), MENU_INSPECT, MENU_INVENTORY, Hud::ShowHudUI(), and Hud::ShowQuickbarUI().
InventoryGrid()
void InventoryGrid () inline private
Definition at line 59 of file InventoryGrid.c.
IsActive()
bool IsActive () inline private
Definition at line 151 of file LayoutHolder.c.
References m_IsActive.
IsAlternateChanged() [1/2]
bool IsAlternateChanged () inline private
Definition at line 50 of file KeybindingElement.c.
References m_IsAlternateEdited.
IsAlternateChanged() [2/2]
bool IsAlternateChanged () inline private
Definition at line 49 of file KeybindingElementNew.c.
References m_IsAlternateEdited.
IsChanged() [1/7]
bool IsChanged () inline private
Definition at line 45 of file KeybindingElement.c.
References m_IsEdited.
IsChanged() [2/7]
bool IsChanged () inline private
Definition at line 44 of file KeybindingElementNew.c.
References m_IsEdited.
IsChanged() [3/7]
bool IsChanged () inline private
Definition at line 165 of file KeybindingsGroup.c.
IsChanged() [4/7]
bool IsChanged () inline private
Definition at line 348 of file OptionsMenuControls.c.
IsChanged() [5/7]
bool IsChanged () inline private
Definition at line 160 of file OptionsMenuGame.c.
References g_Game.
IsChanged() [6/7]
bool IsChanged () inline private
Definition at line 254 of file OptionsMenuSounds.c.
IsChanged() [7/7]
bool IsChanged () inline private
Definition at line 255 of file OptionsMenuVideo.c.
IsComponentInSelection()
protected bool IsComponentInSelection (array< Selection > selection, string compName) inline private
Definition at line 658 of file ActionTargetsCursor.c.
Referenced by GetOnScreenPosition().
IsDisplayable()
bool IsDisplayable () inline private
Definition at line 166 of file LayoutHolder.c.
IsEmpty()
bool IsEmpty () inline private
Definition at line 68 of file PlayerListScriptedWidget.c.
IsEnteringKeyBind()
bool IsEnteringKeyBind () inline private
Definition at line 118 of file KeybindingsGroup.c.
IsFocusable() [1/5]
bool IsFocusable (Widget w) inline private
Definition at line 156 of file CTKeyframe.c.
Referenced by OnFocus(), OnFocusLost(), OnMouseEnter(), and OnMouseLeave().
IsFocusable() [2/5]
bool IsFocusable (Widget w) inline private
Definition at line 172 of file MainMenuNewsfeed.c.
IsFocusable() [3/5]
bool IsFocusable (Widget w) inline private
Definition at line 318 of file OptionsMenuControls.c.
IsFocusable() [4/5]
bool IsFocusable (Widget w) inline private
Definition at line 26 of file OptionSelectorBase.c.
References m_Parent.
IsFocusable() [5/5]
bool IsFocusable (Widget w) inline private
Definition at line 256 of file ServerBrowserEntry.c.
References m_Favorite, and m_Root.
IsGloballyMuted() [1/2]
bool IsGloballyMuted () inline private
Definition at line 76 of file PlayerListEntryScriptedWidget.c.
References m_GlobalMute.
IsGloballyMuted() [2/2]
bool IsGloballyMuted (string UID) inline private
Definition at line 217 of file PlayerListScriptedWidget.c.
References UID.
IsLocalPlayer()
bool IsLocalPlayer () inline private
Definition at line 193 of file PlayerListEntryScriptedWidget.c.
References GetGame(), BiosUserManager::GetSelectedUser(), BiosUser::GetUid(), CGame::GetUserManager(), and m_UID.
Referenced by OnDoubleClick(), PlayerListEntryScriptedWidget(), and ToggleMute().
IsMuted() [1/2]
bool IsMuted () inline private
Definition at line 71 of file PlayerListEntryScriptedWidget.c.
References m_Mute.
IsMuted() [2/2]
bool IsMuted (string UID) inline private
Definition at line 208 of file PlayerListScriptedWidget.c.
References UID.
IsOnline()
bool IsOnline () inline private
Definition at line 251 of file ServerBrowserEntry.c.
References m_IsOnline.
Referenced by OnClick(), OnDoubleClick(), Preview(), and UpdateColors().
IsOpen()
bool IsOpen () inline private
Definition at line 51 of file ModsMenuDetailed.c.
References m_Root.
IsTime()
bool IsTime (float start_time, float end_time) inline private
Definition at line 79 of file CTEvent.c.
IsValidPos()
bool IsValidPos (int index) inline private
Definition at line 260 of file InventoryGrid.c.
Referenced by OnDoubleClick(), OnDrag(), OnDraggingOver(), OnDropReceived(), OnMouseButtonDown(), OnMouseButtonUp(), and OnMouseEnter().
IsVisible() [1/2]
bool IsVisible () inline private
Definition at line 124 of file ContextMenu.c.
Referenced by PreviousTab().
IsVisible() [2/2]
bool IsVisible () inline private
Definition at line 171 of file LayoutHolder.c.
References m_RootWidget.
ItemActionsWidget()
void ItemActionsWidget () inline private
Definition at line 33 of file ItemActionsWidget.c.
References CALL_CATEGORY_GUI, GetGame(), GetHud(), UAInputAPI::GetInputByID(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), UAInput::GetPersistentWrapper(), GetUApi(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), m_AM, m_Hud, OnInputDeviceChanged(), OnInputPresetChanged(), and Update().
KeybindingElement()
void KeybindingElement (int key_index, Widget parent, KeybindingsGroup group) inline private
Definition at line 23 of file KeybindingElement.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), GetLayoutName(), CGame::GetWorkspace(), m_Root, and Reload().
Referenced by AddAction().
KeybindingElementNew()
void KeybindingElementNew (int key_index, Widget parent, KeybindingsContainer group) inline private
Definition at line 22 of file KeybindingElementNew.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), GetLayoutName(), CGame::GetWorkspace(), m_Root, and Reload().
Referenced by array::AddElement().
KeybindingsGroup()
void KeybindingsGroup (int index, Input input, Widget parent, KeybindingsMenu menu) inline private
Definition at line 13 of file KeybindingsGroup.c.
References AddSubgroup(), WorkspaceWidget::CreateWidgets(), Input::GetActionGroupName(), GetGame(), GetLayoutName(), CGame::GetWorkspace(), InitPresets(), m_Menu, and m_Root.
LayoutHolder()
void LayoutHolder (LayoutHolder parent) inline private
Definition at line 79 of file LayoutHolder.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Parent, m_RootWidget, and LayoutHolder::SetLayoutName().
Lighten()
void Lighten (Widget w, Widget enterW, int x, int y) inline private
Definition at line 743 of file ServerBrowserEntry.c.
References ARGB(), GetFocus(), m_Favorite, m_Root, and UpdateColors().
Referenced by Deselect(), OnFocusLost(), OnMouseLeave(), and UpdateEntry().
LimitTextBoxCharacterCount()
bool LimitTextBoxCharacterCount (out string text, int max_length) inline private
Limits the given text to 'max_length' character count. Returns true if any change was done to the input.
Definition at line 266 of file ServerBrowserFilterContainer.c.
Referenced by GenerateValidFilter(), and ProcessIntoIPAddress().
LoadContentList()
private void LoadContentList () inline private
Definition at line 56 of file UiHintPanel.c.
Referenced by UiHintPanel().
LoadData() [1/2]
void LoadData () inline private
Definition at line 89 of file ModsMenuDetailedEntry.c.
References m_Data, m_Description, m_Name, m_Root, name, and Widget::SetText().
Referenced by ModsMenuDetailedEntry(), and ModsMenuSimpleEntry().
LoadData() [2/2]
void LoadData () inline private
Definition at line 43 of file ModsMenuSimpleEntry.c.
References m_Data.
LoadEntries() [1/2]
void LoadEntries (array< ref ModInfo > data) inline private
Definition at line 166 of file ModsMenuDetailed.c.
References m_Data, ModsMenuDetailedEntry(), x, and y.
Referenced by ModsMenuDetailed(), and ModsMenuSimple().
LoadEntries() [2/2]
void LoadEntries (array< ref ModInfo > data) inline private
Definition at line 24 of file ModsMenuSimple.c.
References m_Data, m_Root, and ModsMenuSimpleEntry().
LoadFilters()
void LoadFilters () inline private
Definition at line 106 of file ServerBrowserFilterContainer.c.
References GetGame(), and CGame::GetProfileString().
Referenced by ServerBrowserFilterContainer().
LoadPermissions()
void LoadPermissions (BiosPrivacyPermissionResultArray results) inline private
Definition at line 47 of file PlayerListEntryScriptedWidget.c.
MainMenuNewsfeed()
void MainMenuNewsfeed (Widget root) inline private
Definition at line 19 of file MainMenuNewsfeed.c.
References m_Root, and ShowNewsfeed().
MainMenuStats()
void MainMenuStats (Widget root) inline private
Definition at line 20 of file MainMenuStats.c.
References m_Root.
ModsMenuDetailed()
void ModsMenuDetailed (array< ref ModInfo > data, Widget parent, ModsMenuTooltip tooltip, UIScriptedMenu menu_parent) inline private
Definition at line 17 of file ModsMenuDetailed.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), LoadEntries(), m_CloseButton, m_Data, m_Menu, and m_Root.
ModsMenuDetailedEntry()
void ModsMenuDetailedEntry (ModInfo data, Widget parent, ModsMenuDetailed parent_menu) inline private
Definition at line 25 of file ModsMenuDetailedEntry.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), LoadData(), Widget::LoadImageFile(), m_Data, m_Description, m_Name, m_Root, and TextWidget::SetLineBreakingOverride().
Referenced by LoadEntries().
ModsMenuSimple()
void ModsMenuSimple (array< ref ModInfo > data, Widget parent, ModsMenuDetailed detail_menu) inline private
Definition at line 8 of file ModsMenuSimple.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), LoadEntries(), m_Data, and m_Root.
ModsMenuSimpleEntry()
void ModsMenuSimpleEntry (ModInfo data, int index, Widget parent, ModsMenuSimple parent_menu) inline private
Definition at line 11 of file ModsMenuSimpleEntry.c.
References GetGame(), ModInfo::GetIsDLC(), ModInfo::GetIsOwned(), LoadData(), and m_Data.
Referenced by LoadEntries().
ModsMenuTooltip()
void ModsMenuTooltip (Widget parent) inline private
Definition at line 6 of file ModsMenuTooltip.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Root, and m_Text.
NextTab()
void NextTab () inline private
Definition at line 386 of file TabberUI.c.
References AlignTabbers(), CanSwitchTab(), and PerformSwitchTab().
ObjectFollower()
void ObjectFollower () inline private
Definition at line 9 of file ObjectFollower.c.
References m_Visible.
OnAOChanged()
void OnAOChanged (int value) inline private
Definition at line 539 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnATOCChanged()
void OnATOCChanged (int value) inline private
Definition at line 532 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnBleedingIndicationChanged()
protected void OnBleedingIndicationChanged (bool state) inline private
Definition at line 501 of file OptionsMenuGame.c.
References Mission::GetEffectWidgets(), GetGame(), mission, and GameplayEffectWidgets_base::UpdateWidgets().
Referenced by Apply().
OnBrightnessChanged()
void OnBrightnessChanged (float value) inline private
Definition at line 450 of file OptionsMenuVideo.c.
References m_Menu.
OnChange() [1/3]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 12 of file PluginDayZInfectedDebug.c.
References m_pPluginInfectedDebug, x, and y.
OnChange() [2/3]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 72 of file HudDebug.c.
References GetHudDebug(), x, and y.
OnChange() [3/3]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 398 of file ServerBrowserFilterContainer.c.
References GenerateValidFilter(), OnFilterChanged(), ProcessIntoIPAddress(), and SetFocus().
OnChildAdd()
override bool OnChildAdd (Widget w, Widget child) inline private
Definition at line 285 of file TabberUI.c.
References AlignTabbers(), and m_Root.
OnChildRemove()
override bool OnChildRemove (Widget w, Widget child) inline private
Definition at line 295 of file TabberUI.c.
References AlignTabbers(), and m_Root.
OnClick() [1/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 6 of file PluginDayZInfectedDebug.c.
References m_pPluginInfectedDebug, x, and y.
OnClick() [2/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 24 of file PluginItemDiagnostic.c.
References x, and y.
OnClick() [3/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 136 of file CTKeyframe.c.
References m_Menu, and m_Root.
OnClick() [4/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 139 of file CTObjectFollower.c.
OnClick() [5/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 18 of file HudDebug.c.
References GetHudDebug(), x, and y.
OnClick() [6/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 113 of file DropdownPrefab.c.
References m_IsExpanded.
OnClick() [7/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 194 of file UiHintPanel.c.
References m_UiLeftButton, m_UiRightButton, ShowNextPage(), and ShowPreviousPage().
OnClick() [8/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 230 of file KeybindingElement.c.
OnClick() [9/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 228 of file KeybindingElementNew.c.
OnClick() [10/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 94 of file MainMenuNewsfeed.c.
References OpenDiscord(), OpenDLC(), OpenFeedback(), OpenForums(), OpenTwitter(), and OpenYoutube().
OnClick() [11/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 64 of file ModsMenuSimpleEntry.c.
References m_Data.
OnClick() [12/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 102 of file ServerBrowserEntry.c.
References GetGame(), CGame::GetUIManager(), IsOnline(), m_Root, and UIManager::ShowDialog().
OnClick() [13/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 67 of file ProfileOptionsUI.c.
References SetValue(), x, and y.
OnColorDepthChanged()
void OnColorDepthChanged (int value) inline private
Definition at line 462 of file OptionsMenuVideo.c.
References m_Menu.
OnDisplayModeChanged()
void OnDisplayModeChanged (int value) inline private
Definition at line 438 of file OptionsMenuVideo.c.
References m_Menu.
OnDoubleClick() [1/4]
override bool OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 178 of file InventoryGrid.c.
References GetCol(), IsValidPos(), m_Root, and PrintString().
OnDoubleClick() [2/4]
override bool OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 144 of file CTObjectFollower.c.
OnDoubleClick() [3/4]
override bool OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 168 of file PlayerListEntryScriptedWidget.c.
References GetGame(), GetInput(), IsLocalPlayer(), and OnlineServices::ShowUserProfile().
OnDoubleClick() [4/4]
override bool OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 135 of file ServerBrowserEntry.c.
References IsOnline(), and m_Root.
OnDrag()
override bool OnDrag (Widget w, int x, int y) inline private
Definition at line 269 of file InventoryGrid.c.
References GetCol(), ItemPreviewWidget::GetItem(), IsValidPos(), m_Root, InventoryGridController::OnItemDrag(), PrintString(), ItemPreviewWidget::SetView(), x, and y.
OnDraggingOver()
override bool OnDraggingOver (Widget w, int x, int y, Widget reciever) inline private
Definition at line 294 of file InventoryGrid.c.
References GetCol(), IsValidPos(), m_Root, InventoryGridController::OnItemDraggingOver(), and PrintString().
OnDrop()
override bool OnDrop (Widget w, int x, int y, Widget reciever) inline private
Definition at line 198 of file InventoryGrid.c.
References ItemPreviewWidget::GetItem(), m_Root, InventoryGridController::OnItemDrop(), PrintString(), and ItemPreviewWidget::SetView().
OnDropReceived()
override bool OnDropReceived (Widget w, int x, int y, Widget reciever) inline private
Definition at line 315 of file InventoryGrid.c.
References GetCol(), IsValidPos(), m_Root, InventoryGridController::OnItemDropReceived(), and PrintString().
OnFilterChanged()
void OnFilterChanged () inline private
Definition at line 101 of file ServerBrowserFilterContainer.c.
References ServerBrowserTab::OnFilterChanged().
Referenced by OnChange().
OnFocus() [1/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 146 of file CTKeyframe.c.
References IsFocusable(), and m_Menu.
OnFocus() [2/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 24 of file HudDebug.c.
OnFocus() [3/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 142 of file PlayerListEntryScriptedWidget.c.
References Select().
OnFocus() [4/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 152 of file MainMenuNewsfeed.c.
References ColorRed(), IsFocusable(), x, and y.
OnFocus() [5/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 98 of file ModsMenuSimpleEntry.c.
OnFocus() [6/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 274 of file OptionsMenuControls.c.
References ColorRed(), GetGame(), IsFocusable(), TextMapUpdateWidget(), x, and y.
OnFocus() [7/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 478 of file OptionsMenuGame.c.
References m_Menu, TextMapUpdateWidget(), x, and y.
OnFocus() [8/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 166 of file OptionsMenuSounds.c.
References GetGame(), TextMapUpdateWidget(), x, and y.
OnFocus() [9/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 561 of file OptionsMenuVideo.c.
References GetGame(), TextMapUpdateWidget(), x, and y.
OnFocus() [10/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 105 of file OptionSelectorBase.c.
References OptionSelectorBase::IsFocusable(), m_Root, and OnFocus().
OnFocus() [11/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 211 of file ServerBrowserEntry.c.
References Darken(), IsFocusable(), m_Root, Select(), ServerListFocus(), x, and y.
OnFocus() [12/12]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 430 of file ServerBrowserFilterContainer.c.
References ServerBrowserTab::OnFilterFocus().
OnFocusLost() [1/7]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 30 of file HudDebug.c.
OnFocusLost() [2/7]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 157 of file PlayerListEntryScriptedWidget.c.
References Deselect().
OnFocusLost() [3/7]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 162 of file MainMenuNewsfeed.c.
References ColorWhite(), IsFocusable(), x, and y.
OnFocusLost() [4/7]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 110 of file ModsMenuSimpleEntry.c.
OnFocusLost() [5/7]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 308 of file OptionsMenuControls.c.
References ColorWhite(), and IsFocusable().
OnFocusLost() [6/7]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 119 of file OptionSelectorBase.c.
References OptionSelectorBase::ColorNormalConsole(), OnFocusLost(), x, and y.
OnFocusLost() [7/7]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 231 of file ServerBrowserEntry.c.
References Deselect(), IsFocusable(), Lighten(), m_Root, ServerListFocus(), x, and y.
OnHide()
void OnHide () inline private
Definition at line 187 of file LayoutHolder.c.
References m_RootWidget.
OnHWAAChanged()
void OnHWAAChanged (int value) inline private
Definition at line 517 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnInputDeviceChanged() [1/3]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 161 of file ActionTargetsCursor.c.
References UpdatePCIconsVisibility().
Referenced by Init().
OnInputDeviceChanged() [2/3]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 102 of file ItemActionsWidget.c.
References UpdatePCIconsVisibility().
OnInputDeviceChanged() [3/3]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 26 of file TabberUI.c.
References GetGame(), GetInput(), and UpdateControlsElements().
OnInputPresetChanged() [1/3]
protected void OnInputPresetChanged () inline private
Definition at line 154 of file ActionTargetsCursor.c.
References UpdateControllerInputIcons().
OnInputPresetChanged() [2/3]
protected void OnInputPresetChanged () inline private
Definition at line 95 of file ItemActionsWidget.c.
References UpdateControllerInputIcons().
OnInputPresetChanged() [3/3]
protected void OnInputPresetChanged () inline private
Definition at line 19 of file TabberUI.c.
References UpdateControlsElements().
OnItemClick()
void OnItemClick (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 10 of file InventoryGrid.c.
OnItemDoubleClick()
void OnItemDoubleClick (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 13 of file InventoryGrid.c.
OnItemDrag()
void OnItemDrag (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 6 of file InventoryGrid.c.
OnItemDraggingOver()
void OnItemDraggingOver (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 7 of file InventoryGrid.c.
OnItemDrop()
void OnItemDrop (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 8 of file InventoryGrid.c.
OnItemDropReceived()
void OnItemDropReceived (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 9 of file InventoryGrid.c.
OnItemEnter()
void OnItemEnter (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 4 of file InventoryGrid.c.
OnItemLeave()
void OnItemLeave (InventoryGrid grid, Widget w) inline private
Definition at line 5 of file InventoryGrid.c.
OnItemLeftClick()
void OnItemLeftClick (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 11 of file InventoryGrid.c.
OnItemRightClick()
void OnItemRightClick (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 12 of file InventoryGrid.c.
OnItemSelected()
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
Definition at line 60 of file HudDebug.c.
OnLoadServersAsync()
void OnLoadServersAsync (ref GetServersResult result_list, EBiosError error, string response) inline private
Definition at line 73 of file PlayerListScriptedWidget.c.
OnModalResult()
override bool OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 66 of file HudDebug.c.
OnMouseButtonDown() [1/7]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 143 of file ContextMenu.c.
References CallQueueContext::Call(), ScriptCallQueue::Call(), CALL_CATEGORY_GUI, CGame::GetCallQueue(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), Hide(), UIScriptedMenu::Refresh(), x, and y.
OnMouseButtonDown() [2/7]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 111 of file InventoryGrid.c.
References GetCol(), IsValidPos(), m_Root, and PrintString().
OnMouseButtonDown() [3/7]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 29 of file PluginItemDiagnostic.c.
References x, and y.
OnMouseButtonDown() [4/7]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 149 of file CTObjectFollower.c.
References CTObjectFollower::CTActor(), and m_Menu.
OnMouseButtonDown() [5/7]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 48 of file HudDebug.c.
OnMouseButtonDown() [6/7]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 128 of file DropdownPrefab.c.
References m_IsExpanded, m_IsExpanded, m_Parent, m_Root, and m_Text.
OnMouseButtonDown() [7/7]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 298 of file KeybindingsGroup.c.
OnMouseButtonUp() [1/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 146 of file InventoryGrid.c.
References GetCol(), IsValidPos(), m_Root, and PrintString().
OnMouseButtonUp() [2/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 33 of file PluginItemDiagnostic.c.
References x, and y.
OnMouseButtonUp() [3/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 162 of file CTObjectFollower.c.
References m_Menu.
OnMouseButtonUp() [4/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 180 of file PlayerListEntryScriptedWidget.c.
References GetGame(), GetInput(), and ToggleMute().
OnMouseButtonUp() [5/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 246 of file KeybindingElement.c.
References array::ClearAlternativeKeybind(), and array::ClearKeybind().
OnMouseButtonUp() [6/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 244 of file KeybindingElementNew.c.
References array::ClearAlternativeKeybind(), and array::ClearKeybind().
OnMouseButtonUp() [7/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 184 of file ModsMenuDetailed.c.
References Close(), and m_CloseButton.
OnMouseButtonUp() [8/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 161 of file ModsMenuDetailedEntry.c.
References GetGame(), m_Data, and CGame::OpenURL().
OnMouseButtonUp() [9/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 55 of file ModsMenuSimple.c.
OnMouseButtonUp() [10/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 259 of file OptionsMenuControls.c.
References EnterKeybindingMenu().
OnMouseButtonUp() [11/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 154 of file ServerBrowserEntry.c.
References Darken(), m_Favorite, m_Root, Select(), SetFocus(), ToggleExpand(), ToggleFavorite(), x, and y.
OnMouseButtonUp() [12/12]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 265 of file TabberUI.c.
References CanSwitchTab(), and PerformSwitchTab().
OnMouseEnter() [1/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 85 of file InventoryGrid.c.
References GetCol(), IsValidPos(), m_Root, InventoryGridController::OnItemEnter(), and PrintString().
OnMouseEnter() [2/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 4 of file PluginItemDiagnostic.c.
References Mission::AddActiveInputExcludes(), GetGame(), and CGame::GetMission().
OnMouseEnter() [3/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 109 of file PlayerListEntryScriptedWidget.c.
References Select(), and SetFocus().
OnMouseEnter() [4/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 214 of file UiHintPanel.c.
References StopSlideShow().
OnMouseEnter() [5/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 265 of file KeybindingElement.c.
References ARGBF().
OnMouseEnter() [6/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 263 of file KeybindingElementNew.c.
References ARGBF().
OnMouseEnter() [7/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 132 of file MainMenuNewsfeed.c.
References ColorRed(), IsFocusable(), x, and y.
OnMouseEnter() [8/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 179 of file ModsMenuDetailedEntry.c.
References m_Data, and m_Root.
OnMouseEnter() [9/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 74 of file ModsMenuSimpleEntry.c.
OnMouseEnter() [10/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 236 of file OptionsMenuControls.c.
References m_Menu.
OnMouseEnter() [11/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 450 of file OptionsMenuGame.c.
References m_Menu.
OnMouseEnter() [12/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 143 of file OptionsMenuSounds.c.
References m_Menu.
OnMouseEnter() [13/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 380 of file OptionsMenuVideo.c.
References m_Menu.
OnMouseEnter() [14/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 35 of file OptionSelectorBase.c.
References OptionSelectorBase::ColorHighlight(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), OptionSelectorBase::IsFocusable(), m_Root, OnFocus(), UIScriptedMenu::OnFocus(), OnMouseEnter(), UIScriptedMenu::OnMouseEnter(), x, and y.
OnMouseEnter() [15/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 179 of file ServerBrowserEntry.c.
References IsFocusable(), Preview(), x, and y.
OnMouseEnter() [16/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 436 of file ServerBrowserFilterContainer.c.
References ServerBrowserTab::OnMouseEnter(), x, and y.
OnMouseEnter() [17/17]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 228 of file TabberUI.c.
References ARGB().
OnMouseLeave() [1/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 130 of file ContextMenu.c.
References Hide(), x, and y.
OnMouseLeave() [2/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 103 of file InventoryGrid.c.
References InventoryGridController::OnItemLeave().
OnMouseLeave() [3/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 14 of file PluginItemDiagnostic.c.
References GetGame(), CGame::GetMission(), and Mission::RemoveActiveInputExcludes().
OnMouseLeave() [4/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 125 of file PlayerListEntryScriptedWidget.c.
References Deselect().
OnMouseLeave() [5/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 223 of file UiHintPanel.c.
References RestartSlideShow().
OnMouseLeave() [6/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 293 of file KeybindingElement.c.
References ARGBF().
OnMouseLeave() [7/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 291 of file KeybindingElementNew.c.
References ARGBF().
OnMouseLeave() [8/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 142 of file MainMenuNewsfeed.c.
References ColorWhite(), IsFocusable(), x, and y.
OnMouseLeave() [9/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 203 of file ModsMenuDetailedEntry.c.
References m_Root.
OnMouseLeave() [10/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 86 of file ModsMenuSimpleEntry.c.
OnMouseLeave() [11/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 248 of file OptionsMenuControls.c.
References m_Menu.
OnMouseLeave() [12/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 467 of file OptionsMenuGame.c.
References m_Menu.
OnMouseLeave() [13/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 155 of file OptionsMenuSounds.c.
References m_Menu.
OnMouseLeave() [14/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 392 of file OptionsMenuVideo.c.
References m_Menu.
OnMouseLeave() [15/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 69 of file OptionSelectorBase.c.
References OptionSelectorBase::ColorNormal(), OptionSelectorBase::ColorNormalConsole(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), OptionSelectorBase::IsFocusable(), m_Root, OnFocus(), UIScriptedMenu::OnFocus(), OnFocusLost(), OnMouseLeave(), UIScriptedMenu::OnMouseLeave(), x, and y.
OnMouseLeave() [16/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 190 of file ServerBrowserEntry.c.
References IsFocusable(), Lighten(), x, and y.
OnMouseLeave() [17/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 441 of file ServerBrowserFilterContainer.c.
References ServerBrowserTab::OnMouseLeave(), x, and y.
OnMouseLeave() [18/18]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 247 of file TabberUI.c.
References ARGB().
OnObjectDetailChanged()
void OnObjectDetailChanged (int value) inline private
Definition at line 468 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnOptionChanged()
void OnOptionChanged () inline private
Definition at line 403 of file OptionsMenuVideo.c.
Referenced by OnAOChanged(), OnATOCChanged(), OnHWAAChanged(), OnObjectDetailChanged(), OnPPAAChanged(), OnPPQualityChanged(), OnShadowDetailChanged(), OnSSRQualityChanged(), OnTerrainDetailChanged(), OnTerrainSurfaceDetailChanged(), OnTextureDetailChanged(), and OnTextureFilteringChanged().
OnOverallQualityChanged()
void OnOverallQualityChanged (int value) inline private
Definition at line 423 of file OptionsMenuVideo.c.
References m_Menu, RefreshCustom(), ReloadOptions(), and GameOptions::Test().
OnPartyChatChangedEvent()
void OnPartyChatChangedEvent () inline private
Definition at line 227 of file OptionsMenuSounds.c.
References GetGame(), and UpdateWasMicCapturing().
OnPPAAChanged()
void OnPPAAChanged (int value) inline private
Definition at line 510 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnPPQualityChanged()
void OnPPQualityChanged (int value) inline private
Definition at line 546 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnResolutionChanged()
void OnResolutionChanged (int value) inline private
Definition at line 444 of file OptionsMenuVideo.c.
References m_Menu.
OnSelect()
override bool OnSelect (Widget w, int x, int y) inline private
Definition at line 55 of file HudDebug.c.
OnSelectAction()
void OnSelectAction (ItemBase item, int actionId) inline private
Definition at line 25 of file LayoutHolder.c.
References GetGame(), GetPlayer(), and m_player.
OnSelectConsolePreset()
void OnSelectConsolePreset (int index) inline private
Definition at line 71 of file KeybindingsGroup.c.
References GetGame(), CGame::GetInput(), Input::GetProfileName(), ReloadProfiles(), and Input::SetProfile().
OnSelectKBPreset()
void OnSelectKBPreset (int index) inline private
Definition at line 61 of file KeybindingsGroup.c.
References GetGame(), CGame::GetInput(), Input::GetProfileName(), ReloadProfiles(), and Input::SetProfile().
OnShadowDetailChanged()
void OnShadowDetailChanged (int value) inline private
Definition at line 489 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnShow()
void OnShow () inline private
Definition at line 180 of file LayoutHolder.c.
References m_RootWidget.
OnSortChanged()
void OnSortChanged (int value) inline private
Definition at line 358 of file ServerBrowserFilterContainer.c.
References ServerBrowserTab::SetSort().
OnSSRQualityChanged()
void OnSSRQualityChanged (int value) inline private
Definition at line 553 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnTerrainDetailChanged()
void OnTerrainDetailChanged (int value) inline private
Definition at line 475 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnTerrainSurfaceDetailChanged()
void OnTerrainSurfaceDetailChanged (int value) inline private
Definition at line 503 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnTextureDetailChanged()
void OnTextureDetailChanged (int value) inline private
Definition at line 482 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnTextureFilteringChanged()
void OnTextureFilteringChanged (int value) inline private
Definition at line 496 of file OptionsMenuVideo.c.
References m_Menu, and OnOptionChanged().
OnUpdate() [1/3]
override bool OnUpdate (Widget w) inline private
Definition at line 79 of file InventoryGrid.c.
OnUpdate() [2/3]
override bool OnUpdate (Widget w) inline private
Definition at line 276 of file ActionTargetsCursor.c.
References m_Root, and Update().
OnUpdate() [3/3]
override bool OnUpdate (Widget w) inline private
Definition at line 31 of file ObjectFollower.c.
References m_Root, and Update().
OnVonStateEvent()
void OnVonStateEvent () inline private
Definition at line 214 of file OptionsMenuSounds.c.
References CGame::EnableMicCapture(), GetGame(), and UpdateWasMicCapturing().
OnVSyncChanged()
void OnVSyncChanged (float value) inline private
Definition at line 456 of file OptionsMenuVideo.c.
References m_Menu.
OnWidgetScriptInit() [1/8]
void OnWidgetScriptInit (Widget w) inline private
Definition at line 14 of file SizeToChild.c.
References m_Root, and ResizeParentToChild().
OnWidgetScriptInit() [2/8]
protected void OnWidgetScriptInit (Widget w) inline private
Definition at line 66 of file InventoryGrid.c.
References m_Root.
OnWidgetScriptInit() [3/8]
protected void OnWidgetScriptInit (Widget w) inline private
UA -> widget icon
Definition at line 138 of file ActionTargetsCursor.c.
References m_Root, UpdateControllerInputIcons(), and UpdatePCIconsVisibility().
OnWidgetScriptInit() [4/8]
protected void OnWidgetScriptInit (Widget w) inline private
Definition at line 43 of file ContinuousActionProgress.c.
References m_Root.
OnWidgetScriptInit() [5/8]
protected void OnWidgetScriptInit (Widget w) inline private
UA -> widget icon
Definition at line 82 of file ItemActionsWidget.c.
References m_Root, UpdateControllerInputIcons(), and UpdatePCIconsVisibility().
OnWidgetScriptInit() [6/8]
void OnWidgetScriptInit (Widget w) inline private
Definition at line 95 of file TabberUI.c.
References Init(), and m_Root.
OnWidgetScriptInit() [7/8]
protected void OnWidgetScriptInit (Widget w) inline private
Definition at line 20 of file ObjectFollower.c.
References m_Root.
OnWidgetScriptInit() [8/8]
void OnWidgetScriptInit (Widget w) inline private
Definition at line 26 of file ProjectedCrosshair.c.
References m_Root.
Open()
void Open () inline private
Definition at line 38 of file ModsMenuDetailed.c.
References m_Root.
OpenDiscord()
void OpenDiscord () inline private
Definition at line 69 of file MainMenuNewsfeed.c.
References GetGame(), and CGame::OpenURL().
Referenced by OnClick().
OpenDLC()
void OpenDLC () inline private
Definition at line 64 of file MainMenuNewsfeed.c.
References GetGame(), and CGame::OpenURL().
Referenced by OnClick().
OpenFeedback()
void OpenFeedback () inline private
Definition at line 74 of file MainMenuNewsfeed.c.
References GetGame(), and CGame::OpenURL().
Referenced by OnClick().
OpenForums()
void OpenForums () inline private
Definition at line 79 of file MainMenuNewsfeed.c.
References GetGame(), and CGame::OpenURL().
Referenced by OnClick().
OpenTwitter()
void OpenTwitter () inline private
Definition at line 84 of file MainMenuNewsfeed.c.
References GetGame(), and CGame::OpenURL().
Referenced by OnClick().
OpenYoutube()
void OpenYoutube () inline private
Definition at line 89 of file MainMenuNewsfeed.c.
References GetGame(), and CGame::OpenURL().
Referenced by OnClick().
OptionsMenuControls()
void OptionsMenuControls (Widget parent, Widget details_root, GameOptions options, OptionsMenu menu) inline private
Definition at line 71 of file OptionsMenuControls.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, WorkspaceWidget::CreateWidgets(), FillTextMap(), g_Game, CGame::GetCallQueue(), GetGame(), CGame::GetInput(), GetLayoutName(), CGame::GetWorkspace(), CGame::GetWorld(), Input::IsEnabledMouseAndKeyboardEvenOnServer(), World::IsMouseAndKeyboardEnabledOnServer(), m_Menu, m_Root, SetOptions(), x, and y.
OptionsMenuGame()
void OptionsMenuGame (Widget parent, Widget details_root, GameOptions options, OptionsMenu menu) inline private
Definition at line 39 of file OptionsMenuGame.c.
References WorkspaceWidget::CreateWidgets(), FillTextMap(), g_Game, GetGame(), GetLayoutName(), GameOptions::GetOptionByType(), CGame::GetWorkspace(), InitDependentOptionsVisibility(), m_Menu, m_Root, x, and y.
OptionsMenuSounds()
void OptionsMenuSounds (Widget parent, Widget details_root, GameOptions options, OptionsMenu menu) inline private
Definition at line 36 of file OptionsMenuSounds.c.
References WorkspaceWidget::CreateWidgets(), CGame::EnableMicCapture(), FillTextMap(), GetGame(), VONManager::GetInstance(), GetLayoutName(), GameOptions::GetOptionByType(), CGame::GetWorkspace(), ScriptInvoker::Insert(), CGame::IsInPartyChat(), CGame::IsMicCapturing(), m_Menu, VONManagerBase::m_OnPartyChatChangedEvent, VONManagerBase::m_OnVonStateEvent, m_Root, VONManagerBase::OnVOIPThresholdChanged(), x, and y.
OptionsMenuVideo()
void OptionsMenuVideo (Widget parent, Widget details_root, GameOptions options, OptionsMenu menu) inline private
Definition at line 81 of file OptionsMenuVideo.c.
References CGame::BeginOptionsVideo(), WorkspaceWidget::CreateWidgets(), FillTextMap(), GetGame(), GetLayoutName(), CGame::GetWorkspace(), InitSelectors(), m_Menu, m_Root, RefreshCustom(), SetOptions(), x, and y.
PerformSwitchTab()
void PerformSwitchTab (int index) inline private
Definition at line 210 of file TabberUI.c.
References AlignTabbers(), DeselectTabControl(), DeselectTabPanel(), SelectTabControl(), and SelectTabPanel().
Referenced by NextTab(), OnMouseButtonUp(), PreviousTab(), and RefreshTab().
PingIsSet()
bool PingIsSet () inline private
Definition at line 227 of file ServerBrowserFilterContainer.c.
Play()
void Play () inline private
Definition at line 43 of file CTEvent.c.
References GetEventActor(), GetEventType(), m_Callback, and m_Menu.
PlayerListEntryScriptedWidget()
void PlayerListEntryScriptedWidget (Widget parent, string name, string uid, bool show_permissions, PlayerListScriptedWidget tab) inline private
Definition at line 18 of file PlayerListEntryScriptedWidget.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), IsLocalPlayer(), m_Name, m_PlayerName, m_Root, and name.
Referenced by AddPlayer().
PlayerListScriptedWidget()
void PlayerListScriptedWidget (Widget parent, string header_text = "") inline private
Definition at line 11 of file PlayerListScriptedWidget.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), and m_Root.
PopulateLayout()
private void PopulateLayout () inline private
Definition at line 83 of file UiHintPanel.c.
References SetHintDescription(), SetHintHeadline(), SetHintImage(), and SetHintPaging().
Referenced by ShowNextPage(), ShowPreviousPage(), and UiHintPanel().
PrepareCursorContent()
protected void PrepareCursorContent () inline private
item health
quantity
cargo in item
fill the widget with data
Definition at line 189 of file ActionTargetsCursor.c.
References GetActionDesc(), GetItemCargoCount(), GetItemDesc(), GetItemHealth(), GetItemQuantity(), SetActionWidget(), SetInteractActionIcon(), SetItemDesc(), SetItemHealth(), SetItemQuantity(), SetMultipleContinuousInteractAction(), SetMultipleContinuousItemAction(), SetMultipleInteractAction(), and SetMultipleItemAction().
Referenced by BuildFixedCursor(), and BuildFloatingCursor().
PrepareOwnedSlotsTooltip()
void PrepareOwnedSlotsTooltip (Widget w, string name, string desc, int x = 0, int y = 0) inline private
Definition at line 218 of file LayoutHolder.c.
References ItemManager::GetInstance(), name, ItemManager::PrepareSlotsTooltip(), ItemManager::SetTooltipWidget(), x, and y.
PrepareOwnedTooltip()
void PrepareOwnedTooltip (EntityAI item, int x = 0, int y = 0) inline private
Definition at line 212 of file LayoutHolder.c.
References ItemManager::GetInstance(), ItemManager::PrepareTooltip(), x, and y.
PrepareTooltip()
void PrepareTooltip (ModInfo mod_ref) inline private
Definition at line 138 of file ModsMenuDetailed.c.
References CALL_CATEGORY_GUI.
Preview()
void Preview (Widget w, int x, int y) inline private
Definition at line 711 of file ServerBrowserEntry.c.
References ARGB(), IsOnline(), m_Favorite, m_Root, and UpdateColors().
Referenced by OnMouseEnter().
PreviouslyIsSet()
bool PreviouslyIsSet () inline private
Definition at line 237 of file ServerBrowserFilterContainer.c.
PreviousTab()
void PreviousTab () inline private
Definition at line 416 of file TabberUI.c.
References AlignTabbers(), CanSwitchTab(), IsVisible(), and PerformSwitchTab().
ProcessIntoIPAddress()
bool ProcessIntoIPAddress (out string potential_ip) inline private
Removes all characters from the given string whirh are NOT a number, '.' or ':'. Returns true if any change was done to the input text.
Definition at line 243 of file ServerBrowserFilterContainer.c.
References LimitTextBoxCharacterCount(), and string::ToInt().
Referenced by OnChange().
ProjectedCrosshair()
void ProjectedCrosshair () inline private
Definition at line 11 of file ProjectedCrosshair.c.
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), m_Debug, m_Player, m_Visible, m_Weapon, and Update().
RandomizePageIndex()
private void RandomizePageIndex () inline private
Definition at line 129 of file UiHintPanel.c.
References Math::RandomInt().
Referenced by UiHintPanel().
Refresh()
void Refresh () inline private
Definition at line 192 of file LayoutHolder.c.
References m_RootWidget.
Referenced by OnWidgetScriptInit().
RefreshContent()
void RefreshContent () inline private
Definition at line 38 of file DropdownPrefab.c.
References m_Root, x, and y.
Referenced by DropdownPrefab().
RefreshCustom()
void RefreshCustom () inline private
Definition at line 347 of file OptionsMenuVideo.c.
Referenced by OnOverallQualityChanged(), OptionsMenuVideo(), Revert(), and SetToDefaults().
RefreshItemVariables()
void RefreshItemVariables (InventoryItem item, vector data, bool show_quantity, bool show_temperature) inline private
Definition at line 584 of file InventoryGrid.c.
References GetItemBackground(), InventoryGridController::GetItemCount(), InventoryGridController::GetItemQuantity(), InventoryGridController::GetItemQuantityMax(), InventoryGridController::GetItemQuantityText(), InventoryGridController::HasItemQuantity(), QUANTITY_COUNT, QUANTITY_HIDDEN, QUANTITY_PROGRESS, and Math::Round().
Referenced by AddItem(), RefreshQuickbarItemVariables(), ResetItem(), SetItem(), UpdateItems(), UpdateQuantityItems(), and UpdateTemperatureItems().
RefreshQuickbarItemVariables()
void RefreshQuickbarItemVariables (InventoryItem item, vector data) inline private
Definition at line 567 of file InventoryGrid.c.
References GetItemBackground(), InventoryGridController::GetQuickbarItemColor(), RefreshItemVariables(), and Math::Round().
Referenced by UpdateQuickbarItems().
RefreshTab()
void RefreshTab (bool performInitAlignment = false) inline private
Definition at line 451 of file TabberUI.c.
References DeselectAll(), and PerformSwitchTab().
Reload() [1/7]
void Reload () inline private
Definition at line 122 of file KeybindingElement.c.
References Input::GetActionDesc(), GetGame(), CGame::GetInput(), UAInputAPI::GetInputByID(), GetUApi(), UAInput::IsClickLimit(), UAInput::IsDoubleClickLimit(), UAInput::IsHoldBeginLimit(), UAInput::IsHoldLimit(), UAInput::IsLimited(), UAInput::IsPressLimit(), UAInput::IsReleaseLimit(), name, and SetElementTitle().
Referenced by CancelEnteringAlternateKeybind(), CancelEnteringKeybind(), KeybindingElement(), and KeybindingElementNew().
Reload() [2/7]
void Reload () inline private
Definition at line 120 of file KeybindingElementNew.c.
References Input::GetActionDesc(), GetGame(), CGame::GetInput(), UAInputAPI::GetInputByID(), GetUApi(), UAInput::IsClickLimit(), UAInput::IsDoubleClickLimit(), UAInput::IsHoldBeginLimit(), UAInput::IsHoldLimit(), UAInput::IsLimited(), UAInput::IsPressLimit(), UAInput::IsReleaseLimit(), name, and SetElementTitle().
Reload() [3/7]
void Reload (array< int > custom_binds, bool is_alternate) inline private
Definition at line 175 of file KeybindingElement.c.
References UAInputAPI::GetButtonName(), and GetUApi().
Reload() [4/7]
void Reload (array< int > custom_binds, bool is_alternate) inline private
Definition at line 173 of file KeybindingElementNew.c.
References UAInputAPI::GetButtonName(), and GetUApi().
Reload() [5/7]
void Reload (BiosFriendInfoArray player_list) inline private
Definition at line 78 of file PlayerListScriptedWidget.c.
References AddPlayer(), BiosFriendInfo::m_DisplayName, BiosFriendInfo::m_Uid, RemovePlayer(), and UID.
Reload() [6/7]
void Reload (BiosPrivacyUidResultArray player_list) inline private
Definition at line 112 of file PlayerListScriptedWidget.c.
Reload() [7/7]
void Reload (SyncPlayerList player_list) inline private
Definition at line 34 of file PlayerListScriptedWidget.c.
References AddPlayer(), SyncPlayerList::m_PlayerList, SyncPlayer::m_PlayerName, SyncPlayer::m_UID, RemovePlayer(), and UID.
ReloadAction()
void ReloadAction (int index) inline private
Definition at line 110 of file KeybindingsGroup.c.
ReloadLocal()
void ReloadLocal (map< string, bool > player_list) inline private
Definition at line 125 of file PlayerListScriptedWidget.c.
References OnlineServices::IsPlayerMuted().
ReloadOptions() [1/4]
void ReloadOptions () inline private
Definition at line 590 of file OptionsMenuControls.c.
References m_Menu.
Referenced by OnOverallQualityChanged().
ReloadOptions() [2/4]
void ReloadOptions () inline private
Definition at line 329 of file OptionsMenuGame.c.
References m_Menu.
ReloadOptions() [3/4]
void ReloadOptions () inline private
Definition at line 321 of file OptionsMenuSounds.c.
References m_Menu.
ReloadOptions() [4/4]
void ReloadOptions () inline private
Definition at line 250 of file OptionsMenuVideo.c.
References m_Menu.
ReloadProfiles()
void ReloadProfiles () inline private
Definition at line 79 of file KeybindingsGroup.c.
Referenced by OnSelectConsolePreset(), and OnSelectKBPreset().
Remove()
void Remove (int index) inline private
Definition at line 189 of file ContextMenu.c.
References String(), and ToString().
Referenced by HandsContainer::DestroyAtt(), Container::~CargoContainer(), ClosableContainer::~ContainerWithCargoAndAttachments(), and HandsContainer::~HandsContainer().
RemoveElement()
void RemoveElement (int index) inline private
Definition at line 83 of file DropdownPrefab.c.
References m_Parent, and m_Root.
RemoveItem()
void RemoveItem (InventoryItem item) inline private
Definition at line 750 of file InventoryGrid.c.
References GetItemBackground(), and Math::Round().
Referenced by UpdateItems(), and UpdateQuickbarItems().
RemovePlayer()
void RemovePlayer (string UID) inline private
Definition at line 184 of file PlayerListScriptedWidget.c.
References SelectPlayer(), and UID.
Referenced by Reload().
RemoveTab()
void RemoveTab (int index) inline private
Definition at line 184 of file TabberUI.c.
Reset()
void Reset () inline private
Definition at line 243 of file KeybindingsGroup.c.
References ResetEx().
ResetEx()
void ResetEx (bool forced = false) inline private
Definition at line 248 of file KeybindingsGroup.c.
Referenced by Reset().
ResetFilters()
void ResetFilters () inline private
Definition at line 195 of file ServerBrowserFilterContainer.c.
References SaveFilters().
ResetItem()
void ResetItem (InventoryItem item) inline private
Definition at line 728 of file InventoryGrid.c.
References GetItemBackground(), RefreshItemVariables(), ResetItemWidget(), and Math::Round().
ResetItemWidget()
protected void ResetItemWidget (Widget item_w, int width, int height) inline private
Definition at line 719 of file InventoryGrid.c.
Referenced by AddItem(), ResetItem(), and SetItem().
ResizeParentToChild() [1/2]
bool ResizeParentToChild () inline private
Definition at line 25 of file SizeToChild.c.
References ResizeParentToChild().
Referenced by OnWidgetScriptInit(), and ResizeParentToChild().
ResizeParentToChild() [2/2]
bool ResizeParentToChild (out bool changed_size, int limit = -1, bool immedUpdate = true) inline private
Definition at line 30 of file SizeToChild.c.
References m_HorizontalOffset, m_ResizeHorizontal, m_ResizeVertical, m_Root, m_VerticalOffset, Print(), x, and y.
RestartSlideShow()
private void RestartSlideShow () inline private
Definition at line 185 of file UiHintPanel.c.
References StartSlideshow(), and StopSlideShow().
Referenced by OnMouseLeave().
Revert() [1/4]
void Revert () inline private
Definition at line 382 of file OptionsMenuControls.c.
Referenced by SetOptions().
Revert() [2/4]
void Revert () inline private
Definition at line 246 of file OptionsMenuGame.c.
References g_Game.
Revert() [3/4]
void Revert () inline private
Definition at line 264 of file OptionsMenuSounds.c.
Revert() [4/4]
void Revert () inline private
Definition at line 265 of file OptionsMenuVideo.c.
References RefreshCustom().
SaveFilters()
void SaveFilters () inline private
Definition at line 159 of file ServerBrowserFilterContainer.c.
References GetGame(), and CGame::SetProfileString().
Referenced by ResetFilters().
ScrollToEntry()
void ScrollToEntry (PlayerListEntryScriptedWidget entry) inline private
Definition at line 257 of file PlayerListScriptedWidget.c.
References x, and y.
Referenced by SelectPlayer().
ScrollToMod()
void ScrollToMod (ModInfo mod_ref) inline private
Definition at line 83 of file ModsMenuDetailed.c.
Referenced by Highlight(), and Select().
Select() [1/7]
void Select () inline private
Definition at line 123 of file CTEvent.c.
References ARGBF(), and m_Root.
Referenced by OnFocus(), OnMouseButtonUp(), OnMouseEnter(), and UpdateEntry().
Select() [2/7]
void Select () inline private
Definition at line 120 of file CTKeyframe.c.
References ARGBF(), and m_Root.
Select() [3/7]
void Select () inline private
Definition at line 63 of file ModsMenuDetailedEntry.c.
References ARGBF(), m_Root, and Widget::SetImage().
Select() [4/7]
void Select (bool notify = true) inline private
Definition at line 203 of file PlayerListEntryScriptedWidget.c.
Select() [5/7]
void Select (bool notify = true) inline private
Definition at line 646 of file ServerBrowserEntry.c.
References ARGB(), m_Root, and ServerBrowserTab::SelectServer().
Select() [6/7]
void Select (ModInfo mod) inline private
Definition at line 49 of file ModsMenuSimple.c.
Select() [7/7]
void Select (ModInfo mod_ref, bool show) inline private
Definition at line 116 of file ModsMenuDetailed.c.
References string::Get(), m_Data, and ScrollToMod().
SelectPlayer()
void SelectPlayer (PlayerListEntryScriptedWidget entry) inline private
Definition at line 247 of file PlayerListScriptedWidget.c.
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), UIScriptedMenu::Refresh(), and ScrollToEntry().
Referenced by RemovePlayer().
SelectTabControl()
void SelectTabControl (int index) inline private
Definition at line 313 of file TabberUI.c.
References ARGB().
Referenced by Init(), and PerformSwitchTab().
SelectTabPanel()
void SelectTabPanel (int index) inline private
Definition at line 341 of file TabberUI.c.
Referenced by PerformSwitchTab().
ServerBrowserEntry()
void ServerBrowserEntry (Widget parent, int index, ServerBrowserTab tab) inline private
Definition at line 40 of file ServerBrowserEntry.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Favorite, and m_Root.
ServerBrowserFilterContainer()
void ServerBrowserFilterContainer (Widget root, ServerBrowserTab parent) inline private
Definition at line 26 of file ServerBrowserFilterContainer.c.
References GetGame(), CGame::GetPlayerName(), LoadFilters(), and OnFilterChanged().
ServerListFocus()
void ServerListFocus (bool focus) inline private
Definition at line 206 of file ServerBrowserEntry.c.
Referenced by OnFocus(), and OnFocusLost().
SetAcceleration()
void SetAcceleration (float mult) inline private
Definition at line 538 of file ServerBrowserEntry.c.
References float::ToString().
Referenced by FillInfo().
SetActionWidget() [1/2]
protected void SetActionWidget (ActionBase action, string descText, string actionWidget, string descWidget) inline private
Definition at line 1095 of file ActionTargetsCursor.c.
References Class::CastTo(), m_AM, m_Root, x, and y.
Referenced by BuildCursor(), and PrepareCursorContent().
SetActionWidget() [2/2]
protected void SetActionWidget (ActionBase action, string descText, string actionWidget, string descWidget) inline private
Definition at line 601 of file ItemActionsWidget.c.
References Class::CastTo(), m_Player, and m_Root.
SetActive()
void SetActive (bool active) inline private
Definition at line 143 of file LayoutHolder.c.
References m_IsActive.
SetBattleye()
void SetBattleye (bool battleye) inline private
Definition at line 479 of file ServerBrowserEntry.c.
References ARGBF().
Referenced by FillInfo().
SetButtonStates()
void SetButtonStates (int index) inline private
Definition at line 76 of file ProfileOptionsUI.c.
Referenced by SetValue().
SetCanSwitch()
void SetCanSwitch (bool value) inline private
Definition at line 205 of file TabberUI.c.
SetCharacterAlive()
void SetCharacterAlive (string char_alive) inline private
Definition at line 447 of file ServerBrowserEntry.c.
Referenced by FillInfo().
SetContinuousInteractXboxIcon() [1/2]
void SetContinuousInteractXboxIcon (string imageset_name, string image_name) inline private
Definition at line 126 of file ActionTargetsCursor.c.
SetContinuousInteractXboxIcon() [2/2]
void SetContinuousInteractXboxIcon (string imageset_name, string image_name) inline private
Definition at line 64 of file ItemActionsWidget.c.
SetContinuousXboxIcon() [1/2]
void SetContinuousXboxIcon (string imageset_name, string image_name) inline private
Definition at line 128 of file ActionTargetsCursor.c.
SetContinuousXboxIcon() [2/2]
void SetContinuousXboxIcon (string imageset_name, string image_name) inline private
Definition at line 66 of file ItemActionsWidget.c.
SetController()
void SetController (InventoryGridController controller) inline private
Definition at line 373 of file InventoryGrid.c.
SetControllerIcon() [1/2]
protected void SetControllerIcon (string pWidgetName, string pInputName) inline private
Definition at line 132 of file ActionTargetsCursor.c.
References InputUtils::GetRichtextButtonIconFromInputAction(), and m_Root.
Referenced by UpdateControllerInputIcons().
SetControllerIcon() [2/2]
protected void SetControllerIcon (string pWidgetName, string pInputName) inline private
Definition at line 70 of file ItemActionsWidget.c.
References InputUtils::GetRichtextButtonIconFromInputAction(), and m_Root.
SetDOF()
void SetDOF (float dof) inline private
Definition at line 77 of file CTKeyframe.c.
References float::ToString().
Referenced by CTKeyframe().
SetElementModifier()
bool SetElementModifier (UAInput pInput, out string output) inline private
Determine the active limiter of the bindings (currently unreliable, multiple limiters can be active on key combos!)
Definition at line 126 of file ControlMappingKeybinds.c.
References UAInput::IsClickLimit(), UAInput::IsDoubleClickLimit(), UAInput::IsHoldBeginLimit(), UAInput::IsHoldLimit(), UAInput::IsLimited(), UAInput::IsPressLimit(), and UAInput::IsReleaseLimit().
Referenced by TutorialKeybinds().
SetElementTitle() [1/3]
void SetElementTitle (ButtonWidget btnWidget, UAInput pInput, int iDeviceFlags) inline private
Definition at line 66 of file KeybindingElement.c.
References UAInput::AlternativeCount(), UAInput::Binding(), UAInput::BindingCount(), UAInput::CheckBindDevice(), UAInputAPI::GetButtonName(), GetUApi(), UAInput::IsCombo(), and UAInput::SelectAlternative().
SetElementTitle() [2/3]
void SetElementTitle (ButtonWidget btnWidget, UAInput pInput, int iDeviceFlags) inline private
Definition at line 65 of file KeybindingElementNew.c.
References UAInput::AlternativeCount(), UAInput::Binding(), UAInput::BindingCount(), UAInput::CheckBindDevice(), UAInputAPI::GetButtonName(), GetUApi(), UAInput::IsCombo(), and UAInput::SelectAlternative().
SetElementTitle() [3/3]
bool SetElementTitle (UAInput pInput, int iDeviceFlags, out string output) inline private
assemble all active bindings at widget element
Definition at line 74 of file ControlMappingKeybinds.c.
References UAInput::AlternativeCount(), UAInput::Binding(), UAInput::BindingCount(), UAInput::CheckBindDevice(), UAInputAPI::GetButtonName(), GetUApi(), UAInput::IsCombo(), and UAInput::SelectAlternative().
Referenced by Reload(), and TutorialKeybinds().
SetEventTime()
void SetEventTime (float time) inline private
Definition at line 91 of file CTEvent.c.
References float::ToString().
SetEventType()
void SetEventType (int type) inline private
Definition at line 97 of file CTEvent.c.
SetExpand()
bool SetExpand (bool expand) inline private
Definition at line 619 of file ServerBrowserEntry.c.
References OnlineServices::GetServerModList(), m_IsExpanded, m_IsExpanded, and m_Root.
Referenced by FillInfo(), and ToggleExpand().
SetFavorite()
void SetFavorite (bool favorite) inline private
Definition at line 531 of file ServerBrowserEntry.c.
References m_Root.
Referenced by FillInfo().
SetFirstActive()
void SetFirstActive () private
SetFOV()
void SetFOV (float fov) inline private
Definition at line 67 of file CTKeyframe.c.
References float::ToString().
Referenced by CTKeyframe().
SetFriends()
void SetFriends (string friends_text) inline private
Definition at line 455 of file ServerBrowserEntry.c.
Referenced by FillInfo().
SetGridSize()
void SetGridSize (int size) inline private
Definition at line 244 of file InventoryGrid.c.
SetHealthVisibility()
void SetHealthVisibility (bool state) inline private
Definition at line 114 of file ActionTargetsCursor.c.
SetHintDescription()
private void SetHintDescription () inline private
Definition at line 100 of file UiHintPanel.c.
Referenced by PopulateLayout().
SetHintHeadline()
private void SetHintHeadline () inline private
Definition at line 96 of file UiHintPanel.c.
Referenced by PopulateLayout().
SetHintImage()
private void SetHintImage () inline private
Definition at line 106 of file UiHintPanel.c.
Referenced by PopulateLayout().
SetHintPaging()
private void SetHintPaging () inline private
Definition at line 124 of file UiHintPanel.c.
Referenced by PopulateLayout().
SetImmedUpdate()
void SetImmedUpdate () inline private
Definition at line 20 of file LayoutHolder.c.
SetInteractActionIcon() [1/2]
protected void SetInteractActionIcon (string actionWidget, string actionIconFrameWidget, string actionIconWidget, string actionIconTextWidget) inline private
Definition at line 1244 of file ActionTargetsCursor.c.
References Class::CastTo(), InputUtils::GetButtonNameFromInput(), GetDayZGame(), UAIDWrapper::InputP(), and m_Root.
Referenced by BuildCursor(), and PrepareCursorContent().
SetInteractActionIcon() [2/2]
protected void SetInteractActionIcon (string actionWidget, string actionIconFrameWidget, string actionIconWidget, string actionIconTextWidget) inline private
select first alternative (which is the primary bind)
Definition at line 664 of file ItemActionsWidget.c.
References Class::CastTo(), UAInput::GetBindKey(), UAInputAPI::GetButtonName(), GetUApi(), UAIDWrapper::InputP(), m_Root, and UAInput::SelectAlternative().
SetInteractXboxIcon() [1/2]
void SetInteractXboxIcon (string imageset_name, string image_name) inline private
DEPRECATED.
Definition at line 125 of file ActionTargetsCursor.c.
SetInteractXboxIcon() [2/2]
void SetInteractXboxIcon (string imageset_name, string image_name) inline private
DEPRECATED.
Definition at line 63 of file ItemActionsWidget.c.
SetInterpTime()
void SetInterpTime (float time) inline private
Definition at line 113 of file CTKeyframe.c.
References ToString(), and float::ToString().
Referenced by CTKeyframe().
SetIP()
void SetIP (string ip) inline private
Definition at line 493 of file ServerBrowserEntry.c.
Referenced by FillInfo().
SetIsOnline()
void SetIsOnline (bool isOnline) inline private
Definition at line 585 of file ServerBrowserEntry.c.
SetItem()
void SetItem (InventoryItem item, vector data, vector rotation) inline private
Definition at line 681 of file InventoryGrid.c.
References ItemPreviewWidget::GetItem(), GetItemBackground(), RefreshItemVariables(), ResetItemWidget(), Math::Round(), ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetModelOrientation(), and ItemPreviewWidget::SetView().
SetItemColor()
void SetItemColor (InventoryItem item, int color) inline private
Definition at line 360 of file InventoryGrid.c.
References GetItem(), and Math::Round().
SetItemDesc() [1/2]
protected void SetItemDesc (EntityAI entity, string descText, string itemWidget, string descWidget) inline private
Definition at line 334 of file ItemActionsWidget.c.
References Class::CastTo(), m_Player, m_Root, and string::ToUpper().
SetItemDesc() [2/2]
protected void SetItemDesc (string descText, int cargoCount, string itemWidget, string descWidget) inline private
Last message from finished User Action on target (Thermometer, Blood Test Kit, etc.)
when cargo in container
Definition at line 954 of file ActionTargetsCursor.c.
References Class::CastTo(), string::Format(), string::Length(), m_Root, m_Target, and string::ToUpper().
Referenced by BuildCursor(), and PrepareCursorContent().
SetItemHealth() [1/2]
protected void SetItemHealth (int health, string itemWidget, string healthWidget, bool enabled) inline private
Definition at line 989 of file ActionTargetsCursor.c.
References Class::CastTo(), Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, Colors::COLOR_WORN, m_Root, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
Referenced by BuildCursor(), and PrepareCursorContent().
SetItemHealth() [2/2]
protected void SetItemHealth (int health, string itemWidget, string healthWidget, bool enabled) inline private
Definition at line 352 of file ItemActionsWidget.c.
References Class::CastTo(), Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, Colors::COLOR_WORN, m_Root, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
SetItemQuantity() [1/2]
protected void SetItemQuantity (int type, float current, int min, int max, string itemWidget, string quantityPBWidget, string quantityTextWidget, bool enabled) inline private
Definition at line 1043 of file ActionTargetsCursor.c.
References Class::CastTo(), m_Root, QUANTITY_COUNT, QUANTITY_HIDDEN, QUANTITY_PROGRESS, Math::Round(), float::ToString(), and string::ToString().
Referenced by BuildCursor(), and PrepareCursorContent().
SetItemQuantity() [2/2]
protected void SetItemQuantity (int type, float current, int min, int max, string itemWidget, string quantityPBWidget, string quantityTextWidget, bool enabled) inline private
Definition at line 406 of file ItemActionsWidget.c.
References Class::CastTo(), m_Root, QUANTITY_COUNT, QUANTITY_HIDDEN, QUANTITY_PROGRESS, Math::Round(), float::ToString(), and string::ToString().
SetLastActive()
void SetLastActive () private
SetLayoutName()
void SetLayoutName () private
SetMapName()
void SetMapName (string mapName) inline private
Definition at line 427 of file ServerBrowserEntry.c.
References GetGame(), and CGame::VerifyWorldOwnership().
Referenced by FillInfo().
SetModded()
void SetModded (bool is_modded) inline private
Definition at line 551 of file ServerBrowserEntry.c.
Referenced by FillInfo().
SetMode()
void SetMode (int mode) inline private
Definition at line 460 of file ServerBrowserEntry.c.
Referenced by FillInfo().
SetMods()
void SetMods (array< string > mods) inline private
Definition at line 561 of file ServerBrowserEntry.c.
SetMouseAndKeyboard()
void SetMouseAndKeyboard (bool is_mkenabled) inline private
Definition at line 580 of file ServerBrowserEntry.c.
Referenced by FillInfo().
SetMultipleContinuousInteractAction() [1/2]
protected void SetMultipleContinuousInteractAction (string multiActionsWidget) inline private
shows arrows near the interact action if there are more than one available
Definition at line 639 of file ItemActionsWidget.c.
References m_Root.
SetMultipleContinuousInteractAction() [2/2]
protected void SetMultipleContinuousInteractAction (string multiActionsWidget, string multiActionsWidget_NotSelect) inline private
Definition at line 1162 of file ActionTargetsCursor.c.
References m_Root.
Referenced by BuildCursor(), and PrepareCursorContent().
SetMultipleContinuousItemAction() [1/2]
protected void SetMultipleContinuousItemAction (string multiActionsWidget) inline private
shows arrows near the interact action if there are more than one available
Definition at line 656 of file ItemActionsWidget.c.
References m_Root.
SetMultipleContinuousItemAction() [2/2]
protected void SetMultipleContinuousItemAction (string multiActionsWidget, string multiActionsWidget_NotSelect) inline private
Definition at line 1217 of file ActionTargetsCursor.c.
References ContinuousDefaultActionInput(), and m_Root.
Referenced by BuildCursor(), and PrepareCursorContent().
SetMultipleInteractAction() [1/2]
protected void SetMultipleInteractAction (string multiActionsWidget) inline private
shows arrows near the interact action if there are more than one available
Definition at line 630 of file ItemActionsWidget.c.
References m_Root.
SetMultipleInteractAction() [2/2]
protected void SetMultipleInteractAction (string multiActionsWidget, string multiActionsWidget_NotSelect) inline private
shows arrows near the interact action if there are more than one available
Definition at line 1135 of file ActionTargetsCursor.c.
References m_Root.
Referenced by BuildCursor(), and PrepareCursorContent().
SetMultipleItemAction() [1/2]
protected void SetMultipleItemAction (string multiActionsWidget) inline private
Definition at line 647 of file ItemActionsWidget.c.
References m_Root.
SetMultipleItemAction() [2/2]
protected void SetMultipleItemAction (string multiActionsWidget, string multiActionsWidget_NotSelect) inline private
Definition at line 1190 of file ActionTargetsCursor.c.
References m_Root.
Referenced by BuildCursor(), and PrepareCursorContent().
SetMute() [1/2]
void SetMute (bool mute) inline private
Definition at line 81 of file PlayerListEntryScriptedWidget.c.
SetMute() [2/2]
void SetMute (string UID, bool mute) inline private
Definition at line 226 of file PlayerListScriptedWidget.c.
References UID.
SetName()
void SetName (string name) inline private
Definition at line 323 of file ServerBrowserEntry.c.
References name.
Referenced by FillInfo().
SetOptions() [1/4]
void SetOptions (GameOptions options) inline private
Definition at line 595 of file OptionsMenuControls.c.
References GameOptions::GetOptionByType(), and Revert().
Referenced by OptionsMenuControls(), and OptionsMenuVideo().
SetOptions() [2/4]
void SetOptions (GameOptions options) inline private
Definition at line 334 of file OptionsMenuGame.c.
References GameOptions::GetOptionByType().
SetOptions() [3/4]
void SetOptions (GameOptions options) inline private
Definition at line 326 of file OptionsMenuSounds.c.
References GameOptions::GetOptionByType(), and Revert().
SetOptions() [4/4]
void SetOptions (GameOptions options) inline private
Definition at line 301 of file OptionsMenuVideo.c.
References GameOptions::GetOptionByType().
SetOrientation()
void SetOrientation (vector orient) inline private
Definition at line 92 of file CTKeyframe.c.
References m_Orientation.
SetParentWidget()
void SetParentWidget () inline private
Definition at line 132 of file LayoutHolder.c.
References m_Parent.
SetPasswordLocked()
void SetPasswordLocked (bool locked) inline private
Definition at line 328 of file ServerBrowserEntry.c.
Referenced by FillInfo().
SetPin()
void SetPin (int pin) inline private
Definition at line 57 of file CTKeyframe.c.
Referenced by CTKeyframe().
SetPing()
void SetPing (int ping) inline private
Definition at line 361 of file ServerBrowserEntry.c.
References ARGBF().
Referenced by FillInfo().
SetPopulation()
void SetPopulation (int population, int slots) inline private
Definition at line 333 of file ServerBrowserEntry.c.
Referenced by FillInfo().
SetPosition() [1/2]
void SetPosition (vector pos) inline private
Definition at line 87 of file CTKeyframe.c.
References m_Position.
SetPosition() [2/2]
void SetPosition (vector position) inline private
Definition at line 46 of file CTObjectFollower.c.
References m_Position.
SetProgress()
private void SetProgress (float progress) inline private
Definition at line 140 of file ContinuousActionProgress.c.
Referenced by Update().
SetQuantityVisibility()
void SetQuantityVisibility (bool state) inline private
Definition at line 119 of file ActionTargetsCursor.c.
SetRadioFrequency()
protected void SetRadioFrequency (string freq, string itemWidget, string upWidget, string downWidget, bool enabled) inline private
Definition at line 580 of file ItemActionsWidget.c.
References Class::CastTo(), and m_Root.
Referenced by BuildCursor().
SetRotation()
void SetRotation (vector dir) inline private
Definition at line 57 of file CTObjectFollower.c.
References m_Orientation.
SetServerMapName()
void SetServerMapName () inline private
Definition at line 556 of file ServerBrowserEntry.c.
References GetMapName().
Referenced by FillInfo().
SetShard()
void SetShard (int shard) inline private
Definition at line 408 of file ServerBrowserEntry.c.
Referenced by FillInfo().
SetSingleXboxIcon() [1/2]
void SetSingleXboxIcon (string imageset_name, string image_name) inline private
Definition at line 127 of file ActionTargetsCursor.c.
SetSingleXboxIcon() [2/2]
void SetSingleXboxIcon (string imageset_name, string image_name) inline private
Definition at line 65 of file ItemActionsWidget.c.
SetSlots()
void SetSlots (int slots) inline private
Definition at line 356 of file ServerBrowserEntry.c.
Referenced by FillInfo().
SetTarget()
void SetTarget (Object obj) inline private
Definition at line 26 of file ObjectFollower.c.
References m_TargetObject.
SetText()
void SetText (string text) inline private
Definition at line 108 of file DropdownPrefab.c.
References m_Text.
Referenced by DropdownPrefab().
SetTime()
void SetTime (string time, float multiplier) inline private
Definition at line 377 of file ServerBrowserEntry.c.
References string::Split().
Referenced by FillInfo().
SetTimeBefore()
void SetTimeBefore (float time) inline private
Definition at line 107 of file CTKeyframe.c.
References ToString().
SetToDefaults() [1/4]
void SetToDefaults () inline private
Definition at line 425 of file OptionsMenuControls.c.
References Focus().
SetToDefaults() [2/4]
void SetToDefaults () inline private
Definition at line 285 of file OptionsMenuGame.c.
References g_Game.
SetToDefaults() [3/4]
void SetToDefaults () inline private
Definition at line 292 of file OptionsMenuSounds.c.
SetToDefaults() [4/4]
void SetToDefaults () inline private
Definition at line 282 of file OptionsMenuVideo.c.
References RefreshCustom().
SetValue()
void SetValue () inline private
Definition at line 55 of file ProfileOptionsUI.c.
References Class::CastTo(), and SetButtonStates().
Referenced by OnClick().
SetWeaponModeAndZeroing()
protected void SetWeaponModeAndZeroing (string itemWidget, string upWidget, string downWidget, bool enabled) inline private
Definition at line 547 of file ItemActionsWidget.c.
References Class::CastTo(), string::Format(), m_Player, and m_Root.
Referenced by BuildCursor().
SetWeaponQuantity()
protected void SetWeaponQuantity (int chamber, int mag, string itemWidget, string quantityPBWidget, string quantityTextWidget, bool enabled) inline private
Definition at line 457 of file ItemActionsWidget.c.
References Class::CastTo(), string::Format(), m_Root, and string::ToString().
Referenced by BuildCursor().
SetXboxIcon() [1/2]
protected void SetXboxIcon (string name, string imageset_name, string image_name) inline private
Definition at line 129 of file ActionTargetsCursor.c.
SetXboxIcon() [2/2]
protected void SetXboxIcon (string name, string imageset_name, string image_name) inline private
Definition at line 67 of file ItemActionsWidget.c.
Show() [1/3]
void Show () inline private
Definition at line 117 of file CTObjectFollower.c.
Show() [2/3]
void Show (bool show) inline private
Definition at line 97 of file ServerBrowserEntry.c.
References m_Root.
Show() [3/3]
void Show (int x, int y) inline private
Definition at line 36 of file ContextMenu.c.
References GetScreenSize(), m_count, String(), ToString(), AutoHeightSpacer::Update(), x, and y.
Referenced by ContainerWithElectricManager::ElectricityIcon(), and Container::UpdateRadialIcon().
ShowActionMenu()
void ShowActionMenu (InventoryItem item) inline private
Definition at line 31 of file LayoutHolder.c.
References ItemBase::GetDebugActions(), GetGame(), UIManager::GetMenu(), GetMousePos(), GetPlayer(), CGame::GetUIManager(), UIScriptedMenu::Hide(), and m_player.
ShowBackdrop()
void ShowBackdrop (bool show) inline private
Definition at line 103 of file ContextMenu.c.
ShowNewsfeed()
void ShowNewsfeed () inline private
Definition at line 42 of file MainMenuNewsfeed.c.
Referenced by MainMenuNewsfeed().
ShowNextPage()
private void ShowNextPage () inline private
Definition at line 134 of file UiHintPanel.c.
References PopulateLayout().
Referenced by OnClick(), and SlideshowThread().
ShowPreviousPage()
private void ShowPreviousPage () inline private
Definition at line 150 of file UiHintPanel.c.
References PopulateLayout().
Referenced by OnClick().
ShowStats()
void ShowStats () inline private
Definition at line 40 of file MainMenuStats.c.
References m_Root, and UpdateStats().
ShowTooltip() [1/2]
void ShowTooltip () inline private
Definition at line 150 of file ModsMenuDetailed.c.
ShowTooltip() [2/2]
void ShowTooltip (ModInfo mod_ref) inline private
Definition at line 17 of file ModsMenuTooltip.c.
References GetMousePos(), ModInfo::GetTooltip(), m_Root, m_Text, x, and y.
ShowXboxHidePCIcons() [1/2]
protected void ShowXboxHidePCIcons (string widget, bool show_xbox_icon) inline private
Definition at line 428 of file ActionTargetsCursor.c.
References m_Root.
Referenced by UpdatePCIconsVisibility().
ShowXboxHidePCIcons() [2/2]
protected void ShowXboxHidePCIcons (string widget, bool show_xbox_icon) inline private
Definition at line 76 of file ItemActionsWidget.c.
References m_Root.
SlideshowThread()
private void SlideshowThread () inline private
Definition at line 175 of file UiHintPanel.c.
References ShowNextPage().
StartEnteringAlternateKeybind() [1/3]
void StartEnteringAlternateKeybind () inline private
Definition at line 219 of file KeybindingElement.c.
StartEnteringAlternateKeybind() [2/3]
void StartEnteringAlternateKeybind () inline private
Definition at line 217 of file KeybindingElementNew.c.
StartEnteringAlternateKeybind() [3/3]
void StartEnteringAlternateKeybind (int key_index) inline private
Definition at line 149 of file KeybindingsGroup.c.
References m_Menu.
StartEnteringKeybind() [1/3]
void StartEnteringKeybind () inline private
Definition at line 208 of file KeybindingElement.c.
StartEnteringKeybind() [2/3]
void StartEnteringKeybind () inline private
Definition at line 206 of file KeybindingElementNew.c.
StartEnteringKeybind() [3/3]
void StartEnteringKeybind (int key_index) inline private
Definition at line 133 of file KeybindingsGroup.c.
References m_Menu.
StartSlideshow()
private void StartSlideshow () inline private
Definition at line 170 of file UiHintPanel.c.
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
Referenced by RestartSlideShow(), and UiHintPanel().
Stop()
void Stop () inline private
Definition at line 65 of file CTEvent.c.
References GetEventActor(), m_Callback, and m_Menu.
StopSlideShow()
private void StopSlideShow () inline private
Definition at line 180 of file UiHintPanel.c.
References CALL_CATEGORY_GUI, CGame::GetCallQueue(), GetGame(), and ScriptCallQueue::Remove().
Referenced by OnMouseEnter(), RestartSlideShow(), and ~UiHintPanel().
TextMapUpdateWidget() [1/4]
bool TextMapUpdateWidget (int key) inline private
Definition at line 323 of file OptionsMenuControls.c.
References Class::CastTo().
Referenced by OnFocus(), and UpdateLanguageOption().
TextMapUpdateWidget() [2/4]
bool TextMapUpdateWidget (int key) inline private
Definition at line 511 of file OptionsMenuGame.c.
References Class::CastTo().
TextMapUpdateWidget() [3/4]
bool TextMapUpdateWidget (int key) inline private
Definition at line 189 of file OptionsMenuSounds.c.
References Class::CastTo().
TextMapUpdateWidget() [4/4]
bool TextMapUpdateWidget (int key) inline private
Definition at line 582 of file OptionsMenuVideo.c.
References Class::CastTo().
ToggleDependentOptions() [1/4]
void ToggleDependentOptions (int mode, bool state) inline private
Definition at line 626 of file OptionsMenuControls.c.
ToggleDependentOptions() [2/4]
void ToggleDependentOptions (int mode, bool state) inline private
Definition at line 354 of file OptionsMenuGame.c.
ToggleDependentOptions() [3/4]
void ToggleDependentOptions (int mode, bool state) inline private
Definition at line 340 of file OptionsMenuSounds.c.
ToggleDependentOptions() [4/4]
void ToggleDependentOptions (int mode, bool state) inline private
Definition at line 339 of file OptionsMenuVideo.c.
ToggleExpand()
bool ToggleExpand () inline private
Definition at line 614 of file ServerBrowserEntry.c.
References m_IsExpanded, and SetExpand().
Referenced by OnMouseButtonUp().
ToggleFavorite()
bool ToggleFavorite () inline private
Definition at line 590 of file ServerBrowserEntry.c.
References m_IsFavorited, m_Root, and OnlineServices::SetServerFavorited().
Referenced by OnMouseButtonUp().
ToggleMute() [1/2]
void ToggleMute () inline private
Definition at line 87 of file PlayerListEntryScriptedWidget.c.
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), IsLocalPlayer(), m_Mute, and OnlineServices::MutePlayer().
Referenced by OnMouseButtonUp().
ToggleMute() [2/2]
void ToggleMute (string UID) inline private
Definition at line 234 of file PlayerListScriptedWidget.c.
References UID.
TransformToScreenPos()
protected vector TransformToScreenPos (vector pWorldPos) inline private
transform world pos to screen pos (related to parent widget size)
get relative pos for screen from world pos vector
get size of parent widget
calculate corrent position from relative pos and parent widget size
Definition at line 436 of file ActionTargetsCursor.c.
References GetGame(), CGame::GetScreenPosRelative(), and m_Root.
Referenced by BuildFloatingCursor(), and GetOnScreenPosition().
TutorialKeybinds()
void TutorialKeybinds (Widget parent, TutorialsMenu menu) inline private
Definition at line 8 of file ControlMappingKeybinds.c.
References WorkspaceWidget::CreateWidgets(), ErrorEx, Math::Floor(), Input::GetActionDesc(), UAInputAPI::GetActiveInputs(), GetGame(), CGame::GetInput(), UAInputAPI::GetInputByID(), GetLayoutName(), GetUApi(), CGame::GetWorkspace(), m_Menu, m_Root, name, SetElementModifier(), and SetElementTitle().
UiHintPanel()
void UiHintPanel (Widget parent_widget) inline private
Definition at line 26 of file UiHintPanel.c.
References BuildLayout(), LoadContentList(), PopulateLayout(), Print(), RandomizePageIndex(), and StartSlideshow().
Unselect() [1/2]
void Unselect () inline private
Definition at line 131 of file CTEvent.c.
References ARGBF(), and m_Root.
Unselect() [2/2]
void Unselect () inline private
Definition at line 128 of file CTKeyframe.c.
References ARGBF(), and m_Root.
Update() [1/7]
void Update () inline private
don't show floating widget if it's disabled in profile or the player is unconscious
check if action has target, otherwise don't show the widget
cursor with fixed position (environment interaction mainly)
build cursor for new target
use cached version for known target - recalculate onscreen pos only
Definition at line 296 of file ActionTargetsCursor.c.
References BuildFixedCursor(), BuildFloatingCursor(), CheckRefresherFlagVisibility(), g_Game, GetActionManager(), GetActions(), GetDayZGame(), GetGame(), GetPlayer(), GetTarget(), HideWidget(), Hud::IsHideHudPlayer(), m_AM, m_Continuous, m_Hidden, m_Hud, m_Player, m_Root, and m_Target.
Referenced by MainMenuButtonEffect::MainMenuButtonEffect(), OnUpdate(), and MainMenuButtonEffect::~MainMenuButtonEffect().
Update() [2/7]
protected void Update () inline private
don't show continuous action progressif it's disabled in profile OR soft-disabled by the '~' keyhold
Definition at line 56 of file ContinuousActionProgress.c.
References Math::AbsFloat(), Class::CastTo(), GetActionManager(), GetActions(), GetGame(), Mission::GetHud(), CGame::GetMission(), GetPlayer(), m_Action, m_AM, m_Player, m_Root, mission, Math::RAD2DEG, SetProgress(), UA_AM_PENDING, UA_INITIALIZE, UA_NONE, and UA_PROCESSING.
Update() [3/7]
protected void Update () inline private
don't show when disabled in profile
Definition at line 178 of file ItemActionsWidget.c.
References BuildCursor(), CheckForActionWidgetOverrides(), CheckRefresherFlagVisibility(), g_Game, GetActionManager(), GetActions(), GetEntityInHands(), GetGame(), GetPlayer(), Hud::IsHudVisible(), m_AM, m_Hud, m_Player, and m_Root.
Update() [4/7]
void Update () inline private
Definition at line 42 of file ObjectFollower.c.
References GetOnScreenPosition(), m_Root, m_TargetObject, m_Visible, x, and y.
Update() [5/7]
protected void Update () inline private
Update.
Definition at line 34 of file ProjectedCrosshair.c.
References DiagMenu::GetBool(), GetCrosshairPosition(), GetGame(), GetPlayer(), CGame::GetScreenPos(), IsInventoryOpen(), m_Debug, m_Player, m_Position, m_Root, m_Visible, and vector::Zero.
Update() [6/7]
void Update (float timeslice) inline private
Definition at line 36 of file CTObjectFollower.c.
Update() [7/7]
void Update (float timeslice) inline private
Definition at line 259 of file KeybindingsGroup.c.
References UAInputAPI::DeterminedCount(), UAInputAPI::DeterminePressedButton(), GetDayZGame(), UAInputAPI::GetDetermined(), GetUApi(), m_Menu, and name.
UpdateAdminOption()
protected void UpdateAdminOption (int new_index) inline private
Definition at line 416 of file OptionsMenuGame.c.
References m_Menu.
UpdateAudioLevel()
void UpdateAudioLevel () inline private
Definition at line 384 of file OptionsMenuSounds.c.
References GetAudioLevel(), and GetGame().
UpdateBleedingIndication()
protected void UpdateBleedingIndication (int new_index) inline private
Definition at line 391 of file OptionsMenuGame.c.
References m_Menu.
UpdateColors()
void UpdateColors () inline private
Definition at line 675 of file ServerBrowserEntry.c.
References ARGB(), IsOnline(), and m_Root.
Referenced by Darken(), Lighten(), and Preview().
UpdateConnectivityInfo()
protected void UpdateConnectivityInfo (int newIndex) inline private
Definition at line 396 of file OptionsMenuGame.c.
References m_Menu.
UpdateControllerInputIcons() [1/2]
private void UpdateControllerInputIcons () inline private
Loads icons from the latest keybinds.
Definition at line 167 of file ActionTargetsCursor.c.
References SetControllerIcon().
Referenced by OnInputPresetChanged(), and OnWidgetScriptInit().
UpdateControllerInputIcons() [2/2]
private void UpdateControllerInputIcons () inline private
Loads icons from the latest keybinds.
Definition at line 108 of file ItemActionsWidget.c.
References SetControllerIcon().
UpdateControlsElements()
protected void UpdateControlsElements () inline private
Definition at line 458 of file TabberUI.c.
References InputUtils::GetRichtextButtonIconFromInputAction(), InputUtils::ICON_SCALE_TOOLBAR, and m_Root.
Referenced by Init(), OnInputDeviceChanged(), and OnInputPresetChanged().
UpdateCrosshairOption()
protected void UpdateCrosshairOption (int new_index) inline private
Definition at line 401 of file OptionsMenuGame.c.
References m_Menu.
UpdateEffects()
void UpdateEffects (float value) inline private
Definition at line 354 of file OptionsMenuSounds.c.
References m_Menu.
UpdateEntry()
void UpdateEntry () inline private
Definition at line 309 of file ServerBrowserEntry.c.
References Darken(), Lighten(), m_Root, Select(), and SetFocus().
UpdateFOVOption()
protected void UpdateFOVOption (float new_value) inline private
Definition at line 379 of file OptionsMenuGame.c.
References g_Game, and m_Menu.
UpdateGameOption()
protected void UpdateGameOption (int new_index) inline private
Definition at line 411 of file OptionsMenuGame.c.
References m_Menu.
UpdateHUDOption()
protected void UpdateHUDOption (int new_index) inline private
Definition at line 386 of file OptionsMenuGame.c.
References m_Menu.
UpdateInputMode()
void UpdateInputMode (int newIndex) inline private
Definition at line 378 of file OptionsMenuSounds.c.
References m_Menu.
UpdateInterval()
void UpdateInterval () private
UpdateItems()
void UpdateItems (TItemsMap items, bool show_quantity, bool show_temperature) inline private
Definition at line 468 of file InventoryGrid.c.
References AddItem(), RefreshItemVariables(), RemoveItem(), and Vector().
UpdateLanguageOption()
protected void UpdateLanguageOption (int new_index) inline private
Definition at line 365 of file OptionsMenuGame.c.
References m_Menu, and TextMapUpdateWidget().
UpdateMaster()
void UpdateMaster (float value) inline private
Definition at line 348 of file OptionsMenuSounds.c.
References m_Menu.
UpdateMouseAimModHSensitivity()
void UpdateMouseAimModHSensitivity (float value) inline private
Definition at line 584 of file OptionsMenuControls.c.
References m_Menu.
UpdateMouseAimModVSensitivity()
void UpdateMouseAimModVSensitivity (float value) inline private
Definition at line 578 of file OptionsMenuControls.c.
References m_Menu.
UpdateMouseHSensitivity()
void UpdateMouseHSensitivity (float value) inline private
Definition at line 572 of file OptionsMenuControls.c.
References m_Menu.
UpdateMouseInvertView()
void UpdateMouseInvertView (int index) inline private
Definition at line 557 of file OptionsMenuControls.c.
References m_Menu.
UpdateMouseVSensitivity()
void UpdateMouseVSensitivity (float value) inline private
Definition at line 566 of file OptionsMenuControls.c.
References m_Menu.
UpdateMusic()
void UpdateMusic (float value) inline private
Definition at line 372 of file OptionsMenuSounds.c.
References m_Menu.
UpdatePauseOption()
protected void UpdatePauseOption (int new_index) inline private
Definition at line 373 of file OptionsMenuGame.c.
References m_Menu.
UpdatePCIconsVisibility() [1/2]
private void UpdatePCIconsVisibility () inline private
Contains logic for icon set switching (Gamepad/M&K)
Definition at line 176 of file ActionTargetsCursor.c.
References Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), Input::IsEnabledMouseAndKeyboardEvenOnServer(), and ShowXboxHidePCIcons().
Referenced by OnInputDeviceChanged(), and OnWidgetScriptInit().
UpdatePCIconsVisibility() [2/2]
private void UpdatePCIconsVisibility () inline private
Contains logic for icon set switching (Gamepad/M&K)
Definition at line 117 of file ItemActionsWidget.c.
References Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), Input::IsEnabledMouseAndKeyboardEvenOnServer(), and ShowXboxHidePCIcons().
UpdatePlayerOption()
protected void UpdatePlayerOption (int new_index) inline private
Definition at line 421 of file OptionsMenuGame.c.
References m_Menu.
UpdatePos()
void UpdatePos () inline private
Function updating the position of the tracker widget.
Currently tracks using GetScreenPos() on the position of the player.
Definition at line 90 of file CTObjectFollower.c.
References GetGame(), GetPosition, CGame::GetScreenPosRelative(), x, and y.
UpdateQuantityItems()
void UpdateQuantityItems () inline private
Definition at line 535 of file InventoryGrid.c.
References RefreshItemVariables(), and Math::Round().
UpdateQuickbarItems()
void UpdateQuickbarItems (TItemsMap items) inline private
Definition at line 396 of file InventoryGrid.c.
References AddItem(), InventoryGridController::CanAddItemInHandToInventory(), RefreshQuickbarItemVariables(), RemoveItem(), and Vector().
UpdateQuickbarOption()
protected void UpdateQuickbarOption (int new_index) inline private
Definition at line 406 of file OptionsMenuGame.c.
References m_Menu.
UpdateSelectionIcons()
void UpdateSelectionIcons () inline private
Definition at line 209 of file LayoutHolder.c.
UpdateServerInfoOption()
protected void UpdateServerInfoOption (int new_index) inline private
Definition at line 426 of file OptionsMenuGame.c.
References m_Menu.
UpdateStats()
void UpdateStats () inline private
Definition at line 51 of file MainMenuStats.c.
References GetDistanceString(), GetGame(), GetTimeString(), GetValueString(), AnalyticsManagerServer::STAT_DISTANCE, AnalyticsManagerServer::STAT_INFECTED_KILLED, AnalyticsManagerServer::STAT_LONGEST_SURVIVOR_HIT, AnalyticsManagerServer::STAT_PLAYERS_KILLED, and AnalyticsManagerServer::STAT_PLAYTIME.
Referenced by ShowStats().
UpdateTemperatureItems()
void UpdateTemperatureItems () inline private
Definition at line 551 of file InventoryGrid.c.
References RefreshItemVariables(), and Math::Round().
UpdateVOIP()
void UpdateVOIP (float value) inline private
Definition at line 360 of file OptionsMenuSounds.c.
References m_Menu.
UpdateVOIPThreshold()
void UpdateVOIPThreshold (float value) inline private
Definition at line 366 of file OptionsMenuSounds.c.
References m_Menu.
UpdateWasMicCapturing()
void UpdateWasMicCapturing () inline private
Definition at line 239 of file OptionsMenuSounds.c.
References GetGame().
Referenced by OnPartyChatChangedEvent(), and OnVonStateEvent().
WeaponModeTextTemp()
protected string WeaponModeTextTemp () inline private
Definition at line 575 of file ItemActionsWidget.c.
Field Documentation
ITEM_COLOR_DRAG
int ITEM_COLOR_DRAG = 0x0AFFFFFF static private
Definition at line 44 of file InventoryGrid.c.
ITEM_COLOR_NORMAL
int ITEM_COLOR_NORMAL = 0x0AFFFFFF static private
Definition at line 43 of file InventoryGrid.c.
ITEM_COLOR_QUICKBAR_H_BAD
int ITEM_COLOR_QUICKBAR_H_BAD = 0x2A980d0d static private
Definition at line 41 of file InventoryGrid.c.
ITEM_COLOR_QUICKBAR_H_GOOD
int ITEM_COLOR_QUICKBAR_H_GOOD = 0x2A6e980d static private
Definition at line 40 of file InventoryGrid.c.
ITEM_COLOR_QUICKBAR_I_BAD
int ITEM_COLOR_QUICKBAR_I_BAD = 0x2A986e0d static private
Definition at line 42 of file InventoryGrid.c.
ITEM_COLOR_QUICKBAR_NORMAL
int ITEM_COLOR_QUICKBAR_NORMAL = 0x0AFFFFFF static private
Definition at line 39 of file InventoryGrid.c.
ITEMS_COUNT
const int ITEMS_COUNT = 27 private
Definition at line 9 of file ContextMenu.c.
m_AcceleratedTimeFilter
ref OptionSelector m_AcceleratedTimeFilter private
Definition at line 23 of file ServerBrowserFilterContainer.c.
m_Action
protected ActionBase m_Action private
Definition at line 6 of file ContinuousActionProgress.c.
m_ActionPurchase
protected RichTextWidget m_ActionPurchase private
Definition at line 16 of file ModsMenuDetailedEntry.c.
m_ActionState
protected int m_ActionState private
Definition at line 7 of file ContinuousActionProgress.c.
m_ActionWebsite
protected RichTextWidget m_ActionWebsite private
Definition at line 15 of file ModsMenuDetailedEntry.c.
m_ActorIndex
protected int m_ActorIndex private
Definition at line 4 of file CTEvent.c.
m_AimHelperOption
protected ref SwitchOptionsAccess m_AimHelperOption private
Definition at line 23 of file OptionsMenuControls.c.
m_AimHelperSelector
protected ref OptionSelectorMultistate m_AimHelperSelector private
Definition at line 27 of file OptionsMenuControls.c.
m_AlternativeBindButton
protected ButtonWidget m_AlternativeBindButton private
Definition at line 10 of file KeybindingElement.c.
m_AlternativeClear
protected Widget m_AlternativeClear private
Definition at line 12 of file KeybindingElement.c.
m_AM [1/2]
protected ActionManagerClient m_AM private
Definition at line 64 of file ActionTargetsCursor.c.
m_AM [2/2]
protected ActionManagerBase m_AM private
Definition at line 8 of file ContinuousActionProgress.c.
m_am_entity1
protected EntityAI m_am_entity1 private
Definition at line 13 of file LayoutHolder.c.
m_am_entity2
protected EntityAI m_am_entity2 private
Definition at line 13 of file LayoutHolder.c.
m_AOOption
protected ref ListOptionsAccess m_AOOption private
Definition at line 74 of file OptionsMenuVideo.c.
m_AOSelector
protected ref OptionSelectorMultistate m_AOSelector private
Definition at line 42 of file OptionsMenuVideo.c.
m_ATOCOption
protected ref ListOptionsAccess m_ATOCOption private
Definition at line 73 of file OptionsMenuVideo.c.
m_ATOCSelector
protected ref OptionSelectorMultistate m_ATOCSelector private
Definition at line 41 of file OptionsMenuVideo.c.
m_AttemptOptionChange
ref ScriptInvoker m_AttemptOptionChange = new ScriptInvoker private
Definition at line 13 of file OptionSelectorBase.c.
m_AudioLevelTimer
protected ref Timer m_AudioLevelTimer private
Definition at line 26 of file OptionsMenuSounds.c.
m_Author
protected MultilineTextWidget m_Author private
Definition at line 13 of file ModsMenuDetailedEntry.c.
m_BackgroundWidgets
protected ref map<int, Widget> m_BackgroundWidgets private
Definition at line 48 of file InventoryGrid.c.
m_BattleyeFilter
ref OptionSelector m_BattleyeFilter private
Definition at line 14 of file ServerBrowserFilterContainer.c.
m_BleedingIndication
protected ref OptionSelectorMultistate m_BleedingIndication private
Definition at line 30 of file OptionsMenuGame.c.
m_BrightnessOption
protected ref NumericOptionsAccess m_BrightnessOption private
Definition at line 58 of file OptionsMenuVideo.c.
m_BrightnessSelector
protected ref OptionSelectorSlider m_BrightnessSelector private
Definition at line 26 of file OptionsMenuVideo.c.
m_Button
protected Widget m_Button private
Definition at line 9 of file DropdownPrefab.c.
m_CachedObject
protected ref ATCCachedObject m_CachedObject private
Definition at line 57 of file ActionTargetsCursor.c.
m_Callback
protected HumanCommandActionCallback m_Callback private
Definition at line 17 of file CTEvent.c.
m_CanAddItemInHandToInventory
protected bool m_CanAddItemInHandToInventory private
Definition at line 57 of file InventoryGrid.c.
Referenced by CanAddItemInHandToInventory().
m_CanSwitch
protected bool m_CanSwitch private
Definition at line 13 of file TabberUI.c.
Referenced by CanSwitchTab().
m_CharacterAliveFilter
ref OptionSelectorMultistate m_CharacterAliveFilter private
Definition at line 7 of file ServerBrowserFilterContainer.c.
m_Child
protected Widget m_Child private
Definition at line 10 of file SizeToChild.c.
m_ChildName
reference string m_ChildName private
Definition at line 3 of file SizeToChild.c.
m_CloseButton
protected Widget m_CloseButton private
Definition at line 5 of file ModsMenuDetailed.c.
m_col
private int m_col private
Definition at line 266 of file InventoryGrid.c.
m_commands
private ref array<ref CallQueueContext> m_commands private
Definition at line 6 of file ContextMenu.c.
m_ConnectivityInfo
protected ref OptionSelectorMultistate m_ConnectivityInfo private
Definition at line 31 of file OptionsMenuGame.c.
m_Container [1/2]
protected Widget m_Container private
Definition at line 80 of file ActionTargetsCursor.c.
m_Container [2/2]
protected KeybindingsContainer m_Container private
Definition at line 3 of file KeybindingElementNew.c.
m_Content [1/2]
protected Widget m_Content private
Definition at line 5 of file PlayerListScriptedWidget.c.
m_Content [2/2]
protected ref array<Widget> m_Content = new array<Widget> private
Definition at line 7 of file DropdownPrefab.c.
m_ContentContainer
protected Widget m_ContentContainer private
Definition at line 6 of file DropdownPrefab.c.
m_ContentList
private ref array<ref HintPage> m_ContentList private
Definition at line 20 of file UiHintPanel.c.
m_context_menu_panel_widget
private Widget m_context_menu_panel_widget private
Definition at line 5 of file ContextMenu.c.
m_context_menu_root_widget
private Widget m_context_menu_root_widget private
Definition at line 4 of file ContextMenu.c.
Referenced by ~ContextMenu().
m_Continuous
protected ActionBase m_Continuous private
Definition at line 63 of file ActionTargetsCursor.c.
Referenced by Update().
m_ContinuousInteract
protected ActionBase m_ContinuousInteract private
Definition at line 61 of file ActionTargetsCursor.c.
m_ContinuousInteractActionsNum
protected int m_ContinuousInteractActionsNum private
Definition at line 70 of file ActionTargetsCursor.c.
m_ContinuousItemActionsNum
protected int m_ContinuousItemActionsNum private
Definition at line 72 of file ActionTargetsCursor.c.
m_Controller
protected InventoryGridController m_Controller private
Definition at line 51 of file InventoryGrid.c.
Referenced by GetController().
m_ControllerLS_HSensitivityOption
protected ref NumericOptionsAccess m_ControllerLS_HSensitivityOption private
Definition at line 45 of file OptionsMenuControls.c.
m_ControllerLS_HSensitivitySelector
protected ref OptionSelectorSlider m_ControllerLS_HSensitivitySelector private
Definition at line 57 of file OptionsMenuControls.c.
m_ControllerLS_VehicleMod_HSensitivityOption
protected ref NumericOptionsAccess m_ControllerLS_VehicleMod_HSensitivityOption private
Definition at line 46 of file OptionsMenuControls.c.
m_ControllerLS_VehicleMod_HSensitivitySelector
protected ref OptionSelectorSlider m_ControllerLS_VehicleMod_HSensitivitySelector private
Definition at line 58 of file OptionsMenuControls.c.
m_ControllerLS_VSensitivityOption
protected ref NumericOptionsAccess m_ControllerLS_VSensitivityOption private
Definition at line 44 of file OptionsMenuControls.c.
m_ControllerLS_VSensitivitySelector
protected ref OptionSelectorSlider m_ControllerLS_VSensitivitySelector private
Definition at line 56 of file OptionsMenuControls.c.
m_ControllerRS_AimMod_CurvatureOption
protected ref NumericOptionsAccess m_ControllerRS_AimMod_CurvatureOption private
Definition at line 53 of file OptionsMenuControls.c.
m_ControllerRS_AimMod_CurvatureSelector
protected ref OptionSelectorSlider m_ControllerRS_AimMod_CurvatureSelector private
Definition at line 65 of file OptionsMenuControls.c.
m_ControllerRS_AimMod_HSensitivityOption
protected ref NumericOptionsAccess m_ControllerRS_AimMod_HSensitivityOption private
Definition at line 52 of file OptionsMenuControls.c.
m_ControllerRS_AimMod_HSensitivitySelector
protected ref OptionSelectorSlider m_ControllerRS_AimMod_HSensitivitySelector private
Definition at line 64 of file OptionsMenuControls.c.
m_ControllerRS_AimMod_VSensitivityOption
protected ref NumericOptionsAccess m_ControllerRS_AimMod_VSensitivityOption private
Definition at line 51 of file OptionsMenuControls.c.
m_ControllerRS_AimMod_VSensitivitySelector
protected ref OptionSelectorSlider m_ControllerRS_AimMod_VSensitivitySelector private
Definition at line 63 of file OptionsMenuControls.c.
m_ControllerRS_CurvatureOption
protected ref NumericOptionsAccess m_ControllerRS_CurvatureOption private
Definition at line 50 of file OptionsMenuControls.c.
m_ControllerRS_CurvatureSelector
protected ref OptionSelectorSlider m_ControllerRS_CurvatureSelector private
Definition at line 62 of file OptionsMenuControls.c.
m_ControllerRS_HSensitivityOption
protected ref NumericOptionsAccess m_ControllerRS_HSensitivityOption private
Definition at line 49 of file OptionsMenuControls.c.
m_ControllerRS_HSensitivitySelector
protected ref OptionSelectorSlider m_ControllerRS_HSensitivitySelector private
Definition at line 61 of file OptionsMenuControls.c.
m_ControllerRS_InvertOption
protected ref SwitchOptionsAccess m_ControllerRS_InvertOption private
Definition at line 47 of file OptionsMenuControls.c.
m_ControllerRS_InvertSelector
protected ref OptionSelectorMultistate m_ControllerRS_InvertSelector private
Definition at line 59 of file OptionsMenuControls.c.
m_ControllerRS_VSensitivityOption
protected ref NumericOptionsAccess m_ControllerRS_VSensitivityOption private
Definition at line 48 of file OptionsMenuControls.c.
m_ControllerRS_VSensitivitySelector
protected ref OptionSelectorSlider m_ControllerRS_VSensitivitySelector private
Definition at line 60 of file OptionsMenuControls.c.
m_count
private int m_count private
Definition at line 8 of file ContextMenu.c.
Referenced by Show().
m_CurrentSettingAlternateKeyIndex
protected int m_CurrentSettingAlternateKeyIndex = -1 private
Definition at line 9 of file KeybindingsGroup.c.
m_CurrentSettingKeyIndex
protected int m_CurrentSettingKeyIndex = -1 private
Definition at line 8 of file KeybindingsGroup.c.
m_CustomAlternateBind
protected ref array< int > m_CustomAlternateBind private
Definition at line 19 of file KeybindingElement.c.
Referenced by GetChangedAlternateBinds().
m_CustomBind
protected ref array< int > m_CustomBind private
Definition at line 18 of file KeybindingElement.c.
Referenced by GetChangedBinds().
m_Data [1/3]
protected ModInfo m_Data private
Definition at line 7 of file ModsMenuDetailed.c.
m_Data [2/3]
protected ModInfo m_Data private
Definition at line 21 of file ModsMenuDetailedEntry.c.
m_Data [3/3]
protected ref map<ModInfo, ref ModsMenuSimpleEntry> m_Data private
Definition at line 5 of file ModsMenuSimple.c.
m_DataPath
private const string m_DataPath = "Scripts/data/hints.json" private
Definition at line 9 of file UiHintPanel.c.
m_DayZForum
protected Widget m_DayZForum private
Definition at line 8 of file MainMenuNewsfeed.c.
m_Debug
protected bool m_Debug private
Definition at line 6 of file ProjectedCrosshair.c.
m_Description
protected RichTextWidget m_Description private
Definition at line 19 of file ModsMenuDetailedEntry.c.
m_Detail
protected Widget m_Detail private
Definition at line 4 of file ModsMenuDetailedEntry.c.
m_DetailMenu
protected ModsMenuDetailed m_DetailMenu private
Definition at line 6 of file ModsMenuSimple.c.
m_DetailsBodyConnectivity
protected Widget m_DetailsBodyConnectivity private
Definition at line 8 of file OptionsMenuControls.c.
m_DetailsBodyDefault
protected Widget m_DetailsBodyDefault private
Definition at line 7 of file OptionsMenuControls.c.
m_DetailsLabel
protected TextWidget m_DetailsLabel private
Definition at line 14 of file OptionsMenuControls.c.
m_DetailsRoot
protected Widget m_DetailsRoot private
Definition at line 4 of file ControlMappingKeybinds.c.
m_DetailsText
protected RichTextWidget m_DetailsText private
Definition at line 15 of file OptionsMenuControls.c.
m_Discord
protected Widget m_Discord private
Definition at line 6 of file MainMenuNewsfeed.c.
m_DisplayInteractTarget
protected Object m_DisplayInteractTarget private
Definition at line 58 of file ActionTargetsCursor.c.
Referenced by GetItemCargoCount(), GetItemDesc(), GetItemHealth(), and GetItemQuantity().
m_DisplayModeOption
protected ref ListOptionsAccess m_DisplayModeOption private
Definition at line 56 of file OptionsMenuVideo.c.
m_DisplayModeSelector
protected ref OptionSelectorMultistate m_DisplayModeSelector private
Definition at line 24 of file OptionsMenuVideo.c.
m_DistanceTraveled
protected Widget m_DistanceTraveled private
Definition at line 14 of file MainMenuStats.c.
m_DistanceTraveledValue
protected TextWidget m_DistanceTraveledValue private
Definition at line 15 of file MainMenuStats.c.
m_DLCFilter
ref OptionSelector m_DLCFilter private
Definition at line 11 of file ServerBrowserFilterContainer.c.
m_DLDLC
protected Widget m_DLDLC private
Definition at line 5 of file MainMenuNewsfeed.c.
m_DOFWidget
protected EditBoxWidget m_DOFWidget private
Definition at line 15 of file CTKeyframe.c.
m_EffectsOption
protected ref NumericOptionsAccess m_EffectsOption private
Definition at line 13 of file OptionsMenuSounds.c.
m_EffectsSelector
protected ref OptionSelectorSlider m_EffectsSelector private
Definition at line 20 of file OptionsMenuSounds.c.
m_ElementIndex
protected int m_ElementIndex private
Definition at line 14 of file KeybindingElement.c.
m_ElementModifier
protected TextWidget m_ElementModifier private
Definition at line 8 of file KeybindingElement.c.
m_ElementName
protected TextWidget m_ElementName private
Definition at line 7 of file KeybindingElement.c.
m_Enabled
protected bool m_Enabled private
Definition at line 7 of file OptionSelectorBase.c.
m_EntityInHands
protected EntityAI m_EntityInHands private
Definition at line 4 of file ItemActionsWidget.c.
m_Entries
protected ref map<string, ref PlayerListEntryScriptedWidget> m_Entries private
Definition at line 6 of file PlayerListScriptedWidget.c.
m_EntryTimer
protected ref Timer m_EntryTimer = new Timer(CALL_CATEGORY_GUI) private
Definition at line 21 of file KeybindingElement.c.
m_EventActorWidget
protected EditBoxWidget m_EventActorWidget private
Definition at line 12 of file CTEvent.c.
m_EventTime
protected float m_EventTime private
Definition at line 6 of file CTEvent.c.
Referenced by GetEventTime().
m_EventTimeWidget
protected EditBoxWidget m_EventTimeWidget private
Definition at line 13 of file CTEvent.c.
m_EventType
protected int m_EventType private
Definition at line 5 of file CTEvent.c.
m_EventTypeWidget
protected EditBoxWidget m_EventTypeWidget private
Definition at line 14 of file CTEvent.c.
m_EventWalkWidget
protected CheckBoxWidget m_EventWalkWidget private
Definition at line 15 of file CTEvent.c.
m_Expand
protected Widget m_Expand private
Definition at line 5 of file ServerBrowserEntry.c.
m_Faded
protected bool m_Faded private
Definition at line 11 of file ContinuousActionProgress.c.
m_FadeTimer
protected ref WidgetFadeTimer m_FadeTimer private
Definition at line 10 of file ContinuousActionProgress.c.
m_Favorite
protected Widget m_Favorite private
Definition at line 4 of file ServerBrowserEntry.c.
m_FavoritedFilter
ref OptionSelector m_FavoritedFilter private
Definition at line 12 of file ServerBrowserFilterContainer.c.
m_Feedback
protected Widget m_Feedback private
Definition at line 7 of file MainMenuNewsfeed.c.
m_FirstExpand
protected bool m_FirstExpand = true private
Definition at line 38 of file ServerBrowserEntry.c.
m_FirstInit
protected bool m_FirstInit = true private
Definition at line 3 of file TabberUI.c.
m_FixedOnPosition
protected bool m_FixedOnPosition private
Definition at line 76 of file ActionTargetsCursor.c.
m_FollowedObject
protected EntityAI m_FollowedObject private
Definition at line 8 of file CTObjectFollower.c.
m_FollowerButton
protected Widget m_FollowerButton private
Definition at line 4 of file CTObjectFollower.c.
m_FollowerRoot
protected Widget m_FollowerRoot private
Definition at line 3 of file CTObjectFollower.c.
m_FOVOption
protected ref NumericOptionsAccess m_FOVOption private
Definition at line 13 of file OptionsMenuGame.c.
m_FOVSelector
protected ref OptionSelectorSlider m_FOVSelector private
Definition at line 22 of file OptionsMenuGame.c.
m_FOVWidget
protected EditBoxWidget m_FOVWidget private
Definition at line 14 of file CTKeyframe.c.
m_FriendsPlayingFilter
ref OptionSelector m_FriendsPlayingFilter private
Definition at line 13 of file ServerBrowserFilterContainer.c.
m_FullServerFilter
ref OptionSelector m_FullServerFilter private
Definition at line 20 of file ServerBrowserFilterContainer.c.
m_GlobalMute
protected bool m_GlobalMute private
Definition at line 6 of file PlayerListEntryScriptedWidget.c.
Referenced by IsGloballyMuted().
m_GridSize
protected int m_GridSize private
Definition at line 55 of file InventoryGrid.c.
Referenced by GetGridSize().
m_Group
protected KeybindingsGroup m_Group private
Definition at line 4 of file KeybindingElement.c.
m_HasLogoOver
protected bool m_HasLogoOver private
Definition at line 7 of file ModsMenuSimpleEntry.c.
m_HealthEnabled
protected bool m_HealthEnabled private
Definition at line 74 of file ActionTargetsCursor.c.
m_Hidden
protected bool m_Hidden private
Definition at line 77 of file ActionTargetsCursor.c.
Referenced by Update().
m_Highlighted
protected ModInfo m_Highlighted private
Definition at line 9 of file ModsMenuDetailed.c.
Referenced by GetHighlighted().
m_Holder
protected Widget m_Holder private
Definition at line 10 of file DropdownPrefab.c.
m_HorizontalOffset
reference float m_HorizontalOffset private
Definition at line 4 of file SizeToChild.c.
Referenced by ResizeParentToChild().
m_Hover
protected Widget m_Hover private
Definition at line 5 of file ModsMenuSimpleEntry.c.
m_Hud
protected IngameHud m_Hud private
Definition at line 65 of file ActionTargetsCursor.c.
m_HudDebug
HudDebug m_HudDebug private
Definition at line 6 of file HudDebug.c.
Referenced by GetHudDebug().
m_HWAAOption
protected ref ListOptionsAccess m_HWAAOption private
Definition at line 72 of file OptionsMenuVideo.c.
m_HWAASelector
protected ref OptionSelectorMultistate m_HWAASelector private
Definition at line 40 of file OptionsMenuVideo.c.
m_Icon
protected ImageWidget m_Icon private
Definition at line 4 of file ModsMenuSimpleEntry.c.
m_IconBig
protected ImageWidget m_IconBig private
Definition at line 12 of file ModsMenuDetailedEntry.c.
m_IconCollapse
protected ImageWidget m_IconCollapse private
Definition at line 8 of file ModsMenuDetailedEntry.c.
m_IconSmall
protected ImageWidget m_IconSmall private
Definition at line 7 of file ModsMenuDetailedEntry.c.
m_IgnoredBool
protected bool m_IgnoredBool static private
Definition at line 12 of file SizeToChild.c.
m_ImageCollapse
protected ImageWidget m_ImageCollapse private
Definition at line 13 of file DropdownPrefab.c.
m_ImageExpand
protected ImageWidget m_ImageExpand private
Definition at line 12 of file DropdownPrefab.c.
m_ImmedUpdate
protected bool m_ImmedUpdate private
Definition at line 10 of file LayoutHolder.c.
m_Index
protected int m_Index private
Definition at line 3 of file CTEvent.c.
m_IndexWidget
protected TextWidget m_IndexWidget private
Definition at line 11 of file CTEvent.c.
m_InfectedKilled
protected Widget m_InfectedKilled private
Definition at line 11 of file MainMenuStats.c.
m_InfectedKilledValue
protected TextWidget m_InfectedKilledValue private
Definition at line 12 of file MainMenuStats.c.
m_InitProgress
protected float m_InitProgress private
Definition at line 13 of file ContinuousActionProgress.c.
m_InitTimer
ref Timer m_InitTimer private
Definition at line 17 of file TabberUI.c.
m_InputModeOption
protected ref ListOptionsAccess m_InputModeOption private
Definition at line 17 of file OptionsMenuSounds.c.
m_InputModeSelector
protected ref OptionSelectorMultistate m_InputModeSelector private
Definition at line 24 of file OptionsMenuSounds.c.
m_Interact
protected ActionBase m_Interact private
Definition at line 60 of file ActionTargetsCursor.c.
m_InteractActionsNum
protected int m_InteractActionsNum private
Definition at line 69 of file ActionTargetsCursor.c.
m_InterpTime
protected float m_InterpTime private
Definition at line 4 of file CTKeyframe.c.
Referenced by GetInterpTime().
m_InterpTimeWidget
protected EditBoxWidget m_InterpTimeWidget private
Definition at line 13 of file CTKeyframe.c.
m_IsActive
protected bool m_IsActive private
Definition at line 9 of file LayoutHolder.c.
m_IsAlternateEdited
protected bool m_IsAlternateEdited private
Definition at line 16 of file KeybindingElement.c.
Referenced by IsAlternateChanged().
m_IsDebugOutput
reference bool m_IsDebugOutput private
Definition at line 46 of file InventoryGrid.c.
m_IsEdited
protected bool m_IsEdited private
Definition at line 15 of file KeybindingElement.c.
Referenced by IsChanged().
m_IsExpanded
protected bool m_IsExpanded private
Definition at line 15 of file DropdownPrefab.c.
Referenced by Close(), OnMouseButtonDown(), and SetExpand().
m_IsFavorited
protected bool m_IsFavorited private
Definition at line 31 of file ServerBrowserEntry.c.
Referenced by ToggleFavorite().
m_IsMouseLeftDown
protected bool m_IsMouseLeftDown private
Definition at line 56 of file InventoryGrid.c.
m_IsOnline
protected bool m_IsOnline private
Definition at line 32 of file ServerBrowserEntry.c.
Referenced by IsOnline().
m_IsOpen
protected bool m_IsOpen private
Definition at line 23 of file ModsMenuDetailedEntry.c.
m_ItemActionsNum
protected int m_ItemActionsNum private
Definition at line 71 of file ActionTargetsCursor.c.
m_ItemLeft
protected Widget m_ItemLeft private
Definition at line 81 of file ActionTargetsCursor.c.
m_Items
protected ref TItemsMap m_Items private
Definition at line 50 of file InventoryGrid.c.
Referenced by GetItems().
m_ItemWidgets
protected ref map<int, Widget> m_ItemWidgets private
Definition at line 49 of file InventoryGrid.c.
m_KBDropdown
protected ref DropdownPrefab m_KBDropdown private
Definition at line 11 of file KeybindingsGroup.c.
m_Keybindings
protected GridSpacerWidget m_Keybindings private
Definition at line 16 of file OptionsMenuControls.c.
m_KeyboardFilter
ref OptionSelector m_KeyboardFilter private
Definition at line 17 of file ServerBrowserFilterContainer.c.
m_KeyboardOption
protected ref SwitchOptionsAccess m_KeyboardOption private
Definition at line 22 of file OptionsMenuControls.c.
m_KeyboardSelector
protected ref OptionSelectorMultistate m_KeyboardSelector private
Definition at line 26 of file OptionsMenuControls.c.
m_KeyWidgets
protected ref map<int, ref KeybindingElement> m_KeyWidgets private
Definition at line 7 of file KeybindingsGroup.c.
m_LanguageOption
protected ref ListOptionsAccess m_LanguageOption private
Definition at line 14 of file OptionsMenuGame.c.
m_LanguageSelector
protected ref OptionSelectorMultistate m_LanguageSelector private
Definition at line 21 of file OptionsMenuGame.c.
m_LayoutName
protected string m_LayoutName private
Definition at line 7 of file LayoutHolder.c.
m_LoaderImage
protected ImageWidget m_LoaderImage private
Definition at line 18 of file ContinuousActionProgress.c.
m_LongRangeShot
protected Widget m_LongRangeShot private
Definition at line 17 of file MainMenuStats.c.
m_LongRangeShotValue
protected TextWidget m_LongRangeShotValue private
Definition at line 18 of file MainMenuStats.c.
m_MainText1
protected TextWidget m_MainText1 private
Definition at line 12 of file MainMenuNewsfeed.c.
m_MainText2
protected TextWidget m_MainText2 private
Definition at line 13 of file MainMenuNewsfeed.c.
m_MainText3
protected TextWidget m_MainText3 private
Definition at line 14 of file MainMenuNewsfeed.c.
m_MainWidget
protected Widget m_MainWidget private
Definition at line 3 of file LayoutHolder.c.
m_MasterOption
protected ref NumericOptionsAccess m_MasterOption private
Definition at line 12 of file OptionsMenuSounds.c.
m_MasterSelector
protected ref OptionSelectorSlider m_MasterSelector private
Definition at line 19 of file OptionsMenuSounds.c.
m_max_item_width
private int m_max_item_width private
Definition at line 7 of file ContextMenu.c.
m_MaxFade
protected float m_MaxFade private
Definition at line 10 of file CTObjectFollower.c.
m_MaxWidthChild
protected float m_MaxWidthChild private
widget width
Definition at line 84 of file ActionTargetsCursor.c.
m_Menu [1/5]
protected OptionsMenu m_Menu private
Definition at line 8 of file CTEvent.c.
m_Menu [2/5]
protected TutorialsMenu m_Menu private
Definition at line 6 of file ControlMappingKeybinds.c.
m_Menu [3/5]
protected KeybindingsMenu m_Menu private
Definition at line 5 of file KeybindingsGroup.c.
m_Menu [4/5]
protected UIScriptedMenu m_Menu private
Definition at line 12 of file ModsMenuDetailed.c.
m_Menu [5/5]
protected OptionsMenu m_Menu private
Definition at line 19 of file OptionsMenuControls.c.
m_MicrophoneIcon
protected ImageWidget m_MicrophoneIcon private
Definition at line 11 of file PlayerListEntryScriptedWidget.c.
m_MinFade
protected float m_MinFade private
Definition at line 11 of file CTObjectFollower.c.
m_MissionGameplay
protected MissionGameplay m_MissionGameplay private
Definition at line 29 of file OptionsMenuSounds.c.
m_ModButton
protected ButtonWidget m_ModButton private
Definition at line 3 of file ModsMenuSimpleEntry.c.
Referenced by ~ModsMenuSimpleEntry().
m_Mods
protected ref array<string> m_Mods private
Definition at line 28 of file ServerBrowserEntry.c.
m_MoreButton
protected Widget m_MoreButton private
Definition at line 4 of file ModsMenuSimple.c.
m_Mouse_AimMod_HSensitivityOption
protected ref NumericOptionsAccess m_Mouse_AimMod_HSensitivityOption private
Definition at line 34 of file OptionsMenuControls.c.
m_Mouse_AimMod_HSensitivitySelector
protected ref OptionSelectorSlider m_Mouse_AimMod_HSensitivitySelector private
Definition at line 41 of file OptionsMenuControls.c.
m_Mouse_AimMod_VSensitivityOption
protected ref NumericOptionsAccess m_Mouse_AimMod_VSensitivityOption private
Definition at line 33 of file OptionsMenuControls.c.
m_Mouse_AimMod_VSensitivitySelector
protected ref OptionSelectorSlider m_Mouse_AimMod_VSensitivitySelector private
Definition at line 40 of file OptionsMenuControls.c.
m_Mouse_HSensitivityOption
protected ref NumericOptionsAccess m_Mouse_HSensitivityOption private
Definition at line 32 of file OptionsMenuControls.c.
m_Mouse_HSensitivitySelector
protected ref OptionSelectorSlider m_Mouse_HSensitivitySelector private
Definition at line 39 of file OptionsMenuControls.c.
m_Mouse_InvertOption
protected ref SwitchOptionsAccess m_Mouse_InvertOption private
Definition at line 30 of file OptionsMenuControls.c.
m_Mouse_InvertSelector
protected ref OptionSelectorMultistate m_Mouse_InvertSelector private
Definition at line 37 of file OptionsMenuControls.c.
m_Mouse_VSensitivityOption
protected ref NumericOptionsAccess m_Mouse_VSensitivityOption private
Definition at line 31 of file OptionsMenuControls.c.
m_Mouse_VSensitivitySelector
protected ref OptionSelectorSlider m_Mouse_VSensitivitySelector private
Definition at line 38 of file OptionsMenuControls.c.
m_MusicOption
protected ref NumericOptionsAccess m_MusicOption private
Definition at line 16 of file OptionsMenuSounds.c.
m_MusicSelector
protected ref OptionSelectorSlider m_MusicSelector private
Definition at line 23 of file OptionsMenuSounds.c.
m_Mute
protected bool m_Mute private
Definition at line 5 of file PlayerListEntryScriptedWidget.c.
Referenced by IsMuted(), and ToggleMute().
m_MuteIcon
protected ImageWidget m_MuteIcon private
Definition at line 12 of file PlayerListEntryScriptedWidget.c.
m_Name [1/2]
protected string m_Name private
Definition at line 3 of file PlayerListEntryScriptedWidget.c.
m_Name [2/2]
protected TextWidget m_Name private
Definition at line 9 of file ModsMenuDetailedEntry.c.
m_ObjectDetailOption
protected ref ListOptionsAccess m_ObjectDetailOption private
Definition at line 63 of file OptionsMenuVideo.c.
m_ObjectDetailSelector
protected ref OptionSelectorMultistate m_ObjectDetailSelector private
Definition at line 31 of file OptionsMenuVideo.c.
m_on_drag_item
private Widget m_on_drag_item private
Definition at line 265 of file InventoryGrid.c.
m_OnAttemptTabSwitch
ref ScriptInvoker m_OnAttemptTabSwitch = new ScriptInvoker() private
Definition at line 16 of file TabberUI.c.
m_OnSelectItem
ref ScriptInvoker m_OnSelectItem = new ScriptInvoker() private
Definition at line 16 of file DropdownPrefab.c.
m_OnTabSwitch
ref ScriptInvoker m_OnTabSwitch = new ScriptInvoker() private
Definition at line 15 of file TabberUI.c.
m_OptionChanged
ref ScriptInvoker m_OptionChanged = new ScriptInvoker private
Definition at line 14 of file OptionSelectorBase.c.
m_OptionFocused
ref ScriptInvoker m_OptionFocused = new ScriptInvoker private
Definition at line 11 of file OptionSelectorBase.c.
m_Options [1/2]
protected GameOptions m_Options private
Definition at line 18 of file OptionsMenuControls.c.
m_Options [2/2]
ref map<string, string> m_Options = new map<string, string> private
Definition at line 3 of file ServerBrowserFilterContainer.c.
m_OptionUnfocused
ref ScriptInvoker m_OptionUnfocused = new ScriptInvoker private
Definition at line 12 of file OptionSelectorBase.c.
m_Orientation
protected vector m_Orientation private
Definition at line 8 of file CTKeyframe.c.
Referenced by GetOrientation().
m_OverallQualityOption
protected ref ListOptionsAccess m_OverallQualityOption private
Definition at line 53 of file OptionsMenuVideo.c.
m_OverallQualitySelector
protected ref OptionSelectorMultistate m_OverallQualitySelector private
Definition at line 21 of file OptionsMenuVideo.c.
m_Owner
PluginItemDiagnostic m_Owner private
Definition at line 3 of file PluginItemDiagnostic.c.
m_PageIndex
private int m_PageIndex private
Definition at line 21 of file UiHintPanel.c.
m_Parent [1/2]
protected Widget m_Parent private
Definition at line 6 of file LayoutHolder.c.
m_Parent [2/2]
protected Widget m_Parent private
Definition at line 4 of file DropdownPrefab.c.
m_ParentClass
protected ScriptedWidgetEventHandler m_ParentClass private
Definition at line 9 of file OptionSelectorBase.c.
m_ParentMenu [1/2]
protected ModsMenuDetailed m_ParentMenu private
Definition at line 22 of file ModsMenuDetailedEntry.c.
m_ParentMenu [2/2]
protected ModsMenuSimple m_ParentMenu private
Definition at line 9 of file ModsMenuSimpleEntry.c.
m_ParentWidget
protected Widget m_ParentWidget private
Definition at line 5 of file LayoutHolder.c.
m_PasswordFilter
ref OptionSelector m_PasswordFilter private
Definition at line 15 of file ServerBrowserFilterContainer.c.
m_PauseOption
protected ref ListOptionsAccess m_PauseOption private
Definition at line 15 of file OptionsMenuGame.c.
m_PauseSelector
protected ref OptionSelectorMultistate m_PauseSelector private
Definition at line 32 of file OptionsMenuGame.c.
m_PingFilter
ref OptionSelectorMultistate m_PingFilter private
Definition at line 10 of file ServerBrowserFilterContainer.c.
m_PinWidget
protected EditBoxWidget m_PinWidget private
Definition at line 16 of file CTKeyframe.c.
m_PivotYOffset
reference int m_PivotYOffset private
Definition at line 3 of file ObjectFollower.c.
Referenced by GetOnScreenPosition().
m_Player
protected PlayerBase m_Player private
Definition at line 55 of file ActionTargetsCursor.c.
m_PlayerAvatar
protected ImageWidget m_PlayerAvatar private
Definition at line 10 of file PlayerListEntryScriptedWidget.c.
m_PlayerButton
protected ButtonWidget m_PlayerButton private
Definition at line 13 of file PlayerListEntryScriptedWidget.c.
Referenced by GetButtonWidget().
m_PlayerName
protected TextWidget m_PlayerName private
Definition at line 9 of file PlayerListEntryScriptedWidget.c.
m_PlayersKilled
protected Widget m_PlayersKilled private
Definition at line 8 of file MainMenuStats.c.
m_PlayersKilledValue
protected TextWidget m_PlayersKilledValue private
Definition at line 9 of file MainMenuStats.c.
m_Position
protected vector m_Position private
Definition at line 7 of file CTKeyframe.c.
Referenced by GetPosition().
m_PPAAOption
protected ref ListOptionsAccess m_PPAAOption private
Definition at line 71 of file OptionsMenuVideo.c.
m_PPAASelector
protected ref OptionSelectorMultistate m_PPAASelector private
Definition at line 39 of file OptionsMenuVideo.c.
m_pPluginInfectedDebug
PluginDayZInfectedDebug m_pPluginInfectedDebug private
Definition at line 18 of file PluginDayZInfectedDebug.c.
m_PPQualityOption
protected ref ListOptionsAccess m_PPQualityOption private
Definition at line 75 of file OptionsMenuVideo.c.
m_PPQualitySelector
protected ref OptionSelectorMultistate m_PPQualitySelector private
Definition at line 43 of file OptionsMenuVideo.c.
m_PreviouslyPlayedFilter
ref OptionSelector m_PreviouslyPlayedFilter private
Definition at line 18 of file ServerBrowserFilterContainer.c.
m_PrimaryBindButton
protected ButtonWidget m_PrimaryBindButton private
Definition at line 9 of file KeybindingElement.c.
m_PrimaryClear
protected Widget m_PrimaryClear private
Definition at line 11 of file KeybindingElement.c.
m_profileOption
int m_profileOption private
Definition at line 99 of file ProfileOptionsUI.c.
Referenced by GetProfileOption().
m_PublicFilter
ref OptionSelector m_PublicFilter private
Definition at line 22 of file ServerBrowserFilterContainer.c.
m_QuantityEnabled
protected bool m_QuantityEnabled private
Definition at line 75 of file ActionTargetsCursor.c.
m_QuickbarButton
protected ButtonWidget m_QuickbarButton private
Definition at line 11 of file OptionsMenuGame.c.
m_Radial
ref RadialProgressBar m_Radial private
Definition at line 19 of file ContinuousActionProgress.c.
m_RadialWidget
protected Widget m_RadialWidget private
Definition at line 17 of file ContinuousActionProgress.c.
m_RegionFilter
ref OptionSelectorMultistate m_RegionFilter private
Definition at line 9 of file ServerBrowserFilterContainer.c.
m_ResizeHorizontal
reference bool m_ResizeHorizontal private
Definition at line 6 of file SizeToChild.c.
m_ResizeVertical
reference bool m_ResizeVertical private
Definition at line 7 of file SizeToChild.c.
m_ResolutionMultiplier
protected float m_ResolutionMultiplier private
Definition at line 12 of file TabberUI.c.
Referenced by AlignTabbers().
m_ResolutionOption
protected ref ListOptionsAccess m_ResolutionOption private
Definition at line 57 of file OptionsMenuVideo.c.
m_ResolutionSelector
protected ref OptionSelectorMultistate m_ResolutionSelector private
Definition at line 25 of file OptionsMenuVideo.c.
m_Root
protected Widget m_Root private
Definition at line 9 of file SizeToChild.c.
Referenced by GetRoot(), GetWidget(), ~CTEvent(), ~CTKeyframe(), ~ModsMenuDetailed(), ~ModsMenuDetailedEntry(), ~ModsMenuSimple(), ~ModsMenuTooltip(), ~PlayerListEntryScriptedWidget(), ~PlayerListScriptedWidget(), and ~ServerBrowserEntry().
m_RootFrame
private Widget m_RootFrame private
Definition at line 11 of file UiHintPanel.c.
m_RootHeight
protected float m_RootHeight private
Definition at line 86 of file ActionTargetsCursor.c.
m_RootPath
private const string m_RootPath = "Gui/layouts/new_ui/hints/in_game_hints.layout" private
Definition at line 8 of file UiHintPanel.c.
m_RootWidget
protected Widget m_RootWidget private
Definition at line 4 of file LayoutHolder.c.
m_RootWidth
protected float m_RootWidth private
Definition at line 85 of file ActionTargetsCursor.c.
m_Scroll
protected ScrollWidget m_Scroll private
Definition at line 6 of file ModsMenuDetailed.c.
m_ScrollContainer
protected ScrollWidget m_ScrollContainer private
Definition at line 4 of file PlayerListScriptedWidget.c.
m_Scroller
protected ScrollWidget m_Scroller private
Definition at line 5 of file DropdownPrefab.c.
m_SearchByIP
protected EditBoxWidget m_SearchByIP private
Definition at line 6 of file ServerBrowserFilterContainer.c.
m_SearchByName
protected EditBoxWidget m_SearchByName private
Definition at line 5 of file ServerBrowserFilterContainer.c.
m_SecText1
protected TextWidget m_SecText1 private
Definition at line 15 of file MainMenuNewsfeed.c.
m_SecText2
protected TextWidget m_SecText2 private
Definition at line 16 of file MainMenuNewsfeed.c.
m_SecText3
protected TextWidget m_SecText3 private
Definition at line 17 of file MainMenuNewsfeed.c.
m_Selected
protected bool m_Selected private
Definition at line 16 of file PlayerListEntryScriptedWidget.c.
m_SelectedActionCategory
protected m_SelectedActionCategory private
Definition at line 73 of file ActionTargetsCursor.c.
m_SelectedEntry
protected PlayerListEntryScriptedWidget m_SelectedEntry private
Definition at line 9 of file PlayerListScriptedWidget.c.
Referenced by GetSelectedPlayer().
m_SelectedIndex
protected int m_SelectedIndex private
Definition at line 11 of file TabberUI.c.
Referenced by GetSelectedIndex().
m_SelectorType
protected int m_SelectorType = 0 private
Definition at line 3 of file OptionSelectorBase.c.
m_ServerAcceleration
protected TextWidget m_ServerAcceleration private
Definition at line 24 of file ServerBrowserEntry.c.
m_ServerBattleye
protected TextWidget m_ServerBattleye private
Definition at line 22 of file ServerBrowserEntry.c.
m_ServerCharacterAlive
protected TextWidget m_ServerCharacterAlive private
Definition at line 19 of file ServerBrowserEntry.c.
m_ServerData
protected ref GetServersResultRow m_ServerData private
Definition at line 34 of file ServerBrowserEntry.c.
m_ServerFriends
protected TextWidget m_ServerFriends private
Definition at line 20 of file ServerBrowserEntry.c.
m_ServerIP
protected TextWidget m_ServerIP private
Definition at line 23 of file ServerBrowserEntry.c.
m_ServerLock
protected ImageWidget m_ServerLock private
Definition at line 13 of file ServerBrowserEntry.c.
m_ServerMaKIcon
protected ImageWidget m_ServerMaKIcon private
Definition at line 15 of file ServerBrowserEntry.c.
m_ServerMap
protected TextWidget m_ServerMap private
Definition at line 25 of file ServerBrowserEntry.c.
m_ServerMode
protected TextWidget m_ServerMode private
Definition at line 21 of file ServerBrowserEntry.c.
m_ServerModIcon
protected ImageWidget m_ServerModIcon private
Definition at line 14 of file ServerBrowserEntry.c.
m_ServerMods
protected TextWidget m_ServerMods private
Definition at line 26 of file ServerBrowserEntry.c.
m_ServerModsExpand
protected ButtonWidget m_ServerModsExpand private
Definition at line 27 of file ServerBrowserEntry.c.
m_ServerName
protected TextWidget m_ServerName private
Definition at line 8 of file ServerBrowserEntry.c.
m_ServerPing
protected TextWidget m_ServerPing private
Definition at line 11 of file ServerBrowserEntry.c.
m_ServerPopulation
protected TextWidget m_ServerPopulation private
Definition at line 9 of file ServerBrowserEntry.c.
m_ServerShard
protected TextWidget m_ServerShard private
Definition at line 18 of file ServerBrowserEntry.c.
m_ServerSlots
protected TextWidget m_ServerSlots private
Definition at line 10 of file ServerBrowserEntry.c.
m_ServerTime
protected ImageWidget m_ServerTime private
Definition at line 12 of file ServerBrowserEntry.c.
m_SettingsRoot
protected Widget m_SettingsRoot private
Definition at line 5 of file OptionsMenuControls.c.
m_ShadowDetailOption
protected ref ListOptionsAccess m_ShadowDetailOption private
Definition at line 66 of file OptionsMenuVideo.c.
m_ShadowDetailSelector
protected ref OptionSelectorMultistate m_ShadowDetailSelector private
Definition at line 34 of file OptionsMenuVideo.c.
m_ShowAdminSelector
protected ref OptionSelectorMultistate m_ShowAdminSelector private
Definition at line 27 of file OptionsMenuGame.c.
m_ShowCrosshairSelector
protected ref OptionSelectorMultistate m_ShowCrosshairSelector private
Definition at line 24 of file OptionsMenuGame.c.
m_ShowGameSelector
protected ref OptionSelectorMultistate m_ShowGameSelector private
Definition at line 26 of file OptionsMenuGame.c.
m_ShowHUDSelector
protected ref OptionSelectorMultistate m_ShowHUDSelector private
Definition at line 23 of file OptionsMenuGame.c.
m_ShowPlayerSelector
protected ref OptionSelectorMultistate m_ShowPlayerSelector private
Definition at line 28 of file OptionsMenuGame.c.
m_ShowQuickbarSelector
protected ref OptionSelectorMultistate m_ShowQuickbarSelector private
Definition at line 25 of file OptionsMenuGame.c.
m_ShowServerInfoSelector
protected ref OptionSelectorMultistate m_ShowServerInfoSelector private
Definition at line 29 of file OptionsMenuGame.c.
m_Single
protected ActionBase m_Single private
Definition at line 62 of file ActionTargetsCursor.c.
m_SlideShowDelay
private const int m_SlideShowDelay = 25000 private
Definition at line 7 of file UiHintPanel.c.
m_SortingFilter
ref OptionSelectorMultistate m_SortingFilter private
Definition at line 8 of file ServerBrowserFilterContainer.c.
m_SpacerFrame
private Widget m_SpacerFrame private
Definition at line 12 of file UiHintPanel.c.
m_Speed
protected float m_Speed private
Definition at line 14 of file ContinuousActionProgress.c.
m_SSRQualityOption
protected ref ListOptionsAccess m_SSRQualityOption private
Definition at line 76 of file OptionsMenuVideo.c.
m_SSRQualitySelector
protected ref OptionSelectorMultistate m_SSRQualitySelector private
Definition at line 44 of file OptionsMenuVideo.c.
m_Tab [1/2]
protected ServerBrowserTab m_Tab private
Definition at line 15 of file PlayerListEntryScriptedWidget.c.
m_Tab [2/2]
protected ServerBrowserTab m_Tab private
Definition at line 36 of file ServerBrowserEntry.c.
m_TabControls
protected ref map<int, Widget> m_TabControls private
Definition at line 8 of file TabberUI.c.
m_TabControlsRoot
protected Widget m_TabControlsRoot private
Definition at line 5 of file TabberUI.c.
m_Tabs
protected ref map<int, Widget> m_Tabs private
Definition at line 9 of file TabberUI.c.
m_TabsCount
protected int m_TabsCount private
Definition at line 7 of file TabberUI.c.
Referenced by Init().
m_Target
protected ActionTarget m_Target private
Definition at line 56 of file ActionTargetsCursor.c.
m_TargetObject
protected Object m_TargetObject private
Definition at line 6 of file ObjectFollower.c.
m_TerrainDetailOption
protected ref ListOptionsAccess m_TerrainDetailOption private
Definition at line 64 of file OptionsMenuVideo.c.
m_TerrainDetailSelector
protected ref OptionSelectorMultistate m_TerrainDetailSelector private
Definition at line 32 of file OptionsMenuVideo.c.
m_TerrainSurfaceDetailOption
protected ref ListOptionsAccess m_TerrainSurfaceDetailOption private
Definition at line 70 of file OptionsMenuVideo.c.
m_TerrainSurfaceDetailSelector
protected ref OptionSelectorMultistate m_TerrainSurfaceDetailSelector private
Definition at line 38 of file OptionsMenuVideo.c.
m_Text [1/2]
protected TextWidget m_Text private
Definition at line 11 of file DropdownPrefab.c.
m_Text [2/2]
protected RichTextWidget m_Text private
Definition at line 4 of file ModsMenuTooltip.c.
m_TextMap
protected ref map< int, ref Param2< string, string > > m_TextMap private
Definition at line 67 of file OptionsMenuControls.c.
m_TextureDetailOption
protected ref ListOptionsAccess m_TextureDetailOption private
Definition at line 65 of file OptionsMenuVideo.c.
m_TextureDetailSelector
protected ref OptionSelectorMultistate m_TextureDetailSelector private
Definition at line 33 of file OptionsMenuVideo.c.
m_TextureFilteringOption
protected ref ListOptionsAccess m_TextureFilteringOption private
Definition at line 69 of file OptionsMenuVideo.c.
m_TextureFilteringSelector
protected ref OptionSelectorMultistate m_TextureFilteringSelector private
Definition at line 37 of file OptionsMenuVideo.c.
m_ThirdPersonFilter
ref OptionSelector m_ThirdPersonFilter private
Definition at line 21 of file ServerBrowserFilterContainer.c.
m_TimeSurvived
protected Widget m_TimeSurvived private
Definition at line 5 of file MainMenuStats.c.
m_TimeSurvivedValue
protected TextWidget m_TimeSurvivedValue private
Definition at line 6 of file MainMenuStats.c.
m_Tooltip
protected ModsMenuTooltip m_Tooltip private
Definition at line 13 of file ModsMenuDetailed.c.
m_TooltipMod
protected ModInfo m_TooltipMod private
Definition at line 15 of file ModsMenuDetailed.c.
m_TooltipOwner
protected bool m_TooltipOwner private
Definition at line 11 of file LayoutHolder.c.
m_TooltipTimer
protected ref Timer m_TooltipTimer private
Definition at line 14 of file ModsMenuDetailed.c.
m_TotalEntries
protected int m_TotalEntries private
Definition at line 8 of file PlayerListScriptedWidget.c.
m_TotalTimeBefore
protected float m_TotalTimeBefore private
Definition at line 5 of file CTKeyframe.c.
m_TotalTimeWidget
protected TextWidget m_TotalTimeWidget private
Definition at line 17 of file CTKeyframe.c.
m_Twitter
protected Widget m_Twitter private
Definition at line 9 of file MainMenuNewsfeed.c.
m_UID
protected string m_UID private
Definition at line 4 of file PlayerListEntryScriptedWidget.c.
Referenced by GetUID(), and IsLocalPlayer().
m_UiDescLabel
private RichTextWidget m_UiDescLabel private
Definition at line 15 of file UiHintPanel.c.
m_UiHeadlineLabel
private TextWidget m_UiHeadlineLabel private
Definition at line 16 of file UiHintPanel.c.
m_UiHintImage
private ImageWidget m_UiHintImage private
Definition at line 17 of file UiHintPanel.c.
m_UiLeftButton
private ButtonWidget m_UiLeftButton private
Definition at line 13 of file UiHintPanel.c.
Referenced by OnClick().
m_UiPageingLabel
private TextWidget m_UiPageingLabel private
Definition at line 18 of file UiHintPanel.c.
m_UiRightButton
private ButtonWidget m_UiRightButton private
Definition at line 14 of file UiHintPanel.c.
Referenced by OnClick().
m_UseActionWrapper
protected UAIDWrapper m_UseActionWrapper private
Definition at line 67 of file ActionTargetsCursor.c.
m_Version
protected TextWidget m_Version private
Definition at line 14 of file ModsMenuDetailedEntry.c.
m_VersionMatchFilter
ref OptionSelector m_VersionMatchFilter private
Definition at line 19 of file ServerBrowserFilterContainer.c.
m_VerticalOffset
reference float m_VerticalOffset private
Definition at line 5 of file SizeToChild.c.
Referenced by ResizeParentToChild().
m_Visible
protected bool m_Visible private
Definition at line 7 of file ObjectFollower.c.
m_VOIPOption
protected ref NumericOptionsAccess m_VOIPOption private
Definition at line 14 of file OptionsMenuSounds.c.
m_VOIPSelector
protected ref OptionSelectorSlider m_VOIPSelector private
Definition at line 21 of file OptionsMenuSounds.c.
m_VOIPThresholdOption
protected ref NumericOptionsAccess m_VOIPThresholdOption private
Definition at line 15 of file OptionsMenuSounds.c.
m_VOIPThresholdSelector
protected ref OptionSelectorLevelMarker m_VOIPThresholdSelector private
Definition at line 22 of file OptionsMenuSounds.c.
m_VonManager
protected VONManagerBase m_VonManager private
Definition at line 30 of file OptionsMenuSounds.c.
m_VSyncOption
protected ref ListOptionsAccess m_VSyncOption private
Definition at line 59 of file OptionsMenuVideo.c.
m_VSyncSelector
protected ref OptionSelectorMultistate m_VSyncSelector private
Definition at line 27 of file OptionsMenuVideo.c.
m_WasMicCapturing
private bool m_WasMicCapturing private
Definition at line 34 of file OptionsMenuSounds.c.
m_Weapon
protected Weapon_Base m_Weapon private
Definition at line 9 of file ProjectedCrosshair.c.
m_WhitelistFilter
ref OptionSelector m_WhitelistFilter private
Definition at line 16 of file ServerBrowserFilterContainer.c.
m_widget
Widget m_widget private
Definition at line 100 of file ProfileOptionsUI.c.
m_widget_array
ref array<Widget> m_widget_array private
Definition at line 101 of file ProfileOptionsUI.c.
Referenced by GetWidgetArray().
m_Youtube
protected Widget m_Youtube private
Definition at line 10 of file MainMenuNewsfeed.c.
RadialBarWidgetName
reference string RadialBarWidgetName private
Definition at line 3 of file ContinuousActionProgress.c.
SLIDER_STEP
const float SLIDER_STEP = 0.025 static private
Definition at line 69 of file OptionsMenuControls.c.
The documentation for this class was generated from the following files:
P:/scripts/1_Core/proto/EnWidgets.c
P:/scripts/3_Game/GUI/Containers/SizeToChild.c
P:/scripts/3_Game/GUI/ContextMenu.c
P:/scripts/3_Game/GUI/InventoryGrid.c
P:/scripts/4_World/Plugins/PluginBase/PluginDayZInfectedDebug.c
P:/scripts/4_World/Plugins/PluginBase/PluginItemDiagnostic.c
P:/scripts/5_Mission/GUI/ActionTargetsCursor.c
P:/scripts/5_Mission/GUI/CameraTools/CTEvent.c
P:/scripts/5_Mission/GUI/CameraTools/CTKeyframe.c
P:/scripts/5_Mission/GUI/CameraTools/CTObjectFollower.c
P:/scripts/5_Mission/GUI/ContinuousActionProgress.c
P:/scripts/5_Mission/GUI/HudDebug.c
P:/scripts/5_Mission/GUI/IngameMenu_Xbox/PlayerListEntryScriptedWidget.c
P:/scripts/5_Mission/GUI/IngameMenu_Xbox/PlayerListScriptedWidget.c
P:/scripts/5_Mission/GUI/InventoryNew/LayoutHolder.c
P:/scripts/5_Mission/GUI/ItemActionsWidget.c
P:/scripts/5_Mission/GUI/NewUI/ControlMapping/ControlMappingKeybinds.c
P:/scripts/5_Mission/GUI/NewUI/Credits/Elements/CreditsElement.c
P:/scripts/5_Mission/GUI/NewUI/DropdownPrefab/DropdownPrefab.c
P:/scripts/5_Mission/GUI/NewUI/Hints/UiHintPanel.c
P:/scripts/5_Mission/GUI/NewUI/Keybindings/KeybindingElement.c
P:/scripts/5_Mission/GUI/NewUI/Keybindings/KeybindingElementNew.c
P:/scripts/5_Mission/GUI/NewUI/Keybindings/KeybindingsGroup.c
P:/scripts/5_Mission/GUI/NewUI/MainMenu/MainMenuNewsfeed.c
P:/scripts/5_Mission/GUI/NewUI/MainMenu/MainMenuStats.c
P:/scripts/5_Mission/GUI/NewUI/ModsMenu/ModsMenuDetailed.c
P:/scripts/5_Mission/GUI/NewUI/ModsMenu/ModsMenuDetailedEntry.c
P:/scripts/5_Mission/GUI/NewUI/ModsMenu/ModsMenuSimple.c
P:/scripts/5_Mission/GUI/NewUI/ModsMenu/ModsMenuSimpleEntry.c
P:/scripts/5_Mission/GUI/NewUI/ModsMenu/ModsMenuTooltip.c
P:/scripts/5_Mission/GUI/NewUI/Options/OptionsMenuControls.c
P:/scripts/5_Mission/GUI/NewUI/Options/OptionsMenuGame.c
P:/scripts/5_Mission/GUI/NewUI/Options/OptionsMenuSounds.c
P:/scripts/5_Mission/GUI/NewUI/Options/OptionsMenuVideo.c
P:/scripts/5_Mission/GUI/NewUI/OptionSelectorBase.c
P:/scripts/5_Mission/GUI/NewUI/ServerBrowserMenu/ServerBrowserEntry.c
P:/scripts/5_Mission/GUI/NewUI/ServerBrowserMenu/ServerBrowserFilterContainer.c
P:/scripts/5_Mission/GUI/NewUI/TabberPrefab/TabberUI.c
P:/scripts/5_Mission/GUI/ObjectFollower.c
P:/scripts/5_Mission/GUI/ProfileOptionsUI.c
P:/scripts/5_Mission/GUI/ProjectedCrosshair.c