DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/Medical/ActionSewSelf.c File Reference
ActionSewSelf.c File Reference
Data Structures
class ActionSewSelfCB
Functions
ActionSewSelfCB ActionContinuousBaseCB ActionSewSelf ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override void ApplyBandage (ItemBase item, PlayerBase player)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionSewSelf()
ActionSewSelfCB ActionContinuousBaseCB ActionSewSelf ()
Referenced by ActionConstructor::RegisterActions(), and SewingKit::SetActions().
ApplyBandage()
override void ApplyBandage (ItemBase item, PlayerBase player)
References AGT_ITEM_TO_FLESH, and GetPlugin().
CreateActionComponent()
override void CreateActionComponent ()
References m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_MEDIUM.
CreateConditionComponents()
override void CreateConditionComponents ()
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool HasTarget ()
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
References ActionBandageBase::ApplyBandage(), ActionData::m_MainItem, ActionData::m_Player, and m_SpecialtyWeight.