DayZ Scripts: VehicleBattery Class Reference
VehicleBattery Class Reference
Private Member Functions
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanPutIntoHands (EntityAI player)
override bool CanPutInCargo (EntityAI parent)
override void OnInventoryEnter (Man player)
override void OnMovedInsideCargo (EntityAI container)
override bool CanDisplayAttachmentSlot (int slot_id)
override bool DisplayNameRuinAttach ()
override bool ShowZonesHealth ()
override void SetActions ()
void VehicleBattery ()
float GetEfficiency0To1 ()
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 units.
float GetEfficiencyDecayStart ()
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 unit.
override void SetCEBasedQuantity ()
override void OnEnergyConsumed ()
override void OnEnergyAdded ()
Private Attributes
private int m_Efficiency0To10
ENERGY CONSUMPTION.
Static Private Attributes
static private float m_EfficiencyDecayStart = 0.1
Detailed Description
Definition at line 1 of file VehicleBattery.c.
Constructor & Destructor Documentation
VehicleBattery()
void VehicleBattery () inline private
Definition at line 152 of file VehicleBattery.c.
References m_Efficiency0To10.
Member Function Documentation
CanDetachAttachment()
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 20 of file VehicleBattery.c.
CanDisplayAttachmentSlot()
override bool CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 118 of file VehicleBattery.c.
CanPutAsAttachment()
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file VehicleBattery.c.
References ItemBase::BatteryCharger(), and InventorySlots::INVALID.
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 56 of file VehicleBattery.c.
References ItemBase::MetalWire().
CanPutIntoHands()
override bool CanPutIntoHands (EntityAI player) inline private
Definition at line 33 of file VehicleBattery.c.
References ItemBase::MetalWire().
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 25 of file VehicleBattery.c.
DisplayNameRuinAttach()
override bool DisplayNameRuinAttach () inline private
Definition at line 126 of file VehicleBattery.c.
GetEfficiency0To1()
float GetEfficiency0To1 () inline private
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 units.
Definition at line 160 of file VehicleBattery.c.
References m_Efficiency0To10.
GetEfficiencyDecayStart()
float GetEfficiencyDecayStart () inline private
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 unit.
Definition at line 166 of file VehicleBattery.c.
References m_EfficiencyDecayStart.
OnEnergyAdded()
override void OnEnergyAdded () inline private
Definition at line 197 of file VehicleBattery.c.
References m_Efficiency0To10, m_EfficiencyDecayStart, and Math::Round().
OnEnergyConsumed()
override void OnEnergyConsumed () inline private
Definition at line 180 of file VehicleBattery.c.
References m_Efficiency0To10, m_EfficiencyDecayStart, and Math::Round().
OnInventoryEnter()
override void OnInventoryEnter (Man player) inline private
Definition at line 68 of file VehicleBattery.c.
References ItemBase::MetalWire().
OnMovedInsideCargo()
override void OnMovedInsideCargo (EntityAI container) inline private
Definition at line 95 of file VehicleBattery.c.
References ItemBase::MetalWire().
SetActions()
override void SetActions () inline private
Definition at line 136 of file VehicleBattery.c.
References ActionDetach(), and AddAction().
SetCEBasedQuantity()
override void SetCEBasedQuantity () inline private
Definition at line 172 of file VehicleBattery.c.
References GetQuantity(), and GetQuantityMax().
ShowZonesHealth()
override bool ShowZonesHealth () inline private
Definition at line 131 of file VehicleBattery.c.
Field Documentation
m_Efficiency0To10
private int m_Efficiency0To10 private
ENERGY CONSUMPTION.
Definition at line 149 of file VehicleBattery.c.
Referenced by GetEfficiency0To1(), OnEnergyAdded(), OnEnergyConsumed(), and VehicleBattery().
m_EfficiencyDecayStart
private float m_EfficiencyDecayStart = 0.1 static private
Definition at line 150 of file VehicleBattery.c.
Referenced by GetEfficiencyDecayStart(), OnEnergyAdded(), and OnEnergyConsumed().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/VehicleBattery.c