DayZ Scripts: HitDirectionEffectBase Class Reference
HitDirectionEffectBase Class Reference
Private Member Functions
override HitDirectionImagesBase GetImageData ()
override void FinalizePositionCalculation ()
override void SetIndicatorRotation (float timeslice=-1.0)
void HitDirectionEffectBase ()
void Init (DayZPlayer player, float hit_direction, float intensity_max)
Called manually after object spawn.
HitDirectionImagesBase GetImageData ()
void ~HitDirectionEffectBase ()
bool DurationCheck ()
void Update (float timeslice)
void CalculateArrowPosition (float timeslice=-1.0)
void FinalizePositionCalculation ()
specific handling on individual indicator type
void SetIndicatorRotation (float timeslice=-1.0)
void SetIndicatorPositon (float timeslice=-1.0)
override HitDirectionImagesBase GetImageData ()
override void FinalizePositionCalculation ()
override void SetIndicatorRotation (float timeslice=-1.0)
override HitDirectionImagesBase GetImageData ()
override void FinalizePositionCalculation ()
override void SetIndicatorRotation (float timeslice=-1.0)
Static Private Member Functions
static void CheckValues ()
range 0..180, randomized offset of direction to make it less acurate
static GetCurrentType ()
Private Attributes
const float DURATION_COEF_MIN = 0.6
const float INTENSITY_MIN = 0.6
float m_HitDirection
float m_Duration
float m_BreakPoint
float m_TimeActive
float m_IntensityMax
Widget m_LayoutRoot
Widget m_Image
DayZPlayer m_Player
bool m_Initialized
int m_SizeXEnf
int m_SizeYEnf
float m_PosX
float m_PosY
float m_PosXScreenEdge
float m_PosYScreenEdge
float m_AngleRad
float m_AngleRadPrev
float m_SmoothVel [1]
ref HitDirectionImagesBase m_ImageData
Static Private Attributes
static bool m_ServerOverrideEnabled
static int m_Mode
static int m_ID
static int m_Color
static protected m_Type
static float m_DurationMax
static float m_BreakPointBase
static float m_DistanceAdjust
range 0..1, a point where the fading starts
static int m_RotationOverride
static float m_Scatter
Constructor & Destructor Documentation
HitDirectionEffectBase()
void HitDirectionEffectBase () inline private
References HitDirectionImagesBase::GetCurrentImageData(), GetImageData(), m_AngleRad, m_Image, m_ImageData, m_Initialized, m_LayoutRoot, m_PosX, m_PosY, and m_SmoothVel.
~HitDirectionEffectBase()
void ~HitDirectionEffectBase () inline private
References m_LayoutRoot.
Member Function Documentation
CalculateArrowPosition()
void CalculateArrowPosition (float timeslice = -1.0) inline private
References Math::Clamp(), Math::Cos(), Math::DEG2RAD, FinalizePositionCalculation(), CGame::GetCurrentCameraDirection(), GetGame(), GetScreenSize(), m_AngleRad, m_AngleRadPrev, m_DistanceAdjust, m_HitDirection, m_Initialized, m_Player, m_PosX, m_PosXScreenEdge, m_PosY, m_PosYScreenEdge, m_SizeXEnf, m_SizeYEnf, m_SmoothVel, Math::ModFloat(), Math::NormalizeAngle(), Math::PI, Math::PI2, Math::Sin(), Math::SmoothCD(), and vector::VectorToAngles().
Referenced by Init(), and Update().
CheckValues()
static void CheckValues () inline static private
range 0..180, randomized offset of direction to make it less acurate
sets override values, or defaults
References CfgGameplayHandler::GetHitIndicationBreakPoint(), CfgGameplayHandler::GetHitIndicationIndicatorColor(), CfgGameplayHandler::GetHitIndicationMaxDuration(), CfgGameplayHandler::GetHitIndicationMode(), CfgGameplayHandler::GetHitIndicationOverrideEnabled(), CfgGameplayHandler::GetHitIndicationScatter(), CfgGameplayHandler::GetHitIndicationTypeID(), m_BreakPointBase, m_Color, m_DistanceAdjust, m_DurationMax, m_ID, m_Mode, m_RotationOverride, m_Scatter, and m_ServerOverrideEnabled.
Referenced by PlayerBase::UpdateHitDirectionValues().
DurationCheck()
bool DurationCheck () inline private
References m_Duration, and m_TimeActive.
FinalizePositionCalculation() [1/4]
override void FinalizePositionCalculation () inline private
References Math::Cos(), m_SizeXEnf, m_SizeYEnf, and Math::Sin().
Referenced by CalculateArrowPosition().
FinalizePositionCalculation() [2/4]
void FinalizePositionCalculation () inline private
specific handling on individual indicator type
FinalizePositionCalculation() [3/4]
override void FinalizePositionCalculation () inline private
References Math::Cos(), m_SizeXEnf, m_SizeYEnf, and Math::Sin().
FinalizePositionCalculation() [4/4]
override void FinalizePositionCalculation () inline private
References m_PosXScreenEdge, and m_PosYScreenEdge.
GetCurrentType()
static GetCurrentType () inline static private
References ErrorEx, m_ID, and m_Type.
Referenced by Hud::SpawnHitDirEffect().
GetImageData() [1/4]
override HitDirectionImagesBase GetImageData () inline private
Referenced by HitDirectionEffectBase().
GetImageData() [2/4]
HitDirectionImagesBase GetImageData () inline private
GetImageData() [3/4]
override HitDirectionImagesBase GetImageData () inline private
GetImageData() [4/4]
override HitDirectionImagesBase GetImageData () inline private
Init()
void Init (DayZPlayer player, float hit_direction, float intensity_max) inline private
Called manually after object spawn.
References CalculateArrowPosition(), Math::Clamp(), DURATION_COEF_MIN, INTENSITY_MIN, m_BreakPoint, m_BreakPointBase, m_Color, m_Duration, m_DurationMax, m_HitDirection, m_Image, m_Initialized, m_IntensityMax, m_LayoutRoot, m_Player, m_Scatter, Math::Pow(), Math::RandomFloatInclusive(), Math::RandomIntInclusive(), SetIndicatorPositon(), and SetIndicatorRotation().
Referenced by Hud::SpawnHitDirEffect().
SetIndicatorPositon()
void SetIndicatorPositon (float timeslice = -1.0) inline private
References m_LayoutRoot, m_PosX, and m_PosY.
Referenced by Init(), and Update().
SetIndicatorRotation() [1/4]
override void SetIndicatorRotation (float timeslice = -1.0) inline private
References Math::RAD2DEG.
Referenced by Init(), and Update().
SetIndicatorRotation() [2/4]
void SetIndicatorRotation (float timeslice = -1.0) inline private
SetIndicatorRotation() [3/4]
override void SetIndicatorRotation (float timeslice = -1.0) inline private
References Math::RAD2DEG.
SetIndicatorRotation() [4/4]
override void SetIndicatorRotation (float timeslice = -1.0) inline private
References Math::RandomIntInclusive().
Update()
void Update (float timeslice) inline private
References CalculateArrowPosition(), Math::Clamp(), Math::InverseLerp(), Math::Lerp(), m_BreakPoint, m_Duration, m_IntensityMax, m_LayoutRoot, m_Mode, m_TimeActive, SetIndicatorPositon(), and SetIndicatorRotation().
Field Documentation
DURATION_COEF_MIN
const float DURATION_COEF_MIN = 0.6 private
Referenced by Init().
INTENSITY_MIN
const float INTENSITY_MIN = 0.6 private
Referenced by Init().
m_AngleRad
float m_AngleRad private
Referenced by CalculateArrowPosition(), and HitDirectionEffectBase().
m_AngleRadPrev
float m_AngleRadPrev private
Referenced by CalculateArrowPosition().
m_BreakPoint
float m_BreakPoint private
Referenced by Init(), and Update().
m_BreakPointBase
float m_BreakPointBase static private
Referenced by CheckValues(), and Init().
m_Color
int m_Color static private
Referenced by CheckValues(), and Init().
m_DistanceAdjust
float m_DistanceAdjust static private
range 0..1, a point where the fading starts
Referenced by CalculateArrowPosition(), and CheckValues().
m_Duration
float m_Duration private
Referenced by DurationCheck(), Init(), and Update().
m_DurationMax
float m_DurationMax static private
Referenced by CheckValues(), and Init().
m_HitDirection
float m_HitDirection private
Referenced by CalculateArrowPosition(), and Init().
m_ID
int m_ID static private
Referenced by CheckValues(), and GetCurrentType().
m_Image
Widget m_Image private
Referenced by HitDirectionEffectBase(), and Init().
m_ImageData
ref HitDirectionImagesBase m_ImageData private
Referenced by HitDirectionEffectBase().
m_Initialized
bool m_Initialized private
Referenced by CalculateArrowPosition(), HitDirectionEffectBase(), and Init().
m_IntensityMax
float m_IntensityMax private
Referenced by Init(), and Update().
m_LayoutRoot
Widget m_LayoutRoot private
Referenced by HitDirectionEffectBase(), Init(), SetIndicatorPositon(), Update(), and ~HitDirectionEffectBase().
m_Mode
int m_Mode static private
Referenced by CheckValues(), Hud::SpawnHitDirEffect(), and Update().
m_Player
DayZPlayer m_Player private
Referenced by CalculateArrowPosition(), and Init().
m_PosX
float m_PosX private
Referenced by CalculateArrowPosition(), HitDirectionEffectBase(), and SetIndicatorPositon().
m_PosXScreenEdge
float m_PosXScreenEdge private
Referenced by CalculateArrowPosition(), and FinalizePositionCalculation().
m_PosY
float m_PosY private
Referenced by CalculateArrowPosition(), HitDirectionEffectBase(), and SetIndicatorPositon().
m_PosYScreenEdge
float m_PosYScreenEdge private
Referenced by CalculateArrowPosition(), and FinalizePositionCalculation().
m_RotationOverride
int m_RotationOverride static private
Referenced by CheckValues().
m_Scatter
float m_Scatter static private
Referenced by CheckValues(), and Init().
m_ServerOverrideEnabled
bool m_ServerOverrideEnabled static private
Referenced by CheckValues().
m_SizeXEnf
int m_SizeXEnf private
Referenced by CalculateArrowPosition(), and FinalizePositionCalculation().
m_SizeYEnf
int m_SizeYEnf private
Referenced by CalculateArrowPosition(), and FinalizePositionCalculation().
m_SmoothVel
float m_SmoothVel[1] private
Referenced by CalculateArrowPosition(), and HitDirectionEffectBase().
m_TimeActive
float m_TimeActive private
Referenced by DurationCheck(), and Update().
m_Type
protected m_Type static private
Referenced by GetCurrentType().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/HitIndication/HitDirectionArrow.c
P:/scripts/4_World/Classes/HitIndication/HitDirectionBase.c
P:/scripts/4_World/Classes/HitIndication/HitDirectionSpike.c
P:/scripts/4_World/Classes/HitIndication/HitDirectionSplash.c