DayZ Scripts: Land_WarheadStorage_Main Class Reference
Land_WarheadStorage_Main Class Reference
Private Member Functions
void Land_WarheadStorage_Main ()
void ~Land_WarheadStorage_Main ()
protected void UpdateLamp (string selection, string color)
override void DeferredInit ()
void SetPowerServer (bool hasPower)
void SetLeverStatesServer (int leverBits)
protected void OnPowerOnClient ()
protected void OnPowerOffClient ()
override void OnDoorOpenStart (DoorStartParams params)
override void OnDoorOpenFinish (DoorFinishParams params)
protected void RemoveDoorTimer (int doorIndex)
override void OnDoorCloseStart (DoorStartParams params)
override void OnDoorCloseFinish (DoorFinishParams params)
void AutoCloseDoor (int doorIndex)
void UpdateDoorStateServer ()
void UpdateDoorStateClient ()
protected int GetStorageLightIndexByDoor (int doorIndex)
protected int GetDoorIndexByLeverIndex (int LeverIndex)
override bool CanDoorBeOpened (int doorIndex, bool checkIfLocked=false)
override bool CanDoorBeLocked (int doorIndex)
protected int GetBunkerEffectIndexByDoor (int doorIndex)
protected bool IsBunkerDoor (int doorIndex)
protected bool IsStorageDoor (int doorIndex)
override bool CanDoorBeClosed (int doorIndex)
protected array< ref UndergroundBunkerTriggerData > GetTriggersData (int count)
protected void SpawnTriggers (int count)
override string GetDebugText ()
override void OnVariablesSynchronized ()
Private Attributes
protected bool m_HasPowerPrev
protected WarheadStorageLight m_StorageDoorLights [4]
protected EffectSound m_SoundDoorLoop [4]
protected ref array< EffectSound > m_PoweredSoundEffects = new array<EffectSound>()
protected ref map< int, ref Timer > m_AutoCloseTimers
protected const float DOOR_AUTOCLOSE_TIME = 12
protected const int SOURCES_COUNT = 4
protected const string WARHEAD_BUNKER_TRIGGER = "UndergroundBunkerTrigger"
protected const string ALARM_POS_MEMPOINT = "underground"
protected const string VENT_MAIN_POS_MEMPOINT = "Ventilation_main"
protected const string VENT_POS_MEMPOINT = "Ventilation"
protected const string ALARM_DOOR_OPEN_SOUND = "UndergroundDoor_Alarm_Start_SoundSet"
protected const string ALARM_DOOR_OPEN_LOOP_SOUND = "UndergroundDoor_Alarm_Loop_SoundSet"
protected const string ALARM_DOOR_CLOSE_SOUND = "UndergroundDoor_Alarm_End_SoundSet"
protected const string VENTILATION_SOUND = "Bunker_Ventilation_SoundSet"
protected const string LAMPS_SOUND = "Bunker_Lamp_Hum_SoundSet"
protected const string ELECTRICITY_ON_SOUND = "Bunker_bunker_electricity_on_SoundSet"
protected const string ELECTRICITY_OFF_SOUND = "Bunker_bunker_electricity_off_SoundSet"
protected const string LAMP_SELECTION = "GlassLamp"
protected const string MAIN_DOOR_SELECTION1 = "maindoor1_outer"
protected const string MAIN_DOOR_SELECTION2 = "maindoor2_outer"
protected const string COLOR_LAMP_OFF = "DZ\\structures_sakhal\\military\\storage\\data\\Warhead_Storage_Lamp_Glass_int.rvmat"
protected const string COLOR_LAMP_ON = "DZ\\structures_sakhal\\military\\storage\\data\\Warhead_Storage_Lamp_Glass_e_int.rvmat"
protected bool m_HasPower
protected bool m_LeverStatesBits
Constructor & Destructor Documentation
Land_WarheadStorage_Main()
void Land_WarheadStorage_Main () inline private
References Land_WarheadStorage_PowerStation::RegisterBunker(), and SpawnTriggers().
~Land_WarheadStorage_Main()
void ~Land_WarheadStorage_Main () inline private
References m_StorageDoorLights, and Land_WarheadStorage_PowerStation::UnregisterBunker().
Member Function Documentation
AutoCloseDoor()
void AutoCloseDoor (int doorIndex) inline private
References RemoveDoorTimer().
Referenced by DeferredInit().
CanDoorBeClosed()
override bool CanDoorBeClosed (int doorIndex) inline private
References IsBunkerDoor(), and IsStorageDoor().
CanDoorBeLocked()
override bool CanDoorBeLocked (int doorIndex) inline private
References IsBunkerDoor(), and IsStorageDoor().
CanDoorBeOpened()
override bool CanDoorBeOpened (int doorIndex, bool checkIfLocked = false) inline private
DeferredInit()
override void DeferredInit () inline private
References AutoCloseDoor(), GetGame(), IsBunkerDoor(), CGame::RegisterNetworkStaticObject(), and UpdateDoorStateServer().
GetBunkerEffectIndexByDoor()
protected int GetBunkerEffectIndexByDoor (int doorIndex) inline private
Referenced by OnDoorCloseFinish(), OnDoorCloseStart(), OnDoorOpenFinish(), and OnDoorOpenStart().
GetDebugText()
override string GetDebugText () inline private
References GetGame().
GetDoorIndexByLeverIndex()
protected int GetDoorIndexByLeverIndex (int LeverIndex) inline private
Referenced by UpdateDoorStateClient(), and UpdateDoorStateServer().
GetStorageLightIndexByDoor()
protected int GetStorageLightIndexByDoor (int doorIndex) inline private
Referenced by UpdateDoorStateClient(), and UpdateDoorStateServer().
GetTriggersData()
protected array< ref UndergroundBunkerTriggerData > GetTriggersData (int count) inline private
References UndergroundBunkerTriggerData::m_LinkedDoorSelection, UndergroundBunkerTriggerData::m_Position, UndergroundBunkerTriggerData::m_Size, UndergroundBunkerTriggerData::m_Type, MAIN_DOOR_SELECTION1, and MAIN_DOOR_SELECTION2.
Referenced by SpawnTriggers().
IsBunkerDoor()
protected bool IsBunkerDoor (int doorIndex) inline private
Referenced by CanDoorBeClosed(), CanDoorBeLocked(), DeferredInit(), OnDoorCloseFinish(), OnDoorCloseStart(), OnDoorOpenFinish(), OnDoorOpenStart(), and RemoveDoorTimer().
IsStorageDoor()
protected bool IsStorageDoor (int doorIndex) inline private
Referenced by CanDoorBeClosed(), and CanDoorBeLocked().
OnDoorCloseFinish()
override void OnDoorCloseFinish (DoorFinishParams params) inline private
References ALARM_DOOR_CLOSE_SOUND, ALARM_POS_MEMPOINT, GetBunkerEffectIndexByDoor(), IsBunkerDoor(), IsPlaying(), m_SoundDoorLoop, and EffectSound::SetAutodestroy().
OnDoorCloseStart()
override void OnDoorCloseStart (DoorStartParams params) inline private
References ALARM_DOOR_OPEN_LOOP_SOUND, ALARM_POS_MEMPOINT, GetBunkerEffectIndexByDoor(), IsBunkerDoor(), m_SoundDoorLoop, RemoveDoorTimer(), and EffectSound::SetAutodestroy().
OnDoorOpenFinish()
override void OnDoorOpenFinish (DoorFinishParams params) inline private
References GetBunkerEffectIndexByDoor(), IsBunkerDoor(), IsPlaying(), and m_SoundDoorLoop.
OnDoorOpenStart()
override void OnDoorOpenStart (DoorStartParams params) inline private
References ALARM_DOOR_OPEN_LOOP_SOUND, ALARM_DOOR_OPEN_SOUND, ALARM_POS_MEMPOINT, DOOR_AUTOCLOSE_TIME, GetBunkerEffectIndexByDoor(), IsBunkerDoor(), m_AutoCloseTimers, m_SoundDoorLoop, and EffectSound::SetAutodestroy().
OnPowerOffClient()
protected void OnPowerOffClient () inline private
References ELECTRICITY_OFF_SOUND, m_PoweredSoundEffects, and VENT_MAIN_POS_MEMPOINT.
Referenced by OnVariablesSynchronized().
OnPowerOnClient()
protected void OnPowerOnClient () inline private
References ELECTRICITY_ON_SOUND, LAMPS_SOUND, m_PoweredSoundEffects, m_StorageDoorLights, EffectSound::SetAutodestroy(), SOURCES_COUNT, ToString(), VENT_MAIN_POS_MEMPOINT, VENT_POS_MEMPOINT, and VENTILATION_SOUND.
Referenced by OnVariablesSynchronized().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References m_HasPower, m_HasPowerPrev, OnPowerOffClient(), OnPowerOnClient(), and UpdateDoorStateClient().
RemoveDoorTimer()
protected void RemoveDoorTimer (int doorIndex) inline private
References IsBunkerDoor(), and m_AutoCloseTimers.
Referenced by AutoCloseDoor(), and OnDoorCloseStart().
SetLeverStatesServer()
void SetLeverStatesServer (int leverBits) inline private
References m_LeverStatesBits, and UpdateDoorStateServer().
Referenced by Land_WarheadStorage_PowerStation::UpdateLeverStatesServer().
SetPowerServer()
void SetPowerServer (bool hasPower) inline private
References m_HasPower.
Referenced by Land_WarheadStorage_PowerStation::GetClosestBunker(), Land_WarheadStorage_PowerStation::OnGeneratorStart(), and Land_WarheadStorage_PowerStation::OnGeneratorStop().
SpawnTriggers()
protected void SpawnTriggers (int count) inline private
References AddChild(), CGame::CreateObjectEx(), ECE_LOCAL, GetGame(), GetTriggersData(), UndergroundBunkerTrigger::Init(), and WARHEAD_BUNKER_TRIGGER.
Referenced by Land_WarheadStorage_Main().
UpdateDoorStateClient()
void UpdateDoorStateClient () inline private
References GetDoorIndexByLeverIndex(), GetStorageLightIndexByDoor(), m_HasPower, m_LeverStatesBits, and m_StorageDoorLights.
Referenced by OnVariablesSynchronized().
UpdateDoorStateServer()
void UpdateDoorStateServer () inline private
References COLOR_LAMP_OFF, COLOR_LAMP_ON, GetDoorIndexByLeverIndex(), GetStorageLightIndexByDoor(), LAMP_SELECTION, m_HasPower, m_LeverStatesBits, ToString(), and UpdateLamp().
Referenced by DeferredInit(), and SetLeverStatesServer().
UpdateLamp()
protected void UpdateLamp (string selection, string color) inline private
Referenced by UpdateDoorStateServer().
Field Documentation
ALARM_DOOR_CLOSE_SOUND
protected const string ALARM_DOOR_CLOSE_SOUND = "UndergroundDoor_Alarm_End_SoundSet" private
Referenced by OnDoorCloseFinish().
ALARM_DOOR_OPEN_LOOP_SOUND
protected const string ALARM_DOOR_OPEN_LOOP_SOUND = "UndergroundDoor_Alarm_Loop_SoundSet" private
Referenced by OnDoorCloseStart(), and OnDoorOpenStart().
ALARM_DOOR_OPEN_SOUND
protected const string ALARM_DOOR_OPEN_SOUND = "UndergroundDoor_Alarm_Start_SoundSet" private
Referenced by OnDoorOpenStart().
ALARM_POS_MEMPOINT
protected const string ALARM_POS_MEMPOINT = "underground" private
Referenced by OnDoorCloseFinish(), OnDoorCloseStart(), and OnDoorOpenStart().
COLOR_LAMP_OFF
protected const string COLOR_LAMP_OFF = "DZ\\structures_sakhal\\military\\storage\\data\\Warhead_Storage_Lamp_Glass_int.rvmat" private
Referenced by UpdateDoorStateServer().
COLOR_LAMP_ON
protected const string COLOR_LAMP_ON = "DZ\\structures_sakhal\\military\\storage\\data\\Warhead_Storage_Lamp_Glass_e_int.rvmat" private
Referenced by UpdateDoorStateServer().
DOOR_AUTOCLOSE_TIME
protected const float DOOR_AUTOCLOSE_TIME = 12 private
Referenced by OnDoorOpenStart().
ELECTRICITY_OFF_SOUND
protected const string ELECTRICITY_OFF_SOUND = "Bunker_bunker_electricity_off_SoundSet" private
Referenced by OnPowerOffClient().
ELECTRICITY_ON_SOUND
protected const string ELECTRICITY_ON_SOUND = "Bunker_bunker_electricity_on_SoundSet" private
Referenced by OnPowerOnClient().
LAMP_SELECTION
protected const string LAMP_SELECTION = "GlassLamp" private
Referenced by UpdateDoorStateServer().
LAMPS_SOUND
protected const string LAMPS_SOUND = "Bunker_Lamp_Hum_SoundSet" private
Referenced by OnPowerOnClient().
m_AutoCloseTimers
protected ref map<int, ref Timer> m_AutoCloseTimers private
Referenced by OnDoorOpenStart(), and RemoveDoorTimer().
m_HasPower
protected bool m_HasPower private
Referenced by OnVariablesSynchronized(), SetPowerServer(), UpdateDoorStateClient(), and UpdateDoorStateServer().
m_HasPowerPrev
protected bool m_HasPowerPrev private
Referenced by OnVariablesSynchronized().
m_LeverStatesBits
protected bool m_LeverStatesBits private
Referenced by SetLeverStatesServer(), UpdateDoorStateClient(), and UpdateDoorStateServer().
m_PoweredSoundEffects
protected ref array<EffectSound> m_PoweredSoundEffects = new array<EffectSound>() private
Referenced by OnPowerOffClient(), and OnPowerOnClient().
m_SoundDoorLoop
protected EffectSound m_SoundDoorLoop[4] private
Referenced by OnDoorCloseFinish(), OnDoorCloseStart(), OnDoorOpenFinish(), and OnDoorOpenStart().
m_StorageDoorLights
protected WarheadStorageLight m_StorageDoorLights[4] private
Referenced by OnPowerOnClient(), UpdateDoorStateClient(), and ~Land_WarheadStorage_Main().
MAIN_DOOR_SELECTION1
protected const string MAIN_DOOR_SELECTION1 = "maindoor1_outer" private
Referenced by GetTriggersData().
MAIN_DOOR_SELECTION2
protected const string MAIN_DOOR_SELECTION2 = "maindoor2_outer" private
Referenced by GetTriggersData().
SOURCES_COUNT
protected const int SOURCES_COUNT = 4 private
Referenced by OnPowerOnClient().
VENT_MAIN_POS_MEMPOINT
protected const string VENT_MAIN_POS_MEMPOINT = "Ventilation_main" private
Referenced by OnPowerOffClient(), and OnPowerOnClient().
VENT_POS_MEMPOINT
protected const string VENT_POS_MEMPOINT = "Ventilation" private
Referenced by OnPowerOnClient().
VENTILATION_SOUND
protected const string VENTILATION_SOUND = "Bunker_Ventilation_SoundSet" private
Referenced by OnPowerOnClient().
WARHEAD_BUNKER_TRIGGER
protected const string WARHEAD_BUNKER_TRIGGER = "UndergroundBunkerTrigger" private
Referenced by SpawnTriggers().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Building/Underground/Land_WarheadStorage_Main.c