DayZ Scripts: ErrorProperties Class Reference
ErrorProperties Class Reference
Class which holds the properties and handling of an error.
Private Member Functions
void ErrorProperties (string message, string serverMessage)
void HandleError (int errorCode, string additionalInfo="")
string GetClientMessage (string additionalInfo="")
string GetServerMessage (string additionalInfo="")
Private Attributes
const string EP_HEADER_FORMAT_STRING = "%1 (%2)"
Formating for header (%1 = Header; %2 = ErrorCode)
const string EP_MESSAGE_FORMAT_STRING = "%1\n(%2)"
Formating for message (%1 = Message; %2 = AdditionalInfo)
protected string m_Message
Message which will appear on Client.
protected string m_ServerMessage
Message which will appear on Server.
Detailed Description
Class which holds the properties and handling of an error.
Constructor & Destructor Documentation
ErrorProperties()
void ErrorProperties (string message, string serverMessage) inline private
References m_Message, and m_ServerMessage.
Member Function Documentation
GetClientMessage()
string GetClientMessage (string additionalInfo = "") inline private
References EP_MESSAGE_FORMAT_STRING, string::Format(), and m_Message.
Referenced by GetClientMessage().
GetServerMessage()
string GetServerMessage (string additionalInfo = "") inline private
References EP_MESSAGE_FORMAT_STRING, string::Format(), and m_ServerMessage.
Referenced by GetServerMessage().
HandleError()
void HandleError (int errorCode, string additionalInfo = "") inline private
Referenced by OnErrorThrown().
Field Documentation
EP_HEADER_FORMAT_STRING
const string EP_HEADER_FORMAT_STRING = "%1 (%2)" private
Formating for header (%1 = Header; %2 = ErrorCode)
EP_MESSAGE_FORMAT_STRING
const string EP_MESSAGE_FORMAT_STRING = "%1\n(%2)" private
Formating for message (%1 = Message; %2 = AdditionalInfo)
Referenced by GetClientMessage(), and GetServerMessage().
m_Message
protected string m_Message private
Message which will appear on Client.
Referenced by ErrorProperties(), GetClientMessage(), GetHeader(), and HandleError().
m_ServerMessage
protected string m_ServerMessage private
Message which will appear on Server.
Referenced by ErrorProperties(), and GetServerMessage().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Global/ErrorModuleHandler/ErrorProperties.c