DayZ Scripts: AIBehaviourHLZombie2 Class Reference
AIBehaviourHLZombie2 Class Reference
Private Member Functions
AIBehaviourHLDataZombie2 GetData ()
private void AIBehaviourHLZombie2 ()
private void ~AIBehaviourHLZombie2 ()
override void OnInit ()
override void Simulate (float timeDelta)
void ShowDebugInfo ()
Constructor & Destructor Documentation
AIBehaviourHLZombie2()
private void AIBehaviourHLZombie2 () inline private
~AIBehaviourHLZombie2()
private void ~AIBehaviourHLZombie2 () inline private
Member Function Documentation
GetData()
AIBehaviourHLDataZombie2 GetData () inline private
References GetTemplateData().
OnInit()
override void OnInit () inline private
References SetNextBehaviour(), and SwitchToNextBehaviour().
ShowDebugInfo()
void ShowDebugInfo () inline private
Simulate()
override void Simulate (float timeDelta) inline private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/AIBehaviour.c