DayZ Scripts: TriggerInsider Class Reference
TriggerInsider Class Reference
The object which is in a trigger and its metadata.
Private Member Functions
void TriggerInsider (Object obj)
void ~TriggerInsider ()
Object GetObject ()
Private Attributes
ref OLinkT insider
protected Object m_Object
Object that data belongs to.
int timeStamp
Last time the object was seen in ms.
float timeEntered
Time the object was first seen in seconds.
float lastUpdated
Last time the object was updated in seconds, is used for calculating deltaTime.
Detailed Description
The object which is in a trigger and its metadata.
Definition at line 2 of file Trigger.c.
Constructor & Destructor Documentation
TriggerInsider()
void TriggerInsider (Object obj) inline private
Definition at line 18 of file Trigger.c.
References insider, and m_Object.
~TriggerInsider()
void ~TriggerInsider () inline private
Definition at line 24 of file Trigger.c.
Member Function Documentation
GetObject()
Object GetObject () inline private
Definition at line 28 of file Trigger.c.
References m_Object.
Referenced by TriggerEvents::Enter(), EvaluateDamageInternal(), Trigger::GetInsiderForObject(), Trigger::GetInsiderIndexForObject(), TriggerEvents::Leave(), Trigger::OnEnterBeginEvent(), OnEnterClientEvent(), EffectTrigger::OnEnterClientEvent(), EffectTrigger::OnEnterServerEvent(), TrapTrigger::OnEnterServerEvent(), OnEvaluateDamage(), AreaDamageLoopedDeferred_NoVehicle::OnEvaluateDamageEx(), Trigger::OnLeaveBeginEvent(), EffectTrigger::OnLeaveClientEvent(), OnLeaveClientEvent(), EffectTrigger::OnLeaveServerEvent(), TrapTrigger::OnLeaveServerEvent(), EffectTrigger::OnStayServerEvent(), Trigger::RemoveInsider(), Trigger::RemoveInsiderByObject(), ShouldRemoveInsider(), EffectTrigger::ShouldRemoveInsider(), TriggerEvents::Stay(), AreaDamageTriggerBase::UpdateInsiders(), and Trigger::UpdateInsiders().
Field Documentation
insider
ref OLinkT insider private
Definition at line 4 of file Trigger.c.
Referenced by TriggerInsider().
lastUpdated
float lastUpdated private
Last time the object was updated in seconds, is used for calculating deltaTime.
Definition at line 16 of file Trigger.c.
Referenced by Trigger::AddInsider(), AreaDamageLoopedDeferred::CalculateDamageScale(), CalculateDamageScale(), and Trigger::UpdateInsiders().
m_Object
protected Object m_Object private
Object that data belongs to.
Definition at line 7 of file Trigger.c.
Referenced by GetObject(), and TriggerInsider().
timeEntered
float timeEntered private
Time the object was first seen in seconds.
Definition at line 13 of file Trigger.c.
Referenced by Trigger::AddInsider(), AreaDamageLoopedDeferred::CalculateDamageScale(), and CalculateDamageScale().
timeStamp
int timeStamp private
Last time the object was seen in ms.
Definition at line 10 of file Trigger.c.
Referenced by Trigger::AddInsider(), and AreaDamageTriggerBase::UpdateInsiders().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ScriptedEntities/Triggers/Trigger.c