DayZ Scripts: P:/scripts/3_Game/InputAPI/UAInput.c File Reference
UAInput.c File Reference
Data Structures
class UAIDWrapper
class UAInput
class UAInterface
class UAInputAPI
Functions
proto native UAInputAPI GetUApi ()
Function Documentation
GetUApi()
proto native UAInputAPI GetUApi ()
Referenced by ActionTargetsCursor::ActionTargetsCursor(), MissionBase::AddActiveInputExcludes(), MissionBase::AddActiveInputRestriction(), ScriptedWidgetEventHandler::AddSubgroup(), array::Apply(), ScriptedWidgetEventHandler::Apply(), UIScriptedMenu::Apply(), DayZPlayer::CommandHandler(), ManBase::CommandHandler(), ConstructData(), UIScriptedMenu::CreateTabs(), CGame::DayZGame(), DetermineGestureIndex(), MissionBase::EnableAllInputs(), DayZSpectator::EOnFrame(), InputUtils::GetButtonIconPathFromInput(), InputUtils::GetButtonIconPathFromInput(), InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), InputUtils::GetImagesetAndIconFromInputAction(), InputUtils::GetRichtextButtonIconFromInputAction(), GetStringVariant(), PluginBase::Hide(), Backlit::HintClear(), UIScriptedMenu::Init(), InputUtils::InitInputMetadata(), InitInputWrapperData(), InterruptGestureCheck(), ManBase::IsMapCallbackCancelInput(), ManBase::IsMapCallbackEndInput(), ScriptedWidgetEventHandler::ItemActionsWidget(), Backlit::KeybindingClear(), Backlit::KeybindingShow(), Backlit::LoadingAnim(), Backlit::MainMenu_OnHide(), Backlit::MainMenu_OnShow(), MissionBaseWorld::MissionBase(), UIScriptedMenu::OnChange(), Backlit::OnEnterCar(), Backlit::OnLeaveCar(), array::OnSelectKBPreset(), OnShow(), DayZPlayer::OnSprintEnd(), DayZPlayer::OnSprintStart(), Backlit::OnSwimmingStart(), Backlit::OnSwimmingStop(), MissionBase::OnUpdate(), MissionBase::PerformRefreshExcludes(), UIScriptedMenu::PerformSetToDefaultsExt(), UIScriptedMenu::PerformSwitchPreset(), RadialMenu(), Backlit::RefreshVehicleLayout(), ScriptedWidgetEventHandler::Reload(), ScriptedWidgetEventHandler::Reload(), MissionBase::RemoveActiveInputExcludes(), MissionBase::RemoveActiveInputRestriction(), ScriptedWidgetEventHandler::SetElementTitle(), ScriptedWidgetEventHandler::SetElementTitle(), ActionInput::SetInput(), ScriptedWidgetEventHandler::SetInteractActionIcon(), DebugMonitor::SetPosition(), PluginBase::Show(), SwitchPreset(), ScriptedWidgetEventHandler::TutorialKeybinds(), UIScriptedMenu::Update(), Update(), WarningMenuBase::Update(), array::Update(), ScriptedWidgetEventHandler::Update(), InputUtils::UpdateConsolePresetID(), UpdateInterval(), Backlit::UpdatePlayer(), UIScriptedMenu::UpdateToolbarText(), Backlit::VisualiseBlood(), and Backlit::VisualiseHealth().