DayZ Scripts: CarLightBase Class Reference
CarLightBase Class Reference
Private Member Functions
void CarRearLight ()
void SetAsSegregatedBrakeLight ()
void SetAsSegregatedReverseLight ()
void CivilianSedanFrontLight ()
void Hatchback_02FrontLight ()
void Offroad_02FrontLight ()
void OffroadHatchbackFrontLight ()
void Sedan_02FrontLight ()
void Truck_01FrontLight ()
Private Attributes
float m_SegregatedBrakeBrightness = 2
float m_SegregatedBrakeRadius = 6
float m_SegregatedBrakeAngle = 180
vector m_SegregatedBrakeColorRGB = Vector(1, 0.05, 0.05)
Member Function Documentation
CarRearLight()
void CarRearLight () inline private
References Vector().
CivilianSedanFrontLight()
void CivilianSedanFrontLight () inline private
References Vector().
Hatchback_02FrontLight()
void Hatchback_02FrontLight () inline private
References Vector().
Offroad_02FrontLight()
void Offroad_02FrontLight () inline private
References Vector().
OffroadHatchbackFrontLight()
void OffroadHatchbackFrontLight () inline private
References Vector().
Sedan_02FrontLight()
void Sedan_02FrontLight () inline private
References Vector().
SetAsSegregatedBrakeLight()
void SetAsSegregatedBrakeLight () inline private
SetAsSegregatedReverseLight()
void SetAsSegregatedReverseLight () inline private
Truck_01FrontLight()
void Truck_01FrontLight () inline private
References Vector().
Field Documentation
m_SegregatedBrakeAngle
float m_SegregatedBrakeAngle = 180 private
m_SegregatedBrakeBrightness
float m_SegregatedBrakeBrightness = 2 private
m_SegregatedBrakeColorRGB
vector m_SegregatedBrakeColorRGB = Vector(1, 0.05, 0.05) private
m_SegregatedBrakeRadius
float m_SegregatedBrakeRadius = 6 private
The documentation for this class was generated from the following files:
P:/scripts/4_world/entities/scriptedlightbase/spotlightbase/carlightbase/carrearlightbase.c
P:/scripts/4_world/entities/scriptedlightbase/spotlightbase/carlightbase/civiliansedanfrontlight.c
P:/scripts/4_world/entities/scriptedlightbase/spotlightbase/carlightbase/hatchback_02frontlight.c
P:/scripts/4_world/entities/scriptedlightbase/spotlightbase/carlightbase/offroad_02frontlight.c
P:/scripts/4_world/entities/scriptedlightbase/spotlightbase/carlightbase/offroadhatchbackfrontlight.c
P:/scripts/4_world/entities/scriptedlightbase/spotlightbase/carlightbase/sedan_02frontlight.c
P:/scripts/4_world/entities/scriptedlightbase/spotlightbase/carlightbase/truck_01frontlight.c