DayZ Scripts: TFModule Class Reference
TFModule Class Reference
Private Member Functions
void TFModule ()
int Count ()
int Failed ()
int Success ()
int Pending ()
void AddTest (Class instance, string test, bool repeat)
bool Run (bool fatal, float dt)
private bool RunTest (TFCaller caller, float dt)
string Result ()
void PrintResult (string prefix="", TestFramework caller=null, string function="")
Private Attributes
private int m_Count
private int m_Failed
private int m_Success
private ref TFCallerArr m_Tests
private ref TFResultArr m_Results
private ref array< string > m_SucceededTests
private ref array< string > m_FailedTests
Detailed Description
Definition at line 82 of file TestFramework.c.
Constructor & Destructor Documentation
TFModule()
void TFModule () inline private
Definition at line 94 of file TestFramework.c.
References m_FailedTests, m_Results, m_SucceededTests, and m_Tests.
Member Function Documentation
AddTest()
void AddTest (Class instance, string test, bool repeat) inline private
Definition at line 123 of file TestFramework.c.
References m_Count, m_Results, m_Tests, and TFResult().
Referenced by AddFrameTest(), and AddInitTest().
Count()
int Count () inline private
Definition at line 103 of file TestFramework.c.
References m_Count.
Referenced by Result().
Failed()
int Failed () inline private
Definition at line 108 of file TestFramework.c.
References m_Failed.
Referenced by Result().
Pending()
int Pending () inline private
Definition at line 118 of file TestFramework.c.
References m_Count, m_Failed, and m_Success.
Referenced by Result().
PrintResult()
void PrintResult (string prefix = "", TestFramework caller = null, string function = "") inline private
Definition at line 189 of file TestFramework.c.
References m_FailedTests, m_SucceededTests, Result(), and Debug::TFLog().
Referenced by ~TestFramework().
Result()
string Result () inline private
Definition at line 184 of file TestFramework.c.
References Count(), Failed(), string::Format(), Pending(), and Success().
Referenced by PrintResult().
Run()
bool Run (bool fatal, float dt) inline private
Definition at line 133 of file TestFramework.c.
References ErrorEx, m_Tests, Print(), and RunTest().
Referenced by EOnFrame(), and EOnInit().
RunTest()
private bool RunTest (TFCaller caller, float dt) inline private
Definition at line 165 of file TestFramework.c.
References m_Failed, m_FailedTests, m_SucceededTests, and m_Success.
Referenced by Run().
Success()
int Success () inline private
Definition at line 113 of file TestFramework.c.
References m_Success.
Referenced by Result().
Field Documentation
m_Count
private int m_Count private
Definition at line 84 of file TestFramework.c.
Referenced by AddTest(), Count(), and Pending().
m_Failed
private int m_Failed private
Definition at line 85 of file TestFramework.c.
Referenced by Failed(), Pending(), and RunTest().
m_FailedTests
private ref array<string> m_FailedTests private
Definition at line 92 of file TestFramework.c.
Referenced by PrintResult(), RunTest(), and TFModule().
m_Results
private ref TFResultArr m_Results private
Definition at line 89 of file TestFramework.c.
Referenced by AddTest(), and TFModule().
m_SucceededTests
private ref array<string> m_SucceededTests private
Definition at line 91 of file TestFramework.c.
Referenced by PrintResult(), RunTest(), and TFModule().
m_Success
private int m_Success private
Definition at line 86 of file TestFramework.c.
Referenced by Pending(), RunTest(), and Success().
m_Tests
private ref TFCallerArr m_Tests private
Definition at line 88 of file TestFramework.c.
Referenced by AddTest(), Run(), and TFModule().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/TestFramework.c