DayZ Scripts: DayZInfectedInputController Class Reference
DayZInfectedInputController Class Reference
Private Member Functions
proto native bool IsVault ()
Same as 'DayZCreatureAIInputController::IsJump'.
proto native float GetVaultHeight ()
Same as 'DayZCreatureAIInputController::GetJumpHeight'.
proto native int GetMindState ()
proto native EntityAI GetTargetEntity ()
private void DayZInfectedInputController ()
never created by script
private void ~DayZInfectedInputController ()
never destroyed by script
Constructor & Destructor Documentation
DayZInfectedInputController()
private void DayZInfectedInputController () inline private
never created by script
~DayZInfectedInputController()
private void ~DayZInfectedInputController () inline private
never destroyed by script
Member Function Documentation
GetMindState()
proto native int GetMindState () private
Referenced by DayZInfected::FightLogic(), AITargetCallbacksPlayer::GetVisionPointPositionWS(), and DayZInfected::HandleMindStateChange().
GetTargetEntity()
proto native EntityAI GetTargetEntity () private
Referenced by DayZInfected::ChaseAttackLogic(), and DayZInfected::FightAttackLogic().
GetVaultHeight()
proto native float GetVaultHeight () private
Same as 'DayZCreatureAIInputController::GetJumpHeight'.
Referenced by DayZInfected::HandleVault().
IsVault()
proto native bool IsVault () private
Same as 'DayZCreatureAIInputController::IsJump'.
Referenced by DayZInfected::HandleVault().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Entities/DayZInfectedInputController.c