DayZ Scripts: P:/scripts/4_World/Entities/AdvancedCommunication/AdvancedCommunication.c File Reference
AdvancedCommunication.c File Reference
Data Structures
class EntityAI
class AdvancedCommunication
Functions
void AdvancedCommunication ()
void TurnOnTransmitter ()
void TurnOffTransmitter ()
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
void SetActions ()
void AddAction (typename actionName)
void RemoveAction (typename actionName)
Variables
static ref map< typename, ref TInputActionMap > m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap>
TInputActionMap m_InputActionMap
bool m_ActionsInitialize
class PASBroadcaster extends AdvancedCommunication IsInventoryVisible
Function Documentation
AddAction()
void AddAction (typename actionName)
Definition at line 220 of file AdvancedCommunication.c.
Referenced by ManBase::AddAction(), RemoteDetonatorReceiver(), EntityAI::SetActions(), StaticTransmitter::SetActions(), Land_Misc_Through_Static::SetActions(), Land_Underground_Panel_Lever::SetActions(), SetActions(), BuildingSuper::SetActions(), InventoryItemSuper::SetActions(), ItemBase::SetActions(), ClaymoreMine::SetActions(), ImprovisedExplosive::SetActions(), Plastic_Explosive::SetActions(), RemoteDetonatorTrigger::SetActions(), Rifle_Base::SetActions(), BoltActionRifle_ExternalMagazine_Base::SetActions(), BoltActionRifle_Base::SetActions(), DoubleBarrel_Base::SetActions(), Weapon_Base::SetActions(), Mp133Shotgun_Base::SetActions(), Weapon::SetActions(), InventoryItem::SetActions(), Barrel_ColorBase::SetActions(), BaseBuildingBase::SetActions(), BloodContainerBase::SetActions(), ToolBase::SetActions(), CattleProd::SetActions(), Chemlight_ColorBase::SetActions(), ItemMap::SetActions(), Clothing::SetActions(), Mask_Base::SetActions(), HeadGear_Base::SetActions(), Top_Base::SetActions(), Pants_Base::SetActions(), Glasses_Base::SetActions(), Shoes_Base::SetActions(), Gloves_Base::SetActions(), HelmetBase::SetActions(), RopeBelt::SetActions(), Compass::SetActions(), AgaricusMushroom::SetActions(), Apple::SetActions(), AuriculariaMushroom::SetActions(), Banana::SetActions(), Edible_Base::SetActions(), BoletusMushroom::SetActions(), Bottle_Base::SetActions(), Cannabis::SetActions(), GreenBellPepper::SetActions(), Kiwi::SetActions(), LactariusMushroom::SetActions(), MacrolepiotaMushroom::SetActions(), Orange::SetActions(), Pear::SetActions(), PleurotusMushroom::SetActions(), Plum::SetActions(), Potato::SetActions(), SlicedPumpkin::SetActions(), TetracyclineAntibiotics::SetActions(), Tomato::SetActions(), TunaCan::SetActions(), VitaminBottle::SetActions(), Zucchini::SetActions(), EyeMask_ColorBase::SetActions(), FireplaceBase::SetActions(), FishingRod_Base_New::SetActions(), WoodenCrate::SetActions(), Bandana_ColorBase::SetActions(), Bone::SetActions(), DuctTape::SetActions(), SmallStone::SetActions(), TannedLeather::SetActions(), BurlapSack::SetActions(), ChickenFeather::SetActions(), LongWoodenStick::SetActions(), SharpWoodenStick::SetActions(), Spear::SetActions(), Fabric::SetActions(), AntiPestsSpray::SetActions(), SeedBase::SetActions(), SodaCan_ColorBase::SetActions(), BakedBeansCan_Opened::SetActions(), DogFoodCan::SetActions(), PorkCan::SetActions(), Lunchmeat::SetActions(), Pajka::SetActions(), Pate::SetActions(), BrisketSpread::SetActions(), Marmalade::SetActions(), MushroomBase::SetActions(), Honey::SetActions(), Zagorky_ColorBase::SetActions(), Snack_ColorBase::SetActions(), PeachesCan_Opened::SetActions(), PowderedMilk::SetActions(), Rice::SetActions(), SardinesCan_Opened::SetActions(), SpaghettiCan_Opened::SetActions(), TacticalBaconCan_Opened::SetActions(), TunaCan_Opened::SetActions(), AntiChemInjector::SetActions(), BloodTestKit::SetActions(), DisinfectantAlcohol::SetActions(), Epinephrine::SetActions(), IodineTincture::SetActions(), Morphine::SetActions(), SalineBagIV::SetActions(), Splint::SetActions(), GPSReceiver::SetActions(), Binoculars::SetActions(), AlarmClock_ColorBase::SetActions(), BroomBase::SetActions(), Crowbar::SetActions(), EpoxyPutty::SetActions(), FarmingHoe::SetActions(), FireExtinguisher::SetActions(), HandcuffKeys::SetActions(), Handcuffs::SetActions(), HandSaw::SetActions(), HayHook::SetActions(), Iceaxe::SetActions(), KitchenTimer::SetActions(), LeatherSewingKit::SetActions(), Lockpick::SetActions(), LugWrench::SetActions(), MeatTenderizer::SetActions(), Paddle::SetActions(), Pen_ColorBase::SetActions(), SewingKit::SetActions(), Wrench::SetActions(), Container_Base::SetActions(), Grenade_Base::SetActions(), Heatpack::SetActions(), KazuarOptic::SetActions(), StarlightOptic::SetActions(), Inventory_Base::SetActions(), LongTorch::SetActions(), Ammunition_Base::SetActions(), ItemMegaphone::SetActions(), PoweredOptic_Base::SetActions(), PunchedCard::SetActions(), ItemRadio::SetActions(), Roadflare::SetActions(), StunBaton::SetActions(), Switchable_Base::SetActions(), TelescopicBaton::SetActions(), TentBase::SetActions(), FlammableBase::SetActions(), ItemTransmitter::SetActions(), TrapBase::SetActions(), TrapSpawnBase::SetActions(), TripodBase::SetActions(), VehicleBattery::SetActions(), WoodenStick::SetActions(), CarScript::SetActions(), ManBase::SetActions(), ManBase::SetActionsRemoteTarget(), and UnknownFoodCan_Opened().
AdvancedCommunication()
void AdvancedCommunication ()
Definition at line 140 of file AdvancedCommunication.c.
GetActions()
override void GetActions (typename action_input_type , out array< ActionBase_Basic > actions)
Definition at line 202 of file AdvancedCommunication.c.
InitializeActions()
void InitializeActions ()
Definition at line 190 of file AdvancedCommunication.c.
Referenced by EntityAI::GetActions(), GetActions(), InventoryItem::GetActions(), and ManBase::GetActions().
RemoveAction()
void RemoveAction (typename actionName)
Definition at line 252 of file AdvancedCommunication.c.
Referenced by OnVariablesSynchronized(), ManBase::RemoveAction(), Land_Misc_Through_Static::SetActions(), CarDoor::SetActions(), RemoteDetonatorTrigger::SetActions(), Rifle_Base::SetActions(), BoltActionRifle_Base::SetActions(), DoubleBarrel_Base::SetActions(), Weapon_Base::SetActions(), Mp133Shotgun_Base::SetActions(), SetActions(), ItemBase::SetActions(), Bottle_Base::SetActions(), Vodka::SetActions(), Binoculars::SetActions(), PoweredOptic_Base::SetActions(), TentBase::SetActions(), and TrapSpawnBase::SetActions().
SetActions()
override void SetActions ()
Definition at line 213 of file AdvancedCommunication.c.
Referenced by EntityAI::InitializeActions(), InitializeActions(), and ManBase::InitializeActions().
TurnOffTransmitter()
void TurnOffTransmitter ()
Definition at line 185 of file AdvancedCommunication.c.
TurnOnTransmitter()
void TurnOnTransmitter ()
Definition at line 180 of file AdvancedCommunication.c.
Variable Documentation
IsInventoryVisible
class AdvancedCommunication extends EntityAI IsInventoryVisible
Definition at line 1 of file AdvancedCommunication.c.
m_ActionsInitialize
bool m_ActionsInitialize
Definition at line 138 of file AdvancedCommunication.c.
Referenced by EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), ManBase::AddAction(), EntityAI::AdvancedCommunication(), BuildingBase(), EntityAI::GetActions(), GetActions(), InventoryItem::GetActions(), ManBase::GetActions(), ManBase::Init(), and InventoryItem::ItemBase().
m_AdvComTypeActionsMap
ref map<typename, ref TInputActionMap> m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap> static
Definition at line 136 of file AdvancedCommunication.c.
Referenced by EntityAI::InitializeActions().
m_InputActionMap
TInputActionMap m_InputActionMap
Definition at line 137 of file AdvancedCommunication.c.
Referenced by EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), ManBase::AddAction(), EntityAI::GetActions(), GetActions(), InventoryItem::GetActions(), ManBase::GetActions(), EntityAI::InitializeActions(), InitializeActions(), InventoryItem::InitializeActions(), ManBase::InitializeActions(), EntityAI::RemoveAction(), RemoveAction(), InventoryItem::RemoveAction(), and ManBase::RemoveAction().