DayZ Scripts: HandEventDrop Class Reference
HandEventDrop Class Reference
Private Member Functions
void HandEventThrow (Man p=null, InventoryLocation src=null)
override InventoryLocation GetDst ()
override void ReadFromContext (ParamsReadContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
void SetForce (vector force)
vector GetForce ()
Private Attributes
vector m_Force
ref InventoryLocation m_Dst
Detailed Description
Definition at line 346 of file Hand_Events.c.
Member Function Documentation
GetDst()
override InventoryLocation GetDst () inline private
Definition at line 368 of file Hand_Events.c.
References m_Dst.
Referenced by HandEventBase::AcquireInventoryJunctureFromServer(), HandEventBase::CanPerformEvent(), and HandEventBase::CheckRequest().
GetForce()
vector GetForce () inline private
Definition at line 400 of file Hand_Events.c.
References m_Force.
HandEventThrow()
void HandEventThrow (Man p = null, InventoryLocation src = null) inline private
Definition at line 348 of file Hand_Events.c.
References Error(), GetSrcEntity(), and m_EventID.
ReadFromContext()
override void ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 373 of file Hand_Events.c.
References Serializer::Read(), InventoryLocation::ReadFromContext(), x, and y.
SetForce()
void SetForce (vector force) inline private
Definition at line 399 of file Hand_Events.c.
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 388 of file Hand_Events.c.
References Serializer::Write().
Field Documentation
m_Dst
ref InventoryLocation m_Dst private
Definition at line 404 of file Hand_Events.c.
Referenced by GetDst().
m_Force
vector m_Force private
Definition at line 402 of file Hand_Events.c.
Referenced by GetForce().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/Inventory/Hand_Events.c