DayZ Scripts: BuildingSuper Class Reference
BuildingSuper Class Reference
Private Member Functions
void BuildingWithFireplace ()
override bool IsBuilding ()
override bool IsFuelStation ()
override float GetLiquidThroughputCoef ()
void Land_Misc_Greenhouse ()
override void EEInit ()
override void EEDelete (EntityAI parent)
protected void BonfireHeating ()
DEPRECATED.
override bool IsBuilding ()
override bool IsWell ()
override float GetLiquidThroughputCoef ()
override void SetActions ()
Private Attributes
const float TIMER_HEATING_UPDATE_INTERVAL = 2
const float PARAM_HEAT_RADIUS = 15
const float PARAM_FULL_HEAT_RADIUS = 5
const float PARAM_MAX_TRANSFERED_TEMPERATURE = 25
const float CONST_FIRE_TEMP = 1000
maximum value for temperature that will be transfered to player (environment)
protected BonfireLight m_Light
protected Particle m_ParticleFire
protected Particle m_ParticleSmoke
protected EffectSound m_SoundFireLoop
protected ref Timer m_BonfireHeatingTimer
protected ref UniversalTemperatureSource m_UTSource
DEPRECATED.
protected ref UniversalTemperatureSourceSettings m_UTSSettings
protected ref UniversalTemperatureSourceLambdaConstant m_UTSLBonfire
Detailed Description
Definition at line 1 of file BuildingWithFireplace.c.
Member Function Documentation
BonfireHeating()
protected void BonfireHeating () inline private
DEPRECATED.
Definition at line 111 of file Bonfire.c.
BuildingWithFireplace()
void BuildingWithFireplace () inline private
Definition at line 3 of file BuildingWithFireplace.c.
EEDelete()
override void EEDelete (EntityAI parent) inline private
Definition at line 73 of file Bonfire.c.
References GetGame(), m_Light, m_ParticleSmoke, m_SoundFireLoop, m_UTSource, EffectSound::SoundStop(), and Particle::Stop().
EEInit()
override void EEInit () inline private
Definition at line 22 of file Bonfire.c.
References ParticleList::BONFIRE_FIRE, ParticleList::BONFIRE_SMOKE, CONST_FIRE_TEMP, GetGame(), GetMemoryPointPos(), PointLightBase::m_FireBrightness, PointLightBase::m_FireRadius, m_Light, PointLightBase::m_MemoryPoint, m_ParticleSmoke, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, m_SoundFireLoop, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, UniversalTemperatureSourceSettings::m_Updateable, UniversalTemperatureSourceSettings::m_UpdateInterval, m_UTSource, m_UTSSettings, PARAM_FULL_HEAT_RADIUS, PARAM_HEAT_RADIUS, PARAM_MAX_TRANSFERED_TEMPERATURE, ParticleManager(), PlaySoundSetLoop(), TIMER_HEATING_UPDATE_INTERVAL, and Vector().
GetLiquidThroughputCoef() [1/2]
override float GetLiquidThroughputCoef () inline private
Definition at line 13 of file FuelStation.c.
References LIQUID_THROUGHPUT_FUELSTATION.
GetLiquidThroughputCoef() [2/2]
override float GetLiquidThroughputCoef () inline private
Definition at line 13 of file Well.c.
References LIQUID_THROUGHPUT_WELL.
IsBuilding() [1/2]
override bool IsBuilding () inline private
Definition at line 3 of file FuelStation.c.
IsBuilding() [2/2]
override bool IsBuilding () inline private
Definition at line 3 of file Well.c.
IsFuelStation()
override bool IsFuelStation () inline private
Definition at line 8 of file FuelStation.c.
IsWell()
override bool IsWell () inline private
Definition at line 8 of file Well.c.
Land_Misc_Greenhouse()
void Land_Misc_Greenhouse () inline private
Definition at line 3 of file Land_Misc_Greenhouse.c.
SetActions()
override void SetActions () inline private
Definition at line 18 of file Well.c.
References AddAction().
Field Documentation
CONST_FIRE_TEMP
const float CONST_FIRE_TEMP = 1000 private
maximum value for temperature that will be transfered to player (environment)
Definition at line 7 of file Bonfire.c.
Referenced by EEInit().
m_BonfireHeatingTimer
protected ref Timer m_BonfireHeatingTimer private
Definition at line 15 of file Bonfire.c.
m_Light
protected BonfireLight m_Light private
Definition at line 9 of file Bonfire.c.
m_ParticleFire
protected Particle m_ParticleFire private
Definition at line 10 of file Bonfire.c.
m_ParticleSmoke
protected Particle m_ParticleSmoke private
Definition at line 11 of file Bonfire.c.
m_SoundFireLoop
protected EffectSound m_SoundFireLoop private
Definition at line 12 of file Bonfire.c.
m_UTSLBonfire
protected ref UniversalTemperatureSourceLambdaConstant m_UTSLBonfire private
Definition at line 20 of file Bonfire.c.
m_UTSource
protected ref UniversalTemperatureSource m_UTSource private
DEPRECATED.
Definition at line 18 of file Bonfire.c.
m_UTSSettings
protected ref UniversalTemperatureSourceSettings m_UTSSettings private
Definition at line 19 of file Bonfire.c.
PARAM_FULL_HEAT_RADIUS
const float PARAM_FULL_HEAT_RADIUS = 5 private
Definition at line 5 of file Bonfire.c.
Referenced by EEInit().
PARAM_HEAT_RADIUS
const float PARAM_HEAT_RADIUS = 15 private
Definition at line 4 of file Bonfire.c.
Referenced by EEInit().
PARAM_MAX_TRANSFERED_TEMPERATURE
const float PARAM_MAX_TRANSFERED_TEMPERATURE = 25 private
Definition at line 6 of file Bonfire.c.
Referenced by EEInit().
TIMER_HEATING_UPDATE_INTERVAL
const float TIMER_HEATING_UPDATE_INTERVAL = 2 private
Definition at line 3 of file Bonfire.c.
Referenced by EEInit().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Building/BuildingWithFireplace.c
P:/scripts/4_World/Entities/Building/Specific/Bonfire.c
P:/scripts/4_World/Entities/Building/FuelStation.c
P:/scripts/4_World/Entities/Building/Residential/Misc/Land_Misc_Greenhouse.c
P:/scripts/4_World/Entities/Building/Well.c