DayZ Scripts: Icon Class Reference
Icon Class Reference
Private Member Functions
void Icon (LayoutHolder parent, bool hands_icon=false)
void ~Icon ()
Widget GetSelectedWidget ()
bool IsDragged ()
override void SetActive (bool active)
override void SetParentWidget ()
void RefreshQuickbar ()
void DoubleClick (Widget w, int x, int y, int button)
void DraggingOverSwap (Widget w, int x, int y, Widget receiver)
void DraggingOverCombine (Widget w, int x, int y, Widget receiver)
bool MouseEnter (Widget w, int x, int y)
bool MouseLeave (Widget w, Widget s, int x, int y)
void DraggingOver (Widget w, int x, int y, Widget receiver)
void OnPerformCombination (int combinationFlags)
void ShowActionMenuCombine (EntityAI entity1, EntityAI entity2, int combinationFlags, Widget w, bool color_test)
void OnPerformRecipe (int id)
void Combine (Widget w, int x, int y, Widget receiver)
bool CombineItems (EntityAI entity1, EntityAI entity2)
bool FlagAction (EntityAI entity1, EntityAI entity2, int combinationFlags)
void MouseClick (Widget w, int x, int y, int button)
void DropReceivedFromMain (Widget w, int x, int y, Widget receiver)
void Swap (Widget w, int x, int y, Widget receiver)
void ToRefresh (Icon icon, Icon icon2)
override void SetLayoutName ()
void SetSize (int x, int y)
void SetPos (int x, int y)
int GetCargoPos ()
void SetCargoPos (int x)
void DestroyWhiteBackground ()
void CreateWhiteBackground ()
void OnDraggingOverBackground (Widget w, int x, int y, Widget reciever)
void DropReceivedFromBackground (Widget w, int x, int y, Widget reciever)
void RevertToOriginalFlip ()
override void Refresh ()
void SetTemperature ()
void RefreshIconPos ()
void FullScreen ()
void RefreshPos (int row, int column)
Object GetObject ()
void RefreshMuzzleIcon ()
void SetQuantity ()
void SetSort (int index)
int GetSort ()
void SetItemPreviewEx (bool refresh=true)
void SetItemPreview ()
void SetItemSizeEx (bool refresh=true)
void SetItemSize ()
void UpdateFlip (bool flipped)
void InitLock (EntityAI parent, EntityAI obj, int x_pos, int y_pos, bool flip)
void InitEx (EntityAI obj, bool refresh=true)
void Init (EntityAI obj)
void CheckIsWeapon ()
void CheckIsMagazineEx (bool refresh=true)
void CheckIsMagazine ()
void CheckHasTemperature ()
void CheckHasQuantityEx (bool refresh=true)
void CheckHasQuantity ()
void SetPosX (int x)
void SetPosY (int y)
void SetSizeX (int x)
void SetSizeY (int y)
int GetPosX ()
int GetPosY ()
int GetSizeX ()
int GetSizeY ()
void SetPosEx (bool refresh=true)
void SetPos ()
void SetSize ()
override void UpdateInterval ()
Private Attributes
protected int m_SizeX
protected int m_SizeY
protected int m_PosX
protected int m_PosY
protected EntityAI m_Lock
protected bool m_IsWeapon = false
protected bool m_IsMagazine = false
protected bool m_HasTemperature = false
protected bool m_HasQuantity = false
protected float m_CurrQuantity = -1
protected EntityAI m_Obj
protected ItemBase m_Item
protected bool m_HandsIcon
protected int m_CargoPos
protected bool m_IsDragged
protected bool m_PreviousFlipOrientation
const int NUMBER_OF_TIMERS = 2
protected ItemPreviewWidget m_ItemPreview
protected Widget m_ColorWidget
protected Widget m_SelectedPanel
protected Widget m_QuantityPanel
protected TextWidget m_QuantityItem
protected ProgressBarWidget m_QuantityProgress
protected Widget m_QuantityStack
protected Widget m_ItemSizePanel
protected TextWidget m_ItemSizeWidget
protected ref array< ImageWidget > m_AmmoIcons
protected ImageWidget m_AmmoTypeIcon
Detailed Description
Definition at line 1 of file Icon.c.
Constructor & Destructor Documentation
Icon()
void Icon (LayoutHolder parent, bool hands_icon = false) inline private
Definition at line 40 of file Icon.c.
References FindAnyWidget(), ItemManager::GetInstance(), m_AmmoTypeIcon, m_ColorWidget, m_HandsIcon, m_ItemPreview, m_ItemSizePanel, m_ItemSizeWidget, m_QuantityItem, m_QuantityPanel, m_QuantityProgress, m_QuantityStack, m_SelectedPanel, SetActive(), and ItemManager::SetSelectedItem().
~Icon()
void ~Icon () inline private
Definition at line 62 of file Icon.c.
References ItemManager::GetInstance(), ItemManager::HideDropzones(), m_IsDragged, m_Obj, RevertToOriginalFlip(), ItemManager::SetIsDragging(), SetItemPreview(), and UpdateFlip().
Member Function Documentation
CheckHasQuantity()
void CheckHasQuantity () inline private
Definition at line 1845 of file Icon.c.
References CheckHasQuantityEx().
CheckHasQuantityEx()
void CheckHasQuantityEx (bool refresh = true) inline private
Definition at line 1834 of file Icon.c.
References QuantityConversions::HasItemQuantity(), m_HasQuantity, m_Item, m_QuantityPanel, and QUANTITY_HIDDEN.
Referenced by CheckHasQuantity(), and InitEx().
CheckHasTemperature()
void CheckHasTemperature () inline private
Definition at line 1826 of file Icon.c.
References m_HasTemperature, and m_Item.
Referenced by InitEx().
CheckIsMagazine()
void CheckIsMagazine () inline private
Definition at line 1821 of file Icon.c.
References CheckIsMagazineEx().
CheckIsMagazineEx()
void CheckIsMagazineEx (bool refresh = true) inline private
Definition at line 1783 of file Icon.c.
References m_AmmoTypeIcon, m_IsMagazine, and m_Obj.
Referenced by CheckIsMagazine(), and InitEx().
CheckIsWeapon()
void CheckIsWeapon () inline private
Definition at line 1716 of file Icon.c.
References GetGame(), Widget::LoadImageFile(), m_AmmoIcons, m_IsWeapon, and m_Obj.
Referenced by InitEx().
Combine()
void Combine (Widget w, int x, int y, Widget receiver) inline private
Definition at line 769 of file Icon.c.
References ItemManager::GetCombinationFlags(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), ItemManager::HideDropzones(), name, string::Replace(), ItemManager::SetIsDragging(), and ShowActionMenuCombine().
CombineItems()
bool CombineItems (EntityAI entity1, EntityAI entity2) inline private
Definition at line 794 of file Icon.c.
References FlagAction(), and ItemManager::GetCombinationFlags().
Referenced by Attachments::Combine(), Container::Combine(), PlayerContainer::Combine(), and VicinitySlotsContainer::Combine().
CreateWhiteBackground()
void CreateWhiteBackground () inline private
Definition at line 1271 of file Icon.c.
References ColorManager::BASE_COLOR, GetGame(), ItemManager::GetInstance(), CGame::GetInventoryItemSize(), m_ColorWidget, m_HandsIcon, m_IsDragged, m_Item, m_ItemPreview, m_PreviousFlipOrientation, m_SelectedPanel, Refresh(), ItemManager::SetDraggedIcon(), ItemManager::SetDraggedItem(), ItemPreviewWidget::SetForceFlipEnable(), ItemManager::SetIsDragging(), and SetSize().
DestroyWhiteBackground()
void DestroyWhiteBackground () inline private
Definition at line 1246 of file Icon.c.
References ARGBF(), FullScreen(), GetGame(), ItemManager::GetInstance(), ItemManager::HideDropzones(), InventoryMenu(), m_HandsIcon, m_IsDragged, m_ItemPreview, m_SelectedPanel, MENU_INVENTORY, Refresh(), RevertToOriginalFlip(), ItemPreviewWidget::SetForceFlip(), ItemPreviewWidget::SetForceFlipEnable(), and ItemManager::SetIsDragging().
DoubleClick()
void DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 135 of file Icon.c.
References GetGame(), ItemPreviewWidget::GetItem(), InventoryLocation::GetParent(), GetPlayer(), InventoryLocation::GetType(), InventoryMenu(), m_HandsIcon, m_Obj, MENU_INVENTORY, name, and string::Replace().
DraggingOver()
void DraggingOver (Widget w, int x, int y, Widget receiver) inline private
Definition at line 387 of file Icon.c.
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), ColorManager::COMBINE_COLOR, ColorManager::FSWAP_COLOR, GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_HandsIcon, m_Lock, m_Obj, m_Parent, name, ColorManager::RED_COLOR, string::Replace(), InventoryLocation::SetCargoAuto(), ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), ColorManager::SWAP_COLOR, x, and y.
DraggingOverCombine()
void DraggingOverCombine (Widget w, int x, int y, Widget receiver) inline private
Definition at line 337 of file Icon.c.
References ItemManager::GetCombinationFlags(), GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), name, string::Replace(), and ShowActionMenuCombine().
DraggingOverSwap()
void DraggingOverSwap (Widget w, int x, int y, Widget receiver) inline private
Definition at line 253 of file Icon.c.
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), ColorManager::FSWAP_COLOR, ItemManager::GetCenterDropzone(), GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), ItemManager::HideDropzones(), m_HandsIcon, m_Item, name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and ColorManager::SWAP_COLOR.
DropReceivedFromBackground()
void DropReceivedFromBackground (Widget w, int x, int y, Widget reciever) inline private
Definition at line 1336 of file Icon.c.
References m_Parent, m_PosX, m_PosY, and Pos().
DropReceivedFromMain()
void DropReceivedFromMain (Widget w, int x, int y, Widget receiver) inline private
Definition at line 949 of file Icon.c.
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), CombineItemsClient(), InventoryLocation::CopyLocationFrom(), ItemManager::GetDraggedIcon(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), InventoryLocation::GetParent(), GetPlayer(), InventoryLocation::GetType(), ItemManager::HideDropzones(), m_HandsIcon, m_Item, m_Lock, m_Parent, name, string::Replace(), InventoryLocation::SetCargoAuto(), InventoryLocation::SetFlip(), ItemManager::SetIsDragging(), SplitItemUtils::TakeOrSplitToInventoryLocation(), ToRefresh(), x, and y.
FlagAction()
bool FlagAction (EntityAI entity1, EntityAI entity2, int combinationFlags) inline private
Definition at line 800 of file Icon.c.
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, InventoryCombinationFlags::ATTACH_MAGAZINE, InventoryCombinationFlags::COMBINE_QUANTITY, InventoryCombinationFlags::COMBINE_QUANTITY2, GetGame(), UIManager::GetMenu(), GetMousePos(), CGame::GetUIManager(), InventoryCombinationFlags::LOAD_CHAMBER, mission, InventoryCombinationFlags::NONE, OnPerformCombination(), InventoryCombinationFlags::PERFORM_ACTION, InventoryCombinationFlags::SET_ACTION, and InventoryCombinationFlags::SWAP.
Referenced by CombineItems().
FullScreen()
void FullScreen () inline private
Definition at line 1398 of file Icon.c.
References ARGB(), m_ColorWidget, and m_IsDragged.
Referenced by HandsPreview::CreateNewIcon(), and DestroyWhiteBackground().
GetCargoPos()
int GetCargoPos () inline private
Definition at line 1235 of file Icon.c.
References m_CargoPos.
GetObject()
Object GetObject () inline private
Definition at line 1420 of file Icon.c.
References m_Obj.
Referenced by IconsContainer::AddItem(), Container::Combine(), Container::GetFocusedItem(), RefreshMuzzleIcon(), IconsContainer::RemoveItem(), Container::SelectItem(), and SetActive().
GetPosX()
int GetPosX () inline private
Definition at line 1870 of file Icon.c.
References m_PosX.
Referenced by SetPosEx().
GetPosY()
int GetPosY () inline private
Definition at line 1875 of file Icon.c.
References m_PosY.
Referenced by SetPosEx().
GetSelectedWidget()
Widget GetSelectedWidget () inline private
Definition at line 79 of file Icon.c.
References m_SelectedPanel.
GetSizeX()
int GetSizeX () inline private
Definition at line 1880 of file Icon.c.
References m_SizeX.
Referenced by CargoContainerRow::GetIconSize().
GetSizeY()
int GetSizeY () inline private
Definition at line 1885 of file Icon.c.
References m_SizeY.
Referenced by CargoContainerRow::GetIconSize().
GetSort()
int GetSort () inline private
Definition at line 1589 of file Icon.c.
Init()
void Init (EntityAI obj) inline private
Definition at line 1711 of file Icon.c.
References InitEx().
Referenced by HandsPreview::CreateNewIcon().
InitEx()
void InitEx (EntityAI obj, bool refresh = true) inline private
Definition at line 1659 of file Icon.c.
References CheckHasQuantityEx(), CheckHasTemperature(), CheckIsMagazineEx(), CheckIsWeapon(), FindAnyWidget(), WidgetEventHandler::GetInstance(), m_HandsIcon, m_Item, m_ItemPreview, m_Lock, m_Obj, m_RootWidget, Refresh(), WidgetEventHandler::RegisterOnDoubleClick(), WidgetEventHandler::RegisterOnDrag(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDrop(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), WidgetEventHandler::RegisterOnMouseEnter(), WidgetEventHandler::RegisterOnMouseLeave(), ItemPreviewWidget::SetForceFlip(), ItemPreviewWidget::SetForceFlipEnable(), SetItemPreview(), SetItemPreviewEx(), SetItemSizeEx(), and UpdateFlip().
Referenced by Init(), and Container::InitIconEx().
InitLock()
void InitLock (EntityAI parent, EntityAI obj, int x_pos, int y_pos, bool flip) inline private
Definition at line 1638 of file Icon.c.
References ItemManager::GetInstance(), WidgetEventHandler::GetInstance(), m_Item, m_ItemPreview, m_Lock, m_Obj, m_RootWidget, Refresh(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), ItemPreviewWidget::SetForceFlip(), ItemPreviewWidget::SetForceFlipEnable(), SetItemPreview(), SetPos(), ItemManager::SetWidgetDraggable(), and UpdateFlip().
IsDragged()
bool IsDragged () inline private
Definition at line 84 of file Icon.c.
References m_IsDragged.
Referenced by HandsPreview::UpdateInterval().
MouseClick()
void MouseClick (Widget w, int x, int y, int button) inline private
Definition at line 889 of file Icon.c.
References g_Game, GetDayZGame(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), GetPlayer(), InventoryLocation::GetSlot(), LayoutHolder::InspectItem(), AttachmentsOutOfReach::IsAttachmentReachable(), IsLeftCtrlDown(), m_HasQuantity, m_Item, m_Lock, m_Obj, SetQuantity(), and ItemManager::SetWidgetDraggable().
MouseEnter()
bool MouseEnter (Widget w, int x, int y) inline private
Definition at line 366 of file Icon.c.
References m_IsDragged, m_Obj, m_SelectedPanel, x, and y.
MouseLeave()
bool MouseLeave (Widget w, Widget s, int x, int y) inline private
Definition at line 377 of file Icon.c.
References m_IsDragged, and m_SelectedPanel.
OnDraggingOverBackground()
void OnDraggingOverBackground (Widget w, int x, int y, Widget reciever) inline private
Definition at line 1301 of file Icon.c.
References HandsContainer::DraggingOverGrid(), GetGame(), ItemManager::GetInstance(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), ItemManager::HideDropzones(), m_HandsIcon, m_Obj, m_Parent, m_PosX, m_PosY, and Pos().
OnPerformCombination()
void OnPerformCombination (int combinationFlags) inline private
Definition at line 548 of file Icon.c.
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, WeaponManager::CanLoadBullet(), Class::CastTo(), GetGame(), GetPlayer(), DayZPlayer::GetWeaponManager(), InventoryCombinationFlags::LOAD_CHAMBER, WeaponManager::LoadBullet(), m_player, InventoryCombinationFlags::NONE, InventoryCombinationFlags::PERFORM_ACTION, ActionManagerClient::PerformActionFromInventory(), InventoryCombinationFlags::SET_ACTION, ActionManagerClient::SetActionFromInventory(), InventoryCombinationFlags::SWAP, InventoryCombinationFlags::TAKE_TO_HANDS, and SplitItemUtils::TakeOrSplitToInventory().
Referenced by FlagAction(), and ShowActionMenuCombine().
OnPerformRecipe()
void OnPerformRecipe (int id) inline private
Definition at line 760 of file Icon.c.
References GetGame(), GetPlayer(), Debug::Log(), and ToString().
Refresh()
override void Refresh () inline private
Definition at line 1370 of file Icon.c.
References m_HandsIcon, m_HasQuantity, m_HasTemperature, m_IsWeapon, RefreshMuzzleIcon(), SetPos(), SetQuantity(), and SetTemperature().
Referenced by HandsPreview::CreateNewIcon(), CreateWhiteBackground(), DestroyWhiteBackground(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), InitEx(), InitLock(), and RefreshIconPos().
RefreshIconPos()
void RefreshIconPos () inline private
Definition at line 1392 of file Icon.c.
References Refresh().
Referenced by RefreshPos().
RefreshMuzzleIcon()
void RefreshMuzzleIcon () inline private
Definition at line 1425 of file Icon.c.
References GetObject(), Weapon_Base::IsShowingChamberedBullet(), and m_AmmoIcons.
Referenced by Refresh(), and UpdateInterval().
RefreshPos()
void RefreshPos (int row, int column) inline private
Definition at line 1409 of file Icon.c.
References m_PosX, m_PosY, RefreshIconPos(), and SetPos().
Referenced by AttachmentCategoriesRow::DropReceived().
RefreshQuickbar()
void RefreshQuickbar () inline private
Definition at line 125 of file Icon.c.
References GetGame(), InventoryMenu(), and MENU_INVENTORY.
RevertToOriginalFlip()
void RevertToOriginalFlip () inline private
Definition at line 1353 of file Icon.c.
References GetGame(), CGame::GetInventoryItemSize(), m_Item, m_PreviousFlipOrientation, and SetSize().
Referenced by DestroyWhiteBackground(), and ~Icon().
SetActive()
override void SetActive (bool active) inline private
Definition at line 89 of file Icon.c.
References GetObject(), m_SelectedPanel, x, and y.
Referenced by HandsPreview::SetDefaultFocus(), CargoContainerRow::SetFocus(), Container::SetLastActive(), HandsPreview::SetLastFocus(), Container::Unfocus(), HandsPreview::Unfocus(), CargoContainerRow::UnfocusAll(), and Container::UpdateSelection().
SetCargoPos()
void SetCargoPos (int x) inline private
Definition at line 1240 of file Icon.c.
References m_CargoPos, and x.
Referenced by Container::InitIconEx(), and Container::MovedInCargo().
SetItemPreview()
void SetItemPreview () inline private
Definition at line 1602 of file Icon.c.
References SetItemPreviewEx().
Referenced by InitEx(), InitLock(), and ~Icon().
SetItemPreviewEx()
void SetItemPreviewEx (bool refresh = true) inline private
Definition at line 1594 of file Icon.c.
References m_ItemPreview, m_Obj, ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetModelOrientation(), and ItemPreviewWidget::SetView().
Referenced by InitEx(), and SetItemPreview().
SetItemSize()
void SetItemSize () inline private
Definition at line 1620 of file Icon.c.
References SetItemSizeEx().
SetItemSizeEx()
void SetItemSizeEx (bool refresh = true) inline private
Definition at line 1607 of file Icon.c.
References GetGame(), CGame::GetInventoryItemSize(), m_Item, m_ItemSizePanel, and m_ItemSizeWidget.
Referenced by InitEx(), and SetItemSize().
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 1196 of file Icon.c.
References WidgetLayoutName::IconMedium, WidgetLayoutName::IconNarrow, WidgetLayoutName::IconWide, WidgetLayoutName::IconXbox, and InventoryMenu().
SetParentWidget()
override void SetParentWidget () inline private
Definition at line 102 of file Icon.c.
References m_Parent.
SetPos() [1/2]
void SetPos () inline private
Definition at line 1924 of file Icon.c.
References SetPosEx().
Referenced by InitLock(), Refresh(), and RefreshPos().
SetPos() [2/2]
void SetPos (int x, int y) inline private
Definition at line 1229 of file Icon.c.
References m_PosX, m_PosY, x, and y.
SetPosEx()
void SetPosEx (bool refresh = true) inline private
Definition at line 1890 of file Icon.c.
References HandsPreview::GetIconSize(), GetPosX(), GetPosY(), m_CargoPos, m_Parent, m_SizeX, and m_SizeY.
Referenced by Container::InitIconEx(), and SetPos().
SetPosX()
void SetPosX (int x) inline private
Definition at line 1850 of file Icon.c.
References m_PosX, and x.
Referenced by Container::InitIconEx().
SetPosY()
void SetPosY (int y) inline private
Definition at line 1855 of file Icon.c.
References m_PosY, and y.
Referenced by Container::InitIconEx().
SetQuantity()
void SetQuantity () inline private
Definition at line 1533 of file Icon.c.
References QuantityConversions::GetItemQuantity(), QuantityConversions::GetItemQuantityMax(), QuantityConversions::GetItemQuantityText(), QuantityConversions::HasItemQuantity(), m_CurrQuantity, m_Item, m_QuantityItem, m_QuantityProgress, m_QuantityStack, QUANTITY_COUNT, QUANTITY_HIDDEN, QUANTITY_PROGRESS, and Math::Round().
Referenced by MouseClick(), Refresh(), HandsPreview::RefreshQuantity(), Container::SplitItem(), and UpdateInterval().
SetSize() [1/2]
void SetSize () inline private
Definition at line 1929 of file Icon.c.
References HandsPreview::GetIconSize(), m_Parent, m_SizeX, and m_SizeY.
Referenced by CreateWhiteBackground(), RevertToOriginalFlip(), and UpdateFlip().
SetSize() [2/2]
void SetSize (int x, int y) inline private
Definition at line 1223 of file Icon.c.
References m_SizeX, m_SizeY, x, and y.
Referenced by Container::InitIconEx(), and Hud::SetCursorIconScale().
SetSizeX()
void SetSizeX (int x) inline private
Definition at line 1860 of file Icon.c.
References m_SizeX, and x.
SetSizeY()
void SetSizeY (int y) inline private
Definition at line 1865 of file Icon.c.
References m_SizeY, and y.
SetSort()
void SetSort (int index) inline private
Definition at line 1583 of file Icon.c.
SetTemperature()
void SetTemperature () inline private
Definition at line 1387 of file Icon.c.
References ItemManager::GetInstance(), m_Obj, m_RootWidget, and ItemManager::SetIconTemperature().
Referenced by Refresh(), UpdateInterval(), and IconsContainer::UpdateItemsTemperature().
ShowActionMenuCombine()
void ShowActionMenuCombine (EntityAI entity1, EntityAI entity2, int combinationFlags, Widget w, bool color_test) inline private
Definition at line 636 of file Icon.c.
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, InventoryCombinationFlags::ATTACH_MAGAZINE, ColorManager::COMBINE_COLOR, InventoryCombinationFlags::COMBINE_QUANTITY, InventoryCombinationFlags::COMBINE_QUANTITY2, ItemManager::GetCenterDropzone(), GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), UIManager::GetMenu(), GetMousePos(), CGame::GetUIManager(), ItemManager::HideDropzones(), InventoryCombinationFlags::LOAD_CHAMBER, InventoryCombinationFlags::NONE, OnPerformCombination(), InventoryCombinationFlags::PERFORM_ACTION, ColorManager::RED_COLOR, InventoryCombinationFlags::SET_ACTION, ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and InventoryCombinationFlags::SWAP.
Referenced by Combine(), and DraggingOverCombine().
Swap()
void Swap (Widget w, int x, int y, Widget receiver) inline private
Definition at line 1093 of file Icon.c.
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), Class::CastTo(), ItemManager::GetDraggedIcon(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), CGame::GetPlayer(), GetPlayer(), ItemManager::HideDropzones(), m_HandsIcon, m_Parent, name, string::Replace(), ItemManager::SetIsDragging(), and ToRefresh().
ToRefresh()
void ToRefresh (Icon icon, Icon icon2) inline private
Definition at line 1190 of file Icon.c.
References m_Parent.
Referenced by DropReceivedFromMain(), and Swap().
UpdateFlip()
void UpdateFlip (bool flipped) inline private
Definition at line 1625 of file Icon.c.
References GetGame(), CGame::GetInventoryItemSize(), m_Item, and SetSize().
Referenced by InitEx(), InitLock(), and ~Icon().
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 1959 of file Icon.c.
References m_HasQuantity, m_HasTemperature, m_IsWeapon, m_Item, RefreshMuzzleIcon(), SetQuantity(), and SetTemperature().
Referenced by HandsPreview::UpdateInterval().
Field Documentation
m_AmmoIcons
protected ref array<ImageWidget> m_AmmoIcons private
Definition at line 37 of file Icon.c.
Referenced by CheckIsWeapon(), and RefreshMuzzleIcon().
m_AmmoTypeIcon
protected ImageWidget m_AmmoTypeIcon private
Definition at line 38 of file Icon.c.
Referenced by CheckIsMagazineEx(), and Icon().
m_CargoPos
protected int m_CargoPos private
Definition at line 18 of file Icon.c.
Referenced by GetCargoPos(), SetCargoPos(), and SetPosEx().
m_ColorWidget
protected Widget m_ColorWidget private
Definition at line 26 of file Icon.c.
Referenced by CreateWhiteBackground(), FullScreen(), and Icon().
m_CurrQuantity
protected float m_CurrQuantity = -1 private
Definition at line 13 of file Icon.c.
Referenced by SetQuantity().
m_HandsIcon
protected bool m_HandsIcon private
Definition at line 17 of file Icon.c.
Referenced by CreateWhiteBackground(), DestroyWhiteBackground(), DoubleClick(), DraggingOver(), DraggingOverSwap(), DropReceivedFromMain(), Icon(), InitEx(), OnDraggingOverBackground(), Refresh(), and Swap().
m_HasQuantity
protected bool m_HasQuantity = false private
Definition at line 12 of file Icon.c.
Referenced by CheckHasQuantityEx(), MouseClick(), Refresh(), and UpdateInterval().
m_HasTemperature
protected bool m_HasTemperature = false private
Definition at line 11 of file Icon.c.
Referenced by CheckHasTemperature(), Refresh(), and UpdateInterval().
m_IsDragged
protected bool m_IsDragged private
Definition at line 19 of file Icon.c.
Referenced by CreateWhiteBackground(), DestroyWhiteBackground(), FullScreen(), IsDragged(), MouseEnter(), MouseLeave(), and ~Icon().
m_IsMagazine
protected bool m_IsMagazine = false private
Definition at line 10 of file Icon.c.
Referenced by CheckIsMagazineEx().
m_IsWeapon
protected bool m_IsWeapon = false private
Definition at line 9 of file Icon.c.
Referenced by CheckIsWeapon(), Refresh(), and UpdateInterval().
m_Item
protected ItemBase m_Item private
Definition at line 16 of file Icon.c.
Referenced by CheckHasQuantityEx(), CheckHasTemperature(), CreateWhiteBackground(), DraggingOverSwap(), DropReceivedFromMain(), InitEx(), InitLock(), MouseClick(), RevertToOriginalFlip(), SetItemSizeEx(), SetQuantity(), UpdateFlip(), and UpdateInterval().
m_ItemPreview
protected ItemPreviewWidget m_ItemPreview private
Definition at line 24 of file Icon.c.
Referenced by CreateWhiteBackground(), DestroyWhiteBackground(), Icon(), InitEx(), InitLock(), and SetItemPreviewEx().
m_ItemSizePanel
protected Widget m_ItemSizePanel private
Definition at line 34 of file Icon.c.
Referenced by Icon(), and SetItemSizeEx().
m_ItemSizeWidget
protected TextWidget m_ItemSizeWidget private
Definition at line 35 of file Icon.c.
Referenced by Icon(), and SetItemSizeEx().
m_Lock
protected EntityAI m_Lock private
Definition at line 8 of file Icon.c.
Referenced by DraggingOver(), DropReceivedFromMain(), InitEx(), InitLock(), and MouseClick().
m_Obj
protected EntityAI m_Obj private
Definition at line 15 of file Icon.c.
Referenced by CheckIsMagazineEx(), CheckIsWeapon(), DoubleClick(), DraggingOver(), GetObject(), InitEx(), InitLock(), MouseClick(), MouseEnter(), OnDraggingOverBackground(), SetItemPreviewEx(), SetTemperature(), and ~Icon().
m_PosX
protected int m_PosX private
Definition at line 5 of file Icon.c.
Referenced by DropReceivedFromBackground(), GetPosX(), OnDraggingOverBackground(), RefreshPos(), SetPos(), and SetPosX().
m_PosY
protected int m_PosY private
Definition at line 6 of file Icon.c.
Referenced by DropReceivedFromBackground(), GetPosY(), OnDraggingOverBackground(), RefreshPos(), SetPos(), and SetPosY().
m_PreviousFlipOrientation
protected bool m_PreviousFlipOrientation private
Definition at line 20 of file Icon.c.
Referenced by CreateWhiteBackground(), and RevertToOriginalFlip().
m_QuantityItem
protected TextWidget m_QuantityItem private
Definition at line 30 of file Icon.c.
Referenced by Icon(), and SetQuantity().
m_QuantityPanel
protected Widget m_QuantityPanel private
Definition at line 29 of file Icon.c.
Referenced by CheckHasQuantityEx(), and Icon().
m_QuantityProgress
protected ProgressBarWidget m_QuantityProgress private
Definition at line 31 of file Icon.c.
Referenced by Icon(), and SetQuantity().
m_QuantityStack
protected Widget m_QuantityStack private
Definition at line 32 of file Icon.c.
Referenced by Icon(), and SetQuantity().
m_SelectedPanel
protected Widget m_SelectedPanel private
Definition at line 27 of file Icon.c.
Referenced by CreateWhiteBackground(), DestroyWhiteBackground(), GetSelectedWidget(), Icon(), MouseEnter(), MouseLeave(), and SetActive().
m_SizeX
protected int m_SizeX private
Definition at line 3 of file Icon.c.
Referenced by GetSizeX(), SetPosEx(), SetSize(), and SetSizeX().
m_SizeY
protected int m_SizeY private
Definition at line 4 of file Icon.c.
Referenced by GetSizeY(), SetPosEx(), SetSize(), and SetSizeY().
NUMBER_OF_TIMERS
const int NUMBER_OF_TIMERS = 2 private
Definition at line 22 of file Icon.c.
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/ContainedItems/Icon.c