DayZ Scripts: AnimSoundLookupTableBank Class Reference
AnimSoundLookupTableBank Class Reference
Private Member Functions
void AnimSoundLookupTableBank ()
SoundLookupTable GetStepTable (string tableName)
SoundLookupTable GetImpactTable (string tableName)
Static Private Member Functions
static AnimSoundLookupTableBank GetInstance ()
Private Attributes
private autoptr map< int, ref SoundLookupTable > m_pTables
Static Private Attributes
static private ref AnimSoundLookupTableBank m_instance
Detailed Description
Definition at line 168 of file DayZAnimEventMaps.c.
Constructor & Destructor Documentation
AnimSoundLookupTableBank()
void AnimSoundLookupTableBank () inline private
Definition at line 170 of file DayZAnimEventMaps.c.
References m_pTables.
Referenced by GetInstance().
Member Function Documentation
GetImpactTable()
SoundLookupTable GetImpactTable (string tableName) inline private
Definition at line 199 of file DayZAnimEventMaps.c.
References string::Hash(), ImpactSoundLookupTable(), SoundLookupTable::LoadTable(), and m_pTables.
Referenced by EntityAI::InitImpactSoundData().
GetInstance()
static AnimSoundLookupTableBank GetInstance () inline static private
Definition at line 176 of file DayZAnimEventMaps.c.
References AnimSoundLookupTableBank(), and m_instance.
Referenced by EntityAI::InitImpactSoundData().
GetStepTable()
SoundLookupTable GetStepTable (string tableName) inline private
Definition at line 185 of file DayZAnimEventMaps.c.
References string::Hash(), SoundLookupTable::LoadTable(), m_pTables, and StepSoundLookupTable().
Field Documentation
m_instance
private ref AnimSoundLookupTableBank m_instance static private
Definition at line 213 of file DayZAnimEventMaps.c.
Referenced by GetInstance().
m_pTables
private autoptr map<int, ref SoundLookupTable> m_pTables private
Definition at line 214 of file DayZAnimEventMaps.c.
Referenced by AnimSoundLookupTableBank(), GetImpactTable(), and GetStepTable().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/DayZAnimEventMaps.c