DayZ Scripts: MessageReceiverBase Class Reference
MessageReceiverBase Class Reference
Private Member Functions
void OnReceive (int channel)
void OnReceiveInt (int channel, int value)
void OnReceiveFloat (int channel, float value)
void OnReceiveString (int channel, string value)
void OnReceiveParam (int channel, Param params)
This method is called when an object inheriting from this class subscribes to a channel, and a message along with an object reference is broadcast on that channel, if the object was created just for the purpose of relaying information and is not referenced anywhere else, it should be deleted after processing inside this method.
void MessageReceiverBase ()
void Subscribe (int channel)
void Unsubscribe (int channel)
void UnsubscribeAll ()
void Broadcast (int channel)
void BroadcastInt (int channel, int value)
void BroadcastFloat (int channel, float value)
void BroadcastString (int channel, string value)
void BroadcastParam (int channel, Param params)
void Log (string message)
void AgentBase ()
void Init ()
int GetAgentType ()
float GetDieOffSpeedEx (PlayerBase player)
EStatLevels GetPotencyEx (PlayerBase player)
float GetInvasibilityEx (PlayerBase player)
EStatLevels GetPotency ()
float GetDieOffSpeed ()
float GetAntiboticsResistance ()
float GetAntibioticsResistanceEx (PlayerBase player)
float GetInvasibility ()
bool GrowDuringAntibioticsAttack (PlayerBase player)
float GetDigestibility ()
float CalculateAutoinfectProbability (float userprob)
bool AutoinfectCheck (float deltaT, PlayerBase player)
bool CanAutoinfectPlayer (PlayerBase player)
float GetTransferabilityIn ()
float GetTransferabilityOut ()
float GetTransferabilityAirOut ()
int GetMaxCount ()
string GetName ()
void DisplayElementBase (PlayerBase player)
bool IsClientOnly ()
bool IsValueChanged ()
void UpdateHUD ()
int GetNumberOfBits ()
void SetValue (int value, int range=0)
int GetValue ()
int BitToDec (int mask, int index, int length)
int GetCompareMask ()
int GetType ()
int TranslateLevelToStatus (int level)
Private Attributes
PluginMessageManager m_ModuleMessageManager
string m_System
float m_Type = 0
float m_Invasibility
float m_TransferabilityIn
float m_TransferabilityOut
float m_Digestibility = 0.1
int m_MaxCount = 1
float m_AutoinfectProbability = CalculateAutoinfectProbability(0)
float m_TransferabilityAirOut
float m_AntibioticsResistance = 1
EStatLevels m_Potency = EStatLevels.MEDIUM
float m_DieOffSpeed = 1
int m_Value
int m_ValueLast = -99999
int m_Key = 0
int m_Type = 0
int m_Range = 0
int m_Colors [7]
string m_Labels [7]
int m_Pos = 1
int NUM_OF_BITS
bool m_IsClientOnly = false
PlayerBase m_Player
PluginPlayerStatus m_ModulePlayerStatus
Constructor & Destructor Documentation
MessageReceiverBase()
void MessageReceiverBase () inline private
References GetPlugin(), and m_ModuleMessageManager.
Member Function Documentation
AgentBase()
void AgentBase () inline private
References AgentBase::Init().
AutoinfectCheck()
bool AutoinfectCheck (float deltaT, PlayerBase player) inline private
References AgentBase::CanAutoinfectPlayer(), and Math::RandomFloat01().
BitToDec()
int BitToDec (int mask, int index, int length) inline private
Broadcast()
void Broadcast (int channel) inline private
References m_ModuleMessageManager.
BroadcastFloat()
void BroadcastFloat (int channel, float value) inline private
References m_ModuleMessageManager.
BroadcastInt()
void BroadcastInt (int channel, int value) inline private
References m_ModuleMessageManager.
BroadcastParam()
void BroadcastParam (int channel, Param params) inline private
References m_ModuleMessageManager.
BroadcastString()
void BroadcastString (int channel, string value) inline private
References m_ModuleMessageManager.
CalculateAutoinfectProbability()
float CalculateAutoinfectProbability (float userprob) inline private
References Math::Pow().
CanAutoinfectPlayer()
bool CanAutoinfectPlayer (PlayerBase player) inline private
DisplayElementBase()
void DisplayElementBase (PlayerBase player) inline private
References GetPlugin(), m_ModulePlayerStatus, m_Player, and m_System.
GetAgentType()
int GetAgentType () inline private
References m_Type.
GetAntibioticsResistanceEx()
float GetAntibioticsResistanceEx (PlayerBase player) inline private
GetAntiboticsResistance()
float GetAntiboticsResistance () inline private
GetCompareMask()
int GetCompareMask () inline private
References Math::Pow().
GetDieOffSpeed()
float GetDieOffSpeed () inline private
GetDieOffSpeedEx()
float GetDieOffSpeedEx (PlayerBase player) inline private
GetDigestibility()
float GetDigestibility () inline private
GetInvasibility()
float GetInvasibility () inline private
GetInvasibilityEx()
float GetInvasibilityEx (PlayerBase player) inline private
GetMaxCount()
int GetMaxCount () inline private
GetName()
string GetName () inline private
GetNumberOfBits()
int GetNumberOfBits () inline private
GetPotency()
EStatLevels GetPotency () inline private
GetPotencyEx()
EStatLevels GetPotencyEx (PlayerBase player) inline private
GetTransferabilityAirOut()
float GetTransferabilityAirOut () inline private
GetTransferabilityIn()
float GetTransferabilityIn () inline private
GetTransferabilityOut()
float GetTransferabilityOut () inline private
GetType()
int GetType () inline private
References m_Type.
GetValue()
int GetValue () inline private
References m_Value.
GrowDuringAntibioticsAttack()
bool GrowDuringAntibioticsAttack (PlayerBase player) inline private
Init()
void Init () private
IsClientOnly()
bool IsClientOnly () inline private
IsValueChanged()
bool IsValueChanged () inline private
References m_Value.
Log()
void Log (string message) inline private
References Debug::Log(), and m_System.
OnReceive()
void OnReceive (int channel) inline private
Referenced by PluginBase::Broadcast().
OnReceiveFloat()
void OnReceiveFloat (int channel, float value) inline private
Referenced by PluginBase::BroadcastFloat().
OnReceiveInt()
void OnReceiveInt (int channel, int value) inline private
Referenced by PluginBase::BroadcastInt().
OnReceiveParam()
void OnReceiveParam (int channel, Param params) inline private
This method is called when an object inheriting from this class subscribes to a channel, and a message along with an object reference is broadcast on that channel, if the object was created just for the purpose of relaying information and is not referenced anywhere else, it should be deleted after processing inside this method.
OnReceiveString()
void OnReceiveString (int channel, string value) inline private
SetValue()
void SetValue (int value, int range = 0) inline private
References m_Value.
Subscribe()
void Subscribe (int channel) inline private
References m_ModuleMessageManager.
TranslateLevelToStatus()
int TranslateLevelToStatus (int level) inline private
Unsubscribe()
void Unsubscribe (int channel) inline private
References IsPluginManagerExists(), and m_ModuleMessageManager.
UnsubscribeAll()
void UnsubscribeAll () inline private
References IsPluginManagerExists(), and m_ModuleMessageManager.
UpdateHUD()
void UpdateHUD () inline private
References m_Value.
Field Documentation
m_AntibioticsResistance
float m_AntibioticsResistance = 1 private
m_AutoinfectProbability
float m_AutoinfectProbability = CalculateAutoinfectProbability(0) private
m_Colors
int m_Colors[7] private
m_DieOffSpeed
float m_DieOffSpeed = 1 private
m_Digestibility
float m_Digestibility = 0.1 private
m_Invasibility
float m_Invasibility private
m_IsClientOnly
bool m_IsClientOnly = false private
m_Key
int m_Key = 0 private
m_Labels
string m_Labels[7] private
m_MaxCount
int m_MaxCount = 1 private
m_ModuleMessageManager
PluginMessageManager m_ModuleMessageManager private
Referenced by Broadcast(), BroadcastFloat(), BroadcastInt(), BroadcastParam(), BroadcastString(), MessageReceiverBase(), Subscribe(), Unsubscribe(), and UnsubscribeAll().
m_ModulePlayerStatus
PluginPlayerStatus m_ModulePlayerStatus private
m_Player
PlayerBase m_Player private
m_Pos
int m_Pos = 1 private
m_Potency
EStatLevels m_Potency = EStatLevels.MEDIUM private
m_Range
int m_Range = 0 private
m_System
string m_System private
Referenced by Log().
m_TransferabilityAirOut
float m_TransferabilityAirOut private
m_TransferabilityIn
float m_TransferabilityIn private
m_TransferabilityOut
float m_TransferabilityOut private
m_Type [1/2]
float m_Type = 0 private
m_Type [2/2]
int m_Type = 0 private
m_Value
int m_Value private
m_ValueLast
int m_ValueLast = -99999 private
NUM_OF_BITS
int NUM_OF_BITS private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/MessageReceiverBase.c
P:/scripts/4_World/Classes/TransmissionAgents/Agents/AgentBase.c
P:/scripts/4_World/Classes/VirtualHud/DisplayElementBase.c