DayZ Scripts: ActionAttachOnSelection Class Reference
ActionAttachOnSelection Class Reference
Private Member Functions
void ActionAttachOnSelection ()
override void CreateConditionComponents ()
override ActionData CreateActionData ()
int FindSlotIdToAttachOrCombine (PlayerBase player, ActionTarget target, ItemBase item)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=null)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
Constructor & Destructor Documentation
ActionAttachOnSelection()
void ActionAttachOnSelection () inline private
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References FindSlotIdToAttachOrCombine(), GetGame(), and InventorySlots::INVALID.
CreateActionData()
override ActionData CreateActionData () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References m_ConditionItem, and m_ConditionTarget.
FindSlotIdToAttachOrCombine()
int FindSlotIdToAttachOrCombine (PlayerBase player, ActionTarget target, ItemBase item) inline private
References ItemBase::CanBeCombined(), InventorySlots::GetSlotIdFromString(), and InventorySlots::INVALID.
Referenced by ActionCondition(), and SetupAction().
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
References ClearInventoryReservationEx(), AttachActionData::m_AttSlot, ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
References ClearInventoryReservationEx(), GetGame(), AttachActionData::m_AttSlot, ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = null) inline private
References FindSlotIdToAttachOrCombine(), GetGame(), InventorySlots::INVALID, and AttachActionData::m_AttSlot.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionAttachOnSelection.c