DayZ Scripts: array Class Reference
array Class Reference
Result for an object found in CGame.IsBoxCollidingGeometryProxy.
Private Member Functions
void ParticleProperties (vector localPos, int flags, Object parent=null, vector localOri=vector.Zero, Class owner=null)
Constructor (ctor)
void ~ParticleProperties ()
dtor
void TFCaller (Class instance, string test, TFResult result)
TFResult Run (float dt)
string GetTest ()
string GetTestEx ()
void KeybindingsContainer (int index, Input input, Widget parent, KeybindingsMenu menu)
string GetLayoutName ()
void OnSelectKBPreset (int index)
void ReloadElements ()
void AddSubgroup (int sort_index, Widget parent, Input input)
void CreateSubgroups (Widget parent, Input input)
void AddElement (int index, Widget parent, Input input)
bool IsEnteringKeyBind ()
void ClearKeybind (int key_index)
void ClearAlternativeKeybind (int key_index)
void StartEnteringKeybind (int key_index)
void CancelEnteringKeybind ()
void StartEnteringAlternateKeybind (int key_index)
void CancelEnteringAlternateKeybind ()
bool IsChanged ()
is anything changed?
void Apply ()
void Reset (bool forced=false)
void Update (float timeslice)
void SwitchSubgroup (int index)
Data access
Methods to retrieve the data in script
proto Object GetParent ()
proto Class GetOwner ()
proto vector GetLocalPos ()
proto vector GetLocalOri ()
proto int GetPPFlags ()
proto bool IsPlayOnCreation ()
proto bool IsForceWorldRotation ()
proto bool IsKeepParentOnEnd ()
Private Attributes
Object obj
Object inside of box.
Object parent
Parent of proxy object.
int hierLevel
How deep in the proxy hierarchy are we.
int geomLevel
What geometry was the object found in (will either be primaryType or secondaryType)
ref ComponentInfoArray componentInfo
Either the first component found or all of them depending on "fullComponentInfo".
ref ProxyInfoArray proxyInfo
Either the first proxy found or all of them depending on "fullComponentInfo".
private Class m_Instance
private string m_Test
private ref TFResult m_Result
protected const int NO_SORTING = -1
protected Widget m_Root
protected KeybindingsMenu m_Menu
protected ScrollWidget m_Scroll
protected ref map< int, ref ElementArray > m_KeyWidgetElements
protected int m_CurrentSettingKeyIndex = -1
protected int m_CurrentSettingAlternateKeyIndex = -1
protected ref array< Widget > m_Subgroups
Detailed Description
Result for an object found in CGame.IsBoxCollidingGeometryProxy.
Properties while creating a ParticleSource.
Definition at line 27 of file IsBoxCollidingGeometryProxyClasses.c.
Constructor & Destructor Documentation
~ParticleProperties()
void ~ParticleProperties () inline private
dtor
Definition at line 83 of file ParticleSource.c.
Member Function Documentation
AddElement()
void AddElement (int index, Widget parent, Input input) inline private
Definition at line 100 of file KeybindingsContainer.c.
References ScriptedWidgetEventHandler::KeybindingElementNew().
AddSubgroup()
void AddSubgroup (int sort_index, Widget parent, Input input) inline private
Definition at line 55 of file KeybindingsContainer.c.
References ScriptedWidgetEventHandler::AddElement(), WorkspaceWidget::CreateWidgets(), GetGame(), InputUtils::GetInputActionSortingMap(), InputUtils::GetUnsortedInputActions(), and CGame::GetWorkspace().
Apply()
void Apply () inline private
Definition at line 182 of file KeybindingsContainer.c.
References UAInput::AddAlternative(), UAInput::AlternativeCount(), UAInput::BindComboByHash(), UAInput::ClearDeviceBind(), UAInputAPI::GetInputByID(), and GetUApi().
CancelEnteringAlternateKeybind()
void CancelEnteringAlternateKeybind () inline private
Definition at line 154 of file KeybindingsContainer.c.
CancelEnteringKeybind()
void CancelEnteringKeybind () inline private
Definition at line 135 of file KeybindingsContainer.c.
ClearAlternativeKeybind()
void ClearAlternativeKeybind (int key_index) inline private
Definition at line 123 of file KeybindingsContainer.c.
References m_Menu.
Referenced by ScriptedWidgetEventHandler::OnMouseButtonUp().
ClearKeybind()
void ClearKeybind (int key_index) inline private
Definition at line 118 of file KeybindingsContainer.c.
References m_Menu.
Referenced by ScriptedWidgetEventHandler::OnMouseButtonUp().
CreateSubgroups()
void CreateSubgroups (Widget parent, Input input) inline private
Definition at line 80 of file KeybindingsContainer.c.
References ScriptedWidgetEventHandler::AddSubgroup(), InputUtils::GetInputActionSortingMap(), and InputUtils::GetUnsortedInputActions().
GetLayoutName()
string GetLayoutName () inline private
Definition at line 31 of file KeybindingsContainer.c.
GetLocalOri()
proto vector GetLocalOri () private
GetLocalPos()
proto vector GetLocalPos () private
GetOwner()
proto Class GetOwner () private
GetParent()
proto Object GetParent () private
GetPPFlags()
proto int GetPPFlags () private
GetTest()
string GetTest () inline private
Definition at line 70 of file TestFramework.c.
GetTestEx()
string GetTestEx () inline private
Definition at line 75 of file TestFramework.c.
References string::Format(), and m_Instance.
IsChanged()
bool IsChanged () inline private
is anything changed?
Definition at line 167 of file KeybindingsContainer.c.
IsEnteringKeyBind()
bool IsEnteringKeyBind () inline private
Definition at line 113 of file KeybindingsContainer.c.
IsForceWorldRotation()
proto bool IsForceWorldRotation () private
IsKeepParentOnEnd()
proto bool IsKeepParentOnEnd () private
IsPlayOnCreation()
proto bool IsPlayOnCreation () private
KeybindingsContainer()
void KeybindingsContainer (int index, Input input, Widget parent, KeybindingsMenu menu) inline private
Definition at line 15 of file KeybindingsContainer.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), ScriptedWidgetEventHandler::GetLayoutName(), CGame::GetWorkspace(), m_Menu, and m_Root.
OnSelectKBPreset()
void OnSelectKBPreset (int index) inline private
Definition at line 36 of file KeybindingsContainer.c.
References UAInputAPI::Export(), GetUApi(), UAInputAPI::PresetSelect(), and UAInputAPI::SaveInputPresetMiscData().
ParticleProperties()
void ParticleProperties (vector localPos, int flags, Object parent = null, vector localOri = vector.Zero, Class owner = null) inline private
Constructor (ctor)
Parameters
localPos vector Local position of particle, if no parent this is world position
flags int See ParticlePropertiesFlags
parent Object The parent that the ParticleSource will be added to as a child
localOri vector Local orientation of particle, if no parent this is world orientation
owner Class The owning instance for this particle, as long as it exists, this particle will not be reused (unless flagged) Important when for example virtual is enabled since if the particle owner has been deleted, the virtual should not be converted Only fill in owner if necessary, for example when the owner is reusing the same particle after storing it
Definition at line 78 of file ParticleSource.c.
ReloadElements()
void ReloadElements () inline private
Definition at line 44 of file KeybindingsContainer.c.
Reset()
void Reset (bool forced = false) inline private
Definition at line 236 of file KeybindingsContainer.c.
Run()
TFResult Run (float dt) inline private
Definition at line 58 of file TestFramework.c.
References ScriptModule::CallFunction(), ErrorEx, CGame::GameScript, GetGame(), and m_Instance.
Referenced by AreaDamageBase::EvaluateDamage_Loop().
StartEnteringAlternateKeybind()
void StartEnteringAlternateKeybind (int key_index) inline private
Definition at line 147 of file KeybindingsContainer.c.
References m_Menu.
StartEnteringKeybind()
void StartEnteringKeybind (int key_index) inline private
Definition at line 128 of file KeybindingsContainer.c.
References m_Menu.
SwitchSubgroup()
void SwitchSubgroup (int index) inline private
Definition at line 295 of file KeybindingsContainer.c.
TFCaller()
void TFCaller (Class instance, string test, TFResult result) inline private
Definition at line 51 of file TestFramework.c.
References m_Instance.
Update()
void Update (float timeslice) inline private
Definition at line 250 of file KeybindingsContainer.c.
References UAInputAPI::DeterminedCount(), UAInputAPI::DeterminePressedButton(), GetDayZGame(), UAInputAPI::GetDetermined(), GetUApi(), m_Menu, and name.
Referenced by SymptomManager::UpdateActiveSymptoms().
Field Documentation
componentInfo
ref ComponentInfoArray componentInfo private
Either the first component found or all of them depending on "fullComponentInfo".
Definition at line 35 of file IsBoxCollidingGeometryProxyClasses.c.
geomLevel
int geomLevel private
What geometry was the object found in (will either be primaryType or secondaryType)
Definition at line 33 of file IsBoxCollidingGeometryProxyClasses.c.
hierLevel
int hierLevel private
How deep in the proxy hierarchy are we.
Definition at line 32 of file IsBoxCollidingGeometryProxyClasses.c.
m_CurrentSettingAlternateKeyIndex
protected int m_CurrentSettingAlternateKeyIndex = -1 private
Definition at line 11 of file KeybindingsContainer.c.
m_CurrentSettingKeyIndex
protected int m_CurrentSettingKeyIndex = -1 private
Definition at line 10 of file KeybindingsContainer.c.
m_Instance
private Class m_Instance private
Definition at line 47 of file TestFramework.c.
m_KeyWidgetElements
protected ref map<int, ref ElementArray> m_KeyWidgetElements private
Definition at line 9 of file KeybindingsContainer.c.
m_Menu
protected KeybindingsMenu m_Menu private
Definition at line 6 of file KeybindingsContainer.c.
m_Result
private ref TFResult m_Result private
Definition at line 49 of file TestFramework.c.
m_Root
protected Widget m_Root private
Definition at line 5 of file KeybindingsContainer.c.
m_Scroll
protected ScrollWidget m_Scroll private
Definition at line 7 of file KeybindingsContainer.c.
m_Subgroups
protected ref array<Widget> m_Subgroups private
Definition at line 13 of file KeybindingsContainer.c.
m_Test
private string m_Test private
Definition at line 48 of file TestFramework.c.
NO_SORTING
protected const int NO_SORTING = -1 private
Definition at line 4 of file KeybindingsContainer.c.
obj
Object obj private
Object inside of box.
Definition at line 29 of file IsBoxCollidingGeometryProxyClasses.c.
Referenced by Hud::RefreshPlayerTags().
parent
Object parent private
Parent of proxy object.
Definition at line 30 of file IsBoxCollidingGeometryProxyClasses.c.
proxyInfo
ref ProxyInfoArray proxyInfo private
Either the first proxy found or all of them depending on "fullComponentInfo".
Definition at line 36 of file IsBoxCollidingGeometryProxyClasses.c.
The documentation for this class was generated from the following files:
P:/scripts/3_Game/IsBoxCollidingGeometryProxyClasses.c
P:/scripts/3_Game/Systems/TestFramework.c
P:/scripts/5_Mission/GUI/NewUI/Keybindings/KeybindingsContainer.c
P:/scripts/3_Game/Particles/ParticleManager/ParticleSource.c