DayZ Scripts: HelmetBase Class Reference
HelmetBase Class Reference
Private Member Functions
override array< int > GetEffectWidgetTypes ()
override bool CanPutAsAttachment (EntityAI parent)
override bool IsObstructingVoice ()
override int GetVoiceEffect ()
override int GetGlassesEffectID ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void OnDebugSpawn ()
override array< int > GetEffectWidgetTypes ()
override bool CanPutAsAttachment (EntityAI parent)
override bool IsObstructingVoice ()
override int GetVoiceEffect ()
Detailed Description
Definition at line 1 of file BallisticHelmet_ColorBase.c.
Member Function Documentation
CanPutAsAttachment() [1/3]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 8 of file DarkMotoHelmet_ColorBase.c.
CanPutAsAttachment() [2/3]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file Mich2001Helmet.c.
CanPutAsAttachment() [3/3]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 8 of file MotoHelmet_ColorBase.c.
GetEffectWidgetTypes() [1/2]
override array< int > GetEffectWidgetTypes () inline private
Definition at line 3 of file DarkMotoHelmet_ColorBase.c.
GetEffectWidgetTypes() [2/2]
override array< int > GetEffectWidgetTypes () inline private
Definition at line 3 of file MotoHelmet_ColorBase.c.
GetGlassesEffectID()
override int GetGlassesEffectID () inline private
Definition at line 37 of file DarkMotoHelmet_ColorBase.c.
GetVoiceEffect() [1/2]
override int GetVoiceEffect () inline private
Definition at line 32 of file DarkMotoHelmet_ColorBase.c.
GetVoiceEffect() [2/2]
override int GetVoiceEffect () inline private
Definition at line 32 of file MotoHelmet_ColorBase.c.
IsObstructingVoice() [1/2]
override bool IsObstructingVoice () inline private
Definition at line 27 of file DarkMotoHelmet_ColorBase.c.
IsObstructingVoice() [2/2]
override bool IsObstructingVoice () inline private
Definition at line 27 of file MotoHelmet_ColorBase.c.
OnDebugSpawn() [1/3]
override void OnDebugSpawn () inline private
Definition at line 4 of file DirtBikeHelmet_ColorBase.c.
References Class::CastTo().
OnDebugSpawn() [2/3]
override void OnDebugSpawn () inline private
Definition at line 4 of file GorkaHelmetComplete.c.
References Class::CastTo().
OnDebugSpawn() [3/3]
override void OnDebugSpawn () inline private
Definition at line 26 of file Mich2001Helmet.c.
References Class::CastTo().
SetActions()
override void SetActions () inline private
Definition at line 16 of file Mich2001Helmet.c.
References AddAction().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/BallisticHelmet_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/DarkMotoHelmet_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/DirtBikeHelmet_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/GorkaHelmetComplete.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/Mich2001Helmet.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HelmetBase/MotoHelmet_ColorBase.c