DayZ Scripts: SceneData Class Reference
SceneData Class Reference
Private Member Functions
void SceneData ()
array< ref SceneObject > GetSceneObjects ()
array< ref ScenePlayer > GetScenePlayers ()
array< ref SceneObject > GetSceneObjectsAll ()
string GetNameScene ()
void SetNameScene (string name)
string GetNameMission ()
void SetNameMission (string name)
float GetInitTime ()
void SetInitTime (float time)
int GetInitYear ()
void SetInitYear (int value)
int GetInitMonth ()
void SetInitMonth (int value)
int GetInitDay ()
void SetInitDay (int value)
int GetInitHour ()
void SetInitHour (int value)
int GetInitMinute ()
void SetInitMinute (int value)
float GetInitOvercast ()
void SetInitOvercast (float value)
float GetInitRain ()
void SetInitRain (float value)
float GetInitFog ()
void SetInitFog (float value)
float GetInitWindForce ()
void SetInitWindForce (float value)
SceneObject CreateSceneObject (string obj_name, vector pos)
ScenePlayer CreateScenePlayer ()
void Clear ()
SceneObject AddObject (EntityAI e)
SceneObject GetSceneObjectByEntityAI (EntityAI e)
void DeleteSceneObject (SceneObject scene_object)
Private Attributes
protected string m_NameScene
protected string m_NameMission
protected float m_InitTime
protected int m_DateInitYear
protected int m_DateInitMonth
protected int m_DateInitDay
protected int m_DateInitHour
protected int m_DateInitMinute
protected float m_WeaterInitOvercast
protected float m_WeaterInitRain
protected float m_WeaterInitFog
protected float m_WeaterInitWindForce
protected ref array< ref SceneObject > m_Objects
protected ref array< ref ScenePlayer > m_Players
protected ref array< ref SceneObject > m_AllObjs
Constructor & Destructor Documentation
SceneData()
void SceneData () inline private
References m_AllObjs, m_Objects, and m_Players.
Member Function Documentation
AddObject()
SceneObject AddObject (EntityAI e) inline private
References SceneObject::Init(), SceneObject::IsPlayer(), SceneObject::LinkEntityAI(), m_Objects, and m_Players.
Clear()
void Clear () inline private
References m_AllObjs, m_Objects, and m_Players.
CreateSceneObject()
SceneObject CreateSceneObject (string obj_name, vector pos) inline private
References SceneObject::Init(), and m_Objects.
Referenced by PluginConfigHandler::LoadSceneObjects().
CreateScenePlayer()
ScenePlayer CreateScenePlayer () inline private
References m_Players, STRING_EMPTY, and Vector().
Referenced by PluginConfigHandler::LoadScenePlayer().
DeleteSceneObject()
void DeleteSceneObject (SceneObject scene_object) inline private
References m_Objects, and m_Players.
GetInitDay()
int GetInitDay () inline private
References m_DateInitDay.
Referenced by PluginConfigHandler::SaveSceneSettings().
GetInitFog()
float GetInitFog () inline private
References m_WeaterInitFog.
Referenced by PluginConfigHandler::SaveSceneWeather(), and PluginLocalProfile::SceneSave().
GetInitHour()
int GetInitHour () inline private
References m_DateInitHour.
Referenced by PluginConfigHandler::SaveSceneSettings().
GetInitMinute()
int GetInitMinute () inline private
References m_DateInitMinute.
Referenced by PluginConfigHandler::SaveSceneSettings().
GetInitMonth()
int GetInitMonth () inline private
References m_DateInitMonth.
Referenced by PluginConfigHandler::SaveSceneSettings().
GetInitOvercast()
float GetInitOvercast () inline private
References m_WeaterInitOvercast.
Referenced by PluginConfigHandler::SaveSceneWeather().
GetInitRain()
float GetInitRain () inline private
References m_WeaterInitRain.
Referenced by PluginConfigHandler::SaveSceneWeather(), and PluginLocalProfile::SceneSave().
GetInitTime()
float GetInitTime () inline private
References m_InitTime.
Referenced by PluginConfigHandler::SaveSceneSettings(), and PluginLocalProfile::SceneSave().
GetInitWindForce()
float GetInitWindForce () inline private
References m_WeaterInitWindForce.
Referenced by PluginConfigHandler::SaveSceneWeather().
GetInitYear()
int GetInitYear () inline private
References m_DateInitYear.
Referenced by PluginConfigHandler::SaveSceneSettings().
GetNameMission()
string GetNameMission () inline private
References m_NameMission.
Referenced by PluginConfigHandler::SaveSceneSettings(), and PluginLocalProfile::SceneSave().
GetNameScene()
string GetNameScene () inline private
References m_NameScene.
Referenced by PluginConfigHandler::SceneDataSave(), and PluginLocalProfile::SceneSave().
GetSceneObjectByEntityAI()
SceneObject GetSceneObjectByEntityAI (EntityAI e) inline private
References m_Objects, and m_Players.
Referenced by PluginBase::OnRPCSyncSceneObject().
GetSceneObjects()
array< ref SceneObject > GetSceneObjects () inline private
References m_Objects.
Referenced by GetSceneObjectsAll(), PluginConfigHandler::SaveSceneObjects(), and PluginLocalProfile::SceneSave().
GetSceneObjectsAll()
array< ref SceneObject > GetSceneObjectsAll () inline private
References GetSceneObjects(), GetScenePlayers(), and m_AllObjs.
GetScenePlayers()
array< ref ScenePlayer > GetScenePlayers () inline private
References m_Players.
Referenced by GetSceneObjectsAll(), and PluginConfigHandler::SaveScenePlayer().
SetInitDay()
void SetInitDay (int value) inline private
References GetGame(), CGame::GetWorld(), m_DateInitDay, m_DateInitHour, m_DateInitMinute, m_DateInitMonth, m_DateInitYear, and World::SetDate().
Referenced by PluginConfigHandler::LoadSceneSettings().
SetInitFog()
void SetInitFog (float value) inline private
References Weather::GetFog(), GetGame(), CGame::GetWeather(), m_WeaterInitFog, and WeatherPhenomenon::Set().
Referenced by PluginConfigHandler::LoadSceneWeather().
SetInitHour()
void SetInitHour (int value) inline private
References GetGame(), CGame::GetWorld(), m_DateInitDay, m_DateInitHour, m_DateInitMinute, m_DateInitMonth, m_DateInitYear, and World::SetDate().
Referenced by PluginConfigHandler::LoadSceneSettings().
SetInitMinute()
void SetInitMinute (int value) inline private
References GetGame(), CGame::GetWorld(), m_DateInitDay, m_DateInitHour, m_DateInitMinute, m_DateInitMonth, m_DateInitYear, and World::SetDate().
Referenced by PluginConfigHandler::LoadSceneSettings().
SetInitMonth()
void SetInitMonth (int value) inline private
References GetGame(), CGame::GetWorld(), m_DateInitDay, m_DateInitHour, m_DateInitMinute, m_DateInitMonth, m_DateInitYear, and World::SetDate().
Referenced by PluginConfigHandler::LoadSceneSettings().
SetInitOvercast()
void SetInitOvercast (float value) inline private
References GetGame(), Weather::GetOvercast(), CGame::GetWeather(), m_WeaterInitOvercast, and WeatherPhenomenon::Set().
Referenced by PluginConfigHandler::LoadSceneWeather().
SetInitRain()
void SetInitRain (float value) inline private
References GetGame(), Weather::GetRain(), CGame::GetWeather(), m_WeaterInitRain, and WeatherPhenomenon::Set().
Referenced by PluginConfigHandler::LoadSceneWeather().
SetInitTime()
void SetInitTime (float time) inline private
References m_InitTime.
Referenced by PluginConfigHandler::LoadSceneSettings().
SetInitWindForce()
void SetInitWindForce (float value) inline private
References GetGame(), CGame::GetWeather(), m_WeaterInitWindForce, and Weather::SetWindSpeed().
Referenced by PluginConfigHandler::LoadSceneWeather().
SetInitYear()
void SetInitYear (int value) inline private
References GetGame(), CGame::GetWorld(), m_DateInitDay, m_DateInitHour, m_DateInitMinute, m_DateInitMonth, m_DateInitYear, and World::SetDate().
Referenced by PluginConfigHandler::LoadSceneSettings().
SetNameMission()
void SetNameMission (string name) inline private
References m_NameMission, and name.
Referenced by PluginConfigHandler::LoadSceneSettings().
SetNameScene()
void SetNameScene (string name) inline private
References m_NameScene, and name.
Referenced by PluginConfigHandler::SceneDataLoad().
Field Documentation
m_AllObjs
protected ref array<ref SceneObject> m_AllObjs private
Referenced by Clear(), GetSceneObjectsAll(), and SceneData().
m_DateInitDay
protected int m_DateInitDay private
Referenced by GetInitDay(), SetInitDay(), SetInitHour(), SetInitMinute(), SetInitMonth(), and SetInitYear().
m_DateInitHour
protected int m_DateInitHour private
Referenced by GetInitHour(), SetInitDay(), SetInitHour(), SetInitMinute(), SetInitMonth(), and SetInitYear().
m_DateInitMinute
protected int m_DateInitMinute private
Referenced by GetInitMinute(), SetInitDay(), SetInitHour(), SetInitMinute(), SetInitMonth(), and SetInitYear().
m_DateInitMonth
protected int m_DateInitMonth private
Referenced by GetInitMonth(), SetInitDay(), SetInitHour(), SetInitMinute(), SetInitMonth(), and SetInitYear().
m_DateInitYear
protected int m_DateInitYear private
Referenced by GetInitYear(), SetInitDay(), SetInitHour(), SetInitMinute(), SetInitMonth(), and SetInitYear().
m_InitTime
protected float m_InitTime private
Referenced by GetInitTime(), and SetInitTime().
m_NameMission
protected string m_NameMission private
Referenced by GetNameMission(), and SetNameMission().
m_NameScene
protected string m_NameScene private
Referenced by GetNameScene(), and SetNameScene().
m_Objects
protected ref array<ref SceneObject> m_Objects private
Referenced by AddObject(), Clear(), CreateSceneObject(), DeleteSceneObject(), GetSceneObjectByEntityAI(), GetSceneObjects(), and SceneData().
m_Players
protected ref array<ref ScenePlayer> m_Players private
Referenced by AddObject(), Clear(), CreateScenePlayer(), DeleteSceneObject(), GetSceneObjectByEntityAI(), GetScenePlayers(), and SceneData().
m_WeaterInitFog
protected float m_WeaterInitFog private
Referenced by GetInitFog(), and SetInitFog().
m_WeaterInitOvercast
protected float m_WeaterInitOvercast private
Referenced by GetInitOvercast(), and SetInitOvercast().
m_WeaterInitRain
protected float m_WeaterInitRain private
Referenced by GetInitRain(), and SetInitRain().
m_WeaterInitWindForce
protected float m_WeaterInitWindForce private
Referenced by GetInitWindForce(), and SetInitWindForce().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/SceneEditor/SceneData.c