DayZ Scripts: CGame Class Reference
CGame Class Reference
Private Member Functions
void DayZGame ()
private void ~DayZGame ()
void DeferredInit ()
void GlobalsInit ()
void RegisterProfilesOptions ()
void ResetProfileOptions ()
void SetMissionPath (string path)
Called from C++.
string GetMissionPath ()
string GetMissionFolderPath ()
override ScriptCallQueue GetCallQueue (int call_category)
override ScriptInvoker GetUpdateQueue (int call_category)
override ScriptInvoker GetPostUpdateQueue (int call_category)
override TimerQueue GetTimerQueue (int call_category)
override DragQueue GetDragQueue ()
void OnGameplayDataHandlerLoad ()
int GetMissionState ()
void SetMissionState (int state)
bool GetProfileOption (EDayZProfilesOptions option)
bool GetProfileOptionBool (EDayZProfilesOptions option)
int GetProfileOptionInt (EDayZProfilesOptions option)
float GetProfileOptionFloat (EDayZProfilesOptions option)
bool GetProfileOptionDefault (EDayZProfilesOptions option)
bool GetProfileOptionDefaultBool (EDayZProfilesOptions option)
int GetProfileOptionDefaultInt (EDayZProfilesOptions option)
float GetProfileOptionDefaultFloat (EDayZProfilesOptions option)
void SetProfileOption (EDayZProfilesOptions option, bool value)
void SetProfileOptionBool (EDayZProfilesOptions option, bool value)
void SetProfileOptionInt (EDayZProfilesOptions option, int value)
void SetProfileOptionFloat (EDayZProfilesOptions option, float value)
map< EDayZProfilesOptions, ref DayZProfilesOption > GetProfileOptionMap ()
bool IsStressTest ()
bool IsAimLogEnabled ()
void SetGameState (DayZGameState state)
DayZGameState GetGameState ()
void SetLoadState (DayZLoadState state)
DayZLoadState GetLoadState ()
Backlit GetBacklit ()
override bool IsInventoryOpen ()
void EarlyAccessDialog (UIScriptedMenu parent)
override UIScriptedMenu CreateScriptedMenu (int id)
create custom main menu part (submenu)
void ReloadMission ()
void CancelLoginQueue ()
void CancelLoginTimeCountdown ()
private void ClearConnectivityStates ()
override void OnEvent (EventType eventTypeId, Param params)
protected void SetConnectivityStatState (EConnectivityStatType type, EConnectivityStatLevel level)
protected bool OnConnectivityStatChange (EConnectivityStatType type, EConnectivityStatLevel newLevel, EConnectivityStatLevel oldLevel)
void AddVoiceNotification (VONStopSpeakingEventParams vonStartParams)
void RemoveVoiceNotification (VONStopSpeakingEventParams vonStopParams)
void UpdateLoginQueue (float timeslice)
void OnLoginTimeEvent (int loginTime)
void LoginTimeCountdown ()
void OnRespawnEvent (int time)
void OnPreloadEvent (vector pos)
void StoreLoginDataPrepare ()
void EnterLoginQueue (UIMenuPanel parent)
void EnterLoginTime (UIMenuPanel parent)
void OnMPConnectionLostEvent (int duration)
void LoadProgressUpdate (int progressState, float progress, string title)
override void OnAfterCreate ()
override void OnActivateMessage ()
override void OnDeactivateMessage ()
override bool OnInitialize ()
void InitNotifications ()
string GetDatabaseID ()
void SetDatabaseID (string id)
void CreateTitleScreen ()
void DeleteTitleScreen ()
bool ShouldShowControllerDisconnect ()
void UpdateInputDeviceDisconnectWarning ()
void JoinLaunch ()
void ConnectLaunch ()
void PartyLaunch ()
void MainMenuLaunch ()
void MissionLaunch ()
void SelectUser (int gamepad=-1)
void SetPreviousGamepad (int gamepad)
int GetPreviousGamepad ()
void GamepadCheck ()
void SelectGamepad ()
void TryConnect ()
bool GetLastVisitedServer (out string ip, out int port)
void AddVisitedServer (string ip, int port)
bool IsVisited (string ip, int port)
void RefreshCurrentServerInfo ()
void Connect ()
void DisconnectSessionScript (bool displayJoinError=false)
void DisconnectSessionEx (DisconnectSessionFlags flags)
void ConnectFromServerBrowser (string ip, int port, string password="")
void ConnectFromJoin (string ip, int port)
void ConnectFromCLI ()
bool IsLeftCtrlDown ()
override void OnKeyPress (int key)
override void OnKeyRelease (int key)
override void OnMouseButtonPress (int button)
override void OnMouseButtonRelease (int button)
override void OnDeviceReset ()
float GetDeltaT ()
override void OnUpdate (bool doSim, float timeslice)
override void OnPostUpdate (bool doSim, float timeslice)
override void OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx)
void DelayedMidAirDetonation (float x, float y, float z)
void CheckDialogs ()
void SetConnecting (bool value)
Returns true when connecting to server.
bool IsConnecting ()
bool IsLoading ()
void SetKeyboardHandle (UIScriptedMenu handler)
void LoadingShow ()
void LoadingHide (bool force=false)
override string CreateDefaultPlayer ()
override string CreateRandomPlayer ()
override TStringArray ListAvailableCharacters ()
void ExplosionEffectsEx (Object source, Object directHit, int componentIndex, float energyFactor, float explosionFactor, HitInfo hitInfo)
void ExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
void OnProjectileStopped (ProjectileStoppedInfo info)
void OnProjectileStoppedInTerrain (TerrainCollisionInfo info)
void OnProjectileStoppedInObject (ObjectCollisionInfo info)
void FirearmEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, bool isWater, bool deflected, string ammoType)
void CloseCombatEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, bool isWater, string ammoType)
void UpdateVoiceLevel (int level)
void InitCharacterMenuDataInfo (int menudata_count)
void SetPlayerGameName (string name)
string GetPlayerGameName ()
void SetNewCharacter (bool state)
bool IsNewCharacter ()
void SetUserFOV (float pFov)
float GetUserFOV ()
float GetFOVByZoomType (ECameraZoomType type)
void SetHudBrightness (float value)
float GetHUDBrightnessSetting ()
void SetEVValue (float value)
float GetCurrentEVValue ()
float GetPreviousEVValue ()
int GetCurrentDisplayLanguageIdx ()
bool IsWorldWetTempUpdateEnabled ()
bool IsFoodDecayEnabled ()
float GetFoodDecayModifier ()
array< int > GetConnectedInputDeviceList ()
void CreateGamepadDisconnectMenu ()
void DeleteGamepadDisconnectMenu ()
void CGame ()
private void ~CGame ()
proto native WorkspaceWidget GetWorkspace ()
proto native WorkspaceWidget GetLoadingWorkspace ()
void OnEvent (EventType eventTypeId, Param params)
Called when some system event occur.
void OnProcessLifetimeChanged (int plmtype)
void OnLicenseChanged ()
void OnAfterCreate ()
Called after creating of CGame instance.
void OnActivateMessage ()
Called when recieving focus (windows)
void OnDeactivateMessage ()
Called when loosing focus (windows)
bool OnInitialize ()
Called once before game update loop starts, ret value indicates if init was done in scripts, otherwise it is done in the engine.
void OnDeviceReset ()
Called when inputs is not possible (Steam overlay active or something), all internal script variables should be reset here!
void OnUpdate (bool doSim, float timeslice)
Called on World update.
void OnPostUpdate (bool doSim, float timeslice)
Called on World update after simulation of entities.
void OnKeyPress (int key)
Called when key is pressed.
void OnKeyRelease (int key)
Called when key is released.
void OnMouseButtonPress (int button)
Called when mouse button is pressed.
void OnMouseButtonRelease (int button)
Called when mouse button is released.
UIScriptedMenu CreateScriptedMenu (int id)
create custom main menu part (submenu)
UIScriptedWindow CreateScriptedWindow (int id)
create custom window part
void OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
proto native void RequestExit (int code)
Sets exit code and quits in the right moment.
proto native void RequestRestart (int code)
Sets exit code and restart in the right moment.
proto bool GetHostAddress (out string address, out int port)
Gets the server address. (from client)
proto owned string GetHostName ()
Gets the server name. (from client)
proto GetServersResultRow GetHostData ()
Gets the server data. (from client)
proto native int Connect (UIScriptedMenu parent, string IpAddress, int port, string password)
Connects to IsServer.
proto native int ConnectLastSession (UIScriptedMenu parent, int selectedCharacter=-1)
Connects to last success network session.
proto native void DisconnectSession ()
Disconnects from current multiplayer session.
proto native void DisconnectSessionForce ()
Forces disconnect from current multiplayer session even if not yet in the game.
proto native void GetProfileStringList (string name, out TStringArray values)
Gets array of strings from profile variable.
proto bool GetProfileString (string name, out string value)
Gets string from profile variable.
proto native void SetProfileStringList (string name, TStringArray values)
Sets array of strings to profile variable.
proto native void SetProfileString (string name, string value)
Sets string to profile variable.
proto native void SaveProfile ()
Saves profile on disk.
proto void GetPlayerName (out string name)
Gets current player name.
proto void GetPlayerNameShort (int maxLength, out string name)
Gets current player name. If length of player name is grater than maxLength, then it is omitted and append ellipsis.
proto native void SetPlayerName (string name)
Sets current player name.
proto native Entity CreatePlayer (PlayerIdentity identity, string name, vector pos, float radius, string spec)
Assign player entity to client (in multiplayer)
proto native void SelectPlayer (PlayerIdentity identity, Object player)
Selects player's controlled object.
proto void GetPlayerNetworkIDByIdentityID (int playerIdentityID, out int networkIdLowBits, out int networkIdHightBits)
returns player's network id from identity id in out parameters
proto native Object GetObjectByNetworkId (int networkIdLowBits, int networkIdHighBits)
Returns entity identified by network id.
proto native bool RegisterNetworkStaticObject (Object object)
Static objects cannot be replicated by default (there are too many objects on the map). Use this method when you want to replicate some scripted variables. Cannot be called in object's constructor, because networking is not initialized yet.
proto native void SelectSpectator (PlayerIdentity identity, string spectatorObjType, vector position)
Creates spectator object (mostly cameras)
proto native void UpdateSpectatorPosition (vector position)
Updates spectator position on server = position of network bubble.
proto native void SendLogoutTime (Object player, int time)
Inform client about logout time (creates logout screen on specified client)
proto native void DisconnectPlayer (PlayerIdentity identity, string uid="")
Destroy player info and disconnect.
proto native void AddToReconnectCache (PlayerIdentity identity)
Add player to reconnect cache to be able to rejoin character still existing in the world.
proto native void RemoveFromReconnectCache (string uid)
Remove player from reconnect cache.
proto native void ClearReconnectCache ()
Remove all player from reconnect cache.
proto native void StorageVersion (int iVersion)
Set actual storage version - for next save.
proto native int LoadVersion ()
Returns actual storage version - loading.
proto native int SaveVersion ()
Returns actual storage version - saving.
proto native float GetDayTime ()
Returns current daytime on server.
proto bool ConfigGetText (string path, out string value)
Get string value from config on path.
proto bool ConfigGetTextRaw (string path, out string value)
Get raw string value from config on path.
string ConfigGetTextOut (string path)
Get string value from config on path.
bool FormatRawConfigStringKeys (inout string value)
Changes localization key format to script-friendly format.
string GetModelName (string class_name)
Get name of the p3d file of the given class name.
proto native float ConfigGetFloat (string path)
Get float value from config on path.
proto native vector ConfigGetVector (string path)
Get vector value from config on path.
proto native int ConfigGetInt (string path)
Get int value from config on path.
proto native int ConfigGetType (string path)
Returns type of config value.
proto native void ConfigGetTextArray (string path, out TStringArray values)
Get array of strings from config on path.
proto native void ConfigGetTextArrayRaw (string path, out TStringArray values)
Get array of raw strings from config on path.
proto native void ConfigGetFloatArray (string path, out TFloatArray values)
Get array of floats from config on path.
proto native void ConfigGetIntArray (string path, out TIntArray values)
Get array of integers from config on path.
proto bool ConfigGetChildName (string path, int index, out string name)
Get name of subclass in config class on path.
proto bool ConfigGetBaseName (string path, out string base_name)
Get name of base class of config class on path.
proto native int ConfigGetChildrenCount (string path)
Get count of subclasses in config class on path.
proto native bool ConfigIsExisting (string path)
proto native void ConfigGetFullPath (string path, out TStringArray full_path)
proto native void ConfigGetObjectFullPath (Object obj, out TStringArray full_path)
proto native void GetModInfos (notnull out array< ref ModInfo > modArray)
proto native bool GetModToBeReported ()
string ConfigPathToString (TStringArray array_path)
Converts array of strings into single string.
proto bool CommandlineGetParam (string name, out string value)
Get command line parameter value.
proto native void CopyToClipboard (string text)
proto void CopyFromClipboard (out string text)
proto native void BeginOptionsVideo ()
proto native void EndOptionsVideo ()
proto native void AdminLog (string text)
proto native bool PreloadObject (string type, float distance)
Preload objects with certain type in certain distance from camera.
proto native Object CreateStaticObjectUsingP3D (string p3dFilename, vector position, vector orientation, float scale=1.0, bool createLocal=false)
proto native Object CreateObject (string type, vector pos, bool create_local=false, bool init_ai=false, bool create_physics=true)
Creates object of certain type.
proto native SoundOnVehicle CreateSoundOnObject (Object source, string sound_name, float distance, bool looped, bool create_local=false)
proto native SoundWaveOnVehicle CreateSoundWaveOnObject (Object source, SoundObject soundObject, AbstractWave soundWave)
proto native Object CreateObjectEx (string type, vector pos, int iFlags, int iRotation=RF_DEFAULT)
Creates object of certain type.
proto native void ObjectDelete (Object obj)
proto native void ObjectDeleteOnClient (Object obj)
proto native void RemoteObjectDelete (Object obj)
proto native void RemoteObjectTreeDelete (Object obj)
RemoteObjectDelete - deletes only remote object (unregisters from network). do not use if not sure what you do.
proto native void RemoteObjectCreate (Object obj)
RemoteObjectDelete - deletes only remote object tree (unregisters from network). do not use if not sure what you do.
proto native void RemoteObjectTreeCreate (Object obj)
RemoteObjectCreate - postponed registration of network object (and creation of remote object). do not use if not sure what you do.
proto native int ObjectRelease (Object obj)
RemoteObjectTreeCreate - postponed registration of network object tree (and creation of remote objects). do not use if not sure what you do.
proto void ObjectGetType (Object obj, out string type)
proto void ObjectGetDisplayName (Object obj, out string name)
proto native vector ObjectGetSelectionPosition (Object obj, string name)
proto native vector ObjectGetSelectionPositionLS (Object obj, string name)
proto native vector ObjectGetSelectionPositionMS (Object obj, string name)
proto native vector ObjectGetSelectionPositionWS (Object obj, string name)
proto native vector ObjectModelToWorld (Object obj, vector modelPos)
proto native vector ObjectWorldToModel (Object obj, vector worldPos)
proto native bool IsObjectAccesible (EntityAI item, Man player)
returns true if player can access item's cargo/attachments (check only distance)
proto native Input GetInput ()
proto native vector GetCurrentCameraPosition ()
proto native vector GetCurrentCameraDirection ()
proto native AbstractSoundScene GetSoundScene ()
proto native NoiseSystem GetNoiseSystem ()
proto native bool AddInventoryJuncture (Man player, notnull EntityAI item, InventoryLocation dst, bool test_dst_occupancy, int timeout_ms)
bool AddInventoryJunctureEx (Man player, notnull EntityAI item, InventoryLocation dst, bool test_dst_occupancy, int timeout_ms)
proto native bool HasInventoryJunctureItem (notnull EntityAI item)
proto native bool HasInventoryJunctureDestination (Man player, notnull InventoryLocation dst)
proto native bool AddActionJuncture (Man player, notnull EntityAI item, int timeout_ms)
proto native bool ExtendActionJuncture (Man player, notnull EntityAI item, int timeout_ms)
proto native bool ClearJuncture (Man player, notnull EntityAI item)
bool ClearJunctureEx (Man player, notnull EntityAI item)
proto native bool ExecuteEnforceScript (string expression, string mainFnName)
Delevoper only: Executes Enforce Script expression, if there is an error, is printed into the script console.
proto native void DumpInstances (bool csvFormatting)
Delevoper only: Dump all script allocations.
proto native bool ScriptTest ()
proto native void GetDiagModeNames (out TStringArray diag_names)
Get list of all debug modes.
proto native void SetDiagModeEnable (int diag_mode, bool enabled)
Set specific debug mode.
proto native bool GetDiagModeEnable (int diag_mode)
Gets state of specific debug mode.
proto native void GetDiagDrawModeNames (out TStringArray diag_names)
Get list of all debug draw modes.
proto native void SetDiagDrawMode (int diag_draw_mode)
Set debug draw mode.
proto native int GetDiagDrawMode ()
Gets current debug draw mode.
proto native bool IsPhysicsExtrapolationEnabled ()
If physics extrapolation is enabled, always true on retail release builds.
proto native float GetFps ()
Returns average FPS of last 16 frames.
proto native float GetTickTime ()
Returns current time from start of the game.
proto void GetInventoryItemSize (InventoryItem item, out int width, out int height)
proto native void GetObjectsAtPosition (vector pos, float radius, out array< Object > objects, out array< CargoBase > proxyCargos)
Returns list of all objects in circle "radius" around position "pos".
proto native void GetObjectsAtPosition3D (vector pos, float radius, out array< Object > objects, out array< CargoBase > proxyCargos)
Returns list of all objects in sphere "radius" around position "pos".
proto native World GetWorld ()
proto void GetWorldName (out string world_name)
string GetWorldName ()
proto native bool VerifyWorldOwnership (string sWorldName)
proto native bool GoBuyWorldDLC (string sWorldName)
proto void FormatString (string format, string params[], out string output)
proto void GetVersion (out string version)
proto native UIManager GetUIManager ()
proto native DayZPlayer GetPlayer ()
proto native void GetPlayers (out array< Man > players)
DayZPlayer GetPlayerByIndex (int index=0)
proto native void StoreLoginData (ParamsWriteContext ctx)
Stores login userdata as parameters which are sent to server
proto native vector GetPointerDirection ()
Returns the direction where the mouse points, from the camera view.
proto native vector GetWorldDirectionFromScreen (vector world_pos)
Transforms position in world to position in screen in pixels as x, y component of vector, z parameter represents distance between camera and world_pos.
proto native vector GetScreenPos (vector world_pos)
Transforms position in world to position in screen in pixels as x, y component of vector, z parameter represents distance between camera and world_pos.
proto native vector GetScreenPosRelative (vector world_pos)
Transforms position in world to position in screen in percentage (0.0 - 1.0) as x, y component of vector, z parameter represents distance between camera and world_pos.
proto native MenuData GetMenuData ()
Return singleton of MenuData class - at main menu contains characters played with current profile.
proto native void RPC (Object target, int rpcType, notnull array< ref Param > params, bool guaranteed, PlayerIdentity recipient=null)
Initiate remote procedure call. When called on client, RPC is evaluated on server; When called on server, RPC is executed on all clients.
void RPCSingleParam (Object target, int rpc_type, Param param, bool guaranteed, PlayerIdentity recipient=null)
see CGame.RPC
proto native void RPCSelf (Object target, int rpcType, notnull array< ref Param > params)
Not actually an RPC, as it will send it only to yourself.
void RPCSelfSingleParam (Object target, int rpcType, Param param)
proto native void ProfilerStart (string name)
Use for profiling code from start to stop, they must match have same name, look wiki pages for more info: https://confluence.bistudio.com/display/EN/Profiler.
proto native void ProfilerStop (string name)
Use for profiling code from start to stop, they must match have same name, look wiki pages for more info: https://confluence.bistudio.com/display/EN/Profiler.
proto native void Chat (string text, string colorClass)
Prints text into game chat.
proto native void ChatMP (Man recipient, string text, string colorClass)
proto native void ChatPlayer (string text)
proto native void MutePlayer (string muteUID, string playerUID, bool mute)
Mutes voice of source player to target player.
proto native void MuteAllPlayers (string listenerId, bool mute)
Mute all players for listenerId.
proto native void EnableVoN (Object player, bool enable)
Enable/disable VoN for target player.
proto native void SetVoiceEffect (Object player, int effect, bool enable)
Enable/disable VoN effect (only on server)
proto native void SetVoiceLevel (int level)
Set voice level of VoN (only on client) (VoiceLevelWhisper = 0, VoiceLevelNormal = 1, VoiceLevelShout = 2)
proto native int GetVoiceLevel (Object player=null)
Get voice level of VoN (on both client and server) (VoiceLevelWhisper = 0, VoiceLevelNormal = 1, VoiceLevelShout = 2)
proto native void EnableMicCapture (bool enable)
Enable microphone to locally capture audio from user. Audio heard does NOT automatically get transmitted over network.
proto native bool IsMicCapturing ()
Returns whether mic is currently capturing audio from user.
proto native bool IsInPartyChat ()
Returns whether user is currently in a voice party (currently only supported on xbox)
proto native Mission GetMission ()
proto native void SetMission (Mission mission)
proto native void StartRandomCutscene (string world)
Starts intro.
proto native void PlayMission (string path)
Starts mission (equivalent for SQF playMission). You MUST use double slash \.
proto protected native void CreateMission (string path)
Create only enforce script mission, used for mission script reloading.
proto native void RestartMission ()
proto native void AbortMission ()
Returns to main menu, leave world empty for using last mission world.
proto native void RespawnPlayer ()
proto native bool CanRespawnPlayer ()
proto native void SetMainMenuWorld (string world)
proto native owned string GetMainMenuWorld ()
proto native void LogoutRequestTime ()
Logout methods.
proto native void LogoutRequestCancel ()
proto native bool IsMultiplayer ()
proto native bool IsClient ()
proto native bool IsServer ()
proto native bool IsDedicatedServer ()
Robust check which is preferred than the above, as it is valid much sooner.
proto native int ServerConfigGetInt (string name)
Server config parsing. Returns 0 if not found.
proto native bool IsDebug ()
void SetDebugMonitorEnabled (int value)
bool IsDebugMonitor ()
proto native void GetPlayerIndentities (out array< PlayerIdentity > identities)
proto native float SurfaceY (float x, float z)
proto native float SurfaceRoadY (float x, float z)
proto void SurfaceGetType (float x, float z, out string type)
proto void SurfaceGetType3D (float x, float y, float z, out string type)
proto void SurfaceUnderObject (notnull Object object, out string type, out int liquidType)
proto void SurfaceUnderObjectEx (notnull Object object, out string type, out string impact, out int liquidType)
proto void SurfaceUnderObjectByBone (notnull Object object, int boneType, out string type, out int liquidType)
proto native float SurfaceGetNoiseMultiplier (Object directHit, vector pos, int componentIndex)
proto native vector SurfaceGetNormal (float x, float z)
proto native float SurfaceGetSeaLevel ()
proto native bool SurfaceIsSea (float x, float z)
proto native bool SurfaceIsPond (float x, float z)
proto native float GetWaterDepth (vector posWS)
proto native void UpdatePathgraphRegion (vector regionMin, vector regionMax)
float GetHighestSurfaceYDifference (array< vector > positions)
Returns the largest height difference between the given positions.
vector GetSurfaceOrientation (float x, float z)
Returns tilt of the ground on the given position in degrees, so you can use this value to rotate any item according to terrain.
bool IsSurfaceDigable (string surface)
Checks if the surface is digable.
bool IsSurfaceFertile (string surface)
Checks if the surface is fertile.
void UpdatePathgraphRegionByObject (Object object)
proto native bool IsBoxColliding (vector center, vector orientation, vector edgeLength, array< Object > excludeObjects, array< Object > collidedObjects=NULL)
Finds all objects that are in choosen oriented bounding box (OBB)
proto native bool IsBoxCollidingGeometry (vector center, vector orientation, vector edgeLength, int iPrimaryType, int iSecondaryType, array< Object > excludeObjects, array< Object > collidedObjects=NULL)
Finds all objects with geometry iType that are in choosen oriented bounding box (OBB)
proto native bool IsBoxCollidingGeometryProxy (notnull BoxCollidingParams params, array< Object > excludeObjects, array< ref BoxCollidingResult > collidedObjects=NULL)
proto native Weather GetWeather ()
Returns weather controller object.
proto native void SetEVUser (float value)
Sets custom camera camera EV. range: -50.0..50.0? //TODO.
proto native void OverrideDOF (bool enable, float focusDistance, float focusLength, float focusLengthNear, float blur, float focusDepthOffset)
proto native void AddPPMask (float ndcX, float ndcY, float ndcRadius, float ndcBlur)
proto native void ResetPPMask ()
proto native void OverrideInventoryLights (vector diffuse, vector ambient, vector ground, vector dir)
proto native void NightVissionLightParams (float lightIntensityMul, float noiseIntensity)
proto native void OpenURL (string url)
proto native void InitDamageEffects (Object effect)
Initialization of damage effects.
proto native EntityAI GetEntityByPersitentID (int b1, int b2, int b3, int b4)
bool IsKindOf (string cfg_class_name, string cfg_parent_name)
Returns is class name inherited from parent class name.
bool ObjectIsKindOf (Object object, string cfg_parent_name)
Returns is object inherited from parent class name.
int ConfigFindClassIndex (string config_path, string searched_member)
proto int GetTime ()
returns mission time in milliseconds
ScriptCallQueue GetCallQueue (int call_category)
ScriptInvoker GetUpdateQueue (int call_category)
ScriptInvoker GetPostUpdateQueue (int call_category)
TimerQueue GetTimerQueue (int call_category)
DragQueue GetDragQueue ()
string CreateDefaultPlayer ()
returns class name of first valid survivor (TODO address confusing naming?)
string CreateRandomPlayer ()
returns class name of random survivor (TODO address confusing naming?)
TStringArray ListAvailableCharacters ()
outputs array of all valid survivor class names
bool IsInventoryOpen ()
proto native BiosUserManager GetUserManager ()
proto native ContentDLC GetContentDLCService ()
Return DLC service (service for entitlement keys for unlock content)
bool IsMissionMainMenu ()
Returns true when current mission is Main Menu.
MenuDefaultCharacterData GetMenuDefaultCharacterData (bool fill_data=true)
AnalyticsManagerServer GetAnalyticsServer ()
AnalyticsManagerClient GetAnalyticsClient ()
Static Private Member Functions
static bool ReportModded ()
static float GetUserFOVFromConfig ()
static bool CheckAmmoCompability (EntityAI weaponInHand, EntityAI ammo)
static bool IsDigitalCopy ()
Private Attributes
const int MISSION_STATE_MAINMENU = 0
const int MISSION_STATE_GAME = 1
const int MISSION_STATE_FINNISH = 2
private const int STATS_COUNT = EConnectivityStatType.COUNT
private EConnectivityStatLevel m_ConnectivityStatsStates [STATS_COUNT]
private int m_MissionState
protected DayZGameState m_GameState
protected DayZLoadState m_LoadState
protected ref NotificationUI m_Notifications
protected bool m_FirstConnect = true
ref LoadingScreen m_loading
private ref LoginTimeBase m_LoginTimeScreen
private ref LoginQueueBase m_LoginQueue
private int m_LoginTime
private ref ConnectionLost m_connectionLost
private ref TimerQueue m_timerQueue [CALL_CATEGORY_COUNT]
private ref ScriptCallQueue m_callQueue [CALL_CATEGORY_COUNT]
private ref ScriptInvoker m_updateQueue [CALL_CATEGORY_COUNT]
private ref ScriptInvoker m_postUpdateQueue [CALL_CATEGORY_COUNT]
private ref DragQueue m_dragQueue
private ref DayZProfilesOptions m_DayZProfileOptions
private bool m_early_access_dialog_accepted
private UIScriptedMenu m_keyboard_handler
private ScriptModule m_mission_module
private string m_MissionPath
private string m_MissionFolderPath
private bool m_IsCtrlHolding
private bool m_IsWinHolding
private bool m_IsLeftAltHolding
private bool m_IsRightAltHolding
private bool m_IsWorldWetTempUpdateEnabled = true
private bool m_IsFoodDecayEnabled = true
private float m_FoodDecayModifier
private bool m_IsStressTest
private bool m_AimLoggingEnabled
int m_OriginalCharactersCount
private string m_PlayerName
private bool m_IsNewCharacter
private bool m_IsConnecting
private bool m_ConnectFromJoin
private bool m_ShouldShowControllerDisconnect
private int m_PreviousGamepad
private float m_UserFOV
float m_volume_sound
float m_volume_speechEX
float m_volume_music
float m_volume_VOIP
float m_volume_radio
float m_PreviousEVValue
float m_EVValue = 0
private ref Backlit m_Backlit
private ref array< string > m_CharClassNames = new array<string>()
private ref array< int > m_ConnectedInputDeviceList
private ref EffectSound m_CrashSound
private ref EffectSound m_ArtySound
private const int MIN_ARTY_SOUND_RANGE = 300
protected ref Widget m_IntroMenu
protected ref Widget m_GamepadDisconnectMenu
protected int m_PrevBlur
protected string m_DatabaseID
protected string m_ConnectAddress
protected int m_ConnectPort
protected string m_ConnectPassword
protected const int MAX_VISITED = 50
protected ref TStringArray m_Visited
float m_DeltaTime
const float ARROW_PIERCE_DEPTH = 0.05
int m_DebugMonitorEnabled
ScriptModule GameScript
private ref array< ref Param > m_ParamCache
ref AnalyticsManagerServer m_AnalyticsManagerServer
ref AnalyticsManagerClient m_AnalyticsManagerClient
ref MenuDefaultCharacterData m_CharacterData
Static Private Attributes
static bool m_ReportModded
static ref AmmoCamParams m_AmmoShakeParams = new AmmoCamParams()
static ref ScriptInvoker Event_OnRPC = new ScriptInvoker()
static ref NoiseParams m_NoiseParams = new NoiseParams()
Detailed Description
Definition at line 872 of file DayZGame.c.
Constructor & Destructor Documentation
~DayZGame()
private void ~DayZGame () inline private
Definition at line 1050 of file DayZGame.c.
References NotificationSystem::CleanupInstance(), PPEManagerStatic::DestroyManagerStatic(), g_Game, Print(), and SetDispatcher().
CGame()
void CGame () inline private
Definition at line 33 of file Game.c.
References GAME_STORAGE_VERSION, AmmoEffects::Init(), SEffectManager::Init(), LogManager::Init(), VONManager::Init(), IsDedicatedServer(), m_AnalyticsManagerClient, m_AnalyticsManagerServer, m_ParamCache, Math::Randomize(), and StorageVersion().
~CGame()
private void ~CGame () inline private
Definition at line 62 of file Game.c.
References AmmoEffects::Cleanup(), SEffectManager::Cleanup(), VONManager::CleanupInstance(), and ParticleManager().
Member Function Documentation
AbortMission()
proto native void AbortMission () private
Returns to main menu, leave world empty for using last mission world.
Referenced by OnEvent().
AddActionJuncture()
proto native bool AddActionJuncture (Man player, notnull EntityAI item, int timeout_ms) private
Referenced by OnStartServer().
AddInventoryJuncture()
proto native bool AddInventoryJuncture (Man player, notnull EntityAI item, InventoryLocation dst, bool test_dst_occupancy, int timeout_ms) private
Referenced by AddInventoryJunctureEx().
AddInventoryJunctureEx()
bool AddInventoryJunctureEx (Man player, notnull EntityAI item, InventoryLocation dst, bool test_dst_occupancy, int timeout_ms) inline private
Definition at line 714 of file Game.c.
References AddInventoryJuncture(), InventoryLocation::DumpToStringNullSafe(), Debug::InventoryReservationLog(), LogManager::IsInventoryReservationLogEnable(), and string::ToString().
Referenced by FirearmActionDetachMagazine::OnStartServer().
AddPPMask()
proto native void AddPPMask (float ndcX, float ndcY, float ndcRadius, float ndcBlur) private
Referenced by PPEffects::AddPPMask(), and PPERequester_GameplayBase::SetValuesOptics().
AddToReconnectCache()
proto native void AddToReconnectCache (PlayerIdentity identity) private
Add player to reconnect cache to be able to rejoin character still existing in the world.
Note
Works only on server and no database requests are sent
Parameters
identity of player
AddVisitedServer()
void AddVisitedServer (string ip, int port) inline private
Definition at line 2491 of file DayZGame.c.
References SaveProfile(), and SetProfileStringList().
Referenced by OnEvent().
AddVoiceNotification()
void AddVoiceNotification (VONStopSpeakingEventParams vonStartParams) inline private
Definition at line 1749 of file DayZGame.c.
AdminLog()
proto native void AdminLog (string text) private
Referenced by PluginBase::LogPrint().
BeginOptionsVideo()
proto native void BeginOptionsVideo () private
Referenced by ScriptedWidgetEventHandler::OptionsMenuVideo().
CancelLoginQueue()
void CancelLoginQueue () inline private
Definition at line 1349 of file DayZGame.c.
References m_LoginQueue.
Referenced by OnEvent(), and OnLoginTimeEvent().
CancelLoginTimeCountdown()
void CancelLoginTimeCountdown () inline private
Definition at line 1365 of file DayZGame.c.
References CALL_CATEGORY_SYSTEM, GetCallQueue(), m_LoginTimeScreen, and ScriptCallQueue::Remove().
Referenced by LoginTimeCountdown(), OnEvent(), and OnPreloadEvent().
CanRespawnPlayer()
proto native bool CanRespawnPlayer () private
Chat()
proto native void Chat (string text, string colorClass) private
Prints text into game chat.
Parameters
text to print
colorClass ??
usage :
GetGame().Chat("Item splitted", "colorAction");
Referenced by ManBase::Message().
ChatMP()
proto native void ChatMP (Man recipient, string text, string colorClass) private
Referenced by ManBase::Message().
ChatPlayer()
proto native void ChatPlayer (string text) private
Referenced by UIScriptedMenu::OnChange().
CheckAmmoCompability()
static bool CheckAmmoCompability (EntityAI weaponInHand, EntityAI ammo) inline static private
Definition at line 3549 of file DayZGame.c.
References ConfigGetTextArray(), and GetGame().
CheckDialogs()
void CheckDialogs () inline private
Definition at line 3158 of file DayZGame.c.
References GetMission(), GetUIManager(), mission, Mission::Pause(), and UIManager::ShowQueuedDialog().
ClearConnectivityStates()
private void ClearConnectivityStates () inline private
Definition at line 1383 of file DayZGame.c.
References STATS_COUNT.
Referenced by OnEvent().
ClearJuncture()
proto native bool ClearJuncture (Man player, notnull EntityAI item) private
Referenced by ClearJunctureEx(), HandStateBase::OnAbort(), ActionManagerServer::OnActionEnd(), FirearmActionDetachMagazine::OnEndServer(), HandStateBase::OnExit(), ActionDigGardenPlot::OnFinishProgressServer(), WeaponManager::OnInputUserDataProcess(), and WeaponManager::OnWeaponActionEnd().
ClearJunctureEx()
bool ClearJunctureEx (Man player, notnull EntityAI item) inline private
Definition at line 735 of file Game.c.
References ClearJuncture(), Debug::InventoryReservationLog(), and LogManager::IsInventoryReservationLogEnable().
Referenced by OnEndServer(), ActionDeployBase::OnFinishProgressServer(), and TryAcquireTwoInventoryJuncturesFromServer().
ClearReconnectCache()
proto native void ClearReconnectCache () private
Remove all player from reconnect cache.
Note
Works only on server
CloseCombatEffects()
void CloseCombatEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, bool isWater, string ammoType) inline private
Definition at line 3428 of file DayZGame.c.
References NoiseSystem::AddNoisePos(), ImpactMaterials::EvaluateImpactEffectEx(), GetNoiseSystem(), GetPlayer(), IsServer(), m_NoiseParams, Math::RandomFloat(), SurfaceGetNoiseMultiplier(), and Vector().
CommandlineGetParam()
proto bool CommandlineGetParam (string name, out string value) private
Get command line parameter value.
Parameters
name of parameter
value output
Returns
true when parameter exists, false otherwise
usage :
// you run e.g.: DayZInt.exe -scriptDebug=true
string value;
if (GetGame().CommandlineGetParam("scriptDebug", value) && value == "true")
{
  Print("Script debugging on!");
}
Referenced by DayZGame().
ConfigFindClassIndex()
int ConfigFindClassIndex (string config_path, string searched_member) inline private
Searches given config path (config_path) for the given member (searched_member) and returns its index. \nReturns -1 if not found.
usage:
int skinning_class_index = g_Game.ConfigFindClassIndex(cfgPath_animal, "Skinning");
Definition at line 1318 of file Game.c.
References ConfigGetChildName(), and ConfigGetChildrenCount().
ConfigGetBaseName()
proto bool ConfigGetBaseName (string path, out string base_name) private
Get name of base class of config class on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
name output
Returns
true on success, false if path or base is not exists
Referenced by PluginBase::GetConfigRecursive().
ConfigGetChildName()
proto bool ConfigGetChildName (string path, int index, out string name) private
Get name of subclass in config class on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
index of subclass in class
name output
Returns
true on success, false if path or child is not found
Referenced by BaseBuildingBase::CanReceiveAttachment(), UIScriptedMenu::ChangeFilter(), ConfigFindClassIndex(), PluginBase::ContainsFirstClass(), AttachmentsOutOfReach::CreateAttachmentPosition(), DayZGame(), DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTableImpl(), DestroyMaterialsServer(), DropNonUsableMaterialsServer(), UIScriptedMenu::DumpParam(), ComponentEnergyManager::Event_OnAwake(), PluginRecipesManagerBase::GenerateRecipeCache(), AttachmentCategoriesContainer::GetAttachmentCategory(), AttachmentCategoriesSlotsContainer::GetAttachmentCategory(), ConstructionActionData::GetAttachmentsFromSelection(), ConstructionActionData::GetAttachmentSlotFromSelection(), PluginBase::GetConfig(), PluginBase::GetConfigRecursive(), Debug::GetFiltredConfigClasses(), Liquid::GetLiquidConfigProperty(), DayZPlayer::HandleView(), HasMaterials(), ItemBase::HideAllAnimationsAndProxyPhysics(), SoundSetMap::Init(), Liquid::InitAllLiquids(), InitData(), DayZCreatureAIType::LoadAnimDamageEvents(), DayZCreatureAIType::LoadAnimSoundEvents(), DayZCreatureAIType::LoadAnimSoundVoiceEvents(), DayZCreatureAIType::LoadAnimStepEvents(), PluginBase::LoadFromCfg(), LoadFromCfg(), ModLoader::LoadMods(), InventoryItem::LoadParticleConfigOnFire(), InventoryItem::LoadParticleConfigOnOverheating(), InventoryItemType::LoadSoundEvents(), LoadSoundWeaponEvent(), SoundLookupTable::LoadTable(), LoadVegetationSounds(), MaterialIsRuined(), ActionUnpackBox::OnFinishProgressServer(), SetLockOnAttachedMaterials(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), TakeMaterialsServer(), UpdateConstructionParts(), and Hologram::UpdateSelections().
ConfigGetChildrenCount()
proto native int ConfigGetChildrenCount (string path) private
Get count of subclasses in config class on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
index of parameter in class
name output
Returns
true on success, false if path or child is not found
Referenced by BaseBuildingBase::CanReceiveAttachment(), UIScriptedMenu::ChangeFilter(), ConfigFindClassIndex(), PluginBase::ContainsFirstClass(), AttachmentsOutOfReach::CreateAttachmentPosition(), DayZGame(), DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTableImpl(), DestroyMaterialsServer(), DropNonUsableMaterialsServer(), UIScriptedMenu::DumpParam(), ComponentEnergyManager::Event_OnAwake(), PluginRecipesManagerBase::GenerateRecipeCache(), AttachmentCategoriesContainer::GetAttachmentCategoriesCount(), ConstructionActionData::GetAttachmentsFromSelection(), ConstructionActionData::GetAttachmentSlotFromSelection(), PluginBase::GetConfig(), PluginBase::GetConfigRecursive(), Debug::GetFiltredConfigClasses(), DayZPlayer::HandleView(), HasMaterials(), ItemBase::HideAllAnimationsAndProxyPhysics(), SoundSetMap::Init(), InitData(), DayZCreatureAIType::LoadAnimDamageEvents(), DayZCreatureAIType::LoadAnimSoundEvents(), DayZCreatureAIType::LoadAnimSoundVoiceEvents(), DayZCreatureAIType::LoadAnimStepEvents(), PluginBase::LoadFromCfg(), LoadFromCfg(), ModLoader::LoadMods(), InventoryItem::LoadParticleConfigOnFire(), InventoryItem::LoadParticleConfigOnOverheating(), InventoryItemType::LoadSoundEvents(), LoadSoundWeaponEvent(), SoundLookupTable::LoadTable(), LoadVegetationSounds(), MaterialIsRuined(), ActionUnpackBox::OnFinishProgressServer(), SetLockOnAttachedMaterials(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), TakeMaterialsServer(), and UpdateConstructionParts().
ConfigGetFloat()
proto native float ConfigGetFloat (string path) private
Get float value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
Returns
value
Referenced by Ammo_40mm_Smoke_ColorBase::Activate(), ItemBase::BatteryCharger(), CalcAndSetTotalEnergy(), ActionSkinning::CreateOrgan(), DestroyMaterialsServer(), EffBulletImpactBase::EvaluateEffect(), ComponentEnergyManager::Event_OnAwake(), ItemBase::Fertilize(), FirearmEffects(), Ammunition_Base::GetAmmoWeightByBulletType(), InventoryItem::GetDryingIncrement(), ItemBase::GetEnergyNeededToCharge(), ItemBase::GetFoodEnergy(), ItemBase::GetFoodNutritionalIndex(), ItemBase::GetFoodTotalVolume(), ItemBase::GetFoodToxicity(), ItemBase::GetFoodWater(), Surface::GetParamFloat(), InventoryItem::GetProtectionLevel(), InventoryItem::GetSoakingIncrement(), ItemBase::GetTimeNeededToCharge(), GetTypeMaxGlobalHealth(), HasMaterials(), Hologram::Hologram(), FlammableBase::Init(), InventoryItemSuper::InitDOFAvailability(), InventoryItemSuper::InitOpticsPP(), AmmoCamParams::Load(), InventoryItem::LoadParticleConfigOnOverheating(), MaterialIsRuined(), BarbedWireTrigger::OnEnter(), Grenade_Base::OnExplosionEffects(), ActionSkinning::OnFinishProgressServer(), ItemBase::OnInitEnergy(), OrderedPositionNumbersFromGridCoords(), BleedingSourcesManagerBase::ProcessHit(), ActionRepairTent::RepairDamageTransfer(), ComponentEnergyManager::ResetEnergyUsage(), Ammunition_Base::SetFromProjectile(), SetLockOnAttachedMaterials(), CAContinuousFertilizeGardenSlot::Setup(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), TakeMaterialsServer(), and WeaponParticlesBase::WeaponParticlesBase().
ConfigGetFloatArray()
proto native void ConfigGetFloatArray (string path, out TFloatArray values) private
Get array of floats from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output
Referenced by ActionSkinning::CreateOrgan(), GetHealthLevelForAmmo(), Weapon::InitDOFProperties(), InventoryItemSuper::InitOpticsDOFProperties(), InventoryItemSuper::InitOpticsPP(), Weapon::InitReliability(), ActionSkinning::OnFinishProgressServer(), and WeaponParticlesBase::WeaponParticlesBase().
ConfigGetFullPath()
proto native void ConfigGetFullPath (string path, out TStringArray full_path) private
Referenced by PluginRecipesManagerBase::GenerateRecipeCache(), PluginBase::GetBaseClassPath(), PluginBase::GetBaseClassPathRecursive(), PluginBase::GetConfigRecursive(), and IsKindOf().
ConfigGetInt()
proto native int ConfigGetInt (string path) private
Get int value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
Returns
value
Referenced by CanUseToolToBuildPart(), CanUseToolToDismantlePart(), UIScriptedMenu::ChangeFilter(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), DayZGame(), DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), DestroyMaterialsServer(), ManBase::EEHitBy(), Inventory_Base::EmptySeedPack(), DayZInfected::EvaluateDamageHitAnimation(), DayZPlayer::EvaluateDamageHitAnimation(), DayZInfected::EvaluateDeathAnimation(), DayZPlayer::EvaluateDeathAnimation(), PluginRecipesManagerBase::GenerateRecipeCache(), Debug::GetFiltredConfigClasses(), ItemBase::GetFoodAgents(), ItemBase::GetFoodDigestibility(), Liquid::GetLiquidConfigProperty(), GetMaterialType(), AttachmentCategoriesContainer::GetViewIndex(), Hologram::Hologram(), Liquid::InitAllLiquids(), InitData(), IsSurfaceDigable(), IsSurfaceFertile(), MaterialIsRuined(), UIScriptedMenu::OnClick(), ActionUnpackBox::OnFinishProgressServer(), ItemBase::PlantBase(), ReplaceItemWithNewLambdaBase::PrepareLocations(), SetLockOnAttachedMaterials(), ItemBase::SetSlotTextureFertilized(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), TakeMaterialsServer(), UpdateConstructionParts(), and WeaponParticlesBase::WeaponParticlesBase().
ConfigGetIntArray()
proto native void ConfigGetIntArray (string path, out TIntArray values) private
Get array of integers from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output
Referenced by ComponentEnergyManager::Event_OnAwake(), and LoadVegetationSounds().
ConfigGetObjectFullPath()
proto native void ConfigGetObjectFullPath (Object obj, out TStringArray full_path) private
Referenced by ObjectIsKindOf().
ConfigGetText()
proto bool ConfigGetText (string path, out string value) private
Get string value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output
Returns
true on success
Referenced by ConfigGetTextOut(), AttachmentsOutOfReach::CreateAttachmentPosition(), DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), DestroyMaterialsServer(), DropNonUsableMaterialsServer(), UIScriptedMenu::DumpParam(), Inventory_Base::EmptySeedPack(), ComponentEnergyManager::Event_OnAwake(), AmmoEffects::GetAmmoEffectTypename(), AmmoEffects::GetAmmoParticleID(), Ammunition_Base::GetAmmoWeightByBulletType(), ConstructionActionData::GetAttachmentsFromSelection(), ConstructionActionData::GetAttachmentSlotFromSelection(), AttachmentCategoriesContainer::GetIconName(), AttachmentCategoriesSlotsContainer::GetIconName(), Liquid::GetLiquidConfigProperty(), GetModelName(), PluginBase::GetPlantType(), HasMaterials(), AttachmentCategoriesRow::Init(), InventoryItemSuper::Init2DPreloadType(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), InventoryItemSuper::InitMapState(), InventoryItemSuper::InitReddotData(), ModStructure::LoadData(), PluginBase::LoadFromCfg(), LoadFromCfg(), SoundLookupTable::LoadTable(), LoadVegetationSounds(), MaterialIsRuined(), ActionEmptyMagazine::OnExecuteServer(), OnProjectileStopped(), OnProjectileStoppedInObject(), OnProjectileStoppedInTerrain(), ItemBase::PlantBase(), PlayerContainer::PlayerContainer(), RegisterAttacks(), SetDisplayNameText(), SetLockOnAttachedMaterials(), PlayerContainer::SetPlayer(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), TakeMaterialsServer(), and WeaponParticlesBase::WeaponParticlesBase().
ConfigGetTextArray()
proto native void ConfigGetTextArray (string path, out TStringArray values) private
Get array of strings from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output
usage :
TStringArray characterAnimations = new TStringArray;
GetGame().ConfigGetTextArray("CfgMovesMaleSdr2 States menu_idleUnarmed0 variantsPlayer", characterAnimations);
Referenced by CheckAmmoCompability(), AttachmentsOutOfReach::CreateAttachmentPosition(), DropNonUsableMaterialsServer(), ConstructionActionData::GetAttachmentsFromSelection(), ConstructionActionData::GetAttachmentSlotFromSelection(), ItemBase::GetAttachmentSlots(), GetCollisionBoxData(), GetComponentNamesFromDamageZone(), GetConfigArrayCountFromSlotID(), SceneObject::GetConfigAttachments(), GetConfigAttachmentTypes(), PluginBase::GetConfigRecursive(), GetDamageZoneMap(), HiddenSelectionsData::GetHiddenSelectionsConfig(), HiddenSelectionsData::GetHiddenSelectionsMaterialsConfig(), HiddenSelectionsData::GetHiddenSelectionsTexturesConfig(), Attachments::GetItemSlots(), GetRequiredParts(), DayZPlayer::HandleView(), HasConflictPart(), HasRequiredPart(), HiddenSelectionsData::HiddenSelectionsData(), AttachmentCategoriesRow::Init(), ZombieContainer::InitGhostSlots(), InventoryItem::KindOf(), LoadFromCfg(), LoadPlayerAttachmentIndexes(), SoundLookupTable::LoadTable(), LockOvenAttachments(), ActionSkinning::OnFinishProgressServer(), PlayerContainer::PlayerContainer(), ActionRepairTent::RepairDamageTransfer(), BetaSound::SaySound(), and PlayerContainer::SetPlayer().
ConfigGetTextArrayRaw()
proto native void ConfigGetTextArrayRaw (string path, out TStringArray values) private
Get array of raw strings from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output in raw format (localization keys '$STR_' are not translated)
usage :
TStringArray characterAnimations = new TStringArray;
GetGame().ConfigGetTextArrayRaw("CfgMovesMaleSdr2 States menu_idleUnarmed0 variantsPlayer", characterAnimations);
Note
use 'FormatRawConfigStringKeys' method to change localization keys to script-friendly
ConfigGetTextOut()
string ConfigGetTextOut (string path) inline private
Get string value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
Returns
value output string
Definition at line 440 of file Game.c.
References ConfigGetText(), and path.
Referenced by GetItemDisplayName(), Hologram::Hologram(), Ammo_40mm_Smoke_ColorBase::OnVariablesSynchronized(), and Hologram::RefreshVisual().
ConfigGetTextRaw()
proto bool ConfigGetTextRaw (string path, out string value) private
Get raw string value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
value output in raw format (localization keys '$STR_' are not translated)
Returns
true on success
Note
use 'FormatRawConfigStringKeys' method to change localization keys to script-friendly
Referenced by UpdateConstructionParts().
ConfigGetType()
proto native int ConfigGetType (string path) private
Returns type of config value.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
Returns
one of constants CT_INT, CT_FLOAT, CT_STRING, CT_ARRAY, CT_CLASS, CT_OTHER
Referenced by PluginBase::ContainsFirstClass(), PluginBase::GetConfigRecursive(), and InventoryItem::LoadParticleConfigOnOverheating().
ConfigGetVector()
proto native vector ConfigGetVector (string path) private
Get vector value from config on path.
Parameters
path of value, classes are delimited by empty space. You can specify config file by using "configFile" or "missionConfigFile" as a first class name.
Returns
value
Referenced by Hologram::Hologram(), UIScriptedMenu::Init(), and WeaponParticlesBase::WeaponParticlesBase().
ConfigIsExisting()
proto native bool ConfigIsExisting (string path) private
Referenced by SlotsIcon::CheckHasItemSize(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), InventoryItem::HasFoodStage(), InitData(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), and ReplaceItemWithNewLambdaBase::PrepareLocations().
ConfigPathToString()
string ConfigPathToString (TStringArray array_path) inline private
Converts array of strings into single string.
Parameters
Array of strings like {"All", "AllVehicles", "Land"}
Returns
Converts given array into something lile "All AllVehicles Land".
???
Definition at line 603 of file Game.c.
Connect() [1/2]
void Connect () inline private
Definition at line 2537 of file DayZGame.c.
References Connect(), DeleteTitleScreen(), DisconnectSessionScript(), GetHostAddress(), GetUIManager(), and SetConnecting().
Referenced by Connect(), ConnectFromCLI(), ConnectFromJoin(), and TryConnect().
Connect() [2/2]
proto native int Connect (UIScriptedMenu parent, string IpAddress, int port, string password) private
Connects to IsServer.
Parameters
IpAddress of the server
port of the server set to 0 for default port
password of the server
Returns
0 on success, error code from ErrorModuleHandler on not success
ConnectFromCLI()
void ConnectFromCLI () inline private
Definition at line 2641 of file DayZGame.c.
References Connect(), GetCLIParam(), and string::ToInt().
Referenced by ConnectLaunch(), and TryConnect().
ConnectFromJoin()
void ConnectFromJoin (string ip, int port) inline private
Definition at line 2633 of file DayZGame.c.
References Connect().
ConnectFromServerBrowser()
void ConnectFromServerBrowser (string ip, int port, string password = "") inline private
Definition at line 2624 of file DayZGame.c.
References OnlineServices::LoadMPPrivilege().
ConnectLastSession()
proto native int ConnectLastSession (UIScriptedMenu parent, int selectedCharacter = -1) private
Connects to last success network session.
Returns
0 on success, error code from ErrorModuleHandler on not success
ConnectLaunch()
void ConnectLaunch () inline private
Definition at line 2150 of file DayZGame.c.
References ConnectFromCLI(), CreateTitleScreen(), GamepadCheck(), BiosUserManager::GetTitleInitiator(), GetUserManager(), BiosUserManager::SelectUserEx(), SetGameState(), and SetLoadState().
Referenced by OnInitialize().
CopyFromClipboard()
proto void CopyFromClipboard (out string text) private
Referenced by OnClick(), PluginBase::SpawnFromClipboard(), and HudDebugWinBase::Update().
CopyToClipboard()
proto native void CopyToClipboard (string text) private
Referenced by UIPopupScript::AddItemToClipboard(), UIScriptedMenu::AddItemToClipboard(), UIScriptedMenu::OnClick(), and OnClick().
CreateDefaultPlayer() [1/2]
override string CreateDefaultPlayer () inline private
Definition at line 3221 of file DayZGame.c.
CreateDefaultPlayer() [2/2]
string CreateDefaultPlayer () inline private
returns class name of first valid survivor (TODO address confusing naming?)
Definition at line 1369 of file Game.c.
CreateGamepadDisconnectMenu()
void CreateGamepadDisconnectMenu () private
CreateMission()
proto protected native void CreateMission (string path) private
Create only enforce script mission, used for mission script reloading.
Referenced by ReloadMission().
CreateObject()
proto native Object CreateObject (string type, vector pos, bool create_local = false, bool init_ai = false, bool create_physics = true) private
Creates object of certain type.
Parameters
type of objects to create
pos position where to create object
create_local if True, object is not spawned on clients only on server
init_ai if creating object is LightAI class, by this param is initialised AI or not
Returns
new Object
Referenced by DayZIntroSceneXbox::DayZIntroSceneXbox(), FirearmEffects(), Grenade_ChemGas::OnExplode(), PlayerSyncCreate(), Release(), BleedingSourcesManagerBase::SetDiag(), and ShootsExplosiveAmmo().
CreateObjectEx()
proto native Object CreateObjectEx (string type, vector pos, int iFlags, int iRotation = RF_DEFAULT) private
Creates object of certain type.
Parameters
type of objects to create
pos position where to create object
iFlags are used to setup object and/ or spawn behavior
iRotation are used to setup object rotation on spawn (or default if not specified)
Returns
new Object
Referenced by FireplaceBase::AfterStoreLoad(), CreateItemBasePiles(), CreateMagazinePiles(), CreateMagazinePilesFromBullet(), Particle::CreateParticleEffect(), Inventory_Base::EmptySeedPack(), LateInit(), FishingRod_Base_New::OnDebugSpawn(), ActionCreateIndoorFireplace::OnExecuteServer(), ActionCreateIndoorOven::OnExecuteServer(), ActionUnpackGift::OnFinishProgressServer(), FireplaceBase::OnIgnitedThis(), GardenBase::OnPlacementComplete(), OnPlacementComplete(), TentBase::OnPlacementComplete(), OnProjectileStopped(), OnProjectileStoppedInObject(), OnProjectileStoppedInTerrain(), GardenBase::OnStoreLoad(), ItemBase::OnStoreLoad(), ContaminatedArea_Dynamic::SpawnItems(), and ObjectSpawnerHandler::SpawnObject().
CreatePlayer()
proto native Entity CreatePlayer (PlayerIdentity identity, string name, vector pos, float radius, string spec) private
Assign player entity to client (in multiplayer)
Note
Works only on server
Parameters
name
Referenced by MissionBase::CreateCharacter().
CreateRandomPlayer() [1/2]
override string CreateRandomPlayer () inline private
Definition at line 3230 of file DayZGame.c.
Referenced by MissionBase::OnClientNewEvent().
CreateRandomPlayer() [2/2]
string CreateRandomPlayer () inline private
returns class name of random survivor (TODO address confusing naming?)
Definition at line 1372 of file Game.c.
CreateScriptedMenu() [1/2]
override UIScriptedMenu CreateScriptedMenu (int id) inline private
create custom main menu part (submenu)
Definition at line 1327 of file DayZGame.c.
References Mission::CreateScriptedMenu(), GetMission(), and mission.
CreateScriptedMenu() [2/2]
UIScriptedMenu CreateScriptedMenu (int id) inline private
create custom main menu part (submenu)
Definition at line 186 of file Game.c.
CreateScriptedWindow()
UIScriptedWindow CreateScriptedWindow (int id) inline private
create custom window part
Definition at line 191 of file Game.c.
CreateSoundOnObject()
proto native SoundOnVehicle CreateSoundOnObject (Object source, string sound_name, float distance, bool looped, bool create_local = false) private
Referenced by InventoryItem::DoAmmoExplosion(), PlayActionSound(), IEntity::PlaySound(), IEntity::PlaySoundLoop(), and BetaSound::SaySound().
CreateSoundWaveOnObject()
proto native SoundWaveOnVehicle CreateSoundWaveOnObject (Object source, SoundObject soundObject, AbstractWave soundWave) private
CreateStaticObjectUsingP3D()
proto native Object CreateStaticObjectUsingP3D (string p3dFilename, vector position, vector orientation, float scale = 1.0, bool createLocal = false) private
Referenced by ObjectSpawnerHandler::SpawnObject().
CreateTitleScreen()
void CreateTitleScreen () inline private
Definition at line 2068 of file DayZGame.c.
References WorkspaceWidget::CreateWidgets(), DeleteTitleScreen(), GetGame(), GetInput(), BiosUserManager::GetSelectedUser(), GetUserManager(), and GetWorkspace().
Referenced by ConnectLaunch(), GamepadCheck(), MissionLaunch(), and OnInitialize().
DayZGame()
void DayZGame () inline private
Definition at line 965 of file DayZGame.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_COUNT, CALL_CATEGORY_GAMEPLAY, CALL_CATEGORY_GUI, CommandlineGetParam(), ConfigGetChildName(), ConfigGetChildrenCount(), ConfigGetInt(), PPEManagerStatic::CreateManagerStatic(), GetCallQueue(), GetModToBeReported(), GetUApi(), Component::Init(), Debug::Init(), CachedObjectsParams::Init(), CachedObjectsArrays::Init(), IsKindOf(), LoadingScreen(), m_timerQueue, MISSION_STATE_GAME, path, UAInputAPI::PresetSelect(), and SetMainMenuWorld().
Referenced by IsMissionMainMenu().
DeferredInit()
void DeferredInit () inline private
Definition at line 1061 of file DayZGame.c.
References GetInput(), GetMenuDefaultCharacterData(), PPEManagerStatic::GetPPEManager(), GetSoundScene(), GetUserFOVFromConfig(), GameOptions::Initialize(), and Input::UpdateConnectedInputDeviceList().
DelayedMidAirDetonation()
void DelayedMidAirDetonation (float x, float y, float z) inline private
Definition at line 3151 of file DayZGame.c.
References SEffectManager::PlaySound(), EffectSound::SetAutodestroy(), Vector(), x, and y.
DeleteGamepadDisconnectMenu()
void DeleteGamepadDisconnectMenu () private
DeleteTitleScreen()
void DeleteTitleScreen () inline private
Definition at line 2108 of file DayZGame.c.
References m_IntroMenu.
Referenced by Connect(), CreateTitleScreen(), GamepadCheck(), MainMenuLaunch(), and SelectGamepad().
DisconnectPlayer()
proto native void DisconnectPlayer (PlayerIdentity identity, string uid = "") private
Destroy player info and disconnect.
Note
Works only on server
Referenced by MissionBase::PlayerDisconnected().
DisconnectSession()
proto native void DisconnectSession () private
Disconnects from current multiplayer session.
DisconnectSessionEx()
void DisconnectSessionEx (DisconnectSessionFlags flags) inline private
Definition at line 2566 of file DayZGame.c.
References Mission::AbortMission(), NotificationSystem::AddNotification(), UIManager::CloseAllSubmenus(), UIManager::CloseDialog(), DisconnectSessionForce(), g_Game, GamepadCheck(), OnlineServices::GetBiosUser(), GetGame(), GetMission(), GetUIManager(), GetUserManager(), MainMenuLaunch(), BiosUserManager::SelectUserEx(), SetGameState(), and SetLoadState().
Referenced by DisconnectSessionScript().
DisconnectSessionForce()
proto native void DisconnectSessionForce () private
Forces disconnect from current multiplayer session even if not yet in the game.
Referenced by DisconnectSessionEx(), and TryConnect().
DisconnectSessionScript()
void DisconnectSessionScript (bool displayJoinError = false) inline private
Definition at line 2554 of file DayZGame.c.
References DisconnectSessionEx().
Referenced by Connect(), and TryConnect().
DumpInstances()
proto native void DumpInstances (bool csvFormatting) private
Delevoper only: Dump all script allocations.
EarlyAccessDialog()
void EarlyAccessDialog (UIScriptedMenu parent) inline private
Definition at line 1316 of file DayZGame.c.
References g_Game, and MENU_EARLYACCESS.
EnableMicCapture()
proto native void EnableMicCapture (bool enable) private
Enable microphone to locally capture audio from user. Audio heard does NOT automatically get transmitted over network.
Parameters
enable enables or disabled listening
Referenced by ScriptedWidgetEventHandler::OnVonStateEvent(), ScriptedWidgetEventHandler::OptionsMenuSounds(), and ScriptedWidgetEventHandler::~OptionsMenuSounds().
EnableVoN()
proto native void EnableVoN (Object player, bool enable) private
Enable/disable VoN for target player.
Parameters
player in question
enable sets if player can use VoN
Referenced by ManBase::EEKilled(), ManBase::OnUnconsciousStart(), and ManBase::OnUnconsciousStop().
EndOptionsVideo()
proto native void EndOptionsVideo () private
Referenced by UIScriptedMenu::Back(), UIScriptedMenu::OnModalResult(), and ScriptedWidgetEventHandler::~OptionsMenuVideo().
EnterLoginQueue()
void EnterLoginQueue (UIMenuPanel parent) inline private
Definition at line 1899 of file DayZGame.c.
References GetUIManager(), and MENU_LOGIN_QUEUE.
Referenced by UpdateLoginQueue().
EnterLoginTime()
void EnterLoginTime (UIMenuPanel parent) inline private
Definition at line 1905 of file DayZGame.c.
References GetUIManager(), and MENU_LOGIN_TIME.
Referenced by OnLoginTimeEvent(), and OnRespawnEvent().
ExecuteEnforceScript()
proto native bool ExecuteEnforceScript (string expression, string mainFnName) private
Delevoper only: Executes Enforce Script expression, if there is an error, is printed into the script console.
Referenced by PluginBase::ExecuteEnforceScript(), ManBase::OnRPC(), and UIScriptedMenu::RunEnscript().
ExplosionEffects()
void ExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) inline private
Definition at line 3261 of file DayZGame.c.
References vector::Distance(), ParticleList::EXPLOSION_LANDMINE, GetGame(), GetPlayer(), GetPosition, Math::InverseLerp(), Math::Lerp(), and ParticleManager().
Referenced by ExplosionEffectsEx().
ExplosionEffectsEx()
void ExplosionEffectsEx (Object source, Object directHit, int componentIndex, float energyFactor, float explosionFactor, HitInfo hitInfo) inline private
Definition at line 3242 of file DayZGame.c.
References NoiseSystem::AddNoiseTarget(), ExplosionEffects(), HitInfo::GetAmmoType(), GetNoiseSystem(), HitInfo::GetPosition(), HitInfo::GetSurface(), HitInfo::GetSurfaceNoiseMultiplier(), HitInfo::GetSurfaceNormal(), IsServer(), HitInfo::IsWater(), and m_NoiseParams.
ExtendActionJuncture()
proto native bool ExtendActionJuncture (Man player, notnull EntityAI item, int timeout_ms) private
Referenced by ActionManagerServer::Update().
FirearmEffects()
void FirearmEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, bool isWater, bool deflected, string ammoType) inline private
Definition at line 3373 of file DayZGame.c.
References NoiseSystem::AddNoiseTarget(), ConfigGetFloat(), CreateObject(), ImpactMaterials::EvaluateImpactEffectEx(), GetGame(), GetNoiseSystem(), GetPlayer(), Math::InverseLerp(), IsServer(), vector::Length(), m_NoiseParams, SurfaceGetNoiseMultiplier(), and vector::Zero.
FormatRawConfigStringKeys()
bool FormatRawConfigStringKeys (inout string value) inline private
Changes localization key format to script-friendly format.
Parameters
original config string.
Returns
value output string with '$' substituted to script-friendly '#'. If not found, does nothing.
Definition at line 452 of file Game.c.
Referenced by UpdateConstructionParts().
FormatString()
proto void FormatString (string format, string params[], out string output) private
GamepadCheck()
void GamepadCheck () inline private
Definition at line 2313 of file DayZGame.c.
References CreateTitleScreen(), DeleteTitleScreen(), GetGame(), GetID(), GetInput(), GetUIManager(), Input::GetUserGamepad(), GetUserManager(), Input::IdentifyGamepad(), MENU_TITLE_SCREEN, and SelectUser().
Referenced by ConnectLaunch(), DisconnectSessionEx(), MissionLaunch(), and SelectUser().
GetAnalyticsClient()
AnalyticsManagerClient GetAnalyticsClient () inline private
Definition at line 1412 of file Game.c.
References m_AnalyticsManagerClient.
Referenced by ManBase::EEItemAttached(), InventoryItem::EEItemLocationChanged(), AnimatedActionBase::End(), CAContinuousTimeCooking::Execute(), ActionHandcuffTarget::OnExecuteClient(), ActionRestrainTarget::OnFinishProgressClient(), ActionShave::OnFinishProgressClient(), ActionSkinning::OnFinishProgressClient(), and ActionBandageTarget::OnFinishProgressClient().
GetAnalyticsServer()
AnalyticsManagerServer GetAnalyticsServer () inline private
Definition at line 1407 of file Game.c.
References m_AnalyticsManagerServer.
Referenced by ManBase::EEHitBy(), Plastic_Explosive::EEKilled(), Ammo_40mm_Smoke_ColorBase::EEKilled(), ManBase::OnConnect(), and ManBase::OnDisconnect().
GetBacklit()
Backlit GetBacklit () inline private
Definition at line 1298 of file DayZGame.c.
References m_Backlit.
GetCallQueue() [1/2]
override ScriptCallQueue GetCallQueue (int call_category) inline private
Definition at line 1153 of file DayZGame.c.
Referenced by MissionBase::AbortMission(), Ammo_40mm_Smoke_ColorBase::Activate(), Grenade_Base::ActivateRandomTime(), UIScriptedMenu::Cancel(), CancelLoginTimeCountdown(), BaseBuildingBase::CheckFenceClosed(), BaseBuildingBase::CheckFenceOpened(), BaseBuildingBase::CloseFence(), UIManager::CloseWindow(), UIScriptedMenu::ColorRunButton(), CommitSuicide(), DayZIntroSceneXbox::CreateRandomCharacter(), DayZGame(), DayZIntroScene::DayZIntroScene(), DayZIntroSceneXbox::DayZIntroSceneXbox(), Component::DebugBBoxDelete(), Component::DebugBBoxDraw(), Component::DebugDirectionDelete(), Component::DebugDirectionDraw(), IEntity::DecreaseHealth(), IEntity::Delete(), Destroy(), DynamicArea_Flare::DynamicArea_Flare(), Clothing_Base::EEHealthLevelChanged(), ManBase::EEHealthLevelChanged(), EEHitBy(), Weapon::EEInit(), ItemBase::EEInit(), EEInit(), ManBase::EEItemAttached(), FlammableBase::EEItemDetached(), ManBase::EEItemDetached(), ManBase::EEItemOutOfHands(), Ammo_40mm_Explosive::EEKilled(), ItemBase::EEOnAfterLoad(), EndLoading(), EOnFrame(), UIScriptedMenu::Exit(), UIScriptedMenu::GameRespawn(), UIScriptedMenu::GameRetry(), HandleEngineSound(), HandleSoundEffectsPipeCreaking(), Init(), ManBase::Init(), UIScriptedMenu::Init(), Interact(), Land_Underground_EntranceBase::Land_Underground_EntranceBase(), LogSuicide(), MissionBase::MissionServer(), OnActivate(), DrowningMdfr::OnActivate(), ImprovisedExplosive::OnActivatedByItem(), ClaymoreMine::OnArmed(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnClick_Continue(), UIScriptedMenu::OnClick_Exit(), UIScriptedMenu::OnClick_Respawn(), UIScriptedMenu::OnClick_Restart(), MissionBase::OnClientDisconnectedEvent(), Grenade_ChemGas::OnDamageDestroyed(), ManBase::OnDrowningEnd(), OnEvent(), FireworksLauncherClientEvent::OnExplode(), OnExplode(), ActionDestroyCombinationLock::OnFinishProgressServer(), FireworksLauncher::OnFuseIgnitedServer(), BiosSessionService::OnGetSessionError(), DestructionEffectBase::OnHealthLevelChanged(), FireplaceBase::OnIgnitedThis(), OnItemLocationChanged(), OnLoginTimeEvent(), UIScriptedMenu::OnModalResult(), ScriptedWidgetEventHandler::OnMouseButtonDown(), Land_Underground_Panel_Lever::OnPanelUsedSynchronized(), ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), OnPlacementComplete(), ManBase::OnPlayerLoaded(), MissionBase::OnPlayerRespawned(), OnRespawnEvent(), ManBase::OnRPC(), OnRPC(), PluginBase::OnRPCSyncSceneObject(), ManBase::OnSelectPlayer(), OnShow(), PluginBase::OnUIEditorOpened(), OnUpdate(), ItemBase::OnVariablesSynchronized(), BaseBuildingBase::OpenFence(), ScriptedWidgetEventHandler::OptionsMenuControls(), UIScriptedMenu::PerformSetToDefaultsExt(), Play(), UIScriptedMenu::Play(), MissionBase::PlayerDisconnected(), ItemBase::Refresh(), RefreshFireplaceVisuals(), ManBase::RefreshHandAnimationState(), ItemBase::RegenerateNavmesh(), UndergroundTriggerCarrierBase::RequestDelayedTriggerSpawn(), Land_Underground_EntranceBase::RequestLatentTransition(), FireworksLauncherClientEvent::RequestSecondaryExplosion(), UniversalTemperatureSourceDebug::SetDefferedActive(), DayZPlayer::ShowDeadScreen(), ManBase::SpawnDrowningBubbles(), CrashBase::SpawnRandomDeerLater(), StartFire(), MissionBase::StartLogoutMenu(), Stop(), StopFire(), Synchronize(), ToggleDebugWindowEvent(), UIScriptedMenu::Update(), UpdateInputDeviceDisconnectWarning(), ItemBase::UpdateNavmesh(), ItemBase::UpdatePhysics(), UpdateVisuals(), and MissionBase::~MissionServer().
GetCallQueue() [2/2]
ScriptCallQueue GetCallQueue (int call_category) inline private
Returns CallQueue for certain category
Parameters
call_category call category, valid values are:
CALL_CATEGORY_SYSTEM - calls & timers in this queue are processed every time without any restrictions
CALL_CATEGORY_GUI - calls & timers in this queue are processed when GUI is enabled (even during pase game)
CALL_CATEGORY_GAMEPLAY - calls & timers in this queue are processed only during mission, when game is not paused
usage:
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "Refresh"); // calls "Refresh" function on "this" with no arguments
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "Show", new Param1<bool>(true)); // calls "Show" function on "this" with one bool argument
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "SetPos", new Param2<float, float>(0.2, 0.5)); // calls "SetPos" function on "this" with two float arguments
Definition at line 1349 of file Game.c.
GetConnectedInputDeviceList()
array< int > GetConnectedInputDeviceList () inline private
Definition at line 3621 of file DayZGame.c.
References m_ConnectedInputDeviceList.
GetContentDLCService()
proto native ContentDLC GetContentDLCService () private
Return DLC service (service for entitlement keys for unlock content)
Referenced by UIScriptedMenu::Init(), ServerBrowserTab(), UIScriptedMenu::~MainMenuConsole(), and ~ServerBrowserTab().
GetCurrentCameraDirection()
proto native vector GetCurrentCameraDirection () private
Referenced by HitDirectionEffectBase::CalculateArrowPosition(), ManBase::CommandHandler(), PoweredOptic_Base::DoMeasurement(), ManBase::GetAimPosition(), Hologram::GetDefaultOrientation(), Hologram::GetProjectionEntityPosition(), Hologram::HideWhenClose(), HitZoneSelection(), HitZoneSelectionRaycast(), BaseBuildingBase::IsFacingCamera(), Weapon::LiftWeaponCheck(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnDoubleClick(), WeaponDebug::OnPostFrameUpdate(), Hud::RefreshPlayerTags(), DeveloperTeleport::TeleportAtCursor(), and DeveloperTeleport::TeleportAtCursorEx().
GetCurrentCameraPosition()
proto native vector GetCurrentCameraPosition () private
Referenced by PoweredOptic_Base::DoMeasurement(), Event_OnClick(), EffBulletImpactBase::Event_OnStarted(), ManBase::GetAimPosition(), Hologram::GetProjectionEntityPosition(), Hologram::IsClippingRoof(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnDoubleClick(), Hit_MeatBones::OnEnterCalculations(), PointLightBase::OnFrameLightSource(), WeaponDebug::OnPostFrameUpdate(), Hud::RefreshPlayerTags(), DeveloperTeleport::TeleportAtCursor(), and DeveloperTeleport::TeleportAtCursorEx().
GetCurrentDisplayLanguageIdx()
int GetCurrentDisplayLanguageIdx () inline private
Definition at line 3585 of file DayZGame.c.
References GameOptions::GetOptionByType().
GetCurrentEVValue()
float GetCurrentEVValue () inline private
Definition at line 3575 of file DayZGame.c.
References m_EVValue.
GetDatabaseID()
string GetDatabaseID () inline private
Definition at line 2054 of file DayZGame.c.
References m_DatabaseID.
GetDayTime()
proto native float GetDayTime () private
Returns current daytime on server.
Referenced by ActionFishingNew::EvaluateFishingResult().
GetDeltaT()
float GetDeltaT () inline private
Definition at line 2766 of file DayZGame.c.
References m_DeltaTime.
GetDiagDrawMode()
proto native int GetDiagDrawMode () private
Gets current debug draw mode.
GetDiagDrawModeNames()
proto native void GetDiagDrawModeNames (out TStringArray diag_names) private
Get list of all debug draw modes.
Referenced by UIScriptedMenu::Init().
GetDiagModeEnable()
proto native bool GetDiagModeEnable (int diag_mode) private
Gets state of specific debug mode.
Referenced by UIScriptedMenu::OnClick().
GetDiagModeNames()
proto native void GetDiagModeNames (out TStringArray diag_names) private
Get list of all debug modes.
Referenced by UIScriptedMenu::Init().
GetDragQueue() [1/2]
override DragQueue GetDragQueue () inline private
Definition at line 1173 of file DayZGame.c.
References m_dragQueue.
Referenced by ScrollBarContainer::OnMouseButtonDown(), UIScriptedMenu::OnMouseButtonDown(), OnUpdate(), ScrollBarContainer::StopScrolling(), and UIScriptedMenu::~InspectMenuNew().
GetDragQueue() [2/2]
DragQueue GetDragQueue () inline private
Returns DragQueue. Callbacks are called on mouse move until mouse button is released, then the queue is cleaned.
Definition at line 1366 of file Game.c.
GetEntityByPersitentID()
proto native EntityAI GetEntityByPersitentID (int b1, int b2, int b3, int b4) private
Returns EntityAI by its persistent ID parts or null if entity with given persistent ID does not exists.
This function returns valid data only inside AfterLoad event. Do not use this in anywhere else.
Its main purpose is only for keep track on object connections after server restarts, all data related to this function are deleted when server initialization is done.
GetFoodDecayModifier()
float GetFoodDecayModifier () inline private
Definition at line 3609 of file DayZGame.c.
References m_FoodDecayModifier.
Referenced by IsFoodDecayEnabled().
GetFOVByZoomType()
float GetFOVByZoomType (ECameraZoomType type) inline private
Definition at line 3521 of file DayZGame.c.
References GameConstants::DZPLAYER_CAMERA_FOV_EYEZOOM, GameConstants::DZPLAYER_CAMERA_FOV_EYEZOOM_SHALLOW, GetUserFOV(), and Math::Min().
GetFps()
proto native float GetFps () private
Returns average FPS of last 16 frames.
Returns
fps in milliseconds
GetGameState()
DayZGameState GetGameState () inline private
Definition at line 1278 of file DayZGame.c.
References m_GameState.
Referenced by OnEvent(), OnMPConnectionLostEvent(), and TryConnect().
GetHighestSurfaceYDifference()
float GetHighestSurfaceYDifference (array< vector > positions) inline private
Returns the largest height difference between the given positions.
Definition at line 1050 of file Game.c.
References SurfaceRoadY(), and y.
Referenced by ActionDigInStash::ActionCondition().
GetHostAddress()
proto bool GetHostAddress (out string address, out int port) private
Gets the server address. (from client)
Referenced by Connect(), OnEvent(), BiosSessionService::OnGetGameplaySession(), RefreshCurrentServerInfo(), and TryConnect().
GetHostData()
proto GetServersResultRow GetHostData () private
Gets the server data. (from client)
GetHostName()
proto owned string GetHostName () private
Gets the server name. (from client)
Referenced by EnProfilerTests::TestFuncCountData().
GetHUDBrightnessSetting()
float GetHUDBrightnessSetting () inline private
Definition at line 3543 of file DayZGame.c.
References g_Game.
Referenced by OnInitialize().
GetInput()
proto native Input GetInput () private
Referenced by PluginBase::CaptureFocus(), CaptureFocus(), CreateTitleScreen(), DeferredInit(), PluginBase::FreeCameraControlDisable(), PluginBase::FreeCameraControlEnable(), GamepadCheck(), UIScriptedMenu::GetControlMappingInfo(), UIScriptedMenu::Init(), UIMenuPanel::LockControls(), DayZPlayer::LockControls(), UIScriptedMenu::OnClick(), BiosUserManager::OnJoin(), UIScriptedMenu::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnSelectConsolePreset(), ScriptedWidgetEventHandler::OnSelectKBPreset(), UIScriptedMenu::OnSelectKBPreset(), UIScriptedMenu::OnShow(), BiosUserManager::OnSignedOut(), MissionBase::OnUpdate(), BiosUserManager::OnUserLoggedOn(), BiosUserManager::OnUserPicked(), ScriptedWidgetEventHandler::OptionsMenuControls(), RadialMenu(), PluginBase::ReleaseFocus(), ReleaseFocus(), ScriptedWidgetEventHandler::Reload(), SelectUser(), PluginBase::SetDeveloperItemClientEx(), SwitchPreset(), PluginBase::ToggleFocus(), ScriptedWidgetEventHandler::TutorialKeybinds(), UIMenuPanel::UnlockControls(), UpdataControllerInput(), InputUtils::UpdateConsolePresetID(), UIScriptedMenu::UpdateControlsElements(), UIScriptedMenu::UpdateControlsElementVisibility(), UpdateInputDeviceDisconnectWarning(), ScriptedWidgetEventHandler::UpdatePCIconsVisibility(), UIMenuPanel::UseKeyboard(), and UIMenuPanel::UseMouse().
GetInventoryItemSize()
proto void GetInventoryItemSize (InventoryItem item, out int width, out int height) private
Referenced by ActionPackGift::ActionCondition(), Icon::CreateWhiteBackground(), Container::InitIconEx(), magazinesHaveEqualSizes(), ClosableHeader::OnDragHeader(), ActionPackGift::OnFinishProgressServer(), SlotsIcon::OnIconDrag(), Icon::RevertToOriginalFlip(), SlotsIcon::SetItemSize(), Icon::SetItemSizeEx(), SnapOnObject(), ClosableHeader::UpdateFlip(), Icon::UpdateFlip(), and UpdateInterval().
GetLastVisitedServer()
bool GetLastVisitedServer (out string ip, out int port) inline private
Definition at line 2474 of file DayZGame.c.
References string::Split().
GetLoadingWorkspace()
proto native WorkspaceWidget GetLoadingWorkspace () private
GetLoadState()
DayZLoadState GetLoadState () inline private
Definition at line 1288 of file DayZGame.c.
References m_LoadState.
Referenced by OnInitialize(), SelectGamepad(), SelectUser(), and TryConnect().
GetMainMenuWorld()
proto native owned string GetMainMenuWorld () private
Referenced by MainMenuLaunch(), and PartyLaunch().
GetMenuData()
proto native MenuData GetMenuData () private
Return singleton of MenuData class - at main menu contains characters played with current profile.
Referenced by UIScriptedMenu::Back(), GetMenuDefaultCharacterData(), MenuDefaultCharacterData::Init(), and ManBase::OnSelectPlayer().
GetMenuDefaultCharacterData()
MenuDefaultCharacterData GetMenuDefaultCharacterData (bool fill_data = true) inline private
Definition at line 1392 of file Game.c.
References GetGame(), GetMenuData(), m_CharacterData, and MenuData::RequestGetDefaultCharacterData().
Referenced by UIScriptedMenu::BottomChanged(), Managed::CreateDefaultCharacter(), Managed::CreateNewCharacter(), Managed::CreateNewCharacterByName(), DeferredInit(), UIScriptedMenu::GameRespawn(), UIScriptedMenu::GameRetry(), Managed::GetCharacterName(), Managed::GetCharacterNameById(), MenuData::GetMenuDefaultCharacterDataInstance(), MissionBase::OnClientNewEvent(), MissionBase::ProcessLoginData(), UIScriptedMenu::RandomizeCharacter(), Managed::SaveCharName(), DayZIntroSceneXbox::SaveCharName(), UIScriptedMenu::SetCharacter(), UIScriptedMenu::ShoesChanged(), StoreLoginDataPrepare(), and UIScriptedMenu::TopChanged().
GetMission()
proto native Mission GetMission () private
Referenced by ActionRestrainTarget::ActionConditionContinue(), ScriptedWidgetEventHandler::ActionTargetsCursor(), UIScriptedMenu::Cancel(), CheckDialogs(), ManBase::CloseInventoryMenu(), ManBase::CloseMapEx(), UIScriptedMenu::CloseMapMenu(), ServerBrowserTab::Construct(), CreateScriptedMenu(), DeveloperFreeCamera::DisableFreeCamera(), DisconnectSessionEx(), PluginBase::DisplayTendency(), ManBase::EEKilled(), ContaminatedArea_Dynamic::EEOnCECreate(), DeveloperFreeCamera::EnableFreeCamera(), UIScriptedMenu::Exit(), UIScriptedMenu::GesturesMenu(), ScriptedWidgetEventHandler::GetHud(), DayZPlayer::HandleDamageHit(), MissionBase::HandleMapToggleByKeyboardShortcut(), BaseBuildingBase::HandleRefreshers(), UIScriptedMenu::HudShow(), UIScriptedMenu::InGameMenuXbox(), BleedingSourcesManagerBase::Init(), ManBase::Init(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), Init(), BaseBuildingBase::InsertRefresherPosition(), ScriptedWidgetEventHandler::InspectItem(), Inventory(), IsFullBody(), ManBase::IsTargetInActiveRefresherRange(), IsVonToggled(), ScriptedWidgetEventHandler::ItemActionsWidget(), UIScriptedMenu::OnClick(), ManBase::OnCommandLadderFinish(), ManBase::OnCommandLadderStart(), ManBase::OnCommandSwimFinish(), ManBase::OnCommandSwimStart(), ManBase::OnCommandVehicleFinish(), ManBase::OnCommandVehicleStart(), OnConnectivityStatChange(), ActionViewOptics::OnEndClient(), ActionViewOptics::OnEndServer(), OnEvent(), OnEvent(), Input::OnGamepadConnected(), Input::OnGamepadDisconnected(), Input::OnGamepadIdentification(), ManBase::OnGameplayDataHandlerSync(), UIScriptedMenu::OnHide(), OnHide(), Input::OnKeyboardConnected(), Input::OnKeyboardDisconnected(), OnKeyPress(), OnKeyRelease(), Input::OnLastInputDeviceChanged(), CfgGameplayHandler::OnLoaded(), OnLoginTimeEvent(), UIScriptedMenu::OnModalResult(), UIScriptedMenu::OnMouseButtonDown(), OnMouseButtonPress(), OnMouseButtonRelease(), Input::OnMouseConnected(), Input::OnMouseDisconnected(), ScriptedWidgetEventHandler::OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), ManBase::OnPlayerLoaded(), OnPostUpdate(), ManBase::OnRestrainStart(), ManBase::OnRPC(), UIScriptedMenu::OnSelectKBPreset(), ManBase::OnSelectPlayer(), DeveloperFreeCamera::OnSetFreeCameraEvent(), UIScriptedMenu::OnShow(), OnShow(), ManBase::OnSpawnedFromConsole(), PPERequester_GameplayBase::OnStart(), ActionViewOptics::OnStartClient(), ActionViewOptics::OnStartServer(), PPERequester_GameplayBase::OnStop(), ManBase::OnUnconsciousStop(), ManBase::OnUnconsciousUpdate(), OnUpdate(), PPERequester_GameplayBase::OnUpdate(), BiosUserManager::OnUserPicked(), OnVOIPThresholdChanged(), HeadGear_Base::OnWasAttached(), UIManager::OpenWindow(), ActionUnfoldMapCB::PerformMapChange(), UIScriptedMenu::PerformSwitchPreset(), UIScriptedMenu::RadialQuickbarMenu(), DebugMonitorValues::ReceiveValue(), BleedingSourcesManagerBase::RegisterBleedingZoneEx(), BaseBuildingBase::RemoveRefresherPosition(), PluginBase::ResetGUI(), UIScriptedMenu::ScriptConsole(), InventoryActionHandler::SetAction(), PluginBase::SetBadge(), SetNVPostprocess(), PluginBase::SetStamina(), PluginBase::SetStance(), ShowVoiceNotification(), StartSourceBleedingIndication(), StopSourceBleedingIndication(), PluginBase::SwitchPermanentCrossHair(), SwitchPreset(), PluginBase::ToggleScriptConsole(), ScriptedWidgetEventHandler::Update(), GameplayEffectsData::Update(), ManBase::UpdateLighting(), UpdateLoginQueue(), UpdateSpecialtyMeter(), UpdateVoiceLevel(), VirtualHud(), UIScriptedMenu::WarningMenuBase(), ActionUnfoldMapCB::~ActionUnfoldMapCB(), UIScriptedMenu::~GesturesMenu(), UIScriptedMenu::~InGameMenuXbox(), UIScriptedMenu::~InspectMenuNew(), UIScriptedMenu::~MainMenuConsole(), UIScriptedMenu::~RadialQuickbarMenu(), UIScriptedMenu::~ScriptConsole(), and UIScriptedMenu::~WarningMenuBase().
GetMissionFolderPath()
string GetMissionFolderPath () inline private
Definition at line 1148 of file DayZGame.c.
References m_MissionFolderPath.
GetMissionPath()
string GetMissionPath () inline private
Definition at line 1143 of file DayZGame.c.
References m_MissionPath.
GetMissionState()
int GetMissionState () inline private
Definition at line 1186 of file DayZGame.c.
References m_MissionState.
GetModelName()
string GetModelName (string class_name) inline private
Get name of the p3d file of the given class name.
Parameters
class name of the desired object
Returns
Name of the object's p3d file (without the '.p3d' suffix)
Definition at line 464 of file Game.c.
References class_name, ConfigGetText(), string::Get(), GetGame(), string::Length(), and string::Substring().
Referenced by IEntity::GetModelName().
GetModInfos()
proto native void GetModInfos (notnull out array< ref ModInfo > modArray) private
Referenced by UIScriptedMenu::LoadMods().
GetModToBeReported()
proto native bool GetModToBeReported () private
Referenced by DayZGame().
GetNoiseSystem()
proto native NoiseSystem GetNoiseSystem () private
Referenced by DayZPlayer::AddNoise(), CloseCombatEffects(), EEInit(), ExplosionEffectsEx(), FirearmEffects(), GenerateAINoiseAtPosition(), Heating(), AlarmClock_ColorBase::Init(), KitchenTimer::Init(), ActionCloseDoors::OnEndServer(), ActionCloseFence::OnEndServer(), ActionOpenDoors::OnEndServer(), ActionOpenFence::OnEndServer(), OnWork(), OnWorkStart(), DayZCreature::ProcessSoundEvent(), DayZPlayer::ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), and DayZInfected::ProcessSoundVoiceEvent().
GetObjectByNetworkId()
proto native Object GetObjectByNetworkId (int networkIdLowBits, int networkIdHighBits) private
Returns entity identified by network id.
Parameters
networkIdLowBits identity used in MP (use NULL in singleplayer)
networkIdHighBits object which should be controlled by player
GetObjectsAtPosition()
proto native void GetObjectsAtPosition (vector pos, float radius, out array< Object > objects, out array< CargoBase > proxyCargos) private
Returns list of all objects in circle "radius" around position "pos".
Parameters
pos
radius
objects output array
Referenced by BotSelectNearestTarget(), UIScriptedMenu::DrawItems(), UniversalTemperatureSourceLambdaBaseImpl::DryItemsInVicinity(), Environment::GatherTemperatureSources(), PluginBase::GatherTemperatureSources(), and UIScriptedMenu::OnTabSeleted().
GetObjectsAtPosition3D()
proto native void GetObjectsAtPosition3D (vector pos, float radius, out array< Object > objects, out array< CargoBase > proxyCargos) private
Returns list of all objects in sphere "radius" around position "pos".
Parameters
pos
radius
objects output array
Referenced by ActionCreateGreenhouseGardenPlot::ActionCondition(), FireplaceBase::CanPlaceFireplaceInSelectedSpot(), and VicinityItemManager::RefreshVicinityItems().
GetPlayer()
proto native DayZPlayer GetPlayer () private
Referenced by GameInventory::AddInventoryReservationEx(), CalculateEyeAccoTarget(), AttachmentCategoriesRow::CanCombine(), Attachments::CanEquip(), LayoutHolder::CanEquipEx(), GameInventory::ClearInventoryReservationEx(), CloseCombatEffects(), Container::Combine(), AttachmentCategoriesRow::Combine(), InventoryItem::CombineItemsClient(), DebugGrowAgentsRequest(), DebugRemoveAgentsRequest(), HandsContainer::DraggingOverGrid(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), HandsContainer::ElectricityIcon(), Attachments::EquipItem(), Container::EquipItem(), PlayerContainer::EquipItem(), VicinitySlotsContainer::EquipItem(), ZombieContainer::EquipItem(), ExplosionEffects(), GameInventory::ExtendInventoryReservationEx(), FirearmEffects(), ItemBase::FullyBuild(), GetEmptyingEndSoundset(), GetEmptyingLoopSoundset(), HandleForceSwapEntities(), HandleSwapEntities(), HandleTakeToDst(), HandsPreview::HandsPreview(), UIScriptedMenu::Init(), PlayerContainer::InspectItem(), IsServerOrLocalPlayer(), Icon::MouseClick(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), MoveAttachmentDown(), MoveAttachmentUp(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnClick_Respawn(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesContainer::OnDropReceivedFromHeader(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), ZombieContainer::OnDropReceivedFromHeader(), OnEvent(), MissionBase::OnEvent(), HandsArea::OnHandsPanelDropReceived(), AnalyticsManagerClient::OnItemAttachedAtPlayer(), OnRespawnEvent(), InventoryItem::OnRightClick(), OnRPC(), UIScriptedMenu::OnShow(), OnUpdate(), OnUpdate(), MissionBase::OnUpdate(), PlayerSyncCreate(), RefreshFireplaceVisuals(), UIScriptedMenu::RefreshPlayerPosEditBoxes(), AttachmentCategoriesRow::RefreshSlot(), UIScriptedMenu::RequestRespawn(), Attachments::Select(), Container::Select(), HandsPreview::Select(), AttachmentCategoriesRow::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), SendSyncMessages(), Container::SetLock(), FlareSimulation::Simulate(), Icon::Swap(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), PMTPlayback::TestOnePlaying(), PMTPlayback::TestOnePlayingStandAlone(), PMTPlayback::TestOnePlayingStandAloneAutoDestroy(), PMTPlayback::TestStopping(), PMTPlayback::TestWiggleStress(), Attachments::TransferItem(), Container::TransferItem(), HandsContainer::TransferItem(), AttachmentCategoriesRow::TransferItem(), PlayerContainer::TransferItem(), VicinitySlotsContainer::TransferItem(), ZombieContainer::TransferItem(), Container::TransferItemToVicinity(), PlayerContainer::TransferItemToVicinity(), ZombieContainer::TransferItemToVicinity(), UIScriptedMenu::UpdateGUI(), UIScriptedMenu::UpdateMenuFocus(), UIScriptedMenu::UpdateMousePos(), UIScriptedMenu::UpdateTime(), and HandsPreview::~HandsPreview().
GetPlayerByIndex()
DayZPlayer GetPlayerByIndex (int index = 0) inline private
Definition at line 815 of file Game.c.
References GetPlayers().
GetPlayerGameName()
string GetPlayerGameName () inline private
Definition at line 3479 of file DayZGame.c.
References m_PlayerName.
GetPlayerIndentities()
proto native void GetPlayerIndentities (out array< PlayerIdentity > identities) private
GetPlayerName()
proto void GetPlayerName (out string name) private
Gets current player name.
Parameters
name output value
Referenced by UIScriptedMenu::Init(), UIScriptedMenu::OnChange(), and ScriptedWidgetEventHandler::ServerBrowserFilterContainer().
GetPlayerNameShort()
proto void GetPlayerNameShort (int maxLength, out string name) private
Gets current player name. If length of player name is grater than maxLength, then it is omitted and append ellipsis.
Parameters
maxLength - max chars in name
name - output value of player name with 'maxLength' characters and then ellipsis "..."
GetPlayerNetworkIDByIdentityID()
proto void GetPlayerNetworkIDByIdentityID (int playerIdentityID, out int networkIdLowBits, out int networkIdHightBits) private
returns player's network id from identity id in out parameters
Parameters
identity PlayerIdentity.id used in MP (use NULL in singleplayer)
networkIdLowBits lower bits of 64bit network id
networkIdHighBits higher bits of 64bit network id
Note
Usable only on server
GetPlayers()
proto native void GetPlayers (out array< Man > players) private
Referenced by PluginBase::GatherPlayerInfo(), GetPlayerByIndex(), PluginBase::PlayerList(), PluginBase::SendServerLogToClient(), ManBase::SpreadAgentsEx(), and MissionBase::UpdatePlayersStats().
GetPointerDirection()
proto native vector GetPointerDirection () private
Returns the direction where the mouse points, from the camera view.
Referenced by Event_OnClick(), PluginBase::Event_OnClick(), PluginBase::Event_OnClickMiddle(), PluginBase::Event_OnDoubleClick(), PluginBase::Event_OnDrag(), UIScriptedMenu::GetMouseLookDir(), and PluginBase::GetMousePositionInScene().
GetPostUpdateQueue() [1/2]
override ScriptInvoker GetPostUpdateQueue (int call_category) inline private
Definition at line 1163 of file DayZGame.c.
Referenced by CrossHairSelector(), OnPostUpdate(), and ~CrossHairSelector().
GetPostUpdateQueue() [2/2]
ScriptInvoker GetPostUpdateQueue (int call_category) inline private
Definition at line 1353 of file Game.c.
GetPreviousEVValue()
float GetPreviousEVValue () inline private
Definition at line 3580 of file DayZGame.c.
References m_PreviousEVValue.
GetPreviousGamepad()
int GetPreviousGamepad () inline private
Definition at line 2308 of file DayZGame.c.
References m_PreviousGamepad.
GetProfileOption()
bool GetProfileOption (EDayZProfilesOptions option) inline private
Definition at line 1198 of file DayZGame.c.
Referenced by GetProfileOptionBool().
GetProfileOptionBool()
bool GetProfileOptionBool (EDayZProfilesOptions option) inline private
Definition at line 1203 of file DayZGame.c.
References GetProfileOption().
GetProfileOptionDefault()
bool GetProfileOptionDefault (EDayZProfilesOptions option) inline private
Definition at line 1218 of file DayZGame.c.
Referenced by GetProfileOptionDefaultBool().
GetProfileOptionDefaultBool()
bool GetProfileOptionDefaultBool (EDayZProfilesOptions option) inline private
Definition at line 1223 of file DayZGame.c.
References GetProfileOptionDefault().
GetProfileOptionDefaultFloat()
float GetProfileOptionDefaultFloat (EDayZProfilesOptions option) inline private
Definition at line 1233 of file DayZGame.c.
GetProfileOptionDefaultInt()
int GetProfileOptionDefaultInt (EDayZProfilesOptions option) inline private
Definition at line 1228 of file DayZGame.c.
GetProfileOptionFloat()
float GetProfileOptionFloat (EDayZProfilesOptions option) inline private
Definition at line 1213 of file DayZGame.c.
GetProfileOptionInt()
int GetProfileOptionInt (EDayZProfilesOptions option) inline private
Definition at line 1208 of file DayZGame.c.
GetProfileOptionMap()
map< EDayZProfilesOptions, ref DayZProfilesOption > GetProfileOptionMap () inline private
Definition at line 1258 of file DayZGame.c.
GetProfileString()
proto bool GetProfileString (string name, out string value) private
Gets string from profile variable.
Parameters
name of the variable
value output value
Returns
true when successful
Referenced by ItemManager::GetDefaultOpenStateHands(), ScriptedWidgetEventHandler::LoadFilters(), DayZProfilesOptions::RegisterProfileOptionFloat(), DayZProfilesOptions::RegisterProfileOptionInt(), DayZProfilesOptions::ResetOptionsFloat(), and DayZProfilesOptions::ResetOptionsInt().
GetProfileStringList()
proto native void GetProfileStringList (string name, out TStringArray values) private
Gets array of strings from profile variable.
Parameters
name of the variable
values output values
usage:
TStringArray lastInventoryArray = new TStringArray;
GetGame().GetProfileStringList("lastInventory", lastInventoryArray);
Referenced by ItemManager::DeserializeDefaultHeaderOpenStates(), ItemManager::DeserializeDefaultOpenStates(), UIScriptedMenu::LoadFavoriteServers(), and OnInitialize().
GetScreenPos()
proto native vector GetScreenPos (vector world_pos) private
Transforms position in world to position in screen in pixels as x, y component of vector, z parameter represents distance between camera and world_pos.
Referenced by FloatingCrossHair(), ScriptedWidgetEventHandler::GetOnScreenPosition(), ScriptedWidgetEventHandler::Update(), PluginBase::UpdateStatWidgets(), and UpdateWidgetsStats().
GetScreenPosRelative()
proto native vector GetScreenPosRelative (vector world_pos) private
Transforms position in world to position in screen in percentage (0.0 - 1.0) as x, y component of vector, z parameter represents distance between camera and world_pos.
Referenced by Hud::RefreshPlayerTags(), Hud::ShowPlayerTag(), ScriptedWidgetEventHandler::TransformToScreenPos(), and ScriptedWidgetEventHandler::UpdatePos().
GetSoundScene()
proto native AbstractSoundScene GetSoundScene () private
Referenced by SoundObjectBuilder::BuildSoundObject(), DeferredInit(), DayZPlayer::HandleView(), VONManager::IsVoiceThresholdMinimum(), PluginBase::OnGUITimer(), UIScriptedMenu::OnHide(), MissionBase::OnPlayerRespawned(), UIScriptedMenu::OnShow(), ManBase::OnUnconsciousStart(), ManBase::OnUnconsciousStop(), MissionBase::PlayMusic(), DayZCreature::PlaySound(), EntityAI::PlaySound(), DayZPlayer::PlaySound(), ManBase::SaySoundSet(), DayZPlayer::SimulateDeath(), and EffectSound::SoundPlayEx().
GetSurfaceOrientation()
vector GetSurfaceOrientation (float x, float z) inline private
Returns tilt of the ground on the given position in degrees, so you can use this value to rotate any item according to terrain.
Definition at line 1074 of file Game.c.
References GetGame(), SurfaceGetNormal(), vector::VectorToAngles(), and x.
Referenced by Hit_MeatBones::BloodSplatGround(), and PluginBase::SetupSpawnedEntity().
GetTickTime()
proto native float GetTickTime () private
Returns current time from start of the game.
Returns
time in seconds
Referenced by NotificationSystem::AddNotification(), NotificationSystem::AddNotificationExtended(), DoEverything(), EntityAI::ProcessImpactSoundEx(), EnProfilerTests::Sleep(), SleepAgain(), EnProfilerTests::StringConcat(), EnProfilerTests::StringFormat(), and NotificationSystem::Update().
GetTime()
proto int GetTime () private
returns mission time in milliseconds
Referenced by WeaponManager::CanEjectBulletVerified(), FlareSimulation::CastFlareAINoise(), CheckContactCache(), DayZPlayer::CommandHandler(), ManBase::EEHitBy(), WeaponManager::EjectBulletVerified(), EntityLightSource::EOnFrame(), ManBase::EOnPostFrame(), ReplaceItemWithNewLambdaBase::Execute(), ComponentEnergyManager::GetCurrentUpdateTime(), DayZPlayer::HandleView(), CABase::Init(), HumanCommandActionCallback::Init(), IsDummyFinished(), ServerBrowserTab::LeftHold(), UnconsciousnessMdfr::OnDeactivate(), PluginBase::OnFrame(), PluginBase::OnMouseButtonRelease(), OnScheduledTick(), ManBase::OnTick(), Play(), StaminaSoundHandlerBase::PostponeStamina(), MouseButtonInfo::Press(), ServerBrowserTab::PressX(), ProcessSound(), InjurySoundHandlerBase::ProcessSound(), MouseButtonInfo::Release(), ServerBrowserTab::RightHold(), EntityLightSource::ScriptedLightBase(), WeaponManager::SetEjectBulletTryTimestamp(), EntityLightSource::SetLifetime(), TickNotifiers(), Update(), and MissionBase::UpdateCorpseStatesServer().
GetTimerQueue() [1/2]
override TimerQueue GetTimerQueue (int call_category) inline private
Definition at line 1168 of file DayZGame.c.
References m_timerQueue.
Referenced by OnInit(), and OnUpdate().
GetTimerQueue() [2/2]
TimerQueue GetTimerQueue (int call_category) inline private
Returns TimerQueue for certain category
Parameters
call_category call category, valid values are:
CALL_CATEGORY_SYSTEM - calls & timers in this queue are processed every time without any restrictions
CALL_CATEGORY_GUI - calls & timers in this queue are processed when GUI is enabled (even during pase game)
CALL_CATEGORY_GAMEPLAY - calls & timers in this queue are processed only during mission, when game is not paused
Definition at line 1361 of file Game.c.
GetUIManager()
proto native UIManager GetUIManager () private
Referenced by PluginBase::AddKeyframe(), UIScriptedMenu::Apply(), ScriptedWidgetEventHandler::Apply(), Back(), UIScriptedMenu::Back(), PluginBase::CaptureFocus(), CaptureFocus(), UIScriptedMenu::ChangeAccount(), CheckDialogs(), ManBase::CloseInventoryMenu(), ManBase::CloseMapEx(), UIScriptedMenu::CloseMenu(), UIScriptedWindow::CloseWindow(), Connect(), MissionBase::Continue(), PluginBase::CursorHide(), PluginBase::CursorShow(), PluginBase::DeleteKeyframe(), DisconnectSessionEx(), MissionBaseWorld::DumpCurrentUILayout(), PluginBase::EditorToggle(), EnterLoginQueue(), EnterLoginTime(), UIScriptedMenu::Exit(), PluginBase::FreeCameraControlDisable(), PluginBase::FreeCameraControlEnable(), GamepadCheck(), UIScriptedMenu::GameRetry(), HandleError(), MissionBase::HandleMapToggleByKeyboardShortcut(), UIScriptedMenu::Init(), Inventory(), PluginBase::IsCurrentUIPageValid(), PluginBase::IsInConsole(), PluginBase::IsIngame(), IsInventoryOpen(), MissionBase::IsPaused(), LoadProgressUpdate(), UIMenuPanel::LockControls(), DayZPlayer::LockControls(), OnlineServices::OnAutoConnectToEmptyServer(), UIScriptedMenu::OnClick(), ScriptedWidgetEventHandler::OnClick(), UIScriptedMenu::OnClick_Respawn(), ActionUnfoldMapCB::OnFinish(), BiosUserManager::OnGameNameChanged(), UIScriptedMenu::OnHide(), MissionBase::OnInit(), BiosUserManager::OnJoin(), OnLoginTimeEvent(), MissionBase::OnMissionFinish(), UIScriptedMenu::OnModalResult(), UIScriptedMenu::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnMouseEnter(), OptionSelectorBase::OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), OptionSelectorBase::OnMouseLeave(), BiosUserManager::OnPartyHost(), ManBase::OnPlayerLoaded(), OnRespawnEvent(), UIScriptedMenu::OnShow(), ActionReadPaperCB::OnStateChange(), ActionWritePaperCB::OnStateChange(), ManBase::OnUnconsciousStop(), InventoryItem::OnVariablesSynchronized(), UIScriptedMenu::OpenMenu(), ActionUnfoldMapCB::PerformMapChange(), UIScriptedMenu::Play(), PluginBase::PlayPause(), Hud::RefreshQuickbar(), PluginBase::ReleaseFocus(), ReleaseFocus(), PluginBase::Save(), Dispatcher::SceneEditorCommand(), Dispatcher::ScriptConsoleAddPrint(), Dispatcher::ScriptConsoleGetSelectedItem(), Dispatcher::ScriptConsoleHistoryBack(), Dispatcher::ScriptConsoleHistoryForward(), SelectGamepad(), ScriptedWidgetEventHandler::SelectPlayer(), SetDatabaseID(), PluginBase::SetDeveloperItemClientEx(), DayZPlayer::ShowDeadScreen(), ManBase::ShowUnconsciousScreen(), PluginBase::SpawnFromClipboard(), UIScriptedMenu::Stop(), UIScriptedMenu::StopVideo(), PluginBase::ToggleCameraTools(), PluginBase::ToggleFocus(), UIMenuPanel::UnlockControls(), Update(), UIScriptedMenu::Update(), ActionManagerClient::Update(), UpdateInputDeviceDisconnectWarning(), EntityAI::UpdateInventoryMenu(), and UpdateLoginQueue().
GetUpdateQueue() [1/2]
override ScriptInvoker GetUpdateQueue (int call_category) inline private
Definition at line 1158 of file DayZGame.c.
Referenced by ScriptedWidgetEventHandler::ContinuousActionProgress(), Init(), PluginManager::Init(), ScriptedWidgetEventHandler::ItemActionsWidget(), MainMenuButtonEffect::MainMenuButtonEffect(), UIPopupScript::OnClose(), PluginBase::OnDestroy(), PluginBase::OnInit(), UIPopupScript::OnOpen(), OnUpdate(), ScriptedWidgetEventHandler::ProjectedCrosshair(), RadialProgressBar::RadialProgressBar(), SoftSkillManagerDebug(), ScriptedWidgetEventHandler::~ContinuousActionProgress(), ScriptedWidgetEventHandler::~ItemActionsWidget(), MainMenuButtonEffect::~MainMenuButtonEffect(), PluginManager::~PluginManager(), ScriptedWidgetEventHandler::~ProjectedCrosshair(), RadialProgressBar::~RadialProgressBar(), ~SoftSkillManagerDebug(), UIPopupScript::~UIPopupScriptSceneManager(), and UIPopupScript::~UIPopupScriptSceneSettings().
GetUpdateQueue() [2/2]
ScriptInvoker GetUpdateQueue (int call_category) inline private
Definition at line 1351 of file Game.c.
GetUserFOV()
float GetUserFOV () inline private
Definition at line 3505 of file DayZGame.c.
References m_UserFOV.
Referenced by GetFOVByZoomType().
GetUserFOVFromConfig()
static float GetUserFOVFromConfig () inline static private
Definition at line 3510 of file DayZGame.c.
References Class::CastTo(), and GameOptions::GetOptionByType().
Referenced by DeferredInit(), and SelectGamepad().
GetUserManager()
proto native BiosUserManager GetUserManager () private
Referenced by UIScriptedMenu::ChangeAccount(), ConnectLaunch(), CreateTitleScreen(), DisconnectSessionEx(), GamepadCheck(), OnlineServices::GetClientServices(), DayZIntroScene::GetSelectedUserName(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::IsLocalPlayer(), UIScriptedMenu::IsLocalPlayer(), JoinLaunch(), MissionLaunch(), OnEvent(), OnLoginTimeEvent(), PartyLaunch(), UIScriptedMenu::Refresh(), SelectGamepad(), SelectUser(), Managed::SetupPlayerName(), and DayZIntroSceneXbox::UpdateSelectedUserName().
GetVersion()
proto void GetVersion (out string version) private
Referenced by UIScriptedMenu::Init(), UIScriptedMenu::Refresh(), and UIScriptedMenu::SetGameVersion().
GetVoiceLevel()
proto native int GetVoiceLevel (Object player = null) private
Get voice level of VoN (on both client and server) (VoiceLevelWhisper = 0, VoiceLevelNormal = 1, VoiceLevelShout = 2)
Referenced by DayZPlayer::CommandHandler(), HandleInput(), OnEvent(), and MissionBase::ShowChat().
GetWaterDepth()
proto native float GetWaterDepth (vector posWS) private
GetWeather()
proto native Weather GetWeather () private
Returns weather controller object.
Referenced by ItemBase::CheckRainTick(), Cooling(), RainProcurementHandler::DetermineAmountCoef(), Heating(), ItemBase::Init(), InitValues(), IsWindy(), UIPopupScript::OnChange(), UIPopupScript::OnClick(), UIPopupScript::OnClose(), UIPopupScript::OnOpen(), OnRPC(), OnUndergroundPresenceUpdate(), RainProcurementManager::RainProcurementCheck(), UIPopupScript::ResetSliders(), SceneData::SetInitFog(), SceneData::SetInitOvercast(), SceneData::SetInitRain(), SceneData::SetInitWindForce(), Update(), and ~UndergroundHandlerClient().
GetWorkspace()
proto native WorkspaceWidget GetWorkspace () private
Referenced by AddAgent(), ScriptedWidgetEventHandler::AddItem(), AddModifier(), NotificationUI::AddNotification(), array::AddSubgroup(), ScriptedWidgetEventHandler::AddSubgroup(), ScriptedWidgetEventHandler::AddTab(), HudDebugWinBase::AddValue(), NotificationUI::AddVoiceNotification(), ChatLine::ChatLine(), ServerBrowserTab::Construct(), PluginBase::CreateModuleWidgets(), CreateModuleWidgets(), CreateTitleScreen(), PluginBase::CreateWidgetOverlay(), CreditsElement::CreditsDepartmentElement(), CreditsDepartmentSection(), CTObjectFollower::CTActor(), ScriptedWidgetEventHandler::CTEvent(), ScriptedWidgetEventHandler::CTKeyframe(), DebugMonitor::DebugMonitor(), ScriptedWidgetEventHandler::DropdownPrefab(), GameplayEffectWidgets_base::GameplayEffectWidgets(), ScriptedWidgetEventHandler::GenerateQuickBarBackgroundTiles(), HitDirectionImagesBase::GetCurrentImageData(), Init(), LoginScreenBase::Init(), UIScriptedMenu::Init(), UIScriptedWindow::Init(), ScriptedWidgetEventHandler::Init(), Debug::InitCanvas(), InitializeWidgets(), InitWidgets(), PluginBase::InitWidgets(), ItemManager::ItemManager(), ScriptedWidgetEventHandler::KeybindingElement(), ScriptedWidgetEventHandler::KeybindingElementNew(), array::KeybindingsContainer(), ScriptedWidgetEventHandler::KeybindingsGroup(), ScriptedWidgetEventHandler::LayoutHolder(), ScriptedWidgetEventHandler::ModsMenuDetailed(), ScriptedWidgetEventHandler::ModsMenuDetailedEntry(), ScriptedWidgetEventHandler::ModsMenuSimple(), ScriptedWidgetEventHandler::ModsMenuTooltip(), NotificationUI::NotificationUI(), OnClick(), MissionBase::OnInit(), OptionSelectorBase::OptionSelector(), OptionSelectorBase::OptionSelectorEditbox(), OptionSelectorSliderSetup::OptionSelectorLevelMarker(), OptionSelectorSliderSetup::OptionSelectorSlider(), ScriptedWidgetEventHandler::OptionsMenuControls(), ScriptedWidgetEventHandler::OptionsMenuGame(), ScriptedWidgetEventHandler::OptionsMenuSounds(), ScriptedWidgetEventHandler::OptionsMenuVideo(), ScriptedWidgetEventHandler::PlayerListEntryScriptedWidget(), ScriptedWidgetEventHandler::PlayerListScriptedWidget(), Refresh(), GameplayEffectWidgets_base::RegisterLayouts(), ScriptedWidgetEventHandler::ServerBrowserEntry(), Hud::ShowPlayerTag(), SoftSkillManagerDebug(), ScriptedWidgetEventHandler::TutorialKeybinds(), and UIPropertyAttachment::UIPropertyAttachment().
GetWorld()
proto native World GetWorld () private
Referenced by PPEClassBase::CreateMaterial(), SyncPlayerList::CreatePlayerList(), DayZPlayer::DayZPlayerImplement(), ItemBase::FullyBuild(), GetAlarmInMin(), DayZPlayer::HandleDeath(), PluginBase::HandleSetTime(), PPEffects::Init(), UIScriptedMenu::Init(), PluginConfigHandler::LoadSceneSettings(), UIPopupScript::OnChange(), UIPopupScript::OnClick(), UIPopupScript::OnClose(), OnEvent(), ObjectSpawnerHandler::OnGameplayDataHandlerLoad(), OnlineServices::OnLoadVoicePrivilege(), UIPopupScript::OnOpen(), OnUndergroundPresenceUpdate(), AlarmClock_ColorBase::OnUpdate(), ScriptedWidgetEventHandler::OptionsMenuControls(), OrderedPositionNumbersFromGridCoords(), ProcessLighting(), ProcessSound(), UIScriptedMenu::Refresh(), UIPopupScript::ResetSliders(), SetAlarmInXMins(), PPEffects::SetBlur(), WorldLighting::SetGlobalLighting(), SceneData::SetInitDay(), SceneData::SetInitHour(), SceneData::SetInitMinute(), SceneData::SetInitMonth(), SceneData::SetInitYear(), PPEffects::SetNVParams(), MissionBase::TickScheduler(), UndergroundHandlerClient(), WorldData::UpdateBaseEnvTemperature(), UIScriptedMenu::UpdateTime(), WorldData::WeatherOnBeforeChange(), and ~UndergroundHandlerClient().
GetWorldDirectionFromScreen()
proto native vector GetWorldDirectionFromScreen (vector world_pos) private
Transforms position in world to position in screen in pixels as x, y component of vector, z parameter represents distance between camera and world_pos.
GetWorldName() [1/2]
string GetWorldName () inline private
Definition at line 800 of file Game.c.
References g_Game.
GetWorldName() [2/2]
proto void GetWorldName (out string world_name) private
Referenced by EffectAreaLoader::CreateZones(), UndergroundAreaLoader::GetData(), MissionBaseWorld::InitialiseWorldData(), InventoryItemSuper::InitMapState(), and CfgGameplayHandler::LoadData().
GlobalsInit()
void GlobalsInit () inline private
Definition at line 1081 of file DayZGame.c.
References GetCEApi(), MIN, and ObjectSpawnerHandler::OnGameplayDataHandlerLoad().
GoBuyWorldDLC()
proto native bool GoBuyWorldDLC (string sWorldName) private
HasInventoryJunctureDestination()
proto native bool HasInventoryJunctureDestination (Man player, notnull InventoryLocation dst) private
Referenced by ManBase::CreateCopyOfItemInInventory().
HasInventoryJunctureItem()
proto native bool HasInventoryJunctureItem (notnull EntityAI item) private
InitCharacterMenuDataInfo()
void InitCharacterMenuDataInfo (int menudata_count) inline private
Definition at line 3469 of file DayZGame.c.
InitDamageEffects()
proto native void InitDamageEffects (Object effect) private
Initialization of damage effects.
InitNotifications()
void InitNotifications () inline private
Definition at line 2035 of file DayZGame.c.
References NotificationSystem::InitInstance().
Referenced by OnInitialize().
IsAimLogEnabled()
bool IsAimLogEnabled () inline private
Definition at line 1268 of file DayZGame.c.
References m_AimLoggingEnabled.
IsBoxColliding()
proto native bool IsBoxColliding (vector center, vector orientation, vector edgeLength, array< Object > excludeObjects, array< Object > collidedObjects = NULL) private
Finds all objects that are in choosen oriented bounding box (OBB)
Parameters
center vector, center of OBB
orientation vector, direction (front vector), used for calculation of OBB rotation
edgeLength vector, sizes of whole box
excludeObjects array<Object>, objects that should be excluded from collision check
collidedObjects array<Object>, out parameter, objects that collided with OBB
Returns
bool, true if at least one object collided with OBB, false otherwise
Note
Object that doesn't have collision geometry will be ignored, as this only uses geometry
vector pos = GetPosition();
vector orientation = GetOrientation();
vector size = "10 4 8";
array<Object> excluded_objects = new array<Object>;
excluded_objects.Insert(this);
array<Object> nearby_objects = new array<Object>;
if(GetGame().IsBoxColliding(pos, orientation, size, excluded_objects, nearby_objects))
{
    for (int i = 0, c = nearby_objects.Count(); i < c; ++i)
    {
        PrintString("object " + i.ToString());
    }
}
Referenced by EntityAI::IsAreaAtDoorFree().
IsBoxCollidingGeometry()
proto native bool IsBoxCollidingGeometry (vector center, vector orientation, vector edgeLength, int iPrimaryType, int iSecondaryType, array< Object > excludeObjects, array< Object > collidedObjects = NULL) private
Finds all objects with geometry iType that are in choosen oriented bounding box (OBB)
Parameters
center vector, center of OBB
orientation vector, direction (front vector), used for calculation of OBB rotation
edgeLength vector, sizes of whole box
iPrimaryType int, type of intersection, possible values ObjIntersectFire(0), ObjIntersectView(1), ObjIntersectGeom(2), ObjIntersectIFire(3), ObjIntersectNone(4)
iSecondaryType int, type of intersection, possible values ObjIntersectFire(0), ObjIntersectView(1), ObjIntersectGeom(2), ObjIntersectIFire(3), ObjIntersectNone(4)
excludeObjects array<Object>, objects that should be excluded from collision check
collidedObjects array<Object>, out parameter, objects that collided with OBB
Returns
bool, true if at least one object collided with OBB, false otherwise
vector pos = GetPosition();
vector orientation = GetOrientation();
vector size = "10 4 8";
array<Object> excluded_objects = new array<Object>;
excluded_objects.Insert(this);
array<Object> nearby_objects = new array<Object>;
if(GetGame().IsBoxCollidingGeometry(pos, orientation, size, ObjIntersectView, ObjIntersectGeom, excluded_objects, nearby_objects))
{
    for (int i = 0, c = nearby_objects.Count(); i < c; ++i)
    {
        PrintString("object " + i.ToString());
    }
}
Referenced by Hologram::IsCollidingBBox(), and BaseBuildingBase::PerformRoofCheckForBase().
IsBoxCollidingGeometryProxy()
proto native bool IsBoxCollidingGeometryProxy (notnull BoxCollidingParams params, array< Object > excludeObjects, array< ref BoxCollidingResult > collidedObjects = NULL) private
IsClient()
proto native bool IsClient () private
Referenced by ActionDeployHuntingTrap::ActionConditionContinue().
IsConnecting()
bool IsConnecting () inline private
Definition at line 3176 of file DayZGame.c.
References m_IsConnecting.
IsDebug()
proto native bool IsDebug () private
IsDebugMonitor()
bool IsDebugMonitor () inline private
Definition at line 1026 of file Game.c.
References IsServer(), and m_DebugMonitorEnabled.
IsDedicatedServer()
proto native bool IsDedicatedServer () private
Robust check which is preferred than the above, as it is valid much sooner.
Note
You may want to use #ifdef SERVER instead for slight performance gain...
Referenced by BuildCondition(), CGame(), RecoilBase::PostInit(), and DayZPlayer::ProcessWeaponEvent().
IsDigitalCopy()
static bool IsDigitalCopy () inline static private
Definition at line 1010 of file Game.c.
References OnlineServices::IsGameActive().
IsFoodDecayEnabled()
bool IsFoodDecayEnabled () inline private
Definition at line 3604 of file DayZGame.c.
References GetFoodDecayModifier().
IsInPartyChat()
proto native bool IsInPartyChat () private
Returns whether user is currently in a voice party (currently only supported on xbox)
Referenced by ScriptedWidgetEventHandler::OptionsMenuSounds().
IsInventoryOpen() [1/2]
override bool IsInventoryOpen () inline private
Definition at line 1304 of file DayZGame.c.
References GetUIManager(), and MENU_INVENTORY.
IsInventoryOpen() [2/2]
bool IsInventoryOpen () inline private
Definition at line 1377 of file Game.c.
IsKindOf()
bool IsKindOf (string cfg_class_name, string cfg_parent_name) inline private
Returns is class name inherited from parent class name.
Parameters
cfg_class_name Config Class name ("Animal_CervusElaphus")
cfg_parent_name Parent Config Class name ("DZ_LightAI")
Returns
bool is class name inherited from parent class name
bool is_kind = GetGame().IsKindOf("Animal_CervusElaphus", "DZ_LightAI");
PrintString(ToString(is_kind));
>> 1
Definition at line 1238 of file Game.c.
References ConfigGetFullPath(), and string::ToLower().
Referenced by DayZGame(), SceneObject::Init(), ManBase::SpawnAI(), and ManBase::SpawnEntityOnGroundPos().
IsLeftCtrlDown()
bool IsLeftCtrlDown () inline private
Definition at line 2656 of file DayZGame.c.
References m_IsCtrlHolding.
IsLoading()
bool IsLoading () inline private
Definition at line 3182 of file DayZGame.c.
Referenced by LoadingHide().
IsMicCapturing()
proto native bool IsMicCapturing () private
Returns whether mic is currently capturing audio from user.
Referenced by ScriptedWidgetEventHandler::OptionsMenuSounds().
IsMissionMainMenu()
bool IsMissionMainMenu () inline private
Returns true when current mission is Main Menu.
Definition at line 1387 of file Game.c.
References DayZGame(), and g_Game.
IsMultiplayer()
proto native bool IsMultiplayer () private
Referenced by ejectBulletAndStoreInMagazine(), GUIAction_SetValue(), Debug::LogMessage(), WeaponStateBase::OnEntry(), ActionActivateTrap::OnFinishProgressServer(), and OnUpdate().
IsNewCharacter()
bool IsNewCharacter () inline private
Definition at line 3489 of file DayZGame.c.
References m_IsNewCharacter.
IsObjectAccesible()
proto native bool IsObjectAccesible (EntityAI item, Man player) private
returns true if player can access item's cargo/attachments (check only distance)
IsPhysicsExtrapolationEnabled()
proto native bool IsPhysicsExtrapolationEnabled () private
If physics extrapolation is enabled, always true on retail release builds.
Referenced by DayZPlayerCamera1stPerson::OnUpdate(), and OnUpdate().
IsServer()
proto native bool IsServer () private
Referenced by CloseCombatEffects(), ejectBulletAndStoreInMagazine(), ExplosionEffectsEx(), FirearmEffects(), ItemBase::GardenBase(), ItemBase::GrowthTimerTick(), IsDebugMonitor(), Debug::LogMessage(), WeaponStateBase::OnEntry(), InventoryItemSuper::SyncMapMarkers(), and EnProfilerTests::TestFuncCountData().
IsStressTest()
bool IsStressTest () inline private
Definition at line 1263 of file DayZGame.c.
References m_IsStressTest.
IsSurfaceDigable()
bool IsSurfaceDigable (string surface) inline private
Checks if the surface is digable.
Definition at line 1087 of file Game.c.
References ConfigGetInt().
Referenced by Inventory_Base::CanBeFilledAtPosition(), GetEmptyingEndSoundset(), GetEmptyingLoopSoundset(), ItemBase::IsPlaceableAtPosition(), and FlammableBase::StandUp().
IsSurfaceFertile()
bool IsSurfaceFertile (string surface) inline private
Checks if the surface is fertile.
Definition at line 1093 of file Game.c.
References ConfigGetInt().
Referenced by GardenBase::CanBePlaced().
IsVisited()
bool IsVisited (string ip, int port) inline private
Definition at line 2518 of file DayZGame.c.
IsWorldWetTempUpdateEnabled()
bool IsWorldWetTempUpdateEnabled () inline private
Definition at line 3599 of file DayZGame.c.
References m_IsWorldWetTempUpdateEnabled.
JoinLaunch()
void JoinLaunch () inline private
Definition at line 2135 of file DayZGame.c.
References GetCLIParam(), GetUserManager(), BiosUserManager::ParseJoinAsync(), SetGameState(), and SetLoadState().
Referenced by OnInitialize().
ListAvailableCharacters() [1/2]
override TStringArray ListAvailableCharacters () inline private
Definition at line 3236 of file DayZGame.c.
References m_CharClassNames.
Referenced by Managed::LoadCharacterData().
ListAvailableCharacters() [2/2]
TStringArray ListAvailableCharacters () inline private
outputs array of all valid survivor class names
Definition at line 1375 of file Game.c.
LoadingHide()
void LoadingHide (bool force = false) inline private
Definition at line 3202 of file DayZGame.c.
References PPEManagerStatic::GetPPEManager(), IsLoading(), and UpdateInputDeviceDisconnectWarning().
Referenced by OnEvent().
LoadingShow()
void LoadingShow () inline private
Definition at line 3194 of file DayZGame.c.
Referenced by OnEvent().
LoadProgressUpdate()
void LoadProgressUpdate (int progressState, float progress, string title) inline private
Definition at line 1932 of file DayZGame.c.
References GetUIManager(), PROGRESS_FINISH, PROGRESS_PROGRESS, PROGRESS_START, PROGRESS_UPDATE, and UIManager::ScreenFadeOut().
Referenced by OnEvent().
LoadVersion()
proto native int LoadVersion () private
Returns actual storage version - loading.
LoginTimeCountdown()
void LoginTimeCountdown () inline private
Definition at line 1832 of file DayZGame.c.
References CancelLoginTimeCountdown().
LogoutRequestCancel()
proto native void LogoutRequestCancel () private
Referenced by UIScriptedMenu::Cancel().
LogoutRequestTime()
proto native void LogoutRequestTime () private
Logout methods.
Referenced by UIScriptedMenu::OnClick_Exit(), and UIScriptedMenu::OnModalResult().
MainMenuLaunch()
void MainMenuLaunch () inline private
Definition at line 2185 of file DayZGame.c.
References DeleteTitleScreen(), GetMainMenuWorld(), SetGameState(), SetLoadState(), and StartRandomCutscene().
Referenced by DisconnectSessionEx(), and OnInitialize().
MissionLaunch()
void MissionLaunch () inline private
Definition at line 2193 of file DayZGame.c.
References CreateTitleScreen(), GamepadCheck(), GetCLIParam(), BiosUserManager::GetTitleInitiator(), GetUserManager(), mission, PlayMission(), BiosUserManager::SelectUserEx(), SetGameState(), and SetLoadState().
Referenced by OnInitialize().
MuteAllPlayers()
proto native void MuteAllPlayers (string listenerId, bool mute) private
Mute all players for listenerId.
Parameters
listenerId uid of player
mute true, if player can not listen anybody. Otherwise false.
MutePlayer()
proto native void MutePlayer (string muteUID, string playerUID, bool mute) private
Mutes voice of source player to target player.
Parameters
muteUID uid of player you want to mute
playerUID uid of player that (doesnt't) want to hear muteUID
Referenced by ManBase::OnInputUserDataProcess(), and OnRPC().
NightVissionLightParams()
proto native void NightVissionLightParams (float lightIntensityMul, float noiseIntensity) private
set night vission parameters (set to zero when to disable it)
Parameters
lightIntensityMul multiplicator of lights intensity
noiseIntensity intensity of noise PP
ObjectDelete()
proto native void ObjectDelete (Object obj) private
Referenced by HandActionBase::Action(), PMTPlayback::CheckOnePlayingSA(), PMTPlayback::CheckStop(), ManBase::ClearInventory(), ItemBase::CreatePlant(), DayZIntroScene::DayZIntroScene(), EntityLightSource::DeleteLightNow(), DeleteTrigger(), ItemBase::DestroyClutterCutter(), FireplaceBase::DestroyClutterCutter(), DestroyCollisionTrigger(), ItemBase::DestroyConstruction(), ItemBase::DestroyConstructionKit(), DestroyDamageTriggerEx(), ItemBase::DestroyFireplace(), ScriptedWidgetEventHandler::DestroyFollowedObject(), DestroyLock(), DestroyMaterialsServer(), EffectArea::EEDelete(), GardenBase::EEDelete(), ItemBase::EEDelete(), FlammableBase::EEDelete(), EEDelete(), Inventory_Base::EmptySeedPack(), GameInventory::LocalDestroyEntity(), UIPropertyAttachment::OnClick(), ActionBaseCB::OnFinish(), OnFinishProgressServer(), ActionSkinning::OnFinishProgressServer(), GardenBase::OnPlacementComplete(), ItemBase::OnStoreSave(), ItemBase::OnWorkStop(), FlammableBase::OnWorkStop(), PlayerSyncDelete(), SceneObject::RemoveAttachment(), ItemBase::RemoveSlot(), CTObjectFollower::SetHandsItem(), ItemBase::SoundBuzzLoopStop(), TakeMaterialsServer(), FlammableBase::TryTransformIntoStick(), ValidateDestroy(), DayZIntroSceneXbox::~DayZIntroSceneXbox(), Hologram::~Hologram(), and SceneObject::~SceneObject().
ObjectDeleteOnClient()
proto native void ObjectDeleteOnClient (Object obj) private
ObjectGetDisplayName()
proto void ObjectGetDisplayName (Object obj, out string name) private
Referenced by IEntity::GetDisplayName().
ObjectGetSelectionPosition()
proto native vector ObjectGetSelectionPosition (Object obj, string name) private
Referenced by IEntity::GetSelectionPositionOld().
ObjectGetSelectionPositionLS()
proto native vector ObjectGetSelectionPositionLS (Object obj, string name) private
Referenced by IEntity::GetSelectionPositionLS().
ObjectGetSelectionPositionMS()
proto native vector ObjectGetSelectionPositionMS (Object obj, string name) private
Referenced by IEntity::GetSelectionPositionMS().
ObjectGetSelectionPositionWS()
proto native vector ObjectGetSelectionPositionWS (Object obj, string name) private
Referenced by IEntity::GetSelectionPositionWS().
ObjectGetType()
proto void ObjectGetType (Object obj, out string type) private
Referenced by ManBase::GetPlayerClass(), and IEntity::GetType().
ObjectIsKindOf()
bool ObjectIsKindOf (Object object, string cfg_parent_name) inline private
Returns is object inherited from parent class name.
Parameters
object Object
cfg_parent_name Parent Config Class name ("DZ_LightAI")
Returns
bool is object inherited from parent class name
bool is_kind = GetGame().IsKindOf(my_animal, "DZ_LightAI");
PrintString(ToString(is_kind));
>> 1
Definition at line 1290 of file Game.c.
References ConfigGetObjectFullPath(), and string::ToLower().
Referenced by IEntity::IsKindOf().
ObjectModelToWorld()
proto native vector ObjectModelToWorld (Object obj, vector modelPos) private
Referenced by DropNonUsableMaterialsServer(), IEntity::ModelToWorld(), and StaticConstructionMethods::SpawnConstructionMaterialPiles().
ObjectRelease()
proto native int ObjectRelease (Object obj) private
RemoteObjectTreeCreate - postponed registration of network object tree (and creation of remote objects). do not use if not sure what you do.
Referenced by IEntity::Release().
ObjectWorldToModel()
proto native vector ObjectWorldToModel (Object obj, vector worldPos) private
Referenced by IEntity::WorldToModel().
OnActivateMessage() [1/2]
override void OnActivateMessage () inline private
Definition at line 1980 of file DayZGame.c.
OnActivateMessage() [2/2]
void OnActivateMessage () inline private
Called when recieving focus (windows)
Definition at line 107 of file Game.c.
OnAfterCreate() [1/2]
override void OnAfterCreate () inline private
Definition at line 1974 of file DayZGame.c.
References Math::Randomize().
OnAfterCreate() [2/2]
void OnAfterCreate () inline private
Called after creating of CGame instance.
Definition at line 100 of file Game.c.
OnConnectivityStatChange()
protected bool OnConnectivityStatChange (EConnectivityStatType type, EConnectivityStatLevel newLevel, EConnectivityStatLevel oldLevel) inline private
Definition at line 1706 of file DayZGame.c.
References GetGame(), Mission::GetHud(), GetMission(), and Hud::SetConnectivityStatIcon().
Referenced by SetConnectivityStatState().
OnDeactivateMessage() [1/2]
override void OnDeactivateMessage () inline private
Definition at line 1985 of file DayZGame.c.
OnDeactivateMessage() [2/2]
void OnDeactivateMessage () inline private
Called when loosing focus (windows)
Definition at line 114 of file Game.c.
OnDeviceReset() [1/2]
override void OnDeviceReset () inline private
Definition at line 2756 of file DayZGame.c.
OnDeviceReset() [2/2]
void OnDeviceReset () inline private
Called when inputs is not possible (Steam overlay active or something), all internal script variables should be reset here!
Definition at line 129 of file Game.c.
OnEvent() [1/2]
override void OnEvent (EventType eventTypeId, Param params) inline private
Definition at line 1391 of file DayZGame.c.
References AbortMission(), AddVisitedServer(), ScriptCallQueue::Call(), CALL_CATEGORY_GUI, CALL_CATEGORY_SYSTEM, CancelLoginQueue(), CancelLoginTimeCountdown(), Class::CastTo(), ChatMessageEventTypeID, ClearConnectivityStates(), OnlineServices::ClearCurrentServerInfo(), ConnectingAbortEventTypeID, ConnectingStartEventTypeID, ConnectivityStatsUpdatedEventTypeID, ProgressAsync::DestroyAllPendingProgresses(), DialogQueuedEventTypeID, DLCOwnerShipFailedEventTypeID, OnlineServices::EnterGameplaySession(), g_Game, GetCallQueue(), GetGameState(), GetHostAddress(), ErrorModuleHandler::GetInstance(), VONManager::GetInstance(), GetMission(), PlayerIdentityBase::GetPingAvg(), GetPlayer(), GetUserManager(), GetWorld(), OnlineServices::LeaveGameplaySession(), string::Length(), LoadingHide(), LoadingShow(), LoadProgressUpdate(), OnlineServices::LoadVoicePrivilege(), LoginStatusEventTypeID, LoginTimeEventTypeID, LogoutEventTypeID, StatsEventDisconnectedData::m_CharacterId, StatsEventSpawnedData::m_CharacterId, StatsEventSpawnedData::m_DaytimeHour, StatsEventSpawnedData::m_Lifetime, StatsEventSpawnedData::m_Population, StatsEventSpawnedData::m_Position, StatsEventDisconnectedData::m_Reason, mission, MPConnectionLostEventTypeID, MPSessionEndEventTypeID, MPSessionFailEventTypeID, MPSessionPlayerReadyEventTypeID, MPSessionStartEventTypeID, Mission::OnEvent(), ErrorModuleHandler::OnEvent(), VONManagerBase::OnEvent(), OnLoginTimeEvent(), OnMPConnectionLostEvent(), OnPreloadEvent(), OnRespawnEvent(), ParticleManager(), Analytics::PlayerDisconnected(), Analytics::PlayerSpawned(), PreloadEventTypeID, Print(), ProgressEventTypeID, ClientData::ResetClientData(), RespawnEventTypeID, ServerFpsStatsUpdatedEventTypeID, SetConnecting(), SetConnectivityStatState(), SetGameState(), SetLoadState(), OnlineServices::SetMultiplayState(), StartupEventTypeID, UpdateInputDeviceDisconnectWarning(), WorldCleaupEventTypeID, and vector::Zero.
OnEvent() [2/2]
void OnEvent (EventType eventTypeId, Param params) inline private
Called when some system event occur.
Parameters
eventTypeId event type.
params Param object, cast to specific param class to get parameters for particular event.
Definition at line 82 of file Game.c.
OnGameplayDataHandlerLoad()
void OnGameplayDataHandlerLoad () inline private
Definition at line 1179 of file DayZGame.c.
OnInitialize() [1/2]
override bool OnInitialize () inline private
Definition at line 1990 of file DayZGame.c.
References ConnectLaunch(), CreateTitleScreen(), GetCLIParam(), GetHUDBrightnessSetting(), GetLoadState(), GetProfileStringList(), InitNotifications(), JoinLaunch(), MainMenuLaunch(), MissionLaunch(), PartyLaunch(), ParticleList::PreloadParticles(), RegisterProfilesOptions(), and SetHudBrightness().
OnInitialize() [2/2]
bool OnInitialize () inline private
Called once before game update loop starts, ret value indicates if init was done in scripts, otherwise it is done in the engine.
Definition at line 121 of file Game.c.
OnKeyPress() [1/2]
override void OnKeyPress (int key) inline private
Definition at line 2662 of file DayZGame.c.
References GetMission(), mission, UIScriptedMenu::OnKeyDown(), Mission::OnKeyPress(), and RequestExit().
OnKeyPress() [2/2]
void OnKeyPress (int key) inline private
Called when key is pressed.
Parameters
key direct input key code (DIK)
Definition at line 155 of file Game.c.
OnKeyRelease() [1/2]
override void OnKeyRelease (int key) inline private
Definition at line 2701 of file DayZGame.c.
References GetMission(), mission, Mission::OnKeyRelease(), and UIScriptedMenu::OnKeyUp().
OnKeyRelease() [2/2]
void OnKeyRelease (int key) inline private
Called when key is released.
Parameters
key direct input key code (DIK)
Definition at line 163 of file Game.c.
OnLicenseChanged()
void OnLicenseChanged () inline private
Definition at line 92 of file Game.c.
OnLoginTimeEvent()
void OnLoginTimeEvent (int loginTime) inline private
Definition at line 1794 of file DayZGame.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CancelLoginQueue(), UIManager::CloseAll(), EnterLoginTime(), GetCallQueue(), UIManager::GetMenu(), GetMission(), GetUIManager(), BiosUserManager::GetUserDatabaseIdAsync(), GetUserManager(), UIScriptedMenu::SetTime(), and UIManager::ShowScriptedMenu().
Referenced by OnEvent().
OnMouseButtonPress() [1/2]
override void OnMouseButtonPress (int button) inline private
Definition at line 2736 of file DayZGame.c.
References GetMission(), mission, and Mission::OnMouseButtonPress().
OnMouseButtonPress() [2/2]
void OnMouseButtonPress (int button) inline private
Called when mouse button is pressed.
Parameters
button - number of button Mouse API
Definition at line 171 of file Game.c.
OnMouseButtonRelease() [1/2]
override void OnMouseButtonRelease (int button) inline private
Definition at line 2746 of file DayZGame.c.
References GetMission(), mission, and Mission::OnMouseButtonRelease().
OnMouseButtonRelease() [2/2]
void OnMouseButtonRelease (int button) inline private
Called when mouse button is released.
Parameters
button - number of button Mouse API
Definition at line 179 of file Game.c.
OnMPConnectionLostEvent()
void OnMPConnectionLostEvent (int duration) inline private
Definition at line 1911 of file DayZGame.c.
References GetGameState(), SetConnectivityStatState(), and OnlineServices::SetMultiplayState().
Referenced by OnEvent().
OnPostUpdate() [1/2]
override void OnPostUpdate (bool doSim, float timeslice) inline private
Definition at line 2848 of file DayZGame.c.
References CALL_CATEGORY_GAMEPLAY, CALL_CATEGORY_GUI, CALL_CATEGORY_SYSTEM, GetMission(), GetPostUpdateQueue(), ScriptInvoker::Invoke(), Mission::IsPaused(), and mission.
OnPostUpdate() [2/2]
void OnPostUpdate (bool doSim, float timeslice) inline private
Called on World update after simulation of entities.
Parameters
doSim False when simulation is paused, True otherwise
timeslice time elapsed from last call
Definition at line 147 of file Game.c.
OnPreloadEvent()
void OnPreloadEvent (vector pos) inline private
Definition at line 1877 of file DayZGame.c.
References CancelLoginTimeCountdown(), and StoreLoginDataPrepare().
Referenced by OnEvent().
OnProcessLifetimeChanged()
void OnProcessLifetimeChanged (int plmtype) inline private
Definition at line 87 of file Game.c.
OnProjectileStopped()
void OnProjectileStopped (ProjectileStoppedInfo info) inline private
Definition at line 3287 of file DayZGame.c.
References ConfigGetText(), CreateObjectEx(), ECE_DYNAMIC_PERSISTENCY, ProjectileStoppedInfo::GetAmmoType(), GetGame(), and ProjectileStoppedInfo::GetPos().
OnProjectileStoppedInObject()
void OnProjectileStoppedInObject (ObjectCollisionInfo info) inline private
Definition at line 3333 of file DayZGame.c.
References ARROW_PIERCE_DEPTH, ConfigGetText(), CreateObjectEx(), ECE_DYNAMIC_PERSISTENCY, ECE_KEEPHEIGHT, ObjectCollisionInfo::GetComponentIndex(), GetGame(), ObjectCollisionInfo::GetHitObj(), ObjectCollisionInfo::GetHitObjPos(), ObjectCollisionInfo::GetHitObjRot(), and vector::Normalize().
OnProjectileStoppedInTerrain()
void OnProjectileStoppedInTerrain (TerrainCollisionInfo info) inline private
Definition at line 3308 of file DayZGame.c.
References ARROW_PIERCE_DEPTH, ConfigGetText(), CreateObjectEx(), ECE_DYNAMIC_PERSISTENCY, ECE_KEEPHEIGHT, GetGame(), and vector::Normalize().
OnRespawnEvent()
void OnRespawnEvent (int time) inline private
Definition at line 1851 of file DayZGame.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), UIManager::CloseAll(), EnterLoginTime(), GetCallQueue(), UIManager::GetMenu(), GetPlayer(), GetUIManager(), and DayZPlayer::StopDeathDarkeningEffect().
Referenced by OnEvent().
OnRPC() [1/2]
override void OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 2880 of file DayZGame.c.
References NotificationSystem::AddNotification(), NotificationSystem::AddNotificationExtended(), CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), GameConstants::CAMERA_SHAKE_ARTILLERY_DISTANCE, GameConstants::CAMERA_SHAKE_ARTILLERY_DISTANCE2, ParticleList::CONTAMINATED_AREA_GAS_SHELL, DayZPlayerCamera(), vector::DistanceSq(), ErrorEx, GetCallQueue(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), PlayerIdentityBase::GetPlainId(), GetPlayer(), GetPosition, Weather::GetRain(), CrashSoundSets::GetSoundSetByHash(), GetWeather(), Math::InverseLerp(), DebugWeatherRPCData::m_FogDuration, DebugWeatherRPCData::m_FogInterpolation, DebugWeatherRPCData::m_FogValue, DebugWeatherRPCData::m_OvercastDuration, DebugWeatherRPCData::m_OvercastInterpolation, DebugWeatherRPCData::m_OvercastValue, DebugWeatherRPCData::m_RainDuration, DebugWeatherRPCData::m_RainInterpolation, DebugWeatherRPCData::m_RainValue, MutePlayer(), CfgGameplayHandler::OnRPC(), UndergroundAreaLoader::OnRPC(), CachedObjectsParams::PARAM1_INT, ParticleManager(), SEffectManager::PlaySound(), Serializer::Read(), WeatherPhenomenon::Set(), EffectSound::SetAutodestroy(), Math::Sqrt(), and vector::Zero.
OnRPC() [2/2]
void OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx) inline private
Called after remote procedure call is recieved for this object.
Parameters
target object on which remote procedure is called, when NULL, RPC is evaluated by CGame as global
rpc_type user defined identification of RPC
ctx read context for params
Definition at line 199 of file Game.c.
OnUpdate() [1/2]
override void OnUpdate (bool doSim, float timeslice) inline private
Definition at line 2772 of file DayZGame.c.
References CALL_CATEGORY_GAMEPLAY, CALL_CATEGORY_GUI, CALL_CATEGORY_SYSTEM, DiagMenu::GetBool(), GetCallQueue(), GetDragQueue(), GetGame(), GetMission(), PlayerIdentityBase::GetPingAct(), PlayerIdentityBase::GetPingAvg(), GetPlayer(), GetTimerQueue(), GetUpdateQueue(), ScriptInvoker::Invoke(), IsMultiplayer(), Mission::IsPaused(), mission, Mission::OnUpdate(), ScriptCallQueue::Tick(), NotificationSystem::Update(), and UpdateLoginQueue().
OnUpdate() [2/2]
void OnUpdate (bool doSim, float timeslice) inline private
Called on World update.
Parameters
doSim False when simulation is paused, True otherwise
timeslice time elapsed from last call
Definition at line 138 of file Game.c.
OpenURL()
proto native void OpenURL (string url) private
Referenced by ScriptedWidgetEventHandler::OnMouseButtonUp(), ScriptedWidgetEventHandler::OpenDiscord(), ScriptedWidgetEventHandler::OpenDLC(), ScriptedWidgetEventHandler::OpenFeedback(), ScriptedWidgetEventHandler::OpenForums(), ScriptedWidgetEventHandler::OpenTwitter(), and ScriptedWidgetEventHandler::OpenYoutube().
OverrideDOF()
proto native void OverrideDOF (bool enable, float focusDistance, float focusLength, float focusLengthNear, float blur, float focusDepthOffset) private
Referenced by PPEffects::OverrideDOF().
OverrideInventoryLights()
proto native void OverrideInventoryLights (vector diffuse, vector ambient, vector ground, vector dir) private
override inventory light
Parameters
diffuse directional light
ambient ambient light
ground ground light
dir direction of light, Vector(0,0,1) is from camera
PartyLaunch()
void PartyLaunch () inline private
Definition at line 2171 of file DayZGame.c.
References GetCLIParam(), GetGame(), GetMainMenuWorld(), GetUserManager(), BiosUserManager::ParsePartyAsync(), SetGameState(), SetLoadState(), and StartRandomCutscene().
Referenced by OnInitialize().
PlayMission()
proto native void PlayMission (string path) private
Starts mission (equivalent for SQF playMission). You MUST use double slash \.
Referenced by MissionLaunch(), UIScriptedWindow::OnClick(), and SelectGamepad().
PreloadObject()
proto native bool PreloadObject (string type, float distance) private
Preload objects with certain type in certain distance from camera.
Parameters
type of objects which should be preloaded
distance from camera in which objects should be preloaded
Returns
true on success
ProfilerStart()
proto native void ProfilerStart (string name) private
Use for profiling code from start to stop, they must match have same name, look wiki pages for more info: https://confluence.bistudio.com/display/EN/Profiler.
Referenced by DayZPlayerTypeRegisterItems(), DayZPlayerTypeRegisterSounds(), and PluginRecipesManagerBase::GenerateRecipeCache().
ProfilerStop()
proto native void ProfilerStop (string name) private
Use for profiling code from start to stop, they must match have same name, look wiki pages for more info: https://confluence.bistudio.com/display/EN/Profiler.
Referenced by DayZPlayerTypeRegisterItems(), DayZPlayerTypeRegisterSounds(), and PluginRecipesManagerBase::GenerateRecipeCache().
RefreshCurrentServerInfo()
void RefreshCurrentServerInfo () inline private
Definition at line 2525 of file DayZGame.c.
References OnlineServices::GetCurrentServerInfo(), and GetHostAddress().
RegisterNetworkStaticObject()
proto native bool RegisterNetworkStaticObject (Object object) private
Static objects cannot be replicated by default (there are too many objects on the map). Use this method when you want to replicate some scripted variables. Cannot be called in object's constructor, because networking is not initialized yet.
Parameters
object static object to replicate
Returns
false, if registration wasn't successful or when object is already registered
Referenced by Interact(), Land_Underground_Panel_Lever::Interact(), LateInit(), and Land_Underground_EntranceBase::OpenServer().
RegisterProfilesOptions()
void RegisterProfilesOptions () inline private
Definition at line 1101 of file DayZGame.c.
References ADMIN_CHAT_MSG, DIRECT_CHAT_MSG, ENABLE_BLEEDINGINDICATION, GAME_CHAT_MSG, HUD_BRIGHTNESS, PLAYER_CHAT_MSG, RADIO_CHAT_MSG, SHOW_CONNECTIVITYINFO, SHOW_CROSSHAIR, SHOW_HUD, SHOW_QUICKBAR, SHOW_SERVERINFO, and SYSTEM_CHAT_MSG.
Referenced by OnInitialize().
ReloadMission()
void ReloadMission () inline private
Definition at line 1340 of file DayZGame.c.
References CreateMission(), and Print().
RemoteObjectCreate()
proto native void RemoteObjectCreate (Object obj) private
RemoteObjectDelete - deletes only remote object tree (unregisters from network). do not use if not sure what you do.
RemoteObjectDelete()
proto native void RemoteObjectDelete (Object obj) private
RemoteObjectTreeCreate()
proto native void RemoteObjectTreeCreate (Object obj) private
RemoteObjectCreate - postponed registration of network object (and creation of remote object). do not use if not sure what you do.
Referenced by DropEquipAndDestroyRootLambda::CopyOldPropertiesToNew(), ManBase::CreateCopyOfItemInInventory(), ReplaceItemWithNewLambdaBase::CreateNetworkObjectInfo(), CreateNetworkObjectInfo(), TransferInventory(), ReplaceItemWithNewLambdaBase::UndoRemoveNetworkObjectInfo(), and UndoRemoveNetworkObjectInfo().
RemoteObjectTreeDelete()
proto native void RemoteObjectTreeDelete (Object obj) private
RemoteObjectDelete - deletes only remote object (unregisters from network). do not use if not sure what you do.
Referenced by ReplaceItemWithNewLambdaBase::RemoveNetworkObjectInfo(), and RemoveNetworkObjectInfo().
RemoveFromReconnectCache()
proto native void RemoveFromReconnectCache (string uid) private
Remove player from reconnect cache.
Note
Works only on server
Parameters
uid of the player
RemoveVoiceNotification()
void RemoveVoiceNotification (VONStopSpeakingEventParams vonStopParams) inline private
Definition at line 1754 of file DayZGame.c.
ReportModded()
static bool ReportModded () inline static private
Definition at line 1293 of file DayZGame.c.
References m_ReportModded.
RequestExit()
proto native void RequestExit (int code) private
Sets exit code and quits in the right moment.
Referenced by OnKeyPress().
RequestRestart()
proto native void RequestRestart (int code) private
Sets exit code and restart in the right moment.
ResetPPMask()
proto native void ResetPPMask () private
Referenced by PPERequester_GameplayBase::OnStop(), PPEffects::ResetPPMask(), PPERequester_GameplayBase::SetValuesIronsights(), and PPERequester_GameplayBase::SetValuesOptics().
ResetProfileOptions()
void ResetProfileOptions () inline private
Definition at line 1119 of file DayZGame.c.
Referenced by SelectGamepad().
RespawnPlayer()
proto native void RespawnPlayer () private
Referenced by UIScriptedMenu::GameRespawn(), and UIScriptedMenu::GameRetry().
RestartMission()
proto native void RestartMission () private
Referenced by UIScriptedMenu::GameRetry().
RPC()
proto native void RPC (Object target, int rpcType, notnull array< ref Param > params, bool guaranteed, PlayerIdentity recipient = null) private
Initiate remote procedure call. When called on client, RPC is evaluated on server; When called on server, RPC is executed on all clients.
Parameters
target object on which remote procedure is called, when NULL, RPC is evaluated by CGame as global
rpc_type user defined identification of RPC
params custom params array
recipient specified client to send RPC to. If NULL, RPC will be send to all clients (specifying recipient increase security and decrease network traffic)
const int RPC_LOW_BLOOD_PRESSURE_EFFECT = 0;
...
// on server side, after blood pressure of player is low...
Param1<float> p = new Param1<float>(m_blood_pressure);
array<param> params = new array<param>;
params.Insert(p);
GetGame().RPC(player, RPC_LOW_BLOOD_PRESSURE_EFFECT, params);
// or shortcut
GetGame().RPCSingleParam(player, RPC_LOW_BLOOD_PRESSURE_EFFECT, p);
...
// on client
class PlayerBase
{
  // override OnRPC function
  void OnRPC(PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
  {
      // dont forget to propagate this call trough class hierarchy!
      super.OnRPC(rpc_type, ctx);
      switch(rpc_type)
      {
          case RPC_LOW_BLOOD_PRESSURE_EFFECT:
              Param1<float> p = Param1<float>(0);
              if (ctx.Read(p))
              {
                  float blood_pressure = p.param1;
                  float effect_intensity = 1.0 - blood_pressure;
                  ShowFancyScreenEffect(effect_intensity);
              }
          break;
      }
  }
}
Referenced by ContaminatedArea_Dynamic::EEOnCECreate(), ManBase::OnSelectPlayer(), ContaminatedArea_Dynamic::PlayFX(), MissionBase::RandomArtillery(), IEntity::RPC(), RPCSingleParam(), and SendRPC().
RPCSelf()
proto native void RPCSelf (Object target, int rpcType, notnull array< ref Param > params) private
Not actually an RPC, as it will send it only to yourself.
Referenced by RPCSelfSingleParam().
RPCSelfSingleParam()
void RPCSelfSingleParam (Object target, int rpcType, Param param) inline private
Definition at line 889 of file Game.c.
References m_ParamCache, and RPCSelf().
RPCSingleParam()
void RPCSingleParam (Object target, int rpc_type, Param param, bool guaranteed, PlayerIdentity recipient = null) inline private
see CGame.RPC
Definition at line 882 of file Game.c.
References m_ParamCache, and RPC().
Referenced by MissionBase::ControlPersonalLight(), ManBase::DealShock(), Disarm(), FireplaceBase::IsThisIgnitionSuccessful(), OnAnimationEvent(), OnClick(), MissionBase::OnClientReadyEvent(), MissionBase::OnClientRespawnEvent(), ActionActivateTrap::OnEnd(), ActionLockAttachment::OnEnd(), ActionActivateTrap::OnEndAnimationLoop(), OnEndAnimationLoop(), ActionDrainLiquid::OnEndAnimationLoop(), ActionLockAttachment::OnEndAnimationLoop(), ActionPourLiquid::OnEndAnimationLoop(), ActionTransferLiquid::OnEndAnimationLoop(), ActionRepackTent::OnEndAnimationLoop(), ActionEmptyBottleBase::OnEndServer(), ActionCheckPulse::OnExecuteServer(), ActionCheckPulseTarget::OnFinishProgressServer(), ActionRepackTent::OnFinishProgressServer(), ManBase::OnSelectPlayer(), ActionActivateTrap::OnStartAnimationLoop(), OnStartAnimationLoop(), ActionDrainLiquid::OnStartAnimationLoop(), ActionEmptyBottleBase::OnStartAnimationLoop(), ActionLockAttachment::OnStartAnimationLoop(), ActionPourLiquid::OnStartAnimationLoop(), ActionTransferLiquid::OnStartAnimationLoop(), ActionRepackTent::OnStartAnimationLoopServer(), PlantSuper::OnTreeCutDown(), House::RequestSoundEvent(), IEntity::RPCSingleParam(), UIScriptedMenu::RunEnscriptServer(), SceneObject::SceneObjectSynch(), SendMessageToClient(), SendRPC(), SyncEvents::SendSyncEvent(), Managed::SendValue(), DebugMonitorValues::SendValue(), PluginBase::SetDeveloperItemClientEx(), CfgGameplayHandler::SyncDataSend(), UndergroundAreaLoader::SyncDataSend(), CfgGameplayHandler::SyncDataSendEx(), MissionBase::SyncGlobalLighting(), Synch(), SoftSkillsManager::SynchDebugStats(), IEntity::SynchExplosion(), ComponentBodyStaging::SynchSkinnedState(), SoftSkillsManager::SynchSpecialtyLevel(), SymptomBase::SyncToClientActivated(), SymptomBase::SyncToClientDeactivated(), TeleportCheck(), ToggleDebugWindowEvent(), and UIScriptedMenu::Update().
SaveProfile()
proto native void SaveProfile () private
Saves profile on disk.
Referenced by AddVisitedServer(), UIScriptedMenu::Init(), UIScriptedMenu::SaveFavoriteServersConsoles(), ItemManager::SerializeDefaultHeaderOpenStates(), ItemManager::SerializeDefaultOpenStates(), ItemManager::SetDefaultOpenStateHands(), DayZProfilesOptions::SetProfileOption(), DayZProfilesOptions::SetProfileOptionFloat(), and DayZProfilesOptions::SetProfileOptionInt().
SaveVersion()
proto native int SaveVersion () private
Returns actual storage version - saving.
Referenced by PlayerStats::SaveStats().
ScriptTest()
proto native bool ScriptTest () private
SelectGamepad()
void SelectGamepad () inline private
Definition at line 2355 of file DayZGame.c.
References DeleteTitleScreen(), UIManager::EnterScriptedMenu(), GetCLIParam(), GetLoadState(), UIManager::GetMenu(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), GetUIManager(), BiosUserManager::GetUserDatabaseIdAsync(), GetUserFOVFromConfig(), GetUserManager(), OnlineServices::LoadMPPrivilege(), MENU_MAIN, MENU_SERVER_BROWSER, mission, PlayMission(), UIScriptedMenu::Refresh(), ResetProfileOptions(), OnlineServices::SetBiosUser(), SetLoadState(), SetPlayerGameName(), SetPlayerName(), and SetUserFOV().
Referenced by SelectUser().
SelectPlayer()
proto native void SelectPlayer (PlayerIdentity identity, Object player) private
Selects player's controlled object.
Parameters
identity identity used in MP (use NULL in singleplayer)
player object which should be controlled by player
Note
We can use only instances of DayZPlayer now
Referenced by MissionBase::CreateCharacter(), and MissionBase::OnClientReadyEvent().
SelectSpectator()
proto native void SelectSpectator (PlayerIdentity identity, string spectatorObjType, vector position) private
Creates spectator object (mostly cameras)
Parameters
identity identity used in MP (use NULL in singleplayer)
spectatorObjType classname for spectator object (like cameras)
position where to create spectator instance
SelectUser()
void SelectUser (int gamepad = -1) inline private
Definition at line 2223 of file DayZGame.c.
References GamepadCheck(), GetGame(), Input::GetGamepadUser(), GetInput(), GetLoadState(), BiosUserManager::GetSelectedUser(), GetUserManager(), Input::IdentifyGamepad(), BiosUser::IsOnline(), BiosUserManager::LogOnUserAsync(), BiosUserManager::PickUserAsync(), Input::ResetActiveGamepad(), Input::SelectActiveGamepad(), SelectGamepad(), BiosUserManager::SelectUserEx(), and SetLoadState().
Referenced by GamepadCheck().
SendLogoutTime()
proto native void SendLogoutTime (Object player, int time) private
Inform client about logout time (creates logout screen on specified client)
Note
Works only on server
Parameters
player object which is logging out
time length of logout
Referenced by MissionBase::OnClientDisconnectedEvent().
ServerConfigGetInt()
proto native int ServerConfigGetInt (string name) private
Server config parsing. Returns 0 if not found.
Referenced by MissionBase::ControlPersonalLight(), ITEM_PlayerData::InitServer(), ITEM_DataBase(), PluginBase::PluginAdminLog(), and MissionBase::SyncGlobalLighting().
SetConnecting()
void SetConnecting (bool value) inline private
Returns true when connecting to server.
Definition at line 3171 of file DayZGame.c.
Referenced by Connect(), and OnEvent().
SetConnectivityStatState()
protected void SetConnectivityStatState (EConnectivityStatType type, EConnectivityStatLevel level) inline private
Definition at line 1695 of file DayZGame.c.
References OnConnectivityStatChange().
Referenced by OnEvent(), and OnMPConnectionLostEvent().
SetDatabaseID()
void SetDatabaseID (string id) inline private
Definition at line 2059 of file DayZGame.c.
References UIManager::GetMenu(), GetUIManager(), and UIScriptedMenu::Refresh().
SetDebugMonitorEnabled()
void SetDebugMonitorEnabled (int value) inline private
Definition at line 1021 of file Game.c.
References m_DebugMonitorEnabled.
Referenced by MissionBase::OnGameplayDataHandlerLoad().
SetDiagDrawMode()
proto native void SetDiagDrawMode (int diag_draw_mode) private
Set debug draw mode.
Referenced by UIScriptedMenu::OnClick().
SetDiagModeEnable()
proto native void SetDiagModeEnable (int diag_mode, bool enabled) private
Set specific debug mode.
Referenced by UIScriptedMenu::OnClick().
SetEVUser()
proto native void SetEVUser (float value) private
Sets custom camera camera EV. range: -50.0..50.0? //TODO.
Referenced by SetEVValue().
SetEVValue()
void SetEVValue (float value) inline private
Definition at line 3568 of file DayZGame.c.
References m_EVValue, and SetEVUser().
SetGameState()
void SetGameState (DayZGameState state) inline private
Definition at line 1273 of file DayZGame.c.
Referenced by ConnectLaunch(), DisconnectSessionEx(), JoinLaunch(), MainMenuLaunch(), MissionLaunch(), OnEvent(), PartyLaunch(), and TryConnect().
SetHudBrightness()
void SetHudBrightness (float value) inline private
Definition at line 3537 of file DayZGame.c.
Referenced by OnInitialize().
SetKeyboardHandle()
void SetKeyboardHandle (UIScriptedMenu handler) inline private
Definition at line 3188 of file DayZGame.c.
SetLoadState()
void SetLoadState (DayZLoadState state) inline private
Definition at line 1283 of file DayZGame.c.
Referenced by ConnectLaunch(), DisconnectSessionEx(), JoinLaunch(), MainMenuLaunch(), MissionLaunch(), OnEvent(), PartyLaunch(), SelectGamepad(), and SelectUser().
SetMainMenuWorld()
proto native void SetMainMenuWorld (string world) private
Referenced by DayZGame().
SetMission()
proto native void SetMission (Mission mission) private
SetMissionPath()
void SetMissionPath (string path) inline private
Called from C++.
Definition at line 1127 of file DayZGame.c.
References string::IndexOfFrom(), path, and string::Substring().
SetMissionState()
void SetMissionState (int state) inline private
Definition at line 1192 of file DayZGame.c.
SetNewCharacter()
void SetNewCharacter (bool state) inline private
Definition at line 3484 of file DayZGame.c.
SetPlayerGameName()
void SetPlayerGameName (string name) inline private
Definition at line 3474 of file DayZGame.c.
References name.
Referenced by SelectGamepad().
SetPlayerName()
proto native void SetPlayerName (string name) private
Sets current player name.
Parameters
name
Referenced by SelectGamepad().
SetPreviousGamepad()
void SetPreviousGamepad (int gamepad) inline private
Definition at line 2303 of file DayZGame.c.
SetProfileOption()
void SetProfileOption (EDayZProfilesOptions option, bool value) inline private
Definition at line 1238 of file DayZGame.c.
Referenced by SetProfileOptionBool().
SetProfileOptionBool()
void SetProfileOptionBool (EDayZProfilesOptions option, bool value) inline private
Definition at line 1243 of file DayZGame.c.
References SetProfileOption().
SetProfileOptionFloat()
void SetProfileOptionFloat (EDayZProfilesOptions option, float value) inline private
Definition at line 1253 of file DayZGame.c.
SetProfileOptionInt()
void SetProfileOptionInt (EDayZProfilesOptions option, int value) inline private
Definition at line 1248 of file DayZGame.c.
SetProfileString()
proto native void SetProfileString (string name, string value) private
Sets string to profile variable.
Parameters
name of the variable
value to set
Referenced by UIScriptedMenu::Init(), LoadPlayerAttachmentIndexes(), ScriptedWidgetEventHandler::SaveFilters(), ItemManager::SetDefaultOpenStateHands(), DayZProfilesOptions::SetProfileOption(), DayZProfilesOptions::SetProfileOptionFloat(), DayZProfilesOptions::SetProfileOptionInt(), and SetProfileValueBool().
SetProfileStringList()
proto native void SetProfileStringList (string name, TStringArray values) private
Sets array of strings to profile variable.
Parameters
name of the variable
values to set
Referenced by AddVisitedServer(), UIScriptedMenu::SaveFavoriteServersConsoles(), ItemManager::SerializeDefaultHeaderOpenStates(), and ItemManager::SerializeDefaultOpenStates().
SetUserFOV()
void SetUserFOV (float pFov) inline private
Definition at line 3494 of file DayZGame.c.
Referenced by SelectGamepad().
SetVoiceEffect()
proto native void SetVoiceEffect (Object player, int effect, bool enable) private
Enable/disable VoN effect (only on server)
Parameters
player in question
voice effect (VoiceEffectMumbling = 1, VoiceEffectExtortion = 2, VoiceEffectObstruction = 4)
enable or disable effect
Referenced by ManBase::CheckForGag(), and ItemBase::MutePlayer().
SetVoiceLevel()
proto native void SetVoiceLevel (int level) private
Set voice level of VoN (only on client) (VoiceLevelWhisper = 0, VoiceLevelNormal = 1, VoiceLevelShout = 2)
Parameters
level of voice
Referenced by HandleInput().
ShouldShowControllerDisconnect()
bool ShouldShowControllerDisconnect () inline private
Definition at line 2116 of file DayZGame.c.
References m_ShouldShowControllerDisconnect.
StartRandomCutscene()
proto native void StartRandomCutscene (string world) private
Starts intro.
Referenced by MainMenuLaunch(), and PartyLaunch().
StorageVersion()
proto native void StorageVersion (int iVersion) private
Set actual storage version - for next save.
Referenced by CGame().
StoreLoginData()
proto native void StoreLoginData (ParamsWriteContext ctx) private
Stores login userdata as parameters which are sent to server
Referenced by StoreLoginDataPrepare().
StoreLoginDataPrepare()
void StoreLoginDataPrepare () inline private
Definition at line 1889 of file DayZGame.c.
References GetMenuDefaultCharacterData(), ScriptReadWriteContext::GetWriteContext(), MenuDefaultCharacterData::SerializeCharacterData(), and StoreLoginData().
Referenced by OnPreloadEvent().
SurfaceGetNoiseMultiplier()
proto native float SurfaceGetNoiseMultiplier (Object directHit, vector pos, int componentIndex) private
Referenced by CloseCombatEffects(), FirearmEffects(), and IEntity::GetSurfaceNoise().
SurfaceGetNormal()
proto native vector SurfaceGetNormal (float x, float z) private
Referenced by Hologram::AlignProjectionOnTerrain(), and GetSurfaceOrientation().
SurfaceGetSeaLevel()
proto native float SurfaceGetSeaLevel () private
SurfaceGetType()
proto void SurfaceGetType (float x, float z, out string type) private
Referenced by Inventory_Base::CanBeFilledAtPosition(), ActionDigWorms::IsTargetFertile(), and FlammableBase::StandUp().
SurfaceGetType3D()
proto void SurfaceGetType3D (float x, float y, float z, out string type) private
Referenced by GardenBase::CanBePlaced(), IsEntityOnInteriorSurface(), IsEntityOnWaterSurface(), ItemBase::IsPlaceableAtPosition(), and ItemBase::IsSurfaceWater().
SurfaceIsPond()
proto native bool SurfaceIsPond (float x, float z) private
Referenced by Hologram::IsSurfaceWater().
SurfaceIsSea()
proto native bool SurfaceIsSea (float x, float z) private
Referenced by Hologram::IsSurfaceSea(), and Hologram::IsSurfaceWater().
SurfaceRoadY()
proto native float SurfaceRoadY (float x, float z) private
Referenced by EffectAreaLoader::CreateZones(), DayZSpectator::EOnFrame(), GetHighestSurfaceYDifference(), UIScriptedMenu::OnDoubleClick(), ItemBase::PlaceOnGround(), and ItemBase::SetupTrapPlayer().
SurfaceUnderObject()
proto void SurfaceUnderObject (notnull Object object, out string type, out int liquidType) private
Referenced by ActionCondition(), ActionBuryBody::ActionCondition(), ActionDigInStash::ActionCondition(), IEntity::GetSurfaceType(), ManBase::OnJumpOutVehicleFinish(), and ManBase::ProcessFeetDamageServer().
SurfaceUnderObjectByBone()
proto void SurfaceUnderObjectByBone (notnull Object object, int boneType, out string type, out int liquidType) private
SurfaceUnderObjectEx()
proto void SurfaceUnderObjectEx (notnull Object object, out string type, out string impact, out int liquidType) private
Referenced by EntityAI::GetImpactSurfaceTypeEx().
SurfaceY()
proto native float SurfaceY (float x, float z) private
Referenced by ActionDigWorms::ActionCondition(), Hit_MeatBones::BloodSplatGround(), PluginBase::CalculatePos(), DayZIntroScene::DayZIntroScene(), DayZIntroSceneXbox::DayZIntroSceneXbox(), ActionRepackTentCB::DropDuringRepacking(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnDoubleClick(), UIScriptedMenu::OnMouseButtonDown(), EffectArea::PlaceParticles(), DayZIntroScene::SnapToGround(), DayZIntroSceneXbox::SnapToGround(), UIScriptedMenu::Teleport(), TeleportCheck(), and UIScriptedMenu::UpdateMousePos().
TryConnect()
void TryConnect () inline private
Definition at line 2420 of file DayZGame.c.
References Connect(), ConnectFromCLI(), DisconnectSessionForce(), DisconnectSessionScript(), GetGameState(), GetHostAddress(), GetLoadState(), OnlineServices::GetSession(), SetGameState(), ErrorModuleHandler::ThrowError(), and TryConnect().
Referenced by TryConnect().
UpdateInputDeviceDisconnectWarning()
void UpdateInputDeviceDisconnectWarning () inline private
Definition at line 2121 of file DayZGame.c.
References Input::AreAllAllowedInputDevicesActive(), ScriptCallQueue::Call(), CALL_CATEGORY_GUI, GetCallQueue(), GetInput(), GetUIManager(), and MENU_WARNING_INPUTDEVICE_DISCONNECT.
Referenced by LoadingHide(), and OnEvent().
UpdateLoginQueue()
void UpdateLoginQueue (float timeslice) inline private
Display login queue position dialog
manually update static login queue dialog
Definition at line 1760 of file DayZGame.c.
References UIManager::CloseAll(), EnterLoginQueue(), UIManager::GetLoginQueuePosition(), UIManager::GetMenu(), GetMission(), GetUIManager(), UIScriptedMenu::SetPosition(), and UIManager::ShowScriptedMenu().
Referenced by OnUpdate().
UpdatePathgraphRegion()
proto native void UpdatePathgraphRegion (vector regionMin, vector regionMax) private
Referenced by UpdatePathgraphRegionByObject().
UpdatePathgraphRegionByObject()
void UpdatePathgraphRegionByObject (Object object) inline private
Definition at line 1098 of file Game.c.
References UpdatePathgraphRegion(), and Vector().
Referenced by Land_Underground_EntranceBase::NavmeshUpdate(), and Land_Underground_Stairs_Exit::OnDoorStateChangedServer().
UpdateSpectatorPosition()
proto native void UpdateSpectatorPosition (vector position) private
Updates spectator position on server = position of network bubble.
Parameters
position
Referenced by DayZSpectator::EOnFrame().
UpdateVoiceLevel()
void UpdateVoiceLevel (int level) inline private
Definition at line 3464 of file DayZGame.c.
References GetMission(), and Mission::UpdateVoiceLevelWidgets().
VerifyWorldOwnership()
proto native bool VerifyWorldOwnership (string sWorldName) private
Referenced by ScriptedWidgetEventHandler::RefreshDLCIcon().
Field Documentation
ARROW_PIERCE_DEPTH
const float ARROW_PIERCE_DEPTH = 0.05 private
Definition at line 3305 of file DayZGame.c.
Referenced by OnProjectileStoppedInObject(), and OnProjectileStoppedInTerrain().
Event_OnRPC
ref ScriptInvoker Event_OnRPC = new ScriptInvoker() static private
Definition at line 943 of file DayZGame.c.
GameScript
ScriptModule GameScript private
Definition at line 12 of file Game.c.
Referenced by CallQueueContext::CallParams(), ComponentEnergyManager::DeviceUpdate(), ComponentEnergyManager::Event_OnInit(), UIScriptedMenu::Init(), WidgetEventHandler::OnChildAdd(), WidgetEventHandler::OnChildRemove(), WidgetEventHandler::OnClick(), WidgetEventHandler::OnDoubleClick(), WidgetEventHandler::OnDrag(), WidgetEventHandler::OnDraggingOver(), WidgetEventHandler::OnDrop(), WidgetEventHandler::OnDropReceived(), WidgetEventHandler::OnFocus(), WidgetEventHandler::OnFocusLost(), PluginBase::OnKeyPress(), PluginBase::OnMouse(), WidgetEventHandler::OnMouseButtonDown(), OnMouseButtonUp(), WidgetEventHandler::OnMouseButtonUp(), WidgetEventHandler::OnMouseEnter(), WidgetEventHandler::OnMouseLeave(), WidgetEventHandler::OnMouseWheel(), UniversalTemperatureSource::OnTimer(), TimerBase::OnTimer(), array::Run(), SetControlType(), ComponentEnergyManager::SwitchOff(), ComponentEnergyManager::SwitchOn(), TestCleanup(), EnProfilerTests::TestFuncCountData(), AnimationTimer::Tick(), UpdataControllerInput(), and Update().
m_AimLoggingEnabled
private bool m_AimLoggingEnabled private
Definition at line 918 of file DayZGame.c.
Referenced by IsAimLogEnabled().
m_AmmoShakeParams
ref AmmoCamParams m_AmmoShakeParams = new AmmoCamParams() static private
Definition at line 941 of file DayZGame.c.
m_AnalyticsManagerClient
ref AnalyticsManagerClient m_AnalyticsManagerClient private
Definition at line 18 of file Game.c.
Referenced by CGame(), and GetAnalyticsClient().
m_AnalyticsManagerServer
ref AnalyticsManagerServer m_AnalyticsManagerServer private
Definition at line 17 of file Game.c.
Referenced by CGame(), and GetAnalyticsServer().
m_ArtySound
private ref EffectSound m_ArtySound private
Definition at line 954 of file DayZGame.c.
m_Backlit
private ref Backlit m_Backlit private
Definition at line 945 of file DayZGame.c.
Referenced by GetBacklit().
m_callQueue
private ref ScriptCallQueue m_callQueue[CALL_CATEGORY_COUNT] private
Definition at line 897 of file DayZGame.c.
m_CharacterData
ref MenuDefaultCharacterData m_CharacterData private
Definition at line 19 of file Game.c.
Referenced by GetMenuDefaultCharacterData().
m_CharClassNames
private ref array<string> m_CharClassNames = new array<string>() private
Definition at line 947 of file DayZGame.c.
Referenced by ListAvailableCharacters().
m_ConnectAddress
protected string m_ConnectAddress private
Definition at line 2047 of file DayZGame.c.
m_ConnectedInputDeviceList
private ref array<int> m_ConnectedInputDeviceList private
Definition at line 948 of file DayZGame.c.
Referenced by GetConnectedInputDeviceList().
m_ConnectFromJoin
private bool m_ConnectFromJoin private
Definition at line 923 of file DayZGame.c.
m_connectionLost
private ref ConnectionLost m_connectionLost private
Definition at line 895 of file DayZGame.c.
m_ConnectivityStatsStates
private EConnectivityStatLevel m_ConnectivityStatsStates[STATS_COUNT] private
Definition at line 879 of file DayZGame.c.
m_ConnectPassword
protected string m_ConnectPassword private
Definition at line 2049 of file DayZGame.c.
m_ConnectPort
protected int m_ConnectPort private
Definition at line 2048 of file DayZGame.c.
m_CrashSound
private ref EffectSound m_CrashSound private
Definition at line 951 of file DayZGame.c.
m_DatabaseID
protected string m_DatabaseID private
Definition at line 2045 of file DayZGame.c.
Referenced by GetDatabaseID().
m_DayZProfileOptions
private ref DayZProfilesOptions m_DayZProfileOptions private
Definition at line 901 of file DayZGame.c.
m_DebugMonitorEnabled
int m_DebugMonitorEnabled private
Definition at line 10 of file Game.c.
Referenced by IsDebugMonitor(), and SetDebugMonitorEnabled().
m_DeltaTime
float m_DeltaTime private
Definition at line 2764 of file DayZGame.c.
Referenced by GetDeltaT().
m_dragQueue
private ref DragQueue m_dragQueue private
Definition at line 900 of file DayZGame.c.
Referenced by GetDragQueue().
m_early_access_dialog_accepted
private bool m_early_access_dialog_accepted private
Definition at line 902 of file DayZGame.c.
m_EVValue
float m_EVValue = 0 private
Definition at line 935 of file DayZGame.c.
Referenced by GetCurrentEVValue(), and SetEVValue().
m_FirstConnect
protected bool m_FirstConnect = true private
Definition at line 887 of file DayZGame.c.
m_FoodDecayModifier
private float m_FoodDecayModifier private
Definition at line 914 of file DayZGame.c.
Referenced by GetFoodDecayModifier().
m_GamepadDisconnectMenu
protected ref Widget m_GamepadDisconnectMenu private
Definition at line 2042 of file DayZGame.c.
m_GameState
protected DayZGameState m_GameState private
Definition at line 884 of file DayZGame.c.
Referenced by GetGameState().
m_IntroMenu
protected ref Widget m_IntroMenu private
Definition at line 2041 of file DayZGame.c.
Referenced by DeleteTitleScreen().
m_IsConnecting
private bool m_IsConnecting private
Definition at line 922 of file DayZGame.c.
Referenced by IsConnecting().
m_IsCtrlHolding
private bool m_IsCtrlHolding private
Definition at line 907 of file DayZGame.c.
Referenced by IsLeftCtrlDown().
m_IsFoodDecayEnabled
private bool m_IsFoodDecayEnabled = true private
Definition at line 913 of file DayZGame.c.
m_IsLeftAltHolding
private bool m_IsLeftAltHolding private
Definition at line 909 of file DayZGame.c.
m_IsNewCharacter
private bool m_IsNewCharacter private
Definition at line 921 of file DayZGame.c.
Referenced by IsNewCharacter().
m_IsRightAltHolding
private bool m_IsRightAltHolding private
Definition at line 910 of file DayZGame.c.
m_IsStressTest
private bool m_IsStressTest private
Definition at line 917 of file DayZGame.c.
Referenced by IsStressTest().
m_IsWinHolding
private bool m_IsWinHolding private
Definition at line 908 of file DayZGame.c.
m_IsWorldWetTempUpdateEnabled
private bool m_IsWorldWetTempUpdateEnabled = true private
Definition at line 912 of file DayZGame.c.
Referenced by IsWorldWetTempUpdateEnabled().
m_keyboard_handler
private UIScriptedMenu m_keyboard_handler private
Definition at line 903 of file DayZGame.c.
m_loading
ref LoadingScreen m_loading private
Definition at line 890 of file DayZGame.c.
m_LoadState
protected DayZLoadState m_LoadState private
Definition at line 885 of file DayZGame.c.
Referenced by GetLoadState().
m_LoginQueue
private ref LoginQueueBase m_LoginQueue private
Definition at line 892 of file DayZGame.c.
Referenced by CancelLoginQueue().
m_LoginTime
private int m_LoginTime private
Definition at line 893 of file DayZGame.c.
m_LoginTimeScreen
private ref LoginTimeBase m_LoginTimeScreen private
Definition at line 891 of file DayZGame.c.
Referenced by CancelLoginTimeCountdown().
m_mission_module
private ScriptModule m_mission_module private
Definition at line 904 of file DayZGame.c.
m_MissionFolderPath
private string m_MissionFolderPath private
Definition at line 906 of file DayZGame.c.
Referenced by GetMissionFolderPath().
m_MissionPath
private string m_MissionPath private
Definition at line 905 of file DayZGame.c.
Referenced by GetMissionPath().
m_MissionState
private int m_MissionState private
Definition at line 881 of file DayZGame.c.
Referenced by GetMissionState().
m_NoiseParams
ref NoiseParams m_NoiseParams = new NoiseParams() static private
Definition at line 957 of file DayZGame.c.
m_Notifications
protected ref NotificationUI m_Notifications private
Definition at line 886 of file DayZGame.c.
m_OriginalCharactersCount
int m_OriginalCharactersCount private
Definition at line 919 of file DayZGame.c.
m_ParamCache
private ref array<ref Param> m_ParamCache private
Definition at line 14 of file Game.c.
Referenced by CGame(), RPCSelfSingleParam(), and RPCSingleParam().
m_PlayerName
private string m_PlayerName private
Definition at line 920 of file DayZGame.c.
Referenced by GetPlayerGameName().
m_postUpdateQueue
private ref ScriptInvoker m_postUpdateQueue[CALL_CATEGORY_COUNT] private
Definition at line 899 of file DayZGame.c.
m_PrevBlur
protected int m_PrevBlur private
Definition at line 2043 of file DayZGame.c.
m_PreviousEVValue
float m_PreviousEVValue private
Definition at line 934 of file DayZGame.c.
Referenced by GetPreviousEVValue().
m_PreviousGamepad
private int m_PreviousGamepad private
Definition at line 925 of file DayZGame.c.
Referenced by GetPreviousGamepad().
m_ReportModded
bool m_ReportModded static private
Definition at line 916 of file DayZGame.c.
Referenced by ReportModded().
m_ShouldShowControllerDisconnect
private bool m_ShouldShowControllerDisconnect private
Definition at line 924 of file DayZGame.c.
Referenced by ShouldShowControllerDisconnect().
m_timerQueue
private ref TimerQueue m_timerQueue[CALL_CATEGORY_COUNT] private
Definition at line 896 of file DayZGame.c.
m_updateQueue
private ref ScriptInvoker m_updateQueue[CALL_CATEGORY_COUNT] private
Definition at line 898 of file DayZGame.c.
m_UserFOV
private float m_UserFOV private
Definition at line 926 of file DayZGame.c.
Referenced by GetUserFOV().
m_Visited
protected ref TStringArray m_Visited private
Definition at line 2052 of file DayZGame.c.
m_volume_music
float m_volume_music private
Definition at line 930 of file DayZGame.c.
m_volume_radio
float m_volume_radio private
Definition at line 932 of file DayZGame.c.
m_volume_sound
float m_volume_sound private
Definition at line 928 of file DayZGame.c.
m_volume_speechEX
float m_volume_speechEX private
Definition at line 929 of file DayZGame.c.
m_volume_VOIP
float m_volume_VOIP private
Definition at line 931 of file DayZGame.c.
MAX_VISITED
protected const int MAX_VISITED = 50 private
Definition at line 2051 of file DayZGame.c.
MIN_ARTY_SOUND_RANGE
private const int MIN_ARTY_SOUND_RANGE = 300 private
Definition at line 955 of file DayZGame.c.
MISSION_STATE_FINNISH
const int MISSION_STATE_FINNISH = 2 private
Definition at line 876 of file DayZGame.c.
MISSION_STATE_GAME
const int MISSION_STATE_GAME = 1 private
Definition at line 875 of file DayZGame.c.
Referenced by DayZGame().
MISSION_STATE_MAINMENU
const int MISSION_STATE_MAINMENU = 0 private
Definition at line 874 of file DayZGame.c.
STATS_COUNT
private const int STATS_COUNT = EConnectivityStatType.COUNT private
Definition at line 878 of file DayZGame.c.
Referenced by ClearConnectivityStates().
The documentation for this class was generated from the following files:
P:/scripts/3_Game/DayZGame.c
P:/scripts/3_Game/Global/Game.c