DayZ Scripts: SplitItemUtils Class Reference
SplitItemUtils Class Reference
Static Private Member Functions
static void TakeOrSplitToInventory (notnull PlayerBase player, notnull EntityAI target, notnull EntityAI item)
static void TakeOrSplitToInventoryLocation (notnull PlayerBase player, notnull InventoryLocation dst)
Detailed Description
Definition at line 1 of file SplitItemUtils.c.
Member Function Documentation
TakeOrSplitToInventory()
static void TakeOrSplitToInventory (notnull PlayerBase player, notnull EntityAI target, notnull EntityAI item) inline static private
Definition at line 3 of file SplitItemUtils.c.
References InventoryLocation::GetParent(), InventoryLocation::GetSlot(), and InventoryLocation::GetType().
Referenced by AttachmentCategoriesRow::Combine(), PlayerContainer::OnDropReceivedFromGhostArea(), ClosableContainer::OnDropReceivedFromHeader(), Icon::OnPerformCombination(), HandsContainer::OnPerformCombination(), OnRightPanelDropReceived(), AttachmentCategoriesRow::Select(), HandsContainer::TakeAsAttachment(), and ClosableContainer::TakeAsAttachment().
TakeOrSplitToInventoryLocation()
static void TakeOrSplitToInventoryLocation (notnull PlayerBase player, notnull InventoryLocation dst) inline static private
Definition at line 34 of file SplitItemUtils.c.
References Error(), and ItemBase::GetSlot().
Referenced by VicinitySlotsContainer::DoubleClick(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), Icon::DropReceivedFromMain(), OnCenterPanelDropReceived(), and VicinitySlotsContainer::TransferItem().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/SplitItemUtils.c