DayZ Scripts: Land_Underground_Stairs_Exit Class Reference
Land_Underground_Stairs_Exit Class Reference
Private Member Functions
void Land_Underground_Stairs_Exit ()
override void CleanUpOnClosedClient ()
override float GetOpeningTime ()
override void OnDoorStateChangedServer (EUndegroundEntranceState newState)
void SoundEnded (Effect eff)
override void HandleAudioPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState)
override void CreateLights ()
Private Attributes
EffectSound m_LockingSound
EffectSound m_OpenSoundIn
EffectSound m_OpenSoundOut
EffectSound m_CloseSoundIn
EffectSound m_CloseSoundLoop
EffectSound m_CloseSoundOut
const string LOCKING_SOUNDSET = "UndergroundDoor_Lock_SoundSet"
const string OPENING_SOUNDSET_LOOP_IN = "UndergroundSmallExitDoor_Open_Start_SoundSet"
const string OPENING_SOUNDSET_LOOP = "UndergroundSmallExitDoor_Open_Loop_SoundSet"
const string OPENING_SOUNDSET_LOOP_OUT = "UndergroundSmallExitDoor_Open_End_SoundSet"
const string CLOSING_SOUNDSET_LOOP_IN = "UndergroundSmallExitDoor_Close_Start_SoundSet"
const string CLOSING_SOUNDSET_LOOP = "UndergroundSmallExitDoor_Close_Loop_SoundSet"
const string CLOSING_SOUNDSET_LOOP_OUT = "UndergroundSmallExitDoor_Close_End_SoundSet"
Constructor & Destructor Documentation
Land_Underground_Stairs_Exit()
void Land_Underground_Stairs_Exit () inline private
References Land_Underground_EntranceBase::m_DoorType.
Member Function Documentation
CleanUpOnClosedClient()
override void CleanUpOnClosedClient () inline private
References SEffectManager::DestroySound(), m_CloseSoundIn, m_CloseSoundLoop, m_CloseSoundOut, m_LockingSound, m_OpenSoundIn, and m_OpenSoundOut.
CreateLights()
override void CreateLights () inline private
References EntranceLight(), EntranceLightStairs1(), Land_Underground_EntranceBase::m_InteriorLight1, and Land_Underground_EntranceBase::m_InteriorLight2.
GetOpeningTime()
override float GetOpeningTime () inline private
References Land_Underground_EntranceBase::AdjustTime().
Referenced by OnDoorStateChangedServer().
HandleAudioPlayback()
override void HandleAudioPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState) inline private
References CLOSING_SOUNDSET_LOOP_IN, CLOSING_SOUNDSET_LOOP_OUT, LOCKING_SOUNDSET, m_CloseSoundIn, m_CloseSoundLoop, m_CloseSoundOut, m_LockingSound, m_OpenSoundIn, m_OpenSoundOut, OPENING_SOUNDSET_LOOP_IN, OPENING_SOUNDSET_LOOP_OUT, SoundEnded(), and EffectSound::Stop().
OnDoorStateChangedServer()
override void OnDoorStateChangedServer (EUndegroundEntranceState newState) inline private
References Land_Underground_EntranceBase::AdjustTime(), GetGame(), GetOpeningTime(), Land_Underground_EntranceBase::m_AnimTimerDoorServer, Land_Underground_EntranceBase::RequestLatentTransition(), AnimationTimer::Run(), and CGame::UpdatePathgraphRegionByObject().
SoundEnded()
void SoundEnded (Effect eff) inline private
References CLOSING_SOUNDSET_LOOP, m_CloseSoundIn, and m_CloseSoundLoop.
Referenced by HandleAudioPlayback().
Field Documentation
CLOSING_SOUNDSET_LOOP
const string CLOSING_SOUNDSET_LOOP = "UndergroundSmallExitDoor_Close_Loop_SoundSet" private
Referenced by SoundEnded().
CLOSING_SOUNDSET_LOOP_IN
const string CLOSING_SOUNDSET_LOOP_IN = "UndergroundSmallExitDoor_Close_Start_SoundSet" private
Referenced by HandleAudioPlayback().
CLOSING_SOUNDSET_LOOP_OUT
const string CLOSING_SOUNDSET_LOOP_OUT = "UndergroundSmallExitDoor_Close_End_SoundSet" private
Referenced by HandleAudioPlayback().
LOCKING_SOUNDSET
const string LOCKING_SOUNDSET = "UndergroundDoor_Lock_SoundSet" private
Referenced by HandleAudioPlayback().
m_CloseSoundIn
EffectSound m_CloseSoundIn private
Referenced by CleanUpOnClosedClient(), HandleAudioPlayback(), and SoundEnded().
m_CloseSoundLoop
EffectSound m_CloseSoundLoop private
Referenced by CleanUpOnClosedClient(), HandleAudioPlayback(), and SoundEnded().
m_CloseSoundOut
EffectSound m_CloseSoundOut private
Referenced by CleanUpOnClosedClient(), and HandleAudioPlayback().
m_LockingSound
EffectSound m_LockingSound private
Referenced by CleanUpOnClosedClient(), and HandleAudioPlayback().
m_OpenSoundIn
EffectSound m_OpenSoundIn private
Referenced by CleanUpOnClosedClient(), and HandleAudioPlayback().
m_OpenSoundOut
EffectSound m_OpenSoundOut private
Referenced by CleanUpOnClosedClient(), and HandleAudioPlayback().
OPENING_SOUNDSET_LOOP
const string OPENING_SOUNDSET_LOOP = "UndergroundSmallExitDoor_Open_Loop_SoundSet" private
OPENING_SOUNDSET_LOOP_IN
const string OPENING_SOUNDSET_LOOP_IN = "UndergroundSmallExitDoor_Open_Start_SoundSet" private
Referenced by HandleAudioPlayback().
OPENING_SOUNDSET_LOOP_OUT
const string OPENING_SOUNDSET_LOOP_OUT = "UndergroundSmallExitDoor_Open_End_SoundSet" private
Referenced by HandleAudioPlayback().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Building/Underground/Stairs/Land_Underground_Stairs_Exit.c