DayZ Scripts: 4_World/Entities/ItemBase/Magazine/AmmunitionPiles.c File Reference
AmmunitionPiles.c File Reference
Data Structures
class Ammunition_Base
ammo pile base
class Ammo_45ACP
class Ammo_308Win
class Ammo_308WinTracer
class Ammo_9x19
class Ammo_380
class Ammo_556x45
class Ammo_556x45Tracer
class Ammo_762x54
class Ammo_762x54Tracer
class Ammo_762x39
class Ammo_762x39Tracer
class Ammo_9x39
class Ammo_22
class Ammo_12gaPellets
class Ammo_12gaSlug
class Ammo_357
class Ammo_545x39
class Ammo_545x39Tracer
class Bolt_Base
class Ammo_Flare
class Ammo_RPG7_HE
class Ammo_RPG7_AP
class Ammo_LAW_HE
class Ammo_GrenadeM4
class Ammo_HuntingBolt
class Ammo_ImprovisedBolt_2
class Ammo_40mm_Explosive
class Ammo_40mm_Smoke_ColorBase
class Ammo_40mm_Smoke_Green
class Ammo_40mm_Smoke_White
class Ammo_40mm_Smoke_Black
Functions
Ammo_HuntingBolt Bolt_Base SetActions ()
Ammo_ImprovisedBolt_2 Bolt_Base IsTakeable ()
override bool IsInventoryVisible ()
Ammo_40mm_Explosive Ammo_40mm_Base OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
override bool ShootsExplosiveAmmo ()
override void EEKilled (Object killer)
override void OnDamageDestroyed (int oldLevel)
Variables
Bolt_Base Ammunition_Base
Ammo_40mm_Smoke_ColorBase Ammo_40mm_Smoke_ColorBase
Function Documentation
EEKilled()
override void EEKilled (Object killer)
References ClearFlags().
IsInventoryVisible()
override bool IsInventoryVisible ()
References IsTakeable().
IsTakeable()
Ammo_ImprovisedBolt_2 Bolt_Base IsTakeable ()
Referenced by IsInventoryVisible().
OnActivatedByItem()
Ammo_40mm_Explosive Ammo_40mm_Base OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
OnDamageDestroyed()
override void OnDamageDestroyed (int oldLevel)
SetActions()
Ammo_HuntingBolt Bolt_Base SetActions ()
ShootsExplosiveAmmo()
override bool ShootsExplosiveAmmo ()
References CGame::CreateObject(), and GetGame().
Variable Documentation
Ammo_40mm_Smoke_ColorBase
Ammo_40mm_Smoke_ColorBase Ammo_40mm_Smoke_ColorBase
Ammunition_Base
Bolt_Base Ammunition_Base