DayZ Scripts: Mp133Shotgun_Base Class Reference
Mp133Shotgun_Base Class Reference
basic mp5 submachine gun
Private Member Functions
void Mp133Shotgun ()
override RecoilBase SpawnRecoilObject ()
override void InitStateMachine ()
override bool CanChamberBullet (int muzzleIndex, Magazine mag)
override void SetActions ()
override void OnDebugSpawn ()
Private Attributes
ref WeaponStateBase E
ref WeaponStateBase F
ref WeaponStateBase L
ref WeaponStateBase J
Detailed Description
basic mp5 submachine gun
Definition at line 64 of file MP133.c.
Member Function Documentation
CanChamberBullet()
override bool CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 212 of file MP133.c.
InitStateMachine()
override void InitStateMachine () inline private
Definition at line 80 of file MP133.c.
References E, F, J, and L.
Mp133Shotgun()
void Mp133Shotgun () inline private
Definition at line 71 of file MP133.c.
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 227 of file MP133.c.
References Class::CastTo(), and GameInventory::CreateInInventory().
SetActions()
override void SetActions () inline private
Definition at line 217 of file MP133.c.
References AddAction(), and RemoveAction().
SpawnRecoilObject()
override RecoilBase SpawnRecoilObject () inline private
Definition at line 75 of file MP133.c.
Field Documentation
E
ref WeaponStateBase E private
Definition at line 66 of file MP133.c.
Referenced by InitStateMachine().
F
ref WeaponStateBase F private
Definition at line 67 of file MP133.c.
Referenced by InitStateMachine().
J
ref WeaponStateBase J private
Definition at line 69 of file MP133.c.
Referenced by InitStateMachine().
L
ref WeaponStateBase L private
Definition at line 68 of file MP133.c.
Referenced by InitStateMachine().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Firearms/Shotgun/MP133.c