DayZ Scripts: IngameHudHeatBuffer Class Reference
IngameHudHeatBuffer Class Reference
Private Member Functions
void IngameHudHeatBuffer (Widget root, notnull PlayerBase player)
void OnPlayerNegativeCondition (PlayerBase player)
void OnPlayerConditionChanged (PlayerBase player)
bool CanUpdate ()
void Update (float timeslice)
void SetBaseAlpha (Widget hbw, float valuePercent, float stageThreshold)
void UpdateEffect (Widget hbw, float duration, float timeslice)
Private Attributes
protected Widget m_Root
protected float m_CurrentValue
protected bool m_IsActive
protected int m_CurrentDirection
protected int m_PreviousDirection
protected bool m_Update
protected PlayerBase m_Player
protected float m_EffectTime
protected float m_EffectDuration
protected bool m_FadeIn
protected float m_FlashingTime
protected int m_FlashingStage
protected ref map< int, float > m_FlashingThresholds
Constructor & Destructor Documentation
IngameHudHeatBuffer()
void IngameHudHeatBuffer (Widget root, notnull PlayerBase player) inline private
References m_CurrentDirection, m_FlashingStage, m_FlashingThresholds, m_Player, m_PreviousDirection, m_Root, m_Update, OnPlayerConditionChanged(), and OnPlayerNegativeCondition().
Member Function Documentation
CanUpdate()
bool CanUpdate () inline private
References m_Player, and m_Update.
OnPlayerConditionChanged()
void OnPlayerConditionChanged (PlayerBase player) inline private
References m_Player, m_Update, and Print().
Referenced by IngameHudHeatBuffer().
OnPlayerNegativeCondition()
void OnPlayerNegativeCondition (PlayerBase player) inline private
References m_Player, m_Update, and Print().
Referenced by IngameHudHeatBuffer().
SetBaseAlpha()
void SetBaseAlpha (Widget hbw, float valuePercent, float stageThreshold) inline private
References Math::Floor(), Math::Lerp(), and Print().
Referenced by Update().
Update()
void Update (float timeslice) inline private
References ARGB(), m_CurrentDirection, m_CurrentValue, m_FlashingStage, m_FlashingThresholds, m_FlashingTime, m_IsActive, m_Player, m_PreviousDirection, m_Root, HeatBufferMdfr::NUMBER_OF_STAGES, Print(), SetBaseAlpha(), HeatBufferMdfr::STAGE_THRESHOLDS, and UpdateEffect().
UpdateEffect()
void UpdateEffect (Widget hbw, float duration, float timeslice) inline private
References Math::Clamp(), Math::Lerp(), m_EffectDuration, m_EffectTime, m_FadeIn, m_IsActive, and Print().
Referenced by Update().
Field Documentation
m_CurrentDirection
protected int m_CurrentDirection private
Referenced by IngameHudHeatBuffer(), and Update().
m_CurrentValue
protected float m_CurrentValue private
Referenced by Update().
m_EffectDuration
protected float m_EffectDuration private
Referenced by UpdateEffect().
m_EffectTime
protected float m_EffectTime private
Referenced by UpdateEffect().
m_FadeIn
protected bool m_FadeIn private
Referenced by UpdateEffect().
m_FlashingStage
protected int m_FlashingStage private
Referenced by IngameHudHeatBuffer(), and Update().
m_FlashingThresholds
protected ref map<int, float> m_FlashingThresholds private
Referenced by IngameHudHeatBuffer(), and Update().
m_FlashingTime
protected float m_FlashingTime private
Referenced by Update().
m_IsActive
protected bool m_IsActive private
Referenced by Update(), and UpdateEffect().
m_Player
protected PlayerBase m_Player private
Referenced by CanUpdate(), IngameHudHeatBuffer(), OnPlayerConditionChanged(), OnPlayerNegativeCondition(), and Update().
m_PreviousDirection
protected int m_PreviousDirection private
Referenced by IngameHudHeatBuffer(), and Update().
m_Root
protected Widget m_Root private
Referenced by IngameHudHeatBuffer(), and Update().
m_Update
protected bool m_Update private
Referenced by CanUpdate(), IngameHudHeatBuffer(), OnPlayerConditionChanged(), and OnPlayerNegativeCondition().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/IngameHudHeatBuffer.c