DayZ Scripts: ClientData Class Reference
ClientData Class Reference
Static Private Member Functions
static void ResetClientData ()
static void AddPlayerBase (Man player)
static void RemovePlayerBase (Man player)
static void SyncEvent_PreprocessPlayerList (SyncPlayerList player_list)
static void SyncEvent_OnRecievedPlayerList (SyncPlayerList player_list)
static array< string > GetSimplePlayerList ()
static array< string > GetSimplePlayerList (SyncPlayerList list)
static void SyncEvent_OnEntityKilled (SyncEntityKillInfo entity_killed_data)
static void SyncEvent_OnPlayerIgnitedFireplace (EFireIgniteType igante_type)
Static Private Attributes
static ref ScriptInvoker SyncEvent_OnPlayerListUpdate = new ScriptInvoker()
static ref ScriptInvoker SyncEvent_OnEntityKilled = new ScriptInvoker()
static ref ScriptInvoker SyncEvent_OnPlayerIgnitedFireplace = new ScriptInvoker()
static ref array< Man > m_PlayerBaseList = new array<Man>
static ref SyncPlayerList m_PlayerList
static ref SyncPlayerList m_LastNewPlayers
static ref OnlineServices m_OnlineServices
Member Function Documentation
AddPlayerBase()
static void AddPlayerBase (Man player) inline static private
References GetGame(), GetPlayer(), and m_PlayerBaseList.
Referenced by ManBase::Init().
GetSimplePlayerList() [1/2]
static array< string > GetSimplePlayerList () inline static private
References m_PlayerList, SyncPlayerList::m_PlayerList, and SyncPlayer::m_UID.
Referenced by OnlineServices::GetPendingInviteList(), BiosSessionService::GetSessionPlayerList(), OnlineServices::SetMultiplayState(), and SyncEvent_OnRecievedPlayerList().
GetSimplePlayerList() [2/2]
static array< string > GetSimplePlayerList (SyncPlayerList list) inline static private
References SyncPlayerList::m_PlayerList, and SyncPlayer::m_UID.
RemovePlayerBase()
static void RemovePlayerBase (Man player) inline static private
References m_PlayerBaseList.
Referenced by ManBase::EEKilled(), and ManBase::~PlayerBase().
ResetClientData()
static void ResetClientData () inline static private
References m_LastNewPlayers, m_PlayerBaseList, m_PlayerList, and SyncPlayerList::m_PlayerList.
Referenced by CGame::OnEvent().
SyncEvent_OnEntityKilled()
static void SyncEvent_OnEntityKilled (SyncEntityKillInfo entity_killed_data) inline static private
References ScriptInvoker::Invoke(), SyncEntityKillInfo::m_EntityKiller, SyncEntityKillInfo::m_EntitySource, SyncEntityKillInfo::m_EntityVictim, SyncEntityKillInfo::m_IsHeadShot, and SyncEvent_OnEntityKilled.
SyncEvent_OnPlayerIgnitedFireplace()
static void SyncEvent_OnPlayerIgnitedFireplace (EFireIgniteType igante_type) inline static private
References ScriptInvoker::Invoke(), and SyncEvent_OnPlayerIgnitedFireplace.
SyncEvent_OnRecievedPlayerList()
static void SyncEvent_OnRecievedPlayerList (SyncPlayerList player_list) inline static private
References SyncPlayerList::Compare(), g_Game, OnlineServices::GetMultiplayState(), BiosClientServices::GetSessionService(), GetSimplePlayerList(), ScriptInvoker::Invoke(), OnlineServices::LoadFriends(), OnlineServices::LoadPermissions(), OnlineServices::m_ClientServices, m_LastNewPlayers, m_PlayerList, SyncPlayerList::m_PlayerList, BiosSessionService::OnSessionPlayerListUpdate(), OnlineServices::SetMultiplayState(), and SyncEvent_OnPlayerListUpdate.
Referenced by SyncEvents::OnSyncEvent().
SyncEvent_PreprocessPlayerList()
static void SyncEvent_PreprocessPlayerList (SyncPlayerList player_list) inline static private
References ErrorEx, PlayerIdentityBase::GetPlainId(), PlayerIdentityBase::GetPlainName(), and SyncPlayerList::m_PlayerList.
Referenced by SyncEvents::OnSyncEvent().
Field Documentation
m_LastNewPlayers
ref SyncPlayerList m_LastNewPlayers static private
Referenced by OnlineServices::OnFriendsAsync(), ResetClientData(), and SyncEvent_OnRecievedPlayerList().
m_OnlineServices
ref OnlineServices m_OnlineServices static private
m_PlayerBaseList
ref array<Man> m_PlayerBaseList = new array<Man> static private
Referenced by AddPlayerBase(), Hud::RefreshPlayerTags(), RemovePlayerBase(), and ResetClientData().
m_PlayerList
ref SyncPlayerList m_PlayerList static private
Referenced by GetSimplePlayerList(), UIScriptedMenu::Init(), ResetClientData(), and SyncEvent_OnRecievedPlayerList().
SyncEvent_OnEntityKilled
ref ScriptInvoker SyncEvent_OnEntityKilled = new ScriptInvoker() static private
Referenced by SyncEvents::OnSyncEvent(), AnalyticsManagerClient::RegisterEvents(), SyncEvent_OnEntityKilled(), and AnalyticsManagerClient::UnregisterEvents().
SyncEvent_OnPlayerIgnitedFireplace
ref ScriptInvoker SyncEvent_OnPlayerIgnitedFireplace = new ScriptInvoker() static private
Referenced by SyncEvents::OnSyncEvent(), AnalyticsManagerClient::RegisterEvents(), SyncEvent_OnPlayerIgnitedFireplace(), and AnalyticsManagerClient::UnregisterEvents().
SyncEvent_OnPlayerListUpdate
ref ScriptInvoker SyncEvent_OnPlayerListUpdate = new ScriptInvoker() static private
Referenced by UIScriptedMenu::Init(), SyncEvent_OnRecievedPlayerList(), and UIScriptedMenu::~InGameMenuXbox().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Client/ClientData.c