DayZ Scripts: WidgetEventHandler Class Reference
WidgetEventHandler Class Reference
Private Member Functions
void WidgetEventHandler ()
void UnregisterWidget (Widget w)
void RegisterOnMouseButtonDown (Widget w, Managed eventHandler, string functionName)
void RegisterOnMouseButtonUp (Widget w, Managed eventHandler, string functionName)
void RegisterOnMouseWheel (Widget w, Managed eventHandler, string functionName)
void RegisterOnDropReceived (Widget w, Managed eventHandler, string functionName)
void RegisterOnDrag (Widget w, Managed eventHandler, string functionName)
void RegisterOnDrop (Widget w, Managed eventHandler, string functionName)
void RegisterOnDraggingOver (Widget w, Managed eventHandler, string functionName)
void RegisterOnMouseEnter (Widget w, Managed eventHandler, string functionName)
void RegisterOnMouseLeave (Widget w, Managed eventHandler, string functionName)
void RegisterOnClick (Widget w, Managed eventHandler, string functionName)
void RegisterOnDoubleClick (Widget w, Managed eventHandler, string functionName)
void RegisterOnFocus (Widget w, Managed eventHandler, string functionName)
void RegisterOnFocusLost (Widget w, Managed eventHandler, string functionName)
void RegisterOnChildAdd (Widget w, Managed eventHandler, string functionName)
void RegisterOnChildRemove (Widget w, Managed eventHandler, string functionName)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnDrag (Widget w, int x, int y)
override bool OnDrop (Widget w, int x, int y, Widget reciever)
override bool OnDraggingOver (Widget w, int x, int y, Widget reciever)
override bool OnDropReceived (Widget w, int x, int y, Widget reciever)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override bool OnMouseWheel (Widget w, int x, int y, int wheel)
override bool OnChildAdd (Widget w, Widget child)
override bool OnChildRemove (Widget w, Widget child)
Static Private Member Functions
static WidgetEventHandler GetInstance ()
Private Attributes
protected ref map< Widget, ref Param > m_OnMouseButtonDownRegister
protected ref map< Widget, ref Param > m_OnMouseButtonUpRegister
protected ref map< Widget, ref Param > m_OnMouseWheel
protected ref map< Widget, ref Param > m_OnDropReceived
protected ref map< Widget, ref Param > m_OnDrag
protected ref map< Widget, ref Param > m_OnDrop
protected ref map< Widget, ref Param > m_OnDraggingOver
protected ref map< Widget, ref Param > m_OnMouseEnter
protected ref map< Widget, ref Param > m_OnMouseButtonLeave
protected ref map< Widget, ref Param > m_OnClick
protected ref map< Widget, ref Param > m_OnDoubleClick
protected ref map< Widget, ref Param > m_OnFocus
protected ref map< Widget, ref Param > m_OnFocusLost
protected ref map< Widget, ref Param > m_OnController
protected ref map< Widget, ref Param > m_OnChildAdd
protected ref map< Widget, ref Param > m_OnChildRemove
Static Private Attributes
private static ref WidgetEventHandler s_instance
Constructor & Destructor Documentation
WidgetEventHandler()
void WidgetEventHandler () inline private
References m_OnChildAdd, m_OnChildRemove, m_OnClick, m_OnController, m_OnDoubleClick, m_OnDrag, m_OnDraggingOver, m_OnDrop, m_OnDropReceived, m_OnFocus, m_OnFocusLost, m_OnMouseButtonDownRegister, m_OnMouseButtonLeave, m_OnMouseButtonUpRegister, m_OnMouseEnter, m_OnMouseWheel, and s_instance.
Member Function Documentation
GetInstance()
static WidgetEventHandler GetInstance () inline static private
References s_instance.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), CargoContainerRow::CargoContainerRow(), ClosableHeader::ClosableHeader(), ClosableContainer::ContainerWithCargo(), ClosableContainer::ContainerWithCargoAndAttachments(), Header::Header(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), Icon::InitEx(), ZombieContainer::InitGhostSlots(), Icon::InitLock(), Inventory(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), LeftArea::LeftArea(), PlayerContainer::PlayerContainer(), PlayerPreview::PlayerPreview(), VicinitySlotsContainer::RecomputeNumberOfContainers(), AttachmentCategoriesContainer::SetEntity(), SlotsIcon::SlotsIcon(), VicinityContainer::VicinityContainer(), VicinitySlotsContainer::VicinitySlotsContainer(), and ZombieContainer::ZombieContainer().
OnChildAdd()
override bool OnChildAdd (Widget w, Widget child) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), and m_OnChildAdd.
OnChildRemove()
override bool OnChildRemove (Widget w, Widget child) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), and m_OnChildRemove.
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnClick, x, and y.
OnDoubleClick()
override bool OnDoubleClick (Widget w, int x, int y, int button) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnDoubleClick, x, and y.
OnDrag()
override bool OnDrag (Widget w, int x, int y) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnDrag, x, and y.
OnDraggingOver()
override bool OnDraggingOver (Widget w, int x, int y, Widget reciever) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnDraggingOver, x, and y.
OnDrop()
override bool OnDrop (Widget w, int x, int y, Widget reciever) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnDrop, x, and y.
OnDropReceived()
override bool OnDropReceived (Widget w, int x, int y, Widget reciever) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnDropReceived, x, and y.
OnFocus()
override bool OnFocus (Widget w, int x, int y) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnFocus, x, and y.
OnFocusLost()
override bool OnFocusLost (Widget w, int x, int y) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnFocusLost, x, and y.
OnMouseButtonDown()
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnMouseButtonDownRegister, x, and y.
OnMouseButtonUp()
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnMouseButtonUpRegister, x, and y.
OnMouseEnter()
override bool OnMouseEnter (Widget w, int x, int y) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnMouseEnter, x, and y.
OnMouseLeave()
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnMouseButtonLeave, x, and y.
OnMouseWheel()
override bool OnMouseWheel (Widget w, int x, int y, int wheel) inline private
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnMouseWheel, x, and y.
RegisterOnChildAdd()
void RegisterOnChildAdd (Widget w, Managed eventHandler, string functionName) inline private
References m_OnChildAdd.
Referenced by LeftArea::LeftArea(), PlayerContainer::PlayerContainer(), AttachmentCategoriesContainer::SetEntity(), VicinityContainer::VicinityContainer(), and ZombieContainer::ZombieContainer().
RegisterOnChildRemove()
void RegisterOnChildRemove (Widget w, Managed eventHandler, string functionName) inline private
References m_OnChildRemove.
Referenced by LeftArea::LeftArea(), PlayerContainer::PlayerContainer(), AttachmentCategoriesContainer::SetEntity(), VicinityContainer::VicinityContainer(), and ZombieContainer::ZombieContainer().
RegisterOnClick()
void RegisterOnClick (Widget w, Managed eventHandler, string functionName) inline private
References m_OnClick.
Referenced by ClosableHeader::ClosableHeader().
RegisterOnDoubleClick()
void RegisterOnDoubleClick (Widget w, Managed eventHandler, string functionName) inline private
References m_OnDoubleClick.
Referenced by Attachments::InitAttachmentGrid(), Icon::InitEx(), ZombieContainer::InitGhostSlots(), PlayerContainer::PlayerContainer(), VicinitySlotsContainer::RecomputeNumberOfContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
RegisterOnDrag()
void RegisterOnDrag (Widget w, Managed eventHandler, string functionName) inline private
References m_OnDrag.
Referenced by ClosableHeader::ClosableHeader(), Icon::InitEx(), and SlotsIcon::SlotsIcon().
RegisterOnDraggingOver()
void RegisterOnDraggingOver (Widget w, Managed eventHandler, string functionName) inline private
References m_OnDraggingOver.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), CargoContainerRow::CargoContainerRow(), ClosableContainer::ContainerWithCargo(), ClosableContainer::ContainerWithCargoAndAttachments(), Header::Header(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), Icon::InitEx(), ZombieContainer::InitGhostSlots(), Icon::InitLock(), Inventory(), PlayerContainer::PlayerContainer(), VicinitySlotsContainer::RecomputeNumberOfContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
RegisterOnDrop()
void RegisterOnDrop (Widget w, Managed eventHandler, string functionName) inline private
References m_OnDrop.
Referenced by ClosableHeader::ClosableHeader(), AttachmentCategoriesRow::Init(), Icon::InitEx(), and SlotsIcon::SlotsIcon().
RegisterOnDropReceived()
void RegisterOnDropReceived (Widget w, Managed eventHandler, string functionName) inline private
References m_OnDropReceived.
Referenced by CargoContainerRow::CargoContainerRow(), Header::Header(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), Icon::InitEx(), ZombieContainer::InitGhostSlots(), Icon::InitLock(), Inventory(), PlayerContainer::PlayerContainer(), VicinitySlotsContainer::RecomputeNumberOfContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
RegisterOnFocus()
void RegisterOnFocus (Widget w, Managed eventHandler, string functionName) inline private
References m_OnFocus.
RegisterOnFocusLost()
void RegisterOnFocusLost (Widget w, Managed eventHandler, string functionName) inline private
References m_OnFocusLost.
RegisterOnMouseButtonDown()
void RegisterOnMouseButtonDown (Widget w, Managed eventHandler, string functionName) inline private
References m_OnMouseButtonDownRegister.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), Header::Header(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), Icon::InitEx(), ZombieContainer::InitGhostSlots(), Icon::InitLock(), PlayerContainer::PlayerContainer(), PlayerPreview::PlayerPreview(), VicinitySlotsContainer::RecomputeNumberOfContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
RegisterOnMouseButtonUp()
void RegisterOnMouseButtonUp (Widget w, Managed eventHandler, string functionName) inline private
References m_OnMouseButtonUpRegister.
Referenced by ZombieContainer::InitGhostSlots(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), VicinitySlotsContainer::RecomputeNumberOfContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
RegisterOnMouseEnter()
void RegisterOnMouseEnter (Widget w, Managed eventHandler, string functionName) inline private
References m_OnMouseEnter.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), ClosableHeader::ClosableHeader(), Icon::InitEx(), and SlotsIcon::SlotsIcon().
RegisterOnMouseLeave()
void RegisterOnMouseLeave (Widget w, Managed eventHandler, string functionName) inline private
References m_OnMouseButtonLeave.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), ClosableHeader::ClosableHeader(), Icon::InitEx(), and SlotsIcon::SlotsIcon().
RegisterOnMouseWheel()
void RegisterOnMouseWheel (Widget w, Managed eventHandler, string functionName) inline private
References m_OnMouseWheel.
Referenced by PlayerPreview::PlayerPreview().
UnregisterWidget()
void UnregisterWidget (Widget w) inline private
References m_OnChildAdd, m_OnChildRemove, m_OnClick, m_OnController, m_OnDoubleClick, m_OnDrag, m_OnDraggingOver, m_OnDrop, m_OnDropReceived, m_OnFocus, m_OnFocusLost, m_OnMouseButtonDownRegister, m_OnMouseButtonLeave, m_OnMouseButtonUpRegister, m_OnMouseEnter, and m_OnMouseWheel.
Field Documentation
m_OnChildAdd
protected ref map<Widget, ref Param> m_OnChildAdd private
Referenced by OnChildAdd(), RegisterOnChildAdd(), UnregisterWidget(), and WidgetEventHandler().
m_OnChildRemove
protected ref map<Widget, ref Param> m_OnChildRemove private
Referenced by OnChildRemove(), RegisterOnChildRemove(), UnregisterWidget(), and WidgetEventHandler().
m_OnClick
protected ref map<Widget, ref Param> m_OnClick private
Referenced by OnClick(), RegisterOnClick(), UnregisterWidget(), and WidgetEventHandler().
m_OnController
protected ref map<Widget, ref Param> m_OnController private
Referenced by UnregisterWidget(), and WidgetEventHandler().
m_OnDoubleClick
protected ref map<Widget, ref Param> m_OnDoubleClick private
Referenced by OnDoubleClick(), RegisterOnDoubleClick(), UnregisterWidget(), and WidgetEventHandler().
m_OnDrag
protected ref map<Widget, ref Param> m_OnDrag private
Referenced by OnDrag(), RegisterOnDrag(), UnregisterWidget(), and WidgetEventHandler().
m_OnDraggingOver
protected ref map<Widget, ref Param> m_OnDraggingOver private
Referenced by OnDraggingOver(), RegisterOnDraggingOver(), UnregisterWidget(), and WidgetEventHandler().
m_OnDrop
protected ref map<Widget, ref Param> m_OnDrop private
Referenced by OnDrop(), RegisterOnDrop(), UnregisterWidget(), and WidgetEventHandler().
m_OnDropReceived
protected ref map<Widget, ref Param> m_OnDropReceived private
Referenced by OnDropReceived(), RegisterOnDropReceived(), UnregisterWidget(), and WidgetEventHandler().
m_OnFocus
protected ref map<Widget, ref Param> m_OnFocus private
Referenced by OnFocus(), RegisterOnFocus(), UnregisterWidget(), and WidgetEventHandler().
m_OnFocusLost
protected ref map<Widget, ref Param> m_OnFocusLost private
Referenced by OnFocusLost(), RegisterOnFocusLost(), UnregisterWidget(), and WidgetEventHandler().
m_OnMouseButtonDownRegister
protected ref map<Widget, ref Param> m_OnMouseButtonDownRegister private
Referenced by OnMouseButtonDown(), RegisterOnMouseButtonDown(), UnregisterWidget(), and WidgetEventHandler().
m_OnMouseButtonLeave
protected ref map<Widget, ref Param> m_OnMouseButtonLeave private
Referenced by OnMouseLeave(), RegisterOnMouseLeave(), UnregisterWidget(), and WidgetEventHandler().
m_OnMouseButtonUpRegister
protected ref map<Widget, ref Param> m_OnMouseButtonUpRegister private
Referenced by OnMouseButtonUp(), RegisterOnMouseButtonUp(), UnregisterWidget(), and WidgetEventHandler().
m_OnMouseEnter
protected ref map<Widget, ref Param> m_OnMouseEnter private
Referenced by OnMouseEnter(), RegisterOnMouseEnter(), UnregisterWidget(), and WidgetEventHandler().
m_OnMouseWheel
protected ref map<Widget, ref Param> m_OnMouseWheel private
Referenced by OnMouseWheel(), RegisterOnMouseWheel(), UnregisterWidget(), and WidgetEventHandler().
s_instance
private static ref WidgetEventHandler s_instance static private
Referenced by GetInstance(), and WidgetEventHandler().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/WidgetEventHandler.c