DayZ Scripts: UniversalTemperatureSource Class Reference
UniversalTemperatureSource Class Reference
original Timer deletes m_params which is unwanted
Private Member Functions
override void OnTimer ()
override void Stop ()
void SetParams (Param params)
Detailed Description
original Timer deletes m_params which is unwanted
Definition at line 27 of file UniversalTemperatureSource.c.
Member Function Documentation
OnTimer()
override void OnTimer () inline private
Definition at line 29 of file UniversalTemperatureSource.c.
References ScriptModule::CallFunction(), ScriptModule::CallFunctionParams(), CGame::GameScript, and GetGame().
SetParams()
void SetParams (Param params) inline private
Definition at line 47 of file UniversalTemperatureSource.c.
Stop()
override void Stop () inline private
Definition at line 41 of file UniversalTemperatureSource.c.
References m_time, and SetRunning().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/UniversalTemperatureSource/UniversalTemperatureSource.c