DayZ Scripts: FeverMdfr Class Reference
FeverMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnActivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
private float m_Time
private float m_NextEvent
Static Private Attributes
static const float EVENT_INTERVAL_MIN = 12
static const float EVENT_INTERVAL_MAX = 18
Detailed Description
Definition at line 1 of file Fever.c.
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
Definition at line 17 of file Fever.c.
Referenced by DeactivateCondition().
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
Definition at line 44 of file Fever.c.
References ActivateCondition().
Init()
override void Init () inline private
Definition at line 10 of file Fever.c.
References DEFAULT_TICK_TIME_ACTIVE_SHORT, DEFAULT_TICK_TIME_INACTIVE, m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void OnActivate (PlayerBase player) inline private
Definition at line 22 of file Fever.c.
OnDeactivate()
override void OnDeactivate (PlayerBase player) inline private
Definition at line 36 of file Fever.c.
OnReconnect()
override void OnReconnect (PlayerBase player) inline private
Definition at line 30 of file Fever.c.
References OnActivate().
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
Definition at line 49 of file Fever.c.
References EVENT_INTERVAL_MAX, EVENT_INTERVAL_MIN, m_NextEvent, m_Time, Math::RandomFloatInclusive(), and PlayerConstants::WATER_LOSS_FEVER.
Field Documentation
EVENT_INTERVAL_MAX
const float EVENT_INTERVAL_MAX = 18 static private
Definition at line 7 of file Fever.c.
Referenced by OnTick().
EVENT_INTERVAL_MIN
const float EVENT_INTERVAL_MIN = 12 static private
Definition at line 6 of file Fever.c.
Referenced by OnTick().
m_NextEvent
private float m_NextEvent private
Definition at line 4 of file Fever.c.
Referenced by OnTick().
m_Time
private float m_Time private
Definition at line 3 of file Fever.c.
Referenced by OnTick().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/conditions/Fever.c