DayZ Scripts: FuelStation Class Reference
FuelStation Class Reference
Private Member Functions
override void EEKilled (Object killer)
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
bool HasFuelToGive ()
Returns true if this stand is functional.
Member Function Documentation
EEKilled()
override void EEKilled (Object killer) inline private
References Explode().
HasFuelToGive()
bool HasFuelToGive () inline private
Returns true if this stand is functional.
OnExplosionEffects()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) inline private
References ParticleList::EXPLOSION_LANDMINE, GetGame(), ParticleList::IMPACT_GRAVEL_RICOCHET, ParticleList::IMPACT_METAL_RICOCHET, ParticleManager(), ParticleList::SMOKE_GENERIC_WRECK, and vector::VectorToAngles().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Building/Specific/Land_FuelStation_Feed.c