DayZ Scripts: CCTBase Class Reference
CCTBase Class Reference
Private Member Functions
bool Can (PlayerBase player, ActionTarget target)
bool CanContinue (PlayerBase player, ActionTarget target)
Member Function Documentation
Can()
bool Can (PlayerBase player, ActionTarget target) inline private
Referenced by Can(), and CanContinue().
CanContinue()
bool CanContinue (PlayerBase player, ActionTarget target) inline private
References Can().
Referenced by CanContinue().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/TargetConditionsComponents/CCTBase.c