DayZ Scripts: Material Class Reference
Material Class Reference
Private Member Functions
proto bool SetParam (string propertyName, void value)
proto native void ResetParam (string propertyName)
proto native int GetParamIndex (string paramName)
proto void SetParamByIndex (int paramIndex, void value)
Member Function Documentation
GetParamIndex()
proto native int GetParamIndex (string paramName) private
set parametr index for faster access to material properties
Parameters
paramName name of parameter
Returns
parameter index
ResetParam()
proto native void ResetParam (string propertyName) private
reset parametr of material to default value
Parameters
paramName name of parameter
SetParam()
proto bool SetParam (string propertyName, void value) private
set parametr of material by string name
Parameters
paramName name of parameter
value value
Referenced by PPEffects::FlashbangEffect(), PPEffects::HitEffect(), PPEffects::PerformSetLensEffect(), PPEffects::ResetColorize(), PPEffects::SetBloom(), PPEffects::SetBlur(), PPEffects::SetChromAbb(), PPEffects::SetNVParams(), PPEffects::SetRadialBlur(), PPEffects::SetVignette(), PPEffects::UpdateColor(), PPEffects::UpdateColorize(), and PPEffects::UpdateSaturation().
SetParamByIndex()
proto void SetParamByIndex (int paramIndex, void value) private
set parametr of material by index
Parameters
paramName name of parameter
value value
Referenced by PPEClassBase::SetFinalParameterValue().
The documentation for this class was generated from the following file:
P:/scripts/1_core/proto/proto.c