DayZ Scripts: ActionDismantlePart Class Reference
ActionDismantlePart Class Reference
Private Member Functions
void ActionDismantlePart ()
override void CreateConditionComponents ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override string GetText ()
override bool CanBeUsedLeaning ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
protected void SetBuildingAnimation (ItemBase item)
protected bool DismantleCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check)
override string GetAdminLogMessage (ActionData action_data)
Constructor & Destructor Documentation
ActionDismantlePart()
void ActionDismantlePart () inline private
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References DismantleCondition().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
References DismantleCondition(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
CanBeUsedLeaning()
override bool CanBeUsedLeaning () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References m_ConditionItem, and m_ConditionTarget.
DismantleCondition()
protected bool DismantleCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check) inline private
References Class::CastTo(), Construction(), GetGame(), ConstructionPart::IsBase(), BaseBuildingBase::IsFacingCamera(), ConstructionPart::IsGate(), BaseBuildingBase::IsOpened(), BaseBuildingBase::IsPlayerInside(), and ConstructionActionData::SetTargetPart().
Referenced by ActionCondition(), and ActionConditionContinue().
GetAdminLogMessage()
override string GetAdminLogMessage (ActionData action_data) inline private
References ConstructionPart::GetName(), ConstructionActionData::GetTargetPart(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
GetText()
override string GetText () inline private
References GetGame(), ConstructionPart::GetName(), GetPlayer(), and ConstructionActionData::GetTargetPart().
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
References ConstructionPart::GetName(), ConstructionActionData::GetTargetPart(), and m_Text.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References AT_DISMANTLE_PART, Construction(), UADamageApplied::DISMANTLE, ConstructionPart::GetPartName(), ConstructionActionData::GetTargetPart(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
SetBuildingAnimation()
protected void SetBuildingAnimation (ItemBase item) inline private
References AnimatedActionBase::m_CommandUID.
Referenced by SetupAction().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
References SetBuildingAnimation().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Continuous/ActionDismantlePart.c