DayZ Scripts: RainProcurementComponentBase Class Reference
RainProcurementComponentBase Class Reference
Private Member Functions
void RainProcurementComponentBase (ItemBase procuringItem)
void StartRainProcurement ()
Called on server to queue rain procurement (on next cycle end)
void StopRainProcurement ()
Called on server to queue rain procurement removal (on next cycle end)
void OnUpdate (float deltaTime, float amount)
protected void Reset ()
protected void ProcureLiquid (float amountBase, int liquidType=LIQUID_WATER)
protected void UpdateIsUnderRoof ()
float GetBaseLiquidAmount ()
override this to get different amount per ProcureLiquid cycle
bool IsActive ()
void SetActive (bool run)
Private Attributes
protected ItemBase m_ProcuringItem
protected RainProcurementHandler m_Handler
protected bool m_IsUnderRoof
protected bool m_IsActive
protected int m_UpdateCounter
protected const int UPDATE_ROOFCHECK_COUNT = 3
Detailed Description
Definition at line 1 of file RainProcurementComponent.c.
Constructor & Destructor Documentation
RainProcurementComponentBase()
void RainProcurementComponentBase (ItemBase procuringItem) inline private
Definition at line 10 of file RainProcurementComponent.c.
References GetGame(), m_Handler, m_ProcuringItem, and Reset().
Member Function Documentation
GetBaseLiquidAmount()
float GetBaseLiquidAmount () inline private
override this to get different amount per ProcureLiquid cycle
Definition at line 70 of file RainProcurementComponent.c.
References GameConstants::LIQUID_RAIN_AMOUNT_COEF_BASE.
Referenced by ProcureLiquid().
IsActive()
bool IsActive () inline private
Definition at line 75 of file RainProcurementComponent.c.
References m_IsActive.
Referenced by StopRainProcurement().
OnUpdate()
void OnUpdate (float deltaTime, float amount) inline private
Definition at line 39 of file RainProcurementComponent.c.
References m_UpdateCounter, ProcureLiquid(), UPDATE_ROOFCHECK_COUNT, and UpdateIsUnderRoof().
ProcureLiquid()
protected void ProcureLiquid (float amountBase, int liquidType = LIQUID_WATER) inline private
Definition at line 55 of file RainProcurementComponent.c.
References Liquid::FillContainerEnviro(), GetBaseLiquidAmount(), m_IsUnderRoof, and m_ProcuringItem.
Referenced by OnUpdate().
Reset()
protected void Reset () inline private
Definition at line 50 of file RainProcurementComponent.c.
References m_UpdateCounter.
Referenced by RainProcurementComponentBase(), SetActive(), and StartRainProcurement().
SetActive()
void SetActive (bool run) inline private
Definition at line 80 of file RainProcurementComponent.c.
References m_IsActive, and Reset().
StartRainProcurement()
void StartRainProcurement () inline private
Called on server to queue rain procurement (on next cycle end)
Definition at line 18 of file RainProcurementComponent.c.
References m_Handler, RainProcurementHandler::QueueStart(), Reset(), and SetActive().
Referenced by Barrel_ColorBase::Open(), and Barrel_ColorBase::OpenLoad().
StopRainProcurement()
void StopRainProcurement () inline private
Called on server to queue rain procurement removal (on next cycle end)
Definition at line 28 of file RainProcurementComponent.c.
References IsActive(), m_Handler, RainProcurementHandler::QueueStop(), and SetActive().
Referenced by Barrel_ColorBase::Close(), and Barrel_ColorBase::CloseLoad().
UpdateIsUnderRoof()
protected void UpdateIsUnderRoof () inline private
Definition at line 64 of file RainProcurementComponent.c.
References m_IsUnderRoof, and m_ProcuringItem.
Referenced by OnUpdate().
Field Documentation
m_Handler
protected RainProcurementHandler m_Handler private
Definition at line 4 of file RainProcurementComponent.c.
Referenced by RainProcurementComponentBase(), StartRainProcurement(), and StopRainProcurement().
m_IsActive
protected bool m_IsActive private
Definition at line 6 of file RainProcurementComponent.c.
Referenced by IsActive(), and SetActive().
m_IsUnderRoof
protected bool m_IsUnderRoof private
Definition at line 5 of file RainProcurementComponent.c.
Referenced by ProcureLiquid(), and UpdateIsUnderRoof().
m_ProcuringItem
protected ItemBase m_ProcuringItem private
Definition at line 3 of file RainProcurementComponent.c.
Referenced by ProcureLiquid(), RainProcurementComponentBase(), and UpdateIsUnderRoof().
m_UpdateCounter
protected int m_UpdateCounter private
Definition at line 7 of file RainProcurementComponent.c.
Referenced by OnUpdate(), and Reset().
UPDATE_ROOFCHECK_COUNT
protected const int UPDATE_ROOFCHECK_COUNT = 3 private
Definition at line 8 of file RainProcurementComponent.c.
Referenced by OnUpdate().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/RainProcurementComponent.c