DayZ Scripts: HumanCommandVehicle Class Reference
HumanCommandVehicle Class Reference
Private Member Functions
private void HumanCommandVehicle ()
private void ~HumanCommandVehicle ()
proto native Transport GetTransport ()
proto native int GetVehicleClass ()
proto native int GetVehicleSeat ()
proto native void SetVehicleType (int pVehicleType)
proto native int GetVehicleType ()
proto native void GetOutVehicle ()
proto native void KnockedOutVehicle ()
proto native bool ShouldBeKnockedOut ()
proto native void JumpOutVehicle ()
proto native void SwitchSeat (int pTransportPositionIndex, int pVehicleSeat)
proto native bool IsGettingIn ()
proto native bool IsGettingOut ()
proto native bool IsSwitchSeat ()
proto native bool WasGearChange ()
proto native void SetClutchState (bool pState)
proto native void KeepInVehicleSpaceAfterLeave (bool pState)
proto native void ProcessLeaveEvents ()
bool IsObjectIgnoredOnGettingOut (IEntity entity)
Constructor & Destructor Documentation
HumanCommandVehicle()
private void HumanCommandVehicle () inline private
~HumanCommandVehicle()
private void ~HumanCommandVehicle () inline private
Member Function Documentation
GetOutVehicle()
proto native void GetOutVehicle () private
Referenced by ActionGetOutTransport::OnStart().
GetTransport()
proto native Transport GetTransport () private
Referenced by ActionCarHornBase::ActionCondition(), ActionCondition(), ActionGetOutTransport::ActionCondition(), ActionSwitchLights::ActionCondition(), ActionStopEngine::ActionCondition(), ActionStopEngineBoat::ActionCondition(), DayZPlayer::CameraHandler(), ManBase::CommandHandler(), DayZPlayerCamera3rdPersonVehicle(), CAContinuousRepeatStartEngine::Execute(), DeveloperTeleport::GetPlayerRootForTeleporting(), DayZPlayer::HandleDeath(), EntityAI::IsIgnoredObject(), IsObjectIgnoredOnGettingOut(), OnEndServer(), ActionStopEngineBoat::OnExecute(), OnExecuteServer(), ActionSwitchLights::OnExecuteServer(), ActionStopEngine::OnExecuteServer(), OnFinishProgress(), OnFinishProgressServer(), ActionGetOutTransport::OnStart(), ActionGetOutTransport::OnStartServer(), ManBase::ResetPlayer(), ActionGetOutTransport::SetupAction(), Hud::ShowVehicleInfo(), BoatHud::ShowVehicleInfo(), CarHud::ShowVehicleInfo(), CarHornShortActionInput::UpdatePossibleActions(), and ToggleLightsActionInput::UpdatePossibleActions().
GetVehicleClass()
proto native int GetVehicleClass () private
GetVehicleSeat()
proto native int GetVehicleSeat () private
Referenced by ActionStopEngine::ActionCondition(), and ActionStopEngineBoat::ActionCondition().
GetVehicleType()
proto native int GetVehicleType () private
IsGettingIn()
proto native bool IsGettingIn () private
Referenced by ManBase::CommandHandler(), DayZPlayer::HandleDamageHit(), DayZPlayer::HandleDeath(), and DayZPlayer::HeadingModel().
IsGettingOut()
proto native bool IsGettingOut () private
Referenced by DayZPlayer::CommandHandler(), ManBase::CommandHandler(), DayZPlayer::HandleDamageHit(), DayZPlayer::HandleDeath(), and DayZPlayer::HeadingModel().
IsObjectIgnoredOnGettingOut()
bool IsObjectIgnoredOnGettingOut (IEntity entity) inline private
References Class::CastTo(), GetParent(), and GetTransport().
IsSwitchSeat()
proto native bool IsSwitchSeat () private
Referenced by ManBase::CommandHandler(), and ActionSwitchSeats::OnUpdate().
JumpOutVehicle()
proto native void JumpOutVehicle () private
Referenced by ActionGetOutTransport::OnStart().
KeepInVehicleSpaceAfterLeave()
proto native void KeepInVehicleSpaceAfterLeave (bool pState) private
KnockedOutVehicle()
proto native void KnockedOutVehicle () private
ProcessLeaveEvents()
proto native void ProcessLeaveEvents () private
Referenced by DayZPlayer::CommandHandler().
SetClutchState()
proto native void SetClutchState (bool pState) private
Referenced by GearChangeActionCallback::OnFinish(), and GearChangeActionCallback::SetVehicleCommand().
SetVehicleType()
proto native void SetVehicleType (int pVehicleType) private
Referenced by ActionGetInTransport::Start().
ShouldBeKnockedOut()
proto native bool ShouldBeKnockedOut () private
SwitchSeat()
proto native void SwitchSeat (int pTransportPositionIndex, int pVehicleSeat) private
Referenced by ActionSwitchSeats::OnStart().
WasGearChange()
proto native bool WasGearChange () private
Referenced by DayZPlayer::CommandHandler().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/human.c