DayZ Scripts: CfgParam Class Reference
CfgParam Class Reference
Private Member Functions
void CfgParam (string param_name)
void SetName (string param_name)
string GetName ()
int GetType ()
bool IsArray ()
void CfgParamArray (string param_name)
void ~CfgParamArray ()
void Clear ()
array< ref CfgParam > GetValues ()
CfgParam GetValue (int i)
void InsertValue (CfgParam value)
bool IsParamExist (string name, int cfg_type)
bool RenameParam (string name, int cfg_type, string new_name)
CfgParam GetValueByName (string name, int cfg_type)
void SetParams (array< ref CfgParam > value_array)
bool IsValueArray ()
override int GetType ()
void CfgParamType (string param_name)
Static Private Member Functions
static CfgParam CreateParam (string name, int cfg_type)
Private Attributes
protected string m_ParamName
protected string m_ParamValueString
private ref array< ref CfgParam > m_Values
Constructor & Destructor Documentation
CfgParam()
void CfgParam (string param_name) inline private
References m_ParamName.
~CfgParamArray()
void ~CfgParamArray () inline private
References Clear(), and m_Values.
Member Function Documentation
CfgParamArray()
void CfgParamArray (string param_name) inline private
References m_Values.
Referenced by CreateParam().
CfgParamType()
void CfgParamType (string param_name) inline private
Clear()
void Clear () inline private
References m_Values.
Referenced by ~CfgParamArray().
CreateParam()
static CfgParam CreateParam (string name, int cfg_type) inline static private
References CFG_TYPE_ARRAY, CFG_TYPE_BOOL, CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, CfgParamArray(), and name.
Referenced by PluginFileHandler::GetParamByName(), and GetValueByName().
GetName()
string GetName () inline private
References m_ParamName.
Referenced by PluginFileHandler::GetParamByName(), GetValueByName(), IsParamExist(), PluginFileHandler::ParamExist(), PluginFileHandler::ParseParam(), PluginFileHandler::RemoveParamByName(), RenameParam(), and PluginFileHandler::RenameParam().
GetType() [1/2]
int GetType () inline private
Referenced by PluginFileHandler::ParseParam().
GetType() [2/2]
override int GetType () inline private
References CFG_TYPE_ARRAY.
GetValue()
CfgParam GetValue (int i) inline private
References m_Values.
GetValueByName()
CfgParam GetValueByName (string name, int cfg_type) inline private
References CreateParam(), GetName(), m_Values, and name.
GetValues()
array< ref CfgParam > GetValues () inline private
References m_Values.
InsertValue()
void InsertValue (CfgParam value) inline private
References m_Values.
IsArray()
bool IsArray () inline private
IsParamExist()
bool IsParamExist (string name, int cfg_type) inline private
References GetName(), m_Values, and name.
IsValueArray()
bool IsValueArray () inline private
RenameParam()
bool RenameParam (string name, int cfg_type, string new_name) inline private
References GetName(), m_Values, name, and SetName().
SetName()
void SetName (string param_name) inline private
References m_ParamName.
Referenced by PluginFileHandler::ParseText(), RenameParam(), and PluginFileHandler::RenameParam().
SetParams()
void SetParams (array< ref CfgParam > value_array) inline private
References m_Values.
Field Documentation
m_ParamName
protected string m_ParamName private
Referenced by CfgParam(), GetName(), and SetName().
m_ParamValueString
protected string m_ParamValueString private
m_Values
private ref array<ref CfgParam> m_Values private
Referenced by GetValues().
The documentation for this class was generated from the following files:
4_World/Classes/ConfigHandler/CfgParam.c
4_World/Classes/ConfigHandler/CfgParamArray.c
4_World/Classes/ConfigHandler/CfgParamType.c