DayZ Scripts: SlotsIcon Class Reference
SlotsIcon Class Reference
Private Member Functions
void SlotsIcon (LayoutHolder parent, Widget root, int index, EntityAI slot_parent)
override bool IsVisible ()
void SetSlotParent (EntityAI parent)
void SetContainer (Container container)
void SetSlotDisplayName (string text)
Container GetContainer ()
string GetSlotDisplayName ()
void SetSlotDesc (string text)
string GetSlotDesc ()
void ~SlotsIcon ()
EntityAI GetSlotParent ()
int GetSlotID ()
void SetSlotID (int slot_ID)
bool IsReserved ()
Widget GetPanelWidget ()
Widget GetCursorWidget ()
Widget GetColWidget ()
Widget GetReservedWidget ()
Widget GetMountedWidget ()
ItemPreviewWidget GetRender ()
ImageWidget GetGhostSlot ()
Widget GetColorWidget ()
Widget GetSelectedPanel ()
Widget GetEmptySelectedPanel ()
Widget GetQuantityPanel ()
Widget GetOutOfReachWidget ()
TextWidget GetQuantityItem ()
ProgressBarWidget GetQuantityProgress ()
Widget GetQuantityStack ()
Widget GetItemSizePanel ()
TextWidget GetItemSizeWidget ()
Widget GetAmmoIcon ()
Widget GetRadialIconPanel ()
Widget GetRadialIconClosed ()
Widget GetRadialIcon ()
override void SetActive (bool active)
override void SetLayoutName ()
override void Refresh ()
void SetTemperature ()
Object GetObject ()
EntityAI GetEntity ()
ItemBase GetItem ()
void RefreshMuzzleIcon ()
void SetQuantity ()
void SetItemPreview ()
void SetItemSize ()
void UpdateFlip (bool flipped)
void Init (EntityAI obj, bool reservation=false)
void Clear ()
void CheckIsWeapon ()
void CheckIsMagazine ()
void CheckHasTemperature ()
void CheckHasQuantity ()
void CheckHasItemSize ()
bool IsOutOfReach ()
bool MouseEnter (Widget w, int x, int y)
bool MouseEnterGhostSlot (Widget w, int x, int y)
bool MouseLeave (Widget w, Widget s, int x, int y)
bool MouseLeaveGhostSlot (Widget w, Widget s, int x, int y)
override void UpdateInterval ()
void OnIconDrag (Widget w)
void OnIconDrop (Widget w)
Static Private Member Functions
static int GetNormalWidth ()
static int GetNormalHeight ()
Private Attributes
protected bool m_IsWeapon = false
protected bool m_IsMagazine = false
protected bool m_HasTemperature = false
protected bool m_HasQuantity = false
protected bool m_HasItemSize = false
protected float m_CurrQuantity = -1
protected EntityAI m_Obj
protected ItemBase m_Item
protected EntityAI m_SlotParent
protected Container m_Container
protected int m_SlotID
protected bool m_IsDragged = false
protected Widget m_PanelWidget
protected Widget m_CursorWidget
protected Widget m_ColWidget
protected Widget m_MountedWidget
protected Widget m_OutOfReachWidget
protected Widget m_ReservedWidget
protected ItemPreviewWidget m_ItemPreview
protected ImageWidget m_GhostSlot
protected Widget m_ColorWidget
protected Widget m_SelectedPanel
protected Widget m_EmptySelectedPanel
protected Widget m_QuantityPanel
protected TextWidget m_QuantityItem
protected ProgressBarWidget m_QuantityProgress
protected Widget m_QuantityStack
protected string m_SlotDisplayName
protected string m_SlotDesc
protected Widget m_ItemSizePanel
protected TextWidget m_ItemSizeWidget
protected Widget m_AmmoIcon
protected Widget m_RadialIconPanel
protected Widget m_RadialIconClosed
protected Widget m_RadialIcon
protected bool m_Reserved
Static Private Attributes
static protected int m_NormalWidth
static protected int m_NormalHeight
Detailed Description
Definition at line 1 of file SlotsIcon.c.
Constructor & Destructor Documentation
SlotsIcon()
void SlotsIcon (LayoutHolder parent, Widget root, int index, EntityAI slot_parent) inline private
Definition at line 54 of file SlotsIcon.c.
References GetGame(), WidgetEventHandler::GetInstance(), m_AmmoIcon, m_ColorWidget, m_ColWidget, m_Container, m_CursorWidget, m_EmptySelectedPanel, m_GhostSlot, m_Item, m_ItemPreview, m_ItemSizePanel, m_ItemSizeWidget, m_MountedWidget, m_NormalHeight, m_NormalWidth, m_Obj, m_OutOfReachWidget, m_PanelWidget, m_QuantityItem, m_QuantityPanel, m_QuantityProgress, m_QuantityStack, m_RadialIcon, m_RadialIconClosed, m_RadialIconPanel, m_Reserved, m_ReservedWidget, m_SelectedPanel, m_SlotID, m_SlotParent, WidgetEventHandler::RegisterOnDrag(), WidgetEventHandler::RegisterOnDrop(), WidgetEventHandler::RegisterOnMouseEnter(), WidgetEventHandler::RegisterOnMouseLeave(), SetActive(), ItemPreviewWidget::SetForceFlip(), and ItemPreviewWidget::SetForceFlipEnable().
~SlotsIcon()
void ~SlotsIcon () inline private
Definition at line 169 of file SlotsIcon.c.
References ItemManager::GetInstance(), ItemManager::HideDropzones(), m_IsDragged, m_Obj, ItemManager::SetIsDragging(), SetItemPreview(), and UpdateFlip().
Member Function Documentation
CheckHasItemSize()
void CheckHasItemSize () inline private
Definition at line 597 of file SlotsIcon.c.
References CGame::ConfigIsExisting(), GetGame(), m_HasItemSize, and m_Obj.
Referenced by Init().
CheckHasQuantity()
void CheckHasQuantity () inline private
Definition at line 585 of file SlotsIcon.c.
References QuantityConversions::HasItemQuantity(), m_HasQuantity, m_Item, m_QuantityPanel, and QUANTITY_HIDDEN.
Referenced by Init().
CheckHasTemperature()
void CheckHasTemperature () inline private
Definition at line 577 of file SlotsIcon.c.
References m_HasTemperature, and m_Item.
Referenced by Init().
CheckIsMagazine()
void CheckIsMagazine () inline private
Definition at line 572 of file SlotsIcon.c.
References m_IsMagazine, and m_Obj.
Referenced by Init().
CheckIsWeapon()
void CheckIsWeapon () inline private
Definition at line 567 of file SlotsIcon.c.
References m_IsWeapon, and m_Obj.
Referenced by Init().
Clear()
void Clear () inline private
Definition at line 502 of file SlotsIcon.c.
References CancelWidgetDragging(), ItemManager::GetInstance(), GetSlotID(), InventorySlots::GetStackMaxForSlotId(), m_AmmoIcon, m_ColorWidget, m_ColWidget, m_Container, m_CurrQuantity, m_EmptySelectedPanel, m_GhostSlot, m_HasItemSize, m_HasQuantity, m_HasTemperature, m_IsDragged, m_IsMagazine, m_IsWeapon, m_Item, m_ItemPreview, m_ItemSizePanel, m_MountedWidget, m_Obj, m_OutOfReachWidget, m_PanelWidget, m_QuantityItem, m_QuantityPanel, m_QuantityProgress, m_QuantityStack, m_RadialIconPanel, m_ReservedWidget, m_SelectedPanel, OnIconDrop(), Refresh(), ItemPreviewWidget::SetItem(), SetItemPreview(), ItemManager::SetWidgetDraggable(), and UpdateFlip().
Referenced by Attachments::AttachmentRemoved(), Init(), Attachments::InitAttachmentGrid(), ZombieContainer::InitGhostSlots(), PlayerContainer::ItemDetached(), ZombieContainer::ItemDetached(), Attachments::OnAttachmentReservationRelease(), PlayerContainer::OnAttachmentReservationRelease(), PlayerContainer::PlayerContainer(), AttachmentCategoriesRow::RefreshSlot(), PlayerContainer::SetPlayer(), and VicinitySlotsContainer::ShowItemsInContainers().
GetAmmoIcon()
Widget GetAmmoIcon () inline private
Definition at line 290 of file SlotsIcon.c.
References m_AmmoIcon.
GetColorWidget()
Widget GetColorWidget () inline private
Definition at line 240 of file SlotsIcon.c.
References m_ColorWidget.
GetColWidget()
Widget GetColWidget () inline private
Definition at line 215 of file SlotsIcon.c.
References m_ColWidget.
GetContainer()
Container GetContainer () inline private
Definition at line 149 of file SlotsIcon.c.
References m_Container.
Referenced by AttachmentCategoriesContainer::CanOpenCloseContainerEx(), ZombieContainer::CanOpenCloseContainerEx(), AttachmentCategoriesContainer::ExpandCollapseContainer(), AttachmentCategoriesContainer::MouseClick(), AttachmentCategoriesRow::OnMouseButtonDown(), and ZombieContainer::ToggleContainer().
GetCursorWidget()
Widget GetCursorWidget () inline private
Definition at line 210 of file SlotsIcon.c.
References m_CursorWidget.
Referenced by Attachments::SelectItem(), SlotsContainer::SelectItem(), and SlotsContainer::UpdateIcon().
GetEmptySelectedPanel()
Widget GetEmptySelectedPanel () inline private
Definition at line 250 of file SlotsIcon.c.
References m_EmptySelectedPanel.
GetEntity()
EntityAI GetEntity () inline private
Definition at line 353 of file SlotsIcon.c.
References m_Obj.
Referenced by PlayerContainer::DraggingOver(), HandsContainer::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), AttachmentCategoriesRow::RefreshSlot(), PlayerContainer::Select(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), ZombieContainer::ToggleContainer(), and Attachments::UpdateInterval().
GetGhostSlot()
ImageWidget GetGhostSlot () inline private
Definition at line 235 of file SlotsIcon.c.
References m_GhostSlot.
Referenced by AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), AttachmentCategoriesContainer::LoadAttachmentCategoriesIcon(), PlayerContainer::PlayerContainer(), VicinitySlotsContainer::RecomputeNumberOfContainers(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
GetItem()
ItemBase GetItem () inline private
Definition at line 358 of file SlotsIcon.c.
References m_Item.
Referenced by AttachmentCategoriesRow::OnMouseButtonDown().
GetItemSizePanel()
Widget GetItemSizePanel () inline private
Definition at line 280 of file SlotsIcon.c.
References m_ItemSizePanel.
GetItemSizeWidget()
TextWidget GetItemSizeWidget () inline private
Definition at line 285 of file SlotsIcon.c.
References m_ItemSizeWidget.
GetMountedWidget()
Widget GetMountedWidget () inline private
Definition at line 225 of file SlotsIcon.c.
References m_MountedWidget.
Referenced by AttachmentCategoriesRow::RefreshSlot(), and Attachments::UpdateInterval().
GetNormalHeight()
static int GetNormalHeight () inline static private
Definition at line 758 of file SlotsIcon.c.
References m_NormalHeight.
Referenced by ItemManager::CalculateTooltipSlotPosition().
GetNormalWidth()
static int GetNormalWidth () inline static private
Definition at line 753 of file SlotsIcon.c.
References m_NormalWidth.
Referenced by ItemManager::CalculateTooltipSlotPosition().
GetObject()
Object GetObject () inline private
Definition at line 348 of file SlotsIcon.c.
References m_Obj.
Referenced by AttachmentCategoriesContainer::Close(), SlotsContainer::GetFocusedItem(), RefreshMuzzleIcon(), and SetActive().
GetOutOfReachWidget()
Widget GetOutOfReachWidget () inline private
Definition at line 260 of file SlotsIcon.c.
References m_OutOfReachWidget.
Referenced by AttachmentCategoriesRow::RefreshSlot(), and Attachments::UpdateInterval().
GetPanelWidget()
Widget GetPanelWidget () inline private
Definition at line 205 of file SlotsIcon.c.
References m_PanelWidget.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), ZombieContainer::InitGhostSlots(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), PlayerContainer::PlayerContainer(), VicinitySlotsContainer::RecomputeNumberOfContainers(), VicinitySlotsContainer::ShowItemsInContainers(), UpdateFlip(), Attachments::UpdateInterval(), and VicinitySlotsContainer::VicinitySlotsContainer().
GetQuantityItem()
TextWidget GetQuantityItem () inline private
Definition at line 265 of file SlotsIcon.c.
References m_QuantityItem.
GetQuantityPanel()
Widget GetQuantityPanel () inline private
Definition at line 255 of file SlotsIcon.c.
References m_QuantityPanel.
GetQuantityProgress()
ProgressBarWidget GetQuantityProgress () inline private
Definition at line 270 of file SlotsIcon.c.
References m_QuantityProgress.
GetQuantityStack()
Widget GetQuantityStack () inline private
Definition at line 275 of file SlotsIcon.c.
References m_QuantityStack.
GetRadialIcon()
Widget GetRadialIcon () inline private
Definition at line 305 of file SlotsIcon.c.
References m_RadialIcon.
Referenced by AttachmentCategoriesSlotsContainer::ExpandCollapseContainer(), ZombieContainer::InitGhostSlots(), ZombieContainer::ItemAttached(), and LayoutHolder::SetOpenForSlotIcon().
GetRadialIconClosed()
Widget GetRadialIconClosed () inline private
Definition at line 300 of file SlotsIcon.c.
References m_RadialIconClosed.
Referenced by AttachmentCategoriesSlotsContainer::ExpandCollapseContainer(), and ZombieContainer::ItemAttached().
GetRadialIconPanel()
Widget GetRadialIconPanel () inline private
Definition at line 295 of file SlotsIcon.c.
References m_RadialIconPanel.
Referenced by AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), AttachmentCategoriesRow::RefreshSlot(), VicinitySlotsContainer::ShowItemsInContainers(), and LayoutHolder::UpdateRadialIcon().
GetRender()
ItemPreviewWidget GetRender () inline private
Definition at line 230 of file SlotsIcon.c.
References m_ItemPreview.
Referenced by AttachmentCategoriesSlotsContainer::GetFocusedItem(), AttachmentCategoriesRow::RefreshSlot(), and VicinitySlotsContainer::ShowItemsInContainers().
GetReservedWidget()
Widget GetReservedWidget () inline private
Definition at line 220 of file SlotsIcon.c.
References m_ReservedWidget.
GetSelectedPanel()
Widget GetSelectedPanel () inline private
Definition at line 245 of file SlotsIcon.c.
References m_SelectedPanel.
GetSlotDesc()
string GetSlotDesc () inline private
Definition at line 164 of file SlotsIcon.c.
References m_SlotDesc.
Referenced by SlotsContainer::UpdateIcon().
GetSlotDisplayName()
string GetSlotDisplayName () inline private
Definition at line 154 of file SlotsIcon.c.
References m_SlotDisplayName.
Referenced by SlotsContainer::UpdateIcon().
GetSlotID()
int GetSlotID () inline private
Definition at line 190 of file SlotsIcon.c.
References m_SlotID.
Referenced by Clear(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), Attachments::GetFocusedSlot(), AttachmentCategoriesRow::GetFocusedSlot(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), AttachmentCategoriesRow::RefreshSlot(), Attachments::Select(), AttachmentCategoriesRow::Select(), PlayerContainer::Select(), HandsContainer::TakeAsAttachment(), and ClosableContainer::TakeAsAttachment().
GetSlotParent()
EntityAI GetSlotParent () inline private
Definition at line 185 of file SlotsIcon.c.
References m_SlotParent.
Referenced by HandsContainer::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), ClosableContainer::MouseClick2(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), HandsContainer::TakeAsAttachment(), and ClosableContainer::TakeAsAttachment().
Init()
void Init (EntityAI obj, bool reservation = false) inline private
Definition at line 460 of file SlotsIcon.c.
References CheckHasItemSize(), CheckHasQuantity(), CheckHasTemperature(), CheckIsMagazine(), CheckIsWeapon(), Clear(), ItemManager::GetInstance(), m_Container, m_GhostSlot, m_HasItemSize, m_HasQuantity, m_HasTemperature, m_IsMagazine, m_IsWeapon, m_Item, m_Obj, m_PanelWidget, m_Reserved, m_ReservedWidget, Refresh(), SetItemPreview(), ItemManager::SetWidgetDraggable(), and UpdateFlip().
Referenced by Attachments::AttachmentAdded(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), Attachments::OnAttachmentReservationSet(), PlayerContainer::OnAttachmentReservationSet(), AttachmentCategoriesRow::RefreshSlot(), and VicinitySlotsContainer::ShowItemsInContainers().
IsOutOfReach()
bool IsOutOfReach () inline private
Definition at line 607 of file SlotsIcon.c.
References m_MountedWidget, and m_OutOfReachWidget.
Referenced by AttachmentCategoriesRow::CanCombine(), AttachmentCategoriesRow::Combine(), AttachmentCategoriesRow::IsItemActive(), AttachmentCategoriesRow::IsItemWithQuantityActive(), MouseEnter(), Attachments::Select(), AttachmentCategoriesRow::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), Attachments::SelectItem(), SlotsContainer::SelectItem(), AttachmentCategoriesRow::TransferItem(), and AttachmentCategoriesRow::TransferItemToVicinity().
IsReserved()
bool IsReserved () inline private
Definition at line 200 of file SlotsIcon.c.
References m_Reserved.
Referenced by ClosableContainer::DoubleClick(), PlayerContainer::DoubleClick(), PlayerContainer::DraggingOver(), ClosableContainer::DraggingOverHeader(), SlotsContainer::GetFocusedItem(), PlayerContainer::ItemAttached(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), Attachments::Select(), PlayerContainer::Select(), SlotsContainer::SelectItem(), ClosableContainer::TakeAsAttachment(), and Attachments::UpdateInterval().
IsVisible()
override bool IsVisible () inline private
Definition at line 129 of file SlotsIcon.c.
Referenced by SlotsContainer::GetVisibleFocus(), AttachmentCategoriesContainer::OnHide(), SlotsContainer::SetDefaultFocus(), SlotsContainer::SetNextLeftActive(), SlotsContainer::SetNextRightActive(), and SlotsContainer::SetVisibleFocus().
MouseEnter()
bool MouseEnter (Widget w, int x, int y) inline private
Definition at line 613 of file SlotsIcon.c.
References GetDragWidget(), IsOutOfReach(), m_Item, m_PanelWidget, m_Reserved, m_SelectedPanel, MouseEnterGhostSlot(), x, and y.
MouseEnterGhostSlot()
bool MouseEnterGhostSlot (Widget w, int x, int y) inline private
Definition at line 626 of file SlotsIcon.c.
References GetDragWidget(), m_EmptySelectedPanel, m_PanelWidget, m_SlotDesc, m_SlotDisplayName, x, and y.
Referenced by MouseEnter().
MouseLeave()
bool MouseLeave (Widget w, Widget s, int x, int y) inline private
Definition at line 644 of file SlotsIcon.c.
References GetDragWidget(), m_PanelWidget, m_Reserved, m_SelectedPanel, MouseLeaveGhostSlot(), x, and y.
MouseLeaveGhostSlot()
bool MouseLeaveGhostSlot (Widget w, Widget s, int x, int y) inline private
Definition at line 657 of file SlotsIcon.c.
References GetDragWidget(), m_EmptySelectedPanel, and m_PanelWidget.
Referenced by MouseLeave().
OnIconDrag()
void OnIconDrag (Widget w) inline private
Definition at line 684 of file SlotsIcon.c.
References GetGame(), ItemManager::GetInstance(), CGame::GetInventoryItemSize(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), ItemManager::HideDropzones(), m_ColWidget, m_IsDragged, m_Item, m_ItemPreview, m_Obj, m_Parent, m_SelectedPanel, ItemManager::SetDraggedItem(), ItemPreviewWidget::SetForceFlipEnable(), ItemManager::SetIsDragging(), and y.
OnIconDrop()
void OnIconDrop (Widget w) inline private
Definition at line 739 of file SlotsIcon.c.
References ARGBF(), ItemManager::GetInstance(), ItemManager::HideDropzones(), m_ColWidget, m_EmptySelectedPanel, m_IsDragged, m_ItemPreview, m_SelectedPanel, ItemPreviewWidget::SetForceFlipEnable(), and ItemManager::SetIsDragging().
Referenced by Clear().
Refresh()
override void Refresh () inline private
Definition at line 333 of file SlotsIcon.c.
References m_HasQuantity, m_HasTemperature, m_IsWeapon, RefreshMuzzleIcon(), SetQuantity(), and SetTemperature().
Referenced by Clear(), Init(), and AttachmentCategoriesRow::RefreshSlot().
RefreshMuzzleIcon()
void RefreshMuzzleIcon () inline private
Definition at line 363 of file SlotsIcon.c.
References GetObject(), Weapon_Base::IsShowingChamberedBullet(), and m_AmmoIcon.
Referenced by Refresh(), and UpdateInterval().
SetActive()
override void SetActive (bool active) inline private
Definition at line 310 of file SlotsIcon.c.
References GetObject(), m_SelectedPanel, m_SlotDesc, m_SlotDisplayName, x, and y.
SetContainer()
void SetContainer (Container container) inline private
Definition at line 139 of file SlotsIcon.c.
References m_Container.
Referenced by AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), and AttachmentCategoriesRow::RefreshSlot().
SetItemPreview()
void SetItemPreview () inline private
Definition at line 430 of file SlotsIcon.c.
References m_ItemPreview, m_Obj, ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetModelOrientation(), and ItemPreviewWidget::SetView().
Referenced by Clear(), Init(), and ~SlotsIcon().
SetItemSize()
void SetItemSize () inline private
Definition at line 438 of file SlotsIcon.c.
References GetGame(), CGame::GetInventoryItemSize(), m_HasItemSize, m_ItemSizePanel, m_ItemSizeWidget, m_Obj, and ToString().
Referenced by UpdateInterval().
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 328 of file SlotsIcon.c.
SetQuantity()
void SetQuantity () inline private
Definition at line 381 of file SlotsIcon.c.
References QuantityConversions::GetItemQuantity(), QuantityConversions::GetItemQuantityMax(), QuantityConversions::GetItemQuantityText(), QuantityConversions::HasItemQuantity(), m_CurrQuantity, m_Item, m_QuantityItem, m_QuantityProgress, m_QuantityStack, QUANTITY_COUNT, QUANTITY_HIDDEN, QUANTITY_PROGRESS, and Math::Round().
Referenced by Refresh(), and UpdateInterval().
SetSlotDesc()
void SetSlotDesc (string text) inline private
Definition at line 159 of file SlotsIcon.c.
References m_SlotDesc.
SetSlotDisplayName()
void SetSlotDisplayName (string text) inline private
Definition at line 144 of file SlotsIcon.c.
References m_SlotDisplayName.
Referenced by Attachments::AttachmentAdded(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), and PlayerContainer::PlayerContainer().
SetSlotID()
void SetSlotID (int slot_ID) inline private
Definition at line 195 of file SlotsIcon.c.
References m_SlotID.
Referenced by Attachments::AttachmentAdded(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), ZombieContainer::InitGhostSlots(), and PlayerContainer::PlayerContainer().
SetSlotParent()
void SetSlotParent (EntityAI parent) inline private
Definition at line 134 of file SlotsIcon.c.
References m_SlotParent.
Referenced by PlayerContainer::SetPlayer().
SetTemperature()
void SetTemperature () inline private
Definition at line 343 of file SlotsIcon.c.
References ItemManager::GetInstance(), m_Obj, and ItemManager::SetIconTemperature().
Referenced by Refresh(), and UpdateInterval().
UpdateFlip()
void UpdateFlip (bool flipped) inline private
Definition at line 450 of file SlotsIcon.c.
References GetPanelWidget(), and m_Reserved.
Referenced by Clear(), Init(), and ~SlotsIcon().
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 669 of file SlotsIcon.c.
References m_HasItemSize, m_HasQuantity, m_HasTemperature, m_IsWeapon, m_Item, RefreshMuzzleIcon(), SetItemSize(), SetQuantity(), and SetTemperature().
Referenced by VicinitySlotsContainer::ShowItemsInContainers(), Attachments::UpdateInterval(), AttachmentCategoriesContainer::UpdateInterval(), and PlayerContainer::UpdateInterval().
Field Documentation
m_AmmoIcon
protected Widget m_AmmoIcon private
Definition at line 46 of file SlotsIcon.c.
Referenced by Clear(), GetAmmoIcon(), RefreshMuzzleIcon(), and SlotsIcon().
m_ColorWidget
protected Widget m_ColorWidget private
Definition at line 31 of file SlotsIcon.c.
Referenced by Clear(), GetColorWidget(), and SlotsIcon().
m_ColWidget
protected Widget m_ColWidget private
Definition at line 23 of file SlotsIcon.c.
Referenced by Clear(), GetColWidget(), OnIconDrag(), OnIconDrop(), and SlotsIcon().
m_Container
protected Container m_Container private
Definition at line 16 of file SlotsIcon.c.
Referenced by Clear(), GetContainer(), Init(), SetContainer(), and SlotsIcon().
m_CurrQuantity
protected float m_CurrQuantity = -1 private
Definition at line 11 of file SlotsIcon.c.
Referenced by Clear(), and SetQuantity().
m_CursorWidget
protected Widget m_CursorWidget private
Definition at line 22 of file SlotsIcon.c.
Referenced by GetCursorWidget(), and SlotsIcon().
m_EmptySelectedPanel
protected Widget m_EmptySelectedPanel private
Definition at line 33 of file SlotsIcon.c.
Referenced by Clear(), GetEmptySelectedPanel(), MouseEnterGhostSlot(), MouseLeaveGhostSlot(), OnIconDrop(), and SlotsIcon().
m_GhostSlot
protected ImageWidget m_GhostSlot private
Definition at line 29 of file SlotsIcon.c.
Referenced by Clear(), GetGhostSlot(), Init(), and SlotsIcon().
m_HasItemSize
protected bool m_HasItemSize = false private
Definition at line 10 of file SlotsIcon.c.
Referenced by CheckHasItemSize(), Clear(), Init(), SetItemSize(), and UpdateInterval().
m_HasQuantity
protected bool m_HasQuantity = false private
Definition at line 9 of file SlotsIcon.c.
Referenced by CheckHasQuantity(), Clear(), Init(), Refresh(), and UpdateInterval().
m_HasTemperature
protected bool m_HasTemperature = false private
Definition at line 8 of file SlotsIcon.c.
Referenced by CheckHasTemperature(), Clear(), Init(), Refresh(), and UpdateInterval().
m_IsDragged
protected bool m_IsDragged = false private
Definition at line 18 of file SlotsIcon.c.
Referenced by Clear(), OnIconDrag(), OnIconDrop(), and ~SlotsIcon().
m_IsMagazine
protected bool m_IsMagazine = false private
Definition at line 7 of file SlotsIcon.c.
Referenced by CheckIsMagazine(), Clear(), and Init().
m_IsWeapon
protected bool m_IsWeapon = false private
Definition at line 6 of file SlotsIcon.c.
Referenced by CheckIsWeapon(), Clear(), Init(), Refresh(), and UpdateInterval().
m_Item
protected ItemBase m_Item private
Definition at line 14 of file SlotsIcon.c.
Referenced by CheckHasQuantity(), CheckHasTemperature(), Clear(), GetItem(), Init(), MouseEnter(), OnIconDrag(), SetQuantity(), SlotsIcon(), and UpdateInterval().
m_ItemPreview
protected ItemPreviewWidget m_ItemPreview private
Definition at line 28 of file SlotsIcon.c.
Referenced by Clear(), GetRender(), OnIconDrag(), OnIconDrop(), SetItemPreview(), and SlotsIcon().
m_ItemSizePanel
protected Widget m_ItemSizePanel private
Definition at line 43 of file SlotsIcon.c.
Referenced by Clear(), GetItemSizePanel(), SetItemSize(), and SlotsIcon().
m_ItemSizeWidget
protected TextWidget m_ItemSizeWidget private
Definition at line 44 of file SlotsIcon.c.
Referenced by GetItemSizeWidget(), SetItemSize(), and SlotsIcon().
m_MountedWidget
protected Widget m_MountedWidget private
Definition at line 24 of file SlotsIcon.c.
Referenced by Clear(), GetMountedWidget(), IsOutOfReach(), and SlotsIcon().
m_NormalHeight
protected int m_NormalHeight static private
Definition at line 4 of file SlotsIcon.c.
Referenced by GetNormalHeight(), and SlotsIcon().
m_NormalWidth
protected int m_NormalWidth static private
Definition at line 3 of file SlotsIcon.c.
Referenced by GetNormalWidth(), and SlotsIcon().
m_Obj
protected EntityAI m_Obj private
Definition at line 13 of file SlotsIcon.c.
Referenced by CheckHasItemSize(), CheckIsMagazine(), CheckIsWeapon(), Clear(), GetEntity(), GetObject(), Init(), OnIconDrag(), SetItemPreview(), SetItemSize(), SetTemperature(), SlotsIcon(), and ~SlotsIcon().
m_OutOfReachWidget
protected Widget m_OutOfReachWidget private
Definition at line 25 of file SlotsIcon.c.
Referenced by Clear(), GetOutOfReachWidget(), IsOutOfReach(), and SlotsIcon().
m_PanelWidget
protected Widget m_PanelWidget private
Definition at line 20 of file SlotsIcon.c.
Referenced by Clear(), GetPanelWidget(), Init(), MouseEnter(), MouseEnterGhostSlot(), MouseLeave(), MouseLeaveGhostSlot(), and SlotsIcon().
m_QuantityItem
protected TextWidget m_QuantityItem private
Definition at line 36 of file SlotsIcon.c.
Referenced by Clear(), GetQuantityItem(), SetQuantity(), and SlotsIcon().
m_QuantityPanel
protected Widget m_QuantityPanel private
Definition at line 35 of file SlotsIcon.c.
Referenced by CheckHasQuantity(), Clear(), GetQuantityPanel(), and SlotsIcon().
m_QuantityProgress
protected ProgressBarWidget m_QuantityProgress private
Definition at line 37 of file SlotsIcon.c.
Referenced by Clear(), GetQuantityProgress(), SetQuantity(), and SlotsIcon().
m_QuantityStack
protected Widget m_QuantityStack private
Definition at line 38 of file SlotsIcon.c.
Referenced by Clear(), GetQuantityStack(), SetQuantity(), and SlotsIcon().
m_RadialIcon
protected Widget m_RadialIcon private
Definition at line 50 of file SlotsIcon.c.
Referenced by GetRadialIcon(), and SlotsIcon().
m_RadialIconClosed
protected Widget m_RadialIconClosed private
Definition at line 49 of file SlotsIcon.c.
Referenced by GetRadialIconClosed(), and SlotsIcon().
m_RadialIconPanel
protected Widget m_RadialIconPanel private
Definition at line 48 of file SlotsIcon.c.
Referenced by Clear(), GetRadialIconPanel(), and SlotsIcon().
m_Reserved
protected bool m_Reserved private
Definition at line 52 of file SlotsIcon.c.
Referenced by Init(), IsReserved(), MouseEnter(), MouseLeave(), SlotsIcon(), and UpdateFlip().
m_ReservedWidget
protected Widget m_ReservedWidget private
Definition at line 26 of file SlotsIcon.c.
Referenced by Clear(), GetReservedWidget(), Init(), and SlotsIcon().
m_SelectedPanel
protected Widget m_SelectedPanel private
Definition at line 32 of file SlotsIcon.c.
Referenced by Clear(), GetSelectedPanel(), MouseEnter(), MouseLeave(), OnIconDrag(), OnIconDrop(), SetActive(), and SlotsIcon().
m_SlotDesc
protected string m_SlotDesc private
Definition at line 41 of file SlotsIcon.c.
Referenced by GetSlotDesc(), MouseEnterGhostSlot(), SetActive(), and SetSlotDesc().
m_SlotDisplayName
protected string m_SlotDisplayName private
Definition at line 40 of file SlotsIcon.c.
Referenced by GetSlotDisplayName(), MouseEnterGhostSlot(), SetActive(), and SetSlotDisplayName().
m_SlotID
protected int m_SlotID private
Definition at line 17 of file SlotsIcon.c.
Referenced by GetSlotID(), SetSlotID(), and SlotsIcon().
m_SlotParent
protected EntityAI m_SlotParent private
Definition at line 15 of file SlotsIcon.c.
Referenced by GetSlotParent(), SetSlotParent(), and SlotsIcon().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/ContainedItems/SlotsIcon.c