DayZ Scripts: Grenade_ChemGas Class Reference
Grenade_ChemGas Class Reference
Private Member Functions
void Grenade_ChemGas ()
void ~Grenade_ChemGas ()
override protected void OnExplode ()
protected string GetExplosionSoundSet ()
override void EOnContact (IEntity other, Contact extra)
override void EEKilled (Object killer)
override void OnDamageDestroyed (int oldLevel)
override protected void Activate ()
Private Attributes
protected bool m_Exploded
protected ParticleSource m_ParticleExploded
protected EffectSound m_ExplosionSound
Detailed Description
Definition at line 1 of file Grenade_ChemGas.c.
Constructor & Destructor Documentation
Grenade_ChemGas()
void Grenade_ChemGas () inline private
Definition at line 8 of file Grenade_ChemGas.c.
References Arm(), Grenade_Base::m_Pinned, ParticleList::RGD5, Grenade_Base::SetGrenadeType(), SetParticleExplosion(), and Grenade_Base::SetPinnable().
~Grenade_ChemGas()
void ~Grenade_ChemGas () private
Member Function Documentation
Activate()
override protected void Activate () inline private
Definition at line 64 of file Grenade_ChemGas.c.
EEKilled()
override void EEKilled (Object killer) inline private
Definition at line 45 of file Grenade_ChemGas.c.
EOnContact()
override void EOnContact (IEntity other, Contact extra) inline private
Definition at line 34 of file Grenade_ChemGas.c.
References GetGame(), m_Exploded, and Grenade_Base::OnActivateFinished().
GetExplosionSoundSet()
protected string GetExplosionSoundSet () inline private
Definition at line 29 of file Grenade_ChemGas.c.
Referenced by OnDamageDestroyed().
OnDamageDestroyed()
override void OnDamageDestroyed (int oldLevel) inline private
Definition at line 50 of file Grenade_ChemGas.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), ClearFlags(), Delete(), CGame::GetCallQueue(), GetExplosionSoundSet(), GetGame(), GetPosition, ParticleList::GRENADE_CHEM_BREAK, m_ExplosionSound, m_ParticleExploded, ParticleManager(), and PlaySoundSet().
OnExplode()
override protected void OnExplode () inline private
Definition at line 19 of file Grenade_ChemGas.c.
References CGame::CreateObject(), GetGame(), GetPosition, and m_Exploded.
Field Documentation
m_Exploded
protected bool m_Exploded private
Definition at line 3 of file Grenade_ChemGas.c.
Referenced by EOnContact(), and OnExplode().
m_ExplosionSound
protected EffectSound m_ExplosionSound private
Definition at line 5 of file Grenade_ChemGas.c.
Referenced by OnDamageDestroyed().
m_ParticleExploded
protected ParticleSource m_ParticleExploded private
Definition at line 4 of file Grenade_ChemGas.c.
Referenced by OnDamageDestroyed().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Grenade_Base/Grenade_ChemGas.c