DayZ Scripts: Hologram Class Reference
Hologram Class Reference
Private Member Functions
void Hologram (PlayerBase player, vector pos, ItemBase item)
void ~Hologram ()
void SetAnimations ()
void UpdateSelections ()
string ProjectionBasedOnParent ()
string GetProjectionName (ItemBase item)
void UpdateHologram (float timeslice)
vector AlignProjectionOnTerrain (float timeslice)
vector SmoothProjectionMovement (vector y_p_r, float timeslice)
void CreateTrigger ()
void RefreshTrigger ()
void EvaluateCollision (ItemBase action_item=null)
bool IsClippingRoof ()
bool IsCollidingAngle ()
bool IsCollidingBBox (ItemBase action_item=null)
bool IsBaseViable ()
bool IsCollidingGPlot ()
bool IsCollidingZeroPos ()
bool IsBehindObstacle ()
DEPRECATED.
bool IsBaseStatic (Object objectToCheck)
bool IsObjectStatic (Object obj)
bool IsBaseIntact (Object under_left_close, Object under_right_close, Object under_left_far, Object under_right_far)
bool IsBaseFlat (vector contact_pos_left_close, vector contact_pos_right_close, vector contact_pos_left_far, vector contact_pos_right_far)
bool IsPlacementPermitted ()
Checks if the item can be legally placed (usually checked by action as well)
bool HeightPlacementCheck ()
Checks height relative to player's position.
bool IsUnderwater ()
bool IsInTerrain ()
void CheckPowerSource ()
EntityAI PlaceEntity (EntityAI entity_for_placing)
protected void GetProjectionCollisionBox (out vector min_max[2])
protected vector GetCollisionBoxSize (vector min_max[2])
vector GetLeftCloseProjectionVector ()
vector GetRightCloseProjectionVector ()
vector GetLeftFarProjectionVector ()
vector GetRightFarProjectionVector ()
bool IsSurfaceWater (vector position)
bool IsSurfaceSea (vector position)
protected vector GetProjectionEntityPosition (PlayerBase player)
protected bool SetHologramPosition (vector startPosition, float minProjectionDistance, float maxProjectionDistance, inout vector contactPosition)
Sets hologram position based on player and projection distance.
bool IsFenceOrWatchtowerKit ()
vector CorrectForWatchtower (int contactComponent, vector contactPos, PlayerBase player, Object hitObject)
bool IsProjectionTrap ()
float GetProjectionDiameter ()
float GetProjectionRadius ()
void SetUpdatePosition (bool state)
bool GetUpdatePosition ()
EntityAI GetParentEntity ()
void SetProjectionEntity (EntityAI projection)
EntityAI GetProjectionEntity ()
void SetIsFloating (bool is_floating)
void SetIsColliding (bool is_colliding)
void SetIsHidden (bool is_hidden)
void SetIsCollidingPlayer (bool is_colliding)
void SetIsCollidingGPlot (bool is_colliding_gplot)
bool IsFloating ()
bool IsColliding ()
bool IsHidden ()
bool IsCollidingPlayer ()
void SetProjectionPosition (vector position)
void SetProjectionOrientation (vector orientation)
vector GetProjectionRotation ()
void AddProjectionRotation (float addition)
void SubtractProjectionRotation (float subtraction)
vector SetOnGround (vector position)
vector HideWhenClose (vector pos)
vector GetProjectionPosition ()
vector GetProjectionOrientation ()
vector GetDefaultOrientation ()
int GetHiddenSelection (string selection)
void SetSelectionToRefresh (string selection)
void SetSelectionToRefresh (array< string > selection)
void RefreshVisual ()
string CorrectMaterialPathName ()
Static Private Member Functions
static bool DoesHaveProjection (ItemBase item)
DEPRECATED.
Private Attributes
protected const int SPAWN_FLAGS = ECE_LOCAL
protected const string SUFFIX_MATERIAL_DEPLOYABLE = "_deployable.rvmat"
protected const string SUFFIX_MATERIAL_UNDEPLOYABLE = "_undeployable.rvmat"
protected const string SUFFIX_MATERIAL_POWERED = "_powered.rvmat"
protected ItemBase m_Parent
protected EntityAI m_Projection
protected PlayerBase m_Player
protected ProjectionTrigger m_ProjectionTrigger
protected string m_ProjectionTypename
protected bool m_IsColliding
protected bool m_IsCollidingGPlot
protected bool m_IsSlope
protected bool m_IsCollidingPlayer
protected bool m_IsFloating
protected bool m_UpdatePosition
protected bool m_IsHidden
protected vector m_DefaultOrientation
protected vector m_Rotation
protected vector m_y_p_r_previous
protected vector m_ContactDir
protected vector m_FromAdjusted
protected const string ANIMATION_PLACING = "Placing"
protected const string ANIMATION_INVENTORY = "Inventory"
protected const string SELECTION_PLACING = "placing"
protected const string SELECTION_INVENTORY = "inventory"
protected const float SMALL_PROJECTION_RADIUS = 1
protected const float SMALL_PROJECTION_GROUND = 2
protected const float DISTANCE_SMALL_PROJECTION = 1
protected const float LARGE_PROJECTION_DISTANCE_LIMIT = 6
Deprecated.
protected const float PROJECTION_TRANSITION_MIN = 1
protected const float PROJECTION_TRANSITION_MAX = 0.25
protected const float LOOKING_TO_SKY = 0.75
protected float m_SlopeTolerance
protected bool m_AlignToTerrain
protected vector m_YawPitchRollLimit
protected int m_ContactComponent
protected ref set< string > m_SelectionsToRefresh = new set<string>
Static Private Attributes
static const float DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF = 1.5
static const protected ref array< string > m_WatchtowerIgnoreComponentNames = new array<string>
static const protected ref array< string > m_WatchtowerBlockedComponentNames = new array<string>
Detailed Description
Definition at line 1 of file Hologram.c.
Constructor & Destructor Documentation
Hologram()
void Hologram (PlayerBase player, vector pos, ItemBase item) inline private
Definition at line 60 of file Hologram.c.
References CGame::ConfigGetFloat(), CGame::ConfigGetInt(), CGame::ConfigGetTextOut(), CGame::ConfigGetVector(), CreateTrigger(), ECE_LOCAL, ECE_PLACE_ON_SURFACE, ECE_TRACE, ErrorEx, GetGame(), GetProjectionEntity(), GetType(), m_AlignToTerrain, m_ContactComponent, m_FromAdjusted, m_Parent, m_Player, m_Projection, m_ProjectionTrigger, m_ProjectionTypename, m_Rotation, m_SlopeTolerance, m_UpdatePosition, m_WatchtowerBlockedComponentNames, m_WatchtowerIgnoreComponentNames, m_YawPitchRollLimit, ProjectionBasedOnParent(), RefreshTrigger(), SetAnimations(), SetProjectionEntity(), and string::ToString().
~Hologram()
void ~Hologram () inline private
Definition at line 148 of file Hologram.c.
References DestroyDebugCollisionBox(), GetGame(), m_Projection, m_ProjectionTrigger, and CGame::ObjectDelete().
Member Function Documentation
AddProjectionRotation()
void AddProjectionRotation (float addition) inline private
Definition at line 1352 of file Hologram.c.
References m_Rotation.
AlignProjectionOnTerrain()
vector AlignProjectionOnTerrain (float timeslice) inline private
Definition at line 285 of file Hologram.c.
References Math::Clamp(), GetDefaultOrientation(), GetGame(), GetProjectionRotation(), vector::Length(), m_AlignToTerrain, m_ContactDir, m_Projection, Math3D::MatrixMultiply3(), Math3D::MatrixToAngles(), SmoothProjectionMovement(), CGame::SurfaceGetNormal(), vector::VectorToAngles(), and Math3D::YawPitchRollMatrix().
Referenced by UpdateHologram().
CheckPowerSource()
void CheckPowerSource () inline private
Definition at line 952 of file Hologram.c.
References GetGame(), m_Parent, and m_Player.
Referenced by UpdateHologram().
CorrectForWatchtower()
vector CorrectForWatchtower (int contactComponent, vector contactPos, PlayerBase player, Object hitObject) inline private
Definition at line 1204 of file Hologram.c.
References m_WatchtowerIgnoreComponentNames, and LOD::NAME_VIEW.
Referenced by GetProjectionEntityPosition().
CorrectMaterialPathName()
string CorrectMaterialPathName () inline private
Definition at line 1508 of file Hologram.c.
References GetProjectionPosition(), IsColliding(), ComponentEnergyManager::IsEnergySourceAtReach(), IsFloating(), ComponentEnergyManager::IsPlugged(), m_Parent, m_Projection, ItemBase::SEL_CORD_FOLDED, ItemBase::SEL_CORD_PLUGGED, SUFFIX_MATERIAL_DEPLOYABLE, SUFFIX_MATERIAL_POWERED, and SUFFIX_MATERIAL_UNDEPLOYABLE.
Referenced by RefreshVisual().
CreateTrigger()
void CreateTrigger () inline private
Definition at line 367 of file Hologram.c.
References Class::CastTo(), g_Game, GetProjectionOrientation(), GetProjectionPosition(), m_Player, m_ProjectionTrigger, RefreshVisual(), and SPAWN_FLAGS.
Referenced by Hologram().
DoesHaveProjection()
static bool DoesHaveProjection (ItemBase item) inline static private
DEPRECATED.
Definition at line 240 of file Hologram.c.
References ItemBase::CanMakeGardenplot(), DeployableContainer_Base(), and ItemBase::IsDeployable().
EvaluateCollision()
void EvaluateCollision (ItemBase action_item = null) inline private
Definition at line 424 of file Hologram.c.
References Class::CastTo(), HeightPlacementCheck(), IsBaseViable(), IsClippingRoof(), IsCollidingAngle(), IsCollidingBBox(), IsCollidingGPlot(), IsCollidingPlayer(), IsCollidingZeroPos(), IsFloating(), IsHidden(), IsInTerrain(), TrapSpawnBase::IsPlaceableAtPosition(), IsPlacementPermitted(), IsUnderwater(), m_Projection, and SetIsColliding().
Referenced by UpdateHologram().
GetCollisionBoxSize()
protected vector GetCollisionBoxSize (vector min_max[2]) inline private
Definition at line 1003 of file Hologram.c.
References Vector().
Referenced by GetProjectionDiameter(), GetProjectionRadius(), and IsCollidingBBox().
GetDefaultOrientation()
vector GetDefaultOrientation () inline private
Definition at line 1446 of file Hologram.c.
References CGame::GetCurrentCameraDirection(), GetGame(), GetParentEntity(), m_DefaultOrientation, vector::VectorToAngles(), and vector::Zero.
Referenced by AlignProjectionOnTerrain().
GetHiddenSelection()
int GetHiddenSelection (string selection) inline private
Definition at line 1459 of file Hologram.c.
References m_Projection.
Referenced by RefreshVisual().
GetLeftCloseProjectionVector()
vector GetLeftCloseProjectionVector () inline private
Definition at line 1014 of file Hologram.c.
References GetProjectionCollisionBox().
Referenced by ActionDigGardenPlot::CheckSurfaceBelowGardenPlot(), IsBaseViable(), IsInTerrain(), and IsUnderwater().
GetLeftFarProjectionVector()
vector GetLeftFarProjectionVector () inline private
Definition at line 1032 of file Hologram.c.
References GetProjectionCollisionBox().
Referenced by ActionDigGardenPlot::CheckSurfaceBelowGardenPlot(), IsBaseViable(), IsInTerrain(), and IsUnderwater().
GetParentEntity()
EntityAI GetParentEntity () inline private
Definition at line 1258 of file Hologram.c.
References m_Parent.
Referenced by GetDefaultOrientation().
GetProjectionCollisionBox()
protected void GetProjectionCollisionBox (out vector min_max[2]) inline private
Definition at line 992 of file Hologram.c.
References m_Projection.
Referenced by GetLeftCloseProjectionVector(), GetLeftFarProjectionVector(), GetProjectionDiameter(), GetProjectionRadius(), GetRightCloseProjectionVector(), GetRightFarProjectionVector(), IsCollidingBBox(), and RefreshTrigger().
GetProjectionDiameter()
float GetProjectionDiameter () inline private
Definition at line 1219 of file Hologram.c.
References GetCollisionBoxSize(), GetProjectionCollisionBox(), and vector::Length().
Referenced by SetOnGround().
GetProjectionEntity()
EntityAI GetProjectionEntity () inline private
Definition at line 1268 of file Hologram.c.
References m_Projection.
Referenced by ActionDigGardenPlot::ActionCondition(), HeightPlacementCheck(), Hologram(), IsPlacementPermitted(), and PlaceEntity().
GetProjectionEntityPosition()
protected vector GetProjectionEntityPosition (PlayerBase player) inline private
will not push hologram up when there is direct hit of an item
Definition at line 1063 of file Hologram.c.
References Math::Clamp(), CorrectForWatchtower(), DayZPlayerCamera3rdPerson(), vector::Distance(), vector::DistanceSq(), Debug::DrawSphere(), DiagMenu::GetBool(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), CfgGameplayHandler::GetDisableIsCollidingBBoxCheck(), GetGame(), GetProjectionPosition(), GetProjectionRadius(), LARGE_PROJECTION_DISTANCE_LIMIT, m_ContactComponent, m_ContactDir, m_FromAdjusted, m_Projection, DayZPhysics::RaycastRV(), SetHologramPosition(), SetIsFloating(), SMALL_PROJECTION_RADIUS, and vector::Zero.
Referenced by UpdateHologram().
GetProjectionName()
string GetProjectionName (ItemBase item) inline private
configuration override
Definition at line 212 of file Hologram.c.
References ItemBase::CanMakeGardenplot(), ItemBase::IsBasebuildingKit(), and m_ProjectionTypename.
Referenced by ProjectionBasedOnParent().
GetProjectionOrientation()
vector GetProjectionOrientation () inline private
Definition at line 1438 of file Hologram.c.
References m_Projection, and vector::Zero.
Referenced by CreateTrigger(), IsCollidingBBox(), and RefreshTrigger().
GetProjectionPosition()
vector GetProjectionPosition () inline private
Definition at line 1430 of file Hologram.c.
References m_Projection, and vector::Zero.
Referenced by CorrectMaterialPathName(), CreateTrigger(), GetProjectionEntityPosition(), HeightPlacementCheck(), IsBaseFlat(), IsCollidingZeroPos(), IsPlacementPermitted(), and RefreshTrigger().
GetProjectionRadius()
float GetProjectionRadius () inline private
Definition at line 1233 of file Hologram.c.
References GetCollisionBoxSize(), GetProjectionCollisionBox(), and vector::Length().
Referenced by GetProjectionEntityPosition().
GetProjectionRotation()
vector GetProjectionRotation () inline private
Definition at line 1347 of file Hologram.c.
References m_Rotation.
Referenced by AlignProjectionOnTerrain().
GetRightCloseProjectionVector()
vector GetRightCloseProjectionVector () inline private
Definition at line 1022 of file Hologram.c.
References GetProjectionCollisionBox().
Referenced by ActionDigGardenPlot::CheckSurfaceBelowGardenPlot(), IsBaseViable(), IsInTerrain(), and IsUnderwater().
GetRightFarProjectionVector()
vector GetRightFarProjectionVector () inline private
Definition at line 1041 of file Hologram.c.
References GetProjectionCollisionBox().
Referenced by ActionDigGardenPlot::CheckSurfaceBelowGardenPlot(), IsBaseViable(), IsInTerrain(), and IsUnderwater().
GetUpdatePosition()
bool GetUpdatePosition () inline private
Definition at line 1253 of file Hologram.c.
References m_UpdatePosition.
Referenced by UpdateHologram().
HeightPlacementCheck()
bool HeightPlacementCheck () inline private
Checks height relative to player's position.
Definition at line 798 of file Hologram.c.
References DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF, CfgGameplayHandler::GetDisableHeightPlacementCheck(), GetProjectionEntity(), GetProjectionPosition(), and m_Player.
Referenced by EvaluateCollision().
HideWhenClose()
vector HideWhenClose (vector pos) inline private
Definition at line 1417 of file Hologram.c.
References CGame::GetCurrentCameraDirection(), GetGame(), and LOOKING_TO_SKY.
Referenced by SetOnGround().
IsBaseFlat()
bool IsBaseFlat (vector contact_pos_left_close, vector contact_pos_right_close, vector contact_pos_left_far, vector contact_pos_right_far) inline private
Definition at line 763 of file Hologram.c.
References Math::AbsFloat(), GetProjectionPosition(), and m_SlopeTolerance.
Referenced by IsBaseViable().
IsBaseIntact()
bool IsBaseIntact (Object under_left_close, Object under_right_close, Object under_left_far, Object under_right_far) inline private
Definition at line 677 of file Hologram.c.
Referenced by IsBaseViable().
IsBaseStatic()
bool IsBaseStatic (Object objectToCheck) inline private
Definition at line 659 of file Hologram.c.
References IsObjectStatic().
Referenced by IsBaseViable().
IsBaseViable()
bool IsBaseViable () inline private
Definition at line 566 of file Hologram.c.
References CfgGameplayHandler::GetDisableIsBaseViableCheck(), GetGame(), GetLeftCloseProjectionVector(), GetLeftFarProjectionVector(), GetRightCloseProjectionVector(), GetRightFarProjectionVector(), IsBaseFlat(), IsBaseIntact(), IsBaseStatic(), m_Projection, and DayZPhysics::RaycastRV().
Referenced by EvaluateCollision().
IsBehindObstacle()
bool IsBehindObstacle () inline private
DEPRECATED.
Definition at line 652 of file Hologram.c.
References ErrorEx.
IsClippingRoof()
bool IsClippingRoof () inline private
Definition at line 454 of file Hologram.c.
References CGame::GetCurrentCameraPosition(), CfgGameplayHandler::GetDisableIsClippingRoofCheck(), GetGame(), m_Projection, and GameConstants::ROOF_CHECK_RAYCAST_DIST.
Referenced by EvaluateCollision().
IsColliding()
bool IsColliding () inline private
Definition at line 1309 of file Hologram.c.
References m_IsColliding.
Referenced by ActionDigGardenPlot::ActionCondition(), and CorrectMaterialPathName().
IsCollidingAngle()
bool IsCollidingAngle () inline private
Definition at line 486 of file Hologram.c.
References Math::AbsFloat(), CfgGameplayHandler::GetDisableIsCollidingAngleCheck(), m_Projection, and m_YawPitchRollLimit.
Referenced by EvaluateCollision().
IsCollidingBBox()
bool IsCollidingBBox (ItemBase action_item = null) inline private
Definition at line 519 of file Hologram.c.
References DrawDebugCollisionBox(), DiagMenu::GetBool(), GetCollisionBoxSize(), CfgGameplayHandler::GetDisableIsCollidingBBoxCheck(), GetGame(), GetProjectionCollisionBox(), GetProjectionOrientation(), CGame::IsBoxCollidingGeometry(), m_Player, and m_Projection.
Referenced by EvaluateCollision().
IsCollidingGPlot()
bool IsCollidingGPlot () inline private
Definition at line 628 of file Hologram.c.
References CfgGameplayHandler::GetDisableIsCollidingGPlotCheck(), and m_IsCollidingGPlot.
Referenced by EvaluateCollision().
IsCollidingPlayer()
bool IsCollidingPlayer () inline private
Definition at line 1322 of file Hologram.c.
References CfgGameplayHandler::GetDisableIsCollidingPlayerCheck(), and m_IsCollidingPlayer.
Referenced by EvaluateCollision().
IsCollidingZeroPos()
bool IsCollidingZeroPos () inline private
Definition at line 640 of file Hologram.c.
References GetProjectionPosition(), and Vector().
Referenced by EvaluateCollision().
IsFenceOrWatchtowerKit()
bool IsFenceOrWatchtowerKit () inline private
Definition at line 1199 of file Hologram.c.
References ItemBase::IsBasebuildingKit(), and m_Parent.
IsFloating()
bool IsFloating () inline private
Definition at line 1301 of file Hologram.c.
References m_IsFloating.
Referenced by CorrectMaterialPathName(), EvaluateCollision(), and SetProjectionPosition().
IsHidden()
bool IsHidden () inline private
Definition at line 1314 of file Hologram.c.
References m_IsHidden.
Referenced by EvaluateCollision().
IsInTerrain()
bool IsInTerrain () inline private
Definition at line 865 of file Hologram.c.
References CfgGameplayHandler::GetDisableIsInTerrainCheck(), GetLeftCloseProjectionVector(), GetLeftFarProjectionVector(), GetRightCloseProjectionVector(), GetRightFarProjectionVector(), m_Projection, and DayZPhysics::RaycastRV().
Referenced by EvaluateCollision().
IsObjectStatic()
bool IsObjectStatic (Object obj) inline private
Definition at line 672 of file Hologram.c.
References m_ContactComponent, m_Parent, m_WatchtowerBlockedComponentNames, and LOD::NAME_VIEW.
Referenced by IsBaseStatic().
IsPlacementPermitted()
bool IsPlacementPermitted () inline private
Checks if the item can be legally placed (usually checked by action as well)
Definition at line 784 of file Hologram.c.
References ItemBase::CanBePlaced(), CfgGameplayHandler::GetDisableIsPlacementPermittedCheck(), GetProjectionEntity(), GetProjectionPosition(), and m_Player.
Referenced by EvaluateCollision().
IsProjectionTrap()
bool IsProjectionTrap () inline private
Definition at line 1214 of file Hologram.c.
References m_Projection.
IsSurfaceSea()
bool IsSurfaceSea (vector position) inline private
Definition at line 1057 of file Hologram.c.
References GetGame(), and CGame::SurfaceIsSea().
Referenced by IsUnderwater().
IsSurfaceWater()
bool IsSurfaceWater (vector position) inline private
Definition at line 1051 of file Hologram.c.
References GetGame(), CGame::SurfaceIsPond(), and CGame::SurfaceIsSea().
IsUnderwater()
bool IsUnderwater () inline private
Definition at line 822 of file Hologram.c.
References g_Game, CfgGameplayHandler::GetDisableIsUnderwaterCheck(), GetLeftCloseProjectionVector(), GetLeftFarProjectionVector(), GetRightCloseProjectionVector(), GetRightFarProjectionVector(), IsSurfaceSea(), LIQUID_WATER, and m_Projection.
Referenced by EvaluateCollision().
PlaceEntity()
EntityAI PlaceEntity (EntityAI entity_for_placing) inline private
Definition at line 969 of file Hologram.c.
References Class::CastTo(), ECE_OBJECT_SWAP, GetGame(), GetProjectionEntity(), m_Parent, and m_Projection.
ProjectionBasedOnParent()
string ProjectionBasedOnParent () inline private
Definition at line 207 of file Hologram.c.
References GetProjectionName(), and m_Parent.
Referenced by Hologram().
RefreshTrigger()
void RefreshTrigger () inline private
Definition at line 378 of file Hologram.c.
References GetProjectionCollisionBox(), GetProjectionOrientation(), GetProjectionPosition(), and m_ProjectionTrigger.
Referenced by Hologram(), and UpdateHologram().
RefreshVisual()
void RefreshVisual () inline private
Definition at line 1484 of file Hologram.c.
References CGame::ConfigGetTextOut(), CorrectMaterialPathName(), string::Format(), GetGame(), GetHiddenSelection(), m_Projection, and m_SelectionsToRefresh.
Referenced by CreateTrigger(), and UpdateHologram().
SetAnimations()
void SetAnimations () inline private
Definition at line 168 of file Hologram.c.
References ANIMATION_INVENTORY, ANIMATION_PLACING, m_Projection, SELECTION_INVENTORY, SELECTION_PLACING, SetSelectionToRefresh(), and UpdateSelections().
Referenced by Hologram().
SetHologramPosition()
protected bool SetHologramPosition (vector startPosition, float minProjectionDistance, float maxProjectionDistance, inout vector contactPosition) inline private
Sets hologram position based on player and projection distance.
Parameters
startPosition start position
minProjectionDistance lower distance limit
maxProjectionDistance higher distance limit
inout contactPosition is position of the hologram contact with ground/object
Returns
true if hologram is floating (is on the near or far edge)
Definition at line 1150 of file Hologram.c.
References vector::Distance(), m_IsHidden, vector::Normalize(), PROJECTION_TRANSITION_MAX, and PROJECTION_TRANSITION_MIN.
Referenced by GetProjectionEntityPosition().
SetIsColliding()
void SetIsColliding (bool is_colliding) inline private
Definition at line 1278 of file Hologram.c.
References m_IsColliding.
Referenced by EvaluateCollision().
SetIsCollidingGPlot()
void SetIsCollidingGPlot (bool is_colliding_gplot) inline private
Definition at line 1296 of file Hologram.c.
References m_IsCollidingGPlot.
Referenced by ActionDigGardenPlot::CheckSurfaceBelowGardenPlot().
SetIsCollidingPlayer()
void SetIsCollidingPlayer (bool is_colliding) inline private
Definition at line 1291 of file Hologram.c.
References m_IsCollidingPlayer.
SetIsFloating()
void SetIsFloating (bool is_floating) inline private
Definition at line 1273 of file Hologram.c.
References m_IsFloating.
Referenced by GetProjectionEntityPosition().
SetIsHidden()
void SetIsHidden (bool is_hidden) inline private
Definition at line 1286 of file Hologram.c.
References m_IsHidden.
SetOnGround()
vector SetOnGround (vector position) inline private
Definition at line 1362 of file Hologram.c.
References RaycastRVResult::entry, RaycastRVParams::flags, GetProjectionDiameter(), HideWhenClose(), m_FromAdjusted, m_Player, m_Projection, m_WatchtowerIgnoreComponentNames, Math::Max(), LOD::NAME_VIEW, RaycastRVResult::obj, RaycastRVResult::parent, RaycastRVResult::pos, DayZPhysics::RaycastRV(), DayZPhysics::RaycastRVProxy(), SMALL_PROJECTION_GROUND, and Vector().
Referenced by SetProjectionPosition().
SetProjectionEntity()
void SetProjectionEntity (EntityAI projection) inline private
Definition at line 1263 of file Hologram.c.
References m_Projection.
Referenced by Hologram().
SetProjectionOrientation()
void SetProjectionOrientation (vector orientation) inline private
Definition at line 1342 of file Hologram.c.
References m_Projection.
Referenced by UpdateHologram().
SetProjectionPosition()
void SetProjectionPosition (vector position) inline private
Definition at line 1332 of file Hologram.c.
References IsFloating(), m_Projection, and SetOnGround().
Referenced by UpdateHologram().
SetSelectionToRefresh() [1/2]
void SetSelectionToRefresh (array< string > selection) inline private
Definition at line 1476 of file Hologram.c.
References m_SelectionsToRefresh.
SetSelectionToRefresh() [2/2]
void SetSelectionToRefresh (string selection) inline private
Definition at line 1470 of file Hologram.c.
References m_SelectionsToRefresh.
Referenced by SetAnimations().
SetUpdatePosition()
void SetUpdatePosition (bool state) inline private
Definition at line 1248 of file Hologram.c.
References m_UpdatePosition.
SmoothProjectionMovement()
vector SmoothProjectionMovement (vector y_p_r, float timeslice) inline private
Definition at line 340 of file Hologram.c.
References Math::AbsFloat(), Math::Lerp(), and m_y_p_r_previous.
Referenced by AlignProjectionOnTerrain().
SubtractProjectionRotation()
void SubtractProjectionRotation (float subtraction) inline private
Definition at line 1357 of file Hologram.c.
References m_Rotation.
UpdateHologram()
void UpdateHologram (float timeslice) inline private
Definition at line 246 of file Hologram.c.
References AlignProjectionOnTerrain(), CheckPowerSource(), DestroyDebugCollisionBox(), EvaluateCollision(), GetProjectionEntityPosition(), GetUpdatePosition(), m_Parent, m_Player, m_Projection, RefreshTrigger(), RefreshVisual(), SetProjectionOrientation(), and SetProjectionPosition().
UpdateSelections()
void UpdateSelections () inline private
Definition at line 188 of file Hologram.c.
References CGame::ConfigGetChildName(), g_Game, GetGame(), m_Parent, and m_Projection.
Referenced by SetAnimations().
Field Documentation
ANIMATION_INVENTORY
protected const string ANIMATION_INVENTORY = "Inventory" private
Definition at line 33 of file Hologram.c.
Referenced by SetAnimations().
ANIMATION_PLACING
protected const string ANIMATION_PLACING = "Placing" private
Definition at line 32 of file Hologram.c.
Referenced by SetAnimations().
DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF
const float DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF = 1.5 static private
Definition at line 44 of file Hologram.c.
Referenced by HeightPlacementCheck().
DISTANCE_SMALL_PROJECTION
protected const float DISTANCE_SMALL_PROJECTION = 1 private
Definition at line 39 of file Hologram.c.
LARGE_PROJECTION_DISTANCE_LIMIT
protected const float LARGE_PROJECTION_DISTANCE_LIMIT = 6 private
Deprecated.
Definition at line 40 of file Hologram.c.
Referenced by GetProjectionEntityPosition().
LOOKING_TO_SKY
protected const float LOOKING_TO_SKY = 0.75 private
Definition at line 43 of file Hologram.c.
Referenced by HideWhenClose().
m_AlignToTerrain
protected bool m_AlignToTerrain private
Definition at line 47 of file Hologram.c.
Referenced by AlignProjectionOnTerrain(), and Hologram().
m_ContactComponent
protected int m_ContactComponent private
Definition at line 49 of file Hologram.c.
Referenced by GetProjectionEntityPosition(), Hologram(), and IsObjectStatic().
m_ContactDir
protected vector m_ContactDir private
Definition at line 30 of file Hologram.c.
Referenced by AlignProjectionOnTerrain(), and GetProjectionEntityPosition().
m_DefaultOrientation
protected vector m_DefaultOrientation private
Definition at line 27 of file Hologram.c.
Referenced by GetDefaultOrientation().
m_FromAdjusted
protected vector m_FromAdjusted private
Definition at line 31 of file Hologram.c.
Referenced by GetProjectionEntityPosition(), Hologram(), and SetOnGround().
m_IsColliding
protected bool m_IsColliding private
Definition at line 19 of file Hologram.c.
Referenced by IsColliding(), and SetIsColliding().
m_IsCollidingGPlot
protected bool m_IsCollidingGPlot private
Definition at line 20 of file Hologram.c.
Referenced by IsCollidingGPlot(), and SetIsCollidingGPlot().
m_IsCollidingPlayer
protected bool m_IsCollidingPlayer private
Definition at line 22 of file Hologram.c.
Referenced by IsCollidingPlayer(), and SetIsCollidingPlayer().
m_IsFloating
protected bool m_IsFloating private
Definition at line 23 of file Hologram.c.
Referenced by IsFloating(), and SetIsFloating().
m_IsHidden
protected bool m_IsHidden private
Definition at line 25 of file Hologram.c.
Referenced by IsHidden(), SetHologramPosition(), and SetIsHidden().
m_IsSlope
protected bool m_IsSlope private
Definition at line 21 of file Hologram.c.
m_Parent
protected ItemBase m_Parent private
Definition at line 13 of file Hologram.c.
Referenced by CheckPowerSource(), CorrectMaterialPathName(), GetParentEntity(), Hologram(), IsFenceOrWatchtowerKit(), IsObjectStatic(), PlaceEntity(), ProjectionBasedOnParent(), UpdateHologram(), and UpdateSelections().
m_Player
protected PlayerBase m_Player private
Definition at line 15 of file Hologram.c.
Referenced by CheckPowerSource(), CreateTrigger(), HeightPlacementCheck(), Hologram(), IsCollidingBBox(), IsPlacementPermitted(), SetOnGround(), and UpdateHologram().
m_Projection
protected EntityAI m_Projection private
Definition at line 14 of file Hologram.c.
Referenced by AlignProjectionOnTerrain(), CorrectMaterialPathName(), EvaluateCollision(), GetHiddenSelection(), GetProjectionCollisionBox(), GetProjectionEntity(), GetProjectionEntityPosition(), GetProjectionOrientation(), GetProjectionPosition(), Hologram(), IsBaseViable(), IsClippingRoof(), IsCollidingAngle(), IsCollidingBBox(), IsInTerrain(), IsProjectionTrap(), IsUnderwater(), PlaceEntity(), RefreshVisual(), SetAnimations(), SetOnGround(), SetProjectionEntity(), SetProjectionOrientation(), SetProjectionPosition(), UpdateHologram(), UpdateSelections(), and ~Hologram().
m_ProjectionTrigger
protected ProjectionTrigger m_ProjectionTrigger private
Definition at line 16 of file Hologram.c.
Referenced by CreateTrigger(), Hologram(), RefreshTrigger(), and ~Hologram().
m_ProjectionTypename
protected string m_ProjectionTypename private
Definition at line 17 of file Hologram.c.
Referenced by GetProjectionName(), and Hologram().
m_Rotation
protected vector m_Rotation private
Definition at line 28 of file Hologram.c.
Referenced by AddProjectionRotation(), GetProjectionRotation(), Hologram(), and SubtractProjectionRotation().
m_SelectionsToRefresh
protected ref set<string> m_SelectionsToRefresh = new set<string> private
Definition at line 51 of file Hologram.c.
Referenced by RefreshVisual(), SetSelectionToRefresh(), and SetSelectionToRefresh().
m_SlopeTolerance
protected float m_SlopeTolerance private
Definition at line 46 of file Hologram.c.
Referenced by Hologram(), and IsBaseFlat().
m_UpdatePosition
protected bool m_UpdatePosition private
Definition at line 24 of file Hologram.c.
Referenced by GetUpdatePosition(), Hologram(), and SetUpdatePosition().
m_WatchtowerBlockedComponentNames
const protected ref array<string> m_WatchtowerBlockedComponentNames = new array<string> static private
Definition at line 58 of file Hologram.c.
Referenced by Hologram(), and IsObjectStatic().
m_WatchtowerIgnoreComponentNames
const protected ref array<string> m_WatchtowerIgnoreComponentNames = new array<string> static private
Definition at line 55 of file Hologram.c.
Referenced by CorrectForWatchtower(), Hologram(), and SetOnGround().
m_y_p_r_previous
protected vector m_y_p_r_previous private
Definition at line 29 of file Hologram.c.
Referenced by SmoothProjectionMovement().
m_YawPitchRollLimit
protected vector m_YawPitchRollLimit private
Definition at line 48 of file Hologram.c.
Referenced by Hologram(), and IsCollidingAngle().
PROJECTION_TRANSITION_MAX
protected const float PROJECTION_TRANSITION_MAX = 0.25 private
Definition at line 42 of file Hologram.c.
Referenced by SetHologramPosition().
PROJECTION_TRANSITION_MIN
protected const float PROJECTION_TRANSITION_MIN = 1 private
Definition at line 41 of file Hologram.c.
Referenced by SetHologramPosition().
SELECTION_INVENTORY
protected const string SELECTION_INVENTORY = "inventory" private
Definition at line 35 of file Hologram.c.
Referenced by SetAnimations().
SELECTION_PLACING
protected const string SELECTION_PLACING = "placing" private
Definition at line 34 of file Hologram.c.
Referenced by SetAnimations().
SMALL_PROJECTION_GROUND
protected const float SMALL_PROJECTION_GROUND = 2 private
Definition at line 38 of file Hologram.c.
Referenced by SetOnGround().
SMALL_PROJECTION_RADIUS
protected const float SMALL_PROJECTION_RADIUS = 1 private
Definition at line 37 of file Hologram.c.
Referenced by GetProjectionEntityPosition().
SPAWN_FLAGS
protected const int SPAWN_FLAGS = ECE_LOCAL private
Definition at line 6 of file Hologram.c.
Referenced by CreateTrigger().
SUFFIX_MATERIAL_DEPLOYABLE
protected const string SUFFIX_MATERIAL_DEPLOYABLE = "_deployable.rvmat" private
Definition at line 9 of file Hologram.c.
Referenced by CorrectMaterialPathName().
SUFFIX_MATERIAL_POWERED
protected const string SUFFIX_MATERIAL_POWERED = "_powered.rvmat" private
Definition at line 11 of file Hologram.c.
Referenced by CorrectMaterialPathName().
SUFFIX_MATERIAL_UNDEPLOYABLE
protected const string SUFFIX_MATERIAL_UNDEPLOYABLE = "_undeployable.rvmat" private
Definition at line 10 of file Hologram.c.
Referenced by CorrectMaterialPathName().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/Hologram.c