DayZ Scripts: TrapTrigger Class Reference
TrapTrigger Class Reference
Trigger used by traps.
Private Member Functions
void TrapTrigger ()
void SetParentObject (TrapBase obj)
override protected bool CanAddObjectAsInsider (Object object)
override protected void OnEnterServerEvent (TriggerInsider insider)
override protected void OnLeaveServerEvent (TriggerInsider insider)
void SetEnabled ()
prevents insider adding in the wrong position, HOTFIX
Private Attributes
bool m_Enabled = false
TrapBase m_ParentObj
Detailed Description
Trigger used by traps.
Constructor & Destructor Documentation
TrapTrigger()
void TrapTrigger () inline private
Member Function Documentation
CanAddObjectAsInsider()
override protected bool CanAddObjectAsInsider (Object object) inline private
References m_Enabled, and m_ParentObj.
OnEnterServerEvent()
override protected void OnEnterServerEvent (TriggerInsider insider) inline private
References TriggerInsider::GetObject(), and m_ParentObj.
OnLeaveServerEvent()
override protected void OnLeaveServerEvent (TriggerInsider insider) inline private
References TriggerInsider::GetObject(), and m_ParentObj.
SetEnabled()
void SetEnabled () inline private
prevents insider adding in the wrong position, HOTFIX
References m_Enabled.
Referenced by DeferredEnableTrigger().
SetParentObject()
void SetParentObject (TrapBase obj) inline private
References GetGame(), and m_ParentObj.
Referenced by CreateTrigger(), TrapBase::CreateTrigger(), and DeleteTrigger().
Field Documentation
m_Enabled
bool m_Enabled = false private
Referenced by CanAddObjectAsInsider(), and SetEnabled().
m_ParentObj
TrapBase m_ParentObj private
Referenced by CanAddObjectAsInsider(), OnEnterServerEvent(), OnLeaveServerEvent(), and SetParentObject().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ScriptedEntities/Triggers/TrapTrigger.c