DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionMineTree.c File Reference
ActionMineTree.c File Reference
Data Structures
class MineActionData
class ActionMineBase
Functions
override void CreateActionComponent ()
ActionMineBase ActionContinuousBase ActionMineTree ()
override ActionData CreateActionData ()
override bool CanBeUsedInFreelook ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
string GetYieldName (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanContinue (ActionData action_data)
not checking target damage anymore, callback takes care of that
override void OnEndServer (ActionData action_data)
Variables
MineActionData TIME_BETWEEN_MATERIAL_DROPS_DEFAULT = 4
EHarvestType m_HarvestType = EHarvestType.NORMAL
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionMineTree()
ActionMineBase ActionContinuousBase ActionMineTree ()
References TIME_BETWEEN_MATERIAL_DROPS_DEFAULT.
Referenced by ActionConstructor::RegisterActions(), and ToolBase::SetActions().
CanBeUsedInFreelook()
override bool CanBeUsedInFreelook ()
References UAMaxDistances::SMALL.
CanContinue()
override bool CanContinue (ActionData action_data)
not checking target damage anymore, callback takes care of that
References AnimatedActionBase::ActionConditionContinue().
CreateActionComponent()
override void CreateActionComponent ()
CreateActionData()
override ActionData CreateActionData ()
CreateConditionComponents()
override void CreateConditionComponents ()
GetYieldName()
string GetYieldName (PlayerBase player, ActionTarget target, ItemBase item)
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
OnEndServer()
override void OnEndServer (ActionData action_data)
References SEffectManager::DestroyEffecterParticleServer(), and MineActionData::m_EffecterID.
Variable Documentation
m_HarvestType
EHarvestType m_HarvestType = EHarvestType.NORMAL
Referenced by ActionMineTreeBark::ActionMineTreeBark().
TIME_BETWEEN_MATERIAL_DROPS_DEFAULT
MineActionData TIME_BETWEEN_MATERIAL_DROPS_DEFAULT = 4
Referenced by ActionMineTree().