DayZ Scripts: ActionWorldCraft Class Reference
ActionWorldCraft Class Reference
Private Member Functions
void ActionWorldCraft ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override string GetText ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override string GetSoundCategory (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override void Start (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnEndClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnFinishProgressClient (ActionData action_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Private Attributes
private string m_ActionPrompt
Constructor & Destructor Documentation
ActionWorldCraft()
void ActionWorldCraft () inline private
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References GetGame().
CreateActionData()
override ActionData CreateActionData () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetSoundCategory()
override string GetSoundCategory (ActionData action_data) inline private
References GetPlugin().
GetText()
override string GetText () inline private
References Class::CastTo(), GetGame(), GetPlayer(), GetPlugin(), and m_VariantID.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
References ActionTarget, WorldCraftActionReciveData::m_RecipeID, ActionData::m_Target, and vector::Zero.
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Class::CastTo(), GetPlugin(), m_Text, and m_VariantID.
OnEndClient()
override void OnEndClient (ActionData action_data) inline private
References ActionData::m_Player.
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
References ActionData::m_Player.
OnFinishProgressClient()
override void OnFinishProgressClient (ActionData action_data) inline private
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References Class::CastTo(), GetPlugin(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
References WorldCraftActionReciveData::m_RecipeID, and Serializer::Read().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
References Class::CastTo(), GetGame(), and m_VariantID.
Start()
override void Start (ActionData action_data) inline private
References ActionData::m_Player.
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
References Serializer::Write().
Field Documentation
m_ActionPrompt
private string m_ActionPrompt private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionWorldCraft.c