DayZ Scripts: StaticTransmitter Class Reference
StaticTransmitter Class Reference
Private Member Functions
override bool DisableVicinityIcon ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool IsStaticTransmitter ()
void SetNextFrequency (PlayerBase player=NULL)
override void OnSwitchOn ()
override void OnWorkStart ()
override void OnWorkStop ()
override void SetActions ()
Member Function Documentation
DisableVicinityIcon()
override bool DisableVicinityIcon () inline private
IsStaticTransmitter()
override bool IsStaticTransmitter () inline private
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
References Serializer::Write().
OnSwitchOn()
override void OnSwitchOn () inline private
OnWorkStart()
override void OnWorkStart () inline private
OnWorkStop()
override void OnWorkStop () inline private
SetActions()
override void SetActions () inline private
References AddAction().
SetNextFrequency()
void SetNextFrequency (PlayerBase player = NULL) inline private
The documentation for this class was generated from the following file:
4_World/Entities/AdvancedCommunication/Land_Radio_PanelBig.c