DayZ Scripts: MenuDefaultCharacterData Class Reference
MenuDefaultCharacterData Class Reference
Private Member Functions
void MenuDefaultCharacterData ()
void Init ()
void ClearAttachmentsMap ()
void SetDefaultAttachment (int slotID, string type)
void GenerateRandomEquip ()
void EquipDefaultCharacter (Man player)
void SerializeCharacterData (ParamsWriteContext ctx)
serializes data into a param array to be used by "StoreLoginData(notnull array<ref Param> params);"
bool DeserializeCharacterData (ParamsReadContext ctx)
void SetCharacterName (string name)
string GetCharacterName ()
void SetCharacterType (string character_type)
string GetCharacterType ()
void SetRandomCharacterForced (bool state)
bool IsRandomCharacterForced ()
map< int, string > GetAttachmentMap ()
void DumpAttMapContents ()
Private Attributes
string m_CharacterName
string m_CharacterType
ref map< int, string > m_AttachmentsMap
bool m_ForceRandomCharacter
Detailed Description
Definition at line 937 of file gameplay.c.
Constructor & Destructor Documentation
MenuDefaultCharacterData()
void MenuDefaultCharacterData () inline private
Definition at line 947 of file gameplay.c.
References Init().
Member Function Documentation
ClearAttachmentsMap()
void ClearAttachmentsMap () inline private
Definition at line 961 of file gameplay.c.
References m_AttachmentsMap.
Referenced by GenerateRandomEquip().
DeserializeCharacterData()
bool DeserializeCharacterData (ParamsReadContext ctx) inline private
Definition at line 1034 of file gameplay.c.
References m_AttachmentsMap, m_CharacterName, m_CharacterType, m_ForceRandomCharacter, and Serializer::Read().
Referenced by MissionBase::ProcessLoginData().
DumpAttMapContents()
void DumpAttMapContents () inline private
Definition at line 1085 of file gameplay.c.
References m_AttachmentsMap, and Print().
EquipDefaultCharacter()
void EquipDefaultCharacter (Man player) inline private
Definition at line 989 of file gameplay.c.
References ErrorEx, g_Game, and m_AttachmentsMap.
Referenced by UIScriptedMenu::BottomChanged(), Managed::CreateNewCharacter(), UIScriptedMenu::SetCharacter(), UIScriptedMenu::ShoesChanged(), and UIScriptedMenu::TopChanged().
GenerateRandomEquip()
void GenerateRandomEquip () inline private
Definition at line 971 of file gameplay.c.
References ClearAttachmentsMap(), Count, and SetDefaultAttachment().
Referenced by Managed::CreateNewCharacterByName(), MissionBase::OnClientNewEvent(), and UIScriptedMenu::RandomizeCharacter().
GetAttachmentMap()
map< int, string > GetAttachmentMap () inline private
Definition at line 1079 of file gameplay.c.
References m_AttachmentsMap.
Referenced by MissionBase::EquipCharacter().
GetCharacterName()
string GetCharacterName () inline private
Definition at line 1054 of file gameplay.c.
References m_CharacterName.
Referenced by Managed::GetCharacterName(), and Managed::GetCharacterNameById().
GetCharacterType()
string GetCharacterType () inline private
Definition at line 1064 of file gameplay.c.
References m_CharacterType.
Referenced by Managed::CreateDefaultCharacter(), and MissionBase::OnClientNewEvent().
Init()
void Init () inline private
Definition at line 952 of file gameplay.c.
References GetGame(), CGame::GetMenuData(), MenuData::LoadCharactersLocal(), and m_AttachmentsMap.
Referenced by MenuDefaultCharacterData().
IsRandomCharacterForced()
bool IsRandomCharacterForced () inline private
Definition at line 1074 of file gameplay.c.
References m_ForceRandomCharacter.
SerializeCharacterData()
void SerializeCharacterData (ParamsWriteContext ctx) inline private
serializes data into a param array to be used by "StoreLoginData(notnull array<ref Param> params);"
Definition at line 1025 of file gameplay.c.
References m_AttachmentsMap, m_CharacterName, m_CharacterType, m_ForceRandomCharacter, and Serializer::Write().
Referenced by MenuData::OnSetDefaultCharacter(), and CGame::StoreLoginDataPrepare().
SetCharacterName()
void SetCharacterName (string name) inline private
Definition at line 1049 of file gameplay.c.
References m_CharacterName, and name.
Referenced by Managed::CreateDefaultCharacter(), Managed::SaveCharName(), and DayZIntroSceneXbox::SaveCharName().
SetCharacterType()
void SetCharacterType (string character_type) inline private
Definition at line 1059 of file gameplay.c.
References m_CharacterType.
Referenced by Managed::CreateNewCharacterByName().
SetDefaultAttachment()
void SetDefaultAttachment (int slotID, string type) inline private
Definition at line 966 of file gameplay.c.
References m_AttachmentsMap.
Referenced by UIScriptedMenu::BottomChanged(), GenerateRandomEquip(), UIScriptedMenu::ShoesChanged(), and UIScriptedMenu::TopChanged().
SetRandomCharacterForced()
void SetRandomCharacterForced (bool state) inline private
Definition at line 1069 of file gameplay.c.
References m_ForceRandomCharacter.
Referenced by UIScriptedMenu::GameRespawn(), and UIScriptedMenu::GameRetry().
Field Documentation
m_AttachmentsMap
ref map<int,string> m_AttachmentsMap private
Definition at line 944 of file gameplay.c.
Referenced by ClearAttachmentsMap(), DeserializeCharacterData(), DumpAttMapContents(), EquipDefaultCharacter(), GetAttachmentMap(), Init(), SerializeCharacterData(), and SetDefaultAttachment().
m_CharacterName
string m_CharacterName private
Definition at line 942 of file gameplay.c.
Referenced by DeserializeCharacterData(), GetCharacterName(), SerializeCharacterData(), and SetCharacterName().
m_CharacterType
string m_CharacterType private
Definition at line 943 of file gameplay.c.
Referenced by DeserializeCharacterData(), GetCharacterType(), SerializeCharacterData(), and SetCharacterType().
m_ForceRandomCharacter
bool m_ForceRandomCharacter private
Definition at line 945 of file gameplay.c.
Referenced by DeserializeCharacterData(), IsRandomCharacterForced(), SerializeCharacterData(), and SetRandomCharacterForced().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/gameplay.c