DayZ Scripts: ActionCarDoorsOutside Class Reference
ActionCarDoorsOutside Class Reference
Private Member Functions
void ActionCarDoorsOutside ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
protected void FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3)
protected void FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1)
Private Attributes
protected int m_CommandUIDPerCrewIdx [4]
protected bool m_IsOpening = true
Detailed Description
Definition at line 1 of file ActionCarDoorsOutside.c.
Constructor & Destructor Documentation
ActionCarDoorsOutside()
void ActionCarDoorsOutside () inline private
Definition at line 6 of file ActionCarDoorsOutside.c.
References AnimatedActionBase::m_CommandUID, m_LockTargetOnUse, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
reach check from outside of car
player is outside of vehicle
player is looking at one of the doors, can't open if obstructed
if player is in car and cannot reach doors
is in reach, should open the door
Definition at line 19 of file ActionCarDoorsOutside.c.
References Class::CastTo(), UAMaxDistances::DEFAULT, CarScript::GetAnimSourceFromSelection(), CarScript::GetSeatIndexFromDoor(), IsInReach(), AnimatedActionBase::m_CommandUID, and m_IsOpening.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 13 of file ActionCarDoorsOutside.c.
References m_ConditionItem, and m_ConditionTarget.
FillCommandUIDPerCrewIdx() [1/2]
protected void FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3) inline private
Definition at line 117 of file ActionCarDoorsOutside.c.
References m_CommandUIDPerCrewIdx.
Referenced by ActionCloseCarDoorsOutside::ActionCloseCarDoorsOutside(), ActionOpenCarDoorsOutside::ActionOpenCarDoorsOutside(), and FillCommandUIDPerCrewIdx().
FillCommandUIDPerCrewIdx() [2/2]
protected void FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1) inline private
Definition at line 125 of file ActionCarDoorsOutside.c.
References FillCommandUIDPerCrewIdx().
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
Definition at line 107 of file ActionCarDoorsOutside.c.
References ActionData::m_Target.
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
Definition at line 66 of file ActionCarDoorsOutside.c.
References CarScript::GetAnimSourceFromSelection(), m_IsOpening, and ActionData::m_Target.
Field Documentation
m_CommandUIDPerCrewIdx
protected int m_CommandUIDPerCrewIdx[4] private
Definition at line 3 of file ActionCarDoorsOutside.c.
Referenced by FillCommandUIDPerCrewIdx().
m_IsOpening
protected bool m_IsOpening = true private
Definition at line 4 of file ActionCarDoorsOutside.c.
Referenced by ActionCloseCarDoorsOutside::ActionCloseCarDoorsOutside(), ActionCondition(), ActionOpenCarDoorsOutside::ActionOpenCarDoorsOutside(), and OnStartServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/Vehicles/ActionCarDoorsOutside.c