DayZ Scripts: P:/scripts/3_Game/VONManager.c File Reference
VONManager.c File Reference
Data Structures
class VONManagerBase
class VONManager
Manager class which handles Voice-over-network functionality while player is connected to a server.
Functions
VONManagerBase Managed VONManagerImplementation ()
void VONManagerBase ()
void HideVoiceNotification ()
Hides the VON notification completely and immediately.
void ShowVoiceNotification (int level, bool fading)
Shows the voice notification.
void HandleInput (Input inp)
Handles some VON related input.
void OnVOIPThresholdChanged ()
Fires every time VOIP threshold value changes.
void OnEvent (EventType eventTypeId, Param params)
Handles VON-related events.
bool IsVonToggled ()
void ~VONManagerImplementation ()
Variables
protected bool m_VoNToggled
ref ScriptInvoker m_OnVonStateEvent
ref ScriptInvoker m_OnPartyChatChangedEvent
Function Documentation
HandleInput()
override void HandleInput (Input inp)
Handles some VON related input.
Parameters
inp input to handle
Definition at line 113 of file VONManager.c.
References GetGame(), CGame::GetVoiceLevel(), VONManager::IsVoiceThresholdMinimum(), Input::LocalPress_ID(), m_VoNToggled, CGame::SetVoiceLevel(), and VONManagerBase::ShowVoiceNotification().
HideVoiceNotification()
override void HideVoiceNotification ()
Hides the VON notification completely and immediately.
Definition at line 41 of file VONManager.c.
IsVonToggled()
bool IsVonToggled ()
Definition at line 42 of file VONManager.c.
References GetGame(), Mission::GetMicrophoneIcon(), CGame::GetMission(), Mission::HideVoiceLevelWidgets(), and mission.
OnEvent()
void OnEvent (EventType eventTypeId, Param params)
Handles VON-related events.
Parameters
eventTypeId event that fired
params event-specific parameters
Definition at line 188 of file VONManager.c.
References Class::CastTo(), GetDayZGame(), GetGame(), CGame::GetMission(), CGame::GetVoiceLevel(), VONManagerBase::HideVoiceNotification(), ScriptInvoker::Invoke(), VONManager::IsVoiceThresholdMinimum(), Mission::IsVoNActive(), m_OnPartyChatChangedEvent, m_OnVonStateEvent, m_VoNToggled, mission, MPSessionPlayerReadyEventTypeID, PartyChatStatusChangedEventTypeID, Mission::SetVoNActive(), VONManagerBase::ShowVoiceNotification(), VONStartSpeakingEventTypeID, VONStateEventTypeID, VONStopSpeakingEventTypeID, VONUserStartedTransmittingAudioEventTypeID, and VONUserStoppedTransmittingAudioEventTypeID.
OnVOIPThresholdChanged()
override void OnVOIPThresholdChanged ()
Fires every time VOIP threshold value changes.
Definition at line 165 of file VONManager.c.
References GetGame(), CGame::GetMission(), VONManagerBase::HideVoiceNotification(), VONManager::IsVoiceThresholdMinimum(), m_VoNToggled, mission, and VONManagerBase::ShowVoiceNotification().
ShowVoiceNotification()
override void ShowVoiceNotification (int level, bool fading)
Shows the voice notification.
Parameters
level the loudness of the player voice. 0 = whisper, 1 = normal, 2 = shout
fading specifies whether icon should slowly fade to invisibility after being displayed
Definition at line 58 of file VONManager.c.
References GetGame(), Mission::GetMicrophoneIcon(), Mission::GetMicWidgetFadeTimer(), CGame::GetMission(), Mission::GetVoiceLevelTimers(), Mission::GetVoiceLevelWidgets(), and mission.
VONManagerBase()
void VONManagerBase ()
Definition at line 31 of file VONManager.c.
VONManagerImplementation()
VONManagerBase Managed VONManagerImplementation ()
Definition at line 1 of file VONManager.c.
Referenced by VONManager::Init().
~VONManagerImplementation()
void ~VONManagerImplementation ()
Definition at line 32 of file VONManager.c.
References ScriptInvoker::Clear(), m_OnPartyChatChangedEvent, and m_OnVonStateEvent.
Variable Documentation
m_OnPartyChatChangedEvent
ref ScriptInvoker m_OnPartyChatChangedEvent
Definition at line 29 of file VONManager.c.
Referenced by OnEvent(), and ~VONManagerImplementation().
m_OnVonStateEvent
ref ScriptInvoker m_OnVonStateEvent
Definition at line 28 of file VONManager.c.
Referenced by OnEvent(), and ~VONManagerImplementation().
m_VoNToggled
protected bool m_VoNToggled
Definition at line 27 of file VONManager.c.
Referenced by HandleInput(), OnEvent(), and OnVOIPThresholdChanged().