DayZ Scripts: BotGuardBase Class Reference
BotGuardBase Class Reference
represents guard on a transition from state to state
Private Member Functions
bool GuardCondition (BotEventBase e)
void BotGuardAnd (BotGuardBase arg0=NULL, BotGuardBase arg1=NULL)
override bool GuardCondition (BotEventBase e)
void BotGuardNot (BotGuardBase arg0=NULL)
override bool GuardCondition (BotEventBase e)
void BotGuardOr (BotGuardBase arg0=NULL, BotGuardBase arg1=NULL)
override bool GuardCondition (BotEventBase e)
Private Attributes
ref BotGuardBase m_arg0
ref BotGuardBase m_arg1
Detailed Description
represents guard on a transition from state to state
Member Function Documentation
BotGuardAnd()
void BotGuardAnd (BotGuardBase arg0 = NULL, BotGuardBase arg1 = NULL) inline private
BotGuardNot()
void BotGuardNot (BotGuardBase arg0 = NULL) inline private
BotGuardOr()
void BotGuardOr (BotGuardBase arg0 = NULL, BotGuardBase arg1 = NULL) inline private
GuardCondition() [1/4]
bool GuardCondition (BotEventBase e) inline private
GuardCondition() [2/4]
override bool GuardCondition (BotEventBase e) inline private
References botDebugPrint().
GuardCondition() [3/4]
override bool GuardCondition (BotEventBase e) inline private
References botDebugPrint().
GuardCondition() [4/4]
override bool GuardCondition (BotEventBase e) inline private
References botDebugPrint().
Field Documentation
m_arg0
ref BotGuardBase m_arg0 private
m_arg1
ref BotGuardBase m_arg1 private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Systems/Bot/BotGuards.c