DayZ Scripts: Managed Class Reference
Managed Class Reference
Enforce script essentials
TODO doc.
Private Member Functions
void IncreaseMaskUpdateCount ()
void ResetMaskUpdateCount ()
bool IsAnyEffectRunning ()
bool AreEffectsSuspended ()
void AddActiveEffects (array< int > effects)
void RemoveActiveEffects (array< int > effects)
void StopAllEffects ()
void AddSuspendRequest (int request_id)
void RemoveSuspendRequest (int request_id)
void ClearSuspendRequests ()
int GetSuspendRequestCount ()
void UpdateWidgets (int type=-1, float timeSlice=0, Param p=null, int handle=-1)
void Update (float timeSlice)
void OnVoiceEvent (float breathing_resistance01)
void SetBreathIntensityStamina (float stamina_cap, float stamina_current)
void RegisterGameplayEffectData (int id, Param p)
void IntroSceneCharacter ()
void ~IntroSceneCharacter ()
bool IsDefaultCharacter ()
void SetToDefaultCharacter ()
void SetCharacterID (int char_id)
int GetCharacterID ()
PlayerBase GetCharacterObj ()
TStringArray GetCharGenderList ()
TStringArray GetCharList (ECharGender gender)
TStringArray GetCharShirtsList ()
TStringArray GetCharPantsList ()
TStringArray GetCharShoesList ()
void SetCharacterGender (ECharGender gender)
bool IsCharacterFemale ()
ECharGender GetCharacterGender ()
vector GetPosition ()
int GetNextCharacterID ()
int GetPrevCharacterID ()
void CreateNewCharacterRandom ()
void CreateNewCharacterById (int character_id)
void CreateNewCharacterByName (string character_name, bool randomize_equip=true)
void CreateDefaultCharacter ()
void GetLastPlayedServer (int characterID, out string address, out string name, out int port)
void CreateNewCharacter ()
void LoadCharacterData (vector char_pos, vector char_rot, bool default_char=false)
Generates random equip for the new IntroSceneCharacter, whatever is defined in 'cfgCharacterCreation'.
protected void CharacterUnload ()
protected void CharacterLoad (int character_id, vector char_pos, vector char_rot)
protected void SetupPlayerName (bool new_name)
void SetAttachment (string type, int slot)
string GetCharacterNameById (int char_id)
string GetCharacterName ()
void SaveCharName (string name)
void SaveDefaultCharacter ()
void TransferValues (PlayerBase player)
void Init ()
void OnScheduledTick (float deltatime)
void CheckValues ()
float GetBlood ()
float GetHealth ()
void CheckHealth ()
void CheckBlood ()
void SendInitValues ()
Sends values on object creation.
void SendValue (int value_type, float value)
void ReceiveValue (int value_type, float value)
void OnRPC (ParamsReadContext ctx)
void ShowDebugValues (bool show)
void BleedingIndicator (int source_ID, int severity, GameplayEffectsDataBleeding parent)
void InitIndicator (vector position)
void StopIndicator (bool instant=false)
protected void StartRunningDrops ()
protected bool IsRunningDrops ()
Are any drops currently being animated?
void TrySpawnNextDrop ()
protected void ResetSequence ()
void ResetIndicator ()
void Update (float timeSlice)
bool GetEndNow ()
int GetSeverity ()
void GameplayEffectsData (array< ref Widget > input, int type, int user_override=-1)
void Init (array< ref Widget > input, int type, Widget layout_root, int user_override=-1)
array< ref Widget > GetWidgetSet ()
int GetWidgetSetType ()
int GetWidgetSetID ()
bool HasDefinedHandle ()
Returns 'true' if this class contains update info.
bool DataInitialized ()
void UpdateVisibility (bool state)
void RegisterData (Param p)
void Update (float timeSlice=0, Param p=null, int handle=-1)
void ForceStop ()
Static Private Member Functions
static void Init ()
static void Cleanup ()
static PPERequesterBase GetRequester (typename type)
Returns an instance (singleton) of a requester based on typename.
static PPERequesterBase GetRequester (int index)
Returns an instance (singleton) of a requester based on index.
static int GetRequesterID (typename type)
Returns an ID of a requester type.
static GetRequesterTypename (int index)
Returns a typename from a requester ID.
static int RegisterRequester (typename type)
Registers new requester type.
static bool VerifyRequester (PPERequesterBase req)
Verifies the instance.
Private Attributes
int m_MaskWidgetUpdateCount
protected int m_CharacterId
protected string m_CharacterType
protected MenuData m_CharacterDta
protected PlayerBase m_CharacterObj
protected vector m_CharacterPos
protected vector m_CharacterRot
protected ref TStringArray m_CharGenderList = new TStringArray
protected ref TStringArray m_CharShirtList = new TStringArray
protected ref TStringArray m_CharPantsList = new TStringArray
protected ref TStringArray m_CharShoesList = new TStringArray
protected ref map< ECharGender, ref array< string > > m_Characters = new map<ECharGender, ref array<string>>
protected ECharGender m_CharGender
const int TYPE_HEALTH = 1
const int TYPE_BLOOD = 2
const float VALUE_CHECK_INTERVAL = 5
const float SENSITIVTY_PERCENTAGE = 1
const int BLOOD_THRESHOLD_LOW = 3000
PlayerBase m_Player
float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1
float m_LastHealthUpdate
float m_LastBloodUpdate
float m_HealthMaxValue
float m_BloodMaxValue
float m_BloodClient
float m_HealthClient
protected bool m_InitialSyncSent
int m_AnimType
float m_HitDir
float m_HealthDamage
bool m_Fullbody
bool m_HasSource
protected bool m_Initialized
protected bool m_Terminating = false
protected bool m_EndNow = false
protected bool m_IsRunning = false
protected int m_DropSpawnsQueued
protected int m_ActiveDropsCount
protected int m_Severity
protected int m_SourceID
protected GameplayEffectsDataBleeding m_ParentMetaData
protected array< float > m_DropProbabilityArray
protected float m_AverageFrequency
protected float m_SequenceTick
protected float m_SequenceDuration
protected float m_TimeElapsedTotal
protected float m_TimeElapsedSequence
protected float m_LastDropSpawnTime
protected float m_DropSpawnMinDelay
protected float m_DropSpawnMaxDelay
protected int m_CurrentDropProbabilityStep
protected int m_DropProbabilityRollsCount
protected vector m_BasePosition
ref set< ref BleedingIndicatorDropData > m_ActiveDrops
ref set< int > m_CleanupQueue
protected ref array< ref Widget > m_WidgetArray
int m_Type
int m_WidgetSetIdentifier
Widget m_LayoutRoot
Static Private Attributes
static private ref map< int, ref PPERequesterBase > m_Instances
static private bool m_Initialized = false
static int m_lastID = -1
static const int INVALID = -1
static const int REQ_INVENTORYBLUR = RegisterRequester(PPERequester_InventoryBlur)
static const int REQ_CONTROLLERDISCONNECT = RegisterRequester(PPERequester_ControllerDisconnectBlur)
static const int REQ_GLASSESSPORTBLACK = RegisterRequester(PPERequester_GlassesSportBlack)
static const int REQ_GLASSESSPORTBLUE = RegisterRequester(PPERequester_GlassesSportBlue)
static const int REQ_GLASSESSPORTGREEN = RegisterRequester(PPERequester_GlassesSportGreen)
static const int REQ_GLASSESSPORTORANGE = RegisterRequester(PPERequester_GlassesSportOrange)
static const int REQ_GLASSESAVIATOR = RegisterRequester(PPERequester_GlassesAviator)
static const int REQ_GLASSESDESIGNER = RegisterRequester(PPERequester_GlassesDesignerBlack)
static const int REQ_GLASSESTACTICAL = RegisterRequester(PPERequester_TacticalGoggles)
static const int REQ_MOTOHELMETBLACK = RegisterRequester(PPERequester_MotoHelmetBlack)
static const int REQ_GLASSESWELDING = RegisterRequester(PPERequester_WeldingMask)
static const int REQ_CAMERANV = RegisterRequester(PPERequester_CameraNV)
static const int REQ_CAMERAADS = RegisterRequester(PPERequester_CameraADS)
static const int REQ_BLOODLOSS = RegisterRequester(PPERequester_BloodLoss)
static const int REQ_DEATHEFFECTS = RegisterRequester(PPERequester_DeathDarkening)
static const int REQ_UNCONEFFECTS = RegisterRequester(PPERequester_UnconEffects)
static const int REQ_TUNELVISSION = RegisterRequester(PPERequester_TunnelVisionEffects)
static const int REQ_BURLAPSACK = RegisterRequester(PPERequester_BurlapSackEffects)
static const int REQ_INTROCHROMABB = RegisterRequester(PPERequester_IntroChromAbb)
static const int REQ_FEVEREFFECTS = RegisterRequester(PPERequester_FeverEffects)
static const int REQ_FLASHBANGEFFECTS = RegisterRequester(PPERequester_FlashbangEffects)
static const int REQ_SHOCKHITEFFECTS = RegisterRequester(PPERequester_ShockHitReaction)
static const int REQ_HEALTHHITEFFECTS = RegisterRequester(PPERequester_HealthHitReaction)
static const int REQ_MENUEFFECTS = RegisterRequester(PPERequester_MenuEffects)
static const int REQ_CONTROLLERBLUR = RegisterRequester(PPERequester_ControlsBlur)
static const int REQ_SERVERBROWSEREFFECTS = RegisterRequester(PPERequester_ServerBrowserBlur)
static const int REQ_TUTORIALEFFECTS = RegisterRequester(PPERequester_TutorialMenu)
static const int REQ_CONTAMINATEDAREA = RegisterRequester(PPERequester_ContaminatedAreaTint)
static const int REQ_SPOOKYAREA = RegisterRequester(PPERequester_SpookyAreaTint)
static const int REQ_PAINBLUR = RegisterRequester(PPERequester_PainBlur)
static const int REQ_UNDERGROUND = RegisterRequester(PPERUndergroundAcco)
static const int REQ_DROWNING = RegisterRequester(PPERequester_Drowning)
static private ref PPERequesterRegistrations m_Registrations
Detailed Description
TODO doc.
generic metadata class
indicator wrapper for a specific bleeding source.
extendable type to allow for smarter hit data syncing
Requester bank contains all registered type instances as singletons. Creating new instances outside of bank might be a bad idea (and a way to memory leakage)
Constructor & Destructor Documentation
~IntroSceneCharacter()
void ~IntroSceneCharacter () inline private
References CharacterUnload().
Member Function Documentation
AddActiveEffects()
void AddActiveEffects (array< int > effects) inline private
AddSuspendRequest()
void AddSuspendRequest (int request_id) inline private
AreEffectsSuspended()
bool AreEffectsSuspended () inline private
BleedingIndicator()
void BleedingIndicator (int source_ID, int severity, GameplayEffectsDataBleeding parent) inline private
References BleedingIndicationConstants::INDICATOR_SEVERITY_HIGH, BleedingIndicationConstants::INDICATOR_SEVERITY_LOW, BleedingIndicationConstants::INDICATOR_SEVERITY_MEDIUM, Debug::Log(), DbgBleedingIndicationStaticInfo::m_DbgDropMaxDelay, DbgBleedingIndicationStaticInfo::m_DbgDropMinDelay, DbgBleedingIndicationStaticInfo::m_DbgSequenceDuration, DbgBleedingIndicationStaticInfo::m_DbgUseOverrideValues, m_Initialized, BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_HIGH, BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_LOW, BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_MEDIUM, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MAX_HIGH, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MAX_LOW, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MAX_MEDIUM, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MIN_HIGH, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MIN_LOW, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MIN_MEDIUM, BleedingIndicationConstants::SEQUENCE_DURATION_HIGH, BleedingIndicationConstants::SEQUENCE_DURATION_LOW, and BleedingIndicationConstants::SEQUENCE_DURATION_MEDIUM.
CharacterLoad()
protected void CharacterLoad (int character_id, vector char_pos, vector char_rot) inline private
References CharacterUnload(), MenuData::CreateCharacterPerson(), Error(), and SetCharacterID().
Referenced by CreateNewCharacterById().
CharacterUnload()
protected void CharacterUnload () inline private
References g_Game.
Referenced by CharacterLoad(), CreateDefaultCharacter(), CreateNewCharacter(), and ~IntroSceneCharacter().
CheckBlood()
void CheckBlood () inline private
References Math::AbsFloat(), Math::Clamp(), Math::InverseLerp(), m_LastBloodUpdate, m_Player, SendValue(), and SENSITIVTY_PERCENTAGE.
Referenced by CheckValues().
CheckHealth()
void CheckHealth () inline private
References Math::AbsFloat(), m_HealthMaxValue, m_LastHealthUpdate, m_LastHealthUpdate, m_Player, SendValue(), and SENSITIVTY_PERCENTAGE.
Referenced by CheckValues().
CheckValues()
void CheckValues () inline private
References CheckBlood(), and CheckHealth().
Referenced by OnScheduledTick().
Cleanup()
static void Cleanup () inline static private
References m_Initialized, m_Instances, and m_Registrations.
ClearSuspendRequests()
void ClearSuspendRequests () inline private
CreateDefaultCharacter()
void CreateDefaultCharacter () inline private
References CharacterUnload(), CreateNewCharacter(), CreateNewCharacterRandom(), GameConstants::DEFAULT_CHARACTER_NAME, MenuDefaultCharacterData::GetCharacterType(), GetGame(), CGame::GetMenuDefaultCharacterData(), and MenuDefaultCharacterData::SetCharacterName().
Referenced by CreateNewCharacterById().
CreateNewCharacter()
void CreateNewCharacter () inline private
References CharacterUnload(), ECE_PLACE_ON_SURFACE, MenuDefaultCharacterData::EquipDefaultCharacter(), g_Game, GetGame(), CGame::GetMenuDefaultCharacterData(), and SetupPlayerName().
Referenced by CreateDefaultCharacter(), and CreateNewCharacterByName().
CreateNewCharacterById()
void CreateNewCharacterById (int character_id) inline private
References CharacterLoad(), CreateDefaultCharacter(), and GameConstants::DEFAULT_CHARACTER_MENU_ID.
Referenced by LoadCharacterData().
CreateNewCharacterByName()
void CreateNewCharacterByName (string character_name, bool randomize_equip = true) inline private
References CreateNewCharacter(), MenuDefaultCharacterData::GenerateRandomEquip(), GetGame(), CGame::GetMenuDefaultCharacterData(), and MenuDefaultCharacterData::SetCharacterType().
Referenced by CreateNewCharacterRandom().
CreateNewCharacterRandom()
void CreateNewCharacterRandom () inline private
References CreateNewCharacterByName(), GetCharacterGender(), Math::RandomInt(), and SetCharacterGender().
Referenced by CreateDefaultCharacter().
DataInitialized()
bool DataInitialized () inline private
ForceStop()
void ForceStop () private
GameplayEffectsData()
void GameplayEffectsData (array< ref Widget > input, int type, int user_override = -1) inline private
References m_Type.
GetBlood()
float GetBlood () inline private
References m_BloodClient.
GetCharacterGender()
ECharGender GetCharacterGender () inline private
References m_CharGender.
Referenced by CreateNewCharacterRandom().
GetCharacterID()
int GetCharacterID () inline private
References m_CharacterId.
GetCharacterName()
string GetCharacterName () inline private
References MenuDefaultCharacterData::GetCharacterName(), MenuData::GetCharacterName(), GetGame(), CGame::GetMenuDefaultCharacterData(), and IsDefaultCharacter().
GetCharacterNameById()
string GetCharacterNameById (int char_id) inline private
References GameConstants::DEFAULT_CHARACTER_MENU_ID, MenuDefaultCharacterData::GetCharacterName(), MenuData::GetCharacterName(), GetGame(), and CGame::GetMenuDefaultCharacterData().
GetCharacterObj()
PlayerBase GetCharacterObj () inline private
References m_CharacterObj.
Referenced by LoadCharacterData(), and DayZIntroScene::ResetIntroCamera().
GetCharGenderList()
TStringArray GetCharGenderList () inline private
References m_CharGenderList.
GetCharList()
TStringArray GetCharList (ECharGender gender) inline private
GetCharPantsList()
TStringArray GetCharPantsList () inline private
References m_CharPantsList.
GetCharShirtsList()
TStringArray GetCharShirtsList () inline private
References m_CharShirtList.
GetCharShoesList()
TStringArray GetCharShoesList () inline private
References m_CharShoesList.
GetEndNow()
bool GetEndNow () inline private
References m_EndNow.
GetHealth()
float GetHealth () inline private
References m_HealthClient.
GetLastPlayedServer()
void GetLastPlayedServer (int characterID, out string address, out string name, out int port) inline private
References MenuData::GetLastServerAddress(), MenuData::GetLastServerName(), MenuData::GetLastServerPort(), and name.
GetNextCharacterID()
int GetNextCharacterID () inline private
References MenuData::GetCharactersCount().
GetPosition()
vector GetPosition () inline private
Referenced by DayZIntroScene::ResetIntroCamera().
GetPrevCharacterID()
int GetPrevCharacterID () inline private
References MenuData::GetCharactersCount().
GetRequester() [1/2]
static PPERequesterBase GetRequester (int index) inline static private
Returns an instance (singleton) of a requester based on index.
Parameters
index int Index of the registered requester.
Returns
PPERequesterBase Requester singleton.
Note
Returns only already registered instances, does not register anything.
References Debug::Log(), and m_Instances.
GetRequester() [2/2]
static PPERequesterBase GetRequester (typename type) inline static private
Returns an instance (singleton) of a requester based on typename.
Parameters
type typename Typename of the requester.
Returns
PPERequesterBase Requester singleton.
Note
Returns only already registered instances, does not register anything.
References Class::CastTo(), Error(), Debug::Log(), and m_Instances.
GetRequesterID()
static int GetRequesterID (typename type) inline static private
Returns an ID of a requester type.
Parameters
type typename Typename of the requester.
Returns
int Requester ID.
Note
Returns '-1' if not found.
References Debug::Log(), and m_Instances.
GetRequesterTypename()
static GetRequesterTypename (int index) inline static private
Returns a typename from a requester ID.
Parameters
index int ID of the requester.
Returns
typename Requester typename.
References Debug::Log(), and m_Instances.
GetSeverity()
int GetSeverity () inline private
References m_Severity.
GetSuspendRequestCount()
int GetSuspendRequestCount () inline private
GetWidgetSet()
array< ref Widget > GetWidgetSet () inline private
GetWidgetSetID()
int GetWidgetSetID () inline private
GetWidgetSetType()
int GetWidgetSetType () inline private
References m_Type.
HasDefinedHandle()
bool HasDefinedHandle () inline private
Returns 'true' if this class contains update info.
IncreaseMaskUpdateCount()
void IncreaseMaskUpdateCount () inline private
Init() [1/3]
static void Init () inline static private
References m_Initialized, m_Instances, m_Registrations, and PPERequesterRegistrations().
Referenced by TransferValues().
Init() [2/3]
void Init () inline private
References m_HealthMaxValue, m_LastHealthUpdate, and m_Player.
Init() [3/3]
void Init (array< ref Widget > input, int type, Widget layout_root, int user_override = -1) inline private
References m_Type.
InitIndicator()
void InitIndicator (vector position) inline private
References m_Initialized, and ResetIndicator().
IntroSceneCharacter()
void IntroSceneCharacter () inline private
References GameConstants::DEFAULT_CHARACTER_MENU_ID.
Referenced by DayZIntroScene::DayZIntroScene(), and DayZIntroSceneXbox::DayZIntroSceneXbox().
IsAnyEffectRunning()
bool IsAnyEffectRunning () inline private
IsCharacterFemale()
bool IsCharacterFemale () inline private
IsDefaultCharacter()
bool IsDefaultCharacter () inline private
References GameConstants::DEFAULT_CHARACTER_MENU_ID.
Referenced by GetCharacterName(), and SaveCharName().
IsRunningDrops()
protected bool IsRunningDrops () inline private
Are any drops currently being animated?
Referenced by Update().
LoadCharacterData()
void LoadCharacterData (vector char_pos, vector char_rot, bool default_char = false) inline private
Generates random equip for the new IntroSceneCharacter, whatever is defined in 'cfgCharacterCreation'.
References CreateNewCharacterById(), g_Game, MenuData::GetCharacterName(), GetCharacterObj(), GetGame(), MenuData::GetLastPlayedCharacter(), CGame::ListAvailableCharacters(), and SetCharacterGender().
OnRPC()
void OnRPC (ParamsReadContext ctx) inline private
References CachedObjectsParams::PARAM2_INT_FLOAT, Serializer::Read(), and ReceiveValue().
OnScheduledTick()
void OnScheduledTick (float deltatime) inline private
References CheckValues(), DiagMenu::GetBool(), GetGame(), m_TimeSinceLastTick, SendInitValues(), ShowDebugValues(), and VALUE_CHECK_INTERVAL.
OnVoiceEvent()
void OnVoiceEvent (float breathing_resistance01) inline private
ReceiveValue()
void ReceiveValue (int value_type, float value) inline private
Referenced by OnRPC().
RegisterData()
void RegisterData (Param p) inline private
RegisterGameplayEffectData()
void RegisterGameplayEffectData (int id, Param p) inline private
RegisterRequester()
static int RegisterRequester (typename type) inline static private
Registers new requester type.
Note
Performed only on game start. New requesters can be registered in 'PPERequesterRegistrations'
References GetRequester(), Debug::Log(), m_Instances, m_lastID, m_lastID, and PPERequesterBase::SetRequesterIDX().
RemoveActiveEffects()
void RemoveActiveEffects (array< int > effects) inline private
RemoveSuspendRequest()
void RemoveSuspendRequest (int request_id) inline private
ResetIndicator()
void ResetIndicator () inline private
Referenced by InitIndicator().
ResetMaskUpdateCount()
void ResetMaskUpdateCount () inline private
ResetSequence()
protected void ResetSequence () inline private
Referenced by Update().
SaveCharName()
void SaveCharName (string name) inline private
References GetGame(), CGame::GetMenuDefaultCharacterData(), IsDefaultCharacter(), name, MenuData::SaveCharactersLocal(), MenuData::SetCharacterName(), and MenuDefaultCharacterData::SetCharacterName().
SaveDefaultCharacter()
void SaveDefaultCharacter () inline private
References MenuData::RequestSetDefaultCharacterData().
SendInitValues()
void SendInitValues () inline private
Sends values on object creation.
References Math::Clamp(), Math::InverseLerp(), m_HealthMaxValue, m_LastHealthUpdate, m_Player, and SendValue().
Referenced by OnScheduledTick().
SendValue()
void SendValue (int value_type, float value) inline private
References GetGame(), m_Player, CachedObjectsParams::PARAM2_INT_FLOAT, and CGame::RPCSingleParam().
Referenced by CheckBlood(), CheckHealth(), and SendInitValues().
SetAttachment()
void SetAttachment (string type, int slot) inline private
References ECE_PLACE_ON_SURFACE, and g_Game.
SetBreathIntensityStamina()
void SetBreathIntensityStamina (float stamina_cap, float stamina_current) inline private
SetCharacterGender()
void SetCharacterGender (ECharGender gender) inline private
Referenced by CreateNewCharacterRandom(), and LoadCharacterData().
SetCharacterID()
void SetCharacterID (int char_id) inline private
Referenced by CharacterLoad().
SetToDefaultCharacter()
void SetToDefaultCharacter () inline private
References GameConstants::DEFAULT_CHARACTER_MENU_ID.
SetupPlayerName()
protected void SetupPlayerName (bool new_name) inline private
References GameConstants::DEFAULT_CHARACTER_NAME, g_Game, MenuData::GetCharacterName(), GetGame(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), and name.
Referenced by CreateNewCharacter().
ShowDebugValues()
void ShowDebugValues (bool show) inline private
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), DbgUI::EndCleanupScope(), DbgUI::Text(), and float::ToString().
Referenced by OnScheduledTick().
StartRunningDrops()
protected void StartRunningDrops () inline private
References m_IsRunning, and TrySpawnNextDrop().
Referenced by Update().
StopAllEffects()
void StopAllEffects () inline private
StopIndicator()
void StopIndicator (bool instant = false) inline private
References m_IsRunning.
TransferValues()
void TransferValues (PlayerBase player) inline private
References Init(), and m_Player.
TrySpawnNextDrop()
void TrySpawnNextDrop () inline private
References Class::CastTo(), m_TimeElapsedTotal, BleedingIndicatorDropData::SetBasePosition(), and BleedingIndicatorDropData::StartDrop().
Referenced by StartRunningDrops(), and Update().
Update() [1/3]
void Update (float timeSlice) inline private
Update() [2/3]
void Update (float timeSlice) inline private
References IsRunning(), IsRunningDrops(), m_ActiveDropsCount, DbgBleedingIndicationStaticInfo::m_DbgSequenceDuration, DbgBleedingIndicationStaticInfo::m_DbgUseOverrideValues, m_DropProbabilityRollsCount, m_Initialized, m_IsRunning, m_LastDropSpawnTime, Math::RandomFloat01(), ResetSequence(), StartRunningDrops(), and TrySpawnNextDrop().
Update() [3/3]
void Update (float timeSlice = 0, Param p = null, int handle = -1) inline private
UpdateVisibility()
void UpdateVisibility (bool state) inline private
UpdateWidgets()
void UpdateWidgets (int type = -1, float timeSlice = 0, Param p = null, int handle = -1) inline private
VerifyRequester()
static bool VerifyRequester (PPERequesterBase req) inline static private
Verifies the instance.
References Debug::Log(), m_Initialized, and m_Instances.
Field Documentation
BLOOD_THRESHOLD_LOW
const int BLOOD_THRESHOLD_LOW = 3000 private
INVALID
const int INVALID = -1 static private
m_ActiveDrops
ref set<ref BleedingIndicatorDropData> m_ActiveDrops private
m_ActiveDropsCount
protected int m_ActiveDropsCount private
Referenced by Update().
m_AnimType
int m_AnimType private
Referenced by DayZPlayerSyncJunctures::SendDamageHitEx().
m_AverageFrequency
protected float m_AverageFrequency private
m_BasePosition
protected vector m_BasePosition private
m_BloodClient
float m_BloodClient private
Referenced by GetBlood().
m_BloodMaxValue
float m_BloodMaxValue private
m_CharacterDta
protected MenuData m_CharacterDta private
m_CharacterId
protected int m_CharacterId private
Referenced by GetCharacterID().
m_CharacterObj
protected PlayerBase m_CharacterObj private
Referenced by GetCharacterObj().
m_CharacterPos
protected vector m_CharacterPos private
m_CharacterRot
protected vector m_CharacterRot private
m_Characters
protected ref map<ECharGender, ref array<string> > m_Characters = new map<ECharGender, ref array<string>> private
m_CharacterType
protected string m_CharacterType private
m_CharGender
protected ECharGender m_CharGender private
Referenced by GetCharacterGender().
m_CharGenderList
protected ref TStringArray m_CharGenderList = new TStringArray private
Referenced by GetCharGenderList().
m_CharPantsList
protected ref TStringArray m_CharPantsList = new TStringArray private
Referenced by GetCharPantsList().
m_CharShirtList
protected ref TStringArray m_CharShirtList = new TStringArray private
Referenced by GetCharShirtsList().
m_CharShoesList
protected ref TStringArray m_CharShoesList = new TStringArray private
Referenced by GetCharShoesList().
m_CleanupQueue
ref set<int> m_CleanupQueue private
m_CurrentDropProbabilityStep
protected int m_CurrentDropProbabilityStep private
m_DropProbabilityArray
protected array<float> m_DropProbabilityArray private
m_DropProbabilityRollsCount
protected int m_DropProbabilityRollsCount private
Referenced by Update().
m_DropSpawnMaxDelay
protected float m_DropSpawnMaxDelay private
m_DropSpawnMinDelay
protected float m_DropSpawnMinDelay private
m_DropSpawnsQueued
protected int m_DropSpawnsQueued private
m_EndNow
protected bool m_EndNow = false private
Referenced by GetEndNow().
m_Fullbody
bool m_Fullbody private
m_HasSource
bool m_HasSource private
m_HealthClient
float m_HealthClient private
Referenced by GetHealth().
m_HealthDamage
float m_HealthDamage private
m_HealthMaxValue
float m_HealthMaxValue private
Referenced by CheckHealth(), and SendInitValues().
m_HitDir
float m_HitDir private
m_Initialized [1/2]
private bool m_Initialized = false static private
m_Initialized [2/2]
protected bool m_Initialized private
m_InitialSyncSent
protected bool m_InitialSyncSent private
m_Instances
private ref map<int,ref PPERequesterBase> m_Instances static private
m_IsRunning
protected bool m_IsRunning = false private
m_LastBloodUpdate
float m_LastBloodUpdate private
Referenced by CheckBlood().
m_LastDropSpawnTime
protected float m_LastDropSpawnTime private
Referenced by Update().
m_LastHealthUpdate
float m_LastHealthUpdate private
Referenced by CheckHealth().
m_lastID
int m_lastID = -1 static private
Referenced by RegisterRequester().
m_LayoutRoot
Widget m_LayoutRoot private
m_MaskWidgetUpdateCount
int m_MaskWidgetUpdateCount private
m_ParentMetaData
protected GameplayEffectsDataBleeding m_ParentMetaData private
m_Player
PlayerBase m_Player private
m_Registrations
private ref PPERequesterRegistrations m_Registrations static private
Referenced by Cleanup().
m_SequenceDuration
protected float m_SequenceDuration private
m_SequenceTick
protected float m_SequenceTick private
m_Severity
protected int m_Severity private
Referenced by GetSeverity().
m_SourceID
protected int m_SourceID private
m_Terminating
protected bool m_Terminating = false private
m_TimeElapsedSequence
protected float m_TimeElapsedSequence private
m_TimeElapsedTotal
protected float m_TimeElapsedTotal private
Referenced by TrySpawnNextDrop().
m_TimeSinceLastTick
float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1 private
m_Type
int m_Type private
m_WidgetArray
protected ref array<ref Widget> m_WidgetArray private
m_WidgetSetIdentifier
int m_WidgetSetIdentifier private
REQ_BLOODLOSS
const int REQ_BLOODLOSS = RegisterRequester(PPERequester_BloodLoss) static private
REQ_BURLAPSACK
const int REQ_BURLAPSACK = RegisterRequester(PPERequester_BurlapSackEffects) static private
REQ_CAMERAADS
const int REQ_CAMERAADS = RegisterRequester(PPERequester_CameraADS) static private
REQ_CAMERANV
const int REQ_CAMERANV = RegisterRequester(PPERequester_CameraNV) static private
REQ_CONTAMINATEDAREA
const int REQ_CONTAMINATEDAREA = RegisterRequester(PPERequester_ContaminatedAreaTint) static private
REQ_CONTROLLERBLUR
const int REQ_CONTROLLERBLUR = RegisterRequester(PPERequester_ControlsBlur) static private
REQ_CONTROLLERDISCONNECT
const int REQ_CONTROLLERDISCONNECT = RegisterRequester(PPERequester_ControllerDisconnectBlur) static private
REQ_DEATHEFFECTS
const int REQ_DEATHEFFECTS = RegisterRequester(PPERequester_DeathDarkening) static private
REQ_DROWNING
const int REQ_DROWNING = RegisterRequester(PPERequester_Drowning) static private
REQ_FEVEREFFECTS
const int REQ_FEVEREFFECTS = RegisterRequester(PPERequester_FeverEffects) static private
REQ_FLASHBANGEFFECTS
const int REQ_FLASHBANGEFFECTS = RegisterRequester(PPERequester_FlashbangEffects) static private
REQ_GLASSESAVIATOR
const int REQ_GLASSESAVIATOR = RegisterRequester(PPERequester_GlassesAviator) static private
REQ_GLASSESDESIGNER
const int REQ_GLASSESDESIGNER = RegisterRequester(PPERequester_GlassesDesignerBlack) static private
REQ_GLASSESSPORTBLACK
const int REQ_GLASSESSPORTBLACK = RegisterRequester(PPERequester_GlassesSportBlack) static private
REQ_GLASSESSPORTBLUE
const int REQ_GLASSESSPORTBLUE = RegisterRequester(PPERequester_GlassesSportBlue) static private
REQ_GLASSESSPORTGREEN
const int REQ_GLASSESSPORTGREEN = RegisterRequester(PPERequester_GlassesSportGreen) static private
REQ_GLASSESSPORTORANGE
const int REQ_GLASSESSPORTORANGE = RegisterRequester(PPERequester_GlassesSportOrange) static private
REQ_GLASSESTACTICAL
const int REQ_GLASSESTACTICAL = RegisterRequester(PPERequester_TacticalGoggles) static private
REQ_GLASSESWELDING
const int REQ_GLASSESWELDING = RegisterRequester(PPERequester_WeldingMask) static private
REQ_HEALTHHITEFFECTS
const int REQ_HEALTHHITEFFECTS = RegisterRequester(PPERequester_HealthHitReaction) static private
REQ_INTROCHROMABB
const int REQ_INTROCHROMABB = RegisterRequester(PPERequester_IntroChromAbb) static private
REQ_INVENTORYBLUR
const int REQ_INVENTORYBLUR = RegisterRequester(PPERequester_InventoryBlur) static private
REQ_MENUEFFECTS
const int REQ_MENUEFFECTS = RegisterRequester(PPERequester_MenuEffects) static private
REQ_MOTOHELMETBLACK
const int REQ_MOTOHELMETBLACK = RegisterRequester(PPERequester_MotoHelmetBlack) static private
REQ_PAINBLUR
const int REQ_PAINBLUR = RegisterRequester(PPERequester_PainBlur) static private
REQ_SERVERBROWSEREFFECTS
const int REQ_SERVERBROWSEREFFECTS = RegisterRequester(PPERequester_ServerBrowserBlur) static private
REQ_SHOCKHITEFFECTS
const int REQ_SHOCKHITEFFECTS = RegisterRequester(PPERequester_ShockHitReaction) static private
REQ_SPOOKYAREA
const int REQ_SPOOKYAREA = RegisterRequester(PPERequester_SpookyAreaTint) static private
REQ_TUNELVISSION
const int REQ_TUNELVISSION = RegisterRequester(PPERequester_TunnelVisionEffects) static private
REQ_TUTORIALEFFECTS
const int REQ_TUTORIALEFFECTS = RegisterRequester(PPERequester_TutorialMenu) static private
REQ_UNCONEFFECTS
const int REQ_UNCONEFFECTS = RegisterRequester(PPERequester_UnconEffects) static private
REQ_UNDERGROUND
const int REQ_UNDERGROUND = RegisterRequester(PPERUndergroundAcco) static private
SENSITIVTY_PERCENTAGE
const float SENSITIVTY_PERCENTAGE = 1 private
TYPE_BLOOD
const int TYPE_BLOOD = 2 private
TYPE_HEALTH
const int TYPE_HEALTH = 1 private
VALUE_CHECK_INTERVAL
const float VALUE_CHECK_INTERVAL = 5 private
The documentation for this class was generated from the following files:
P:/scripts/1_core/proto/enscript.c
P:/scripts/3_game/gameplayeffectwidgets_base.c
P:/scripts/3_game/ppemanager/pperequesterbank.c
P:/scripts/4_world/classes/introscenecharacter.c
P:/scripts/4_world/classes/transfervalues.c
P:/scripts/4_world/entities/synchitinfo.c
P:/scripts/5_mission/mission/gameplayeffectwidgets/bleedingindicators/bleedingindicator.c
P:/scripts/5_mission/mission/gameplayeffectwidgets/gewidgetsmetadata.c