DayZ Scripts: CollapsibleHeader Class Reference
CollapsibleHeader Class Reference
Private Member Functions
void CollapsibleHeader (LayoutHolder parent, string function_name)
override void SetLayoutName ()
void SetArrowButtonOpened (bool state)
bool IsHeaderVisible ()
void SetHeaderVisible (bool show)
Constructor & Destructor Documentation
CollapsibleHeader()
void CollapsibleHeader (LayoutHolder parent, string function_name) inline private
References Header::m_DefaultFontSize.
Member Function Documentation
IsHeaderVisible()
bool IsHeaderVisible () inline private
SetArrowButtonOpened()
void SetArrowButtonOpened (bool state) inline private
References Header::m_DownArrowButton, and Header::m_UpArrowButton.
Referenced by CollapsibleContainer::SetCollapsibleHeaderArrowState().
SetHeaderVisible()
void SetHeaderVisible (bool show) inline private
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), and AttachmentCategoriesContainer::OnHide().
SetLayoutName()
override void SetLayoutName () inline private
References WidgetLayoutName::CollapsibleHeader.
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/ContainedItems/Headers/CollapsibleHeader.c