DayZ Scripts: NotificationUI Class Reference
NotificationUI Class Reference
Private Member Functions
void NotificationUI ()
void ~NotificationUI ()
void AddNotification (NotificationRuntimeData data)
void RemoveNotification (NotificationRuntimeData data)
void AddVoiceNotification (string player, string name)
void RemoveVoiceNotification (string player)
void ClearVoiceNotifications ()
void UpdateTargetHeight ()
void UpdateOffset ()
void Update (float timeslice)
Private Attributes
protected ref Widget m_Root
protected ref Widget m_Spacer
protected ref Widget m_VoiceContent
protected ref Widget m_NotificationContent
protected ref map< NotificationRuntimeData, Widget > m_Notifications
protected ref map< string, Widget > m_VoiceNotifications
protected float m_Width
protected float m_CurrentHeight
protected float m_TargetHeight
protected float m_BackupPosX
protected float m_BackupPosY
protected ref map< string, Widget > m_WidgetTimers
protected bool m_OffsetEnabled
Static Private Attributes
static float m_VelArr [1]
Constructor & Destructor Documentation
NotificationUI()
void NotificationUI () inline private
References AddNotification(), WorkspaceWidget::CreateWidgets(), GetGame(), NotificationSystem::GetInstance(), CGame::GetWorkspace(), ScriptInvoker::Insert(), m_NotificationContent, m_Notifications, NotificationSystem::m_OnNotificationAdded, NotificationSystem::m_OnNotificationRemoved, m_Root, m_Spacer, m_VoiceContent, m_VoiceNotifications, m_WidgetTimers, and RemoveNotification().
~NotificationUI()
void ~NotificationUI () inline private
References AddNotification(), NotificationSystem::GetInstance(), NotificationSystem::m_OnNotificationAdded, NotificationSystem::m_OnNotificationRemoved, ScriptInvoker::Remove(), and RemoveNotification().
Member Function Documentation
AddNotification()
void AddNotification (NotificationRuntimeData data) inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_NotificationContent, m_Notifications, and UpdateTargetHeight().
Referenced by NotificationUI(), and ~NotificationUI().
AddVoiceNotification()
void AddVoiceNotification (string player, string name) inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_VoiceContent, m_VoiceNotifications, m_WidgetTimers, name, and UpdateTargetHeight().
ClearVoiceNotifications()
void ClearVoiceNotifications () inline private
References m_VoiceNotifications, and UpdateTargetHeight().
RemoveNotification()
void RemoveNotification (NotificationRuntimeData data) inline private
References m_Notifications, m_WidgetTimers, and UpdateTargetHeight().
Referenced by NotificationUI(), and ~NotificationUI().
RemoveVoiceNotification()
void RemoveVoiceNotification (string player) inline private
References m_VoiceNotifications, m_WidgetTimers, and UpdateTargetHeight().
Update()
void Update (float timeslice) inline private
References Math::Clamp(), m_CurrentHeight, m_Root, m_Spacer, m_TargetHeight, m_VelArr, m_WidgetTimers, m_Width, NotificationSystem::NOTIFICATION_FADE_TIME, Math::SmoothCD(), UpdateOffset(), UpdateTargetHeight(), and x.
UpdateOffset()
void UpdateOffset () inline private
References GetGame(), m_BackupPosX, m_BackupPosY, m_OffsetEnabled, m_Root, x, and y.
Referenced by Update(), and UpdateTargetHeight().
UpdateTargetHeight()
void UpdateTargetHeight () inline private
References m_CurrentHeight, m_NotificationContent, m_Root, m_Spacer, m_TargetHeight, m_VoiceContent, m_Width, UpdateOffset(), and x.
Referenced by AddNotification(), AddVoiceNotification(), ClearVoiceNotifications(), RemoveNotification(), RemoveVoiceNotification(), and Update().
Field Documentation
m_BackupPosX
protected float m_BackupPosX private
Referenced by UpdateOffset().
m_BackupPosY
protected float m_BackupPosY private
Referenced by UpdateOffset().
m_CurrentHeight
protected float m_CurrentHeight private
Referenced by Update(), and UpdateTargetHeight().
m_NotificationContent
protected ref Widget m_NotificationContent private
Referenced by AddNotification(), NotificationUI(), and UpdateTargetHeight().
m_Notifications
protected ref map<NotificationRuntimeData, Widget> m_Notifications private
Referenced by AddNotification(), NotificationUI(), and RemoveNotification().
m_OffsetEnabled
protected bool m_OffsetEnabled private
Referenced by UpdateOffset().
m_Root
protected ref Widget m_Root private
Referenced by NotificationUI(), Update(), UpdateOffset(), and UpdateTargetHeight().
m_Spacer
protected ref Widget m_Spacer private
Referenced by NotificationUI(), Update(), and UpdateTargetHeight().
m_TargetHeight
protected float m_TargetHeight private
Referenced by Update(), and UpdateTargetHeight().
m_VelArr
float m_VelArr[1] static private
Referenced by Update().
m_VoiceContent
protected ref Widget m_VoiceContent private
Referenced by AddVoiceNotification(), NotificationUI(), and UpdateTargetHeight().
m_VoiceNotifications
protected ref map<string, Widget> m_VoiceNotifications private
Referenced by AddVoiceNotification(), ClearVoiceNotifications(), NotificationUI(), and RemoveVoiceNotification().
m_WidgetTimers
protected ref map<string, Widget> m_WidgetTimers private
Referenced by AddVoiceNotification(), NotificationUI(), RemoveNotification(), RemoveVoiceNotification(), and Update().
m_Width
protected float m_Width private
Referenced by Update(), and UpdateTargetHeight().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Client/Notifications/NotificationUI.c