DayZ Scripts: LogTemplates Class Reference
LogTemplates Class Reference
Static Private Member Functions
static private void RegisterLogTamplate (LogTemplateID template_id, string author, string plugin, string label)
static void Init ()
static LogTemplate GetTemplate (LogTemplateID template_id)
Static Private Attributes
static private ref map< LogTemplateID, ref LogTemplate > m_LogTemplates
static LogTemplateID TEMPLATE_UNKNOWN = 0
static LogTemplateID TEMPLATE_JANOSIK = 1
static LogTemplateID TEMPLATE_PLAYER_WEIGHT = 2
static LogTemplateID TEMPLATE_BROADCAST = 3
Detailed Description
Definition at line 7 of file LogTemplates.c.
Member Function Documentation
GetTemplate()
static LogTemplate GetTemplate (LogTemplateID template_id) inline static private
Definition at line 52 of file LogTemplates.c.
References Debug::Log(), m_LogTemplates, and ToString().
Referenced by LogError(), LogInfo(), and LogWarning().
Init()
static void Init () inline static private
Definition at line 40 of file LogTemplates.c.
References RegisterLogTamplate(), TEMPLATE_BROADCAST, TEMPLATE_JANOSIK, TEMPLATE_PLAYER_WEIGHT, and TEMPLATE_UNKNOWN.
RegisterLogTamplate()
static private void RegisterLogTamplate (LogTemplateID template_id, string author, string plugin, string label) inline static private
Definition at line 11 of file LogTemplates.c.
References Debug::Log(), m_LogTemplates, and ToString().
Referenced by Init().
Field Documentation
m_LogTemplates
private ref map<LogTemplateID, ref LogTemplate> m_LogTemplates static private
Definition at line 9 of file LogTemplates.c.
Referenced by GetTemplate(), and RegisterLogTamplate().
TEMPLATE_BROADCAST
LogTemplateID TEMPLATE_BROADCAST = 3 static private
Definition at line 38 of file LogTemplates.c.
Referenced by Init().
TEMPLATE_JANOSIK
LogTemplateID TEMPLATE_JANOSIK = 1 static private
Definition at line 36 of file LogTemplates.c.
Referenced by Init().
TEMPLATE_PLAYER_WEIGHT
LogTemplateID TEMPLATE_PLAYER_WEIGHT = 2 static private
Definition at line 37 of file LogTemplates.c.
Referenced by Init().
TEMPLATE_UNKNOWN
LogTemplateID TEMPLATE_UNKNOWN = 0 static private
Definition at line 35 of file LogTemplates.c.
Referenced by Init().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/LogTemplates.c