DayZ Scripts: ActionVariantManager Class Reference
ActionVariantManager Class Reference
Private Member Functions
void ActionVariantManager (typename type)
ScriptInvoker GetOnUpdateInvoker ()
void Clear ()
void SetActionVariantCount (int count)
int GetActions (out array< ref ActionBase > variants_action)
int GetActionsCount ()
void UpdateVariants (Object item, Object target, int componet_index)
Private Attributes
protected ref array< ref ActionBase > m_VariantActions
protected m_type
protected ref ScriptInvoker e_OnUpdate
Detailed Description
Definition at line 1 of file ActionVariantsManager.c.
Constructor & Destructor Documentation
ActionVariantManager()
void ActionVariantManager (typename type) inline private
Definition at line 7 of file ActionVariantsManager.c.
References e_OnUpdate, m_type, and m_VariantActions.
Member Function Documentation
Clear()
void Clear () inline private
Definition at line 19 of file ActionVariantsManager.c.
References m_VariantActions.
Referenced by CraftingManager::OnUpdate(), ConstructionActionData::OnUpdateActions(), and ConstructionActionData::OnUpdateActionsNoTool().
GetActions()
int GetActions (out array< ref ActionBase > variants_action) inline private
Definition at line 40 of file ActionVariantsManager.c.
References m_VariantActions.
Referenced by GetVariants().
GetActionsCount()
int GetActionsCount () inline private
Definition at line 46 of file ActionVariantsManager.c.
References m_VariantActions.
Referenced by GetVariantsCount().
GetOnUpdateInvoker()
ScriptInvoker GetOnUpdateInvoker () inline private
Definition at line 14 of file ActionVariantsManager.c.
References e_OnUpdate.
Referenced by ConstructionActionData::ConstructionActionData(), and CraftingManager::CraftingManager().
SetActionVariantCount()
void SetActionVariantCount (int count) inline private
Definition at line 24 of file ActionVariantsManager.c.
References ActionBase(), ActionManagerBase(), m_type, and m_VariantActions.
Referenced by CraftingManager::OnUpdate(), ConstructionActionData::OnUpdateActions(), and ConstructionActionData::OnUpdateActionsNoTool().
UpdateVariants()
void UpdateVariants (Object item, Object target, int componet_index) inline private
Definition at line 51 of file ActionVariantsManager.c.
References e_OnUpdate, and ScriptInvoker::Invoke().
Referenced by UpdateVariants().
Field Documentation
e_OnUpdate
protected ref ScriptInvoker e_OnUpdate private
Definition at line 5 of file ActionVariantsManager.c.
Referenced by ActionVariantManager(), GetOnUpdateInvoker(), and UpdateVariants().
m_type
protected m_type private
Definition at line 4 of file ActionVariantsManager.c.
Referenced by ActionVariantManager(), and SetActionVariantCount().
m_VariantActions
protected ref array<ref ActionBase> m_VariantActions private
Definition at line 3 of file ActionVariantsManager.c.
Referenced by ActionVariantManager(), Clear(), GetActions(), GetActionsCount(), and SetActionVariantCount().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionVariantsManager.c