DayZ Scripts: CfgGameplayHandler Class Reference
CfgGameplayHandler Class Reference
Static Private Member Functions
static void RegisterItem (ITEM_DataBase item)
static private void ValidateItems ()
static private void InitData ()
static bool LoadData ()
static void OnLoaded ()
static void SyncDataSend (notnull Man player)
static void SyncDataSendEx (notnull PlayerIdentity identity)
static void OnRPC (Man player, ParamsReadContext ctx)
static bool GetDisablePersonalLight ()
static int GetLightingConfig ()
static TStringArray GetObjectSpawnersArr ()
static array< float > GetEnvironmentMinTemps ()
static array< float > GetEnvironmentMaxTemps ()
static array< float > GetWetnessWeightModifiers ()
static bool GetDisableBaseDamage ()
static bool GetDisableContainerDamage ()
static bool GetDisableRespawnDialog ()
static float GetSprintStaminaModifierErc ()
static float GetSprintStaminaModifierCro ()
static float GetSprintSwimmingStaminaModifier ()
static float GetSprintLadderStaminaModifier ()
static float GetStaminaWeightLimitThreshold ()
static float GetStaminaMax ()
static float GetStaminaKgToStaminaPercentPenalty ()
static float GetStaminaMinCap ()
static float GetMeleeStaminaModifier ()
static float GetObstacleTraversalStaminaModifier ()
static float GetHoldBreathStaminaModifier ()
static float GetMovementTimeToStrafeJog ()
static float GetMovementTimeToSprint ()
static float GetMovementTimeToStrafeSprint ()
static float GetMovementRotationSpeedJog ()
static float GetMovementRotationSpeedSprint ()
static bool GetDisable2dMap ()
static bool GetDisableIsCollidingBBoxCheck ()
static bool GetDisableIsCollidingPlayerCheck ()
static bool GetDisableIsClippingRoofCheck ()
static bool GetDisableIsBaseViableCheck ()
static bool GetDisableIsInTerrainCheck ()
static bool GetDisableIsUnderwaterCheck ()
static bool GetDisableHeightPlacementCheck ()
static bool GetDisableIsPlacementPermittedCheck ()
static bool GetDisableIsCollidingAngleCheck ()
static bool GetDisableIsCollidingGPlotCheck ()
static bool GetDisableIsCollidingCheck ()
static bool GetDisablePerformRoofCheck ()
static bool GetDisableDistanceCheck ()
static bool GetHitIndicationOverrideEnabled ()
static int GetHitIndicationMode ()
static int GetHitIndicationTypeID ()
static int GetHitIndicationIndicatorColor ()
static float GetHitIndicationMaxDuration ()
static float GetHitIndicationBreakPoint ()
static float GetHitIndicationScatter ()
static bool GetHitIndicationPPEEnabled ()
static bool GetUse3DMap ()
static float GetShockRefillSpeedConscious ()
static float GetShockRefillSpeedUnconscious ()
static bool GetAllowRefillSpeedModifier ()
static bool GetMapIgnoreMapOwnership ()
static bool GetMapIgnoreNavItemsOwnership ()
static bool GetMapDisplayPlayerPosition ()
static bool GetMapDisplayNavigationInfo ()
static float GetStaminaDepletionSpeed ()
static float GetHealthDepletionSpeed ()
static float GetShockDepletionSpeed ()
static bool GetAllowStaminaAffectInertia ()
Static Private Attributes
static private string m_Path = "$mission:cfgGameplay.json"
static private ref array< ref ITEM_DataBase > m_Items = new array<ref ITEM_DataBase>()
static ref CfgGameplayJson m_Data = new CfgGameplayJson
Detailed Description
Definition at line 1 of file CfgGameplayHandler.c.
Member Function Documentation
GetAllowRefillSpeedModifier()
static bool GetAllowRefillSpeedModifier () inline static private
Definition at line 370 of file CfgGameplayHandler.c.
References ITEM_ShockHandlingData::allowRefillSpeedModifier, m_Data, CfgGameplayJson::PlayerData, and ITEM_PlayerData::ShockHandlingData.
Referenced by ShockMdfr::OnTick().
GetAllowStaminaAffectInertia()
static bool GetAllowStaminaAffectInertia () inline static private
Definition at line 411 of file CfgGameplayHandler.c.
References ITEM_MovementData::allowStaminaAffectInertia, m_Data, ITEM_PlayerData::MovementData, and CfgGameplayJson::PlayerData.
Referenced by ManBase::OnCommandHandlerTick().
GetDisable2dMap()
static bool GetDisable2dMap () inline static private
Definition at line 245 of file CfgGameplayHandler.c.
References ITEM_PlayerData::disable2dMap, m_Data, and CfgGameplayJson::PlayerData.
GetDisableBaseDamage()
static bool GetDisableBaseDamage () inline static private
Definition at line 150 of file CfgGameplayHandler.c.
References CfgGameplayJson::GeneralData, and m_Data.
GetDisableContainerDamage()
static bool GetDisableContainerDamage () inline static private
Definition at line 156 of file CfgGameplayHandler.c.
References CfgGameplayJson::GeneralData, and m_Data.
GetDisableDistanceCheck()
static bool GetDisableDistanceCheck () inline static private
Definition at line 310 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_BaseBuildingData::ConstructionData, ITEM_ConstructionData::disableDistanceCheck, and m_Data.
GetDisableHeightPlacementCheck()
static bool GetDisableHeightPlacementCheck () inline static private
Definition at line 280 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableHeightPlacementCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::HeightPlacementCheck().
GetDisableIsBaseViableCheck()
static bool GetDisableIsBaseViableCheck () inline static private
Definition at line 265 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsBaseViableCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsBaseViable().
GetDisableIsClippingRoofCheck()
static bool GetDisableIsClippingRoofCheck () inline static private
Definition at line 260 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsClippingRoofCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsClippingRoof().
GetDisableIsCollidingAngleCheck()
static bool GetDisableIsCollidingAngleCheck () inline static private
Definition at line 290 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsCollidingAngleCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsCollidingAngle().
GetDisableIsCollidingBBoxCheck()
static bool GetDisableIsCollidingBBoxCheck () inline static private
Definition at line 250 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsCollidingBBoxCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::GetProjectionEntityPosition(), and Hologram::IsCollidingBBox().
GetDisableIsCollidingCheck()
static bool GetDisableIsCollidingCheck () inline static private
Definition at line 300 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_BaseBuildingData::ConstructionData, ITEM_ConstructionData::disableIsCollidingCheck, and m_Data.
Referenced by IsColliding(), and IsCollidingEx().
GetDisableIsCollidingGPlotCheck()
static bool GetDisableIsCollidingGPlotCheck () inline static private
Definition at line 295 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsCollidingGPlotCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsCollidingGPlot().
GetDisableIsCollidingPlayerCheck()
static bool GetDisableIsCollidingPlayerCheck () inline static private
Definition at line 255 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsCollidingPlayerCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsCollidingPlayer().
GetDisableIsInTerrainCheck()
static bool GetDisableIsInTerrainCheck () inline static private
Definition at line 270 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsInTerrainCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsInTerrain().
GetDisableIsPlacementPermittedCheck()
static bool GetDisableIsPlacementPermittedCheck () inline static private
Definition at line 285 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsPlacementPermittedCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsPlacementPermitted().
GetDisableIsUnderwaterCheck()
static bool GetDisableIsUnderwaterCheck () inline static private
Definition at line 275 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsUnderwaterCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsUnderwater().
GetDisablePerformRoofCheck()
static bool GetDisablePerformRoofCheck () inline static private
Definition at line 305 of file CfgGameplayHandler.c.
References CfgGameplayJson::BaseBuildingData, ITEM_BaseBuildingData::ConstructionData, ITEM_ConstructionData::disablePerformRoofCheck, and m_Data.
Referenced by BaseBuildingBase::PerformRoofCheckForBase().
GetDisablePersonalLight()
static bool GetDisablePersonalLight () inline static private
! ===================================================================================== !! the naming convention for static functions in this file is Get+MemberVariableName !! ! =====================================================================================
Definition at line 117 of file CfgGameplayHandler.c.
References ITEM_PlayerData::disablePersonalLight, m_Data, and CfgGameplayJson::PlayerData.
Referenced by PlayerBase::OnGameplayDataHandlerSync().
GetDisableRespawnDialog()
static bool GetDisableRespawnDialog () inline static private
Definition at line 161 of file CfgGameplayHandler.c.
References CfgGameplayJson::GeneralData, and m_Data.
Referenced by MissionBase::OnGameplayDataHandlerLoad(), and ManBase::OnGameplayDataHandlerSync().
GetEnvironmentMaxTemps()
static array< float > GetEnvironmentMaxTemps () inline static private
Definition at line 139 of file CfgGameplayHandler.c.
References m_Data, and CfgGameplayJson::WorldsData.
Referenced by WorldData::Init().
GetEnvironmentMinTemps()
static array< float > GetEnvironmentMinTemps () inline static private
Definition at line 134 of file CfgGameplayHandler.c.
References m_Data, and CfgGameplayJson::WorldsData.
Referenced by WorldData::Init().
GetHealthDepletionSpeed()
static float GetHealthDepletionSpeed () inline static private
Definition at line 401 of file CfgGameplayHandler.c.
References ITEM_PlayerData::DrowningData, m_Data, and CfgGameplayJson::PlayerData.
Referenced by DrowningMdfr::OnTick().
GetHitIndicationBreakPoint()
static float GetHitIndicationBreakPoint () inline static private
Definition at line 340 of file CfgGameplayHandler.c.
References ITEM_HitIndicationData::hitDirectionBreakPointRelative, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationIndicatorColor()
static int GetHitIndicationIndicatorColor () inline static private
Definition at line 330 of file CfgGameplayHandler.c.
References string::HexToInt(), ITEM_HitIndicationData::hitDirectionIndicatorColorStr, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationMaxDuration()
static float GetHitIndicationMaxDuration () inline static private
Definition at line 335 of file CfgGameplayHandler.c.
References ITEM_HitIndicationData::hitDirectionMaxDuration, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationMode()
static int GetHitIndicationMode () inline static private
Definition at line 320 of file CfgGameplayHandler.c.
References ITEM_HitIndicationData::hitDirectionBehaviour, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationOverrideEnabled()
static bool GetHitIndicationOverrideEnabled () inline static private
Definition at line 315 of file CfgGameplayHandler.c.
References ITEM_HitIndicationData::hitDirectionOverrideEnabled, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationPPEEnabled()
static bool GetHitIndicationPPEEnabled () inline static private
Definition at line 350 of file CfgGameplayHandler.c.
References ITEM_UIData::HitIndicationData, ITEM_HitIndicationData::hitIndicationPostProcessEnabled, m_Data, and CfgGameplayJson::UIData.
Referenced by ManBase::OnGameplayDataHandlerSync().
GetHitIndicationScatter()
static float GetHitIndicationScatter () inline static private
Definition at line 345 of file CfgGameplayHandler.c.
References ITEM_HitIndicationData::hitDirectionScatter, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationTypeID()
static int GetHitIndicationTypeID () inline static private
Definition at line 325 of file CfgGameplayHandler.c.
References ITEM_HitIndicationData::hitDirectionStyle, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHoldBreathStaminaModifier()
static float GetHoldBreathStaminaModifier () inline static private
Definition at line 215 of file CfgGameplayHandler.c.
References ITEM_StaminaData::holdBreathStaminaModifier, m_Data, CfgGameplayJson::PlayerData, and ITEM_PlayerData::StaminaData.
Referenced by RegisterStaminaModifiers().
GetLightingConfig()
static int GetLightingConfig () inline static private
Definition at line 124 of file CfgGameplayHandler.c.
References m_Data, and CfgGameplayJson::WorldsData.
Referenced by ManBase::UpdateLighting().
GetMapDisplayNavigationInfo()
static bool GetMapDisplayNavigationInfo () inline static private
Definition at line 391 of file CfgGameplayHandler.c.
References ITEM_MapData::displayNavInfo, m_Data, and CfgGameplayJson::MapData.
Referenced by UIScriptedMenu::Init().
GetMapDisplayPlayerPosition()
static bool GetMapDisplayPlayerPosition () inline static private
Definition at line 386 of file CfgGameplayHandler.c.
References ITEM_MapData::displayPlayerPosition, m_Data, and CfgGameplayJson::MapData.
Referenced by UIScriptedMenu::Init().
GetMapIgnoreMapOwnership()
static bool GetMapIgnoreMapOwnership () inline static private
Definition at line 376 of file CfgGameplayHandler.c.
References ITEM_MapData::ignoreMapOwnership, m_Data, and CfgGameplayJson::MapData.
Referenced by UIScriptedMenu::CloseMapMenu(), MissionBase::OnUpdate(), and UIScriptedMenu::Update().
GetMapIgnoreNavItemsOwnership()
static bool GetMapIgnoreNavItemsOwnership () inline static private
Definition at line 381 of file CfgGameplayHandler.c.
References ITEM_MapData::ignoreNavItemsOwnership, m_Data, and CfgGameplayJson::MapData.
Referenced by UIScriptedMenu::Init(), and UIScriptedMenu::Update().
GetMeleeStaminaModifier()
static float GetMeleeStaminaModifier () inline static private
Definition at line 205 of file CfgGameplayHandler.c.
References m_Data, ITEM_StaminaData::meleeStaminaModifier, CfgGameplayJson::PlayerData, and ITEM_PlayerData::StaminaData.
Referenced by RegisterStaminaModifiers().
GetMovementRotationSpeedJog()
static float GetMovementRotationSpeedJog () inline static private
Definition at line 235 of file CfgGameplayHandler.c.
References m_Data, Math::Max(), ITEM_PlayerData::MovementData, CfgGameplayJson::PlayerData, and ITEM_MovementData::rotationSpeedJog.
GetMovementRotationSpeedSprint()
static float GetMovementRotationSpeedSprint () inline static private
Definition at line 240 of file CfgGameplayHandler.c.
References m_Data, Math::Max(), ITEM_PlayerData::MovementData, CfgGameplayJson::PlayerData, and ITEM_MovementData::rotationSpeedSprint.
GetMovementTimeToSprint()
static float GetMovementTimeToSprint () inline static private
Definition at line 225 of file CfgGameplayHandler.c.
References m_Data, Math::Max(), ITEM_PlayerData::MovementData, CfgGameplayJson::PlayerData, and ITEM_MovementData::timeToSprint.
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeInitMovement().
GetMovementTimeToStrafeJog()
static float GetMovementTimeToStrafeJog () inline static private
Definition at line 220 of file CfgGameplayHandler.c.
References m_Data, Math::Max(), ITEM_PlayerData::MovementData, CfgGameplayJson::PlayerData, and ITEM_MovementData::timeToStrafeJog.
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeInitMovement().
GetMovementTimeToStrafeSprint()
static float GetMovementTimeToStrafeSprint () inline static private
Definition at line 230 of file CfgGameplayHandler.c.
References m_Data, Math::Max(), ITEM_PlayerData::MovementData, CfgGameplayJson::PlayerData, and ITEM_MovementData::timeToStrafeSprint.
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeInitMovement().
GetObjectSpawnersArr()
static TStringArray GetObjectSpawnersArr () inline static private
Definition at line 129 of file CfgGameplayHandler.c.
References m_Data, and CfgGameplayJson::WorldsData.
Referenced by ObjectSpawnerHandler::SpawnObjects().
GetObstacleTraversalStaminaModifier()
static float GetObstacleTraversalStaminaModifier () inline static private
Definition at line 210 of file CfgGameplayHandler.c.
References m_Data, ITEM_StaminaData::obstacleTraversalStaminaModifier, CfgGameplayJson::PlayerData, and ITEM_PlayerData::StaminaData.
Referenced by RegisterStaminaModifiers().
GetShockDepletionSpeed()
static float GetShockDepletionSpeed () inline static private
Definition at line 406 of file CfgGameplayHandler.c.
References ITEM_PlayerData::DrowningData, m_Data, and CfgGameplayJson::PlayerData.
Referenced by DrowningMdfr::OnTick().
GetShockRefillSpeedConscious()
static float GetShockRefillSpeedConscious () inline static private
Definition at line 360 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::ShockHandlingData, and ITEM_ShockHandlingData::shockRefillSpeedConscious.
Referenced by ShockMdfr::GetRefillSpeed().
GetShockRefillSpeedUnconscious()
static float GetShockRefillSpeedUnconscious () inline static private
Definition at line 365 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::ShockHandlingData, and ITEM_ShockHandlingData::shockRefillSpeedUnconscious.
Referenced by ShockMdfr::GetRefillSpeed().
GetSprintLadderStaminaModifier()
static float GetSprintLadderStaminaModifier () inline static private
Definition at line 180 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::PlayerData, ITEM_StaminaData::sprintLadderStaminaModifier, and ITEM_PlayerData::StaminaData.
Referenced by StaminaProcessor_Ladder().
GetSprintStaminaModifierCro()
static float GetSprintStaminaModifierCro () inline static private
Definition at line 171 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::PlayerData, ITEM_StaminaData::sprintStaminaModifierCro, and ITEM_PlayerData::StaminaData.
Referenced by StaminaProcessor_Move().
GetSprintStaminaModifierErc()
static float GetSprintStaminaModifierErc () inline static private
Definition at line 166 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::PlayerData, ITEM_StaminaData::sprintStaminaModifierErc, and ITEM_PlayerData::StaminaData.
Referenced by StaminaProcessor_Move().
GetSprintSwimmingStaminaModifier()
static float GetSprintSwimmingStaminaModifier () inline static private
Definition at line 176 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::PlayerData, ITEM_StaminaData::sprintSwimmingStaminaModifier, and ITEM_PlayerData::StaminaData.
Referenced by StaminaProcessor_Swimming().
GetStaminaDepletionSpeed()
static float GetStaminaDepletionSpeed () inline static private
Definition at line 396 of file CfgGameplayHandler.c.
References ITEM_PlayerData::DrowningData, m_Data, and CfgGameplayJson::PlayerData.
GetStaminaKgToStaminaPercentPenalty()
static float GetStaminaKgToStaminaPercentPenalty () inline static private
Definition at line 195 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::StaminaData, and ITEM_StaminaData::staminaKgToStaminaPercentPenalty.
Referenced by Update().
GetStaminaMax()
static float GetStaminaMax () inline static private
Definition at line 190 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::StaminaData, and ITEM_StaminaData::staminaMax.
Referenced by DepleteStamina(), GetStaminaMax(), PlayerStatsPCO_Base::Init(), RegisterStaminaModifiers(), SetStamina(), Hud::SetStamina(), StaminaHandler(), and Update().
GetStaminaMinCap()
static float GetStaminaMinCap () inline static private
Definition at line 200 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::StaminaData, and ITEM_StaminaData::staminaMinCap.
Referenced by RegisterStaminaConsumers(), and Update().
GetStaminaWeightLimitThreshold()
static float GetStaminaWeightLimitThreshold () inline static private
Definition at line 185 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::StaminaData, and ITEM_StaminaData::staminaWeightLimitThreshold.
Referenced by Update().
GetUse3DMap()
static bool GetUse3DMap () inline static private
Definition at line 355 of file CfgGameplayHandler.c.
References m_Data, CfgGameplayJson::UIData, and ITEM_UIData::use3DMap.
Referenced by UIScriptedMenu::CloseMapMenu(), ManBase::CommandHandler(), MissionBase::HandleMapToggleByKeyboardShortcut(), MissionBase::OnUpdate(), ActionUnfoldMapCB::PerformMapChange(), and ActionUnfoldMapCB::~ActionUnfoldMapCB().
GetWetnessWeightModifiers()
static array< float > GetWetnessWeightModifiers () inline static private
Definition at line 143 of file CfgGameplayHandler.c.
References m_Data, and CfgGameplayJson::WorldsData.
InitData()
static private void InitData () inline static private
Definition at line 29 of file CfgGameplayHandler.c.
References m_Items.
Referenced by LoadData().
LoadData()
static bool LoadData () inline static private
Definition at line 44 of file CfgGameplayHandler.c.
References FileExist(), string::Format(), GetGame(), CGame::GetWorldName(), InitData(), CfgGameplayJson::InitServer(), m_Data, m_Path, OnLoaded(), and ValidateItems().
Referenced by MissionBase::OnInit().
OnLoaded()
static void OnLoaded () inline static private
Definition at line 69 of file CfgGameplayHandler.c.
References GetGame(), CGame::GetMission(), and Mission::OnGameplayDataHandlerLoad().
Referenced by LoadData().
OnRPC()
static void OnRPC (Man player, ParamsReadContext ctx) inline static private
Definition at line 90 of file CfgGameplayHandler.c.
References ErrorEx, m_Data, and Serializer::Read().
Referenced by CGame::OnRPC().
RegisterItem()
static void RegisterItem (ITEM_DataBase item) inline static private
Definition at line 9 of file CfgGameplayHandler.c.
References m_Items.
Referenced by ITEM_DataBase::ITEM_DataBase().
SyncDataSend()
static void SyncDataSend (notnull Man player) inline static private
Definition at line 76 of file CfgGameplayHandler.c.
References GetGame(), m_Data, and CGame::RPCSingleParam().
SyncDataSendEx()
static void SyncDataSendEx (notnull PlayerIdentity identity) inline static private
Definition at line 82 of file CfgGameplayHandler.c.
References GetGame(), m_Data, and CGame::RPCSingleParam().
Referenced by MissionBase::OnEvent().
ValidateItems()
static private void ValidateItems () inline static private
Definition at line 14 of file CfgGameplayHandler.c.
References m_Items, PrintToRPT(), and string::Replace().
Referenced by LoadData().
Field Documentation
m_Data
ref CfgGameplayJson m_Data = new CfgGameplayJson static private
Definition at line 6 of file CfgGameplayHandler.c.
Referenced by GetAllowRefillSpeedModifier(), GetAllowStaminaAffectInertia(), GetDisable2dMap(), GetDisableBaseDamage(), GetDisableContainerDamage(), GetDisableDistanceCheck(), GetDisableHeightPlacementCheck(), GetDisableIsBaseViableCheck(), GetDisableIsClippingRoofCheck(), GetDisableIsCollidingAngleCheck(), GetDisableIsCollidingBBoxCheck(), GetDisableIsCollidingCheck(), GetDisableIsCollidingGPlotCheck(), GetDisableIsCollidingPlayerCheck(), GetDisableIsInTerrainCheck(), GetDisableIsPlacementPermittedCheck(), GetDisableIsUnderwaterCheck(), GetDisablePerformRoofCheck(), GetDisablePersonalLight(), GetDisableRespawnDialog(), GetEnvironmentMaxTemps(), GetEnvironmentMinTemps(), GetHealthDepletionSpeed(), GetHitIndicationBreakPoint(), GetHitIndicationIndicatorColor(), GetHitIndicationMaxDuration(), GetHitIndicationMode(), GetHitIndicationOverrideEnabled(), GetHitIndicationPPEEnabled(), GetHitIndicationScatter(), GetHitIndicationTypeID(), GetHoldBreathStaminaModifier(), GetLightingConfig(), GetMapDisplayNavigationInfo(), GetMapDisplayPlayerPosition(), GetMapIgnoreMapOwnership(), GetMapIgnoreNavItemsOwnership(), GetMeleeStaminaModifier(), GetMovementRotationSpeedJog(), GetMovementRotationSpeedSprint(), GetMovementTimeToSprint(), GetMovementTimeToStrafeJog(), GetMovementTimeToStrafeSprint(), GetObjectSpawnersArr(), GetObstacleTraversalStaminaModifier(), GetShockDepletionSpeed(), GetShockRefillSpeedConscious(), GetShockRefillSpeedUnconscious(), GetSprintLadderStaminaModifier(), GetSprintStaminaModifierCro(), GetSprintStaminaModifierErc(), GetSprintSwimmingStaminaModifier(), GetStaminaDepletionSpeed(), GetStaminaKgToStaminaPercentPenalty(), GetStaminaMax(), GetStaminaMinCap(), GetStaminaWeightLimitThreshold(), GetUse3DMap(), GetWetnessWeightModifiers(), LoadData(), OnRPC(), SyncDataSend(), and SyncDataSendEx().
m_Items
private ref array<ref ITEM_DataBase> m_Items = new array<ref ITEM_DataBase>() static private
Definition at line 4 of file CfgGameplayHandler.c.
Referenced by InitData(), RegisterItem(), and ValidateItems().
m_Path
private string m_Path = "$mission:cfgGameplay.json" static private
Definition at line 3 of file CfgGameplayHandler.c.
Referenced by LoadData().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/CfgGameplayHandler.c