DayZ Scripts: Selection Class Reference
Selection Class Reference
Selection class.
Private Member Functions
private void Selection ()
private void ~Selection ()
proto native owned string GetName ()
proto native int GetVertexCount ()
proto native int GetLODVertexIndex (int sel_vertex_index)
vector GetVertexPosition (LOD lod, int index)
Detailed Description
Selection class.
Constructor & Destructor Documentation
Selection()
private void Selection () inline private
~Selection()
private void ~Selection () inline private
Member Function Documentation
GetLODVertexIndex()
proto native int GetLODVertexIndex (int sel_vertex_index) private
Referenced by GetVertexPosition().
GetName()
proto native owned string GetName () private
GetVertexCount()
proto native int GetVertexCount () private
GetVertexPosition()
vector GetVertexPosition (LOD lod, int index) inline private
References Error(), GetLODVertexIndex(), LOD::GetVertexPosition(), and vector::Zero.
The documentation for this class was generated from the following file:
3_Game/gameplay.c