DayZ Scripts: P:/scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/StaminaEvents.c File Reference
StaminaEvents.c File Reference
Data Structures
class PlayerSoundEventBase
class StaminaSoundEventBase
class StaminaLowFilterBase
Functions
class StaminaSoundEventBase extends PlayerSoundEventBase StaminaDownLight ()
void StaminaSoundEventBase ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override void OnPlay (PlayerBase player)
class StaminaDownHeavy extends StaminaSoundEventBase StaminaUpHeavy ()
void StaminaDownHeavy ()
class StaminaUpLight extends StaminaSoundEventBase StaminaUpEnd ()
void StaminaUpLight ()
class StaminaNormalDummy extends StaminaSoundEventBase StaminaLowFilterBase ()
void StaminaNormalDummy ()
class StaminaLowFilterUpper extends StaminaLowFilterBase StaminaLowFilterMid ()
void StaminaLowFilterUpper ()
Variables
const int MAX_VOLUME = 4
Function Documentation
HasPriorityOverCurrent()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Definition at line 58 of file StaminaEvents.c.
OnPlay()
override void OnPlay (PlayerBase player)
!! beware of the ifdef above , most likely you want to put your code above it, otherwise it might not get executed !!!
Definition at line 63 of file StaminaEvents.c.
StaminaDownHeavy()
void StaminaDownHeavy ()
Definition at line 69 of file StaminaEvents.c.
References m_ID, and m_SoundVoiceAnimEventClassID.
Referenced by PlayerSoundEventHandler().
StaminaDownLight()
class StaminaSoundEventBase extends PlayerSoundEventBase StaminaDownLight ()
Definition at line 1 of file StaminaEvents.c.
Referenced by PlayerSoundEventHandler().
StaminaLowFilterBase()
class StaminaNormalDummy extends StaminaSoundEventBase StaminaLowFilterBase ()
Definition at line 98 of file StaminaEvents.c.
StaminaLowFilterMid()
class StaminaLowFilterUpper extends StaminaLowFilterBase StaminaLowFilterMid ()
Definition at line 120 of file StaminaEvents.c.
Referenced by PlayerSoundEventHandler().
StaminaLowFilterUpper()
void StaminaLowFilterUpper ()
Definition at line 132 of file StaminaEvents.c.
References m_ID, and m_SoundVoiceAnimEventClassID.
Referenced by PlayerSoundEventHandler().
StaminaNormalDummy()
void StaminaNormalDummy ()
Definition at line 115 of file StaminaEvents.c.
References m_ProcessPlaybackEvent.
Referenced by PlayerSoundEventHandler().
StaminaSoundEventBase()
void StaminaSoundEventBase ()
Definition at line 52 of file StaminaEvents.c.
StaminaUpEnd()
class StaminaUpLight extends StaminaSoundEventBase StaminaUpEnd ()
Definition at line 75 of file StaminaEvents.c.
Referenced by PlayerSoundEventHandler().
StaminaUpHeavy()
class StaminaDownHeavy extends StaminaSoundEventBase StaminaUpHeavy ()
Definition at line 57 of file StaminaEvents.c.
Referenced by PlayerSoundEventHandler().
StaminaUpLight()
void StaminaUpLight ()
Definition at line 87 of file StaminaEvents.c.
References m_ID, and m_SoundVoiceAnimEventClassID.
Referenced by PlayerSoundEventHandler().
Variable Documentation
MAX_VOLUME
const int MAX_VOLUME = 4
Definition at line 51 of file StaminaEvents.c.
Referenced by PlayerSoundEventBase::OnPlay().