DayZ Scripts: DayZProfilesOptions Class Reference
DayZProfilesOptions Class Reference
Private Member Functions
void DayZProfilesOptions ()
void RegisterProfileOption (EDayZProfilesOptions option, string profileOptionName, bool def=true)
void RegisterProfileOptionBool (EDayZProfilesOptions option, string profileOptionName, bool defaultValue=true)
void RegisterProfileOptionInt (EDayZProfilesOptions option, string profileOptionName, int defaultValue=0)
void RegisterProfileOptionFloat (EDayZProfilesOptions option, string profileOptionName, float defaultValue=0.0)
void ResetOptionsBool ()
void ResetOptions ()
void ResetOptionsInt ()
void ResetOptionsFloat ()
void SetProfileOption (EDayZProfilesOptions option, bool value)
void SetProfileOptionBool (EDayZProfilesOptions option, bool value)
void SetProfileOptionInt (EDayZProfilesOptions option, int value)
void SetProfileOptionFloat (EDayZProfilesOptions option, float value)
bool GetProfileOption (EDayZProfilesOptions option)
bool GetProfileOptionBool (EDayZProfilesOptions option)
int GetProfileOptionInt (EDayZProfilesOptions option)
float GetProfileOptionFloat (EDayZProfilesOptions option)
bool GetProfileOptionDefault (EDayZProfilesOptions option)
bool GetProfileOptionDefaultBool (EDayZProfilesOptions option)
int GetProfileOptionDefaultInt (EDayZProfilesOptions option)
float GetProfileOptionDefaultFloat (EDayZProfilesOptions option)
map< EDayZProfilesOptions, ref DayZProfilesOptionBool > GetProfileOptionMap ()
Private Attributes
private ref map< EDayZProfilesOptions, ref DayZProfilesOptionBool > m_DayZProfilesOptionsBool
private ref map< EDayZProfilesOptions, ref DayZProfilesOptionInt > m_DayZProfilesOptionsInt
private ref map< EDayZProfilesOptions, ref DayZProfilesOptionFloat > m_DayZProfilesOptionsFloat
private ref map< EDayZProfilesOptions, ref DayZProfilesOption > m_DayZProfilesOptions
private DayZGame m_Game
Static Private Attributes
static ref ScriptInvoker m_OnIntOptionChanged = new ScriptInvoker()
static ref ScriptInvoker m_OnBoolOptionChanged = new ScriptInvoker()
static ref ScriptInvoker m_OnFloatOptionChanged = new ScriptInvoker()
Constructor & Destructor Documentation
DayZProfilesOptions()
void DayZProfilesOptions () inline private
References m_DayZProfilesOptionsBool, m_DayZProfilesOptionsFloat, and m_DayZProfilesOptionsInt.
Member Function Documentation
GetProfileOption()
bool GetProfileOption (EDayZProfilesOptions option) inline private
References m_DayZProfilesOptionsBool.
Referenced by GetProfileOptionBool().
GetProfileOptionBool()
bool GetProfileOptionBool (EDayZProfilesOptions option) inline private
References GetProfileOption().
GetProfileOptionDefault()
bool GetProfileOptionDefault (EDayZProfilesOptions option) inline private
References GetProfileOptionDefaultBool().
GetProfileOptionDefaultBool()
bool GetProfileOptionDefaultBool (EDayZProfilesOptions option) inline private
References ErrorEx, and m_DayZProfilesOptionsBool.
Referenced by GetProfileOptionDefault().
GetProfileOptionDefaultFloat()
float GetProfileOptionDefaultFloat (EDayZProfilesOptions option) inline private
References ErrorEx, and m_DayZProfilesOptionsFloat.
GetProfileOptionDefaultInt()
int GetProfileOptionDefaultInt (EDayZProfilesOptions option) inline private
References ErrorEx, and m_DayZProfilesOptionsInt.
GetProfileOptionFloat()
float GetProfileOptionFloat (EDayZProfilesOptions option) inline private
References m_DayZProfilesOptionsFloat.
GetProfileOptionInt()
int GetProfileOptionInt (EDayZProfilesOptions option) inline private
References m_DayZProfilesOptionsInt.
GetProfileOptionMap()
map< EDayZProfilesOptions, ref DayZProfilesOptionBool > GetProfileOptionMap () inline private
References m_DayZProfilesOptions.
RegisterProfileOption()
void RegisterProfileOption (EDayZProfilesOptions option, string profileOptionName, bool def = true) inline private
init of DayZProfilesOption - profileOptionName, value from Profiles files, or use default value
References GetProfileValueBool(), m_DayZProfilesOptionsBool, and SetProfileOptionBool().
Referenced by RegisterProfileOptionBool().
RegisterProfileOptionBool()
void RegisterProfileOptionBool (EDayZProfilesOptions option, string profileOptionName, bool defaultValue = true) inline private
References RegisterProfileOption().
RegisterProfileOptionFloat()
void RegisterProfileOptionFloat (EDayZProfilesOptions option, string profileOptionName, float defaultValue = 0.0) inline private
init of DayZProfilesOption - profileOptionName, value from Profiles files, or use default value
References GetGame(), CGame::GetProfileString(), m_DayZProfilesOptionsFloat, SetProfileOptionFloat(), and string::ToFloat().
RegisterProfileOptionInt()
void RegisterProfileOptionInt (EDayZProfilesOptions option, string profileOptionName, int defaultValue = 0) inline private
init of DayZProfilesOption - profileOptionName, value from Profiles files, or use default value
References GetGame(), CGame::GetProfileString(), m_DayZProfilesOptionsInt, SetProfileOptionInt(), and string::ToInt().
ResetOptions()
void ResetOptions () inline private
References ResetOptionsBool().
ResetOptionsBool()
void ResetOptionsBool () inline private
References GetProfileValueBool(), m_DayZProfilesOptionsBool, and SetProfileOptionBool().
Referenced by ResetOptions().
ResetOptionsFloat()
void ResetOptionsFloat () inline private
References GetGame(), CGame::GetProfileString(), m_DayZProfilesOptionsFloat, SetProfileOptionFloat(), and string::ToFloat().
ResetOptionsInt()
void ResetOptionsInt () inline private
References GetGame(), CGame::GetProfileString(), m_DayZProfilesOptionsInt, SetProfileOptionInt(), and string::ToInt().
SetProfileOption()
void SetProfileOption (EDayZProfilesOptions option, bool value) inline private
References GetGame(), ScriptInvoker::Invoke(), m_DayZProfilesOptionsBool, m_OnBoolOptionChanged, CGame::SaveProfile(), CGame::SetProfileString(), and bool::ToString().
Referenced by SetProfileOptionBool().
SetProfileOptionBool()
void SetProfileOptionBool (EDayZProfilesOptions option, bool value) inline private
References SetProfileOption().
Referenced by RegisterProfileOption(), and ResetOptionsBool().
SetProfileOptionFloat()
void SetProfileOptionFloat (EDayZProfilesOptions option, float value) inline private
References GetGame(), ScriptInvoker::Invoke(), m_DayZProfilesOptionsFloat, m_OnFloatOptionChanged, CGame::SaveProfile(), CGame::SetProfileString(), and float::ToString().
Referenced by RegisterProfileOptionFloat(), and ResetOptionsFloat().
SetProfileOptionInt()
void SetProfileOptionInt (EDayZProfilesOptions option, int value) inline private
References GetGame(), ScriptInvoker::Invoke(), m_DayZProfilesOptionsInt, m_OnIntOptionChanged, CGame::SaveProfile(), and CGame::SetProfileString().
Referenced by RegisterProfileOptionInt(), and ResetOptionsInt().
Field Documentation
m_DayZProfilesOptions
private ref map<EDayZProfilesOptions, ref DayZProfilesOption> m_DayZProfilesOptions private
DEPRECATED
Referenced by GetProfileOptionMap().
m_DayZProfilesOptionsBool
private ref map<EDayZProfilesOptions, ref DayZProfilesOptionBool> m_DayZProfilesOptionsBool private
Referenced by DayZProfilesOptions(), GetProfileOption(), GetProfileOptionDefaultBool(), RegisterProfileOption(), ResetOptionsBool(), and SetProfileOption().
m_DayZProfilesOptionsFloat
private ref map<EDayZProfilesOptions, ref DayZProfilesOptionFloat> m_DayZProfilesOptionsFloat private
Referenced by DayZProfilesOptions(), GetProfileOptionDefaultFloat(), GetProfileOptionFloat(), RegisterProfileOptionFloat(), ResetOptionsFloat(), and SetProfileOptionFloat().
m_DayZProfilesOptionsInt
private ref map<EDayZProfilesOptions, ref DayZProfilesOptionInt> m_DayZProfilesOptionsInt private
Referenced by DayZProfilesOptions(), GetProfileOptionDefaultInt(), GetProfileOptionInt(), RegisterProfileOptionInt(), ResetOptionsInt(), and SetProfileOptionInt().
m_Game
private DayZGame m_Game private
m_OnBoolOptionChanged
ref ScriptInvoker m_OnBoolOptionChanged = new ScriptInvoker() static private
Referenced by SetProfileOption().
m_OnFloatOptionChanged
ref ScriptInvoker m_OnFloatOptionChanged = new ScriptInvoker() static private
Referenced by SetProfileOptionFloat().
m_OnIntOptionChanged
ref ScriptInvoker m_OnIntOptionChanged = new ScriptInvoker() static private
Referenced by DynamicMusicPlayer::DynamicMusicPlayer(), and SetProfileOptionInt().
The documentation for this class was generated from the following file:
P:/scripts/3_game/dayzgame.c