DayZ Scripts: ActionFillBottleBase Class Reference
ActionFillBottleBase Class Reference
Private Member Functions
void ActionFillBottleBase ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
int GetLiquidType (PlayerBase player, ActionTarget target, ItemBase item)
void SetupStance (PlayerBase player)
Private Attributes
private const float WATER_DEPTH = 0.5
private const string ALLOWED_WATER_SURFACES = string.Format("%1|%2", UAWaterType.FRESH, UAWaterType.STILL)
Detailed Description
Definition at line 22 of file ActionFillBottleBase.c.
Constructor & Destructor Documentation
ActionFillBottleBase()
void ActionFillBottleBase () inline private
Definition at line 27 of file ActionFillBottleBase.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 43 of file ActionFillBottleBase.c.
References ALLOWED_WATER_SURFACES, CCTWaterSurface::Can(), UAMaxDistances::DEFAULT, vector::DistanceSq(), and GetLiquidType().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
Definition at line 67 of file ActionFillBottleBase.c.
References ActionData::m_MainItem.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 37 of file ActionFillBottleBase.c.
References m_ConditionItem, and m_ConditionTarget.
GetLiquidType()
int GetLiquidType (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 87 of file ActionFillBottleBase.c.
References Liquid::CanFillContainer(), LIQUID_GASOLINE, and LIQUID_WATER.
Referenced by ActionFillBottleBaseCB::CreateActionComponent().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 72 of file ActionFillBottleBase.c.
References AnimatedActionBase::m_CommandUID, and SetupStance().
SetupStance()
void SetupStance (PlayerBase player) inline private
Definition at line 102 of file ActionFillBottleBase.c.
References HumanCommandSwim(), m_StanceMask, and WATER_DEPTH.
Referenced by SetupAction().
Field Documentation
ALLOWED_WATER_SURFACES
private const string ALLOWED_WATER_SURFACES = string.Format("%1|%2", UAWaterType.FRESH, UAWaterType.STILL) private
Definition at line 25 of file ActionFillBottleBase.c.
Referenced by ActionCondition().
WATER_DEPTH
private const float WATER_DEPTH = 0.5 private
Definition at line 24 of file ActionFillBottleBase.c.
Referenced by SetupStance().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionFillBottleBase.c