DayZ Scripts: P:/scripts/3_Game/Systems/DynamicMusicPlayer/DynamicMusicPlayer.c File Reference
DynamicMusicPlayer.c File Reference
Data Structures
class DynamicMusicLocationTypes
class DynamicMusicPlayerSettings
class DynamicMusicPlayerTrackHistoryLookupType
class DynamicMusicPlayerTimeOfDay
for backward compatibility
Functions
static array< vector > GetRectangularCoordsFromSize (vector origin, float size)
void InsertLocation (vector min, vector max)
void DynamicMusicPlayer (DynamicMusicPlayerRegistry configuration)
void OnUpdate (float timeslice)
void SetCategory (EDynamicMusicPlayerCategory category, bool forced)
void RegisterDynamicLocation (notnull Entity caller, int locationType, float locationSize)
void UnregisterDynamicLocation (notnull Entity caller)
protected bool IsPriotitizedCategorySelected ()
protected void DetermineTrackByCategory (EDynamicMusicPlayerCategory category)
protected bool IsPlaybackActive ()
protected void OnProfileOptionChanged (EDayZProfilesOptions option, int value)
protected void OnCategorySet (EDynamicMusicPlayerCategory category, bool forced)
protected void OnTrackEnded ()
protected void OnTrackStopped ()
protected void OnNextTrackSelected (DynamicMusicTrackData track, float waitTime)
protected void OnLocationMatched (EDynamicMusicPlayerCategory category, bool isPriorityLocation)
protected void OnFadeoutFinished (EDynamicMusicPlayerCategory category)
private void PlayTrack (DynamicMusicTrackData track)
private void StopTrack ()
private void ResetWaitingQueue ()
private void FadeoutTrack (float fadeoutSeconds)
private void ProcessFadeOut ()
private bool PlayerInsideOfLocationFilter (ref array< ref DynamicMusicTrackData > locations)
private bool PlayerInsideOfLocationFilter (ref map< int, ref DynamicMusicLocationDynamicData > locations)
private bool SetSelectedTrackFromCategory (EDynamicMusicPlayerCategory category, notnull ref array< ref DynamicMusicTrackData > tracklist, int historyLookupType=DynamicMusicPlayerTrackHistoryLookupType.ANY)
private int SelectRandomTrackIndexFromCategoryPriorityFlagFirst (EDynamicMusicPlayerCategory category, notnull array< ref DynamicMusicTrackData > tracks)
private int SelectRandomTrackIndexFromCategory (EDynamicMusicPlayerCategory category, int lookupType, notnull array< ref DynamicMusicTrackData > tracks)
private void SetTimeOfDate ()
protected float GetWaitTimeForCategory (EDynamicMusicPlayerCategory category)
private float GetMinWaitTimePerCategory (EDynamicMusicPlayerCategory category)
private float GetMaxWaitTimePerCategory (EDynamicMusicPlayerCategory category)
private float GetPreviousTrackFadeoutSeconds (EDynamicMusicPlayerCategory category)
private void RefreshTracksCache ()
Variables
class DynamicMusicLocationTypes m_Type = DynamicMusicLocationTypes.NONE
vector m_Min = vector.Zero
rectangle coords (2d only)
vector m_Max = vector.Zero
class DynamicMusicPlayerSettings m_HasPriority = false
int m_TimeOfDay = -1
int m_LocationType = DynamicMusicLocationTypes.NONE
string m_SoundSet
EDynamicMusicPlayerCategory m_Category
ref array< ref array< vector > > locationBoundaries = new ref array<ref array<vector>>()
class DynamicMusicPlayerTrackHistoryLookupType TICK_TIME_OF_DATE_UPDATE_SECONDS = 300.0
protected const float TICK_LOCATION_CACHE_UPDATE_SECONDS = 120.0
protected const float TICK_LOCATION_UPDATE_SECONDS = 120.0
protected const float TICK_PRIORITY_LOCATION_UPDATE_SECONDS = 30.0
protected const float TICK_FADEOUT_PROCESSOR_SECONDS = 0.2
protected const int TRACKS_BUFFER_HISTORY_SIZE = 2
protected const float LOCATION_DISTANCE_MAX = 500
protected float m_TickTimeOfDateElapsed
protected float m_TickLocationCacheUpdateElapsed
protected float m_TickLocationUpdateElapsed
protected float m_TickPriorityLocationUpdateElapsed
protected float m_TickFadeOutProcessingElapsed
protected int m_ActualTimeOfDay protected EDynamicMusicPlayerCategory m_CategorySelected
protected DynamicMusicTrackData m_CurrentTrack
protected ref DynamicMusicPlayerRegistry m_DynamicMusicPlayerRegistry
protected ref map< int, ref DynamicMusicLocationDynamicData > m_LocationsDynamic private ref array< ref DynamicMusicTrackData > m_TracksLocationStaticCached
map of dynamically registered locations during runtime
private ref array< ref DynamicMusicTrackData > m_TracksLocationStaticPrioritizedCached
static + filtered by the distance between player and center of zone
protected ref array< ref DynamicMusicTrackData > m_TracksLocationMatchedPlayerInside
static prio + filtered by the distance between player and center of zone
protected AbstractWave m_SoundPlaying
private bool m_WaitingForPlayback
private int m_RequestedPlaybackMode private ref map< EDynamicMusicPlayerCategory, ref SimpleCircularBuffer< int > > m_LastPlayedTrackBufferPerCategory
gets the playback mode as set in sounds menu; 0 - all; 1 - menu only
private vector m_PlayerPosition
private float m_FadeoutTimeElapsed
private float m_FadeoutTimeRequested
private bool m_FadeoutInProgress
private bool m_Created
Function Documentation
DetermineTrackByCategory()
protected void DetermineTrackByCategory (EDynamicMusicPlayerCategory category)
References DynamicMusicPlayerTrackHistoryLookupType::BUFFER, CALL_CATEGORY_SYSTEM, DetermineTrackByCategory(), g_Game, IsPlaybackActive(), m_CategorySelected, m_DynamicMusicPlayerRegistry, DynamicMusicPlayerRegistry::m_TracksLocationDynamic, m_TracksLocationMatchedPlayerInside, DynamicMusicPlayerRegistry::m_TracksMenu, DynamicMusicPlayerRegistry::m_TracksTime, and SetSelectedTrackFromCategory().
Referenced by DetermineTrackByCategory(), OnCategorySet(), and OnUpdate().
DynamicMusicPlayer()
void DynamicMusicPlayer (DynamicMusicPlayerRegistry configuration)
fadeout settings
References WorldDataDaytime::ANY, CALL_CATEGORY_SYSTEM, g_Game, ScriptInvoker::Insert(), m_CategorySelected, m_Created, m_DynamicMusicPlayerRegistry, m_FadeoutTimeElapsed, m_FadeoutTimeRequested, m_LastPlayedTrackBufferPerCategory, DayZProfilesOptions::m_OnIntOptionChanged, m_TracksLocationMatchedPlayerInside, m_TracksLocationStaticCached, m_TracksLocationStaticPrioritizedCached, OnProfileOptionChanged(), RefreshTracksCache(), SetTimeOfDate(), and TRACKS_BUFFER_HISTORY_SIZE.
Referenced by MissionBaseWorld::MissionBase().
FadeoutTrack()
private void FadeoutTrack (float fadeoutSeconds)
References m_CurrentTrack, m_FadeoutInProgress, m_FadeoutTimeRequested, and m_SoundPlaying.
Referenced by OnLocationMatched().
GetMaxWaitTimePerCategory()
private float GetMaxWaitTimePerCategory (EDynamicMusicPlayerCategory category)
References m_DynamicMusicPlayerRegistry, and DynamicMusicPlayerRegistry::m_SettingsByCategory.
Referenced by GetWaitTimeForCategory().
GetMinWaitTimePerCategory()
private float GetMinWaitTimePerCategory (EDynamicMusicPlayerCategory category)
References m_DynamicMusicPlayerRegistry, and DynamicMusicPlayerRegistry::m_SettingsByCategory.
Referenced by GetWaitTimeForCategory().
GetPreviousTrackFadeoutSeconds()
private float GetPreviousTrackFadeoutSeconds (EDynamicMusicPlayerCategory category)
References m_DynamicMusicPlayerRegistry, and DynamicMusicPlayerRegistry::m_SettingsByCategory.
Referenced by OnLocationMatched().
GetRectangularCoordsFromSize()
static array< vector > GetRectangularCoordsFromSize (vector origin, float size) static
References Vector().
GetWaitTimeForCategory()
protected float GetWaitTimeForCategory (EDynamicMusicPlayerCategory category)
References GetMaxWaitTimePerCategory(), GetMinWaitTimePerCategory(), and Math::RandomFloatInclusive().
Referenced by SetSelectedTrackFromCategory().
InsertLocation()
void InsertLocation (vector min, vector max)
References locationBoundaries.
IsPlaybackActive()
protected bool IsPlaybackActive ()
References m_SoundPlaying, and m_WaitingForPlayback.
Referenced by DetermineTrackByCategory(), and OnUpdate().
IsPriotitizedCategorySelected()
protected bool IsPriotitizedCategorySelected ()
References m_CategorySelected.
Referenced by OnFadeoutFinished(), OnLocationMatched(), and OnUpdate().
OnCategorySet()
protected void OnCategorySet (EDynamicMusicPlayerCategory category, bool forced)
References DetermineTrackByCategory(), and EnumTools::EnumToString().
Referenced by SetCategory().
OnFadeoutFinished()
protected void OnFadeoutFinished (EDynamicMusicPlayerCategory category)
References AbstractWave::GetEvents(), IsPriotitizedCategorySelected(), m_SoundPlaying, OnTrackEnded(), SetCategory(), and StopTrack().
Referenced by OnUpdate().
OnLocationMatched()
protected void OnLocationMatched (EDynamicMusicPlayerCategory category, bool isPriorityLocation)
play prio location track (no fadeout)
play location track (no fadeout)
References FadeoutTrack(), GetPreviousTrackFadeoutSeconds(), IsPriotitizedCategorySelected(), m_CategorySelected, and SetCategory().
Referenced by OnUpdate().
OnNextTrackSelected()
protected void OnNextTrackSelected (DynamicMusicTrackData track, float waitTime)
References CALL_CATEGORY_SYSTEM, g_Game, m_Created, m_CurrentTrack, m_WaitingForPlayback, and PlayTrack().
Referenced by SetSelectedTrackFromCategory().
OnProfileOptionChanged()
protected void OnProfileOptionChanged (EDayZProfilesOptions option, int value)
Events
References m_CategorySelected, ResetWaitingQueue(), and StopTrack().
Referenced by DynamicMusicPlayer().
OnTrackEnded()
protected void OnTrackEnded ()
References m_CurrentTrack, m_SoundPlaying, and m_WaitingForPlayback.
Referenced by OnFadeoutFinished(), and PlayTrack().
OnTrackStopped()
protected void OnTrackStopped ()
stopped only by fadeouts
References m_CurrentTrack, m_SoundPlaying, and m_WaitingForPlayback.
Referenced by PlayTrack().
OnUpdate()
void OnUpdate (float timeslice)
handle fadeouts
caching of locations based on distance from player (<= LOCATION_DISTANCE_MAX)
no playback at all OR playback of non-prioritized category
works as default category selector
menu only
References DetermineTrackByCategory(), g_Game, DiagMenu::GetBool(), IsPlaybackActive(), IsPriotitizedCategorySelected(), m_CategorySelected, m_DynamicMusicPlayerRegistry, m_FadeoutInProgress, m_FadeoutTimeElapsed, m_FadeoutTimeRequested, m_PlayerPosition, m_TickFadeOutProcessingElapsed, m_TickLocationCacheUpdateElapsed, m_TickLocationUpdateElapsed, m_TickPriorityLocationUpdateElapsed, m_TickTimeOfDateElapsed, m_TracksLocationStaticCached, m_TracksLocationStaticPrioritizedCached, OnFadeoutFinished(), OnLocationMatched(), PlayerInsideOfLocationFilter(), ProcessFadeOut(), RefreshTracksCache(), SetCategory(), SetTimeOfDate(), TICK_FADEOUT_PROCESSOR_SECONDS, TICK_LOCATION_CACHE_UPDATE_SECONDS, TICK_LOCATION_UPDATE_SECONDS, TICK_PRIORITY_LOCATION_UPDATE_SECONDS, and TICK_TIME_OF_DATE_UPDATE_SECONDS.
PlayerInsideOfLocationFilter() [1/2]
private bool PlayerInsideOfLocationFilter (ref array< ref DynamicMusicTrackData > locations)
References INDEX_NOT_FOUND, Math::IsPointInRectangle(), m_PlayerPosition, and m_TracksLocationMatchedPlayerInside.
Referenced by OnUpdate().
PlayerInsideOfLocationFilter() [2/2]
private bool PlayerInsideOfLocationFilter (ref map< int, ref DynamicMusicLocationDynamicData > locations)
References Math::IsPointInRectangle(), and m_PlayerPosition.
PlayTrack()
private void PlayTrack (DynamicMusicTrackData track)
register callbacks
invalid sound set is used
References SoundObjectBuilder::BuildSoundObject(), AbstractWave::GetEvents(), GetGame(), CGame::GetSoundScene(), SoundParams::IsValid(), AbstractWave::Loop(), m_CurrentTrack, m_SoundPlaying, m_WaitingForPlayback, OnTrackEnded(), OnTrackStopped(), AbstractWave::Play(), and SoundObject().
Referenced by OnNextTrackSelected(), and ResetWaitingQueue().
ProcessFadeOut()
private void ProcessFadeOut ()
References m_FadeoutTimeElapsed, m_FadeoutTimeRequested, m_SoundPlaying, and AbstractWave::SetFadeOutFactor().
Referenced by OnUpdate().
RefreshTracksCache()
private void RefreshTracksCache ()
References Math::CenterOfRectangle(), vector::Distance(), LOCATION_DISTANCE_MAX, m_DynamicMusicPlayerRegistry, m_PlayerPosition, DynamicMusicPlayerRegistry::m_TracksLocationStatic, m_TracksLocationStaticCached, DynamicMusicPlayerRegistry::m_TracksLocationStaticPrioritized, and m_TracksLocationStaticPrioritizedCached.
Referenced by DynamicMusicPlayer(), and OnUpdate().
RegisterDynamicLocation()
void RegisterDynamicLocation (notnull Entity caller, int locationType, float locationSize)
ResetWaitingQueue()
private void ResetWaitingQueue ()
References CALL_CATEGORY_SYSTEM, g_Game, m_CurrentTrack, m_WaitingForPlayback, and PlayTrack().
Referenced by OnProfileOptionChanged().
SelectRandomTrackIndexFromCategory()
private int SelectRandomTrackIndexFromCategory (EDynamicMusicPlayerCategory category, int lookupType, notnull array< ref DynamicMusicTrackData > tracks)
References DynamicMusicPlayerTrackHistoryLookupType::ANY, DynamicMusicPlayerTrackHistoryLookupType::BUFFER, INDEX_NOT_FOUND, m_LastPlayedTrackBufferPerCategory, Math::RandomInt(), and TRACKS_BUFFER_HISTORY_SIZE.
Referenced by SetSelectedTrackFromCategory().
SelectRandomTrackIndexFromCategoryPriorityFlagFirst()
private int SelectRandomTrackIndexFromCategoryPriorityFlagFirst (EDynamicMusicPlayerCategory category, notnull array< ref DynamicMusicTrackData > tracks)
main menu priority tracks first
fallback in case there is no priority track
References INDEX_NOT_FOUND.
Referenced by SetSelectedTrackFromCategory().
SetCategory()
void SetCategory (EDynamicMusicPlayerCategory category, bool forced)
References m_CategorySelected, m_DynamicMusicPlayerRegistry, and OnCategorySet().
Referenced by BIOSErrorModule::BIOSErrorModule(), ClientKickedModule::ClientKickedModule(), ConnectErrorClientModule::ConnectErrorClientModule(), ConnectErrorServerModule::ConnectErrorServerModule(), OnFadeoutFinished(), OnLocationMatched(), and OnUpdate().
SetSelectedTrackFromCategory()
private bool SetSelectedTrackFromCategory (EDynamicMusicPlayerCategory category, notnull ref array< ref DynamicMusicTrackData > tracklist, int historyLookupType = DynamicMusicPlayerTrackHistoryLookupType.ANY)
currently prioritize main menu track on DMP start
References WorldDataDaytime::ANY, GetWaitTimeForCategory(), INDEX_NOT_FOUND, m_Created, m_LastPlayedTrackBufferPerCategory, OnNextTrackSelected(), SelectRandomTrackIndexFromCategory(), and SelectRandomTrackIndexFromCategoryPriorityFlagFirst().
Referenced by DetermineTrackByCategory().
SetTimeOfDate()
private void SetTimeOfDate ()
References WorldDataDaytime::DAY, and g_Game.
Referenced by DynamicMusicPlayer(), and OnUpdate().
StopTrack()
private void StopTrack ()
References m_SoundPlaying, and AbstractWave::Stop().
Referenced by OnFadeoutFinished(), and OnProfileOptionChanged().
UnregisterDynamicLocation()
void UnregisterDynamicLocation (notnull Entity caller)
Variable Documentation
LOCATION_DISTANCE_MAX
protected const float LOCATION_DISTANCE_MAX = 500
Referenced by RefreshTracksCache().
locationBoundaries
ref array<ref array<vector> > locationBoundaries = new ref array<ref array<vector>>()
Referenced by InsertLocation(), and DynamicMusicPlayerRegistry::RegisterTrackLocationStaticMultiRectangle().
m_Category
EDynamicMusicPlayerCategory m_Category
m_CategorySelected
protected int m_ActualTimeOfDay protected EDynamicMusicPlayerCategory m_CategorySelected
Referenced by DetermineTrackByCategory(), DynamicMusicPlayer(), IsPriotitizedCategorySelected(), OnLocationMatched(), OnProfileOptionChanged(), OnUpdate(), and SetCategory().
m_Created
private bool m_Created
Referenced by DynamicMusicPlayer(), OnNextTrackSelected(), and SetSelectedTrackFromCategory().
m_CurrentTrack
protected DynamicMusicTrackData m_CurrentTrack
Referenced by FadeoutTrack(), OnNextTrackSelected(), OnTrackEnded(), OnTrackStopped(), PlayTrack(), and ResetWaitingQueue().
m_DynamicMusicPlayerRegistry
protected ref DynamicMusicPlayerRegistry m_DynamicMusicPlayerRegistry
Referenced by DetermineTrackByCategory(), DynamicMusicPlayer(), GetMaxWaitTimePerCategory(), GetMinWaitTimePerCategory(), GetPreviousTrackFadeoutSeconds(), MissionBaseWorld::InitialiseWorldData(), MissionBaseWorld::MissionBase(), OnUpdate(), RefreshTracksCache(), and SetCategory().
m_FadeoutInProgress
private bool m_FadeoutInProgress
Referenced by FadeoutTrack(), and OnUpdate().
m_FadeoutTimeElapsed
private float m_FadeoutTimeElapsed
Referenced by DynamicMusicPlayer(), OnUpdate(), and ProcessFadeOut().
m_FadeoutTimeRequested
private float m_FadeoutTimeRequested
Referenced by DynamicMusicPlayer(), FadeoutTrack(), OnUpdate(), and ProcessFadeOut().
m_HasPriority
class DynamicMusicPlayerSettings m_HasPriority = false
m_LastPlayedTrackBufferPerCategory
private int m_RequestedPlaybackMode private ref map<EDynamicMusicPlayerCategory, ref SimpleCircularBuffer<int> > m_LastPlayedTrackBufferPerCategory
gets the playback mode as set in sounds menu; 0 - all; 1 - menu only
Referenced by DynamicMusicPlayer(), SelectRandomTrackIndexFromCategory(), and SetSelectedTrackFromCategory().
m_LocationType
int m_LocationType = DynamicMusicLocationTypes.NONE
m_Max
vector m_Max = vector.Zero
m_Min
vector m_Min = vector.Zero
rectangle coords (2d only)
m_PlayerPosition
private vector m_PlayerPosition
Referenced by OnUpdate(), PlayerInsideOfLocationFilter(), PlayerInsideOfLocationFilter(), and RefreshTracksCache().
m_SoundPlaying
protected AbstractWave m_SoundPlaying
Referenced by FadeoutTrack(), IsPlaybackActive(), OnFadeoutFinished(), OnTrackEnded(), OnTrackStopped(), PlayTrack(), ProcessFadeOut(), and StopTrack().
m_SoundSet
string m_SoundSet
m_TickFadeOutProcessingElapsed
protected float m_TickFadeOutProcessingElapsed
Referenced by OnUpdate().
m_TickLocationCacheUpdateElapsed
protected float m_TickLocationCacheUpdateElapsed
Referenced by OnUpdate().
m_TickLocationUpdateElapsed
protected float m_TickLocationUpdateElapsed
Referenced by OnUpdate().
m_TickPriorityLocationUpdateElapsed
protected float m_TickPriorityLocationUpdateElapsed
Referenced by OnUpdate().
m_TickTimeOfDateElapsed
protected float m_TickTimeOfDateElapsed
Referenced by OnUpdate().
m_TimeOfDay
int m_TimeOfDay = -1
m_TracksLocationMatchedPlayerInside
protected ref array<ref DynamicMusicTrackData> m_TracksLocationMatchedPlayerInside
static prio + filtered by the distance between player and center of zone
Referenced by DetermineTrackByCategory(), DynamicMusicPlayer(), and PlayerInsideOfLocationFilter().
m_TracksLocationStaticCached
protected ref map<int, ref DynamicMusicLocationDynamicData> m_LocationsDynamic private ref array<ref DynamicMusicTrackData> m_TracksLocationStaticCached
map of dynamically registered locations during runtime
Referenced by DynamicMusicPlayer(), OnUpdate(), and RefreshTracksCache().
m_TracksLocationStaticPrioritizedCached
private ref array<ref DynamicMusicTrackData> m_TracksLocationStaticPrioritizedCached
static + filtered by the distance between player and center of zone
Referenced by DynamicMusicPlayer(), OnUpdate(), and RefreshTracksCache().
m_Type
class DynamicMusicLocationTypes m_Type = DynamicMusicLocationTypes.NONE
Referenced by MindStateSoundEventBase::AlertedMoveSoundEvent(), DisplayElementBadge::BadgeBleeding(), DisplayElementBadge::BadgeFracture(), DisplayElementBadge::BadgeHeartbeat(), DisplayElementBadge::BadgeLegs(), DisplayElementBadge::BadgePills(), DisplayElementBadge::BadgePoisoned(), DisplayElementBadge::BadgeSick(), DisplayElementBadge::BadgeStuffed(), DisplayElementBadge::BadgeWet(), BotStateBase::Bot_TestSpawnOpen(), BotStateBase::BotSpawnEntityInHands(), MindStateSoundEventBase::CalmMoveSoundEvent(), CalmMoveSoundEvent(), CanPlay(), MindStateSoundEventBase::ChaseMoveSoundEvent(), ChaseMoveSoundEvent(), PlayerSoundEventBase::DamageSoundEvents(), PlayerSoundEventBase::DrowningEvents(), DisplayElementBase::ElementStance(), HoldBreathSoundEventBase::ExhaustedBreathSoundEvent(), ExhaustedBreathSoundEvent(), Managed::GameplayEffectsData(), MessageReceiverBase::GetAgentType(), GetType(), MessageReceiverBase::GetType(), Managed::GetWidgetSetType(), HasPriorityOverCurrent(), PlayerSoundEventBase::HeatComfortEventsBase(), HoldBreathSoundEventBase(), InfectedSoundEventBase(), AgentBase::Init(), Managed::Init(), PlayerStatBase::Init(), Init(), PlayerSoundEventBase::InjurySoundEvents(), PlayerSoundEventBase::MeleeAttackSoundEvents(), BotStateBase::OnEntry(), OnUpdateServer(), PlayerSoundEventBase::PickupHeavySoundEvent(), PickupHeavySoundEvent(), PlayerSoundEventBase(), HandEventBase::ReadFromContext(), SetType(), StaminaModifier(), StaminaSoundEventBase::StaminaNormalDummy(), PlayerSoundEventBase::StaminaSoundEventBase(), PlayerSoundEventBase::SymptomSoundEventBase(), DisplayElementTendency::TendencyBacteria(), DisplayElementTendency::TendencyBlood(), DisplayElementTendency::TendencyHealth(), DisplayElementTendency::TendencyHunger(), DisplayElementTendency::TendencyTemperature(), DisplayElementTendency::TendencyThirst(), and HandEventBase::WriteToContext().
m_WaitingForPlayback
private bool m_WaitingForPlayback
Referenced by IsPlaybackActive(), OnNextTrackSelected(), OnTrackEnded(), OnTrackStopped(), PlayTrack(), and ResetWaitingQueue().
TICK_FADEOUT_PROCESSOR_SECONDS
protected const float TICK_FADEOUT_PROCESSOR_SECONDS = 0.2
Referenced by OnUpdate().
TICK_LOCATION_CACHE_UPDATE_SECONDS
protected const float TICK_LOCATION_CACHE_UPDATE_SECONDS = 120.0
Referenced by OnUpdate().
TICK_LOCATION_UPDATE_SECONDS
protected const float TICK_LOCATION_UPDATE_SECONDS = 120.0
Referenced by OnUpdate().
TICK_PRIORITY_LOCATION_UPDATE_SECONDS
protected const float TICK_PRIORITY_LOCATION_UPDATE_SECONDS = 30.0
Referenced by OnUpdate().
TICK_TIME_OF_DATE_UPDATE_SECONDS
class DynamicMusicPlayerTrackHistoryLookupType TICK_TIME_OF_DATE_UPDATE_SECONDS = 300.0
Referenced by OnUpdate().
TRACKS_BUFFER_HISTORY_SIZE
protected const int TRACKS_BUFFER_HISTORY_SIZE = 2
Referenced by DynamicMusicPlayer(), and SelectRandomTrackIndexFromCategory().