DayZ Scripts: ActionDebug Class Reference
ActionDebug Class Reference
Private Member Functions
override bool HasTarget ()
override void CreateConditionComponents ()
override ActionData CreateActionData ()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override void Start (ActionData action_data)
override bool UseAcknowledgment ()
Detailed Description
Definition at line 12 of file ActionDebug.c.
Member Function Documentation
CreateActionData()
override ActionData CreateActionData () inline private
Definition at line 25 of file ActionDebug.c.
Referenced by SetupAction().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 19 of file ActionDebug.c.
References m_ConditionItem, and m_ConditionTarget.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 86 of file ActionDebug.c.
References ActionDebugReciveData::m_DebugActionID, and ActionDebugReciveData::m_Item.
Referenced by SetupAction().
HasTarget()
override bool HasTarget () inline private
Definition at line 14 of file ActionDebug.c.
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 64 of file ActionDebug.c.
References ActionDebugReciveData::m_DebugActionID, ActionDebugReciveData::m_Item, and Serializer::Read().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 31 of file ActionDebug.c.
References Class::CastTo(), CreateActionData(), GetGame(), and HandleReciveData().
Start()
override void Start (ActionData action_data) inline private
Definition at line 95 of file ActionDebug.c.
References Class::CastTo().
UseAcknowledgment()
override bool UseAcknowledgment () inline private
Definition at line 103 of file ActionDebug.c.
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 55 of file ActionDebug.c.
References Class::CastTo(), and Serializer::Write().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Instant/ActionDebug.c