DayZ Scripts: FracturedLegNotfr Class Reference
FracturedLegNotfr Class Reference
Private Member Functions
void FracturedLegNotfr (NotifiersManager manager)
override int GetNotifierType ()
override void SetActive (bool state)
override void DisplayBadge ()
override void HideBadge ()
Detailed Description
Definition at line 1 of file FracturedLegNotfr.c.
Constructor & Destructor Documentation
FracturedLegNotfr()
void FracturedLegNotfr (NotifiersManager manager) inline private
Definition at line 3 of file FracturedLegNotfr.c.
References NotifierBase::m_Active.
Member Function Documentation
DisplayBadge()
override void DisplayBadge () inline private
Definition at line 26 of file FracturedLegNotfr.c.
References GetElement(), and NotifierBase::GetVirtualHud().
Referenced by SetActive().
GetNotifierType()
override int GetNotifierType () inline private
Definition at line 8 of file FracturedLegNotfr.c.
HideBadge()
override void HideBadge () inline private
Definition at line 36 of file FracturedLegNotfr.c.
References GetElement(), and NotifierBase::GetVirtualHud().
Referenced by SetActive().
SetActive()
override void SetActive (bool state) inline private
Definition at line 13 of file FracturedLegNotfr.c.
References DisplayBadge(), and HideBadge().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerNotifiers/Notifiers/FracturedLegNotfr.c