DayZ Scripts: PlayerPreviewWidget Class Reference
PlayerPreviewWidget Class Reference
Private Member Functions
proto native void UpdateItemInHands (EntityAI object)
proto native void SetPlayer (DayZPlayer player)
proto native DayZPlayer GetDummyPlayer ()
proto native void Refresh ()
proto native void SetModelOrientation (vector vOrientation)
proto native vector GetModelOrientation ()
proto native void SetModelPosition (vector vPos)
proto native vector GetModelPosition ()
Detailed Description
Definition at line 299 of file gameplay.c.
Member Function Documentation
GetDummyPlayer()
proto native DayZPlayer GetDummyPlayer () private
Referenced by PlayerPreview::UpdateInterval().
GetModelOrientation()
proto native vector GetModelOrientation () private
GetModelPosition()
proto native vector GetModelPosition () private
Refresh()
proto native void Refresh () private
Referenced by PlayerPreview::RefreshPlayerPreview().
SetModelOrientation()
proto native void SetModelOrientation (vector vOrientation) private
Referenced by PlayerPreview::UpdateRotation().
SetModelPosition()
proto native void SetModelPosition (vector vPos) private
Referenced by PlayerPreview::PlayerPreview().
SetPlayer()
proto native void SetPlayer (DayZPlayer player) private
Referenced by PlayerPreview::PlayerPreview().
UpdateItemInHands()
proto native void UpdateItemInHands (EntityAI object) private
Referenced by PlayerPreview::UpdateInterval().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/gameplay.c