DayZ Scripts: ShockHandler Class Reference
ShockHandler Class Reference
Private Member Functions
void ShockHandler (PlayerBase player)
void Update (float deltaT)
float GetCurrentShock ()
float GetShock ()
void SetShock (float dealtShock)
private void DealShock ()
void CheckValue (bool forceUpdate)
protected void Synchronize ()
float SetMultiplier (float mult)
private float NormalizeShockVal (float shock)
private float LerpVignette (float x, float y, float deltaT)
private void ShockHitEffect (float compareBase)
Private Attributes
protected float m_Shock
protected float m_ShockValueMax
protected float m_ShockValueThreshold
protected PlayerBase m_Player
protected const float UPDATE_THRESHOLD = 3
const float VALUE_CHECK_INTERVAL = 0.95
protected float m_CumulatedShock
private float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1
private float m_ShockMultiplier = 1
private float m_PrevVignette
private float m_LerpRes
private const int LIGHT_SHOCK_HIT = 33
private const int MID_SHOCK_HIT = 67
private const int HEAVY_SHOCK_HIT = 100
private const int INTENSITY_FACTOR = 1
private const float PULSE_PERIOD = 0.5
private const float PULSE_AMPLITUDE = 0.05
private float m_PulseTimer
protected ref Param1< float > m_Param
Constructor & Destructor Documentation
ShockHandler()
void ShockHandler (PlayerBase player) inline private
References m_Param, m_Player, m_PrevVignette, m_ShockValueMax, and m_ShockValueThreshold.
Member Function Documentation
CheckValue()
void CheckValue (bool forceUpdate) inline private
References DealShock(), GetGame(), m_CumulatedShock, m_Player, m_PrevVignette, m_Shock, m_ShockMultiplier, NormalizeShockVal(), Synchronize(), and UPDATE_THRESHOLD.
Referenced by SetShock(), and Update().
DealShock()
private void DealShock () inline private
References GetGame(), m_CumulatedShock, and m_Player.
Referenced by CheckValue().
GetCurrentShock()
float GetCurrentShock () inline private
References m_Player.
GetShock()
float GetShock () inline private
References m_Shock.
LerpVignette()
private float LerpVignette (float x, float y, float deltaT) inline private
References Math::Lerp(), x, and y.
Referenced by Update().
NormalizeShockVal()
private float NormalizeShockVal (float shock) inline private
References INTENSITY_FACTOR, and m_Player.
Referenced by CheckValue(), and Update().
SetMultiplier()
float SetMultiplier (float mult) inline private
References m_ShockMultiplier.
SetShock()
void SetShock (float dealtShock) inline private
References CheckValue(), and m_Shock.
ShockHitEffect()
private void ShockHitEffect (float compareBase) inline private
References HEAVY_SHOCK_HIT, LIGHT_SHOCK_HIT, m_CumulatedShock, m_Player, MID_SHOCK_HIT, and UPDATE_THRESHOLD.
Referenced by Update().
Synchronize()
protected void Synchronize () inline private
References m_Player, and DayZPlayerSyncJunctures::SendShock().
Referenced by CheckValue().
Update()
void Update (float deltaT) inline private
References CheckValue(), Easing::EaseInQuart(), GetGame(), LerpVignette(), m_LerpRes, m_Param, m_Player, m_PrevVignette, m_PulseTimer, m_ShockValueMax, m_ShockValueThreshold, m_TimeSinceLastTick, NormalizeShockVal(), PULSE_AMPLITUDE, PULSE_PERIOD, ShockHitEffect(), and VALUE_CHECK_INTERVAL.
Field Documentation
HEAVY_SHOCK_HIT
private const int HEAVY_SHOCK_HIT = 100 private
Referenced by ShockHitEffect().
INTENSITY_FACTOR
private const int INTENSITY_FACTOR = 1 private
Referenced by NormalizeShockVal().
LIGHT_SHOCK_HIT
private const int LIGHT_SHOCK_HIT = 33 private
Referenced by ShockHitEffect().
m_CumulatedShock
protected float m_CumulatedShock private
Referenced by CheckValue(), DealShock(), and ShockHitEffect().
m_LerpRes
private float m_LerpRes private
Referenced by Update().
m_Param
protected ref Param1<float> m_Param private
Referenced by ShockHandler(), and Update().
m_Player
protected PlayerBase m_Player private
Referenced by CheckValue(), DealShock(), GetCurrentShock(), NormalizeShockVal(), ShockHandler(), ShockHitEffect(), Synchronize(), and Update().
m_PrevVignette
private float m_PrevVignette private
Referenced by CheckValue(), ShockHandler(), and Update().
m_PulseTimer
private float m_PulseTimer private
Referenced by Update().
m_Shock
protected float m_Shock private
Referenced by CheckValue(), GetShock(), and SetShock().
m_ShockMultiplier
private float m_ShockMultiplier = 1 private
Referenced by CheckValue(), and SetMultiplier().
m_ShockValueMax
protected float m_ShockValueMax private
Referenced by ShockHandler(), and Update().
m_ShockValueThreshold
protected float m_ShockValueThreshold private
Referenced by ShockHandler(), and Update().
m_TimeSinceLastTick
private float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1 private
Referenced by Update().
MID_SHOCK_HIT
private const int MID_SHOCK_HIT = 67 private
Referenced by ShockHitEffect().
PULSE_AMPLITUDE
private const float PULSE_AMPLITUDE = 0.05 private
Referenced by Update().
PULSE_PERIOD
private const float PULSE_PERIOD = 0.5 private
Referenced by Update().
UPDATE_THRESHOLD
protected const float UPDATE_THRESHOLD = 3 private
Referenced by CheckValue(), and ShockHitEffect().
VALUE_CHECK_INTERVAL
const float VALUE_CHECK_INTERVAL = 0.95 private
Referenced by Update().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/ShockHandler.c