DayZ Scripts: Hud Class Reference
Hud Class Reference
Private Member Functions
void Init (Widget hud_panel_widget)
void DisplayNotifier (int key, int tendency, int status)
void DisplayBadge (int key, int value)
void SetStamina (int value, int range)
void DisplayStance (int stance)
void DisplayPresence ()
void ShowCursor ()
void HideCursor ()
void SetCursorIcon (string icon)
void SetCursorIconScale (string type, float percentage)
void SetCursorIconOffset (string type, float x, float y)
void SetCursorIconSize (string type, float x, float y)
void ShowWalkieTalkie (bool show)
void ShowWalkieTalkie (int fadeOutSeconds)
void SetWalkieTalkieText (string text)
void RefreshQuickbar (bool itemChanged=false)
void Show (bool show)
void UpdateBloodName ()
void SetTemperature (string temp)
void SetStaminaBarVisibility (bool show)
void Update (float timeslice)
void ShowVehicleInfo ()
void HideVehicleInfo ()
void ToggleHeatBufferPlusSign (bool show)
void ShowQuickbarUI (bool show)
void ShowQuickbarPlayer (bool show)
void ShowHudPlayer (bool show)
void ShowHudUI (bool show)
void ShowHudInventory (bool show)
void ShowQuickBar (bool show)
void UpdateQuickbarGlobalVisibility ()
void ShowHud (bool show)
void OnResizeScreen ()
void SetPermanentCrossHair (bool show)
void SpawnHitDirEffect (DayZPlayer player, float hit_direction, float intensity_max)
void SetConnectivityStatIcon (EConnectivityStatType type, EConnectivityStatLevel level)
void IngameHud ()
override void Init (Widget hud_panel_widget)
void InitBadgesAndNotifiers ()
void OnConnectionIconsSettingsChanged (bool enabled)
override void OnResizeScreen ()
override void Show (bool show)
override void ShowWalkieTalkie (bool show)
override void ShowWalkieTalkie (int fadeOutSeconds)
override void SetWalkieTalkieText (string text)
override void SetCursorIcon (string icon)
override void ShowCursor ()
override void HideCursor ()
override void SetCursorIconScale (string type, float percentage)
override void SetCursorIconOffset (string type, float x, float y)
override void SetCursorIconSize (string type, float x, float y)
override void DisplayNotifier (int key, int tendency, int status)
void DisplayTendencyNormal (int key, int tendency, int status)
void DisplayTendencyTemp (int key, int tendency, int status)
override void DisplayBadge (int key, int value)
override void SetTemperature (string temp)
void HideTemperature ()
override void SetStaminaBarVisibility (bool show)
void SetStomachState (int state)
override void SetStamina (int value, int range)
bool KeyPress (int key)
void ZeroingKeyPress ()
override void DisplayStance (int stance)
override void DisplayPresence ()
override void ShowVehicleInfo ()
override void HideVehicleInfo ()
void RefreshVehicleHud (float timeslice)
void InitQuickbar ()
InventoryQuickbar GetQuickbar ()
bool IsQuickbarVisible ()
bool IsHudVisible ()
override void UpdateQuickbarGlobalVisibility ()
void RefreshQuickbarVisibility ()
void RefreshHudVisibility ()
void UpdateSpecialtyMeter (float x, float y)
bool IsHideQuickbarPlayer ()
bool IsHideHudPlayer ()
override void ShowQuickbarUI (bool show)
override void ShowQuickbarPlayer (bool show)
override void ShowHudPlayer (bool show)
override void ShowHudUI (bool show)
override void ShowHudInventory (bool show)
override void ToggleHeatBufferPlusSign (bool show)
override void ShowQuickBar (bool show)
global setting; is quickbar visibility allowed?
override void ShowHud (bool show)
bool GetQuickBarState ()
bool GetHudState ()
override void SetConnectivityStatIcon (EConnectivityStatType type, EConnectivityStatLevel level)
void SetLeftStatsVisibility (bool visible)
eg. stamina bar...
override void RefreshQuickbar (bool itemChanged=false)
Widget GetHudPanelWidget ()
override void UpdateBloodName ()
void RefreshPlayerTags ()
void ShowPlayerTag (float timeslice)
override void Update (float timeslice)
override void SpawnHitDirEffect (DayZPlayer player, float hit_direction, float intensity_max)
void UpdateHitDirEffects (float timeslice)
void CleanupHitDirEffects ()
void Debug ()
void HideQuickbarTimer ()
Private Attributes
ref Timer m_Timer
protected const float FADE_IN_TIME = 0.3
protected const float FADE_OUT_TIME = 0.3
protected const float HIDE_MENU_TIME = 5
protected ref map< int, string > m_StatesWidgetNames
protected ref map< int, ImageWidget > m_StatesWidgets
protected ref map< ImageWidget, int > m_TendencyStatusCritical
protected const float TENDENCY_BLINK_TIME = 0.25
protected float m_BlinkTime
protected ref map< int, string > m_BadgesWidgetNames
protected ref map< int, int > m_BadgesSupportedLevels
protected ref map< int, int > m_BadgesWidgetDisplay
protected ref map< int, ImageWidget > m_BadgesWidgets
protected bool m_AnyBadgeVisible
protected bool m_IsTemperatureVisible
protected float m_TemperatureTimer
protected float m_TemperatureShowTime = 30
protected ImageWidget m_HeatBufferPlus
protected bool m_IsStaminaVisible
protected float m_StaminaTimer
protected float m_StaminaShowTime = 0.15
protected ref map< int, string > m_VehicleGearTable
protected ref map< int, string > m_VehicleGearTableAuto
protected Widget m_HudPanelWidget
protected Widget m_LeftHudPanelWidget
protected Widget m_QuickbarWidget
protected ref InventoryQuickbar m_Quickbar
protected Widget m_VehiclePanel
protected ImageWidget m_VehicleRPMPointer
protected ImageWidget m_VehicleRPMDial
protected ImageWidget m_VehicleRPMRedline
protected ImageWidget m_VehicleSpeedPointer
protected Widget m_VehicleTemperatureIndicator
protected ImageWidget m_VehicleTemperaturePointer
protected ImageWidget m_VehicleTemperatureLight
protected ImageWidget m_VehicleFuelPointer
protected ImageWidget m_VehicleFuelLight
protected TextWidget m_VehicleSpeedValue
protected TextWidget m_VehicleCurrentGearValue
protected TextWidget m_VehicleNextGearValue
protected TextWidget m_VehiclePrevGearValue
protected ImageWidget m_VehicleBatteryLight
protected ImageWidget m_VehicleEngineLight
protected ImageWidget m_VehicleOilLight
protected ImageWidget m_VehicleHandBrakeLight
protected ImageWidget m_VehicleWheelLight
protected bool m_VehicleDamageZoneHitEngineState
protected float m_VehicleDamageZonesHitTimer
protected bool m_InVehicleAsDriver
protected CarScript m_CurrentVehicle
protected Widget m_GameStatusIconsPanel
protected ImageWidget m_HighPingA
protected ImageWidget m_HighPingB
protected ImageWidget m_LowServerPerfA
protected ImageWidget m_LowServerPerfB
protected ImageWidget m_ConnectionLost
protected Widget m_Notifiers
protected TextWidget m_BloodType
protected TextWidget m_BloodPosType
protected Widget m_BadgeNotifierDivider
protected Widget m_Badges
protected ref Timer m_HideTimer
protected ref WidgetFadeTimer m_FadeTimerCrosshair
protected ref WidgetFadeTimer m_FadeTimerActionCursor
protected ref WidgetFadeTimer m_FadeTimerZeroingOld
protected ref WidgetFadeTimer m_FadeTimerMagazineName
protected ref WidgetFadeTimer m_FadeTimerWeaponName
protected ref WidgetFadeTimer m_FadeTimerWeaponStats
protected ref WidgetFadeTimer m_FadeTimerQuickbar
protected ref WidgetFadeTimer m_FadeTimerWalkieTalkie
protected ref WidgetFadeTimer m_FadeTimerWalkieTalkieText
protected ProgressBarWidget m_Stamina
protected Widget m_StaminaBackground
protected Widget m_Presence
protected Widget m_StanceProne
protected Widget m_StanceStand
protected Widget m_StanceStandWalk
protected Widget m_StanceCrouch
protected Widget m_StanceCar
protected Widget m_StancePanel
protected Widget m_PresenceLevel0
protected Widget m_PresenceLevel1
protected Widget m_PresenceLevel2
protected Widget m_PresenceLevel3
protected Widget m_PresenceLevel4
protected ref Timer myTimer
protected ref array< ref WidgetFadeTimer > m_FadeTimers = new array<ref WidgetFadeTimer>
protected Widget m_MouseSingleAction
protected Widget m_MouseContinuousAction
protected Widget m_RadialProgressBar1
protected Widget m_RadialProgressBarCrossHair
protected Widget m_RadialProgressBar
protected Widget m_CursorWidget
protected ImageWidget m_CursorIcon
protected Widget m_WalkieTalkie
protected Widget m_ActionWidget
protected TextWidget m_ActionDesc
protected TextWidget m_ActionItemDesc
protected Widget m_ActionItemQuantityWrapper protected ImageWidget m_ActionHealthMark
protected ProgressBarWidget m_ActionQuantityBar
protected Widget m_ActionQuantityBox
protected TextWidget m_ActionQuantityBoxText
protected ImageWidget m_ActionIcon
protected TextWidget m_ActionButtonText
protected Widget m_ActionIconFrame
protected Widget m_ActionMultipleItemsFrame
protected Widget m_ActionTarget
protected ActionTargetsCursor m_ActionTargetsCursor
protected ImageWidget m_PermanentCrossHair
protected bool m_HudHideUI
protected bool m_HudHidePlayer
protected bool m_HudInventory
protected bool m_HudState
protected bool m_QuickbarHideUI
protected bool m_QuickbarHidePlayer
protected bool m_QuickbarState
protected bool m_IsQuickbarVisible
protected bool m_IsHudVisible
protected bool m_Faded
protected bool m_ZeroingKeyPressed
protected Widget m_HitIndicatorUp
protected Widget m_HitIndicatorDown
protected Widget m_HitIndicatorLeft
protected Widget m_HitIndicatorRight
protected Widget m_HitIndicatorSingle
protected Widget m_SpecializatonPanel
protected Widget m_SpecializationIcon
ref array< ref HitDirectionEffectBase > m_HitDirEffectArray
int m_VehicleGearCount = -1
float m_TimeSinceLastEngineLightChange
bool m_VehicleHasOil
bool m_VehicleHasCoolant
int m_PlayerSpineIndex
PlayerBase m_CurrentTaggedPlayer
Widget m_PlayerTag
TextWidget m_PlayerTagText
Member Function Documentation
CleanupHitDirEffects()
void CleanupHitDirEffects () inline private
Referenced by Update().
Debug()
void Debug () inline private
References EnumTools::EnumToString(), m_BadgesWidgetDisplay, and Print().
DisplayBadge() [1/2]
void DisplayBadge (int key, int value) inline private
Referenced by PluginBase::SetBadge().
DisplayBadge() [2/2]
override void DisplayBadge (int key, int value) inline private
References Class::CastTo(), NTFKEY_BLEEDISH, and RefreshHudVisibility().
DisplayNotifier() [1/2]
void DisplayNotifier (int key, int tendency, int status) inline private
Referenced by PluginBase::DisplayTendency().
DisplayNotifier() [2/2]
override void DisplayNotifier (int key, int tendency, int status) inline private
References Math::AbsInt(), Class::CastTo(), Math::Clamp(), DisplayTendencyNormal(), DisplayTendencyTemp(), m_Notifiers, NTFKEY_FEVERISH, String(), and x.
DisplayPresence() [1/2]
void DisplayPresence () inline private
Referenced by Update().
DisplayPresence() [2/2]
override void DisplayPresence () inline private
References Class::CastTo(), GetGame(), and GetPlayer().
DisplayStance() [1/2]
void DisplayStance (int stance) inline private
Referenced by PluginBase::SetStance().
DisplayStance() [2/2]
override void DisplayStance (int stance) inline private
References Class::CastTo(), GetGame(), and GetPlayer().
DisplayTendencyNormal()
void DisplayTendencyNormal (int key, int tendency, int status) inline private
References ARGB(), Class::CastTo(), Math::Clamp(), m_Notifiers, and String().
Referenced by DisplayNotifier().
DisplayTendencyTemp()
void DisplayTendencyTemp (int key, int tendency, int status) inline private
References ARGB(), m_Notifiers, and String().
Referenced by DisplayNotifier().
GetHudPanelWidget()
Widget GetHudPanelWidget () inline private
References m_HudPanelWidget.
GetHudState()
bool GetHudState () inline private
References m_HudState.
GetQuickbar()
InventoryQuickbar GetQuickbar () inline private
References m_Quickbar.
GetQuickBarState()
bool GetQuickBarState () inline private
References m_QuickbarState.
HideCursor() [1/2]
void HideCursor () inline private
HideCursor() [2/2]
override void HideCursor () inline private
HideQuickbarTimer()
void HideQuickbarTimer () inline private
HideTemperature()
void HideTemperature () inline private
References m_Notifiers.
Referenced by Update().
HideVehicleInfo() [1/2]
void HideVehicleInfo () private
Referenced by MissionBase::HideVehicleInfo(), and ManBase::OnVehicleSeatDriverLeft().
HideVehicleInfo() [2/2]
override void HideVehicleInfo () inline private
IngameHud()
void IngameHud () inline private
Init() [1/2]
void Init (Widget hud_panel_widget) inline private
Referenced by MissionBase::OnInit().
Init() [2/2]
override void Init (Widget hud_panel_widget) inline private
gets scripted handler from widget
References CALL_CATEGORY_GAMEPLAY, Class::CastTo(), g_Game, GetGame(), InitBadgesAndNotifiers(), m_BloodType, m_Notifiers, m_QuickbarWidget, m_SpecializationIcon, m_Stamina, m_Timer, and SetLeftStatsVisibility().
InitBadgesAndNotifiers()
void InitBadgesAndNotifiers () inline private
References ARGB(), Class::CastTo(), m_Notifiers, NTFKEY_BLEEDISH, NTFKEY_FEVERISH, NTFKEY_FRACTURE, NTFKEY_HUNGRY, NTFKEY_LEGS, NTFKEY_LIVES, NTFKEY_PILLS, NTFKEY_POISONED, NTFKEY_SICK, NTFKEY_STUFFED, NTFKEY_THIRSTY, NTFKEY_WETNESS, String(), x, and y.
Referenced by Init().
InitQuickbar()
void InitQuickbar () inline private
References m_Quickbar, and m_QuickbarWidget.
IsHideHudPlayer()
bool IsHideHudPlayer () inline private
References m_HudHidePlayer.
Referenced by MissionBase::OnUpdate().
IsHideQuickbarPlayer()
bool IsHideQuickbarPlayer () inline private
References m_QuickbarHidePlayer.
Referenced by MissionBase::OnUpdate().
IsHudVisible()
bool IsHudVisible () inline private
References m_IsHudVisible.
Referenced by ScriptedWidgetEventHandler::Update().
IsQuickbarVisible()
bool IsQuickbarVisible () inline private
References m_IsQuickbarVisible.
KeyPress()
bool KeyPress (int key) inline private
Referenced by MissionBase::OnKeyPress().
OnConnectionIconsSettingsChanged()
void OnConnectionIconsSettingsChanged (bool enabled) inline private
OnResizeScreen() [1/2]
void OnResizeScreen () private
Referenced by MissionBase::OnEvent().
OnResizeScreen() [2/2]
override void OnResizeScreen () inline private
References m_Notifiers, x, and y.
RefreshHudVisibility()
void RefreshHudVisibility () inline private
References m_HudState, m_Notifiers, and SetLeftStatsVisibility().
Referenced by DisplayBadge(), ShowHud(), ShowHudInventory(), ShowHudPlayer(), and ShowHudUI().
RefreshPlayerTags()
void RefreshPlayerTags () inline private
References vector::Distance(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), CGame::GetPlayer(), GetPlayer(), CGame::GetScreenPosRelative(), ClientData::m_PlayerBaseList, array::obj, DayZPhysics::RaycastRVProxy(), and RaycastRVParams::sorted.
Referenced by Update().
RefreshQuickbar() [1/2]
void RefreshQuickbar (bool itemChanged = false) inline private
RefreshQuickbar() [2/2]
override void RefreshQuickbar (bool itemChanged = false) inline private
References UIManager::FindMenu(), GetGame(), CGame::GetUIManager(), InventoryMenu(), m_Quickbar, m_QuickbarWidget, MENU_INVENTORY, and mission.
RefreshQuickbarVisibility()
void RefreshQuickbarVisibility () inline private
References m_QuickbarState, and m_QuickbarWidget.
Referenced by ShowQuickBar(), ShowQuickbarPlayer(), and ShowQuickbarUI().
RefreshVehicleHud()
void RefreshVehicleHud (float timeslice) inline private
engine
fuel tank
temperature
general hit timer reset
References Math::AbsInt(), Colors::COLOR_RUINED, GetDayZGame(), EnumTools::GetEnumSize(), GetGame(), ItemManager::GetItemHealthColor(), CarScript::IsVitalRadiator(), GameConstants::STATE_WORN, and Colors::WHITE.
Referenced by Update().
SetConnectivityStatIcon() [1/2]
void SetConnectivityStatIcon (EConnectivityStatType type, EConnectivityStatLevel level) private
Referenced by CGame::OnConnectivityStatChange().
SetConnectivityStatIcon() [2/2]
override void SetConnectivityStatIcon (EConnectivityStatType type, EConnectivityStatLevel level) inline private
SetCursorIcon() [1/2]
void SetCursorIcon (string icon) inline private
SetCursorIcon() [2/2]
override void SetCursorIcon (string icon) inline private
References string::Length(), and CursorIcons::None.
SetCursorIconOffset() [1/2]
void SetCursorIconOffset (string type, float x, float y) inline private
SetCursorIconOffset() [2/2]
override void SetCursorIconOffset (string type, float x, float y) inline private
References x, and y.
SetCursorIconScale() [1/2]
void SetCursorIconScale (string type, float percentage) inline private
SetCursorIconScale() [2/2]
override void SetCursorIconScale (string type, float percentage) inline private
References Icon::SetSize(), x, and y.
SetCursorIconSize() [1/2]
void SetCursorIconSize (string type, float x, float y) inline private
SetCursorIconSize() [2/2]
override void SetCursorIconSize (string type, float x, float y) inline private
References x, and y.
SetLeftStatsVisibility()
void SetLeftStatsVisibility (bool visible) inline private
eg. stamina bar...
Referenced by Init(), and RefreshHudVisibility().
SetPermanentCrossHair()
void SetPermanentCrossHair (bool show) inline private
Referenced by PluginBase::SwitchPermanentCrossHair().
SetStamina() [1/2]
void SetStamina (int value, int range) inline private
Referenced by PluginBase::SetStamina().
SetStamina() [2/2]
override void SetStamina (int value, int range) inline private
References Class::CastTo(), GetDayZGame(), GetGame(), GetPlayer(), CfgGameplayHandler::GetStaminaMax(), and m_Stamina.
SetStaminaBarVisibility() [1/2]
void SetStaminaBarVisibility (bool show) private
Referenced by ManBase::StaminaHUDNotifier(), and Update().
SetStaminaBarVisibility() [2/2]
override void SetStaminaBarVisibility (bool show) inline private
References m_Stamina.
SetStomachState()
void SetStomachState (int state) inline private
SetTemperature() [1/2]
void SetTemperature (string temp) private
Referenced by ManBase::OnRPC().
SetTemperature() [2/2]
override void SetTemperature (string temp) inline private
References m_Notifiers.
SetWalkieTalkieText() [1/2]
void SetWalkieTalkieText (string text) inline private
SetWalkieTalkieText() [2/2]
override void SetWalkieTalkieText (string text) inline private
References Class::CastTo().
Show() [1/2]
void Show (bool show) inline private
Show() [2/2]
override void Show (bool show) inline private
ShowCursor() [1/2]
void ShowCursor () inline private
ShowCursor() [2/2]
override void ShowCursor () inline private
ShowHud() [1/2]
void ShowHud (bool show) private
ShowHud() [2/2]
override void ShowHud (bool show) inline private
References RefreshHudVisibility().
ShowHudInventory() [1/2]
void ShowHudInventory (bool show) private
ShowHudInventory() [2/2]
override void ShowHudInventory (bool show) inline private
References RefreshHudVisibility().
ShowHudPlayer() [1/2]
void ShowHudPlayer (bool show) private
Referenced by ManBase::CloseMapEx(), MissionBase::OnUpdate(), UIScriptedMenu::ScriptConsole(), and UIScriptedMenu::~ScriptConsole().
ShowHudPlayer() [2/2]
override void ShowHudPlayer (bool show) inline private
References RefreshHudVisibility().
ShowHudUI() [1/2]
void ShowHudUI (bool show) private
Referenced by UIScriptedMenu::CloseMapMenu(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::InspectItem(), UIScriptedMenu::InviteMenu(), ManBase::OnPlayerLoaded(), ManBase::OnUnconsciousStop(), ManBase::OnUnconsciousUpdate(), MissionBase::OnUpdate(), WarningMenuBase::WarningMenuBase(), UIScriptedMenu::~InspectMenuNew(), UIScriptedMenu::~InviteMenu(), and WarningMenuBase::~WarningMenuBase().
ShowHudUI() [2/2]
override void ShowHudUI (bool show) inline private
References RefreshHudVisibility().
ShowPlayerTag()
void ShowPlayerTag (float timeslice) inline private
References Math::Clamp(), WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetScreenPosRelative(), and CGame::GetWorkspace().
Referenced by Update().
ShowQuickBar() [1/2]
void ShowQuickBar (bool show) private
Referenced by UpdateQuickbarGlobalVisibility().
ShowQuickBar() [2/2]
override void ShowQuickBar (bool show) inline private
global setting; is quickbar visibility allowed?
References RefreshQuickbarVisibility().
ShowQuickbarPlayer() [1/2]
void ShowQuickbarPlayer (bool show) private
Referenced by ManBase::CloseMapEx(), MissionBase::OnUpdate(), UIScriptedMenu::ScriptConsole(), and UIScriptedMenu::~ScriptConsole().
ShowQuickbarPlayer() [2/2]
override void ShowQuickbarPlayer (bool show) inline private
References RefreshQuickbarVisibility().
ShowQuickbarUI() [1/2]
void ShowQuickbarUI (bool show) private
Referenced by UIScriptedMenu::CloseMapMenu(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::InspectItem(), UIScriptedMenu::InviteMenu(), ManBase::OnPlayerLoaded(), ManBase::OnUnconsciousStop(), ManBase::OnUnconsciousUpdate(), WarningMenuBase::WarningMenuBase(), UIScriptedMenu::~InspectMenuNew(), UIScriptedMenu::~InviteMenu(), and WarningMenuBase::~WarningMenuBase().
ShowQuickbarUI() [2/2]
override void ShowQuickbarUI (bool show) inline private
References RefreshQuickbarVisibility().
ShowVehicleInfo() [1/2]
void ShowVehicleInfo () private
Referenced by ManBase::OnVehicleSeatDriverEnter(), and MissionBase::ShowVehicleInfo().
ShowVehicleInfo() [2/2]
override void ShowVehicleInfo () inline private
References GetGame(), GetPlayer(), and HumanCommandVehicle::GetTransport().
ShowWalkieTalkie() [1/4]
void ShowWalkieTalkie (bool show) inline private
ShowWalkieTalkie() [2/4]
override void ShowWalkieTalkie (bool show) inline private
ShowWalkieTalkie() [3/4]
void ShowWalkieTalkie (int fadeOutSeconds) inline private
ShowWalkieTalkie() [4/4]
override void ShowWalkieTalkie (int fadeOutSeconds) inline private
References Widget::Stop().
SpawnHitDirEffect() [1/2]
void SpawnHitDirEffect (DayZPlayer player, float hit_direction, float intensity_max) private
Referenced by DayZPlayer::EvaluateDamageHit().
SpawnHitDirEffect() [2/2]
override void SpawnHitDirEffect (DayZPlayer player, float hit_direction, float intensity_max) inline private
References HitDirectionEffectBase::GetCurrentType(), HitDirectionEffectBase::Init(), and HitDirectionEffectBase::m_Mode.
ToggleHeatBufferPlusSign() [1/2]
void ToggleHeatBufferPlusSign (bool show) private
Referenced by ManBase::EOnFrame().
ToggleHeatBufferPlusSign() [2/2]
override void ToggleHeatBufferPlusSign (bool show) inline private
Update() [1/2]
void Update (float timeslice) inline private
Referenced by ManBase::EOnFrame().
Update() [2/2]
override void Update (float timeslice) inline private
References ARGB(), CleanupHitDirEffects(), DisplayPresence(), HideTemperature(), RefreshPlayerTags(), RefreshVehicleHud(), SetStaminaBarVisibility(), ShowPlayerTag(), ActionTargetsCursor::Update(), and UpdateHitDirEffects().
UpdateBloodName() [1/2]
void UpdateBloodName () inline private
Referenced by ManBase::OnPlayerLoaded().
UpdateBloodName() [2/2]
override void UpdateBloodName () inline private
References Class::CastTo(), BloodTypes::GetBloodTypeName(), GetGame(), GetPlayer(), and m_BloodType.
UpdateHitDirEffects()
void UpdateHitDirEffects (float timeslice) inline private
Referenced by Update().
UpdateQuickbarGlobalVisibility() [1/2]
void UpdateQuickbarGlobalVisibility () private
Referenced by ManBase::OnPlayerLoaded().
UpdateQuickbarGlobalVisibility() [2/2]
override void UpdateQuickbarGlobalVisibility () inline private
References g_Game, GetGame(), GetInput(), and ShowQuickBar().
UpdateSpecialtyMeter()
void UpdateSpecialtyMeter (float x, float y) inline private
References m_SpecializationIcon, x, and y.
ZeroingKeyPress()
void ZeroingKeyPress () inline private
Referenced by MissionBase::OnUpdate().
Field Documentation
FADE_IN_TIME
protected const float FADE_IN_TIME = 0.3 private
FADE_OUT_TIME
protected const float FADE_OUT_TIME = 0.3 private
HIDE_MENU_TIME
protected const float HIDE_MENU_TIME = 5 private
m_ActionButtonText
protected TextWidget m_ActionButtonText private
m_ActionDesc
protected TextWidget m_ActionDesc private
m_ActionHealthMark
protected Widget m_ActionItemQuantityWrapper protected ImageWidget m_ActionHealthMark private
m_ActionIcon
protected ImageWidget m_ActionIcon private
m_ActionIconFrame
protected Widget m_ActionIconFrame private
m_ActionItemDesc
protected TextWidget m_ActionItemDesc private
m_ActionMultipleItemsFrame
protected Widget m_ActionMultipleItemsFrame private
m_ActionQuantityBar
protected ProgressBarWidget m_ActionQuantityBar private
m_ActionQuantityBox
protected Widget m_ActionQuantityBox private
m_ActionQuantityBoxText
protected TextWidget m_ActionQuantityBoxText private
m_ActionTarget
protected Widget m_ActionTarget private
m_ActionTargetsCursor
protected ActionTargetsCursor m_ActionTargetsCursor private
m_ActionWidget
protected Widget m_ActionWidget private
m_AnyBadgeVisible
protected bool m_AnyBadgeVisible private
m_BadgeNotifierDivider
protected Widget m_BadgeNotifierDivider private
m_Badges
protected Widget m_Badges private
m_BadgesSupportedLevels
protected ref map<int,int> m_BadgesSupportedLevels private
m_BadgesWidgetDisplay
protected ref map<int,int> m_BadgesWidgetDisplay private
Referenced by Debug().
m_BadgesWidgetNames
protected ref map<int,string> m_BadgesWidgetNames private
m_BadgesWidgets
protected ref map<int,ImageWidget> m_BadgesWidgets private
m_BlinkTime
protected float m_BlinkTime private
m_BloodPosType
protected TextWidget m_BloodPosType private
m_BloodType
protected TextWidget m_BloodType private
m_ConnectionLost
protected ImageWidget m_ConnectionLost private
m_CurrentTaggedPlayer
PlayerBase m_CurrentTaggedPlayer private
m_CurrentVehicle
protected CarScript m_CurrentVehicle private
m_CursorIcon
protected ImageWidget m_CursorIcon private
m_CursorWidget
protected Widget m_CursorWidget private
m_Faded
protected bool m_Faded private
m_FadeTimerActionCursor
protected ref WidgetFadeTimer m_FadeTimerActionCursor private
m_FadeTimerCrosshair
protected ref WidgetFadeTimer m_FadeTimerCrosshair private
m_FadeTimerMagazineName
protected ref WidgetFadeTimer m_FadeTimerMagazineName private
m_FadeTimerQuickbar
protected ref WidgetFadeTimer m_FadeTimerQuickbar private
m_FadeTimers
protected ref array<ref WidgetFadeTimer> m_FadeTimers = new array<ref WidgetFadeTimer> private
m_FadeTimerWalkieTalkie
protected ref WidgetFadeTimer m_FadeTimerWalkieTalkie private
m_FadeTimerWalkieTalkieText
protected ref WidgetFadeTimer m_FadeTimerWalkieTalkieText private
m_FadeTimerWeaponName
protected ref WidgetFadeTimer m_FadeTimerWeaponName private
m_FadeTimerWeaponStats
protected ref WidgetFadeTimer m_FadeTimerWeaponStats private
m_FadeTimerZeroingOld
protected ref WidgetFadeTimer m_FadeTimerZeroingOld private
m_GameStatusIconsPanel
protected Widget m_GameStatusIconsPanel private
m_HeatBufferPlus
protected ImageWidget m_HeatBufferPlus private
m_HideTimer
protected ref Timer m_HideTimer private
m_HighPingA
protected ImageWidget m_HighPingA private
m_HighPingB
protected ImageWidget m_HighPingB private
m_HitDirEffectArray
ref array<ref HitDirectionEffectBase> m_HitDirEffectArray private
m_HitIndicatorDown
protected Widget m_HitIndicatorDown private
m_HitIndicatorLeft
protected Widget m_HitIndicatorLeft private
m_HitIndicatorRight
protected Widget m_HitIndicatorRight private
m_HitIndicatorSingle
protected Widget m_HitIndicatorSingle private
m_HitIndicatorUp
protected Widget m_HitIndicatorUp private
m_HudHidePlayer
protected bool m_HudHidePlayer private
Referenced by IsHideHudPlayer().
m_HudHideUI
protected bool m_HudHideUI private
m_HudInventory
protected bool m_HudInventory private
m_HudPanelWidget
protected Widget m_HudPanelWidget private
Referenced by GetHudPanelWidget().
m_HudState
protected bool m_HudState private
Referenced by GetHudState(), and RefreshHudVisibility().
m_InVehicleAsDriver
protected bool m_InVehicleAsDriver private
m_IsHudVisible
protected bool m_IsHudVisible private
Referenced by IsHudVisible().
m_IsQuickbarVisible
protected bool m_IsQuickbarVisible private
Referenced by IsQuickbarVisible().
m_IsStaminaVisible
protected bool m_IsStaminaVisible private
m_IsTemperatureVisible
protected bool m_IsTemperatureVisible private
m_LeftHudPanelWidget
protected Widget m_LeftHudPanelWidget private
m_LowServerPerfA
protected ImageWidget m_LowServerPerfA private
m_LowServerPerfB
protected ImageWidget m_LowServerPerfB private
m_MouseContinuousAction
protected Widget m_MouseContinuousAction private
m_MouseSingleAction
protected Widget m_MouseSingleAction private
m_Notifiers
protected Widget m_Notifiers private
m_PermanentCrossHair
protected ImageWidget m_PermanentCrossHair private
m_PlayerSpineIndex
int m_PlayerSpineIndex private
m_PlayerTag
Widget m_PlayerTag private
m_PlayerTagText
TextWidget m_PlayerTagText private
m_Presence
protected Widget m_Presence private
m_PresenceLevel0
protected Widget m_PresenceLevel0 private
m_PresenceLevel1
protected Widget m_PresenceLevel1 private
m_PresenceLevel2
protected Widget m_PresenceLevel2 private
m_PresenceLevel3
protected Widget m_PresenceLevel3 private
m_PresenceLevel4
protected Widget m_PresenceLevel4 private
m_Quickbar
protected ref InventoryQuickbar m_Quickbar private
Referenced by GetQuickbar().
m_QuickbarHidePlayer
protected bool m_QuickbarHidePlayer private
Referenced by IsHideQuickbarPlayer().
m_QuickbarHideUI
protected bool m_QuickbarHideUI private
m_QuickbarState
protected bool m_QuickbarState private
Referenced by GetQuickBarState(), and RefreshQuickbarVisibility().
m_QuickbarWidget
protected Widget m_QuickbarWidget private
m_RadialProgressBar
protected Widget m_RadialProgressBar private
m_RadialProgressBar1
protected Widget m_RadialProgressBar1 private
m_RadialProgressBarCrossHair
protected Widget m_RadialProgressBarCrossHair private
m_SpecializationIcon
protected Widget m_SpecializationIcon private
m_SpecializatonPanel
protected Widget m_SpecializatonPanel private
m_Stamina
protected ProgressBarWidget m_Stamina private
m_StaminaBackground
protected Widget m_StaminaBackground private
m_StaminaShowTime
protected float m_StaminaShowTime = 0.15 private
m_StaminaTimer
protected float m_StaminaTimer private
m_StanceCar
protected Widget m_StanceCar private
m_StanceCrouch
protected Widget m_StanceCrouch private
m_StancePanel
protected Widget m_StancePanel private
m_StanceProne
protected Widget m_StanceProne private
m_StanceStand
protected Widget m_StanceStand private
m_StanceStandWalk
protected Widget m_StanceStandWalk private
m_StatesWidgetNames
protected ref map<int,string> m_StatesWidgetNames private
m_StatesWidgets
protected ref map<int,ImageWidget> m_StatesWidgets private
m_TemperatureShowTime
protected float m_TemperatureShowTime = 30 private
m_TemperatureTimer
protected float m_TemperatureTimer private
m_TendencyStatusCritical
protected ref map<ImageWidget, int> m_TendencyStatusCritical private
m_Timer
ref Timer m_Timer private
m_TimeSinceLastEngineLightChange
float m_TimeSinceLastEngineLightChange private
m_VehicleBatteryLight
protected ImageWidget m_VehicleBatteryLight private
m_VehicleCurrentGearValue
protected TextWidget m_VehicleCurrentGearValue private
m_VehicleDamageZoneHitEngineState
protected bool m_VehicleDamageZoneHitEngineState private
m_VehicleDamageZonesHitTimer
protected float m_VehicleDamageZonesHitTimer private
m_VehicleEngineLight
protected ImageWidget m_VehicleEngineLight private
m_VehicleFuelLight
protected ImageWidget m_VehicleFuelLight private
m_VehicleFuelPointer
protected ImageWidget m_VehicleFuelPointer private
m_VehicleGearCount
int m_VehicleGearCount = -1 private
m_VehicleGearTable
protected ref map<int,string> m_VehicleGearTable private
m_VehicleGearTableAuto
protected ref map<int,string> m_VehicleGearTableAuto private
m_VehicleHandBrakeLight
protected ImageWidget m_VehicleHandBrakeLight private
m_VehicleHasCoolant
bool m_VehicleHasCoolant private
m_VehicleHasOil
bool m_VehicleHasOil private
m_VehicleNextGearValue
protected TextWidget m_VehicleNextGearValue private
m_VehicleOilLight
protected ImageWidget m_VehicleOilLight private
m_VehiclePanel
protected Widget m_VehiclePanel private
m_VehiclePrevGearValue
protected TextWidget m_VehiclePrevGearValue private
m_VehicleRPMDial
protected ImageWidget m_VehicleRPMDial private
m_VehicleRPMPointer
protected ImageWidget m_VehicleRPMPointer private
m_VehicleRPMRedline
protected ImageWidget m_VehicleRPMRedline private
m_VehicleSpeedPointer
protected ImageWidget m_VehicleSpeedPointer private
m_VehicleSpeedValue
protected TextWidget m_VehicleSpeedValue private
m_VehicleTemperatureIndicator
protected Widget m_VehicleTemperatureIndicator private
m_VehicleTemperatureLight
protected ImageWidget m_VehicleTemperatureLight private
m_VehicleTemperaturePointer
protected ImageWidget m_VehicleTemperaturePointer private
m_VehicleWheelLight
protected ImageWidget m_VehicleWheelLight private
m_WalkieTalkie
protected Widget m_WalkieTalkie private
m_ZeroingKeyPressed
protected bool m_ZeroingKeyPressed private
myTimer
protected ref Timer myTimer private
TENDENCY_BLINK_TIME
protected const float TENDENCY_BLINK_TIME = 0.25 private
The documentation for this class was generated from the following files:
P:/scripts/3_Game/gameplay.c
P:/scripts/5_Mission/GUI/IngameHud.c