DayZ Scripts: ResavePlugin Class Reference
ResavePlugin Class Reference
Private Member Functions
void Resave (string file)
override void Run ()
override void RunCommandline ()
bool OK ()
bool Cancel ()
Private Attributes
string Extension
WBModuleDef m_module
Detailed Description
Definition at line 2 of file ResaveTool.c.
Member Function Documentation
Cancel()
bool Cancel () inline private
Definition at line 44 of file ResaveTool.c.
OK()
bool OK () inline private
Definition at line 38 of file ResaveTool.c.
Resave()
void Resave (string file) inline private
Definition at line 8 of file ResaveTool.c.
References Print(), WBModuleDef::Save(), and WBModuleDef::SetOpenedResource().
Run()
override void Run () inline private
Definition at line 15 of file ResaveTool.c.
References Workbench::GetModule(), Workbench::ScriptDialog(), and Workbench::SearchResources().
RunCommandline()
override void RunCommandline () inline private
Definition at line 24 of file ResaveTool.c.
References WBModuleDef::Close(), WBModuleDef::GetCmdLine(), Workbench::GetModule(), string::Replace(), and Workbench::SearchResources().
Field Documentation
Extension
string Extension private
Definition at line 5 of file ResaveTool.c.
m_module
WBModuleDef m_module private
Definition at line 6 of file ResaveTool.c.
The documentation for this class was generated from the following file:
P:/scripts/editor/Workbench/ResaveTool.c