DayZ Scripts: Land_Underground_Panel_Lever Class Reference
Land_Underground_Panel_Lever Class Reference
Private Member Functions
override void SetActions ()
void ResetPhase (EntityAI target)
override void OnPanelUsedSynchronized ()
override void Interact ()
Member Function Documentation
Interact()
override void Interact () inline private
References GetGame(), GetLinkedDoor(), and CGame::RegisterNetworkStaticObject().
OnPanelUsedSynchronized()
override void OnPanelUsedSynchronized () inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), OnLEDStateChanged(), and ResetPhase().
ResetPhase()
void ResetPhase (EntityAI target) inline private
Referenced by OnPanelUsedSynchronized().
SetActions()
override void SetActions () inline private
References AddAction().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Building/Underground/Entrance/Land_Underground_Panel_Lever.c