DayZ Scripts: EmoteBase Class Reference
EmoteBase Class Reference
Private Member Functions
bool EmoteCondition (int stancemask)
bool CanBeCanceledNormally (notnull EmoteCB callback)
bool EmoteFBStanceCheck (int stancemask)
Checks for valid stance mask.
bool DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody)
void OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody)
void OnCallbackEnd ()
bool EmoteStartOverride (typename callbacktype, int id, int mask, bool fullbody)
void SetOwnerPlayer (PlayerBase player)
PlayerBase GetOwnerPlayer ()
int GetID ()
string GetInputActionName ()
int GetStanceMaskAdditive ()
int GetStanceMaskFullbody ()
int GetAdditiveCallbackUID ()
int GetFullbodyCallbackUID ()
bool GetHideItemInHands ()
void EmoteGreeting ()
void EmoteHeart ()
void EmoteLyingDown ()
override bool EmoteCondition (int stancemask)
void EmotePoint ()
void EmoteThumb ()
void EmoteThroat ()
void EmoteSalute ()
void EmoteDabbing ()
void EmoteClap ()
void EmoteWatching ()
void EmoteListening ()
void EmoteLookAtMe ()
void EmoteMove ()
void EmoteCome ()
void EmoteCampfireSit ()
void EmoteSitB ()
void EmoteRPSRock ()
void EmoteRPSScisors ()
void EmoteShake ()
void EmoteSuicide ()
override bool DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody)
override bool EmoteCondition (int stancemask)
override bool CanBeCanceledNormally (notnull EmoteCB callback)
override void OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody)
override void OnCallbackEnd ()
Private Attributes
protected PlayerBase m_Player
protected int m_ID = -1
protected string m_InputActionName = ""
protected int m_StanceMaskAdditive = 0
protected int m_StanceMaskFullbody = 0
protected int m_AdditiveCallbackUID = 0
protected int m_FullbodyCallbackUID = 0
protected bool m_HideItemInHands = false
protected const float WATER_DEPTH = 0.15
Member Function Documentation
CanBeCanceledNormally() [1/2]
bool CanBeCanceledNormally (notnull EmoteCB callback) inline private
Referenced by OnSyncJuncture(), and SendEmoteRequestSync().
CanBeCanceledNormally() [2/2]
override bool CanBeCanceledNormally (notnull EmoteCB callback) inline private
DetermineOverride() [1/2]
bool DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody) inline private
Referenced by DetermineEmoteData().
DetermineOverride() [2/2]
override bool DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody) inline private
References m_Player.
EmoteCampfireSit()
void EmoteCampfireSit () inline private
References EmoteConstants::ID_EMOTE_CAMPFIRE, and m_ID.
EmoteClap()
void EmoteClap () inline private
References EmoteConstants::ID_EMOTE_CLAP, and m_ID.
EmoteCome()
void EmoteCome () inline private
References EmoteConstants::ID_EMOTE_COME, and m_ID.
EmoteCondition() [1/3]
bool EmoteCondition (int stancemask) inline private
Referenced by CanPlayEmote().
EmoteCondition() [2/3]
override bool EmoteCondition (int stancemask) inline private
References HumanCommandSwim(), m_Player, and WATER_DEPTH.
EmoteCondition() [3/3]
override bool EmoteCondition (int stancemask) inline private
References m_Player.
EmoteDabbing()
void EmoteDabbing () inline private
References EmoteConstants::ID_EMOTE_DABBING, and m_ID.
EmoteFBStanceCheck()
bool EmoteFBStanceCheck (int stancemask) inline private
Checks for valid stance mask.
References DayZPlayerUtils(), ErrorEx, and m_Player.
Referenced by DetermineEmoteData().
EmoteGreeting()
void EmoteGreeting () inline private
References EmoteConstants::ID_EMOTE_GREETING, and m_ID.
EmoteHeart()
void EmoteHeart () inline private
References EmoteConstants::ID_EMOTE_HEART, and m_ID.
EmoteListening()
void EmoteListening () inline private
References EmoteConstants::ID_EMOTE_LISTENING, and m_ID.
EmoteLookAtMe()
void EmoteLookAtMe () inline private
References EmoteConstants::ID_EMOTE_LOOKATME, and m_ID.
EmoteLyingDown()
void EmoteLyingDown () inline private
References EmoteConstants::ID_EMOTE_LYINGDOWN, and m_ID.
EmoteMove()
void EmoteMove () inline private
References EmoteConstants::ID_EMOTE_MOVE, and m_ID.
EmotePoint()
void EmotePoint () inline private
References EmoteConstants::ID_EMOTE_POINT, and m_ID.
EmoteRPSRock()
void EmoteRPSRock () inline private
References EmoteConstants::ID_EMOTE_RPS_R, and m_ID.
EmoteRPSScisors()
void EmoteRPSScisors () inline private
References EmoteConstants::ID_EMOTE_RPS_S, and m_ID.
EmoteSalute()
void EmoteSalute () inline private
References EmoteConstants::ID_EMOTE_SALUTE, and m_ID.
EmoteShake()
void EmoteShake () inline private
References EmoteConstants::ID_EMOTE_SHAKE, and m_ID.
EmoteSitB()
void EmoteSitB () inline private
References EmoteConstants::ID_EMOTE_SITB, and m_ID.
EmoteStartOverride()
bool EmoteStartOverride (typename callbacktype , int id, int mask, bool fullbody) inline private
Referenced by PlayEmote().
EmoteSuicide()
void EmoteSuicide () inline private
References EmoteConstants::ID_EMOTE_SUICIDE, and m_ID.
EmoteThroat()
void EmoteThroat () inline private
References EmoteConstants::ID_EMOTE_THROAT, and m_ID.
EmoteThumb()
void EmoteThumb () inline private
References EmoteConstants::ID_EMOTE_THUMB, and m_ID.
EmoteWatching()
void EmoteWatching () inline private
References EmoteConstants::ID_EMOTE_WATCHING, and m_ID.
GetAdditiveCallbackUID()
int GetAdditiveCallbackUID () inline private
References m_AdditiveCallbackUID.
Referenced by DetermineEmoteData().
GetFullbodyCallbackUID()
int GetFullbodyCallbackUID () inline private
References m_FullbodyCallbackUID.
Referenced by DetermineEmoteData().
GetHideItemInHands()
bool GetHideItemInHands () inline private
References m_HideItemInHands.
Referenced by PlayEmote().
GetID()
int GetID () inline private
References m_ID.
GetInputActionName()
string GetInputActionName () inline private
References m_InputActionName.
Referenced by GetBoundButtonText().
GetOwnerPlayer()
PlayerBase GetOwnerPlayer () inline private
References m_Player.
GetStanceMaskAdditive()
int GetStanceMaskAdditive () inline private
References m_StanceMaskAdditive.
Referenced by DetermineEmoteData().
GetStanceMaskFullbody()
int GetStanceMaskFullbody () inline private
References m_StanceMaskFullbody.
Referenced by DetermineEmoteData().
OnBeforeStandardCallbackCreated() [1/2]
void OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody) private
Referenced by PlayEmote().
OnBeforeStandardCallbackCreated() [2/2]
override void OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody) inline private
References m_Player, and DayZPlayer::OverrideShootFromCamera().
OnCallbackEnd() [1/2]
void OnCallbackEnd () private
Referenced by OnCallbackEnd().
OnCallbackEnd() [2/2]
override void OnCallbackEnd () inline private
References m_Player, and DayZPlayer::SetSuicide().
SetOwnerPlayer()
void SetOwnerPlayer (PlayerBase player) inline private
References m_Player.
Field Documentation
m_AdditiveCallbackUID
protected int m_AdditiveCallbackUID = 0 private
Referenced by GetAdditiveCallbackUID().
m_FullbodyCallbackUID
protected int m_FullbodyCallbackUID = 0 private
Referenced by GetFullbodyCallbackUID().
m_HideItemInHands
protected bool m_HideItemInHands = false private
Referenced by GetHideItemInHands().
m_ID
protected int m_ID = -1 private
Referenced by GetID().
m_InputActionName
protected string m_InputActionName = "" private
Referenced by GetInputActionName().
m_Player
protected PlayerBase m_Player private
Referenced by EmoteFBStanceCheck(), GetOwnerPlayer(), and SetOwnerPlayer().
m_StanceMaskAdditive
protected int m_StanceMaskAdditive = 0 private
Referenced by GetStanceMaskAdditive().
m_StanceMaskFullbody
protected int m_StanceMaskFullbody = 0 private
Referenced by GetStanceMaskFullbody().
WATER_DEPTH
protected const float WATER_DEPTH = 0.15 private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/EmoteClasses/EmoteBase.c
P:/scripts/4_World/Classes/EmoteClasses/EmoteClasses.c