DayZ Scripts: PlayerSpawnPreset Class Reference
PlayerSpawnPreset Class Reference
Private Member Functions
string GetRandomCharacterType ()
override bool IsValid ()
bool HasAttachmentSlotSetsDefined ()
preset might be valid even with no attachmentSlotItemSets configured, checked separately
bool HasDiscreteUnsortedItemSetsDefined ()
preset might be valid even with no unsorted item sets configured, checked separately
Private Attributes
int spawnWeight
string name
ref array< string > characterTypes
ref array< ref PlayerSpawnPresetSlotData > attachmentSlotItemSets
ref array< ref PlayerSpawnPresetDiscreteCargoSetData > discreteUnsortedItemSets
Member Function Documentation
GetRandomCharacterType()
string GetRandomCharacterType () inline private
References characterTypes, and Debug::Log().
Referenced by MissionBase::OnClientNewEvent().
HasAttachmentSlotSetsDefined()
bool HasAttachmentSlotSetsDefined () inline private
preset might be valid even with no attachmentSlotItemSets configured, checked separately
References attachmentSlotItemSets.
Referenced by PlayerSpawnHandler::ProcessSlotsEquipment().
HasDiscreteUnsortedItemSetsDefined()
bool HasDiscreteUnsortedItemSetsDefined () inline private
preset might be valid even with no unsorted item sets configured, checked separately
References discreteUnsortedItemSets.
Referenced by PlayerSpawnHandler::ProcessCargoEquipment().
IsValid()
override bool IsValid () inline private
References Debug::Log(), name, and spawnWeight.
Referenced by PlayerSpawnHandler::GetRandomCharacterPreset(), MissionBase::OnClientNewEvent(), and PlayerSpawnHandler::ProcessEquipmentData().
Field Documentation
attachmentSlotItemSets
ref array<ref PlayerSpawnPresetSlotData> attachmentSlotItemSets private
Referenced by HasAttachmentSlotSetsDefined(), and PlayerSpawnHandler::ProcessSlotsEquipment().
characterTypes
ref array<string> characterTypes private
Referenced by GetRandomCharacterType().
discreteUnsortedItemSets
ref array<ref PlayerSpawnPresetDiscreteCargoSetData> discreteUnsortedItemSets private
Referenced by HasDiscreteUnsortedItemSetsDefined(), and PlayerSpawnHandler::SelectAndSpawnCargoSet().
name
string name private
Referenced by IsValid().
spawnWeight
int spawnWeight private
Referenced by PlayerSpawnHandler::GetRandomCharacterPreset(), and IsValid().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerGearSpawn/CfgPlayerSpawnDataJson.c