DayZ Scripts: ClosableHeader Class Reference
ClosableHeader Class Reference
Private Member Functions
void ClosableHeader (LayoutHolder parent, string function_name)
void ~ClosableHeader ()
override void SetLayoutName ()
override void SetName (string name)
void OnDragHeader (Widget w, int x, int y)
void UpdateFlip (bool flipped)
void OnDropHeader (Widget w)
bool MouseEnter (Widget w, int x, int y)
bool MouseLeave (Widget w, Widget enter_w, int x, int y)
override void SetActive (bool active)
Private Attributes
protected float m_SquareSize
protected int m_DefaultSort
protected Widget m_MovePanel
protected Widget m_PanelWidget
protected Widget m_DragRender
protected ButtonWidget m_MoveUp
protected ButtonWidget m_MoveDown
protected bool m_IsInLocalEquipment
Detailed Description
Definition at line 1 of file ClosableHeader.c.
Constructor & Destructor Documentation
ClosableHeader()
void ClosableHeader (LayoutHolder parent, string function_name) inline private
Definition at line 14 of file ClosableHeader.c.
References FindAnyWidget(), WidgetEventHandler::GetInstance(), GetParent(), Header::m_DefaultColor, Header::m_DefaultFontSize, m_DragRender, m_IsInLocalEquipment, m_MoveDown, m_MovePanel, m_MoveUp, m_PanelWidget, m_Parent, m_SquareSize, WidgetEventHandler::RegisterOnClick(), WidgetEventHandler::RegisterOnDrag(), WidgetEventHandler::RegisterOnDrop(), WidgetEventHandler::RegisterOnMouseEnter(), and WidgetEventHandler::RegisterOnMouseLeave().
~ClosableHeader()
void ~ClosableHeader () inline private
Definition at line 43 of file ClosableHeader.c.
References Header::m_Entity, and UpdateFlip().
Member Function Documentation
MouseEnter()
bool MouseEnter (Widget w, int x, int y) inline private
Definition at line 151 of file ClosableHeader.c.
References GetDragWidget(), GetGame(), GetInput(), Header::m_Entity, m_IsInLocalEquipment, m_MovePanel, x, and y.
MouseLeave()
bool MouseLeave (Widget w, Widget enter_w, int x, int y) inline private
Definition at line 165 of file ClosableHeader.c.
References Header::m_CollapseButton, m_IsInLocalEquipment, m_MoveDown, m_MovePanel, and m_MoveUp.
OnDragHeader()
void OnDragHeader (Widget w, int x, int y) inline private
Definition at line 66 of file ClosableHeader.c.
References GetGame(), ItemManager::GetInstance(), CGame::GetInventoryItemSize(), m_DefaultSort, m_DragRender, Header::m_Entity, m_PanelWidget, m_Parent, m_SquareSize, ItemManager::SetIsDragging(), ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetView(), and UpdateFlip().
OnDropHeader()
void OnDropHeader (Widget w) inline private
Definition at line 124 of file ClosableHeader.c.
References ItemManager::GetInstance(), ItemManager::HideDropzones(), m_DragRender, Header::m_Entity, m_PanelWidget, m_Parent, ItemManager::SetIsDragging(), ItemPreviewWidget::SetItem(), and UpdateFlip().
SetActive()
override void SetActive (bool active) inline private
Definition at line 178 of file ClosableHeader.c.
References ARGBF(), Header::m_DefaultColor, and m_PanelWidget.
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 49 of file ClosableHeader.c.
References WidgetLayoutName::ClosableHeader.
SetName()
override void SetName (string name) inline private
Definition at line 54 of file ClosableHeader.c.
References InventoryMenu(), Header::m_HeaderText, m_PanelWidget, name, string::ToUpper(), x, and y.
UpdateFlip()
void UpdateFlip (bool flipped) inline private
Definition at line 106 of file ClosableHeader.c.
References GetGame(), CGame::GetInventoryItemSize(), m_DragRender, Header::m_Entity, and m_SquareSize.
Referenced by OnDragHeader(), OnDropHeader(), and ~ClosableHeader().
Field Documentation
m_DefaultSort
protected int m_DefaultSort private
Definition at line 4 of file ClosableHeader.c.
Referenced by OnDragHeader().
m_DragRender
protected Widget m_DragRender private
Definition at line 8 of file ClosableHeader.c.
Referenced by ClosableHeader(), OnDragHeader(), OnDropHeader(), and UpdateFlip().
m_IsInLocalEquipment
protected bool m_IsInLocalEquipment private
Definition at line 12 of file ClosableHeader.c.
Referenced by ClosableHeader(), MouseEnter(), and MouseLeave().
m_MoveDown
protected ButtonWidget m_MoveDown private
Definition at line 10 of file ClosableHeader.c.
Referenced by ClosableHeader(), and MouseLeave().
m_MovePanel
protected Widget m_MovePanel private
Definition at line 6 of file ClosableHeader.c.
Referenced by ClosableHeader(), MouseEnter(), and MouseLeave().
m_MoveUp
protected ButtonWidget m_MoveUp private
Definition at line 9 of file ClosableHeader.c.
Referenced by ClosableHeader(), and MouseLeave().
m_PanelWidget
protected Widget m_PanelWidget private
Definition at line 7 of file ClosableHeader.c.
Referenced by ClosableHeader(), OnDragHeader(), OnDropHeader(), SetActive(), and SetName().
m_SquareSize
protected float m_SquareSize private
Definition at line 3 of file ClosableHeader.c.
Referenced by ClosableHeader(), OnDragHeader(), and UpdateFlip().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/ContainedItems/Headers/ClosableHeader.c