DayZ Scripts Documentation: P:/scripts/4_World/Entities/Core/Inherited/InventoryItem.c File Reference
InventoryItem.c File Reference
Data Structures
class InventoryItemSuper
class Weapon
script counterpart to engine's class Weapon
class CarWheel_Ruined
class CarWheel
class CarDoor
class Hatchback_02_Door_1_1
class Hatchback_02_Door_1_2
class Hatchback_02_Door_2_1
class Hatchback_02_Door_2_2
class Hatchback_02_Hood
class Hatchback_02_Trunk
class Sedan_02_Door_1_1
class Sedan_02_Door_1_2
class Sedan_02_Door_2_1
class Sedan_02_Door_2_2
class Sedan_02_Hood
class Sedan_02_Trunk
class HatchbackDoors_Driver
class HatchbackDoors_CoDriver
class HatchbackHood
class HatchbackTrunk
class CivSedanDoors_Driver
class CivSedanDoors_CoDriver
class CivSedanDoors_BackLeft
class CivSedanDoors_BackRight
class CivSedanHood
class CivSedanTrunk
class Truck_01_Door_1_1
class Truck_01_Door_2_1
class Truck_01_Door_Hood
class CarRadiator
class ItemBase
class Box_Base
class MapMarker
Typedefs
typedef ItemSuppressor SuppressorBase
typedef ItemGrenade GrenadeBase
Functions
proto native bool CanSpeak ()
proto native void SetCanSpeak (bool onOff)
proto native void TunePrev ()
void ReplaceWheelLambda (EntityAI old_item, string new_item_type, PlayerBase player)
override protected bool CanExecuteLambda ()
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
override protected void OnSuccess (EntityAI new_item)
Variables
class ItemBarrel extends InventoryItemSuper TuneNext
CarWheel_Ruined m_oldOri
Typedef Documentation
GrenadeBase
typedef ItemGrenade GrenadeBase
Definition at line 1031 of file InventoryItem.c.
SuppressorBase
typedef ItemSuppressor SuppressorBase
Definition at line 7 of file InventoryItem.c.
Function Documentation
CanExecuteLambda()
override protected bool CanExecuteLambda ()
Definition at line 407 of file InventoryItem.c.
CanSpeak()
proto native bool CanSpeak ()
CopyOldPropertiesToNew()
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
Definition at line 412 of file InventoryItem.c.
References m_oldOri.
OnSuccess()
override protected void OnSuccess (EntityAI new_item)
Definition at line 418 of file InventoryItem.c.
References m_oldOri.
ReplaceWheelLambda()
void ReplaceWheelLambda (EntityAI old_item, string new_item_type, PlayerBase player)
Definition at line 404 of file InventoryItem.c.
Referenced by InventoryItemSuper::EEHealthLevelChanged(), and CarWheel_Ruined::EEHealthLevelChanged().
SetCanSpeak()
proto native void SetCanSpeak (bool onOff)
TunePrev()
proto native void TunePrev ()
Referenced by ItemRadio::TunePreviousStation().
Variable Documentation
m_oldOri
CarWheel_Ruined m_oldOri
Referenced by CopyOldPropertiesToNew(), and OnSuccess().
TuneNext
class ItemMegaphone extends InventoryItemSuper TuneNext
Referenced by ItemRadio::TuneNextStation().