DayZ: 4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionForceConsumeSingle.c File Reference
ActionForceConsumeSingle.c File Reference
Data Structures
class ActionForceConsumeSingleCB
Functions
void ActionForceConsumeSingle ()
override void CreateConditionComponents ()
int GetConsumedQuantity ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnEndServer (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Variables
ActionForceConsumeSingleCB DEFAULT_CONSUMED_QUANTITY = 1
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 33 of file ActionForceConsumeSingle.c.
ActionForceConsumeSingle()
void ActionForceConsumeSingle ()
Definition at line 13 of file ActionForceConsumeSingle.c.
References m_FullBody, m_StanceMask, and m_Text.
Referenced by ActionConstructor::RegisterActions(), Edible_Base::SetActions(), TetracyclineAntibiotics::SetActions(), and VitaminBottle::SetActions().
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 22 of file ActionForceConsumeSingle.c.
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetConsumedQuantity()
int GetConsumedQuantity ()
Definition at line 28 of file ActionForceConsumeSingle.c.
References DEFAULT_CONSUMED_QUANTITY.
Referenced by OnExecuteServer().
OnEndServer()
override void OnEndServer (ActionData action_data)
Definition at line 45 of file ActionForceConsumeSingle.c.
References ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
Definition at line 62 of file ActionForceConsumeSingle.c.
References GetConsumedQuantity(), ActionData::m_MainItem, and ActionData::m_Target.
Variable Documentation
DEFAULT_CONSUMED_QUANTITY
ActionForceConsumeSingleCB DEFAULT_CONSUMED_QUANTITY = 1
Referenced by GetConsumedQuantity().