DayZ: 4_World/Classes/SoundEvents/PlayerSoundEvents/Events/HoldBreathEvents.c File Reference
HoldBreathEvents.c File Reference
Data Structures
class PlayerSoundEventBase
class HoldBreathSoundEventBase
Functions
class HoldBreathSoundEventBase extends PlayerSoundEventBase HoldBreathSoundEvent ()
void HoldBreathSoundEventBase ()
override bool HasHoldBreathException ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
class ExhaustedBreathSoundEvent extends HoldBreathSoundEventBase ReleaseBreathSoundEvent ()
void ExhaustedBreathSoundEvent ()
Function Documentation
ExhaustedBreathSoundEvent()
void ExhaustedBreathSoundEvent ()
Definition at line 53 of file HoldBreathEvents.c.
References m_ID, m_SoundVoiceAnimEventClassID, and m_Type.
Referenced by PlayerSoundEventHandler().
HasHoldBreathException()
override bool HasHoldBreathException ()
Definition at line 24 of file HoldBreathEvents.c.
HasPriorityOverCurrent()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Definition at line 25 of file HoldBreathEvents.c.
HoldBreathSoundEvent()
class HoldBreathSoundEventBase extends PlayerSoundEventBase HoldBreathSoundEvent ()
Definition at line 1 of file HoldBreathEvents.c.
Referenced by PlayerSoundEventHandler().
HoldBreathSoundEventBase()
void HoldBreathSoundEventBase ()
Definition at line 19 of file HoldBreathEvents.c.
References m_ID, m_SoundVoiceAnimEventClassID, and m_Type.
ReleaseBreathSoundEvent()
class ExhaustedBreathSoundEvent extends HoldBreathSoundEventBase ReleaseBreathSoundEvent ()
Definition at line 35 of file HoldBreathEvents.c.
Referenced by PlayerSoundEventHandler().