DayZ: 4_World/Classes/SoundEvents/PlayerSoundEvents/Events/InjuryEvents.c File Reference
InjuryEvents.c File Reference
Data Structures
class PlayerSoundEventBase
class InjurySoundEvents
Functions
class InjurySoundEvents extends PlayerSoundEventBase InjuryLightSoundEvent ()
void InjurySoundEvents ()
override bool CanPlay (PlayerBase player)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
class InjuryMediumSoundEvent extends InjurySoundEvents InjuryHeavySoundEvent ()
void InjuryMediumSoundEvent ()
Function Documentation
CanPlay()
override bool CanPlay (PlayerBase player)
Definition at line 31 of file InjuryEvents.c.
HasPriorityOverCurrent()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Definition at line 36 of file InjuryEvents.c.
InjuryHeavySoundEvent()
class InjuryMediumSoundEvent extends InjurySoundEvents InjuryHeavySoundEvent ()
Definition at line 31 of file InjuryEvents.c.
Referenced by PlayerSoundEventHandler().
InjuryLightSoundEvent()
class InjurySoundEvents extends PlayerSoundEventBase InjuryLightSoundEvent ()
Definition at line 1 of file InjuryEvents.c.
Referenced by PlayerSoundEventHandler().
InjuryMediumSoundEvent()
void InjuryMediumSoundEvent ()
Definition at line 44 of file InjuryEvents.c.
References m_ID, and m_SoundVoiceAnimEventClassID.
Referenced by PlayerSoundEventHandler().
InjurySoundEvents()
void InjurySoundEvents ()
Definition at line 25 of file InjuryEvents.c.