DayZ Scripts Documentation: P:/scripts/4_World/Entities/ItemBase.c File Reference
ItemBase.c File Reference
Data Structures
class ItemBase
class InventoryItem
Typedefs
typedef ItemBase Inventory_Base
Functions
class ItemBase extends InventoryItem SpawnItemOnLocation (string object_name, notnull InventoryLocation loc, bool full_quantity)
void TransferModifiers (PlayerBase reciever)
void ItemBase ()
void InitItemVariables ()
override int GetQuickBarBonus ()
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
void SetActions ()
void AddAction (typename actionName)
void RemoveAction (typename actionName)
void OnItemInHandsPlayerSwimStart (PlayerBase player)
ScriptedLightBase GetLight ()
void LoadParticleConfigOnFire (int id)
void LoadParticleConfigOnOverheating (int id)
float GetOverheatingValue ()
void IncreaseOverheating (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
void CheckOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
bool IsOverheatingEffectActive ()
void OnOverheatingDecay ()
void StartOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void UpdateOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void StopOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void RegisterOverheatingParticle (Particle p, float min_heat_coef, float max_heat_coef, int particle_id, Object parent, vector local_pos, vector local_ori)
float GetOverheatingCoef ()
void UpdateAllOverheatingParticles ()
void KillAllOverheatingParticles ()
float GetInfectionChance (int system=0, Param param=null)
Infection chance while/after using this item, originally used for wound infection after bandaging, params 'system' and 'param' can allow usage by other systems as well.
float GetDisinfectQuantity (int system=0, Param param1=null)
float GetFilterDamageRatio ()
bool HasMuzzle ()
Returns true if this item has a muzzle (weapons, suppressors)
int GetMuzzleID ()
Returns global muzzle ID. If not found, then it gets automatically registered.
int GetDamageSystemVersionChange ()
Re-sets DamageSystem changes.
void ~ItemBase ()
static int GetDebugActionsMask ()
static bool HasDebugActionsMask (int mask)
static void SetDebugActionsMask (int mask)
static void AddDebugActionsMask (int mask)
static void RemoveDebugActionsMask (int mask)
static void ToggleDebugActionsMask (int mask)
void SetCEBasedQuantity ()
void LockToParent ()
Locks this item in it's current attachment slot of its parent. This makes the "locked" icon visible in inventory over this item.
void UnlockFromParent ()
Unlocks this item from its attachment slot of its parent.
override void CombineItemsClient (EntityAI entity2, bool use_stack_max=true)
bool IsLiquidPresent ()
bool IsLiquidContainer ()
bool IsBloodContainer ()
bool IsNVG ()
bool IsExplosive ()
string GetExplosiveTriggerSlotName ()
bool IsLightSource ()
bool CanBeRepairedByCrafting ()
bool IsFacingPlayer (PlayerBase player, string selection)
bool IsPlayerInside (PlayerBase player, string selection)
override bool CanObstruct ()
override bool IsBeingPlaced ()
void SetIsBeingPlaced (bool is_being_placed)
void OnEndPlacement ()
override bool IsHologram ()
bool CanBeDigged ()
bool CanMakeGardenplot ()
void SetIsHologram (bool is_hologram)
override void EECargoIn (EntityAI item)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EOnContact (IEntity other, Contact extra)
void RefreshPhysics ()
override void OnCreatePhysics ()
override void OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void EOnInit (IEntity other, int extra)
override void EEDelete (EntityAI parent)
override void EEKilled (Object killer)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override string ChangeIntoOnAttach (string slot)
override string ChangeIntoOnDetach ()
void ExplodeAmmo ()
void DoAmmoExplosion ()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
bool DamageItemInCargo (float damage)
bool DamageItemAttachments (float damage)
override bool CanBeSplit ()
void SplitIntoStackMaxClient (EntityAI destination_entity, int slot_id)
void SplitIntoStackMax (EntityAI destination_entity, int slot_id, PlayerBase player)
void SplitIntoStackMaxToInventoryLocationClient (notnull InventoryLocation dst)
void SplitIntoStackMaxCargoClient (EntityAI destination_entity, int idx, int row, int col)
void SplitIntoStackMaxToInventoryLocation (notnull InventoryLocation dst)
ItemBase SplitIntoStackMaxToInventoryLocationEx (notnull InventoryLocation dst)
void SplitIntoStackMaxCargo (EntityAI destination_entity, int idx, int row, int col)
void SplitIntoStackMaxHandsClient (PlayerBase player)
void SplitIntoStackMaxHands (PlayerBase player)
void SplitItemToInventoryLocation (notnull InventoryLocation dst)
void SplitItem (PlayerBase player)
void OnQuantityChanged (float delta)
Called on server side when this item's quantity is changed. Call super.OnQuantityChanged(); first when overriding this event.
void OnAttachmentQuantityChanged (ItemBase item)
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
void OnAttachmentQuantityChangedEx (ItemBase item, float delta)
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void OnRightClick ()
override bool CanBeCombined (EntityAI other_item, bool reservation_check=true, bool stack_max_limit=false)
bool IsCombineAll (ItemBase other_item, bool use_stack_max=false)
bool IsResultOfSplit ()
void SetResultOfSplit (bool value)
int ComputeQuantityUsed (ItemBase other_item, bool use_stack_max=true)
float ComputeQuantityUsedEx (ItemBase other_item, bool use_stack_max=true)
void CombineItems (ItemBase other_item, bool use_stack_max=true)
void OnCombine (ItemBase other_item)
void GetRecipesActions (Man player, out TSelectableActionInfoArray outputList)
void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
bool OnAction (int action_id, Man player, ParamsReadContext ctx)
void OnActivatedByTripWire ()
void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
bool CanExplodeInFire ()
bool CanEat ()
override bool IsIgnoredByConstruction ()
bool HasFoodStage ()
bool CanBeCooked ()
bool CanBeCookedOnStick ()
bool CanRepair (ItemBase item_repair_kit)
bool Repair (PlayerBase player, ItemBase item_repair_kit, float specialty_weight)
int GetItemSize ()
bool CanBeMovedOverride ()
void SetCanBeMovedOverride (bool setting)
void MessageToOwnerStatus (string text)
Send message to owner player in grey color.
void MessageToOwnerAction (string text)
Send message to owner player in yellow color.
void MessageToOwnerFriendly (string text)
Send message to owner player in green color.
void MessageToOwnerImportant (string text)
Send message to owner player in red color.
override bool IsItemBase ()
override bool KindOf (string tag)
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
void TransferVariablesFloat (array< float > float_vars)
array< float > GetVariablesFloat ()
int NameToID (string name)
string IDToName (int id)
void OnSyncVariables (ParamsReadContext ctx)
void SerializeNumericalVars (array< float > floats_out)
void DeSerializeNumericalVars (array< float > floats)
void WriteVarsToCTX (ParamsWriteContext ctx)
bool ReadVarsFromCTX (ParamsReadContext ctx, int version=-1)
void SaveVariables (ParamsWriteContext ctx)
bool LoadVariables (ParamsReadContext ctx, int version=-1)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void AfterStoreLoad ()
override void EEOnAfterLoad ()
bool CanBeDisinfected ()
override void OnVariablesSynchronized ()
bool SetQuantity (float value, bool destroy_config=true, bool destroy_forced=false, bool allow_client=false, bool clamp_to_stack_max=true)
Set item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted.
bool AddQuantity (float value, bool destroy_config=true, bool destroy_forced=false)
add item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted
void SetQuantityMax ()
void SetQuantityNormalized (float value, bool destroy_config=true, bool destroy_forced=false)
Sets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, setting 0.5 will result in value 2500)
float GetQuantityNormalized ()
Gets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, value 2500 will result in 0.5)
override int GetQuantityMax ()
override int GetTargetQuantityMax (int attSlotID=-1)
int GetQuantityMin ()
int GetQuantityInit ()
bool HasQuantity ()
override float GetQuantity ()
bool IsFullQuantity ()
float GetSingleInventoryItemWeightEx ()
float GetSingleInventoryItemWeight ()
override protected float GetWeightSpecialized (bool forceRecalc=false)
int GetNumberOfItems ()
Returns the number of items in cargo, otherwise returns 0(non-cargo objects). Recursive.
float GetUnitWeight (bool include_wetness=true)
Obsolete, use GetWeightEx instead.
void SetVariableMask (int variable)
void RemoveItemVariable (int variable)
Removes variable from variable mask, making it appear as though the variable has never been changed from default.
bool IsVariableSet (int variable)
'true' if this variable has ever been changed from default
float GetEnergy ()
override void OnEnergyConsumed ()
override void OnEnergyAdded ()
void ConvertEnergyToQuantity ()
override void SetTemperature (float value, bool allow_client=false)
override void AddTemperature (float value)
override void SetTemperatureMax ()
override float GetTemperature ()
override float GetTemperatureInit ()
override float GetTemperatureMin ()
override float GetTemperatureMax ()
float GetHeatIsolationInit ()
float GetHeatIsolation ()
override void SetWet (float value, bool allow_client=false)
override void AddWet (float value)
override void SetWetMax ()
override float GetWet ()
override float GetWetMax ()
override float GetWetMin ()
override float GetWetInit ()
override void OnWetChanged (float newVal, float oldVal)
override void OnWetLevelChanged (EWetnessLevel newLevel, EWetnessLevel oldLevel)
override EWetnessLevel GetWetLevel ()
bool IsServerCheck (bool allow_client)
float GetItemModelLength ()
void SetCleanness (int value, bool allow_client=false)
bool AllowFoodConsumption ()
int GetLockType ()
string GetLockSoundSet ()
void SetColor (int r, int g, int b, int a)
void GetColor (out int r, out int g, out int b, out int a)
gets item's color variable as components
bool IsColorSet ()
string GetColorString ()
Returns item's PROCEDURAL color as formated string, i.e. "#(argb,8,8,3)color(0.15,0.15,0.15,1.0,CO)".
void SetLiquidType (int value, bool allow_client=false)
int GetLiquidTypeInit ()
int GetLiquidType ()
void OnInventoryEnter (Man player)
Event called on item when it is placed in the player(Man) inventory, passes the owner as a parameter.
void OnInventoryExit (Man player)
Event called on item when it is removed from the player(Man) inventory, passes the old owner as a parameter.
override void OnPlacementStarted (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
bool ContainsAgent (int agent_id)
override void RemoveAgent (int agent_id)
override void RemoveAllAgents ()
override void RemoveAllAgentsExcept (int agents_to_keep_mask)
override void InsertAgent (int agent, float count=1)
void TransferAgents (int agents)
transfer agents from another item
override int GetAgents ()
bool LoadAgents (ParamsReadContext ctx, int version)
void SaveAgents (ParamsWriteContext ctx)
float GetProtectionLevel (int type, bool consider_filter=false, int system=0)
override void EEOnCECreate ()
Called when entity is being created as new by CE/ Debug.
void Open ()
Implementations only.
void Close ()
bool IsOpen ()
override bool CanDisplayCargo ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
static void PlayFireParticles (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void PlayBulletCasingEjectParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void PlayOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void UpdateOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void StopOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
override bool IsHeavyBehaviour ()
override bool IsOneHandedBehaviour ()
override bool IsTwoHandedBehaviour ()
bool IsDeployable ()
float GetDeployTime ()
how long it takes to deploy this item in seconds
override void SetTakeable (bool pState)
override bool IsTakeable ()
protected void PreLoadSoundAttachmentType ()
Attachment Sound Type getting from config file.
override string GetAttachmentSoundType ()
void SoundSynchRemoteReset ()
void SoundSynchRemote ()
bool IsSoundSynchRemote ()
string GetDeploySoundset ()
string GetPlaceSoundset ()
string GetLoopDeploySoundset ()
string GetDeployFinishSoundset ()
void SetIsPlaceSound (bool is_place_sound)
bool IsPlaceSound ()
void SetIsDeploySound (bool is_deploy_sound)
bool IsDeploySound ()
void PlayDeploySound ()
void PlayDeployFinishSound ()
void PlayPlaceSound ()
bool CanPlayDeployLoopSound ()
void PlayAttachSound (string slot_type)
Plays sound on item attach. Be advised, the config structure may slightly change in 1.11 update to allow for more complex use.
void PlayDetachSound (string slot_type)
void OnApply (PlayerBase player)
float GetBandagingEffectivity ()
array< string > GetHeadHidingSelection ()
bool HidesSelectionBySlot ()
WrittenNoteData GetWrittenNoteData ()
void StopItemDynamicPhysics ()
void PerformDamageSystemReinit ()
void SetZoneDamageCEInit ()
Sets zone damages to match randomized global health set by CE (CE spawn only)
bool IsCoverFaceForShave (string slot_name)
void ProcessItemWetness (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
void ProcessItemTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
void ProcessItemWetnessAndTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
void HierarchyCheck (out bool hasParent, out bool hasRootAsPlayer, out ItemBase refParentIB)
protected void ProcessDecay (float delta, bool hasRootAsPlayer)
bool CanDecay ()
protected bool CanProcessDecay ()
protected bool CanHaveWetness ()
protected bool CanHaveTemperature ()
override void OnCEUpdate ()
bool IsCargoException4x3 (EntityAI item)
void CopyScriptPropertiesFrom (EntityAI oldItem)
void AddLightSourceItem (ItemBase lightsource)
Adds a light source child.
void RemoveLightSourceItem ()
ItemBase GetLightSourceItem ()
array< int > GetValidFinishers ()
returns an array of possible finishers
bool GetActionWidgetOverride (out typename name)
If we need a different (handheld)item action widget displayed, the logic goes in here.
RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
Remotely controlled devices helpers.
void SetupSpawnedItem (ItemBase item, float health, float quantity)
Variables
static ref map< typename, ref TInputActionMap > m_ItemTypeActionsMap = new map<typename, ref TInputActionMap>
TInputActionMap m_InputActionMap
bool m_ActionsInitialize
static int m_DebugActionsMask
bool m_RecipesInitialized
int m_VariablesMask
float m_VarQuantity
float m_VarQuantityPrev
int m_VarQuantityInit
int m_VarQuantityMin
int m_VarQuantityMax
int m_Count
float m_VarStackMax
float m_StoreLoadedQuantity = float.LOWEST
float m_VarTemperature
float m_VarTemperatureInit
float m_VarTemperatureMin
float m_VarTemperatureMax
float m_VarWet
float m_VarWetPrev
float m_VarWetInit
float m_VarWetMin
float m_VarWetMax
int m_Cleanness
int m_CleannessInit
int m_CleannessMin
int m_CleannessMax
bool m_WantPlayImpactSound
bool m_CanPlayImpactSound = true
float m_ImpactSpeed
int m_ImpactSoundSurfaceHash
float m_HeatIsolation
float m_ItemModelLength
int m_VarLiquidType
int m_ItemBehaviour = -1
int m_QuickBarBonus = 0
bool m_IsBeingPlaced
bool m_IsHologram
bool m_IsPlaceSound
bool m_IsDeploySound
bool m_IsTakeable
bool m_IsSoundSynchRemote
bool m_ThrowItemOnDrop
bool m_ItemBeingDroppedPhys
bool m_CanBeMovedOverride
bool m_FixDamageSystemInit = false
bool can_this_be_combined = false
bool m_CanThisBeSplit = false
bool m_IsStoreLoad = false
bool m_CanShowQuantity
bool m_HasQuantityBar
protected bool m_CanBeDigged
protected bool m_IsResultOfSplit string m_SoundAttType
distinguish if item has been created as new or it came from splitting (server only flag)
int m_ColorComponentR
int m_ColorComponentG
int m_ColorComponentB
int m_ColorComponentA
ItemBase m_LightSourceItem
ref TIntArray m_SingleUseActions
ref TIntArray m_ContinuousActions
ref TIntArray m_InteractActions
private int m_AttachedAgents
static ref map< int, ref array< ref WeaponParticlesOnFire > > m_OnFireEffect
static ref map< int, ref array< ref WeaponParticlesOnBulletCasingEject > > m_OnBulletCasingEjectEffect
ref map< int, ref array< ref WeaponParticlesOnOverheating > > m_OnOverheatingEffect
static ref map< string, int > m_WeaponTypeToID
static int m_LastRegisteredWeaponID = 0
bool m_IsOverheatingEffectActive
float m_OverheatingShots
ref Timer m_CheckOverheating
int m_ShotsToStartOverheating = 0
int m_MaxOverheatingValue = 0
float m_OverheatingDecayInterval = 1
ref array< ref OverheatingParticle > m_OverheatingParticles
protected ref TStringArray m_HeadHidingSelections
protected bool m_HideSelectionsBySlot
PluginAdminLog m_AdminLog
ref Timer m_PhysDropTimer
ref array< int > m_CompatibleLocks = new array<int>
protected int m_LockType
protected ref EffectSound m_LockingSound
protected string m_LockSoundSet = ""
protected EffectSound m_SoundPlace
protected EffectSound m_SoundDeploy
protected EffectSound m_SoundDeployFinish
Typedef Documentation
Inventory_Base
typedef ItemBase Inventory_Base
Definition at line 1 of file ItemBase.c.
Function Documentation
AddAction()
void AddAction (typename actionName)
Definition at line 4899 of file ItemBase.c.
AddDebugActionsMask()
static void AddDebugActionsMask (int mask) static
Definition at line 5346 of file ItemBase.c.
Referenced by InventoryItem::ToggleDebugActionsMask().
AddLightSourceItem()
void AddLightSourceItem (ItemBase lightsource)
Adds a light source child.
Definition at line 9151 of file ItemBase.c.
AddQuantity()
bool AddQuantity (float value, bool destroy_config = true, bool destroy_forced = false)
add item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted
Definition at line 7851 of file ItemBase.c.
Referenced by InventoryItem::CombineItems(), ItemBase::Consume(), InventoryItem::OnAction(), ItemBase::OnIgnitedTarget(), ItemBase::OnIgnitedTargetFailed(), ItemBase::RemovePlanks(), InventoryItem::SplitIntoStackMax(), InventoryItem::SplitIntoStackMaxCargo(), InventoryItem::SplitIntoStackMaxHands(), InventoryItem::SplitIntoStackMaxToInventoryLocationEx(), InventoryItem::SplitItem(), and InventoryItem::SplitItemToInventoryLocation().
AddTemperature()
override void AddTemperature (float value)
Definition at line 8124 of file ItemBase.c.
Referenced by InventoryItem::OnAction(), and InventoryItem::ProcessItemTemperature().
AddWet()
override void AddWet (float value)
Definition at line 8182 of file ItemBase.c.
Referenced by InventoryItem::OnAction(), FlammableBase::OnWork(), and InventoryItem::ProcessItemWetness().
AfterStoreLoad()
override void AfterStoreLoad ()
Definition at line 7715 of file ItemBase.c.
AllowFoodConsumption()
bool AllowFoodConsumption ()
Definition at line 8273 of file ItemBase.c.
CanBeCombined()
override bool CanBeCombined (EntityAI other_item, bool reservation_check = true, bool stack_max_limit = false)
Definition at line 6558 of file ItemBase.c.
CanBeCooked()
bool CanBeCooked ()
Definition at line 7031 of file ItemBase.c.
CanBeCookedOnStick()
bool CanBeCookedOnStick ()
Definition at line 7036 of file ItemBase.c.
CanBeDigged()
bool CanBeDigged ()
Definition at line 5527 of file ItemBase.c.
CanBeDisinfected()
bool CanBeDisinfected ()
Definition at line 7741 of file ItemBase.c.
CanBeMovedOverride()
bool CanBeMovedOverride ()
Definition at line 7071 of file ItemBase.c.
CanBeRepairedByCrafting()
bool CanBeRepairedByCrafting ()
Definition at line 5484 of file ItemBase.c.
CanBeSplit()
override bool CanBeSplit ()
Definition at line 6103 of file ItemBase.c.
Referenced by InventoryItem::OnRightClick(), InventoryItem::SplitItem(), and InventoryItem::SplitItemToInventoryLocation().
CanDecay()
BrisketSpread Edible_Base CanDecay ()
Definition at line 9083 of file ItemBase.c.
CanDisplayCargo()
override bool CanDisplayCargo ()
Definition at line 8570 of file ItemBase.c.
CanEat()
bool CanEat ()
Definition at line 7012 of file ItemBase.c.
CanExplodeInFire()
bool CanExplodeInFire ()
Definition at line 7006 of file ItemBase.c.
CanHaveTemperature()
protected bool CanHaveTemperature ()
Definition at line 9102 of file ItemBase.c.
CanHaveWetness()
protected bool CanHaveWetness ()
Definition at line 9096 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate().
CanMakeGardenplot()
bool CanMakeGardenplot ()
Definition at line 5532 of file ItemBase.c.
CanObstruct()
override bool CanObstruct ()
Definition at line 5501 of file ItemBase.c.
CanPlayDeployLoopSound()
bool CanPlayDeployLoopSound ()
Definition at line 8899 of file ItemBase.c.
Referenced by ItemBase::OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), and OnVariablesSynchronized().
CanProcessDecay()
override bool CanProcessDecay ()
Definition at line 9089 of file ItemBase.c.
CanPutAsAttachment()
override bool CanPutAsAttachment (EntityAI parent)
Definition at line 8590 of file ItemBase.c.
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent)
Definition at line 8576 of file ItemBase.c.
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
Definition at line 8614 of file ItemBase.c.
CanReceiveItemIntoCargo()
override bool CanReceiveItemIntoCargo (EntityAI item)
Definition at line 8605 of file ItemBase.c.
CanRepair()
bool CanRepair (ItemBase item_repair_kit)
Definition at line 7042 of file ItemBase.c.
ChangeIntoOnAttach()
override string ChangeIntoOnAttach (string slot)
Definition at line 5926 of file ItemBase.c.
ChangeIntoOnDetach()
override string ChangeIntoOnDetach ()
Definition at line 5950 of file ItemBase.c.
CheckOverheating()
void CheckOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "")
Definition at line 5101 of file ItemBase.c.
Referenced by InventoryItem::IncreaseOverheating(), and InventoryItem::OnOverheatingDecay().
Close()
void Close ()
Definition at line 8568 of file ItemBase.c.
Referenced by UIScriptedMenu::Cancel(), UIScriptedMenu::CloseMapMenu(), UIScriptedMenu::GameRespawn(), UIScriptedMenu::GameRetry(), UIScriptedMenu::Leave(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnKeyUp(), UIScriptedMenu::OnMouseButtonUp(), FireplaceBase::OnWasDetached(), UIScriptedMenu::Update(), and UIScriptedMenu::UpdateWarningMenu().
CombineItems()
void CombineItems (ItemBase other_item, bool use_stack_max = true)
Definition at line 6660 of file ItemBase.c.
Referenced by InventoryItem::CombineItemsClient().
CombineItemsClient()
override void CombineItemsClient (EntityAI entity2, bool use_stack_max = true)
Definition at line 5410 of file ItemBase.c.
Referenced by Icon::DropReceivedFromMain(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), HandsContainer::TakeAsAttachment(), and ClosableContainer::TakeAsAttachment().
ComputeQuantityUsed()
int ComputeQuantityUsed (ItemBase other_item, bool use_stack_max = true)
Definition at line 6636 of file ItemBase.c.
Referenced by InventoryItem::IsCombineAll().
ComputeQuantityUsedEx()
float ComputeQuantityUsedEx (ItemBase other_item, bool use_stack_max = true)
Definition at line 6641 of file ItemBase.c.
Referenced by InventoryItem::CombineItems(), and InventoryItem::ComputeQuantityUsed().
ContainsAgent()
bool ContainsAgent (int agent_id)
Definition at line 8404 of file ItemBase.c.
Referenced by InventoryItem::RemoveAgent().
ConvertEnergyToQuantity()
void ConvertEnergyToQuantity ()
Definition at line 8097 of file ItemBase.c.
Referenced by InventoryItem::OnEnergyAdded(), and InventoryItem::OnEnergyConsumed().
CopyScriptPropertiesFrom()
void CopyScriptPropertiesFrom (EntityAI oldItem)
Definition at line 9145 of file ItemBase.c.
DamageItemAttachments()
bool DamageItemAttachments (float damage)
Definition at line 6086 of file ItemBase.c.
Referenced by InventoryItem::EEHitBy().
DamageItemInCargo()
bool DamageItemInCargo (float damage)
Definition at line 6067 of file ItemBase.c.
Referenced by InventoryItem::EEHitBy().
DeSerializeNumericalVars()
void DeSerializeNumericalVars (array< float > floats)
Definition at line 7324 of file ItemBase.c.
Referenced by InventoryItem::ReadVarsFromCTX(), and InventoryItem::TransferVariablesFloat().
DoAmmoExplosion()
void DoAmmoExplosion ()
Definition at line 6002 of file ItemBase.c.
EECargoIn()
override void EECargoIn (EntityAI item)
Definition at line 5577 of file ItemBase.c.
EEDelete()
override void EEDelete (EntityAI parent)
Definition at line 5842 of file ItemBase.c.
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
drops content of container when ruined in fireplace
Definition at line 6458 of file ItemBase.c.
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
Definition at line 6026 of file ItemBase.c.
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
Definition at line 5582 of file ItemBase.c.
EEKilled()
override void EEKilled (Object killer)
item is able to explode in fire
Definition at line 5876 of file ItemBase.c.
EEOnAfterLoad()
override void EEOnAfterLoad ()
Definition at line 7731 of file ItemBase.c.
EEOnCECreate()
override void EEOnCECreate ()
Called when entity is being created as new by CE/ Debug.
Definition at line 8554 of file ItemBase.c.
EOnContact()
override void EOnContact (IEntity other, Contact extra)
Definition at line 5706 of file ItemBase.c.
EOnInit()
override void EOnInit (IEntity other, int extra)
Definition at line 5838 of file ItemBase.c.
ExplodeAmmo()
void ExplodeAmmo ()
Definition at line 5989 of file ItemBase.c.
Referenced by InventoryItem::DoAmmoExplosion(), and InventoryItem::EEKilled().
GetActions()
override void GetActions (typename action_input_type , out array< ActionBase_Basic > actions)
Definition at line 4876 of file ItemBase.c.
GetActionWidgetOverride()
bool GetActionWidgetOverride (out typename name)
If we need a different (handheld)item action widget displayed, the logic goes in here.
Definition at line 9173 of file ItemBase.c.
GetAgents()
override int GetAgents ()
Definition at line 8451 of file ItemBase.c.
Referenced by BakedBeansCan_Opened::CanProcessDecay(), PeachesCan_Opened::CanProcessDecay(), SardinesCan_Opened::CanProcessDecay(), SpaghettiCan_Opened::CanProcessDecay(), TunaCan_Opened::CanProcessDecay(), and Liquid::SetUpNutritionalProfile().
GetAttachmentSoundType()
override string GetAttachmentSoundType ()
Definition at line 8819 of file ItemBase.c.
GetBandagingEffectivity()
float GetBandagingEffectivity ()
Definition at line 8948 of file ItemBase.c.
GetColor()
void GetColor (out int r, out int g, out int b, out int a)
gets item's color variable as components
Definition at line 8303 of file ItemBase.c.
GetColorString()
string GetColorString ()
Returns item's PROCEDURAL color as formated string, i.e. "#(argb,8,8,3)color(0.15,0.15,0.15,1.0,CO)".
Definition at line 8317 of file ItemBase.c.
GetDamageSystemVersionChange()
int GetDamageSystemVersionChange ()
Re-sets DamageSystem changes.
Returns
storage version on which the config changes occured (default -1, to be overriden!)
Note
Significant changes to DamageSystem in item configs have to be re-set by increasing the storage version and overriding this method. Default return is -1 (does nothing).
Definition at line 5293 of file ItemBase.c.
GetDebugActions()
void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
Definition at line 6709 of file ItemBase.c.
GetDebugActionsMask()
static int GetDebugActionsMask () static
Definition at line 5331 of file ItemBase.c.
GetDeployFinishSoundset()
string GetDeployFinishSoundset ()
GetDeploySoundset()
string GetDeploySoundset ()
Definition at line 146 of file LargeTent.c.
GetDeployTime()
float GetDeployTime ()
how long it takes to deploy this item in seconds
Definition at line 8787 of file ItemBase.c.
GetDisinfectQuantity()
float GetDisinfectQuantity (int system = 0, Param param1 = null)
Definition at line 5250 of file ItemBase.c.
GetEnergy()
float GetEnergy ()
Definition at line 8071 of file ItemBase.c.
Referenced by ItemBase::CanAddFuel(), FlammableBase::CanBeIgnitedBy(), BroomBase::CanTransformIntoStick(), InventoryItem::GetWeightSpecialized(), FlammableBase::OnWork(), Chemlight_ColorBase::OnWorkStop(), Roadflare::OnWorkStop(), FlammableBase::OnWorkStop(), and Liquid::SetUpNutritionalProfile().
GetExplosiveTriggerSlotName()
string GetExplosiveTriggerSlotName ()
Definition at line 5472 of file ItemBase.c.
GetFilterDamageRatio()
override float GetFilterDamageRatio ()
Definition at line 5255 of file ItemBase.c.
GetHeadHidingSelection()
array< string > GetHeadHidingSelection ()
Definition at line 8953 of file ItemBase.c.
GetHeatIsolation()
float GetHeatIsolation ()
Definition at line 8158 of file ItemBase.c.
GetHeatIsolationInit()
float GetHeatIsolationInit ()
Definition at line 8154 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
GetInfectionChance()
float GetInfectionChance (int system = 0, Param param = null)
Infection chance while/after using this item, originally used for wound infection after bandaging, params 'system' and 'param' can allow usage by other systems as well.
Definition at line 5244 of file ItemBase.c.
GetItemModelLength()
float GetItemModelLength ()
Definition at line 8250 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
GetItemSize()
int GetItemSize ()
Definition at line 7056 of file ItemBase.c.
GetLight()
ScriptedLightBase GetLight ()
GetLightSourceItem()
ItemBase GetLightSourceItem ()
Definition at line 9161 of file ItemBase.c.
GetLiquidType()
int GetLiquidType ()
Definition at line 8342 of file ItemBase.c.
Referenced by ActionFillBottleBase::ActionCondition(), InventoryItem::IsLiquidPresent(), InventoryItem::OnAction(), and InventoryItem::SetQuantity().
GetLiquidTypeInit()
int GetLiquidTypeInit ()
Definition at line 8337 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
GetLockSoundSet()
string GetLockSoundSet ()
Definition at line 8286 of file ItemBase.c.
GetLockType()
int GetLockType ()
Definition at line 8281 of file ItemBase.c.
GetLoopDeploySoundset()
string GetLoopDeploySoundset ()
Definition at line 151 of file LargeTent.c.
GetMuzzleID()
int GetMuzzleID ()
Returns global muzzle ID. If not found, then it gets automatically registered.
Definition at line 5270 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
GetNumberOfItems()
int GetNumberOfItems ()
Returns the number of items in cargo, otherwise returns 0(non-cargo objects). Recursive.
Definition at line 8010 of file ItemBase.c.
Referenced by Barrel_ColorBase::CanDetachAttachment(), FireplaceBase::CanDetachAttachment(), ClothingBase::CanPutAsAttachment(), Barrel_ColorBase::CanPutInCargo(), Clothing::CanPutInCargo(), Clothing_Base::CanPutInCargoClothingConditions(), and Barrel_ColorBase::CanPutIntoHands().
GetOverheatingCoef()
float GetOverheatingCoef ()
Definition at line 5180 of file ItemBase.c.
Referenced by InventoryItem::UpdateAllOverheatingParticles().
GetOverheatingValue()
float GetOverheatingValue ()
Definition at line 5080 of file ItemBase.c.
GetPlaceSoundset()
string GetPlaceSoundset ()
Definition at line 2649 of file FireplaceBase.c.
GetProtectionLevel()
float GetProtectionLevel (int type, bool consider_filter = false, int system = 0)
Definition at line 8514 of file ItemBase.c.
GetQuantity()
override float GetQuantity ()
Definition at line 7946 of file ItemBase.c.
Referenced by InventoryItem::AddQuantity(), InventoryItem::CanBeCombined(), InventoryItem::CanBeSplit(), ItemBase::CanIgniteItem(), Clothing::CanPutAsAttachment(), ItemBase::CanPutAsAttachment(), InventoryItem::CombineItems(), InventoryItem::ComputeQuantityUsedEx(), Clothing::ConsumeQuantity(), Barrel_ColorBase::DetermineAction(), Clothing::GetFilterQuantity(), Clothing::GetFilterQuantity01(), InventoryItem::GetProtectionLevel(), FlammableBase::GetRagQuantity(), InventoryItem::GetWeightSpecialized(), Clothing::HasValidFilter(), LargeGasCanister::IsDestructionBehaviour(), MediumGasCanister::IsDestructionBehaviour(), SmallGasCanister::IsDestructionBehaviour(), InventoryItem::IsFullQuantity(), ItemBase::RemovePlanks(), ItemBase::SetCEBasedQuantity(), VehicleBattery::SetCEBasedQuantity(), InventoryItem::SplitIntoStackMax(), InventoryItem::SplitIntoStackMaxCargo(), InventoryItem::SplitIntoStackMaxHands(), InventoryItem::SplitIntoStackMaxToInventoryLocationEx(), InventoryItem::SplitItem(), InventoryItem::SplitItemToInventoryLocation(), FlammableBase::UpdateLight(), BroomBase::UpdateParticle(), FlammableBase::UpdateParticle(), and ItemBase::UpdateSelections().
GetQuantityInit()
int GetQuantityInit ()
Definition at line 7929 of file ItemBase.c.
GetQuantityMax()
override int GetQuantityMax ()
Definition at line 7886 of file ItemBase.c.
Referenced by CalcAndSetQuantity(), InventoryItem::CanBeCombined(), Capture(), InventoryItem::ComputeQuantityUsedEx(), Edible_Base::GetDisinfectQuantity(), DisinfectantAlcohol::GetDisinfectQuantity(), IodineTincture::GetDisinfectQuantity(), Clothing::GetFilterQuantity01(), Clothing::GetFilterQuantityMax(), InventoryItem::GetQuantityNormalized(), InventoryItem::HasQuantity(), InventoryItem::IsFullQuantity(), InventoryItem::OnAction(), ItemBase::SetCEBasedQuantity(), VehicleBattery::SetCEBasedQuantity(), InventoryItem::SetQuantity(), InventoryItem::SetQuantityMax(), InventoryItem::SetQuantityNormalized(), BroomBase::UpdateParticle(), and ItemBase::UpdateSelections().
GetQuantityMin()
int GetQuantityMin ()
Definition at line 7924 of file ItemBase.c.
Referenced by InventoryItem::GetQuantityNormalized(), InventoryItem::HasQuantity(), InventoryItem::InitItemVariables(), InventoryItem::OnWasAttached(), InventoryItem::OnWasDetached(), Release(), InventoryItem::SetQuantity(), and InventoryItem::SetQuantityNormalized().
GetQuantityNormalized()
float GetQuantityNormalized ()
Gets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, value 2500 will result in 0.5)
Definition at line 7872 of file ItemBase.c.
GetQuickBarBonus()
override int GetQuickBarBonus ()
Definition at line 4859 of file ItemBase.c.
GetRecipesActions()
void GetRecipesActions (Man player, out TSelectableActionInfoArray outputList)
Definition at line 6688 of file ItemBase.c.
GetRemotelyActivatedItemBehaviour()
RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
Remotely controlled devices helpers.
Definition at line 262 of file RemoteDetonator.c.
GetSingleInventoryItemWeight()
float GetSingleInventoryItemWeight ()
Definition at line 7966 of file ItemBase.c.
GetSingleInventoryItemWeightEx()
float GetSingleInventoryItemWeightEx ()
Definition at line 7957 of file ItemBase.c.
Referenced by InventoryItem::GetSingleInventoryItemWeight(), and InventoryItem::OnAction().
GetTargetQuantityMax()
override int GetTargetQuantityMax (int attSlotID = -1)
Definition at line 7908 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMax(), InventoryItem::SplitIntoStackMaxCargo(), InventoryItem::SplitIntoStackMaxHands(), and InventoryItem::SplitIntoStackMaxToInventoryLocationEx().
GetTemperature()
override float GetTemperature ()
Definition at line 8134 of file ItemBase.c.
Referenced by AddDamageToItemByFireEx(), InventoryItem::AddTemperature(), AddWetnessToFireplace(), CanCookOnStick(), CanDismantleOven(), Cooling(), InventoryItem::DoAmmoExplosion(), InventoryItem::EEKilled(), Heating(), InventoryItem::ProcessItemTemperature(), and RefreshFireState().
GetTemperatureInit()
override float GetTemperatureInit ()
Definition at line 8139 of file ItemBase.c.
GetTemperatureMax()
override float GetTemperatureMax ()
Definition at line 8149 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), and InventoryItem::SetTemperature().
GetTemperatureMin()
override float GetTemperatureMin ()
Definition at line 8144 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::ProcessItemTemperature(), and InventoryItem::SetTemperature().
GetUnitWeight()
float GetUnitWeight (bool include_wetness = true)
Obsolete, use GetWeightEx instead.
Definition at line 8030 of file ItemBase.c.
GetValidFinishers()
array< int > GetValidFinishers ()
returns an array of possible finishers
Definition at line 9167 of file ItemBase.c.
GetVariablesFloat()
array< float > GetVariablesFloat ()
Definition at line 7238 of file ItemBase.c.
GetWeightSpecialized()
override protected float GetWeightSpecialized (bool forceRecalc = false)
Definition at line 7971 of file ItemBase.c.
GetWet()
override float GetWet ()
Definition at line 8192 of file ItemBase.c.
Referenced by InventoryItem::AddWet(), AddWetnessToFireplace(), CanBeIgnitedBy(), ItemBase::CanIgniteItem(), Cooling(), InventoryItem::GetUnitWeight(), Heating(), and StartHeating().
GetWetInit()
override float GetWetInit ()
Definition at line 8207 of file ItemBase.c.
GetWetLevel()
override EWetnessLevel GetWetLevel ()
Definition at line 8227 of file ItemBase.c.
GetWetMax()
override float GetWetMax ()
Definition at line 8197 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::OnAction(), and InventoryItem::SetWet().
GetWetMin()
override float GetWetMin ()
Definition at line 8202 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), and InventoryItem::SetWet().
GetWrittenNoteData()
WrittenNoteData GetWrittenNoteData ()
Definition at line 8963 of file ItemBase.c.
HasDebugActionsMask()
static bool HasDebugActionsMask (int mask) static
Definition at line 5336 of file ItemBase.c.
Referenced by InventoryItem::ToggleDebugActionsMask().
HasFoodStage()
bool HasFoodStage ()
Definition at line 7025 of file ItemBase.c.
Referenced by ItemBase::Edible_Base(), and ItemBase::GetDebugActions().
HasMuzzle()
bool HasMuzzle ()
Returns true if this item has a muzzle (weapons, suppressors)
Definition at line 5261 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
HasQuantity()
bool HasQuantity ()
Definition at line 7934 of file ItemBase.c.
Referenced by ItemBase::CatchSetQuant(), Clothing::ConsumeQuantity(), InventoryItem::ConvertEnergyToQuantity(), CAContinuousMineWood::CreatePrimaryItems(), InventoryItem::EEOnCECreate(), Clothing::GetFilterQuantityMax(), InventoryItem::GetProtectionLevel(), Clothing::HasIntegratedFilter(), InventoryItem::InitItemVariables(), InventoryItem::IsLiquidPresent(), InventoryItem::OnWasAttached(), InventoryItem::OnWasDetached(), and InventoryItem::SetQuantity().
HidesSelectionBySlot()
bool HidesSelectionBySlot ()
Definition at line 8958 of file ItemBase.c.
HierarchyCheck()
void HierarchyCheck (out bool hasParent, out bool hasRootAsPlayer, out ItemBase refParentIB)
Definition at line 9061 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate().
IDToName()
string IDToName (int id)
Definition at line 7251 of file ItemBase.c.
IncreaseOverheating()
void IncreaseOverheating (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
Definition at line 5085 of file ItemBase.c.
Referenced by Weapon::EEFired().
InitializeActions()
void InitializeActions ()
Definition at line 4864 of file ItemBase.c.
InitItemVariables()
void InitItemVariables ()
Definition at line 4780 of file ItemBase.c.
InsertAgent()
override void InsertAgent (int agent, float count = 1)
Definition at line 8436 of file ItemBase.c.
Referenced by Bottle_Base::EEOnCECreate(), Edible_Base::HumanSteakMeat(), InventoryItem::OnAction(), ItemBase::ProcessDecay(), and ManBase::SetBloodyHandsPenalty().
IsBeingPlaced()
override bool IsBeingPlaced ()
Definition at line 5506 of file ItemBase.c.
Referenced by InventoryItem::CanPlayDeployLoopSound(), OnInventoryExit(), ItemBase::OnItemLocationChanged(), Barrel_ColorBase::OnVariablesSynchronized(), and FireplaceBase::OnVariablesSynchronized().
IsBloodContainer()
bool IsBloodContainer ()
Definition at line 5455 of file ItemBase.c.
IsCargoException4x3()
bool IsCargoException4x3 (EntityAI item)
Definition at line 9140 of file ItemBase.c.
Referenced by Bottle_Base::CanLoadItemIntoCargo(), Inventory_Base::CanLoadItemIntoCargo(), Bottle_Base::CanPutInCargo(), Inventory_Base::CanPutInCargo(), Bottle_Base::CanReceiveItemIntoCargo(), and Inventory_Base::CanReceiveItemIntoCargo().
IsColorSet()
bool IsColorSet ()
Definition at line 8311 of file ItemBase.c.
IsCombineAll()
bool IsCombineAll (ItemBase other_item, bool use_stack_max = false)
Definition at line 6621 of file ItemBase.c.
Referenced by InventoryItem::CombineItemsClient().
IsCoverFaceForShave()
bool IsCoverFaceForShave (string slot_name)
Definition at line 8995 of file ItemBase.c.
IsDeployable()
bool IsDeployable ()
Definition at line 8781 of file ItemBase.c.
IsDeploySound()
bool IsDeploySound ()
Definition at line 8867 of file ItemBase.c.
Referenced by ItemBase::OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), and OnVariablesSynchronized().
IsExplosive()
bool IsExplosive ()
explosive
Definition at line 5467 of file ItemBase.c.
IsFacingPlayer()
bool IsFacingPlayer (PlayerBase player, string selection)
Definition at line 5491 of file ItemBase.c.
IsFullQuantity()
bool IsFullQuantity ()
Definition at line 7951 of file ItemBase.c.
Referenced by InventoryItem::CanBeCombined(), and CAContinuousMineWood::CreatePrimaryItems().
IsHeavyBehaviour()
override bool IsHeavyBehaviour ()
Definition at line 8751 of file ItemBase.c.
Referenced by Start().
IsHologram()
override bool IsHologram ()
Definition at line 5522 of file ItemBase.c.
IsIgnoredByConstruction()
override bool IsIgnoredByConstruction ()
Definition at line 7018 of file ItemBase.c.
IsItemBase()
override bool IsItemBase ()
Definition at line 7155 of file ItemBase.c.
IsLightSource()
bool IsLightSource ()
Definition at line 5479 of file ItemBase.c.
IsLiquidContainer()
bool IsLiquidContainer ()
Definition at line 5450 of file ItemBase.c.
Referenced by InventoryItem::GetDebugActions(), and InventoryItem::SetQuantity().
IsLiquidPresent()
bool IsLiquidPresent ()
Definition at line 5444 of file ItemBase.c.
IsNVG()
bool IsNVG ()
Definition at line 5460 of file ItemBase.c.
IsOneHandedBehaviour()
override bool IsOneHandedBehaviour ()
Definition at line 8761 of file ItemBase.c.
IsOpen()
override bool IsOpen ()
Definition at line 8569 of file ItemBase.c.
Referenced by FireplaceBase::CanBeIgnitedBy(), FireplaceBase::CanDisplayAttachmentCategory(), InventoryItem::CanDisplayCargo(), FireplaceBase::CanDisplayCargo(), FireplaceBase::CanExtinguishFire(), FireplaceBase::CanIgniteItem(), FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), FireplaceBase::CanReceiveAttachment(), FireplaceBase::CanReceiveItemIntoCargo(), FireplaceBase::CanReleaseCargo(), FireplaceBase::CanShowSmoke(), FireplaceBase::IsThisIgnitionSuccessful(), FireplaceBase::OnVariablesSynchronized(), and FireplaceBase::UpdateVisualState().
IsOverheatingEffectActive()
bool IsOverheatingEffectActive ()
Definition at line 5118 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating().
IsPlaceSound()
bool IsPlaceSound ()
Definition at line 8857 of file ItemBase.c.
Referenced by Barrel_ColorBase::OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), OnVariablesSynchronized(), and TrapSpawnBase::OnVariablesSynchronized().
IsPlayerInside()
bool IsPlayerInside (PlayerBase player, string selection)
Definition at line 5496 of file ItemBase.c.
IsResultOfSplit()
bool IsResultOfSplit ()
Definition at line 6626 of file ItemBase.c.
Referenced by InventoryItem::EEHealthLevelChanged().
IsServerCheck()
bool IsServerCheck (bool allow_client)
Definition at line 8233 of file ItemBase.c.
Referenced by InventoryItem::SetCleanness(), InventoryItem::SetLiquidType(), InventoryItem::SetQuantity(), InventoryItem::SetTemperature(), and InventoryItem::SetWet().
IsSoundSynchRemote()
bool IsSoundSynchRemote ()
Definition at line 8842 of file ItemBase.c.
Referenced by InventoryItem::CanPlayDeployLoopSound(), Barrel_ColorBase::OnVariablesSynchronized(), FireplaceBase::OnVariablesSynchronized(), and ItemBase::OnVariablesSynchronized().
IsTakeable()
override bool IsTakeable ()
Definition at line 8801 of file ItemBase.c.
IsTwoHandedBehaviour()
override bool IsTwoHandedBehaviour ()
Definition at line 8771 of file ItemBase.c.
IsVariableSet()
bool IsVariableSet (int variable)
'true' if this variable has ever been changed from default
Definition at line 8063 of file ItemBase.c.
Referenced by InventoryItem::IsColorSet(), InventoryItem::SerializeNumericalVars(), and InventoryItem::WriteVarsToCTX().
ItemBase()
void ItemBase ()
Definition at line 4729 of file ItemBase.c.
KillAllOverheatingParticles()
void KillAllOverheatingParticles ()
Definition at line 5216 of file ItemBase.c.
Referenced by InventoryItem::UpdateOverheating().
KindOf()
override bool KindOf (string tag)
Definition at line 7161 of file ItemBase.c.
LoadAgents()
bool LoadAgents (ParamsReadContext ctx, int version)
Definition at line 8498 of file ItemBase.c.
Referenced by InventoryItem::OnStoreLoad().
LoadParticleConfigOnFire()
void LoadParticleConfigOnFire (int id)
Definition at line 4955 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
LoadParticleConfigOnOverheating()
void LoadParticleConfigOnOverheating (int id)
Definition at line 5024 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
LoadVariables()
bool LoadVariables (ParamsReadContext ctx, int version = -1)
Definition at line 7564 of file ItemBase.c.
Referenced by InventoryItem::OnStoreLoad().
LockToParent()
void LockToParent ()
Locks this item in it's current attachment slot of its parent. This makes the "locked" icon visible in inventory over this item.
Definition at line 5385 of file ItemBase.c.
MessageToOwnerAction()
void MessageToOwnerAction (string text)
Send message to owner player in yellow color.
Returns
void
item_stone.MessageToOwnerAction("Some Action Message");
Definition at line 7109 of file ItemBase.c.
MessageToOwnerFriendly()
void MessageToOwnerFriendly (string text)
Send message to owner player in green color.
Returns
void
item_stone.MessageToOwnerFriendly("Some Friendly Message");
Definition at line 7127 of file ItemBase.c.
MessageToOwnerImportant()
void MessageToOwnerImportant (string text)
Send message to owner player in red color.
Returns
void
item_stone.MessageToOwnerImportant("Some Important Message");
Definition at line 7145 of file ItemBase.c.
MessageToOwnerStatus()
void MessageToOwnerStatus (string text)
Send message to owner player in grey color.
Returns
void
item_stone.MessageToOwnerStatus("Some Status Message");
Definition at line 7091 of file ItemBase.c.
NameToID()
int NameToID (string name)
Definition at line 7245 of file ItemBase.c.
OnAction()
bool OnAction (int action_id, Man player, ParamsReadContext ctx)
Definition at line 6778 of file ItemBase.c.
OnActivatedByItem()
void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
Definition at line 295 of file RemoteDetonator.c.
References DeleteThis(), and SetHealth().
OnActivatedByTripWire()
void OnActivatedByTripWire ()
DEPRECATED use OnActivatedByItem below Called when this item is activated from a trip wire that was stepped on.
OnApply()
void OnApply (PlayerBase player)
OnAttachmentQuantityChanged()
void OnAttachmentQuantityChanged (ItemBase item)
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
Definition at line 6447 of file ItemBase.c.
Referenced by InventoryItem::OnAttachmentQuantityChangedEx().
OnAttachmentQuantityChangedEx()
void OnAttachmentQuantityChangedEx (ItemBase item, float delta)
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
Definition at line 6453 of file ItemBase.c.
OnCEUpdate()
override void OnCEUpdate ()
Definition at line 9108 of file ItemBase.c.
OnCombine()
void OnCombine (ItemBase other_item)
OnCreatePhysics()
override void OnCreatePhysics ()
Definition at line 5748 of file ItemBase.c.
OnEndPlacement()
void OnEndPlacement ()
Definition at line 5520 of file ItemBase.c.
OnEnergyAdded()
override void OnEnergyAdded ()
Definition at line 8089 of file ItemBase.c.
OnEnergyConsumed()
override void OnEnergyConsumed ()
Definition at line 8082 of file ItemBase.c.
OnInventoryEnter()
void OnInventoryEnter (Man player)
Event called on item when it is placed in the player(Man) inventory, passes the owner as a parameter.
Definition at line 8349 of file ItemBase.c.
OnInventoryExit()
void OnInventoryExit (Man player)
Event called on item when it is removed from the player(Man) inventory, passes the old owner as a parameter.
Definition at line 8362 of file ItemBase.c.
OnItemAttachmentSlotChanged()
override void OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
Definition at line 5775 of file ItemBase.c.
OnItemInHandsPlayerSwimStart()
void OnItemInHandsPlayerSwimStart (PlayerBase player)
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
Definition at line 5780 of file ItemBase.c.
OnOverheatingDecay()
void OnOverheatingDecay ()
Definition at line 5123 of file ItemBase.c.
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0")
Definition at line 8390 of file ItemBase.c.
OnPlacementStarted()
override void OnPlacementStarted (Man player)
Definition at line 8383 of file ItemBase.c.
OnQuantityChanged()
void OnQuantityChanged (float delta)
Called on server side when this item's quantity is changed. Call super.OnQuantityChanged(); first when overriding this event.
Definition at line 6435 of file ItemBase.c.
Referenced by InventoryItem::SetQuantity().
OnRightClick()
override void OnRightClick ()
Definition at line 6496 of file ItemBase.c.
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
Parameters
rpc_type user defined identification of RPC
ctx read context for params
Definition at line 7181 of file ItemBase.c.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 7607 of file ItemBase.c.
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
Definition at line 7694 of file ItemBase.c.
OnSyncVariables()
void OnSyncVariables (ParamsReadContext ctx)
Definition at line 7257 of file ItemBase.c.
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 7748 of file ItemBase.c.
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id)
Definition at line 5899 of file ItemBase.c.
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id)
Definition at line 5909 of file ItemBase.c.
OnWetChanged()
override void OnWetChanged (float newVal, float oldVal)
Definition at line 8212 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized(), and InventoryItem::SetWet().
OnWetLevelChanged()
override void OnWetLevelChanged (EWetnessLevel newLevel, EWetnessLevel oldLevel)
Definition at line 8222 of file ItemBase.c.
Referenced by InventoryItem::OnWetChanged().
Open()
override void Open ()
Implementations only.
Definition at line 8567 of file ItemBase.c.
Referenced by FireplaceBase::OnWasAttached().
PerformDamageSystemReinit()
void PerformDamageSystemReinit ()
Definition at line 8971 of file ItemBase.c.
Referenced by InventoryItem::AfterStoreLoad().
PlayAttachSound()
void PlayAttachSound (string slot_type)
Plays sound on item attach. Be advised, the config structure may slightly change in 1.11 update to allow for more complex use.
Definition at line 8905 of file ItemBase.c.
Referenced by InventoryItem::OnWasAttached().
PlayBulletCasingEjectParticles()
static void PlayBulletCasingEjectParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) static
Definition at line 8670 of file ItemBase.c.
PlayDeployFinishSound()
void PlayDeployFinishSound ()
Definition at line 8881 of file ItemBase.c.
Referenced by ItemBase::OnVariablesSynchronized().
PlayDeploySound()
void PlayDeploySound ()
Definition at line 8872 of file ItemBase.c.
Referenced by ItemBase::OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), and OnVariablesSynchronized().
PlayDetachSound()
void PlayDetachSound (string slot_type)
Definition at line 8941 of file ItemBase.c.
PlayFireParticles()
static void PlayFireParticles (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) static
Definition at line 8650 of file ItemBase.c.
PlayOverheatingParticles()
static void PlayOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) static
Definition at line 8690 of file ItemBase.c.
PlayPlaceSound()
void PlayPlaceSound ()
Definition at line 8890 of file ItemBase.c.
Referenced by Barrel_ColorBase::OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), OnVariablesSynchronized(), and TrapSpawnBase::OnVariablesSynchronized().
PreLoadSoundAttachmentType()
protected void PreLoadSoundAttachmentType ()
Attachment Sound Type getting from config file.
Definition at line 8807 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
ProcessDecay()
protected void ProcessDecay (float delta, bool hasRootAsPlayer)
Definition at line 9078 of file ItemBase.c.
ProcessItemTemperature()
void ProcessItemTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
Definition at line 9035 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate(), and InventoryItem::ProcessItemWetnessAndTemperature().
ProcessItemWetness()
void ProcessItemWetness (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
Definition at line 9010 of file ItemBase.c.
Referenced by InventoryItem::OnCEUpdate(), and InventoryItem::ProcessItemWetnessAndTemperature().
ProcessItemWetnessAndTemperature()
void ProcessItemWetnessAndTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
Definition at line 9055 of file ItemBase.c.
ReadVarsFromCTX()
bool ReadVarsFromCTX (ParamsReadContext ctx, int version = -1)
Definition at line 7427 of file ItemBase.c.
Referenced by InventoryItem::LoadVariables(), and InventoryItem::OnSyncVariables().
RefreshPhysics()
void RefreshPhysics ()
Definition at line 5743 of file ItemBase.c.
RegisterOverheatingParticle()
void RegisterOverheatingParticle (Particle p, float min_heat_coef, float max_heat_coef, int particle_id, Object parent, vector local_pos, vector local_ori)
Definition at line 5166 of file ItemBase.c.
RemoveAction()
void RemoveAction (typename actionName)
Definition at line 4937 of file ItemBase.c.
RemoveAgent()
override void RemoveAgent (int agent_id)
Definition at line 8417 of file ItemBase.c.
Referenced by InventoryItem::OnAction().
RemoveAllAgents()
override void RemoveAllAgents ()
Definition at line 8426 of file ItemBase.c.
Referenced by InventoryItem::SetQuantity().
RemoveAllAgentsExcept()
override void RemoveAllAgentsExcept (int agents_to_keep_mask)
Definition at line 8431 of file ItemBase.c.
RemoveDebugActionsMask()
static void RemoveDebugActionsMask (int mask) static
Definition at line 5351 of file ItemBase.c.
Referenced by InventoryItem::ToggleDebugActionsMask().
RemoveItemVariable()
void RemoveItemVariable (int variable)
Removes variable from variable mask, making it appear as though the variable has never been changed from default.
Definition at line 8057 of file ItemBase.c.
RemoveLightSourceItem()
void RemoveLightSourceItem ()
Definition at line 9156 of file ItemBase.c.
Repair()
bool Repair (PlayerBase player, ItemBase item_repair_kit, float specialty_weight)
Definition at line 7049 of file ItemBase.c.
SaveAgents()
void SaveAgents (ParamsWriteContext ctx)
Definition at line 8505 of file ItemBase.c.
Referenced by InventoryItem::OnStoreSave().
SaveVariables()
void SaveVariables (ParamsWriteContext ctx)
Definition at line 7541 of file ItemBase.c.
Referenced by InventoryItem::OnStoreSave().
SerializeNumericalVars()
void SerializeNumericalVars (array< float > floats_out)
Definition at line 7284 of file ItemBase.c.
Referenced by InventoryItem::GetVariablesFloat().
SetActions()
void SetActions ()
Definition at line 4887 of file ItemBase.c.
SetCanBeMovedOverride()
void SetCanBeMovedOverride (bool setting)
Definition at line 7078 of file ItemBase.c.
SetCEBasedQuantity()
void SetCEBasedQuantity ()
Definition at line 5369 of file ItemBase.c.
SetCleanness()
void SetCleanness (int value, bool allow_client = false)
Definition at line 8259 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::EEHealthLevelChanged(), ItemBase::OnCombine(), SewingKit::OnCombine(), and InventoryItem::ReadVarsFromCTX().
SetColor()
void SetColor (int r, int g, int b, int a)
Definition at line 8294 of file ItemBase.c.
SetDebugActionsMask()
static void SetDebugActionsMask (int mask) static
Definition at line 5341 of file ItemBase.c.
SetIsBeingPlaced()
void SetIsBeingPlaced (bool is_being_placed)
Definition at line 5511 of file ItemBase.c.
SetIsDeploySound()
void SetIsDeploySound (bool is_deploy_sound)
Definition at line 8862 of file ItemBase.c.
Referenced by ItemBase::OnPlacementComplete(), KitBase::OnPlacementComplete(), Inventory_Base::OnPlacementComplete(), and ItemBase::SpawnCatch().
SetIsHologram()
void SetIsHologram (bool is_hologram)
Definition at line 5537 of file ItemBase.c.
SetIsPlaceSound()
void SetIsPlaceSound (bool is_place_sound)
Definition at line 8852 of file ItemBase.c.
Referenced by Barrel_ColorBase::OnPlacementComplete(), ItemBase::OnPlacementComplete(), OnPlacementComplete(), and TrapSpawnBase::OnPlacementComplete().
SetLiquidType()
void SetLiquidType (int value, bool allow_client = false)
Definition at line 8330 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::OnAction(), and InventoryItem::ReadVarsFromCTX().
SetQuantity()
bool SetQuantity (float value, bool destroy_config = true, bool destroy_forced = false, bool allow_client = false, bool clamp_to_stack_max = true)
Set item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted.
Definition at line 7790 of file ItemBase.c.
Referenced by InventoryItem::AddQuantity(), InventoryItem::AfterStoreLoad(), CalcAndSetQuantity(), Capture(), InventoryItem::DeSerializeNumericalVars(), MaskBase::EEHealthLevelChanged(), GasMask_Filter::EEHealthLevelChanged(), InventoryItem::OnAction(), InventoryItem::ReadVarsFromCTX(), Release(), InventoryItem::SetQuantityMax(), InventoryItem::SetQuantityNormalized(), and InventoryItem::SplitIntoStackMax().
SetQuantityMax()
void SetQuantityMax ()
Definition at line 7856 of file ItemBase.c.
Referenced by InventoryItem::OnAction().
SetQuantityNormalized()
void SetQuantityNormalized (float value, bool destroy_config = true, bool destroy_forced = false)
Sets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, setting 0.5 will result in value 2500)
Definition at line 7863 of file ItemBase.c.
Referenced by FlammableBase::CalculateQuantity(), InventoryItem::ConvertEnergyToQuantity(), and InventoryItem::SetCEBasedQuantity().
SetResultOfSplit()
void SetResultOfSplit (bool value)
Definition at line 6631 of file ItemBase.c.
Referenced by InventoryItem::EEHealthLevelChanged().
SetTakeable()
override void SetTakeable (bool pState)
Definition at line 8795 of file ItemBase.c.
Referenced by Barrel_ColorBase::Close(), FireplaceBase::Close(), Barrel_ColorBase::CloseLoad(), FireplaceBase::CloseLoad(), ImprovisedExplosive::EEHealthLevelChanged(), Plastic_Explosive::EEHealthLevelChanged(), EEItemAttached(), EEItemDetached(), LockServer(), Grenade_Base::OnActivateFinished(), Grenade_Base::OnActivateImmediate(), ImprovisedExplosive::OnDisarmed(), Plastic_Explosive::OnDisarmed(), InventoryItemSuper::OnInventoryExit(), InventoryItem::OnPlacementStarted(), InventoryItemSuper::OnWasAttached(), InventoryItemSuper::OnWasDetached(), Barrel_ColorBase::Open(), FireplaceBase::Open(), Barrel_ColorBase::OpenLoad(), FireplaceBase::OpenLoad(), ItemBase::PlantBase(), ItemBase::SetMountedState(), and UnlockServer().
SetTemperature()
override void SetTemperature (float value, bool allow_client = false)
Definition at line 8109 of file ItemBase.c.
Referenced by InventoryItem::AddTemperature(), InventoryItem::DeSerializeNumericalVars(), ItemBase::OnWork(), Heatpack::OnWork(), Heatpack::OnWorkStart(), InventoryItem::ReadVarsFromCTX(), and InventoryItem::SetTemperatureMax().
SetTemperatureMax()
override void SetTemperatureMax ()
Definition at line 8129 of file ItemBase.c.
SetupSpawnedItem()
void SetupSpawnedItem (ItemBase item, float health, float quantity)
Definition at line 4622 of file ItemBase.c.
Referenced by PluginBase::SetupSpawnedEntity(), PluginBase::SpawnEntityAsAttachment(), and PluginBase::SpawnEntityInInventory().
SetVariableMask()
void SetVariableMask (int variable)
Definition at line 8047 of file ItemBase.c.
Referenced by InventoryItem::SetCleanness(), InventoryItem::SetColor(), InventoryItem::SetLiquidType(), InventoryItem::SetQuantity(), InventoryItem::SetTemperature(), and InventoryItem::SetWet().
SetWet()
override void SetWet (float value, bool allow_client = false)
Definition at line 8163 of file ItemBase.c.
Referenced by InventoryItem::AddWet(), AddWetnessToFireplace(), InventoryItem::DeSerializeNumericalVars(), InventoryItem::ReadVarsFromCTX(), and InventoryItem::SetWetMax().
SetWetMax()
override void SetWetMax ()
Definition at line 8187 of file ItemBase.c.
SetZoneDamageCEInit()
void SetZoneDamageCEInit ()
Sets zone damages to match randomized global health set by CE (CE spawn only)
Definition at line 8983 of file ItemBase.c.
Referenced by InventoryItem::EEOnCECreate().
SoundSynchRemote()
void SoundSynchRemote ()
Definition at line 8835 of file ItemBase.c.
Referenced by Barrel_ColorBase::Close(), FireplaceBase::Close(), ItemBase::OnEndPlacement(), Barrel_ColorBase::Open(), FireplaceBase::Open(), and ItemBase::ToggleAnimation().
SoundSynchRemoteReset()
void SoundSynchRemoteReset ()
Definition at line 8828 of file ItemBase.c.
SpawnItemOnLocation()
class ItemBase extends InventoryItem SpawnItemOnLocation (string object_name, notnull InventoryLocation loc, bool full_quantity)
Definition at line 13 of file ItemBase.c.
Referenced by ManBase::CreateInInventory().
SplitIntoStackMax()
void SplitIntoStackMax (EntityAI destination_entity, int slot_id, PlayerBase player)
Definition at line 6134 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMaxClient().
SplitIntoStackMaxCargo()
void SplitIntoStackMaxCargo (EntityAI destination_entity, int idx, int row, int col)
Definition at line 6293 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMaxCargoClient().
SplitIntoStackMaxCargoClient()
void SplitIntoStackMaxCargoClient (EntityAI destination_entity, int idx, int row, int col)
Definition at line 6232 of file ItemBase.c.
SplitIntoStackMaxClient()
void SplitIntoStackMaxClient (EntityAI destination_entity, int slot_id)
Definition at line 6111 of file ItemBase.c.
SplitIntoStackMaxHands()
void SplitIntoStackMaxHands (PlayerBase player)
Definition at line 6341 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMaxHandsClient().
SplitIntoStackMaxHandsClient()
void SplitIntoStackMaxHandsClient (PlayerBase player)
Definition at line 6317 of file ItemBase.c.
SplitIntoStackMaxToInventoryLocation()
void SplitIntoStackMaxToInventoryLocation (notnull InventoryLocation dst)
Definition at line 6257 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMaxToInventoryLocationClient().
SplitIntoStackMaxToInventoryLocationClient()
void SplitIntoStackMaxToInventoryLocationClient (notnull InventoryLocation dst)
Definition at line 6211 of file ItemBase.c.
SplitIntoStackMaxToInventoryLocationEx()
ItemBase SplitIntoStackMaxToInventoryLocationEx (notnull InventoryLocation dst)
Definition at line 6262 of file ItemBase.c.
Referenced by InventoryItem::SplitIntoStackMaxToInventoryLocation().
SplitItem()
void SplitItem (PlayerBase player)
Definition at line 6399 of file ItemBase.c.
Referenced by InventoryItem::OnRightClick().
SplitItemToInventoryLocation()
void SplitItemToInventoryLocation (notnull InventoryLocation dst)
Definition at line 6366 of file ItemBase.c.
StartOverheating()
void StartOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "")
Definition at line 5147 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating().
StopItemDynamicPhysics()
void StopItemDynamicPhysics ()
Definition at line 8965 of file ItemBase.c.
StopOverheating()
void StopOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "")
Definition at line 5160 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating().
StopOverheatingParticles()
static void StopOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) static
Definition at line 8730 of file ItemBase.c.
ToggleDebugActionsMask()
static void ToggleDebugActionsMask (int mask) static
Definition at line 5356 of file ItemBase.c.
TransferAgents()
void TransferAgents (int agents)
transfer agents from another item
Definition at line 8445 of file ItemBase.c.
TransferModifiers()
void TransferModifiers (PlayerBase reciever)
TransferVariablesFloat()
void TransferVariablesFloat (array< float > float_vars)
Definition at line 7233 of file ItemBase.c.
UnlockFromParent()
void UnlockFromParent ()
Unlocks this item from its attachment slot of its parent.
Definition at line 5398 of file ItemBase.c.
Referenced by ItemBase::DestroyPlant(), InventoryItemSuper::EEHealthLevelChanged(), CarWheel_Ruined::EEHealthLevelChanged(), ItemBase::RemovePlant(), and ItemBase::RemovePlantEx().
UpdateAllOverheatingParticles()
void UpdateAllOverheatingParticles ()
Definition at line 5188 of file ItemBase.c.
Referenced by InventoryItem::UpdateOverheating().
UpdateOverheating()
void UpdateOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "")
Definition at line 5153 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating().
UpdateOverheatingParticles()
static void UpdateOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) static
Definition at line 8710 of file ItemBase.c.
WriteVarsToCTX()
void WriteVarsToCTX (ParamsWriteContext ctx)
Definition at line 7388 of file ItemBase.c.
Referenced by InventoryItem::SaveVariables().
~ItemBase()
void ~ItemBase ()
Definition at line 5299 of file ItemBase.c.
Variable Documentation
can_this_be_combined
bool can_this_be_combined = false
Definition at line 4662 of file ItemBase.c.
Referenced by InventoryItem::CanBeCombined(), InventoryItem::InitItemVariables(), Edible_Base::InitItemVariables(), VitaminBottle::InitItemVariables(), DisinfectantAlcohol::InitItemVariables(), IodineTincture::InitItemVariables(), and ItemBase::InitItemVariables().
m_ActionsInitialize
bool m_ActionsInitialize
Definition at line 4605 of file ItemBase.c.
m_AdminLog
PluginAdminLog m_AdminLog
Definition at line 4713 of file ItemBase.c.
m_AttachedAgents
private int m_AttachedAgents
Definition at line 4687 of file ItemBase.c.
Referenced by InventoryItem::ContainsAgent(), InventoryItem::GetAgents(), InventoryItem::InsertAgent(), InventoryItem::LoadAgents(), InventoryItem::RemoveAgent(), InventoryItem::RemoveAllAgents(), InventoryItem::RemoveAllAgentsExcept(), InventoryItem::SaveAgents(), and InventoryItem::TransferAgents().
m_CanBeDigged
protected bool m_CanBeDigged
Definition at line 4667 of file ItemBase.c.
Referenced by InventoryItem::CanBeDigged(), and InventoryItem::InitItemVariables().
m_CanBeMovedOverride
bool m_CanBeMovedOverride
Definition at line 4660 of file ItemBase.c.
Referenced by InventoryItem::CanBeMovedOverride(), InventoryItem::InitItemVariables(), and InventoryItem::SetCanBeMovedOverride().
m_CanPlayImpactSound
bool m_CanPlayImpactSound = true
Definition at line 4643 of file ItemBase.c.
Referenced by InventoryItem::EOnContact(), and InventoryItem::OnInventoryEnter().
m_CanShowQuantity
bool m_CanShowQuantity
Definition at line 4665 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_CanThisBeSplit
bool m_CanThisBeSplit = false
Definition at line 4663 of file ItemBase.c.
Referenced by InventoryItem::CanBeSplit(), InventoryItem::GetUnitWeight(), InventoryItem::GetWeightSpecialized(), InventoryItem::InitItemVariables(), and InventoryItem::OnVariablesSynchronized().
m_CheckOverheating
ref Timer m_CheckOverheating
Definition at line 4703 of file ItemBase.c.
Referenced by InventoryItem::IncreaseOverheating(), and InventoryItem::OnOverheatingDecay().
m_Cleanness
int m_Cleanness
Definition at line 4637 of file ItemBase.c.
Referenced by InventoryItem::EEHealthLevelChanged(), ItemBase::GetInfectionChance(), Bandana_ColorBase::GetInfectionChance(), SewingKit::GetInfectionChance(), InventoryItem::InitItemVariables(), ItemBase::OnCombine(), SewingKit::OnCombine(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetCleanness(), and InventoryItem::WriteVarsToCTX().
m_CleannessInit
int m_CleannessInit
Definition at line 4638 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_CleannessMax
int m_CleannessMax
Definition at line 4640 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), and InventoryItem::SetCleanness().
m_CleannessMin
int m_CleannessMin
Definition at line 4639 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), and InventoryItem::SetCleanness().
m_ColorComponentA
int m_ColorComponentA
Definition at line 4675 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::GetColor(), InventoryItem::ReadVarsFromCTX(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetColor(), and InventoryItem::WriteVarsToCTX().
m_ColorComponentB
int m_ColorComponentB
Definition at line 4674 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::GetColor(), InventoryItem::ReadVarsFromCTX(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetColor(), and InventoryItem::WriteVarsToCTX().
m_ColorComponentG
int m_ColorComponentG
Definition at line 4673 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::GetColor(), InventoryItem::ReadVarsFromCTX(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetColor(), and InventoryItem::WriteVarsToCTX().
m_ColorComponentR
int m_ColorComponentR
Definition at line 4672 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItem::GetColor(), InventoryItem::ReadVarsFromCTX(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetColor(), and InventoryItem::WriteVarsToCTX().
m_CompatibleLocks
ref array<int> m_CompatibleLocks = new array<int>
Definition at line 4719 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_ContinuousActions
ref TIntArray m_ContinuousActions
Definition at line 4682 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
m_Count
int m_Count
Definition at line 4622 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_DebugActionsMask
int m_DebugActionsMask static
Definition at line 4607 of file ItemBase.c.
m_FixDamageSystemInit
bool m_FixDamageSystemInit = false
Definition at line 4661 of file ItemBase.c.
Referenced by InventoryItem::AfterStoreLoad(), ItemBase::AfterStoreLoad(), ItemBase::EEHealthLevelChanged(), InventoryItem::EEOnAfterLoad(), ItemBase::EEOnAfterLoad(), and InventoryItem::OnStoreLoad().
m_HasQuantityBar
bool m_HasQuantityBar
Definition at line 4666 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_HeadHidingSelections
protected ref TStringArray m_HeadHidingSelections
Definition at line 4709 of file ItemBase.c.
Referenced by InventoryItem::GetHeadHidingSelection(), and InventoryItem::ItemBase().
m_HeatIsolation
float m_HeatIsolation
Definition at line 4647 of file ItemBase.c.
Referenced by InventoryItem::GetHeatIsolation(), and InventoryItem::InitItemVariables().
m_HideSelectionsBySlot
protected bool m_HideSelectionsBySlot
Definition at line 4710 of file ItemBase.c.
Referenced by InventoryItem::HidesSelectionBySlot(), and InventoryItem::ItemBase().
m_ImpactSoundSurfaceHash
int m_ImpactSoundSurfaceHash
Definition at line 4645 of file ItemBase.c.
Referenced by InventoryItem::EOnContact(), and InventoryItem::OnVariablesSynchronized().
m_ImpactSpeed
float m_ImpactSpeed
Definition at line 4644 of file ItemBase.c.
Referenced by InventoryItem::EOnContact(), InventoryItem::InitItemVariables(), and InventoryItem::OnVariablesSynchronized().
m_InputActionMap
TInputActionMap m_InputActionMap
Definition at line 4604 of file ItemBase.c.
m_InteractActions
ref TIntArray m_InteractActions
Definition at line 4683 of file ItemBase.c.
Referenced by EntityAI::Building(), and InventoryItem::ItemBase().
m_IsBeingPlaced
bool m_IsBeingPlaced
Definition at line 4652 of file ItemBase.c.
Referenced by TrapSpawnBase::CanBePlaced(), InventoryItem::InitItemVariables(), InventoryItem::IsBeingPlaced(), and InventoryItem::SetIsBeingPlaced().
m_IsDeploySound
bool m_IsDeploySound
Definition at line 4655 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsDeploySound(), and InventoryItem::SetIsDeploySound().
m_IsHologram
bool m_IsHologram
Definition at line 4653 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsHologram(), and InventoryItem::SetIsHologram().
m_IsOverheatingEffectActive
bool m_IsOverheatingEffectActive
Definition at line 4701 of file ItemBase.c.
Referenced by InventoryItem::IsOverheatingEffectActive(), InventoryItem::StartOverheating(), and InventoryItem::StopOverheating().
m_IsPlaceSound
bool m_IsPlaceSound
Definition at line 4654 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsPlaceSound(), and InventoryItem::SetIsPlaceSound().
m_IsSoundSynchRemote
bool m_IsSoundSynchRemote
Definition at line 4657 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsSoundSynchRemote(), InventoryItem::SoundSynchRemote(), and InventoryItem::SoundSynchRemoteReset().
m_IsStoreLoad
bool m_IsStoreLoad = false
Definition at line 4664 of file ItemBase.c.
Referenced by InventoryItem::DeSerializeNumericalVars(), InventoryItemSuper::OnStoreLoad(), InventoryItem::OnStoreLoad(), and InventoryItem::ReadVarsFromCTX().
m_IsTakeable
bool m_IsTakeable
Definition at line 4656 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsTakeable(), and InventoryItem::SetTakeable().
m_ItemBehaviour
int m_ItemBehaviour = -1
Definition at line 4650 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables(), InventoryItem::IsHeavyBehaviour(), InventoryItem::IsOneHandedBehaviour(), and InventoryItem::IsTwoHandedBehaviour().
m_ItemBeingDroppedPhys
bool m_ItemBeingDroppedPhys
Definition at line 4659 of file ItemBase.c.
Referenced by InventoryItem::OnCreatePhysics(), and InventoryItem::StopItemDynamicPhysics().
m_ItemModelLength
float m_ItemModelLength
Definition at line 4648 of file ItemBase.c.
Referenced by InventoryItem::InitItemVariables().
m_ItemTypeActionsMap
ref map<typename, ref TInputActionMap> m_ItemTypeActionsMap = new map<typename, ref TInputActionMap> static
Definition at line 4603 of file ItemBase.c.
Referenced by InventoryItem::InitializeActions().
m_LastRegisteredWeaponID
int m_LastRegisteredWeaponID = 0 static
Definition at line 4698 of file ItemBase.c.
Referenced by InventoryItem::GetMuzzleID().
m_LightSourceItem
ItemBase m_LightSourceItem
Definition at line 4679 of file ItemBase.c.
Referenced by InventoryItem::AddLightSourceItem(), InventoryItem::GetLightSourceItem(), and InventoryItem::RemoveLightSourceItem().
m_LockingSound
protected ref EffectSound m_LockingSound
Definition at line 4721 of file ItemBase.c.
m_LockSoundSet
protected string m_LockSoundSet = ""
Definition at line 4722 of file ItemBase.c.
Referenced by InventoryItem::GetLockSoundSet(), and InventoryItem::InitItemVariables().
m_LockType
protected int m_LockType
Definition at line 4720 of file ItemBase.c.
Referenced by InventoryItem::GetLockType(), and InventoryItem::InitItemVariables().
m_MaxOverheatingValue
int m_MaxOverheatingValue = 0
Definition at line 4705 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating(), InventoryItem::GetOverheatingCoef(), InventoryItem::IncreaseOverheating(), InventoryItem::LoadParticleConfigOnOverheating(), and InventoryItem::OnOverheatingDecay().
m_OnBulletCasingEjectEffect
ref map<int, ref array<ref WeaponParticlesOnBulletCasingEject> > m_OnBulletCasingEjectEffect static
Definition at line 4695 of file ItemBase.c.
Referenced by InventoryItem::LoadParticleConfigOnFire(), and InventoryItem::PlayBulletCasingEjectParticles().
m_OnFireEffect
ref map<int, ref array<ref WeaponParticlesOnFire> > m_OnFireEffect static
Definition at line 4694 of file ItemBase.c.
Referenced by InventoryItem::LoadParticleConfigOnFire(), and InventoryItem::PlayFireParticles().
m_OnOverheatingEffect
ref map<int, ref array<ref WeaponParticlesOnOverheating> > m_OnOverheatingEffect
Definition at line 4696 of file ItemBase.c.
Referenced by InventoryItem::LoadParticleConfigOnOverheating().
m_OverheatingDecayInterval
float m_OverheatingDecayInterval = 1
Definition at line 4706 of file ItemBase.c.
Referenced by InventoryItem::IncreaseOverheating(), InventoryItem::LoadParticleConfigOnOverheating(), and InventoryItem::OnOverheatingDecay().
m_OverheatingParticles
ref array<ref OverheatingParticle> m_OverheatingParticles
Definition at line 4707 of file ItemBase.c.
Referenced by InventoryItem::KillAllOverheatingParticles(), InventoryItem::RegisterOverheatingParticle(), and InventoryItem::UpdateAllOverheatingParticles().
m_OverheatingShots
float m_OverheatingShots
Definition at line 4702 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating(), InventoryItem::GetOverheatingCoef(), InventoryItem::GetOverheatingValue(), InventoryItem::IncreaseOverheating(), and InventoryItem::OnOverheatingDecay().
m_PhysDropTimer
ref Timer m_PhysDropTimer
Definition at line 4716 of file ItemBase.c.
m_QuickBarBonus
int m_QuickBarBonus = 0
Definition at line 4651 of file ItemBase.c.
Referenced by InventoryItem::GetQuickBarBonus(), ManBase::GetQuickBarBonus(), ManBase::Init(), and InventoryItem::ItemBase().
m_RecipesInitialized
bool m_RecipesInitialized
Definition at line 4608 of file ItemBase.c.
m_ShotsToStartOverheating
int m_ShotsToStartOverheating = 0
Definition at line 4704 of file ItemBase.c.
Referenced by InventoryItem::CheckOverheating(), InventoryItem::GetOverheatingCoef(), InventoryItem::ItemBase(), and InventoryItem::LoadParticleConfigOnOverheating().
m_SingleUseActions
ref TIntArray m_SingleUseActions
Definition at line 4681 of file ItemBase.c.
Referenced by InventoryItem::ItemBase().
m_SoundAttType
protected bool m_IsResultOfSplit string m_SoundAttType
distinguish if item has been created as new or it came from splitting (server only flag)
Definition at line 4670 of file ItemBase.c.
Referenced by InventoryItem::GetAttachmentSoundType(), and InventoryItem::PreLoadSoundAttachmentType().
m_SoundDeploy
protected EffectSound m_SoundDeploy
Definition at line 4725 of file ItemBase.c.
Referenced by InventoryItem::PlayDeploySound().
m_SoundDeployFinish
protected EffectSound m_SoundDeployFinish
Definition at line 4726 of file ItemBase.c.
Referenced by InventoryItem::PlayDeployFinishSound().
m_SoundPlace
protected EffectSound m_SoundPlace
Definition at line 4724 of file ItemBase.c.
Referenced by InventoryItem::PlayPlaceSound().
m_StoreLoadedQuantity
float m_StoreLoadedQuantity = float.LOWEST
Definition at line 4624 of file ItemBase.c.
Referenced by InventoryItem::AfterStoreLoad(), InventoryItem::DeSerializeNumericalVars(), InventoryItem::ReadVarsFromCTX(), and InventoryItem::SetQuantity().
m_ThrowItemOnDrop
bool m_ThrowItemOnDrop
Definition at line 4658 of file ItemBase.c.
Referenced by InventoryItem::EEItemLocationChanged().
m_VariablesMask
int m_VariablesMask
Definition at line 4614 of file ItemBase.c.
Referenced by InventoryItem::IsVariableSet(), InventoryItem::RemoveItemVariable(), InventoryItem::SaveVariables(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetVariableMask(), and InventoryItem::WriteVarsToCTX().
m_VarLiquidType
int m_VarLiquidType
Definition at line 4649 of file ItemBase.c.
Referenced by InventoryItem::GetLiquidType(), InventoryItem::InitItemVariables(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetLiquidType(), and InventoryItem::WriteVarsToCTX().
m_VarQuantity
float m_VarQuantity
Definition at line 4617 of file ItemBase.c.
Referenced by InventoryItem::GetQuantity(), InventoryItem::GetQuantityNormalized(), InventoryItem::InitItemVariables(), InventoryItem::OnVariablesSynchronized(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetQuantity(), and InventoryItem::WriteVarsToCTX().
m_VarQuantityInit
int m_VarQuantityInit
Definition at line 4619 of file ItemBase.c.
Referenced by InventoryItem::GetQuantityInit(), and InventoryItem::InitItemVariables().
m_VarQuantityMax
int m_VarQuantityMax
Definition at line 4621 of file ItemBase.c.
Referenced by InventoryItem::GetQuantityMax(), InventoryItem::GetTargetQuantityMax(), InventoryItem::InitItemVariables(), InventoryItem::OnWasAttached(), and InventoryItem::OnWasDetached().
m_VarQuantityMin
int m_VarQuantityMin
Definition at line 4620 of file ItemBase.c.
Referenced by InventoryItem::GetQuantityMin(), and InventoryItem::InitItemVariables().
m_VarQuantityPrev
float m_VarQuantityPrev
Definition at line 4618 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized().
m_VarStackMax
float m_VarStackMax
Definition at line 4623 of file ItemBase.c.
Referenced by InventoryItem::GetQuantityMax(), InventoryItem::GetTargetQuantityMax(), and InventoryItem::InitItemVariables().
m_VarTemperature
float m_VarTemperature
Definition at line 4626 of file ItemBase.c.
Referenced by InventoryItem::GetTemperature(), InventoryItem::InitItemVariables(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetTemperature(), and InventoryItem::WriteVarsToCTX().
m_VarTemperatureInit
float m_VarTemperatureInit
Definition at line 4627 of file ItemBase.c.
Referenced by InventoryItem::GetTemperatureInit(), and InventoryItem::InitItemVariables().
m_VarTemperatureMax
float m_VarTemperatureMax
Definition at line 4629 of file ItemBase.c.
Referenced by InventoryItem::GetTemperatureMax(), InventoryItem::InitItemVariables(), and InventoryItem::SetTemperatureMax().
m_VarTemperatureMin
float m_VarTemperatureMin
Definition at line 4628 of file ItemBase.c.
Referenced by InventoryItem::GetTemperatureMin(), and InventoryItem::InitItemVariables().
m_VarWet
float m_VarWet
Definition at line 4631 of file ItemBase.c.
Referenced by InventoryItem::GetWet(), InventoryItem::GetWetLevel(), InventoryItem::InitItemVariables(), InventoryItem::OnVariablesSynchronized(), InventoryItem::ProcessItemWetness(), InventoryItem::SerializeNumericalVars(), InventoryItem::SetWet(), and InventoryItem::WriteVarsToCTX().
m_VarWetInit
float m_VarWetInit
Definition at line 4633 of file ItemBase.c.
Referenced by InventoryItem::GetWetInit(), and InventoryItem::InitItemVariables().
m_VarWetMax
float m_VarWetMax
Definition at line 4635 of file ItemBase.c.
Referenced by InventoryItem::GetWetMax(), InventoryItem::InitItemVariables(), InventoryItem::ProcessItemWetness(), and InventoryItem::SetWetMax().
m_VarWetMin
float m_VarWetMin
Definition at line 4634 of file ItemBase.c.
Referenced by InventoryItem::GetWetMin(), InventoryItem::InitItemVariables(), and InventoryItem::ProcessItemWetness().
m_VarWetPrev
float m_VarWetPrev
Definition at line 4632 of file ItemBase.c.
Referenced by InventoryItem::OnVariablesSynchronized().
m_WantPlayImpactSound
bool m_WantPlayImpactSound
Definition at line 4642 of file ItemBase.c.
Referenced by InventoryItem::EOnContact(), InventoryItem::InitItemVariables(), and InventoryItem::OnVariablesSynchronized().
m_WeaponTypeToID
ref map<string, int> m_WeaponTypeToID static
Definition at line 4697 of file ItemBase.c.
Referenced by InventoryItem::GetMuzzleID().