DayZ Scripts Documentation: P:/scripts/3_Game/PPEManager/Requesters/PPERequestPlatformsBase.c File Reference
PPERequestPlatformsBase.c File Reference
Data Structures
class PPERequesterBase
Functions
class PPERequesterBase GetCategoryMask ()
mask for mass-handling methods like 'StopAllEffects'
void PPERequesterBase (int requester_IDX)
void SetRequesterUpdating (bool state)
Has to be set for the requester to be handled.
void Start (Param par=null)
void Stop (Param par=null)
bool IsRequesterRunning ()
void SetRequesterIDX (int idx)
automatically assigned by PPERequesterBank
int GetRequesterIDX ()
Returns requester index.
protected void SetTargetValueBool (int mat_id, int param_idx, bool val, int priority_layer, int operator=PPOperators.SET)
protected void SetTargetValueBoolDefault (int mat_id, int param_idx)
protected void SetTargetValueInt (int mat_id, int param_idx, bool relative, int val, int priority_layer, int operator=PPOperators.SET)
protected void SetTargetValueIntDefault (int mat_id, int param_idx)
protected void SetTargetValueFloat (int mat_id, int param_idx, bool relative, float val, int priority_layer, int operator=PPOperators.ADD_RELATIVE)
protected void SetTargetValueFloatDefault (int mat_id, int param_idx)
protected void SetTargetValueColor (int mat_id, int param_idx, ref array< float > val, int priority_layer, int operator=PPOperators.ADD_RELATIVE)
protected void SetTargetValueColorDefault (int mat_id, int param_idx)
protected void QueueValuesSend ()
Sets this requester to update in the manager.
PPERequestParamDataBase GetRequestData (int mat_id, int param_idx, int type)
returns request data for specific parameter, or creates one if one does not exist in this request yet (singletons)
protected PPERequestParamDataBase PrepareData (int mat_id, int param_idx, int type)
map< int, ref map< int, ref PPERequestParamDataBase > > GetActiveRequestStructure ()
protected void ClearRequesterData ()
protected void SendCurrentValueData (PPERequestParamDataBase data)
void OnUpdate (float delta)
protected void OnStart (Param par=null)
protected void OnStop (Param par=null)
automatically resets all material parameters of this requester to defaults
protected float RelativizeValue (float value, int var_type, int mat_id, int param_id, bool relative)
converts all values used to relative values (if not relative already)
protected void SetDefaultValuesAll ()
Sets all requested values to default, ignoring them in further calculations.
void DbgPrnt (string text)
Variables
protected bool m_IsRunning
protected bool m_ValuesSent
protected int m_IDX
protected bool m_Valid = false
protected ref map< int, ref map< int, ref PPERequestParamDataBase > > m_RequestDataStructure
Function Documentation
ClearRequesterData()
protected void ClearRequesterData ()
Definition at line 757 of file PPERequestPlatformsBase.c.
DbgPrnt()
void DbgPrnt (string text)
Definition at line 857 of file PPERequestPlatformsBase.c.
GetActiveRequestStructure()
map< int, ref map< int, ref PPERequestParamDataBase > > GetActiveRequestStructure ()
Definition at line 752 of file PPERequestPlatformsBase.c.
GetCategoryMask()
int GetCategoryMask ()
mask for mass-handling methods like 'StopAllEffects'
Definition at line 1 of file PPERequestPlatformsBase.c.
GetRequestData()
PPERequestParamDataBase GetRequestData (int mat_id, int param_idx, int type)
returns request data for specific parameter, or creates one if one does not exist in this request yet (singletons)
Definition at line 694 of file PPERequestPlatformsBase.c.
GetRequesterIDX()
int GetRequesterIDX ()
Returns requester index.
Definition at line 498 of file PPERequestPlatformsBase.c.
IsRequesterRunning()
bool IsRequesterRunning ()
Definition at line 486 of file PPERequestPlatformsBase.c.
OnStart()
override protected void OnStart (Param par = null)
Definition at line 787 of file PPERequestPlatformsBase.c.
Referenced by TimerBase::Run(), and Start().
OnStop()
protected void OnStop (Param par = null)
automatically resets all material parameters of this requester to defaults
Definition at line 793 of file PPERequestPlatformsBase.c.
OnUpdate()
void OnUpdate (float delta)
Definition at line 769 of file PPERequestPlatformsBase.c.
PPERequesterBase()
void PPERequesterBase (int requester_IDX)
Definition at line 445 of file PPERequestPlatformsBase.c.
PrepareData()
protected PPERequestParamDataBase PrepareData (int mat_id, int param_idx, int type)
Definition at line 727 of file PPERequestPlatformsBase.c.
QueueValuesSend()
protected void QueueValuesSend ()
Sets this requester to update in the manager.
Definition at line 686 of file PPERequestPlatformsBase.c.
RelativizeValue()
protected float RelativizeValue (float value, int var_type, int mat_id, int param_id, bool relative)
converts all values used to relative values (if not relative already)
Definition at line 801 of file PPERequestPlatformsBase.c.
SendCurrentValueData()
protected void SendCurrentValueData (PPERequestParamDataBase data)
Definition at line 762 of file PPERequestPlatformsBase.c.
SetDefaultValuesAll()
protected void SetDefaultValuesAll ()
Sets all requested values to default, ignoring them in further calculations.
Definition at line 821 of file PPERequestPlatformsBase.c.
SetRequesterIDX()
void SetRequesterIDX (int idx)
automatically assigned by PPERequesterBank
Definition at line 492 of file PPERequestPlatformsBase.c.
SetRequesterUpdating()
void SetRequesterUpdating (bool state)
Has to be set for the requester to be handled.
Definition at line 456 of file PPERequestPlatformsBase.c.
SetTargetValueBool()
protected void SetTargetValueBool (int mat_id, int param_idx, bool val, int priority_layer, int operator = PPOperators.SET)
Definition at line 511 of file PPERequestPlatformsBase.c.
Referenced by PPERequester_GameplayBase::SetValuesIronsights().
SetTargetValueBoolDefault()
protected void SetTargetValueBoolDefault (int mat_id, int param_idx)
Definition at line 533 of file PPERequestPlatformsBase.c.
Referenced by PPERequester_GameplayBase::SetValuesOptics().
SetTargetValueColor()
protected void SetTargetValueColor (int mat_id, int param_idx, ref array< float > val, int priority_layer, int operator = PPOperators.ADD_RELATIVE)
Definition at line 630 of file PPERequestPlatformsBase.c.
Referenced by PPERequester_GameplayBase::OnStart(), PPERequester_GameplayBase::OnUpdate(), PPERequester_GameplayBase::SetFlashbangIntensity(), PPERequester_GameplayBase::SetHitIntensity(), PPERequester_GameplayBase::SetNVMode(), and PPERequester_MenuBase::SetVignetteIntensity().
SetTargetValueColorDefault()
protected void SetTargetValueColorDefault (int mat_id, int param_idx)
Definition at line 654 of file PPERequestPlatformsBase.c.
SetTargetValueFloat()
protected void SetTargetValueFloat (int mat_id, int param_idx, bool relative, float val, int priority_layer, int operator = PPOperators.ADD_RELATIVE)
Definition at line 588 of file PPERequestPlatformsBase.c.
Referenced by PPERequester_GameplayBase::OnStart(), PPERequester_MenuBase::OnStart(), PPERequester_GameplayBase::OnUpdate(), PPERequester_GameplayBase::SetBloodLossLevel(), PPERequester_MenuBase::SetBlurIntensity(), PPERequester_GameplayBase::SetEyeAccommodation(), PPERequester_GameplayBase::SetFeverIntensity(), PPERequester_GameplayBase::SetFlashbangIntensity(), PPERequester_GameplayBase::SetHitIntensity(), PPERequester_GameplayBase::SetNVMode(), PPERequester_GameplayBase::SetRadialBlur(), PPERequester_GameplayBase::SetValuesIronsights(), PPERequester_GameplayBase::SetValuesOptics(), and PPERequester_MenuBase::SetVignetteIntensity().
SetTargetValueFloatDefault()
protected void SetTargetValueFloatDefault (int mat_id, int param_idx)
Definition at line 611 of file PPERequestPlatformsBase.c.
Referenced by PPERequester_GameplayBase::SetNVMode(), and PPERequester_GameplayBase::SetValuesIronsights().
SetTargetValueInt()
protected void SetTargetValueInt (int mat_id, int param_idx, bool relative, int val, int priority_layer, int operator = PPOperators.SET)
Definition at line 550 of file PPERequestPlatformsBase.c.
SetTargetValueIntDefault()
protected void SetTargetValueIntDefault (int mat_id, int param_idx)
Definition at line 571 of file PPERequestPlatformsBase.c.
Start()
void Start (Param par = null)
Definition at line 471 of file PPERequestPlatformsBase.c.
Stop()
void Stop (Param par = null)
Definition at line 477 of file PPERequestPlatformsBase.c.
Variable Documentation
m_IDX
protected int m_IDX
Definition at line 439 of file PPERequestPlatformsBase.c.
m_IsRunning
protected bool m_IsRunning
Definition at line 437 of file PPERequestPlatformsBase.c.
Referenced by PPERequester_GameplayBase::OnStart(), PPERequester_GameplayBase::OnUpdate(), PPERequester_GameplayBase::SetUndergroundExposureCoef(), Managed::StartRunningDrops(), Managed::StopIndicator(), and Managed::Update().
m_RequestDataStructure
protected ref map<int,ref map<int,ref PPERequestParamDataBase> > m_RequestDataStructure
Definition at line 443 of file PPERequestPlatformsBase.c.
m_Valid
protected bool m_Valid = false
Definition at line 441 of file PPERequestPlatformsBase.c.
m_ValuesSent
protected bool m_ValuesSent
Definition at line 438 of file PPERequestPlatformsBase.c.