DayZ: StaminaConsumers Class Reference
StaminaConsumers Class Reference
Private Member Functions
void StaminaConsumers ()
void RegisterConsumer (EStaminaConsumers consumer, float threshold, float depletion_threshold=-1)
bool HasEnoughStaminaFor (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap)
bool HasEnoughStaminaToStart (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap)
Private Attributes
protected ref map< EStaminaConsumers, ref StaminaConsumer > m_StaminaConsumers
Detailed Description
Definition at line 39 of file StaminaHandler.c.
Constructor & Destructor Documentation
StaminaConsumers()
void StaminaConsumers () inline private
Definition at line 43 of file StaminaHandler.c.
References m_StaminaConsumers.
Member Function Documentation
HasEnoughStaminaFor()
bool HasEnoughStaminaFor (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap) inline private
Definition at line 63 of file StaminaHandler.c.
References m_StaminaConsumers, and StaminaConsumer().
HasEnoughStaminaToStart()
bool HasEnoughStaminaToStart (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap) inline private
Definition at line 104 of file StaminaHandler.c.
References m_StaminaConsumers, and StaminaConsumer().
RegisterConsumer()
void RegisterConsumer (EStaminaConsumers consumer, float threshold, float depletion_threshold = -1) inline private
init of StaminaConsumer - threshold, state
Definition at line 48 of file StaminaHandler.c.
References m_StaminaConsumers, and StaminaConsumer().
Field Documentation
m_StaminaConsumers
protected ref map<EStaminaConsumers, ref StaminaConsumer> m_StaminaConsumers private
Definition at line 41 of file StaminaHandler.c.
Referenced by HasEnoughStaminaFor(), HasEnoughStaminaToStart(), RegisterConsumer(), and StaminaConsumers().
The documentation for this class was generated from the following file:
4_World/Classes/StaminaHandler.c