DayZ: UniversalTemperatureSourceLambdaBase Class Reference
UniversalTemperatureSourceLambdaBase Class Reference
Private Member Functions
void UniversalTemperatureSourceLambdaBase ()
void ~UniversalTemperatureSourceLambdaBase ()
void Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues)
void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings)
Private Attributes
const float HEAT_THROUGH_AIR_COEF = 0.003
Detailed Description
Definition at line 1 of file UniversalTemperatureSourceLambdaBase.c.
Constructor & Destructor Documentation
UniversalTemperatureSourceLambdaBase()
void UniversalTemperatureSourceLambdaBase () inline private
Definition at line 5 of file UniversalTemperatureSourceLambdaBase.c.
~UniversalTemperatureSourceLambdaBase()
void ~UniversalTemperatureSourceLambdaBase () inline private
Definition at line 6 of file UniversalTemperatureSourceLambdaBase.c.
Member Function Documentation
DryItemsInVicinity()
void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings) inline private
heat transfer to items (no in player possession)
drying of items around the fireplace (based on distance)
Definition at line 10 of file UniversalTemperatureSourceLambdaBase.c.
References Math::Clamp(), vector::Distance(), GetGame(), CGame::GetObjectsAtPosition(), HEAT_THROUGH_AIR_COEF, UniversalTemperatureSourceSettings::m_Parent, UniversalTemperatureSourceSettings::m_Position, UniversalTemperatureSourceSettings::m_RangeMax, and Math::Max().
Referenced by UniversalTemperatureSourceLambdaFireplace::Execute().
Execute()
void Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues) inline private
Definition at line 8 of file UniversalTemperatureSourceLambdaBase.c.
Referenced by UniversalTemperatureSourceDebug::Update().
Field Documentation
HEAT_THROUGH_AIR_COEF
const float HEAT_THROUGH_AIR_COEF = 0.003 private
Definition at line 3 of file UniversalTemperatureSourceLambdaBase.c.
Referenced by DryItemsInVicinity().
The documentation for this class was generated from the following file:
3_Game/Systems/UniversalTemperatureSource/UniversalTemperatureSourceLambdaBase.c