DayZ: ActionBuildPartSwitch Class Reference
ActionBuildPartSwitch Class Reference
Private Member Functions
void ActionBuildPartSwitch ()
override void CreateConditionComponents ()
override bool IsInstant ()
override bool RemoveForceTargetAfterUse ()
override bool UseAcknowledgment ()
override bool CanBeUsedLeaning ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
void SetNextIndex (ActionData action_data)
Detailed Description
Definition at line 2 of file ActionBuildPartSwitch.c.
Constructor & Destructor Documentation
ActionBuildPartSwitch()
void ActionBuildPartSwitch () inline private
Definition at line 4 of file ActionBuildPartSwitch.c.
References m_FullBody, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 38 of file ActionBuildPartSwitch.c.
CanBeUsedLeaning()
override bool CanBeUsedLeaning () inline private
Definition at line 33 of file ActionBuildPartSwitch.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 12 of file ActionBuildPartSwitch.c.
References UAMaxDistances::BASEBUILDING, m_ConditionItem, and m_ConditionTarget.
IsInstant()
override bool IsInstant () inline private
Definition at line 18 of file ActionBuildPartSwitch.c.
OnStartClient()
override void OnStartClient (ActionData action_data) inline private
Definition at line 44 of file ActionBuildPartSwitch.c.
References SetNextIndex().
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
Definition at line 51 of file ActionBuildPartSwitch.c.
References GetGame(), and SetNextIndex().
RemoveForceTargetAfterUse()
override bool RemoveForceTargetAfterUse () inline private
Definition at line 23 of file ActionBuildPartSwitch.c.
SetNextIndex()
void SetNextIndex (ActionData action_data) inline private
Definition at line 59 of file ActionBuildPartSwitch.c.
References ActionData::m_Player, and ConstructionActionData::SetNextIndex().
Referenced by OnStartClient(), and OnStartServer().
UseAcknowledgment()
override bool UseAcknowledgment () inline private
Definition at line 28 of file ActionBuildPartSwitch.c.
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionBuildPartSwitch.c