DayZ Scripts: ActionCarDoors Class Reference
ActionCarDoors Class Reference
Private Member Functions
void ActionCarDoors ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnEnd (ActionData action_data)
override bool CanBeUsedInVehicle ()
protected void FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3)
protected void FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1)
Private Attributes
protected int m_CommandUIDPerCrewIdx [4]
protected bool m_IsOpening = true
CarScript m_Car = null
string m_AnimSource = ""
Detailed Description
Definition at line 1 of file ActionCarDoors.c.
Constructor & Destructor Documentation
ActionCarDoors()
void ActionCarDoors () inline private
Definition at line 10 of file ActionCarDoors.c.
References AnimatedActionBase::m_CommandUID, m_LockTargetOnUse, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
player inside vehicle
crewIdx sanity checks and see if there is a door
see if door is in reach
Definition at line 23 of file ActionCarDoors.c.
References CarScript::CanReachDoorsFromSeat(), Class::CastTo(), CarScript::GetAnimSourceFromSelection(), CarScript::GetCarDoorsState(), CarScript::GetDoorInvSlotNameFromSeatPos(), CarScript::GetDoorSelectionNameFromSeatPos(), AnimatedActionBase::m_CommandUID, m_CommandUIDPerCrewIdx, and m_IsOpening.
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle () inline private
Definition at line 116 of file ActionCarDoors.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 17 of file ActionCarDoors.c.
References m_ConditionItem, and m_ConditionTarget.
FillCommandUIDPerCrewIdx() [1/2]
protected void FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3) inline private
Definition at line 121 of file ActionCarDoors.c.
References m_CommandUIDPerCrewIdx.
Referenced by ActionCloseCarDoors::ActionCloseCarDoors(), ActionOpenCarDoors::ActionOpenCarDoors(), and FillCommandUIDPerCrewIdx().
FillCommandUIDPerCrewIdx() [2/2]
protected void FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1) inline private
Definition at line 129 of file ActionCarDoors.c.
References FillCommandUIDPerCrewIdx().
OnEnd()
override void OnEnd (ActionData action_data) inline private
Definition at line 108 of file ActionCarDoors.c.
References Error(), string::Length(), m_AnimSource, and m_Car.
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
Definition at line 93 of file ActionCarDoors.c.
References ActionData::m_Player.
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
Definition at line 59 of file ActionCarDoors.c.
References CarScript::GetAnimSourceFromSelection(), CarScript::GetDoorSelectionNameFromSeatPos(), m_IsOpening, and ActionData::m_Player.
Field Documentation
m_AnimSource
string m_AnimSource = "" private
Definition at line 7 of file ActionCarDoors.c.
Referenced by OnEnd().
m_Car
CarScript m_Car = null private
Definition at line 6 of file ActionCarDoors.c.
Referenced by OnEnd().
m_CommandUIDPerCrewIdx
protected int m_CommandUIDPerCrewIdx[4] private
Definition at line 3 of file ActionCarDoors.c.
Referenced by ActionCondition(), and FillCommandUIDPerCrewIdx().
m_IsOpening
protected bool m_IsOpening = true private
Definition at line 4 of file ActionCarDoors.c.
Referenced by ActionCloseCarDoors::ActionCloseCarDoors(), ActionCondition(), ActionOpenCarDoors::ActionOpenCarDoors(), and OnStartServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/Vehicles/ActionCarDoors.c