DayZ Scripts Documentation: Grenade_Base Class Reference
Grenade_Base Class Reference
Private Member Functions
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
void FlashGrenade ()
protected override void CreateLight ()
void ~FlashGrenade ()
void M67Grenade ()
void ~M67Grenade ()
void RGD5Grenade ()
void ~RGD5Grenade ()
void Pin ()
void Unpin ()
override void OnActivatedByTripWire ()
DEPRECATED use OnActivatedByItem.
override void OnActivatedByItem (notnull ItemBase item)
bool IsPinned ()
bool IsPinnable ()
void ActivateImmediate ()
void ActivateRandomTime ()
void SetPinnable (bool state)
void SetFuseDelay (float delay)
void SetGrenadeType (EGrenadeType type)
EGrenadeType GetGrenadeType ()
protected void Activate ()
protected void Deactivate ()
protected override void InitiateExplosion ()
protected void ExplodeGrenade (EGrenadeType grenade_type)
DEPRECATED - for backward compatibility only.
protected void OnPin ()
protected void OnUnpin ()
protected void OnActivateStarted ()
protected void OnActivateFinished ()
protected void OnActivateImmediate ()
protected void OnDeactivate ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool CanBeArmed ()
override bool CanBeDisarmed ()
override bool CanExplodeInFire ()
override void SetActions ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnWasAttached (EntityAI parent, int slot_id)
void Grenade_Base ()
Private Attributes
const float FX_RANGE_MAX_MULT = 1.0
protected const float DEFAULT_FUSE_DELAY = 10
protected ref Timer m_FuseTimer
protected float m_FuseDelay
protected float m_RemainingFuseTime
protected bool m_Pinned
protected bool m_Pinnable
protected EGrenadeType m_GrenadeType
Detailed Description
Definition at line 1 of file FlashGrenade.c.
Constructor & Destructor Documentation
~FlashGrenade()
void ~FlashGrenade () inline private
Definition at line 92 of file FlashGrenade.c.
~M67Grenade()
void ~M67Grenade () inline private
Definition at line 10 of file M67Grenade.c.
~RGD5Grenade()
void ~RGD5Grenade () inline private
Definition at line 10 of file RGD5Grenade.c.
Grenade_Base()
void Grenade_Base () inline private
Definition at line 294 of file Grenade_Base.c.
References DEFAULT_FUSE_DELAY, m_FuseTimer, m_Pinned, m_RemainingFuseTime, SetFuseDelay(), SetGrenadeType(), and SetPinnable().
Member Function Documentation
Activate()
protected void Activate () inline private
run only the remaining part (already unpinned and pinned)
Definition at line 122 of file Grenade_Base.c.
References m_FuseDelay, m_FuseTimer, and m_RemainingFuseTime.
Referenced by EEItemLocationChanged().
ActivateImmediate()
void ActivateImmediate () inline private
Definition at line 90 of file Grenade_Base.c.
References OnActivateImmediate().
Referenced by ActivateRandomTime().
ActivateRandomTime()
void ActivateRandomTime () inline private
to millis
Definition at line 95 of file Grenade_Base.c.
References ActivateImmediate(), CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and Math::RandomFloat().
CanBeArmed()
override bool CanBeArmed () inline private
Definition at line 250 of file Grenade_Base.c.
CanBeDisarmed()
override bool CanBeDisarmed () inline private
Definition at line 255 of file Grenade_Base.c.
CanExplodeInFire()
override bool CanExplodeInFire () inline private
Definition at line 260 of file Grenade_Base.c.
CreateLight()
protected override void CreateLight () inline private
Definition at line 87 of file FlashGrenade.c.
References FlashGrenadeLight(), GetPosition, and m_Light.
Deactivate()
protected void Deactivate () inline private
Definition at line 141 of file Grenade_Base.c.
References m_FuseTimer, m_RemainingFuseTime, OnDeactivate(), and Timer::Stop().
Referenced by OnPin(), and OnWasAttached().
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
activate grenade when it leaves player hands (safety handle released)
Definition at line 273 of file Grenade_Base.c.
References Activate(), and IsPinned().
ExplodeGrenade()
protected void ExplodeGrenade (EGrenadeType grenade_type) inline private
DEPRECATED - for backward compatibility only.
Definition at line 171 of file Grenade_Base.c.
References InitiateExplosion().
FlashGrenade()
void FlashGrenade () inline private
Definition at line 79 of file FlashGrenade.c.
References ParticleList::GRENADE_M84, SetAmmoType(), SetFuseDelay(), SetGrenadeType(), and SetParticleExplosion().
GetGrenadeType()
EGrenadeType GetGrenadeType () inline private
Definition at line 117 of file Grenade_Base.c.
References m_GrenadeType.
Referenced by InitiateExplosion().
InitiateExplosion()
protected override void InitiateExplosion () inline private
Definition at line 151 of file Grenade_Base.c.
References Explode(), GetGrenadeType(), m_AmmoTypes, and OnExplode().
Referenced by ExplodeGrenade().
IsPinnable()
bool IsPinnable () inline private
cannot be pinned once the fuse has started
Definition at line 79 of file Grenade_Base.c.
References m_FuseTimer, and m_Pinnable.
Referenced by ActionSingleUseBase::ActionCondition().
IsPinned()
bool IsPinned () inline private
Definition at line 74 of file Grenade_Base.c.
References m_Pinned.
Referenced by ActionSingleUseBase::ActionCondition(), and EEItemLocationChanged().
M67Grenade()
void M67Grenade () inline private
Definition at line 3 of file M67Grenade.c.
References ParticleList::M67, SetAmmoType(), SetFuseDelay(), and SetParticleExplosion().
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 63 of file Grenade_Base.c.
References OnActivateFinished(), and Unpin().
OnActivatedByTripWire()
override void OnActivatedByTripWire () private
DEPRECATED use OnActivatedByItem.
OnActivateFinished()
protected void OnActivateFinished () inline private
Definition at line 201 of file Grenade_Base.c.
References GetGame(), SetHealth(), and SetTakeable().
Referenced by Grenade_ChemGas::EOnContact(), and OnActivatedByItem().
OnActivateImmediate()
protected void OnActivateImmediate () inline private
Definition at line 210 of file Grenade_Base.c.
References GetGame(), SetHealth(), and SetTakeable().
Referenced by ActivateImmediate().
OnActivateStarted()
protected void OnActivateStarted () private
Referenced by OnUnpin().
OnDeactivate()
protected void OnDeactivate () private
Referenced by Deactivate().
OnExplosionEffects()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) inline private
values less than 1.0 make no sense
removes possible obstacles made by items around the grenade(or on the same position)
Definition at line 5 of file FlashGrenade.c.
References Math::Clamp(), ConfigGetFloat(), CGame::ConfigGetFloat(), ConfigIsExisting(), vector::Distance(), vector::DistanceSq(), RaycastRVParams::flags, GetGame(), GetPlayer(), MAX, DayZPhysics::RaycastRVProxy(), and Math::SqrFloat().
OnPin()
protected void OnPin () inline private
Definition at line 176 of file Grenade_Base.c.
References Deactivate(), GetGame(), and m_Pinned.
Referenced by Pin().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 231 of file Grenade_Base.c.
References m_Pinned, and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 221 of file Grenade_Base.c.
References GetGame(), m_Pinned, and Serializer::Write().
OnUnpin()
protected void OnUnpin () inline private
Definition at line 188 of file Grenade_Base.c.
References GetGame(), m_Pinned, and OnActivateStarted().
Referenced by Unpin().
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 284 of file Grenade_Base.c.
References Deactivate().
Pin()
void Pin () inline private
Definition at line 44 of file Grenade_Base.c.
References m_Pinnable, m_Pinned, and OnPin().
Referenced by ActionSingleUseBase::OnExecute().
RGD5Grenade()
void RGD5Grenade () inline private
Definition at line 3 of file RGD5Grenade.c.
References ParticleList::RGD5, SetAmmoType(), SetFuseDelay(), and SetParticleExplosion().
SetActions()
override void SetActions () inline private
Definition at line 265 of file Grenade_Base.c.
References AddAction().
SetFuseDelay()
void SetFuseDelay (float delay) inline private
Definition at line 107 of file Grenade_Base.c.
References m_FuseDelay.
Referenced by FlashGrenade(), Grenade_Base(), M67Grenade(), and RGD5Grenade().
SetGrenadeType()
void SetGrenadeType (EGrenadeType type) inline private
Definition at line 112 of file Grenade_Base.c.
References m_GrenadeType.
Referenced by FlashGrenade(), Grenade_Base(), and Grenade_ChemGas::Grenade_ChemGas().
SetPinnable()
void SetPinnable (bool state) inline private
Definition at line 102 of file Grenade_Base.c.
References m_Pinnable.
Referenced by Grenade_Base(), and Grenade_ChemGas::Grenade_ChemGas().
Unpin()
void Unpin () inline private
Definition at line 52 of file Grenade_Base.c.
References m_Pinned, and OnUnpin().
Referenced by OnActivatedByItem(), and ActionSingleUseBase::OnExecute().
Field Documentation
DEFAULT_FUSE_DELAY
protected const float DEFAULT_FUSE_DELAY = 10 private
Definition at line 32 of file Grenade_Base.c.
Referenced by Grenade_Base().
FX_RANGE_MAX_MULT
const float FX_RANGE_MAX_MULT = 1.0 private
Definition at line 3 of file FlashGrenade.c.
m_FuseDelay
protected float m_FuseDelay private
Definition at line 35 of file Grenade_Base.c.
Referenced by Activate(), and SetFuseDelay().
m_FuseTimer
protected ref Timer m_FuseTimer private
Definition at line 34 of file Grenade_Base.c.
Referenced by Activate(), Deactivate(), Grenade_Base(), and IsPinnable().
m_GrenadeType
protected EGrenadeType m_GrenadeType private
Definition at line 42 of file Grenade_Base.c.
Referenced by GetGrenadeType(), and SetGrenadeType().
m_Pinnable
protected bool m_Pinnable private
Definition at line 39 of file Grenade_Base.c.
Referenced by IsPinnable(), Pin(), and SetPinnable().
m_Pinned
protected bool m_Pinned private
Definition at line 38 of file Grenade_Base.c.
Referenced by Grenade_Base(), Grenade_ChemGas::Grenade_ChemGas(), IsPinned(), OnPin(), OnStoreLoad(), OnStoreSave(), OnUnpin(), Pin(), and Unpin().
m_RemainingFuseTime
protected float m_RemainingFuseTime private
Definition at line 36 of file Grenade_Base.c.
Referenced by Activate(), Deactivate(), and Grenade_Base().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Grenade_Base/FlashGrenade.c
P:/scripts/4_World/Entities/ItemBase/Grenade_Base.c
P:/scripts/4_World/Entities/Grenade_Base/M67Grenade.c
P:/scripts/4_World/Entities/Grenade_Base/RGD5Grenade.c