DayZ: array< ref CallQueueContext > Class Reference
array< ref CallQueueContext > Class Reference
Tools
CallQueue Class provide "lazy" calls - when we don't want to execute function immediately but later during frame update (used mainly in UI)
usage:
Private Member Functions
void CallQueue ()
void Tick ()
System function, don't call it.
void Call (Class obj, string fn_name, Param params=NULL)
Creates new call request, add it on queue and execute during frame update (depends on call category)
void RemoveCalls (Class obj)
Removes all queued calls for object (call this function when object is going to be deleted)
Private Attributes
private bool m_processing
Detailed Description
CallQueue Class provide "lazy" calls - when we don't want to execute function immediately but later during frame update (used mainly in UI)
usage:
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "Refresh"); // calls "Refresh" function on "this" with no arguments
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "Show", new Param1<bool>(true)); // calls "Show" function on "this" with one bool argument
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "SetPos", new Param2<float, float>(0.2, 0.5)); // calls "SetPos" function on "this" with two float arguments
Definition at line 66 of file tools.c.
Member Function Documentation
Call()
void Call (Class obj, string fn_name, Param params = NULL) inline private
Creates new call request, add it on queue and execute during frame update (depends on call category)
Parameters
obj target object on which function will be executed
fn_name name of function (on object "obj") which will be executed
params function arguments see Param for usage, default NULL (no arguments)
Warning
When object "obj" is deleted prior call execution, don't forget to remove calls for this object with RemoveCalls
Definition at line 108 of file tools.c.
CallQueue()
void CallQueue () inline private
Definition at line 70 of file tools.c.
RemoveCalls()
void RemoveCalls (Class obj) inline private
Removes all queued calls for object (call this function when object is going to be deleted)
Parameters
obj object for which you want remove all "lazy" calls
Definition at line 118 of file tools.c.
References Count, Get(), CallQueueContext::Invalidate(), and CallQueueContext::m_target.
Tick()
void Tick () inline private
System function, don't call it.
Definition at line 78 of file tools.c.
References CallQueueContext::Call(), Count, Get(), CallQueueContext::IsValid(), and Remove().
Field Documentation
m_processing
private bool m_processing private
Definition at line 68 of file tools.c.
The documentation for this class was generated from the following file:
3_Game/tools/tools.c