DayZ: OptionSelectorBase Class Reference
OptionSelectorBase Class Reference
Private Member Functions
void OptionSelector (Widget parent, int current_index, ScriptedWidgetEventHandler parent_c, bool disabled)
void ~OptionSelector ()
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void Reset ()
void SetNextOption ()
void SetPrevOption ()
array< string > GetOptions ()
bool IsSet ()
bool IsEnabled ()
Returns 'true' if current index == 1 (default 'enabled' value). Take care, as different selectors may follow different logic!
bool IsSelectorEnabled ()
Returns false for the selector in 'disabled' states.
string GetStringValue ()
void SetStringOption (string option, bool fire_event=true)
void ColorOption ()
override bool IsFocusable (Widget w)
override void Enable ()
override void Disable ()
override void ColorNormalConsole (Widget w)
override void ColorDisabledConsole (Widget w)
void OptionSelectorEditbox (Widget parent, string value, ScriptedWidgetEventHandler parent_menu, bool disabled)
void ~OptionSelectorEditbox ()
override void Enable ()
override void Disable ()
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool IsFocusable (Widget w)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
void SetValue (string value, bool update=true)
string GetValue ()
override void ColorHighlight (Widget w)
override void ColorNormal (Widget w)
void ~OptionSelectorSliderSetup ()
override void Enable ()
override void Disable ()
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool IsFocusable (Widget w)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
float NormalizeInput (float value)
void SetStep (float step)
void SetValue (float value, bool update=true)
float GetValue ()
override void ColorHighlight (Widget w)
override void ColorNormal (Widget w)
Private Attributes
protected Widget m_PreviousOption
protected Widget m_NextOption
protected TextWidget m_SelectedOption
protected int m_SelectedOptionIndex
protected ref array< string > m_Options
protected EditBoxWidget m_EditBox
protected SliderWidget m_Slider
protected float m_MinValue
protected float m_MaxValue
Detailed Description
Definition at line 1 of file OptionSelector.c.
Constructor & Destructor Documentation
~OptionSelector()
void ~OptionSelector () inline private
Definition at line 56 of file OptionSelector.c.
References m_Root.
~OptionSelectorEditbox()
void ~OptionSelectorEditbox () inline private
Definition at line 26 of file OptionSelectorEditbox.c.
References m_Root.
~OptionSelectorSliderSetup()
void ~OptionSelectorSliderSetup () inline private
Definition at line 7 of file OptionSelectorSliderSetup.c.
References m_Root.
Member Function Documentation
ColorDisabledConsole()
override void ColorDisabledConsole (Widget w) inline private
Definition at line 248 of file OptionSelector.c.
References ARGB().
Referenced by ScriptedWidgetEventHandler::Disable().
ColorHighlight() [1/2]
override void ColorHighlight (Widget w) inline private
Definition at line 145 of file OptionSelectorEditbox.c.
References ARGB(), and SetFocus().
Referenced by ScriptedWidgetEventHandler::OnMouseEnter(), and OnMouseEnter().
ColorHighlight() [2/2]
override void ColorHighlight (Widget w) inline private
Definition at line 134 of file OptionSelectorSliderSetup.c.
References ARGB(), and SetFocus().
ColorNormal() [1/2]
override void ColorNormal (Widget w) inline private
Definition at line 159 of file OptionSelectorEditbox.c.
References ARGB().
Referenced by ScriptedWidgetEventHandler::Enable(), ScriptedWidgetEventHandler::OnMouseLeave(), and OnMouseLeave().
ColorNormal() [2/2]
override void ColorNormal (Widget w) inline private
Definition at line 148 of file OptionSelectorSliderSetup.c.
References ARGB().
ColorNormalConsole()
override void ColorNormalConsole (Widget w) inline private
Definition at line 235 of file OptionSelector.c.
References ARGB().
Referenced by ScriptedWidgetEventHandler::Enable(), ScriptedWidgetEventHandler::OnFocusLost(), and ScriptedWidgetEventHandler::OnMouseLeave().
ColorOption()
void ColorOption () inline private
Definition at line 176 of file OptionSelector.c.
References ARGB().
Disable() [1/3]
override void Disable () inline private
Definition at line 221 of file OptionSelector.c.
References m_Parent.
Disable() [2/3]
override void Disable () inline private
Definition at line 38 of file OptionSelectorEditbox.c.
Disable() [3/3]
override void Disable () inline private
Definition at line 19 of file OptionSelectorSliderSetup.c.
Enable() [1/3]
override void Enable () inline private
Definition at line 207 of file OptionSelector.c.
References m_Parent.
Referenced by OptionSelectorEditbox().
Enable() [2/3]
override void Enable () inline private
Definition at line 31 of file OptionSelectorEditbox.c.
Enable() [3/3]
override void Enable () inline private
Definition at line 12 of file OptionSelectorSliderSetup.c.
GetOptions()
array< string > GetOptions () inline private
Definition at line 135 of file OptionSelector.c.
GetStringValue()
string GetStringValue () inline private
Definition at line 158 of file OptionSelector.c.
References string::Get().
GetValue() [1/2]
string GetValue () inline private
Definition at line 140 of file OptionSelectorEditbox.c.
Referenced by OnChange(), and SetValue().
GetValue() [2/2]
float GetValue () inline private
Definition at line 128 of file OptionSelectorSliderSetup.c.
References m_MaxValue, and m_MinValue.
IsEnabled()
bool IsEnabled () inline private
Returns 'true' if current index == 1 (default 'enabled' value). Take care, as different selectors may follow different logic!
Definition at line 147 of file OptionSelector.c.
IsFocusable() [1/3]
override bool IsFocusable (Widget w) inline private
Definition at line 198 of file OptionSelector.c.
References m_Parent.
Referenced by ScriptedWidgetEventHandler::OnFocus(), ScriptedWidgetEventHandler::OnMouseEnter(), OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), and OnMouseLeave().
IsFocusable() [2/3]
override bool IsFocusable (Widget w) inline private
Definition at line 103 of file OptionSelectorEditbox.c.
References m_Parent.
IsFocusable() [3/3]
override bool IsFocusable (Widget w) inline private
Definition at line 75 of file OptionSelectorSliderSetup.c.
References m_Parent.
IsSelectorEnabled()
bool IsSelectorEnabled () inline private
Returns false for the selector in 'disabled' states.
Definition at line 153 of file OptionSelector.c.
IsSet()
bool IsSet () inline private
Definition at line 141 of file OptionSelector.c.
NormalizeInput()
float NormalizeInput (float value) inline private
Definition at line 110 of file OptionSelectorSliderSetup.c.
References m_MaxValue, and m_MinValue.
OnChange() [1/2]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 93 of file OptionSelectorEditbox.c.
References GetValue().
OnChange() [2/2]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 65 of file OptionSelectorSliderSetup.c.
References GetValue().
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 79 of file OptionSelector.c.
References m_Parent, and OptionSelector::SetNextOption().
OnFocus() [1/2]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 112 of file OptionSelectorEditbox.c.
References GetFocus(), m_Parent, SetFocus(), x, and y.
OnFocus() [2/2]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 84 of file OptionSelectorSliderSetup.c.
References GetFocus(), m_Parent, SetFocus(), x, and y.
OnFocusLost() [1/2]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 123 of file OptionSelectorEditbox.c.
References m_Parent, x, and y.
OnFocusLost() [2/2]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 100 of file OptionSelectorSliderSetup.c.
References m_Parent, x, and y.
OnMouseButtonUp() [1/2]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 61 of file OptionSelector.c.
References OptionSelector::SetNextOption(), and OptionSelector::SetPrevOption().
OnMouseButtonUp() [2/2]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 57 of file OptionSelectorSliderSetup.c.
OnMouseEnter() [1/3]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 90 of file OptionSelector.c.
References x, and y.
OnMouseEnter() [2/3]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 45 of file OptionSelectorEditbox.c.
References ColorHighlight(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), IsFocusable(), m_Root, UIScriptedMenu::OnFocus(), UIScriptedMenu::OnMouseEnter(), x, and y.
OnMouseEnter() [3/3]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 26 of file OptionSelectorSliderSetup.c.
References ColorHighlight(), m_Root, OnFocus(), x, and y.
OnMouseLeave() [1/3]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 95 of file OptionSelector.c.
References x, and y.
OnMouseLeave() [2/3]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 69 of file OptionSelectorEditbox.c.
References ColorNormal(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), IsFocusable(), m_Root, UIScriptedMenu::OnFocus(), UIScriptedMenu::OnMouseLeave(), x, and y.
OnMouseLeave() [3/3]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 41 of file OptionSelectorSliderSetup.c.
References ColorNormal(), m_Root, OnFocusLost(), SetFocus(), x, and y.
OptionSelector()
void OptionSelector (Widget parent, int current_index, ScriptedWidgetEventHandler parent_c, bool disabled) inline private
Definition at line 9 of file OptionSelector.c.
References WorkspaceWidget::CreateWidgets(), Enable(), GetGame(), CGame::GetWorkspace(), m_Parent, and m_Root.
OptionSelectorEditbox()
void OptionSelectorEditbox (Widget parent, string value, ScriptedWidgetEventHandler parent_menu, bool disabled) inline private
Definition at line 5 of file OptionSelectorEditbox.c.
References WorkspaceWidget::CreateWidgets(), Enable(), GetGame(), CGame::GetWorkspace(), m_Parent, m_Root, and SetValue().
Reset()
void Reset () inline private
Definition at line 100 of file OptionSelector.c.
SetNextOption()
void SetNextOption () inline private
Definition at line 109 of file OptionSelector.c.
SetPrevOption()
void SetPrevOption () inline private
Definition at line 122 of file OptionSelector.c.
SetStep()
void SetStep (float step) inline private
Definition at line 116 of file OptionSelectorSliderSetup.c.
SetStringOption()
void SetStringOption (string option, bool fire_event = true) inline private
Definition at line 163 of file OptionSelector.c.
SetValue() [1/2]
void SetValue (float value, bool update = true) inline private
Definition at line 121 of file OptionSelectorSliderSetup.c.
References GetValue().
SetValue() [2/2]
void SetValue (string value, bool update = true) inline private
Definition at line 133 of file OptionSelectorEditbox.c.
References GetValue().
Referenced by OptionSelectorEditbox().
Field Documentation
m_EditBox
protected EditBoxWidget m_EditBox private
Definition at line 3 of file OptionSelectorEditbox.c.
m_MaxValue
protected float m_MaxValue private
Definition at line 5 of file OptionSelectorSliderSetup.c.
m_MinValue
protected float m_MinValue private
Definition at line 4 of file OptionSelectorSliderSetup.c.
m_NextOption
protected Widget m_NextOption private
Definition at line 4 of file OptionSelector.c.
m_Options
protected ref array<string> m_Options private
Definition at line 7 of file OptionSelector.c.
m_PreviousOption
protected Widget m_PreviousOption private
Definition at line 3 of file OptionSelector.c.
m_SelectedOption
protected TextWidget m_SelectedOption private
Definition at line 5 of file OptionSelector.c.
m_SelectedOptionIndex
protected int m_SelectedOptionIndex private
Definition at line 6 of file OptionSelector.c.
m_Slider
protected SliderWidget m_Slider private
Definition at line 3 of file OptionSelectorSliderSetup.c.
The documentation for this class was generated from the following files:
5_Mission/GUI/NewUI/OptionSelector.c
5_Mission/GUI/NewUI/OptionSelectorEditbox.c
5_Mission/GUI/NewUI/OptionSelectorSliderSetup.c