DayZ: Switchable_Base Class Reference
Switchable_Base Class Reference
Private Member Functions
override bool CanPutInCargo (EntityAI parent)
override void SetActions ()
override ScriptedLightBase GetLight ()
override bool CanPutAsAttachment (EntityAI parent)
override void OnWorkStart ()
override void OnWork (float consumed_energy)
override void OnWorkStop ()
override void OnInventoryExit (Man player)
override void SetActions ()
override bool IsLightSource ()
void UniversalLight ()
override ScriptedLightBase GetLight ()
override bool CanPutAsAttachment (EntityAI parent)
override void OnWorkStart ()
override void OnWork (float consumed_energy)
override void OnWorkStop ()
override void OnInventoryExit (Man player)
override void SetActions ()
override bool IsLightSource ()
void InitAttachmentsSlotsToCheck (out array< int > AttSlots)
Enter att slot types to check on attach.
Private Attributes
PistollightLight m_Light
UniversallightLight m_Light
ref array< int > m_AttachmentSlotsCheck
Static Private Attributes
static int REFLECTOR_ID = 1
static int GLASS_ID = 0
static string LIGHT_OFF_GLASS = "dz\\gear\\tools\\data\\flashlight_glass.rvmat"
static string LIGHT_OFF_REFLECTOR = "dz\\weapons\\attachments\\data\\TLS3.rvmat"
static string LIGHT_ON_GLASS = "dz\\gear\\tools\\data\\flashlight_glass_on.rvmat"
static string LIGHT_ON_REFLECTOR = "dz\\weapons\\attachments\\data\\TLS3_on.rvmat"
Detailed Description
Definition at line 1 of file Chainsaw.c.
Member Function Documentation
CanPutAsAttachment() [1/2]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 18 of file TLRLight.c.
CanPutAsAttachment() [2/2]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 25 of file UniversalLight.c.
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 3 of file Chainsaw.c.
GetLight() [1/2]
override ScriptedLightBase GetLight () inline private
Definition at line 13 of file TLRLight.c.
References m_Light.
Referenced by ItemBase::EEItemLocationChanged().
GetLight() [2/2]
override ScriptedLightBase GetLight () inline private
Definition at line 20 of file UniversalLight.c.
References m_Light.
InitAttachmentsSlotsToCheck()
void InitAttachmentsSlotsToCheck (out array< int > AttSlots) inline private
Enter att slot types to check on attach.
Definition at line 123 of file UniversalLight.c.
References InventorySlots::GetSlotIdFromString().
Referenced by UniversalLight().
IsLightSource() [1/2]
override bool IsLightSource () inline private
Definition at line 99 of file TLRLight.c.
IsLightSource() [2/2]
override bool IsLightSource () inline private
Definition at line 117 of file UniversalLight.c.
OnInventoryExit() [1/2]
override void OnInventoryExit (Man player) inline private
Definition at line 77 of file TLRLight.c.
References SetOrientation(), and Vector().
OnInventoryExit() [2/2]
override void OnInventoryExit (Man player) inline private
Definition at line 95 of file UniversalLight.c.
References SetOrientation(), and Vector().
OnWork() [1/2]
override void OnWork (float consumed_energy) inline private
Definition at line 40 of file TLRLight.c.
References GetGame(), m_Light, and PointLightBase::SetIntensity().
OnWork() [2/2]
override void OnWork (float consumed_energy) inline private
Definition at line 58 of file UniversalLight.c.
References GetGame(), m_Light, and PointLightBase::SetIntensity().
OnWorkStart() [1/2]
override void OnWorkStart () inline private
Definition at line 29 of file TLRLight.c.
References GetGame(), and m_Light.
OnWorkStart() [2/2]
override void OnWorkStart () inline private
Definition at line 47 of file UniversalLight.c.
References GetGame(), and m_Light.
OnWorkStop() [1/2]
override void OnWorkStop () inline private
Definition at line 62 of file TLRLight.c.
References GetGame(), and m_Light.
OnWorkStop() [2/2]
override void OnWorkStop () inline private
Definition at line 80 of file UniversalLight.c.
References GetGame(), and m_Light.
SetActions() [1/3]
override void SetActions () inline private
Definition at line 13 of file Chainsaw.c.
References AddAction().
SetActions() [2/3]
override void SetActions () inline private
Definition at line 92 of file TLRLight.c.
References AddAction().
SetActions() [3/3]
override void SetActions () inline private
Definition at line 110 of file UniversalLight.c.
References AddAction().
UniversalLight()
void UniversalLight () inline private
Definition at line 15 of file UniversalLight.c.
References InitAttachmentsSlotsToCheck().
Field Documentation
GLASS_ID
static int GLASS_ID = 0 static private
Definition at line 6 of file TLRLight.c.
LIGHT_OFF_GLASS
static string LIGHT_OFF_GLASS = "dz\\gear\\tools\\data\\flashlight_glass.rvmat" static private
Definition at line 8 of file TLRLight.c.
LIGHT_OFF_REFLECTOR
static string LIGHT_OFF_REFLECTOR = "dz\\weapons\\attachments\\data\\TLS3.rvmat" static private
Definition at line 9 of file TLRLight.c.
LIGHT_ON_GLASS
static string LIGHT_ON_GLASS = "dz\\gear\\tools\\data\\flashlight_glass_on.rvmat" static private
Definition at line 10 of file TLRLight.c.
LIGHT_ON_REFLECTOR
static string LIGHT_ON_REFLECTOR = "dz\\weapons\\attachments\\data\\TLS3_on.rvmat" static private
Definition at line 11 of file TLRLight.c.
m_AttachmentSlotsCheck
ref array<int> m_AttachmentSlotsCheck private
Definition at line 13 of file UniversalLight.c.
m_Light [1/2]
PistollightLight m_Light private
Definition at line 3 of file TLRLight.c.
Referenced by GetLight().
m_Light [2/2]
UniversallightLight m_Light private
Definition at line 3 of file UniversalLight.c.
REFLECTOR_ID
static int REFLECTOR_ID = 1 static private
Definition at line 5 of file TLRLight.c.
The documentation for this class was generated from the following files:
4_World/Entities/ItemBase/Switchable_Base/Chainsaw.c
4_World/Entities/ItemBase/Switchable_Base/TLRLight.c
4_World/Entities/ItemBase/Switchable_Base/UniversalLight.c