DayZ: BiosSessionService Class Reference
BiosSessionService Class Reference
Private Member Functions
proto native EBiosError EnterGameplaySessionAsync (string session_address, int session_port)
Enter a gameplay session.
proto native EBiosError LeaveGameplaySessionAsync (string session_address, int session_port)
Leave a gameplay session.
proto native void OnSessionPlayerListUpdate (array< string > newPlayers)
Alerts engine that players in current session have changed.
void TryGetSession (string join_handle="")
Gets a session from a join handle.
proto native EBiosError GetSessionAsync (string join_handle)
Gets a session from a join handle.
proto native EBiosError SetGameplayActivityAsync (string session_address, int session_port)
Sets the activity to a gameplay session.
proto native EBiosError ClearActivityAsync ()
not implemented
proto native EBiosError ShowInviteToGameplaySessionAsync (string session_address, int session_port)
Show system UI to invite friends to current gameplay session.
proto native EBiosError InviteToGameplaySessionAsync (string session_address, int session_port, array< string > invitee_list)
Send invite to list of users.
proto native void SetMultiplayState (bool is_active)
Notifiy about interactive multiplayer state.
void OnSetActivity (EBiosError error)
Callback function.
void OnClearActivity (EBiosError error)
Callback function.
void OnGetGameplaySession (string session_address, int session_port)
Callback function.
void OnGetSessionError (EBiosError error)
//! Callback function, not implemented
void OnEnterGameplaySession (string session_address, int session_port, EBiosError error)
Callback function.
void OnLeaveGameplaySession (EBiosError error)
Callback function.
void OnShowInviteToGameplaySession (EBiosError error)
Callback function.
void OnInviteToGameplaySession (EBiosError error)
Callback function.
array< string > GetSessionPlayerList ()
Private Attributes
protected int m_GetSessionAttempts
string m_CurrentHandle
Detailed Description
Definition at line 1 of file BiosSessionService.c.
Member Function Documentation
ClearActivityAsync()
proto native EBiosError ClearActivityAsync () private
not implemented
Clears the current activity
The async result is returned in the OnClearActivity callback. Expected errors:
Returns
EBiosError indicating if the async operation is pending.
EnterGameplaySessionAsync()
proto native EBiosError EnterGameplaySessionAsync (string session_address, int session_port) private
Enter a gameplay session.
The async result is returned in the OnEnterGameplaySession callback. Expected errors: LOGICAL - if the user is currently in an active gameplay session.
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::EnterGameplaySession().
GetSessionAsync()
proto native EBiosError GetSessionAsync (string join_handle) private
Gets a session from a join handle.
The async result is returned in the OnGetGameplaySession, OnGetLobbySession or OnGetSessionError callback, dependinng on the type of session, or error. Expected errors:
Parameters
join_handle the parsed join handle.
Returns
EBiosError indicating if the async operation is pending.
Referenced by TryGetSession().
GetSessionPlayerList()
array< string > GetSessionPlayerList () inline private
Definition at line 258 of file BiosSessionService.c.
References ClientData::GetSimplePlayerList().
InviteToGameplaySessionAsync()
proto native EBiosError InviteToGameplaySessionAsync (string session_address, int session_port, array< string > invitee_list) private
Send invite to list of users.
The async result is returned in the OnInviteToGameplaySession callback. The user must be inside the session. That means, OnEnterGameplaySession must be called with no errors.
Parameters
session_address server IP address.
session_port server port.
invitee_list list of users to invite
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnEnterGameplaySession(), and OnlineServices::SetPendingInviteList().
LeaveGameplaySessionAsync()
proto native EBiosError LeaveGameplaySessionAsync (string session_address, int session_port) private
Leave a gameplay session.
The async result is returned in the OnLeaveGameplaySession callback. If there is an unexpected error the state is cleared. Expected errors: ERR_NOT_FOUND - when attempting to leave a gameplay session the user is not part of. ERR_LOGICAL - when the user is not in a gameplay session.
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::LeaveGameplaySession().
OnClearActivity()
void OnClearActivity (EBiosError error) inline private
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 138 of file BiosSessionService.c.
OnEnterGameplaySession()
void OnEnterGameplaySession (string session_address, int session_port, EBiosError error) inline private
Callback function.
Parameters
session_address server IP address. Empty if failed.
session_port server port. 0 if failed.
error error indicating success or fail of the async operation.
Definition at line 220 of file BiosSessionService.c.
References OnlineServices::ErrorCaught(), OnlineServices::GetPendingInviteList(), InviteToGameplaySessionAsync(), and SetGameplayActivityAsync().
OnGetGameplaySession()
void OnGetGameplaySession (string session_address, int session_port) inline private
Callback function.
Parameters
session_address server IP address.
session_port server port.
Definition at line 147 of file BiosSessionService.c.
References NotificationSystem::AddNotification(), DISCONNECT_SESSION_FLAGS_FORCE, g_Game, GetGame(), CGame::GetHostAddress(), m_GetSessionAttempts, MENU_INVITE_TIMER, and OnlineServices::SetInviteServerInfo().
OnGetSessionError()
void OnGetSessionError (EBiosError error) inline private
//! Callback function, not implemented
Callback function
Parameters
error error indicating fail of the async operation. Cannot be OK.
Definition at line 201 of file BiosSessionService.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), DISCONNECT_SESSION_FLAGS_JOIN, OnlineServices::ErrorCaught(), g_Game, CGame::GetCallQueue(), GetGame(), m_GetSessionAttempts, and TryGetSession().
OnInviteToGameplaySession()
void OnInviteToGameplaySession (EBiosError error) inline private
Callback function.
Parameters
error indicating success or fail of the async operation.
Definition at line 253 of file BiosSessionService.c.
OnLeaveGameplaySession()
void OnLeaveGameplaySession (EBiosError error) inline private
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 236 of file BiosSessionService.c.
OnSessionPlayerListUpdate()
proto native void OnSessionPlayerListUpdate (array< string > newPlayers) private
Alerts engine that players in current session have changed.
Parameters
newPlayers players that have just joined the server. When player joins a server, ALL players already on server count as new players.
Referenced by ClientData::SyncEvent_OnRecievedPlayerList().
OnSetActivity()
void OnSetActivity (EBiosError error) inline private
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 129 of file BiosSessionService.c.
References OnlineServices::ErrorCaught().
OnShowInviteToGameplaySession()
void OnShowInviteToGameplaySession (EBiosError error) inline private
Callback function.
Parameters
error indicating success or fail of the async operation.
Definition at line 244 of file BiosSessionService.c.
References OnlineServices::ErrorCaught().
SetGameplayActivityAsync()
proto native EBiosError SetGameplayActivityAsync (string session_address, int session_port) private
Sets the activity to a gameplay session.
The async result is returned in the OnSetActivity callback. Expected errors: ERR_NOT_FOUND - when attempting to set a gameplay session activity the user is not part of.
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnEnterGameplaySession(), and OnlineServices::SetGameplayActivity().
SetMultiplayState()
proto native void SetMultiplayState (bool is_active) private
Notifiy about interactive multiplayer state.
Referenced by OnlineServices::SetMultiplayState().
ShowInviteToGameplaySessionAsync()
proto native EBiosError ShowInviteToGameplaySessionAsync (string session_address, int session_port) private
Show system UI to invite friends to current gameplay session.
The async result is returned in the OnShowInviteToGameplaySession callback. On Xbox, if session with session_address and session_port does not exist, then xbox show message "We could not send the invite".
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::ShowInviteScreen().
TryGetSession()
void TryGetSession (string join_handle = "") inline private
Gets a session from a join handle.
The async result is returned in the OnGetGameplaySession, OnGetLobbySession or OnGetSessionError callback, dependinng on the type of session, or error. Expected errors:
Parameters
join_handle the parsed join handle.
Returns
EBiosError indicating if the async operation is pending.
Definition at line 47 of file BiosSessionService.c.
References DISCONNECT_SESSION_FLAGS_JOIN, g_Game, GetSessionAsync(), m_CurrentHandle, and m_GetSessionAttempts.
Referenced by OnlineServices::GetSession(), and OnGetSessionError().
Field Documentation
m_CurrentHandle
string m_CurrentHandle private
Definition at line 4 of file BiosSessionService.c.
Referenced by OnlineServices::GetSessionHandle(), OnlineServices::SetSessionHandle(), and TryGetSession().
m_GetSessionAttempts
protected int m_GetSessionAttempts private
Definition at line 3 of file BiosSessionService.c.
Referenced by OnGetGameplaySession(), OnGetSessionError(), and TryGetSession().
The documentation for this class was generated from the following file:
3_Game/Services/BiosSessionService.c