DayZ: UIScriptedMenu Class Reference
UIScriptedMenu Class Reference
Private Member Functions
void LoginQueueBase ()
void ~LoginQueueBase ()
override Widget Init ()
override void Update (float timeslice)
override bool OnClick (Widget w, int x, int y, int button)
void Show ()
void Hide ()
void SetPosition (int position)
bool IsStatic ()
void Leave ()
void LoginTimeBase ()
void ~LoginTimeBase ()
override Widget Init ()
override void Update (float timeslice)
override bool OnClick (Widget w, int x, int y, int button)
void Show ()
void Hide ()
void SetTime (int time)
void SetStatus (string status)
void SetRespawn (bool value)
bool IsStatic ()
bool IsRespawn ()
void Leave ()
override Widget Init ()
void ReadBook (InventoryItem book)
override bool OnClick (Widget w, int x, int y, int button)
void NextPrevPage (bool next)
void CameraToolsMenu ()
void ~CameraToolsMenu ()
override void OnShow ()
override void OnHide ()
void SelectKeyframe (CTKeyframe kf)
void SelectEvent (CTEvent ev)
void SelectActor (CTActor ac)
override Widget Init ()
PlayerBase GetActor (int index)
void LoadData ()
void SaveData ()
float GetTotalTime (int index)
void AddKeyframe ()
void SaveKeyframe ()
void DeleteKeyframe ()
void ViewKeyframe ()
void AddActor (string actor_type)
void AddEvent (int actor_index)
void AddItem (string id, string type)
void AddHandsItem (string id, string type)
void SaveEvent ()
void DeleteEvent ()
void ViewEvent ()
Param6< vector, vector, float, float, float, int > GetCameraLine (int index)
void Play ()
void Stop ()
vector GetCameraLookDir ()
vector GetMouseLookDir ()
override void Update (float timeslice)
float SetCameraData (Param6< vector, vector, float, float, float, int > transform1, Param6< vector, vector, float, float, float, int > transform2)
void SetBlurValue (float blur)
float GetBlurValue ()
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
override bool OnKeyPress (Widget w, int x, int y, int key)
void ColorRed (Widget w)
void ColorWhite (Widget w, Widget enterW)
void ChatInputMenu ()
override Widget Init ()
override bool UseKeyboard ()
override bool OnChange (Widget w, int x, int y, bool finished)
override void OnShow ()
override void OnHide ()
override void Refresh ()
override void Update (float timeslice)
void UpdateChannel ()
void ~ControlsXboxNew ()
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
void Back ()
void UpdateTabContent (int tab_index)
protected void DrawConnectingLines (int index)
override Widget Init ()
override void OnShow ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
override void Update (float timeslice)
protected void ComposeData ()
Inits data structure.
protected void PerformSwitchPreset ()
protected void UpdateToolbarText ()
protected Widget FindChildByID (Widget wid, int user_id)
Finds immediate child widget with a corresponding userID.
protected bool FindAllChildrenByID (Widget wid, int user_id, out array< Widget > results)
Finds all immediate children widgets with corresponding userIDs.
protected int FilterByVisible (array< Widget > input, array< Widget > filtered)
returns count
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
protected void UpdateControlsElements ()
protected void UpdateControlsElementVisibility ()
void EarlyAccessMenu ()
void ~EarlyAccessMenu ()
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
void GesturesMenu ()
void ~GesturesMenu ()
protected void OnInputPresetChanged ()
override Widget Init ()
override void OnShow ()
override void OnHide ()
override bool OnController (Widget w, int control, int value)
override bool OnMouseEnter (Widget w, int x, int y)
override bool UseMouse ()
override bool UseGamepad ()
override void Update (float timeslice)
void ProcessEmoteConditionRequest (GestureMenuItem gesture_item)
protected void RefreshGestures (GestureCategories category_id=-1)
protected void GetGestureItems (out ref array< ref GestureMenuItem > gesture_items, GestureCategories category)
protected void CreateGestureContent ()
protected void UpdateQuickbarItemCard (GestureMenuItem gesture_item)
protected void DeleteGestureItems ()
protected void UpdateToolbar ()
DEPRECATED.
protected void UpdateCategoryName (string name)
void OnControlsChanged (RadialMenuControlType type)
void OnMouseSelect (Widget w)
void OnMouseDeselect (Widget w)
void OnMouseExecute (Widget w)
void OnMousePressLeft (Widget w)
LMB.
void OnMousePressRight (Widget w)
RMB.
void OnControllerSelect (Widget w)
void OnControllerDeselect (Widget w)
void OnControllerExecute (Widget w)
void OnControllerPressSelect (Widget w)
void OnControllerPressBack (Widget w)
protected void MarkSelected (Widget w)
protected void UnmarkSelected (Widget w)
protected void ExecuteSelectedCategory (Widget w)
protected void ExecuteSelectedItem ()
protected void BackOneLevel ()
bool IsMenuClosing ()
void SetMenuClosing (bool state)
protected void UpdateControlsElements ()
protected void OnMenuRelease ()
DEPRECATED.
void HelpScreen ()
void ~HelpScreen ()
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
void ~InGameMenu ()
override Widget Init ()
protected void SetGameVersion ()
protected bool SetServerInfo ()
protected void HudShow (bool show)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnClick (Widget w, int x, int y, int button)
protected void OnClick_Continue ()
protected void OnClick_Restart ()
protected void OnClick_Respawn ()
protected void OnClick_Options ()
protected void OnClick_Exit ()
override bool OnModalResult (Widget w, int x, int y, int code, int result)
override void Update (float timeslice)
protected void UpdateGUI ()
void MenuRequestRespawn (UIScriptedMenu menu, bool random)
protected void GameRespawn (bool random)
protected void ColorHighlight (Widget w)
protected void ColorNormal (Widget w)
protected void ColorDisable (Widget w)
protected void ButtonSetText (Widget w, string text)
protected void ButtonSetColor (Widget w, int color)
protected void ButtonSetTextColor (Widget w, int color)
void SetServerInfoVisibility (bool show)
void ToggleFavoriteServer ()
void InGameMenuXbox ()
void ~InGameMenuXbox ()
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnModalResult (Widget w, int x, int y, int code, int result)
void GameRetry (bool random)
void MenuRequestRespawn (UIScriptedMenu menu, bool random)
bool IsLocalPlayer (string uid)
SyncPlayerList CreateFakePlayerList (int player_count)
override void Update (float timeslice)
void UpdateGUI ()
bool IsOnlineOpen ()
void CloseOnline ()
void SelectServer ()
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
void SyncEvent_OnRecievedPlayerList (SyncPlayerList player_list)
void OnPermissionsUpdate (BiosPrivacyUidResultArray result_list)
override void OnShow ()
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
override void Refresh ()
void ColorDisable (Widget w)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
protected void SetMuteButtonText (bool isMuted)
Set mute text button text (mute / unmute)
protected void LoadTextStrings ()
Set correct bottom button texts based on platform (ps4 vs xbox texts)
protected void LoadFooterButtonTexts ()
Initial texts load for the footer buttons.
void UpdateMenuFocus ()
protected void UpdateControlsElements ()
void InputDeviceDisconnectWarningMenu ()
void ~InputDeviceDisconnectWarningMenu ()
override Widget Init ()
private void BuildMessages ()
private void UpdateDisconnectTexts ()
Composes message depending on context.
private void SetDisconnectTexts ()
private void UpdateDisconnectedDevices (int device=-1)
private void UpdateWarningMenu (int device)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnKeyUp (Widget w, int x, int y, int key)
void InspectMenuNew ()
void ~InspectMenuNew ()
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
void SetItem (EntityAI item)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
void UpdateRotation (int mouse_x, int mouse_y, bool is_dragging)
override bool OnMouseWheel (Widget w, int x, int y, int wheel)
void UpdateScale ()
void InviteMenu ()
override Widget Init ()
override void OnShow ()
override void Update (float timeslice)
void UpdateTime ()
void Cancel ()
void WarningMenuBase ()
void ~WarningMenuBase ()
override Widget Init ()
string GetText ()
override bool OnClick (Widget w, int x, int y, int button)
void LoadingMenu ()
void ~LoadingMenu ()
override Widget Init ()
void LogoutMenu ()
void ~LogoutMenu ()
override Widget Init ()
void Show ()
void Hide ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnKeyDown (Widget w, int x, int y, int key)
override void Update (float timeslice)
void SetLogoutTime ()
void SetTime (int time)
void UpdateTime ()
void UpdateInfo ()
void Exit ()
void Cancel ()
override Widget Init ()
override void InitMapItem (EntityAI item)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnKeyPress (Widget w, int x, int y, int key)
override void Update (float timeslice)
void AddMarker (vector pos, int color, int icon=0)
void RemoveMarker ()
override void LoadMapMarkers ()
void CloseMapMenu ()
protected void SetCompassUIVisibility (bool pState)
protected void SetGPSMarkerVisibility (bool pState)
protected void SetGPSDirectionVisibility (bool pState)
protected void SetUpperLegendVisibility (bool pState)
protected void RenderScaleRuler ()
protected void ProcessDistanceAndUnits (float num, out float dist, out string units)
void CharacterCreationMenu ()
PlayerBase GetPlayerObj ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override Widget Init ()
void ~CharacterCreationMenu ()
void Apply ()
renames character
void Save ()
saves default character
void Back ()
void SetCharacter ()
void RandomizeCharacter ()
void GenderChanged ()
void SkinChanged ()
void TopChanged ()
void BottomChanged ()
void ShoesChanged ()
override bool OnKeyPress (Widget w, int x, int y, int key)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
void SetTooltipTexts (Widget w, string header="", string desc="")
void CheckNewOptions ()
override void OnShow ()
override void Refresh ()
override void Update (float timeslice)
override void OnHide ()
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ColorDisable (Widget w)
void SetCharacterSaved (bool state)
protected void UpdateControlsElements ()
protected void UpdateControlsElementVisibility ()
override Widget Init ()
void LoadDataAsync ()
override void Update (float timeslice)
void UpdateInfoPanelText (int input_device_type)
override Widget Init ()
void CreateTabs ()
void CreateGroupContainer ()
void UpdateTabContent (int tab_index)
void ClearKeybind (int key_index)
void ClearAlternativeKeybind (int key_index)
void StartEnteringKeybind (int key_index)
void CancelEnteringKeybind ()
void StartEnteringAlternateKeybind (int key_index)
void CancelEnteringAlternateKeybind ()
void ConfirmKeybindEntry (TIntArray new_keys)
void ConfirmAlternateKeybindEntry (TIntArray new_keys)
override void Update (float timeslice)
override bool OnClick (Widget w, int x, int y, int button)
void Apply ()
void Back ()
void Reset ()
Undoes the unsaved changes and reverts to previous state. Does not reset to defaults!
void SetToDefaults ()
void HardReset ()
void PerformSetToDefaultsExt (int mode)
override bool OnModalResult (Widget w, int x, int y, int code, int result)
override void Refresh ()
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseWheel (Widget w, int x, int y, int wheel)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
void ColorRed (Widget w)
void ColorWhite (Widget w, Widget enterW)
void ColorDisabled (Widget w)
protected void InitInputSortingMap ()
void InitPresets (int index, Widget parent, Input input)
void OnAttemptSelectPreset (int index)
void OnSelectKBPreset (int index)
KeybindingsContainer GetCurrentTab ()
void AddGroup (int index, Input input)
void PerformSetToDefaults ()
deprecated, resets all (as before ~1.20)
void DeferredDefaultsInit ()
deprecated
override Widget Init ()
void ~MainMenu ()
void LoadMods ()
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
override void Refresh ()
override void OnShow ()
override void OnHide ()
override void Update (float timeslice)
void Play ()
bool CanSaveDefaultCharacter ()
void OpenMenuServerBrowser ()
void OpenMenuCustomizeCharacter ()
void NextCharacter ()
void PreviousCharacter ()
void OnChangeCharacter (bool create_character=true)
void OpenStats ()
void OpenMessages ()
void OpenSettings ()
void PlayVideo ()
void OpenTutorials ()
void OpenCredits ()
void Exit ()
bool TryConnectLastSession (out string ip, out int port)
void AutoConnect ()
void ConnectLastSession ()
void ConnectBestServer ()
override bool OnModalResult (Widget w, int x, int y, int code, int result)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ImagenSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
override Widget Init ()
void LoadMods ()
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override void Refresh ()
override void OnShow ()
override void OnHide ()
override void Update (float timeslice)
bool CanStoreBeOpened ()
void OpenMenuServerBrowser ()
void OpenMenuControls ()
void OpenMenuOptions ()
void OpenMenuPlayVideo ()
void OpenMenuTutorials ()
void OpenMenuCustomizeCharacter ()
void OpenCredits ()
void ChangeAccount ()
void Exit ()
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
override bool OnModalResult (Widget w, int x, int y, int code, int result)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ButtonSetAlphaAnim (Widget w)
void ButtonSetTextColor (Widget w, int color)
protected void UpdateControlsElements ()
protected void UpdateControlsElementVisibility ()
override Widget Init ()
void ~MainMenuVideo ()
override void OnShow ()
override void OnHide ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
void PlayVideoLoop ()
void StopVideo ()
void PlayPauseVideo ()
override void Update (float timeslice)
override void OnVisibilityChanged (bool isVisible)
protected void LoadFooterButtonTexts ()
protected void LoadTextStrings ()
protected void UpdateControlsElements ()
override Widget Init ()
void ~TutorialsMenu ()
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override void OnShow ()
void Back ()
void DrawConnectingLines (int index)
protected array< ref JsonControlMappingInfo > GetControlMappingInfo ()
override void Update (float timeslice)
protected void LoadFooterButtonTexts ()
Initial texts load for the footer buttons.
protected void LoadTextStrings ()
Set correct bottom button texts based on platform (ps4 vs xbox texts)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ImagenSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
protected void UpdateControlsElements ()
protected void UpdateControlsElementVisibility ()
void OptionsMenu ()
override Widget Init ()
void ~OptionsMenu ()
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override bool OnClick (Widget w, int x, int y, int button)
void OnTabSwitch (int tab)
void Apply ()
void Back ()
void OnAttemptTabSwitch (int source, int target)
bool IsAnyTabChanged ()
void OnChanged ()
void Reset ()
void ResetCurrentTab ()
void SetToDefaults ()
void PerformSetToDefaults ()
void SliderFocus ()
void ToggleFocus ()
void ToggleDependentOptions (int mode, bool state)
Controls visibility and sometimes even state of specific, dependent options across sub-menus.
void ReloadOptions ()
void ReloadVideoOptions ()
override bool OnModalResult (Widget w, int x, int y, int code, int result)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
override void Refresh ()
override void OnShow ()
override void Update (float timeslice)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ColorDisable (Widget w)
protected void UpdateControlsElements ()
protected void UpdateControlsElementVisibility ()
override Widget Init ()
void ~ServerBrowserMenuNew ()
TStringArray GetFavoritedServerIds ()
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void SetServersLoadingTab (TabType refreshing)
TabType GetServersLoadingTab ()
void AddFavoritesToFilter (GetServersInput input)
bool IsFavorited (string server_id)
bool SetFavoriteConsoles (string ipAddress, int port, bool favorite)
void AddFavorite (string ipAddress, int port, bool favorite)
void Back ()
void ShowYButton (bool show)
void ShowAButton (bool show)
void FilterFocus (bool focus)
void BackButtonFocus ()
void ServerListFocus (bool focus, bool favorite)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override void Refresh ()
override void Update (float timeslice)
bool IsFocusable (Widget w)
void LoadFavoriteServers ()
void SaveFavoriteServersConsoles ()
void SelectServer (ServerBrowserEntry server)
void Connect (ServerBrowserEntry server)
void Play ()
void CustomizeCharacter ()
void NextCharacter ()
void PreviousCharacter ()
ServerBrowserTab GetSelectedTab ()
void OnTabSwitch ()
void OnLoadServerModsAsync (GetServerModListResult result_list)
void OnLoadServersAsync (GetServersResult result_list, EBiosError error, string response)
void ColorHighlight (Widget w)
void ColorNormal (Widget w)
void ButtonSetText (Widget w, string text)
void ButtonSetColor (Widget w, int color)
void ButtonSetTextColor (Widget w, int color)
protected void UpdateControlsElements ()
void NoteMenu ()
void ~NoteMenu ()
override void InitNoteRead (string text="")
override void InitNoteWrite (EntityAI paper, EntityAI pen, string text="")
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
override void Update (float timeslice)
void PresetsMenu ()
void ~PresetsMenu ()
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
void RadialQuickbarMenu ()
void ~RadialQuickbarMenu ()
protected void OnInputPresetChanged ()
override Widget Init ()
override void OnShow ()
override void OnHide ()
override bool OnController (Widget w, int control, int value)
override bool OnMouseEnter (Widget w, int x, int y)
override bool UseMouse ()
override bool UseGamepad ()
protected void RefreshQuickbar (bool reset_selection=true)
protected void GetItems (out ref array< ref RadialQuickbarItem > items)
protected void CheckForLightsAndNVG (out ref array< ref RadialQuickbarItem > items, int last_idx)
protected void CreateContent (int selected_item_id=-1)
protected void UpdateQuickbarItemCard (RadialQuickbarItem quickbar_item)
protected void DeleteItems ()
protected void ChangeCurrentCategory (int category)
void OnControlsChanged (RadialMenuControlType type)
void OnMouseSelect (Widget w)
void OnMouseDeselect (Widget w)
void OnMouseExecute (Widget w)
void OnMousePressLeft (Widget w)
LMB.
void OnMousePressRight (Widget w)
RMB.
void OnControllerSelect (Widget w)
void OnControllerDeselect (Widget w)
void OnControllerPressSelect (Widget w)
void OnControllerPressBack (Widget w)
protected void MarkSelected (Widget w)
protected void UnmarkSelected (Widget w)
protected void PrimaryAction (Widget w)
protected void SecondaryAction (Widget w)
protected void BackOneLevel ()
void HandleLights (RadialQuickbarItem quickbar_item)
void HandleNVG (RadialQuickbarItem quickbar_item)
bool IsMenuClosing ()
void SetMenuClosing (bool state)
protected void UpdateControlsElements ()
void RespawnDialogue ()
void ~RespawnDialogue ()
override Widget Init ()
override void Update (float timeslice)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override void OnShow ()
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
bool IsFocusable (Widget w)
protected void ColorHighlight (Widget w)
protected void ColorNormal (Widget w)
protected void ButtonSetColor (Widget w, int color)
protected void ButtonSetTextColor (Widget w, int color)
void SetTooltipTexts (Widget w, string header="", string desc="")
bool RequestRespawn (bool random)
void RenderPresets ()
bool IsPresetFixed (string preset_name)
int GetPresetIndexByName (string preset_name)
void NewPreset (string preset_name)
void DeletePreset ()
void SetDefaultPreset (int preset_index)
void RefreshLists ()
void RenamePreset (string new_preset_name)
void RenderPresetItems ()
string GetCurrentPresetName ()
string GetCurrentItemName ()
string GetCurrentObjectName ()
int GetCurrentPresetIndex ()
int GetCurrentItemIndex ()
bool IsCurrentPresetFixed ()
void AddItemToPreset ()
void RemoveItemFromPreset ()
void SetPreset (bool clear_inventory, string preset_name)
spawn preset items into inventory
void ItemMoveUp ()
void ItemMoveDown ()
void SaveProfileSpawnDistance ()
override bool UseMouse ()
override bool UseKeyboard ()
void SceneEditorMenu ()
void ~SceneEditorMenu ()
override Widget Init ()
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
override void OnShow ()
override void OnHide ()
override bool OnMouseWheel (Widget w, int x, int y, int wheel)
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
UIPopupScript PopupOpen (int popup_id, Param param)
UIPopupScript PopupBack ()
void PopupCloseAll ()
void ToggleVisibility ()
override void Refresh ()
void SceneEditorCommand (Param params)
protected void RefreshByLocalProfile ()
private void UpdateListObjects ()
protected void UpdateListClasses ()
protected map< int, SceneObject > GetFiltredSceneObjects (string search_string, map< int, SceneObject > array_ret)
TStringArray GetFiltredConfigClasses (string search_string, TStringArray array_ret)
private void PopupClose (int popup_id)
private void PopupHideAll ()
private bool ComponentsOnClick (Widget w, int x, int y, int button)
private bool ComponentsOnChange (Widget w, int x, int y, bool finished)
UIPropertyAttachment GetFreeUIPropertyAttchament ()
private map< string, ref TStringArray > GetItemNamesForSlots (TStringArray slots)
void ScriptConsole ()
void ~ScriptConsole ()
override Widget Init ()
void RefreshDateWidgets (int year, int month, int day, int hour, int minute)
bool IsLocationNameAvailable (string name)
void SetFilterOrder (bool reversed)
void RefreshLocations ()
void LateInit ()
void Add (string message, bool isReload=false)
void AddServer (string message)
void HistoryBack ()
void HistoryForward ()
void EnscriptHistoryBack ()
void EnscriptHistoryForward ()
void Clear (bool clearFile=false)
void RunEnscript ()
void ColorRunButton (bool success)
void ResetRunButtonColor ()
void RunEnscriptServer ()
TStringArray GetItemsClasses ()
TStringArray GetSoundClasses ()
int GetFilterColor (string color)
void PrepareFilters (string filter, out TStringArray filters, out TIntArray colors)
void ChangeFilter (TStringArray classes, TextListboxWidget widget, EditBoxWidget filterWidget, int categoryMask=-1, bool ignoreScope=false)
void ChangeConfigFilter ()
override bool OnKeyPress (Widget w, int x, int y, int key)
override bool OnKeyDown (Widget w, int x, int y, int key)
override void Update (float timeslice)
void UpdateMousePos ()
void SelectObject (bool hide_presets=true)
void SetMapPos (vector pos)
vector GetMapPos ()
void DumpParam (string param, string relativePath)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnDoubleClick (Widget w, int x, int y, int button)
void Teleport (PlayerBase player, vector position)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
void ChangeFilterItems ()
void ChangeFilterSound ()
void SelectPreset ()
void RefreshLists ()
void RenderPresets ()
void RenderPresetItems ()
void NewPreset (string preset_name)
void DeletePreset ()
void SaveProfileSpawnDistance ()
void RenamePreset (string new_preset_name)
void SpawnPreset (EntityAI target, bool clear_inventory, string preset_name, InventoryLocationType location=InventoryLocationType.ATTACHMENT, float distance=0)
void SetDefaultPreset (int preset_index)
void SetObject (string object)
void SetPreviewObject (string object)
void AddItemToPreset ()
void ShowPresetButtons ()
void AddItemToClipboard (TextListboxWidget text_listbox_widget)
void RemoveItemFromPreset ()
string GetCurrentPresetName ()
string GetCurrentItemName ()
string GetCurrentObjectName ()
string GetCurrentLocationName ()
vector GetCurrentLocationPos ()
void GetCurrentPositionData (out LocationParams data)
bool IsCurrentPositionCustom ()
int GetCurrentPositionIndex ()
bool IsCurrentPositionValid ()
int GetCurrentPresetIndex ()
int GetCurrentItemIndex ()
bool IsCurrentPresetFixed ()
bool IsPresetFixed (string preset_name)
int GetPresetIndexByName (string preset_name)
void ShowItemButtons ()
void HideItemButtons ()
void ShowItemTransferButtons ()
void ItemMoveUp ()
void ItemMoveDown ()
void ClearHierarchy ()
void FindInHierarchy (string class_name)
void ExpandHierarchy (int row)
void CollapseHierarchy (int row)
void RenderVariables (int row)
void UpdateHudDebugSetting ()
void RefreshPlayerPosEditBoxes ()
void UpdateTime (bool slider_used)
void SelectPreviousTab ()
void SelectNextTab ()
void SelectTab (int tab_id)
void ReloadOutput ()
void ReloadScriptOutput ()
void OnTabSeleted (int tabID)
override void OnRPCEx (int rpc_type, ParamsReadContext ctx)
void ScriptConsoleAddLocation ()
void ~ScriptConsoleAddLocation ()
void SetPosition (vector pos)
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
void ScriptConsoleNewPresetDialog ()
void ~ScriptConsoleNewPresetDialog ()
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
void ScriptConsoleRenamePresetDialog ()
void ~ScriptConsoleRenamePresetDialog ()
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
void StartupMenu ()
void ~StartupMenu ()
override Widget Init ()
void TitleScreenMenu ()
void ~TitleScreenMenu ()
override Widget Init ()
override void OnShow ()
override void OnHide ()
override void Update (float timeslice)
Static Private Member Functions
static void PlayAnimOnActor (int actor, int anim)
static string GetChannelName (ChatChannel channel)
static void OpenMenu ()
static void CloseMenu ()
static void UpdateItemInfo (Widget root_widget, EntityAI item)
static void UpdateSlotInfo (Widget root_widget, string name, string desc="")
static void UpdateItemInfoDamage (Widget root_widget, EntityAI item)
static void UpdateItemInfoLiquidType (Widget root_widget, EntityAI item)
static void UpdateItemInfoTemperature (Widget root_widget, EntityAI item)
static void UpdateItemInfoWetness (Widget root_widget, EntityAI item)
static void UpdateItemInfoQuantity (Widget root_widget, EntityAI item)
static void UpdateItemInfoWeight (Widget root_widget, EntityAI item)
static void UpdateItemInfoFoodStage (Widget root_widget, EntityAI item)
static void UpdateItemInfoCleanness (Widget root_widget, EntityAI item)
static void WidgetTrySetText (Widget root_widget, string widget_name, string text, int color=0)
static void SetItemToAssign (EntityAI item)
static EntityAI GetItemToAssign ()
static RadialQuickbarMenu GetMenuInstance ()
static void OpenMenu (UIScriptedMenu parent=NULL)
static void CloseMenu ()
static void PrintS (string message)
static void PrintS (bool message)
static void PrintS (int message)
static void PrintS (float message)
static void PrintS (vector message)
static void DrawItems (string type, float distance=0)
static void DrawItemsClear ()
static string GetLastSelectedObject ()
Private Attributes
protected TextWidget m_txtPosition
protected TextWidget m_txtNote
protected ButtonWidget m_btnLeave
protected int m_iPosition
protected bool m_IsStatic
protected TextWidget m_txtDescription
protected TextWidget m_txtLabel
protected bool m_IsRespawn
protected TextWidget m_author
protected TextWidget m_title
protected TextWidget m_page
protected HtmlWidget m_content
protected float m_page_height
protected float m_content_total_height
protected float m_content_pos
vector m_FreeflightCamTransform [4]
protected vector m_NextCamPosition
protected float m_Time
protected Camera m_Camera1
protected Camera m_Camera2
protected ref array< ref Param6< vector, vector, float, float, float, int > > m_CameraLines
protected bool m_IsPlaying
protected int m_NextCameraIndex = 1
protected float m_FollowingTimeFinished
protected ref Param2< int, int > m_FollowingBone
protected CTKeyframe m_SelectedKeyframe
protected CTEvent m_SelectedEvent
protected CTActor m_SelectedActor
protected ref array< ref CTActor > m_Actors
protected ref array< ref CTKeyframe > m_Cameras
protected ref array< ref CTEvent > m_Events
protected Widget m_KeyframeContent
protected Widget m_EventContent
protected XComboBoxWidget m_InterpTypeSpeedCombo
protected XComboBoxWidget m_InterpTypeCombo
protected EditBoxWidget m_BlurEditWidget
protected EditBoxWidget m_ActorTypeWidget
protected EditBoxWidget m_ActorIdWidget
protected EditBoxWidget m_ActorItemTypeWidget
protected ButtonWidget m_AddItem
protected ButtonWidget m_AddHandsItem
protected ButtonWidget m_AddActor
protected ButtonWidget m_Play
protected ButtonWidget m_Stop
protected ButtonWidget m_Save
protected ButtonWidget m_Load
protected ButtonWidget m_AddKeyframe
protected ButtonWidget m_SaveKeyframe
protected ButtonWidget m_DeleteKeyframe
protected ButtonWidget m_ViewKeyframe
protected ButtonWidget m_AddEvent
protected ButtonWidget m_SaveEvent
protected ButtonWidget m_DeleteEvent
protected ButtonWidget m_ViewEvent
protected ButtonWidget m_CopyButton
protected ButtonWidget m_ApplyButton
protected EditBoxWidget m_CameraEditbox
protected TextWidget m_CameraValues
private EditBoxWidget m_edit_box
private TextWidget m_channel_text
private UAIDWrapper m_BackInputWrapper
private ref Timer m_close_timer
protected string m_BackButtonTextID
protected string m_NextPresetText
protected int m_CurrentTabIdx = -1
protected int m_CurrentPresetVariant = -1
protected ButtonWidget m_Back
protected ImageWidget m_ControlsLayoutImage
protected CanvasWidget m_CanvasWidget
protected TabberUI m_TabScript
protected Widget m_TabberWidget
protected Widget m_ControlsImage
protected Widget m_PlatformHolder
protected Widget m_VariantWidget
protected ref map< int, Widget > m_ImageMarkerStructure
protected ref map< int, Widget > m_CategoryStructure
protected ref map< int, ref TButtonPairingInfo > m_AreasLR
protected const int AREA_LEFT = 1
protected const int AREA_RIGHT = 2
protected const int PLATFORM_ADJUST_X1 = 1000
protected const int PLATFORM_ADJUST_PS = 2000
protected Widget m_GestureItemCardPanel
protected ref array< ref GestureMenuItem > m_GestureItems
protected Widget m_ToolbarPanel
protected TextWidget m_CategoryNameText
const string RADIAL_TEXT = "RadialText"
const string GESTURE_TEXT = "GestureNameText"
const string INPUT_TEXT = "InputActionText"
const string CATEGORY_NAME = "CategoryName"
protected Widget m_SelectedItem
protected bool m_IsCategorySelected
protected bool m_IsMenuClosing
protected int m_CurrentCategory
TextListboxWidget m_KeyBindingsTextListboxWidget
TextListboxWidget m_MouseBindingsTextListboxWidget
ButtonWidget m_CloseConsoleButton
string m_ServerInfoText
protected Widget m_ContinueButton
protected Widget m_SeparatorPanel
protected Widget m_ExitButton
protected Widget m_RestartButton
protected Widget m_RespawnButton
protected Widget m_RestartDeadRandomButton
protected Widget m_RestartDeadCustomButton
protected Widget m_OptionsButton
protected Widget m_ServerInfoPanel
protected Widget m_FavoriteButton
protected Widget m_FavoriteImage
protected Widget m_UnfavoriteImage
protected Widget m_CopyInfoButton
protected ref TextWidget m_ModdedWarning
protected ref TextWidget m_ServerIP
protected ref TextWidget m_ServerPort
protected ref TextWidget m_ServerName
protected ref UiHintPanel m_HintPanel
protected string m_MuteButtonTextID
protected string m_UnmuteButtonTextID
protected string m_SelectButtonTextID
protected string m_OpenGameCardButtonTextID
protected string m_CurrentMuteButtonText
protected bool m_SelectAvailable
protected bool m_MuteAvailable
protected bool m_BackAvailable
protected bool m_GamercardAvailable
protected bool m_PlayerAlive
protected ref PlayerListScriptedWidget m_ServerInfoPanel
protected Widget m_OnlineMenu
protected ButtonWidget m_ContinueButton
protected ButtonWidget m_ExitButton
protected ButtonWidget m_RestartDeadButton
protected ButtonWidget m_RestartButton
protected ButtonWidget m_OptionsButton
protected ButtonWidget m_ControlsButton
protected ButtonWidget m_OnlineButton
protected ButtonWidget m_TutorialsButton
protected TextWidget m_Version
const int BUTTON_XBOX_CONTROLS = 201
private ref array< int > m_DisconnectedDevices
private ref array< int > m_DeviceOrder = {EUAINPUT_DEVICE_CONTROLLER,EUAINPUT_DEVICE_MOUSE,EUAINPUT_DEVICE_KEYBOARD}
private ref map< int, string > m_DeviceMessages
private bool m_CanClose
private bool m_Initialized
private string m_DevicesText
private string m_CaptionText
private string m_ConfirmationText
private WrapSpacerWidget m_WrapperWidget
private TextWidget m_CaptionWidget
private RichTextWidget m_DeviceListWidget
private RichTextWidget m_ActionTextWidget
private ItemPreviewWidget m_item_widget
private ItemPreviewWidget m_slot_widget
private int m_characterRotationX
private int m_characterRotationY
private int m_characterScaleDelta
private vector m_characterOrientation
private TextWidget m_LogoutTimetext
private TextWidget m_Info
private int m_iTime
TextWidget m_label
ProgressBarWidget m_progressBar
ImageWidget m_image
private TextWidget m_LogoutTimeText
private TextWidget m_DescriptionText
private ButtonWidget m_bLogoutNow
private ButtonWidget m_bCancel
private ButtonWidget m_bCancelConsole
protected const string COORD_FORMAT = "%1.%2%3"
protected const int SCALE_RULER_LINE_WIDTH = 8
protected const int SCALE_RULER_NUM_SEGMENTS = 10
protected bool m_WasChanged
protected bool m_HasCompass protected bool m_HasGPS protected bool m_IsOpenning
protected float m_ToolScaleCellSizeCanvasWidth
protected ref IngameHud m_Hud
protected ref MapHandler m_MapMenuHandler
protected ref MapWidget m_MapWidgetInstance
protected ref SizeToChild m_LegendResizer
protected ImageWidget m_Images
protected Widget m_GPSMarker
protected ImageWidget m_GPSMarkerArrow
protected Widget m_UpperLegendContainer
protected Widget m_ToolsCompassBase
protected ImageWidget m_ToolsCompassArrow
protected TextWidget m_ToolsCompassAzimuth
protected TextWidget m_ToolsScaleContourText
protected TextWidget m_ToolsGPSElevationText
protected TextWidget m_ToolsGPSXText
protected TextWidget m_ToolsGPSYText
protected TextWidget m_ToolsScaleCellSizeText
protected CanvasWidget m_ToolsScaleCellSizeCanvas
protected ItemMap m_Map
protected ref MapNavigationBehaviour m_MapNavigationBehaviour
DayZIntroScenePC m_Scene
const int TOOLTIP_ID_SAVE = 1
const int TOOLTIP_ID_APPLY = 2
protected Widget m_CharacterRotationFrame
protected Widget m_Apply
protected Widget m_Save
protected Widget m_RandomizeCharacter
protected Widget m_BackButton
protected Widget m_PlayedCharacterInfo
protected Widget m_DetailsRoot
protected TextWidget m_DetailsLabel
protected RichTextWidget m_DetailsText
protected TextWidget m_CharacterHeaderText
protected ref OptionSelectorEditbox m_NameSelector
protected ref OptionSelectorMultistateCharacterMenu m_GenderSelector
protected ref OptionSelectorMultistateCharacterMenu m_SkinSelector
protected ref OptionSelectorMultistateCharacterMenu m_TopSelector
protected ref OptionSelectorMultistateCharacterMenu m_BottomSelector
protected ref OptionSelectorMultistateCharacterMenu m_ShoesSelector
int m_OriginalCharacterID
protected float m_MenuFadeInIncrement
protected float m_MenuFadeInLevel
protected float m_MenuFadeInLevel2 = 1
protected float m_LogoFadeInIncrement
protected float m_LogoFadeInLevel
protected float m_ScrollIncrement
protected float m_ScrollLevel
protected float m_ScrollMax
protected float m_ScrollSize
protected ref JsonDataCredits m_CreditsData
protected float m_CurrentTime = 0.0
protected ref array< ref CreditsElement > m_CreditsEntries = new array<ref CreditsElement>
protected ImageWidget m_Logo
protected ScrollWidget m_Scroller
protected WrapSpacerWidget m_Content
protected RichTextWidget m_InfoPanelText
protected Widget m_InfoPanel
protected TabberUI m_Tabber
protected ref DropdownPrefab m_KBDropdown
protected ref OptionSelectorMultistate m_PresetSelector
protected ref KeybindingsContainer m_GroupsContainer
protected ref array< ref KeybindingsGroup > m_Tabs
protected ButtonWidget m_Apply
protected ButtonWidget m_Undo
protected ButtonWidget m_Defaults
protected ButtonWidget m_HardReset
protected int m_CurrentSettingKeyIndex = -1
protected int m_CurrentSettingAlternateKeyIndex = -1
protected int m_OriginalPresetIndex
protected int m_TargetPresetIndex
protected ref array< int > m_SetKeybinds
const int MODAL_ID_BACK = 1337
const int MODAL_ID_DEFAULT = 100
const int MODAL_ID_DEFAULT_ALL = 101
const int MODAL_ID_PRESET_CHANGE = 200
const int MODAL_RESULT_DEFAULT_CURRENT = 0
const int MODAL_RESULT_DEFAULT_ALL = 1
protected ref MainMenuStats m_Stats
protected ref MainMenuVideo m_Video
protected MissionMainMenu m_Mission
protected DayZIntroScenePC m_ScenePC
protected TextWidget m_PlayerName
protected Widget m_Play
protected Widget m_ChooseServer
protected Widget m_CustomizeCharacter
protected Widget m_PlayVideo
protected Widget m_Tutorials
protected Widget m_TutorialButton
protected Widget m_MessageButton
protected Widget m_SettingsButton
protected Widget m_Exit
protected Widget m_NewsMain
protected Widget m_NewsSec1
protected Widget m_NewsSec2
protected Widget m_PrevCharacter
protected Widget m_NextCharacter
protected Widget m_LastPlayedTooltip
protected Widget m_LastPlayedTooltipLabel
protected TextWidget m_LastPlayedTooltipName
protected TextWidget m_LastPlayedTooltipIP
protected TextWidget m_LastPlayedTooltipPort
protected ref WidgetFadeTimer m_LastPlayedTooltipTimer
protected ref Widget m_LastFocusedButton
protected ref ModsMenuSimple m_ModsSimple
protected ref ModsMenuDetailed m_ModsDetailed
protected ref ModsMenuTooltip m_ModsTooltip
protected Widget m_OpenDLC
protected Widget m_ChangeAccount
protected Widget m_Options
protected Widget m_Controls
protected VideoWidget m_Video
protected ref Timer m_VideoPlayTimer
protected ref WidgetFadeTimer m_VideoFadeTimer
bool m_IsPaused
protected const string PATH_MOUSEKEY = "Scripts/data/PageDataTutorials.json"
protected const string PATH_X1_OLD = "Xbox/PageDataTutorials.json"
protected const string PATH_X1_NEW = "Xbox/PageDataTutorialsAlternate.json"
protected const string PATH_PS_OLD = "PS4/PageDataTutorials.json"
protected const string PATH_PS_NEW = "PS4/PageDataTutorialsAlternate.json"
protected Widget m_InfoTextLeft
protected Widget m_InfoTextRight
protected const int TABS_COUNT = 4
protected ImageWidget m_tab_images [TABS_COUNT]
protected ref TutorialKeybinds m_KeybindsTab
const int DIALOG_TAB_OFFSET = 1400
protected ref OptionsMenuGame m_GameTab
protected ref OptionsMenuSounds m_SoundsTab
protected ref OptionsMenuVideo m_VideoTab
protected ref OptionsMenuControls m_ControlsTab
protected ref GameOptions m_Options
protected ButtonWidget m_Reset
protected Widget m_Details
protected int m_ActiveTabIdx = 0
protected bool m_ModalLock
protected bool m_CanApplyOrReset
protected bool m_CanToggle
protected Widget m_Back
protected ref ServerBrowserTab m_OfficialTab
protected ref ServerBrowserTab m_CommunityTab
protected ref ServerBrowserTab m_FavoritesTab
protected ref ServerBrowserTab m_LANTab
protected TabType m_IsRefreshing = TabType.NONE
protected ref TStringArray m_Favorites
protected ServerBrowserEntry m_SelectedServer
protected MultilineEditBoxWidget m_edit
protected HtmlWidget m_html
protected ButtonWidget m_confirm_button
protected ItemBase m_Paper
protected EntityAI m_Pen
protected bool m_IsWriting
protected int m_SymbolCount
protected string m_PenColor
private TextListboxWidget m_schemes_list
protected Widget m_ItemCardPanel
protected ref array< ref RadialQuickbarItem > m_Items
const string TEXT_ITEM_NAME = "ItemName"
const string TEXT_ITEM_TITLE = "ItemTitle"
const int ID_RESPAWN_CUSTOM = 101
const int ID_RESPAWN_RANDOM = 102
protected Widget m_CustomRespawn
protected Widget m_CurrentlyHighlighted
const string CONST_DEFAULT_PRESET_PREFIX = "[Default]"
protected Widget m_WgtRoot
protected PluginSceneManager m_ModuleSceneManager
protected ButtonWidget m_WgtBtnSceneManager
protected ButtonWidget m_WgtBtnSceneSettings
protected ButtonWidget m_WgtBtnSceneSave
protected ButtonWidget m_WgtBtnEditorSettings
protected ButtonWidget m_WgtBtnDeleteRuler
protected Widget m_WgtPopupsMain
protected Widget m_WgtPopupsBg
protected ref TIntArray m_OpenedPopups
protected ref map< int, ref UIPopupScript > m_Popups
protected TextWidget m_SlWgtLoadedScene
protected string m_SlSelectedClass
protected ref map< int, SceneObject > m_SlObjectsList
protected TextListboxWidget m_SlWgtLbxObjectsList
protected EditBoxWidget m_SlWgtEbxFilter
protected ButtonWidget m_SlWgtSelect
protected ButtonWidget m_SlWgtFocus
protected string m_ClSelectedClass
protected ref TStringArray m_ClClassesList
protected EditBoxWidget m_ClWgtEbxFilter
protected TextListboxWidget m_ClWgtLbxClassesList
protected ButtonWidget m_ClWgtButtonAddAtt
protected TextWidget m_PrWgtClassName
protected EditBoxWidget m_PrWgtPoxX
protected EditBoxWidget m_PrWgtPoxY
protected EditBoxWidget m_PrWgtPoxZ
protected EditBoxWidget m_PrWgtDir
protected EditBoxWidget m_PrWgtDmg
protected ButtonWidget m_WgtBtnEditInitScript
protected Widget m_PrWgtAttRoot
protected Widget m_PrWgtAttTitle
protected ref array< ref UIPropertyAttachment > m_PrWidgetsAttachments
protected ref WidgetFadeTimer m_NotifyFadeTimer
protected Widget m_NotifyWgtPanel
protected TextListboxWidget m_PresetsTextListbox
protected TextListboxWidget m_PresetItemsTextListbox
protected ButtonWidget m_PresetAddItemtButton
protected ButtonWidget m_PresetRemoveItemButton
protected ButtonWidget m_SpawnOnGroundButton
protected ButtonWidget m_SpawnInInventoryButton
protected ButtonWidget m_SpawnAsAttachmentButton
protected ButtonWidget m_UpButton
protected ButtonWidget m_DownButton
protected ButtonWidget m_PresetNewButton
protected ButtonWidget m_PresetDeleteButton
protected ButtonWidget m_PresetRenameButton
protected ButtonWidget m_PresetSetDefaultButton
protected ButtonWidget m_CopyToClipboardButton
protected EditBoxWidget m_DamageEditBox
protected EditBoxWidget m_QuantityEditBox
protected EditBoxWidget m_SpawnDistanceEditBox
protected EditBoxWidget m_ConfigsButton
protected Widget m_WgtPnlWrapper
protected ButtonWidget m_WgtBtnLeftPresets
protected ButtonWidget m_WgtBtnPositionManager
protected string m_SelectedObject
protected bool m_SelectedObjectIsPreset
protected PluginDeveloper m_Developer
protected UIPopupScriptPositionManager m_PopupScriptPositionManager
protected PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
protected PluginConfigDebugProfile m_ConfigDebugProfile
const string DEFAULT_POS_XYZ = "<1,2,3>"
protected ref map< CheckBoxWidget, int > m_ClassCheckboxes = new map<CheckBoxWidget, int>
vector m_MapPos
bool m_PlayerPosRefreshBlocked
ref array< Object > m_VicinityItems = new array<Object>
Widget m_WgtClassesConfig
int m_RunColor
ref TStringArray m_BaseConfigClasses = new TStringArray
ref TStringArray m_BaseConfigClassesToggled = new TStringArray
PluginItemDiagnostic m_ItemDisagPlugin
ref array< Widget > m_CategoryButtonsWidgets = new array<Widget>
ref array< string > m_CategoryButtonsNames = {"FIREARMS","MELEE","ATTACHMENTS","MAGAZINES","AMMO","FOOD","MEDICAL","CARS","BACKPACKS"}
SliderWidget m_TimeSlider
ref Timer m_LateInit = new Timer()
bool m_ScriptServer
bool m_UpdateMap
int m_CategoryMask
bool m_FilterOrderReversed
bool m_AllowScriptOutput
ref Timer m_RefreshFilterTimer = new Timer()
int m_selected_tab
int m_ServerRows
int m_EnscriptHistoryRow
int m_EnscriptHistoryRowServer
ref TStringArray m_EnscriptConsoleHistory
ref TStringArray m_EnscriptConsoleHistoryServer
PluginLocalEnscriptHistory m_ModuleLocalEnscriptHistory
PluginLocalEnscriptHistoryServer m_ModuleLocalEnscriptHistoryServer
MissionGameplay m_MissionGameplay
Widget m_ButtonsWindowWidget
TextListboxWidget m_ClientLogListbox
TextListboxWidget m_ScriptOutputListbox
ButtonWidget m_ClientLogClearButton
CheckBoxWidget m_ClientLogScrollCheckbox
TextListboxWidget m_DiagToggleTextListbox
ButtonWidget m_DiagToggleButton
TextListboxWidget m_DiagDrawmodeTextListbox
ButtonWidget m_DiagDrawButton
ButtonWidget m_DrawInWorld
ButtonWidget m_DrawInWorldClear
MultilineEditBoxWidget m_EnfScriptEdit
ButtonWidget m_EnfScriptRun
ButtonWidget m_EnfScriptClear
ButtonWidget m_TeleportButton
ButtonWidget m_ButtonCopyPos
EditBoxWidget m_TeleportX
EditBoxWidget m_TeleportY
EditBoxWidget m_TeleportXYZ
EditBoxWidget m_DateYear
EditBoxWidget m_DateMonth
EditBoxWidget m_DateDay
EditBoxWidget m_DateHour
EditBoxWidget m_DateMinute
ButtonWidget m_CopySoundset
ButtonWidget m_PlaySoundset
ButtonWidget m_PlaySoundsetLooped
ButtonWidget m_StopSoundset
ButtonWidget m_LocationAddButton
ButtonWidget m_LocationRemoveButton
ButtonWidget m_FilterOrderButton
TextWidget m_PlayerCurPos
TextWidget m_MouseCurPos
TextWidget m_PlayerMouseDiff
TextListboxWidget m_PositionsListbox
CheckBoxWidget m_LogsEnabled
CheckBoxWidget m_HudDCharStats
CheckBoxWidget m_HudDCharLevels
CheckBoxWidget m_HudDCharStomach
CheckBoxWidget m_HudDCharModifiers
CheckBoxWidget m_HudDCharAgents
CheckBoxWidget m_HudDCharDebug
CheckBoxWidget m_HudDFreeCamCross
CheckBoxWidget m_HudDVersion
CheckBoxWidget m_ShowProtected
CheckBoxWidget m_ShowOthers
CheckBoxWidget m_ClearInventory
CheckBoxWidget m_HudDTemperature
CheckBoxWidget m_CategoryMergeType
CheckBoxWidget m_ItemPreviewCheckbox
ImageWidget m_FilterOrderImage
EditBoxWidget m_ObjectFilter
EditBoxWidget m_SpawnDistanceEditBox
TextWidget m_SelectedObjectText
string m_SelectedObject
TextListboxWidget m_ObjectsTextListbox
EditBoxWidget m_SoundFilter
TextListboxWidget m_SoundsTextListbox
TextListboxWidget m_PresetsTextListbox
TextListboxWidget m_PresetItemsTextListbox
ButtonWidget m_PresetNewButton
ButtonWidget m_PresetDeleteButton
ButtonWidget m_PresetRenameButton
ButtonWidget m_PresetSetDefaultButton
ButtonWidget m_PresetAddItemtButton
ButtonWidget m_ItemNameCopy
ButtonWidget m_PresetRemoveItemButton
ButtonWidget m_ItemMoveUpButton
ButtonWidget m_ItemMoveDownButton
EditBoxWidget m_DrawDistanceWidget
EditBoxWidget m_QuantityEditBox
EditBoxWidget m_DamageEditBox
TextWidget m_ItemDamageLabel
TextWidget m_ItemQuantityLabel
ButtonWidget m_SpawnInInvButton
ButtonWidget m_SpawnGroundButton
ButtonWidget m_SpawnGroundPatternGrid
ButtonWidget m_SpawnAsAttachment
ButtonWidget m_SpawnSpecial
ButtonWidget m_WatchItem
ButtonWidget m_SpawnBatchButton
ButtonWidget m_PlaySoundsetButton
EditBoxWidget m_RectSpawnRow
EditBoxWidget m_RectSpawnColumn
EditBoxWidget m_RectSpawnRowStep
EditBoxWidget m_RectSpawnColumnStep
EditBoxWidget m_BatchSpawnQuantity
EditBoxWidget m_ObjectConfigFilter
TextListboxWidget m_ConfigHierarchyTextListbox
TextListboxWidget m_ConfigVariablesTextListbox
ButtonWidget m_SelectedRowCopy
ButtonWidget m_DumpParamButton
ItemPreviewWidget m_ItemPreviewWidget
TextListboxWidget m_HelpTextListboxWidget
TextListboxWidget m_VicinityListbox
Widget m_Tabs [TABS_COUNT]
MapWidget m_DebugMapWidget
ButtonWidget m_Tab_buttons [TABS_COUNT]
ref array< ref RemotePlayerStatDebug > m_PlayerDebugStats = new array<ref RemotePlayerStatDebug>
PluginDeveloper m_Developer
PluginConfigDebugProfile m_ConfigDebugProfile
PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
PluginConfigViewer m_ModuleConfigViewer
EditBoxWidget m_EditboxName
EditBoxWidget m_EditboxPos
TextWidget m_Label
TextWidget m_Message
ButtonWidget m_ClearButton
EditBoxWidget m_Editbox
RichTextWidget m_TextPress
Static Private Attributes
static protected CameraToolsMenu m_Instance
static GesturesMenu instance
static protected float MENU_FADEIN_TIME = 2.0
static protected float LOGO_FADEIN_TIME = 1.0
static protected float CREDIT_SCROLL_SPEED = 200.0
static EntityAI m_ItemToAssign
static RadialQuickbarMenu instance
static const int POPUP_ID_SCENE_MANAGER = 0
static const int POPUP_ID_SCENE_SETTINGS = 1
static const int POPUP_ID_SCENE_NEW = 2
static const int POPUP_ID_SCENE_RENAME = 3
static const int POPUP_ID_SCENE_DELETE = 4
static const int POPUP_ID_NOTIFY = 5
static const int POPUP_ID_EDITOR_SETTINGS = 6
static const int POPUP_ID_INIT_SCRIPT = 7
static const int POPUP_ID_POSITION_MANAGER = 8
static const int POPUP_ID_PRESET_NEW = 9
static const int POPUP_ID_PRESET_RENAME = 10
static const int POPUP_ID_CONFIGS = 11
static ScriptConsole m_This
static EffectSound m_SoundSet
static ref ConfigParamsEx m_ConfigData
static float DEBUG_MAP_ZOOM = 1
static int ITEMS_SELECTED_ROW = -1
static int PRESETS_SELECTED_ROW = 0
static int ITEMS_IN_PRESET_SELECTED_ROW
static int m_ObjectsScope = 2
static bool SHOW_OTHERS = 0
static bool CLEAR_IVN
static float DRAW_DISTANCE = 1000
static ref array< Shape > m_DebugShapes = new array<Shape>
static EntityAI m_PreviewEntity
static ref TStringArray m_ScriptOutputHistory = new TStringArray()
static string m_LastSelectedObject
static int m_SelectedObjectIsPreset = -1
static const int TABS_GENERAL = 0
static const int TAB_ITEMS = 1
static const int TAB_CONFIGS = 2
static const int TAB_ENSCRIPT = 3
static const int TAB_ENSCRIPT_SERVER = 4
static const int TABS_OUTPUT = 5
static const int TABS_VICINITY = 6
static const int TABS_SOUNDS = 7
static const int TABS_COUNT = 8
static string m_ConfigTextField
Detailed Description
Xbox menu
Definition at line 35 of file DayZGame.c.
Constructor & Destructor Documentation
~LoginQueueBase()
void ~LoginQueueBase () inline private
Definition at line 51 of file DayZGame.c.
References g_Game.
~LoginTimeBase()
void ~LoginTimeBase () inline private
Definition at line 167 of file DayZGame.c.
References g_Game.
~CameraToolsMenu()
void ~CameraToolsMenu () inline private
Definition at line 73 of file CameraToolsMenu.c.
References DeveloperFreeCamera::DisableFreeCamera(), GetGame(), and GetPlayer().
~ControlsXboxNew()
void ~ControlsXboxNew () inline private
Definition at line 58 of file ControlsXboxNew.c.
~EarlyAccessMenu()
void ~EarlyAccessMenu () inline private
Definition at line 7 of file EarlyAccessMenu.c.
~GesturesMenu()
void ~GesturesMenu () inline private
Definition at line 143 of file GesturesMenu.c.
References GetGame(), CGame::GetMission(), and Mission::RemoveActiveInputExcludes().
~HelpScreen()
void ~HelpScreen () inline private
Definition at line 13 of file HelpScreen.c.
~InGameMenu()
void ~InGameMenu () inline private
Definition at line 26 of file InGameMenu.c.
References Mission::Continue(), g_Game, HudShow(), and mission.
~InGameMenuXbox()
void ~InGameMenuXbox () inline private
Definition at line 43 of file InGameMenuXbox.c.
References Mission::Continue(), GetGame(), Mission::GetHud(), CGame::GetMission(), OnlineServices::m_PermissionsAsyncInvoker, mission, ScriptInvoker::Remove(), and ClientData::SyncEvent_OnPlayerListUpdate.
~InputDeviceDisconnectWarningMenu()
void ~InputDeviceDisconnectWarningMenu () inline private
Definition at line 27 of file InputDeviceDisconnectWarningMenu.c.
References g_Game.
~InspectMenuNew()
void ~InspectMenuNew () inline private
Definition at line 18 of file InspectMenuNew.c.
References CGame::GetDragQueue(), GetGame(), Mission::GetHud(), CGame::GetMission(), Hud::ShowHudUI(), and Hud::ShowQuickbarUI().
~WarningMenuBase()
void ~WarningMenuBase () inline private
Definition at line 8 of file ItemDropWarningMenu.c.
References GetGame(), CGame::GetMission(), and Mission::RemoveActiveInputExcludes().
~LoadingMenu()
void ~LoadingMenu () inline private
Definition at line 7 of file LoadingMenu.c.
~LogoutMenu()
void ~LogoutMenu () inline private
Definition at line 17 of file LogoutMenu.c.
References g_Game.
~CharacterCreationMenu()
void ~CharacterCreationMenu () inline private
Definition at line 148 of file CharacterCreationMenu.c.
~MainMenu()
void ~MainMenu () inline private
Definition at line 109 of file MainMenu.c.
~MainMenuVideo()
void ~MainMenuVideo () inline private
Definition at line 33 of file MainMenuVideo.c.
~TutorialsMenu()
void ~TutorialsMenu () inline private
Definition at line 67 of file TutorialsMenu.c.
References DrawConnectingLines(), and m_TabScript.
~OptionsMenu()
void ~OptionsMenu () inline private
Definition at line 97 of file OptionsMenu.c.
~ServerBrowserMenuNew()
void ~ServerBrowserMenuNew () inline private
Definition at line 99 of file ServerBrowserMenuNew.c.
References OnlineServices::m_ServerModLoadAsyncInvoker, OnlineServices::m_ServersAsyncInvoker, OnLoadServerModsAsync(), ScriptInvoker::Remove(), and SaveFavoriteServersConsoles().
~NoteMenu()
void ~NoteMenu () inline private
Definition at line 26 of file NoteMenu.c.
References GetGame(), Mission::GetHud(), and mission.
~PresetsMenu()
void ~PresetsMenu () inline private
Definition at line 7 of file PresetsMenu.c.
~RadialQuickbarMenu()
void ~RadialQuickbarMenu () inline private
Definition at line 122 of file RadialQuickbarMenu.c.
References GetGame(), CGame::GetMission(), and Mission::RemoveActiveInputExcludes().
~RespawnDialogue()
void ~RespawnDialogue () private
~SceneEditorMenu()
void ~SceneEditorMenu () inline private
Definition at line 376 of file SceneEditorMenu.c.
References IsModuleExist(), and PopupCloseAll().
~ScriptConsole()
void ~ScriptConsole () inline private
Definition at line 60 of file ScriptConsole.c.
References SEffectManager::DestroyEffect(), Mission::EnableAllInputs(), GetGame(), Mission::GetHud(), CGame::GetMission(), GetPlayer(), GetPlugin(), m_ConfigDebugProfile, Hud::ShowHudPlayer(), and Hud::ShowQuickbarPlayer().
~ScriptConsoleAddLocation()
void ~ScriptConsoleAddLocation () inline private
Definition at line 8 of file ScriptConsoleAddPosition.c.
~ScriptConsoleNewPresetDialog()
void ~ScriptConsoleNewPresetDialog () inline private
Definition at line 8 of file ScriptConsoleNewPresetDialog.c.
~ScriptConsoleRenamePresetDialog()
void ~ScriptConsoleRenamePresetDialog () inline private
Definition at line 8 of file ScriptConsoleRenamePresetDialog.c.
~StartupMenu()
void ~StartupMenu () inline private
Definition at line 7 of file StartupMenu.c.
~TitleScreenMenu()
void ~TitleScreenMenu () inline private
Definition at line 12 of file TitleScreenMenu.c.
Member Function Documentation
Add()
void Add (string message, bool isReload = false) inline private
Definition at line 528 of file ScriptConsole.c.
References Empty, and String().
Referenced by Dispatcher::ScriptConsoleAddPrint().
AddActor()
void AddActor (string actor_type) inline private
Definition at line 315 of file CameraToolsMenu.c.
AddEvent()
void AddEvent (int actor_index) inline private
Definition at line 323 of file CameraToolsMenu.c.
AddFavorite()
void AddFavorite (string ipAddress, int port, bool favorite) inline private
Definition at line 243 of file ServerBrowserMenuNew.c.
References IsFavorited().
Referenced by SetFavoriteConsoles().
AddFavoritesToFilter()
void AddFavoritesToFilter (GetServersInput input) inline private
Definition at line 203 of file ServerBrowserMenuNew.c.
References GetServersInput::AddFavourite().
AddGroup()
void AddGroup (int index, Input input) inline private
Definition at line 528 of file KeybindingsMenu.c.
AddHandsItem()
void AddHandsItem (string id, string type) inline private
Definition at line 344 of file CameraToolsMenu.c.
AddItem()
void AddItem (string id, string type) inline private
Definition at line 333 of file CameraToolsMenu.c.
AddItemToClipboard()
void AddItemToClipboard (TextListboxWidget text_listbox_widget) inline private
Definition at line 2442 of file ScriptConsole.c.
References CGame::CopyToClipboard(), and GetGame().
AddItemToPreset() [1/2]
void AddItemToPreset () inline private
Definition at line 246 of file SceneEditorMenu.c.
References GetCurrentPresetIndex(), GetCurrentPresetName(), m_ConfigDebugProfile, and RenderPresetItems().
Referenced by OnClick().
AddItemToPreset() [2/2]
void AddItemToPreset () inline private
Definition at line 2416 of file ScriptConsole.c.
References m_ConfigDebugProfile.
AddKeyframe()
void AddKeyframe () inline private
Definition at line 271 of file CameraToolsMenu.c.
AddMarker()
void AddMarker (vector pos, int color, int icon = 0) inline private
Definition at line 290 of file MapMenu.c.
References MapMarkerTypes::GetMarkerTypeFromID().
AddServer()
void AddServer (string message) inline private
Definition at line 552 of file ScriptConsole.c.
Apply() [1/3]
void Apply () inline private
renames character
Definition at line 159 of file CharacterCreationMenu.c.
References UIManager::Back(), GameConstants::DEFAULT_CHARACTER_NAME, GetGame(), DayZIntroSceneXbox::GetIntroCharacter(), CGame::GetUIManager(), MENU_MAIN, and name.
Referenced by OnClick(), and Update().
Apply() [2/3]
void Apply () inline private
Definition at line 221 of file KeybindingsMenu.c.
References ColorDisabled(), ColorWhite(), UAInputAPI::Export(), and GetUApi().
Apply() [3/3]
void Apply () inline private
Definition at line 182 of file OptionsMenu.c.
References ColorDisable(), UAInputAPI::Export(), g_Game, GetGame(), GetInput(), GetUApi(), UpdateControlsElements(), and UpdateControlsElementVisibility().
AutoConnect()
void AutoConnect () inline private
Definition at line 496 of file MainMenu.c.
References OnlineServices::AutoConnectToEmptyServer().
Back() [1/6]
void Back () inline private
Definition at line 76 of file ControlsXboxNew.c.
References UIManager::Back(), GetGame(), and CGame::GetUIManager().
Referenced by OnClick(), OnClick(), Update(), and Update().
Back() [2/6]
void Back () inline private
Definition at line 194 of file CharacterCreationMenu.c.
References UIManager::Back(), GameConstants::DEFAULT_CHARACTER_MENU_ID, GetGame(), DayZIntroSceneXbox::GetIntroCharacter(), CGame::GetMenuData(), CGame::GetUIManager(), and MenuData::RequestGetDefaultCharacterData().
Back() [3/6]
void Back () inline private
Definition at line 236 of file KeybindingsMenu.c.
References UIManager::Back(), CancelEnteringAlternateKeybind(), CancelEnteringKeybind(), g_Game, GetGame(), and CGame::GetUIManager().
Back() [4/6]
void Back () inline private
Definition at line 93 of file TutorialsMenu.c.
References UIManager::Back(), GetGame(), and CGame::GetUIManager().
Back() [5/6]
void Back () inline private
Definition at line 218 of file OptionsMenu.c.
References UIManager::Back(), CGame::EndOptionsVideo(), g_Game, GetGame(), CGame::GetUIManager(), and IsAnyTabChanged().
Back() [6/6]
void Back () inline private
Definition at line 264 of file ServerBrowserMenuNew.c.
References UIManager::Back(), GetGame(), and CGame::GetUIManager().
BackButtonFocus()
void BackButtonFocus () inline private
Definition at line 322 of file ServerBrowserMenuNew.c.
References m_Back, and SetFocus().
BackOneLevel() [1/2]
protected void BackOneLevel () inline private
Definition at line 649 of file GesturesMenu.c.
BackOneLevel() [2/2]
protected void BackOneLevel () inline private
Definition at line 738 of file RadialQuickbarMenu.c.
BottomChanged()
void BottomChanged () inline private
Definition at line 279 of file CharacterCreationMenu.c.
References MenuDefaultCharacterData::EquipDefaultCharacter(), GetGame(), DayZIntroSceneXbox::GetIntroCharacter(), CGame::GetMenuDefaultCharacterData(), SetCharacterSaved(), and MenuDefaultCharacterData::SetDefaultAttachment().
BuildMessages()
private void BuildMessages () inline private
Definition at line 60 of file InputDeviceDisconnectWarningMenu.c.
Referenced by InputDeviceDisconnectWarningMenu().
ButtonSetAlphaAnim()
void ButtonSetAlphaAnim (Widget w) inline private
Definition at line 415 of file MainMenuConsoles.c.
Referenced by ColorHighlight(), and ColorNormal().
ButtonSetColor() [1/8]
void ButtonSetColor (Widget w, int color) inline private
Definition at line 706 of file ControlsXboxNew.c.
Referenced by ColorDisable(), ColorHighlight(), and ColorNormal().
ButtonSetColor() [2/8]
protected void ButtonSetColor (Widget w, int color) inline private
Definition at line 395 of file InGameMenu.c.
ButtonSetColor() [3/8]
void ButtonSetColor (Widget w, int color) inline private
Definition at line 673 of file InGameMenuXbox.c.
ButtonSetColor() [4/8]
void ButtonSetColor (Widget w, int color) inline private
Definition at line 589 of file MainMenu.c.
ButtonSetColor() [5/8]
void ButtonSetColor (Widget w, int color) inline private
Definition at line 402 of file MainMenuConsoles.c.
ButtonSetColor() [6/8]
void ButtonSetColor (Widget w, int color) inline private
Definition at line 505 of file TutorialsMenu.c.
ButtonSetColor() [7/8]
void ButtonSetColor (Widget w, int color) inline private
Definition at line 713 of file ServerBrowserMenuNew.c.
ButtonSetColor() [8/8]
protected void ButtonSetColor (Widget w, int color) inline private
Definition at line 171 of file RespawnDialogue.c.
ButtonSetText() [1/7]
void ButtonSetText (Widget w, string text) inline private
Definition at line 692 of file ControlsXboxNew.c.
Referenced by Init().
ButtonSetText() [2/7]
protected void ButtonSetText (Widget w, string text) inline private
Definition at line 381 of file InGameMenu.c.
ButtonSetText() [3/7]
void ButtonSetText (Widget w, string text) inline private
Definition at line 659 of file InGameMenuXbox.c.
ButtonSetText() [4/7]
void ButtonSetText (Widget w, string text) inline private
Definition at line 575 of file MainMenu.c.
ButtonSetText() [5/7]
void ButtonSetText (Widget w, string text) inline private
Definition at line 388 of file MainMenuConsoles.c.
ButtonSetText() [6/7]
void ButtonSetText (Widget w, string text) inline private
Definition at line 491 of file TutorialsMenu.c.
ButtonSetText() [7/7]
void ButtonSetText (Widget w, string text) inline private
Definition at line 699 of file ServerBrowserMenuNew.c.
ButtonSetTextColor() [1/8]
void ButtonSetTextColor (Widget w, int color) inline private
Definition at line 719 of file ControlsXboxNew.c.
Referenced by ColorDisable(), ColorHighlight(), and ColorNormal().
ButtonSetTextColor() [2/8]
protected void ButtonSetTextColor (Widget w, int color) inline private
Definition at line 408 of file InGameMenu.c.
ButtonSetTextColor() [3/8]
void ButtonSetTextColor (Widget w, int color) inline private
Definition at line 686 of file InGameMenuXbox.c.
ButtonSetTextColor() [4/8]
void ButtonSetTextColor (Widget w, int color) inline private
Definition at line 615 of file MainMenu.c.
ButtonSetTextColor() [5/8]
void ButtonSetTextColor (Widget w, int color) inline private
Definition at line 428 of file MainMenuConsoles.c.
ButtonSetTextColor() [6/8]
void ButtonSetTextColor (Widget w, int color) inline private
Definition at line 531 of file TutorialsMenu.c.
ButtonSetTextColor() [7/8]
void ButtonSetTextColor (Widget w, int color) inline private
Definition at line 726 of file ServerBrowserMenuNew.c.
ButtonSetTextColor() [8/8]
protected void ButtonSetTextColor (Widget w, int color) inline private
Definition at line 178 of file RespawnDialogue.c.
CameraToolsMenu()
void CameraToolsMenu () inline private
Definition at line 61 of file CameraToolsMenu.c.
References GetGame(), GetPlayer(), GetPosition, and m_Instance.
Cancel() [1/2]
void Cancel () inline private
Definition at line 69 of file InviteMenu.c.
References CALL_CATEGORY_SYSTEM, Close(), g_Game, CGame::GetCallQueue(), GetGame(), and ScriptCallQueue::Remove().
Referenced by OnClick(), OnKeyDown(), and Update().
Cancel() [2/2]
void Cancel () inline private
Definition at line 171 of file LogoutMenu.c.
References CALL_CATEGORY_SYSTEM, Mission::Continue(), CGame::GetCallQueue(), GetGame(), CGame::GetMission(), CGame::LogoutRequestCancel(), and ScriptCallQueue::Remove().
CancelEnteringAlternateKeybind()
void CancelEnteringAlternateKeybind () inline private
Definition at line 151 of file KeybindingsMenu.c.
Referenced by Back().
CancelEnteringKeybind()
void CancelEnteringKeybind () inline private
Definition at line 139 of file KeybindingsMenu.c.
Referenced by Back().
CanSaveDefaultCharacter()
bool CanSaveDefaultCharacter () inline private
Definition at line 367 of file MainMenu.c.
References DayZIntroScene::GetIntroCharacter().
CanStoreBeOpened()
bool CanStoreBeOpened () inline private
Definition at line 281 of file MainMenuConsoles.c.
References GetGame().
Referenced by Update(), and UpdateControlsElements().
ChangeAccount()
void ChangeAccount () inline private
Definition at line 322 of file MainMenuConsoles.c.
References UIManager::Back(), g_Game, GetGame(), CGame::GetUIManager(), CGame::GetUserManager(), and BiosUserManager::SelectUserEx().
Referenced by OnClick(), and Update().
ChangeConfigFilter()
void ChangeConfigFilter () inline private
Definition at line 926 of file ScriptConsole.c.
ChangeCurrentCategory()
protected void ChangeCurrentCategory (int category) inline private
Definition at line 519 of file RadialQuickbarMenu.c.
References RefreshQuickbar().
ChangeFilter()
void ChangeFilter (TStringArray classes, TextListboxWidget widget, EditBoxWidget filterWidget, int categoryMask = -1, bool ignoreScope = false) inline private
Definition at line 815 of file ScriptConsole.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), string::Contains(), GetGame(), m_ConfigDebugProfile, and string::ToLower().
ChangeFilterItems()
void ChangeFilterItems () inline private
Definition at line 2141 of file ScriptConsole.c.
References m_ConfigDebugProfile.
ChangeFilterSound()
void ChangeFilterSound () inline private
Definition at line 2147 of file ScriptConsole.c.
References m_ConfigDebugProfile.
CharacterCreationMenu()
void CharacterCreationMenu () inline private
Definition at line 34 of file CharacterCreationMenu.c.
References GetGame(), mission, and DayZIntroSceneXbox::ResetIntroCamera().
ChatInputMenu()
void ChatInputMenu () inline private
Definition at line 8 of file ChatInputMenu.c.
CheckForLightsAndNVG()
protected void CheckForLightsAndNVG (out ref array< ref RadialQuickbarItem > items, int last_idx) inline private
Definition at line 303 of file RadialQuickbarMenu.c.
References GetGame(), GetPlayer(), and RadialQuickbarItem().
CheckNewOptions()
void CheckNewOptions () inline private
Definition at line 451 of file CharacterCreationMenu.c.
References DayZIntroSceneXbox::GetIntroCharacter(), and SetFocus().
Referenced by Init(), OnInputDeviceChanged(), OnShow(), and RandomizeCharacter().
Clear()
void Clear (bool clearFile = false) inline private
Definition at line 672 of file ScriptConsole.c.
References Debug::ClearLogs().
ClearAlternativeKeybind()
void ClearAlternativeKeybind (int key_index) inline private
Definition at line 125 of file KeybindingsMenu.c.
References ColorWhite().
ClearHierarchy()
void ClearHierarchy () inline private
Definition at line 2698 of file ScriptConsole.c.
References string::Get().
ClearKeybind()
void ClearKeybind (int key_index) inline private
Definition at line 117 of file KeybindingsMenu.c.
References ColorWhite().
CloseMapMenu()
void CloseMapMenu () inline private
Definition at line 312 of file MapMenu.c.
References Close(), g_Game, GetGame(), CfgGameplayHandler::GetMapIgnoreMapOwnership(), CGame::GetMission(), CfgGameplayHandler::GetUse3DMap(), m_Hud, Mission::RemoveActiveInputExcludes(), Mission::RemoveActiveInputRestriction(), Hud::ShowHudUI(), and Hud::ShowQuickbarUI().
Referenced by OnClick(), and Update().
CloseMenu() [1/2]
static void CloseMenu () inline static private
Definition at line 159 of file GesturesMenu.c.
References UIManager::Back(), GetGame(), and CGame::GetUIManager().
CloseMenu() [2/2]
static void CloseMenu () inline static private
Definition at line 160 of file RadialQuickbarMenu.c.
References UIManager::Back(), GetGame(), and CGame::GetUIManager().
CloseOnline()
void CloseOnline () inline private
Definition at line 447 of file InGameMenuXbox.c.
References SetFocus(), and UpdateControlsElements().
Referenced by OnClick().
CollapseHierarchy()
void CollapseHierarchy (int row) inline private
Definition at line 2803 of file ScriptConsole.c.
References x.
ColorDisable() [1/4]
protected void ColorDisable (Widget w) inline private
Definition at line 372 of file InGameMenu.c.
References ARGB(), ButtonSetColor(), ButtonSetTextColor(), and ColorManager::COLOR_DISABLED_TEXT.
Referenced by Apply(), OnChanged(), Reset(), and ResetCurrentTab().
ColorDisable() [2/4]
void ColorDisable (Widget w) inline private
Definition at line 615 of file InGameMenuXbox.c.
References ARGB(), ButtonSetColor(), ButtonSetTextColor(), and SetFocus().
ColorDisable() [3/4]
void ColorDisable (Widget w) inline private
Definition at line 656 of file CharacterCreationMenu.c.
References ColorManager::COLOR_DISABLED_TEXT, and SetFocus().
ColorDisable() [4/4]
void ColorDisable (Widget w) inline private
Definition at line 759 of file OptionsMenu.c.
References ColorManager::COLOR_DISABLED_TEXT, and SetFocus().
ColorDisabled()
void ColorDisabled (Widget w) inline private
Definition at line 455 of file KeybindingsMenu.c.
References ColorManager::COLOR_DISABLED_TEXT, and SetFocus().
Referenced by Apply(), Init(), OnFocusLost(), OnMouseLeave(), PerformSetToDefaultsExt(), and Reset().
ColorHighlight() [1/10]
void ColorHighlight (Widget w) inline private
Definition at line 663 of file ControlsXboxNew.c.
References ARGB(), ButtonSetColor(), and ButtonSetTextColor().
Referenced by OnFocus(), and OnMouseEnter().
ColorHighlight() [2/10]
protected void ColorHighlight (Widget w) inline private
Definition at line 354 of file InGameMenu.c.
References ARGB(), ButtonSetColor(), and ButtonSetTextColor().
ColorHighlight() [3/10]
void ColorHighlight (Widget w) inline private
Definition at line 630 of file InGameMenuXbox.c.
References ARGB(), ButtonSetColor(), and ButtonSetTextColor().
ColorHighlight() [4/10]
void ColorHighlight (Widget w) inline private
Definition at line 556 of file CharacterCreationMenu.c.
References ARGB().
ColorHighlight() [5/10]
void ColorHighlight (Widget w) inline private
Definition at line 547 of file MainMenu.c.
References ARGB(), ButtonSetColor(), ButtonSetTextColor(), and ImagenSetColor().
ColorHighlight() [6/10]
void ColorHighlight (Widget w) inline private
Definition at line 341 of file MainMenuConsoles.c.
References ARGB(), ButtonSetAlphaAnim(), ButtonSetColor(), and ButtonSetTextColor().
ColorHighlight() [7/10]
void ColorHighlight (Widget w) inline private
Definition at line 458 of file TutorialsMenu.c.
References ARGB(), ButtonSetColor(), ButtonSetTextColor(), and ImagenSetColor().
ColorHighlight() [8/10]
void ColorHighlight (Widget w) inline private
Definition at line 658 of file OptionsMenu.c.
References ARGB().
ColorHighlight() [9/10]
void ColorHighlight (Widget w) inline private
Definition at line 670 of file ServerBrowserMenuNew.c.
References ARGB(), ButtonSetColor(), and ButtonSetTextColor().
ColorHighlight() [10/10]
protected void ColorHighlight (Widget w) inline private
Definition at line 145 of file RespawnDialogue.c.
References ARGB(), ButtonSetColor(), ButtonSetTextColor(), and ColorNormal().
ColorNormal() [1/10]
void ColorNormal (Widget w) inline private
Definition at line 680 of file ControlsXboxNew.c.
References ARGB(), ButtonSetColor(), and ButtonSetTextColor().
Referenced by ColorHighlight(), OnChanged(), OnFocusLost(), OnModalResult(), OnMouseLeave(), and PerformSetToDefaults().
ColorNormal() [2/10]
protected void ColorNormal (Widget w) inline private
Definition at line 363 of file InGameMenu.c.
References ARGB(), ButtonSetColor(), and ButtonSetTextColor().
ColorNormal() [3/10]
void ColorNormal (Widget w) inline private
Definition at line 647 of file InGameMenuXbox.c.
References ARGB(), ButtonSetColor(), and ButtonSetTextColor().
ColorNormal() [4/10]
void ColorNormal (Widget w) inline private
Definition at line 607 of file CharacterCreationMenu.c.
References ARGB(), and ColorManager::COLOR_NORMAL_TEXT.
ColorNormal() [5/10]
void ColorNormal (Widget w) inline private
Definition at line 561 of file MainMenu.c.
References ARGB(), ButtonSetColor(), ButtonSetTextColor(), and ImagenSetColor().
ColorNormal() [6/10]
void ColorNormal (Widget w) inline private
Definition at line 354 of file MainMenuConsoles.c.
References ARGB(), ButtonSetAlphaAnim(), ButtonSetColor(), and ButtonSetTextColor().
ColorNormal() [7/10]
void ColorNormal (Widget w) inline private
Definition at line 477 of file TutorialsMenu.c.
References ARGB(), ButtonSetColor(), ButtonSetTextColor(), and ImagenSetColor().
ColorNormal() [8/10]
void ColorNormal (Widget w) inline private
Definition at line 707 of file OptionsMenu.c.
References ARGB().
ColorNormal() [9/10]
void ColorNormal (Widget w) inline private
Definition at line 687 of file ServerBrowserMenuNew.c.
References ARGB(), ButtonSetColor(), and ButtonSetTextColor().
ColorNormal() [10/10]
protected void ColorNormal (Widget w) inline private
Definition at line 162 of file RespawnDialogue.c.
References ARGB(), ButtonSetColor(), and ButtonSetTextColor().
ColorRed() [1/2]
void ColorRed (Widget w) inline private
Definition at line 934 of file CameraToolsMenu.c.
References ARGB().
Referenced by OnFocus(), and OnMouseEnter().
ColorRed() [2/2]
void ColorRed (Widget w) inline private
Definition at line 424 of file KeybindingsMenu.c.
References ARGB(), and SetFocus().
ColorRunButton()
void ColorRunButton (bool success) inline private
Definition at line 726 of file ScriptConsole.c.
References ARGB(), CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
ColorWhite() [1/2]
void ColorWhite (Widget w, Widget enterW) inline private
Definition at line 945 of file CameraToolsMenu.c.
References ARGB().
Referenced by Apply(), ClearAlternativeKeybind(), ClearKeybind(), ConfirmAlternateKeybindEntry(), ConfirmKeybindEntry(), Init(), OnFocusLost(), and OnMouseLeave().
ColorWhite() [2/2]
void ColorWhite (Widget w, Widget enterW) inline private
Definition at line 435 of file KeybindingsMenu.c.
References ColorManager::COLOR_DISABLED_TEXT, ColorManager::COLOR_NORMAL_TEXT, and SetFocus().
ComponentsOnChange()
private bool ComponentsOnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 1298 of file SceneEditorMenu.c.
References x, and y.
Referenced by OnChange().
ComponentsOnClick()
private bool ComponentsOnClick (Widget w, int x, int y, int button) inline private
Definition at line 1274 of file SceneEditorMenu.c.
References x, and y.
Referenced by OnClick().
ComposeData()
protected void ComposeData () inline private
Inits data structure.
Definition at line 524 of file ControlsXboxNew.c.
References FindChildByID(), and InputUtils::UpdateConsolePresetID().
Referenced by Init().
ConfirmAlternateKeybindEntry()
void ConfirmAlternateKeybindEntry (TIntArray new_keys) inline private
Definition at line 166 of file KeybindingsMenu.c.
References ColorWhite().
ConfirmKeybindEntry()
void ConfirmKeybindEntry (TIntArray new_keys) inline private
Definition at line 157 of file KeybindingsMenu.c.
References ColorWhite().
Connect()
void Connect (ServerBrowserEntry server) inline private
Definition at line 568 of file ServerBrowserMenuNew.c.
References Play(), SaveFavoriteServersConsoles(), and SelectServer().
ConnectBestServer()
void ConnectBestServer () inline private
Definition at line 523 of file MainMenu.c.
References ConnectLastSession().
ConnectLastSession()
void ConnectLastSession () inline private
Definition at line 501 of file MainMenu.c.
References g_Game, DayZIntroScene::GetIntroCharacter(), string::Length(), name, and OpenMenuServerBrowser().
Referenced by ConnectBestServer().
CreateContent()
protected void CreateContent (int selected_item_id = -1) inline private
Definition at line 367 of file RadialQuickbarMenu.c.
References GetGame(), RadialMenu(), and RadialQuickbarItem().
CreateFakePlayerList()
SyncPlayerList CreateFakePlayerList (int player_count) inline private
Definition at line 380 of file InGameMenuXbox.c.
References SyncPlayerList::m_PlayerList, SyncPlayer::m_PlayerName, and SyncPlayer::m_UID.
CreateGestureContent()
protected void CreateGestureContent () inline private
Definition at line 388 of file GesturesMenu.c.
References GestureMenuItem(), GetGame(), and RadialMenu().
CreateGroupContainer()
void CreateGroupContainer () inline private
Definition at line 107 of file KeybindingsMenu.c.
References GetGame(), and GetInput().
Referenced by Init().
CreateTabs()
void CreateTabs () inline private
Definition at line 87 of file KeybindingsMenu.c.
References InputUtils::GetInputActionSortingMap(), GetUApi(), InputUtils::GetUnsortedInputActions(), and UAInputAPI::SortingLocalization().
Referenced by Init().
CustomizeCharacter()
void CustomizeCharacter () inline private
Definition at line 595 of file ServerBrowserMenuNew.c.
References MENU_CHARACTER.
Referenced by OnClick().
DeferredDefaultsInit()
void DeferredDefaultsInit () inline private
deprecated
Definition at line 538 of file KeybindingsMenu.c.
DeleteEvent()
void DeleteEvent () inline private
Definition at line 360 of file CameraToolsMenu.c.
DeleteGestureItems()
protected void DeleteGestureItems () inline private
Definition at line 452 of file GesturesMenu.c.
DeleteItems()
protected void DeleteItems () inline private
Definition at line 504 of file RadialQuickbarMenu.c.
DeleteKeyframe()
void DeleteKeyframe () inline private
Definition at line 292 of file CameraToolsMenu.c.
References Math::Clamp().
DeletePreset() [1/2]
void DeletePreset () inline private
Definition at line 93 of file SceneEditorMenu.c.
References GetCurrentPresetIndex(), GetCurrentPresetName(), m_ConfigDebugProfile, and RefreshLists().
Referenced by OnClick().
DeletePreset() [2/2]
void DeletePreset () inline private
Definition at line 2262 of file ScriptConsole.c.
References m_ConfigDebugProfile.
DrawConnectingLines() [1/2]
protected void DrawConnectingLines (int index) inline private
Definition at line 109 of file ControlsXboxNew.c.
References FilterByVisible(), FindAllChildrenByID(), EnumTools::GetEnumSize(), and m_VariantWidget.
Referenced by Init(), Init(), and UpdateTabContent().
DrawConnectingLines() [2/2]
void DrawConnectingLines (int index) inline private
Definition at line 98 of file TutorialsMenu.c.
References ARGBF(), Widget::DrawLine(), GetControlMappingInfo(), JsonControlMappingInfo::m_ButtonName, JsonControlMappingInfo::m_TabID, m_TabScript, and JsonControlMappingInfo::m_TextWidgetID.
DrawItems()
static void DrawItems (string type, float distance = 0) inline static private
need better logic for cleaning
Definition at line 957 of file ScriptConsole.c.
References COLOR_RED, GetGame(), CGame::GetObjectsAtPosition(), GetPlayer(), GetPosition, Debug::Log(), and Shape.
DrawItemsClear()
static void DrawItemsClear () inline static private
Definition at line 990 of file ScriptConsole.c.
References Shape.
DumpParam()
void DumpParam (string param, string relativePath) inline private
Definition at line 1099 of file ScriptConsole.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), ConfigIsExisting(), string::Get(), GetGame(), path, and Print().
EarlyAccessMenu()
void EarlyAccessMenu () inline private
Definition at line 3 of file EarlyAccessMenu.c.
EnscriptHistoryBack()
void EnscriptHistoryBack () inline private
Definition at line 597 of file ScriptConsole.c.
EnscriptHistoryForward()
void EnscriptHistoryForward () inline private
Definition at line 642 of file ScriptConsole.c.
ExecuteSelectedCategory()
protected void ExecuteSelectedCategory (Widget w) inline private
Definition at line 597 of file GesturesMenu.c.
References GestureMenuItem().
ExecuteSelectedItem()
protected void ExecuteSelectedItem () inline private
Definition at line 626 of file GesturesMenu.c.
References GestureMenuItem(), GetGame(), and GetPlayer().
Exit() [1/3]
void Exit () inline private
Definition at line 159 of file LogoutMenu.c.
References Mission::AbortMission(), CALL_CATEGORY_SYSTEM, Mission::Continue(), CGame::GetCallQueue(), GetGame(), CGame::GetMission(), and ScriptCallQueue::Remove().
Referenced by OnClick(), Update(), and UpdateTime().
Exit() [2/3]
void Exit () inline private
Definition at line 482 of file MainMenu.c.
References GetGame(), CGame::GetUIManager(), IDC_MAIN_QUIT, and UIManager::ShowDialog().
Exit() [3/3]
void Exit () inline private
Definition at line 335 of file MainMenuConsoles.c.
References GetGame(), CGame::GetUIManager(), IDC_MAIN_QUIT, and UIManager::ShowDialog().
ExpandHierarchy()
void ExpandHierarchy (int row) inline private
Definition at line 2763 of file ScriptConsole.c.
FilterByVisible()
protected int FilterByVisible (array< Widget > input, array< Widget > filtered) inline private
returns count
Definition at line 650 of file ControlsXboxNew.c.
References IsVisible().
Referenced by DrawConnectingLines().
FilterFocus()
void FilterFocus (bool focus) inline private
Definition at line 302 of file ServerBrowserMenuNew.c.
FindAllChildrenByID()
protected bool FindAllChildrenByID (Widget wid, int user_id, out array< Widget > results) inline private
Finds all immediate children widgets with corresponding userIDs.
Definition at line 635 of file ControlsXboxNew.c.
Referenced by DrawConnectingLines().
FindChildByID()
protected Widget FindChildByID (Widget wid, int user_id) inline private
Finds immediate child widget with a corresponding userID.
Definition at line 620 of file ControlsXboxNew.c.
Referenced by ComposeData(), and UpdateTabContent().
FindInHierarchy()
void FindInHierarchy (string class_name) inline private
Definition at line 2724 of file ScriptConsole.c.
References class_name, string::Contains(), string::Split(), and string::ToLower().
GameRespawn()
protected void GameRespawn (bool random) inline private
Definition at line 334 of file InGameMenu.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, Close(), CGame::GetCallQueue(), GetGame(), CGame::GetMenuDefaultCharacterData(), GetPlayer(), CGame::RespawnPlayer(), and MenuDefaultCharacterData::SetRandomCharacterForced().
Referenced by MenuRequestRespawn(), OnClick_Respawn(), and OnModalResult().
GameRetry()
void GameRetry (bool random) inline private
Definition at line 339 of file InGameMenuXbox.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, Close(), UIManager::CloseAll(), CGame::GetCallQueue(), GetGame(), CGame::GetMenuDefaultCharacterData(), GetPlayer(), CGame::GetUIManager(), CGame::RespawnPlayer(), CGame::RestartMission(), and MenuDefaultCharacterData::SetRandomCharacterForced().
Referenced by MenuRequestRespawn(), OnClick(), and OnModalResult().
GenderChanged()
void GenderChanged () inline private
Definition at line 250 of file CharacterCreationMenu.c.
References DayZIntroSceneXbox::GetIntroCharacter(), and SetCharacterSaved().
GesturesMenu()
void GesturesMenu () inline private
Definition at line 131 of file GesturesMenu.c.
References GetGame(), CGame::GetMission(), Mission::GetOnInputPresetChanged(), ScriptInvoker::Insert(), and OnInputPresetChanged().
GetActor()
PlayerBase GetActor (int index) inline private
Definition at line 170 of file CameraToolsMenu.c.
GetBlurValue()
float GetBlurValue () inline private
Definition at line 717 of file CameraToolsMenu.c.
GetCameraLine()
Param6< vector, vector, float, float, float, int > GetCameraLine (int index) inline private
Definition at line 370 of file CameraToolsMenu.c.
GetCameraLookDir()
vector GetCameraLookDir () inline private
Definition at line 456 of file CameraToolsMenu.c.
References DayZPhysics::RaycastRV().
GetChannelName()
static string GetChannelName (ChatChannel channel) inline static private
Definition at line 87 of file ChatInputMenu.c.
Referenced by UpdateChannel().
GetControlMappingInfo()
protected array< ref JsonControlMappingInfo > GetControlMappingInfo () inline private
Definition at line 296 of file TutorialsMenu.c.
References CloseFile(), ErrorEx, FGets(), GetGame(), CGame::GetInput(), GetInput(), Input::GetProfileName(), OpenFile(), PATH_MOUSEKEY, PATH_PS_NEW, PATH_PS_OLD, PATH_X1_NEW, PATH_X1_OLD, and JsonSerializer::ReadFromString().
Referenced by DrawConnectingLines(), and DrawConnectingLines().
GetCurrentItemIndex() [1/2]
int GetCurrentItemIndex () inline private
Definition at line 229 of file SceneEditorMenu.c.
Referenced by GetCurrentItemName(), ItemMoveDown(), ItemMoveUp(), OnChange(), OnClick(), OnDoubleClick(), and RemoveItemFromPreset().
GetCurrentItemIndex() [2/2]
int GetCurrentItemIndex () inline private
Definition at line 2550 of file ScriptConsole.c.
GetCurrentItemName() [1/2]
string GetCurrentItemName () inline private
Definition at line 201 of file SceneEditorMenu.c.
References GetCurrentItemIndex().
Referenced by OnClick(), and Dispatcher::ScriptConsoleGetSelectedItem().
GetCurrentItemName() [2/2]
string GetCurrentItemName () inline private
Definition at line 2475 of file ScriptConsole.c.
GetCurrentLocationName()
string GetCurrentLocationName () inline private
Definition at line 2498 of file ScriptConsole.c.
References name.
GetCurrentLocationPos()
vector GetCurrentLocationPos () inline private
Definition at line 2507 of file ScriptConsole.c.
References vector::Zero.
GetCurrentObjectName() [1/2]
string GetCurrentObjectName () inline private
Definition at line 212 of file SceneEditorMenu.c.
Referenced by OnItemSelected().
GetCurrentObjectName() [2/2]
string GetCurrentObjectName () inline private
Definition at line 2486 of file ScriptConsole.c.
GetCurrentPositionData()
void GetCurrentPositionData (out LocationParams data) inline private
Definition at line 2517 of file ScriptConsole.c.
GetCurrentPositionIndex()
int GetCurrentPositionIndex () inline private
Definition at line 2535 of file ScriptConsole.c.
GetCurrentPresetIndex() [1/2]
int GetCurrentPresetIndex () inline private
Definition at line 224 of file SceneEditorMenu.c.
Referenced by AddItemToPreset(), DeletePreset(), GetCurrentPresetName(), IsCurrentPresetFixed(), ItemMoveDown(), ItemMoveUp(), OnClick(), RemoveItemFromPreset(), RenamePreset(), RenderPresetItems(), SetDefaultPreset(), and SetPreset().
GetCurrentPresetIndex() [2/2]
int GetCurrentPresetIndex () inline private
Definition at line 2545 of file ScriptConsole.c.
GetCurrentPresetName() [1/2]
string GetCurrentPresetName () inline private
Definition at line 188 of file SceneEditorMenu.c.
References GetCurrentPresetIndex().
Referenced by AddItemToPreset(), DeletePreset(), ItemMoveDown(), ItemMoveUp(), OnChange(), OnClick(), OnDoubleClick(), RemoveItemFromPreset(), RenamePreset(), RenderPresetItems(), and SetDefaultPreset().
GetCurrentPresetName() [2/2]
string GetCurrentPresetName () inline private
Definition at line 2462 of file ScriptConsole.c.
GetCurrentTab()
KeybindingsContainer GetCurrentTab () inline private
Definition at line 523 of file KeybindingsMenu.c.
References m_GroupsContainer.
GetFavoritedServerIds()
TStringArray GetFavoritedServerIds () inline private
Definition at line 111 of file ServerBrowserMenuNew.c.
References m_Favorites.
GetFilterColor()
int GetFilterColor (string color) inline private
Definition at line 764 of file ScriptConsole.c.
References ARGB().
GetFiltredConfigClasses()
TStringArray GetFiltredConfigClasses (string search_string, TStringArray array_ret) inline private
Definition at line 1210 of file SceneEditorMenu.c.
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, string::Contains(), g_Game, and string::ToLower().
Referenced by UpdateListClasses().
GetFiltredSceneObjects()
protected map< int, SceneObject > GetFiltredSceneObjects (string search_string, map< int, SceneObject > array_ret) inline private
Definition at line 1179 of file SceneEditorMenu.c.
References string::Contains(), SceneObject::GetTypeName(), and string::ToLower().
Referenced by UpdateListObjects().
GetFreeUIPropertyAttchament()
UIPropertyAttachment GetFreeUIPropertyAttchament () inline private
Definition at line 1314 of file SceneEditorMenu.c.
References UIPropertyAttachment::IsVisible().
Referenced by Refresh().
GetGestureItems()
protected void GetGestureItems (out ref array< ref GestureMenuItem > gesture_items, GestureCategories category) inline private
Definition at line 317 of file GesturesMenu.c.
References GestureMenuItem(), EmoteConstants::ID_EMOTE_CAMPFIRE, EmoteConstants::ID_EMOTE_CLAP, EmoteConstants::ID_EMOTE_COME, EmoteConstants::ID_EMOTE_DANCE, EmoteConstants::ID_EMOTE_DOWN, EmoteConstants::ID_EMOTE_FACEPALM, EmoteConstants::ID_EMOTE_GREETING, EmoteConstants::ID_EMOTE_HEART, EmoteConstants::ID_EMOTE_HOLD, EmoteConstants::ID_EMOTE_LISTENING, EmoteConstants::ID_EMOTE_LOOKATME, EmoteConstants::ID_EMOTE_LYINGDOWN, EmoteConstants::ID_EMOTE_MOVE, EmoteConstants::ID_EMOTE_NOD, EmoteConstants::ID_EMOTE_POINT, EmoteConstants::ID_EMOTE_POINTSELF, EmoteConstants::ID_EMOTE_RPS, EmoteConstants::ID_EMOTE_SALUTE, EmoteConstants::ID_EMOTE_SHAKE, EmoteConstants::ID_EMOTE_SHRUG, EmoteConstants::ID_EMOTE_SILENT, EmoteConstants::ID_EMOTE_SITA, EmoteConstants::ID_EMOTE_SITB, EmoteConstants::ID_EMOTE_SOS, EmoteConstants::ID_EMOTE_SUICIDE, EmoteConstants::ID_EMOTE_SURRENDER, EmoteConstants::ID_EMOTE_TAUNT, EmoteConstants::ID_EMOTE_TAUNTELBOW, EmoteConstants::ID_EMOTE_TAUNTKISS, EmoteConstants::ID_EMOTE_TAUNTTHINK, EmoteConstants::ID_EMOTE_THROAT, EmoteConstants::ID_EMOTE_THUMB, EmoteConstants::ID_EMOTE_THUMBDOWN, EmoteConstants::ID_EMOTE_TIMEOUT, EmoteConstants::ID_EMOTE_VOMIT, and EmoteConstants::ID_EMOTE_WATCHING.
GetItemNamesForSlots()
private map< string, ref TStringArray > GetItemNamesForSlots (TStringArray slots) inline private
Definition at line 1335 of file SceneEditorMenu.c.
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, and g_Game.
Referenced by Refresh().
GetItems()
protected void GetItems (out ref array< ref RadialQuickbarItem > items) inline private
Definition at line 285 of file RadialQuickbarMenu.c.
References GetGame(), GetPlayer(), and RadialQuickbarItem().
GetItemsClasses()
TStringArray GetItemsClasses () inline private
Definition at line 754 of file ScriptConsole.c.
References CFG_AMMO, CFG_MAGAZINESPATH, CFG_VEHICLESPATH, and CFG_WEAPONSPATH.
GetItemToAssign()
static EntityAI GetItemToAssign () inline static private
Definition at line 135 of file RadialQuickbarMenu.c.
GetLastSelectedObject()
static string GetLastSelectedObject () inline static private
Definition at line 2885 of file ScriptConsole.c.
GetMapPos()
vector GetMapPos () inline private
Definition at line 1094 of file ScriptConsole.c.
GetMenuInstance()
static RadialQuickbarMenu GetMenuInstance () inline static private
Definition at line 140 of file RadialQuickbarMenu.c.
GetMouseLookDir()
vector GetMouseLookDir () inline private
Definition at line 475 of file CameraToolsMenu.c.
References GetGame(), CGame::GetPointerDirection(), and DayZPhysics::RaycastRV().
GetPlayerObj()
PlayerBase GetPlayerObj () inline private
Definition at line 47 of file CharacterCreationMenu.c.
References DayZIntroSceneXbox::GetIntroCharacter().
Referenced by Init().
GetPresetIndexByName() [1/2]
int GetPresetIndexByName (string preset_name) inline private
Definition at line 71 of file SceneEditorMenu.c.
Referenced by IsPresetFixed(), RenderPresets(), and SetDefaultPreset().
GetPresetIndexByName() [2/2]
int GetPresetIndexByName (string preset_name) inline private
Definition at line 2579 of file ScriptConsole.c.
GetSelectedTab()
ServerBrowserTab GetSelectedTab () inline private
Definition at line 611 of file ServerBrowserMenuNew.c.
References m_CommunityTab, m_FavoritesTab, m_LANTab, and m_OfficialTab.
Referenced by OnLoadServerModsAsync(), OnLoadServersAsync(), OnTabSwitch(), and Update().
GetServersLoadingTab()
TabType GetServersLoadingTab () inline private
Definition at line 198 of file ServerBrowserMenuNew.c.
References m_IsRefreshing.
GetSoundClasses()
TStringArray GetSoundClasses () inline private
Definition at line 759 of file ScriptConsole.c.
References CFG_SOUND_SETS.
GetText()
string GetText () inline private
Definition at line 27 of file ItemDropWarningMenu.c.
Referenced by OnClick().
GetTotalTime()
float GetTotalTime (int index) inline private
Definition at line 260 of file CameraToolsMenu.c.
References Math::Clamp().
HandleLights()
void HandleLights (RadialQuickbarItem quickbar_item) inline private
Definition at line 749 of file RadialQuickbarMenu.c.
References ActionTarget, GetGame(), GetPlayer(), ActionManagerClient::PerformActionStart(), and vector::Zero.
HandleNVG()
void HandleNVG (RadialQuickbarItem quickbar_item) inline private
Definition at line 782 of file RadialQuickbarMenu.c.
References ActionTarget, GetGame(), GetPlayer(), ActionManagerClient::PerformActionStart(), and vector::Zero.
HardReset()
void HardReset () inline private
Definition at line 278 of file KeybindingsMenu.c.
References g_Game.
Referenced by OnClick().
HelpScreen()
void HelpScreen () inline private
Definition at line 8 of file HelpScreen.c.
Hide() [1/3]
void Hide () inline private
Definition at line 105 of file DayZGame.c.
Referenced by OnClick(), ScriptedWidgetEventHandler::ShowActionMenu(), and Update().
Hide() [2/3]
void Hide () inline private
Definition at line 221 of file DayZGame.c.
Hide() [3/3]
void Hide () inline private
Definition at line 63 of file LogoutMenu.c.
HideItemButtons()
void HideItemButtons () inline private
Definition at line 2633 of file ScriptConsole.c.
HistoryBack()
void HistoryBack () inline private
Definition at line 565 of file ScriptConsole.c.
References m_ConfigDebugProfile.
Referenced by Dispatcher::ScriptConsoleHistoryBack().
HistoryForward()
void HistoryForward () inline private
Definition at line 573 of file ScriptConsole.c.
References m_ConfigDebugProfile.
Referenced by Dispatcher::ScriptConsoleHistoryForward().
HudShow()
protected void HudShow (bool show) inline private
Definition at line 137 of file InGameMenu.c.
References g_Game, GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
Referenced by Init(), and ~InGameMenu().
ImagenSetColor() [1/2]
void ImagenSetColor (Widget w, int color) inline private
Definition at line 602 of file MainMenu.c.
Referenced by ColorHighlight(), and ColorNormal().
ImagenSetColor() [2/2]
void ImagenSetColor (Widget w, int color) inline private
Definition at line 518 of file TutorialsMenu.c.
InGameMenuXbox()
void InGameMenuXbox () inline private
Definition at line 37 of file InGameMenuXbox.c.
References GetGame(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), ScriptInvoker::Insert(), OnInputDeviceChanged(), and OnInputPresetChanged().
Init() [1/38]
override Widget Init () inline private
Definition at line 56 of file DayZGame.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), InputUtils::GetRichtextButtonIconFromInputAction(), CGame::GetWorkspace(), and InputUtils::ICON_SCALE_TOOLBAR.
Init() [2/38]
override Widget Init () inline private
Definition at line 172 of file DayZGame.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), InputUtils::GetRichtextButtonIconFromInputAction(), CGame::GetWorkspace(), and InputUtils::ICON_SCALE_TOOLBAR.
Init() [3/38]
override Widget Init () inline private
Definition at line 11 of file BookMenu.c.
References Class::CastTo(), WorkspaceWidget::CreateWidgets(), GetGame(), and CGame::GetWorkspace().
Init() [4/38]
override Widget Init () inline private
Definition at line 126 of file CameraToolsMenu.c.
References WorkspaceWidget::CreateWidgets(), DeveloperFreeCamera::EnableFreeCameraSceneEditor(), GetGame(), GetPlayer(), and CGame::GetWorkspace().
Init() [5/38]
override Widget Init () inline private
Definition at line 13 of file ChatInputMenu.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), UAInputAPI::GetInputByID(), UAInput::GetPersistentWrapper(), GetUApi(), CGame::GetWorkspace(), m_BackInputWrapper, and UpdateChannel().
Init() [6/38]
override Widget Init () inline private
Definition at line 393 of file ControlsXboxNew.c.
References Class::CastTo(), ComposeData(), WorkspaceWidget::CreateWidgets(), GetGame(), GetInput(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), CGame::GetWorkspace(), ScriptInvoker::Insert(), m_Back, m_TabScript, OnInputDeviceChanged(), OnInputDeviceChanged(), OnInputPresetChanged(), UpdateControlsElements(), UpdateControlsElementVisibility(), UpdateTabContent(), and UpdateToolbarText().
Init() [7/38]
override Widget Init () inline private
Definition at line 11 of file EarlyAccessMenu.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), and CGame::GetWorkspace().
Init() [8/38]
override Widget Init () inline private
Definition at line 179 of file GesturesMenu.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), and RadialMenu().
Init() [9/38]
override Widget Init () inline private
Definition at line 17 of file HelpScreen.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), GetPlugin(), and CGame::GetWorkspace().
Init() [10/38]
override Widget Init () inline private
Definition at line 37 of file InGameMenu.c.
References ButtonSetText(), WorkspaceWidget::CreateWidgets(), g_Game, GetGame(), CGame::GetWorkspace(), HudShow(), mission, Mission::Pause(), SetGameVersion(), SetServerInfo(), and SetServerInfoVisibility().
Init() [11/38]
override Widget Init () inline private
Definition at line 76 of file InGameMenuXbox.c.
References Class::CastTo(), WorkspaceWidget::CreateWidgets(), g_Game, GetFocus(), GetGame(), Mission::GetHud(), GetInput(), CGame::GetMission(), OnlineServices::GetMuteList(), CGame::GetPlayer(), CGame::GetVersion(), CGame::GetWorkspace(), CGame::GetWorld(), IDC_INT_RETRY, ScriptInvoker::Insert(), World::IsDisabledReceivingVoN(), IsLocalPlayer(), OnlineServices::IsPlayerMuted(), LoadFooterButtonTexts(), LoadTextStrings(), OnlineServices::m_PermissionsAsyncInvoker, ClientData::m_PlayerList, mission, OnInputDeviceChanged(), Mission::Pause(), SetMuteButtonText(), ClientData::SyncEvent_OnPlayerListUpdate, UpdateControlsElements(), and UpdateMenuFocus().
Init() [12/38]
override Widget Init () inline private
Definition at line 38 of file InputDeviceDisconnectWarningMenu.c.
References g_Game, and UpdateDisconnectedDevices().
Init() [13/38]
override Widget Init () inline private
Definition at line 29 of file InspectMenuNew.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), and CGame::GetWorkspace().
Init() [14/38]
override Widget Init () inline private
Definition at line 12 of file InviteMenu.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), WorkspaceWidget::CreateWidgets(), EmoteLauncher::FORCE_DIFFERENT, CGame::GetCallQueue(), GetGame(), GetPlayer(), InputUtils::GetRichtextButtonIconFromInputAction(), CGame::GetWorkspace(), InputUtils::ICON_SCALE_TOOLBAR, and EmoteConstants::ID_EMOTE_SITA.
Init() [15/38]
override Widget Init () inline private
Definition at line 14 of file ItemDropWarningMenu.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), WarningMenuBase::GetText(), and CGame::GetWorkspace().
Init() [16/38]
override Widget Init () inline private
Definition at line 11 of file LoadingMenu.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), GetRandomLoadingBackground(), and CGame::GetWorkspace().
Init() [17/38]
override Widget Init () inline private
Definition at line 22 of file LogoutMenu.c.
References WorkspaceWidget::CreateWidgets(), EmoteLauncher::FORCE_DIFFERENT, GetGame(), GetPlayer(), InputUtils::GetRichtextButtonIconFromInputAction(), CGame::GetWorkspace(), InputUtils::ICON_SCALE_TOOLBAR, EmoteConstants::ID_EMOTE_SITA, and UpdateInfo().
Init() [18/38]
override Widget Init () inline private
gameplay cfg json overrides handling
override the CfgGameplayHandler.GetMapIgnoreNavItemsOwnership()
Definition at line 37 of file MapMenu.c.
References CGame::ConfigGetVector(), WorkspaceWidget::CreateWidgets(), g_Game, GetGame(), CfgGameplayHandler::GetMapDisplayNavigationInfo(), CfgGameplayHandler::GetMapDisplayPlayerPosition(), CfgGameplayHandler::GetMapIgnoreNavItemsOwnership(), CGame::GetWorkspace(), m_Hud, SetCompassUIVisibility(), SetGPSDirectionVisibility(), SetGPSMarkerVisibility(), SetUpperLegendVisibility(), Hud::ShowHudUI(), Hud::ShowQuickbarUI(), and Vector().
Init() [19/38]
override Widget Init () inline private
Definition at line 63 of file CharacterCreationMenu.c.
References CheckNewOptions(), WorkspaceWidget::CreateWidgets(), g_Game, GetGame(), DayZIntroSceneXbox::GetIntroCharacter(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), GetPlayerObj(), CGame::GetVersion(), CGame::GetWorkspace(), ScriptInvoker::Insert(), OnInputDeviceChanged(), OptionSelectorMultistateCharacterMenu(), Refresh(), and SetCharacter().
Init() [20/38]
override Widget Init () inline private
Definition at line 28 of file CreditsMenu.c.
References ScriptModule::Call(), WorkspaceWidget::CreateWidgets(), CGame::GameScript, GetGame(), GetInput(), GetScreenSize(), CGame::GetWorkspace(), LOGO_FADEIN_TIME, MENU_FADEIN_TIME, UpdateInfoPanelText(), x, and y.
Init() [21/38]
override Widget Init () inline private
Definition at line 29 of file KeybindingsMenu.c.
References ColorDisabled(), ColorWhite(), CreateGroupContainer(), CreateTabs(), WorkspaceWidget::CreateWidgets(), g_Game, GetGame(), CGame::GetInput(), GetInput(), CGame::GetVersion(), CGame::GetWorkspace(), InitInputSortingMap(), InitPresets(), and m_Back.
Init() [22/38]
override Widget Init () inline private
Definition at line 43 of file MainMenu.c.
References WorkspaceWidget::CreateWidgets(), g_Game, GetDayZGame(), GetGame(), CGame::GetUIManager(), CGame::GetVersion(), CGame::GetWorkspace(), LoadMods(), m_Mission, m_Play, m_PlayerName, m_Stats, Refresh(), DayZIntroScene::ResetIntroCamera(), UIManager::ScreenFadeOut(), and SetFocus().
Init() [23/38]
override Widget Init () inline private
Definition at line 25 of file MainMenuConsoles.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), GetInput(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), CGame::GetUIManager(), CGame::GetWorkspace(), ScriptInvoker::Insert(), LoadMods(), m_Controls, m_Mission, m_Play, m_PlayerName, OnInputDeviceChanged(), OnInputDeviceChanged(), OnInputPresetChanged(), Refresh(), CGame::SaveProfile(), UIManager::ScreenFadeOut(), CGame::SetProfileString(), UIManager::ShowDialog(), UpdateControlsElements(), and UpdateControlsElementVisibility().
Init() [24/38]
override Widget Init () inline private
Definition at line 10 of file MainMenuVideo.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), CGame::GetWorkspace(), ScriptInvoker::Insert(), and OnInputDeviceChanged().
Init() [25/38]
override Widget Init () inline private
Definition at line 24 of file TutorialsMenu.c.
References WorkspaceWidget::CreateWidgets(), DrawConnectingLines(), DrawConnectingLines(), GetGame(), GetInput(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), CGame::GetWorkspace(), ScriptInvoker::Insert(), m_Back, m_tab_images, m_TabScript, OnInputDeviceChanged(), OnInputDeviceChanged(), OnInputPresetChanged(), UpdateControlsElements(), and UpdateControlsElementVisibility().
Init() [26/38]
override Widget Init () inline private
Definition at line 32 of file OptionsMenu.c.
References WorkspaceWidget::CreateWidgets(), g_Game, GetGame(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), CGame::GetVersion(), CGame::GetWorkspace(), ScriptInvoker::Insert(), m_Back, OnChanged(), OnInputDeviceChanged(), OnInputPresetChanged(), SetFocus(), and ToggleFocus().
Init() [27/38]
override Widget Init () inline private
Definition at line 27 of file ServerBrowserMenuNew.c.
References WorkspaceWidget::CreateWidgets(), g_Game, GetGame(), GetInput(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), CGame::GetVersion(), CGame::GetWorkspace(), OnlineServices::Init(), ScriptInvoker::Insert(), LoadFavoriteServers(), m_Back, m_PlayerName, OnlineServices::m_ServerModLoadAsyncInvoker, OnlineServices::m_ServersAsyncInvoker, OnInputDeviceChanged(), OnInputDeviceChanged(), OnInputPresetChanged(), OnLoadServerModsAsync(), Refresh(), and UpdateControlsElements().
Init() [28/38]
override Widget Init () inline private
Definition at line 88 of file NoteMenu.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), and IDC_OK.
Init() [29/38]
override Widget Init () inline private
Definition at line 11 of file PresetsMenu.c.
References WorkspaceWidget::CreateWidgets(), Input::GetCurrentProfile(), GetGame(), CGame::GetInput(), Input::GetProfileName(), Input::GetProfilesCount(), and CGame::GetWorkspace().
Init() [30/38]
override Widget Init () inline private
Definition at line 169 of file RadialQuickbarMenu.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), RadialMenu(), and RefreshQuickbar().
Init() [31/38]
override Widget Init () inline private
Definition at line 19 of file RespawnDialogue.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), and SetFocus().
Init() [32/38]
override Widget Init () inline private
Definition at line 392 of file SceneEditorMenu.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), GetPlugin(), CGame::GetWorkspace(), m_ConfigDebugProfile, PopupHideAll(), RenderPresets(), UpdateListClasses(), and UpdateListObjects().
Init() [33/38]
override Widget Init () inline private
Definition at line 109 of file ScriptConsole.c.
References WorkspaceWidget::CreateWidgets(), Debug::GetBaseConfigClasses(), World::GetDate(), CGame::GetDiagDrawModeNames(), CGame::GetDiagModeNames(), GetGame(), GetPlayer(), GetPlugin(), CGame::GetWorkspace(), CGame::GetWorld(), GetWorldPosition(), m_ConfigDebugProfile, m_ItemPreviewWidget, Math::Pow(), Widget::SetText(), and AutoHeightSpacer::Update().
Init() [34/38]
override Widget Init () inline private
Definition at line 17 of file ScriptConsoleAddPosition.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), GetPlugin(), CGame::GetWorkspace(), and m_ConfigDebugProfile.
Init() [35/38]
override Widget Init () inline private
Definition at line 12 of file ScriptConsoleNewPresetDialog.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), and CGame::GetWorkspace().
Init() [36/38]
override Widget Init () inline private
Definition at line 12 of file ScriptConsoleRenamePresetDialog.c.
References WorkspaceWidget::CreateWidgets(), UIManager::FindMenu(), GetGame(), CGame::GetUIManager(), CGame::GetWorkspace(), MENU_SCRIPTCONSOLE, and mission.
Init() [37/38]
override Widget Init () inline private
Definition at line 11 of file StartupMenu.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), and CGame::GetWorkspace().
Init() [38/38]
override Widget Init () inline private
Definition at line 16 of file TitleScreenMenu.c.
References WorkspaceWidget::CreateWidgets(), g_Game, GetGame(), GetInput(), CGame::GetPlayerName(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), CGame::GetWorkspace(), and mission.
InitInputSortingMap()
protected void InitInputSortingMap () inline private
Definition at line 468 of file KeybindingsMenu.c.
References InputUtils::InitInputMetadata().
Referenced by Init().
InitMapItem()
override void InitMapItem (EntityAI item) inline private
Definition at line 147 of file MapMenu.c.
Referenced by ActionUnfoldMapCB::PerformMapChange().
InitNoteRead()
override void InitNoteRead (string text = "") inline private
Definition at line 39 of file NoteMenu.c.
InitNoteWrite()
override void InitNoteWrite (EntityAI paper, EntityAI pen, string text = "") inline private
Definition at line 62 of file NoteMenu.c.
InitPresets()
void InitPresets (int index, Widget parent, Input input) inline private
Definition at line 473 of file KeybindingsMenu.c.
References Input::GetCurrentProfile(), Input::GetProfileName(), and Input::GetProfilesCount().
Referenced by Init().
InputDeviceDisconnectWarningMenu()
void InputDeviceDisconnectWarningMenu () inline private
Definition at line 17 of file InputDeviceDisconnectWarningMenu.c.
References BuildMessages(), and g_Game.
InspectMenuNew()
void InspectMenuNew () inline private
Definition at line 12 of file InspectMenuNew.c.
InviteMenu()
void InviteMenu () inline private
Definition at line 7 of file InviteMenu.c.
IsAnyTabChanged()
bool IsAnyTabChanged () inline private
Definition at line 254 of file OptionsMenu.c.
Referenced by Back(), OnAttemptTabSwitch(), and OnChanged().
IsCurrentPositionCustom()
bool IsCurrentPositionCustom () inline private
Definition at line 2525 of file ScriptConsole.c.
IsCurrentPositionValid()
bool IsCurrentPositionValid () inline private
Definition at line 2540 of file ScriptConsole.c.
IsCurrentPresetFixed() [1/2]
bool IsCurrentPresetFixed () inline private
Definition at line 234 of file SceneEditorMenu.c.
References GetCurrentPresetIndex().
Referenced by RenderPresetItems(), and SetPreset().
IsCurrentPresetFixed() [2/2]
bool IsCurrentPresetFixed () inline private
Definition at line 2555 of file ScriptConsole.c.
IsFavorited()
bool IsFavorited (string server_id) inline private
Definition at line 218 of file ServerBrowserMenuNew.c.
Referenced by AddFavorite().
IsFocusable() [1/10]
bool IsFocusable (Widget w) inline private
Definition at line 884 of file CameraToolsMenu.c.
Referenced by OnFocus(), OnFocusLost(), OnMouseEnter(), and OnMouseLeave().
IsFocusable() [2/10]
bool IsFocusable (Widget w) inline private
Definition at line 493 of file ControlsXboxNew.c.
References m_Back.
IsFocusable() [3/10]
bool IsFocusable (Widget w) inline private
Definition at line 575 of file InGameMenuXbox.c.
IsFocusable() [4/10]
bool IsFocusable (Widget w) inline private
Definition at line 412 of file CharacterCreationMenu.c.
IsFocusable() [5/10]
bool IsFocusable (Widget w) inline private
Definition at line 414 of file KeybindingsMenu.c.
References m_Back.
IsFocusable() [6/10]
bool IsFocusable (Widget w) inline private
Definition at line 293 of file MainMenu.c.
IsFocusable() [7/10]
bool IsFocusable (Widget w) inline private
Definition at line 452 of file TutorialsMenu.c.
References m_Back.
IsFocusable() [8/10]
bool IsFocusable (Widget w) inline private
Definition at line 580 of file OptionsMenu.c.
References m_Back.
IsFocusable() [9/10]
bool IsFocusable (Widget w) inline private
Definition at line 497 of file ServerBrowserMenuNew.c.
References m_Back.
IsFocusable() [10/10]
bool IsFocusable (Widget w) inline private
Definition at line 134 of file RespawnDialogue.c.
References IDC_CANCEL.
IsLocalPlayer()
bool IsLocalPlayer (string uid) inline private
Definition at line 371 of file InGameMenuXbox.c.
References GetGame(), GetPlayer(), BiosUserManager::GetSelectedUser(), BiosUser::GetUid(), and CGame::GetUserManager().
Referenced by Init().
IsLocationNameAvailable()
bool IsLocationNameAvailable (string name) inline private
Definition at line 383 of file ScriptConsole.c.
References name.
IsMenuClosing() [1/2]
bool IsMenuClosing () inline private
Definition at line 655 of file GesturesMenu.c.
Referenced by MissionBase::OnUpdate().
IsMenuClosing() [2/2]
bool IsMenuClosing () inline private
Definition at line 795 of file RadialQuickbarMenu.c.
IsOnlineOpen()
bool IsOnlineOpen () inline private
Definition at line 442 of file InGameMenuXbox.c.
Referenced by UpdateControlsElements().
IsPresetFixed() [1/2]
bool IsPresetFixed (string preset_name) inline private
Definition at line 59 of file SceneEditorMenu.c.
References GetPresetIndexByName().
Referenced by RenderPresets(), and SetDefaultPreset().
IsPresetFixed() [2/2]
bool IsPresetFixed (string preset_name) inline private
Definition at line 2567 of file ScriptConsole.c.
IsRespawn()
bool IsRespawn () inline private
Definition at line 250 of file DayZGame.c.
IsStatic() [1/2]
bool IsStatic () inline private
Definition at line 120 of file DayZGame.c.
IsStatic() [2/2]
bool IsStatic () inline private
Definition at line 245 of file DayZGame.c.
ItemMoveDown() [1/2]
void ItemMoveDown () inline private
Definition at line 322 of file SceneEditorMenu.c.
References GetCurrentItemIndex(), GetCurrentPresetIndex(), GetCurrentPresetName(), m_ConfigDebugProfile, and RenderPresetItems().
Referenced by OnClick().
ItemMoveDown() [2/2]
void ItemMoveDown () inline private
Definition at line 2687 of file ScriptConsole.c.
References m_ConfigDebugProfile.
ItemMoveUp() [1/2]
void ItemMoveUp () inline private
Definition at line 311 of file SceneEditorMenu.c.
References GetCurrentItemIndex(), GetCurrentPresetIndex(), GetCurrentPresetName(), m_ConfigDebugProfile, and RenderPresetItems().
Referenced by OnClick().
ItemMoveUp() [2/2]
void ItemMoveUp () inline private
Definition at line 2676 of file ScriptConsole.c.
References m_ConfigDebugProfile.
LateInit()
void LateInit () inline private
Definition at line 428 of file ScriptConsole.c.
References GetPlugin(), m_ConfigDebugProfile, m_SelectedObject, name, PluginItemDiagnostic(), Widget::SetText(), and float::ToString().
Leave() [1/2]
void Leave () inline private
Definition at line 125 of file DayZGame.c.
References CALL_CATEGORY_SYSTEM, Close(), g_Game, and GetGame().
Leave() [2/2]
void Leave () inline private
Definition at line 255 of file DayZGame.c.
References CALL_CATEGORY_SYSTEM, Close(), g_Game, and GetGame().
LoadData()
void LoadData () inline private
Definition at line 191 of file CameraToolsMenu.c.
References FileExist(), g_Game, CTSaveStructure::m_Actors, CTSaveStructure::m_BlurValue, CTSaveStructure::m_Cameras, CTSaveStructure::m_Events, CTSaveStructure::m_InterpSpeed, CTSaveStructure::m_InterpType, and MakeDirectory().
LoadDataAsync()
void LoadDataAsync () inline private
Definition at line 56 of file CreditsMenu.c.
References CreditsLoader::GetData().
LoadFavoriteServers()
void LoadFavoriteServers () inline private
Definition at line 506 of file ServerBrowserMenuNew.c.
References OnlineServices::GetFavoriteServers(), GetGame(), CGame::GetProfileStringList(), and MAX_FAVORITES.
Referenced by Init(), and OnTabSwitch().
LoadFooterButtonTexts() [1/3]
protected void LoadFooterButtonTexts () inline private
Initial texts load for the footer buttons.
Definition at line 743 of file InGameMenuXbox.c.
References m_BackButtonTextID.
Referenced by Init().
LoadFooterButtonTexts() [2/3]
protected void LoadFooterButtonTexts () inline private
Definition at line 112 of file MainMenuVideo.c.
LoadFooterButtonTexts() [3/3]
protected void LoadFooterButtonTexts () inline private
Initial texts load for the footer buttons.
Definition at line 380 of file TutorialsMenu.c.
References m_BackButtonTextID.
LoadingMenu()
void LoadingMenu () inline private
Definition at line 3 of file LoadingMenu.c.
LoadMapMarkers()
override void LoadMapMarkers () inline private
Definition at line 302 of file MapMenu.c.
References Count, MapMarker::GetMarkerColor(), MapMarker::GetMarkerIcon(), MapMarker::GetMarkerPos(), MapMarker::GetMarkerText(), and MapMarkerTypes::GetMarkerTypeFromID().
Referenced by ActionUnfoldMapCB::PerformMapChange().
LoadMods() [1/2]
void LoadMods () inline private
Definition at line 114 of file MainMenu.c.
References GetGame(), CGame::GetModInfos(), m_ModsDetailed, and m_ModsSimple.
Referenced by Init(), and OnShow().
LoadMods() [2/2]
void LoadMods () inline private
Definition at line 68 of file MainMenuConsoles.c.
References GetGame(), ModInfo::GetIsOwned(), ModInfo::GetLogoSmall(), CGame::GetModInfos(), and m_ModsDetailed.
LoadTextStrings() [1/3]
protected void LoadTextStrings () inline private
Set correct bottom button texts based on platform (ps4 vs xbox texts)
Definition at line 725 of file InGameMenuXbox.c.
References m_BackButtonTextID.
Referenced by Init().
LoadTextStrings() [2/3]
protected void LoadTextStrings () inline private
Definition at line 117 of file MainMenuVideo.c.
LoadTextStrings() [3/3]
protected void LoadTextStrings () inline private
Set correct bottom button texts based on platform (ps4 vs xbox texts)
Definition at line 390 of file TutorialsMenu.c.
References m_BackButtonTextID.
LoginQueueBase()
void LoginQueueBase () inline private
Definition at line 44 of file DayZGame.c.
References g_Game.
LoginTimeBase()
void LoginTimeBase () inline private
Definition at line 160 of file DayZGame.c.
References g_Game.
LogoutMenu()
void LogoutMenu () inline private
Definition at line 11 of file LogoutMenu.c.
References g_Game.
MarkSelected() [1/2]
protected void MarkSelected (Widget w) inline private
Definition at line 555 of file GesturesMenu.c.
References GestureMenuItem().
MarkSelected() [2/2]
protected void MarkSelected (Widget w) inline private
Definition at line 584 of file RadialQuickbarMenu.c.
References Class::CastTo(), and RadialQuickbarItem().
MenuRequestRespawn() [1/2]
void MenuRequestRespawn (UIScriptedMenu menu, bool random) inline private
Definition at line 328 of file InGameMenu.c.
References GameRespawn().
MenuRequestRespawn() [2/2]
void MenuRequestRespawn (UIScriptedMenu menu, bool random) inline private
Definition at line 365 of file InGameMenuXbox.c.
References GameRetry().
NewPreset() [1/2]
void NewPreset (string preset_name) inline private
Definition at line 87 of file SceneEditorMenu.c.
References m_ConfigDebugProfile, and RefreshLists().
Referenced by OnClick().
NewPreset() [2/2]
void NewPreset (string preset_name) inline private
Definition at line 2256 of file ScriptConsole.c.
References m_ConfigDebugProfile.
NextCharacter() [1/2]
void NextCharacter () inline private
Definition at line 386 of file MainMenu.c.
References DayZIntroScene::GetIntroCharacter(), and OnChangeCharacter().
Referenced by OnClick().
NextCharacter() [2/2]
void NextCharacter () inline private
Definition at line 601 of file ServerBrowserMenuNew.c.
NextPrevPage()
void NextPrevPage (bool next) inline private
Definition at line 54 of file BookMenu.c.
References Math::Ceil(), m_page_height, Math::Round(), and float::ToString().
Referenced by OnClick(), and ReadBook().
NoteMenu()
void NoteMenu () inline private
Definition at line 13 of file NoteMenu.c.
References GetGame(), Mission::GetHud(), and mission.
OnAttemptSelectPreset()
void OnAttemptSelectPreset (int index) inline private
Definition at line 497 of file KeybindingsMenu.c.
References g_Game.
OnAttemptTabSwitch()
void OnAttemptTabSwitch (int source, int target) inline private
Definition at line 235 of file OptionsMenu.c.
References DIALOG_TAB_OFFSET, g_Game, IsAnyTabChanged(), and ResetCurrentTab().
OnChange() [1/3]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 29 of file ChatInputMenu.c.
References CGame::ChatPlayer(), GetGame(), UAInputAPI::GetInputByID(), CGame::GetPlayerName(), GetUApi(), name, UAInput::Supress(), x, and y.
OnChange() [2/3]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 748 of file SceneEditorMenu.c.
References ComponentsOnChange(), GetCurrentItemIndex(), GetCurrentPresetName(), m_ConfigDebugProfile, UpdateListClasses(), UpdateListObjects(), x, and y.
OnChange() [3/3]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 1960 of file ScriptConsole.c.
References ARGB(), GetGame(), GetPlayer(), GetPlugin(), m_ConfigDebugProfile, Math::Pow(), x, and y.
OnChangeCharacter()
void OnChangeCharacter (bool create_character = true) inline private
Definition at line 412 of file MainMenu.c.
References DayZIntroScene::GetIntroCharacter(), m_PlayerName, and m_Stats.
Referenced by NextCharacter(), OnShow(), PreviousCharacter(), and Refresh().
OnChanged()
void OnChanged () inline private
Definition at line 264 of file OptionsMenu.c.
References ColorDisable(), ColorNormal(), GetGame(), GetInput(), IsAnyTabChanged(), UpdateControlsElements(), and UpdateControlsElementVisibility().
Referenced by Init().
OnClick() [1/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 88 of file DayZGame.c.
References x, and y.
OnClick() [2/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 204 of file DayZGame.c.
References x, and y.
OnClick() [3/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 34 of file BookMenu.c.
References Close(), IDC_BOOK_VIEWER_NEXT, IDC_BOOK_VIEWER_PREV, IDC_CANCEL, NextPrevPage(), x, and y.
OnClick() [4/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 750 of file CameraToolsMenu.c.
References CGame::CopyToClipboard(), GetGame(), string::IndexOf(), string::Length(), Play(), Stop(), string::Substring(), and string::ToVector().
OnClick() [5/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 440 of file ControlsXboxNew.c.
References Back(), and m_Back.
OnClick() [6/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 18 of file EarlyAccessMenu.c.
References Close(), IDC_OK, x, and y.
OnClick() [7/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 44 of file HelpScreen.c.
References Close(), x, and y.
OnClick() [8/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 163 of file InGameMenu.c.
References CGame::CopyToClipboard(), GetGame(), OnClick_Continue(), OnClick_Exit(), OnClick_Options(), OnClick_Respawn(), OnClick_Restart(), x, and y.
OnClick() [9/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 212 of file InGameMenuXbox.c.
References BUTTON_XBOX_CONTROLS, ScriptCallQueue::Call(), CALL_CATEGORY_GUI, CloseOnline(), Continue(), GameRetry(), CGame::GetCallQueue(), GetGame(), CGame::GetUIManager(), IDC_INT_EXIT, IDC_INT_RETRY, IDC_MAIN_CONTINUE, IDC_MAIN_ONLINE, IDC_MAIN_OPTIONS, IDC_MAIN_QUIT, IDC_MULTI_INVITE, MENU_OPTIONS, MENU_RESPAWN_DIALOGUE, MENU_TUTORIAL, MENU_XBOX_CONTROLS, GameConstants::RESPAWN_MODE_CUSTOM, UIManager::ShowDialog(), OnlineServices::ShowInviteScreen(), UpdateControlsElements(), x, and y.
OnClick() [10/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 38 of file InspectMenuNew.c.
References Close(), IDC_CANCEL, x, and y.
OnClick() [11/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 32 of file ItemDropWarningMenu.c.
References Close(), IDC_OK, x, and y.
OnClick() [12/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 69 of file LogoutMenu.c.
References Mission::AbortMission(), Cancel(), GetGame(), CGame::GetMission(), Hide(), x, and y.
OnClick() [13/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 156 of file MapMenu.c.
References CloseMapMenu(), IDC_CANCEL, x, and y.
OnClick() [14/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 299 of file CharacterCreationMenu.c.
References Apply(), UIManager::Back(), Back(), GetGame(), CGame::GetUIManager(), RandomizeCharacter(), and Save().
OnClick() [15/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 188 of file KeybindingsMenu.c.
References Apply(), Back(), HardReset(), m_Back, Reset(), and SetToDefaults().
OnClick() [16/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 162 of file MainMenu.c.
References Exit(), m_ChooseServer, m_Play, m_PlayVideo, m_Tutorials, NextCharacter(), OpenCredits(), OpenMenuCustomizeCharacter(), OpenMenuServerBrowser(), OpenSettings(), OpenTutorials(), Play(), PlayVideo(), and PreviousCharacter().
OnClick() [17/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 107 of file MainMenuConsoles.c.
References ChangeAccount(), m_ChangeAccount, m_Controls, m_Controls, m_CustomizeCharacter, m_Mission, m_OpenDLC, m_Options, m_Play, m_PlayVideo, m_Tutorials, OpenCredits(), OpenMenuControls(), OpenMenuCustomizeCharacter(), OpenMenuOptions(), OpenMenuPlayVideo(), OpenMenuServerBrowser(), OpenMenuTutorials(), and UpdateControlsElements().
OnClick() [18/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 399 of file TutorialsMenu.c.
References Back(), and m_Back.
OnClick() [19/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 115 of file OptionsMenu.c.
References Apply(), Back(), m_Apply, m_Back, m_Defaults, m_Reset, PerformSetToDefaults(), and ResetCurrentTab().
OnClick() [20/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 147 of file ServerBrowserMenuNew.c.
References Back(), CustomizeCharacter(), m_Back, and Play().
OnClick() [21/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 98 of file NoteMenu.c.
References Close(), IDC_CANCEL, IDC_OK, x, and y.
OnClick() [22/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 34 of file PresetsMenu.c.
References Close(), GetGame(), CGame::GetInput(), CGame::GetMission(), Mission::GetOnInputPresetChanged(), IDC_CANCEL, IDC_OK, ScriptInvoker::Invoke(), Input::SetProfile(), x, and y.
OnClick() [23/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 40 of file RespawnDialogue.c.
References Close(), ID_RESPAWN_CUSTOM, ID_RESPAWN_RANDOM, IDC_CANCEL, RequestRespawn(), x, and y.
OnClick() [24/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 517 of file SceneEditorMenu.c.
References AddItemToPreset(), ComponentsOnClick(), CGame::CopyToClipboard(), DeletePreset(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetCurrentItemIndex(), GetCurrentItemName(), GetCurrentPresetIndex(), GetCurrentPresetName(), GetGame(), CGame::GetPlayer(), GetPlayer(), ItemMoveDown(), ItemMoveUp(), m_ConfigDebugProfile, m_SelectedObject, m_SpawnAsAttachmentButton, m_SpawnInInventoryButton, m_SpawnOnGroundButton, PopupOpen(), DayZPhysics::RaycastRV(), RefreshLists(), RemoveItemFromPreset(), RenderPresetItems(), SaveProfileSpawnDistance(), SetDefaultPreset(), float::ToString(), x, and y.
OnClick() [25/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 1168 of file ScriptConsole.c.
References string::BeautifiedToVector(), ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, Close(), ConfigGetFloat(), CGame::ConfigGetInt(), CGame::CopyToClipboard(), Mission::EnableAllInputs(), g_Game, CGame::GetCallQueue(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), CGame::GetDiagModeEnable(), GetGame(), CGame::GetMission(), CGame::GetPlayer(), GetPlayer(), GetPlugin(), GetPosition, string::IndexOf(), int, m_ConfigDebugProfile, m_ItemPreviewWidget, m_SelectedObject, MENU_LOC_ADD, MENU_SCRIPTCONSOLE_DIALOG_PRESET_NAME, MENU_SCRIPTCONSOLE_DIALOG_PRESET_RENAME, path, SEffectManager::PlaySoundEnviroment(), Math::Pow(), Print(), DayZPhysics::RaycastRV(), RefreshCrosshairVisibility(), CGame::SetDiagDrawMode(), CGame::SetDiagModeEnable(), ItemPreviewWidget::SetItem(), LogManager::SetLogsEnabled(), string::Split(), EffectSound::Stop(), string::Substring(), CGame::SurfaceY(), TABS_COUNT, ToString(), string::Trim(), Vector(), x, and y.
OnClick() [26/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 30 of file ScriptConsoleAddPosition.c.
References string::BeautifiedToVector(), Close(), GetGame(), IDC_CANCEL, IDC_OK, m_ConfigDebugProfile, MENU_SCRIPTCONSOLE, name, x, and y.
OnClick() [27/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 22 of file ScriptConsoleNewPresetDialog.c.
References Close(), UIManager::FindMenu(), GetGame(), GetText(), CGame::GetUIManager(), IDC_CANCEL, IDC_OK, MENU_SCRIPTCONSOLE, NewPreset(), x, and y.
OnClick() [28/28]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 34 of file ScriptConsoleRenamePresetDialog.c.
References Close(), UIManager::FindMenu(), GetGame(), CGame::GetUIManager(), IDC_CANCEL, IDC_OK, MENU_SCRIPTCONSOLE, RenamePreset(), x, and y.
OnClick_Continue()
protected void OnClick_Continue () inline private
Definition at line 200 of file InGameMenu.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, Continue(), CGame::GetCallQueue(), and GetGame().
Referenced by OnClick().
OnClick_Exit()
protected void OnClick_Exit () inline private
Definition at line 243 of file InGameMenu.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, CGame::GetCallQueue(), GetGame(), and CGame::LogoutRequestTime().
Referenced by OnClick().
OnClick_Options()
protected void OnClick_Options () inline private
Definition at line 238 of file InGameMenu.c.
References MENU_OPTIONS.
Referenced by OnClick().
OnClick_Respawn()
protected void OnClick_Respawn () inline private
Definition at line 217 of file InGameMenu.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, GameRespawn(), CGame::GetCallQueue(), GetGame(), CGame::GetPlayer(), CGame::GetUIManager(), IDC_INT_RETRY, MENU_RESPAWN_DIALOGUE, GameConstants::RESPAWN_MODE_CUSTOM, and UIManager::ShowDialog().
Referenced by OnClick(), and OnClick_Restart().
OnClick_Restart()
protected void OnClick_Restart () inline private
Definition at line 205 of file InGameMenu.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, CGame::GetCallQueue(), GetGame(), and OnClick_Respawn().
Referenced by OnClick().
OnController() [1/2]
override bool OnController (Widget w, int control, int value) inline private
Definition at line 242 of file GesturesMenu.c.
References RadialMenu().
OnController() [2/2]
override bool OnController (Widget w, int control, int value) inline private
Definition at line 232 of file RadialQuickbarMenu.c.
References RadialMenu().
OnControllerDeselect() [1/2]
void OnControllerDeselect (Widget w) inline private
Definition at line 528 of file GesturesMenu.c.
OnControllerDeselect() [2/2]
void OnControllerDeselect (Widget w) inline private
Definition at line 567 of file RadialQuickbarMenu.c.
OnControllerExecute()
void OnControllerExecute (Widget w) inline private
Definition at line 533 of file GesturesMenu.c.
OnControllerPressBack() [1/2]
void OnControllerPressBack (Widget w) inline private
Definition at line 549 of file GesturesMenu.c.
OnControllerPressBack() [2/2]
void OnControllerPressBack (Widget w) inline private
Definition at line 577 of file RadialQuickbarMenu.c.
OnControllerPressSelect() [1/2]
void OnControllerPressSelect (Widget w) inline private
Definition at line 537 of file GesturesMenu.c.
OnControllerPressSelect() [2/2]
void OnControllerPressSelect (Widget w) inline private
Definition at line 572 of file RadialQuickbarMenu.c.
OnControllerSelect() [1/2]
void OnControllerSelect (Widget w) inline private
Definition at line 523 of file GesturesMenu.c.
OnControllerSelect() [2/2]
void OnControllerSelect (Widget w) inline private
Definition at line 562 of file RadialQuickbarMenu.c.
OnControlsChanged() [1/2]
void OnControlsChanged (RadialMenuControlType type) inline private
Definition at line 484 of file GesturesMenu.c.
OnControlsChanged() [2/2]
void OnControlsChanged (RadialMenuControlType type) inline private
Definition at line 530 of file RadialQuickbarMenu.c.
OnDoubleClick() [1/2]
override bool OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 487 of file SceneEditorMenu.c.
References GetCurrentItemIndex(), GetCurrentPresetName(), GetGame(), GetPlayer(), m_ConfigDebugProfile, m_SelectedObject, SaveProfileSpawnDistance(), and SetPreset().
OnDoubleClick() [2/2]
override bool OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 1843 of file ScriptConsole.c.
References CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), GetPlayer(), m_SelectedObject, Math::Max(), DayZPhysics::RaycastRV(), CGame::SurfaceRoadY(), CGame::SurfaceY(), Vector(), x, and y.
OnFocus() [1/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 864 of file CameraToolsMenu.c.
References IsFocusable().
Referenced by ScriptedWidgetEventHandler::OnMouseEnter(), OptionSelectorBase::OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), and OptionSelectorBase::OnMouseLeave().
OnFocus() [2/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 473 of file ControlsXboxNew.c.
References ColorHighlight(), and IsFocusable().
OnFocus() [3/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 555 of file InGameMenuXbox.c.
References ColorHighlight(), and IsFocusable().
OnFocus() [4/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 376 of file CharacterCreationMenu.c.
References ColorHighlight(), IsFocusable(), SetTooltipTexts(), TOOLTIP_ID_APPLY, and TOOLTIP_ID_SAVE.
OnFocus() [5/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 387 of file KeybindingsMenu.c.
References ColorRed(), and IsFocusable().
OnFocus() [6/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 273 of file MainMenu.c.
References ColorHighlight(), and IsFocusable().
OnFocus() [7/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 177 of file MainMenuConsoles.c.
References ColorHighlight().
OnFocus() [8/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 432 of file TutorialsMenu.c.
References ColorHighlight(), and IsFocusable().
OnFocus() [9/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 551 of file OptionsMenu.c.
References ColorHighlight(), IsFocusable(), SliderFocus(), ToggleFocus(), and y.
OnFocus() [10/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 354 of file ServerBrowserMenuNew.c.
References ColorHighlight(), and IsFocusable().
OnFocus() [11/11]
override bool OnFocus (Widget w, int x, int y) inline private
Definition at line 95 of file RespawnDialogue.c.
References ColorHighlight(), ID_RESPAWN_CUSTOM, ID_RESPAWN_RANDOM, IsFocusable(), and SetTooltipTexts().
OnFocusLost() [1/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 874 of file CameraToolsMenu.c.
References IsFocusable().
OnFocusLost() [2/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 483 of file ControlsXboxNew.c.
References ColorNormal(), and IsFocusable().
OnFocusLost() [3/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 565 of file InGameMenuXbox.c.
References ColorNormal(), and IsFocusable().
OnFocusLost() [4/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 402 of file CharacterCreationMenu.c.
References ColorNormal(), and IsFocusable().
OnFocusLost() [5/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 397 of file KeybindingsMenu.c.
References ColorDisabled(), ColorWhite(), and IsFocusable().
OnFocusLost() [6/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 283 of file MainMenu.c.
References ColorNormal(), and IsFocusable().
OnFocusLost() [7/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 183 of file MainMenuConsoles.c.
References ColorNormal().
OnFocusLost() [8/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 442 of file TutorialsMenu.c.
References ColorNormal(), and IsFocusable().
OnFocusLost() [9/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 570 of file OptionsMenu.c.
References ColorNormal(), and IsFocusable().
OnFocusLost() [10/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 364 of file ServerBrowserMenuNew.c.
References ColorNormal(), and IsFocusable().
OnFocusLost() [11/11]
override bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 123 of file RespawnDialogue.c.
References ColorNormal(), and IsFocusable().
OnHide() [1/10]
override void OnHide () inline private
Definition at line 97 of file CameraToolsMenu.c.
References GetGame(), CGame::GetMission(), CGame::GetUIManager(), m_IsPlaying, Mission::RemoveActiveInputExcludes(), and UIManager::ShowCursor().
Referenced by PluginBase::CursorHide(), and PluginBase::FreeCameraControlEnable().
OnHide() [2/10]
override void OnHide () inline private
Definition at line 61 of file ChatInputMenu.c.
References GetGame(), CGame::GetMission(), Mission::HideChat(), and Mission::HideVoiceLevelWidgets().
OnHide() [3/10]
override void OnHide () inline private
Definition at line 225 of file GesturesMenu.c.
References GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
OnHide() [4/10]
override void OnHide () inline private
Definition at line 551 of file CharacterCreationMenu.c.
OnHide() [5/10]
override void OnHide () inline private
Definition at line 340 of file MainMenu.c.
References GetDayZGame().
OnHide() [6/10]
override void OnHide () inline private
Definition at line 242 of file MainMenuConsoles.c.
References GetDayZGame().
OnHide() [7/10]
override void OnHide () inline private
Definition at line 48 of file MainMenuVideo.c.
References GetGame(), CGame::GetSoundScene(), CGame::GetUIManager(), and UIManager::ShowUICursor().
OnHide() [8/10]
override void OnHide () inline private
Definition at line 213 of file RadialQuickbarMenu.c.
References GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
OnHide() [9/10]
override void OnHide () inline private
Definition at line 805 of file SceneEditorMenu.c.
References GetGame(), CGame::GetMission(), and Mission::RemoveActiveInputExcludes().
OnHide() [10/10]
override void OnHide () inline private
Definition at line 72 of file TitleScreenMenu.c.
OnInputDeviceChanged() [1/8]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 71 of file ControlsXboxNew.c.
References UpdateControlsElementVisibility().
Referenced by Init().
OnInputDeviceChanged() [2/8]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 71 of file InGameMenuXbox.c.
References UpdateControlsElements().
OnInputDeviceChanged() [3/8]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 52 of file CharacterCreationMenu.c.
References CheckNewOptions(), and UpdateControlsElementVisibility().
OnInputDeviceChanged() [4/8]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 101 of file MainMenuConsoles.c.
References UpdateControlsElements(), and UpdateControlsElementVisibility().
OnInputDeviceChanged() [5/8]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 55 of file MainMenuVideo.c.
References UpdateControlsElements().
OnInputDeviceChanged() [6/8]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 81 of file TutorialsMenu.c.
References UpdateControlsElementVisibility().
OnInputDeviceChanged() [7/8]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 108 of file OptionsMenu.c.
References UpdateControlsElementVisibility().
OnInputDeviceChanged() [8/8]
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 123 of file ServerBrowserMenuNew.c.
References GetGame(), GetInput(), and UpdateControlsElements().
OnInputPresetChanged() [1/8]
protected void OnInputPresetChanged () inline private
Definition at line 63 of file ControlsXboxNew.c.
References UpdateControlsElements(), and UpdateControlsElementVisibility().
OnInputPresetChanged() [2/8]
protected void OnInputPresetChanged () inline private
Definition at line 169 of file GesturesMenu.c.
OnInputPresetChanged() [3/8]
protected void OnInputPresetChanged () inline private
Definition at line 64 of file InGameMenuXbox.c.
References UpdateControlsElements().
OnInputPresetChanged() [4/8]
protected void OnInputPresetChanged () inline private
Definition at line 94 of file MainMenuConsoles.c.
References UpdateControlsElements().
OnInputPresetChanged() [5/8]
protected void OnInputPresetChanged () inline private
Definition at line 73 of file TutorialsMenu.c.
References UpdateControlsElements(), and UpdateControlsElementVisibility().
OnInputPresetChanged() [6/8]
protected void OnInputPresetChanged () inline private
Definition at line 101 of file OptionsMenu.c.
References UpdateControlsElementVisibility().
OnInputPresetChanged() [7/8]
protected void OnInputPresetChanged () inline private
Definition at line 116 of file ServerBrowserMenuNew.c.
References UpdateControlsElements().
OnInputPresetChanged() [8/8]
protected void OnInputPresetChanged () inline private
Definition at line 145 of file RadialQuickbarMenu.c.
OnItemSelected() [1/3]
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
Definition at line 468 of file InGameMenuXbox.c.
OnItemSelected() [2/3]
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
Definition at line 824 of file SceneEditorMenu.c.
References GetCurrentObjectName(), m_SelectedObject, x, and y.
OnItemSelected() [3/3]
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
Definition at line 2082 of file ScriptConsole.c.
References CFG_SOUND_SETS, m_ConfigDebugProfile, ToString(), vector::ToString(), x, and y.
OnKeyDown() [1/2]
override bool OnKeyDown (Widget w, int x, int y, int key) inline private
Definition at line 89 of file LogoutMenu.c.
References Cancel(), x, and y.
Referenced by OnKeyPress().
OnKeyDown() [2/2]
override bool OnKeyDown (Widget w, int x, int y, int key) inline private
Definition at line 945 of file ScriptConsole.c.
References m_SelectedObject, x, and y.
OnKeyPress() [1/4]
override bool OnKeyPress (Widget w, int x, int y, int key) inline private
Definition at line 893 of file CameraToolsMenu.c.
References g_Game, m_IsPlaying, Play(), and Stop().
Referenced by PluginBase::AddKeyframe(), PluginBase::DeleteKeyframe(), PluginBase::PlayPause(), and PluginBase::Save().
OnKeyPress() [2/4]
override bool OnKeyPress (Widget w, int x, int y, int key) inline private
Definition at line 170 of file MapMenu.c.
References Print(), x, and y.
OnKeyPress() [3/4]
override bool OnKeyPress (Widget w, int x, int y, int key) inline private
Definition at line 293 of file CharacterCreationMenu.c.
References x, and y.
OnKeyPress() [4/4]
override bool OnKeyPress (Widget w, int x, int y, int key) inline private
Definition at line 940 of file ScriptConsole.c.
References x, and y.
OnKeyUp()
override bool OnKeyUp (Widget w, int x, int y, int key) inline private
Definition at line 151 of file InputDeviceDisconnectWarningMenu.c.
References Close(), m_CanClose, x, and y.
Referenced by OnKeyRelease().
OnLoadServerModsAsync()
void OnLoadServerModsAsync (GetServerModListResult result_list) inline private
Definition at line 648 of file ServerBrowserMenuNew.c.
References GetSelectedTab(), GetServerModListResult::m_Id, GetServerModListResult::m_Mods, and ServerBrowserTab::OnLoadServerModsAsync().
OnLoadServersAsync()
void OnLoadServersAsync (GetServersResult result_list, EBiosError error, string response) inline private
Definition at line 656 of file ServerBrowserMenuNew.c.
References GetSelectedTab(), ServerBrowserTab::OnLoadServersAsyncConsole(), and ServerBrowserTab::OnLoadServersAsyncPC().
OnMenuRelease()
protected void OnMenuRelease () inline private
DEPRECATED.
Definition at line 697 of file GesturesMenu.c.
OnModalResult() [1/6]
override bool OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 249 of file InGameMenu.c.
References Mission::AbortMission(), ScriptCallQueue::Call(), CALL_CATEGORY_GUI, g_Game, GameRespawn(), CGame::GetCallQueue(), GetGame(), CGame::GetMission(), IDC_INT_EXIT, IDC_INT_RETRY, CGame::LogoutRequestTime(), MENU_RESPAWN_DIALOGUE, GameConstants::RESPAWN_MODE_CUSTOM, x, and y.
OnModalResult() [2/6]
override bool OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 291 of file InGameMenuXbox.c.
References Mission::AbortMission(), ScriptCallQueue::Call(), CALL_CATEGORY_GUI, g_Game, GameRetry(), CGame::GetCallQueue(), GetGame(), CGame::GetMission(), IDC_INT_EXIT, IDC_INT_RETRY, CGame::LogoutRequestTime(), MENU_RESPAWN_DIALOGUE, GameConstants::RESPAWN_MODE_CUSTOM, UpdateMenuFocus(), x, and y.
OnModalResult() [3/6]
override bool OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 304 of file KeybindingsMenu.c.
References UIManager::Back(), GetGame(), CGame::GetUIManager(), PerformSetToDefaultsExt(), and Reset().
OnModalResult() [4/6]
override bool OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 528 of file MainMenu.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, ColorNormal(), g_Game, CGame::GetCallQueue(), GetFocus(), GetGame(), IDC_MAIN_QUIT, and OpenTutorials().
OnModalResult() [5/6]
override bool OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 367 of file MainMenuConsoles.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, g_Game, CGame::GetCallQueue(), GetGame(), IDC_MAIN_QUIT, and OpenMenuTutorials().
OnModalResult() [6/6]
override bool OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 490 of file OptionsMenu.c.
References UIManager::Back(), DIALOG_TAB_OFFSET, CGame::EndOptionsVideo(), g_Game, GetGame(), CGame::GetUIManager(), IDC_MAIN_QUIT, PerformSetToDefaults(), and ResetCurrentTab().
OnMouseButtonDown() [1/5]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 722 of file CameraToolsMenu.c.
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetMission(), CGame::GetUIManager(), IsFocusable(), m_IsPlaying, Mission::RemoveActiveInputExcludes(), Input::ResetGameFocus(), SetFocus(), and UIManager::ShowCursor().
OnMouseButtonDown() [2/5]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 76 of file InspectMenuNew.c.
References g_Game, CGame::GetDragQueue(), GetGame(), x, and y.
OnMouseButtonDown() [3/5]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 325 of file CharacterCreationMenu.c.
References DayZIntroScenePC::CharacterRotationStart().
OnMouseButtonDown() [4/5]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 143 of file MainMenu.c.
References DayZIntroScenePC::CharacterRotationStart().
OnMouseButtonDown() [5/5]
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 1140 of file ScriptConsole.c.
References GetGame(), GetMousePos(), GetPlayer(), GetWorldPosition(), CGame::SurfaceY(), x, and y.
OnMouseButtonUp() [1/4]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 740 of file CameraToolsMenu.c.
OnMouseButtonUp() [2/4]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 139 of file InputDeviceDisconnectWarningMenu.c.
References Close(), m_CanClose, x, and y.
OnMouseButtonUp() [3/4]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 338 of file CharacterCreationMenu.c.
References DayZIntroScenePC::CharacterRotationStop().
OnMouseButtonUp() [4/4]
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 155 of file MainMenu.c.
References DayZIntroScenePC::CharacterRotationStop().
OnMouseDeselect() [1/2]
void OnMouseDeselect (Widget w) inline private
Definition at line 494 of file GesturesMenu.c.
OnMouseDeselect() [2/2]
void OnMouseDeselect (Widget w) inline private
Definition at line 540 of file RadialQuickbarMenu.c.
OnMouseEnter() [1/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 852 of file CameraToolsMenu.c.
Referenced by ScriptedWidgetEventHandler::OnMouseEnter(), and OptionSelectorBase::OnMouseEnter().
OnMouseEnter() [2/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 453 of file ControlsXboxNew.c.
References ColorHighlight(), and IsFocusable().
OnMouseEnter() [3/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 251 of file GesturesMenu.c.
References RadialMenu(), x, and y.
OnMouseEnter() [4/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 151 of file InGameMenu.c.
References ColorHighlight().
OnMouseEnter() [5/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 535 of file InGameMenuXbox.c.
References ColorHighlight(), and IsFocusable().
OnMouseEnter() [6/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 347 of file CharacterCreationMenu.c.
References ColorHighlight(), SetTooltipTexts(), TOOLTIP_ID_APPLY, and TOOLTIP_ID_SAVE.
OnMouseEnter() [7/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 355 of file KeybindingsMenu.c.
References ColorRed(), and IsFocusable().
OnMouseEnter() [8/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 229 of file MainMenu.c.
References ColorHighlight(), DayZIntroScene::GetIntroCharacter(), IsFocusable(), and name.
OnMouseEnter() [9/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 412 of file TutorialsMenu.c.
References ColorHighlight(), and IsFocusable().
OnMouseEnter() [10/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 531 of file OptionsMenu.c.
References ColorHighlight(), and IsFocusable().
OnMouseEnter() [11/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 170 of file ServerBrowserMenuNew.c.
References ColorHighlight(), and IsFocusable().
OnMouseEnter() [12/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 241 of file RadialQuickbarMenu.c.
References RadialMenu(), x, and y.
OnMouseEnter() [13/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 60 of file RespawnDialogue.c.
References ColorHighlight(), ID_RESPAWN_CUSTOM, ID_RESPAWN_RANDOM, and SetTooltipTexts().
OnMouseEnter() [14/14]
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 1950 of file ScriptConsole.c.
References x, and y.
OnMouseExecute() [1/2]
void OnMouseExecute (Widget w) inline private
Definition at line 499 of file GesturesMenu.c.
OnMouseExecute() [2/2]
void OnMouseExecute (Widget w) inline private
Definition at line 545 of file RadialQuickbarMenu.c.
OnMouseLeave() [1/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 859 of file CameraToolsMenu.c.
Referenced by ScriptedWidgetEventHandler::OnMouseLeave(), and OptionSelectorBase::OnMouseLeave().
OnMouseLeave() [2/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 463 of file ControlsXboxNew.c.
References ColorNormal(), and IsFocusable().
OnMouseLeave() [3/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 157 of file InGameMenu.c.
References ColorNormal().
OnMouseLeave() [4/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 545 of file InGameMenuXbox.c.
References ColorNormal(), and IsFocusable().
OnMouseLeave() [5/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 368 of file CharacterCreationMenu.c.
References ColorNormal(), and SetFocus().
OnMouseLeave() [6/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 365 of file KeybindingsMenu.c.
References ColorDisabled(), ColorWhite(), and IsFocusable().
OnMouseLeave() [7/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 258 of file MainMenu.c.
References ColorNormal(), and IsFocusable().
OnMouseLeave() [8/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 422 of file TutorialsMenu.c.
References ColorNormal(), and IsFocusable().
OnMouseLeave() [9/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 541 of file OptionsMenu.c.
References ColorNormal(), and IsFocusable().
OnMouseLeave() [10/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 180 of file ServerBrowserMenuNew.c.
References ColorNormal(), and IsFocusable().
OnMouseLeave() [11/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 82 of file RespawnDialogue.c.
References ColorNormal().
OnMouseLeave() [12/12]
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 1937 of file ScriptConsole.c.
References x, and y.
OnMousePressLeft() [1/2]
void OnMousePressLeft (Widget w) inline private
LMB.
Definition at line 504 of file GesturesMenu.c.
OnMousePressLeft() [2/2]
void OnMousePressLeft (Widget w) inline private
LMB.
Definition at line 550 of file RadialQuickbarMenu.c.
OnMousePressRight() [1/2]
void OnMousePressRight (Widget w) inline private
RMB.
Definition at line 517 of file GesturesMenu.c.
OnMousePressRight() [2/2]
void OnMousePressRight (Widget w) inline private
RMB.
Definition at line 556 of file RadialQuickbarMenu.c.
OnMouseSelect() [1/2]
void OnMouseSelect (Widget w) inline private
Definition at line 489 of file GesturesMenu.c.
OnMouseSelect() [2/2]
void OnMouseSelect (Widget w) inline private
Definition at line 535 of file RadialQuickbarMenu.c.
OnMouseWheel() [1/3]
override bool OnMouseWheel (Widget w, int x, int y, int wheel) inline private
Definition at line 105 of file InspectMenuNew.c.
References UpdateScale(), x, and y.
OnMouseWheel() [2/3]
override bool OnMouseWheel (Widget w, int x, int y, int wheel) inline private
Definition at line 382 of file KeybindingsMenu.c.
References x, and y.
OnMouseWheel() [3/3]
override bool OnMouseWheel (Widget w, int x, int y, int wheel) inline private
Definition at line 813 of file SceneEditorMenu.c.
References x, and y.
OnPermissionsUpdate()
void OnPermissionsUpdate (BiosPrivacyUidResultArray result_list) inline private
Definition at line 480 of file InGameMenuXbox.c.
References Refresh().
OnRPCEx()
override void OnRPCEx (int rpc_type, ParamsReadContext ctx) inline private
Definition at line 3258 of file ScriptConsole.c.
References m_PlayerDebugStats, CachedObjectsParams::PARAM1_BOOL, and Serializer::Read().
OnSelectKBPreset()
void OnSelectKBPreset (int index) inline private
Definition at line 510 of file KeybindingsMenu.c.
References GetGame(), CGame::GetInput(), CGame::GetMission(), Mission::GetOnInputPresetChanged(), Input::GetProfileName(), and ScriptInvoker::Invoke().
OnShow() [1/16]
override void OnShow () inline private
Definition at line 88 of file CameraToolsMenu.c.
References Mission::AddActiveInputExcludes(), GetGame(), CGame::GetMission(), and m_IsPlaying.
Referenced by PluginBase::CursorShow(), and PluginBase::FreeCameraControlDisable().
OnShow() [2/16]
override void OnShow () inline private
Definition at line 56 of file ChatInputMenu.c.
References SetFocus().
OnShow() [3/16]
override void OnShow () inline private
Definition at line 433 of file ControlsXboxNew.c.
References SetFocus().
OnShow() [4/16]
override void OnShow () inline private
Definition at line 207 of file GesturesMenu.c.
References GetGame(), Mission::GetHud(), CGame::GetMission(), mission, and SetFocus().
OnShow() [5/16]
override void OnShow () inline private
Definition at line 487 of file InGameMenuXbox.c.
References GetGame(), CGame::GetInput(), CGame::GetPlayer(), Input::IsEnabledMouseAndKeyboard(), Input::IsEnabledMouseAndKeyboardEvenOnServer(), UpdateControlsElements(), and UpdateMenuFocus().
OnShow() [6/16]
override void OnShow () inline private
Definition at line 36 of file InviteMenu.c.
OnShow() [7/16]
override void OnShow () inline private
Definition at line 467 of file CharacterCreationMenu.c.
References CheckNewOptions(), and UpdateControlsElementVisibility().
OnShow() [8/16]
override void OnShow () inline private
Definition at line 329 of file MainMenu.c.
References g_Game, LoadMods(), OnChangeCharacter(), and SetFocus().
OnShow() [9/16]
override void OnShow () inline private
Definition at line 217 of file MainMenuConsoles.c.
References GetDayZGame(), GetGame(), GetInput(), DayZIntroScene::GetIntroCamera(), DayZIntroScene::GetIntroCharacter(), LoadMods(), Refresh(), SetFocus(), UpdateControlsElements(), UpdateControlsElementVisibility(), and Vector().
OnShow() [10/16]
override void OnShow () inline private
Definition at line 38 of file MainMenuVideo.c.
References GetGame(), CGame::GetSoundScene(), CGame::GetUIManager(), UIManager::ShowUICursor(), and UpdateControlsElements().
OnShow() [11/16]
override void OnShow () inline private
Definition at line 86 of file TutorialsMenu.c.
References SetFocus().
OnShow() [12/16]
override void OnShow () inline private
Definition at line 607 of file OptionsMenu.c.
References Refresh().
OnShow() [13/16]
override void OnShow () inline private
Definition at line 195 of file RadialQuickbarMenu.c.
References GetGame(), Mission::GetHud(), CGame::GetMission(), mission, and SetFocus().
OnShow() [14/16]
override void OnShow () inline private
Definition at line 88 of file RespawnDialogue.c.
References SetFocus().
OnShow() [15/16]
override void OnShow () inline private
Definition at line 800 of file SceneEditorMenu.c.
References Mission::AddActiveInputExcludes(), GetGame(), and CGame::GetMission().
OnShow() [16/16]
override void OnShow () inline private
Definition at line 52 of file TitleScreenMenu.c.
References g_Game.
OnTabSeleted()
void OnTabSeleted (int tabID) inline private
Definition at line 3180 of file ScriptConsole.c.
References string::Get(), GetGame(), CGame::GetObjectsAtPosition(), GetPlayer(), GetPosition, m_ConfigDebugProfile, and AutoHeightSpacer::Update().
OnTabSwitch() [1/2]
void OnTabSwitch () inline private
Definition at line 635 of file ServerBrowserMenuNew.c.
References ServerBrowserTab::Focus(), GetSelectedTab(), IsNotInitialized(), LoadFavoriteServers(), ServerBrowserTab::RefreshList(), and SetServersLoadingTab().
OnTabSwitch() [2/2]
void OnTabSwitch (int tab) inline private
Definition at line 147 of file OptionsMenu.c.
OnVisibilityChanged()
override void OnVisibilityChanged (bool isVisible) inline private
Definition at line 103 of file MainMenuVideo.c.
OpenCredits() [1/2]
void OpenCredits () inline private
Definition at line 476 of file MainMenu.c.
References m_Mission, and MENU_CREDITS.
Referenced by OnClick(), and Update().
OpenCredits() [2/2]
void OpenCredits () inline private
Definition at line 316 of file MainMenuConsoles.c.
References m_Mission, and MENU_CREDITS.
OpenMenu() [1/2]
static void OpenMenu () inline static private
Definition at line 154 of file GesturesMenu.c.
References UIManager::EnterScriptedMenu(), GetGame(), CGame::GetUIManager(), and MENU_GESTURES.
OpenMenu() [2/2]
static void OpenMenu (UIScriptedMenu parent = NULL) inline static private
Definition at line 155 of file RadialQuickbarMenu.c.
References UIManager::EnterScriptedMenu(), GetGame(), CGame::GetUIManager(), and MENU_RADIAL_QUICKBAR.
OpenMenuControls()
void OpenMenuControls () inline private
Definition at line 291 of file MainMenuConsoles.c.
References MENU_XBOX_CONTROLS.
Referenced by OnClick().
OpenMenuCustomizeCharacter() [1/2]
void OpenMenuCustomizeCharacter () inline private
Definition at line 381 of file MainMenu.c.
References MENU_CHARACTER.
Referenced by OnClick().
OpenMenuCustomizeCharacter() [2/2]
void OpenMenuCustomizeCharacter () inline private
Definition at line 311 of file MainMenuConsoles.c.
References MENU_CHARACTER.
OpenMenuOptions()
void OpenMenuOptions () inline private
Definition at line 296 of file MainMenuConsoles.c.
References MENU_OPTIONS.
Referenced by OnClick().
OpenMenuPlayVideo()
void OpenMenuPlayVideo () inline private
Definition at line 301 of file MainMenuConsoles.c.
References MENU_VIDEO.
Referenced by OnClick().
OpenMenuServerBrowser() [1/2]
void OpenMenuServerBrowser () inline private
Definition at line 376 of file MainMenu.c.
References MENU_SERVER_BROWSER.
Referenced by ConnectLastSession(), and OnClick().
OpenMenuServerBrowser() [2/2]
void OpenMenuServerBrowser () inline private
Definition at line 286 of file MainMenuConsoles.c.
References MENU_SERVER_BROWSER.
OpenMenuTutorials()
void OpenMenuTutorials () inline private
Definition at line 306 of file MainMenuConsoles.c.
References MENU_TUTORIAL.
Referenced by OnClick(), and OnModalResult().
OpenMessages()
void OpenMessages () inline private
Definition at line 456 of file MainMenu.c.
OpenSettings()
void OpenSettings () inline private
Definition at line 461 of file MainMenu.c.
References MENU_OPTIONS.
Referenced by OnClick().
OpenStats()
void OpenStats () inline private
Definition at line 451 of file MainMenu.c.
OpenTutorials()
void OpenTutorials () inline private
Definition at line 471 of file MainMenu.c.
References MENU_TUTORIAL.
Referenced by OnClick(), and OnModalResult().
OptionsMenu()
void OptionsMenu () inline private
Definition at line 27 of file OptionsMenu.c.
PerformSetToDefaults() [1/2]
void PerformSetToDefaults () inline private
deprecated, resets all (as before ~1.20)
Definition at line 533 of file KeybindingsMenu.c.
References PerformSetToDefaultsExt().
Referenced by OnClick(), OnModalResult(), and Update().
PerformSetToDefaults() [2/2]
void PerformSetToDefaults () inline private
Definition at line 391 of file OptionsMenu.c.
References ColorNormal(), GetGame(), GetInput(), UpdateControlsElements(), and UpdateControlsElementVisibility().
PerformSetToDefaultsExt()
void PerformSetToDefaultsExt (int mode) inline private
Definition at line 283 of file KeybindingsMenu.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, ColorDisabled(), CGame::GetCallQueue(), GetGame(), GetUApi(), MODAL_RESULT_DEFAULT_ALL, MODAL_RESULT_DEFAULT_CURRENT, UAInputAPI::PresetReset(), and UAInputAPI::Revert().
Referenced by OnModalResult(), and PerformSetToDefaults().
PerformSwitchPreset()
protected void PerformSwitchPreset () inline private
Definition at line 566 of file ControlsXboxNew.c.
References UAInputAPI::Export(), GetGame(), CGame::GetMission(), Mission::GetOnInputPresetChanged(), GetUApi(), ScriptInvoker::Invoke(), UAInputAPI::PresetCount(), UAInputAPI::PresetCurrent(), UAInputAPI::PresetSelect(), UAInputAPI::SaveInputPresetMiscData(), UAInputAPI::SupressNextFrame(), InputUtils::UpdateConsolePresetID(), UpdateControlsElements(), and UpdateToolbarText().
Referenced by Update().
Play() [1/3]
void Play () inline private
Definition at line 379 of file CameraToolsMenu.c.
References DeveloperFreeCamera::DisableFreeCamera(), GetGame(), GetPlayer(), CGame::GetUIManager(), m_IsPlaying, m_Time, and UIManager::ShowCursor().
Referenced by Connect(), and OnClick().
Play() [2/3]
void Play () inline private
Definition at line 355 of file MainMenu.c.
References CALL_CATEGORY_GUI, ScriptCallQueue::CallByName(), g_Game, CGame::GetCallQueue(), and GetGame().
Play() [3/3]
void Play () inline private
Definition at line 577 of file ServerBrowserMenuNew.c.
References g_Game, GetGame(), CGame::GetUIManager(), m_SelectedServer, and UIManager::ShowDialog().
PlayAnimOnActor()
static void PlayAnimOnActor (int actor, int anim) inline static private
Definition at line 178 of file CameraToolsMenu.c.
References m_Instance.
PlayPauseVideo()
void PlayPauseVideo () inline private
Definition at line 78 of file MainMenuVideo.c.
PlayVideo()
void PlayVideo () inline private
Definition at line 466 of file MainMenu.c.
References MENU_VIDEO.
Referenced by OnClick().
PlayVideoLoop()
void PlayVideoLoop () inline private
Definition at line 60 of file MainMenuVideo.c.
References StopVideo().
PopupBack()
UIPopupScript PopupBack () inline private
Definition at line 888 of file SceneEditorMenu.c.
References UIPopupScript::Show().
PopupClose()
private void PopupClose (int popup_id) inline private
Definition at line 1253 of file SceneEditorMenu.c.
PopupCloseAll()
void PopupCloseAll () inline private
Definition at line 918 of file SceneEditorMenu.c.
Referenced by ~SceneEditorMenu().
PopupHideAll()
private void PopupHideAll () inline private
Definition at line 1260 of file SceneEditorMenu.c.
Referenced by Init().
PopupOpen()
UIPopupScript PopupOpen (int popup_id, Param param) inline private
Definition at line 861 of file SceneEditorMenu.c.
References UIPopupScript::OnOpen(), and UIPopupScript::Show().
Referenced by OnClick().
PrepareFilters()
void PrepareFilters (string filter, out TStringArray filters, out TIntArray colors) inline private
Definition at line 782 of file ScriptConsole.c.
References ARGB(), string::Split(), string::ToLower(), and string::Trim().
PresetsMenu()
void PresetsMenu () inline private
Definition at line 3 of file PresetsMenu.c.
PreviousCharacter() [1/2]
void PreviousCharacter () inline private
Definition at line 399 of file MainMenu.c.
References DayZIntroScene::GetIntroCharacter(), and OnChangeCharacter().
Referenced by OnClick().
PreviousCharacter() [2/2]
void PreviousCharacter () inline private
Definition at line 606 of file ServerBrowserMenuNew.c.
PrimaryAction()
protected void PrimaryAction (Widget w) inline private
Definition at line 653 of file RadialQuickbarMenu.c.
References GetGame(), GetPlayer(), RadialQuickbarItem(), and RefreshQuickbar().
PrintS() [1/5]
static void PrintS (bool message) inline static private
Definition at line 687 of file ScriptConsole.c.
References bool::ToString().
PrintS() [2/5]
static void PrintS (float message) inline static private
Definition at line 697 of file ScriptConsole.c.
References float::ToString().
PrintS() [3/5]
static void PrintS (int message) inline static private
Definition at line 692 of file ScriptConsole.c.
PrintS() [4/5]
static void PrintS (string message) inline static private
Definition at line 680 of file ScriptConsole.c.
References Print().
PrintS() [5/5]
static void PrintS (vector message) inline static private
Definition at line 702 of file ScriptConsole.c.
References vector::ToString().
ProcessDistanceAndUnits()
protected void ProcessDistanceAndUnits (float num, out float dist, out string units) inline private
Definition at line 420 of file MapMenu.c.
References Math::Ceil(), Math::Floor(), and Math::Round().
Referenced by Update().
ProcessEmoteConditionRequest()
void ProcessEmoteConditionRequest (GestureMenuItem gesture_item) inline private
Definition at line 285 of file GesturesMenu.c.
References GetGame(), and GetPlayer().
RadialQuickbarMenu()
void RadialQuickbarMenu () inline private
Definition at line 109 of file RadialQuickbarMenu.c.
References GetGame(), CGame::GetMission(), Mission::GetOnInputPresetChanged(), ScriptInvoker::Insert(), and OnInputPresetChanged().
RandomizeCharacter()
void RandomizeCharacter () inline private
Definition at line 217 of file CharacterCreationMenu.c.
References CheckNewOptions(), MenuDefaultCharacterData::GenerateRandomEquip(), Get(), GetGame(), DayZIntroSceneXbox::GetIntroCharacter(), CGame::GetMenuDefaultCharacterData(), Math::RandomInt(), Refresh(), and SetCharacter().
Referenced by OnClick(), and Update().
ReadBook()
void ReadBook (InventoryItem book) inline private
Definition at line 24 of file BookMenu.c.
References NextPrevPage().
Refresh() [1/9]
override void Refresh () inline private
Definition at line 70 of file ChatInputMenu.c.
Referenced by Init(), BiosUserManager::OnGameNameChanged(), ScriptedWidgetEventHandler::OnMouseButtonDown(), OnPermissionsUpdate(), OnShow(), InventoryItem::OnVariablesSynchronized(), RandomizeCharacter(), SceneEditorCommand(), SelectGamepad(), ScriptedWidgetEventHandler::SelectPlayer(), SelectServer(), SetCharacterSaved(), SetDatabaseID(), SyncEvent_OnRecievedPlayerList(), and Update().
Refresh() [2/9]
override void Refresh () inline private
Definition at line 585 of file InGameMenuXbox.c.
References g_Game, GetGame(), CGame::GetVersion(), CGame::GetWorld(), World::IsDisabledReceivingVoN(), SetMuteButtonText(), and UpdateControlsElements().
Refresh() [3/9]
override void Refresh () inline private
Definition at line 476 of file CharacterCreationMenu.c.
References GameConstants::DEFAULT_CHARACTER_NAME, g_Game, GetGame(), DayZIntroSceneXbox::GetIntroCharacter(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), CGame::GetVersion(), string::LengthUtf8(), name, string::SubstringUtf8(), UpdateControlsElements(), and UpdateControlsElementVisibility().
Refresh() [4/9]
override void Refresh () inline private
Definition at line 343 of file KeybindingsMenu.c.
References g_Game, GetGame(), and CGame::GetVersion().
Refresh() [5/9]
override void Refresh () inline private
Definition at line 315 of file MainMenu.c.
References GetGame(), CGame::GetVersion(), name, and OnChangeCharacter().
Refresh() [6/9]
override void Refresh () inline private
Definition at line 189 of file MainMenuConsoles.c.
References g_Game, GetGame(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), CGame::GetVersion(), string::LengthUtf8(), m_Mission, m_PlayerName, name, and string::SubstringUtf8().
Refresh() [7/9]
override void Refresh () inline private
Definition at line 589 of file OptionsMenu.c.
References g_Game, GetGame(), CGame::GetVersion(), UpdateControlsElements(), and UpdateControlsElementVisibility().
Refresh() [8/9]
override void Refresh () inline private
Definition at line 374 of file ServerBrowserMenuNew.c.
References g_Game, GetGame(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), CGame::GetVersion(), string::LengthUtf8(), m_PlayerName, name, and string::SubstringUtf8().
Refresh() [9/9]
override void Refresh () inline private
Definition at line 944 of file SceneEditorMenu.c.
References class_name, SceneObject::GetConfigAttachments(), GetFreeUIPropertyAttchament(), SceneObject::GetHealth(), GetItemNamesForSlots(), SceneObject::GetPosition(), SceneObject::GetRotation(), SceneObject::GetTypeName(), UIPropertyAttachment::SetPos(), UIPropertyAttachment::SetSize(), UIPropertyAttachment::Show(), float::ToString(), vector::ToString(), and UpdateListObjects().
RefreshByLocalProfile()
protected void RefreshByLocalProfile () private
RefreshDateWidgets()
void RefreshDateWidgets (int year, int month, int day, int hour, int minute) inline private
Definition at line 372 of file ScriptConsole.c.
References Math::InverseLerp().
RefreshGestures()
protected void RefreshGestures (GestureCategories category_id = -1) inline private
Definition at line 298 of file GesturesMenu.c.
RefreshLists() [1/2]
void RefreshLists () inline private
Definition at line 143 of file SceneEditorMenu.c.
References RenderPresetItems(), and RenderPresets().
Referenced by DeletePreset(), NewPreset(), OnClick(), and RenamePreset().
RefreshLists() [2/2]
void RefreshLists () inline private
Definition at line 2181 of file ScriptConsole.c.
RefreshLocations()
void RefreshLocations () inline private
Definition at line 410 of file ScriptConsole.c.
References m_ConfigDebugProfile, and name.
RefreshPlayerPosEditBoxes()
void RefreshPlayerPosEditBoxes () inline private
Definition at line 2874 of file ScriptConsole.c.
References GetGame(), and CGame::GetPlayer().
RefreshQuickbar()
protected void RefreshQuickbar (bool reset_selection = true) inline private
Definition at line 264 of file RadialQuickbarMenu.c.
References RadialQuickbarItem().
ReloadOptions()
void ReloadOptions () inline private
Definition at line 465 of file OptionsMenu.c.
ReloadOutput()
void ReloadOutput () inline private
Definition at line 3152 of file ScriptConsole.c.
References Add(), CloseFile(), FGets(), Debug::GetFileName(), and OpenFile().
ReloadScriptOutput()
void ReloadScriptOutput () inline private
Definition at line 3169 of file ScriptConsole.c.
References Add().
ReloadVideoOptions()
void ReloadVideoOptions () inline private
Definition at line 482 of file OptionsMenu.c.
RemoveItemFromPreset() [1/2]
void RemoveItemFromPreset () inline private
Definition at line 258 of file SceneEditorMenu.c.
References GetCurrentItemIndex(), GetCurrentPresetIndex(), GetCurrentPresetName(), m_ConfigDebugProfile, and RenderPresetItems().
Referenced by OnClick().
RemoveItemFromPreset() [2/2]
void RemoveItemFromPreset () inline private
Definition at line 2453 of file ScriptConsole.c.
References m_ConfigDebugProfile.
RemoveMarker()
void RemoveMarker () inline private
Definition at line 297 of file MapMenu.c.
RenamePreset() [1/2]
void RenamePreset (string new_preset_name) inline private
Definition at line 149 of file SceneEditorMenu.c.
References GetCurrentPresetIndex(), GetCurrentPresetName(), m_ConfigDebugProfile, and RefreshLists().
Referenced by OnClick().
RenamePreset() [2/2]
void RenamePreset (string new_preset_name) inline private
Definition at line 2279 of file ScriptConsole.c.
References m_ConfigDebugProfile.
RenderPresetItems() [1/2]
void RenderPresetItems () inline private
Definition at line 159 of file SceneEditorMenu.c.
References GetCurrentPresetIndex(), GetCurrentPresetName(), IsCurrentPresetFixed(), and m_ConfigDebugProfile.
Referenced by AddItemToPreset(), ItemMoveDown(), ItemMoveUp(), OnClick(), RefreshLists(), and RemoveItemFromPreset().
RenderPresetItems() [2/2]
void RenderPresetItems () inline private
Definition at line 2227 of file ScriptConsole.c.
References m_ConfigDebugProfile.
RenderPresets() [1/2]
void RenderPresets () inline private
Definition at line 20 of file SceneEditorMenu.c.
References GetPresetIndexByName(), IsPresetFixed(), and m_ConfigDebugProfile.
Referenced by Init(), and RefreshLists().
RenderPresets() [2/2]
void RenderPresets () inline private
Definition at line 2188 of file ScriptConsole.c.
References m_ConfigDebugProfile.
RenderScaleRuler()
protected void RenderScaleRuler () inline private
1st segment
last segment
Definition at line 391 of file MapMenu.c.
References SCALE_RULER_NUM_SEGMENTS.
Referenced by Update().
RenderVariables()
void RenderVariables (int row) inline private
Definition at line 2855 of file ScriptConsole.c.
References path.
RequestRespawn()
bool RequestRespawn (bool random) inline private
Definition at line 197 of file RespawnDialogue.c.
References GetGame(), CGame::GetPlayer(), and MENU_INGAME.
Referenced by OnClick().
Reset() [1/2]
void Reset () inline private
Undoes the unsaved changes and reverts to previous state. Does not reset to defaults!
Definition at line 263 of file KeybindingsMenu.c.
References ColorDisabled().
Referenced by OnClick(), and OnModalResult().
Reset() [2/2]
void Reset () inline private
Definition at line 296 of file OptionsMenu.c.
References ColorDisable(), GetGame(), GetInput(), UpdateControlsElements(), and UpdateControlsElementVisibility().
ResetCurrentTab()
void ResetCurrentTab () inline private
Definition at line 324 of file OptionsMenu.c.
References ColorDisable(), GetGame(), GetInput(), UpdateControlsElements(), and UpdateControlsElementVisibility().
Referenced by OnAttemptTabSwitch(), OnClick(), OnModalResult(), and Update().
ResetRunButtonColor()
void ResetRunButtonColor () inline private
Definition at line 739 of file ScriptConsole.c.
RespawnDialogue()
void RespawnDialogue () private
RunEnscript()
void RunEnscript () inline private
Definition at line 707 of file ScriptConsole.c.
References _player, CGame::ExecuteEnforceScript(), GetGame(), GetPlayer(), and string::Replace().
RunEnscriptServer()
void RunEnscriptServer () inline private
Definition at line 744 of file ScriptConsole.c.
References GetGame(), GetPlayer(), CachedObjectsParams::PARAM1_STRING, and CGame::RPCSingleParam().
Save()
void Save () inline private
saves default character
Definition at line 179 of file CharacterCreationMenu.c.
References GameConstants::DEFAULT_CHARACTER_NAME, DayZIntroSceneXbox::GetIntroCharacter(), name, and SetCharacterSaved().
Referenced by OnClick(), and Update().
SaveData()
void SaveData () inline private
Definition at line 229 of file CameraToolsMenu.c.
References FileExist(), g_Game, CTSaveStructure::m_Actors, CTSaveStructure::m_BlurValue, CTSaveStructure::m_Cameras, CTSaveStructure::m_Events, CTSaveStructure::m_InterpSpeed, CTSaveStructure::m_InterpType, and MakeDirectory().
SaveEvent()
void SaveEvent () inline private
Definition at line 355 of file CameraToolsMenu.c.
SaveFavoriteServersConsoles()
void SaveFavoriteServersConsoles () inline private
Definition at line 541 of file ServerBrowserMenuNew.c.
References GetGame(), CGame::SaveProfile(), and CGame::SetProfileStringList().
Referenced by Connect(), SetFavoriteConsoles(), and ~ServerBrowserMenuNew().
SaveKeyframe()
void SaveKeyframe () inline private
Definition at line 283 of file CameraToolsMenu.c.
SaveProfileSpawnDistance() [1/2]
void SaveProfileSpawnDistance () inline private
Definition at line 333 of file SceneEditorMenu.c.
References m_ConfigDebugProfile.
Referenced by OnClick(), and OnDoubleClick().
SaveProfileSpawnDistance() [2/2]
void SaveProfileSpawnDistance () inline private
Definition at line 2271 of file ScriptConsole.c.
References m_ConfigDebugProfile.
SceneEditorCommand()
void SceneEditorCommand (Param params) inline private
Definition at line 1028 of file SceneEditorMenu.c.
References Refresh().
Referenced by Dispatcher::SceneEditorCommand().
SceneEditorMenu()
void SceneEditorMenu () inline private
Definition at line 362 of file SceneEditorMenu.c.
References GetPlugin().
ScriptConsole()
void ScriptConsole () inline private
Definition at line 46 of file ScriptConsole.c.
References GetGame(), Mission::GetHud(), CGame::GetMission(), GetPlugin(), PluginLocalEnscriptHistory(), PluginLocalEnscriptHistoryServer(), Hud::ShowHudPlayer(), and Hud::ShowQuickbarPlayer().
ScriptConsoleAddLocation()
void ScriptConsoleAddLocation () inline private
Definition at line 3 of file ScriptConsoleAddPosition.c.
ScriptConsoleNewPresetDialog()
void ScriptConsoleNewPresetDialog () inline private
Definition at line 3 of file ScriptConsoleNewPresetDialog.c.
ScriptConsoleRenamePresetDialog()
void ScriptConsoleRenamePresetDialog () inline private
Definition at line 3 of file ScriptConsoleRenamePresetDialog.c.
SecondaryAction()
protected void SecondaryAction (Widget w) inline private
Definition at line 713 of file RadialQuickbarMenu.c.
References GetGame(), GetPlayer(), RadialQuickbarItem(), and RefreshQuickbar().
SelectActor()
void SelectActor (CTActor ac) inline private
Definition at line 121 of file CameraToolsMenu.c.
SelectEvent()
void SelectEvent (CTEvent ev) inline private
Definition at line 116 of file CameraToolsMenu.c.
SelectKeyframe()
void SelectKeyframe (CTKeyframe kf) inline private
Definition at line 107 of file CameraToolsMenu.c.
SelectNextTab()
void SelectNextTab () inline private
Definition at line 3100 of file ScriptConsole.c.
References TABS_COUNT.
SelectObject()
void SelectObject (bool hide_presets = true) inline private
Definition at line 1072 of file ScriptConsole.c.
References m_SelectedObject.
SelectPreset()
void SelectPreset () inline private
Definition at line 2153 of file ScriptConsole.c.
References m_SelectedObject, and string::ToLower().
SelectPreviousTab()
void SelectPreviousTab () inline private
Definition at line 3075 of file ScriptConsole.c.
References TABS_COUNT.
SelectServer() [1/2]
void SelectServer () inline private
Definition at line 458 of file InGameMenuXbox.c.
References Refresh().
Referenced by Connect().
SelectServer() [2/2]
void SelectServer (ServerBrowserEntry server) inline private
Definition at line 548 of file ServerBrowserMenuNew.c.
References m_SelectedServer.
SelectTab()
void SelectTab (int tab_id) inline private
Definition at line 3117 of file ScriptConsole.c.
References m_ConfigDebugProfile, and TABS_COUNT.
ServerListFocus()
void ServerListFocus (bool focus, bool favorite) inline private
Definition at line 327 of file ServerBrowserMenuNew.c.
References x, and y.
SetBlurValue()
void SetBlurValue (float blur) inline private
Definition at line 712 of file CameraToolsMenu.c.
References float::ToString().
SetCameraData()
float SetCameraData (Param6< vector, vector, float, float, float, int > transform1, Param6< vector, vector, float, float, float, int > transform2) inline private
Definition at line 648 of file CameraToolsMenu.c.
References Math::DEG2RAD, vector::Distance(), fixAngle_180_180(), Math3D::QuatToAngles(), DbgUI::Text(), and vector::ToString().
SetCharacter()
void SetCharacter () inline private
Definition at line 209 of file CharacterCreationMenu.c.
References MenuDefaultCharacterData::EquipDefaultCharacter(), GetGame(), DayZIntroSceneXbox::GetIntroCharacter(), and CGame::GetMenuDefaultCharacterData().
Referenced by Init(), and RandomizeCharacter().
SetCharacterSaved()
void SetCharacterSaved (bool state) inline private
Definition at line 712 of file CharacterCreationMenu.c.
References Refresh().
Referenced by BottomChanged(), GenderChanged(), Save(), ShoesChanged(), SkinChanged(), and TopChanged().
SetCompassUIVisibility()
protected void SetCompassUIVisibility (bool pState) inline private
Definition at line 349 of file MapMenu.c.
Referenced by Init().
SetDefaultPreset() [1/2]
void SetDefaultPreset (int preset_index) inline private
Definition at line 102 of file SceneEditorMenu.c.
References GetCurrentPresetIndex(), GetCurrentPresetName(), GetPresetIndexByName(), IsPresetFixed(), and m_ConfigDebugProfile.
Referenced by OnClick().
SetDefaultPreset() [2/2]
void SetDefaultPreset (int preset_index) inline private
Definition at line 2340 of file ScriptConsole.c.
References m_ConfigDebugProfile.
SetDisconnectTexts()
private void SetDisconnectTexts () inline private
Definition at line 108 of file InputDeviceDisconnectWarningMenu.c.
Referenced by UpdateWarningMenu().
SetFavoriteConsoles()
bool SetFavoriteConsoles (string ipAddress, int port, bool favorite) inline private
Definition at line 229 of file ServerBrowserMenuNew.c.
References AddFavorite(), g_Game, MAX_FAVORITES, and SaveFavoriteServersConsoles().
SetFilterOrder()
void SetFilterOrder (bool reversed) inline private
Definition at line 396 of file ScriptConsole.c.
References m_ConfigDebugProfile.
SetGameVersion()
protected void SetGameVersion () inline private
Definition at line 82 of file InGameMenu.c.
References GetGame(), and CGame::GetVersion().
Referenced by Init().
SetGPSDirectionVisibility()
protected void SetGPSDirectionVisibility (bool pState) inline private
Definition at line 370 of file MapMenu.c.
Referenced by Init().
SetGPSMarkerVisibility()
protected void SetGPSMarkerVisibility (bool pState) inline private
Definition at line 362 of file MapMenu.c.
Referenced by Init().
SetItem()
void SetItem (EntityAI item) inline private
Definition at line 53 of file InspectMenuNew.c.
References ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetModelPosition(), ItemPreviewWidget::SetView(), and Vector().
SetItemToAssign()
static void SetItemToAssign (EntityAI item) inline static private
Definition at line 130 of file RadialQuickbarMenu.c.
SetLogoutTime()
void SetLogoutTime () inline private
Definition at line 120 of file LogoutMenu.c.
SetMapPos()
void SetMapPos (vector pos) inline private
Definition at line 1088 of file ScriptConsole.c.
SetMenuClosing() [1/2]
void SetMenuClosing (bool state) inline private
Definition at line 660 of file GesturesMenu.c.
SetMenuClosing() [2/2]
void SetMenuClosing (bool state) inline private
Definition at line 800 of file RadialQuickbarMenu.c.
SetMuteButtonText()
protected void SetMuteButtonText (bool isMuted) inline private
Set mute text button text (mute / unmute)
Definition at line 712 of file InGameMenuXbox.c.
References m_MuteButtonTextID, and m_UnmuteButtonTextID.
Referenced by Init(), and Refresh().
SetObject()
void SetObject (string object) inline private
Definition at line 2381 of file ScriptConsole.c.
References m_ConfigDebugProfile, and m_SelectedObject.
SetPosition() [1/2]
void SetPosition (int position) inline private
Definition at line 111 of file DayZGame.c.
SetPosition() [2/2]
void SetPosition (vector pos) inline private
Definition at line 12 of file ScriptConsoleAddPosition.c.
References vector::ToString().
SetPreset()
void SetPreset (bool clear_inventory, string preset_name) inline private
spawn preset items into inventory
Definition at line 268 of file SceneEditorMenu.c.
References GetCurrentPresetIndex(), GetGame(), GetPlayer(), IsCurrentPresetFixed(), and m_ConfigDebugProfile.
Referenced by OnDoubleClick().
SetPreviewObject()
void SetPreviewObject (string object) inline private
Definition at line 2392 of file ScriptConsole.c.
References DayZGame(), dBodyDestroy(), ECE_LOCAL, ECE_PLACE_ON_SURFACE, GetGame(), IsKindOf(), m_ItemPreviewWidget, and ItemPreviewWidget::SetItem().
SetRespawn()
void SetRespawn (bool value) inline private
Definition at line 240 of file DayZGame.c.
SetServerInfo()
protected bool SetServerInfo () inline private
Definition at line 94 of file InGameMenu.c.
References GameConstants::DEFAULT_CHARACTER_MENU_ID, g_Game, OnlineServices::GetCurrentServerInfo(), GetGame(), MenuData::GetLastPlayedCharacter(), MenuData::GetLastServerAddress(), MenuData::GetLastServerName(), MenuData::GetLastServerPort(), and name.
Referenced by Init().
SetServerInfoVisibility()
void SetServerInfoVisibility (bool show) inline private
Definition at line 421 of file InGameMenu.c.
Referenced by Init().
SetServersLoadingTab()
void SetServersLoadingTab (TabType refreshing) inline private
Definition at line 190 of file ServerBrowserMenuNew.c.
References ScriptInvoker::Insert(), OnlineServices::m_ServersAsyncInvoker, and ScriptInvoker::Remove().
Referenced by OnTabSwitch().
SetStatus()
void SetStatus (string status) inline private
Definition at line 235 of file DayZGame.c.
SetTime() [1/2]
void SetTime (int time) inline private
Definition at line 227 of file DayZGame.c.
Referenced by UpdateTime().
SetTime() [2/2]
void SetTime (int time) inline private
Definition at line 125 of file LogoutMenu.c.
SetToDefaults() [1/2]
void SetToDefaults () inline private
Definition at line 273 of file KeybindingsMenu.c.
References g_Game.
Referenced by OnClick().
SetToDefaults() [2/2]
void SetToDefaults () inline private
Definition at line 383 of file OptionsMenu.c.
References g_Game.
SetTooltipTexts() [1/2]
void SetTooltipTexts (Widget w, string header = "", string desc = "") inline private
Definition at line 421 of file CharacterCreationMenu.c.
Referenced by OnFocus(), and OnMouseEnter().
SetTooltipTexts() [2/2]
void SetTooltipTexts (Widget w, string header = "", string desc = "") inline private
Definition at line 185 of file RespawnDialogue.c.
SetUpperLegendVisibility()
protected void SetUpperLegendVisibility (bool pState) inline private
Definition at line 378 of file MapMenu.c.
Referenced by Init().
ShoesChanged()
void ShoesChanged () inline private
Definition at line 286 of file CharacterCreationMenu.c.
References MenuDefaultCharacterData::EquipDefaultCharacter(), GetGame(), DayZIntroSceneXbox::GetIntroCharacter(), CGame::GetMenuDefaultCharacterData(), SetCharacterSaved(), and MenuDefaultCharacterData::SetDefaultAttachment().
Show() [1/3]
void Show () inline private
Definition at line 99 of file DayZGame.c.
Show() [2/3]
void Show () inline private
Definition at line 215 of file DayZGame.c.
Show() [3/3]
void Show () inline private
Definition at line 57 of file LogoutMenu.c.
ShowAButton()
void ShowAButton (bool show) inline private
Definition at line 285 of file ServerBrowserMenuNew.c.
ShowItemButtons()
void ShowItemButtons () inline private
Definition at line 2595 of file ScriptConsole.c.
References m_ConfigDebugProfile, and float::ToString().
ShowItemTransferButtons()
void ShowItemTransferButtons () inline private
Definition at line 2644 of file ScriptConsole.c.
ShowPresetButtons()
void ShowPresetButtons () inline private
Definition at line 2428 of file ScriptConsole.c.
ShowYButton()
void ShowYButton (bool show) inline private
Definition at line 269 of file ServerBrowserMenuNew.c.
SkinChanged()
void SkinChanged () inline private
Definition at line 266 of file CharacterCreationMenu.c.
References DayZIntroSceneXbox::GetIntroCharacter(), and SetCharacterSaved().
SliderFocus()
void SliderFocus () inline private
Definition at line 438 of file OptionsMenu.c.
References UpdateControlsElements().
Referenced by OnFocus().
SpawnPreset()
void SpawnPreset (EntityAI target, bool clear_inventory, string preset_name, InventoryLocationType location = InventoryLocationType.ATTACHMENT, float distance = 0) inline private
Definition at line 2289 of file ScriptConsole.c.
References m_ConfigDebugProfile.
StartEnteringAlternateKeybind()
void StartEnteringAlternateKeybind (int key_index) inline private
Definition at line 145 of file KeybindingsMenu.c.
StartEnteringKeybind()
void StartEnteringKeybind (int key_index) inline private
Definition at line 133 of file KeybindingsMenu.c.
StartupMenu()
void StartupMenu () inline private
Definition at line 3 of file StartupMenu.c.
Stop()
void Stop () inline private
Definition at line 430 of file CameraToolsMenu.c.
References GetGame(), Camera::GetInstance(), CGame::GetUIManager(), m_IsPlaying, and UIManager::ShowCursor().
StopVideo()
void StopVideo () inline private
Definition at line 68 of file MainMenuVideo.c.
References UIManager::Back(), GetGame(), and CGame::GetUIManager().
Referenced by PlayVideoLoop(), and Update().
SyncEvent_OnRecievedPlayerList()
void SyncEvent_OnRecievedPlayerList (SyncPlayerList player_list) inline private
Definition at line 473 of file InGameMenuXbox.c.
References Refresh().
Teleport()
void Teleport (PlayerBase player, vector position) inline private
Definition at line 1930 of file ScriptConsole.c.
References GetGame(), and CGame::SurfaceY().
TitleScreenMenu()
void TitleScreenMenu () inline private
Definition at line 6 of file TitleScreenMenu.c.
References g_Game.
ToggleDependentOptions()
void ToggleDependentOptions (int mode, bool state) inline private
Controls visibility and sometimes even state of specific, dependent options across sub-menus.
Definition at line 455 of file OptionsMenu.c.
ToggleFavoriteServer()
void ToggleFavoriteServer () inline private
Definition at line 426 of file InGameMenu.c.
References OnlineServices::GetCurrentServerInfo(), and OnlineServices::SetServerFavorited().
ToggleFocus()
void ToggleFocus () inline private
Definition at line 446 of file OptionsMenu.c.
References UpdateControlsElements().
Referenced by Init(), and OnFocus().
ToggleVisibility()
void ToggleVisibility () inline private
Definition at line 936 of file SceneEditorMenu.c.
References m_WgtRoot.
TopChanged()
void TopChanged () inline private
Definition at line 272 of file CharacterCreationMenu.c.
References MenuDefaultCharacterData::EquipDefaultCharacter(), GetGame(), DayZIntroSceneXbox::GetIntroCharacter(), CGame::GetMenuDefaultCharacterData(), SetCharacterSaved(), and MenuDefaultCharacterData::SetDefaultAttachment().
TryConnectLastSession()
bool TryConnectLastSession (out string ip, out int port) inline private
Definition at line 487 of file MainMenu.c.
References g_Game.
UnmarkSelected() [1/2]
protected void UnmarkSelected (Widget w) inline private
Definition at line 576 of file GesturesMenu.c.
References GestureMenuItem().
UnmarkSelected() [2/2]
protected void UnmarkSelected (Widget w) inline private
Definition at line 623 of file RadialQuickbarMenu.c.
Update() [1/24]
override void Update (float timeslice) inline private
Definition at line 80 of file DayZGame.c.
References GetUApi().
Update() [2/24]
override void Update (float timeslice) inline private
Definition at line 196 of file DayZGame.c.
References GetUApi().
Update() [3/24]
override void Update (float timeslice) inline private
Definition at line 494 of file CameraToolsMenu.c.
References COLOR_RED, vector::Direction(), Debug::DrawArrow(), DeveloperFreeCamera::EnableFreeCameraSceneEditor(), g_Game, DiagMenu::GetBool(), GetGame(), GetPlayer(), m_IsPlaying, m_Time, vector::Normalized(), Math3D::QuatToAngles(), CGame::RPCSingleParam(), Stop(), and vector::VectorToAngles().
Update() [4/24]
override void Update (float timeslice) inline private
Definition at line 74 of file ChatInputMenu.c.
References Close(), UAIDWrapper::InputP(), UAInput::LocalPress(), and m_BackInputWrapper.
Update() [5/24]
override void Update (float timeslice) inline private
Definition at line 498 of file ControlsXboxNew.c.
References Back(), GetUApi(), m_TabScript, PerformSwitchPreset(), and UpdateTabContent().
Update() [6/24]
override void Update (float timeslice) inline private
Definition at line 270 of file GesturesMenu.c.
References GetGame(), and GetPlayer().
Update() [7/24]
override void Update (float timeslice) inline private
Definition at line 287 of file InGameMenu.c.
References UpdateGUI().
Update() [8/24]
override void Update (float timeslice) inline private
Definition at line 394 of file InGameMenuXbox.c.
References GetGame(), GetUApi(), Refresh(), OnlineServices::ShowUserProfile(), and UpdateGUI().
Update() [9/24]
override void Update (float timeslice) inline private
Definition at line 41 of file InviteMenu.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, Cancel(), Close(), g_Game, CGame::GetCallQueue(), GetGame(), OnlineServices::GetInviteServerInfo(), GetUApi(), and ScriptCallQueue::Remove().
Update() [10/24]
override void Update (float timeslice) inline private
Definition at line 111 of file LogoutMenu.c.
References Cancel(), GetUApi(), and Hide().
Update() [11/24]
override void Update (float timeslice) inline private
Definition at line 199 of file MapMenu.c.
References CloseMapMenu(), g_Game, UAInputAPI::GetInputByID(), CfgGameplayHandler::GetMapIgnoreMapOwnership(), CfgGameplayHandler::GetMapIgnoreNavItemsOwnership(), GetUApi(), UAInput::LocalPress(), MapNavigationBehaviour(), ProcessDistanceAndUnits(), RenderScaleRuler(), and Math::Round().
Update() [12/24]
override void Update (float timeslice) inline private
Definition at line 528 of file CharacterCreationMenu.c.
References Back(), DayZIntroSceneXbox::GetIntroCharacter(), GetUApi(), RandomizeCharacter(), and Save().
Update() [13/24]
override void Update (float timeslice) inline private
Definition at line 67 of file CreditsMenu.c.
References Close(), GetGame(), and GetInput().
Update() [14/24]
override void Update (float timeslice) inline private
Definition at line 175 of file KeybindingsMenu.c.
References Back(), and GetUApi().
Update() [15/24]
override void Update (float timeslice) inline private
Definition at line 345 of file MainMenu.c.
References Exit(), GetGame(), and GetUApi().
Update() [16/24]
override void Update (float timeslice) inline private
Definition at line 247 of file MainMenuConsoles.c.
References CanStoreBeOpened(), ChangeAccount(), Exit(), g_Game, GetGame(), GetUApi(), and OpenCredits().
Update() [17/24]
override void Update (float timeslice) inline private
Definition at line 95 of file MainMenuVideo.c.
References GetUApi(), and StopVideo().
Update() [18/24]
override void Update (float timeslice) inline private
Definition at line 360 of file TutorialsMenu.c.
References Back(), GetUApi(), and m_TabScript.
Update() [19/24]
override void Update (float timeslice) inline private
Definition at line 614 of file OptionsMenu.c.
References Apply(), Back(), GetUApi(), PerformSetToDefaults(), and ResetCurrentTab().
Update() [20/24]
override void Update (float timeslice) inline private
Definition at line 405 of file ServerBrowserMenuNew.c.
References Back(), GetDayZGame(), GetGame(), GetSelectedTab(), GetUApi(), IsConnecting(), ServerBrowserTab::Left(), ServerBrowserTab::LeftHold(), ServerBrowserTab::LeftRelease(), ServerBrowserTab::PressA(), ServerBrowserTab::PressSholderLeft(), ServerBrowserTab::PressSholderRight(), ServerBrowserTab::PressX(), ServerBrowserTab::PressY(), ServerBrowserTab::Right(), ServerBrowserTab::RightHold(), and ServerBrowserTab::RightRelease().
Update() [21/24]
override void Update (float timeslice) inline private
Definition at line 130 of file NoteMenu.c.
References Close(), GetGame(), and GetUApi().
Update() [22/24]
override void Update (float timeslice) inline private
Definition at line 32 of file RespawnDialogue.c.
References Close(), and GetUApi().
Update() [23/24]
override void Update (float timeslice) inline private
Definition at line 999 of file ScriptConsole.c.
References UIManager::Back(), COLOR_BLUE, COLOR_RED, GetGame(), GetPlayer(), GetUApi(), CGame::GetUIManager(), int, vector::Length(), m_PlayerDebugStats, RemotePlayerStatDebug(), and ToString().
Update() [24/24]
override void Update (float timeslice) inline private
Definition at line 77 of file TitleScreenMenu.c.
References g_Game, GetUApi(), and MENU_MAIN.
UpdateCategoryName()
protected void UpdateCategoryName (string name) inline private
Definition at line 470 of file GesturesMenu.c.
References name.
UpdateChannel()
void UpdateChannel () inline private
Definition at line 82 of file ChatInputMenu.c.
References GetChannelName().
Referenced by Init().
UpdateControlsElements() [1/10]
protected void UpdateControlsElements () inline private
Definition at line 744 of file ControlsXboxNew.c.
References InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
Referenced by Apply(), CloseOnline(), Init(), OnChanged(), OnClick(), OnInputDeviceChanged(), OnInputPresetChanged(), OnShow(), PerformSetToDefaults(), PerformSwitchPreset(), Refresh(), Reset(), ResetCurrentTab(), SliderFocus(), and ToggleFocus().
UpdateControlsElements() [2/10]
protected void UpdateControlsElements () inline private
Definition at line 665 of file GesturesMenu.c.
References GetGame(), GetInput(), InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
UpdateControlsElements() [3/10]
protected void UpdateControlsElements () inline private
Definition at line 783 of file InGameMenuXbox.c.
References string::Format(), Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), InputUtils::GetRichtextButtonIconFromInputAction(), InputUtils::ICON_SCALE_TOOLBAR, Input::IsEnabledMouseAndKeyboardEvenOnServer(), IsOnlineOpen(), and m_BackButtonTextID.
UpdateControlsElements() [4/10]
protected void UpdateControlsElements () inline private
Definition at line 720 of file CharacterCreationMenu.c.
References string::Format(), DayZIntroSceneXbox::GetIntroCharacter(), InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
UpdateControlsElements() [5/10]
protected void UpdateControlsElements () inline private
Definition at line 453 of file MainMenuConsoles.c.
References CanStoreBeOpened(), string::Format(), InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
UpdateControlsElements() [6/10]
protected void UpdateControlsElements () inline private
Definition at line 121 of file MainMenuVideo.c.
References string::Format(), GetGame(), GetInput(), InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
UpdateControlsElements() [7/10]
protected void UpdateControlsElements () inline private
Definition at line 556 of file TutorialsMenu.c.
References InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
UpdateControlsElements() [8/10]
protected void UpdateControlsElements () inline private
Definition at line 775 of file OptionsMenu.c.
References string::Format(), InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
UpdateControlsElements() [9/10]
protected void UpdateControlsElements () inline private
Definition at line 751 of file ServerBrowserMenuNew.c.
References InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
UpdateControlsElements() [10/10]
protected void UpdateControlsElements () inline private
Definition at line 805 of file RadialQuickbarMenu.c.
References GetGame(), GetInput(), InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
UpdateControlsElementVisibility() [1/5]
protected void UpdateControlsElementVisibility () inline private
Definition at line 757 of file ControlsXboxNew.c.
References Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), and Input::IsEnabledMouseAndKeyboardEvenOnServer().
Referenced by Apply(), Init(), OnChanged(), OnInputDeviceChanged(), OnInputPresetChanged(), OnShow(), PerformSetToDefaults(), Refresh(), Reset(), and ResetCurrentTab().
UpdateControlsElementVisibility() [2/5]
protected void UpdateControlsElementVisibility () inline private
Definition at line 751 of file CharacterCreationMenu.c.
References Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), and Input::IsEnabledMouseAndKeyboard().
UpdateControlsElementVisibility() [3/5]
protected void UpdateControlsElementVisibility () inline private
Definition at line 469 of file MainMenuConsoles.c.
References Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), and Input::IsEnabledMouseAndKeyboard().
UpdateControlsElementVisibility() [4/5]
protected void UpdateControlsElementVisibility () inline private
Definition at line 571 of file TutorialsMenu.c.
References Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), and Input::IsEnabledMouseAndKeyboardEvenOnServer().
UpdateControlsElementVisibility() [5/5]
protected void UpdateControlsElementVisibility () inline private
Definition at line 805 of file OptionsMenu.c.
References Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), and Input::IsEnabledMouseAndKeyboardEvenOnServer().
UpdateDisconnectedDevices()
private void UpdateDisconnectedDevices (int device = -1) inline private
Definition at line 117 of file InputDeviceDisconnectWarningMenu.c.
References g_Game, m_Initialized, and UpdateWarningMenu().
Referenced by Init().
UpdateDisconnectTexts()
private void UpdateDisconnectTexts () inline private
Composes message depending on context.
Definition at line 69 of file InputDeviceDisconnectWarningMenu.c.
References string::Empty, and string::Get().
Referenced by UpdateWarningMenu().
UpdateGUI() [1/2]
protected void UpdateGUI () inline private
Definition at line 294 of file InGameMenu.c.
References GetGame(), and CGame::GetPlayer().
Referenced by Update().
UpdateGUI() [2/2]
void UpdateGUI () inline private
Definition at line 420 of file InGameMenuXbox.c.
References GetGame(), and CGame::GetPlayer().
UpdateHudDebugSetting()
void UpdateHudDebugSetting () private
UpdateInfo()
void UpdateInfo () inline private
Definition at line 144 of file LogoutMenu.c.
References GetGame(), and GetPlayer().
Referenced by Init().
UpdateInfoPanelText()
void UpdateInfoPanelText (int input_device_type) inline private
Definition at line 117 of file CreditsMenu.c.
References GetGame(), GetInput(), InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
Referenced by Init().
UpdateItemInfo()
static void UpdateItemInfo (Widget root_widget, EntityAI item) inline static private
Definition at line 138 of file InspectMenuNew.c.
References WidgetTrySetText().
UpdateItemInfoCleanness()
static void UpdateItemInfoCleanness (Widget root_widget, EntityAI item) inline static private
Definition at line 573 of file InspectMenuNew.c.
References Colors::WHITEGRAY, and WidgetTrySetText().
UpdateItemInfoDamage()
static void UpdateItemInfoDamage (Widget root_widget, EntityAI item) inline static private
Definition at line 183 of file InspectMenuNew.c.
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, Colors::COLOR_WORN, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, GameConstants::STATE_WORN, and WidgetTrySetText().
UpdateItemInfoFoodStage()
static void UpdateItemInfoFoodStage (Widget root_widget, EntityAI item) inline static private
Definition at line 523 of file InspectMenuNew.c.
References Colors::COLOR_BAKED, Colors::COLOR_BOILED, Colors::COLOR_BURNED, Colors::COLOR_DRIED, Colors::COLOR_RAW, Colors::COLOR_ROTTEN, and WidgetTrySetText().
UpdateItemInfoLiquidType()
static void UpdateItemInfoLiquidType (Widget root_widget, EntityAI item) inline static private
Definition at line 230 of file InspectMenuNew.c.
References Colors::COLOR_LIQUID, BloodTypes::GetBloodTypeName(), ItemBase::IsBloodContainer(), LIQUID_BEER, LIQUID_DIESEL, LIQUID_DISINFECTANT, LIQUID_GASOLINE, LIQUID_RIVERWATER, LIQUID_SALINE, LIQUID_VODKA, LIQUID_WATER, and WidgetTrySetText().
UpdateItemInfoQuantity()
static void UpdateItemInfoQuantity (Widget root_widget, EntityAI item) inline static private
Definition at line 383 of file InspectMenuNew.c.
References Class::CastTo(), Colors::COLOR_DEFAULT, GetTemperatureColor(), GameConstants::HEATISO_THRESHOLD_BAD, GameConstants::HEATISO_THRESHOLD_HIGH, GameConstants::HEATISO_THRESHOLD_LOW, GameConstants::HEATISO_THRESHOLD_MEDIUM, Math::Round(), float::ToString(), and WidgetTrySetText().
UpdateItemInfoTemperature()
static void UpdateItemInfoTemperature (Widget root_widget, EntityAI item) inline static private
Definition at line 320 of file InspectMenuNew.c.
References Math::Floor(), GetTemperatureColor(), float::ToString(), and WidgetTrySetText().
UpdateItemInfoWeight()
static void UpdateItemInfoWeight (Widget root_widget, EntityAI item) inline static private
Definition at line 484 of file InspectMenuNew.c.
References Colors::COLOR_DEFAULT, Math::Round(), and WidgetTrySetText().
UpdateItemInfoWetness()
static void UpdateItemInfoWetness (Widget root_widget, EntityAI item) inline static private
Definition at line 349 of file InspectMenuNew.c.
References Colors::COLOR_DAMP, Colors::COLOR_DRENCHED, Colors::COLOR_SOAKING_WET, Colors::COLOR_WET, GameConstants::STATE_DAMP, GameConstants::STATE_DRENCHED, GameConstants::STATE_SOAKING_WET, GameConstants::STATE_WET, and WidgetTrySetText().
UpdateListClasses()
protected void UpdateListClasses () inline private
Definition at line 1164 of file SceneEditorMenu.c.
References GetFiltredConfigClasses().
Referenced by Init(), and OnChange().
UpdateListObjects()
private void UpdateListObjects () inline private
Definition at line 1137 of file SceneEditorMenu.c.
References GetFiltredSceneObjects(), and SceneObject::GetTypeName().
Referenced by Init(), OnChange(), and Refresh().
UpdateMenuFocus()
void UpdateMenuFocus () inline private
Definition at line 763 of file InGameMenuXbox.c.
References GetGame(), CGame::GetPlayer(), and SetFocus().
Referenced by Init(), OnModalResult(), and OnShow().
UpdateMousePos()
void UpdateMousePos () inline private
Definition at line 1032 of file ScriptConsole.c.
References GetGame(), GetMousePos(), CGame::GetPlayer(), CGame::SurfaceY(), x, and y.
UpdateQuickbarItemCard() [1/2]
protected void UpdateQuickbarItemCard (GestureMenuItem gesture_item) inline private
Definition at line 423 of file GesturesMenu.c.
References ARGB().
UpdateQuickbarItemCard() [2/2]
protected void UpdateQuickbarItemCard (RadialQuickbarItem quickbar_item) inline private
Definition at line 414 of file RadialQuickbarMenu.c.
References QuantityConversions::GetItemQuantity(), QuantityConversions::GetItemQuantityText(), QuantityConversions::HasItemQuantity(), QUANTITY_COUNT, QUANTITY_HIDDEN, QUANTITY_PROGRESS, Math::Round(), ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetModelOrientation(), ItemPreviewWidget::SetView(), and Vector().
UpdateRotation()
void UpdateRotation (int mouse_x, int mouse_y, bool is_dragging) inline private
Definition at line 90 of file InspectMenuNew.c.
References m_characterOrientation, and ItemPreviewWidget::SetModelOrientation().
UpdateScale()
void UpdateScale () inline private
Definition at line 118 of file InspectMenuNew.c.
References GetScreenSize(), x, and y.
Referenced by OnMouseWheel().
UpdateSlotInfo()
static void UpdateSlotInfo (Widget root_widget, string name, string desc = "") inline static private
Definition at line 175 of file InspectMenuNew.c.
References name, and WidgetTrySetText().
UpdateTabContent() [1/2]
void UpdateTabContent (int tab_index) inline private
Definition at line 81 of file ControlsXboxNew.c.
References DrawConnectingLines(), FindChildByID(), and InputUtils::GetConsolePresetID().
Referenced by Init(), and Update().
UpdateTabContent() [2/2]
void UpdateTabContent (int tab_index) inline private
Definition at line 112 of file KeybindingsMenu.c.
UpdateTime() [1/3]
void UpdateTime () inline private
Definition at line 60 of file InviteMenu.c.
UpdateTime() [2/3]
void UpdateTime () inline private
Definition at line 131 of file LogoutMenu.c.
References Exit(), and SetTime().
UpdateTime() [3/3]
void UpdateTime (bool slider_used) inline private
Definition at line 2890 of file ScriptConsole.c.
References GetGame(), CGame::GetPlayer(), CGame::GetWorld(), Math::Lerp(), and World::SetDate().
UpdateToolbar()
protected void UpdateToolbar () inline private
DEPRECATED.
Definition at line 468 of file GesturesMenu.c.
UpdateToolbarText()
protected void UpdateToolbarText () inline private
Definition at line 594 of file ControlsXboxNew.c.
References GetUApi(), m_NextPresetText, InputUtils::PRESET_NEW, InputUtils::PRESET_OLD, UAInputAPI::PresetCount(), UAInputAPI::PresetCurrent(), and UAInputAPI::PresetName().
Referenced by Init(), and PerformSwitchPreset().
UpdateWarningMenu()
private void UpdateWarningMenu (int device) inline private
Definition at line 125 of file InputDeviceDisconnectWarningMenu.c.
References Close(), SetDisconnectTexts(), and UpdateDisconnectTexts().
Referenced by UpdateDisconnectedDevices().
UseGamepad() [1/2]
override bool UseGamepad () inline private
Definition at line 265 of file GesturesMenu.c.
Referenced by UIMenuPanel::LockControls(), and UIMenuPanel::UnlockControls().
UseGamepad() [2/2]
override bool UseGamepad () inline private
Definition at line 255 of file RadialQuickbarMenu.c.
UseKeyboard() [1/2]
override bool UseKeyboard () inline private
Definition at line 24 of file ChatInputMenu.c.
Referenced by UIMenuPanel::LockControls(), MissionBase::OnUpdate(), and UIMenuPanel::UnlockControls().
UseKeyboard() [2/2]
override bool UseKeyboard () inline private
Definition at line 353 of file SceneEditorMenu.c.
UseMouse() [1/3]
override bool UseMouse () inline private
Definition at line 260 of file GesturesMenu.c.
Referenced by UIMenuPanel::LockControls(), MissionBase::OnUpdate(), and UIMenuPanel::UnlockControls().
UseMouse() [2/3]
override bool UseMouse () inline private
Definition at line 250 of file RadialQuickbarMenu.c.
UseMouse() [3/3]
override bool UseMouse () inline private
Definition at line 345 of file SceneEditorMenu.c.
ViewEvent()
void ViewEvent () inline private
Definition at line 365 of file CameraToolsMenu.c.
ViewKeyframe()
void ViewKeyframe () inline private
Definition at line 306 of file CameraToolsMenu.c.
WarningMenuBase()
void WarningMenuBase () inline private
Definition at line 3 of file ItemDropWarningMenu.c.
References Mission::AddActiveInputExcludes(), GetGame(), and CGame::GetMission().
WidgetTrySetText()
static void WidgetTrySetText (Widget root_widget, string widget_name, string text, int color = 0) inline static private
Definition at line 589 of file InspectMenuNew.c.
Referenced by UpdateItemInfo(), UpdateItemInfoCleanness(), UpdateItemInfoDamage(), UpdateItemInfoFoodStage(), UpdateItemInfoLiquidType(), UpdateItemInfoQuantity(), UpdateItemInfoTemperature(), UpdateItemInfoWeight(), UpdateItemInfoWetness(), and UpdateSlotInfo().
Field Documentation
AREA_LEFT
protected const int AREA_LEFT = 1 private
Definition at line 50 of file ControlsXboxNew.c.
AREA_RIGHT
protected const int AREA_RIGHT = 2 private
Definition at line 51 of file ControlsXboxNew.c.
BUTTON_XBOX_CONTROLS
const int BUTTON_XBOX_CONTROLS = 201 private
Definition at line 35 of file InGameMenuXbox.c.
Referenced by OnClick().
CATEGORY_NAME
const string CATEGORY_NAME = "CategoryName" private
Definition at line 118 of file GesturesMenu.c.
CLEAR_IVN
bool CLEAR_IVN static private
Definition at line 21 of file ScriptConsole.c.
CONST_DEFAULT_PRESET_PREFIX
const string CONST_DEFAULT_PRESET_PREFIX = "[Default]" private
Definition at line 17 of file SceneEditorMenu.c.
COORD_FORMAT
protected const string COORD_FORMAT = "%1.%2%3" private
Definition at line 3 of file MapMenu.c.
CREDIT_SCROLL_SPEED
protected float CREDIT_SCROLL_SPEED = 200.0 static private
Definition at line 5 of file CreditsMenu.c.
DEBUG_MAP_ZOOM
float DEBUG_MAP_ZOOM = 1 static private
Definition at line 15 of file ScriptConsole.c.
DEFAULT_POS_XYZ
const string DEFAULT_POS_XYZ = "<1,2,3>" private
Definition at line 10 of file ScriptConsole.c.
DIALOG_TAB_OFFSET
const int DIALOG_TAB_OFFSET = 1400 private
Definition at line 4 of file OptionsMenu.c.
Referenced by OnAttemptTabSwitch(), and OnModalResult().
DRAW_DISTANCE
float DRAW_DISTANCE = 1000 static private
Definition at line 22 of file ScriptConsole.c.
GESTURE_TEXT
const string GESTURE_TEXT = "GestureNameText" private
Definition at line 116 of file GesturesMenu.c.
ID_RESPAWN_CUSTOM
const int ID_RESPAWN_CUSTOM = 101 private
Definition at line 3 of file RespawnDialogue.c.
Referenced by OnClick(), OnFocus(), and OnMouseEnter().
ID_RESPAWN_RANDOM
const int ID_RESPAWN_RANDOM = 102 private
Definition at line 4 of file RespawnDialogue.c.
Referenced by OnClick(), OnFocus(), and OnMouseEnter().
INPUT_TEXT
const string INPUT_TEXT = "InputActionText" private
Definition at line 117 of file GesturesMenu.c.
instance [1/2]
GesturesMenu instance static private
Definition at line 126 of file GesturesMenu.c.
instance [2/2]
RadialQuickbarMenu instance static private
Definition at line 104 of file RadialQuickbarMenu.c.
ITEMS_IN_PRESET_SELECTED_ROW
int ITEMS_IN_PRESET_SELECTED_ROW static private
Definition at line 18 of file ScriptConsole.c.
ITEMS_SELECTED_ROW
int ITEMS_SELECTED_ROW = -1 static private
Definition at line 16 of file ScriptConsole.c.
LOGO_FADEIN_TIME
protected float LOGO_FADEIN_TIME = 1.0 static private
Definition at line 4 of file CreditsMenu.c.
Referenced by Init().
m_ActionTextWidget
private RichTextWidget m_ActionTextWidget private
Definition at line 15 of file InputDeviceDisconnectWarningMenu.c.
m_ActiveTabIdx
protected int m_ActiveTabIdx = 0 private
Definition at line 22 of file OptionsMenu.c.
m_ActorIdWidget
protected EditBoxWidget m_ActorIdWidget private
Definition at line 35 of file CameraToolsMenu.c.
m_ActorItemTypeWidget
protected EditBoxWidget m_ActorItemTypeWidget private
Definition at line 36 of file CameraToolsMenu.c.
m_Actors
protected ref array<ref CTActor> m_Actors private
Definition at line 23 of file CameraToolsMenu.c.
m_ActorTypeWidget
protected EditBoxWidget m_ActorTypeWidget private
Definition at line 33 of file CameraToolsMenu.c.
m_AddActor
protected ButtonWidget m_AddActor private
Definition at line 40 of file CameraToolsMenu.c.
m_AddEvent
protected ButtonWidget m_AddEvent private
Definition at line 51 of file CameraToolsMenu.c.
m_AddHandsItem
protected ButtonWidget m_AddHandsItem private
Definition at line 39 of file CameraToolsMenu.c.
m_AddItem
protected ButtonWidget m_AddItem private
Definition at line 38 of file CameraToolsMenu.c.
m_AddKeyframe
protected ButtonWidget m_AddKeyframe private
Definition at line 46 of file CameraToolsMenu.c.
m_AllowScriptOutput
bool m_AllowScriptOutput private
Definition at line 40 of file ScriptConsole.c.
m_Apply [1/2]
protected ButtonWidget m_Apply private
Definition at line 14 of file CharacterCreationMenu.c.
Referenced by OnClick().
m_Apply [2/2]
protected ButtonWidget m_Apply private
Definition at line 10 of file KeybindingsMenu.c.
m_ApplyButton
protected ButtonWidget m_ApplyButton private
Definition at line 57 of file CameraToolsMenu.c.
m_AreasLR
protected ref map<int,ref TButtonPairingInfo> m_AreasLR private
Definition at line 48 of file ControlsXboxNew.c.
m_author
protected TextWidget m_author private
Definition at line 3 of file BookMenu.c.
m_Back [1/2]
protected ButtonWidget m_Back private
Definition at line 35 of file ControlsXboxNew.c.
Referenced by OnClick().
m_Back [2/2]
protected Widget m_Back private
Definition at line 12 of file ServerBrowserMenuNew.c.
m_BackAvailable
protected bool m_BackAvailable private
Definition at line 15 of file InGameMenuXbox.c.
m_BackButton
protected Widget m_BackButton private
Definition at line 17 of file CharacterCreationMenu.c.
m_BackButtonTextID
protected string m_BackButtonTextID private
Definition at line 30 of file ControlsXboxNew.c.
m_BackInputWrapper
private UAIDWrapper m_BackInputWrapper private
Definition at line 5 of file ChatInputMenu.c.
m_BaseConfigClasses
ref TStringArray m_BaseConfigClasses = new TStringArray private
Definition at line 29 of file ScriptConsole.c.
m_BaseConfigClassesToggled
ref TStringArray m_BaseConfigClassesToggled = new TStringArray private
Definition at line 30 of file ScriptConsole.c.
m_BatchSpawnQuantity
EditBoxWidget m_BatchSpawnQuantity private
Definition at line 3040 of file ScriptConsole.c.
m_bCancel
private ButtonWidget m_bCancel private
Definition at line 7 of file LogoutMenu.c.
m_bCancelConsole
private ButtonWidget m_bCancelConsole private
Definition at line 8 of file LogoutMenu.c.
m_bLogoutNow
private ButtonWidget m_bLogoutNow private
Definition at line 6 of file LogoutMenu.c.
m_BlurEditWidget
protected EditBoxWidget m_BlurEditWidget private
Definition at line 32 of file CameraToolsMenu.c.
m_BottomSelector
protected ref OptionSelectorMultistateCharacterMenu m_BottomSelector private
Definition at line 29 of file CharacterCreationMenu.c.
m_btnLeave
protected ButtonWidget m_btnLeave private
Definition at line 39 of file DayZGame.c.
m_ButtonCopyPos
ButtonWidget m_ButtonCopyPos private
Definition at line 2956 of file ScriptConsole.c.
m_ButtonsWindowWidget
Widget m_ButtonsWindowWidget private
Definition at line 2934 of file ScriptConsole.c.
m_Camera1
protected Camera m_Camera1 private
Definition at line 9 of file CameraToolsMenu.c.
m_Camera2
protected Camera m_Camera2 private
Definition at line 10 of file CameraToolsMenu.c.
m_CameraEditbox
protected EditBoxWidget m_CameraEditbox private
Definition at line 58 of file CameraToolsMenu.c.
m_CameraLines
protected ref array<ref Param6<vector, vector, float, float, float, int> > m_CameraLines private
Definition at line 12 of file CameraToolsMenu.c.
m_Cameras
protected ref array<ref CTKeyframe> m_Cameras private
Definition at line 24 of file CameraToolsMenu.c.
m_CameraValues
protected TextWidget m_CameraValues private
Definition at line 59 of file CameraToolsMenu.c.
m_CanApplyOrReset
protected bool m_CanApplyOrReset private
Definition at line 24 of file OptionsMenu.c.
m_CanClose
private bool m_CanClose private
Definition at line 6 of file InputDeviceDisconnectWarningMenu.c.
Referenced by OnKeyUp(), and OnMouseButtonUp().
m_CanToggle
protected bool m_CanToggle private
Definition at line 25 of file OptionsMenu.c.
m_CanvasWidget
protected CanvasWidget m_CanvasWidget private
Definition at line 39 of file ControlsXboxNew.c.
m_CaptionText
private string m_CaptionText private
Definition at line 9 of file InputDeviceDisconnectWarningMenu.c.
m_CaptionWidget
private TextWidget m_CaptionWidget private
Definition at line 13 of file InputDeviceDisconnectWarningMenu.c.
m_CategoryButtonsNames
ref array<string> m_CategoryButtonsNames = {"FIREARMS","MELEE","ATTACHMENTS","MAGAZINES","AMMO","FOOD","MEDICAL","CARS","BACKPACKS"} private
Definition at line 33 of file ScriptConsole.c.
m_CategoryButtonsWidgets
ref array<Widget> m_CategoryButtonsWidgets = new array<Widget> private
Definition at line 32 of file ScriptConsole.c.
m_CategoryMask
int m_CategoryMask private
Definition at line 38 of file ScriptConsole.c.
m_CategoryMergeType
CheckBoxWidget m_CategoryMergeType private
Definition at line 2991 of file ScriptConsole.c.
m_CategoryNameText
protected TextWidget m_CategoryNameText private
Definition at line 112 of file GesturesMenu.c.
m_CategoryStructure
protected ref map<int,Widget> m_CategoryStructure private
Definition at line 47 of file ControlsXboxNew.c.
m_ChangeAccount
protected Widget m_ChangeAccount private
Definition at line 12 of file MainMenuConsoles.c.
Referenced by OnClick().
m_channel_text
private TextWidget m_channel_text private
Definition at line 4 of file ChatInputMenu.c.
m_CharacterHeaderText
protected TextWidget m_CharacterHeaderText private
Definition at line 23 of file CharacterCreationMenu.c.
m_characterOrientation
private vector m_characterOrientation private
Definition at line 9 of file InspectMenuNew.c.
Referenced by UpdateRotation().
m_CharacterRotationFrame
protected Widget m_CharacterRotationFrame private
Definition at line 13 of file CharacterCreationMenu.c.
m_characterRotationX
private int m_characterRotationX private
Definition at line 6 of file InspectMenuNew.c.
m_characterRotationY
private int m_characterRotationY private
Definition at line 7 of file InspectMenuNew.c.
m_characterScaleDelta
private int m_characterScaleDelta private
Definition at line 8 of file InspectMenuNew.c.
m_ChooseServer
protected Widget m_ChooseServer private
Definition at line 15 of file MainMenu.c.
Referenced by OnClick().
m_ClassCheckboxes
protected ref map<CheckBoxWidget, int> m_ClassCheckboxes = new map<CheckBoxWidget, int> private
Definition at line 11 of file ScriptConsole.c.
m_ClClassesList
protected ref TStringArray m_ClClassesList private
Definition at line 1079 of file SceneEditorMenu.c.
m_ClearButton
ButtonWidget m_ClearButton private
Definition at line 64 of file ScriptConsoleAddPosition.c.
m_ClearInventory
CheckBoxWidget m_ClearInventory private
Definition at line 2989 of file ScriptConsole.c.
m_ClientLogClearButton
ButtonWidget m_ClientLogClearButton private
Definition at line 2937 of file ScriptConsole.c.
m_ClientLogListbox
TextListboxWidget m_ClientLogListbox private
Definition at line 2935 of file ScriptConsole.c.
m_ClientLogScrollCheckbox
CheckBoxWidget m_ClientLogScrollCheckbox private
Definition at line 2938 of file ScriptConsole.c.
m_close_timer
private ref Timer m_close_timer private
Definition at line 6 of file ChatInputMenu.c.
m_CloseConsoleButton
ButtonWidget m_CloseConsoleButton private
Definition at line 6 of file HelpScreen.c.
m_ClSelectedClass
protected string m_ClSelectedClass private
Definition at line 1078 of file SceneEditorMenu.c.
m_ClWgtButtonAddAtt
protected ButtonWidget m_ClWgtButtonAddAtt private
Definition at line 1082 of file SceneEditorMenu.c.
m_ClWgtEbxFilter
protected EditBoxWidget m_ClWgtEbxFilter private
Definition at line 1080 of file SceneEditorMenu.c.
m_ClWgtLbxClassesList
protected TextListboxWidget m_ClWgtLbxClassesList private
Definition at line 1081 of file SceneEditorMenu.c.
m_CommunityTab
protected ref ServerBrowserTab m_CommunityTab private
Definition at line 19 of file ServerBrowserMenuNew.c.
Referenced by GetSelectedTab().
m_ConfigData
ref ConfigParamsEx m_ConfigData static private
Definition at line 9 of file ScriptConsole.c.
m_ConfigDebugProfile [1/2]
PluginConfigDebugProfile m_ConfigDebugProfile private
Definition at line 1129 of file SceneEditorMenu.c.
m_ConfigDebugProfile [2/2]
PluginConfigDebugProfile m_ConfigDebugProfile private
Definition at line 3284 of file ScriptConsole.c.
m_ConfigDebugProfileFixed [1/2]
protected PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed private
Definition at line 1128 of file SceneEditorMenu.c.
m_ConfigDebugProfileFixed [2/2]
PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed private
Definition at line 3285 of file ScriptConsole.c.
m_ConfigHierarchyTextListbox
TextListboxWidget m_ConfigHierarchyTextListbox private
Definition at line 3044 of file ScriptConsole.c.
m_ConfigsButton
protected EditBoxWidget m_ConfigsButton private
Definition at line 1119 of file SceneEditorMenu.c.
m_ConfigTextField
string m_ConfigTextField static private
Definition at line 3073 of file ScriptConsole.c.
m_ConfigVariablesTextListbox
TextListboxWidget m_ConfigVariablesTextListbox private
Definition at line 3045 of file ScriptConsole.c.
m_confirm_button
protected ButtonWidget m_confirm_button private
Definition at line 5 of file NoteMenu.c.
m_ConfirmationText
private string m_ConfirmationText private
Definition at line 10 of file InputDeviceDisconnectWarningMenu.c.
m_content
protected HtmlWidget m_content private
Definition at line 6 of file BookMenu.c.
m_Content
protected WrapSpacerWidget m_Content private
Definition at line 24 of file CreditsMenu.c.
m_content_pos
protected float m_content_pos private
Definition at line 9 of file BookMenu.c.
m_content_total_height
protected float m_content_total_height private
Definition at line 8 of file BookMenu.c.
m_ContinueButton [1/2]
protected Widget m_ContinueButton private
Definition at line 5 of file InGameMenu.c.
m_ContinueButton [2/2]
protected ButtonWidget m_ContinueButton private
Definition at line 24 of file InGameMenuXbox.c.
m_Controls
protected Widget m_Controls private
Definition at line 17 of file MainMenuConsoles.c.
Referenced by OnClick().
m_ControlsButton
protected ButtonWidget m_ControlsButton private
Definition at line 29 of file InGameMenuXbox.c.
m_ControlsImage
protected Widget m_ControlsImage private
Definition at line 42 of file ControlsXboxNew.c.
m_ControlsLayoutImage
protected ImageWidget m_ControlsLayoutImage private
Definition at line 36 of file ControlsXboxNew.c.
m_ControlsTab
protected ref OptionsMenuControls m_ControlsTab private
Definition at line 10 of file OptionsMenu.c.
m_CopyButton
protected ButtonWidget m_CopyButton private
Definition at line 56 of file CameraToolsMenu.c.
m_CopyInfoButton
protected Widget m_CopyInfoButton private
Definition at line 17 of file InGameMenu.c.
m_CopySoundset
ButtonWidget m_CopySoundset private
Definition at line 2966 of file ScriptConsole.c.
m_CopyToClipboardButton
protected ButtonWidget m_CopyToClipboardButton private
Definition at line 1115 of file SceneEditorMenu.c.
m_CreditsData
protected ref JsonDataCredits m_CreditsData private
Definition at line 17 of file CreditsMenu.c.
m_CreditsEntries
protected ref array<ref CreditsElement> m_CreditsEntries = new array<ref CreditsElement> private
Definition at line 20 of file CreditsMenu.c.
m_CurrentCategory
protected int m_CurrentCategory private
Definition at line 123 of file GesturesMenu.c.
m_CurrentlyHighlighted
protected Widget m_CurrentlyHighlighted private
Definition at line 14 of file RespawnDialogue.c.
m_CurrentMuteButtonText
protected string m_CurrentMuteButtonText private
Definition at line 11 of file InGameMenuXbox.c.
m_CurrentPresetVariant
protected int m_CurrentPresetVariant = -1 private
Definition at line 33 of file ControlsXboxNew.c.
m_CurrentSettingAlternateKeyIndex
protected int m_CurrentSettingAlternateKeyIndex = -1 private
Definition at line 17 of file KeybindingsMenu.c.
m_CurrentSettingKeyIndex
protected int m_CurrentSettingKeyIndex = -1 private
Definition at line 16 of file KeybindingsMenu.c.
m_CurrentTabIdx
protected int m_CurrentTabIdx = -1 private
Definition at line 32 of file ControlsXboxNew.c.
m_CurrentTime
protected float m_CurrentTime = 0.0 private
Definition at line 19 of file CreditsMenu.c.
m_CustomizeCharacter
protected Widget m_CustomizeCharacter private
Definition at line 16 of file MainMenu.c.
Referenced by OnClick().
m_CustomRespawn
protected Widget m_CustomRespawn private
Definition at line 11 of file RespawnDialogue.c.
m_DamageEditBox [1/2]
protected EditBoxWidget m_DamageEditBox private
Definition at line 1116 of file SceneEditorMenu.c.
m_DamageEditBox [2/2]
EditBoxWidget m_DamageEditBox private
Definition at line 3021 of file ScriptConsole.c.
m_DateDay
EditBoxWidget m_DateDay private
Definition at line 2962 of file ScriptConsole.c.
m_DateHour
EditBoxWidget m_DateHour private
Definition at line 2963 of file ScriptConsole.c.
m_DateMinute
EditBoxWidget m_DateMinute private
Definition at line 2964 of file ScriptConsole.c.
m_DateMonth
EditBoxWidget m_DateMonth private
Definition at line 2961 of file ScriptConsole.c.
m_DateYear
EditBoxWidget m_DateYear private
Definition at line 2960 of file ScriptConsole.c.
m_DebugMapWidget
MapWidget m_DebugMapWidget private
Definition at line 3071 of file ScriptConsole.c.
m_DebugShapes
ref array<Shape> m_DebugShapes = new array<Shape> static private
Definition at line 23 of file ScriptConsole.c.
m_Defaults
protected ButtonWidget m_Defaults private
Definition at line 13 of file KeybindingsMenu.c.
Referenced by OnClick().
m_DeleteEvent
protected ButtonWidget m_DeleteEvent private
Definition at line 53 of file CameraToolsMenu.c.
m_DeleteKeyframe
protected ButtonWidget m_DeleteKeyframe private
Definition at line 48 of file CameraToolsMenu.c.
m_DescriptionText
private TextWidget m_DescriptionText private
Definition at line 5 of file LogoutMenu.c.
m_Details
protected Widget m_Details private
Definition at line 19 of file OptionsMenu.c.
m_DetailsLabel
protected TextWidget m_DetailsLabel private
Definition at line 21 of file CharacterCreationMenu.c.
m_DetailsRoot
protected Widget m_DetailsRoot private
Definition at line 20 of file CharacterCreationMenu.c.
m_DetailsText
protected RichTextWidget m_DetailsText private
Definition at line 22 of file CharacterCreationMenu.c.
m_Developer [1/2]
protected PluginDeveloper m_Developer private
Definition at line 1126 of file SceneEditorMenu.c.
m_Developer [2/2]
PluginDeveloper m_Developer private
Definition at line 3283 of file ScriptConsole.c.
m_DeviceListWidget
private RichTextWidget m_DeviceListWidget private
Definition at line 14 of file InputDeviceDisconnectWarningMenu.c.
m_DeviceMessages
private ref map<int,string> m_DeviceMessages private
Definition at line 5 of file InputDeviceDisconnectWarningMenu.c.
m_DeviceOrder
private ref array<int> m_DeviceOrder = {EUAINPUT_DEVICE_CONTROLLER,EUAINPUT_DEVICE_MOUSE,EUAINPUT_DEVICE_KEYBOARD} private
Definition at line 4 of file InputDeviceDisconnectWarningMenu.c.
m_DevicesText
private string m_DevicesText private
Definition at line 8 of file InputDeviceDisconnectWarningMenu.c.
m_DiagDrawButton
ButtonWidget m_DiagDrawButton private
Definition at line 2944 of file ScriptConsole.c.
m_DiagDrawmodeTextListbox
TextListboxWidget m_DiagDrawmodeTextListbox private
Definition at line 2943 of file ScriptConsole.c.
m_DiagToggleButton
ButtonWidget m_DiagToggleButton private
Definition at line 2941 of file ScriptConsole.c.
m_DiagToggleTextListbox
TextListboxWidget m_DiagToggleTextListbox private
Definition at line 2940 of file ScriptConsole.c.
m_DisconnectedDevices
private ref array<int> m_DisconnectedDevices private
Definition at line 3 of file InputDeviceDisconnectWarningMenu.c.
m_DownButton
protected ButtonWidget m_DownButton private
Definition at line 1110 of file SceneEditorMenu.c.
m_DrawDistanceWidget
EditBoxWidget m_DrawDistanceWidget private
Definition at line 3019 of file ScriptConsole.c.
m_DrawInWorld
ButtonWidget m_DrawInWorld private
Definition at line 2945 of file ScriptConsole.c.
m_DrawInWorldClear
ButtonWidget m_DrawInWorldClear private
Definition at line 2946 of file ScriptConsole.c.
m_DumpParamButton
ButtonWidget m_DumpParamButton private
Definition at line 3047 of file ScriptConsole.c.
m_edit
protected MultilineEditBoxWidget m_edit private
Definition at line 3 of file NoteMenu.c.
m_edit_box
private EditBoxWidget m_edit_box private
Definition at line 3 of file ChatInputMenu.c.
m_Editbox
EditBoxWidget m_Editbox private
Definition at line 47 of file ScriptConsoleNewPresetDialog.c.
m_EditboxName
EditBoxWidget m_EditboxName private
Definition at line 60 of file ScriptConsoleAddPosition.c.
m_EditboxPos
EditBoxWidget m_EditboxPos private
Definition at line 61 of file ScriptConsoleAddPosition.c.
m_EnfScriptClear
ButtonWidget m_EnfScriptClear private
Definition at line 2950 of file ScriptConsole.c.
m_EnfScriptEdit
MultilineEditBoxWidget m_EnfScriptEdit private
Definition at line 2948 of file ScriptConsole.c.
m_EnfScriptRun
ButtonWidget m_EnfScriptRun private
Definition at line 2949 of file ScriptConsole.c.
m_EnscriptConsoleHistory
ref TStringArray m_EnscriptConsoleHistory private
Definition at line 2927 of file ScriptConsole.c.
m_EnscriptConsoleHistoryServer
ref TStringArray m_EnscriptConsoleHistoryServer private
Definition at line 2928 of file ScriptConsole.c.
m_EnscriptHistoryRow
int m_EnscriptHistoryRow private
Definition at line 2925 of file ScriptConsole.c.
m_EnscriptHistoryRowServer
int m_EnscriptHistoryRowServer private
Definition at line 2926 of file ScriptConsole.c.
m_EventContent
protected Widget m_EventContent private
Definition at line 28 of file CameraToolsMenu.c.
m_Events
protected ref array<ref CTEvent> m_Events private
Definition at line 25 of file CameraToolsMenu.c.
m_Exit
protected Widget m_Exit private
Definition at line 22 of file MainMenu.c.
m_ExitButton [1/2]
protected Widget m_ExitButton private
Definition at line 7 of file InGameMenu.c.
m_ExitButton [2/2]
protected ButtonWidget m_ExitButton private
Definition at line 25 of file InGameMenuXbox.c.
m_FavoriteButton
protected Widget m_FavoriteButton private
Definition at line 14 of file InGameMenu.c.
m_FavoriteImage
protected Widget m_FavoriteImage private
Definition at line 15 of file InGameMenu.c.
m_Favorites
protected ref TStringArray m_Favorites private
Definition at line 24 of file ServerBrowserMenuNew.c.
Referenced by GetFavoritedServerIds().
m_FavoritesTab
protected ref ServerBrowserTab m_FavoritesTab private
Definition at line 20 of file ServerBrowserMenuNew.c.
Referenced by GetSelectedTab().
m_FilterOrderButton
ButtonWidget m_FilterOrderButton private
Definition at line 2972 of file ScriptConsole.c.
m_FilterOrderImage
ImageWidget m_FilterOrderImage private
Definition at line 2995 of file ScriptConsole.c.
m_FilterOrderReversed
bool m_FilterOrderReversed private
Definition at line 39 of file ScriptConsole.c.
m_FollowingBone
protected ref Param2<int, int> m_FollowingBone private
Definition at line 17 of file CameraToolsMenu.c.
m_FollowingTimeFinished
protected float m_FollowingTimeFinished private
Definition at line 16 of file CameraToolsMenu.c.
m_FreeflightCamTransform
vector m_FreeflightCamTransform[4] private
Definition at line 4 of file CameraToolsMenu.c.
m_GamercardAvailable
protected bool m_GamercardAvailable private
Definition at line 16 of file InGameMenuXbox.c.
m_GameTab
protected ref OptionsMenuGame m_GameTab private
Definition at line 7 of file OptionsMenu.c.
m_GenderSelector
protected ref OptionSelectorMultistateCharacterMenu m_GenderSelector private
Definition at line 26 of file CharacterCreationMenu.c.
m_GestureItemCardPanel
protected Widget m_GestureItemCardPanel private
Definition at line 108 of file GesturesMenu.c.
m_GestureItems
protected ref array<ref GestureMenuItem> m_GestureItems private
Definition at line 109 of file GesturesMenu.c.
m_GPSMarker
protected Widget m_GPSMarker private
Definition at line 20 of file MapMenu.c.
m_GPSMarkerArrow
protected ImageWidget m_GPSMarkerArrow private
Definition at line 21 of file MapMenu.c.
m_GroupsContainer
protected ref KeybindingsContainer m_GroupsContainer private
Definition at line 6 of file KeybindingsMenu.c.
Referenced by GetCurrentTab().
m_HardReset
protected ButtonWidget m_HardReset private
Definition at line 14 of file KeybindingsMenu.c.
m_HelpTextListboxWidget
TextListboxWidget m_HelpTextListboxWidget private
Definition at line 3051 of file ScriptConsole.c.
m_HintPanel
protected ref UiHintPanel m_HintPanel private
Definition at line 24 of file InGameMenu.c.
m_html
protected HtmlWidget m_html private
Definition at line 4 of file NoteMenu.c.
m_Hud
protected ref IngameHud m_Hud private
Definition at line 14 of file MapMenu.c.
m_HudDCharAgents
CheckBoxWidget m_HudDCharAgents private
Definition at line 2983 of file ScriptConsole.c.
m_HudDCharDebug
CheckBoxWidget m_HudDCharDebug private
Definition at line 2984 of file ScriptConsole.c.
m_HudDCharLevels
CheckBoxWidget m_HudDCharLevels private
Definition at line 2980 of file ScriptConsole.c.
m_HudDCharModifiers
CheckBoxWidget m_HudDCharModifiers private
Definition at line 2982 of file ScriptConsole.c.
m_HudDCharStats
CheckBoxWidget m_HudDCharStats private
Definition at line 2979 of file ScriptConsole.c.
m_HudDCharStomach
CheckBoxWidget m_HudDCharStomach private
Definition at line 2981 of file ScriptConsole.c.
m_HudDFreeCamCross
CheckBoxWidget m_HudDFreeCamCross private
Definition at line 2985 of file ScriptConsole.c.
m_HudDTemperature
CheckBoxWidget m_HudDTemperature private
Definition at line 2990 of file ScriptConsole.c.
m_HudDVersion
CheckBoxWidget m_HudDVersion private
Definition at line 2986 of file ScriptConsole.c.
m_image
ImageWidget m_image private
Definition at line 39 of file LoadingMenu.c.
m_ImageMarkerStructure
protected ref map<int,Widget> m_ImageMarkerStructure private
Definition at line 46 of file ControlsXboxNew.c.
m_Images
protected ImageWidget m_Images private
Definition at line 19 of file MapMenu.c.
m_Info
private TextWidget m_Info private
Definition at line 4 of file InviteMenu.c.
m_InfoPanel
protected Widget m_InfoPanel private
Definition at line 26 of file CreditsMenu.c.
m_InfoPanelText
protected RichTextWidget m_InfoPanelText private
Definition at line 25 of file CreditsMenu.c.
m_InfoTextLeft
protected Widget m_InfoTextLeft private
Definition at line 11 of file TutorialsMenu.c.
m_InfoTextRight
protected Widget m_InfoTextRight private
Definition at line 12 of file TutorialsMenu.c.
m_Initialized
private bool m_Initialized private
Definition at line 7 of file InputDeviceDisconnectWarningMenu.c.
m_Instance
protected CameraToolsMenu m_Instance static private
Definition at line 3 of file CameraToolsMenu.c.
m_InterpTypeCombo
protected XComboBoxWidget m_InterpTypeCombo private
Definition at line 31 of file CameraToolsMenu.c.
m_InterpTypeSpeedCombo
protected XComboBoxWidget m_InterpTypeSpeedCombo private
Definition at line 30 of file CameraToolsMenu.c.
m_iPosition
protected int m_iPosition private
Definition at line 41 of file DayZGame.c.
m_IsCategorySelected
protected bool m_IsCategorySelected private
Definition at line 121 of file GesturesMenu.c.
m_IsMenuClosing
protected bool m_IsMenuClosing private
Definition at line 122 of file GesturesMenu.c.
m_IsOpenning
protected bool m_HasCompass protected bool m_HasGPS protected bool m_IsOpenning private
Definition at line 10 of file MapMenu.c.
m_IsPaused
bool m_IsPaused private
Definition at line 8 of file MainMenuVideo.c.
m_IsPlaying
protected bool m_IsPlaying private
Definition at line 13 of file CameraToolsMenu.c.
m_IsRefreshing
protected TabType m_IsRefreshing = TabType.NONE private
Definition at line 23 of file ServerBrowserMenuNew.c.
Referenced by GetServersLoadingTab().
m_IsRespawn
protected bool m_IsRespawn private
Definition at line 158 of file DayZGame.c.
m_IsStatic
protected bool m_IsStatic private
Definition at line 42 of file DayZGame.c.
m_IsWriting
protected bool m_IsWriting private
Definition at line 8 of file NoteMenu.c.
m_item_widget
private ItemPreviewWidget m_item_widget private
Definition at line 4 of file InspectMenuNew.c.
m_ItemCardPanel
protected Widget m_ItemCardPanel private
Definition at line 90 of file RadialQuickbarMenu.c.
m_ItemDamageLabel
TextWidget m_ItemDamageLabel private
Definition at line 3022 of file ScriptConsole.c.
m_ItemDisagPlugin
PluginItemDiagnostic m_ItemDisagPlugin private
Definition at line 31 of file ScriptConsole.c.
m_ItemMoveDownButton
ButtonWidget m_ItemMoveDownButton private
Definition at line 3017 of file ScriptConsole.c.
m_ItemMoveUpButton
ButtonWidget m_ItemMoveUpButton private
Definition at line 3016 of file ScriptConsole.c.
m_ItemNameCopy
ButtonWidget m_ItemNameCopy private
Definition at line 3014 of file ScriptConsole.c.
m_ItemPreviewCheckbox
CheckBoxWidget m_ItemPreviewCheckbox private
Definition at line 2992 of file ScriptConsole.c.
m_ItemPreviewWidget
ItemPreviewWidget m_ItemPreviewWidget private
Definition at line 3050 of file ScriptConsole.c.
m_ItemQuantityLabel
TextWidget m_ItemQuantityLabel private
Definition at line 3023 of file ScriptConsole.c.
m_Items
protected ref array<ref RadialQuickbarItem> m_Items private
Definition at line 91 of file RadialQuickbarMenu.c.
m_ItemToAssign
EntityAI m_ItemToAssign static private
Definition at line 101 of file RadialQuickbarMenu.c.
m_iTime
private int m_iTime private
Definition at line 5 of file InviteMenu.c.
m_KBDropdown
protected ref DropdownPrefab m_KBDropdown private
Definition at line 4 of file KeybindingsMenu.c.
m_KeyBindingsTextListboxWidget
TextListboxWidget m_KeyBindingsTextListboxWidget private
Definition at line 3 of file HelpScreen.c.
m_KeybindsTab
protected ref TutorialKeybinds m_KeybindsTab private
Definition at line 19 of file TutorialsMenu.c.
m_KeyframeContent
protected Widget m_KeyframeContent private
Definition at line 27 of file CameraToolsMenu.c.
m_label
TextWidget m_label private
Definition at line 37 of file LoadingMenu.c.
m_Label
TextWidget m_Label private
Definition at line 62 of file ScriptConsoleAddPosition.c.
m_LANTab
protected ref ServerBrowserTab m_LANTab private
Definition at line 21 of file ServerBrowserMenuNew.c.
Referenced by GetSelectedTab().
m_LastFocusedButton
protected ref Widget m_LastFocusedButton private
Definition at line 36 of file MainMenu.c.
m_LastPlayedTooltip
protected Widget m_LastPlayedTooltip private
Definition at line 29 of file MainMenu.c.
m_LastPlayedTooltipIP
protected TextWidget m_LastPlayedTooltipIP private
Definition at line 32 of file MainMenu.c.
m_LastPlayedTooltipLabel
protected Widget m_LastPlayedTooltipLabel private
Definition at line 30 of file MainMenu.c.
m_LastPlayedTooltipName
protected TextWidget m_LastPlayedTooltipName private
Definition at line 31 of file MainMenu.c.
m_LastPlayedTooltipPort
protected TextWidget m_LastPlayedTooltipPort private
Definition at line 33 of file MainMenu.c.
m_LastPlayedTooltipTimer
protected ref WidgetFadeTimer m_LastPlayedTooltipTimer private
Definition at line 35 of file MainMenu.c.
m_LastSelectedObject
string m_LastSelectedObject static private
Definition at line 3000 of file ScriptConsole.c.
m_LateInit
ref Timer m_LateInit = new Timer() private
Definition at line 35 of file ScriptConsole.c.
m_LegendResizer
protected ref SizeToChild m_LegendResizer private
Definition at line 17 of file MapMenu.c.
m_Load
protected ButtonWidget m_Load private
Definition at line 44 of file CameraToolsMenu.c.
m_LocationAddButton
ButtonWidget m_LocationAddButton private
Definition at line 2970 of file ScriptConsole.c.
m_LocationRemoveButton
ButtonWidget m_LocationRemoveButton private
Definition at line 2971 of file ScriptConsole.c.
m_Logo
protected ImageWidget m_Logo private
Definition at line 22 of file CreditsMenu.c.
m_LogoFadeInIncrement
protected float m_LogoFadeInIncrement private
Definition at line 10 of file CreditsMenu.c.
m_LogoFadeInLevel
protected float m_LogoFadeInLevel private
Definition at line 11 of file CreditsMenu.c.
m_LogoutTimetext
private TextWidget m_LogoutTimetext private
Definition at line 3 of file InviteMenu.c.
m_LogoutTimeText
private TextWidget m_LogoutTimeText private
Definition at line 4 of file LogoutMenu.c.
m_LogsEnabled
CheckBoxWidget m_LogsEnabled private
Definition at line 2978 of file ScriptConsole.c.
m_Map
protected ItemMap m_Map private
Definition at line 32 of file MapMenu.c.
m_MapMenuHandler
protected ref MapHandler m_MapMenuHandler private
Definition at line 15 of file MapMenu.c.
m_MapNavigationBehaviour
protected ref MapNavigationBehaviour m_MapNavigationBehaviour private
Definition at line 35 of file MapMenu.c.
m_MapPos
vector m_MapPos private
Definition at line 12 of file ScriptConsole.c.
m_MapWidgetInstance
protected ref MapWidget m_MapWidgetInstance private
Definition at line 16 of file MapMenu.c.
m_MenuFadeInIncrement
protected float m_MenuFadeInIncrement private
Definition at line 7 of file CreditsMenu.c.
m_MenuFadeInLevel
protected float m_MenuFadeInLevel private
Definition at line 8 of file CreditsMenu.c.
m_MenuFadeInLevel2
protected float m_MenuFadeInLevel2 = 1 private
Definition at line 9 of file CreditsMenu.c.
m_Message
TextWidget m_Message private
Definition at line 63 of file ScriptConsoleAddPosition.c.
m_MessageButton
protected Widget m_MessageButton private
Definition at line 20 of file MainMenu.c.
m_Mission
protected MissionMainMenu m_Mission private
Definition at line 6 of file MainMenu.c.
m_MissionGameplay
MissionGameplay m_MissionGameplay private
Definition at line 2931 of file ScriptConsole.c.
m_ModalLock
protected bool m_ModalLock private
Definition at line 23 of file OptionsMenu.c.
m_ModdedWarning
protected ref TextWidget m_ModdedWarning private
Definition at line 19 of file InGameMenu.c.
m_ModsDetailed
protected ref ModsMenuDetailed m_ModsDetailed private
Definition at line 40 of file MainMenu.c.
Referenced by LoadMods().
m_ModsSimple
protected ref ModsMenuSimple m_ModsSimple private
Definition at line 39 of file MainMenu.c.
Referenced by LoadMods().
m_ModsTooltip
protected ref ModsMenuTooltip m_ModsTooltip private
Definition at line 41 of file MainMenu.c.
m_ModuleConfigViewer
PluginConfigViewer m_ModuleConfigViewer private
Definition at line 3286 of file ScriptConsole.c.
m_ModuleLocalEnscriptHistory
PluginLocalEnscriptHistory m_ModuleLocalEnscriptHistory private
Definition at line 2929 of file ScriptConsole.c.
m_ModuleLocalEnscriptHistoryServer
PluginLocalEnscriptHistoryServer m_ModuleLocalEnscriptHistoryServer private
Definition at line 2930 of file ScriptConsole.c.
m_ModuleSceneManager
protected PluginSceneManager m_ModuleSceneManager private
Definition at line 1050 of file SceneEditorMenu.c.
m_MouseBindingsTextListboxWidget
TextListboxWidget m_MouseBindingsTextListboxWidget private
Definition at line 4 of file HelpScreen.c.
m_MouseCurPos
TextWidget m_MouseCurPos private
Definition at line 2975 of file ScriptConsole.c.
m_MuteAvailable
protected bool m_MuteAvailable private
Definition at line 14 of file InGameMenuXbox.c.
m_MuteButtonTextID
protected string m_MuteButtonTextID private
Definition at line 6 of file InGameMenuXbox.c.
Referenced by SetMuteButtonText().
m_NameSelector
protected ref OptionSelectorEditbox m_NameSelector private
Definition at line 25 of file CharacterCreationMenu.c.
m_NewsMain
protected Widget m_NewsMain private
Definition at line 23 of file MainMenu.c.
m_NewsSec1
protected Widget m_NewsSec1 private
Definition at line 24 of file MainMenu.c.
m_NewsSec2
protected Widget m_NewsSec2 private
Definition at line 25 of file MainMenu.c.
m_NextCameraIndex
protected int m_NextCameraIndex = 1 private
Definition at line 14 of file CameraToolsMenu.c.
m_NextCamPosition
protected vector m_NextCamPosition private
Definition at line 5 of file CameraToolsMenu.c.
m_NextCharacter
protected Widget m_NextCharacter private
Definition at line 27 of file MainMenu.c.
m_NextPresetText
protected string m_NextPresetText private
Definition at line 31 of file ControlsXboxNew.c.
Referenced by UpdateToolbarText().
m_NotifyFadeTimer
protected ref WidgetFadeTimer m_NotifyFadeTimer private
Definition at line 1098 of file SceneEditorMenu.c.
m_NotifyWgtPanel
protected Widget m_NotifyWgtPanel private
Definition at line 1099 of file SceneEditorMenu.c.
m_ObjectConfigFilter
EditBoxWidget m_ObjectConfigFilter private
Definition at line 3043 of file ScriptConsole.c.
m_ObjectFilter
EditBoxWidget m_ObjectFilter private
Definition at line 2996 of file ScriptConsole.c.
m_ObjectsScope
int m_ObjectsScope = 2 static private
Definition at line 19 of file ScriptConsole.c.
m_ObjectsTextListbox
TextListboxWidget m_ObjectsTextListbox private
Definition at line 3002 of file ScriptConsole.c.
m_OfficialTab
protected ref ServerBrowserTab m_OfficialTab private
Definition at line 18 of file ServerBrowserMenuNew.c.
Referenced by GetSelectedTab().
m_OnlineButton
protected ButtonWidget m_OnlineButton private
Definition at line 30 of file InGameMenuXbox.c.
m_OnlineMenu
protected Widget m_OnlineMenu private
Definition at line 22 of file InGameMenuXbox.c.
m_OpenDLC
protected Widget m_OpenDLC private
Definition at line 11 of file MainMenuConsoles.c.
Referenced by OnClick().
m_OpenedPopups
protected ref TIntArray m_OpenedPopups private
Definition at line 1065 of file SceneEditorMenu.c.
m_OpenGameCardButtonTextID
protected string m_OpenGameCardButtonTextID private
Definition at line 10 of file InGameMenuXbox.c.
m_Options [1/2]
protected Widget m_Options private
Definition at line 16 of file MainMenuConsoles.c.
Referenced by OnClick().
m_Options [2/2]
protected ref GameOptions m_Options private
Definition at line 12 of file OptionsMenu.c.
m_OptionsButton [1/2]
protected Widget m_OptionsButton private
Definition at line 12 of file InGameMenu.c.
m_OptionsButton [2/2]
protected ButtonWidget m_OptionsButton private
Definition at line 28 of file InGameMenuXbox.c.
m_OriginalCharacterID
int m_OriginalCharacterID private
Definition at line 32 of file CharacterCreationMenu.c.
m_OriginalPresetIndex
protected int m_OriginalPresetIndex private
Definition at line 18 of file KeybindingsMenu.c.
m_page
protected TextWidget m_page private
Definition at line 5 of file BookMenu.c.
m_page_height
protected float m_page_height private
Definition at line 7 of file BookMenu.c.
Referenced by NextPrevPage().
m_Paper
protected ItemBase m_Paper private
Definition at line 6 of file NoteMenu.c.
m_Pen
protected EntityAI m_Pen private
Definition at line 7 of file NoteMenu.c.
m_PenColor
protected string m_PenColor private
Definition at line 11 of file NoteMenu.c.
m_PlatformHolder
protected Widget m_PlatformHolder private
Definition at line 43 of file ControlsXboxNew.c.
m_Play [1/2]
protected Widget m_Play private
Definition at line 41 of file CameraToolsMenu.c.
Referenced by Init(), and OnClick().
m_Play [2/2]
protected Widget m_Play private
Definition at line 14 of file MainMenu.c.
m_PlayedCharacterInfo
protected Widget m_PlayedCharacterInfo private
Definition at line 18 of file CharacterCreationMenu.c.
m_PlayerAlive
protected bool m_PlayerAlive private
Definition at line 18 of file InGameMenuXbox.c.
m_PlayerCurPos
TextWidget m_PlayerCurPos private
Definition at line 2974 of file ScriptConsole.c.
m_PlayerDebugStats
ref array<ref RemotePlayerStatDebug> m_PlayerDebugStats = new array<ref RemotePlayerStatDebug> private
Definition at line 3149 of file ScriptConsole.c.
m_PlayerMouseDiff
TextWidget m_PlayerMouseDiff private
Definition at line 2976 of file ScriptConsole.c.
m_PlayerName
protected TextWidget m_PlayerName private
Definition at line 9 of file MainMenu.c.
m_PlayerPosRefreshBlocked
bool m_PlayerPosRefreshBlocked private
Definition at line 13 of file ScriptConsole.c.
m_PlaySoundset
ButtonWidget m_PlaySoundset private
Definition at line 2967 of file ScriptConsole.c.
m_PlaySoundsetButton
ButtonWidget m_PlaySoundsetButton private
Definition at line 3033 of file ScriptConsole.c.
m_PlaySoundsetLooped
ButtonWidget m_PlaySoundsetLooped private
Definition at line 2968 of file ScriptConsole.c.
m_PlayVideo
protected Widget m_PlayVideo private
Definition at line 17 of file MainMenu.c.
Referenced by OnClick().
m_Popups
protected ref map<int, ref UIPopupScript> m_Popups private
Definition at line 1066 of file SceneEditorMenu.c.
m_PopupScriptPositionManager
protected UIPopupScriptPositionManager m_PopupScriptPositionManager private
Definition at line 1127 of file SceneEditorMenu.c.
m_PositionsListbox
TextListboxWidget m_PositionsListbox private
Definition at line 2977 of file ScriptConsole.c.
m_PresetAddItemtButton [1/2]
protected ButtonWidget m_PresetAddItemtButton private
Definition at line 1104 of file SceneEditorMenu.c.
m_PresetAddItemtButton [2/2]
ButtonWidget m_PresetAddItemtButton private
Definition at line 3013 of file ScriptConsole.c.
m_PresetDeleteButton [1/2]
protected ButtonWidget m_PresetDeleteButton private
Definition at line 1112 of file SceneEditorMenu.c.
m_PresetDeleteButton [2/2]
ButtonWidget m_PresetDeleteButton private
Definition at line 3010 of file ScriptConsole.c.
m_PresetItemsTextListbox [1/2]
protected TextListboxWidget m_PresetItemsTextListbox private
Definition at line 1103 of file SceneEditorMenu.c.
m_PresetItemsTextListbox [2/2]
TextListboxWidget m_PresetItemsTextListbox private
Definition at line 3008 of file ScriptConsole.c.
m_PresetNewButton [1/2]
protected ButtonWidget m_PresetNewButton private
Definition at line 1111 of file SceneEditorMenu.c.
m_PresetNewButton [2/2]
ButtonWidget m_PresetNewButton private
Definition at line 3009 of file ScriptConsole.c.
m_PresetRemoveItemButton [1/2]
protected ButtonWidget m_PresetRemoveItemButton private
Definition at line 1105 of file SceneEditorMenu.c.
m_PresetRemoveItemButton [2/2]
ButtonWidget m_PresetRemoveItemButton private
Definition at line 3015 of file ScriptConsole.c.
m_PresetRenameButton [1/2]
protected ButtonWidget m_PresetRenameButton private
Definition at line 1113 of file SceneEditorMenu.c.
m_PresetRenameButton [2/2]
ButtonWidget m_PresetRenameButton private
Definition at line 3011 of file ScriptConsole.c.
m_PresetSelector
protected ref OptionSelectorMultistate m_PresetSelector private
Definition at line 5 of file KeybindingsMenu.c.
m_PresetSetDefaultButton [1/2]
protected ButtonWidget m_PresetSetDefaultButton private
Definition at line 1114 of file SceneEditorMenu.c.
m_PresetSetDefaultButton [2/2]
ButtonWidget m_PresetSetDefaultButton private
Definition at line 3012 of file ScriptConsole.c.
m_PresetsTextListbox [1/2]
protected TextListboxWidget m_PresetsTextListbox private
Definition at line 1102 of file SceneEditorMenu.c.
m_PresetsTextListbox [2/2]
TextListboxWidget m_PresetsTextListbox private
Definition at line 3007 of file ScriptConsole.c.
m_PrevCharacter
protected Widget m_PrevCharacter private
Definition at line 26 of file MainMenu.c.
m_PreviewEntity
EntityAI m_PreviewEntity static private
Definition at line 24 of file ScriptConsole.c.
m_progressBar
ProgressBarWidget m_progressBar private
Definition at line 38 of file LoadingMenu.c.
m_PrWgtAttRoot
protected Widget m_PrWgtAttRoot private
Definition at line 1092 of file SceneEditorMenu.c.
m_PrWgtAttTitle
protected Widget m_PrWgtAttTitle private
Definition at line 1093 of file SceneEditorMenu.c.
m_PrWgtClassName
protected TextWidget m_PrWgtClassName private
Definition at line 1085 of file SceneEditorMenu.c.
m_PrWgtDir
protected EditBoxWidget m_PrWgtDir private
Definition at line 1089 of file SceneEditorMenu.c.
m_PrWgtDmg
protected EditBoxWidget m_PrWgtDmg private
Definition at line 1090 of file SceneEditorMenu.c.
m_PrWgtPoxX
protected EditBoxWidget m_PrWgtPoxX private
Definition at line 1086 of file SceneEditorMenu.c.
m_PrWgtPoxY
protected EditBoxWidget m_PrWgtPoxY private
Definition at line 1087 of file SceneEditorMenu.c.
m_PrWgtPoxZ
protected EditBoxWidget m_PrWgtPoxZ private
Definition at line 1088 of file SceneEditorMenu.c.
m_PrWidgetsAttachments
protected ref array<ref UIPropertyAttachment> m_PrWidgetsAttachments private
Definition at line 1095 of file SceneEditorMenu.c.
m_QuantityEditBox [1/2]
protected EditBoxWidget m_QuantityEditBox private
Definition at line 1117 of file SceneEditorMenu.c.
m_QuantityEditBox [2/2]
EditBoxWidget m_QuantityEditBox private
Definition at line 3020 of file ScriptConsole.c.
m_RandomizeCharacter
protected Widget m_RandomizeCharacter private
Definition at line 16 of file CharacterCreationMenu.c.
m_RectSpawnColumn
EditBoxWidget m_RectSpawnColumn private
Definition at line 3036 of file ScriptConsole.c.
m_RectSpawnColumnStep
EditBoxWidget m_RectSpawnColumnStep private
Definition at line 3038 of file ScriptConsole.c.
m_RectSpawnRow
EditBoxWidget m_RectSpawnRow private
Definition at line 3035 of file ScriptConsole.c.
m_RectSpawnRowStep
EditBoxWidget m_RectSpawnRowStep private
Definition at line 3037 of file ScriptConsole.c.
m_RefreshFilterTimer
ref Timer m_RefreshFilterTimer = new Timer() private
Definition at line 44 of file ScriptConsole.c.
m_Reset
protected ButtonWidget m_Reset private
Definition at line 16 of file OptionsMenu.c.
Referenced by OnClick().
m_RespawnButton
protected Widget m_RespawnButton private
Definition at line 9 of file InGameMenu.c.
m_RestartButton [1/2]
protected Widget m_RestartButton private
Definition at line 8 of file InGameMenu.c.
m_RestartButton [2/2]
protected ButtonWidget m_RestartButton private
Definition at line 27 of file InGameMenuXbox.c.
m_RestartDeadButton
protected ButtonWidget m_RestartDeadButton private
Definition at line 26 of file InGameMenuXbox.c.
m_RestartDeadCustomButton
protected Widget m_RestartDeadCustomButton private
Definition at line 11 of file InGameMenu.c.
m_RestartDeadRandomButton
protected Widget m_RestartDeadRandomButton private
Definition at line 10 of file InGameMenu.c.
m_RunColor
int m_RunColor private
Definition at line 28 of file ScriptConsole.c.
m_Save [1/2]
protected ButtonWidget m_Save private
Definition at line 43 of file CameraToolsMenu.c.
m_Save [2/2]
protected Widget m_Save private
Definition at line 15 of file CharacterCreationMenu.c.
m_SaveEvent
protected ButtonWidget m_SaveEvent private
Definition at line 52 of file CameraToolsMenu.c.
m_SaveKeyframe
protected ButtonWidget m_SaveKeyframe private
Definition at line 47 of file CameraToolsMenu.c.
m_Scene
DayZIntroScenePC m_Scene private
Definition at line 7 of file CharacterCreationMenu.c.
m_ScenePC
protected DayZIntroScenePC m_ScenePC private
Definition at line 7 of file MainMenu.c.
m_schemes_list
private TextListboxWidget m_schemes_list private
Definition at line 60 of file PresetsMenu.c.
m_ScriptOutputHistory
ref TStringArray m_ScriptOutputHistory = new TStringArray() static private
Definition at line 42 of file ScriptConsole.c.
m_ScriptOutputListbox
TextListboxWidget m_ScriptOutputListbox private
Definition at line 2936 of file ScriptConsole.c.
m_ScriptServer
bool m_ScriptServer private
Definition at line 36 of file ScriptConsole.c.
m_Scroller
protected ScrollWidget m_Scroller private
Definition at line 23 of file CreditsMenu.c.
m_ScrollIncrement
protected float m_ScrollIncrement private
Definition at line 12 of file CreditsMenu.c.
m_ScrollLevel
protected float m_ScrollLevel private
Definition at line 13 of file CreditsMenu.c.
m_ScrollMax
protected float m_ScrollMax private
Definition at line 14 of file CreditsMenu.c.
m_ScrollSize
protected float m_ScrollSize private
Definition at line 15 of file CreditsMenu.c.
m_SelectAvailable
protected bool m_SelectAvailable private
Definition at line 13 of file InGameMenuXbox.c.
m_SelectButtonTextID
protected string m_SelectButtonTextID private
Definition at line 9 of file InGameMenuXbox.c.
m_selected_tab
int m_selected_tab private
Definition at line 2923 of file ScriptConsole.c.
m_SelectedActor
protected CTActor m_SelectedActor private
Definition at line 21 of file CameraToolsMenu.c.
m_SelectedEvent
protected CTEvent m_SelectedEvent private
Definition at line 20 of file CameraToolsMenu.c.
m_SelectedItem
protected Widget m_SelectedItem private
Definition at line 120 of file GesturesMenu.c.
m_SelectedKeyframe
protected CTKeyframe m_SelectedKeyframe private
Definition at line 19 of file CameraToolsMenu.c.
m_SelectedObject [1/2]
protected string m_SelectedObject private
Definition at line 1124 of file SceneEditorMenu.c.
m_SelectedObject [2/2]
string m_SelectedObject private
Definition at line 2999 of file ScriptConsole.c.
m_SelectedObjectIsPreset [1/2]
protected bool m_SelectedObjectIsPreset private
Definition at line 1125 of file SceneEditorMenu.c.
m_SelectedObjectIsPreset [2/2]
int m_SelectedObjectIsPreset = -1 static private
Definition at line 3001 of file ScriptConsole.c.
m_SelectedObjectText
TextWidget m_SelectedObjectText private
Definition at line 2998 of file ScriptConsole.c.
m_SelectedRowCopy
ButtonWidget m_SelectedRowCopy private
Definition at line 3046 of file ScriptConsole.c.
m_SelectedServer
protected ServerBrowserEntry m_SelectedServer private
Definition at line 25 of file ServerBrowserMenuNew.c.
m_SeparatorPanel
protected Widget m_SeparatorPanel private
Definition at line 6 of file InGameMenu.c.
m_ServerInfoPanel [1/2]
protected Widget m_ServerInfoPanel private
Definition at line 13 of file InGameMenu.c.
m_ServerInfoPanel [2/2]
protected ref PlayerListScriptedWidget m_ServerInfoPanel private
Definition at line 20 of file InGameMenuXbox.c.
m_ServerInfoText
string m_ServerInfoText private
Definition at line 3 of file InGameMenu.c.
m_ServerIP
protected ref TextWidget m_ServerIP private
Definition at line 20 of file InGameMenu.c.
m_ServerName
protected ref TextWidget m_ServerName private
Definition at line 22 of file InGameMenu.c.
m_ServerPort
protected ref TextWidget m_ServerPort private
Definition at line 21 of file InGameMenu.c.
m_ServerRows
int m_ServerRows private
Definition at line 2924 of file ScriptConsole.c.
m_SetKeybinds
protected ref array<int> m_SetKeybinds private
Definition at line 20 of file KeybindingsMenu.c.
m_SettingsButton
protected Widget m_SettingsButton private
Definition at line 21 of file MainMenu.c.
m_ShoesSelector
protected ref OptionSelectorMultistateCharacterMenu m_ShoesSelector private
Definition at line 30 of file CharacterCreationMenu.c.
m_ShowOthers
CheckBoxWidget m_ShowOthers private
Definition at line 2988 of file ScriptConsole.c.
m_ShowProtected
CheckBoxWidget m_ShowProtected private
Definition at line 2987 of file ScriptConsole.c.
m_SkinSelector
protected ref OptionSelectorMultistateCharacterMenu m_SkinSelector private
Definition at line 27 of file CharacterCreationMenu.c.
m_SlObjectsList
protected ref map<int, SceneObject> m_SlObjectsList private
Definition at line 1071 of file SceneEditorMenu.c.
m_slot_widget
private ItemPreviewWidget m_slot_widget private
Definition at line 5 of file InspectMenuNew.c.
m_SlSelectedClass
protected string m_SlSelectedClass private
Definition at line 1070 of file SceneEditorMenu.c.
m_SlWgtEbxFilter
protected EditBoxWidget m_SlWgtEbxFilter private
Definition at line 1073 of file SceneEditorMenu.c.
m_SlWgtFocus
protected ButtonWidget m_SlWgtFocus private
Definition at line 1075 of file SceneEditorMenu.c.
m_SlWgtLbxObjectsList
protected TextListboxWidget m_SlWgtLbxObjectsList private
Definition at line 1072 of file SceneEditorMenu.c.
m_SlWgtLoadedScene
protected TextWidget m_SlWgtLoadedScene private
Definition at line 1069 of file SceneEditorMenu.c.
m_SlWgtSelect
protected ButtonWidget m_SlWgtSelect private
Definition at line 1074 of file SceneEditorMenu.c.
m_SoundFilter
EditBoxWidget m_SoundFilter private
Definition at line 3004 of file ScriptConsole.c.
m_SoundSet
EffectSound m_SoundSet static private
Definition at line 8 of file ScriptConsole.c.
m_SoundsTab
protected ref OptionsMenuSounds m_SoundsTab private
Definition at line 8 of file OptionsMenu.c.
m_SoundsTextListbox
TextListboxWidget m_SoundsTextListbox private
Definition at line 3005 of file ScriptConsole.c.
m_SpawnAsAttachment
ButtonWidget m_SpawnAsAttachment private
Definition at line 3028 of file ScriptConsole.c.
m_SpawnAsAttachmentButton
protected ButtonWidget m_SpawnAsAttachmentButton private
Definition at line 1108 of file SceneEditorMenu.c.
Referenced by OnClick().
m_SpawnBatchButton
ButtonWidget m_SpawnBatchButton private
Definition at line 3032 of file ScriptConsole.c.
m_SpawnDistanceEditBox [1/2]
protected EditBoxWidget m_SpawnDistanceEditBox private
Definition at line 1118 of file SceneEditorMenu.c.
m_SpawnDistanceEditBox [2/2]
EditBoxWidget m_SpawnDistanceEditBox private
Definition at line 2997 of file ScriptConsole.c.
m_SpawnGroundButton
ButtonWidget m_SpawnGroundButton private
Definition at line 3026 of file ScriptConsole.c.
m_SpawnGroundPatternGrid
ButtonWidget m_SpawnGroundPatternGrid private
Definition at line 3027 of file ScriptConsole.c.
m_SpawnInInvButton
ButtonWidget m_SpawnInInvButton private
Definition at line 3025 of file ScriptConsole.c.
m_SpawnInInventoryButton
protected ButtonWidget m_SpawnInInventoryButton private
Definition at line 1107 of file SceneEditorMenu.c.
Referenced by OnClick().
m_SpawnOnGroundButton
protected ButtonWidget m_SpawnOnGroundButton private
Definition at line 1106 of file SceneEditorMenu.c.
Referenced by OnClick().
m_SpawnSpecial
ButtonWidget m_SpawnSpecial private
Definition at line 3029 of file ScriptConsole.c.
m_Stats
protected ref MainMenuStats m_Stats private
Definition at line 3 of file MainMenu.c.
m_Stop
protected ButtonWidget m_Stop private
Definition at line 42 of file CameraToolsMenu.c.
m_StopSoundset
ButtonWidget m_StopSoundset private
Definition at line 2969 of file ScriptConsole.c.
m_SymbolCount
protected int m_SymbolCount private
Definition at line 10 of file NoteMenu.c.
m_Tab_buttons
ButtonWidget m_Tab_buttons[TABS_COUNT] private
Definition at line 3072 of file ScriptConsole.c.
m_tab_images
protected ImageWidget m_tab_images[TABS_COUNT] private
Definition at line 17 of file TutorialsMenu.c.
m_Tabber
protected TabberUI m_Tabber private
Definition at line 3 of file KeybindingsMenu.c.
m_TabberWidget
protected Widget m_TabberWidget private
Definition at line 41 of file ControlsXboxNew.c.
m_Tabs [1/2]
protected ref array<ref KeybindingsGroup> m_Tabs private
Definition at line 7 of file KeybindingsMenu.c.
m_Tabs [2/2]
Widget m_Tabs[TABS_COUNT] private
Definition at line 3070 of file ScriptConsole.c.
m_TabScript
protected TabberUI m_TabScript private
Definition at line 40 of file ControlsXboxNew.c.
m_TargetPresetIndex
protected int m_TargetPresetIndex private
Definition at line 19 of file KeybindingsMenu.c.
m_TeleportButton
ButtonWidget m_TeleportButton private
Definition at line 2954 of file ScriptConsole.c.
m_TeleportX
EditBoxWidget m_TeleportX private
Definition at line 2957 of file ScriptConsole.c.
m_TeleportXYZ
EditBoxWidget m_TeleportXYZ private
Definition at line 2959 of file ScriptConsole.c.
m_TeleportY
EditBoxWidget m_TeleportY private
Definition at line 2958 of file ScriptConsole.c.
m_TextPress
RichTextWidget m_TextPress private
Definition at line 4 of file TitleScreenMenu.c.
m_This
ScriptConsole m_This static private
Definition at line 7 of file ScriptConsole.c.
m_Time
protected float m_Time private
Definition at line 7 of file CameraToolsMenu.c.
m_TimeSlider
SliderWidget m_TimeSlider private
Definition at line 34 of file ScriptConsole.c.
m_title
protected TextWidget m_title private
Definition at line 4 of file BookMenu.c.
m_ToolbarPanel
protected Widget m_ToolbarPanel private
Definition at line 110 of file GesturesMenu.c.
m_ToolScaleCellSizeCanvasWidth
protected float m_ToolScaleCellSizeCanvasWidth private
Definition at line 12 of file MapMenu.c.
m_ToolsCompassArrow
protected ImageWidget m_ToolsCompassArrow private
Definition at line 24 of file MapMenu.c.
m_ToolsCompassAzimuth
protected TextWidget m_ToolsCompassAzimuth private
Definition at line 25 of file MapMenu.c.
m_ToolsCompassBase
protected Widget m_ToolsCompassBase private
Definition at line 23 of file MapMenu.c.
m_ToolsGPSElevationText
protected TextWidget m_ToolsGPSElevationText private
Definition at line 27 of file MapMenu.c.
m_ToolsGPSXText
protected TextWidget m_ToolsGPSXText private
Definition at line 28 of file MapMenu.c.
m_ToolsGPSYText
protected TextWidget m_ToolsGPSYText private
Definition at line 29 of file MapMenu.c.
m_ToolsScaleCellSizeCanvas
protected CanvasWidget m_ToolsScaleCellSizeCanvas private
Definition at line 31 of file MapMenu.c.
m_ToolsScaleCellSizeText
protected TextWidget m_ToolsScaleCellSizeText private
Definition at line 30 of file MapMenu.c.
m_ToolsScaleContourText
protected TextWidget m_ToolsScaleContourText private
Definition at line 26 of file MapMenu.c.
m_TopSelector
protected ref OptionSelectorMultistateCharacterMenu m_TopSelector private
Definition at line 28 of file CharacterCreationMenu.c.
m_TutorialButton
protected Widget m_TutorialButton private
Definition at line 19 of file MainMenu.c.
m_Tutorials
protected Widget m_Tutorials private
Definition at line 18 of file MainMenu.c.
Referenced by OnClick().
m_TutorialsButton
protected ButtonWidget m_TutorialsButton private
Definition at line 31 of file InGameMenuXbox.c.
m_txtDescription
protected TextWidget m_txtDescription private
Definition at line 154 of file DayZGame.c.
m_txtLabel
protected TextWidget m_txtLabel private
Definition at line 155 of file DayZGame.c.
m_txtNote
protected TextWidget m_txtNote private
Definition at line 38 of file DayZGame.c.
m_txtPosition
protected TextWidget m_txtPosition private
Definition at line 37 of file DayZGame.c.
m_Undo
protected ButtonWidget m_Undo private
Definition at line 12 of file KeybindingsMenu.c.
m_UnfavoriteImage
protected Widget m_UnfavoriteImage private
Definition at line 16 of file InGameMenu.c.
m_UnmuteButtonTextID
protected string m_UnmuteButtonTextID private
Definition at line 7 of file InGameMenuXbox.c.
Referenced by SetMuteButtonText().
m_UpButton
protected ButtonWidget m_UpButton private
Definition at line 1109 of file SceneEditorMenu.c.
m_UpdateMap
bool m_UpdateMap private
Definition at line 37 of file ScriptConsole.c.
m_UpperLegendContainer
protected Widget m_UpperLegendContainer private
Definition at line 22 of file MapMenu.c.
m_VariantWidget
protected Widget m_VariantWidget private
Definition at line 44 of file ControlsXboxNew.c.
Referenced by DrawConnectingLines().
m_Version
protected TextWidget m_Version private
Definition at line 33 of file InGameMenuXbox.c.
m_VicinityItems
ref array<Object> m_VicinityItems = new array<Object> private
Definition at line 26 of file ScriptConsole.c.
m_VicinityListbox
TextListboxWidget m_VicinityListbox private
Definition at line 3056 of file ScriptConsole.c.
m_Video [1/2]
protected ref MainMenuVideo m_Video private
Definition at line 4 of file MainMenu.c.
m_Video [2/2]
protected VideoWidget m_Video private
Definition at line 5 of file MainMenuVideo.c.
m_VideoFadeTimer
protected ref WidgetFadeTimer m_VideoFadeTimer private
Definition at line 7 of file MainMenuVideo.c.
m_VideoPlayTimer
protected ref Timer m_VideoPlayTimer private
Definition at line 6 of file MainMenuVideo.c.
m_VideoTab
protected ref OptionsMenuVideo m_VideoTab private
Definition at line 9 of file OptionsMenu.c.
m_ViewEvent
protected ButtonWidget m_ViewEvent private
Definition at line 54 of file CameraToolsMenu.c.
m_ViewKeyframe
protected ButtonWidget m_ViewKeyframe private
Definition at line 49 of file CameraToolsMenu.c.
m_WasChanged
protected bool m_WasChanged private
Definition at line 7 of file MapMenu.c.
m_WatchItem
ButtonWidget m_WatchItem private
Definition at line 3031 of file ScriptConsole.c.
m_WgtBtnDeleteRuler
protected ButtonWidget m_WgtBtnDeleteRuler private
Definition at line 1060 of file SceneEditorMenu.c.
m_WgtBtnEditInitScript
protected ButtonWidget m_WgtBtnEditInitScript private
Definition at line 1091 of file SceneEditorMenu.c.
m_WgtBtnEditorSettings
protected ButtonWidget m_WgtBtnEditorSettings private
Definition at line 1059 of file SceneEditorMenu.c.
m_WgtBtnLeftPresets
protected ButtonWidget m_WgtBtnLeftPresets private
Definition at line 1121 of file SceneEditorMenu.c.
m_WgtBtnPositionManager
protected ButtonWidget m_WgtBtnPositionManager private
Definition at line 1122 of file SceneEditorMenu.c.
m_WgtBtnSceneManager
protected ButtonWidget m_WgtBtnSceneManager private
Definition at line 1056 of file SceneEditorMenu.c.
m_WgtBtnSceneSave
protected ButtonWidget m_WgtBtnSceneSave private
Definition at line 1058 of file SceneEditorMenu.c.
m_WgtBtnSceneSettings
protected ButtonWidget m_WgtBtnSceneSettings private
Definition at line 1057 of file SceneEditorMenu.c.
m_WgtClassesConfig
Widget m_WgtClassesConfig private
Definition at line 27 of file ScriptConsole.c.
m_WgtPnlWrapper
protected Widget m_WgtPnlWrapper private
Definition at line 1120 of file SceneEditorMenu.c.
m_WgtPopupsBg
protected Widget m_WgtPopupsBg private
Definition at line 1064 of file SceneEditorMenu.c.
m_WgtPopupsMain
protected Widget m_WgtPopupsMain private
Definition at line 1063 of file SceneEditorMenu.c.
m_WgtRoot
protected Widget m_WgtRoot private
Definition at line 1049 of file SceneEditorMenu.c.
m_WrapperWidget
private WrapSpacerWidget m_WrapperWidget private
Definition at line 12 of file InputDeviceDisconnectWarningMenu.c.
MENU_FADEIN_TIME
protected float MENU_FADEIN_TIME = 2.0 static private
Definition at line 3 of file CreditsMenu.c.
Referenced by Init().
MODAL_ID_BACK
const int MODAL_ID_BACK = 1337 private
Definition at line 22 of file KeybindingsMenu.c.
MODAL_ID_DEFAULT
const int MODAL_ID_DEFAULT = 100 private
Definition at line 23 of file KeybindingsMenu.c.
MODAL_ID_DEFAULT_ALL
const int MODAL_ID_DEFAULT_ALL = 101 private
Definition at line 24 of file KeybindingsMenu.c.
MODAL_ID_PRESET_CHANGE
const int MODAL_ID_PRESET_CHANGE = 200 private
Definition at line 25 of file KeybindingsMenu.c.
MODAL_RESULT_DEFAULT_ALL
const int MODAL_RESULT_DEFAULT_ALL = 1 private
Definition at line 27 of file KeybindingsMenu.c.
Referenced by PerformSetToDefaultsExt().
MODAL_RESULT_DEFAULT_CURRENT
const int MODAL_RESULT_DEFAULT_CURRENT = 0 private
Definition at line 26 of file KeybindingsMenu.c.
Referenced by PerformSetToDefaultsExt().
PATH_MOUSEKEY
protected const string PATH_MOUSEKEY = "Scripts/data/PageDataTutorials.json" private
Definition at line 3 of file TutorialsMenu.c.
Referenced by GetControlMappingInfo().
PATH_PS_NEW
protected const string PATH_PS_NEW = "PS4/PageDataTutorialsAlternate.json" private
Definition at line 7 of file TutorialsMenu.c.
Referenced by GetControlMappingInfo().
PATH_PS_OLD
protected const string PATH_PS_OLD = "PS4/PageDataTutorials.json" private
Definition at line 6 of file TutorialsMenu.c.
Referenced by GetControlMappingInfo().
PATH_X1_NEW
protected const string PATH_X1_NEW = "Xbox/PageDataTutorialsAlternate.json" private
Definition at line 5 of file TutorialsMenu.c.
Referenced by GetControlMappingInfo().
PATH_X1_OLD
protected const string PATH_X1_OLD = "Xbox/PageDataTutorials.json" private
Definition at line 4 of file TutorialsMenu.c.
Referenced by GetControlMappingInfo().
PLATFORM_ADJUST_PS
protected const int PLATFORM_ADJUST_PS = 2000 private
Definition at line 53 of file ControlsXboxNew.c.
PLATFORM_ADJUST_X1
protected const int PLATFORM_ADJUST_X1 = 1000 private
Definition at line 52 of file ControlsXboxNew.c.
POPUP_ID_CONFIGS
const int POPUP_ID_CONFIGS = 11 static private
Definition at line 16 of file SceneEditorMenu.c.
POPUP_ID_EDITOR_SETTINGS
const int POPUP_ID_EDITOR_SETTINGS = 6 static private
Definition at line 11 of file SceneEditorMenu.c.
POPUP_ID_INIT_SCRIPT
const int POPUP_ID_INIT_SCRIPT = 7 static private
Definition at line 12 of file SceneEditorMenu.c.
POPUP_ID_NOTIFY
const int POPUP_ID_NOTIFY = 5 static private
Definition at line 10 of file SceneEditorMenu.c.
POPUP_ID_POSITION_MANAGER
const int POPUP_ID_POSITION_MANAGER = 8 static private
Definition at line 13 of file SceneEditorMenu.c.
POPUP_ID_PRESET_NEW
const int POPUP_ID_PRESET_NEW = 9 static private
Definition at line 14 of file SceneEditorMenu.c.
POPUP_ID_PRESET_RENAME
const int POPUP_ID_PRESET_RENAME = 10 static private
Definition at line 15 of file SceneEditorMenu.c.
POPUP_ID_SCENE_DELETE
const int POPUP_ID_SCENE_DELETE = 4 static private
Definition at line 9 of file SceneEditorMenu.c.
POPUP_ID_SCENE_MANAGER
const int POPUP_ID_SCENE_MANAGER = 0 static private
Definition at line 5 of file SceneEditorMenu.c.
POPUP_ID_SCENE_NEW
const int POPUP_ID_SCENE_NEW = 2 static private
Definition at line 7 of file SceneEditorMenu.c.
POPUP_ID_SCENE_RENAME
const int POPUP_ID_SCENE_RENAME = 3 static private
Definition at line 8 of file SceneEditorMenu.c.
POPUP_ID_SCENE_SETTINGS
const int POPUP_ID_SCENE_SETTINGS = 1 static private
Definition at line 6 of file SceneEditorMenu.c.
PRESETS_SELECTED_ROW
int PRESETS_SELECTED_ROW = 0 static private
Definition at line 17 of file ScriptConsole.c.
RADIAL_TEXT
const string RADIAL_TEXT = "RadialText" private
Definition at line 115 of file GesturesMenu.c.
SCALE_RULER_LINE_WIDTH
protected const int SCALE_RULER_LINE_WIDTH = 8 private
Definition at line 4 of file MapMenu.c.
SCALE_RULER_NUM_SEGMENTS
protected const int SCALE_RULER_NUM_SEGMENTS = 10 private
Definition at line 5 of file MapMenu.c.
Referenced by RenderScaleRuler().
SHOW_OTHERS
bool SHOW_OTHERS = 0 static private
Definition at line 20 of file ScriptConsole.c.
TAB_CONFIGS
const int TAB_CONFIGS = 2 static private
Definition at line 3061 of file ScriptConsole.c.
TAB_ENSCRIPT
const int TAB_ENSCRIPT = 3 static private
Definition at line 3062 of file ScriptConsole.c.
TAB_ENSCRIPT_SERVER
const int TAB_ENSCRIPT_SERVER = 4 static private
Definition at line 3063 of file ScriptConsole.c.
TAB_ITEMS
const int TAB_ITEMS = 1 static private
Definition at line 3060 of file ScriptConsole.c.
TABS_COUNT [1/2]
protected const int TABS_COUNT = 4 private
Definition at line 16 of file TutorialsMenu.c.
TABS_COUNT [2/2]
const int TABS_COUNT = 8 static private
Definition at line 3068 of file ScriptConsole.c.
TABS_GENERAL
const int TABS_GENERAL = 0 static private
Definition at line 3059 of file ScriptConsole.c.
TABS_OUTPUT
const int TABS_OUTPUT = 5 static private
Definition at line 3064 of file ScriptConsole.c.
TABS_SOUNDS
const int TABS_SOUNDS = 7 static private
Definition at line 3066 of file ScriptConsole.c.
TABS_VICINITY
const int TABS_VICINITY = 6 static private
Definition at line 3065 of file ScriptConsole.c.
TEXT_ITEM_NAME
const string TEXT_ITEM_NAME = "ItemName" private
Definition at line 97 of file RadialQuickbarMenu.c.
TEXT_ITEM_TITLE
const string TEXT_ITEM_TITLE = "ItemTitle" private
Definition at line 98 of file RadialQuickbarMenu.c.
TOOLTIP_ID_APPLY
const int TOOLTIP_ID_APPLY = 2 private
Definition at line 11 of file CharacterCreationMenu.c.
Referenced by OnFocus(), and OnMouseEnter().
TOOLTIP_ID_SAVE
const int TOOLTIP_ID_SAVE = 1 private
Definition at line 10 of file CharacterCreationMenu.c.
Referenced by OnFocus(), and OnMouseEnter().
The documentation for this class was generated from the following files:
3_Game/DayZGame.c
5_Mission/GUI/BookMenu.c
5_Mission/GUI/CameraTools/CameraToolsMenu.c
5_Mission/GUI/Chat/ChatInputMenu.c
5_Mission/GUI/ControlsXboxNew.c
5_Mission/GUI/GesturesMenu.c
5_Mission/GUI/HelpScreen.c
5_Mission/GUI/InGameMenu.c
5_Mission/GUI/InGameMenuXbox.c
5_Mission/GUI/InputDeviceDisconnectWarningMenu.c
5_Mission/GUI/InspectMenuNew.c
5_Mission/GUI/InviteMenu.c
5_Mission/GUI/LoadingMenu.c
5_Mission/GUI/LogoutMenu.c
5_Mission/GUI/MapMenu.c
5_Mission/GUI/NewUI/CharacterCreation/CharacterCreationMenu.c
5_Mission/GUI/NewUI/Credits/CreditsMenu.c
5_Mission/GUI/NewUI/Keybindings/KeybindingsMenu.c
5_Mission/GUI/NewUI/MainMenu/MainMenu.c
5_Mission/GUI/NewUI/MainMenu/MainMenuConsoles.c
5_Mission/GUI/NewUI/MainMenu/MainMenuVideo.c
5_Mission/GUI/NewUI/MainMenu/TutorialsMenu.c
5_Mission/GUI/NewUI/Options/OptionsMenu.c
5_Mission/GUI/NewUI/ServerBrowserMenu/ServerBrowserMenuNew.c
5_Mission/GUI/NoteMenu.c
5_Mission/GUI/PresetsMenu.c
5_Mission/GUI/RadialQuickbarMenu.c
5_Mission/GUI/RespawnDialogue.c
5_Mission/GUI/SceneEditorMenu.c
5_Mission/GUI/ScriptConsole.c
5_Mission/GUI/ScriptConsole/ScriptConsoleAddPosition.c
5_Mission/GUI/ScriptConsole/ScriptConsoleNewPresetDialog.c
5_Mission/GUI/ScriptConsole/ScriptConsoleRenamePresetDialog.c
5_Mission/GUI/StartupMenu.c
5_Mission/GUI/TitleScreenMenu.c
5_Mission/GUI/EarlyAccessMenu.c
5_Mission/GUI/ItemDropWarningMenu.c