DayZ: PlayerSoundEventBase Class Reference
PlayerSoundEventBase Class Reference
Private Member Functions
void DamageSoundEvents ()
override bool CanPlay (PlayerBase player)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
void DrowningEvents ()
override bool CanPlay (PlayerBase player)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
void HeatComfortEventsBase ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
void HoldBreathSoundEventBase ()
override bool HasHoldBreathException ()
void InjurySoundEvents ()
override bool CanPlay (PlayerBase player)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool CanPlay (PlayerBase player)
override void OnPlay (PlayerBase player)
override void OnEnd ()
void MeleeAttackSoundEvents ()
override bool CanPlay (PlayerBase player)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override void OnEnd ()
void PickupHeavySoundEvent ()
void StaminaSoundEventBase ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override void OnPlay (PlayerBase player)
void SymptomSoundEventBase ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Private Attributes
const int MAX_VOLUME = 4
Detailed Description
Definition at line 1 of file DamageEvents.c.
Member Function Documentation
CanPlay() [1/5]
override bool CanPlay (PlayerBase player) inline private
Definition at line 10 of file DamageEvents.c.
Referenced by PlayRequestEx().
CanPlay() [2/5]
override bool CanPlay (PlayerBase player) inline private
Definition at line 9 of file DrowningEvents.c.
CanPlay() [3/5]
override bool CanPlay (PlayerBase player) inline private
Definition at line 10 of file InjuryEvents.c.
CanPlay() [4/5]
override bool CanPlay (PlayerBase player) inline private
Definition at line 8 of file JumpEvents.c.
CanPlay() [5/5]
override bool CanPlay (PlayerBase player) inline private
Definition at line 9 of file MeleeAttack.c.
DamageSoundEvents()
void DamageSoundEvents () inline private
Definition at line 4 of file DamageEvents.c.
References m_HasPriorityOverTypes, and m_Type.
DrowningEvents()
void DrowningEvents () inline private
Definition at line 3 of file DrowningEvents.c.
References m_HasPriorityOverTypes, and m_Type.
HasHoldBreathException()
override bool HasHoldBreathException () inline private
Definition at line 8 of file HoldBreathEvents.c.
Referenced by CanPlay().
HasPriorityOverCurrent() [1/8]
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 15 of file DamageEvents.c.
Referenced by PlayRequestEx().
HasPriorityOverCurrent() [2/8]
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 14 of file DrowningEvents.c.
HasPriorityOverCurrent() [3/8]
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 10 of file HeatComfortEvents.c.
HasPriorityOverCurrent() [4/8]
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 15 of file InjuryEvents.c.
HasPriorityOverCurrent() [5/8]
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 3 of file JumpEvents.c.
HasPriorityOverCurrent() [6/8]
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 14 of file MeleeAttack.c.
HasPriorityOverCurrent() [7/8]
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 10 of file StaminaEvents.c.
HasPriorityOverCurrent() [8/8]
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 9 of file SymptomEvents.c.
HeatComfortEventsBase()
void HeatComfortEventsBase () inline private
Definition at line 4 of file HeatComfortEvents.c.
References m_HasPriorityOverTypes, and m_Type.
HoldBreathSoundEventBase()
void HoldBreathSoundEventBase () inline private
Definition at line 3 of file HoldBreathEvents.c.
References m_HasPriorityOverTypes.
InjurySoundEvents()
void InjurySoundEvents () inline private
Definition at line 4 of file InjuryEvents.c.
References m_HasPriorityOverTypes, and m_Type.
MeleeAttackSoundEvents()
void MeleeAttackSoundEvents () inline private
Definition at line 3 of file MeleeAttack.c.
References m_HasPriorityOverTypes, and m_Type.
OnEnd() [1/2]
override void OnEnd () inline private
Definition at line 24 of file JumpEvents.c.
References m_Player.
Referenced by Play(), and ~PlayerSoundEventBase().
OnEnd() [2/2]
override void OnEnd () inline private
Definition at line 23 of file MeleeAttack.c.
References m_Player.
OnPlay() [1/2]
override void OnPlay (PlayerBase player) inline private
Definition at line 17 of file JumpEvents.c.
OnPlay() [2/2]
override void OnPlay (PlayerBase player) inline private
!! beware of the ifdef above , most likely you want to put your code above it, otherwise it might not get executed !!!
Definition at line 15 of file StaminaEvents.c.
References DiagMenu::GetBool(), InventorySlots::GetSlotIdFromString(), Math::Lerp(), m_SoundSetCallback, MAX_VOLUME, and AbstractWave::SetVolumeRelative().
PickupHeavySoundEvent()
void PickupHeavySoundEvent () inline private
Definition at line 3 of file MiscEvents.c.
References m_HasPriorityOverTypes, m_ID, m_SoundVoiceAnimEventClassID, and m_Type.
StaminaSoundEventBase()
void StaminaSoundEventBase () inline private
Definition at line 4 of file StaminaEvents.c.
References m_HasPriorityOverTypes, and m_Type.
SymptomSoundEventBase()
void SymptomSoundEventBase () inline private
Definition at line 3 of file SymptomEvents.c.
References m_HasPriorityOverTypes, and m_Type.
Field Documentation
MAX_VOLUME
const int MAX_VOLUME = 4 private
Definition at line 3 of file StaminaEvents.c.
The documentation for this class was generated from the following files:
4_World/Classes/SoundEvents/PlayerSoundEvents/Events/DamageEvents.c
4_World/Classes/SoundEvents/PlayerSoundEvents/Events/StaminaEvents.c
4_World/Classes/SoundEvents/PlayerSoundEvents/Events/DrowningEvents.c
4_World/Classes/SoundEvents/PlayerSoundEvents/Events/HeatComfortEvents.c
4_World/Classes/SoundEvents/PlayerSoundEvents/Events/HoldBreathEvents.c
4_World/Classes/SoundEvents/PlayerSoundEvents/Events/InjuryEvents.c
4_World/Classes/SoundEvents/PlayerSoundEvents/Events/JumpEvents.c
4_World/Classes/SoundEvents/PlayerSoundEvents/Events/MeleeAttack.c
4_World/Classes/SoundEvents/PlayerSoundEvents/Events/MiscEvents.c
4_World/Classes/SoundEvents/PlayerSoundEvents/Events/SymptomEvents.c