DayZ Scripts Documentation: ActionPackGift Class Reference
ActionPackGift Class Reference
Private Member Functions
void ActionPackGift ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file ActionPackGift.c.
Constructor & Destructor Documentation
ActionPackGift()
void ActionPackGift () inline private
Definition at line 11 of file ActionPackGift.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file ActionPackGift.c.
References ItemBase::CanDetachAttachment(), ItemBase::CanPutInCargo(), ItemBase::CanRemoveFromCargo(), GetGame(), CGame::GetInventoryItemSize(), ItemBase::IsTakeable(), x, and y.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 21 of file ActionPackGift.c.
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool HasTarget () inline private
Definition at line 27 of file ActionPackGift.c.
OnFinishProgressClient()
override void OnFinishProgressClient (ActionData action_data) inline private
Definition at line 77 of file ActionPackGift.c.
References ActionData::m_Player, and ActionData::m_Target.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 86 of file ActionPackGift.c.
References GetGame(), CGame::GetInventoryItemSize(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, Math::RandomIntInclusive(), x, and y.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionPackGift.c