DayZ Scripts: VicinityItemManager Class Reference
VicinityItemManager Class Reference
Private Member Functions
void Init ()
array< EntityAI > GetVicinityItems ()
void AddVicinityItems (Object object)
array< CargoBase > GetVicinityCargos ()
void AddVicinityCargos (CargoBase object)
void ResetRefreshCounter ()
void Update (float delta_time)
bool ExcludeFromContainer_Phase1 (Object actor_in_radius)
bool ExcludeFromContainer_Phase2 (Object object_in_radius)
bool ExcludeFromContainer_Phase3 (Object object_in_cone)
bool CanIgnoreDistanceCheck (EntityAI entity_ai)
void RefreshVicinityItems ()
bool IsObstructed (Object filtered_object)
Static Private Member Functions
static VicinityItemManager GetInstance ()
Private Attributes
private const float UPDATE_FREQUENCY = 0.25
private const float VICINITY_DISTANCE = 0.5
private const float VICINITY_ACTOR_DISTANCE = 2.0
private const float VICINITY_LARGE_ACTOR_DISTANCE = 3.0
private const float VICINITY_CONE_DISTANCE = 2.0
private const float VICINITY_CONE_REACH_DISTANCE = 2.0
private const float VICINITY_CONE_ANGLE = 30
private const float VICINITY_CONE_RADIANS = 0.5
private const string CE_CENTER = "ce_center"
private const float HEIGHT_OFFSET = 0.2
private const int OBJECT_OBSTRUCTION_WEIGHT = 10000
private const float CONE_HEIGHT_MIN = -0.5
private const float CONE_HEIGHT_MAX = 3.0
private ref array< EntityAI > m_VicinityItems = new array<EntityAI>()
private ref array< CargoBase > m_VicinityCargos = new array<CargoBase>()
private float m_RefreshCounter
Static Private Attributes
static private ref VicinityItemManager s_Instance
Detailed Description
Definition at line 1 of file VicinityItemManager.c.
Member Function Documentation
AddVicinityCargos()
void AddVicinityCargos (CargoBase object) inline private
Definition at line 56 of file VicinityItemManager.c.
References INDEX_NOT_FOUND, and m_VicinityCargos.
Referenced by RefreshVicinityItems().
AddVicinityItems()
void AddVicinityItems (Object object) inline private
Definition at line 39 of file VicinityItemManager.c.
References GameInventory::CheckManipulatedObjectsDistances(), GetGame(), GetPlayer(), INDEX_NOT_FOUND, m_VicinityItems, and VICINITY_CONE_REACH_DISTANCE.
Referenced by RefreshVicinityItems().
CanIgnoreDistanceCheck()
bool CanIgnoreDistanceCheck (EntityAI entity_ai) inline private
Definition at line 189 of file VicinityItemManager.c.
Referenced by RefreshVicinityItems().
ExcludeFromContainer_Phase1()
bool ExcludeFromContainer_Phase1 (Object actor_in_radius) inline private
Definition at line 80 of file VicinityItemManager.c.
References Class::CastTo(), vector::Dot(), GetGame(), GetPlayer(), EntityAI::IsMan(), and vector::Normalize().
Referenced by RefreshVicinityItems().
ExcludeFromContainer_Phase2()
bool ExcludeFromContainer_Phase2 (Object object_in_radius) inline private
Definition at line 135 of file VicinityItemManager.c.
References Class::CastTo(), GetGame(), GetPlayer(), and ItemBase::IsTakeable().
Referenced by RefreshVicinityItems().
ExcludeFromContainer_Phase3()
bool ExcludeFromContainer_Phase3 (Object object_in_cone) inline private
Definition at line 161 of file VicinityItemManager.c.
References Class::CastTo(), GetGame(), GetPlayer(), and ItemBase::IsTakeable().
Referenced by RefreshVicinityItems().
GetInstance()
static VicinityItemManager GetInstance () inline static private
Definition at line 22 of file VicinityItemManager.c.
References s_Instance.
Referenced by MissionBase::HideInventory(), OnShow(), and VicinityContainer::UpdateInterval().
GetVicinityCargos()
array< CargoBase > GetVicinityCargos () inline private
Definition at line 51 of file VicinityItemManager.c.
References m_VicinityCargos.
Referenced by VicinityContainer::UpdateInterval().
GetVicinityItems()
array< EntityAI > GetVicinityItems () inline private
Definition at line 34 of file VicinityItemManager.c.
References m_VicinityItems.
Referenced by VicinityContainer::UpdateInterval().
Init()
void Init () inline private
Definition at line 30 of file VicinityItemManager.c.
IsObstructed()
bool IsObstructed (Object filtered_object) inline private
Definition at line 393 of file VicinityItemManager.c.
Referenced by RefreshVicinityItems().
RefreshVicinityItems()
void RefreshVicinityItems () inline private
Definition at line 195 of file VicinityItemManager.c.
References AddVicinityCargos(), AddVicinityItems(), CanIgnoreDistanceCheck(), Class::CastTo(), CONE_HEIGHT_MAX, CONE_HEIGHT_MIN, vector::DistanceSq(), ExcludeFromContainer_Phase1(), ExcludeFromContainer_Phase2(), ExcludeFromContainer_Phase3(), DayZPlayerUtils::GetEntitiesInCone(), GetGame(), CGame::GetObjectsAtPosition3D(), GetPlayer(), INDEX_NOT_FOUND, IsObstructed(), m_VicinityCargos, m_VicinityItems, DayZPhysics::RaycastRVProxy(), BoxCollidingParams::SetParams(), vector::VectorToAngles(), VICINITY_ACTOR_DISTANCE, VICINITY_CONE_ANGLE, VICINITY_CONE_DISTANCE, VICINITY_CONE_REACH_DISTANCE, VICINITY_DISTANCE, and VICINITY_LARGE_ACTOR_DISTANCE.
Referenced by OnShow(), and Update().
ResetRefreshCounter()
void ResetRefreshCounter () inline private
Definition at line 64 of file VicinityItemManager.c.
References m_RefreshCounter.
Referenced by MissionBase::HideInventory().
Update()
void Update (float delta_time) inline private
Definition at line 69 of file VicinityItemManager.c.
References m_RefreshCounter, RefreshVicinityItems(), and UPDATE_FREQUENCY.
Referenced by VicinityContainer::UpdateInterval().
Field Documentation
CE_CENTER
private const string CE_CENTER = "ce_center" private
Definition at line 11 of file VicinityItemManager.c.
CONE_HEIGHT_MAX
private const float CONE_HEIGHT_MAX = 3.0 private
Definition at line 15 of file VicinityItemManager.c.
Referenced by RefreshVicinityItems().
CONE_HEIGHT_MIN
private const float CONE_HEIGHT_MIN = -0.5 private
Definition at line 14 of file VicinityItemManager.c.
Referenced by RefreshVicinityItems().
HEIGHT_OFFSET
private const float HEIGHT_OFFSET = 0.2 private
Definition at line 12 of file VicinityItemManager.c.
m_RefreshCounter
private float m_RefreshCounter private
Definition at line 19 of file VicinityItemManager.c.
Referenced by ResetRefreshCounter(), and Update().
m_VicinityCargos
private ref array<CargoBase> m_VicinityCargos = new array<CargoBase>() private
Definition at line 18 of file VicinityItemManager.c.
Referenced by AddVicinityCargos(), GetVicinityCargos(), and RefreshVicinityItems().
m_VicinityItems
private ref array<EntityAI> m_VicinityItems = new array<EntityAI>() private
Definition at line 17 of file VicinityItemManager.c.
Referenced by AddVicinityItems(), GetVicinityItems(), and RefreshVicinityItems().
OBJECT_OBSTRUCTION_WEIGHT
private const int OBJECT_OBSTRUCTION_WEIGHT = 10000 private
Definition at line 13 of file VicinityItemManager.c.
s_Instance
private ref VicinityItemManager s_Instance static private
Definition at line 20 of file VicinityItemManager.c.
Referenced by GetInstance().
UPDATE_FREQUENCY
private const float UPDATE_FREQUENCY = 0.25 private
Definition at line 3 of file VicinityItemManager.c.
Referenced by Update().
VICINITY_ACTOR_DISTANCE
private const float VICINITY_ACTOR_DISTANCE = 2.0 private
Definition at line 5 of file VicinityItemManager.c.
Referenced by RefreshVicinityItems().
VICINITY_CONE_ANGLE
private const float VICINITY_CONE_ANGLE = 30 private
Definition at line 9 of file VicinityItemManager.c.
Referenced by RefreshVicinityItems().
VICINITY_CONE_DISTANCE
private const float VICINITY_CONE_DISTANCE = 2.0 private
Definition at line 7 of file VicinityItemManager.c.
Referenced by RefreshVicinityItems().
VICINITY_CONE_RADIANS
private const float VICINITY_CONE_RADIANS = 0.5 private
Definition at line 10 of file VicinityItemManager.c.
VICINITY_CONE_REACH_DISTANCE
private const float VICINITY_CONE_REACH_DISTANCE = 2.0 private
Definition at line 8 of file VicinityItemManager.c.
Referenced by AddVicinityItems(), and RefreshVicinityItems().
VICINITY_DISTANCE
private const float VICINITY_DISTANCE = 0.5 private
Definition at line 4 of file VicinityItemManager.c.
Referenced by RefreshVicinityItems().
VICINITY_LARGE_ACTOR_DISTANCE
private const float VICINITY_LARGE_ACTOR_DISTANCE = 3.0 private
Definition at line 6 of file VicinityItemManager.c.
Referenced by RefreshVicinityItems().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/VicinityItemManager.c