DayZ: PPEffects Class Reference
PPEffects Class Reference
Deprecated; 'PPEManager' used instead.
Static Private Member Functions
static void Init ()
static void ResetBlurEffects ()
static void ResetRadialBlur ()
static void SetBlurValue (int index, float value)
static int RegisterBlurEffect ()
static void SetRadialBlur (float powerX, float powerY, float offsetX, float offsetY)
sets blur effect to an absolute value between 0..1
static void SetBlur (float value)
sets blur effect to an absolute value between 0..1
static void UpdateBlur ()
updates the blur post process effect where the resulting blur is an aggregate of all individual blur effect values
static void SetBlurInventory (float value)
Set blur inventory effect to a specified 'value' between 0..1.
static void SetBlurDrunk (float value)
Set blur drunk effect to a specified 'value' between 0..1.
static void SetBlurFever (float value)
Set blur drunk effect to a specified 'value' between 0..1.
static void SetBlurMenu (float value)
Set menu blur to a specified 'value' between 0..1.
static void SetBlurOptics (float value)
Set optics and ironsights blur to a specified 'value' between 0..1.
static void SetBlurFlashbang (float value)
Set blur flashbang hit effect to a specified 'value' between 0..1.
static void SetBlurShock (float value)
static int RegisterChromAbbEffect ()
static void ResetChromAbbEffects ()
static void SetChromAbbValue (int index, float value)
static void SetChromAbb (float value)
static void UpdateChromAbb ()
updates the chromatic abberation post process effect where the resulting chromabb is an aggregate of all individual chromabb effect values
static void SetChromAbbOptic (float value)
static void ResetColorEffects ()
static void SetColorValue (int index, float r, float g, float b, float a, float overlay)
static int RegisterColorEffect ()
static void UpdateColor ()
static void SetLensEffect (float lens, float chromAbb, float centerX, float centerY)
static void PerformSetLensEffect (float lens, float chromAbb, float centerX, float centerY)
added for convenience
static void SetVignette (float intensity, float R, float G, float B, float A)
static void SetVignetteEffectValue (int index, float intensity, float r, float g, float b, float a)
static int RegisterVignetteEffect ()
static void SetUnconsciousnessVignette (float value)
static void SetShockVignette (float value)
static void SetTunnelVignette (float value)
static void SetMenuVignette (float value)
static void ResetVignettes ()
static void OverrideDOF (bool enable, float focusDistance, float focusLength, float focusLengthNear, float blur, float focusDepthOffset)
static void AddPPMask (float ndcX, float ndcY, float ndcRadius, float ndcBlur)
static void ResetPPMask ()
static void ResetDOFOverride ()
static void ResetLensEffect ()
static void HitEffect (float value)
static void SetShockEffectColor (float value)
static void FlashbangEffect (float value)
static void EnableBurlapSackBlindness ()
static void DisableBurlapSackBlindness ()
static void SetDeathDarkening (float value)
static void UpdateSaturation ()
static void UpdateVignette ()
static void SetBloodSaturation (float value)
static void SetColorizationNV (float r, float g, float b)
static void UpdateColorize ()
static void ResetColorize ()
static void SetEVValuePP (float value)
static void SetNVParams (float light_mult, float noise_intensity, float sharpness, float grain_size)
static void SetBloom (float thres, float steep, float inten)
static void ResetAll ()
Static Private Attributes
static const int COLORIZE_NV = 100
static const float COLOR_SHOCK = 0.1
static int m_BlurInventory
static int m_BlurDrunk
static int m_BlurFever
static int m_BlurMenu
static int m_BlurOptics
static int m_BlurFlashbang
static int m_BlurShock
static int m_BurlapBlindness
static int m_DyingEffect
static int m_ShockEffect
static int m_ChromAbbOptic
static int m_VignetteUnconscious
static int m_VignetteShock
static int m_VignetteTunnel
static int m_VignetteMenu
static float m_BloodSaturation
static ref array< float > m_BlurValues
static ref array< float > m_ChromAbbValues
static ref array< int > m_VignetteEffects
static ref map< int, ref array< float > > m_VignetteValues
static ref map< int, ref array< float > > m_ColorValues
static ref array< float > m_ColorEffect
static ref map< int, ref array< float > > m_ColorizeEffects
static float m_ColorValueTotal [4] = {0,0,0,0}
static float m_ColorOverlayTotal
static Material m_MatColors
static Material m_RadialBlur
Detailed Description
Deprecated; 'PPEManager' used instead.
Definition at line 2 of file PPEffects.c.
Member Function Documentation
AddPPMask()
static void AddPPMask (float ndcX, float ndcY, float ndcRadius, float ndcBlur) inline static private
Definition at line 508 of file PPEffects.c.
References CGame::AddPPMask(), and GetGame().
DisableBurlapSackBlindness()
static void DisableBurlapSackBlindness () inline static private
Definition at line 577 of file PPEffects.c.
References g_Game, m_BurlapBlindness, SetColorValue(), and UpdateColor().
EnableBurlapSackBlindness()
static void EnableBurlapSackBlindness () inline static private
Definition at line 570 of file PPEffects.c.
References g_Game, m_BurlapBlindness, SetColorValue(), and UpdateColor().
FlashbangEffect()
static void FlashbangEffect (float value) inline static private
Definition at line 558 of file PPEffects.c.
References Math::Clamp(), Math::Lerp(), m_ColorValueTotal, m_MatColors, and Material::SetParam().
HitEffect()
static void HitEffect (float value) inline static private
Definition at line 528 of file PPEffects.c.
References Math::Clamp(), Math::Lerp(), m_ColorValueTotal, m_MatColors, and Material::SetParam().
Init()
static void Init () inline static private
Definition at line 52 of file PPEffects.c.
References COLORIZE_NV, GetGame(), World::GetMaterial(), CGame::GetWorld(), m_BlurDrunk, m_BlurFever, m_BlurFlashbang, m_BlurInventory, m_BlurMenu, m_BlurOptics, m_BlurValues, m_BurlapBlindness, m_ChromAbbOptic, m_ChromAbbValues, m_ColorEffect, m_ColorizeEffects, m_ColorValues, m_DyingEffect, m_MatColors, m_RadialBlur, m_ShockEffect, m_VignetteEffects, m_VignetteMenu, m_VignetteShock, m_VignetteTunnel, m_VignetteUnconscious, m_VignetteValues, RegisterBlurEffect(), RegisterChromAbbEffect(), RegisterColorEffect(), and RegisterVignetteEffect().
Referenced by DayZIntroScene::DayZIntroScene(), DayZIntroSceneXbox::DayZIntroSceneXbox(), and MissionBase::OnInit().
OverrideDOF()
static void OverrideDOF (bool enable, float focusDistance, float focusLength, float focusLengthNear, float blur, float focusDepthOffset) inline static private
Definition at line 503 of file PPEffects.c.
References GetGame(), and CGame::OverrideDOF().
Referenced by ResetDOFOverride().
PerformSetLensEffect()
static void PerformSetLensEffect (float lens, float chromAbb, float centerX, float centerY) inline static private
added for convenience
Definition at line 419 of file PPEffects.c.
References m_MatColors, SetChromAbbOptic(), and Material::SetParam().
Referenced by SetLensEffect().
RegisterBlurEffect()
static int RegisterBlurEffect () inline static private
Definition at line 149 of file PPEffects.c.
References m_BlurValues.
Referenced by Init().
RegisterChromAbbEffect()
static int RegisterChromAbbEffect () inline static private
Definition at line 255 of file PPEffects.c.
References m_ChromAbbValues.
Referenced by Init().
RegisterColorEffect()
static int RegisterColorEffect () inline static private
Definition at line 370 of file PPEffects.c.
References m_ColorEffect.
Referenced by Init().
RegisterVignetteEffect()
static int RegisterVignetteEffect () inline static private
Definition at line 460 of file PPEffects.c.
References m_VignetteEffects.
Referenced by Init().
ResetAll()
static void ResetAll () inline static private
Definition at line 744 of file PPEffects.c.
References ResetBlurEffects(), ResetColorEffects(), ResetColorize(), ResetDOFOverride(), ResetLensEffect(), ResetPPMask(), ResetVignettes(), and SetBloodSaturation().
ResetBlurEffects()
static void ResetBlurEffects () inline static private
Definition at line 120 of file PPEffects.c.
References m_BlurValues, and UpdateBlur().
Referenced by ResetAll().
ResetChromAbbEffects()
static void ResetChromAbbEffects () inline static private
Definition at line 260 of file PPEffects.c.
References m_ChromAbbValues, and UpdateChromAbb().
ResetColorEffects()
static void ResetColorEffects () inline static private
Definition at line 343 of file PPEffects.c.
References m_ColorEffect, m_ColorValues, and UpdateColor().
Referenced by ResetAll().
ResetColorize()
static void ResetColorize () inline static private
Definition at line 706 of file PPEffects.c.
References m_MatColors, and Material::SetParam().
Referenced by ResetAll(), and UpdateColorize().
ResetDOFOverride()
static void ResetDOFOverride () inline static private
Definition at line 518 of file PPEffects.c.
References OverrideDOF().
Referenced by ResetAll().
ResetLensEffect()
static void ResetLensEffect () inline static private
Definition at line 523 of file PPEffects.c.
References SetLensEffect().
Referenced by ResetAll().
ResetPPMask()
static void ResetPPMask () inline static private
Definition at line 513 of file PPEffects.c.
References GetGame(), and CGame::ResetPPMask().
Referenced by ResetAll().
ResetRadialBlur()
static void ResetRadialBlur () inline static private
Definition at line 132 of file PPEffects.c.
References SetRadialBlur().
ResetVignettes()
static void ResetVignettes () inline static private
Definition at line 489 of file PPEffects.c.
References m_VignetteValues, and UpdateVignette().
Referenced by ResetAll().
SetBloodSaturation()
static void SetBloodSaturation (float value) inline static private
Definition at line 640 of file PPEffects.c.
References m_BloodSaturation, and UpdateSaturation().
Referenced by ResetAll().
SetBloom()
static void SetBloom (float thres, float steep, float inten) inline static private
Definition at line 737 of file PPEffects.c.
References m_MatColors, and Material::SetParam().
SetBlur()
static void SetBlur (float value) inline static private
sets blur effect to an absolute value between 0..1
Definition at line 168 of file PPEffects.c.
References GetGame(), World::GetMaterial(), CGame::GetWorld(), and Material::SetParam().
Referenced by UpdateBlur().
SetBlurDrunk()
static void SetBlurDrunk (float value) inline static private
Set blur drunk effect to a specified 'value' between 0..1.
Definition at line 204 of file PPEffects.c.
References m_BlurDrunk, SetBlurValue(), and UpdateBlur().
SetBlurFever()
static void SetBlurFever (float value) inline static private
Set blur drunk effect to a specified 'value' between 0..1.
Definition at line 212 of file PPEffects.c.
References m_BlurFever, SetBlurValue(), and UpdateBlur().
SetBlurFlashbang()
static void SetBlurFlashbang (float value) inline static private
Set blur flashbang hit effect to a specified 'value' between 0..1.
Definition at line 236 of file PPEffects.c.
References m_BlurFlashbang, SetBlurValue(), and UpdateBlur().
SetBlurInventory()
static void SetBlurInventory (float value) inline static private
Set blur inventory effect to a specified 'value' between 0..1.
Definition at line 197 of file PPEffects.c.
References m_BlurInventory, SetBlurValue(), and UpdateBlur().
SetBlurMenu()
static void SetBlurMenu (float value) inline static private
Set menu blur to a specified 'value' between 0..1.
Definition at line 220 of file PPEffects.c.
References m_BlurMenu, SetBlurValue(), and UpdateBlur().
SetBlurOptics()
static void SetBlurOptics (float value) inline static private
Set optics and ironsights blur to a specified 'value' between 0..1.
Definition at line 228 of file PPEffects.c.
References m_BlurOptics, SetBlurValue(), and UpdateBlur().
SetBlurShock()
static void SetBlurShock (float value) inline static private
Definition at line 242 of file PPEffects.c.
References m_BlurShock, SetBlurValue(), and UpdateBlur().
SetBlurValue()
static void SetBlurValue (int index, float value) inline static private
Definition at line 137 of file PPEffects.c.
References m_BlurValues, and Print().
Referenced by SetBlurDrunk(), SetBlurFever(), SetBlurFlashbang(), SetBlurInventory(), SetBlurMenu(), SetBlurOptics(), and SetBlurShock().
SetChromAbb()
static void SetChromAbb (float value) inline static private
Definition at line 284 of file PPEffects.c.
References GetGame(), m_MatColors, and Material::SetParam().
Referenced by UpdateChromAbb().
SetChromAbbOptic()
static void SetChromAbbOptic (float value) inline static private
Definition at line 312 of file PPEffects.c.
References m_ChromAbbOptic, SetChromAbbValue(), and UpdateChromAbb().
Referenced by PerformSetLensEffect().
SetChromAbbValue()
static void SetChromAbbValue (int index, float value) inline static private
Definition at line 272 of file PPEffects.c.
References m_ChromAbbValues, and Print().
Referenced by SetChromAbbOptic().
SetColorizationNV()
static void SetColorizationNV (float r, float g, float b) inline static private
Definition at line 659 of file PPEffects.c.
References COLORIZE_NV, m_ColorizeEffects, and UpdateColorize().
SetColorValue()
static void SetColorValue (int index, float r, float g, float b, float a, float overlay) inline static private
Definition at line 356 of file PPEffects.c.
References m_ColorEffect, m_ColorValues, and Print().
Referenced by DisableBurlapSackBlindness(), EnableBurlapSackBlindness(), SetDeathDarkening(), and SetShockEffectColor().
SetDeathDarkening()
static void SetDeathDarkening (float value) inline static private
Definition at line 584 of file PPEffects.c.
References Math::Clamp(), m_DyingEffect, SetColorValue(), SetEVValuePP(), and UpdateColor().
SetEVValuePP()
static void SetEVValuePP (float value) inline static private
Definition at line 717 of file PPEffects.c.
References g_Game.
Referenced by SetDeathDarkening().
SetLensEffect()
static void SetLensEffect (float lens, float chromAbb, float centerX, float centerY) inline static private
set lens effect
Parameters
lens <-5, 5>, 0 = disable (performance plus), > 0 = outside effect, < 0 inside effect
chromAbb <0, 1>, chromaticity, 1 = max, 0 disable (performance plus)
centerX <-1, 1>, center of effect, 0 = screen center in X
centerY <-1, 1>, center of effect, 0 = screen center in Y
Definition at line 413 of file PPEffects.c.
References PerformSetLensEffect().
Referenced by ResetLensEffect().
SetMenuVignette()
static void SetMenuVignette (float value) inline static private
Definition at line 483 of file PPEffects.c.
References m_VignetteMenu, SetVignetteEffectValue(), and UpdateVignette().
SetNVParams()
static void SetNVParams (float light_mult, float noise_intensity, float sharpness, float grain_size) inline static private
Definition at line 724 of file PPEffects.c.
References g_Game, GetGame(), World::GetMaterial(), CGame::GetWorld(), and Material::SetParam().
SetRadialBlur()
static void SetRadialBlur (float powerX, float powerY, float offsetX, float offsetY) inline static private
sets blur effect to an absolute value between 0..1
Definition at line 156 of file PPEffects.c.
References GetGame(), m_RadialBlur, and Material::SetParam().
Referenced by ResetRadialBlur().
SetShockEffectColor()
static void SetShockEffectColor (float value) inline static private
Definition at line 549 of file PPEffects.c.
References COLOR_SHOCK, m_ShockEffect, SetColorValue(), and UpdateColor().
SetShockVignette()
static void SetShockVignette (float value) inline static private
Definition at line 471 of file PPEffects.c.
References m_VignetteShock, SetVignetteEffectValue(), and UpdateVignette().
SetTunnelVignette()
static void SetTunnelVignette (float value) inline static private
Definition at line 477 of file PPEffects.c.
References m_VignetteTunnel, SetVignetteEffectValue(), and UpdateVignette().
SetUnconsciousnessVignette()
static void SetUnconsciousnessVignette (float value) inline static private
Definition at line 465 of file PPEffects.c.
References m_VignetteUnconscious, SetVignetteEffectValue(), and UpdateVignette().
SetVignette()
static void SetVignette (float intensity, float R, float G, float B, float A) inline static private
set vignette
Parameters
intensity <0, 1>, intensity of effect, 0 = disable
R
G
B
Definition at line 434 of file PPEffects.c.
References A, B, m_MatColors, R, and Material::SetParam().
Referenced by UpdateVignette().
SetVignetteEffectValue()
static void SetVignetteEffectValue (int index, float intensity, float r, float g, float b, float a) inline static private
Definition at line 446 of file PPEffects.c.
References m_VignetteEffects, m_VignetteValues, and Print().
Referenced by SetMenuVignette(), SetShockVignette(), SetTunnelVignette(), and SetUnconsciousnessVignette().
UpdateBlur()
static void UpdateBlur () inline static private
updates the blur post process effect where the resulting blur is an aggregate of all individual blur effect values
Definition at line 182 of file PPEffects.c.
References m_BlurValues, and SetBlur().
Referenced by ResetBlurEffects(), SetBlurDrunk(), SetBlurFever(), SetBlurFlashbang(), SetBlurInventory(), SetBlurMenu(), SetBlurOptics(), and SetBlurShock().
UpdateChromAbb()
static void UpdateChromAbb () inline static private
updates the chromatic abberation post process effect where the resulting chromabb is an aggregate of all individual chromabb effect values
Definition at line 298 of file PPEffects.c.
References m_ChromAbbValues, and SetChromAbb().
Referenced by ResetChromAbbEffects(), and SetChromAbbOptic().
UpdateColor()
static void UpdateColor () inline static private
Definition at line 375 of file PPEffects.c.
References GetGame(), m_ColorOverlayTotal, m_ColorValues, m_ColorValueTotal, m_MatColors, and Material::SetParam().
Referenced by DisableBurlapSackBlindness(), EnableBurlapSackBlindness(), ResetColorEffects(), SetDeathDarkening(), and SetShockEffectColor().
UpdateColorize()
static void UpdateColorize () inline static private
Definition at line 666 of file PPEffects.c.
References m_ColorizeEffects, m_MatColors, ResetColorize(), and Material::SetParam().
Referenced by SetColorizationNV().
UpdateSaturation()
static void UpdateSaturation () inline static private
Definition at line 595 of file PPEffects.c.
References m_BloodSaturation, m_MatColors, and Material::SetParam().
Referenced by SetBloodSaturation().
UpdateVignette()
static void UpdateVignette () inline static private
Definition at line 600 of file PPEffects.c.
References m_VignetteEffects, m_VignetteValues, and SetVignette().
Referenced by ResetVignettes(), SetMenuVignette(), SetShockVignette(), SetTunnelVignette(), and SetUnconsciousnessVignette().
Field Documentation
COLOR_SHOCK
const float COLOR_SHOCK = 0.1 static private
Definition at line 8 of file PPEffects.c.
Referenced by SetShockEffectColor().
COLORIZE_NV
const int COLORIZE_NV = 100 static private
Definition at line 5 of file PPEffects.c.
Referenced by Init(), and SetColorizationNV().
m_BloodSaturation
float m_BloodSaturation static private
Definition at line 33 of file PPEffects.c.
Referenced by SetBloodSaturation(), and UpdateSaturation().
m_BlurDrunk
int m_BlurDrunk static private
Definition at line 14 of file PPEffects.c.
Referenced by Init(), and SetBlurDrunk().
m_BlurFever
int m_BlurFever static private
Definition at line 15 of file PPEffects.c.
Referenced by Init(), and SetBlurFever().
m_BlurFlashbang
int m_BlurFlashbang static private
Definition at line 18 of file PPEffects.c.
Referenced by Init(), and SetBlurFlashbang().
m_BlurInventory
int m_BlurInventory static private
Definition at line 13 of file PPEffects.c.
Referenced by Init(), and SetBlurInventory().
m_BlurMenu
int m_BlurMenu static private
Definition at line 16 of file PPEffects.c.
Referenced by Init(), and SetBlurMenu().
m_BlurOptics
int m_BlurOptics static private
Definition at line 17 of file PPEffects.c.
Referenced by Init(), and SetBlurOptics().
m_BlurShock
int m_BlurShock static private
Definition at line 19 of file PPEffects.c.
Referenced by SetBlurShock().
m_BlurValues
ref array<float> m_BlurValues static private
Definition at line 35 of file PPEffects.c.
Referenced by Init(), RegisterBlurEffect(), ResetBlurEffects(), SetBlurValue(), and UpdateBlur().
m_BurlapBlindness
int m_BurlapBlindness static private
Definition at line 21 of file PPEffects.c.
Referenced by DisableBurlapSackBlindness(), EnableBurlapSackBlindness(), and Init().
m_ChromAbbOptic
int m_ChromAbbOptic static private
Definition at line 25 of file PPEffects.c.
Referenced by Init(), and SetChromAbbOptic().
m_ChromAbbValues
ref array<float> m_ChromAbbValues static private
Definition at line 36 of file PPEffects.c.
Referenced by Init(), RegisterChromAbbEffect(), ResetChromAbbEffects(), SetChromAbbValue(), and UpdateChromAbb().
m_ColorEffect
ref array<float> m_ColorEffect static private
Definition at line 40 of file PPEffects.c.
Referenced by Init(), RegisterColorEffect(), ResetColorEffects(), and SetColorValue().
m_ColorizeEffects
ref map<int, ref array<float> > m_ColorizeEffects static private
Definition at line 41 of file PPEffects.c.
Referenced by Init(), SetColorizationNV(), and UpdateColorize().
m_ColorOverlayTotal
float m_ColorOverlayTotal static private
Definition at line 47 of file PPEffects.c.
Referenced by UpdateColor().
m_ColorValues
ref map<int, ref array<float> > m_ColorValues static private
Definition at line 39 of file PPEffects.c.
Referenced by Init(), ResetColorEffects(), SetColorValue(), and UpdateColor().
m_ColorValueTotal
float m_ColorValueTotal[4] = {0,0,0,0} static private
Definition at line 46 of file PPEffects.c.
Referenced by FlashbangEffect(), HitEffect(), and UpdateColor().
m_DyingEffect
int m_DyingEffect static private
Definition at line 22 of file PPEffects.c.
Referenced by Init(), and SetDeathDarkening().
m_MatColors
Material m_MatColors static private
Definition at line 49 of file PPEffects.c.
Referenced by FlashbangEffect(), HitEffect(), Init(), PerformSetLensEffect(), ResetColorize(), SetBloom(), SetChromAbb(), SetVignette(), UpdateColor(), UpdateColorize(), and UpdateSaturation().
m_RadialBlur
Material m_RadialBlur static private
Definition at line 50 of file PPEffects.c.
Referenced by Init(), and SetRadialBlur().
m_ShockEffect
int m_ShockEffect static private
Definition at line 23 of file PPEffects.c.
Referenced by Init(), and SetShockEffectColor().
m_VignetteEffects
ref array<int> m_VignetteEffects static private
Definition at line 37 of file PPEffects.c.
Referenced by Init(), RegisterVignetteEffect(), SetVignetteEffectValue(), and UpdateVignette().
m_VignetteMenu
int m_VignetteMenu static private
Definition at line 31 of file PPEffects.c.
Referenced by Init(), and SetMenuVignette().
m_VignetteShock
int m_VignetteShock static private
Definition at line 29 of file PPEffects.c.
Referenced by Init(), and SetShockVignette().
m_VignetteTunnel
int m_VignetteTunnel static private
Definition at line 30 of file PPEffects.c.
Referenced by Init(), and SetTunnelVignette().
m_VignetteUnconscious
int m_VignetteUnconscious static private
Definition at line 28 of file PPEffects.c.
Referenced by Init(), and SetUnconsciousnessVignette().
m_VignetteValues
ref map<int, ref array<float> > m_VignetteValues static private
Definition at line 38 of file PPEffects.c.
Referenced by Init(), ResetVignettes(), SetVignetteEffectValue(), and UpdateVignette().
The documentation for this class was generated from the following file:
3_Game/PPEffects.c