DayZ Scripts: ServerBrowserTab Class Reference
ServerBrowserTab Class Reference
Private Member Functions
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type)
void ShowHideConsoleWidgets ()
override void OnLoadServersAsyncConsole (GetServersResult result_list, EBiosError error, string response)
void OnLoadServersAsyncFinished ()
void LoadEntries (int cur_page_index, GetServersResultRowArray page)
override void OnFilterFocus (Widget w)
override void OnFilterChanged ()
override void RefreshList ()
override void ResetFilters ()
override void ApplyFilters ()
override void OnFilterFocusLost (Widget w)
override void PressA ()
override void PressX ()
override void PressY ()
override void PressSholderLeft ()
override void PressSholderRight ()
void SetFocusFilters ()
override void Focus ()
void SetFocusServers ()
void SetEnableFilters (bool enable)
void SetEnableServers (bool enable)
override void ColorHighlight (Widget w)
override void ColorNormal (Widget w)
override void ColorDisable (Widget w)
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type)
void ShowHideConsoleWidgets ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override void OnLoadServersAsyncConsole (GetServersResult result_list, EBiosError error, string response)
void OnLoadServersAsyncFinished ()
protected void LoadEntries (int cur_page_index, GetServersResultRowArray page_entries)
protected ServerBrowserEntry GetServerEntryByIndex (int index)
override void OnFilterChanged ()
bool CanRefreshServerList ()
override void RefreshList ()
override void ResetFilters ()
override void ApplyFilters ()
override void PressA ()
override void PressX ()
override void PressY ()
override void Left ()
override void LeftHold ()
override void LeftRelease ()
override void Right ()
override void RightHold ()
override void RightRelease ()
override void PressSholderLeft ()
override void PressSholderRight ()
override void Focus ()
void SetFocusFilters ()
void SetFocusServers ()
void SetEnableFilters (bool enable)
void SetEnableServers (bool enable)
void UpdatePageButtons ()
override bool OnClick (Widget w, int x, int y, int button)
override void ColorHighlight (Widget w)
override void ColorNormal (Widget w)
override void ColorDisable (Widget w)
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type)
void ~ServerBrowserTabPc ()
void DisableFilters ()
override void RefreshList ()
override void ResetFilters ()
override void ApplyFilters ()
void LoadingServersStop ()
override void OnLoadServersAsyncPC (ref GetServersResult result_list, EBiosError error, string response)
void OnLoadServersAsyncPCFinished ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override void OnFilterChanged ()
void OnClickPagePrev ()
void OnClickPageNext ()
void OnClickPageEnd ()
void OnClickPageFirst ()
bool OnClickPage (Widget w)
void SetPageIndex (int page_index)
void ToggleSort (ESortType type)
override void SetSort (ESortType type, ESortOrder order)
int GetTimeOfDayEnum (string time_of_day)
override int AddSorted (GetServersResultRow entry)
override void SelectServer (ServerBrowserEntry server)
int SortedInsert (GetServersResultRow entry, ESortType sort_type)
int SortedInsertAsc (GetServersResultRow entry, ESortType sort_type)
int SortedInsertDesc (GetServersResultRow entry, ESortType sort_type)
void UpdatePageButtons ()
void UpdateServerList ()
void UpdateStatusBar ()
override void OnLoadServerModsAsync (string server_id, array< string > mods)
protected ServerBrowserEntry GetServerEntryByIndex (int index, string server_id)
override bool IsFocusable (Widget w)
void ButtonRefreshToCancel ()
void ButtonCancelToRefresh ()
Private Attributes
private bool m_IsFilterChanged
private bool m_IsFilterFocused
private Widget m_WidgetNavFilters
private Widget m_WidgetNavServers
protected bool m_MouseKeyboardControlled private Widget m_WidgetNavFilters
protected Widget m_ButtonPageLeftImg
protected Widget m_ButtonPageRightImg
protected int m_PreviousPage
protected int m_TotalServersCount
protected int m_PageStartNum
protected int m_PageEndNum
protected int m_PagesCount
protected int m_ServersEstimateCount
protected int m_TimeLastServerRefresh
protected int m_TimeLastServerRefreshHoldButton
protected Widget m_PnlPagesPanel
protected TextWidget m_PnlPagesLoadingText
protected ref array< ref ServerBrowserEntry > m_ServerListEntiers
protected const int SERVERS_VISIBLE_COUNT = 24
protected const int PAGES_BUTTONS_COUNT = 10
protected int m_PageIndex
protected ButtonWidget m_BtnPagesFirst
protected ButtonWidget m_BtnPagesLast
protected Widget m_FilterSearchIP
protected Widget m_FilterSearchIPBox
protected Widget m_FilterPanelPing
protected Widget m_FilterPanelAccTime
protected ref array< ButtonWidget > m_BtnPages
protected ref array< ref ServerBrowserEntry > m_ServerListEntries
protected ref TStringArray m_TempTime = new TStringArray
Detailed Description
Definition at line 1 of file ServerBrowserTabConsole.c.
Constructor & Destructor Documentation
~ServerBrowserTabPc()
void ~ServerBrowserTabPc () inline private
Definition at line 129 of file ServerBrowserTabPc.c.
Member Function Documentation
AddSorted()
override int AddSorted (GetServersResultRow entry) inline private
Definition at line 607 of file ServerBrowserTabPc.c.
References m_SortType.
ApplyFilters() [1/3]
override void ApplyFilters () inline private
Definition at line 233 of file ServerBrowserTabConsole.c.
References m_CurrentFilterInput, m_Filters, and RefreshList().
ApplyFilters() [2/3]
override void ApplyFilters () inline private
Definition at line 305 of file ServerBrowserTabConsolePages.c.
References m_CurrentFilterInput, m_Filters, ServerBrowserTabConsolePages::RefreshList(), and SetCurrentPage().
ApplyFilters() [3/3]
override void ApplyFilters () inline private
Definition at line 181 of file ServerBrowserTabPc.c.
References ButtonDisable(), ButtonEnable(), m_ApplyFilter, m_Filters, m_RefreshList, and ServerBrowserTabPc::RefreshList().
ButtonCancelToRefresh()
void ButtonCancelToRefresh () inline private
Definition at line 1115 of file ServerBrowserTabPc.c.
References m_RefreshList.
ButtonRefreshToCancel()
void ButtonRefreshToCancel () inline private
Definition at line 1109 of file ServerBrowserTabPc.c.
References m_RefreshList.
CanRefreshServerList()
bool CanRefreshServerList () inline private
Definition at line 266 of file ServerBrowserTabConsolePages.c.
References m_LoadingFinished.
ColorDisable() [1/2]
override void ColorDisable (Widget w) inline private
Definition at line 429 of file ServerBrowserTabConsole.c.
References ColorManager::COLOR_DISABLED_TEXT, and SetFocus().
Referenced by ButtonDisable().
ColorDisable() [2/2]
override void ColorDisable (Widget w) inline private
Definition at line 667 of file ServerBrowserTabConsolePages.c.
References ColorManager::COLOR_DISABLED_TEXT, and SetFocus().
ColorHighlight() [1/2]
override void ColorHighlight (Widget w) inline private
Definition at line 367 of file ServerBrowserTabConsole.c.
References ARGB().
Referenced by OnFocus(), and OnMouseEnter().
ColorHighlight() [2/2]
override void ColorHighlight (Widget w) inline private
Definition at line 601 of file ServerBrowserTabConsolePages.c.
References ARGB().
ColorNormal() [1/2]
override void ColorNormal (Widget w) inline private
Definition at line 377 of file ServerBrowserTabConsole.c.
References ARGB().
Referenced by ButtonEnable(), OnFocusLost(), and OnMouseLeave().
ColorNormal() [2/2]
override void ColorNormal (Widget w) inline private
Definition at line 611 of file ServerBrowserTabConsolePages.c.
References ARGB().
Construct() [1/3]
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type) inline private
Definition at line 9 of file ServerBrowserTabConsole.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_ApplyFilter, m_EntriesSorted, m_EntryWidgets, m_Filters, m_FiltersChanged, m_HostSort, m_LoadingText, m_Menu, m_PingSort, m_PopulationSort, m_RefreshList, m_Root, m_ServerList, m_ServerListScroller, m_SlotsSort, m_TabType, m_TimeSort, SetFocusFilters(), SetSort(), and ShowHideConsoleWidgets().
Referenced by ServerBrowserTab().
Construct() [2/3]
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type) inline private
Definition at line 26 of file ServerBrowserTabConsolePages.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), GetInput(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), CGame::GetWorkspace(), ScriptInvoker::Insert(), m_ApplyFilter, m_BtnPageNext, m_BtnPagePrev, m_EntriesSorted, m_EntryWidgets, m_Filters, m_FiltersChanged, m_FilterSearchText, m_FilterSearchTextBox, m_HostSort, m_LoadingFinished, m_LoadingText, m_Menu, m_PingSort, m_PopulationSort, m_RefreshList, m_ResetFilters, m_Root, m_ServerList, m_ServerListScroller, m_SlotsSort, m_TabType, m_TimeSort, OnInputDeviceChanged(), SetCurrentPage(), and ServerBrowserTabConsolePages::SetFocusFilters().
Construct() [3/3]
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type) inline private
Definition at line 28 of file ServerBrowserTabPc.c.
References ButtonDisable(), WorkspaceWidget::CreateWidgets(), Error(), GetGame(), CGame::GetWorkspace(), m_ApplyFilter, m_BtnPageNext, m_BtnPagePrev, m_EntriesSorted, m_EntryMods, m_EntryWidgets, m_Filters, m_FiltersChanged, m_FilterSearchText, m_FilterSearchTextBox, m_HostSort, m_LoadingText, m_Menu, m_PingSort, m_PopulationSort, m_RefreshList, m_ResetFilters, m_Root, m_ServerList, m_ServerListScroller, m_SlotsSort, m_SortInverted, m_TabType, m_TimeSort, and SetSort().
DisableFilters()
void DisableFilters () inline private
Definition at line 134 of file ServerBrowserTabPc.c.
References m_ApplyFilter, m_FiltersChanged, and m_Root.
Focus() [1/2]
override void Focus () inline private
Definition at line 320 of file ServerBrowserTabConsole.c.
References m_CurrentSelectedServer, m_EntryWidgets, ScrollToEntry(), and SetFocusServers().
Referenced by UIScriptedMenu::OnTabSwitch().
Focus() [2/2]
override void Focus () inline private
Definition at line 452 of file ServerBrowserTabConsolePages.c.
References m_CurrentSelectedServer, m_EntriesSorted, m_EntryWidgets, m_SortType, ScrollToEntry(), and ServerBrowserTabConsolePages::SetFocusFilters().
GetServerEntryByIndex() [1/2]
protected ServerBrowserEntry GetServerEntryByIndex (int index) inline private
Definition at line 235 of file ServerBrowserTabConsolePages.c.
References m_ServerList.
GetServerEntryByIndex() [2/2]
protected ServerBrowserEntry GetServerEntryByIndex (int index, string server_id) inline private
Definition at line 1051 of file ServerBrowserTabPc.c.
References m_EntryWidgets, and m_ServerList.
GetTimeOfDayEnum()
int GetTimeOfDayEnum (string time_of_day) inline private
Definition at line 573 of file ServerBrowserTabPc.c.
References string::Split().
IsFocusable()
override bool IsFocusable (Widget w) inline private
Definition at line 1080 of file ServerBrowserTabPc.c.
References m_HostSort, m_PingSort, m_PopulationSort, m_ServerListScroller, m_SlotsSort, and m_TimeSort.
Referenced by OnFocus(), OnFocusLost(), OnMouseEnter(), and OnMouseLeave().
Left()
override void Left () inline private
Definition at line 361 of file ServerBrowserTabConsolePages.c.
References GetCurrentPage(), and SetCurrentPage().
Referenced by UIScriptedMenu::Update().
LeftHold()
override void LeftHold () inline private
Definition at line 375 of file ServerBrowserTabConsolePages.c.
References GetGame(), GetTime(), CGame::GetTime(), and Left().
Referenced by UIScriptedMenu::Update().
LeftRelease()
override void LeftRelease () inline private
Definition at line 387 of file ServerBrowserTabConsolePages.c.
References GetCurrentPage(), and ServerBrowserTabConsolePages::RefreshList().
Referenced by UIScriptedMenu::Update().
LoadEntries() [1/2]
void LoadEntries (int cur_page_index, GetServersResultRowArray page) inline private
Definition at line 122 of file ServerBrowserTabConsole.c.
References Count, m_EntriesSorted, m_EntryWidgets, m_LastLoadedPage, m_Menu, m_ServerList, m_SortType, m_TabType, m_TotalLoadedServers, m_TotalPages, PassFilter(), SERVER_BROWSER_PAGE_SIZE, and SetFocusServers().
Referenced by OnLoadServersAsyncConsole().
LoadEntries() [2/2]
protected void LoadEntries (int cur_page_index, GetServersResultRowArray page_entries) inline private
Definition at line 180 of file ServerBrowserTabConsolePages.c.
References ServerBrowserTabConsolePages::LoadExtraEntries(), m_CurrentPageNum, m_EntriesSorted, m_EntryWidgets, m_Menu, m_OnlineFavServers, m_ServerList, m_SortType, m_TabType, m_TotalLoadedServers, and ServerBrowserTabConsolePages::PassFilter().
LoadingServersStop()
void LoadingServersStop () inline private
Definition at line 190 of file ServerBrowserTabPc.c.
References m_Loading, m_LoadingFinished, m_Menu, OnlineServices::m_ServersAsyncInvoker, and ScriptInvoker::Remove().
OnClick() [1/2]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 558 of file ServerBrowserTabConsolePages.c.
References ApplyFilters(), Left(), m_ApplyFilter, m_BtnPageNext, m_BtnPagePrev, m_Loading, m_LoadingFinished, m_RefreshList, m_ResetFilters, ServerBrowserTabConsolePages::PressX(), ServerBrowserTabConsolePages::RefreshList(), ResetFilters(), Right(), x, and y.
OnClick() [2/2]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 263 of file ServerBrowserTabPc.c.
References ApplyFilters(), m_ApplyFilter, m_BtnPageNext, m_BtnPagePrev, m_Loading, m_LoadingFinished, m_RefreshList, m_ResetFilters, ServerBrowserTabPc::RefreshList(), ResetFilters(), x, and y.
OnClickPage()
bool OnClickPage (Widget w) inline private
Definition at line 450 of file ServerBrowserTabPc.c.
OnClickPageEnd()
void OnClickPageEnd () inline private
Definition at line 440 of file ServerBrowserTabPc.c.
OnClickPageFirst()
void OnClickPageFirst () inline private
Definition at line 445 of file ServerBrowserTabPc.c.
OnClickPageNext()
void OnClickPageNext () inline private
Definition at line 428 of file ServerBrowserTabPc.c.
OnClickPagePrev()
void OnClickPagePrev () inline private
Definition at line 416 of file ServerBrowserTabPc.c.
OnFilterChanged() [1/3]
override void OnFilterChanged () inline private
Definition at line 202 of file ServerBrowserTabConsole.c.
Referenced by ScriptedWidgetEventHandler::OnFilterChanged().
OnFilterChanged() [2/3]
override void OnFilterChanged () inline private
Definition at line 261 of file ServerBrowserTabConsolePages.c.
OnFilterChanged() [3/3]
override void OnFilterChanged () inline private
Definition at line 404 of file ServerBrowserTabPc.c.
References ButtonDisable(), ButtonEnable(), m_ApplyFilter, m_Loading, and m_RefreshList.
OnFilterFocus()
override void OnFilterFocus (Widget w) inline private
Definition at line 195 of file ServerBrowserTabConsole.c.
Referenced by ScriptedWidgetEventHandler::OnFocus().
OnFilterFocusLost()
override void OnFilterFocusLost (Widget w) inline private
Definition at line 240 of file ServerBrowserTabConsole.c.
OnInputDeviceChanged()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 117 of file ServerBrowserTabConsolePages.c.
References GetGame(), and GetInput().
OnLoadServerModsAsync()
override void OnLoadServerModsAsync (string server_id, array< string > mods) inline private
Definition at line 1041 of file ServerBrowserTabPc.c.
References m_EntryWidgets.
Referenced by UIScriptedMenu::OnLoadServerModsAsync().
OnLoadServersAsyncConsole() [1/2]
override void OnLoadServersAsyncConsole (GetServersResult result_list, EBiosError error, string response) inline private
Definition at line 67 of file ServerBrowserTabConsole.c.
References ErrorModuleHandler::GetClientMessage(), GetNextPage(), LoadEntries(), m_LastLoadedPage, m_LoadingText, m_Menu, GetServersResult::m_NumServers, GetServersResult::m_Page, GetServersResult::m_Pages, GetServersResult::m_Results, m_TabType, m_TotalPages, m_TotalServers, and OnLoadServersAsyncFinished().
Referenced by UIScriptedMenu::OnLoadServersAsync().
OnLoadServersAsyncConsole() [2/2]
override void OnLoadServersAsyncConsole (GetServersResult result_list, EBiosError error, string response) inline private
Definition at line 142 of file ServerBrowserTabConsolePages.c.
References ErrorModuleHandler::GetClientMessage(), ServerBrowserTabConsolePages::LoadEntries(), m_LoadingFinished, m_LoadingText, m_Menu, GetServersResult::m_NumServers, GetServersResult::m_Page, GetServersResult::m_Pages, GetServersResult::m_Results, m_TotalLoadedServers, ServerBrowserTabConsolePages::OnLoadServersAsyncFinished(), and ServerBrowserTabConsolePages::SetFocusFilters().
OnLoadServersAsyncFinished() [1/2]
void OnLoadServersAsyncFinished () inline private
Definition at line 111 of file ServerBrowserTabConsole.c.
References m_LoadingFinished, m_LoadingText, and m_TotalLoadedServers.
Referenced by OnLoadServersAsyncConsole().
OnLoadServersAsyncFinished() [2/2]
void OnLoadServersAsyncFinished () inline private
Definition at line 167 of file ServerBrowserTabConsolePages.c.
References m_LoadingFinished, m_LoadingText, m_Menu, and m_TotalLoadedServers.
OnLoadServersAsyncPC()
override void OnLoadServersAsyncPC (ref GetServersResult result_list, EBiosError error, string response) inline private
Definition at line 203 of file ServerBrowserTabPc.c.
References AddSorted(), m_Menu, m_TabType, and PassFilter().
Referenced by UIScriptedMenu::OnLoadServersAsync().
OnLoadServersAsyncPCFinished()
void OnLoadServersAsyncPCFinished () inline private
Definition at line 258 of file ServerBrowserTabPc.c.
OnMouseButtonUp()
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 364 of file ServerBrowserTabPc.c.
References m_HostSort, m_PingSort, m_PopulationSort, m_SlotsSort, and m_TimeSort.
OnMouseEnter()
override bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 326 of file ServerBrowserTabPc.c.
References ColorHighlight(), IsFocusable(), m_FilterSearchText, m_FilterSearchTextBox, and SetFocus().
Referenced by ScriptedWidgetEventHandler::OnMouseEnter().
OnMouseLeave()
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 348 of file ServerBrowserTabPc.c.
References ColorNormal(), IsFocusable(), m_FilterSearchText, and SetFocus().
Referenced by ScriptedWidgetEventHandler::OnMouseLeave().
PressA() [1/2]
override void PressA () inline private
Definition at line 245 of file ServerBrowserTabConsole.c.
Referenced by UIScriptedMenu::Update().
PressA() [2/2]
override void PressA () inline private
Definition at line 317 of file ServerBrowserTabConsolePages.c.
PressSholderLeft() [1/2]
override void PressSholderLeft () inline private
Definition at line 283 of file ServerBrowserTabConsole.c.
References SetFocusFilters(), and SetFocusServers().
Referenced by UIScriptedMenu::Update().
PressSholderLeft() [2/2]
override void PressSholderLeft () inline private
Definition at line 429 of file ServerBrowserTabConsolePages.c.
References ServerBrowserTabConsolePages::SetFocusFilters().
PressSholderRight() [1/2]
override void PressSholderRight () inline private
Definition at line 295 of file ServerBrowserTabConsole.c.
References SetFocusFilters(), and SetFocusServers().
Referenced by UIScriptedMenu::Update().
PressSholderRight() [2/2]
override void PressSholderRight () inline private
Definition at line 441 of file ServerBrowserTabConsolePages.c.
References ServerBrowserTabConsolePages::SetFocusFilters().
PressX() [1/2]
override void PressX () inline private
Definition at line 250 of file ServerBrowserTabConsole.c.
References RefreshList().
Referenced by UIScriptedMenu::Update().
PressX() [2/2]
override void PressX () inline private
Definition at line 322 of file ServerBrowserTabConsolePages.c.
References GetGame(), GetTime(), CGame::GetTime(), m_OnlineFavServers, ServerBrowserTabConsolePages::RefreshList(), and SetCurrentPage().
PressY() [1/2]
override void PressY () inline private
Definition at line 255 of file ServerBrowserTabConsole.c.
References m_Filters, m_Menu, m_SelectedPanel, and m_SelectedServer.
Referenced by UIScriptedMenu::Update().
PressY() [2/2]
override void PressY () inline private
Definition at line 338 of file ServerBrowserTabConsolePages.c.
References m_Filters, m_Menu, m_SelectedPanel, and m_SelectedServer.
RefreshList() [1/3]
override void RefreshList () inline private
Definition at line 207 of file ServerBrowserTabConsole.c.
References m_EntriesSorted, m_Filters, m_LoadingText, m_ServerListScroller, and SetFocusFilters().
Referenced by ApplyFilters(), UIScriptedMenu::OnTabSwitch(), PressX(), and PressX().
RefreshList() [2/3]
override void RefreshList () inline private
Definition at line 271 of file ServerBrowserTabConsolePages.c.
References m_EntriesSorted, m_Filters, m_LoadingText, and m_ServerListScroller.
RefreshList() [3/3]
override void RefreshList () inline private
Definition at line 144 of file ServerBrowserTabPc.c.
References ScriptInvoker::Insert(), m_EntriesSorted, m_Loading, m_LoadingFinished, m_Menu, m_ServerListScroller, OnlineServices::m_ServersAsyncInvoker, and m_TotalLoadedServers.
ResetFilters() [1/3]
override void ResetFilters () inline private
Definition at line 226 of file ServerBrowserTabConsole.c.
ResetFilters() [2/3]
override void ResetFilters () inline private
Definition at line 298 of file ServerBrowserTabConsolePages.c.
ResetFilters() [3/3]
override void ResetFilters () inline private
Definition at line 169 of file ServerBrowserTabPc.c.
References ButtonDisable(), ButtonEnable(), m_ApplyFilter, m_Filters, m_Loading, and m_RefreshList.
Right()
override void Right () inline private
Definition at line 395 of file ServerBrowserTabConsolePages.c.
References GetCurrentPage(), and SetCurrentPage().
Referenced by UIScriptedMenu::Update().
RightHold()
override void RightHold () inline private
Definition at line 409 of file ServerBrowserTabConsolePages.c.
References GetGame(), GetTime(), CGame::GetTime(), and Right().
Referenced by UIScriptedMenu::Update().
RightRelease()
override void RightRelease () inline private
Definition at line 421 of file ServerBrowserTabConsolePages.c.
References GetCurrentPage(), and ServerBrowserTabConsolePages::RefreshList().
Referenced by UIScriptedMenu::Update().
SelectServer()
override void SelectServer (ServerBrowserEntry server) inline private
Definition at line 638 of file ServerBrowserTabPc.c.
References m_Menu, m_SelectedServer, and ScrollToEntry().
Referenced by ScriptedWidgetEventHandler::Select().
SetEnableFilters() [1/2]
void SetEnableFilters (bool enable) inline private
Definition at line 350 of file ServerBrowserTabConsole.c.
References m_Root.
Referenced by SetFocusFilters(), and SetFocusServers().
SetEnableFilters() [2/2]
void SetEnableFilters (bool enable) inline private
Definition at line 514 of file ServerBrowserTabConsolePages.c.
References m_Root, and SetFocus().
SetEnableServers() [1/2]
void SetEnableServers (bool enable) inline private
Definition at line 358 of file ServerBrowserTabConsole.c.
References m_Root.
Referenced by SetFocusFilters(), and SetFocusServers().
SetEnableServers() [2/2]
void SetEnableServers (bool enable) inline private
Definition at line 526 of file ServerBrowserTabConsolePages.c.
References m_Root.
SetFocusFilters() [1/2]
void SetFocusFilters () inline private
Definition at line 307 of file ServerBrowserTabConsole.c.
References m_EntryWidgets, m_Filters, SetEnableFilters(), and SetEnableServers().
Referenced by Construct(), PressSholderLeft(), PressSholderRight(), RefreshList(), and SetFocusServers().
SetFocusFilters() [2/2]
void SetFocusFilters () inline private
Definition at line 468 of file ServerBrowserTabConsolePages.c.
References m_Filters.
SetFocusServers() [1/2]
void SetFocusServers () inline private
Definition at line 330 of file ServerBrowserTabConsole.c.
References m_EntriesSorted, m_EntryWidgets, m_SortType, SetEnableFilters(), SetEnableServers(), and SetFocusFilters().
Referenced by Focus(), LoadEntries(), PressSholderLeft(), and PressSholderRight().
SetFocusServers() [2/2]
void SetFocusServers () inline private
Definition at line 486 of file ServerBrowserTabConsolePages.c.
References m_EntriesSorted, m_EntryWidgets, m_Menu, m_SortType, and SetFocus().
SetPageIndex()
void SetPageIndex (int page_index) inline private
Definition at line 464 of file ServerBrowserTabPc.c.
SetSort()
override void SetSort (ESortType type, ESortOrder order) inline private
Definition at line 502 of file ServerBrowserTabPc.c.
References ARGBF(), m_Root, and m_SortOrder.
Referenced by Construct(), and ScriptedWidgetEventHandler::OnSortChanged().
ShowHideConsoleWidgets() [1/2]
void ShowHideConsoleWidgets () inline private
Definition at line 48 of file ServerBrowserTabConsole.c.
References m_Root.
Referenced by Construct().
ShowHideConsoleWidgets() [2/2]
void ShowHideConsoleWidgets () inline private
Definition at line 96 of file ServerBrowserTabConsolePages.c.
References GetGame(), GetInput(), and m_Root.
SortedInsert()
int SortedInsert (GetServersResultRow entry, ESortType sort_type) inline private
Definition at line 654 of file ServerBrowserTabPc.c.
References m_SortInverted.
SortedInsertAsc()
int SortedInsertAsc (GetServersResultRow entry, ESortType sort_type) inline private
Definition at line 664 of file ServerBrowserTabPc.c.
References Math::Floor(), GetValueInt(), GetValueStr(), and m_EntriesSorted.
SortedInsertDesc()
int SortedInsertDesc (GetServersResultRow entry, ESortType sort_type) inline private
Definition at line 753 of file ServerBrowserTabPc.c.
References Math::Floor(), GetValueInt(), GetValueStr(), and m_EntriesSorted.
ToggleSort()
void ToggleSort (ESortType type) inline private
Definition at line 471 of file ServerBrowserTabPc.c.
References m_EntriesSorted, m_SortInverted, m_SortOrder, m_SortType, and SetSort().
UpdatePageButtons() [1/2]
void UpdatePageButtons () inline private
Definition at line 533 of file ServerBrowserTabConsolePages.c.
References GetCurrentPage(), m_BtnPageNext, m_BtnPagePrev, m_Root, ToString(), and string::ToString().
UpdatePageButtons() [2/2]
void UpdatePageButtons () inline private
Definition at line 842 of file ServerBrowserTabPc.c.
References Math::Ceil(), m_BtnPageNext, m_BtnPagePrev, m_TotalLoadedServers, and Math::Round().
UpdateServerList()
void UpdateServerList () inline private
Definition at line 978 of file ServerBrowserTabPc.c.
References Count, GetRootMenu(), ServerBrowserTabPc::LoadExtraEntries(), m_EntriesSorted, m_EntryMods, m_EntryWidgets, m_OnlineFavServers, m_ServerList, m_SortType, and m_TotalLoadedServers.
UpdateStatusBar()
void UpdateStatusBar () inline private
Definition at line 1028 of file ServerBrowserTabPc.c.
References m_LoadingFinished, m_LoadingText, and m_TotalLoadedServers.
Field Documentation
m_BtnPages
protected ref array<ButtonWidget> m_BtnPages private
Definition at line 23 of file ServerBrowserTabPc.c.
m_BtnPagesFirst
protected ButtonWidget m_BtnPagesFirst private
Definition at line 15 of file ServerBrowserTabPc.c.
m_BtnPagesLast
protected ButtonWidget m_BtnPagesLast private
Definition at line 16 of file ServerBrowserTabPc.c.
m_ButtonPageLeftImg
protected Widget m_ButtonPageLeftImg private
Definition at line 10 of file ServerBrowserTabConsolePages.c.
m_ButtonPageRightImg
protected Widget m_ButtonPageRightImg private
Definition at line 11 of file ServerBrowserTabConsolePages.c.
m_FilterPanelAccTime
protected Widget m_FilterPanelAccTime private
Definition at line 21 of file ServerBrowserTabPc.c.
m_FilterPanelPing
protected Widget m_FilterPanelPing private
Definition at line 20 of file ServerBrowserTabPc.c.
m_FilterSearchIP
protected Widget m_FilterSearchIP private
Definition at line 18 of file ServerBrowserTabPc.c.
m_FilterSearchIPBox
protected Widget m_FilterSearchIPBox private
Definition at line 19 of file ServerBrowserTabPc.c.
m_IsFilterChanged
private bool m_IsFilterChanged private
Definition at line 3 of file ServerBrowserTabConsole.c.
m_IsFilterFocused
private bool m_IsFilterFocused private
Definition at line 4 of file ServerBrowserTabConsole.c.
m_PageEndNum
protected int m_PageEndNum private
Definition at line 16 of file ServerBrowserTabConsolePages.c.
m_PageIndex
protected int m_PageIndex private
Definition at line 7 of file ServerBrowserTabPc.c.
m_PagesCount
protected int m_PagesCount private
Definition at line 17 of file ServerBrowserTabConsolePages.c.
m_PageStartNum
protected int m_PageStartNum private
Definition at line 15 of file ServerBrowserTabConsolePages.c.
m_PnlPagesLoadingText
protected TextWidget m_PnlPagesLoadingText private
Definition at line 23 of file ServerBrowserTabConsolePages.c.
m_PnlPagesPanel
protected Widget m_PnlPagesPanel private
Definition at line 22 of file ServerBrowserTabConsolePages.c.
m_PreviousPage
protected int m_PreviousPage private
Definition at line 13 of file ServerBrowserTabConsolePages.c.
m_ServerListEntiers
protected ref array<ref ServerBrowserEntry> m_ServerListEntiers private
Definition at line 24 of file ServerBrowserTabConsolePages.c.
m_ServerListEntries
protected ref array<ref ServerBrowserEntry> m_ServerListEntries private
Definition at line 24 of file ServerBrowserTabPc.c.
m_ServersEstimateCount
protected int m_ServersEstimateCount private
Definition at line 18 of file ServerBrowserTabConsolePages.c.
m_TempTime
protected ref TStringArray m_TempTime = new TStringArray private
Definition at line 26 of file ServerBrowserTabPc.c.
m_TimeLastServerRefresh
protected int m_TimeLastServerRefresh private
Definition at line 19 of file ServerBrowserTabConsolePages.c.
m_TimeLastServerRefreshHoldButton
protected int m_TimeLastServerRefreshHoldButton private
Definition at line 20 of file ServerBrowserTabConsolePages.c.
m_TotalServersCount
protected int m_TotalServersCount private
Definition at line 14 of file ServerBrowserTabConsolePages.c.
m_WidgetNavFilters [1/2]
private Widget m_WidgetNavFilters private
Definition at line 6 of file ServerBrowserTabConsole.c.
m_WidgetNavFilters [2/2]
protected bool m_MouseKeyboardControlled private Widget m_WidgetNavFilters private
Definition at line 7 of file ServerBrowserTabConsolePages.c.
m_WidgetNavServers
private Widget m_WidgetNavServers private
Definition at line 7 of file ServerBrowserTabConsole.c.
PAGES_BUTTONS_COUNT
protected const int PAGES_BUTTONS_COUNT = 10 private
Definition at line 4 of file ServerBrowserTabPc.c.
SERVERS_VISIBLE_COUNT
protected const int SERVERS_VISIBLE_COUNT = 24 private
Definition at line 3 of file ServerBrowserTabPc.c.
The documentation for this class was generated from the following files:
P:/scripts/5_Mission/GUI/NewUI/ServerBrowserMenu/ServerBrowserTabConsole.c
P:/scripts/5_Mission/GUI/NewUI/ServerBrowserMenu/ServerBrowserTabConsolePages.c
P:/scripts/5_Mission/GUI/NewUI/ServerBrowserMenu/ServerBrowserTabPc.c