DayZ: ActionBuildShelter Class Reference
ActionBuildShelter Class Reference
Private Member Functions
void ActionBuildShelter ()
void ~ActionBuildShelter ()
override void CreateConditionComponents ()
override string GetText ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeUsedLeaning ()
override GetInputType ()
override bool UseMainItem ()
override bool HasProgress ()
override bool HasAlternativeInterrupt ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override ActionData CreateActionData ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool ActionConditionContinue (ActionData action_data)
override void OnStart (ActionData action_data)
override void OnStartClient (ActionData action_data)
override void OnStartAnimationLoopClient (ActionData action_data)
override void OnEnd (ActionData action_data)
override void OnEndClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnFinishProgressClient (ActionData action_data)
void DetermineConstructionSounds (ActionData action_data)
void PlayActionStartSound (ActionData action_data)
void PlayActionLoopSound (ActionData action_data)
void StopActionLoopSound ()
void DestroyActionLoopSound ()
void PlayActionFinishSound (ActionData action_data)
Private Attributes
string m_SoundsetBuildStart
string m_SoundsetBuildLoop
string m_SoundsetBuildFinish
ref protected EffectSound m_BuildLoopSound
Detailed Description
Definition at line 1 of file ActionBuildShelter.c.
Constructor & Destructor Documentation
ActionBuildShelter()
void ActionBuildShelter () inline private
Definition at line 8 of file ActionBuildShelter.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_StanceMask, and m_Text.
~ActionBuildShelter()
void ~ActionBuildShelter () inline private
Definition at line 17 of file ActionBuildShelter.c.
References DestroyActionLoopSound().
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 108 of file ActionBuildShelter.c.
References GetGame(), and m_VariantID.
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
Definition at line 183 of file ActionBuildShelter.c.
References CollisionCheckData(), Construction(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
CanBeUsedLeaning()
override bool CanBeUsedLeaning () inline private
Definition at line 83 of file ActionBuildShelter.c.
CreateActionData()
override ActionData CreateActionData () inline private
Definition at line 146 of file ActionBuildShelter.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 22 of file ActionBuildShelter.c.
References m_ConditionItem, and m_ConditionTarget.
DestroyActionLoopSound()
void DestroyActionLoopSound () inline private
Definition at line 312 of file ActionBuildShelter.c.
References SEffectManager::DestroyEffect(), and m_BuildLoopSound.
Referenced by ~ActionBuildShelter().
DetermineConstructionSounds()
void DetermineConstructionSounds (ActionData action_data) inline private
Definition at line 254 of file ActionBuildShelter.c.
References ConstructionActionData::GetBuildPartNoToolAtIndex(), ConstructionPart::GetName(), ActionData::m_Player, m_SoundsetBuildFinish, m_SoundsetBuildLoop, m_SoundsetBuildStart, and m_VariantID.
Referenced by OnStartClient().
GetInputType()
override GetInputType () inline private
Definition at line 88 of file ActionBuildShelter.c.
GetText()
override string GetText () inline private
Definition at line 28 of file ActionBuildShelter.c.
References ConstructionActionData::GetBuildPartNoToolAtIndex(), GetGame(), ConstructionPart::GetName(), GetPlayer(), and m_VariantID.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 176 of file ActionBuildShelter.c.
References BuildPartActionReciveData::m_PartType.
HasAlternativeInterrupt()
override bool HasAlternativeInterrupt () inline private
Definition at line 103 of file ActionBuildShelter.c.
HasProgress()
override bool HasProgress () inline private
Definition at line 98 of file ActionBuildShelter.c.
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 59 of file ActionBuildShelter.c.
References ConstructionActionData::GetBuildPartNoToolAtIndex(), ConstructionPart::GetName(), m_Text, and m_VariantID.
OnEnd()
override void OnEnd (ActionData action_data) inline private
Definition at line 217 of file ActionBuildShelter.c.
References ActionData::m_Player.
OnEndClient()
override void OnEndClient (ActionData action_data) inline private
Definition at line 223 of file ActionBuildShelter.c.
References StopActionLoopSound().
OnFinishProgressClient()
override void OnFinishProgressClient (ActionData action_data) inline private
Definition at line 247 of file ActionBuildShelter.c.
References PlayActionFinishSound().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 231 of file ActionBuildShelter.c.
References AT_BUILD_PART, Construction(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
OnStart()
override void OnStart (ActionData action_data) inline private
Definition at line 196 of file ActionBuildShelter.c.
References ActionData::m_Player.
OnStartAnimationLoopClient()
override void OnStartAnimationLoopClient (ActionData action_data) inline private
Definition at line 210 of file ActionBuildShelter.c.
References PlayActionLoopSound().
OnStartClient()
override void OnStartClient (ActionData action_data) inline private
Definition at line 202 of file ActionBuildShelter.c.
References DetermineConstructionSounds(), and PlayActionStartSound().
PlayActionFinishSound()
void PlayActionFinishSound (ActionData action_data) inline private
Definition at line 317 of file ActionBuildShelter.c.
References m_SoundsetBuildFinish, ActionData::m_Target, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnFinishProgressClient().
PlayActionLoopSound()
void PlayActionLoopSound (ActionData action_data) inline private
Definition at line 295 of file ActionBuildShelter.c.
References EffectSound::IsSoundPlaying(), m_BuildLoopSound, m_SoundsetBuildLoop, ActionData::m_Target, and SEffectManager::PlaySound().
Referenced by OnStartAnimationLoopClient().
PlayActionStartSound()
void PlayActionStartSound (ActionData action_data) inline private
Definition at line 289 of file ActionBuildShelter.c.
References m_SoundsetBuildStart, ActionData::m_Target, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnStartClient().
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 159 of file ActionBuildShelter.c.
References BuildPartActionReciveData::m_PartType, and Serializer::Read().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 131 of file ActionBuildShelter.c.
References ConstructionActionData::GetBuildPartNoToolAtIndex(), GetGame(), ConstructionPart::GetPartName(), and m_VariantID.
StopActionLoopSound()
void StopActionLoopSound () inline private
Definition at line 303 of file ActionBuildShelter.c.
References m_BuildLoopSound, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
Referenced by OnEndClient().
UseMainItem()
override bool UseMainItem () inline private
Definition at line 93 of file ActionBuildShelter.c.
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 152 of file ActionBuildShelter.c.
References Serializer::Write().
Field Documentation
m_BuildLoopSound
ref protected EffectSound m_BuildLoopSound private
Definition at line 6 of file ActionBuildShelter.c.
Referenced by DestroyActionLoopSound(), PlayActionLoopSound(), and StopActionLoopSound().
m_SoundsetBuildFinish
string m_SoundsetBuildFinish private
Definition at line 5 of file ActionBuildShelter.c.
Referenced by DetermineConstructionSounds(), and PlayActionFinishSound().
m_SoundsetBuildLoop
string m_SoundsetBuildLoop private
Definition at line 4 of file ActionBuildShelter.c.
Referenced by DetermineConstructionSounds(), and PlayActionLoopSound().
m_SoundsetBuildStart
string m_SoundsetBuildStart private
Definition at line 3 of file ActionBuildShelter.c.
Referenced by DetermineConstructionSounds(), and PlayActionStartSound().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Interact/ActionBuildShelter.c