DayZ: UAInputAPI Class Reference
UAInputAPI Class Reference
Private Member Functions
private void UAInputAPI ()
private void ~UAInputAPI ()
proto native void ListCurrentProfile ()
proto native void ListCurrentPreset ()
proto native void ListAvailableButtons ()
proto native void ListActiveGroup ()
proto native void GetActiveInputs (out TIntArray items)
proto native UAInput GetInputByID (int iID)
returns list of all bindable (i.e. visible) inputs from the active group ('core' by default)
proto native UAInput GetInputByName (string sInputName)
proto native owned string GetButtonName (int iHash)
proto native owned string GetButtonIcon (int iHash)
proto native int ModificatorCount ()
proto native owned string GetModificatorName (int index)
proto native int DeterminePressedButton ()
proto native int DeterminedCount ()
proto native int GetDetermined (int iIndex)
proto native UAInput RegisterInput (string sInputName, string sLoc, string sGroupName)
proto native void DeRegisterInput (string sInputName)
proto native void RegisterGroup (string sGroupName, string sLoc)
proto native void DeRegisterGroup (string sGroupName)
proto native void UpdateControls ()
proto native void ActivateGroup (string sGroupName)
proto native void ActivateExclude (string sExcludeName)
proto native void ActivateContext (string sContextName)
proto native void ActivateModificator (string sModName)
proto native void DeactivateModificator (string sModName)
proto native void DeactivateContext ()
proto native bool PresetCreateNew ()
proto native bool PresetDelete (int index)
proto native int PresetCurrent ()
proto native void PresetSelect (int index)
proto native void PresetReset ()
Resets current 'main' preset without reverting anything else ('softer' Revert)
proto native int PresetCount ()
proto native owned string PresetName (int index)
proto native int SortingCount ()
proto native owned string SortingName (int index)
proto native owned string SortingLocalization (int index)
proto native void Export ()
proto native void Revert ()
proto native void SaveInputPresetMiscData ()
proto native void SupressNextFrame (bool bForce)
proto native void Backlit_None ()
proto native void Backlit_Background (int eType, int iColor1, int iColor2)
proto native void Backlit_Animation (string strName, float fLifeTime, int iColor1, int iColor2)
proto native bool Backlit_Enabled ()
proto native void Backlit_KeyByHash (int uHash, int eLayer, int eType, int iColor)
proto native void Backlit_KeyByName (string strName, int eLayer, int eType, int iColor)
proto native void Backlit_Remove (int eLayer)
proto native void Backlit_ForceUpdate ()
proto native void Backlit_EmptyQueue ()
Detailed Description
Definition at line 164 of file UAInput.c.
Constructor & Destructor Documentation
UAInputAPI()
private void UAInputAPI () inline private
Definition at line 166 of file UAInput.c.
~UAInputAPI()
private void ~UAInputAPI () inline private
Definition at line 167 of file UAInput.c.
Member Function Documentation
ActivateContext()
proto native void ActivateContext (string sContextName) private
ActivateExclude()
proto native void ActivateExclude (string sExcludeName) private
Referenced by MissionBase::PerformRefreshExcludes(), and PluginBase::Show().
ActivateGroup()
proto native void ActivateGroup (string sGroupName) private
ActivateModificator()
proto native void ActivateModificator (string sModName) private
Referenced by DayZPlayer::CommandHandler().
Backlit_Animation()
proto native void Backlit_Animation (string strName, float fLifeTime, int iColor1, int iColor2) private
Referenced by Backlit::LoadingAnim(), Backlit::MainMenu_OnShow(), and Backlit::OnSwimmingStart().
Backlit_Background()
proto native void Backlit_Background (int eType, int iColor1, int iColor2) private
Referenced by Backlit::MainMenu_OnHide(), Backlit::OnEnterCar(), Backlit::OnLeaveCar(), Backlit::OnSwimmingStop(), and Backlit::UpdatePlayer().
Backlit_EmptyQueue()
proto native void Backlit_EmptyQueue () private
Referenced by Backlit::OnSwimmingStart().
Backlit_Enabled()
proto native bool Backlit_Enabled () private
Backlit_ForceUpdate()
proto native void Backlit_ForceUpdate () private
Referenced by Backlit::LoadingAnim(), and Backlit::MainMenu_OnShow().
Backlit_KeyByHash()
proto native void Backlit_KeyByHash (int uHash, int eLayer, int eType, int iColor) private
Referenced by Backlit::KeybindingShow().
Backlit_KeyByName()
proto native void Backlit_KeyByName (string strName, int eLayer, int eType, int iColor) private
Referenced by Backlit::LoadingAnim(), Backlit::RefreshVehicleLayout(), Backlit::UpdatePlayer(), Backlit::VisualiseBlood(), and Backlit::VisualiseHealth().
Backlit_None()
proto native void Backlit_None () private
Backlit_Remove()
proto native void Backlit_Remove (int eLayer) private
Referenced by Backlit::HintClear(), Backlit::KeybindingClear(), Backlit::MainMenu_OnHide(), Backlit::MainMenu_OnShow(), Backlit::OnEnterCar(), Backlit::OnLeaveCar(), and Backlit::UpdatePlayer().
DeactivateContext()
proto native void DeactivateContext () private
DeactivateModificator()
proto native void DeactivateModificator (string sModName) private
Referenced by DayZPlayer::CommandHandler().
DeRegisterGroup()
proto native void DeRegisterGroup (string sGroupName) private
DeRegisterInput()
proto native void DeRegisterInput (string sInputName) private
DeterminedCount()
proto native int DeterminedCount () private
Referenced by array::Update(), and ScriptedWidgetEventHandler::Update().
DeterminePressedButton()
proto native int DeterminePressedButton () private
Referenced by array::Update(), and ScriptedWidgetEventHandler::Update().
Export()
proto native void Export () private
Referenced by UIScriptedMenu::Apply(), array::OnSelectKBPreset(), UIScriptedMenu::PerformSwitchPreset(), and SwitchPreset().
GetActiveInputs()
proto native void GetActiveInputs (out TIntArray items) private
Referenced by ScriptedWidgetEventHandler::AddSubgroup(), InputUtils::InitInputMetadata(), and ScriptedWidgetEventHandler::TutorialKeybinds().
GetButtonIcon()
proto native owned string GetButtonIcon (int iHash) private
GetButtonName()
proto native owned string GetButtonName (int iHash) private
Referenced by InputUtils::GetButtonNameFromInput(), ScriptedWidgetEventHandler::Reload(), ScriptedWidgetEventHandler::SetElementTitle(), and ScriptedWidgetEventHandler::SetInteractActionIcon().
GetDetermined()
proto native int GetDetermined (int iIndex) private
Referenced by array::Update(), and ScriptedWidgetEventHandler::Update().
GetInputByID()
proto native UAInput GetInputByID (int iID) private
returns list of all bindable (i.e. visible) inputs from the active group ('core' by default)
Referenced by ScriptedWidgetEventHandler::ActionTargetsCursor(), MissionBase::AddActiveInputRestriction(), array::Apply(), ScriptedWidgetEventHandler::Apply(), DayZSpectator::EOnFrame(), DayZPlayer::HandleOptic(), UIScriptedMenu::Init(), InputUtils::InitInputMetadata(), ScriptedWidgetEventHandler::ItemActionsWidget(), UIScriptedMenu::OnChange(), DayZPlayer::OnSprintEnd(), DayZPlayer::OnSprintStart(), MissionBase::OnUpdate(), RadialMenu(), ScriptedWidgetEventHandler::Reload(), MissionBase::RemoveActiveInputRestriction(), ScriptedWidgetEventHandler::TutorialKeybinds(), and UIScriptedMenu::Update().
GetInputByName()
proto native UAInput GetInputByName (string sInputName) private
Referenced by ConstructData(), InputUtils::GetButtonIconPathFromInput(), InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), InputUtils::GetImagesetAndIconFromInputAction(), InputUtils::GetRichtextButtonIconFromInputAction(), GetStringVariant(), and ActionInput::SetInput().
GetModificatorName()
proto native owned string GetModificatorName (int index) private
ListActiveGroup()
proto native void ListActiveGroup () private
ListAvailableButtons()
proto native void ListAvailableButtons () private
ListCurrentPreset()
proto native void ListCurrentPreset () private
ListCurrentProfile()
proto native void ListCurrentProfile () private
ModificatorCount()
proto native int ModificatorCount () private
PresetCount()
proto native int PresetCount () private
Referenced by UIScriptedMenu::PerformSwitchPreset(), SwitchPreset(), and UIScriptedMenu::UpdateToolbarText().
PresetCreateNew()
proto native bool PresetCreateNew () private
PresetCurrent()
proto native int PresetCurrent () private
Referenced by OnShow(), UIScriptedMenu::PerformSwitchPreset(), SwitchPreset(), and UIScriptedMenu::UpdateToolbarText().
PresetDelete()
proto native bool PresetDelete (int index) private
PresetName()
proto native owned string PresetName (int index) private
Referenced by OnShow(), SwitchPreset(), and UIScriptedMenu::UpdateToolbarText().
PresetReset()
proto native void PresetReset () private
Resets current 'main' preset without reverting anything else ('softer' Revert)
Note
Does not reset dynamic presets, since they don't have any real defaults in the core PBOs.
Referenced by UIScriptedMenu::PerformSetToDefaultsExt().
PresetSelect()
proto native void PresetSelect (int index) private
Referenced by DayZGame(), array::OnSelectKBPreset(), UIScriptedMenu::PerformSwitchPreset(), and SwitchPreset().
RegisterGroup()
proto native void RegisterGroup (string sGroupName, string sLoc) private
RegisterInput()
proto native UAInput RegisterInput (string sInputName, string sLoc, string sGroupName) private
Revert()
proto native void Revert () private
Referenced by UIScriptedMenu::PerformSetToDefaultsExt().
SaveInputPresetMiscData()
proto native void SaveInputPresetMiscData () private
Referenced by array::OnSelectKBPreset(), and UIScriptedMenu::PerformSwitchPreset().
SortingCount()
proto native int SortingCount () private
Referenced by InputUtils::InitInputMetadata().
SortingLocalization()
proto native owned string SortingLocalization (int index) private
Referenced by UIScriptedMenu::CreateTabs().
SortingName()
proto native owned string SortingName (int index) private
SupressNextFrame()
proto native void SupressNextFrame (bool bForce) private
Referenced by MissionBase::AddActiveInputExcludes(), MissionBase::EnableAllInputs(), UIScriptedMenu::PerformSwitchPreset(), and MissionBase::RemoveActiveInputExcludes().
UpdateControls()
proto native void UpdateControls () private
Referenced by PluginBase::Hide(), MissionBase::PerformRefreshExcludes(), and PluginBase::Show().
The documentation for this class was generated from the following file:
3_Game/InputAPI/UAInput.c