DayZ Scripts Documentation: DayZPlayerImplementAiming Class Reference
DayZPlayerImplementAiming Class Reference
Private Member Functions
void DayZPlayerImplementAiming (DayZPlayerImplement player)
void SetRecoil (Weapon_Base weapon)
void RequestKuruShake (float amount)
void OnRaiseBegin (DayZPlayerImplement player)
void OnFinisherBegin (float currentAimY)
void OnSwayStateChange (int state)
float GetSwayWeight ()
void SetAimNoiseAllowed (bool state)
bool IsAimNoiseAllowed ()
void SetProceduralRecoilEnabled (bool state)
bool IsProceduralRecoilEnabled ()
void SetCamShakeValues (float x_axis, float y_axis)
bool ProcessStealthFilters (float pDt, SDayZPlayerAimingModel pModel)
bool ProcessAimFilters (float pDt, SDayZPlayerAimingModel pModel, int stance_index)
protected float CalculateSwayMultiplier ()
protected bool UpdateSwayState (int state)
int GetCurrentSwayState ()
protected void ApplyBreathingPattern (out float x_axis, out float y_axis, float pAmplitude, float pTotalTime, float weight)
protected void ApplyHorizontalNoise (out float x_axis, out float y_axis, float smooth_time, float max_velocity_low, float max_velocity_high, float velocity_modifier, float max_distance, float weight, float pDt)
protected void ApplyShakes (out float x_axis, out float y_axis, int level)
protected float CalculateWeight (int stance_index, float current_stamina, float camera_sway_modifier, bool holding_breath)
void DbgPrintAimingImplement (string val)
Private Attributes
protected const float SWAY_WEIGHT_SCALER = 1
protected float m_HorizontalNoise
protected float m_HorizontalTargetValue
protected float m_HorizontalNoiseVelocity [1] = {0}
protected DayZPlayerImplement m_PlayerDpi
protected PlayerBase m_PlayerPb
protected float m_TotalTime
protected float m_ReferenceTime = 0
protected float m_SwayStateStartTime
protected float m_LastSwayMultiplier = PlayerSwayConstants.SWAY_MULTIPLIER_DEFAULT
protected float m_StateStartSwayMultiplier
protected float m_HorizontalNoiseXAxisOffset
protected float m_BreathingXAxisOffset
protected float m_BreathingYAxisOffset
protected bool m_HoldingBreathSet
protected bool m_AimNoiseAllowed = true
protected bool m_ProceduralRecoilEnabled = true
protected ref RecoilBase m_CurrentRecoil
protected int m_ShakeCount
protected float m_SwayWeight
protected float m_MaxVelocity
protected ref KuruShake m_KuruShake
protected float m_CamShakeX
protected float m_CamShakeY
protected vector m_SwayModifier = "1 1 1"
protected int m_SwayState = -1
protected float m_StealthAimY_Last
protected float m_FilterVelocityStealthAimY [1] = {0}
Static Private Attributes
static protected float m_AimXClampRanges [] = { -180, -20, 90, 0, -50, 90, 180, -20, 90 }
Detailed Description
Definition at line 31 of file DayZPlayerImplementAiming.c.
Constructor & Destructor Documentation
DayZPlayerImplementAiming()
void DayZPlayerImplementAiming (DayZPlayerImplement player) inline private
Definition at line 72 of file DayZPlayerImplementAiming.c.
References Class::CastTo(), m_PlayerDpi, m_PlayerPb, and UpdateSwayState().
Member Function Documentation
ApplyBreathingPattern()
protected void ApplyBreathingPattern (out float x_axis, out float y_axis, float pAmplitude, float pTotalTime, float weight) inline private
Definition at line 355 of file DayZPlayerImplementAiming.c.
References DbgPrintAimingImplement(), Math::Lerp(), m_BreathingXAxisOffset, m_BreathingYAxisOffset, m_LastSwayMultiplier, and Math::Sin().
Referenced by ProcessAimFilters().
ApplyHorizontalNoise()
protected void ApplyHorizontalNoise (out float x_axis, out float y_axis, float smooth_time, float max_velocity_low, float max_velocity_high, float velocity_modifier, float max_distance, float weight, float pDt) inline private
Definition at line 376 of file DayZPlayerImplementAiming.c.
References Math::AbsFloat(), Math::Lerp(), m_HorizontalNoise, m_HorizontalNoiseVelocity, m_HorizontalNoiseXAxisOffset, m_HorizontalTargetValue, m_LastSwayMultiplier, m_MaxVelocity, m_PlayerPb, and Math::SmoothCD().
Referenced by ProcessAimFilters().
ApplyShakes()
protected void ApplyShakes (out float x_axis, out float y_axis, int level) inline private
Definition at line 394 of file DayZPlayerImplementAiming.c.
References m_PlayerPb, m_ShakeCount, and Math::Round().
Referenced by ProcessAimFilters().
CalculateSwayMultiplier()
protected float CalculateSwayMultiplier () inline private
Definition at line 295 of file DayZPlayerImplementAiming.c.
References Math::Clamp(), Math::Lerp(), m_LastSwayMultiplier, m_PlayerPb, m_ReferenceTime, m_SwayStateStartTime, m_TotalTime, and UpdateSwayState().
Referenced by ProcessAimFilters().
CalculateWeight()
protected float CalculateWeight (int stance_index, float current_stamina, float camera_sway_modifier, bool holding_breath) inline private
Definition at line 409 of file DayZPlayerImplementAiming.c.
References DbgPrintAimingImplement(), m_AimNoiseAllowed, m_PlayerDpi, and SWAY_WEIGHT_SCALER.
Referenced by ProcessAimFilters().
DbgPrintAimingImplement()
void DbgPrintAimingImplement (string val) inline private
Definition at line 443 of file DayZPlayerImplementAiming.c.
References GetDayZGame(), IsAimLogEnabled(), and Print().
Referenced by ApplyBreathingPattern(), CalculateWeight(), and ProcessAimFilters().
GetCurrentSwayState()
int GetCurrentSwayState () inline private
Definition at line 350 of file DayZPlayerImplementAiming.c.
References m_SwayState.
GetSwayWeight()
float GetSwayWeight () inline private
Definition at line 121 of file DayZPlayerImplementAiming.c.
References m_SwayWeight.
IsAimNoiseAllowed()
bool IsAimNoiseAllowed () inline private
Definition at line 131 of file DayZPlayerImplementAiming.c.
References m_AimNoiseAllowed.
IsProceduralRecoilEnabled()
bool IsProceduralRecoilEnabled () inline private
Definition at line 141 of file DayZPlayerImplementAiming.c.
References m_ProceduralRecoilEnabled.
OnFinisherBegin()
void OnFinisherBegin (float currentAimY) inline private
Definition at line 102 of file DayZPlayerImplementAiming.c.
References m_FilterVelocityStealthAimY, and m_StealthAimY_Last.
OnRaiseBegin()
void OnRaiseBegin (DayZPlayerImplement player) inline private
Definition at line 93 of file DayZPlayerImplementAiming.c.
References m_SwayModifier.
OnSwayStateChange()
void OnSwayStateChange (int state) inline private
Definition at line 108 of file DayZPlayerImplementAiming.c.
References m_PlayerPb.
Referenced by UpdateSwayState().
ProcessAimFilters()
bool ProcessAimFilters (float pDt, SDayZPlayerAimingModel pModel, int stance_index) inline private
get sway
get recoil
hands offset
cam offset
clamp aim ranges
mouse offset
Definition at line 159 of file DayZPlayerImplementAiming.c.
References ApplyBreathingPattern(), ApplyHorizontalNoise(), ApplyShakes(), CalculateSwayMultiplier(), CalculateWeight(), DbgPrintAimingImplement(), DayZPlayerUtils::LinearRangeClamp(), m_AimXClampRanges, m_BreathingXAxisOffset, m_BreathingYAxisOffset, m_CamShakeX, m_CamShakeY, m_CurrentRecoil, SDayZPlayerAimingModel::m_fAimXCamOffset, SDayZPlayerAimingModel::m_fAimXHandsOffset, SDayZPlayerAimingModel::m_fAimXMouseShift, SDayZPlayerAimingModel::m_fAimYCamOffset, SDayZPlayerAimingModel::m_fAimYHandsOffset, SDayZPlayerAimingModel::m_fAimYMouseShift, SDayZPlayerAimingModel::m_fCurrentAimX, SDayZPlayerAimingModel::m_fCurrentAimY, m_HoldingBreathSet, m_HorizontalNoiseXAxisOffset, m_KuruShake, m_LastSwayMultiplier, m_PlayerDpi, m_PlayerPb, m_ReferenceTime, m_SwayModifier, m_SwayWeight, m_TotalTime, KuruShake::Update(), and RecoilBase::Update().
ProcessStealthFilters()
bool ProcessStealthFilters (float pDt, SDayZPlayerAimingModel pModel) inline private
Definition at line 152 of file DayZPlayerImplementAiming.c.
References SDayZPlayerAimingModel::m_fAimYMouseShift, SDayZPlayerAimingModel::m_fCurrentAimY, m_FilterVelocityStealthAimY, m_StealthAimY_Last, and Math::SmoothCD().
RequestKuruShake()
void RequestKuruShake (float amount) inline private
Definition at line 87 of file DayZPlayerImplementAiming.c.
References m_KuruShake, and m_PlayerPb.
SetAimNoiseAllowed()
void SetAimNoiseAllowed (bool state) inline private
Definition at line 126 of file DayZPlayerImplementAiming.c.
References m_AimNoiseAllowed.
SetCamShakeValues()
void SetCamShakeValues (float x_axis, float y_axis) inline private
Definition at line 146 of file DayZPlayerImplementAiming.c.
References m_CamShakeX, and m_CamShakeY.
SetProceduralRecoilEnabled()
void SetProceduralRecoilEnabled (bool state) inline private
Definition at line 136 of file DayZPlayerImplementAiming.c.
References m_ProceduralRecoilEnabled.
SetRecoil()
void SetRecoil (Weapon_Base weapon) inline private
Definition at line 79 of file DayZPlayerImplementAiming.c.
References m_CurrentRecoil, m_ProceduralRecoilEnabled, and Weapon_Base::SpawnRecoilObject().
UpdateSwayState()
protected bool UpdateSwayState (int state) inline private
Definition at line 336 of file DayZPlayerImplementAiming.c.
References m_LastSwayMultiplier, m_StateStartSwayMultiplier, m_SwayState, m_SwayStateStartTime, m_TotalTime, and OnSwayStateChange().
Referenced by CalculateSwayMultiplier(), and DayZPlayerImplementAiming().
Field Documentation
m_AimNoiseAllowed
protected bool m_AimNoiseAllowed = true private
Definition at line 55 of file DayZPlayerImplementAiming.c.
Referenced by CalculateWeight(), IsAimNoiseAllowed(), and SetAimNoiseAllowed().
m_AimXClampRanges
protected float m_AimXClampRanges[] = { -180, -20, 90, 0, -50, 90, 180, -20, 90 } static private
Definition at line 70 of file DayZPlayerImplementAiming.c.
Referenced by ProcessAimFilters().
m_BreathingXAxisOffset
protected float m_BreathingXAxisOffset private
Definition at line 52 of file DayZPlayerImplementAiming.c.
Referenced by ApplyBreathingPattern(), and ProcessAimFilters().
m_BreathingYAxisOffset
protected float m_BreathingYAxisOffset private
Definition at line 53 of file DayZPlayerImplementAiming.c.
Referenced by ApplyBreathingPattern(), and ProcessAimFilters().
m_CamShakeX
protected float m_CamShakeX private
Definition at line 62 of file DayZPlayerImplementAiming.c.
Referenced by ProcessAimFilters(), and SetCamShakeValues().
m_CamShakeY
protected float m_CamShakeY private
Definition at line 63 of file DayZPlayerImplementAiming.c.
Referenced by ProcessAimFilters(), and SetCamShakeValues().
m_CurrentRecoil
protected ref RecoilBase m_CurrentRecoil private
Definition at line 57 of file DayZPlayerImplementAiming.c.
Referenced by ProcessAimFilters(), and SetRecoil().
m_FilterVelocityStealthAimY
protected float m_FilterVelocityStealthAimY[1] = {0} private
Definition at line 68 of file DayZPlayerImplementAiming.c.
Referenced by OnFinisherBegin(), and ProcessStealthFilters().
m_HoldingBreathSet
protected bool m_HoldingBreathSet private
Definition at line 54 of file DayZPlayerImplementAiming.c.
Referenced by ProcessAimFilters().
m_HorizontalNoise
protected float m_HorizontalNoise private
Definition at line 40 of file DayZPlayerImplementAiming.c.
Referenced by ApplyHorizontalNoise().
m_HorizontalNoiseVelocity
protected float m_HorizontalNoiseVelocity[1] = {0} private
Definition at line 42 of file DayZPlayerImplementAiming.c.
Referenced by ApplyHorizontalNoise().
m_HorizontalNoiseXAxisOffset
protected float m_HorizontalNoiseXAxisOffset private
Definition at line 51 of file DayZPlayerImplementAiming.c.
Referenced by ApplyHorizontalNoise(), and ProcessAimFilters().
m_HorizontalTargetValue
protected float m_HorizontalTargetValue private
Definition at line 41 of file DayZPlayerImplementAiming.c.
Referenced by ApplyHorizontalNoise().
m_KuruShake
protected ref KuruShake m_KuruShake private
Definition at line 61 of file DayZPlayerImplementAiming.c.
Referenced by ProcessAimFilters(), and RequestKuruShake().
m_LastSwayMultiplier
protected float m_LastSwayMultiplier = PlayerSwayConstants.SWAY_MULTIPLIER_DEFAULT private
Definition at line 49 of file DayZPlayerImplementAiming.c.
Referenced by ApplyBreathingPattern(), ApplyHorizontalNoise(), CalculateSwayMultiplier(), ProcessAimFilters(), and UpdateSwayState().
m_MaxVelocity
protected float m_MaxVelocity private
Definition at line 60 of file DayZPlayerImplementAiming.c.
Referenced by ApplyHorizontalNoise().
m_PlayerDpi
protected DayZPlayerImplement m_PlayerDpi private
Definition at line 43 of file DayZPlayerImplementAiming.c.
Referenced by CalculateWeight(), DayZPlayerImplementAiming(), and ProcessAimFilters().
m_PlayerPb
protected PlayerBase m_PlayerPb private
Definition at line 44 of file DayZPlayerImplementAiming.c.
Referenced by ApplyHorizontalNoise(), ApplyShakes(), CalculateSwayMultiplier(), DayZPlayerImplementAiming(), OnSwayStateChange(), ProcessAimFilters(), and RequestKuruShake().
m_ProceduralRecoilEnabled
protected bool m_ProceduralRecoilEnabled = true private
Definition at line 56 of file DayZPlayerImplementAiming.c.
Referenced by IsProceduralRecoilEnabled(), SetProceduralRecoilEnabled(), and SetRecoil().
m_ReferenceTime
protected float m_ReferenceTime = 0 private
Definition at line 46 of file DayZPlayerImplementAiming.c.
Referenced by CalculateSwayMultiplier(), and ProcessAimFilters().
m_ShakeCount
protected int m_ShakeCount private
Definition at line 58 of file DayZPlayerImplementAiming.c.
Referenced by ApplyShakes().
m_StateStartSwayMultiplier
protected float m_StateStartSwayMultiplier private
Definition at line 50 of file DayZPlayerImplementAiming.c.
Referenced by UpdateSwayState().
m_StealthAimY_Last
protected float m_StealthAimY_Last private
Definition at line 67 of file DayZPlayerImplementAiming.c.
Referenced by OnFinisherBegin(), and ProcessStealthFilters().
m_SwayModifier
protected vector m_SwayModifier = "1 1 1" private
Definition at line 64 of file DayZPlayerImplementAiming.c.
Referenced by OnRaiseBegin(), and ProcessAimFilters().
m_SwayState
protected int m_SwayState = -1 private
Definition at line 65 of file DayZPlayerImplementAiming.c.
Referenced by GetCurrentSwayState(), and UpdateSwayState().
m_SwayStateStartTime
protected float m_SwayStateStartTime private
Definition at line 47 of file DayZPlayerImplementAiming.c.
Referenced by CalculateSwayMultiplier(), and UpdateSwayState().
m_SwayWeight
protected float m_SwayWeight private
Definition at line 59 of file DayZPlayerImplementAiming.c.
Referenced by GetSwayWeight(), and ProcessAimFilters().
m_TotalTime
protected float m_TotalTime private
Definition at line 45 of file DayZPlayerImplementAiming.c.
Referenced by CalculateSwayMultiplier(), ProcessAimFilters(), and UpdateSwayState().
SWAY_WEIGHT_SCALER
protected const float SWAY_WEIGHT_SCALER = 1 private
This HeadingModel - Clamps heading
Definition at line 39 of file DayZPlayerImplementAiming.c.
Referenced by CalculateWeight().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/DayZPlayerImplementAiming.c