DayZ: ReplaceWithNewReciveCargoLambda Class Reference
ReplaceWithNewReciveCargoLambda Class Reference
Private Member Functions
void ReplaceWithNewReciveCargoLambda (EntityAI old_item, string new_item_type, PlayerBase player, EntityAI item_to_cargo)
override void OnSuccess (EntityAI new_item)
Private Attributes
protected EntityAI m_ItemToCargo
Detailed Description
Definition at line 128 of file ActionPackGift.c.
Constructor & Destructor Documentation
ReplaceWithNewReciveCargoLambda()
void ReplaceWithNewReciveCargoLambda (EntityAI old_item, string new_item_type, PlayerBase player, EntityAI item_to_cargo) inline private
Definition at line 131 of file ActionPackGift.c.
References m_ItemToCargo.
Member Function Documentation
OnSuccess()
override void OnSuccess (EntityAI new_item) inline private
Definition at line 136 of file ActionPackGift.c.
References GetGame(), InventoryLocation::IsValid(), m_ItemToCargo, m_Player, and InventoryLocation::SetCargo().
Field Documentation
m_ItemToCargo
protected EntityAI m_ItemToCargo private
Definition at line 130 of file ActionPackGift.c.
Referenced by OnSuccess(), and ReplaceWithNewReciveCargoLambda().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Continuous/ActionPackGift.c