DayZ Scripts: SoundParams Class Reference
SoundParams Class Reference
Private Member Functions
void SoundParams (string name)
proto native bool Load (string name)
proto native bool IsValid ()
proto string GetName ()
Detailed Description
Definition at line 72 of file Sound.c.
Constructor & Destructor Documentation
SoundParams()
void SoundParams (string name) private
Member Function Documentation
GetName()
proto string GetName () private
Referenced by SEffectManager::PlaySoundCachedParams().
IsValid()
proto native bool IsValid () private
Referenced by GetBuilder(), EffectSound::IsSoundValid(), LoadVegetationSounds(), DayZInfected::ProcessVoiceFX(), and EffectSound::SoundLoadEx().
Load()
proto native bool Load (string name) private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Sound.c