DayZ Scripts: EffVehicleSmoke Class Reference
EffVehicleSmoke Class Reference
Private Member Functions
void EffVehicleSmoke ()
void SetParticleStateLight ()
void SetParticleStateHeavy ()
void SetParticleState (int state)
Detailed Description
Definition at line 1 of file VehicleSmoke.c.
Constructor & Destructor Documentation
EffVehicleSmoke()
void EffVehicleSmoke () inline private
Definition at line 3 of file VehicleSmoke.c.
References SetParticleStateLight().
Member Function Documentation
SetParticleState()
void SetParticleState (int state) inline private
Definition at line 20 of file VehicleSmoke.c.
References IsPlaying(), EffectParticle::SetParticleID(), EffectParticle::Start(), and EffectParticle::Stop().
Referenced by EffEngineSmoke::Event_OnFrameUpdate(), SetParticleStateHeavy(), EffCoolantSteam::SetParticleStateHeavy(), EffEngineSmoke::SetParticleStateHeavy(), SetParticleStateLight(), EffCoolantSteam::SetParticleStateLight(), EffEngineSmoke::SetParticleStateLight(), and EffExhaustSmoke::SetParticleStateLight().
SetParticleStateHeavy()
void SetParticleStateHeavy () inline private
Definition at line 15 of file VehicleSmoke.c.
References ParticleList::HATCHBACK_COOLANT_OVERHEATED, and SetParticleState().
Referenced by CreateCarDestroyedEffect(), and EOnPostSimulate().
SetParticleStateLight()
void SetParticleStateLight () inline private
Definition at line 9 of file VehicleSmoke.c.
References ParticleList::HATCHBACK_COOLANT_OVERHEATING, and SetParticleState().
Referenced by EffVehicleSmoke(), and EOnPostSimulate().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Effects/EffectParticle/VehicleSmoke.c