DayZ: DisinfectantAlcohol Class Reference
DisinfectantAlcohol Class Reference
Private Member Functions
override void InitItemVariables ()
override float GetDisinfectQuantity (int system=0, Param param1=null)
override void SetActions ()
Detailed Description
Definition at line 1 of file DisinfectantAlcohol.c.
Member Function Documentation
GetDisinfectQuantity()
override float GetDisinfectQuantity (int system = 0, Param param1 = null) inline private
Definition at line 10 of file DisinfectantAlcohol.c.
References GetQuantityMax().
InitItemVariables()
override void InitItemVariables () inline private
Definition at line 4 of file DisinfectantAlcohol.c.
References can_this_be_combined.
SetActions()
override void SetActions () inline private
Definition at line 16 of file DisinfectantAlcohol.c.
References ActionDisinfectSelf(), and AddAction().
The documentation for this class was generated from the following file:
4_World/Entities/ItemBase/Gear/Medical/DisinfectantAlcohol.c