DayZ: ActionManagerServer Class Reference
ActionManagerServer Class Reference
Private Member Functions
void ActionManagerServer (PlayerBase player)
override void OnJumpStart ()
override bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
override void StartDeliveredAction ()
override void OnActionEnd ()
override void Update (int pCurrentCommandID)
override void Interrupt ()
override ActionReciveData GetReciveData ()
Private Attributes
protected ActionBase m_PendingAction
ref ActionReciveData m_PendingActionReciveData
Detailed Description
Definition at line 1 of file ActionManagerServer.c.
Constructor & Destructor Documentation
ActionManagerServer()
void ActionManagerServer (PlayerBase player) inline private
Definition at line 6 of file ActionManagerServer.c.
References m_PendingAction, and m_PendingActionReciveData.
Member Function Documentation
GetReciveData()
override ActionReciveData GetReciveData () inline private
Definition at line 334 of file ActionManagerServer.c.
References m_PendingActionReciveData.
Interrupt()
override void Interrupt () inline private
Definition at line 328 of file ActionManagerServer.c.
References m_CurrentActionData, m_Player, and DayZPlayerSyncJunctures::SendActionInterrupt().
OnActionEnd()
override void OnActionEnd () inline private
Definition at line 186 of file ActionManagerServer.c.
References CGame::ClearJuncture(), GetGame(), m_CurrentActionData, ActionData::m_Player, and ActionData::m_Target.
Referenced by OnJumpStart(), and Update().
OnInputUserDataProcess()
override bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx) inline private
Definition at line 31 of file ActionManagerServer.c.
References ActionBase(), GetAction(), INPUT_UDT_STANDARD_ACTION_END_REQUEST, INPUT_UDT_STANDARD_ACTION_INPUT_END, INPUT_UDT_STANDARD_ACTION_START, m_ActionInputWantEnd, m_ActionWantEndRequest, m_PendingAction, m_PendingActionAcknowledgmentID, m_PendingActionReciveData, m_Player, Serializer::Read(), DayZPlayerSyncJunctures::SendActionAcknowledgment(), and DayZPlayerSyncJunctures::SendActionInterrupt().
OnJumpStart()
override void OnJumpStart () inline private
Definition at line 15 of file ActionManagerServer.c.
References ActionData::m_Action, m_CurrentActionData, m_PendingActionAcknowledgmentID, ActionData::m_State, OnActionEnd(), UA_AM_ACCEPTED, UA_AM_PENDING, and UA_AM_REJECTED.
StartDeliveredAction()
override void StartDeliveredAction () inline private
error - expected action data
Definition at line 110 of file ActionManagerServer.c.
References ActionBase(), Debug::ActionLog(), ActionTarget, GetGame(), LogManager::IsActionLogEnable(), ActionData::m_Action, m_CurrentActionData, m_Interrupted, ActionData::m_MainItem, m_PendingActionAcknowledgmentID, m_Player, ActionData::m_State, ActionData::m_Target, DayZPlayerSyncJunctures::SendActionAcknowledgment(), DayZPlayerSyncJunctures::SendActionInterrupt(), UA_AM_ACCEPTED, and UA_AM_PENDING.
Referenced by Update().
Update()
override void Update (int pCurrentCommandID) inline private
Definition at line 205 of file ActionManagerServer.c.
References Debug::ActionLog(), ActionPossibilityCheck(), ActionTarget, CGame::ExtendActionJuncture(), GetGame(), LogManager::IsActionLogEnable(), ActionData::m_Action, m_ActionInputWantEnd, m_ActionWantEndRequest, m_CurrentActionData, ActionData::m_MainItem, m_PendingAction, m_PendingActionAcknowledgmentID, m_PendingActionReciveData, m_Player, ActionData::m_Player, ActionData::m_RefreshJunctureTimer, ActionData::m_State, ActionData::m_Target, OnActionEnd(), DayZPlayerSyncJunctures::SendActionAcknowledgment(), DayZPlayerSyncJunctures::SendActionInterrupt(), StartDeliveredAction(), UA_AM_ACCEPTED, UA_AM_PENDING, UA_AM_REJECTED, UA_START, and vector::Zero.
Field Documentation
m_PendingAction
protected ActionBase m_PendingAction private
Definition at line 3 of file ActionManagerServer.c.
Referenced by ActionManagerServer(), OnInputUserDataProcess(), and Update().
m_PendingActionReciveData
ref ActionReciveData m_PendingActionReciveData private
Definition at line 4 of file ActionManagerServer.c.
Referenced by ActionManagerServer(), GetReciveData(), OnInputUserDataProcess(), and Update().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/ActionManagerServer.c