DayZ Scripts: ActionContinuousBaseCB Class Reference
ActionContinuousBaseCB Class Reference
Private Member Functions
bool CancelCondition ()
override void OnAnimationEvent (int pEventID)
override void InitActionComponent ()
override void EndActionComponent ()
void UserEndsAction ()
Private Attributes
bool m_inLoop = false
bool m_callLoopEnd = false
Detailed Description
Definition at line 1 of file ActionContinuousBase.c.
Member Function Documentation
CancelCondition()
bool CancelCondition () inline private
Definition at line 6 of file ActionContinuousBase.c.
References DefaultCancelCondition(), AnimatedActionBase::Do(), GetState(), ActionData::m_Action, ActionBaseCB::m_ActionData, m_callLoopEnd, m_inLoop, ActionBaseCB::m_Interrupted, ActionData::m_State, ActionContinuousBase::OnEndAnimationLoop(), ActionContinuousBase::OnStartAnimationLoop(), STATE_LOOP_LOOP, STATE_LOOP_LOOP2, UA_INITIALIZE, and UA_PROCESSING.
EndActionComponent()
override void EndActionComponent () inline private
Definition at line 90 of file ActionContinuousBase.c.
References ActionContinuousBase::HasAlternativeInterrupt(), ActionData::m_Action, ActionBaseCB::m_ActionData, ActionBaseCB::m_Canceled, ActionData::m_State, ActionBaseCB::SetCommand(), UA_CANCEL, and UA_FINISHED.
Referenced by UserEndsAction().
InitActionComponent()
override void InitActionComponent () inline private
Definition at line 71 of file ActionContinuousBase.c.
References ActionBaseCB::CreateActionComponent(), EnableCancelCondition(), CABase::Init(), ActionData::m_Action, ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, ActionBaseCB::m_Canceled, m_inLoop, ActionBaseCB::m_Interrupted, ActionData::m_Player, ActionBaseCB::m_SoundObject, ActionData::m_State, RegisterAnimationEvent(), UA_ANIM_EVENT, UA_IN_END, UA_IN_START, and UA_INITIALIZE.
OnAnimationEvent()
override void OnAnimationEvent (int pEventID) inline private
Definition at line 40 of file ActionContinuousBase.c.
References ActionData::m_Action, ActionBaseCB::m_ActionData, m_inLoop, ActionBaseCB::m_Interrupted, AnimatedActionBase::OnAnimationEvent(), UA_ANIM_EVENT, UA_IN_END, and UA_IN_START.
UserEndsAction()
void UserEndsAction () inline private
Definition at line 121 of file ActionContinuousBase.c.
References CABase::Cancel(), EndActionComponent(), ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, and ActionData::m_State.
Referenced by ActionContinuousBase::OnEndInput().
Field Documentation
m_callLoopEnd
bool m_callLoopEnd = false private
Definition at line 4 of file ActionContinuousBase.c.
Referenced by CancelCondition().
m_inLoop
bool m_inLoop = false private
Definition at line 3 of file ActionContinuousBase.c.
Referenced by CancelCondition(), InitActionComponent(), and OnAnimationEvent().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/ActionContinuousBase.c