DayZ: ThirstMdfr Class Reference
ThirstMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnReconnect (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
float m_LastWaterLevel
ref HumanMovementState m_MovementState = new HumanMovementState()
Detailed Description
Definition at line 1 of file Thirst.c.
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
Definition at line 15 of file Thirst.c.
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
Definition at line 25 of file Thirst.c.
Init()
override void Init () inline private
Definition at line 6 of file Thirst.c.
References DEFAULT_TICK_TIME_INACTIVE, DisableDeactivateCheck(), m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnReconnect()
override void OnReconnect (PlayerBase player) inline private
Definition at line 20 of file Thirst.c.
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
Definition at line 30 of file Thirst.c.
References PlayerConstants::CONSUMPTION_MULTIPLIER_BASE, PlayerConstants::LOW_WATER_DAMAGE_PER_SEC, PlayerConstants::LOW_WATER_THRESHOLD, HumanMovementState::m_iMovement, m_MovementState, PlayerStomach(), and PlayerConstants::SL_WATER_MAX.
Field Documentation
m_LastWaterLevel
float m_LastWaterLevel private
Definition at line 3 of file Thirst.c.
m_MovementState
ref HumanMovementState m_MovementState = new HumanMovementState() private
Definition at line 4 of file Thirst.c.
Referenced by OnTick().
The documentation for this class was generated from the following file:
4_World/Classes/PlayerModifiers/Modifiers/Thirst.c