DayZ: FlammableBase Class Reference
FlammableBase Class Reference
Private Member Functions
void FlammableBase ()
override void DeferredInit ()
void Init ()
override void EEInit ()
override vector GetUniversalTemperatureSourcePosition ()
override void EEDelete (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanPutInCargo (EntityAI parent)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
bool CanBeTakenAsCargo ()
override bool IsIgnited ()
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
void UpdateCheckForReceivingUpgrade ()
override void OnIgnitedThis (EntityAI fire_source)
override void OnSwitchOn ()
override void OnSwitchOff ()
void SetTorchDecraftResult (string type)
bool ConsumeRag ()
void ConsumeLard (Lard lard)
void Upgrade (ItemBase source)
void ConsumeFuelFromBottle (ItemBase vessel)
void ConsumeFuelFromGasStation ()
void RuinRags ()
override void OnInventoryExit (Man player)
bool StandUp ()
void CalculateQuantity ()
bool CanReceiveUpgrade ()
void CraftingInit (float quantity)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
bool CanTransformIntoStick ()
void TryTransformIntoStick ()
override void OnWorkStart ()
void StopAllParticles ()
Rag GetRag ()
void LockRags (bool do_lock)
void UpdateLight ()
override void OnItemInHandsPlayerSwimStart (PlayerBase player)
override void OnWork (float consumed_energy)
string GetSoundName ()
void UpdateParticle ()
override void OnWorkStop ()
override int GetMeleeMode ()
override int GetMeleeHeavyMode ()
override int GetMeleeSprintMode ()
override void SetActions ()
override void OnAttachmentQuantityChangedEx (ItemBase item, float delta)
override bool DisassembleOnLastDetach ()
override void OnDebugSpawn ()
int GetRagQuantity ()
string GetBurningMaterial ()
string GetBurntMaterial ()
void UpdateMaterial ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void ApplyResultModifications (ItemBase result)
Private Attributes
private SoundOnVehicle m_LoopSoundEntity
Particle m_FireParticle
bool m_CanReceiveUpgrade
bool m_IsBeingDestructed = false
float m_BurnTimePerRagEx
float m_BurnTimePerFullLardEx
float m_BurnTimePerFullFuelDoseEx
float m_MaxConsumableLardQuantityEx
float m_MaxConsumableFuelQuantityEx
float m_WaterEvaporationByFireIntensityEx = 0.001
int m_StartFadeOutOfLightAtQuantityEx = 3
int m_RagsUpgradedCount
bool m_ConsumeRagFlipFlop
vector m_ParticleLocalPos = Vector(0, 0.50, 0)
string m_DecraftResult = "WoodenStick"
TorchLight m_Light
bool m_WasLit
protected ref UniversalTemperatureSource m_UTSource
protected ref UniversalTemperatureSourceSettings m_UTSSettings
protected ref UniversalTemperatureSourceLambdaConstant m_UTSLConstant
Detailed Description
Definition at line 1 of file Torch.c.
Constructor & Destructor Documentation
FlammableBase()
void FlammableBase () inline private
Definition at line 3 of file Torch.c.
References Init().
Member Function Documentation
ApplyResultModifications()
void ApplyResultModifications (ItemBase result) inline private
Definition at line 849 of file Torch.c.
Referenced by TorchLambda::CopyOldPropertiesToNew(), and TryTransformIntoStick().
CalculateQuantity()
void CalculateQuantity () inline private
Definition at line 413 of file Torch.c.
References GetGame(), and SetQuantityNormalized().
Referenced by ConsumeFuelFromBottle(), ConsumeFuelFromGasStation(), ConsumeLard(), EEItemAttached(), EEItemDetached(), OnAttachmentQuantityChangedEx(), OnDebugSpawn(), OnWork(), OnWorkStop(), and Upgrade().
CanBeIgnitedBy()
override bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 151 of file Torch.c.
References GetEnergy(), and GetRag().
CanBeTakenAsCargo()
bool CanBeTakenAsCargo () inline private
Definition at line 129 of file Torch.c.
Referenced by CanPutInCargo(), and CanRemoveFromCargo().
CanIgniteItem()
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 140 of file Torch.c.
CanPutAsAttachment()
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 124 of file Torch.c.
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 106 of file Torch.c.
References CanBeTakenAsCargo().
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 97 of file Torch.c.
References ItemBase::CanReceiveAttachment().
CanReceiveUpgrade()
bool CanReceiveUpgrade () inline private
Definition at line 421 of file Torch.c.
References m_CanReceiveUpgrade.
Referenced by RecipeBase::CanDo().
CanReleaseAttachment()
override bool CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 112 of file Torch.c.
CanRemoveFromCargo()
override bool CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 119 of file Torch.c.
References CanBeTakenAsCargo().
CanTransformIntoStick()
bool CanTransformIntoStick () inline private
Definition at line 462 of file Torch.c.
References GetGame(), GetRag(), and IsIgnited().
Referenced by TryTransformIntoStick().
ConsumeFuelFromBottle()
void ConsumeFuelFromBottle (ItemBase vessel) inline private
Definition at line 322 of file Torch.c.
References CalculateQuantity(), m_BurnTimePerFullFuelDoseEx, m_MaxConsumableFuelQuantityEx, and UpdateCheckForReceivingUpgrade().
ConsumeFuelFromGasStation()
void ConsumeFuelFromGasStation () inline private
Definition at line 356 of file Torch.c.
References CalculateQuantity(), m_BurnTimePerFullFuelDoseEx, and UpdateCheckForReceivingUpgrade().
ConsumeLard()
void ConsumeLard (Lard lard) inline private
Definition at line 251 of file Torch.c.
References CalculateQuantity(), m_BurnTimePerFullLardEx, m_MaxConsumableLardQuantityEx, and UpdateCheckForReceivingUpgrade().
ConsumeRag()
bool ConsumeRag () inline private
Definition at line 231 of file Torch.c.
References GetRag(), and LockRags().
Referenced by OnIgnitedThis(), and OnWork().
CraftingInit()
void CraftingInit (float quantity) inline private
Definition at line 426 of file Torch.c.
References m_BurnTimePerRagEx, and m_CanReceiveUpgrade.
Referenced by OnDebugSpawn().
DeferredInit()
override void DeferredInit () inline private
Definition at line 33 of file Torch.c.
References LockRags(), and m_RagsUpgradedCount.
DisassembleOnLastDetach()
override bool DisassembleOnLastDetach () inline private
Definition at line 772 of file Torch.c.
EEDelete()
override void EEDelete (EntityAI parent) inline private
Definition at line 86 of file Torch.c.
References GetGame(), m_LoopSoundEntity, CGame::ObjectDelete(), and StopAllParticles().
EEInit()
override void EEInit () inline private
Definition at line 55 of file Torch.c.
References GetGame(), UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, UniversalTemperatureSourceSettings::m_Updateable, UniversalTemperatureSourceSettings::m_UpdateInterval, m_UTSLConstant, m_UTSource, and m_UTSSettings.
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 434 of file Torch.c.
References CalculateQuantity(), and UpdateCheckForReceivingUpgrade().
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 442 of file Torch.c.
References CalculateQuantity(), CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), ECE_PLACE_ON_SURFACE, CGame::GetCallQueue(), GetGame(), GetPosition, m_IsBeingDestructed, TryTransformIntoStick(), and UpdateCheckForReceivingUpgrade().
GetBurningMaterial()
string GetBurningMaterial () inline private
Definition at line 793 of file Torch.c.
Referenced by UpdateMaterial().
GetBurntMaterial()
string GetBurntMaterial () inline private
Definition at line 798 of file Torch.c.
Referenced by UpdateMaterial().
GetMeleeHeavyMode()
override int GetMeleeHeavyMode () inline private
Definition at line 736 of file Torch.c.
GetMeleeMode()
override int GetMeleeMode () inline private
Definition at line 728 of file Torch.c.
GetMeleeSprintMode()
override int GetMeleeSprintMode () inline private
Definition at line 744 of file Torch.c.
GetRag()
Rag GetRag () inline private
Definition at line 529 of file Torch.c.
Referenced by CanBeIgnitedBy(), CanTransformIntoStick(), ConsumeRag(), GetRagQuantity(), LockRags(), OnWork(), OnWorkStop(), RuinRags(), and Upgrade().
GetRagQuantity()
int GetRagQuantity () inline private
Definition at line 784 of file Torch.c.
References GetQuantity(), GetRag(), and Math::Round().
Referenced by OnDebugSpawn(), OnWork(), OnWorkStop(), UpdateCheckForReceivingUpgrade(), and Upgrade().
GetSoundName()
string GetSoundName () inline private
Definition at line 653 of file Torch.c.
Referenced by OnWork().
GetUniversalTemperatureSourcePosition()
override vector GetUniversalTemperatureSourcePosition () inline private
Definition at line 76 of file Torch.c.
HasFlammableMaterial()
override bool HasFlammableMaterial () inline private
Definition at line 145 of file Torch.c.
Init()
void Init () inline private
Definition at line 41 of file Torch.c.
References CGame::ConfigGetFloat(), GetGame(), GetType(), m_BurnTimePerFullFuelDoseEx, m_BurnTimePerFullLardEx, m_BurnTimePerRagEx, m_MaxConsumableFuelQuantityEx, and m_MaxConsumableLardQuantityEx.
Referenced by FlammableBase().
IsIgnited()
override bool IsIgnited () inline private
Definition at line 135 of file Torch.c.
Referenced by RecipeBase::CanDo(), BroomBase::CanTransformIntoStick(), and CanTransformIntoStick().
LockRags()
void LockRags (bool do_lock) inline private
Definition at line 534 of file Torch.c.
References GetRag(), and m_RagsUpgradedCount.
Referenced by ConsumeRag(), DeferredInit(), OnWasAttached(), OnWasDetached(), OnWorkStart(), OnWorkStop(), and Upgrade().
OnAttachmentQuantityChangedEx()
override void OnAttachmentQuantityChangedEx (ItemBase item, float delta) inline private
Definition at line 760 of file Torch.c.
References CalculateQuantity(), m_BurnTimePerRagEx, and UpdateCheckForReceivingUpgrade().
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 777 of file Torch.c.
References CalculateQuantity(), CraftingInit(), and GetRagQuantity().
OnIgnitedThis()
override void OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 195 of file Torch.c.
References ConsumeRag().
Referenced by BroomBase::OnDebugButtonPressServer().
OnInventoryExit()
override void OnInventoryExit (Man player) inline private
Definition at line 385 of file Torch.c.
References StandUp().
OnItemInHandsPlayerSwimStart()
override void OnItemInHandsPlayerSwimStart (PlayerBase player) inline private
Definition at line 591 of file Torch.c.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 832 of file Torch.c.
References m_WasLit, Serializer::Read(), and UpdateMaterial().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 825 of file Torch.c.
References m_WasLit, and Serializer::Write().
OnSwitchOff()
override void OnSwitchOff () inline private
Definition at line 218 of file Torch.c.
References GetGame(), and m_UTSource.
OnSwitchOn()
override void OnSwitchOn () inline private
Definition at line 205 of file Torch.c.
References GetGame(), and m_UTSource.
OnWork()
override void OnWork (float consumed_energy) inline private
Definition at line 597 of file Torch.c.
References AddWet(), CalculateQuantity(), ConsumeRag(), GetEnergy(), GetGame(), GetRag(), GetRagQuantity(), GetSoundName(), m_BurnTimePerRagEx, m_ConsumeRagFlipFlop, m_LoopSoundEntity, m_RagsUpgradedCount, m_WaterEvaporationByFireIntensityEx, PlaySoundLoop(), RuinRags(), UpdateCheckForReceivingUpgrade(), UpdateLight(), UpdateMaterial(), and UpdateParticle().
OnWorkStart()
override void OnWorkStart () inline private
Definition at line 514 of file Torch.c.
References LockRags(), m_WasLit, and UpdateMaterial().
OnWorkStop()
override void OnWorkStop () inline private
Definition at line 692 of file Torch.c.
References CalculateQuantity(), GetEnergy(), GetGame(), GetRag(), GetRagQuantity(), LockRags(), m_FireParticle, m_Light, m_LoopSoundEntity, CGame::ObjectDelete(), Particle::Stop(), TryTransformIntoStick(), UpdateCheckForReceivingUpgrade(), and UpdateMaterial().
RuinRags()
void RuinRags () inline private
Definition at line 374 of file Torch.c.
References GetRag().
Referenced by OnWork(), and Upgrade().
SetActions()
override void SetActions () inline private
Definition at line 752 of file Torch.c.
References ActionLightItemOnFire(), and AddAction().
SetTorchDecraftResult()
void SetTorchDecraftResult (string type) inline private
Definition at line 226 of file Torch.c.
References m_DecraftResult.
StandUp()
bool StandUp () inline private
Definition at line 393 of file Torch.c.
References GetGame(), GetPosition, IsRuined(), CGame::IsSurfaceDigable(), Math::RandomFloat(), SetOrientation(), and CGame::SurfaceGetType().
Referenced by OnInventoryExit().
StopAllParticles()
void StopAllParticles () inline private
Definition at line 521 of file Torch.c.
References m_FireParticle, and Particle::Stop().
Referenced by EEDelete(), and TryTransformIntoStick().
TryTransformIntoStick()
void TryTransformIntoStick () inline private
Definition at line 470 of file Torch.c.
References ApplyResultModifications(), CanTransformIntoStick(), ECE_PLACE_ON_SURFACE, GetGame(), GetOrientation(), GetPosition, GetType(), m_DecraftResult, m_IsBeingDestructed, CGame::ObjectDelete(), StopAllParticles(), and Vector().
Referenced by EEItemDetached(), and OnWorkStop().
UpdateCheckForReceivingUpgrade()
void UpdateCheckForReceivingUpgrade () inline private
Definition at line 186 of file Torch.c.
References GetGame(), GetRagQuantity(), m_BurnTimePerRagEx, m_CanReceiveUpgrade, and m_RagsUpgradedCount.
Referenced by ConsumeFuelFromBottle(), ConsumeFuelFromGasStation(), ConsumeLard(), EEItemAttached(), EEItemDetached(), OnAttachmentQuantityChangedEx(), OnStoreLoad(), OnWork(), OnWorkStop(), and Upgrade().
UpdateLight()
void UpdateLight () inline private
Definition at line 550 of file Torch.c.
References Particle::GetDirectParticleEffect(), GetQuantity(), m_FireParticle, m_Light, m_ParticleLocalPos, m_StartFadeOutOfLightAtQuantityEx, and Vector().
Referenced by OnWork().
UpdateMaterial()
void UpdateMaterial () inline private
Definition at line 803 of file Torch.c.
References GetBurningMaterial(), GetBurntMaterial(), GetGame(), and m_WasLit.
Referenced by OnStoreLoad(), OnWork(), OnWorkStart(), and OnWorkStop().
UpdateParticle()
void UpdateParticle () inline private
Definition at line 658 of file Torch.c.
References Particle::GetParticleID(), GetQuantity(), m_FireParticle, m_ParticleLocalPos, ParticleManager(), Particle::ScaleParticleParamFromOriginal(), Particle::Stop(), ParticleList::TORCH_T1, and ParticleList::TORCH_T2.
Referenced by OnWork().
Upgrade()
void Upgrade (ItemBase source) inline private
Definition at line 285 of file Torch.c.
References CalculateQuantity(), Math::Ceil(), GetRag(), GetRagQuantity(), LockRags(), m_BurnTimePerRagEx, m_ConsumeRagFlipFlop, m_RagsUpgradedCount, Math::Max(), Math::Min(), RuinRags(), and UpdateCheckForReceivingUpgrade().
Referenced by RecipeBase::Do().
Field Documentation
m_BurnTimePerFullFuelDoseEx
float m_BurnTimePerFullFuelDoseEx private
Definition at line 15 of file Torch.c.
Referenced by ConsumeFuelFromBottle(), ConsumeFuelFromGasStation(), Init(), and Init().
m_BurnTimePerFullLardEx
float m_BurnTimePerFullLardEx private
Definition at line 14 of file Torch.c.
Referenced by ConsumeLard(), Init(), and Init().
m_BurnTimePerRagEx
float m_BurnTimePerRagEx private
Definition at line 13 of file Torch.c.
Referenced by CraftingInit(), Init(), Init(), OnAttachmentQuantityChangedEx(), OnWork(), UpdateCheckForReceivingUpgrade(), and Upgrade().
m_CanReceiveUpgrade
bool m_CanReceiveUpgrade private
Definition at line 10 of file Torch.c.
Referenced by CanReceiveUpgrade(), CraftingInit(), and UpdateCheckForReceivingUpgrade().
m_ConsumeRagFlipFlop
bool m_ConsumeRagFlipFlop private
Definition at line 22 of file Torch.c.
Referenced by OnWork(), and Upgrade().
m_DecraftResult
string m_DecraftResult = "WoodenStick" private
Definition at line 25 of file Torch.c.
Referenced by BroomBase::Init(), SetTorchDecraftResult(), and TryTransformIntoStick().
m_FireParticle
Particle m_FireParticle private
Definition at line 9 of file Torch.c.
Referenced by OnWorkStop(), StopAllParticles(), UpdateLight(), BroomBase::UpdateParticle(), and UpdateParticle().
m_IsBeingDestructed
bool m_IsBeingDestructed = false private
Definition at line 11 of file Torch.c.
Referenced by EEItemDetached(), and TryTransformIntoStick().
m_Light
TorchLight m_Light private
Definition at line 26 of file Torch.c.
Referenced by OnWorkStop(), and UpdateLight().
m_LoopSoundEntity
private SoundOnVehicle m_LoopSoundEntity private
Definition at line 8 of file Torch.c.
Referenced by EEDelete(), OnWork(), and OnWorkStop().
m_MaxConsumableFuelQuantityEx
float m_MaxConsumableFuelQuantityEx private
Definition at line 17 of file Torch.c.
Referenced by ConsumeFuelFromBottle(), Init(), and Init().
m_MaxConsumableLardQuantityEx
float m_MaxConsumableLardQuantityEx private
Definition at line 16 of file Torch.c.
Referenced by ConsumeLard(), Init(), and Init().
m_ParticleLocalPos
vector m_ParticleLocalPos = Vector(0, 0.50, 0) private
Definition at line 23 of file Torch.c.
Referenced by BroomBase::Init(), UpdateLight(), BroomBase::UpdateParticle(), and UpdateParticle().
m_RagsUpgradedCount
int m_RagsUpgradedCount private
Definition at line 21 of file Torch.c.
Referenced by DeferredInit(), LockRags(), OnWork(), UpdateCheckForReceivingUpgrade(), and Upgrade().
m_StartFadeOutOfLightAtQuantityEx
int m_StartFadeOutOfLightAtQuantityEx = 3 private
Definition at line 19 of file Torch.c.
Referenced by UpdateLight().
m_UTSLConstant
protected ref UniversalTemperatureSourceLambdaConstant m_UTSLConstant private
Definition at line 31 of file Torch.c.
Referenced by EEInit().
m_UTSource
protected ref UniversalTemperatureSource m_UTSource private
Definition at line 29 of file Torch.c.
Referenced by EEInit(), OnSwitchOff(), and OnSwitchOn().
m_UTSSettings
protected ref UniversalTemperatureSourceSettings m_UTSSettings private
Definition at line 30 of file Torch.c.
Referenced by EEInit().
m_WasLit
bool m_WasLit private
Definition at line 27 of file Torch.c.
Referenced by OnStoreLoad(), OnStoreSave(), OnWorkStart(), and UpdateMaterial().
m_WaterEvaporationByFireIntensityEx
float m_WaterEvaporationByFireIntensityEx = 0.001 private
Definition at line 18 of file Torch.c.
Referenced by OnWork().
The documentation for this class was generated from the following file:
4_World/Entities/ItemBase/Torch.c