DayZ: ActionSawPlanks Class Reference
ActionSawPlanks Class Reference
Private Member Functions
void ActionSawPlanks ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
Private Attributes
ItemBase m_Planks
ref InventoryLocation m_PlanksLocation = new InventoryLocation
Static Private Attributes
static const int DECREASE_HEALTH_OF_TOOL_DEFAULT = 10
static const int YIELD = 3
Detailed Description
Definition at line 35 of file ActionSawPlanks.c.
Constructor & Destructor Documentation
ActionSawPlanks()
void ActionSawPlanks () inline private
Definition at line 45 of file ActionSawPlanks.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_MEDIUM.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 62 of file ActionSawPlanks.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 56 of file ActionSawPlanks.c.
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 90 of file ActionSawPlanks.c.
References InventoryLocation::CompareLocationOnly(), InventoryLocation::Copy(), ECE_PLACE_ON_SURFACE, GetGame(), GetSpecialtyWeight(), ActionData::m_MainItem, m_Planks, m_PlanksLocation, ActionData::m_Player, m_SpecialtyWeight, ActionData::m_Target, UADamageApplied::SAW_PLANKS, and YIELD.
Field Documentation
DECREASE_HEALTH_OF_TOOL_DEFAULT
const int DECREASE_HEALTH_OF_TOOL_DEFAULT = 10 static private
Definition at line 37 of file ActionSawPlanks.c.
m_Planks
ItemBase m_Planks private
Definition at line 42 of file ActionSawPlanks.c.
Referenced by OnFinishProgressServer().
m_PlanksLocation
ref InventoryLocation m_PlanksLocation = new InventoryLocation private
Definition at line 43 of file ActionSawPlanks.c.
Referenced by OnFinishProgressServer().
YIELD
const int YIELD = 3 static private
Definition at line 41 of file ActionSawPlanks.c.
Referenced by OnFinishProgressServer().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Continuous/ActionSawPlanks.c