DayZ Scripts Documentation: VicinitySlotsContainer Class Reference
VicinitySlotsContainer Class Reference
Private Member Functions
void VicinitySlotsContainer (LayoutHolder parent)
bool IsItemWithContainerActive ()
override bool IsItemWithQuantityActive ()
override bool IsItemActive ()
bool IsEmptyItemActive ()
override bool IsDisplayable ()
bool IsTakeable ()
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool CanEquip ()
override bool EquipItem ()
override bool InspectItem ()
override bool TransferItem ()
override bool Combine ()
override bool Select ()
void ~VicinitySlotsContainer ()
override void SetLayoutName ()
override void OnShow ()
int GetRowSlotCount ()
bool ExcludeFromContainer (EntityAI item)
Decides on the icon visibility.
void ShowItemsInContainers (array< EntityAI > items)
void DoubleClick (Widget w, int x, int y, int button)
string GetItemQuantityText (EntityAI item)
int HasItemQuantity (EntityAI item)
float GetItemQuantity (InventoryItem item)
void MouseButtonDown (Widget w, int x, int y, int button)
void MouseClick (Widget w, int x, int y, int button)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void RecomputeNumberOfContainers (array< EntityAI > items)
Private Attributes
protected ref AttachmentsGroupContainer m_Container
protected int m_ItemsCount
protected int m_SlotsCount
protected ref array< EntityAI > m_ShowedItems
Detailed Description
Definition at line 1 of file VicinitySlotsContainer.c.
Constructor & Destructor Documentation
VicinitySlotsContainer()
void VicinitySlotsContainer (LayoutHolder parent) inline private
Definition at line 8 of file VicinitySlotsContainer.c.
References SlotsIcon::GetGhostSlot(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), ITEMS_IN_ROW, m_Container, m_Parent, m_ShowedItems, WidgetEventHandler::RegisterOnDoubleClick(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), and WidgetEventHandler::RegisterOnMouseButtonUp().
~VicinitySlotsContainer()
void ~VicinitySlotsContainer () inline private
Definition at line 232 of file VicinitySlotsContainer.c.
References Container::Get(), ITEMS_IN_ROW, and m_Container.
Member Function Documentation
CanCombine()
override bool CanCombine () inline private
Definition at line 76 of file VicinitySlotsContainer.c.
References ItemManager::GetCombinationFlags(), Container::GetFocusedItem(), GetGame(), and GetPlayer().
Referenced by UpdateConsoleToolbar().
CanCombineAmmo()
override bool CanCombineAmmo () inline private
Definition at line 84 of file VicinitySlotsContainer.c.
References ActionManagerClient::CanPerformActionFromInventory(), ActionManagerClient::CanSetActionFromInventory(), Class::CastTo(), Container::GetFocusedItem(), GetGame(), GetPlayer(), and m_player.
Referenced by UpdateConsoleToolbar().
CanEquip()
override bool CanEquip () inline private
Definition at line 95 of file VicinitySlotsContainer.c.
References Container::GetFocusedItem(), GetGame(), and CGame::GetPlayer().
Referenced by UpdateConsoleToolbar().
Combine()
override bool Combine () inline private
Definition at line 157 of file VicinitySlotsContainer.c.
References Icon::CombineItems(), Container::GetFocusedItem(), GetGame(), ItemManager::GetHandsPreview(), HandsPreview::GetIcon(), ItemManager::GetInstance(), and GetPlayer().
DoubleClick()
void DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 354 of file VicinitySlotsContainer.c.
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), InventoryMenu(), ItemBase::IsTakeable(), InventoryLocation::IsValid(), MENU_INVENTORY, name, string::Replace(), and SplitItemUtils::TakeOrSplitToInventoryLocation().
EquipItem()
override bool EquipItem () inline private
Definition at line 110 of file VicinitySlotsContainer.c.
References Container::GetFocusedItem(), GetGame(), and CGame::GetPlayer().
ExcludeFromContainer()
bool ExcludeFromContainer (EntityAI item) inline private
Decides on the icon visibility.
Definition at line 260 of file VicinitySlotsContainer.c.
Referenced by ShowItemsInContainers().
GetItemQuantity()
float GetItemQuantity (InventoryItem item) inline private
Definition at line 487 of file VicinitySlotsContainer.c.
GetItemQuantityText()
string GetItemQuantityText (EntityAI item) inline private
Definition at line 419 of file VicinitySlotsContainer.c.
References Math::Round(), float::ToString(), and string::ToString().
GetRowSlotCount()
int GetRowSlotCount () inline private
Definition at line 254 of file VicinitySlotsContainer.c.
HasItemQuantity()
int HasItemQuantity (EntityAI item) inline private
Definition at line 457 of file VicinitySlotsContainer.c.
References QUANTITY_COUNT, QUANTITY_HIDDEN, and QUANTITY_PROGRESS.
InspectItem()
override bool InspectItem () inline private
Definition at line 126 of file VicinitySlotsContainer.c.
References Container::GetFocusedItem(), and InspectItem().
Referenced by InspectItem(), and MouseClick().
IsDisplayable()
override bool IsDisplayable () inline private
Definition at line 65 of file VicinitySlotsContainer.c.
IsEmptyItemActive()
bool IsEmptyItemActive () inline private
Definition at line 58 of file VicinitySlotsContainer.c.
References Container::GetFocusedItem().
Referenced by UpdateConsoleToolbar().
IsItemActive()
override bool IsItemActive () inline private
Definition at line 52 of file VicinitySlotsContainer.c.
References Container::GetFocusedItem(), IsItemWithContainerActive(), and IsItemWithQuantityActive().
Referenced by UpdateConsoleToolbar().
IsItemWithContainerActive()
bool IsItemWithContainerActive () inline private
Definition at line 39 of file VicinitySlotsContainer.c.
References Container::GetFocusedItem().
Referenced by IsItemActive(), and UpdateConsoleToolbar().
IsItemWithQuantityActive()
override bool IsItemWithQuantityActive () inline private
Definition at line 46 of file VicinitySlotsContainer.c.
References Container::GetFocusedItem(), and QuantityConversions::HasItemQuantity().
Referenced by IsItemActive(), and UpdateConsoleToolbar().
IsTakeable()
bool IsTakeable () inline private
Definition at line 70 of file VicinitySlotsContainer.c.
References Container::GetFocusedItem().
Referenced by UpdateConsoleToolbar().
MouseButtonDown()
void MouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 507 of file VicinitySlotsContainer.c.
References ItemManager::EvaluateContainerDragabilityDefault(), GetDayZGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), IsLeftCtrlDown(), name, string::Replace(), and ItemManager::SetWidgetDraggable().
MouseClick()
void MouseClick (Widget w, int x, int y, int button) inline private
Definition at line 526 of file VicinitySlotsContainer.c.
References Container::Get(), ItemPreviewWidget::GetItem(), InspectItem(), m_Parent, name, InventoryItem::OnRightClick(), and string::Replace().
OnDropReceivedFromHeader()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 560 of file VicinitySlotsContainer.c.
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), name, and string::Replace().
OnShow()
override void OnShow () inline private
Definition at line 249 of file VicinitySlotsContainer.c.
RecomputeNumberOfContainers()
void RecomputeNumberOfContainers (array< EntityAI > items) inline private
Definition at line 597 of file VicinitySlotsContainer.c.
References Container::Get(), SlotsIcon::GetGhostSlot(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), SlotsContainer::GetSlotIcon(), ITEMS_IN_ROW, m_Container, m_Parent, WidgetEventHandler::RegisterOnDoubleClick(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), and WidgetEventHandler::RegisterOnMouseButtonUp().
Referenced by ShowItemsInContainers().
Select()
override bool Select () inline private
Definition at line 172 of file VicinitySlotsContainer.c.
References GameInventory::CanSwapEntitiesEx(), Container::GetFocusedItem(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), GetPlayer(), ItemManager::GetSelectedIcon(), ItemManager::GetSelectedItem(), SlotsIcon::IsOutOfReach(), m_ShowedItems, and ItemManager::SetSelectedItem().
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 244 of file VicinitySlotsContainer.c.
References WidgetLayoutName::Container.
ShowItemsInContainers()
void ShowItemsInContainers (array< EntityAI > items) inline private
Definition at line 266 of file VicinitySlotsContainer.c.
References CancelWidgetDragging(), SlotsIcon::Clear(), ItemManager::EvaluateContainerDragabilityDefault(), ExcludeFromContainer(), Math::Floor(), Container::Get(), GetDragWidget(), SlotsIcon::GetGhostSlot(), ItemManager::GetInstance(), SlotsIcon::GetPanelWidget(), SlotsIcon::GetRadialIconPanel(), SlotsIcon::GetRender(), SlotsContainer::GetSlotIcon(), SlotsIcon::Init(), int, Container::IsDisplayable(), ItemManager::IsDragging(), ITEMS_IN_ROW, m_Container, m_Parent, m_ShowedItems, RecomputeNumberOfContainers(), ItemManager::SetTemperature(), ItemManager::SetWidgetDraggable(), SlotsIcon::UpdateInterval(), Container::UpdateRadialIcon(), and x.
Referenced by VicinityContainer::UpdateInterval().
TransferItem()
override bool TransferItem () inline private
Definition at line 138 of file VicinitySlotsContainer.c.
References Container::GetFocusedItem(), GetGame(), CGame::GetPlayer(), GetPlayer(), ItemBase::IsTakeable(), InventoryLocation::IsValid(), and SplitItemUtils::TakeOrSplitToInventoryLocation().
Field Documentation
m_Container
protected ref AttachmentsGroupContainer m_Container private
Definition at line 3 of file VicinitySlotsContainer.c.
Referenced by RecomputeNumberOfContainers(), ShowItemsInContainers(), VicinitySlotsContainer(), and ~VicinitySlotsContainer().
m_ItemsCount
protected int m_ItemsCount private
Definition at line 4 of file VicinitySlotsContainer.c.
m_ShowedItems
protected ref array<EntityAI> m_ShowedItems private
Definition at line 6 of file VicinitySlotsContainer.c.
Referenced by Select(), ShowItemsInContainers(), and VicinitySlotsContainer().
m_SlotsCount
protected int m_SlotsCount private
Definition at line 5 of file VicinitySlotsContainer.c.
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Inherited/VicinitySlotsContainer.c