DayZ: DeveloperTeleport Class Reference
DeveloperTeleport Class Reference
Static Private Member Functions
static void TeleportAtCursor ()
static void TeleportAtCursorEx ()
static void SetPlayerPosition (PlayerBase player, vector position)
static void SetPlayerDirection (PlayerBase player, vector direction)
static void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx)
static protected void OnRPCSetPlayerPosition (PlayerBase player, ParamsReadContext ctx)
static protected void OnRPCSetPlayerDirection (PlayerBase player, ParamsReadContext ctx)
Static Private Attributes
static protected const float TELEPORT_DISTANCE_MAX = 1000
static protected const float TELEPORT_DISTANCE_MAX_EX = 500
Detailed Description
Definition at line 1 of file DeveloperTeleport.c.
Member Function Documentation
OnRPC()
static void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline static private
Definition at line 108 of file DeveloperTeleport.c.
References OnRPCSetPlayerDirection(), and OnRPCSetPlayerPosition().
Referenced by PluginBase::OnRPC().
OnRPCSetPlayerDirection()
static protected void OnRPCSetPlayerDirection (PlayerBase player, ParamsReadContext ctx) inline static private
Definition at line 135 of file DeveloperTeleport.c.
References Serializer::Read(), and SetPlayerDirection().
Referenced by OnRPC().
OnRPCSetPlayerPosition()
static protected void OnRPCSetPlayerPosition (PlayerBase player, ParamsReadContext ctx) inline static private
Definition at line 122 of file DeveloperTeleport.c.
References Serializer::Read(), and SetPlayerPosition().
Referenced by OnRPC().
SetPlayerDirection()
static void SetPlayerDirection (PlayerBase player, vector direction) inline static private
Definition at line 82 of file DeveloperTeleport.c.
References GetGame(), and HumanCommandVehicle::GetTransport().
Referenced by OnRPCSetPlayerDirection(), and TeleportAtCursorEx().
SetPlayerPosition()
static void SetPlayerPosition (PlayerBase player, vector position) inline static private
Definition at line 55 of file DeveloperTeleport.c.
References GetGame(), and HumanCommandVehicle::GetTransport().
Referenced by OnRPCSetPlayerPosition(), PluginBase::Teleport(), TeleportAtCursor(), and TeleportAtCursorEx().
TeleportAtCursor()
static void TeleportAtCursor () inline static private
Definition at line 5 of file DeveloperTeleport.c.
References vector::Distance(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), GetPlayer(), DeveloperFreeCamera::IsFreeCameraEnabled(), Debug::LogWarning(), DayZPhysics::RaycastRV(), SetPlayerPosition(), and TELEPORT_DISTANCE_MAX.
TeleportAtCursorEx()
static void TeleportAtCursorEx () inline static private
Definition at line 33 of file DeveloperTeleport.c.
References CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), GetPlayer(), DeveloperFreeCamera::IsFreeCameraEnabled(), SetPlayerDirection(), SetPlayerPosition(), DayZPhysics::SphereCastBullet(), and TELEPORT_DISTANCE_MAX_EX.
Referenced by DeveloperFreeCamera::DisableFreeCamera(), and PluginBase::TeleportAtCursor().
Field Documentation
TELEPORT_DISTANCE_MAX
protected const float TELEPORT_DISTANCE_MAX = 1000 static private
Definition at line 3 of file DeveloperTeleport.c.
Referenced by TeleportAtCursor().
TELEPORT_DISTANCE_MAX_EX
protected const float TELEPORT_DISTANCE_MAX_EX = 500 static private
Definition at line 32 of file DeveloperTeleport.c.
Referenced by TeleportAtCursorEx().
The documentation for this class was generated from the following file:
4_World/Plugins/PluginBase/PluginDeveloper/DeveloperTeleport.c