DayZ: DebugPrint Class Reference
DebugPrint Class Reference
Static Private Member Functions
static void OnInit ()
static void Log (string msg)
Prints debug message with normal prio.
static void LogAndTrace (string msg)
Prints debug message as normal message and prints stack trace of calls.
static void LogWarning (string msg)
Prints debug message as warning message.
static void LogWarningAndTrace (string msg)
Prints debug message as warning message and prints stack trace of calls.
static void LogError (string msg)
Prints debug message as error message.
static void LogErrorAndTrace (string msg)
Prints debug message as error message and prints stack trace of calls.
static string AdjustDebugLog (string msg)
Function adjust received message for debug console (Do not use)
static void EnableTracingLogs (bool enable)
static private bool IsDebugLog (string msg)
static private string TrimDebugLog (string msg)
static private bool IsStackTrace (string msg)
static private string TrimStackTrace (string msg)
static private void LogMessage (string msg, int msg_type, bool trace=false)
Static Private Attributes
static private const int MSG_LOG = 0
static private const int MSG_WARNING = 1
static private const int MSG_ERROR = 2
static private const int MSG_COUNT = 3
static private string s_MsgPrefix [MSG_COUNT]
static private string s_MsgStackMarkStart
static private string s_MsgStackMarkEnd
static private bool s_MsgStackMarked
static private bool s_TraceAllLogs
Detailed Description
Definition at line 1 of file DebugPrint.c.
Member Function Documentation
AdjustDebugLog()
static string AdjustDebugLog (string msg) inline static private
Function adjust received message for debug console (Do not use)
Parameters
msg string Message for adjust
Returns
string Adjusted Message
string msg = DebugPrint.AdjustDebugLog("s = 'Hello World, this is error log'");
DebugPrint.Log(msg);
>> Hello World, this is error log
Definition at line 141 of file DebugPrint.c.
References IsDebugLog(), IsStackTrace(), TrimDebugLog(), and TrimStackTrace().
EnableTracingLogs()
static void EnableTracingLogs (bool enable) inline static private
Definition at line 156 of file DebugPrint.c.
References s_TraceAllLogs.
IsDebugLog()
static private bool IsDebugLog (string msg) inline static private
Definition at line 161 of file DebugPrint.c.
References string::IndexOf(), MSG_COUNT, and s_MsgPrefix.
Referenced by AdjustDebugLog().
IsStackTrace()
static private bool IsStackTrace (string msg) inline static private
Definition at line 187 of file DebugPrint.c.
References string::IndexOf(), s_MsgStackMarked, s_MsgStackMarkEnd, and s_MsgStackMarkStart.
Referenced by AdjustDebugLog().
Log()
static void Log (string msg) inline static private
Prints debug message with normal prio.
Parameters
msg string Debug message for print
Returns
void None
DebugPrint.Log("Hello World");
>> [Log]: Hello World;
Definition at line 37 of file DebugPrint.c.
References LogMessage(), MSG_LOG, and s_TraceAllLogs.
LogAndTrace()
static void LogAndTrace (string msg) inline static private
Prints debug message as normal message and prints stack trace of calls.
Parameters
msg string Debug message for print
Returns
void None
DebugPrint.LogAndTrace("Hello World, this is normal log");
>> [Log]: Hello World, this is normal log
>>      -- Stack trace --
>>      OnKeyPress() Scripts/mission/missionGameplay.c : 230
>>      OnKeyPress() Scripts/DayZGame.c : 346
>>      -----------------
Definition at line 56 of file DebugPrint.c.
References LogMessage(), and MSG_LOG.
LogError()
static void LogError (string msg) inline static private
Prints debug message as error message.
Parameters
msg string Debug message for error print
Returns
void None
DebugPrint.LogError("Hello World, this is error log");
>> [Error]: Hello World, this is error log
Definition at line 105 of file DebugPrint.c.
References LogMessage(), MSG_ERROR, and s_TraceAllLogs.
LogErrorAndTrace()
static void LogErrorAndTrace (string msg) inline static private
Prints debug message as error message and prints stack trace of calls.
Parameters
msg string Debug message for error print
Returns
void None
DebugPrint.LogErrorAndTrace("Hello World, this is error log");
>> [Error]: Hello World, this is error log
>>      -- Stack trace --
>>      OnKeyPress() Scripts/mission/missionGameplay.c : 230
>>      OnKeyPress() Scripts/DayZGame.c : 346
>>      -----------------
Definition at line 124 of file DebugPrint.c.
References LogMessage(), and MSG_ERROR.
Referenced by SyncPlayerList::CreatePlayerList(), OnlineServices::ErrorCaught(), OnlineServices::LoadFriends(), OnlineServices::LoadMPPrivilege(), OnlineServices::LoadPermissions(), OnlineServices::LoadServers(), OnlineServices::LoadVoicePrivilege(), OnlineServices::SetServerFavorited(), OnlineServices::ShowInviteScreen(), and OnlineServices::ShowUserProfile().
LogMessage()
static private void LogMessage (string msg, int msg_type, bool trace = false) inline static private
Definition at line 218 of file DebugPrint.c.
References DumpStack(), Print(), and s_MsgPrefix.
Referenced by Log(), LogAndTrace(), LogError(), LogErrorAndTrace(), LogWarning(), and LogWarningAndTrace().
LogWarning()
static void LogWarning (string msg) inline static private
Prints debug message as warning message.
Parameters
msg string Debug message for warning print
Returns
void None
DebugPrint.LogWarning("Hello World, this is warning log");
>> [Warning]: Hello World, this is warning log
Definition at line 71 of file DebugPrint.c.
References LogMessage(), MSG_WARNING, and s_TraceAllLogs.
LogWarningAndTrace()
static void LogWarningAndTrace (string msg) inline static private
Prints debug message as warning message and prints stack trace of calls.
Parameters
msg string Debug message for warning print
Returns
void None
DebugPrint.LogWarningAndTrace("Hello World, this is warning log");
>> [Warning]: Hello World, this is warning log
>>      -- Stack trace --
>>      OnKeyPress() Scripts/mission/missionGameplay.c : 230
>>      OnKeyPress() Scripts/DayZGame.c : 346
>>      -----------------
Definition at line 90 of file DebugPrint.c.
References LogMessage(), and MSG_WARNING.
OnInit()
static void OnInit () inline static private
Definition at line 14 of file DebugPrint.c.
References MSG_ERROR, MSG_LOG, MSG_WARNING, s_MsgPrefix, s_MsgStackMarked, s_MsgStackMarkEnd, s_MsgStackMarkStart, and s_TraceAllLogs.
TrimDebugLog()
static private string TrimDebugLog (string msg) inline static private
Definition at line 173 of file DebugPrint.c.
References string::IndexOf(), string::Length(), and string::Substring().
Referenced by AdjustDebugLog().
TrimStackTrace()
static private string TrimStackTrace (string msg) inline static private
Definition at line 208 of file DebugPrint.c.
References string::Empty, and string::IndexOf().
Referenced by AdjustDebugLog().
Field Documentation
MSG_COUNT
private const int MSG_COUNT = 3 static private
Definition at line 6 of file DebugPrint.c.
Referenced by IsDebugLog().
MSG_ERROR
private const int MSG_ERROR = 2 static private
Definition at line 5 of file DebugPrint.c.
Referenced by LogError(), LogErrorAndTrace(), and OnInit().
MSG_LOG
private const int MSG_LOG = 0 static private
Definition at line 3 of file DebugPrint.c.
Referenced by Log(), LogAndTrace(), and OnInit().
MSG_WARNING
private const int MSG_WARNING = 1 static private
Definition at line 4 of file DebugPrint.c.
Referenced by LogWarning(), LogWarningAndTrace(), and OnInit().
s_MsgPrefix
private string s_MsgPrefix[MSG_COUNT] static private
Definition at line 8 of file DebugPrint.c.
Referenced by IsDebugLog(), LogMessage(), and OnInit().
s_MsgStackMarked
private bool s_MsgStackMarked static private
Definition at line 11 of file DebugPrint.c.
Referenced by IsStackTrace(), and OnInit().
s_MsgStackMarkEnd
private string s_MsgStackMarkEnd static private
Definition at line 10 of file DebugPrint.c.
Referenced by IsStackTrace(), and OnInit().
s_MsgStackMarkStart
private string s_MsgStackMarkStart static private
Definition at line 9 of file DebugPrint.c.
Referenced by IsStackTrace(), and OnInit().
s_TraceAllLogs
private bool s_TraceAllLogs static private
Definition at line 12 of file DebugPrint.c.
Referenced by EnableTracingLogs(), Log(), LogError(), LogWarning(), and OnInit().
The documentation for this class was generated from the following file:
3_Game/tools/DebugPrint.c