DayZ: StaticGUIUtils Class Reference
StaticGUIUtils Class Reference
Static Private Member Functions
static string VerifyIconImageString (int imageset_group=IMAGESETGROUP_INVENTORY, string icon_name="")
Checks for improperly formated, legacy image names and corrects them to default format.
Static Private Attributes
static const int IMAGESETGROUP_INVENTORY = 0
Detailed Description
Definition at line 1 of file StaticGUIUtils.c.
Member Function Documentation
VerifyIconImageString()
static string VerifyIconImageString (int imageset_group = IMAGESETGROUP_INVENTORY, string icon_name = "") inline static private
Checks for improperly formated, legacy image names and corrects them to default format.
Definition at line 7 of file StaticGUIUtils.c.
References IMAGESETGROUP_INVENTORY.
Referenced by AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), AttachmentCategoriesContainer::LoadAttachmentCategoriesIcon(), and PlayerContainer::PlayerContainer().
Field Documentation
IMAGESETGROUP_INVENTORY
const int IMAGESETGROUP_INVENTORY = 0 static private
Definition at line 3 of file StaticGUIUtils.c.
Referenced by AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), AttachmentCategoriesContainer::LoadAttachmentCategoriesIcon(), PlayerContainer::PlayerContainer(), and VerifyIconImageString().
The documentation for this class was generated from the following file:
5_Mission/GUI/StaticGUIUtils.c