DayZ Scripts: InjurySoundHandlerBase Class Reference
InjurySoundHandlerBase Class Reference
Private Member Functions
eInjurySoundZones DetermineInjuryZone (eInjuryHandlerLevels level)
override void Update ()
void ProcessSound (eInjurySoundZones zone)
void PlaySound (eInjurySoundZones zone)
Private Attributes
const float SOUND_INTERVALS_LIGHT_MIN = 15
const float SOUND_INTERVALS_LIGHT_MAX = 30
const float SOUND_INTERVALS_MEDIUM_MIN = 10
const float SOUND_INTERVALS_MEDIUM_MAX = 25
const float SOUND_INTERVALS_HEAVY_MIN = 3
const float SOUND_INTERVALS_HEAVY_MAX = 12
ref HumanMovementState m_MovementState = new HumanMovementState
eInjurySoundZones m_InjurySoundZone
eInjuryHandlerLevels m_InjuryLevel
float m_SoundTime
Detailed Description
Definition at line 24 of file InjurySoundHandler.c.
Member Function Documentation
DetermineInjuryZone()
eInjurySoundZones DetermineInjuryZone (eInjuryHandlerLevels level) inline private
Definition at line 36 of file InjurySoundHandler.c.
References Math::Clamp(), HumanMovementState::m_iMovement, HumanMovementState::m_iStanceIdx, m_MovementState, and m_Player.
Referenced by Update().
PlaySound()
void PlaySound (eInjurySoundZones zone) inline private
Definition at line 111 of file InjurySoundHandler.c.
References m_Player.
ProcessSound()
void ProcessSound (eInjurySoundZones zone) inline private
Definition at line 81 of file InjurySoundHandler.c.
References GetGame(), GetTime(), CGame::GetTime(), m_SoundTime, PlaySound(), Math::RandomFloatInclusive(), SOUND_INTERVALS_LIGHT_MAX, and SOUND_INTERVALS_LIGHT_MIN.
Update()
override void Update () inline private
Definition at line 70 of file InjurySoundHandler.c.
References DetermineInjuryZone(), m_Player, and ProcessSound().
Field Documentation
m_InjuryLevel
eInjuryHandlerLevels m_InjuryLevel private
Definition at line 32 of file InjurySoundHandler.c.
m_InjurySoundZone
eInjurySoundZones m_InjurySoundZone private
Definition at line 31 of file InjurySoundHandler.c.
m_MovementState
ref HumanMovementState m_MovementState = new HumanMovementState private
Definition at line 30 of file InjurySoundHandler.c.
m_SoundTime
float m_SoundTime private
Definition at line 33 of file InjurySoundHandler.c.
SOUND_INTERVALS_HEAVY_MAX
const float SOUND_INTERVALS_HEAVY_MAX = 12 private
Definition at line 28 of file InjurySoundHandler.c.
SOUND_INTERVALS_HEAVY_MIN
const float SOUND_INTERVALS_HEAVY_MIN = 3 private
Definition at line 28 of file InjurySoundHandler.c.
SOUND_INTERVALS_LIGHT_MAX
const float SOUND_INTERVALS_LIGHT_MAX = 30 private
Definition at line 26 of file InjurySoundHandler.c.
SOUND_INTERVALS_LIGHT_MIN
const float SOUND_INTERVALS_LIGHT_MIN = 15 private
Definition at line 26 of file InjurySoundHandler.c.
SOUND_INTERVALS_MEDIUM_MAX
const float SOUND_INTERVALS_MEDIUM_MAX = 25 private
Definition at line 27 of file InjurySoundHandler.c.
SOUND_INTERVALS_MEDIUM_MIN
const float SOUND_INTERVALS_MEDIUM_MIN = 10 private
Definition at line 27 of file InjurySoundHandler.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/SoundHandlers/InjurySoundHandler.c