DayZ: NotificationSystem Class Reference
NotificationSystem Class Reference
Private Member Functions
void NotificationSystem ()
protected NotificationData GetNotificationData (NotificationType type)
Static Private Member Functions
static void InitInstance ()
static void CleanupInstance ()
static NotificationSystem GetInstance ()
static void SendNotificationToPlayerExtended (Man player, float show_time, string title_text, string detail_text="", string icon="")
Send custom notification to player from server.
static void SendNotificationToPlayerIdentityExtended (PlayerIdentity player, float show_time, string title_text, string detail_text="", string icon="")
Send custom notification to player identity from server.
static void SendNotificationToPlayer (Man player, NotificationType type, float show_time, string detail_text="")
Send notification from default types to player from server.
static void SendNotificationToPlayerIdentity (PlayerIdentity player, NotificationType type, float show_time, string detail_text="")
Send notification from default types to player identity from server.
static void AddNotification (NotificationType type, float show_time, string detail_text="")
Send notification from default types to local player.
static void AddNotificationExtended (float show_time, string title_text, string detail_text="", string icon="")
Send custom notification from to local player.
static void Update (float timeslice)
static void LoadNotificationData ()
Private Attributes
protected ref array< ref NotificationRuntimeData > m_TimeArray
protected ref array< ref NotificationRuntimeData > m_DeferredArray
protected ref map< NotificationType, ref NotificationData > m_DataArray
ref ScriptInvoker m_OnNotificationAdded = new ScriptInvoker
ref ScriptInvoker m_OnNotificationRemoved = new ScriptInvoker
Static Private Attributes
static protected const string JSON_FILE_PATH = "Scripts/Data/notifications.json"
static protected const int MAX_NOTIFICATIONS = 5
static protected ref NotificationSystem m_Instance
Detailed Description
Definition at line 57 of file NotificationSystem.c.
Constructor & Destructor Documentation
NotificationSystem()
void NotificationSystem () inline private
Definition at line 90 of file NotificationSystem.c.
References m_DeferredArray, and m_TimeArray.
Referenced by InitInstance().
Member Function Documentation
AddNotification()
static void AddNotification (NotificationType type, float show_time, string detail_text = "") inline static private
Send notification from default types to local player.
Parameters
type the type of notification to send - these can be viewed in /Scripts/Data/Notifications.json
show_time amount of time this notification is displayed
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
Definition at line 173 of file NotificationSystem.c.
References GetGame(), GetNotificationData(), CGame::GetTickTime(), ScriptInvoker::Invoke(), m_DeferredArray, m_Instance, m_OnNotificationAdded, m_TimeArray, MAX_NOTIFICATIONS, and NotificationRuntimeData().
Referenced by DisconnectSessionEx(), OnlineServices::OnFriendsAsync(), BiosSessionService::OnGetGameplaySession(), and OnRPC().
AddNotificationExtended()
static void AddNotificationExtended (float show_time, string title_text, string detail_text = "", string icon = "") inline static private
Send custom notification from to local player.
Parameters
show_time amount of time this notification is displayed
title_text the title text that is displayed in the notification
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
icon the icon that is displayed in the notification - will use default icon if not set
Definition at line 197 of file NotificationSystem.c.
References GetGame(), CGame::GetTickTime(), ScriptInvoker::Invoke(), m_DeferredArray, m_Instance, m_OnNotificationAdded, m_TimeArray, MAX_NOTIFICATIONS, and NotificationRuntimeData().
Referenced by OnRPC().
CleanupInstance()
static void CleanupInstance () inline static private
Definition at line 80 of file NotificationSystem.c.
References m_Instance.
Referenced by ~DayZGame().
GetInstance()
static NotificationSystem GetInstance () inline static private
Definition at line 85 of file NotificationSystem.c.
References m_Instance.
Referenced by NotificationUI::NotificationUI(), and NotificationUI::~NotificationUI().
GetNotificationData()
protected NotificationData GetNotificationData (NotificationType type) inline private
Definition at line 248 of file NotificationSystem.c.
References m_DataArray.
Referenced by AddNotification().
InitInstance()
static void InitInstance () inline static private
Definition at line 71 of file NotificationSystem.c.
References LoadNotificationData(), m_Instance, and NotificationSystem().
Referenced by InitNotifications().
LoadNotificationData()
static void LoadNotificationData () inline static private
Definition at line 258 of file NotificationSystem.c.
References JSON_FILE_PATH, m_DataArray, and m_Instance.
Referenced by InitInstance().
SendNotificationToPlayer()
static void SendNotificationToPlayer (Man player, NotificationType type, float show_time, string detail_text = "") inline static private
Send notification from default types to player from server.
Parameters
player the target player to send notification to
type the type of notification to send - these can be viewed in /Scripts/Data/Notifications.json
show_time amount of time this notification is displayed
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
Definition at line 141 of file NotificationSystem.c.
References SendNotificationToPlayerIdentity().
SendNotificationToPlayerExtended()
static void SendNotificationToPlayerExtended (Man player, float show_time, string title_text, string detail_text = "", string icon = "") inline static private
Send custom notification to player from server.
Parameters
player the target player to send notification to
show_time amount of time this notification is displayed
title_text the title text that is displayed in the notification
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
icon the icon that is displayed in the notification - will use default icon if not set
Definition at line 106 of file NotificationSystem.c.
References SendNotificationToPlayerIdentityExtended().
SendNotificationToPlayerIdentity()
static void SendNotificationToPlayerIdentity (PlayerIdentity player, NotificationType type, float show_time, string detail_text = "") inline static private
Send notification from default types to player identity from server.
Parameters
player the target player to send notification to - if null, will send to all players
type the type of notification to send - these can be viewed in /Scripts/Data/Notifications.json
show_time amount of time this notification is displayed
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
Definition at line 156 of file NotificationSystem.c.
References ScriptRPC::Send(), and Serializer::Write().
Referenced by SendNotificationToPlayer().
SendNotificationToPlayerIdentityExtended()
static void SendNotificationToPlayerIdentityExtended (PlayerIdentity player, float show_time, string title_text, string detail_text = "", string icon = "") inline static private
Send custom notification to player identity from server.
Parameters
player the target player to send notification to - if null, will send to all players
show_time amount of time this notification is displayed
title_text the title text that is displayed in the notification
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
icon the icon that is displayed in the notification - will use default icon if not set
Definition at line 122 of file NotificationSystem.c.
References ScriptRPC::Send(), and Serializer::Write().
Referenced by SendNotificationToPlayerExtended().
Update()
static void Update (float timeslice) inline static private
Definition at line 217 of file NotificationSystem.c.
References GetGame(), CGame::GetTickTime(), ScriptInvoker::Invoke(), m_DeferredArray, m_Instance, m_OnNotificationAdded, m_OnNotificationRemoved, m_TimeArray, and NotificationRuntimeData().
Referenced by OnUpdate().
Field Documentation
JSON_FILE_PATH
protected const string JSON_FILE_PATH = "Scripts/Data/notifications.json" static private
Definition at line 59 of file NotificationSystem.c.
Referenced by LoadNotificationData().
m_DataArray
protected ref map<NotificationType, ref NotificationData> m_DataArray private
Definition at line 66 of file NotificationSystem.c.
Referenced by GetNotificationData(), and LoadNotificationData().
m_DeferredArray
protected ref array<ref NotificationRuntimeData> m_DeferredArray private
Definition at line 65 of file NotificationSystem.c.
Referenced by AddNotification(), AddNotificationExtended(), NotificationSystem(), and Update().
m_Instance
protected ref NotificationSystem m_Instance static private
Definition at line 62 of file NotificationSystem.c.
Referenced by AddNotification(), AddNotificationExtended(), CleanupInstance(), GetInstance(), InitInstance(), LoadNotificationData(), and Update().
m_OnNotificationAdded
ref ScriptInvoker m_OnNotificationAdded = new ScriptInvoker private
Definition at line 68 of file NotificationSystem.c.
Referenced by AddNotification(), AddNotificationExtended(), NotificationUI::NotificationUI(), Update(), and NotificationUI::~NotificationUI().
m_OnNotificationRemoved
ref ScriptInvoker m_OnNotificationRemoved = new ScriptInvoker private
Definition at line 69 of file NotificationSystem.c.
Referenced by NotificationUI::NotificationUI(), Update(), and NotificationUI::~NotificationUI().
m_TimeArray
protected ref array<ref NotificationRuntimeData> m_TimeArray private
Definition at line 64 of file NotificationSystem.c.
Referenced by AddNotification(), AddNotificationExtended(), NotificationSystem(), and Update().
MAX_NOTIFICATIONS
protected const int MAX_NOTIFICATIONS = 5 static private
Definition at line 60 of file NotificationSystem.c.
Referenced by AddNotification(), and AddNotificationExtended().
The documentation for this class was generated from the following file:
3_Game/Client/Notifications/NotificationSystem.c