DayZ: ReplaceItemWithNewLambdaBase Class Reference
ReplaceItemWithNewLambdaBase Class Reference
base class for transformation operations (creating one item from another)
Private Member Functions
void ReplaceItemWithNewLambdaBase (EntityAI old_item, string new_item_type)
void OverrideNewLocation (InventoryLocation newLocation)
void VerifyItemTypeBySlotType ()
protected bool WantCreateNewEntity ()
protected bool CanExecuteLambda ()
protected bool PrepareLocations ()
Step A. - prepare inventory locations.
protected void RemoveOldItemFromLocation ()
Step B. - free location for new item @NOTE this operation does not delete the object, only removes it from inventory location.
protected void UndoRemoveOldItemFromLocation ()
protected void RemoveNetworkObjectInfo ()
Step C. - remove network part of the object @NOTE this operation does not delete the object, only removes its network part (and deletes it on client)
protected void UndoRemoveNetworkObjectInfo ()
protected EntityAI CreateNewEntity ()
Step D. - create new entity (LOCAL) with specified type.
void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
Step E. copy properties from old object to the created one.
protected void DeleteOldEntity ()
Step F. - deletes physically old item.
protected void CreateNetworkObjectInfo (EntityAI new_item)
Step G. - create NetworkObjectInfo for new item.
protected void OnSuccess (EntityAI new_item)
Step H. - notification on finish.
protected void OnAbort ()
Step Out - notification on abort.
void Execute (HumanInventoryWithFSM fsm_to_notify=null)
string DumpToString ()
Private Attributes
EntityAI m_OldItem
string m_NewItemType
protected ref InventoryLocation m_OldLocation
protected ref InventoryLocation m_NewLocation
protected bool m_RemoveFromLocationPassed = false
private bool m_RemoveNetworkObjectInfoPassed = false
Detailed Description
base class for transformation operations (creating one item from another)
Definition at line 4 of file ReplaceItemWithNewLambdaBase.c.
Constructor & Destructor Documentation
ReplaceItemWithNewLambdaBase()
void ReplaceItemWithNewLambdaBase (EntityAI old_item, string new_item_type) inline private
Definition at line 13 of file ReplaceItemWithNewLambdaBase.c.
References m_NewItemType, and m_OldItem.
Member Function Documentation
CanExecuteLambda()
protected bool CanExecuteLambda () inline private
Definition at line 31 of file ReplaceItemWithNewLambdaBase.c.
References GameInventory::LocationCanRemoveEntity(), m_OldItem, and m_OldLocation.
Referenced by Execute().
CopyOldPropertiesToNew()
CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item) inline private
Step E. copy properties from old object to the created one.
@NOTE: This is supposed to be overriden in derived classes
Definition at line 185 of file ReplaceItemWithNewLambdaBase.c.
References hndDebugPrint().
Referenced by Execute().
CreateNetworkObjectInfo()
CreateNetworkObjectInfo (EntityAI new_item) inline private
Step G. - create NetworkObjectInfo for new item.
@NOTE: new_item can be null if the lambda did not create any item (intentionaly)
Definition at line 204 of file ReplaceItemWithNewLambdaBase.c.
References GetGame(), hndDebugPrint(), and CGame::RemoteObjectTreeCreate().
Referenced by Execute().
CreateNewEntity()
CreateNewEntity () inline private
Step D. - create new entity (LOCAL) with specified type.
@NOTE: if (!m_NewLocation || m_NewItemType.Empty) ==> this function does not create a new entity
Definition at line 123 of file ReplaceItemWithNewLambdaBase.c.
References CFG_VEHICLESPATH, CGame::ConfigGetInt(), CGame::ConfigIsExisting(), ECE_LOCAL, ECE_OBJECT_SWAP, ECE_PLACE_ON_SURFACE, GetGame(), InventoryLocation::GetParent(), InventoryLocation::GetPos(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), hndDebugPrint(), GameInventory::LocationCreateEntity(), GameInventory::LocationCreateLocalEntity(), m_NewItemType, m_NewLocation, m_OldItem, path, RF_NONE, InventoryLocation::SetAttachment(), VerifyItemTypeBySlotType(), and WantCreateNewEntity().
Referenced by Execute().
DeleteOldEntity()
DeleteOldEntity () inline private
Step F. - deletes physically old item.
Definition at line 193 of file ReplaceItemWithNewLambdaBase.c.
References GetGame(), hndDebugPrint(), m_OldItem, and CGame::ObjectDelete().
Referenced by Execute().
DumpToString()
string DumpToString () inline private
Definition at line 294 of file ReplaceItemWithNewLambdaBase.c.
References m_NewItemType, and m_OldItem.
Referenced by EntityAI::ReplaceItemElsewhereWithNewInHandsImpl(), EntityAI::ReplaceItemInHandsWithNewElsewhereImpl(), EntityAI::ReplaceItemInHandsWithNewImpl(), and EntityAI::ReplaceItemWithNewImpl().
Execute()
void Execute (HumanInventoryWithFSM fsm_to_notify = null) inline private
Definition at line 231 of file ReplaceItemWithNewLambdaBase.c.
References CanExecuteLambda(), CopyOldPropertiesToNew(), CreateNetworkObjectInfo(), CreateNewEntity(), DeleteOldEntity(), InventoryLocation::DumpToStringNullSafe(), Error(), GetGame(), CGame::GetTime(), hndDebugPrint(), m_NewItemType, m_NewLocation, m_OldItem, m_OldLocation, m_RemoveFromLocationPassed, m_RemoveNetworkObjectInfoPassed, OnAbort(), OnSuccess(), PrepareLocations(), Print(), RemoveNetworkObjectInfo(), RemoveOldItemFromLocation(), UndoRemoveNetworkObjectInfo(), UndoRemoveOldItemFromLocation(), and WantCreateNewEntity().
Referenced by GameInventory::ReplaceItemWithNew().
OnAbort()
OnAbort () inline private
Step Out - notification on abort.
@NOTE: new_item can be null if the lambda did not create any item (intentionaly)
Definition at line 226 of file ReplaceItemWithNewLambdaBase.c.
References Print().
Referenced by Execute().
OnSuccess()
OnSuccess (EntityAI new_item) inline private
Step H. - notification on finish.
@NOTE: new_item can be null if the lambda did not create any item (intentionaly)
Definition at line 216 of file ReplaceItemWithNewLambdaBase.c.
References hndDebugPrint().
Referenced by Execute().
OverrideNewLocation()
void OverrideNewLocation (InventoryLocation newLocation) inline private
Definition at line 19 of file ReplaceItemWithNewLambdaBase.c.
References m_NewLocation.
PrepareLocations()
PrepareLocations () inline private
Step A. - prepare inventory locations.
Definition at line 43 of file ReplaceItemWithNewLambdaBase.c.
References CFG_VEHICLESPATH, CGame::ConfigGetInt(), CGame::ConfigIsExisting(), InventoryLocation::CopyLocationFrom(), Error(), InventoryLocation::GetDir(), GetGame(), InventoryLocation::GetParent(), InventoryLocation::GetPos(), InventoryLocation::GetType(), hndDebugPrint(), m_NewItemType, m_NewLocation, m_OldItem, m_OldLocation, Math3D::MatrixIdentity4(), path, InventoryLocation::SetGround(), and InventoryLocation::SetGroundEx().
Referenced by Execute().
RemoveNetworkObjectInfo()
RemoveNetworkObjectInfo () inline private
Step C. - remove network part of the object @NOTE this operation does not delete the object, only removes its network part (and deletes it on client)
Definition at line 107 of file ReplaceItemWithNewLambdaBase.c.
References GetGame(), m_OldItem, m_RemoveNetworkObjectInfoPassed, and CGame::RemoteObjectTreeDelete().
Referenced by Execute().
RemoveOldItemFromLocation()
RemoveOldItemFromLocation () inline private
Step B. - free location for new item @NOTE this operation does not delete the object, only removes it from inventory location.
Definition at line 86 of file ReplaceItemWithNewLambdaBase.c.
References InventoryLocation::DumpToStringNullSafe(), Error(), GameInventory::LocationRemoveEntity(), m_OldLocation, m_RemoveFromLocationPassed, and Print().
Referenced by Execute().
UndoRemoveNetworkObjectInfo()
protected void UndoRemoveNetworkObjectInfo () inline private
Definition at line 113 of file ReplaceItemWithNewLambdaBase.c.
References GetGame(), m_OldItem, and CGame::RemoteObjectTreeCreate().
Referenced by Execute().
UndoRemoveOldItemFromLocation()
protected void UndoRemoveOldItemFromLocation () inline private
Definition at line 96 of file ReplaceItemWithNewLambdaBase.c.
References InventoryLocation::DumpToStringNullSafe(), Error(), GameInventory::LocationAddEntity(), m_OldLocation, and Print().
Referenced by Execute().
VerifyItemTypeBySlotType()
void VerifyItemTypeBySlotType () inline private
Definition at line 24 of file ReplaceItemWithNewLambdaBase.c.
Referenced by CreateNewEntity().
WantCreateNewEntity()
protected bool WantCreateNewEntity () inline private
Definition at line 26 of file ReplaceItemWithNewLambdaBase.c.
References string::Empty, m_NewItemType, and m_NewLocation.
Referenced by CreateNewEntity(), and Execute().
Field Documentation
m_NewItemType
string m_NewItemType private
Definition at line 7 of file ReplaceItemWithNewLambdaBase.c.
Referenced by UnboxLambda::CopyOldPropertiesToNew(), CreateNewEntity(), DumpToString(), Execute(), PrepareLocations(), ReplaceItemWithNewLambdaBase(), and WantCreateNewEntity().
m_NewLocation
protected ref InventoryLocation m_NewLocation private
Definition at line 9 of file ReplaceItemWithNewLambdaBase.c.
Referenced by DropEquipAndDestroyRootLambda::CopyOldPropertiesToNew(), CreateNewEntity(), Execute(), OverrideNewLocation(), PrepareLocations(), and WantCreateNewEntity().
m_OldItem
EntityAI m_OldItem private
Definition at line 6 of file ReplaceItemWithNewLambdaBase.c.
Referenced by CanExecuteLambda(), CreateNewEntity(), DeleteOldEntity(), DumpToString(), Execute(), PrepareLocations(), RemoveNetworkObjectInfo(), HumanInventory::ReplaceItemWithNew(), GameInventory::ReplaceItemWithNew(), ReplaceItemWithNewLambdaBase(), and UndoRemoveNetworkObjectInfo().
m_OldLocation
protected ref InventoryLocation m_OldLocation private
Definition at line 8 of file ReplaceItemWithNewLambdaBase.c.
Referenced by CanExecuteLambda(), Execute(), PrepareLocations(), RemoveOldItemFromLocation(), and UndoRemoveOldItemFromLocation().
m_RemoveFromLocationPassed
protected bool m_RemoveFromLocationPassed = false private
Definition at line 10 of file ReplaceItemWithNewLambdaBase.c.
Referenced by Execute(), and RemoveOldItemFromLocation().
m_RemoveNetworkObjectInfoPassed
private bool m_RemoveNetworkObjectInfoPassed = false private
Definition at line 11 of file ReplaceItemWithNewLambdaBase.c.
Referenced by Execute(), and RemoveNetworkObjectInfo().
The documentation for this class was generated from the following file:
3_Game/Systems/Inventory/ReplaceItemWithNewLambdaBase.c