DayZ: ActionEmptyBottleBase Class Reference
ActionEmptyBottleBase Class Reference
Private Member Functions
void ActionEmptyBottleBase ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override void OnStartAnimationLoop (ActionData action_data)
override void OnEndServer (ActionData action_data)
Detailed Description
Definition at line 13 of file ActionEmptyBottleBase.c.
Constructor & Destructor Documentation
ActionEmptyBottleBase()
void ActionEmptyBottleBase () inline private
Definition at line 15 of file ActionEmptyBottleBase.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 37 of file ActionEmptyBottleBase.c.
References GetGame().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
Definition at line 54 of file ActionEmptyBottleBase.c.
References ActionData::m_MainItem.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 26 of file ActionEmptyBottleBase.c.
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool HasTarget () inline private
Definition at line 32 of file ActionEmptyBottleBase.c.
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
Definition at line 73 of file ActionEmptyBottleBase.c.
References GetGame(), ActionData::m_MainItem, and CGame::RPCSingleParam().
OnStartAnimationLoop()
override void OnStartAnimationLoop (ActionData action_data) inline private
Definition at line 63 of file ActionEmptyBottleBase.c.
References GetGame(), ActionData::m_MainItem, and CGame::RPCSingleParam().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Continuous/ActionEmptyBottleBase.c