DayZ: PresenceNotifierNoiseEvents Class Reference
PresenceNotifierNoiseEvents Class Reference
Private Member Functions
void PresenceNotifierNoiseEvents ()
void RegisterEvent (EPresenceNotifierNoiseEventType pEventType, int pValue, float pLength)
void ProcessEvent (EPresenceNotifierNoiseEventType pEventType)
int GetValue ()
protected void ResetEvent ()
Private Attributes
protected int m_Value
protected ref Timer m_CooldownTimer
Static Private Attributes
static protected ref map< EPresenceNotifierNoiseEventType, ref PresenceNotifierNoiseEvent > m_PresenceNotifierNotifierEvents
Detailed Description
Definition at line 29 of file PluginPresenceNotifier.c.
Constructor & Destructor Documentation
PresenceNotifierNoiseEvents()
void PresenceNotifierNoiseEvents () inline private
Definition at line 36 of file PluginPresenceNotifier.c.
References CALL_CATEGORY_SYSTEM, m_CooldownTimer, m_PresenceNotifierNotifierEvents, and m_Value.
Member Function Documentation
GetValue()
int GetValue () inline private
Definition at line 64 of file PluginPresenceNotifier.c.
References m_Value.
ProcessEvent()
void ProcessEvent (EPresenceNotifierNoiseEventType pEventType) inline private
Definition at line 49 of file PluginPresenceNotifier.c.
References m_CooldownTimer, m_PresenceNotifierNotifierEvents, m_Value, PresenceNotifierNoiseEvent(), and Timer::Stop().
Referenced by ProcessEvent().
RegisterEvent()
void RegisterEvent (EPresenceNotifierNoiseEventType pEventType, int pValue, float pLength) inline private
Definition at line 43 of file PluginPresenceNotifier.c.
References m_PresenceNotifierNotifierEvents, and PresenceNotifierNoiseEvent().
Referenced by PluginPresenceNotifier().
ResetEvent()
protected void ResetEvent () inline private
Definition at line 69 of file PluginPresenceNotifier.c.
References m_Value.
Field Documentation
m_CooldownTimer
protected ref Timer m_CooldownTimer private
Definition at line 34 of file PluginPresenceNotifier.c.
Referenced by PresenceNotifierNoiseEvents(), and ProcessEvent().
m_PresenceNotifierNotifierEvents
protected ref map<EPresenceNotifierNoiseEventType, ref PresenceNotifierNoiseEvent> m_PresenceNotifierNotifierEvents static private
Definition at line 33 of file PluginPresenceNotifier.c.
Referenced by PresenceNotifierNoiseEvents(), ProcessEvent(), and RegisterEvent().
m_Value
protected int m_Value private
Definition at line 31 of file PluginPresenceNotifier.c.
Referenced by GetValue(), PresenceNotifierNoiseEvents(), ProcessEvent(), and ResetEvent().
The documentation for this class was generated from the following file:
4_World/Plugins/PluginBase/PluginPresenceNotifier.c