DayZ Scripts Documentation: QuantityConversions Class Reference
QuantityConversions Class Reference
Static Private Member Functions
static string GetItemQuantityText (EntityAI item, bool showMax=false)
static float GetItemQuantity (InventoryItem item)
static float GetItemQuantityMax (InventoryItem item)
static void GetItemQuantity (InventoryItem item, out float q_cur, out float q_min, out float q_max)
static int HasItemQuantity (notnull EntityAI item)
Detailed Description
Definition at line 1 of file QuantityConversions.c.
Member Function Documentation
GetItemQuantity() [1/2]
static float GetItemQuantity (InventoryItem item) inline static private
Definition at line 72 of file QuantityConversions.c.
References Class::CastTo().
Referenced by InventoryGridController::GetItemQuantity(), ScriptedWidgetEventHandler::GetItemQuantity(), Icon::SetQuantity(), SlotsIcon::SetQuantity(), and UIScriptedMenu::UpdateQuickbarItemCard().
GetItemQuantity() [2/2]
static void GetItemQuantity (InventoryItem item, out float q_cur, out float q_min, out float q_max) inline static private
Definition at line 120 of file QuantityConversions.c.
References Class::CastTo().
GetItemQuantityMax()
static float GetItemQuantityMax (InventoryItem item) inline static private
Definition at line 96 of file QuantityConversions.c.
References Class::CastTo().
Referenced by Icon::SetQuantity(), and SlotsIcon::SetQuantity().
GetItemQuantityText()
static string GetItemQuantityText (EntityAI item, bool showMax = false) inline static private
Definition at line 3 of file QuantityConversions.c.
References Class::CastTo(), string::Format(), bool::ToString(), float::ToString(), and string::ToString().
Referenced by InventoryGridController::GetItemQuantityText(), Icon::SetQuantity(), SlotsIcon::SetQuantity(), and UIScriptedMenu::UpdateQuickbarItemCard().
HasItemQuantity()
static int HasItemQuantity (notnull EntityAI item) inline static private
Definition at line 143 of file QuantityConversions.c.
References Class::CastTo(), QUANTITY_COUNT, QUANTITY_HIDDEN, and QUANTITY_PROGRESS.
Referenced by SlotsIcon::CheckHasQuantity(), Icon::CheckHasQuantityEx(), ScriptedWidgetEventHandler::GetItemQuantity(), InventoryGridController::HasItemQuantity(), Attachments::IsItemActive(), HandsContainer::IsItemActive(), Attachments::IsItemWithQuantityActive(), Container::IsItemWithQuantityActive(), HandsContainer::IsItemWithQuantityActive(), PlayerContainer::IsItemWithQuantityActive(), VicinitySlotsContainer::IsItemWithQuantityActive(), ZombieContainer::IsItemWithQuantityActive(), Icon::SetQuantity(), SlotsIcon::SetQuantity(), and UIScriptedMenu::UpdateQuickbarItemCard().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/QuantityConversions.c