DayZ: ActionTakeItemToHands Class Reference
ActionTakeItemToHands Class Reference
Private Member Functions
void ActionTakeItemToHands ()
override void CreateConditionComponents ()
override bool HasProneException ()
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanContinue (ActionData action_data)
override void OnExecute (ActionData action_data)
override void CreateAndSetupActionCallback (ActionData action_data)
override bool CanBeUsedOnBack ()
Detailed Description
Definition at line 1 of file ActionTakeItemToHands.c.
Constructor & Destructor Documentation
ActionTakeItemToHands()
void ActionTakeItemToHands () inline private
Definition at line 3 of file ActionTakeItemToHands.c.
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 31 of file ActionTakeItemToHands.c.
References ItemBase::CanDetachAttachment(), and ItemBase::IsTakeable().
CanBeUsedOnBack()
override bool CanBeUsedOnBack () inline private
Definition at line 101 of file ActionTakeItemToHands.c.
CanContinue()
override bool CanContinue (ActionData action_data) inline private
Definition at line 44 of file ActionTakeItemToHands.c.
CreateAndSetupActionCallback()
override void CreateAndSetupActionCallback (ActionData action_data) inline private
Definition at line 71 of file ActionTakeItemToHands.c.
References Class::CastTo(), AnimatedActionBase::GetCallbackClassTypename(), ActionBaseCB::InitActionComponent(), ActionData::m_Callback, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, ActionData::m_Player, ActionData::m_Target, and ActionBaseCB::SetActionData().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 10 of file ActionTakeItemToHands.c.
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType () inline private
Definition at line 21 of file ActionTakeItemToHands.c.
HasProgress()
override bool HasProgress () inline private
Definition at line 26 of file ActionTakeItemToHands.c.
HasProneException()
override bool HasProneException () inline private
Definition at line 16 of file ActionTakeItemToHands.c.
OnExecute()
override void OnExecute (ActionData action_data) inline private
Definition at line 49 of file ActionTakeItemToHands.c.
References ClearInventoryReservationEx(), GetGame(), ActionData::m_Player, ActionData::m_Target, and InventoryLocation::SetHands().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Interact/ActionTakeItemToHands.c