DayZ: GameplayEffectWidgets_base Class Reference
GameplayEffectWidgets_base Class Reference
grouped gameplay effect widgets and their handling
Private Member Functions
void GameplayEffectWidgets ()
void ~GameplayEffectWidgets ()
protected void RegisterLayouts (string path, array< int > types)
Registers new layout and ties effect IDs to it.
protected void PairIDToTypes ()
protected TranslateIDToType (int typeID)
override void RegisterGameplayEffectData (int id, Param p)
protected void InitWidgetSet (int type, bool updating=false, int user_id_override=-1)
InitWidgetSet.
bool CreateHandledClass (typename handled_type, array< ref Widget > input, int type, int user_override)
array< int > CompileEffectListing ()
returns all vanilla effects, nested in a vanilla layout. If using different layouts for custom effects, please register and link separately
protected void UpdateVisibility ()
override void AddActiveEffects (array< int > effects)
override void RemoveActiveEffects (array< int > effects)
override void StopAllEffects ()
override bool IsAnyEffectRunning ()
override void AddSuspendRequest (int request_id)
override void RemoveSuspendRequest (int request_id)
override void ClearSuspendRequests ()
override int GetSuspendRequestCount ()
override void UpdateWidgets (int type=-1, float timeSlice=0, Param p=null, int handle=-1)
Usually called in course of an OnFrame update, can be manually called from elsewhere with parameters.
protected void CalculateValues (int type=-1, float timeSlice=0, Param p=null, int handle=-1)
Only one calculation per unique WidgetSet.
protected void ProcessWidgetUpdate (Widget w, int type, float timeSlice=0, Param p=null, int handle=-1)
protected void CalculateBreathEffect (float timeSlice=0, int type=-1, Param p=null)
protected void UpdateBreathEffect (ImageWidget w)
protected void CalculateOccluderEffect (int type, float timeSlice, Param p, int handle)
protected void UpdateOccluderEffect (ImageWidget w, int type, float timeSlice, Param p, int handle)
protected void CalculateFlashbangEffect (int type, float timeSlice, Param p, int handle)
protected void UpdateFlashbangEffect (ImageWidget w)
protected void HandleWidgetRoot (float timeSlice=0, Param p=null, int handle=-1)
override void Update (float timeSlice)
Generic update, called on frame from the player.
override void OnVoiceEvent (float breathing_resistance01)
Private Attributes
protected ref Widget m_Root
protected ref map< int, ref Widget > m_Layouts
protected ref set< ref Widget > m_UniqueLayouts
protected ref GameplayEffectDataMap m_WidgetDataMap
protected ref set< int > m_RunningEffects
protected ref set< int > m_RunningEffectsPrevious
protected ref array< int > m_UpdatingEffects
protected ref array< ref Widget > m_UpdatedWidgetsCheck
protected ref array< int > m_UpdatedWidgetSetsCheck
protected ref set< int > m_SuspendRequests
protected ref map< int, typename > m_IDToTypeMap
protected float m_TimeProgBreath
protected float m_BreathMultStamina
protected float m_BreathResidue
protected const int WIDGETSET_BREATH = 100
protected int m_BreathColor
protected float m_BreathAlphaVal
protected float m_FlashbangCoverAlphaVal
const float BREATH_HDR_MIN = 0.005
const float BREATH_HDR_MAX = 1.0
const float BREATH_COLOR_MULT_MIN = 0.5
const float BREATH_COLOR_MULT_MAX = 0.8
Detailed Description
grouped gameplay effect widgets and their handling
Definition at line 6 of file GameplayEffectWidgets.c.
Constructor & Destructor Documentation
~GameplayEffectWidgets()
void ~GameplayEffectWidgets () inline private
Definition at line 72 of file GameplayEffectWidgets.c.
Member Function Documentation
AddActiveEffects()
override void AddActiveEffects (array< int > effects) inline private
Definition at line 279 of file GameplayEffectWidgets.c.
References UpdateVisibility().
Referenced by ManBase::OnCommandHandlerTick(), PPERequester_GameplayBase::OnStart(), and StartSourceBleedingIndication().
AddSuspendRequest()
override void AddSuspendRequest (int request_id) inline private
Definition at line 349 of file GameplayEffectWidgets.c.
References UpdateVisibility().
Referenced by PPERequester_GameplayBase::OnStart(), and ManBase::OnUnconsciousStart().
CalculateBreathEffect()
protected void CalculateBreathEffect (float timeSlice = 0, int type = -1, Param p = null) inline private
Definition at line 533 of file GameplayEffectWidgets.c.
References ARGBF(), Math::Clamp(), GetSceneHDRMul(), Math::InverseLerp(), and Math::Lerp().
Referenced by CalculateValues().
CalculateFlashbangEffect()
protected void CalculateFlashbangEffect (int type, float timeSlice, Param p, int handle) inline private
Definition at line 572 of file GameplayEffectWidgets.c.
Referenced by CalculateValues().
CalculateOccluderEffect()
protected void CalculateOccluderEffect (int type, float timeSlice, Param p, int handle) inline private
Definition at line 561 of file GameplayEffectWidgets.c.
Referenced by CalculateValues().
CalculateValues()
protected void CalculateValues (int type = -1, float timeSlice = 0, Param p = null, int handle = -1) inline private
Only one calculation per unique WidgetSet.
Definition at line 448 of file GameplayEffectWidgets.c.
References CalculateBreathEffect(), CalculateFlashbangEffect(), and CalculateOccluderEffect().
Referenced by UpdateWidgets().
ClearSuspendRequests()
override void ClearSuspendRequests () inline private
Definition at line 365 of file GameplayEffectWidgets.c.
References UpdateVisibility().
Referenced by ManBase::SimulateDeath().
CompileEffectListing()
array< int > CompileEffectListing () inline private
returns all vanilla effects, nested in a vanilla layout. If using different layouts for custom effects, please register and link separately
Definition at line 194 of file GameplayEffectWidgets.c.
Referenced by GameplayEffectWidgets().
CreateHandledClass()
bool CreateHandledClass (typename handled_type , array< ref Widget > input, int type, int user_override) inline private
Definition at line 181 of file GameplayEffectWidgets.c.
References GameplayEffectsData::Init().
Referenced by InitWidgetSet().
GameplayEffectWidgets()
void GameplayEffectWidgets () inline private
Definition at line 32 of file GameplayEffectWidgets.c.
References CompileEffectListing(), WorkspaceWidget::CreateWidget(), GetGame(), CGame::GetWorkspace(), InitWidgetSet(), m_Root, PairIDToTypes(), RegisterLayouts(), and UpdateVisibility().
GetSuspendRequestCount()
override int GetSuspendRequestCount () inline private
Definition at line 371 of file GameplayEffectWidgets.c.
HandleWidgetRoot()
protected void HandleWidgetRoot (float timeSlice = 0, Param p = null, int handle = -1) inline private
Definition at line 592 of file GameplayEffectWidgets.c.
References Math::Clamp(), and m_Root.
Referenced by UpdateWidgets().
InitWidgetSet()
protected void InitWidgetSet (int type, bool updating = false, int user_id_override = -1) inline private
InitWidgetSet.
Parameters
type int ID of effect widget type
updating bool Marks widgets for 'PlayerBase.EOnFrame' updating
user_id_override int UserID of a widget to be used instead (allows multiple types to use single widget)
InitWidgetSet(EffectWidgetsTypes.MASK_BREATH,true,BREATH);
Note
All child widgets MUST be of the same type if special functionality is required (ImageWidget etc.)
Definition at line 124 of file GameplayEffectWidgets.c.
References CreateHandledClass(), GameplayEffectsDataImage(), Print(), and TranslateIDToType().
Referenced by GameplayEffectWidgets().
IsAnyEffectRunning()
override bool IsAnyEffectRunning () inline private
Definition at line 344 of file GameplayEffectWidgets.c.
Referenced by ManBase::EOnFrame(), and StopAllEffects().
OnVoiceEvent()
override void OnVoiceEvent (float breathing_resistance01) inline private
Definition at line 642 of file GameplayEffectWidgets.c.
References Math::Clamp(), and Math::Lerp().
Referenced by ManBase::UpdateMaskBreathWidget().
PairIDToTypes()
protected void PairIDToTypes () inline private
Definition at line 96 of file GameplayEffectWidgets.c.
Referenced by GameplayEffectWidgets().
ProcessWidgetUpdate()
protected void ProcessWidgetUpdate (Widget w, int type, float timeSlice = 0, Param p = null, int handle = -1) inline private
Definition at line 489 of file GameplayEffectWidgets.c.
References UpdateBreathEffect(), UpdateFlashbangEffect(), and UpdateOccluderEffect().
Referenced by UpdateWidgets().
RegisterGameplayEffectData()
override void RegisterGameplayEffectData (int id, Param p) inline private
Definition at line 106 of file GameplayEffectWidgets.c.
Referenced by BleedingSourcesManagerBase::Init(), and BleedingSourcesManagerBase::RegisterBleedingZoneEx().
RegisterLayouts()
protected void RegisterLayouts (string path, array< int > types) inline private
Registers new layout and ties effect IDs to it.
Note
Order of layout creation matters, they get layered on top of each other. Within a single layout, widget priorities govern the widget order.
Definition at line 85 of file GameplayEffectWidgets.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Root, and path.
Referenced by GameplayEffectWidgets().
RemoveActiveEffects()
override void RemoveActiveEffects (array< int > effects) inline private
Definition at line 299 of file GameplayEffectWidgets.c.
References UpdateVisibility().
Referenced by ManBase::OnCommandHandlerTick(), PPERequester_GameplayBase::OnStop(), and GameplayEffectsData::Update().
RemoveSuspendRequest()
override void RemoveSuspendRequest (int request_id) inline private
Definition at line 355 of file GameplayEffectWidgets.c.
References UpdateVisibility().
Referenced by PPERequester_GameplayBase::OnStop(), and ManBase::OnUnconsciousStop().
StopAllEffects()
override void StopAllEffects () inline private
Definition at line 324 of file GameplayEffectWidgets.c.
References GameplayEffectsData::ForceStop(), IsAnyEffectRunning(), m_Root, and UpdateVisibility().
Referenced by ManBase::SimulateDeath().
TranslateIDToType()
protected TranslateIDToType (int typeID) inline private
Definition at line 101 of file GameplayEffectWidgets.c.
Referenced by InitWidgetSet().
Update()
override void Update (float timeSlice) inline private
Generic update, called on frame from the player.
Definition at line 612 of file GameplayEffectWidgets.c.
References UpdateWidgets().
Referenced by ManBase::EOnFrame().
UpdateBreathEffect()
protected void UpdateBreathEffect (ImageWidget w) inline private
Definition at line 552 of file GameplayEffectWidgets.c.
Referenced by ProcessWidgetUpdate().
UpdateFlashbangEffect()
protected void UpdateFlashbangEffect (ImageWidget w) inline private
Definition at line 584 of file GameplayEffectWidgets.c.
Referenced by ProcessWidgetUpdate().
UpdateOccluderEffect()
protected void UpdateOccluderEffect (ImageWidget w, int type, float timeSlice, Param p, int handle) inline private
Definition at line 565 of file GameplayEffectWidgets.c.
Referenced by ProcessWidgetUpdate().
UpdateVisibility()
protected void UpdateVisibility () inline private
Definition at line 211 of file GameplayEffectWidgets.c.
References Widget::Clear(), Count, GameplayEffectsData::HasDefinedHandle(), m_Root, and GameplayEffectsData::UpdateVisibility().
Referenced by AddActiveEffects(), AddSuspendRequest(), ClearSuspendRequests(), GameplayEffectWidgets(), RemoveActiveEffects(), RemoveSuspendRequest(), and StopAllEffects().
UpdateWidgets()
override void UpdateWidgets (int type = -1, float timeSlice = 0, Param p = null, int handle = -1) inline private
Usually called in course of an OnFrame update, can be manually called from elsewhere with parameters.
Definition at line 377 of file GameplayEffectWidgets.c.
References CalculateValues(), GameplayEffectsData::DataInitialized(), HandleWidgetRoot(), GameplayEffectsData::HasDefinedHandle(), ProcessWidgetUpdate(), and GameplayEffectsData::Update().
Referenced by ScriptedWidgetEventHandler::OnBleedingIndicationChanged(), PPERequester_GameplayBase::OnUpdate(), StartSourceBleedingIndication(), StopSourceBleedingIndication(), and Update().
Field Documentation
BREATH_COLOR_MULT_MAX
const float BREATH_COLOR_MULT_MAX = 0.8 private
Definition at line 528 of file GameplayEffectWidgets.c.
BREATH_COLOR_MULT_MIN
const float BREATH_COLOR_MULT_MIN = 0.5 private
Definition at line 527 of file GameplayEffectWidgets.c.
BREATH_HDR_MAX
const float BREATH_HDR_MAX = 1.0 private
Definition at line 526 of file GameplayEffectWidgets.c.
BREATH_HDR_MIN
const float BREATH_HDR_MIN = 0.005 private
Definition at line 525 of file GameplayEffectWidgets.c.
m_BreathAlphaVal
protected float m_BreathAlphaVal private
Definition at line 29 of file GameplayEffectWidgets.c.
m_BreathColor
protected int m_BreathColor private
Definition at line 28 of file GameplayEffectWidgets.c.
m_BreathMultStamina
protected float m_BreathMultStamina private
Definition at line 21 of file GameplayEffectWidgets.c.
m_BreathResidue
protected float m_BreathResidue private
Definition at line 22 of file GameplayEffectWidgets.c.
m_FlashbangCoverAlphaVal
protected float m_FlashbangCoverAlphaVal private
Definition at line 30 of file GameplayEffectWidgets.c.
m_IDToTypeMap
protected ref map<int,typename> m_IDToTypeMap private
Definition at line 18 of file GameplayEffectWidgets.c.
m_Layouts
protected ref map<int,ref Widget> m_Layouts private
Definition at line 9 of file GameplayEffectWidgets.c.
m_Root
protected ref Widget m_Root private
Definition at line 8 of file GameplayEffectWidgets.c.
m_RunningEffects
protected ref set<int> m_RunningEffects private
Definition at line 12 of file GameplayEffectWidgets.c.
m_RunningEffectsPrevious
protected ref set<int> m_RunningEffectsPrevious private
Definition at line 13 of file GameplayEffectWidgets.c.
m_SuspendRequests
protected ref set<int> m_SuspendRequests private
Definition at line 17 of file GameplayEffectWidgets.c.
m_TimeProgBreath
protected float m_TimeProgBreath private
Definition at line 20 of file GameplayEffectWidgets.c.
m_UniqueLayouts
protected ref set<ref Widget> m_UniqueLayouts private
Definition at line 10 of file GameplayEffectWidgets.c.
m_UpdatedWidgetsCheck
protected ref array<ref Widget> m_UpdatedWidgetsCheck private
Definition at line 15 of file GameplayEffectWidgets.c.
m_UpdatedWidgetSetsCheck
protected ref array<int> m_UpdatedWidgetSetsCheck private
Definition at line 16 of file GameplayEffectWidgets.c.
m_UpdatingEffects
protected ref array<int> m_UpdatingEffects private
Definition at line 14 of file GameplayEffectWidgets.c.
m_WidgetDataMap
protected ref GameplayEffectDataMap m_WidgetDataMap private
Definition at line 11 of file GameplayEffectWidgets.c.
WIDGETSET_BREATH
protected const int WIDGETSET_BREATH = 100 private
Definition at line 25 of file GameplayEffectWidgets.c.
The documentation for this class was generated from the following file:
5_Mission/mission/GameplayEffectWidgets/GameplayEffectWidgets.c