DayZ Scripts Documentation: PluginManager Class Reference
PluginManager Class Reference
Private Member Functions
void PluginManager ()
void ~PluginManager ()
void Init ()
void PluginsInit ()
void MainOnUpdate (float delta_time)
PluginBase GetPluginByType (typename plugin_type)
Returns registred plugin by class type, better is to use global funtion GetPlugin(typename plugin_type)
protected void RegisterPlugin (string plugin_class_name, bool reg_on_client, bool reg_on_server, bool reg_on_release=true)
Register new PluginBase to PluginManager for storing and handling plugin.
protected void RegisterPluginDebug (string plugin_class_name, bool reg_on_client, bool reg_on_server)
Register new PluginBase to PluginManager for storing and handling plugin.
protected void RegisterPluginDiag (string plugin_class_name, bool reg_on_client, bool reg_on_server)
protected bool UnregisterPlugin (string plugin_class_name)
Private Attributes
private ref array< typename > m_PluginRegister
private ref map< typename, ref PluginBase > m_PluginsPtrs
Detailed Description
Definition at line 1 of file PluginManager.c.
Constructor & Destructor Documentation
PluginManager()
void PluginManager () inline private
Definition at line 9 of file PluginManager.c.
References m_PluginRegister, and m_PluginsPtrs.
~PluginManager()
void ~PluginManager () inline private
Definition at line 18 of file PluginManager.c.
References CALL_CATEGORY_GAMEPLAY, GetGame(), CGame::GetUpdateQueue(), m_PluginsPtrs, MainOnUpdate(), PluginBase::OnDestroy(), and ScriptInvoker::Remove().
Member Function Documentation
GetPluginByType()
PluginBase GetPluginByType (typename plugin_type) inline private
Returns registred plugin by class type, better is to use global funtion GetPlugin(typename plugin_type)
Parameters
module_tpye typename class type of plugin
Returns
PluginBase
PluginRepairing plugin = GetPluginManager().GetPluginByType(PluginRepairing);
Definition at line 157 of file PluginManager.c.
References m_PluginsPtrs.
Referenced by GetPlugin(), and PluginsInit().
Init()
void Init () inline private
Definition at line 39 of file PluginManager.c.
References CALL_CATEGORY_GAMEPLAY, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), MainOnUpdate(), RegisterPlugin(), RegisterPluginDebug(), and RegisterPluginDiag().
Referenced by PluginManagerInit().
MainOnUpdate()
void MainOnUpdate (float delta_time) inline private
Definition at line 134 of file PluginManager.c.
References m_PluginsPtrs, and PluginBase::OnUpdate().
Referenced by Init(), and ~PluginManager().
PluginsInit()
void PluginsInit () inline private
Definition at line 101 of file PluginManager.c.
References GetPluginByType(), m_PluginRegister, and m_PluginsPtrs.
Referenced by PluginManagerInit().
RegisterPlugin()
protected void RegisterPlugin (string plugin_class_name, bool reg_on_client, bool reg_on_server, bool reg_on_release = true) inline private
Register new PluginBase to PluginManager for storing and handling plugin.
Parameters
module_tpye typename class type of plugin
Returns
void
class PluginRepairing extends PluginBase
{
...
}
RegisterPlugin(PluginRepairing);
Definition at line 183 of file PluginManager.c.
References GetGame(), m_PluginRegister, and string::ToType().
Referenced by Init(), RegisterPluginDebug(), and RegisterPluginDiag().
RegisterPluginDebug()
protected void RegisterPluginDebug (string plugin_class_name, bool reg_on_client, bool reg_on_server) inline private
Register new PluginBase to PluginManager for storing and handling plugin.
Parameters
module_tpye typename class type of plugin
Returns
void
class PluginRepairing extends PluginBase
{
...
}
RegisterPlugin(PluginRepairing);
Definition at line 231 of file PluginManager.c.
References RegisterPlugin().
Referenced by Init().
RegisterPluginDiag()
protected void RegisterPluginDiag (string plugin_class_name, bool reg_on_client, bool reg_on_server) inline private
Definition at line 238 of file PluginManager.c.
References RegisterPlugin().
Referenced by Init().
UnregisterPlugin()
protected bool UnregisterPlugin (string plugin_class_name) inline private
Definition at line 250 of file PluginManager.c.
References m_PluginRegister, and string::ToType().
Field Documentation
m_PluginRegister
private ref array<typename> m_PluginRegister private
Definition at line 3 of file PluginManager.c.
Referenced by PluginManager(), PluginsInit(), RegisterPlugin(), and UnregisterPlugin().
m_PluginsPtrs
private ref map<typename, ref PluginBase> m_PluginsPtrs private
Definition at line 4 of file PluginManager.c.
Referenced by GetPluginByType(), MainOnUpdate(), PluginManager(), PluginsInit(), and ~PluginManager().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Plugins/PluginManager.c