DayZ: RemotePlayerDamageDebug Class Reference
RemotePlayerDamageDebug Class Reference
Private Member Functions
void RemotePlayerDamageDebug (PlayerBase player)
void AddDamage (float value_global, float value_blood, float value_shock)
void InsertDamageObject (DamageData damage_object)
PlayerBase GetPlayer ()
void Get (array< ref DamageData > damage_list)
void GetReversed (array< ref DamageData > damage_list)
void Serialize (array< ref RemotePlayerDamageDebug > list)
void Debug ()
Private Attributes
const int MAX_DAMAGE_RECORDS = 5
PlayerBase m_Player
bool m_ChangedSinceSerialization
ref array< ref DamageData > m_DamageList = new array<ref DamageData>
Detailed Description
Definition at line 1 of file RemotePlayerDamageDebug.c.
Constructor & Destructor Documentation
RemotePlayerDamageDebug()
void RemotePlayerDamageDebug (PlayerBase player) inline private
Definition at line 9 of file RemotePlayerDamageDebug.c.
References m_Player.
Member Function Documentation
AddDamage()
void AddDamage (float value_global, float value_blood, float value_shock) inline private
Definition at line 14 of file RemotePlayerDamageDebug.c.
References m_ChangedSinceSerialization, m_DamageList, and MAX_DAMAGE_RECORDS.
Referenced by PluginBase::OnDamageEvent().
Debug()
void Debug () inline private
Definition at line 63 of file RemotePlayerDamageDebug.c.
References m_DamageList, m_Player, and PrintString().
Referenced by DebugDamage(), and OnRPC().
Get()
void Get (array< ref DamageData > damage_list) inline private
Definition at line 37 of file RemotePlayerDamageDebug.c.
References m_DamageList.
GetPlayer()
PlayerBase GetPlayer () inline private
Definition at line 31 of file RemotePlayerDamageDebug.c.
References m_Player.
Referenced by OnRPC().
GetReversed()
void GetReversed (array< ref DamageData > damage_list) inline private
Definition at line 45 of file RemotePlayerDamageDebug.c.
References m_DamageList.
Referenced by UpdateDamageWidget().
InsertDamageObject()
void InsertDamageObject (DamageData damage_object) inline private
Definition at line 25 of file RemotePlayerDamageDebug.c.
References m_DamageList.
Referenced by MergeDamage().
Serialize()
void Serialize (array< ref RemotePlayerDamageDebug > list) inline private
Definition at line 54 of file RemotePlayerDamageDebug.c.
References m_ChangedSinceSerialization.
Field Documentation
m_ChangedSinceSerialization
bool m_ChangedSinceSerialization private
Definition at line 5 of file RemotePlayerDamageDebug.c.
Referenced by AddDamage(), and Serialize().
m_DamageList
ref array<ref DamageData> m_DamageList = new array<ref DamageData> private
Definition at line 7 of file RemotePlayerDamageDebug.c.
Referenced by AddDamage(), Debug(), Get(), GetReversed(), and InsertDamageObject().
m_Player
PlayerBase m_Player private
Definition at line 4 of file RemotePlayerDamageDebug.c.
Referenced by Debug(), GetPlayer(), and RemotePlayerDamageDebug().
MAX_DAMAGE_RECORDS
const int MAX_DAMAGE_RECORDS = 5 private
Definition at line 3 of file RemotePlayerDamageDebug.c.
Referenced by AddDamage().
The documentation for this class was generated from the following file:
4_World/Classes/RemotePlayerDebug/RemotePlayerDamageDebug.c