DayZ Scripts: PropertyModifiers Class Reference
PropertyModifiers Class Reference
Private Member Functions
float m_Weapon void PropertyModifiers (ItemBase owner)
float GetBarrelLength ()
Get Barrel Legth in mm.
float CalculateBarrelLength (ItemBase owner)
void UpdateModifiers ()
Static Private Member Functions
static vector GetModifierRaw (ItemBase item, string modifier_name, vector value="1 1 1")
Private Attributes
vector m_RecoilModifiers
vector m_SwayModifiers
vector m_SightMisalignment
float m_BarrelLength
ItemBase m_OwnerItem
Detailed Description
Definition at line 1 of file PropertyModifiers.c.
Constructor & Destructor Documentation
PropertyModifiers()
float m_Weapon void PropertyModifiers (ItemBase owner) inline private
Definition at line 12 of file PropertyModifiers.c.
References CalculateBarrelLength(), m_BarrelLength, m_OwnerItem, and UpdateModifiers().
Member Function Documentation
CalculateBarrelLength()
float CalculateBarrelLength (ItemBase owner) inline private
Definition at line 28 of file PropertyModifiers.c.
References vector::Distance().
Referenced by GetBarrelLength(), and PropertyModifiers().
GetBarrelLength()
float GetBarrelLength () inline private
Get Barrel Legth in mm.
Definition at line 22 of file PropertyModifiers.c.
References CalculateBarrelLength(), and m_OwnerItem.
GetModifierRaw()
static vector GetModifierRaw (ItemBase item, string modifier_name, vector value = "1 1 1") inline static private
Definition at line 65 of file PropertyModifiers.c.
Referenced by UpdateModifiers().
UpdateModifiers()
void UpdateModifiers () inline private
Definition at line 38 of file PropertyModifiers.c.
References GetModifierRaw(), m_OwnerItem, m_RecoilModifiers, m_SightMisalignment, and m_SwayModifiers.
Referenced by PropertyModifiers().
Field Documentation
m_BarrelLength
float m_BarrelLength private
Definition at line 7 of file PropertyModifiers.c.
Referenced by PropertyModifiers().
m_OwnerItem
ItemBase m_OwnerItem private
Definition at line 9 of file PropertyModifiers.c.
Referenced by GetBarrelLength(), PropertyModifiers(), and UpdateModifiers().
m_RecoilModifiers
vector m_RecoilModifiers private
Definition at line 3 of file PropertyModifiers.c.
Referenced by UpdateModifiers().
m_SightMisalignment
vector m_SightMisalignment private
Definition at line 5 of file PropertyModifiers.c.
Referenced by UpdateModifiers().
m_SwayModifiers
vector m_SwayModifiers private
Definition at line 4 of file PropertyModifiers.c.
Referenced by UpdateModifiers().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PropertyModifiers.c