DayZ Scripts Documentation: ContaminatedArea_Local Class Reference
ContaminatedArea_Local Class Reference
Private Member Functions
override void SetupZoneData (EffectAreaParams params)
override void EEInit ()
override void SpawnItems ()
override float GetStartDecayLifetime ()
override float GetFinishDecayLifetime ()
override float GetRemainingTime ()
override void Tick ()
Private Attributes
const float TICK_RATE = 1
ref Timer m_Timer1 = new Timer
float m_Lifetime = 360
Detailed Description
Definition at line 1 of file ContaminatedArea_Local.c.
Member Function Documentation
EEInit()
override void EEInit () inline private
Definition at line 26 of file ContaminatedArea_Local.c.
References GetGame(), m_Timer1, SetupZoneData(), and TICK_RATE.
GetFinishDecayLifetime()
override float GetFinishDecayLifetime () inline private
Definition at line 45 of file ContaminatedArea_Local.c.
GetRemainingTime()
override float GetRemainingTime () inline private
Definition at line 50 of file ContaminatedArea_Local.c.
References m_Lifetime.
GetStartDecayLifetime()
override float GetStartDecayLifetime () inline private
Definition at line 40 of file ContaminatedArea_Local.c.
SetupZoneData()
override void SetupZoneData (EffectAreaParams params) inline private
Definition at line 10 of file ContaminatedArea_Local.c.
References ParticleList::CONTAMINATED_AREA_GAS_AROUND.
Referenced by EEInit().
SpawnItems()
override void SpawnItems () inline private
Definition at line 35 of file ContaminatedArea_Local.c.
Tick()
override void Tick () inline private
Definition at line 55 of file ContaminatedArea_Local.c.
References Delete(), m_Lifetime, and TICK_RATE.
Field Documentation
m_Lifetime
float m_Lifetime = 360 private
Definition at line 5 of file ContaminatedArea_Local.c.
Referenced by GetRemainingTime(), and Tick().
m_Timer1
ref Timer m_Timer1 = new Timer private
Definition at line 4 of file ContaminatedArea_Local.c.
Referenced by EEInit().
TICK_RATE
const float TICK_RATE = 1 private
Definition at line 3 of file ContaminatedArea_Local.c.
Referenced by EEInit(), and Tick().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/ContaminatedArea/ContaminatedArea_Local.c