DayZ: Attachments Class Reference
Attachments Class Reference
Private Member Functions
void Attachments (Container parent, EntityAI entity)
void ~Attachments ()
AttachmentsWrapper GetWrapper ()
bool IsEmpty ()
bool IsItemActive ()
bool IsItemWithQuantityActive ()
void UnfocusAll ()
void SetDefaultFocus (bool while_micromanagment_mode=false)
void SetLastActive ()
void SetActive (bool active)
void SelFirstActive ()
SlotsIcon GetFocusedSlotsIcon ()
EntityAI GetFocusedItem ()
int GetFocusedSlot ()
bool SelectItem ()
bool Select ()
int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2)
bool CanCombine ()
bool CanCombineAmmo ()
bool CanEquip ()
bool Combine ()
bool SplitItem ()
bool EquipItem ()
bool TransferItem ()
bool InspectItem ()
bool TransferItemToVicinity ()
bool IsActive ()
int GetAttachmentHeight ()
void UpdateInterval ()
array< int > GetSlotsSorted ()
void AttachmentAdded (EntityAI item, string slot, EntityAI parent)
void AttachmentRemoved (EntityAI item, string slot, EntityAI parent)
void OnAttachmentReservationSet (EntityAI item, int slot_id)
void OnAttachmentReservationRelease (EntityAI item, int slot_id)
void InitAttachmentGrid (int att_row_index)
array< string > GetItemSlots (EntityAI e)
void ShowFalseAttachmentsHeader (bool show)
void SetFalseAttachmentsHeaderText (string text)
TextWidget GetFalseHeaderTextWidget ()
Private Attributes
protected Container m_Parent
protected EntityAI m_Entity
protected ref AttachmentsWrapper m_AttachmentsContainer
protected ref array< string > m_AttachmentSlotNames
protected ref array< string > m_AttachmentSlotDisplayable
protected ref map< int, SlotsIcon > m_AttachmentSlots
protected ref array< int > m_AttachmentIDOrdered
protected int m_RowIndex
Detailed Description
Definition at line 3 of file Attachments.c.
Constructor & Destructor Documentation
Attachments()
void Attachments (Container parent, EntityAI entity) inline private
Definition at line 15 of file Attachments.c.
References AttachmentAdded(), AttachmentRemoved(), GetItemSlots(), m_AttachmentIDOrdered, m_AttachmentSlotDisplayable, m_AttachmentSlotNames, m_AttachmentSlots, m_Entity, m_Parent, OnAttachmentReservationRelease(), and OnAttachmentReservationSet().
~Attachments()
void ~Attachments () inline private
Definition at line 30 of file Attachments.c.
References AttachmentAdded(), AttachmentRemoved(), m_AttachmentsContainer, m_Entity, OnAttachmentReservationRelease(), and OnAttachmentReservationSet().
Member Function Documentation
AttachmentAdded()
void AttachmentAdded (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 408 of file Attachments.c.
References InventorySlots::GetSlotDisplayName(), InventorySlots::GetSlotIdFromString(), SlotsIcon::Init(), m_AttachmentSlots, SlotsIcon::SetSlotDisplayName(), and SlotsIcon::SetSlotID().
Referenced by Attachments(), InitAttachmentGrid(), and ~Attachments().
AttachmentRemoved()
void AttachmentRemoved (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 423 of file Attachments.c.
References SlotsIcon::Clear(), InventorySlots::GetSlotIdFromString(), and m_AttachmentSlots.
Referenced by Attachments(), and ~Attachments().
CanCombine()
bool CanCombine () inline private
Definition at line 197 of file Attachments.c.
References ItemManager::GetCombinationFlags(), GetFocusedItem(), GetGame(), and GetPlayer().
Referenced by AttachmentsWrapper::CanCombine().
CanCombineAmmo()
bool CanCombineAmmo () inline private
Definition at line 205 of file Attachments.c.
References ActionManagerClient::CanPerformActionFromInventory(), Class::CastTo(), GetFocusedItem(), GetGame(), GetPlayer(), and m_player.
Referenced by AttachmentsWrapper::CanCombineAmmo().
CanEquip()
bool CanEquip () inline private
Definition at line 216 of file Attachments.c.
References GetFocusedItem(), GetGame(), and CGame::GetPlayer().
Referenced by AttachmentsWrapper::CanEquip().
Combine()
bool Combine () inline private
Definition at line 227 of file Attachments.c.
References Icon::CombineItems(), GetFocusedItem(), GetGame(), ItemManager::GetHandsPreview(), HandsPreview::GetIcon(), ItemManager::GetInstance(), and GetPlayer().
Referenced by AttachmentsWrapper::Combine().
EquipItem()
bool EquipItem () inline private
Definition at line 255 of file Attachments.c.
References GetFocusedItem(), GetFocusedSlotsIcon(), GetGame(), and CGame::GetPlayer().
Referenced by AttachmentsWrapper::EquipItem().
GetAttachmentHeight()
int GetAttachmentHeight () inline private
Definition at line 308 of file Attachments.c.
References m_AttachmentsContainer.
Referenced by HandsContainer::ShowAtt().
GetFalseHeaderTextWidget()
TextWidget GetFalseHeaderTextWidget () inline private
Definition at line 598 of file Attachments.c.
References AttachmentsWrapper::GetFalseHeaderTextWidget(), and m_AttachmentsContainer.
Referenced by HandsContainer::AttachmentAdded().
GetFocusedItem()
EntityAI GetFocusedItem () inline private
Definition at line 103 of file Attachments.c.
References Container::GetFocusedItem(), and m_AttachmentsContainer.
Referenced by CanCombine(), CanCombineAmmo(), CanEquip(), Combine(), EquipItem(), InspectItem(), IsItemActive(), IsItemWithQuantityActive(), Select(), SelectItem(), SplitItem(), TransferItem(), and TransferItemToVicinity().
GetFocusedSlot()
int GetFocusedSlot () inline private
Definition at line 108 of file Attachments.c.
References SlotsIcon::GetSlotID(), and m_AttachmentsContainer.
Referenced by AttachmentsWrapper::GetFocusedSlot().
GetFocusedSlotsIcon()
SlotsIcon GetFocusedSlotsIcon () inline private
Definition at line 98 of file Attachments.c.
References m_AttachmentsContainer.
Referenced by EquipItem(), Select(), SelectItem(), SplitItem(), TransferItem(), TransferItemToVicinity(), and UpdateInterval().
GetItemSlots()
array< string > GetItemSlots (EntityAI e) inline private
Definition at line 555 of file Attachments.c.
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), and path.
Referenced by Attachments().
GetRecipeCount()
int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2) inline private
Definition at line 191 of file Attachments.c.
References GetGame(), GetPlayer(), and GetPlugin().
GetSlotsSorted()
array< int > GetSlotsSorted () inline private
Definition at line 403 of file Attachments.c.
References m_AttachmentIDOrdered.
Referenced by HandsContainer::ShowAtt().
GetWrapper()
AttachmentsWrapper GetWrapper () inline private
Definition at line 43 of file Attachments.c.
References m_AttachmentsContainer.
Referenced by HandsContainer::AttachmentAdded(), HandsContainer::DestroyAtt(), HandsContainer::OnPerformCombination(), and HandsContainer::SetFocusToIndex().
InitAttachmentGrid()
void InitAttachmentGrid (int att_row_index) inline private
Definition at line 450 of file Attachments.c.
References AttachmentAdded(), Math::Ceil(), SlotsIcon::Clear(), Container::Get(), GetGame(), SlotsIcon::GetGhostSlot(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), InventorySlots::GetSlotDisplayName(), SlotsContainer::GetSlotIcon(), InventorySlots::GetSlotIdFromString(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, ITEMS_IN_ROW, m_AttachmentIDOrdered, m_AttachmentsContainer, m_AttachmentSlotNames, m_AttachmentSlots, m_Entity, m_Parent, m_RowIndex, name, path, WidgetEventHandler::RegisterOnDoubleClick(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), AttachmentsWrapper::SetFalseAttachmentsHeaderText(), AttachmentsWrapper::SetParent(), SlotsIcon::SetSlotDisplayName(), SlotsIcon::SetSlotID(), string::ToUpper(), and StaticGUIUtils::VerifyIconImageString().
Referenced by HandsContainer::AttachmentAdded(), HandsContainer::OnPerformCombination(), and HandsContainer::ShowAtt().
InspectItem()
bool InspectItem () inline private
Definition at line 277 of file Attachments.c.
References GetFocusedItem(), and m_Parent.
Referenced by AttachmentsWrapper::InspectItem().
IsActive()
bool IsActive () inline private
Definition at line 303 of file Attachments.c.
References m_Parent.
IsEmpty()
bool IsEmpty () inline private
Definition at line 48 of file Attachments.c.
References Container::IsEmpty(), and m_AttachmentsContainer.
Referenced by IsItemActive(), and IsItemWithQuantityActive().
IsItemActive()
bool IsItemActive () inline private
Definition at line 53 of file Attachments.c.
References GetFocusedItem(), QuantityConversions::HasItemQuantity(), and IsEmpty().
Referenced by AttachmentsWrapper::IsItemActive().
IsItemWithQuantityActive()
bool IsItemWithQuantityActive () inline private
Definition at line 63 of file Attachments.c.
References GetFocusedItem(), QuantityConversions::HasItemQuantity(), and IsEmpty().
Referenced by AttachmentsWrapper::IsItemWithQuantityActive().
OnAttachmentReservationRelease()
void OnAttachmentReservationRelease (EntityAI item, int slot_id) inline private
Definition at line 443 of file Attachments.c.
References SlotsIcon::Clear(), and m_AttachmentSlots.
Referenced by Attachments(), and ~Attachments().
OnAttachmentReservationSet()
void OnAttachmentReservationSet (EntityAI item, int slot_id) inline private
Definition at line 433 of file Attachments.c.
References SlotsIcon::Init(), and m_AttachmentSlots.
Referenced by Attachments(), and ~Attachments().
Select()
bool Select () inline private
Definition at line 129 of file Attachments.c.
References GameInventory::CanSwapEntitiesEx(), GetFocusedItem(), GetFocusedSlotsIcon(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), ItemManager::GetSelectedIcon(), ItemManager::GetSelectedItem(), InventoryLocation::GetSlot(), SlotsIcon::GetSlotID(), AttachmentsOutOfReach::IsAttachmentReachable(), SlotsIcon::IsOutOfReach(), SlotsIcon::IsReserved(), m_Entity, and ItemManager::SetSelectedItem().
Referenced by AttachmentsWrapper::Select().
SelectItem()
bool SelectItem () inline private
Definition at line 116 of file Attachments.c.
References SlotsIcon::GetCursorWidget(), GetFocusedItem(), GetFocusedSlotsIcon(), ItemManager::GetInstance(), SlotsIcon::IsOutOfReach(), and ItemManager::SetSelectedItem().
Referenced by AttachmentsWrapper::SelectItem().
SelFirstActive()
void SelFirstActive () inline private
Definition at line 93 of file Attachments.c.
References m_AttachmentsContainer.
SetActive()
void SetActive (bool active) inline private
Definition at line 88 of file Attachments.c.
References m_AttachmentsContainer, and AttachmentsGroupContainer::SetActive().
SetDefaultFocus()
void SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 78 of file Attachments.c.
References m_AttachmentsContainer, and AttachmentsGroupContainer::SetDefaultFocus().
Referenced by HandsContainer::SetFocusToIndex(), and UpdateInterval().
SetFalseAttachmentsHeaderText()
void SetFalseAttachmentsHeaderText (string text) inline private
Definition at line 593 of file Attachments.c.
References m_AttachmentsContainer, and AttachmentsWrapper::SetFalseAttachmentsHeaderText().
SetLastActive()
void SetLastActive () inline private
Definition at line 83 of file Attachments.c.
References m_AttachmentsContainer, and Container::SetLastActive().
ShowFalseAttachmentsHeader()
void ShowFalseAttachmentsHeader (bool show) inline private
Definition at line 588 of file Attachments.c.
References m_AttachmentsContainer, and AttachmentsWrapper::ShowFalseAttachmentsHeader().
Referenced by HandsContainer::AttachmentAdded().
SplitItem()
bool SplitItem () inline private
Definition at line 241 of file Attachments.c.
References GetFocusedItem(), and GetFocusedSlotsIcon().
Referenced by AttachmentsWrapper::SplitItem().
TransferItem()
bool TransferItem () inline private
Definition at line 266 of file Attachments.c.
References GetFocusedItem(), GetFocusedSlotsIcon(), GetGame(), and CGame::GetPlayer().
Referenced by AttachmentsWrapper::TransferItem().
TransferItemToVicinity()
bool TransferItemToVicinity () inline private
Definition at line 288 of file Attachments.c.
References GetFocusedItem(), GetFocusedSlotsIcon(), GetGame(), and GetPlayer().
Referenced by AttachmentsWrapper::TransferItemToVicinity().
UnfocusAll()
void UnfocusAll () inline private
Definition at line 73 of file Attachments.c.
References m_AttachmentsContainer, and Container::UnfocusAll().
Referenced by HandsContainer::UnfocusGrid().
UpdateInterval()
void UpdateInterval () inline private
Definition at line 313 of file Attachments.c.
References ItemManager::GetDraggedItem(), SlotsIcon::GetEntity(), GetFocusedSlotsIcon(), GetGame(), ItemManager::GetInstance(), SlotsIcon::GetMountedWidget(), SlotsIcon::GetOutOfReachWidget(), SlotsIcon::GetPanelWidget(), GetPlayer(), InventorySlots::GetSlotIdFromString(), AttachmentsOutOfReach::IsAttachmentReachable(), SlotsIcon::IsReserved(), m_AttachmentsContainer, m_AttachmentSlotDisplayable, m_AttachmentSlotNames, m_AttachmentSlots, m_Entity, m_Parent, SetDefaultFocus(), SlotsIcon::UpdateInterval(), and Container::UpdateRadialIcon().
Referenced by HandsContainer::AttachmentAdded(), AttachmentsWrapper::UpdateInterval(), and HandsContainer::UpdateInterval().
Field Documentation
m_AttachmentIDOrdered
protected ref array<int> m_AttachmentIDOrdered private
Definition at line 11 of file Attachments.c.
Referenced by Attachments(), GetSlotsSorted(), and InitAttachmentGrid().
m_AttachmentsContainer
protected ref AttachmentsWrapper m_AttachmentsContainer private
Definition at line 7 of file Attachments.c.
Referenced by GetAttachmentHeight(), GetFalseHeaderTextWidget(), GetFocusedItem(), GetFocusedSlot(), GetFocusedSlotsIcon(), GetWrapper(), InitAttachmentGrid(), IsEmpty(), SelFirstActive(), SetActive(), SetDefaultFocus(), SetFalseAttachmentsHeaderText(), SetLastActive(), ShowFalseAttachmentsHeader(), UnfocusAll(), UpdateInterval(), and ~Attachments().
m_AttachmentSlotDisplayable
protected ref array<string> m_AttachmentSlotDisplayable private
Definition at line 9 of file Attachments.c.
Referenced by Attachments(), and UpdateInterval().
m_AttachmentSlotNames
protected ref array<string> m_AttachmentSlotNames private
Definition at line 8 of file Attachments.c.
Referenced by Attachments(), InitAttachmentGrid(), and UpdateInterval().
m_AttachmentSlots
protected ref map<int, SlotsIcon> m_AttachmentSlots private
Definition at line 10 of file Attachments.c.
Referenced by AttachmentAdded(), AttachmentRemoved(), Attachments(), InitAttachmentGrid(), OnAttachmentReservationRelease(), OnAttachmentReservationSet(), and UpdateInterval().
m_Entity
protected EntityAI m_Entity private
Definition at line 6 of file Attachments.c.
Referenced by Attachments(), InitAttachmentGrid(), Select(), UpdateInterval(), and ~Attachments().
m_Parent
protected Container m_Parent private
Definition at line 5 of file Attachments.c.
Referenced by Attachments(), InitAttachmentGrid(), InspectItem(), IsActive(), and UpdateInterval().
m_RowIndex
protected int m_RowIndex private
Definition at line 13 of file Attachments.c.
Referenced by InitAttachmentGrid().
The documentation for this class was generated from the following file:
5_Mission/GUI/InventoryNew/Attachments.c