DayZ Scripts Documentation: HumanCommandMove Class Reference
HumanCommandMove Class Reference
Private Member Functions
private void HumanCommandMove ()
private void ~HumanCommandMove ()
proto native float GetCurrentMovementAngle ()
proto bool GetCurrentInputAngle (out float pAngle)
proto native float GetCurrentMovementSpeed ()
0,1,2..3 idle, walk, run, sprint
proto native bool IsChangingStance ()
returns true if character is changing stance
proto native bool IsOnBack ()
return true if prone is on back
proto native bool IsInRoll ()
return true if character barrel rolling
proto native bool IsLeavingUncon ()
return true if character transitions out of uncon
proto native bool IsStandingFromBack ()
return true if prone on back is chaning to crounch/stand
proto native void StartMeleeEvade ()
marks command to continue to combo
proto native void StartMeleeEvadeA (float pDirAngle)
marks command to continue to combo, pDirAngle specifies angle
proto native bool IsMeleeEvade ()
this is true when in melee evade
proto native void SetMeleeBlock (bool pBlock)
this enables/disables block
proto native void ForceStance (int pStanceIdx)
proto native void ForceStanceUp (int pStanceIdx)
proto native void SetRunSprintFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fRunSpringTimeout
proto native void SetDirectionFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterTimeout
proto native void SetDirectionSprintFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterSprintTimeout
proto native void SetTurnSpanModifier (float value)
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingFilterSpan
proto native void SetTurnSpanSprintModifier (float value)
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingSprintFilterSpan
proto native void SetCurrentWaterLevel (float value)
sets water level (depth)
Detailed Description
Definition at line 421 of file human.c.
Constructor & Destructor Documentation
HumanCommandMove()
private void HumanCommandMove () inline private
Definition at line 423 of file human.c.
~HumanCommandMove()
private void ~HumanCommandMove () inline private
Definition at line 424 of file human.c.
Member Function Documentation
ForceStance()
proto native void ForceStance (int pStanceIdx) private
pStanceIds is one of STANCEIDX_ERECT,STANCEIDX_CROUCH,STANCEIDX_PRONE,STANCEIDX_RAISEDERECT,STANCEIDX_RAISEDCROUCH,STANCEIDX_RAISEDPRONE, or -1 when release the stance lock
Referenced by ManBase::BrokenLegForceProne(), PluginDayzPlayerDebug_Ctrl::CommandHandler(), ManBase::EEItemIntoHands(), ForceStandUpForHeavyItems(), HandleFightLogic(), and HandleInitialFirearmMelee().
ForceStanceUp()
proto native void ForceStanceUp (int pStanceIdx) private
pStanceIds is one of STANCEIDX_ERECT,STANCEIDX_CROUCH this forces to stand up to required stance
Referenced by DayZPlayerImplementSwimming::HandleSwimming().
GetCurrentInputAngle()
proto bool GetCurrentInputAngle (out float pAngle) private
direction held on keyboard/controller -180 -90 0 90 180 angles of input movement (no filtering, no postprocesses) return false in idle states
Referenced by HandleFightLogic().
GetCurrentMovementAngle()
proto native float GetCurrentMovementAngle () private
marks command to continue to combo -180 -90 0 90 180 angles of current movement
GetCurrentMovementSpeed()
proto native float GetCurrentMovementSpeed () private
0,1,2..3 idle, walk, run, sprint
Referenced by Environment::CollectAndSetPlayerData(), DayZPlayer::CommandHandler(), ManBase::ContaminatedParticleAdjustment(), HandleInitialFirearmMelee(), and DayZPlayerCameraBase::OnUpdate().
IsChangingStance()
proto native bool IsChangingStance () private
returns true if character is changing stance
Referenced by ActionCondition().
IsInRoll()
proto native bool IsInRoll () private
return true if character barrel rolling
Referenced by ManBase::IsRolling().
IsLeavingUncon()
proto native bool IsLeavingUncon () private
return true if character transitions out of uncon
IsMeleeEvade()
proto native bool IsMeleeEvade () private
this is true when in melee evade
IsOnBack()
proto native bool IsOnBack () private
return true if prone is on back
Referenced by ManBase::CanRoll().
IsStandingFromBack()
proto native bool IsStandingFromBack () private
return true if prone on back is chaning to crounch/stand
Referenced by DayZPlayer::HeadingModel().
SetCurrentWaterLevel()
proto native void SetCurrentWaterLevel (float value) private
sets water level (depth)
Referenced by DayZPlayerImplementSwimming::HandleSwimming().
SetDirectionFilterModifier()
proto native void SetDirectionFilterModifier (float value) private
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterTimeout
SetDirectionSprintFilterModifier()
proto native void SetDirectionSprintFilterModifier (float value) private
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterSprintTimeout
Referenced by ManBase::UpdateMovementInertia().
SetMeleeBlock()
proto native void SetMeleeBlock (bool pBlock) private
this enables/disables block
Referenced by ManBase::EEItemIntoHands(), Weapon::EEItemLocationChanged(), and HandleFightLogic().
SetRunSprintFilterModifier()
proto native void SetRunSprintFilterModifier (float value) private
sets the multiplier for SHumanCommandMoveSettings::m_fRunSpringTimeout
Referenced by ManBase::UpdateMovementInertia().
SetTurnSpanModifier()
proto native void SetTurnSpanModifier (float value) private
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingFilterSpan
SetTurnSpanSprintModifier()
proto native void SetTurnSpanSprintModifier (float value) private
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingSprintFilterSpan
Referenced by ManBase::UpdateMovementInertia().
StartMeleeEvade()
proto native void StartMeleeEvade () private
marks command to continue to combo
StartMeleeEvadeA()
proto native void StartMeleeEvadeA (float pDirAngle) private
marks command to continue to combo, pDirAngle specifies angle
Referenced by HandleFightLogic().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/human.c