DayZ: ActionBandageTarget Class Reference
ActionBandageTarget Class Reference
Private Member Functions
void ActionBandageTarget ()
override void CreateConditionComponents ()
override int GetStanceMask (PlayerBase player)
override void OnFinishProgressServer (ActionData action_data)
override void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 13 of file ActionBandageTarget.c.
Constructor & Destructor Documentation
ActionBandageTarget()
void ActionBandageTarget () inline private
Definition at line 15 of file ActionBandageTarget.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 25 of file ActionBandageTarget.c.
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetStanceMask()
override int GetStanceMask (PlayerBase player) inline private
Definition at line 32 of file ActionBandageTarget.c.
OnFinishProgressClient()
override void OnFinishProgressClient (ActionData action_data) inline private
Definition at line 62 of file ActionBandageTarget.c.
References CGame::GetAnalyticsClient(), GetGame(), and AnalyticsManagerClient::OnActionBandageTarget().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 48 of file ActionBandageTarget.c.
References ActionBandageBase::ApplyBandage(), CanReceiveAction(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Continuous/Medical/ActionBandageTarget.c