DayZ Scripts Documentation: Mission Class Reference
Mission Class Reference
Mission class.
Private Member Functions
private void ~Mission ()
void OnInit ()
void OnMissionStart ()
void OnMissionFinish ()
void OnUpdate (float timeslice)
void OnKeyPress (int key)
void OnKeyRelease (int key)
void OnMouseButtonPress (int button)
void OnMouseButtonRelease (int button)
void OnEvent (EventType eventTypeId, Param params)
void OnItemUsed (InventoryItem item, Man owner)
void AddDummyPlayerToScheduler (Man player)
void Reset ()
void ResetGUI ()
void OnGameplayDataHandlerLoad ()
Hud GetHud ()
bool IsPlayerDisconnecting (Man player)
UIScriptedMenu CreateScriptedMenu (int id)
UIScriptedWindow CreateScriptedWindow (int id)
WorldData GetWorldData ()
WorldLighting GetWorldLighting ()
bool IsPaused ()
bool IsGame ()
bool IsServer ()
void Pause ()
void Continue ()
void AbortMission ()
void CreateLogoutMenu (UIMenuPanel parent)
void StartLogoutMenu (int time)
void CreateDebugMonitor ()
void RefreshCrosshairVisibility ()
void HideCrosshairVisibility ()
bool IsMissionGameplay ()
bool IsControlDisabled ()
int GetControlDisabledMode ()
void PlayerControlEnable (bool bForceSupress)
void PlayerControlDisable (int mode)
deprecated
void RemoveActiveInputExcludes (array< string > excludes, bool bForceSupress=false)
deprecated
void RemoveActiveInputRestriction (int restrictor)
void AddActiveInputExcludes (array< string > excludes)
void AddActiveInputRestriction (int restrictor)
void RefreshExcludes ()
bool IsInputExcludeActive (string exclude)
bool IsInputRestrictionActive (int restriction)
void EnableAllInputs (bool bForceSupress=false)
void ShowInventory ()
void HideInventory ()
void ShowChat ()
void HideChat ()
void UpdateVoiceLevelWidgets (int level)
void HideVoiceLevelWidgets ()
bool IsVoNActive ()
void SetVoNActive (bool active)
bool InsertCorpse (Man player)
UIScriptedMenu GetNoteMenu ()
void SetNoteMenu (UIScriptedMenu menu)
void SetPlayerRespawning (bool state)
void OnPlayerRespawned (Man player)
bool IsPlayerRespawning ()
array< vector > GetActiveRefresherLocations ()
void SetRespawnModeClient (int mode)
for client-side usage
int GetRespawnModeClient ()
void SyncRespawnModeInfo (PlayerIdentity identity)
server-side
ImageWidget GetMicrophoneIcon ()
WidgetFadeTimer GetMicWidgetFadeTimer ()
GameplayEffectWidgets_base GetEffectWidgets ()
map< int, ImageWidget > GetVoiceLevelWidgets ()
map< int, ref WidgetFadeTimer > GetVoiceLevelTimers ()
ScriptInvoker GetOnInputDeviceChanged ()
ScriptInvoker GetOnInputPresetChanged ()
ScriptInvoker GetOnInputDeviceConnected ()
ScriptInvoker GetOnInputDeviceDisconnected ()
Private Attributes
ScriptModule MissionScript
ref array< vector > m_ActiveRefresherLocations
protected ref ScriptInvoker m_OnInputDeviceChanged = new ScriptInvoker()
protected ref ScriptInvoker m_OnInputPresetChanged = new ScriptInvoker()
protected ref ScriptInvoker m_OnInputDeviceConnected = new ScriptInvoker()
protected ref ScriptInvoker m_OnInputDeviceDisconnected = new ScriptInvoker()
Detailed Description
Mission class.
Definition at line 666 of file gameplay.c.
Constructor & Destructor Documentation
~Mission()
private void ~Mission () private
Member Function Documentation
AbortMission()
void AbortMission () inline private
Definition at line 739 of file gameplay.c.
Referenced by DisconnectSessionEx(), UIScriptedMenu::Exit(), UIScriptedMenu::OnClick(), and UIScriptedMenu::OnModalResult().
AddActiveInputExcludes()
void AddActiveInputExcludes (array< string > excludes) private
Referenced by MissionBase::HandleMapToggleByKeyboardShortcut(), ScriptedWidgetEventHandler::OnMouseEnter(), ManBase::OnRPC(), UIScriptedMenu::OnShow(), ActionUnfoldMapCB::PerformMapChange(), PluginBase::ToggleScriptConsole(), and UIScriptedMenu::WarningMenuBase().
AddActiveInputRestriction()
void AddActiveInputRestriction (int restrictor) private
Referenced by MissionBase::HandleMapToggleByKeyboardShortcut(), and ActionUnfoldMapCB::PerformMapChange().
AddDummyPlayerToScheduler()
void AddDummyPlayerToScheduler (Man player) inline private
Definition at line 689 of file gameplay.c.
Referenced by ManBase::OnSpawnedFromConsole().
Continue()
void Continue () inline private
Definition at line 737 of file gameplay.c.
Referenced by UIScriptedMenu::Cancel(), UIScriptedMenu::Exit(), UIScriptedMenu::~InGameMenu(), and UIScriptedMenu::~InGameMenuXbox().
CreateDebugMonitor()
void CreateDebugMonitor () inline private
Definition at line 744 of file gameplay.c.
Referenced by DebugMonitorValues::ReceiveValue().
CreateLogoutMenu()
void CreateLogoutMenu (UIMenuPanel parent) inline private
Definition at line 741 of file gameplay.c.
CreateScriptedMenu()
UIScriptedMenu CreateScriptedMenu (int id) inline private
Definition at line 701 of file gameplay.c.
Referenced by CreateScriptedMenu().
CreateScriptedWindow()
UIScriptedWindow CreateScriptedWindow (int id) inline private
Definition at line 706 of file gameplay.c.
Referenced by UIManager::OpenWindow().
EnableAllInputs()
void EnableAllInputs (bool bForceSupress = false) private
Referenced by UIScriptedMenu::OnClick(), ManBase::OnSelectPlayer(), and UIScriptedMenu::~ScriptConsole().
GetActiveRefresherLocations()
array< vector > GetActiveRefresherLocations () private
Referenced by ManBase::IsTargetInActiveRefresherRange().
GetControlDisabledMode()
int GetControlDisabledMode () inline private
Definition at line 756 of file gameplay.c.
GetEffectWidgets()
GameplayEffectWidgets_base GetEffectWidgets () inline private
Definition at line 809 of file gameplay.c.
Referenced by BleedingSourcesManagerBase::Init(), ScriptedWidgetEventHandler::OnBleedingIndicationChanged(), ManBase::OnPlayerLoaded(), PPERequester_GameplayBase::OnStart(), PPERequester_GameplayBase::OnStop(), PPERequester_GameplayBase::OnUpdate(), BleedingSourcesManagerBase::RegisterBleedingZoneEx(), StartSourceBleedingIndication(), StopSourceBleedingIndication(), and GameplayEffectsData::Update().
GetHud()
Hud GetHud () inline private
Definition at line 694 of file gameplay.c.
Referenced by PluginBase::DisplayTendency(), ScriptedWidgetEventHandler::GetHud(), DayZPlayer::HandleDamageHit(), UIScriptedMenu::HudShow(), ManBase::Init(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::InspectItem(), UIScriptedMenu::NoteMenu(), OnConnectivityStatChange(), UIScriptedMenu::OnHide(), OnHide(), UIScriptedMenu::OnShow(), OnShow(), ManBase::OnUnconsciousStop(), ManBase::OnUnconsciousUpdate(), UIScriptedMenu::ScriptConsole(), PluginBase::SetBadge(), PluginBase::SetStamina(), PluginBase::SetStance(), PluginBase::SwitchPermanentCrossHair(), ScriptedWidgetEventHandler::Update(), UpdateSpecialtyMeter(), VirtualHud(), UIScriptedMenu::~InGameMenuXbox(), UIScriptedMenu::~InspectMenuNew(), UIScriptedMenu::~NoteMenu(), and UIScriptedMenu::~ScriptConsole().
GetMicrophoneIcon()
ImageWidget GetMicrophoneIcon () inline private
Definition at line 802 of file gameplay.c.
Referenced by IsVonToggled(), and ShowVoiceNotification().
GetMicWidgetFadeTimer()
WidgetFadeTimer GetMicWidgetFadeTimer () inline private
Definition at line 807 of file gameplay.c.
Referenced by ShowVoiceNotification().
GetNoteMenu()
UIScriptedMenu GetNoteMenu () inline private
Definition at line 786 of file gameplay.c.
GetOnInputDeviceChanged()
ScriptInvoker GetOnInputDeviceChanged () inline private
Definition at line 815 of file gameplay.c.
References m_OnInputDeviceChanged.
Referenced by ScriptedWidgetEventHandler::ActionTargetsCursor(), ServerBrowserTab::Construct(), UIScriptedMenu::InGameMenuXbox(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), Inventory(), ScriptedWidgetEventHandler::ItemActionsWidget(), and Input::OnLastInputDeviceChanged().
GetOnInputDeviceConnected()
ScriptInvoker GetOnInputDeviceConnected () inline private
Definition at line 835 of file gameplay.c.
References m_OnInputDeviceConnected.
Referenced by Input::OnGamepadConnected(), Input::OnGamepadIdentification(), Input::OnKeyboardConnected(), and Input::OnMouseConnected().
GetOnInputDeviceDisconnected()
ScriptInvoker GetOnInputDeviceDisconnected () inline private
Definition at line 845 of file gameplay.c.
References m_OnInputDeviceDisconnected.
Referenced by Input::OnGamepadDisconnected(), Input::OnKeyboardDisconnected(), and Input::OnMouseDisconnected().
GetOnInputPresetChanged()
ScriptInvoker GetOnInputPresetChanged () inline private
Definition at line 825 of file gameplay.c.
References m_OnInputPresetChanged.
Referenced by ScriptedWidgetEventHandler::ActionTargetsCursor(), UIScriptedMenu::GesturesMenu(), UIScriptedMenu::InGameMenuXbox(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), Inventory(), ScriptedWidgetEventHandler::ItemActionsWidget(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnSelectKBPreset(), UIScriptedMenu::PerformSwitchPreset(), UIScriptedMenu::RadialQuickbarMenu(), and SwitchPreset().
GetRespawnModeClient()
int GetRespawnModeClient () inline private
Definition at line 795 of file gameplay.c.
GetVoiceLevelTimers()
map< int, ref WidgetFadeTimer > GetVoiceLevelTimers () inline private
Definition at line 813 of file gameplay.c.
Referenced by ShowVoiceNotification().
GetVoiceLevelWidgets()
map< int, ImageWidget > GetVoiceLevelWidgets () inline private
Definition at line 811 of file gameplay.c.
Referenced by ShowVoiceNotification().
GetWorldData()
WorldData GetWorldData () inline private
Definition at line 711 of file gameplay.c.
Referenced by ContaminatedArea_Dynamic::EEOnCECreate(), and WeatherPhenomenon::OnBeforeChange().
GetWorldLighting()
WorldLighting GetWorldLighting () inline private
Definition at line 716 of file gameplay.c.
Referenced by ManBase::UpdateLighting().
HideChat()
void HideChat () inline private
Definition at line 774 of file gameplay.c.
Referenced by UIScriptedMenu::OnHide().
HideCrosshairVisibility()
void HideCrosshairVisibility () inline private
Definition at line 748 of file gameplay.c.
HideInventory()
void HideInventory () inline private
Definition at line 771 of file gameplay.c.
Referenced by Dispatcher::MissionGameplayHideInventory(), ClothingBase::OnWasAttached(), InventoryActionHandler::SetAction(), and UpdateInterval().
HideVoiceLevelWidgets()
void HideVoiceLevelWidgets () inline private
Definition at line 777 of file gameplay.c.
Referenced by IsVonToggled(), and UIScriptedMenu::OnHide().
InsertCorpse()
bool InsertCorpse (Man player) inline private
Definition at line 781 of file gameplay.c.
IsControlDisabled()
bool IsControlDisabled () inline private
Definition at line 755 of file gameplay.c.
IsGame()
bool IsGame () inline private
Definition at line 726 of file gameplay.c.
IsInputExcludeActive()
bool IsInputExcludeActive (string exclude) private
IsInputRestrictionActive()
bool IsInputRestrictionActive (int restriction) private
IsMissionGameplay()
bool IsMissionGameplay () inline private
Definition at line 750 of file gameplay.c.
IsPaused()
bool IsPaused () inline private
Definition at line 721 of file gameplay.c.
Referenced by OnUpdate().
IsPlayerDisconnecting()
bool IsPlayerDisconnecting (Man player) private
Referenced by ActionRestrainTarget::ActionConditionContinue().
IsPlayerRespawning()
bool IsPlayerRespawning () private
IsServer()
bool IsServer () inline private
Definition at line 731 of file gameplay.c.
IsVoNActive()
bool IsVoNActive () inline private
Definition at line 778 of file gameplay.c.
Referenced by OnEvent().
OnEvent()
void OnEvent (EventType eventTypeId, Param params) inline private
Definition at line 687 of file gameplay.c.
Referenced by OnEvent().
OnGameplayDataHandlerLoad()
void OnGameplayDataHandlerLoad () inline private
Definition at line 692 of file gameplay.c.
Referenced by CfgGameplayHandler::OnLoaded().
OnInit()
void OnInit () inline private
Definition at line 679 of file gameplay.c.
OnItemUsed()
void OnItemUsed (InventoryItem item, Man owner) inline private
Definition at line 688 of file gameplay.c.
OnKeyPress()
void OnKeyPress (int key) inline private
Definition at line 683 of file gameplay.c.
Referenced by OnKeyPress().
OnKeyRelease()
void OnKeyRelease (int key) inline private
Definition at line 684 of file gameplay.c.
Referenced by OnKeyRelease().
OnMissionFinish()
void OnMissionFinish () inline private
Definition at line 681 of file gameplay.c.
OnMissionStart()
void OnMissionStart () inline private
Definition at line 680 of file gameplay.c.
OnMouseButtonPress()
void OnMouseButtonPress (int button) inline private
Definition at line 685 of file gameplay.c.
Referenced by OnMouseButtonPress().
OnMouseButtonRelease()
void OnMouseButtonRelease (int button) inline private
Definition at line 686 of file gameplay.c.
Referenced by OnMouseButtonRelease().
OnPlayerRespawned()
void OnPlayerRespawned (Man player) private
Referenced by ManBase::OnPlayerLoaded().
OnUpdate()
void OnUpdate (float timeslice) inline private
Definition at line 682 of file gameplay.c.
Referenced by OnUpdate().
Pause()
void Pause () inline private
Definition at line 736 of file gameplay.c.
Referenced by CheckDialogs(), and UIScriptedMenu::Init().
PlayerControlDisable()
void PlayerControlDisable (int mode) private
deprecated
PlayerControlEnable()
void PlayerControlEnable (bool bForceSupress) private
RefreshCrosshairVisibility()
void RefreshCrosshairVisibility () inline private
Definition at line 746 of file gameplay.c.
Referenced by DeveloperFreeCamera::DisableFreeCamera(), DeveloperFreeCamera::EnableFreeCamera(), and DeveloperFreeCamera::OnSetFreeCameraEvent().
RefreshExcludes()
void RefreshExcludes () private
RemoveActiveInputExcludes()
void RemoveActiveInputExcludes (array< string > excludes, bool bForceSupress = false) private
deprecated
Referenced by ManBase::CloseInventoryMenu(), ManBase::CloseMapEx(), UIScriptedMenu::CloseMapMenu(), UIScriptedMenu::OnHide(), UIScriptedMenu::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnMouseLeave(), ManBase::OnRestrainStart(), PluginBase::ToggleScriptConsole(), ActionUnfoldMapCB::~ActionUnfoldMapCB(), UIScriptedMenu::~GesturesMenu(), UIScriptedMenu::~RadialQuickbarMenu(), and UIScriptedMenu::~WarningMenuBase().
RemoveActiveInputRestriction()
void RemoveActiveInputRestriction (int restrictor) private
Referenced by ManBase::CloseInventoryMenu(), ManBase::CloseMapEx(), UIScriptedMenu::CloseMapMenu(), ManBase::OnRestrainStart(), and ActionUnfoldMapCB::~ActionUnfoldMapCB().
Reset()
void Reset () inline private
Definition at line 690 of file gameplay.c.
Referenced by Input::OnGamepadIdentification(), and BiosUserManager::OnUserPicked().
ResetGUI()
void ResetGUI () inline private
Definition at line 691 of file gameplay.c.
Referenced by ScriptedWidgetEventHandler::Apply(), ManBase::OnSelectPlayer(), and PluginBase::ResetGUI().
SetNoteMenu()
void SetNoteMenu (UIScriptedMenu menu) inline private
Definition at line 787 of file gameplay.c.
SetPlayerRespawning()
void SetPlayerRespawning (bool state) private
Referenced by ManBase::OnPlayerLoaded().
SetRespawnModeClient()
void SetRespawnModeClient (int mode) private
for client-side usage
Referenced by ManBase::OnGameplayDataHandlerSync().
SetVoNActive()
void SetVoNActive (bool active) inline private
Definition at line 779 of file gameplay.c.
Referenced by OnEvent().
ShowChat()
void ShowChat () inline private
Definition at line 773 of file gameplay.c.
ShowInventory()
void ShowInventory () inline private
Definition at line 770 of file gameplay.c.
StartLogoutMenu()
void StartLogoutMenu (int time) inline private
Definition at line 742 of file gameplay.c.
SyncRespawnModeInfo()
void SyncRespawnModeInfo (PlayerIdentity identity) inline private
server-side
Definition at line 800 of file gameplay.c.
Referenced by ManBase::EEKilled(), and ManBase::OnSelectPlayer().
UpdateVoiceLevelWidgets()
void UpdateVoiceLevelWidgets (int level) inline private
Definition at line 775 of file gameplay.c.
Referenced by UpdateVoiceLevel().
Field Documentation
m_ActiveRefresherLocations
ref array<vector> m_ActiveRefresherLocations private
Definition at line 670 of file gameplay.c.
Referenced by BaseBuildingBase::HandleRefreshers(), BaseBuildingBase::InsertRefresherPosition(), and BaseBuildingBase::RemoveRefresherPosition().
m_OnInputDeviceChanged
protected ref ScriptInvoker m_OnInputDeviceChanged = new ScriptInvoker() private
Definition at line 672 of file gameplay.c.
Referenced by GetOnInputDeviceChanged().
m_OnInputDeviceConnected
protected ref ScriptInvoker m_OnInputDeviceConnected = new ScriptInvoker() private
Definition at line 674 of file gameplay.c.
Referenced by GetOnInputDeviceConnected().
m_OnInputDeviceDisconnected
protected ref ScriptInvoker m_OnInputDeviceDisconnected = new ScriptInvoker() private
Definition at line 675 of file gameplay.c.
Referenced by GetOnInputDeviceDisconnected().
m_OnInputPresetChanged
protected ref ScriptInvoker m_OnInputPresetChanged = new ScriptInvoker() private
Definition at line 673 of file gameplay.c.
Referenced by GetOnInputPresetChanged().
MissionScript
ScriptModule MissionScript private
Definition at line 668 of file gameplay.c.
The documentation for this class was generated from the following file:
P:/scripts/3_Game/gameplay.c