DayZ: PumpkinHelmet Class Reference
PumpkinHelmet Class Reference
Private Member Functions
void PumpkinHelmet ()
override bool CanPutAsAttachment (EntityAI parent)
override void OnMovedInsideCargo (EntityAI container)
override void OnMovedWithinCargo (EntityAI container)
override void OnRemovedFromCargo (EntityAI container)
override void EOnInit (IEntity other, int extra)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
void UpdateGlowState ()
override void UpdateNVGStatus (PlayerBase player, bool attaching=false, bool force_disable=false)
Detailed Description
Definition at line 3 of file PumpkinHelmet.c.
Constructor & Destructor Documentation
PumpkinHelmet()
void PumpkinHelmet () inline private
Definition at line 5 of file PumpkinHelmet.c.
Member Function Documentation
CanPutAsAttachment()
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 10 of file PumpkinHelmet.c.
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 56 of file PumpkinHelmet.c.
References UpdateGlowState().
EOnInit()
override void EOnInit (IEntity other, int extra) inline private
Definition at line 44 of file PumpkinHelmet.c.
References UpdateGlowState().
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 49 of file PumpkinHelmet.c.
References UpdateGlowState().
OnMovedInsideCargo()
override void OnMovedInsideCargo (EntityAI container) inline private
Definition at line 29 of file PumpkinHelmet.c.
References UpdateGlowState().
OnMovedWithinCargo()
override void OnMovedWithinCargo (EntityAI container) inline private
Definition at line 34 of file PumpkinHelmet.c.
References UpdateGlowState().
OnRemovedFromCargo()
override void OnRemovedFromCargo (EntityAI container) inline private
Definition at line 39 of file PumpkinHelmet.c.
References UpdateGlowState().
UpdateGlowState()
void UpdateGlowState () inline private
Definition at line 63 of file PumpkinHelmet.c.
References InventoryLocation::GetIdx(), InventoryLocation::GetSlot(), and IsDamageDestroyed().
Referenced by EEHealthLevelChanged(), EOnInit(), OnItemLocationChanged(), OnMovedInsideCargo(), OnMovedWithinCargo(), and OnRemovedFromCargo().
UpdateNVGStatus()
override void UpdateNVGStatus (PlayerBase player, bool attaching = false, bool force_disable = false) inline private
Definition at line 92 of file PumpkinHelmet.c.
References GetGame().
The documentation for this class was generated from the following file:
4_World/Entities/ItemBase/PumpkinHelmet.c