DayZ Scripts: DoubleBarrel_Base Class Reference
DoubleBarrel_Base Class Reference
Private Member Functions
override void InitStateMachine ()
override bool CanChamberBullet (int muzzleIndex, Magazine mag)
override void SetActions ()
Private Attributes
ref WeaponStateBase L_L
ref WeaponStateBase L_E
ref WeaponStateBase E_L
ref WeaponStateBase F_L
ref WeaponStateBase F_F
ref WeaponStateBase F_E
ref WeaponStateBase E_F
ref WeaponStateBase E_E
Detailed Description
Definition at line 119 of file DoubleBarrel_Base.c.
Member Function Documentation
CanChamberBullet()
override bool CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 299 of file DoubleBarrel_Base.c.
References IsChamberFiredOut().
InitStateMachine()
override void InitStateMachine () inline private
Definition at line 130 of file DoubleBarrel_Base.c.
References ChamberMultiBullet(), E_E, E_F, E_L, F_E, F_F, F_L, L_E, and L_L.
SetActions()
override void SetActions () inline private
Definition at line 315 of file DoubleBarrel_Base.c.
References AddAction(), and RemoveAction().
Field Documentation
E_E
ref WeaponStateBase E_E private
Definition at line 128 of file DoubleBarrel_Base.c.
Referenced by InitStateMachine().
E_F
ref WeaponStateBase E_F private
Definition at line 127 of file DoubleBarrel_Base.c.
Referenced by InitStateMachine().
E_L
ref WeaponStateBase E_L private
Definition at line 123 of file DoubleBarrel_Base.c.
Referenced by InitStateMachine().
F_E
ref WeaponStateBase F_E private
Definition at line 126 of file DoubleBarrel_Base.c.
Referenced by InitStateMachine().
F_F
ref WeaponStateBase F_F private
Definition at line 125 of file DoubleBarrel_Base.c.
Referenced by InitStateMachine().
F_L
ref WeaponStateBase F_L private
Definition at line 124 of file DoubleBarrel_Base.c.
Referenced by InitStateMachine().
L_E
ref WeaponStateBase L_E private
Definition at line 122 of file DoubleBarrel_Base.c.
Referenced by InitStateMachine().
L_L
ref WeaponStateBase L_L private
Definition at line 121 of file DoubleBarrel_Base.c.
Referenced by InitStateMachine().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Firearms/DoubleBarrel_Base.c