DayZ: ActionCarHornLong Class Reference
ActionCarHornLong Class Reference
Private Member Functions
void ActionCarHornLong ()
override bool HasTarget ()
override bool HasProgress ()
override bool CanBeUsedInVehicle ()
override GetInputType ()
override bool UseMainItem ()
override void CreateConditionComponents ()
override ActionData CreateActionData ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnUpdate (ActionData action_data)
special case - manually ends the action on exec event
override void OnEndInput (ActionData action_data)
override void OnStart (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Detailed Description
Definition at line 208 of file ActionCarHorn.c.
Constructor & Destructor Documentation
ActionCarHornLong()
void ActionCarHornLong () inline private
Definition at line 210 of file ActionCarHorn.c.
References AnimatedActionBase::m_CommandUID, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 253 of file ActionCarHorn.c.
References ActionCarHornBase::ActionCondition().
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle () inline private
Definition at line 226 of file ActionCarHorn.c.
CreateActionData()
override ActionData CreateActionData () inline private
Definition at line 247 of file ActionCarHorn.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 241 of file ActionCarHorn.c.
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType () inline private
Definition at line 231 of file ActionCarHorn.c.
References CarHornLongActionInput.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 339 of file ActionCarHorn.c.
References CarHornActionData::m_ActionNeedEnd, and CarHornActionData::m_Car.
HasProgress()
override bool HasProgress () inline private
Definition at line 221 of file ActionCarHorn.c.
HasTarget()
override bool HasTarget () inline private
Definition at line 216 of file ActionCarHorn.c.
OnEndInput()
override void OnEndInput (ActionData action_data) inline private
Definition at line 271 of file ActionCarHorn.c.
References ActionCarHornBase::SetCarHornState().
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
Definition at line 297 of file ActionCarHorn.c.
References ActionCarHornBase::SetCarHornState().
OnStart()
override void OnStart (ActionData action_data) inline private
Definition at line 279 of file ActionCarHorn.c.
References CarHornActionData::m_ActionNeedEnd, CarHornActionData::m_Car, and ActionData::m_Player.
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
Definition at line 288 of file ActionCarHorn.c.
References CarHornActionData::m_ActionNeedEnd, and ActionCarHornBase::SetCarHornState().
OnUpdate()
override void OnUpdate (ActionData action_data) inline private
special case - manually ends the action on exec event
Definition at line 259 of file ActionCarHorn.c.
References CarHornActionData::m_ActionNeedEnd, ActionData::m_Callback, ActionData::m_ReciveEndInput, and ActionBaseCB::SetCommand().
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 315 of file ActionCarHorn.c.
References Serializer::Read().
UseMainItem()
override bool UseMainItem () inline private
Definition at line 236 of file ActionCarHorn.c.
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 305 of file ActionCarHorn.c.
References CarHornActionData::m_ActionNeedEnd, CarHornActionData::m_Car, and Serializer::Write().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Continuous/Vehicles/ActionCarHorn.c