DayZ Scripts Documentation: DebugMonitorValues Class Reference
DebugMonitorValues Class Reference
Private Member Functions
void DebugMonitorValues (PlayerBase player)
void Init ()
void OnScheduledTick (float deltatime)
void CheckValues ()
float GetBlood ()
float GetHealth ()
string GetLastDamage ()
void SetLastDamage (string value)
void CheckHealth ()
void CheckBlood ()
void CheckLastDamage ()
void SendValue (int value_type, Param param)
void ReceiveValue (int value_type, Param param)
void OnRPCFloat (ParamsReadContext ctx)
void OnRPCString (ParamsReadContext ctx)
Private Attributes
const int TYPE_HEALTH = 1
const int TYPE_BLOOD = 2
const int TYPE_BODY_TEMP = 3
const int TYPE_POSITION = 4
const int TYPE_LAST_DAMAGE = 5
const int LAST_DAMAGE_FALL = 1
const int LAST_DAMAGE_HIT = 2
const float VALUE_CHECK_INTERVAL = 1
const float SENSITIVTY_PERCENTAGE = 1
PlayerBase m_Player
float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1
string m_CurrentLastDamage
float m_LastHealthUpdate
float m_LastBloodUpdate
string m_lastDamageUpdate
float m_HealthMaxValue
float m_BloodMaxValue
float m_BloodClient
float m_HealthClient
string m_LastDamageClient
Detailed Description
Definition at line 1 of file DebugMonitorValues.c.
Constructor & Destructor Documentation
DebugMonitorValues()
void DebugMonitorValues (PlayerBase player) inline private
Definition at line 31 of file DebugMonitorValues.c.
References Init(), and m_Player.
Member Function Documentation
CheckBlood()
void CheckBlood () inline private
Definition at line 100 of file DebugMonitorValues.c.
References Math::AbsFloat(), m_BloodMaxValue, m_LastBloodUpdate, m_Player, SendValue(), SENSITIVTY_PERCENTAGE, and TYPE_BLOOD.
Referenced by CheckValues().
CheckHealth()
void CheckHealth () inline private
Definition at line 84 of file DebugMonitorValues.c.
References Math::AbsFloat(), m_HealthMaxValue, m_LastHealthUpdate, m_Player, SendValue(), SENSITIVTY_PERCENTAGE, and TYPE_HEALTH.
Referenced by CheckValues().
CheckLastDamage()
void CheckLastDamage () inline private
Definition at line 116 of file DebugMonitorValues.c.
References m_CurrentLastDamage, m_lastDamageUpdate, SendValue(), and TYPE_LAST_DAMAGE.
Referenced by CheckValues().
CheckValues()
void CheckValues () inline private
Definition at line 57 of file DebugMonitorValues.c.
References CheckBlood(), CheckHealth(), and CheckLastDamage().
Referenced by OnScheduledTick().
GetBlood()
float GetBlood () inline private
Definition at line 64 of file DebugMonitorValues.c.
References m_BloodClient.
Referenced by MissionBase::UpdateDebugMonitor().
GetHealth()
float GetHealth () inline private
Definition at line 69 of file DebugMonitorValues.c.
References m_HealthClient.
Referenced by MissionBase::UpdateDebugMonitor().
GetLastDamage()
string GetLastDamage () inline private
Definition at line 74 of file DebugMonitorValues.c.
References m_LastDamageClient.
Referenced by MissionBase::UpdateDebugMonitor().
Init()
void Init () inline private
Definition at line 37 of file DebugMonitorValues.c.
References m_BloodMaxValue, m_HealthMaxValue, and m_Player.
Referenced by DebugMonitorValues().
OnRPCFloat()
void OnRPCFloat (ParamsReadContext ctx) inline private
Definition at line 184 of file DebugMonitorValues.c.
References CachedObjectsParams::PARAM2_INT_FLOAT, Serializer::Read(), and ReceiveValue().
OnRPCString()
void OnRPCString (ParamsReadContext ctx) inline private
Definition at line 195 of file DebugMonitorValues.c.
References CachedObjectsParams::PARAM2_INT_STRING, Serializer::Read(), and ReceiveValue().
OnScheduledTick()
void OnScheduledTick (float deltatime) inline private
Definition at line 43 of file DebugMonitorValues.c.
References CheckValues(), GetGame(), m_TimeSinceLastTick, and VALUE_CHECK_INTERVAL.
ReceiveValue()
void ReceiveValue (int value_type, Param param) inline private
Definition at line 154 of file DebugMonitorValues.c.
References Mission::CreateDebugMonitor(), GetGame(), CGame::GetMission(), m_BloodClient, m_HealthClient, m_LastDamageClient, TYPE_BLOOD, TYPE_HEALTH, and TYPE_LAST_DAMAGE.
Referenced by OnRPCFloat(), and OnRPCString().
SendValue()
void SendValue (int value_type, Param param) inline private
Definition at line 126 of file DebugMonitorValues.c.
References GetGame(), m_Player, CachedObjectsParams::PARAM2_INT_FLOAT, CachedObjectsParams::PARAM2_INT_STRING, CGame::RPCSingleParam(), TYPE_BLOOD, TYPE_HEALTH, and TYPE_LAST_DAMAGE.
Referenced by CheckBlood(), CheckHealth(), and CheckLastDamage().
SetLastDamage()
void SetLastDamage (string value) inline private
Definition at line 79 of file DebugMonitorValues.c.
References m_CurrentLastDamage.
Field Documentation
LAST_DAMAGE_FALL
const int LAST_DAMAGE_FALL = 1 private
Definition at line 9 of file DebugMonitorValues.c.
LAST_DAMAGE_HIT
const int LAST_DAMAGE_HIT = 2 private
Definition at line 10 of file DebugMonitorValues.c.
m_BloodClient
float m_BloodClient private
Definition at line 27 of file DebugMonitorValues.c.
Referenced by GetBlood(), and ReceiveValue().
m_BloodMaxValue
float m_BloodMaxValue private
Definition at line 25 of file DebugMonitorValues.c.
Referenced by CheckBlood(), and Init().
m_CurrentLastDamage
string m_CurrentLastDamage private
Definition at line 18 of file DebugMonitorValues.c.
Referenced by CheckLastDamage(), and SetLastDamage().
m_HealthClient
float m_HealthClient private
Definition at line 28 of file DebugMonitorValues.c.
Referenced by GetHealth(), and ReceiveValue().
m_HealthMaxValue
float m_HealthMaxValue private
Definition at line 24 of file DebugMonitorValues.c.
Referenced by CheckHealth(), and Init().
m_LastBloodUpdate
float m_LastBloodUpdate private
Definition at line 21 of file DebugMonitorValues.c.
Referenced by CheckBlood().
m_LastDamageClient
string m_LastDamageClient private
Definition at line 29 of file DebugMonitorValues.c.
Referenced by GetLastDamage(), and ReceiveValue().
m_lastDamageUpdate
string m_lastDamageUpdate private
Definition at line 22 of file DebugMonitorValues.c.
Referenced by CheckLastDamage().
m_LastHealthUpdate
float m_LastHealthUpdate private
Definition at line 20 of file DebugMonitorValues.c.
Referenced by CheckHealth().
m_Player
PlayerBase m_Player private
Definition at line 15 of file DebugMonitorValues.c.
Referenced by CheckBlood(), CheckHealth(), DebugMonitorValues(), Init(), and SendValue().
m_TimeSinceLastTick
float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1 private
Definition at line 16 of file DebugMonitorValues.c.
Referenced by OnScheduledTick().
SENSITIVTY_PERCENTAGE
const float SENSITIVTY_PERCENTAGE = 1 private
Definition at line 13 of file DebugMonitorValues.c.
Referenced by CheckBlood(), and CheckHealth().
TYPE_BLOOD
const int TYPE_BLOOD = 2 private
Definition at line 4 of file DebugMonitorValues.c.
Referenced by CheckBlood(), ReceiveValue(), and SendValue().
TYPE_BODY_TEMP
const int TYPE_BODY_TEMP = 3 private
Definition at line 5 of file DebugMonitorValues.c.
TYPE_HEALTH
const int TYPE_HEALTH = 1 private
Definition at line 3 of file DebugMonitorValues.c.
Referenced by CheckHealth(), ReceiveValue(), and SendValue().
TYPE_LAST_DAMAGE
const int TYPE_LAST_DAMAGE = 5 private
Definition at line 7 of file DebugMonitorValues.c.
Referenced by CheckLastDamage(), ReceiveValue(), and SendValue().
TYPE_POSITION
const int TYPE_POSITION = 4 private
Definition at line 6 of file DebugMonitorValues.c.
VALUE_CHECK_INTERVAL
const float VALUE_CHECK_INTERVAL = 1 private
Definition at line 12 of file DebugMonitorValues.c.
Referenced by OnScheduledTick().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/DebugMonitorValues.c