DayZ: HandEventSwap Class Reference
HandEventSwap Class Reference
Private Member Functions
void HandEventForceSwap (Man p=null, InventoryLocation src=null, InventoryLocation src2=null, InventoryLocation dst=null, InventoryLocation dst2=null)
override bool CheckRequest ()
override bool CanPerformEvent ()
Detailed Description
Definition at line 549 of file Hand_Events.c.
Member Function Documentation
CanPerformEvent()
override bool CanPerformEvent () inline private
Definition at line 571 of file Hand_Events.c.
References GameInventory::CanForceSwapEntitiesEx(), GetEventID(), InventoryLocation::GetItem(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), m_Player, and m_Src.
CheckRequest()
override bool CheckRequest () inline private
Definition at line 553 of file Hand_Events.c.
References GameInventory::c_MaxItemDistanceRadius, GameInventory::CheckSwapItemsRequest(), GetEventID(), GetSrcEntity(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), m_Player, and m_Src.
HandEventForceSwap()
void HandEventForceSwap (Man p = null, InventoryLocation src = null, InventoryLocation src2 = null, InventoryLocation dst = null, InventoryLocation dst2 = null) inline private
Definition at line 551 of file Hand_Events.c.
References m_EventID.
The documentation for this class was generated from the following file:
3_Game/Systems/Inventory/Hand_Events.c