DayZ Scripts: HandsPreview Class Reference
HandsPreview Class Reference
Private Member Functions
protected ItemBase m_Item void HandsPreview (LayoutHolder parent)
void ~HandsPreview ()
void RefreshQuantity (EntityAI m_Item_to_refresh)
override EntityAI GetFocusedItem ()
Icon GetIcon ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
override void SetLastFocus ()
override void Unfocus ()
float GetIconSize ()
override void SetLayoutName ()
void RemoveItem ()
override void UpdateInterval ()
void CreateNewIcon (ItemBase item)
void DeleteIcon ()
override bool SelectItem ()
override bool Select ()
Private Attributes
protected ref Icon m_Icon
protected EntityAI m_AttachmentsInitialized
protected float m_IconSize
Detailed Description
Definition at line 1 of file HandsPreview.c.
Constructor & Destructor Documentation
HandsPreview()
protected ItemBase m_Item void HandsPreview (LayoutHolder parent) inline private
Definition at line 10 of file HandsPreview.c.
References CreateNewIcon(), DeleteIcon(), GetGame(), and CGame::GetPlayer().
~HandsPreview()
void ~HandsPreview () inline private
Definition at line 16 of file HandsPreview.c.
References CreateNewIcon(), DeleteIcon(), GetGame(), and CGame::GetPlayer().
Member Function Documentation
CreateNewIcon()
void CreateNewIcon (ItemBase item) inline private
Definition at line 97 of file HandsPreview.c.
References ARGB(), Icon::FullScreen(), HandsContainer::GetHeader(), Icon::Init(), Inventory(), m_Icon, m_IconSize, m_Item, m_Parent, m_RootWidget, Icon::Refresh(), Header::SetName(), string::ToUpper(), and y.
Referenced by HandsContainer::HandsContainer(), HandsPreview(), and ~HandsPreview().
DeleteIcon()
void DeleteIcon () inline private
Definition at line 129 of file HandsPreview.c.
References ARGB(), Inventory(), m_AttachmentsInitialized, m_Parent, m_RootWidget, and RemoveItem().
Referenced by HandsPreview(), and ~HandsPreview().
GetFocusedItem()
override EntityAI GetFocusedItem () inline private
Definition at line 30 of file HandsPreview.c.
References m_Item.
GetIcon()
Icon GetIcon () inline private
Definition at line 35 of file HandsPreview.c.
References m_Icon.
Referenced by Attachments::Combine(), PlayerContainer::Combine(), and VicinitySlotsContainer::Combine().
GetIconSize()
float GetIconSize () inline private
Definition at line 61 of file HandsPreview.c.
References m_IconSize.
Referenced by Icon::SetPosEx(), and Icon::SetSize().
RefreshQuantity()
void RefreshQuantity (EntityAI m_Item_to_refresh) inline private
Definition at line 22 of file HandsPreview.c.
References m_Icon, and Icon::SetQuantity().
RemoveItem()
void RemoveItem () inline private
Definition at line 71 of file HandsPreview.c.
References m_Icon, and m_Item.
Referenced by DeleteIcon().
Select()
override bool Select () inline private
Definition at line 151 of file HandsPreview.c.
References GameInventory::CanSwapEntitiesEx(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), GetPlayer(), ItemManager::GetSelectedItem(), ItemManager::IsMicromanagmentMode(), m_Item, and EntityAI::PredictiveSwapEntities().
SelectItem()
override bool SelectItem () inline private
Definition at line 141 of file HandsPreview.c.
References ItemManager::GetInstance(), m_Item, and ItemManager::SetSelectedItem().
SetDefaultFocus()
override void SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 40 of file HandsPreview.c.
References m_Icon, and Icon::SetActive().
SetLastFocus()
override void SetLastFocus () inline private
Definition at line 47 of file HandsPreview.c.
References m_Icon, and Icon::SetActive().
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 66 of file HandsPreview.c.
References WidgetLayoutName::HandsPreview.
Unfocus()
override void Unfocus () inline private
Definition at line 54 of file HandsPreview.c.
References m_Icon, and Icon::SetActive().
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 77 of file HandsPreview.c.
References GetGame(), GetInput(), ItemManager::GetInstance(), Icon::IsDragged(), ItemManager::IsDragging(), m_Icon, and Icon::UpdateInterval().
Field Documentation
m_AttachmentsInitialized
protected EntityAI m_AttachmentsInitialized private
Definition at line 4 of file HandsPreview.c.
Referenced by DeleteIcon().
m_Icon
protected ref Icon m_Icon private
Definition at line 3 of file HandsPreview.c.
Referenced by CreateNewIcon(), GetIcon(), RefreshQuantity(), RemoveItem(), SetDefaultFocus(), SetLastFocus(), Unfocus(), and UpdateInterval().
m_IconSize
protected float m_IconSize private
Definition at line 6 of file HandsPreview.c.
Referenced by CreateNewIcon(), and GetIconSize().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/ContainedItems/HandsPreview.c