DayZ: ActionDetachPowerSourceFromPanel Class Reference
ActionDetachPowerSourceFromPanel Class Reference
Private Member Functions
void ActionDetachPowerSourceFromPanel ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void Process (ActionData action_data)
Detailed Description
Definition at line 2 of file ActionDetachPowerSourceFromPanel.c.
Constructor & Destructor Documentation
ActionDetachPowerSourceFromPanel()
void ActionDetachPowerSourceFromPanel () inline private
Definition at line 4 of file ActionDetachPowerSourceFromPanel.c.
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 9 of file ActionDetachPowerSourceFromPanel.c.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
Definition at line 28 of file ActionDetachPowerSourceFromPanel.c.
References Process().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
Definition at line 33 of file ActionDetachPowerSourceFromPanel.c.
References Process().
Process()
void Process (ActionData action_data) inline private
Definition at line 38 of file ActionDetachPowerSourceFromPanel.c.
References ActionData::m_Player, and ActionData::m_Target.
Referenced by OnExecuteClient(), and OnExecuteServer().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Interact/ActionDetachPowerSourceFromPanel.c