DayZ: HiddenSelectionsData Class Reference
HiddenSelectionsData Class Reference
Private Member Functions
void HiddenSelectionsData (string type)
int GetHiddenSelectionIndex (string selection)
TStringArray GetHiddenSelectionsTextures ()
TStringArray GetHiddenSelectionsMaterials ()
Static Private Member Functions
static array< string > GetHiddenSelectionsConfig (string type)
static array< string > GetHiddenSelectionsTexturesConfig (string type)
static array< string > GetHiddenSelectionsMaterialsConfig (string type)
Private Attributes
ref array< string > m_HiddenSelections = new array<string>
ref array< string > m_HiddenSelectionsTextures = new array<string>
ref array< string > m_HiddenSelectionsMaterials = new array<string>
ref map< string, int > m_HiddenSelectionNameToIndex = new map<string, int>
Detailed Description
Definition at line 1 of file HiddenSelectionsData.c.
Constructor & Destructor Documentation
HiddenSelectionsData()
void HiddenSelectionsData (string type) inline private
Definition at line 9 of file HiddenSelectionsData.c.
References CGame::ConfigGetTextArray(), GetGame(), m_HiddenSelectionNameToIndex, m_HiddenSelections, m_HiddenSelectionsMaterials, and m_HiddenSelectionsTextures.
Member Function Documentation
GetHiddenSelectionIndex()
int GetHiddenSelectionIndex (string selection) inline private
Definition at line 19 of file HiddenSelectionsData.c.
References m_HiddenSelectionNameToIndex.
GetHiddenSelectionsConfig()
static array< string > GetHiddenSelectionsConfig (string type) inline static private
Definition at line 38 of file HiddenSelectionsData.c.
References CGame::ConfigGetTextArray(), and GetGame().
Referenced by GetHiddenSelections().
GetHiddenSelectionsMaterials()
TStringArray GetHiddenSelectionsMaterials () inline private
Definition at line 33 of file HiddenSelectionsData.c.
References m_HiddenSelectionsMaterials.
GetHiddenSelectionsMaterialsConfig()
static array< string > GetHiddenSelectionsMaterialsConfig (string type) inline static private
Definition at line 52 of file HiddenSelectionsData.c.
References CGame::ConfigGetTextArray(), and GetGame().
Referenced by GetHiddenSelectionsMaterials().
GetHiddenSelectionsTextures()
TStringArray GetHiddenSelectionsTextures () inline private
Definition at line 28 of file HiddenSelectionsData.c.
References m_HiddenSelectionsTextures.
GetHiddenSelectionsTexturesConfig()
static array< string > GetHiddenSelectionsTexturesConfig (string type) inline static private
Definition at line 45 of file HiddenSelectionsData.c.
References CGame::ConfigGetTextArray(), and GetGame().
Referenced by GetHiddenSelectionsTextures().
Field Documentation
m_HiddenSelectionNameToIndex
ref map<string, int> m_HiddenSelectionNameToIndex = new map<string, int> private
Definition at line 7 of file HiddenSelectionsData.c.
Referenced by GetHiddenSelectionIndex(), and HiddenSelectionsData().
m_HiddenSelections
ref array<string> m_HiddenSelections = new array<string> private
Definition at line 3 of file HiddenSelectionsData.c.
Referenced by HiddenSelectionsData().
m_HiddenSelectionsMaterials
ref array<string> m_HiddenSelectionsMaterials = new array<string> private
Definition at line 5 of file HiddenSelectionsData.c.
Referenced by GetHiddenSelectionsMaterials(), and HiddenSelectionsData().
m_HiddenSelectionsTextures
ref array<string> m_HiddenSelectionsTextures = new array<string> private
Definition at line 4 of file HiddenSelectionsData.c.
Referenced by GetHiddenSelectionsTextures(), and HiddenSelectionsData().
The documentation for this class was generated from the following file:
3_Game/HiddenSelectionsData.c