DayZ: ItemBase Class Reference
ItemBase Class Reference
Private Member Functions
override void SetActions ()
override void SetActions ()
override void SetActions ()
override bool DisplayNameRuinAttach ()
override void SetActions ()
override void SetActions ()
override bool DisplayNameRuinAttach ()
override bool ShowZonesHealth ()
override void SetActions ()
void Clothing_Base ()
void ~Clothing_Base ()
override bool IsClothing ()
float GetItemVisibility ()
void UpdateNVGStatus (PlayerBase player, bool attaching=false, bool force_disable=false)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
bool IsObstructingVoice ()
Returns if this entity obsructs player's voice.
void MutePlayer (PlayerBase player, bool state)
This items has effect on player's voice.
void HandleVoiceEffect (bool enable, PlayerBase player)
int GetVoiceEffect ()
The voice effect this item uses, default is 0 (none)
bool IsGasMask ()
void GardenBase ()
override void OnVariablesSynchronized ()
override bool HasProxyParts ()
override int GetHideIconMask ()
void SetBaseFertility (float value)
float GetBaseFertility ()
override void EOnInit (IEntity other, int extra)
void InitializeSlots ()
void SetMaxWaterStateVal ()
int GetMaxWaterStateVal ()
void UpdateTexturesOnAllSlots ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
override void EEOnAfterLoad ()
void SyncSlots ()
override void OnStoreSave (ParamsWriteContext ctx)
void PrintSlots ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
override bool CanRemoveFromHands (EntityAI player)
int GetGardenSlotsCount ()
bool CanPlantSeed (string selection_component)
string ConvertAttSlotToPlantSlot (string attach_slot)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
void PlantSeed (ItemBase seed, string selection_component)
void CreatePlant (Slot slot)
void Fertilize (PlayerBase player, ItemBase item, float consumed_quantity, string selection_component)
bool IsCorrectFertilizer (ItemBase item, string selection_component)
bool NeedsFertilization (string selection_component)
void SlotWaterStateUpdate (Slot slot)
void UpdateSlotTexture (int slot_index)
void SetSlotTextureDigged (int slot_index)
void SetSlotTextureFertilized (int slot_index, string item_type)
void RemoveSlot (int index)
void RemoveSlotPlant (Object plant)
Slot GetSlotBySelection (string selection_component)
int GetSlotIndexBySelection (string selection_component)
int GetSlotIndexByAttachmentSlot (string att_slot)
int GetSlotIndexByPlant (Object plant)
int GetNearestSlotIDByState (vector position, int slot_state)
vector GetSlotPosition (int index)
void CheckRainStart ()
void CheckRainTick ()
void WaterAllSlots ()
array< ref Slot > GetSlots ()
Slot GetSlotByIndex (int index)
int GetSlotWateredState ()
void SetSlotWateredState (int newState)
override void SetActions ()
void PlantBase ()
void ~PlantBase ()
void Init (GardenBase garden_base, float fertility, float harvesting_efficiency, float water)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
string GetCropsType ()
bool OnStoreLoadCustom (ParamsReadContext ctx, int version)
void OnStoreSaveCustom (ParamsWriteContext ctx)
void PrintValues ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
override bool CanRemoveFromHands (EntityAI player)
void ChangeInfestation (bool is_infested)
void UpdatePlant ()
void GrowthTimerTick ()
void InfestationTimerTick ()
void SpoiledRemoveTimerTick ()
void DeleteDryPlantTick ()
void SetSpoiled ()
void CheckWater ()
void SprayPlant (float consumed_quantity)
string StopInfestation (float consumed_quantity)
void RemovePlant ()
void RemovePlantEx (vector pos)
void DestroyPlant ()
void Harvest (PlayerBase player)
void SetPlantState (int state)
int GetPlantState ()
int GetPlantStateIndex ()
float GetWater ()
float GetWaterMax ()
bool NeedsWater ()
bool NeedsSpraying ()
float GetSprayQuantity ()
float GetSprayUsage ()
void RemoveSlot ()
void SetSlot (Slot slot)
Slot GetSlot ()
GardenBase GetGarden ()
bool IsDry ()
bool IsGrowing ()
bool IsMature ()
bool IsSpoiled ()
bool HasCrops ()
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
override void SetActions ()
override float GetBandagingEffectivity ()
override bool CanBeDisinfected ()
override float GetInfectionChance (int system=0, Param param=null)
override void OnCombine (ItemBase other_item)
void BarbedWire ()
void ~BarbedWire ()
override void EEInit ()
bool IsMounted ()
protected bool GetSlotLockedState ()
void SetMountedState (bool is_mounted)
protected void UpdateAttachmentSlot ()
protected void LockAttachmentSlot (bool lock_state)
void Synchronize ()
override void OnVariablesSynchronized ()
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
override void OnIsPlugged (EntityAI source_device)
override void OnIsUnplugged (EntityAI last_energy_source)
override void OnInventoryEnter (Man player)
protected void CreateElectrifiedDamageTrigger ()
protected void CreateDamageTrigger ()
protected void DestroyDamageTrigger ()
void Spark ()
void SoundCut ()
void SoundSpark ()
void SoundBuzzLoopStart ()
void SoundBuzzLoopStop ()
void SoundElectricShock ()
void SoundCollision ()
override void PreAreaDamageActions ()
override void PostAreaDamageActions ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override void SetActions ()
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
override void SetActions ()
void BaseBuildingBase ()
override string GetInvulnerabilityTypeString ()
override bool CanObstruct ()
override int GetHideIconMask ()
void SynchronizeBaseState ()
override void OnVariablesSynchronized ()
protected void OnSynchronizedClient ()
void RegisterPartForSync (int part_id)
void UnregisterPartForSync (int part_id)
bool IsPartBuildInSyncData (int part_id)
protected void RegisterActionForSync (int part_id, int action_id)
protected void ResetActionSyncData ()
protected void SetActionFromSyncData ()
void SetPartFromSyncData (ConstructionPart part)
void SetPartsFromSyncData ()
protected ConstructionPart GetConstructionPartById (int id)
bool HasBase ()
void SetBaseState (bool has_base)
override bool IsDeployable ()
bool IsOpened ()
ItemBase CreateConstructionKit ()
void CreateConstructionKitInHands (notnull PlayerBase player)
protected vector GetKitSpawnPosition ()
protected string GetConstructionKitType ()
void DestroyConstructionKit (ItemBase construction_kit)
void DestroyConstruction ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
void SetPartsAfterStoreLoad ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEOnAfterLoad ()
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
protected void OnSetSlotLock (int slotId, bool locked, bool was_locked)
override bool IgnoreOutOfReachCondition ()
void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
void OnPartBuiltClient (string part_name, int action_id)
void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
void OnPartDismantledClient (string part_name, int action_id)
void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
void OnPartDestroyedClient (string part_name, int action_id)
void InitBaseState ()
void InitVisuals ()
void UpdateVisuals ()
void UpdateAttachmentVisuals (string slot_name, bool is_locked)
void UpdatePhysics ()
void UpdateAttachmentPhysics (string slot_name, bool is_locked)
protected void UpdateNavmesh ()
override bool CanUseConstruction ()
override bool CanUseConstructionBuild ()
protected bool IsAttachmentSlotLocked (EntityAI attachment)
protected bool IsAttachmentSlotLocked (string slot_name)
void GetAttachmentSlots (EntityAI entity, out array< string > attachment_slots)
bool CheckSlotVerticalDistance (int slot_id, PlayerBase player)
protected bool CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player)
protected bool CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player)
void ConstructionInit ()
Construction GetConstruction ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
bool HasAttachmentsBesidesBase ()
override bool ShowZonesHealth ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool IsFacingPlayer (PlayerBase player, string selection)
override bool IsPlayerInside (PlayerBase player, string selection)
bool MustBeBuiltFromOutside ()
Some buildings can only be built from outside.
bool IsFacingCamera (string selection)
bool PerformRoofCheckForBase (string partName, PlayerBase player, out bool result)
bool HasProperDistance (string selection, PlayerBase player)
bool CanFoldBaseBuildingObject ()
ItemBase FoldBaseBuildingObject ()
void CreateAreaDamage (string slot_name, float rotation_angle=0)
void CalcDamageAreaRotation (float angle_deg, out vector center, out vector orientation)
void DestroyAreaDamage (string slot_name)
override bool IsIgnoredByConstruction ()
protected void SoundBuildStart (string part_name)
protected void SoundDismantleStart (string part_name)
protected void SoundDestroyStart (string part_name)
protected string GetBuildSoundByMaterial (string part_name)
protected string GetDismantleSoundByMaterial (string part_name)
void CheckForHybridAttachments (EntityAI item, string slot_name)
override int GetDamageSystemVersionChange ()
override void SetActions ()
protected void DebugCustomState ()
array< string > OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
override void OnDebugSpawn ()
void FullyBuild ()
void Battery9V ()
override void SetCEBasedQuantity ()
float GetEfficiency0To1 ()
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 units.
float GetEfficiencyDecayStart ()
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 unit.
override void OnEnergyConsumed ()
override void OnEnergyAdded ()
override void SetActions ()
void BatteryCharger ()
override bool IsElectricAppliance ()
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStop ()
void UpdateStatusLights ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
override void OnOwnSocketTaken (EntityAI device)
override void OnOwnSocketReleased (EntityAI device)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanLoadAttachment (EntityAI attachment)
void HideAttachedClipsStates ()
void RedLightOn ()
void GreenLightOn ()
void YellowLightOn ()
void SwitchLightOn ()
void RedLightOff ()
void GreenLightOff ()
void YellowLightOff ()
void SwitchLightOff ()
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnInventoryExit (Man player)
override void OnInventoryEnter (Man player)
override void OnVariablesSynchronized ()
override void RefreshPhysics ()
override void OnPlacementStarted (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool IsDeployable ()
override string GetPlaceSoundset ()
override void SetActions ()
void BloodContainerBase ()
override bool IsBloodContainer ()
void SetBloodTypeVisible (bool visible)
bool GetBloodTypeVisible ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnWorkStart ()
override void OnWorkStop ()
protected void RefreshFlameVisual (bool working=false)
protected void SoundBurningStart ()
protected void SoundBurningStop ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool IsIgnited ()
override void OnIgnitedTarget (EntityAI ignited_item)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void SetActions ()
protected EntityAI GetGasCanister ()
bool HasEnoughEnergyForRepair (float pTime)
override void OnDebugSpawn ()
void CableReel ()
override bool IsElectricAppliance ()
void ForceIntoHandsNow (PlayerBase player)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
override void OnInventoryEnter (Man player)
override bool CanRemoveFromHands (EntityAI player)
override void OnVariablesSynchronized ()
override void OnPlacementStarted (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetPlaceSoundset ()
override void SetActions ()
override void SetActions ()
void Defibrillator ()
void ~Defibrillator ()
float GetTimeNeededToCharge ()
float GetEnergyNeededToCharge ()
override void OnWorkStart ()
override void OnWorkStop ()
void OnIsCharged ()
void StopChargedAlarm ()
void StopChargingSound ()
void StopChargingTimer ()
bool IsCharged ()
void DischargeServer (PlayerBase victim)
void DischargeClient (PlayerBase victim)
override void SetActions ()
void Edible_Base ()
override void EEInit ()
override void EEDelete (EntityAI parent)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void UpdateVisuals ()
bool Consume (float amount, PlayerBase consumer)
void OnConsume (float amount, PlayerBase consumer)
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
void Synchronize ()
override void OnVariablesSynchronized ()
void MakeSoundsOnClient (bool soundstate)
protected void RefreshAudio ()
protected void RemoveAudio ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
FoodStage GetFoodStage ()
override bool IsMeat ()
override bool IsCorpse ()
override bool IsFruit ()
override bool IsMushroom ()
FoodStageType GetFoodStageType ()
bool IsFoodRaw ()
bool IsFoodBaked ()
bool IsFoodBoiled ()
bool IsFoodDried ()
bool IsFoodBurned ()
bool IsFoodRotten ()
void ChangeFoodStage (FoodStageType new_food_stage_type)
FoodStageType GetNextFoodStageType (CookingMethodType cooking_method)
string GetFoodStageName (FoodStageType food_stage_type)
bool CanChangeToNewStage (CookingMethodType cooking_method)
void TransferFoodStage (notnull Edible_Base source)
float GetCookingTime ()
void SetCookingTime (float time)
void ReplaceEdibleWithNew (string typeName)
override void SetActions ()
protected void SoundCookingStart (string sound_name)
protected void SoundCookingStop ()
override bool CanHaveTemperature ()
override bool CanDecay ()
override bool CanProcessDecay ()
override void ProcessDecay (float delta, bool hasRootAsPlayer)
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
float GetDecayTimer ()
float GetDecayDelta ()
FoodStageType GetLastDecayStage ()
override bool CanMakeGardenplot ()
override void SetActions ()
override void SetActions ()
void Flag_Base ()
void ~Flag_Base ()
void Synchronize ()
override void OnVariablesSynchronized ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override int GetViewIndex ()
override void SetActions ()
override void OnWorkStart ()
override void OnWork (float consumed_energy)
override void OnWorkStop ()
override void OnInventoryExit (Man player)
override void SetActions ()
override void OnDebugSpawn ()
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
override void SetActions ()
void ~RestrainingToolLocked ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void SetActions ()
override bool CanIgniteItem (EntityAI ignite_target=NULL)
Override this method and and check if the given item can be ignited. It is not necesarry to check here if the item is not in cargo of something.
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedTargetFailed (EntityAI target_item)
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
void KitBase ()
void ~KitBase ()
override bool IsBasebuildingKit ()
override bool HasProxyParts ()
override void OnVariablesSynchronized ()
override void EEInit ()
override bool DisassembleOnLastDetach ()
override void EEItemDetached (EntityAI item, string slot_name)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnEndPlacement ()
override void OnPlacementCancelled (Man player)
override bool IsDeployable ()
override bool CanAssignAttachmentsToQuickbar ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override string GetDeployFinishSoundset ()
override void RefreshPhysics ()
void UpdateVisuals ()
void UpdatePhysics ()
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
void AssembleKit ()
void DisassembleKit (ItemBase item)
void CreateRope (Rope rope)
override void SetActions ()
override bool CanExplodeInFire ()
override void InitItemVariables ()
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedTargetFailed (EntityAI target_item)
override void SetActions ()
override bool CanExplodeInFire ()
override void SetActions ()
void MetalWire ()
override bool CanPutAsAttachment (EntityAI parent)
void UpdateAllSelections ()
override void OnInventoryEnter (Man player)
override void OnIsPlugged (EntityAI source_device)
override void OnIsUnplugged (EntityAI last_energy_source)
override void OnOwnSocketTaken (EntityAI device)
override void OnOwnSocketReleased (EntityAI device)
override void SetActions ()
override void SetActions ()
void Paper ()
void ~Paper ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override WrittenNoteData GetWrittenNoteData ()
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=null)
override bool CanIgniteItem (EntityAI ignite_target=null)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=null)
override void SetActions ()
void ParticleTest ()
override void EEDelete (EntityAI parent)
override bool IsPeltBase ()
override void SetActions ()
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedTargetFailed (EntityAI target_item)
override void SetActions ()
override bool CanMakeGardenplot ()
override void SetActions ()
void PileOfWoodenPlanks ()
void UpdateSelections ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
int RemovePlanks (int needed_planks)
override bool CanPutIntoHands (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
void Pitchfork ()
override void SetActions ()
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStart ()
override void OnWorkStop ()
protected void SoundBurningStart ()
protected void SoundBurningStop ()
protected void SoundTurnOn ()
protected void SoundTurnOff ()
override void SetActions ()
ItemBase GetCookingEquipment ()
void SetCookingEquipment (ItemBase equipment)
void ClearCookingEquipment (ItemBase pItem)
void DestroyFireplace ()
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
void CookWithEquipment ()
protected void RefreshFlameVisual (bool working=false, bool hasAttachment=false)
protected void RemoveCookingAudioVisuals ()
protected void SoundBurningStart ()
protected void SoundBurningStop ()
protected void SoundTurnOn ()
protected void SoundTurnOff ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool IsIgnited ()
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void SetActions ()
override void OnDebugSpawn ()
void PowerGenerator ()
void ~PowerGenerator ()
override void EEInit ()
override void EOnInit (IEntity other, int extra)
override float GetLiquidThroughputCoef ()
void StartLoopSound ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
bool CanManipulate ()
override void OnInitEnergy ()
override void OnWorkStart ()
override void OnWork (float consumed_energy)
override void OnWorkStop ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
void UpdateFuelMeter ()
void SetFuel (float fuel_amount)
float AddFuel (float available_fuel)
bool CanAddFuel (ItemBase container)
float GetFuel ()
float GetMaxFuel ()
bool HasSparkplug ()
override void OnVariablesSynchronized ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetPlaceSoundset ()
override void SetActions ()
override void OnDebugSpawn ()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
override bool CanPutAsAttachment (EntityAI parent)
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=null)
override bool CanIgniteItem (EntityAI ignite_target=null)
override bool CanBeCombined (EntityAI other_item, bool reservation_check=true, bool stack_max_limit=false)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=null)
override bool CanAssignToQuickbar ()
override bool CanBeDisinfected ()
override void SetActions ()
override float GetBandagingEffectivity ()
override float GetInfectionChance (int system=0, Param param=null)
override void OnCombine (ItemBase other_item)
override void OnWorkStart ()
void StartPeriodicMeasurement ()
void PrepareMeasurement ()
void DoMeasurement ()
void StopPeriodicMeasurement ()
override void OnWorkStop ()
override void SetActions ()
override bool IsElectricAppliance ()
override void OnInitEnergy ()
override void OnWorkStart ()
override void OnWork (float consumed_energy)
override void OnWorkStop ()
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnVariablesSynchronized ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetPlaceSoundset ()
override void SetActions ()
override bool CanMakeGardenplot ()
override void SetActions ()
override bool CanExplodeInFire ()
void Spotlight ()
void ~Spotlight ()
override bool IsElectricAppliance ()
override void OnInitEnergy ()
override void EOnInit (IEntity other, int extra)
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnIsPlugged (EntityAI source_device)
protected void UpdateAllSelections ()
override void OnIsUnplugged (EntityAI last_energy_source)
override void OnVariablesSynchronized ()
void Fold (bool keep_connected=false)
void Unfold ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
bool IsFolded ()
protected void SoundTurnOn ()
protected void SoundTurnOff ()
override void OnPlacementStarted (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementCancelled (Man player)
override bool IsDeployable ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override int GetViewIndex ()
override void SetActions ()
override void SetActions ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void TentBase ()
void ~TentBase ()
override string GetInvulnerabilityTypeString ()
override bool HasProxyParts ()
override bool IsItemTent ()
override bool CanBeRepairedByCrafting ()
override int GetMeleeTargetType ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void RefreshPhysics ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnVariablesSynchronized ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
void HideAllAnimationsAndProxyPhysics (bool hide_animations=true, bool hide_physics=true)
bool ConditionIntoInventory (EntityAI player)
override bool CanPutIntoHands (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
bool ConditionOutOfHands (EntityAI player)
override bool CanBeRepairedToPristine ()
void RefreshAttachements ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override int GetViewIndex ()
int GetState ()
int GetStateLocal ()
bool CanBePacked ()
bool CanBeManipulated ()
bool CanAttach (ItemBase item)
override bool IsIgnoredByConstruction ()
void Pack (bool update_navmesh, bool init=false)
void Pitch (bool update_navmesh, bool init=false)
protected void TryPitch (bool update_navmesh, bool init=false)
void UpdateVisuals ()
void UpdatePhysics ()
void Refresh ()
bool CanToggleAnimations (string selection)
void ResetToggle ()
void ManipulateEntrance ()
void ManipulateWindow ()
bool IsManipulatedEntrance ()
bool IsManipulatedWindow ()
void ToggleAnimation (string selection)
void HandleCamoNetAttachment (bool hide)
void AnimateCamonetToggle (ToggleAnimations toggle)
void AnimateCamonetByOpeningSelection (string opening_selection)
string GetSoundOpen ()
string GetSoundClose ()
string GetSoundOpenWindow ()
string GetSoundCloseWindow ()
void SoundTentOpenPlay ()
void SoundTentClosePlay ()
void SoundTentOpenWindowPlay ()
void SoundTentCloseWindowPlay ()
void RegenerateNavmesh ()
bool HasClutterCutter ()
string GetClutterCutter ()
void DestroyClutterCutter ()
override bool IsDeployable ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override void SetActions ()
void HandleOpeningsVisuals ()
void HandleOpeningsPhysics ()
override int GetDamageSystemVersionChange ()
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanLoadAttachment (EntityAI attachment)
override bool CanBePlaced (Man player, vector position)
void SetIsBeingPacked (bool isBeingPacked)
float GetTemperatureValue (PlayerBase player)
override void SetActions ()
void ToolBase ()
int GetDisarmRate ()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
void TrapSpawnBase ()
void ~TrapSpawnBase ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnVariablesSynchronized ()
this event is called all variables are synchronized on client
bool IsActive ()
bool IsDeployed ()
void SetDeployed (bool newState)
override bool IsTakeable ()
bool IsPlaceableAtPosition (vector position)
void SetupTrap ()
void SetupTrapPlayer (PlayerBase player, bool set_position=true)
void Fold ()
void AddDefect ()
void StartActivate (PlayerBase player)
bool CanBeTaken ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
void SetActive ()
void SetInactive ()
void SetUsed ()
void SpawnCatch ()
bool SetCanCatch (out EntityAI bait)
void CatchSetQuant (ItemBase catch)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
bool IsSurfaceWater (vector position)
override bool CanDisplayAttachmentSlot (int slot_id)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override void EEItemAttached (EntityAI item, string slot_name)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override void SetActions ()
bool CanPutInInventory (EntityAI player)
void AlignCatch (ItemBase obj, string catch_name)
bool IsPlaceable ()
override bool CanBePlaced (Man player, vector position)
override void SetActions ()
override void SetActions ()
override void SetActions ()
void UndergroundStash ()
void PlaceOnGround ()
ItemBase GetStashedItem ()
override bool CanDisplayCargo ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReleaseCargo (EntityAI cargo)
override bool CanReceiveItemIntoHands (EntityAI item_to_hands)
override bool CanSaveItemInHands (EntityAI item_in_hands)
override bool CanPutIntoHands (EntityAI parent)
override bool IsInventoryVisible ()
Static Private Member Functions
static float GetFoodTotalVolume (ItemBase item, string classname="", int food_stage=0)
static float GetFoodEnergy (ItemBase item, string classname="", int food_stage=0)
static float GetFoodWater (ItemBase item, string classname="", int food_stage=0)
static float GetFoodNutritionalIndex (ItemBase item, string classname="", int food_stage=0)
static float GetFoodToxicity (ItemBase item, string classname="", int food_stage=0)
static int GetFoodAgents (ItemBase item, string classname="", int food_stage=0)
static float GetFoodDigestibility (ItemBase item, string classname="", int food_stage=0)
static NutritionalProfile GetNutritionalProfile (ItemBase item, string classname="", int food_stage=0)
Private Attributes
float m_ItemVisibilityModifier
protected ref array< ref Slot > m_Slots
protected int m_SlotFertilityState = 0
protected int m_SlotWateredState = 0
protected int m_MaxWateredStateVal = 0
protected float m_DefaultFertility = 1
ref Timer m_CheckRainTimer
private float m_SprayUsage
private float m_InfestationChance
private int m_GrowthStagesCount
private int m_CropsCount
private bool m_HasCrops
private string m_CropsType
private float m_PlantMaterialMultiplier
private int m_PlantState
private int m_PlantStateIndex
private float m_CurrentPlantMaterialQuantity
private bool m_IsInfested
private float m_SprayQuantity
bool m_MarkForDeletion = false
int m_DeleteDryPlantTime
int m_SpoiledRemoveTime
int m_FullMaturityTime
int m_SpoilAfterFullMaturityTime
int m_StateChangeTime
ref Timer m_GrowthTimer = NULL
ref Timer m_InfestationTimer = NULL
ref Timer m_SpoilAfterFullMaturityTimer = NULL
ref Timer m_SpoiledRemoveTimer = NULL
ref Timer m_DeleteDryPlantTimer = NULL
private GardenBase m_GardenBase = NULL
private ref Slot m_Slot = NULL
private PluginHorticulture m_ModuleHorticulture
private const float SPOIL_AFTER_MATURITY_TIME = 7200
ref protected EffectSound m_DeployLoopSound
SoundOnVehicle m_BuzzSoundLoop
ref Timer m_SparkEvent
protected ref AreaDamageManager m_AreaDamage
protected bool m_TriggerActive
protected bool m_IsPlaced
protected bool m_IsMounted
protected bool m_LastMountedState
const string SOUND_MOUNT = "putDown_BarbedWire_SoundSet"
protected EffectSound m_MountSound
const string ANIMATION_DEPLOYED = "Deployed"
float m_ConstructionKitHealth
ref Construction m_Construction
bool m_HasBase = false
int m_SyncParts01
int m_SyncParts02
int m_SyncParts03
int m_InteractedPartId
int m_PerformedActionId
const string SOUND_BUILD_WOOD_LOG = "putDown_WoodLog_SoundSet"
const string SOUND_BUILD_WOOD_PLANK = "putDown_WoodPlank_SoundSet"
const string SOUND_BUILD_WOOD_STAIRS = "putDown_WoodStairs_SoundSet"
const string SOUND_BUILD_METAL = "putDown_MetalPlank_SoundSet"
const string SOUND_BUILD_WIRE = "putDown_BarbedWire_SoundSet"
const string SOUND_DISMANTLE_WOOD_LOG = "Crash_WoodPlank_SoundSet"
const string SOUND_DISMANTLE_WOOD_PLANK = "Crash_WoodPlank_SoundSet"
const string SOUND_DISMANTLE_WOOD_STAIRS = "Crash_WoodPlank_SoundSet"
const string SOUND_DISMANTLE_METAL = "Crash_MetalPlank_SoundSet"
const string SOUND_DISMANTLE_WIRE = "putDown_BarbedWire_SoundSet"
protected EffectSound m_Sound
ref map< string, ref AreaDamageManager > m_DamageTriggers
ref array< string > m_HybridAttachments
ref array< string > m_Mountables
private int m_Efficiency0To10
protected const string ATTACHED_CLIPS_STATES [] = {SEL_CLIPS_CAR, SEL_CLIPS_TRUCK}
protected const int ATTACHED_CLIPS_STATES_COUNT = 2
int m_BatteryEnergy0To100
protected float m_ChargeEnergyPerSecond
ref Timer m_UpdateStatusLightsTimer
protected bool m_BlinkingStatusLightIsOn = false
private bool m_IsBloodTypeVisible = false
const string TEXTURE_FLAME = "dz\\gear\\cooking\\data\\flame_butane_ca.paa"
const string ANIM_PHASE_FLAME = "FlameHide"
const string SOUND_BURNING = "Blowtorch_Loop_SoundSet"
protected BlowtorchLight m_Light
protected EffectSound m_SoundBurningLoop
bool m_ForceIntoHands
bool m_IsCharged = false
ref Timer m_ChargingTimer
EffectSound m_ChargedAlarm
EffectSound m_ChargingSound
const string DIRECT_COOKING_SLOT_NAME = "DirectCooking"
const string SOUND_BAKING_START = "Baking_SoundSet"
const string SOUND_BAKING_DONE = "Baking_Done_SoundSet"
const string SOUND_BURNING_DONE = "Food_Burning_SoundSet"
protected bool m_MakeCookingSounds
protected SoundOnVehicle m_SoundCooking
protected EffectSound m_SoundEffectCooking
DEPRECATED.
protected string m_SoundPlaying
ref FoodStage m_FoodStage
protected float m_DecayTimer
protected float m_DecayDelta = 0.0
protected FoodStageType m_LastDecayStage = FoodStageType.NONE
FlashlightLight m_Light
protected bool m_DeployedRegularly
protected ref WrittenNoteData m_NoteContents
protected int PARTICLE_PATH
protected Particle m_Particle
PortableGasLampLight m_Light
private const string GAS_LIGHT_MATERIAL_ON = "dz\\gear\\cooking\\data\\GasLightOn.rvmat"
private const string GAS_LIGHT_MATERIAL_OFF = "dz\\data\\data\\default.rvmat"
const string SOUND_TURN_ON = "portablegaslamp_turn_on_SoundSet"
const string SOUND_TURN_OFF = "portablegaslamp_turn_off_SoundSet"
protected EffectSound m_SoundTurnOn
protected EffectSound m_SoundTurnOff
StoveLight m_Light
protected const string FLAME_BUTANE_ON = "dz\\gear\\cooking\\data\\flame_butane_ca.paa"
protected const string FLAME_BUTANE_OFF = ""
ATTACHMENT_COOKING_POT = Pot
ATTACHMENT_FRYING_PAN = FryingPan
ATTACHMENT_CAULDRON = Cauldron
protected const float PARAM_COOKING_TEMP_THRESHOLD = 100
protected const float PARAM_COOKING_EQUIP_TEMP_INCREASE = 10
protected const float PARAM_COOKING_EQUIP_MAX_TEMP = 250
protected const float PARAM_COOKING_TIME_INC_COEF = 0.5
private float m_TimeFactor
ref Cooking m_CookingProcess
ItemBase m_CookingEquipment
protected ref UniversalTemperatureSource m_UTSource
DEPRECATED Attached spark plug item.
protected ref UniversalTemperatureSourceSettings m_UTSSettings
protected ref UniversalTemperatureSourceLambdaConstant m_UTSLConst
float m_Fuel
private int m_FuelPercentage
protected EffectSound m_EngineLoop
protected EffectSound m_EngineStart
protected EffectSound m_EngineStop
ref Timer m_SoundLoopStartTimer
ref protected Effect m_Smoke
ItemBase m_SparkPlug
protected ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine
protected ref Timer m_Timer
SoundOnVehicle m_SoundLoopEntity
private bool m_IsFolded
private bool m_EvaluateDeployment
SpotlightLight m_Light
protected EffectSound m_DeployLoopSound
const int OPENING_0 = 1
const int OPENING_1 = 2
const int OPENING_2 = 4
const int OPENING_3 = 8
const int OPENING_4 = 16
const int OPENING_5 = 32
const int OPENING_6 = 64
const int OPENING_7 = 128
const int OPENING_8 = 256
const int OPENING_9 = 512
const int OPENING_10 = 1024
const int OPENING_11 = 2048
const int OPENING_12 = 4096
const int OPENING_13 = 8192
const int OPENING_14 = 16384
const int OPENING_15 = 32768
const float MAX_PLACEMENT_HEIGHT_DIFF = 1.5
protected int m_State
protected int m_StateLocal = -1
protected bool m_IsEntrance
protected bool m_IsWindow
protected bool m_IsToggle
protected bool m_IsBeingPacked = false
protected int m_OpeningMask = 0
protected int m_OpeningMaskLocal = -1
protected ref map< ref ToggleAnimations, bool > m_ToggleAnimations
protected ref array< string > m_ShowAnimationsWhenPitched
protected ref array< string > m_ShowAnimationsWhenPacked
protected Object m_ClutterCutter
protected CamoNet m_CamoNet
protected vector m_HalfExtents
protected int m_MineDisarmRate = 60
int m_InitWaitTime
int m_UpdateWaitTime
float m_DefectRate
bool m_IsFoldable
bool m_CanCatch = false
float m_MinimalDistanceFromPlayersToCatch
float m_BaitCatchProb
float m_NoBaitCatchProb
float m_FinalCatchProb
vector m_PreyPos
protected EntityAI m_Bait
protected bool m_IsActive
protected bool m_IsDeployed
protected bool m_IsInProgress
ref Timer m_Timer
string m_AnimationPhaseSet
string m_AnimationPhaseTriggered
string m_AnimationPhaseUsed
const string m_PlaceableWaterType protected ref array< string > m_PlaceableWaterSurfaceList
DEPRECATED.
bool m_WaterSurfaceForSetup
ref multiMap< string, float > m_CatchesPond
ref multiMap< string, float > m_CatchesSea
ref multiMap< string, float > m_CatchesGroundAnimal
protected ref EffectSound m_DeployLoopSound
ref Timer m_PrevTimer
bool m_NeedInstalation
bool m_BaitNeeded
bool m_IsUsable
private ItemBase m_Catch
ref Timer m_AlignCatchTimer
string m_InfoSetup
Static Private Attributes
static const string SLOT_TEXTURE_DIGGED_WET_LIME = "dz\\gear\\cultivation\\data\\soil_digged_wet_lime_CO.paa"
static const string SLOT_TEXTURE_DIGGED_WET_PLANT = "dz\\gear\\cultivation\\data\\soil_digged_wet_plant_CO.paa"
static const string SLOT_MATERIAL_WET = "dz\\gear\\cultivation\\data\\soil_cultivated_wet.rvmat"
static const string SLOT_MATERIAL_DRY = "dz\\gear\\cultivation\\data\\soil_cultivated.rvmat"
static const string SLOT_MATERIAL_LIMED_WET = "dz\\gear\\cultivation\\data\\soil_cultivated_limed_wet.rvmat"
static const string SLOT_MATERIAL_LIMED_DRY = "dz\\gear\\cultivation\\data\\soil_cultivated_limed.rvmat"
static const string SLOT_MATERIAL_COMPOST_WET = "dz\\gear\\cultivation\\data\\soil_cultivated_compost_wet.rvmat"
static const string SLOT_MATERIAL_COMPOST_DRY = "dz\\gear\\cultivation\\data\\soil_cultivated_compost.rvmat"
static private const string SLOT_SELECTION_DIGGED_PREFIX = "seedbase_"
static private const string SLOT_SELECTION_COVERED_PREFIX = "slotCovered_"
static private const string SLOT_MEMORY_POINT_PREFIX = "slot_"
static private const string SLOT_SEEDBASE_PREFIX = "seedbase_"
static private const int CHECK_RAIN_INTERVAL = 15
static private ref map< string, string > m_map_slots
static const int STATE_DRY = 0
static const int STATE_GROWING = 1
static const int STATE_MATURE = 2
static const int STATE_SPOILED = 3
static const int SOUNDS_SPARK_COUNT = 4
static const int SOUNDS_CUT_COUNT = 3
static const int SOUNDS_COLLISION_COUNT = 4
static const int SOUNDS_SHOCK_COUNT = 4
static const float RANDOM_SPARK_INTERVAL = 5.0
static const string m_SoundsSpark [SOUNDS_SPARK_COUNT] = {"electricFenceSpark1", "electricFenceSpark2", "electricFenceSpark3", "electricFenceSpark4"}
static const string m_SoundsCut [SOUNDS_CUT_COUNT] = {"barbedFenceCut1", "barbedFenceCut2", "barbedFenceCut3"}
static const string m_SoundsCollision [SOUNDS_COLLISION_COUNT] = {"barbedFenceCollision1", "barbedFenceCollision2", "barbedFenceCollision3", "barbedFenceCollision4"}
static const string m_SoundsShock [SOUNDS_SHOCK_COUNT] = {"electricFenceShock1", "electricFenceShock2", "electricFenceShock3", "electricFenceShock4"}
static const string m_SoundBuzzLoop = "electricFenceBuzzLoop1"
static private float m_EfficiencyDecayStart = 0.1
static protected const string SEL_CLIPS_CAR = "clips_car_battery"
static protected const string SEL_CLIPS_TRUCK = "clips_truck_battery"
static protected const string SEL_CLIPS_DETACHED = "clips_detached"
static protected const string SEL_CLIPS_FOLDED = "clips_folded"
static protected const string SEL_SWITCH_ON = "switch_on"
static protected const string SEL_SWITCH_OFF = "switch_off"
static protected const string SEL_CORD_PLUGGED = "cord_plugged"
static protected const string SEL_CORD_FOLDED = "cord_folded"
static protected const string SEL_LIGHT_STATE_1 = "light_stand_by"
static protected const string SEL_LIGHT_STATE_2 = "light_charging"
static protected const string SEL_LIGHT_STATE_3 = "light_charged"
static protected const string RED_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_r.rvmat"
static protected const string GREEN_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_g.rvmat"
static protected const string YELLOW_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_y.rvmat"
static protected const string SWITCH_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_switch_on.rvmat"
static protected const string DEFAULT_MATERIAL = "dz\\gear\\camping\\data\\battery_charger.rvmat"
static protected float m_BlinkingStatusLightInterval = 0.4
static const string SEL_CORD_FOLDED = "cord_folded"
static const string SEL_CORD_PLUGGED = "cord_plugged"
static const string CHARGING_SOUND = "defibrillator_charge_SoundSet"
static const string CHARGED_AND_READY_SOUND = "defibrillator_ready_SoundSet"
static const string SHOCK_SOUND = "defibrillator_shock_SoundSet"
static float m_ChargeTime = 5
static float m_EnergyNeededToCharge = 20
static int REFLECTOR_ID = 1
static int GLASS_ID = 2
static string LIGHT_OFF_GLASS = "dz\\gear\\tools\\data\\flashlight_glass.rvmat"
static string LIGHT_OFF_REFLECTOR = "dz\\gear\\tools\\data\\flashlight.rvmat"
static string LIGHT_ON_GLASS = "dz\\gear\\tools\\data\\flashlight_glass_on.rvmat"
static string LIGHT_ON_REFLECTOR = "dz\\gear\\tools\\data\\flashlight_glass_on.rvmat"
static string SEL_WIRE_ROLLED = "rolled"
static string SEL_WIRE_PREFIX = "Att_"
static string SEL_WIRE_SUFIX = "_plugged"
static string SEL_PLUG_SUFIX = "_plug"
static private float m_FuelTankCapacity
static private float m_FuelToEnergyRatio
static const string START_SOUND = "powerGeneratorTurnOn_SoundSet"
static const string LOOP_SOUND = "powerGeneratorLoop_SoundSet"
static const string STOP_SOUND = "powerGeneratorTurnOff_SoundSet"
static const string SPARKPLUG_ATTACH_SOUND = "sparkplug_attach_SoundSet"
static const string SPARKPLUG_DETACH_SOUND = "sparkplug_detach_SoundSet"
static vector m_LightLocalPosition
static vector m_LightLocalOrientation = "0 0 0"
static const string SEL_REFLECTOR_COMP_U = "reflector"
static const string SEL_CORD_FOLDED_U = "cord_folded"
static const string SEL_CORD_PLUGGED_U = "cord_plugged"
static const string SEL_CORD_PLUGGED_F = "spotlight_folded_cord_plugged"
static const string SEL_CORD_FOLDED_F = "spotlight_folded_cord_folded"
static const string SEL_INVENTORY = "inventory"
static const string SEL_PLACING = "placing"
static const string SEL_GLASS_F = "glass_folded"
static const string SEL_GLASS_U = "glass_unfolded"
static const string SEL_REFLECTOR_F = "reflector_folded"
static const string SEL_REFLECTOR_U = "reflector_unfolded"
static const int ID_GLASS_UNFOLDED = 3
static const int ID_REFLECTOR_UNFOLDED = 4
static const int ID_GLASS_FOLDED = 5
static const int ID_REFLECTOR_FOLDED = 6
static const int PACKED = 0
static const int PITCHED = 1
Detailed Description
Definition at line 762 of file InventoryItem.c.
Constructor & Destructor Documentation
~Clothing_Base()
void ~Clothing_Base () inline private
Definition at line 862 of file InventoryItem.c.
~PlantBase()
void ~PlantBase () inline private
Definition at line 76 of file PlantBase.c.
References DestroyPlant().
~BarbedWire()
void ~BarbedWire () inline private
Definition at line 44 of file BarbedWire.c.
References SEffectManager::DestroyEffect(), and m_DeployLoopSound.
~Defibrillator()
void ~Defibrillator () inline private
Definition at line 23 of file Defibrillator.c.
References SEffectManager::DestroyEffect().
~Flag_Base()
void ~Flag_Base () inline private
Definition at line 11 of file Flag_Base.c.
~RestrainingToolLocked()
void ~RestrainingToolLocked () inline private
Definition at line 3 of file HandcuffsLocked.c.
~KitBase()
void ~KitBase () inline private
Definition at line 12 of file KitBase.c.
References SEffectManager::DestroyEffect(), and m_DeployLoopSound.
~Paper()
void ~Paper () inline private
Definition at line 10 of file Paper.c.
~PowerGenerator()
void ~PowerGenerator () inline private
Definition at line 37 of file PowerGenerator.c.
References SEffectManager::DestroyEffect().
~Spotlight()
void ~Spotlight () inline private
Definition at line 52 of file Spotlight.c.
References SEffectManager::DestroyEffect(), and m_DeployLoopSound.
~TentBase()
void ~TentBase () inline private
Definition at line 61 of file TentBase.c.
References SEffectManager::DestroyEffect(), GetGame(), and m_DeployLoopSound.
~TrapSpawnBase()
void ~TrapSpawnBase () inline private
Definition at line 81 of file TrapSpawnBase.c.
References SEffectManager::DestroyEffect(), and m_DeployLoopSound.
Member Function Documentation
AddDefect()
void AddDefect () inline private
Definition at line 235 of file TrapSpawnBase.c.
References DecreaseHealth(), GetGame(), and m_DefectRate.
AddFuel()
float AddFuel (float available_fuel) inline private
Definition at line 275 of file PowerGenerator.c.
References GetFuel(), GetMaxFuel(), and SetFuel().
AfterStoreLoad() [1/5]
override void AfterStoreLoad () inline private
Definition at line 183 of file GardenBase.c.
AfterStoreLoad() [2/5]
override void AfterStoreLoad () inline private
Definition at line 198 of file BarbedWire.c.
References GetSlotLockedState(), and SetMountedState().
AfterStoreLoad() [3/5]
override void AfterStoreLoad () inline private
Definition at line 431 of file BaseBuildingBase.c.
References m_FixDamageSystemInit, and SetPartsAfterStoreLoad().
AfterStoreLoad() [4/5]
override void AfterStoreLoad () inline private
Definition at line 220 of file Edible_Base.c.
References Synchronize().
AfterStoreLoad() [5/5]
override void AfterStoreLoad () inline private
Definition at line 45 of file Flag_Base.c.
AlignCatch()
void AlignCatch (ItemBase obj, string catch_name) inline private
Definition at line 528 of file TrapSpawnBase.c.
AnimateCamonetByOpeningSelection()
void AnimateCamonetByOpeningSelection (string opening_selection) inline private
Definition at line 816 of file TentBase.c.
AnimateCamonetToggle()
void AnimateCamonetToggle (ToggleAnimations toggle) inline private
Definition at line 814 of file TentBase.c.
AssembleKit()
void AssembleKit () inline private
Definition at line 172 of file KitBase.c.
References IsHologram().
BarbedWire()
void BarbedWire () inline private
Definition at line 32 of file BarbedWire.c.
References CALL_CATEGORY_SYSTEM.
BaseBuildingBase()
void BaseBuildingBase () inline private
Definition at line 39 of file BaseBuildingBase.c.
References ConfigGetTextArray(), ConfigIsExisting(), ConstructionInit(), GetInvulnerabilityTypeString(), m_DamageTriggers, m_HybridAttachments, and m_Mountables.
Battery9V()
void Battery9V () inline private
Definition at line 6 of file Battery9V.c.
BatteryCharger()
void BatteryCharger () inline private
Definition at line 35 of file BatteryCharger.c.
References CALL_CATEGORY_SYSTEM, CGame::ConfigGetFloat(), GetGame(), GetType(), and SwitchLightOff().
Referenced by VehicleBattery::CanPutAsAttachment().
BloodContainerBase()
void BloodContainerBase () inline private
Definition at line 5 of file BloodContainerBase.c.
CableReel()
void CableReel () inline private
Definition at line 8 of file CableReel.c.
CalcDamageAreaRotation()
void CalcDamageAreaRotation (float angle_deg, out vector center, out vector orientation) inline private
Definition at line 1040 of file BaseBuildingBase.c.
References Math::Cos(), Math::DEG2RAD, GetMemoryPointPos(), MemoryPointExists(), ModelToWorld(), and Math::Sin().
CanAddFuel()
bool CanAddFuel (ItemBase container) inline private
Definition at line 297 of file PowerGenerator.c.
References GetEnergy(), and LIQUID_GASOLINE.
CanAssignAttachmentsToQuickbar()
override bool CanAssignAttachmentsToQuickbar () inline private
Definition at line 111 of file KitBase.c.
CanAssignToQuickbar()
override bool CanAssignToQuickbar () inline private
Definition at line 72 of file Rag.c.
CanAttach()
bool CanAttach (ItemBase item) inline private
Definition at line 536 of file TentBase.c.
References GetState().
CanBeCombined()
override bool CanBeCombined (EntityAI other_item, bool reservation_check = true, bool stack_max_limit = false) inline private
Definition at line 52 of file Rag.c.
Referenced by AttachmentCategoriesRow::CanCombine(), AttachmentCategoriesRow::Combine(), InventoryItem::CombineItems(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), ActionAttachOnSelection::FindSlotIdToAttachOrCombine(), ConstructionActionData::GetAttachmentSlotFromSelection(), HandsContainer::GetCombinationFlags(), and ItemManager::GetCombinationFlags().
CanBeCooked()
override bool CanBeCooked () inline private
Definition at line 95 of file Edible_Base.c.
Referenced by AddDamageToItemByFire(), and AddDamageToItemByFireEx().
CanBeCookedOnStick()
override bool CanBeCookedOnStick () inline private
Definition at line 100 of file Edible_Base.c.
CanBeDisinfected() [1/2]
override bool CanBeDisinfected () inline private
Definition at line 54 of file BandageDressing.c.
Referenced by RecipeBase::CanDo().
CanBeDisinfected() [2/2]
override bool CanBeDisinfected () inline private
Definition at line 77 of file Rag.c.
CanBeIgnitedBy() [1/5]
override bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 11 of file BandageDressing.c.
Referenced by ActionCondition(), CreateActionComponent(), and OnFinishProgressServer().
CanBeIgnitedBy() [2/5]
override bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 11 of file Bark_ColorBase.c.
CanBeIgnitedBy() [3/5]
override bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 11 of file GiftWrapPaper.c.
CanBeIgnitedBy() [4/5]
override bool CanBeIgnitedBy (EntityAI igniter = null) inline private
Definition at line 43 of file Paper.c.
CanBeIgnitedBy() [5/5]
override bool CanBeIgnitedBy (EntityAI igniter = null) inline private
Definition at line 42 of file Rag.c.
CanBeManipulated()
bool CanBeManipulated () inline private
Definition at line 524 of file TentBase.c.
References GetState().
CanBePacked()
bool CanBePacked () inline private
Definition at line 511 of file TentBase.c.
References GetState().
CanBePlaced() [1/2]
override bool CanBePlaced (Man player, vector position) inline private
Definition at line 1030 of file TentBase.c.
Referenced by ActionDeployHuntingTrap::ActionCondition(), ActionCondition(), ActionDeployHuntingTrap::ActionConditionContinue(), ActionConditionContinue(), and Hologram::IsPlacementPermitted().
CanBePlaced() [2/2]
override bool CanBePlaced (Man player, vector position) inline private
Definition at line 551 of file TrapSpawnBase.c.
References TrapSpawnBase::IsPlaceableAtPosition().
CanBeRepairedByCrafting()
override bool CanBeRepairedByCrafting () inline private
Definition at line 86 of file TentBase.c.
Referenced by RecipeBase::CanDo().
CanBeRepairedToPristine()
override bool CanBeRepairedToPristine () inline private
Definition at line 333 of file TentBase.c.
CanBeTaken()
bool CanBeTaken () inline private
Definition at line 247 of file TrapSpawnBase.c.
CanChangeToNewStage()
bool CanChangeToNewStage (CookingMethodType cooking_method) inline private
Definition at line 456 of file Edible_Base.c.
References GetFoodStage().
CanDecay()
override bool CanDecay () inline private
Definition at line 540 of file Edible_Base.c.
Referenced by InventoryItem::OnCEUpdate(), and TransferItemVariables().
CanDetachAttachment()
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 42 of file GardenLime.c.
Referenced by ActionPackGift::ActionCondition(), ActionRepositionPluggedItem::ActionCondition(), ActionTakeItem::ActionCondition(), and ActionTakeItemToHands::ActionCondition().
CanDisplayAttachmentSlot()
override bool CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 453 of file TrapSpawnBase.c.
CanDisplayCargo()
override bool CanDisplayCargo () inline private
Definition at line 24 of file UndergroundStash.c.
CanExplodeInFire() [1/3]
override bool CanExplodeInFire () inline private
Definition at line 3 of file LargeGasCannister.c.
Referenced by InventoryItem::EEKilled().
CanExplodeInFire() [2/3]
override bool CanExplodeInFire () inline private
Definition at line 3 of file MediumGasCannister.c.
CanExplodeInFire() [3/3]
override bool CanExplodeInFire () inline private
Definition at line 3 of file SmallGasCannister.c.
CanFoldBaseBuildingObject()
bool CanFoldBaseBuildingObject () inline private
Definition at line 973 of file BaseBuildingBase.c.
References HasBase().
CanHaveTemperature()
override bool CanHaveTemperature () inline private
Definition at line 535 of file Edible_Base.c.
Referenced by InventoryItem::OnCEUpdate().
CanIgniteItem() [1/10]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 18 of file BandageDressing.c.
Referenced by ActionCondition(), CreateActionComponent(), and OnFinishProgressServer().
CanIgniteItem() [2/10]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 18 of file Bark_ColorBase.c.
CanIgniteItem() [3/10]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 94 of file Blowtorch.c.
CanIgniteItem() [4/10]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 18 of file GiftWrapPaper.c.
CanIgniteItem() [5/10]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Override this method and and check if the given item can be ignited. It is not necesarry to check here if the item is not in cargo of something.
Definition at line 4 of file HandDrillKit.c.
CanIgniteItem() [6/10]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 9 of file Matchbox.c.
References GetQuantity(), GetWet(), and GameConstants::STATE_DAMP.
CanIgniteItem() [7/10]
override bool CanIgniteItem (EntityAI ignite_target = null) inline private
Definition at line 48 of file Paper.c.
CanIgniteItem() [8/10]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 3 of file PetrolLighter.c.
References GetQuantity().
CanIgniteItem() [9/10]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 333 of file PortableGasStove.c.
CanIgniteItem() [10/10]
override bool CanIgniteItem (EntityAI ignite_target = null) inline private
Definition at line 47 of file Rag.c.
CanLoadAttachment() [1/2]
override bool CanLoadAttachment (EntityAI attachment) inline private
Definition at line 268 of file BatteryCharger.c.
References Class::CastTo().
Referenced by FireplaceBase::CanLoadAttachment().
CanLoadAttachment() [2/2]
override bool CanLoadAttachment (EntityAI attachment) inline private
Definition at line 1022 of file TentBase.c.
References GetHealthLevel(), and GameConstants::STATE_RUINED.
CanLoadItemIntoCargo()
override bool CanLoadItemIntoCargo (EntityAI item) inline private
Definition at line 1004 of file TentBase.c.
References GetHealthLevel(), and GameConstants::STATE_RUINED.
CanMakeGardenplot() [1/3]
override bool CanMakeGardenplot () inline private
Definition at line 3 of file FieldShovel.c.
Referenced by Hologram::DoesHaveProjection(), and Hologram::GetProjectionName().
CanMakeGardenplot() [2/3]
override bool CanMakeGardenplot () inline private
Definition at line 3 of file PickAxe.c.
CanMakeGardenplot() [3/3]
override bool CanMakeGardenplot () inline private
Definition at line 3 of file Shovel.c.
CanManipulate()
bool CanManipulate () inline private
Definition at line 117 of file PowerGenerator.c.
Referenced by CanPutInCargo(), and CanPutIntoHands().
CanObstruct()
override bool CanObstruct () inline private
Definition at line 73 of file BaseBuildingBase.c.
CanPlantSeed()
bool CanPlantSeed (string selection_component) inline private
Definition at line 313 of file GardenBase.c.
CanProcessDecay()
override bool CanProcessDecay () inline private
Definition at line 545 of file Edible_Base.c.
References GetFoodStageType().
Referenced by InventoryItem::OnCEUpdate().
CanPutAsAttachment() [1/5]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 5 of file ItemBase.c.
CanPutAsAttachment() [2/5]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file GardenLime.c.
CanPutAsAttachment() [3/5]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file GrozaGL_LowerReceiver.c.
CanPutAsAttachment() [4/5]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 13 of file MetalWire.c.
CanPutAsAttachment() [5/5]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 19 of file Rag.c.
References GetQuantity().
CanPutInCargo() [1/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 288 of file GardenBase.c.
Referenced by ActionPackGift::ActionCondition().
CanPutInCargo() [2/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 443 of file PlantBase.c.
CanPutInCargo() [3/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 920 of file BaseBuildingBase.c.
CanPutInCargo() [4/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 192 of file BatteryCharger.c.
CanPutInCargo() [5/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 61 of file Blowtorch.c.
CanPutInCargo() [6/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 27 of file CableReel.c.
CanPutInCargo() [7/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 101 of file PileOfWoodenPlanks.c.
CanPutInCargo() [8/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 298 of file PortableGasStove.c.
CanPutInCargo() [9/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 96 of file PowerGenerator.c.
References CanManipulate().
CanPutInCargo() [10/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 317 of file Spotlight.c.
CanPutInCargo() [11/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 318 of file TentBase.c.
CanPutInCargo() [12/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 257 of file TrapSpawnBase.c.
CanPutInCargo() [13/13]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 29 of file UndergroundStash.c.
CanPutInInventory()
bool CanPutInInventory (EntityAI player) inline private
Definition at line 526 of file TrapSpawnBase.c.
CanPutIntoHands() [1/12]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 931 of file BaseBuildingBase.c.
CanPutIntoHands() [2/12]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 91 of file PileOfWoodenPlanks.c.
CanPutIntoHands() [3/12]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 314 of file PortableGasStove.c.
CanPutIntoHands() [4/12]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 308 of file TentBase.c.
CanPutIntoHands() [5/12]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 263 of file TrapSpawnBase.c.
CanPutIntoHands() [6/12]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 49 of file UndergroundStash.c.
CanPutIntoHands() [7/12]
override bool CanPutIntoHands (EntityAI player) inline private
Definition at line 294 of file GardenBase.c.
CanPutIntoHands() [8/12]
override bool CanPutIntoHands (EntityAI player) inline private
Definition at line 448 of file PlantBase.c.
CanPutIntoHands() [9/12]
override bool CanPutIntoHands (EntityAI player) inline private
Definition at line 204 of file BatteryCharger.c.
CanPutIntoHands() [10/12]
override bool CanPutIntoHands (EntityAI player) inline private
Definition at line 40 of file CableReel.c.
CanPutIntoHands() [11/12]
override bool CanPutIntoHands (EntityAI player) inline private
Definition at line 107 of file PowerGenerator.c.
References CanManipulate().
CanPutIntoHands() [12/12]
override bool CanPutIntoHands (EntityAI player) inline private
Definition at line 325 of file Spotlight.c.
CanReceiveAttachment() [1/4]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 893 of file BaseBuildingBase.c.
Referenced by FireplaceBase::CanReceiveAttachment(), FlammableBase::CanReceiveAttachment(), and KitBase::CanReceiveAttachment().
CanReceiveAttachment() [2/4]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 245 of file BatteryCharger.c.
References Class::CastTo().
CanReceiveAttachment() [3/4]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 1014 of file TentBase.c.
References GetHealthLevel(), and GameConstants::STATE_RUINED.
CanReceiveAttachment() [4/4]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 459 of file TrapSpawnBase.c.
CanReceiveItemIntoCargo()
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 996 of file TentBase.c.
References GetHealthLevel(), and GameConstants::STATE_RUINED.
CanReceiveItemIntoHands()
override bool CanReceiveItemIntoHands (EntityAI item_to_hands) inline private
Definition at line 39 of file UndergroundStash.c.
CanReleaseCargo()
override bool CanReleaseCargo (EntityAI cargo) inline private
Definition at line 34 of file UndergroundStash.c.
CanRemoveFromCargo() [1/3]
override bool CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 925 of file BaseBuildingBase.c.
Referenced by ActionPackGift::ActionCondition().
CanRemoveFromCargo() [2/3]
override bool CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 71 of file Blowtorch.c.
CanRemoveFromCargo() [3/3]
override bool CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 308 of file PortableGasStove.c.
CanRemoveFromHands() [1/3]
override bool CanRemoveFromHands (EntityAI player) inline private
Definition at line 303 of file GardenBase.c.
CanRemoveFromHands() [2/3]
override bool CanRemoveFromHands (EntityAI player) inline private
Definition at line 453 of file PlantBase.c.
CanRemoveFromHands() [3/3]
override bool CanRemoveFromHands (EntityAI player) inline private
Definition at line 86 of file CableReel.c.
CanSaveItemInHands()
override bool CanSaveItemInHands (EntityAI item_in_hands) inline private
Definition at line 44 of file UndergroundStash.c.
CanSwapEntities()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination) inline private
Definition at line 3 of file Rag.c.
CanToggleAnimations()
bool CanToggleAnimations (string selection) inline private
Definition at line 688 of file TentBase.c.
References GetHealthLevel(), ToggleAnimations::GetToggleOff(), ToggleAnimations::GetToggleOn(), GameConstants::STATE_RUINED, and string::ToLower().
CanUseConstruction()
override bool CanUseConstruction () inline private
Definition at line 822 of file BaseBuildingBase.c.
CanUseConstructionBuild()
override bool CanUseConstructionBuild () inline private
Definition at line 827 of file BaseBuildingBase.c.
CatchSetQuant()
void CatchSetQuant (ItemBase catch) inline private
Definition at line 406 of file TrapSpawnBase.c.
References HasQuantity(), Math::RandomFloatInclusive(), and Math::Round().
ChangeFoodStage()
void ChangeFoodStage (FoodStageType new_food_stage_type) inline private
Definition at line 441 of file Edible_Base.c.
References GetFoodStage().
ChangeInfestation()
void ChangeInfestation (bool is_infested) inline private
Definition at line 458 of file PlantBase.c.
References GetType(), PlantMaterialHealth::m_HealthyMat, PlantMaterialHealth::m_HealthyTex, PlantMaterialHealth::m_InfestedMat, and PlantMaterialHealth::m_InfestedTex.
Referenced by InfestationTimerTick(), SprayPlant(), and StopInfestation().
CheckForHybridAttachments()
void CheckForHybridAttachments (EntityAI item, string slot_name) inline private
Definition at line 1134 of file BaseBuildingBase.c.
References GetGame(), m_HybridAttachments, and SetHealth().
CheckLevelVerticalDistance()
protected bool CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player) inline private
Definition at line 870 of file BaseBuildingBase.c.
CheckMemoryPointVerticalDistance()
protected bool CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player) inline private
Definition at line 865 of file BaseBuildingBase.c.
CheckRainStart()
void CheckRainStart () inline private
Definition at line 778 of file GardenBase.c.
References CALL_CATEGORY_SYSTEM.
CheckRainTick()
void CheckRainTick () inline private
Definition at line 786 of file GardenBase.c.
References WeatherPhenomenon::GetActual(), GetGame(), GardenBase::GetGardenSlotsCount(), Weather::GetRain(), CGame::GetWeather(), and Math::RandomFloat01().
CheckSlotVerticalDistance()
bool CheckSlotVerticalDistance (int slot_id, PlayerBase player) inline private
Definition at line 860 of file BaseBuildingBase.c.
CheckWater()
void CheckWater () inline private
Definition at line 623 of file PlantBase.c.
References CALL_CATEGORY_SYSTEM, GetGame(), IsMature(), NeedsWater(), and SetPlantState().
Referenced by Init().
ClearCookingEquipment()
void ClearCookingEquipment (ItemBase pItem) inline private
Definition at line 46 of file PortableGasStove.c.
References m_CookingProcess, and SetCookingEquipment().
Clothing_Base()
void Clothing_Base () inline private
Definition at line 857 of file InventoryItem.c.
References ConfigGetFloat().
ConditionIntoInventory()
bool ConditionIntoInventory (EntityAI player) inline private
Definition at line 303 of file TentBase.c.
ConditionOutOfHands()
bool ConditionOutOfHands (EntityAI player) inline private
Definition at line 328 of file TentBase.c.
ConstructionInit()
void ConstructionInit () inline private
Definition at line 876 of file BaseBuildingBase.c.
References Construction(), GetConstruction(), and m_Construction.
Consume()
bool Consume (float amount, PlayerBase consumer) inline private
Definition at line 85 of file Edible_Base.c.
References AddQuantity(), and Edible_Base::OnConsume().
ConvertAttSlotToPlantSlot()
string ConvertAttSlotToPlantSlot (string attach_slot) inline private
Definition at line 328 of file GardenBase.c.
References string::Get().
CookWithEquipment()
void CookWithEquipment () inline private
Definition at line 213 of file PortableGasStove.c.
References GetCookingEquipment(), and m_CookingProcess.
Referenced by OnWork().
CreateAreaDamage()
void CreateAreaDamage (string slot_name, float rotation_angle = 0) inline private
Definition at line 991 of file BaseBuildingBase.c.
References CalcDamageAreaRotation(), DestroyAreaDamage(), GetConstruction(), GetGame(), GetMemoryPointPos(), GetOrientation(), AreaDamageComponentTypes::HITZONE, m_DamageTriggers, MemoryPointExists(), ModelToWorld(), AreaDamageLoopedDeferred::SetDeferDuration(), and AreaDamageLooped::SetLoopInterval().
CreateConstructionKit()
ItemBase CreateConstructionKit () inline private
Definition at line 341 of file BaseBuildingBase.c.
References ECE_PLACE_ON_SURFACE, BaseBuildingBase::GetConstructionKitType(), GetGame(), BaseBuildingBase::GetKitSpawnPosition(), and m_ConstructionKitHealth.
CreateConstructionKitInHands()
void CreateConstructionKitInHands (notnull PlayerBase player) inline private
Definition at line 352 of file BaseBuildingBase.c.
References BaseBuildingBase::GetConstructionKitType(), and m_ConstructionKitHealth.
CreateDamageTrigger()
protected void CreateDamageTrigger () inline private
Definition at line 270 of file BarbedWire.c.
References m_AreaDamage.
Referenced by OnPlacementComplete(), and OnWorkStop().
CreateElectrifiedDamageTrigger()
protected void CreateElectrifiedDamageTrigger () inline private
Definition at line 259 of file BarbedWire.c.
References m_AreaDamage.
Referenced by OnPlacementComplete(), and OnWorkStart().
CreatePlant()
void CreatePlant (Slot slot) inline private
Definition at line 429 of file GardenBase.c.
References g_Game, GetGame(), and CGame::ObjectDelete().
CreateRope()
void CreateRope (Rope rope) inline private
Definition at line 182 of file KitBase.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and InventoryLocation::GetType().
DebugCustomState()
protected void DebugCustomState () inline private
Definition at line 1165 of file BaseBuildingBase.c.
Defibrillator()
void Defibrillator () inline private
Definition at line 16 of file Defibrillator.c.
References GetEnergyNeededToCharge().
DeleteDryPlantTick()
void DeleteDryPlantTick () inline private
Definition at line 595 of file PlantBase.c.
DestroyAreaDamage()
void DestroyAreaDamage (string slot_name) inline private
Definition at line 1060 of file BaseBuildingBase.c.
References GetGame(), and m_DamageTriggers.
DestroyClutterCutter()
void DestroyClutterCutter () inline private
Definition at line 860 of file TentBase.c.
References GetGame(), m_ClutterCutter, and CGame::ObjectDelete().
DestroyConstruction()
void DestroyConstruction () inline private
Definition at line 378 of file BaseBuildingBase.c.
References bsbDebugPrint(), GetDebugName(), GetGame(), and CGame::ObjectDelete().
DestroyConstructionKit()
void DestroyConstructionKit (ItemBase construction_kit) inline private
Definition at line 371 of file BaseBuildingBase.c.
References GetGame(), m_ConstructionKitHealth, and CGame::ObjectDelete().
DestroyDamageTrigger()
protected void DestroyDamageTrigger () inline private
Definition at line 280 of file BarbedWire.c.
References m_AreaDamage.
Referenced by OnInventoryEnter(), OnIsUnplugged(), OnItemLocationChanged(), OnWorkStart(), and OnWorkStop().
DestroyFireplace()
void DestroyFireplace () inline private
Definition at line 57 of file PortableGasStove.c.
References GetGame(), and CGame::ObjectDelete().
DestroyPlant()
void DestroyPlant () inline private
Definition at line 723 of file PlantBase.c.
References GetGame(), RemoveSlot(), and UnlockFromParent().
Referenced by ~PlantBase().
DisassembleKit()
void DisassembleKit (ItemBase item) inline private
Definition at line 180 of file KitBase.c.
DisassembleOnLastDetach()
override bool DisassembleOnLastDetach () inline private
Definition at line 63 of file KitBase.c.
Referenced by PluginRecipesManagerBase::GetValidRecipes().
DischargeClient()
void DischargeClient (PlayerBase victim) inline private
Definition at line 142 of file Defibrillator.c.
References SEffectManager::PlaySoundOnObject().
DischargeServer()
void DischargeServer (PlayerBase victim) inline private
Definition at line 116 of file Defibrillator.c.
DisplayNameRuinAttach() [1/2]
override bool DisplayNameRuinAttach () inline private
Definition at line 798 of file InventoryItem.c.
DisplayNameRuinAttach() [2/2]
override bool DisplayNameRuinAttach () inline private
Definition at line 830 of file InventoryItem.c.
DoMeasurement()
void DoMeasurement () inline private
Definition at line 31 of file Raycaster.c.
References vector::AnglesToVector(), ParticleList::DEBUG_DOT, GetMemoryPointPos(), GetOrientation(), GetPosition, ParticleManager(), Math::RandomFloat(), DayZPhysics::RaycastRV(), Vector(), and vector::VectorToAngles().
Referenced by PrepareMeasurement().
Edible_Base()
void Edible_Base () inline private
Definition at line 18 of file Edible_Base.c.
References HasFoodStage(), m_FoodStage, and m_SoundPlaying.
EEDelete() [1/2]
override void EEDelete (EntityAI parent) inline private
Definition at line 44 of file Edible_Base.c.
References RemoveAudio().
EEDelete() [2/2]
override void EEDelete (EntityAI parent) inline private
Definition at line 35 of file ParticleTest.c.
References GetGame(), CGame::ObjectDelete(), and Particle::Stop().
EEHealthLevelChanged() [1/2]
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 454 of file BaseBuildingBase.c.
References AT_DESTROY_PART, Construction(), string::Contains(), GetConstruction(), GetGame(), m_FixDamageSystemInit, GameConstants::STATE_RUINED, and string::ToLower().
EEHealthLevelChanged() [2/2]
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 237 of file TentBase.c.
References TentBase::AnimateCamonetByOpeningSelection(), GetGame(), GetState(), m_FixDamageSystemInit, m_HalfExtents, RemoveProxyPhysics(), and GameConstants::STATE_RUINED.
EEInit() [1/6]
override void EEInit () inline private
Definition at line 49 of file BarbedWire.c.
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
EEInit() [2/6]
override void EEInit () inline private
Definition at line 498 of file BaseBuildingBase.c.
References DebugCustomState(), and InitBaseState().
EEInit() [3/6]
override void EEInit () inline private
Definition at line 36 of file Edible_Base.c.
References UpdateVisuals().
EEInit() [4/6]
override void EEInit () inline private
Definition at line 52 of file KitBase.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), UpdatePhysics(), and UpdateVisuals().
EEInit() [5/6]
override void EEInit () inline private
Definition at line 63 of file PortableGasStove.c.
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSource, and m_UTSSettings.
EEInit() [6/6]
override void EEInit () inline private
Definition at line 42 of file PowerGenerator.c.
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEItemAttached() [1/6]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 340 of file GardenBase.c.
References CGame::ConfigIsExisting(), string::Format(), g_Game, GetGame(), GetPosition, InventorySlots::GetSlotIdFromString(), path, and string::ToString().
EEItemAttached() [2/6]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 511 of file BaseBuildingBase.c.
References CheckForHybridAttachments(), UpdateAttachmentPhysics(), and BaseBuildingBase::UpdateVisuals().
EEItemAttached() [3/6]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 83 of file PortableGasStove.c.
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, RefreshFlameVisual(), and SetCookingEquipment().
EEItemAttached() [4/6]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 208 of file PowerGenerator.c.
References GetPosition, IsInitialized(), SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
EEItemAttached() [5/6]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 371 of file TentBase.c.
References AddProxyPhysics(), TentBase::HandleCamoNetAttachment(), and IsKindOf().
EEItemAttached() [6/6]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 465 of file TrapSpawnBase.c.
References SetActive().
EEItemDetached() [1/6]
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 378 of file GardenBase.c.
References CGame::ConfigIsExisting(), string::Format(), GetGame(), path, and string::ToLower().
EEItemDetached() [2/6]
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 520 of file BaseBuildingBase.c.
References UpdateAttachmentPhysics(), and BaseBuildingBase::UpdateVisuals().
EEItemDetached() [3/6]
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 68 of file KitBase.c.
References Delete(), KitBase::DisassembleKit(), and GetGame().
EEItemDetached() [4/6]
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 99 of file PortableGasStove.c.
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ClearCookingEquipment(), RefreshFlameVisual(), and RemoveCookingAudioVisuals().
EEItemDetached() [5/6]
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 225 of file PowerGenerator.c.
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
EEItemDetached() [6/6]
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 400 of file TentBase.c.
References TentBase::HandleCamoNetAttachment(), IsKindOf(), and RemoveProxyPhysics().
EEItemLocationChanged() [1/4]
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
disable sounds (from cooking)
check for DirectCooking slot name
Definition at line 52 of file Edible_Base.c.
References string::Contains(), DIRECT_COOKING_SLOT_NAME, InventorySlots::GetSlotName(), and MakeSoundsOnClient().
EEItemLocationChanged() [2/4]
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 12 of file HandcuffsLocked.c.
References Delete(), and GetGame().
EEItemLocationChanged() [3/4]
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 64 of file PileOfWoodenPlanks.c.
References UpdateSelections().
EEItemLocationChanged() [4/4]
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 25 of file Switchable_Base.c.
References Switchable_Base::GetLight().
EEOnAfterLoad() [1/2]
override void EEOnAfterLoad () inline private
Definition at line 188 of file GardenBase.c.
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and SyncSlots().
EEOnAfterLoad() [2/2]
override void EEOnAfterLoad () inline private
Definition at line 488 of file BaseBuildingBase.c.
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), m_FixDamageSystemInit, and SetPartsAfterStoreLoad().
EOnInit() [1/3]
override void EOnInit (IEntity other, int extra) inline private
Definition at line 95 of file GardenBase.c.
EOnInit() [2/3]
override void EOnInit (IEntity other, int extra) inline private
Definition at line 61 of file PowerGenerator.c.
References GetGame(), and UpdateFuelMeter().
EOnInit() [3/3]
override void EOnInit (IEntity other, int extra) inline private
Definition at line 78 of file Spotlight.c.
References IsHologram(), Unfold(), and UpdateAllSelections().
Fertilize()
void Fertilize (PlayerBase player, ItemBase item, float consumed_quantity, string selection_component) inline private
Definition at line 448 of file GardenBase.c.
References Math::Clamp(), CGame::ConfigGetFloat(), and GetGame().
Flag_Base()
void Flag_Base () inline private
Definition at line 3 of file Flag_Base.c.
Fold() [1/2]
void Fold () inline private
Definition at line 226 of file TrapSpawnBase.c.
References GetGame(), and SetInactive().
Referenced by OnInitEnergy(), OnIsUnplugged(), OnItemLocationChanged(), OnPlacementCancelled(), and OnStoreLoad().
Fold() [2/2]
void Fold (bool keep_connected = false) inline private
Definition at line 267 of file Spotlight.c.
References UpdateAllSelections().
FoldBaseBuildingObject()
ItemBase FoldBaseBuildingObject () inline private
Definition at line 983 of file BaseBuildingBase.c.
References CreateConstructionKit(), and DestroyConstruction().
ForceIntoHandsNow()
void ForceIntoHandsNow (PlayerBase player) inline private
Definition at line 20 of file CableReel.c.
FullyBuild()
void FullyBuild () inline private
Definition at line 1180 of file BaseBuildingBase.c.
References AT_BUILD_PART, string::Contains(), GetConstruction(), GetGame(), CGame::GetPlayer(), World::GetPlayerList(), CGame::GetWorld(), BaseBuildingBase::OnDebugSpawnBuildExcludes(), and BaseBuildingBase::OnPartBuiltServer().
GardenBase()
void GardenBase () inline private
Definition at line 34 of file GardenBase.c.
References GetGame(), GardenBase::GetGardenSlotsCount(), CGame::IsServer(), string::Set(), and string::ToString().
GetAttachmentSlots()
void GetAttachmentSlots (EntityAI entity, out array< string > attachment_slots) inline private
Definition at line 851 of file BaseBuildingBase.c.
References CGame::ConfigGetTextArray(), ConfigIsExisting(), and GetGame().
GetBandagingEffectivity() [1/2]
override float GetBandagingEffectivity () inline private
Definition at line 49 of file BandageDressing.c.
Referenced by ActionBandageSelfCB::CreateActionComponent(), and ActionBandageTargetCB::CreateActionComponent().
GetBandagingEffectivity() [2/2]
override float GetBandagingEffectivity () inline private
Definition at line 107 of file Rag.c.
GetBaseFertility()
float GetBaseFertility () inline private
Definition at line 90 of file GardenBase.c.
GetBloodTypeVisible()
bool GetBloodTypeVisible () inline private
Definition at line 21 of file BloodContainerBase.c.
GetBuildSoundByMaterial()
protected string GetBuildSoundByMaterial (string part_name) inline private
Definition at line 1101 of file BaseBuildingBase.c.
References GetConstruction(), SOUND_BUILD_METAL, SOUND_BUILD_WIRE, SOUND_BUILD_WOOD_LOG, SOUND_BUILD_WOOD_PLANK, and SOUND_BUILD_WOOD_STAIRS.
GetClutterCutter()
string GetClutterCutter () inline private
Definition at line 858 of file TentBase.c.
GetConstruction()
Construction GetConstruction () inline private
Definition at line 886 of file BaseBuildingBase.c.
References m_Construction.
GetConstructionKitType()
protected string GetConstructionKitType () inline private
Definition at line 366 of file BaseBuildingBase.c.
GetConstructionPartById()
protected ConstructionPart GetConstructionPartById (int id) inline private
Definition at line 299 of file BaseBuildingBase.c.
References Construction(), GetConstruction(), and ConstructionPart::GetId().
GetCookingEquipment()
ItemBase GetCookingEquipment () inline private
Definition at line 36 of file PortableGasStove.c.
References m_CookingEquipment.
Referenced by CookWithEquipment(), OnSwitchOff(), OnWork(), OnWorkStart(), and RemoveCookingAudioVisuals().
GetCookingTime()
float GetCookingTime () inline private
Definition at line 476 of file Edible_Base.c.
References GetFoodStage().
GetCropsType()
string GetCropsType () inline private
Definition at line 173 of file PlantBase.c.
References m_CropsType.
GetDamageSystemVersionChange() [1/2]
override int GetDamageSystemVersionChange () inline private
Definition at line 1146 of file BaseBuildingBase.c.
Referenced by InventoryItem::OnStoreLoad().
GetDamageSystemVersionChange() [2/2]
override int GetDamageSystemVersionChange () inline private
Definition at line 991 of file TentBase.c.
GetDebugActions()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline private
Definition at line 740 of file Edible_Base.c.
References HasFoodStage(), and SAT_DEBUG_ACTION.
Referenced by ScriptedWidgetEventHandler::ShowActionMenu().
GetDecayDelta()
float GetDecayDelta () inline private
Definition at line 789 of file Edible_Base.c.
References m_DecayDelta.
GetDecayTimer()
float GetDecayTimer () inline private
Definition at line 784 of file Edible_Base.c.
References m_DecayTimer.
GetDeployFinishSoundset()
override string GetDeployFinishSoundset () inline private
Definition at line 127 of file KitBase.c.
Referenced by InventoryItem::PlayDeployFinishSound().
GetDeploySoundset() [1/3]
override string GetDeploySoundset () inline private
Definition at line 437 of file BarbedWire.c.
Referenced by InventoryItem::PlayDeploySound().
GetDeploySoundset() [2/3]
override string GetDeploySoundset () inline private
Definition at line 116 of file KitBase.c.
GetDeploySoundset() [3/3]
override string GetDeploySoundset () inline private
Definition at line 404 of file Spotlight.c.
GetDisarmRate()
int GetDisarmRate () inline private
Definition at line 11 of file ToolBase.c.
GetDismantleSoundByMaterial()
protected string GetDismantleSoundByMaterial (string part_name) inline private
Definition at line 1117 of file BaseBuildingBase.c.
References GetConstruction(), SOUND_DISMANTLE_METAL, SOUND_DISMANTLE_WIRE, SOUND_DISMANTLE_WOOD_LOG, SOUND_DISMANTLE_WOOD_PLANK, and SOUND_DISMANTLE_WOOD_STAIRS.
GetEfficiency0To1()
float GetEfficiency0To1 () inline private
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 units.
Definition at line 21 of file Battery9V.c.
GetEfficiencyDecayStart()
float GetEfficiencyDecayStart () inline private
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 unit.
Definition at line 27 of file Battery9V.c.
References m_EfficiencyDecayStart.
GetEnergyNeededToCharge()
float GetEnergyNeededToCharge () inline private
Definition at line 35 of file Defibrillator.c.
References CGame::ConfigGetFloat(), GetGame(), and GetType().
Referenced by Defibrillator().
GetFoodAgents()
static int GetFoodAgents (ItemBase item, string classname = "", int food_stage = 0) inline static private
Definition at line 336 of file Edible_Base.c.
References CGame::ConfigGetInt(), and GetGame().
GetFoodDigestibility()
static float GetFoodDigestibility (ItemBase item, string classname = "", int food_stage = 0) inline static private
Definition at line 351 of file Edible_Base.c.
References CGame::ConfigGetInt(), and GetGame().
GetFoodEnergy()
static float GetFoodEnergy (ItemBase item, string classname = "", int food_stage = 0) inline static private
Definition at line 275 of file Edible_Base.c.
References CGame::ConfigGetFloat(), and GetGame().
GetFoodNutritionalIndex()
static float GetFoodNutritionalIndex (ItemBase item, string classname = "", int food_stage = 0) inline static private
Definition at line 305 of file Edible_Base.c.
References CGame::ConfigGetFloat(), and GetGame().
GetFoodStage()
FoodStage GetFoodStage () inline private
Definition at line 229 of file Edible_Base.c.
References m_FoodStage.
GetFoodStageName()
string GetFoodStageName (FoodStageType food_stage_type) inline private
Definition at line 451 of file Edible_Base.c.
References GetFoodStage().
GetFoodStageType()
FoodStageType GetFoodStageType () inline private
Definition at line 374 of file Edible_Base.c.
References GetFoodStage().
GetFoodTotalVolume()
static float GetFoodTotalVolume (ItemBase item, string classname = "", int food_stage = 0) inline static private
Definition at line 259 of file Edible_Base.c.
References CGame::ConfigGetFloat(), and GetGame().
GetFoodToxicity()
static float GetFoodToxicity (ItemBase item, string classname = "", int food_stage = 0) inline static private
Definition at line 321 of file Edible_Base.c.
References CGame::ConfigGetFloat(), and GetGame().
GetFoodWater()
static float GetFoodWater (ItemBase item, string classname = "", int food_stage = 0) inline static private
Definition at line 290 of file Edible_Base.c.
References CGame::ConfigGetFloat(), and GetGame().
GetFuel()
float GetFuel () inline private
Definition at line 315 of file PowerGenerator.c.
References m_FuelToEnergyRatio.
Referenced by AddFuel().
GetGarden()
GardenBase GetGarden () inline private
Definition at line 853 of file PlantBase.c.
References m_GardenBase.
GetGardenSlotsCount()
int GetGardenSlotsCount () inline private
Definition at line 308 of file GardenBase.c.
GetGasCanister()
protected EntityAI GetGasCanister () inline private
Definition at line 110 of file Blowtorch.c.
Referenced by HasEnoughEnergyForRepair(), and OnIgnitedTarget().
GetHideIconMask() [1/2]
override int GetHideIconMask () inline private
Definition at line 80 of file GardenBase.c.
GetHideIconMask() [2/2]
override int GetHideIconMask () inline private
Definition at line 78 of file BaseBuildingBase.c.
GetInfectionChance() [1/2]
override float GetInfectionChance (int system = 0, Param param = null) inline private
Definition at line 59 of file BandageDressing.c.
References m_Cleanness.
Referenced by BleedingSourcesManagerBase::RemoveBleedingSource().
GetInfectionChance() [2/2]
override float GetInfectionChance (int system = 0, Param param = null) inline private
Definition at line 112 of file Rag.c.
References m_Cleanness.
GetInvulnerabilityTypeString() [1/2]
override string GetInvulnerabilityTypeString () inline private
Definition at line 68 of file BaseBuildingBase.c.
Referenced by DeployableContainer_Base().
GetInvulnerabilityTypeString() [2/2]
override string GetInvulnerabilityTypeString () inline private
Definition at line 71 of file TentBase.c.
GetItemVisibility()
float GetItemVisibility () inline private
Definition at line 872 of file InventoryItem.c.
GetKitSpawnPosition()
protected vector GetKitSpawnPosition () inline private
Definition at line 361 of file BaseBuildingBase.c.
References GetPosition.
GetLastDecayStage()
FoodStageType GetLastDecayStage () inline private
Definition at line 794 of file Edible_Base.c.
References m_LastDecayStage.
GetLiquidThroughputCoef()
override float GetLiquidThroughputCoef () inline private
Definition at line 72 of file PowerGenerator.c.
References LIQUID_THROUGHPUT_GENERATOR.
Referenced by ActionExtinguishFireplaceByExtinguisherCB::CreateActionComponent(), ActionExtinguishFireplaceByLiquidCB::CreateActionComponent(), CAContinuousFill::Setup(), CAContinuousFillCoolant::Setup(), CAContinuousFillFuel::Setup(), CAContinuousFillPowerGenerator::Setup(), and CAContinuousQuantityLiquidTransfer::Setup().
GetLoopDeploySoundset() [1/3]
override string GetLoopDeploySoundset () inline private
Definition at line 442 of file BarbedWire.c.
Referenced by PlayDeployLoopSound().
GetLoopDeploySoundset() [2/3]
override string GetLoopDeploySoundset () inline private
Definition at line 121 of file KitBase.c.
GetLoopDeploySoundset() [3/3]
override string GetLoopDeploySoundset () inline private
Definition at line 409 of file Spotlight.c.
GetMaxFuel()
float GetMaxFuel () inline private
Definition at line 321 of file PowerGenerator.c.
References m_FuelTankCapacity.
Referenced by AddFuel(), and OnDebugSpawn().
GetMaxWaterStateVal()
int GetMaxWaterStateVal () inline private
Definition at line 132 of file GardenBase.c.
GetMeleeTargetType()
override int GetMeleeTargetType () inline private
Definition at line 91 of file TentBase.c.
GetNearestSlotIDByState()
int GetNearestSlotIDByState (vector position, int slot_state) inline private
Definition at line 745 of file GardenBase.c.
References vector::Distance(), and GardenBase::GetGardenSlotsCount().
GetNextFoodStageType()
FoodStageType GetNextFoodStageType (CookingMethodType cooking_method) inline private
Definition at line 446 of file Edible_Base.c.
References GetFoodStage().
GetNutritionalProfile()
static NutritionalProfile GetNutritionalProfile (ItemBase item, string classname = "", int food_stage = 0) inline static private
Definition at line 366 of file Edible_Base.c.
References GetFoodAgents(), GetFoodDigestibility(), GetFoodEnergy(), GetFoodNutritionalIndex(), GetFoodTotalVolume(), GetFoodToxicity(), and GetFoodWater().
GetPlaceSoundset() [1/4]
override string GetPlaceSoundset () inline private
Definition at line 429 of file BatteryCharger.c.
Referenced by InventoryItem::PlayPlaceSound().
GetPlaceSoundset() [2/4]
override string GetPlaceSoundset () inline private
Definition at line 130 of file CableReel.c.
GetPlaceSoundset() [3/4]
override string GetPlaceSoundset () inline private
Definition at line 358 of file PowerGenerator.c.
GetPlaceSoundset() [4/4]
override string GetPlaceSoundset () inline private
Definition at line 68 of file Refridgerator.c.
GetPlantState()
int GetPlantState () inline private
Definition at line 762 of file PlantBase.c.
References m_PlantState.
Referenced by IsDry(), IsGrowing(), IsMature(), and IsSpoiled().
GetPlantStateIndex()
int GetPlantStateIndex () inline private
Definition at line 767 of file PlantBase.c.
References m_PlantStateIndex.
GetSlot()
Slot GetSlot () inline private
Definition at line 848 of file PlantBase.c.
References m_Slot.
Referenced by GetWater(), GetWaterMax(), OnStoreSave(), InventoryItem::SplitIntoStackMaxToInventoryLocationEx(), and SplitItemUtils::TakeOrSplitToInventoryLocation().
GetSlotByIndex()
Slot GetSlotByIndex (int index) inline private
Definition at line 838 of file GardenBase.c.
GetSlotBySelection()
Slot GetSlotBySelection (string selection_component) inline private
Definition at line 666 of file GardenBase.c.
GetSlotIndexByAttachmentSlot()
int GetSlotIndexByAttachmentSlot (string att_slot) inline private
Definition at line 713 of file GardenBase.c.
References string::Length(), string::Substring(), and string::ToInt().
GetSlotIndexByPlant()
int GetSlotIndexByPlant (Object plant) inline private
Definition at line 727 of file GardenBase.c.
GetSlotIndexBySelection()
int GetSlotIndexBySelection (string selection_component) inline private
Definition at line 681 of file GardenBase.c.
References string::IndexOf(), string::Length(), string::Substring(), string::ToInt(), and string::ToLower().
GetSlotLockedState()
protected bool GetSlotLockedState () inline private
Definition at line 61 of file BarbedWire.c.
References InventoryLocation::GetSlot().
Referenced by AfterStoreLoad(), and IsMounted().
GetSlotPosition()
vector GetSlotPosition (int index) inline private
Definition at line 770 of file GardenBase.c.
References GetSelectionPositionMS(), ModelToWorld(), and ToStringLen().
GetSlots()
array< ref Slot > GetSlots () inline private
Definition at line 833 of file GardenBase.c.
GetSlotWateredState()
int GetSlotWateredState () inline private
Definition at line 843 of file GardenBase.c.
GetSoundClose()
string GetSoundClose () inline private
Definition at line 820 of file TentBase.c.
GetSoundCloseWindow()
string GetSoundCloseWindow () inline private
Definition at line 824 of file TentBase.c.
GetSoundOpen()
string GetSoundOpen () inline private
Definition at line 818 of file TentBase.c.
GetSoundOpenWindow()
string GetSoundOpenWindow () inline private
Definition at line 822 of file TentBase.c.
GetSprayQuantity()
float GetSprayQuantity () inline private
Definition at line 814 of file PlantBase.c.
References m_SprayQuantity.
GetSprayUsage()
float GetSprayUsage () inline private
Definition at line 819 of file PlantBase.c.
References m_SprayUsage.
GetStashedItem()
ItemBase GetStashedItem () inline private
Definition at line 13 of file UndergroundStash.c.
References GetItem().
Referenced by OnFinishProgressServer().
GetState()
int GetState () inline private
Definition at line 501 of file TentBase.c.
References m_State.
Referenced by PrintSlots().
GetStateLocal()
int GetStateLocal () inline private
Definition at line 506 of file TentBase.c.
GetTemperatureValue()
float GetTemperatureValue (PlayerBase player) inline private
Definition at line 3 of file Thermometer.c.
References PlayerConstants::HIGH_TEMPERATURE_H, PlayerConstants::HIGH_TEMPERATURE_L, PlayerConstants::NORMAL_TEMPERATURE_H, PlayerConstants::NORMAL_TEMPERATURE_L, Math::RandomFloatInclusive(), and Math::Round().
GetTimeNeededToCharge()
float GetTimeNeededToCharge () inline private
Definition at line 29 of file Defibrillator.c.
References CGame::ConfigGetFloat(), GetGame(), and GetType().
GetViewIndex() [1/3]
override int GetViewIndex () inline private
Definition at line 90 of file Flag_Base.c.
References InventoryLocation::GetType(), and MemoryPointExists().
GetViewIndex() [2/3]
override int GetViewIndex () inline private
Definition at line 432 of file Spotlight.c.
References MemoryPointExists().
GetViewIndex() [3/3]
override int GetViewIndex () inline private
Definition at line 429 of file TentBase.c.
References GetState(), InventoryLocation::GetType(), and MemoryPointExists().
GetVoiceEffect()
int GetVoiceEffect () inline private
The voice effect this item uses, default is 0 (none)
Definition at line 982 of file InventoryItem.c.
GetWater()
float GetWater () inline private
Definition at line 772 of file PlantBase.c.
References GetSlot().
GetWaterMax()
float GetWaterMax () inline private
Definition at line 780 of file PlantBase.c.
References GetSlot().
GetWrittenNoteData()
override WrittenNoteData GetWrittenNoteData () inline private
Definition at line 30 of file Paper.c.
References m_NoteContents.
Referenced by InventoryItem::OnRPC(), ActionWritePaper::OnStartClient(), ActionWritePaper::OnStartServer(), ActionReadPaperCB::OnStateChange(), and ActionWritePaperCB::OnStateChange().
GreenLightOff()
void GreenLightOff () inline private
Definition at line 320 of file BatteryCharger.c.
Referenced by UpdateStatusLights().
GreenLightOn()
void GreenLightOn () inline private
Definition at line 303 of file BatteryCharger.c.
Referenced by UpdateStatusLights().
GrowthTimerTick()
void GrowthTimerTick () inline private
Definition at line 522 of file PlantBase.c.
References CALL_CATEGORY_SYSTEM, GetGame(), int, IsGrowing(), IsMature(), CGame::IsServer(), Math::RandomInt(), SetPlantState(), SetSpoiled(), and UpdatePlant().
HandleCamoNetAttachment()
void HandleCamoNetAttachment (bool hide) inline private
Definition at line 809 of file TentBase.c.
HandleOpeningsPhysics()
void HandleOpeningsPhysics () inline private
Definition at line 955 of file TentBase.c.
References AddProxyPhysics(), component, GetHealthLevel(), ToggleAnimations::GetOpeningBit(), GetState(), ToggleAnimations::GetToggleOff(), ToggleAnimations::GetToggleOn(), RemoveProxyPhysics(), and GameConstants::STATE_RUINED.
HandleOpeningsVisuals()
void HandleOpeningsVisuals () inline private
Definition at line 922 of file TentBase.c.
References component, ToggleAnimations::GetOpeningBit(), ToggleAnimations::GetToggleOff(), and ToggleAnimations::GetToggleOn().
HandleVoiceEffect()
void HandleVoiceEffect (bool enable, PlayerBase player) inline private
Definition at line 974 of file InventoryItem.c.
Harvest()
void Harvest (PlayerBase player) inline private
Definition at line 733 of file PlantBase.c.
References ECE_PLACE_ON_SURFACE, GetGame(), IsSpoiled(), m_CropsCount, and UpdatePlant().
HasAttachmentsBesidesBase()
bool HasAttachmentsBesidesBase () inline private
Definition at line 898 of file BaseBuildingBase.c.
References HasBase().
HasBase()
bool HasBase () inline private
Definition at line 320 of file BaseBuildingBase.c.
References m_HasBase.
HasClutterCutter()
bool HasClutterCutter () inline private
Definition at line 857 of file TentBase.c.
HasCrops()
bool HasCrops () inline private
Definition at line 907 of file PlantBase.c.
References m_HasCrops.
Referenced by UpdatePlant().
HasEnoughEnergyForRepair()
bool HasEnoughEnergyForRepair (float pTime) inline private
Definition at line 120 of file Blowtorch.c.
References ComponentEnergyManager::GetEnergy(), and GetGasCanister().
HasFlammableMaterial() [1/5]
override bool HasFlammableMaterial () inline private
Definition at line 6 of file BandageDressing.c.
Referenced by SetIgnitingAnimation().
HasFlammableMaterial() [2/5]
override bool HasFlammableMaterial () inline private
Definition at line 6 of file Bark_ColorBase.c.
HasFlammableMaterial() [3/5]
override bool HasFlammableMaterial () inline private
Definition at line 6 of file GiftWrapPaper.c.
HasFlammableMaterial() [4/5]
override bool HasFlammableMaterial () inline private
Definition at line 38 of file Paper.c.
HasFlammableMaterial() [5/5]
override bool HasFlammableMaterial () inline private
Definition at line 37 of file Rag.c.
HasProperDistance()
bool HasProperDistance (string selection, PlayerBase player) inline private
Definition at line 967 of file BaseBuildingBase.c.
HasProxyParts() [1/3]
override bool HasProxyParts () inline private
Definition at line 75 of file GardenBase.c.
HasProxyParts() [2/3]
override bool HasProxyParts () inline private
Definition at line 22 of file KitBase.c.
HasProxyParts() [3/3]
override bool HasProxyParts () inline private
Definition at line 76 of file TentBase.c.
HasSparkplug()
bool HasSparkplug () inline private
Definition at line 327 of file PowerGenerator.c.
References InventorySlots::GetSlotIdFromString().
HideAllAnimationsAndProxyPhysics()
void HideAllAnimationsAndProxyPhysics (bool hide_animations = true, bool hide_physics = true) inline private
Definition at line 275 of file TentBase.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), ConfigIsExisting(), GetGame(), GetType(), RemoveProxyPhysics(), and string::ToLower().
HideAttachedClipsStates()
void HideAttachedClipsStates () inline private
Definition at line 286 of file BatteryCharger.c.
References ATTACHED_CLIPS_STATES_COUNT.
Referenced by OnInventoryEnter(), OnInventoryExit(), OnOwnSocketReleased(), and OnOwnSocketTaken().
IgnoreOutOfReachCondition()
override bool IgnoreOutOfReachCondition () inline private
Definition at line 538 of file BaseBuildingBase.c.
InfestationTimerTick()
void InfestationTimerTick () inline private
Definition at line 575 of file PlantBase.c.
References ChangeInfestation(), and Math::RandomFloat01().
Init()
void Init (GardenBase garden_base, float fertility, float harvesting_efficiency, float water) inline private
Definition at line 84 of file PlantBase.c.
References CALL_CATEGORY_SYSTEM, Math::Ceil(), CheckWater(), WeatherPhenomenon::GetActual(), GetGame(), Weather::GetRain(), CGame::GetWeather(), int, m_FullMaturityTime, NeedsWater(), Math::RandomInt(), SetPlantState(), and SPOIL_AFTER_MATURITY_TIME.
InitBaseState()
void InitBaseState () inline private
Definition at line 660 of file BaseBuildingBase.c.
References bsbDebugPrint(), GetConstruction(), GetDebugName(), InitVisuals(), and UpdateNavmesh().
InitializeSlots()
void InitializeSlots () inline private
Definition at line 101 of file GardenBase.c.
References GardenBase::GetGardenSlotsCount(), InventorySlots::GetSlotIdFromString(), and name.
InitItemVariables()
override void InitItemVariables () inline private
Definition at line 3 of file Matchbox.c.
References can_this_be_combined.
Referenced by InventoryItem::ItemBase().
InitVisuals()
void InitVisuals () inline private
Definition at line 669 of file BaseBuildingBase.c.
References ANIMATION_DEPLOYED, bsbDebugPrint(), GetConstruction(), GetDebugName(), and HasBase().
IsActive()
bool IsActive () inline private
Definition at line 150 of file TrapSpawnBase.c.
References m_IsActive.
IsAttachmentSlotLocked() [1/2]
protected bool IsAttachmentSlotLocked (EntityAI attachment) inline private
Definition at line 832 of file BaseBuildingBase.c.
References InventoryLocation::GetSlot().
IsAttachmentSlotLocked() [2/2]
protected bool IsAttachmentSlotLocked (string slot_name) inline private
Definition at line 845 of file BaseBuildingBase.c.
References InventorySlots::GetSlotIdFromString().
IsBasebuildingKit()
override bool IsBasebuildingKit () inline private
Definition at line 17 of file KitBase.c.
Referenced by ActionDeployBase::DropDuringPlacing(), Hologram::GetProjectionName(), Hologram::IsFenceOrWatchtowerKit(), ActionDeployBase::MoveEntityToFinalPosition(), and OnEndServer().
IsBloodContainer()
override bool IsBloodContainer () inline private
Definition at line 10 of file BloodContainerBase.c.
Referenced by UIScriptedMenu::UpdateItemInfoLiquidType().
IsCharged()
bool IsCharged () inline private
Definition at line 111 of file Defibrillator.c.
References m_IsCharged.
IsClothing()
override bool IsClothing () inline private
Definition at line 867 of file InventoryItem.c.
Referenced by InventoryItem::EEHitBy(), and CAContinuousEmpty::Setup().
IsCorpse()
override bool IsCorpse () inline private
Definition at line 240 of file Edible_Base.c.
IsCorrectFertilizer()
bool IsCorrectFertilizer (ItemBase item, string selection_component) inline private
Definition at line 496 of file GardenBase.c.
IsDeployable() [1/5]
override bool IsDeployable () inline private
Definition at line 330 of file BaseBuildingBase.c.
Referenced by Hologram::DoesHaveProjection(), and SetupAnimation().
IsDeployable() [2/5]
override bool IsDeployable () inline private
Definition at line 424 of file BatteryCharger.c.
IsDeployable() [3/5]
override bool IsDeployable () inline private
Definition at line 106 of file KitBase.c.
IsDeployable() [4/5]
override bool IsDeployable () inline private
Definition at line 399 of file Spotlight.c.
IsDeployable() [5/5]
override bool IsDeployable () inline private
Definition at line 875 of file TentBase.c.
IsDeployed()
bool IsDeployed () inline private
Definition at line 155 of file TrapSpawnBase.c.
IsDry()
bool IsDry () inline private
Definition at line 858 of file PlantBase.c.
References GetPlantState().
Referenced by NeedsWater().
IsElectricAppliance() [1/4]
override bool IsElectricAppliance () inline private
Definition at line 45 of file BatteryCharger.c.
Referenced by ActionPlugTargetIntoThis::ActionCondition().
IsElectricAppliance() [2/4]
override bool IsElectricAppliance () inline private
Definition at line 15 of file CableReel.c.
IsElectricAppliance() [3/4]
override bool IsElectricAppliance () inline private
Definition at line 5 of file Refridgerator.c.
IsElectricAppliance() [4/4]
override bool IsElectricAppliance () inline private
Definition at line 58 of file Spotlight.c.
IsFacingCamera()
bool IsFacingCamera (string selection) inline private
Definition at line 955 of file BaseBuildingBase.c.
IsFacingPlayer()
override bool IsFacingPlayer (PlayerBase player, string selection) inline private
Definition at line 938 of file BaseBuildingBase.c.
IsFolded()
bool IsFolded () inline private
Definition at line 335 of file Spotlight.c.
References m_IsFolded.
Referenced by UpdateAllSelections().
IsFoodBaked()
bool IsFoodBaked () inline private
Definition at line 390 of file Edible_Base.c.
References GetFoodStage().
IsFoodBoiled()
bool IsFoodBoiled () inline private
Definition at line 400 of file Edible_Base.c.
References GetFoodStage().
IsFoodBurned()
bool IsFoodBurned () inline private
Definition at line 420 of file Edible_Base.c.
References GetFoodStage().
IsFoodDried()
bool IsFoodDried () inline private
Definition at line 410 of file Edible_Base.c.
References GetFoodStage().
IsFoodRaw()
bool IsFoodRaw () inline private
Definition at line 380 of file Edible_Base.c.
References GetFoodStage().
IsFoodRotten()
bool IsFoodRotten () inline private
Definition at line 430 of file Edible_Base.c.
References GetFoodStage().
IsFruit()
override bool IsFruit () inline private
Definition at line 245 of file Edible_Base.c.
IsGasMask()
bool IsGasMask () inline private
Definition at line 987 of file InventoryItem.c.
IsGrowing()
bool IsGrowing () inline private
Definition at line 870 of file PlantBase.c.
References GetPlantState().
Referenced by GrowthTimerTick().
IsIgnited() [1/2]
override bool IsIgnited () inline private
Definition at line 76 of file Blowtorch.c.
Referenced by ActionCondition(), and CreateActionComponent().
IsIgnited() [2/2]
override bool IsIgnited () inline private
Definition at line 328 of file PortableGasStove.c.
IsIgnoredByConstruction() [1/2]
override bool IsIgnoredByConstruction () inline private
Definition at line 1078 of file BaseBuildingBase.c.
IsIgnoredByConstruction() [2/2]
override bool IsIgnoredByConstruction () inline private
Definition at line 546 of file TentBase.c.
IsInventoryVisible()
override bool IsInventoryVisible () inline private
Definition at line 54 of file UndergroundStash.c.
IsItemTent()
override bool IsItemTent () inline private
Definition at line 81 of file TentBase.c.
Referenced by InventoryItem::EEHitBy().
IsManipulatedEntrance()
bool IsManipulatedEntrance () inline private
Definition at line 726 of file TentBase.c.
IsManipulatedWindow()
bool IsManipulatedWindow () inline private
Definition at line 731 of file TentBase.c.
IsMature()
bool IsMature () inline private
Definition at line 883 of file PlantBase.c.
References GetPlantState().
Referenced by CheckWater(), and GrowthTimerTick().
IsMeat()
override bool IsMeat () inline private
Definition at line 235 of file Edible_Base.c.
IsMounted()
bool IsMounted () inline private
Definition at line 56 of file BarbedWire.c.
References GetSlotLockedState().
IsMushroom()
override bool IsMushroom () inline private
Definition at line 250 of file Edible_Base.c.
IsObstructingVoice()
bool IsObstructingVoice () inline private
Returns if this entity obsructs player's voice.
Definition at line 955 of file InventoryItem.c.
IsOpened()
bool IsOpened () inline private
Definition at line 335 of file BaseBuildingBase.c.
IsPartBuildInSyncData()
bool IsPartBuildInSyncData (int part_id) inline private
Definition at line 171 of file BaseBuildingBase.c.
References m_SyncParts01, m_SyncParts02, and m_SyncParts03.
IsPeltBase()
override bool IsPeltBase () inline private
Definition at line 3 of file Pelt_Base.c.
IsPlaceable()
bool IsPlaceable () inline private
Definition at line 530 of file TrapSpawnBase.c.
References vector::DistanceSq(), GetGame(), and TrapSpawnBase::IsPlaceableAtPosition().
IsPlaceableAtPosition()
bool IsPlaceableAtPosition (vector position) inline private
Definition at line 191 of file TrapSpawnBase.c.
References GetGame(), CGame::IsSurfaceDigable(), and CGame::SurfaceGetType3D().
IsPlayerInside()
override bool IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 943 of file BaseBuildingBase.c.
Referenced by InventoryItem::CanObstruct().
IsSpoiled()
bool IsSpoiled () inline private
Definition at line 895 of file PlantBase.c.
References GetPlantState().
Referenced by Harvest(), and SetSpoiled().
IsSurfaceWater()
bool IsSurfaceWater (vector position) inline private
Definition at line 444 of file TrapSpawnBase.c.
References Surface::AllowedWaterSurface(), GetGame(), and CGame::SurfaceGetType3D().
IsTakeable()
override bool IsTakeable () inline private
Definition at line 186 of file TrapSpawnBase.c.
Referenced by ActionPackGift::ActionCondition(), ActionCondition(), ActionRepositionPluggedItem::ActionCondition(), ActionTakeHybridAttachment::ActionCondition(), ActionTakeHybridAttachmentToHands::ActionCondition(), ActionTakeItem::ActionCondition(), ActionTakeItemToHands::ActionCondition(), VicinitySlotsContainer::DoubleClick(), VicinityItemManager::ExcludeFromContainer_Phase2(), VicinityItemManager::ExcludeFromContainer_Phase3(), ScriptedWidgetEventHandler::GetTarget(), VicinityObjects::GetVicinityObjects(), Container::SelectItem(), SlotsContainer::SelectItem(), and VicinitySlotsContainer::TransferItem().
IsThisIgnitionSuccessful() [1/5]
override bool IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 32 of file BandageDressing.c.
Referenced by OnFinishProgressServer().
IsThisIgnitionSuccessful() [2/5]
override bool IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 32 of file Bark_ColorBase.c.
IsThisIgnitionSuccessful() [3/5]
override bool IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 32 of file GiftWrapPaper.c.
IsThisIgnitionSuccessful() [4/5]
override bool IsThisIgnitionSuccessful (EntityAI item_source = null) inline private
Definition at line 60 of file Paper.c.
IsThisIgnitionSuccessful() [5/5]
override bool IsThisIgnitionSuccessful (EntityAI item_source = null) inline private
Definition at line 67 of file Rag.c.
KitBase()
void KitBase () inline private
Definition at line 6 of file KitBase.c.
LockAttachmentSlot()
protected void LockAttachmentSlot (bool lock_state) inline private
Definition at line 102 of file BarbedWire.c.
References InventoryLocation::GetSlot().
Referenced by SetMountedState().
MakeSoundsOnClient()
void MakeSoundsOnClient (bool soundstate) inline private
Definition at line 139 of file Edible_Base.c.
References m_MakeCookingSounds, and Synchronize().
ManipulateEntrance()
void ManipulateEntrance () inline private
Definition at line 716 of file TentBase.c.
ManipulateWindow()
void ManipulateWindow () inline private
Definition at line 721 of file TentBase.c.
MetalWire()
void MetalWire () inline private
Definition at line 8 of file MetalWire.c.
Referenced by VehicleBattery::CanPutInCargo(), VehicleBattery::CanPutIntoHands(), VehicleBattery::OnInventoryEnter(), and VehicleBattery::OnMovedInsideCargo().
MustBeBuiltFromOutside()
bool MustBeBuiltFromOutside () inline private
Some buildings can only be built from outside.
Definition at line 949 of file BaseBuildingBase.c.
MutePlayer()
void MutePlayer (PlayerBase player, bool state) inline private
This items has effect on player's voice.
Definition at line 962 of file InventoryItem.c.
References GetGame(), GetPlayer(), and CGame::SetVoiceEffect().
NeedsFertilization()
bool NeedsFertilization (string selection_component) inline private
Definition at line 513 of file GardenBase.c.
NeedsSpraying()
bool NeedsSpraying () inline private
Definition at line 802 of file PlantBase.c.
Referenced by SprayPlant(), and StopInfestation().
NeedsWater()
bool NeedsWater () inline private
Definition at line 788 of file PlantBase.c.
References IsDry(), and m_Slot.
Referenced by CheckWater(), and Init().
OnAction()
override bool OnAction (int action_id, Man player, ParamsReadContext ctx) inline private
Definition at line 751 of file Edible_Base.c.
References ChangeFoodStage(), GetFoodStageType(), and GetGame().
OnCombine() [1/2]
override void OnCombine (ItemBase other_item) inline private
Definition at line 71 of file BandageDressing.c.
References m_Cleanness, and SetCleanness().
Referenced by InventoryItem::CombineItems().
OnCombine() [2/2]
override void OnCombine (ItemBase other_item) inline private
Definition at line 120 of file Rag.c.
References m_Cleanness, and SetCleanness().
OnConsume()
void OnConsume (float amount, PlayerBase consumer) private
OnDebugSpawn() [1/5]
override void OnDebugSpawn () inline private
Definition at line 1175 of file BaseBuildingBase.c.
References FullyBuild().
Referenced by InventoryItem::OnAction().
OnDebugSpawn() [2/5]
override void OnDebugSpawn () inline private
Definition at line 134 of file Blowtorch.c.
OnDebugSpawn() [3/5]
override void OnDebugSpawn () inline private
Definition at line 85 of file Flashlight.c.
OnDebugSpawn() [4/5]
override void OnDebugSpawn () inline private
Definition at line 348 of file PortableGasStove.c.
References Class::CastTo(), and Vector().
OnDebugSpawn() [5/5]
override void OnDebugSpawn () inline private
Definition at line 375 of file PowerGenerator.c.
References Class::CastTo(), GetMaxFuel(), and SetFuel().
OnDebugSpawnBuildExcludes()
array< string > OnDebugSpawnBuildExcludes () inline private
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
Definition at line 1170 of file BaseBuildingBase.c.
OnEndPlacement()
override void OnEndPlacement () inline private
Definition at line 94 of file KitBase.c.
References SoundSynchRemote().
Referenced by InventoryItem::SetIsBeingPlaced().
OnEnergyAdded()
override void OnEnergyAdded () inline private
Definition at line 50 of file Battery9V.c.
References GetGame(), and Math::Round().
OnEnergyConsumed()
override void OnEnergyConsumed () inline private
Definition at line 33 of file Battery9V.c.
References GetGame(), and Math::Round().
OnIgnitedTarget() [1/8]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 23 of file BandageDressing.c.
Referenced by OnFinishProgressServer().
OnIgnitedTarget() [2/8]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 23 of file Bark_ColorBase.c.
OnIgnitedTarget() [3/8]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 81 of file Blowtorch.c.
References ComponentEnergyManager::AddEnergy(), UATimeSpent::FIREPLACE_IGNITE, GetGame(), and GetGasCanister().
OnIgnitedTarget() [4/8]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 23 of file GiftWrapPaper.c.
OnIgnitedTarget() [5/8]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 9 of file HandDrillKit.c.
References DecreaseHealth(), and GetGame().
OnIgnitedTarget() [6/8]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 17 of file Matchbox.c.
References AddQuantity(), and GetGame().
OnIgnitedTarget() [7/8]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 53 of file Paper.c.
OnIgnitedTarget() [8/8]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 11 of file PetrolLighter.c.
References AddQuantity(), and GetGame().
OnIgnitedTargetFailed() [1/3]
override void OnIgnitedTargetFailed (EntityAI target_item) inline private
Definition at line 17 of file HandDrillKit.c.
References DecreaseHealth(), and GetGame().
Referenced by OnFinishProgressServer().
OnIgnitedTargetFailed() [2/3]
override void OnIgnitedTargetFailed (EntityAI target_item) inline private
Definition at line 25 of file Matchbox.c.
References AddQuantity(), and GetGame().
OnIgnitedTargetFailed() [3/3]
override void OnIgnitedTargetFailed (EntityAI target_item) inline private
Definition at line 19 of file PetrolLighter.c.
References AddQuantity(), and GetGame().
OnIgnitedThis() [1/5]
override void OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 27 of file BandageDressing.c.
Referenced by OnFinishProgressServer().
OnIgnitedThis() [2/5]
override void OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 27 of file Bark_ColorBase.c.
OnIgnitedThis() [3/5]
override void OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 27 of file GiftWrapPaper.c.
OnIgnitedThis() [4/5]
override void OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 55 of file Paper.c.
OnIgnitedThis() [5/5]
override void OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 62 of file Rag.c.
OnInitEnergy() [1/3]
override void OnInitEnergy () inline private
Definition at line 127 of file PowerGenerator.c.
References CGame::ConfigGetFloat(), GetGame(), GetType(), m_FuelTankCapacity, and UpdateFuelMeter().
OnInitEnergy() [2/3]
override void OnInitEnergy () inline private
Definition at line 10 of file Refridgerator.c.
OnInitEnergy() [3/3]
override void OnInitEnergy () inline private
Definition at line 63 of file Spotlight.c.
References Fold(), Unfold(), and UpdateAllSelections().
OnInventoryEnter() [1/4]
override void OnInventoryEnter (Man player) inline private
Definition at line 246 of file BarbedWire.c.
References DestroyDamageTrigger().
Referenced by InventoryItem::OnItemLocationChanged().
OnInventoryEnter() [2/4]
override void OnInventoryEnter (Man player) inline private
Definition at line 356 of file BatteryCharger.c.
References HideAttachedClipsStates().
OnInventoryEnter() [3/4]
override void OnInventoryEnter (Man player) inline private
Definition at line 66 of file CableReel.c.
References Class::CastTo().
OnInventoryEnter() [4/4]
override void OnInventoryEnter (Man player) inline private
Definition at line 72 of file MetalWire.c.
References Class::CastTo().
OnInventoryExit() [1/2]
override void OnInventoryExit (Man player) inline private
Definition at line 347 of file BatteryCharger.c.
References HideAttachedClipsStates().
Referenced by InventoryItem::EEDelete(), and InventoryItem::OnItemLocationChanged().
OnInventoryExit() [2/2]
override void OnInventoryExit (Man player) inline private
Definition at line 62 of file Flashlight.c.
References SetOrientation(), and Vector().
OnIsCharged()
void OnIsCharged () inline private
Definition at line 69 of file Defibrillator.c.
References GetGame(), SEffectManager::PlaySoundOnObject(), and EffectSound::SoundStop().
OnIsPlugged() [1/3]
override void OnIsPlugged (EntityAI source_device) inline private
Definition at line 234 of file BarbedWire.c.
References SoundCut().
OnIsPlugged() [2/3]
override void OnIsPlugged (EntityAI source_device) inline private
Definition at line 97 of file MetalWire.c.
References UpdateAllSelections().
OnIsPlugged() [3/3]
override void OnIsPlugged (EntityAI source_device) inline private
Definition at line 159 of file Spotlight.c.
References Unfold(), and UpdateAllSelections().
OnIsUnplugged() [1/3]
override void OnIsUnplugged (EntityAI last_energy_source) inline private
Definition at line 239 of file BarbedWire.c.
References DestroyDamageTrigger(), and SoundCut().
OnIsUnplugged() [2/3]
override void OnIsUnplugged (EntityAI last_energy_source) inline private
Definition at line 103 of file MetalWire.c.
References UpdateAllSelections().
OnIsUnplugged() [3/3]
override void OnIsUnplugged (EntityAI last_energy_source) inline private
Definition at line 241 of file Spotlight.c.
References Fold(), and UpdateAllSelections().
OnItemLocationChanged() [1/6]
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 400 of file BarbedWire.c.
References DestroyDamageTrigger().
OnItemLocationChanged() [2/6]
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 86 of file KitBase.c.
References UpdatePhysics().
OnItemLocationChanged() [3/6]
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 202 of file PowerGenerator.c.
References UpdateFuelMeter().
OnItemLocationChanged() [4/6]
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 133 of file Spotlight.c.
References Fold(), IsBeingPlaced(), m_Light, and Unfold().
OnItemLocationChanged() [5/6]
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 154 of file TentBase.c.
OnItemLocationChanged() [6/6]
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 418 of file TrapSpawnBase.c.
References GetGame(), SetActive(), and SetInactive().
OnOwnSocketReleased() [1/2]
override void OnOwnSocketReleased (EntityAI device) inline private
Definition at line 239 of file BatteryCharger.c.
References HideAttachedClipsStates().
OnOwnSocketReleased() [2/2]
override void OnOwnSocketReleased (EntityAI device) inline private
Definition at line 116 of file MetalWire.c.
References UpdateAllSelections().
OnOwnSocketTaken() [1/2]
override void OnOwnSocketTaken (EntityAI device) inline private
Definition at line 219 of file BatteryCharger.c.
References HideAttachedClipsStates().
OnOwnSocketTaken() [2/2]
override void OnOwnSocketTaken (EntityAI device) inline private
Definition at line 110 of file MetalWire.c.
References UpdateAllSelections().
OnPartBuiltClient()
void OnPartBuiltClient (string part_name, int action_id) inline private
Definition at line 577 of file BaseBuildingBase.c.
References SoundBuildStart().
OnPartBuiltServer()
void OnPartBuiltServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 545 of file BaseBuildingBase.c.
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CreateConstructionKit(), CGame::GetCallQueue(), GetConstruction(), GetGame(), ConstructionPart::GetId(), ConstructionPart::IsBase(), RegisterActionForSync(), RegisterPartForSync(), ResetActionSyncData(), SetBaseState(), SetPartFromSyncData(), SynchronizeBaseState(), and BaseBuildingBase::UpdateVisuals().
OnPartDestroyedClient()
void OnPartDestroyedClient (string part_name, int action_id) inline private
Definition at line 653 of file BaseBuildingBase.c.
References SoundDestroyStart().
OnPartDestroyedServer()
void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false) inline private
Definition at line 622 of file BaseBuildingBase.c.
References bsbDebugPrint(), CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), DestroyConstruction(), CGame::GetCallQueue(), GetConstruction(), GetDebugName(), GetGame(), ConstructionPart::GetId(), ConstructionPart::IsBase(), RegisterActionForSync(), ResetActionSyncData(), SetPartFromSyncData(), SynchronizeBaseState(), UnregisterPartForSync(), and BaseBuildingBase::UpdateVisuals().
OnPartDismantledClient()
void OnPartDismantledClient (string part_name, int action_id) inline private
Definition at line 615 of file BaseBuildingBase.c.
References SoundDismantleStart().
OnPartDismantledServer()
void OnPartDismantledServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 584 of file BaseBuildingBase.c.
References bsbDebugPrint(), CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), DestroyConstruction(), CGame::GetCallQueue(), GetConstruction(), GetDebugName(), GetGame(), ConstructionPart::GetId(), ConstructionPart::IsBase(), RegisterActionForSync(), ResetActionSyncData(), SetPartFromSyncData(), SynchronizeBaseState(), UnregisterPartForSync(), and BaseBuildingBase::UpdateVisuals().
OnPlacementCancelled() [1/2]
override void OnPlacementCancelled (Man player) inline private
Definition at line 100 of file KitBase.c.
OnPlacementCancelled() [2/2]
override void OnPlacementCancelled (Man player) inline private
Definition at line 392 of file Spotlight.c.
References Fold().
OnPlacementComplete() [1/8]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 415 of file BarbedWire.c.
References CreateDamageTrigger(), CreateElectrifiedDamageTrigger(), GetGame(), and SetIsDeploySound().
OnPlacementComplete() [2/8]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 417 of file BatteryCharger.c.
References SetIsPlaceSound().
OnPlacementComplete() [3/8]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 123 of file CableReel.c.
References SetIsPlaceSound().
OnPlacementComplete() [4/8]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 351 of file PowerGenerator.c.
References SetIsPlaceSound().
OnPlacementComplete() [5/8]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 61 of file Refridgerator.c.
References SetIsPlaceSound().
OnPlacementComplete() [6/8]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 379 of file Spotlight.c.
References GetGame(), SetIsDeploySound(), and Unfold().
OnPlacementComplete() [7/8]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 880 of file TentBase.c.
References GetGame(), and SetIsDeploySound().
OnPlacementComplete() [8/8]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 480 of file TrapSpawnBase.c.
References GetGame(), SetActive(), SetIsDeploySound(), and SetupTrapPlayer().
OnPlacementStarted() [1/3]
override void OnPlacementStarted (Man player) inline private
Definition at line 392 of file BatteryCharger.c.
References GetGame(), SEL_CLIPS_DETACHED, SEL_CORD_FOLDED, and SEL_CORD_PLUGGED.
OnPlacementStarted() [2/3]
override void OnPlacementStarted (Man player) inline private
Definition at line 105 of file CableReel.c.
References GetGame(), and SEL_CORD_PLUGGED.
OnPlacementStarted() [3/3]
override void OnPlacementStarted (Man player) inline private
Definition at line 356 of file Spotlight.c.
References GetGame(), and SEL_CORD_PLUGGED_F.
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 16 of file ToolBase.c.
OnSetSlotLock()
protected void OnSetSlotLock (int slotId, bool locked, bool was_locked) inline private
Definition at line 528 of file BaseBuildingBase.c.
References bsbDebugPrint(), GetDebugName(), InventorySlots::GetSlotName(), UpdateAttachmentPhysics(), and UpdateAttachmentVisuals().
OnStoreLoad() [1/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 147 of file GardenBase.c.
References GardenBase::GetGardenSlotsCount(), and Serializer::Read().
OnStoreLoad() [2/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 125 of file PlantBase.c.
References OnStoreLoadCustom(), Serializer::Read(), and SetSlot().
OnStoreLoad() [3/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 178 of file BarbedWire.c.
References Serializer::Read().
OnStoreLoad() [4/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 397 of file BaseBuildingBase.c.
References m_HasBase, m_SyncParts01, m_SyncParts02, m_SyncParts03, and Serializer::Read().
OnStoreLoad() [5/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 33 of file BloodContainerBase.c.
References Serializer::Read().
OnStoreLoad() [6/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 192 of file Edible_Base.c.
References GetFoodStage(), m_DecayTimer, m_LastDecayStage, OnStoreLoad(), and Serializer::Read().
OnStoreLoad() [7/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 37 of file Flag_Base.c.
OnStoreLoad() [8/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 12 of file Paper.c.
References Serializer::Read().
OnStoreLoad() [9/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 295 of file Spotlight.c.
References Fold(), Serializer::Read(), and Unfold().
OnStoreLoad() [10/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 104 of file TentBase.c.
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, TentBase::GetClutterCutter(), GetGame(), GetOrientation(), GetPosition, TentBase::HasClutterCutter(), m_ClutterCutter, m_State, Print(), and Serializer::Read().
OnStoreLoad() [11/11]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 97 of file TrapSpawnBase.c.
References Serializer::Read(), SetActive(), and StartActivate().
OnStoreLoadCustom()
bool OnStoreLoadCustom (ParamsReadContext ctx, int version) inline private
Definition at line 179 of file PlantBase.c.
References CALL_CATEGORY_SYSTEM, GetGame(), Serializer::Read(), and UpdatePlant().
Referenced by OnStoreLoad().
OnStoreSave() [1/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 225 of file GardenBase.c.
References GardenBase::GetGardenSlotsCount(), and Serializer::Write().
OnStoreSave() [2/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 151 of file PlantBase.c.
References GetGame(), GetSlot(), CGame::ObjectDelete(), OnStoreSaveCustom(), Print(), and Serializer::Write().
OnStoreSave() [3/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 173 of file BarbedWire.c.
OnStoreSave() [4/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 385 of file BaseBuildingBase.c.
References m_HasBase, m_SyncParts01, m_SyncParts02, m_SyncParts03, and Serializer::Write().
OnStoreSave() [5/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 26 of file BloodContainerBase.c.
References Serializer::Write().
OnStoreSave() [6/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 178 of file Edible_Base.c.
References GetFoodStage(), m_DecayTimer, m_LastDecayStage, and Serializer::Write().
OnStoreSave() [7/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 32 of file Flag_Base.c.
OnStoreSave() [8/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 23 of file Paper.c.
References Serializer::Write().
OnStoreSave() [9/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 287 of file Spotlight.c.
References Serializer::Write().
OnStoreSave() [10/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 96 of file TentBase.c.
References m_State, and Serializer::Write().
OnStoreSave() [11/11]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 86 of file TrapSpawnBase.c.
References m_IsActive, m_IsInProgress, and Serializer::Write().
OnStoreSaveCustom()
void OnStoreSaveCustom (ParamsWriteContext ctx) inline private
Definition at line 357 of file PlantBase.c.
References Serializer::Write().
Referenced by OnStoreSave().
OnSwitchOff() [1/5]
override void OnSwitchOff () inline private
Definition at line 340 of file BatteryCharger.c.
OnSwitchOff() [2/5]
override void OnSwitchOff () inline private
Definition at line 26 of file PortableGasLamp.c.
References SoundTurnOff().
OnSwitchOff() [3/5]
override void OnSwitchOff () inline private
Definition at line 131 of file PortableGasStove.c.
References GetCookingEquipment(), GetGame(), m_CookingProcess, m_UTSource, and SoundTurnOff().
OnSwitchOff() [4/5]
override void OnSwitchOff () inline private
Definition at line 42 of file Refridgerator.c.
OnSwitchOff() [5/5]
override void OnSwitchOff () inline private
Definition at line 99 of file Spotlight.c.
References m_Light, and SoundTurnOff().
OnSwitchOn() [1/5]
override void OnSwitchOn () inline private
Definition at line 334 of file BatteryCharger.c.
OnSwitchOn() [2/5]
override void OnSwitchOn () inline private
Definition at line 18 of file PortableGasLamp.c.
References SoundTurnOn().
OnSwitchOn() [3/5]
override void OnSwitchOn () inline private
Definition at line 118 of file PortableGasStove.c.
References GetGame(), m_UTSource, and SoundTurnOn().
OnSwitchOn() [4/5]
override void OnSwitchOn () inline private
Definition at line 37 of file Refridgerator.c.
OnSwitchOn() [5/5]
override void OnSwitchOn () inline private
Definition at line 92 of file Spotlight.c.
References SoundTurnOn().
OnSynchronizedClient()
protected void OnSynchronizedClient () inline private
Definition at line 100 of file BaseBuildingBase.c.
References SetActionFromSyncData(), SetPartsFromSyncData(), and BaseBuildingBase::UpdateVisuals().
OnVariablesSynchronized() [1/13]
override void OnVariablesSynchronized () inline private
Definition at line 68 of file GardenBase.c.
References SyncSlots().
OnVariablesSynchronized() [2/13]
override void OnVariablesSynchronized () inline private
Definition at line 125 of file BarbedWire.c.
References CanPlayDeployLoopSound(), IsDeploySound(), m_DeployLoopSound, m_IsMounted, PlayDeployLoopSound(), PlayDeploySound(), PlaySoundSet(), and StopDeployLoopSound().
OnVariablesSynchronized() [3/13]
override void OnVariablesSynchronized () inline private
Definition at line 92 of file BaseBuildingBase.c.
References bsbDebugPrint(), CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetDebugName(), GetGame(), and OnSynchronizedClient().
OnVariablesSynchronized() [4/13]
override void OnVariablesSynchronized () inline private
Definition at line 365 of file BatteryCharger.c.
References IsPlaceSound(), and PlayPlaceSound().
OnVariablesSynchronized() [5/13]
override void OnVariablesSynchronized () inline private
Definition at line 91 of file CableReel.c.
References IsPlaceSound(), and PlayPlaceSound().
OnVariablesSynchronized() [6/13]
override void OnVariablesSynchronized () inline private
Definition at line 118 of file Edible_Base.c.
References m_MakeCookingSounds, RefreshAudio(), RemoveAudio(), and UpdateVisuals().
OnVariablesSynchronized() [7/13]
override void OnVariablesSynchronized () inline private
Definition at line 24 of file Flag_Base.c.
OnVariablesSynchronized() [8/13]
override void OnVariablesSynchronized () inline private
Definition at line 27 of file KitBase.c.
References CanPlayDeployLoopSound(), IsDeploySound(), IsSoundSynchRemote(), m_DeployLoopSound, PlayDeployFinishSound(), PlayDeployLoopSound(), PlayDeploySound(), and StopDeployLoopSound().
OnVariablesSynchronized() [9/13]
override void OnVariablesSynchronized () inline private
Definition at line 335 of file PowerGenerator.c.
References IsPlaceSound(), PlayPlaceSound(), and UpdateFuelMeter().
OnVariablesSynchronized() [10/13]
override void OnVariablesSynchronized () inline private
Definition at line 47 of file Refridgerator.c.
References IsPlaceSound(), and PlayPlaceSound().
OnVariablesSynchronized() [11/13]
override void OnVariablesSynchronized () inline private
Definition at line 247 of file Spotlight.c.
References CanPlayDeployLoopSound(), IsDeploySound(), m_DeployLoopSound, PlayDeployLoopSound(), PlayDeploySound(), and StopDeployLoopSound().
OnVariablesSynchronized() [12/13]
override void OnVariablesSynchronized () inline private
Definition at line 165 of file TentBase.c.
References CanPlayDeployLoopSound(), IsDeploySound(), IsSoundSynchRemote(), m_DeployLoopSound, m_State, PlayDeployLoopSound(), PlayDeploySound(), and StopDeployLoopSound().
OnVariablesSynchronized() [13/13]
override void OnVariablesSynchronized () inline private
this event is called all variables are synchronized on client
Definition at line 130 of file TrapSpawnBase.c.
References CanPlayDeployLoopSound(), IsDeploySound(), m_DeployLoopSound, PlayDeployLoopSound(), PlayDeploySound(), and StopDeployLoopSound().
OnWasAttached() [1/3]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 939 of file InventoryItem.c.
OnWasAttached() [2/3]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 69 of file Flag_Base.c.
OnWasAttached() [3/3]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 3 of file Switchable_Base.c.
References Class::CastTo().
OnWasDetached() [1/3]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 947 of file InventoryItem.c.
OnWasDetached() [2/3]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 77 of file Flag_Base.c.
OnWasDetached() [3/3]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 14 of file Switchable_Base.c.
References Class::CastTo().
OnWork() [1/6]
override void OnWork (float consumed_energy) inline private
Definition at line 232 of file BarbedWire.c.
OnWork() [2/6]
override void OnWork (float consumed_energy) inline private
Definition at line 50 of file BatteryCharger.c.
References GetGame(), GetHealth(), and SetTemperature().
OnWork() [3/6]
override void OnWork (float consumed_energy) inline private
Definition at line 25 of file Flashlight.c.
References GetGame(), m_Light, and PointLightBase::SetIntensity().
OnWork() [4/6]
override void OnWork (float consumed_energy) inline private
damaging of cookware
Definition at line 182 of file PortableGasStove.c.
References Math::Clamp(), CookWithEquipment(), GameConstants::FIRE_ATTACHMENT_DAMAGE_PER_SECOND, GetCookingEquipment(), GetGame(), m_UTSource, m_UTSSettings, PARAM_COOKING_EQUIP_MAX_TEMP, PARAM_COOKING_EQUIP_TEMP_INCREASE, and PARAM_COOKING_TEMP_THRESHOLD.
OnWork() [5/6]
override void OnWork (float consumed_energy) inline private
Definition at line 163 of file PowerGenerator.c.
References GetGame(), m_UTSLEngine, m_UTSource, m_UTSSettings, and UpdateFuelMeter().
OnWork() [6/6]
override void OnWork (float consumed_energy) inline private
Definition at line 23 of file Refridgerator.c.
OnWorkStart() [1/11]
override void OnWorkStart () inline private
Definition at line 207 of file BarbedWire.c.
References CreateElectrifiedDamageTrigger(), DestroyDamageTrigger(), and SoundBuzzLoopStart().
OnWorkStart() [2/11]
override void OnWorkStart () inline private
Definition at line 101 of file BatteryCharger.c.
References GetGame(), and UpdateStatusLights().
OnWorkStart() [3/11]
override void OnWorkStart () inline private
Definition at line 11 of file Blowtorch.c.
References m_Light, RefreshFlameVisual(), and SoundBurningStart().
OnWorkStart() [4/11]
override void OnWorkStart () inline private
Definition at line 41 of file Defibrillator.c.
References CALL_CATEGORY_GAMEPLAY, GetGame(), m_ChargeTime, and SEffectManager::PlaySoundOnObject().
OnWorkStart() [5/11]
override void OnWorkStart () inline private
Definition at line 13 of file Flashlight.c.
References GetGame(), and m_Light.
OnWorkStart() [6/11]
override void OnWorkStart () inline private
Definition at line 34 of file PortableGasLamp.c.
References GetGame(), m_Light, and SoundBurningStart().
OnWorkStart() [7/11]
override void OnWorkStart () inline private
Definition at line 148 of file PortableGasStove.c.
References GetCookingEquipment(), m_Light, RefreshFlameVisual(), and SoundBurningStart().
OnWorkStart() [8/11]
override void OnWorkStart () inline private
Definition at line 136 of file PowerGenerator.c.
References CALL_CATEGORY_SYSTEM, GetGame(), IsInitialized(), m_UTSource, and PlaySoundSet().
OnWorkStart() [9/11]
override void OnWorkStart () inline private
Definition at line 7 of file Raycaster.c.
References GetGame(), and StartPeriodicMeasurement().
OnWorkStart() [10/11]
override void OnWorkStart () inline private
Definition at line 16 of file Refridgerator.c.
References PlaySoundLoop().
OnWorkStart() [11/11]
override void OnWorkStart () inline private
Definition at line 112 of file Spotlight.c.
References m_Light, and UpdateAllSelections().
OnWorkStop() [1/11]
override void OnWorkStop () inline private
Definition at line 220 of file BarbedWire.c.
References CreateDamageTrigger(), DestroyDamageTrigger(), and SoundBuzzLoopStop().
OnWorkStop() [2/11]
override void OnWorkStop () inline private
Definition at line 110 of file BatteryCharger.c.
References GetGame(), and UpdateStatusLights().
OnWorkStop() [3/11]
override void OnWorkStop () inline private
Definition at line 24 of file Blowtorch.c.
References m_Light, RefreshFlameVisual(), and SoundBurningStop().
OnWorkStop() [4/11]
override void OnWorkStop () inline private
Definition at line 58 of file Defibrillator.c.
References StopChargedAlarm(), StopChargingSound(), and StopChargingTimer().
OnWorkStop() [5/11]
override void OnWorkStop () inline private
Definition at line 47 of file Flashlight.c.
References GetGame(), and m_Light.
OnWorkStop() [6/11]
override void OnWorkStop () inline private
Definition at line 49 of file PortableGasLamp.c.
References m_Light, and SoundBurningStop().
OnWorkStop() [7/11]
override void OnWorkStop () inline private
Definition at line 164 of file PortableGasStove.c.
References m_Light, RefreshFlameVisual(), RemoveCookingAudioVisuals(), and SoundBurningStop().
OnWorkStop() [8/11]
override void OnWorkStop () inline private
Definition at line 180 of file PowerGenerator.c.
References SEffectManager::DestroyEffect(), GetGame(), m_UTSource, PlaySoundSet(), StopSoundSet(), and UpdateFuelMeter().
OnWorkStop() [9/11]
override void OnWorkStop () inline private
Definition at line 63 of file Raycaster.c.
References GetGame(), and StopPeriodicMeasurement().
OnWorkStop() [10/11]
override void OnWorkStop () inline private
Definition at line 28 of file Refridgerator.c.
References GetGame(), and CGame::ObjectDelete().
OnWorkStop() [11/11]
override void OnWorkStop () inline private
Definition at line 122 of file Spotlight.c.
References m_Light, and UpdateAllSelections().
Pack()
void Pack (bool update_navmesh, bool init = false) inline private
Definition at line 551 of file TentBase.c.
References GetGame(), init, m_HalfExtents, m_State, and Refresh().
Paper()
void Paper () inline private
Definition at line 5 of file Paper.c.
ParticleTest()
void ParticleTest () inline private
Definition at line 9 of file ParticleTest.c.
References ParticleList::DEBUG_DOT, GetGame(), ParticleList::GetPathToParticles(), GetPosition, ParticleManager(), and path.
PerformRoofCheckForBase()
bool PerformRoofCheckForBase (string partName, PlayerBase player, out bool result) inline private
Definition at line 961 of file BaseBuildingBase.c.
PileOfWoodenPlanks()
void PileOfWoodenPlanks () inline private
Definition at line 3 of file PileOfWoodenPlanks.c.
References GetGame(), and SetAllowDamage().
Pitch()
void Pitch (bool update_navmesh, bool init = false) inline private
Definition at line 582 of file TentBase.c.
References GetGame(), init, m_State, and Refresh().
Pitchfork()
void Pitchfork () inline private
Definition at line 3 of file Pitchfork.c.
PlaceOnGround()
void PlaceOnGround () inline private
Definition at line 5 of file UndergroundStash.c.
References GetGame(), GetPosition, SetPosition(), and CGame::SurfaceRoadY().
PlantBase()
void PlantBase () inline private
Definition at line 46 of file PlantBase.c.
References CGame::ConfigGetInt(), CGame::ConfigGetText(), GetGame(), GetPlugin(), GetType(), Math::RandomInt(), and SetTakeable().
PlantSeed()
void PlantSeed (ItemBase seed, string selection_component) inline private
Definition at line 402 of file GardenBase.c.
References CALL_CATEGORY_SYSTEM, and GetPlugin().
PlayDeployLoopSound() [1/5]
void PlayDeployLoopSound () inline private
Definition at line 152 of file BarbedWire.c.
References GetGame(), GetLoopDeploySoundset(), GetPosition, EffectSound::IsSoundPlaying(), m_DeployLoopSound, and SEffectManager::PlaySound().
Referenced by OnVariablesSynchronized().
PlayDeployLoopSound() [2/5]
void PlayDeployLoopSound () inline private
Definition at line 152 of file KitBase.c.
References GetGame(), KitBase::GetLoopDeploySoundset(), GetPosition, EffectSound::IsSoundPlaying(), m_DeployLoopSound, and SEffectManager::PlaySound().
PlayDeployLoopSound() [3/5]
void PlayDeployLoopSound () inline private
Definition at line 414 of file Spotlight.c.
References GetGame(), GetLoopDeploySoundset(), GetPosition, m_DeployLoopSound, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
PlayDeployLoopSound() [4/5]
void PlayDeployLoopSound () inline private
Definition at line 892 of file TentBase.c.
References GetGame(), TentBase::GetLoopDeploySoundset(), GetPosition, EffectSound::IsSoundPlaying(), m_DeployLoopSound, and SEffectManager::PlaySound().
PlayDeployLoopSound() [5/5]
void PlayDeployLoopSound () inline private
Definition at line 492 of file TrapSpawnBase.c.
References GetGame(), TrapSpawnBase::GetLoopDeploySoundset(), GetPosition, EffectSound::IsSoundPlaying(), m_DeployLoopSound, and SEffectManager::PlaySound().
PostAreaDamageActions()
override void PostAreaDamageActions () inline private
Definition at line 391 of file BarbedWire.c.
PowerGenerator()
void PowerGenerator () inline private
Definition at line 27 of file PowerGenerator.c.
PreAreaDamageActions()
override void PreAreaDamageActions () inline private
Definition at line 381 of file BarbedWire.c.
References SoundCollision(), SoundElectricShock(), and Spark().
PrepareMeasurement()
void PrepareMeasurement () inline private
Definition at line 25 of file Raycaster.c.
References DoMeasurement().
PrintSlots()
void PrintSlots () inline private
Definition at line 243 of file GardenBase.c.
References GetState(), and Debug::Log().
PrintValues()
void PrintValues () inline private
Definition at line 427 of file PlantBase.c.
References Print().
ProcessDecay()
override void ProcessDecay (float delta, bool hasRootAsPlayer) inline private
Definition at line 550 of file Edible_Base.c.
References CanChangeToNewStage(), ChangeFoodStage(), DayZGame(), GameConstants::DECAY_FOOD_BAKED_FRVG, GameConstants::DECAY_FOOD_BAKED_MEAT, GameConstants::DECAY_FOOD_BOILED_FRVG, GameConstants::DECAY_FOOD_BOILED_MEAT, GameConstants::DECAY_FOOD_CAN_OPEN, GameConstants::DECAY_FOOD_DRIED_MEAT, GameConstants::DECAY_FOOD_FRVG_DRIED_CHANCE, GameConstants::DECAY_FOOD_RAW_CORPSE, GameConstants::DECAY_FOOD_RAW_FRVG, GameConstants::DECAY_FOOD_RAW_MEAT, GameConstants::DECAY_RATE_ON_PLAYER, GameConstants::DECAY_TIMER_RANDOM_PERCENTAGE, GetFoodStageType(), GetGame(), GetHealth01(), InsertAgent(), Edible_Base::IsCorpse(), Edible_Base::IsFruit(), Edible_Base::IsMeat(), IsMushroom(), m_DecayDelta, m_DecayTimer, m_LastDecayStage, Math::RandomFloat01(), and Math::RandomIntInclusive().
Referenced by InventoryItem::OnCEUpdate().
RedLightOff()
void RedLightOff () inline private
Definition at line 316 of file BatteryCharger.c.
Referenced by UpdateStatusLights().
RedLightOn()
void RedLightOn () inline private
Definition at line 299 of file BatteryCharger.c.
Referenced by UpdateStatusLights().
Refresh()
void Refresh () inline private
Definition at line 682 of file TentBase.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), UpdatePhysics(), and UpdateVisuals().
RefreshAttachements()
void RefreshAttachements () inline private
Definition at line 338 of file TentBase.c.
References AddProxyPhysics(), InventorySlots::GetSlotIdFromString(), TentBase::HandleCamoNetAttachment(), and IsKindOf().
RefreshAudio()
protected void RefreshAudio () inline private
Definition at line 146 of file Edible_Base.c.
References GetFoodStageType(), particle_id, SOUND_BAKING_DONE, SOUND_BAKING_START, SOUND_BURNING_DONE, and SoundCookingStart().
RefreshFlameVisual() [1/2]
protected void RefreshFlameVisual (bool working = false) inline private
Definition at line 37 of file Blowtorch.c.
Referenced by EEItemAttached(), EEItemDetached(), OnWorkStart(), and OnWorkStop().
RefreshFlameVisual() [2/2]
protected void RefreshFlameVisual (bool working = false, bool hasAttachment = false) inline private
full size flame selection
shrinked flame selection
Definition at line 223 of file PortableGasStove.c.
RefreshPhysics() [1/3]
override void RefreshPhysics () inline private
Definition at line 375 of file BatteryCharger.c.
References AddProxyPhysics(), and RemoveProxyPhysics().
Referenced by InventoryItem::OnCreatePhysics().
RefreshPhysics() [2/3]
override void RefreshPhysics () inline private
Definition at line 132 of file KitBase.c.
References UpdatePhysics().
RefreshPhysics() [3/3]
override void RefreshPhysics () inline private
Definition at line 140 of file TentBase.c.
References m_State.
RegenerateNavmesh()
void RegenerateNavmesh () inline private
Definition at line 850 of file TentBase.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and SetAffectPathgraph().
RegisterActionForSync()
protected void RegisterActionForSync (int part_id, int action_id) inline private
Definition at line 211 of file BaseBuildingBase.c.
References m_InteractedPartId, and m_PerformedActionId.
RegisterPartForSync()
void RegisterPartForSync (int part_id) inline private
Definition at line 113 of file BaseBuildingBase.c.
References m_SyncParts01, m_SyncParts02, and m_SyncParts03.
RemoveAudio()
protected void RemoveAudio () inline private
Definition at line 169 of file Edible_Base.c.
References m_MakeCookingSounds, and SoundCookingStop().
RemoveCookingAudioVisuals()
protected void RemoveCookingAudioVisuals () inline private
Definition at line 251 of file PortableGasStove.c.
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, and GetCookingEquipment().
Referenced by EEItemDetached(), and OnWorkStop().
RemovePlanks()
int RemovePlanks (int needed_planks) inline private
Definition at line 72 of file PileOfWoodenPlanks.c.
References AddQuantity(), GetQuantity(), and UpdateSelections().
RemovePlant()
void RemovePlant () inline private
Definition at line 690 of file PlantBase.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, RemoveSlot(), and UnlockFromParent().
RemovePlantEx()
void RemovePlantEx (vector pos) inline private
Definition at line 707 of file PlantBase.c.
References ECE_PLACE_ON_SURFACE, GetGame(), RemoveSlot(), and UnlockFromParent().
RemoveSlot() [1/2]
void RemoveSlot () inline private
Definition at line 824 of file PlantBase.c.
Referenced by DestroyPlant(), RemovePlant(), RemovePlantEx(), and SpoiledRemoveTimerTick().
RemoveSlot() [2/2]
void RemoveSlot (int index) inline private
Definition at line 627 of file GardenBase.c.
References GetGame(), CGame::ObjectDelete(), and ToStringLen().
RemoveSlotPlant()
void RemoveSlotPlant (Object plant) inline private
Definition at line 657 of file GardenBase.c.
ReplaceEdibleWithNew()
void ReplaceEdibleWithNew (string typeName) inline private
Definition at line 490 of file Edible_Base.c.
References Error(), and ReplaceEdibleWithNewLambda().
ResetActionSyncData()
protected void ResetActionSyncData () inline private
Definition at line 217 of file BaseBuildingBase.c.
References m_InteractedPartId, and m_PerformedActionId.
ResetToggle()
void ResetToggle () inline private
Definition at line 709 of file TentBase.c.
SetActionFromSyncData()
protected void SetActionFromSyncData () inline private
Definition at line 224 of file BaseBuildingBase.c.
References AT_BUILD_PART, AT_DESTROY_PART, AT_DISMANTLE_PART, GetConstructionPartById(), ConstructionPart::GetPartName(), m_InteractedPartId, m_PerformedActionId, OnPartBuiltClient(), OnPartDestroyedClient(), and OnPartDismantledClient().
SetActions() [1/52]
override void SetActions () inline private
Definition at line 764 of file InventoryItem.c.
References ActionAttach(), and AddAction().
Referenced by InventoryItem::InitializeActions().
SetActions() [2/52]
override void SetActions () inline private
Definition at line 774 of file InventoryItem.c.
References ActionAttach(), and AddAction().
SetActions() [3/52]
override void SetActions () inline private
Definition at line 786 of file InventoryItem.c.
References AddAction().
SetActions() [4/52]
override void SetActions () inline private
Definition at line 803 of file InventoryItem.c.
References ActionDetach(), and AddAction().
SetActions() [5/52]
override void SetActions () inline private
Definition at line 819 of file InventoryItem.c.
References ActionDetach(), and AddAction().
SetActions() [6/52]
override void SetActions () inline private
Definition at line 840 of file InventoryItem.c.
References ActionDetach(), and AddAction().
SetActions() [7/52]
override void SetActions () inline private
Definition at line 853 of file GardenBase.c.
References AddAction().
SetActions() [8/52]
override void SetActions () inline private
Definition at line 912 of file PlantBase.c.
References AddAction().
SetActions() [9/52]
override void SetActions () inline private
Definition at line 37 of file BandageDressing.c.
References ActionAttach(), ActionDetach(), and AddAction().
SetActions() [10/52]
override void SetActions () inline private
Definition at line 447 of file BarbedWire.c.
References AddAction().
SetActions() [11/52]
override void SetActions () inline private
Definition at line 37 of file Bark_ColorBase.c.
References ActionAttach(), ActionDetach(), and AddAction().
SetActions() [12/52]
override void SetActions () inline private
Definition at line 1151 of file BaseBuildingBase.c.
References AddAction(), and RemoveAction().
SetActions() [13/52]
override void SetActions () inline private
Definition at line 71 of file Battery9V.c.
References AddAction().
SetActions() [14/52]
override void SetActions () inline private
Definition at line 434 of file BatteryCharger.c.
References AddAction().
SetActions() [15/52]
override void SetActions () inline private
Definition at line 99 of file Blowtorch.c.
References ActionRepairCarChassisWithBlowtorch(), ActionRepairCarEngineWithBlowtorch(), ActionRepairCarPartWithBlowtorch(), ActionRepairItemWithBlowtorch(), and AddAction().
SetActions() [16/52]
override void SetActions () inline private
Definition at line 135 of file CableReel.c.
References AddAction(), and RemoveAction().
SetActions() [17/52]
override void SetActions () inline private
Definition at line 3 of file CamoNet.c.
References AddAction().
SetActions() [18/52]
override void SetActions () inline private
Definition at line 147 of file Defibrillator.c.
References AddAction().
SetActions() [19/52]
override void SetActions () inline private
Definition at line 502 of file Edible_Base.c.
References ActionAttach(), ActionDetach(), and AddAction().
SetActions() [20/52]
override void SetActions () inline private
Definition at line 8 of file FieldShovel.c.
References ActionBuryAshes(), and AddAction().
SetActions() [21/52]
override void SetActions () inline private
Definition at line 3 of file Firewood.c.
References ActionAttach(), ActionDetach(), and AddAction().
SetActions() [22/52]
override void SetActions () inline private
Definition at line 112 of file Flag_Base.c.
References ActionAttach(), and AddAction().
SetActions() [23/52]
override void SetActions () inline private
Definition at line 77 of file Flashlight.c.
References AddAction().
SetActions() [24/52]
override void SetActions () inline private
Definition at line 37 of file GiftWrapPaper.c.
References ActionAttach(), ActionDetach(), and AddAction().
SetActions() [25/52]
override void SetActions () inline private
Definition at line 70 of file HandcuffsLocked.c.
References AddAction().
SetActions() [26/52]
override void SetActions () inline private
Definition at line 25 of file HandDrillKit.c.
References ActionLightItemOnFire(), and AddAction().
SetActions() [27/52]
override void SetActions () inline private
Definition at line 67 of file GardenLime.c.
References AddAction().
SetActions() [28/52]
override void SetActions () inline private
Definition at line 202 of file KitBase.c.
References ActionDeployObject(), and AddAction().
SetActions() [29/52]
override void SetActions () inline private
Definition at line 33 of file Matchbox.c.
References ActionLightItemOnFire(), and AddAction().
SetActions() [30/52]
override void SetActions () inline private
Definition at line 3 of file MetalPlate.c.
References AddAction().
SetActions() [31/52]
override void SetActions () inline private
Definition at line 121 of file MetalWire.c.
References ActionAttach(), and AddAction().
SetActions() [32/52]
override void SetActions () inline private
Definition at line 3 of file Nail.c.
References AddAction().
SetActions() [33/52]
override void SetActions () inline private
Definition at line 65 of file Paper.c.
References ActionAttach(), ActionDetach(), and AddAction().
SetActions() [34/52]
override void SetActions () inline private
Definition at line 8 of file Pelt_Base.c.
References ActionAttach(), ActionDetach(), and AddAction().
SetActions() [35/52]
override void SetActions () inline private
Definition at line 33 of file PetrolLighter.c.
References ActionLightItemOnFire(), and AddAction().
SetActions() [36/52]
override void SetActions () inline private
Definition at line 8 of file PickAxe.c.
References ActionBuryAshes(), ActionDigOutStash(), and AddAction().
SetActions() [37/52]
override void SetActions () inline private
Definition at line 7 of file Pitchfork.c.
References AddAction().
SetActions() [38/52]
override void SetActions () inline private
Definition at line 84 of file PortableGasLamp.c.
References AddAction().
SetActions() [39/52]
override void SetActions () inline private
Definition at line 338 of file PortableGasStove.c.
References ActionLightItemOnFire(), and AddAction().
SetActions() [40/52]
override void SetActions () inline private
Definition at line 363 of file PowerGenerator.c.
References AddAction().
SetActions() [41/52]
override void SetActions () inline private
Definition at line 83 of file Rag.c.
References ActionAttach(), ActionCraftArmband(), ActionDetach(), and AddAction().
SetActions() [42/52]
override void SetActions () inline private
Definition at line 71 of file Raycaster.c.
References AddAction().
SetActions() [43/52]
override void SetActions () inline private
Definition at line 73 of file Refridgerator.c.
References AddAction(), and RemoveAction().
SetActions() [44/52]
override void SetActions () inline private
Definition at line 8 of file Shovel.c.
References ActionBuryAshes(), ActionDigOutStash(), and AddAction().
SetActions() [45/52]
override void SetActions () inline private
Definition at line 442 of file Spotlight.c.
References ActionDeployObject(), AddAction(), and RemoveAction().
SetActions() [46/52]
override void SetActions () inline private
Definition at line 3 of file Stone.c.
References ActionAttach(), ActionDetach(), and AddAction().
SetActions() [47/52]
override void SetActions () inline private
Definition at line 912 of file TentBase.c.
References ActionDeployObject(), ActionPackTent(), and AddAction().
SetActions() [48/52]
override void SetActions () inline private
Definition at line 21 of file Thermometer.c.
References AddAction().
SetActions() [49/52]
override void SetActions () inline private
Definition at line 513 of file TrapSpawnBase.c.
References AddAction().
SetActions() [50/52]
override void SetActions () inline private
Definition at line 3 of file WoodenLog.c.
References AddAction().
SetActions() [51/52]
override void SetActions () inline private
Definition at line 3 of file WoodenPlank.c.
References AddAction().
SetActions() [52/52]
override void SetActions () inline private
Definition at line 3 of file WoodenStick.c.
References ActionAttach(), ActionDetach(), and AddAction().
SetActive()
void SetActive () inline private
Definition at line 270 of file TrapSpawnBase.c.
References CALL_CATEGORY_GAMEPLAY, GetGame(), IsActive(), m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_InitWaitTime, m_IsActive, and m_Timer.
SetBaseFertility()
void SetBaseFertility (float value) inline private
Definition at line 85 of file GardenBase.c.
SetBaseState()
void SetBaseState (bool has_base) inline private
Definition at line 325 of file BaseBuildingBase.c.
References m_HasBase.
SetBloodTypeVisible()
void SetBloodTypeVisible (bool visible) inline private
Definition at line 15 of file BloodContainerBase.c.
SetCanCatch()
bool SetCanCatch (out EntityAI bait) inline private
Definition at line 385 of file TrapSpawnBase.c.
References InventorySlots::GetSlotIdFromString().
SetCEBasedQuantity()
override void SetCEBasedQuantity () inline private
Definition at line 13 of file Battery9V.c.
References GetQuantity(), and GetQuantityMax().
Referenced by InventoryItem::EEOnCECreate().
SetCookingEquipment()
void SetCookingEquipment (ItemBase equipment) inline private
Definition at line 41 of file PortableGasStove.c.
References m_CookingEquipment.
Referenced by ClearCookingEquipment(), and EEItemAttached().
SetCookingTime()
void SetCookingTime (float time) inline private
Definition at line 481 of file Edible_Base.c.
References GetFoodStage(), and Synchronize().
SetDeployed()
void SetDeployed (bool newState) inline private
Definition at line 160 of file TrapSpawnBase.c.
References m_AnimationPhaseSet, and m_AnimationPhaseTriggered.
SetFuel()
void SetFuel (float fuel_amount) inline private
Definition at line 256 of file PowerGenerator.c.
References DPrint(), GetType(), m_FuelTankCapacity, and UpdateFuelMeter().
Referenced by AddFuel(), and OnDebugSpawn().
SetInactive()
void SetInactive () inline private
Definition at line 291 of file TrapSpawnBase.c.
References GetGame(), m_IsActive, m_Timer, and Timer::Stop().
SetIsBeingPacked()
void SetIsBeingPacked (bool isBeingPacked) inline private
Definition at line 1040 of file TentBase.c.
SetMaxWaterStateVal()
void SetMaxWaterStateVal () inline private
Definition at line 120 of file GardenBase.c.
References Math::Pow().
SetMountedState()
void SetMountedState (bool is_mounted) inline private
Definition at line 74 of file BarbedWire.c.
References bsbDebugPrint(), GetDebugName(), LockAttachmentSlot(), SetTakeable(), and Synchronize().
Referenced by AfterStoreLoad().
SetPartFromSyncData()
void SetPartFromSyncData (ConstructionPart part) inline private
Definition at line 241 of file BaseBuildingBase.c.
References AddProxyPhysics(), ANIMATION_DEPLOYED, bsbDebugPrint(), bsbDebugSpam(), GetConstruction(), GetDebugName(), ConstructionPart::GetId(), ConstructionPart::GetPartName(), ConstructionPart::IsBase(), ConstructionPart::IsBuilt(), IsPartBuildInSyncData(), ConstructionPart::m_PartName, and RemoveProxyPhysics().
SetPartsAfterStoreLoad()
void SetPartsAfterStoreLoad () inline private
Definition at line 441 of file BaseBuildingBase.c.
References GetConstruction(), ConstructionPart::IsBuilt(), SetBaseState(), SetPartsFromSyncData(), and SynchronizeBaseState().
SetPartsFromSyncData()
void SetPartsFromSyncData () inline private
Definition at line 283 of file BaseBuildingBase.c.
References Construction(), GetConstruction(), SetPartFromSyncData(), and UpdateNavmesh().
SetPlantState()
void SetPlantState (int state) inline private
Definition at line 756 of file PlantBase.c.
Referenced by CheckWater(), GrowthTimerTick(), Init(), and SetSpoiled().
SetSlot()
void SetSlot (Slot slot) inline private
Definition at line 840 of file PlantBase.c.
Referenced by OnStoreLoad().
SetSlotTextureDigged()
void SetSlotTextureDigged (int slot_index) inline private
Definition at line 561 of file GardenBase.c.
References GetHiddenSelectionsTextures(), and ToStringLen().
SetSlotTextureFertilized()
void SetSlotTextureFertilized (int slot_index, string item_type) inline private
Definition at line 585 of file GardenBase.c.
References CGame::ConfigGetInt(), GetGame(), GetHiddenSelectionsTextures(), and ToStringLen().
SetSlotWateredState()
void SetSlotWateredState (int newState) inline private
Definition at line 848 of file GardenBase.c.
SetSpoiled()
void SetSpoiled () inline private
Definition at line 603 of file PlantBase.c.
References CALL_CATEGORY_SYSTEM, GetGame(), IsSpoiled(), SetPlantState(), and UpdatePlant().
Referenced by GrowthTimerTick().
SetupTrap()
void SetupTrap () inline private
Definition at line 200 of file TrapSpawnBase.c.
References GetGame(), and SetupTrapPlayer().
SetupTrapPlayer()
void SetupTrapPlayer (PlayerBase player, bool set_position = true) inline private
Definition at line 211 of file TrapSpawnBase.c.
References GetGame(), SetPosition(), and CGame::SurfaceRoadY().
SetUsed()
void SetUsed () inline private
Definition at line 308 of file TrapSpawnBase.c.
References GetGame(), m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_IsActive, m_Timer, and Timer::Stop().
ShowZonesHealth() [1/2]
override bool ShowZonesHealth () inline private
Definition at line 835 of file InventoryItem.c.
ShowZonesHealth() [2/2]
override bool ShowZonesHealth () inline private
Definition at line 914 of file BaseBuildingBase.c.
SlotWaterStateUpdate()
void SlotWaterStateUpdate (Slot slot) inline private
Definition at line 528 of file GardenBase.c.
SoundBuildStart()
protected void SoundBuildStart (string part_name) inline private
Definition at line 1086 of file BaseBuildingBase.c.
References GetBuildSoundByMaterial(), m_Sound, and PlaySoundSet().
SoundBurningStart() [1/3]
protected void SoundBurningStart () inline private
Definition at line 51 of file Blowtorch.c.
References PlaySoundSetLoop().
Referenced by OnWorkStart().
SoundBurningStart() [2/3]
protected void SoundBurningStart () inline private
Definition at line 64 of file PortableGasLamp.c.
References PlaySoundSetLoop().
SoundBurningStart() [3/3]
protected void SoundBurningStart () inline private
Definition at line 274 of file PortableGasStove.c.
References PlaySoundSetLoop().
SoundBurningStop() [1/3]
protected void SoundBurningStop () inline private
Definition at line 56 of file Blowtorch.c.
References StopSoundSet().
Referenced by OnWorkStop().
SoundBurningStop() [2/3]
protected void SoundBurningStop () inline private
Definition at line 69 of file PortableGasLamp.c.
References StopSoundSet().
SoundBurningStop() [3/3]
protected void SoundBurningStop () inline private
Definition at line 279 of file PortableGasStove.c.
References StopSoundSet().
SoundBuzzLoopStart()
void SoundBuzzLoopStart () inline private
Definition at line 332 of file BarbedWire.c.
References GetGame(), and PlaySoundLoop().
Referenced by OnWorkStart().
SoundBuzzLoopStop()
void SoundBuzzLoopStop () inline private
Definition at line 344 of file BarbedWire.c.
References GetGame(), and CGame::ObjectDelete().
Referenced by OnWorkStop().
SoundCollision()
void SoundCollision () inline private
Definition at line 368 of file BarbedWire.c.
References GetGame(), PlaySound(), and Math::RandomInt().
Referenced by PreAreaDamageActions().
SoundCookingStart()
protected void SoundCookingStart (string sound_name) inline private
Definition at line 510 of file Edible_Base.c.
References GetPosition, m_SoundEffectCooking, m_SoundPlaying, SEffectManager::PlaySound(), and SoundCookingStop().
SoundCookingStop()
protected void SoundCookingStop () inline private
Definition at line 523 of file Edible_Base.c.
References m_SoundEffectCooking, m_SoundPlaying, and EffectSound::Stop().
SoundCut()
void SoundCut () inline private
Definition at line 310 of file BarbedWire.c.
References GetGame(), PlaySound(), and Math::RandomInt().
Referenced by OnIsPlugged(), and OnIsUnplugged().
SoundDestroyStart()
protected void SoundDestroyStart (string part_name) inline private
Definition at line 1096 of file BaseBuildingBase.c.
References GetDismantleSoundByMaterial(), m_Sound, and PlaySoundSet().
SoundDismantleStart()
protected void SoundDismantleStart (string part_name) inline private
Definition at line 1091 of file BaseBuildingBase.c.
References GetDismantleSoundByMaterial(), m_Sound, and PlaySoundSet().
SoundElectricShock()
void SoundElectricShock () inline private
Definition at line 357 of file BarbedWire.c.
References GetGame(), PlaySound(), and Math::RandomInt().
Referenced by PreAreaDamageActions().
SoundSpark()
void SoundSpark () inline private
Definition at line 321 of file BarbedWire.c.
References GetGame(), PlaySound(), and Math::RandomInt().
Referenced by Spark().
SoundTentClosePlay()
void SoundTentClosePlay () inline private
Definition at line 832 of file TentBase.c.
References GetPosition, TentBase::GetSoundClose(), SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
SoundTentCloseWindowPlay()
void SoundTentCloseWindowPlay () inline private
Definition at line 844 of file TentBase.c.
References GetPosition, TentBase::GetSoundCloseWindow(), SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
SoundTentOpenPlay()
void SoundTentOpenPlay () inline private
Definition at line 826 of file TentBase.c.
References GetPosition, TentBase::GetSoundOpen(), SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
SoundTentOpenWindowPlay()
void SoundTentOpenWindowPlay () inline private
Definition at line 838 of file TentBase.c.
References GetPosition, TentBase::GetSoundOpenWindow(), SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
SoundTurnOff() [1/3]
protected void SoundTurnOff () inline private
Definition at line 79 of file PortableGasLamp.c.
References PlaySoundSet().
Referenced by OnSwitchOff().
SoundTurnOff() [2/3]
protected void SoundTurnOff () inline private
Definition at line 289 of file PortableGasStove.c.
References PlaySoundSet().
SoundTurnOff() [3/3]
protected void SoundTurnOff () inline private
Definition at line 348 of file Spotlight.c.
References PlaySoundSet().
SoundTurnOn() [1/3]
protected void SoundTurnOn () inline private
Definition at line 74 of file PortableGasLamp.c.
References PlaySoundSet().
Referenced by OnSwitchOn().
SoundTurnOn() [2/3]
protected void SoundTurnOn () inline private
Definition at line 284 of file PortableGasStove.c.
References PlaySoundSet().
SoundTurnOn() [3/3]
protected void SoundTurnOn () inline private
Definition at line 343 of file Spotlight.c.
References PlaySoundSet().
Spark()
void Spark () inline private
Definition at line 301 of file BarbedWire.c.
References ParticleList::BARBED_WIRE_SPARKS, ParticleManager(), and SoundSpark().
Referenced by PreAreaDamageActions().
SpawnCatch()
void SpawnCatch () inline private
Definition at line 332 of file TrapSpawnBase.c.
References AvoidPlayer(), CALL_CATEGORY_GAMEPLAY, GetCEApi(), GetGame(), GetMemoryPointPos(), GetPosition, m_Timer, MemoryPointExists(), ModelToWorld(), SetIsDeploySound(), and Timer::Stop().
SpoiledRemoveTimerTick()
void SpoiledRemoveTimerTick () inline private
Definition at line 585 of file PlantBase.c.
References RemoveSlot().
Spotlight()
void Spotlight () inline private
Definition at line 43 of file Spotlight.c.
SprayPlant()
void SprayPlant (float consumed_quantity) inline private
Definition at line 643 of file PlantBase.c.
References ChangeInfestation(), NeedsSpraying(), and UpdatePlant().
StartActivate()
void StartActivate (PlayerBase player) inline private
Definition at line 243 of file TrapSpawnBase.c.
StartLoopSound()
void StartLoopSound () inline private
Definition at line 78 of file PowerGenerator.c.
References GetGame(), SEffectManager::PlayOnObject(), and PlaySoundSetLoop().
StartPeriodicMeasurement()
void StartPeriodicMeasurement () inline private
Definition at line 15 of file Raycaster.c.
References m_Timer.
Referenced by OnWorkStart().
StopChargedAlarm()
void StopChargedAlarm () inline private
Definition at line 84 of file Defibrillator.c.
References EffectSound::SoundStop().
Referenced by OnWorkStop().
StopChargingSound()
void StopChargingSound () inline private
Definition at line 94 of file Defibrillator.c.
References EffectSound::SoundStop().
Referenced by OnWorkStop().
StopChargingTimer()
void StopChargingTimer () inline private
Definition at line 102 of file Defibrillator.c.
Referenced by OnWorkStop().
StopDeployLoopSound() [1/5]
void StopDeployLoopSound () inline private
Definition at line 163 of file BarbedWire.c.
References GetGame(), m_DeployLoopSound, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
Referenced by OnVariablesSynchronized().
StopDeployLoopSound() [2/5]
void StopDeployLoopSound () inline private
Definition at line 163 of file KitBase.c.
References GetGame(), m_DeployLoopSound, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
StopDeployLoopSound() [3/5]
void StopDeployLoopSound () inline private
Definition at line 423 of file Spotlight.c.
References GetGame(), m_DeployLoopSound, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
StopDeployLoopSound() [4/5]
void StopDeployLoopSound () inline private
Definition at line 903 of file TentBase.c.
References GetGame(), m_DeployLoopSound, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
StopDeployLoopSound() [5/5]
void StopDeployLoopSound () inline private
Definition at line 503 of file TrapSpawnBase.c.
References GetGame(), m_DeployLoopSound, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
StopInfestation()
string StopInfestation (float consumed_quantity) inline private
Definition at line 664 of file PlantBase.c.
References ChangeInfestation(), NeedsSpraying(), and UpdatePlant().
StopPeriodicMeasurement()
void StopPeriodicMeasurement () inline private
Definition at line 55 of file Raycaster.c.
References m_Timer, and Timer::Stop().
Referenced by OnWorkStop().
SwitchLightOff()
void SwitchLightOff () inline private
Definition at line 328 of file BatteryCharger.c.
Referenced by BatteryCharger(), and UpdateStatusLights().
SwitchLightOn()
void SwitchLightOn () inline private
Definition at line 311 of file BatteryCharger.c.
Referenced by UpdateStatusLights().
Synchronize() [1/3]
void Synchronize () inline private
Definition at line 117 of file BarbedWire.c.
References GetGame().
Referenced by SetMountedState().
Synchronize() [2/3]
void Synchronize () inline private
Definition at line 108 of file Edible_Base.c.
References GetGame(), and UpdateVisuals().
Synchronize() [3/3]
void Synchronize () inline private
Definition at line 16 of file Flag_Base.c.
References GetGame().
SynchronizeBaseState()
void SynchronizeBaseState () inline private
Definition at line 84 of file BaseBuildingBase.c.
References GetGame().
SyncSlots()
void SyncSlots () inline private
Definition at line 194 of file GardenBase.c.
References GetGame(), and GardenBase::GetGardenSlotsCount().
TentBase()
void TentBase () inline private
Definition at line 42 of file TentBase.c.
References GetInvulnerabilityTypeString(), m_HalfExtents, and vector::Zero.
ToggleAnimation()
void ToggleAnimation (string selection) inline private
Definition at line 737 of file TentBase.c.
References AddProxyPhysics(), TentBase::AnimateCamonetToggle(), string::Contains(), ToggleAnimations::GetOpeningBit(), ToggleAnimations::GetToggleOff(), ToggleAnimations::GetToggleOn(), m_State, RemoveProxyPhysics(), SoundSynchRemote(), and string::ToLower().
ToolBase()
void ToolBase () inline private
Definition at line 6 of file ToolBase.c.
TransferFoodStage()
void TransferFoodStage (notnull Edible_Base source) inline private
Definition at line 462 of file Edible_Base.c.
References ChangeFoodStage(), m_DecayDelta, m_DecayTimer, and m_LastDecayStage.
TrapSpawnBase()
void TrapSpawnBase () inline private
Definition at line 50 of file TrapSpawnBase.c.
References UAWaterType::FRESH, m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DefectRate, m_InitWaitTime, and UAWaterType::SEA.
TryPitch()
protected void TryPitch (bool update_navmesh, bool init = false) inline private
Definition at line 608 of file TentBase.c.
References GetGame(), and init.
UndergroundStash()
void UndergroundStash () inline private
Definition at line 3 of file UndergroundStash.c.
Unfold()
void Unfold () inline private
Definition at line 280 of file Spotlight.c.
References UpdateAllSelections().
Referenced by EOnInit(), ActionFillObject::OnFinishProgressServer(), OnInitEnergy(), OnIsPlugged(), OnItemLocationChanged(), OnPlacementComplete(), and OnStoreLoad().
UnregisterPartForSync()
void UnregisterPartForSync (int part_id) inline private
Definition at line 142 of file BaseBuildingBase.c.
References m_SyncParts01, m_SyncParts02, and m_SyncParts03.
UpdateAllSelections() [1/2]
void UpdateAllSelections () inline private
Definition at line 32 of file MetalWire.c.
References SEL_PLUG_SUFIX, SEL_WIRE_SUFIX, and string::ToLower().
Referenced by EOnInit(), Fold(), OnInitEnergy(), OnIsPlugged(), OnIsUnplugged(), OnOwnSocketReleased(), OnOwnSocketTaken(), OnWorkStart(), OnWorkStop(), and Unfold().
UpdateAllSelections() [2/2]
protected void UpdateAllSelections () inline private
Definition at line 165 of file Spotlight.c.
References GetSelectionPositionLS(), IsFolded(), and IsHologram().
UpdateAttachmentPhysics()
void UpdateAttachmentPhysics (string slot_name, bool is_locked) inline private
Definition at line 786 of file BaseBuildingBase.c.
References AddProxyPhysics(), bsbDebugPrint(), GetDebugName(), m_Mountables, and RemoveProxyPhysics().
UpdateAttachmentSlot()
protected void UpdateAttachmentSlot () inline private
Definition at line 87 of file BarbedWire.c.
References InventoryLocation::GetSlot(), and InventorySlots::GetSlotName().
UpdateAttachmentVisuals()
void UpdateAttachmentVisuals (string slot_name, bool is_locked) inline private
Definition at line 709 of file BaseBuildingBase.c.
References CreateAreaDamage(), and DestroyAreaDamage().
UpdateFuelMeter()
void UpdateFuelMeter () inline private
Definition at line 247 of file PowerGenerator.c.
References GetGame().
Referenced by EOnInit(), OnInitEnergy(), OnItemLocationChanged(), OnVariablesSynchronized(), OnWork(), OnWorkStop(), and SetFuel().
UpdateNavmesh()
protected void UpdateNavmesh () inline private
Definition at line 816 of file BaseBuildingBase.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and SetAffectPathgraph().
UpdateNVGStatus()
void UpdateNVGStatus (PlayerBase player, bool attaching = false, bool force_disable = false) inline private
Definition at line 877 of file InventoryItem.c.
References InventorySlots::GetSlotIdFromString().
UpdatePhysics() [1/3]
void UpdatePhysics () inline private
Definition at line 754 of file BaseBuildingBase.c.
References AddProxyPhysics(), ANIMATION_DEPLOYED, bsbDebugPrint(), GetAttachmentSlots(), GetConstruction(), GetDebugName(), HasBase(), IsAttachmentSlotLocked(), RemoveProxyPhysics(), UpdateAttachmentPhysics(), and UpdateNavmesh().
UpdatePhysics() [2/3]
void UpdatePhysics () inline private
Definition at line 146 of file KitBase.c.
References AddProxyPhysics(), and RemoveProxyPhysics().
UpdatePhysics() [3/3]
void UpdatePhysics () inline private
Definition at line 650 of file TentBase.c.
References AddProxyPhysics(), ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, string::Get(), CGame::GetCallQueue(), GetGame(), GetState(), and string::ToLower().
UpdatePlant()
void UpdatePlant () inline private
Definition at line 489 of file PlantBase.c.
References HasCrops(), and ToStringLen().
Referenced by GrowthTimerTick(), Harvest(), OnStoreLoadCustom(), SetSpoiled(), SprayPlant(), and StopInfestation().
UpdateSelections()
void UpdateSelections () inline private
Definition at line 12 of file PileOfWoodenPlanks.c.
References AddProxyPhysics(), GetQuantity(), GetQuantityMax(), and RemoveProxyPhysics().
Referenced by EEItemLocationChanged(), and RemovePlanks().
UpdateSlotTexture()
void UpdateSlotTexture (int slot_index) inline private
Definition at line 535 of file GardenBase.c.
References ToStringLen().
UpdateStatusLights()
void UpdateStatusLights () inline private
Definition at line 119 of file BatteryCharger.c.
References GetGame(), GreenLightOff(), GreenLightOn(), m_BlinkingStatusLightIsOn, RedLightOff(), RedLightOn(), SwitchLightOff(), SwitchLightOn(), YellowLightOff(), and YellowLightOn().
Referenced by OnWorkStart(), and OnWorkStop().
UpdateTexturesOnAllSlots()
void UpdateTexturesOnAllSlots () inline private
Definition at line 137 of file GardenBase.c.
References GardenBase::GetGardenSlotsCount().
UpdateVisuals() [1/4]
void UpdateVisuals () inline private
Definition at line 685 of file BaseBuildingBase.c.
References ANIMATION_DEPLOYED, GetAttachmentSlots(), GetConstruction(), HasBase(), IsAttachmentSlotLocked(), and UpdateAttachmentVisuals().
UpdateVisuals() [2/4]
void UpdateVisuals () inline private
Definition at line 77 of file Edible_Base.c.
References GetFoodStage().
UpdateVisuals() [3/4]
void UpdateVisuals () inline private
Definition at line 140 of file KitBase.c.
UpdateVisuals() [4/4]
void UpdateVisuals () inline private
Definition at line 623 of file TentBase.c.
References string::Get(), and GetState().
WaterAllSlots()
void WaterAllSlots () inline private
Definition at line 821 of file GardenBase.c.
References Math::Pow().
YellowLightOff()
void YellowLightOff () inline private
Definition at line 324 of file BatteryCharger.c.
Referenced by UpdateStatusLights().
YellowLightOn()
void YellowLightOn () inline private
Definition at line 307 of file BatteryCharger.c.
Referenced by UpdateStatusLights().
Field Documentation
ANIM_PHASE_FLAME
const string ANIM_PHASE_FLAME = "FlameHide" private
Definition at line 4 of file Blowtorch.c.
ANIMATION_DEPLOYED
const string ANIMATION_DEPLOYED = "Deployed" private
Definition at line 4 of file BaseBuildingBase.c.
ATTACHED_CLIPS_STATES
protected const string ATTACHED_CLIPS_STATES[] = {SEL_CLIPS_CAR, SEL_CLIPS_TRUCK} private
Definition at line 23 of file BatteryCharger.c.
ATTACHED_CLIPS_STATES_COUNT
protected const int ATTACHED_CLIPS_STATES_COUNT = 2 private
Definition at line 24 of file BatteryCharger.c.
Referenced by HideAttachedClipsStates().
ATTACHMENT_CAULDRON
ATTACHMENT_CAULDRON = Cauldron private
Definition at line 9 of file PortableGasStove.c.
Referenced by EEItemAttached(), EEItemDetached(), and RemoveCookingAudioVisuals().
ATTACHMENT_COOKING_POT
ATTACHMENT_COOKING_POT = Pot private
Definition at line 7 of file PortableGasStove.c.
Referenced by EEItemAttached(), EEItemDetached(), and RemoveCookingAudioVisuals().
ATTACHMENT_FRYING_PAN
ATTACHMENT_FRYING_PAN = FryingPan private
Definition at line 8 of file PortableGasStove.c.
Referenced by EEItemAttached(), EEItemDetached(), and RemoveCookingAudioVisuals().
CHARGED_AND_READY_SOUND
const string CHARGED_AND_READY_SOUND = "defibrillator_ready_SoundSet" static private
Definition at line 4 of file Defibrillator.c.
CHARGING_SOUND
const string CHARGING_SOUND = "defibrillator_charge_SoundSet" static private
Definition at line 3 of file Defibrillator.c.
CHECK_RAIN_INTERVAL
private const int CHECK_RAIN_INTERVAL = 15 static private
Definition at line 23 of file GardenBase.c.
DEFAULT_MATERIAL
protected const string DEFAULT_MATERIAL = "dz\\gear\\camping\\data\\battery_charger.rvmat" static private
Definition at line 21 of file BatteryCharger.c.
DIRECT_COOKING_SLOT_NAME
const string DIRECT_COOKING_SLOT_NAME = "DirectCooking" private
Definition at line 3 of file Edible_Base.c.
FLAME_BUTANE_OFF
protected const string FLAME_BUTANE_OFF = "" private
Definition at line 6 of file PortableGasStove.c.
FLAME_BUTANE_ON
protected const string FLAME_BUTANE_ON = "dz\\gear\\cooking\\data\\flame_butane_ca.paa" private
Definition at line 5 of file PortableGasStove.c.
GAS_LIGHT_MATERIAL_OFF
private const string GAS_LIGHT_MATERIAL_OFF = "dz\\data\\data\\default.rvmat" private
Definition at line 6 of file PortableGasLamp.c.
GAS_LIGHT_MATERIAL_ON
private const string GAS_LIGHT_MATERIAL_ON = "dz\\gear\\cooking\\data\\GasLightOn.rvmat" private
Definition at line 5 of file PortableGasLamp.c.
GLASS_ID
int GLASS_ID = 2 static private
Definition at line 6 of file Flashlight.c.
GREEN_LIGHT_GLOW
protected const string GREEN_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_g.rvmat" static private
Definition at line 18 of file BatteryCharger.c.
ID_GLASS_FOLDED
const int ID_GLASS_FOLDED = 5 static private
Definition at line 26 of file Spotlight.c.
ID_GLASS_UNFOLDED
const int ID_GLASS_UNFOLDED = 3 static private
Definition at line 24 of file Spotlight.c.
ID_REFLECTOR_FOLDED
const int ID_REFLECTOR_FOLDED = 6 static private
Definition at line 27 of file Spotlight.c.
ID_REFLECTOR_UNFOLDED
const int ID_REFLECTOR_UNFOLDED = 4 static private
Definition at line 25 of file Spotlight.c.
LIGHT_OFF_GLASS
static string LIGHT_OFF_GLASS = "dz\\gear\\tools\\data\\flashlight_glass.rvmat" static private
Definition at line 8 of file Flashlight.c.
LIGHT_OFF_REFLECTOR
static string LIGHT_OFF_REFLECTOR = "dz\\gear\\tools\\data\\flashlight.rvmat" static private
Definition at line 9 of file Flashlight.c.
LIGHT_ON_GLASS
static string LIGHT_ON_GLASS = "dz\\gear\\tools\\data\\flashlight_glass_on.rvmat" static private
Definition at line 10 of file Flashlight.c.
LIGHT_ON_REFLECTOR
static string LIGHT_ON_REFLECTOR = "dz\\gear\\tools\\data\\flashlight_glass_on.rvmat" static private
Definition at line 11 of file Flashlight.c.
LOOP_SOUND
const string LOOP_SOUND = "powerGeneratorLoop_SoundSet" static private
Definition at line 9 of file PowerGenerator.c.
m_AlignCatchTimer
ref Timer m_AlignCatchTimer private
Definition at line 46 of file TrapSpawnBase.c.
m_AnimationPhaseSet
string m_AnimationPhaseSet private
Definition at line 24 of file TrapSpawnBase.c.
m_AnimationPhaseTriggered
string m_AnimationPhaseTriggered private
Definition at line 25 of file TrapSpawnBase.c.
m_AnimationPhaseUsed
string m_AnimationPhaseUsed private
Definition at line 26 of file TrapSpawnBase.c.
m_AreaDamage
protected ref AreaDamageManager m_AreaDamage private
Definition at line 20 of file BarbedWire.c.
m_Bait
protected EntityAI m_Bait private
Definition at line 16 of file TrapSpawnBase.c.
m_BaitCatchProb
float m_BaitCatchProb private
Definition at line 10 of file TrapSpawnBase.c.
m_BaitNeeded
bool m_BaitNeeded private
Definition at line 43 of file TrapSpawnBase.c.
m_BatteryEnergy0To100
int m_BatteryEnergy0To100 private
Definition at line 28 of file BatteryCharger.c.
m_BlinkingStatusLightInterval
protected float m_BlinkingStatusLightInterval = 0.4 static private
Definition at line 31 of file BatteryCharger.c.
m_BlinkingStatusLightIsOn
protected bool m_BlinkingStatusLightIsOn = false private
Definition at line 33 of file BatteryCharger.c.
Referenced by UpdateStatusLights().
m_BuzzSoundLoop
SoundOnVehicle m_BuzzSoundLoop private
Definition at line 17 of file BarbedWire.c.
m_CamoNet
protected CamoNet m_CamoNet private
Definition at line 39 of file TentBase.c.
m_CanCatch
bool m_CanCatch = false private
Definition at line 7 of file TrapSpawnBase.c.
m_Catch
private ItemBase m_Catch private
Definition at line 45 of file TrapSpawnBase.c.
m_CatchesGroundAnimal
ref multiMap<string, float> m_CatchesGroundAnimal private
Definition at line 34 of file TrapSpawnBase.c.
m_CatchesPond
ref multiMap<string, float> m_CatchesPond private
Definition at line 32 of file TrapSpawnBase.c.
m_CatchesSea
ref multiMap<string, float> m_CatchesSea private
Definition at line 33 of file TrapSpawnBase.c.
m_ChargedAlarm
EffectSound m_ChargedAlarm private
Definition at line 13 of file Defibrillator.c.
m_ChargeEnergyPerSecond
protected float m_ChargeEnergyPerSecond private
Definition at line 29 of file BatteryCharger.c.
m_ChargeTime
float m_ChargeTime = 5 static private
Definition at line 9 of file Defibrillator.c.
Referenced by OnWorkStart().
m_ChargingSound
EffectSound m_ChargingSound private
Definition at line 14 of file Defibrillator.c.
m_ChargingTimer
ref Timer m_ChargingTimer private
Definition at line 12 of file Defibrillator.c.
m_CheckRainTimer
ref Timer m_CheckRainTimer private
Definition at line 30 of file GardenBase.c.
m_ClutterCutter
protected Object m_ClutterCutter private
Definition at line 37 of file TentBase.c.
m_Construction
ref Construction m_Construction private
Definition at line 8 of file BaseBuildingBase.c.
m_ConstructionKitHealth
float m_ConstructionKitHealth private
Definition at line 6 of file BaseBuildingBase.c.
m_CookingEquipment
ItemBase m_CookingEquipment private
Definition at line 20 of file PortableGasStove.c.
Referenced by GetCookingEquipment().
m_CookingProcess
ref Cooking m_CookingProcess private
Definition at line 19 of file PortableGasStove.c.
m_CropsCount
private int m_CropsCount private
Definition at line 14 of file PlantBase.c.
Referenced by Harvest().
m_CropsType
private string m_CropsType private
Definition at line 16 of file PlantBase.c.
Referenced by GetCropsType().
m_CurrentPlantMaterialQuantity
private float m_CurrentPlantMaterialQuantity private
Definition at line 21 of file PlantBase.c.
m_DamageTriggers
ref map<string, ref AreaDamageManager> m_DamageTriggers private
Definition at line 34 of file BaseBuildingBase.c.
m_DecayDelta
protected float m_DecayDelta = 0.0 private
Definition at line 15 of file Edible_Base.c.
m_DecayTimer
protected float m_DecayTimer private
Definition at line 14 of file Edible_Base.c.
m_DefaultFertility
protected float m_DefaultFertility = 1 private
Definition at line 29 of file GardenBase.c.
m_DefectRate
float m_DefectRate private
Definition at line 5 of file TrapSpawnBase.c.
m_DeleteDryPlantTime
int m_DeleteDryPlantTime private
Definition at line 27 of file PlantBase.c.
m_DeleteDryPlantTimer
ref Timer m_DeleteDryPlantTimer = NULL private
Definition at line 37 of file PlantBase.c.
m_DeployedRegularly
protected bool m_DeployedRegularly private
Definition at line 4 of file KitBase.c.
m_DeployLoopSound [1/3]
ref protected EffectSound m_DeployLoopSound private
Definition at line 15 of file BarbedWire.c.
m_DeployLoopSound [2/3]
protected EffectSound m_DeployLoopSound private
Definition at line 40 of file Spotlight.c.
m_DeployLoopSound [3/3]
protected ref EffectSound m_DeployLoopSound private
Definition at line 36 of file TrapSpawnBase.c.
m_Efficiency0To10
private int m_Efficiency0To10 private
Definition at line 3 of file Battery9V.c.
m_EfficiencyDecayStart
private float m_EfficiencyDecayStart = 0.1 static private
Definition at line 4 of file Battery9V.c.
Referenced by GetEfficiencyDecayStart().
m_EnergyNeededToCharge
float m_EnergyNeededToCharge = 20 static private
Definition at line 10 of file Defibrillator.c.
m_EngineLoop
protected EffectSound m_EngineLoop private
Definition at line 14 of file PowerGenerator.c.
m_EngineStart
protected EffectSound m_EngineStart private
Definition at line 15 of file PowerGenerator.c.
m_EngineStop
protected EffectSound m_EngineStop private
Definition at line 16 of file PowerGenerator.c.
m_EvaluateDeployment
private bool m_EvaluateDeployment private
Definition at line 4 of file Spotlight.c.
m_FinalCatchProb
float m_FinalCatchProb private
Definition at line 12 of file TrapSpawnBase.c.
m_FoodStage
ref FoodStage m_FoodStage private
Definition at line 13 of file Edible_Base.c.
m_ForceIntoHands
bool m_ForceIntoHands private
Definition at line 3 of file CableReel.c.
m_Fuel
float m_Fuel private
Definition at line 3 of file PowerGenerator.c.
m_FuelPercentage
private int m_FuelPercentage private
Definition at line 6 of file PowerGenerator.c.
m_FuelTankCapacity
private float m_FuelTankCapacity static private
Definition at line 4 of file PowerGenerator.c.
Referenced by GetMaxFuel(), OnInitEnergy(), and SetFuel().
m_FuelToEnergyRatio
private float m_FuelToEnergyRatio static private
Definition at line 5 of file PowerGenerator.c.
Referenced by GetFuel().
m_FullMaturityTime
int m_FullMaturityTime private
Definition at line 29 of file PlantBase.c.
Referenced by Init().
m_GardenBase
private GardenBase m_GardenBase = NULL private
Definition at line 39 of file PlantBase.c.
Referenced by GetGarden().
m_GrowthStagesCount
private int m_GrowthStagesCount private
Definition at line 13 of file PlantBase.c.
m_GrowthTimer
ref Timer m_GrowthTimer = NULL private
Definition at line 33 of file PlantBase.c.
m_HalfExtents
protected vector m_HalfExtents private
Definition at line 40 of file TentBase.c.
m_HasBase
bool m_HasBase = false private
Definition at line 10 of file BaseBuildingBase.c.
m_HasCrops
private bool m_HasCrops private
Definition at line 15 of file PlantBase.c.
Referenced by HasCrops().
m_HybridAttachments
ref array<string> m_HybridAttachments private
Definition at line 35 of file BaseBuildingBase.c.
m_InfestationChance
private float m_InfestationChance private
Definition at line 11 of file PlantBase.c.
m_InfestationTimer
ref Timer m_InfestationTimer = NULL private
Definition at line 34 of file PlantBase.c.
m_InfoSetup
string m_InfoSetup private
Definition at line 47 of file TrapSpawnBase.c.
m_InitWaitTime
int m_InitWaitTime private
Definition at line 3 of file TrapSpawnBase.c.
m_InteractedPartId
int m_InteractedPartId private
Definition at line 15 of file BaseBuildingBase.c.
m_IsActive
protected bool m_IsActive private
Definition at line 18 of file TrapSpawnBase.c.
m_IsBeingPacked
protected bool m_IsBeingPacked = false private
Definition at line 30 of file TentBase.c.
m_IsBloodTypeVisible
private bool m_IsBloodTypeVisible = false private
Definition at line 3 of file BloodContainerBase.c.
m_IsCharged
bool m_IsCharged = false private
Definition at line 7 of file Defibrillator.c.
Referenced by IsCharged().
m_IsDeployed
protected bool m_IsDeployed private
Definition at line 19 of file TrapSpawnBase.c.
m_IsEntrance
protected bool m_IsEntrance private
Definition at line 27 of file TentBase.c.
m_IsFoldable
bool m_IsFoldable private
Definition at line 6 of file TrapSpawnBase.c.
m_IsFolded
private bool m_IsFolded private
Definition at line 3 of file Spotlight.c.
Referenced by IsFolded().
m_IsInfested
private bool m_IsInfested private
Definition at line 23 of file PlantBase.c.
m_IsInProgress
protected bool m_IsInProgress private
Definition at line 20 of file TrapSpawnBase.c.
m_IsMounted
protected bool m_IsMounted private
Definition at line 26 of file BarbedWire.c.
Referenced by OnVariablesSynchronized().
m_IsPlaced
protected bool m_IsPlaced private
Definition at line 23 of file BarbedWire.c.
m_IsToggle
protected bool m_IsToggle private
Definition at line 29 of file TentBase.c.
m_IsUsable
bool m_IsUsable private
Definition at line 44 of file TrapSpawnBase.c.
m_IsWindow
protected bool m_IsWindow private
Definition at line 28 of file TentBase.c.
m_ItemVisibilityModifier
float m_ItemVisibilityModifier private
Definition at line 855 of file InventoryItem.c.
m_LastDecayStage
protected FoodStageType m_LastDecayStage = FoodStageType.NONE private
Definition at line 16 of file Edible_Base.c.
m_LastMountedState
protected bool m_LastMountedState private
Definition at line 27 of file BarbedWire.c.
m_Light [1/5]
protected BlowtorchLight m_Light private
Definition at line 7 of file Blowtorch.c.
m_Light [2/5]
FlashlightLight m_Light private
Definition at line 3 of file Flashlight.c.
m_Light [3/5]
PortableGasLampLight m_Light private
Definition at line 3 of file PortableGasLamp.c.
m_Light [4/5]
StoveLight m_Light private
Definition at line 3 of file PortableGasStove.c.
m_Light [5/5]
SpotlightLight m_Light private
Definition at line 5 of file Spotlight.c.
m_LightLocalOrientation
vector m_LightLocalOrientation = "0 0 0" static private
Definition at line 8 of file Spotlight.c.
m_LightLocalPosition
vector m_LightLocalPosition static private
Definition at line 7 of file Spotlight.c.
m_MakeCookingSounds
protected bool m_MakeCookingSounds private
Definition at line 9 of file Edible_Base.c.
m_map_slots
private ref map<string,string> m_map_slots static private
Definition at line 32 of file GardenBase.c.
m_MarkForDeletion
bool m_MarkForDeletion = false private
Definition at line 25 of file PlantBase.c.
m_MaxWateredStateVal
protected int m_MaxWateredStateVal = 0 private
Definition at line 28 of file GardenBase.c.
m_MineDisarmRate
protected int m_MineDisarmRate = 60 private
Definition at line 4 of file ToolBase.c.
m_MinimalDistanceFromPlayersToCatch
float m_MinimalDistanceFromPlayersToCatch private
Definition at line 8 of file TrapSpawnBase.c.
m_ModuleHorticulture
private PluginHorticulture m_ModuleHorticulture private
Definition at line 42 of file PlantBase.c.
m_Mountables
ref array<string> m_Mountables private
Definition at line 36 of file BaseBuildingBase.c.
m_MountSound
protected EffectSound m_MountSound private
Definition at line 29 of file BarbedWire.c.
m_NeedInstalation
bool m_NeedInstalation private
Definition at line 42 of file TrapSpawnBase.c.
m_NoBaitCatchProb
float m_NoBaitCatchProb private
Definition at line 11 of file TrapSpawnBase.c.
m_NoteContents
protected ref WrittenNoteData m_NoteContents private
Definition at line 3 of file Paper.c.
Referenced by GetWrittenNoteData().
m_OpeningMask
protected int m_OpeningMask = 0 private
Definition at line 31 of file TentBase.c.
m_OpeningMaskLocal
protected int m_OpeningMaskLocal = -1 private
Definition at line 32 of file TentBase.c.
m_Particle
protected Particle m_Particle private
Definition at line 6 of file ParticleTest.c.
m_PerformedActionId
int m_PerformedActionId private
Definition at line 16 of file BaseBuildingBase.c.
m_PlaceableWaterSurfaceList
const string m_PlaceableWaterType protected ref array<string> m_PlaceableWaterSurfaceList private
DEPRECATED.
Definition at line 29 of file TrapSpawnBase.c.
m_PlantMaterialMultiplier
private float m_PlantMaterialMultiplier private
Definition at line 17 of file PlantBase.c.
m_PlantState
private int m_PlantState private
Definition at line 19 of file PlantBase.c.
Referenced by GetPlantState().
m_PlantStateIndex
private int m_PlantStateIndex private
Definition at line 20 of file PlantBase.c.
Referenced by GetPlantStateIndex().
m_PrevTimer
ref Timer m_PrevTimer private
Definition at line 41 of file TrapSpawnBase.c.
m_PreyPos
vector m_PreyPos private
Definition at line 14 of file TrapSpawnBase.c.
m_ShowAnimationsWhenPacked
protected ref array<string> m_ShowAnimationsWhenPacked private
Definition at line 36 of file TentBase.c.
m_ShowAnimationsWhenPitched
protected ref array<string> m_ShowAnimationsWhenPitched private
Definition at line 35 of file TentBase.c.
m_Slot
private ref Slot m_Slot = NULL private
Definition at line 40 of file PlantBase.c.
Referenced by GetSlot(), and NeedsWater().
m_SlotFertilityState
protected int m_SlotFertilityState = 0 private
Definition at line 26 of file GardenBase.c.
m_Slots
protected ref array<ref Slot> m_Slots private
Definition at line 25 of file GardenBase.c.
m_SlotWateredState
protected int m_SlotWateredState = 0 private
Definition at line 27 of file GardenBase.c.
m_Smoke
ref protected Effect m_Smoke private
Definition at line 18 of file PowerGenerator.c.
m_Sound
protected EffectSound m_Sound private
Definition at line 32 of file BaseBuildingBase.c.
m_SoundBurningLoop
protected EffectSound m_SoundBurningLoop private
Definition at line 9 of file Blowtorch.c.
m_SoundBuzzLoop
const string m_SoundBuzzLoop = "electricFenceBuzzLoop1" static private
Definition at line 14 of file BarbedWire.c.
m_SoundCooking
protected SoundOnVehicle m_SoundCooking private
Definition at line 10 of file Edible_Base.c.
m_SoundEffectCooking
protected EffectSound m_SoundEffectCooking private
DEPRECATED.
Definition at line 11 of file Edible_Base.c.
m_SoundLoopEntity
SoundOnVehicle m_SoundLoopEntity private
Definition at line 3 of file Refridgerator.c.
m_SoundLoopStartTimer
ref Timer m_SoundLoopStartTimer private
Definition at line 17 of file PowerGenerator.c.
m_SoundPlaying
protected string m_SoundPlaying private
Definition at line 12 of file Edible_Base.c.
m_SoundsCollision
const string m_SoundsCollision[SOUNDS_COLLISION_COUNT] = {"barbedFenceCollision1", "barbedFenceCollision2", "barbedFenceCollision3", "barbedFenceCollision4"} static private
Definition at line 12 of file BarbedWire.c.
m_SoundsCut
const string m_SoundsCut[SOUNDS_CUT_COUNT] = {"barbedFenceCut1", "barbedFenceCut2", "barbedFenceCut3"} static private
Definition at line 11 of file BarbedWire.c.
m_SoundsShock
const string m_SoundsShock[SOUNDS_SHOCK_COUNT] = {"electricFenceShock1", "electricFenceShock2", "electricFenceShock3", "electricFenceShock4"} static private
Definition at line 13 of file BarbedWire.c.
m_SoundsSpark
const string m_SoundsSpark[SOUNDS_SPARK_COUNT] = {"electricFenceSpark1", "electricFenceSpark2", "electricFenceSpark3", "electricFenceSpark4"} static private
Definition at line 10 of file BarbedWire.c.
m_SoundTurnOff
protected EffectSound m_SoundTurnOff private
Definition at line 15 of file PortableGasLamp.c.
m_SoundTurnOn
protected EffectSound m_SoundTurnOn private
Definition at line 14 of file PortableGasLamp.c.
m_SparkEvent
ref Timer m_SparkEvent private
Definition at line 19 of file BarbedWire.c.
m_SparkPlug
ItemBase m_SparkPlug private
Definition at line 20 of file PowerGenerator.c.
m_SpoilAfterFullMaturityTime
int m_SpoilAfterFullMaturityTime private
Definition at line 30 of file PlantBase.c.
m_SpoilAfterFullMaturityTimer
ref Timer m_SpoilAfterFullMaturityTimer = NULL private
Definition at line 35 of file PlantBase.c.
m_SpoiledRemoveTime
int m_SpoiledRemoveTime private
Definition at line 28 of file PlantBase.c.
m_SpoiledRemoveTimer
ref Timer m_SpoiledRemoveTimer = NULL private
Definition at line 36 of file PlantBase.c.
m_SprayQuantity
private float m_SprayQuantity private
Definition at line 24 of file PlantBase.c.
Referenced by GetSprayQuantity().
m_SprayUsage
private float m_SprayUsage private
Definition at line 9 of file PlantBase.c.
Referenced by GetSprayUsage().
m_State
protected int m_State private
Definition at line 25 of file TentBase.c.
m_StateChangeTime
int m_StateChangeTime private
Definition at line 31 of file PlantBase.c.
m_StateLocal
protected int m_StateLocal = -1 private
Definition at line 26 of file TentBase.c.
m_SyncParts01
int m_SyncParts01 private
Definition at line 12 of file BaseBuildingBase.c.
m_SyncParts02
int m_SyncParts02 private
Definition at line 13 of file BaseBuildingBase.c.
m_SyncParts03
int m_SyncParts03 private
Definition at line 14 of file BaseBuildingBase.c.
m_TimeFactor
private float m_TimeFactor private
Definition at line 17 of file PortableGasStove.c.
m_Timer [1/2]
protected ref Timer m_Timer private
Definition at line 5 of file Raycaster.c.
m_Timer [2/2]
ref Timer m_Timer private
Definition at line 22 of file TrapSpawnBase.c.
m_ToggleAnimations
protected ref map< ref ToggleAnimations, bool> m_ToggleAnimations private
Definition at line 34 of file TentBase.c.
m_TriggerActive
protected bool m_TriggerActive private
Definition at line 22 of file BarbedWire.c.
m_UpdateStatusLightsTimer
ref Timer m_UpdateStatusLightsTimer private
Definition at line 32 of file BatteryCharger.c.
m_UpdateWaitTime
int m_UpdateWaitTime private
Definition at line 4 of file TrapSpawnBase.c.
m_UTSLConst
protected ref UniversalTemperatureSourceLambdaConstant m_UTSLConst private
Definition at line 33 of file PortableGasStove.c.
m_UTSLEngine
protected ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine private
Definition at line 24 of file PowerGenerator.c.
m_UTSource
protected ref UniversalTemperatureSource m_UTSource private
DEPRECATED Attached spark plug item.
Definition at line 31 of file PortableGasStove.c.
m_UTSSettings
protected ref UniversalTemperatureSourceSettings m_UTSSettings private
Definition at line 32 of file PortableGasStove.c.
m_WaterSurfaceForSetup
bool m_WaterSurfaceForSetup private
Definition at line 31 of file TrapSpawnBase.c.
MAX_PLACEMENT_HEIGHT_DIFF
const float MAX_PLACEMENT_HEIGHT_DIFF = 1.5 private
Definition at line 22 of file TentBase.c.
OPENING_0
const int OPENING_0 = 1 private
Definition at line 3 of file TentBase.c.
OPENING_1
const int OPENING_1 = 2 private
Definition at line 4 of file TentBase.c.
OPENING_10
const int OPENING_10 = 1024 private
Definition at line 13 of file TentBase.c.
OPENING_11
const int OPENING_11 = 2048 private
Definition at line 14 of file TentBase.c.
OPENING_12
const int OPENING_12 = 4096 private
Definition at line 15 of file TentBase.c.
OPENING_13
const int OPENING_13 = 8192 private
Definition at line 16 of file TentBase.c.
OPENING_14
const int OPENING_14 = 16384 private
Definition at line 17 of file TentBase.c.
OPENING_15
const int OPENING_15 = 32768 private
Definition at line 18 of file TentBase.c.
OPENING_2
const int OPENING_2 = 4 private
Definition at line 5 of file TentBase.c.
OPENING_3
const int OPENING_3 = 8 private
Definition at line 6 of file TentBase.c.
OPENING_4
const int OPENING_4 = 16 private
Definition at line 7 of file TentBase.c.
OPENING_5
const int OPENING_5 = 32 private
Definition at line 8 of file TentBase.c.
OPENING_6
const int OPENING_6 = 64 private
Definition at line 9 of file TentBase.c.
OPENING_7
const int OPENING_7 = 128 private
Definition at line 10 of file TentBase.c.
OPENING_8
const int OPENING_8 = 256 private
Definition at line 11 of file TentBase.c.
OPENING_9
const int OPENING_9 = 512 private
Definition at line 12 of file TentBase.c.
PACKED
const int PACKED = 0 static private
Definition at line 20 of file TentBase.c.
PARAM_COOKING_EQUIP_MAX_TEMP
protected const float PARAM_COOKING_EQUIP_MAX_TEMP = 250 private
Definition at line 14 of file PortableGasStove.c.
PARAM_COOKING_EQUIP_TEMP_INCREASE
protected const float PARAM_COOKING_EQUIP_TEMP_INCREASE = 10 private
Definition at line 13 of file PortableGasStove.c.
PARAM_COOKING_TEMP_THRESHOLD
protected const float PARAM_COOKING_TEMP_THRESHOLD = 100 private
Definition at line 12 of file PortableGasStove.c.
PARAM_COOKING_TIME_INC_COEF
protected const float PARAM_COOKING_TIME_INC_COEF = 0.5 private
Definition at line 15 of file PortableGasStove.c.
PARTICLE_PATH
protected int PARTICLE_PATH private
Definition at line 5 of file ParticleTest.c.
PITCHED
const int PITCHED = 1 static private
Definition at line 21 of file TentBase.c.
RANDOM_SPARK_INTERVAL
const float RANDOM_SPARK_INTERVAL = 5.0 static private
Definition at line 8 of file BarbedWire.c.
RED_LIGHT_GLOW
protected const string RED_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_r.rvmat" static private
Definition at line 17 of file BatteryCharger.c.
REFLECTOR_ID
int REFLECTOR_ID = 1 static private
Definition at line 5 of file Flashlight.c.
SEL_CLIPS_CAR
protected const string SEL_CLIPS_CAR = "clips_car_battery" static private
Definition at line 4 of file BatteryCharger.c.
SEL_CLIPS_DETACHED
protected const string SEL_CLIPS_DETACHED = "clips_detached" static private
Definition at line 6 of file BatteryCharger.c.
Referenced by OnPlacementStarted().
SEL_CLIPS_FOLDED
protected const string SEL_CLIPS_FOLDED = "clips_folded" static private
Definition at line 7 of file BatteryCharger.c.
SEL_CLIPS_TRUCK
protected const string SEL_CLIPS_TRUCK = "clips_truck_battery" static private
Definition at line 5 of file BatteryCharger.c.
SEL_CORD_FOLDED [1/2]
protected const string SEL_CORD_FOLDED = "cord_folded" static private
Definition at line 11 of file BatteryCharger.c.
Referenced by Hologram::CorrectMaterialPathName(), and OnPlacementStarted().
SEL_CORD_FOLDED [2/2]
const string SEL_CORD_FOLDED = "cord_folded" static private
Definition at line 5 of file CableReel.c.
SEL_CORD_FOLDED_F
const string SEL_CORD_FOLDED_F = "spotlight_folded_cord_folded" static private
Definition at line 15 of file Spotlight.c.
SEL_CORD_FOLDED_U
const string SEL_CORD_FOLDED_U = "cord_folded" static private
Definition at line 12 of file Spotlight.c.
SEL_CORD_PLUGGED [1/2]
protected const string SEL_CORD_PLUGGED = "cord_plugged" static private
Definition at line 10 of file BatteryCharger.c.
Referenced by Hologram::CorrectMaterialPathName(), and OnPlacementStarted().
SEL_CORD_PLUGGED [2/2]
const string SEL_CORD_PLUGGED = "cord_plugged" static private
Definition at line 6 of file CableReel.c.
SEL_CORD_PLUGGED_F
const string SEL_CORD_PLUGGED_F = "spotlight_folded_cord_plugged" static private
Definition at line 14 of file Spotlight.c.
Referenced by OnPlacementStarted().
SEL_CORD_PLUGGED_U
const string SEL_CORD_PLUGGED_U = "cord_plugged" static private
Definition at line 13 of file Spotlight.c.
SEL_GLASS_F
const string SEL_GLASS_F = "glass_folded" static private
Definition at line 19 of file Spotlight.c.
SEL_GLASS_U
const string SEL_GLASS_U = "glass_unfolded" static private
Definition at line 20 of file Spotlight.c.
SEL_INVENTORY
const string SEL_INVENTORY = "inventory" static private
Definition at line 17 of file Spotlight.c.
SEL_LIGHT_STATE_1
protected const string SEL_LIGHT_STATE_1 = "light_stand_by" static private
Definition at line 12 of file BatteryCharger.c.
SEL_LIGHT_STATE_2
protected const string SEL_LIGHT_STATE_2 = "light_charging" static private
Definition at line 13 of file BatteryCharger.c.
SEL_LIGHT_STATE_3
protected const string SEL_LIGHT_STATE_3 = "light_charged" static private
Definition at line 14 of file BatteryCharger.c.
SEL_PLACING
const string SEL_PLACING = "placing" static private
Definition at line 18 of file Spotlight.c.
SEL_PLUG_SUFIX
string SEL_PLUG_SUFIX = "_plug" static private
Definition at line 6 of file MetalWire.c.
Referenced by UpdateAllSelections().
SEL_REFLECTOR_COMP_U
const string SEL_REFLECTOR_COMP_U = "reflector" static private
Definition at line 11 of file Spotlight.c.
SEL_REFLECTOR_F
const string SEL_REFLECTOR_F = "reflector_folded" static private
Definition at line 21 of file Spotlight.c.
SEL_REFLECTOR_U
const string SEL_REFLECTOR_U = "reflector_unfolded" static private
Definition at line 22 of file Spotlight.c.
SEL_SWITCH_OFF
protected const string SEL_SWITCH_OFF = "switch_off" static private
Definition at line 9 of file BatteryCharger.c.
SEL_SWITCH_ON
protected const string SEL_SWITCH_ON = "switch_on" static private
Definition at line 8 of file BatteryCharger.c.
SEL_WIRE_PREFIX
string SEL_WIRE_PREFIX = "Att_" static private
Definition at line 4 of file MetalWire.c.
SEL_WIRE_ROLLED
string SEL_WIRE_ROLLED = "rolled" static private
Definition at line 3 of file MetalWire.c.
SEL_WIRE_SUFIX
string SEL_WIRE_SUFIX = "_plugged" static private
Definition at line 5 of file MetalWire.c.
Referenced by UpdateAllSelections().
SHOCK_SOUND
const string SHOCK_SOUND = "defibrillator_shock_SoundSet" static private
Definition at line 5 of file Defibrillator.c.
SLOT_MATERIAL_COMPOST_DRY
const string SLOT_MATERIAL_COMPOST_DRY = "dz\\gear\\cultivation\\data\\soil_cultivated_compost.rvmat" static private
Definition at line 14 of file GardenBase.c.
SLOT_MATERIAL_COMPOST_WET
const string SLOT_MATERIAL_COMPOST_WET = "dz\\gear\\cultivation\\data\\soil_cultivated_compost_wet.rvmat" static private
Definition at line 13 of file GardenBase.c.
SLOT_MATERIAL_DRY
const string SLOT_MATERIAL_DRY = "dz\\gear\\cultivation\\data\\soil_cultivated.rvmat" static private
Definition at line 9 of file GardenBase.c.
SLOT_MATERIAL_LIMED_DRY
const string SLOT_MATERIAL_LIMED_DRY = "dz\\gear\\cultivation\\data\\soil_cultivated_limed.rvmat" static private
Definition at line 12 of file GardenBase.c.
SLOT_MATERIAL_LIMED_WET
const string SLOT_MATERIAL_LIMED_WET = "dz\\gear\\cultivation\\data\\soil_cultivated_limed_wet.rvmat" static private
Definition at line 11 of file GardenBase.c.
SLOT_MATERIAL_WET
const string SLOT_MATERIAL_WET = "dz\\gear\\cultivation\\data\\soil_cultivated_wet.rvmat" static private
Definition at line 8 of file GardenBase.c.
SLOT_MEMORY_POINT_PREFIX
private const string SLOT_MEMORY_POINT_PREFIX = "slot_" static private
Definition at line 19 of file GardenBase.c.
SLOT_SEEDBASE_PREFIX
private const string SLOT_SEEDBASE_PREFIX = "seedbase_" static private
Definition at line 20 of file GardenBase.c.
SLOT_SELECTION_COVERED_PREFIX
private const string SLOT_SELECTION_COVERED_PREFIX = "slotCovered_" static private
Definition at line 18 of file GardenBase.c.
SLOT_SELECTION_DIGGED_PREFIX
private const string SLOT_SELECTION_DIGGED_PREFIX = "seedbase_" static private
Definition at line 17 of file GardenBase.c.
SLOT_TEXTURE_DIGGED_WET_LIME
const string SLOT_TEXTURE_DIGGED_WET_LIME = "dz\\gear\\cultivation\\data\\soil_digged_wet_lime_CO.paa" static private
Definition at line 4 of file GardenBase.c.
SLOT_TEXTURE_DIGGED_WET_PLANT
const string SLOT_TEXTURE_DIGGED_WET_PLANT = "dz\\gear\\cultivation\\data\\soil_digged_wet_plant_CO.paa" static private
Definition at line 5 of file GardenBase.c.
SOUND_BAKING_DONE
const string SOUND_BAKING_DONE = "Baking_Done_SoundSet" private
Definition at line 6 of file Edible_Base.c.
SOUND_BAKING_START
const string SOUND_BAKING_START = "Baking_SoundSet" private
Definition at line 5 of file Edible_Base.c.
SOUND_BUILD_METAL
const string SOUND_BUILD_METAL = "putDown_MetalPlank_SoundSet" private
Definition at line 23 of file BaseBuildingBase.c.
SOUND_BUILD_WIRE
const string SOUND_BUILD_WIRE = "putDown_BarbedWire_SoundSet" private
Definition at line 24 of file BaseBuildingBase.c.
SOUND_BUILD_WOOD_LOG
const string SOUND_BUILD_WOOD_LOG = "putDown_WoodLog_SoundSet" private
Definition at line 20 of file BaseBuildingBase.c.
SOUND_BUILD_WOOD_PLANK
const string SOUND_BUILD_WOOD_PLANK = "putDown_WoodPlank_SoundSet" private
Definition at line 21 of file BaseBuildingBase.c.
SOUND_BUILD_WOOD_STAIRS
const string SOUND_BUILD_WOOD_STAIRS = "putDown_WoodStairs_SoundSet" private
Definition at line 22 of file BaseBuildingBase.c.
SOUND_BURNING
const string SOUND_BURNING = "Blowtorch_Loop_SoundSet" private
Definition at line 5 of file Blowtorch.c.
SOUND_BURNING_DONE
const string SOUND_BURNING_DONE = "Food_Burning_SoundSet" private
Definition at line 7 of file Edible_Base.c.
SOUND_DISMANTLE_METAL
const string SOUND_DISMANTLE_METAL = "Crash_MetalPlank_SoundSet" private
Definition at line 29 of file BaseBuildingBase.c.
SOUND_DISMANTLE_WIRE
const string SOUND_DISMANTLE_WIRE = "putDown_BarbedWire_SoundSet" private
Definition at line 30 of file BaseBuildingBase.c.
SOUND_DISMANTLE_WOOD_LOG
const string SOUND_DISMANTLE_WOOD_LOG = "Crash_WoodPlank_SoundSet" private
Definition at line 26 of file BaseBuildingBase.c.
SOUND_DISMANTLE_WOOD_PLANK
const string SOUND_DISMANTLE_WOOD_PLANK = "Crash_WoodPlank_SoundSet" private
Definition at line 27 of file BaseBuildingBase.c.
SOUND_DISMANTLE_WOOD_STAIRS
const string SOUND_DISMANTLE_WOOD_STAIRS = "Crash_WoodPlank_SoundSet" private
Definition at line 28 of file BaseBuildingBase.c.
SOUND_MOUNT
const string SOUND_MOUNT = "putDown_BarbedWire_SoundSet" private
Definition at line 28 of file BarbedWire.c.
SOUND_TURN_OFF
const string SOUND_TURN_OFF = "portablegaslamp_turn_off_SoundSet" private
Definition at line 11 of file PortableGasLamp.c.
SOUND_TURN_ON
const string SOUND_TURN_ON = "portablegaslamp_turn_on_SoundSet" private
Definition at line 10 of file PortableGasLamp.c.
SOUNDS_COLLISION_COUNT
const int SOUNDS_COLLISION_COUNT = 4 static private
Definition at line 6 of file BarbedWire.c.
SOUNDS_CUT_COUNT
const int SOUNDS_CUT_COUNT = 3 static private
Definition at line 5 of file BarbedWire.c.
SOUNDS_SHOCK_COUNT
const int SOUNDS_SHOCK_COUNT = 4 static private
Definition at line 7 of file BarbedWire.c.
SOUNDS_SPARK_COUNT
const int SOUNDS_SPARK_COUNT = 4 static private
Definition at line 4 of file BarbedWire.c.
SPARKPLUG_ATTACH_SOUND
const string SPARKPLUG_ATTACH_SOUND = "sparkplug_attach_SoundSet" static private
Definition at line 11 of file PowerGenerator.c.
SPARKPLUG_DETACH_SOUND
const string SPARKPLUG_DETACH_SOUND = "sparkplug_detach_SoundSet" static private
Definition at line 12 of file PowerGenerator.c.
SPOIL_AFTER_MATURITY_TIME
private const float SPOIL_AFTER_MATURITY_TIME = 7200 private
Definition at line 44 of file PlantBase.c.
Referenced by Init().
START_SOUND
const string START_SOUND = "powerGeneratorTurnOn_SoundSet" static private
Definition at line 8 of file PowerGenerator.c.
STATE_DRY
const int STATE_DRY = 0 static private
Definition at line 4 of file PlantBase.c.
STATE_GROWING
const int STATE_GROWING = 1 static private
Definition at line 5 of file PlantBase.c.
STATE_MATURE
const int STATE_MATURE = 2 static private
Definition at line 6 of file PlantBase.c.
STATE_SPOILED
const int STATE_SPOILED = 3 static private
Definition at line 7 of file PlantBase.c.
STOP_SOUND
const string STOP_SOUND = "powerGeneratorTurnOff_SoundSet" static private
Definition at line 10 of file PowerGenerator.c.
SWITCH_LIGHT_GLOW
protected const string SWITCH_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_switch_on.rvmat" static private
Definition at line 20 of file BatteryCharger.c.
TEXTURE_FLAME
const string TEXTURE_FLAME = "dz\\gear\\cooking\\data\\flame_butane_ca.paa" private
Definition at line 3 of file Blowtorch.c.
YELLOW_LIGHT_GLOW
protected const string YELLOW_LIGHT_GLOW = "dz\\gear\\camping\\data\\battery_charger_light_y.rvmat" static private
Definition at line 19 of file BatteryCharger.c.
The documentation for this class was generated from the following files:
4_World/Entities/Core/Inherited/InventoryItem.c
4_World/Entities/GardenBase.c
4_World/Entities/GardenBase/PlantBase.c
4_World/Entities/ItemBase/BarbedWire.c
4_World/Entities/ItemBase/BaseBuildingBase.c
4_World/Entities/ItemBase/Battery9V.c
4_World/Entities/ItemBase/BatteryCharger.c
4_World/Entities/ItemBase/BloodContainerBase/BloodContainerBase.c
4_World/Entities/ItemBase/Blowtorch.c
4_World/Entities/ItemBase/CableReel.c
4_World/Entities/ItemBase/Defibrillator.c
4_World/Entities/ItemBase/Edible_Base.c
4_World/Entities/ItemBase/Flashlight.c
4_World/Entities/ItemBase/KitBase.c
4_World/Entities/ItemBase/MetalWire.c
4_World/Entities/ItemBase/Paper.c
4_World/Entities/ItemBase/ParticleTest.c
4_World/Entities/ItemBase/PortableGasLamp.c
4_World/Entities/ItemBase/PortableGasStove.c
4_World/Entities/ItemBase/PowerGenerator.c
4_World/Entities/ItemBase/Raycaster.c
4_World/Entities/ItemBase/Refridgerator.c
4_World/Entities/ItemBase/Spotlight.c
4_World/Entities/ItemBase/TentBase.c
4_World/Entities/ItemBase/ToolBase.c
4_World/Entities/ItemBase/TrapSpawnBase.c
4_World/Entities/ItemBase.c
4_World/Entities/ItemBase/BandageDressing.c
4_World/Entities/ItemBase/Bark_ColorBase.c
4_World/Entities/ItemBase/CamoNet.c
4_World/Entities/ItemBase/FieldShovel.c
4_World/Entities/ItemBase/Firewood.c
4_World/Entities/ItemBase/Flag_Base.c
4_World/Entities/ItemBase/GiftWrapPaper.c
4_World/Entities/ItemBase/HandcuffsLocked.c
4_World/Entities/ItemBase/HandDrillKit.c
4_World/Entities/ItemBase/Inventory_Base/GardenLime.c
4_World/Entities/ItemBase/Inventory_Base/GrozaGL_LowerReceiver.c
4_World/Entities/ItemBase/LargeGasCannister.c
4_World/Entities/ItemBase/Matchbox.c
4_World/Entities/ItemBase/MediumGasCannister.c
4_World/Entities/ItemBase/MetalPlate.c
4_World/Entities/ItemBase/Nail.c
4_World/Entities/ItemBase/Pelt_Base.c
4_World/Entities/ItemBase/PetrolLighter.c
4_World/Entities/ItemBase/PickAxe.c
4_World/Entities/ItemBase/PileOfWoodenPlanks.c
4_World/Entities/ItemBase/Pitchfork.c
4_World/Entities/ItemBase/Rag.c
4_World/Entities/ItemBase/Shovel.c
4_World/Entities/ItemBase/SmallGasCannister.c
4_World/Entities/ItemBase/Stone.c
4_World/Entities/ItemBase/Switchable_Base.c
4_World/Entities/ItemBase/Thermometer.c
4_World/Entities/ItemBase/WoodenLog.c
4_World/Entities/ItemBase/WoodenPlank.c
4_World/Entities/ItemBase/WoodenStick.c
4_World/Entities/UndergroundStash.c