DayZ Scripts Documentation: BIOSErrorModule Class Reference
BIOSErrorModule Class Reference
Private Member Functions
void BIOSErrorModule ()
override void InitOptionalVariables ()
override void FillErrorDataMap ()
void InsertBIOSError (int code, string message)
Detailed Description
Definition at line 62 of file BIOSErrorModule.c.
Constructor & Destructor Documentation
BIOSErrorModule()
void BIOSErrorModule () inline private
Definition at line 64 of file BIOSErrorModule.c.
Member Function Documentation
FillErrorDataMap()
override void FillErrorDataMap () inline private
Definition at line 76 of file BIOSErrorModule.c.
References InsertBIOSError(), and InsertErrorProperties().
InitOptionalVariables()
override void InitOptionalVariables () inline private
Definition at line 69 of file BIOSErrorModule.c.
References m_Header.
InsertBIOSError()
void InsertBIOSError (int code, string message) inline private
Definition at line 110 of file BIOSErrorModule.c.
References InsertDialogueErrorProperties(), and InsertErrorProperties().
Referenced by FillErrorDataMap().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Global/ErrorModuleHandler/BIOSErrorModule.c