DayZ Scripts Documentation: HeatComfortMdfr Class Reference
HeatComfortMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnReconnect (PlayerBase player)
override string GetDebugText ()
override string GetDebugTextSimple ()
override void OnTick (PlayerBase player, float deltaT)
Detailed Description
Definition at line 1 of file HeatComfortMdfr.c.
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
Definition at line 12 of file HeatComfortMdfr.c.
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
Definition at line 17 of file HeatComfortMdfr.c.
GetDebugText()
override string GetDebugText () inline private
Definition at line 27 of file HeatComfortMdfr.c.
References m_Player.
GetDebugTextSimple()
override string GetDebugTextSimple () inline private
Definition at line 32 of file HeatComfortMdfr.c.
References m_Player.
Init()
override void Init () inline private
Definition at line 3 of file HeatComfortMdfr.c.
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, DisableDeactivateCheck(), m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnReconnect()
override void OnReconnect (PlayerBase player) inline private
Definition at line 22 of file HeatComfortMdfr.c.
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
Definition at line 38 of file HeatComfortMdfr.c.
References Math::Clamp(), PlayerConstants::ENERGY_LOSS_HC_MINUS_HIGH, PlayerConstants::ENERGY_LOSS_HC_MINUS_LOW, PlayerConstants::ENERGY_LOSS_THRESHOLD_HC_MINUS_HIGH, PlayerConstants::ENERGY_LOSS_THRESHOLD_HC_MINUS_LOW, PlayerConstants::HEALTH_LOSS_HC_MINUS_HIGH, PlayerConstants::HEALTH_LOSS_HC_MINUS_LOW, PlayerConstants::HEALTH_LOSS_HC_PLUS_HIGH, PlayerConstants::HEALTH_LOSS_HC_PLUS_LOW, Math::InverseLerp(), Math::Lerp(), PlayerConstants::WATER_LOSS_HC_PLUS_HIGH, PlayerConstants::WATER_LOSS_HC_PLUS_LOW, PlayerConstants::WATER_LOSS_THRESHOLD_HC_PLUS_HIGH, and PlayerConstants::WATER_LOSS_THRESHOLD_HC_PLUS_LOW.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/HeatComfortMdfr.c