DayZ Scripts Documentation: GameOptions Class Reference
GameOptions Class Reference
Private Member Functions
proto native void Apply ()
Tests, Applies every option and save config with options to file, see OptionsAccess::Test, OptionsAccess::Apply.
proto native void Revert ()
Load config with options and Revert every option, see OptionsAccess::Revert.
proto native void Test ()
Tests every option, see OptionsAccess::Test.
proto native OptionsAccess GetOption (int index)
Get option by index.
proto native OptionsAccess GetOptionByType (int accessType)
Get option by AccessType.
proto native int GetOptionsCount ()
Registered options count.
proto native int NeedRestart ()
Checks if any option is changed and needs restart, see OptionsAccess::IsChanged, OptionsAccess::NeedRestart.
proto native int IsChanged ()
Checks if any option is changed, see OptionsAccess::IsChanged.
proto native void Initialize ()
Initializes option values with the current users settings.
Detailed Description
Definition at line 1388 of file gameplay.c.
Member Function Documentation
Apply()
proto native void Apply () private
Tests, Applies every option and save config with options to file, see OptionsAccess::Test, OptionsAccess::Apply.
GetOption()
proto native OptionsAccess GetOption (int index) private
Get option by index.
Parameters
index
Returns
OptionsAccess
GetOptionByType()
proto native OptionsAccess GetOptionByType (int accessType) private
Get option by AccessType.
Parameters
AccessType
Returns
OptionsAccess
Referenced by GetCurrentDisplayLanguageIdx(), PPESSAO::GetDefaultMaterialPath(), GetUserFOVFromConfig(), VONManager::IsVoiceThresholdMinimum(), ScriptedWidgetEventHandler::OptionsMenuGame(), ScriptedWidgetEventHandler::OptionsMenuSounds(), and ScriptedWidgetEventHandler::SetOptions().
GetOptionsCount()
proto native int GetOptionsCount () private
Registered options count.
Returns
number of options
Initialize()
proto native void Initialize () private
Initializes option values with the current users settings.
Referenced by DeferredInit().
IsChanged()
proto native int IsChanged () private
Checks if any option is changed, see OptionsAccess::IsChanged.
Returns
1 if such option was found, 0 othewise
NeedRestart()
proto native int NeedRestart () private
Checks if any option is changed and needs restart, see OptionsAccess::IsChanged, OptionsAccess::NeedRestart.
Returns
1 if such option was found, 0 othewise
Revert()
proto native void Revert () private
Load config with options and Revert every option, see OptionsAccess::Revert.
Test()
proto native void Test () private
Tests every option, see OptionsAccess::Test.
Referenced by ScriptedWidgetEventHandler::OnOverallQualityChanged().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/gameplay.c