DayZ Scripts: ActionDestroyPart Class Reference
ActionDestroyPart Class Reference
Private Member Functions
void ActionDestroyPart ()
override void CreateConditionComponents ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeUsedLeaning ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
protected bool DestroyCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check)
override string GetAdminLogMessage (ActionData action_data)
Static Private Attributes
static int CYCLES = 4
Detailed Description
Definition at line 9 of file ActionDestroyPart.c.
Constructor & Destructor Documentation
ActionDestroyPart()
void ActionDestroyPart () inline private
Definition at line 13 of file ActionDestroyPart.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 41 of file ActionDestroyPart.c.
References DestroyCondition().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
Definition at line 50 of file ActionDestroyPart.c.
References DestroyCondition(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
CanBeUsedLeaning()
override bool CanBeUsedLeaning () inline private
Definition at line 36 of file ActionDestroyPart.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 24 of file ActionDestroyPart.c.
References m_ConditionItem, and m_ConditionTarget.
DestroyCondition()
protected bool DestroyCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check) inline private
Definition at line 87 of file ActionDestroyPart.c.
References Construction(), UAMaxDistances::DEFAULT, GetGame(), BaseBuildingBase::IsFacingCamera(), IsInReach(), and ConstructionActionData::SetTargetPart().
Referenced by ActionCondition(), and ActionConditionContinue().
GetAdminLogMessage()
override string GetAdminLogMessage (ActionData action_data) inline private
Definition at line 126 of file ActionDestroyPart.c.
References ActionData::m_MainItem, and ActionData::m_Target.
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 30 of file ActionDestroyPart.c.
References ConstructionActionData::GetTargetPart(), and m_Text.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 55 of file ActionDestroyPart.c.
References AT_DESTROY_PART, Construction(), CYCLES, UADamageApplied::DESTROY, ConstructionPart::GetPartName(), ConstructionActionData::GetTargetPart(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
Field Documentation
CYCLES
int CYCLES = 4 static private
Definition at line 11 of file ActionDestroyPart.c.
Referenced by ActionDestroyPartCB::CreateActionComponent(), and OnFinishProgressServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionDestroyPart.c