DayZ: PluginLocalProfile Class Reference
PluginLocalProfile Class Reference
Private Member Functions
override string GetFileName ()
string GetPathScenes ()
override string GetFileName ()
override void OnInit ()
TStringArray GetSceneList ()
void SceneSave (SceneData scene)
Private Attributes
private const string FILE_ROOT = "$saves:"
private const string FILE_ROOT_SCENES = "Scenes"
private const string PARAM_MISSION = "Mission"
private const string PARAM_TIME = "InitTime"
private const string PARAM_RAIN = "InitWeatherRain"
private const string PARAM_FOG = "InitWeatherFog"
private const string PARAM_OBJ_COUNT = "SceneObjectsCount"
private const string PARAM_OBJ_NAME = "SceneObject"
private string m_FileSceneName
Detailed Description
Definition at line 1 of file PluginAdditionalInfo.c.
Member Function Documentation
GetFileName() [1/2]
override string GetFileName () inline private
Definition at line 3 of file PluginAdditionalInfo.c.
References CFG_FILE_ADDITIONAL_INFO.
Referenced by PluginFileHandler::LoadConfigFile().
GetFileName() [2/2]
override string GetFileName () inline private
Definition at line 42 of file PluginLocalProfileScene.c.
References GetPathScenes(), and m_FileSceneName.
GetPathScenes()
string GetPathScenes () inline private
Definition at line 34 of file PluginLocalProfileScene.c.
References FILE_ROOT_SCENES.
Referenced by GetFileName(), and GetSceneList().
GetSceneList()
TStringArray GetSceneList () inline private
Definition at line 59 of file PluginLocalProfileScene.c.
References FileExist(), FindFile(), FindNextFile(), GetPathScenes(), and MakeDirectory().
OnInit()
override void OnInit () inline private
Definition at line 51 of file PluginLocalProfileScene.c.
SceneSave()
void SceneSave (SceneData scene) inline private
Definition at line 88 of file PluginLocalProfileScene.c.
References SceneData::GetInitFog(), SceneData::GetInitRain(), SceneData::GetInitTime(), SceneData::GetNameMission(), SceneData::GetNameScene(), SceneData::GetSceneObjects(), SceneObject::GetTypeName(), Print(), and string::ToString().
Field Documentation
FILE_ROOT
private const string FILE_ROOT = "$saves:" private
Definition at line 20 of file PluginLocalProfileScene.c.
FILE_ROOT_SCENES
private const string FILE_ROOT_SCENES = "Scenes" private
Definition at line 21 of file PluginLocalProfileScene.c.
Referenced by GetPathScenes().
m_FileSceneName
private string m_FileSceneName private
Definition at line 29 of file PluginLocalProfileScene.c.
Referenced by GetFileName().
PARAM_FOG
private const string PARAM_FOG = "InitWeatherFog" private
Definition at line 25 of file PluginLocalProfileScene.c.
PARAM_MISSION
private const string PARAM_MISSION = "Mission" private
Definition at line 22 of file PluginLocalProfileScene.c.
PARAM_OBJ_COUNT
private const string PARAM_OBJ_COUNT = "SceneObjectsCount" private
Definition at line 26 of file PluginLocalProfileScene.c.
PARAM_OBJ_NAME
private const string PARAM_OBJ_NAME = "SceneObject" private
Definition at line 27 of file PluginLocalProfileScene.c.
PARAM_RAIN
private const string PARAM_RAIN = "InitWeatherRain" private
Definition at line 24 of file PluginLocalProfileScene.c.
PARAM_TIME
private const string PARAM_TIME = "InitTime" private
Definition at line 23 of file PluginLocalProfileScene.c.
The documentation for this class was generated from the following files:
4_World/Plugins/PluginBase/PluginFileHandler/PluginLocalProfile/PluginAdditionalInfo.c
4_World/Plugins/PluginBase/PluginFileHandler/PluginLocalProfile/PluginLocalProfileScene.c