DayZ: LayoutHolder Class Reference
LayoutHolder Class Reference
Private Member Functions
void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void DraggingOver (Widget w, int x, int y, Widget receiver)
void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void UpdateSpacer ()
Header GetHeader ()
void SetHeader (Header header)
void CheckHeaderDragability ()
void Container (LayoutHolder parent)
Container GetFocusedContainer ()
Container GetContainer (int index)
void SetFocusedContainer (Container cont)
SlotsIcon GetFocusedSlotsIcon ()
int GetActiveIndex ()
void SetActiveIndex (int index)
ScrollWidget GetScrollWidget ()
void UpdateRadialIcon ()
void SetSlotIcon (SlotsIcon icon)
void SetDefaultFocus (bool while_micromanagment_mode=false)
void SetLastFocus ()
void Unfocus ()
void MoveGridCursor (int direction)
void ScrollToActiveContainer ()
void CheckScrollbarVisibility ()
void Open ()
void Close ()
bool IsOpened ()
void SetOpenForSlotIcon (bool open, SlotsIcon icon=null)
void Toggle ()
float GetFocusedContainerHeight (bool contents=false)
float GetFocusedContainerYPos (bool contents=false)
float GetFocusedContainerYScreenPos (bool contents=false)
int Count ()
bool SelectItem ()
bool Select ()
bool OnSelectButton ()
bool Combine ()
bool TransferItemToVicinity ()
bool TransferItem ()
bool InspectItem ()
bool SplitItem ()
bool EquipItem ()
bool CanEquip ()
bool CanCombine ()
bool CanCombineAmmo ()
bool IsEmpty ()
bool IsItemActive ()
bool IsItemWithQuantityActive ()
EntityAI GetFocusedItem ()
EntityAI GetFocusedContainerEntity ()
int GetColumnCount ()
void SetColumnCount (int count)
int GetFocusedColumn ()
void SetFocusedColumn (int column)
override void UpdateInterval ()
override void SetLastActive ()
override void SetFirstActive ()
override void SetActive (bool active)
void UnfocusAll ()
void UnfocusGrid ()
bool IsLastIndex ()
bool IsFirstIndex ()
bool IsFirstContainerFocused ()
bool IsLastContainerFocused ()
void ResetFocusedContainer ()
void SetNextActive ()
void SetPreviousActive (bool force=false)
void SetNextRightActive ()
void SetNextLeftActive ()
void RecomputeOpenedContainers ()
override void SetLayoutName ()
void Insert (LayoutHolder container, int pos=-1, bool immedUpdate=true)
void Remove (LayoutHolder container)
LayoutHolder Get (int x)
override void Refresh ()
void UpdateBodySpacers ()
void HideContent (bool force_hide=false)
void ShowContent (bool force_show=false)
void SetForceShow (bool value)
override void UpdateSelectionIcons ()
void ExpandCollapseContainer ()
Private Attributes
protected ref array< ref LayoutHolder > m_Body
protected ref array< LayoutHolder > m_OpenedContainers
protected int m_ActiveIndex = 0
protected bool m_LastIndex
protected bool m_Closed
protected Container m_FocusedContainer
protected float m_PrevAlpha
const int ITEMS_IN_ROW = 8
protected int m_ColumnCount
protected int m_FocusedColumn = 0
protected bool m_ForcedHide
protected bool m_ForcedShow
protected SlotsIcon m_SlotIcon
protected EntityAI m_Entity
const int SORT_ATTACHMENTS_OWN = 1
const int SORT_CARGO_OWN = 2
const int SORT_ATTACHMENTS_NEXT_OFFSET = 2
const int SORT_CARGO_NEXT_OFFSET = 3
Detailed Description
Definition at line 1 of file Container.c.
Member Function Documentation
CanCombine()
bool CanCombine () inline private
Definition at line 379 of file Container.c.
CanCombineAmmo()
bool CanCombineAmmo () inline private
Definition at line 386 of file Container.c.
CanEquip()
bool CanEquip () inline private
Definition at line 372 of file Container.c.
CheckHeaderDragability()
void CheckHeaderDragability () private
CheckScrollbarVisibility()
void CheckScrollbarVisibility () inline private
Definition at line 184 of file Container.c.
Close()
void Close () inline private
Definition at line 206 of file Container.c.
Combine()
bool Combine () inline private
Definition at line 330 of file Container.c.
Container()
void Container (LayoutHolder parent) inline private
Definition at line 35 of file Container.c.
References m_IsActive, and m_RootWidget.
Count()
int Count () inline private
Definition at line 302 of file Container.c.
Referenced by PluginBase::Broadcast(), PluginBase::BroadcastFloat(), PluginBase::BroadcastInt(), PluginBase::BroadcastParam(), PluginBase::BroadcastString(), Container::Get(), and PluginRecipesManagerBase::MatchItems().
DraggingOver()
void DraggingOver (Widget w, int x, int y, Widget receiver) private
DraggingOverHeader()
void DraggingOverHeader (Widget w, int x, int y, Widget receiver) private
EquipItem()
bool EquipItem () inline private
Definition at line 365 of file Container.c.
ExpandCollapseContainer()
void ExpandCollapseContainer () inline private
Definition at line 898 of file Container.c.
Get()
LayoutHolder Get (int x) inline private
Definition at line 832 of file Container.c.
References Get(), and x.
Referenced by PluginBase::Broadcast(), PluginBase::BroadcastFloat(), PluginBase::BroadcastInt(), PluginBase::BroadcastParam(), PluginBase::BroadcastString(), Container::Get(), Get(), Container::GetIcon(), Container::ReleaseLock(), and Container::SplitItem().
GetActiveIndex()
int GetActiveIndex () inline private
Definition at line 82 of file Container.c.
GetColumnCount()
int GetColumnCount () inline private
Definition at line 429 of file Container.c.
GetContainer()
Container GetContainer (int index) inline private
Definition at line 57 of file Container.c.
GetFocusedColumn()
int GetFocusedColumn () inline private
Definition at line 439 of file Container.c.
GetFocusedContainer()
Container GetFocusedContainer () inline private
Definition at line 48 of file Container.c.
GetFocusedContainerEntity()
EntityAI GetFocusedContainerEntity () inline private
Definition at line 421 of file Container.c.
GetFocusedContainerHeight()
float GetFocusedContainerHeight (bool contents = false) inline private
Definition at line 248 of file Container.c.
References GetFocusedContainerHeight(), Container::GetHeader(), x, and y.
Referenced by Container::GetFocusedContainerHeight(), and GetFocusedContainerHeight().
GetFocusedContainerYPos()
float GetFocusedContainerYPos (bool contents = false) inline private
Definition at line 269 of file Container.c.
References GetFocusedContainerYPos(), x, and y.
Referenced by Container::GetFocusedContainerYPos(), and GetFocusedContainerYPos().
GetFocusedContainerYScreenPos()
float GetFocusedContainerYScreenPos (bool contents = false) inline private
Definition at line 280 of file Container.c.
References GetFocusedContainerYScreenPos(), Container::GetHeader(), x, and y.
Referenced by Container::GetFocusedContainerYScreenPos(), and GetFocusedContainerYScreenPos().
GetFocusedItem()
EntityAI GetFocusedItem () inline private
Definition at line 412 of file Container.c.
GetFocusedSlotsIcon()
SlotsIcon GetFocusedSlotsIcon () inline private
Definition at line 72 of file Container.c.
GetHeader()
Header GetHeader () private
GetScrollWidget()
ScrollWidget GetScrollWidget () inline private
Definition at line 92 of file Container.c.
HideContent()
void HideContent (bool force_hide = false) inline private
Definition at line 860 of file Container.c.
Insert()
void Insert (LayoutHolder container, int pos = -1, bool immedUpdate = true) inline private
Definition at line 787 of file Container.c.
References Container::Refresh().
Referenced by ClosableContainer::RecomputeContainers().
InspectItem()
bool InspectItem () inline private
Definition at line 351 of file Container.c.
Referenced by Icon::MouseClick().
IsEmpty()
bool IsEmpty () inline private
Definition at line 393 of file Container.c.
IsFirstContainerFocused()
bool IsFirstContainerFocused () inline private
Definition at line 613 of file Container.c.
IsFirstIndex()
bool IsFirstIndex () inline private
Definition at line 608 of file Container.c.
IsItemActive()
bool IsItemActive () inline private
Definition at line 398 of file Container.c.
IsItemWithQuantityActive()
bool IsItemWithQuantityActive () inline private
Definition at line 405 of file Container.c.
IsLastContainerFocused()
bool IsLastContainerFocused () inline private
Definition at line 618 of file Container.c.
IsLastIndex()
bool IsLastIndex () inline private
Definition at line 603 of file Container.c.
IsOpened()
bool IsOpened () inline private
Definition at line 212 of file Container.c.
MoveGridCursor()
void MoveGridCursor (int direction) inline private
Definition at line 129 of file Container.c.
References Inventory(), Container::SetNextActive(), Container::SetNextLeftActive(), Container::SetNextRightActive(), and Container::SetPreviousActive().
OnDropReceivedFromHeader()
void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) private
OnSelectButton()
bool OnSelectButton () inline private
Definition at line 321 of file Container.c.
Open()
void Open () inline private
Definition at line 200 of file Container.c.
RecomputeOpenedContainers()
void RecomputeOpenedContainers () inline private
Definition at line 734 of file Container.c.
References IsActive(), Container::IsDisplayable(), and Container::SetActive().
Refresh()
override void Refresh () inline private
Definition at line 837 of file Container.c.
Remove()
void Remove (LayoutHolder container) inline private
Definition at line 802 of file Container.c.
References Container::Refresh(), and Container::SetPreviousActive().
Referenced by ClosableContainer::AttachmentRemoved(), and Container::ReleaseLock().
ResetFocusedContainer()
void ResetFocusedContainer () inline private
Definition at line 623 of file Container.c.
ScrollToActiveContainer()
void ScrollToActiveContainer () inline private
Definition at line 153 of file Container.c.
References Container::GetFocusedContainerHeight(), Container::GetFocusedContainerYScreenPos(), x, and y.
Select()
bool Select () inline private
Definition at line 314 of file Container.c.
SelectItem()
bool SelectItem () inline private
Definition at line 307 of file Container.c.
SetActive()
override void SetActive (bool active) inline private
Definition at line 534 of file Container.c.
References Container::GetHeader(), m_IsActive, Container::SetActive(), Header::SetActive(), Container::SetDefaultFocus(), and Container::Unfocus().
SetActiveIndex()
void SetActiveIndex (int index) inline private
Definition at line 87 of file Container.c.
SetColumnCount()
void SetColumnCount (int count) inline private
Definition at line 434 of file Container.c.
SetDefaultFocus()
void SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 110 of file Container.c.
SetFirstActive()
override void SetFirstActive () inline private
Definition at line 504 of file Container.c.
References IsActive(), m_IsActive, SetActive(), and Container::SetDefaultFocus().
SetFocusedColumn()
void SetFocusedColumn (int column) inline private
Definition at line 444 of file Container.c.
SetFocusedContainer()
void SetFocusedContainer (Container cont) inline private
Definition at line 67 of file Container.c.
SetForceShow()
void SetForceShow (bool value) inline private
Definition at line 888 of file Container.c.
SetHeader()
void SetHeader (Header header) private
SetLastActive()
override void SetLastActive () inline private
Definition at line 460 of file Container.c.
References Container::GetHeader(), IsActive(), m_IsActive, Header::SetActive(), Container::SetLastActive(), and Container::SetLastFocus().
SetLastFocus()
void SetLastFocus () inline private
Definition at line 115 of file Container.c.
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 782 of file Container.c.
References WidgetLayoutName::Container.
Referenced by ScriptedWidgetEventHandler::LayoutHolder().
SetNextActive()
void SetNextActive () inline private
Definition at line 633 of file Container.c.
References GetParent(), SetActive(), Container::SetActive(), and Container::SetNextActive().
SetNextLeftActive()
void SetNextLeftActive () inline private
Definition at line 719 of file Container.c.
References Container::SetNextLeftActive().
SetNextRightActive()
void SetNextRightActive () inline private
Definition at line 705 of file Container.c.
References Container::SetNextRightActive().
SetOpenForSlotIcon()
void SetOpenForSlotIcon (bool open, SlotsIcon icon = null) inline private
Definition at line 217 of file Container.c.
References SlotsIcon::GetRadialIcon().
SetPreviousActive()
void SetPreviousActive (bool force = false) inline private
Definition at line 669 of file Container.c.
References GetParent(), SetActive(), Container::SetLastActive(), and Container::SetPreviousActive().
SetSlotIcon()
void SetSlotIcon (SlotsIcon icon) inline private
Definition at line 105 of file Container.c.
ShowContent()
void ShowContent (bool force_show = false) inline private
Definition at line 873 of file Container.c.
SplitItem()
bool SplitItem () inline private
Definition at line 358 of file Container.c.
Toggle()
void Toggle () inline private
Definition at line 235 of file Container.c.
References Container::Close(), IsOpened(), and Container::Open().
TransferItem()
bool TransferItem () inline private
Definition at line 344 of file Container.c.
TransferItemToVicinity()
bool TransferItemToVicinity () inline private
Definition at line 337 of file Container.c.
Unfocus()
void Unfocus () inline private
Definition at line 125 of file Container.c.
UnfocusAll()
void UnfocusAll () inline private
Definition at line 582 of file Container.c.
References Count, Get(), and ITEMS_IN_ROW.
UnfocusGrid()
void UnfocusGrid () inline private
Definition at line 594 of file Container.c.
UpdateBodySpacers()
void UpdateBodySpacers () inline private
Definition at line 846 of file Container.c.
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 449 of file Container.c.
References Container::CheckHeaderDragability().
UpdateRadialIcon()
void UpdateRadialIcon () inline private
Definition at line 97 of file Container.c.
References SlotsIcon::GetRadialIconPanel().
UpdateSelectionIcons()
override void UpdateSelectionIcons () inline private
Definition at line 893 of file Container.c.
References m_Parent.
UpdateSpacer()
void UpdateSpacer () private
Field Documentation
ITEMS_IN_ROW
const int ITEMS_IN_ROW = 8 private
Definition at line 10 of file Container.c.
m_ActiveIndex
protected int m_ActiveIndex = 0 private
Definition at line 5 of file Container.c.
m_Body
protected ref array<ref LayoutHolder> m_Body private
Definition at line 3 of file Container.c.
m_Closed
protected bool m_Closed private
Definition at line 7 of file Container.c.
m_ColumnCount
protected int m_ColumnCount private
Definition at line 13 of file Container.c.
m_Entity
protected EntityAI m_Entity private
Definition at line 20 of file Container.c.
m_FocusedColumn
protected int m_FocusedColumn = 0 private
Definition at line 15 of file Container.c.
m_FocusedContainer
protected Container m_FocusedContainer private
Definition at line 8 of file Container.c.
m_ForcedHide
protected bool m_ForcedHide private
Definition at line 16 of file Container.c.
m_ForcedShow
protected bool m_ForcedShow private
Definition at line 17 of file Container.c.
m_LastIndex
protected bool m_LastIndex private
Definition at line 6 of file Container.c.
m_OpenedContainers
protected ref array<LayoutHolder> m_OpenedContainers private
Definition at line 4 of file Container.c.
m_PrevAlpha
protected float m_PrevAlpha private
Definition at line 9 of file Container.c.
m_SlotIcon
protected SlotsIcon m_SlotIcon private
Definition at line 19 of file Container.c.
SORT_ATTACHMENTS_NEXT_OFFSET
const int SORT_ATTACHMENTS_NEXT_OFFSET = 2 private
Definition at line 24 of file Container.c.
SORT_ATTACHMENTS_OWN
const int SORT_ATTACHMENTS_OWN = 1 private
Definition at line 22 of file Container.c.
SORT_CARGO_NEXT_OFFSET
const int SORT_CARGO_NEXT_OFFSET = 3 private
Definition at line 25 of file Container.c.
SORT_CARGO_OWN
const int SORT_CARGO_OWN = 2 private
Definition at line 23 of file Container.c.
The documentation for this class was generated from the following file:
5_Mission/GUI/InventoryNew/Containers/Container.c