DayZ: OverheatingParticle Class Reference
OverheatingParticle Class Reference
Private Member Functions
void RegisterParticle (Particle p)
Particle GetParticle ()
void SetOverheatingLimitMin (float min)
void SetOverheatingLimitMax (float max)
float GetOverheatingLimitMin ()
float GetOverheatingLimitMax ()
void SetParticleParams (int particle_id, Object parent, vector local_pos, vector local_ori)
int GetParticleID ()
Object GetParticleParent ()
vector GetParticlePos ()
vector GetParticleOri ()
Private Attributes
Particle m_Particle
int m_ParticleID
Object m_Parent
vector m_LocalPos
vector m_LocalOri
float m_OverheatingLimitMin
float m_OverheatingLimitMax
Detailed Description
Definition at line 381 of file WeaponParticles.c.
Member Function Documentation
GetOverheatingLimitMax()
float GetOverheatingLimitMax () inline private
Definition at line 417 of file WeaponParticles.c.
References m_OverheatingLimitMax.
Referenced by InventoryItem::UpdateAllOverheatingParticles().
GetOverheatingLimitMin()
float GetOverheatingLimitMin () inline private
Definition at line 412 of file WeaponParticles.c.
References m_OverheatingLimitMin.
Referenced by InventoryItem::UpdateAllOverheatingParticles().
GetParticle()
Particle GetParticle () inline private
Definition at line 397 of file WeaponParticles.c.
References m_Particle.
Referenced by InventoryItem::KillAllOverheatingParticles(), and InventoryItem::UpdateAllOverheatingParticles().
GetParticleID()
int GetParticleID () inline private
Definition at line 430 of file WeaponParticles.c.
References m_ParticleID.
GetParticleOri()
vector GetParticleOri () inline private
Definition at line 445 of file WeaponParticles.c.
References m_LocalOri.
GetParticleParent()
Object GetParticleParent () inline private
Definition at line 435 of file WeaponParticles.c.
References m_Parent.
GetParticlePos()
vector GetParticlePos () inline private
Definition at line 440 of file WeaponParticles.c.
References m_LocalPos.
RegisterParticle()
void RegisterParticle (Particle p) inline private
Definition at line 392 of file WeaponParticles.c.
References m_Particle.
Referenced by InventoryItem::RegisterOverheatingParticle(), and InventoryItem::UpdateAllOverheatingParticles().
SetOverheatingLimitMax()
void SetOverheatingLimitMax (float max) inline private
Definition at line 407 of file WeaponParticles.c.
References m_OverheatingLimitMax.
Referenced by InventoryItem::RegisterOverheatingParticle().
SetOverheatingLimitMin()
void SetOverheatingLimitMin (float min) inline private
Definition at line 402 of file WeaponParticles.c.
References m_OverheatingLimitMin.
Referenced by InventoryItem::RegisterOverheatingParticle().
SetParticleParams()
void SetParticleParams (int particle_id, Object parent, vector local_pos, vector local_ori) inline private
Definition at line 422 of file WeaponParticles.c.
References m_LocalOri, m_LocalPos, m_Parent, m_ParticleID, and particle_id.
Referenced by InventoryItem::RegisterOverheatingParticle().
Field Documentation
m_LocalOri
vector m_LocalOri private
Definition at line 387 of file WeaponParticles.c.
Referenced by GetParticleOri(), and SetParticleParams().
m_LocalPos
vector m_LocalPos private
Definition at line 386 of file WeaponParticles.c.
Referenced by GetParticlePos(), and SetParticleParams().
m_OverheatingLimitMax
float m_OverheatingLimitMax private
Definition at line 390 of file WeaponParticles.c.
Referenced by GetOverheatingLimitMax(), and SetOverheatingLimitMax().
m_OverheatingLimitMin
float m_OverheatingLimitMin private
Definition at line 389 of file WeaponParticles.c.
Referenced by GetOverheatingLimitMin(), and SetOverheatingLimitMin().
m_Parent
Object m_Parent private
Definition at line 385 of file WeaponParticles.c.
Referenced by GetParticleParent(), and SetParticleParams().
m_Particle
Particle m_Particle private
Definition at line 383 of file WeaponParticles.c.
Referenced by GetParticle(), and RegisterParticle().
m_ParticleID
int m_ParticleID private
Definition at line 384 of file WeaponParticles.c.
Referenced by GetParticleID(), and SetParticleParams().
The documentation for this class was generated from the following file:
4_World/Entities/WeaponParticles.c