DayZ: TentBase Class Reference
TentBase Class Reference
Private Member Functions
void CarTent ()
override void EEInit ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override string GetSoundOpen ()
override string GetSoundClose ()
override bool HasClutterCutter ()
override bool IsDeployable ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
void MediumTent ()
override void EEInit ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override string GetSoundOpen ()
override string GetSoundClose ()
override bool HasClutterCutter ()
override string GetClutterCutter ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
void PartyTent ()
override string GetSoundOpen ()
override string GetSoundClose ()
override string GetSoundOpenWindow ()
override string GetSoundCloseWindow ()
override bool HasClutterCutter ()
override string GetClutterCutter ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override void HandleCamoNetAttachment (bool hide)
override void AnimateCamonetToggle (ToggleAnimations toggle)
override void AnimateCamonetByOpeningSelection (string opening_selection)
void ShelterBase ()
override void SetActions ()
override void EEInit ()
void Deconstruct ()
string GetMaterialPath ()
string GetShelterVariant ()
void SpawnKit ()
override bool IsPlayerInside (PlayerBase player, string selection)
Static Private Attributes
static const string SITE_OBJECT_TYPE = "ShelterSite"
Detailed Description
Definition at line 1 of file CarTent.c.
Member Function Documentation
AnimateCamonetByOpeningSelection()
override void AnimateCamonetByOpeningSelection (string opening_selection) inline private
Definition at line 143 of file PartyTent.c.
References string::Substring().
Referenced by ItemBase::EEHealthLevelChanged().
AnimateCamonetToggle()
override void AnimateCamonetToggle (ToggleAnimations toggle) inline private
Definition at line 129 of file PartyTent.c.
References ToggleAnimations::GetOpeningBit(), ToggleAnimations::GetToggleOff(), ToggleAnimations::GetToggleOn(), and string::Substring().
Referenced by ItemBase::ToggleAnimation().
CarTent()
void CarTent () inline private
Definition at line 3 of file CarTent.c.
References m_HalfExtents, and Vector().
Deconstruct()
void Deconstruct () inline private
Definition at line 32 of file Shelter.c.
References Delete(), GetMaterialPath(), ShelterBase::GetShelterVariant(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), and SpawnKit().
EEInit() [1/3]
override void EEInit () inline private
Definition at line 16 of file CarTent.c.
EEInit() [2/3]
override void EEInit () inline private
Definition at line 16 of file MediumTent.c.
EEInit() [3/3]
override void EEInit () inline private
Definition at line 25 of file Shelter.c.
GetClutterCutter() [1/2]
override string GetClutterCutter () inline private
Definition at line 41 of file MediumTent.c.
Referenced by ItemBase::OnStoreLoad().
GetClutterCutter() [2/2]
override string GetClutterCutter () inline private
Definition at line 51 of file PartyTent.c.
GetDeploySoundset() [1/3]
override string GetDeploySoundset () inline private
Definition at line 50 of file CarTent.c.
GetDeploySoundset() [2/3]
override string GetDeploySoundset () inline private
Definition at line 66 of file MediumTent.c.
GetDeploySoundset() [3/3]
override string GetDeploySoundset () inline private
Definition at line 76 of file PartyTent.c.
GetLoopDeploySoundset() [1/3]
override string GetLoopDeploySoundset () inline private
Definition at line 55 of file CarTent.c.
Referenced by ItemBase::PlayDeployLoopSound().
GetLoopDeploySoundset() [2/3]
override string GetLoopDeploySoundset () inline private
Definition at line 71 of file MediumTent.c.
GetLoopDeploySoundset() [3/3]
override string GetLoopDeploySoundset () inline private
Definition at line 81 of file PartyTent.c.
GetMaterialPath()
string GetMaterialPath () inline private
Definition at line 39 of file Shelter.c.
References CFG_VEHICLESPATH, string::Format(), ShelterBase::GetShelterVariant(), and SITE_OBJECT_TYPE.
GetShelterVariant()
string GetShelterVariant () inline private
Definition at line 44 of file Shelter.c.
GetSoundClose() [1/3]
override string GetSoundClose () inline private
Definition at line 31 of file CarTent.c.
Referenced by ItemBase::SoundTentClosePlay().
GetSoundClose() [2/3]
override string GetSoundClose () inline private
Definition at line 31 of file MediumTent.c.
GetSoundClose() [3/3]
override string GetSoundClose () inline private
Definition at line 31 of file PartyTent.c.
GetSoundCloseWindow()
override string GetSoundCloseWindow () inline private
Definition at line 41 of file PartyTent.c.
Referenced by ItemBase::SoundTentCloseWindowPlay().
GetSoundOpen() [1/3]
override string GetSoundOpen () inline private
Definition at line 26 of file CarTent.c.
Referenced by ItemBase::SoundTentOpenPlay().
GetSoundOpen() [2/3]
override string GetSoundOpen () inline private
Definition at line 26 of file MediumTent.c.
GetSoundOpen() [3/3]
override string GetSoundOpen () inline private
Definition at line 26 of file PartyTent.c.
GetSoundOpenWindow()
override string GetSoundOpenWindow () inline private
Definition at line 36 of file PartyTent.c.
Referenced by ItemBase::SoundTentOpenWindowPlay().
HandleCamoNetAttachment()
override void HandleCamoNetAttachment (bool hide) inline private
Definition at line 86 of file PartyTent.c.
References component, GetHealthLevel(), ToggleAnimations::GetOpeningBit(), ToggleAnimations::GetToggleOff(), ToggleAnimations::GetToggleOn(), GameConstants::STATE_RUINED, and string::Substring().
Referenced by ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), and ItemBase::RefreshAttachements().
HasClutterCutter() [1/3]
override bool HasClutterCutter () inline private
Definition at line 36 of file CarTent.c.
Referenced by ItemBase::OnStoreLoad().
HasClutterCutter() [2/3]
override bool HasClutterCutter () inline private
Definition at line 36 of file MediumTent.c.
HasClutterCutter() [3/3]
override bool HasClutterCutter () inline private
Definition at line 46 of file PartyTent.c.
IsDeployable()
override bool IsDeployable () inline private
Definition at line 45 of file CarTent.c.
IsPlayerInside()
override bool IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 55 of file Shelter.c.
References vector::AnglesToVector(), GetCollisionBox(), GetDirection(), GetPosition, vector::Length(), vector::Normalize(), vector::VectorToAngles(), and x.
MediumTent()
void MediumTent () inline private
Definition at line 3 of file MediumTent.c.
References m_HalfExtents, and Vector().
OnItemLocationChanged() [1/2]
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 21 of file CarTent.c.
OnItemLocationChanged() [2/2]
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 21 of file MediumTent.c.
OnPlacementComplete() [1/2]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 50 of file MediumTent.c.
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), and m_ClutterCutter.
OnPlacementComplete() [2/2]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 60 of file PartyTent.c.
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), and m_ClutterCutter.
PartyTent()
void PartyTent () inline private
Definition at line 3 of file PartyTent.c.
References m_HalfExtents, and Vector().
SetActions()
override void SetActions () inline private
Definition at line 13 of file Shelter.c.
References ActionDeployObject(), ActionPackTent(), AddAction(), and RemoveAction().
ShelterBase()
void ShelterBase () inline private
Definition at line 5 of file Shelter.c.
References m_HalfExtents, and Vector().
SpawnKit()
void SpawnKit () inline private
Definition at line 49 of file Shelter.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetHealth01(), and GetPosition.
Field Documentation
SITE_OBJECT_TYPE
const string SITE_OBJECT_TYPE = "ShelterSite" static private
Definition at line 3 of file Shelter.c.
The documentation for this class was generated from the following files:
4_World/Entities/ItemBase/TentBase/CarTent.c
4_World/Entities/ItemBase/TentBase/Shelter.c
4_World/Entities/ItemBase/TentBase/MediumTent.c
4_World/Entities/ItemBase/TentBase/PartyTent.c