DayZ: CallQueueContext Class Reference
CallQueueContext Class Reference
Tools
Private Member Functions
void CallQueueContext (Class target, string fn, Param params)
void Call ()
void CallParams (Param params)
void Invalidate ()
bool IsValid ()
Private Attributes
Class m_target
string m_function
ref Param m_params
bool m_valid
Detailed Description
Definition at line 15 of file tools.c.
Constructor & Destructor Documentation
CallQueueContext()
void CallQueueContext (Class target, string fn, Param params) inline private
Definition at line 22 of file tools.c.
References m_function, m_params, m_target, and m_valid.
Member Function Documentation
Call()
void Call () inline private
Definition at line 30 of file tools.c.
References CallParams(), and m_params.
Referenced by ScriptedWidgetEventHandler::OnMouseButtonDown(), and array< ref CallQueueContext >::Tick().
CallParams()
void CallParams (Param params) inline private
Definition at line 35 of file tools.c.
References ScriptModule::CallFunction(), ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_function, and m_target.
Referenced by Call(), and CallQueue::Tick().
Invalidate()
void Invalidate () inline private
Definition at line 47 of file tools.c.
References m_valid.
Referenced by array< ref CallQueueContext >::RemoveCalls().
IsValid()
bool IsValid () inline private
Definition at line 51 of file tools.c.
References m_valid.
Referenced by array< ref CallQueueContext >::Tick(), and CallQueue::Tick().
Field Documentation
m_function
string m_function private
Definition at line 18 of file tools.c.
Referenced by CallParams(), and CallQueueContext().
m_params
ref Param m_params private
Definition at line 19 of file tools.c.
Referenced by Call(), and CallQueueContext().
m_target
Class m_target private
Definition at line 17 of file tools.c.
Referenced by CallParams(), CallQueueContext(), and array< ref CallQueueContext >::RemoveCalls().
m_valid
bool m_valid private
Definition at line 20 of file tools.c.
Referenced by CallQueueContext(), Invalidate(), and IsValid().
The documentation for this class was generated from the following file:
3_Game/tools/tools.c