DayZ Scripts Documentation: AITargetCallbacksPlayer Class Reference
AITargetCallbacksPlayer Class Reference
Private Member Functions
void AITargetCallbacksPlayer (PlayerBase pPlayer)
override vector GetHeadPositionWS ()
override vector GetVisionPointPositionWS (EntityAI pApplicant)
override float GetMaxVisionRangeModifier (EntityAI pApplicant)
Static Private Member Functions
static int StanceToMovementIdxTranslation (HumanMovementState pState)
Private Attributes
private PlayerBase m_Player
private int m_iHeadBoneIndex
private int m_iChestBoneIndex
Detailed Description
Definition at line 1 of file AITargetCallbacksPlayer.c.
Constructor & Destructor Documentation
AITargetCallbacksPlayer()
void AITargetCallbacksPlayer (PlayerBase pPlayer) inline private
Definition at line 3 of file AITargetCallbacksPlayer.c.
References m_iChestBoneIndex, m_iHeadBoneIndex, and m_Player.
Member Function Documentation
GetHeadPositionWS()
override vector GetHeadPositionWS () inline private
Definition at line 11 of file AITargetCallbacksPlayer.c.
References m_iHeadBoneIndex, and m_Player.
Referenced by GetVisionPointPositionWS().
GetMaxVisionRangeModifier()
override float GetMaxVisionRangeModifier (EntityAI pApplicant) inline private
player speed mofifications
stance modification
player visibility modification (from cloths)
mean value of the coefs
Definition at line 43 of file AITargetCallbacksPlayer.c.
References PlayerConstants::AI_VISIBILITY_CROUCH, PlayerConstants::AI_VISIBILITY_IDLE, PlayerConstants::AI_VISIBILITY_PRONE, PlayerConstants::AI_VISIBILITY_RUN, PlayerConstants::AI_VISIBILITY_STANDING, PlayerConstants::AI_VISIBILITY_WALK, HumanMovementState::m_iStanceIdx, m_Player, and StanceToMovementIdxTranslation().
GetVisionPointPositionWS()
override vector GetVisionPointPositionWS (EntityAI pApplicant) inline private
Definition at line 19 of file AITargetCallbacksPlayer.c.
References GetHeadPositionWS(), DayZInfectedInputController::GetMindState(), m_iChestBoneIndex, and m_Player.
StanceToMovementIdxTranslation()
static int StanceToMovementIdxTranslation (HumanMovementState pState) inline static private
Translates players speed (idx) and corrects it by current stance used mainly for visibility/audibility of player to AI
Definition at line 90 of file AITargetCallbacksPlayer.c.
References HumanMovementState::m_iMovement, and HumanMovementState::m_iStanceIdx.
Referenced by GetMaxVisionRangeModifier(), GetMovementSpeedVisualCoef(), and NoiseAIEvaluate::GetNoiseMultiplierByPlayerSpeed().
Field Documentation
m_iChestBoneIndex
private int m_iChestBoneIndex private
Definition at line 133 of file AITargetCallbacksPlayer.c.
Referenced by AITargetCallbacksPlayer(), and GetVisionPointPositionWS().
m_iHeadBoneIndex
private int m_iHeadBoneIndex private
Definition at line 132 of file AITargetCallbacksPlayer.c.
Referenced by AITargetCallbacksPlayer(), and GetHeadPositionWS().
m_Player
private PlayerBase m_Player private
Definition at line 131 of file AITargetCallbacksPlayer.c.
Referenced by AITargetCallbacksPlayer(), GetHeadPositionWS(), GetMaxVisionRangeModifier(), and GetVisionPointPositionWS().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ManBase/PlayerBase/AITargetCallbacksPlayer.c