DayZ: IconsContainer Class Reference
IconsContainer Class Reference
Private Member Functions
void IconsContainer (LayoutHolder parent)
override void UnfocusAll ()
int GetItemCount ()
void AddItem (Icon icon)
Icon GetIcon (int entity_id)
Icon GetIconByIndex (int index)
void RemoveItem (Icon icon)
void RemoveItem (int entity)
bool ContainsEntity (EntityAI entity)
void UpdateItemsTemperature ()
override void Refresh ()
Private Attributes
protected ref map< int, ref Icon > m_EntitiesMap = new map<int, ref Icon>
Detailed Description
Definition at line 1 of file IconsContainer.c.
Constructor & Destructor Documentation
IconsContainer()
void IconsContainer (LayoutHolder parent) inline private
Definition at line 5 of file IconsContainer.c.
Member Function Documentation
AddItem()
void AddItem (Icon icon) inline private
Definition at line 31 of file IconsContainer.c.
References Icon::GetObject(), and m_EntitiesMap.
ContainsEntity()
bool ContainsEntity (EntityAI entity) inline private
Definition at line 74 of file IconsContainer.c.
References m_EntitiesMap.
GetIcon()
Icon GetIcon (int entity_id) inline private
Definition at line 39 of file IconsContainer.c.
References m_EntitiesMap.
GetIconByIndex()
Icon GetIconByIndex (int index) inline private
Definition at line 44 of file IconsContainer.c.
References m_EntitiesMap.
GetItemCount()
int GetItemCount () inline private
Definition at line 26 of file IconsContainer.c.
References m_EntitiesMap.
Refresh()
override void Refresh () inline private
Definition at line 91 of file IconsContainer.c.
References m_EntitiesMap.
RemoveItem() [1/2]
void RemoveItem (Icon icon) inline private
Definition at line 51 of file IconsContainer.c.
References Icon::GetObject(), and m_EntitiesMap.
RemoveItem() [2/2]
void RemoveItem (int entity) inline private
Definition at line 69 of file IconsContainer.c.
References m_EntitiesMap.
UnfocusAll()
override void UnfocusAll () inline private
Definition at line 9 of file IconsContainer.c.
References Count, Get(), ITEMS_IN_ROW, and m_EntitiesMap.
UpdateItemsTemperature()
void UpdateItemsTemperature () inline private
Definition at line 79 of file IconsContainer.c.
References ItemManager::GetInstance(), ItemManager::IsDragging(), m_EntitiesMap, and Icon::SetTemperature().
Field Documentation
m_EntitiesMap
protected ref map<int, ref Icon> m_EntitiesMap = new map<int, ref Icon> private
Definition at line 3 of file IconsContainer.c.
Referenced by AddItem(), ContainsEntity(), GetIcon(), GetIconByIndex(), GetItemCount(), Refresh(), RemoveItem(), UnfocusAll(), and UpdateItemsTemperature().
The documentation for this class was generated from the following file:
5_Mission/GUI/InventoryNew/Containers/IconsContainer.c