DayZ: PointLightBase Class Reference
PointLightBase Class Reference
Private Member Functions
void Roadblock_Light ()
void BonfireLight ()
override void OnFrameLightSource (IEntity other, float timeSlice)
void BrightnessTestLight ()
override void OnFrameLightSource (IEntity other, float timeSlice)
void ChemlightLight ()
void SetIntensity (float coef, float time)
void SetColorToWhite ()
void SetColorToRed ()
void SetColorToGreen ()
void SetColorToBlue ()
void SetColorToYellow ()
void EntranceLight ()
void FireplaceLight ()
void SetInteriorMode ()
void SetExteriorMode ()
void FlareLight ()
void MuzzleFlashLight ()
void MuzzleFlashLight_2 ()
void PartyLight ()
override void OnFrameLightSource (IEntity other, float timeSlice)
void PersonalLight ()
override void OnFrameLightSource (IEntity other, float timeSlice)
void PortableGasLampLight ()
void RoadflareLight ()
void StoveLight ()
void TorchLight ()
override void OnFrameLightSource (IEntity other, float timeSlice)
void XmasSleighLight ()
void XmasTreeLight ()
void ZombieMummyLight ()
Private Attributes
protected float m_DefaultBrightness = 5.5
protected float m_DefaultRadius = 20
float m_Timer = 0
Static Private Attributes
static float m_FireRadius = 40
static float m_FireBrightness = 15.0
static string m_MemoryPoint = "bonfire_fire"
static private float m_DefaultBrightness = 1.5
static private float m_DefaultRadius = 7.5
static float m_FireplaceRadius = 25
static float m_FireplaceBrightness = 4.75
static float m_FlareRadius = 100
static float m_FlareBrightness = 10.0
static float m_Lifetime = 0.04
static float m_TorchRadius = 15
static float m_TorchBrightness = 5.0
static float m_RoadflareRadius = 30
static float m_RoadflareBrightness = 8.5
Detailed Description
Definition at line 27 of file StaticObj_Roadblock_Wood_Small.c.
Member Function Documentation
BonfireLight()
void BonfireLight () inline private
Definition at line 7 of file BonfireLight.c.
BrightnessTestLight()
void BrightnessTestLight () inline private
Definition at line 7 of file BrightnessTestLight.c.
ChemlightLight()
void ChemlightLight () inline private
Definition at line 6 of file ChemlightLight.c.
References m_DefaultBrightness, and m_DefaultRadius.
EntranceLight()
void EntranceLight () inline private
Definition at line 6 of file EntranceLight.c.
References m_DefaultBrightness, and m_DefaultRadius.
FireplaceLight()
void FireplaceLight () inline private
Definition at line 6 of file FireplaceLight.c.
References SetExteriorMode().
FlareLight()
void FlareLight () inline private
Definition at line 7 of file FlareLight.c.
References m_FlareBrightness, and m_FlareRadius.
MuzzleFlashLight()
void MuzzleFlashLight () inline private
Definition at line 5 of file MuzzleFlashLight.c.
References m_Lifetime.
MuzzleFlashLight_2()
void MuzzleFlashLight_2 () inline private
Definition at line 43 of file MuzzleFlashLight.c.
References m_Lifetime.
OnFrameLightSource() [1/5]
override void OnFrameLightSource (IEntity other, float timeSlice) inline private
Definition at line 23 of file BonfireLight.c.
OnFrameLightSource() [2/5]
override void OnFrameLightSource (IEntity other, float timeSlice) inline private
Definition at line 18 of file BrightnessTestLight.c.
References Math::AbsFloat(), Math::Cos(), m_Timer, and Print().
OnFrameLightSource() [3/5]
override void OnFrameLightSource (IEntity other, float timeSlice) inline private
Definition at line 15 of file PartyLight.c.
References Math::AbsFloat(), Math::Cos(), m_Timer, Math::PI2, Math::Sin(), and Math::Tan().
OnFrameLightSource() [4/5]
override void OnFrameLightSource (IEntity other, float timeSlice) inline private
Definition at line 15 of file PersonalLight.c.
References CGame::GetCurrentCameraPosition(), GetGame(), SetPosition(), and Vector().
OnFrameLightSource() [5/5]
override void OnFrameLightSource (IEntity other, float timeSlice) inline private
Definition at line 25 of file TorchLight.c.
PartyLight()
void PartyLight () inline private
Definition at line 5 of file PartyLight.c.
PersonalLight()
void PersonalLight () inline private
Definition at line 3 of file PersonalLight.c.
PortableGasLampLight()
void PortableGasLampLight () inline private
Definition at line 6 of file PortableGasLampLight.c.
Roadblock_Light()
void Roadblock_Light () inline private
Definition at line 32 of file StaticObj_Roadblock_Wood_Small.c.
References m_DefaultBrightness, and m_DefaultRadius.
RoadflareLight()
void RoadflareLight () inline private
Definition at line 7 of file RoadflareLight.c.
SetColorToBlue()
void SetColorToBlue () inline private
Definition at line 40 of file ChemlightLight.c.
SetColorToGreen()
void SetColorToGreen () inline private
Definition at line 34 of file ChemlightLight.c.
SetColorToRed()
void SetColorToRed () inline private
Definition at line 28 of file ChemlightLight.c.
Referenced by Headtorch_Black::OnLightCreated().
SetColorToWhite()
void SetColorToWhite () inline private
Definition at line 22 of file ChemlightLight.c.
Referenced by Clothing::OnLightCreated().
SetColorToYellow()
void SetColorToYellow () inline private
Definition at line 46 of file ChemlightLight.c.
SetExteriorMode()
void SetExteriorMode () inline private
Definition at line 32 of file FireplaceLight.c.
Referenced by FireplaceLight().
SetIntensity()
void SetIntensity (float coef, float time) inline private
Definition at line 16 of file ChemlightLight.c.
References m_DefaultBrightness, and m_DefaultRadius.
Referenced by Clothing::OnWork(), ItemBase::OnWork(), and Switchable_Base::OnWork().
SetInteriorMode()
void SetInteriorMode () inline private
Definition at line 25 of file FireplaceLight.c.
StoveLight()
void StoveLight () inline private
Definition at line 3 of file StoveLight.c.
TorchLight()
void TorchLight () inline private
Definition at line 6 of file TorchLight.c.
XmasSleighLight()
void XmasSleighLight () inline private
Definition at line 3 of file XmasSleighLight.c.
XmasTreeLight()
void XmasTreeLight () inline private
Definition at line 3 of file XmasTreeLight.c.
ZombieMummyLight()
void ZombieMummyLight () inline private
Definition at line 3 of file ZombieMummyLight.c.
Field Documentation
m_DefaultBrightness [1/2]
protected float m_DefaultBrightness = 5.5 private
Definition at line 29 of file StaticObj_Roadblock_Wood_Small.c.
m_DefaultBrightness [2/2]
private float m_DefaultBrightness = 1.5 static private
Definition at line 3 of file ChemlightLight.c.
m_DefaultRadius [1/2]
protected float m_DefaultRadius = 20 private
Definition at line 30 of file StaticObj_Roadblock_Wood_Small.c.
m_DefaultRadius [2/2]
private float m_DefaultRadius = 7.5 static private
Definition at line 4 of file ChemlightLight.c.
m_FireBrightness
float m_FireBrightness = 15.0 static private
Definition at line 4 of file BonfireLight.c.
Referenced by BuildingSuper::EEInit().
m_FireplaceBrightness
float m_FireplaceBrightness = 4.75 static private
Definition at line 4 of file FireplaceLight.c.
m_FireplaceRadius
float m_FireplaceRadius = 25 static private
Definition at line 3 of file FireplaceLight.c.
m_FireRadius
float m_FireRadius = 40 static private
Definition at line 3 of file BonfireLight.c.
Referenced by BuildingSuper::EEInit().
m_FlareBrightness
float m_FlareBrightness = 10.0 static private
Definition at line 4 of file FlareLight.c.
m_FlareRadius
float m_FlareRadius = 100 static private
Definition at line 3 of file FlareLight.c.
m_Lifetime
static float m_Lifetime = 0.04 static private
Definition at line 3 of file MuzzleFlashLight.c.
m_MemoryPoint
static string m_MemoryPoint = "bonfire_fire" static private
Definition at line 5 of file BonfireLight.c.
Referenced by BuildingSuper::EEInit().
m_RoadflareBrightness
float m_RoadflareBrightness = 8.5 static private
Definition at line 4 of file RoadflareLight.c.
m_RoadflareRadius
float m_RoadflareRadius = 30 static private
Definition at line 3 of file RoadflareLight.c.
m_Timer
float m_Timer = 0 private
Definition at line 5 of file BrightnessTestLight.c.
m_TorchBrightness
static float m_TorchBrightness = 5.0 static private
Definition at line 4 of file PortableGasLampLight.c.
m_TorchRadius
static float m_TorchRadius = 15 static private
Definition at line 3 of file PortableGasLampLight.c.
The documentation for this class was generated from the following files:
4_World/Entities/Building/Wrecks/StaticObj_Roadblock_Wood_Small.c
4_World/Entities/ScriptedLightBase/PointLightBase/BonfireLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/BrightnessTestLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/ChemlightLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/EntranceLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/FireplaceLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/FlareLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/MuzzleFlashLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/PartyLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/PortableGasLampLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/RoadflareLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/TorchLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/PersonalLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/StoveLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/XmasSleighLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/XmasTreeLight.c
4_World/Entities/ScriptedLightBase/PointLightBase/ZombieMummyLight.c