DayZ Scripts Documentation: InventoryActionHandler Class Reference
InventoryActionHandler Class Reference
Client only - manage set up crafting on client.
Private Member Functions
void InventoryActionHandler (PlayerBase player)
void SetAction (ActionBase action, ItemBase target_item, ItemBase main_item)
void SetAction (ActionBase action, ActionTarget target, ItemBase main_item)
bool IsActiveAction ()
void OnUpdate ()
void DeactiveAction ()
Private Attributes
ActionBase m_action
ActionTarget m_target
ItemBase m_mainItem
bool m_useItemInHands
PlayerBase m_player
bool m_isActive
vector m_actionStartPos
const float MIN_DISTANCE_TO_INTERRUPT = 1.0
const int IAH_SINGLE_USE = 1
const int IAH_CONTINUOUS = 2
Detailed Description
Client only - manage set up crafting on client.
Definition at line 2 of file InventoryActionHandler.c.
Constructor & Destructor Documentation
InventoryActionHandler()
void InventoryActionHandler (PlayerBase player) inline private
Definition at line 19 of file InventoryActionHandler.c.
References m_action, m_isActive, m_mainItem, m_player, m_target, and m_useItemInHands.
Member Function Documentation
DeactiveAction()
void DeactiveAction () inline private
Definition at line 105 of file InventoryActionHandler.c.
References Class::CastTo(), ActionManagerClient::ClearForceTarget(), ActionManagerClient::EjectAction(), m_action, m_isActive, m_mainItem, m_player, m_target, and m_useItemInHands.
Referenced by ActionManagerClient::OnActionEnd(), OnUpdate(), and ActionManagerClient::UnsetInventoryAction().
IsActiveAction()
bool IsActiveAction () inline private
Definition at line 63 of file InventoryActionHandler.c.
References m_isActive.
OnUpdate()
void OnUpdate () inline private
Definition at line 68 of file InventoryActionHandler.c.
References Math::AbsFloat(), DeactiveAction(), vector::Distance(), GetGame(), IsInventoryOpen(), m_actionStartPos, m_isActive, m_mainItem, m_player, m_useItemInHands, and MIN_DISTANCE_TO_INTERRUPT.
Referenced by ActionManagerClient::Update().
SetAction() [1/2]
void SetAction (ActionBase action, ActionTarget target, ItemBase main_item) inline private
Definition at line 42 of file InventoryActionHandler.c.
References Class::CastTo(), ActionManagerClient::ForceTarget(), GetGame(), CGame::GetMission(), Mission::HideInventory(), m_action, m_actionStartPos, m_isActive, m_mainItem, m_player, m_target, and m_useItemInHands.
SetAction() [2/2]
void SetAction (ActionBase action, ItemBase target_item, ItemBase main_item) inline private
Definition at line 30 of file InventoryActionHandler.c.
References ActionTarget, SetAction(), and vector::Zero.
Referenced by SetAction(), and ActionManagerClient::SetInventoryAction().
Field Documentation
IAH_CONTINUOUS
const int IAH_CONTINUOUS = 2 private
Definition at line 16 of file InventoryActionHandler.c.
IAH_SINGLE_USE
const int IAH_SINGLE_USE = 1 private
Definition at line 15 of file InventoryActionHandler.c.
m_action
ActionBase m_action private
Definition at line 4 of file InventoryActionHandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), and SetAction().
m_actionStartPos
vector m_actionStartPos private
Definition at line 12 of file InventoryActionHandler.c.
Referenced by OnUpdate(), and SetAction().
m_isActive
bool m_isActive private
Definition at line 11 of file InventoryActionHandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), IsActiveAction(), OnUpdate(), and SetAction().
m_mainItem
ItemBase m_mainItem private
Definition at line 6 of file InventoryActionHandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), OnUpdate(), and SetAction().
m_player
PlayerBase m_player private
Definition at line 9 of file InventoryActionHandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), OnUpdate(), and SetAction().
m_target
ActionTarget m_target private
Definition at line 5 of file InventoryActionHandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), and SetAction().
m_useItemInHands
bool m_useItemInHands private
Definition at line 7 of file InventoryActionHandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), OnUpdate(), and SetAction().
MIN_DISTANCE_TO_INTERRUPT
const float MIN_DISTANCE_TO_INTERRUPT = 1.0 private
Definition at line 14 of file InventoryActionHandler.c.
Referenced by OnUpdate().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/InventoryActionHandler.c