DayZ Scripts: DropEquipAndDestroyRootLambda Class Reference
DropEquipAndDestroyRootLambda Class Reference
this one is a bit special: it drops all items and destroys the ex-root of the hierarchy
Private Member Functions
void DropEquipAndDestroyRootLambda (EntityAI old_item, string new_item_type, PlayerBase player)
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
Private Attributes
PlayerBase m_Player
Detailed Description
this one is a bit special: it drops all items and destroys the ex-root of the hierarchy
Definition at line 115 of file MiscGameplayFunctions.c.
Constructor & Destructor Documentation
DropEquipAndDestroyRootLambda()
void DropEquipAndDestroyRootLambda (EntityAI old_item, string new_item_type, PlayerBase player) inline private
Definition at line 119 of file MiscGameplayFunctions.c.
References m_Player.
Member Function Documentation
CopyOldPropertiesToNew()
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item) inline private
Definition at line 124 of file MiscGameplayFunctions.c.
References GetGame(), ReplaceItemWithNewLambdaBase::m_NewLocation, m_Player, Math3D::MatrixIdentity4(), GameInventory::PrepareDropEntityPos(), CGame::RemoteObjectTreeCreate(), and InventoryLocation::SetGround().
Field Documentation
m_Player
PlayerBase m_Player private
Definition at line 117 of file MiscGameplayFunctions.c.
Referenced by CopyOldPropertiesToNew(), and DropEquipAndDestroyRootLambda().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/MiscGameplayFunctions.c