DayZ Scripts: BleedingCheckMdfr Class Reference
BleedingCheckMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
protected const float BLOOD_DECREMENT_PER_SEC = -10
PluginAdminLog m_AdminLog
Detailed Description
Definition at line 2 of file Bleeding.c.
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
Definition at line 22 of file Bleeding.c.
References PlayerConstants::BLOOD_THRESHOLD_FATAL.
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
Definition at line 49 of file Bleeding.c.
Init()
override void Init () inline private
Definition at line 7 of file Bleeding.c.
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, DisableDeactivateCheck(), GetGame(), GetPlugin(), m_AdminLog, m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void OnActivate (PlayerBase player) inline private
Definition at line 34 of file Bleeding.c.
References m_AdminLog.
OnDeactivate()
override void OnDeactivate (PlayerBase player) inline private
Definition at line 44 of file Bleeding.c.
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
Definition at line 54 of file Bleeding.c.
Field Documentation
BLOOD_DECREMENT_PER_SEC
protected const float BLOOD_DECREMENT_PER_SEC = -10 private
Definition at line 4 of file Bleeding.c.
m_AdminLog
PluginAdminLog m_AdminLog private
Definition at line 5 of file Bleeding.c.
Referenced by Init(), and OnActivate().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/conditions/Bleeding.c