DayZ: Chemlight_ColorBase Class Reference
Chemlight_ColorBase Class Reference
Private Member Functions
float GetEfficiency0To1 ()
Returns efficiency. The value is synchronized from server to all clients and is accurate down to 0.1 units.
float GetEfficiencyDecayStart ()
Returns efficiency. The value is synchronized from server to all clients and is accurate down to 0.1 units.
override void OnEnergyConsumed ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
void Chemlight_ColorBase ()
void CreateLight ()
override void OnWorkStart ()
override void OnInventoryExit (Man player)
void StandUp ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
override void SetActions ()
string GetMaterialForDamageState (bool glowing, int healthLevel=-1)
Private Attributes
string m_DefaultMaterial
string m_GlowMaterial
ChemlightLight m_Light
private int m_Efficiency0To10
Static Private Attributes
static private float m_EfficiencyDecayStart = 0.05
Detailed Description
Definition at line 1 of file ChemLight.c.
Constructor & Destructor Documentation
Chemlight_ColorBase()
void Chemlight_ColorBase () inline private
Definition at line 46 of file ChemLight.c.
References Error(), GetHiddenSelectionsMaterials(), GetType(), m_DefaultMaterial, m_Efficiency0To10, and m_GlowMaterial.
Member Function Documentation
CreateLight()
void CreateLight () inline private
Definition at line 66 of file ChemLight.c.
References GetGame(), GetMaterialForDamageState(), GetType(), and m_Light.
Referenced by OnWork().
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 39 of file ChemLight.c.
References GetMaterialForDamageState().
GetEfficiency0To1()
float GetEfficiency0To1 () inline private
Returns efficiency. The value is synchronized from server to all clients and is accurate down to 0.1 units.
Definition at line 12 of file ChemLight.c.
References m_Efficiency0To10.
Referenced by OnWork().
GetEfficiencyDecayStart()
float GetEfficiencyDecayStart () inline private
Returns efficiency. The value is synchronized from server to all clients and is accurate down to 0.1 units.
Definition at line 18 of file ChemLight.c.
References m_EfficiencyDecayStart.
GetMaterialForDamageState()
string GetMaterialForDamageState (bool glowing, int healthLevel = -1) inline private
Definition at line 165 of file ChemLight.c.
References Error(), GetHealthLevel(), string::IndexOf(), m_DefaultMaterial, m_GlowMaterial, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and string::Substring().
Referenced by CreateLight(), EEHealthLevelChanged(), and OnWorkStop().
OnEnergyConsumed()
override void OnEnergyConsumed () inline private
Definition at line 23 of file ChemLight.c.
References GetGame(), m_Efficiency0To10, m_EfficiencyDecayStart, and Math::Round().
OnInventoryExit()
override void OnInventoryExit (Man player) inline private
Definition at line 106 of file ChemLight.c.
References StandUp().
OnWork()
override void OnWork (float consumed_energy) inline private
Definition at line 141 of file ChemLight.c.
References CreateLight(), GetEfficiency0To1(), and m_Light.
OnWorkStart()
override void OnWorkStart () inline private
Definition at line 100 of file ChemLight.c.
OnWorkStop()
override void OnWorkStop () inline private
Definition at line 122 of file ChemLight.c.
References GetEnergy(), GetGame(), GetMaterialForDamageState(), m_Light, and SetHealth().
SetActions()
override void SetActions () inline private
Definition at line 158 of file ChemLight.c.
References AddAction().
StandUp()
void StandUp () inline private
Definition at line 113 of file ChemLight.c.
References GetGame(), and SetOrientation().
Referenced by OnInventoryExit().
Field Documentation
m_DefaultMaterial
string m_DefaultMaterial private
Definition at line 3 of file ChemLight.c.
Referenced by Chemlight_ColorBase(), and GetMaterialForDamageState().
m_Efficiency0To10
private int m_Efficiency0To10 private
Definition at line 8 of file ChemLight.c.
Referenced by Chemlight_ColorBase(), GetEfficiency0To1(), and OnEnergyConsumed().
m_EfficiencyDecayStart
private float m_EfficiencyDecayStart = 0.05 static private
Definition at line 9 of file ChemLight.c.
Referenced by GetEfficiencyDecayStart(), and OnEnergyConsumed().
m_GlowMaterial
string m_GlowMaterial private
Definition at line 4 of file ChemLight.c.
Referenced by Chemlight_ColorBase(), and GetMaterialForDamageState().
m_Light
ChemlightLight m_Light private
Definition at line 6 of file ChemLight.c.
Referenced by CreateLight(), OnWork(), and OnWorkStop().
The documentation for this class was generated from the following file:
4_World/Entities/ItemBase/ChemLight.c