DayZ: DestructionEffectBase Class Reference
DestructionEffectBase Class Reference
Private Member Functions
void ~DestructionEffectBase ()
private void Init ()
bool HasExplosionDamage ()
private void DealExplosionDamage ()
void OnHealthLevelChanged (notnull EntityAI entity, int oldLevel, int newLevel, string zone)
private void ReplaceEntityServer ()
private ParticleSource PlayParticle (int particleType, bool attach=false)
void OnEntityDestroyedOneTimeClient (EntityAI entity, int oldLevel, string zone)
void OnEntityDestroyedOneTimeServer (EntityAI entity, int oldLevel, string zone)
void OnEntityDestroyedPersistentClient (EntityAI entity, string zone)
void OnEntityDestroyedPersistentServer (EntityAI entity, string zone)
void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
Private Attributes
EntityAI m_Entity
bool m_EntityIsTakeable
ParticleSource m_POneTime
ParticleSource m_PPersistent
int m_ParticleOneTime
int m_ParticlePersistent
EffectSound m_SOneTime
EffectSound m_SPersistent
string m_SoundSetOneTime
string m_SoundSetPersistent
bool m_KeepHealthOnReplace
string m_ReplaceWithEntity
int m_ReplaceDelay
bool m_HasExplosionDamage
DamageType m_DamageType
string m_AmmoType
Detailed Description
Definition at line 1 of file DestructionEffectBase.c.
Constructor & Destructor Documentation
~DestructionEffectBase()
void ~DestructionEffectBase () inline private
Definition at line 28 of file DestructionEffectBase.c.
References SEffectManager::DestroyEffect(), m_POneTime, m_PPersistent, m_SOneTime, m_SPersistent, and Particle::Stop().
Member Function Documentation
DealExplosionDamage()
private void DealExplosionDamage () inline private
Definition at line 50 of file DestructionEffectBase.c.
References m_AmmoType, m_DamageType, and m_Entity.
Referenced by OnHealthLevelChanged().
HasExplosionDamage()
bool HasExplosionDamage () inline private
Definition at line 45 of file DestructionEffectBase.c.
References m_AmmoType, and m_HasExplosionDamage.
Referenced by OnHealthLevelChanged().
Init()
private void Init () private
Referenced by OnHealthLevelChanged().
OnEntityDestroyedOneTimeClient()
void OnEntityDestroyedOneTimeClient (EntityAI entity, int oldLevel, string zone) private
Referenced by OnHealthLevelChanged().
OnEntityDestroyedOneTimeServer()
void OnEntityDestroyedOneTimeServer (EntityAI entity, int oldLevel, string zone) private
Referenced by OnHealthLevelChanged().
OnEntityDestroyedPersistentClient()
void OnEntityDestroyedPersistentClient (EntityAI entity, string zone) private
Referenced by OnHealthLevelChanged().
OnEntityDestroyedPersistentServer()
void OnEntityDestroyedPersistentServer (EntityAI entity, string zone) private
Referenced by OnHealthLevelChanged().
OnExplosionEffects()
void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) private
OnHealthLevelChanged()
void OnHealthLevelChanged (notnull EntityAI entity, int oldLevel, int newLevel, string zone) inline private
Definition at line 55 of file DestructionEffectBase.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), DealExplosionDamage(), CGame::GetCallQueue(), GetGame(), HasExplosionDamage(), Init(), m_Entity, m_EntityIsTakeable, m_ParticleOneTime, m_ParticlePersistent, m_POneTime, m_PPersistent, m_ReplaceDelay, m_ReplaceWithEntity, m_SOneTime, m_SoundSetOneTime, m_SoundSetPersistent, m_SPersistent, OnEntityDestroyedOneTimeClient(), OnEntityDestroyedOneTimeServer(), OnEntityDestroyedPersistentClient(), OnEntityDestroyedPersistentServer(), PlayParticle(), ReplaceEntityServer(), and ParticleSource::SetOwner().
PlayParticle()
private ParticleSource PlayParticle (int particleType, bool attach = false) inline private
Definition at line 121 of file DestructionEffectBase.c.
References ParticleSource::AddAsChild(), ErrorEx, m_Entity, and ParticleManager().
Referenced by OnHealthLevelChanged().
ReplaceEntityServer()
private void ReplaceEntityServer () inline private
Definition at line 110 of file DestructionEffectBase.c.
References ECE_OBJECT_SWAP, GetGame(), m_Entity, m_KeepHealthOnReplace, m_ReplaceWithEntity, and RF_ORIGINAL.
Referenced by OnHealthLevelChanged().
Field Documentation
m_AmmoType
string m_AmmoType private
Definition at line 25 of file DestructionEffectBase.c.
Referenced by DealExplosionDamage(), HasExplosionDamage(), and DestructionEffectGasCanister::Init().
m_DamageType
DamageType m_DamageType private
Definition at line 24 of file DestructionEffectBase.c.
Referenced by DealExplosionDamage(), and DestructionEffectGasCanister::Init().
m_Entity
EntityAI m_Entity private
Definition at line 3 of file DestructionEffectBase.c.
Referenced by DealExplosionDamage(), OnHealthLevelChanged(), PlayParticle(), and ReplaceEntityServer().
m_EntityIsTakeable
bool m_EntityIsTakeable private
Definition at line 5 of file DestructionEffectBase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_HasExplosionDamage
bool m_HasExplosionDamage private
Definition at line 23 of file DestructionEffectBase.c.
Referenced by HasExplosionDamage(), and DestructionEffectGasCanister::Init().
m_KeepHealthOnReplace
bool m_KeepHealthOnReplace private
Definition at line 19 of file DestructionEffectBase.c.
Referenced by DestructionEffectGasCanister::Init(), and ReplaceEntityServer().
m_ParticleOneTime
int m_ParticleOneTime private
Definition at line 10 of file DestructionEffectBase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_ParticlePersistent
int m_ParticlePersistent private
Definition at line 11 of file DestructionEffectBase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_POneTime
ParticleSource m_POneTime private
Definition at line 7 of file DestructionEffectBase.c.
Referenced by OnHealthLevelChanged(), and ~DestructionEffectBase().
m_PPersistent
ParticleSource m_PPersistent private
Definition at line 8 of file DestructionEffectBase.c.
Referenced by OnHealthLevelChanged(), and ~DestructionEffectBase().
m_ReplaceDelay
int m_ReplaceDelay private
Definition at line 21 of file DestructionEffectBase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_ReplaceWithEntity
string m_ReplaceWithEntity private
Definition at line 20 of file DestructionEffectBase.c.
Referenced by DestructionEffectGasCanister::Init(), OnHealthLevelChanged(), and ReplaceEntityServer().
m_SOneTime
EffectSound m_SOneTime private
Definition at line 13 of file DestructionEffectBase.c.
Referenced by OnHealthLevelChanged(), and ~DestructionEffectBase().
m_SoundSetOneTime
string m_SoundSetOneTime private
Definition at line 16 of file DestructionEffectBase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_SoundSetPersistent
string m_SoundSetPersistent private
Definition at line 17 of file DestructionEffectBase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_SPersistent
EffectSound m_SPersistent private
Definition at line 14 of file DestructionEffectBase.c.
Referenced by OnHealthLevelChanged(), and ~DestructionEffectBase().
The documentation for this class was generated from the following file:
3_Game/Effects/DestructionEffects/DestructionEffectBase.c