DayZ: ActionMineBase Class Reference
ActionMineBase Class Reference
Private Member Functions
override ActionData CreateActionData ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
string GetYieldName (PlayerBase player, ActionTarget target, ItemBase item)
Private Attributes
EHarvestType m_HarvestType = EHarvestType.NORMAL
Detailed Description
Definition at line 16 of file ActionMineTree.c.
Member Function Documentation
CreateActionData()
override ActionData CreateActionData () inline private
Definition at line 20 of file ActionMineTree.c.
References MineActionData::m_HarvestType, and m_HarvestType.
GetYieldName()
string GetYieldName (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file ActionMineTree.c.
References RockBase::GetMaterialAndQuantityMap(), m_HarvestType, and WoodBase().
Referenced by OnActionInfoUpdate().
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 27 of file ActionMineTree.c.
References GetYieldName(), and m_Text.
Field Documentation
m_HarvestType
EHarvestType m_HarvestType = EHarvestType.NORMAL private
Definition at line 18 of file ActionMineTree.c.
Referenced by CreateActionData(), and GetYieldName().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Continuous/ActionMineTree.c