DayZ Scripts Documentation: LifespanLevel Class Reference
LifespanLevel Class Reference
Private Member Functions
void LifespanLevel (int level, float threshold, string texture_name, string material_name)
int GetLevel ()
float GetThreshold ()
string GetTextureName ()
string GetMaterialName ()
Private Attributes
protected int m_Level
protected float m_Threshold
protected string m_TextureName
protected string m_MaterialName
Detailed Description
Definition at line 1 of file LifespanLevel.c.
Constructor & Destructor Documentation
LifespanLevel()
void LifespanLevel (int level, float threshold, string texture_name, string material_name) inline private
Definition at line 9 of file LifespanLevel.c.
References m_Level, m_MaterialName, m_TextureName, and m_Threshold.
Member Function Documentation
GetLevel()
int GetLevel () inline private
Definition at line 17 of file LifespanLevel.c.
References m_Level.
Referenced by SetPlayerLifespanLevel().
GetMaterialName()
string GetMaterialName () inline private
Definition at line 32 of file LifespanLevel.c.
References m_MaterialName.
Referenced by GetCurrentHeadMaterial(), and SetPlayerLifespanLevel().
GetTextureName()
string GetTextureName () inline private
Definition at line 27 of file LifespanLevel.c.
References m_TextureName.
Referenced by GetCurrentHeadTexture(), and SetPlayerLifespanLevel().
GetThreshold()
float GetThreshold () inline private
Definition at line 22 of file LifespanLevel.c.
References m_Threshold.
Referenced by GetLifespanLevel(), and UpdateLifespanLevel().
Field Documentation
m_Level
protected int m_Level private
Definition at line 3 of file LifespanLevel.c.
Referenced by GetLevel(), and LifespanLevel().
m_MaterialName
protected string m_MaterialName private
Definition at line 6 of file LifespanLevel.c.
Referenced by GetMaterialName(), and LifespanLevel().
m_TextureName
protected string m_TextureName private
Definition at line 5 of file LifespanLevel.c.
Referenced by GetTextureName(), and LifespanLevel().
m_Threshold
protected float m_Threshold private
Definition at line 4 of file LifespanLevel.c.
Referenced by GetThreshold(), and LifespanLevel().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/LifespanLevel.c