DayZ: Ammo_40mm_Smoke_ColorBase Class Reference
Ammo_40mm_Smoke_ColorBase Class Reference
Private Member Functions
void Ammo_40mm_Smoke_ColorBase ()
override void OnVariablesSynchronized ()
protected void Activate ()
override void EEKilled (Object killer)
special behaviour - do not call super
override void EEDelete (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override void OnActivatedByItem (notnull ItemBase item)
Private Attributes
protected Particle m_ParticleSmoke
protected float m_ParticleLifetime
protected int m_ParticleId
protected bool m_Activated
Detailed Description
Definition at line 161 of file AmmunitionPiles.c.
Constructor & Destructor Documentation
Ammo_40mm_Smoke_ColorBase()
void Ammo_40mm_Smoke_ColorBase () inline private
Definition at line 168 of file AmmunitionPiles.c.
Member Function Documentation
Activate()
protected void Activate () inline private
Definition at line 191 of file AmmunitionPiles.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::ConfigGetFloat(), CGame::GetCallQueue(), GetGame(), GetType(), m_Activated, and m_ParticleLifetime.
Referenced by OnActivatedByItem().
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 219 of file AmmunitionPiles.c.
References m_Activated.
EEDelete()
override void EEDelete (EntityAI parent) inline private
Definition at line 207 of file AmmunitionPiles.c.
References m_ParticleSmoke, and Particle::Stop().
EEKilled()
override void EEKilled (Object killer) inline private
special behaviour - do not call super
Definition at line 201 of file AmmunitionPiles.c.
References CGame::GetAnalyticsServer(), GetGame(), and AnalyticsManagerServer::OnEntityKilled().
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 224 of file AmmunitionPiles.c.
References Activate(), and SetHealth().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Definition at line 173 of file AmmunitionPiles.c.
References CGame::ConfigGetTextOut(), GetGame(), ParticleList::GetParticleIDByName(), GetType(), m_Activated, m_ParticleId, m_ParticleSmoke, ParticleManager(), and Particle::SetWiggle().
Field Documentation
m_Activated
protected bool m_Activated private
Definition at line 166 of file AmmunitionPiles.c.
Referenced by Activate(), CanPutInCargo(), and OnVariablesSynchronized().
m_ParticleId
protected int m_ParticleId private
Definition at line 165 of file AmmunitionPiles.c.
Referenced by OnVariablesSynchronized().
m_ParticleLifetime
protected float m_ParticleLifetime private
Definition at line 164 of file AmmunitionPiles.c.
Referenced by Activate().
m_ParticleSmoke
protected Particle m_ParticleSmoke private
Definition at line 163 of file AmmunitionPiles.c.
Referenced by EEDelete(), and OnVariablesSynchronized().
The documentation for this class was generated from the following file:
4_World/Entities/ItemBase/Magazine/AmmunitionPiles.c