DayZ: CrashBase Class Reference
CrashBase Class Reference
Private Member Functions
void Wreck_Mi8_Crashed ()
void Wreck_SantasSleigh ()
override string GetSoundSet ()
override void EEOnCECreate ()
override void EEDelete (EntityAI parent)
void SpawnRandomDeerLater ()
void SpawnRandomDeers ()
vector RandomizePosition (vector origin)
void Wreck_UH1Y ()
Private Attributes
XmasSleighLight m_SleighLight
int m_MaxDeersAmount = 4
int m_MinDeersAmount = 2
int m_MaxDeersSpawnRange = 25
int m_MinDeersSpawnRange = 5
Detailed Description
Definition at line 2 of file Wreck_MI8.c.
Member Function Documentation
EEDelete()
override void EEDelete (EntityAI parent) inline private
Definition at line 36 of file Wreck_SantasSleigh.c.
References GetGame().
EEOnCECreate()
override void EEOnCECreate () inline private
Definition at line 30 of file Wreck_SantasSleigh.c.
References SpawnRandomDeerLater().
GetSoundSet()
override string GetSoundSet () inline private
Definition at line 25 of file Wreck_SantasSleigh.c.
Referenced by House::EEInit(), and House::RequestSoundEvent().
RandomizePosition()
vector RandomizePosition (vector origin) inline private
Definition at line 72 of file Wreck_SantasSleigh.c.
References Math::RandomIntInclusive().
SpawnRandomDeerLater()
void SpawnRandomDeerLater () inline private
Definition at line 47 of file Wreck_SantasSleigh.c.
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
Referenced by EEOnCECreate().
SpawnRandomDeers()
void SpawnRandomDeers () inline private
Definition at line 54 of file Wreck_SantasSleigh.c.
References GetGame(), GetPosition, m_MaxDeersAmount, Math::RandomIntInclusive(), RandomizePosition(), and Vector().
Wreck_Mi8_Crashed()
void Wreck_Mi8_Crashed () inline private
Definition at line 4 of file Wreck_MI8.c.
References GetGame(), ParticleManager(), ParticleList::SMOKING_HELI_WRECK, and Vector().
Wreck_SantasSleigh()
void Wreck_SantasSleigh () inline private
Definition at line 11 of file Wreck_SantasSleigh.c.
References ParticleList::AURORA_SANTA_WRECK, GetGame(), ParticleManager(), and Vector().
Wreck_UH1Y()
void Wreck_UH1Y () inline private
Definition at line 3 of file Wreck_UH1Y.c.
References GetGame(), ParticleManager(), ParticleList::SMOKING_HELI_WRECK, and Vector().
Field Documentation
m_MaxDeersAmount
int m_MaxDeersAmount = 4 private
Definition at line 6 of file Wreck_SantasSleigh.c.
Referenced by SpawnRandomDeers().
m_MaxDeersSpawnRange
int m_MaxDeersSpawnRange = 25 private
Definition at line 8 of file Wreck_SantasSleigh.c.
m_MinDeersAmount
int m_MinDeersAmount = 2 private
Definition at line 7 of file Wreck_SantasSleigh.c.
m_MinDeersSpawnRange
int m_MinDeersSpawnRange = 5 private
Definition at line 9 of file Wreck_SantasSleigh.c.
m_SleighLight
XmasSleighLight m_SleighLight private
Definition at line 4 of file Wreck_SantasSleigh.c.
The documentation for this class was generated from the following files:
4_World/Entities/Building/Wrecks/Wreck_MI8.c
4_World/Entities/Building/Wrecks/Wreck_SantasSleigh.c
4_World/Entities/Building/Wrecks/Wreck_UH1Y.c