DayZ Scripts: DeferredHandEvent Class Reference
DeferredHandEvent Class Reference
Private Member Functions
void DeferredHandEvent (InventoryMode mode, HandEventBase e)
override bool ReserveInventory (HumanInventory inventory)
override void ClearInventoryReservation (HumanInventory inventory)
Private Attributes
ref HandEventBase m_event
Detailed Description
Definition at line 111 of file DayZPlayerInventory.c.
Constructor & Destructor Documentation
DeferredHandEvent()
void DeferredHandEvent (InventoryMode mode, HandEventBase e) inline private
Definition at line 114 of file DayZPlayerInventory.c.
References m_event, and DeferredEvent::m_mode.
Member Function Documentation
ClearInventoryReservation()
override void ClearInventoryReservation (HumanInventory inventory) inline private
Definition at line 125 of file DayZPlayerInventory.c.
References HandEventBase::ClearInventoryReservation(), and m_event.
Referenced by HandleHandEvent().
ReserveInventory()
override bool ReserveInventory (HumanInventory inventory) inline private
Definition at line 120 of file DayZPlayerInventory.c.
References m_event, and HandEventBase::ReserveInventory().
Referenced by HandleHandEvent().
Field Documentation
m_event
ref HandEventBase m_event private
Definition at line 113 of file DayZPlayerInventory.c.
Referenced by ClearInventoryReservation(), DeferredHandEvent(), HandleHandEvent(), and ReserveInventory().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Systems/Inventory/DayZPlayerInventory.c