DayZ: SymptomBase Class Reference
SymptomBase Class Reference
Private Member Functions
void SymptomBase ()
void ~SymptomBase ()
void Init (SymptomManager manager, PlayerBase player, int uid)
int GetMaxCount ()
int GetUID ()
void OnOwnerKilled ()
bool CanBeInterupted ()
bool IsClientOnly ()
void SetDuration (float duration)
float GetDuration ()
string GetName ()
SymptomManager GetManager ()
int GetType ()
void SetParam (Param p)
bool IsSyncToClient ()
void GetPersistentParams (array< Param > params)
void MakeParamObjectPersistent (Param object)
bool IsPersistent ()
bool IsPrimary ()
PlayerBase GetPlayer ()
int GetPriority ()
bool OnConstructed (SymptomManager manager)
void OnDestructed ()
void Activate ()
void Deactivate ()
bool IsActivated ()
void Update (float deltatime)
void PlayAnimationFB (int animation, int stance_mask, float running_time=-1)
void PlayAnimationADD (int type)
void PlaySound (EPlayerSoundEventID id)
void SyncToClientActivated (int SYMPTOM_id, int uid)
void SyncToClientDeactivated (int SYMPTOM_id, int uid)
void CheckSoundFinished ()
void CheckDestroy ()
SmptAnimMetaBase SpawnAnimMetaObject ()
void RequestDestroy ()
void Destroy ()
void AnimationFinish ()
gets called upon animation Symptom exit
void AnimationPlayFailed ()
void AnimationStart ()
protected void OnAnimationFinish ()
protected void OnAnimationStart ()
protected void OnAnimationPlayFailed ()
void OnInit ()
this is just for the Symptom parameters set-up and is called even if the Symptom doesn't execute, don't put any gameplay code in here
void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
bool CanActivate ()
void OnUpdateClient (PlayerBase player, float deltatime)
gets called every frame
void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
void OnGetActivatedClient (PlayerBase player)
void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
void OnGetDeactivatedClient (PlayerBase player)
override void OnInit ()
bool IsContaminationActive ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnAnimationStart ()
override SmptAnimMetaBase SpawnAnimMetaObject ()
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnInit ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnAnimationPlayFailed ()
override bool CanActivate ()
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override SmptAnimMetaBase SpawnAnimMetaObject ()
override void OnInit ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnAnimationPlayFailed ()
override bool CanActivate ()
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override SmptAnimMetaBase SpawnAnimMetaObject ()
override void OnInit ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnInit ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnAnimationPlayFailed ()
override bool CanActivate ()
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnInit ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnAnimationPlayFailed ()
override bool CanActivate ()
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnInit ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override SmptAnimMetaBase SpawnAnimMetaObject ()
override void OnInit ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
bool IsContaminationActive ()
override void OnAnimationStart ()
override void OnAnimationFinish ()
override bool CanActivate ()
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
override SmptAnimMetaBase SpawnAnimMetaObject ()
override void OnInit ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
override void OnGetDeactivatedServer (PlayerBase player)
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnInit ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
override void OnGetDeactivatedServer (PlayerBase player)
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnInit ()
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
override void OnGetDeactivatedServer (PlayerBase player)
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnInit ()
override void SetParam (Param p)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnGetActivatedServer (PlayerBase player)
override void OnGetDeactivatedServer (PlayerBase player)
override void OnGetActivatedClient (PlayerBase player)
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
Private Attributes
const float MAX_TIME_ACTIVE_SAVEGUARD = 20
int m_Priority
SoundOnVehicle m_SoundObject
bool m_PlayedSound
bool m_IsActivated
PlayerBase m_Player
float m_ServerUpdateInterval = 1
float m_ServerUpdateDelta
bool m_IsTemplate = true
float m_ActivatedTime
int m_ID
int m_UID
bool m_IsClientOnly
bool m_DestroyOnAnimFinish = true
bool m_DestroyRequested = false
int m_SymptomType = -1
bool m_IsPersistent = false
SymptomManager m_Manager
bool m_SyncToClient = false
float m_Duration
bool m_AnimPlayRequested
int m_MaxCount = -1
SymptomCB m_AnimCallback
ref array< Param > m_PersistentParams = new array<Param>
const int COUGH_BLOOD_LOSS = 50
const int BLOOD_LOSS = 250
Material m_MatGauss
const int BLUR_DURATION = 3000
ref Param1< vector > m_Position = new Param1<vector>("0 0 0")
float m_BloodSet
PPERequester_BloodLoss m_RequesterBloodLoss
float m_BlurDuration
float m_BlurStrength
float m_EffectTime
float m_EffectStartTime
float m_Time
protected PPERequester_FeverEffects m_Requester
const float BLUR_STRENGTH_MIN = 0.15
const float BLUR_STRENGTH_MAX = 0.25
const int BLUR_DURATION_TIME_MIN = 1.5
const int BLUR_DURATION_TIME_MAX = 2.5
const int MIN_TIME_BETWEEN_EFFECTS = 25.0
const int MAX_TIME_BETWEEN_EFFECTS = 35.0
int m_ShakeLevel
Detailed Description
Definition at line 1 of file StateBase.c.
Constructor & Destructor Documentation
SymptomBase()
void SymptomBase () inline private
Definition at line 30 of file StateBase.c.
~SymptomBase()
void ~SymptomBase () inline private
Definition at line 34 of file StateBase.c.
Member Function Documentation
Activate()
void Activate () inline private
Definition at line 163 of file StateBase.c.
References GetGame(), GetManager(), GetType(), GetUID(), IsSyncToClient(), m_IsActivated, m_Player, OnGetActivatedClient(), OnGetActivatedServer(), and SyncToClientActivated().
Referenced by SymptomManager::UpdateActiveSymptoms().
AnimationFinish()
void AnimationFinish () inline private
gets called upon animation Symptom exit
Definition at line 308 of file StateBase.c.
References m_DestroyOnAnimFinish, OnAnimationFinish(), and RequestDestroy().
Referenced by AnimationPlayFailed(), and AnimFinished().
AnimationPlayFailed()
void AnimationPlayFailed () inline private
Definition at line 315 of file StateBase.c.
References AnimationFinish(), and OnAnimationPlayFailed().
Referenced by AnimFinished().
AnimationStart()
void AnimationStart () inline private
Definition at line 321 of file StateBase.c.
References OnAnimationStart().
Referenced by SymptomManager::OnAnimationStarted().
CanActivate() [1/6]
bool CanActivate () inline private
Definition at line 336 of file StateBase.c.
CanActivate() [2/6]
override bool CanActivate () inline private
Definition at line 29 of file FreezeState.c.
CanActivate() [3/6]
override bool CanActivate () inline private
Definition at line 29 of file HotState.c.
CanActivate() [4/6]
override bool CanActivate () inline private
Definition at line 29 of file PainHeavyState.c.
CanActivate() [5/6]
override bool CanActivate () inline private
Definition at line 29 of file PainLightState.c.
CanActivate() [6/6]
override bool CanActivate () inline private
Definition at line 61 of file VomitState.c.
References m_Manager.
CanBeInterupted()
bool CanBeInterupted () inline private
Definition at line 64 of file StateBase.c.
References m_AnimPlayRequested.
CheckDestroy()
void CheckDestroy () inline private
Definition at line 277 of file StateBase.c.
References CheckSoundFinished(), Destroy(), IsPrimary(), m_ActivatedTime, m_DestroyRequested, MAX_TIME_ACTIVE_SAVEGUARD, and RequestDestroy().
Referenced by Update().
CheckSoundFinished()
void CheckSoundFinished () inline private
Definition at line 268 of file StateBase.c.
References GetGame(), m_ActivatedTime, m_Duration, m_PlayedSound, and RequestDestroy().
Referenced by CheckDestroy().
Deactivate()
void Deactivate () inline private
Definition at line 184 of file StateBase.c.
References GetGame(), GetType(), GetUID(), IsSyncToClient(), m_IsActivated, m_Player, OnGetDeactivatedClient(), OnGetDeactivatedServer(), and SyncToClientDeactivated().
Referenced by OnDestructed().
Destroy()
void Destroy () inline private
Definition at line 301 of file StateBase.c.
References m_IsTemplate, and OnDestructed().
Referenced by CheckDestroy().
GetDuration()
float GetDuration () inline private
Definition at line 85 of file StateBase.c.
References m_Duration.
GetManager()
SymptomManager GetManager () inline private
Definition at line 95 of file StateBase.c.
References m_Manager.
Referenced by Activate(), and OnDestructed().
GetMaxCount()
int GetMaxCount () inline private
Definition at line 48 of file StateBase.c.
References m_MaxCount.
GetName()
string GetName () inline private
Definition at line 90 of file StateBase.c.
GetPersistentParams()
void GetPersistentParams (array< Param > params) inline private
Definition at line 115 of file StateBase.c.
References m_PersistentParams.
GetPlayer()
PlayerBase GetPlayer () inline private
Definition at line 142 of file StateBase.c.
References m_Player.
Referenced by PlaySound(), SyncToClientActivated(), and SyncToClientDeactivated().
GetPriority()
int GetPriority () inline private
Definition at line 147 of file StateBase.c.
References m_Priority.
GetType()
int GetType () inline private
Definition at line 100 of file StateBase.c.
References m_ID.
Referenced by Activate(), Deactivate(), SymptomManager::OnSymptomExit(), PlayAnimationADD(), PlayAnimationFB(), and SymptomManager::RegisterSymptom().
GetUID()
int GetUID () inline private
Definition at line 53 of file StateBase.c.
References m_UID.
Referenced by Activate(), and Deactivate().
Init()
void Init (SymptomManager manager, PlayerBase player, int uid) inline private
Definition at line 39 of file StateBase.c.
References m_IsTemplate, m_Manager, m_Player, m_UID, and OnInit().
Referenced by SymptomManager::RegisterSymptom(), and SymptomManager::SpawnSymptom().
IsActivated()
bool IsActivated () inline private
Definition at line 203 of file StateBase.c.
References m_IsActivated.
Referenced by OnDestructed().
IsClientOnly()
bool IsClientOnly () inline private
Definition at line 74 of file StateBase.c.
References m_IsClientOnly.
IsContaminationActive() [1/2]
bool IsContaminationActive () inline private
Definition at line 14 of file CoughState.c.
References m_Player.
Referenced by OnAnimationFinish(), OnAnimationStart(), and OnGetActivatedServer().
IsContaminationActive() [2/2]
bool IsContaminationActive () inline private
Definition at line 27 of file VomitState.c.
References m_Player.
IsPersistent()
bool IsPersistent () inline private
Definition at line 130 of file StateBase.c.
References m_IsPersistent.
IsPrimary()
bool IsPrimary () inline private
Definition at line 135 of file StateBase.c.
References m_SymptomType.
Referenced by CheckDestroy(), and SymptomManager::OnSymptomExit().
IsSyncToClient()
bool IsSyncToClient () inline private
Definition at line 110 of file StateBase.c.
References m_SyncToClient.
Referenced by Activate(), and Deactivate().
MakeParamObjectPersistent()
void MakeParamObjectPersistent (Param object) inline private
Definition at line 123 of file StateBase.c.
References GetGame(), and m_PersistentParams.
Referenced by OnInit().
OnAnimationFinish() [1/2]
protected void OnAnimationFinish () private
Referenced by AnimationFinish().
OnAnimationFinish() [2/2]
override void OnAnimationFinish () inline private
deplete stamina
Definition at line 49 of file VomitState.c.
References GetPlugin(), IsContaminationActive(), m_Player, and PluginLifespan().
OnAnimationPlayFailed() [1/5]
protected void OnAnimationPlayFailed () private
Referenced by AnimationPlayFailed().
OnAnimationPlayFailed() [2/5]
override void OnAnimationPlayFailed () inline private
Definition at line 24 of file FreezeState.c.
OnAnimationPlayFailed() [3/5]
override void OnAnimationPlayFailed () inline private
Definition at line 24 of file HotState.c.
OnAnimationPlayFailed() [4/5]
override void OnAnimationPlayFailed () inline private
Definition at line 24 of file PainHeavyState.c.
OnAnimationPlayFailed() [5/5]
override void OnAnimationPlayFailed () inline private
Definition at line 24 of file PainLightState.c.
OnAnimationStart() [1/3]
protected void OnAnimationStart () private
Referenced by AnimationStart().
OnAnimationStart() [2/3]
override void OnAnimationStart () inline private
Definition at line 30 of file CoughState.c.
References GetPlugin(), IsContaminationActive(), m_Player, and PluginLifespan().
OnAnimationStart() [3/3]
override void OnAnimationStart () inline private
Definition at line 32 of file VomitState.c.
References IsContaminationActive(), and m_Player.
OnConstructed()
bool OnConstructed (SymptomManager manager) inline private
Definition at line 152 of file StateBase.c.
OnDestructed()
void OnDestructed () inline private
Definition at line 157 of file StateBase.c.
References Deactivate(), GetManager(), IsActivated(), m_Manager, m_UID, and SymptomManager::OnSymptomExit().
Referenced by Destroy().
OnGetActivatedClient() [1/12]
void OnGetActivatedClient (PlayerBase player) private
Referenced by Activate().
OnGetActivatedClient() [2/12]
override void OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 63 of file CoughState.c.
OnGetActivatedClient() [3/12]
override void OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 53 of file FreezeState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [4/12]
override void OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 53 of file HotState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [5/12]
override void OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 34 of file LaughterState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [6/12]
override void OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 44 of file PainHeavyState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [7/12]
override void OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 44 of file PainLightState.c.
References LogManager::IsSymptomLogEnable(), m_Player, CachedObjectsParams::PARAM2_FLOAT_FLOAT, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [8/12]
override void OnGetActivatedClient (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 39 of file SneezeState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [9/12]
override void OnGetActivatedClient (PlayerBase player) inline private
Definition at line 35 of file BlindnessState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [10/12]
override void OnGetActivatedClient (PlayerBase player) inline private
Definition at line 53 of file BloodLoss.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [11/12]
override void OnGetActivatedClient (PlayerBase player) inline private
Definition at line 79 of file FeverBlurState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [12/12]
override void OnGetActivatedClient (PlayerBase player) inline private
Definition at line 45 of file HandShivers.c.
OnGetActivatedServer() [1/13]
void OnGetActivatedServer (PlayerBase player) private
gets called once on an Symptom which is being activated
Referenced by Activate().
OnGetActivatedServer() [2/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 46 of file CoughState.c.
References IsContaminationActive(), m_Manager, PlayAnimationADD(), and PlaySound().
OnGetActivatedServer() [3/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 35 of file FreezeState.c.
References LogManager::IsSymptomLogEnable(), HumanMovementState::m_iMovement, m_Manager, m_Player, PlayAnimationADD(), PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [4/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 35 of file HotState.c.
References LogManager::IsSymptomLogEnable(), HumanMovementState::m_iMovement, m_Manager, m_Player, PlayAnimationADD(), PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [5/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 26 of file LaughterState.c.
References LogManager::IsSymptomLogEnable(), m_Player, PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [6/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 35 of file PainHeavyState.c.
References LogManager::IsSymptomLogEnable(), m_Player, PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [7/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 35 of file PainLightState.c.
References LogManager::IsSymptomLogEnable(), m_Player, PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [8/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 24 of file SneezeState.c.
References LogManager::IsSymptomLogEnable(), m_Manager, m_Player, PlayAnimationADD(), PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [9/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 67 of file VomitState.c.
References GetDuration(), and PlayAnimationFB().
OnGetActivatedServer() [10/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 30 of file BlindnessState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [11/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 48 of file BloodLoss.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [12/13]
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 74 of file FeverBlurState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [13/13]
override void OnGetActivatedServer (PlayerBase player) inline private
Definition at line 35 of file HandShivers.c.
OnGetDeactivatedClient() [1/13]
void OnGetDeactivatedClient (PlayerBase player) private
Referenced by Deactivate().
OnGetDeactivatedClient() [2/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 75 of file CoughState.c.
OnGetDeactivatedClient() [3/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 65 of file FreezeState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [4/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 65 of file HotState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [5/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 46 of file LaughterState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [6/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 58 of file PainHeavyState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [7/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 60 of file PainLightState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [8/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 52 of file SneezeState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [9/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
Definition at line 80 of file VomitState.c.
OnGetDeactivatedClient() [10/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 46 of file BlindnessState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [11/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 64 of file BloodLoss.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [12/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 90 of file FeverBlurState.c.
References LogManager::IsSymptomLogEnable(), m_Player, m_Requester, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [13/13]
override void OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 52 of file HandShivers.c.
OnGetDeactivatedServer() [1/13]
void OnGetDeactivatedServer (PlayerBase player) private
only gets called once on an active Symptom that is being deactivated
Referenced by Deactivate().
OnGetDeactivatedServer() [2/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 69 of file CoughState.c.
OnGetDeactivatedServer() [3/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 59 of file FreezeState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [4/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 59 of file HotState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [5/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 40 of file LaughterState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [6/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 52 of file PainHeavyState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [7/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 54 of file PainLightState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [8/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 46 of file SneezeState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [9/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 75 of file VomitState.c.
OnGetDeactivatedServer() [10/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
Definition at line 40 of file BlindnessState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [11/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
Definition at line 58 of file BloodLoss.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [12/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
Definition at line 84 of file FeverBlurState.c.
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [13/13]
override void OnGetDeactivatedServer (PlayerBase player) inline private
Definition at line 40 of file HandShivers.c.
OnInit() [1/13]
void OnInit () private
this is just for the Symptom parameters set-up and is called even if the Symptom doesn't execute, don't put any gameplay code in here
Referenced by Init().
OnInit() [2/13]
override void OnInit () inline private
Definition at line 5 of file CoughState.c.
References m_ID, m_Priority, and m_SymptomType.
OnInit() [3/13]
override void OnInit () inline private
Definition at line 4 of file FreezeState.c.
References m_ID, m_Priority, and m_SymptomType.
OnInit() [4/13]
override void OnInit () inline private
Definition at line 4 of file HotState.c.
References m_ID, m_Priority, and m_SymptomType.
OnInit() [5/13]
override void OnInit () inline private
Definition at line 4 of file LaughterState.c.
References m_Duration, m_ID, m_Priority, and m_SymptomType.
OnInit() [6/13]
override void OnInit () inline private
Definition at line 4 of file PainHeavyState.c.
References m_Duration, m_ID, m_Priority, and m_SymptomType.
OnInit() [7/13]
override void OnInit () inline private
Definition at line 4 of file PainLightState.c.
References m_Duration, m_ID, m_Priority, and m_SymptomType.
OnInit() [8/13]
override void OnInit () inline private
Definition at line 4 of file SneezeState.c.
References m_ID, m_Priority, and m_SymptomType.
OnInit() [9/13]
override void OnInit () inline private
Definition at line 5 of file VomitState.c.
References m_Duration, m_ID, m_Priority, and m_SymptomType.
OnInit() [10/13]
override void OnInit () inline private
Definition at line 8 of file BlindnessState.c.
References m_ID, m_IsPersistent, m_Position, m_Priority, m_SymptomType, and MakeParamObjectPersistent().
OnInit() [11/13]
override void OnInit () inline private
Definition at line 9 of file BloodLoss.c.
References Class::CastTo(), GetGame(), m_ID, m_IsPersistent, m_Priority, and m_SymptomType.
OnInit() [12/13]
override void OnInit () inline private
Definition at line 22 of file FeverBlurState.c.
References Class::CastTo(), GetGame(), m_ID, m_IsPersistent, m_Priority, m_Requester, and m_SymptomType.
OnInit() [13/13]
override void OnInit () inline private
Definition at line 6 of file HandShivers.c.
References m_ID, m_Priority, and m_SymptomType.
OnOwnerKilled()
void OnOwnerKilled () inline private
Definition at line 58 of file StateBase.c.
OnUpdateClient() [1/13]
void OnUpdateClient (PlayerBase player, float deltatime) private
gets called every frame
Referenced by Update().
OnUpdateClient() [2/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 26 of file CoughState.c.
OnUpdateClient() [3/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 20 of file FreezeState.c.
OnUpdateClient() [4/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 20 of file HotState.c.
OnUpdateClient() [5/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 20 of file LaughterState.c.
OnUpdateClient() [6/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 20 of file PainHeavyState.c.
OnUpdateClient() [7/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 20 of file PainLightState.c.
OnUpdateClient() [8/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 19 of file SneezeState.c.
OnUpdateClient() [9/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 22 of file VomitState.c.
OnUpdateClient() [10/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 23 of file BlindnessState.c.
OnUpdateClient() [11/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 31 of file BloodLoss.c.
OnUpdateClient() [12/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 44 of file FeverBlurState.c.
References m_BlurDuration, m_BlurStrength, m_Requester, m_Time, Math::PI, Math::RandomFloat(), Math::RandomFloatInclusive(), and Math::Sin().
OnUpdateClient() [13/13]
override void OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 30 of file HandShivers.c.
OnUpdateServer() [1/12]
void OnUpdateServer (PlayerBase player, float deltatime) private
gets called every frame
Referenced by Update().
OnUpdateServer() [2/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 21 of file CoughState.c.
OnUpdateServer() [3/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 15 of file FreezeState.c.
OnUpdateServer() [4/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 15 of file HotState.c.
OnUpdateServer() [5/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 15 of file LaughterState.c.
OnUpdateServer() [6/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 15 of file PainHeavyState.c.
OnUpdateServer() [7/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 15 of file PainLightState.c.
OnUpdateServer() [8/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 14 of file SneezeState.c.
OnUpdateServer() [9/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 17 of file VomitState.c.
OnUpdateServer() [10/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 19 of file BlindnessState.c.
OnUpdateServer() [11/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 27 of file BloodLoss.c.
OnUpdateServer() [12/12]
override void OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 38 of file FeverBlurState.c.
PlayAnimationADD()
void PlayAnimationADD (int type) inline private
Definition at line 239 of file StateBase.c.
References GetType(), m_AnimPlayRequested, m_Player, and DayZPlayerSyncJunctures::SendPlayerSymptomADD().
Referenced by OnGetActivatedServer().
PlayAnimationFB()
void PlayAnimationFB (int animation, int stance_mask, float running_time = -1) inline private
Definition at line 233 of file StateBase.c.
References GetType(), m_AnimPlayRequested, m_Player, and DayZPlayerSyncJunctures::SendPlayerSymptomFB().
Referenced by OnGetActivatedServer().
PlaySound()
void PlaySound (EPlayerSoundEventID id) inline private
Definition at line 245 of file StateBase.c.
References GetPlayer(), and m_PlayedSound.
RequestDestroy()
void RequestDestroy () inline private
Definition at line 295 of file StateBase.c.
References m_DestroyRequested.
Referenced by AnimationFinish(), CheckDestroy(), and CheckSoundFinished().
SetDuration()
void SetDuration (float duration) inline private
Definition at line 80 of file StateBase.c.
References m_Duration.
Referenced by PoisoningMdfr::OnTick(), CholeraMdfr::OnTick(), SalmonellaMdfr::OnTick(), and ToxicityMdfr::OnTick().
SetParam() [1/2]
void SetParam (Param p) inline private
Definition at line 105 of file StateBase.c.
Referenced by WoundInfectStage2Mdfr::OnActivate().
SetParam() [2/2]
override void SetParam (Param p) inline private
Definition at line 15 of file HandShivers.c.
SpawnAnimMetaObject() [1/6]
SmptAnimMetaBase SpawnAnimMetaObject () inline private
Definition at line 289 of file StateBase.c.
SpawnAnimMetaObject() [2/6]
override SmptAnimMetaBase SpawnAnimMetaObject () inline private
Definition at line 40 of file CoughState.c.
SpawnAnimMetaObject() [3/6]
override SmptAnimMetaBase SpawnAnimMetaObject () inline private
Definition at line 70 of file FreezeState.c.
SpawnAnimMetaObject() [4/6]
override SmptAnimMetaBase SpawnAnimMetaObject () inline private
Definition at line 70 of file HotState.c.
SpawnAnimMetaObject() [5/6]
override SmptAnimMetaBase SpawnAnimMetaObject () inline private
Definition at line 57 of file SneezeState.c.
SpawnAnimMetaObject() [6/6]
override SmptAnimMetaBase SpawnAnimMetaObject () inline private
Definition at line 85 of file VomitState.c.
SyncToClientActivated()
void SyncToClientActivated (int SYMPTOM_id, int uid) inline private
Definition at line 251 of file StateBase.c.
References GetGame(), GetPlayer(), CachedObjectsParams::PARAM2_INT_INT, and CGame::RPCSingleParam().
Referenced by Activate().
SyncToClientDeactivated()
void SyncToClientDeactivated (int SYMPTOM_id, int uid) inline private
Definition at line 260 of file StateBase.c.
References GetGame(), GetPlayer(), CachedObjectsParams::PARAM2_INT_INT, and CGame::RPCSingleParam().
Referenced by Deactivate().
Update()
void Update (float deltatime) inline private
Definition at line 210 of file StateBase.c.
References CheckDestroy(), GetGame(), m_ActivatedTime, m_Player, m_ServerUpdateDelta, m_ServerUpdateInterval, OnUpdateClient(), and OnUpdateServer().
Referenced by SymptomManager::UpdateActiveSymptoms().
Field Documentation
BLOOD_LOSS
const int BLOOD_LOSS = 250 private
Definition at line 4 of file VomitState.c.
BLUR_DURATION
const int BLUR_DURATION = 3000 private
Definition at line 4 of file BlindnessState.c.
BLUR_DURATION_TIME_MAX
const int BLUR_DURATION_TIME_MAX = 2.5 private
Definition at line 16 of file FeverBlurState.c.
BLUR_DURATION_TIME_MIN
const int BLUR_DURATION_TIME_MIN = 1.5 private
Definition at line 15 of file FeverBlurState.c.
BLUR_STRENGTH_MAX
const float BLUR_STRENGTH_MAX = 0.25 private
Definition at line 13 of file FeverBlurState.c.
BLUR_STRENGTH_MIN
const float BLUR_STRENGTH_MIN = 0.15 private
Definition at line 12 of file FeverBlurState.c.
COUGH_BLOOD_LOSS
const int COUGH_BLOOD_LOSS = 50 private
Definition at line 3 of file CoughState.c.
m_ActivatedTime
float m_ActivatedTime private
Definition at line 12 of file StateBase.c.
Referenced by CheckDestroy(), CheckSoundFinished(), and Update().
m_AnimCallback
SymptomCB m_AnimCallback private
Definition at line 26 of file StateBase.c.
m_AnimPlayRequested
bool m_AnimPlayRequested private
Definition at line 23 of file StateBase.c.
Referenced by CanBeInterupted(), PlayAnimationADD(), and PlayAnimationFB().
m_BloodSet
float m_BloodSet private
Definition at line 5 of file BloodLoss.c.
m_BlurDuration
float m_BlurDuration private
Definition at line 5 of file FeverBlurState.c.
Referenced by OnUpdateClient().
m_BlurStrength
float m_BlurStrength private
Definition at line 6 of file FeverBlurState.c.
Referenced by OnUpdateClient().
m_DestroyOnAnimFinish
bool m_DestroyOnAnimFinish = true private
Definition at line 16 of file StateBase.c.
Referenced by AnimationFinish().
m_DestroyRequested
bool m_DestroyRequested = false private
Definition at line 17 of file StateBase.c.
Referenced by CheckDestroy(), and RequestDestroy().
m_Duration
float m_Duration private
Definition at line 22 of file StateBase.c.
Referenced by CheckSoundFinished(), GetDuration(), and SetDuration().
m_EffectStartTime
float m_EffectStartTime private
Definition at line 8 of file FeverBlurState.c.
m_EffectTime
float m_EffectTime private
Definition at line 7 of file FeverBlurState.c.
m_ID
int m_ID private
Definition at line 13 of file StateBase.c.
Referenced by GetType().
m_IsActivated
bool m_IsActivated private
Definition at line 7 of file StateBase.c.
Referenced by Activate(), Deactivate(), and IsActivated().
m_IsClientOnly
bool m_IsClientOnly private
Definition at line 15 of file StateBase.c.
Referenced by IsClientOnly().
m_IsPersistent
bool m_IsPersistent = false private
Definition at line 19 of file StateBase.c.
Referenced by IsPersistent().
m_IsTemplate
bool m_IsTemplate = true private
Definition at line 11 of file StateBase.c.
Referenced by Destroy(), and Init().
m_Manager
SymptomManager m_Manager private
Definition at line 20 of file StateBase.c.
Referenced by GetManager(), Init(), and OnDestructed().
m_MatGauss
Material m_MatGauss private
Definition at line 3 of file BlindnessState.c.
m_MaxCount
int m_MaxCount = -1 private
Definition at line 24 of file StateBase.c.
Referenced by GetMaxCount().
m_PersistentParams
ref array<Param> m_PersistentParams = new array<Param> private
Definition at line 28 of file StateBase.c.
Referenced by GetPersistentParams(), and MakeParamObjectPersistent().
m_PlayedSound
bool m_PlayedSound private
Definition at line 6 of file StateBase.c.
Referenced by CheckSoundFinished(), and PlaySound().
m_Player
PlayerBase m_Player private
Definition at line 8 of file StateBase.c.
Referenced by Activate(), Deactivate(), GetPlayer(), Init(), PlayAnimationADD(), PlayAnimationFB(), and Update().
m_Position
ref Param1<vector> m_Position = new Param1<vector>("0 0 0") private
Definition at line 5 of file BlindnessState.c.
m_Priority
int m_Priority private
Definition at line 4 of file StateBase.c.
Referenced by GetPriority().
m_Requester
protected PPERequester_FeverEffects m_Requester private
Definition at line 10 of file FeverBlurState.c.
m_RequesterBloodLoss
PPERequester_BloodLoss m_RequesterBloodLoss private
Definition at line 6 of file BloodLoss.c.
m_ServerUpdateDelta
float m_ServerUpdateDelta private
Definition at line 10 of file StateBase.c.
Referenced by Update().
m_ServerUpdateInterval
float m_ServerUpdateInterval = 1 private
Definition at line 9 of file StateBase.c.
Referenced by Update().
m_ShakeLevel
int m_ShakeLevel private
Definition at line 4 of file HandShivers.c.
m_SoundObject
SoundOnVehicle m_SoundObject private
Definition at line 5 of file StateBase.c.
m_SymptomType
int m_SymptomType = -1 private
Definition at line 18 of file StateBase.c.
Referenced by IsPrimary().
m_SyncToClient
bool m_SyncToClient = false private
Definition at line 21 of file StateBase.c.
Referenced by IsSyncToClient().
m_Time
float m_Time private
Definition at line 9 of file FeverBlurState.c.
m_UID
int m_UID private
Definition at line 14 of file StateBase.c.
Referenced by GetUID(), Init(), and OnDestructed().
MAX_TIME_ACTIVE_SAVEGUARD
const float MAX_TIME_ACTIVE_SAVEGUARD = 20 private
Definition at line 3 of file StateBase.c.
Referenced by CheckDestroy().
MAX_TIME_BETWEEN_EFFECTS
const int MAX_TIME_BETWEEN_EFFECTS = 35.0 private
Definition at line 19 of file FeverBlurState.c.
MIN_TIME_BETWEEN_EFFECTS
const int MIN_TIME_BETWEEN_EFFECTS = 25.0 private
Definition at line 18 of file FeverBlurState.c.
The documentation for this class was generated from the following files:
4_World/Classes/PlayerSymptoms/StateBase.c
4_World/Classes/PlayerSymptoms/States/Primary/CoughState.c
4_World/Classes/PlayerSymptoms/States/Primary/VomitState.c
4_World/Classes/PlayerSymptoms/States/Secondary/BlindnessState.c
4_World/Classes/PlayerSymptoms/States/Secondary/BloodLoss.c
4_World/Classes/PlayerSymptoms/States/Secondary/FeverBlurState.c
4_World/Classes/PlayerSymptoms/States/Secondary/HandShivers.c
4_World/Classes/PlayerSymptoms/States/Primary/FreezeState.c
4_World/Classes/PlayerSymptoms/States/Primary/HotState.c
4_World/Classes/PlayerSymptoms/States/Primary/LaughterState.c
4_World/Classes/PlayerSymptoms/States/Primary/PainHeavyState.c
4_World/Classes/PlayerSymptoms/States/Primary/PainLightState.c
4_World/Classes/PlayerSymptoms/States/Primary/SneezeState.c