DayZ: ActionRepackTent Class Reference
ActionRepackTent Class Reference
Private Member Functions
void ActionRepackTent ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool HasProgress ()
override bool ActionConditionContinue (ActionData action_data)
override bool HasAlternativeInterrupt ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override void OnStartServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
void SetupAnimation (ItemBase item)
override void OnStartAnimationLoopClient (ActionData action_data)
override void OnStartAnimationLoopServer (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
Private Attributes
EntityAI m_RepackedEntity
bool m_IsFinished
Detailed Description
Definition at line 42 of file ActionRepackTent.c.
Constructor & Destructor Documentation
ActionRepackTent()
void ActionRepackTent () inline private
Definition at line 47 of file ActionRepackTent.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 83 of file ActionRepackTent.c.
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
Definition at line 73 of file ActionRepackTent.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 57 of file ActionRepackTent.c.
References m_ConditionItem, and m_ConditionTarget.
HasAlternativeInterrupt()
override bool HasAlternativeInterrupt () inline private
Definition at line 78 of file ActionRepackTent.c.
HasProgress()
override bool HasProgress () inline private
Definition at line 68 of file ActionRepackTent.c.
HasTarget()
override bool HasTarget () inline private
Definition at line 63 of file ActionRepackTent.c.
OnEndAnimationLoop()
override void OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 194 of file ActionRepackTent.c.
References GetGame(), ActionData::m_MainItem, and CGame::RPCSingleParam().
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
Definition at line 117 of file ActionRepackTent.c.
References GetGame(), m_IsFinished, ActionData::m_MainItem, and ActionData::m_Player.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 109 of file ActionRepackTent.c.
References GetGame(), m_IsFinished, ActionData::m_MainItem, and CGame::RPCSingleParam().
OnStartAnimationLoopClient()
override void OnStartAnimationLoopClient (ActionData action_data) inline private
Definition at line 172 of file ActionRepackTent.c.
References ActionRepackTentCB::DropDuringRepacking(), ActionData::m_Callback, and ActionData::m_Player.
OnStartAnimationLoopServer()
override void OnStartAnimationLoopServer (ActionData action_data) inline private
Definition at line 178 of file ActionRepackTent.c.
References ActionRepackTentCB::DropDuringRepacking(), GetGame(), ActionData::m_Callback, ActionData::m_MainItem, ActionData::m_Player, and CGame::RPCSingleParam().
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
Definition at line 103 of file ActionRepackTent.c.
References m_IsFinished, and m_RepackedEntity.
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 92 of file ActionRepackTent.c.
References SetupAnimation().
SetupAnimation()
void SetupAnimation (ItemBase item) inline private
Definition at line 152 of file ActionRepackTent.c.
References AnimatedActionBase::m_CommandUID, and Print().
Referenced by SetupAction().
Field Documentation
m_IsFinished
bool m_IsFinished private
Definition at line 45 of file ActionRepackTent.c.
Referenced by OnEndServer(), OnFinishProgressServer(), and OnStartServer().
m_RepackedEntity
EntityAI m_RepackedEntity private
Definition at line 44 of file ActionRepackTent.c.
Referenced by OnStartServer().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Interact/ActionRepackTent.c