DayZ: SpookyArea Class Reference
SpookyArea Class Reference
Private Member Functions
override void SetupZoneData (EffectAreaParams params)
override void EEInit ()
override void InitZone ()
override void InitZoneServer ()
override void InitZoneClient ()
override void EEDelete (EntityAI parent)
Detailed Description
Definition at line 2 of file SpookyArea.c.
Member Function Documentation
EEDelete()
override void EEDelete (EntityAI parent) inline private
Definition at line 60 of file SpookyArea.c.
EEInit()
override void EEInit () inline private
Definition at line 13 of file SpookyArea.c.
References GetGame(), InitZone(), Debug::Log(), and EffectArea::m_ToxicClouds.
InitZone()
override void InitZone () inline private
Definition at line 38 of file SpookyArea.c.
Referenced by EEInit().
InitZoneClient()
override void InitZoneClient () inline private
Definition at line 52 of file SpookyArea.c.
References GetWorldPosition(), EffectArea::m_InnerRings, EffectArea::m_InnerSpacing, EffectArea::m_OuterRingOffset, EffectArea::m_OuterRingToggle, EffectArea::m_OuterSpacing, EffectArea::m_ParticleID, EffectArea::m_Radius, and EffectArea::PlaceParticles().
InitZoneServer()
override void InitZoneServer () inline private
Definition at line 43 of file SpookyArea.c.
References CreateTrigger(), EffectArea::m_Position, EffectArea::m_Radius, and EffectArea::m_TriggerType.
SetupZoneData()
override void SetupZoneData (EffectAreaParams params) inline private
Definition at line 8 of file SpookyArea.c.
The documentation for this class was generated from the following file:
4_World/Classes/ContaminatedArea/SpookyArea.c