DayZ Scripts Documentation: MapMarker Class Reference
MapMarker Class Reference
Private Member Functions
void MapMarker (vector pos, string text, int color, int idx)
vector GetMarkerPos ()
string GetMarkerText ()
int GetMarkerColor ()
int GetMarkerIcon ()
Private Attributes
protected vector m_Position
protected int m_Color
protected int m_IconIdx
protected string m_Text
Detailed Description
Definition at line 1195 of file InventoryItem.c.
Constructor & Destructor Documentation
MapMarker()
void MapMarker (vector pos, string text, int color, int idx) inline private
Definition at line 1202 of file InventoryItem.c.
References m_Color, m_IconIdx, m_Position, and m_Text.
Member Function Documentation
GetMarkerColor()
int GetMarkerColor () inline private
Definition at line 1220 of file InventoryItem.c.
References m_Color.
Referenced by UIScriptedMenu::LoadMapMarkers().
GetMarkerIcon()
int GetMarkerIcon () inline private
Definition at line 1225 of file InventoryItem.c.
References m_IconIdx.
Referenced by UIScriptedMenu::LoadMapMarkers().
GetMarkerPos()
vector GetMarkerPos () inline private
Definition at line 1210 of file InventoryItem.c.
References m_Position.
Referenced by UIScriptedMenu::LoadMapMarkers().
GetMarkerText()
string GetMarkerText () inline private
Definition at line 1215 of file InventoryItem.c.
References m_Text.
Referenced by UIScriptedMenu::LoadMapMarkers().
Field Documentation
m_Color
protected int m_Color private
Definition at line 1198 of file InventoryItem.c.
Referenced by GetMarkerColor(), and MapMarker().
m_IconIdx
protected int m_IconIdx private
Definition at line 1199 of file InventoryItem.c.
Referenced by GetMarkerIcon(), and MapMarker().
m_Position
protected vector m_Position private
Definition at line 1197 of file InventoryItem.c.
Referenced by GetMarkerPos(), and MapMarker().
m_Text
protected string m_Text private
Definition at line 1200 of file InventoryItem.c.
Referenced by GetMarkerText(), and MapMarker().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Core/Inherited/InventoryItem.c