DayZ Scripts Documentation: Weapon_Base Class Reference
Weapon_Base Class Reference
shorthand
Private Member Functions
override float GetChanceToJam ()
override void SetActions ()
override RecoilBase SpawnRecoilObject ()
void Magnum_Base ()
override void InitStateMachine ()
override bool CanChamberBullet (int muzzleIndex, Magazine mag)
override void AssembleGun ()
void SetCylinderRotationAnimationPhase (float rot, bool reset=false)
void SyncCylinderRotation (bool reset=true)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
void SetAttachmentsHealth ()
override void OnFire (int muzzle_index)
override bool IsShowingChamberedBullet ()
override bool CanEjectBullet ()
override void ShowBullet (int muzzleIndex)
override void HideBullet (int muzzleIndex)
override void OnDebugSpawn ()
override bool CanChamberBullet (int muzzleIndex, Magazine mag)
void Pistol_Base ()
override void InitStateMachine ()
override float GetChanceToJam ()
override void SetActions ()
void Rifle_Base ()
override void InitStateMachine ()
Static Private Member Functions
static float GetCylinderRotation (int muzzleIndex)
Private Attributes
ref WeaponStateBase C
int m_LastMuzzleloaded
int m_ActiveMuzzle
const string ATT_SLOT_CYLINDER = "RevolverCylinder"
const string ATT_SLOT_EJECTOR = "RevolverEjector"
ref WeaponStateBase CD00
ref WeaponStateBase CC00
ref WeaponStateBase CC10
ref WeaponStateBase CJF0
ref WeaponStateBase OD00
ref WeaponStateBase CD01
ref WeaponStateBase CC01
ref WeaponStateBase CC11
ref WeaponStateBase CJF1
ref WeaponStateBase OD01
Detailed Description
shorthand
script base for all weapons
@NOTE: this class is bound to core-config "Weapon_Base" config class
Definition at line 5 of file BoltActionRifle_Base.c.
Member Function Documentation
AssembleGun()
override void AssembleGun () inline private
Definition at line 181 of file Magnum.c.
Referenced by Weapon::EEInit().
CanChamberBullet() [1/2]
override bool CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 165 of file Magnum.c.
References IsChamberFiredOut().
Referenced by WeaponManager::CanLoadBullet().
CanChamberBullet() [2/2]
override bool CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 160 of file Pistol_Base.c.
CanEjectBullet()
override bool CanEjectBullet () inline private
Definition at line 296 of file Magnum.c.
References IsChamberFull().
Referenced by WeaponManager::CanEjectBullet().
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 253 of file Magnum.c.
References GetGame().
GetChanceToJam() [1/2]
override float GetChanceToJam () inline private
Definition at line 7 of file BoltActionRifle_Base.c.
Referenced by WeaponManager::Update().
GetChanceToJam() [2/2]
override float GetChanceToJam () inline private
Definition at line 576 of file Pistol_Base.c.
GetCylinderRotation()
static float GetCylinderRotation (int muzzleIndex) inline static private
Definition at line 199 of file Magnum.c.
References ErrorEx, MAGNUM_ROTATION_POSITION_0, MAGNUM_ROTATION_POSITION_1, MAGNUM_ROTATION_POSITION_2, MAGNUM_ROTATION_POSITION_3, MAGNUM_ROTATION_POSITION_4, and MAGNUM_ROTATION_POSITION_5.
HideBullet()
override void HideBullet (int muzzleIndex) inline private
Definition at line 329 of file Magnum.c.
References string::Format().
Referenced by Weapon::ForceSyncSelectionState().
InitStateMachine() [1/3]
override void InitStateMachine () inline private
Definition at line 88 of file Magnum.c.
Referenced by Weapon::Weapon_Base().
InitStateMachine() [2/3]
override void InitStateMachine () inline private
Definition at line 169 of file Pistol_Base.c.
References WeaponGuardHasAmmo().
InitStateMachine() [3/3]
override void InitStateMachine () inline private
Definition at line 16 of file Rifle_Base.c.
References E.
IsShowingChamberedBullet()
override bool IsShowingChamberedBullet () inline private
Definition at line 291 of file Magnum.c.
Referenced by Icon::RefreshMuzzleIcon(), and SlotsIcon::RefreshMuzzleIcon().
Magnum_Base()
void Magnum_Base () inline private
Definition at line 73 of file Magnum.c.
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 350 of file Magnum.c.
References Class::CastTo().
OnFire()
override void OnFire (int muzzle_index) inline private
Definition at line 278 of file Magnum.c.
References string::Format().
Pistol_Base()
void Pistol_Base () inline private
Definition at line 165 of file Pistol_Base.c.
Rifle_Base()
void Rifle_Base () inline private
Definition at line 12 of file Rifle_Base.c.
SetActions() [1/2]
override void SetActions () inline private
Definition at line 58 of file Magnum.c.
References AddAction(), and RemoveAction().
SetActions() [2/2]
override void SetActions () inline private
Definition at line 607 of file Pistol_Base.c.
References AddAction().
SetAttachmentsHealth()
void SetAttachmentsHealth () inline private
Definition at line 264 of file Magnum.c.
References Class::CastTo(), and GetHealth01().
SetCylinderRotationAnimationPhase()
void SetCylinderRotationAnimationPhase (float rot, bool reset = false) inline private
Definition at line 222 of file Magnum.c.
References Math::AbsFloat(), MAGNUM_ROTATION_POSITION_0, and MAGNUM_ROTATION_POSITION_M1.
ShowBullet()
override void ShowBullet (int muzzleIndex) inline private
Definition at line 306 of file Magnum.c.
References string::Format(), and IsChamberFiredOut().
Referenced by Weapon::ForceSyncSelectionState().
SpawnRecoilObject()
override RecoilBase SpawnRecoilObject () inline private
Definition at line 68 of file Magnum.c.
Referenced by DayZPlayerImplementAiming::SetRecoil().
SyncCylinderRotation()
void SyncCylinderRotation (bool reset = true) inline private
Definition at line 248 of file Magnum.c.
Field Documentation
ATT_SLOT_CYLINDER
const string ATT_SLOT_CYLINDER = "RevolverCylinder" private
Definition at line 55 of file Magnum.c.
ATT_SLOT_EJECTOR
const string ATT_SLOT_EJECTOR = "RevolverEjector" private
Definition at line 56 of file Magnum.c.
C
ref WeaponStateBase C private
Definition at line 52 of file Magnum.c.
CC00
ref WeaponStateBase CC00 private
Definition at line 150 of file Pistol_Base.c.
CC01
ref WeaponStateBase CC01 private
Definition at line 155 of file Pistol_Base.c.
CC10
ref WeaponStateBase CC10 private
Definition at line 151 of file Pistol_Base.c.
CC11
ref WeaponStateBase CC11 private
Definition at line 156 of file Pistol_Base.c.
CD00
ref WeaponStateBase CD00 private
Definition at line 149 of file Pistol_Base.c.
CD01
ref WeaponStateBase CD01 private
Definition at line 154 of file Pistol_Base.c.
CJF0
ref WeaponStateBase CJF0 private
Definition at line 152 of file Pistol_Base.c.
CJF1
ref WeaponStateBase CJF1 private
Definition at line 157 of file Pistol_Base.c.
m_ActiveMuzzle
int m_ActiveMuzzle private
Definition at line 54 of file Magnum.c.
m_LastMuzzleloaded
int m_LastMuzzleloaded private
Definition at line 53 of file Magnum.c.
OD00
ref WeaponStateBase OD00 private
Definition at line 153 of file Pistol_Base.c.
OD01
ref WeaponStateBase OD01 private
Definition at line 158 of file Pistol_Base.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Firearms/BoltActionRifle_Base.c
P:/scripts/4_World/Entities/Firearms/Pistol/Magnum.c
P:/scripts/4_World/Entities/Firearms/Pistol_Base.c
P:/scripts/4_World/Entities/Firearms/Rifle_Base.c