DayZ: ActionViewOptics Class Reference
ActionViewOptics Class Reference
Private Member Functions
void ActionViewOptics ()
override void CreateConditionComponents ()
override bool IsFullBody (PlayerBase player)
override bool HasProgress ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override void OnStartAnimationLoopServer (ActionData action_data)
override void OnStartAnimationLoopClient (ActionData action_data)
override void OnEndClient (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnEndAnimationLoopClient (ActionData action_data)
override void OnEndAnimationLoopServer (ActionData action_data)
bool CanWork (ItemBase item)
void EnterOptics (ItemOptics optic, PlayerBase player)
void ExitOptics (ItemOptics optic, PlayerBase player)
Detailed Description
Definition at line 1 of file ActionViewOptics.c.
Constructor & Destructor Documentation
ActionViewOptics()
void ActionViewOptics () inline private
Definition at line 3 of file ActionViewOptics.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file ActionViewOptics.c.
References Class::CastTo().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
Definition at line 42 of file ActionViewOptics.c.
CanWork()
bool CanWork (ItemBase item) inline private
Definition at line 107 of file ActionViewOptics.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 11 of file ActionViewOptics.c.
References m_ConditionItem, and m_ConditionTarget.
EnterOptics()
void EnterOptics (ItemOptics optic, PlayerBase player) inline private
Definition at line 121 of file ActionViewOptics.c.
References ItemOptics::HideSelection().
Referenced by OnStartAnimationLoopClient(), and OnStartAnimationLoopServer().
ExitOptics()
void ExitOptics (ItemOptics optic, PlayerBase player) inline private
Definition at line 133 of file ActionViewOptics.c.
References ItemOptics::ShowSelection().
Referenced by OnEndAnimationLoopClient(), OnEndAnimationLoopServer(), OnEndClient(), and OnEndServer().
HasProgress()
override bool HasProgress () inline private
Definition at line 22 of file ActionViewOptics.c.
HasTarget()
override bool HasTarget () inline private
Definition at line 27 of file ActionViewOptics.c.
IsFullBody()
override bool IsFullBody (PlayerBase player) inline private
Definition at line 17 of file ActionViewOptics.c.
OnEndAnimationLoopClient()
override void OnEndAnimationLoopClient (ActionData action_data) inline private
Definition at line 89 of file ActionViewOptics.c.
References Class::CastTo(), ExitOptics(), ActionData::m_MainItem, and ActionData::m_Player.
OnEndAnimationLoopServer()
override void OnEndAnimationLoopServer (ActionData action_data) inline private
Definition at line 98 of file ActionViewOptics.c.
References Class::CastTo(), ExitOptics(), ActionData::m_MainItem, and ActionData::m_Player.
OnEndClient()
override void OnEndClient (ActionData action_data) inline private
Definition at line 71 of file ActionViewOptics.c.
References Class::CastTo(), ExitOptics(), ActionData::m_MainItem, and ActionData::m_Player.
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
Definition at line 80 of file ActionViewOptics.c.
References Class::CastTo(), ExitOptics(), ActionData::m_MainItem, and ActionData::m_Player.
OnStartAnimationLoopClient()
override void OnStartAnimationLoopClient (ActionData action_data) inline private
Definition at line 59 of file ActionViewOptics.c.
References Class::CastTo(), EnterOptics(), ActionData::m_MainItem, and ActionData::m_Player.
OnStartAnimationLoopServer()
override void OnStartAnimationLoopServer (ActionData action_data) inline private
Definition at line 47 of file ActionViewOptics.c.
References Class::CastTo(), EnterOptics(), ActionData::m_MainItem, and ActionData::m_Player.
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Continuous/ActionViewOptics.c