DayZ Scripts: ActionRepairTent Class Reference
ActionRepairTent Class Reference
Private Member Functions
void ActionRepairTent ()
override void CreateConditionComponents ()
override bool IsUsingProxies ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override ActionData CreateActionData ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
void RepairDamageTransfer (PlayerBase player, ItemBase repair_kit, ItemBase item, float specialty_weight, string damage_zone="")
Private Attributes
m_LastValidType
string m_CurrentDamageZone = ""
int m_LastValidComponentIndex = -1
Detailed Description
Definition at line 19 of file ActionRepairTent.c.
Constructor & Destructor Documentation
ActionRepairTent()
void ActionRepairTent () inline private
Definition at line 25 of file ActionRepairTent.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 52 of file ActionRepairTent.c.
References Class::CastTo(), GetPlugin(), and m_CurrentDamageZone.
CreateActionData()
override ActionData CreateActionData () inline private
Definition at line 110 of file ActionRepairTent.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 36 of file ActionRepairTent.c.
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::SMALL.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 148 of file ActionRepairTent.c.
References RepairTentActionReciveData::m_DamageZoneRecived.
HasTarget()
override bool HasTarget () inline private
Definition at line 47 of file ActionRepairTent.c.
Referenced by ReadFromContext(), and WriteToContext().
IsUsingProxies()
override bool IsUsingProxies () inline private
Definition at line 42 of file ActionRepairTent.c.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 90 of file ActionRepairTent.c.
References Class::CastTo(), GetGame(), GetPlugin(), m_CurrentDamageZone, ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, ActionData::m_Target, and RepairDamageTransfer().
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 128 of file ActionRepairTent.c.
References HasTarget(), RepairTentActionReciveData::m_DamageZoneRecived, and Serializer::Read().
RepairDamageTransfer()
void RepairDamageTransfer (PlayerBase player, ItemBase repair_kit, ItemBase item, float specialty_weight, string damage_zone = "") inline private
Definition at line 156 of file ActionRepairTent.c.
References Class::CastTo(), CFG_VEHICLESPATH, CGame::ConfigGetFloat(), CGame::ConfigGetTextArray(), GetGame(), GetPlugin(), and path.
Referenced by OnFinishProgressServer().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 116 of file ActionRepairTent.c.
References Class::CastTo(), HasTarget(), m_CurrentDamageZone, and Serializer::Write().
Field Documentation
m_CurrentDamageZone
string m_CurrentDamageZone = "" private
Definition at line 22 of file ActionRepairTent.c.
Referenced by ActionCondition(), OnFinishProgressServer(), and WriteToContext().
m_LastValidComponentIndex
int m_LastValidComponentIndex = -1 private
Definition at line 23 of file ActionRepairTent.c.
m_LastValidType
m_LastValidType private
Definition at line 21 of file ActionRepairTent.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionRepairTent.c