DayZ Scripts Documentation: PASBroadcaster Class Reference
PASBroadcaster Class Reference
Private Member Functions
override bool IsStaticTransmitter ()
override bool DisableVicinityIcon ()
override void OnSwitchOn ()
override void OnSwitchOff ()
override void OnWorkStart ()
override void OnWorkStop ()
protected void SoundTurnedOnNoiseStart ()
protected void SoundTurnedOnNoiseStop ()
protected void SoundTurnOn ()
protected void SoundTurnOff ()
Private Attributes
const string SOUND_PAS_TURN_ON = "pastransmitter_turnon_SoundSet"
const string SOUND_PAS_TURN_OFF = "pastransmitter_turnoff_SoundSet"
const string SOUND_PAS_TURNED_ON = "pastransmitter_staticnoise_SoundSet"
protected EffectSound m_Sound
protected EffectSound m_SoundLoop
Detailed Description
Definition at line 1 of file Land_Radio_PanelPAS.c.
Member Function Documentation
DisableVicinityIcon()
override bool DisableVicinityIcon () inline private
Definition at line 17 of file Land_Radio_PanelPAS.c.
IsStaticTransmitter()
override bool IsStaticTransmitter () inline private
Definition at line 12 of file Land_Radio_PanelPAS.c.
OnSwitchOff()
override void OnSwitchOff () inline private
Definition at line 36 of file Land_Radio_PanelPAS.c.
References SoundTurnOff().
OnSwitchOn()
override void OnSwitchOn () inline private
Definition at line 23 of file Land_Radio_PanelPAS.c.
References SoundTurnOn().
OnWorkStart()
override void OnWorkStart () inline private
Definition at line 44 of file Land_Radio_PanelPAS.c.
References SoundTurnedOnNoiseStart().
OnWorkStop()
override void OnWorkStop () inline private
Definition at line 55 of file Land_Radio_PanelPAS.c.
References SoundTurnedOnNoiseStop().
SoundTurnedOnNoiseStart()
protected void SoundTurnedOnNoiseStart () inline private
Definition at line 70 of file Land_Radio_PanelPAS.c.
References PlaySoundSetLoop().
Referenced by OnWorkStart().
SoundTurnedOnNoiseStop()
protected void SoundTurnedOnNoiseStop () inline private
Definition at line 75 of file Land_Radio_PanelPAS.c.
References StopSoundSet().
Referenced by OnWorkStop().
SoundTurnOff()
protected void SoundTurnOff () inline private
Definition at line 85 of file Land_Radio_PanelPAS.c.
References m_Sound, and PlaySoundSet().
Referenced by OnSwitchOff().
SoundTurnOn()
protected void SoundTurnOn () inline private
Definition at line 80 of file Land_Radio_PanelPAS.c.
References m_Sound, and PlaySoundSet().
Referenced by OnSwitchOn().
Field Documentation
m_Sound
protected EffectSound m_Sound private
Definition at line 8 of file Land_Radio_PanelPAS.c.
m_SoundLoop
protected EffectSound m_SoundLoop private
Definition at line 9 of file Land_Radio_PanelPAS.c.
SOUND_PAS_TURN_OFF
const string SOUND_PAS_TURN_OFF = "pastransmitter_turnoff_SoundSet" private
Definition at line 5 of file Land_Radio_PanelPAS.c.
SOUND_PAS_TURN_ON
const string SOUND_PAS_TURN_ON = "pastransmitter_turnon_SoundSet" private
Definition at line 4 of file Land_Radio_PanelPAS.c.
SOUND_PAS_TURNED_ON
const string SOUND_PAS_TURNED_ON = "pastransmitter_staticnoise_SoundSet" private
Definition at line 6 of file Land_Radio_PanelPAS.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/AdvancedCommunication/Land_Radio_PanelPAS.c