DayZ Scripts Documentation: PluginDayzPlayerDebug_Ctrl Class Reference
PluginDayzPlayerDebug_Ctrl Class Reference
Private Member Functions
void PluginDayzPlayerDebug_Ctrl (Widget pMainWnd)
void ~PluginDayzPlayerDebug_Ctrl ()
void CreateModuleWidgets ()
void DestroyModuleWidgets ()
bool OnClick (Widget w, int x, int y, int button)
buttons clicks
bool OnChange (Widget w, int x, int y, bool finished)
void CommandHandler ()
Private Attributes
Widget m_MainWnd
XComboBoxWidget m_ForceStance
EditBoxWidget m_MovSpeedEB
EditBoxWidget m_MovDirEB
CheckBoxWidget m_MovOverrideCheckbox
int m_ApplyStanceChange
bool m_OverrideMovementChange = false
Detailed Description
Definition at line 6 of file PluginDayzPlayerDebug_Ctrl.c.
Constructor & Destructor Documentation
PluginDayzPlayerDebug_Ctrl()
void PluginDayzPlayerDebug_Ctrl (Widget pMainWnd) inline private
Definition at line 23 of file PluginDayzPlayerDebug_Ctrl.c.
References CreateModuleWidgets(), m_ApplyStanceChange, and m_MainWnd.
~PluginDayzPlayerDebug_Ctrl()
void ~PluginDayzPlayerDebug_Ctrl () inline private
Definition at line 32 of file PluginDayzPlayerDebug_Ctrl.c.
References DestroyModuleWidgets().
Member Function Documentation
CommandHandler()
void CommandHandler () inline private
Definition at line 107 of file PluginDayzPlayerDebug_Ctrl.c.
References HumanCommandMove::ForceStance(), GetGame(), GetPlayer(), m_ApplyStanceChange, m_MovDirEB, m_MovOverrideCheckbox, m_MovSpeedEB, and m_OverrideMovementChange.
Referenced by CommandHandler().
CreateModuleWidgets()
void CreateModuleWidgets () inline private
Definition at line 38 of file PluginDayzPlayerDebug_Ctrl.c.
References m_ForceStance, m_MainWnd, m_MovDirEB, m_MovOverrideCheckbox, and m_MovSpeedEB.
Referenced by PluginDayzPlayerDebug_Ctrl().
DestroyModuleWidgets()
void DestroyModuleWidgets () inline private
Definition at line 46 of file PluginDayzPlayerDebug_Ctrl.c.
Referenced by ~PluginDayzPlayerDebug_Ctrl().
OnChange()
bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 92 of file PluginDayzPlayerDebug_Ctrl.c.
References m_MovDirEB, m_MovSpeedEB, m_OverrideMovementChange, and Print().
OnClick()
bool OnClick (Widget w, int x, int y, int button) inline private
buttons clicks
Definition at line 74 of file PluginDayzPlayerDebug_Ctrl.c.
References m_ApplyStanceChange, m_ForceStance, m_MovOverrideCheckbox, m_OverrideMovementChange, and Print().
Field Documentation
m_ApplyStanceChange
int m_ApplyStanceChange private
Definition at line 16 of file PluginDayzPlayerDebug_Ctrl.c.
Referenced by CommandHandler(), OnClick(), and PluginDayzPlayerDebug_Ctrl().
m_ForceStance
XComboBoxWidget m_ForceStance private
Definition at line 10 of file PluginDayzPlayerDebug_Ctrl.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_MainWnd
Widget m_MainWnd private
Definition at line 8 of file PluginDayzPlayerDebug_Ctrl.c.
Referenced by CreateModuleWidgets(), and PluginDayzPlayerDebug_Ctrl().
m_MovDirEB
EditBoxWidget m_MovDirEB private
Definition at line 12 of file PluginDayzPlayerDebug_Ctrl.c.
Referenced by CommandHandler(), CreateModuleWidgets(), and OnChange().
m_MovOverrideCheckbox
CheckBoxWidget m_MovOverrideCheckbox private
Definition at line 13 of file PluginDayzPlayerDebug_Ctrl.c.
Referenced by CommandHandler(), CreateModuleWidgets(), and OnClick().
m_MovSpeedEB
EditBoxWidget m_MovSpeedEB private
Definition at line 11 of file PluginDayzPlayerDebug_Ctrl.c.
Referenced by CommandHandler(), CreateModuleWidgets(), and OnChange().
m_OverrideMovementChange
bool m_OverrideMovementChange = false private
Definition at line 17 of file PluginDayzPlayerDebug_Ctrl.c.
Referenced by CommandHandler(), OnChange(), and OnClick().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Plugins/PluginBase/PluginDayzPlayerDebug_Ctrl.c