DayZ Scripts Documentation: WeaponStateJammed Class Reference
WeaponStateJammed Class Reference
handle jamming state set jam/unjam state for weapon
Private Member Functions
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasMagazine ()
override bool IsJammed ()
override bool IsBoltOpen ()
override bool IsRepairEnabled ()
override void InitMuzzleArray ()
Detailed Description
handle jamming state set jam/unjam state for weapon
Definition at line 52 of file SKS.c.
Member Function Documentation
GetCurrentStateID() [1/13]
override int GetCurrentStateID () inline private
Definition at line 56 of file SKS.c.
GetCurrentStateID() [2/13]
override int GetCurrentStateID () inline private
Definition at line 90 of file BoltActionRifleExternalMagazine_Base.c.
GetCurrentStateID() [3/13]
override int GetCurrentStateID () inline private
Definition at line 102 of file BoltActionRifleExternalMagazine_Base.c.
GetCurrentStateID() [4/13]
override int GetCurrentStateID () inline private
Definition at line 55 of file BoltActionRifleInnerMagazine_Base.c.
GetCurrentStateID() [5/13]
override int GetCurrentStateID () inline private
Definition at line 64 of file Pistol_Base.c.
GetCurrentStateID() [6/13]
override int GetCurrentStateID () inline private
Definition at line 110 of file Pistol_Base.c.
GetCurrentStateID() [7/13]
override int GetCurrentStateID () inline private
Definition at line 55 of file Repeater.c.
GetCurrentStateID() [8/13]
override int GetCurrentStateID () inline private
Definition at line 66 of file RifleBoltFree_Base.c.
GetCurrentStateID() [9/13]
override int GetCurrentStateID () inline private
Definition at line 78 of file RifleBoltFree_Base.c.
GetCurrentStateID() [10/13]
override int GetCurrentStateID () inline private
Definition at line 93 of file RifleBoltLock_Base.c.
GetCurrentStateID() [11/13]
override int GetCurrentStateID () inline private
Definition at line 105 of file RifleBoltLock_Base.c.
GetCurrentStateID() [12/13]
override int GetCurrentStateID () inline private
Definition at line 52 of file RifleSingleShot_Base.c.
GetCurrentStateID() [13/13]
override int GetCurrentStateID () inline private
Definition at line 52 of file MP133.c.
HasBullet() [1/13]
override bool HasBullet () inline private
Definition at line 57 of file SKS.c.
HasBullet() [2/13]
override bool HasBullet () inline private
Definition at line 91 of file BoltActionRifleExternalMagazine_Base.c.
HasBullet() [3/13]
override bool HasBullet () inline private
Definition at line 103 of file BoltActionRifleExternalMagazine_Base.c.
HasBullet() [4/13]
override bool HasBullet () inline private
Definition at line 56 of file BoltActionRifleInnerMagazine_Base.c.
HasBullet() [5/13]
override bool HasBullet () inline private
Definition at line 65 of file Pistol_Base.c.
HasBullet() [6/13]
override bool HasBullet () inline private
Definition at line 111 of file Pistol_Base.c.
HasBullet() [7/13]
override bool HasBullet () inline private
Definition at line 56 of file Repeater.c.
HasBullet() [8/13]
override bool HasBullet () inline private
Definition at line 67 of file RifleBoltFree_Base.c.
HasBullet() [9/13]
override bool HasBullet () inline private
Definition at line 79 of file RifleBoltFree_Base.c.
HasBullet() [10/13]
override bool HasBullet () inline private
Definition at line 94 of file RifleBoltLock_Base.c.
HasBullet() [11/13]
override bool HasBullet () inline private
Definition at line 106 of file RifleBoltLock_Base.c.
HasBullet() [12/13]
override bool HasBullet () inline private
Definition at line 53 of file RifleSingleShot_Base.c.
HasBullet() [13/13]
override bool HasBullet () inline private
Definition at line 53 of file MP133.c.
HasMagazine() [1/13]
override bool HasMagazine () inline private
Definition at line 58 of file SKS.c.
HasMagazine() [2/13]
override bool HasMagazine () inline private
Definition at line 92 of file BoltActionRifleExternalMagazine_Base.c.
HasMagazine() [3/13]
override bool HasMagazine () inline private
Definition at line 104 of file BoltActionRifleExternalMagazine_Base.c.
HasMagazine() [4/13]
override bool HasMagazine () inline private
Definition at line 57 of file BoltActionRifleInnerMagazine_Base.c.
HasMagazine() [5/13]
override bool HasMagazine () inline private
Definition at line 66 of file Pistol_Base.c.
HasMagazine() [6/13]
override bool HasMagazine () inline private
Definition at line 112 of file Pistol_Base.c.
HasMagazine() [7/13]
override bool HasMagazine () inline private
Definition at line 57 of file Repeater.c.
HasMagazine() [8/13]
override bool HasMagazine () inline private
Definition at line 68 of file RifleBoltFree_Base.c.
HasMagazine() [9/13]
override bool HasMagazine () inline private
Definition at line 80 of file RifleBoltFree_Base.c.
HasMagazine() [10/13]
override bool HasMagazine () inline private
Definition at line 95 of file RifleBoltLock_Base.c.
HasMagazine() [11/13]
override bool HasMagazine () inline private
Definition at line 107 of file RifleBoltLock_Base.c.
HasMagazine() [12/13]
override bool HasMagazine () inline private
Definition at line 54 of file RifleSingleShot_Base.c.
HasMagazine() [13/13]
override bool HasMagazine () inline private
Definition at line 54 of file MP133.c.
InitMuzzleArray() [1/13]
override void InitMuzzleArray () inline private
Definition at line 62 of file SKS.c.
References m_muzzleHasBullet.
InitMuzzleArray() [2/13]
override void InitMuzzleArray () inline private
Definition at line 96 of file BoltActionRifleExternalMagazine_Base.c.
References m_muzzleHasBullet.
InitMuzzleArray() [3/13]
override void InitMuzzleArray () inline private
Definition at line 108 of file BoltActionRifleExternalMagazine_Base.c.
References m_muzzleHasBullet.
InitMuzzleArray() [4/13]
override void InitMuzzleArray () inline private
Definition at line 60 of file BoltActionRifleInnerMagazine_Base.c.
References m_muzzleHasBullet.
InitMuzzleArray() [5/13]
override void InitMuzzleArray () inline private
Definition at line 70 of file Pistol_Base.c.
References m_muzzleHasBullet.
InitMuzzleArray() [6/13]
override void InitMuzzleArray () inline private
Definition at line 116 of file Pistol_Base.c.
References m_muzzleHasBullet.
InitMuzzleArray() [7/13]
override void InitMuzzleArray () inline private
Definition at line 60 of file Repeater.c.
References m_muzzleHasBullet.
InitMuzzleArray() [8/13]
override void InitMuzzleArray () inline private
Definition at line 72 of file RifleBoltFree_Base.c.
References m_muzzleHasBullet.
InitMuzzleArray() [9/13]
override void InitMuzzleArray () inline private
Definition at line 84 of file RifleBoltFree_Base.c.
References m_muzzleHasBullet.
InitMuzzleArray() [10/13]
override void InitMuzzleArray () inline private
Definition at line 99 of file RifleBoltLock_Base.c.
References m_muzzleHasBullet.
InitMuzzleArray() [11/13]
override void InitMuzzleArray () inline private
Definition at line 111 of file RifleBoltLock_Base.c.
References m_muzzleHasBullet.
InitMuzzleArray() [12/13]
override void InitMuzzleArray () inline private
Definition at line 58 of file RifleSingleShot_Base.c.
References m_muzzleHasBullet.
InitMuzzleArray() [13/13]
override void InitMuzzleArray () inline private
Definition at line 58 of file MP133.c.
References m_muzzleHasBullet.
IsBoltOpen() [1/11]
override bool IsBoltOpen () inline private
Definition at line 60 of file SKS.c.
IsBoltOpen() [2/11]
override bool IsBoltOpen () inline private
Definition at line 94 of file BoltActionRifleExternalMagazine_Base.c.
IsBoltOpen() [3/11]
override bool IsBoltOpen () inline private
Definition at line 106 of file BoltActionRifleExternalMagazine_Base.c.
IsBoltOpen() [4/11]
override bool IsBoltOpen () inline private
Definition at line 68 of file Pistol_Base.c.
IsBoltOpen() [5/11]
override bool IsBoltOpen () inline private
Definition at line 114 of file Pistol_Base.c.
IsBoltOpen() [6/11]
override bool IsBoltOpen () inline private
Definition at line 70 of file RifleBoltFree_Base.c.
IsBoltOpen() [7/11]
override bool IsBoltOpen () inline private
Definition at line 82 of file RifleBoltFree_Base.c.
IsBoltOpen() [8/11]
override bool IsBoltOpen () inline private
Definition at line 97 of file RifleBoltLock_Base.c.
IsBoltOpen() [9/11]
override bool IsBoltOpen () inline private
Definition at line 109 of file RifleBoltLock_Base.c.
IsBoltOpen() [10/11]
override bool IsBoltOpen () inline private
Definition at line 56 of file RifleSingleShot_Base.c.
IsBoltOpen() [11/11]
override bool IsBoltOpen () inline private
Definition at line 56 of file MP133.c.
IsJammed() [1/13]
override bool IsJammed () inline private
Definition at line 59 of file SKS.c.
IsJammed() [2/13]
override bool IsJammed () inline private
Definition at line 93 of file BoltActionRifleExternalMagazine_Base.c.
IsJammed() [3/13]
override bool IsJammed () inline private
Definition at line 105 of file BoltActionRifleExternalMagazine_Base.c.
IsJammed() [4/13]
override bool IsJammed () inline private
Definition at line 58 of file BoltActionRifleInnerMagazine_Base.c.
IsJammed() [5/13]
override bool IsJammed () inline private
Definition at line 67 of file Pistol_Base.c.
IsJammed() [6/13]
override bool IsJammed () inline private
Definition at line 113 of file Pistol_Base.c.
IsJammed() [7/13]
override bool IsJammed () inline private
Definition at line 58 of file Repeater.c.
IsJammed() [8/13]
override bool IsJammed () inline private
Definition at line 69 of file RifleBoltFree_Base.c.
IsJammed() [9/13]
override bool IsJammed () inline private
Definition at line 81 of file RifleBoltFree_Base.c.
IsJammed() [10/13]
override bool IsJammed () inline private
Definition at line 96 of file RifleBoltLock_Base.c.
IsJammed() [11/13]
override bool IsJammed () inline private
Definition at line 108 of file RifleBoltLock_Base.c.
IsJammed() [12/13]
override bool IsJammed () inline private
Definition at line 55 of file RifleSingleShot_Base.c.
IsJammed() [13/13]
override bool IsJammed () inline private
Definition at line 55 of file MP133.c.
IsRepairEnabled() [1/13]
override bool IsRepairEnabled () inline private
Definition at line 61 of file SKS.c.
IsRepairEnabled() [2/13]
override bool IsRepairEnabled () inline private
Definition at line 95 of file BoltActionRifleExternalMagazine_Base.c.
IsRepairEnabled() [3/13]
override bool IsRepairEnabled () inline private
Definition at line 107 of file BoltActionRifleExternalMagazine_Base.c.
IsRepairEnabled() [4/13]
override bool IsRepairEnabled () inline private
Definition at line 59 of file BoltActionRifleInnerMagazine_Base.c.
IsRepairEnabled() [5/13]
override bool IsRepairEnabled () inline private
Definition at line 69 of file Pistol_Base.c.
IsRepairEnabled() [6/13]
override bool IsRepairEnabled () inline private
Definition at line 115 of file Pistol_Base.c.
IsRepairEnabled() [7/13]
override bool IsRepairEnabled () inline private
Definition at line 59 of file Repeater.c.
IsRepairEnabled() [8/13]
override bool IsRepairEnabled () inline private
Definition at line 71 of file RifleBoltFree_Base.c.
IsRepairEnabled() [9/13]
override bool IsRepairEnabled () inline private
Definition at line 83 of file RifleBoltFree_Base.c.
IsRepairEnabled() [10/13]
override bool IsRepairEnabled () inline private
Definition at line 98 of file RifleBoltLock_Base.c.
IsRepairEnabled() [11/13]
override bool IsRepairEnabled () inline private
Definition at line 110 of file RifleBoltLock_Base.c.
IsRepairEnabled() [12/13]
override bool IsRepairEnabled () inline private
Definition at line 57 of file RifleSingleShot_Base.c.
IsRepairEnabled() [13/13]
override bool IsRepairEnabled () inline private
Definition at line 57 of file MP133.c.
OnEntry() [1/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 54 of file SKS.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [2/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 88 of file BoltActionRifleExternalMagazine_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [3/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 100 of file BoltActionRifleExternalMagazine_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [4/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 53 of file BoltActionRifleInnerMagazine_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [5/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 62 of file Pistol_Base.c.
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnEntry() [6/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 108 of file Pistol_Base.c.
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnEntry() [7/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 53 of file Repeater.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [8/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 64 of file RifleBoltFree_Base.c.
References m_weapon, and Print().
OnEntry() [9/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 76 of file RifleBoltFree_Base.c.
References m_weapon, and Print().
OnEntry() [10/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 91 of file RifleBoltLock_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [11/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 103 of file RifleBoltLock_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [12/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 50 of file RifleSingleShot_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [13/13]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 50 of file MP133.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [1/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 55 of file SKS.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [2/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 89 of file BoltActionRifleExternalMagazine_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [3/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 101 of file BoltActionRifleExternalMagazine_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [4/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 54 of file BoltActionRifleInnerMagazine_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [5/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 63 of file Pistol_Base.c.
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [6/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 109 of file Pistol_Base.c.
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [7/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 54 of file Repeater.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [8/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 65 of file RifleBoltFree_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [9/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 77 of file RifleBoltFree_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [10/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 92 of file RifleBoltLock_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [11/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 104 of file RifleBoltLock_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [12/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 51 of file RifleSingleShot_Base.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [13/13]
override void OnExit (WeaponEventBase e) inline private
Definition at line 51 of file MP133.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Firearms/AutomaticRifle/SKS.c
P:/scripts/4_World/Entities/Firearms/BoltActionRifleExternalMagazine_Base.c
P:/scripts/4_World/Entities/Firearms/BoltActionRifleInnerMagazine_Base.c
P:/scripts/4_World/Entities/Firearms/Pistol_Base.c
P:/scripts/4_World/Entities/Firearms/Rifle/Repeater.c
P:/scripts/4_World/Entities/Firearms/RifleBoltFree_Base.c
P:/scripts/4_World/Entities/Firearms/RifleBoltLock_Base.c
P:/scripts/4_World/Entities/Firearms/RifleSingleShot_Base.c
P:/scripts/4_World/Entities/Firearms/Shotgun/MP133.c