DayZ Scripts Documentation: WeaponManager Class Reference
WeaponManager Class Reference
Private Member Functions
void WeaponManager (PlayerBase player)
bool CanFire (Weapon_Base wpn)
bool CanAttachMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck=true)
bool CanSwapMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck=true)
bool CanDetachMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck=true)
bool CanLoadBullet (Weapon_Base wpn, Magazine mag, bool reservationCheck=true)
bool CanUnjam (Weapon_Base wpn, bool reservationCheck=true)
bool CanEjectBullet (Weapon_Base wpn, bool reservationCheck=true)
void SetEjectBulletTryTimestamp ()
bool InventoryReservation (Magazine mag, InventoryLocation invLoc)
bool AttachMagazine (Magazine mag, ActionBase control_action=NULL)
bool DetachMagazine (InventoryLocation invLoc, ActionBase control_action=NULL)
bool SwapMagazine (Magazine mag, ActionBase control_action=NULL)
bool SwapMagazineEx (Magazine mag, InventoryLocation invLoc, ActionBase control_action=NULL)
bool LoadBullet (Magazine mag, ActionBase control_action=NULL)
bool LoadMultiBullet (Magazine mag, ActionBase control_action=NULL)
void LoadMultiBulletStop ()
bool Unjam (ActionBase control_action=NULL)
bool EjectBullet (ActionBase control_action=NULL)
bool CanEjectBulletVerified ()
bool EjectBulletVerified (ActionBase control_action=NULL)
bool SetNextMuzzleMode ()
void Fire (Weapon_Base wpn)
private void Synchronize ()
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
bool StartAction (int action, Magazine mag, InventoryLocation il, ActionBase control_action=NULL)
void StartPendingAction ()
bool IsRunning ()
void SetRunning (bool value)
void Refresh ()
void Update (float deltaT)
void OnWeaponActionEnd ()
void DelayedRefreshAnimationState (int delay)
void RefreshAnimationState ()
bool WantContinue ()
Magazine GetPreparedMagazine ()
Magazine GetNextPreparedMagazine (out int startIdx)
void OnMagazineInventoryEnter (Magazine mag)
void OnMagazineInventoryExit (Magazine mag)
void OnMagazineAttach (Magazine mag)
void OnMagazineDetach (Magazine mag)
int CompareMagazinesSuitability (Magazine mag1, Magazine mag2)
void SortMagazineAfterLoad ()
void SetSutableMagazines ()
void OnLiftWeapon ()
string GetCurrentModeName ()
bool PrepareInventoryLocationForMagazineSwap (notnull Weapon_Base wpn, notnull Magazine new_mag, out InventoryLocation new_il)
Private Attributes
const float MAX_DROP_MAGAZINE_DISTANCE_SQ = 4
protected PlayerBase m_player
protected int m_LastAcknowledgmentID
protected int m_PendingWeaponActionAcknowledgmentID
protected Magazine m_PendingTargetMagazine
protected ref InventoryLocation m_TargetInventoryLocation
protected int m_PendingWeaponAction
protected ref InventoryLocation m_PendingInventoryLocation
protected bool m_canEnd
protected bool m_justStart
protected bool m_InProgress
protected bool m_IsEventSended
protected bool m_WantContinue
protected bool m_InIronSight
protected bool m_InOptic
protected bool m_readyToStart
protected Weapon_Base m_WeaponInHand
protected MagazineStorage m_MagazineInHand
protected ActionBase m_ControlAction
protected int m_ForceEjectBulletTimestamp
protected const int FORCE_EJECT_BULLET_TIMEOUT = 2000
protected ref array< Magazine > m_MagazinePilesInInventory
protected ref array< MagazineStorage > m_MagazineStorageInInventory
protected ref array< Magazine > m_SuitableMagazines
protected Magazine m_PreparedMagazine
protected float m_NewJamChance
protected bool m_WaitToSyncJamChance
protected int m_AnimationRefreshCooldown
Detailed Description
Definition at line 1 of file WeaponManager.c.
Constructor & Destructor Documentation
WeaponManager()
void WeaponManager (PlayerBase player) inline private
Definition at line 45 of file WeaponManager.c.
References m_AnimationRefreshCooldown, m_canEnd, m_ControlAction, m_ForceEjectBulletTimestamp, m_InProgress, m_IsEventSended, m_LastAcknowledgmentID, m_MagazineInHand, m_MagazinePilesInInventory, m_MagazineStorageInInventory, m_NewJamChance, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_PendingWeaponActionAcknowledgmentID, m_player, m_PreparedMagazine, m_readyToStart, m_SuitableMagazines, m_WaitToSyncJamChance, m_WantContinue, and m_WeaponInHand.
Member Function Documentation
AttachMagazine()
bool AttachMagazine (Magazine mag, ActionBase control_action = NULL) inline private
Definition at line 344 of file WeaponManager.c.
References AT_WPN_ATTACH_MAGAZINE, and StartAction().
Referenced by HandsContainer::OnPerformCombination().
CanAttachMagazine()
bool CanAttachMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck = true) inline private
Definition at line 92 of file WeaponManager.c.
References Class::CastTo(), InventoryLocation::GetParent(), and m_player.
Referenced by ManBase::GetMagazineToReload(), and HandsContainer::OnPerformCombination().
CanDetachMagazine()
bool CanDetachMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck = true) inline private
Definition at line 181 of file WeaponManager.c.
References m_player.
CanEjectBullet()
bool CanEjectBullet (Weapon_Base wpn, bool reservationCheck = true) inline private
Definition at line 257 of file WeaponManager.c.
References Weapon_Base::CanEjectBullet(), and m_player.
CanEjectBulletVerified()
bool CanEjectBulletVerified () inline private
Definition at line 394 of file WeaponManager.c.
References FORCE_EJECT_BULLET_TIMEOUT, GetGame(), CGame::GetTime(), m_ForceEjectBulletTimestamp, and m_WeaponInHand.
CanFire()
bool CanFire (Weapon_Base wpn) inline private
Definition at line 79 of file WeaponManager.c.
References m_player.
CanLoadBullet()
bool CanLoadBullet (Weapon_Base wpn, Magazine mag, bool reservationCheck = true) inline private
Definition at line 201 of file WeaponManager.c.
References Weapon_Base::CanChamberBullet(), and m_player.
Referenced by ManBase::GetMagazineToReload(), and Icon::OnPerformCombination().
CanSwapMagazine()
bool CanSwapMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck = true) inline private
Definition at line 133 of file WeaponManager.c.
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), Class::CastTo(), InventoryLocation::GetParent(), and m_player.
Referenced by HandsContainer::GetCombinationFlags(), ManBase::GetMagazineToReload(), and HandsContainer::OnPerformCombination().
CanUnjam()
bool CanUnjam (Weapon_Base wpn, bool reservationCheck = true) inline private
Definition at line 233 of file WeaponManager.c.
References m_player.
CompareMagazinesSuitability()
int CompareMagazinesSuitability (Magazine mag1, Magazine mag2) inline private
Definition at line 1136 of file WeaponManager.c.
Referenced by OnMagazineInventoryEnter().
DelayedRefreshAnimationState()
void DelayedRefreshAnimationState (int delay) inline private
Definition at line 987 of file WeaponManager.c.
References m_AnimationRefreshCooldown, m_WeaponInHand, and RefreshAnimationState().
DetachMagazine()
bool DetachMagazine (InventoryLocation invLoc, ActionBase control_action = NULL) inline private
Definition at line 349 of file WeaponManager.c.
References AT_WPN_DETACH_MAGAZINE, and StartAction().
EjectBullet()
bool EjectBullet (ActionBase control_action = NULL) inline private
Definition at line 389 of file WeaponManager.c.
References AT_WPN_EJECT_BULLET, and StartAction().
EjectBulletVerified()
bool EjectBulletVerified (ActionBase control_action = NULL) inline private
Definition at line 408 of file WeaponManager.c.
References AT_WPN_EJECT_BULLET, GetGame(), CGame::GetTime(), m_ForceEjectBulletTimestamp, m_WeaponInHand, and StartAction().
Fire()
void Fire (Weapon_Base wpn) inline private
Definition at line 431 of file WeaponManager.c.
References m_player.
GetCurrentModeName()
string GetCurrentModeName () inline private
Definition at line 1269 of file WeaponManager.c.
References m_WeaponInHand.
GetNextPreparedMagazine()
Magazine GetNextPreparedMagazine (out int startIdx) inline private
Definition at line 1038 of file WeaponManager.c.
References m_SuitableMagazines.
Referenced by FirearmActionLoadMultiBulletQuick::Start().
GetPreparedMagazine()
Magazine GetPreparedMagazine () inline private
Definition at line 1021 of file WeaponManager.c.
References m_SuitableMagazines.
InventoryReservation()
bool InventoryReservation (Magazine mag, InventoryLocation invLoc) inline private
Definition at line 285 of file WeaponManager.c.
References GameInventory::c_InventoryReservationTimeoutMS, InventoryLocation::GetItem(), m_PendingInventoryLocation, m_PendingTargetMagazine, m_player, m_TargetInventoryLocation, m_WeaponInHand, and InventoryLocation::SetAttachment().
Referenced by StartAction().
IsRunning()
bool IsRunning () inline private
Definition at line 819 of file WeaponManager.c.
References m_InProgress.
LoadBullet()
bool LoadBullet (Magazine mag, ActionBase control_action = NULL) inline private
Definition at line 369 of file WeaponManager.c.
References AT_WPN_LOAD_BULLET, and StartAction().
Referenced by Icon::OnPerformCombination(), and HandsContainer::OnPerformCombination().
LoadMultiBullet()
bool LoadMultiBullet (Magazine mag, ActionBase control_action = NULL) inline private
Definition at line 374 of file WeaponManager.c.
References AT_WPN_LOAD_MULTI_BULLETS_START, and StartAction().
LoadMultiBulletStop()
void LoadMultiBulletStop () inline private
Definition at line 379 of file WeaponManager.c.
References m_InProgress, and m_WantContinue.
OnInputUserDataProcess()
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx) inline private
Definition at line 575 of file WeaponManager.c.
References AT_WPN_ATTACH_MAGAZINE, AT_WPN_DETACH_MAGAZINE, AT_WPN_EJECT_BULLET, AT_WPN_LOAD_BULLET, AT_WPN_LOAD_MULTI_BULLETS_START, AT_WPN_SET_NEXT_MUZZLE_MODE, AT_WPN_SWAP_MAGAZINE, AT_WPN_UNJAM, CGame::ClearJuncture(), Error(), GetGame(), InventoryLocation::GetItem(), INPUT_UDT_WEAPON_ACTION, InventoryLocation::IsValid(), m_InProgress, m_IsEventSended, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_PendingWeaponActionAcknowledgmentID, m_player, Serializer::Read(), InventoryLocation::ReadFromContext(), DayZPlayerSyncJunctures::SendWeaponActionAcknowledgment(), and InventoryLocation::SetAttachment().
OnLiftWeapon()
void OnLiftWeapon () inline private
Definition at line 1263 of file WeaponManager.c.
References m_WeaponInHand.
OnMagazineAttach()
void OnMagazineAttach (Magazine mag) inline private
Definition at line 1126 of file WeaponManager.c.
References OnMagazineInventoryExit().
OnMagazineDetach()
void OnMagazineDetach (Magazine mag) inline private
Definition at line 1131 of file WeaponManager.c.
References OnMagazineInventoryEnter().
OnMagazineInventoryEnter()
void OnMagazineInventoryEnter (Magazine mag) inline private
Definition at line 1051 of file WeaponManager.c.
References CompareMagazinesSuitability(), m_MagazinePilesInInventory, m_MagazineStorageInInventory, and SetSutableMagazines().
Referenced by OnMagazineDetach().
OnMagazineInventoryExit()
void OnMagazineInventoryExit (Magazine mag) inline private
Definition at line 1109 of file WeaponManager.c.
References m_MagazinePilesInInventory, m_MagazineStorageInInventory, and m_SuitableMagazines.
Referenced by OnMagazineAttach().
OnSyncJuncture()
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx) inline private
Definition at line 525 of file WeaponManager.c.
References GetGame(), m_InProgress, m_NewJamChance, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_PendingWeaponActionAcknowledgmentID, m_player, m_readyToStart, m_TargetInventoryLocation, Serializer::Read(), DayZPlayerSyncJunctures::SJ_WEAPON_ACTION_ACK_ACCEPT, DayZPlayerSyncJunctures::SJ_WEAPON_ACTION_ACK_REJECT, and DayZPlayerSyncJunctures::SJ_WEAPON_SET_JAMMING_CHANCE.
OnWeaponActionEnd()
void OnWeaponActionEnd () inline private
Definition at line 942 of file WeaponManager.c.
References CGame::ClearJuncture(), GetGame(), InventoryLocation::GetItem(), m_ControlAction, m_InProgress, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_PendingWeaponActionAcknowledgmentID, m_player, m_readyToStart, m_TargetInventoryLocation, m_WantContinue, and InventoryLocation::SetHands().
Referenced by Refresh(), StartPendingAction(), and Update().
PrepareInventoryLocationForMagazineSwap()
bool PrepareInventoryLocationForMagazineSwap (notnull Weapon_Base wpn, notnull Magazine new_mag, out InventoryLocation new_il) inline private
Definition at line 1279 of file WeaponManager.c.
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), and m_player.
Referenced by SwapMagazine().
Refresh()
void Refresh () inline private
Definition at line 829 of file WeaponManager.c.
References OnWeaponActionEnd().
RefreshAnimationState()
void RefreshAnimationState () inline private
Definition at line 999 of file WeaponManager.c.
References m_player, m_WeaponInHand, and HumanCommandWeapons::SetInitState().
Referenced by DelayedRefreshAnimationState(), and Update().
SetEjectBulletTryTimestamp()
void SetEjectBulletTryTimestamp () inline private
Definition at line 280 of file WeaponManager.c.
References GetGame(), CGame::GetTime(), and m_ForceEjectBulletTimestamp.
SetNextMuzzleMode()
bool SetNextMuzzleMode () inline private
Definition at line 426 of file WeaponManager.c.
References AT_WPN_SET_NEXT_MUZZLE_MODE, and StartAction().
SetRunning()
void SetRunning (bool value) inline private
Definition at line 824 of file WeaponManager.c.
References m_InProgress.
SetSutableMagazines()
void SetSutableMagazines () inline private
Definition at line 1202 of file WeaponManager.c.
References m_MagazineInHand, m_MagazinePilesInInventory, m_MagazineStorageInInventory, m_PreparedMagazine, m_SuitableMagazines, and m_WeaponInHand.
Referenced by OnMagazineInventoryEnter(), SortMagazineAfterLoad(), and Update().
SortMagazineAfterLoad()
void SortMagazineAfterLoad () inline private
Definition at line 1141 of file WeaponManager.c.
References m_MagazinePilesInInventory, m_MagazineStorageInInventory, and SetSutableMagazines().
StartAction()
bool StartAction (int action, Magazine mag, InventoryLocation il, ActionBase control_action = NULL) inline private
Definition at line 717 of file WeaponManager.c.
References ActionBase(), ScriptInputUserData::CanStoreInputUserData(), GetGame(), InventoryReservation(), m_ControlAction, m_InProgress, m_IsEventSended, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_readyToStart, StartPendingAction(), and Synchronize().
Referenced by AttachMagazine(), DetachMagazine(), EjectBullet(), EjectBulletVerified(), LoadBullet(), LoadMultiBullet(), SetNextMuzzleMode(), SwapMagazine(), SwapMagazineEx(), and Unjam().
StartPendingAction()
void StartPendingAction () inline private
Definition at line 754 of file WeaponManager.c.
References AT_WPN_ATTACH_MAGAZINE, AT_WPN_DETACH_MAGAZINE, AT_WPN_EJECT_BULLET, AT_WPN_LOAD_BULLET, AT_WPN_LOAD_MULTI_BULLETS_END, AT_WPN_LOAD_MULTI_BULLETS_START, AT_WPN_SET_NEXT_MUZZLE_MODE, AT_WPN_SWAP_MAGAZINE, AT_WPN_UNJAM, Error(), InventoryLocation::GetItem(), m_canEnd, m_InProgress, m_IsEventSended, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_player, m_WantContinue, m_WeaponInHand, and OnWeaponActionEnd().
Referenced by StartAction(), and Update().
SwapMagazine()
bool SwapMagazine (Magazine mag, ActionBase control_action = NULL) inline private
Definition at line 354 of file WeaponManager.c.
References AT_WPN_SWAP_MAGAZINE, m_WeaponInHand, PrepareInventoryLocationForMagazineSwap(), and StartAction().
Referenced by HandsContainer::OnPerformCombination().
SwapMagazineEx()
bool SwapMagazineEx (Magazine mag, InventoryLocation invLoc, ActionBase control_action = NULL) inline private
Definition at line 364 of file WeaponManager.c.
References AT_WPN_SWAP_MAGAZINE, and StartAction().
Synchronize()
private void Synchronize () inline private
Definition at line 466 of file WeaponManager.c.
References AT_WPN_ATTACH_MAGAZINE, AT_WPN_DETACH_MAGAZINE, AT_WPN_EJECT_BULLET, AT_WPN_LOAD_BULLET, AT_WPN_LOAD_MULTI_BULLETS_START, AT_WPN_SWAP_MAGAZINE, AT_WPN_UNJAM, GetGame(), INPUT_UDT_WEAPON_ACTION, m_LastAcknowledgmentID, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_PendingWeaponActionAcknowledgmentID, ScriptInputUserData::Send(), Serializer::Write(), and InventoryLocation::WriteToContext().
Referenced by StartAction().
Unjam()
bool Unjam (ActionBase control_action = NULL) inline private
Definition at line 384 of file WeaponManager.c.
References AT_WPN_UNJAM, and StartAction().
Update()
void Update (float deltaT) inline private
Definition at line 834 of file WeaponManager.c.
References Math::AbsFloat(), Weapon_Base::GetChanceToJam(), GetGame(), m_AnimationRefreshCooldown, m_canEnd, m_InIronSight, m_InOptic, m_InProgress, m_IsEventSended, m_justStart, m_MagazineInHand, m_NewJamChance, m_player, m_readyToStart, m_SuitableMagazines, m_WaitToSyncJamChance, m_WeaponInHand, OnWeaponActionEnd(), RefreshAnimationState(), DayZPlayerSyncJunctures::SendWeaponJamChance(), SetSutableMagazines(), and StartPendingAction().
WantContinue()
bool WantContinue () inline private
Definition at line 1016 of file WeaponManager.c.
References m_WantContinue.
Field Documentation
FORCE_EJECT_BULLET_TIMEOUT
protected const int FORCE_EJECT_BULLET_TIMEOUT = 2000 private
Definition at line 28 of file WeaponManager.c.
Referenced by CanEjectBulletVerified().
m_AnimationRefreshCooldown
protected int m_AnimationRefreshCooldown private
Definition at line 43 of file WeaponManager.c.
Referenced by DelayedRefreshAnimationState(), Update(), and WeaponManager().
m_canEnd
protected bool m_canEnd private
Definition at line 15 of file WeaponManager.c.
Referenced by StartPendingAction(), Update(), and WeaponManager().
m_ControlAction
protected ActionBase m_ControlAction private
Definition at line 25 of file WeaponManager.c.
Referenced by OnWeaponActionEnd(), StartAction(), and WeaponManager().
m_ForceEjectBulletTimestamp
protected int m_ForceEjectBulletTimestamp private
Definition at line 26 of file WeaponManager.c.
Referenced by CanEjectBulletVerified(), EjectBulletVerified(), SetEjectBulletTryTimestamp(), and WeaponManager().
m_InIronSight
protected bool m_InIronSight private
Definition at line 20 of file WeaponManager.c.
Referenced by Update().
m_InOptic
protected bool m_InOptic private
Definition at line 21 of file WeaponManager.c.
Referenced by Update().
m_InProgress
protected bool m_InProgress private
Definition at line 17 of file WeaponManager.c.
Referenced by IsRunning(), LoadMultiBulletStop(), OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), SetRunning(), StartAction(), StartPendingAction(), Update(), and WeaponManager().
m_IsEventSended
protected bool m_IsEventSended private
Definition at line 18 of file WeaponManager.c.
Referenced by OnInputUserDataProcess(), StartAction(), StartPendingAction(), Update(), and WeaponManager().
m_justStart
protected bool m_justStart private
Definition at line 16 of file WeaponManager.c.
Referenced by Update().
m_LastAcknowledgmentID
protected int m_LastAcknowledgmentID private
Definition at line 7 of file WeaponManager.c.
Referenced by Synchronize(), and WeaponManager().
m_MagazineInHand
protected MagazineStorage m_MagazineInHand private
Definition at line 24 of file WeaponManager.c.
Referenced by SetSutableMagazines(), Update(), and WeaponManager().
m_MagazinePilesInInventory
protected ref array<Magazine> m_MagazinePilesInInventory private
Definition at line 33 of file WeaponManager.c.
Referenced by OnMagazineInventoryEnter(), OnMagazineInventoryExit(), SetSutableMagazines(), SortMagazineAfterLoad(), and WeaponManager().
m_MagazineStorageInInventory
protected ref array<MagazineStorage> m_MagazineStorageInInventory private
Definition at line 34 of file WeaponManager.c.
Referenced by OnMagazineInventoryEnter(), OnMagazineInventoryExit(), SetSutableMagazines(), SortMagazineAfterLoad(), and WeaponManager().
m_NewJamChance
protected float m_NewJamChance private
Definition at line 39 of file WeaponManager.c.
Referenced by OnSyncJuncture(), Update(), and WeaponManager().
m_PendingInventoryLocation
protected ref InventoryLocation m_PendingInventoryLocation private
Definition at line 13 of file WeaponManager.c.
Referenced by InventoryReservation(), OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), StartAction(), StartPendingAction(), Synchronize(), and WeaponManager().
m_PendingTargetMagazine
protected Magazine m_PendingTargetMagazine private
Definition at line 10 of file WeaponManager.c.
Referenced by InventoryReservation(), OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), StartAction(), StartPendingAction(), Synchronize(), and WeaponManager().
m_PendingWeaponAction
protected int m_PendingWeaponAction private
Definition at line 12 of file WeaponManager.c.
Referenced by OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), StartAction(), StartPendingAction(), Synchronize(), and WeaponManager().
m_PendingWeaponActionAcknowledgmentID
protected int m_PendingWeaponActionAcknowledgmentID private
Definition at line 9 of file WeaponManager.c.
Referenced by OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), Synchronize(), and WeaponManager().
m_player
protected PlayerBase m_player private
Definition at line 5 of file WeaponManager.c.
Referenced by CanAttachMagazine(), CanDetachMagazine(), CanEjectBullet(), CanFire(), CanLoadBullet(), CanSwapMagazine(), CanUnjam(), Fire(), InventoryReservation(), OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), PrepareInventoryLocationForMagazineSwap(), RefreshAnimationState(), StartPendingAction(), Update(), and WeaponManager().
m_PreparedMagazine
protected Magazine m_PreparedMagazine private
Definition at line 36 of file WeaponManager.c.
Referenced by SetSutableMagazines(), and WeaponManager().
m_readyToStart
protected bool m_readyToStart private
Definition at line 22 of file WeaponManager.c.
Referenced by OnSyncJuncture(), OnWeaponActionEnd(), StartAction(), Update(), and WeaponManager().
m_SuitableMagazines
protected ref array<Magazine> m_SuitableMagazines private
Definition at line 35 of file WeaponManager.c.
Referenced by GetNextPreparedMagazine(), GetPreparedMagazine(), OnMagazineInventoryExit(), SetSutableMagazines(), Update(), and WeaponManager().
m_TargetInventoryLocation
protected ref InventoryLocation m_TargetInventoryLocation private
Definition at line 11 of file WeaponManager.c.
Referenced by InventoryReservation(), OnSyncJuncture(), and OnWeaponActionEnd().
m_WaitToSyncJamChance
protected bool m_WaitToSyncJamChance private
Definition at line 40 of file WeaponManager.c.
Referenced by Update(), and WeaponManager().
m_WantContinue
protected bool m_WantContinue private
Definition at line 19 of file WeaponManager.c.
Referenced by LoadMultiBulletStop(), OnWeaponActionEnd(), StartPendingAction(), WantContinue(), and WeaponManager().
m_WeaponInHand
protected Weapon_Base m_WeaponInHand private
Definition at line 23 of file WeaponManager.c.
Referenced by CanEjectBulletVerified(), DelayedRefreshAnimationState(), EjectBulletVerified(), GetCurrentModeName(), InventoryReservation(), OnLiftWeapon(), RefreshAnimationState(), SetSutableMagazines(), StartPendingAction(), SwapMagazine(), Update(), and WeaponManager().
MAX_DROP_MAGAZINE_DISTANCE_SQ
const float MAX_DROP_MAGAZINE_DISTANCE_SQ = 4 private
Definition at line 3 of file WeaponManager.c.
Referenced by WeaponStateBase::OnAbort(), OnAbort(), and WeaponStateBase::OnExit().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/Weapons/WeaponManager.c