DayZ Scripts Documentation: UIPopupScript Class Reference
UIPopupScript Class Reference
Private Member Functions
void UIPopupScript (Widget wgt)
void OnOpen (Param param)
void OnClose ()
void Show (bool show)
bool OnClick (Widget w, int x, int y, int button)
bool OnChange (Widget w, int x, int y, bool finished)
protected UIPopupScript PopupBack ()
protected UIPopupScript PopupOpen (int popup_id, Param param)
protected PluginSceneManager GetSceneEditor ()
void UIPopupScriptConfigs (Widget wgt)
void ChangeConfigFilter ()
override void OnOpen (Param param)
void AddItemToClipboard (TextListboxWidget text_listbox_widget)
void RenderVariables (int row)
void ExpandHierarchy (int row)
void CollapseHierarchy (int row)
void ClearHierarchy ()
void FindInHierarchy (string class_name)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnClick (Widget w, int x, int y, int button)
void UIPopupScriptEditorSettings (Widget wgt)
override void OnOpen (Param param)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
void UIPopupScriptInitScript (Widget wgt)
override void OnOpen (Param param)
override bool OnClick (Widget w, int x, int y, int button)
void UIPopupScriptNotify (Widget wgt)
override bool OnClick (Widget w, int x, int y, int button)
void SetLabelText (string text)
void UIPopupScriptPositionManager (Widget wgt)
override void OnOpen (Param param)
override bool OnClick (Widget w, int x, int y, int button)
void OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
string GetCurrentLocationName ()
void UIPopupScriptPresetNew (Widget wgt)
override bool OnClick (Widget w, int x, int y, int button)
void UIPopupScriptPresetRename (Widget wgt)
override void OnOpen (Param param)
override bool OnClick (Widget w, int x, int y, int button)
void UIPopupScriptSceneDelete (Widget wgt)
override bool OnClick (Widget w, int x, int y, int button)
void SetDeleteName (string scene_name)
void UIPopupScriptSceneManager (Widget wgt)
void ~UIPopupScriptSceneManager ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
void UpdateSceneList ()
override void OnOpen (Param param)
override void OnClose ()
void OnUpdate ()
void ResetSliders ()
void UpdateSliderStartTime (int hour, int minute)
void UpdateSliderStartDay (int month, int day)
void UpdateSliderOvercast ()
void UpdateSliderRain ()
void UpdateSliderFog ()
void UpdateSliderWindForce ()
void UIPopupScriptSceneNew (Widget wgt)
override bool OnClick (Widget w, int x, int y, int button)
void UIPopupScriptSceneRename (Widget wgt)
override bool OnClick (Widget w, int x, int y, int button)
void SetRenameName (string rename_name)
void UIPopupScriptSceneSettings (Widget wgt)
void ~UIPopupScriptSceneSettings ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
override void OnOpen (Param param)
override void OnClose ()
void OnUpdate ()
void ResetSliders ()
void UpdateSliderStartTime (int hour, int minute)
void UpdateSliderStartDay (int month, int day)
void UpdateSliderOvercast ()
void UpdateSliderRain ()
void UpdateSliderFog ()
void UpdateSliderWindForce ()
Private Attributes
protected Widget m_WgtRoot
private ButtonWidget m_BtnOk
private ButtonWidget m_BtnCancel
private ButtonWidget m_BtnCopyToClipboard
private TextListboxWidget m_ConfigHierarchyTextListbox
private TextListboxWidget m_ConfigVariablesTextListbox
private PluginConfigViewer m_ModuleConfigViewer
private EditBoxWidget m_ObjectConfigFilter
private CheckBoxWidget m_WgtTglSeleHighlight
private CheckBoxWidget m_WgtTglSavePlayerPos
private EditBoxWidget m_EdxRotationDelta
private PluginSceneManager m_ModuleSceneManager
private MultilineEditBoxWidget m_MedxInitScript
private ButtonWidget m_BtnRun
private ButtonWidget m_BtnSave
private int m_SceneObjectIndex
private SceneObject m_SceneObject
private TextWidget m_TxtLabel
private TextListboxWidget m_LstPositionList
private EditBoxWidget m_TxtSelectedX
private EditBoxWidget m_TxtSelectedY
private EditBoxWidget m_TxtCurrentX
private EditBoxWidget m_TxtCurrentY
private PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
private ButtonWidget m_TeleportButton
private ButtonWidget m_CancelButton
private EditBoxWidget m_Editbox
private ButtonWidget m_BtnYes
private ButtonWidget m_BtnNo
private string m_DeleteScene
private ButtonWidget m_BtnSceneNew
private ButtonWidget m_BtnSceneLoad
private ButtonWidget m_BtnSceneRename
private ButtonWidget m_BtnSceneDuplicate
private ButtonWidget m_BtnSceneDelete
private TextListboxWidget m_LstListScenes
private TextWidget m_TxtWeatherTime
private SliderWidget m_SldStartTime
private TextWidget m_TxtStartTimeValue
private SliderWidget m_SldStartDay
private TextWidget m_TxtStartDayValue
private SliderWidget m_SldOvercast
private TextWidget m_TxtOvercastValue
private SliderWidget m_SldRain
private TextWidget m_TxtRainValue
private SliderWidget m_SldFog
private TextWidget m_TxtFogValue
private SliderWidget m_SldWindForce
private TextWidget m_TxtWindForceValue
private int m_OrigYear
private int m_OrigMonth
private int m_OrigDay
private int m_OrigHour
private int m_OrigMinute
private float m_OrigOvercast
private float m_OrigRain
private float m_OrigFog
private float m_OrigWindForce
private int m_CurrYear
private int m_CurrMonth
private int m_CurrDay
private int m_CurrHour
private int m_CurrMinute
private float m_CurrOvercast
private float m_CurrRain
private float m_CurrFog
private float m_CurrWindForce
private string m_RenameName
Static Private Attributes
static private const int m_DaysInMonth [12] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
Detailed Description
Definition at line 1 of file UIPopupScript.c.
Constructor & Destructor Documentation
UIPopupScript()
void UIPopupScript (Widget wgt) inline private
Definition at line 6 of file UIPopupScript.c.
References m_WgtRoot.
~UIPopupScriptSceneManager()
void ~UIPopupScriptSceneManager () inline private
Definition at line 87 of file UIPopupScriptSceneManager.c.
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), OnUpdate(), and ScriptInvoker::Remove().
~UIPopupScriptSceneSettings()
void ~UIPopupScriptSceneSettings () inline private
Definition at line 72 of file UIPopupScriptSceneSettings.c.
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), OnUpdate(), and ScriptInvoker::Remove().
Member Function Documentation
AddItemToClipboard()
void AddItemToClipboard (TextListboxWidget text_listbox_widget) inline private
Definition at line 41 of file UIPopupScriptConfigs.c.
References CGame::CopyToClipboard(), and GetGame().
Referenced by OnClick().
ChangeConfigFilter()
void ChangeConfigFilter () inline private
Definition at line 23 of file UIPopupScriptConfigs.c.
References ClearHierarchy(), and FindInHierarchy().
Referenced by OnChange().
ClearHierarchy()
void ClearHierarchy () inline private
Definition at line 155 of file UIPopupScriptConfigs.c.
References string::Get(), and Debug::GetBaseConfigClasses().
Referenced by ChangeConfigFilter(), and OnOpen().
CollapseHierarchy()
void CollapseHierarchy (int row) inline private
Definition at line 109 of file UIPopupScriptConfigs.c.
References x.
Referenced by OnClick().
ExpandHierarchy()
void ExpandHierarchy (int row) inline private
Definition at line 69 of file UIPopupScriptConfigs.c.
References string::Get().
Referenced by OnClick().
FindInHierarchy()
void FindInHierarchy (string class_name) inline private
Definition at line 184 of file UIPopupScriptConfigs.c.
References class_name, string::Contains(), string::Get(), Debug::GetBaseConfigClasses(), string::Split(), and string::ToLower().
Referenced by ChangeConfigFilter().
GetCurrentLocationName()
string GetCurrentLocationName () inline private
Definition at line 84 of file UIPopupScriptPositionManager.c.
GetSceneEditor()
protected PluginSceneManager GetSceneEditor () inline private
Definition at line 55 of file UIPopupScript.c.
References GetPlugin().
OnChange() [1/5]
bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 29 of file UIPopupScript.c.
OnChange() [2/5]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 225 of file UIPopupScriptConfigs.c.
References ChangeConfigFilter(), x, and y.
OnChange() [3/5]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 63 of file UIPopupScriptEditorSettings.c.
OnChange() [4/5]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 205 of file UIPopupScriptSceneManager.c.
References Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetWeather(), Weather::GetWindMaximumSpeed(), CGame::GetWorld(), WeatherPhenomenon::Set(), World::SetDate(), Weather::SetWindSpeed(), UpdateSliderFog(), UpdateSliderOvercast(), UpdateSliderRain(), UpdateSliderStartDay(), UpdateSliderStartTime(), and UpdateSliderWindForce().
OnChange() [5/5]
override bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 115 of file UIPopupScriptSceneSettings.c.
References Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetWeather(), CGame::GetWorld(), WeatherPhenomenon::Set(), World::SetDate(), UpdateSliderFog(), UpdateSliderOvercast(), UpdateSliderRain(), UpdateSliderStartDay(), UpdateSliderStartTime(), and UpdateSliderWindForce().
OnClick() [1/13]
bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 24 of file UIPopupScript.c.
OnClick() [2/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 237 of file UIPopupScriptConfigs.c.
References AddItemToClipboard(), CollapseHierarchy(), ExpandHierarchy(), PopupBack(), RenderVariables(), x, and y.
OnClick() [3/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 38 of file UIPopupScriptEditorSettings.c.
References PopupBack(), x, and y.
OnClick() [4/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 53 of file UIPopupScriptInitScript.c.
References PopupBack(), SceneObject::SetInitScript(), x, and y.
OnClick() [5/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 18 of file UIPopupScriptNotify.c.
References PopupBack(), x, and y.
OnClick() [6/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 55 of file UIPopupScriptPositionManager.c.
References PopupBack().
OnClick() [7/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 18 of file UIPopupScriptPresetNew.c.
References GetGame(), GetPlugin(), m_ConfigDebugProfile, m_WgtRoot, PopupBack(), x, and y.
OnClick() [8/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 26 of file UIPopupScriptPresetRename.c.
References GetGame(), m_WgtRoot, PopupBack(), x, and y.
OnClick() [9/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 19 of file UIPopupScriptSceneDelete.c.
References GetPlugin(), PopupBack(), STRING_EMPTY, x, and y.
OnClick() [10/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 95 of file UIPopupScriptSceneManager.c.
References Weather::GetFog(), GetGame(), Weather::GetOvercast(), GetPlugin(), Weather::GetRain(), CGame::GetWeather(), CGame::GetWorld(), m_CurrDay, m_CurrFog, m_CurrHour, m_CurrMinute, m_CurrMonth, m_CurrOvercast, m_CurrRain, m_CurrWindForce, m_CurrYear, PopupBack(), PopupOpen(), WeatherPhenomenon::Set(), World::SetDate(), Weather::SetWindSpeed(), UpdateSceneList(), x, and y.
OnClick() [11/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 18 of file UIPopupScriptSceneNew.c.
References GetPlugin(), Log(), m_WgtRoot, PopupBack(), x, and y.
OnClick() [12/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 19 of file UIPopupScriptSceneRename.c.
References GetPlugin(), m_WgtRoot, PopupBack(), STRING_EMPTY, x, and y.
OnClick() [13/13]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 79 of file UIPopupScriptSceneSettings.c.
References GetPlugin(), m_CurrDay, m_CurrFog, m_CurrHour, m_CurrMinute, m_CurrMonth, m_CurrOvercast, m_CurrRain, m_CurrWindForce, m_CurrYear, PopupBack(), x, and y.
OnClose() [1/3]
void OnClose () inline private
Definition at line 15 of file UIPopupScript.c.
OnClose() [2/3]
override void OnClose () inline private
Definition at line 351 of file UIPopupScriptSceneManager.c.
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), OnUpdate(), and ScriptInvoker::Remove().
OnClose() [3/3]
override void OnClose () inline private
Definition at line 233 of file UIPopupScriptSceneSettings.c.
References Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetWeather(), CGame::GetWorld(), WeatherPhenomenon::Set(), and World::SetDate().
OnItemSelected()
void OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
Definition at line 75 of file UIPopupScriptPositionManager.c.
OnOpen() [1/8]
void OnOpen (Param param) inline private
Definition at line 11 of file UIPopupScript.c.
Referenced by UIScriptedMenu::PopupOpen().
OnOpen() [2/8]
override void OnOpen (Param param) inline private
Definition at line 35 of file UIPopupScriptConfigs.c.
References ClearHierarchy(), and GetPlugin().
OnOpen() [3/8]
override void OnOpen (Param param) inline private
Definition at line 28 of file UIPopupScriptEditorSettings.c.
OnOpen() [4/8]
override void OnOpen (Param param) inline private
Definition at line 31 of file UIPopupScriptInitScript.c.
References SceneObject::GetInitScript().
OnOpen() [5/8]
override void OnOpen (Param param) inline private
Definition at line 38 of file UIPopupScriptPositionManager.c.
References ToString().
OnOpen() [6/8]
override void OnOpen (Param param) inline private
Definition at line 17 of file UIPopupScriptPresetRename.c.
References GetGame().
OnOpen() [7/8]
override void OnOpen (Param param) inline private
Definition at line 317 of file UIPopupScriptSceneManager.c.
References CALL_CATEGORY_SYSTEM, WeatherPhenomenon::GetActual(), World::GetDate(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetUpdateQueue(), CGame::GetWeather(), Weather::GetWindSpeed(), CGame::GetWorld(), ScriptInvoker::Insert(), m_OrigDay, m_OrigFog, m_OrigHour, m_OrigMinute, m_OrigMonth, m_OrigOvercast, m_OrigRain, m_OrigWindForce, m_OrigYear, OnUpdate(), Print(), ResetSliders(), and UpdateSceneList().
OnOpen() [8/8]
override void OnOpen (Param param) inline private
Definition at line 201 of file UIPopupScriptSceneSettings.c.
References CALL_CATEGORY_SYSTEM, WeatherPhenomenon::GetActual(), World::GetDate(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetUpdateQueue(), CGame::GetWeather(), Weather::GetWindSpeed(), CGame::GetWorld(), ScriptInvoker::Insert(), m_OrigDay, m_OrigFog, m_OrigHour, m_OrigMinute, m_OrigMonth, m_OrigOvercast, m_OrigRain, m_OrigWindForce, m_OrigYear, OnUpdate(), Print(), and ResetSliders().
OnUpdate() [1/2]
void OnUpdate () inline private
Definition at line 359 of file UIPopupScriptSceneManager.c.
References GetGame(), GetTime(), and ToString().
OnUpdate() [2/2]
void OnUpdate () inline private
Definition at line 247 of file UIPopupScriptSceneSettings.c.
References GetGame(), GetTime(), and ToString().
PopupBack()
protected UIPopupScript PopupBack () inline private
Definition at line 37 of file UIPopupScript.c.
References GetGame(), and PopupBack().
Referenced by OnClick(), and PopupBack().
PopupOpen()
protected UIPopupScript PopupOpen (int popup_id, Param param) inline private
Definition at line 46 of file UIPopupScript.c.
References GetGame(), and PopupOpen().
Referenced by OnClick(), and PopupOpen().
RenderVariables()
void RenderVariables (int row) inline private
Definition at line 52 of file UIPopupScriptConfigs.c.
References path.
Referenced by OnClick().
ResetSliders() [1/2]
void ResetSliders () inline private
Definition at line 367 of file UIPopupScriptSceneManager.c.
References WeatherPhenomenon::GetActual(), World::GetDate(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetWeather(), Weather::GetWindMaximumSpeed(), CGame::GetWorld(), Weather::SetWindSpeed(), UpdateSliderFog(), UpdateSliderOvercast(), UpdateSliderRain(), UpdateSliderStartDay(), UpdateSliderStartTime(), and UpdateSliderWindForce().
Referenced by OnOpen().
ResetSliders() [2/2]
void ResetSliders () inline private
Definition at line 255 of file UIPopupScriptSceneSettings.c.
References WeatherPhenomenon::GetActual(), World::GetDate(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetWeather(), Weather::GetWindMaximumSpeed(), Weather::GetWindSpeed(), CGame::GetWorld(), UpdateSliderFog(), UpdateSliderOvercast(), UpdateSliderRain(), UpdateSliderStartDay(), UpdateSliderStartTime(), and UpdateSliderWindForce().
SetDeleteName()
void SetDeleteName (string scene_name) inline private
Definition at line 43 of file UIPopupScriptSceneDelete.c.
SetLabelText()
void SetLabelText (string text) inline private
Definition at line 35 of file UIPopupScriptNotify.c.
SetRenameName()
void SetRenameName (string rename_name) inline private
Definition at line 49 of file UIPopupScriptSceneRename.c.
Show()
void Show (bool show) inline private
Definition at line 19 of file UIPopupScript.c.
References m_WgtRoot.
Referenced by UIScriptedMenu::PopupBack(), and UIScriptedMenu::PopupOpen().
UIPopupScriptConfigs()
void UIPopupScriptConfigs (Widget wgt) inline private
Definition at line 14 of file UIPopupScriptConfigs.c.
UIPopupScriptEditorSettings()
void UIPopupScriptEditorSettings (Widget wgt) inline private
Definition at line 14 of file UIPopupScriptEditorSettings.c.
References GetPlugin().
UIPopupScriptInitScript()
void UIPopupScriptInitScript (Widget wgt) inline private
Definition at line 17 of file UIPopupScriptInitScript.c.
References GetPlugin().
UIPopupScriptNotify()
void UIPopupScriptNotify (Widget wgt) inline private
Definition at line 9 of file UIPopupScriptNotify.c.
UIPopupScriptPositionManager()
void UIPopupScriptPositionManager (Widget wgt) inline private
Definition at line 15 of file UIPopupScriptPositionManager.c.
References GetPlugin().
UIPopupScriptPresetNew()
void UIPopupScriptPresetNew (Widget wgt) inline private
Definition at line 9 of file UIPopupScriptPresetNew.c.
UIPopupScriptPresetRename()
void UIPopupScriptPresetRename (Widget wgt) inline private
Definition at line 10 of file UIPopupScriptPresetRename.c.
UIPopupScriptSceneDelete()
void UIPopupScriptSceneDelete (Widget wgt) inline private
Definition at line 10 of file UIPopupScriptSceneDelete.c.
UIPopupScriptSceneManager()
void UIPopupScriptSceneManager (Widget wgt) inline private
Definition at line 53 of file UIPopupScriptSceneManager.c.
UIPopupScriptSceneNew()
void UIPopupScriptSceneNew (Widget wgt) inline private
Definition at line 9 of file UIPopupScriptSceneNew.c.
UIPopupScriptSceneRename()
void UIPopupScriptSceneRename (Widget wgt) inline private
Definition at line 10 of file UIPopupScriptSceneRename.c.
UIPopupScriptSceneSettings()
void UIPopupScriptSceneSettings (Widget wgt) inline private
Definition at line 46 of file UIPopupScriptSceneSettings.c.
UpdateSceneList()
void UpdateSceneList () inline private
Definition at line 292 of file UIPopupScriptSceneManager.c.
References GetPlugin().
Referenced by OnClick(), and OnOpen().
UpdateSliderFog() [1/2]
void UpdateSliderFog () inline private
Definition at line 425 of file UIPopupScriptSceneManager.c.
Referenced by OnChange(), and ResetSliders().
UpdateSliderFog() [2/2]
void UpdateSliderFog () inline private
Definition at line 312 of file UIPopupScriptSceneSettings.c.
UpdateSliderOvercast() [1/2]
void UpdateSliderOvercast () inline private
Definition at line 413 of file UIPopupScriptSceneManager.c.
Referenced by OnChange(), and ResetSliders().
UpdateSliderOvercast() [2/2]
void UpdateSliderOvercast () inline private
Definition at line 300 of file UIPopupScriptSceneSettings.c.
UpdateSliderRain() [1/2]
void UpdateSliderRain () inline private
Definition at line 419 of file UIPopupScriptSceneManager.c.
Referenced by OnChange(), and ResetSliders().
UpdateSliderRain() [2/2]
void UpdateSliderRain () inline private
Definition at line 306 of file UIPopupScriptSceneSettings.c.
UpdateSliderStartDay() [1/2]
void UpdateSliderStartDay (int month, int day) inline private
Definition at line 407 of file UIPopupScriptSceneManager.c.
Referenced by OnChange(), and ResetSliders().
UpdateSliderStartDay() [2/2]
void UpdateSliderStartDay (int month, int day) inline private
Definition at line 294 of file UIPopupScriptSceneSettings.c.
UpdateSliderStartTime() [1/2]
void UpdateSliderStartTime (int hour, int minute) inline private
Definition at line 401 of file UIPopupScriptSceneManager.c.
Referenced by OnChange(), and ResetSliders().
UpdateSliderStartTime() [2/2]
void UpdateSliderStartTime (int hour, int minute) inline private
Definition at line 288 of file UIPopupScriptSceneSettings.c.
UpdateSliderWindForce() [1/2]
void UpdateSliderWindForce () inline private
Definition at line 431 of file UIPopupScriptSceneManager.c.
References float::ToString().
Referenced by OnChange(), and ResetSliders().
UpdateSliderWindForce() [2/2]
void UpdateSliderWindForce () inline private
Definition at line 318 of file UIPopupScriptSceneSettings.c.
Field Documentation
m_BtnCancel
private ButtonWidget m_BtnCancel private
Definition at line 4 of file UIPopupScriptConfigs.c.
m_BtnCopyToClipboard
private ButtonWidget m_BtnCopyToClipboard private
Definition at line 5 of file UIPopupScriptConfigs.c.
m_BtnNo
private ButtonWidget m_BtnNo private
Definition at line 4 of file UIPopupScriptSceneDelete.c.
m_BtnOk
private ButtonWidget m_BtnOk private
Definition at line 3 of file UIPopupScriptConfigs.c.
m_BtnRun
private ButtonWidget m_BtnRun private
Definition at line 5 of file UIPopupScriptInitScript.c.
m_BtnSave
private ButtonWidget m_BtnSave private
Definition at line 6 of file UIPopupScriptInitScript.c.
m_BtnSceneDelete
private ButtonWidget m_BtnSceneDelete private
Definition at line 8 of file UIPopupScriptSceneManager.c.
m_BtnSceneDuplicate
private ButtonWidget m_BtnSceneDuplicate private
Definition at line 7 of file UIPopupScriptSceneManager.c.
m_BtnSceneLoad
private ButtonWidget m_BtnSceneLoad private
Definition at line 5 of file UIPopupScriptSceneManager.c.
m_BtnSceneNew
private ButtonWidget m_BtnSceneNew private
Definition at line 4 of file UIPopupScriptSceneManager.c.
m_BtnSceneRename
private ButtonWidget m_BtnSceneRename private
Definition at line 6 of file UIPopupScriptSceneManager.c.
m_BtnYes
private ButtonWidget m_BtnYes private
Definition at line 3 of file UIPopupScriptSceneDelete.c.
m_CancelButton
private ButtonWidget m_CancelButton private
Definition at line 10 of file UIPopupScriptPositionManager.c.
m_ConfigDebugProfileFixed
private PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed private
Definition at line 8 of file UIPopupScriptPositionManager.c.
m_ConfigHierarchyTextListbox
private TextListboxWidget m_ConfigHierarchyTextListbox private
Definition at line 7 of file UIPopupScriptConfigs.c.
m_ConfigVariablesTextListbox
private TextListboxWidget m_ConfigVariablesTextListbox private
Definition at line 8 of file UIPopupScriptConfigs.c.
m_CurrDay
private int m_CurrDay private
Definition at line 42 of file UIPopupScriptSceneManager.c.
Referenced by OnClick().
m_CurrFog
private float m_CurrFog private
Definition at line 47 of file UIPopupScriptSceneManager.c.
Referenced by OnClick().
m_CurrHour
private int m_CurrHour private
Definition at line 43 of file UIPopupScriptSceneManager.c.
Referenced by OnClick().
m_CurrMinute
private int m_CurrMinute private
Definition at line 44 of file UIPopupScriptSceneManager.c.
Referenced by OnClick().
m_CurrMonth
private int m_CurrMonth private
Definition at line 41 of file UIPopupScriptSceneManager.c.
Referenced by OnClick().
m_CurrOvercast
private float m_CurrOvercast private
Definition at line 45 of file UIPopupScriptSceneManager.c.
Referenced by OnClick().
m_CurrRain
private float m_CurrRain private
Definition at line 46 of file UIPopupScriptSceneManager.c.
Referenced by OnClick().
m_CurrWindForce
private float m_CurrWindForce private
Definition at line 48 of file UIPopupScriptSceneManager.c.
Referenced by OnClick().
m_CurrYear
private int m_CurrYear private
Definition at line 40 of file UIPopupScriptSceneManager.c.
Referenced by OnClick().
m_DaysInMonth
static private const int m_DaysInMonth = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 } static private
Definition at line 11 of file UIPopupScriptSceneManager.c.
m_DeleteScene
private string m_DeleteScene private
Definition at line 5 of file UIPopupScriptSceneDelete.c.
m_Editbox
private EditBoxWidget m_Editbox private
Definition at line 5 of file UIPopupScriptPresetRename.c.
m_EdxRotationDelta
private EditBoxWidget m_EdxRotationDelta private
Definition at line 5 of file UIPopupScriptEditorSettings.c.
m_LstListScenes
private TextListboxWidget m_LstListScenes private
Definition at line 9 of file UIPopupScriptSceneManager.c.
m_LstPositionList
private TextListboxWidget m_LstPositionList private
Definition at line 3 of file UIPopupScriptPositionManager.c.
m_MedxInitScript
private MultilineEditBoxWidget m_MedxInitScript private
Definition at line 3 of file UIPopupScriptInitScript.c.
m_ModuleConfigViewer
private PluginConfigViewer m_ModuleConfigViewer private
Definition at line 10 of file UIPopupScriptConfigs.c.
m_ModuleSceneManager
private PluginSceneManager m_ModuleSceneManager private
Definition at line 9 of file UIPopupScriptEditorSettings.c.
m_ObjectConfigFilter
private EditBoxWidget m_ObjectConfigFilter private
Definition at line 12 of file UIPopupScriptConfigs.c.
m_OrigDay
private int m_OrigDay private
Definition at line 32 of file UIPopupScriptSceneManager.c.
Referenced by OnOpen().
m_OrigFog
private float m_OrigFog private
Definition at line 37 of file UIPopupScriptSceneManager.c.
Referenced by OnOpen().
m_OrigHour
private int m_OrigHour private
Definition at line 33 of file UIPopupScriptSceneManager.c.
Referenced by OnOpen().
m_OrigMinute
private int m_OrigMinute private
Definition at line 34 of file UIPopupScriptSceneManager.c.
Referenced by OnOpen().
m_OrigMonth
private int m_OrigMonth private
Definition at line 31 of file UIPopupScriptSceneManager.c.
Referenced by OnOpen().
m_OrigOvercast
private float m_OrigOvercast private
Definition at line 35 of file UIPopupScriptSceneManager.c.
Referenced by OnOpen().
m_OrigRain
private float m_OrigRain private
Definition at line 36 of file UIPopupScriptSceneManager.c.
Referenced by OnOpen().
m_OrigWindForce
private float m_OrigWindForce private
Definition at line 38 of file UIPopupScriptSceneManager.c.
Referenced by OnOpen().
m_OrigYear
private int m_OrigYear private
Definition at line 30 of file UIPopupScriptSceneManager.c.
Referenced by OnOpen().
m_RenameName
private string m_RenameName private
Definition at line 5 of file UIPopupScriptSceneRename.c.
m_SceneObject
private SceneObject m_SceneObject private
Definition at line 10 of file UIPopupScriptInitScript.c.
m_SceneObjectIndex
private int m_SceneObjectIndex private
Definition at line 9 of file UIPopupScriptInitScript.c.
m_SldFog
private SliderWidget m_SldFog private
Definition at line 25 of file UIPopupScriptSceneManager.c.
m_SldOvercast
private SliderWidget m_SldOvercast private
Definition at line 21 of file UIPopupScriptSceneManager.c.
m_SldRain
private SliderWidget m_SldRain private
Definition at line 23 of file UIPopupScriptSceneManager.c.
m_SldStartDay
private SliderWidget m_SldStartDay private
Definition at line 19 of file UIPopupScriptSceneManager.c.
m_SldStartTime
private SliderWidget m_SldStartTime private
Definition at line 17 of file UIPopupScriptSceneManager.c.
m_SldWindForce
private SliderWidget m_SldWindForce private
Definition at line 27 of file UIPopupScriptSceneManager.c.
m_TeleportButton
private ButtonWidget m_TeleportButton private
Definition at line 9 of file UIPopupScriptPositionManager.c.
m_TxtCurrentX
private EditBoxWidget m_TxtCurrentX private
Definition at line 6 of file UIPopupScriptPositionManager.c.
m_TxtCurrentY
private EditBoxWidget m_TxtCurrentY private
Definition at line 7 of file UIPopupScriptPositionManager.c.
m_TxtFogValue
private TextWidget m_TxtFogValue private
Definition at line 26 of file UIPopupScriptSceneManager.c.
m_TxtLabel
private TextWidget m_TxtLabel private
Definition at line 4 of file UIPopupScriptNotify.c.
m_TxtOvercastValue
private TextWidget m_TxtOvercastValue private
Definition at line 22 of file UIPopupScriptSceneManager.c.
m_TxtRainValue
private TextWidget m_TxtRainValue private
Definition at line 24 of file UIPopupScriptSceneManager.c.
m_TxtSelectedX
private EditBoxWidget m_TxtSelectedX private
Definition at line 4 of file UIPopupScriptPositionManager.c.
m_TxtSelectedY
private EditBoxWidget m_TxtSelectedY private
Definition at line 5 of file UIPopupScriptPositionManager.c.
m_TxtStartDayValue
private TextWidget m_TxtStartDayValue private
Definition at line 20 of file UIPopupScriptSceneManager.c.
m_TxtStartTimeValue
private TextWidget m_TxtStartTimeValue private
Definition at line 18 of file UIPopupScriptSceneManager.c.
m_TxtWeatherTime
private TextWidget m_TxtWeatherTime private
Definition at line 15 of file UIPopupScriptSceneManager.c.
m_TxtWindForceValue
private TextWidget m_TxtWindForceValue private
Definition at line 28 of file UIPopupScriptSceneManager.c.
m_WgtRoot
protected Widget m_WgtRoot private
Definition at line 61 of file UIPopupScript.c.
Referenced by Show(), and UIPopupScript().
m_WgtTglSavePlayerPos
private CheckBoxWidget m_WgtTglSavePlayerPos private
Definition at line 4 of file UIPopupScriptEditorSettings.c.
m_WgtTglSeleHighlight
private CheckBoxWidget m_WgtTglSeleHighlight private
Definition at line 3 of file UIPopupScriptEditorSettings.c.
The documentation for this class was generated from the following files:
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptConfigs.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptEditorSettings.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptInitScript.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptNotify.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptPositionManager.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptPresetNew.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptPresetRename.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptSceneDelete.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptSceneManager.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptSceneNew.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptSceneRename.c
P:/scripts/5_Mission/GUI/SceneEditorMenu/UIPopupScript/UIPopupScriptSceneSettings.c