DayZ: PluginFileHandler Class Reference
PluginFileHandler Class Reference
Private Member Functions
void PluginConfigHandler ()
override void OnInit ()
override string GetFileName ()
void LoadConfigFile ()
void SaveConfigToFile ()
CfgParam GetParamByName (string name, int cfg_type)
array< ref CfgParam > GetAllParams ()
void ClearParams ()
void RemoveParamByName (string name)
void RenameParam (string name, string new_name)
bool ParamExist (string name)
string ParseParam (CfgParam param)
CfgParam ParseText (string text)
protected int GetTextType (string text)
protected bool IsString (string text)
protected bool IsParam (string text)
protected bool IsArray (string text)
protected bool IsFloat (string text)
protected bool IsInt (string text)
protected bool IsBool (string text)
protected string ParseToValueString (string param_value)
protected float ParseToValueFloat (string param_value)
protected int ParseToValueInt (string param_value)
protected bool ParseToValueBool (string param_value)
protected array< ref CfgParam > ParseToValueArray (string param_value)
void PluginLocalHistoryBase ()
void ~PluginLocalHistoryBase ()
override void OnInit ()
override string GetFileName ()
void AddNewLine (string text)
TStringArray GetAllLines ()
TStringArray GetLastLine ()
void PluginLocalProfile ()
override string GetFileName ()
override void OnInit ()
bool LoadConfigFile ()
void SaveConfigToFile ()
bool IsTextArray (string text)
TStringArray ParseTextToParameter (string text)
TStringArray ParseTextToArray (string text, out TStringArray ret)
array< ref map< string, string > > ParseTextArrayToParameters (string text)
string LoadParameter (string param_name)
TStringArray LoadParameterArray (string param_name)
string LoadSubParameter (string param_name, int sub_array_index, string sub_param_name)
void SaveParameter (string param_name, string value, bool save_in_file=true)
void SaveParameterArray (string param_name, TStringArray value, bool save_in_file=true)
void SaveSubParameterInArray (string param_name, int sub_array_index, string sub_param_name, string sub_param_value, bool save_in_file=true)
void RenameParameter (string old_name, string new_name, bool save_in_file=true)
void RenameParameterArray (string old_name, string new_name, bool save_in_file=true)
void RemoveParameter (string name, bool save_in_file=true)
void RemoveParameterArray (string name, bool save_in_file=true)
void SetParameterString (string name, string value, bool save_in_file=true)
void SetParameterInt (string name, int value, bool save_in_file=true)
void SetParameterFloat (string name, float value, bool save_in_file=true)
void SetParameterBool (string name, bool value, bool save_in_file=true)
void SetParameterArray (string name, TStringArray value, bool save_in_file=true)
void SetSubParameterInArray (string param_name, int sub_array_index, string sub_param_name, string sub_param_value, bool save_in_file=true)
string GetParameterString (string name)
int GetParameterInt (string name)
float GetParameterFloat (string name)
bool GetParameterBool (string name)
TStringArray GetParameterArray (string name)
string GetSubParameterInArrayString (string param_name, int sub_array_index, string sub_param_name)
TStringArray GetAllSubParametersInArrayString (string param_name, string sub_param_name)
Private Attributes
ref array< ref CfgParam > m_CfgParams
ref map< string, string > m_ConfigParams
ref map< string, ref TStringArray > m_ConfigParamsArray
ref map< string, ref map< string, string > > m_ConfigParamsInArray
ref map< string, ref array< ref map< string, string > > > m_ConfigParamsArrayInArray
Detailed Description
Definition at line 1 of file PluginConfigHandler.c.
Constructor & Destructor Documentation
~PluginLocalHistoryBase()
void ~PluginLocalHistoryBase () inline private
Definition at line 8 of file PluginLocalHistoryBase.c.
Member Function Documentation
AddNewLine()
void AddNewLine (string text) inline private
Definition at line 23 of file PluginLocalHistoryBase.c.
References string::Replace().
ClearParams()
void ClearParams () inline private
Definition at line 73 of file PluginConfigHandler.c.
GetAllLines()
TStringArray GetAllLines () inline private
Definition at line 31 of file PluginLocalHistoryBase.c.
References string::Replace().
GetAllParams()
array< ref CfgParam > GetAllParams () inline private
Definition at line 68 of file PluginConfigHandler.c.
GetAllSubParametersInArrayString()
TStringArray GetAllSubParametersInArrayString (string param_name, string sub_param_name) inline private
Definition at line 578 of file PluginLocalProfile.c.
References string::Get(), and STRING_EMPTY.
GetFileName() [1/3]
override string GetFileName () inline private
Definition at line 17 of file PluginConfigHandler.c.
References CFG_FILE_USER_PROFILE.
Referenced by PluginBase::LoadFile(), and PluginBase::SaveFile().
GetFileName() [2/3]
override string GetFileName () inline private
Definition at line 17 of file PluginLocalHistoryBase.c.
References Error(), and STRING_EMPTY.
GetFileName() [3/3]
override string GetFileName () inline private
Definition at line 16 of file PluginLocalProfile.c.
References CFG_FILE_USER_PROFILE.
GetLastLine()
TStringArray GetLastLine () inline private
Definition at line 44 of file PluginLocalHistoryBase.c.
References string::Get().
GetParamByName()
CfgParam GetParamByName (string name, int cfg_type) inline private
Definition at line 48 of file PluginConfigHandler.c.
References CfgParam::CreateParam(), CfgParam::GetName(), and name.
GetParameterArray()
TStringArray GetParameterArray (string name) inline private
Definition at line 544 of file PluginLocalProfile.c.
References name.
GetParameterBool()
bool GetParameterBool (string name) inline private
Definition at line 523 of file PluginLocalProfile.c.
References name, and string::ToInt().
GetParameterFloat()
float GetParameterFloat (string name) inline private
Definition at line 506 of file PluginLocalProfile.c.
References name, and string::ToFloat().
GetParameterInt()
int GetParameterInt (string name) inline private
Definition at line 489 of file PluginLocalProfile.c.
References name, and string::ToInt().
GetParameterString()
string GetParameterString (string name) inline private
Definition at line 467 of file PluginLocalProfile.c.
References name, string::Split(), and STRING_EMPTY.
GetSubParameterInArrayString()
string GetSubParameterInArrayString (string param_name, int sub_array_index, string sub_param_name) inline private
Definition at line 561 of file PluginLocalProfile.c.
References string::Split(), and STRING_EMPTY.
GetTextType()
protected int GetTextType (string text) inline private
Definition at line 281 of file PluginConfigHandler.c.
References CFG_TYPE_ARRAY, CFG_TYPE_BOOL, CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_PARAM, CFG_TYPE_STRING, string::IndexOf(), string::Length(), and string::Substring().
IsArray()
protected bool IsArray (string text) inline private
Definition at line 356 of file PluginConfigHandler.c.
References CFG_TYPE_ARRAY.
IsBool()
protected bool IsBool (string text) inline private
Definition at line 386 of file PluginConfigHandler.c.
References CFG_TYPE_BOOL.
IsFloat()
protected bool IsFloat (string text) inline private
Definition at line 366 of file PluginConfigHandler.c.
References CFG_TYPE_FLOAT.
IsInt()
protected bool IsInt (string text) inline private
Definition at line 376 of file PluginConfigHandler.c.
References CFG_TYPE_INT.
IsParam()
protected bool IsParam (string text) inline private
Definition at line 346 of file PluginConfigHandler.c.
References CFG_TYPE_PARAM.
IsString()
protected bool IsString (string text) inline private
Definition at line 336 of file PluginConfigHandler.c.
References CFG_TYPE_STRING.
IsTextArray()
bool IsTextArray (string text) inline private
Definition at line 205 of file PluginLocalProfile.c.
References string::Length(), and string::Substring().
LoadConfigFile() [1/2]
void LoadConfigFile () inline private
Definition at line 22 of file PluginConfigHandler.c.
LoadConfigFile() [2/2]
bool LoadConfigFile () inline private
Definition at line 28 of file PluginLocalProfile.c.
References PluginLocalProfile::GetFileName(), PrintString(), and string::ToString().
LoadParameter()
string LoadParameter (string param_name) inline private
Definition at line 304 of file PluginLocalProfile.c.
References string::Get(), and STRING_EMPTY.
LoadParameterArray()
TStringArray LoadParameterArray (string param_name) inline private
Definition at line 316 of file PluginLocalProfile.c.
LoadSubParameter()
string LoadSubParameter (string param_name, int sub_array_index, string sub_param_name) inline private
Definition at line 326 of file PluginLocalProfile.c.
References string::Get(), and STRING_EMPTY.
OnInit() [1/3]
override void OnInit () inline private
Definition at line 12 of file PluginConfigHandler.c.
OnInit() [2/3]
override void OnInit () inline private
Definition at line 12 of file PluginLocalHistoryBase.c.
OnInit() [3/3]
override void OnInit () inline private
Definition at line 21 of file PluginLocalProfile.c.
ParamExist()
bool ParamExist (string name) inline private
Definition at line 106 of file PluginConfigHandler.c.
References CfgParam::GetName(), and name.
ParseParam()
string ParseParam (CfgParam param) inline private
Definition at line 123 of file PluginConfigHandler.c.
References CFG_TYPE_ARRAY, CFG_TYPE_BOOL, CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, CfgParam::GetName(), CfgParam::GetType(), string::IndexOf(), STRING_EMPTY, and string::ToString().
ParseText()
CfgParam ParseText (string text) inline private
Definition at line 203 of file PluginConfigHandler.c.
References CFG_TYPE_ARRAY, CFG_TYPE_BOOL, CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_PARAM, CFG_TYPE_STRING, string::IndexOf(), string::Length(), CfgParam::SetName(), STRING_EMPTY, string::Substring(), and string::Trim().
ParseTextArrayToParameters()
array< ref map< string, string > > ParseTextArrayToParameters (string text) inline private
Definition at line 279 of file PluginLocalProfile.c.
ParseTextToArray()
TStringArray ParseTextToArray (string text, out TStringArray ret) inline private
Definition at line 243 of file PluginLocalProfile.c.
References string::IndexOf(), string::IndexOfFrom(), string::Length(), string::Split(), and string::Substring().
ParseTextToParameter()
TStringArray ParseTextToParameter (string text) inline private
Definition at line 218 of file PluginLocalProfile.c.
References string::IndexOf(), string::Length(), string::Substring(), and string::Trim().
ParseToValueArray()
protected array< ref CfgParam > ParseToValueArray (string param_value) inline private
Definition at line 421 of file PluginConfigHandler.c.
References string::IndexOfFrom(), string::Length(), string::Split(), and string::Substring().
ParseToValueBool()
protected bool ParseToValueBool (string param_value) inline private
Definition at line 411 of file PluginConfigHandler.c.
References string::Contains().
ParseToValueFloat()
protected float ParseToValueFloat (string param_value) inline private
Definition at line 401 of file PluginConfigHandler.c.
References string::ToFloat().
ParseToValueInt()
protected int ParseToValueInt (string param_value) inline private
Definition at line 406 of file PluginConfigHandler.c.
References string::ToInt().
ParseToValueString()
protected string ParseToValueString (string param_value) inline private
Definition at line 396 of file PluginConfigHandler.c.
References string::Length(), and string::Substring().
PluginConfigHandler()
void PluginConfigHandler () inline private
Definition at line 5 of file PluginConfigHandler.c.
PluginLocalHistoryBase()
void PluginLocalHistoryBase () inline private
Definition at line 3 of file PluginLocalHistoryBase.c.
PluginLocalProfile()
void PluginLocalProfile () inline private
Definition at line 8 of file PluginLocalProfile.c.
RemoveParamByName()
void RemoveParamByName (string name) inline private
Definition at line 78 of file PluginConfigHandler.c.
References CfgParam::GetName(), and name.
RemoveParameter()
void RemoveParameter (string name, bool save_in_file = true) inline private
Definition at line 416 of file PluginLocalProfile.c.
References name.
RemoveParameterArray()
void RemoveParameterArray (string name, bool save_in_file = true) inline private
Definition at line 426 of file PluginLocalProfile.c.
References name.
RenameParam()
void RenameParam (string name, string new_name) inline private
Definition at line 92 of file PluginConfigHandler.c.
References CfgParam::GetName(), name, and CfgParam::SetName().
RenameParameter()
void RenameParameter (string old_name, string new_name, bool save_in_file = true) inline private
Definition at line 390 of file PluginLocalProfile.c.
RenameParameterArray()
void RenameParameterArray (string old_name, string new_name, bool save_in_file = true) inline private
Definition at line 403 of file PluginLocalProfile.c.
SaveConfigToFile() [1/2]
void SaveConfigToFile () inline private
Definition at line 34 of file PluginConfigHandler.c.
SaveConfigToFile() [2/2]
void SaveConfigToFile () inline private
Definition at line 112 of file PluginLocalProfile.c.
SaveParameter()
void SaveParameter (string param_name, string value, bool save_in_file = true) inline private
Definition at line 353 of file PluginLocalProfile.c.
References Log().
SaveParameterArray()
void SaveParameterArray (string param_name, TStringArray value, bool save_in_file = true) inline private
Definition at line 368 of file PluginLocalProfile.c.
SaveSubParameterInArray()
void SaveSubParameterInArray (string param_name, int sub_array_index, string sub_param_name, string sub_param_value, bool save_in_file = true) inline private
Definition at line 378 of file PluginLocalProfile.c.
SetParameterArray()
void SetParameterArray (string name, TStringArray value, bool save_in_file = true) inline private
Definition at line 457 of file PluginLocalProfile.c.
References name.
SetParameterBool()
void SetParameterBool (string name, bool value, bool save_in_file = true) inline private
Definition at line 452 of file PluginLocalProfile.c.
References name, and bool::ToString().
SetParameterFloat()
void SetParameterFloat (string name, float value, bool save_in_file = true) inline private
Definition at line 447 of file PluginLocalProfile.c.
References name, and float::ToString().
SetParameterInt()
void SetParameterInt (string name, int value, bool save_in_file = true) inline private
Definition at line 442 of file PluginLocalProfile.c.
References name, and string::ToString().
SetParameterString()
void SetParameterString (string name, string value, bool save_in_file = true) inline private
Definition at line 436 of file PluginLocalProfile.c.
References name.
SetSubParameterInArray()
void SetSubParameterInArray (string param_name, int sub_array_index, string sub_param_name, string sub_param_value, bool save_in_file = true) inline private
Definition at line 462 of file PluginLocalProfile.c.
Field Documentation
m_CfgParams
ref array<ref CfgParam> m_CfgParams private
Definition at line 3 of file PluginConfigHandler.c.
m_ConfigParams
ref map<string, string> m_ConfigParams private
Definition at line 3 of file PluginLocalProfile.c.
m_ConfigParamsArray
ref map<string, ref TStringArray> m_ConfigParamsArray private
Definition at line 4 of file PluginLocalProfile.c.
m_ConfigParamsArrayInArray
ref map<string, ref array<ref map<string, string> > > m_ConfigParamsArrayInArray private
Definition at line 6 of file PluginLocalProfile.c.
m_ConfigParamsInArray
ref map<string, ref map<string, string> > m_ConfigParamsInArray private
Definition at line 5 of file PluginLocalProfile.c.
The documentation for this class was generated from the following files:
4_World/Plugins/PluginBase/PluginFileHandler/PluginConfigHandler.c
4_World/Plugins/PluginBase/PluginFileHandler/PluginLocalProfile.c
4_World/Plugins/PluginBase/PluginFileHandler/PluginLocalHistoryBase.c