DayZ Scripts: RockBase Class Reference
RockBase Class Reference
Private Member Functions
override bool IsRock ()
int GetAmountOfDrops (ItemBase item)
void GetMaterialAndQuantityMap (ItemBase item, out map< string, int > output_map)
float GetDamageToMiningItemEachDrop (ItemBase item)
Detailed Description
Definition at line 1 of file RockBase.c.
Member Function Documentation
GetAmountOfDrops()
int GetAmountOfDrops (ItemBase item) inline private
Definition at line 8 of file RockBase.c.
Referenced by CAContinuousMineRock::GetMiningData().
GetDamageToMiningItemEachDrop()
float GetDamageToMiningItemEachDrop (ItemBase item) inline private
Definition at line 50 of file RockBase.c.
Referenced by CAContinuousMineRock::GetMiningData().
GetMaterialAndQuantityMap()
void GetMaterialAndQuantityMap (ItemBase item, out map< string, int > output_map) inline private
Definition at line 25 of file RockBase.c.
Referenced by CAContinuousMineRock::GetMiningData(), and ActionMineBase::GetYieldName().
IsRock()
override bool IsRock () inline private
Definition at line 3 of file RockBase.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/RockBase.c