DayZ: ActionMenu Class Reference
ActionMenu Class Reference
Private Member Functions
void ActionMenu ()
void Init (Widget actions_panel_widget, TextWidget default_action_widget)
void UpdateWidgets ()
void NextAction ()
void PrevAction ()
void NextActionCategory ()
void PrevActionCategory ()
void Show ()
void Refresh ()
void Hide ()
void HideWithFadeout ()
Private Attributes
private const float FADE_IN_TIME = 0.3
private const float FADE_OUT_TIME = 0.3
private const float HIDE_MENU_TIME = 5
private ref WidgetFadeTimer m_FadeTimer
private ref array< TextWidget > m_actionItems
private TextWidget m_defaultActionWidget
private Widget m_actionsPanelWidget
private ref Timer m_hide_timer
private bool m_visible
Detailed Description
Definition at line 1 of file ActionMenu.c.
Constructor & Destructor Documentation
ActionMenu()
void ActionMenu () inline private
Definition at line 15 of file ActionMenu.c.
References CALL_CATEGORY_GUI, m_actionItems, m_FadeTimer, m_hide_timer, and m_visible.
Member Function Documentation
Hide()
void Hide () inline private
Definition at line 161 of file ActionMenu.c.
References m_actionsPanelWidget, m_FadeTimer, m_hide_timer, m_visible, and Timer::Stop().
HideWithFadeout()
void HideWithFadeout () inline private
Definition at line 173 of file ActionMenu.c.
References FADE_OUT_TIME, m_actionsPanelWidget, and m_FadeTimer.
Init()
void Init (Widget actions_panel_widget, TextWidget default_action_widget) inline private
Definition at line 23 of file ActionMenu.c.
References m_actionItems, m_actionsPanelWidget, and m_defaultActionWidget.
NextAction()
void NextAction () inline private
Definition at line 102 of file ActionMenu.c.
References GetGame(), GetPlayer(), HIDE_MENU_TIME, m_hide_timer, and UpdateWidgets().
NextActionCategory()
void NextActionCategory () inline private
Definition at line 122 of file ActionMenu.c.
References GetGame(), GetPlayer(), HIDE_MENU_TIME, m_hide_timer, and UpdateWidgets().
PrevAction()
void PrevAction () inline private
Definition at line 112 of file ActionMenu.c.
References GetGame(), GetPlayer(), HIDE_MENU_TIME, m_hide_timer, and UpdateWidgets().
PrevActionCategory()
void PrevActionCategory () inline private
Definition at line 132 of file ActionMenu.c.
References GetGame(), GetPlayer(), HIDE_MENU_TIME, m_hide_timer, and UpdateWidgets().
Refresh()
void Refresh () inline private
Definition at line 151 of file ActionMenu.c.
References GetGame(), GetPlayer(), m_visible, Show(), and UpdateWidgets().
Show()
void Show () inline private
Definition at line 142 of file ActionMenu.c.
References HIDE_MENU_TIME, m_hide_timer, and m_visible.
Referenced by Refresh().
UpdateWidgets()
void UpdateWidgets () inline private
Definition at line 44 of file ActionMenu.c.
References FADE_IN_TIME, FADE_OUT_TIME, DiagMenu::GetBool(), GetGame(), GetPlayer(), m_actionItems, m_actionsPanelWidget, m_defaultActionWidget, and m_FadeTimer.
Referenced by NextAction(), NextActionCategory(), PrevAction(), PrevActionCategory(), and Refresh().
Field Documentation
FADE_IN_TIME
private const float FADE_IN_TIME = 0.3 private
Definition at line 3 of file ActionMenu.c.
Referenced by UpdateWidgets().
FADE_OUT_TIME
private const float FADE_OUT_TIME = 0.3 private
Definition at line 4 of file ActionMenu.c.
Referenced by HideWithFadeout(), and UpdateWidgets().
HIDE_MENU_TIME
private const float HIDE_MENU_TIME = 5 private
Definition at line 5 of file ActionMenu.c.
Referenced by NextAction(), NextActionCategory(), PrevAction(), PrevActionCategory(), and Show().
m_actionItems
private ref array<TextWidget> m_actionItems private
Definition at line 8 of file ActionMenu.c.
Referenced by ActionMenu(), Init(), and UpdateWidgets().
m_actionsPanelWidget
private Widget m_actionsPanelWidget private
Definition at line 10 of file ActionMenu.c.
Referenced by Hide(), HideWithFadeout(), Init(), and UpdateWidgets().
m_defaultActionWidget
private TextWidget m_defaultActionWidget private
Definition at line 9 of file ActionMenu.c.
Referenced by Init(), and UpdateWidgets().
m_FadeTimer
private ref WidgetFadeTimer m_FadeTimer private
Definition at line 7 of file ActionMenu.c.
Referenced by ActionMenu(), Hide(), HideWithFadeout(), and UpdateWidgets().
m_hide_timer
private ref Timer m_hide_timer private
Definition at line 11 of file ActionMenu.c.
Referenced by ActionMenu(), Hide(), NextAction(), NextActionCategory(), PrevAction(), PrevActionCategory(), and Show().
m_visible
private bool m_visible private
Definition at line 13 of file ActionMenu.c.
Referenced by ActionMenu(), Hide(), Refresh(), and Show().
The documentation for this class was generated from the following file:
5_Mission/GUI/ActionMenu.c