DayZ: UIScriptedWindow Class Reference
UIScriptedWindow Class Reference
Private Member Functions
void UIScriptedWindow (int id)
void ~UIScriptedWindow ()
Widget GetWidgetRoot ()
Widget Init ()
void ShowWindow ()
void HideWindow ()
void CloseWindow ()
bool OnClick (Widget w, int x, int y, int button)
bool OnModalResult (Widget w, int x, int y, int code, int result)
bool OnDoubleClick (Widget w, int x, int y, int button)
bool OnSelect (Widget w, int x, int y)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnFocus (Widget w, int x, int y)
bool OnFocusLost (Widget w, int x, int y)
bool OnMouseEnter (Widget w, int x, int y)
bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnMouseButtonUp (Widget w, int x, int y, int button)
bool OnMouseWheel (Widget w, int x, int y, int wheel)
bool OnController (Widget w, int control, int value)
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnKeyUp (Widget w, int x, int y, int key)
bool OnKeyPress (Widget w, int x, int y, int key)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnDrag (Widget w, int x, int y)
bool OnDragging (Widget w, int x, int y, Widget reciever)
bool OnDraggingOver (Widget w, int x, int y, Widget reciever)
bool OnDrop (Widget w, int x, int y, Widget reciever)
bool OnDropReceived (Widget w, int x, int y, Widget reciever)
bool OnEvent (EventType eventType, Widget target, int parameter0, int parameter1)
void MissionLoader (int id)
override Widget Init ()
private TStringArray GetMissionList ()
override bool OnClick (Widget w, int x, int y, int button)
Static Private Member Functions
static void AddToActiveWindows (int id, UIScriptedWindow window)
static void RemoveFromActiveWindows (int id)
static UIScriptedWindow GetWindow (int id)
static map< int, UIScriptedWindow > GetActiveWindows ()
Private Attributes
Widget m_WgtRoot
int m_Id
string m_PathToMissions
TextListboxWidget m_WgtLstMsnList
ButtonWidget m_WgtBtnMsnPlay
ButtonWidget m_WgtBtnMsnClose
ref TStringArray m_ListMissionsNames
Static Private Attributes
static ref map< int, UIScriptedWindow > m_ActiveWindows
Detailed Description
Definition at line 1 of file UIScriptedWindow.c.
Constructor & Destructor Documentation
UIScriptedWindow()
void UIScriptedWindow (int id) inline private
Definition at line 44 of file UIScriptedWindow.c.
References m_Id.
~UIScriptedWindow()
void ~UIScriptedWindow () inline private
Definition at line 49 of file UIScriptedWindow.c.
References GetWidgetRoot().
Member Function Documentation
AddToActiveWindows()
static void AddToActiveWindows (int id, UIScriptedWindow window) inline static private
Definition at line 9 of file UIScriptedWindow.c.
References m_ActiveWindows.
Referenced by UIManager::OpenWindow().
CloseWindow()
void CloseWindow () inline private
Definition at line 74 of file UIScriptedWindow.c.
References UIManager::CloseWindow(), GetGame(), CGame::GetUIManager(), and m_Id.
Referenced by OnClick().
GetActiveWindows()
static map< int, UIScriptedWindow > GetActiveWindows () inline static private
Definition at line 37 of file UIScriptedWindow.c.
References m_ActiveWindows.
Referenced by UIMenuPanel::OnChange(), UIMenuPanel::OnClick(), UIMenuPanel::OnController(), UIMenuPanel::OnDoubleClick(), UIMenuPanel::OnDrag(), UIMenuPanel::OnDragging(), UIMenuPanel::OnDraggingOver(), UIMenuPanel::OnDrop(), UIMenuPanel::OnDropReceived(), UIMenuPanel::OnEvent(), UIMenuPanel::OnFocus(), UIMenuPanel::OnFocusLost(), UIMenuPanel::OnItemSelected(), UIMenuPanel::OnKeyDown(), UIMenuPanel::OnKeyPress(), UIMenuPanel::OnKeyUp(), UIMenuPanel::OnModalResult(), UIMenuPanel::OnMouseButtonDown(), UIMenuPanel::OnMouseButtonUp(), UIMenuPanel::OnMouseEnter(), UIMenuPanel::OnMouseLeave(), UIMenuPanel::OnMouseWheel(), and UIMenuPanel::OnSelect().
GetMissionList()
private TStringArray GetMissionList () inline private
Definition at line 34 of file MissionLoader.c.
References FindFile(), and FindNextFile().
Referenced by Init().
GetWidgetRoot()
Widget GetWidgetRoot () inline private
Definition at line 55 of file UIScriptedWindow.c.
References m_WgtRoot.
Referenced by HideWindow(), ShowWindow(), and ~UIScriptedWindow().
GetWindow()
static UIScriptedWindow GetWindow (int id) inline static private
Definition at line 27 of file UIScriptedWindow.c.
References m_ActiveWindows.
Referenced by UIManager::CloseWindow(), UIManager::IsWindowOpened(), and UIManager::OpenWindow().
HideWindow()
void HideWindow () inline private
Definition at line 69 of file UIScriptedWindow.c.
References GetWidgetRoot().
Referenced by UIManager::CloseWindow().
Init() [1/2]
Widget Init () inline private
Definition at line 60 of file UIScriptedWindow.c.
Referenced by UIManager::OpenWindow().
Init() [2/2]
override Widget Init () inline private
Definition at line 15 of file MissionLoader.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), GetMissionList(), CGame::GetWorkspace(), m_WgtRoot, and m_WgtRoot.
MissionLoader()
void MissionLoader (int id) inline private
Definition at line 10 of file MissionLoader.c.
References m_Id.
OnChange()
bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 160 of file UIScriptedWindow.c.
OnClick() [1/2]
bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 80 of file UIScriptedWindow.c.
OnClick() [2/2]
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 60 of file MissionLoader.c.
References CloseWindow(), GetGame(), Log(), and CGame::PlayMission().
OnController()
bool OnController (Widget w, int control, int value) inline private
Definition at line 140 of file UIScriptedWindow.c.
OnDoubleClick()
bool OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 90 of file UIScriptedWindow.c.
OnDrag()
bool OnDrag (Widget w, int x, int y) inline private
Definition at line 165 of file UIScriptedWindow.c.
OnDragging()
bool OnDragging (Widget w, int x, int y, Widget reciever) inline private
Definition at line 170 of file UIScriptedWindow.c.
OnDraggingOver()
bool OnDraggingOver (Widget w, int x, int y, Widget reciever) inline private
Definition at line 175 of file UIScriptedWindow.c.
OnDrop()
bool OnDrop (Widget w, int x, int y, Widget reciever) inline private
Definition at line 180 of file UIScriptedWindow.c.
OnDropReceived()
bool OnDropReceived (Widget w, int x, int y, Widget reciever) inline private
Definition at line 185 of file UIScriptedWindow.c.
OnEvent()
bool OnEvent (EventType eventType, Widget target, int parameter0, int parameter1) inline private
Definition at line 190 of file UIScriptedWindow.c.
OnFocus()
bool OnFocus (Widget w, int x, int y) inline private
Definition at line 105 of file UIScriptedWindow.c.
OnFocusLost()
bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 110 of file UIScriptedWindow.c.
OnItemSelected()
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
Definition at line 100 of file UIScriptedWindow.c.
OnKeyDown()
bool OnKeyDown (Widget w, int x, int y, int key) inline private
Definition at line 145 of file UIScriptedWindow.c.
OnKeyPress()
bool OnKeyPress (Widget w, int x, int y, int key) inline private
Definition at line 155 of file UIScriptedWindow.c.
OnKeyUp()
bool OnKeyUp (Widget w, int x, int y, int key) inline private
Definition at line 150 of file UIScriptedWindow.c.
OnModalResult()
bool OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 85 of file UIScriptedWindow.c.
OnMouseButtonDown()
bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 125 of file UIScriptedWindow.c.
OnMouseButtonUp()
bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 130 of file UIScriptedWindow.c.
OnMouseEnter()
bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 115 of file UIScriptedWindow.c.
OnMouseLeave()
bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 120 of file UIScriptedWindow.c.
OnMouseWheel()
bool OnMouseWheel (Widget w, int x, int y, int wheel) inline private
Definition at line 135 of file UIScriptedWindow.c.
OnSelect()
bool OnSelect (Widget w, int x, int y) inline private
Definition at line 95 of file UIScriptedWindow.c.
RemoveFromActiveWindows()
static void RemoveFromActiveWindows (int id) inline static private
Definition at line 19 of file UIScriptedWindow.c.
References m_ActiveWindows.
Referenced by UIManager::CloseWindow().
ShowWindow()
void ShowWindow () inline private
Definition at line 64 of file UIScriptedWindow.c.
References GetWidgetRoot().
Field Documentation
m_ActiveWindows
ref map<int, UIScriptedWindow> m_ActiveWindows static private
Definition at line 7 of file UIScriptedWindow.c.
Referenced by AddToActiveWindows(), GetActiveWindows(), GetWindow(), and RemoveFromActiveWindows().
m_Id
int m_Id private
Definition at line 4 of file UIScriptedWindow.c.
Referenced by CloseWindow(), and UIScriptedWindow().
m_ListMissionsNames
ref TStringArray m_ListMissionsNames private
Definition at line 8 of file MissionLoader.c.
m_PathToMissions
string m_PathToMissions private
Definition at line 3 of file MissionLoader.c.
m_WgtBtnMsnClose
ButtonWidget m_WgtBtnMsnClose private
Definition at line 6 of file MissionLoader.c.
m_WgtBtnMsnPlay
ButtonWidget m_WgtBtnMsnPlay private
Definition at line 5 of file MissionLoader.c.
m_WgtLstMsnList
TextListboxWidget m_WgtLstMsnList private
Definition at line 4 of file MissionLoader.c.
m_WgtRoot
Widget m_WgtRoot private
Definition at line 3 of file UIScriptedWindow.c.
Referenced by GetWidgetRoot(), and Init().
The documentation for this class was generated from the following files:
3_Game/tools/UIScriptedWindow.c
5_Mission/GUI/ScriptedWindows/MissionLoader.c