DayZ: DeveloperFreeCamera Class Reference
DeveloperFreeCamera Class Reference
Static Private Member Functions
static void OnInit ()
static void FreeCameraToggle (PlayerBase player, bool teleport_player=false)
Enable / Disable Free camera (Fly mod) - disable of camera will teleport player at current free camera position.
static void EnableFreeCameraSceneEditor (PlayerBase player)
static bool IsFreeCameraEnabled ()
static protected void EnableFreeCamera (PlayerBase player)
static void DisableFreeCamera (PlayerBase player, bool teleport_player=false)
static void OnSetFreeCameraEvent (PlayerBase player, FreeDebugCamera camera)
Detailed Description
Definition at line 1 of file DeveloperFreeCamera.c.
Member Function Documentation
DisableFreeCamera()
static void DisableFreeCamera (PlayerBase player, bool teleport_player = false) inline static private
Definition at line 44 of file DeveloperFreeCamera.c.
References GetGame(), CGame::GetMission(), Debug::LogError(), Mission::RefreshCrosshairVisibility(), and DeveloperTeleport::TeleportAtCursorEx().
Referenced by FreeCameraToggle(), UIScriptedMenu::Play(), and UIScriptedMenu::~CameraToolsMenu().
EnableFreeCamera()
static protected void EnableFreeCamera (PlayerBase player) inline static private
Definition at line 28 of file DeveloperFreeCamera.c.
References GetGame(), CGame::GetMission(), Debug::LogError(), and Mission::RefreshCrosshairVisibility().
Referenced by EnableFreeCameraSceneEditor(), and FreeCameraToggle().
EnableFreeCameraSceneEditor()
static void EnableFreeCameraSceneEditor (PlayerBase player) inline static private
Definition at line 18 of file DeveloperFreeCamera.c.
References EnableFreeCamera().
Referenced by UIScriptedMenu::Init(), PluginBase::OnUIEditorOpened(), and UIScriptedMenu::Update().
FreeCameraToggle()
static void FreeCameraToggle (PlayerBase player, bool teleport_player = false) inline static private
Enable / Disable Free camera (Fly mod) - disable of camera will teleport player at current free camera position.
Definition at line 6 of file DeveloperFreeCamera.c.
References DisableFreeCamera(), EnableFreeCamera(), and IsFreeCameraEnabled().
Referenced by PluginBase::ToggleFreeCamera(), and PluginBase::ToggleFreeCameraBackPos().
IsFreeCameraEnabled()
static bool IsFreeCameraEnabled () inline static private
Definition at line 23 of file DeveloperFreeCamera.c.
Referenced by FreeCameraToggle(), PluginBase::IsEnabledFreeCamera(), DeveloperTeleport::TeleportAtCursor(), DeveloperTeleport::TeleportAtCursorEx(), and ActionManagerClient::Update().
OnInit()
static void OnInit () static private
Referenced by PluginBase::OnInit().
OnSetFreeCameraEvent()
static void OnSetFreeCameraEvent (PlayerBase player, FreeDebugCamera camera) inline static private
Definition at line 67 of file DeveloperFreeCamera.c.
References GetGame(), CGame::GetMission(), GetPlugin(), and Mission::RefreshCrosshairVisibility().
Referenced by PluginBase::OnSetFreeCameraEvent().
The documentation for this class was generated from the following file:
4_World/Plugins/PluginBase/PluginDeveloper/DeveloperFreeCamera.c