DayZ Scripts: OpenItem Class Reference
OpenItem Class Reference
Static Private Member Functions
static void OpenAndSwitch (ItemBase item_tool, ItemBase item_target, PlayerBase player, float specialty_weight=0)
WIll open the 'item_target' by spawning a new entity and transferring item variables to the new one.
static void SwitchItems (EntityAI old_item, PlayerBase player, float spill_modificator, float specialty_weight)
Will switch the 'item' for a new game entity, the new entity's classname will be formed by adding the 'suffix' to the classname of the old 'item'.
Detailed Description
Definition at line 1 of file OpenItem.c.
Member Function Documentation
OpenAndSwitch()
static void OpenAndSwitch (ItemBase item_tool, ItemBase item_target, PlayerBase player, float specialty_weight = 0) inline static private
WIll open the 'item_target' by spawning a new entity and transferring item variables to the new one.
Definition at line 4 of file OpenItem.c.
References Error(), Debug::LogError(), Math::RandomIntInclusive(), and SwitchItems().
Referenced by RecipeBase::Do().
SwitchItems()
static void SwitchItems (EntityAI old_item, PlayerBase player, float spill_modificator, float specialty_weight) inline static private
Will switch the 'item' for a new game entity, the new entity's classname will be formed by adding the 'suffix' to the classname of the old 'item'.
Definition at line 25 of file OpenItem.c.
Referenced by OpenAndSwitch().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/OpenItem.c