DayZ: DisplayElementBase Class Reference
DisplayElementBase Class Reference
Private Member Functions
void SetLevel (int level)
override void UpdateHUD ()
void DisplayElementTendency (PlayerBase player)
void SetSeriousnessLevel (DSLevels level)
override void UpdateHUD ()
void SetTendency (int tendency)
void ElementStance (PlayerBase player)
override void UpdateHUD ()
Private Attributes
protected int TENDENCY_MASK = 7
protected int SERIOUSNESS_BIT_MASK = 7
protected int SERIOUSNESS_BIT_OFFSET = 3
Detailed Description
Definition at line 1 of file DisplayElementBadge.c.
Member Function Documentation
DisplayElementTendency()
void DisplayElementTendency (PlayerBase player) inline private
Definition at line 7 of file DisplayElementTendency.c.
ElementStance()
void ElementStance (PlayerBase player) inline private
Definition at line 3 of file ElementStance.c.
References m_Type.
SetLevel()
void SetLevel (int level) inline private
Definition at line 3 of file DisplayElementBadge.c.
References SetValue().
SetSeriousnessLevel()
void SetSeriousnessLevel (DSLevels level) inline private
Definition at line 12 of file DisplayElementTendency.c.
References m_Value.
SetTendency()
void SetTendency (int tendency) inline private
Definition at line 37 of file DisplayElementTendency.c.
References m_Value.
UpdateHUD() [1/3]
override void UpdateHUD () inline private
Definition at line 8 of file DisplayElementBadge.c.
References m_Key, m_ModulePlayerStatus, and m_Value.
Referenced by ImmediateUpdate(), and UpdateStatus().
UpdateHUD() [2/3]
override void UpdateHUD () inline private
Definition at line 18 of file DisplayElementTendency.c.
References m_Key, m_ModulePlayerStatus, m_Value, and DisplayElementTendency::TranslateLevelToStatus().
UpdateHUD() [3/3]
override void UpdateHUD () inline private
Definition at line 10 of file ElementStance.c.
References m_ModulePlayerStatus, and m_Value.
Field Documentation
SERIOUSNESS_BIT_MASK
protected int SERIOUSNESS_BIT_MASK = 7 private
Definition at line 4 of file DisplayElementTendency.c.
SERIOUSNESS_BIT_OFFSET
protected int SERIOUSNESS_BIT_OFFSET = 3 private
Definition at line 5 of file DisplayElementTendency.c.
TENDENCY_MASK
protected int TENDENCY_MASK = 7 private
Definition at line 3 of file DisplayElementTendency.c.
The documentation for this class was generated from the following files:
4_World/Classes/VirtualHud/DisplayElementBadge.c
4_World/Classes/VirtualHud/DisplayElementTendency.c
4_World/Classes/VirtualHud/Elements/Misc/ElementStance.c