DayZ: UIMenuPanel Class Reference
UIMenuPanel Class Reference
Part of main menu hierarchy to create custom menus from script.
Private Member Functions
proto native UIMenuPanel GetSubMenu ()
proto native UIMenuPanel GetParentMenu ()
proto native UIMenuPanel GetVisibleMenu ()
proto native void SetSubMenu (UIMenuPanel submenu)
proto native void SetParentMenu (UIMenuPanel parent)
proto native bool CanClose ()
proto native bool CanCloseOnEscape ()
proto native UIScriptedMenu EnterScriptedMenu (int id)
Create & open menu with specific id (see MenuID) and set this menu as its parent.
proto native void DestroySubmenu ()
proto native bool IsAnyMenuVisible ()
proto native bool IsVisible ()
void OnVisibilityChanged (bool isVisible)
proto native void Close ()
Safe way to close window, using this function can even window safely close itself.
bool UseMouse ()
bool UseKeyboard ()
bool UseGamepad ()
int GetID ()
Returns MenuID.
void Refresh ()
Refresh request, called from anywhere.
Widget GetLayoutRoot ()
void LockControls ()
void UnlockControls ()
void UIScriptedMenu ()
void ~UIScriptedMenu ()
void SetID (int id)
Sets MenuID.
override int GetID ()
Returns MenuID.
void SetWidgetAnimAlpha (Widget widget)
Widget Init ()
void Cleanup ()
void OnShow ()
void OnHide ()
void Update (float timeslice)
Per frame update, called from engine.
proto native void SetFadingPanels (Widget panel0, Widget panel1, Widget panel2, Widget panel3, Widget panel4)
Refresh request, called from anywhere.
bool OnClick (Widget w, int x, int y, int button)
bool OnModalResult (Widget w, int x, int y, int code, int result)
bool OnDoubleClick (Widget w, int x, int y, int button)
bool OnSelect (Widget w, int x, int y)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnFocus (Widget w, int x, int y)
bool OnFocusLost (Widget w, int x, int y)
bool OnMouseEnter (Widget w, int x, int y)
bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnMouseButtonUp (Widget w, int x, int y, int button)
bool OnMouseWheel (Widget w, int x, int y, int wheel)
bool OnController (Widget w, int control, int value)
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnKeyUp (Widget w, int x, int y, int key)
bool OnKeyPress (Widget w, int x, int y, int key)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnDrag (Widget w, int x, int y)
bool OnDragging (Widget w, int x, int y, Widget reciever)
bool OnDraggingOver (Widget w, int x, int y, Widget reciever)
bool OnDrop (Widget w, int x, int y, Widget reciever)
bool OnDropReceived (Widget w, int x, int y, Widget reciever)
bool OnEvent (EventType eventType, Widget target, int parameter0, int parameter1)
ContextMenu GetContextMenu ()
bool OnXboxEvent (int xboxEvent)
void OnRPC (ParamsReadContext ctx)
void OnRPCEx (int rpc_type, ParamsReadContext ctx)
void InitNoteWrite (EntityAI paper, EntityAI pen, string text="")
void InitNoteRead (string text="")
void InitMapItem (EntityAI item)
void LoadMapMarkers ()
Private Attributes
int m_id
Widget layoutRoot
private Widget m_AnimAlphaWidget
private bool m_AnimAlphaIsIncreasing
private float m_AnimAlphaValue
Detailed Description
Part of main menu hierarchy to create custom menus from script.
Definition at line 2 of file UIScriptedMenu.c.
Constructor & Destructor Documentation
~UIScriptedMenu()
void ~UIScriptedMenu () inline private
Definition at line 124 of file UIScriptedMenu.c.
Member Function Documentation
CanClose()
proto native bool CanClose () private
CanCloseOnEscape()
proto native bool CanCloseOnEscape () private
Cleanup()
void Cleanup () inline private
Definition at line 151 of file UIScriptedMenu.c.
Close()
proto native void Close () private
Safe way to close window, using this function can even window safely close itself.
Referenced by UIManager::Back(), UIManager::CloseAll(), UIManager::CloseAllSubmenus(), and UIManager::CloseMenu().
DestroySubmenu()
proto native void DestroySubmenu () private
EnterScriptedMenu()
proto native UIScriptedMenu EnterScriptedMenu (int id) private
Create & open menu with specific id (see MenuID) and set this menu as its parent.
Referenced by MissionBase::CreateLogoutMenu().
GetContextMenu()
ContextMenu GetContextMenu () inline private
Definition at line 558 of file UIScriptedMenu.c.
GetID() [1/2]
int GetID () inline private
Returns MenuID.
Definition at line 48 of file UIScriptedMenu.c.
References MENU_UNKNOWN.
Referenced by UIManager::CloseMenu().
GetID() [2/2]
override int GetID () inline private
Returns MenuID.
Definition at line 134 of file UIScriptedMenu.c.
GetLayoutRoot()
Widget GetLayoutRoot () inline private
Definition at line 68 of file UIScriptedMenu.c.
GetParentMenu()
proto native UIMenuPanel GetParentMenu () private
Referenced by UIManager::CloseAll(), UIManager::CloseAllSubmenus(), and UIManager::CloseMenu().
GetSubMenu()
proto native UIMenuPanel GetSubMenu () private
GetVisibleMenu()
proto native UIMenuPanel GetVisibleMenu () private
Init()
Widget Init () inline private
Definition at line 146 of file UIScriptedMenu.c.
InitMapItem()
void InitMapItem (EntityAI item) inline private
Definition at line 573 of file UIScriptedMenu.c.
InitNoteRead()
void InitNoteRead (string text = "") inline private
Definition at line 572 of file UIScriptedMenu.c.
InitNoteWrite()
void InitNoteWrite (EntityAI paper, EntityAI pen, string text = "") inline private
Definition at line 571 of file UIScriptedMenu.c.
IsAnyMenuVisible()
proto native bool IsAnyMenuVisible () private
IsVisible()
proto native bool IsVisible () private
LoadMapMarkers()
void LoadMapMarkers () inline private
Definition at line 574 of file UIScriptedMenu.c.
LockControls()
void LockControls () inline private
Definition at line 73 of file UIScriptedMenu.c.
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), INPUT_DEVICE_GAMEPAD, INPUT_DEVICE_KEYBOARD, INPUT_DEVICE_MOUSE, UIManager::ShowUICursor(), UIScriptedMenu::UseGamepad(), UIScriptedMenu::UseKeyboard(), and UIScriptedMenu::UseMouse().
OnChange()
bool OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 451 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnClick()
bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 211 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnController()
bool OnController (Widget w, int control, int value) inline private
Definition at line 391 of file UIScriptedMenu.c.
References Count, and UIScriptedWindow::GetActiveWindows().
OnDoubleClick()
bool OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 241 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnDrag()
bool OnDrag (Widget w, int x, int y) inline private
Definition at line 466 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnDragging()
bool OnDragging (Widget w, int x, int y, Widget reciever) inline private
Definition at line 481 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnDraggingOver()
bool OnDraggingOver (Widget w, int x, int y, Widget reciever) inline private
Definition at line 496 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnDrop()
bool OnDrop (Widget w, int x, int y, Widget reciever) inline private
Definition at line 511 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnDropReceived()
bool OnDropReceived (Widget w, int x, int y, Widget reciever) inline private
Definition at line 526 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnEvent()
bool OnEvent (EventType eventType, Widget target, int parameter0, int parameter1) inline private
Definition at line 542 of file UIScriptedMenu.c.
References Count, and UIScriptedWindow::GetActiveWindows().
OnFocus()
bool OnFocus (Widget w, int x, int y) inline private
Definition at line 286 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnFocusLost()
bool OnFocusLost (Widget w, int x, int y) inline private
Definition at line 301 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnHide()
void OnHide () inline private
Definition at line 162 of file UIScriptedMenu.c.
OnItemSelected()
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
Definition at line 271 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnKeyDown()
bool OnKeyDown (Widget w, int x, int y, int key) inline private
Definition at line 406 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnKeyPress()
bool OnKeyPress (Widget w, int x, int y, int key) inline private
Definition at line 436 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnKeyUp()
bool OnKeyUp (Widget w, int x, int y, int key) inline private
Definition at line 421 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnModalResult()
bool OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 226 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnMouseButtonDown()
bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 346 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnMouseButtonUp()
bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 361 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnMouseEnter()
bool OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 316 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnMouseLeave()
bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 331 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnMouseWheel()
bool OnMouseWheel (Widget w, int x, int y, int wheel) inline private
Definition at line 376 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnRPC()
void OnRPC (ParamsReadContext ctx) inline private
Definition at line 568 of file UIScriptedMenu.c.
OnRPCEx()
void OnRPCEx (int rpc_type, ParamsReadContext ctx) inline private
Definition at line 569 of file UIScriptedMenu.c.
OnSelect()
bool OnSelect (Widget w, int x, int y) inline private
Definition at line 256 of file UIScriptedMenu.c.
References Count, UIScriptedWindow::GetActiveWindows(), x, and y.
OnShow()
void OnShow () inline private
Definition at line 156 of file UIScriptedMenu.c.
OnVisibilityChanged()
void OnVisibilityChanged (bool isVisible) inline private
If visibility of application is changed. On console it is called when application is suspended or constrained.
Parameters
isVisible indicate if application is visible in foreground
Definition at line 20 of file UIScriptedMenu.c.
OnXboxEvent()
bool OnXboxEvent (int xboxEvent) inline private
Definition at line 563 of file UIScriptedMenu.c.
Refresh()
void Refresh () inline private
Refresh request, called from anywhere.
Definition at line 53 of file UIScriptedMenu.c.
SetFadingPanels()
proto native void SetFadingPanels (Widget panel0, Widget panel1, Widget panel2, Widget panel3, Widget panel4) private
Refresh request, called from anywhere.
SetID()
void SetID (int id) inline private
Sets MenuID.
Definition at line 129 of file UIScriptedMenu.c.
SetParentMenu()
proto native void SetParentMenu (UIMenuPanel parent) private
SetSubMenu()
proto native void SetSubMenu (UIMenuPanel submenu) private
SetWidgetAnimAlpha()
void SetWidgetAnimAlpha (Widget widget) inline private
Definition at line 138 of file UIScriptedMenu.c.
UIScriptedMenu()
void UIScriptedMenu () inline private
Definition at line 119 of file UIScriptedMenu.c.
References MENU_UNKNOWN.
UnlockControls()
void UnlockControls () inline private
Definition at line 92 of file UIScriptedMenu.c.
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), INPUT_DEVICE_GAMEPAD, INPUT_DEVICE_KEYBOARD, INPUT_DEVICE_MOUSE, UIManager::ShowUICursor(), UIScriptedMenu::UseGamepad(), UIScriptedMenu::UseKeyboard(), and UIScriptedMenu::UseMouse().
Update()
void Update (float timeslice) inline private
Per frame update, called from engine.
Definition at line 168 of file UIScriptedMenu.c.
UseGamepad()
bool UseGamepad () inline private
Definition at line 43 of file UIScriptedMenu.c.
UseKeyboard()
bool UseKeyboard () inline private
Definition at line 35 of file UIScriptedMenu.c.
References GetGame(), CGame::GetInput(), and Input::IsEnabledMouseAndKeyboardEvenOnServer().
UseMouse()
bool UseMouse () inline private
Definition at line 27 of file UIScriptedMenu.c.
References GetGame(), CGame::GetInput(), and Input::IsEnabledMouseAndKeyboardEvenOnServer().
Field Documentation
layoutRoot
Widget layoutRoot private
Definition at line 63 of file UIScriptedMenu.c.
m_AnimAlphaIsIncreasing
private bool m_AnimAlphaIsIncreasing private
Definition at line 65 of file UIScriptedMenu.c.
m_AnimAlphaValue
private float m_AnimAlphaValue private
Definition at line 66 of file UIScriptedMenu.c.
m_AnimAlphaWidget
private Widget m_AnimAlphaWidget private
Definition at line 64 of file UIScriptedMenu.c.
m_id
int m_id private
Definition at line 62 of file UIScriptedMenu.c.
The documentation for this class was generated from the following file:
3_Game/tools/UIScriptedMenu.c