DayZ Scripts: GPSReceiver Class Reference
GPSReceiver Class Reference
Private Member Functions
void GPSReceiver ()
protected void PositionalUpdate ()
override void OnMovedInsideCargo (EntityAI container)
need to be overriden, otherwise the item will be turned off when moved to cargo
override void SetActions ()
override bool IsTurnedOn ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
protected void UpdateDisplayState (bool pIsTurnedOn)
protected void UpdateDisplayPosition ()
protected void UpdateDisplayElevation ()
protected int GetHiddenSelection (string selection)
override void OnDebugSpawn ()
Private Attributes
const string DISPLAY_TEXTURE_PATH_FORMAT = "dz\\gear\\navigation\\data\\GPS_%1_ca.paa"
const string ANIM_PHASE_DISPLAY_HIDE = "DisplayState"
protected ref set< string > m_DisplayGridSelections
protected ref set< string > m_DisplayAltSelections
protected ref map< int, string > m_DisplayNumericSignTextureMap
protected ref array< int > m_OrderedPositionNumbersLast
cache
protected ref array< int > m_AltitudeNumbersLast
Detailed Description
Definition at line 1 of file GPSReceiver.c.
Constructor & Destructor Documentation
GPSReceiver()
void GPSReceiver () inline private
translate numerical -1 to - texture
Definition at line 15 of file GPSReceiver.c.
References DISPLAY_TEXTURE_PATH_FORMAT, string::Format(), m_AltitudeNumbersLast, m_DisplayAltSelections, m_DisplayGridSelections, m_DisplayNumericSignTextureMap, m_OrderedPositionNumbersLast, and MapNavigationBehaviour().
Member Function Documentation
GetHiddenSelection()
protected int GetHiddenSelection (string selection) inline private
Definition at line 161 of file GPSReceiver.c.
References INDEX_NOT_FOUND.
Referenced by UpdateDisplayElevation(), and UpdateDisplayPosition().
IsTurnedOn()
override bool IsTurnedOn () inline private
Definition at line 78 of file GPSReceiver.c.
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 179 of file GPSReceiver.c.
OnMovedInsideCargo()
override void OnMovedInsideCargo (EntityAI container) private
need to be overriden, otherwise the item will be turned off when moved to cargo
OnWork()
override void OnWork (float consumed_energy) inline private
Definition at line 112 of file GPSReceiver.c.
References PositionalUpdate().
OnWorkStart()
override void OnWorkStart () inline private
Definition at line 84 of file GPSReceiver.c.
References UpdateDisplayState().
OnWorkStop()
override void OnWorkStop () inline private
Definition at line 98 of file GPSReceiver.c.
References UpdateDisplayState().
PositionalUpdate()
protected void PositionalUpdate () inline private
Definition at line 61 of file GPSReceiver.c.
References UpdateDisplayElevation(), and UpdateDisplayPosition().
Referenced by OnWork().
SetActions()
override void SetActions () inline private
Definition at line 70 of file GPSReceiver.c.
References AddAction().
UpdateDisplayElevation()
protected void UpdateDisplayElevation () inline private
Definition at line 142 of file GPSReceiver.c.
References GetHiddenSelection(), INDEX_NOT_FOUND, m_AltitudeNumbersLast, m_DisplayAltSelections, m_DisplayNumericSignTextureMap, and MapNavigationBehaviour().
Referenced by PositionalUpdate().
UpdateDisplayPosition()
protected void UpdateDisplayPosition () inline private
Definition at line 123 of file GPSReceiver.c.
References GetHiddenSelection(), INDEX_NOT_FOUND, m_DisplayGridSelections, m_DisplayNumericSignTextureMap, m_OrderedPositionNumbersLast, and MapNavigationBehaviour().
Referenced by PositionalUpdate().
UpdateDisplayState()
protected void UpdateDisplayState (bool pIsTurnedOn) inline private
Definition at line 118 of file GPSReceiver.c.
References ANIM_PHASE_DISPLAY_HIDE.
Referenced by OnWorkStart(), and OnWorkStop().
Field Documentation
ANIM_PHASE_DISPLAY_HIDE
const string ANIM_PHASE_DISPLAY_HIDE = "DisplayState" private
Definition at line 5 of file GPSReceiver.c.
Referenced by UpdateDisplayState().
DISPLAY_TEXTURE_PATH_FORMAT
const string DISPLAY_TEXTURE_PATH_FORMAT = "dz\\gear\\navigation\\data\\GPS_%1_ca.paa" private
Definition at line 4 of file GPSReceiver.c.
Referenced by GPSReceiver().
m_AltitudeNumbersLast
protected ref array<int> m_AltitudeNumbersLast private
Definition at line 13 of file GPSReceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayElevation().
m_DisplayAltSelections
protected ref set<string> m_DisplayAltSelections private
Definition at line 8 of file GPSReceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayElevation().
m_DisplayGridSelections
protected ref set<string> m_DisplayGridSelections private
Definition at line 7 of file GPSReceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayPosition().
m_DisplayNumericSignTextureMap
protected ref map<int, string> m_DisplayNumericSignTextureMap private
Definition at line 9 of file GPSReceiver.c.
Referenced by GPSReceiver(), UpdateDisplayElevation(), and UpdateDisplayPosition().
m_OrderedPositionNumbersLast
protected ref array<int> m_OrderedPositionNumbersLast private
cache
Definition at line 12 of file GPSReceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayPosition().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Gear/Navigation/GPSReceiver.c