DayZ Scripts Documentation: TestDiseaseMdfr Class Reference
TestDiseaseMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnActivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
float m_Interval
ref Param1< float > m_SomeValue
Detailed Description
Definition at line 1 of file TestDisease.c.
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
Definition at line 19 of file TestDisease.c.
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
Definition at line 39 of file TestDisease.c.
Init()
override void Init () inline private
Definition at line 6 of file TestDisease.c.
References DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), DisableDeactivateCheck(), m_ID, m_SomeValue, m_TickIntervalActive, m_TickIntervalInactive, m_TrackActivatedTime, and MakeParamObjectPersistent().
OnActivate()
override void OnActivate (PlayerBase player) inline private
Definition at line 24 of file TestDisease.c.
OnDeactivate()
override void OnDeactivate (PlayerBase player) inline private
Definition at line 35 of file TestDisease.c.
OnReconnect()
override void OnReconnect (PlayerBase player) inline private
Definition at line 29 of file TestDisease.c.
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
Definition at line 44 of file TestDisease.c.
Field Documentation
m_Interval
float m_Interval private
Definition at line 3 of file TestDisease.c.
m_SomeValue
ref Param1<float> m_SomeValue private
Definition at line 4 of file TestDisease.c.
Referenced by Init().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/diseases/TestDisease.c