DayZ: KuruShake Class Reference
KuruShake Class Reference
Private Member Functions
void KuruShake (PlayerBase player, float amount)
void Update (float delta_time, out float pos_x, out float pos_y)
Private Attributes
const float RANDOM_RANGE_POINT = 1
const float RANDOM_RANGE_DEVIATION = 0.50
const float SHAKE_DURATION_PHASE1 = 0.01
const float SHAKE_STRENGTH_MIN = 1
const float SHAKE_STRENGTH_MAX = 5
PlayerBase m_Player
float m_Time
float m_Time2
float m_RelativeTime
float m_RelativeTime2
float m_ShakeStrength
ref array< vector > m_Curve = new array<vector>
Detailed Description
Definition at line 1 of file KuruShake.c.
Constructor & Destructor Documentation
KuruShake()
void KuruShake (PlayerBase player, float amount) inline private
Definition at line 19 of file KuruShake.c.
References Math::Lerp(), m_Curve, m_ShakeStrength, vector::Normalize(), RANDOM_RANGE_DEVIATION, RANDOM_RANGE_POINT, Math::RandomFloat(), Math::Randomize(), SHAKE_STRENGTH_MAX, and SHAKE_STRENGTH_MIN.
Member Function Documentation
Update()
void Update (float delta_time, out float pos_x, out float pos_y) inline private
Definition at line 48 of file KuruShake.c.
References Math3D::Curve(), Easing::EaseInQuint(), Math::InverseLerp(), m_Curve, m_RelativeTime, m_RelativeTime2, m_Time, m_Time2, and SHAKE_DURATION_PHASE1.
Referenced by DayZPlayerImplementAiming::ProcessAimFilters().
Field Documentation
m_Curve
ref array<vector> m_Curve = new array<vector> private
Definition at line 17 of file KuruShake.c.
Referenced by KuruShake(), and Update().
m_Player
PlayerBase m_Player private
Definition at line 9 of file KuruShake.c.
m_RelativeTime
float m_RelativeTime private
Definition at line 12 of file KuruShake.c.
Referenced by Update().
m_RelativeTime2
float m_RelativeTime2 private
Definition at line 13 of file KuruShake.c.
Referenced by Update().
m_ShakeStrength
float m_ShakeStrength private
Definition at line 14 of file KuruShake.c.
Referenced by KuruShake().
m_Time
float m_Time private
Definition at line 10 of file KuruShake.c.
Referenced by Update().
m_Time2
float m_Time2 private
Definition at line 11 of file KuruShake.c.
Referenced by Update().
RANDOM_RANGE_DEVIATION
const float RANDOM_RANGE_DEVIATION = 0.50 private
Definition at line 4 of file KuruShake.c.
Referenced by KuruShake().
RANDOM_RANGE_POINT
const float RANDOM_RANGE_POINT = 1 private
Definition at line 3 of file KuruShake.c.
Referenced by KuruShake().
SHAKE_DURATION_PHASE1
const float SHAKE_DURATION_PHASE1 = 0.01 private
Definition at line 5 of file KuruShake.c.
Referenced by Update().
SHAKE_STRENGTH_MAX
const float SHAKE_STRENGTH_MAX = 5 private
Definition at line 7 of file KuruShake.c.
Referenced by KuruShake().
SHAKE_STRENGTH_MIN
const float SHAKE_STRENGTH_MIN = 1 private
Definition at line 6 of file KuruShake.c.
Referenced by KuruShake().
The documentation for this class was generated from the following file:
4_World/Classes/KuruShake.c