DayZ Scripts: AttachmentsGroupContainer Class Reference
AttachmentsGroupContainer Class Reference
Private Member Functions
override void SetLayoutName ()
override void SetHeader (Header header)
override Header GetHeader ()
void AttachmentsGroupContainer (LayoutHolder parent)
override void SetActive (bool active)
override void SetDefaultFocus (bool while_micromanagment_mode=false)
SlotsIcon GetSlotsIcon (int row, int column, bool include_invisible=true)
int GetRowCount (bool include_invisible=true)
int GetColumnCountForRow (int row, bool include_invisible=true)
override void SetNextActive ()
override void SetPreviousActive (bool force=false)
Private Attributes
ref Header m_Header
Detailed Description
Definition at line 1 of file AttachmentsGroupContainer.c.
Constructor & Destructor Documentation
AttachmentsGroupContainer()
void AttachmentsGroupContainer (LayoutHolder parent) inline private
Definition at line 21 of file AttachmentsGroupContainer.c.
Member Function Documentation
GetColumnCountForRow()
int GetColumnCountForRow (int row, bool include_invisible = true) inline private
Definition at line 67 of file AttachmentsGroupContainer.c.
Referenced by AttachmentCategoriesRow::RefreshAllSlots().
GetHeader()
override Header GetHeader () inline private
Definition at line 16 of file AttachmentsGroupContainer.c.
References m_Header.
GetRowCount()
int GetRowCount (bool include_invisible = true) inline private
Definition at line 55 of file AttachmentsGroupContainer.c.
Referenced by AttachmentCategoriesRow::RefreshAllSlots().
GetSlotsIcon()
SlotsIcon GetSlotsIcon (int row, int column, bool include_invisible = true) inline private
Definition at line 41 of file AttachmentsGroupContainer.c.
References SlotsContainer::GetSlotIcon().
Referenced by PlayerContainer::GetSlotsIcon(), and AttachmentCategoriesRow::RefreshSlot().
SetActive()
override void SetActive (bool active) inline private
Definition at line 26 of file AttachmentsGroupContainer.c.
Referenced by Attachments::SetActive().
SetDefaultFocus()
override void SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 35 of file AttachmentsGroupContainer.c.
Referenced by Attachments::SetDefaultFocus().
SetHeader()
override void SetHeader (Header header) inline private
Definition at line 10 of file AttachmentsGroupContainer.c.
References m_Header.
Referenced by AttachmentCategoriesRow::Init(), PlayerContainer::PlayerContainer(), and ZombieContainer::ZombieContainer().
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 5 of file AttachmentsGroupContainer.c.
References WidgetLayoutName::AttachmentsGroupContainer.
SetNextActive()
override void SetNextActive () inline private
Definition at line 81 of file AttachmentsGroupContainer.c.
References GetParent(), SlotsContainer::GetVisibleFocus(), SetActive(), Container::SetActive(), Container::SetNextActive(), and SlotsContainer::SetVisibleFocus().
SetPreviousActive()
override void SetPreviousActive (bool force = false) inline private
Definition at line 122 of file AttachmentsGroupContainer.c.
References GetParent(), SlotsContainer::GetVisibleFocus(), SetActive(), Container::SetActive(), Container::SetLastActive(), Container::SetPreviousActive(), and SlotsContainer::SetVisibleFocus().
Field Documentation
m_Header
ref Header m_Header private
Definition at line 3 of file AttachmentsGroupContainer.c.
Referenced by GetHeader(), and SetHeader().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Containers/AttachmentsGroupContainer.c