DayZ: ActionTakeItem Class Reference
ActionTakeItem Class Reference
Private Member Functions
void ActionTakeItem ()
override void CreateConditionComponents ()
override bool HasProneException ()
override bool ActionConditionContinue (ActionData action_data)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeUsedOnBack ()
override bool InventoryReservation (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
Private Attributes
string m_ItemName = ""
Detailed Description
Definition at line 6 of file ActionTakeItem.c.
Constructor & Destructor Documentation
ActionTakeItem()
void ActionTakeItem () inline private
Definition at line 10 of file ActionTakeItem.c.
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 33 of file ActionTakeItem.c.
References ItemBase::CanDetachAttachment(), and ItemBase::IsTakeable().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
Definition at line 28 of file ActionTakeItem.c.
CanBeUsedOnBack()
override bool CanBeUsedOnBack () inline private
Definition at line 55 of file ActionTakeItem.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 17 of file ActionTakeItem.c.
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool HasProneException () inline private
Definition at line 23 of file ActionTakeItem.c.
InventoryReservation()
override bool InventoryReservation (ActionData action_data) inline private
Definition at line 96 of file ActionTakeItem.c.
References GameInventory::c_InventoryReservationTimeoutMS, ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
Definition at line 153 of file ActionTakeItem.c.
References InventoryLocation::GetSlot(), ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
Definition at line 125 of file ActionTakeItem.c.
References ClearInventoryReservationEx(), GetGame(), InventoryLocation::GetSlot(), ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
Field Documentation
m_ItemName
string m_ItemName = "" private
Definition at line 8 of file ActionTakeItem.c.
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Interact/ActionTakeItem.c