DayZ Scripts Documentation: TrapBase Class Reference
TrapBase Class Reference
Private Member Functions
void BearTrap ()
override bool CanBeDisarmed ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void CreateTrigger ()
override void OnUpdate (EntityAI victim)
override void OnSteppedOn (EntityAI victim)
override void OnSteppedOut (EntityAI victim)
protected void OnServerSteppedOn (Object obj, string damageZone)
void CauseVictimToStartLimping (Object obj, string damagedZone)
void PlaySoundBiteLeg ()
void PlaySoundBiteEmpty ()
void PlaySoundOpen ()
override void OnActivate ()
override void OnDisarm ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool IsDeployable ()
override string GetLoopDeploySoundset ()
override void SetActions ()
Static Private Attributes
static const int RAYCAST_SOURCES_COUNT = 5
static const vector m_RaycastSources [RAYCAST_SOURCES_COUNT]
Detailed Description
Definition at line 1 of file Trap_Bear.c.
Member Function Documentation
BearTrap()
void BearTrap () inline private
Definition at line 14 of file Trap_Bear.c.
References m_AnimationPhaseGrounded, m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DamageOthers, m_DamagePlayers, m_DefectRate, and m_InitWaitTime.
CanBeDisarmed()
override bool CanBeDisarmed () inline private
Definition at line 25 of file Trap_Bear.c.
CauseVictimToStartLimping()
void CauseVictimToStartLimping (Object obj, string damagedZone) inline private
Definition at line 176 of file Trap_Bear.c.
References Class::CastTo().
Referenced by OnServerSteppedOn().
CreateTrigger()
override void CreateTrigger () inline private
Definition at line 43 of file Trap_Bear.c.
References GetOrientation(), m_TrapTrigger, Trigger::SetExtents(), and TrapTrigger::SetParentObject().
Referenced by SetActive().
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 30 of file Trap_Bear.c.
References GetGame(), SetInactive(), and GameConstants::STATE_RUINED.
GetLoopDeploySoundset()
override string GetLoopDeploySoundset () inline private
Definition at line 246 of file Trap_Bear.c.
Referenced by PlayDeployLoopSound().
IsDeployable()
override bool IsDeployable () inline private
Definition at line 241 of file Trap_Bear.c.
OnActivate()
override void OnActivate () inline private
Definition at line 209 of file Trap_Bear.c.
References PlaySoundOpen().
Referenced by SetActive().
OnDisarm()
override void OnDisarm () inline private
Definition at line 216 of file Trap_Bear.c.
References PlaySoundBiteEmpty().
Referenced by Disarm(), and OnRPC().
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 227 of file Trap_Bear.c.
References GetGame(), m_TrapTrigger, and StartActivate().
OnServerSteppedOn()
protected void OnServerSteppedOn (Object obj, string damageZone) inline private
Generic limp handling
Definition at line 136 of file Trap_Bear.c.
References Class::CastTo(), CauseVictimToStartLimping(), m_UpdateTimer, Math::RandomIntInclusive(), SetInactive(), Timer::Stop(), and Synch().
Referenced by OnSteppedOn(), OnUpdate(), and OnUpdate().
OnSteppedOn()
override void OnSteppedOn (EntityAI victim) inline private
CarScript specific reaction on BearTrap
this is also called on client (OnRPC->SnapOn->OnSteppedOn chain)
Definition at line 67 of file Trap_Bear.c.
References RaycastRVParams::flags, GetGame(), m_UpdateTimer, ModelToWorld(), OnServerSteppedOn(), PlaySoundBiteLeg(), RaycastRVParams::radius, DayZPhysics::RaycastRVProxy(), RaycastRVParams::type, and UPDATE_TIMER_INTERVAL.
Referenced by SnapOnObject().
OnSteppedOut()
override void OnSteppedOut (EntityAI victim) inline private
Definition at line 125 of file Trap_Bear.c.
References m_UpdateTimer, and Timer::Stop().
Referenced by RemoveFromObject().
OnUpdate()
override void OnUpdate (EntityAI victim) inline private
Definition at line 55 of file Trap_Bear.c.
References GetClosestCarWheel(), and OnServerSteppedOn().
PlaySoundBiteEmpty()
void PlaySoundBiteEmpty () inline private
Definition at line 197 of file Trap_Bear.c.
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnDisarm().
PlaySoundBiteLeg()
void PlaySoundBiteLeg () inline private
Definition at line 191 of file Trap_Bear.c.
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnSteppedOn().
PlaySoundOpen()
void PlaySoundOpen () inline private
Definition at line 203 of file Trap_Bear.c.
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnActivate().
SetActions()
override void SetActions () inline private
Definition at line 251 of file Trap_Bear.c.
References ActionDeployObject(), and AddAction().
Field Documentation
m_RaycastSources
const vector m_RaycastSources[RAYCAST_SOURCES_COUNT] static private
Initial value:
= {
        "0.0 0.1 0.0",
        "0.2 0.1 0.2",
        "-.2 0.1 0.2",
        "0.2 0.1 -0.2",
        "-0.2 0.1 -0.2"
    }
Definition at line 6 of file Trap_Bear.c.
RAYCAST_SOURCES_COUNT
const int RAYCAST_SOURCES_COUNT = 5 static private
Definition at line 3 of file Trap_Bear.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/TrapBase/Trap_Bear.c