DayZ Scripts: Clothing Class Reference
Clothing Class Reference
Private Member Functions
override bool CanPutInCargo (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par=null)
override int GetGlassesEffectID ()
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override int GetGlassesEffectID ()
override bool CanPutAsAttachment (EntityAI parent)
override array< int > GetEffectWidgetTypes ()
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
void Headtorch_ColorBase ()
override bool CanPutAsAttachment (EntityAI parent)
void CheckParent ()
override void OnWorkStart ()
override void OnWork (float consumed_energy)
void OnLightCreated ()
void CreateHeadtorchLight ()
void AttachLightOnHead (EntityAI person)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnWorkStop ()
override void SetActions ()
override bool IsLightSource ()
override ItemBase GetLightSourceItem ()
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool IsClothing ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override bool IsGasMask ()
override array< int > GetEffectWidgetTypes ()
override bool AllowFoodConsumption ()
override void OnDebugSpawn ()
override void EEItemAttached (EntityAI item, string slot_name)
EntityAI GetExternalFilter ()
bool HasValidFilter ()
has either external or integrated non-empty non-ruined filter ?
float GetFilterQuantityMax ()
float GetFilterQuantity ()
float GetFilterQuantity01 ()
bool IsExternalFilterAttached ()
bool HasIntegratedFilter ()
bool CanHaveExternalFilter ()
bool ConsumeQuantity (float quantity, PlayerBase consumer_player)
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player)
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player, float quantity)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
void MouthRag ()
override bool CanDetachAttachment (EntityAI parent)
override bool IsObstructingVoice ()
override int GetVoiceEffect ()
void SetIncomingLambaBool (bool state)
bool GetIncomingLambdaBool ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void SetActions ()
override int GetGlassesEffectID ()
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
void LargeTentBackPack ()
void ~LargeTentBackPack ()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
void PlayRepackingLoopSound ()
void StopRepackingLoopSound ()
override void SetActions ()
Private Attributes
HeadtorchLight m_Light
ref Timer m_Timer
float m_LowFilterEventTime
bool m_IncomingLambdaChange
ref protected EffectSound m_RepackingLoopSound
Static Private Attributes
static int REFLECTOR_ID = 4
static int GLASS_ID = 5
static string LIGHT_OFF_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass.rvmat"
static string LIGHT_OFF_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch.rvmat"
static string LIGHT_ON_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass_on.rvmat"
static string LIGHT_ON_GLASS_RED = "dz\\characters\\headgear\\data\\HeadTorchGlass_on_red.rvmat"
static string LIGHT_ON_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch_ON.rvmat"
static string LIGHT_ON_REFLECTOR_RED = "dz\\characters\\headgear\\data\\HeadTorch_ON_red.rvmat"
static vector m_OnHeadLocalPos = Vector(0.12,0.15,0)
static vector m_OnHeadLocalOri = Vector(0,90,0)
static string m_OffHeadLightPoint = "beamStart"
static string m_OffHeadLightTarget = "beamEnd"
Detailed Description
Definition at line 1 of file AliceBag_ColorBase.c.
Constructor & Destructor Documentation
~LargeTentBackPack()
void ~LargeTentBackPack () inline private
Definition at line 10 of file LargeTentBackPack.c.
References SEffectManager::DestroyEffect(), and m_RepackingLoopSound.
Member Function Documentation
AllowFoodConsumption()
override bool AllowFoodConsumption () inline private
Definition at line 15 of file MaskBase.c.
AttachLightOnHead()
void AttachLightOnHead (EntityAI person) inline private
Definition at line 156 of file Headtorch_ColorBase.c.
References m_Light.
Referenced by CreateHeadtorchLight(), and OnWasAttached().
CanDetachAttachment()
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 10 of file MouthRag.c.
References m_IncomingLambdaChange.
CanHaveExternalFilter()
bool CanHaveExternalFilter () inline private
Definition at line 103 of file MaskBase.c.
CanPutAsAttachment() [1/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 13 of file Armband_ColorBase.c.
References GetQuantity().
CanPutAsAttachment() [2/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 8 of file AviatorGlasses.c.
CanPutAsAttachment() [3/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file CrookedNose.c.
CanPutAsAttachment() [4/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 8 of file DesignerGlasses.c.
CanPutAsAttachment() [5/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 8 of file EyePatch_improvised.c.
CanPutAsAttachment() [6/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 30 of file Headtorch_ColorBase.c.
CanPutAsAttachment() [7/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file HockeyMask.c.
CanPutAsAttachment() [8/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file NVGHeadstrap.c.
CanPutAsAttachment() [9/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file SantasBeard.c.
CanPutAsAttachment() [10/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file SportGlasses_ColorBase.c.
CanPutAsAttachment() [11/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 8 of file TacticalGoggles.c.
CanPutAsAttachment() [12/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file ThickFramesGlasses.c.
CanPutAsAttachment() [13/13]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file ThinFramesGlasses.c.
CanPutInCargo() [1/2]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 3 of file Armband_ColorBase.c.
References GetNumberOfItems(), and EntityAI::IsMan().
CanPutInCargo() [2/2]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 3 of file LeatherBelt_ColorBase.c.
References IsEmpty().
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 13 of file LeatherBelt_ColorBase.c.
CheckParent()
void CheckParent () inline private
Definition at line 50 of file Headtorch_ColorBase.c.
References m_Timer, and Timer::Stop().
ConsumeQuantity()
bool ConsumeQuantity (float quantity, PlayerBase consumer_player) inline private
Definition at line 108 of file MaskBase.c.
References GetQuantity(), and HasQuantity().
CreateHeadtorchLight()
void CreateHeadtorchLight () inline private
Definition at line 113 of file Headtorch_ColorBase.c.
References AttachLightOnHead(), InventorySlots::GetSlotIdFromString(), m_Light, and OnLightCreated().
Referenced by OnWorkStart().
EEItemAttached() [1/2]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 25 of file MaskBase.c.
EEItemAttached() [2/2]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 3 of file SmershVest.c.
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 13 of file SmershVest.c.
GetEffectWidgetTypes() [1/2]
override array< int > GetEffectWidgetTypes () inline private
Definition at line 3 of file EyePatch_improvised.c.
Referenced by ManBase::EEItemAttached(), and ManBase::EEItemDetached().
GetEffectWidgetTypes() [2/2]
override array< int > GetEffectWidgetTypes () inline private
Definition at line 10 of file MaskBase.c.
GetExternalFilter()
EntityAI GetExternalFilter () inline private
Definition at line 31 of file MaskBase.c.
GetFilterQuantity()
float GetFilterQuantity () inline private
Definition at line 60 of file MaskBase.c.
References GetQuantity().
GetFilterQuantity01()
float GetFilterQuantity01 () inline private
Definition at line 69 of file MaskBase.c.
References GetQuantity(), GetQuantityMax(), and Math::InverseLerp().
GetFilterQuantityMax()
float GetFilterQuantityMax () inline private
Definition at line 48 of file MaskBase.c.
References GetQuantityMax(), and HasQuantity().
GetGlassesEffectID() [1/3]
override int GetGlassesEffectID () inline private
Definition at line 3 of file AviatorGlasses.c.
Referenced by ManBase::EEItemAttached(), and ManBase::EEItemDetached().
GetGlassesEffectID() [2/3]
override int GetGlassesEffectID () inline private
Definition at line 3 of file DesignerGlasses.c.
GetGlassesEffectID() [3/3]
override int GetGlassesEffectID () inline private
Definition at line 3 of file TacticalGoggles.c.
GetIncomingLambdaBool()
bool GetIncomingLambdaBool () inline private
Definition at line 30 of file MouthRag.c.
References m_IncomingLambdaChange.
GetLightSourceItem()
override ItemBase GetLightSourceItem () inline private
Definition at line 244 of file Headtorch_ColorBase.c.
Referenced by ToggleLightsActionInput::UpdatePossibleActions().
GetVoiceEffect()
override int GetVoiceEffect () inline private
Definition at line 20 of file MouthRag.c.
HasIntegratedFilter()
bool HasIntegratedFilter () inline private
Definition at line 98 of file MaskBase.c.
References HasQuantity().
HasValidFilter()
bool HasValidFilter () inline private
has either external or integrated non-empty non-ruined filter ?
Definition at line 37 of file MaskBase.c.
References GetQuantity(), and IsRuined().
Headtorch_ColorBase()
void Headtorch_ColorBase () inline private
Definition at line 22 of file Headtorch_ColorBase.c.
References CALL_CATEGORY_SYSTEM, and m_Timer.
IsClothing()
override bool IsClothing () inline private
Definition at line 3 of file LeatherSack_ColorBase.c.
IsExternalFilterAttached()
bool IsExternalFilterAttached () inline private
Definition at line 93 of file MaskBase.c.
IsGasMask()
override bool IsGasMask () inline private
Definition at line 5 of file MaskBase.c.
Referenced by ManBase::EEItemAttached(), and ManBase::EEItemDetached().
IsLightSource()
override bool IsLightSource () inline private
Definition at line 239 of file Headtorch_ColorBase.c.
IsObstructingVoice()
override bool IsObstructingVoice () inline private
Definition at line 15 of file MouthRag.c.
Referenced by ManBase::CheckForGag().
LargeTentBackPack()
void LargeTentBackPack () inline private
Definition at line 5 of file LargeTentBackPack.c.
References m_RepackingLoopSound.
MouthRag()
void MouthRag () inline private
Definition at line 5 of file MouthRag.c.
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 20 of file MaskBase.c.
OnLightCreated()
void OnLightCreated () inline private
Definition at line 108 of file Headtorch_ColorBase.c.
References m_Light, and PointLightBase::SetColorToWhite().
Referenced by CreateHeadtorchLight().
OnQuantityConsumed() [1/2]
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player) inline private
Definition at line 131 of file MaskBase.c.
OnQuantityConsumed() [2/2]
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player, float quantity) inline private
Definition at line 133 of file MaskBase.c.
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 15 of file LargeTentBackPack.c.
References PlayRepackingLoopSound(), Serializer::Read(), and StopRepackingLoopSound().
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 186 of file Headtorch_ColorBase.c.
References AttachLightOnHead(), and m_Light.
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 201 of file Headtorch_ColorBase.c.
References m_Light.
OnWork()
override void OnWork (float consumed_energy) inline private
Definition at line 86 of file Headtorch_ColorBase.c.
References GetGame(), m_Light, and PointLightBase::SetIntensity().
OnWorkStart()
override void OnWorkStart () inline private
Definition at line 67 of file Headtorch_ColorBase.c.
References CreateHeadtorchLight(), and GetGame().
OnWorkStop()
override void OnWorkStop () inline private
Definition at line 216 of file Headtorch_ColorBase.c.
References GetGame(), and m_Light.
PlayRepackingLoopSound()
void PlayRepackingLoopSound () inline private
Definition at line 43 of file LargeTentBackPack.c.
References GetPosition, m_RepackingLoopSound, and SEffectManager::PlaySound().
Referenced by OnRPC().
SetActions() [1/85]
override void SetActions () inline private
Definition at line 23 of file Armband_ColorBase.c.
References AddAction().
SetActions() [2/85]
override void SetActions () inline private
Definition at line 3 of file Balaclava3Holes_ColorBase.c.
References AddAction().
SetActions() [3/85]
override void SetActions () inline private
Definition at line 3 of file BalaclavaMask_ColorBase.c.
References AddAction().
SetActions() [4/85]
override void SetActions () inline private
Definition at line 3 of file BaseballCap_ColorBase.c.
References AddAction().
SetActions() [5/85]
override void SetActions () inline private
Definition at line 3 of file BDUJacket.c.
References AddAction().
SetActions() [6/85]
override void SetActions () inline private
Definition at line 3 of file BDUPants.c.
References AddAction().
SetActions() [7/85]
override void SetActions () inline private
Definition at line 3 of file BeanieHat_ColorBase.c.
References AddAction().
SetActions() [8/85]
override void SetActions () inline private
Definition at line 3 of file Blouse_ColorBase.c.
References AddAction().
SetActions() [9/85]
override void SetActions () inline private
Definition at line 3 of file BomberJacket_ColorBase.c.
References AddAction().
SetActions() [10/85]
override void SetActions () inline private
Definition at line 3 of file BoonieHat_ColorBase.c.
References AddAction().
SetActions() [11/85]
override void SetActions () inline private
Definition at line 3 of file Breeches_ColorBase.c.
References AddAction().
SetActions() [12/85]
override void SetActions () inline private
Definition at line 3 of file CanvasPants.c.
References AddAction().
SetActions() [13/85]
override void SetActions () inline private
Definition at line 17 of file CanvasPants.c.
References AddAction().
SetActions() [14/85]
override void SetActions () inline private
Definition at line 3 of file CargoPants_ColorBase.c.
References AddAction().
SetActions() [15/85]
override void SetActions () inline private
Definition at line 3 of file ChernarusSportShirt.c.
References AddAction().
SetActions() [16/85]
override void SetActions () inline private
Definition at line 3 of file DenimJacket.c.
References AddAction().
SetActions() [17/85]
override void SetActions () inline private
Definition at line 22 of file EyePatch_improvised.c.
References AddAction().
SetActions() [18/85]
override void SetActions () inline private
Definition at line 3 of file FaceCover_improvised.c.
References AddAction().
SetActions() [19/85]
override void SetActions () inline private
Definition at line 3 of file FeetCover_improvised.c.
References AddAction().
SetActions() [20/85]
override void SetActions () inline private
Definition at line 3 of file FirefighterJacket_ColorBase.c.
References AddAction().
SetActions() [21/85]
override void SetActions () inline private
Definition at line 3 of file FirefightersPants_ColorBase.c.
References AddAction().
SetActions() [22/85]
override void SetActions () inline private
Definition at line 3 of file FlatCap_ColorBase.c.
References AddAction().
SetActions() [23/85]
override void SetActions () inline private
Definition at line 3 of file GorkaEJacket_ColorBase.c.
References AddAction().
SetActions() [24/85]
override void SetActions () inline private
Definition at line 3 of file GorkaPants_ColorBase.c.
References AddAction().
SetActions() [25/85]
override void SetActions () inline private
Definition at line 3 of file HandsCover_improvised.c.
References AddAction().
SetActions() [26/85]
override void SetActions () inline private
Definition at line 3 of file HeadCover_improvised.c.
References AddAction().
SetActions() [27/85]
override void SetActions () inline private
Definition at line 230 of file Headtorch_ColorBase.c.
References AddAction().
SetActions() [28/85]
override void SetActions () inline private
Definition at line 3 of file HikingJacket_ColorBase.c.
References AddAction().
SetActions() [29/85]
override void SetActions () inline private
Definition at line 3 of file Hoodie_ColorBase.c.
References AddAction().
SetActions() [30/85]
override void SetActions () inline private
Definition at line 3 of file HunterPants_ColorBase.c.
References AddAction().
SetActions() [31/85]
override void SetActions () inline private
Definition at line 3 of file HuntingJacket_ColorBase.c.
References AddAction().
SetActions() [32/85]
override void SetActions () inline private
Definition at line 3 of file Jeans_ColorBase.c.
References AddAction().
SetActions() [33/85]
override void SetActions () inline private
Definition at line 18 of file Jeans_ColorBase.c.
References AddAction().
SetActions() [34/85]
override void SetActions () inline private
Definition at line 3 of file JumpsuitJacket_ColorBase.c.
References AddAction().
SetActions() [35/85]
override void SetActions () inline private
Definition at line 3 of file JumpsuitPants_ColorBase.c.
References AddAction().
SetActions() [36/85]
override void SetActions () inline private
Definition at line 3 of file LabCoat.c.
References AddAction().
SetActions() [37/85]
override void SetActions () inline private
Definition at line 3 of file LegCover_improvised.c.
References AddAction().
SetActions() [38/85]
override void SetActions () inline private
Definition at line 3 of file M65Jacket_ColorBase.c.
References AddAction().
SetActions() [39/85]
override void SetActions () inline private
Definition at line 3 of file ManSuit_ColorBase.c.
References AddAction().
SetActions() [40/85]
override void SetActions () inline private
Definition at line 3 of file MedicalScrubsHat_ColorBase.c.
References AddAction().
SetActions() [41/85]
override void SetActions () inline private
Definition at line 3 of file MedicalScrubsPants_ColorBase.c.
References AddAction().
SetActions() [42/85]
override void SetActions () inline private
Definition at line 3 of file MedicalScrubsShirt_ColorBase.c.
References AddAction().
SetActions() [43/85]
override void SetActions () inline private
Definition at line 3 of file MiniDress_ColorBase.c.
References AddAction().
SetActions() [44/85]
override void SetActions () inline private
Definition at line 3 of file NBCJacketBase.c.
References AddAction().
SetActions() [45/85]
override void SetActions () inline private
Definition at line 3 of file NBCPantsBase.c.
References AddAction().
SetActions() [46/85]
override void SetActions () inline private
Definition at line 3 of file NurseDress_ColorBase.c.
References AddAction().
SetActions() [47/85]
override void SetActions () inline private
Definition at line 23 of file NVGHeadstrap.c.
References AddAction().
SetActions() [48/85]
override void SetActions () inline private
Definition at line 3 of file ParamedicJacket_ColorBase.c.
References AddAction().
SetActions() [49/85]
override void SetActions () inline private
Definition at line 3 of file ParamedicPants_ColorBase.c.
References AddAction().
SetActions() [50/85]
override void SetActions () inline private
Definition at line 3 of file PilotkaCap.c.
References AddAction().
SetActions() [51/85]
override void SetActions () inline private
Definition at line 3 of file PoliceJacket.c.
References AddAction().
SetActions() [52/85]
override void SetActions () inline private
Definition at line 3 of file PoliceJacketOrel.c.
References AddAction().
SetActions() [53/85]
override void SetActions () inline private
Definition at line 3 of file PolicePants.c.
References AddAction().
SetActions() [54/85]
override void SetActions () inline private
Definition at line 3 of file PolicePantsOrel.c.
References AddAction().
SetActions() [55/85]
override void SetActions () inline private
Definition at line 3 of file PrisonerCap.c.
References AddAction().
SetActions() [56/85]
override void SetActions () inline private
Definition at line 3 of file PrisonUniformJacket.c.
References AddAction().
SetActions() [57/85]
override void SetActions () inline private
Definition at line 3 of file PrisonUniformPants.c.
References AddAction().
SetActions() [58/85]
override void SetActions () inline private
Definition at line 3 of file QuiltedJacket_ColorBase.c.
References AddAction().
SetActions() [59/85]
override void SetActions () inline private
Definition at line 3 of file RadarCap_ColorBase.c.
References AddAction().
SetActions() [60/85]
override void SetActions () inline private
Definition at line 3 of file RidersJacket_ColorBase.c.
References AddAction().
SetActions() [61/85]
override void SetActions () inline private
Definition at line 16 of file SantasBeard.c.
References AddAction().
SetActions() [62/85]
override void SetActions () inline private
Definition at line 3 of file SantasHat.c.
References AddAction().
SetActions() [63/85]
override void SetActions () inline private
Definition at line 3 of file Shirt_ColorBase.c.
References AddAction().
SetActions() [64/85]
override void SetActions () inline private
Definition at line 3 of file Skirt_ColorBase.c.
References AddAction().
SetActions() [65/85]
override void SetActions () inline private
Definition at line 3 of file SlacksPants_ColorBase.c.
References AddAction().
SetActions() [66/85]
override void SetActions () inline private
Definition at line 3 of file SurgicalMask.c.
References AddAction().
SetActions() [67/85]
override void SetActions () inline private
Definition at line 3 of file Sweater_ColorBase.c.
References AddAction().
SetActions() [68/85]
override void SetActions () inline private
Definition at line 3 of file TacticalShirt_ColorBase.c.
References AddAction().
SetActions() [69/85]
override void SetActions () inline private
Definition at line 3 of file TankerHelmet.c.
References AddAction().
SetActions() [70/85]
override void SetActions () inline private
Definition at line 3 of file TelnyashkaShirt.c.
References AddAction().
SetActions() [71/85]
override void SetActions () inline private
Definition at line 3 of file TorsoCover_improvised.c.
References AddAction().
SetActions() [72/85]
override void SetActions () inline private
Definition at line 3 of file TrackSuitJacket_ColorBase.c.
References AddAction().
SetActions() [73/85]
override void SetActions () inline private
Definition at line 3 of file TrackSuitPants_ColorBase.c.
References AddAction().
SetActions() [74/85]
override void SetActions () inline private
Definition at line 3 of file TShirt_ColorBase.c.
References AddAction().
SetActions() [75/85]
override void SetActions () inline private
Definition at line 3 of file TTsKOJacket_ColorBase.c.
References AddAction().
SetActions() [76/85]
override void SetActions () inline private
Definition at line 3 of file TTSKOPants.c.
References AddAction().
SetActions() [77/85]
override void SetActions () inline private
Definition at line 3 of file Ushanka_ColorBase.c.
References AddAction().
SetActions() [78/85]
override void SetActions () inline private
Definition at line 3 of file USMCJacket_ColorBase.c.
References AddAction().
SetActions() [79/85]
override void SetActions () inline private
Definition at line 3 of file USMCPants_ColorBase.c.
References AddAction().
SetActions() [80/85]
override void SetActions () inline private
Definition at line 3 of file WitchHat.c.
References AddAction().
SetActions() [81/85]
override void SetActions () inline private
Definition at line 3 of file WitchHood.c.
References AddAction().
SetActions() [82/85]
override void SetActions () inline private
Definition at line 3 of file WomanSuit_ColorBase.c.
References AddAction().
SetActions() [83/85]
override void SetActions () inline private
Definition at line 3 of file WoolCoat_ColorBase.c.
References AddAction().
SetActions() [84/85]
override void SetActions () inline private
Definition at line 3 of file ZmijovkaCap_ColorBase.c.
References AddAction().
SetActions() [85/85]
override void SetActions () inline private
Definition at line 57 of file LargeTentBackPack.c.
SetIncomingLambaBool()
void SetIncomingLambaBool (bool state) inline private
Definition at line 25 of file MouthRag.c.
StopRepackingLoopSound()
void StopRepackingLoopSound () inline private
Definition at line 51 of file LargeTentBackPack.c.
References m_RepackingLoopSound.
Referenced by OnRPC().
SwitchItemSelectionTextureEx()
override void SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par = null) inline private
Definition at line 29 of file Armband_ColorBase.c.
Field Documentation
GLASS_ID
int GLASS_ID = 5 static private
Definition at line 6 of file Headtorch_ColorBase.c.
LIGHT_OFF_GLASS
string LIGHT_OFF_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass.rvmat" static private
Definition at line 8 of file Headtorch_ColorBase.c.
LIGHT_OFF_REFLECTOR
string LIGHT_OFF_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch.rvmat" static private
Definition at line 9 of file Headtorch_ColorBase.c.
LIGHT_ON_GLASS
string LIGHT_ON_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass_on.rvmat" static private
Definition at line 10 of file Headtorch_ColorBase.c.
LIGHT_ON_GLASS_RED
string LIGHT_ON_GLASS_RED = "dz\\characters\\headgear\\data\\HeadTorchGlass_on_red.rvmat" static private
Definition at line 11 of file Headtorch_ColorBase.c.
LIGHT_ON_REFLECTOR
string LIGHT_ON_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch_ON.rvmat" static private
Definition at line 12 of file Headtorch_ColorBase.c.
LIGHT_ON_REFLECTOR_RED
string LIGHT_ON_REFLECTOR_RED = "dz\\characters\\headgear\\data\\HeadTorch_ON_red.rvmat" static private
Definition at line 13 of file Headtorch_ColorBase.c.
m_IncomingLambdaChange
bool m_IncomingLambdaChange private
Definition at line 3 of file MouthRag.c.
Referenced by CanDetachAttachment(), and GetIncomingLambdaBool().
m_Light
HeadtorchLight m_Light private
Definition at line 3 of file Headtorch_ColorBase.c.
m_LowFilterEventTime
float m_LowFilterEventTime private
Definition at line 3 of file MaskBase.c.
m_OffHeadLightPoint
string m_OffHeadLightPoint = "beamStart" static private
Definition at line 17 of file Headtorch_ColorBase.c.
m_OffHeadLightTarget
string m_OffHeadLightTarget = "beamEnd" static private
Definition at line 18 of file Headtorch_ColorBase.c.
m_OnHeadLocalOri
vector m_OnHeadLocalOri = Vector(0,90,0) static private
Definition at line 16 of file Headtorch_ColorBase.c.
m_OnHeadLocalPos
vector m_OnHeadLocalPos = Vector(0.12,0.15,0) static private
Definition at line 15 of file Headtorch_ColorBase.c.
m_RepackingLoopSound
ref protected EffectSound m_RepackingLoopSound private
Definition at line 3 of file LargeTentBackPack.c.
m_Timer
ref Timer m_Timer private
Definition at line 20 of file Headtorch_ColorBase.c.
REFLECTOR_ID
int REFLECTOR_ID = 4 static private
Definition at line 5 of file Headtorch_ColorBase.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/Clothing/AliceBag_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Headtorch_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MaskBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MouthRag.c
P:/scripts/4_World/Entities/ItemBase/TentBase/LargeTentBackPack.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Armband_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/AviatorGlasses.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Balaclava3Holes_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BalaclavaMask_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BaseballCap_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BDUJacket.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BDUPants.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BeanieHat_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Blouse_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BomberJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BoonieHat_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Breeches_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/CanvasPants.c
P:/scripts/4_World/Entities/ItemBase/Clothing/CargoPants_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/ChernarusSportShirt.c
P:/scripts/4_World/Entities/ItemBase/Clothing/CrookedNose.c
P:/scripts/4_World/Entities/ItemBase/Clothing/DenimJacket.c
P:/scripts/4_World/Entities/ItemBase/Clothing/DesignerGlasses.c
P:/scripts/4_World/Entities/ItemBase/Clothing/EyePatch_improvised.c
P:/scripts/4_World/Entities/ItemBase/Clothing/FaceCover_improvised.c
P:/scripts/4_World/Entities/ItemBase/Clothing/FeetCover_improvised.c
P:/scripts/4_World/Entities/ItemBase/Clothing/FirefighterJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/FirefightersPants_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/FlatCap_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/GorkaEJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/GorkaPants_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HandsCover_improvised.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HeadCover_improvised.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HikingJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HockeyMask.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Hoodie_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HunterPants_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HuntingJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Jeans_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/JumpsuitJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/JumpsuitPants_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/LabCoat.c
P:/scripts/4_World/Entities/ItemBase/Clothing/LeatherBelt_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/LeatherSack_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/LegCover_improvised.c
P:/scripts/4_World/Entities/ItemBase/Clothing/M65Jacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/ManSuit_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MedicalScrubsHat_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MedicalScrubsPants_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MedicalScrubsShirt_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MiniDress_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/NBCJacketBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/NBCPantsBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/NurseDress_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/NVGHeadstrap.c
P:/scripts/4_World/Entities/ItemBase/Clothing/ParamedicJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/ParamedicPants_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PilotkaCap.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PoliceJacket.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PoliceJacketOrel.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PolicePants.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PolicePantsOrel.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PrisonerCap.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PrisonUniformJacket.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PrisonUniformPants.c
P:/scripts/4_World/Entities/ItemBase/Clothing/QuiltedJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/RadarCap_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/RidersJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/SantasBeard.c
P:/scripts/4_World/Entities/ItemBase/Clothing/SantasHat.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Shirt_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Skirt_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/SlacksPants_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/SmershVest.c
P:/scripts/4_World/Entities/ItemBase/Clothing/SportGlasses_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/SurgicalMask.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Sweater_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TacticalGoggles.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TacticalShirt_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TankerHelmet.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TelnyashkaShirt.c
P:/scripts/4_World/Entities/ItemBase/Clothing/ThickFramesGlasses.c
P:/scripts/4_World/Entities/ItemBase/Clothing/ThinFramesGlasses.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TorsoCover_improvised.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TrackSuitJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TrackSuitPants_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TShirt_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TTsKOJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TTSKOPants.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Ushanka_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/USMCJacket_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/USMCPants_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/WitchHat.c
P:/scripts/4_World/Entities/ItemBase/Clothing/WitchHood.c
P:/scripts/4_World/Entities/ItemBase/Clothing/WomanSuit_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/WoolCoat_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/ZmijovkaCap_ColorBase.c