DayZ: Component Class Reference
Component Class Reference
Private Member Functions
void Event_OnFrame (IEntity other, float timeSlice)
Shape DebugBBoxDraw ()
void DebugBBoxSetColor (int color)
void DebugBBoxDelete ()
Shape DebugDirectionDraw (float distance=1)
void DebugDirectionSetColor (int color)
void DebugDirectionDelete ()
void SetParentEntityAI (EntityAI e)
void Event_OnAwake ()
void Event_OnInit ()
void LogThis (string msg, string fnc_name="n/a")
void LogThisWarning (string msg, string fnc_name="n/a")
void LogThisError (string msg, string fnc_name="n/a")
string GetCompName ()
int GetCompType ()
void Event_OnItemAttached (EntityAI item, string slot_name)
void Event_OnItemDetached (EntityAI item, string slot_name)
override Shape DebugBBoxDraw ()
override void DebugBBoxSetColor (int color)
override void DebugBBoxDelete ()
override Shape DebugDirectionDraw (float distance=1)
override void DebugDirectionDelete ()
void OnDrawing ()
Static Private Member Functions
static void Init ()
static string GetNameByType (int comp_type)
static bool IsTypeExist (int comp_type)
static void LogErrorBadCompType (int comp_type, string fnc_name)
static void LogWarningAlredyExist (int comp_type, string fnc_name)
Private Attributes
protected EntityAI m_ThisEntityAI
protected Shape m_DebugShapeBBox
protected Shape m_DebugShapeDirection
protected float m_DebugShapeDirectionDist
Static Private Attributes
static private string m_CompNames [COMP_TYPE_COUNT]
Detailed Description
Definition at line 15 of file Component.c.
Member Function Documentation
DebugBBoxDelete() [1/2]
void DebugBBoxDelete () private
DebugBBoxDelete() [2/2]
override void DebugBBoxDelete () inline private
Definition at line 42 of file ComponentEntityDebug.c.
References CALL_CATEGORY_GUI, CGame::GetCallQueue(), GetGame(), and ScriptCallQueue::Remove().
DebugBBoxDraw() [1/2]
Shape DebugBBoxDraw () private
DebugBBoxDraw() [2/2]
override Shape DebugBBoxDraw () inline private
Definition at line 9 of file ComponentEntityDebug.c.
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), Debug::DrawBox(), CGame::GetCallQueue(), and GetGame().
DebugBBoxSetColor() [1/2]
void DebugBBoxSetColor (int color) private
DebugBBoxSetColor() [2/2]
override void DebugBBoxSetColor (int color) inline private
Definition at line 33 of file ComponentEntityDebug.c.
DebugDirectionDelete() [1/2]
void DebugDirectionDelete () private
DebugDirectionDelete() [2/2]
override void DebugDirectionDelete () inline private
Definition at line 84 of file ComponentEntityDebug.c.
References CALL_CATEGORY_GUI, CGame::GetCallQueue(), GetGame(), and ScriptCallQueue::Remove().
DebugDirectionDraw() [1/2]
Shape DebugDirectionDraw (float distance = 1) private
DebugDirectionDraw() [2/2]
override Shape DebugDirectionDraw (float distance = 1) inline private
Definition at line 61 of file ComponentEntityDebug.c.
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), Debug::DrawArrow(), CGame::GetCallQueue(), GetGame(), and m_DebugShapeDirectionDist.
DebugDirectionSetColor()
void DebugDirectionSetColor (int color) private
Event_OnAwake()
void Event_OnAwake () inline private
Definition at line 102 of file Component.c.
Referenced by ComponentsBank::CreateComponent().
Event_OnFrame()
void Event_OnFrame (IEntity other, float timeSlice) private
Event_OnInit()
void Event_OnInit () inline private
Definition at line 110 of file Component.c.
Referenced by ComponentsBank::CreateComponent().
Event_OnItemAttached()
void Event_OnItemAttached (EntityAI item, string slot_name) inline private
Definition at line 158 of file Component.c.
References LogThis().
Event_OnItemDetached()
void Event_OnItemDetached (EntityAI item, string slot_name) inline private
Definition at line 167 of file Component.c.
References LogThis().
GetCompName()
string GetCompName () inline private
Definition at line 142 of file Component.c.
References GetCompType(), and GetNameByType().
Referenced by LogThisError(), and LogThisWarning().
GetCompType()
int GetCompType () inline private
Definition at line 150 of file Component.c.
References COMP_TYPE_UNDEFINED.
Referenced by GetCompName().
GetNameByType()
static string GetNameByType (int comp_type) inline static private
Definition at line 48 of file Component.c.
References IsTypeExist(), LogErrorBadCompType(), and m_CompNames.
Referenced by ComponentsBank::CreateComponent(), GetCompName(), and LogWarningAlredyExist().
Init()
static void Init () inline static private
Definition at line 37 of file Component.c.
References COMP_TYPE_ANIMAL_BLEEDING, COMP_TYPE_BODY_STAGING, COMP_TYPE_ENERGY_MANAGER, COMP_TYPE_ETITY_DEBUG, and m_CompNames.
Referenced by DayZGame().
IsTypeExist()
static bool IsTypeExist (int comp_type) inline static private
Definition at line 62 of file Component.c.
References COMP_TYPE_COUNT.
Referenced by ComponentsBank::CreateComponent(), ComponentsBank::GetComponent(), and GetNameByType().
LogErrorBadCompType()
static void LogErrorBadCompType (int comp_type, string fnc_name) inline static private
Definition at line 76 of file Component.c.
References COMP_TYPE_COUNT, Debug::LogError(), and ToString().
Referenced by ComponentsBank::CreateComponent(), ComponentsBank::GetComponent(), and GetNameByType().
LogThis()
void LogThis (string msg, string fnc_name = "n/a") inline private
Definition at line 118 of file Component.c.
Referenced by Event_OnItemAttached(), and Event_OnItemDetached().
LogThisError()
void LogThisError (string msg, string fnc_name = "n/a") inline private
Definition at line 134 of file Component.c.
References GetCompName(), Debug::LogError(), and m_ThisEntityAI.
LogThisWarning()
void LogThisWarning (string msg, string fnc_name = "n/a") inline private
Definition at line 126 of file Component.c.
References GetCompName(), Debug::LogWarning(), and m_ThisEntityAI.
LogWarningAlredyExist()
static void LogWarningAlredyExist (int comp_type, string fnc_name) inline static private
Definition at line 85 of file Component.c.
References GetNameByType(), and Debug::LogError().
Referenced by ComponentsBank::CreateComponent().
OnDrawing()
void OnDrawing () inline private
Definition at line 102 of file ComponentEntityDebug.c.
SetParentEntityAI()
void SetParentEntityAI (EntityAI e) inline private
Definition at line 94 of file Component.c.
References m_ThisEntityAI.
Referenced by ComponentsBank::CreateComponent().
Field Documentation
m_CompNames
private string m_CompNames[COMP_TYPE_COUNT] static private
Definition at line 20 of file Component.c.
Referenced by GetNameByType(), and Init().
m_DebugShapeBBox
protected Shape m_DebugShapeBBox private
Definition at line 4 of file ComponentEntityDebug.c.
m_DebugShapeDirection
protected Shape m_DebugShapeDirection private
Definition at line 5 of file ComponentEntityDebug.c.
m_DebugShapeDirectionDist
protected float m_DebugShapeDirectionDist private
Definition at line 6 of file ComponentEntityDebug.c.
Referenced by DebugDirectionDraw().
m_ThisEntityAI
protected EntityAI m_ThisEntityAI private
Definition at line 24 of file Component.c.
Referenced by ComponentAnimalBleeding::Bleed(), ComponentEnergyManager::CanBePluggedInto(), ComponentEnergyManager::CanReceivePlugFrom(), ComponentEnergyManager::CanWork(), ComponentEnergyManager::CheckWetness(), ComponentEnergyManager::ConsumeEnergy(), ComponentEnergyManager::DebugUpdate(), ComponentEnergyManager::DeviceUpdate(), ComponentEnergyManager::Event_OnAwake(), ComponentEnergyManager::Event_OnInit(), ComponentEnergyManager::FindAndConsumeEnergy(), ComponentEnergyManager::GetEnergyMax(), ComponentEnergyManager::GetThisEntityAI(), ComponentAnimalBleeding::InflictWoundDamage(), LogThisError(), LogThisWarning(), ComponentEnergyManager::OnAttachmentAdded(), ComponentEnergyManager::OnDeviceDestroyed(), ComponentEnergyManager::OnEnergyAdded(), ComponentEnergyManager::OnEnergyConsumed(), ComponentEnergyManager::OnIsPlugged(), ComponentEnergyManager::OnIsUnplugged(), ComponentEnergyManager::OnOwnSocketReleased(), ComponentEnergyManager::OnOwnSocketTaken(), ComponentEnergyManager::OnWork(), ComponentEnergyManager::PlugInDevice(), ComponentEnergyManager::PlugThisInto(), ComponentEnergyManager::ResetEnergyUsage(), ComponentEnergyManager::SetEnergy(), SetParentEntityAI(), ComponentEnergyManager::SwitchOff(), ComponentEnergyManager::SwitchOn(), ComponentEnergyManager::Synch(), ComponentBodyStaging::SynchSkinnedState(), ComponentEnergyManager::UnplugCordFromSocket(), ComponentEnergyManager::UnplugDevice(), ComponentEnergyManager::UnplugThis(), ComponentEnergyManager::UpdateCanWork(), ComponentEnergyManager::UpdatePlugState(), ComponentEnergyManager::UpdateSelections(), and ComponentEnergyManager::UpdateSocketSelections().
The documentation for this class was generated from the following files:
3_Game/tools/Component.c
3_Game/tools/Component/ComponentEntityDebug.c