DayZ Scripts Documentation: Backlit Class Reference
Backlit Class Reference
Backlit effect class.
Private Member Functions
void OnInit (DayZGame game)
void LoadingAnim ()
void MainMenu_OnShow ()
void MainMenu_OnHide ()
void OnEnterCar ()
void OnLeaveCar ()
void OnSwimmingStart ()
void OnSwimmingStop ()
void HintClear ()
void HintShow (UAInput action)
void KeybindingClear ()
void KeybindingShow (int keyHash)
void VisualiseHealth (int iLevel)
void VisualiseBlood (int iLevel)
void SetHealth (float fHealth)
void SetBlood (float fBlood)
void UpdatePlayer (bool bForce)
void RefreshVehicleLayout (int iGear, bool bCEL)
Private Attributes
bool m_BacklitActive
int m_HealthBefore = -1
int m_BloodBefore = -1
int m_HealthNew = 0
int m_BloodNew = 0
int m_GearBefore = 0
bool m_CELBefore = false
Detailed Description
Backlit effect class.
Definition at line 104 of file Backlit.c.
Member Function Documentation
HintClear()
void HintClear () inline private
Definition at line 211 of file Backlit.c.
References UAInputAPI::Backlit_Remove(), EUABLAYER_HINTKEY, GetUApi(), and m_BacklitActive.
HintShow()
void HintShow (UAInput action) inline private
Definition at line 221 of file Backlit.c.
References UAInput::Backlit_Override(), EUABLAYER_HINTKEY, and m_BacklitActive.
KeybindingClear()
void KeybindingClear () inline private
Definition at line 230 of file Backlit.c.
References UAInputAPI::Backlit_Remove(), EUABLAYER_ALL, GetUApi(), and m_BacklitActive.
KeybindingShow()
void KeybindingShow (int keyHash) inline private
Definition at line 239 of file Backlit.c.
References UAInputAPI::Backlit_KeyByHash(), EUABACKLIT_FADEOUT_SLOW, EUABLAYER_VISKEY, GetUApi(), and m_BacklitActive.
LoadingAnim()
void LoadingAnim () inline private
Definition at line 121 of file Backlit.c.
References UAInputAPI::Backlit_Animation(), UAInputAPI::Backlit_ForceUpdate(), UAInputAPI::Backlit_KeyByName(), EUABACKLIT_ON, EUABLAYER_LOADING, GetUApi(), and m_BacklitActive.
MainMenu_OnHide()
void MainMenu_OnHide () inline private
Definition at line 148 of file Backlit.c.
References UAInputAPI::Backlit_Background(), UAInputAPI::Backlit_Remove(), EUABLAYER_ALL, GetUApi(), and m_BacklitActive.
MainMenu_OnShow()
void MainMenu_OnShow () inline private
Definition at line 136 of file Backlit.c.
References UAInputAPI::Backlit_Animation(), UAInputAPI::Backlit_ForceUpdate(), UAInputAPI::Backlit_Remove(), EUABLAYER_ALL, GetUApi(), and m_BacklitActive.
OnEnterCar()
void OnEnterCar () inline private
Definition at line 158 of file Backlit.c.
References UAInputAPI::Backlit_Background(), UAInputAPI::Backlit_Remove(), EUABLAYER_ALL, GetUApi(), and m_BacklitActive.
OnInit()
void OnInit (DayZGame game) inline private
Definition at line 110 of file Backlit.c.
References m_BacklitActive, and Print().
Referenced by DayZGame().
OnLeaveCar()
void OnLeaveCar () inline private
Definition at line 168 of file Backlit.c.
References UAInputAPI::Backlit_Background(), UAInputAPI::Backlit_Remove(), EUABLAYER_ALL, GetGame(), GetUApi(), m_BacklitActive, and UpdatePlayer().
OnSwimmingStart()
void OnSwimmingStart () inline private
Definition at line 184 of file Backlit.c.
References UAInputAPI::Backlit_Animation(), UAInputAPI::Backlit_EmptyQueue(), GetUApi(), and m_BacklitActive.
OnSwimmingStop()
void OnSwimmingStop () inline private
Definition at line 196 of file Backlit.c.
References UAInputAPI::Backlit_Background(), GetGame(), GetUApi(), m_BacklitActive, and UpdatePlayer().
RefreshVehicleLayout()
void RefreshVehicleLayout (int iGear, bool bCEL) inline private
Definition at line 390 of file Backlit.c.
References UAInputAPI::Backlit_KeyByName(), EUABACKLIT_NONE, EUABACKLIT_ON, EUABLAYER_CAR, GetUApi(), m_BacklitActive, m_CELBefore, and m_GearBefore.
SetBlood()
void SetBlood (float fBlood) inline private
Definition at line 336 of file Backlit.c.
References m_BloodNew.
SetHealth()
void SetHealth (float fHealth) inline private
Definition at line 330 of file Backlit.c.
References m_HealthNew.
UpdatePlayer()
void UpdatePlayer (bool bForce) inline private
Definition at line 342 of file Backlit.c.
References UAInputAPI::Backlit_Background(), UAInputAPI::Backlit_KeyByName(), UAInputAPI::Backlit_Remove(), EUABACKLIT_ON, EUABLAYER_ALL, EUABLAYER_CUSTOM, GetUApi(), m_BacklitActive, m_BloodBefore, m_BloodNew, m_HealthBefore, m_HealthNew, VisualiseBlood(), and VisualiseHealth().
Referenced by OnLeaveCar(), and OnSwimmingStop().
VisualiseBlood()
void VisualiseBlood (int iLevel) inline private
Definition at line 286 of file Backlit.c.
References UAInputAPI::Backlit_KeyByName(), EUABACKLIT_ON, EUABLAYER_HUMAN, and GetUApi().
Referenced by UpdatePlayer().
VisualiseHealth()
void VisualiseHealth (int iLevel) inline private
Definition at line 248 of file Backlit.c.
References UAInputAPI::Backlit_KeyByName(), EUABACKLIT_ON, EUABLAYER_HUMAN, and GetUApi().
Referenced by UpdatePlayer().
Field Documentation
m_BacklitActive
bool m_BacklitActive private
Definition at line 108 of file Backlit.c.
Referenced by HintClear(), HintShow(), KeybindingClear(), KeybindingShow(), LoadingAnim(), MainMenu_OnHide(), MainMenu_OnShow(), OnEnterCar(), OnInit(), OnLeaveCar(), OnSwimmingStart(), OnSwimmingStop(), RefreshVehicleLayout(), and UpdatePlayer().
m_BloodBefore
int m_BloodBefore = -1 private
Definition at line 325 of file Backlit.c.
Referenced by UpdatePlayer().
m_BloodNew
int m_BloodNew = 0 private
Definition at line 328 of file Backlit.c.
Referenced by SetBlood(), and UpdatePlayer().
m_CELBefore
bool m_CELBefore = false private
Definition at line 388 of file Backlit.c.
Referenced by RefreshVehicleLayout().
m_GearBefore
int m_GearBefore = 0 private
Definition at line 387 of file Backlit.c.
Referenced by RefreshVehicleLayout().
m_HealthBefore
int m_HealthBefore = -1 private
Definition at line 324 of file Backlit.c.
Referenced by UpdatePlayer().
m_HealthNew
int m_HealthNew = 0 private
Definition at line 327 of file Backlit.c.
Referenced by SetHealth(), and UpdatePlayer().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Effects/Backlit/Backlit.c