DayZ Scripts Documentation: ErrorHandlerModule Class Reference
ErrorHandlerModule Class Reference
Definition and API of an ErrorHandlerModule - Do not insert any logic here! (as this class is not moddable)
Private Member Functions
proto native ErrorCategory GetCategory ()
Returns the category the module handles.
proto native void SetCategory (ErrorCategory category)
Set the category the module handles.
protected void OnErrorThrown (int errorCode, owned string additionalInfo="")
Event that gets triggered when an error of the owned category is thrown.
string GetClientMessage (int errorCode, string additionalInfo="")
Retrieve the message shown on Client.
string GetLastClientMessage (int errorCode)
Retrieve the message shown on Client.
string GetServerMessage (int errorCode, string additionalInfo="")
Retrieve the message shown on Server.
string GetLastServerMessage (int errorCode)
Retrieve the message shown on Server.
string GetSimpleMessage (int errorCode, string additionalInfo="")
Simple message of just code and info.
void OnEvent (EventType eventTypeId, Param params)
Event called by ErrorModuleHandler.
Detailed Description
Definition and API of an ErrorHandlerModule - Do not insert any logic here! (as this class is not moddable)
Definition at line 5 of file ErrorHandlerModule.c.
Member Function Documentation
GetCategory()
proto native ErrorCategory GetCategory () private
Returns the category the module handles.
GetClientMessage()
string GetClientMessage (int errorCode, string additionalInfo = "") inline private
Retrieve the message shown on Client.
Definition at line 22 of file ErrorHandlerModule.c.
References GetSimpleMessage().
Referenced by GetLastClientMessage().
GetLastClientMessage()
string GetLastClientMessage (int errorCode) inline private
Retrieve the message shown on Client.
Definition at line 28 of file ErrorHandlerModule.c.
References GetSimpleMessage().
GetLastServerMessage()
string GetLastServerMessage (int errorCode) inline private
Retrieve the message shown on Server.
Definition at line 40 of file ErrorHandlerModule.c.
References GetSimpleMessage().
GetServerMessage()
string GetServerMessage (int errorCode, string additionalInfo = "") inline private
Retrieve the message shown on Server.
Definition at line 34 of file ErrorHandlerModule.c.
References GetSimpleMessage().
Referenced by GetLastServerMessage().
GetSimpleMessage()
string GetSimpleMessage (int errorCode, string additionalInfo = "") inline private
Simple message of just code and info.
Definition at line 46 of file ErrorHandlerModule.c.
References string::Format(), and ErrorModuleHandler::GetErrorHex().
Referenced by GetClientMessage(), GetLastClientMessage(), GetLastServerMessage(), and GetServerMessage().
OnErrorThrown()
protected void OnErrorThrown (int errorCode, owned string additionalInfo = "") inline private
Event that gets triggered when an error of the owned category is thrown.
Definition at line 14 of file ErrorHandlerModule.c.
References ErrorModuleHandler::GetErrorHex(), and Print().
OnEvent()
void OnEvent (EventType eventTypeId, Param params) inline private
Event called by ErrorModuleHandler.
Definition at line 52 of file ErrorHandlerModule.c.
SetCategory()
proto native void SetCategory (ErrorCategory category) private
Set the category the module handles.
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Global/ErrorModuleHandler/ErrorHandlerModule.c