DayZ: Easing Class Reference
Easing Class Reference
Input value between 0 and 1, returns value adjusted by easing, no automatic clamping of input(do your own !!)
Static Private Member Functions
static float EaseInSine (float t)
static float EaseOutSine (float t)
static float EaseInOutSine (float t)
static float EaseInQuad (float t)
static float EaseOutQuad (float t)
static float EaseInOutQuad (float t)
static float EaseInCubic (float t)
static float EaseOutCubic (float t)
static float EaseInOutCubic (float t)
static float EaseInQuart (float t)
static float EaseOutQuart (float t)
static float EaseInOutQuart (float t)
static float EaseInQuint (float t)
static float EaseOutQuint (float t)
static float EaseInOutQuint (float t)
static float EaseInExpo (float t)
static float EaseOutExpo (float t)
static float EaseInOutExpo (float t)
static float EaseInCirc (float t)
static float EaseOutCirc (float t)
static float EaseInOutCirc (float t)
static float EaseInBack (float t, float magnitude=1.70158)
static float EaseOutBack (float t, float magnitude=1.70158)
static float EaseInOutBack (float t, float magnitude=1.70158)
static float EaseInElastic (float t, float magnitude=0.7)
static float EaseOutElastic (float t, float magnitude=0.7)
static float EaseInOutElastic (float t, float magnitude=0.65)
static float EaseOutBounce (float t)
static float EaseInBounce (float t)
static float EaseInOutBounce (float t)
Detailed Description
Input value between 0 and 1, returns value adjusted by easing, no automatic clamping of input(do your own !!)
Definition at line 2 of file Easing.c.
Member Function Documentation
EaseInBack()
static float EaseInBack (float t, float magnitude = 1.70158) inline static private
Definition at line 168 of file Easing.c.
EaseInBounce()
static float EaseInBounce (float t) inline static private
Definition at line 271 of file Easing.c.
References EaseOutBounce().
Referenced by EaseInOutBounce().
EaseInCirc()
static float EaseInCirc (float t) inline static private
Definition at line 142 of file Easing.c.
References Math::Sqrt().
Referenced by PoisoningMdfr::OnTick().
EaseInCubic()
static float EaseInCubic (float t) inline static private
Definition at line 37 of file Easing.c.
Referenced by PPERequester_GameplayBase::OnStart().
EaseInElastic()
static float EaseInElastic (float t, float magnitude = 0.7) inline static private
Definition at line 195 of file Easing.c.
References Math::Asin(), Math::PI, Math::Pow(), and Math::Sin().
EaseInExpo()
static float EaseInExpo (float t) inline static private
Definition at line 103 of file Easing.c.
References Math::Pow().
Referenced by PPERequester_GameplayBase::OnUpdate().
EaseInOutBack()
static float EaseInOutBack (float t, float magnitude = 1.70158) inline static private
Definition at line 179 of file Easing.c.
EaseInOutBounce()
static float EaseInOutBounce (float t) inline static private
Definition at line 276 of file Easing.c.
References EaseInBounce(), and EaseOutBounce().
EaseInOutCirc()
static float EaseInOutCirc (float t) inline static private
Definition at line 154 of file Easing.c.
References Math::Sqrt().
EaseInOutCubic()
static float EaseInOutCubic (float t) inline static private
Definition at line 48 of file Easing.c.
EaseInOutElastic()
static float EaseInOutElastic (float t, float magnitude = 0.65) inline static private
Definition at line 222 of file Easing.c.
References Math::Asin(), Math::PI, Math::Pow(), and Math::Sin().
EaseInOutExpo()
static float EaseInOutExpo (float t) inline static private
Definition at line 122 of file Easing.c.
References Math::Pow().
EaseInOutQuad()
static float EaseInOutQuad (float t) inline static private
Definition at line 29 of file Easing.c.
EaseInOutQuart()
static float EaseInOutQuart (float t) inline static private
Definition at line 68 of file Easing.c.
Referenced by DayZPlayerImplementFallDamage::HandleFallDamage().
EaseInOutQuint()
static float EaseInOutQuint (float t) inline static private
Definition at line 89 of file Easing.c.
EaseInOutSine()
static float EaseInOutSine (float t) inline static private
Definition at line 14 of file Easing.c.
References Math::Cos(), and Math::PI.
Referenced by EOnPostSimulate(), and PPERequester_GameplayBase::FadeColourMult().
EaseInQuad()
static float EaseInQuad (float t) inline static private
Definition at line 19 of file Easing.c.
EaseInQuart()
static float EaseInQuart (float t) inline static private
Definition at line 56 of file Easing.c.
Referenced by PPERequester_GameplayBase::SetFlashbangIntensity(), ShockHandler::Update(), and Update().
EaseInQuint()
static float EaseInQuint (float t) inline static private
Definition at line 78 of file Easing.c.
Referenced by OnUpdateTimerIn(), and KuruShake::Update().
EaseInSine()
static float EaseInSine (float t) inline static private
Definition at line 4 of file Easing.c.
References Math::Cos(), and Math::PI.
EaseOutBack()
static float EaseOutBack (float t, float magnitude = 1.70158) inline static private
Definition at line 173 of file Easing.c.
Referenced by RecoilBase::ApplyCamOffset().
EaseOutBounce()
static float EaseOutBounce (float t) inline static private
Definition at line 244 of file Easing.c.
Referenced by EaseInBounce(), and EaseInOutBounce().
EaseOutCirc()
static float EaseOutCirc (float t) inline static private
Definition at line 148 of file Easing.c.
References Math::Sqrt().
EaseOutCubic()
static float EaseOutCubic (float t) inline static private
Definition at line 42 of file Easing.c.
Referenced by OnUpdateTimerOut().
EaseOutElastic()
static float EaseOutElastic (float t, float magnitude = 0.7) inline static private
Definition at line 209 of file Easing.c.
References Math::Asin(), Math::PI, Math::Pow(), and Math::Sin().
EaseOutExpo()
static float EaseOutExpo (float t) inline static private
Definition at line 113 of file Easing.c.
References Math::Pow().
EaseOutQuad()
static float EaseOutQuad (float t) inline static private
Definition at line 24 of file Easing.c.
EaseOutQuart()
static float EaseOutQuart (float t) inline static private
Definition at line 61 of file Easing.c.
EaseOutQuint()
static float EaseOutQuint (float t) inline static private
Definition at line 83 of file Easing.c.
EaseOutSine()
static float EaseOutSine (float t) inline static private
Definition at line 9 of file Easing.c.
References Math::PI, and Math::Sin().
Referenced by BleedingIndicatorDropData::AdjustColorSaturation(), and PPEMatClassParameterColor::ModifyResultValues().
The documentation for this class was generated from the following file:
3_Game/Static/Easing.c