DayZ: UndergroundTriggerCarrierBase Class Reference
UndergroundTriggerCarrierBase Class Reference
Private Member Functions
void UndergroundTriggerCarrier ()
void ~UndergroundTriggerCarrier ()
override void OnVariablesSynchronized ()
bool CanSpawnTrigger ()
void RequestDelayedTriggerSpawn ()
void SpawnTrigger ()
Private Attributes
ref JsonUndergroundAreaTriggerData m_Data
UndergroundTrigger m_Trigger
Detailed Description
This entity exists both client andserver side when it enters into player's bubble and gets instantiated client-side, it will locally spawn UndergroundTrigger, which is the actual trigger
Definition at line 3 of file UndergroundTrigger.c.
Constructor & Destructor Documentation
~UndergroundTriggerCarrier()
void ~UndergroundTriggerCarrier () inline private
Definition at line 13 of file UndergroundTrigger.c.
References GetGame().
Member Function Documentation
CanSpawnTrigger()
bool CanSpawnTrigger () inline private
Definition at line 31 of file UndergroundTrigger.c.
References UndergroundAreaLoader::m_JsonData.
Referenced by SpawnTrigger().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Definition at line 22 of file UndergroundTrigger.c.
References SpawnTrigger().
RequestDelayedTriggerSpawn()
void RequestDelayedTriggerSpawn () inline private
Definition at line 36 of file UndergroundTrigger.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
Referenced by SpawnTrigger().
SpawnTrigger()
void SpawnTrigger () inline private
Definition at line 42 of file UndergroundTrigger.c.
References AddChild(), CanSpawnTrigger(), ECE_LOCAL, GetGame(), GetOrientation(), GetPosition, UndergroundAreaLoader::m_JsonData, RequestDelayedTriggerSpawn(), JsonUndergroundTriggers::Triggers, and vector::Zero.
Referenced by OnVariablesSynchronized().
UndergroundTriggerCarrier()
void UndergroundTriggerCarrier () inline private
Definition at line 8 of file UndergroundTrigger.c.
Field Documentation
m_Data
ref JsonUndergroundAreaTriggerData m_Data private
Definition at line 5 of file UndergroundTrigger.c.
m_Trigger
UndergroundTrigger m_Trigger private
Definition at line 6 of file UndergroundTrigger.c.
The documentation for this class was generated from the following file:
4_World/Entities/ScriptedEntities/Triggers/UndergroundTrigger.c