DayZ Scripts Documentation: CAContinuousQuantityEdible Class Reference
CAContinuousQuantityEdible Class Reference
Private Member Functions
void CAContinuousQuantityEdible (float quantity_used_per_second, float time_to_repeat)
override void Setup (ActionData action_data)
override void CalcAndSetQuantity (ActionData action_data)
override float GetProgress ()
Private Attributes
protected float m_InitItemQuantity
protected float m_SpentQuantityTotal
Detailed Description
Definition at line 1 of file CAContinuousQuantityEdible.c.
Constructor & Destructor Documentation
CAContinuousQuantityEdible()
void CAContinuousQuantityEdible (float quantity_used_per_second, float time_to_repeat) inline private
Definition at line 6 of file CAContinuousQuantityEdible.c.
References CAContinuousQuantityRepeat::m_DefaultTimeToRepeat, m_InitItemQuantity, CAContinuousQuantityRepeat::m_QuantityUsedPerSecond, and m_SpentQuantityTotal.
Member Function Documentation
CalcAndSetQuantity()
override void CalcAndSetQuantity (ActionData action_data) inline private
Definition at line 24 of file CAContinuousQuantityEdible.c.
References GetGame(), ActionData::m_MainItem, ActionData::m_Player, CAContinuousQuantityRepeat::m_SpentQuantity, m_SpentQuantityTotal, CAContinuousQuantityRepeat::m_SpentUnits, ActionData::m_Target, and CABase::SetACData().
GetProgress()
override float GetProgress () inline private
Definition at line 56 of file CAContinuousQuantityEdible.c.
References Math::Clamp(), m_InitItemQuantity, CAContinuousQuantityRepeat::m_SpentQuantity, and m_SpentQuantityTotal.
Setup()
override void Setup (ActionData action_data) inline private
Definition at line 14 of file CAContinuousQuantityEdible.c.
References m_InitItemQuantity, and ActionData::m_MainItem.
Field Documentation
m_InitItemQuantity
protected float m_InitItemQuantity private
Definition at line 3 of file CAContinuousQuantityEdible.c.
Referenced by CAContinuousQuantityEdible(), GetProgress(), and Setup().
m_SpentQuantityTotal
protected float m_SpentQuantityTotal private
Definition at line 4 of file CAContinuousQuantityEdible.c.
Referenced by CAContinuousQuantityEdible(), CalcAndSetQuantity(), and GetProgress().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousQuantityEdible.c