DayZ Scripts Documentation: PlantSuper Class Reference
PlantSuper Class Reference
Specific tree class can be declared as: class TreeHard + _ + p3d filename (without extension)
Private Member Functions
override void OnTreeCutDown (EntityAI cutting_entity)
override bool IsTree ()
override void OnTreeCutDown (EntityAI cutting_entity)
override bool IsTree ()
override void OnTreeCutDown (EntityAI cutting_entity)
override bool IsBush ()
override void OnTreeCutDown (EntityAI cutting_entity)
override bool IsBush ()
Detailed Description
Specific tree class can be declared as: class TreeHard + _ + p3d filename (without extension)
For specific tree declaration see description of TreeHard.
//exapmle for tree DZ\plants2\tree\t_acer2s.p3d
class TreeHard_t_acer2s: TreeHard
{
};
For specific tree declaration see description of TreeHard default values for hard bushes
Definition at line 17 of file Plant.c.
Member Function Documentation
IsBush() [1/2]
override bool IsBush () inline private
Definition at line 164 of file Plant.c.
IsBush() [2/2]
override bool IsBush () inline private
Definition at line 225 of file Plant.c.
IsTree() [1/2]
override bool IsTree () inline private
Definition at line 27 of file Plant.c.
IsTree() [2/2]
override bool IsTree () inline private
Definition at line 95 of file Plant.c.
OnTreeCutDown() [1/4]
override void OnTreeCutDown (EntityAI cutting_entity) inline private
Definition at line 19 of file Plant.c.
References GetGame(), and CGame::RPCSingleParam().
OnTreeCutDown() [2/4]
override void OnTreeCutDown (EntityAI cutting_entity) inline private
Definition at line 89 of file Plant.c.
References GetGame(), and CGame::RPCSingleParam().
OnTreeCutDown() [3/4]
override void OnTreeCutDown (EntityAI cutting_entity) inline private
Definition at line 158 of file Plant.c.
References GetGame(), and CGame::RPCSingleParam().
OnTreeCutDown() [4/4]
override void OnTreeCutDown (EntityAI cutting_entity) inline private
Definition at line 219 of file Plant.c.
References GetGame(), and CGame::RPCSingleParam().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Core/Inherited/Plant.c