DayZ Scripts Documentation: ActionRepairCarChassis Class Reference
ActionRepairCarChassis Class Reference
Private Member Functions
void ActionRepairCarChassis ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override ActionData CreateActionData ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Private Attributes
protected m_LastValidType
protected string m_CurrentDamageZone
protected int m_LastValidComponentIndex
Detailed Description
Definition at line 19 of file ActionRepairCarChassis.c.
Constructor & Destructor Documentation
ActionRepairCarChassis()
void ActionRepairCarChassis () inline private
Definition at line 25 of file ActionRepairCarChassis.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_LastValidComponentIndex, m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 44 of file ActionRepairCarChassis.c.
References GetGame(), m_CurrentDamageZone, m_LastValidComponentIndex, m_LastValidType, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
CreateActionData()
override ActionData CreateActionData () inline private
Definition at line 154 of file ActionRepairCarChassis.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 38 of file ActionRepairCarChassis.c.
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::REPAIR.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 196 of file ActionRepairCarChassis.c.
References RepairCarPartActionReciveData::m_DamageZoneRecived.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 97 of file ActionRepairCarChassis.c.
References Math::Clamp(), GameConstants::DAMAGE_BADLY_DAMAGED_VALUE, GameConstants::DAMAGE_DAMAGED_VALUE, GameConstants::DAMAGE_RUINED_VALUE, GetGame(), m_CurrentDamageZone, ActionData::m_MainItem, ActionData::m_Target, Math::RandomFloatInclusive(), GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 172 of file ActionRepairCarChassis.c.
References HasTarget(), RepairCarPartActionReciveData::m_DamageZoneRecived, and Serializer::Read().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 160 of file ActionRepairCarChassis.c.
References Class::CastTo(), HasTarget(), m_CurrentDamageZone, and Serializer::Write().
Field Documentation
m_CurrentDamageZone
protected string m_CurrentDamageZone private
Definition at line 22 of file ActionRepairCarChassis.c.
Referenced by ActionCondition(), OnFinishProgressServer(), and WriteToContext().
m_LastValidComponentIndex
protected int m_LastValidComponentIndex private
Definition at line 23 of file ActionRepairCarChassis.c.
Referenced by ActionCondition(), and ActionRepairCarChassis().
m_LastValidType
protected m_LastValidType private
Definition at line 21 of file ActionRepairCarChassis.c.
Referenced by ActionCondition().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionRepairCarChassis.c