DayZ: ActionTakeMaterialToHands Class Reference
ActionTakeMaterialToHands Class Reference
Private Member Functions
void ActionTakeMaterialToHands ()
override void CreateConditionComponents ()
override bool HasProneException ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanContinue (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
protected void OnExecuteImpl (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override void CreateAndSetupActionCallback (ActionData action_data)
Detailed Description
Definition at line 1 of file ActionTakeMaterialToHands.c.
Constructor & Destructor Documentation
ActionTakeMaterialToHands()
void ActionTakeMaterialToHands () inline private
Definition at line 3 of file ActionTakeMaterialToHands.c.
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 42 of file ActionTakeMaterialToHands.c.
References ConstructionActionData::GetActualAttachmentToDetach(), GetGame(), BaseBuildingBase::IsPlayerInside(), and ConstructionActionData::RefreshAttachmentsToDetach().
CanContinue()
override bool CanContinue (ActionData action_data) inline private
Definition at line 70 of file ActionTakeMaterialToHands.c.
CreateAndSetupActionCallback()
override void CreateAndSetupActionCallback (ActionData action_data) inline private
Definition at line 109 of file ActionTakeMaterialToHands.c.
References Class::CastTo(), ConstructionActionData::GetActualAttachmentToDetach(), AnimatedActionBase::GetCallbackClassTypename(), ActionBaseCB::InitActionComponent(), ActionData::m_Callback, ActionData::m_Player, and ActionBaseCB::SetActionData().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 10 of file ActionTakeMaterialToHands.c.
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType () inline private
Definition at line 32 of file ActionTakeMaterialToHands.c.
HasProgress()
override bool HasProgress () inline private
Definition at line 37 of file ActionTakeMaterialToHands.c.
HasProneException()
override bool HasProneException () inline private
Definition at line 16 of file ActionTakeMaterialToHands.c.
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 21 of file ActionTakeMaterialToHands.c.
References ConstructionActionData::GetActualAttachmentToDetach(), and m_Text.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
Definition at line 75 of file ActionTakeMaterialToHands.c.
References OnExecuteImpl().
OnExecuteImpl()
protected void OnExecuteImpl (ActionData action_data) inline private
Definition at line 80 of file ActionTakeMaterialToHands.c.
References ConstructionActionData::GetActualAttachmentToDetach(), and ActionData::m_Player.
Referenced by OnExecuteClient(), and OnExecuteServer().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
Definition at line 101 of file ActionTakeMaterialToHands.c.
References GetGame(), and OnExecuteImpl().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Interact/ActionTakeMaterialToHands.c