DayZ: AreaDamageComponentRaycasted Class Reference
AreaDamageComponentRaycasted Class Reference
Newer implementation equivalent of "AreaDamageRegularRaycasted", hitzone selection only.
Private Member Functions
void AreaDamageComponentRaycasted (AreaDamageManager parent)
override void OnTriggerCreated ()
void SetRaycastSources (array< string > raycast_sources)
void SetRaycastSourcesVector (array< vector > raycast_sources)
void SetRaycastLength (float length)
override void OnStayFinishServerEvent ()
override protected AreaDamageComponentData GetAreaDamageComponentData (Object object)
protected void ClearCache ()
protected string GetRaycastedHitZone (Object victim)
protected string GetFallbackHitZone (Object victim)
Private Attributes
ref array< vector > m_RaycastSources
vector m_RaycastEndOffset
ref array< ref RaycastRVResult > m_RaycastCache
int m_RaycastCachedIndex
Detailed Description
Newer implementation equivalent of "AreaDamageRegularRaycasted", hitzone selection only.
Definition at line 2 of file AreaDamageComponentRaycasted.c.
Constructor & Destructor Documentation
AreaDamageComponentRaycasted()
void AreaDamageComponentRaycasted (AreaDamageManager parent) inline private
Definition at line 11 of file AreaDamageComponentRaycasted.c.
References m_RaycastCache, m_RaycastCachedIndex, m_RaycastEndOffset, and m_RaycastSources.
Member Function Documentation
ClearCache()
protected void ClearCache () inline private
Definition at line 64 of file AreaDamageComponentRaycasted.c.
References m_RaycastCache, and m_RaycastCachedIndex.
Referenced by OnStayFinishServerEvent(), and OnTriggerCreated().
GetAreaDamageComponentData()
override protected AreaDamageComponentData GetAreaDamageComponentData (Object object) inline private
Definition at line 56 of file AreaDamageComponentRaycasted.c.
References GetRaycastedHitZone(), and AreaDamageComponentData::Hitzone.
GetFallbackHitZone()
protected string GetFallbackHitZone (Object victim) inline private
Definition at line 121 of file AreaDamageComponentRaycasted.c.
References Error(), m_Parent, and Math::RandomIntInclusive().
Referenced by GetRaycastedHitZone().
GetRaycastedHitZone()
protected string GetRaycastedHitZone (Object victim) inline private
Definition at line 70 of file AreaDamageComponentRaycasted.c.
References RaycastRVParams::begPos, RaycastRVResult::component, RaycastRVParams::endPos, RaycastRVParams::flags, GetFallbackHitZone(), m_Parent, m_RaycastCache, m_RaycastCachedIndex, m_RaycastEndOffset, m_RaycastSources, RaycastRVResult::obj, DayZPhysics::RaycastRVProxy(), RaycastRVParams::type, and vector::Zero.
Referenced by GetAreaDamageComponentData().
OnStayFinishServerEvent()
override void OnStayFinishServerEvent () inline private
Definition at line 49 of file AreaDamageComponentRaycasted.c.
References ClearCache().
OnTriggerCreated()
override void OnTriggerCreated () inline private
Definition at line 20 of file AreaDamageComponentRaycasted.c.
References ClearCache().
SetRaycastLength()
void SetRaycastLength (float length) inline private
Definition at line 44 of file AreaDamageComponentRaycasted.c.
References m_RaycastEndOffset, and Vector().
SetRaycastSources()
void SetRaycastSources (array< string > raycast_sources) inline private
Definition at line 27 of file AreaDamageComponentRaycasted.c.
References m_RaycastSources.
Referenced by SetRaycastSources().
SetRaycastSourcesVector()
void SetRaycastSourcesVector (array< vector > raycast_sources) inline private
Definition at line 39 of file AreaDamageComponentRaycasted.c.
References m_RaycastSources.
Referenced by SetRaycastSourcesVector().
Field Documentation
m_RaycastCache
ref array<ref RaycastRVResult> m_RaycastCache private
Definition at line 8 of file AreaDamageComponentRaycasted.c.
Referenced by AreaDamageComponentRaycasted(), ClearCache(), and GetRaycastedHitZone().
m_RaycastCachedIndex
int m_RaycastCachedIndex private
Definition at line 9 of file AreaDamageComponentRaycasted.c.
Referenced by AreaDamageComponentRaycasted(), ClearCache(), and GetRaycastedHitZone().
m_RaycastEndOffset
vector m_RaycastEndOffset private
Definition at line 6 of file AreaDamageComponentRaycasted.c.
Referenced by AreaDamageComponentRaycasted(), GetRaycastedHitZone(), and SetRaycastLength().
m_RaycastSources
ref array<vector> m_RaycastSources private
Definition at line 5 of file AreaDamageComponentRaycasted.c.
Referenced by AreaDamageComponentRaycasted(), GetRaycastedHitZone(), SetRaycastSources(), and SetRaycastSourcesVector().
The documentation for this class was generated from the following file:
4_World/Classes/AreaDamage/AreaDamageNew/DamageComponents/AreaDamageComponentRaycasted.c