DayZ: PluginDayzPlayerDebug_Weapons Class Reference
PluginDayzPlayerDebug_Weapons Class Reference
Private Member Functions
int FindAbilityConfig (int pAction, int pActionT)
void PluginDayzPlayerDebug_Weapons (Widget pMainWnd)
void ~PluginDayzPlayerDebug_Weapons ()
void CreateModuleWidgets ()
void DestroyModuleWidgets ()
void Tick ()
void WeaponsInit (Weapon_Base w)
void WeaponsStartAction ()
bool OnClick (Widget w, int x, int y, int button)
buttons clicks
bool IsWeaponChange (out string pNewWeapon, out int pHideSlot, out int pShowSlot)
void CommandHandler ()
Private Attributes
Widget m_MainWnd
TextListboxWidget m_Selector
ButtonWidget m_ButtonStart
TextWidget m_WidgetActionRunning
TextWidget m_WidgetActionEvents
Weapon_Base m_CurrentWeapon
EditBoxWidget m_SetInitStateI
ButtonWidget m_SetInitStateB
ButtonWidget m_WeaponChange
ButtonWidget m_WeaponHide
EditBoxWidget m_WeaponSlotH
EditBoxWidget m_WeaponSlotS
EditBoxWidget m_WeaponActionProgressStart
EditBoxWidget m_WeaponActionProgressEnd
int m_CH_WeapAction = -1
int m_CH_WeapActionType = -1
int m_CH_LastWeapAction = -1
int m_CH_LastWeapActionType = -1
float m_CH_WeapActionProgressStart = 0
float m_CH_WeapActionProgressEnd = 1
string m_CH_WeaponChangeI
int m_CH_WeaponChangeSlotH = -1
int m_CH_WeaponChangeSlotS = -1
ref array< ref PluginDayzPlayerDebug_AbilityConfig > m_AbilityConfig
Detailed Description
Definition at line 52 of file PluginDayzPlayerDebug_Weapons.c.
Constructor & Destructor Documentation
PluginDayzPlayerDebug_Weapons()
void PluginDayzPlayerDebug_Weapons (Widget pMainWnd) inline private
Definition at line 181 of file PluginDayzPlayerDebug_Weapons.c.
References CreateModuleWidgets(), HumanCommandWeapons::DebugResetEvents(), GetGame(), GetPlayer(), and m_MainWnd.
~PluginDayzPlayerDebug_Weapons()
void ~PluginDayzPlayerDebug_Weapons () inline private
Definition at line 197 of file PluginDayzPlayerDebug_Weapons.c.
References DestroyModuleWidgets().
Member Function Documentation
CommandHandler()
void CommandHandler () inline private
Definition at line 431 of file PluginDayzPlayerDebug_Weapons.c.
References ClearKey(), GetGame(), GetPlayer(), KeyState(), m_CH_LastWeapAction, m_CH_LastWeapActionType, m_CH_WeapAction, m_CH_WeapActionProgressEnd, m_CH_WeapActionProgressStart, m_CH_WeapActionType, Print(), HumanCommandWeapons::SetActionProgressParams(), and HumanCommandWeapons::StartAction().
Referenced by CommandHandler().
CreateModuleWidgets()
void CreateModuleWidgets () inline private
Definition at line 203 of file PluginDayzPlayerDebug_Weapons.c.
References m_ButtonStart, m_MainWnd, m_Selector, m_SetInitStateB, m_SetInitStateI, m_WeaponActionProgressEnd, m_WeaponActionProgressStart, m_WeaponChange, m_WeaponHide, m_WeaponSlotH, m_WeaponSlotS, m_WidgetActionEvents, and m_WidgetActionRunning.
Referenced by PluginDayzPlayerDebug_Weapons().
DestroyModuleWidgets()
void DestroyModuleWidgets () inline private
Definition at line 226 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by ~PluginDayzPlayerDebug_Weapons().
FindAbilityConfig()
int FindAbilityConfig (int pAction, int pActionT) inline private
Definition at line 164 of file PluginDayzPlayerDebug_Weapons.c.
References m_AbilityConfig, m_iAction, and m_iActionT.
Referenced by WeaponsInit().
IsWeaponChange()
bool IsWeaponChange (out string pNewWeapon, out int pHideSlot, out int pShowSlot) inline private
Definition at line 410 of file PluginDayzPlayerDebug_Weapons.c.
References m_CH_WeaponChangeI, m_CH_WeaponChangeSlotH, and m_CH_WeaponChangeSlotS.
Referenced by IsWeaponChange().
OnClick()
bool OnClick (Widget w, int x, int y, int button) inline private
buttons clicks
Definition at line 355 of file PluginDayzPlayerDebug_Weapons.c.
References CALL_ID_SCR_CNSL_GETSELECTEDITEM, Dispatcher::CallMethod(), GetDispatcher(), GetGame(), GetPlayer(), m_ButtonStart, m_CH_WeaponChangeI, m_CH_WeaponChangeSlotH, m_CH_WeaponChangeSlotS, m_SetInitStateB, m_SetInitStateI, m_WeaponChange, m_WeaponHide, m_WeaponSlotH, m_WeaponSlotS, Print(), HumanCommandWeapons::SetInitState(), and WeaponsStartAction().
Tick()
void Tick () inline private
update running action
Definition at line 236 of file PluginDayzPlayerDebug_Weapons.c.
References Class::CastTo(), HumanCommandWeapons::DebugIsEvent(), GetGame(), GetPlayer(), HumanCommandWeapons::GetRunningAction(), HumanCommandWeapons::GetRunningActionType(), m_CurrentWeapon, m_Selector, m_WidgetActionEvents, m_WidgetActionRunning, Print(), string::ToString(), and WeaponsInit().
Referenced by Tick().
WeaponsInit()
void WeaponsInit (Weapon_Base w) inline private
select weapon abilities
Definition at line 294 of file PluginDayzPlayerDebug_Weapons.c.
References FindAbilityConfig(), m_AbilityConfig, AbilityRecord::m_action, AbilityRecord::m_actionType, m_CurrentWeapon, m_iAction, m_iActionT, m_Name, and m_Selector.
Referenced by Tick().
WeaponsStartAction()
void WeaponsStartAction () inline private
Definition at line 329 of file PluginDayzPlayerDebug_Weapons.c.
References PluginDayzPlayerWeaponsDebugUserData::GetAction(), PluginDayzPlayerWeaponsDebugUserData::GetActionType(), m_CH_WeapAction, m_CH_WeapActionProgressEnd, m_CH_WeapActionProgressStart, m_CH_WeapActionType, m_Selector, m_WeaponActionProgressEnd, m_WeaponActionProgressStart, and Print().
Referenced by OnClick().
Field Documentation
m_AbilityConfig
ref array<ref PluginDayzPlayerDebug_AbilityConfig> m_AbilityConfig private
Definition at line 86 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by FindAbilityConfig(), and WeaponsInit().
m_ButtonStart
ButtonWidget m_ButtonStart private
Definition at line 57 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_CH_LastWeapAction
int m_CH_LastWeapAction = -1 private
Definition at line 73 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CommandHandler().
m_CH_LastWeapActionType
int m_CH_LastWeapActionType = -1 private
Definition at line 74 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CommandHandler().
m_CH_WeapAction
int m_CH_WeapAction = -1 private
Definition at line 71 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CommandHandler(), and WeaponsStartAction().
m_CH_WeapActionProgressEnd
float m_CH_WeapActionProgressEnd = 1 private
Definition at line 76 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CommandHandler(), and WeaponsStartAction().
m_CH_WeapActionProgressStart
float m_CH_WeapActionProgressStart = 0 private
Definition at line 75 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CommandHandler(), and WeaponsStartAction().
m_CH_WeapActionType
int m_CH_WeapActionType = -1 private
Definition at line 72 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CommandHandler(), and WeaponsStartAction().
m_CH_WeaponChangeI
string m_CH_WeaponChangeI private
Definition at line 78 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by IsWeaponChange(), and OnClick().
m_CH_WeaponChangeSlotH
int m_CH_WeaponChangeSlotH = -1 private
Definition at line 79 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by IsWeaponChange(), and OnClick().
m_CH_WeaponChangeSlotS
int m_CH_WeaponChangeSlotS = -1 private
Definition at line 80 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by IsWeaponChange(), and OnClick().
m_CurrentWeapon
Weapon_Base m_CurrentWeapon private
Definition at line 60 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by Tick(), and WeaponsInit().
m_MainWnd
Widget m_MainWnd private
Definition at line 54 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and PluginDayzPlayerDebug_Weapons().
m_Selector
TextListboxWidget m_Selector private
Definition at line 56 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), Tick(), WeaponsInit(), and WeaponsStartAction().
m_SetInitStateB
ButtonWidget m_SetInitStateB private
Definition at line 62 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_SetInitStateI
EditBoxWidget m_SetInitStateI private
Definition at line 61 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_WeaponActionProgressEnd
EditBoxWidget m_WeaponActionProgressEnd private
Definition at line 68 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and WeaponsStartAction().
m_WeaponActionProgressStart
EditBoxWidget m_WeaponActionProgressStart private
Definition at line 67 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and WeaponsStartAction().
m_WeaponChange
ButtonWidget m_WeaponChange private
Definition at line 63 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_WeaponHide
ButtonWidget m_WeaponHide private
Definition at line 64 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_WeaponSlotH
EditBoxWidget m_WeaponSlotH private
Definition at line 65 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_WeaponSlotS
EditBoxWidget m_WeaponSlotS private
Definition at line 66 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_WidgetActionEvents
TextWidget m_WidgetActionEvents private
Definition at line 59 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and Tick().
m_WidgetActionRunning
TextWidget m_WidgetActionRunning private
Definition at line 58 of file PluginDayzPlayerDebug_Weapons.c.
Referenced by CreateModuleWidgets(), and Tick().
The documentation for this class was generated from the following file:
4_World/Plugins/PluginBase/PluginDayzPlayerDebug_Weapons.c