DayZ: HumanInventory Class Reference
HumanInventory Class Reference
inventory for plain man/human
Private Member Functions
proto native EntityAI GetEntityInHands ()
proto native bool CanAddEntityInHands (EntityAI e)
alternative for TestAddEntityInHands(e, true, true, true);
proto native bool TestAddEntityInHands (EntityAI e, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check)
proto native bool CanRemoveEntityInHands ()
proto native bool CanOpenInventory ()
proto native EntityAI CreateInHands (string typeName)
creates new entity in hands
proto native int GetUserReservedLocationCount ()
proto native int FindUserReservedLocationIndex (notnull EntityAI e)
proto native int FindCollidingUserReservedLocationIndex (notnull EntityAI e, notnull InventoryLocation dst)
proto native void GetUserReservedLocation (int index, out notnull InventoryLocation dst)
proto native int FindFirstUserReservedLocationIndexForContainer (notnull EntityAI e)
proto native void SetUserReservedLocation (notnull EntityAI eai, notnull InventoryLocation dst)
proto native void ClearUserReservedLocation (notnull EntityAI eai)
proto native bool ClearUserReservedLocationAtIndex (int index)
proto native void ClearUserReservedLocationForContainer (notnull EntityAI eai)
proto native bool GetDebugFlag ()
override EntityAI CreateInInventory (string type)
creates entity somewhere in inventory
void ClearUserReservedLocationSynced (notnull EntityAI eai)
void ClearUserReservedLocationAtIndexSynced (int index)
Man GetManOwner ()
bool HasEntityInHands (EntityAI e)
bool ProcessHandEvent (HandEventBase e)
void OnHandsStateChanged (HandStateBase src, HandStateBase dst)
void OnHandsExitedStableState (HandStateBase src, HandStateBase dst)
void OnHandsEnteredStableState (HandStateBase src, HandStateBase dst)
void OnEntityInHandsCreated (InventoryLocation src)
void OnEntityInHandsDestroyed (InventoryLocation src)
bool HandEvent (InventoryMode mode, HandEventBase e)
override bool DropEntity (InventoryMode mode, EntityAI owner, notnull EntityAI item)
bool ThrowEntity (EntityAI item, vector dir, float force)
bool RedirectToHandEvent (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
override bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
override bool TakeEntityToInventory (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item)
override bool TakeEntityToCargoEx (InventoryMode mode, notnull EntityAI item, int idx, int row, int col)
Put item into into cargo on specific cargo location.
override bool TakeEntityAsAttachmentEx (InventoryMode mode, notnull EntityAI item, int slot)
override bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
override bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
override bool LocalDestroyEntity (notnull EntityAI item)
override bool ReplaceItemWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
bool ReplaceItemElsewhereWithNewInHands (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
protected bool ReplaceItemInElsewhereWithNewinHandsImpl (InventoryMode mode, HandEventBase e)
protected bool ReplaceItemInHandsWithNewImpl (InventoryMode mode, HandEventBase e)
bool ReplaceItemInHandsWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
bool ReplaceItemInHandsWithNewElsewhere (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
bool SwappingToPreviousLocation (EntityAI item1, EntityAI item2, out InventoryLocation dst)
void HandleInventoryManipulation ()
void Update (float delta_time)
bool ProccessInputData (int type, bool handling_juncture, bool remote, ParamsReadContext ctx)
Private Attributes
int m_syncClearUserReservationindex = -1
Detailed Description
inventory for plain man/human
HumanInventory has simple synchronous operations only, i.e. no animations are involved while adding/removing/swapping to/from hands.
Animations are added on higher level of hierarchy (DayZPlayerInventory for example)
Definition at line 9 of file HumanInventory.c.
Member Function Documentation
CanAddEntityInHands()
CanAddEntityInHands (EntityAI e) private
alternative for TestAddEntityInHands(e, true, true, true);
CanOpenInventory()
proto native bool CanOpenInventory () private
CanRemoveEntityInHands()
CanRemoveEntityInHands () private
Returns
true if entity can be removed from hands
ClearUserReservedLocation()
proto native void ClearUserReservedLocation (notnull EntityAI eai) private
Referenced by ClearUserReservedLocationSynced().
ClearUserReservedLocationAtIndex()
proto native bool ClearUserReservedLocationAtIndex (int index) private
Referenced by ClearUserReservedLocationAtIndexSynced(), ProccessInputData(), RedirectToHandEvent(), and Update().
ClearUserReservedLocationAtIndexSynced()
void ClearUserReservedLocationAtIndexSynced (int index) inline private
Definition at line 85 of file HumanInventory.c.
References ClearUserReservedLocationAtIndex(), GetGame(), InventoryLocation::GetItem(), GetUserReservedLocation(), and m_syncClearUserReservationindex.
ClearUserReservedLocationForContainer()
proto native void ClearUserReservedLocationForContainer (notnull EntityAI eai) private
ClearUserReservedLocationSynced()
void ClearUserReservedLocationSynced (notnull EntityAI eai) inline private
Definition at line 73 of file HumanInventory.c.
References ClearUserReservedLocation(), FindUserReservedLocationIndex(), GetGame(), and m_syncClearUserReservationindex.
CreateInHands()
CreateInHands (string typeName) private
creates new entity in hands
Parameters
[in] typeName type name of the entity to be created
Returns
new entity or null otherwise
Referenced by CreateInInventory(), CTObjectFollower::SetHandsItem(), and ActionUncoverHeadBase::UncoverHead().
CreateInInventory()
CreateInInventory (string type) inline private
creates entity somewhere in inventory
Parameters
[in] type item type to be placed in inventory
Returns
created entity
Definition at line 65 of file HumanInventory.c.
References CreateInHands().
DropEntity()
override bool DropEntity (InventoryMode mode, EntityAI owner, notnull EntityAI item) inline private
Definition at line 133 of file HumanInventory.c.
References Error(), GetManOwner(), InventoryLocation::GetType(), HandEvent(), and hndDebugPrint().
Referenced by EntityAI::DropEntityImpl(), and ThrowEntity().
FindCollidingUserReservedLocationIndex()
proto native int FindCollidingUserReservedLocationIndex (notnull EntityAI e, notnull InventoryLocation dst) private
FindFirstUserReservedLocationIndexForContainer()
proto native int FindFirstUserReservedLocationIndexForContainer (notnull EntityAI e) private
FindUserReservedLocationIndex()
proto native int FindUserReservedLocationIndex (notnull EntityAI e) private
Referenced by ClearUserReservedLocationSynced(), and RedirectToHandEvent().
ForceSwapEntities()
override bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline private
returns item to previous location, if available
Definition at line 366 of file HumanInventory.c.
References InventoryLocation::DumpToStringNullSafe(), Error(), GetManOwner(), InventoryLocation::GetType(), HandEvent(), hndDebugPrint(), GameInventory::MakeSrcAndDstForForceSwap(), HandEventBase::ReserveInventory(), and SwappingToPreviousLocation().
Referenced by EntityAI::ForceSwapEntitiesImpl().
GetDebugFlag()
proto native bool GetDebugFlag () private
GetEntityInHands()
GetEntityInHands () private
Returns
entity in hands
Referenced by HandActionBase::Action(), InventoryItem::GetRecipesActions(), HasEntityInHands(), BotWaitForChangeInHands::OnEntry(), HandStateBase::OnEntry(), AnalyticsManagerClient::OnItemAttachedAtPlayer(), BotStateBase::OnUpdate(), EntityAI::PredictiveMoveItemFromHandsToInventory(), ReplaceItemInElsewhereWithNewinHandsImpl(), ReplaceItemInHandsWithNewImpl(), ReplaceItemWithNew(), and EntityAI::TakeEntityToHandsImpl().
GetManOwner()
Man GetManOwner () inline private
Definition at line 102 of file HumanInventory.c.
References GameInventory::GetInventoryOwner().
Referenced by HumanInventoryWithFSM::CreateStableStates(), DropEntity(), ForceSwapEntities(), HumanInventoryWithFSM::Init(), LocalDestroyEntity(), OnEntityInHandsCreated(), OnEntityInHandsDestroyed(), HumanInventoryWithFSM::ProcessHandAbortEvent(), HumanInventoryWithFSM::ProcessHandEvent(), ReplaceItemElsewhereWithNewInHands(), ReplaceItemInHandsWithNew(), ReplaceItemInHandsWithNewElsewhere(), SwapEntities(), TakeEntityAsAttachmentEx(), TakeEntityToCargoEx(), TakeToDst(), and ThrowEntity().
GetUserReservedLocation()
proto native void GetUserReservedLocation (int index, out notnull InventoryLocation dst) private
Referenced by ClearUserReservedLocationAtIndexSynced(), RedirectToHandEvent(), and Update().
GetUserReservedLocationCount()
proto native int GetUserReservedLocationCount () private
HandEvent()
bool HandEvent (InventoryMode mode, HandEventBase e) inline private
Definition at line 128 of file HumanInventory.c.
Referenced by DropEntity(), ForceSwapEntities(), LocalDestroyEntity(), RedirectToHandEvent(), ReplaceItemInElsewhereWithNewinHandsImpl(), ReplaceItemInHandsWithNewImpl(), SwapEntities(), TakeEntityAsAttachmentEx(), TakeEntityToCargoEx(), and ThrowEntity().
HandleInventoryManipulation()
void HandleInventoryManipulation () inline private
Definition at line 579 of file HumanInventory.c.
Referenced by Update().
HasEntityInHands()
bool HasEntityInHands (EntityAI e) inline private
Definition at line 104 of file HumanInventory.c.
References GetEntityInHands().
LocalDestroyEntity()
override bool LocalDestroyEntity (notnull EntityAI item) inline private
Definition at line 420 of file HumanInventory.c.
References Error(), GameInventory::GetInventoryOwner(), GetManOwner(), InventoryLocation::GetType(), HandEvent(), hndDebugPrint(), and IsAlive().
Referenced by EntityAI::LocalDestroyEntityInHands(), and CTObjectFollower::SetHandsItem().
OnEntityInHandsCreated()
void OnEntityInHandsCreated (InventoryLocation src) inline private
Definition at line 112 of file HumanInventory.c.
References InventoryLocation::Copy(), InventoryLocation::DumpToStringNullSafe(), GetManOwner(), hndDebugPrint(), and ProcessHandEvent().
OnEntityInHandsDestroyed()
void OnEntityInHandsDestroyed (InventoryLocation src) inline private
Definition at line 120 of file HumanInventory.c.
References InventoryLocation::Copy(), InventoryLocation::DumpToStringNullSafe(), GetManOwner(), hndDebugPrint(), and ProcessHandEvent().
OnHandsEnteredStableState()
void OnHandsEnteredStableState (HandStateBase src, HandStateBase dst) inline private
Definition at line 110 of file HumanInventory.c.
OnHandsExitedStableState()
void OnHandsExitedStableState (HandStateBase src, HandStateBase dst) inline private
Definition at line 109 of file HumanInventory.c.
OnHandsStateChanged()
void OnHandsStateChanged (HandStateBase src, HandStateBase dst) inline private
Definition at line 108 of file HumanInventory.c.
ProccessInputData()
bool ProccessInputData (int type, bool handling_juncture, bool remote, ParamsReadContext ctx) inline private
Definition at line 611 of file HumanInventory.c.
References ClearUserReservedLocationAtIndex(), and Serializer::Read().
ProcessHandEvent()
bool ProcessHandEvent (HandEventBase e) inline private
Definition at line 106 of file HumanInventory.c.
Referenced by OnEntityInHandsCreated(), and OnEntityInHandsDestroyed().
RedirectToHandEvent()
bool RedirectToHandEvent (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst) inline private
Definition at line 185 of file HumanInventory.c.
References ClearUserReservedLocationAtIndex(), FindUserReservedLocationIndex(), EntityAI::GetHumanInventory(), InventoryLocation::GetParent(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), GetUserReservedLocation(), HandEvent(), and hndDebugPrint().
Referenced by TakeEntityToInventory(), and TakeToDst().
ReplaceItemElsewhereWithNewInHands()
bool ReplaceItemElsewhereWithNewInHands (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline private
Definition at line 452 of file HumanInventory.c.
References GetManOwner(), and ReplaceItemInElsewhereWithNewinHandsImpl().
Referenced by EntityAI::ReplaceItemElsewhereWithNewInHandsImpl().
ReplaceItemInElsewhereWithNewinHandsImpl()
protected bool ReplaceItemInElsewhereWithNewinHandsImpl (InventoryMode mode, HandEventBase e) inline private
Definition at line 457 of file HumanInventory.c.
References HandEventBase::DumpToString(), Error(), HandEventBase::GetDst(), GetEntityInHands(), GameInventory::GetInventoryOwner(), GetName(), InventoryLocation::GetType(), HandEvent(), hndDebugPrint(), and IsAlive().
Referenced by ReplaceItemElsewhereWithNewInHands().
ReplaceItemInHandsWithNew()
bool ReplaceItemInHandsWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline private
Definition at line 523 of file HumanInventory.c.
References GetManOwner(), and ReplaceItemInHandsWithNewImpl().
Referenced by EntityAI::ReplaceItemInHandsWithNewImpl(), and ReplaceItemWithNew().
ReplaceItemInHandsWithNewElsewhere()
bool ReplaceItemInHandsWithNewElsewhere (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline private
Definition at line 528 of file HumanInventory.c.
References GetManOwner(), and ReplaceItemInHandsWithNewImpl().
Referenced by EntityAI::ReplaceItemInHandsWithNewElsewhereImpl().
ReplaceItemInHandsWithNewImpl()
protected bool ReplaceItemInHandsWithNewImpl (InventoryMode mode, HandEventBase e) inline private
Definition at line 492 of file HumanInventory.c.
References HandEventBase::DumpToString(), Error(), GetEntityInHands(), GameInventory::GetInventoryOwner(), GetName(), InventoryLocation::GetType(), HandEvent(), hndDebugPrint(), and IsAlive().
Referenced by ReplaceItemInHandsWithNew(), and ReplaceItemInHandsWithNewElsewhere().
ReplaceItemWithNew()
override bool ReplaceItemWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline private
Definition at line 444 of file HumanInventory.c.
References GetEntityInHands(), ReplaceItemWithNewLambdaBase::m_OldItem, and ReplaceItemInHandsWithNew().
Referenced by EntityAI::ReplaceItemWithNewImpl().
SetUserReservedLocation()
proto native void SetUserReservedLocation (notnull EntityAI eai, notnull InventoryLocation dst) private
SwapEntities()
override bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2) inline private
returns item to previous location, if available
Definition at line 320 of file HumanInventory.c.
References InventoryLocation::DumpToStringNullSafe(), Error(), GetManOwner(), InventoryLocation::GetType(), HandEvent(), hndDebugPrint(), GameInventory::MakeSrcAndDstForSwap(), and SwappingToPreviousLocation().
Referenced by EntityAI::SwapEntitiesImpl().
SwappingToPreviousLocation()
bool SwappingToPreviousLocation (EntityAI item1, EntityAI item2, out InventoryLocation dst) inline private
Definition at line 533 of file HumanInventory.c.
References GameInventory::CanSwapEntitiesEx(), InventoryLocation::Copy(), InventoryLocation::GetSlot(), and InventoryLocation::GetType().
Referenced by ForceSwapEntities(), and SwapEntities().
TakeEntityAsAttachmentEx()
override bool TakeEntityAsAttachmentEx (InventoryMode mode, notnull EntityAI item, int slot) inline private
Definition at line 292 of file HumanInventory.c.
References Error(), GameInventory::GetInventoryOwner(), GetManOwner(), InventoryLocation::GetType(), HandEvent(), hndDebugPrint(), IsAlive(), and InventoryLocation::SetAttachment().
Referenced by EntityAI::TakeEntityAsAttachmentExImpl().
TakeEntityToCargoEx()
override bool TakeEntityToCargoEx (InventoryMode mode, notnull EntityAI item, int idx, int row, int col) inline private
Put item into into cargo on specific cargo location.
Definition at line 265 of file HumanInventory.c.
References Error(), GameInventory::GetInventoryOwner(), GetManOwner(), InventoryLocation::GetType(), HandEvent(), hndDebugPrint(), IsAlive(), and InventoryLocation::SetCargo().
TakeEntityToInventory()
override bool TakeEntityToInventory (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item) inline private
Definition at line 238 of file HumanInventory.c.
References Error(), GameInventory::FindFreeLocationFor(), hndDebugPrint(), and RedirectToHandEvent().
Referenced by EntityAI::PredictiveMoveItemFromHandsToInventory(), and EntityAI::TakeEntityToInventoryImpl().
TakeToDst()
override bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst) inline private
Definition at line 228 of file HumanInventory.c.
References InventoryLocation::DumpToStringNullSafe(), GetManOwner(), hndDebugPrint(), IsAlive(), and RedirectToHandEvent().
Referenced by EntityAI::TakeEntityToHandsImpl(), and EntityAI::TakeToDstImpl().
TestAddEntityInHands()
TestAddEntityInHands (EntityAI e, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check) private
Parameters
[in] e entity to test for taking in hands
[in] do_item_check deny if entity is not InventoryItem
[in] do_occupancy_test deny if there is item in hands already
[in] do_script_check deny if script conditions fail
Returns
true if item passed all tests
ThrowEntity()
bool ThrowEntity (EntityAI item, vector dir, float force) inline private
Definition at line 152 of file HumanInventory.c.
References DropEntity(), Error(), GetGame(), GetManOwner(), InventoryLocation::GetType(), HandEvent(), and hndDebugPrint().
Update()
void Update (float delta_time) inline private
Definition at line 582 of file HumanInventory.c.
References ScriptInputUserData::CanStoreInputUserData(), ClearUserReservedLocationAtIndex(), InventoryLocation::GetItem(), GetUserReservedLocation(), HandleInventoryManipulation(), INPUT_UDT_INVENTORY, m_syncClearUserReservationindex, ScriptInputUserData::Send(), and Serializer::Write().
Field Documentation
m_syncClearUserReservationindex
int m_syncClearUserReservationindex = -1 private
Definition at line 11 of file HumanInventory.c.
Referenced by ClearUserReservedLocationAtIndexSynced(), ClearUserReservedLocationSynced(), and Update().
The documentation for this class was generated from the following file:
3_Game/Systems/Inventory/HumanInventory.c