DayZ Scripts Documentation: ConstructionActionData Class Reference
ConstructionActionData Class Reference
Private Member Functions
void ConstructionActionData ()
string GetMainPartName ()
string GetMainPartNameNoTool ()
void SetTarget (Object target)
Object GetTarget ()
void SetTargetPart (ConstructionPart target_part)
ConstructionPart GetTargetPart ()
void SetSlotId (int slot_id)
int GetSlotId ()
void SetActionInitiator (PlayerBase action_initiator)
PlayerBase GetActionInitiator ()
void SetNextIndex ()
void RefreshPartsToBuild (string main_part_name, ItemBase tool, bool use_tool=true)
void OnUpdateActions (Object item, Object target, int component_index)
void OnUpdateActionsNoTool (Object item, Object target, int component_index)
int GetConstructionPartsCount ()
ConstructionPart GetCurrentBuildPart ()
ConstructionPart GetBuildPartAtIndex (int idx)
ConstructionPart GetBuildPartNoToolAtIndex (int idx)
CombinationLock GetCombinationLock ()
void SetCombinationLock (CombinationLock combination_lock)
string GetDialNumberText ()
int GetAttachmentSlotFromSelection (PlayerBase player, EntityAI target, ItemBase item_to_attach, string selection)
void GetAttachmentsFromSelection (EntityAI target, string selection, out array< EntityAI > attachments)
void CombineItems (ItemBase target, ItemBase item)
void RefreshAttachmentsToDetach (EntityAI target, string main_part_name)
void SetNextAttachmentIndex ()
int GetAttachmentsToDetachCount ()
EntityAI GetActualAttachmentToDetach ()
void ResetActionIndexes ()
Private Attributes
Object m_Target
ref array< ConstructionPart > m_BuildParts
ref array< ConstructionPart > m_BuildPartsNoTool
int m_PartIndex
string m_MainPartName
string m_MainPartNameNoTool
ref ConstructionPart m_TargetPart
CombinationLock m_CombinationLock
int m_SlotId
PlayerBase m_ActionInitiator
ref array< EntityAI > m_Attachments
protected ActionVariantManager m_ActionVariantManager
protected ActionVariantManager m_ActionNoToolVariantManager
int m_AttachmentsIndex
Detailed Description
Definition at line 1 of file ConstructionActionData.c.
Constructor & Destructor Documentation
ConstructionActionData()
void ConstructionActionData () inline private
Definition at line 28 of file ConstructionActionData.c.
References ScriptInvoker::Clear(), GetGame(), ActionVariantManager::GetOnUpdateInvoker(), ActionManagerClient::GetVariantManager(), ScriptInvoker::Insert(), m_ActionNoToolVariantManager, m_ActionVariantManager, m_Attachments, m_AttachmentsIndex, m_BuildParts, m_BuildPartsNoTool, m_PartIndex, OnUpdateActions(), and OnUpdateActionsNoTool().
Member Function Documentation
CombineItems()
void CombineItems (ItemBase target, ItemBase item) inline private
Definition at line 322 of file ConstructionActionData.c.
GetActionInitiator()
PlayerBase GetActionInitiator () inline private
Definition at line 97 of file ConstructionActionData.c.
References m_ActionInitiator.
Referenced by BaseBuildingBase::CanReceiveAttachment().
GetActualAttachmentToDetach()
EntityAI GetActualAttachmentToDetach () inline private
Definition at line 364 of file ConstructionActionData.c.
References Math::Clamp(), GetAttachmentsToDetachCount(), m_Attachments, and m_AttachmentsIndex.
Referenced by ActionTakeMaterialToHands::ActionCondition(), ActionTakeMaterialToHands::CreateAndSetupActionCallback(), ActionTakeMaterialToHands::OnActionInfoUpdate(), and ActionTakeMaterialToHands::OnExecuteImpl().
GetAttachmentsFromSelection()
void GetAttachmentsFromSelection (EntityAI target, string selection, out array< EntityAI > attachments) inline private
Definition at line 284 of file ConstructionActionData.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), and InventorySlots::GetSlotIdFromString().
Referenced by RefreshAttachmentsToDetach().
GetAttachmentSlotFromSelection()
int GetAttachmentSlotFromSelection (PlayerBase player, EntityAI target, ItemBase item_to_attach, string selection) inline private
Definition at line 234 of file ConstructionActionData.c.
References ItemBase::CanBeCombined(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), and InventorySlots::GetSlotIdFromString().
Referenced by ActionAttachToConstruction::ActionCondition().
GetAttachmentsToDetachCount()
int GetAttachmentsToDetachCount () inline private
Definition at line 359 of file ConstructionActionData.c.
References m_Attachments.
Referenced by ActionTakeMaterialToHandsSwitch::ActionCondition(), GetActualAttachmentToDetach(), and SetNextAttachmentIndex().
GetBuildPartAtIndex()
ConstructionPart GetBuildPartAtIndex (int idx) inline private
Definition at line 168 of file ConstructionActionData.c.
References m_BuildParts.
Referenced by BuildCondition(), ComplexBuildCollideCheckClient(), ActionBuildPart::OnActionInfoUpdate(), and ActionBuildPart::SetupAction().
GetBuildPartNoToolAtIndex()
ConstructionPart GetBuildPartNoToolAtIndex (int idx) inline private
Definition at line 177 of file ConstructionActionData.c.
References m_BuildPartsNoTool.
Referenced by BuildCondition(), ComplexBuildCollideCheckClient(), ActionBuildShelter::DetermineConstructionSounds(), ActionBuildShelter::GetText(), ActionBuildShelter::OnActionInfoUpdate(), and ActionBuildShelter::SetupAction().
GetCombinationLock()
CombinationLock GetCombinationLock () inline private
Definition at line 189 of file ConstructionActionData.c.
References m_CombinationLock.
Referenced by OnFinishProgressServer(), and ActionNextCombinationLockDialOnTarget::Start().
GetConstructionPartsCount()
int GetConstructionPartsCount () inline private
Definition at line 157 of file ConstructionActionData.c.
References m_BuildParts.
GetCurrentBuildPart()
ConstructionPart GetCurrentBuildPart () inline private
Definition at line 163 of file ConstructionActionData.c.
GetDialNumberText()
string GetDialNumberText () inline private
Definition at line 199 of file ConstructionActionData.c.
References string::Format(), string::Get(), string::Length(), and m_CombinationLock.
Referenced by OnActionInfoUpdate().
GetMainPartName()
string GetMainPartName () inline private
Definition at line 52 of file ConstructionActionData.c.
References m_MainPartName.
GetMainPartNameNoTool()
string GetMainPartNameNoTool () inline private
Definition at line 57 of file ConstructionActionData.c.
References m_MainPartNameNoTool.
GetSlotId()
int GetSlotId () inline private
Definition at line 87 of file ConstructionActionData.c.
References m_SlotId.
Referenced by ActionAttachToConstruction::OnExecuteImpl().
GetTarget()
Object GetTarget () inline private
Definition at line 67 of file ConstructionActionData.c.
References m_Target.
GetTargetPart()
ConstructionPart GetTargetPart () inline private
Definition at line 77 of file ConstructionActionData.c.
References m_TargetPart.
Referenced by ActionDismantlePart::GetAdminLogMessage(), ActionDismantlePart::GetText(), ActionRepairPart::GetText(), ActionDestroyPart::OnActionInfoUpdate(), ActionDismantlePart::OnActionInfoUpdate(), ActionRepairPart::OnActionInfoUpdate(), ActionDestroyPart::OnFinishProgressServer(), and ActionDismantlePart::OnFinishProgressServer().
OnUpdateActions()
void OnUpdateActions (Object item, Object target, int component_index) inline private
Definition at line 113 of file ConstructionActionData.c.
References ActionVariantManager::Clear(), m_ActionVariantManager, m_BuildParts, m_MainPartName, and ActionVariantManager::SetActionVariantCount().
Referenced by ConstructionActionData().
OnUpdateActionsNoTool()
void OnUpdateActionsNoTool (Object item, Object target, int component_index) inline private
Definition at line 141 of file ConstructionActionData.c.
References ActionVariantManager::Clear(), m_ActionNoToolVariantManager, m_BuildPartsNoTool, m_MainPartNameNoTool, and ActionVariantManager::SetActionVariantCount().
Referenced by ConstructionActionData().
RefreshAttachmentsToDetach()
void RefreshAttachmentsToDetach (EntityAI target, string main_part_name) inline private
Definition at line 335 of file ConstructionActionData.c.
References GetAttachmentsFromSelection(), and m_Attachments.
Referenced by ActionTakeMaterialToHands::ActionCondition(), and ActionTakeMaterialToHandsSwitch::ActionCondition().
RefreshPartsToBuild()
void RefreshPartsToBuild (string main_part_name, ItemBase tool, bool use_tool = true) inline private
Definition at line 108 of file ConstructionActionData.c.
ResetActionIndexes()
void ResetActionIndexes () inline private
Definition at line 382 of file ConstructionActionData.c.
References m_AttachmentsIndex, and m_PartIndex.
SetActionInitiator()
void SetActionInitiator (PlayerBase action_initiator) inline private
Definition at line 92 of file ConstructionActionData.c.
References m_ActionInitiator.
Referenced by BaseBuildingBase::CanReceiveAttachment(), and ActionAttachToConstruction::OnStartClient().
SetCombinationLock()
void SetCombinationLock (CombinationLock combination_lock) inline private
Definition at line 194 of file ConstructionActionData.c.
References m_CombinationLock.
Referenced by ActionCondition(), ActionNextCombinationLockDialOnTarget::ActionCondition(), and ActionNextCombinationLockDial::ActionCondition().
SetNextAttachmentIndex()
void SetNextAttachmentIndex () inline private
Definition at line 340 of file ConstructionActionData.c.
References GetAttachmentsToDetachCount(), and m_AttachmentsIndex.
Referenced by ActionTakeMaterialToHandsSwitch::Start().
SetNextIndex()
void SetNextIndex () inline private
Definition at line 103 of file ConstructionActionData.c.
Referenced by ActionHandsPartSwitch::SetNextIndex(), and ActionBuildPartSwitch::SetNextIndex().
SetSlotId()
void SetSlotId (int slot_id) inline private
Definition at line 82 of file ConstructionActionData.c.
References m_SlotId.
Referenced by ActionAttachToConstruction::ActionCondition().
SetTarget()
void SetTarget (Object target) inline private
Definition at line 62 of file ConstructionActionData.c.
References m_Target.
Referenced by BuildCondition().
SetTargetPart()
void SetTargetPart (ConstructionPart target_part) inline private
Definition at line 72 of file ConstructionActionData.c.
References m_TargetPart.
Referenced by ActionDestroyPart::DestroyCondition(), ActionDismantlePart::DismantleCondition(), and ActionRepairPart::RepairCondition().
Field Documentation
m_ActionInitiator
PlayerBase m_ActionInitiator private
Definition at line 19 of file ConstructionActionData.c.
Referenced by GetActionInitiator(), and SetActionInitiator().
m_ActionNoToolVariantManager
protected ActionVariantManager m_ActionNoToolVariantManager private
Definition at line 24 of file ConstructionActionData.c.
Referenced by ConstructionActionData(), and OnUpdateActionsNoTool().
m_ActionVariantManager
protected ActionVariantManager m_ActionVariantManager private
Definition at line 23 of file ConstructionActionData.c.
Referenced by ConstructionActionData(), and OnUpdateActions().
m_Attachments
ref array<EntityAI> m_Attachments private
Definition at line 21 of file ConstructionActionData.c.
Referenced by ConstructionActionData(), GetActualAttachmentToDetach(), GetAttachmentsToDetachCount(), and RefreshAttachmentsToDetach().
m_AttachmentsIndex
int m_AttachmentsIndex private
Definition at line 26 of file ConstructionActionData.c.
Referenced by ConstructionActionData(), GetActualAttachmentToDetach(), ResetActionIndexes(), and SetNextAttachmentIndex().
m_BuildParts
ref array<ConstructionPart> m_BuildParts private
Definition at line 6 of file ConstructionActionData.c.
Referenced by ConstructionActionData(), GetBuildPartAtIndex(), GetConstructionPartsCount(), and OnUpdateActions().
m_BuildPartsNoTool
ref array<ConstructionPart> m_BuildPartsNoTool private
Definition at line 7 of file ConstructionActionData.c.
Referenced by ConstructionActionData(), GetBuildPartNoToolAtIndex(), and OnUpdateActionsNoTool().
m_CombinationLock
CombinationLock m_CombinationLock private
Definition at line 15 of file ConstructionActionData.c.
Referenced by GetCombinationLock(), GetDialNumberText(), and SetCombinationLock().
m_MainPartName
string m_MainPartName private
Definition at line 10 of file ConstructionActionData.c.
Referenced by GetMainPartName(), and OnUpdateActions().
m_MainPartNameNoTool
string m_MainPartNameNoTool private
Definition at line 11 of file ConstructionActionData.c.
Referenced by GetMainPartNameNoTool(), and OnUpdateActionsNoTool().
m_PartIndex
int m_PartIndex private
Definition at line 9 of file ConstructionActionData.c.
Referenced by ConstructionActionData(), and ResetActionIndexes().
m_SlotId
int m_SlotId private
Definition at line 18 of file ConstructionActionData.c.
Referenced by GetSlotId(), and SetSlotId().
m_Target
Object m_Target private
Definition at line 3 of file ConstructionActionData.c.
Referenced by GetTarget(), and SetTarget().
m_TargetPart
ref ConstructionPart m_TargetPart private
Definition at line 12 of file ConstructionActionData.c.
Referenced by GetTargetPart(), and SetTargetPart().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/BaseBuilding/ConstructionActionData.c