DayZ Scripts: BaseBuildingBase Class Reference
BaseBuildingBase Class Reference
Private Member Functions
void Fence ()
override string GetConstructionKitType ()
override int GetMeleeTargetType ()
bool HasHinges ()
bool HasFullyConstructedGate ()
void SetGateState (int state)
int GetGateState ()
int CheckGateState ()
void SetOpenedState (bool state)
override bool IsOpened ()
bool IsLocked ()
override bool NameOverride (out string output)
CombinationLock GetCombinationLock ()
CamoNet GetCamoNet ()
BarbedWire GetBarbedWire1 ()
BarbedWire GetBarbedWire2 ()
override vector GetKitSpawnPosition ()
override bool CanDisplayAttachmentSlot (int slot_id)
override bool CanDisplayAttachmentCategory (string category_name)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
override void OnVariablesSynchronized ()
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanPutIntoHands (EntityAI parent)
override bool CanBeRepairedToPristine ()
bool CanOpenFence ()
bool CanCloseFence ()
void OpenFence ()
void CloseFence ()
protected void CheckFenceOpened ()
protected void CheckFenceClosed ()
override void CreateAreaDamage (string slot_name, float rotation_angle=0)
void UpdateBarbedWireAreaDamagePos (float rotation_angle=0, bool to_delete=false)
override void PostAreaDamageActions ()
override bool IsPlayerInside (PlayerBase player, string selection)
override bool IsFacingPlayer (PlayerBase player, string selection)
override bool IsFacingCamera (string selection)
override bool HasProperDistance (string selection, PlayerBase player)
override bool CanUseConstructionBuild ()
protected void SoundGateOpenStart ()
protected void SoundGateCloseStart ()
protected void SoundGateCloseEnd ()
void GateAttachmentsSanityCheck ()
void HandleDropAttachment (ItemBase item)
bool GateAttachmentConditions (int slotId)
override bool TranslateSlotFromSelection (string selection_name, out int slot_id)
override void SetActions ()
override array< string > OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
override void OnDebugSpawn ()
void ShelterSite ()
override string GetConstructionKitType ()
override int GetMeleeTargetType ()
override vector GetKitSpawnPosition ()
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
override bool CanPutIntoHands (EntityAI parent)
override bool CanBeRepairedToPristine ()
override bool CanUseHandConstruction ()
override bool MustBeBuiltFromOutside ()
override bool IsFacingCamera (string selection)
override bool IsPlayerInside (PlayerBase player, string selection)
override bool HasProperDistance (string selection, PlayerBase player)
override void SetActions ()
void TerritoryFlag ()
void ~TerritoryFlag ()
void InitRefresherData ()
override string GetConstructionKitType ()
override int GetMeleeTargetType ()
override vector GetKitSpawnPosition ()
override bool CanDisplayAttachmentCategory (string category_name)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
override void OnCEUpdate ()
void HandleRefreshers ()
Client-side, saves positions of active lifetime refreshers to MissionGameplay.
void SetRefresherActive (bool state)
void InsertRefresherPosition ()
void RemoveRefresherPosition (int idx=-2)
override void OnVariablesSynchronized ()
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanPutIntoHands (EntityAI parent)
override bool CanBeRepairedToPristine ()
override bool IsPlayerInside (PlayerBase player, string selection)
override bool IsFacingPlayer (PlayerBase player, string selection)
override bool IsFacingCamera (string selection)
override bool HasProperDistance (string selection, PlayerBase player)
override void SetActions ()
void AnimateFlag (float delta)
void SetRefreshTimer01 (float fraction)
void AddRefresherTime01 (float fraction)
float GetRefresherTime01 ()
void CheckLoadedVariables (int max_duration)
override void OnDebugSpawn ()
void Watchtower ()
override string GetConstructionKitType ()
override int GetMeleeTargetType ()
override void UpdateVisuals ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanPutIntoHands (EntityAI parent)
override bool CanBeRepairedToPristine ()
override bool PerformRoofCheckForBase (string partName, PlayerBase player, out bool result)
override bool CanDisplayAttachmentSlot (int slot_id)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CheckSlotVerticalDistance (int slot_id, PlayerBase player)
override bool CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player)
override bool CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player)
override void AfterStoreLoad ()
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
override bool IsFacingPlayer (PlayerBase player, string selection)
override bool IsFacingCamera (string selection)
override bool IsPlayerInside (PlayerBase player, string selection)
override bool HasProperDistance (string selection, PlayerBase player)
override void SetActions ()
override array< string > OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
override void OnDebugSpawn ()
Private Attributes
const int GATE_STATE_NONE = 0
const int GATE_STATE_PARTIAL = 1
const int GATE_STATE_FULL = 2
const string ATTACHMENT_SLOT_COMBINATION_LOCK = "Att_CombinationLock"
const string SOUND_GATE_OPEN_START = "DoorWoodTowerOpen_SoundSet"
const string SOUND_GATE_CLOSE_START = "DoorWoodTowerClose_start_SoundSet"
const string SOUND_GATE_CLOSE_END = "DoorWoodTowerClose_end_SoundSet"
const float GATE_ROTATION_ANGLE_DEG = 100
const float GATE_ROTATION_TIME_APPROX = 2000
const float MAX_ACTION_DETECTION_ANGLE_RAD = 1.3
const float MAX_ACTION_DETECTION_DISTANCE = 2.0
ATTACHMENT_WOODEN_LOG = WoodenLog
ATTACHMENT_COMBINATION_LOCK = CombinationLock
string ATTSLOT_CAMONET = "Wall_Camonet"
string ATTSLOT_BARBEDWIRE_DOWN = "Wall_Barbedwire_1"
string ATTSLOT_BARBEDWIRE_UP = "Wall_Barbedwire_2"
protected bool m_ToDiscard = false
protected bool m_IsOpened = false
protected bool m_IsOpenedClient = false
protected int m_GateState = 0
protected EffectSound m_SoundGate_Start
protected EffectSound m_SoundGate_End
bool m_RefresherActive
bool m_RefresherActiveLocal
bool m_RefresherInitialized
int m_RefresherTimeRemaining
int m_RefreshTimeCounter
protected int m_FlagRefresherFrequency = GameConstants.REFRESHER_FREQUENCY_DEFAULT
protected int m_FlagRefresherMaxDuration = GameConstants.REFRESHER_MAX_DURATION_DEFAULT
ATTACHMENT_BARBED_WIRE = BarbedWire
ATTACHMENT_CAMONET = CamoNet
const float MAX_FLOOR_VERTICAL_DISTANCE = 0.5
const float MIN_ACTION_DETECTION_ANGLE_RAD = 0.35
Static Private Attributes
static const string BASE_VIEW_NAME = "level_"
static const string BASE_WALL_NAME = "_wall_"
static const string BASE_ROOF_NAME = "_roof"
static const int MAX_WATCHTOWER_FLOORS = 3
static const int MAX_WATCHTOWER_WALLS = 3
Detailed Description
Definition at line 1 of file Fence.c.
Constructor & Destructor Documentation
~TerritoryFlag()
void ~TerritoryFlag () inline private
Definition at line 29 of file Totem.c.
References RemoveRefresherPosition().
Member Function Documentation
AddRefresherTime01()
void AddRefresherTime01 (float fraction) inline private
Definition at line 516 of file Totem.c.
References Math::Clamp(), Math::Round(), and SetRefresherActive().
Referenced by OnDebugSpawn().
AfterStoreLoad() [1/3]
override void AfterStoreLoad () inline private
Definition at line 257 of file Fence.c.
References bsbDebugPrint(), CheckGateState(), GetConstruction(), ConstructionPart::IsBuilt(), IsOpened(), IsOpened(), OpenFence(), SetGateState(), and UpdateVisuals().
AfterStoreLoad() [2/3]
override void AfterStoreLoad () inline private
Definition at line 145 of file Totem.c.
References GetCEApi(), InitRefresherData(), and UpdateVisuals().
AfterStoreLoad() [3/3]
override void AfterStoreLoad () inline private
Definition at line 399 of file Watchtower.c.
References UpdateVisuals().
AnimateFlag()
void AnimateFlag (float delta) inline private
Definition at line 488 of file Totem.c.
References Math::Clamp(), InventorySlots::GetSlotIdFromString(), and Math::Round().
Referenced by OnCEUpdate(), OnDebugSpawn(), and OnStoreLoad().
CanBeRepairedToPristine() [1/4]
override bool CanBeRepairedToPristine () inline private
Definition at line 425 of file Fence.c.
CanBeRepairedToPristine() [2/4]
override bool CanBeRepairedToPristine () inline private
Definition at line 77 of file ShelterSite.c.
CanBeRepairedToPristine() [3/4]
override bool CanBeRepairedToPristine () inline private
Definition at line 350 of file Totem.c.
CanBeRepairedToPristine() [4/4]
override bool CanBeRepairedToPristine () inline private
Definition at line 128 of file Watchtower.c.
CanCloseFence()
bool CanCloseFence () inline private
Definition at line 441 of file Fence.c.
References HasHinges(), and IsOpened().
CanDisplayAttachmentCategory() [1/3]
override bool CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 197 of file Fence.c.
References HasBase().
CanDisplayAttachmentCategory() [2/3]
override bool CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 85 of file Totem.c.
References GetConstruction(), HasBase(), and IsPartConstructed().
CanDisplayAttachmentCategory() [3/3]
override bool CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 245 of file Watchtower.c.
References CheckMemoryPointVerticalDistance(), string::Contains(), GetConstruction(), GetGame(), GetPlayer(), and string::ToLower().
CanDisplayAttachmentSlot() [1/2]
override bool CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 176 of file Fence.c.
References GateAttachmentConditions(), InventorySlots::GetSlotIdFromString(), InventorySlots::GetSlotName(), and HasFullyConstructedGate().
CanDisplayAttachmentSlot() [2/2]
override bool CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 198 of file Watchtower.c.
References CheckMemoryPointVerticalDistance(), string::Contains(), GetConstruction(), GetGame(), GetPlayer(), InventorySlots::GetSlotName(), and string::ToLower().
CanOpenFence()
bool CanOpenFence () inline private
Definition at line 431 of file Fence.c.
References HasHinges(), IsLocked(), and IsOpened().
CanPutIntoHands() [1/4]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 410 of file Fence.c.
References HasBase().
CanPutIntoHands() [2/4]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 72 of file ShelterSite.c.
CanPutIntoHands() [3/4]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 345 of file Totem.c.
CanPutIntoHands() [4/4]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 123 of file Watchtower.c.
CanReceiveAttachment() [1/3]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 371 of file Fence.c.
References GateAttachmentConditions(), GetGame(), GetPlayer(), HasBase(), HasFullyConstructedGate(), IsOpened(), and ConstructionActionData::SetActionInitiator().
CanReceiveAttachment() [2/3]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 276 of file Totem.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), ConfigIsExisting(), GetConstruction(), GetGame(), ConstructionPart::GetId(), ConstructionPart::GetMainPartName(), ConstructionPart::GetPartName(), GetPlayer(), InventorySlots::GetSlotName(), GetType(), ConstructionPart::IsBuilt(), IsPartConstructed(), and ConstructionActionData::SetActionInitiator().
CanReceiveAttachment() [3/3]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 90 of file Watchtower.c.
References CheckSlotVerticalDistance(), ConstructionActionData::GetActionInitiator(), GetGame(), GetPlayer(), and ConstructionActionData::SetActionInitiator().
CanUseConstructionBuild()
override bool CanUseConstructionBuild () inline private
Definition at line 722 of file Fence.c.
References IsOpened().
CanUseHandConstruction()
override bool CanUseHandConstruction () inline private
Definition at line 82 of file ShelterSite.c.
CheckFenceClosed()
protected void CheckFenceClosed () inline private
Definition at line 545 of file Fence.c.
References CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), ScriptCallQueue::Remove(), SoundGateCloseEnd(), and UpdateBarbedWireAreaDamagePos().
CheckFenceOpened()
protected void CheckFenceOpened () inline private
Definition at line 535 of file Fence.c.
References CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), ScriptCallQueue::Remove(), and UpdateBarbedWireAreaDamagePos().
CheckGateState()
int CheckGateState () inline private
Definition at line 77 of file Fence.c.
References GATE_STATE_FULL, GATE_STATE_NONE, GATE_STATE_PARTIAL, GetConstruction(), ConstructionPart::GetRequiredParts(), and ConstructionPart::IsBuilt().
Referenced by AfterStoreLoad(), OnPartBuiltServer(), OnPartDestroyedServer(), and OnPartDismantledServer().
CheckLevelVerticalDistance()
override bool CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player) inline private
Definition at line 383 of file Watchtower.c.
References CheckMemoryPointVerticalDistance(), and string::Contains().
Referenced by IsPlayerInside().
CheckLoadedVariables()
void CheckLoadedVariables (int max_duration) inline private
Definition at line 529 of file Totem.c.
Referenced by OnStoreLoad().
CheckMemoryPointVerticalDistance()
override bool CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player) inline private
Definition at line 357 of file Watchtower.c.
References Math::AbsFloat(), GetMemoryPointPos(), MemoryPointExists(), and ModelToWorld().
Referenced by CanDisplayAttachmentCategory(), CanDisplayAttachmentSlot(), CheckLevelVerticalDistance(), and CheckSlotVerticalDistance().
CheckSlotVerticalDistance()
override bool CheckSlotVerticalDistance (int slot_id, PlayerBase player) inline private
Definition at line 295 of file Watchtower.c.
References CheckMemoryPointVerticalDistance(), string::Contains(), GetConstruction(), InventorySlots::GetSelectionForSlotId(), and string::ToLower().
Referenced by ActionAttachToConstruction::ActionCondition(), and CanReceiveAttachment().
CloseFence()
void CloseFence () inline private
Definition at line 493 of file Fence.c.
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), ScriptCallQueue::Remove(), SetOpenedState(), SoundGateCloseStart(), SynchronizeBaseState(), UpdateBarbedWireAreaDamagePos(), and UpdateNavmesh().
Referenced by OnPartDestroyedServer(), and OnVariablesSynchronized().
CreateAreaDamage()
override void CreateAreaDamage (string slot_name, float rotation_angle = 0) inline private
Definition at line 562 of file Fence.c.
References IsOpened().
Fence()
void Fence () inline private
Definition at line 36 of file Fence.c.
GateAttachmentConditions()
bool GateAttachmentConditions (int slotId) inline private
Definition at line 793 of file Fence.c.
References GetConstruction(), GetGateState(), InventorySlots::GetSlotName(), and ConstructionPart::IsBuilt().
Referenced by CanDisplayAttachmentSlot(), and CanReceiveAttachment().
GateAttachmentsSanityCheck()
void GateAttachmentsSanityCheck () inline private
Definition at line 757 of file Fence.c.
References GetBarbedWire1(), GetBarbedWire2(), GetCamoNet(), GetCombinationLock(), GetConstruction(), HandleDropAttachment(), and ConstructionPart::IsBuilt().
GetBarbedWire1()
BarbedWire GetBarbedWire1 () inline private
Definition at line 149 of file Fence.c.
Referenced by GateAttachmentsSanityCheck(), OnPartDestroyedServer(), and UpdateBarbedWireAreaDamagePos().
GetBarbedWire2()
BarbedWire GetBarbedWire2 () inline private
Definition at line 155 of file Fence.c.
Referenced by GateAttachmentsSanityCheck(), OnPartDestroyedServer(), and UpdateBarbedWireAreaDamagePos().
GetCamoNet()
CamoNet GetCamoNet () inline private
Definition at line 143 of file Fence.c.
Referenced by GateAttachmentsSanityCheck(), and OnPartDestroyedServer().
GetCombinationLock()
CombinationLock GetCombinationLock () inline private
Definition at line 137 of file Fence.c.
Referenced by GateAttachmentsSanityCheck(), IsLocked(), and OnPartDestroyedServer().
GetConstructionKitType() [1/4]
override string GetConstructionKitType () inline private
Definition at line 45 of file Fence.c.
Referenced by ItemBase::CreateConstructionKit(), and ItemBase::CreateConstructionKitInHands().
GetConstructionKitType() [2/4]
override string GetConstructionKitType () inline private
Definition at line 10 of file ShelterSite.c.
GetConstructionKitType() [3/4]
override string GetConstructionKitType () inline private
Definition at line 50 of file Totem.c.
GetConstructionKitType() [4/4]
override string GetConstructionKitType () inline private
Definition at line 21 of file Watchtower.c.
GetGateState()
int GetGateState () inline private
Definition at line 72 of file Fence.c.
References m_GateState.
Referenced by GateAttachmentConditions().
GetKitSpawnPosition() [1/3]
override vector GetKitSpawnPosition () inline private
Definition at line 162 of file Fence.c.
References GetMemoryPointPos(), GetPosition, MemoryPointExists(), and ModelToWorld().
Referenced by ItemBase::CreateConstructionKit().
GetKitSpawnPosition() [2/3]
override vector GetKitSpawnPosition () inline private
Definition at line 21 of file ShelterSite.c.
References GetMemoryPointPos(), GetPosition, MemoryPointExists(), and ModelToWorld().
GetKitSpawnPosition() [3/3]
override vector GetKitSpawnPosition () inline private
Definition at line 72 of file Totem.c.
References GetMemoryPointPos(), GetPosition, MemoryPointExists(), and ModelToWorld().
GetMeleeTargetType() [1/4]
override int GetMeleeTargetType () inline private
Definition at line 50 of file Fence.c.
GetMeleeTargetType() [2/4]
override int GetMeleeTargetType () inline private
Definition at line 15 of file ShelterSite.c.
GetMeleeTargetType() [3/4]
override int GetMeleeTargetType () inline private
Definition at line 55 of file Totem.c.
GetMeleeTargetType() [4/4]
override int GetMeleeTargetType () inline private
Definition at line 26 of file Watchtower.c.
GetRefresherTime01()
float GetRefresherTime01 () inline private
Definition at line 524 of file Totem.c.
References m_FlagRefresherMaxDuration.
Referenced by OnCEUpdate(), and OnStoreLoad().
HandleDropAttachment()
void HandleDropAttachment (ItemBase item) inline private
Definition at line 774 of file Fence.c.
References Class::CastTo().
Referenced by GateAttachmentsSanityCheck(), and OnPartDestroyedServer().
HandleRefreshers()
void HandleRefreshers () inline private
Client-side, saves positions of active lifetime refreshers to MissionGameplay.
Definition at line 179 of file Totem.c.
References GetGame(), CGame::GetMission(), GetPosition, InsertRefresherPosition(), Mission::m_ActiveRefresherLocations, mission, and RemoveRefresherPosition().
Referenced by OnVariablesSynchronized().
HasFullyConstructedGate()
bool HasFullyConstructedGate () inline private
Definition at line 61 of file Fence.c.
References GATE_STATE_FULL.
Referenced by CanDisplayAttachmentSlot(), and CanReceiveAttachment().
HasHinges()
bool HasHinges () inline private
Definition at line 56 of file Fence.c.
References GATE_STATE_NONE.
Referenced by CanCloseFence(), and CanOpenFence().
HasProperDistance() [1/4]
override bool HasProperDistance (string selection, PlayerBase player) inline private
Definition at line 707 of file Fence.c.
References vector::Distance(), GetMemoryPointPos(), MemoryPointExists(), and ModelToWorld().
Referenced by ActionRepairPart::RepairCondition().
HasProperDistance() [2/4]
override bool HasProperDistance (string selection, PlayerBase player) inline private
Definition at line 149 of file ShelterSite.c.
References vector::Distance(), GetMemoryPointPos(), MemoryPointExists(), and ModelToWorld().
HasProperDistance() [3/4]
override bool HasProperDistance (string selection, PlayerBase player) inline private
Definition at line 450 of file Totem.c.
References vector::Distance(), GetMemoryPointPos(), MemoryPointExists(), and ModelToWorld().
HasProperDistance() [4/4]
override bool HasProperDistance (string selection, PlayerBase player) inline private
Definition at line 546 of file Watchtower.c.
References vector::Distance(), GetMemoryPointPos(), MemoryPointExists(), and ModelToWorld().
InitRefresherData()
void InitRefresherData () inline private
Definition at line 34 of file Totem.c.
References GetCEApi().
Referenced by AfterStoreLoad(), and TerritoryFlag().
InsertRefresherPosition()
void InsertRefresherPosition () inline private
Definition at line 208 of file Totem.c.
References GetGame(), CGame::GetMission(), GetPosition, Mission::m_ActiveRefresherLocations, and mission.
Referenced by HandleRefreshers().
IsFacingCamera() [1/4]
override bool IsFacingCamera (string selection) inline private
Definition at line 682 of file Fence.c.
References Math::Acos(), CGame::GetCurrentCameraDirection(), GetDirection(), GetGame(), vector::Length(), and vector::Normalize().
Referenced by BuildCondition(), ActionDestroyPart::DestroyCondition(), ActionDismantlePart::DismantleCondition(), and ActionRepairPart::RepairCondition().
IsFacingCamera() [2/4]
override bool IsFacingCamera (string selection) inline private
Definition at line 92 of file ShelterSite.c.
References Math::Acos(), CGame::GetCurrentCameraDirection(), GetDirection(), GetGame(), vector::Length(), and vector::Normalize().
IsFacingCamera() [3/4]
override bool IsFacingCamera (string selection) inline private
Definition at line 423 of file Totem.c.
References Math::Acos(), CGame::GetCurrentCameraDirection(), GetDirection(), GetGame(), vector::Length(), and vector::Normalize().
IsFacingCamera() [4/4]
override bool IsFacingCamera (string selection) inline private
Definition at line 478 of file Watchtower.c.
References vector::Dot(), CGame::GetCurrentCameraDirection(), GetGame(), GetMemoryPointPos(), GetPosition, vector::Length(), MemoryPointExists(), ModelToWorld(), and vector::Normalize().
IsFacingPlayer() [1/3]
override bool IsFacingPlayer (PlayerBase player, string selection) inline private
Definition at line 655 of file Fence.c.
References Math::Acos(), GetDirection(), GetPosition, vector::Length(), and vector::Normalize().
Referenced by ActionRepairPart::RepairCondition().
IsFacingPlayer() [2/3]
override bool IsFacingPlayer (PlayerBase player, string selection) inline private
Definition at line 394 of file Totem.c.
References Math::Acos(), GetDirection(), GetPosition, vector::Length(), and vector::Normalize().
IsFacingPlayer() [3/3]
override bool IsFacingPlayer (PlayerBase player, string selection) inline private
Definition at line 429 of file Watchtower.c.
References Math::AbsFloat(), vector::Dot(), GetMemoryPointPos(), GetPosition, vector::Length(), MemoryPointExists(), ModelToWorld(), and vector::Normalize().
IsLocked()
bool IsLocked () inline private
Definition at line 115 of file Fence.c.
References GetCombinationLock().
Referenced by CanOpenFence(), and OnPartDismantledServer().
IsOpened()
override bool IsOpened () inline private
Definition at line 110 of file Fence.c.
References m_IsOpened.
Referenced by AfterStoreLoad(), CanCloseFence(), CanOpenFence(), CanReceiveAttachment(), CanUseConstructionBuild(), CreateAreaDamage(), ActionDismantlePart::DismantleCondition(), and OnPartDestroyedServer().
IsPlayerInside() [1/4]
override bool IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 619 of file Fence.c.
References vector::AnglesToVector(), GetCollisionBox(), GetDirection(), GetPosition, vector::Length(), vector::Normalize(), vector::VectorToAngles(), and x.
Referenced by ActionUnmountBarbedWire::ActionCondition(), ActionTakeMaterialToHands::ActionCondition(), ActionAttachToConstruction::ActionCondition(), ActionTakeMaterialToHandsSwitch::ActionCondition(), BuildCondition(), ActionDismantlePart::DismantleCondition(), and VicinityContainer::UpdateInterval().
IsPlayerInside() [2/4]
override bool IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 117 of file ShelterSite.c.
References vector::AnglesToVector(), GetDirection(), GetMemoryPointPos(), GetPosition, vector::Length(), vector::Normalize(), and vector::VectorToAngles().
IsPlayerInside() [3/4]
override bool IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 356 of file Totem.c.
References vector::AnglesToVector(), GetCollisionBox(), GetDirection(), GetPosition, vector::Length(), vector::Normalize(), vector::VectorToAngles(), and x.
IsPlayerInside() [4/4]
override bool IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 508 of file Watchtower.c.
References vector::AnglesToVector(), CheckLevelVerticalDistance(), GetDirection(), GetMemoryPointPos(), GetPosition, vector::Length(), vector::Normalize(), and vector::VectorToAngles().
MustBeBuiltFromOutside()
override bool MustBeBuiltFromOutside () inline private
Definition at line 87 of file ShelterSite.c.
Referenced by BuildCondition().
NameOverride()
override bool NameOverride (out string output) inline private
Definition at line 126 of file Fence.c.
OnCEUpdate()
override void OnCEUpdate () inline private
Definition at line 157 of file Totem.c.
References AnimateFlag(), Math::Clamp(), GetCEApi(), GetPosition, GetRefresherTime01(), GameConstants::REFRESHER_RADIUS, Math::Round(), and SetRefresherActive().
OnDebugSpawn() [1/3]
override void OnDebugSpawn () inline private
Definition at line 896 of file Fence.c.
OnDebugSpawn() [2/3]
override void OnDebugSpawn () inline private
Definition at line 553 of file Totem.c.
References AddRefresherTime01(), and AnimateFlag().
OnDebugSpawn() [3/3]
override void OnDebugSpawn () inline private
Definition at line 599 of file Watchtower.c.
References MAX_WATCHTOWER_WALLS.
OnDebugSpawnBuildExcludes() [1/2]
override array< string > OnDebugSpawnBuildExcludes () inline private
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
Definition at line 858 of file Fence.c.
References DiagMenu::GetBool().
Referenced by ItemBase::FullyBuild().
OnDebugSpawnBuildExcludes() [2/2]
override array< string > OnDebugSpawnBuildExcludes () inline private
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
Definition at line 576 of file Watchtower.c.
References DiagMenu::GetBool().
OnPartBuiltServer() [1/4]
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 297 of file Fence.c.
References CheckGateState(), GetConstruction(), ConstructionPart::IsGate(), SetGateState(), and UpdateVisuals().
Referenced by ItemBase::FullyBuild().
OnPartBuiltServer() [2/4]
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 36 of file ShelterSite.c.
References GetConstruction(), and GetPlugin().
OnPartBuiltServer() [3/4]
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 247 of file Totem.c.
References UpdateVisuals().
OnPartBuiltServer() [4/4]
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 406 of file Watchtower.c.
References UpdateVisuals().
OnPartDestroyedServer() [1/3]
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false) inline private
Definition at line 335 of file Fence.c.
References CheckGateState(), CloseFence(), GetBarbedWire1(), GetBarbedWire2(), GetCamoNet(), GetCombinationLock(), GetConstruction(), HandleDropAttachment(), ConstructionPart::IsGate(), IsOpened(), SetGateState(), and UpdateVisuals().
OnPartDestroyedServer() [2/3]
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false) inline private
Definition at line 267 of file Totem.c.
References UpdateVisuals().
OnPartDestroyedServer() [3/3]
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false) inline private
Definition at line 420 of file Watchtower.c.
References UpdateVisuals().
OnPartDismantledServer() [1/3]
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 313 of file Fence.c.
References CheckGateState(), GetConstruction(), ConstructionPart::IsGate(), IsLocked(), SetGateState(), and UpdateVisuals().
OnPartDismantledServer() [2/3]
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 257 of file Totem.c.
References GetConstruction(), and UpdateVisuals().
OnPartDismantledServer() [3/3]
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 413 of file Watchtower.c.
References UpdateVisuals().
OnStoreLoad() [1/2]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 222 of file Fence.c.
References bsbDebugPrint(), GATE_STATE_NONE, m_IsOpened, and Serializer::Read().
OnStoreLoad() [2/2]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 111 of file Totem.c.
References AnimateFlag(), CheckLoadedVariables(), GetRefresherTime01(), and Serializer::Read().
OnStoreSave() [1/2]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 212 of file Fence.c.
References bsbDebugPrint(), m_IsOpened, and Serializer::Write().
OnStoreSave() [2/2]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 101 of file Totem.c.
References Serializer::Write().
OnVariablesSynchronized() [1/2]
override void OnVariablesSynchronized () inline private
Definition at line 276 of file Fence.c.
References CloseFence(), m_IsOpened, m_IsOpened, and OpenFence().
OnVariablesSynchronized() [2/2]
override void OnVariablesSynchronized () inline private
Definition at line 234 of file Totem.c.
References HandleRefreshers(), and m_RefresherActive.
OpenFence()
void OpenFence () inline private
Definition at line 451 of file Fence.c.
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), GATE_ROTATION_ANGLE_DEG, CGame::GetCallQueue(), GetGame(), ScriptCallQueue::Remove(), SetOpenedState(), SoundGateOpenStart(), SynchronizeBaseState(), UpdateBarbedWireAreaDamagePos(), and UpdateNavmesh().
Referenced by AfterStoreLoad(), and OnVariablesSynchronized().
PerformRoofCheckForBase()
override bool PerformRoofCheckForBase (string partName, PlayerBase player, out bool result) inline private
Definition at line 133 of file Watchtower.c.
References CfgGameplayHandler::GetDisablePerformRoofCheck(), GetGame(), GetMemoryPointPos(), GetOrientation(), GetPosition, and CGame::IsBoxCollidingGeometry().
Referenced by ComplexBuildCollideCheckClient().
PostAreaDamageActions()
override void PostAreaDamageActions () inline private
Definition at line 607 of file Fence.c.
RemoveRefresherPosition()
void RemoveRefresherPosition (int idx = -2) inline private
Definition at line 214 of file Totem.c.
References GetGame(), CGame::GetMission(), GetPosition, Mission::m_ActiveRefresherLocations, and mission.
Referenced by HandleRefreshers(), and ~TerritoryFlag().
SetActions() [1/4]
override void SetActions () inline private
Definition at line 829 of file Fence.c.
References ActionFoldBaseBuildingObject(), and AddAction().
SetActions() [2/4]
override void SetActions () inline private
Definition at line 164 of file ShelterSite.c.
References ActionFoldBaseBuildingObject(), and AddAction().
SetActions() [3/4]
override void SetActions () inline private
Definition at line 471 of file Totem.c.
References ActionFoldBaseBuildingObject(), and AddAction().
SetActions() [4/4]
override void SetActions () inline private
Definition at line 561 of file Watchtower.c.
References ActionFoldBaseBuildingObject(), and AddAction().
SetGateState()
void SetGateState (int state) inline private
Definition at line 66 of file Fence.c.
Referenced by AfterStoreLoad(), OnPartBuiltServer(), OnPartDestroyedServer(), and OnPartDismantledServer().
SetOpenedState()
void SetOpenedState (bool state) inline private
Definition at line 105 of file Fence.c.
References m_IsOpened.
Referenced by CloseFence(), and OpenFence().
SetRefresherActive()
void SetRefresherActive (bool state) inline private
Definition at line 196 of file Totem.c.
References GetCEApi(), GetPosition, and GameConstants::REFRESHER_RADIUS.
Referenced by AddRefresherTime01(), and OnCEUpdate().
SetRefreshTimer01()
void SetRefreshTimer01 (float fraction) inline private
Definition at line 503 of file Totem.c.
References Math::Clamp(), and Math::Round().
ShelterSite()
void ShelterSite () inline private
Definition at line 6 of file ShelterSite.c.
SoundGateCloseEnd()
protected void SoundGateCloseEnd () inline private
Definition at line 748 of file Fence.c.
References GetGame(), and PlaySoundSet().
Referenced by CheckFenceClosed().
SoundGateCloseStart()
protected void SoundGateCloseStart () inline private
Definition at line 739 of file Fence.c.
References GetGame(), and PlaySoundSet().
Referenced by CloseFence().
SoundGateOpenStart()
protected void SoundGateOpenStart () inline private
Definition at line 730 of file Fence.c.
References GetGame(), and PlaySoundSet().
Referenced by OpenFence().
TerritoryFlag()
void TerritoryFlag () inline private
Definition at line 15 of file Totem.c.
References GetCEApi(), and InitRefresherData().
TranslateSlotFromSelection()
override bool TranslateSlotFromSelection (string selection_name, out int slot_id) inline private
Definition at line 819 of file Fence.c.
References InventorySlots::GetSlotIdFromString().
UpdateBarbedWireAreaDamagePos()
void UpdateBarbedWireAreaDamagePos (float rotation_angle = 0, bool to_delete = false) inline private
Definition at line 573 of file Fence.c.
References DestroyAreaDamage(), GetBarbedWire1(), and GetBarbedWire2().
Referenced by CheckFenceClosed(), CheckFenceOpened(), CloseFence(), and OpenFence().
UpdateVisuals()
override void UpdateVisuals () inline private
Definition at line 44 of file Watchtower.c.
References BASE_ROOF_NAME, GetConstruction(), and MAX_WATCHTOWER_FLOORS.
Referenced by AfterStoreLoad(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), ItemBase::OnPartBuiltServer(), OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), OnPartDismantledServer(), and ItemBase::OnSynchronizedClient().
Watchtower()
void Watchtower () inline private
Definition at line 17 of file Watchtower.c.
Field Documentation
ATTACHMENT_BARBED_WIRE
ATTACHMENT_BARBED_WIRE = BarbedWire private
Definition at line 3 of file Watchtower.c.
ATTACHMENT_CAMONET
ATTACHMENT_CAMONET = CamoNet private
Definition at line 4 of file Watchtower.c.
ATTACHMENT_COMBINATION_LOCK
ATTACHMENT_COMBINATION_LOCK = CombinationLock private
Definition at line 20 of file Fence.c.
ATTACHMENT_SLOT_COMBINATION_LOCK
const string ATTACHMENT_SLOT_COMBINATION_LOCK = "Att_CombinationLock" private
Definition at line 7 of file Fence.c.
ATTACHMENT_WOODEN_LOG
ATTACHMENT_WOODEN_LOG = WoodenLog private
Definition at line 19 of file Fence.c.
ATTSLOT_BARBEDWIRE_DOWN
string ATTSLOT_BARBEDWIRE_DOWN = "Wall_Barbedwire_1" private
Definition at line 23 of file Fence.c.
ATTSLOT_BARBEDWIRE_UP
string ATTSLOT_BARBEDWIRE_UP = "Wall_Barbedwire_2" private
Definition at line 24 of file Fence.c.
ATTSLOT_CAMONET
string ATTSLOT_CAMONET = "Wall_Camonet" private
Definition at line 22 of file Fence.c.
BASE_ROOF_NAME
const string BASE_ROOF_NAME = "_roof" static private
Definition at line 13 of file Watchtower.c.
Referenced by UpdateVisuals().
BASE_VIEW_NAME
const string BASE_VIEW_NAME = "level_" static private
Definition at line 11 of file Watchtower.c.
BASE_WALL_NAME
const string BASE_WALL_NAME = "_wall_" static private
Definition at line 12 of file Watchtower.c.
GATE_ROTATION_ANGLE_DEG
const float GATE_ROTATION_ANGLE_DEG = 100 private
Definition at line 13 of file Fence.c.
Referenced by OpenFence().
GATE_ROTATION_TIME_APPROX
const float GATE_ROTATION_TIME_APPROX = 2000 private
Definition at line 14 of file Fence.c.
GATE_STATE_FULL
const int GATE_STATE_FULL = 2 private
Definition at line 5 of file Fence.c.
Referenced by CheckGateState(), and HasFullyConstructedGate().
GATE_STATE_NONE
const int GATE_STATE_NONE = 0 private
Definition at line 3 of file Fence.c.
Referenced by CheckGateState(), HasHinges(), and OnStoreLoad().
GATE_STATE_PARTIAL
const int GATE_STATE_PARTIAL = 1 private
Definition at line 4 of file Fence.c.
Referenced by CheckGateState().
m_FlagRefresherFrequency
protected int m_FlagRefresherFrequency = GameConstants.REFRESHER_FREQUENCY_DEFAULT private
Definition at line 12 of file Totem.c.
m_FlagRefresherMaxDuration
protected int m_FlagRefresherMaxDuration = GameConstants.REFRESHER_MAX_DURATION_DEFAULT private
Definition at line 13 of file Totem.c.
Referenced by GetRefresherTime01().
m_GateState
protected int m_GateState = 0 private
Definition at line 31 of file Fence.c.
Referenced by GetGateState().
m_IsOpened
protected bool m_IsOpened = false private
Definition at line 29 of file Fence.c.
Referenced by IsOpened(), and OnVariablesSynchronized().
m_IsOpenedClient
protected bool m_IsOpenedClient = false private
Definition at line 30 of file Fence.c.
m_RefresherActive
bool m_RefresherActive private
Definition at line 6 of file Totem.c.
Referenced by OnVariablesSynchronized().
m_RefresherActiveLocal
bool m_RefresherActiveLocal private
Definition at line 7 of file Totem.c.
m_RefresherInitialized
bool m_RefresherInitialized private
Definition at line 8 of file Totem.c.
m_RefresherTimeRemaining
int m_RefresherTimeRemaining private
Definition at line 9 of file Totem.c.
m_RefreshTimeCounter
int m_RefreshTimeCounter private
Definition at line 10 of file Totem.c.
m_SoundGate_End
protected EffectSound m_SoundGate_End private
Definition at line 34 of file Fence.c.
m_SoundGate_Start
protected EffectSound m_SoundGate_Start private
Definition at line 33 of file Fence.c.
m_ToDiscard
protected bool m_ToDiscard = false private
Definition at line 28 of file Fence.c.
MAX_ACTION_DETECTION_ANGLE_RAD
const float MAX_ACTION_DETECTION_ANGLE_RAD = 1.3 private
Definition at line 16 of file Fence.c.
MAX_ACTION_DETECTION_DISTANCE
const float MAX_ACTION_DETECTION_DISTANCE = 2.0 private
Definition at line 17 of file Fence.c.
MAX_FLOOR_VERTICAL_DISTANCE
const float MAX_FLOOR_VERTICAL_DISTANCE = 0.5 private
Definition at line 6 of file Watchtower.c.
MAX_WATCHTOWER_FLOORS
const int MAX_WATCHTOWER_FLOORS = 3 static private
Definition at line 14 of file Watchtower.c.
Referenced by UpdateVisuals().
MAX_WATCHTOWER_WALLS
const int MAX_WATCHTOWER_WALLS = 3 static private
Definition at line 15 of file Watchtower.c.
Referenced by OnDebugSpawn().
MIN_ACTION_DETECTION_ANGLE_RAD
const float MIN_ACTION_DETECTION_ANGLE_RAD = 0.35 private
Definition at line 8 of file Watchtower.c.
SOUND_GATE_CLOSE_END
const string SOUND_GATE_CLOSE_END = "DoorWoodTowerClose_end_SoundSet" private
Definition at line 10 of file Fence.c.
SOUND_GATE_CLOSE_START
const string SOUND_GATE_CLOSE_START = "DoorWoodTowerClose_start_SoundSet" private
Definition at line 9 of file Fence.c.
SOUND_GATE_OPEN_START
const string SOUND_GATE_OPEN_START = "DoorWoodTowerOpen_SoundSet" private
Definition at line 8 of file Fence.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/BaseBuildingBase/Fence.c
P:/scripts/4_World/Entities/ItemBase/BaseBuildingBase/ShelterSite.c
P:/scripts/4_World/Entities/ItemBase/BaseBuildingBase/Totem.c
P:/scripts/4_World/Entities/ItemBase/BaseBuildingBase/Watchtower.c