DayZ: OptionSelectorSliderSetup Class Reference
OptionSelectorSliderSetup Class Reference
This Option Selector handles a Slider Marker, which basically has 2 sliders One slider is for selecting the value, and the other slider is for displaying some other value/ information.
Private Member Functions
void OptionSelectorLevelMarker (Widget parent, float value, ScriptedWidgetEventHandler parentMenu, bool disabled, float min, float max)
override void Enable ()
override void Disable ()
void SetSlider2Value (float value)
override bool OnUpdate (Widget w)
void OptionSelectorSlider (Widget parent, float value, ScriptedWidgetEventHandler parent_menu, bool disabled, float min, float max)
Private Attributes
protected SliderWidget m_Slider2
Detailed Description
This Option Selector handles a Slider Marker, which basically has 2 sliders One slider is for selecting the value, and the other slider is for displaying some other value/ information.
Parameters
m_Slider2 other slider value, which can be used to convery some other info to the player
Definition at line 6 of file OptionSelectorLevelMarker.c.
Member Function Documentation
Disable()
override void Disable () inline private
Definition at line 42 of file OptionSelectorLevelMarker.c.
Enable()
override void Enable () inline private
Definition at line 36 of file OptionSelectorLevelMarker.c.
Referenced by OptionSelectorLevelMarker(), and OptionSelectorSlider().
OnUpdate()
override bool OnUpdate (Widget w) inline private
Definition at line 53 of file OptionSelectorLevelMarker.c.
OptionSelectorLevelMarker()
void OptionSelectorLevelMarker (Widget parent, float value, ScriptedWidgetEventHandler parentMenu, bool disabled, float min, float max) inline private
Definition at line 10 of file OptionSelectorLevelMarker.c.
References WorkspaceWidget::CreateWidgets(), Enable(), GetGame(), CGame::GetWorkspace(), m_MaxValue, m_MinValue, m_Parent, m_Root, SetSlider2Value(), and SetValue().
OptionSelectorSlider()
void OptionSelectorSlider (Widget parent, float value, ScriptedWidgetEventHandler parent_menu, bool disabled, float min, float max) inline private
Definition at line 3 of file OptionSelectorSlider.c.
References WorkspaceWidget::CreateWidgets(), Enable(), GetGame(), CGame::GetWorkspace(), m_MaxValue, m_MinValue, m_Parent, m_Root, and SetValue().
SetSlider2Value()
void SetSlider2Value (float value) inline private
Definition at line 48 of file OptionSelectorLevelMarker.c.
Referenced by OptionSelectorLevelMarker().
Field Documentation
m_Slider2
protected SliderWidget m_Slider2 private
Definition at line 8 of file OptionSelectorLevelMarker.c.
The documentation for this class was generated from the following files:
5_Mission/GUI/NewUI/OptionSelectorLevelMarker.c
5_Mission/GUI/NewUI/OptionSelectorSlider.c