DayZ: ActionAnimateSeats Class Reference
ActionAnimateSeats Class Reference
Private Member Functions
void ActionAnimateSeats ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeUsedInVehicle ()
Detailed Description
Definition at line 1 of file ActionAnimateSeats.c.
Constructor & Destructor Documentation
ActionAnimateSeats()
void ActionAnimateSeats () inline private
Definition at line 3 of file ActionAnimateSeats.c.
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 8 of file ActionAnimateSeats.c.
References Class::CastTo(), UAMaxDistances::DEFAULT, CarScript::GetAnimSourceFromSelection(), CarScript::GetCarDoorsState(), IsInReach(), and ActionAnimateCarSelection::m_AnimSource.
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle () inline private
Definition at line 67 of file ActionAnimateSeats.c.
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Interact/Vehicles/ActionAnimateSeats.c