DayZ Scripts Documentation: StarlightOptic Class Reference
StarlightOptic Class Reference
Private Member Functions
override void InitOpticMode ()
override int GetCurrentNVType ()
override void OnOpticModeChange ()
override void OnOpticEnter ()
override void UpdateSelectionVisibility ()
override void SetActions ()
Detailed Description
Definition at line 87 of file Optics.c.
Member Function Documentation
GetCurrentNVType()
override int GetCurrentNVType () inline private
Definition at line 96 of file Optics.c.
References Error(), GameConstants::OPTICS_STATE_DAY, and GameConstants::OPTICS_STATE_NIGHTVISION.
InitOpticMode()
override void InitOpticMode () inline private
Definition at line 89 of file Optics.c.
References GameConstants::OPTICS_STATE_NIGHTVISION.
OnOpticEnter()
override void OnOpticEnter () inline private
Definition at line 124 of file Optics.c.
References ItemOptics::HideSelection().
OnOpticModeChange()
override void OnOpticModeChange () inline private
Definition at line 117 of file Optics.c.
References UpdateSelectionVisibility().
SetActions()
override void SetActions () inline private
Definition at line 152 of file Optics.c.
References AddAction().
UpdateSelectionVisibility()
override void UpdateSelectionVisibility () inline private
Definition at line 131 of file Optics.c.
References GetGame(), ItemOptics::HideSelection(), GameConstants::OPTICS_STATE_DAY, GameConstants::OPTICS_STATE_NIGHTVISION, and ItemOptics::ShowSelection().
Referenced by OnOpticModeChange().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/Optics.c