DayZ: ConstructionPart Class Reference
ConstructionPart Class Reference
Private Member Functions
void ConstructionPart (string name, string part_name, string main_part_name, int id, bool is_built, bool is_base, bool is_gate, array< string > required_parts)
string GetName ()
string GetPartName ()
string GetMainPartName ()
int GetId ()
bool IsBuilt ()
void SetBuiltState (bool is_built)
void SetRequestBuiltState (bool req_built)
bool IsBase ()
bool IsGate ()
array< string > GetRequiredParts ()
Private Attributes
string m_Name
int m_Id
string m_PartName
string m_MainPartName
bool m_IsBuilt
bool m_IsBase
bool m_IsGate
ref array< string > m_RequiredParts
Detailed Description
Definition at line 1 of file ConstructionPart.c.
Constructor & Destructor Documentation
ConstructionPart()
void ConstructionPart (string name, string part_name, string main_part_name, int id, bool is_built, bool is_base, bool is_gate, array< string > required_parts) inline private
Definition at line 12 of file ConstructionPart.c.
References m_Id, m_IsBase, m_IsBuilt, m_IsGate, m_MainPartName, m_Name, m_PartName, m_RequiredParts, and name.
Member Function Documentation
GetId()
int GetId () inline private
Definition at line 40 of file ConstructionPart.c.
References m_Id.
Referenced by BaseBuildingBase::CanReceiveAttachment(), ItemBase::GetConstructionPartById(), ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), and ItemBase::SetPartFromSyncData().
GetMainPartName()
string GetMainPartName () inline private
Definition at line 35 of file ConstructionPart.c.
References m_MainPartName.
Referenced by BuildCondition(), BaseBuildingBase::CanReceiveAttachment(), CanUseToolToBuildPart(), CanUseToolToDismantlePart(), DestroyMaterialsServer(), DropNonUsableMaterialsServer(), GetCollisionBoxData(), GetConstructionPartsToBuild(), GetMaterialType(), HasConflictPart(), HasMaterials(), HasRequiredPart(), MaterialIsRuined(), ReceiveMaterialsServer(), ActionRepairPart::RepairCondition(), SetLockOnAttachedMaterials(), and TakeMaterialsServer().
GetName()
string GetName () inline private
Definition at line 24 of file ConstructionPart.c.
References m_Name.
Referenced by ActionBuildShelter::DetermineConstructionSounds(), ActionDismantlePart::GetAdminLogMessage(), ActionDismantlePart::GetText(), ActionRepairPart::GetText(), ActionBuildShelter::GetText(), ActionBuildPart::OnActionInfoUpdate(), ActionDismantlePart::OnActionInfoUpdate(), ActionRepairPart::OnActionInfoUpdate(), and ActionBuildShelter::OnActionInfoUpdate().
GetPartName()
string GetPartName () inline private
Definition at line 30 of file ConstructionPart.c.
References m_PartName.
Referenced by AddToConstructedParts(), BaseBuildingBase::CanReceiveAttachment(), CanUseToolToBuildPart(), CanUseToolToDismantlePart(), ComplexBuildCollideCheckClient(), DropNonUsableMaterialsServer(), GetConstructionPartsToBuild(), GetMaterialType(), InitVisuals(), ActionDestroyPart::OnFinishProgressServer(), ActionDismantlePart::OnFinishProgressServer(), RemoveFromConstructedParts(), ItemBase::SetActionFromSyncData(), ItemBase::SetPartFromSyncData(), ActionBuildPart::SetupAction(), ActionBuildShelter::SetupAction(), UpdatePhysics(), and UpdateVisuals().
GetRequiredParts()
array< string > GetRequiredParts () inline private
Definition at line 75 of file ConstructionPart.c.
References m_RequiredParts.
Referenced by BaseBuildingBase::CheckGateState(), GetValidDepenentPartsArray(), and HasDependentPart().
IsBase()
bool IsBase () inline private
Definition at line 65 of file ConstructionPart.c.
References m_IsBase.
Referenced by ActionDismantlePart::DismantleCondition(), DropNonUsableMaterialsServer(), GetBaseConstructionPart(), ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), ReceiveMaterialsServer(), and ItemBase::SetPartFromSyncData().
IsBuilt()
bool IsBuilt () inline private
Definition at line 45 of file ConstructionPart.c.
References m_IsBuilt.
Referenced by BaseBuildingBase::AfterStoreLoad(), BaseBuildingBase::CanReceiveAttachment(), BaseBuildingBase::CheckGateState(), BaseBuildingBase::GateAttachmentConditions(), BaseBuildingBase::GateAttachmentsSanityCheck(), GetValidDepenentPartsArray(), HasDependentPart(), InitVisuals(), IsPartConstructed(), ItemBase::SetPartFromSyncData(), ItemBase::SetPartsAfterStoreLoad(), UpdatePhysics(), and UpdateVisuals().
IsGate()
bool IsGate () inline private
Definition at line 70 of file ConstructionPart.c.
References m_IsGate.
Referenced by ActionDismantlePart::DismantleCondition(), ExceptionCheck(), GetGateConstructionPart(), BaseBuildingBase::OnPartBuiltServer(), BaseBuildingBase::OnPartDestroyedServer(), and BaseBuildingBase::OnPartDismantledServer().
SetBuiltState()
void SetBuiltState (bool is_built) inline private
Definition at line 50 of file ConstructionPart.c.
References bsbDebugPrint(), m_IsBuilt, and m_PartName.
Referenced by AddToConstructedParts(), RemoveFromConstructedParts(), and SetRequestBuiltState().
SetRequestBuiltState()
void SetRequestBuiltState (bool req_built) inline private
Definition at line 56 of file ConstructionPart.c.
References bsbDebugPrint(), GetGame(), m_PartName, and SetBuiltState().
Field Documentation
m_Id
int m_Id private
Definition at line 4 of file ConstructionPart.c.
Referenced by ConstructionPart(), and GetId().
m_IsBase
bool m_IsBase private
Definition at line 8 of file ConstructionPart.c.
Referenced by ConstructionPart(), and IsBase().
m_IsBuilt
bool m_IsBuilt private
Definition at line 7 of file ConstructionPart.c.
Referenced by ConstructionPart(), IsBuilt(), and SetBuiltState().
m_IsGate
bool m_IsGate private
Definition at line 9 of file ConstructionPart.c.
Referenced by ConstructionPart(), and IsGate().
m_MainPartName
string m_MainPartName private
Definition at line 6 of file ConstructionPart.c.
Referenced by ConstructionPart(), and GetMainPartName().
m_Name
string m_Name private
Definition at line 3 of file ConstructionPart.c.
Referenced by ConstructionPart(), and GetName().
m_PartName
string m_PartName private
Definition at line 5 of file ConstructionPart.c.
Referenced by ConstructionPart(), GetPartName(), SetBuiltState(), ItemBase::SetPartFromSyncData(), and SetRequestBuiltState().
m_RequiredParts
ref array<string> m_RequiredParts private
Definition at line 10 of file ConstructionPart.c.
Referenced by ConstructionPart(), and GetRequiredParts().
The documentation for this class was generated from the following file:
4_World/Classes/BaseBuilding/ConstructionPart.c