DayZ Scripts: HandGuardBase Class Reference
HandGuardBase Class Reference
guards
Private Member Functions
bool GuardCondition (HandEventBase e)
void HandGuardAnd (HandGuardBase arg0=null, HandGuardBase arg1=null)
override bool GuardCondition (HandEventBase e)
void HandGuardNot (HandGuardBase arg0=null)
override bool GuardCondition (HandEventBase e)
void HandGuardOr (HandGuardBase arg0=null, HandGuardBase arg1=null)
override bool GuardCondition (HandEventBase e)
void HandGuardHasItemInEvent (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardIsSameItemInHands (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardHasDestroyedItemInHands (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardHasItemInHands (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardHasRoomForItem (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardCanMove (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandGuardCanSwap (Man p=NULL)
override bool GuardCondition (HandEventBase e)
void HandGuardCanForceSwap (Man p=NULL)
override bool GuardCondition (HandEventBase e)
void HandGuardInstantForceSwap (Man p=NULL)
override bool GuardCondition (HandEventBase e)
void HandSelectAnimationOfTakeToHandsEvent (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandSelectAnimationOfMoveFromHandsEvent (Man p=null)
override bool GuardCondition (HandEventBase e)
void HandSelectAnimationOfForceSwapInHandsEvent (Man p=NULL)
bool ProcessSwapEvent (notnull HandEventBase e, out int animType1, out int animType2)
override bool GuardCondition (HandEventBase e)
void BotGuardHasItemInHands (Man p=NULL)
override bool GuardCondition (HandEventBase e)
Private Attributes
ref HandGuardBase m_arg0
ref HandGuardBase m_arg1
protected Man m_Player
Detailed Description
guards
represents guard on a transition from state to state
Definition at line 6 of file Hand_Guards.c.
Member Function Documentation
BotGuardHasItemInHands()
void BotGuardHasItemInHands (Man p = NULL) inline private
Definition at line 61 of file BotGuards.c.
References m_Player.
GuardCondition() [1/17]
bool GuardCondition (HandEventBase e) inline private
Definition at line 13 of file Hand_Guards.c.
GuardCondition() [2/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 24 of file Hand_Guards.c.
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
GuardCondition() [3/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 45 of file Hand_Guards.c.
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
GuardCondition() [4/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 66 of file Hand_Guards.c.
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
GuardCondition() [5/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 85 of file Hand_Guards.c.
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [6/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 140 of file Hand_Guards.c.
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [7/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 163 of file Hand_Guards.c.
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [8/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 215 of file Hand_Guards.c.
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [9/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 238 of file Hand_Guards.c.
References GameInventory::c_InventoryReservationTimeoutShortMS, InventoryLocation::DumpToStringNullSafe(), HandEventBase::GetDst(), GetGame(), InventoryLocation::GetItem(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), InventoryLocation::IsValid(), GameInventory::LocationTestAddEntity(), and m_Player.
GuardCondition() [10/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 293 of file Hand_Guards.c.
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationCanMoveEntity(), and m_Player.
GuardCondition() [11/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 315 of file Hand_Guards.c.
References GameInventory::CanSwapEntitiesEx(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [12/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 336 of file Hand_Guards.c.
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [13/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 360 of file Hand_Guards.c.
References InventoryLocation::GetParent(), InventoryLocation::GetType(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [14/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 189 of file HandAnimated_Guards.c.
References HandEventBase::GetDst(), and SelectAnimationOfTakeToHands().
GuardCondition() [15/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 210 of file HandAnimated_Guards.c.
References HandEventBase::GetDst(), hndDebugPrint(), GameInventory::LocationCanMoveEntity(), m_Player, and SelectAnimationOfMoveFromHands().
GuardCondition() [16/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 252 of file HandAnimated_Guards.c.
References GameInventory::CanForceSwapEntitiesEx(), GameInventory::CanSwapEntitiesEx(), HandEventBase::DumpToString(), InventoryLocation::DumpToStringNullSafe(), Error(), hndDebugPrint(), and HandEventBase::m_Animation2ID.
GuardCondition() [17/17]
override bool GuardCondition (HandEventBase e) inline private
Definition at line 63 of file BotGuards.c.
References hndDebugPrint(), and m_Player.
HandGuardAnd()
void HandGuardAnd (HandGuardBase arg0 = null, HandGuardBase arg1 = null) inline private
Definition at line 22 of file Hand_Guards.c.
HandGuardCanForceSwap()
void HandGuardCanForceSwap (Man p = NULL) inline private
Definition at line 334 of file Hand_Guards.c.
References m_Player.
HandGuardCanMove()
void HandGuardCanMove (Man p = null) inline private
Definition at line 291 of file Hand_Guards.c.
References m_Player.
HandGuardCanSwap()
void HandGuardCanSwap (Man p = NULL) inline private
Definition at line 313 of file Hand_Guards.c.
References m_Player.
HandGuardHasDestroyedItemInHands()
void HandGuardHasDestroyedItemInHands (Man p = null) inline private
Definition at line 161 of file Hand_Guards.c.
References m_Player.
HandGuardHasItemInEvent()
void HandGuardHasItemInEvent (Man p = null) inline private
Definition at line 83 of file Hand_Guards.c.
References m_Player.
HandGuardHasItemInHands()
void HandGuardHasItemInHands (Man p = null) inline private
Definition at line 213 of file Hand_Guards.c.
References m_Player.
HandGuardHasRoomForItem()
void HandGuardHasRoomForItem (Man p = null) inline private
Definition at line 236 of file Hand_Guards.c.
References m_Player.
HandGuardInstantForceSwap()
void HandGuardInstantForceSwap (Man p = NULL) inline private
Definition at line 358 of file Hand_Guards.c.
References m_Player.
HandGuardIsSameItemInHands()
void HandGuardIsSameItemInHands (Man p = null) inline private
Definition at line 138 of file Hand_Guards.c.
References m_Player.
HandGuardNot()
void HandGuardNot (HandGuardBase arg0 = null) inline private
Definition at line 43 of file Hand_Guards.c.
HandGuardOr()
void HandGuardOr (HandGuardBase arg0 = null, HandGuardBase arg1 = null) inline private
Definition at line 64 of file Hand_Guards.c.
HandSelectAnimationOfForceSwapInHandsEvent()
void HandSelectAnimationOfForceSwapInHandsEvent (Man p = NULL) inline private
Definition at line 241 of file HandAnimated_Guards.c.
References m_Player.
HandSelectAnimationOfMoveFromHandsEvent()
void HandSelectAnimationOfMoveFromHandsEvent (Man p = null) inline private
Definition at line 205 of file HandAnimated_Guards.c.
References m_Player.
HandSelectAnimationOfTakeToHandsEvent()
void HandSelectAnimationOfTakeToHandsEvent (Man p = null) inline private
Definition at line 187 of file HandAnimated_Guards.c.
ProcessSwapEvent()
bool ProcessSwapEvent (notnull HandEventBase e, out int animType1, out int animType2) inline private
Definition at line 243 of file HandAnimated_Guards.c.
References Error(), and SelectAnimationOfForceSwapInHands().
Field Documentation
m_arg0
ref HandGuardBase m_arg0 private
Definition at line 19 of file Hand_Guards.c.
m_arg1
ref HandGuardBase m_arg1 private
Definition at line 20 of file Hand_Guards.c.
m_Player
protected Man m_Player private
Definition at line 82 of file Hand_Guards.c.
The documentation for this class was generated from the following files:
P:/scripts/3_Game/Systems/Inventory/Hand_Guards.c
P:/scripts/3_Game/Systems/Inventory/HandAnimated_Guards.c
P:/scripts/4_World/Systems/Bot/BotGuards.c