DayZ Scripts Documentation: FireworksLauncherClientEvent Class Reference
FireworksLauncherClientEvent Class Reference
Private Member Functions
protected int GetSoundDelay ()
protected int GetLightDelay ()
protected float GetExplosionDistance ()
protected float GetShotDispersionAngle ()
protected string GetExplosionSoundSet ()
protected float GetExplosionDelay ()
void FireworksLauncherClientEvent (FireworksLauncher item, int index)
void ~FireworksLauncherClientEvent ()
override protected void OnFired ()
protected vector GetShotPos ()
protected void CalculateExplosionPosition ()
protected vector GetExplosionPosition ()
int GetSecondaryExplosionCount ()
protected void OnExplode ()
protected void RequestSecondaryExplosion ()
protected void SpawnSecondaryExplosion ()
protected int GetSecondaryExplosionDelay ()
protected int GetExplParticleFromSequence ()
protected void SetupLight (PointLightBase light)
protected void SpawnLight ()
protected void PlayExplosionSound ()
Private Attributes
protected ref Timer m_Timer = new Timer()
protected FireworksLauncher m_Item
protected int m_Index
protected vector m_ExplosionPos
protected EffectSound m_FireSound
protected EffectSound m_ExplosionSound
protected ParticleSource m_ParticleShot
protected ParticleSource m_ParticleExplosion
protected vector m_ShotDir
protected ExplosionLight m_ExplosionLight
protected ParticleSource m_ParticleAfterBurnEnd
protected string m_Color
protected int m_RemainingExplosions = GetSecondaryExplosionCount()
protected ref array< ref FireworksLauncherClientEventBase > m_Events = new ref array<ref FireworksLauncherClientEventBase>
Detailed Description
Definition at line 27 of file FireworksLauncher.c.
Constructor & Destructor Documentation
FireworksLauncherClientEvent()
void FireworksLauncherClientEvent (FireworksLauncher item, int index) inline private
Definition at line 87 of file FireworksLauncher.c.
References string::Get(), FireworksLauncher::GetColorSequence(), string::Length(), Debug::LogError(), m_Color, m_Index, and m_Item.
~FireworksLauncherClientEvent()
void ~FireworksLauncherClientEvent () inline private
Definition at line 106 of file FireworksLauncher.c.
References SEffectManager::DestroyEffect(), m_ExplosionSound, m_FireSound, m_ParticleAfterBurnEnd, and ParticleSource::StopParticle().
Member Function Documentation
CalculateExplosionPosition()
protected void CalculateExplosionPosition () inline private
Definition at line 154 of file FireworksLauncher.c.
References GetExplosionDistance(), GetShotPos(), m_ExplosionPos, and m_ShotDir.
Referenced by GetExplosionPosition().
GetExplosionDelay()
protected float GetExplosionDelay () inline private
Definition at line 77 of file FireworksLauncher.c.
References Math::RandomFloatInclusive().
Referenced by OnFired().
GetExplosionDistance()
protected float GetExplosionDistance () inline private
Definition at line 62 of file FireworksLauncher.c.
References Math::RandomFloatInclusive().
Referenced by CalculateExplosionPosition(), GetExplosionPosition(), and OnFired().
GetExplosionPosition()
protected vector GetExplosionPosition () inline private
Definition at line 159 of file FireworksLauncher.c.
References CalculateExplosionPosition(), and m_ExplosionPos.
Referenced by OnExplode(), OnExplode(), SpawnLight(), and SpawnSecondaryExplosion().
GetExplosionSoundSet()
protected string GetExplosionSoundSet () inline private
Definition at line 72 of file FireworksLauncher.c.
Referenced by PlayExplosionSound().
GetExplParticleFromSequence()
protected int GetExplParticleFromSequence () inline private
Definition at line 216 of file FireworksLauncher.c.
References ErrorEx, ParticleList::FIREWORKS_EXPLOSION_BLUE, ParticleList::FIREWORKS_EXPLOSION_GREEN, ParticleList::FIREWORKS_EXPLOSION_PINK, ParticleList::FIREWORKS_EXPLOSION_RED, ParticleList::FIREWORKS_EXPLOSION_YELLOW, and m_Color.
Referenced by OnExplode(), and OnExplode().
GetLightDelay()
protected int GetLightDelay () inline private
Definition at line 57 of file FireworksLauncher.c.
Referenced by OnExplode(), and OnExplode().
GetSecondaryExplosionCount()
int GetSecondaryExplosionCount () inline private
Definition at line 168 of file FireworksLauncher.c.
GetSecondaryExplosionDelay()
protected int GetSecondaryExplosionDelay () inline private
Definition at line 211 of file FireworksLauncher.c.
References Math::RandomIntInclusive().
Referenced by RequestSecondaryExplosion().
GetShotDispersionAngle()
protected float GetShotDispersionAngle () inline private
Definition at line 67 of file FireworksLauncher.c.
References Math::RandomFloatInclusive().
Referenced by OnFired().
GetShotPos()
protected vector GetShotPos () inline private
Definition at line 136 of file FireworksLauncher.c.
References Debug::LogError(), m_Index, and m_Item.
Referenced by CalculateExplosionPosition(), GetExplosionPosition(), and OnFired().
GetSoundDelay()
protected int GetSoundDelay () inline private
Definition at line 52 of file FireworksLauncher.c.
Referenced by OnExplode(), and OnExplode().
OnExplode()
protected void OnExplode () inline private
Definition at line 174 of file FireworksLauncher.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetExplosionPosition(), GetExplParticleFromSequence(), GetGame(), GetLightDelay(), GetSoundDelay(), m_ParticleAfterBurnEnd, m_ParticleExplosion, ParticleManager(), PlayExplosionSound(), RequestSecondaryExplosion(), SpawnLight(), and Particle::Stop().
OnFired()
override protected void OnFired () inline private
Definition at line 116 of file FireworksLauncher.c.
References ParticleList::FIREWORKS_AFTERBURN_END, ParticleList::FIREWORKS_SHOT, GetExplosionDelay(), GetExplosionDistance(), GetShotDispersionAngle(), GetShotPos(), m_FireSound, m_Item, m_ParticleAfterBurnEnd, m_ParticleShot, m_ShotDir, m_Timer, ParticleManager(), Math::RandomFloatInclusive(), ParticleSource::SetOwner(), and Vector().
PlayExplosionSound()
protected void PlayExplosionSound () inline private
Definition at line 272 of file FireworksLauncher.c.
References GetExplosionSoundSet(), m_ExplosionSound, m_FireSound, m_Item, and EffectSound::Stop().
Referenced by OnExplode().
RequestSecondaryExplosion()
protected void RequestSecondaryExplosion () inline private
Definition at line 193 of file FireworksLauncher.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), GetSecondaryExplosionDelay(), m_RemainingExplosions, and SpawnSecondaryExplosion().
Referenced by OnExplode(), and SpawnSecondaryExplosion().
SetupLight()
protected void SetupLight (PointLightBase light) inline private
Definition at line 236 of file FireworksLauncher.c.
References ErrorEx, and m_Color.
Referenced by SpawnLight().
SpawnLight()
protected void SpawnLight () inline private
Definition at line 266 of file FireworksLauncher.c.
References GetExplosionPosition(), m_ExplosionLight, and SetupLight().
Referenced by OnExplode().
SpawnSecondaryExplosion()
protected void SpawnSecondaryExplosion () inline private
Definition at line 202 of file FireworksLauncher.c.
References GetExplosionPosition(), m_Events, m_Index, m_Item, and RequestSecondaryExplosion().
Referenced by RequestSecondaryExplosion().
Field Documentation
m_Color
protected string m_Color private
Definition at line 40 of file FireworksLauncher.c.
Referenced by FireworksLauncherClientEvent(), GetExplParticleFromSequence(), and SetupLight().
m_Events
protected ref array<ref FireworksLauncherClientEventBase> m_Events = new ref array<ref FireworksLauncherClientEventBase> private
Definition at line 42 of file FireworksLauncher.c.
Referenced by SpawnSecondaryExplosion().
m_ExplosionLight
protected ExplosionLight m_ExplosionLight private
Definition at line 38 of file FireworksLauncher.c.
Referenced by SpawnLight().
m_ExplosionPos
protected vector m_ExplosionPos private
Definition at line 32 of file FireworksLauncher.c.
Referenced by CalculateExplosionPosition(), and GetExplosionPosition().
m_ExplosionSound
protected EffectSound m_ExplosionSound private
Definition at line 34 of file FireworksLauncher.c.
Referenced by PlayExplosionSound(), and ~FireworksLauncherClientEvent().
m_FireSound
protected EffectSound m_FireSound private
Definition at line 33 of file FireworksLauncher.c.
Referenced by OnFired(), PlayExplosionSound(), and ~FireworksLauncherClientEvent().
m_Index
protected int m_Index private
Definition at line 31 of file FireworksLauncher.c.
Referenced by FireworksLauncherClientEvent(), GetShotPos(), and SpawnSecondaryExplosion().
m_Item
protected FireworksLauncher m_Item private
Definition at line 30 of file FireworksLauncher.c.
Referenced by FireworksLauncherClientEvent(), GetShotPos(), OnFired(), PlayExplosionSound(), and SpawnSecondaryExplosion().
m_ParticleAfterBurnEnd
protected ParticleSource m_ParticleAfterBurnEnd private
Definition at line 39 of file FireworksLauncher.c.
Referenced by OnExplode(), OnFired(), and ~FireworksLauncherClientEvent().
m_ParticleExplosion
protected ParticleSource m_ParticleExplosion private
Definition at line 36 of file FireworksLauncher.c.
Referenced by OnExplode().
m_ParticleShot
protected ParticleSource m_ParticleShot private
Definition at line 35 of file FireworksLauncher.c.
Referenced by OnFired().
m_RemainingExplosions
protected int m_RemainingExplosions = GetSecondaryExplosionCount() private
Definition at line 41 of file FireworksLauncher.c.
Referenced by RequestSecondaryExplosion().
m_ShotDir
protected vector m_ShotDir private
Definition at line 37 of file FireworksLauncher.c.
Referenced by CalculateExplosionPosition(), and OnFired().
m_Timer
protected ref Timer m_Timer = new Timer() private
Definition at line 29 of file FireworksLauncher.c.
Referenced by OnFired().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Gear/Tools/FireworksLauncher.c