var dir_31061108f67df0ec09e3076544c294bd =
[
    [ "conditions", "dir_9eed6bfa079daf99bfc5950bca917a7b.html", "dir_9eed6bfa079daf99bfc5950bca917a7b" ],
    [ "diseases", "dir_19f43f6a65bab7c3e353a2a44635cc79.html", "dir_19f43f6a65bab7c3e353a2a44635cc79" ],
    [ "Antibiotics.c", "_antibiotics_8c.html", "_antibiotics_8c" ],
    [ "BloodRegen.c", "_blood_regen_8c.html", "_blood_regen_8c" ],
    [ "BoneRegen.c", "_bone_regen_8c.html", "_bone_regen_8c" ],
    [ "BreathVapourMdfr.c", "_breath_vapour_mdfr_8c.html", "_breath_vapour_mdfr_8c" ],
    [ "CharcoalMdfr.c", "_charcoal_mdfr_8c.html", "_charcoal_mdfr_8c" ],
    [ "DisinfectMdfr.c", "_disinfect_mdfr_8c.html", "_disinfect_mdfr_8c" ],
    [ "Drowning.c", "_drowning_8c.html", "_drowning_8c" ],
    [ "EpinephrineMdfr.c", "_epinephrine_mdfr_8c.html", "_epinephrine_mdfr_8c" ],
    [ "Flies.c", "_flies_8c.html", "_flies_8c" ],
    [ "Health.c", "_health_8c.html", "_health_8c" ],
    [ "HealthRegen.c", "_health_regen_8c.html", "_health_regen_8c" ],
    [ "HeatComfortMdfr.c", "_heat_comfort_mdfr_8c.html", "_heat_comfort_mdfr_8c" ],
    [ "Hunger.c", "_hunger_8c.html", "_hunger_8c" ],
    [ "ImmuneSystem.c", "_immune_system_8c.html", "_immune_system_8c" ],
    [ "ImmunityBoost.c", "_immunity_boost_8c.html", "_immunity_boost_8c" ],
    [ "Mask.c", "_mask_8c.html", "_mask_8c" ],
    [ "MorphineMdfr.c", "_morphine_mdfr_8c.html", "_morphine_mdfr_8c" ],
    [ "PainKillersMdfr.c", "_pain_killers_mdfr_8c.html", "_pain_killers_mdfr_8c" ],
    [ "Saline.c", "_saline_8c.html", "_saline_8c" ],
    [ "Shock.c", "_shock_8c.html", "_shock_8c" ],
    [ "ShockDamage.c", "_shock_damage_8c.html", "_shock_damage_8c" ],
    [ "Stomach.c", "_stomach_8c.html", "_stomach_8c" ],
    [ "Testing.c", "_testing_8c.html", "_testing_8c" ],
    [ "Thirst.c", "_thirst_8c.html", "_thirst_8c" ],
    [ "Toxicity.c", "_toxicity_8c.html", "_toxicity_8c" ],
    [ "Unconsciousness.c", "_unconsciousness_8c.html", "_unconsciousness_8c" ]
];