DayZ Scripts: ActionDigWorms Class Reference
ActionDigWorms Class Reference
Private Member Functions
void ActionDigWorms ()
override void CreateConditionComponents ()
override bool Can (PlayerBase player, ActionTarget target, ItemBase item, int condition_mask)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override bool HasTarget ()
override void OnFinishProgressServer (ActionData action_data)
void SetDiggingAnimation (ItemBase item)
bool IsTargetFertile (ActionTarget target)
bool IsPlayerOnGround (PlayerBase player)
Constructor & Destructor Documentation
ActionDigWorms()
void ActionDigWorms () inline private
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_MEDIUM.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References IsPlayerOnGround(), and IsTargetFertile().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
References IsPlayerOnGround(), and ActionData::m_Player.
Can()
override bool Can (PlayerBase player, ActionTarget target, ItemBase item, int condition_mask) inline private
References vector::Forward.
CreateConditionComponents()
override void CreateConditionComponents () inline private
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool HasTarget () inline private
IsPlayerOnGround()
bool IsPlayerOnGround (PlayerBase player) inline private
References GetGame(), and CGame::SurfaceY().
Referenced by ActionCondition(), and ActionConditionContinue().
IsTargetFertile()
bool IsTargetFertile (ActionTarget target) inline private
References GetGame(), and CGame::SurfaceGetType().
Referenced by ActionCondition().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References Class::CastTo(), ECE_PLACE_ON_SURFACE, GetGame(), ActionData::m_MainItem, ActionData::m_Player, and m_SpecialtyWeight.
SetDiggingAnimation()
void SetDiggingAnimation (ItemBase item) inline private
References AnimatedActionBase::m_CommandUID, and m_StanceMask.
Referenced by SetupAction().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
References SetDiggingAnimation().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionDigWorms.c