DayZ Scripts: VONManager Class Reference
VONManager Class Reference
Manager class which handles Voice-over-network functionality while player is connected to a server.
Static Private Member Functions
static VONManagerBase GetInstance ()
Main way to access VONManager functionality from script.
static void Init ()
Initializes VONManager, runs when user first connects to a server.
static void CleanupInstance ()
Uninitializes VONManager, runs when user disconnects from server.
static bool IsVONToggled ()
Specifies whether VON mode is toggled or not.
static bool IsVoiceThresholdMinimum ()
Specifies whether user's voice activation threshold value is equal to the minimum voice activation threshold value.
Static Private Attributes
static private ref VONManagerBase m_VONManager = new VONManagerBase()
Detailed Description
Manager class which handles Voice-over-network functionality while player is connected to a server.
Definition at line 300 of file VONManager.c.
Member Function Documentation
CleanupInstance()
static void CleanupInstance () inline static private
Uninitializes VONManager, runs when user disconnects from server.
Definition at line 325 of file VONManager.c.
References m_VONManager.
Referenced by CGame::~CGame().
GetInstance()
static VONManagerBase GetInstance () inline static private
Main way to access VONManager functionality from script.
Returns
Instance of VONManagerImplementation if logged on to server, or VONManagerBase otherwise
Definition at line 308 of file VONManager.c.
References m_VONManager.
Referenced by OnEvent(), MissionBase::OnUpdate(), and ScriptedWidgetEventHandler::OptionsMenuSounds().
Init()
static void Init () inline static private
Initializes VONManager, runs when user first connects to a server.
Definition at line 316 of file VONManager.c.
References m_VONManager, and VONManagerImplementation().
Referenced by CGame::CGame().
IsVoiceThresholdMinimum()
static bool IsVoiceThresholdMinimum () inline static private
Specifies whether user's voice activation threshold value is equal to the minimum voice activation threshold value.
Returns
True if threshold minimum, false otherwise
Definition at line 344 of file VONManager.c.
References Class::CastTo(), GetGame(), GameOptions::GetOptionByType(), and CGame::GetSoundScene().
Referenced by HandleInput(), OnEvent(), and OnVOIPThresholdChanged().
IsVONToggled()
static bool IsVONToggled () inline static private
Specifies whether VON mode is toggled or not.
Returns
True if in Voice Activation mode, False if in Push-to-Talk mode
Definition at line 335 of file VONManager.c.
References VONManagerBase::IsVonToggled(), and m_VONManager.
Field Documentation
m_VONManager
private ref VONManagerBase m_VONManager = new VONManagerBase() static private
Definition at line 302 of file VONManager.c.
Referenced by CleanupInstance(), GetInstance(), Init(), and IsVONToggled().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/VONManager.c