DayZ Scripts: Barrel_ColorBase Class Reference
Barrel_ColorBase Class Reference
Private Member Functions
void Barrel_ColorBase ()
override int GetDamageSystemVersionChange ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
bool IsLocked ()
override void Open ()
void OpenLoad ()
override void Close ()
void CloseLoad ()
override bool IsOpen ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
protected void UpdateVisualState ()
override void OnVariablesSynchronized ()
void SoundBarrelOpenPlay ()
void SoundBarrelClosePlay ()
void Lock (float actiontime)
void Unlock ()
void DetermineAction (PlayerBase player)
void ProduceFertilizer (ItemBase guts, ItemBase plant, PlayerBase player)
void TanPelts (ItemBase lime, PlayerBase player)
void ColourLeatherClothes (ItemBase color_source, PlayerBase player, string color)
void BleachClothes (ItemBase bleach, PlayerBase player)
void ColourClothes (ItemBase rci, ItemBase gci, ItemBase bci, PlayerBase player)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanReleaseCargo (EntityAI attachment)
override bool CanDetachAttachment (EntityAI parent)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override string GetPlaceSoundset ()
override float GetLiquidThroughputCoef ()
override void SetActions ()
override void OnDebugSpawn ()
Private Attributes
private bool m_IsLocked = false
private ref Timer m_BarrelOpener
protected ref RainProcurementComponentBarrel m_RainProcComponent
protected ref OpenableBehaviour m_Openable
ref RainProcurementManager m_RainProcurement
Detailed Description
Definition at line 1 of file Barrel_ColorBase.c.
Constructor & Destructor Documentation
Barrel_ColorBase()
void Barrel_ColorBase () inline private
Definition at line 9 of file Barrel_ColorBase.c.
References m_BarrelOpener, m_HalfExtents, m_Openable, m_RainProcComponent, m_RainProcurement, and Vector().
Member Function Documentation
BleachClothes()
void BleachClothes (ItemBase bleach, PlayerBase player) inline private
Definition at line 360 of file Barrel_ColorBase.c.
References GameConstants::BAREL_BLEACH_PER_CLOTH, GetGame(), and Lock().
Referenced by DetermineAction().
CanDetachAttachment()
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 531 of file Barrel_ColorBase.c.
References GetNumberOfItems().
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 496 of file Barrel_ColorBase.c.
References GetNumberOfItems(), and IsOpen().
CanPutIntoHands()
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 507 of file Barrel_ColorBase.c.
References GetNumberOfItems(), and IsOpen().
CanReceiveItemIntoCargo()
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 518 of file Barrel_ColorBase.c.
References IsOpen().
CanReleaseCargo()
override bool CanReleaseCargo (EntityAI attachment) inline private
Definition at line 526 of file Barrel_ColorBase.c.
References IsOpen().
Close()
override void Close () inline private
Definition at line 84 of file Barrel_ColorBase.c.
References OpenableBehaviour::Close(), m_Openable, m_RainProcComponent, SetTakeable(), SoundSynchRemote(), RainProcurementComponentBase::StopRainProcurement(), and UpdateVisualState().
Referenced by DetermineAction(), and OnWasDetached().
CloseLoad()
void CloseLoad () inline private
Definition at line 94 of file Barrel_ColorBase.c.
References OpenableBehaviour::Close(), m_Openable, m_RainProcComponent, SetTakeable(), RainProcurementComponentBase::StopRainProcurement(), and UpdateVisualState().
Referenced by OnStoreLoad().
ColourClothes()
void ColourClothes (ItemBase rci, ItemBase gci, ItemBase bci, PlayerBase player) inline private
Definition at line 432 of file Barrel_ColorBase.c.
References Math::Clamp(), GetGame(), and Lock().
Referenced by DetermineAction().
ColourLeatherClothes()
void ColourLeatherClothes (ItemBase color_source, PlayerBase player, string color) inline private
Definition at line 309 of file Barrel_ColorBase.c.
References GetGame(), and Lock().
Referenced by DetermineAction().
DetermineAction()
void DetermineAction (PlayerBase player) inline private
Definition at line 183 of file Barrel_ColorBase.c.
References BleachClothes(), Close(), ColourClothes(), ColourLeatherClothes(), GetQuantity(), InventorySlots::GetSlotIdFromString(), ProduceFertilizer(), and TanPelts().
Referenced by ActionCloseBarrel::OnExecuteServer().
GetDamageSystemVersionChange()
override int GetDamageSystemVersionChange () inline private
Definition at line 24 of file Barrel_ColorBase.c.
GetLiquidThroughputCoef()
override float GetLiquidThroughputCoef () inline private
Definition at line 554 of file Barrel_ColorBase.c.
References LIQUID_THROUGHPUT_BARREL.
GetPlaceSoundset()
override string GetPlaceSoundset () inline private
Definition at line 548 of file Barrel_ColorBase.c.
IsLocked()
bool IsLocked () inline private
Definition at line 59 of file Barrel_ColorBase.c.
References m_IsLocked.
Referenced by ActionCloseBarrel::ActionCondition(), and ActionOpenBarrel::ActionCondition().
IsOpen()
override bool IsOpen () inline private
Definition at line 104 of file Barrel_ColorBase.c.
References OpenableBehaviour::IsOpened(), and m_Openable.
Referenced by ActionCloseBarrel::ActionCondition(), ActionOpenBarrel::ActionCondition(), CanPutInCargo(), CanPutIntoHands(), CanReceiveItemIntoCargo(), CanReleaseCargo(), Liquid::CanTransfer(), Edible_Base::ConditionAttach(), Edible_Base::ConditionDetach(), OnVariablesSynchronized(), and UpdateVisualState().
Lock()
void Lock (float actiontime) inline private
Definition at line 171 of file Barrel_ColorBase.c.
References m_BarrelOpener, and m_IsLocked.
Referenced by BleachClothes(), ColourClothes(), ColourLeatherClothes(), ProduceFertilizer(), and TanPelts().
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 569 of file Barrel_ColorBase.c.
References SetQuantityMax().
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 541 of file Barrel_ColorBase.c.
References SetIsPlaceSound().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 36 of file Barrel_ColorBase.c.
References CloseLoad(), OpenLoad(), and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 29 of file Barrel_ColorBase.c.
References OpenableBehaviour::IsOpened(), m_Openable, and Serializer::Write().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Definition at line 137 of file Barrel_ColorBase.c.
References IsBeingPlaced(), IsOpen(), IsPlaceSound(), IsSoundSynchRemote(), m_Initialized, PlayPlaceSound(), SoundBarrelClosePlay(), SoundBarrelOpenPlay(), and UpdateVisualState().
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 109 of file Barrel_ColorBase.c.
References Open().
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 116 of file Barrel_ColorBase.c.
References Close().
Open()
override void Open () inline private
Definition at line 64 of file Barrel_ColorBase.c.
References m_Openable, m_RainProcComponent, OpenableBehaviour::Open(), SetTakeable(), SoundSynchRemote(), RainProcurementComponentBase::StartRainProcurement(), and UpdateVisualState().
Referenced by ActionOpenBarrel::OnExecuteServer(), OnWasAttached(), and Unlock().
OpenLoad()
void OpenLoad () inline private
Definition at line 74 of file Barrel_ColorBase.c.
References m_Openable, m_RainProcComponent, OpenableBehaviour::Open(), SetTakeable(), RainProcurementComponentBase::StartRainProcurement(), and UpdateVisualState().
Referenced by OnStoreLoad().
ProduceFertilizer()
void ProduceFertilizer (ItemBase guts, ItemBase plant, PlayerBase player) inline private
Definition at line 257 of file Barrel_ColorBase.c.
References GameConstants::BAREL_LIME_PER_PLANT, and Lock().
Referenced by DetermineAction().
SetActions()
override void SetActions () inline private
Definition at line 559 of file Barrel_ColorBase.c.
References AddAction().
SoundBarrelClosePlay()
void SoundBarrelClosePlay () inline private
Definition at line 165 of file Barrel_ColorBase.c.
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnVariablesSynchronized().
SoundBarrelOpenPlay()
void SoundBarrelOpenPlay () inline private
Definition at line 159 of file Barrel_ColorBase.c.
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnVariablesSynchronized().
TanPelts()
void TanPelts (ItemBase lime, PlayerBase player) inline private
Definition at line 270 of file Barrel_ColorBase.c.
References GameConstants::BAREL_LIME_PER_PELT, Math::Floor(), g_Game, and Lock().
Referenced by DetermineAction().
Unlock()
void Unlock () inline private
Definition at line 177 of file Barrel_ColorBase.c.
References m_IsLocked, and Open().
UpdateVisualState()
protected void UpdateVisualState () inline private
Definition at line 123 of file Barrel_ColorBase.c.
References IsOpen().
Referenced by Close(), CloseLoad(), OnVariablesSynchronized(), Open(), and OpenLoad().
Field Documentation
m_BarrelOpener
private ref Timer m_BarrelOpener private
Definition at line 4 of file Barrel_ColorBase.c.
Referenced by Barrel_ColorBase(), and Lock().
m_IsLocked
private bool m_IsLocked = false private
Definition at line 3 of file Barrel_ColorBase.c.
Referenced by IsLocked(), Lock(), and Unlock().
m_Openable
protected ref OpenableBehaviour m_Openable private
Definition at line 7 of file Barrel_ColorBase.c.
Referenced by Barrel_ColorBase(), Close(), CloseLoad(), IsOpen(), OnStoreSave(), Open(), and OpenLoad().
m_RainProcComponent
protected ref RainProcurementComponentBarrel m_RainProcComponent private
Definition at line 6 of file Barrel_ColorBase.c.
Referenced by Barrel_ColorBase(), Close(), CloseLoad(), Open(), and OpenLoad().
m_RainProcurement
ref RainProcurementManager m_RainProcurement private
Definition at line 577 of file Barrel_ColorBase.c.
Referenced by Barrel_ColorBase().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Barrel_ColorBase.c