DayZ Scripts: FlashbangEffect Class Reference
FlashbangEffect Class Reference
Private Member Functions
void FlashbangEffect (PlayerBase player, bool visual=true)
void ~FlashbangEffect ()
void SetupFlashbangValues (float progress_mult=1.0, float visual_value_max=1.0, float sound_value_max=1.0)
protected void PlaySound ()
protected void SetAttenuationFilter ()
protected void ResetAttenuationFilter ()
protected void StopSound ()
protected void ClearVisual ()
protected void SetVisual (float val)
void Stop ()
void Update (float deltatime)
Private Attributes
protected const float ALPHA_MIN = 0.0
protected const float ALPHA_MAX = 1.0
protected const float SOUND_DEFER_TIME = 0.4
protected float m_HitDuration
SFX will be played ~0.5s AFTER VFX.
protected float m_BreakPoint
protected float m_TimeActive
protected float m_DayTimeToggle
protected float m_AlphaMaxActual
protected float m_SoundMaxActual
protected float m_ProgressMultiplier
protected bool m_Visual
protected bool m_Initialized
protected PlayerBase m_Player
protected EffectSound m_FlashbangEffectSound
protected float m_SoundStopTime
protected ref Timer m_DeferAttenuation
protected PPERequester_FlashbangEffects m_Requester
Detailed Description
Definition at line 1 of file FlashbangEffect.c.
Constructor & Destructor Documentation
FlashbangEffect()
void FlashbangEffect (PlayerBase player, bool visual = true) inline private
naive time of the day selector
-1: night; 1: day
Definition at line 28 of file FlashbangEffect.c.
References ALPHA_MAX, Class::CastTo(), g_Game, m_AlphaMaxActual, m_BreakPoint, m_DayTimeToggle, m_DeferAttenuation, m_FlashbangEffectSound, m_HitDuration, m_Initialized, m_Player, m_ProgressMultiplier, m_Requester, m_SoundMaxActual, m_Visual, and SOUND_DEFER_TIME.
~FlashbangEffect()
void ~FlashbangEffect () inline private
Definition at line 59 of file FlashbangEffect.c.
References ClearVisual(), SEffectManager::DestroyEffect(), m_DeferAttenuation, m_FlashbangEffectSound, m_Player, m_Visual, and Timer::Stop().
Member Function Documentation
ClearVisual()
protected void ClearVisual () inline private
Definition at line 147 of file FlashbangEffect.c.
References m_Requester.
Referenced by ~FlashbangEffect().
PlaySound()
protected void PlaySound () inline private
Definition at line 94 of file FlashbangEffect.c.
References Math::Clamp(), SEffectManager::CreateSound(), Error(), EffectSound::IsPlaying(), m_FlashbangEffectSound, m_Initialized, m_Player, m_ProgressMultiplier, m_SoundMaxActual, m_SoundStopTime, SetAttenuationFilter(), EffectSound::SetParent(), EffectSound::SetSoundFadeIn(), EffectSound::SetSoundFadeOut(), EffectSound::SetSoundLoop(), EffectSound::SetSoundMaxVolume(), EffectSound::SetSoundWaveKind(), and EffectSound::SoundPlay().
ResetAttenuationFilter()
protected void ResetAttenuationFilter () inline private
Definition at line 134 of file FlashbangEffect.c.
References m_Player.
Referenced by Update().
SetAttenuationFilter()
protected void SetAttenuationFilter () inline private
Definition at line 126 of file FlashbangEffect.c.
References m_DeferAttenuation, and m_Player.
Referenced by PlaySound().
SetupFlashbangValues()
void SetupFlashbangValues (float progress_mult = 1.0, float visual_value_max = 1.0, float sound_value_max = 1.0) inline private
Definition at line 80 of file FlashbangEffect.c.
References m_AlphaMaxActual, m_BreakPoint, m_HitDuration, m_Initialized, m_ProgressMultiplier, and m_SoundMaxActual.
SetVisual()
protected void SetVisual (float val) inline private
Definition at line 155 of file FlashbangEffect.c.
References m_DayTimeToggle, and m_Requester.
Referenced by Update().
Stop()
void Stop () inline private
Definition at line 163 of file FlashbangEffect.c.
References StopSound().
StopSound()
protected void StopSound () inline private
Definition at line 139 of file FlashbangEffect.c.
References m_FlashbangEffectSound, and EffectSound::SoundStop().
Referenced by Stop(), and Update().
Update()
void Update (float deltatime) inline private
Definition at line 168 of file FlashbangEffect.c.
References Math::Clamp(), Error(), Math::InverseLerp(), m_AlphaMaxActual, m_BreakPoint, m_HitDuration, m_Initialized, m_SoundStopTime, m_TimeActive, m_Visual, ResetAttenuationFilter(), SetVisual(), and StopSound().
Field Documentation
ALPHA_MAX
protected const float ALPHA_MAX = 1.0 private
Definition at line 4 of file FlashbangEffect.c.
Referenced by FlashbangEffect().
ALPHA_MIN
protected const float ALPHA_MIN = 0.0 private
Definition at line 3 of file FlashbangEffect.c.
m_AlphaMaxActual
protected float m_AlphaMaxActual private
Definition at line 13 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), SetupFlashbangValues(), and Update().
m_BreakPoint
protected float m_BreakPoint private
Definition at line 9 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), SetupFlashbangValues(), and Update().
m_DayTimeToggle
protected float m_DayTimeToggle private
Definition at line 11 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), and SetVisual().
m_DeferAttenuation
protected ref Timer m_DeferAttenuation private
Definition at line 24 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), SetAttenuationFilter(), and ~FlashbangEffect().
m_FlashbangEffectSound
protected EffectSound m_FlashbangEffectSound private
Definition at line 21 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), PlaySound(), StopSound(), and ~FlashbangEffect().
m_HitDuration
protected float m_HitDuration private
SFX will be played ~0.5s AFTER VFX.
Definition at line 8 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), SetupFlashbangValues(), and Update().
m_Initialized
protected bool m_Initialized private
Definition at line 18 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), PlaySound(), SetupFlashbangValues(), and Update().
m_Player
protected PlayerBase m_Player private
Definition at line 20 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), PlaySound(), ResetAttenuationFilter(), SetAttenuationFilter(), and ~FlashbangEffect().
m_ProgressMultiplier
protected float m_ProgressMultiplier private
Definition at line 15 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), PlaySound(), and SetupFlashbangValues().
m_Requester
protected PPERequester_FlashbangEffects m_Requester private
Definition at line 26 of file FlashbangEffect.c.
Referenced by ClearVisual(), FlashbangEffect(), and SetVisual().
m_SoundMaxActual
protected float m_SoundMaxActual private
Definition at line 14 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), PlaySound(), and SetupFlashbangValues().
m_SoundStopTime
protected float m_SoundStopTime private
Definition at line 22 of file FlashbangEffect.c.
Referenced by PlaySound(), and Update().
m_TimeActive
protected float m_TimeActive private
Definition at line 10 of file FlashbangEffect.c.
Referenced by Update().
m_Visual
protected bool m_Visual private
Definition at line 17 of file FlashbangEffect.c.
Referenced by FlashbangEffect(), Update(), and ~FlashbangEffect().
SOUND_DEFER_TIME
protected const float SOUND_DEFER_TIME = 0.4 private
Definition at line 6 of file FlashbangEffect.c.
Referenced by FlashbangEffect().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/Explosions/FlashbangEffect.c