DayZ Scripts: BiosClientServices Class Reference
BiosClientServices Class Reference
BiosClientServices class provides individual online services.
Private Member Functions
private void BiosClientServices ()
void ~BiosClientServices ()
proto native BiosPrivacyService GetPrivacyService ()
proto native BiosSocialService GetSocialService ()
proto native BiosLobbyService GetLobbyService ()
proto native BiosSessionService GetSessionService ()
proto native BiosPackageService GetPackageService ()
Detailed Description
BiosClientServices class provides individual online services.
Bohemia interactive online services (Bios), Client services API. Use the individual Get methods to access individual service providers. Do not store references to individual service providers, use the Get methods instead. Temporary storage in a function body is fine as long as the owning BiosClientServices object is referenced. Do not attempt to construct this object. It is currently provided by the engine.
Definition at line 9 of file BiosClientServices.c.
Constructor & Destructor Documentation
BiosClientServices()
private void BiosClientServices () inline private
Definition at line 11 of file BiosClientServices.c.
~BiosClientServices()
void ~BiosClientServices () inline private
Definition at line 12 of file BiosClientServices.c.
Member Function Documentation
GetLobbyService()
proto native BiosLobbyService GetLobbyService () private
Referenced by OnlineServices::AutoConnectToEmptyServer(), OnlineServices::GetCachedFavServerInfo(), OnlineServices::GetCurrentServerInfo(), OnlineServices::GetFavoriteServers(), OnlineServices::GetServerModList(), OnlineServices::LoadServers(), OnlineServices::OnAutoConnectToEmptyServer(), and OnlineServices::SetServerFavorited().
GetPackageService()
proto native BiosPackageService GetPackageService () private
Referenced by OnlineServices::CheckUpdate(), and OnlineServices::PromptUpdate().
GetPrivacyService()
proto native BiosPrivacyService GetPrivacyService () private
Referenced by OnlineServices::LoadMPPrivilege(), OnlineServices::LoadPermissions(), and OnlineServices::LoadVoicePrivilege().
GetSessionService()
proto native BiosSessionService GetSessionService () private
Referenced by OnlineServices::EnterGameplaySession(), OnlineServices::GetSession(), OnlineServices::GetSessionHandle(), OnlineServices::LeaveGameplaySession(), OnlineServices::SetGameplayActivity(), OnlineServices::SetMultiplayState(), OnlineServices::SetPendingInviteList(), OnlineServices::SetSessionHandle(), OnlineServices::ShowInviteScreen(), and ClientData::SyncEvent_OnRecievedPlayerList().
GetSocialService()
proto native BiosSocialService GetSocialService () private
Referenced by OnlineServices::LoadFriends(), and OnlineServices::ShowUserProfile().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Services/BiosClientServices.c