DayZ Scripts: SoundLookupTable Class Reference
SoundLookupTable Class Reference
Private Member Functions
void SoundLookupTable ()
void InitTable (string tableCategoryName, string parameterName)
void LoadTable (string soundLookupTableName)
SoundObjectBuilder GetSoundBuilder (int parameterHash)
void AttachmentSoundLookupTable ()
void ImpactSoundLookupTable ()
Private Attributes
private string m_tableCategoryName
private string m_parameterName
private ref map< int, ref array< SoundObjectBuilder > > m_soundBuilders
Detailed Description
Definition at line 2 of file DayZAnimEventMaps.c.
Constructor & Destructor Documentation
SoundLookupTable()
void SoundLookupTable () inline private
Definition at line 4 of file DayZAnimEventMaps.c.
References m_soundBuilders.
Member Function Documentation
AttachmentSoundLookupTable()
void AttachmentSoundLookupTable () inline private
Definition at line 89 of file DayZAnimEventMaps.c.
References InitTable().
GetSoundBuilder()
SoundObjectBuilder GetSoundBuilder (int parameterHash) inline private
Definition at line 53 of file DayZAnimEventMaps.c.
References m_soundBuilders, and Math::RandomInt().
Referenced by DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder(), GetSoundBuilder(), and EntityAI::PlayImpactSound().
ImpactSoundLookupTable()
void ImpactSoundLookupTable () inline private
Definition at line 118 of file DayZAnimEventMaps.c.
References InitTable().
InitTable()
void InitTable (string tableCategoryName, string parameterName) inline private
Definition at line 9 of file DayZAnimEventMaps.c.
References m_parameterName, and m_tableCategoryName.
Referenced by AttachmentSoundLookupTable(), ImpactSoundLookupTable(), ImpactSoundLookupTable(), PlayerVoiceLookupTable(), and SoundLookupTable().
LoadTable()
void LoadTable (string soundLookupTableName) inline private
Definition at line 15 of file DayZAnimEventMaps.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), AnimSoundObjectBuilderBank::GetBuilder(), GetGame(), AnimSoundObjectBuilderBank::GetInstance(), string::Hash(), m_parameterName, m_soundBuilders, m_tableCategoryName, and path.
Referenced by GetActionTable(), GetBuilder(), and GetImpactTable().
Field Documentation
m_parameterName
private string m_parameterName private
Definition at line 74 of file DayZAnimEventMaps.c.
Referenced by InitTable(), and LoadTable().
m_soundBuilders
private ref map<int, ref array<SoundObjectBuilder> > m_soundBuilders private
Definition at line 75 of file DayZAnimEventMaps.c.
Referenced by GetSoundBuilder(), LoadTable(), and SoundLookupTable().
m_tableCategoryName
private string m_tableCategoryName private
Definition at line 73 of file DayZAnimEventMaps.c.
Referenced by InitTable(), and LoadTable().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/DayZAnimEventMaps.c