DayZ Scripts: P:/scripts/4_world/classes/useractionscomponent/actions/interact/actiongetouttransport.c File Reference
actiongetouttransport.c File Reference
Data Structures
class GetOutTransportActionData
Functions
void ActionGetOutTransport ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ProcessGetOutActionData (Car car, GetOutTransportActionData got_action_data)
override void OnStart (ActionData action_data)
override void OnStartServer (ActionData action_data)
void Unhide (PlayerBase player)
override void OnUpdate (ActionData action_data)
override bool CanBeUsedInRestrain ()
override bool CanBeUsedInVehicle ()
override int GetActionCategory ()
override void OnEnd (ActionData action_data)
override void OnEndServer (ActionData action_data)
void ApplyJumpOutDmg (ActionData action_data)
Variables
GetOutTransportActionData m_DmgFactor = 60
int m_ShockFactor = 15
const int LOW_SPEED_VALUE = 20
const int HIGH_SPEED_VALUE = 30
private const int HEALTH_LOW_SPEED_VALUE = 30
private const int HEALTH_HIGH_SPEED_VALUE = 70
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
References HumanCommandVehicle::GetTransport(), and Transport::IsAreaAtDoorFree().
ActionGetOutTransport()
void ActionGetOutTransport ()
References m_StanceMask, and m_Text.
Referenced by ActionConstructor::RegisterActions(), and ManBase::SetActions().
ApplyJumpOutDmg()
void ApplyJumpOutDmg (ActionData action_data)
References Class::CastTo(), HIGH_SPEED_VALUE, LOW_SPEED_VALUE, GetOutTransportActionData::m_CarSpeed, GetOutTransportActionData::m_DmgTaken, ActionData::m_Player, GetOutTransportActionData::m_ShockTaken, Math::RandomInt(), and Math::RandomIntInclusive().
Referenced by OnEndServer().
CanBeUsedInRestrain()
override bool CanBeUsedInRestrain ()
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle ()
CreateActionData()
override ActionData CreateActionData ()
CreateConditionComponents()
override void CreateConditionComponents ()
References m_ConditionItem, and m_ConditionTarget.
GetActionCategory()
override int GetActionCategory ()
References AC_INTERACT.
GetInputType()
override GetInputType ()
HasProgress()
override bool HasProgress ()
OnEnd()
override void OnEnd (ActionData action_data)
References ActionData::m_Player.
OnEndServer()
override void OnEndServer (ActionData action_data)
References ApplyJumpOutDmg(), Class::CastTo(), Math::Clamp(), HEALTH_HIGH_SPEED_VALUE, HEALTH_LOW_SPEED_VALUE, Math::InverseLerp(), GetOutTransportActionData::m_Car, GetOutTransportActionData::m_CarSpeed, GetOutTransportActionData::m_DmgTaken, ActionData::m_Player, and GetOutTransportActionData::m_WasJumpingOut.
OnStart()
override void OnStart (ActionData action_data)
References Class::CastTo(), GetDayZGame(), HumanCommandVehicle::GetOutVehicle(), HumanCommandVehicle::GetTransport(), HumanCommandVehicle::JumpOutVehicle(), ActionData::m_Player, GetOutTransportActionData::m_WasJumpingOut, and ProcessGetOutActionData().
OnStartServer()
override void OnStartServer (ActionData action_data)
References Class::CastTo(), HumanCommandVehicle::GetTransport(), and ActionData::m_Player.
OnUpdate()
override void OnUpdate (ActionData action_data)
References End(), ActionData::m_Player, ActionData::m_State, and UA_START.
ProcessGetOutActionData()
void ProcessGetOutActionData (Car car, GetOutTransportActionData got_action_data)
References GetOutTransportActionData::m_Car, GetOutTransportActionData::m_CarSpeed, m_DmgFactor, GetOutTransportActionData::m_DmgTaken, ActionData::m_Player, m_ShockFactor, GetOutTransportActionData::m_ShockTaken, GetOutTransportActionData::m_StartLocation, and GetOutTransportActionData::m_WasJumpingOut.
Referenced by OnStart().
Unhide()
void Unhide (PlayerBase player)
Variable Documentation
HEALTH_HIGH_SPEED_VALUE
private const int HEALTH_HIGH_SPEED_VALUE = 70
Referenced by OnEndServer().
HEALTH_LOW_SPEED_VALUE
private const int HEALTH_LOW_SPEED_VALUE = 30
Referenced by OnEndServer().
HIGH_SPEED_VALUE
const int HIGH_SPEED_VALUE = 30
Referenced by ApplyJumpOutDmg().
LOW_SPEED_VALUE
const int LOW_SPEED_VALUE = 20
Referenced by ApplyJumpOutDmg().
m_DmgFactor
GetOutTransportActionData m_DmgFactor = 60
Referenced by ProcessGetOutActionData().
m_ShockFactor
int m_ShockFactor = 15
Referenced by ProcessGetOutActionData().