DayZ Scripts: SmptAnimMetaBase Class Reference
SmptAnimMetaBase Class Reference
Private Member Functions
void ~SmptAnimMetaFB ()
override void Init (ParamsReadContext ctx, SymptomManager manager, PlayerBase player)
override EAnimPlayState Play ()
Private Attributes
int m_StanceMask
float m_Duration
Constructor & Destructor Documentation
~SmptAnimMetaFB()
void ~SmptAnimMetaFB () inline private
References DayZPlayer::m_isFBsymptomPlaying, and m_Player.
Member Function Documentation
Init()
override void Init (ParamsReadContext ctx, SymptomManager manager, PlayerBase player) inline private
References m_AnimID, m_Duration, m_StanceMask, and DayZPlayerSyncJunctures::ReadPlayerSymptomFBParams().
Referenced by SymptomManager::SetAnimation().
Play()
override EAnimPlayState Play () inline private
References m_AnimID, m_Canceled, m_Duration, DayZPlayer::m_isFBsymptomPlaying, m_IsPlaying, m_Player, and m_StanceMask.
Referenced by PlayRequest().
Field Documentation
m_Duration
float m_Duration private
m_StanceMask
int m_StanceMask private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerSymptoms/SmptAnimMeta.c