DayZ Scripts: GearChangeActionCallback Class Reference
GearChangeActionCallback Class Reference
Private Member Functions
void SetVehicleCommand (HumanCommandVehicle hcv)
override void OnFinish (bool pCanceled)
Private Attributes
HumanCommandVehicle m_hcv
Member Function Documentation
OnFinish()
override void OnFinish (bool pCanceled) inline private
References GetHuman(), and HumanCommandVehicle::SetClutchState().
SetVehicleCommand()
void SetVehicleCommand (HumanCommandVehicle hcv) inline private
References HumanCommandVehicle::SetClutchState().
Referenced by DayZPlayer::CommandHandler().
Field Documentation
m_hcv
HumanCommandVehicle m_hcv private
The documentation for this class was generated from the following file:
P:/scripts/4_world/entities/dayzplayerimplementvehicle.c