DayZ Scripts: PCOHandlerStats Class Reference
PCOHandlerStats Class Reference
Private Member Functions
void PCOHandlerStats ()
void RegisterPCO (PlayerStatsPCO_Base pco)
PlayerStatsPCO_Base GetPCO (int version=-1)
Private Attributes
ref map< int, ref PlayerStatsPCO_Base > m_PCOs = new map<int, ref PlayerStatsPCO_Base>
int m_HighestVersion
Detailed Description
Definition at line 3 of file PlayerStatsPCO.c.
Constructor & Destructor Documentation
PCOHandlerStats()
void PCOHandlerStats () inline private
Definition at line 8 of file PlayerStatsPCO.c.
References RegisterPCO().
Member Function Documentation
GetPCO()
PlayerStatsPCO_Base GetPCO (int version = -1) inline private
Definition at line 27 of file PlayerStatsPCO.c.
References m_HighestVersion, and m_PCOs.
Referenced by PlayerStats::GetPCO().
RegisterPCO()
void RegisterPCO (PlayerStatsPCO_Base pco) inline private
Definition at line 15 of file PlayerStatsPCO.c.
References PlayerStatsPCO_Base::GetVersion(), m_HighestVersion, and m_PCOs.
Referenced by PCOHandlerStats().
Field Documentation
m_HighestVersion
int m_HighestVersion private
Definition at line 6 of file PlayerStatsPCO.c.
Referenced by GetPCO(), and RegisterPCO().
m_PCOs
ref map<int, ref PlayerStatsPCO_Base> m_PCOs = new map<int, ref PlayerStatsPCO_Base> private
Definition at line 5 of file PlayerStatsPCO.c.
Referenced by GetPCO(), and RegisterPCO().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerStats/PlayerStatsPCO.c