DayZ Scripts: P:/scripts/4_World/Entities/ItemBase/BaseBuildingBase.c File Reference
BaseBuildingBase.c File Reference
Data Structures
class ItemBase
Functions
class BaseBuildingBase extends ItemBase bsbDebugPrint (string s)
void BaseBuildingBase ()
override void EEDelete (EntityAI parent)
override string GetInvulnerabilityTypeString ()
override bool CanObstruct ()
override int GetHideIconMask ()
void SynchronizeBaseState ()
override void OnVariablesSynchronized ()
protected void OnSynchronizedClient ()
void RegisterPartForSync (int part_id)
void UnregisterPartForSync (int part_id)
bool IsPartBuildInSyncData (int part_id)
protected void RegisterActionForSync (int part_id, int action_id)
protected void ResetActionSyncData ()
protected void SetActionFromSyncData ()
void SetPartFromSyncData (ConstructionPart part)
void SetPartsFromSyncData ()
protected ConstructionPart GetConstructionPartById (int id)
bool HasBase ()
void SetBaseState (bool has_base)
override bool IsDeployable ()
bool IsOpened ()
ItemBase CreateConstructionKit ()
void CreateConstructionKitInHands (notnull PlayerBase player)
protected vector GetKitSpawnPosition ()
protected string GetConstructionKitType ()
void DestroyConstructionKit (ItemBase construction_kit)
void DestroyConstruction ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
void SetPartsAfterStoreLoad ()
override void OnCreatePhysics ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEOnAfterLoad ()
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
protected void OnSetSlotLock (int slotId, bool locked, bool was_locked)
override bool IgnoreOutOfReachCondition ()
void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
void OnPartBuiltClient (string part_name, int action_id)
void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
void OnPartDismantledClient (string part_name, int action_id)
void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
void OnPartDestroyedClient (string part_name, int action_id)
void InitBaseState ()
void InitVisuals ()
void UpdateVisuals ()
void UpdateAttachmentVisuals (string slot_name, bool is_locked)
void UpdatePhysics ()
void UpdateAttachmentPhysics (string slot_name, bool is_locked)
protected void UpdateNavmesh ()
override bool CanUseConstruction ()
override bool CanUseConstructionBuild ()
protected bool IsAttachmentSlotLocked (EntityAI attachment)
protected bool IsAttachmentSlotLocked (string slot_name)
void GetAttachmentSlots (EntityAI entity, out array< string > attachment_slots)
bool CheckSlotVerticalDistance (int slot_id, PlayerBase player)
protected bool CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player)
protected bool CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player)
void ConstructionInit ()
Construction GetConstruction ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
bool HasAttachmentsBesidesBase ()
override bool ShowZonesHealth ()
override bool IsTakeable ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool IsFacingPlayer (PlayerBase player, string selection)
override bool IsPlayerInside (PlayerBase player, string selection)
bool MustBeBuiltFromOutside ()
Some buildings can only be built from outside.
bool IsFacingCamera (string selection)
bool PerformRoofCheckForBase (string partName, PlayerBase player, out bool result)
bool HasProperDistance (string selection, PlayerBase player)
bool CanFoldBaseBuildingObject ()
ItemBase FoldBaseBuildingObject ()
void CreateAreaDamage (string slot_name, float rotation_angle=0)
void CalcDamageAreaRotation (float angle_deg, out vector center, out vector orientation)
void DestroyAreaDamage (string slot_name)
override bool IsIgnoredByConstruction ()
protected void SoundBuildStart (string part_name)
protected void SoundDismantleStart (string part_name)
protected void SoundDestroyStart (string part_name)
protected string GetBuildSoundByMaterial (string part_name)
protected string GetDismantleSoundByMaterial (string part_name)
void CheckForHybridAttachments (EntityAI item, string slot_name)
override int GetDamageSystemVersionChange ()
override void SetActions ()
protected void DebugCustomState ()
array< string > OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
override void OnDebugSpawn ()
void FullyBuild ()
void bsbDebugSpam (string s)
Variables
const string ANIMATION_DEPLOYED = "Deployed"
float m_ConstructionKitHealth
ref Construction m_Construction
bool m_HasBase
int m_SyncParts01
int m_SyncParts02
int m_SyncParts03
int m_InteractedPartId
int m_PerformedActionId
const string SOUND_BUILD_WOOD_LOG = "putDown_WoodLog_SoundSet"
const string SOUND_BUILD_WOOD_PLANK = "putDown_WoodPlank_SoundSet"
const string SOUND_BUILD_WOOD_STAIRS = "putDown_WoodStairs_SoundSet"
const string SOUND_BUILD_METAL = "putDown_MetalPlank_SoundSet"
const string SOUND_BUILD_WIRE = "putDown_BarbedWire_SoundSet"
const string SOUND_DISMANTLE_WOOD_LOG = "Crash_WoodPlank_SoundSet"
const string SOUND_DISMANTLE_WOOD_PLANK = "Crash_WoodPlank_SoundSet"
const string SOUND_DISMANTLE_WOOD_STAIRS = "Crash_WoodPlank_SoundSet"
const string SOUND_DISMANTLE_METAL = "Crash_MetalPlank_SoundSet"
const string SOUND_DISMANTLE_WIRE = "putDown_BarbedWire_SoundSet"
protected EffectSound m_Sound
ref map< string, ref AreaDamageManager > m_DamageTriggers
ref array< string > m_HybridAttachments
ref array< string > m_Mountables
Function Documentation
AfterStoreLoad()
override void AfterStoreLoad ()
BaseBuildingBase()
void BaseBuildingBase ()
bsbDebugPrint()
class BaseBuildingBase extends ItemBase bsbDebugPrint (string s)
Referenced by AddToConstructedParts(), BaseBuildingBase::AfterStoreLoad(), BuildPartServer(), DestroyConnectedParts(), ItemBase::DestroyConstruction(), DestroyMaterialsServer(), DestroyPartServer(), DismantlePartServer(), DropNonUsableMaterialsServer(), HideConstructionPart(), InitBaseState(), ItemBase::InitBaseState(), InitVisuals(), ItemBase::InitVisuals(), LockServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), ItemBase::OnSetSlotLock(), BaseBuildingBase::OnStoreLoad(), BaseBuildingBase::OnStoreSave(), ItemBase::OnVariablesSynchronized(), OnVariablesSynchronized(), RemoveFromConstructedParts(), ConstructionPart::SetBuiltState(), SetLockOnAttachedMaterials(), ItemBase::SetMountedState(), ItemBase::SetPartFromSyncData(), ConstructionPart::SetRequestBuiltState(), ShowConstructionPart(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), Synchronize(), UnlockServer(), ItemBase::UpdateAttachmentPhysics(), UpdateConstructionParts(), UpdatePhysics(), ItemBase::UpdatePhysics(), and UpdateVisuals().
bsbDebugSpam()
void bsbDebugSpam (string s)
Referenced by ItemBase::SetPartFromSyncData().
CalcDamageAreaRotation()
void CalcDamageAreaRotation (float angle_deg, out vector center, out vector orientation)
Referenced by ItemBase::CreateAreaDamage().
CanFoldBaseBuildingObject()
bool CanFoldBaseBuildingObject ()
CanObstruct()
override bool CanObstruct ()
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent)
CanPutIntoHands()
override bool CanPutIntoHands (EntityAI parent)
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
CanRemoveFromCargo()
override bool CanRemoveFromCargo (EntityAI parent)
CanUseConstruction()
override bool CanUseConstruction ()
Referenced by IEntity::CanProxyObstruct().
CanUseConstructionBuild()
override bool CanUseConstructionBuild ()
CheckForHybridAttachments()
void CheckForHybridAttachments (EntityAI item, string slot_name)
Referenced by ItemBase::EEItemAttached().
CheckLevelVerticalDistance()
protected bool CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player)
CheckMemoryPointVerticalDistance()
protected bool CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player)
CheckSlotVerticalDistance()
bool CheckSlotVerticalDistance (int slot_id, PlayerBase player)
ConstructionInit()
void ConstructionInit ()
Referenced by ItemBase::BaseBuildingBase(), and ItemBase::OnCreatePhysics().
CreateAreaDamage()
void CreateAreaDamage (string slot_name, float rotation_angle = 0)
CreateConstructionKit()
ItemBase CreateConstructionKit ()
Referenced by ItemBase::FoldBaseBuildingObject(), and ItemBase::OnPartBuiltServer().
CreateConstructionKitInHands()
void CreateConstructionKitInHands (notnull PlayerBase player)
DebugCustomState()
protected void DebugCustomState ()
Referenced by ItemBase::EEInit().
DestroyAreaDamage()
void DestroyAreaDamage (string slot_name)
DestroyConstruction()
void DestroyConstruction ()
Referenced by ItemBase::FoldBaseBuildingObject(), ItemBase::OnPartDestroyedServer(), and ItemBase::OnPartDismantledServer().
DestroyConstructionKit()
void DestroyConstructionKit (ItemBase construction_kit)
EEDelete()
override void EEDelete (EntityAI parent)
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
EEInit()
override void EEInit ()
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name)
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name)
EEOnAfterLoad()
override void EEOnAfterLoad ()
FoldBaseBuildingObject()
ItemBase FoldBaseBuildingObject ()
FullyBuild()
void FullyBuild ()
Referenced by ItemBase::OnDebugSpawn().
GetAttachmentSlots()
void GetAttachmentSlots (EntityAI entity, out array< string > attachment_slots)
Referenced by ItemBase::UpdatePhysics(), and ItemBase::UpdateVisuals().
GetBuildSoundByMaterial()
protected string GetBuildSoundByMaterial (string part_name)
Referenced by ItemBase::SoundBuildStart().
GetConstruction()
Construction GetConstruction ()
Referenced by BaseBuildingBase::AfterStoreLoad(), BaseBuildingBase::CanDisplayAttachmentCategory(), BaseBuildingBase::CanDisplayAttachmentSlot(), BaseBuildingBase::CanReceiveAttachment(), BaseBuildingBase::CheckGateState(), BaseBuildingBase::CheckSlotVerticalDistance(), ItemBase::ConstructionInit(), ItemBase::CreateAreaDamage(), ItemBase::EEHealthLevelChanged(), ItemBase::FullyBuild(), BaseBuildingBase::GateAttachmentConditions(), BaseBuildingBase::GateAttachmentsSanityCheck(), ItemBase::GetBuildSoundByMaterial(), ItemBase::GetConstructionPartById(), ItemBase::GetDismantleSoundByMaterial(), ItemBase::InitBaseState(), ItemBase::InitVisuals(), ItemBase::OnPartBuiltServer(), BaseBuildingBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), BaseBuildingBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), BaseBuildingBase::OnPartDismantledServer(), ItemBase::SetPartFromSyncData(), ItemBase::SetPartsAfterStoreLoad(), ItemBase::SetPartsFromSyncData(), ItemBase::UpdatePhysics(), ItemBase::UpdateVisuals(), and BaseBuildingBase::UpdateVisuals().
GetConstructionKitType()
protected string GetConstructionKitType ()
GetConstructionPartById()
protected ConstructionPart GetConstructionPartById (int id)
Referenced by ItemBase::SetActionFromSyncData().
GetDamageSystemVersionChange()
override int GetDamageSystemVersionChange ()
GetDismantleSoundByMaterial()
protected string GetDismantleSoundByMaterial (string part_name)
Referenced by ItemBase::SoundDestroyStart(), and ItemBase::SoundDismantleStart().
GetHideIconMask()
override int GetHideIconMask ()
GetInvulnerabilityTypeString()
override string GetInvulnerabilityTypeString ()
Referenced by FireplaceBase::BarrelHoles_ColorBase(), ItemBase::BaseBuildingBase(), BuildPartServer(), and ItemBase::TentBase().
GetKitSpawnPosition()
protected vector GetKitSpawnPosition ()
HasAttachmentsBesidesBase()
bool HasAttachmentsBesidesBase ()
HasBase()
bool HasBase ()
Referenced by BaseBuildingBase::CanDisplayAttachmentCategory(), ItemBase::CanFoldBaseBuildingObject(), BaseBuildingBase::CanPutIntoHands(), BaseBuildingBase::CanReceiveAttachment(), ItemBase::HasAttachmentsBesidesBase(), ItemBase::InitVisuals(), ItemBase::UpdatePhysics(), and ItemBase::UpdateVisuals().
HasProperDistance()
bool HasProperDistance (string selection, PlayerBase player)
IgnoreOutOfReachCondition()
override bool IgnoreOutOfReachCondition ()
InitBaseState()
void InitBaseState ()
InitVisuals()
void InitVisuals ()
IsAttachmentSlotLocked() [1/2]
protected bool IsAttachmentSlotLocked (EntityAI attachment)
Referenced by ItemBase::UpdatePhysics(), and ItemBase::UpdateVisuals().
IsAttachmentSlotLocked() [2/2]
protected bool IsAttachmentSlotLocked (string slot_name)
IsDeployable()
override bool IsDeployable ()
IsFacingCamera()
bool IsFacingCamera (string selection)
IsFacingPlayer()
override bool IsFacingPlayer (PlayerBase player, string selection)
IsIgnoredByConstruction()
override bool IsIgnoredByConstruction ()
IsOpened()
bool IsOpened ()
Referenced by BaseBuildingBase::AfterStoreLoad(), PluginBase::EditorToggle(), PluginBase::EditorUpdate(), and LayoutHolder::Toggle().
IsPartBuildInSyncData()
bool IsPartBuildInSyncData (int part_id)
Referenced by ItemBase::SetPartFromSyncData().
IsPlayerInside()
override bool IsPlayerInside (PlayerBase player, string selection)
IsTakeable()
override bool IsTakeable ()
MustBeBuiltFromOutside()
bool MustBeBuiltFromOutside ()
Some buildings can only be built from outside.
OnCreatePhysics()
override void OnCreatePhysics ()
OnDebugSpawn()
override void OnDebugSpawn ()
OnDebugSpawnBuildExcludes()
array< string > OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
OnPartBuiltClient()
void OnPartBuiltClient (string part_name, int action_id)
Referenced by ItemBase::SetActionFromSyncData().
OnPartBuiltServer()
void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
OnPartDestroyedClient()
void OnPartDestroyedClient (string part_name, int action_id)
Referenced by ItemBase::SetActionFromSyncData().
OnPartDestroyedServer()
void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false)
OnPartDismantledClient()
void OnPartDismantledClient (string part_name, int action_id)
Referenced by ItemBase::SetActionFromSyncData().
OnPartDismantledServer()
void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
OnSetSlotLock()
protected void OnSetSlotLock (int slotId, bool locked, bool was_locked)
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
OnSynchronizedClient()
protected void OnSynchronizedClient ()
Referenced by ItemBase::OnVariablesSynchronized().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
PerformRoofCheckForBase()
bool PerformRoofCheckForBase (string partName, PlayerBase player, out bool result)
RegisterActionForSync()
protected void RegisterActionForSync (int part_id, int action_id)
Referenced by ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), and ItemBase::OnPartDismantledServer().
RegisterPartForSync()
void RegisterPartForSync (int part_id)
Referenced by ItemBase::OnPartBuiltServer().
ResetActionSyncData()
protected void ResetActionSyncData ()
Referenced by ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), and ItemBase::OnPartDismantledServer().
SetActionFromSyncData()
protected void SetActionFromSyncData ()
Referenced by ItemBase::OnSynchronizedClient().
SetActions()
override void SetActions ()
SetBaseState()
void SetBaseState (bool has_base)
Referenced by ItemBase::OnPartBuiltServer(), and ItemBase::SetPartsAfterStoreLoad().
SetPartFromSyncData()
void SetPartFromSyncData (ConstructionPart part)
Referenced by ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), and ItemBase::SetPartsFromSyncData().
SetPartsAfterStoreLoad()
void SetPartsAfterStoreLoad ()
Referenced by ItemBase::AfterStoreLoad(), ItemBase::EEOnAfterLoad(), and ItemBase::OnCreatePhysics().
SetPartsFromSyncData()
void SetPartsFromSyncData ()
Referenced by ItemBase::OnSynchronizedClient(), and ItemBase::SetPartsAfterStoreLoad().
ShowZonesHealth()
override bool ShowZonesHealth ()
SoundBuildStart()
protected void SoundBuildStart (string part_name)
Referenced by ItemBase::OnPartBuiltClient().
SoundDestroyStart()
protected void SoundDestroyStart (string part_name)
Referenced by ItemBase::OnPartDestroyedClient().
SoundDismantleStart()
protected void SoundDismantleStart (string part_name)
Referenced by ItemBase::OnPartDismantledClient().
SynchronizeBaseState()
void SynchronizeBaseState ()
Referenced by BaseBuildingBase::CloseFence(), ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), BaseBuildingBase::OpenFence(), and ItemBase::SetPartsAfterStoreLoad().
UnregisterPartForSync()
void UnregisterPartForSync (int part_id)
Referenced by ItemBase::OnPartDestroyedServer(), and ItemBase::OnPartDismantledServer().
UpdateAttachmentPhysics()
void UpdateAttachmentPhysics (string slot_name, bool is_locked)
Referenced by ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), ItemBase::OnSetSlotLock(), and ItemBase::UpdatePhysics().
UpdateAttachmentVisuals()
void UpdateAttachmentVisuals (string slot_name, bool is_locked)
Referenced by ItemBase::OnSetSlotLock(), and ItemBase::UpdateVisuals().
UpdateNavmesh()
protected void UpdateNavmesh ()
Referenced by BaseBuildingBase::CloseFence(), ItemBase::InitBaseState(), ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), BaseBuildingBase::OpenFence(), ItemBase::SetPartsFromSyncData(), and ItemBase::UpdatePhysics().
UpdatePhysics()
void UpdatePhysics ()
UpdateVisuals()
void UpdateVisuals ()
Variable Documentation
ANIMATION_DEPLOYED
const string ANIMATION_DEPLOYED = "Deployed"
Referenced by ItemBase::InitVisuals(), ItemBase::SetPartFromSyncData(), ItemBase::UpdatePhysics(), and ItemBase::UpdateVisuals().
m_Construction
ref Construction m_Construction
Referenced by ItemBase::ConstructionInit(), and ItemBase::GetConstruction().
m_ConstructionKitHealth
float m_ConstructionKitHealth
Referenced by ItemBase::CreateConstructionKit(), ItemBase::CreateConstructionKitInHands(), and ItemBase::DestroyConstructionKit().
m_DamageTriggers
ref map<string, ref AreaDamageManager> m_DamageTriggers
Referenced by ItemBase::BaseBuildingBase(), ItemBase::CreateAreaDamage(), ItemBase::DestroyAreaDamage(), and ItemBase::EEDelete().
m_HasBase
bool m_HasBase
Referenced by ItemBase::HasBase(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), and ItemBase::SetBaseState().
m_HybridAttachments
ref array<string> m_HybridAttachments
Referenced by ItemBase::BaseBuildingBase(), and ItemBase::CheckForHybridAttachments().
m_InteractedPartId
int m_InteractedPartId
Referenced by ItemBase::RegisterActionForSync(), ItemBase::ResetActionSyncData(), and ItemBase::SetActionFromSyncData().
m_Mountables
ref array<string> m_Mountables
Referenced by ItemBase::BaseBuildingBase(), and ItemBase::UpdateAttachmentPhysics().
m_PerformedActionId
int m_PerformedActionId
Referenced by ItemBase::RegisterActionForSync(), ItemBase::ResetActionSyncData(), and ItemBase::SetActionFromSyncData().
m_Sound
protected EffectSound m_Sound
m_SyncParts01
int m_SyncParts01
Referenced by ItemBase::IsPartBuildInSyncData(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::RegisterPartForSync(), and ItemBase::UnregisterPartForSync().
m_SyncParts02
int m_SyncParts02
Referenced by ItemBase::IsPartBuildInSyncData(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::RegisterPartForSync(), and ItemBase::UnregisterPartForSync().
m_SyncParts03
int m_SyncParts03
Referenced by ItemBase::IsPartBuildInSyncData(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::RegisterPartForSync(), and ItemBase::UnregisterPartForSync().
SOUND_BUILD_METAL
const string SOUND_BUILD_METAL = "putDown_MetalPlank_SoundSet"
Referenced by ItemBase::GetBuildSoundByMaterial().
SOUND_BUILD_WIRE
const string SOUND_BUILD_WIRE = "putDown_BarbedWire_SoundSet"
Referenced by ItemBase::GetBuildSoundByMaterial().
SOUND_BUILD_WOOD_LOG
const string SOUND_BUILD_WOOD_LOG = "putDown_WoodLog_SoundSet"
Referenced by ItemBase::GetBuildSoundByMaterial().
SOUND_BUILD_WOOD_PLANK
const string SOUND_BUILD_WOOD_PLANK = "putDown_WoodPlank_SoundSet"
Referenced by ItemBase::GetBuildSoundByMaterial().
SOUND_BUILD_WOOD_STAIRS
const string SOUND_BUILD_WOOD_STAIRS = "putDown_WoodStairs_SoundSet"
Referenced by ItemBase::GetBuildSoundByMaterial().
SOUND_DISMANTLE_METAL
const string SOUND_DISMANTLE_METAL = "Crash_MetalPlank_SoundSet"
Referenced by ItemBase::GetDismantleSoundByMaterial().
SOUND_DISMANTLE_WIRE
const string SOUND_DISMANTLE_WIRE = "putDown_BarbedWire_SoundSet"
Referenced by ItemBase::GetDismantleSoundByMaterial().
SOUND_DISMANTLE_WOOD_LOG
const string SOUND_DISMANTLE_WOOD_LOG = "Crash_WoodPlank_SoundSet"
Referenced by ItemBase::GetDismantleSoundByMaterial().
SOUND_DISMANTLE_WOOD_PLANK
const string SOUND_DISMANTLE_WOOD_PLANK = "Crash_WoodPlank_SoundSet"
Referenced by ItemBase::GetDismantleSoundByMaterial().
SOUND_DISMANTLE_WOOD_STAIRS
const string SOUND_DISMANTLE_WOOD_STAIRS = "Crash_WoodPlank_SoundSet"
Referenced by ItemBase::GetDismantleSoundByMaterial().