DayZ Scripts: RainProcurementHandler Class Reference
RainProcurementHandler Class Reference
Private Member Functions
void RainProcurementHandler (MissionBaseWorld mission)
void QueueStart (RainProcurementComponentBase component)
void QueueStop (RainProcurementComponentBase component)
void Update (float timeslice)
protected bool ProcessBatch ()
returns 'true' when all the batches are finished
protected void Cleanup ()
protected void Reset ()
protected void HandleChangedComponents ()
protected void CheckUpdating ()
float GetLiquidAmountCoef ()
float DetermineAmountCoef ()
scalable on handler level
Private Attributes
protected MissionBaseWorld m_Mission
protected ref set< RainProcurementComponentBase > m_ActiveComponents
protected ref set< RainProcurementComponentBase > m_ChangedQueue
protected ref set< int > m_CleanupQueue
protected const int UPDATE_BATCH_SIZE = 20
const int UPDATE_TIME = 10
protected bool m_Update
protected bool m_ProcessComponents
protected bool m_ProcessingFinished
protected int m_NextToProcessIdx
protected float m_UpdateTimer
protected float m_LiquidAmountCoef
Constructor & Destructor Documentation
RainProcurementHandler()
void RainProcurementHandler (MissionBaseWorld mission) inline private
References m_ActiveComponents, m_ChangedQueue, m_CleanupQueue, m_Mission, m_NextToProcessIdx, m_ProcessComponents, m_ProcessingFinished, m_Update, m_UpdateTimer, and mission.
Member Function Documentation
CheckUpdating()
protected void CheckUpdating () inline private
References m_ActiveComponents, and m_Update.
Referenced by Update().
Cleanup()
protected void Cleanup () inline private
References m_ActiveComponents, and m_CleanupQueue.
Referenced by Update().
DetermineAmountCoef()
float DetermineAmountCoef () inline private
scalable on handler level
References WeatherPhenomenon::GetActual(), GetGame(), Weather::GetRain(), and CGame::GetWeather().
Referenced by Update().
GetLiquidAmountCoef()
float GetLiquidAmountCoef () inline private
References m_LiquidAmountCoef.
HandleChangedComponents()
protected void HandleChangedComponents () inline private
References component, m_ActiveComponents, and m_ChangedQueue.
Referenced by Update().
ProcessBatch()
protected bool ProcessBatch () inline private
returns 'true' when all the batches are finished
References Math::Clamp(), int, m_ActiveComponents, m_CleanupQueue, m_LiquidAmountCoef, m_NextToProcessIdx, m_UpdateTimer, and UPDATE_BATCH_SIZE.
Referenced by Update().
QueueStart()
void QueueStart (RainProcurementComponentBase component) inline private
References component, m_ChangedQueue, and m_Update.
Referenced by RainProcurementComponentBase::StartRainProcurement().
QueueStop()
void QueueStop (RainProcurementComponentBase component) inline private
References component, m_ChangedQueue, and m_Update.
Referenced by RainProcurementComponentBase::StopRainProcurement().
Reset()
protected void Reset () inline private
References m_ProcessComponents, m_ProcessingFinished, and m_UpdateTimer.
Referenced by Update().
Update()
void Update (float timeslice) inline private
References CheckUpdating(), Cleanup(), DetermineAmountCoef(), HandleChangedComponents(), m_LiquidAmountCoef, m_ProcessComponents, m_ProcessingFinished, m_Update, m_UpdateTimer, ProcessBatch(), Reset(), and UPDATE_TIME.
Field Documentation
m_ActiveComponents
protected ref set<RainProcurementComponentBase> m_ActiveComponents private
Referenced by CheckUpdating(), Cleanup(), HandleChangedComponents(), ProcessBatch(), and RainProcurementHandler().
m_ChangedQueue
protected ref set<RainProcurementComponentBase> m_ChangedQueue private
Referenced by HandleChangedComponents(), QueueStart(), QueueStop(), and RainProcurementHandler().
m_CleanupQueue
protected ref set<int> m_CleanupQueue private
Referenced by Cleanup(), ProcessBatch(), and RainProcurementHandler().
m_LiquidAmountCoef
protected float m_LiquidAmountCoef private
Referenced by GetLiquidAmountCoef(), ProcessBatch(), and Update().
m_Mission
protected MissionBaseWorld m_Mission private
Referenced by RainProcurementHandler().
m_NextToProcessIdx
protected int m_NextToProcessIdx private
Referenced by ProcessBatch(), and RainProcurementHandler().
m_ProcessComponents
protected bool m_ProcessComponents private
Referenced by RainProcurementHandler(), Reset(), and Update().
m_ProcessingFinished
protected bool m_ProcessingFinished private
Referenced by RainProcurementHandler(), Reset(), and Update().
m_Update
protected bool m_Update private
Referenced by CheckUpdating(), QueueStart(), QueueStop(), RainProcurementHandler(), and Update().
m_UpdateTimer
protected float m_UpdateTimer private
Referenced by ProcessBatch(), RainProcurementHandler(), Reset(), and Update().
UPDATE_BATCH_SIZE
protected const int UPDATE_BATCH_SIZE = 20 private
Referenced by ProcessBatch().
UPDATE_TIME
const int UPDATE_TIME = 10 private
Referenced by Update().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/RainProcurementHandler.c