DayZ Scripts: PlayerAgentPool Class Reference
PlayerAgentPool Class Reference
Private Member Functions
void PlayerAgentPool (PlayerBase player)
void ~PlayerAgentPool ()
int GetStorageVersion ()
void PrintAgents ()
void ImmuneSystemTick (float value, float deltaT)
void GrowAgents (float deltaT)
void OnStoreSave (ParamsWriteContext ctx)
bool OnStoreLoad (ParamsReadContext ctx, int version)
void DigestAgent (int agent_id, float count)
void AddAgent (int agent_id, float count)
void RemoveAgent (int agent_id)
void RemoveAllAgents ()
int GetAgents ()
int GetSingleAgentCount (int agent_id)
float GetTotalAgentCount ()
void SpawnAgents (float deltaT)
void SetAgentCount (int agent_id, float count)
void AntibioticsAttack (float attack_value)
void RemoteGrowRequestDebug (ParamsReadContext ctx)
void GetDebugObject (array< ref Param > object_out)
Private Attributes
ref map< int, float > m_VirusPool = new map<int,float>
ref array< int > m_VirusPoolArray = new array<int>
float m_LastTicked = 0
float m_TotalAgentCount
PlayerBase m_Player
int m_AgentMask
const int STORAGE_VERSION = 100
PluginTransmissionAgents m_PluginTransmissionAgents = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents))
Detailed Description
Definition at line 1 of file PlayerAgentPool.c.
Constructor & Destructor Documentation
PlayerAgentPool()
void PlayerAgentPool (PlayerBase player) inline private
Definition at line 14 of file PlayerAgentPool.c.
References m_Player.
~PlayerAgentPool()
void ~PlayerAgentPool () inline private
Definition at line 19 of file PlayerAgentPool.c.
Member Function Documentation
AddAgent()
void AddAgent (int agent_id, float count) inline private
Definition at line 139 of file PlayerAgentPool.c.
References m_PluginTransmissionAgents, m_VirusPool, and SetAgentCount().
Referenced by DigestAgent(), RemoteGrowRequestDebug(), and SpawnAgents().
AntibioticsAttack()
void AntibioticsAttack (float attack_value) inline private
Definition at line 251 of file PlayerAgentPool.c.
References m_Player, m_PluginTransmissionAgents, m_VirusPool, and SetAgentCount().
DigestAgent()
void DigestAgent (int agent_id, float count) inline private
Definition at line 134 of file PlayerAgentPool.c.
References AddAgent(), and m_PluginTransmissionAgents.
GetAgents()
int GetAgents () inline private
Definition at line 190 of file PlayerAgentPool.c.
References m_AgentMask.
GetDebugObject()
void GetDebugObject (array< ref Param > object_out) inline private
Definition at line 284 of file PlayerAgentPool.c.
References GetSingleAgentCount(), and m_PluginTransmissionAgents.
GetSingleAgentCount()
int GetSingleAgentCount (int agent_id) inline private
Definition at line 195 of file PlayerAgentPool.c.
References m_VirusPool.
Referenced by GetDebugObject(), and SpawnAgents().
GetStorageVersion()
int GetStorageVersion () inline private
Definition at line 24 of file PlayerAgentPool.c.
References STORAGE_VERSION.
GetTotalAgentCount()
float GetTotalAgentCount () inline private
Definition at line 204 of file PlayerAgentPool.c.
References m_VirusPool.
GrowAgents()
void GrowAgents (float deltaT) inline private
Definition at line 48 of file PlayerAgentPool.c.
References Math::Clamp(), IsPluginManagerExists(), m_Player, m_PluginTransmissionAgents, m_TotalAgentCount, m_VirusPool, and SetAgentCount().
Referenced by ImmuneSystemTick().
ImmuneSystemTick()
void ImmuneSystemTick (float value, float deltaT) inline private
Definition at line 42 of file PlayerAgentPool.c.
References GrowAgents(), and SpawnAgents().
OnStoreLoad()
bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 105 of file PlayerAgentPool.c.
References Serializer::Read(), and SetAgentCount().
OnStoreSave()
void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 91 of file PlayerAgentPool.c.
References m_VirusPool, and Serializer::Write().
PrintAgents()
void PrintAgents () inline private
Definition at line 29 of file PlayerAgentPool.c.
References Debug::Log(), and m_VirusPool.
RemoteGrowRequestDebug()
void RemoteGrowRequestDebug (ParamsReadContext ctx) inline private
Definition at line 268 of file PlayerAgentPool.c.
References Math::AbsInt(), AddAgent(), m_PluginTransmissionAgents, CachedObjectsParams::PARAM1_INT, and Serializer::Read().
RemoveAgent()
void RemoveAgent (int agent_id) inline private
Definition at line 165 of file PlayerAgentPool.c.
References SetAgentCount().
RemoveAllAgents()
void RemoveAllAgents () inline private
Definition at line 170 of file PlayerAgentPool.c.
References m_AgentMask, and m_VirusPool.
SetAgentCount()
void SetAgentCount (int agent_id, float count) inline private
Definition at line 230 of file PlayerAgentPool.c.
References m_AgentMask, m_Player, and m_VirusPool.
Referenced by AddAgent(), AntibioticsAttack(), GrowAgents(), OnStoreLoad(), and RemoveAgent().
SpawnAgents()
void SpawnAgents (float deltaT) inline private
Definition at line 214 of file PlayerAgentPool.c.
References AddAgent(), GetSingleAgentCount(), m_Player, and m_PluginTransmissionAgents.
Referenced by ImmuneSystemTick().
Field Documentation
m_AgentMask
int m_AgentMask private
Definition at line 8 of file PlayerAgentPool.c.
Referenced by GetAgents(), RemoveAllAgents(), and SetAgentCount().
m_LastTicked
float m_LastTicked = 0 private
Definition at line 5 of file PlayerAgentPool.c.
m_Player
PlayerBase m_Player private
Definition at line 7 of file PlayerAgentPool.c.
Referenced by AntibioticsAttack(), GrowAgents(), PlayerAgentPool(), SetAgentCount(), and SpawnAgents().
m_PluginTransmissionAgents
PluginTransmissionAgents m_PluginTransmissionAgents = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents)) private
Definition at line 12 of file PlayerAgentPool.c.
Referenced by AddAgent(), AntibioticsAttack(), DigestAgent(), GetDebugObject(), GrowAgents(), RemoteGrowRequestDebug(), and SpawnAgents().
m_TotalAgentCount
float m_TotalAgentCount private
Definition at line 6 of file PlayerAgentPool.c.
Referenced by GrowAgents().
m_VirusPool
ref map<int,float> m_VirusPool = new map<int,float> private
Definition at line 3 of file PlayerAgentPool.c.
Referenced by AddAgent(), AntibioticsAttack(), GetSingleAgentCount(), GetTotalAgentCount(), GrowAgents(), OnStoreSave(), PrintAgents(), RemoveAllAgents(), and SetAgentCount().
m_VirusPoolArray
ref array<int> m_VirusPoolArray = new array<int> private
Definition at line 4 of file PlayerAgentPool.c.
STORAGE_VERSION
const int STORAGE_VERSION = 100 private
Definition at line 10 of file PlayerAgentPool.c.
Referenced by GetStorageVersion().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/TransmissionAgents/PlayerAgentPool/PlayerAgentPool.c