DayZ Scripts: P:/scripts/4_World/Classes/PlayerStats/PlayerStats.c File Reference
PlayerStats.c File Reference
Enumerations
enum EPSstatsFlags { EMPTY = 0 , SYNCED = 1 }
Functions
void PlayerStats (Man player)
void Init (Man player)
PlayerStatsPCO_Base GetPCO (int version=-1)
void ~PlayerStats ()
PlayerStatBase GetStatObject (int id)
void SetAllowLogs (bool enable)
bool GetAllowLogs ()
void GetDebugInfo (array< ref StatDebugObject > objects, int flags)
void GatherAllRecords ()
void SaveStats (ParamsWriteContext ctx)
bool LoadStats (ParamsReadContext ctx, int version)
void ResetAllStats ()
void OnRPC (ParamsReadContext ctx)
void OnAfterStoreLoad ()
Variables
enum EPSstatsFlags m_PlayerStats
ref array< ref StatDebugObject > m_PlayerStatsDebug
ref PCOHandlerStats m_PCOhandler
ref Timer m_SyncTimer
Man m_Player
bool m_AllowLogs
string m_System = "Stats"
Enumeration Type Documentation
EPSstatsFlags
enum EPSstatsFlags
Enumerator
EMPTY
SYNCED
Function Documentation
GatherAllRecords()
void GatherAllRecords ()
GetAllowLogs()
bool GetAllowLogs ()
References m_AllowLogs.
GetDebugInfo()
void GetDebugInfo (array< ref StatDebugObject > objects, int flags)
GetPCO()
PlayerStatsPCO_Base GetPCO (int version = -1)
References PCOHandlerStats::GetPCO(), and m_PCOhandler.
Referenced by GetStatObject(), LoadStats(), OnAfterStoreLoad(), OnRPC(), ResetAllStats(), and SaveStats().
GetStatObject()
PlayerStatBase GetStatObject (int id)
References GetPCO().
Referenced by ManBase::GetStatBloodType(), ManBase::GetStatDiet(), ManBase::GetStatEnergy(), ManBase::GetStatHeatBuffer(), ManBase::GetStatHeatComfort(), ManBase::GetStatSpecialty(), ManBase::GetStatStamina(), ManBase::GetStatToxicity(), ManBase::GetStatTremor(), ManBase::GetStatWater(), and ManBase::GetStatWet().
Init()
void Init (Man player)
References m_Player.
LoadStats()
bool LoadStats (ParamsReadContext ctx, int version)
References GetPCO().
Referenced by ManBase::OnStoreLoad().
OnAfterStoreLoad()
void OnAfterStoreLoad ()
References GetPCO().
OnRPC()
void OnRPC (ParamsReadContext ctx)
References GetPCO().
PlayerStats()
void PlayerStats (Man player)
References Init(), and m_PCOhandler.
Referenced by ManBase::Init().
ResetAllStats()
void ResetAllStats ()
References GetPCO().
SaveStats()
void SaveStats (ParamsWriteContext ctx)
References GetGame(), GetPCO(), and CGame::SaveVersion().
SetAllowLogs()
void SetAllowLogs (bool enable)
References m_AllowLogs.
~PlayerStats()
void ~PlayerStats ()
Variable Documentation
m_AllowLogs
bool m_AllowLogs
Referenced by GetAllowLogs(), and SetAllowLogs().
m_PCOhandler
ref PCOHandlerStats m_PCOhandler
Referenced by GetPCO(), and PlayerStats().
m_Player
Man m_Player
m_PlayerStats
enum EPSstatsFlags m_PlayerStats
Referenced by ManBase::GetPlayerStats(), and ManBase::Init().
m_PlayerStatsDebug
ref array<ref StatDebugObject> m_PlayerStatsDebug
m_SyncTimer
ref Timer m_SyncTimer
m_System
string m_System = "Stats"