DayZ Scripts: PMTPlayback Class Reference
PMTPlayback Class Reference
Private Member Functions
void PMTPlayback ()
TFResult TestOnePlaying ()
TFResult TestOnePlayingStandAloneAutoDestroy ()
TFResult TestOnePlayingStandAlone ()
TFResult TestWiggleStress ()
TFResult TestStopping ()
TFResult CheckOnePlaying ()
TFResult CheckOnePlayingSAAD ()
TFResult CheckOnePlayingSA ()
TFResult CheckStop (float dt)
void PassOnePlaying (ParticleSource p)
void OnePlayingSAADEnded (ParticleSource p)
void OnePlayingSAEnded (ParticleSource p)
void StopEnded (ParticleSource p)
Private Attributes
ref array< ParticleSource > m_ParticleSources = new array<ParticleSource>()
int m_OnePlayingManagerID
bool m_bOnePlayingTestSuccess = false
int m_OnePlayingSAADPSID
bool m_bOnePlayingSAADEnded = false
int m_OnePlayingSAPSID
bool m_bOnePlayingSAEnded = false
int m_StopPSID
float m_StopAccumulatedTime
bool m_bStopWasStopped = false
bool m_bStopWasResumed = false
bool m_bStopEnded = false
Static Private Attributes
static const float STOP_ACCUMULATED_TIME_STOP_CUTOFF = 2
static const float STOP_ACCUMULATED_TIME_PLAY_CUTOFF = 3
Constructor & Destructor Documentation
PMTPlayback()
void PMTPlayback () inline private
References AddInitTest().
Member Function Documentation
CheckOnePlaying()
TFResult CheckOnePlaying () inline private
References Assert(), BTFR(), PMTF::GetManager(), ParticleSource::GetParticle(), ParticleSource::IsParticlePlaying(), m_bOnePlayingTestSuccess, m_OnePlayingManagerID, NTFR(), and ParticleManager().
CheckOnePlayingSA()
TFResult CheckOnePlayingSA () inline private
References Assert(), BTFR(), GetGame(), ParticleSource::IsParticlePlaying(), m_bOnePlayingSAEnded, m_OnePlayingSAPSID, m_ParticleSources, NTFR(), and CGame::ObjectDelete().
CheckOnePlayingSAAD()
TFResult CheckOnePlayingSAAD () inline private
References Assert(), BTFR(), ParticleSource::IsParticlePlaying(), m_bOnePlayingSAADEnded, m_OnePlayingSAADPSID, m_ParticleSources, and NTFR().
CheckStop()
TFResult CheckStop (float dt) inline private
References Assert(), BTFR(), GetGame(), ParticleSource::IsParticlePlaying(), m_bStopEnded, m_bStopWasResumed, m_bStopWasStopped, m_ParticleSources, m_StopAccumulatedTime, m_StopPSID, NTFR(), CGame::ObjectDelete(), Particle::PlayParticle(), STOP_ACCUMULATED_TIME_PLAY_CUTOFF, STOP_ACCUMULATED_TIME_STOP_CUTOFF, and ParticleSource::StopParticle().
OnePlayingSAADEnded()
void OnePlayingSAADEnded (ParticleSource p) inline private
References m_bOnePlayingSAADEnded.
Referenced by TestOnePlayingStandAloneAutoDestroy().
OnePlayingSAEnded()
void OnePlayingSAEnded (ParticleSource p) inline private
References m_bOnePlayingSAEnded.
Referenced by TestOnePlayingStandAlone().
PassOnePlaying()
void PassOnePlaying (ParticleSource p) inline private
References m_bOnePlayingTestSuccess.
Referenced by TestOnePlaying().
StopEnded()
void StopEnded (ParticleSource p) inline private
References m_bStopEnded.
Referenced by TestStopping().
TestOnePlaying()
TFResult TestOnePlaying () inline private
References AddFrameTest(), BTFR(), PMTF::CreatePMFixedBlocking(), ParticleList::EXPLOSION_LANDMINE, GetGame(), CGame::GetPlayer(), PMTF::InsertManager(), ParticleSource::IsParticlePlaying(), m_OnePlayingManagerID, ParticleManager(), and PassOnePlaying().
TestOnePlayingStandAlone()
TFResult TestOnePlayingStandAlone () inline private
References AddFrameTest(), BTFR(), ParticleSource::CreateParticle(), ParticleSource::DisableAutoDestroy(), ParticleList::EXPLOSION_LANDMINE, GetGame(), CGame::GetPlayer(), ParticleSource::IsParticlePlaying(), m_OnePlayingSAPSID, m_ParticleSources, and OnePlayingSAEnded().
TestOnePlayingStandAloneAutoDestroy()
TFResult TestOnePlayingStandAloneAutoDestroy () inline private
References AddFrameTest(), BTFR(), ParticleSource::CreateParticle(), ParticleList::EXPLOSION_LANDMINE, GetGame(), CGame::GetPlayer(), ParticleSource::IsParticlePlaying(), m_OnePlayingSAADPSID, m_ParticleSources, and OnePlayingSAADEnded().
TestStopping()
TFResult TestStopping () inline private
References AddFrameTest(), BTFR(), ParticleSource::CreateParticle(), ParticleSource::DisableAutoDestroy(), ParticleList::EXPLOSION_LANDMINE, GetGame(), CGame::GetPlayer(), ParticleSource::IsParticlePlaying(), m_ParticleSources, m_StopPSID, StopEnded(), and vector::Zero.
TestWiggleStress()
TFResult TestWiggleStress () inline private
References BTFR(), ParticleSource::CreateParticle(), GetGame(), CGame::GetPlayer(), ParticleSource::IsParticlePlaying(), ParticleList::ROADFLARE_BURNING_MAIN, and ParticleSource::SetWiggle().
Field Documentation
m_bOnePlayingSAADEnded
bool m_bOnePlayingSAADEnded = false private
Referenced by CheckOnePlayingSAAD(), and OnePlayingSAADEnded().
m_bOnePlayingSAEnded
bool m_bOnePlayingSAEnded = false private
Referenced by CheckOnePlayingSA(), and OnePlayingSAEnded().
m_bOnePlayingTestSuccess
bool m_bOnePlayingTestSuccess = false private
Referenced by CheckOnePlaying(), and PassOnePlaying().
m_bStopEnded
bool m_bStopEnded = false private
Referenced by CheckStop(), and StopEnded().
m_bStopWasResumed
bool m_bStopWasResumed = false private
Referenced by CheckStop().
m_bStopWasStopped
bool m_bStopWasStopped = false private
Referenced by CheckStop().
m_OnePlayingManagerID
int m_OnePlayingManagerID private
Referenced by CheckOnePlaying(), and TestOnePlaying().
m_OnePlayingSAADPSID
int m_OnePlayingSAADPSID private
Referenced by CheckOnePlayingSAAD(), and TestOnePlayingStandAloneAutoDestroy().
m_OnePlayingSAPSID
int m_OnePlayingSAPSID private
Referenced by CheckOnePlayingSA(), and TestOnePlayingStandAlone().
m_ParticleSources
ref array<ParticleSource> m_ParticleSources = new array<ParticleSource>() private
Referenced by CheckOnePlayingSA(), CheckOnePlayingSAAD(), CheckStop(), TestOnePlayingStandAlone(), TestOnePlayingStandAloneAutoDestroy(), and TestStopping().
m_StopAccumulatedTime
float m_StopAccumulatedTime private
Referenced by CheckStop().
m_StopPSID
int m_StopPSID private
Referenced by CheckStop(), and TestStopping().
STOP_ACCUMULATED_TIME_PLAY_CUTOFF
const float STOP_ACCUMULATED_TIME_PLAY_CUTOFF = 3 static private
Referenced by CheckStop().
STOP_ACCUMULATED_TIME_STOP_CUTOFF
const float STOP_ACCUMULATED_TIME_STOP_CUTOFF = 2 static private
Referenced by CheckStop().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Particles/Tests/PMTPlayback.c