DayZ Scripts: P:/scripts/4_World/Entities/Creatures/Animals/AnimalBase.c File Reference
AnimalBase.c File Reference
Data Structures
class DayZAnimal
class Animal_BosTaurus
class AnimalBase
class Animal_CervusElaphus
class Animal_GallusGallusDomesticus
class Animal_GallusGallusDomesticusF
Functions
class AnimalBase extends DayZAnimal RegisterHitComponentsForAI ()
void AnimalBase ()
override ArrowManagerBase GetArrowManager ()
override bool IsRefresherSignalingViable ()
override string CaptureSound ()
override string ReleaseSound ()
override bool IsDanger ()
class Animal_CapraHircus extends AnimalBase GetDestructionBehaviour ()
override bool IsDestructionBehaviour ()
override void EEInit ()
void ~Animal_CapraHircus_Spooky ()
override void OnDamageDestroyed (int oldLevel)
override bool ResistContaminatedEffect ()
override bool ReplaceOnDeath ()
override bool CanBeSkinned ()
override string GetDeadItemName ()
override bool KeepHealthOnReplace ()
Variables
protected ref ArrowManagerBase m_ArrowManager
protected GoatLight m_EyeLight
Function Documentation
AnimalBase()
void AnimalBase ()
CanBeSkinned()
override bool CanBeSkinned ()
CaptureSound()
override string CaptureSound ()
EEInit()
override void EEInit ()
References IsDamageDestroyed(), and m_EyeLight.
GetArrowManager()
override ArrowManagerBase GetArrowManager ()
Referenced by ManBase::EEDelete(), ManBase::OnBleedingSourceRemoved(), ManBase::OnStoreLoad(), ManBase::OnStoreSave(), and ManBase::ResetPlayer().
GetDeadItemName()
override string GetDeadItemName ()
Referenced by Entity::DeathUpdate().
GetDestructionBehaviour()
class Animal_CapraHircus extends AnimalBase GetDestructionBehaviour ()
Referenced by Entity::AttemptDestructionBehaviour().
IsDanger()
override bool IsDanger ()
IsDestructionBehaviour()
override bool IsDestructionBehaviour ()
Referenced by Entity::AttemptDestructionBehaviour().
IsRefresherSignalingViable()
override bool IsRefresherSignalingViable ()
KeepHealthOnReplace()
override bool KeepHealthOnReplace ()
Referenced by Entity::DeathUpdate().
OnDamageDestroyed()
override void OnDamageDestroyed (int oldLevel)
References m_EyeLight.
Referenced by Entity::EEHealthLevelChanged().
RegisterHitComponentsForAI()
class AnimalBase extends DayZAnimal RegisterHitComponentsForAI ()
Referenced by DayZCreatureAI::DayZAnimal().
ReleaseSound()
override string ReleaseSound ()
ReplaceOnDeath()
override bool ReplaceOnDeath ()
Referenced by Entity::EEKilled().
ResistContaminatedEffect()
override bool ResistContaminatedEffect ()
~Animal_CapraHircus_Spooky()
void ~Animal_CapraHircus_Spooky ()
References m_EyeLight.
Variable Documentation
m_ArrowManager
protected ref ArrowManagerBase m_ArrowManager
Referenced by DayZAnimal::AnimalBase(), DayZAnimal::GetArrowManager(), DayZInfected::GetArrowManager(), ManBase::GetArrowManager(), DayZInfected::Init(), and ManBase::Init().
m_EyeLight
protected GoatLight m_EyeLight
Referenced by EEInit(), ZombieMaleBase::EEInit(), OnDamageDestroyed(), ZombieMaleBase::OnDamageDestroyed(), ~Animal_CapraHircus_Spooky(), and ZombieMaleBase::~ZmbM_Mummy().