DayZ Scripts: ActionFishingNew Class Reference
ActionFishingNew Class Reference
Private Member Functions
void ActionFishingNew ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool HasAlternativeInterrupt ()
override bool CanBeUsedInFreelook ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override ActionData CreateActionData ()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=null)
protected void ComposeLocalContextData (FishingActionData data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override protected void CreateAndSetupActionCallback (ActionData action_data)
override void OnAnimationEvent (ActionData action_data)
override void OnUpdate (ActionData action_data)
void PlaySplashEffectSynced (FishingActionData actionDataFishing)
protected bool CheckForSea (ActionData action_data)
override void OnFinishProgress (ActionData action_data)
override void OnEndInput (ActionData action_data)
override void OnEnd (ActionData action_data)
int EvaluateFishingResult (ActionData action_data)
Player input reaction evaluation.
void OnSignalStart (FishingActionData action_data)
void OnSignalEnd (FishingActionData action_data)
protected EntityAI TrySpawnCatch (FishingActionData action_data)
Private Attributes
private const string ALLOWED_WATER_SURFACES = string.Format("%1|%2", UAWaterType.SEA, UAWaterType.FRESH)
Constructor & Destructor Documentation
ActionFishingNew()
void ActionFishingNew () inline private
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, ActionBase::m_FullBody, ActionBase::m_SpecialtyWeight, ActionBase::m_StanceMask, and ActionBase::m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
CanBeUsedInFreelook()
override bool CanBeUsedInFreelook () inline private
CheckForSea()
protected bool CheckForSea (ActionData action_data) inline private
References GetGame().
Referenced by ComposeLocalContextData().
ComposeLocalContextData()
protected void ComposeLocalContextData (FishingActionData data) inline private
References CheckForSea().
Referenced by SetupAction().
CreateActionData()
override ActionData CreateActionData () inline private
CreateAndSetupActionCallback()
override protected void CreateAndSetupActionCallback (ActionData action_data) inline private
References Class::CastTo().
CreateConditionComponents()
override void CreateConditionComponents () inline private
References CCTWaterSurfaceEx(), LIQUID_FRESHWATER, LIQUID_SALTWATER, ActionBase::m_ConditionItem, and ActionBase::m_ConditionTarget.
EvaluateFishingResult()
int EvaluateFishingResult (ActionData action_data) inline private
Player input reaction evaluation.
References Class::CastTo(), GetGame(), ActionFishingNewCB::HandleFishingResultFailure(), ActionFishingNewCB::HandleFishingResultSuccess(), and TrySpawnCatch().
Referenced by OnEndInput().
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
References FishingActionReceiveData::m_IsSurfaceSea.
HasAlternativeInterrupt()
override bool HasAlternativeInterrupt () inline private
HasTarget()
override bool HasTarget () inline private
OnAnimationEvent()
override void OnAnimationEvent (ActionData action_data) inline private
References UAFishingConstants::EVENT_ANIMATE_ROD_CLOSE, UAFishingConstants::EVENT_SPLASH_SIGNAL, and PlaySplashEffectSynced().
OnEnd()
override void OnEnd (ActionData action_data) inline private
References Class::CastTo().
OnEndInput()
override void OnEndInput (ActionData action_data) inline private
References Class::CastTo(), ActionContinuousBaseCB::EndActionComponent(), EvaluateFishingResult(), and UA_FINISHED.
OnFinishProgress()
override void OnFinishProgress (ActionData action_data) inline private
References Class::CastTo().
OnSignalEnd()
void OnSignalEnd (FishingActionData action_data) inline private
References Class::CastTo(), and ActionFishingNewCB::ToggleFishBiting().
Referenced by CAContinuousRepeatFishing::OnSignalEnd().
OnSignalStart()
void OnSignalStart (FishingActionData action_data) inline private
References Class::CastTo(), and ActionFishingNewCB::ToggleFishBiting().
Referenced by CAContinuousRepeatFishing::OnSignalStart().
OnUpdate()
override void OnUpdate (ActionData action_data) inline private
References vector::Direction(), and vector::Normalize().
PlaySplashEffectSynced()
void PlaySplashEffectSynced (FishingActionData actionDataFishing) inline private
References SEffectManager::CreateParticleServer(), EffecterBase(), GetGame(), SEffectManager::ReactivateParticleServer(), and SEffectManager::ReinitParticleServer().
Referenced by OnAnimationEvent().
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
References Class::CastTo(), FishingActionReceiveData::m_IsSurfaceSea, and Serializer::Read().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = null) inline private
References Class::CastTo(), and ComposeLocalContextData().
TrySpawnCatch()
protected EntityAI TrySpawnCatch (FishingActionData action_data) inline private
References vector::Direction().
Referenced by EvaluateFishingResult().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
References Class::CastTo(), and Serializer::Write().
Field Documentation
ALLOWED_WATER_SURFACES
private const string ALLOWED_WATER_SURFACES = string.Format("%1|%2", UAWaterType.SEA, UAWaterType.FRESH) private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionFishingNew.c