DayZ Scripts: ScriptReadWriteContext Class Reference
ScriptReadWriteContext Class Reference
Private Member Functions
void ScriptReadWriteContext ()
void ~ScriptReadWriteContext ()
proto native ParamsWriteContext GetWriteContext ()
proto native ParamsReadContext GetReadContext ()
Constructor & Destructor Documentation
ScriptReadWriteContext()
void ScriptReadWriteContext () private
~ScriptReadWriteContext()
void ~ScriptReadWriteContext () private
Member Function Documentation
GetReadContext()
proto native ParamsReadContext GetReadContext () private
Referenced by Weapon::CopyWeaponStateFrom().
GetWriteContext()
proto native ParamsWriteContext GetWriteContext () private
Referenced by Weapon::CopyWeaponStateFrom(), and CGame::StoreLoginDataPrepare().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/gameplay.c