DayZ Scripts: TemperatureAccessManager Class Reference
TemperatureAccessManager Class Reference
Private Member Functions
void TemperatureAccessManager ()
protected void Init ()
protected void RegisterTemperatureAccesType (typename type)
Static Private Member Functions
static TemperatureAccessTypeBase GetTAData (ETemperatureAccessTypes id)
Static Private Attributes
static ref map< ETemperatureAccessTypes, ref TemperatureAccessTypeBase > m_AccessTypesMap
Constructor & Destructor Documentation
TemperatureAccessManager()
void TemperatureAccessManager () inline private
References Init(), and m_AccessTypesMap.
Member Function Documentation
GetTAData()
static TemperatureAccessTypeBase GetTAData (ETemperatureAccessTypes id) inline static private
References m_AccessTypesMap.
Referenced by TemperatureAccessComponent::PriorityCheck(), and TemperatureAccessComponent::TryAccessSource().
Init()
protected void Init () inline private
References RegisterTemperatureAccesType().
Referenced by TemperatureAccessManager().
RegisterTemperatureAccesType()
protected void RegisterTemperatureAccesType (typename type) inline private
References TemperatureAccessTypeBase::GetAccessTypeID(), and m_AccessTypesMap.
Referenced by Init().
Field Documentation
m_AccessTypesMap
ref map<ETemperatureAccessTypes,ref TemperatureAccessTypeBase> m_AccessTypesMap static private
Referenced by GetTAData(), RegisterTemperatureAccesType(), and TemperatureAccessManager().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/TemperatureAccess/TemperatureAccessManager.c