DayZ Scripts: Battery9V Class Reference
Battery9V Class Reference
Private Member Functions
void Battery9V ()
float GetEfficiency0To1 ()
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 units.
float GetEfficiencyDecayStart ()
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 unit.
override void OnEnergyConsumed ()
override void OnEnergyAdded ()
override void SetActions ()
Private Attributes
private int m_Efficiency0To10
Static Private Attributes
static private float m_EfficiencyDecayStart = 0.1
Constructor & Destructor Documentation
Battery9V()
void Battery9V () inline private
References m_Efficiency0To10.
Member Function Documentation
GetEfficiency0To1()
float GetEfficiency0To1 () inline private
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 units.
References m_Efficiency0To10.
Referenced by Clothing::OnWork(), ItemBase::OnWork(), and Switchable_Base::OnWork().
GetEfficiencyDecayStart()
float GetEfficiencyDecayStart () inline private
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 unit.
References m_EfficiencyDecayStart.
OnEnergyAdded()
override void OnEnergyAdded () inline private
References GetGame(), m_Efficiency0To10, m_EfficiencyDecayStart, and Math::Round().
OnEnergyConsumed()
override void OnEnergyConsumed () inline private
References GetGame(), m_Efficiency0To10, m_EfficiencyDecayStart, and Math::Round().
SetActions()
override void SetActions () inline private
References AddAction().
Field Documentation
m_Efficiency0To10
private int m_Efficiency0To10 private
Referenced by Battery9V(), GetEfficiency0To1(), OnEnergyAdded(), and OnEnergyConsumed().
m_EfficiencyDecayStart
private float m_EfficiencyDecayStart = 0.1 static private
Referenced by GetEfficiencyDecayStart(), OnEnergyAdded(), and OnEnergyConsumed().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Battery9V.c