DayZ Scripts: FishingRod_Base_New Class Reference
FishingRod_Base_New Class Reference
Private Member Functions
void FishingRod_Base_New ()
override void SetActions ()
override bool GetActionWidgetOverride (out typename name)
override bool IsOpen ()
void AnimateFishingRodEx (float phase, bool instant=false)
override void OnDebugSpawn ()
float GetFishingEffectivityBonus ()
DEPRECATED, used to dictate catch chance.
void AnimateFishingRod (bool state)
DEPRECATED.
Constructor & Destructor Documentation
FishingRod_Base_New()
void FishingRod_Base_New () inline private
Member Function Documentation
AnimateFishingRod()
void AnimateFishingRod (bool state) inline private
DEPRECATED.
References AnimateFishingRodEx().
AnimateFishingRodEx()
void AnimateFishingRodEx (float phase, bool instant = false) inline private
Referenced by AnimateFishingRod(), and AnimateRod().
GetActionWidgetOverride()
override bool GetActionWidgetOverride (out typename name) inline private
References Class::CastTo(), name, and UA_PROCESSING.
GetFishingEffectivityBonus()
float GetFishingEffectivityBonus () inline private
DEPRECATED, used to dictate catch chance.
IsOpen()
override bool IsOpen () inline private
OnDebugSpawn()
override void OnDebugSpawn () inline private
References Class::CastTo(), ECE_PLACE_ON_SURFACE, GetGame(), and GetPosition.
SetActions()
override void SetActions () inline private
References AddAction().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/FishingRod_Base.c