DayZ Scripts: HudDebugWinBase Class Reference
HudDebugWinBase Class Reference
Private Member Functions
void HudDebugWinBase (Widget widget_root)
int GetType ()
void Init (Widget widget_root)
void SetUpdate (bool state)
void Update ()
void SetRPCSent ()
void Show ()
void Hide ()
bool IsVisible ()
void FitWindowByContent (TextListboxWidget wgt)
void SetValueListSize (int x, int y, TextListboxWidget wgt)
void HudDebugWinCharDebug (Widget widget_root)
void ~HudDebugWinCharDebug ()
override void Update ()
override int GetType ()
void HudDebugWinCharLevels (Widget widget_root)
void ~HudDebugWinCharLevels ()
override int GetType ()
override void Show ()
override void Hide ()
override void SetUpdate (bool state)
override void Update ()
void SetValues ()
void AddValue (string title, string value, string value2)
void ClearValues ()
void FitWindow ()
void HudDebugWinCharStats (Widget widget_root)
void ~HudDebugWinCharStats ()
override int GetType ()
override void Show ()
override void Hide ()
override void SetUpdate (bool state)
override void Update ()
void SetupValues ()
void UpdateValues ()
void AddValue (string title, string value)
void ClearValues ()
void FitWindow ()
bool OnClick (Widget w, int x, int y, int button)
bool OnChange (Widget w, int x, int y, bool finished)
void ResetStats ()
void RPCChangeStat (string stat, float value)
void HudDebugWinCharStomach (Widget widget_root)
void ~HudDebugWinCharStomach ()
override int GetType ()
override void Show ()
override void Hide ()
override void SetUpdate (bool state)
override void Update ()
void SetContentValues ()
void AddValue (string classname, int food_stage, int agents, float amount)
array< string > GetAgentsArray (int agents)
void ClearValues ()
void FitWindow ()
void HudDebugWinTemperature (Widget widget_root)
void ~HudDebugWinTemperature ()
override void SetUpdate (bool state)
override void Show ()
override void Hide ()
override void Update ()
override int GetType ()
void HudDebugWinVersion (Widget widget_root)
void ~HudDebugWinVersion ()
override void Update ()
override int GetType ()
Private Attributes
Widget m_WgtRoot
protected bool m_Show
protected bool m_RPCSent
private PluginDeveloper m_ModuleDeveloper
private TextWidget m_PlayerPosTextWidget
private TextWidget m_ClipboardTextWidget
TextListboxWidget m_WgtValues
Widget m_WgtPanel
ref array< ref Widget > m_StatWidgets = new array<ref Widget>
ref map< ref SliderWidget, string > m_SliderWidgets = new map<ref SliderWidget, string>
ref array< ref TextWidget > m_StatValues = new array<ref TextWidget>
ref map< ref EditBoxWidget, string > m_StatValuesInput = new map<ref EditBoxWidget, string>
bool m_Populated
bool m_ChangingSlider
TextWidget m_WgtOverall
private TextWidget m_EnviroTextWidget
protected PluginDeveloperSync m_PluginDeveloperSync
private TextWidget m_VersionTextWidget
Constructor & Destructor Documentation
HudDebugWinBase()
void HudDebugWinBase (Widget widget_root) inline private
References m_WgtRoot.
~HudDebugWinCharDebug()
void ~HudDebugWinCharDebug () inline private
~HudDebugWinCharLevels()
void ~HudDebugWinCharLevels () inline private
References SetUpdate().
~HudDebugWinCharStats()
void ~HudDebugWinCharStats () inline private
References SetUpdate().
~HudDebugWinCharStomach()
void ~HudDebugWinCharStomach () inline private
References SetUpdate().
~HudDebugWinTemperature()
void ~HudDebugWinTemperature () inline private
~HudDebugWinVersion()
void ~HudDebugWinVersion () inline private
Member Function Documentation
AddValue() [1/3]
void AddValue (string classname, int food_stage, int agents, float amount) inline private
References GetAgentsArray(), and float::ToString().
AddValue() [2/3]
void AddValue (string title, string value) inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_WgtPanel, and AutoHeightSpacer::Update().
AddValue() [3/3]
void AddValue (string title, string value, string value2) inline private
Referenced by SetContentValues(), SetupValues(), and SetValues().
ClearValues() [1/3]
void ClearValues () inline private
Referenced by SetContentValues(), and SetValues().
ClearValues() [2/3]
void ClearValues () inline private
ClearValues() [3/3]
void ClearValues () inline private
FitWindow() [1/3]
void FitWindow () inline private
Referenced by HudDebugWinCharLevels(), SetModifiers(), SetupValues(), and SetValues().
FitWindow() [2/3]
void FitWindow () inline private
References FitWindowByContent(), and m_WgtPanel.
FitWindow() [3/3]
void FitWindow () inline private
References FitWindowByContent().
FitWindowByContent()
void FitWindowByContent (TextListboxWidget wgt) inline private
References SetValueListSize().
Referenced by FitWindow(), and FitWindow().
GetAgentsArray()
array< string > GetAgentsArray (int agents) inline private
Referenced by AddValue().
GetType() [1/7]
int GetType () inline private
References HudDebug().
Referenced by PanelHide(), and PanelShow().
GetType() [2/7]
override int GetType () inline private
References HudDebug().
GetType() [3/7]
override int GetType () inline private
References HudDebug().
GetType() [4/7]
override int GetType () inline private
References HudDebug().
GetType() [5/7]
override int GetType () inline private
References HudDebug().
GetType() [6/7]
override int GetType () inline private
References HudDebug().
GetType() [7/7]
override int GetType () inline private
References HudDebug().
Hide() [1/5]
void Hide () inline private
References m_Show, and m_WgtRoot.
Referenced by PanelHide().
Hide() [2/5]
override void Hide () inline private
References SetUpdate().
Hide() [3/5]
override void Hide () inline private
References SetUpdate().
Hide() [4/5]
override void Hide () inline private
References SetUpdate().
Hide() [5/5]
override void Hide () inline private
References SetUpdate().
HudDebugWinCharDebug()
void HudDebugWinCharDebug (Widget widget_root) inline private
HudDebugWinCharLevels()
void HudDebugWinCharLevels (Widget widget_root) inline private
References FitWindow().
HudDebugWinCharStats()
void HudDebugWinCharStats (Widget widget_root) inline private
References m_WgtPanel, and m_WgtRoot.
HudDebugWinCharStomach()
void HudDebugWinCharStomach (Widget widget_root) inline private
HudDebugWinTemperature()
void HudDebugWinTemperature (Widget widget_root) inline private
References GetPlugin(), and m_PluginDeveloperSync.
HudDebugWinVersion()
void HudDebugWinVersion (Widget widget_root) inline private
References g_Game, GetPBOAPI(), and GetPBOVersion().
Init()
void Init (Widget widget_root) private
IsVisible()
bool IsVisible () inline private
References m_WgtRoot.
OnChange()
bool OnChange (Widget w, int x, int y, bool finished) inline private
References Count, Get(), GetGame(), GetPlayer(), and RPCChangeStat().
OnClick()
bool OnClick (Widget w, int x, int y, int button) inline private
References ResetStats().
Referenced by InitDebug().
ResetStats()
void ResetStats () inline private
References GetGame(), and GetPlayer().
Referenced by OnClick().
RPCChangeStat()
void RPCChangeStat (string stat, float value) inline private
References GetGame(), and GetPlayer().
Referenced by OnChange().
SetContentValues()
void SetContentValues () inline private
References AddValue(), ClearValues(), GetPlugin(), and PlayerStomach().
Referenced by Update().
SetRPCSent()
void SetRPCSent () inline private
References m_RPCSent.
Referenced by SetUpdate(), and SetUpdate().
SetUpdate() [1/5]
void SetUpdate (bool state) private
Referenced by Hide(), Hide(), Show(), Show(), Update(), ~HudDebugWinCharAgents(), ~HudDebugWinCharLevels(), ~HudDebugWinCharModifiers(), ~HudDebugWinCharStats(), ~HudDebugWinCharStomach(), and ~HudDebugWinHealth().
SetUpdate() [2/5]
override void SetUpdate (bool state) inline private
References GetGame(), GetPlayer(), GetPlugin(), and SetRPCSent().
SetUpdate() [3/5]
override void SetUpdate (bool state) inline private
References GetGame(), GetPlayer(), GetPlugin(), and SetRPCSent().
SetUpdate() [4/5]
override void SetUpdate (bool state) inline private
References GetGame(), GetPlayer(), GetPlugin(), and SetRPCSent().
SetUpdate() [5/5]
override void SetUpdate (bool state) inline private
References GetGame(), GetPlayer(), m_PluginDeveloperSync, CachedObjectsParams::PARAM1_BOOL, and SetRPCSent().
SetupValues()
void SetupValues () inline private
References AddValue(), FitWindow(), and GetPlugin().
Referenced by Update().
SetValueListSize()
void SetValueListSize (int x, int y, TextListboxWidget wgt) inline private
References m_WgtRoot, x, and y.
Referenced by FitWindowByContent().
SetValues()
void SetValues () inline private
References AddValue(), ClearValues(), FitWindow(), and GetPlugin().
Referenced by Update().
Show() [1/5]
void Show () inline private
References m_Show, and m_WgtRoot.
Referenced by PanelShow().
Show() [2/5]
override void Show () inline private
References SetUpdate().
Show() [3/5]
override void Show () inline private
References SetUpdate().
Show() [4/5]
override void Show () inline private
References SetUpdate().
Show() [5/5]
override void Show () inline private
References SetUpdate().
Update() [1/7]
void Update () inline private
References m_RPCSent, m_Show, and SetUpdate().
Update() [2/7]
override void Update () inline private
References CGame::CopyFromClipboard(), GetGame(), GetPlayer(), string::Length(), Math::Min(), string::Substring(), and vector::ToString().
Update() [3/7]
override void Update () inline private
References SetValues().
Update() [4/7]
override void Update () inline private
References SetupValues(), and UpdateValues().
Update() [5/7]
override void Update () inline private
References SetContentValues().
Update() [6/7]
override void Update () inline private
References GetPlugin(), m_WgtRoot, and AutoHeightSpacer::Update().
Update() [7/7]
override void Update () inline private
UpdateValues()
void UpdateValues () inline private
References string::Get(), BloodTypes::GetBloodTypeName(), GetPlugin(), name, Math::Round(), and float::ToString().
Referenced by Update().
Field Documentation
m_ChangingSlider
bool m_ChangingSlider private
m_ClipboardTextWidget
private TextWidget m_ClipboardTextWidget private
m_EnviroTextWidget
private TextWidget m_EnviroTextWidget private
m_ModuleDeveloper
private PluginDeveloper m_ModuleDeveloper private
m_PlayerPosTextWidget
private TextWidget m_PlayerPosTextWidget private
m_PluginDeveloperSync
protected PluginDeveloperSync m_PluginDeveloperSync private
m_Populated
bool m_Populated private
m_RPCSent
protected bool m_RPCSent private
Referenced by SetRPCSent(), and Update().
m_Show
protected bool m_Show private
Referenced by Hide(), Show(), and Update().
m_SliderWidgets
ref map<ref SliderWidget, string> m_SliderWidgets = new map<ref SliderWidget, string> private
m_StatValues
ref array<ref TextWidget> m_StatValues = new array<ref TextWidget> private
m_StatValuesInput
ref map<ref EditBoxWidget, string> m_StatValuesInput = new map<ref EditBoxWidget, string> private
m_StatWidgets
ref array<ref Widget> m_StatWidgets = new array<ref Widget> private
m_VersionTextWidget
private TextWidget m_VersionTextWidget private
m_WgtOverall
TextWidget m_WgtOverall private
m_WgtPanel
Widget m_WgtPanel private
m_WgtRoot
Widget m_WgtRoot private
Referenced by Hide(), HudDebugWinBase(), IsVisible(), SetValueListSize(), and Show().
m_WgtValues
TextListboxWidget m_WgtValues private
The documentation for this class was generated from the following files:
P:/scripts/5_Mission/GUI/ScriptsHudDebug/HudDebugWinBase.c
P:/scripts/5_Mission/GUI/ScriptsHudDebug/HudDebugWinCharDebug.c
P:/scripts/5_Mission/GUI/ScriptsHudDebug/HudDebugWinCharLevels.c
P:/scripts/5_Mission/GUI/ScriptsHudDebug/HudDebugWinCharStats.c
P:/scripts/5_Mission/GUI/ScriptsHudDebug/HudDebugWinCharStomach.c
P:/scripts/5_Mission/GUI/ScriptsHudDebug/HudDebugWinTemperature.c
P:/scripts/5_Mission/GUI/ScriptsHudDebug/HudDebugWinVersion.c