DayZ Scripts: P:/scripts/5_Mission/GUI/ScriptsHudDebug/HudDebugWinHealth.c File Reference
HudDebugWinHealth.c File Reference
Data Structures
class HudDebugWinHealthEntry
Functions
void HudDebugWinHealth (Widget widget_root)
void ~HudDebugWinHealth ()
override void Update ()
override int GetType ()
override void Show ()
override void Hide ()
override void SetUpdate (bool state)
void InitDebug ()
bool OnClick (Widget w, int x, int y, int button)
Called from HudDebug.c.
void RunRPC (HudDebugWinHealthEntry entry, int buttonID)
void HandleTargetState (bool button)
void InitEntityEntries ()
void InitEntry (SyncedValue data)
void UpdateZones ()
void CleanupEntries ()
Variables
class HudDebugWinHealthEntry m_IsInit
protected bool m_IsModeSelf = true
protected Widget m_WgtPanel
protected TextWidget m_TargetDisplayNameW
protected ButtonWidget m_ButtonSelf
protected ButtonWidget m_ButtonTarget
protected EntityAI m_TargetEntity
protected PluginDeveloperSync m_DevSyncPlugin
protected ref array< ref HudDebugWinHealthEntry > m_Entries = {}
Function Documentation
CleanupEntries()
void CleanupEntries ()
References m_Entries.
Referenced by Hide(), and Update().
GetType()
override int GetType ()
References HudDebug().
HandleTargetState()
void HandleTargetState (bool button)
References COLOR_YELLOW, m_ButtonSelf, m_ButtonTarget, and m_IsModeSelf.
Referenced by OnClick().
Hide()
override void Hide ()
References CleanupEntries(), m_IsInit, m_TargetEntity, and HudDebugWinBase::SetUpdate().
HudDebugWinHealth()
void HudDebugWinHealth (Widget widget_root)
References m_WgtPanel, and m_WgtRoot.
Referenced by Init().
InitDebug()
void InitDebug ()
References m_ButtonSelf, m_ButtonTarget, m_IsInit, m_IsModeSelf, m_TargetDisplayNameW, m_WgtRoot, and HudDebugWinBase::OnClick().
Referenced by Update().
InitEntityEntries()
void InitEntityEntries ()
References InitEntry(), m_DevSyncPlugin, m_TargetDisplayNameW, m_TargetEntity, m_WgtPanel, and AutoHeightSpacer::Update().
Referenced by Update().
InitEntry()
void InitEntry (SyncedValue data)
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Entries, HudDebugWinHealthEntry::m_EntryRootW, HudDebugWinHealthEntry::m_EntryValueW, HudDebugWinHealthEntry::m_EntryZoneW, HudDebugWinHealthEntry::m_HealthMode, HudDebugWinHealthEntry::m_IsTitleEntry, SyncedValue::m_Name, SyncedValue::m_State, SyncedValue::m_ValueNorm, m_WgtPanel, and HudDebugWinHealthEntry::m_Zone.
Referenced by InitEntityEntries().
OnClick()
bool OnClick (Widget w, int x, int y, int button)
Called from HudDebug.c.
References HandleTargetState(), m_ButtonSelf, m_ButtonTarget, m_Entries, and RunRPC().
RunRPC()
void RunRPC (HudDebugWinHealthEntry entry, int buttonID)
References GetGame(), GetPlayer(), HudDebugWinHealthEntry::m_HealthMode, and HudDebugWinHealthEntry::m_Zone.
Referenced by OnClick().
SetUpdate()
override void SetUpdate (bool state)
References GetGame(), GetPlayer(), m_DevSyncPlugin, and HudDebugWinBase::SetRPCSent().
Show()
override void Show ()
References GetPlugin(), m_DevSyncPlugin, and HudDebugWinBase::SetUpdate().
UpdateZones()
void UpdateZones ()
References COLOR_GREEN, COLOR_RED, COLOR_YELLOW, m_DevSyncPlugin, m_Entries, HudDebugWinHealthEntry::m_EntryValueW, HudDebugWinHealthEntry::m_HealthMode, HudDebugWinHealthEntry::m_IsTitleEntry, m_TargetEntity, HudDebugWinHealthEntry::m_Zone, Math::Round(), and float::ToString().
Referenced by Update().
~HudDebugWinHealth()
void ~HudDebugWinHealth ()
References HudDebugWinBase::SetUpdate().
Variable Documentation
m_ButtonSelf
protected ButtonWidget m_ButtonSelf
Referenced by HandleTargetState(), InitDebug(), and OnClick().
m_ButtonTarget
protected ButtonWidget m_ButtonTarget
Referenced by HandleTargetState(), InitDebug(), and OnClick().
m_DevSyncPlugin
protected PluginDeveloperSync m_DevSyncPlugin
Referenced by InitEntityEntries(), SetUpdate(), Show(), Update(), and UpdateZones().
m_Entries
protected ref array<ref HudDebugWinHealthEntry> m_Entries = {}
Referenced by ScriptedWidgetEventHandler::AddPlayer(), CleanupEntries(), ScriptedWidgetEventHandler::FindEntryByWidget(), ScriptedWidgetEventHandler::FindPlayerByWidget(), InitEntry(), ScriptedWidgetEventHandler::IsEmpty(), ScriptedWidgetEventHandler::IsGloballyMuted(), ScriptedWidgetEventHandler::IsMuted(), OnClick(), ScriptedWidgetEventHandler::PlayerListScriptedWidget(), ScriptedWidgetEventHandler::Reload(), ScriptedWidgetEventHandler::Reload(), ScriptedWidgetEventHandler::Reload(), ScriptedWidgetEventHandler::ReloadLocal(), ScriptedWidgetEventHandler::RemovePlayer(), ScriptedWidgetEventHandler::SetMute(), ScriptedWidgetEventHandler::ToggleMute(), and UpdateZones().
m_IsInit
class HudDebugWinHealthEntry m_IsInit
Referenced by Hide(), InitDebug(), and Update().
m_IsModeSelf
protected bool m_IsModeSelf = true
Referenced by HandleTargetState(), InitDebug(), and Update().
m_TargetDisplayNameW
protected TextWidget m_TargetDisplayNameW
Referenced by InitDebug(), InitEntityEntries(), and Update().
m_TargetEntity
protected EntityAI m_TargetEntity
Referenced by Hide(), InitEntityEntries(), Update(), and UpdateZones().
m_WgtPanel
protected Widget m_WgtPanel
Referenced by HudDebugWinBase::AddValue(), HudDebugWinBase::FitWindow(), HudDebugWinBase::HudDebugWinCharStats(), HudDebugWinHealth(), InitEntityEntries(), and InitEntry().