DayZ Scripts: BetaSound Class Reference
BetaSound Class Reference
Static Private Member Functions
static SoundOnVehicle SaySound (Object source, string sound_name, float distance, bool looped)
Detailed Description
Definition at line 1 of file BetaSound.c.
Member Function Documentation
SaySound()
static SoundOnVehicle SaySound (Object source, string sound_name, float distance, bool looped) inline static private
Definition at line 3 of file BetaSound.c.
References CachedObjectsArrays::ARRAY_STRING, CGame::ConfigGetTextArray(), CGame::CreateSoundOnObject(), GetDayZGame(), GetGame(), and Math::RandomInt().
Referenced by ManBase::PlaySound().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/BetaSound.c