DayZ Scripts: InventoryItem Class Reference
InventoryItem Class Reference
Private Member Functions
void TransferModifiers (PlayerBase reciever)
appears to be deprecated, legacy code
void ItemBase ()
override void InitItemVariables ()
protected bool UsesGlobalDeploy ()
override int GetQuickBarBonus ()
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
void SetActions ()
void SetActionAnimOverrides ()
void AddAction (typename actionName)
void RemoveAction (typename actionName)
void OverrideActionAnimation (typename action, int commandUID, int stanceMask=-1, int commandUIDProne=-1)
void OnItemInHandsPlayerSwimStart (PlayerBase player)
ScriptedLightBase GetLight ()
void LoadParticleConfigOnFire (int id)
void LoadParticleConfigOnOverheating (int id)
float GetOverheatingValue ()
void IncreaseOverheating (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
void CheckOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
bool IsOverheatingEffectActive ()
void OnOverheatingDecay ()
void StartOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void UpdateOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void StopOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void RegisterOverheatingParticle (Particle p, float min_heat_coef, float max_heat_coef, int particle_id, Object parent, vector local_pos, vector local_ori)
float GetOverheatingCoef ()
void UpdateAllOverheatingParticles ()
void KillAllOverheatingParticles ()
float GetInfectionChance (int system=0, Param param=null)
Infection chance while/after using this item, originally used for wound infection after bandaging, params 'system' and 'param' can allow usage by other systems as well.
float GetDisinfectQuantity (int system=0, Param param1=null)
float GetFilterDamageRatio ()
bool HasMuzzle ()
Returns true if this item has a muzzle (weapons, suppressors)
int GetMuzzleID ()
Returns global muzzle ID. If not found, then it gets automatically registered.
int GetDamageSystemVersionChange ()
Re-sets DamageSystem changes.
void ~ItemBase ()
void SetCEBasedQuantity ()
void LockToParent ()
Locks this item in it's current attachment slot of its parent. This makes the "locked" icon visible in inventory over this item.
void UnlockFromParent ()
Unlocks this item from its attachment slot of its parent.
override void CombineItemsClient (EntityAI entity2, bool use_stack_max=true)
bool IsLiquidPresent ()
bool IsLiquidContainer ()
int GetLiquidContainerMask ()
bool IsBloodContainer ()
bool IsNVG ()
bool IsExplosive ()
string GetExplosiveTriggerSlotName ()
bool IsLightSource ()
bool CanBeRepairedByCrafting ()
bool IsFacingPlayer (PlayerBase player, string selection)
bool IsPlayerInside (PlayerBase player, string selection)
override bool CanObstruct ()
override bool IsBeingPlaced ()
void SetIsBeingPlaced (bool is_being_placed)
void OnEndPlacement ()
override bool IsHologram ()
bool CanBeDigged ()
int GetOnDigWormsAmount ()
bool CanMakeGardenplot ()
void SetIsHologram (bool is_hologram)
override void OnMovedInsideCargo (EntityAI container)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EOnContact (IEntity other, Contact extra)
void RefreshPhysics ()
override void OnCreatePhysics ()
override void OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void EEDelete (EntityAI parent)
override void EEKilled (Object killer)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override string ChangeIntoOnAttach (string slot)
override string ChangeIntoOnDetach ()
void ExplodeAmmo ()
void DoAmmoExplosion ()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
bool DamageItemInCargo (float damage)
bool DamageItemAttachments (float damage)
override bool IsSplitable ()
override bool CanBeSplit ()
override void SplitIntoStackMaxClient (EntityAI destination_entity, int slot_id)
void SplitIntoStackMax (EntityAI destination_entity, int slot_id, PlayerBase player)
override void SplitIntoStackMaxEx (EntityAI destination_entity, int slot_id)
void SplitIntoStackMaxToInventoryLocationClient (notnull InventoryLocation dst)
void SplitIntoStackMaxCargoClient (EntityAI destination_entity, int idx, int row, int col)
void SplitIntoStackMaxToInventoryLocation (notnull InventoryLocation dst)
ItemBase SplitIntoStackMaxToInventoryLocationEx (notnull InventoryLocation dst)
void SplitIntoStackMaxCargo (EntityAI destination_entity, int idx, int row, int col)
void SplitIntoStackMaxHandsClient (PlayerBase player)
void SplitIntoStackMaxHands (PlayerBase player)
void SplitItemToInventoryLocation (notnull InventoryLocation dst)
void SplitItem (PlayerBase player)
void OnQuantityChanged (float delta)
Called on server side when this item's quantity is changed. Call super.OnQuantityChanged(); first when overriding this event.
void OnAttachmentQuantityChanged (ItemBase item)
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
void OnAttachmentQuantityChangedEx (ItemBase item, float delta)
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void OnRightClick ()
override bool CanBeCombined (EntityAI other_item, bool reservation_check=true, bool stack_max_limit=false)
bool IsCombineAll (ItemBase other_item, bool use_stack_max=false)
bool IsResultOfSplit ()
void SetResultOfSplit (bool value)
int ComputeQuantityUsed (ItemBase other_item, bool use_stack_max=true)
float ComputeQuantityUsedEx (ItemBase other_item, bool use_stack_max=true)
override void CombineItemsEx (EntityAI entity2, bool use_stack_max=true)
void CombineItems (ItemBase other_item, bool use_stack_max=true)
void OnCombine (ItemBase other_item)
void GetRecipesActions (Man player, out TSelectableActionInfoArray outputList)
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
void OnActivatedByTripWire ()
void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
bool CanExplodeInFire ()
bool CanEat ()
override bool IsIgnoredByConstruction ()
bool HasFoodStage ()
FoodStage GetFoodStage ()
overridden on Edible_Base; so we don't have to parse configs all the time
bool CanBeCooked ()
bool CanBeCookedOnStick ()
bool CanRepair (ItemBase item_repair_kit)
bool Repair (PlayerBase player, ItemBase item_repair_kit, float specialty_weight)
int GetItemSize ()
bool CanBeMovedOverride ()
void SetCanBeMovedOverride (bool setting)
void MessageToOwnerStatus (string text)
Send message to owner player in grey color.
void MessageToOwnerAction (string text)
Send message to owner player in yellow color.
void MessageToOwnerFriendly (string text)
Send message to owner player in green color.
void MessageToOwnerImportant (string text)
Send message to owner player in red color.
override bool IsItemBase ()
override bool KindOf (string tag)
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
int NameToID (string name)
string IDToName (int id)
void OnSyncVariables (ParamsReadContext ctx)
DEPRECATED (most likely)
override void SerializeNumericalVars (array< float > floats_out)
override void DeSerializeNumericalVars (array< float > floats)
override void WriteVarsToCTX (ParamsWriteContext ctx)
override bool ReadVarsFromCTX (ParamsReadContext ctx, int version=-1)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void AfterStoreLoad ()
override void EEOnAfterLoad ()
bool CanBeDisinfected ()
override void OnVariablesSynchronized ()
override bool SetQuantity (float value, bool destroy_config=true, bool destroy_forced=false, bool allow_client=false, bool clamp_to_stack_max=true)
Set item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted.
bool AddQuantity (float value, bool destroy_config=true, bool destroy_forced=false)
add item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted
void SetQuantityMax ()
override void SetQuantityToMinimum ()
void SetQuantityNormalized (float value, bool destroy_config=true, bool destroy_forced=false)
Sets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, setting 0.5 will result in value 2500)
override float GetQuantityNormalized ()
Gets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, value 2500 will result in 0.5)
float GetQuantityNormalizedScripted ()
override int GetQuantityMax ()
override int GetTargetQuantityMax (int attSlotID=-1)
override int GetQuantityMin ()
int GetQuantityInit ()
override bool HasQuantity ()
override float GetQuantity ()
bool IsFullQuantity ()
override float GetSingleInventoryItemWeightEx ()
float GetSingleInventoryItemWeight ()
override protected float GetWeightSpecialized (bool forceRecalc=false)
int GetNumberOfItems ()
Returns the number of items in cargo, otherwise returns 0(non-cargo objects). Recursive.
float GetUnitWeight (bool include_wetness=true)
Obsolete, use GetWeightEx instead.
override void ClearInventory ()
float GetEnergy ()
override void OnEnergyConsumed ()
override void OnEnergyAdded ()
void ConvertEnergyToQuantity ()
float GetHeatIsolationInit ()
float GetHeatIsolation ()
float GetDryingIncrement (string pIncrementName)
float GetSoakingIncrement (string pIncrementName)
override void SetWet (float value, bool allow_client=false)
override void AddWet (float value)
override void SetWetMax ()
override float GetWet ()
override float GetWetMax ()
override float GetWetMin ()
override float GetWetInit ()
override void OnWetChanged (float newVal, float oldVal)
override void OnWetLevelChanged (EWetnessLevel newLevel, EWetnessLevel oldLevel)
override EWetnessLevel GetWetLevel ()
override void SetStoreLoad (bool value)
override bool IsStoreLoad ()
override void SetStoreLoadedQuantity (float value)
override float GetStoreLoadedQuantity ()
float GetItemModelLength ()
float GetItemAttachOffset ()
override void SetCleanness (int value, bool allow_client=false)
override int GetCleanness ()
bool AllowFoodConsumption ()
int GetLockType ()
string GetLockSoundSet ()
override void SetColor (int r, int g, int b, int a)
override void GetColor (out int r, out int g, out int b, out int a)
gets item's color variable as components
bool IsColorSet ()
string GetColorString ()
Returns item's PROCEDURAL color as formated string, i.e. "#(argb,8,8,3)color(0.15,0.15,0.15,1.0,CO)".
override void SetLiquidType (int value, bool allow_client=false)
int GetLiquidTypeInit ()
override int GetLiquidType ()
protected void OnLiquidTypeChanged (int oldType, int newType)
void UpdateQuickbarShortcutVisibility (PlayerBase player)
To be called on moving item within character's inventory; 'player' should never be null.
void OnInventoryEnter (Man player)
Event called on item when it is placed in the player(Man) inventory, passes the owner as a parameter.
void OnInventoryExit (Man player)
Event called on item when it is removed from the player(Man) inventory, passes the old owner as a parameter.
override void OnPlacementStarted (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
bool ContainsAgent (int agent_id)
override void RemoveAgent (int agent_id)
override void RemoveAllAgents ()
override void RemoveAllAgentsExcept (int agents_to_keep_mask)
override void InsertAgent (int agent, float count=1)
void TransferAgents (int agents)
transfer agents from another item
override int GetAgents ()
bool LoadAgents (ParamsReadContext ctx, int version)
void SaveAgents (ParamsWriteContext ctx)
override void CheckForRoofLimited (float timeTresholdMS=3000)
Roof check for entity, limited by time (anti-spam solution)
float GetProtectionLevel (int type, bool consider_filter=false, int system=0)
override void EEOnCECreate ()
Called when entity is being created as new by CE/ Debug.
void Open ()
Implementations only.
void Close ()
bool IsOpen ()
override bool CanDisplayCargo ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReleaseAttachment (EntityAI attachment)
override bool IsHeavyBehaviour ()
override bool IsOneHandedBehaviour ()
override bool IsTwoHandedBehaviour ()
bool IsDeployable ()
float GetDeployTime ()
how long it takes to deploy this item in seconds
override void SetTakeable (bool pState)
override bool IsTakeable ()
bool IsActionTargetVisible ()
protected void PreLoadSoundAttachmentType ()
Attachment Sound Type getting from config file.
override string GetAttachmentSoundType ()
void SoundSynchRemoteReset ()
void SoundSynchRemote ()
bool IsSoundSynchRemote ()
string GetDeploySoundset ()
string GetPlaceSoundset ()
string GetLoopDeploySoundset ()
string GetDeployFinishSoundset ()
void SetIsPlaceSound (bool is_place_sound)
bool IsPlaceSound ()
void SetIsDeploySound (bool is_deploy_sound)
bool IsDeploySound ()
void PlayDeployLoopSoundEx ()
void StopDeployLoopSoundEx ()
void PlayDeploySound ()
void PlayDeployFinishSound ()
void PlayPlaceSound ()
bool CanPlayDeployLoopSound ()
void PlayAttachSound (string slot_type)
Plays sound on item attach. Be advised, the config structure may slightly change in 1.11 update to allow for more complex use.
void PlayDetachSound (string slot_type)
void OnApply (PlayerBase player)
float GetBandagingEffectivity ()
array< string > GetHeadHidingSelection ()
bool HidesSelectionBySlot ()
WrittenNoteData GetWrittenNoteData ()
void StopItemDynamicPhysics ()
void PerformDamageSystemReinit ()
void SetZoneDamageCEInit ()
Sets zone damages to match randomized global health set by CE (CE spawn only)
bool IsCoverFaceForShave (string slot_name)
DEPRECATED in use, but returns correct values nontheless. Check performed elsewhere.
void ProcessItemWetness (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
void ProcessItemTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
void HierarchyCheck (out bool hasParent, out bool hasRootAsPlayer, out ItemBase refParentIB)
protected void ProcessDecay (float delta, bool hasRootAsPlayer)
bool CanDecay ()
protected bool CanProcessDecay ()
protected bool CanHaveWetness ()
override void ProcessVariables ()
float GetTemperaturePerQuantityWeight ()
Used in heat comfort calculations only!
override float GetTemperatureFreezeThreshold ()
override float GetTemperatureThawThreshold ()
override float GetItemOverheatThreshold ()
override float GetTemperatureFreezeTime ()
override float GetTemperatureThawTime ()
void AffectLiquidContainerOnFill (int liquid_type, float amount)
bool IsCargoException4x3 (EntityAI item)
void CopyScriptPropertiesFrom (EntityAI oldItem)
void AddLightSourceItem (ItemBase lightsource)
Adds a light source child.
void RemoveLightSourceItem ()
ItemBase GetLightSourceItem ()
array< int > GetValidFinishers ()
returns an array of possible finishers
bool GetActionWidgetOverride (out typename name)
If we need a different (handheld)item action widget displayed, the logic goes in here.
bool PairWithDevice (notnull ItemBase otherDevice)
float GetBaitEffectivity ()
generic effectivity as a bait for animal catching
bool CanBeUsedForSuicide ()
void ProcessItemWetnessAndTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
Static Private Member Functions
static int GetDebugActionsMask ()
static bool HasDebugActionsMask (int mask)
static void SetDebugActionsMask (int mask)
static void AddDebugActionsMask (int mask)
static void RemoveDebugActionsMask (int mask)
static void ToggleDebugActionsMask (int mask)
static void PlayFireParticles (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void PlayBulletCasingEjectParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void PlayOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void UpdateOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void StopOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
Private Attributes
TInputActionMap m_InputActionMap
bool m_ActionsInitialize
bool m_RecipesInitialized
float m_VarQuantity
float m_VarQuantityPrev
int m_VarQuantityInit
int m_VarQuantityMin
int m_VarQuantityMax
int m_Count
float m_VarStackMax
float m_StoreLoadedQuantity = float.LOWEST
float m_VarWet
float m_VarWetPrev
float m_VarWetInit
float m_VarWetMin
float m_VarWetMax
int m_Cleanness
int m_CleannessInit
int m_CleannessMin
int m_CleannessMax
bool m_WantPlayImpactSound
bool m_CanPlayImpactSound = true
float m_ImpactSpeed
int m_ImpactSoundSurfaceHash
float m_HeatIsolation
float m_ItemModelLength
float m_ItemAttachOffset
int m_LiquidContainerMask
int m_VarLiquidType
int m_ItemBehaviour
int m_QuickBarBonus
bool m_IsBeingPlaced
bool m_IsHologram
bool m_IsPlaceSound
bool m_IsDeploySound
bool m_IsTakeable
bool m_IsSoundSynchRemote
bool m_ThrowItemOnDrop
bool m_ItemBeingDroppedPhys
bool m_CanBeMovedOverride
bool m_FixDamageSystemInit = false
bool can_this_be_combined
bool m_CanThisBeSplit
bool m_IsStoreLoad = false
bool m_CanShowQuantity
bool m_HasQuantityBar
protected bool m_CanBeDigged
protected bool m_IsResultOfSplit protected EffectSound m_DeployLoopSoundEx
distinguish if item has been created as new or it came from splitting (server only flag)
string m_SoundAttType
int m_ColorComponentR
int m_ColorComponentG
int m_ColorComponentB
int m_ColorComponentA
ItemBase m_LightSourceItem
ref TIntArray m_SingleUseActions
ref TIntArray m_ContinuousActions
ref TIntArray m_InteractActions
private int m_AttachedAgents
ref map< int, ref array< ref WeaponParticlesOnOverheating > > m_OnOverheatingEffect
bool m_IsOverheatingEffectActive
float m_OverheatingShots
ref Timer m_CheckOverheating
int m_ShotsToStartOverheating = 0
int m_MaxOverheatingValue = 0
float m_OverheatingDecayInterval = 1
ref array< ref OverheatingParticle > m_OverheatingParticles
protected ref TStringArray m_HeadHidingSelections
protected bool m_HideSelectionsBySlot
PluginAdminLog m_AdminLog
ref Timer m_PhysDropTimer
ref array< int > m_CompatibleLocks
protected int m_LockType
protected ref EffectSound m_LockingSound
protected string m_LockSoundSet
protected EffectSound m_SoundPlace
protected EffectSound m_SoundDeploy
protected EffectSound m_SoundDeployFinish
private float m_TemperaturePerQuantityWeight
Static Private Attributes
static ref map< typename, ref TInputActionMap > m_ItemTypeActionsMap = new map<typename, ref TInputActionMap>
static ref map< typename, ref TActionAnimOverrideMap > m_ItemActionOverrides = new map<typename, ref TActionAnimOverrideMap>
static int m_DebugActionsMask
static ref map< int, ref array< ref WeaponParticlesOnFire > > m_OnFireEffect
static ref map< int, ref array< ref WeaponParticlesOnBulletCasingEject > > m_OnBulletCasingEjectEffect
static ref map< string, int > m_WeaponTypeToID
static int m_LastRegisteredWeaponID = 0
Constructor & Destructor Documentation
~ItemBase()
void ~ItemBase () inline private
References SEffectManager::DestroyEffect(), GetGame(), InventoryLocation::GetParent(), GetPlayer(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), m_DeployLoopSoundEx, and m_LockingSound.
Member Function Documentation
AddAction()
void AddAction (typename actionName) inline private
References Debug::ActionLog(), ActionManagerBase(), ActionBase::GetInputType(), LogManager::IsActionLogEnable(), Debug::Log(), Debug::LogError(), m_ActionsInitialize, and m_InputActionMap.
AddDebugActionsMask()
static void AddDebugActionsMask (int mask) inline static private
AddLightSourceItem()
void AddLightSourceItem (ItemBase lightsource) inline private
Adds a light source child.
References m_LightSourceItem.
AddQuantity()
bool AddQuantity (float value, bool destroy_config = true, bool destroy_forced = false) inline private
add item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted
References GetQuantity(), and SetQuantity().
AddWet()
override void AddWet (float value) inline private
References GetWet(), and SetWet().
AffectLiquidContainerOnFill()
void AffectLiquidContainerOnFill (int liquid_type, float amount) private
AfterStoreLoad()
override void AfterStoreLoad () inline private
References GetStoreLoadedQuantity(), LOWEST, m_FixDamageSystemInit, PerformDamageSystemReinit(), SetQuantity(), and SetStoreLoadedQuantity().
AllowFoodConsumption()
bool AllowFoodConsumption () inline private
CanBeCombined()
override bool CanBeCombined (EntityAI other_item, bool reservation_check = true, bool stack_max_limit = false) inline private
References can_this_be_combined, GetQuantity(), GetQuantityMax(), GetType(), IsFullQuantity(), slotName, and GameConstants::STATE_RUINED.
CanBeCooked()
bool CanBeCooked () inline private
CanBeCookedOnStick()
bool CanBeCookedOnStick () inline private
CanBeDigged()
bool CanBeDigged () inline private
References m_CanBeDigged.
CanBeDisinfected()
bool CanBeDisinfected () inline private
CanBeMovedOverride()
bool CanBeMovedOverride () inline private
References m_CanBeMovedOverride.
CanBeRepairedByCrafting()
bool CanBeRepairedByCrafting () inline private
CanBeSplit()
override bool CanBeSplit () inline private
References GetQuantity(), and IsSplitable().
CanBeUsedForSuicide()
bool CanBeUsedForSuicide () inline private
CanDecay()
bool CanDecay () inline private
CanDisplayCargo()
override bool CanDisplayCargo () inline private
References IsOpen().
CanEat()
bool CanEat () inline private
CanExplodeInFire()
bool CanExplodeInFire () inline private
CanHaveWetness()
protected bool CanHaveWetness () inline private
CanMakeGardenplot()
bool CanMakeGardenplot () inline private
CanObstruct()
override bool CanObstruct () inline private
References g_Game, and ItemBase::IsPlayerInside().
CanPlayDeployLoopSound()
bool CanPlayDeployLoopSound () inline private
References IsBeingPlaced(), and IsSoundSynchRemote().
CanProcessDecay()
protected bool CanProcessDecay () inline private
CanPutAsAttachment()
override bool CanPutAsAttachment (EntityAI parent) inline private
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
References GameInventory::GetCargo(), CargoBase::GetItemCount(), and InventoryLocation::IsValid().
CanReceiveItemIntoCargo()
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
CanReleaseAttachment()
override bool CanReleaseAttachment (EntityAI attachment) inline private
CanRepair()
bool CanRepair (ItemBase item_repair_kit) inline private
References GetPlugin().
ChangeIntoOnAttach()
override string ChangeIntoOnAttach (string slot) inline private
ChangeIntoOnDetach()
override string ChangeIntoOnDetach () inline private
CheckForRoofLimited()
override void CheckForRoofLimited (float timeTresholdMS = 3000) inline private
Roof check for entity, limited by time (anti-spam solution)
References GetGame(), and CGame::GetTime().
CheckOverheating()
void CheckOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") inline private
References IsOverheatingEffectActive(), m_MaxOverheatingValue, m_OverheatingShots, m_ShotsToStartOverheating, StartOverheating(), StopOverheating(), and UpdateOverheating().
ClearInventory()
override void ClearInventory () inline private
References GameInventory::EnumerateInventory(), GetGame(), and CGame::ObjectDelete().
Close()
void Close () private
CombineItems()
void CombineItems (ItemBase other_item, bool use_stack_max = true) inline private
References AddQuantity(), ItemBase::CanBeCombined(), ComputeQuantityUsedEx(), GetQuantity(), ItemBase::OnCombine(), and Math::Round().
CombineItemsClient()
override void CombineItemsClient (EntityAI entity2, bool use_stack_max = true) inline private
References GameInventory::c_InventoryReservationTimeoutShortMS, ScriptInputUserData::CanStoreInputUserData(), CombineItems(), GetGame(), CGame::GetPlayer(), INPUT_UDT_ITEM_MANIPULATION, IsCombineAll(), ScriptInputUserData::Send(), and Serializer::Write().
CombineItemsEx()
override void CombineItemsEx (EntityAI entity2, bool use_stack_max = true) inline private
References CombineItems().
ComputeQuantityUsed()
int ComputeQuantityUsed (ItemBase other_item, bool use_stack_max = true) inline private
References ComputeQuantityUsedEx().
ComputeQuantityUsedEx()
float ComputeQuantityUsedEx (ItemBase other_item, bool use_stack_max = true) inline private
References GetQuantity(), and GetQuantityMax().
ContainsAgent()
bool ContainsAgent (int agent_id) inline private
References m_AttachedAgents.
ConvertEnergyToQuantity()
void ConvertEnergyToQuantity () inline private
References GetGame(), HasQuantity(), and SetQuantityNormalized().
CopyScriptPropertiesFrom()
void CopyScriptPropertiesFrom (EntityAI oldItem) inline private
DamageItemAttachments()
bool DamageItemAttachments (float damage) inline private
References Math::RandomInt().
DamageItemInCargo()
bool DamageItemInCargo (float damage) inline private
References GetItem(), and Math::RandomInt().
DeSerializeNumericalVars()
override void DeSerializeNumericalVars (array< float > floats) inline private
References m_ColorComponentA, m_ColorComponentB, m_ColorComponentG, m_ColorComponentR, m_IsStoreLoad, Math::Round(), SetCleanness(), SetLiquidType(), SetQuantity(), SetStoreLoadedQuantity(), SetWet(), VARIABLE_CLEANNESS, VARIABLE_COLOR, VARIABLE_LIQUIDTYPE, VARIABLE_QUANTITY, and VARIABLE_WET.
DoAmmoExplosion()
void DoAmmoExplosion () inline private
References CGame::CreateSoundOnObject(), ExplodeAmmo(), GetGame(), and Math::RandomInt().
EEDelete()
override void EEDelete (EntityAI parent) inline private
References InventoryLocation::GetParent(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), and ItemBase::OnInventoryExit().
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
drops content of container when ruined in fireplace
References GetGame(), CargoBase::GetItem(), CargoBase::GetItemCount(), IsResultOfSplit(), m_Cleanness, SetCleanness(), SetResultOfSplit(), and GameConstants::STATE_RUINED.
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
References component, DamageItemAttachments(), DamageItemInCargo(), TotalDamageResult::GetDamage(), ItemBase::IsClothing(), ItemBase::IsItemTent(), and Math::RandomInt().
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
References InventoryLocation::Copy(), CGame::GetAnalyticsClient(), GetGame(), InventoryLocation::GetItem(), InventoryLocation::GetParent(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), m_ThrowItemOnDrop, AnalyticsManagerClient::OnItemAttachedAtPlayer(), and InventoryLocation::Reset().
EEKilled()
override void EEKilled (Object killer) inline private
item is able to explode in fire
References ItemBase::CanExplodeInFire(), Explode(), ExplodeAmmo(), and GameConstants::ITEM_TEMPERATURE_TO_EXPLODE_MIN.
EEOnAfterLoad()
override void EEOnAfterLoad () inline private
References GetRemotelyActivatedItemBehaviour(), m_FixDamageSystemInit, and RemotelyActivatedItemBehaviour::OnAfterLoad().
EEOnCECreate()
override void EEOnCECreate () inline private
Called when entity is being created as new by CE/ Debug.
References SetCEBasedQuantity(), and SetZoneDamageCEInit().
EOnContact()
override void EOnContact (IEntity other, Contact extra) inline private
References vector::Distance(), GetPosition, m_CanPlayImpactSound, m_ImpactSoundSurfaceHash, m_ImpactSpeed, and m_WantPlayImpactSound.
ExplodeAmmo()
void ExplodeAmmo () inline private
References CALL_CATEGORY_SYSTEM, and Math::RandomFloat().
GetActions()
override void GetActions (typename action_input_type , out array< ActionBase_Basic > actions) inline private
References InitializeActions(), m_ActionsInitialize, and m_InputActionMap.
GetActionWidgetOverride()
bool GetActionWidgetOverride (out typename name) inline private
If we need a different (handheld)item action widget displayed, the logic goes in here.
GetAgents()
override int GetAgents () inline private
References m_AttachedAgents.
GetAttachmentSoundType()
override string GetAttachmentSoundType () inline private
References m_SoundAttType.
GetBaitEffectivity()
float GetBaitEffectivity () inline private
generic effectivity as a bait for animal catching
References GetQuantityNormalized(), and HasQuantity().
GetBandagingEffectivity()
float GetBandagingEffectivity () inline private
GetCleanness()
override int GetCleanness () inline private
References m_Cleanness.
GetColor()
override void GetColor (out int r, out int g, out int b, out int a) inline private
gets item's color variable as components
References m_ColorComponentA, m_ColorComponentB, m_ColorComponentG, and m_ColorComponentR.
GetColorString()
string GetColorString () inline private
Returns item's PROCEDURAL color as formated string, i.e. "#(argb,8,8,3)color(0.15,0.15,0.15,1.0,CO)".
References GetColor().
GetDamageSystemVersionChange()
int GetDamageSystemVersionChange () inline private
Re-sets DamageSystem changes.
Returns
storage version on which the config changes occured (default -1, to be overriden!)
Note
Significant changes to DamageSystem in item configs have to be re-set by increasing the storage version and overriding this method. Default return is -1 (does nothing).
GetDebugActions()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline private
References IsLiquidContainer(), and SAT_DEBUG_ACTION.
GetDebugActionsMask()
static int GetDebugActionsMask () inline static private
GetDeployFinishSoundset()
string GetDeployFinishSoundset () private
GetDeploySoundset()
string GetDeploySoundset () private
GetDeployTime()
float GetDeployTime () inline private
how long it takes to deploy this item in seconds
References UATimeSpent::DEFAULT_DEPLOY.
GetDisinfectQuantity()
float GetDisinfectQuantity (int system = 0, Param param1 = null) inline private
GetDryingIncrement()
float GetDryingIncrement (string pIncrementName) inline private
References CGame::ConfigGetFloat(), GetGame(), and GetType().
GetEnergy()
float GetEnergy () inline private
GetExplosiveTriggerSlotName()
string GetExplosiveTriggerSlotName () inline private
GetFilterDamageRatio()
float GetFilterDamageRatio () inline private
GetFoodStage()
FoodStage GetFoodStage () inline private
overridden on Edible_Base; so we don't have to parse configs all the time
GetHeadHidingSelection()
array< string > GetHeadHidingSelection () inline private
References m_HeadHidingSelections.
GetHeatIsolation()
float GetHeatIsolation () inline private
References m_HeatIsolation.
GetHeatIsolationInit()
float GetHeatIsolationInit () inline private
GetInfectionChance()
float GetInfectionChance (int system = 0, Param param = null) inline private
Infection chance while/after using this item, originally used for wound infection after bandaging, params 'system' and 'param' can allow usage by other systems as well.
GetItemAttachOffset()
float GetItemAttachOffset () inline private
GetItemModelLength()
float GetItemModelLength () inline private
GetItemOverheatThreshold()
override float GetItemOverheatThreshold () inline private
References GetLiquidType(), IsLiquidContainer(), and LIQUID_NONE.
GetItemSize()
int GetItemSize () inline private
GetLight()
ScriptedLightBase GetLight () private
GetLightSourceItem()
ItemBase GetLightSourceItem () inline private
References m_LightSourceItem.
GetLiquidContainerMask()
int GetLiquidContainerMask () inline private
References m_LiquidContainerMask.
GetLiquidType()
override int GetLiquidType () inline private
References m_VarLiquidType.
GetLiquidTypeInit()
int GetLiquidTypeInit () inline private
GetLockSoundSet()
string GetLockSoundSet () inline private
References m_LockSoundSet.
GetLockType()
int GetLockType () inline private
References m_LockType.
GetLoopDeploySoundset()
string GetLoopDeploySoundset () private
GetMuzzleID()
int GetMuzzleID () inline private
Returns global muzzle ID. If not found, then it gets automatically registered.
References GetType(), m_LastRegisteredWeaponID, and m_WeaponTypeToID.
GetNumberOfItems()
int GetNumberOfItems () inline private
Returns the number of items in cargo, otherwise returns 0(non-cargo objects). Recursive.
References Class::CastTo().
GetOnDigWormsAmount()
int GetOnDigWormsAmount () inline private
GetOverheatingCoef()
float GetOverheatingCoef () inline private
References m_MaxOverheatingValue, m_OverheatingShots, and m_ShotsToStartOverheating.
GetOverheatingValue()
float GetOverheatingValue () inline private
References m_OverheatingShots.
GetPlaceSoundset()
string GetPlaceSoundset () private
GetProtectionLevel()
float GetProtectionLevel (int type, bool consider_filter = false, int system = 0) inline private
References CGame::ConfigGetFloat(), DEF_BIOLOGICAL, DEF_CHEMICAL, GetGame(), GetQuantity(), GetType(), and HasQuantity().
GetQuantity()
override float GetQuantity () inline private
References m_VarQuantity.
GetQuantityInit()
int GetQuantityInit () inline private
References m_VarQuantityInit.
GetQuantityMax()
override int GetQuantityMax () inline private
References InventoryLocation::GetSlot(), and GetTargetQuantityMax().
GetQuantityMin()
override int GetQuantityMin () inline private
References m_VarQuantityMin.
GetQuantityNormalized()
override float GetQuantityNormalized () inline private
Gets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, value 2500 will result in 0.5)
References GetQuantityMax(), GetQuantityMin(), Math::InverseLerp(), and m_VarQuantity.
GetQuantityNormalizedScripted()
float GetQuantityNormalizedScripted () inline private
References GetQuantityNormalized().
GetQuickBarBonus()
override int GetQuickBarBonus () inline private
References m_QuickBarBonus.
GetRecipesActions()
void GetRecipesActions (Man player, out TSelectableActionInfoArray outputList) inline private
References HumanInventory::GetEntityInHands(), EntityAI::GetHumanInventory(), GetPlugin(), and SAT_CRAFTING.
GetSingleInventoryItemWeight()
float GetSingleInventoryItemWeight () inline private
References GetSingleInventoryItemWeightEx().
GetSingleInventoryItemWeightEx()
override float GetSingleInventoryItemWeightEx () inline private
GetSoakingIncrement()
float GetSoakingIncrement (string pIncrementName) inline private
References CGame::ConfigGetFloat(), GetGame(), and GetType().
GetStoreLoadedQuantity()
override float GetStoreLoadedQuantity () inline private
References m_StoreLoadedQuantity.
GetTargetQuantityMax()
override int GetTargetQuantityMax (int attSlotID = -1) inline private
References InventorySlots::GetStackMaxForSlotId(), IsSplitable(), m_VarQuantityMax, and m_VarStackMax.
GetTemperatureFreezeThreshold()
override float GetTemperatureFreezeThreshold () inline private
References GetLiquidType(), IsLiquidContainer(), and LIQUID_NONE.
GetTemperatureFreezeTime()
override float GetTemperatureFreezeTime () inline private
References GetQuantityNormalized(), HasQuantity(), Math::Lerp(), Math::Max(), and GameConstants::TEMPERATURE_TIME_FREEZE_MIN.
GetTemperaturePerQuantityWeight()
float GetTemperaturePerQuantityWeight () inline private
Used in heat comfort calculations only!
References GameConstants::ITEM_TEMPERATURE_QUANTITY_WEIGHT_MULTIPLIER, and m_TemperaturePerQuantityWeight.
GetTemperatureThawThreshold()
override float GetTemperatureThawThreshold () inline private
References GetLiquidType(), IsLiquidContainer(), and LIQUID_NONE.
GetTemperatureThawTime()
override float GetTemperatureThawTime () inline private
References GetQuantityNormalized(), HasQuantity(), Math::Lerp(), Math::Max(), GameConstants::TEMPERATURE_TIME_FREEZE_MIN, and GameConstants::TEMPERATURE_TIME_THAW_MIN.
GetUnitWeight()
float GetUnitWeight (bool include_wetness = true) inline private
Obsolete, use GetWeightEx instead.
References GetWet(), IsLiquidContainer(), and IsSplitable().
GetValidFinishers()
array< int > GetValidFinishers () inline private
returns an array of possible finishers
GetWeightSpecialized()
override protected float GetWeightSpecialized (bool forceRecalc = false) inline private
References GetEnergy(), GetQuantity(), IsSplitable(), and WeightDebugData::SetCalcDetails().
GetWet()
override float GetWet () inline private
References m_VarWet.
GetWetInit()
override float GetWetInit () inline private
References m_VarWetInit.
GetWetLevel()
override EWetnessLevel GetWetLevel () inline private
References m_VarWet.
GetWetMax()
override float GetWetMax () inline private
References m_VarWetMax.
GetWetMin()
override float GetWetMin () inline private
References m_VarWetMin.
GetWrittenNoteData()
WrittenNoteData GetWrittenNoteData () inline private
HasDebugActionsMask()
static bool HasDebugActionsMask (int mask) inline static private
HasFoodStage()
bool HasFoodStage () inline private
References CGame::ConfigIsExisting(), GetGame(), and GetType().
HasMuzzle()
bool HasMuzzle () inline private
Returns true if this item has a muzzle (weapons, suppressors)
HasQuantity()
override bool HasQuantity () inline private
References GetQuantityMax(), and GetQuantityMin().
HidesSelectionBySlot()
bool HidesSelectionBySlot () inline private
References m_HideSelectionsBySlot.
HierarchyCheck()
void HierarchyCheck (out bool hasParent, out bool hasRootAsPlayer, out ItemBase refParentIB) inline private
IDToName()
string IDToName (int id) inline private
References GetPlugin().
IncreaseOverheating()
void IncreaseOverheating (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline private
References CALL_CATEGORY_SYSTEM, CheckOverheating(), m_CheckOverheating, m_MaxOverheatingValue, m_OverheatingDecayInterval, m_OverheatingShots, and Timer::Stop().
InitializeActions()
void InitializeActions () inline private
References m_InputActionMap, m_ItemTypeActionsMap, ItemBase::SetActions(), and Type.
InitItemVariables()
override void InitItemVariables () inline private
References can_this_be_combined, GetHeatIsolationInit(), GetItemAttachOffset(), GetItemModelLength(), GetLiquidTypeInit(), GetQuantity(), GetQuantityMin(), GetWetMax(), GetWetMin(), HasQuantity(), IsLiquidContainer(), m_CanBeDigged, m_CanBeMovedOverride, m_CanShowQuantity, m_CanThisBeSplit, m_Cleanness, m_CleannessInit, m_CleannessMax, m_CleannessMin, m_CompatibleLocks, m_Count, m_HasQuantityBar, m_HeatIsolation, m_ImpactSpeed, m_IsBeingPlaced, m_IsDeploySound, m_IsHologram, m_IsPlaceSound, m_IsSoundSynchRemote, m_IsTakeable, m_ItemAttachOffset, m_ItemBehaviour, m_ItemModelLength, m_LiquidContainerMask, m_LockSoundSet, m_LockType, m_TemperaturePerQuantityWeight, m_VarLiquidType, m_VarQuantity, m_VarQuantityInit, m_VarQuantityMax, m_VarQuantityMin, m_VarStackMax, m_VarWet, m_VarWetInit, m_VarWetMax, m_VarWetMin, m_WantPlayImpactSound, and UsesGlobalDeploy().
InsertAgent()
override void InsertAgent (int agent, float count = 1) inline private
References m_AttachedAgents.
IsActionTargetVisible()
bool IsActionTargetVisible () inline private
IsBeingPlaced()
override bool IsBeingPlaced () inline private
References m_IsBeingPlaced.
IsBloodContainer()
bool IsBloodContainer () inline private
IsCargoException4x3()
bool IsCargoException4x3 (EntityAI item) inline private
IsColorSet()
bool IsColorSet () inline private
References VARIABLE_COLOR.
IsCombineAll()
bool IsCombineAll (ItemBase other_item, bool use_stack_max = false) inline private
References ComputeQuantityUsed().
IsCoverFaceForShave()
bool IsCoverFaceForShave (string slot_name) inline private
DEPRECATED in use, but returns correct values nontheless. Check performed elsewhere.
IsDeployable()
bool IsDeployable () inline private
IsDeploySound()
bool IsDeploySound () inline private
References m_IsDeploySound.
IsExplosive()
bool IsExplosive () inline private
explosive
IsFacingPlayer()
bool IsFacingPlayer (PlayerBase player, string selection) inline private
IsFullQuantity()
bool IsFullQuantity () inline private
References GetQuantity(), and GetQuantityMax().
IsHeavyBehaviour()
override bool IsHeavyBehaviour () inline private
References m_ItemBehaviour.
IsHologram()
override bool IsHologram () inline private
References m_IsHologram.
IsIgnoredByConstruction()
override bool IsIgnoredByConstruction () inline private
IsItemBase()
override bool IsItemBase () inline private
IsLightSource()
bool IsLightSource () inline private
IsLiquidContainer()
bool IsLiquidContainer () inline private
References m_LiquidContainerMask.
IsLiquidPresent()
bool IsLiquidPresent () inline private
References GetLiquidType(), and HasQuantity().
IsNVG()
bool IsNVG () inline private
IsOneHandedBehaviour()
override bool IsOneHandedBehaviour () inline private
References m_ItemBehaviour.
IsOpen()
bool IsOpen () inline private
IsOverheatingEffectActive()
bool IsOverheatingEffectActive () inline private
References m_IsOverheatingEffectActive.
IsPlaceSound()
bool IsPlaceSound () inline private
References m_IsPlaceSound.
IsPlayerInside()
bool IsPlayerInside (PlayerBase player, string selection) inline private
IsResultOfSplit()
bool IsResultOfSplit () inline private
IsSoundSynchRemote()
bool IsSoundSynchRemote () inline private
References m_IsSoundSynchRemote.
IsSplitable()
override bool IsSplitable () inline private
References m_CanThisBeSplit.
IsStoreLoad()
override bool IsStoreLoad () inline private
References m_IsStoreLoad.
IsTakeable()
override bool IsTakeable () inline private
References m_IsTakeable.
IsTwoHandedBehaviour()
override bool IsTwoHandedBehaviour () inline private
References m_ItemBehaviour.
ItemBase()
void ItemBase () inline private
References GetGame(), GetMuzzleID(), GetPlugin(), HasMuzzle(), LoadParticleConfigOnFire(), LoadParticleConfigOnOverheating(), m_ActionsInitialize, m_AdminLog, m_ContinuousActions, m_HeadHidingSelections, m_HideSelectionsBySlot, m_InteractActions, m_QuickBarBonus, m_ShotsToStartOverheating, m_SingleUseActions, Math::Max(), PreLoadSoundAttachmentType(), and ItemBase::SetActionAnimOverrides().
KillAllOverheatingParticles()
void KillAllOverheatingParticles () inline private
References OverheatingParticle::GetParticle(), m_OverheatingParticles, and Particle::Stop().
KindOf()
override bool KindOf (string tag) inline private
References CGame::ConfigGetTextArray(), GetGame(), and GetType().
LoadAgents()
bool LoadAgents (ParamsReadContext ctx, int version) inline private
References m_AttachedAgents, and Serializer::Read().
LoadParticleConfigOnFire()
void LoadParticleConfigOnFire (int id) inline private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), GetType(), m_OnBulletCasingEjectEffect, and m_OnFireEffect.
LoadParticleConfigOnOverheating()
void LoadParticleConfigOnOverheating (int id) inline private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetType(), Error(), GetGame(), GetType(), m_MaxOverheatingValue, m_OnOverheatingEffect, m_OverheatingDecayInterval, and m_ShotsToStartOverheating.
LockToParent()
void LockToParent () inline private
Locks this item in it's current attachment slot of its parent. This makes the "locked" icon visible in inventory over this item.
References InventoryLocation::GetSlot().
MessageToOwnerAction()
void MessageToOwnerAction (string text) inline private
Send message to owner player in yellow color.
Returns
void
item_stone.MessageToOwnerAction("Some Action Message");
MessageToOwnerFriendly()
void MessageToOwnerFriendly (string text) inline private
Send message to owner player in green color.
Returns
void
item_stone.MessageToOwnerFriendly("Some Friendly Message");
MessageToOwnerImportant()
void MessageToOwnerImportant (string text) inline private
Send message to owner player in red color.
Returns
void
item_stone.MessageToOwnerImportant("Some Important Message");
MessageToOwnerStatus()
void MessageToOwnerStatus (string text) inline private
Send message to owner player in grey color.
Returns
void
item_stone.MessageToOwnerStatus("Some Status Message");
NameToID()
int NameToID (string name) inline private
References GetPlugin(), and name.
OnAction()
override bool OnAction (int action_id, Man player, ParamsReadContext ctx) inline private
References AddQuantity(), AddWet(), GetGame(), GetLiquidType(), GetPlugin(), GetQuantityMax(), GetWetMax(), InsertAgent(), PluginItemDiagnostic(), RemoveAgent(), SetLiquidType(), SetQuantity(), and SetQuantityMax().
OnActivatedByItem()
void OnActivatedByItem (notnull ItemBase item) private
Called when this item is activated by other.
OnActivatedByTripWire()
void OnActivatedByTripWire () private
DEPRECATED use OnActivatedByItem below Called when this item is activated from a trip wire that was stepped on.
OnApply()
void OnApply (PlayerBase player) private
OnAttachmentQuantityChanged()
void OnAttachmentQuantityChanged (ItemBase item) inline private
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
OnAttachmentQuantityChangedEx()
void OnAttachmentQuantityChangedEx (ItemBase item, float delta) inline private
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
References OnAttachmentQuantityChanged().
OnCombine()
void OnCombine (ItemBase other_item) inline private
OnCreatePhysics()
override void OnCreatePhysics () inline private
References ItemBase::RefreshPhysics().
OnEndPlacement()
void OnEndPlacement () inline private
OnEnergyAdded()
override void OnEnergyAdded () inline private
References ConvertEnergyToQuantity().
OnEnergyConsumed()
override void OnEnergyConsumed () inline private
References ConvertEnergyToQuantity().
OnInventoryEnter()
void OnInventoryEnter (Man player) inline private
Event called on item when it is placed in the player(Man) inventory, passes the owner as a parameter.
References m_CanPlayImpactSound.
OnInventoryExit()
void OnInventoryExit (Man player) inline private
Event called on item when it is removed from the player(Man) inventory, passes the old owner as a parameter.
OnItemAttachmentSlotChanged()
override void OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
OnItemInHandsPlayerSwimStart()
void OnItemInHandsPlayerSwimStart (PlayerBase player) private
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
References ActionManagerBase(), ActionBase::GetID(), ItemBase::IsElectricAppliance(), EntityAI::IsMan(), ItemBase::OnInventoryEnter(), ItemBase::OnInventoryExit(), and ActionBase::OnItemLocationChanged().
OnLiquidTypeChanged()
protected void OnLiquidTypeChanged (int oldType, int newType) inline private
References LIQUID_NONE.
OnMovedInsideCargo()
override void OnMovedInsideCargo (EntityAI container) inline private
OnOverheatingDecay()
void OnOverheatingDecay () inline private
References CALL_CATEGORY_GAMEPLAY, CheckOverheating(), m_CheckOverheating, m_MaxOverheatingValue, m_OverheatingDecayInterval, m_OverheatingShots, and Timer::Stop().
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
References GetGame(), m_AdminLog, and SetIsDeploySound().
OnPlacementStarted()
override void OnPlacementStarted (Man player) inline private
References SetTakeable().
OnQuantityChanged()
void OnQuantityChanged (float delta) inline private
Called on server side when this item's quantity is changed. Call super.OnQuantityChanged(); first when overriding this event.
References ErrorEx, GetLiquidType(), GetLiquidTypeInit(), GetQuantityNormalized(), IsLiquidContainer(), LIQUID_NONE, and SetLiquidType().
OnRightClick()
override void OnRightClick () inline private
References GameInventory::c_InventoryReservationTimeoutShortMS, ItemBase::CanBeSplit(), ScriptInputUserData::CanStoreInputUserData(), InventoryLocation::GetCol(), GetDayZGame(), InventoryLocation::GetFlip(), GetGame(), InventoryLocation::GetIdx(), InventoryLocation::GetParent(), CGame::GetPlayer(), GetPlayer(), InventoryLocation::GetRow(), GetType(), INPUT_UDT_ITEM_MANIPULATION, ScriptInputUserData::Send(), InventoryLocation::SetCargo(), InventoryLocation::SetGround(), SplitItem(), Serializer::Write(), and InventoryLocation::WriteToContext().
Referenced by VicinitySlotsContainer::MouseClick().
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
References SEffectManager::DestroyEffect(), GetPosition, ItemBase::GetWrittenNoteData(), EffectSound::IsSoundPlaying(), m_LockingSound, WrittenNoteData::OnRPC(), SEffectManager::PlaySound(), and Serializer::Read().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References Class::CastTo(), ItemBase::GetDamageSystemVersionChange(), GetRemotelyActivatedItemBehaviour(), LoadAgents(), m_FixDamageSystemInit, m_IsStoreLoad, MAX, RemotelyActivatedItemBehaviour::OnStoreLoad(), and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
References GetRemotelyActivatedItemBehaviour(), RemotelyActivatedItemBehaviour::OnStoreSave(), SaveAgents(), and Serializer::Write().
OnSyncVariables()
void OnSyncVariables (ParamsReadContext ctx) inline private
DEPRECATED (most likely)
References ItemVariableFlags::FLOAT, Serializer::Read(), and ReadVarsFromCTX().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References CanPlayDeployLoopSound(), dBodyIsDynamic(), UIManager::FindMenu(), GetGame(), CGame::GetUIManager(), IsDeploySound(), IsSplitable(), m_DeployLoopSoundEx, m_ImpactSoundSurfaceHash, m_ImpactSpeed, m_Initialized, m_VarQuantity, m_VarQuantityPrev, m_VarWet, m_VarWetPrev, m_WantPlayImpactSound, MENU_INVENTORY, OnWetChanged(), PlayDeployLoopSoundEx(), PlayDeploySound(), UIScriptedMenu::Refresh(), and StopDeployLoopSoundEx().
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
References GetQuantityMin(), InventorySlots::GetSlotName(), HasQuantity(), m_VarQuantityMax, and PlayAttachSound().
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id) inline private
References GetQuantityMin(), HasQuantity(), and m_VarQuantityMax.
OnWetChanged()
override void OnWetChanged (float newVal, float oldVal) inline private
References OnWetLevelChanged().
OnWetLevelChanged()
override void OnWetLevelChanged (EWetnessLevel newLevel, EWetnessLevel oldLevel) inline private
Open()
void Open () private
Implementations only.
OverrideActionAnimation()
void OverrideActionAnimation (typename action , int commandUID, int stanceMask = -1, int commandUIDProne = -1) inline private
References ActionOverrideData::m_CommandUID, ActionOverrideData::m_CommandUIDProne, m_ItemActionOverrides, ActionOverrideData::m_StanceMask, and Type.
PairWithDevice()
bool PairWithDevice (notnull ItemBase otherDevice) inline private
References RemotelyActivatedItemBehaviour::GeneratePersistentID(), GetGame(), and RemoteDetonatorTrigger::SetControlledDevice().
PerformDamageSystemReinit()
void PerformDamageSystemReinit () inline private
PlayAttachSound()
void PlayAttachSound (string slot_type) inline private
Plays sound on item attach. Be advised, the config structure may slightly change in 1.11 update to allow for more complex use.
References GetGame(), GetPosition, GetType(), SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
PlayBulletCasingEjectParticles()
static void PlayBulletCasingEjectParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline static private
References m_OnBulletCasingEjectEffect.
PlayDeployFinishSound()
void PlayDeployFinishSound () inline private
References ItemBase::GetDeployFinishSoundset(), GetGame(), GetPosition, Debug::Log(), m_SoundDeployFinish, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
PlayDeployLoopSoundEx()
void PlayDeployLoopSoundEx () inline private
References GetGame(), ItemBase::GetLoopDeploySoundset(), GetPosition, Debug::Log(), m_DeployLoopSoundEx, and SEffectManager::PlaySound().
PlayDeploySound()
void PlayDeploySound () inline private
References ItemBase::GetDeploySoundset(), GetGame(), GetPosition, Debug::Log(), m_SoundDeploy, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
PlayDetachSound()
void PlayDetachSound (string slot_type) inline private
PlayFireParticles()
static void PlayFireParticles (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline static private
References m_OnFireEffect.
PlayOverheatingParticles()
static void PlayOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline static private
PlayPlaceSound()
void PlayPlaceSound () inline private
References GetGame(), ItemBase::GetPlaceSoundset(), GetPosition, Debug::Log(), m_SoundPlace, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
PreLoadSoundAttachmentType()
protected void PreLoadSoundAttachmentType () inline private
Attachment Sound Type getting from config file.
References m_SoundAttType.
ProcessDecay()
protected void ProcessDecay (float delta, bool hasRootAsPlayer) inline private
ProcessItemTemperature()
void ProcessItemTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB) inline private
References CanHaveTemperature(), g_Game, ItemBase::IsSelfAdjustingTemperature(), and GameConstants::TEMP_COEF_WORLD.
ProcessItemWetness()
void ProcessItemWetness (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB) inline private
References AddWet(), GetDryingIncrement(), m_VarWet, m_VarWetMax, m_VarWetMin, GameConstants::STATE_SOAKING_WET, GameConstants::WETNESS_RATE_WETTING_INSIDE, and GameConstants::WETNESS_RATE_WETTING_LIQUID.
ProcessItemWetnessAndTemperature()
void ProcessItemWetnessAndTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB) inline private
References ProcessItemTemperature(), and ProcessItemWetness().
ProcessVariables()
override void ProcessVariables () inline private
References CanDecay(), CanHaveTemperature(), CanHaveWetness(), CanProcessDecay(), g_Game, HierarchyCheck(), ProcessDecay(), ProcessItemTemperature(), and ProcessItemWetness().
ReadVarsFromCTX()
override bool ReadVarsFromCTX (ParamsReadContext ctx, int version = -1) inline private
References IsStoreLoad(), Serializer::Read(), SetCleanness(), SetColor(), SetLiquidType(), SetQuantity(), SetStoreLoadedQuantity(), SetWet(), VARIABLE_CLEANNESS, VARIABLE_COLOR, VARIABLE_LIQUIDTYPE, VARIABLE_QUANTITY, VARIABLE_TEMPERATURE, and VARIABLE_WET.
RefreshPhysics()
void RefreshPhysics () private
RegisterOverheatingParticle()
void RegisterOverheatingParticle (Particle p, float min_heat_coef, float max_heat_coef, int particle_id, Object parent, vector local_pos, vector local_ori) inline private
References m_OverheatingParticles, particle_id, OverheatingParticle::RegisterParticle(), OverheatingParticle::SetOverheatingLimitMax(), OverheatingParticle::SetOverheatingLimitMin(), and OverheatingParticle::SetParticleParams().
RemoveAction()
void RemoveAction (typename actionName) inline private
References GetGame(), ActionBase::GetInputType(), GetPlayer(), and m_InputActionMap.
RemoveAgent()
override void RemoveAgent (int agent_id) inline private
References ContainsAgent(), and m_AttachedAgents.
RemoveAllAgents()
override void RemoveAllAgents () inline private
References m_AttachedAgents.
RemoveAllAgentsExcept()
override void RemoveAllAgentsExcept (int agents_to_keep_mask) inline private
References m_AttachedAgents.
RemoveDebugActionsMask()
static void RemoveDebugActionsMask (int mask) inline static private
RemoveLightSourceItem()
void RemoveLightSourceItem () inline private
References m_LightSourceItem.
Repair()
bool Repair (PlayerBase player, ItemBase item_repair_kit, float specialty_weight) inline private
References GetPlugin().
SaveAgents()
void SaveAgents (ParamsWriteContext ctx) inline private
References m_AttachedAgents, and Serializer::Write().
SerializeNumericalVars()
override void SerializeNumericalVars (array< float > floats_out) inline private
References m_Cleanness, m_ColorComponentA, m_ColorComponentB, m_ColorComponentG, m_ColorComponentR, m_VarLiquidType, m_VarQuantity, m_VarWet, VARIABLE_CLEANNESS, VARIABLE_COLOR, VARIABLE_LIQUIDTYPE, VARIABLE_QUANTITY, and VARIABLE_WET.
SetActionAnimOverrides()
void SetActionAnimOverrides () private
SetActions()
void SetActions () inline private
References ActionDropItem(), and AddAction().
SetCanBeMovedOverride()
void SetCanBeMovedOverride (bool setting) inline private
References m_CanBeMovedOverride.
SetCEBasedQuantity()
void SetCEBasedQuantity () inline private
References COMP_TYPE_ENERGY_MANAGER, ComponentEnergyManager::GetEnergyAtSpawn(), ComponentEnergyManager::GetEnergyMaxPristine(), HasQuantity(), Math::RandomFloatInclusive(), ComponentEnergyManager::SetEnergy0To1(), and SetQuantityNormalized().
SetCleanness()
override void SetCleanness (int value, bool allow_client = false) inline private
References Math::Clamp(), m_Cleanness, m_CleannessMax, m_CleannessMin, and VARIABLE_CLEANNESS.
SetColor()
override void SetColor (int r, int g, int b, int a) inline private
References m_ColorComponentA, m_ColorComponentB, m_ColorComponentG, m_ColorComponentR, and VARIABLE_COLOR.
SetDebugActionsMask()
static void SetDebugActionsMask (int mask) inline static private
SetIsBeingPlaced()
void SetIsBeingPlaced (bool is_being_placed) inline private
References m_IsBeingPlaced, and ItemBase::OnEndPlacement().
SetIsDeploySound()
void SetIsDeploySound (bool is_deploy_sound) inline private
References m_IsDeploySound.
SetIsHologram()
void SetIsHologram (bool is_hologram) inline private
References m_IsHologram.
SetIsPlaceSound()
void SetIsPlaceSound (bool is_place_sound) inline private
References m_IsPlaceSound.
SetLiquidType()
override void SetLiquidType (int value, bool allow_client = false) inline private
References m_VarLiquidType, OnLiquidTypeChanged(), and VARIABLE_LIQUIDTYPE.
SetQuantity()
override bool SetQuantity (float value, bool destroy_config = true, bool destroy_forced = false, bool allow_client = false, bool clamp_to_stack_max = true) inline private
Set item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted.
References Math::Clamp(), GetQuantityMax(), GetQuantityMin(), GetStoreLoadedQuantity(), HasQuantity(), LOWEST, m_VarQuantity, OnQuantityChanged(), RemoveAllAgents(), and VARIABLE_QUANTITY.
SetQuantityMax()
void SetQuantityMax () inline private
References GetQuantityMax(), and SetQuantity().
SetQuantityNormalized()
void SetQuantityNormalized (float value, bool destroy_config = true, bool destroy_forced = false) inline private
Sets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, setting 0.5 will result in value 2500)
References Math::Clamp(), GetQuantityMax(), GetQuantityMin(), Math::Lerp(), Math::Round(), and SetQuantity().
SetQuantityToMinimum()
override void SetQuantityToMinimum () inline private
References GetQuantityMin(), and SetQuantity().
SetResultOfSplit()
void SetResultOfSplit (bool value) inline private
SetStoreLoad()
override void SetStoreLoad (bool value) inline private
References m_IsStoreLoad.
SetStoreLoadedQuantity()
override void SetStoreLoadedQuantity (float value) inline private
References m_StoreLoadedQuantity.
SetTakeable()
override void SetTakeable (bool pState) inline private
References m_IsTakeable.
SetWet()
override void SetWet (float value, bool allow_client = false) inline private
References Math::Clamp(), GetWetMax(), GetWetMin(), m_VarWet, OnWetChanged(), and VARIABLE_WET.
SetWetMax()
override void SetWetMax () inline private
References m_VarWetMax, and SetWet().
SetZoneDamageCEInit()
void SetZoneDamageCEInit () inline private
Sets zone damages to match randomized global health set by CE (CE spawn only)
SoundSynchRemote()
void SoundSynchRemote () inline private
References m_IsSoundSynchRemote.
SoundSynchRemoteReset()
void SoundSynchRemoteReset () inline private
References m_IsSoundSynchRemote.
SplitIntoStackMax()
void SplitIntoStackMax (EntityAI destination_entity, int slot_id, PlayerBase player) inline private
References AddQuantity(), ECE_IN_INVENTORY, ECE_PLACE_ON_SURFACE, GetGame(), GetQuantity(), GetTargetQuantityMax(), GetType(), InventorySlots::IsSlotIdValid(), RF_DEFAULT, and SetQuantity().
SplitIntoStackMaxCargo()
void SplitIntoStackMaxCargo (EntityAI destination_entity, int idx, int row, int col) inline private
References AddQuantity(), GetQuantity(), and GetTargetQuantityMax().
SplitIntoStackMaxCargoClient()
void SplitIntoStackMaxCargoClient (EntityAI destination_entity, int idx, int row, int col) inline private
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_ITEM_MANIPULATION, ScriptInputUserData::Send(), SplitIntoStackMaxCargo(), and Serializer::Write().
SplitIntoStackMaxClient()
override void SplitIntoStackMaxClient (EntityAI destination_entity, int slot_id) inline private
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), GetPlayer(), INPUT_UDT_ITEM_MANIPULATION, ScriptInputUserData::Send(), SplitIntoStackMax(), and Serializer::Write().
SplitIntoStackMaxEx()
override void SplitIntoStackMaxEx (EntityAI destination_entity, int slot_id) inline private
References AddQuantity(), ECE_IN_INVENTORY, ECE_PLACE_ON_SURFACE, GetGame(), GetQuantity(), GetTargetQuantityMax(), GetType(), InventorySlots::IsSlotIdValid(), RF_DEFAULT, and SetQuantity().
SplitIntoStackMaxHands()
void SplitIntoStackMaxHands (PlayerBase player) inline private
References AddQuantity(), GetQuantity(), GetTargetQuantityMax(), and GetType().
SplitIntoStackMaxHandsClient()
void SplitIntoStackMaxHandsClient (PlayerBase player) inline private
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_ITEM_MANIPULATION, ScriptInputUserData::Send(), SplitIntoStackMaxHands(), and Serializer::Write().
SplitIntoStackMaxToInventoryLocation()
void SplitIntoStackMaxToInventoryLocation (notnull InventoryLocation dst) inline private
References SplitIntoStackMaxToInventoryLocationEx().
SplitIntoStackMaxToInventoryLocationClient()
void SplitIntoStackMaxToInventoryLocationClient (notnull InventoryLocation dst) inline private
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_ITEM_MANIPULATION, ScriptInputUserData::Send(), SplitIntoStackMaxToInventoryLocation(), and Serializer::Write().
SplitIntoStackMaxToInventoryLocationEx()
ItemBase SplitIntoStackMaxToInventoryLocationEx (notnull InventoryLocation dst) inline private
References AddQuantity(), ECE_IN_INVENTORY, GetQuantity(), ItemBase::GetSlot(), GetTargetQuantityMax(), GameInventory::LocationCreateEntity(), and RF_DEFAULT.
SplitItem()
void SplitItem (PlayerBase player) inline private
References AddQuantity(), ItemBase::CanBeSplit(), Math::Floor(), GetQuantity(), InventoryLocation::GetType(), GetType(), and InventoryLocation::IsValid().
SplitItemToInventoryLocation()
void SplitItemToInventoryLocation (notnull InventoryLocation dst) inline private
References AddQuantity(), ItemBase::CanBeSplit(), ECE_IN_INVENTORY, Math::Floor(), GetQuantity(), GetType(), GameInventory::LocationCreateEntity(), and RF_DEFAULT.
StartOverheating()
void StartOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") inline private
References m_IsOverheatingEffectActive.
StopDeployLoopSoundEx()
void StopDeployLoopSoundEx () inline private
References GetGame(), and m_DeployLoopSoundEx.
StopItemDynamicPhysics()
void StopItemDynamicPhysics () inline private
References m_ItemBeingDroppedPhys.
StopOverheating()
void StopOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") inline private
References m_IsOverheatingEffectActive.
StopOverheatingParticles()
static void StopOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline static private
ToggleDebugActionsMask()
static void ToggleDebugActionsMask (int mask) inline static private
References AddDebugActionsMask(), HasDebugActionsMask(), and RemoveDebugActionsMask().
TransferAgents()
void TransferAgents (int agents) inline private
transfer agents from another item
References m_AttachedAgents.
TransferModifiers()
void TransferModifiers (PlayerBase reciever) private
appears to be deprecated, legacy code
UnlockFromParent()
void UnlockFromParent () inline private
Unlocks this item from its attachment slot of its parent.
References InventoryLocation::GetSlot().
UpdateAllOverheatingParticles()
void UpdateAllOverheatingParticles () inline private
References GetOverheatingCoef(), OverheatingParticle::GetOverheatingLimitMax(), OverheatingParticle::GetOverheatingLimitMin(), OverheatingParticle::GetParticle(), m_OverheatingParticles, OverheatingParticle::RegisterParticle(), and Particle::Stop().
UpdateOverheating()
void UpdateOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") inline private
References KillAllOverheatingParticles(), and UpdateAllOverheatingParticles().
UpdateOverheatingParticles()
static void UpdateOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline static private
UpdateQuickbarShortcutVisibility()
void UpdateQuickbarShortcutVisibility (PlayerBase player) inline private
To be called on moving item within character's inventory; 'player' should never be null.
UsesGlobalDeploy()
protected bool UsesGlobalDeploy () inline private
WriteVarsToCTX()
override void WriteVarsToCTX (ParamsWriteContext ctx) inline private
References GetCleanness(), GetColor(), GetLiquidType(), GetQuantity(), GetWet(), VARIABLE_CLEANNESS, VARIABLE_COLOR, VARIABLE_LIQUIDTYPE, VARIABLE_QUANTITY, VARIABLE_WET, and Serializer::Write().
Field Documentation
can_this_be_combined
bool can_this_be_combined private
m_ActionsInitialize
bool m_ActionsInitialize private
m_AdminLog
PluginAdminLog m_AdminLog private
m_AttachedAgents
private int m_AttachedAgents private
m_CanBeDigged
protected bool m_CanBeDigged private
m_CanBeMovedOverride
bool m_CanBeMovedOverride private
m_CanPlayImpactSound
bool m_CanPlayImpactSound = true private
m_CanShowQuantity
bool m_CanShowQuantity private
m_CanThisBeSplit
bool m_CanThisBeSplit private
m_CheckOverheating
ref Timer m_CheckOverheating private
m_Cleanness
int m_Cleanness private
m_CleannessInit
int m_CleannessInit private
m_CleannessMax
int m_CleannessMax private
m_CleannessMin
int m_CleannessMin private
m_ColorComponentA
int m_ColorComponentA private
m_ColorComponentB
int m_ColorComponentB private
m_ColorComponentG
int m_ColorComponentG private
m_ColorComponentR
int m_ColorComponentR private
m_CompatibleLocks
ref array<int> m_CompatibleLocks private
m_ContinuousActions
ref TIntArray m_ContinuousActions private
m_Count
int m_Count private
m_DebugActionsMask
int m_DebugActionsMask static private
m_DeployLoopSoundEx
protected bool m_IsResultOfSplit protected EffectSound m_DeployLoopSoundEx private
distinguish if item has been created as new or it came from splitting (server only flag)
m_FixDamageSystemInit
bool m_FixDamageSystemInit = false private
m_HasQuantityBar
bool m_HasQuantityBar private
m_HeadHidingSelections
protected ref TStringArray m_HeadHidingSelections private
m_HeatIsolation
float m_HeatIsolation private
m_HideSelectionsBySlot
protected bool m_HideSelectionsBySlot private
m_ImpactSoundSurfaceHash
int m_ImpactSoundSurfaceHash private
m_ImpactSpeed
float m_ImpactSpeed private
m_InputActionMap
TInputActionMap m_InputActionMap private
m_InteractActions
ref TIntArray m_InteractActions private
m_IsBeingPlaced
bool m_IsBeingPlaced private
m_IsDeploySound
bool m_IsDeploySound private
m_IsHologram
bool m_IsHologram private
m_IsOverheatingEffectActive
bool m_IsOverheatingEffectActive private
m_IsPlaceSound
bool m_IsPlaceSound private
m_IsSoundSynchRemote
bool m_IsSoundSynchRemote private
m_IsStoreLoad
bool m_IsStoreLoad = false private
m_IsTakeable
bool m_IsTakeable private
m_ItemActionOverrides
ref map<typename, ref TActionAnimOverrideMap> m_ItemActionOverrides = new map<typename, ref TActionAnimOverrideMap> static private
m_ItemAttachOffset
float m_ItemAttachOffset private
m_ItemBehaviour
int m_ItemBehaviour private
m_ItemBeingDroppedPhys
bool m_ItemBeingDroppedPhys private
m_ItemModelLength
float m_ItemModelLength private
m_ItemTypeActionsMap
ref map<typename, ref TInputActionMap> m_ItemTypeActionsMap = new map<typename, ref TInputActionMap> static private
m_LastRegisteredWeaponID
int m_LastRegisteredWeaponID = 0 static private
m_LightSourceItem
ItemBase m_LightSourceItem private
m_LiquidContainerMask
int m_LiquidContainerMask private
m_LockingSound
protected ref EffectSound m_LockingSound private
m_LockSoundSet
protected string m_LockSoundSet private
m_LockType
protected int m_LockType private
m_MaxOverheatingValue
int m_MaxOverheatingValue = 0 private
m_OnBulletCasingEjectEffect
ref map<int, ref array<ref WeaponParticlesOnBulletCasingEject> > m_OnBulletCasingEjectEffect static private
m_OnFireEffect
ref map<int, ref array<ref WeaponParticlesOnFire> > m_OnFireEffect static private
m_OnOverheatingEffect
ref map<int, ref array<ref WeaponParticlesOnOverheating> > m_OnOverheatingEffect private
m_OverheatingDecayInterval
float m_OverheatingDecayInterval = 1 private
m_OverheatingParticles
ref array<ref OverheatingParticle> m_OverheatingParticles private
m_OverheatingShots
float m_OverheatingShots private
m_PhysDropTimer
ref Timer m_PhysDropTimer private
m_QuickBarBonus
int m_QuickBarBonus private
m_RecipesInitialized
bool m_RecipesInitialized private
m_ShotsToStartOverheating
int m_ShotsToStartOverheating = 0 private
m_SingleUseActions
ref TIntArray m_SingleUseActions private
m_SoundAttType
string m_SoundAttType private
m_SoundDeploy
protected EffectSound m_SoundDeploy private
m_SoundDeployFinish
protected EffectSound m_SoundDeployFinish private
m_SoundPlace
protected EffectSound m_SoundPlace private
m_StoreLoadedQuantity
float m_StoreLoadedQuantity = float.LOWEST private
m_TemperaturePerQuantityWeight
private float m_TemperaturePerQuantityWeight private
m_ThrowItemOnDrop
bool m_ThrowItemOnDrop private
m_VarLiquidType
int m_VarLiquidType private
m_VarQuantity
float m_VarQuantity private
m_VarQuantityInit
int m_VarQuantityInit private
m_VarQuantityMax
int m_VarQuantityMax private
m_VarQuantityMin
int m_VarQuantityMin private
m_VarQuantityPrev
float m_VarQuantityPrev private
m_VarStackMax
float m_VarStackMax private
m_VarWet
float m_VarWet private
m_VarWetInit
float m_VarWetInit private
m_VarWetMax
float m_VarWetMax private
m_VarWetMin
float m_VarWetMin private
m_VarWetPrev
float m_VarWetPrev private
m_WantPlayImpactSound
bool m_WantPlayImpactSound private
m_WeaponTypeToID
ref map<string, int> m_WeaponTypeToID static private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase.c