DayZ Scripts: DayZIntroSceneXbox Class Reference
DayZIntroSceneXbox Class Reference
Private Member Functions
void DayZIntroSceneXbox ()
void ~DayZIntroSceneXbox ()
protected void SetInitPostprocesses ()
IntroSceneCharacter GetIntroCharacter ()
void SetupCharacter ()
void SetupParticles ()
void SetupDate ()
void CheckXboxClientUpdateLoopStart ()
void CheckXboxClientUpdateLoopStop ()
bool CheckXboxClientUpdate ()
protected Camera CameraCreate (vector cam_pos, float cam_rot_h, float cam_rot_v, float cam_fov, float cam_focus_dist, float cam_focus_strg)
Camera GetCamera ()
void ResetIntroCamera ()
void SetCharacterFemale (bool fem)
bool IsCharacterFemale ()
void CreateRandomCharacter ()
void UpdateSelectedUserName ()
void UpdateCharacterPos ()
void SaveCharName (string name)
vector SnapToGround (vector pos)
Private Attributes
protected bool m_IsCharFemale
protected int m_LastPlayedCharacterID
protected ref TStringArray m_genderList
protected ref TStringArray m_CharPersonalityMaleList
protected ref TStringArray m_CharPersonalityFemaleList
protected ref TStringArray m_CharShirtList
protected ref TStringArray m_CharPantsList
protected ref TStringArray m_CharShoesList
protected ref TStringArray m_AllCharacters
protected ref IntroSceneCharacter m_Character
protected Camera m_SceneCamera
protected Weather m_Weather
protected Object m_Clutter
protected vector m_CharacterPos
protected vector m_CharacterDir
protected ref TIntArray m_Date = new TIntArray
protected MenuData m_MenuData
protected ref MenuCarEngineSmoke m_FXParticleCarSmoke
protected ref MenuEvaporation m_FXParticleStreamLeft
protected ref MenuEvaporation m_FXParticleStreamRight
ref Timer m_TimerUpdate = new Timer(CALL_CATEGORY_GAMEPLAY)
ref Timer m_TimerParticle = new Timer(CALL_CATEGORY_GAMEPLAY)
ref Timer m_TimerDate = new Timer(CALL_CATEGORY_GAMEPLAY)
ref Timer m_TimerClientUpdate = new Timer(CALL_CATEGORY_GAMEPLAY)
Constructor & Destructor Documentation
DayZIntroSceneXbox()
void DayZIntroSceneXbox () inline private
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, CameraCreate(), CheckXboxClientUpdateLoopStart(), CGame::CreateObject(), g_Game, CGame::GetCallQueue(), MenuData::GetCharacterName(), MenuData::GetCharactersCount(), Weather::GetFog(), GetGame(), MenuData::GetLastPlayedCharacter(), Weather::GetOvercast(), Weather::GetRain(), PPEffects::Init(), Managed::IntroSceneCharacter(), m_Character, m_CharacterDir, m_CharacterPos, m_Clutter, m_LastPlayedCharacterID, m_MenuData, m_SceneCamera, m_TimerParticle, m_TimerUpdate, m_Weather, WeatherPhenomenon::Set(), SetInitPostprocesses(), WeatherPhenomenon::SetLimits(), SnapToGround(), and CGame::SurfaceY().
~DayZIntroSceneXbox()
void ~DayZIntroSceneXbox () inline private
References CheckXboxClientUpdateLoopStop(), MenuData::ClearCharacters(), SEffectManager::DestroyEffect(), GetGame(), PPEManagerStatic::GetPPEManager(), m_FXParticleCarSmoke, m_FXParticleStreamLeft, m_FXParticleStreamRight, m_MenuData, m_SceneCamera, m_TimerDate, m_TimerParticle, m_TimerUpdate, CGame::ObjectDelete(), and Timer::Stop().
Member Function Documentation
CameraCreate()
protected Camera CameraCreate (vector cam_pos, float cam_rot_h, float cam_rot_v, float cam_fov, float cam_focus_dist, float cam_focus_strg) inline private
References g_Game, SnapToGround(), and Vector().
Referenced by DayZIntroSceneXbox().
CheckXboxClientUpdate()
bool CheckXboxClientUpdate () inline private
References OnlineServices::CheckUpdate().
Referenced by CheckXboxClientUpdateLoopStart().
CheckXboxClientUpdateLoopStart()
void CheckXboxClientUpdateLoopStart () inline private
References CheckXboxClientUpdate(), and m_TimerClientUpdate.
Referenced by DayZIntroSceneXbox().
CheckXboxClientUpdateLoopStop()
void CheckXboxClientUpdateLoopStop () inline private
References m_TimerClientUpdate, and Timer::Stop().
Referenced by ~DayZIntroSceneXbox().
CreateRandomCharacter()
void CreateRandomCharacter () inline private
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), m_CharPersonalityFemaleList, m_CharPersonalityMaleList, m_IsCharFemale, Math::RandomInt(), and UpdateCharacterPos().
GetCamera()
Camera GetCamera () inline private
References m_SceneCamera.
GetIntroCharacter()
IntroSceneCharacter GetIntroCharacter () inline private
References m_Character.
Referenced by UIScriptedMenu::Apply(), UIScriptedMenu::Back(), UIScriptedMenu::BottomChanged(), UIScriptedMenu::CheckNewOptions(), UIScriptedMenu::GenderChanged(), UIScriptedMenu::GetPlayerObj(), UIScriptedMenu::Init(), UIScriptedMenu::RandomizeCharacter(), UIScriptedMenu::Refresh(), UIScriptedMenu::Save(), UIScriptedMenu::SetCharacter(), UIScriptedMenu::ShoesChanged(), UIScriptedMenu::SkinChanged(), UIScriptedMenu::TopChanged(), UIScriptedMenu::Update(), and UIScriptedMenu::UpdateControlsElements().
IsCharacterFemale()
bool IsCharacterFemale () inline private
References m_IsCharFemale.
ResetIntroCamera()
void ResetIntroCamera () inline private
Referenced by UIScriptedMenu::CharacterCreationMenu().
SaveCharName()
void SaveCharName (string name) inline private
References MenuData::GetCharactersCount(), GetDayZGame(), GetGame(), CGame::GetMenuDefaultCharacterData(), m_Character, m_LastPlayedCharacterID, m_MenuData, name, MenuData::SaveCharactersLocal(), MenuData::SetCharacterName(), and MenuDefaultCharacterData::SetCharacterName().
SetCharacterFemale()
void SetCharacterFemale (bool fem) inline private
References m_IsCharFemale.
SetInitPostprocesses()
protected void SetInitPostprocesses () inline private
References Class::CastTo().
Referenced by DayZIntroSceneXbox().
SetupCharacter()
void SetupCharacter () inline private
References m_Character.
SetupDate()
void SetupDate () inline private
SetupParticles()
void SetupParticles () inline private
References m_FXParticleCarSmoke, m_FXParticleStreamLeft, m_FXParticleStreamRight, m_SceneCamera, and SEffectManager::PlayInWorld().
SnapToGround()
vector SnapToGround (vector pos) inline private
References GetGame(), CGame::SurfaceY(), and Vector().
Referenced by CameraCreate(), and DayZIntroSceneXbox().
UpdateCharacterPos()
void UpdateCharacterPos () inline private
References m_Character, m_CharacterDir, m_CharacterPos, and vector::Normalized().
Referenced by CreateRandomCharacter().
UpdateSelectedUserName()
void UpdateSelectedUserName () inline private
References GameConstants::DEFAULT_CHARACTER_NAME, g_Game, GetGame(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), and name.
Field Documentation
m_AllCharacters
protected ref TStringArray m_AllCharacters private
m_Character
protected ref IntroSceneCharacter m_Character private
Referenced by DayZIntroSceneXbox(), GetIntroCharacter(), SaveCharName(), SetupCharacter(), and UpdateCharacterPos().
m_CharacterDir
protected vector m_CharacterDir private
Referenced by DayZIntroSceneXbox(), and UpdateCharacterPos().
m_CharacterPos
protected vector m_CharacterPos private
Referenced by DayZIntroSceneXbox(), and UpdateCharacterPos().
m_CharPantsList
protected ref TStringArray m_CharPantsList private
m_CharPersonalityFemaleList
protected ref TStringArray m_CharPersonalityFemaleList private
Referenced by CreateRandomCharacter().
m_CharPersonalityMaleList
protected ref TStringArray m_CharPersonalityMaleList private
Referenced by CreateRandomCharacter().
m_CharShirtList
protected ref TStringArray m_CharShirtList private
m_CharShoesList
protected ref TStringArray m_CharShoesList private
m_Clutter
protected Object m_Clutter private
Referenced by DayZIntroSceneXbox().
m_Date
protected ref TIntArray m_Date = new TIntArray private
m_FXParticleCarSmoke
protected ref MenuCarEngineSmoke m_FXParticleCarSmoke private
Referenced by SetupParticles(), and ~DayZIntroSceneXbox().
m_FXParticleStreamLeft
protected ref MenuEvaporation m_FXParticleStreamLeft private
Referenced by SetupParticles(), and ~DayZIntroSceneXbox().
m_FXParticleStreamRight
protected ref MenuEvaporation m_FXParticleStreamRight private
Referenced by SetupParticles(), and ~DayZIntroSceneXbox().
m_genderList
protected ref TStringArray m_genderList private
m_IsCharFemale
protected bool m_IsCharFemale private
Referenced by CreateRandomCharacter(), IsCharacterFemale(), and SetCharacterFemale().
m_LastPlayedCharacterID
protected int m_LastPlayedCharacterID private
Referenced by DayZIntroSceneXbox(), and SaveCharName().
m_MenuData
protected MenuData m_MenuData private
Referenced by DayZIntroSceneXbox(), SaveCharName(), and ~DayZIntroSceneXbox().
m_SceneCamera
protected Camera m_SceneCamera private
Referenced by DayZIntroSceneXbox(), GetCamera(), SetupParticles(), and ~DayZIntroSceneXbox().
m_TimerClientUpdate
ref Timer m_TimerClientUpdate = new Timer(CALL_CATEGORY_GAMEPLAY) private
Referenced by CheckXboxClientUpdateLoopStart(), and CheckXboxClientUpdateLoopStop().
m_TimerDate
ref Timer m_TimerDate = new Timer(CALL_CATEGORY_GAMEPLAY) private
Referenced by ~DayZIntroSceneXbox().
m_TimerParticle
ref Timer m_TimerParticle = new Timer(CALL_CATEGORY_GAMEPLAY) private
Referenced by DayZIntroSceneXbox(), and ~DayZIntroSceneXbox().
m_TimerUpdate
ref Timer m_TimerUpdate = new Timer(CALL_CATEGORY_GAMEPLAY) private
Referenced by DayZIntroSceneXbox(), and ~DayZIntroSceneXbox().
m_Weather
protected Weather m_Weather private
Referenced by DayZIntroSceneXbox().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/DayZIntroSceneXbox.c