DayZ Scripts: EffectTrigger Class Reference
EffectTrigger Class Reference
Private Member Functions
override void OnEnterServerEvent (TriggerInsider insider)
override void OnLeaveServerEvent (TriggerInsider insider)
override void OnEnterClientEvent (TriggerInsider insider)
override void OnLeaveClientEvent (TriggerInsider insider)
override void OnStayStartServerEvent (int nrOfInsiders)
override void OnStayFinishServerEvent ()
override void OnStayServerEvent (TriggerInsider insider, float deltaTime)
override string GetAmbientSoundsetName ()
void EffectTrigger ()
void SetLocalEffects (int aroundPartId, int tinyPartId, int ppeRequesterIdx)
string GetAmbientSoundsetName ()
void SetupClientEffects (bool enable, notnull PlayerBase player)
override void EOnFrame (IEntity other, float timeSlice)
override bool CanAddObjectAsInsider (Object object)
override void OnEnterServerEvent (TriggerInsider insider)
override void OnEnterClientEvent (TriggerInsider insider)
override void OnLeaveServerEvent (TriggerInsider insider)
override void OnLeaveClientEvent (TriggerInsider insider)
override bool ShouldRemoveInsider (TriggerInsider insider)
Static Private Member Functions
static void TriggerEffect (EntityAI insider, typename triggerType)
Private Attributes
const float DAMAGE_TICK_RATE = 10
int m_AroundPartId
int m_TinyPartId
int m_PPERequester
float m_DeltaTime
float m_TimeAccuStay
bool m_DealDamageFlag
TriggerEffectManager m_Manager
Detailed Description
Definition at line 2 of file ContaminatedTrigger.c.
Constructor & Destructor Documentation
EffectTrigger()
void EffectTrigger () inline private
Definition at line 13 of file EffectTrigger.c.
References TriggerEffectManager::GetInstance(), m_Manager, and TriggerEffectManager::RegisterTriggerType().
Member Function Documentation
CanAddObjectAsInsider()
override bool CanAddObjectAsInsider (Object object) inline private
Definition at line 67 of file EffectTrigger.c.
EOnFrame()
override void EOnFrame (IEntity other, float timeSlice) inline private
Definition at line 62 of file EffectTrigger.c.
References m_DeltaTime.
GetAmbientSoundsetName() [1/2]
override string GetAmbientSoundsetName () inline private
Definition at line 96 of file ContaminatedTrigger.c.
Referenced by SetupClientEffects().
GetAmbientSoundsetName() [2/2]
string GetAmbientSoundsetName () inline private
Definition at line 37 of file EffectTrigger.c.
OnEnterClientEvent() [1/2]
override void OnEnterClientEvent (TriggerInsider insider) inline private
Definition at line 55 of file ContaminatedTrigger.c.
OnEnterClientEvent() [2/2]
override void OnEnterClientEvent (TriggerInsider insider) inline private
Definition at line 102 of file EffectTrigger.c.
References TriggerInsider::GetObject(), m_Manager, TriggerEffectManager::OnPlayerEnter(), and SetupClientEffects().
OnEnterServerEvent() [1/2]
override void OnEnterServerEvent (TriggerInsider insider) inline private
Definition at line 10 of file ContaminatedTrigger.c.
References TriggerInsider::GetObject().
OnEnterServerEvent() [2/2]
override void OnEnterServerEvent (TriggerInsider insider) inline private
Definition at line 83 of file EffectTrigger.c.
References TriggerInsider::GetObject(), m_Manager, and TriggerEffectManager::OnPlayerEnter().
OnLeaveClientEvent() [1/2]
override void OnLeaveClientEvent (TriggerInsider insider) inline private
Definition at line 60 of file ContaminatedTrigger.c.
OnLeaveClientEvent() [2/2]
override void OnLeaveClientEvent (TriggerInsider insider) inline private
Definition at line 136 of file EffectTrigger.c.
References TriggerInsider::GetObject(), m_Manager, TriggerEffectManager::OnPlayerExit(), and SetupClientEffects().
OnLeaveServerEvent() [1/2]
override void OnLeaveServerEvent (TriggerInsider insider) inline private
Definition at line 33 of file ContaminatedTrigger.c.
References TriggerInsider::GetObject(), and m_Manager.
OnLeaveServerEvent() [2/2]
override void OnLeaveServerEvent (TriggerInsider insider) inline private
Definition at line 121 of file EffectTrigger.c.
References TriggerInsider::GetObject(), m_Manager, and TriggerEffectManager::OnPlayerExit().
OnStayFinishServerEvent()
override void OnStayFinishServerEvent () inline private
Definition at line 77 of file ContaminatedTrigger.c.
OnStayServerEvent()
override void OnStayServerEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 86 of file ContaminatedTrigger.c.
References GameConstants::AI_CONTAMINATION_DMG_PER_SEC, and TriggerInsider::GetObject().
OnStayStartServerEvent()
override void OnStayStartServerEvent (int nrOfInsiders) inline private
Definition at line 66 of file ContaminatedTrigger.c.
References m_DeltaTime.
SetLocalEffects()
void SetLocalEffects (int aroundPartId, int tinyPartId, int ppeRequesterIdx) inline private
Definition at line 27 of file EffectTrigger.c.
References m_AroundPartId, m_PPERequester, and m_TinyPartId.
Referenced by EffectArea::CreateTrigger().
SetupClientEffects()
void SetupClientEffects (bool enable, notnull PlayerBase player) inline private
Definition at line 42 of file EffectTrigger.c.
References GetAmbientSoundsetName(), TriggerEffectManager::IsPlayerInTriggerType(), m_AroundPartId, m_Manager, m_PPERequester, and m_TinyPartId.
Referenced by OnEnterClientEvent(), and OnLeaveClientEvent().
ShouldRemoveInsider()
override bool ShouldRemoveInsider (TriggerInsider insider) inline private
Definition at line 157 of file EffectTrigger.c.
References TriggerInsider::GetObject().
TriggerEffect()
static void TriggerEffect (EntityAI insider, typename triggerType) inline static private
Definition at line 164 of file EffectTrigger.c.
Field Documentation
DAMAGE_TICK_RATE
const float DAMAGE_TICK_RATE = 10 private
Definition at line 4 of file ContaminatedTrigger.c.
m_AroundPartId
int m_AroundPartId private
Definition at line 5 of file EffectTrigger.c.
Referenced by SetLocalEffects(), and SetupClientEffects().
m_DealDamageFlag
bool m_DealDamageFlag private
Definition at line 10 of file EffectTrigger.c.
m_DeltaTime
float m_DeltaTime private
Definition at line 8 of file EffectTrigger.c.
Referenced by EOnFrame(), and OnStayStartServerEvent().
m_Manager
TriggerEffectManager m_Manager private
Definition at line 11 of file EffectTrigger.c.
Referenced by EffectTrigger(), OnEnterClientEvent(), OnEnterServerEvent(), OnLeaveClientEvent(), OnLeaveServerEvent(), and SetupClientEffects().
m_PPERequester
int m_PPERequester private
Definition at line 7 of file EffectTrigger.c.
Referenced by SetLocalEffects(), and SetupClientEffects().
m_TimeAccuStay
float m_TimeAccuStay private
Definition at line 9 of file EffectTrigger.c.
m_TinyPartId
int m_TinyPartId private
Definition at line 6 of file EffectTrigger.c.
Referenced by SetLocalEffects(), and SetupClientEffects().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ScriptedEntities/Triggers/ContaminatedTrigger.c
P:/scripts/4_World/Entities/ScriptedEntities/Triggers/EffectTrigger.c