DayZ Scripts: ScrollBarContainer Class Reference
ScrollBarContainer Class Reference
Private Member Functions
void ~ScrollBarContainer ()
void ScrollFixedAmount (bool down, float amount)
void ScrollToPos (float pos)
void ScrollToBottom ()
void ScrollToTop ()
float GetContentYPos ()
float GetRootHeight ()
void UpdateScroller ()
void OnWidgetScriptInit (Widget w)
protected void StopScrolling ()
protected void UpdateScroll (int mouse_x, int mouse_y, bool is_dragging)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseWheel (Widget w, int x, int y, int wheel)
override bool OnResize (Widget w, int x, int y)
Private Attributes
reference bool Invert
protected Widget Content
protected Widget ScrollBar
protected Widget Scroller
protected Widget m_root
const int WHEEL_STEP = 20
protected float m_root_height
protected float m_content_height
protected float m_position
protected bool m_scrolling
protected float m_scrolling_start_pos
protected int m_scrolling_mouse_pos
Constructor & Destructor Documentation
~ScrollBarContainer()
void ~ScrollBarContainer () inline private
Member Function Documentation
GetContentYPos()
float GetContentYPos () inline private
References Content, x, and y.
GetRootHeight()
float GetRootHeight () inline private
References m_root_height.
OnMouseButtonDown()
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
References CGame::GetDragQueue(), GetGame(), GetMousePos(), m_position, m_scrolling, m_scrolling_mouse_pos, m_scrolling_start_pos, and Scroller.
OnMouseButtonUp()
override bool OnMouseButtonUp (Widget w, int x, int y, int button) inline private
References StopScrolling().
OnMouseWheel()
override bool OnMouseWheel (Widget w, int x, int y, int wheel) inline private
References m_content_height, m_position, m_root_height, m_scrolling, UpdateScroller(), and WHEEL_STEP.
OnResize()
override bool OnResize (Widget w, int x, int y) inline private
References Content, m_root, and UpdateScroller().
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w) inline private
References m_root, m_scrolling, and UpdateScroller().
ScrollFixedAmount()
void ScrollFixedAmount (bool down, float amount) inline private
References Content, m_content_height, m_position, m_root, m_root_height, and UpdateScroller().
ScrollToBottom()
void ScrollToBottom () inline private
References Content, m_content_height, m_position, m_root, m_root_height, and UpdateScroller().
ScrollToPos()
void ScrollToPos (float pos) inline private
References Content, m_content_height, m_position, m_root, m_root_height, and UpdateScroller().
ScrollToTop()
void ScrollToTop () inline private
References m_position, and UpdateScroller().
StopScrolling()
protected void StopScrolling () inline private
References CGame::GetDragQueue(), GetGame(), and m_scrolling.
Referenced by OnMouseButtonUp(), and UpdateScroll().
UpdateScroll()
protected void UpdateScroll (int mouse_x, int mouse_y, bool is_dragging) inline private
References Content, m_content_height, m_position, m_root, m_root_height, m_scrolling, m_scrolling_mouse_pos, m_scrolling_start_pos, StopScrolling(), and UpdateScroller().
UpdateScroller()
void UpdateScroller () inline private
References Content, Invert, m_content_height, m_position, m_root, m_root_height, ScrollBar, and Scroller.
Referenced by OnMouseWheel(), OnResize(), OnWidgetScriptInit(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), ScrollToTop(), and UpdateScroll().
Field Documentation
Content
protected Widget Content private
Referenced by GetContentYPos(), OnResize(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), UpdateScroll(), and UpdateScroller().
Invert
reference bool Invert private
Referenced by UpdateScroller().
m_content_height
protected float m_content_height private
Referenced by OnMouseWheel(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), UpdateScroll(), and UpdateScroller().
m_position
protected float m_position private
Referenced by OnMouseButtonDown(), OnMouseWheel(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), ScrollToTop(), UpdateScroll(), and UpdateScroller().
m_root
protected Widget m_root private
Referenced by OnResize(), OnWidgetScriptInit(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), UpdateScroll(), and UpdateScroller().
m_root_height
protected float m_root_height private
Referenced by GetRootHeight(), OnMouseWheel(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), UpdateScroll(), and UpdateScroller().
m_scrolling
protected bool m_scrolling private
Referenced by OnMouseButtonDown(), OnMouseWheel(), OnWidgetScriptInit(), StopScrolling(), and UpdateScroll().
m_scrolling_mouse_pos
protected int m_scrolling_mouse_pos private
Referenced by OnMouseButtonDown(), and UpdateScroll().
m_scrolling_start_pos
protected float m_scrolling_start_pos private
Referenced by OnMouseButtonDown(), and UpdateScroll().
ScrollBar
protected Widget ScrollBar private
Referenced by UpdateScroller().
Scroller
protected Widget Scroller private
Referenced by OnMouseButtonDown(), and UpdateScroller().
WHEEL_STEP
const int WHEEL_STEP = 20 private
Referenced by OnMouseWheel().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/GUI/Containers/ScrollBarContainer.c