DayZ Scripts: ComponentAnimalBleeding Class Reference
ComponentAnimalBleeding Class Reference
Private Member Functions
void ComponentAnimalBleeding ()
void InflictWoundDamage (TotalDamageResult damage_result, string zone_name, string ammo)
void CreateWound (TotalDamageResult damage_result, string zone_name, string ammo)
void Bleed (float wound_intensity)
float GetWoundIntensity (float bleed_treshold)
Private Attributes
protected ref Timer m_BleedTimer
protected const float BASE_BLEED_RATE = 250
protected const float PASS_OUT_AMOUT = 500
Constructor & Destructor Documentation
ComponentAnimalBleeding()
void ComponentAnimalBleeding () inline private
Member Function Documentation
Bleed()
void Bleed (float wound_intensity) inline private
References BASE_BLEED_RATE, m_BleedTimer, Component::m_ThisEntityAI, PASS_OUT_AMOUT, and Timer::Stop().
CreateWound()
void CreateWound (TotalDamageResult damage_result, string zone_name, string ammo) inline private
References GetWoundIntensity(), InflictWoundDamage(), and m_BleedTimer.
Referenced by DayZCreatureAI::EEHitBy().
GetWoundIntensity()
float GetWoundIntensity (float bleed_treshold) inline private
Referenced by CreateWound().
InflictWoundDamage()
void InflictWoundDamage (TotalDamageResult damage_result, string zone_name, string ammo) inline private
References TotalDamageResult::GetDamage(), and Component::m_ThisEntityAI.
Referenced by CreateWound().
Field Documentation
BASE_BLEED_RATE
protected const float BASE_BLEED_RATE = 250 private
Referenced by Bleed().
m_BleedTimer
protected ref Timer m_BleedTimer private
Referenced by Bleed(), and CreateWound().
PASS_OUT_AMOUT
protected const float PASS_OUT_AMOUT = 500 private
Referenced by Bleed().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/Component/ComponentAnimalBleeding.c