DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Weapons/FirearmActionLoadBullet.c File Reference
FirearmActionLoadBullet.c File Reference
Data Structures
class FirearmActionLoadBullet
Functions
FirearmActionLoadBullet FirearmActionBase FirearmActionLoadBulletQuick ()
void FirearmActionLoadBullet ()
override int GetActionCategory ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void Start (ActionData action_data)
override Object GetDisplayInteractObject (PlayerBase player, ActionTarget target)
override bool CanBePerformedFromInventory ()
override bool CanBePerformedFromQuickbar ()
override GetInputType ()
override void CreateConditionComponents ()
override bool HasProgress ()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
CanBePerformedFromInventory()
override bool CanBePerformedFromInventory ()
CanBePerformedFromQuickbar()
override bool CanBePerformedFromQuickbar ()
CreateConditionComponents()
override void CreateConditionComponents ()
References m_ConditionItem, and m_ConditionTarget.
FirearmActionLoadBullet()
void FirearmActionLoadBullet ()
FirearmActionLoadBulletQuick()
FirearmActionLoadBullet FirearmActionBase FirearmActionLoadBulletQuick ()
Referenced by ActionConstructor::RegisterActions(), Rifle_Base::SetActions(), BoltActionRifle_Base::SetActions(), DoubleBarrel_Base::SetActions(), Weapon_Base::SetActions(), Mp133Shotgun_Base::SetActions(), and Weapon::SetActions().
GetActionCategory()
override int GetActionCategory ()
GetDisplayInteractObject()
override Object GetDisplayInteractObject (PlayerBase player, ActionTarget target)
GetInputType()
override GetInputType ()
HasProgress()
override bool HasProgress ()
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL)
References ActionTarget, and vector::Zero.
Start()
override void Start (ActionData action_data)