DayZ Scripts: BarbedWireTrigger Class Reference
BarbedWireTrigger Class Reference
DEPRECATED UNUSED prototype for damage by BarbedWire, do not use as example.
Private Member Functions
override void OnEnter (Object obj)
void SetParentObject (ItemBase wire)
void SoundElectricShock ()
void SoundCollision ()
Private Attributes
ItemBase m_ParentBarbedWire
Static Private Attributes
static const int SOUNDS_COLLISION_COUNT = 4
static const int SOUNDS_SHOCK_COUNT = 4
static const string m_SoundsCollision [SOUNDS_COLLISION_COUNT] = {"barbedFenceCollision1", "barbedFenceCollision2", "barbedFenceCollision3", "barbedFenceCollision4"}
static const string m_SoundsShock [SOUNDS_SHOCK_COUNT] = {"electricFenceShock1", "electricFenceShock2", "electricFenceShock3", "electricFenceShock4"}
Detailed Description
DEPRECATED UNUSED prototype for damage by BarbedWire, do not use as example.
Member Function Documentation
OnEnter()
override void OnEnter (Object obj) inline private
References CGame::ConfigGetFloat(), g_Game, GetGame(), m_ParentBarbedWire, SoundCollision(), and SoundElectricShock().
SetParentObject()
void SetParentObject (ItemBase wire) inline private
References g_Game, and m_ParentBarbedWire.
SoundCollision()
void SoundCollision () inline private
References m_SoundsCollision, PlaySound(), Math::RandomInt(), and SOUNDS_COLLISION_COUNT.
Referenced by OnEnter().
SoundElectricShock()
void SoundElectricShock () inline private
References m_SoundsShock, PlaySound(), Math::RandomInt(), and SOUNDS_SHOCK_COUNT.
Referenced by OnEnter().
Field Documentation
m_ParentBarbedWire
ItemBase m_ParentBarbedWire private
Referenced by OnEnter(), and SetParentObject().
m_SoundsCollision
const string m_SoundsCollision[SOUNDS_COLLISION_COUNT] = {"barbedFenceCollision1", "barbedFenceCollision2", "barbedFenceCollision3", "barbedFenceCollision4"} static private
Referenced by SoundCollision().
m_SoundsShock
const string m_SoundsShock[SOUNDS_SHOCK_COUNT] = {"electricFenceShock1", "electricFenceShock2", "electricFenceShock3", "electricFenceShock4"} static private
Referenced by SoundElectricShock().
SOUNDS_COLLISION_COUNT
const int SOUNDS_COLLISION_COUNT = 4 static private
Referenced by SoundCollision().
SOUNDS_SHOCK_COUNT
const int SOUNDS_SHOCK_COUNT = 4 static private
Referenced by SoundElectricShock().
The documentation for this class was generated from the following file:
P:/scripts/4_world/entities/scriptedentities/triggers/barbedwiretrigger.c