DayZ Scripts: PlayerRestrictedAreaInstance Class Reference
PlayerRestrictedAreaInstance Class Reference
Private Member Functions
void Initialize ()
private bool ValidatePlayerRestrictedAreaPositions ()
private bool TranslateSafePositions ()
bool IsValid ()
vector GetCenterPos2D ()
vector GetClosestSafePos3D (vector targetPos)
vector GetRandomSafePos3D (vector targetPos)
Private Attributes
private bool m_IsValid = false
private int m_LastUsedSafePosIdx = -1
private ref array< vector > m_TranslatedSafePositions3D
private ref array< vector > m_RandomizedSafePositions3D
private vector m_CenterPos2D
string areaName = ""
ref array< ref array< ref array< float > > > PRABoxes = new array<ref array<ref array<float>>>
ref array< ref array< ref array< float > > > PRAPolygons = new array<ref array<ref array<float>>>
3D, not used directly!
ref array< ref array< float > > safePositions2D = new array<ref array<float>>
ref array< ref array< float > > safePositions3D = new array<ref array<float>>
ref array< ref PRAShapeBoxData > m_PRABoxDataTranslated = new array<ref PRAShapeBoxData>
Member Function Documentation
GetCenterPos2D()
vector GetCenterPos2D () inline private
References m_CenterPos2D.
GetClosestSafePos3D()
vector GetClosestSafePos3D (vector targetPos) inline private
References vector::DistanceSq(), and m_TranslatedSafePositions3D.
GetRandomSafePos3D()
vector GetRandomSafePos3D (vector targetPos) inline private
References m_LastUsedSafePosIdx, m_RandomizedSafePositions3D, and m_TranslatedSafePositions3D.
Referenced by ManBase::AfterStoreLoad().
Initialize()
void Initialize () inline private
References m_IsValid, TranslateSafePositions(), and ValidatePlayerRestrictedAreaPositions().
IsValid()
bool IsValid () inline private
References m_IsValid.
TranslateSafePositions()
private bool TranslateSafePositions () inline private
References areaName, GetGame(), Debug::Log(), m_TranslatedSafePositions3D, safePositions2D, safePositions3D, and Vector().
Referenced by Initialize().
ValidatePlayerRestrictedAreaPositions()
private bool ValidatePlayerRestrictedAreaPositions () inline private
References areaName, Debug::Log(), m_CenterPos2D, m_PRABoxDataTranslated, Math::Max(), Math::Min(), PRABoxes, PRAPolygons, and Vector().
Referenced by Initialize().
Field Documentation
areaName
string areaName = "" private
Referenced by ManBase::AfterStoreLoad(), TranslateSafePositions(), and ValidatePlayerRestrictedAreaPositions().
m_CenterPos2D
private vector m_CenterPos2D private
Referenced by GetCenterPos2D(), and ValidatePlayerRestrictedAreaPositions().
m_IsValid
private bool m_IsValid = false private
Referenced by Initialize(), and IsValid().
m_LastUsedSafePosIdx
private int m_LastUsedSafePosIdx = -1 private
Referenced by GetRandomSafePos3D().
m_PRABoxDataTranslated
ref array<ref PRAShapeBoxData> m_PRABoxDataTranslated = new array<ref PRAShapeBoxData> private
Referenced by ValidatePlayerRestrictedAreaPositions().
m_RandomizedSafePositions3D
private ref array<vector> m_RandomizedSafePositions3D private
Referenced by GetRandomSafePos3D().
m_TranslatedSafePositions3D
private ref array<vector> m_TranslatedSafePositions3D private
Referenced by GetClosestSafePos3D(), GetRandomSafePos3D(), and TranslateSafePositions().
PRABoxes
ref array<ref array<ref array<float> > > PRABoxes = new array<ref array<ref array<float>>> private
Referenced by ValidatePlayerRestrictedAreaPositions().
PRAPolygons
ref array<ref array<ref array<float> > > PRAPolygons = new array<ref array<ref array<float>>> private
3D, not used directly!
Referenced by ValidatePlayerRestrictedAreaPositions().
safePositions2D
ref array<ref array<float> > safePositions2D = new array<ref array<float>> private
Referenced by TranslateSafePositions().
safePositions3D
ref array<ref array<float> > safePositions3D = new array<ref array<float>> private
Referenced by TranslateSafePositions().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/CfgPlayerRestrictedAreaJsonData.c