DayZ Scripts: ToggleAnimations Class Reference
ToggleAnimations Class Reference
Private Member Functions
void ToggleAnimations (string toggle_off, string toggle_on, int mask, array< string > linked_anims_off=null, array< string > linked_anims_on=null)
string GetToggleOff ()
string GetToggleOn ()
int GetOpeningBit ()
Private Attributes
protected string m_ToggleOff
protected string m_ToggleOn
int m_OpeningBit
Constructor & Destructor Documentation
ToggleAnimations()
void ToggleAnimations (string toggle_off, string toggle_on, int mask, array< string > linked_anims_off = null, array< string > linked_anims_on = null) inline private
References m_OpeningBit, m_ToggleOff, and m_ToggleOn.
Member Function Documentation
GetOpeningBit()
int GetOpeningBit () inline private
References m_OpeningBit.
Referenced by TentBase::AnimateCamonetToggle(), TentBase::HandleCamoNetAttachment(), ItemBase::HandleOpeningsPhysics(), ItemBase::HandleOpeningsVisuals(), and ItemBase::ToggleAnimation().
GetToggleOff()
string GetToggleOff () inline private
References m_ToggleOff.
Referenced by TentBase::AnimateCamonetToggle(), ItemBase::CanToggleAnimations(), TentBase::HandleCamoNetAttachment(), ItemBase::HandleOpeningsPhysics(), ItemBase::HandleOpeningsVisuals(), and ItemBase::ToggleAnimation().
GetToggleOn()
string GetToggleOn () inline private
References m_ToggleOn.
Referenced by TentBase::AnimateCamonetToggle(), ItemBase::CanToggleAnimations(), TentBase::HandleCamoNetAttachment(), ItemBase::HandleOpeningsPhysics(), ItemBase::HandleOpeningsVisuals(), and ItemBase::ToggleAnimation().
Field Documentation
m_OpeningBit
int m_OpeningBit private
Referenced by GetOpeningBit(), and ToggleAnimations().
m_ToggleOff
protected string m_ToggleOff private
Referenced by GetToggleOff(), and ToggleAnimations().
m_ToggleOn
protected string m_ToggleOn private
Referenced by GetToggleOn(), and ToggleAnimations().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/ToggleSelections.c