DayZ Scripts: Debug UI API
Debug UI API
Debug utilities
Immediate mode debug UI APIPer frame usage example:
Data Structures
class DbgUI
Functions
private void DbgUI ()
private void ~DbgUI ()
static proto native void DoUnitTest ()
Creates all possible DbgUI widgets. Just for the testing purposes.
static proto native void Text (string label)
static proto native void ColoredText (int color, string label)
static proto void Check (string label, out bool checked)
static proto void Combo (string label, out int selection, TStringArray elems)
static proto void List (string label, out int selection, TStringArray elems)
static proto void SliderFloat (string label, out float value, float min, float max, int pxWidth=150)
static proto native void Spacer (int height)
static proto native void Panel (string label, int width, int height, int color=0xaa555555)
static proto native bool Button (string txt, int minWidth=0)
static proto void InputText (string txt, out string value, int pxWidth=150)
static proto void InputInt (string txt, out int value, int pxWidth=150)
static proto void InputFloat (string txt, out float value, int pxWidth=150)
static proto native void PlotLive (string label, int sizeX, int sizeY, float val, int timeStep=100, int historySize=30, int color=0xFFFFFFFF)
static proto native void SameLine ()
static proto native void SameSpot ()
static proto native void PushID_Int (int int_id)
static proto native void PushID_Str (string str_id)
static proto native void PopID ()
static proto void BeginCleanupScope ()
static proto native void EndCleanupScope ()
static proto native void Begin (string windowTitle, float x=0, float y=0)
static proto native void End ()
Detailed Description
Immediate mode debug UI API
Per frame usage example:
bool m_ShowDbgUI = false;
int m_DbgListSelection = 0;
float m_DbgSliderValue = 0.0;
autoptr array<string> m_DbgOptions = {"jedna", "dva", "tri"};
void OnUpdate(float timeslice)
{
   DbgUI.Begin("Test");
   DbgUI.Check("Show DbgUI", m_ShowDbgUI);
   if (m_ShowDbgUI)
   {
       DbgUI.Text("DbgUI Test");
       string name = "";
       DbgUI.InputText("name", name);
       if (DbgUI.Button("Print name"))
       {
           Print(name);
       }
       DbgUI.List("test list", m_DbgListSelection, m_DbgOptions);
       DbgUI.Text("Choice = " + m_DbgListSelection.ToString());
       DbgUI.Spacer(10);
       DbgUI.SliderFloat("slider", m_DbgSliderValue, 0, 100);
       DbgUI.Text("Slider value = " + ftoa(m_DbgSliderValue));
   }
   DbgUI.End();
}
For non-per frame usage example:
int m_DbgEventCount = 0;
void OnEvent(EventType eventTypeId, Param params)
{
   m_DbgEventCount++;
   DbgUI.BeginCleanupScope();
   DbgUI.Begin("events", 300, 0);
   DbgUI.Text("Events count = " + m_DbgEventCount.ToString());
   DbgUI.End();
   DbgUI.EndCleanupScope();
}
Function Documentation
Begin()
static proto native void Begin (string windowTitle, float x = 0, float y = 0) static private
Referenced by BleedingSourcesManagerBase::CleanDebug(), BleedingSourcesManagerBase::DisplayDebug(), WeaponDebug::DisplayGeneralInfo(), WeaponDebug::DisplayTargetInfo(), PluginBase::DrawDebugs(), Weapon::LiftWeaponCheck(), OnGUI(), PluginBase::OnGUITimer(), MissionBase::OnUpdate(), ShowCoefsDbg(), Managed::ShowDebugValues(), and MissionBase::ShowHairDebugValues().
BeginCleanupScope()
static proto void BeginCleanupScope () static private
Referenced by BleedingSourcesManagerBase::CleanDebug(), BleedingSourcesManagerBase::DisplayDebug(), Weapon::LiftWeaponCheck(), OnGUI(), OnGUI_CommandsEdit(), OnGUI_Variables(), OnGUI_VariablesEdit(), PluginBase::OnGUITimer(), ShowCoefsDbg(), Managed::ShowDebugValues(), and MissionBase::ShowHairDebugValues().
Button()
static proto native bool Button (string txt, int minWidth = 0) static private
Referenced by OnGUI(), OnGUI_AIControlEdit(), OnGUI_AnimEvents(), OnGUI_BulkSet(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
Check()
static proto void Check (string label, out bool checked) static private
Referenced by OnGUI(), OnGUI_CommandsEdit(), and OnGUI_VariablesEdit().
ColoredText()
static proto native void ColoredText (int color, string label) static private
Combo()
static proto void Combo (string label, out int selection, TStringArray elems) static private
DbgUI()
private void DbgUI () inline private
DoUnitTest()
static proto native void DoUnitTest () static private
Creates all possible DbgUI widgets. Just for the testing purposes.
End()
static proto native void End () static private
Referenced by BleedingSourcesManagerBase::CleanDebug(), BleedingSourcesManagerBase::DisplayDebug(), WeaponDebug::DisplayGeneralInfo(), WeaponDebug::DisplayTargetInfo(), PluginBase::DrawDebugs(), Weapon::LiftWeaponCheck(), OnGUI(), PluginBase::OnGUITimer(), MissionBase::OnUpdate(), ShowCoefsDbg(), Managed::ShowDebugValues(), and MissionBase::ShowHairDebugValues().
EndCleanupScope()
static proto native void EndCleanupScope () static private
Referenced by BleedingSourcesManagerBase::CleanDebug(), BleedingSourcesManagerBase::DisplayDebug(), Weapon::LiftWeaponCheck(), OnGUI(), OnGUI_CommandsEdit(), OnGUI_Variables(), OnGUI_VariablesEdit(), PluginBase::OnGUITimer(), ShowCoefsDbg(), Managed::ShowDebugValues(), and MissionBase::ShowHairDebugValues().
InputFloat()
static proto void InputFloat (string txt, out float value, int pxWidth = 150) static private
Referenced by PluginBase::OnGUITimer().
InputInt()
static proto void InputInt (string txt, out int value, int pxWidth = 150) static private
Referenced by OnGUI().
InputText()
static proto void InputText (string txt, out string value, int pxWidth = 150) static private
Referenced by OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
List()
static proto void List (string label, out int selection, TStringArray elems) static private
Panel()
static proto native void Panel (string label, int width, int height, int color = 0xaa555555) static private
Referenced by OnGUI(), OnGUI_AnimEvents(), and ShowCoefsDbg().
PlotLive()
static proto native void PlotLive (string label, int sizeX, int sizeY, float val, int timeStep = 100, int historySize = 30, int color = 0xFFFFFFFF) static private
PopID()
static proto native void PopID () static private
Referenced by OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
PushID_Int()
static proto native void PushID_Int (int int_id) static private
Referenced by OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
PushID_Str()
static proto native void PushID_Str (string str_id) static private
Referenced by OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
SameLine()
static proto native void SameLine () static private
Referenced by OnGUI(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
SameSpot()
static proto native void SameSpot () static private
SliderFloat()
static proto void SliderFloat (string label, out float value, float min, float max, int pxWidth = 150) static private
Spacer()
static proto native void Spacer (int height) static private
Referenced by OnGUI(), and ShowCoefsDbg().
Text()
static proto native void Text (string label) static private
Referenced by BleedingSourcesManagerBase::DisplayDebug(), WeaponDebug::DisplayGeneralInfo(), WeaponDebug::DisplayTargetInfo(), PluginBase::DrawDebugs(), Weapon::LiftWeaponCheck(), OnGUI(), OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_Variables(), OnGUI_VariablesEdit(), PluginBase::OnGUITimer(), MissionBase::OnUpdate(), UIScriptedMenu::SetCameraData(), ShowCoefsDbg(), Managed::ShowDebugValues(), and MissionBase::ShowHairDebugValues().
~DbgUI()
private void ~DbgUI () inline private