DayZ Scripts: FirearmActionDetachMagazine Class Reference
FirearmActionDetachMagazine Class Reference
Private Member Functions
void FirearmActionDetachMagazine ()
override ActionData CreateActionData ()
override bool InventoryReservation (ActionData action_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override GetInputType ()
override void CreateConditionComponents ()
override bool CanBePerformedFromQuickbar ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override void OnStageStart (SequentialActionData action_data)
override void OnUpdate (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
Detailed Description
Definition at line 147 of file FirearmActionDetachMagazine.c.
Constructor & Destructor Documentation
FirearmActionDetachMagazine()
void FirearmActionDetachMagazine () inline private
Definition at line 149 of file FirearmActionDetachMagazine.c.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 266 of file FirearmActionDetachMagazine.c.
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
Definition at line 276 of file FirearmActionDetachMagazine.c.
CanBePerformedFromQuickbar()
override bool CanBePerformedFromQuickbar () inline private
Definition at line 261 of file FirearmActionDetachMagazine.c.
CreateActionData()
override ActionData CreateActionData () inline private
Definition at line 153 of file FirearmActionDetachMagazine.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 255 of file FirearmActionDetachMagazine.c.
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType () inline private
Definition at line 250 of file FirearmActionDetachMagazine.c.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 238 of file FirearmActionDetachMagazine.c.
References InventoryLocation::Copy(), AdvDetachMagActionReciveData::m_ilMagazine, and AdvDetachMagActionReciveData::m_ilWeapon.
InventoryReservation()
override bool InventoryReservation (ActionData action_data) inline private
Definition at line 160 of file FirearmActionDetachMagazine.c.
References ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
Definition at line 362 of file FirearmActionDetachMagazine.c.
References CGame::ClearJuncture(), GetGame(), ActionData::m_Player, and ActionData::m_Target.
OnStageStart()
override void OnStageStart (SequentialActionData action_data) inline private
Definition at line 281 of file FirearmActionDetachMagazine.c.
References End(), GetGame(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_ReciveEndInput, SequentialActionData::m_Stage, and ActionData::m_Target.
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
Definition at line 356 of file FirearmActionDetachMagazine.c.
References CGame::AddInventoryJunctureEx(), GetGame(), ActionData::m_Player, and ActionData::m_Target.
OnUpdate()
override void OnUpdate (ActionData action_data) inline private
Definition at line 329 of file FirearmActionDetachMagazine.c.
References ActionData::m_MainItem, ActionData::m_Player, SequentialActionData::m_Stage, and SetStage().
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 213 of file FirearmActionDetachMagazine.c.
References AdvDetachMagActionReciveData::m_ilMagazine, AdvDetachMagActionReciveData::m_ilWeapon, and InventoryLocation::ReadFromContext().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 202 of file FirearmActionDetachMagazine.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Weapons/FirearmActionDetachMagazine.c