DayZ Scripts: DayZIntroScenePC Class Reference
DayZIntroScenePC Class Reference
Private Member Functions
void DayZIntroScenePC ()
protected override void SetInitPostprocesses ()
void SetClickEnable (bool enable)
bool IsClickEnabled ()
void CharacterRotationStart ()
void CharacterRotationStop ()
bool IsRotatingCharacter ()
void CharacterRotate ()
void Update ()
Private Attributes
protected bool m_EnableClick
protected bool m_RotatingCharacter
protected int m_RotatingCharacterMouseX
protected int m_RotatingCharacterMouseY
protected float m_RotatingCharacterRot
protected float m_Radius
protected float m_Radius_original
protected float m_DiffX
protected float m_DeltaX
protected float m_DeltaZ
protected float m_Angle
protected float m_Angle_offset = 0
protected float m_NewX = 0
protected float m_NewZ = 0
protected float m_BlurValue
protected ref OptionsMenu m_optmenu
Detailed Description
Definition at line 1 of file DayZIntroScenePC.c.
Constructor & Destructor Documentation
DayZIntroScenePC()
void DayZIntroScenePC () inline private
Definition at line 22 of file DayZIntroScenePC.c.
References Math::AbsFloat(), DayZIntroScene::m_Camera, DayZIntroScene::m_CharacterPos, m_DeltaX, m_DeltaZ, m_Radius, m_Radius_original, Math::Pow(), SetClickEnable(), and Math::Sqrt().
Member Function Documentation
CharacterRotate()
void CharacterRotate () inline private
Definition at line 86 of file DayZIntroScenePC.c.
References Math::Floor(), g_Game, DayZIntroScene::m_Character, DayZIntroScene::m_CharacterRot, m_DiffX, m_RotatingCharacterMouseX, and m_RotatingCharacterRot.
Referenced by Update().
CharacterRotationStart()
void CharacterRotationStart () inline private
Definition at line 59 of file DayZIntroScenePC.c.
References g_Game, DayZIntroScene::m_Character, DayZIntroScene::m_CharacterRot, m_RotatingCharacter, m_RotatingCharacterMouseX, m_RotatingCharacterMouseY, and m_RotatingCharacterRot.
Referenced by UIScriptedMenu::OnMouseButtonDown().
CharacterRotationStop()
void CharacterRotationStop () inline private
Definition at line 71 of file DayZIntroScenePC.c.
References m_RotatingCharacter.
Referenced by UIScriptedMenu::OnMouseButtonUp().
IsClickEnabled()
bool IsClickEnabled () inline private
Definition at line 53 of file DayZIntroScenePC.c.
References m_EnableClick.
IsRotatingCharacter()
bool IsRotatingCharacter () inline private
Definition at line 80 of file DayZIntroScenePC.c.
References m_RotatingCharacter.
SetClickEnable()
void SetClickEnable (bool enable) inline private
Definition at line 47 of file DayZIntroScenePC.c.
References m_EnableClick.
Referenced by DayZIntroScenePC().
SetInitPostprocesses()
protected override void SetInitPostprocesses () inline private
Definition at line 36 of file DayZIntroScenePC.c.
References Class::CastTo().
Update()
void Update () inline private
Definition at line 106 of file DayZIntroScenePC.c.
References CharacterRotate(), DayZIntroScene::m_Character, and m_RotatingCharacter.
Field Documentation
m_Angle
protected float m_Angle private
Definition at line 13 of file DayZIntroScenePC.c.
m_Angle_offset
protected float m_Angle_offset = 0 private
Definition at line 14 of file DayZIntroScenePC.c.
m_BlurValue
protected float m_BlurValue private
Definition at line 17 of file DayZIntroScenePC.c.
m_DeltaX
protected float m_DeltaX private
Definition at line 11 of file DayZIntroScenePC.c.
Referenced by DayZIntroScenePC().
m_DeltaZ
protected float m_DeltaZ private
Definition at line 12 of file DayZIntroScenePC.c.
Referenced by DayZIntroScenePC().
m_DiffX
protected float m_DiffX private
Definition at line 10 of file DayZIntroScenePC.c.
Referenced by CharacterRotate().
m_EnableClick
protected bool m_EnableClick private
Definition at line 3 of file DayZIntroScenePC.c.
Referenced by IsClickEnabled(), and SetClickEnable().
m_NewX
protected float m_NewX = 0 private
Definition at line 15 of file DayZIntroScenePC.c.
m_NewZ
protected float m_NewZ = 0 private
Definition at line 16 of file DayZIntroScenePC.c.
m_optmenu
protected ref OptionsMenu m_optmenu private
Definition at line 19 of file DayZIntroScenePC.c.
m_Radius
protected float m_Radius private
Definition at line 8 of file DayZIntroScenePC.c.
Referenced by DayZIntroScenePC().
m_Radius_original
protected float m_Radius_original private
Definition at line 9 of file DayZIntroScenePC.c.
Referenced by DayZIntroScenePC().
m_RotatingCharacter
protected bool m_RotatingCharacter private
Definition at line 4 of file DayZIntroScenePC.c.
Referenced by CharacterRotationStart(), CharacterRotationStop(), IsRotatingCharacter(), and Update().
m_RotatingCharacterMouseX
protected int m_RotatingCharacterMouseX private
Definition at line 5 of file DayZIntroScenePC.c.
Referenced by CharacterRotate(), and CharacterRotationStart().
m_RotatingCharacterMouseY
protected int m_RotatingCharacterMouseY private
Definition at line 6 of file DayZIntroScenePC.c.
Referenced by CharacterRotationStart().
m_RotatingCharacterRot
protected float m_RotatingCharacterRot private
Definition at line 7 of file DayZIntroScenePC.c.
Referenced by CharacterRotate(), and CharacterRotationStart().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/DayZIntroScenePC.c