DayZ Scripts: ObjectSpawnerHandler Class Reference
ObjectSpawnerHandler Class Reference
Static Private Member Functions
static void SpawnObjects ()
static void SpawnObject (ITEM_SpawnerObject item)
static void OnGameplayDataHandlerLoad ()
static bool ValidatePath (string path)
Static Private Attributes
static protected const ref TStringArray VALID_PATHS = {"DZ\\plants","DZ\\plants_bliss","DZ\\rocks","DZ\\rocks_bliss","DZ/plants","DZ/plants_bliss","DZ/rocks","DZ/rocks_bliss"}
Member Function Documentation
OnGameplayDataHandlerLoad()
static void OnGameplayDataHandlerLoad () inline static private
References GetGame(), CGame::GetWorld(), World::ProcessMarkedObjectsForPathgraphUpdate(), and SpawnObjects().
Referenced by CGame::GlobalsInit().
SpawnObject()
static void SpawnObject (ITEM_SpawnerObject item) inline static private
References vector::ArrayToVec(), string::Contains(), CGame::CreateObjectEx(), CGame::CreateStaticObjectUsingP3D(), ECE_CREATEPHYSICS, ECE_DYNAMIC_PERSISTENCY, ECE_NOLIFETIME, ECE_SETUP, ECE_UPDATEPATHGRAPH, ITEM_SpawnerObject::enableCEPersistency, GetGame(), ITEM_SpawnerObject::name, ITEM_SpawnerObject::pos, PrintToRPT(), RF_IGNORE, ITEM_SpawnerObject::scale, ValidatePath(), and ITEM_SpawnerObject::ypr.
Referenced by SpawnObjects().
SpawnObjects()
static void SpawnObjects () inline static private
References FileExist(), CfgGameplayHandler::GetObjectSpawnersArr(), ObjectSpawnerJson::Objects, path, and SpawnObject().
Referenced by OnGameplayDataHandlerLoad().
ValidatePath()
static bool ValidatePath (string path) inline static private
References string::Contains(), path, and VALID_PATHS.
Referenced by SpawnObject().
Field Documentation
VALID_PATHS
protected const ref TStringArray VALID_PATHS = {"DZ\\plants","DZ\\plants_bliss","DZ\\rocks","DZ\\rocks_bliss","DZ/plants","DZ/plants_bliss","DZ/rocks","DZ/rocks_bliss"} static private
Referenced by ValidatePath().
The documentation for this class was generated from the following file:
3_Game/ObjectSpawner.c