DayZ Scripts: CatchingContextTrapsBase Class Reference
CatchingContextTrapsBase Class Reference
Private Member Functions
override protected void DeserializeData (Param par)
override protected void CreateResultDataStructure ()
override protected void ClearCatchingItemData ()
override protected void InitItemValues (EntityAI item)
float AdjustBaitItemChance (EntityAI item)
Allows for adjustment of all catch probabilities from item qualities (damage, qty...)
override protected void InitCatchEnviroMask ()
override protected void Init (Param par)
override protected void SetupInitialTypes ()
void UpdateDataAndMasks ()
int UpdateTrapEnviroMask ()
void SetTrapEnviroMask (int value)
void UpdateUsedBait (ECatchingBaitCategories type)
if non-empty bait type is used, some 'Bait' attachment is picked as an active bait (currently no direct link between item and sensitivity-weighted target probability)
override void UpdateBaseProbability (YieldItemBase yItem)
override bool ModifySignalProbability (inout float probability)
void RemoveBait ()
void ReduceBaitQty (float qtyNorm)
Private Attributes
protected float m_CumulativeTrappingSuccess
after N attempts, the chance to catch should be this. Only highest one applies. @NOTE: Take care, only way to achieve guaranteed 1.0 chance at the end is to have EVERY chance at 1.0.
protected int m_AttemptsCount
protected ItemBase m_Bait
Member Function Documentation
AdjustBaitItemChance()
float AdjustBaitItemChance (EntityAI item) inline private
Allows for adjustment of all catch probabilities from item qualities (damage, qty...)
References Class::CastTo().
Referenced by InitItemValues().
ClearCatchingItemData()
override protected void ClearCatchingItemData () inline private
References m_CumulativeTrappingSuccess, m_QualityBaseMod, m_QualityDispersionMaxMod, and m_QualityDispersionMinMod.
CreateResultDataStructure()
override protected void CreateResultDataStructure () inline private
References m_MainItem, and m_Result.
DeserializeData()
override protected void DeserializeData (Param par) inline private
References Class::CastTo(), m_AttemptsCount, and m_MainItem.
Init()
override protected void Init (Param par) inline private
References GenerateResult().
InitCatchEnviroMask()
override protected void InitCatchEnviroMask () inline private
References GetGame(), m_EnviroMask, m_MainItem, AnimalCatchingConstants::MASK_ENVIRO_LAND_ALL, AnimalCatchingConstants::MASK_ENVIRO_POND, and AnimalCatchingConstants::MASK_ENVIRO_SEA.
Referenced by UpdateTrapEnviroMask().
InitItemValues()
override protected void InitItemValues (EntityAI item) inline private
References AdjustBaitItemChance(), CachedObjectsArrays::ARRAY_FLOAT, CachedObjectsArrays::ARRAY_INT, CFG_VEHICLESPATH, CGame::ConfigGetFloat(), CGame::ConfigGetFloatArray(), CGame::ConfigGetIntArray(), ErrorEx, GetGame(), m_BaitCompatibilityMap, m_QualityBaseMod, m_QualityDispersionMaxMod, m_QualityDispersionMinMod, and path.
ModifySignalProbability()
override bool ModifySignalProbability (inout float probability) inline private
References m_AttemptsCount, m_CumulativeTrappingSuccess, and Math::Pow().
Referenced by UpdateBaseProbability().
ReduceBaitQty()
void ReduceBaitQty (float qtyNorm) inline private
References ItemBase::CanBeSplit(), and m_Bait.
RemoveBait()
void RemoveBait () inline private
References m_Bait.
SetTrapEnviroMask()
void SetTrapEnviroMask (int value) inline private
References m_EnviroMask.
SetupInitialTypes()
override protected void SetupInitialTypes () inline private
References IsCLIParam(), and Print().
Referenced by UpdateDataAndMasks().
UpdateBaseProbability()
override void UpdateBaseProbability (YieldItemBase yItem) inline private
References Math::Clamp(), YieldItemBase::GetBaitTypeSensitivity(), IsCLIParam(), m_BaitCompatibilityMap, m_CumulativeTrappingSuccess, ModifySignalProbability(), Print(), and UpdateUsedBait().
UpdateDataAndMasks()
void UpdateDataAndMasks () inline private
References InitCatchingItemData(), InitCatchMethodMask(), SetupInitialTypes(), and SetupProbabilityArray().
UpdateTrapEnviroMask()
int UpdateTrapEnviroMask () inline private
References GetCatchEnviroMask(), and InitCatchEnviroMask().
UpdateUsedBait()
void UpdateUsedBait (ECatchingBaitCategories type) inline private
if non-empty bait type is used, some 'Bait' attachment is picked as an active bait (currently no direct link between item and sensitivity-weighted target probability)
References ErrorEx, IsCLIParam(), m_Bait, m_BaitCompatibilityMap, m_MainItem, BaitData::m_Owner, and Print().
Referenced by UpdateBaseProbability().
Field Documentation
m_AttemptsCount
protected int m_AttemptsCount private
Referenced by DeserializeData(), and ModifySignalProbability().
m_Bait
protected ItemBase m_Bait private
Referenced by ReduceBaitQty(), RemoveBait(), and UpdateUsedBait().
m_CumulativeTrappingSuccess
m_CumulativeTrappingSuccess private
after N attempts, the chance to catch should be this. Only highest one applies. @NOTE: Take care, only way to achieve guaranteed 1.0 chance at the end is to have EVERY chance at 1.0.
Referenced by ClearCatchingItemData(), ModifySignalProbability(), and UpdateBaseProbability().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Systems/AnimalCatchingSystem/CatchingContexts/CatchingContextTraps.c