DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionTakeItemToHands.c File Reference
ActionTakeItemToHands.c File Reference
Data Structures
class ActionTakeItemToHands
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool UseMainItem ()
override bool MainItemAlwaysInHands ()
override void CreateAndSetupActionCallback (ActionData action_data)
override void Start (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnEndClient (ActionData action_data)
void PerformSwap (ActionData action_data)
Variables
ActionTakeItemToHands m_Executable
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 111 of file ActionTakeItemToHands.c.
References ItemBase::IsTakeable().
CreateAndSetupActionCallback()
override void CreateAndSetupActionCallback (ActionData action_data)
Definition at line 130 of file ActionTakeItemToHands.c.
References Class::CastTo(), ActionBaseCB::InitActionComponent(), ActionData::m_Callback, ActionData::m_Player, ActionData::m_Target, and ActionBaseCB::SetActionData().
MainItemAlwaysInHands()
override bool MainItemAlwaysInHands ()
Definition at line 125 of file ActionTakeItemToHands.c.
OnEndClient()
override void OnEndClient (ActionData action_data)
Definition at line 201 of file ActionTakeItemToHands.c.
References m_Executable, and PerformSwap().
OnEndServer()
override void OnEndServer (ActionData action_data)
Definition at line 187 of file ActionTakeItemToHands.c.
References GetGame(), m_Executable, and PerformSwap().
OnExecuteClient()
override void OnExecuteClient (ActionData action_data)
Definition at line 179 of file ActionTakeItemToHands.c.
References m_Executable, and PerformSwap().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
Definition at line 168 of file ActionTakeItemToHands.c.
References GetGame(), m_Executable, and PerformSwap().
PerformSwap()
void PerformSwap (ActionData action_data)
Definition at line 212 of file ActionTakeItemToHands.c.
References ActionData::m_Player, and ActionData::m_Target.
Referenced by OnEndClient(), OnEndServer(), OnExecuteClient(), and OnExecuteServer().
Start()
override void Start (ActionData action_data)
Definition at line 152 of file ActionTakeItemToHands.c.
References IsHeavyBehaviour(), m_Executable, ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
UseMainItem()
override bool UseMainItem ()
Definition at line 120 of file ActionTakeItemToHands.c.
Variable Documentation
m_Executable
ActionTakeItemToHands m_Executable
Referenced by OnEndClient(), OnEndServer(), OnExecuteClient(), OnExecuteServer(), and Start().