DayZ Scripts: ActionFillObject Class Reference
ActionFillObject Class Reference
Private Member Functions
void ActionFillObject ()
override void CreateConditionComponents ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override void OnFinishProgressClient (ActionData action_data)
Private Attributes
protected int m_ActionState
protected const int EMPTY = 0
protected const int FILLED = 1
Constructor & Destructor Documentation
ActionFillObject()
void ActionFillObject () inline private
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Class::CastTo(), EMPTY, FILLED, and m_ActionState.
CreateConditionComponents()
override void CreateConditionComponents () inline private
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
References m_Text.
OnFinishProgressClient()
override void OnFinishProgressClient (ActionData action_data) inline private
References Class::CastTo(), and ActionData::m_Target.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References Class::CastTo(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, ActionData::m_Target, and ItemBase::Unfold().
Field Documentation
EMPTY
protected const int EMPTY = 0 private
Referenced by ActionCondition().
FILLED
protected const int FILLED = 1 private
Referenced by ActionCondition().
m_ActionState
protected int m_ActionState private
Referenced by ActionCondition().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionFillObject.c