DayZ Scripts: ActionSortAmmoPile Class Reference
ActionSortAmmoPile Class Reference
Private Member Functions
void ActionSortAmmoPile ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnEndAnimationLoopServer (ActionData action_data)
void SortAmmo (ItemBase item)
Detailed Description
Definition at line 9 of file ActionSortAmmoPile.c.
Constructor & Destructor Documentation
ActionSortAmmoPile()
void ActionSortAmmoPile () inline private
Definition at line 11 of file ActionSortAmmoPile.c.
References AnimatedActionBase::m_CallbackClass, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 24 of file ActionSortAmmoPile.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 18 of file ActionSortAmmoPile.c.
References m_ConditionItem, and m_ConditionTarget.
OnEndAnimationLoopServer()
override void OnEndAnimationLoopServer (ActionData action_data) inline private
Definition at line 29 of file ActionSortAmmoPile.c.
References ActionData::m_MainItem, and SortAmmo().
SortAmmo()
void SortAmmo (ItemBase item) inline private
Definition at line 34 of file ActionSortAmmoPile.c.
References Class::CastTo(), ECE_PLACE_ON_SURFACE, and GetGame().
Referenced by OnEndAnimationLoopServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionSortAmmoPile.c