DayZ Scripts: ActionManagerClient Class Reference
ActionManagerClient Class Reference
Private Member Functions
void ActionManagerClient (PlayerBase player)
override void Update (int pCurrentCommandID)
void RegisterInputs (PlayerBase player)
void SetActioninputOrder ()
void SetDefaultInputsOrder ()
override void RequestEndAction ()
override void EndActionInput ()
void InputsUpdate ()
void ProcessActionRequestEnd ()
void ProcessActionInputEnd ()
ActionBase GetPossibleAction (typename inputType)
array< ActionBase > GetPossibleActions (typename inputType)
int GetPossibleActionIndex (typename inputType)
int GetPossibleActionCount (typename inputType)
void InjectAction (ActionBase action, ActionTarget target, ItemBase item)
void InjectAction (typename actionType, ActionTarget target, ItemBase item)
void EjectAction (ActionBase action)
void EjectAction (typename actionType)
void ForceTarget (Object targetObject)
void ClearForceTarget ()
override ActionTarget FindActionTarget ()
ItemBase FindActionItem ()
protected bool HasHandInventoryReservation ()
protected void FindContextualUserActions (int pCurrentCommandID)
protected bool LockInventory (ActionData action_data)
void UnlockInventory (ActionData action_data)
protected void ActionStart (ActionBase action, ActionTarget target, ItemBase item, Param extra_data=NULL)
void HandleInputsOnActionStart (ActionBase action)
void HandleInputsOnActionEnd ()
void ResetInputsState ()
void ResetInputsActions ()
override void OnJumpStart ()
override void OnInstantAction (typename user_action_type, Param data=NULL)
void PerformActionStart (ActionBase action, ActionTarget target, ItemBase item, Param extra_data=NULL)
override void OnActionEnd ()
void SetInventoryAction (ActionBase action_name, ItemBase target_item, ItemBase main_item)
void SetInventoryAction (ActionBase action_name, ActionTarget target, ItemBase main_item)
void UnsetInventoryAction ()
override GetSelectedActionCategory ()
void UpdateActionCategoryPriority ()
override void SelectFirstActionCategory ()
override void SelectNextActionCategory ()
override void SelectPrevActionCategory ()
override void SelectNextAction ()
override void SelectPrevAction ()
bool CanPerformActionFromQuickbar (ItemBase mainItem, ItemBase targetItem)
void PerformActionFromQuickbar (ItemBase mainItem, ItemBase targetItem)
bool CanPerformActionFromInventory (ItemBase mainItem, ItemBase targetItem)
void PerformActionFromInventory (ItemBase mainItem, ItemBase targetItem)
bool CanSetActionFromInventory (ItemBase mainItem, ItemBase targetItem)
void SetActionFromInventory (ItemBase mainItem, ItemBase targetItem)
override void Interrupt ()
void RequestInterruptAction ()
client requests action interrupt
Static Private Member Functions
static ActionVariantManager GetVariantManager (typename actionName)
Private Attributes
protected int m_LastAcknowledgmentID
protected bool m_ActionPossible
protected ref array< ref InventoryLocation > m_ReservedInventoryLocations
protected ref InventoryActionHandler m_InventoryActionHandler
protected ref InventoryLocation m_HandInventoryLocationTest
protected ref TTypeNameActionInputMap m_RegistredInputsMap
protected ref array< ActionInput > m_OrederedAllActionInput
protected ref array< ActionInput > m_OrderedStandartActionInputs
protected ref array< ActionInput > m_DefaultOrderOfActionInputs
protected int m_SelectedActionInputToSrollIndex
protected ref ActionData m_PendingActionData
protected bool m_ActionWantEndRequest_Send
protected bool m_ActionInputWantEnd_Send
private ref ActionTarget m_ForceTarget
private ref ActionTargets m_Targets
Detailed Description
Definition at line 4 of file ActionManagerClient.c.
Constructor & Destructor Documentation
ActionManagerClient()
void ActionManagerClient (PlayerBase player) inline private
Definition at line 24 of file ActionManagerClient.c.
References m_ActionInputWantEnd_Send, m_ActionWantEndRequest_Send, m_HandInventoryLocationTest, m_InventoryActionHandler, m_LastAcknowledgmentID, m_ReservedInventoryLocations, m_SelectedActionInputToSrollIndex, m_Targets, RegisterInputs(), and InventoryLocation::SetHands().
Member Function Documentation
ActionStart()
protected void ActionStart (ActionBase action, ActionTarget target, ItemBase item, Param extra_data = NULL) inline private
Definition at line 592 of file ActionManagerClient.c.
References Debug::ActionLog(), ScriptInputUserData::CanStoreInputUserData(), DPrint(), GetGame(), HandleInputsOnActionStart(), INPUT_UDT_STANDARD_ACTION_START, LogManager::IsActionLogEnable(), m_ActionInputWantEnd, m_ActionInputWantEnd_Send, m_ActionWantEndRequest, m_ActionWantEndRequest_Send, m_CurrentActionData, m_Interrupted, m_LastAcknowledgmentID, m_PendingActionAcknowledgmentID, m_Player, ActionData::m_State, OnActionEnd(), ScriptInputUserData::Send(), UA_AM_PENDING, and Serializer::Write().
Referenced by InputsUpdate(), OnInstantAction(), PerformActionFromInventory(), PerformActionFromQuickbar(), and PerformActionStart().
CanPerformActionFromInventory()
bool CanPerformActionFromInventory (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 1022 of file ActionManagerClient.c.
References ActionBase(), ActionTarget, m_Player, and vector::Zero.
Referenced by Attachments::CanCombineAmmo(), Container::CanCombineAmmo(), VicinitySlotsContainer::CanCombineAmmo(), and ItemManager::GetCombinationFlags().
CanPerformActionFromQuickbar()
bool CanPerformActionFromQuickbar (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 892 of file ActionManagerClient.c.
References ActionBase(), ActionTarget, ContinuousDefaultActionInput(), m_Player, and vector::Zero.
Referenced by ManBase::OnQuickBarContinuousUseStart().
CanSetActionFromInventory()
bool CanSetActionFromInventory (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 1120 of file ActionManagerClient.c.
References ActionBase(), ActionTarget, ContinuousDefaultActionInput(), m_Player, and vector::Zero.
Referenced by Container::CanCombineAmmo(), VicinitySlotsContainer::CanCombineAmmo(), HandsContainer::GetCombinationFlags(), and ItemManager::GetCombinationFlags().
ClearForceTarget()
void ClearForceTarget () inline private
Definition at line 465 of file ActionManagerClient.c.
References m_ForceTarget.
Referenced by InventoryActionHandler::DeactiveAction(), and ManBase::OnQuickBarContinuousUseEnd().
EjectAction() [1/2]
void EjectAction (ActionBase action) inline private
Definition at line 444 of file ActionManagerClient.c.
References ActionInput::ClearForcedAction().
Referenced by InventoryActionHandler::DeactiveAction(), and EjectAction().
EjectAction() [2/2]
void EjectAction (typename actionType) inline private
Definition at line 450 of file ActionManagerClient.c.
References ActionBase(), EjectAction(), and GetAction().
EndActionInput()
override void EndActionInput () inline private
Definition at line 270 of file ActionManagerClient.c.
References m_ActionInputWantEnd, and m_ActionInputWantEnd_Send.
Referenced by InputsUpdate(), and ManBase::OnQuickBarContinuousUseEnd().
FindActionItem()
ItemBase FindActionItem () inline private
Definition at line 506 of file ActionManagerClient.c.
References m_Player.
Referenced by FindContextualUserActions().
FindActionTarget()
override ActionTarget FindActionTarget () inline private
Definition at line 472 of file ActionManagerClient.c.
References ActionTarget, ActionTargets::GetTarget(), ActionTargets::GetTargetsCount(), m_ForceTarget, m_Targets, and vector::Zero.
Referenced by FindContextualUserActions().
FindContextualUserActions()
protected void FindContextualUserActions (int pCurrentCommandID) inline private
Definition at line 524 of file ActionManagerClient.c.
References ActionBase(), ActionTarget, FindActionItem(), FindActionTarget(), GetGame(), GetRunningAction(), HasHandInventoryReservation(), m_ActionPossible, m_ActionsAvaibale, m_OrederedAllActionInput, m_Player, ResetInputsActions(), SetActionContext(), and ActionInput::UpdatePossibleActions().
Referenced by Update().
ForceTarget()
void ForceTarget (Object targetObject) inline private
Definition at line 456 of file ActionManagerClient.c.
References ActionTarget, m_ForceTarget, and vector::Zero.
Referenced by ManBase::OnQuickBarContinuousUseStart(), and InventoryActionHandler::SetAction().
GetPossibleAction()
ActionBase GetPossibleAction (typename inputType) inline private
Definition at line 389 of file ActionManagerClient.c.
References ActionInput::GetAction(), and m_RegistredInputsMap.
GetPossibleActionCount()
int GetPossibleActionCount (typename inputType) inline private
Definition at line 419 of file ActionManagerClient.c.
References ActionInput::GetPossibleActionsCount(), and m_RegistredInputsMap.
GetPossibleActionIndex()
int GetPossibleActionIndex (typename inputType) inline private
Definition at line 409 of file ActionManagerClient.c.
References ActionInput::GetPossibleActionIndex(), and m_RegistredInputsMap.
GetPossibleActions()
array< ActionBase > GetPossibleActions (typename inputType) inline private
Definition at line 399 of file ActionManagerClient.c.
References ActionInput::GetPossibleActions(), and m_RegistredInputsMap.
GetSelectedActionCategory()
override GetSelectedActionCategory () inline private
Definition at line 785 of file ActionManagerClient.c.
References m_OrderedStandartActionInputs, and m_SelectedActionInputToSrollIndex.
GetVariantManager()
static ActionVariantManager GetVariantManager (typename actionName) inline static private
Definition at line 251 of file ActionManagerClient.c.
References ActionBase(), and GetAction().
Referenced by ConstructionActionData::ConstructionActionData(), and CraftingManager::CraftingManager().
HandleInputsOnActionEnd()
void HandleInputsOnActionEnd () inline private
Definition at line 687 of file ActionManagerClient.c.
References ResetInputsState().
Referenced by OnActionEnd().
HandleInputsOnActionStart()
void HandleInputsOnActionStart (ActionBase action) inline private
Definition at line 671 of file ActionManagerClient.c.
References m_OrederedAllActionInput, ActionInput::OnActionStart(), and ActionInput::Reset().
Referenced by ActionStart().
HasHandInventoryReservation()
protected bool HasHandInventoryReservation () inline private
Definition at line 516 of file ActionManagerClient.c.
References m_HandInventoryLocationTest, m_Player, and InventoryLocation::SetHands().
Referenced by FindContextualUserActions().
InjectAction() [1/2]
void InjectAction (ActionBase action, ActionTarget target, ItemBase item) inline private
Definition at line 432 of file ActionManagerClient.c.
References ActionInput::ForceAction().
Referenced by InjectAction().
InjectAction() [2/2]
void InjectAction (typename actionType , ActionTarget target, ItemBase item) inline private
Definition at line 438 of file ActionManagerClient.c.
References ActionBase(), GetAction(), and InjectAction().
InputsUpdate()
void InputsUpdate () inline private
Definition at line 278 of file ActionManagerClient.c.
References ActionBase(), ActionStart(), EndActionInput(), ActionInput::GetAction(), ActionInput::GetInputType(), ActionInput::GetUsedActionTarget(), ActionInput::GetUsedMainItem(), ActionInput::JustActivate(), ActionData::m_Action, m_ActionInputWantEnd, m_ActionsAvaibale, m_CurrentActionData, m_OrederedAllActionInput, m_Player, ActionInput::Update(), and ActionInput::WasEnded().
Referenced by Update().
Interrupt()
override void Interrupt () inline private
Definition at line 1255 of file ActionManagerClient.c.
References m_CurrentActionData, and m_Interrupted.
Referenced by ManBase::ReloadWeapon().
LockInventory()
protected bool LockInventory (ActionData action_data) inline private
Definition at line 558 of file ActionManagerClient.c.
References Debug::ActionLog(), LogManager::IsActionLogEnable(), ActionData::m_Action, and ActionData::m_Player.
OnActionEnd()
override void OnActionEnd () inline private
Definition at line 757 of file ActionManagerClient.c.
References InventoryActionHandler::DeactiveAction(), HandleInputsOnActionEnd(), ActionData::m_Action, m_CurrentActionData, m_InventoryActionHandler, and UnlockInventory().
Referenced by ActionStart(), OnJumpStart(), and Update().
OnInstantAction()
override void OnInstantAction (typename user_action_type , Param data = NULL) inline private
Definition at line 727 of file ActionManagerClient.c.
References ActionBase(), ActionStart(), and GetAction().
OnJumpStart()
override void OnJumpStart () inline private
Definition at line 710 of file ActionManagerClient.c.
References ActionData::m_Action, m_CurrentActionData, m_PendingActionAcknowledgmentID, ActionData::m_State, OnActionEnd(), UA_AM_ACCEPTED, UA_AM_PENDING, and UA_AM_REJECTED.
PerformActionFromInventory()
void PerformActionFromInventory (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 1069 of file ActionManagerClient.c.
References ActionBase(), ActionStart(), ActionTarget, m_Player, and vector::Zero.
Referenced by Icon::OnPerformCombination().
PerformActionFromQuickbar()
void PerformActionFromQuickbar (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 950 of file ActionManagerClient.c.
References ActionBase(), ActionStart(), ActionTarget, ContinuousDefaultActionInput(), m_Player, and vector::Zero.
Referenced by ManBase::OnQuickBarContinuousUseStart().
PerformActionStart()
void PerformActionStart (ActionBase action, ActionTarget target, ItemBase item, Param extra_data = NULL) inline private
Definition at line 744 of file ActionManagerClient.c.
References ActionStart(), GetGame(), m_PendingActionData, and m_Player.
Referenced by UIScriptedMenu::HandleLights(), UIScriptedMenu::HandleNVG(), OnCenterPanelDropReceived(), ManBase::PhysicalPredictiveDropItem(), ManBase::PredictiveForceSwapEntities(), ManBase::PredictiveSwapEntities(), ManBase::PredictiveTakeEntityToHands(), and ManBase::ReloadWeapon().
ProcessActionInputEnd()
void ProcessActionInputEnd () inline private
Definition at line 355 of file ActionManagerClient.c.
References Debug::ActionLog(), ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_STANDARD_ACTION_INPUT_END, LogManager::IsActionLogEnable(), ActionData::m_Action, m_ActionInputWantEnd, m_ActionInputWantEnd_Send, m_CurrentActionData, m_Player, ActionData::m_Player, ScriptInputUserData::Send(), and Serializer::Write().
Referenced by Update().
ProcessActionRequestEnd()
void ProcessActionRequestEnd () inline private
Definition at line 325 of file ActionManagerClient.c.
References Debug::ActionLog(), ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_STANDARD_ACTION_END_REQUEST, LogManager::IsActionLogEnable(), ActionData::m_Action, m_ActionWantEndRequest, m_ActionWantEndRequest_Send, m_CurrentActionData, m_Player, ActionData::m_Player, ScriptInputUserData::Send(), and Serializer::Write().
Referenced by Update().
RegisterInputs()
void RegisterInputs (PlayerBase player) inline private
Definition at line 134 of file ActionManagerClient.c.
References ActionBase(), m_ActionsArray, m_RegistredInputsMap, and SetActioninputOrder().
Referenced by ActionManagerClient().
RequestEndAction()
override void RequestEndAction () inline private
Definition at line 262 of file ActionManagerClient.c.
References m_ActionWantEndRequest, and m_ActionWantEndRequest_Send.
Referenced by ManBase::CloseMapEx(), ActionReadPaper::OnUpdate(), and ActionWritePaper::OnUpdate().
RequestInterruptAction()
void RequestInterruptAction () inline private
client requests action interrupt
Definition at line 1264 of file ActionManagerClient.c.
References ScriptInputUserData::CanStoreInputUserData(), INPUT_UDT_STANDARD_ACTION_END_REQUEST, ScriptInputUserData::Send(), and Serializer::Write().
Referenced by ManBase::CloseMapEx().
ResetInputsActions()
void ResetInputsActions () inline private
Definition at line 701 of file ActionManagerClient.c.
References ActionInput::ActionsSelectReset(), and m_OrederedAllActionInput.
Referenced by FindContextualUserActions(), and Update().
ResetInputsState()
void ResetInputsState () inline private
Definition at line 692 of file ActionManagerClient.c.
References m_OrederedAllActionInput, and ActionInput::Reset().
Referenced by HandleInputsOnActionEnd().
SelectFirstActionCategory()
override void SelectFirstActionCategory () inline private
Definition at line 813 of file ActionManagerClient.c.
References GetPossibleActionsCount(), m_OrderedStandartActionInputs, m_SelectedActionInputToSrollIndex, and UpdateActionCategoryPriority().
SelectNextAction()
override void SelectNextAction () inline private
Definition at line 866 of file ActionManagerClient.c.
References ActionInput::GetPossibleActionsCount(), m_OrderedStandartActionInputs, m_SelectedActionInputToSrollIndex, and ActionInput::SelectNextAction().
SelectNextActionCategory()
override void SelectNextActionCategory () inline private
Definition at line 828 of file ActionManagerClient.c.
References GetPossibleActionsCount(), m_OrderedStandartActionInputs, and m_SelectedActionInputToSrollIndex.
SelectPrevAction()
override void SelectPrevAction () inline private
Definition at line 879 of file ActionManagerClient.c.
References ActionInput::GetPossibleActionsCount(), m_OrderedStandartActionInputs, m_SelectedActionInputToSrollIndex, and ActionInput::SelectPrevAction().
SelectPrevActionCategory()
override void SelectPrevActionCategory () inline private
Definition at line 846 of file ActionManagerClient.c.
References GetPossibleActionsCount(), m_OrderedStandartActionInputs, and m_SelectedActionInputToSrollIndex.
SetActionFromInventory()
void SetActionFromInventory (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 1206 of file ActionManagerClient.c.
References ActionBase(), ActionTarget, ContinuousDefaultActionInput(), m_Player, SetInventoryAction(), and vector::Zero.
Referenced by Icon::OnPerformCombination().
SetActioninputOrder()
void SetActioninputOrder () inline private
Definition at line 165 of file ActionManagerClient.c.
References ActionInput::GetPriority(), m_OrederedAllActionInput, m_RegistredInputsMap, and SetDefaultInputsOrder().
Referenced by RegisterInputs().
SetDefaultInputsOrder()
void SetDefaultInputsOrder () inline private
Definition at line 209 of file ActionManagerClient.c.
References ContinuousDefaultActionInput(), m_DefaultOrderOfActionInputs, m_OrderedStandartActionInputs, m_OrederedAllActionInput, and m_RegistredInputsMap.
Referenced by SetActioninputOrder().
SetInventoryAction() [1/2]
void SetInventoryAction (ActionBase action_name, ActionTarget target, ItemBase main_item) inline private
Definition at line 775 of file ActionManagerClient.c.
References m_InventoryActionHandler, and InventoryActionHandler::SetAction().
SetInventoryAction() [2/2]
void SetInventoryAction (ActionBase action_name, ItemBase target_item, ItemBase main_item) inline private
Definition at line 770 of file ActionManagerClient.c.
References m_InventoryActionHandler, and InventoryActionHandler::SetAction().
Referenced by SetActionFromInventory(), and CraftingManager::SetInventoryCraft().
UnlockInventory()
void UnlockInventory (ActionData action_data) inline private
Definition at line 582 of file ActionManagerClient.c.
References Debug::ActionLog(), LogManager::IsActionLogEnable(), ActionData::m_Action, and ActionData::m_Player.
Referenced by OnActionEnd(), OnExecuteClient(), and OnExecuteServer().
UnsetInventoryAction()
void UnsetInventoryAction () inline private
Definition at line 780 of file ActionManagerClient.c.
References InventoryActionHandler::DeactiveAction(), and m_InventoryActionHandler.
Update()
override void Update (int pCurrentCommandID) inline private
Definition at line 39 of file ActionManagerClient.c.
References ActionBase(), ActionPossibilityCheck(), ActionTargets::Clear(), FindContextualUserActions(), GetGame(), CGame::GetUIManager(), InputsUpdate(), DeveloperFreeCamera::IsFreeCameraEnabled(), UIManager::IsMenuOpen(), DayZPlayer::IsRaised(), ActionData::m_Action, m_ActionPossible, m_CurrentActionData, m_InventoryActionHandler, ActionData::m_MainItem, m_PendingActionAcknowledgmentID, m_PendingActionData, m_Player, ActionData::m_State, ActionData::m_Target, m_Targets, MENU_INVENTORY, OnActionEnd(), InventoryActionHandler::OnUpdate(), ProcessActionInputEnd(), ProcessActionRequestEnd(), ResetInputsActions(), UA_AM_ACCEPTED, UA_AM_PENDING, UA_AM_REJECTED, UA_START, and ActionTargets::Update().
UpdateActionCategoryPriority()
void UpdateActionCategoryPriority () inline private
Definition at line 790 of file ActionManagerClient.c.
References HasTarget(), m_DefaultOrderOfActionInputs, and m_OrderedStandartActionInputs.
Referenced by SelectFirstActionCategory().
Field Documentation
m_ActionInputWantEnd_Send
protected bool m_ActionInputWantEnd_Send private
Definition at line 22 of file ActionManagerClient.c.
Referenced by ActionManagerClient(), ActionStart(), EndActionInput(), and ProcessActionInputEnd().
m_ActionPossible
protected bool m_ActionPossible private
Definition at line 9 of file ActionManagerClient.c.
Referenced by FindContextualUserActions(), and Update().
m_ActionWantEndRequest_Send
protected bool m_ActionWantEndRequest_Send private
Definition at line 21 of file ActionManagerClient.c.
Referenced by ActionManagerClient(), ActionStart(), ProcessActionRequestEnd(), and RequestEndAction().
m_DefaultOrderOfActionInputs
protected ref array<ActionInput> m_DefaultOrderOfActionInputs private
Definition at line 16 of file ActionManagerClient.c.
Referenced by SetDefaultInputsOrder(), and UpdateActionCategoryPriority().
m_ForceTarget
private ref ActionTarget m_ForceTarget private
Definition at line 1275 of file ActionManagerClient.c.
Referenced by ClearForceTarget(), FindActionTarget(), and ForceTarget().
m_HandInventoryLocationTest
protected ref InventoryLocation m_HandInventoryLocationTest private
Definition at line 12 of file ActionManagerClient.c.
Referenced by ActionManagerClient(), and HasHandInventoryReservation().
m_InventoryActionHandler
protected ref InventoryActionHandler m_InventoryActionHandler private
Definition at line 11 of file ActionManagerClient.c.
Referenced by ActionManagerClient(), OnActionEnd(), SetInventoryAction(), SetInventoryAction(), UnsetInventoryAction(), and Update().
m_LastAcknowledgmentID
protected int m_LastAcknowledgmentID private
Definition at line 8 of file ActionManagerClient.c.
Referenced by ActionManagerClient(), and ActionStart().
m_OrderedStandartActionInputs
protected ref array<ActionInput> m_OrderedStandartActionInputs private
Definition at line 15 of file ActionManagerClient.c.
Referenced by GetSelectedActionCategory(), SelectFirstActionCategory(), SelectNextAction(), SelectNextActionCategory(), SelectPrevAction(), SelectPrevActionCategory(), SetDefaultInputsOrder(), and UpdateActionCategoryPriority().
m_OrederedAllActionInput
protected ref array<ActionInput> m_OrederedAllActionInput private
Definition at line 14 of file ActionManagerClient.c.
Referenced by FindContextualUserActions(), HandleInputsOnActionStart(), InputsUpdate(), ResetInputsActions(), ResetInputsState(), SetActioninputOrder(), and SetDefaultInputsOrder().
m_PendingActionData
protected ref ActionData m_PendingActionData private
Definition at line 19 of file ActionManagerClient.c.
Referenced by PerformActionStart(), and Update().
m_RegistredInputsMap
protected ref TTypeNameActionInputMap m_RegistredInputsMap private
Definition at line 13 of file ActionManagerClient.c.
Referenced by GetPossibleAction(), GetPossibleActionCount(), GetPossibleActionIndex(), GetPossibleActions(), RegisterInputs(), SetActioninputOrder(), and SetDefaultInputsOrder().
m_ReservedInventoryLocations
protected ref array<ref InventoryLocation> m_ReservedInventoryLocations private
Definition at line 10 of file ActionManagerClient.c.
Referenced by ActionManagerClient().
m_SelectedActionInputToSrollIndex
protected int m_SelectedActionInputToSrollIndex private
Definition at line 17 of file ActionManagerClient.c.
Referenced by ActionManagerClient(), GetSelectedActionCategory(), SelectFirstActionCategory(), SelectNextAction(), SelectNextActionCategory(), SelectPrevAction(), and SelectPrevActionCategory().
m_Targets
private ref ActionTargets m_Targets private
Definition at line 1276 of file ActionManagerClient.c.
Referenced by ActionManagerClient(), FindActionTarget(), and Update().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionManagerClient.c