DayZ Scripts: SoftSkillsManager Class Reference
SoftSkillsManager Class Reference
Private Member Functions
void SoftSkillsManager (PlayerBase player)
void InitSpecialty (float specialty_level)
void ~SoftSkillsManager ()
float AddLinearPrecise (float specialty_weight)
float AddLinearRough (float specialty_weight)
float AddExponentialPrecise (float specialty_weight)
float AddExponentialRough (float specialty_weight)
void AddSpecialty (float specialty_weight)
float AddSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent=false, float limit_efficiency=2)
float SubtractSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent=false, float limit_efficiency=2)
float AdjustCraftingTime (float base_time, float specialty_weight, float limit_efficiency=2)
PlayerBase GetSoftSkillsPlayer ()
void SetSpecialtyLevel (float specialty_level)
float GetSpecialtyLevel ()
void SynchSpecialtyLevel ()
void SetSoftSkillsState (bool state)
bool GetSoftSkillsState ()
void SetLinearState (bool model)
bool IsLinear ()
void GetPreciseRoughLevels ()
void StartCoolDownTimer (float cooldown_value)
bool IsCoolDown ()
void SetCoolDown (bool cool_down)
void CreateDebugWindow (bool create)
void SynchDebugStats ()
void SetIsDebug (bool is_debug)
bool IsDebug ()
void SetCoolDownValue (float cooldown_value)
float GetCoolDownValue ()
float GetLastUAValue ()
void SetLastUAValue (float last_ua_value)
void SetBonusBefore (bool is_cacomponent, float base_value)
void SetBonusAfter (bool is_cacomponent, float adjusted_value)
float GetComponentBonusBefore ()
void SetComponentBonusBefore (float component_bonus_before)
float GetComponentBonusAfter ()
void SetComponentBonusAfter (float component_bonus_after)
float GetGeneralBonusBefore ()
void SetGeneralBonusBefore (float general_bonus_before)
float GetGeneralBonusAfter ()
void SetGeneralBonusAfter (float general_bonus_after)
void StartSynchTimer ()
void StopSynchTimer ()
void ResetDebugWindow ()
Private Attributes
protected PlayerBase m_Player
protected float m_SpecialtyLevel
protected float m_RoughLevel
protected float m_PreciseLevel
protected bool m_IsLinear
protected bool m_IsActive
protected bool m_IsCoolDown
protected int m_UserActionsCounter
protected ref Timer m_CoolDownTimer = new Timer()
protected bool m_IsDebugMode
protected float m_CoolDownValue
protected float m_LastUAValue
protected float m_ComponentBonusBefore
protected float m_ComponentBonusAfter
protected float m_GeneralBonusBefore
protected float m_GeneralBonusAfter
protected ref SoftSkillManagerDebug m_DebugWindow
protected ref Timer m_SynchTimer
Static Private Attributes
static protected const int DEFAULT_EFFICIENCY = 0
static protected const float PRECISE_WEIGHT_LIMIT = -1
static protected const float ROUGH_WEIGHT_LIMIT = 1
static protected const float COOLDOWN_TIMER = 5
Constructor & Destructor Documentation
SoftSkillsManager()
void SoftSkillsManager (PlayerBase player) inline private
References m_IsActive, m_IsCoolDown, m_IsDebugMode, m_IsLinear, and m_Player.
~SoftSkillsManager()
void ~SoftSkillsManager () inline private
References m_CoolDownTimer.
Member Function Documentation
AddExponentialPrecise()
float AddExponentialPrecise (float specialty_weight) inline private
References Math::AbsInt(), Math::Clamp(), m_SpecialtyLevel, m_UserActionsCounter, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, SetLastUAValue(), and Math::Sqrt().
Referenced by AddSpecialty().
AddExponentialRough()
float AddExponentialRough (float specialty_weight) inline private
References Math::AbsInt(), Math::Clamp(), m_SpecialtyLevel, m_UserActionsCounter, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, SetLastUAValue(), and Math::Sqrt().
Referenced by AddSpecialty().
AddLinearPrecise()
float AddLinearPrecise (float specialty_weight) inline private
References Math::Clamp(), m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, and SetLastUAValue().
Referenced by AddSpecialty().
AddLinearRough()
float AddLinearRough (float specialty_weight) inline private
References Math::Clamp(), m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, and SetLastUAValue().
Referenced by AddSpecialty().
AddSpecialty()
void AddSpecialty (float specialty_weight) inline private
References Math::AbsFloat(), AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), AddLinearRough(), COOLDOWN_TIMER, GetSoftSkillsState(), IsCoolDown(), IsLinear(), m_Player, m_SpecialtyLevel, SetSpecialtyLevel(), StartCoolDownTimer(), and SynchSpecialtyLevel().
AddSpecialtyBonus()
float AddSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent = false, float limit_efficiency = 2) inline private
References GetPreciseRoughLevels(), m_PreciseLevel, m_RoughLevel, SetBonusAfter(), and SetBonusBefore().
AdjustCraftingTime()
float AdjustCraftingTime (float base_time, float specialty_weight, float limit_efficiency = 2) inline private
References GetPreciseRoughLevels(), m_PreciseLevel, m_RoughLevel, SetBonusAfter(), and SetBonusBefore().
CreateDebugWindow()
void CreateDebugWindow (bool create) inline private
References m_DebugWindow, ResetDebugWindow(), SetIsDebug(), and SoftSkillManagerDebug().
GetComponentBonusAfter()
float GetComponentBonusAfter () inline private
References m_ComponentBonusAfter.
GetComponentBonusBefore()
float GetComponentBonusBefore () inline private
References m_ComponentBonusBefore.
GetCoolDownValue()
float GetCoolDownValue () inline private
References m_CoolDownValue.
GetGeneralBonusAfter()
float GetGeneralBonusAfter () inline private
References m_GeneralBonusAfter.
GetGeneralBonusBefore()
float GetGeneralBonusBefore () inline private
References m_GeneralBonusBefore.
GetLastUAValue()
float GetLastUAValue () inline private
References m_LastUAValue.
GetPreciseRoughLevels()
void GetPreciseRoughLevels () inline private
References Math::AbsFloat(), DEFAULT_EFFICIENCY, m_PreciseLevel, m_RoughLevel, and m_SpecialtyLevel.
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), and SubtractSpecialtyBonus().
GetSoftSkillsPlayer()
PlayerBase GetSoftSkillsPlayer () inline private
References m_Player.
GetSoftSkillsState()
bool GetSoftSkillsState () inline private
References m_IsActive.
Referenced by AddSpecialty().
GetSpecialtyLevel()
float GetSpecialtyLevel () inline private
References m_SpecialtyLevel.
Referenced by OnUpdate().
InitSpecialty()
void InitSpecialty (float specialty_level) inline private
References SetSpecialtyLevel(), and SynchSpecialtyLevel().
IsCoolDown()
bool IsCoolDown () inline private
References m_IsCoolDown.
Referenced by AddSpecialty().
IsDebug()
bool IsDebug () inline private
References m_IsDebugMode.
Referenced by SetBonusAfter(), and SetBonusBefore().
IsLinear()
bool IsLinear () inline private
References m_IsLinear.
Referenced by AddSpecialty().
ResetDebugWindow()
void ResetDebugWindow () inline private
References SetComponentBonusAfter(), SetComponentBonusBefore(), SetCoolDownValue(), SetGeneralBonusAfter(), SetGeneralBonusBefore(), SetLastUAValue(), SetSpecialtyLevel(), and SynchSpecialtyLevel().
Referenced by CreateDebugWindow().
SetBonusAfter()
void SetBonusAfter (bool is_cacomponent, float adjusted_value) inline private
References IsDebug(), SetComponentBonusAfter(), and SetGeneralBonusAfter().
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), and SubtractSpecialtyBonus().
SetBonusBefore()
void SetBonusBefore (bool is_cacomponent, float base_value) inline private
References IsDebug(), SetComponentBonusBefore(), and SetGeneralBonusBefore().
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), and SubtractSpecialtyBonus().
SetComponentBonusAfter()
void SetComponentBonusAfter (float component_bonus_after) inline private
References m_ComponentBonusAfter.
Referenced by ResetDebugWindow(), and SetBonusAfter().
SetComponentBonusBefore()
void SetComponentBonusBefore (float component_bonus_before) inline private
References m_ComponentBonusBefore.
Referenced by ResetDebugWindow(), and SetBonusBefore().
SetCoolDown()
void SetCoolDown (bool cool_down) inline private
References m_IsCoolDown.
Referenced by StartCoolDownTimer().
SetCoolDownValue()
void SetCoolDownValue (float cooldown_value) inline private
References m_CoolDownValue.
Referenced by ResetDebugWindow(), and StartCoolDownTimer().
SetGeneralBonusAfter()
void SetGeneralBonusAfter (float general_bonus_after) inline private
References m_GeneralBonusAfter.
Referenced by ResetDebugWindow(), and SetBonusAfter().
SetGeneralBonusBefore()
void SetGeneralBonusBefore (float general_bonus_before) inline private
References m_GeneralBonusBefore.
Referenced by ResetDebugWindow(), and SetBonusBefore().
SetIsDebug()
void SetIsDebug (bool is_debug) inline private
References m_IsDebugMode.
Referenced by CreateDebugWindow(), StartSynchTimer(), and StopSynchTimer().
SetLastUAValue()
void SetLastUAValue (float last_ua_value) inline private
References m_LastUAValue.
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), AddLinearRough(), and ResetDebugWindow().
SetLinearState()
void SetLinearState (bool model) inline private
References m_IsLinear.
SetSoftSkillsState()
void SetSoftSkillsState (bool state) inline private
References m_IsActive.
SetSpecialtyLevel()
void SetSpecialtyLevel (float specialty_level) inline private
References m_SpecialtyLevel.
Referenced by AddSpecialty(), InitSpecialty(), and ResetDebugWindow().
StartCoolDownTimer()
void StartCoolDownTimer (float cooldown_value) inline private
References m_CoolDownTimer, SetCoolDown(), and SetCoolDownValue().
Referenced by AddSpecialty().
StartSynchTimer()
void StartSynchTimer () inline private
References m_SynchTimer, and SetIsDebug().
StopSynchTimer()
void StopSynchTimer () inline private
References m_SynchTimer, SetIsDebug(), and Timer::Stop().
SubtractSpecialtyBonus()
float SubtractSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent = false, float limit_efficiency = 2) inline private
References GetPreciseRoughLevels(), m_PreciseLevel, m_RoughLevel, SetBonusAfter(), and SetBonusBefore().
SynchDebugStats()
void SynchDebugStats () inline private
References GetGame(), m_CoolDownValue, m_GeneralBonusAfter, m_GeneralBonusBefore, m_IsCoolDown, m_LastUAValue, m_Player, and CGame::RPCSingleParam().
SynchSpecialtyLevel()
void SynchSpecialtyLevel () inline private
References GetGame(), m_Player, m_SpecialtyLevel, and CGame::RPCSingleParam().
Referenced by AddSpecialty(), InitSpecialty(), and ResetDebugWindow().
Field Documentation
COOLDOWN_TIMER
protected const float COOLDOWN_TIMER = 5 static private
Referenced by AddSpecialty().
DEFAULT_EFFICIENCY
protected const int DEFAULT_EFFICIENCY = 0 static private
Referenced by GetPreciseRoughLevels().
m_ComponentBonusAfter
protected float m_ComponentBonusAfter private
Referenced by GetComponentBonusAfter(), and SetComponentBonusAfter().
m_ComponentBonusBefore
protected float m_ComponentBonusBefore private
Referenced by GetComponentBonusBefore(), and SetComponentBonusBefore().
m_CoolDownTimer
protected ref Timer m_CoolDownTimer = new Timer() private
Referenced by StartCoolDownTimer(), and ~SoftSkillsManager().
m_CoolDownValue
protected float m_CoolDownValue private
Referenced by GetCoolDownValue(), SetCoolDownValue(), and SynchDebugStats().
m_DebugWindow
protected ref SoftSkillManagerDebug m_DebugWindow private
Referenced by CreateDebugWindow().
m_GeneralBonusAfter
protected float m_GeneralBonusAfter private
Referenced by GetGeneralBonusAfter(), SetGeneralBonusAfter(), and SynchDebugStats().
m_GeneralBonusBefore
protected float m_GeneralBonusBefore private
Referenced by GetGeneralBonusBefore(), SetGeneralBonusBefore(), and SynchDebugStats().
m_IsActive
protected bool m_IsActive private
Referenced by GetSoftSkillsState(), SetSoftSkillsState(), and SoftSkillsManager().
m_IsCoolDown
protected bool m_IsCoolDown private
Referenced by IsCoolDown(), SetCoolDown(), SoftSkillsManager(), and SynchDebugStats().
m_IsDebugMode
protected bool m_IsDebugMode private
Referenced by IsDebug(), SetIsDebug(), and SoftSkillsManager().
m_IsLinear
protected bool m_IsLinear private
Referenced by IsLinear(), SetLinearState(), and SoftSkillsManager().
m_LastUAValue
protected float m_LastUAValue private
Referenced by GetLastUAValue(), SetLastUAValue(), and SynchDebugStats().
m_Player
protected PlayerBase m_Player private
Referenced by AddSpecialty(), GetSoftSkillsPlayer(), SoftSkillsManager(), SynchDebugStats(), and SynchSpecialtyLevel().
m_PreciseLevel
protected float m_PreciseLevel private
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), GetPreciseRoughLevels(), and SubtractSpecialtyBonus().
m_RoughLevel
protected float m_RoughLevel private
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), GetPreciseRoughLevels(), and SubtractSpecialtyBonus().
m_SpecialtyLevel
protected float m_SpecialtyLevel private
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), AddLinearRough(), AddSpecialty(), GetPreciseRoughLevels(), GetSpecialtyLevel(), SetSpecialtyLevel(), and SynchSpecialtyLevel().
m_SynchTimer
protected ref Timer m_SynchTimer private
Referenced by StartSynchTimer(), and StopSynchTimer().
m_UserActionsCounter
protected int m_UserActionsCounter private
Referenced by AddExponentialPrecise(), and AddExponentialRough().
PRECISE_WEIGHT_LIMIT
protected const float PRECISE_WEIGHT_LIMIT = -1 static private
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), and AddLinearRough().
ROUGH_WEIGHT_LIMIT
protected const float ROUGH_WEIGHT_LIMIT = 1 static private
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), and AddLinearRough().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/SoftSkillsManager.c