DayZ Scripts: VicinityObjects Class Reference
VicinityObjects Class Reference
objects in vicinity - extended with secondary object which is parent of that Object
Private Member Functions
void VicinityObjects ()
void StoreVicinityObject (Object object, Object parent=null)
stores VicinityObject to Hashmap - for storing of parent/child relationship
void TransformToVicinityObjects (array< Object > objects)
transform simple array of Objects to VicinityObjects hashmap
void ClearVicinityObjects ()
array< Object > GetVicinityObjects ()
return simple array of Objects in Vicinity
array< Object > GetRawVicinityObjects ()
return simple array of Objects in Vicinity
Object GetObject (int i)
returns VicinityObjects Key
Object GetParent (int i)
returns VicinityObjects Element
int Count ()
void Remove (Object object)
void Remove (array< Object > objects)
Private Attributes
private ref map< Object, Object > m_VicinityObjects
Detailed Description
objects in vicinity - extended with secondary object which is parent of that Object
Constructor & Destructor Documentation
VicinityObjects()
void VicinityObjects () inline private
References m_VicinityObjects.
Member Function Documentation
ClearVicinityObjects()
void ClearVicinityObjects () inline private
References m_VicinityObjects.
Count()
int Count () inline private
References m_VicinityObjects.
GetObject()
Object GetObject (int i) inline private
returns VicinityObjects Key
References m_VicinityObjects.
GetParent()
Object GetParent (int i) inline private
returns VicinityObjects Element
References m_VicinityObjects.
GetRawVicinityObjects()
array< Object > GetRawVicinityObjects () inline private
return simple array of Objects in Vicinity
References GetObject(), and m_VicinityObjects.
GetVicinityObjects()
array< Object > GetVicinityObjects () inline private
return simple array of Objects in Vicinity
filters out non-takeable items (won't be shown in vicinity)
References GetObject(), ItemBase::IsTakeable(), and m_VicinityObjects.
Remove() [1/2]
void Remove (array< Object > objects) inline private
References m_VicinityObjects.
Remove() [2/2]
void Remove (Object object) inline private
References m_VicinityObjects.
StoreVicinityObject()
void StoreVicinityObject (Object object, Object parent = null) inline private
stores VicinityObject to Hashmap - for storing of parent/child relationship
completely remove items that are being placed or are holograms
ignores plain objects
init of VicinityObjects - object, parent(if exists)
References m_VicinityObjects.
Referenced by TransformToVicinityObjects().
TransformToVicinityObjects()
void TransformToVicinityObjects (array< Object > objects) inline private
transform simple array of Objects to VicinityObjects hashmap
References CanBeActionTarget(), GetType(), and StoreVicinityObject().
Field Documentation
m_VicinityObjects
private ref map<Object, Object> m_VicinityObjects private
Referenced by ClearVicinityObjects(), Count(), GetObject(), GetParent(), GetRawVicinityObjects(), GetVicinityObjects(), Remove(), Remove(), StoreVicinityObject(), and VicinityObjects().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionTargets.c