DayZ Scripts: DayZPlayerImplementFallDamage Class Reference
DayZPlayerImplementFallDamage Class Reference
Private Member Functions
void DayZPlayerImplementFallDamage (DayZPlayer pPlayer)
float DamageCoef (float pHeight)
damage coef calculated from height
void HandleFallDamage (float pHeight)
handle fall damage
Private Attributes
const string FD_AMMO = "FallDamage"
ammo type used for damaging
const float FD_DMG_FROM_HEIGHT = 2.5
damage will not be taken into account bellow this HeightToDamage
const float FD_MAX_DMG_AT_HEIGHT = 15
height where player gets 100% damage
const float FD_MAX_HEIGHT_LEG_BREAK = 8
height where legs break most of the time
DayZPlayer m_Player
Detailed Description
Definition at line 1 of file DayZPlayerImplementFallDamage.c.
Constructor & Destructor Documentation
DayZPlayerImplementFallDamage()
void DayZPlayerImplementFallDamage (DayZPlayer pPlayer) inline private
Definition at line 10 of file DayZPlayerImplementFallDamage.c.
References m_Player.
Member Function Documentation
DamageCoef()
float DamageCoef (float pHeight) inline private
damage coef calculated from height
Definition at line 16 of file DayZPlayerImplementFallDamage.c.
References FD_DMG_FROM_HEIGHT, and FD_MAX_DMG_AT_HEIGHT.
Referenced by HandleFallDamage().
HandleFallDamage()
void HandleFallDamage (float pHeight) inline private
handle fall damage
no dmg height
updates injury state of player immediately
Definition at line 25 of file DayZPlayerImplementFallDamage.c.
References DamageCoef(), Easing::EaseInOutQuart(), FD_AMMO, FD_DMG_FROM_HEIGHT, FD_MAX_HEIGHT_LEG_BREAK, GetGame(), m_Player, and Math::RandomFloatInclusive().
Field Documentation
FD_AMMO
const string FD_AMMO = "FallDamage" private
ammo type used for damaging
Definition at line 3 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
FD_DMG_FROM_HEIGHT
const float FD_DMG_FROM_HEIGHT = 2.5 private
damage will not be taken into account bellow this HeightToDamage
Definition at line 4 of file DayZPlayerImplementFallDamage.c.
Referenced by DayZPlayer::CommandHandler(), DamageCoef(), and HandleFallDamage().
FD_MAX_DMG_AT_HEIGHT
const float FD_MAX_DMG_AT_HEIGHT = 15 private
height where player gets 100% damage
Definition at line 5 of file DayZPlayerImplementFallDamage.c.
Referenced by DamageCoef().
FD_MAX_HEIGHT_LEG_BREAK
const float FD_MAX_HEIGHT_LEG_BREAK = 8 private
height where legs break most of the time
Definition at line 6 of file DayZPlayerImplementFallDamage.c.
Referenced by HandleFallDamage().
m_Player
DayZPlayer m_Player private
Definition at line 8 of file DayZPlayerImplementFallDamage.c.
Referenced by DayZPlayerImplementFallDamage(), and HandleFallDamage().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/DayZPlayerImplementFallDamage.c