DayZ Scripts: ClothingBase Class Reference
ClothingBase Class Reference
Private Member Functions
void ~BurlapSackCover ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override bool CanPutInCargo (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
void OnRemovedFromHead (PlayerBase player)
override bool CanPutAsAttachment (EntityAI parent)
override array< int > GetEffectWidgetTypes ()
override bool CanPutAsAttachment (EntityAI parent)
override bool IsObstructingVoice ()
override int GetVoiceEffect ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override array< int > GetEffectWidgetTypes ()
override bool CanPutAsAttachment (EntityAI parent)
override int GetGlassesEffectID ()
override bool CanPutAsAttachment (EntityAI parent)
Private Attributes
PlayerBase m_Player
Detailed Description
Definition at line 1 of file BurlapSackCover.c.
Constructor & Destructor Documentation
~BurlapSackCover()
void ~BurlapSackCover () inline private
Definition at line 5 of file BurlapSackCover.c.
References m_Player, and OnRemovedFromHead().
Member Function Documentation
CanDetachAttachment()
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 70 of file BurlapSackCover.c.
References Class::CastTo().
CanPutAsAttachment() [1/7]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file DallasMask.c.
References GetNumberOfItems(), and EntityAI::IsMan().
CanPutAsAttachment() [2/7]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 8 of file GreatHelm.c.
CanPutAsAttachment() [3/7]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file GuyFawkesMask.c.
References GetNumberOfItems(), and EntityAI::IsMan().
CanPutAsAttachment() [4/7]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file HoxtonMask.c.
References GetNumberOfItems(), and EntityAI::IsMan().
CanPutAsAttachment() [5/7]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file MilitaryBoots_ColorBase.c.
CanPutAsAttachment() [6/7]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 8 of file WeldingMask.c.
CanPutAsAttachment() [7/7]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file WolfMask.c.
References GetNumberOfItems(), and EntityAI::IsMan().
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 60 of file BurlapSackCover.c.
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 13 of file BurlapSackCover.c.
References GetGame(), and m_Player.
GetEffectWidgetTypes() [1/2]
override array< int > GetEffectWidgetTypes () inline private
Definition at line 3 of file GreatHelm.c.
GetEffectWidgetTypes() [2/2]
override array< int > GetEffectWidgetTypes () inline private
Definition at line 3 of file WeldingMask.c.
GetGlassesEffectID()
override int GetGlassesEffectID () inline private
Definition at line 27 of file WeldingMask.c.
GetVoiceEffect()
override int GetVoiceEffect () inline private
Definition at line 32 of file GreatHelm.c.
IsObstructingVoice()
override bool IsObstructingVoice () inline private
Definition at line 27 of file GreatHelm.c.
OnRemovedFromHead()
void OnRemovedFromHead (PlayerBase player) inline private
Definition at line 77 of file BurlapSackCover.c.
Referenced by ~BurlapSackCover().
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 26 of file BurlapSackCover.c.
References Class::CastTo(), GetGame(), CGame::GetMission(), Mission::HideInventory(), m_Player, and MENU_INVENTORY.
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 48 of file BurlapSackCover.c.
References Class::CastTo(), and GetGame().
Field Documentation
m_Player
PlayerBase m_Player private
Definition at line 3 of file BurlapSackCover.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/Clothing/BurlapSackCover.c
P:/scripts/4_World/Entities/ItemBase/Clothing/DallasMask.c
P:/scripts/4_World/Entities/ItemBase/Clothing/GreatHelm.c
P:/scripts/4_World/Entities/ItemBase/Clothing/GuyFawkesMask.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HoxtonMask.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MilitaryBoots_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/WeldingMask.c
P:/scripts/4_World/Entities/ItemBase/Clothing/WolfMask.c