DayZ Scripts: BotStateBase Class Reference
BotStateBase Class Reference
represent weapon state base
Private Member Functions
void BotHunt (Bot bot=NULL, BotStateBase parent=NULL)
void SelectTarget ()
override void OnEntry (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
override void OnEntry (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
override void OnEntry (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
void BotTestAttachAndDropCycle (Bot bot=NULL, BotStateBase parent=NULL)
override void OnEntry (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
override void OnEntry (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
override void OnEntry (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
void BotTestItemMoveBackAndForth (Bot bot=NULL, BotStateBase parent=NULL)
override void OnEntry (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
override void OnEntry (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnExit (BotEventBase e)
int GetNextSlot (int curr)
override void OnUpdate (float dt)
void BotSpawnEntityInHands (Bot bot=NULL, BotStateBase parent=NULL, string new_type="")
override void OnEntry (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
override void OnEntry (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
void Bot_TestSpawnOpen (Bot bot=NULL, BotStateBase parent=NULL, string new_type="")
override void OnEntry (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
override void OnEntry (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
void BotTimedWait (Bot bot=NULL, BotStateBase parent=NULL, float timeout=3.0)
override void OnEntry (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
void OnTimeout ()
void BotStateBase (Bot bot=NULL, BotStateBase parent=NULL)
nested state machine (or null)
PlayerBase GetPlayerOwner ()
void SetParentState (BotStateBase parent)
allows construction of hierarchical state machine
BotStateBase GetParentState ()
bool HasFSM ()
BotFSM GetFSM ()
bool ProcessEvent (BotEventBase e)
void AddTransition (FSMTransition< BotStateBase, BotEventBase, BotActionBase, BotGuardBase > t)
adds transition into m_FSM transition table
void OnEntry (BotEventBase e)
void OnUpdate (float dt)
void OnAbort (BotEventBase e)
void OnExit (BotEventBase e)
bool IsWaitingForActionFinish ()
waiting for active animation action/actionType finish
bool IsIdle ()
idle state does not expect any animation events
void OnSubMachineChanged (BotStateBase src, BotStateBase dst)
called when sub-machine has changed its state
void OnStateChanged (BotStateBase src, BotStateBase dst)
called on current state when state machine has changed its state
Private Attributes
Man m_Target
float m_dtAccumulator = 0.0
ref BotHunt_Tracking m_Tracking
ref BotHunt_Hunting m_Hunting
EntityAI m_Target
bool m_TargetInSight = false
bool m_TargetLost = false
bool m_Tracking = true
EntityAI m_Entity
ref BotTestAttachAndDropCycle_Detaching m_Detaching
ref BotTestAttachAndDropCycle_Attaching m_Attaching
ref BotTestItemMoveBackAndForth_MoveFromSlotToSlot m_Move
int m_WaitingForSlot = InventorySlots.INVALID
int m_hgSlot = InventorySlots.GetSlotIdFromString("Headgear")
int m_mskSlot = InventorySlots.GetSlotIdFromString("Mask")
string m_Type
ref BotSpawnEntityInHands m_Spawning
ref BotOpenEntityInHands m_Opening
protected float m_dtAccumulator = 0.0
protected float m_Timeout = 3.0
protected bool m_Periodic = true
PlayerBase m_Owner
Bot m_Bot
man that this state belongs to
BotStateBase m_ParentState
bot that this state belongs to
ref BotFSM m_FSM
hierarchical parent state of this state (or null)
Detailed Description
represent weapon state base
Class comes with entry/update/exit hooks that can be overriden in custom states
Class is ready for hierarchic composition, i.e. this state having a sub-machine running under hood. If no m_FSM member is configured, class acts as ordinary plain finite machine state.
Definition at line 15 of file Bot_Hunt.c.
Constructor & Destructor Documentation
BotStateBase()
void BotStateBase (Bot bot = NULL, BotStateBase parent = NULL) inline private
nested state machine (or null)
Definition at line 17 of file BotStates.c.
References m_Bot, m_Owner, and m_ParentState.
Member Function Documentation
AddTransition()
AddTransition (FSMTransition< BotStateBase, BotEventBase, BotActionBase, BotGuardBase > t) inline private
adds transition into m_FSM transition table
Definition at line 43 of file BotStates.c.
References Error(), HasFSM(), and m_FSM.
Bot_TestSpawnOpen()
void Bot_TestSpawnOpen (Bot bot = NULL, BotStateBase parent = NULL, string new_type = "") inline private
Definition at line 99 of file Bot_TestSpawnAndOpenCan.c.
References m_Type.
BotHunt()
void BotHunt (Bot bot = NULL, BotStateBase parent = NULL) inline private
Definition at line 23 of file Bot_Hunt.c.
BotSpawnEntityInHands()
void BotSpawnEntityInHands (Bot bot = NULL, BotStateBase parent = NULL, string new_type = "") inline private
Definition at line 7 of file Bot_TestSpawnAndOpenCan.c.
References Empty, and m_Type.
BotTestAttachAndDropCycle()
void BotTestAttachAndDropCycle (Bot bot = NULL, BotStateBase parent = NULL) inline private
Definition at line 11 of file Bot_TestAttachAndDropCycle.c.
BotTestItemMoveBackAndForth()
void BotTestItemMoveBackAndForth (Bot bot = NULL, BotStateBase parent = NULL) inline private
Definition at line 6 of file Bot_TestItemMoveBackAndForth.c.
BotTimedWait()
void BotTimedWait (Bot bot = NULL, BotStateBase parent = NULL, float timeout = 3.0) inline private
Definition at line 10 of file Bot_TimedWait.c.
GetFSM()
BotFSM GetFSM () inline private
Definition at line 31 of file BotStates.c.
References m_FSM.
GetNextSlot()
int GetNextSlot (int curr) inline private
Definition at line 79 of file Bot_TestItemMoveBackAndForth.c.
References Error(), InventorySlots::INVALID, m_hgSlot, and m_mskSlot.
Referenced by OnUpdate().
GetParentState()
GetParentState () inline private
Returns
state that owns this sub-state (or null if plain state)
Definition at line 28 of file BotStates.c.
References m_ParentState.
GetPlayerOwner()
PlayerBase GetPlayerOwner () inline private
Definition at line 19 of file BotStates.c.
References m_Owner.
Referenced by OnUpdate(), and SelectTarget().
HasFSM()
bool HasFSM () inline private
Definition at line 30 of file BotStates.c.
References m_FSM.
Referenced by AddTransition(), IsWaitingForActionFinish(), OnAbort(), OnEntry(), OnUpdate(), and ProcessEvent().
IsIdle()
IsIdle () inline private
idle state does not expect any animation events
Returns
true if this state is idle
Definition at line 112 of file BotStates.c.
IsWaitingForActionFinish()
IsWaitingForActionFinish () inline private
waiting for active animation action/actionType finish
Returns
true if this state or active substate is waiting for finish signal
Definition at line 106 of file BotStates.c.
References HasFSM(), and m_FSM.
OnAbort() [1/8]
override void OnAbort (BotEventBase e) inline private
Definition at line 105 of file Bot_Hunt.c.
OnAbort() [2/8]
override void OnAbort (BotEventBase e) inline private
Definition at line 183 of file Bot_Hunt.c.
OnAbort() [3/8]
override void OnAbort (BotEventBase e) inline private
Definition at line 61 of file Bot_TestAttachAndDropCycle.c.
OnAbort() [4/8]
override void OnAbort (BotEventBase e) inline private
Definition at line 97 of file Bot_TestAttachAndDropCycle.c.
OnAbort() [5/8]
override void OnAbort (BotEventBase e) inline private
Definition at line 72 of file Bot_TestItemMoveBackAndForth.c.
OnAbort() [6/8]
override void OnAbort (BotEventBase e) inline private
Definition at line 66 of file Bot_TestSpawnAndOpenCan.c.
OnAbort() [7/8]
override void OnAbort (BotEventBase e) inline private
Definition at line 131 of file Bot_TestSpawnAndOpenCan.c.
OnAbort() [8/8]
void OnAbort (BotEventBase e) inline private
Definition at line 83 of file BotStates.c.
References botDebugPrint(), HasFSM(), m_FSM, ToString(), and Type.
OnEntry() [1/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 50 of file Bot_Hunt.c.
References m_dtAccumulator, and SelectTarget().
OnEntry() [2/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 96 of file Bot_Hunt.c.
OnEntry() [3/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 178 of file Bot_Hunt.c.
OnEntry() [4/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 30 of file Bot_TestAttachAndDropCycle.c.
References m_Entity, and m_Entity.
OnEntry() [5/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 56 of file Bot_TestAttachAndDropCycle.c.
OnEntry() [6/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 92 of file Bot_TestAttachAndDropCycle.c.
OnEntry() [7/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 22 of file Bot_TestItemMoveBackAndForth.c.
References Error(), InventoryLocation::GetSlot(), InventorySlots::GetSlotIdFromString(), m_Entity, and m_Entity.
OnEntry() [8/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 67 of file Bot_TestItemMoveBackAndForth.c.
OnEntry() [9/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 15 of file Bot_TestSpawnAndOpenCan.c.
References m_Type.
OnEntry() [10/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 46 of file Bot_TestSpawnAndOpenCan.c.
References botDebugPrint(), m_Entity, and BotEventBase::m_Entity.
OnEntry() [11/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 120 of file Bot_TestSpawnAndOpenCan.c.
OnEntry() [12/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 130 of file Bot_TestSpawnAndOpenCan.c.
OnEntry() [13/14]
override void OnEntry (BotEventBase e) inline private
Definition at line 15 of file Bot_TimedWait.c.
References m_dtAccumulator, and WeaponFire::OnEntry().
OnEntry() [14/14]
void OnEntry (BotEventBase e) inline private
Definition at line 57 of file BotStates.c.
References botDebugPrint(), HasFSM(), m_FSM, ToString(), and Type.
OnExit() [1/14]
override void OnExit (BotEventBase e) inline private
Definition at line 58 of file Bot_Hunt.c.
References m_dtAccumulator, and m_Target.
OnExit() [2/14]
override void OnExit (BotEventBase e) inline private
Definition at line 114 of file Bot_Hunt.c.
OnExit() [3/14]
override void OnExit (BotEventBase e) inline private
Definition at line 185 of file Bot_Hunt.c.
OnExit() [4/14]
override void OnExit (BotEventBase e) inline private
Definition at line 39 of file Bot_TestAttachAndDropCycle.c.
References m_Entity.
OnExit() [5/14]
override void OnExit (BotEventBase e) inline private
Definition at line 63 of file Bot_TestAttachAndDropCycle.c.
OnExit() [6/14]
override void OnExit (BotEventBase e) inline private
Definition at line 99 of file Bot_TestAttachAndDropCycle.c.
OnExit() [7/14]
override void OnExit (BotEventBase e) inline private
Definition at line 47 of file Bot_TestItemMoveBackAndForth.c.
References m_Entity.
OnExit() [8/14]
override void OnExit (BotEventBase e) inline private
Definition at line 74 of file Bot_TestItemMoveBackAndForth.c.
OnExit() [9/14]
override void OnExit (BotEventBase e) inline private
Definition at line 25 of file Bot_TestSpawnAndOpenCan.c.
OnExit() [10/14]
override void OnExit (BotEventBase e) inline private
Definition at line 68 of file Bot_TestSpawnAndOpenCan.c.
OnExit() [11/14]
override void OnExit (BotEventBase e) inline private
Definition at line 121 of file Bot_TestSpawnAndOpenCan.c.
OnExit() [12/14]
override void OnExit (BotEventBase e) inline private
Definition at line 132 of file Bot_TestSpawnAndOpenCan.c.
OnExit() [13/14]
override void OnExit (BotEventBase e) inline private
Definition at line 22 of file Bot_TimedWait.c.
References m_dtAccumulator.
OnExit() [14/14]
void OnExit (BotEventBase e) inline private
Definition at line 97 of file BotStates.c.
References botDebugPrint(), ToString(), and Type.
OnStateChanged()
OnStateChanged (BotStateBase src, BotStateBase dst) inline private
called on current state when state machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
Definition at line 126 of file BotStates.c.
OnSubMachineChanged()
OnSubMachineChanged (BotStateBase src, BotStateBase dst) inline private
called when sub-machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
Definition at line 119 of file BotStates.c.
OnTimeout()
void OnTimeout () inline private
Definition at line 47 of file Bot_TimedWait.c.
References botDebugSpam().
Referenced by OnUpdate().
OnUpdate() [1/14]
override void OnUpdate (float dt) inline private
Definition at line 66 of file Bot_Hunt.c.
References m_dtAccumulator, m_dtAccumulator, m_Target, Print(), and SelectTarget().
OnUpdate() [2/14]
override void OnUpdate (float dt) inline private
Definition at line 123 of file Bot_Hunt.c.
References botDebugPrint(), vector::Distance(), GetPlayerOwner(), GetPosition, and m_Target.
OnUpdate() [3/14]
override void OnUpdate (float dt) inline private
Definition at line 190 of file Bot_Hunt.c.
OnUpdate() [4/14]
override void OnUpdate (float dt) inline private
Definition at line 46 of file Bot_TestAttachAndDropCycle.c.
OnUpdate() [5/14]
override void OnUpdate (float dt) inline private
Definition at line 68 of file Bot_TestAttachAndDropCycle.c.
References botDebugPrint(), InventoryLocation::GetType(), and m_Entity.
OnUpdate() [6/14]
override void OnUpdate (float dt) inline private
Definition at line 104 of file Bot_TestAttachAndDropCycle.c.
References botDebugPrint(), InventoryLocation::GetType(), and m_Entity.
OnUpdate() [7/14]
override void OnUpdate (float dt) inline private
Definition at line 54 of file Bot_TestItemMoveBackAndForth.c.
OnUpdate() [8/14]
override void OnUpdate (float dt) inline private
Definition at line 89 of file Bot_TestItemMoveBackAndForth.c.
References botDebugPrint(), GetNextSlot(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), and m_Entity.
OnUpdate() [9/14]
override void OnUpdate (float dt) inline private
Definition at line 27 of file Bot_TestSpawnAndOpenCan.c.
References botDebugPrint(), HumanInventory::GetEntityInHands(), and EntityAI::GetHumanInventory().
OnUpdate() [10/14]
override void OnUpdate (float dt) inline private
Definition at line 73 of file Bot_TestSpawnAndOpenCan.c.
References botDebugPrint(), botDebugSpam(), HumanInventory::GetEntityInHands(), EntityAI::GetHumanInventory(), and string::IndexOf().
OnUpdate() [11/14]
override void OnUpdate (float dt) inline private
Definition at line 122 of file Bot_TestSpawnAndOpenCan.c.
OnUpdate() [12/14]
override void OnUpdate (float dt) inline private
Definition at line 134 of file Bot_TestSpawnAndOpenCan.c.
References botDebugPrint(), botDebugSpam(), HumanInventory::GetEntityInHands(), and EntityAI::GetHumanInventory().
OnUpdate() [13/14]
override void OnUpdate (float dt) inline private
Definition at line 29 of file Bot_TimedWait.c.
References m_dtAccumulator, m_Timeout, and OnTimeout().
OnUpdate() [14/14]
void OnUpdate (float dt) inline private
Definition at line 73 of file BotStates.c.
References HasFSM(), and m_FSM.
ProcessEvent()
bool ProcessEvent (BotEventBase e) inline private
Definition at line 33 of file BotStates.c.
References HasFSM(), and m_FSM.
SelectTarget()
void SelectTarget () inline private
Definition at line 42 of file Bot_Hunt.c.
References botDebugPrint(), BotSelectNearestTarget(), GetPlayerOwner(), m_Target, and m_Target.
Referenced by OnEntry(), and OnUpdate().
SetParentState()
SetParentState (BotStateBase parent) inline private
allows construction of hierarchical state machine
Definition at line 24 of file BotStates.c.
References m_ParentState.
Field Documentation
m_Attaching
ref BotTestAttachAndDropCycle_Attaching m_Attaching private
Definition at line 9 of file Bot_TestAttachAndDropCycle.c.
m_Bot
Bot m_Bot private
man that this state belongs to
Definition at line 13 of file BotStates.c.
Referenced by BotStateBase(), BotStateIdle::BotStateIdle(), and BotTestSpamUserActions::BotTestSpamUserActions().
m_Detaching
ref BotTestAttachAndDropCycle_Detaching m_Detaching private
Definition at line 8 of file Bot_TestAttachAndDropCycle.c.
m_dtAccumulator [1/2]
float m_dtAccumulator = 0.0 private
Definition at line 18 of file Bot_Hunt.c.
Referenced by OnUpdate().
m_dtAccumulator [2/2]
protected float m_dtAccumulator = 0.0 private
Definition at line 6 of file Bot_TimedWait.c.
m_Entity
EntityAI m_Entity private
Definition at line 7 of file Bot_TestAttachAndDropCycle.c.
Referenced by OnEntry().
m_FSM
ref BotFSM m_FSM private
hierarchical parent state of this state (or null)
Definition at line 15 of file BotStates.c.
Referenced by AddTransition(), BotTestSpamUserActions::BotTestSpamUserActions(), GetFSM(), HasFSM(), IsWaitingForActionFinish(), OnAbort(), OnEntry(), OnUpdate(), and ProcessEvent().
m_hgSlot
int m_hgSlot = InventorySlots.GetSlotIdFromString("Headgear") private
Definition at line 64 of file Bot_TestItemMoveBackAndForth.c.
Referenced by GetNextSlot().
m_Hunting
ref BotHunt_Hunting m_Hunting private
Definition at line 21 of file Bot_Hunt.c.
m_Move
ref BotTestItemMoveBackAndForth_MoveFromSlotToSlot m_Move private
Definition at line 4 of file Bot_TestItemMoveBackAndForth.c.
m_mskSlot
int m_mskSlot = InventorySlots.GetSlotIdFromString("Mask") private
Definition at line 65 of file Bot_TestItemMoveBackAndForth.c.
Referenced by GetNextSlot().
m_Opening
ref BotOpenEntityInHands m_Opening private
Definition at line 97 of file Bot_TestSpawnAndOpenCan.c.
m_Owner
PlayerBase m_Owner private
Definition at line 12 of file BotStates.c.
Referenced by BotStateBase(), BotStateIdle::BotStateIdle(), GetPlayerOwner(), BotTestSwapInternal::OnEntry(), BotTestSwapInternalC2H::OnEntry(), BotTestSwapG2H::OnEntry(), BotTestSpamUserActions::OnEntry(), BotTestSwapInternal::OnUpdate(), and BotTestSwapInternalC2H::OnUpdate().
m_ParentState
BotStateBase m_ParentState private
bot that this state belongs to
Definition at line 14 of file BotStates.c.
Referenced by BotStateBase(), BotStateIdle::BotStateIdle(), GetParentState(), and SetParentState().
m_Periodic
protected bool m_Periodic = true private
Definition at line 8 of file Bot_TimedWait.c.
m_Spawning
ref BotSpawnEntityInHands m_Spawning private
Definition at line 96 of file Bot_TestSpawnAndOpenCan.c.
m_Target [1/2]
EntityAI m_Target private
Definition at line 17 of file Bot_Hunt.c.
Referenced by SelectTarget().
m_Target [2/2]
EntityAI m_Target private
Definition at line 91 of file Bot_Hunt.c.
m_TargetInSight
bool m_TargetInSight = false private
Definition at line 92 of file Bot_Hunt.c.
m_TargetLost
bool m_TargetLost = false private
Definition at line 93 of file Bot_Hunt.c.
m_Timeout
protected float m_Timeout = 3.0 private
Definition at line 7 of file Bot_TimedWait.c.
Referenced by OnUpdate().
m_Tracking [1/2]
ref BotHunt_Tracking m_Tracking private
Definition at line 20 of file Bot_Hunt.c.
m_Tracking [2/2]
bool m_Tracking = true private
Definition at line 94 of file Bot_Hunt.c.
m_Type
string m_Type private
Definition at line 5 of file Bot_TestSpawnAndOpenCan.c.
m_WaitingForSlot
int m_WaitingForSlot = InventorySlots.INVALID private
Definition at line 63 of file Bot_TestItemMoveBackAndForth.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Systems/Bot/Bot_Hunt.c
P:/scripts/4_World/Systems/Bot/Bot_TestAttachAndDropCycle.c
P:/scripts/4_World/Systems/Bot/Bot_TestItemMoveBackAndForth.c
P:/scripts/4_World/Systems/Bot/Bot_TestSpawnAndOpenCan.c
P:/scripts/4_World/Systems/Bot/Bot_TimedWait.c
P:/scripts/4_World/Systems/Bot/BotStates.c