DayZ Scripts: OpenableBehaviour Class Reference
OpenableBehaviour Class Reference
Private Member Functions
void OpenableBehaviour (bool bState=true)
void Open ()
void Close ()
bool IsOpened ()
protected void SetState (bool bState)
protected bool GetState ()
Private Attributes
protected bool m_IsOpened
Constructor & Destructor Documentation
OpenableBehaviour()
void OpenableBehaviour (bool bState = true) inline private
initial value
References m_IsOpened.
Member Function Documentation
Close()
void Close () inline private
References SetState().
Referenced by Barrel_ColorBase::Close(), Compass::Close(), TelescopicBaton::Close(), and Barrel_ColorBase::CloseLoad().
GetState()
protected bool GetState () inline private
References m_IsOpened.
Referenced by IsOpened().
IsOpened()
bool IsOpened () inline private
References GetState().
Referenced by Barrel_ColorBase::IsOpen(), Compass::IsOpen(), TelescopicBaton::IsOpen(), and Barrel_ColorBase::OnStoreSave().
Open()
void Open () inline private
References SetState().
Referenced by Barrel_ColorBase::Open(), Compass::Open(), TelescopicBaton::Open(), and Barrel_ColorBase::OpenLoad().
SetState()
protected void SetState (bool bState) inline private
References m_IsOpened.
Referenced by Close(), and Open().
Field Documentation
m_IsOpened
protected bool m_IsOpened private
Referenced by GetState(), OpenableBehaviour(), and SetState().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/OpenableBehaviour.c