DayZ Scripts: P:/scripts/4_World/Classes/SoundEvents/PlayerSoundEvents/Events/MiscEvents.c File Reference
MiscEvents.c File Reference
Data Structures
class PlayerSoundEventBase
class ForceConsumeSoundEvent
Functions
class PickupHeavySoundEvent extends PlayerSoundEventBase ThirstSoundEvent ()
void PickupHeavySoundEvent ()
class ForceConsumeSoundEvent extends PlayerSoundEventBase ForceFeedSoundEvent ()
void ForceConsumeSoundEvent ()
Function Documentation
ForceConsumeSoundEvent()
void ForceConsumeSoundEvent ()
References m_ID, and m_SoundVoiceAnimEventClassID.
ForceFeedSoundEvent()
class ForceConsumeSoundEvent extends PlayerSoundEventBase ForceFeedSoundEvent ()
Referenced by PlayerSoundEventHandler().
PickupHeavySoundEvent()
void PickupHeavySoundEvent ()
References m_HasPriorityOverTypes, m_ID, m_SoundVoiceAnimEventClassID, and m_Type.
Referenced by PlayerSoundEventHandler().
ThirstSoundEvent()
class PickupHeavySoundEvent extends PlayerSoundEventBase ThirstSoundEvent ()
Referenced by PlayerSoundEventHandler().