DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionDropItem.c File Reference
ActionDropItem.c File Reference
Data Structures
class ActionDropItemCB
Functions
void ActionDropItem ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProneException ()
override bool CanBeUsedThrowing ()
override bool HasTarget ()
override bool ActionConditionContinue (ActionData action_data)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
void PhysicalDropItem (ActionData action_data)
Variables
ActionDropItemCB m_ItemName = ""
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 53 of file ActionDropItem.c.
References HumanCommandMove::IsChangingStance().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data)
Definition at line 48 of file ActionDropItem.c.
ActionDropItem()
void ActionDropItem ()
Definition at line 14 of file ActionDropItem.c.
References m_Text.
Referenced by ActionConstructor::RegisterActions(), and InventoryItem::SetActions().
CanBeUsedThrowing()
override bool CanBeUsedThrowing ()
Definition at line 38 of file ActionDropItem.c.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 22 of file ActionDropItem.c.
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType ()
Definition at line 28 of file ActionDropItem.c.
HasProneException()
override bool HasProneException ()
Definition at line 33 of file ActionDropItem.c.
HasTarget()
override bool HasTarget ()
Definition at line 43 of file ActionDropItem.c.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data)
Definition at line 71 of file ActionDropItem.c.
References PhysicalDropItem().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
Definition at line 65 of file ActionDropItem.c.
References GetGame(), and PhysicalDropItem().
PhysicalDropItem()
void PhysicalDropItem (ActionData action_data)
Definition at line 78 of file ActionDropItem.c.
References ActionData::m_Player.
Referenced by OnExecuteClient(), and OnExecuteServer().
Variable Documentation
m_ItemName
ActionDropItemCB m_ItemName = ""