DayZ Scripts: Achievements Class Reference
Achievements Class Reference
Private Member Functions
private void Achievements ()
private void ~Achievements ()
Static Private Member Functions
static proto EAchievementError SendEventAction (EAchievementActionId action_id)
static proto EAchievementError SendEventKill (EAchievementTargetId target_id, EAchievementRankId rank_id, EAchievementRangeId range_id, EAchievementHitId hit_id, float distance)
static void OnActionEat ()
static void OnActionDrink ()
static void OnEquippedFullGear ()
static void OnCookedSteak ()
static void OnActionIgniteMatchbox ()
static void OnActionIgniteRoadflare ()
static void OnActionIgniteDrill ()
static void OnActionShave ()
static void OnActionGutDeer ()
static void OnActionMedsSurvivor ()
static void OnActionHandcuff ()
static void OnPlayerKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot)
static private void CheckError (EAchievementError error)
Detailed Description
Definition at line 51 of file AchievementsXbox.c.
Constructor & Destructor Documentation
Achievements()
private void Achievements () private
~Achievements()
private void ~Achievements () private
Member Function Documentation
CheckError()
static private void CheckError (EAchievementError error) inline static private
Definition at line 193 of file AchievementsXbox.c.
References Print().
Referenced by OnActionDrink(), OnActionEat(), OnActionGutDeer(), OnActionHandcuff(), OnActionIgniteDrill(), OnActionIgniteMatchbox(), OnActionIgniteRoadflare(), OnActionMedsSurvivor(), OnActionShave(), OnCookedSteak(), OnEquippedFullGear(), and OnPlayerKilled().
OnActionDrink()
static void OnActionDrink () inline static private
Definition at line 70 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionDrink().
OnActionEat()
static void OnActionEat () inline static private
Definition at line 62 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionEat().
OnActionGutDeer()
static void OnActionGutDeer () inline static private
Definition at line 126 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionFinishedGutDeer().
OnActionHandcuff()
static void OnActionHandcuff () inline static private
Definition at line 142 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionRestrain().
OnActionIgniteDrill()
static void OnActionIgniteDrill () inline static private
Definition at line 110 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::Event_OnPlayerIgnitedFireplace().
OnActionIgniteMatchbox()
static void OnActionIgniteMatchbox () inline static private
Definition at line 94 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::Event_OnPlayerIgnitedFireplace().
OnActionIgniteRoadflare()
static void OnActionIgniteRoadflare () inline static private
Definition at line 102 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::Event_OnPlayerIgnitedFireplace().
OnActionMedsSurvivor()
static void OnActionMedsSurvivor () inline static private
Definition at line 134 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionBandageTarget().
OnActionShave()
static void OnActionShave () inline static private
Definition at line 118 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionFinishedShaveSelf().
OnCookedSteak()
static void OnCookedSteak () inline static private
Definition at line 86 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionCookedSteak().
OnEquippedFullGear()
static void OnEquippedFullGear () inline static private
Definition at line 78 of file AchievementsXbox.c.
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnItemAttachedAtPlayer().
OnPlayerKilled()
static void OnPlayerKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot) inline static private
Definition at line 150 of file AchievementsXbox.c.
References CheckError(), vector::Distance(), EntityAI::IsMeleeWeapon(), and SendEventKill().
Referenced by AnalyticsManagerClient::Event_OnEntityKilled().
SendEventAction()
static proto EAchievementError SendEventAction (EAchievementActionId action_id) static private
Referenced by OnActionDrink(), OnActionEat(), OnActionGutDeer(), OnActionHandcuff(), OnActionIgniteDrill(), OnActionIgniteMatchbox(), OnActionIgniteRoadflare(), OnActionMedsSurvivor(), OnActionShave(), OnCookedSteak(), and OnEquippedFullGear().
SendEventKill()
static proto EAchievementError SendEventKill (EAchievementTargetId target_id, EAchievementRankId rank_id, EAchievementRangeId range_id, EAchievementHitId hit_id, float distance) static private
Referenced by OnPlayerKilled().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Services/AchievementsXbox.c