DayZ Scripts: Strings
Strings
Data Structures
class string
Functions
proto native int ToInt ()
Converts string to integer.
proto native int HexToInt ()
Converts string to integer.
proto native float ToFloat ()
Converts string to float.
proto vector ToVector ()
Returns a vector from a string.
vector BeautifiedToVector ()
Convert beautified string into a vector.
proto native int ToAscii ()
Converts string's first character to ASCII code.
proto native ToType ()
Returns internal type representation. Can be used in runtime, or cached in variables and used for faster inheritance checking.
static proto string ToString (void var, bool type=false, bool name=false, bool quotes=true)
Return string representation of variable.
proto string Substring (int start, int len)
Substring of 'str' from 'start' position 'len' number of characters.
string SubstringInverted (string string_to_split, int position_start, int position_end)
Inverted SubString. This deletes everything in between position_start and position_end.
proto string SubstringUtf8 (int startChar, int len)
Substring of 'str' from 'startChar' position 'len' number of characters for UTF8 strings with multibyte chars.
proto int Replace (string sample, string replace)
Replace all occurrances of 'sample' in 'str' by 'replace'.
proto int ToLower ()
Changes string to lowercase. Returns length.
proto int ToUpper ()
Changes string to uppercase. Returns length.
proto native int Length ()
Returns length of string.
proto native int LengthUtf8 ()
Returns number of characters in UTF8 string.
proto native int Hash ()
Returns hash of string.
proto native int IndexOf (string sample)
Finds 'sample' in 'str'. Returns -1 when not found.
proto native int LastIndexOf (string sample)
Finds last 'sample' in 'str'. Returns -1 when not found.
proto native int IndexOfFrom (int start, string sample)
Finds 'sample' in 'str' from 'start' position. Returns -1 when not found.
bool Contains (string sample)
Returns true if sample is substring of string.
proto string Trim ()
Returns trimmed string with removed leading and trailing whitespaces.
proto int TrimInPlace ()
Removes leading and trailing whitespaces in string. Returns length.
proto int ParseStringEx (out string token)
Parses one token from input string. Result is put into token string, and type of token is returned. Input string is left-truncated by the resulting token length.
proto int ParseString (out string tokens[])
Parses string into array of tokens returns number of tokens.
void Split (string sample, out array< string > output)
Splits string into array of strings separated by 'sample'.
proto string Get (int index)
Gets n-th character from string.
proto void Set (int index, string input)
Sets the n-th character in string with the input, replacing previous value.
proto void Insert (int index, string input)
Inserts a string into the n-th index, increasing the string length by the size of the input.
static proto string Format (string fmt, void param1=NULL, void param2=NULL, void param3=NULL, void param4=NULL, void param5=NULL, void param6=NULL, void param7=NULL, void param8=NULL, void param9=NULL)
Gets n-th character from string.
Variables
static const string Empty
Detailed Description
Function Documentation
BeautifiedToVector()
vector BeautifiedToVector () inline private
Convert beautified string into a vector.
Parameters
vec beautified string
Returns
vector resulting vector
References string::Replace(), and string::ToVector().
Referenced by UIScriptedMenu::OnClick(), and ScriptConsoleGeneralTab::OnClick().
Contains()
bool Contains (string sample) inline private
Returns true if sample is substring of string.
Parameters
sample string Finding string expression
Returns
bool true if sample is substring of string
string str = "Hello World";
Print(str.IndexOfFrom(3, "Hello"));
Print(str.IndexOfFrom(3, "Mexico"));
>> true
>> false
Referenced by ActionCreateIndoorFireplace::ActionCondition(), ActionCreateIndoorOven::ActionCondition(), ActionPlaceFireplaceIndoor::ActionCondition(), ActionPlaceOvenIndoor::ActionCondition(), BaseBuildingBase::CanDisplayAttachmentCategory(), CarScript::CanDisplayAttachmentCategory(), BaseBuildingBase::CanDisplayAttachmentSlot(), ScriptConsoleItemsTab::ChangeFilter(), ScriptConsoleSoundsTab::ChangeFilter(), BaseBuildingBase::CheckLevelVerticalDistance(), BaseBuildingBase::CheckSlotVerticalDistance(), AttachmentsOutOfReach::CreateAttachmentPosition(), CreateMission(), DisplayActions(), DropNonUsableMaterialsServer(), ItemBase::EEHealthLevelChanged(), ItemBase::EEItemLocationChanged(), UIPopupScript::FindInHierarchy(), ScriptConsoleConfigTab::FindInHierarchy(), CheckLocalisationPlugin::FindTexts(), ItemBase::FullyBuild(), GetClosestCarWheel(), Debug::GetFiltredConfigClasses(), UIScriptedMenu::GetFiltredConfigClasses(), UIScriptedMenu::GetFiltredSceneObjects(), SpookyEventBase::GetMatchingSurfacePos(), ActionTargetsCursor::GetOnScreenPosition(), GUIAction_SetValue(), IsEntityOnWaterSurface(), DayZPlayer::OnStepEvent(), PluginFileHandler::ParseToValueBool(), ScriptConsoleConfigTab::RenderVariables(), PluginBase::SpawnFromClipboard(), ObjectSpawnerHandler::SpawnObject(), ItemBase::ToggleAnimation(), and ObjectSpawnerHandler::ValidatePath().
Format()
static proto string Format (string fmt, void param1 = NULL, void param2 = NULL, void param3 = NULL, void param4 = NULL, void param5 = NULL, void param6 = NULL, void param7 = NULL, void param8 = NULL, void param9 = NULL) static private
Gets n-th character from string.
Parameters
index character index
Returns
string character on index-th position in string
int a = 5;
float b = 5.99;
string c = "beta";
string  test = string.Format("Ahoj %1 = %3 , %2", a, b, c);
Print(test);
>> 'Ahoj 5 = 'beta' , 5.99'
Referenced by Add(), Category(), CheckContactCache(), EffectAreaLoader::CreateZones(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), FullTimeData::FormatedNonZero(), FullTimeData::FormatedWithZero(), ActionDigInStash::GetAdminLogMessage(), GetAdminLogMessage(), ActionMountBarbedWire::GetAdminLogMessage(), ActionUnmountBarbedWire::GetAdminLogMessage(), ErrorProperties::GetClientMessage(), GetColorString(), GetComponentNamesFromDamageZone(), GetDamageZoneMap(), UndergroundAreaLoader::GetData(), EffectParticle::GetDebugName(), EffectSound::GetDebugName(), ConstructionActionData::GetDialNumberText(), QuantityConversions::GetItemQuantityText(), TentBase::GetMaterialPath(), ParticleList::GetParticleFullPath(), InputUtils::GetRichtextButtonIconFromInputAction(), ErrorProperties::GetServerMessage(), ErrorHandlerModule::GetSimpleMessage(), array::GetTestEx(), GPSReceiver::GPSReceiver(), HandleError(), Weapon_Base::HideBullet(), LandMineTrap(), ScriptConsoleItemsTab::ListItemRelatedActions(), CfgGameplayHandler::LoadData(), Debug::LogMessage(), Weapon_Base::OnFire(), Play(), Hologram::RefreshVisual(), ParticleList::RegisterParticle(), TFModule::Result(), ActionTargetsCursor::SetItemDesc(), LoginScreenBase::SetTime(), UIScriptedMenu::SetTime(), ScriptedWidgetEventHandler::SetWeaponModeAndZeroing(), ScriptedWidgetEventHandler::SetWeaponQuantity(), Weapon_Base::ShowBullet(), Tag(), TripwireTrap(), and UIScriptedMenu::UpdateControlsElements().
Get()
proto string Get (int index) private
Gets n-th character from string.
Parameters
index character index
Returns
string character on index-th position in string
Warning
VME When index less than 0 or greater than string length
string str = "Hello World";
Print(str[4]); // Print(str.Get(4));
>> 'o'
Referenced by UIPopupScript::ClearHierarchy(), ItemBase::ConvertAttSlotToPlantSlot(), DialNextNumber(), UIPopupScript::ExpandHierarchy(), UIPopupScript::FindInHierarchy(), FireworksLauncherClientEvent::FireworksLauncherClientEvent(), PluginFileHandler::GetAllSubParametersInArrayString(), PluginBase::GetBaseClassPath(), PluginBase::GetBaseClassPathRecursive(), PluginBase::GetConfig(), ConstructionActionData::GetDialNumberText(), PluginFileHandler::GetLastLine(), CGame::GetModelName(), PluginBase::GetName(), PluginBase::GetNameByID(), OptionSelectorBase::GetStringValue(), ScriptedWidgetEventHandler::GetValueString(), ScriptedWidgetEventHandler::Highlight(), PluginFileHandler::LoadParameter(), LoadPlayerAttachmentIndexes(), PluginFileHandler::LoadSubParameter(), Debug::LogArrayInt(), Debug::LogArrayString(), OrderedAltitudeNumbersPosition(), OrderedPositionNumbersFromGridCoords(), PluginBase::PlayerKilled(), ScriptedWidgetEventHandler::Select(), ShuffleLock(), UIScriptedMenu::UpdateDisconnectTexts(), ItemBase::UpdatePhysics(), HudDebugWinBase::UpdateValues(), and ItemBase::UpdateVisuals().
Hash()
proto native int Hash () private
Returns hash of string.
Returns
int - Hash of string
string str = "Hello World";
int hash = str.Hash();
Print(hash);
Referenced by ArrowManagerPlayer::AddArrowTypeToHash(), Capture(), DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), GetActionTable(), GetBuilder(), GetDamageDisplayName(), GetImpactTable(), GetInstance(), SoundLookupTable::LoadTable(), DayZPlayer::OnStepEvent(), EntityAI::ProcessImpactSoundEx(), DayZPlayer::ProcessVoiceEvent(), RegisterItem(), CrashSoundSets::RegisterSoundSet(), RegisterSoundSetMap(), and ArrowManagerPlayer::Save().
HexToInt()
proto native int HexToInt () private
Converts string to integer.
Returns
int - Converted string.
string str = "0xFF";
int i = str.HexToInt();
Print(i);
>> i = 255
Referenced by CfgGameplayHandler::GetHitIndicationIndicatorColor().
IndexOf()
proto native int IndexOf (string sample) private
Finds 'sample' in 'str'. Returns -1 when not found.
Parameters
sample string Finding string
Returns
int - Returns position where sample starts, or -1 when sample not found
string str = "Hello World";
Print(str.IndexOf("H"));
Print(str.IndexOf("W"));
Print(str.IndexOf("Q"));
>> 0
>> 6
>> -1
Referenced by PluginBase::ContainsFirstClass(), PluginBase::GetConfig(), Chemlight_ColorBase::GetMaterialForDamageState(), PluginBase::GetPlayerPrefix(), PluginConfigHandler::GetSceneList(), ItemBase::GetSlotIndexBySelection(), PluginFileHandler::GetTextType(), ScriptedWidgetEventHandler::GetValueString(), DebugPrint::IsDebugLog(), DebugPrint::IsStackTrace(), UIScriptedMenu::OnClick(), ScriptConsoleConfigTab::OnClick(), BotStateBase::OnUpdate(), PluginFileHandler::ParseParam(), PluginFileHandler::ParseText(), PluginFileHandler::ParseTextToArray(), PluginFileHandler::ParseTextToParameter(), OpenDirPlugin::Run(), DayZTool::RunDayZBat(), DebugPrint::TrimDebugLog(), and DebugPrint::TrimStackTrace().
IndexOfFrom()
proto native int IndexOfFrom (int start, string sample) private
Finds 'sample' in 'str' from 'start' position. Returns -1 when not found.
Parameters
start int Start from position
sample string Finding string expression
Returns
int - Length of string s
string str = "Hello World";
Print(str.IndexOfFrom(3, "H"));
Print(str.IndexOfFrom(3, "W"));
Print(str.IndexOfFrom(3, "Q"));
>> -1
>> 6
>> -1
Referenced by ActionUnmountBarbedWire::ActionCondition(), PluginBase::GetBaseClassPathCombined(), PluginFileHandler::ParseTextToArray(), PluginFileHandler::ParseToValueArray(), OpenDirPlugin::Run(), DayZTool::RunDayZBat(), and CGame::SetMissionPath().
Insert()
proto void Insert (int index, string input) private
Inserts a string into the n-th index, increasing the string length by the size of the input.
Parameters
index index to insert at
input string value to insert with
Warning
VME When index less than 0 or greater than string length
VME When string is empty
string str = "Hello World";
str.Insert(6, "Test ");
Print(str);
>> 'Hello Test World'
Referenced by ActionBuildPart::ActionConditionContinue(), ActionBuildShelter::ActionConditionContinue(), CGame::AddVisitedServer(), ManBase::GetDebugActions(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::GetHierarchyPath(), ScriptedWidgetEventHandler::LoadEntries(), ActionBuildPart::OnFinishProgressServer(), PluginFileHandler::ParseTextToArray(), string::Split(), TrapSpawnBase::Trap_FishNet(), TrapSpawnBase::Trap_RabbitSnare(), and TrapSpawnBase::Trap_SmallFish().
LastIndexOf()
proto native int LastIndexOf (string sample) private
Finds last 'sample' in 'str'. Returns -1 when not found.
Parameters
sample string Finding string
Returns
int - Returns position where sample starts, or -1 when sample not found
string str = "Hello World";
Print(str.IndexOf("l"));
>> 9
Length()
proto native int Length () private
Returns length of string.
Returns
int - Length of string
string str = "Hello World";
int i = str.Length();
Print(i);
>> i = 11
Referenced by ActionMountBarbedWire::ActionCondition(), ActionUnmountBarbedWire::ActionCondition(), ActionEnterLadder::ActionCondition(), ScriptedWidgetEventHandler::AddEx(), JsonObject::AddString(), CanReachSeatFromDoors(), UIScriptedMenu::ConnectLastSession(), ManBase::Consume(), PluginBase::ContainsFirstClass(), AttachmentsOutOfReach::CreateAttachmentPosition(), WrittenNoteData::DepleteWritingImplement(), DialNextNumber(), DropNonUsableMaterialsServer(), FireworksLauncherClientEvent::FireworksLauncherClientEvent(), PluginBase::GetBaseClassPath(), PluginBase::GetConfig(), PluginBase::GetConfigRecursive(), ConstructionActionData::GetDialNumberText(), ScriptedWidgetEventHandler::GetFilterOptionsPC(), FireplaceBase::GetFirePointIndex(), JsonObject::GetJson(), CGame::GetModelName(), GetName(), PluginBase::GetOnlyChildPath(), ItemBase::GetSlotIndexByAttachmentSlot(), ItemBase::GetSlotIndexBySelection(), PluginFileHandler::GetTextType(), ScriptedWidgetEventHandler::GetValueString(), InsertAtPos(), IsComponentInSelection(), IsPingInRange(), PluginFileHandler::IsTextArray(), UIScriptedMenu::OnClick(), ActionCarDoors::OnEnd(), CGame::OnEvent(), DayZPlayer::OnStepEvent(), OrderedAltitudeNumbersPosition(), OrderedPositionNumbersFromGridCoords(), PluginFileHandler::ParseText(), PluginFileHandler::ParseTextToArray(), PluginFileHandler::ParseTextToParameter(), PluginFileHandler::ParseToValueArray(), PluginFileHandler::ParseToValueString(), OpenDirPlugin::Run(), DayZTool::RunDayZBat(), SanitizeString(), Hud::SetCursorIcon(), ActionTargetsCursor::SetItemDesc(), ShuffleLock(), string::SubstringInverted(), ToStringLen(), DebugPrint::TrimDebugLog(), HudDebugWinBase::Update(), and ValueToBar().
LengthUtf8()
proto native int LengthUtf8 () private
Returns number of characters in UTF8 string.
Returns
int - Number of characters in UTF8 string
string str = "こんにちは世界";
int i = str.LengthUtf8();
Print(i);
>> i = 7
Referenced by UIScriptedMenu::Refresh().
ParseString()
proto int ParseString (out string tokens[]) private
Parses string into array of tokens returns number of tokens.
Parameters
[out] tokens array[] Parsed string in array
Returns
int Number of tokens
string token[2];
string str = "Hello World";
int result = str.ParseString(token);
for (int i = 0; i < 2; i++)
{
    Print(token[i]);
}
>> 'Hello'
>> 'World'
ParseStringEx()
proto int ParseStringEx (out string token) private
Parses one token from input string. Result is put into token string, and type of token is returned. Input string is left-truncated by the resulting token length.
Parameters
[out] token string Founded string token
Returns
int Type of token
Token types:
 0 - error, no token
 1 - defined token (special characters etc. . / * )
 2 - quoted string. Quotes are removed -> TODO
 3 - alphabetic string
 4 - number
 5 - end of line -> TODO
string input = "Hello*World";
string token1;
string token2;
int result1 = input.ParseStringEx(token1);
int result2 = input.ParseStringEx(token2);
Print("Token1 = '" + token1 + "' Type = " + result1.ToString()));
Print("Token2 = '" + token2 + "' Type = " + result2.ToString()));
>> 'Toke1 = 'Hello' Type = 3'
>> 'Toke1 = '*' Type = 1'
Replace()
proto int Replace (string sample, string replace) private
Replace all occurrances of 'sample' in 'str' by 'replace'.
Parameters
sample string to search in str
replace string which replace sample in str
Returns
int - number of occurrances of 'sample' in 'str'
string test = "If the length of the C string in source is less than num, only the content up to the terminating null-character is copied.";
Print(test);
int count = test.Replace("the", "*");
Print(count);
Print(test);
>> string test = 'If the length of the C string in source is less than num, only the content up to the terminating null-character is copied.';
>> int count =   4
>> string test = 'If * length of * C string in source is less than num, only * content up to * terminating null-character is copied.'
Referenced by PluginFileHandler::AddNewLine(), Surface::AllowedWaterSurface(), string::BeautifiedToVector(), Icon::Combine(), PluginConfigHandler::DecodeInitScript(), Icon::DoubleClick(), HandsContainer::DoubleClick(), AttachmentCategoriesRow::DoubleClick(), ClosableContainer::DoubleClick(), PlayerContainer::DoubleClick(), VicinitySlotsContainer::DoubleClick(), ZombieContainer::DoubleClick(), Icon::DraggingOver(), DraggingOverCenterPanel(), Icon::DraggingOverCombine(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), AttachmentCategoriesRow::DraggingOverGrid(), ClosableContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), ZombieContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), Icon::DropReceivedFromMain(), PluginConfigHandler::EncodeInitScript(), PluginFileHandler::GetAllLines(), HandsContainer::GetItemPreviewItem(), AttachmentCategoriesRow::GetItemPreviewItem(), ClosableContainer::GetItemPreviewItem(), ClosableContainer::GetItemPreviewWidget(), PlayerContainer::GetItemPreviewWidget(), ClosableContainer::GetItemPreviewWidgetDragOrDrop(), LoadPlayerAttachmentIndexes(), VicinitySlotsContainer::MouseButtonDown(), VicinitySlotsContainer::MouseClick(), HandsContainer::MouseClick2(), OnCenterPanelDropReceived(), ZombieContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinitySlotsContainer::OnDropReceivedFromHeader(), ZombieContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), HandsArea::OnHandsPanelDropReceived(), InventoryGridController::OnItemDraggingOver(), InventoryGridController::OnItemDropReceived(), OnRightPanelDropReceived(), SVNBlamePlugin::Run(), SVNDiffPlugin::Run(), OpenDirPlugin::Run(), SVNShowLogPlugin::Run(), ResavePlugin::RunCommandline(), DayZTool::RunDayZBat(), ScriptConsoleEnfScriptTab::RunEnscript(), ColorManager::SetColor(), ItemManager::SetTemperature(), Icon::Swap(), PlayerContainer::ToggleWidget(), and CfgGameplayHandler::ValidateItems().
Set()
proto void Set (int index, string input) private
Sets the n-th character in string with the input, replacing previous value.
Parameters
index index to be replaced
input single non-terminated character value to replace with
Warning
VME When index less than 0 or greater than string length
(Diag) VME When string is empty or greater than length of 1 (Retail) Calls 'string.Insert' except it replaces only the initial character
string str = "Hello World";
str[4] = "O";
Print(str);
>> 'HellO World'
string str = "Hello World";
str[6] = "Test ";
Print(str);
>> 'Hello Test orld'
Referenced by ItemBase::GardenBase().
Split()
void Split (string sample, out array< string > output) inline private
Splits string into array of strings separated by 'sample'.
Parameters
sample string Strings separator
Returns
TStringArray Array with strings
string example = "The quick brown fox jumps over the lazy dog";
TStringArray strs = new TStringArray;
example.Split(" ", strs);
for (int i = 0; i < strs.Count(); i++)
{
    Print(strs.Get(i));
}
>> 'The'
>> 'quick'
>> 'brown'
>> 'fox'
>> 'jumps'
>> 'over'
>> 'the'
>> 'lazy'
>> 'dog'
References string::Insert(), and string::Substring().
Referenced by JsonObject::AddString(), DisplayActions(), UIPopupScript::FindInHierarchy(), ScriptConsoleConfigTab::FindInHierarchy(), ScriptedWidgetEventHandler::GenerateValidIP(), PluginBase::GetConfig(), CGame::GetLastVisitedServer(), PluginFileHandler::GetParameterString(), PluginFileHandler::GetSubParameterInArrayString(), ServerBrowserTab::GetTimeOfDayEnum(), ServerBrowserTabConsolePages::LoadExtraEntries(), ScriptConsoleConfigTab::OnClick(), OnGUI_AnimEvents(), ParseData(), PluginFileHandler::ParseTextToArray(), PluginFileHandler::ParseToValueArray(), ScriptConsoleWeatherTab::PasteValues(), ScriptConsoleSoundsTab::PrepareFilters(), ScriptConsoleItemsTab::PrepareFilters(), DayZPlayer::ProcessAttachmentEvent(), ScriptConsoleConfigTab::RenderVariables(), ScriptedWidgetEventHandler::SetTime(), and PluginBase::SpawnFromClipboard().
Substring()
proto string Substring (int start, int len) private
Substring of 'str' from 'start' position 'len' number of characters.
Parameters
start Position in str
len Count of characters
Returns
string - Substring of str
string str = "Hello World";
string strSub = str.Substring(2, 5);
Print(strSub);
>> strSub = llo W
Referenced by ActionUnmountBarbedWire::ActionCondition(), ActionEnterLadder::ActionCondition(), TentBase::AnimateCamonetByOpeningSelection(), TentBase::AnimateCamonetToggle(), PluginBase::ContainsFirstClass(), AttachmentsOutOfReach::CreateAttachmentPosition(), PluginBase::GetBaseClassPathCombined(), PluginBase::GetConfig(), PluginBase::GetConfigRecursive(), ScriptedWidgetEventHandler::GetFilterOptionsPC(), FireplaceBase::GetFirePointIndex(), Chemlight_ColorBase::GetMaterialForDamageState(), CGame::GetModelName(), PluginBase::GetOnlyChildPath(), PluginBase::GetPlayerPrefix(), PluginConfigHandler::GetSceneList(), ItemBase::GetSlotIndexByAttachmentSlot(), ItemBase::GetSlotIndexBySelection(), PluginFileHandler::GetTextType(), ScriptedWidgetEventHandler::GetValueString(), TentBase::HandleCamoNetAttachment(), InsertAtPos(), IsPingInRange(), PluginFileHandler::IsTextArray(), UIScriptedMenu::OnClick(), ScriptConsoleConfigTab::OnClick(), PluginFileHandler::ParseText(), PluginFileHandler::ParseTextToArray(), PluginFileHandler::ParseTextToParameter(), PluginFileHandler::ParseToValueArray(), PluginFileHandler::ParseToValueString(), OpenDirPlugin::Run(), DayZTool::RunDayZBat(), SanitizeString(), CGame::SetMissionPath(), string::Split(), string::SubstringInverted(), DebugPrint::TrimDebugLog(), and HudDebugWinBase::Update().
SubstringInverted()
string SubstringInverted (string string_to_split, int position_start, int position_end) inline private
Inverted SubString. This deletes everything in between position_start and position_end.
References string::Length(), and string::Substring().
Referenced by GetName().
SubstringUtf8()
proto string SubstringUtf8 (int startChar, int len) private
Substring of 'str' from 'startChar' position 'len' number of characters for UTF8 strings with multibyte chars.
Parameters
startChar Position in str.
len Count of characters
Returns
string - Substring of str with startChar character and len characters
string str = "こんにちは世界";
string strSub = str.SubstringUtf8(2, 4);
Print(strSub);
>> strSub = にちは世
Referenced by UIScriptedMenu::Refresh().
ToAscii()
proto native int ToAscii () private
Converts string's first character to ASCII code.
Parameters
str String for convert to ASCII code
Returns
ascii code int.
int ascii = "M".ToAscii();
Print(ascii);
>> ascii = 77
ToFloat()
proto native float ToFloat () private
Converts string to float.
Returns
float - Converted string in float.
string str = "56.6";
float f = str.ToFloat();
Print(f);
>> f = 56.6
Referenced by Liquid::GetDigestibility(), Liquid::GetEnergy(), Liquid::GetFlammability(), Liquid::GetFullness(), ScriptedWidgetEventHandler::GetInterpTime(), Liquid::GetNutritionalIndex(), PluginFileHandler::GetParameterFloat(), Liquid::GetToxicity(), Liquid::GetWaterContent(), GUIAction_SetValue(), OnGUI_CommandsEdit(), PluginFileHandler::ParseToValueFloat(), DayZProfilesOptions::RegisterProfileOptionFloat(), and DayZProfilesOptions::ResetOptionsFloat().
ToInt()
proto native int ToInt () private
Converts string to integer.
Returns
int - Converted string.
string str = "56";
int i = str.ToInt();
Print(i);
>> i = 56
Referenced by CGame::ConnectFromCLI(), DialNextNumber(), Liquid::GetAgents(), ItemManager::GetDefaultOpenStateHands(), ScriptedWidgetEventHandler::GetFilterOptionsPC(), FireplaceBase::GetFirePointIndex(), PluginFileHandler::GetParameterBool(), PluginFileHandler::GetParameterInt(), ItemBase::GetSlotIndexByAttachmentSlot(), ItemBase::GetSlotIndexBySelection(), GUIAction_SetValue(), IsPingInRange(), OnGUI_CommandsEdit(), OrderedAltitudeNumbersPosition(), OrderedPositionNumbersFromGridCoords(), PluginFileHandler::ParseToValueInt(), ScriptedWidgetEventHandler::ProcessIntoIPAddress(), DayZProfilesOptions::RegisterProfileOptionInt(), DayZProfilesOptions::ResetOptionsInt(), and ShuffleLock().
ToLower()
proto int ToLower () private
Changes string to lowercase. Returns length.
Returns
int - Length of changed string
string str = "Hello World";
int i = str.ToLower();
Print(str);
Print(i);
>> str = hello world
>> i = 11
Referenced by BleedingSourcesManagerBase::AttemptAddBleedingSourceBySelection(), BaseBuildingBase::CanDisplayAttachmentCategory(), CarScript::CanDisplayAttachmentCategory(), BaseBuildingBase::CanDisplayAttachmentSlot(), ItemBase::CanToggleAnimations(), ScriptConsoleItemsTab::ChangeFilter(), ScriptConsoleSoundsTab::ChangeFilter(), BaseBuildingBase::CheckSlotVerticalDistance(), AttachmentsOutOfReach::CreateAttachmentPosition(), PluginConfigHandler::CustomLocationsAdd(), PluginConfigHandler::CustomLocationsRemove(), DisplayActions(), DropNonUsableMaterialsServer(), ItemBase::EEHealthLevelChanged(), ItemBase::EEItemDetached(), UIPopupScript::FindInHierarchy(), ScriptConsoleConfigTab::FindInHierarchy(), GetClosestCarWheel(), GetComponentIndex(), PluginBase::GetConfig(), PluginBase::GetConfigRecursive(), GetDamageZoneFromComponentName(), Debug::GetFiltredConfigClasses(), UIScriptedMenu::GetFiltredConfigClasses(), UIScriptedMenu::GetFiltredSceneObjects(), PluginConfigHandler::GetLocationsData(), IEntity::GetLODByName(), ScriptedWidgetEventHandler::GetMapName(), LOD::GetSelectionByName(), ItemBase::GetSlotIndexBySelection(), GUIAction_SetValue(), ItemBase::HideAllAnimationsAndProxyPhysics(), MissionBaseWorld::InitialiseWorldData(), BleedingSourcesManagerBase::IsBleedingSourceActive(), IsComponentInSelection(), CGame::IsKindOf(), CGame::ObjectIsKindOf(), ActionMountBarbedWire::OnFinishProgressServer(), ScriptConsoleSoundsTab::PrepareFilters(), ScriptConsoleItemsTab::PrepareFilters(), BleedingSourcesManagerBase::RegisterBleedingZoneEx(), ScriptConsoleConfigTab::RenderVariables(), ScriptConsoleItemsTab::SelectPreset(), ItemBase::ToggleAnimation(), ItemBase::UpdateAllSelections(), and ItemBase::UpdatePhysics().
ToString()
static proto string ToString (void var, bool type = false, bool name = false, bool quotes = true) static private
Return string representation of variable.
Referenced by HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Abort(), CGame::AddInventoryJunctureEx(), FireplaceBase::CanPlaceFireplaceInSelectedSpot(), EntityLightSource::CreateLight(), DbgShowBoneName(), DialNextNumber(), ItemBase::EEItemAttached(), ComponentEnergyManager::Event_OnAwake(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState(), ItemBase::GardenBase(), ScriptedWidgetEventHandler::GenerateValidIP(), AntibioticsMdfr::GetDebugText(), DisinfectionMdfr::GetDebugText(), EpinephrineMdfr::GetDebugText(), ImmunityBoost::GetDebugText(), MorphineMdfr::GetDebugText(), PainKillersMdfr::GetDebugText(), AntibioticsMdfr::GetDebugTextSimple(), CharcoalMdfr::GetDebugTextSimple(), DisinfectionMdfr::GetDebugTextSimple(), VicinitySlotsContainer::GetItemQuantityText(), QuantityConversions::GetItemQuantityText(), GetStrValue(), Hologram::Hologram(), ComponentEnergyManager::IsSelectionAPlug(), PluginFileHandler::LoadConfigFile(), PluginConfigHandler::LoadSceneObjects(), Debug::LogArrayInt(), OnActionEnd(), ActionTuneFrequencyOnGround::OnActionInfoUpdate(), MissionBase::OnClientDisconnectedEvent(), PluginFileHandler::ParseParam(), PluginBase::PlayerKilled(), PrintElements(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), PluginConfigHandler::SaveSceneObjects(), PluginConfigHandler::SceneDuplicate(), PluginLocalProfile::SceneSave(), ActionTargetsCursor::SetItemQuantity(), ScriptedWidgetEventHandler::SetItemQuantity(), PluginFileHandler::SetParameterInt(), SetupAction(), ScriptedWidgetEventHandler::SetWeaponQuantity(), ShuffleLock(), OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Terminate(), PluginDayzPlayerDebug_Weapons::Tick(), ToStringLen(), ServerBrowserTab::UpdatePageButtons(), UpdatePlayerStatus(), and ComponentEnergyManager::UpdateSelections().
ToType()
proto native ToType () private
Returns internal type representation. Can be used in runtime, or cached in variables and used for faster inheritance checking.
Returns
typename Type of class
???
Referenced by ArrowManagerPlayer::AddArrowTypeToHash(), ComponentsBank::CreateComponent(), CreateParticle(), DayZCreatureAI::EEHitBy(), ManBase::EEHitBy(), ImpactMaterials::EvaluateImpactEffect(), AmmoEffects::GetAmmoEffectTypename(), PluginBase::GetModuleType(), EffectArea::GetRequesterIndex(), PluginBase::OnKeyPress(), PluginBase::OnMouse(), PluginManager::RegisterPlugin(), ImpactMaterials::RegisterSurface(), and PluginManager::UnregisterPlugin().
ToUpper()
proto int ToUpper () private
Changes string to uppercase. Returns length.
Returns
int - Length of changed string
string str = "Hello World";
int i = str.ToUpper();
Print(str);
Print(i);
>> str = HELLO WORLD
>> i = 11
Referenced by ScriptedWidgetEventHandler::AddEx(), HandsPreview::CreateNewIcon(), Attachments::InitAttachmentGrid(), ClosableContainer::SetEntity(), ScriptedWidgetEventHandler::SetItemDesc(), ActionTargetsCursor::SetItemDesc(), ClosableHeader::SetName(), Header::SetName(), and Container::UpdateHeaderText().
ToVector()
proto vector ToVector () private
Returns a vector from a string.
Returns
vector Converted s as vector
string str = "1 0 1";
vector v = str.ToVector();
Print(v);
>> v = <1,0,1>
Referenced by string::BeautifiedToVector(), UIScriptedMenu::OnClick(), and SceneObject::SetPositionAsString().
Trim()
proto string Trim () private
Returns trimmed string with removed leading and trailing whitespaces.
Returns
string - Trimmed string
string str = " Hello World "
Print(str);
Print(str.Trim());
>> ' Hello World '
>> 'Hello World'
Referenced by PluginBase::GetOnlyChildPath(), ScriptConsoleConfigTab::OnClick(), PluginFileHandler::ParseText(), PluginFileHandler::ParseTextToParameter(), ScriptConsoleSoundsTab::PrepareFilters(), ScriptConsoleItemsTab::PrepareFilters(), and PluginBase::SpawnFromClipboard().
TrimInPlace()
proto int TrimInPlace () private
Removes leading and trailing whitespaces in string. Returns length.
Returns
int - Count of chars
string str = " Hello World ";
int i = str.TrimInPlace();
Print(str);
Print(i);
>> str = 'Hello World'
>> i = 11
Referenced by ScriptedWidgetEventHandler::GetValueString().
Variable Documentation
Empty
const string Empty static private
Referenced by ActionTuneFrequencyOnGround::ActionTuneFrequencyOnGround(), ScriptedWidgetEventHandler::GetActionDesc(), PluginBase::GetFileName(), WeaponStateBase::OnEntry(), WeaponStateBase::OnExit(), DebugPrint::TrimStackTrace(), UIScriptedMenu::UpdateDisconnectTexts(), and ReplaceItemWithNewLambdaBase::WantCreateNewEntity().