DayZ Scripts: AIBehaviourHLDataZombie2 Class Reference
AIBehaviourHLDataZombie2 Class Reference
Private Member Functions
private void AIBehaviourHLDataZombie2 ()
private void ~AIBehaviourHLDataZombie2 ()
override void OnParseConfig ()
Private Attributes
float m_fDamageToCrawl
float m_fCrawlProbability
Constructor & Destructor Documentation
AIBehaviourHLDataZombie2()
private void AIBehaviourHLDataZombie2 () inline private
~AIBehaviourHLDataZombie2()
private void ~AIBehaviourHLDataZombie2 () inline private
Member Function Documentation
OnParseConfig()
override void OnParseConfig () inline private
References m_fCrawlProbability, m_fDamageToCrawl, AIBehaviourHLData::ParseAlertLevel(), AIBehaviourHLData::ParseBehaviourSlot(), Print(), and AIBehaviourHLData::ReadParamValue().
Field Documentation
m_fCrawlProbability
float m_fCrawlProbability private
Referenced by OnParseConfig().
m_fDamageToCrawl
float m_fDamageToCrawl private
Referenced by OnParseConfig().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/AIBehaviour.c