DayZ Scripts: AreaExposureMdfr Class Reference
AreaExposureMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
void ApplyAgentsToBleedingSources (PlayerBase player, float deltaT)
void BleedingSourceCreateCheck (PlayerBase player)
float TransmitAgents (PlayerBase player, float count)
Private Attributes
const int EVENT_1_INTERVAL_MIN = 3
const int EVENT_1_INTERVAL_MAX = 5
const float AGENTS_PER_SEC = 5
protected float m_NextEvent1
protected float m_Time1
const int EVENT_2_INTERVAL_MIN = 13
const int EVENT_2_INTERVAL_MAX = 18
const float AGENT_DOSE_PER_BS_SEC = 0.33
protected float m_NextEvent2
protected float m_Time2
Detailed Description
Definition at line 1 of file AreaExposure.c.
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
Definition at line 33 of file AreaExposure.c.
ApplyAgentsToBleedingSources()
void ApplyAgentsToBleedingSources (PlayerBase player, float deltaT) inline private
Definition at line 106 of file AreaExposure.c.
References AGENT_DOSE_PER_BS_SEC.
Referenced by OnTick().
BleedingSourceCreateCheck()
void BleedingSourceCreateCheck (PlayerBase player) inline private
Definition at line 115 of file AreaExposure.c.
References DEF_CHEMICAL, Math::GetNthBitSet(), Math::GetNumberOfSetBits(), Math::Pow(), Math::RandomFloat01(), and Math::RandomIntInclusive().
Referenced by OnTick().
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
Definition at line 59 of file AreaExposure.c.
Init()
override void Init () inline private
Definition at line 21 of file AreaExposure.c.
References DEFAULT_TICK_TIME_ACTIVE_SHORT, DEFAULT_TICK_TIME_INACTIVE_LONG, DisableActivateCheck(), DisableDeactivateCheck(), m_ID, m_SyncID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void OnActivate (PlayerBase player) inline private
Definition at line 38 of file AreaExposure.c.
References EVENT_1_INTERVAL_MAX, EVENT_1_INTERVAL_MIN, EffectAreaLoader::GetData(), m_NextEvent1, Math::RandomFloatInclusive(), JsonDataContaminatedAreas::SafePositions, and TransmitAgents().
OnDeactivate()
override void OnDeactivate (PlayerBase player) inline private
Definition at line 55 of file AreaExposure.c.
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
Definition at line 64 of file AreaExposure.c.
References AGENTS_PER_SEC, ApplyAgentsToBleedingSources(), BleedingSourceCreateCheck(), EVENT_1_INTERVAL_MAX, EVENT_1_INTERVAL_MIN, EVENT_2_INTERVAL_MAX, EVENT_2_INTERVAL_MIN, m_NextEvent1, m_NextEvent2, m_Time1, m_Time2, Math::RandomFloat01(), Math::RandomFloatInclusive(), and TransmitAgents().
TransmitAgents()
float TransmitAgents (PlayerBase player, float count) inline private
Definition at line 140 of file AreaExposure.c.
References AGT_AIRBOURNE_CHEMICAL, and GetPlugin().
Referenced by OnActivate(), and OnTick().
Field Documentation
AGENT_DOSE_PER_BS_SEC
const float AGENT_DOSE_PER_BS_SEC = 0.33 private
Definition at line 14 of file AreaExposure.c.
Referenced by ApplyAgentsToBleedingSources().
AGENTS_PER_SEC
const float AGENTS_PER_SEC = 5 private
Definition at line 6 of file AreaExposure.c.
Referenced by OnTick().
EVENT_1_INTERVAL_MAX
const int EVENT_1_INTERVAL_MAX = 5 private
Definition at line 4 of file AreaExposure.c.
Referenced by OnActivate(), and OnTick().
EVENT_1_INTERVAL_MIN
const int EVENT_1_INTERVAL_MIN = 3 private
Definition at line 3 of file AreaExposure.c.
Referenced by OnActivate(), and OnTick().
EVENT_2_INTERVAL_MAX
const int EVENT_2_INTERVAL_MAX = 18 private
Definition at line 11 of file AreaExposure.c.
Referenced by OnTick().
EVENT_2_INTERVAL_MIN
const int EVENT_2_INTERVAL_MIN = 13 private
Definition at line 10 of file AreaExposure.c.
Referenced by OnTick().
m_NextEvent1
protected float m_NextEvent1 private
Definition at line 7 of file AreaExposure.c.
Referenced by OnActivate(), and OnTick().
m_NextEvent2
protected float m_NextEvent2 private
Definition at line 16 of file AreaExposure.c.
Referenced by OnTick().
m_Time1
protected float m_Time1 private
Definition at line 8 of file AreaExposure.c.
Referenced by OnTick().
m_Time2
protected float m_Time2 private
Definition at line 17 of file AreaExposure.c.
Referenced by OnTick().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/conditions/AreaExposure.c