DayZ Scripts: DayZPlayerImplementHeading Class Reference
DayZPlayerImplementHeading Class Reference
Static Private Member Functions
static bool ClampHeading (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff)
static bool RotateOrient (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff)
static bool NoHeading (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff)
Static Private Attributes
static float CONST_ROTLIMIT = Math.PI * 0.95
Detailed Description
Definition at line 10 of file DayZPlayerImplementHeading.c.
Member Function Documentation
ClampHeading()
static bool ClampHeading (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff) inline static private
This HeadingModel - Clamps heading
Definition at line 19 of file DayZPlayerImplementHeading.c.
References Math::PI, Math::PI2, and Math::PI_HALF.
Referenced by DayZPlayer::HeadingModel(), and ManBase::HeadingModel().
NoHeading()
static bool NoHeading (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff) inline static private
Definition at line 122 of file DayZPlayerImplementHeading.c.
Referenced by DayZPlayer::HeadingModel(), and ManBase::HeadingModel().
RotateOrient()
static bool RotateOrient (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff) inline static private
Definition at line 67 of file DayZPlayerImplementHeading.c.
References CONST_ROTLIMIT, Math::PI, Math::PI2, and Math::PI_HALF.
Referenced by DayZPlayer::HeadingModel().
Field Documentation
CONST_ROTLIMIT
float CONST_ROTLIMIT = Math.PI * 0.95 static private
This HeadingModel - Rotates orientations - so player slides
Definition at line 64 of file DayZPlayerImplementHeading.c.
Referenced by RotateOrient().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/DayZPlayerImplementHeading.c