DayZ Scripts: ArrowManagerBase Class Reference
ArrowManagerBase Class Reference
Private Member Functions
void ArrowManagerBase (EntityAI owner)
void AddArrow (EntityAI arrow)
void RemoveArrow (EntityAI arrow)
void ClearArrows ()
int GetArrowsCount ()
void DropArrow (int index)
void DropFirstArrow ()
void DropAllArrows ()
EntityAI GetArrow (int index)
EntityAI GetFirstArrow ()
EntityAI AcquireFirstArrow (bool keepTransform=false)
Private Attributes
protected const int VERSION = 2
protected ref array< EntityAI > m_Arrows
protected EntityAI m_Owner
Constructor & Destructor Documentation
ArrowManagerBase()
void ArrowManagerBase (EntityAI owner) inline private
References m_Arrows, and m_Owner.
Member Function Documentation
AcquireFirstArrow()
EntityAI AcquireFirstArrow (bool keepTransform = false) inline private
References GetFirstArrow(), and m_Owner.
Referenced by FirearmActionLoadBullet::Start().
AddArrow()
void AddArrow (EntityAI arrow) inline private
References m_Arrows.
Referenced by Bolt_Base::EEParentedTo().
ClearArrows()
void ClearArrows () inline private
References m_Arrows.
Referenced by ManBase::EEDelete(), and ManBase::ResetPlayer().
DropAllArrows()
void DropAllArrows () inline private
References DropArrow(), and m_Arrows.
Referenced by ManBase::OnBleedingSourceRemoved().
DropArrow()
void DropArrow (int index) inline private
References m_Arrows, m_Owner, and Math3D::MatrixIdentity4().
Referenced by DropAllArrows(), and DropFirstArrow().
DropFirstArrow()
void DropFirstArrow () inline private
References DropArrow().
Referenced by ManBase::OnBleedingSourceRemoved().
GetArrow()
EntityAI GetArrow (int index) inline private
References m_Arrows.
GetArrowsCount()
int GetArrowsCount () inline private
References m_Arrows.
GetFirstArrow()
EntityAI GetFirstArrow () inline private
References m_Arrows.
Referenced by AcquireFirstArrow(), ActionTakeArrow::ActionCondition(), ActionTakeArrowToHands::ActionCondition(), FirearmActionLoadBullet::ActionCondition(), ActionTakeArrow::GetDisplayInteractObject(), ActionTakeArrowToHands::GetDisplayInteractObject(), FirearmActionLoadBullet::GetDisplayInteractObject(), ActionTakeArrow::InventoryReservation(), and ActionTakeArrowToHands::InventoryReservation().
RemoveArrow()
void RemoveArrow (EntityAI arrow) inline private
References m_Arrows.
Referenced by Bolt_Base::EEParentedFrom().
Field Documentation
m_Arrows
protected ref array<EntityAI> m_Arrows private
Referenced by AddArrow(), ArrowManagerBase(), ClearArrows(), DropAllArrows(), DropArrow(), GetArrow(), GetArrowsCount(), GetFirstArrow(), RemoveArrow(), and ArrowManagerPlayer::Save().
m_Owner
protected EntityAI m_Owner private
Referenced by AcquireFirstArrow(), ArrowManagerBase(), DropArrow(), and ArrowManagerPlayer::Load().
VERSION
protected const int VERSION = 2 private
Referenced by ArrowManagerPlayer::Save().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/ArrowManager/ArrowManagerBase.c