DayZ Scripts: ScriptConsoleConfigTab Class Reference
ScriptConsoleConfigTab Class Reference
Private Member Functions
void ScriptConsoleConfigTab (Widget root, ScriptConsole console)
void ~ScriptConsoleConfigTab ()
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
override bool OnClick (Widget w, int x, int y, int button)
override void Update (float timeslice)
protected void Init ()
protected void DumpParam (string param, string relativePath)
protected void ChangeConfigFilter ()
protected void ClearHierarchy ()
protected void FindInHierarchy (string class_name)
protected void ExpandHierarchy (int row)
protected void CollapseHierarchy (int row)
protected void RenderVariables (int row)
Private Attributes
protected ref TStringArray m_BaseConfigClasses = new TStringArray
protected ref TStringArray m_BaseConfigClassesToggled = new TStringArray
protected ref map< CheckBoxWidget, int > m_ClassCheckboxes = new map<CheckBoxWidget, int>
protected EditBoxWidget m_ObjectConfigFilter
protected EditBoxWidget m_VariableConfigFilter
protected TextListboxWidget m_ConfigHierarchyTextListbox
protected TextListboxWidget m_ConfigVariablesTextListbox
protected ButtonWidget m_SelectedRowCopy
protected ButtonWidget m_DumpParamButton
protected Widget m_WgtClassesConfig
protected PluginConfigViewer m_ModuleConfigViewer
protected int m_Row
Static Private Attributes
static protected string m_ConfigTextField
static protected string m_VariableTextField
static protected ref ConfigParamsEx m_ConfigData
Constructor & Destructor Documentation
ScriptConsoleConfigTab()
void ScriptConsoleConfigTab (Widget root, ScriptConsole console) inline private
References Init(), m_ConfigHierarchyTextListbox, m_ConfigTextField, m_ConfigVariablesTextListbox, m_DumpParamButton, m_ObjectConfigFilter, m_SelectedRowCopy, m_VariableConfigFilter, m_VariableTextField, and m_WgtClassesConfig.
~ScriptConsoleConfigTab()
void ~ScriptConsoleConfigTab () inline private
References m_ClassCheckboxes, m_VariableConfigFilter, and m_VariableTextField.
Member Function Documentation
ChangeConfigFilter()
protected void ChangeConfigFilter () inline private
References ClearHierarchy(), FindInHierarchy(), m_ConfigTextField, and m_ObjectConfigFilter.
Referenced by Init(), and OnChange().
ClearHierarchy()
protected void ClearHierarchy () inline private
References m_BaseConfigClassesToggled, m_ConfigHierarchyTextListbox, m_ConfigVariablesTextListbox, and m_ModuleConfigViewer.
Referenced by ChangeConfigFilter(), Init(), and OnClick().
CollapseHierarchy()
protected void CollapseHierarchy (int row) inline private
References m_ConfigHierarchyTextListbox, and x.
Referenced by OnClick().
DumpParam()
protected void DumpParam (string param, string relativePath) inline private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), GetGame(), m_BaseConfigClassesToggled, path, and Print().
Referenced by OnClick().
ExpandHierarchy()
protected void ExpandHierarchy (int row) inline private
References m_ConfigHierarchyTextListbox, and m_ModuleConfigViewer.
Referenced by OnClick().
FindInHierarchy()
protected void FindInHierarchy (string class_name) inline private
References class_name, string::Contains(), m_BaseConfigClassesToggled, m_ConfigHierarchyTextListbox, m_ConfigVariablesTextListbox, m_ModuleConfigViewer, string::Split(), and string::ToLower().
Referenced by ChangeConfigFilter().
Init()
protected void Init () inline private
References ChangeConfigFilter(), ClearHierarchy(), WorkspaceWidget::CreateWidgets(), Debug::GetBaseConfigClasses(), GetGame(), GetPlugin(), CGame::GetWorkspace(), m_BaseConfigClasses, m_BaseConfigClassesToggled, m_ClassCheckboxes, ScriptConsoleTabBase::m_ConfigDebugProfile, m_ModuleConfigViewer, m_WgtClassesConfig, Math::Pow(), and Widget::SetText().
Referenced by ScriptConsoleConfigTab().
OnChange()
override bool OnChange (Widget w, int x, int y, bool finished) inline private
References ChangeConfigFilter(), m_ObjectConfigFilter, m_Row, m_VariableConfigFilter, RenderVariables(), x, and y.
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References ScriptConsoleTabBase::AddItemToClipboard(), ClearHierarchy(), CollapseHierarchy(), DumpParam(), ExpandHierarchy(), string::IndexOf(), int, m_BaseConfigClasses, m_BaseConfigClassesToggled, m_ClassCheckboxes, ScriptConsoleTabBase::m_ConfigDebugProfile, m_ConfigHierarchyTextListbox, m_ConfigVariablesTextListbox, m_DumpParamButton, m_Row, m_SelectedRowCopy, path, Math::Pow(), Print(), RenderVariables(), string::Split(), string::Substring(), string::Trim(), x, and y.
OnItemSelected()
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
References m_ConfigData, m_ConfigHierarchyTextListbox, x, and y.
RenderVariables()
protected void RenderVariables (int row) inline private
References string::Contains(), m_ConfigHierarchyTextListbox, m_ConfigVariablesTextListbox, m_ModuleConfigViewer, m_VariableConfigFilter, path, string::Split(), and string::ToLower().
Referenced by OnChange(), and OnClick().
Update()
override void Update (float timeslice) inline private
Field Documentation
m_BaseConfigClasses
protected ref TStringArray m_BaseConfigClasses = new TStringArray private
Referenced by Init(), and OnClick().
m_BaseConfigClassesToggled
protected ref TStringArray m_BaseConfigClassesToggled = new TStringArray private
Referenced by ClearHierarchy(), DumpParam(), FindInHierarchy(), Init(), and OnClick().
m_ClassCheckboxes
protected ref map<CheckBoxWidget, int> m_ClassCheckboxes = new map<CheckBoxWidget, int> private
Referenced by Init(), OnClick(), and ~ScriptConsoleConfigTab().
m_ConfigData
protected ref ConfigParamsEx m_ConfigData static private
Referenced by OnItemSelected().
m_ConfigHierarchyTextListbox
protected TextListboxWidget m_ConfigHierarchyTextListbox private
Referenced by ClearHierarchy(), CollapseHierarchy(), ExpandHierarchy(), FindInHierarchy(), OnClick(), OnItemSelected(), RenderVariables(), and ScriptConsoleConfigTab().
m_ConfigTextField
protected string m_ConfigTextField static private
Referenced by ChangeConfigFilter(), and ScriptConsoleConfigTab().
m_ConfigVariablesTextListbox
protected TextListboxWidget m_ConfigVariablesTextListbox private
Referenced by ClearHierarchy(), FindInHierarchy(), OnClick(), RenderVariables(), and ScriptConsoleConfigTab().
m_DumpParamButton
protected ButtonWidget m_DumpParamButton private
Referenced by OnClick(), and ScriptConsoleConfigTab().
m_ModuleConfigViewer
protected PluginConfigViewer m_ModuleConfigViewer private
Referenced by ClearHierarchy(), ExpandHierarchy(), FindInHierarchy(), Init(), and RenderVariables().
m_ObjectConfigFilter
protected EditBoxWidget m_ObjectConfigFilter private
Referenced by ChangeConfigFilter(), OnChange(), and ScriptConsoleConfigTab().
m_Row
protected int m_Row private
Referenced by OnChange(), and OnClick().
m_SelectedRowCopy
protected ButtonWidget m_SelectedRowCopy private
Referenced by OnClick(), and ScriptConsoleConfigTab().
m_VariableConfigFilter
protected EditBoxWidget m_VariableConfigFilter private
Referenced by OnChange(), RenderVariables(), ScriptConsoleConfigTab(), and ~ScriptConsoleConfigTab().
m_VariableTextField
protected string m_VariableTextField static private
Referenced by ScriptConsoleConfigTab(), and ~ScriptConsoleConfigTab().
m_WgtClassesConfig
protected Widget m_WgtClassesConfig private
Referenced by Init(), and ScriptConsoleConfigTab().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptConsoleConfigTab.c