DayZ Scripts: ContentDLC Class Reference
ContentDLC Class Reference
ContentDLC is for query installed DLC (only as entitlement keys, not content)
Private Member Functions
proto native int GetEntitlements (out TIntArray dlcIdList)
proto native bool IsDLCInstalled (EDLCId dlcId)
bool OwnsAllDLC ()
void OnChange (EDLCId dlcId)
Private Attributes
ref ScriptInvoker m_OnChange = new ScriptInvoker()
void(EDLCId dlcId)
Detailed Description
ContentDLC is for query installed DLC (only as entitlement keys, not content)
Member Function Documentation
GetEntitlements()
proto native int GetEntitlements (out TIntArray dlcIdList) private
For getting current entitlements on device (console). Could be called after any entitlement change or before accessing locked content.
Parameters
dlcIdList through this list is returned all installed DLC with valid license for current user
Returns
count of installed and valid DLCs.
IsDLCInstalled()
proto native bool IsDLCInstalled (EDLCId dlcId) private
Parameters
dlcId ID of DLC
Returns
current state of availability of unlocking' dlc. Only DLC with valid license return true.
Referenced by OwnsAllDLC().
OnChange()
void OnChange (EDLCId dlcId) inline private
Called from engine for notifing script after any change in additional content (installed, lost license). There should be check for current state of entitlements. On Xbox should be problem with event lost license! (system bug)
Parameters
dlcId ID of DLC that was changed. Could be empty string if console does not report concrete DLC ID.
References ScriptInvoker::Invoke(), and m_OnChange.
OwnsAllDLC()
bool OwnsAllDLC () inline private
References EnumTools::GetEnumSize(), EnumTools::GetEnumValue(), and IsDLCInstalled().
Field Documentation
m_OnChange
ref ScriptInvoker m_OnChange = new ScriptInvoker() private
void(EDLCId dlcId)
Referenced by UIScriptedMenu::Init(), ScriptedWidgetEventHandler::MainMenuDlcHandlerBase(), OnChange(), ServerBrowserTab(), UIScriptedMenu::~MainMenuConsole(), ScriptedWidgetEventHandler::~MainMenuDlcHandlerBase(), and ~ServerBrowserTab().
The documentation for this class was generated from the following file:
P:/scripts/3_game/services/contentdlc.c