DayZ Scripts: EffBulletImpactBase Class Reference
EffBulletImpactBase Class Reference
Private Member Functions
void EffBulletImpactBase ()
override void OnCheckUpdate ()
void SetEnterParticle (int id)
void SetExitParticle (int id)
void SetRicochetParticle (int id)
void SetSingleParticle (int id)
void SetAngledEnterValue (float f)
void EvaluateEffect (Object directHit, int componentIndex, vector pos, int impact_type, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, string ammoType)
float CalculateStoppingForce (float in_speedf, float out_speedf, string ammoType, float weight)
void OnEnterCalculations (Particle p)
void OnExitCalculations (Particle p, float outSpeedf)
void OnRicochetCalculations (Particle p, float outspeedf)
void OnEnterAngledCalculations (Particle p)
override void Event_OnStarted ()
Private Attributes
float MIN_SCALING_PARAM = 0.1
Object m_DirectHit
float m_StoppingForce
float m_Weight
int m_ImpactType
int m_ComponentIndex
vector m_Pos
vector m_SurfNormal
vector m_ExitPos
vector m_InSpeed
vector m_OutSpeed
string m_AmmoType
int m_ParticleEnter = -1
int m_ParticleExit = -1
int m_ParticleRicochet = -1
float m_EnterSplashCoef = 0.003
float m_ExitSplashCoef = 0.002
float m_RicochetSplashCoef = 0.002
float m_EnterAngledSplashCoef = 0.01
float m_AngledEnter = 0.40
Static Private Attributes
static const int SURVIVOR_HEAD = 0
static const int INFECTED_HEAD = 3
static float DEFAULT_PROJECTILE_WEIGHT = 0.015
static vector INVALID = "0 0 0"
Detailed Description
Definition at line 1 of file BulletImpactBase.c.
Constructor & Destructor Documentation
EffBulletImpactBase()
void EffBulletImpactBase () inline private
Definition at line 35 of file BulletImpactBase.c.
Member Function Documentation
CalculateStoppingForce()
float CalculateStoppingForce (float in_speedf, float out_speedf, string ammoType, float weight) inline private
Definition at line 88 of file BulletImpactBase.c.
References DEFAULT_PROJECTILE_WEIGHT, m_ImpactType, and Math::RandomFloat().
Referenced by EvaluateEffect().
EvaluateEffect()
void EvaluateEffect (Object directHit, int componentIndex, vector pos, int impact_type, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, string ammoType) inline private
Definition at line 72 of file BulletImpactBase.c.
References CalculateStoppingForce(), CGame::ConfigGetFloat(), GetGame(), vector::Length(), m_AmmoType, m_ComponentIndex, m_DirectHit, m_ExitPos, m_ImpactType, m_InSpeed, m_OutSpeed, m_Pos, m_StoppingForce, m_SurfNormal, and m_Weight.
Referenced by ImpactMaterials::EvaluateImpactEffect().
Event_OnStarted()
override void Event_OnStarted () inline private
Definition at line 221 of file BulletImpactBase.c.
References vector::Distance(), vector::Dot(), CGame::GetCurrentCameraPosition(), GetDayZGame(), GetGame(), ParticleList::IMPACT_DISTANT_DUST, INVALID, vector::Length(), m_AngledEnter, m_ExitPos, m_ImpactType, m_InSpeed, m_OutSpeed, m_ParticleEnter, m_ParticleExit, m_ParticleRicochet, m_Pos, m_SurfNormal, vector::Normalized(), OnEnterAngledCalculations(), OnEnterCalculations(), OnExitCalculations(), OnRicochetCalculations(), ParticleManager(), Particle::PlayInWorld(), Particle::ScaleParticleParam(), EffectParticle::SetParticle(), Type, and vector::VectorToAngles().
OnCheckUpdate()
override void OnCheckUpdate () inline private
Definition at line 40 of file BulletImpactBase.c.
OnEnterAngledCalculations()
void OnEnterAngledCalculations (Particle p) inline private
Definition at line 199 of file BulletImpactBase.c.
References m_EnterAngledSplashCoef, m_StoppingForce, MIN_SCALING_PARAM, and Particle::ScaleParticleParam().
Referenced by Event_OnStarted().
OnEnterCalculations()
void OnEnterCalculations (Particle p) inline private
Definition at line 102 of file BulletImpactBase.c.
References m_AmmoType, m_EnterSplashCoef, m_StoppingForce, and Particle::ScaleParticleParam().
Referenced by Event_OnStarted().
OnExitCalculations()
void OnExitCalculations (Particle p, float outSpeedf) inline private
Definition at line 155 of file BulletImpactBase.c.
References m_ExitSplashCoef, MIN_SCALING_PARAM, and Particle::ScaleParticleParam().
Referenced by Event_OnStarted().
OnRicochetCalculations()
void OnRicochetCalculations (Particle p, float outspeedf) inline private
Definition at line 177 of file BulletImpactBase.c.
References m_RicochetSplashCoef, m_StoppingForce, MIN_SCALING_PARAM, and Particle::ScaleParticleParam().
Referenced by Event_OnStarted().
SetAngledEnterValue()
void SetAngledEnterValue (float f) inline private
Definition at line 67 of file BulletImpactBase.c.
References m_AngledEnter.
SetEnterParticle()
void SetEnterParticle (int id) inline private
Definition at line 45 of file BulletImpactBase.c.
References m_ParticleEnter.
Referenced by Hit_Water::CalculateStoppingForce(), Hit_Concrete::Hit_Concrete(), Hit_Dirt::Hit_Dirt(), Hit_Foliage::Hit_Foliage(), Hit_Glass::Hit_Glass(), Hit_Glass_Thin::Hit_Glass_Thin(), Hit_Grass::Hit_Grass(), Hit_Gravel::Hit_Gravel(), Hit_MeatBones::Hit_MeatBones(), Hit_Metal::Hit_Metal(), Hit_Plaster::Hit_Plaster(), Hit_Plastic::Hit_Plastic(), Hit_Rubber::Hit_Rubber(), Hit_Sand::Hit_Sand(), Hit_Textile::Hit_Textile(), Hit_Wood::Hit_Wood(), and SetSingleParticle().
SetExitParticle()
void SetExitParticle (int id) inline private
Definition at line 50 of file BulletImpactBase.c.
References m_ParticleExit.
Referenced by Hit_Concrete::Hit_Concrete(), Hit_Dirt::Hit_Dirt(), Hit_Foliage::Hit_Foliage(), Hit_Glass::Hit_Glass(), Hit_Glass_Thin::Hit_Glass_Thin(), Hit_Grass::Hit_Grass(), Hit_Gravel::Hit_Gravel(), Hit_MeatBones::Hit_MeatBones(), Hit_Metal::Hit_Metal(), Hit_Plaster::Hit_Plaster(), Hit_Plastic::Hit_Plastic(), Hit_Rubber::Hit_Rubber(), Hit_Sand::Hit_Sand(), Hit_Textile::Hit_Textile(), Hit_Wood::Hit_Wood(), and SetSingleParticle().
SetRicochetParticle()
void SetRicochetParticle (int id) inline private
Definition at line 55 of file BulletImpactBase.c.
References m_ParticleRicochet.
Referenced by Hit_Concrete::Hit_Concrete(), Hit_Dirt::Hit_Dirt(), Hit_Foliage::Hit_Foliage(), Hit_Glass::Hit_Glass(), Hit_Glass_Thin::Hit_Glass_Thin(), Hit_Grass::Hit_Grass(), Hit_Gravel::Hit_Gravel(), Hit_MeatBones::Hit_MeatBones(), Hit_Metal::Hit_Metal(), Hit_Plaster::Hit_Plaster(), Hit_Plastic::Hit_Plastic(), Hit_Rubber::Hit_Rubber(), Hit_Sand::Hit_Sand(), Hit_Textile::Hit_Textile(), Hit_Wood::Hit_Wood(), and SetSingleParticle().
SetSingleParticle()
void SetSingleParticle (int id) inline private
Definition at line 60 of file BulletImpactBase.c.
References SetEnterParticle(), SetExitParticle(), and SetRicochetParticle().
Referenced by Hit_ErrorNoMaterial::Hit_ErrorNoMaterial(), Hit_MeatBones_MeleeFist::Hit_MeatBones_MeleeFist(), Hit_Undefined::Hit_Undefined(), and Hit_Water::Hit_Water().
Field Documentation
DEFAULT_PROJECTILE_WEIGHT
float DEFAULT_PROJECTILE_WEIGHT = 0.015 static private
Definition at line 5 of file BulletImpactBase.c.
Referenced by CalculateStoppingForce(), Hit_Foliage::CalculateStoppingForce(), Hit_MeatBones::CalculateStoppingForce(), and Hit_Water::CalculateStoppingForce().
INFECTED_HEAD
const int INFECTED_HEAD = 3 static private
Definition at line 4 of file BulletImpactBase.c.
INVALID
vector INVALID = "0 0 0" static private
Definition at line 21 of file BulletImpactBase.c.
Referenced by Event_OnStarted().
m_AmmoType
string m_AmmoType private
Definition at line 19 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), OnEnterCalculations(), and Hit_MeatBones::OnEnterCalculations().
m_AngledEnter
float m_AngledEnter = 0.40 private
Definition at line 33 of file BulletImpactBase.c.
Referenced by Event_OnStarted(), Hit_Concrete::Hit_Concrete(), Hit_Grass::Hit_Grass(), Hit_MeatBones::Hit_MeatBones(), Hit_Water::Hit_Water(), and SetAngledEnterValue().
m_ComponentIndex
int m_ComponentIndex private
Definition at line 13 of file BulletImpactBase.c.
Referenced by EvaluateEffect().
m_DirectHit
Object m_DirectHit private
Definition at line 9 of file BulletImpactBase.c.
Referenced by Hit_MeatBones::CalculateStoppingForce(), and EvaluateEffect().
m_EnterAngledSplashCoef
float m_EnterAngledSplashCoef = 0.01 private
Definition at line 32 of file BulletImpactBase.c.
Referenced by OnEnterAngledCalculations().
m_EnterSplashCoef
float m_EnterSplashCoef = 0.003 private
Definition at line 29 of file BulletImpactBase.c.
Referenced by Hit_MeatBones::Hit_MeatBones(), OnEnterCalculations(), Hit_MeatBones::OnEnterCalculations(), and Hit_Wood::OnEnterCalculations().
m_ExitPos
vector m_ExitPos private
Definition at line 16 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), Event_OnStarted(), and Hit_MeatBones::Event_OnStarted().
m_ExitSplashCoef
float m_ExitSplashCoef = 0.002 private
Definition at line 30 of file BulletImpactBase.c.
Referenced by Hit_MeatBones::Hit_MeatBones(), OnExitCalculations(), Hit_MeatBones::OnExitCalculations(), and Hit_Wood::OnExitCalculations().
m_ImpactType
int m_ImpactType private
Definition at line 12 of file BulletImpactBase.c.
Referenced by CalculateStoppingForce(), Hit_Foliage::CalculateStoppingForce(), Hit_MeatBones::CalculateStoppingForce(), EvaluateEffect(), Event_OnStarted(), and Hit_MeatBones::Event_OnStarted().
m_InSpeed
vector m_InSpeed private
Definition at line 17 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), Event_OnStarted(), and Hit_MeatBones::Event_OnStarted().
m_OutSpeed
vector m_OutSpeed private
Definition at line 18 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), Event_OnStarted(), and Hit_MeatBones::Event_OnStarted().
m_ParticleEnter
int m_ParticleEnter = -1 private
Definition at line 24 of file BulletImpactBase.c.
Referenced by Event_OnStarted(), and SetEnterParticle().
m_ParticleExit
int m_ParticleExit = -1 private
Definition at line 25 of file BulletImpactBase.c.
Referenced by Event_OnStarted(), and SetExitParticle().
m_ParticleRicochet
int m_ParticleRicochet = -1 private
Definition at line 26 of file BulletImpactBase.c.
Referenced by Event_OnStarted(), and SetRicochetParticle().
m_Pos
vector m_Pos private
Definition at line 14 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), Event_OnStarted(), and Hit_MeatBones::OnEnterCalculations().
m_RicochetSplashCoef
float m_RicochetSplashCoef = 0.002 private
Definition at line 31 of file BulletImpactBase.c.
Referenced by OnRicochetCalculations().
m_StoppingForce
float m_StoppingForce private
Definition at line 10 of file BulletImpactBase.c.
Referenced by Hit_MeatBones::BloodSplatGround(), EvaluateEffect(), OnEnterAngledCalculations(), OnEnterCalculations(), Hit_MeatBones::OnEnterCalculations(), Hit_Wood::OnEnterCalculations(), and OnRicochetCalculations().
m_SurfNormal
vector m_SurfNormal private
Definition at line 15 of file BulletImpactBase.c.
Referenced by EvaluateEffect(), Hit_Water::EvaluateEffect(), and Event_OnStarted().
m_Weight
float m_Weight private
Definition at line 11 of file BulletImpactBase.c.
Referenced by EvaluateEffect().
MIN_SCALING_PARAM
float MIN_SCALING_PARAM = 0.1 private
Definition at line 7 of file BulletImpactBase.c.
Referenced by Hit_MeatBones::Hit_MeatBones(), OnEnterAngledCalculations(), Hit_MeatBones::OnEnterCalculations(), Hit_Wood::OnEnterCalculations(), OnExitCalculations(), Hit_MeatBones::OnExitCalculations(), Hit_Wood::OnExitCalculations(), and OnRicochetCalculations().
SURVIVOR_HEAD
const int SURVIVOR_HEAD = 0 static private
Definition at line 3 of file BulletImpactBase.c.
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Effects/EffectParticle/BulletImpactBase.c