DayZ Scripts: ModLoader Class Reference
ModLoader Class Reference
Static Private Member Functions
static array< ref ModStructure > GetMods ()
static void LoadMods ()
Static Private Attributes
static protected bool m_Loaded
static protected ref array< ref ModStructure > m_Mods
Member Function Documentation
GetMods()
static array< ref ModStructure > GetMods () inline static private
References LoadMods(), and m_Mods.
LoadMods()
static void LoadMods () inline static private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), and m_Mods.
Referenced by GetMods().
Field Documentation
m_Loaded
protected bool m_Loaded static private
m_Mods
protected ref array<ref ModStructure> m_Mods static private
Referenced by GetMods(), and LoadMods().
The documentation for this class was generated from the following file:
3_Game/Client/Mods/ModLoader.c