DayZ Scripts: UAInput Class Reference
UAInput Class Reference
Private Member Functions
proto native int ID ()
proto native int NameHash ()
proto native int BindingCount ()
proto native int Binding (int iIndex)
proto native void ClearBinding ()
proto native void BindCombo (string sButtonName)
proto native void BindComboByHash (int iHash)
proto native void AddAlternative ()
proto native void ClearAlternative (int iIndex)
proto native void SelectAlternative (int iIndex)
proto native int AlternativeCount ()
proto native int AlternativeIndex ()
proto native void ClearDeviceBind (int iDeviceFlags)
proto native int BindKeyCount ()
proto native int GetBindKey (int iIndex)
proto native int GetBindDevice (int iIndex)
proto native bool CheckBindDevice (int iIndex, int iDeviceFlags)
proto native float LocalValue ()
proto native bool LocalPress ()
proto native bool LocalRelease ()
proto native bool LocalHold ()
proto native bool LocalHoldBegin ()
proto native bool LocalDoubleClick ()
proto native bool LocalClick ()
proto native bool IsCombo ()
proto native bool IsLimited ()
proto native bool IsLimitConditionActive ()
proto native bool IsPressLimit ()
proto native bool IsReleaseLimit ()
proto native bool IsHoldLimit ()
proto native bool IsHoldBeginLimit ()
proto native bool IsClickLimit ()
proto native bool IsDoubleClickLimit ()
proto native bool HasSorting (int iIndex)
proto native void Supress ()
proto native bool IsLocked ()
proto native void Lock ()
proto native void Unlock ()
proto native int ConflictCount ()
proto native void ForceEnable (bool bEnable)
proto native void ForceDisable (bool bEnable)
proto native void Backlit_Override (int eType, int iColor)
proto native bool Backlit_Enabled ()
proto native UAIDWrapper GetPersistentWrapper ()
private void UAInput ()
private void ~UAInput ()
Constructor & Destructor Documentation
UAInput()
private void UAInput () private
~UAInput()
private void ~UAInput () private
Member Function Documentation
AddAlternative()
proto native void AddAlternative () private
Referenced by array::Apply(), and ScriptedWidgetEventHandler::Apply().
AlternativeCount()
proto native int AlternativeCount () private
Referenced by array::Apply(), ScriptedWidgetEventHandler::Apply(), InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), ScriptedWidgetEventHandler::SetElementTitle(), and ScriptedWidgetEventHandler::SetElementTitle().
AlternativeIndex()
proto native int AlternativeIndex () private
Backlit_Enabled()
proto native bool Backlit_Enabled () private
Backlit_Override()
proto native void Backlit_Override (int eType, int iColor) private
Referenced by Backlit::HintShow().
BindCombo()
proto native void BindCombo (string sButtonName) private
BindComboByHash()
proto native void BindComboByHash (int iHash) private
Referenced by array::Apply(), and ScriptedWidgetEventHandler::Apply().
Binding()
proto native int Binding (int iIndex) private
Referenced by InputUtils::GetComboButtonNamesFromInput(), ScriptedWidgetEventHandler::SetElementTitle(), and ScriptedWidgetEventHandler::SetElementTitle().
BindingCount()
proto native int BindingCount () private
Referenced by InputUtils::GetComboButtonNamesFromInput(), ScriptedWidgetEventHandler::SetElementTitle(), and ScriptedWidgetEventHandler::SetElementTitle().
BindKeyCount()
proto native int BindKeyCount () private
CheckBindDevice()
proto native bool CheckBindDevice (int iIndex, int iDeviceFlags) private
Referenced by InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), ScriptedWidgetEventHandler::SetElementTitle(), and ScriptedWidgetEventHandler::SetElementTitle().
ClearAlternative()
proto native void ClearAlternative (int iIndex) private
ClearBinding()
proto native void ClearBinding () private
ClearDeviceBind()
proto native void ClearDeviceBind (int iDeviceFlags) private
Referenced by array::Apply(), and ScriptedWidgetEventHandler::Apply().
ConflictCount()
proto native int ConflictCount () private
ForceDisable()
proto native void ForceDisable (bool bEnable) private
ForceEnable()
proto native void ForceEnable (bool bEnable) private
Referenced by MissionBase::AddActiveInputRestriction(), and MissionBase::RemoveActiveInputRestriction().
GetBindDevice()
proto native int GetBindDevice (int iIndex) private
GetBindKey()
proto native int GetBindKey (int iIndex) private
Referenced by InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), and ScriptedWidgetEventHandler::SetInteractActionIcon().
GetPersistentWrapper()
proto native UAIDWrapper GetPersistentWrapper () private
Referenced by ActionTargetsCursor::ActionTargetsCursor(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::ItemActionsWidget(), RadialMenu(), and ActionInput::SetInput().
HasSorting()
proto native bool HasSorting (int iIndex) private
Referenced by InputUtils::InitInputMetadata().
ID()
proto native int ID () private
Referenced by ConstructData().
IsClickLimit()
proto native bool IsClickLimit () private
Referenced by GetStringVariant(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsCombo()
proto native bool IsCombo () private
Referenced by InputUtils::GetComboButtonNamesFromInput(), ScriptedWidgetEventHandler::SetElementTitle(), and ScriptedWidgetEventHandler::SetElementTitle().
IsDoubleClickLimit()
proto native bool IsDoubleClickLimit () private
Referenced by GetStringVariant(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsHoldBeginLimit()
proto native bool IsHoldBeginLimit () private
Referenced by GetStringVariant(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsHoldLimit()
proto native bool IsHoldLimit () private
Referenced by GetStringVariant(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsLimitConditionActive()
proto native bool IsLimitConditionActive () private
IsLimited()
proto native bool IsLimited () private
Referenced by GetStringVariant(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsLocked()
proto native bool IsLocked () private
IsPressLimit()
proto native bool IsPressLimit () private
Referenced by ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsReleaseLimit()
proto native bool IsReleaseLimit () private
Referenced by ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
LocalClick()
proto native bool LocalClick () private
Referenced by ActionInput::Update().
LocalDoubleClick()
proto native bool LocalDoubleClick () private
Referenced by ActionInput::Update().
LocalHold()
proto native bool LocalHold () private
Referenced by ActionInput::Update().
LocalHoldBegin()
proto native bool LocalHoldBegin () private
Referenced by ActionInput::Update().
LocalPress()
proto native bool LocalPress () private
Referenced by InventoryMovementButtonTickHandler(), UpdataControllerInput(), and UIScriptedMenu::Update().
LocalRelease()
proto native bool LocalRelease () private
LocalValue()
proto native float LocalValue () private
Referenced by DayZSpectator::EOnFrame(), and InventoryMovementButtonTickHandler().
Lock()
proto native void Lock () private
Referenced by DayZPlayer::OnSprintStart(), and MissionBase::OnUpdate().
NameHash()
proto native int NameHash () private
SelectAlternative()
proto native void SelectAlternative (int iIndex) private
Referenced by InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), ScriptedWidgetEventHandler::SetElementTitle(), ScriptedWidgetEventHandler::SetElementTitle(), and ScriptedWidgetEventHandler::SetInteractActionIcon().
Supress()
proto native void Supress () private
Referenced by ManBase::CommandHandler(), and UIScriptedMenu::OnChange().
Unlock()
proto native void Unlock () private
Referenced by DayZPlayer::OnSprintEnd(), and MissionBase::OnUpdate().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/InputAPI/UAInput.c