DayZ Scripts: PPEManagerStatic Class Reference
PPEManagerStatic Class Reference
Static component of PPE manager, used to hold the instance.
Static Private Member Functions
static void CreateManagerStatic ()
static void DestroyManagerStatic ()
static PPEManager GetPPEManager ()
Returns the manager instance singleton.
Static Private Attributes
static ref PPEManager m_Manager
Detailed Description
Static component of PPE manager, used to hold the instance.
Definition at line 2 of file PPEManager.c.
Member Function Documentation
CreateManagerStatic()
static void CreateManagerStatic () inline static private
Definition at line 6 of file PPEManager.c.
References Debug::Log(), m_Manager, and PPEManager().
Referenced by DayZGame().
DestroyManagerStatic()
static void DestroyManagerStatic () inline static private
Definition at line 17 of file PPEManager.c.
References m_Manager.
Referenced by ~DayZGame().
GetPPEManager()
static PPEManager GetPPEManager () inline static private
Returns the manager instance singleton.
Definition at line 27 of file PPEManager.c.
References m_Manager.
Referenced by BleedingIndicatorDropData::AdjustColorSaturation(), DeferredInit(), PPEClassBase::Init(), LoadingHide(), PPEMatClassParameterColor::ModifyResultValues(), MissionBase::OnMissionFinish(), ManBase::OnSelectPlayer(), PPERequesterBase::RelativizeValue(), PPERequesterBase::SendCurrentValueData(), PPERequesterBase::SetRequesterUpdating(), PPEMatClassParameterCommandData::Update(), DayZIntroScene::~DayZIntroScene(), and DayZIntroSceneXbox::~DayZIntroSceneXbox().
Field Documentation
m_Manager
ref PPEManager m_Manager static private
Definition at line 4 of file PPEManager.c.
Referenced by CreateManagerStatic(), DestroyManagerStatic(), and GetPPEManager().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/PPEManager/PPEManager.c