DayZ Scripts: CAContinuousMineWood Class Reference
CAContinuousMineWood Class Reference
Private Member Functions
void CAContinuousMineWood (float time_between_drops)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override float GetProgress ()
override int Cancel (ActionData action_data)
bool GetMiningData (ActionData action_data)
void CreatePrimaryItems (ActionData action_data)
void CreateSecondaryItems (ActionData action_data, string material_secondary="", int quantity_secondary=-1)
void DamagePlayersHands (PlayerBase player)
Private Attributes
protected float m_TimeElpased
protected float m_AdjustedTimeBetweenMaterialDrops
protected float m_CycleTimeOverride
protected float m_TimeBetweenMaterialDrops
protected float m_DamageToMiningItemEachDrop
protected float m_AdjustedDamageToMiningItemEachDrop
protected int m_AmountOfDrops
protected ref map< string, int > m_MaterialAndQuantityMap
protected float m_TimeToComplete
protected ref Param1< float > m_SpentUnits
protected bool m_DataLoaded = false
protected const int MINEDITEM_MAX = 5
protected ItemBase m_MinedItem [MINEDITEM_MAX]
protected ItemBase m_SecondaryItem
Detailed Description
Definition at line 1 of file CAContinuousMineWood.c.
Constructor & Destructor Documentation
CAContinuousMineWood()
void CAContinuousMineWood (float time_between_drops) inline private
Definition at line 20 of file CAContinuousMineWood.c.
References m_CycleTimeOverride, and m_TimeBetweenMaterialDrops.
Member Function Documentation
Cancel()
override int Cancel (ActionData action_data) inline private
Definition at line 131 of file CAContinuousMineWood.c.
References ActionData::m_MainItem.
CreatePrimaryItems()
void CreatePrimaryItems (ActionData action_data) inline private
Definition at line 161 of file CAContinuousMineWood.c.
References ECE_PLACE_ON_SURFACE, GetGame(), HasQuantity(), IsFullQuantity(), m_MaterialAndQuantityMap, m_MinedItem, and ActionData::m_Player.
Referenced by Execute().
CreateSecondaryItems()
void CreateSecondaryItems (ActionData action_data, string material_secondary = "", int quantity_secondary = -1) inline private
Definition at line 208 of file CAContinuousMineWood.c.
References Math::Ceil(), CreateSecondaryItems(), ECE_PLACE_ON_SURFACE, GetGame(), ActionData::m_Player, and m_SecondaryItem.
Referenced by CreateSecondaryItems(), and Execute().
DamagePlayersHands()
void DamagePlayersHands (PlayerBase player) inline private
Definition at line 243 of file CAContinuousMineWood.c.
References m_AdjustedDamageToMiningItemEachDrop, and Math::RandomIntInclusive().
Referenced by Execute().
Execute()
override int Execute (ActionData action_data) inline private
Definition at line 56 of file CAContinuousMineWood.c.
References Class::CastTo(), CreatePrimaryItems(), CreateSecondaryItems(), DamagePlayersHands(), GetGame(), m_AdjustedDamageToMiningItemEachDrop, m_AdjustedTimeBetweenMaterialDrops, m_AmountOfDrops, m_DataLoaded, ActionData::m_MainItem, ActionData::m_Player, m_SpentUnits, ActionData::m_Target, m_TimeElpased, CAContinuousBase::OnCompletePogress(), CABase::SetACData(), UA_ERROR, UA_FINISHED, UA_PROCESSING, and WoodBase().
GetMiningData()
bool GetMiningData (ActionData action_data) inline private
Definition at line 143 of file CAContinuousMineWood.c.
References Class::CastTo(), CABase::m_Action, m_AdjustedDamageToMiningItemEachDrop, m_AmountOfDrops, m_CycleTimeOverride, m_DamageToMiningItemEachDrop, MineActionData::m_HarvestType, ActionData::m_MainItem, m_MaterialAndQuantityMap, ActionData::m_Player, ActionData::m_Target, and WoodBase().
Referenced by Setup().
GetProgress()
override float GetProgress () inline private
Definition at line 125 of file CAContinuousMineWood.c.
References m_AdjustedTimeBetweenMaterialDrops, and m_TimeElpased.
Setup()
override void Setup (ActionData action_data) inline private
Definition at line 26 of file CAContinuousMineWood.c.
References GetMiningData(), CABase::m_Action, m_AdjustedTimeBetweenMaterialDrops, m_AmountOfDrops, m_CycleTimeOverride, m_DataLoaded, ActionData::m_MainItem, m_MaterialAndQuantityMap, ActionData::m_Player, m_SpentUnits, m_TimeBetweenMaterialDrops, m_TimeElpased, and m_TimeToComplete.
Field Documentation
m_AdjustedDamageToMiningItemEachDrop
protected float m_AdjustedDamageToMiningItemEachDrop private
Definition at line 8 of file CAContinuousMineWood.c.
Referenced by DamagePlayersHands(), Execute(), CAContinuousMineRock::GetMiningData(), and GetMiningData().
m_AdjustedTimeBetweenMaterialDrops
protected float m_AdjustedTimeBetweenMaterialDrops private
Definition at line 4 of file CAContinuousMineWood.c.
Referenced by Execute(), GetProgress(), and Setup().
m_AmountOfDrops
protected int m_AmountOfDrops private
Definition at line 9 of file CAContinuousMineWood.c.
Referenced by Execute(), CAContinuousMineRock::GetMiningData(), GetMiningData(), and Setup().
m_CycleTimeOverride
protected float m_CycleTimeOverride private
Definition at line 5 of file CAContinuousMineWood.c.
Referenced by CAContinuousMineWood(), GetMiningData(), and Setup().
m_DamageToMiningItemEachDrop
protected float m_DamageToMiningItemEachDrop private
Definition at line 7 of file CAContinuousMineWood.c.
Referenced by CAContinuousMineRock::GetMiningData(), and GetMiningData().
m_DataLoaded
protected bool m_DataLoaded = false private
Definition at line 15 of file CAContinuousMineWood.c.
Referenced by Execute(), and Setup().
m_MaterialAndQuantityMap
protected ref map<string,int> m_MaterialAndQuantityMap private
Definition at line 12 of file CAContinuousMineWood.c.
Referenced by CreatePrimaryItems(), CAContinuousMineRock::GetMiningData(), GetMiningData(), and Setup().
m_MinedItem
protected ItemBase m_MinedItem[MINEDITEM_MAX] private
Definition at line 17 of file CAContinuousMineWood.c.
Referenced by CreatePrimaryItems().
m_SecondaryItem
protected ItemBase m_SecondaryItem private
Definition at line 18 of file CAContinuousMineWood.c.
Referenced by CreateSecondaryItems().
m_SpentUnits
protected ref Param1<float> m_SpentUnits private
Definition at line 14 of file CAContinuousMineWood.c.
Referenced by Execute(), and Setup().
m_TimeBetweenMaterialDrops
protected float m_TimeBetweenMaterialDrops private
Definition at line 6 of file CAContinuousMineWood.c.
Referenced by CAContinuousMineRock::CAContinuousMineRock(), CAContinuousMineWood(), and Setup().
m_TimeElpased
protected float m_TimeElpased private
Definition at line 3 of file CAContinuousMineWood.c.
Referenced by Execute(), GetProgress(), and Setup().
m_TimeToComplete
protected float m_TimeToComplete private
Definition at line 13 of file CAContinuousMineWood.c.
Referenced by Setup().
MINEDITEM_MAX
protected const int MINEDITEM_MAX = 5 private
Definition at line 16 of file CAContinuousMineWood.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousMineWood.c