DayZ Scripts: VicinityContainer Class Reference
VicinityContainer Class Reference
Private Member Functions
void VicinityContainer (LayoutHolder parent, int sort=-1)
bool IsVicinityContainerIconsActive ()
VicinitySlotsContainer GetVicinityIconsContainer ()
bool IsContainerWithCargoActive ()
bool IsItemWithAttachmentsActive ()
bool IsItemWithCategoriesActive ()
void TraverseShowedItems ()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void DraggingOverIcon (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromIcon (Widget w, int x, int y, Widget receiver)
void OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromEmptySpace (Widget w, int x, int y, Widget receiver)
override void UpdateInterval ()
void ToggleContainer (Widget w, EntityAI item)
void ToggleContainer (Container conta)
override void ExpandCollapseContainer ()
override bool OnChildRemove (Widget w, Widget child)
override bool OnChildAdd (Widget w, Widget child)
override void CollapseButtonOnMouseButtonDown (Widget w)
void UpdateHeader (EntityAI entity, Container cont, PlayerBase player)
Updates header dragability to be consistent with current 'icon' behaviour.
Private Attributes
ref VicinitySlotsContainer m_VicinityIconsContainer
ref map< EntityAI, ref Container > m_ShowedItems = new ref map<EntityAI, ref Container>
ref map< int, ref Container > m_ShowedItemsIDs = new ref map<int, ref Container>
ref array< EntityAI > m_ShowedItemIcons = new array<EntityAI>
ref map< CargoBase, ref Container > m_ShowedCargos = new ref map<CargoBase, ref Container>
protected bool m_IsProcessing = false
const float DISTANCE_TO_ENTITIES = 1.0
const float DISTANCE_TO_THE_REST = 0.5
Detailed Description
Definition at line 1 of file VicinityContainer.c.
Constructor & Destructor Documentation
VicinityContainer()
void VicinityContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 13 of file VicinityContainer.c.
References WidgetEventHandler::GetInstance(), CollapsibleContainer::LoadDefaultState(), CollapsibleContainer::m_CollapsibleHeader, m_RootWidget, m_VicinityIconsContainer, WidgetEventHandler::RegisterOnChildAdd(), WidgetEventHandler::RegisterOnChildRemove(), and Header::SetName().
Member Function Documentation
CollapseButtonOnMouseButtonDown()
override void CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 649 of file VicinityContainer.c.
References ItemManager::GetInstance(), CollapsibleContainer::m_Hidden, and ItemManager::SetDefaultHeaderOpenState().
DraggingOverHeader()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 87 of file VicinityContainer.c.
References GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_ShowedItemIcons, name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), and ItemManager::ShowSourceDropzone().
Referenced by LeftArea::DraggingOverHeader().
DraggingOverIcon()
void DraggingOverIcon (Widget w, int x, int y, Widget receiver) inline private
Definition at line 125 of file VicinityContainer.c.
References GameInventory::CanSwapEntitiesEx(), ColorManager::COMBINE_COLOR, ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::GetLeftDropzone(), ItemManager::HideDropzones(), m_ShowedItemIcons, name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and ColorManager::SWAP_COLOR.
ExpandCollapseContainer()
override void ExpandCollapseContainer () inline private
Definition at line 614 of file VicinityContainer.c.
References Container::GetFocusedItem(), m_ShowedItems, and ToggleContainer().
GetVicinityIconsContainer()
VicinitySlotsContainer GetVicinityIconsContainer () inline private
Definition at line 32 of file VicinityContainer.c.
References m_VicinityIconsContainer.
Referenced by UpdateConsoleToolbar().
IsContainerWithCargoActive()
bool IsContainerWithCargoActive () inline private
Definition at line 37 of file VicinityContainer.c.
Referenced by UpdateConsoleToolbar().
IsItemWithAttachmentsActive()
bool IsItemWithAttachmentsActive () inline private
Definition at line 42 of file VicinityContainer.c.
Referenced by UpdateConsoleToolbar().
IsItemWithCategoriesActive()
bool IsItemWithCategoriesActive () inline private
Definition at line 47 of file VicinityContainer.c.
IsVicinityContainerIconsActive()
bool IsVicinityContainerIconsActive () inline private
Definition at line 27 of file VicinityContainer.c.
References m_VicinityIconsContainer.
Referenced by UpdateConsoleToolbar().
OnChildAdd()
override bool OnChildAdd (Widget w, Widget child) inline private
Definition at line 639 of file VicinityContainer.c.
References m_Parent.
OnChildRemove()
override bool OnChildRemove (Widget w, Widget child) inline private
Definition at line 626 of file VicinityContainer.c.
References m_Parent, x, and y.
OnDropReceivedFromEmptySpace()
void OnDropReceivedFromEmptySpace (Widget w, int x, int y, Widget receiver) inline private
Definition at line 306 of file VicinityContainer.c.
References OnDropReceivedFromHeader(), x, and y.
OnDropReceivedFromHeader()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 252 of file VicinityContainer.c.
References GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), ItemManager::HideDropzones(), InventoryMenu(), m_ShowedItemIcons, MENU_INVENTORY, name, string::Replace(), and ItemManager::SetIsDragging().
Referenced by OnDropReceivedFromEmptySpace(), and OnLeftPanelDropReceived().
OnDropReceivedFromIcon()
void OnDropReceivedFromIcon (Widget w, int x, int y, Widget receiver) inline private
Definition at line 184 of file VicinityContainer.c.
References GameInventory::CanSwapEntitiesEx(), CombineItemsClient(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), InventoryLocation::GetType(), ItemManager::HideDropzones(), InventoryMenu(), MENU_INVENTORY, name, string::Replace(), and ItemManager::SetIsDragging().
OnLeftPanelDropReceived()
void OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver) inline private
Definition at line 247 of file VicinityContainer.c.
References OnDropReceivedFromHeader(), x, and y.
Referenced by LeftArea::OnLeftPanelDropReceived().
ToggleContainer() [1/2]
void ToggleContainer (Container conta) inline private
Definition at line 609 of file VicinityContainer.c.
ToggleContainer() [2/2]
void ToggleContainer (Widget w, EntityAI item) inline private
Definition at line 591 of file VicinityContainer.c.
References m_ShowedItems, and ToggleContainer().
Referenced by ExpandCollapseContainer(), and ToggleContainer().
TraverseShowedItems()
void TraverseShowedItems () inline private
Definition at line 52 of file VicinityContainer.c.
References FileSerializer::Close(), m_ShowedItems, FileSerializer::Open(), and Serializer::Write().
UpdateHeader()
void UpdateHeader (EntityAI entity, Container cont, PlayerBase player) inline private
Updates header dragability to be consistent with current 'icon' behaviour.
Definition at line 656 of file VicinityContainer.c.
References CancelWidgetDragging(), ItemManager::EvaluateContainerDragabilityDefault(), GetDragWidget(), Container::GetHeader(), ItemManager::GetInstance(), and ItemManager::SetWidgetDraggable().
Referenced by UpdateInterval().
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 311 of file VicinityContainer.c.
References ConfigIsExisting(), CargoBase::GetCargoOwner(), GetGame(), VicinityItemManager::GetInstance(), CargoBase::GetOwnerCargoIndex(), GetParent(), GetPlayer(), VicinityItemManager::GetVicinityCargos(), VicinityItemManager::GetVicinityItems(), Inventory(), EntityAI::IsInventoryVisible(), GameInventory::IsPlaceholderEntity(), BaseBuildingBase::IsPlayerInside(), m_Parent, m_ShowedCargos, m_ShowedItemIcons, m_ShowedItems, m_ShowedItemsIDs, m_VicinityIconsContainer, CollapsibleContainer::Refresh(), CollapsibleContainer::Remove(), AttachmentCategoriesContainer::SetEntity(), ContainerWithElectricManager::SetEntity(), ZombieContainer::SetEntity(), PlayerContainer::SetPlayer(), VicinitySlotsContainer::ShowItemsInContainers(), VicinityItemManager::Update(), CollapsibleContainer::UpdateCollapseButtons(), and UpdateHeader().
Field Documentation
DISTANCE_TO_ENTITIES
const float DISTANCE_TO_ENTITIES = 1.0 private
Definition at line 10 of file VicinityContainer.c.
DISTANCE_TO_THE_REST
const float DISTANCE_TO_THE_REST = 0.5 private
Definition at line 11 of file VicinityContainer.c.
m_IsProcessing
protected bool m_IsProcessing = false private
Definition at line 8 of file VicinityContainer.c.
m_ShowedCargos
ref map<CargoBase, ref Container> m_ShowedCargos = new ref map<CargoBase, ref Container> private
Definition at line 7 of file VicinityContainer.c.
Referenced by UpdateInterval().
m_ShowedItemIcons
ref array<EntityAI> m_ShowedItemIcons = new array<EntityAI> private
Definition at line 6 of file VicinityContainer.c.
Referenced by DraggingOverHeader(), DraggingOverIcon(), OnDropReceivedFromHeader(), and UpdateInterval().
m_ShowedItems
ref map<EntityAI, ref Container> m_ShowedItems = new ref map<EntityAI, ref Container> private
Definition at line 4 of file VicinityContainer.c.
Referenced by ExpandCollapseContainer(), ToggleContainer(), TraverseShowedItems(), and UpdateInterval().
m_ShowedItemsIDs
ref map<int, ref Container> m_ShowedItemsIDs = new ref map<int, ref Container> private
Definition at line 5 of file VicinityContainer.c.
Referenced by UpdateInterval().
m_VicinityIconsContainer
ref VicinitySlotsContainer m_VicinityIconsContainer private
Definition at line 3 of file VicinityContainer.c.
Referenced by GetVicinityIconsContainer(), IsVicinityContainerIconsActive(), UpdateInterval(), and VicinityContainer().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Inherited/VicinityContainer.c