DayZ Scripts: CatchingContextPoissonBase Class Reference
CatchingContextPoissonBase Class Reference
Private Member Functions
override protected void ClearCatchingItemData ()
float GetSignalPoissonMean ()
int GetSignalMax ()
maximum number of signals in a single cycle
override bool ModifySignalProbability (inout float probability)
override bool RollCatch ()
float GetChanceCoef ()
Private Attributes
protected float m_SignalPoissonMean
protected int m_SignalCurrent
Member Function Documentation
ClearCatchingItemData()
override protected void ClearCatchingItemData () inline private
References m_SignalCurrent, m_SignalPoissonMean, and AnimalCatchingConstants::POISSON_CYCLE_MEAN_DEFAULT.
GetChanceCoef()
float GetChanceCoef () inline private
Referenced by ModifySignalProbability().
GetSignalMax()
int GetSignalMax () inline private
maximum number of signals in a single cycle
References Math::Ceil(), and m_SignalPoissonMean.
Referenced by ModifySignalProbability().
GetSignalPoissonMean()
float GetSignalPoissonMean () inline private
References m_SignalPoissonMean.
ModifySignalProbability()
override bool ModifySignalProbability (inout float probability) inline private
References GetChanceCoef(), GetSignalMax(), m_SignalCurrent, m_SignalPoissonMean, and Math::Poisson().
RollCatch()
override bool RollCatch () inline private
References m_SignalCurrent.
Referenced by RollNextResultChance().
Field Documentation
m_SignalCurrent
protected int m_SignalCurrent private
Referenced by ClearCatchingItemData(), ModifySignalProbability(), and RollCatch().
m_SignalPoissonMean
protected float m_SignalPoissonMean private
Referenced by ClearCatchingItemData(), CatchingContextFishingRodAction::ClearCatchingItemData(), GetSignalMax(), GetSignalPoissonMean(), CatchingContextFishingRodAction::InitItemValues(), and ModifySignalProbability().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/AnimalCatching/CatchingContextPoissonBase.c