DayZ Scripts: ComponentEnergyManager Class Reference
ComponentEnergyManager Class Reference
Private Member Functions
void ComponentEnergyManager ()
void ~ComponentEnergyManager ()
override void Event_OnInit ()
void DebugUpdate ()
Shape DrawArrow (vector from, vector to, float size=0.5, int color=0xFFFFFFFF, float flags=0)
EntityAI GetThisEntityAI ()
override void Event_OnAwake ()
override int GetCompType ()
void OnDeviceDestroyed ()
void RefreshDebug ()
bool GetDebugPlugs ()
void SetDebugPlugs (bool newVal)
void SwitchOn ()
Energy manager: Switches ON the device so it starts doing its work if it has enough energy.
void SwitchOff ()
Energy manager: Switches OFF the device.
void SetPassiveState (bool state=true)
Energy manager: Changes the status of this device. When it's passive (true), the main timer and OnWork events are not used.
void UnplugDevice (EntityAI device_to_unplug)
Energy manager: Unplugs the given device from this one.
void UnplugThis ()
Energy manager: Unplugs this device from its power source.
void UnplugAllDevices ()
Energy manager: Unplugs everything directly connected to this device.
void RestorePlugState (bool state)
void SetEnergy (float new_energy)
Energy manager: Sets stored energy for this device. It ignores the min/max limit!
void SetEnergy0To1 (float energy01)
Energy manager: Sets stored energy for this device between 0 and MAX based on relative input value between 0 and 1.
void UpdateSelections ()
Energy manager: Shows/Hides all selections this system works with. Call this if something is wrong with selections (like during Init and Restore event in config)
void UpdatePlugState ()
Energy manager: Unplugs this device when it's necesarry.
void GetCompatiblePlugTypes (out TIntArray IDs)
void StoreEnergySourceIDs (int b1, int b2, int b3, int b4)
void SetEnergyMaxPristine (float new_limit)
Energy manager: Changes the maximum amount of energy this device can store (when pristine).
void SetCordLength (float new_length)
Energy manager: Changes the length of the virtual power cord.
void SetPlugType (int new_type)
void SetAttachmentAction (int new_action_type)
void SetEnergyUsage (float new_usage)
Energy manager: Changes the energy usage per second.
void ResetEnergyUsage ()
Energy manager: Resets energy usage to default (config) value.
void SetCordTextureFile (string new_path)
void SetEnergySourceClient (EntityAI source)
void SetDeviceBySocketID (int id, EntityAI plugged_device)
Energy manager: Stores the device which is plugged into the given socket ID.
void SetElectricityIconVisibility (bool make_visible)
Energy manager: Sets visibility of the electricity icon (bolt).
void UpdateCanWork ()
void HandleMoveInsideCargo (EntityAI container)
void SetUpdateInterval (float value)
Energy manager: Sets the interval of the OnWork(...) calls. Changing this value does not change the rate of energy consumption.
bool GetRestorePlugState ()
bool PlugThisInto (EntityAI energy_source, int socket_id=-1)
Energy manager: Attempts to plug this device into the energy_source. Returns true if the action was successfull, or false if not (due to plug incompatibility or no free socket on the receiver). The ID of the power socket is chosen automatically unless optional parameter socket_id is used (starting from 0). If the given ID is not free then a free socket is found.
bool CanSwitchOn ()
Energy manager: Checks if the device can be switched ON.
bool CanWork (float test_energy=-1)
Energy manager: Checks whenever this device can do work or not.
bool CheckWetness ()
Energy manager: Checks if this device is being stopped from working by its wetness level. Returns true when its wetness is not blocking it, false when its to owet to work.
bool CanSwitchOff ()
Energy manager: Checks if the device can be switched OFF.
bool GetPreviousSwitchState ()
bool IsSwitchedOn ()
Energy manager: Returns state of the switch. Whenever the device is working or not does not matter. Use IsWorking() to account for that as well.
bool IsCordFolded ()
Energy manager: Returns true if the cord of this device is folded. Returns false if it's plugged.
bool IsPassive ()
Energy manager: Returns true if this device is set to be passive. False if otherwise.
bool IsPlugged ()
Energy manager: Returns true if this device is plugged into some other device (even if they are OFF or ruined). Otherwise it returns false.
bool ConsumeEnergy (float amount)
Energy manager: Consumes the given amount of energy. If there is not enough of stored energy in this device, then it tries to take it from its power source, if any exists. Returns true if the requested amount of energy was consumed. Otherwise it returns false.
bool IsWorking ()
Energy manager: Returns true if this device is working right now.
bool HasEnoughStoredEnergy ()
Energy manager: Returns true if this device has enough of stored energy for its own use.
bool HasFreeSocket (int socket_id=-1)
Energy manager: Returns true if this device has any free socket to receive a plug. If optional parameter socket_id is provided then only that socket ID is checked.
bool IsPlugCompatible (int plug_ID)
Energy manager: Checks if the given plug is compatible with this device's socket. Used by CanReceivePlugFrom() method.
bool CanReceivePlugFrom (EntityAI device_to_plug)
Energy manager: Returns true if this device can receive power plug of the other device.
bool CanBePluggedInto (EntityAI potential_energy_provider)
Energy manager: Returns true if this device can be plugged into the given energy source. Otherwise returns false.
bool HasElectricityIcon ()
Energy manager: Returns true if the electricity icon (bolt) is supposed to be visible for this device. False if not.
bool HasConversionOfEnergyToQuantity ()
Energy manager: Returns true if this item automatically converts its energy to quantity.
bool IsEnergySourceAtReach (vector from_position, float add_tolerance=0, vector override_source_position="-1 -1 -1")
Energy manager: Returns true if this device's virtual power cord can reach its energy source at the given position, depending on its cordLength config parameter. Otherwise returns false.
bool HasVisibleSocketsInInventory ()
bool IsSelectionAPlug (string selection_to_test)
Energy manager: Returns true if this selection is a plug that's plugged into this device. Otherwise returns false.
int GetSocketsCount ()
Energy manager: Returns the count of power sockets (whenever used or not)
int GetPlugType ()
Energy manager: Returns plug type. Check \DZ\data\basicDefines.hpp OR \Scripts\Classes\Component_constants.h files for types of plugs.
int GetAttachmentAction ()
int GetEnergySourceStorageIDb1 ()
int GetEnergySourceStorageIDb2 ()
int GetEnergySourceStorageIDb3 ()
int GetEnergySourceStorageIDb4 ()
int GetEnergySourceNetworkIDLow ()
int GetEnergySourceNetworkIDHigh ()
int GetPluggedDevicesCount ()
Energy manager: Returns the number of devices plugged into this one.
int GetEnergy0To100 ()
Energy manager: Returns % of stored energy this device has as integer (from 0 to 100)
float GetEnergy0To1 ()
Energy manager: Returns % of stored energy this device has as float (from 0.0 to 1.0)
float GetUpdateInterval ()
Energy manager: Returns the update interval of this device.
float GetWetnessExposure ()
Returns wetness exposure value defined in config.
float GetEnergyUsage ()
Energy manager: Returns the number of energy this device needs to run itself (See its config >> energyUsagePerSecond)
float GetEnergy ()
Energy manager: Returns the amount of stored energy this device has.
float AddEnergy (float added_energy)
Energy manager: Adds energy to this device and clamps it within its min/max storage limits. Returns the amount of energy that was clamped. Negative value is supported, but you should still use ConsumeEnergy(...) for propper substraction of energy.
float GetEnergyMax ()
Energy manager: Returns the maximum amount of energy this device can curently store. If parameter 'reduceMaxEnergyByDamageCoef' is used in the config of this device then the returned value will be reduced by damage.
float GetEnergyMaxPristine ()
Energy manager: Returns the maximum amount of energy this device can store. It's damage is NOT taken into account.
float GetEnergyAtSpawn ()
float GetCordLength ()
Energy manager: Returns the length of the virtual power cord.
EntityAI GetEnergySource ()
Energy manager: Returns the energy source this device is plugged into.
EntityAI GetDeviceBySocketID (int id)
Energy manager: Returns the device which is plugged into the given socket ID.
EntityAI GetPlugOwner (string plug_selection_name)
Energy manager: Returns the device to which the given plug selection belongs to.
EntityAI GetPluggedDevice ()
Energy manager: Returns a device which is plugged into this one. If there are more devices to choose from then it returns the first one that is found.
string GetCordTextureFile ()
Energy manager: Returns path to the cord texture file.
array< EntityAI > GetPluggedDevices ()
Energy manager: Returns an array of devices which are plugged into this one.
array< EntityAI > GetPoweredDevices ()
Energy manager: Returns an array of devices which are plugged into this one and are turned on.
void OnWork (float consumed_energy)
void OnIsPlugged (EntityAI source_device)
void OnIsUnplugged (EntityAI last_energy_source)
void OnOwnSocketTaken (EntityAI device)
void OnOwnSocketReleased (EntityAI device)
void OnAttachmentAdded (EntityAI elec_device)
void OnAttachmentRemoved (EntityAI elec_device)
void StartUpdates ()
void OnEnergyConsumed ()
Energy manager: Called when energy was consumed on this device.
void OnEnergyAdded ()
Energy manager: Called when energy was added on this device.
protected void StopUpdates ()
void InteractBranch (EntityAI originalCaller, Man player=null, int system=0)
protected void OnInteractBranch (EntityAI originalCaller, Man player, int system)
Called when the player is interacting with an item containing this energy component, or when interacting with an item this device is connected to.
protected void WakeUpWholeBranch (EntityAI original_caller)
protected void PlugCordIntoSocket (EntityAI device_to_plug, int socket_id=-1)
protected void UpdateSocketSelections (int socket_id, EntityAI device_to_plug)
protected void SetEnergySource (EntityAI source)
protected bool PlugInDevice (EntityAI device_to_plug, int socket_id=-1)
protected void SetPlugOwner (string selection_name, EntityAI device)
protected void UnplugCordFromSocket (int socket_to_unplug_ID)
protected void SetPowered (bool state)
protected bool FindAndConsumeEnergy (EntityAI original_caller, float amount, bool ignore_switch_state=false)
protected int GetMySocketID ()
protected void SetMySocketID (int slot_ID)
void Synch ()
void ClearLastUpdateTime ()
void RememberLastUpdateTime ()
float GetCurrentUpdateTime ()
void DeviceUpdate ()
Private Attributes
protected const float DEFAULT_UPDATE_INTERVAL = 15
protected Shape m_DebugPlugArrow
protected bool m_IsSwichedOn
protected bool m_IsSwichedOnPreviousState
protected bool m_IsPassiveDevice
protected bool m_IsWorking
protected bool m_CanWork
protected bool m_CanStopWork
protected bool m_RestorePlugState
protected bool m_AutoSwitchOff
protected bool m_ShowSocketsInInventory
protected bool m_HasElectricityIcon
protected bool m_AutoSwitchOffWhenInCargo
protected bool m_IsPlugged
protected bool m_ConvertEnergyToQuantity
protected int m_MySocketID = -1
protected int m_PlugType
protected int m_EnergySourceStorageIDb1
protected int m_EnergySourceStorageIDb2
protected int m_EnergySourceStorageIDb3
protected int m_EnergySourceStorageIDb4
protected int m_AttachmentActionType
protected int m_EnergySourceNetworkIDLow = -1
protected int m_EnergySourceNetworkIDHigh = -1
protected float m_EnergyUsage
protected float m_Energy
protected float m_EnergyAtSpawn
protected float m_EnergyStorageMax
protected float m_ReduceMaxEnergyByDamageCoef
protected float m_SocketsCount
protected float m_CordLength
protected float m_LastUpdateTime
protected float m_WetnessExposure
protected float m_UpdateInterval
protected string m_CordTextureFile
protected ref TIntArray m_CompatiblePlugTypes
EntityAI m_EnergySource
ref array< EntityAI > m_PluggedDevices
ref map< string, EntityAI > m_DeviceByPlugSelection
ref Timer m_UpdateTimer
ref Timer m_UpdateQuantityTimer
ref Timer m_DebugUpdate
const int MAX_SOCKETS_COUNT = 4
EntityAI m_Sockets [MAX_SOCKETS_COUNT]
Static Private Attributes
static protected bool m_DebugPlugs = false
static protected const string SOCKET_ = "socket_"
static protected const string _PLUGGED = "_plugged"
static protected const string _AVAILABLE = "_available"
static const string SEL_CORD_PLUGGED = "cord_plugged"
static const string SEL_CORD_FOLDED = "cord_folded"
Constructor & Destructor Documentation
ComponentEnergyManager()
void ComponentEnergyManager () inline private
References m_DebugPlugs.
~ComponentEnergyManager()
void ~ComponentEnergyManager () inline private
References m_DebugPlugArrow.
Member Function Documentation
AddEnergy()
float AddEnergy (float added_energy) inline private
Energy manager: Adds energy to this device and clamps it within its min/max storage limits. Returns the amount of energy that was clamped. Negative value is supported, but you should still use ConsumeEnergy(...) for propper substraction of energy.
References Math::Clamp(), GetEnergy(), GetEnergyMax(), OnEnergyAdded(), OnEnergyConsumed(), SetEnergy(), and StartUpdates().
Referenced by FindAndConsumeEnergy(), and ItemBase::OnIgnitedTarget().
CanBePluggedInto()
bool CanBePluggedInto (EntityAI potential_energy_provider) inline private
Energy manager: Returns true if this device can be plugged into the given energy source. Otherwise returns false.
References Component::m_ThisEntityAI.
CanReceivePlugFrom()
bool CanReceivePlugFrom (EntityAI device_to_plug) inline private
Energy manager: Returns true if this device can receive power plug of the other device.
References HasFreeSocket(), IsPlugCompatible(), and Component::m_ThisEntityAI.
Referenced by PlugInDevice().
CanSwitchOff()
bool CanSwitchOff () inline private
Energy manager: Checks if the device can be switched OFF.
References IsPassive(), and IsSwitchedOn().
Referenced by SwitchOff().
CanSwitchOn()
bool CanSwitchOn () inline private
Energy manager: Checks if the device can be switched ON.
References IsSwitchedOn().
Referenced by SwitchOn().
CanWork()
bool CanWork (float test_energy = -1) inline private
Energy manager: Checks whenever this device can do work or not.
Parameters
test_energy float optional parameter will overwite the default energy consumption value of this device.
Returns
bool Returns true if this device will work when it's switched on. Otherwise it returns false.
References CheckWetness(), DPrint(), GetEnergy(), GetEnergySource(), GetEnergyUsage(), GetGame(), m_CanWork, and Component::m_ThisEntityAI.
Referenced by UpdateCanWork().
CheckWetness()
bool CheckWetness () inline private
Energy manager: Checks if this device is being stopped from working by its wetness level. Returns true when its wetness is not blocking it, false when its to owet to work.
References Component::m_ThisEntityAI, and m_WetnessExposure.
Referenced by CanWork(), and DeviceUpdate().
ClearLastUpdateTime()
void ClearLastUpdateTime () inline private
References m_LastUpdateTime.
Referenced by DeviceUpdate().
ConsumeEnergy()
bool ConsumeEnergy (float amount) inline private
Energy manager: Consumes the given amount of energy. If there is not enough of stored energy in this device, then it tries to take it from its power source, if any exists. Returns true if the requested amount of energy was consumed. Otherwise it returns false.
References FindAndConsumeEnergy(), and Component::m_ThisEntityAI.
Referenced by DeviceUpdate().
DebugUpdate()
void DebugUpdate () inline private
References vector::DistanceSq(), DrawArrow(), GetDebugPlugs(), GetEnergySource(), GetGame(), m_DebugPlugArrow, m_DebugUpdate, Component::m_ThisEntityAI, and Timer::Stop().
DeviceUpdate()
void DeviceUpdate () inline private
References ScriptModule::CallFunction(), CheckWetness(), ClearLastUpdateTime(), ConsumeEnergy(), CGame::GameScript, GetCurrentUpdateTime(), GetEnergyUsage(), GetGame(), IsSwitchedOn(), IsWorking(), m_AutoSwitchOff, m_CanStopWork, m_CanWork, m_IsPassiveDevice, m_LastUpdateTime, Component::m_ThisEntityAI, OnWork(), RememberLastUpdateTime(), SetPowered(), StopUpdates(), SwitchOff(), UpdateCanWork(), and WakeUpWholeBranch().
Referenced by Entity::OnVariablesSynchronized(), SetPassiveState(), SwitchOff(), and SwitchOn().
DrawArrow()
Shape DrawArrow (vector from, vector to, float size = 0.5, int color = 0xFFFFFFFF, float flags = 0) inline private
References vector::Normalize(), vector::Perpend(), and Shape.
Referenced by DebugUpdate().
Event_OnAwake()
override void Event_OnAwake () inline private
References _PLUGGED, CALL_CATEGORY_SYSTEM, CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetIntArray(), CGame::ConfigGetText(), DEFAULT_UPDATE_INTERVAL, DPrint(), Error(), GetGame(), GetSocketsCount(), HasEnoughStoredEnergy(), IsPlugCompatible(), m_AttachmentActionType, m_AutoSwitchOff, m_AutoSwitchOffWhenInCargo, m_CanWork, m_CompatiblePlugTypes, m_ConvertEnergyToQuantity, m_CordLength, m_CordTextureFile, m_DeviceByPlugSelection, m_Energy, m_EnergyAtSpawn, m_EnergyStorageMax, m_EnergyUsage, m_HasElectricityIcon, m_IsPassiveDevice, m_PluggedDevices, m_PlugType, m_ReduceMaxEnergyByDamageCoef, m_ShowSocketsInInventory, m_Sockets, m_SocketsCount, Component::m_ThisEntityAI, m_UpdateQuantityTimer, m_WetnessExposure, MAX_SOCKETS_COUNT, PLUG_COMMON_APPLIANCE, SEL_CORD_PLUGGED, SetUpdateInterval(), SOCKET_, SwitchOn(), and string::ToString().
Event_OnInit()
override void Event_OnInit () inline private
References ScriptModule::CallFunction(), CGame::GameScript, GetGame(), and Component::m_ThisEntityAI.
FindAndConsumeEnergy()
protected bool FindAndConsumeEnergy (EntityAI original_caller, float amount, bool ignore_switch_state = false) inline private
References AddEnergy(), GetEnergySource(), IsPlugged(), IsSwitchedOn(), and Component::m_ThisEntityAI.
Referenced by ConsumeEnergy().
GetAttachmentAction()
int GetAttachmentAction () inline private
References m_AttachmentActionType.
Referenced by OnAttachmentAdded(), and OnAttachmentRemoved().
GetCompatiblePlugTypes()
void GetCompatiblePlugTypes (out TIntArray IDs) inline private
References m_CompatiblePlugTypes.
GetCompType()
override int GetCompType () inline private
References COMP_TYPE_ENERGY_MANAGER.
GetCordLength()
float GetCordLength () inline private
Energy manager: Returns the length of the virtual power cord.
References m_CordLength.
Referenced by IsEnergySourceAtReach().
GetCordTextureFile()
string GetCordTextureFile () inline private
Energy manager: Returns path to the cord texture file.
References m_CordTextureFile.
GetCurrentUpdateTime()
float GetCurrentUpdateTime () inline private
References GetGame(), and CGame::GetTime().
Referenced by DeviceUpdate(), and RememberLastUpdateTime().
GetDebugPlugs()
bool GetDebugPlugs () inline private
References m_DebugPlugs.
Referenced by DebugUpdate().
GetDeviceBySocketID()
EntityAI GetDeviceBySocketID (int id) inline private
Energy manager: Returns the device which is plugged into the given socket ID.
References m_Sockets.
Referenced by HasFreeSocket(), PlugCordIntoSocket(), UnplugCordFromSocket(), and UpdateSelections().
GetEnergy()
float GetEnergy () inline private
Energy manager: Returns the amount of stored energy this device has.
References m_Energy.
Referenced by AddEnergy(), CanWork(), ItemBase::HasEnoughEnergyForRepair(), HasEnoughStoredEnergy(), Entity::OnStoreSave(), and TransferItemVariables().
GetEnergy0To1()
float GetEnergy0To1 () inline private
Energy manager: Returns % of stored energy this device has as float (from 0.0 to 1.0)
References m_Energy, and m_EnergyStorageMax.
GetEnergy0To100()
int GetEnergy0To100 () inline private
Energy manager: Returns % of stored energy this device has as integer (from 0 to 100)
References m_Energy, m_EnergyStorageMax, and Math::Round().
GetEnergyAtSpawn()
float GetEnergyAtSpawn () inline private
References m_EnergyAtSpawn.
Referenced by InventoryItem::SetCEBasedQuantity().
GetEnergyMax()
float GetEnergyMax () inline private
Energy manager: Returns the maximum amount of energy this device can curently store. If parameter 'reduceMaxEnergyByDamageCoef' is used in the config of this device then the returned value will be reduced by damage.
References GetEnergyMaxPristine(), GetGame(), m_ReduceMaxEnergyByDamageCoef, and Component::m_ThisEntityAI.
Referenced by AddEnergy(), and SetEnergy0To1().
GetEnergyMaxPristine()
float GetEnergyMaxPristine () inline private
Energy manager: Returns the maximum amount of energy this device can store. It's damage is NOT taken into account.
References m_EnergyStorageMax.
Referenced by GetEnergyMax(), and InventoryItem::SetCEBasedQuantity().
GetEnergySource()
EntityAI GetEnergySource () inline private
Energy manager: Returns the energy source this device is plugged into.
References m_EnergySource.
Referenced by CanWork(), DebugUpdate(), FindAndConsumeEnergy(), Entity::GetDebugText(), IsEnergySourceAtReach(), OnAttachmentRemoved(), Entity::OnStoreSave(), UnplugThis(), and UpdateSelections().
GetEnergySourceNetworkIDHigh()
int GetEnergySourceNetworkIDHigh () inline private
References m_EnergySourceNetworkIDHigh.
Referenced by Entity::OnVariablesSynchronized().
GetEnergySourceNetworkIDLow()
int GetEnergySourceNetworkIDLow () inline private
References m_EnergySourceNetworkIDLow.
Referenced by Entity::OnVariablesSynchronized().
GetEnergySourceStorageIDb1()
int GetEnergySourceStorageIDb1 () inline private
References m_EnergySourceStorageIDb1.
Referenced by Entity::EEOnAfterLoad().
GetEnergySourceStorageIDb2()
int GetEnergySourceStorageIDb2 () inline private
References m_EnergySourceStorageIDb2.
Referenced by Entity::EEOnAfterLoad().
GetEnergySourceStorageIDb3()
int GetEnergySourceStorageIDb3 () inline private
References m_EnergySourceStorageIDb3.
Referenced by Entity::EEOnAfterLoad().
GetEnergySourceStorageIDb4()
int GetEnergySourceStorageIDb4 () inline private
References m_EnergySourceStorageIDb4.
Referenced by Entity::EEOnAfterLoad().
GetEnergyUsage()
float GetEnergyUsage () inline private
Energy manager: Returns the number of energy this device needs to run itself (See its config >> energyUsagePerSecond)
References m_EnergyUsage.
Referenced by CanWork(), DeviceUpdate(), HasEnoughStoredEnergy(), and SetEnergy().
GetMySocketID()
protected int GetMySocketID () inline private
References m_MySocketID.
GetPluggedDevice()
EntityAI GetPluggedDevice () inline private
Energy manager: Returns a device which is plugged into this one. If there are more devices to choose from then it returns the first one that is found.
References GetPluggedDevices(), and GetPluggedDevicesCount().
GetPluggedDevices()
array< EntityAI > GetPluggedDevices () inline private
Energy manager: Returns an array of devices which are plugged into this one.
References m_PluggedDevices.
Referenced by GetPluggedDevice(), GetPluggedDevicesCount(), GetPoweredDevices(), InteractBranch(), IsSelectionAPlug(), PlugInDevice(), UnplugAllDevices(), UnplugDevice(), and WakeUpWholeBranch().
GetPluggedDevicesCount()
int GetPluggedDevicesCount () inline private
Energy manager: Returns the number of devices plugged into this one.
References GetPluggedDevices().
Referenced by GetPluggedDevice(), GetPoweredDevices(), HasFreeSocket(), UnplugAllDevices(), and UnplugDevice().
GetPlugOwner()
EntityAI GetPlugOwner (string plug_selection_name) inline private
Energy manager: Returns the device to which the given plug selection belongs to.
References m_DeviceByPlugSelection.
GetPlugType()
int GetPlugType () inline private
Energy manager: Returns plug type. Check \DZ\data\basicDefines.hpp OR \Scripts\Classes\Component_constants.h files for types of plugs.
References m_PlugType.
GetPoweredDevices()
array< EntityAI > GetPoweredDevices () inline private
Energy manager: Returns an array of devices which are plugged into this one and are turned on.
References GetPluggedDevices(), GetPluggedDevicesCount(), and IsSwitchedOn().
GetPreviousSwitchState()
bool GetPreviousSwitchState () inline private
References m_IsSwichedOnPreviousState.
Referenced by Entity::OnVariablesSynchronized().
GetRestorePlugState()
bool GetRestorePlugState () inline private
References m_RestorePlugState.
Referenced by Entity::EEOnAfterLoad().
GetSocketsCount()
int GetSocketsCount () inline private
Energy manager: Returns the count of power sockets (whenever used or not)
References m_SocketsCount.
Referenced by Event_OnAwake(), HasFreeSocket(), InteractBranch(), IsSelectionAPlug(), PlugCordIntoSocket(), UpdateSelections(), and WakeUpWholeBranch().
GetThisEntityAI()
EntityAI GetThisEntityAI () inline private
References Component::m_ThisEntityAI.
GetUpdateInterval()
float GetUpdateInterval () inline private
Energy manager: Returns the update interval of this device.
References m_UpdateInterval.
Referenced by StartUpdates().
GetWetnessExposure()
float GetWetnessExposure () inline private
Returns wetness exposure value defined in config.
References m_WetnessExposure.
HandleMoveInsideCargo()
void HandleMoveInsideCargo (EntityAI container) inline private
References IsSwitchedOn(), m_AutoSwitchOffWhenInCargo, and SwitchOff().
Referenced by Entity::OnMovedInsideCargo().
HasConversionOfEnergyToQuantity()
bool HasConversionOfEnergyToQuantity () inline private
Energy manager: Returns true if this item automatically converts its energy to quantity.
References m_ConvertEnergyToQuantity.
HasElectricityIcon()
bool HasElectricityIcon () inline private
Energy manager: Returns true if the electricity icon (bolt) is supposed to be visible for this device. False if not.
References m_HasElectricityIcon.
HasEnoughStoredEnergy()
bool HasEnoughStoredEnergy () inline private
Energy manager: Returns true if this device has enough of stored energy for its own use.
References GetEnergy(), and GetEnergyUsage().
Referenced by Event_OnAwake().
HasFreeSocket()
bool HasFreeSocket (int socket_id = -1) inline private
Energy manager: Returns true if this device has any free socket to receive a plug. If optional parameter socket_id is provided then only that socket ID is checked.
References GetDeviceBySocketID(), GetPluggedDevicesCount(), and GetSocketsCount().
Referenced by CanReceivePlugFrom().
HasVisibleSocketsInInventory()
bool HasVisibleSocketsInInventory () inline private
References m_ShowSocketsInInventory.
InteractBranch()
void InteractBranch (EntityAI originalCaller, Man player = null, int system = 0) inline private
Gets called originally when the player is interacting with an item containing this energy component, then recursively following the branches of connection from the original item to the peripheries External calling of this function is not automatic for all item interactions and may need to be implemented on case by case bases Avoid using for gameplay logic, use 'OnInteractBranch' instead
References GetPluggedDevices(), GetSocketsCount(), and OnInteractBranch().
Referenced by PlugInDevice().
IsCordFolded()
bool IsCordFolded () inline private
Energy manager: Returns true if the cord of this device is folded. Returns false if it's plugged.
References IsPlugged().
IsEnergySourceAtReach()
bool IsEnergySourceAtReach (vector from_position, float add_tolerance = 0, vector override_source_position = "-1 -1 -1") inline private
Energy manager: Returns true if this device's virtual power cord can reach its energy source at the given position, depending on its cordLength config parameter. Otherwise returns false.
Parameters
from_position vector position from where the measurement will be taken
add_tolerance float parameter will add to the cord's length in meters (optional)
Returns
bool True if the power source will be at reach for the plug, or if config param cordLength is absent or 0. False if not, or is not plugged, or this device lacks Energy Manager component.
vector position_player = GetGame().GetPlayer().GetPosition();
if (my_device.GetCompEM().IsEnergySourceAtReach(position_player))
{
    Print("Power source is at reach!");
}else{
    Print("Power source is NOT at reach!");
}
References vector::Distance(), GetCordLength(), GetEnergySource(), and IsPlugged().
Referenced by Hologram::CorrectMaterialPathName(), and UpdatePlugState().
IsPassive()
bool IsPassive () inline private
Energy manager: Returns true if this device is set to be passive. False if otherwise.
References m_IsPassiveDevice.
Referenced by CanSwitchOff(), and Entity::OnStoreSave().
IsPlugCompatible()
bool IsPlugCompatible (int plug_ID) inline private
Energy manager: Checks if the given plug is compatible with this device's socket. Used by CanReceivePlugFrom() method.
References m_CompatiblePlugTypes, and PLUG_UNDEFINED.
Referenced by CanReceivePlugFrom(), and Event_OnAwake().
IsPlugged()
bool IsPlugged () inline private
Energy manager: Returns true if this device is plugged into some other device (even if they are OFF or ruined). Otherwise it returns false.
References m_IsPlugged.
Referenced by Hologram::CorrectMaterialPathName(), FindAndConsumeEnergy(), IsCordFolded(), IsEnergySourceAtReach(), and Entity::OnStoreSave().
IsSelectionAPlug()
bool IsSelectionAPlug (string selection_to_test) inline private
Energy manager: Returns true if this selection is a plug that's plugged into this device. Otherwise returns false.
References _PLUGGED, GetPluggedDevices(), GetSocketsCount(), SOCKET_, and string::ToString().
IsSwitchedOn()
bool IsSwitchedOn () inline private
Energy manager: Returns state of the switch. Whenever the device is working or not does not matter. Use IsWorking() to account for that as well.
References m_IsSwichedOn.
Referenced by CanSwitchOff(), CanSwitchOn(), DeviceUpdate(), FindAndConsumeEnergy(), Entity::GetDebugText(), GetPoweredDevices(), HandleMoveInsideCargo(), Entity::OnStoreSave(), Entity::OnVariablesSynchronized(), and TransferItemVariables().
IsWorking()
bool IsWorking () inline private
Energy manager: Returns true if this device is working right now.
References m_IsWorking.
Referenced by DeviceUpdate(), Entity::GetDebugText(), Entity::IsIgnited(), and SwitchOff().
OnAttachmentAdded()
void OnAttachmentAdded (EntityAI elec_device) inline private
References GetAttachmentAction(), Component::m_ThisEntityAI, PLUG_ATTACHMENTS_INTO_THIS, PLUG_THIS_INTO_ATTACHMENT, and PlugThisInto().
Referenced by Entity::EEItemAttached().
OnAttachmentRemoved()
void OnAttachmentRemoved (EntityAI elec_device) inline private
References GetAttachmentAction(), GetEnergySource(), PLUG_ATTACHMENTS_INTO_THIS, PLUG_THIS_INTO_ATTACHMENT, and UnplugThis().
Referenced by Entity::EEItemDetached().
OnDeviceDestroyed()
void OnDeviceDestroyed () inline private
References Component::m_ThisEntityAI, SetPowered(), SwitchOff(), UnplugAllDevices(), and UnplugThis().
Referenced by Entity::EEDelete().
OnEnergyAdded()
void OnEnergyAdded () inline private
Energy manager: Called when energy was added on this device.
References Component::m_ThisEntityAI, m_UpdateQuantityTimer, and Timer::Stop().
Referenced by AddEnergy().
OnEnergyConsumed()
void OnEnergyConsumed () inline private
Energy manager: Called when energy was consumed on this device.
References Component::m_ThisEntityAI.
Referenced by AddEnergy().
OnInteractBranch()
protected void OnInteractBranch (EntityAI originalCaller, Man player, int system) inline private
Called when the player is interacting with an item containing this energy component, or when interacting with an item this device is connected to.
References Component::m_ThisEntityAI.
Referenced by InteractBranch().
OnIsPlugged()
void OnIsPlugged (EntityAI source_device) inline private
References CALL_CATEGORY_SYSTEM, m_DebugPlugs, m_DebugUpdate, Component::m_ThisEntityAI, and UpdateCanWork().
OnIsUnplugged()
void OnIsUnplugged (EntityAI last_energy_source) inline private
References Component::m_ThisEntityAI, and UpdateCanWork().
OnOwnSocketReleased()
void OnOwnSocketReleased (EntityAI device) inline private
References Component::m_ThisEntityAI, and PLUG_COMMON_APPLIANCE.
Referenced by UnplugDevice().
OnOwnSocketTaken()
void OnOwnSocketTaken (EntityAI device) inline private
References Component::m_ThisEntityAI, and PLUG_COMMON_APPLIANCE.
Referenced by PlugInDevice().
OnWork()
void OnWork (float consumed_energy) inline private
References Component::m_ThisEntityAI.
Referenced by DeviceUpdate().
PlugCordIntoSocket()
protected void PlugCordIntoSocket (EntityAI device_to_plug, int socket_id = -1) inline private
References GetDeviceBySocketID(), GetSocketsCount(), and UpdateSocketSelections().
Referenced by PlugInDevice().
PlugInDevice()
protected bool PlugInDevice (EntityAI device_to_plug, int socket_id = -1) inline private
References CanReceivePlugFrom(), GetGame(), GetPluggedDevices(), InteractBranch(), Component::m_ThisEntityAI, OnOwnSocketTaken(), PlugCordIntoSocket(), SEL_CORD_FOLDED, SEL_CORD_PLUGGED, and WakeUpWholeBranch().
PlugThisInto()
bool PlugThisInto (EntityAI energy_source, int socket_id = -1) inline private
Energy manager: Attempts to plug this device into the energy_source. Returns true if the action was successfull, or false if not (due to plug incompatibility or no free socket on the receiver). The ID of the power socket is chosen automatically unless optional parameter socket_id is used (starting from 0). If the given ID is not free then a free socket is found.
References Component::m_ThisEntityAI.
Referenced by Entity::EEOnAfterLoad(), OnAttachmentAdded(), and Entity::OnVariablesSynchronized().
RefreshDebug()
void RefreshDebug () inline private
References CALL_CATEGORY_SYSTEM, m_DebugPlugArrow, m_DebugPlugs, and m_DebugUpdate.
Referenced by SetDebugPlugs().
RememberLastUpdateTime()
void RememberLastUpdateTime () inline private
References GetCurrentUpdateTime(), and m_LastUpdateTime.
Referenced by DeviceUpdate().
ResetEnergyUsage()
void ResetEnergyUsage () inline private
Energy manager: Resets energy usage to default (config) value.
References CGame::ConfigGetFloat(), GetGame(), m_EnergyUsage, and Component::m_ThisEntityAI.
RestorePlugState()
void RestorePlugState (bool state) inline private
References m_RestorePlugState.
Referenced by Entity::OnStoreLoad().
SetAttachmentAction()
void SetAttachmentAction (int new_action_type) inline private
References m_AttachmentActionType.
SetCordLength()
void SetCordLength (float new_length) inline private
Energy manager: Changes the length of the virtual power cord.
References m_CordLength.
SetCordTextureFile()
void SetCordTextureFile (string new_path) inline private
References m_CordTextureFile.
SetDebugPlugs()
void SetDebugPlugs (bool newVal) inline private
References m_DebugPlugs, and RefreshDebug().
SetDeviceBySocketID()
void SetDeviceBySocketID (int id, EntityAI plugged_device) inline private
Energy manager: Stores the device which is plugged into the given socket ID.
References m_Sockets.
Referenced by UnplugCordFromSocket(), and UpdateSocketSelections().
SetElectricityIconVisibility()
void SetElectricityIconVisibility (bool make_visible) inline private
Energy manager: Sets visibility of the electricity icon (bolt).
References m_HasElectricityIcon.
SetEnergy()
void SetEnergy (float new_energy) inline private
Energy manager: Sets stored energy for this device. It ignores the min/max limit!
References GetEnergyUsage(), GetGame(), m_Energy, Component::m_ThisEntityAI, Math::Min(), and UpdateCanWork().
Referenced by AddEnergy(), Entity::OnStoreLoad(), SetEnergy0To1(), and TransferItemVariables().
SetEnergy0To1()
void SetEnergy0To1 (float energy01) inline private
Energy manager: Sets stored energy for this device between 0 and MAX based on relative input value between 0 and 1.
References GetEnergyMax(), Math::Lerp(), and SetEnergy().
Referenced by InventoryItem::SetCEBasedQuantity().
SetEnergyMaxPristine()
void SetEnergyMaxPristine (float new_limit) inline private
Energy manager: Changes the maximum amount of energy this device can store (when pristine).
References m_EnergyStorageMax.
SetEnergySource()
protected void SetEnergySource (EntityAI source) inline private
References m_EnergySource, m_EnergySourceNetworkIDHigh, m_EnergySourceNetworkIDLow, m_IsPlugged, StartUpdates(), and Synch().
Referenced by SetEnergySourceClient().
SetEnergySourceClient()
void SetEnergySourceClient (EntityAI source) inline private
References SetEnergySource().
SetEnergyUsage()
void SetEnergyUsage (float new_usage) inline private
Energy manager: Changes the energy usage per second.
References m_EnergyUsage.
SetMySocketID()
protected void SetMySocketID (int slot_ID) inline private
References m_MySocketID.
SetPassiveState()
void SetPassiveState (bool state = true) inline private
Energy manager: Changes the status of this device. When it's passive (true), the main timer and OnWork events are not used.
References DeviceUpdate(), and m_IsPassiveDevice.
Referenced by Entity::OnStoreLoad().
SetPlugOwner()
protected void SetPlugOwner (string selection_name, EntityAI device) inline private
References m_DeviceByPlugSelection.
Referenced by UnplugCordFromSocket(), and UpdateSocketSelections().
SetPlugType()
void SetPlugType (int new_type) inline private
References m_PlugType.
SetPowered()
protected void SetPowered (bool state) inline private
References m_IsWorking.
Referenced by DeviceUpdate(), and OnDeviceDestroyed().
SetUpdateInterval()
void SetUpdateInterval (float value) inline private
Energy manager: Sets the interval of the OnWork(...) calls. Changing this value does not change the rate of energy consumption.
References m_UpdateInterval.
Referenced by Event_OnAwake().
StartUpdates()
void StartUpdates () inline private
References CALL_CATEGORY_SYSTEM, GetUpdateInterval(), m_IsPassiveDevice, and m_UpdateTimer.
Referenced by AddEnergy(), Entity::OnVariablesSynchronized(), SetEnergySource(), and SwitchOn().
StopUpdates()
protected void StopUpdates () inline private
References m_UpdateTimer, and Timer::Stop().
Referenced by DeviceUpdate(), and SwitchOff().
StoreEnergySourceIDs()
void StoreEnergySourceIDs (int b1, int b2, int b3, int b4) inline private
References m_EnergySourceStorageIDb1, m_EnergySourceStorageIDb2, m_EnergySourceStorageIDb3, and m_EnergySourceStorageIDb4.
Referenced by Entity::OnStoreLoad().
SwitchOff()
void SwitchOff () inline private
Energy manager: Switches OFF the device.
References ScriptModule::CallFunction(), CanSwitchOff(), DeviceUpdate(), CGame::GameScript, GetGame(), IsWorking(), m_IsSwichedOn, m_IsSwichedOnPreviousState, Component::m_ThisEntityAI, StopUpdates(), Synch(), UpdateCanWork(), and WakeUpWholeBranch().
Referenced by DeviceUpdate(), HandleMoveInsideCargo(), OnDeviceDestroyed(), and Entity::OnVariablesSynchronized().
SwitchOn()
void SwitchOn () inline private
Energy manager: Switches ON the device so it starts doing its work if it has enough energy.
References ScriptModule::CallFunction(), CanSwitchOn(), DeviceUpdate(), CGame::GameScript, GetGame(), m_IsSwichedOn, m_IsSwichedOnPreviousState, Component::m_ThisEntityAI, StartUpdates(), Synch(), UpdateCanWork(), and WakeUpWholeBranch().
Referenced by Event_OnAwake(), Entity::OnStoreLoad(), Entity::OnVariablesSynchronized(), and TransferItemVariables().
Synch()
void Synch () inline private
References Component::m_ThisEntityAI.
Referenced by SetEnergySource(), SwitchOff(), SwitchOn(), and UpdateCanWork().
UnplugAllDevices()
void UnplugAllDevices () inline private
Energy manager: Unplugs everything directly connected to this device.
References Get(), GetPluggedDevices(), GetPluggedDevicesCount(), and UnplugDevice().
Referenced by OnDeviceDestroyed().
UnplugCordFromSocket()
protected void UnplugCordFromSocket (int socket_to_unplug_ID) inline private
References _AVAILABLE, _PLUGGED, GetDeviceBySocketID(), Component::m_ThisEntityAI, SetDeviceBySocketID(), SetPlugOwner(), SOCKET_, and ToString().
Referenced by UnplugDevice().
UnplugDevice()
void UnplugDevice (EntityAI device_to_unplug) inline private
Energy manager: Unplugs the given device from this one.
References GetGame(), GetPluggedDevices(), GetPluggedDevicesCount(), m_DebugPlugArrow, m_DebugPlugs, Component::m_ThisEntityAI, OnOwnSocketReleased(), SEL_CORD_FOLDED, SEL_CORD_PLUGGED, and UnplugCordFromSocket().
Referenced by UnplugAllDevices().
UnplugThis()
void UnplugThis () inline private
Energy manager: Unplugs this device from its power source.
References GetEnergySource(), GetGame(), and Component::m_ThisEntityAI.
Referenced by OnAttachmentRemoved(), OnDeviceDestroyed(), Entity::OnVariablesSynchronized(), and UpdatePlugState().
UpdateCanWork()
void UpdateCanWork () inline private
References CanWork(), GetGame(), m_CanWork, Component::m_ThisEntityAI, and Synch().
Referenced by DeviceUpdate(), OnIsPlugged(), OnIsUnplugged(), SetEnergy(), SwitchOff(), and SwitchOn().
UpdatePlugState()
void UpdatePlugState () inline private
Energy manager: Unplugs this device when it's necesarry.
References IsEnergySourceAtReach(), Component::m_ThisEntityAI, and UnplugThis().
UpdateSelections()
void UpdateSelections () inline private
Energy manager: Shows/Hides all selections this system works with. Call this if something is wrong with selections (like during Init and Restore event in config)
References _AVAILABLE, _PLUGGED, GetDeviceBySocketID(), GetEnergySource(), GetSocketsCount(), Component::m_ThisEntityAI, SEL_CORD_FOLDED, SEL_CORD_PLUGGED, SOCKET_, ToString(), and string::ToString().
UpdateSocketSelections()
protected void UpdateSocketSelections (int socket_id, EntityAI device_to_plug) inline private
References _AVAILABLE, _PLUGGED, Component::m_ThisEntityAI, SetDeviceBySocketID(), SetPlugOwner(), SOCKET_, and ToString().
Referenced by PlugCordIntoSocket().
WakeUpWholeBranch()
protected void WakeUpWholeBranch (EntityAI original_caller) inline private
References GetPluggedDevices(), and GetSocketsCount().
Referenced by DeviceUpdate(), PlugInDevice(), SwitchOff(), and SwitchOn().
Field Documentation
_AVAILABLE
protected const string _AVAILABLE = "_available" static private
Referenced by UnplugCordFromSocket(), UpdateSelections(), and UpdateSocketSelections().
_PLUGGED
protected const string _PLUGGED = "_plugged" static private
Referenced by Event_OnAwake(), IsSelectionAPlug(), UnplugCordFromSocket(), UpdateSelections(), and UpdateSocketSelections().
DEFAULT_UPDATE_INTERVAL
protected const float DEFAULT_UPDATE_INTERVAL = 15 private
Referenced by Event_OnAwake().
m_AttachmentActionType
protected int m_AttachmentActionType private
Referenced by Event_OnAwake(), GetAttachmentAction(), and SetAttachmentAction().
m_AutoSwitchOff
protected bool m_AutoSwitchOff private
Referenced by DeviceUpdate(), and Event_OnAwake().
m_AutoSwitchOffWhenInCargo
protected bool m_AutoSwitchOffWhenInCargo private
Referenced by Event_OnAwake(), and HandleMoveInsideCargo().
m_CanStopWork
protected bool m_CanStopWork private
Referenced by DeviceUpdate().
m_CanWork
protected bool m_CanWork private
Referenced by CanWork(), DeviceUpdate(), Event_OnAwake(), and UpdateCanWork().
m_CompatiblePlugTypes
protected ref TIntArray m_CompatiblePlugTypes private
Referenced by Event_OnAwake(), GetCompatiblePlugTypes(), and IsPlugCompatible().
m_ConvertEnergyToQuantity
protected bool m_ConvertEnergyToQuantity private
Referenced by Event_OnAwake(), and HasConversionOfEnergyToQuantity().
m_CordLength
protected float m_CordLength private
Referenced by Event_OnAwake(), GetCordLength(), and SetCordLength().
m_CordTextureFile
protected string m_CordTextureFile private
Referenced by Event_OnAwake(), GetCordTextureFile(), and SetCordTextureFile().
m_DebugPlugArrow
protected Shape m_DebugPlugArrow private
Referenced by DebugUpdate(), RefreshDebug(), UnplugDevice(), and ~ComponentEnergyManager().
m_DebugPlugs
protected bool m_DebugPlugs = false static private
Referenced by ComponentEnergyManager(), GetDebugPlugs(), OnIsPlugged(), RefreshDebug(), SetDebugPlugs(), and UnplugDevice().
m_DebugUpdate
ref Timer m_DebugUpdate private
Referenced by DebugUpdate(), OnIsPlugged(), and RefreshDebug().
m_DeviceByPlugSelection
ref map<string,EntityAI> m_DeviceByPlugSelection private
Referenced by Event_OnAwake(), GetPlugOwner(), and SetPlugOwner().
m_Energy
protected float m_Energy private
Referenced by Event_OnAwake(), GetEnergy(), GetEnergy0To1(), GetEnergy0To100(), and SetEnergy().
m_EnergyAtSpawn
protected float m_EnergyAtSpawn private
Referenced by Event_OnAwake(), and GetEnergyAtSpawn().
m_EnergySource
EntityAI m_EnergySource private
Referenced by GetEnergySource(), and SetEnergySource().
m_EnergySourceNetworkIDHigh
protected int m_EnergySourceNetworkIDHigh = -1 private
Referenced by GetEnergySourceNetworkIDHigh(), and SetEnergySource().
m_EnergySourceNetworkIDLow
protected int m_EnergySourceNetworkIDLow = -1 private
Referenced by GetEnergySourceNetworkIDLow(), and SetEnergySource().
m_EnergySourceStorageIDb1
protected int m_EnergySourceStorageIDb1 private
Referenced by GetEnergySourceStorageIDb1(), and StoreEnergySourceIDs().
m_EnergySourceStorageIDb2
protected int m_EnergySourceStorageIDb2 private
Referenced by GetEnergySourceStorageIDb2(), and StoreEnergySourceIDs().
m_EnergySourceStorageIDb3
protected int m_EnergySourceStorageIDb3 private
Referenced by GetEnergySourceStorageIDb3(), and StoreEnergySourceIDs().
m_EnergySourceStorageIDb4
protected int m_EnergySourceStorageIDb4 private
Referenced by GetEnergySourceStorageIDb4(), and StoreEnergySourceIDs().
m_EnergyStorageMax
protected float m_EnergyStorageMax private
Referenced by Event_OnAwake(), GetEnergy0To1(), GetEnergy0To100(), GetEnergyMaxPristine(), and SetEnergyMaxPristine().
m_EnergyUsage
protected float m_EnergyUsage private
Referenced by Event_OnAwake(), GetEnergyUsage(), ResetEnergyUsage(), and SetEnergyUsage().
m_HasElectricityIcon
protected bool m_HasElectricityIcon private
Referenced by Event_OnAwake(), HasElectricityIcon(), and SetElectricityIconVisibility().
m_IsPassiveDevice
protected bool m_IsPassiveDevice private
Referenced by DeviceUpdate(), Event_OnAwake(), IsPassive(), SetPassiveState(), and StartUpdates().
m_IsPlugged
protected bool m_IsPlugged private
Referenced by IsPlugged(), and SetEnergySource().
m_IsSwichedOn
protected bool m_IsSwichedOn private
Referenced by IsSwitchedOn(), SwitchOff(), and SwitchOn().
m_IsSwichedOnPreviousState
protected bool m_IsSwichedOnPreviousState private
Referenced by GetPreviousSwitchState(), SwitchOff(), and SwitchOn().
m_IsWorking
protected bool m_IsWorking private
Referenced by IsWorking(), and SetPowered().
m_LastUpdateTime
protected float m_LastUpdateTime private
Referenced by ClearLastUpdateTime(), DeviceUpdate(), and RememberLastUpdateTime().
m_MySocketID
protected int m_MySocketID = -1 private
Referenced by GetMySocketID(), and SetMySocketID().
m_PluggedDevices
ref array<EntityAI> m_PluggedDevices private
Referenced by Event_OnAwake(), and GetPluggedDevices().
m_PlugType
protected int m_PlugType private
Referenced by Event_OnAwake(), GetPlugType(), and SetPlugType().
m_ReduceMaxEnergyByDamageCoef
protected float m_ReduceMaxEnergyByDamageCoef private
Referenced by Event_OnAwake(), and GetEnergyMax().
m_RestorePlugState
protected bool m_RestorePlugState private
Referenced by GetRestorePlugState(), and RestorePlugState().
m_ShowSocketsInInventory
protected bool m_ShowSocketsInInventory private
Referenced by Event_OnAwake(), and HasVisibleSocketsInInventory().
m_Sockets
EntityAI m_Sockets[MAX_SOCKETS_COUNT] private
Referenced by Event_OnAwake(), GetDeviceBySocketID(), and SetDeviceBySocketID().
m_SocketsCount
protected float m_SocketsCount private
Referenced by Event_OnAwake(), and GetSocketsCount().
m_UpdateInterval
protected float m_UpdateInterval private
Referenced by GetUpdateInterval(), and SetUpdateInterval().
m_UpdateQuantityTimer
ref Timer m_UpdateQuantityTimer private
Referenced by Event_OnAwake(), and OnEnergyAdded().
m_UpdateTimer
ref Timer m_UpdateTimer private
Referenced by StartUpdates(), and StopUpdates().
m_WetnessExposure
protected float m_WetnessExposure private
Referenced by CheckWetness(), Event_OnAwake(), and GetWetnessExposure().
MAX_SOCKETS_COUNT
const int MAX_SOCKETS_COUNT = 4 private
Referenced by Event_OnAwake().
SEL_CORD_FOLDED
const string SEL_CORD_FOLDED = "cord_folded" static private
Referenced by PlugInDevice(), UnplugDevice(), and UpdateSelections().
SEL_CORD_PLUGGED
const string SEL_CORD_PLUGGED = "cord_plugged" static private
Referenced by ActionUnplugThisByCord::ActionCondition(), Event_OnAwake(), PlugInDevice(), UnplugDevice(), and UpdateSelections().
SOCKET_
protected const string SOCKET_ = "socket_" static private
Referenced by Event_OnAwake(), IsSelectionAPlug(), UnplugCordFromSocket(), UpdateSelections(), and UpdateSocketSelections().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/Component/ComponentEnergyManager.c