DayZ Scripts: UAIDWrapper Class Reference
UAIDWrapper Class Reference
Private Member Functions
private void UAIDWrapper ()
private void ~UAIDWrapper ()
proto native UAInput InputP ()
Constructor & Destructor Documentation
UAIDWrapper()
private void UAIDWrapper () inline private
~UAIDWrapper()
private void ~UAIDWrapper () inline private
Member Function Documentation
InputP()
proto native UAInput InputP () private
Referenced by ActionInput::GetUAInput(), ActionInput::SetInput(), ActionTargetsCursor::SetInteractActionIcon(), ScriptedWidgetEventHandler::SetInteractActionIcon(), UpdataControllerInput(), ActionInput::Update(), and UIScriptedMenu::Update().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/InputAPI/UAInput.c