DayZ Scripts: DayZCreature Class Reference
DayZCreature Class Reference
Private Member Functions
proto native AIAgent GetAIAgent ()
proto native bool IsSoundInsideBuilding ()
proto native void AddDamageSphere (string bone_name, string ammo_name, float radius, float duration, bool invertTeams)
proto native DayZCreatureAIType GetCreatureAIType ()
proto native void InitAIAgent (AIGroup group)
proto native void DestroyAIAgent ()
void DayZCreatureAI ()
void IncreaseEffectTriggerCount ()
void DecreaseEffectTriggerCount ()
void AddDamageSphere (AnimDamageParams damage_params)
override void EEKilled (Object killer)
AnimBootsType GetBootsType ()
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob)
void OnSoundEvent (int event_id, string event_user_string)
void OnSoundVoiceEvent (int event_id, string event_user_string)
void OnStepEvent (int event_id, string event_user_string)
void OnDamageEvent (int event_id, string event_user_string)
protected void RegisterAnimEvents ()
private void ProcessSoundEvent (AnimSoundEvent sound_event)
private void ProcessSoundVoiceEvent (AnimSoundVoiceEvent sound_event)
private void ProcessStepEvent (AnimStepEvent step_event)
private void ProcessDamageEvent (AnimDamageEvent damage_event)
protected void AttenuateSoundIfNecessary (SoundObject soundObject)
bool ResistContaminatedEffect ()
bool IsDanger ()
string CaptureSound ()
string ReleaseSound ()
Private Attributes
int m_EffectTriggerCount
Detailed Description
Definition at line 65 of file DayZAnimal.c.
Member Function Documentation
AddDamageSphere() [1/2]
void AddDamageSphere (AnimDamageParams damage_params) inline private
Definition at line 104 of file DayZAnimal.c.
AddDamageSphere() [2/2]
proto native void AddDamageSphere (string bone_name, string ammo_name, float radius, float duration, bool invertTeams) private
AttenuateSoundIfNecessary()
protected void AttenuateSoundIfNecessary (SoundObject soundObject) inline private
Definition at line 254 of file DayZAnimal.c.
References GetGame(), and GetPlayer().
CaptureSound()
string CaptureSound () inline private
Definition at line 281 of file DayZAnimal.c.
DayZCreatureAI()
void DayZCreatureAI () inline private
Definition at line 87 of file DayZAnimal.c.
References SetFlags().
DecreaseEffectTriggerCount()
void DecreaseEffectTriggerCount () inline private
Definition at line 99 of file DayZAnimal.c.
DestroyAIAgent()
proto native void DestroyAIAgent () private
EEKilled()
override void EEKilled (Object killer) inline private
Definition at line 109 of file DayZAnimal.c.
References COMP_TYPE_BODY_STAGING.
GetAIAgent()
proto native AIAgent GetAIAgent () private
GetBootsType()
AnimBootsType GetBootsType () inline private
Definition at line 115 of file DayZAnimal.c.
GetCreatureAIType()
proto native DayZCreatureAIType GetCreatureAIType () private
IncreaseEffectTriggerCount()
void IncreaseEffectTriggerCount () inline private
Definition at line 94 of file DayZAnimal.c.
InitAIAgent()
proto native void InitAIAgent (AIGroup group) private
AIAgent initialization. Manual ai initialization for creatures created with CreateObject(... init_ai = false...).
IsDanger()
bool IsDanger () inline private
Definition at line 276 of file DayZAnimal.c.
IsSoundInsideBuilding()
proto native bool IsSoundInsideBuilding () private
OnDamageEvent()
void OnDamageEvent (int event_id, string event_user_string) inline private
Definition at line 159 of file DayZAnimal.c.
OnSoundEvent()
void OnSoundEvent (int event_id, string event_user_string) inline private
Definition at line 132 of file DayZAnimal.c.
OnSoundVoiceEvent()
void OnSoundVoiceEvent (int event_id, string event_user_string) inline private
Definition at line 141 of file DayZAnimal.c.
OnStepEvent()
void OnStepEvent (int event_id, string event_user_string) inline private
Definition at line 150 of file DayZAnimal.c.
PlaySound()
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob) inline private
Definition at line 120 of file DayZAnimal.c.
References GetGame(), GetPosition, CGame::GetSoundScene(), and AbstractWave::SetPosition().
ProcessDamageEvent()
private void ProcessDamageEvent (AnimDamageEvent damage_event) inline private
Definition at line 249 of file DayZAnimal.c.
ProcessSoundEvent()
private void ProcessSoundEvent (AnimSoundEvent sound_event) inline private
Definition at line 194 of file DayZAnimal.c.
References NoiseSystem::AddNoise(), SoundObjectBuilder::BuildSoundObject(), GetGame(), CGame::GetNoiseSystem(), GetPosition, PlaySound(), SoundObject(), and SoundObjectBuilder::UpdateEnvSoundControllers().
ProcessSoundVoiceEvent()
private void ProcessSoundVoiceEvent (AnimSoundVoiceEvent sound_event) inline private
Definition at line 214 of file DayZAnimal.c.
References NoiseSystem::AddNoise(), SoundObjectBuilder::BuildSoundObject(), GetGame(), CGame::GetNoiseSystem(), GetPosition, PlaySound(), SoundObject(), and SoundObjectBuilder::UpdateEnvSoundControllers().
ProcessStepEvent()
private void ProcessStepEvent (AnimStepEvent step_event) inline private
Definition at line 235 of file DayZAnimal.c.
References SoundObjectBuilder::BuildSoundObject(), GetPosition, GetSurfaceType(), PlaySound(), SoundObject(), and SoundObjectBuilder::UpdateEnvSoundControllers().
RegisterAnimEvents()
protected void RegisterAnimEvents () inline private
Definition at line 168 of file DayZAnimal.c.
References GetGame(), Print(), and RegisterAnimationEvent().
ReleaseSound()
string ReleaseSound () inline private
Definition at line 286 of file DayZAnimal.c.
ResistContaminatedEffect()
bool ResistContaminatedEffect () inline private
Definition at line 266 of file DayZAnimal.c.
Field Documentation
m_EffectTriggerCount
int m_EffectTriggerCount private
Definition at line 84 of file DayZAnimal.c.
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Entities/DayZAnimal.c