DayZ Scripts: P:/scripts/4_World/Systems/AnimalCatchingSystem/CatchingContexts/CatchingContextTraps.c File Reference
CatchingContextTraps.c File Reference
Data Structures
class CatchingContextTrapsBase
class CatchingContextTrapFishLarge
Functions
CatchingContextTrapsBase CatchingContextBase InitCatchMethodMask ()
override protected void DeserializeData (Param par)
override protected void CreateResultDataStructure ()
override protected void ClearCatchingItemData ()
override protected void InitItemValues (EntityAI item)
override to init context-specific values
float AdjustBaitItemChance (EntityAI item)
Allows for adjustment of all catch probabilities from item qualities (damage, qty...)
override protected void InitCatchEnviroMask ()
override protected void Init (Param par)
override protected void SetupInitialTypes ()
void UpdateDataAndMasks ()
int UpdateTrapEnviroMask ()
void SetTrapEnviroMask (int value)
void UpdateUsedBait (ECatchingBaitCategories type)
if non-empty bait type is used, some 'Bait' attachment is picked as an active bait (currently no direct link between item and sensitivity-weighted target probability)
override void UpdateBaseProbability (YieldItemBase yItem)
updates base probability when catching the specific item (some context subclasses only)
override bool ModifySignalProbability (inout float probability)
void RemoveBait ()
void ReduceBaitQty (float qtyNorm)
Variables
protected float m_CumulativeTrappingSuccess
after N attempts, the chance to catch should be this. Only highest one applies. @NOTE: Take care, only way to achieve guaranteed 1.0 chance at the end is to have EVERY chance at 1.0.
protected int m_AttemptsCount
protected ItemBase m_Bait
Function Documentation
AdjustBaitItemChance()
float AdjustBaitItemChance (EntityAI item)
Allows for adjustment of all catch probabilities from item qualities (damage, qty...)
ClearCatchingItemData()
override protected void ClearCatchingItemData ()
CreateResultDataStructure()
override protected void CreateResultDataStructure ()
DeserializeData()
override protected void DeserializeData (Param par)
References m_MethodMask, and AnimalCatchingConstants::MASK_METHOD_FISHTRAP_LARGE.
Referenced by Init().
Init()
override protected void Init (Param par)
InitCatchEnviroMask()
override protected void InitCatchEnviroMask ()
InitCatchMethodMask()
CatchingContextTrapsBase CatchingContextBase InitCatchMethodMask ()
References CatchingContextBase().
Referenced by CatchingContextTrapsBase::UpdateDataAndMasks().
InitItemValues()
override protected void InitItemValues (EntityAI item)
override to init context-specific values
Referenced by InitCatchingItemData().
ModifySignalProbability()
override bool ModifySignalProbability (inout float probability)
ReduceBaitQty()
void ReduceBaitQty (float qtyNorm)
RemoveBait()
void RemoveBait ()
SetTrapEnviroMask()
void SetTrapEnviroMask (int value)
Referenced by ItemBase::SetActive().
SetupInitialTypes()
override protected void SetupInitialTypes ()
UpdateBaseProbability()
override void UpdateBaseProbability (YieldItemBase yItem)
updates base probability when catching the specific item (some context subclasses only)
Referenced by GenerateResult().
UpdateDataAndMasks()
void UpdateDataAndMasks ()
UpdateTrapEnviroMask()
int UpdateTrapEnviroMask ()
Referenced by ItemBase::OnPlacementComplete(), and ItemBase::SetActive().
UpdateUsedBait()
void UpdateUsedBait (ECatchingBaitCategories type)
if non-empty bait type is used, some 'Bait' attachment is picked as an active bait (currently no direct link between item and sensitivity-weighted target probability)
Variable Documentation
m_AttemptsCount
protected int m_AttemptsCount
m_Bait
protected ItemBase m_Bait
m_CumulativeTrappingSuccess
m_CumulativeTrappingSuccess
after N attempts, the chance to catch should be this. Only highest one applies. @NOTE: Take care, only way to achieve guaranteed 1.0 chance at the end is to have EVERY chance at 1.0.