DayZ Scripts: CheckLocalisationPlugin Class Reference
CheckLocalisationPlugin Class Reference
Private Member Functions
void FindTexts (WidgetSource src)
void CheckTextIDs (string file)
override void Run ()
Private Attributes
ref array< string > m_results = new array<string>
WBModuleDef m_module
Member Function Documentation
CheckTextIDs()
void CheckTextIDs (string file) inline private
References WBModuleDef::GetContainer(), and WBModuleDef::SetOpenedResource().
FindTexts()
void FindTexts (WidgetSource src) inline private
References string::Contains(), BaseContainer::Get(), WidgetSource::GetChildren(), BaseContainer::GetName(), WidgetSource::GetSibling(), and BaseContainer::VarIndex().
Run()
override void Run () inline private
References Workbench::Dialog(), Workbench::GetModule(), and Workbench::SearchResources().
Field Documentation
m_module
WBModuleDef m_module private
m_results
ref array<string> m_results = new array<string> private
The documentation for this class was generated from the following file:
P:/scripts/editor/Workbench/CheckLocTool.c