DayZ Scripts: KitchenTimer Class Reference
KitchenTimer Class Reference
Private Member Functions
override void Init ()
override void SetActions ()
override string GetExplosiveTriggerSlotName ()
override string GetToggleSound ()
override string GetRingingSound ()
string GetRingingStopSound ()
override string GetDestroyedSound ()
override string GetHitSound ()
override string GetWorkingSound ()
int GetMinutesMax ()
int Time01ToSeconds (float time01)
float SecondsTo01 (int seconds)
override float GetRingingDurationMax ()
override void TurnOff ()
void OnUpdate ()
override protected void Disarm ()
override protected void OnRingingStopClient ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void SetAlarmTimeServer (float time01)
void SetAlarmTimeServerSecs (int inSecs)
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
override string GetDebugText ()
Private Attributes
const string RINGING_SOUND = "KitchenTimer_Ring_Loop_SoundSet"
const string DESTROYED_SOUND = "AlarmClock_Destroyed_SoundSet"
const string HIT_SOUND = "AlarmClock_Hit_SoundSet"
const string WORKING_SOUND = "KitchenTimer_Ticking_Loop_SoundSet"
EffectSound m_RingingStopSound
int m_AlarmInSecs
Static Private Attributes
static ref NoiseParams m_NoisePar
static NoiseSystem m_NoiseSystem
Member Function Documentation
Disarm()
override protected void Disarm () inline private
References SetAlarmTimeServerSecs().
GetDebugActions()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline private
References SAT_DEBUG_ACTION.
GetDebugText()
override string GetDebugText () inline private
References GetGame(), GetRingingDurationMax(), m_AlarmInSecs, m_RingingDuration, m_State, and float::ToString().
GetDestroyedSound()
override string GetDestroyedSound () inline private
References DESTROYED_SOUND.
GetExplosiveTriggerSlotName()
override string GetExplosiveTriggerSlotName () inline private
GetHitSound()
override string GetHitSound () inline private
References HIT_SOUND.
GetMinutesMax()
int GetMinutesMax () inline private
Referenced by SecondsTo01(), and Time01ToSeconds().
GetRingingDurationMax()
override float GetRingingDurationMax () inline private
Referenced by GetDebugText(), and OnUpdate().
GetRingingSound()
override string GetRingingSound () inline private
References RINGING_SOUND.
GetRingingStopSound()
string GetRingingStopSound () inline private
Referenced by OnRingingStopClient().
GetToggleSound()
override string GetToggleSound () inline private
GetWorkingSound()
override string GetWorkingSound () inline private
References WORKING_SOUND.
Init()
override void Init () inline private
References GetGame(), CGame::GetNoiseSystem(), GetType(), m_NoisePar, m_NoiseSystem, and NoiseParams().
OnAction()
override bool OnAction (int action_id, Man player, ParamsReadContext ctx) inline private
References GetGame(), and SetAlarmTimeServerSecs().
OnRingingStopClient()
override protected void OnRingingStopClient () inline private
References GetRingingStopSound(), m_RingingSoundLoop, and m_RingingStopSound.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References MakeRingingStart(), Serializer::Read(), SetAlarmTimeServerSecs(), and SetState().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
References m_AlarmInSecs, m_State, and Serializer::Write().
OnUpdate()
void OnUpdate () inline private
References NoiseSystem::AddNoiseTarget(), GetPosition, GetRingingDurationMax(), IsRinging(), m_AlarmInSecs, m_NoisePar, m_NoiseSystem, m_RingingDuration, MakeRingingStart(), MakeRingingStop(), SecondsTo01(), TurnOff(), and UPDATE_TICK_RATE.
SecondsTo01()
float SecondsTo01 (int seconds) inline private
References GetMinutesMax(), and Math::InverseLerp().
Referenced by OnUpdate(), and SetAlarmTimeServerSecs().
SetActions()
override void SetActions () inline private
References ActionResetKitchenTimer(), and AddAction().
SetAlarmTimeServer()
override void SetAlarmTimeServer (float time01) inline private
References m_AlarmInSecs, Time01ToSeconds(), and TurnOn().
Referenced by ActionSetKitchenTimer::OnEndServer(), and SetAlarmTimeServerSecs().
SetAlarmTimeServerSecs()
void SetAlarmTimeServerSecs (int inSecs) inline private
References SecondsTo01(), and SetAlarmTimeServer().
Referenced by Disarm(), OnAction(), and OnStoreLoad().
Time01ToSeconds()
int Time01ToSeconds (float time01) inline private
References GetMinutesMax(), and Math::Lerp().
Referenced by SetAlarmTimeServer().
TurnOff()
override void TurnOff () inline private
References SEffectManager::DestroyEffect(), and m_WorkingSound.
Referenced by OnUpdate().
Field Documentation
DESTROYED_SOUND
const string DESTROYED_SOUND = "AlarmClock_Destroyed_SoundSet" private
Referenced by GetDestroyedSound().
HIT_SOUND
const string HIT_SOUND = "AlarmClock_Hit_SoundSet" private
Referenced by GetHitSound().
m_AlarmInSecs
int m_AlarmInSecs private
Referenced by GetDebugText(), OnStoreSave(), OnUpdate(), and SetAlarmTimeServer().
m_NoisePar
ref NoiseParams m_NoisePar static private
Referenced by Init(), and OnUpdate().
m_NoiseSystem
NoiseSystem m_NoiseSystem static private
Referenced by Init(), and OnUpdate().
m_RingingStopSound
EffectSound m_RingingStopSound private
Referenced by OnRingingStopClient().
RINGING_SOUND
const string RINGING_SOUND = "KitchenTimer_Ring_Loop_SoundSet" private
Referenced by GetRingingSound().
WORKING_SOUND
const string WORKING_SOUND = "KitchenTimer_Ticking_Loop_SoundSet" private
Referenced by GetWorkingSound().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Gear/Tools/KitchenTimer.c