DayZ Scripts: KeysToUIElements Class Reference
KeysToUIElements Class Reference
Static Private Member Functions
static private void RegisterKeyToUIElement (int key_code, string name, bool is_image_set)
static KeyToUIElement GetKeyToUIElement (int key_code)
static void Init ()
Static Private Attributes
static private ref map< int, ref KeyToUIElement > m_KeysToUIElements
Detailed Description
Definition at line 9 of file KeysToUIElements.c.
Member Function Documentation
GetKeyToUIElement()
static KeyToUIElement GetKeyToUIElement (int key_code) inline static private
Definition at line 31 of file KeysToUIElements.c.
References Debug::Log(), m_KeysToUIElements, and ToString().
Init()
static void Init () inline static private
Definition at line 42 of file KeysToUIElements.c.
References RegisterKeyToUIElement().
RegisterKeyToUIElement()
static private void RegisterKeyToUIElement (int key_code, string name, bool is_image_set) inline static private
Definition at line 13 of file KeysToUIElements.c.
References Debug::Log(), m_KeysToUIElements, name, and ToString().
Referenced by Init().
Field Documentation
m_KeysToUIElements
private ref map<int, ref KeyToUIElement> m_KeysToUIElements static private
Definition at line 11 of file KeysToUIElements.c.
Referenced by GetKeyToUIElement(), and RegisterKeyToUIElement().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/KeysToUIElements.c