DayZ Scripts: PlayerIdentityBase Class Reference
PlayerIdentityBase Class Reference
Player description (base engine class)
Private Member Functions
proto int GetPingAct ()
ping range estimation
proto int GetPingMin ()
ping range estimation
proto int GetPingMax ()
ping range estimation
proto int GetPingAvg ()
ping range estimation
proto int GetBandwidthMin ()
bandwidth estimation (in kbps)
proto int GetBandwidthMax ()
bandwidth estimation (in kbps)
proto int GetBandwidthAvg ()
bandwidth estimation (in kbps)
proto float GetOutputThrottle ()
Throttling performed on output bandwidth since last update (percentage [0,1])
proto float GetInputThrottle ()
Throttling performed on input bandwidth since last update(percentage [0,1]) (unknown value on Server)
proto string GetName ()
nick (short) name of player
proto string GetPlainName ()
nick without any processing
proto string GetFullName ()
full name of player
proto string GetId ()
unique id of player (hashed steamID, database Xbox id...) can be used in database or logs
proto string GetPlainId ()
plaintext unique id of player (cannot be used in database or logs)
proto int GetPlayerId ()
id of player in one session (is reused after player disconnects)
proto Man GetPlayer ()
get player
private void PlayerIdentityBase ()
This is a C++ managed class, so script has no business managing the lifetime.
private void ~PlayerIdentityBase ()
Detailed Description
Player description (base engine class)
Constructor & Destructor Documentation
PlayerIdentityBase()
private void PlayerIdentityBase () private
This is a C++ managed class, so script has no business managing the lifetime.
~PlayerIdentityBase()
private void ~PlayerIdentityBase () private
Member Function Documentation
GetBandwidthAvg()
proto int GetBandwidthAvg () private
bandwidth estimation (in kbps)
GetBandwidthMax()
proto int GetBandwidthMax () private
bandwidth estimation (in kbps)
GetBandwidthMin()
proto int GetBandwidthMin () private
bandwidth estimation (in kbps)
GetFullName()
proto string GetFullName () private
full name of player
GetId()
proto string GetId () private
unique id of player (hashed steamID, database Xbox id...) can be used in database or logs
Referenced by PluginBase::GetPlayerPrefix(), LogSuicide(), MissionBase::OnClientDisconnectedEvent(), MissionBase::OnEvent(), and ManBase::OnSelectPlayer().
GetInputThrottle()
proto float GetInputThrottle () private
Throttling performed on input bandwidth since last update(percentage [0,1]) (unknown value on Server)
Referenced by CGame::OnUpdate().
GetName()
proto string GetName () private
nick (short) name of player
Referenced by PluginBase::GetPlayerPrefix(), LogSuicide(), and ManBase::OnSelectPlayer().
GetOutputThrottle()
proto float GetOutputThrottle () private
Throttling performed on output bandwidth since last update (percentage [0,1])
Referenced by CGame::OnUpdate().
GetPingAct()
proto int GetPingAct () private
ping range estimation
Referenced by CGame::OnUpdate().
GetPingAvg()
proto int GetPingAvg () private
ping range estimation
Referenced by CGame::OnEvent(), and CGame::OnUpdate().
GetPingMax()
proto int GetPingMax () private
ping range estimation
GetPingMin()
proto int GetPingMin () private
ping range estimation
GetPlainId()
proto string GetPlainId () private
plaintext unique id of player (cannot be used in database or logs)
Referenced by CGame::OnRPC(), and ClientData::SyncEvent_PreprocessPlayerList().
GetPlainName()
proto string GetPlainName () private
nick without any processing
Referenced by ClientData::SyncEvent_PreprocessPlayerList().
GetPlayer()
proto Man GetPlayer () private
get player
Referenced by BillboardSetHandler::ActivateBillboardSet().
GetPlayerId()
proto int GetPlayerId () private
id of player in one session (is reused after player disconnects)
The documentation for this class was generated from the following file:
P:/scripts/3_Game/gameplay.c