DayZ Scripts: CraftTorch Class Reference
CraftTorch Class Reference
Private Member Functions
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
Member Function Documentation
CanDo()
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Do()
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
References GetGame(), InventorySlots::GetSlotIdFromString(), and GetType().
Init()
override void Init () inline private
References RecipeBase::AddResult(), RecipeBase::InsertIngredient(), RecipeBase::m_AnimationLength, RecipeBase::m_IngredientAddHealth, RecipeBase::m_IngredientAddQuantity, RecipeBase::m_IngredientDestroy, RecipeBase::m_IngredientSetHealth, RecipeBase::m_IngredientUseSoftSkills, RecipeBase::m_IsInstaRecipe, RecipeBase::m_MaxDamageIngredient, RecipeBase::m_MaxQuantityIngredient, RecipeBase::m_MinDamageIngredient, RecipeBase::m_MinQuantityIngredient, RecipeBase::m_Name, RecipeBase::m_ResultInheritsColor, RecipeBase::m_ResultInheritsHealth, RecipeBase::m_ResultReplacesIngredient, RecipeBase::m_ResultSetFullQuantity, RecipeBase::m_ResultSetHealth, RecipeBase::m_ResultSetQuantity, RecipeBase::m_ResultToInventory, RecipeBase::m_ResultUseSoftSkills, and RecipeBase::m_Specialty.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/Recipes/Recipes/CraftTorch.c