DayZ Scripts: ActionViewBinoculars Class Reference
ActionViewBinoculars Class Reference
Private Member Functions
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void EnterOptics (ItemOptics optic, PlayerBase player)
override void ExitOptics (ItemOptics optic, PlayerBase player)
Private Attributes
bool m_workingRangefinder
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Class::CastTo(), and ItemOptics::IsInOptics().
EnterOptics()
override void EnterOptics (ItemOptics optic, PlayerBase player) inline private
References ItemOptics::EnterOptics(), GetGame(), and ItemOptics::HideSelection().
ExitOptics()
override void ExitOptics (ItemOptics optic, PlayerBase player) inline private
References GetGame(), and ItemOptics::ShowSelection().
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
References ActionBase::m_Text.
Field Documentation
m_workingRangefinder
bool m_workingRangefinder private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionViewBinoculars.c