DayZ Scripts: ManBase Class Reference
ManBase Class Reference
Private Member Functions
void PlayerBase ()
void Init ()
void IncreaseAntibioticsCount ()
void DecreaseAntibioticsCount ()
bool IsAntibioticsActive ()
void SetSoundCategoryHash (int hash)
void RequestTriggerEffect (EffectTrigger trigger, int ppeIdx=-1, int aroundId=ParticleList.CONTAMINATED_AREA_GAS_AROUND, int tinyId=ParticleList.CONTAMINATED_AREA_GAS_TINY, string soundset="", bool partDynaUpdate=false, int newBirthRate=0, bool forceUpdate=false)
void RemoveCurrentEffectTrigger ()
void IncreaseContaminatedAreaCount ()
void DecreaseContaminatedAreaCount ()
void IncreaseEffectAreaCount ()
void DecreaseEffectAreaCount ()
protected void OnContaminatedAreaEnterServer ()
protected void OnContaminatedAreaExitServer ()
protected void OnPlayerIsNowInsideEffectAreaBeginServer ()
protected void OnPlayerIsNowInsideEffectAreaEndServer ()
protected void OnPlayerIsNowInsideEffectAreaBeginClient ()
protected void OnPlayerIsNowInsideEffectAreaEndClient ()
ItemBase GetItemOnSlot (string slot_type)
Returns item that's on this player's attachment slot. Parameter slot_type should be a string from config parameter 'itemInfo[]' like "Legs", "Headgear" and so on.
ItemBase GetItemOnHead ()
Returns item on player's head. For an example, a headtorch.
override int GetQuickBarBonus ()
override bool CanDropEntity (notnull EntityAI item)
int GetBreathVapourLevel ()
void UnsetMixedSoundState (eMixedSoundStates state)
void SetMixedSoundState (eMixedSoundStates state)
override bool IsPlayer ()
bool IsBleeding ()
void SetBleedingBits (int bits)
int GetBleedingBits ()
void IncreaseDiseaseCount ()
void DecreaseDiseaseCount ()
void IncreaseHealingsCount ()
void DecreaseHealingsCount ()
bool HasHealings ()
bool HasDisease ()
EPulseType GetPulseType ()
void SetPulseType (EPulseType pulse_type)
void QueueAddEffectWidget (array< int > effects)
void QueueRemoveEffectWidget (array< int > effects)
void QueueAddGlassesEffect (int id)
void QueueRemoveGlassesEffect (int id)
DamageDealtEffect GetDamageDealtEffect ()
override void SpawnDamageDealtEffect ()
void SpawnDamageDealtEffect2 (Param param1=null, Param param2=null)
FlashbangEffect GetFlashbangEffect ()
void SpawnFlashbangEffect (PlayerBase player, bool visual)
ShockDealtEffect GetShockEffect ()
void SpawnShockEffect (float intensity_max)
override void EEKilled (Object killer)
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos)
override void EEDelete (EntityAI parent)
override protected float ConvertNonlethalDamage (float damage, DamageType damageType)
override void OnReceivedHit (ImpactEffectsData hitData)
override void OnPlayerRecievedHit ()
void OnPlayerReceiveFlashbangHitStart (bool visual)
void OnPlayerReceiveFlashbangHitEnd ()
override string GetHitComponentForAI ()
Melee helpers.
override string GetDefaultHitComponent ()
returns default hit component (fallback)
override vector GetDefaultHitPosition ()
override array< string > GetSuitableFinisherHitComponents ()
returns list of suitable finisher hit components (defined on base entity/entity type)
protected vector SetDefaultHitPosition (string pSelection)
void AddPossibleCoverFaceForShave ()
DEPRECATED!
void RemovePossibleCoverFaceForShave ()
DEPRECATED!
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
void SwitchItemTypeAttach (EntityAI item, string slot)
void SwitchItemTypeDetach (EntityAI item, string slot)
void UpdateShoulderProxyVisibility (EntityAI item, string slot_name)
override void SwitchItemSelectionTexture (EntityAI item, string slot_name)
void RemoveAllItems ()
bool GetHitPPEEnabled ()
void SetHitPPEEnabled (bool enabled)
bool IsMale ()
int GetVoiceType ()
PlayerSoundManagerServer GetPlayerSoundManagerServer ()
UndergroundHandlerClient GetUndergroundHandler ()
void KillUndergroundHandler ()
void SetActions (out TInputActionMap InputActionMap)
void SetActions ()
void SetActionsRemoteTarget (out TInputActionMap InputActionMap)
void SetActionsRemoteTarget ()
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
void AddAction (typename actionName, out TInputActionMap InputActionMap)
void AddAction (typename actionName)
void RemoveAction (typename actionName, out TInputActionMap InputActionMap)
void RemoveAction (typename actionName)
int GetCurrentRecipe ()
void SetNextRecipe ()
void SetFirstRecipe ()
ActionManagerBase GetActionManager ()
EmoteManager GetEmoteManager ()
RandomGeneratorSyncManager GetRandomGeneratorSyncManager ()
override void OnLadder (float delta_time, HumanMovementState pState)
called every command handler tick when player is on ladder
void ProcessHandDamage (float delta_time, HumanMovementState pState)
override void ProcessFeetDamageServer (int pUserInt)
float GetFeetDamageMoveModifier ()
void SetStamina (int value, int range)
void SetQuickRestrain (bool enable)
void SetQuickFishing (bool enable)
bool IsQuickRestrain ()
bool IsQuickFishing ()
PlayerStats GetPlayerStats ()
CraftingManager GetCraftingManager ()
StaminaHandler GetStaminaHandler ()
override WeaponManager GetWeaponManager ()
override ArrowManagerBase GetArrowManager ()
bool CanBeRestrained ()
void SetRestrainStarted (bool restrain_started)
bool IsRestrainStarted ()
void SetRestrainPrelocked (bool restrain_prelock)
bool IsRestrainPrelocked ()
void SetRestrained (bool is_restrained)
override bool IsRestrained ()
override bool IsInventoryVisible ()
bool CanManipulateInventory ()
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanReleaseCargo (EntityAI cargo)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity)
override bool CanReceiveItemIntoHands (EntityAI item_to_hands)
override bool CanSaveItemInHands (EntityAI item_in_hands)
override bool CanReleaseFromHands (EntityAI handheld)
int GetCraftingRecipeID ()
void SetCraftingRecipeID (int recipeID)
ConstructionActionData GetConstructionActionData ()
void ResetConstructionActionData ()
vector GetLastFirePoint ()
float GetLastFirePointRot ()
int GetLastFirePointIndex ()
void SetLastFirePoint (vector last_fire_point)
void SetLastFirePointRot (float last_fire_point_rot)
void SetLastFirePointIndex (int last_fire_point_index)
void RemoveQuickBarEntityShortcut (EntityAI entity)
void SetEnableQuickBarEntityShortcut (EntityAI entity, bool value)
int FindQuickBarEntityIndex (EntityAI entity)
int GetQuickBarSize ()
EntityAI GetQuickBarEntity (int index)
void UpdateQuickBarEntityVisibility (EntityAI entity)
void SetQuickBarEntityShortcut (EntityAI entity, int index, bool force=false)
void OnQuickbarSetEntityRequest (ParamsReadContext ctx)
void ApplySplint ()
void ProcessDrowning (float dT)
void SpawnDrowningBubbles ()
void ProcessHoldBreath (float dT)
void OnHoldBreathStart ()
void OnHoldBreathExhausted ()
void OnHoldBreathEnd ()
override bool IsHoldingBreath ()
override bool IsRefresherSignalingViable ()
eMixedSoundStates GetMixedSoundStates ()
AbstractWave SaySoundSet (string name)
EntityAI FindCargoByBaseType (string searched_item)
void InitEditor ()
void OnPlayerLoaded ()
void SetPlayerDisconnected (bool state)
bool IsPlayerDisconnected ()
Hologram GetHologramServer ()
Hologram GetHologramLocal ()
void PlacingStartServer (ItemBase item)
void PlacingStartLocal (ItemBase item)
void PlacingCancelServer ()
void LockHandsUntilItemHeld ()
void PlacingCancelLocal ()
void PlacingCompleteServer ()
void PlacingCompleteLocal ()
bool IsPlacingServer ()
bool IsPlacingLocal ()
void SetDrowning (bool enable)
void OnDrowningStart ()
void OnDrowningEnd ()
bool TogglePlacingServer (int userDataType, ParamsReadContext ctx)
void RequestResetADSSync ()
bool ResetADSPlayerSync (int userDataType, ParamsReadContext ctx)
server only
override bool CanPlaceItem (EntityAI item)
void SetUnderground (EUndergroundPresence presence)
void TogglePlacingLocal (ItemBase item=null)
void SetLocalProjectionPosition (vector local_position)
void SetLocalProjectionOrientation (vector local_orientation)
vector GetLocalProjectionPosition ()
vector GetLocalProjectionOrientation ()
void AddToEnvironmentTemperature (float pTemperature)
DEPRECATED.
void SetInWater (bool pState)
water contact (driven by Environment)
bool IsInWater ()
void ~PlayerBase ()
void OnCameraChanged (DayZPlayerCameraBase new_camera)
DayZPlayerCamera GetCurrentPlayerCamera ()
bool IsCurrentCameraAimedAtGround ()
BleedingSourcesManagerServer GetBleedingManagerServer ()
BleedingSourcesManagerRemote GetBleedingManagerRemote ()
SymptomManager GetSymptomManager ()
VirtualHud GetVirtualHud ()
TransferValues GetTransferValues ()
DebugMonitorValues GetDebugMonitorValues ()
void OnScheduledTick (float deltaTime)
void OnCommandHandlerTick (float delta_time, int pCurrentCommandID)
void UpdateMovementInertia ()
Update movement inertia based on stamina available.
NotifiersManager GetNotifiersManager ()
void OnTick ()
override void EEItemIntoHands (EntityAI item)
override void EEItemOutOfHands (EntityAI item)
PlayerStomach GetStomach ()
override void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
void CloseMap ()
DEPRECATED; terminates map animation callback and re-enables controls.
void CloseMapEx (bool cancelled)
void SetMapOpen (bool state)
bool IsMapOpen ()
void SetMapClosingSyncSet (bool state)
bool GetMapClosingSyncSent ()
bool IsMapCallbackCancelInput ()
bool IsMapCallbackEndInput ()
MapNavigationBehaviour GetMapNavigationBehaviour ()
void MapNavigationItemInPossession (EntityAI item)
void MapNavigationItemNotInPossession (EntityAI item)
void SetCheckMeleeItem (ItemBase item=null)
void SetShakesForced (int value)
void FreezeCheck ()
override bool IsLanded (int pCurrentCommandID)
override bool OnLand (int pCurrentCommandID, FallDamageData fallDamageData)
override bool IsAlreadyInFallingCommand (int pCurrentCommandID)
void OnUnconsciousStart ()
void OnUnconsciousStop (int pCurrentCommandID)
void OnUnconsciousUpdate (float pDt, int last_command)
int SimplifyShock ()
float GetSimplifiedShockNormalized ()
override bool IsUnconscious ()
override bool CanBeTargetedByAI (EntityAI ai)
void GiveShock (float shock)
void OnRestrainStart ()
void ShockRefill (float pDt)
functionality moved to ShockMdfr::OnTick
eBrokenLegs GetBrokenLegs ()
void SetBrokenLegs (int stateId)
void UpdateBrokenLegs (int stateId)
void BreakLegSound ()
void BrokenLegForceProne (bool forceOverride=false)
void BrokenLegWalkShock ()
void MovingShock (float legHealth, float highShock, float midShock, float lowShock)
void DealShock (float dmg)
override bool CanPickupHeavyItem (notnull EntityAI item)
void SetLegHealth ()
void DropHeavyItem ()
bool IsWearingSplint ()
override void OnCommandSwimStart ()
override void OnCommandSwimFinish ()
override void OnCommandLadderStart ()
override void OnCommandLadderFinish ()
override void OnCommandFallStart ()
override void OnCommandFallFinish ()
override void OnCommandClimbStart ()
override void OnCommandClimbFinish ()
override void OnCommandVehicleStart ()
override void OnCommandVehicleFinish ()
override void OnCommandMelee2Start ()
override void OnCommandMelee2Finish ()
override void OnCommandDeathStart ()
override void OnJumpStart ()
override void OnJumpEnd (int pLandType=0)
bool IsStance (int stance, int stanceMask)
override void OnStanceChange (int previousStance, int newStance)
override bool CanChangeStance (int previousStance, int newStance)
override void OnCommandMoveStart ()
override bool CanRoll ()
override void OnRollStart (bool isToTheRight)
override void OnRollFinish ()
void OnJumpOutVehicleFinish (float carSpeed)
void OnVehicleSwitchSeat (int seatIndex)
override void OnVehicleSeatDriverEnter ()
override void OnVehicleSeatDriverLeft ()
override void OnThrowingModeChange (bool change_to_enabled)
override void EOnFrame (IEntity other, float timeSlice)
override void EOnPostFrame (IEntity other, int extra)
void StaminaHUDNotifier (bool show)
override void DepleteStamina (EStaminaModifiers modifier, float dT=-1)
override bool CanConsumeStamina (EStaminaConsumers consumer)
override bool CanStartConsumingStamina (EStaminaConsumers consumer)
bool HasStaminaRemaining ()
DEPRECATED.
override bool CanClimb (int climbType, SHumanCommandClimbResult climbRes)
override bool CanJump ()
bool IsJumpInProgress ()
bool IsTargetInActiveRefresherRange (EntityAI target)
void RequestHandAnimationStateRefresh ()
void RefreshHandAnimationState (int delay=0)
bool IsFacingTarget (Object target)
void OnQuickBarSingleUse (int slotClicked)
void OnQuickBarContinuousUseStart (int slotClicked)
void OnQuickBarContinuousUseEnd (int slotClicked)
void SetActionEndInput (ActionBase action)
bool IsQBControl ()
void ResetActionEndInput ()
void RadialQuickBarSingleUse (int slotClicked)
void RadialQuickBarCombine (int slotClicked)
void QuickReloadWeapon (EntityAI weapon)
void ReloadWeapon (EntityAI weapon, EntityAI magazine)
EntityAI GetMagazineToReload (EntityAI weapon)
void OnSpawnedFromConsole ()
bool GetLiquidTendencyDrain ()
void SetLiquidTendencyDrain (bool state)
bool GetFlagTendencyRaise ()
DEPRECATED.
void SetFlagTendencyRaise (bool state)
DEPRECATED.
override SoundOnVehicle PlaySound (string sound_name, float range, bool create_local=false)
float GetPlayerLoad ()
bool IsOverloaded ()
void SetPlayerLoad (float load)
void AddPlayerLoad (float addedload)
bool IsItemInInventory (EntityAI entity)
override bool NeedInventoryJunctureFromServer (notnull EntityAI item, EntityAI currParent, EntityAI newParent)
override protected float GetWeightSpecialized (bool forceRecalc=false)
void CalculateVisibilityForAI ()
void SetVisibilityCoef (float pVisibility)
float GetVisibilityCoef ()
int GetShakeLevel ()
EStatLevels GetStatLevelHealth ()
EStatLevels GetStatLevelToxicity ()
EStatLevels GetStatLevelBlood ()
EStatLevels GetStatLevelEnergy ()
EStatLevels GetStatLevelWater ()
EStatLevels GetImmunityLevel ()
returns player's immunity level
float GetBordersImmunity ()
float GetStatBordersHealth ()
float GetStatBordersToxicity ()
float GetStatBordersBlood ()
float GetStatBordersEnergy ()
float GetStatBordersWater ()
float GetStatLevelBorders (float stat_value, float critical, float low, float normal, float high, float max)
EStatLevels GetStatLevel (float stat_value, float critical, float low, float normal, float high)
void SetImmunityBoosted (bool boosted)
float GetImmunity ()
returns player's immunity strength between 0..1
bool IsSprinting ()
bool CanSprint ()
bool IsInProne ()
bool IsInRasedProne ()
bool IsLeaning ()
bool IsRolling ()
bool IsClimbing ()
bool IsFalling ()
override bool IsFighting ()
bool IsEmotePlaying ()
override bool IsIgnoredByConstruction ()
bool AnimCommandCheck (HumanMoveCommandID mask)
void RunFightBlendTimer ()
void EndFighting ()
bool CheckMeleeItemDamage (ItemBase item)
void PlayAttachmentDropSound ()
override void RPC (int rpc_type, array< ref Param > params, bool guaranteed, PlayerIdentity recipient=NULL)
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
override void OnGameplayDataHandlerSync ()
void UpdateLighting ()
void SetContaminatedEffectEx (bool enable, int ppeIdx=-1, int aroundId=ParticleList.CONTAMINATED_AREA_GAS_AROUND, int tinyId=ParticleList.CONTAMINATED_AREA_GAS_TINY, string soundset="", bool partDynaUpdate=false, int newBirthRate=0)
void SetContaminatedEffect (bool enable, int ppeIdx=-1, int aroundId=ParticleList.CONTAMINATED_AREA_GAS_AROUND, int tinyId=ParticleList.CONTAMINATED_AREA_GAS_TINY, bool partDynaUpdate=false, int newBirthRate=0)
void UpdateCorpseState ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void OnVariablesSynchronized ()
bool IsSyncedModifierActive (eModifierSyncIDs modifier)
Checks whether modifier (which has syncing enabled) is currently active, works on both Client and Server.
void HandleBrokenLegsSync ()
void FixAllInventoryItems ()
void OnInventoryMenuOpen ()
void OnInventoryMenuClose ()
void OnSelectPlayer ()
override void SimulateDeath (bool state)
void SetNewCharName ()
void CheckForBurlap ()
void CheckForGag ()
void UpdateMaskBreathWidget (notnull MaskBase mask, bool is_start=false)
void OnVoiceEvent (PlayerSoundEventBase voice_event)
void OnVoiceEventPlayback (PlayerSoundEventBase voice_event, AbstractWave callback, float playback_time)
called every cmd handler tick during a playback of PlayerSoundEvent, m_ProcessPlaybackEvent needs to be enabled on the PlayerSoundEvent
override bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
float GetHealthRegenSpeed ()
bool HandleRemoteItemManipulation (int userDataType, ParamsReadContext ctx)
ItemBase GetItemInHands ()
override EntityAI SpawnEntityOnGroundPos (string object_name, vector pos)
EntityAI SpawnEntityOnGroundOnCursorDir (string object_name, float distance)
EntityAI SpawnAI (string object_name, vector pos)
bool DropItem (ItemBase item)
Spawn item on server side.
EntityAI CreateInInventory (string item_name, string cargo_type="", bool full_quantity=false)
ItemBase CreateCopyOfItemInInventory (ItemBase src)
ItemBase CreateCopyOfItemInInventoryOrGround (ItemBase src)
ItemBase CreateCopyOfItemInInventoryOrGroundEx (ItemBase src, bool markItemAsSplitResult=false)
void Message (string text, string style)
void MessageStatus (string text)
void MessageAction (string text)
void MessageFriendly (string text)
void MessageImportant (string text)
void CloseInventoryMenu ()
override void ClearInventory ()
void DropAllItems ()
Drops all clothes/wearables this character is carrying on themselves.
string GetPlayerClass ()
void ShavePlayer ()
bool CanShave ()
override void OnParticleEvent (string pEventType, string pUserString, int pUserInt)
bool CanSpawnBreathVaporEffect ()
void ProcessADDModifier ()
void SpawnBreathVaporEffect ()
bool GetDrowningWaterLevelCheck ()
void SetLifeSpanStateVisible (int show_state)
int GetLifeSpanState ()
int GetLastShavedSeconds ()
void SetLastShavedSeconds (int last_shaved_seconds)
bool HasCoveredFaceForShave ()
eBloodyHandsTypes HasBloodyHandsEx ()
bool HasBloodyHands ()
void SetBloodyHands (bool show)
void SetBloodyHandsEx (eBloodyHandsTypes type)
private void SetBloodyHandsBase (int type)
void SetBloodyHandsPenalty ()
bool HasBloodTypeVisible ()
void SetBloodTypeVisible (bool show)
int GetBloodType ()
void SetBloodType (int blood_type)
SoftSkillsManager GetSoftSkillsManager ()
void CheckDeath ()
int GetNoisePresenceInAI ()
Return actual noise presence of player.
bool IsPersistentFlag (PersistentFlag bit)
void SetPersistentFlag (PersistentFlag bit, bool enable)
int GetStoreLoadVersion ()
override void OnStoreSave (ParamsWriteContext ctx)
void SaveAreaPersistenceFlag (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
void OnStoreSaveLifespan (ParamsWriteContext ctx)
bool OnStoreLoadLifespan (ParamsReadContext ctx, int version)
void UpdatePlayerMeasures ()
void OnConnect ()
void OnReconnect ()
void OnDisconnect ()
void SetModifiers (bool enable)
bool Consume (ItemBase source, float amount, EConsumeType consume_type)
void ShowUnconsciousScreen (bool show)
override void RequestSoundEventEx (EPlayerSoundEventID id, bool from_server_and_client=false, int param=0)
override void RequestSoundEvent (EPlayerSoundEventID id, bool from_server_and_client=false)
override protected void SendSoundEvent (EPlayerSoundEventID id)
override protected void SendSoundEventEx (EPlayerSoundEventID id, int param=0)
void CheckZeroSoundEvent ()
void CheckSendSoundEvent ()
override bool PlaySoundEvent (EPlayerSoundEventID id, bool from_anim_system=false, bool is_from_server=false)
override bool PlaySoundEventEx (EPlayerSoundEventID id, bool from_anim_system=false, bool is_from_server=false, int param=0)
PlayerSoundEventHandler GetPlayerSoundEventHandler ()
void OnBleedingBegin ()
void OnBleedingEnd ()
void OnBleedingSourceAdded ()
void OnBleedingSourceRemoved ()
void OnBleedingSourceRemovedEx (ItemBase item)
int GetBleedingSourceCount ()
void ResetPlayer (bool set_max)
void CheckSoundEvent ()
void TestSend ()
void SetStaminaState (eStaminaState state)
int GetStaminaState ()
void UpdateQuickBarExtraSlots ()
bool Save ()
void SpreadAgentsEx (float distance=3, float chance=0.25)
chance between [0..1] , distance in meters
void SpreadAgents ()
override int GetAgents ()
override void RemoveAgent (int agent_id)
override void RemoveAllAgents ()
override void InsertAgent (int agent, float count=1)
int GetSingleAgentCount (int agent_id)
float GetSingleAgentCountNormalized (int agent_id)
float GetTotalAgentCount ()
void PrintAgents ()
void ImmuneSystemTick (float value, float deltaT)
void AntibioticsAttack (float value)
vector GetAimPosition ()
bool CanEatAndDrink ()
ModifiersManager GetModifiersManager ()
PlayerStat< float > GetStatWater ()
PlayerStat< float > GetStatToxicity ()
PlayerStat< float > GetStatEnergy ()
PlayerStat< float > GetStatHeatComfort ()
PlayerStat< float > GetStatTremor ()
PlayerStat< int > GetStatWet ()
PlayerStat< float > GetStatDiet ()
PlayerStat< float > GetStatStamina ()
PlayerStat< float > GetStatSpecialty ()
PlayerStat< int > GetStatBloodType ()
PlayerStat< float > GetStatHeatBuffer ()
void ToggleHeatBufferVisibility (bool show)
string GetLastUAMessage ()
UA Last Message.
void SetLastUAMessage (string pMsg)
protected void ClearLastUAMessage ()
void ForceUpdateInjuredState ()
update injured state immediately
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
bool IsItemsToDelete ()
void SetToDelete (ParamsReadContext pCtx)
override void AddItemToDelete (EntityAI item)
bool CanDeleteItems ()
override void JunctureDeleteItem (EntityAI item)
void UpdateDelete ()
override bool HeadingModel (float pDt, SDayZPlayerHeadingModel pModel)
override bool IsInventorySoftLocked ()
override void SetInventorySoftLock (bool status)
'soft lock' meaning inventory screen cannot be displayed, but mechanically, inventory operations are still possible
void SetLoadedQuickBarItemBind (EntityAI entity, int index)
override bool IsLiftWeapon ()
bool ReadLiftWeaponRequest (int userDataType, ParamsReadContext ctx)
void SetLiftWeapon (int pJunctureID, ParamsReadContext ctx)
void SetLiftWeapon (bool state)
void SendLiftWeaponSync (bool state)
Client-side only.
override void CheckLiftWeapon ()
override void ProcessLiftWeapon ()
override void HideClothing (ItemOptics optic, bool state)
state 'true' == hide
void RequestUnconsciousness (bool enable)
override void SetDeathDarknessLevel (float duration, float tick_time)
override bool IsInFBEmoteState ()
void EndSurrenderRequest (SurrenderData data=null)
ends surrender, originally intended for surrender->restrained transitioning
bool IsSurrendered ()
bool IsPlayerLoaded ()
override void CheckAnimationOverrides ()
bool CanRedirectToWeaponManager (notnull EntityAI item, out bool isActionPossible)
override bool PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
override bool PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
override bool PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
override bool PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
override bool PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
override bool PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
override bool PredictiveDropEntity (notnull EntityAI item)
override bool PredictiveSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
override bool PredictiveForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
override void PredictiveTakeEntityToHands (EntityAI item)
override bool PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
bool IsSwapBetweenHandsAndGroundLargeItem (notnull EntityAI item1, notnull EntityAI item2, out EntityAI item_hands, out EntityAI item_ground)
void SetHairLevelToHide (int level, bool state, bool was_debug=false)
Dynamic hair hiding.
void HideHairSelections (ItemBase item, bool state)
void UpdateHairSelectionVisibility (bool was_debug=false)
void UpdateTranslatedSelections (SelectionTranslation stt)
void CheckHairClippingOnCharacterLoad ()
helper method for re-checking hairhiding on character load
bool IsNVGWorking ()
bool IsNVGLowered ()
int GetNVType ()
array< int > GetNVTypesArray ()
void SetNVGWorking (bool state)
Deprecated.
void SetNVGLowered (bool state)
void AddActiveNV (int type)
void RemoveActiveNV (int type)
void ResetActiveNV ()
void AdjustBandana (EntityAI item, string slot_name)
void UpdateCorpseStateVisual ()
void SetDecayEffects (int effect=-1)
void PreloadDecayTexture ()
void SetLastMapInfo (float scale, vector pos)
bool GetLastMapInfo (out float scale, out vector pos)
override bool PhysicalPredictiveDropItem (EntityAI entity, bool heavy_item_only=true)
override void SetProcessUIWarning (bool state)
void dmgDebugPrint (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
void DamageAllLegs (float inputDmg)
void TryHideItemInHands (bool hide, bool force=false)
tries to hide item in player's hands, some exceptions for various movement states
bool CheckAndExecuteStackSplit (FindInventoryLocationType flags, notnull EntityAI item, notnull EntityAI target)
bool CheckAndExecuteStackSplitToInventoryLocation (InventoryLocation il, notnull EntityAI item)
override protected bool TakeEntityToInventoryImpl (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item)
override protected bool TakeEntityToCargoImpl (InventoryMode mode, notnull EntityAI item)
override protected bool TakeEntityAsAttachmentImpl (InventoryMode mode, notnull EntityAI item)
override void TakeEntityToHandsImpl (InventoryMode mode, EntityAI item)
override protected bool TakeEntityToTargetInventoryImpl (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
override protected bool TakeEntityToTargetCargoImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
override protected bool TakeEntityToTargetAttachmentImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
override protected bool TakeToDstImpl (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
override vector GetCenter ()
void ContaminatedParticleAdjustment ()
void HandleGlassesEffect ()
override void AddArrow (Object arrow, int componentIndex, vector closeBonePosWS, vector closeBoneRotWS)
override bool IsManagingArrows ()
string GetCachedName ()
string GetCachedID ()
Static Private Member Functions
static set< int > GetFaceCoverageShaveValues ()
returns a set of face covering values
Private Attributes
const int SIMPLIFIED_SHOCK_CAP = 63
const int SHAKE_LEVEL_MAX = 7
private int m_LifeSpanState
private int m_LastShavedSeconds
private int m_BloodType
private bool m_HasBloodTypeVisible
private bool m_LiquidTendencyDrain
private bool m_FlagRaisingTendency
private int m_HasBloodyHandsVisible
private int m_FaceCoveredForShaveLayers = 0
protected bool m_HasHeatBuffer
protected bool m_PlayerLoaded
protected bool m_PlayerDisconnectProcessed
protected bool m_ProcessUIWarning
protected int m_LocalRefreshAnimStateIdx
protected int m_RefreshAnimStateIdx
private int m_StoreLoadVersion
const int ACT_STORE_SAVE_VERSION = 4
protected int m_LifespanLevelLocal
protected int m_AnimCommandStarting
EUndergroundPresence m_UndergroundPresence
private PluginPlayerStatus m_ModulePlayerStatus
PluginConfigEmotesProfile m_ConfigEmotesProfile
private PluginLifespan m_ModuleLifespan
protected PluginPresenceNotifier m_PresenceNotifier
protected ref UndergroundHandlerClient m_UndergroundHandler
ref PlayerStats m_PlayerStats
PluginRecipesManager m_ModuleRecipesManager
ref BleedingSourcesManagerServer m_BleedingManagerServer
ref BleedingSourcesManagerRemote m_BleedingManagerRemote
ref ModifiersManager m_ModifiersManager
ref NotifiersManager m_NotifiersManager
ref protected ActionManagerBase m_ActionManager
ref PlayerAgentPool m_AgentPool
int m_Agents
ref Environment m_Environment
ref EmoteManager m_EmoteManager
ref SymptomManager m_SymptomManager
ref VirtualHud m_VirtualHud
ref StaminaHandler m_StaminaHandler
ref InjuryAnimationHandler m_InjuryHandler
ref ShockHandler m_ShockHandler
ref SoftSkillsManager m_SoftSkillsManager
ref StanceIndicator m_StanceIndicator
ref TransferValues m_TrasferValues
ref DebugMonitorValues m_DebugMonitorValues
const int OVERLOAD_LIMIT = 30000
float m_CargoLoad
float m_VisibilityCoef
float m_OriginalSlidePoseAngle
int m_SoundEvent
int m_SoundEventParam
int m_FliesIndex
bool m_SoundEventSent
ref Param2< float, float > m_UAProgressParam
ref Param2< int, int > m_UAParam
ref Param3< float, float, bool > m_StaminaParam
ref Param1< string > m_UAParamMessage
ref Param1< float > m_UnconParam
ref Param1< float > m_DeathDarkeningParam
ref DamageDealtEffect m_DamageDealtEffect
ref EffectRadial m_EffectRadial
ref FlashbangEffect m_FlashbangEffect
ref ShockDealtEffect m_ShockDealtEffect
ref EffectParticle m_FliesEff
ref TInputActionMap m_InputActionMap
ref TInputActionMap m_InputActionMapControled
ref TInputActionMap m_InputActionMapAsTarget
bool m_ActionsInitialize
ref HiddenSelectionsData m_EmptyGloves
ref WeaponManager m_WeaponManager
ref CraftingManager m_CraftingManager
ref ArrowManagerPlayer m_ArrowManager
ref InventoryActionHandler m_InventoryActionHandler
ref protected QuickBarBase m_QuickBarBase
ref PlayerSoundManagerServer m_PlayerSoundManagerServer
ref PlayerSoundManagerClient m_PlayerSoundManagerClient
ref HeatComfortAnimHandler m_HCAnimHandler
ref EffectSound m_SoundFliesEffect
bool m_QuickBarHold
bool m_QuickBarFT = false
Hud m_Hud
protected int m_RecipePick
protected bool m_IsHoldingBreath
protected bool m_IsInWater
float m_LastPostFrameTickTime
ref Timer m_DeathCheckTimer
bool m_CorpseProcessing
int m_CorpseState
protected int m_CorpseStateLocal
int m_PersistentFlags
int m_StaminaState
float m_UnconsciousTime
int m_ShockSimplified
float m_CurrentShock
bool m_IsRestrained
bool m_IsRestrainStarted
bool m_IsRestrainPrelocked
bool m_ImmunityBoosted
bool m_AreHandsLocked
float m_UnconsciousVignetteTarget = 2
float m_CameraSwayModifier = 0.2
float m_LastShockHitTime
DayZPlayerCameraBase m_CurrentCamera
int m_BleedingBits
vector m_DirectionToCursor
vector m_DefaultHitPosition
int m_DiseaseCount
int m_HealingsCount
protected bool m_AllowQuickRestrain
protected bool m_AllowQuickFishing
protected int m_Shakes
protected int m_ShakesForced
int m_BreathVapour
int m_HealthLevel
int m_MixedSoundStates
int m_QuickBarBonus = 0
bool m_IsVehicleSeatDriver
float m_UnconsciousEndTime = 0
int m_BleedingSourceCount
Head_Default m_CharactersHead
EPulseType m_PulseType
PlayerBase m_CheckPulseLastTarget
int m_ForceInjuryAnimMask
bool m_HideHairAnimated
string m_DecayedTexture
protected ref array< EntityAI > m_ItemsToDelete
int m_BrokenLegState = eBrokenLegs.NO_BROKEN_LEGS
int m_LocalBrokenState = eBrokenLegs.NO_BROKEN_LEGS
bool m_BrokenLegsJunctureReceived
ref EffectSound m_BrokenLegSound
const string SOUND_BREAK_LEG = "broken_leg_SoundSet"
bool m_CanPlayBrokenLegSound
float m_UnconRefillModifier = 1
ref protected RandomGeneratorSyncManager m_RGSManager
int m_AntibioticsActive
bool m_ContaminatedAreaEffectEnabled
const string CONTAMINATED_AREA_AMBIENT = "ContaminatedArea_SoundSet"
EffectSound m_AmbientContamination
protected int m_ContaminatedAreaCount
protected int m_EffectAreaCount
protected bool m_InsideEffectArea
protected bool m_InsideEffectAreaPrev
protected EffectTrigger m_CurrentEffectTrigger
protected bool m_CanDisplayHitEffectPPE
protected string m_CachedPlayerName
protected string m_CachedPlayerID
ref array< ref Param2< EntityAI, int > > m_aQuickBarLoad
ref Hologram m_HologramServer
ref Hologram m_HologramLocal
vector m_LocalProjectionPosition = "0 0 0 "
vector m_LocalProjectionOrientation = "0 0 0 "
float m_LastTick = -1
int m_AddModifier = -1
int m_RecipeID = -1
EntityAI m_Item1
EntityAI m_Item2
bool m_IsCraftingReady
float m_RecipeAnimLength
vector m_CraftingInitialPos
ref array< int > m_Recipes
ref SoundParams m_SaySoundParams
ref SoundObjectBuilder m_SaySoundBuilder
ref SoundObject m_SaySoundObject
string m_SaySoundLastSetName
bool m_ActionQBControl
ref ConstructionActionData m_ConstructionActionData
vector m_LastFirePoint
float m_LastFirePointRot
int m_LastFirePointIndex
bool ItemToInventory
bool m_IsFighting = false
bool m_IsDrowning
int m_DebugMonitorEnabled
ActionUnfoldMapCB m_hac
bool m_MapOpen
bool m_MapCloseRequestProcessed
protected bool m_MapClosingSyncSent
protected float m_LastMapScale = -1.0
protected vector m_LastMapPos
protected ref MapNavigationBehaviour m_MapNavigationBehaviour
protected bool m_InventorySoftLocked
protected int m_InventorySoftLockCount = 0
string m_DatabaseID
ref Timer m_AnalyticsTimer
protected bool m_MeleeDebug
melee stats
protected ItemBase m_CheckMeleeItem
protected string m_UALastMessage
user actions last message
protected ref Timer m_UALastMessageTimer
bool m_WorkingNVGHeadset
bool m_LoweredNVGHeadset
protected ref array< int > m_ActiveNVTypes
int m_SyncedModifiers
int m_SyncedModifiersPrev
PluginAdminLog m_AdminLog
ref PlayerStomach m_PlayerStomach
protected PlayerStat< float > m_StatWater
protected PlayerStat< float > m_StatToxicity
protected PlayerStat< float > m_StatEnergy
protected PlayerStat< float > m_StatHeatComfort
protected PlayerStat< float > m_StatTremor
protected PlayerStat< int > m_StatWet protected PlayerStat< int > m_StatBloodType protected PlayerStat< float > m_StatDiet protected PlayerStat< float > m_StatStamina protected PlayerStat< float > m_StatSpecialty protected PlayerStat< float > m_StatHeatBuffer protected GameplayEffectWidgets_base m_EffectWidgets
effect widgets
protected ref array< int > m_ProcessAddEffectWidgets
protected ref array< int > m_ProcessRemoveEffectWidgets
protected ref array< int > m_ProcessAddGlassesEffects
protected ref array< int > m_ProcessRemoveGlassesEffects
bool m_ShowDbgUI = true
int m_DbgListSelection = 0
float m_DbgSliderValue = 0.0
ref array< string > m_DbgOptions = {"jedna", "dva", "tri"}
vector m_PlayerOldPos
Static Private Attributes
static bool DEBUG_INVENTORY_ACCESS = false
static ref array< string > m_BleedingSourcesLow
static ref array< string > m_BleedingSourcesUp
static ref array< Man > m_ServerPlayers = new array<Man>
static ref TStringArray m_QBarItems
static protected Particle m_ContaminatedAroundPlayer
static protected Particle m_ContaminatedAroundPlayerTiny
static ref array< Object > SPREAD_AGENTS_OBJECTS = new array<Object>
static ref array< CargoBase > SPREAD_AGENTS_PROXY_CARGOS = new array<CargoBase>
Constructor & Destructor Documentation
~PlayerBase()
void ~PlayerBase () inline private
References SEffectManager::DestroyEffect(), GetGame(), and ClientData::RemovePlayerBase().
Member Function Documentation
AddAction() [1/2]
void AddAction (typename actionName) inline private
References AddAction(), and m_InputActionMap.
AddAction() [2/2]
void AddAction (typename actionName , out TInputActionMap InputActionMap) inline private
References ActionBase(), GetActionManager(), and m_ActionsInitialize.
AddActiveNV()
void AddActiveNV (int type) inline private
References Error(), and GetGame().
AddArrow()
override void AddArrow (Object arrow, int componentIndex, vector closeBonePosWS, vector closeBoneRotWS) inline private
References AddChild(), CachedObjectsArrays::ARRAY_STRING, GetBoneIndexByName(), Math3D::MatrixInvMultiply4(), Math3D::MatrixOrthogonalize4(), LOD::NAME_FIRE, Math::RAD2DEG, and Math3D::YawPitchRollMatrix().
AddItemToDelete()
override void AddItemToDelete (EntityAI item) inline private
AddPlayerLoad()
void AddPlayerLoad (float addedload) inline private
AddPossibleCoverFaceForShave()
void AddPossibleCoverFaceForShave () inline private
DEPRECATED!
AddToEnvironmentTemperature()
void AddToEnvironmentTemperature (float pTemperature) inline private
DEPRECATED.
AdjustBandana()
void AdjustBandana (EntityAI item, string slot_name) inline private
AfterStoreLoad()
override void AfterStoreLoad () inline private
AnimCommandCheck()
bool AnimCommandCheck (HumanMoveCommandID mask) inline private
Returns whether the specified movement command(s) are starting the next frame. Use caution when using this for anything player animation-related, some commands may require the movement state to be truly active (wait until next update)
AntibioticsAttack()
void AntibioticsAttack (float value) inline private
ApplySplint()
void ApplySplint () inline private
BreakLegSound()
void BreakLegSound () inline private
BrokenLegForceProne()
void BrokenLegForceProne (bool forceOverride = false) inline private
References PlayerConstants::BROKEN_LEGS_INITIAL_SHOCK, Class::CastTo(), DayZPlayerUtils(), HumanCommandMove::ForceStance(), IsInWater(), HumanMovementState::m_iStanceIdx, and m_MovementState.
BrokenLegWalkShock()
void BrokenLegWalkShock () inline private
References PlayerConstants::BROKEN_CROUCH_MODIFIER, PlayerConstants::BROKEN_LEGS_HIGH_SHOCK_WALK, PlayerConstants::BROKEN_LEGS_LOW_SHOCK_WALK, PlayerConstants::BROKEN_LEGS_MID_SHOCK_WALK, PlayerConstants::BROKEN_LEGS_SHOCK_SWIM, PlayerConstants::BROKEN_LEGS_STAND_SHOCK, vector::LengthSq(), HumanMovementState::m_iMovement, HumanMovementState::m_iStanceIdx, and m_MovementState.
CalculateVisibilityForAI()
void CalculateVisibilityForAI () inline private
References Class::CastTo().
CanBeRestrained()
bool CanBeRestrained () inline private
References GetActionManager(), GetRunningAction(), and IsRunning().
CanBeTargetedByAI()
override bool CanBeTargetedByAI (EntityAI ai) inline private
CanChangeStance()
override bool CanChangeStance (int previousStance, int newStance) inline private
References Math::AbsInt(), GetCurrentWaterLevel(), and GetDayZPlayerType().
CanClimb()
override bool CanClimb (int climbType, SHumanCommandClimbResult climbRes) inline private
References InjuryAnimValues::LVL3.
CanConsumeStamina()
override bool CanConsumeStamina (EStaminaConsumers consumer) inline private
CanDeleteItems()
bool CanDeleteItems () inline private
References GetActionManager().
CanDropEntity()
override bool CanDropEntity (notnull EntityAI item) inline private
CanEatAndDrink()
bool CanEatAndDrink () inline private
CanJump()
override bool CanJump () inline private
disables jump when player is significantly injured
References InjuryAnimValues::LVL3.
CanManipulateInventory()
bool CanManipulateInventory () inline private
CanPickupHeavyItem()
override bool CanPickupHeavyItem (notnull EntityAI item) inline private
CanPlaceItem()
override bool CanPlaceItem (EntityAI item) inline private
References CfgGameplayHandler::GetDisallowedTypesInUnderground().
CanReceiveItemIntoCargo()
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
CanReceiveItemIntoHands()
override bool CanReceiveItemIntoHands (EntityAI item_to_hands) inline private
CanRedirectToWeaponManager()
bool CanRedirectToWeaponManager (notnull EntityAI item, out bool isActionPossible) inline private
CanReleaseAttachment()
override bool CanReleaseAttachment (EntityAI attachment) inline private
CanReleaseCargo()
override bool CanReleaseCargo (EntityAI cargo) inline private
CanReleaseFromHands()
override bool CanReleaseFromHands (EntityAI handheld) inline private
CanRoll()
override bool CanRoll () inline private
References IsPlayerInStance().
CanSaveItemInHands()
override bool CanSaveItemInHands (EntityAI item_in_hands) inline private
CanShave()
bool CanShave () inline private
CanSpawnBreathVaporEffect()
bool CanSpawnBreathVaporEffect () inline private
CanSprint()
bool CanSprint () inline private
CanStartConsumingStamina()
override bool CanStartConsumingStamina (EStaminaConsumers consumer) inline private
CanSwapItemInCargo()
override bool CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity) inline private
CheckAndExecuteStackSplit()
bool CheckAndExecuteStackSplit (FindInventoryLocationType flags, notnull EntityAI item, notnull EntityAI target) inline private
CheckAndExecuteStackSplitToInventoryLocation()
bool CheckAndExecuteStackSplitToInventoryLocation (InventoryLocation il, notnull EntityAI item) inline private
CheckAnimationOverrides()
override void CheckAnimationOverrides () inline private
References Math::PI2.
CheckDeath()
void CheckDeath () inline private
CheckForBurlap()
void CheckForBurlap () inline private
References Class::CastTo(), and GetInstanceType().
CheckForGag()
void CheckForGag () inline private
References Class::CastTo(), GetGame(), and CGame::SetVoiceEffect().
CheckHairClippingOnCharacterLoad()
void CheckHairClippingOnCharacterLoad () inline private
helper method for re-checking hairhiding on character load
CheckLiftWeapon()
override void CheckLiftWeapon () inline private
References GetInstanceType().
CheckMeleeItemDamage()
bool CheckMeleeItemDamage (ItemBase item) inline private
CheckSendSoundEvent()
void CheckSendSoundEvent () inline private
CheckSoundEvent()
void CheckSoundEvent () inline private
CheckZeroSoundEvent()
void CheckZeroSoundEvent () inline private
ClearInventory()
override void ClearInventory () inline private
/brief Delete all items in inventory
Returns
void
PlayerBase player = GetGame().GetPlayer();
player.ClearInventory();
References GameInventory::EnumerateInventory(), GetGame(), and CGame::ObjectDelete().
ClearLastUAMessage()
protected void ClearLastUAMessage () inline private
CloseInventoryMenu()
void CloseInventoryMenu () inline private
References UIManager::CloseAll(), GetGame(), GetInstanceType(), UIManager::GetMenu(), CGame::GetMission(), CGame::GetUIManager(), MENU_INSPECT, MENU_INVENTORY, Mission::RemoveActiveInputExcludes(), and Mission::RemoveActiveInputRestriction().
CloseMap()
void CloseMap () inline private
DEPRECATED; terminates map animation callback and re-enables controls.
CloseMapEx()
void CloseMapEx (bool cancelled) inline private
References ScriptInputUserData::CanStoreInputUserData(), UIManager::FindMenu(), GetActionManager(), GetGame(), CGame::GetMission(), CGame::GetUIManager(), m_Hud, MENU_MAP, Mission::RemoveActiveInputExcludes(), Mission::RemoveActiveInputRestriction(), ActionManagerClient::RequestEndAction(), ActionManagerClient::RequestInterruptAction(), Hud::ShowHudPlayer(), and Hud::ShowQuickbarPlayer().
CommandHandler()
override void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
When the player should be and is unconscious
Player can start floating while unconscious
When the player will be unconscious, or is being blocked from being unconscious
If the player is getting in/out or switching seats, delay unconsciousness until after animation has finished
Death gate - prevent unlikely occurence of death -> unconsciousness transition Fall gate - prevent unconciousness animation from playing while falling, doesn't look good Transition gate - prevent unconciousness while previous command is transitioning
TODO: rework vehicle command Knockout back to force player prone after they have exited the vehicle
When the player is waking up
Make sure the player is actually unconscious
protection for a player being broken when attempting to wake them up too early into unconsciousness
Don't set the stance if we are swimming or in a vehicle, stance change animation could play
Maybe instead error out or notify of possible desync?
SPRINT: enable/disable - based on stamina; disable also when raised
References ActionManagerBase(), HumanInputController::CameraIsFreeLook(), GetActionManager(), CGame::GetCurrentCameraDirection(), GetGame(), UAInputAPI::GetInputByID(), GetInstanceType(), GetPosition, HumanCommandVehicle::GetTransport(), GetUApi(), CfgGameplayHandler::GetUse3DMap(), HumanCommandVehicle::IsGettingIn(), HumanCommandVehicle::IsGettingOut(), HumanCommandUnconscious::IsInWater(), HumanInputController::IsQuickBarContinuousUseEnd(), HumanInputController::IsQuickBarContinuousUseStart(), HumanInputController::IsQuickBarSingleUse(), HumanInputController::IsQuickBarSlot(), HumanCommandVehicle::IsSwitchSeat(), HumanInputController::LimitsDisableSprint(), m_MovementState, m_StaminaHandler, MENU_MAP, HumanInputController::ResetADS(), UAInput::Supress(), StaminaHandler::Update(), HumanCommandUnconscious::WakeUp(), and vector::Zero.
Consume()
bool Consume (ItemBase source, float amount, EConsumeType consume_type) inline private
References AGT_UACTION_CONSUME, Edible_Base::Consume(), Error(), Edible_Base::GetFoodStage(), Liquid::GetLiquidClassname(), GetPlugin(), string::Length(), and LIQUID_WATER.
ContaminatedParticleAdjustment()
void ContaminatedParticleAdjustment () inline private
References Particle::SetParameter().
ConvertNonlethalDamage()
override protected float ConvertNonlethalDamage (float damage, DamageType damageType) inline private
References GameConstants::NL_DAMAGE_FIREARM_CONVERSION_PLAYERS.
CreateCopyOfItemInInventory()
ItemBase CreateCopyOfItemInInventory (ItemBase src) inline private
/brief Creates copy of ItemBase in players inventory. If player dont have enough slots for new item, item will be created on the ground under player.
Parameters
item_name string Class name of ItemBase in configs
Returns
ItemBase Created item
ItemBase item = g_Game.GetPlayer().CreateInInventory("Consumable_GardenLime", "cargo_weapon");
References InventoryLocation::DumpToStringNullSafe(), ECE_IN_INVENTORY, GetGame(), CGame::HasInventoryJunctureDestination(), Print(), CGame::RemoteObjectTreeCreate(), and RF_DEFAULT.
CreateCopyOfItemInInventoryOrGround()
ItemBase CreateCopyOfItemInInventoryOrGround (ItemBase src) inline private
CreateCopyOfItemInInventoryOrGroundEx()
ItemBase CreateCopyOfItemInInventoryOrGroundEx (ItemBase src, bool markItemAsSplitResult = false) inline private
CreateInInventory()
EntityAI CreateInInventory (string item_name, string cargo_type = "", bool full_quantity = false) inline private
/brief Creates ItemBase in players inventory. If player dont have enough slots for new item, item will be created on the ground under player.
Parameters
item_name string Class name of ItemBase in configs
Returns
ItemBase Created item
ItemBase item = g_Game.GetPlayer().CreateInInventory("Consumable_GardenLime", "cargo_weapon");
References SpawnItemOnLocation().
DamageAllLegs()
void DamageAllLegs (float inputDmg) inline private
DealShock()
void DealShock (float dmg) inline private
References GetGame(), and CGame::RPCSingleParam().
DecreaseAntibioticsCount()
void DecreaseAntibioticsCount () inline private
References Error().
DecreaseContaminatedAreaCount()
void DecreaseContaminatedAreaCount () inline private
DecreaseDiseaseCount()
void DecreaseDiseaseCount () inline private
DecreaseEffectAreaCount()
void DecreaseEffectAreaCount () inline private
DecreaseHealingsCount()
void DecreaseHealingsCount () inline private
DepleteStamina()
override void DepleteStamina (EStaminaModifiers modifier, float dT = -1) inline private
dmgDebugPrint()
void dmgDebugPrint (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
DropAllItems()
void DropAllItems () inline private
Drops all clothes/wearables this character is carrying on themselves.
References Class::CastTo().
DropHeavyItem()
void DropHeavyItem () inline private
DropItem()
bool DropItem (ItemBase item) inline private
Spawn item on server side.
Parameters
object_name string Name of item class
spawn_type \int(const) Type of spawning const: SPAWNTYPE_GROUND, SPAWNTYPE_HANDS, SPAWNTYPE_INVENTORY
full_quantity \bool Spawn with full quantity of item
distance \float Distance of spawn position from player (Only if spawn_type = SPAWNTYPE_GROUND)
Returns
ItemBase Spawned item
PlayerBase player = GetGame().GetPlayer();
player.SpawnItem("Fruit_Apple", SPAWNTYPE_GROUND, true, 5);
References GetPosition, and Math::RandomFloat().
EEDelete()
override void EEDelete (EntityAI parent) inline private
References ArrowManagerBase::ClearArrows(), SEffectManager::DestroyEffect(), and GetArrowManager().
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and GameConstants::STATE_RUINED.
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
DT_EXPLOSION & FlashGrenade
References CFG_AMMO, component, CGame::ConfigGetInt(), g_Game, CGame::GetAnalyticsServer(), DiagMenu::GetBool(), TotalDamageResult::GetDamage(), GetGame(), GetPlugin(), CGame::GetTime(), IsModifierActive(), m_AdminLog, m_StaminaHandler, AnalyticsManagerServer::OnEntityHit(), Print(), DayZPlayerSyncJunctures::SendPlayerUnconsciousness(), StaminaHandler::SetStamina(), and GameConstants::STAMINA_MAX.
EEHitByRemote()
override void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos) inline private
References component, SEffectManager::PlaySoundOnObject(), and EffectSound::SetAutodestroy().
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name) inline private
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetAnalyticsClient(), CGame::GetCallQueue(), GetGame(), and AnalyticsManagerClient::OnItemAttachedAtPlayer().
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name) inline private
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
EEItemIntoHands()
override void EEItemIntoHands (EntityAI item) inline private
fixes situation where raise is canceling some manipulation with heavy item(ex. TakeItemToHands), forces normal stance
References Class::CastTo(), HumanCommandMove::ForceStance(), OnItemInHandsChanged(), and HumanCommandMove::SetMeleeBlock().
EEItemOutOfHands()
override void EEItemOutOfHands (EntityAI item) inline private
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), GetGame(), and OnItemInHandsChanged().
EEKilled()
override void EEKilled (Object killer) inline private
References Hive::CharacterKill(), CGame::EnableVoN(), GetGame(), GetHive(), CGame::GetMission(), m_AdminLog, ClientData::RemovePlayerBase(), and Mission::SyncRespawnModeInfo().
EndFighting()
void EndFighting () inline private
EndSurrenderRequest()
void EndSurrenderRequest (SurrenderData data = null) inline private
ends surrender, originally intended for surrender->restrained transitioning
EOnFrame()
override void EOnFrame (IEntity other, float timeSlice) inline private
References GetInstanceType(), GameplayEffectWidgets_base::IsAnyEffectRunning(), m_Hud, Hud::ToggleHeatBufferPlusSign(), Hud::Update(), and GameplayEffectWidgets_base::Update().
EOnPostFrame()
override void EOnPostFrame (IEntity other, int extra) inline private
References GetGame(), GetInstanceType(), and CGame::GetTime().
FindCargoByBaseType()
EntityAI FindCargoByBaseType (string searched_item) inline private
References GetGame().
FindQuickBarEntityIndex()
int FindQuickBarEntityIndex (EntityAI entity) inline private
FixAllInventoryItems()
void FixAllInventoryItems () inline private
ForceUpdateInjuredState()
void ForceUpdateInjuredState () inline private
update injured state immediately
Injured stat
FreezeCheck()
void FreezeCheck () inline private
References Math::Clamp(), Math::InverseLerp(), Math::Lerp(), PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_CRITICAL, and PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_WARNING.
GetActionManager()
ActionManagerBase GetActionManager () inline private
References ActionManagerBase().
GetActions()
override void GetActions (typename action_input_type , out array< ActionBase_Basic > actions) inline private
References InitializeActions(), m_ActionsInitialize, and m_InputActionMap.
GetAgents()
override int GetAgents () inline private
GetAimPosition()
vector GetAimPosition () inline private
References CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), and DayZPhysics::RaycastRV().
GetArrowManager()
override ArrowManagerBase GetArrowManager () inline private
References m_ArrowManager.
GetBleedingBits()
int GetBleedingBits () inline private
GetBleedingManagerRemote()
BleedingSourcesManagerRemote GetBleedingManagerRemote () inline private
GetBleedingManagerServer()
BleedingSourcesManagerServer GetBleedingManagerServer () inline private
GetBleedingSourceCount()
int GetBleedingSourceCount () inline private
GetBloodType()
int GetBloodType () inline private
References m_BloodType.
GetBordersImmunity()
float GetBordersImmunity () inline private
References PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_CRITICAL, PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_HIGH, PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_LOW, and PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_NORMAL.
GetBreathVapourLevel()
int GetBreathVapourLevel () inline private
GetBrokenLegs()
eBrokenLegs GetBrokenLegs () inline private
References Math::AbsInt().
GetCachedID()
string GetCachedID () inline private
GetCachedName()
string GetCachedName () inline private
GetCenter()
override vector GetCenter () inline private
References GetBoneIndexByName().
GetConstructionActionData()
ConstructionActionData GetConstructionActionData () inline private
GetCraftingManager()
CraftingManager GetCraftingManager () inline private
GetCraftingRecipeID()
int GetCraftingRecipeID () inline private
References GetInstanceType(), and m_RecipeID.
GetCurrentPlayerCamera()
DayZPlayerCamera GetCurrentPlayerCamera () inline private
GetCurrentRecipe()
int GetCurrentRecipe () inline private
GetDamageDealtEffect()
DamageDealtEffect GetDamageDealtEffect () inline private
GetDebugActions()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline private
References GetPlugin(), name, SAT_DEBUG_ACTION, and Colors::WHITE.
GetDebugMonitorValues()
DebugMonitorValues GetDebugMonitorValues () inline private
GetDefaultHitComponent()
override string GetDefaultHitComponent () inline private
returns default hit component (fallback)
References GetDayZPlayerType().
GetDefaultHitPosition()
override vector GetDefaultHitPosition () inline private
GetDrowningWaterLevelCheck()
bool GetDrowningWaterLevelCheck () inline private
References PlayerConstants::DROWNING_DEFAULT_THRESHOLD, PlayerConstants::DROWNING_SWIMMING_THRESHOLD, PlayerConstants::DROWNING_UNCONSCIOUS_THRESHOLD, g_Game, and GetBoneIndexByName().
GetEmoteManager()
EmoteManager GetEmoteManager () inline private
GetFaceCoverageShaveValues()
static set< int > GetFaceCoverageShaveValues () inline static private
returns a set of face covering values
GetFeetDamageMoveModifier()
float GetFeetDamageMoveModifier () inline private
References HumanMovementState::m_iMovement, and m_MovementState.
GetFlagTendencyRaise()
bool GetFlagTendencyRaise () inline private
DEPRECATED.
GetFlashbangEffect()
FlashbangEffect GetFlashbangEffect () inline private
GetHealthRegenSpeed()
float GetHealthRegenSpeed () inline private
References PlayerConstants::BLOOD_THRESHOLD_FATAL, Math::Clamp(), PlayerConstants::HEALTH_REGEN_MAX, PlayerConstants::HEALTH_REGEN_MIN, Math::InverseLerp(), and Math::Lerp().
GetHitComponentForAI()
override string GetHitComponentForAI () inline private
Melee helpers.
select & return hit component for attacking AI
References GetDayZPlayerType().
GetHitPPEEnabled()
bool GetHitPPEEnabled () inline private
GetHologramLocal()
Hologram GetHologramLocal () inline private
GetHologramServer()
Hologram GetHologramServer () inline private
GetImmunity()
float GetImmunity () inline private
returns player's immunity strength between 0..1
References Math::Clamp(), PlayerConstants::SL_ENERGY_MAX, and PlayerConstants::SL_WATER_MAX.
GetImmunityLevel()
EStatLevels GetImmunityLevel () inline private
returns player's immunity level
References PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_CRITICAL, PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_HIGH, PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_LOW, and PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_NORMAL.
GetItemInHands()
ItemBase GetItemInHands () inline private
GetItemOnHead()
ItemBase GetItemOnHead () inline private
Returns item on player's head. For an example, a headtorch.
GetItemOnSlot()
ItemBase GetItemOnSlot (string slot_type) inline private
Returns item that's on this player's attachment slot. Parameter slot_type should be a string from config parameter 'itemInfo[]' like "Legs", "Headgear" and so on.
References Error(), InventorySlots::GetSlotIdFromString(), and GetType().
GetLastFirePoint()
vector GetLastFirePoint () inline private
GetLastFirePointIndex()
int GetLastFirePointIndex () inline private
GetLastFirePointRot()
float GetLastFirePointRot () inline private
GetLastMapInfo()
bool GetLastMapInfo (out float scale, out vector pos) inline private
GetLastShavedSeconds()
int GetLastShavedSeconds () inline private
GetLastUAMessage()
string GetLastUAMessage () inline private
UA Last Message.
GetLifeSpanState()
int GetLifeSpanState () inline private
GetLiquidTendencyDrain()
bool GetLiquidTendencyDrain () inline private
GetLocalProjectionOrientation()
vector GetLocalProjectionOrientation () inline private
GetLocalProjectionPosition()
vector GetLocalProjectionPosition () inline private
GetMagazineToReload()
EntityAI GetMagazineToReload (EntityAI weapon) inline private
References WeaponManager::CanAttachMagazine(), WeaponManager::CanLoadBullet(), and WeaponManager::CanSwapMagazine().
GetMapClosingSyncSent()
bool GetMapClosingSyncSent () inline private
GetMapNavigationBehaviour()
MapNavigationBehaviour GetMapNavigationBehaviour () inline private
GetMixedSoundStates()
eMixedSoundStates GetMixedSoundStates () inline private
GetModifiersManager()
ModifiersManager GetModifiersManager () inline private
GetNoisePresenceInAI()
int GetNoisePresenceInAI () inline private
Return actual noise presence of player.
GetNotifiersManager()
NotifiersManager GetNotifiersManager () inline private
GetNVType()
int GetNVType () inline private
GetNVTypesArray()
array< int > GetNVTypesArray () inline private
GetPlayerClass()
string GetPlayerClass () inline private
References GetGame(), and CGame::ObjectGetType().
GetPlayerLoad()
float GetPlayerLoad () inline private
GetPlayerSoundEventHandler()
PlayerSoundEventHandler GetPlayerSoundEventHandler () inline private
GetPlayerSoundManagerServer()
PlayerSoundManagerServer GetPlayerSoundManagerServer () inline private
GetPlayerStats()
PlayerStats GetPlayerStats () inline private
References m_PlayerStats.
GetPulseType()
EPulseType GetPulseType () inline private
GetQuickBarBonus()
override int GetQuickBarBonus () inline private
References m_QuickBarBonus.
GetQuickBarEntity()
EntityAI GetQuickBarEntity (int index) inline private
GetQuickBarSize()
int GetQuickBarSize () inline private
GetRandomGeneratorSyncManager()
RandomGeneratorSyncManager GetRandomGeneratorSyncManager () inline private
GetShakeLevel()
int GetShakeLevel () inline private
GetShockEffect()
ShockDealtEffect GetShockEffect () inline private
GetSimplifiedShockNormalized()
float GetSimplifiedShockNormalized () inline private
GetSingleAgentCount()
int GetSingleAgentCount (int agent_id) inline private
GetSingleAgentCountNormalized()
float GetSingleAgentCountNormalized (int agent_id) inline private
GetSoftSkillsManager()
SoftSkillsManager GetSoftSkillsManager () inline private
GetStaminaHandler()
StaminaHandler GetStaminaHandler () inline private
References m_StaminaHandler.
GetStaminaState()
int GetStaminaState () inline private
GetStatBloodType()
PlayerStat< int > GetStatBloodType () inline private
References GetStatObject().
GetStatBordersBlood()
float GetStatBordersBlood () inline private
References PlayerConstants::SL_BLOOD_CRITICAL, PlayerConstants::SL_BLOOD_HIGH, PlayerConstants::SL_BLOOD_LOW, and PlayerConstants::SL_BLOOD_NORMAL.
GetStatBordersEnergy()
float GetStatBordersEnergy () inline private
References PlayerConstants::SL_ENERGY_CRITICAL, PlayerConstants::SL_ENERGY_HIGH, PlayerConstants::SL_ENERGY_LOW, and PlayerConstants::SL_ENERGY_NORMAL.
GetStatBordersHealth()
float GetStatBordersHealth () inline private
References PlayerConstants::SL_HEALTH_CRITICAL, PlayerConstants::SL_HEALTH_HIGH, PlayerConstants::SL_HEALTH_LOW, and PlayerConstants::SL_HEALTH_NORMAL.
GetStatBordersToxicity()
float GetStatBordersToxicity () inline private
References PlayerConstants::SL_HEALTH_CRITICAL, PlayerConstants::SL_HEALTH_HIGH, PlayerConstants::SL_HEALTH_LOW, and PlayerConstants::SL_HEALTH_NORMAL.
GetStatBordersWater()
float GetStatBordersWater () inline private
References PlayerConstants::SL_WATER_CRITICAL, PlayerConstants::SL_WATER_HIGH, PlayerConstants::SL_WATER_LOW, and PlayerConstants::SL_WATER_NORMAL.
GetStatDiet()
PlayerStat< float > GetStatDiet () inline private
References GetStatObject().
GetStatEnergy()
PlayerStat< float > GetStatEnergy () inline private
References GetStatObject().
GetStatHeatBuffer()
PlayerStat< float > GetStatHeatBuffer () inline private
References GetStatObject().
GetStatHeatComfort()
PlayerStat< float > GetStatHeatComfort () inline private
References GetStatObject().
GetStatLevel()
EStatLevels GetStatLevel (float stat_value, float critical, float low, float normal, float high) inline private
GetStatLevelBlood()
EStatLevels GetStatLevelBlood () inline private
References PlayerConstants::SL_BLOOD_CRITICAL, PlayerConstants::SL_BLOOD_HIGH, PlayerConstants::SL_BLOOD_LOW, and PlayerConstants::SL_BLOOD_NORMAL.
GetStatLevelBorders()
float GetStatLevelBorders (float stat_value, float critical, float low, float normal, float high, float max) inline private
References Math::InverseLerp().
GetStatLevelEnergy()
EStatLevels GetStatLevelEnergy () inline private
References PlayerConstants::SL_ENERGY_CRITICAL, PlayerConstants::SL_ENERGY_HIGH, PlayerConstants::SL_ENERGY_LOW, and PlayerConstants::SL_ENERGY_NORMAL.
GetStatLevelHealth()
EStatLevels GetStatLevelHealth () inline private
References PlayerConstants::SL_HEALTH_CRITICAL, PlayerConstants::SL_HEALTH_HIGH, PlayerConstants::SL_HEALTH_LOW, and PlayerConstants::SL_HEALTH_NORMAL.
GetStatLevelToxicity()
EStatLevels GetStatLevelToxicity () inline private
References PlayerConstants::SL_HEALTH_CRITICAL, PlayerConstants::SL_HEALTH_HIGH, PlayerConstants::SL_HEALTH_LOW, and PlayerConstants::SL_HEALTH_NORMAL.
GetStatLevelWater()
EStatLevels GetStatLevelWater () inline private
References PlayerConstants::SL_WATER_CRITICAL, PlayerConstants::SL_WATER_HIGH, PlayerConstants::SL_WATER_LOW, and PlayerConstants::SL_WATER_NORMAL.
GetStatSpecialty()
PlayerStat< float > GetStatSpecialty () inline private
References GetStatObject().
GetStatStamina()
PlayerStat< float > GetStatStamina () inline private
References GetStatObject().
GetStatToxicity()
PlayerStat< float > GetStatToxicity () inline private
References GetStatObject().
GetStatTremor()
PlayerStat< float > GetStatTremor () inline private
References GetStatObject().
GetStatWater()
PlayerStat< float > GetStatWater () inline private
References GetStatObject().
GetStatWet()
PlayerStat< int > GetStatWet () inline private
References GetStatObject().
GetStomach()
PlayerStomach GetStomach () inline private
GetStoreLoadVersion()
int GetStoreLoadVersion () inline private
GetSuitableFinisherHitComponents()
override array< string > GetSuitableFinisherHitComponents () inline private
returns list of suitable finisher hit components (defined on base entity/entity type)
References GetDayZPlayerType().
GetSymptomManager()
SymptomManager GetSymptomManager () inline private
GetTotalAgentCount()
float GetTotalAgentCount () inline private
GetTransferValues()
TransferValues GetTransferValues () inline private
GetUndergroundHandler()
UndergroundHandlerClient GetUndergroundHandler () inline private
References UndergroundHandlerClient().
GetVirtualHud()
VirtualHud GetVirtualHud () inline private
References m_VirtualHud, and VirtualHud().
GetVisibilityCoef()
float GetVisibilityCoef () inline private
GetVoiceType()
int GetVoiceType () inline private
GetWeaponManager()
override WeaponManager GetWeaponManager () inline private
GetWeightSpecialized()
override protected float GetWeightSpecialized (bool forceRecalc = false) inline private
References WeightDebugData::SetCalcDetails().
GiveShock()
void GiveShock (float shock) inline private
HandleBrokenLegsSync()
void HandleBrokenLegsSync () inline private
HandleGlassesEffect()
void HandleGlassesEffect () inline private
HandleRemoteItemManipulation()
bool HandleRemoteItemManipulation (int userDataType, ParamsReadContext ctx) inline private
References INPUT_UDT_ITEM_MANIPULATION, Serializer::Read(), and InventoryLocation::ReadFromContext().
HasBloodTypeVisible()
bool HasBloodTypeVisible () inline private
HasBloodyHands()
bool HasBloodyHands () inline private
HasBloodyHandsEx()
eBloodyHandsTypes HasBloodyHandsEx () inline private
HasCoveredFaceForShave()
bool HasCoveredFaceForShave () inline private
HasDisease()
bool HasDisease () inline private
HasHealings()
bool HasHealings () inline private
HasStaminaRemaining()
bool HasStaminaRemaining () inline private
DEPRECATED.
HeadingModel()
override bool HeadingModel (float pDt, SDayZPlayerHeadingModel pModel) inline private
during fullbody gestures - disables character turning
References DayZPlayerImplementHeading::ClampHeading(), GetActionManager(), GetRunningAction(), HumanItemAccessor(), IsControllsLocked(), IsFullBody(), HumanMovementState::m_iStanceIdx, m_MovementState, HumanItemBehaviorCfg::m_StanceRotation, and DayZPlayerImplementHeading::NoHeading().
HideClothing()
override void HideClothing (ItemOptics optic, bool state) inline private
state 'true' == hide
References DayZPlayerCameraOptics(), GameConstants::DZPLAYER_CAMERA_FOV_IRONSIGHTS, ItemOptics::GetCurrentStepFOV(), and GetInstanceType().
HideHairSelections()
void HideHairSelections (ItemBase item, bool state) inline private
References GetType(), and Debug::Log().
ImmuneSystemTick()
void ImmuneSystemTick (float value, float deltaT) inline private
IncreaseAntibioticsCount()
void IncreaseAntibioticsCount () inline private
IncreaseContaminatedAreaCount()
void IncreaseContaminatedAreaCount () inline private
IncreaseDiseaseCount()
void IncreaseDiseaseCount () inline private
IncreaseEffectAreaCount()
void IncreaseEffectAreaCount () inline private
IncreaseHealingsCount()
void IncreaseHealingsCount () inline private
Init()
void Init () inline private
sets default hit position and cache it here (mainly for impact particles)
References ClientData::AddPlayerBase(), BREATH_VAPOUR_LEVEL_MAX, ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, PlayerConstants::CORPSE_STATE_DECAYED, EmoteManager(), CGame::GetCallQueue(), GetDayZGame(), GetDayZPlayerType(), GetDefaultHitPositionComponent(), GetGame(), Mission::GetHud(), CGame::GetMission(), GetPlugin(), InjuryAnimationHandler(), m_ActionsInitialize, m_AdminLog, m_ArrowManager, m_BloodType, m_ConfigDebugProfile, m_Hud, m_ModulePlayerStatus, m_PlayerStats, m_QuickBarBonus, m_Recipes, m_StaminaHandler, m_VirtualHud, MapNavigationBehaviour(), Math::Max(), ModifiersManager(), NotifiersManager(), PlayerSoundManagerClient(), PlayerStomach(), PluginLifespan(), QuickBarBase(), RandomGeneratorSyncManager(), and VirtualHud().
InitEditor()
void InitEditor () inline private
References GetGame(), GetID(), GetPlayer(), and GetPlugin().
InitializeActions()
void InitializeActions () inline private
References m_InputActionMap, and SetActions().
InsertAgent()
override void InsertAgent (int agent, float count = 1) inline private
IsAlreadyInFallingCommand()
override bool IsAlreadyInFallingCommand (int pCurrentCommandID) inline private
Don't switch to falling command if unconscious Don't switch to falling command if being damaged
IsAntibioticsActive()
bool IsAntibioticsActive () inline private
IsBleeding()
bool IsBleeding () inline private
IsClimbing()
bool IsClimbing () inline private
References HumanMovementState::m_CommandTypeId, and m_MovementState.
IsCurrentCameraAimedAtGround()
bool IsCurrentCameraAimedAtGround () inline private
References PlayerConstants::CAMERA_THRESHOLD_PITCH.
IsEmotePlaying()
bool IsEmotePlaying () inline private
IsFacingTarget()
bool IsFacingTarget (Object target) inline private
References Math::AbsFloat(), GetPosition, and vector::Normalize().
IsFalling()
bool IsFalling () inline private
References HumanMovementState::m_CommandTypeId, and m_MovementState.
IsFighting()
override bool IsFighting () inline private
IsHoldingBreath()
override bool IsHoldingBreath () inline private
IsIgnoredByConstruction()
override bool IsIgnoredByConstruction () inline private
IsInFBEmoteState()
override bool IsInFBEmoteState () inline private
References IsEmotePlaying().
IsInProne()
bool IsInProne () inline private
References HumanMovementState::IsInProne(), and m_MovementState.
IsInRasedProne()
bool IsInRasedProne () inline private
References HumanMovementState::IsInRaisedProne(), and m_MovementState.
IsInventorySoftLocked()
override bool IsInventorySoftLocked () inline private
IsInventoryVisible()
override bool IsInventoryVisible () inline private
IsInWater()
bool IsInWater () inline private
IsItemInInventory()
bool IsItemInInventory (EntityAI entity) inline private
IsItemsToDelete()
bool IsItemsToDelete () inline private
IsJumpInProgress()
bool IsJumpInProgress () inline private
IsLanded()
override bool IsLanded (int pCurrentCommandID) inline private
Handle fall damage for unconscious
No fall damage for players currently being damaged, animation is temporary
IsLeaning()
bool IsLeaning () inline private
References HumanMovementState::IsLeaning(), and m_MovementState.
IsLiftWeapon()
override bool IsLiftWeapon () inline private
IsMale()
bool IsMale () inline private
IsManagingArrows()
override bool IsManagingArrows () inline private
IsMapCallbackCancelInput()
bool IsMapCallbackCancelInput () inline private
References GetUApi().
IsMapCallbackEndInput()
bool IsMapCallbackEndInput () inline private
References GetUApi().
IsMapOpen()
bool IsMapOpen () inline private
IsNVGLowered()
bool IsNVGLowered () inline private
IsNVGWorking()
bool IsNVGWorking () inline private
IsOverloaded()
bool IsOverloaded () inline private
IsPersistentFlag()
bool IsPersistentFlag (PersistentFlag bit) inline private
IsPlacingLocal()
bool IsPlacingLocal () inline private
IsPlacingServer()
bool IsPlacingServer () inline private
IsPlayer()
override bool IsPlayer () inline private
IsPlayerDisconnected()
bool IsPlayerDisconnected () inline private
IsPlayerLoaded()
bool IsPlayerLoaded () inline private
IsQBControl()
bool IsQBControl () inline private
IsQuickFishing()
bool IsQuickFishing () inline private
IsQuickRestrain()
bool IsQuickRestrain () inline private
IsRefresherSignalingViable()
override bool IsRefresherSignalingViable () inline private
IsRestrained()
override bool IsRestrained () inline private
IsRestrainPrelocked()
bool IsRestrainPrelocked () inline private
IsRestrainStarted()
bool IsRestrainStarted () inline private
IsRolling()
bool IsRolling () inline private
IsSprinting()
bool IsSprinting () inline private
References HumanMovementState::m_iMovement, and m_MovementState.
IsStance()
bool IsStance (int stance, int stanceMask) inline private
IsSurrendered()
bool IsSurrendered () inline private
IsSwapBetweenHandsAndGroundLargeItem()
bool IsSwapBetweenHandsAndGroundLargeItem (notnull EntityAI item1, notnull EntityAI item2, out EntityAI item_hands, out EntityAI item_ground) inline private
References InventoryLocation::GetType().
IsSyncedModifierActive()
bool IsSyncedModifierActive (eModifierSyncIDs modifier) inline private
Checks whether modifier (which has syncing enabled) is currently active, works on both Client and Server.
IsTargetInActiveRefresherRange()
bool IsTargetInActiveRefresherRange (EntityAI target) inline private
References vector::Distance(), Mission::GetActiveRefresherLocations(), GetGame(), CGame::GetMission(), and GameConstants::REFRESHER_RADIUS.
IsUnconscious()
override bool IsUnconscious () inline private
References HumanMovementState::m_CommandTypeId, and m_MovementState.
IsWearingSplint()
bool IsWearingSplint () inline private
References Class::CastTo().
JunctureDeleteItem()
override void JunctureDeleteItem (EntityAI item) inline private
References DayZPlayerSyncJunctures::SendDeleteItem().
KillUndergroundHandler()
void KillUndergroundHandler () inline private
LockHandsUntilItemHeld()
void LockHandsUntilItemHeld () inline private
MapNavigationItemInPossession()
void MapNavigationItemInPossession (EntityAI item) inline private
MapNavigationItemNotInPossession()
void MapNavigationItemNotInPossession (EntityAI item) inline private
Message()
void Message (string text, string style) inline private
colorStatusChannel colorAction colorFriendly colorImportant
References CGame::Chat(), CGame::ChatMP(), GetGame(), and GetInstanceType().
MessageAction()
void MessageAction (string text) inline private
MessageFriendly()
void MessageFriendly (string text) inline private
MessageImportant()
void MessageImportant (string text) inline private
MessageStatus()
void MessageStatus (string text) inline private
MovingShock()
void MovingShock (float legHealth, float highShock, float midShock, float lowShock) inline private
References PlayerConstants::BROKEN_LEGS_HIGH_HEALTH_THRESHOLD, and PlayerConstants::BROKEN_LEGS_LOW_HEALTH_THRESHOLD.
NeedInventoryJunctureFromServer()
override bool NeedInventoryJunctureFromServer (notnull EntityAI item, EntityAI currParent, EntityAI newParent) inline private
References Error(), GetDebugName(), GetGame(), GetInstanceType(), LogManager::IsSyncLogEnable(), and syncDebugPrint().
OnBleedingBegin()
void OnBleedingBegin () private
OnBleedingEnd()
void OnBleedingEnd () private
OnBleedingSourceAdded()
void OnBleedingSourceAdded () inline private
References GetElement(), GetGame(), GetVirtualHud(), and SEffectManager::PlaySoundOnObject().
OnBleedingSourceRemoved()
void OnBleedingSourceRemoved () inline private
References ArrowManagerBase::DropAllArrows(), ArrowManagerBase::DropFirstArrow(), GetArrowManager(), GetElement(), GetGame(), and GetVirtualHud().
OnBleedingSourceRemovedEx()
void OnBleedingSourceRemovedEx (ItemBase item) inline private
OnCameraChanged()
void OnCameraChanged (DayZPlayerCameraBase new_camera) inline private
OnCommandClimbFinish()
override void OnCommandClimbFinish () inline private
OnCommandClimbStart()
override void OnCommandClimbStart () inline private
References AbortWeaponEvent().
OnCommandDeathStart()
override void OnCommandDeathStart () inline private
References AbortWeaponEvent().
OnCommandFallFinish()
override void OnCommandFallFinish () inline private
OnCommandFallStart()
override void OnCommandFallStart () inline private
References AbortWeaponEvent().
OnCommandHandlerTick()
void OnCommandHandlerTick (float delta_time, int pCurrentCommandID) inline private
References GameplayEffectWidgets_base::AddActiveEffects(), CfgGameplayHandler::GetAllowStaminaAffectInertia(), GetInstanceType(), m_MovementState, GameplayEffectWidgets_base::RemoveActiveEffects(), and SyncEvents::SendEntityKilled().
OnCommandLadderFinish()
override void OnCommandLadderFinish () inline private
References GetGame(), CGame::GetMission(), and Mission::RemoveActiveInputExcludes().
OnCommandLadderStart()
override void OnCommandLadderStart () inline private
References Mission::AddActiveInputExcludes(), GetGame(), and CGame::GetMission().
OnCommandMelee2Finish()
override void OnCommandMelee2Finish () inline private
OnCommandMelee2Start()
override void OnCommandMelee2Start () inline private
References AbortWeaponEvent().
OnCommandMoveStart()
override void OnCommandMoveStart () inline private
References GetGame(), and IsPlayerInStance().
OnCommandSwimFinish()
override void OnCommandSwimFinish () inline private
References GetDayZGame(), GetGame(), CGame::GetMission(), and Mission::RemoveActiveInputExcludes().
OnCommandSwimStart()
override void OnCommandSwimStart () inline private
References AbortWeaponEvent(), Mission::AddActiveInputExcludes(), GetDayZGame(), GetGame(), and CGame::GetMission().
OnCommandVehicleFinish()
override void OnCommandVehicleFinish () inline private
References GetGame(), CGame::GetMission(), and Mission::RemoveActiveInputExcludes().
OnCommandVehicleStart()
override void OnCommandVehicleStart () inline private
References Mission::AddActiveInputExcludes(), GetGame(), and CGame::GetMission().
OnConnect()
void OnConnect () inline private
References CGame::GetAnalyticsServer(), GetGame(), GetPosition, Debug::Log(), AnalyticsManagerServer::OnPlayerConnect(), and ToString().
OnContaminatedAreaEnterServer()
protected void OnContaminatedAreaEnterServer () inline private
OnContaminatedAreaExitServer()
protected void OnContaminatedAreaExitServer () inline private
OnDisconnect()
void OnDisconnect () inline private
References g_Game, CGame::GetAnalyticsServer(), GetGame(), Debug::Log(), StatsEventDisconnectedData::m_CharacterId, StatsEventDisconnectedData::m_Reason, AnalyticsManagerServer::OnPlayerDisconnect(), Analytics::PlayerDisconnected(), and ToString().
OnDrowningEnd()
void OnDrowningEnd () inline private
References CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), GetGame(), and ScriptCallQueue::Remove().
OnDrowningStart()
void OnDrowningStart () inline private
OnGameplayDataHandlerSync()
override void OnGameplayDataHandlerSync () inline private
References CfgGameplayHandler::GetDisableRespawnDialog(), GetGame(), CfgGameplayHandler::GetHitIndicationPPEEnabled(), CGame::GetMission(), and Mission::SetRespawnModeClient().
OnHoldBreathEnd()
void OnHoldBreathEnd () inline private
OnHoldBreathExhausted()
void OnHoldBreathExhausted () inline private
OnHoldBreathStart()
void OnHoldBreathStart () inline private
OnInputUserDataProcess()
override bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx) inline private
References GetGame(), INPUT_UDT_GESTURE, INPUT_UDT_INVENTORY, INPUT_UDT_USER_MUTE_XBOX, INPUT_UDT_WEAPON_LIFT_EVENT, CGame::MutePlayer(), OnInputUserDataProcess(), and Serializer::Read().
OnInventoryMenuClose()
void OnInventoryMenuClose () inline private
OnInventoryMenuOpen()
void OnInventoryMenuOpen () inline private
OnJumpEnd()
override void OnJumpEnd (int pLandType = 0) inline private
References HumanCommandFall().
OnJumpOutVehicleFinish()
void OnJumpOutVehicleFinish (float carSpeed) inline private
References GetGame(), and CGame::SurfaceUnderObject().
OnJumpStart()
override void OnJumpStart () inline private
References AbortWeaponEvent().
OnLadder()
override void OnLadder (float delta_time, HumanMovementState pState) inline private
called every command handler tick when player is on ladder
OnLand()
override bool OnLand (int pCurrentCommandID, FallDamageData fallDamageData) inline private
Nothing happens for unconscious Nothing happens for being damaged
OnParticleEvent()
override void OnParticleEvent (string pEventType, string pUserString, int pUserInt) inline private
References GetGame(), EffectParticle::GetParticle(), SEffectManager::PlayInWorld(), EffectParticle::SetDecalOwner(), and vector::Zero.
OnPlayerIsNowInsideEffectAreaBeginClient()
protected void OnPlayerIsNowInsideEffectAreaBeginClient () inline private
OnPlayerIsNowInsideEffectAreaBeginServer()
protected void OnPlayerIsNowInsideEffectAreaBeginServer () inline private
OnPlayerIsNowInsideEffectAreaEndClient()
protected void OnPlayerIsNowInsideEffectAreaEndClient () inline private
OnPlayerIsNowInsideEffectAreaEndServer()
protected void OnPlayerIsNowInsideEffectAreaEndServer () inline private
OnPlayerLoaded()
void OnPlayerLoaded () inline private
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), UIManager::CloseAll(), CGame::GetCallQueue(), Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), InventorySlots::GetSlotIdFromString(), CGame::GetUIManager(), m_BloodType, m_Hud, m_VirtualHud, Mission::OnPlayerRespawned(), PlayerSoundEventHandler(), Mission::SetPlayerRespawning(), Hud::ShowHudUI(), Hud::ShowQuickbarUI(), Hud::UpdateBloodName(), Hud::UpdateQuickbarGlobalVisibility(), and VirtualHud().
OnPlayerReceiveFlashbangHitEnd()
void OnPlayerReceiveFlashbangHitEnd () inline private
OnPlayerReceiveFlashbangHitStart()
void OnPlayerReceiveFlashbangHitStart (bool visual) inline private
OnPlayerRecievedHit()
override void OnPlayerRecievedHit () inline private
References CachedObjectsParams::PARAM2_FLOAT_FLOAT, SEffectManager::PlaySoundOnObject(), and EffectSound::SetAutodestroy().
OnQuickBarContinuousUseEnd()
void OnQuickBarContinuousUseEnd (int slotClicked) inline private
References ActionBase(), ActionManagerClient::ClearForceTarget(), ActionManagerClient::EndActionInput(), GetActionManager(), and GetInstanceType().
OnQuickBarContinuousUseStart()
void OnQuickBarContinuousUseStart (int slotClicked) inline private
References ActionManagerClient::CanPerformActionFromQuickbar(), ActionManagerClient::ForceTarget(), GetActionManager(), GetInstanceType(), and ActionManagerClient::PerformActionFromQuickbar().
OnQuickbarSetEntityRequest()
void OnQuickbarSetEntityRequest (ParamsReadContext ctx) inline private
OnQuickBarSingleUse()
void OnQuickBarSingleUse (int slotClicked) inline private
References GameInventory::CanForceSwapEntitiesEx(), ScriptInputUserData::CanStoreInputUserData(), GameInventory::CanSwapEntitiesEx(), Class::CastTo(), InventoryLocation::CopyLocationFrom(), InventoryLocation::DumpToStringNullSafe(), GetActionManager(), GetInstanceType(), GetRunningAction(), IsEmotePlaying(), IsIdle(), IsProcessing(), IsRunning(), LogManager::IsSyncLogEnable(), InventoryLocation::SetHands(), and syncDebugPrint().
OnReceivedHit()
override void OnReceivedHit (ImpactEffectsData hitData) inline private
Call only on client or single player PlayerBase (as GetGame().GetPlayer())
References GetCurrentCamera(), GetInstanceType(), and Math::InverseLerp().
OnReconnect()
void OnReconnect () inline private
References Debug::Log(), and ToString().
OnRestrainStart()
void OnRestrainStart () inline private
References GetGame(), CGame::GetMission(), Mission::RemoveActiveInputExcludes(), and Mission::RemoveActiveInputRestriction().
OnRollFinish()
override void OnRollFinish () inline private
OnRollStart()
override void OnRollStart (bool isToTheRight) inline private
References PlayerConstants::BROKEN_LEGS_ROLL_SHOCK.
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
uses contants outside of ERPCs !!!!
References _player, Mission::AddActiveInputExcludes(), ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, CGame::ExecuteEnforceScript(), CGame::GetCallQueue(), GetGame(), GetInstanceType(), CGame::GetMission(), GetPlugin(), ActionCheckPulse::GetPulseMessage(), GetVirtualHud(), m_Hud, MENU_WARNING_ITEMDROP, MENU_WARNING_TELEPORT, PluginBase::OnRPC(), CachedObjectsParams::PARAM1_BOOL, CachedObjectsParams::PARAM1_INT, CachedObjectsParams::PARAM1_STRING, PluginItemDiagnostic(), Serializer::Read(), Hud::SetTemperature(), ActionCheckPulse::TARGET_IRREGULAR_PULSE_BIT, and float::ToString().
OnScheduledTick()
void OnScheduledTick (float deltaTime) inline private
References m_VirtualHud.
OnSelectPlayer()
void OnSelectPlayer () inline private
add callbacks for ai target system
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, GameConstants::DEFAULT_CHARACTER_MENU_ID, Mission::EnableAllInputs(), Get(), CGame::GetCallQueue(), MenuData::GetCharactersCount(), GetDayZGame(), GetGame(), PlayerIdentityBase::GetId(), GetInstanceType(), MenuData::GetLastPlayedCharacter(), CGame::GetMenuData(), CGame::GetMission(), PlayerIdentityBase::GetName(), GetPlugin(), PPEManagerStatic::GetPPEManager(), PlayerBase::OnGameplayDataHandlerSync(), PluginPresenceNotifier(), Mission::ResetGUI(), CGame::RPC(), CGame::RPCSingleParam(), and Mission::SyncRespawnModeInfo().
OnSpawnedFromConsole()
void OnSpawnedFromConsole () inline private
References Mission::AddDummyPlayerToScheduler(), GetGame(), GetInstanceType(), and CGame::GetMission().
OnStanceChange()
override void OnStanceChange (int previousStance, int newStance) inline private
References AbortWeaponEvent(), PlayerConstants::FULL_SPRINT_DELAY_FROM_CROUCH, and PlayerConstants::FULL_SPRINT_DELAY_FROM_PRONE.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References Hive::CharacterIsLoginPositionChanged(), GetArrowManager(), GetDayZGame(), GetHive(), GetStorageVersion(), ArrowManagerPlayer::Load(), OnStoreLoad(), Print(), Serializer::Read(), and SetPosition().
OnStoreLoadLifespan()
bool OnStoreLoadLifespan (ParamsReadContext ctx, int version) inline private
References m_BloodType, and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
References GetArrowManager(), GetDayZGame(), GetGame(), HumanCommandLadder::GetLogoutPosition(), ArrowManagerPlayer::Save(), and Serializer::Write().
OnStoreSaveLifespan()
void OnStoreSaveLifespan (ParamsWriteContext ctx) inline private
References m_BloodType, and Serializer::Write().
OnSyncJuncture()
override void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx) inline private
SyncJunctures
References m_StaminaHandler, StaminaHandler::OnSyncJuncture(), DayZPlayerSyncJunctures::ReadBrokenLegsParamsEx(), DayZPlayerSyncJunctures::ReadInjuryParams(), DayZPlayerSyncJunctures::ReadKuruRequest(), DayZPlayerSyncJunctures::ReadPlayerUnconsciousnessParams(), DayZPlayerSyncJunctures::ReadShockParams(), DayZPlayerSyncJunctures::SJ_ACTION_ACK_ACCEPT, DayZPlayerSyncJunctures::SJ_ACTION_ACK_REJECT, DayZPlayerSyncJunctures::SJ_ACTION_INTERRUPT, DayZPlayerSyncJunctures::SJ_ADS_RESET, DayZPlayerSyncJunctures::SJ_BROKEN_LEGS, DayZPlayerSyncJunctures::SJ_DELETE_ITEM, DayZPlayerSyncJunctures::SJ_GESTURE_REQUEST, DayZPlayerSyncJunctures::SJ_INJURY, DayZPlayerSyncJunctures::SJ_INVENTORY, DayZPlayerSyncJunctures::SJ_INVENTORY_FAILURE, DayZPlayerSyncJunctures::SJ_INVENTORY_REPAIR, DayZPlayerSyncJunctures::SJ_KURU_REQUEST, DayZPlayerSyncJunctures::SJ_PLAYER_ADD_MODIFIER, DayZPlayerSyncJunctures::SJ_PLAYER_STATES, DayZPlayerSyncJunctures::SJ_QUICKBAR_SET_SHORTCUT, DayZPlayerSyncJunctures::SJ_SHOCK, DayZPlayerSyncJunctures::SJ_STAMINA, DayZPlayerSyncJunctures::SJ_STAMINA_MISC, DayZPlayerSyncJunctures::SJ_UNCONSCIOUSNESS, DayZPlayerSyncJunctures::SJ_WEAPON_ACTION_ACK_ACCEPT, DayZPlayerSyncJunctures::SJ_WEAPON_ACTION_ACK_REJECT, DayZPlayerSyncJunctures::SJ_WEAPON_LIFT, and DayZPlayerSyncJunctures::SJ_WEAPON_SET_JAMMING_CHANCE.
OnThrowingModeChange()
override void OnThrowingModeChange (bool change_to_enabled) inline private
OnTick()
void OnTick () inline private
References GetGame(), CGame::GetTime(), m_LastTick, and OnScheduledTick().
OnUnconsciousStart()
void OnUnconsciousStart () inline private
References GameplayEffectWidgets_base::AddSuspendRequest(), CGame::EnableVoN(), GetGame(), GetInstanceType(), CGame::GetSoundScene(), and m_AdminLog.
OnUnconsciousStop()
void OnUnconsciousStop (int pCurrentCommandID) inline private
References UIManager::CloseDialog(), CGame::EnableVoN(), UIManager::FindMenu(), g_Game, GetGame(), Mission::GetHud(), GetInstanceType(), CGame::GetMission(), CGame::GetSoundScene(), CGame::GetUIManager(), m_AdminLog, MENU_RESPAWN_DIALOGUE, GameplayEffectWidgets_base::RemoveSuspendRequest(), Hud::ShowHudUI(), and Hud::ShowQuickbarUI().
OnUnconsciousUpdate()
void OnUnconsciousUpdate (float pDt, int last_command) inline private
References GetGame(), Mission::GetHud(), GetInstanceType(), CGame::GetMission(), Math::Lerp(), Hud::ShowHudUI(), Hud::ShowQuickbarUI(), Math::Sin(), and PlayerConstants::UNCONSCIOUS_IN_WATER_TIME_LIMIT_TO_DEATH.
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Remotely Activated Item Behaviour refresh on item is in hands
References m_BloodType, and RemotelyActivatedItemBehaviour::OnVariableSynchronized().
OnVehicleSeatDriverEnter()
override void OnVehicleSeatDriverEnter () inline private
References GetParent(), m_Hud, and Hud::ShowVehicleInfo().
OnVehicleSeatDriverLeft()
override void OnVehicleSeatDriverLeft () inline private
References Hud::HideVehicleInfo(), and m_Hud.
OnVehicleSwitchSeat()
void OnVehicleSwitchSeat (int seatIndex) inline private
OnVoiceEvent()
void OnVoiceEvent (PlayerSoundEventBase voice_event) inline private
OnVoiceEventPlayback()
void OnVoiceEventPlayback (PlayerSoundEventBase voice_event, AbstractWave callback, float playback_time) inline private
called every cmd handler tick during a playback of PlayerSoundEvent, m_ProcessPlaybackEvent needs to be enabled on the PlayerSoundEvent
References AbstractWave::GetLength().
PhysicalPredictiveDropItem()
override bool PhysicalPredictiveDropItem (EntityAI entity, bool heavy_item_only = true) inline private
References ActionTarget, GetOrientation(), ActionManagerClient::PerformActionStart(), and vector::Zero.
PlacingCancelLocal()
void PlacingCancelLocal () inline private
References vector::Zero.
PlacingCancelServer()
void PlacingCancelServer () inline private
References vector::Zero.
PlacingCompleteLocal()
void PlacingCompleteLocal () inline private
References vector::Zero.
PlacingCompleteServer()
void PlacingCompleteServer () inline private
References vector::Zero.
PlacingStartLocal()
void PlacingStartLocal (ItemBase item) inline private
References GetGame().
PlacingStartServer()
void PlacingStartServer (ItemBase item) inline private
PlayAttachmentDropSound()
void PlayAttachmentDropSound () inline private
PlayerBase()
void PlayerBase () inline private
References Init().
PlaySound()
override SoundOnVehicle PlaySound (string sound_name, float range, bool create_local = false) inline private
References BetaSound::SaySound().
PlaySoundEvent()
override bool PlaySoundEvent (EPlayerSoundEventID id, bool from_anim_system = false, bool is_from_server = false) inline private
PlaySoundEventEx()
override bool PlaySoundEventEx (EPlayerSoundEventID id, bool from_anim_system = false, bool is_from_server = false, int param = 0) inline private
PredictiveDropEntity()
override bool PredictiveDropEntity (notnull EntityAI item) inline private
We don't care if a valid transform couldn't be found, we just want to preferably use it instead of placing on the player
References GameConstants::INVENTORY_ENTITY_DROP_OVERLAP_DEPTH, Math3D::MatrixIdentity4(), GameInventory::PrepareDropEntityPos(), and InventoryLocation::SetGround().
PredictiveForceSwapEntities()
override bool PredictiveForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline private
References ActionTarget, ForceStandUpForHeavyItemsSwap(), InventoryLocation::GetType(), ActionManagerClient::PerformActionStart(), and vector::Zero.
PredictiveSwapEntities()
override bool PredictiveSwapEntities (notnull EntityAI item1, notnull EntityAI item2) inline private
References ActionTarget, Class::CastTo(), ForceStandUpForHeavyItemsSwap(), ActionManagerClient::PerformActionStart(), Print(), and vector::Zero.
PredictiveTakeEntityToHands()
override void PredictiveTakeEntityToHands (EntityAI item) inline private
References ActionTarget, ActionManagerClient::PerformActionStart(), and vector::Zero.
PredictiveTakeEntityToInventory()
override bool PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline private
PredictiveTakeEntityToTargetAttachment()
override bool PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline private
PredictiveTakeEntityToTargetAttachmentEx()
override bool PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline private
PredictiveTakeEntityToTargetCargo()
override bool PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline private
PredictiveTakeEntityToTargetCargoEx()
override bool PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline private
References InventoryLocation::SetCargoAuto().
PredictiveTakeEntityToTargetInventory()
override bool PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
PredictiveTakeToDst()
override bool PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline private
References EntityAI::PredictiveTakeToDst().
PreloadDecayTexture()
void PreloadDecayTexture () inline private
PrintAgents()
void PrintAgents () inline private
ProcessADDModifier()
void ProcessADDModifier () inline private
References HumanCommandAdditives().
ProcessDrowning()
void ProcessDrowning (float dT) inline private
ProcessFeetDamageServer()
override void ProcessFeetDamageServer (int pUserInt) inline private
References PlayerConstants::BAREFOOT_MOVEMENT_BLEED_MODIFIER, PlayerConstants::CHECK_EVERY_N_STEP, GetGame(), Surface::GetParamFloat(), Math::RandomFloat01(), PlayerConstants::SHOES_MOVEMENT_DAMAGE_PER_STEP, and CGame::SurfaceUnderObject().
ProcessHandDamage()
void ProcessHandDamage (float delta_time, HumanMovementState pState) inline private
References PlayerConstants::CHANCE_TO_BLEED_SLIDING_LADDER_PER_SEC, GetGame(), GetInstanceType(), PlayerConstants::GLOVES_DAMAGE_SLIDING_LADDER_PER_SEC, HumanMovementState::m_iMovement, and Math::RandomFloat01().
ProcessHoldBreath()
void ProcessHoldBreath (float dT) inline private
ProcessLiftWeapon()
override void ProcessLiftWeapon () inline private
References HumanCommandWeapons::LiftWeapon().
QueueAddEffectWidget()
void QueueAddEffectWidget (array< int > effects) inline private
QueueAddGlassesEffect()
void QueueAddGlassesEffect (int id) inline private
QueueRemoveEffectWidget()
void QueueRemoveEffectWidget (array< int > effects) inline private
QueueRemoveGlassesEffect()
void QueueRemoveGlassesEffect (int id) inline private
QuickReloadWeapon()
void QuickReloadWeapon (EntityAI weapon) inline private
RadialQuickBarCombine()
void RadialQuickBarCombine (int slotClicked) inline private
RadialQuickBarSingleUse()
void RadialQuickBarSingleUse (int slotClicked) inline private
ReadLiftWeaponRequest()
bool ReadLiftWeaponRequest (int userDataType, ParamsReadContext ctx) inline private
References Serializer::Read().
RefreshHandAnimationState()
void RefreshHandAnimationState (int delay = 0) inline private
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
ReloadWeapon()
void ReloadWeapon (EntityAI weapon, EntityAI magazine) inline private
References ActionTarget, Class::CastTo(), GetActionManager(), GetInstanceType(), ActionManagerClient::Interrupt(), ActionManagerClient::PerformActionStart(), and vector::Zero.
RemoveAction() [1/2]
void RemoveAction (typename actionName) inline private
References m_InputActionMap, and RemoveAction().
RemoveAction() [2/2]
void RemoveAction (typename actionName , out TInputActionMap InputActionMap) inline private
References ActionBase(), and GetActionManager().
RemoveActiveNV()
void RemoveActiveNV (int type) inline private
References Error(), and GetGame().
RemoveAgent()
override void RemoveAgent (int agent_id) inline private
RemoveAllAgents()
override void RemoveAllAgents () inline private
RemoveAllItems()
void RemoveAllItems () inline private
References Class::CastTo().
RemoveCurrentEffectTrigger()
void RemoveCurrentEffectTrigger () inline private
References EffectTrigger::m_PPERequester.
RemovePossibleCoverFaceForShave()
void RemovePossibleCoverFaceForShave () inline private
DEPRECATED!
RemoveQuickBarEntityShortcut()
void RemoveQuickBarEntityShortcut (EntityAI entity) inline private
RequestHandAnimationStateRefresh()
void RequestHandAnimationStateRefresh () inline private
References GetGame().
RequestResetADSSync()
void RequestResetADSSync () inline private
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), GetInstanceType(), INPUT_UDT_RESET_ADS, ScriptInputUserData::Send(), and Serializer::Write().
RequestSoundEvent()
override void RequestSoundEvent (EPlayerSoundEventID id, bool from_server_and_client = false) inline private
RequestSoundEventEx()
override void RequestSoundEventEx (EPlayerSoundEventID id, bool from_server_and_client = false, int param = 0) inline private
References GetInstanceType().
RequestTriggerEffect()
void RequestTriggerEffect (EffectTrigger trigger, int ppeIdx = -1, int aroundId = ParticleList.CONTAMINATED_AREA_GAS_AROUND, int tinyId = ParticleList.CONTAMINATED_AREA_GAS_TINY, string soundset = "", bool partDynaUpdate = false, int newBirthRate = 0, bool forceUpdate = false) inline private
References EffectTrigger::GetEffectsPriority().
RequestUnconsciousness()
void RequestUnconsciousness (bool enable) inline private
References DayZPlayerSyncJunctures::SendPlayerUnconsciousness().
ResetActionEndInput()
void ResetActionEndInput () inline private
ResetActiveNV()
void ResetActiveNV () inline private
ResetADSPlayerSync()
bool ResetADSPlayerSync (int userDataType, ParamsReadContext ctx) inline private
server only
References INPUT_UDT_RESET_ADS, SendSyncJuncture(), and DayZPlayerSyncJunctures::SJ_ADS_RESET.
ResetConstructionActionData()
void ResetConstructionActionData () inline private
ResetPlayer()
void ResetPlayer (bool set_max) inline private
References ArrowManagerBase::ClearArrows(), GetArrowManager(), GetGame(), GetMax(), GetPlugin(), HumanCommandVehicle::GetTransport(), m_StaminaHandler, PluginLifespan(), DayZPlayerSyncJunctures::SendPlayerUnconsciousness(), StaminaHandler::SetStamina(), and GameConstants::STAMINA_MAX.
RPC()
override void RPC (int rpc_type, array< ref Param > params, bool guaranteed, PlayerIdentity recipient = NULL) inline private
RunFightBlendTimer()
void RunFightBlendTimer () inline private
References PlayerConstants::MELEE2_MOVEMENT_BLEND_DELAY.
Save()
bool Save () inline private
References Hive::CharacterSave(), GetHive(), Debug::Log(), and ToString().
SaveAreaPersistenceFlag()
void SaveAreaPersistenceFlag (ParamsWriteContext ctx) inline private
References IsModifierActive(), and Serializer::Write().
SaySoundSet()
AbstractWave SaySoundSet (string name) inline private
References GetGame(), GetPosition, CGame::GetSoundScene(), and name.
SendLiftWeaponSync()
void SendLiftWeaponSync (bool state) inline private
Client-side only.
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_WEAPON_LIFT_EVENT, HumanCommandWeapons::LiftWeapon(), ScriptInputUserData::Send(), and Serializer::Write().
SendSoundEvent()
override protected void SendSoundEvent (EPlayerSoundEventID id) inline private
SendSoundEventEx()
override protected void SendSoundEventEx (EPlayerSoundEventID id, int param = 0) inline private
References GetGame().
SetActionEndInput()
void SetActionEndInput (ActionBase action) inline private
SetActions() [1/2]
void SetActions () inline private
SetActions() [2/2]
void SetActions (out TInputActionMap InputActionMap) inline private
References ActionDrinkPondContinuous(), ActionGetOutTransport(), ActionStartEngine(), ActionUncoverHeadSelf(), ActionWashHandsWater(), and AddAction().
SetActionsRemoteTarget() [1/2]
void SetActionsRemoteTarget () inline private
SetActionsRemoteTarget() [2/2]
void SetActionsRemoteTarget (out TInputActionMap InputActionMap) inline private
References AddAction().
SetBleedingBits()
void SetBleedingBits (int bits) inline private
SetBloodType()
void SetBloodType (int blood_type) inline private
References m_BloodType.
SetBloodTypeVisible()
void SetBloodTypeVisible (bool show) inline private
SetBloodyHands()
void SetBloodyHands (bool show) inline private
SetBloodyHandsBase()
private void SetBloodyHandsBase (int type) inline private
References DiagMenu::SetValue().
SetBloodyHandsEx()
void SetBloodyHandsEx (eBloodyHandsTypes type) inline private
SetBloodyHandsPenalty()
void SetBloodyHandsPenalty () inline private
References InsertAgent().
SetBrokenLegs()
void SetBrokenLegs (int stateId) inline private
References DayZPlayerSyncJunctures::SendBrokenLegsEx().
SetCheckMeleeItem()
void SetCheckMeleeItem (ItemBase item = null) inline private
SetContaminatedEffect()
void SetContaminatedEffect (bool enable, int ppeIdx = -1, int aroundId = ParticleList.CONTAMINATED_AREA_GAS_AROUND, int tinyId = ParticleList.CONTAMINATED_AREA_GAS_TINY, bool partDynaUpdate = false, int newBirthRate = 0) inline private
SetContaminatedEffectEx()
void SetContaminatedEffectEx (bool enable, int ppeIdx = -1, int aroundId = ParticleList.CONTAMINATED_AREA_GAS_AROUND, int tinyId = ParticleList.CONTAMINATED_AREA_GAS_TINY, string soundset = "", bool partDynaUpdate = false, int newBirthRate = 0) inline private
References Class::CastTo(), GetPosition, ParticleManager(), Particle::SetParameter(), PPERequesterBase::Start(), and Particle::Stop().
SetCraftingRecipeID()
void SetCraftingRecipeID (int recipeID) inline private
References GetInstanceType(), and m_RecipeID.
SetDeathDarknessLevel()
override void SetDeathDarknessLevel (float duration, float tick_time) inline private
SetDecayEffects()
void SetDecayEffects (int effect = -1) inline private
References AddChild(), PlayerConstants::CORPSE_STATE_DECAYED, PlayerConstants::CORPSE_STATE_MEDIUM, SEffectManager::DestroyEffect(), GetBoneIndexByName(), SEffectManager::IsEffectExist(), and SEffectManager::PlayOnObject().
SetDefaultHitPosition()
protected vector SetDefaultHitPosition (string pSelection) inline private
SetDrowning()
void SetDrowning (bool enable) inline private
SetEnableQuickBarEntityShortcut()
void SetEnableQuickBarEntityShortcut (EntityAI entity, bool value) inline private
SetFirstRecipe()
void SetFirstRecipe () inline private
SetFlagTendencyRaise()
void SetFlagTendencyRaise (bool state) inline private
DEPRECATED.
SetHairLevelToHide()
void SetHairLevelToHide (int level, bool state, bool was_debug = false) inline private
Dynamic hair hiding.
References ErrorEx, GetInstanceType(), GetPlugin(), and SelectionTranslation::SetSelectionState().
SetHitPPEEnabled()
void SetHitPPEEnabled (bool enabled) inline private
SetImmunityBoosted()
void SetImmunityBoosted (bool boosted) inline private
SetInventorySoftLock()
override void SetInventorySoftLock (bool status) inline private
'soft lock' meaning inventory screen cannot be displayed, but mechanically, inventory operations are still possible
SetInWater()
void SetInWater (bool pState) inline private
water contact (driven by Environment)
SetLastFirePoint()
void SetLastFirePoint (vector last_fire_point) inline private
SetLastFirePointIndex()
void SetLastFirePointIndex (int last_fire_point_index) inline private
SetLastFirePointRot()
void SetLastFirePointRot (float last_fire_point_rot) inline private
SetLastMapInfo()
void SetLastMapInfo (float scale, vector pos) inline private
SetLastShavedSeconds()
void SetLastShavedSeconds (int last_shaved_seconds) inline private
SetLastUAMessage()
void SetLastUAMessage (string pMsg) inline private
References PlayerConstants::LAST_UA_MSG_LIFETIME.
SetLegHealth()
void SetLegHealth () inline private
SetLifeSpanStateVisible()
void SetLifeSpanStateVisible (int show_state) inline private
SetLiftWeapon() [1/2]
void SetLiftWeapon (bool state) inline private
SetLiftWeapon() [2/2]
void SetLiftWeapon (int pJunctureID, ParamsReadContext ctx) inline private
References Serializer::Read().
SetLiquidTendencyDrain()
void SetLiquidTendencyDrain (bool state) inline private
SetLoadedQuickBarItemBind()
void SetLoadedQuickBarItemBind (EntityAI entity, int index) inline private
SetLocalProjectionOrientation()
void SetLocalProjectionOrientation (vector local_orientation) inline private
SetLocalProjectionPosition()
void SetLocalProjectionPosition (vector local_position) inline private
SetMapClosingSyncSet()
void SetMapClosingSyncSet (bool state) inline private
SetMapOpen()
void SetMapOpen (bool state) inline private
SetMixedSoundState()
void SetMixedSoundState (eMixedSoundStates state) inline private
SetModifiers()
void SetModifiers (bool enable) inline private
SetNewCharName()
void SetNewCharName () inline private
References g_Game.
SetNextRecipe()
void SetNextRecipe () inline private
SetNVGLowered()
void SetNVGLowered (bool state) inline private
SetNVGWorking()
void SetNVGWorking (bool state) inline private
Deprecated.
SetPersistentFlag()
void SetPersistentFlag (PersistentFlag bit, bool enable) inline private
SetPlayerDisconnected()
void SetPlayerDisconnected (bool state) inline private
SetPlayerLoad()
void SetPlayerLoad (float load) inline private
SetProcessUIWarning()
override void SetProcessUIWarning (bool state) inline private
SetPulseType()
void SetPulseType (EPulseType pulse_type) inline private
SetQuickBarEntityShortcut()
void SetQuickBarEntityShortcut (EntityAI entity, int index, bool force = false) inline private
SetQuickFishing()
void SetQuickFishing (bool enable) inline private
SetQuickRestrain()
void SetQuickRestrain (bool enable) inline private
SetRestrained()
void SetRestrained (bool is_restrained) inline private
SetRestrainPrelocked()
void SetRestrainPrelocked (bool restrain_prelock) inline private
SetRestrainStarted()
void SetRestrainStarted (bool restrain_started) inline private
SetShakesForced()
void SetShakesForced (int value) inline private
SetSoundCategoryHash()
void SetSoundCategoryHash (int hash) inline private
SetStamina()
void SetStamina (int value, int range) inline private
References m_ModulePlayerStatus.
SetStaminaState()
void SetStaminaState (eStaminaState state) inline private
SetToDelete()
void SetToDelete (ParamsReadContext pCtx) inline private
References Serializer::Read().
SetUnderground()
void SetUnderground (EUndergroundPresence presence) inline private
SetVisibilityCoef()
void SetVisibilityCoef (float pVisibility) inline private
ShavePlayer()
void ShavePlayer () inline private
References AnalyticsManagerServer::STAT_PLAYTIME.
ShockRefill()
void ShockRefill (float pDt) private
functionality moved to ShockMdfr::OnTick
ShowUnconsciousScreen()
void ShowUnconsciousScreen (bool show) inline private
References GetGame(), CGame::GetUIManager(), PrintString(), UIManager::ScreenFadeIn(), and UIManager::ScreenFadeOut().
SimplifyShock()
int SimplifyShock () inline private
References Math::Clamp(), and Math::Lerp().
SimulateDeath()
override void SimulateDeath (bool state) inline private
References GameplayEffectWidgets_base::ClearSuspendRequests(), and GameplayEffectWidgets_base::StopAllEffects().
SpawnAI()
EntityAI SpawnAI (string object_name, vector pos) inline private
References ECE_EQUIP_ATTACHMENTS, ECE_INITAI, ECE_PLACE_ON_SURFACE, GetGame(), and CGame::IsKindOf().
SpawnBreathVaporEffect()
void SpawnBreathVaporEffect () inline private
References AddChild(), ParticleList::BREATH_VAPOUR_HEAVY, ParticleList::BREATH_VAPOUR_LIGHT, ParticleList::BREATH_VAPOUR_MEDIUM, GetBoneIndexByName(), and ParticleManager().
SpawnDamageDealtEffect()
override void SpawnDamageDealtEffect () inline private
SpawnDamageDealtEffect2()
void SpawnDamageDealtEffect2 (Param param1 = null, Param param2 = null) inline private
References EffectRadial().
SpawnDrowningBubbles()
void SpawnDrowningBubbles () inline private
References AddChild(), CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), PlayerConstants::DROWNING_BUBBLE_FREQUENCY_MAX, PlayerConstants::DROWNING_BUBBLE_FREQUENCY_MIN, ParticleList::DROWNING_BUBBLES, GetBoneIndexByName(), CGame::GetCallQueue(), GetGame(), Math::Lerp(), and ParticleManager().
SpawnEntityOnGroundOnCursorDir()
EntityAI SpawnEntityOnGroundOnCursorDir (string object_name, float distance) inline private
References GetPosition.
SpawnEntityOnGroundPos()
override EntityAI SpawnEntityOnGroundPos (string object_name, vector pos) inline private
References ECE_PLACE_ON_SURFACE, GetGame(), GetInstanceType(), InventoryLocation::GetPos(), CGame::IsKindOf(), Math3D::MatrixIdentity4(), and InventoryLocation::SetGround().
SpawnFlashbangEffect()
void SpawnFlashbangEffect (PlayerBase player, bool visual) inline private
SpawnShockEffect()
void SpawnShockEffect (float intensity_max) inline private
SpreadAgents()
void SpreadAgents () inline private
SpreadAgentsEx()
void SpreadAgentsEx (float distance = 3, float chance = 0.25) inline private
chance between [0..1] , distance in meters
References AGT_AIRBOURNE_BIOLOGICAL, vector::DistanceSq(), GetGame(), CGame::GetPlayers(), GetPlugin(), and Math::RandomFloat01().
StaminaHUDNotifier()
void StaminaHUDNotifier (bool show) inline private
References m_Hud, and Hud::SetStaminaBarVisibility().
SwitchItemSelectionTexture()
override void SwitchItemSelectionTexture (EntityAI item, string slot_name) inline private
SwitchItemTypeAttach()
void SwitchItemTypeAttach (EntityAI item, string slot) inline private
References GetGame().
SwitchItemTypeDetach()
void SwitchItemTypeDetach (EntityAI item, string slot) inline private
TakeEntityAsAttachmentImpl()
override protected bool TakeEntityAsAttachmentImpl (InventoryMode mode, notnull EntityAI item) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), and syncDebugPrint().
TakeEntityToCargoImpl()
override protected bool TakeEntityToCargoImpl (InventoryMode mode, notnull EntityAI item) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), and syncDebugPrint().
TakeEntityToHandsImpl()
override void TakeEntityToHandsImpl (InventoryMode mode, EntityAI item) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), and syncDebugPrint().
TakeEntityToInventoryImpl()
override protected bool TakeEntityToInventoryImpl (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), and syncDebugPrint().
TakeEntityToTargetAttachmentImpl()
override protected bool TakeEntityToTargetAttachmentImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), and syncDebugPrint().
TakeEntityToTargetCargoImpl()
override protected bool TakeEntityToTargetCargoImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), and syncDebugPrint().
TakeEntityToTargetInventoryImpl()
override protected bool TakeEntityToTargetInventoryImpl (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), and syncDebugPrint().
TakeToDstImpl()
override protected bool TakeToDstImpl (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), and syncDebugPrint().
TestSend()
void TestSend () inline private
References GetGame().
ToggleHeatBufferVisibility()
void ToggleHeatBufferVisibility (bool show) inline private
TogglePlacingLocal()
void TogglePlacingLocal (ItemBase item = null) inline private
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), GetInstanceType(), INPUT_UDT_ADVANCED_PLACEMENT, ScriptInputUserData::Send(), and Serializer::Write().
TogglePlacingServer()
bool TogglePlacingServer (int userDataType, ParamsReadContext ctx) inline private
References INPUT_UDT_ADVANCED_PLACEMENT.
TryHideItemInHands()
void TryHideItemInHands (bool hide, bool force = false) inline private
tries to hide item in player's hands, some exceptions for various movement states
UnsetMixedSoundState()
void UnsetMixedSoundState (eMixedSoundStates state) inline private
UpdateBrokenLegs()
void UpdateBrokenLegs (int stateId) inline private
References HumanMovementState::m_iStanceIdx, and m_MovementState.
UpdateCorpseState()
void UpdateCorpseState () inline private
References Math::AbsInt().
UpdateCorpseStateVisual()
void UpdateCorpseStateVisual () inline private
References Math::AbsInt(), PlayerConstants::CORPSE_STATE_DECAYED, InventorySlots::GetSlotIdFromString(), and path.
UpdateDelete()
void UpdateDelete () inline private
References GetGame(), and InventoryLocation::GetType().
UpdateHairSelectionVisibility()
void UpdateHairSelectionVisibility (bool was_debug = false) inline private
References SelectionTranslation::GetSelectionState().
UpdateLighting()
void UpdateLighting () inline private
References GetGame(), CfgGameplayHandler::GetLightingConfig(), CGame::GetMission(), Mission::GetWorldLighting(), mission, and WorldLighting::SetGlobalLighting().
UpdateMaskBreathWidget()
void UpdateMaskBreathWidget (notnull MaskBase mask, bool is_start = false) inline private
References GameplayEffectWidgets_base::OnVoiceEvent().
UpdateMovementInertia()
void UpdateMovementInertia () inline private
Update movement inertia based on stamina available.
References HumanCommandMove::SetDirectionSprintFilterModifier(), HumanCommandMove::SetRunSprintFilterModifier(), and HumanCommandMove::SetTurnSpanSprintModifier().
UpdatePlayerMeasures()
void UpdatePlayerMeasures () inline private
References g_Game, GetHourMinuteSecond(), GetPosition, StatsEventMeasuresData::m_CharacterId, StatsEventMeasuresData::m_DaytimeHour, StatsEventMeasuresData::m_DistanceOnFoot, StatsEventMeasuresData::m_PositionEnd, StatsEventMeasuresData::m_PositionStart, StatsEventMeasuresData::m_TimeInterval, Analytics::PlayerMeasures(), and AnalyticsManagerServer::STAT_DISTANCE.
UpdateQuickBarEntityVisibility()
void UpdateQuickBarEntityVisibility (EntityAI entity) inline private
UpdateQuickBarExtraSlots()
void UpdateQuickBarExtraSlots () inline private
UpdateShoulderProxyVisibility()
void UpdateShoulderProxyVisibility (EntityAI item, string slot_name) inline private
References SIMPLE_SELECTION_MELEE_MELEE, SIMPLE_SELECTION_MELEE_RIFLE, SIMPLE_SELECTION_SHOULDER_MELEE, and SIMPLE_SELECTION_SHOULDER_RIFLE.
UpdateTranslatedSelections()
void UpdateTranslatedSelections (SelectionTranslation stt) inline private
References SelectionTranslation::GetTranslatedSelections().
Field Documentation
ACT_STORE_SAVE_VERSION
const int ACT_STORE_SAVE_VERSION = 4 private
CONTAMINATED_AREA_AMBIENT
const string CONTAMINATED_AREA_AMBIENT = "ContaminatedArea_SoundSet" private
DEBUG_INVENTORY_ACCESS
bool DEBUG_INVENTORY_ACCESS = false static private
ItemToInventory
bool ItemToInventory private
m_ActionManager
ref protected ActionManagerBase m_ActionManager private
m_ActionQBControl
bool m_ActionQBControl private
m_ActionsInitialize
bool m_ActionsInitialize private
m_ActiveNVTypes
protected ref array<int> m_ActiveNVTypes private
m_AddModifier
int m_AddModifier = -1 private
m_AdminLog
PluginAdminLog m_AdminLog private
m_AgentPool
ref PlayerAgentPool m_AgentPool private
m_Agents
int m_Agents private
m_AllowQuickFishing
protected bool m_AllowQuickFishing private
m_AllowQuickRestrain
protected bool m_AllowQuickRestrain private
m_AmbientContamination
EffectSound m_AmbientContamination private
m_AnalyticsTimer
ref Timer m_AnalyticsTimer private
m_AnimCommandStarting
protected int m_AnimCommandStarting private
m_AntibioticsActive
int m_AntibioticsActive private
m_aQuickBarLoad
ref array<ref Param2<EntityAI,int> > m_aQuickBarLoad private
m_AreHandsLocked
bool m_AreHandsLocked private
m_ArrowManager
ref ArrowManagerPlayer m_ArrowManager private
m_BleedingBits
int m_BleedingBits private
m_BleedingManagerRemote
ref BleedingSourcesManagerRemote m_BleedingManagerRemote private
m_BleedingManagerServer
ref BleedingSourcesManagerServer m_BleedingManagerServer private
m_BleedingSourceCount
int m_BleedingSourceCount private
m_BleedingSourcesLow
ref array<string> m_BleedingSourcesLow static private
m_BleedingSourcesUp
ref array<string> m_BleedingSourcesUp static private
m_BloodType
private int m_BloodType private
m_BreathVapour
int m_BreathVapour private
m_BrokenLegsJunctureReceived
bool m_BrokenLegsJunctureReceived private
m_BrokenLegSound
ref EffectSound m_BrokenLegSound private
m_BrokenLegState
int m_BrokenLegState = eBrokenLegs.NO_BROKEN_LEGS private
m_CachedPlayerID
protected string m_CachedPlayerID private
m_CachedPlayerName
protected string m_CachedPlayerName private
m_CameraSwayModifier
float m_CameraSwayModifier = 0.2 private
m_CanDisplayHitEffectPPE
protected bool m_CanDisplayHitEffectPPE private
m_CanPlayBrokenLegSound
bool m_CanPlayBrokenLegSound private
m_CargoLoad
float m_CargoLoad private
m_CharactersHead
Head_Default m_CharactersHead private
m_CheckMeleeItem
protected ItemBase m_CheckMeleeItem private
m_CheckPulseLastTarget
PlayerBase m_CheckPulseLastTarget private
m_ConfigEmotesProfile
PluginConfigEmotesProfile m_ConfigEmotesProfile private
m_ConstructionActionData
ref ConstructionActionData m_ConstructionActionData private
m_ContaminatedAreaCount
protected int m_ContaminatedAreaCount private
m_ContaminatedAreaEffectEnabled
bool m_ContaminatedAreaEffectEnabled private
m_ContaminatedAroundPlayer
protected Particle m_ContaminatedAroundPlayer static private
m_ContaminatedAroundPlayerTiny
protected Particle m_ContaminatedAroundPlayerTiny static private
m_CorpseProcessing
bool m_CorpseProcessing private
m_CorpseState
int m_CorpseState private
m_CorpseStateLocal
protected int m_CorpseStateLocal private
m_CraftingInitialPos
vector m_CraftingInitialPos private
m_CraftingManager
ref CraftingManager m_CraftingManager private
m_CurrentCamera
DayZPlayerCameraBase m_CurrentCamera private
m_CurrentEffectTrigger
protected EffectTrigger m_CurrentEffectTrigger private
m_CurrentShock
float m_CurrentShock private
m_DamageDealtEffect
ref DamageDealtEffect m_DamageDealtEffect private
m_DatabaseID
string m_DatabaseID private
m_DbgListSelection
int m_DbgListSelection = 0 private
m_DbgOptions
ref array<string> m_DbgOptions = {"jedna", "dva", "tri"} private
m_DbgSliderValue
float m_DbgSliderValue = 0.0 private
m_DeathCheckTimer
ref Timer m_DeathCheckTimer private
m_DeathDarkeningParam
ref Param1<float> m_DeathDarkeningParam private
m_DebugMonitorEnabled
int m_DebugMonitorEnabled private
m_DebugMonitorValues
ref DebugMonitorValues m_DebugMonitorValues private
m_DecayedTexture
string m_DecayedTexture private
m_DefaultHitPosition
vector m_DefaultHitPosition private
m_DirectionToCursor
vector m_DirectionToCursor private
m_DiseaseCount
int m_DiseaseCount private
m_EffectAreaCount
protected int m_EffectAreaCount private
m_EffectRadial
ref EffectRadial m_EffectRadial private
m_EffectWidgets
protected PlayerStat<int> m_StatWet protected PlayerStat<int> m_StatBloodType protected PlayerStat<float> m_StatDiet protected PlayerStat<float> m_StatStamina protected PlayerStat<float> m_StatSpecialty protected PlayerStat<float> m_StatHeatBuffer protected GameplayEffectWidgets_base m_EffectWidgets private
effect widgets
m_EmoteManager
ref EmoteManager m_EmoteManager private
m_EmptyGloves
ref HiddenSelectionsData m_EmptyGloves private
m_Environment
ref Environment m_Environment private
m_FaceCoveredForShaveLayers
private int m_FaceCoveredForShaveLayers = 0 private
m_FlagRaisingTendency
private bool m_FlagRaisingTendency private
m_FlashbangEffect
ref FlashbangEffect m_FlashbangEffect private
m_FliesEff
ref EffectParticle m_FliesEff private
m_FliesIndex
int m_FliesIndex private
m_ForceInjuryAnimMask
int m_ForceInjuryAnimMask private
m_hac
ActionUnfoldMapCB m_hac private
m_HasBloodTypeVisible
private bool m_HasBloodTypeVisible private
m_HasBloodyHandsVisible
private int m_HasBloodyHandsVisible private
m_HasHeatBuffer
protected bool m_HasHeatBuffer private
m_HCAnimHandler
ref HeatComfortAnimHandler m_HCAnimHandler private
m_HealingsCount
int m_HealingsCount private
m_HealthLevel
int m_HealthLevel private
m_HideHairAnimated
bool m_HideHairAnimated private
m_HologramLocal
ref Hologram m_HologramLocal private
m_HologramServer
ref Hologram m_HologramServer private
m_Hud
Hud m_Hud private
m_ImmunityBoosted
bool m_ImmunityBoosted private
m_InjuryHandler
ref InjuryAnimationHandler m_InjuryHandler private
m_InputActionMap
ref TInputActionMap m_InputActionMap private
m_InputActionMapAsTarget
ref TInputActionMap m_InputActionMapAsTarget private
m_InputActionMapControled
ref TInputActionMap m_InputActionMapControled private
m_InsideEffectArea
protected bool m_InsideEffectArea private
m_InsideEffectAreaPrev
protected bool m_InsideEffectAreaPrev private
m_InventoryActionHandler
ref InventoryActionHandler m_InventoryActionHandler private
m_InventorySoftLockCount
protected int m_InventorySoftLockCount = 0 private
m_InventorySoftLocked
protected bool m_InventorySoftLocked private
m_IsCraftingReady
bool m_IsCraftingReady private
m_IsDrowning
bool m_IsDrowning private
m_IsFighting
bool m_IsFighting = false private
m_IsHoldingBreath
protected bool m_IsHoldingBreath private
m_IsInWater
protected bool m_IsInWater private
m_IsRestrained
bool m_IsRestrained private
m_IsRestrainPrelocked
bool m_IsRestrainPrelocked private
m_IsRestrainStarted
bool m_IsRestrainStarted private
m_IsVehicleSeatDriver
bool m_IsVehicleSeatDriver private
m_Item1
EntityAI m_Item1 private
m_Item2
EntityAI m_Item2 private
m_ItemsToDelete
protected ref array<EntityAI> m_ItemsToDelete private
m_LastFirePoint
vector m_LastFirePoint private
m_LastFirePointIndex
int m_LastFirePointIndex private
m_LastFirePointRot
float m_LastFirePointRot private
m_LastMapPos
protected vector m_LastMapPos private
m_LastMapScale
protected float m_LastMapScale = -1.0 private
m_LastPostFrameTickTime
float m_LastPostFrameTickTime private
m_LastShavedSeconds
private int m_LastShavedSeconds private
m_LastShockHitTime
float m_LastShockHitTime private
m_LastTick
float m_LastTick = -1 private
m_LifespanLevelLocal
protected int m_LifespanLevelLocal private
m_LifeSpanState
private int m_LifeSpanState private
m_LiquidTendencyDrain
private bool m_LiquidTendencyDrain private
m_LocalBrokenState
int m_LocalBrokenState = eBrokenLegs.NO_BROKEN_LEGS private
m_LocalProjectionOrientation
vector m_LocalProjectionOrientation = "0 0 0 " private
m_LocalProjectionPosition
vector m_LocalProjectionPosition = "0 0 0 " private
m_LocalRefreshAnimStateIdx
protected int m_LocalRefreshAnimStateIdx private
m_LoweredNVGHeadset
bool m_LoweredNVGHeadset private
m_MapCloseRequestProcessed
bool m_MapCloseRequestProcessed private
m_MapClosingSyncSent
protected bool m_MapClosingSyncSent private
m_MapNavigationBehaviour
protected ref MapNavigationBehaviour m_MapNavigationBehaviour private
m_MapOpen
bool m_MapOpen private
m_MeleeDebug
protected bool m_MeleeDebug private
melee stats
m_MixedSoundStates
int m_MixedSoundStates private
m_ModifiersManager
ref ModifiersManager m_ModifiersManager private
m_ModuleLifespan
private PluginLifespan m_ModuleLifespan private
m_ModulePlayerStatus
private PluginPlayerStatus m_ModulePlayerStatus private
m_ModuleRecipesManager
PluginRecipesManager m_ModuleRecipesManager private
m_NotifiersManager
ref NotifiersManager m_NotifiersManager private
m_OriginalSlidePoseAngle
float m_OriginalSlidePoseAngle private
m_PersistentFlags
int m_PersistentFlags private
m_PlayerDisconnectProcessed
protected bool m_PlayerDisconnectProcessed private
m_PlayerLoaded
protected bool m_PlayerLoaded private
m_PlayerOldPos
vector m_PlayerOldPos private
m_PlayerSoundManagerClient
ref PlayerSoundManagerClient m_PlayerSoundManagerClient private
m_PlayerSoundManagerServer
ref PlayerSoundManagerServer m_PlayerSoundManagerServer private
m_PlayerStats
ref PlayerStats m_PlayerStats private
m_PlayerStomach
ref PlayerStomach m_PlayerStomach private
m_PresenceNotifier
protected PluginPresenceNotifier m_PresenceNotifier private
m_ProcessAddEffectWidgets
protected ref array<int> m_ProcessAddEffectWidgets private
m_ProcessAddGlassesEffects
protected ref array<int> m_ProcessAddGlassesEffects private
m_ProcessRemoveEffectWidgets
protected ref array<int> m_ProcessRemoveEffectWidgets private
m_ProcessRemoveGlassesEffects
protected ref array<int> m_ProcessRemoveGlassesEffects private
m_ProcessUIWarning
protected bool m_ProcessUIWarning private
m_PulseType
EPulseType m_PulseType private
m_QBarItems
ref TStringArray m_QBarItems static private
m_QuickBarBase
ref protected QuickBarBase m_QuickBarBase private
m_QuickBarBonus
int m_QuickBarBonus = 0 private
m_QuickBarFT
bool m_QuickBarFT = false private
m_QuickBarHold
bool m_QuickBarHold private
m_RecipeAnimLength
float m_RecipeAnimLength private
m_RecipeID
int m_RecipeID = -1 private
m_RecipePick
protected int m_RecipePick private
m_Recipes
ref array<int> m_Recipes private
m_RefreshAnimStateIdx
protected int m_RefreshAnimStateIdx private
m_RGSManager
ref protected RandomGeneratorSyncManager m_RGSManager private
m_SaySoundBuilder
ref SoundObjectBuilder m_SaySoundBuilder private
m_SaySoundLastSetName
string m_SaySoundLastSetName private
m_SaySoundObject
ref SoundObject m_SaySoundObject private
m_SaySoundParams
ref SoundParams m_SaySoundParams private
m_ServerPlayers
ref array<Man> m_ServerPlayers = new array<Man> static private
m_Shakes
protected int m_Shakes private
m_ShakesForced
protected int m_ShakesForced private
m_ShockDealtEffect
ref ShockDealtEffect m_ShockDealtEffect private
m_ShockHandler
ref ShockHandler m_ShockHandler private
m_ShockSimplified
int m_ShockSimplified private
m_ShowDbgUI
bool m_ShowDbgUI = true private
m_SoftSkillsManager
ref SoftSkillsManager m_SoftSkillsManager private
m_SoundEvent
int m_SoundEvent private
m_SoundEventParam
int m_SoundEventParam private
m_SoundEventSent
bool m_SoundEventSent private
m_SoundFliesEffect
ref EffectSound m_SoundFliesEffect private
m_StaminaHandler
ref StaminaHandler m_StaminaHandler private
m_StaminaParam
ref Param3<float,float,bool> m_StaminaParam private
m_StaminaState
int m_StaminaState private
m_StanceIndicator
ref StanceIndicator m_StanceIndicator private
m_StatEnergy
protected PlayerStat<float> m_StatEnergy private
m_StatHeatComfort
protected PlayerStat<float> m_StatHeatComfort private
m_StatToxicity
protected PlayerStat<float> m_StatToxicity private
m_StatTremor
protected PlayerStat<float> m_StatTremor private
m_StatWater
protected PlayerStat<float> m_StatWater private
m_StoreLoadVersion
private int m_StoreLoadVersion private
m_SymptomManager
ref SymptomManager m_SymptomManager private
m_SyncedModifiers
int m_SyncedModifiers private
m_SyncedModifiersPrev
int m_SyncedModifiersPrev private
m_TrasferValues
ref TransferValues m_TrasferValues private
m_UALastMessage
protected string m_UALastMessage private
user actions last message
m_UALastMessageTimer
protected ref Timer m_UALastMessageTimer private
m_UAParam
ref Param2<int,int> m_UAParam private
m_UAParamMessage
ref Param1<string> m_UAParamMessage private
m_UAProgressParam
ref Param2<float,float> m_UAProgressParam private
m_UnconParam
ref Param1<float> m_UnconParam private
m_UnconRefillModifier
float m_UnconRefillModifier = 1 private
m_UnconsciousEndTime
float m_UnconsciousEndTime = 0 private
m_UnconsciousTime
float m_UnconsciousTime private
m_UnconsciousVignetteTarget
float m_UnconsciousVignetteTarget = 2 private
m_UndergroundHandler
protected ref UndergroundHandlerClient m_UndergroundHandler private
m_UndergroundPresence
EUndergroundPresence m_UndergroundPresence private
m_VirtualHud
ref VirtualHud m_VirtualHud private
m_VisibilityCoef
float m_VisibilityCoef private
m_WeaponManager
ref WeaponManager m_WeaponManager private
m_WorkingNVGHeadset
bool m_WorkingNVGHeadset private
OVERLOAD_LIMIT
const int OVERLOAD_LIMIT = 30000 private
SHAKE_LEVEL_MAX
const int SHAKE_LEVEL_MAX = 7 private
SIMPLIFIED_SHOCK_CAP
const int SIMPLIFIED_SHOCK_CAP = 63 private
SOUND_BREAK_LEG
const string SOUND_BREAK_LEG = "broken_leg_SoundSet" private
SPREAD_AGENTS_OBJECTS
ref array<Object> SPREAD_AGENTS_OBJECTS = new array<Object> static private
SPREAD_AGENTS_PROXY_CARGOS
ref array<CargoBase> SPREAD_AGENTS_PROXY_CARGOS = new array<CargoBase> static private
The documentation for this class was generated from the following file:
P:/scripts/4_world/entities/manbase/playerbase.c