DayZ Scripts: AmmoEffects Class Reference
AmmoEffects Class Reference
Static data holder for certain ammo config values.
Static Private Member Functions
Ammo particles
Methods regarding getting/playing ammo particle
static int GetAmmoParticleID (string ammoType)
Get the ParticleList ID for the particle for this ammoType.
static bool PlayAmmoParticle (string ammoType, vector pos)
Attempt to play the ammo particle at pos if found, returns true on success.
Ammo effects
Methods regarding getting/playing ammo effect
static GetAmmoEffectTypename (string ammoType)
Get the typename for the effect for this ammoType.
static bool PlayAmmoEffect (string ammoType, vector pos)
Attempt to play the ammo effect at pos if found, returns true on success.
Lifetime
Creation and cleanup
static void Init ()
Initialize the containers: this is done this way, to have these not exist on server.
static void Cleanup ()
Clean up the data.
Static Private Attributes
static ref map< string, int > m_AmmoParticles
Key: Ammo class name; Data: ParticleList ID.
static ref map< string, typename > m_AmmoEffects
Key: Ammo class name; Data: ParticleList ID.
Detailed Description
Static data holder for certain ammo config values.
Note
Kept the names similar to what is in config, but it might be a little deceiving as this is mainly used for explosives
Member Function Documentation
Cleanup()
static void Cleanup () inline static private
Clean up the data.
Referenced by CGame::~CGame().
GetAmmoEffectTypename()
static GetAmmoEffectTypename (string ammoType) inline static private
Get the typename for the effect for this ammoType.
References CGame::ConfigGetText(), GetGame(), m_AmmoEffects, and string::ToType().
Referenced by PlayAmmoEffect().
GetAmmoParticleID()
static int GetAmmoParticleID (string ammoType) inline static private
Get the ParticleList ID for the particle for this ammoType.
References CGame::ConfigGetText(), GetGame(), ParticleList::GetParticleIDByName(), and m_AmmoParticles.
Referenced by PlayAmmoParticle().
Init()
static void Init () inline static private
Initialize the containers: this is done this way, to have these not exist on server.
References m_AmmoEffects, and m_AmmoParticles.
Referenced by CGame::CGame().
PlayAmmoEffect()
static bool PlayAmmoEffect (string ammoType, vector pos) inline static private
Attempt to play the ammo effect at pos if found, returns true on success.
References Effect(), GetAmmoEffectTypename(), and SEffectManager::PlayInWorld().
Referenced by IEntity::OnExplodeClient().
PlayAmmoParticle()
static bool PlayAmmoParticle (string ammoType, vector pos) inline static private
Attempt to play the ammo particle at pos if found, returns true on success.
References GetAmmoParticleID(), ParticleList::IsValidId(), and ParticleManager().
Referenced by IEntity::OnExplodeClient().
Field Documentation
m_AmmoEffects
ref map<string, typename> m_AmmoEffects static private
Key: Ammo class name; Data: ParticleList ID.
Referenced by GetAmmoEffectTypename(), and Init().
m_AmmoParticles
ref map<string, int> m_AmmoParticles static private
Key: Ammo class name; Data: ParticleList ID.
Referenced by GetAmmoParticleID(), and Init().
The documentation for this class was generated from the following file:
3_Game/AmmoEffects.c