DayZ Scripts: ImprovisedExplosive Class Reference
ImprovisedExplosive Class Reference
Private Member Functions
void ImprovisedExplosive ()
override void EOnInit (IEntity other, int extra)
override bool HasLockedTriggerSlots ()
override void LockTriggerSlots ()
override void UnlockTriggerSlots ()
override void OnVariablesSynchronized ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
override void PairRemote (notnull EntityAI trigger)
override EntityAI GetPairDevice ()
override bool CanBeArmed ()
override bool CanBeDisarmed ()
override bool CanPutIntoHands (EntityAI parent)
override bool CanRemoveFromHands (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanDisplayAttachmentSlot (int slot_id)
override bool IsTimerDetonable ()
override bool IsTakeable ()
override bool IsDeployable ()
override void SetActions ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void OnActivatedByItem (notnull ItemBase item)
override protected void InitiateExplosion ()
not exploding itself, rely on attached explosives
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void OnDisarmed (bool pWithTool)
override void UpdateLED (int pState)
protected void OnTriggerAttached (EntityAI entity)
protected void OnTriggerDetached (EntityAI entity)
protected void UpdateVisuals (EntityAI entity)
Private Attributes
protected const float TIME_TRIGGER_INITIAL_DELAY_SECS = 0.1
protected const float TIME_TRIGGER_TIMER_BASED_DELAY_SECS = 1.0
protected const float TIME_TRIGGER_DELAY_SECS = 0.3
protected const int SLOT_EXPLOSIVE_COUNT = 2
protected const string SLOT_EXPLOSIVES [SLOT_EXPLOSIVE_COUNT]
protected const int SLOT_TRIGGERS_COUNT = 3
protected const string SLOT_TRIGGERS [SLOT_TRIGGERS_COUNT]
protected const string ANIM_PHASE_TRIGGER_EMPTY = "TriggerEmpty"
protected const string ANIM_PHASE_TRIGGER_TIMER = "TriggerTimer"
protected const string ANIM_PHASE_TRIGGER_CLOCK = "TriggerClock"
protected const string ANIM_PHASE_TRIGGER_REMOTE = "TriggerRemote"
protected ref RemotelyActivatedItemBehaviour m_RAIB
Static Private Attributes
static protected const string SLOT_TRIGGER_ALARM_CLOCK = "TriggerAlarmClock"
static protected const string SLOT_TRIGGER_KITCHEN_TIMER = "TriggerKitchenTimer"
static protected const string SLOT_TRIGGER_REMOTE = "TriggerRemoteDetonator_Receiver"
static protected const string SLOT_EXPLOSIVE_A = "IEDExplosiveA"
static protected const string SLOT_EXPLOSIVE_B = "IEDExplosiveB"
Detailed Description
Definition at line 1 of file ImprovisedExplosive.c.
Constructor & Destructor Documentation
ImprovisedExplosive()
void ImprovisedExplosive () inline private
Definition at line 34 of file ImprovisedExplosive.c.
References m_RAIB.
Member Function Documentation
CanBeArmed()
override bool CanBeArmed () inline private
Definition at line 118 of file ImprovisedExplosive.c.
References GetArmed(), HasLockedTriggerSlots(), SLOT_EXPLOSIVE_COUNT, and SLOT_EXPLOSIVES.
CanBeDisarmed()
override bool CanBeDisarmed () inline private
Definition at line 142 of file ImprovisedExplosive.c.
CanDisplayAttachmentSlot()
override bool CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 175 of file ImprovisedExplosive.c.
References InventorySlots::GetSlotName(), SLOT_TRIGGER_ALARM_CLOCK, SLOT_TRIGGER_KITCHEN_TIMER, and SLOT_TRIGGER_REMOTE.
CanPutIntoHands()
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 147 of file ImprovisedExplosive.c.
References IsTakeable().
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 157 of file ImprovisedExplosive.c.
References GetArmed(), InventorySlots::GetSlotIdFromString(), InventoryLocation::GetType(), SLOT_TRIGGERS, and SLOT_TRIGGERS_COUNT.
CanRemoveFromHands()
override bool CanRemoveFromHands (EntityAI parent) inline private
Definition at line 152 of file ImprovisedExplosive.c.
References IsTakeable().
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 214 of file ImprovisedExplosive.c.
References GetGame(), SetArmed(), SetTakeable(), and GameConstants::STATE_RUINED.
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 324 of file ImprovisedExplosive.c.
References OnTriggerAttached(), SLOT_TRIGGER_ALARM_CLOCK, SLOT_TRIGGER_KITCHEN_TIMER, and SLOT_TRIGGER_REMOTE.
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 338 of file ImprovisedExplosive.c.
References OnTriggerDetached(), SLOT_TRIGGER_ALARM_CLOCK, SLOT_TRIGGER_KITCHEN_TIMER, and SLOT_TRIGGER_REMOTE.
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 93 of file ImprovisedExplosive.c.
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
EOnInit()
override void EOnInit (IEntity other, int extra) inline private
Definition at line 42 of file ImprovisedExplosive.c.
References LockTriggerSlots().
GetPairDevice()
override EntityAI GetPairDevice () inline private
Definition at line 113 of file ImprovisedExplosive.c.
References RemotelyActivatedItemBehaviour::GetPairDevice(), and m_RAIB.
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour () inline private
Definition at line 103 of file ImprovisedExplosive.c.
References m_RAIB.
HasLockedTriggerSlots()
override bool HasLockedTriggerSlots () inline private
Definition at line 47 of file ImprovisedExplosive.c.
References InventorySlots::GetSlotIdFromString(), SLOT_TRIGGERS, and SLOT_TRIGGERS_COUNT.
Referenced by CanBeArmed().
InitiateExplosion()
override protected void InitiateExplosion () private
not exploding itself, rely on attached explosives
IsDeployable()
override bool IsDeployable () inline private
Definition at line 201 of file ImprovisedExplosive.c.
References GetArmed().
IsTakeable()
override bool IsTakeable () inline private
Definition at line 196 of file ImprovisedExplosive.c.
References GetArmed().
Referenced by CanPutIntoHands(), and CanRemoveFromHands().
IsTimerDetonable()
override bool IsTimerDetonable () inline private
Definition at line 191 of file ImprovisedExplosive.c.
LockTriggerSlots()
override void LockTriggerSlots () inline private
Definition at line 57 of file ImprovisedExplosive.c.
References InventorySlots::GetSlotIdFromString(), SLOT_TRIGGERS, and SLOT_TRIGGERS_COUNT.
Referenced by EOnInit(), and OnDisarmed().
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item) inline private
cache attachments
unlock attachments first
triggers specific handling
go through attached explosives
defer delete to allow ringing
final traverse - attached explosives activation
defer damage to trigger attachments to allow ringing
Definition at line 238 of file ImprovisedExplosive.c.
References ANIM_PHASE_VISIBILITY, CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), ScriptCallQueue::CallLaterByName(), ClockBase(), GetArmed(), CGame::GetCallQueue(), GetGame(), TIME_TRIGGER_DELAY_SECS, TIME_TRIGGER_INITIAL_DELAY_SECS, and TIME_TRIGGER_TIMER_BASED_DELAY_SECS.
OnDisarmed()
override void OnDisarmed (bool pWithTool) inline private
Definition at line 352 of file ImprovisedExplosive.c.
References ClockBase(), LockTriggerSlots(), SetTakeable(), and UnpairRemote().
OnTriggerAttached()
protected void OnTriggerAttached (EntityAI entity) inline private
Definition at line 401 of file ImprovisedExplosive.c.
References Arm(), ClockBase(), UpdateLED(), and UpdateVisuals().
Referenced by EEItemAttached().
OnTriggerDetached()
protected void OnTriggerDetached (EntityAI entity) inline private
Definition at line 421 of file ImprovisedExplosive.c.
References UpdateLED(), and UpdateVisuals().
Referenced by EEItemDetached().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Definition at line 73 of file ImprovisedExplosive.c.
References m_RAIB, RemotelyActivatedItemBehaviour::OnVariableSynchronized(), SLOT_TRIGGERS, SLOT_TRIGGERS_COUNT, and UpdateVisuals().
PairRemote()
override void PairRemote (notnull EntityAI trigger) inline private
Definition at line 108 of file ImprovisedExplosive.c.
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
SetActions()
override void SetActions () inline private
Definition at line 206 of file ImprovisedExplosive.c.
References ActionDeployObject(), and AddAction().
UnlockTriggerSlots()
override void UnlockTriggerSlots () inline private
Definition at line 65 of file ImprovisedExplosive.c.
References InventorySlots::GetSlotIdFromString(), SLOT_TRIGGERS, and SLOT_TRIGGERS_COUNT.
UpdateLED()
override void UpdateLED (int pState) inline private
Definition at line 392 of file ImprovisedExplosive.c.
References RemoteDetonatorReceiver(), and SLOT_TRIGGER_REMOTE.
Referenced by OnTriggerAttached(), and OnTriggerDetached().
UpdateVisuals()
protected void UpdateVisuals (EntityAI entity) inline private
Definition at line 427 of file ImprovisedExplosive.c.
References ANIM_PHASE_TRIGGER_CLOCK, ANIM_PHASE_TRIGGER_EMPTY, ANIM_PHASE_TRIGGER_REMOTE, and ANIM_PHASE_TRIGGER_TIMER.
Field Documentation
ANIM_PHASE_TRIGGER_CLOCK
protected const string ANIM_PHASE_TRIGGER_CLOCK = "TriggerClock" private
Definition at line 29 of file ImprovisedExplosive.c.
Referenced by UpdateVisuals().
ANIM_PHASE_TRIGGER_EMPTY
protected const string ANIM_PHASE_TRIGGER_EMPTY = "TriggerEmpty" private
Definition at line 27 of file ImprovisedExplosive.c.
Referenced by UpdateVisuals().
ANIM_PHASE_TRIGGER_REMOTE
protected const string ANIM_PHASE_TRIGGER_REMOTE = "TriggerRemote" private
Definition at line 30 of file ImprovisedExplosive.c.
Referenced by UpdateVisuals().
ANIM_PHASE_TRIGGER_TIMER
protected const string ANIM_PHASE_TRIGGER_TIMER = "TriggerTimer" private
Definition at line 28 of file ImprovisedExplosive.c.
Referenced by UpdateVisuals().
m_RAIB
protected ref RemotelyActivatedItemBehaviour m_RAIB private
Definition at line 32 of file ImprovisedExplosive.c.
Referenced by EEItemLocationChanged(), GetPairDevice(), GetRemotelyActivatedItemBehaviour(), ImprovisedExplosive(), OnVariablesSynchronized(), and PairRemote().
SLOT_EXPLOSIVE_A
protected const string SLOT_EXPLOSIVE_A = "IEDExplosiveA" static private
Definition at line 11 of file ImprovisedExplosive.c.
SLOT_EXPLOSIVE_B
protected const string SLOT_EXPLOSIVE_B = "IEDExplosiveB" static private
Definition at line 12 of file ImprovisedExplosive.c.
SLOT_EXPLOSIVE_COUNT
protected const int SLOT_EXPLOSIVE_COUNT = 2 private
Definition at line 14 of file ImprovisedExplosive.c.
Referenced by CanBeArmed().
SLOT_EXPLOSIVES
protected const string SLOT_EXPLOSIVES[SLOT_EXPLOSIVE_COUNT] private
Initial value:
= {
        SLOT_EXPLOSIVE_A,
        SLOT_EXPLOSIVE_B
    }
Definition at line 15 of file ImprovisedExplosive.c.
Referenced by CanBeArmed().
SLOT_TRIGGER_ALARM_CLOCK
protected const string SLOT_TRIGGER_ALARM_CLOCK = "TriggerAlarmClock" static private
Definition at line 7 of file ImprovisedExplosive.c.
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), and EEItemDetached().
SLOT_TRIGGER_KITCHEN_TIMER
protected const string SLOT_TRIGGER_KITCHEN_TIMER = "TriggerKitchenTimer" static private
Definition at line 8 of file ImprovisedExplosive.c.
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), and EEItemDetached().
SLOT_TRIGGER_REMOTE
protected const string SLOT_TRIGGER_REMOTE = "TriggerRemoteDetonator_Receiver" static private
Definition at line 9 of file ImprovisedExplosive.c.
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), EEItemDetached(), and UpdateLED().
SLOT_TRIGGERS
protected const string SLOT_TRIGGERS[SLOT_TRIGGERS_COUNT] private
Initial value:
= {
        SLOT_TRIGGER_ALARM_CLOCK,
        SLOT_TRIGGER_KITCHEN_TIMER,
        SLOT_TRIGGER_REMOTE
    }
Definition at line 21 of file ImprovisedExplosive.c.
Referenced by CanReceiveAttachment(), HasLockedTriggerSlots(), LockTriggerSlots(), OnVariablesSynchronized(), and UnlockTriggerSlots().
SLOT_TRIGGERS_COUNT
protected const int SLOT_TRIGGERS_COUNT = 3 private
Definition at line 20 of file ImprovisedExplosive.c.
Referenced by CanReceiveAttachment(), HasLockedTriggerSlots(), LockTriggerSlots(), OnVariablesSynchronized(), and UnlockTriggerSlots().
TIME_TRIGGER_DELAY_SECS
protected const float TIME_TRIGGER_DELAY_SECS = 0.3 private
Definition at line 5 of file ImprovisedExplosive.c.
Referenced by OnActivatedByItem().
TIME_TRIGGER_INITIAL_DELAY_SECS
protected const float TIME_TRIGGER_INITIAL_DELAY_SECS = 0.1 private
Definition at line 3 of file ImprovisedExplosive.c.
Referenced by OnActivatedByItem().
TIME_TRIGGER_TIMER_BASED_DELAY_SECS
protected const float TIME_TRIGGER_TIMER_BASED_DELAY_SECS = 1.0 private
Definition at line 4 of file ImprovisedExplosive.c.
Referenced by OnActivatedByItem().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ExplosivesBase/ImprovisedExplosive.c