DayZ Scripts: EyeMask_ColorBase Class Reference
EyeMask_ColorBase Class Reference
Private Member Functions
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=null)
override bool CanIgniteItem (EntityAI ignite_target=null)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=null)
override void SetActions ()
Member Function Documentation
CanBeIgnitedBy()
override bool CanBeIgnitedBy (EntityAI igniter = null) inline private
CanIgniteItem()
override bool CanIgniteItem (EntityAI ignite_target = null) inline private
HasFlammableMaterial()
override bool HasFlammableMaterial () inline private
IsThisIgnitionSuccessful()
override bool IsThisIgnitionSuccessful (EntityAI item_source = null) inline private
OnIgnitedTarget()
override void OnIgnitedTarget (EntityAI ignited_item) inline private
OnIgnitedThis()
override void OnIgnitedThis (EntityAI fire_source) inline private
SetActions()
override void SetActions () inline private
References ActionAttach(), ActionDetach(), and AddAction().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/EyeMask_Colorbase.c