DayZ Scripts: HandsHeader Class Reference
HandsHeader Class Reference
Private Member Functions
void HandsHeader (LayoutHolder parent, string function_name)
override void SetLayoutName ()
override void UpdateInterval ()
void ShowCollapseButtons (bool show, bool force=false)
Private Attributes
protected bool m_ForceHideCollapseButtons
protected Widget m_ItemHeader
Detailed Description
Definition at line 1 of file HandsHeader.c.
Constructor & Destructor Documentation
HandsHeader()
void HandsHeader (LayoutHolder parent, string function_name) inline private
Definition at line 6 of file HandsHeader.c.
References Header::m_DefaultColor, Header::m_DefaultFontSize, m_ItemHeader, and ShowCollapseButtons().
Member Function Documentation
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 18 of file HandsHeader.c.
References WidgetLayoutName::HandsHeader.
ShowCollapseButtons()
void ShowCollapseButtons (bool show, bool force = false) inline private
Definition at line 45 of file HandsHeader.c.
References Header::m_CollapseButton, and m_ForceHideCollapseButtons.
Referenced by HandsHeader(), HandsContainer::RemoveItem(), HandsContainer::ShowAtt(), and UpdateInterval().
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 23 of file HandsHeader.c.
References GetGame(), GetPlayer(), m_ForceHideCollapseButtons, m_ItemHeader, and ShowCollapseButtons().
Referenced by HandsContainer::UpdateInterval().
Field Documentation
m_ForceHideCollapseButtons
protected bool m_ForceHideCollapseButtons private
Definition at line 3 of file HandsHeader.c.
Referenced by ShowCollapseButtons(), and UpdateInterval().
m_ItemHeader
protected Widget m_ItemHeader private
Definition at line 4 of file HandsHeader.c.
Referenced by HandsHeader(), and UpdateInterval().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/ContainedItems/Headers/HandsHeader.c