DayZ Scripts: P:/scripts/3_Game/Entities/DayZAnimal.c File Reference
DayZAnimal.c File Reference
Data Structures
class DayZCreatureAnimInterface
class DayZCreature
class AnimCommandBase
base class of all commands exposed to script to provide common functionality over animations
class DayZCreatureAI
do not process rotations !
Functions
class DayZCreatureAnimInterface RegisterAnimationEvent (string event_name, string function_name)
private void DayZCreatureAnimInterface ()
private void ~DayZCreatureAnimInterface ()
proto native TAnimGraphCommand BindCommand (string pCommandName)
returns command index -
proto native TAnimGraphVariable BindVariableFloat (string pVariable)
proto native TAnimGraphVariable BindVariableInt (string pVariable)
proto native TAnimGraphVariable BindVariableBool (string pVariable)
proto native TAnimGraphTag BindTag (string pTagName)
proto native TAnimGraphEvent BindEvent (string pEventName)
proto native void SetAnimationInstanceByName (string animation_instance_name, int instance_uuid, float duration)
proto native int GetCurrentAnimationInstanceUUID ()
proto native DayZCreatureAnimInterface GetAnimInterface ()
proto native void UpdateSimulationPrecision (int simLOD)
proto native void StartDeath ()
proto native void ResetDeath ()
proto native void ResetDeathCooldown ()
proto native bool IsDeathProcessed ()
proto native bool IsDeathConditionMet ()
proto native int GetBoneIndexByName (string pBoneName)
returns bone index for a name (-1 if pBoneName doesn't exist)
override bool IsDayZCreature ()
override bool CanBeSkinned ()
override bool IsIgnoredByConstruction ()
override bool IsManagingArrows ()
override void AddArrow (Object arrow, int componentIndex, vector closeBonePosWS, vector closeBoneRotWS)
override bool HasFixedActionTargetCursorPosition ()
bool ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
class DayZAnimalCommandMove extends AnimCommandBase SetFlagFinished (bool pFinished)
DayZAnimalCommandScript fully scriptable command.
proto native bool PrePhys_GetTranslation (out vector pOutTransl)
script function usable in PrePhysUpdate
proto native bool PrePhys_GetRotation (out float pOutRot[4])
proto native void PrePhys_SetTranslation (vector pInTransl)
proto native void PrePhys_SetRotation (float pInRot[4])
bool PostPhysUpdate (float pDt)
proto native void PostPhys_GetPosition (out vector pOutTransl)
script function usable in PostPhysUpdate
proto native void PostPhys_GetRotation (out float pOutRot[4])
vec3 in world space
proto native void PostPhys_SetPosition (vector pInTransl)
quaternion in world space
proto native void PostPhys_SetRotation (float pInRot[4])
vec3 in world space
proto native void PostPhys_LockRotation ()
quaternion in world space
Variables
class DayZCreatureAI extends DayZCreature COMMANDID_MOVE
class DayZCreatureAI extends DayZCreature COMMANDID_JUMP
class DayZCreatureAI extends DayZCreature COMMANDID_DEATH
class DayZCreatureAI extends DayZCreature COMMANDID_HIT
class DayZCreatureAI extends DayZCreature COMMANDID_ATTACK
class DayZCreatureAI extends DayZCreature COMMANDID_SCRIPT
Function Documentation
AddArrow()
override void AddArrow (Object arrow, int componentIndex, vector closeBonePosWS, vector closeBoneRotWS)
References AddChild(), CachedObjectsArrays::ARRAY_STRING, GetBoneIndexByName(), Math3D::MatrixInvMultiply4(), Math3D::MatrixOrthogonalize4(), Math::RAD2DEG, and Math3D::YawPitchRollMatrix().
BindCommand()
proto native TAnimGraphCommand BindCommand (string pCommandName)
returns command index -
BindEvent()
proto native TAnimGraphEvent BindEvent (string pEventName)
BindTag()
proto native TAnimGraphTag BindTag (string pTagName)
BindVariableBool()
proto native TAnimGraphVariable BindVariableBool (string pVariable)
BindVariableFloat()
proto native TAnimGraphVariable BindVariableFloat (string pVariable)
BindVariableInt()
proto native TAnimGraphVariable BindVariableInt (string pVariable)
CanBeSkinned()
override bool CanBeSkinned ()
DayZCreatureAnimInterface()
private void DayZCreatureAnimInterface ()
GetAnimInterface()
proto native DayZCreatureAnimInterface GetAnimInterface ()
GetBoneIndexByName()
proto native int GetBoneIndexByName (string pBoneName)
returns bone index for a name (-1 if pBoneName doesn't exist)
Referenced by AddArrow(), DayZInfected::AddArrow(), ManBase::AddArrow(), DayZInfected::GetCenter(), ManBase::GetCenter(), ManBase::GetDrowningWaterLevelCheck(), ManBase::SetDecayEffects(), ManBase::SpawnBreathVaporEffect(), and ManBase::SpawnDrowningBubbles().
GetCurrentAnimationInstanceUUID()
proto native int GetCurrentAnimationInstanceUUID ()
HasFixedActionTargetCursorPosition()
override bool HasFixedActionTargetCursorPosition ()
Referenced by ActionTargetsCursor::GetOnScreenPosition().
IsDayZCreature()
override bool IsDayZCreature ()
Referenced by IEntity::CanBeIgnoredByDroppedItem().
IsDeathConditionMet()
proto native bool IsDeathConditionMet ()
IsDeathProcessed()
proto native bool IsDeathProcessed ()
IsIgnoredByConstruction()
override bool IsIgnoredByConstruction ()
IsManagingArrows()
override bool IsManagingArrows ()
ModCommandHandlerAfter()
bool ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
Referenced by DayZCreatureAI::CommandHandler(), DayZInfected::CommandHandler(), and DayZPlayer::CommandHandler().
ModCommandHandlerBefore()
bool ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
ModOverrides
Referenced by DayZCreatureAI::CommandHandler(), DayZInfected::CommandHandler(), and DayZPlayer::CommandHandler().
ModCommandHandlerInside()
bool ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
Referenced by DayZCreatureAI::CommandHandler(), DayZInfected::CommandHandler(), and DayZPlayer::CommandHandler().
PostPhys_GetPosition()
proto native void PostPhys_GetPosition (out vector pOutTransl)
script function usable in PostPhysUpdate
PostPhys_GetRotation()
proto native void PostPhys_GetRotation (out float pOutRot[4])
vec3 in world space
PostPhys_LockRotation()
proto native void PostPhys_LockRotation ()
quaternion in world space
PostPhys_SetPosition()
proto native void PostPhys_SetPosition (vector pInTransl)
quaternion in world space
PostPhys_SetRotation()
proto native void PostPhys_SetRotation (float pInRot[4])
vec3 in world space
PostPhysUpdate()
bool PostPhysUpdate (float pDt)
override this ! final adjustment of physics state (after physics was applied) returns true if command continues running / false if command should end (or you can use SetFlagFinished(true))
PrePhys_GetRotation()
proto native bool PrePhys_GetRotation (out float pOutRot[4])
PrePhys_GetTranslation()
proto native bool PrePhys_GetTranslation (out vector pOutTransl)
script function usable in PrePhysUpdate
PrePhys_SetRotation()
proto native void PrePhys_SetRotation (float pInRot[4])
PrePhys_SetTranslation()
proto native void PrePhys_SetTranslation (vector pInTransl)
RegisterAnimationEvent()
class DayZCreatureAnimInterface RegisterAnimationEvent (string event_name, string function_name)
Referenced by ActionUnfoldMapCB::ActionUnfoldMapCB(), ActionContinuousBaseCB::InitActionComponent(), ActionInteractBaseCB::InitActionComponent(), ActionSingleUseBaseCB::InitActionComponent(), ActionActivateTrapCB::InitActionComponent(), ActionArmExplosiveCB::InitActionComponent(), and DayZCreature::RegisterAnimEvents().
ResetDeath()
proto native void ResetDeath ()
ResetDeathCooldown()
proto native void ResetDeathCooldown ()
Referenced by DayZPlayer::ResetDeathStartTime(), and DayZPlayer::TriggerPullPlayerOutOfVehicleImpl().
SetAnimationInstanceByName()
proto native void SetAnimationInstanceByName (string animation_instance_name, int instance_uuid, float duration)
SetFlagFinished()
class DayZAnimalCommandMove extends AnimCommandBase SetFlagFinished (bool pFinished)
DayZAnimalCommandScript fully scriptable command.
Warning
NON-MANAGED, will be managed by C++ once it is sent to the CommandHandler through DayZAnimal.StartCommand_Script
Note
So ideally, it is best to set up the DayZAnimalCommandScript, not create any instances and start it through DayZAnimal.StartCommand_ScriptInst In case an instance needs to be created, it needs manual deletion if not sent to the CommandHandler But deleting it while it is in the CommandHandler will cause crashes constructor must have 1st parameter to be DayZAnimal this terminates command script and shows CommandHandler(... pCurrentCommandFinished == true);
StartDeath()
proto native void StartDeath ()
UpdateSimulationPrecision()
proto native void UpdateSimulationPrecision (int simLOD)
~DayZCreatureAnimInterface()
private void ~DayZCreatureAnimInterface ()
Variable Documentation
COMMANDID_ATTACK
class DayZCreatureAI extends DayZCreature COMMANDID_ATTACK
COMMANDID_DEATH
class DayZCreatureAI extends DayZCreature COMMANDID_DEATH
COMMANDID_HIT
class DayZCreatureAI extends DayZCreature COMMANDID_HIT
COMMANDID_JUMP
class DayZCreatureAI extends DayZCreature COMMANDID_JUMP
COMMANDID_MOVE
class DayZCreatureAI extends DayZCreature COMMANDID_MOVE
COMMANDID_SCRIPT
class DayZCreatureAI extends DayZCreature COMMANDID_SCRIPT