DayZ Scripts: RestCallback Class Reference
RestCallback Class Reference
Private Member Functions
void OnError (int errorCode)
Called in case request failed (ERestResultState) - Note! May be called multiple times in case of (RetryCount > 1)
void OnTimeout ()
Called in case request timed out or handled improperly (no error, no success, no data)
void OnSuccess (string data, int dataSize)
Called when data arrived and/ or response processed successfully.
void OnFileCreated (string fileName, int dataSize)
Called when data arrived and/ or file created successfully.
Member Function Documentation
OnError()
void OnError (int errorCode) inline private
Called in case request failed (ERestResultState) - Note! May be called multiple times in case of (RetryCount > 1)
References Print().
OnFileCreated()
void OnFileCreated (string fileName, int dataSize) inline private
Called when data arrived and/ or file created successfully.
References Print().
OnSuccess()
void OnSuccess (string data, int dataSize) inline private
Called when data arrived and/ or response processed successfully.
References Print().
OnTimeout()
void OnTimeout () inline private
Called in case request timed out or handled improperly (no error, no success, no data)
References Print().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Http/RestApi.c