DayZ Scripts: BoatScript Class Reference
BoatScript Class Reference
Private Member Functions
void BoatScript ()
void ~BoatScript ()
override void EEDelete (EntityAI parent)
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
override bool DisableVicinityIcon ()
override string GetVehicleType ()
override bool IsInventoryVisible ()
override float GetTransportCameraDistance ()
override vector GetTransportCameraOffset ()
override int GetAnimInstance ()
override int Get3rdPersonCameraType ()
override bool CrewCanGetThrough (int posIdx)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachSeatFromDoors (string pSeatSelection, vector pFromPos, float pDistance=1.0)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight, inout vector extents, out vector transform[4])
override bool OnBeforeEngineStart ()
override void OnEngineStart ()
override void OnEngineStop ()
override void EEOnCECreate ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override void EOnSimulate (IEntity other, float timeSlice)
override void EOnFrame (IEntity other, float timeSlice)
override void EOnContact (IEntity other, Contact extra)
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void OnVariablesSynchronized ()
override float OnSound (BoatSoundCtrl ctrl, float oldValue)
override void HandleByCrewMemberState (ECrewMemberState state)
bool CheckOperationalState ()
void OnVehicleJumpOutServer (GetOutTransportActionData data)
protected void HandleEngineSound (EBoatEngineSoundState state)
protected void PlaySound (string soundset, inout EffectSound sound)
protected void HandleBoatSplashSound ()
protected void SyncSoundImpactLight ()
protected void SyncSoundImpactHeavy ()
void SyncSoundPushBoat (bool play)
protected void FadeEngineSound (bool fadeIn)
protected void CheckContactCache ()
protected void SetActions ()
void AddAction (typename actionName)
void RemoveAction (typename actionName)
protected void UpdateParticles ()
protected void StopParticleUpdate ()
protected void ClearWaterEffects ()
protected void CleanupEffects ()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
protected override event GetOwnerStateType ()
protected override event GetMoveType ()
Private Attributes
protected const float SOUND_ENGINE_FADE = 0.2
protected const float SPLASH_THRESHOLD_CONDITION = 0.08
protected const float SPLASH_THRESHOLD = 0.18
private TInputActionMap m_InputActionMap
private bool m_ActionsInitialized
protected vector m_VelocityPrevTick
protected float m_MomentumPrevTick
protected ref VehicleContactData m_ContactData
protected bool m_UpdateParticles
protected ref EffectBoatWaterBase m_WaterEffects [4]
protected bool m_SplashIncoming
protected bool m_PlaySoundEngineStopNoFuel
protected bool m_PlaySoundImpactLight
protected bool m_PlaySoundImpactHeavy
protected bool m_PlaySoundPushBoat
protected bool m_IsEngineSoundFading
protected bool m_EngineFadeDirection
protected float m_EngineFadeTime
protected string m_SoundImpactLight
protected string m_SoundImpactHeavy
protected string m_SoundPushBoat
protected string m_SoundWaterSplash
protected ref EffectSound m_SoundImpactLightEffect
protected ref EffectSound m_SoundImpactHeavyEffect
protected ref EffectSound m_SoundPushBoatEffect
protected ref EffectSound m_SoundWaterSplashEffect
Static Private Attributes
static private ref map< typename, ref TInputActionMap > m_BoatTypeActionsMap = new map<typename, ref TInputActionMap>()
Constructor & Destructor Documentation
BoatScript()
void BoatScript () inline private
References EffectBoatWaterBase::AttachTo(), EffectBoatWaterFront(), EffectBoatWaterSide(), GetGame(), m_PlaySoundImpactHeavy, m_PlaySoundImpactLight, m_SoundImpactHeavy, m_SoundImpactLight, m_SoundPushBoat, m_SoundWaterSplash, and m_WaterEffects.
~BoatScript()
void ~BoatScript () inline private
References CleanupEffects().
Member Function Documentation
AddAction()
void AddAction (typename actionName) inline private
References Debug::ActionLog(), ActionManagerBase(), ActionBase::GetInputType(), LogManager::IsActionLogEnable(), Debug::LogError(), m_ActionsInitialized, and m_InputActionMap.
Referenced by SetActions().
CanReachDoorsFromSeat()
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
CanReachSeatFromDoors()
override bool CanReachSeatFromDoors (string pSeatSelection, vector pFromPos, float pDistance = 1.0) inline private
CanReachSeatFromSeat()
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
CheckContactCache()
protected void CheckContactCache () inline private
References Math::AbsInt(), GameConstants::CARS_CONTACT_DMG_MIN, GameConstants::CARS_CONTACT_DMG_THRESHOLD, m_ContactData, VehicleContactData::m_Impulse, SyncSoundImpactHeavy(), and SyncSoundImpactLight().
Referenced by EOnPostSimulate().
CheckOperationalState()
bool CheckOperationalState () inline private
References GameConstants::STATE_RUINED.
Referenced by ActionCondition(), EEHitBy(), and EOnContact().
CleanupEffects()
protected void CleanupEffects () inline private
References SEffectManager::DestroyEffect(), SEffectManager::EffectUnregisterEx(), IsRegistered(), m_SoundImpactHeavyEffect, m_SoundImpactLightEffect, m_SoundPushBoatEffect, m_SoundWaterSplashEffect, m_WaterEffects, and EffectParticle::Stop().
Referenced by EEDelete(), and ~BoatScript().
ClearWaterEffects()
protected void ClearWaterEffects () inline private
References CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), GetGame(), EffectParticle::GetParticle(), GetParticle(), IsPlaying(), m_WaterEffects, ScriptCallQueue::Remove(), Particle::SetParticleParam(), EffectParticle::Stop(), and StopParticleUpdate().
Referenced by OnEngineStart(), and StopParticleUpdate().
CrewCanGetThrough()
override bool CrewCanGetThrough (int posIdx) inline private
DisableVicinityIcon()
override bool DisableVicinityIcon () inline private
EEDelete()
override void EEDelete (EntityAI parent) inline private
References CleanupEffects(), and GetGame().
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
References CheckOperationalState(), component, and GetGame().
EEOnCECreate()
override void EEOnCECreate () inline private
References Math::RandomFloat().
EOnContact()
override void EOnContact (IEntity other, Contact extra) inline private
References CheckOperationalState(), vector::Dot(), GetGame(), GetVelocity(), m_ContactData, m_MomentumPrevTick, m_VelocityPrevTick, vector::Normalized(), Contact::Position, and VehicleContactData::SetData().
EOnFrame()
override void EOnFrame (IEntity other, float timeSlice) inline private
References GetGame(), m_EngineFadeTime, m_IsEngineSoundFading, m_UpdateParticles, and UpdateParticles().
EOnPostSimulate()
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
References CheckContactCache(), GetGame(), GetVelocity(), HandleBoatSplashSound(), HandleByCrewMemberState(), m_MomentumPrevTick, m_PlaySoundEngineStopNoFuel, m_UpdateParticles, and m_VelocityPrevTick.
EOnSimulate()
override void EOnSimulate (IEntity other, float timeSlice) inline private
References dBodyGetWorldTransform(), GetGame(), and IsProxy().
FadeEngineSound()
protected void FadeEngineSound (bool fadeIn) inline private
References m_EngineFadeDirection, m_EngineFadeTime, m_IsEngineSoundFading, and SOUND_ENGINE_FADE.
Referenced by OnEngineStart(), and OnEngineStop().
Get3rdPersonCameraType()
override int Get3rdPersonCameraType () inline private
References DayZPlayerCameras::DAYZCAMERA_3RD_VEHICLE.
GetActions()
override void GetActions (typename action_input_type , out array< ActionBase_Basic > actions) inline private
References InitializeActions(), m_ActionsInitialized, and m_InputActionMap.
GetAnimInstance()
override int GetAnimInstance () inline private
GetDebugActions()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline private
References SAT_DEBUG_ACTION.
GetMoveType()
protected override event GetMoveType () inline private
GetOwnerStateType()
protected override event GetOwnerStateType () inline private
GetTransportCameraDistance()
override float GetTransportCameraDistance () inline private
GetTransportCameraOffset()
override vector GetTransportCameraOffset () inline private
GetVehicleType()
override string GetVehicleType () inline private
HandleBoatSplashSound()
protected void HandleBoatSplashSound () inline private
References SEffectManager::CreateSound(), dBodyGetVelocityAt(), GetGame(), GetPosition, Math::InverseLerp(), m_SoundWaterSplash, m_SoundWaterSplashEffect, m_SplashIncoming, vector::Normalize(), EffectSound::SetAutodestroy(), EffectSound::SetSoundVolume(), SPLASH_THRESHOLD, SPLASH_THRESHOLD_CONDITION, EffectSound::Start(), and CGame::SurfaceGetSeaLevel().
Referenced by EOnPostSimulate().
HandleByCrewMemberState()
override void HandleByCrewMemberState (ECrewMemberState state) inline private
Referenced by EOnPostSimulate().
HandleEngineSound()
protected void HandleEngineSound (EBoatEngineSoundState state) inline private
References GetGame(), SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnBeforeEngineStart(), OnEngineStart(), OnEngineStop(), and OnVariablesSynchronized().
InitializeActions()
void InitializeActions () inline private
References m_BoatTypeActionsMap, m_InputActionMap, SetActions(), and Type.
Referenced by GetActions().
IsAreaAtDoorFree()
override bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight, inout vector extents, out vector transform[4]) inline private
IsInventoryVisible()
override bool IsInventoryVisible () inline private
References GetGame(), and GetPlayer().
OnAction()
override bool OnAction (int action_id, Man player, ParamsReadContext ctx) inline private
References GetGame().
OnBeforeEngineStart()
override bool OnBeforeEngineStart () inline private
References HandleEngineSound().
OnEngineStart()
override void OnEngineStart () inline private
References ClearWaterEffects(), FadeEngineSound(), GetGame(), and HandleEngineSound().
OnEngineStop()
override void OnEngineStop () inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), dBodyGetWorldTransform(), FadeEngineSound(), CGame::GetCallQueue(), GetGame(), HandleEngineSound(), and StopParticleUpdate().
OnSound()
override float OnSound (BoatSoundCtrl ctrl, float oldValue) inline private
References Math::InverseLerp(), m_EngineFadeDirection, m_EngineFadeTime, m_IsEngineSoundFading, and SOUND_ENGINE_FADE.
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References HandleEngineSound(), EffectSound::IsPlaying(), m_PlaySoundEngineStopNoFuel, m_PlaySoundImpactHeavy, m_PlaySoundImpactLight, m_PlaySoundPushBoat, m_SoundImpactHeavy, m_SoundImpactHeavyEffect, m_SoundImpactLight, m_SoundImpactLightEffect, m_SoundPushBoat, m_SoundPushBoatEffect, PlaySound(), and EffectSound::Stop().
OnVehicleJumpOutServer()
void OnVehicleJumpOutServer (GetOutTransportActionData data) inline private
References Math::Clamp(), ActionGetOutTransport::HEALTH_HIGH_SPEED_VALUE, ActionGetOutTransport::HEALTH_LOW_SPEED_VALUE, Math::InverseLerp(), and GetOutTransportActionData::m_Speed.
Referenced by ActionGetOutTransport::ApplyJumpOutDmg().
PlaySound()
protected void PlaySound (string soundset, inout EffectSound sound) inline private
References GetPosition, SEffectManager::PlaySoundCachedParams(), and EffectSound::SetAutodestroy().
RemoveAction()
void RemoveAction (typename actionName) inline private
References GetGame(), ActionBase::GetInputType(), GetPlayer(), and m_InputActionMap.
SetActions()
protected void SetActions () inline private
References AddAction().
Referenced by InitializeActions().
StopParticleUpdate()
protected void StopParticleUpdate () inline private
References ClearWaterEffects(), and m_UpdateParticles.
Referenced by ClearWaterEffects(), and OnEngineStop().
SyncSoundImpactHeavy()
protected void SyncSoundImpactHeavy () inline private
References m_PlaySoundImpactHeavy.
Referenced by CheckContactCache().
SyncSoundImpactLight()
protected void SyncSoundImpactLight () inline private
References m_PlaySoundImpactLight.
Referenced by CheckContactCache().
SyncSoundPushBoat()
void SyncSoundPushBoat (bool play) inline private
References m_PlaySoundPushBoat.
Referenced by ActionPushBoat::OnEndServer(), and ActionPushBoat::OnStartServer().
UpdateParticles()
protected void UpdateParticles () inline private
References m_WaterEffects, and EffectBoatWaterBase::Update().
Referenced by EOnFrame().
Field Documentation
m_ActionsInitialized
private bool m_ActionsInitialized private
Referenced by AddAction(), and GetActions().
m_BoatTypeActionsMap
private ref map<typename, ref TInputActionMap> m_BoatTypeActionsMap = new map<typename, ref TInputActionMap>() static private
Referenced by InitializeActions().
m_ContactData
protected ref VehicleContactData m_ContactData private
Referenced by CheckContactCache(), and EOnContact().
m_EngineFadeDirection
protected bool m_EngineFadeDirection private
Referenced by FadeEngineSound(), and OnSound().
m_EngineFadeTime
protected float m_EngineFadeTime private
Referenced by EOnFrame(), FadeEngineSound(), and OnSound().
m_InputActionMap
private TInputActionMap m_InputActionMap private
Referenced by AddAction(), GetActions(), InitializeActions(), and RemoveAction().
m_IsEngineSoundFading
protected bool m_IsEngineSoundFading private
Referenced by EOnFrame(), FadeEngineSound(), and OnSound().
m_MomentumPrevTick
protected float m_MomentumPrevTick private
Referenced by EOnContact(), and EOnPostSimulate().
m_PlaySoundEngineStopNoFuel
protected bool m_PlaySoundEngineStopNoFuel private
Referenced by EOnPostSimulate(), and OnVariablesSynchronized().
m_PlaySoundImpactHeavy
protected bool m_PlaySoundImpactHeavy private
Referenced by BoatScript(), OnVariablesSynchronized(), and SyncSoundImpactHeavy().
m_PlaySoundImpactLight
protected bool m_PlaySoundImpactLight private
Referenced by BoatScript(), OnVariablesSynchronized(), and SyncSoundImpactLight().
m_PlaySoundPushBoat
protected bool m_PlaySoundPushBoat private
Referenced by OnVariablesSynchronized(), and SyncSoundPushBoat().
m_SoundImpactHeavy
protected string m_SoundImpactHeavy private
Referenced by BoatScript(), and OnVariablesSynchronized().
m_SoundImpactHeavyEffect
protected ref EffectSound m_SoundImpactHeavyEffect private
Referenced by CleanupEffects(), and OnVariablesSynchronized().
m_SoundImpactLight
protected string m_SoundImpactLight private
Referenced by BoatScript(), and OnVariablesSynchronized().
m_SoundImpactLightEffect
protected ref EffectSound m_SoundImpactLightEffect private
Referenced by CleanupEffects(), and OnVariablesSynchronized().
m_SoundPushBoat
protected string m_SoundPushBoat private
Referenced by BoatScript(), and OnVariablesSynchronized().
m_SoundPushBoatEffect
protected ref EffectSound m_SoundPushBoatEffect private
Referenced by CleanupEffects(), and OnVariablesSynchronized().
m_SoundWaterSplash
protected string m_SoundWaterSplash private
Referenced by BoatScript(), and HandleBoatSplashSound().
m_SoundWaterSplashEffect
protected ref EffectSound m_SoundWaterSplashEffect private
Referenced by CleanupEffects(), and HandleBoatSplashSound().
m_SplashIncoming
protected bool m_SplashIncoming private
Referenced by HandleBoatSplashSound().
m_UpdateParticles
protected bool m_UpdateParticles private
Referenced by EOnFrame(), EOnPostSimulate(), and StopParticleUpdate().
m_VelocityPrevTick
protected vector m_VelocityPrevTick private
Referenced by EOnContact(), and EOnPostSimulate().
m_WaterEffects
protected ref EffectBoatWaterBase m_WaterEffects[4] private
Referenced by BoatScript(), CleanupEffects(), ClearWaterEffects(), and UpdateParticles().
SOUND_ENGINE_FADE
protected const float SOUND_ENGINE_FADE = 0.2 private
Referenced by FadeEngineSound(), and OnSound().
SPLASH_THRESHOLD
protected const float SPLASH_THRESHOLD = 0.18 private
Referenced by HandleBoatSplashSound().
SPLASH_THRESHOLD_CONDITION
protected const float SPLASH_THRESHOLD_CONDITION = 0.08 private
Referenced by HandleBoatSplashSound().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Vehicles/BoatScript.c