DayZ Scripts: MaskMdfr Class Reference
MaskMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
void HandleSounds (PlayerBase player, float deltaT, MaskBase mask)
override void OnReconnect (PlayerBase player)
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
Private Attributes
const float IN_AREA_CONSUME_FILTER_QUANTITY_PER_SEC = 0.3
const float OUT_AREA_CONSUME_FILTER_QUANTITY_PER_SEC = 0.03
const float STAMINA_RECOVERY_MODIFIER = 0.5
const float STAMINA_DEPLETION_MODIFIER = 1.25
const float LOW_FILTER_SOUND_EVENT_MIN = 3
const float LOW_FILTER_SOUND_EVENT_MAX = 9
const float LOW_FILTER_SOUND_THRESHOLD = 0.2
float m_SoundTimeAccu1
float m_NextSoundEventTime
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
Referenced by DeactivateCondition().
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
References ActivateCondition().
HandleSounds()
void HandleSounds (PlayerBase player, float deltaT, MaskBase mask) inline private
References Math::InverseLerp(), Math::Lerp(), LOW_FILTER_SOUND_EVENT_MAX, LOW_FILTER_SOUND_EVENT_MIN, LOW_FILTER_SOUND_THRESHOLD, m_NextSoundEventTime, and m_SoundTimeAccu1.
Referenced by OnTick().
Init()
override void Init () inline private
References DEFAULT_TICK_TIME_ACTIVE_SHORT, DEFAULT_TICK_TIME_INACTIVE, m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void OnActivate (PlayerBase player) inline private
OnDeactivate()
override void OnDeactivate (PlayerBase player) inline private
OnReconnect()
override void OnReconnect (PlayerBase player) inline private
References OnActivate().
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
References HandleSounds(), IN_AREA_CONSUME_FILTER_QUANTITY_PER_SEC, m_Manager, and OUT_AREA_CONSUME_FILTER_QUANTITY_PER_SEC.
Field Documentation
IN_AREA_CONSUME_FILTER_QUANTITY_PER_SEC
const float IN_AREA_CONSUME_FILTER_QUANTITY_PER_SEC = 0.3 private
Referenced by OnTick().
LOW_FILTER_SOUND_EVENT_MAX
const float LOW_FILTER_SOUND_EVENT_MAX = 9 private
Referenced by HandleSounds().
LOW_FILTER_SOUND_EVENT_MIN
const float LOW_FILTER_SOUND_EVENT_MIN = 3 private
Referenced by HandleSounds().
LOW_FILTER_SOUND_THRESHOLD
const float LOW_FILTER_SOUND_THRESHOLD = 0.2 private
Referenced by HandleSounds().
m_NextSoundEventTime
float m_NextSoundEventTime private
Referenced by HandleSounds().
m_SoundTimeAccu1
float m_SoundTimeAccu1 private
Referenced by HandleSounds().
OUT_AREA_CONSUME_FILTER_QUANTITY_PER_SEC
const float OUT_AREA_CONSUME_FILTER_QUANTITY_PER_SEC = 0.03 private
Referenced by OnTick().
STAMINA_DEPLETION_MODIFIER
const float STAMINA_DEPLETION_MODIFIER = 1.25 private
Referenced by StaminaHandler::Init().
STAMINA_RECOVERY_MODIFIER
const float STAMINA_RECOVERY_MODIFIER = 0.5 private
Referenced by StaminaHandler::Init().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/Mask.c