DayZ Scripts: Head Class Reference
Head Class Reference
Private Member Functions
void Head_Default ()
void Init ()
void InitSelectionTranslation ()
bool GetHeadHideableSelections (out array< string > selections)
int GetBeardIndex ()
int GetHairIndex ()
int GetSelectionIndex (string str)
bool IsHandlingException ()
Private Attributes
bool m_handling_exception = false
int m_beard_idx
int m_hair_idx
ref map< int, ref SelectionTranslation > m_HeadHairHidingStateMap
ref array< string > m_HeadHairSelectionArray
Member Function Documentation
GetBeardIndex()
int GetBeardIndex () inline private
References m_beard_idx.
GetHairIndex()
int GetHairIndex () inline private
References m_hair_idx.
GetHeadHideableSelections()
bool GetHeadHideableSelections (out array< string > selections) inline private
References m_HeadHairSelectionArray.
GetSelectionIndex()
int GetSelectionIndex (string str) inline private
Head_Default()
void Head_Default () inline private
References Init().
Init()
void Init () inline private
References InitSelectionTranslation().
Referenced by Head_Default().
InitSelectionTranslation()
void InitSelectionTranslation () inline private
References SelectionTranslation::SetSelectionState().
Referenced by Init().
IsHandlingException()
bool IsHandlingException () inline private
References m_handling_exception.
Field Documentation
m_beard_idx
int m_beard_idx private
Referenced by GetBeardIndex().
m_hair_idx
int m_hair_idx private
Referenced by GetHairIndex().
m_handling_exception
bool m_handling_exception = false private
Referenced by IsHandlingException().
m_HeadHairHidingStateMap
ref map<int,ref SelectionTranslation> m_HeadHairHidingStateMap private
m_HeadHairSelectionArray
ref array<string> m_HeadHairSelectionArray private
Referenced by GetHeadHideableSelections().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/Head.c
P:/scripts/4_World/Entities/ManBase/BodyParts/Head.c