DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionTurnOffAlarmClock.c File Reference
ActionTurnOffAlarmClock.c File Reference
Data Structures
class ActionTurnOffAlarmClockCB
Functions
ActionTurnOffAlarmClockCB ActionSingleUseBaseCB ActionTurnOffAlarmClock ()
override void CreateActionComponent ()
override bool HasProneException ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
References ClockBase().
ActionTurnOffAlarmClock()
ActionTurnOffAlarmClockCB ActionSingleUseBaseCB ActionTurnOffAlarmClock ()
Referenced by ActionConstructor::RegisterActions(), and AlarmClock_ColorBase::SetActions().
CreateActionComponent()
override void CreateActionComponent ()
References m_Text.
HasProneException()
override bool HasProneException ()
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
References ClockBase(), and ActionData::m_MainItem.