DayZ Scripts: TriggerEffectManager Class Reference
TriggerEffectManager Class Reference
Private Member Functions
void TriggerEffectManager ()
void RegisterTriggerType (EffectTrigger effectTrigger)
void OnPlayerEnter (notnull PlayerBase player, notnull EffectTrigger trigger)
void OnPlayerInsideEffectAreaEnter (PlayerBase player)
void OnPlayerInsideEffectAreaExit (PlayerBase player)
void OnPlayerExit (notnull PlayerBase player, notnull EffectTrigger trigger)
bool IsPlayerInTriggerType (notnull PlayerBase player, notnull EffectTrigger trigger)
Static Private Member Functions
static void DestroyInstance ()
static TriggerEffectManager GetInstance ()
Private Attributes
ref map< string, ref map< PlayerBase, int > > m_PlayerInsiderMap
Static Private Attributes
static ref TriggerEffectManager m_This
Constructor & Destructor Documentation
TriggerEffectManager()
void TriggerEffectManager () inline private
References m_PlayerInsiderMap.
Referenced by GetInstance().
Member Function Documentation
DestroyInstance()
static void DestroyInstance () inline static private
References m_This.
Referenced by MissionBaseWorld::~MissionBase().
GetInstance()
static TriggerEffectManager GetInstance () inline static private
References m_This, and TriggerEffectManager().
Referenced by ContaminatedTrigger_Dynamic(), and EffectTrigger::EffectTrigger().
IsPlayerInTriggerType()
bool IsPlayerInTriggerType (notnull PlayerBase player, notnull EffectTrigger trigger) inline private
References m_PlayerInsiderMap.
Referenced by EffectTrigger::SetupClientEffects().
OnPlayerEnter()
void OnPlayerEnter (notnull PlayerBase player, notnull EffectTrigger trigger) inline private
References m_PlayerInsiderMap.
Referenced by EffectTrigger::OnEnterClientEvent(), and EffectTrigger::OnEnterServerEvent().
OnPlayerExit()
void OnPlayerExit (notnull PlayerBase player, notnull EffectTrigger trigger) inline private
References m_PlayerInsiderMap.
Referenced by EffectTrigger::OnLeaveClientEvent(), and EffectTrigger::OnLeaveServerEvent().
OnPlayerInsideEffectAreaEnter()
void OnPlayerInsideEffectAreaEnter (PlayerBase player) private
OnPlayerInsideEffectAreaExit()
void OnPlayerInsideEffectAreaExit (PlayerBase player) private
RegisterTriggerType()
void RegisterTriggerType (EffectTrigger effectTrigger) inline private
References m_PlayerInsiderMap.
Referenced by EffectTrigger::EffectTrigger().
Field Documentation
m_PlayerInsiderMap
ref map<string, ref map<PlayerBase, int> > m_PlayerInsiderMap private
Referenced by IsPlayerInTriggerType(), OnPlayerEnter(), OnPlayerExit(), RegisterTriggerType(), and TriggerEffectManager().
m_This
ref TriggerEffectManager m_This static private
Referenced by DestroyInstance(), and GetInstance().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ScriptedEntities/Triggers/TriggerEffectManager.c