DayZ Scripts: PPERequester_MenuBase Class Reference
PPERequester_MenuBase Class Reference
Private Member Functions
override protected void OnStart (Param par=null)
override protected void OnStart (Param par=null)
override protected void OnStart (Param par=null)
void SetBlurIntensity (float gauss)
void SetVignetteIntensity (float vignette)
override protected void OnStart (Param par=null)
override protected void OnStart (Param par=null)
Private Attributes
protected float m_Gauss
Detailed Description
Definition at line 1 of file PPERControllerDisconnectBlur.c.
Member Function Documentation
OnStart() [1/5]
override protected void OnStart (Param par = null) inline private
Definition at line 3 of file PPERControllerDisconnectBlur.c.
References PPEGaussFilter::L_0_DISCONNECT, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
OnStart() [2/5]
override protected void OnStart (Param par = null) inline private
Definition at line 5 of file PPERControlsBlur.c.
References PPEGaussFilter::L_0_CONTROLS, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
OnStart() [3/5]
override protected void OnStart (Param par = null) inline private
Definition at line 3 of file PPERIntroChromAbb.c.
References PPEChromAber::L_0_INTRO, PPEChromAber::L_1_INTRO, PPEChromAber::PARAM_POWERX, PPEChromAber::PARAM_POWERY, and SetTargetValueFloat().
OnStart() [4/5]
override protected void OnStart (Param par = null) inline private
Definition at line 5 of file PPERServerBrowser.c.
References PPEGaussFilter::L_0_SERVER_BROWSER, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
OnStart() [5/5]
override protected void OnStart (Param par = null) inline private
Definition at line 5 of file PPERTutorial.c.
References PPEGaussFilter::L_0_TUTORIALS, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
SetBlurIntensity()
void SetBlurIntensity (float gauss) inline private
Definition at line 3 of file PPERMenuEffects.c.
References PPEGaussFilter::L_0_MENU, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
SetVignetteIntensity()
void SetVignetteIntensity (float vignette) inline private
Definition at line 8 of file PPERMenuEffects.c.
References PPEGlow::L_25_MENU, PPEGlow::L_26_MENU, PPEGlow::PARAM_VIGNETTE, PPEGlow::PARAM_VIGNETTECOLOR, SetTargetValueColor(), and SetTargetValueFloat().
Field Documentation
m_Gauss
protected float m_Gauss private
Definition at line 3 of file PPERControlsBlur.c.
The documentation for this class was generated from the following files:
P:/scripts/3_Game/PPEManager/Requesters/PPERControllerDisconnectBlur.c
P:/scripts/3_Game/PPEManager/Requesters/PPERControlsBlur.c
P:/scripts/3_Game/PPEManager/Requesters/PPERServerBrowser.c
P:/scripts/3_Game/PPEManager/Requesters/PPERTutorial.c
P:/scripts/3_Game/PPEManager/Requesters/PPERIntroChromAbb.c
P:/scripts/3_Game/PPEManager/Requesters/PPERMenuEffects.c