DayZ Scripts: BoatHud Class Reference
BoatHud Class Reference
Private Member Functions
override void Init (Widget vehicleHudPanels)
override void ShowVehicleInfo (PlayerBase player)
override void HideVehicleInfo ()
override void RefreshVehicleHud (float timeslice)
protected void UpdateEngineIcon (int level)
protected void UpdateFuelIcon (float level)
protected void UpdateSpeedPointer ()
protected void UpdateGear ()
protected void UpdateEngineBlink (float timeSlice)
protected float GetSpeedometer ()
Private Attributes
protected const float ENGINE_BLINK_DURATION = 3
protected ImageWidget m_SpeedPointer
protected ImageWidget m_EngineLight
protected ImageWidget m_FuelLight
protected bool m_HasEngine
protected int m_EngagedGear
protected int m_EngineHealthLevel
protected float m_FuelLevel
protected float m_TimeSinceEngineHit
protected float m_TimeSinceEngineBlink
protected BoatScript m_CurrentVehicle
protected ref WidgetFadeTimer m_FadeTimer = new WidgetFadeTimer()
Member Function Documentation
GetSpeedometer()
protected float GetSpeedometer () inline private
References GetVelocity(), vector::InvMultiply3(), and m_CurrentVehicle.
HideVehicleInfo()
override void HideVehicleInfo () inline private
References m_CurrentVehicle, and VehicleHudBase::m_VehicleGearTable.
Init()
override void Init (Widget vehicleHudPanels) inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_EngineLight, m_FuelLight, m_SpeedPointer, VehicleHudBase::m_VehicleCurrentGearValue, VehicleHudBase::m_VehicleNextGearValue, VehicleHudBase::m_VehiclePanel, and VehicleHudBase::m_VehiclePrevGearValue.
RefreshVehicleHud()
override void RefreshVehicleHud (float timeslice) inline private
References ENGINE_BLINK_DURATION, m_CurrentVehicle, m_EngineHealthLevel, m_FuelLevel, m_TimeSinceEngineHit, UpdateEngineBlink(), UpdateEngineIcon(), UpdateFuelIcon(), UpdateGear(), and UpdateSpeedPointer().
ShowVehicleInfo()
override void ShowVehicleInfo (PlayerBase player) inline private
References HumanCommandVehicle::GetTransport(), m_CurrentVehicle, m_EngagedGear, m_EngineHealthLevel, m_FuelLevel, m_HasEngine, VehicleHudBase::m_VehicleGearTable, and VehicleHudBase::m_VehiclePanel.
UpdateEngineBlink()
protected void UpdateEngineBlink (float timeSlice) inline private
References m_EngineLight, m_FadeTimer, m_TimeSinceEngineBlink, and m_TimeSinceEngineHit.
Referenced by RefreshVehicleHud().
UpdateEngineIcon()
protected void UpdateEngineIcon (int level) inline private
References COLOR_WHITE, ItemManager::GetItemHealthColor(), m_EngineHealthLevel, m_EngineLight, and GameConstants::STATE_WORN.
Referenced by RefreshVehicleHud().
UpdateFuelIcon()
protected void UpdateFuelIcon (float level) inline private
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_RUINED, m_FuelLevel, and m_FuelLight.
Referenced by RefreshVehicleHud().
UpdateGear()
protected void UpdateGear () inline private
References m_CurrentVehicle, m_EngagedGear, m_HasEngine, VehicleHudBase::m_VehicleCurrentGearValue, VehicleHudBase::m_VehicleGearTable, VehicleHudBase::m_VehicleNextGearValue, and VehicleHudBase::m_VehiclePrevGearValue.
Referenced by RefreshVehicleHud().
UpdateSpeedPointer()
protected void UpdateSpeedPointer () inline private
References Math::AbsFloat(), Math::Clamp(), Math::InverseLerp(), Math::Lerp(), m_CurrentVehicle, m_HasEngine, and m_SpeedPointer.
Referenced by RefreshVehicleHud().
Field Documentation
ENGINE_BLINK_DURATION
protected const float ENGINE_BLINK_DURATION = 3 private
Referenced by RefreshVehicleHud().
m_CurrentVehicle
protected BoatScript m_CurrentVehicle private
Referenced by GetSpeedometer(), HideVehicleInfo(), RefreshVehicleHud(), ShowVehicleInfo(), UpdateGear(), and UpdateSpeedPointer().
m_EngagedGear
protected int m_EngagedGear private
Referenced by ShowVehicleInfo(), and UpdateGear().
m_EngineHealthLevel
protected int m_EngineHealthLevel private
Referenced by RefreshVehicleHud(), ShowVehicleInfo(), and UpdateEngineIcon().
m_EngineLight
protected ImageWidget m_EngineLight private
Referenced by Init(), UpdateEngineBlink(), and UpdateEngineIcon().
m_FadeTimer
protected ref WidgetFadeTimer m_FadeTimer = new WidgetFadeTimer() private
Referenced by UpdateEngineBlink().
m_FuelLevel
protected float m_FuelLevel private
Referenced by RefreshVehicleHud(), ShowVehicleInfo(), and UpdateFuelIcon().
m_FuelLight
protected ImageWidget m_FuelLight private
Referenced by Init(), and UpdateFuelIcon().
m_HasEngine
protected bool m_HasEngine private
Referenced by ShowVehicleInfo(), UpdateGear(), and UpdateSpeedPointer().
m_SpeedPointer
protected ImageWidget m_SpeedPointer private
Referenced by Init(), and UpdateSpeedPointer().
m_TimeSinceEngineBlink
protected float m_TimeSinceEngineBlink private
Referenced by UpdateEngineBlink().
m_TimeSinceEngineHit
protected float m_TimeSinceEngineHit private
Referenced by RefreshVehicleHud(), and UpdateEngineBlink().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/Vehicles/BoatHud.c