DayZ Scripts: ActionPlaceFireplaceIndoor Class Reference
ActionPlaceFireplaceIndoor Class Reference
Private Member Functions
void ActionPlaceFireplaceIndoor ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
override bool IsLockTargetOnUse ()
Constructor & Destructor Documentation
ActionPlaceFireplaceIndoor()
void ActionPlaceFireplaceIndoor () inline private
References AnimatedActionBase::m_CommandUID, ActionBase::m_SpecialtyWeight, ActionBase::m_StanceMask, and ActionBase::m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Math::Acos(), string::Contains(), UAMaxDistances::DEFAULT, vector::Distance(), vector::Dot(), ActionBase::IsInReach(), vector::Normalize(), and Math::RAD2DEG.
CreateConditionComponents()
override void CreateConditionComponents () inline private
References ActionBase::m_ConditionItem, and ActionBase::m_ConditionTarget.
IsLockTargetOnUse()
override bool IsLockTargetOnUse () inline private
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
References FireplaceToIndoorsLambda().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionPlaceFireplaceIndoor.c