DayZ Scripts: ContainerWithElectricManager Class Reference
ContainerWithElectricManager Class Reference
Private Member Functions
override void UpdateInterval ()
override void SetEntity (EntityAI entity, bool immedUpdate=true)
void ElectricityIcon ()
Member Function Documentation
ElectricityIcon()
void ElectricityIcon () inline private
References FindAnyWidget(), and m_Entity.
Referenced by SetEntity(), and UpdateInterval().
SetEntity()
override void SetEntity (EntityAI entity, bool immedUpdate = true) inline private
References ElectricityIcon().
Referenced by VicinityContainer::UpdateInterval().
UpdateInterval()
override void UpdateInterval () inline private
References ElectricityIcon(), and m_Entity.
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Inherited/ContainerWithElectricManager.c