DayZ Scripts: RemotelyActivatedItemBehaviour Class Reference
RemotelyActivatedItemBehaviour Class Reference
Private Member Functions
void RemotelyActivatedItemBehaviour (notnull EntityAI pParent)
void ~RemotelyActivatedItemBehaviour ()
void SetTrigger ()
void OnVariableSynchronized ()
void OnStoreSave (ParamsWriteContext ctx)
bool OnStoreLoad (ParamsReadContext ctx, int version)
void OnAfterLoad ()
void SetPersistentPairID (int id)
void Pair ()
void Pair (notnull EntityAI device)
void Unpair ()
EntityAI GetPairDevice ()
bool IsPaired ()
void SetPairDeviceNetIds (notnull EntityAI device)
int GetPairDeviceNetIdLow ()
int GetPairDeviceNetIdHigh ()
Static Private Member Functions
static int GeneratePersistentID ()
Private Attributes
protected EntityAI m_Parent
protected bool m_IsTrigger
protected EntityAI m_PairDevice
protected int m_PairDeviceNetIdLow
protected int m_PairDeviceNetIdHigh
protected int m_PersistentPairID = int.MIN
Static Private Attributes
static protected ref map< int, EntityAI > m_RemoteReceivers = new map<int,EntityAI>()
Detailed Description
Definition at line 1 of file RemotelyActivatedItemBehaviour.c.
Constructor & Destructor Documentation
RemotelyActivatedItemBehaviour()
void RemotelyActivatedItemBehaviour (notnull EntityAI pParent) inline private
Definition at line 12 of file RemotelyActivatedItemBehaviour.c.
References m_PairDeviceNetIdHigh, m_PairDeviceNetIdLow, and m_Parent.
~RemotelyActivatedItemBehaviour()
void ~RemotelyActivatedItemBehaviour () inline private
Definition at line 20 of file RemotelyActivatedItemBehaviour.c.
References m_Parent, and Unpair().
Member Function Documentation
GeneratePersistentID()
static int GeneratePersistentID () inline static private
Definition at line 81 of file RemotelyActivatedItemBehaviour.c.
References GeneratePersistentID(), m_RemoteReceivers, MAX, and Math::RandomInt().
Referenced by GeneratePersistentID(), and InventoryItem::PairWithDevice().
GetPairDevice()
EntityAI GetPairDevice () inline private
Definition at line 143 of file RemotelyActivatedItemBehaviour.c.
References m_PairDevice.
Referenced by RemoteDetonatorTrigger::GetControlledDevice(), ClaymoreMine::GetPairDevice(), ImprovisedExplosive::GetPairDevice(), and Plastic_Explosive::GetPairDevice().
GetPairDeviceNetIdHigh()
int GetPairDeviceNetIdHigh () inline private
Definition at line 163 of file RemotelyActivatedItemBehaviour.c.
References m_PairDeviceNetIdHigh.
Referenced by Pair().
GetPairDeviceNetIdLow()
int GetPairDeviceNetIdLow () inline private
Definition at line 158 of file RemotelyActivatedItemBehaviour.c.
References m_PairDeviceNetIdLow.
Referenced by Pair().
IsPaired()
bool IsPaired () inline private
Definition at line 148 of file RemotelyActivatedItemBehaviour.c.
References m_PairDevice.
Referenced by RemoteDetonatorTrigger::IsConnected(), ClaymoreMine::OnActivatedByItem(), Plastic_Explosive::OnActivatedByItem(), and RemoteDetonatorTrigger::OnActivatedByItem().
OnAfterLoad()
void OnAfterLoad () inline private
Definition at line 63 of file RemotelyActivatedItemBehaviour.c.
References m_IsTrigger, m_PairDevice, m_PersistentPairID, m_RemoteReceivers, MIN, and Pair().
Referenced by InventoryItem::EEOnAfterLoad().
OnStoreLoad()
bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 41 of file RemotelyActivatedItemBehaviour.c.
References m_IsTrigger, m_Parent, m_PersistentPairID, m_RemoteReceivers, MIN, Pair(), and Serializer::Read().
Referenced by InventoryItem::OnStoreLoad().
OnStoreSave()
void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 36 of file RemotelyActivatedItemBehaviour.c.
References m_PersistentPairID, and Serializer::Write().
Referenced by InventoryItem::OnStoreSave().
OnVariableSynchronized()
void OnVariableSynchronized () inline private
Definition at line 31 of file RemotelyActivatedItemBehaviour.c.
References Pair().
Referenced by ClaymoreMine::OnVariablesSynchronized(), ImprovisedExplosive::OnVariablesSynchronized(), Plastic_Explosive::OnVariablesSynchronized(), RemoteDetonatorTrigger::OnVariablesSynchronized(), and ManBase::OnVariablesSynchronized().
Pair() [1/2]
void Pair () inline private
Definition at line 101 of file RemotelyActivatedItemBehaviour.c.
References GetGame(), GetPairDeviceNetIdHigh(), GetPairDeviceNetIdLow(), and Pair().
Referenced by ClaymoreMine::EEItemLocationChanged(), ImprovisedExplosive::EEItemLocationChanged(), Plastic_Explosive::EEItemLocationChanged(), RemoteDetonatorTrigger::EEItemLocationChanged(), OnAfterLoad(), OnStoreLoad(), OnVariableSynchronized(), Pair(), ClaymoreMine::PairRemote(), ImprovisedExplosive::PairRemote(), Plastic_Explosive::PairRemote(), RemoteDetonatorTrigger::PairRemote(), and RemoteDetonatorTrigger::SetControlledDevice().
Pair() [2/2]
void Pair (notnull EntityAI device) inline private
Definition at line 110 of file RemotelyActivatedItemBehaviour.c.
References m_PairDevice, m_Parent, and SetPairDeviceNetIds().
SetPairDeviceNetIds()
void SetPairDeviceNetIds (notnull EntityAI device) inline private
Definition at line 153 of file RemotelyActivatedItemBehaviour.c.
References m_PairDeviceNetIdHigh, and m_PairDeviceNetIdLow.
Referenced by Pair().
SetPersistentPairID()
void SetPersistentPairID (int id) inline private
Definition at line 93 of file RemotelyActivatedItemBehaviour.c.
References m_IsTrigger, m_Parent, m_PersistentPairID, and m_RemoteReceivers.
SetTrigger()
void SetTrigger () inline private
Definition at line 26 of file RemotelyActivatedItemBehaviour.c.
References m_IsTrigger.
Referenced by RemoteDetonatorTrigger::RemoteDetonatorTrigger().
Unpair()
void Unpair () inline private
Definition at line 122 of file RemotelyActivatedItemBehaviour.c.
References m_PairDevice, m_PairDeviceNetIdHigh, m_PairDeviceNetIdLow, m_Parent, m_PersistentPairID, m_RemoteReceivers, and MIN.
Referenced by UnpairRemote(), RemoteDetonatorTrigger::UnpairRemote(), and ~RemotelyActivatedItemBehaviour().
Field Documentation
m_IsTrigger
protected bool m_IsTrigger private
Definition at line 4 of file RemotelyActivatedItemBehaviour.c.
Referenced by OnAfterLoad(), OnStoreLoad(), SetPersistentPairID(), and SetTrigger().
m_PairDevice
protected EntityAI m_PairDevice private
Definition at line 5 of file RemotelyActivatedItemBehaviour.c.
Referenced by GetPairDevice(), IsPaired(), OnAfterLoad(), Pair(), and Unpair().
m_PairDeviceNetIdHigh
protected int m_PairDeviceNetIdHigh private
Definition at line 7 of file RemotelyActivatedItemBehaviour.c.
Referenced by GetPairDeviceNetIdHigh(), RemotelyActivatedItemBehaviour(), SetPairDeviceNetIds(), and Unpair().
m_PairDeviceNetIdLow
protected int m_PairDeviceNetIdLow private
Definition at line 6 of file RemotelyActivatedItemBehaviour.c.
Referenced by GetPairDeviceNetIdLow(), RemotelyActivatedItemBehaviour(), SetPairDeviceNetIds(), and Unpair().
m_Parent
protected EntityAI m_Parent private
Definition at line 3 of file RemotelyActivatedItemBehaviour.c.
Referenced by OnStoreLoad(), Pair(), RemotelyActivatedItemBehaviour(), SetPersistentPairID(), Unpair(), and ~RemotelyActivatedItemBehaviour().
m_PersistentPairID
protected int m_PersistentPairID = int.MIN private
Definition at line 8 of file RemotelyActivatedItemBehaviour.c.
Referenced by OnAfterLoad(), OnStoreLoad(), OnStoreSave(), SetPersistentPairID(), and Unpair().
m_RemoteReceivers
protected ref map<int,EntityAI> m_RemoteReceivers = new map<int,EntityAI>() static private
Definition at line 10 of file RemotelyActivatedItemBehaviour.c.
Referenced by GeneratePersistentID(), OnAfterLoad(), OnStoreLoad(), SetPersistentPairID(), and Unpair().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/RemotelyActivatedItemBehaviour.c