DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionWashHandsWell.c File Reference
ActionWashHandsWell.c File Reference
Data Structures
class ActionWashHandsWellCB
Functions
ActionWashHandsWellCB ActionContinuousBaseCB ActionWashHandsWell ()
override void CreateActionComponent ()
override GetInputType ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionWashHandsWell()
ActionWashHandsWellCB ActionContinuousBaseCB ActionWashHandsWell ()
Referenced by ActionConstructor::RegisterActions(), Land_Misc_Through_Static::SetActions(), and BuildingSuper::SetActions().
CreateActionComponent()
override void CreateActionComponent ()
References m_FullBody, m_StanceMask, and m_Text.
CreateConditionComponents()
override void CreateConditionComponents ()
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType ()
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
References GetPlugin(), ActionData::m_Player, and PluginLifespan().