DayZ Scripts: P:/scripts/4_World/Classes/PlayerStats/PlayerStatBase.c File Reference
PlayerStatBase.c File Reference
Data Structures
class PlayerStatBase
Functions
void PlayerStat (T min, T max, T init, string label, int flags)
override void Init (int id)
override void SerializeValue (array< ref StatDebugObject > objects, int flags)
override bool IsSynced ()
override void OnRPC (ParamsReadContext ctx)
void Set (T value, string system="")
void SetByFloat (float value, string system="")
override void SetByFloatEx (float value, string system="")
void Add (T value, string system="")
override float Get ()
override string GetLabel ()
override float GetMax ()
override float GetMin ()
override float GetNormalized ()
override array< PlayerStatRecord > GetRecords ()
void CreateRecord (float value, string system)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx)
override void OnAfterStoreLoad ()
engine reaction to load from database originates in: engine - Person::BinLoad script - PlayerBase.OnAfterStoreLoad
PlayerStats GetManager ()
Variables
class PlayerStatBase m_MinValue
protected T m_MaxValue
protected T m_Value
protected T m_ValueLastSynced
protected string m_ValueLabel
protected int m_Flags
ref array< PlayerStatRecord > m_Records
PlayerStats m_Manager
DEPRECATED.
Function Documentation
Add()
void Add (T value, string system = "")
References m_Value, and Set().
CreateRecord()
void CreateRecord (float value, string system)
References GetGame(), GetTime(), and m_Records.
Get()
override float Get ()
References m_Value.
Referenced by array< Class T >::Debug(), set< Class T >::Debug(), array< Class T >::DifferentAtPosition(), array< Class T >::GetRandomElement(), array< Class T >::Invert(), Link< Class T >::IsNull(), array< ref TSelectableActionInfo >::IsSameAs(), HudDebugWinBase::OnChange(), PluginBase::OnRPCStatSet(), ManBase::OnSelectPlayer(), Link< Class T >::Ptr(), UIScriptedMenu::RandomizeCharacter(), Link< Class T >::Release(), array< ref CallQueueContext >::RemoveCalls(), map< Class TKey, Class TValue >::ReplaceKey(), PluginBase::SendRPCStats(), array< Class T >::SwapItems(), array< ref CallQueueContext >::Tick(), CallQueue::Tick(), array< TimerBase >::Tick(), LayoutHolder::UnfocusAll(), IconsContainer::UnfocusAll(), AttachmentCategoriesRow::UnfocusAll(), ComponentEnergyManager::UnplugAllDevices(), PluginBase::UpdateStatsLocal(), and array< TimerBase >::~TimerQueue().
GetLabel()
override string GetLabel ()
References m_ValueLabel.
GetManager()
PlayerStats GetManager ()
References m_Manager.
Referenced by PMTPlayback::CheckOnePlaying(), and CheckTestEvents().
GetMax()
override float GetMax ()
References m_MaxValue.
Referenced by ManBase::ResetPlayer().
GetMin()
override float GetMin ()
References m_MinValue.
GetNormalized()
override float GetNormalized ()
References PlayerStatBase::Get(), PlayerStatBase::GetMax(), PlayerStatBase::GetMin(), and Math::InverseLerp().
GetRecords()
override array< PlayerStatRecord > GetRecords ()
References m_Records.
Init()
override void Init (int id)
References m_Type.
IsSynced()
override bool IsSynced ()
References m_Flags.
OnAfterStoreLoad()
OnAfterStoreLoad ()
engine reaction to load from database originates in: engine - Person::BinLoad script - PlayerBase.OnAfterStoreLoad
References PlayerStatBase::Get(), and Set().
OnRPC()
override void OnRPC (ParamsReadContext ctx)
References PlayerStatBase::IsSynced(), m_Type, Serializer::Read(), and Set().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx)
References m_Value, and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
References m_Value, and Serializer::Write().
PlayerStat()
void PlayerStat (T min, T max, T init, string label, int flags)
References init, m_Flags, m_MaxValue, m_MinValue, m_Records, m_Value, and m_ValueLabel.
SerializeValue()
override void SerializeValue (array< ref StatDebugObject > objects, int flags)
References PlayerStatBase::Get(), and PlayerStatBase::GetLabel().
Set()
void Set (T value, string system = "")
References Math::AbsFloat(), PlayerStatBase::IsSynced(), m_MaxValue, m_MinValue, m_Player, PlayerStatBase::m_Type, m_Value, m_ValueLastSynced, and Math::Round().
Referenced by Add(), array< Class T >::Invert(), OnAfterStoreLoad(), OnRPC(), map< Class TKey, Class TValue >::ReplaceKey(), SetByFloat(), and array< Class T >::SwapItems().
SetByFloat()
void SetByFloat (float value, string system = "")
References Set().
SetByFloatEx()
override void SetByFloatEx (float value, string system = "")
References PlayerStatBase::SetByFloat().
Variable Documentation
m_Flags
protected int m_Flags
Referenced by IsSynced(), and PlayerStat().
m_Manager
PlayerStats m_Manager
DEPRECATED.
Referenced by GetManager().
m_MaxValue
protected T m_MaxValue
Referenced by GetMax(), GetMaxValue(), OptionSelectorBase::GetValue(), OptionSelectorBase::NormalizeInput(), OptionSelectorSliderSetup::OptionSelectorLevelMarker(), OptionSelectorSliderSetup::OptionSelectorSlider(), PlayerStat(), Set(), OptionSelectorBase::SetMax(), SetMaxValue(), and StaminaModifier().
m_MinValue
class PlayerStatBase m_MinValue
Referenced by GetMin(), GetMinValue(), OptionSelectorBase::GetValue(), OptionSelectorBase::NormalizeInput(), OptionSelectorSliderSetup::OptionSelectorLevelMarker(), OptionSelectorSliderSetup::OptionSelectorSlider(), PlayerStat(), Set(), SetMinValue(), and StaminaModifier().
m_Records
ref array<PlayerStatRecord> m_Records
Referenced by CreateRecord(), GetRecords(), and PlayerStat().
m_Value
protected T m_Value
Referenced by Get(), and Set().
m_ValueLabel
protected string m_ValueLabel
Referenced by GetLabel(), and PlayerStat().
m_ValueLastSynced
protected T m_ValueLastSynced
Referenced by Set().