DayZ Scripts: LogManager Class Reference
LogManager Class Reference
Static Private Member Functions
static void Init ()
static bool IsLogsEnable ()
static void SetLogsEnabled (bool enable)
static bool IsActionLogEnable ()
static void ActionLogEnable (bool enable)
static bool IsInventoryMoveLogEnable ()
static void InventoryMoveLogEnable (bool enable)
static bool IsInventoryReservationLogEnable ()
static void InventoryReservationLogEnable (bool enable)
static bool IsInventoryHFSMLogEnable ()
static void InventoryHFSMLogEnable (bool enable)
static bool IsSyncLogEnable ()
static void SyncLogEnable (bool enable)
static bool IsQuickbarLogEnable ()
static void QuickbarLogEnable (bool enable)
static bool IsBaseBuildingLogEnable ()
static void BaseBuildingLogEnable (bool enable)
static bool IsSymptomLogEnable ()
static void SymptomLogEnable (bool enable)
static bool IsWeaponLogEnable ()
static void WeaponLogEnable (bool enable)
static bool IsWeatherLogEnabled ()
static bool IsBleedingChancesLogEnable ()
static void BleedingChancesLogEnable (bool enable)
Static Private Attributes
static bool m_DoLogs
static bool m_DoActionDebugLog
static bool m_DoSymptomDebugLog
static bool m_DoInventoryMoveLog
static bool m_DoInventoryReservationLog
static bool m_DoInventoryHFSMLog
static bool m_DoSyncLog
static bool m_DoQuickbarLog
static bool m_DoBaseBuildingLog
static bool m_DoWeaponLog
static bool m_DoWeatherLog
static bool m_DoBleedingChanceLog
Member Function Documentation
ActionLogEnable()
static void ActionLogEnable (bool enable) inline static private
References m_DoActionDebugLog.
BaseBuildingLogEnable()
static void BaseBuildingLogEnable (bool enable) inline static private
References m_DoBaseBuildingLog.
BleedingChancesLogEnable()
static void BleedingChancesLogEnable (bool enable) inline static private
References m_DoBleedingChanceLog.
Init()
static void Init () inline static private
References IsCLIParam(), m_DoActionDebugLog, m_DoBaseBuildingLog, m_DoInventoryHFSMLog, m_DoInventoryMoveLog, m_DoInventoryReservationLog, m_DoLogs, m_DoQuickbarLog, m_DoSymptomDebugLog, m_DoSyncLog, m_DoWeaponLog, and m_DoWeatherLog.
Referenced by CGame::CGame().
InventoryHFSMLogEnable()
static void InventoryHFSMLogEnable (bool enable) inline static private
References m_DoInventoryHFSMLog.
InventoryMoveLogEnable()
static void InventoryMoveLogEnable (bool enable) inline static private
References m_DoInventoryMoveLog.
InventoryReservationLogEnable()
static void InventoryReservationLogEnable (bool enable) inline static private
References m_DoInventoryReservationLog.
IsActionLogEnable()
static bool IsActionLogEnable () inline static private
References m_DoActionDebugLog.
Referenced by ActionManagerClient::ActionStart(), EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), AnimatedActionBase::Do(), AnimatedActionBase::End(), ActionInput::Init(), ActionInteractBaseCB::InitActionComponent(), ActionBaseCB::Interrupt(), ActionManagerClient::LockInventory(), OnActionEnd(), AnimatedActionBase::OnAnimationEvent(), ActionContinuousBaseCB::OnAnimationEvent(), ActionInteractBaseCB::OnAnimationEvent(), ActionContinuousBase::OnEndAnimationLoop(), ActionBaseCB::OnFinish(), ActionContinuousBase::OnFinishProgress(), ActionContinuousBase::OnStartAnimationLoop(), ActionManagerClient::ProcessActionInputEnd(), ActionManagerClient::ProcessActionRequestEnd(), ActionInput::SetInput(), SetupAction(), Start(), ActionManagerServer::StartDeliveredAction(), ActionManagerClient::UnlockInventory(), and ActionManagerServer::Update().
IsBaseBuildingLogEnable()
static bool IsBaseBuildingLogEnable () inline static private
References m_DoBaseBuildingLog.
Referenced by AddToConstructedParts(), BaseBuildingBase::AfterStoreLoad(), BuildPartServer(), DestroyConnectedParts(), ItemBase::DestroyConstruction(), DestroyMaterialsServer(), DestroyPartServer(), DismantlePartServer(), DropNonUsableMaterialsServer(), HideConstructionPart(), InitBaseState(), ItemBase::InitBaseState(), InitVisuals(), ItemBase::InitVisuals(), LockServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), ItemBase::OnSetSlotLock(), BaseBuildingBase::OnStoreLoad(), BaseBuildingBase::OnStoreSave(), ItemBase::OnVariablesSynchronized(), OnVariablesSynchronized(), RemoveFromConstructedParts(), ConstructionPart::SetBuiltState(), SetLockOnAttachedMaterials(), ItemBase::SetMountedState(), ItemBase::SetPartFromSyncData(), ConstructionPart::SetRequestBuiltState(), ShowConstructionPart(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), Synchronize(), UnlockServer(), ItemBase::UpdateAttachmentPhysics(), UpdateConstructionParts(), UpdatePhysics(), ItemBase::UpdatePhysics(), and UpdateVisuals().
IsBleedingChancesLogEnable()
static bool IsBleedingChancesLogEnable () inline static private
References m_DoBleedingChanceLog.
Referenced by BleedChanceData::CalculateBleedChance(), and BleedingSourcesManagerBase::ProcessHit().
IsInventoryHFSMLogEnable()
static bool IsInventoryHFSMLogEnable () inline static private
References m_DoInventoryHFSMLog.
Referenced by HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Abort(), HandActionBase::Action(), HandEventBase::CanPerformEvent(), HandEventSwap::CanPerformEvent(), HandEventBase::CanPerformEventEx(), HandEventBase::CheckRequest(), HandEventSwap::CheckRequest(), HandEventBase::CheckRequestSrc(), ReplaceItemWithNewLambdaBase::CopyOldPropertiesToNew(), ReplaceItemWithNewLambdaBase::CreateNetworkObjectInfo(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), ReplaceItemWithNewLambdaBase::DeleteOldEntity(), HumanInventory::DropEntity(), ReplaceItemWithNewLambdaBase::Execute(), Execute(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState(), HumanInventory::ForceSwapEntities(), HandGuardBase::GuardCondition(), HandGuardHasItemInEvent::GuardCondition(), HandleHandEvent(), HandleInventory(), HandleTakeToDst(), HumanInventoryWithFSM::Init(), Init(), HumanInventory::LocalDestroyEntity(), HandStateBase::OnAbort(), HumanInventory::OnEntityInHandsCreated(), HumanInventory::OnEntityInHandsDestroyed(), HandStateBase::OnEntry(), HandStartAction::OnEntry(), HandStateBase::OnExit(), OnHandEventForRemote(), OnHandsEnteredStableState(), OnHandsExitedStableState(), OnHandsStateChanged(), ReplaceItemWithNewLambdaBase::OnSuccess(), ReplaceItemWithNewLambdaBase::PrepareLocations(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessAbortEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortTransition(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessAbortTransition(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessEvent(), HumanInventoryWithFSM::ProcessHandAbortEvent(), HumanInventoryWithFSM::ProcessHandEvent(), FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessLocalTransition(), OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition(), HumanInventory::RedirectToHandEvent(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), HumanInventory::ReplaceItemInHandsWithNewImpl(), SelectAnimationOfForceSwapInHands(), SelectAnimationOfMoveFromHands(), SelectAnimationOfTakeToHands(), OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), HumanInventory::SwapEntities(), SyncHandEventToRemote(), HumanInventory::TakeEntityAsAttachmentEx(), HumanInventory::TakeEntityToCargoEx(), HumanInventory::TakeEntityToInventory(), HumanInventory::TakeToDst(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Terminate(), and HumanInventory::ThrowEntity().
IsInventoryMoveLogEnable()
static bool IsInventoryMoveLogEnable () inline static private
References m_DoInventoryMoveLog.
Referenced by GameInventory::DropEntity(), GameInventory::DropEntityInBounds(), GameInventory::DropEntityWithTransform(), GameInventory::EEInit(), ForceSwapEntities(), HandleForceSwapEntities(), HandleSwapEntities(), HandleTakeToDst(), GameInventory::LocalDestroyEntity(), GameInventory::ReplaceItemWithNew(), StoreInputForRemotes(), SwapEntities(), GameInventory::TakeEntityAsAttachment(), GameInventory::TakeEntityAsAttachmentEx(), GameInventory::TakeEntityAsTargetAttachment(), GameInventory::TakeEntityAsTargetAttachmentEx(), GameInventory::TakeEntityToCargo(), GameInventory::TakeEntityToCargoEx(), GameInventory::TakeEntityToInventory(), GameInventory::TakeEntityToTargetCargo(), GameInventory::TakeEntityToTargetCargoEx(), GameInventory::TakeEntityToTargetInventory(), TakeToDst(), ValidateDestroy(), ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().
IsInventoryReservationLogEnable()
static bool IsInventoryReservationLogEnable () inline static private
References m_DoInventoryReservationLog.
Referenced by CGame::AddInventoryJunctureEx(), GameInventory::AddInventoryReservationEx(), GameInventory::ClearInventoryReservationEx(), CGame::ClearJunctureEx(), GameInventory::ExtendInventoryReservationEx(), and TryAcquireTwoInventoryJuncturesFromServer().
IsLogsEnable()
static bool IsLogsEnable () inline static private
References m_DoLogs.
Referenced by Debug::LogMessage(), MissionBase::OnInit(), and Debug::ReceivedLogMessageFromServer().
IsQuickbarLogEnable()
static bool IsQuickbarLogEnable () inline static private
References m_DoQuickbarLog.
IsSymptomLogEnable()
static bool IsSymptomLogEnable () inline static private
References m_DoSymptomDebugLog.
Referenced by SymptomBase::OnGetActivatedClient(), SymptomBase::OnGetActivatedServer(), SymptomBase::OnGetDeactivatedClient(), and SymptomBase::OnGetDeactivatedServer().
IsSyncLogEnable()
static bool IsSyncLogEnable () inline static private
References m_DoSyncLog.
Referenced by HandEventBase::CheckRequestSrc(), EntityAI::DropEntityImpl(), EntityAI::ForceSwapEntitiesImpl(), EntityAI::LocalDestroyEntityInHands(), ManBase::NeedInventoryJunctureFromServer(), OnHandleStoredInputUserData(), OnHandleStoredJunctureData(), OnInputUserDataForRemote(), OnInputUserDataProcess(), OnInventoryJunctureFromServer(), ManBase::OnQuickBarSingleUse(), OnServerInventoryCommand(), GameInventory::OnServerInventoryCommandStatic(), DayZPlayerCommandDeathCallback::OnSimulationEnd(), EntityAI::PredictiveMoveItemFromHandsToInventory(), EntityAI::ReplaceItemElsewhereWithNewInHandsImpl(), EntityAI::ReplaceItemInHandsWithNewElsewhereImpl(), EntityAI::ReplaceItemInHandsWithNewImpl(), EntityAI::ReplaceItemWithNewImpl(), InventoryInputUserData::SendInputUserDataDestroy(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), InventoryInputUserData::SendServerMove(), InventoryInputUserData::SendServerSwap(), EntityAI::SwapEntitiesImpl(), EntityAI::TakeEntityAsAttachmentExImpl(), EntityAI::TakeEntityAsAttachmentImpl(), ManBase::TakeEntityAsAttachmentImpl(), EntityAI::TakeEntityToCargoImpl(), ManBase::TakeEntityToCargoImpl(), EntityAI::TakeEntityToHandsImpl(), ManBase::TakeEntityToHandsImpl(), EntityAI::TakeEntityToInventoryImpl(), ManBase::TakeEntityToInventoryImpl(), EntityAI::TakeEntityToTargetAttachmentExImpl(), ManBase::TakeEntityToTargetAttachmentImpl(), EntityAI::TakeEntityToTargetCargoExImpl(), EntityAI::TakeEntityToTargetCargoImpl(), ManBase::TakeEntityToTargetCargoImpl(), EntityAI::TakeEntityToTargetInventoryImpl(), ManBase::TakeEntityToTargetInventoryImpl(), TakeToDst(), EntityAI::TakeToDstImpl(), ManBase::TakeToDstImpl(), TryAcquireInventoryJunctureFromServer(), TryAcquireTwoInventoryJuncturesFromServer(), ValidateHandEvent(), ValidateSwap(), and ValidateSyncMove().
IsWeaponLogEnable()
static bool IsWeaponLogEnable () inline static private
References m_DoWeaponLog.
Referenced by AbortWeaponEvent(), Weapon::CanRemoveFromHands(), ejectBulletAndStoreInMagazine(), WeaponGuardBase::GuardCondition(), GuardCondition(), HandleWeaponEvents(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadAndSetCurrentFSMState(), WeaponStateBase::LoadCurrentFSMState(), Weapon::LoadCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadCurrentUnstableFSMState(), magazinesHaveEqualSizes(), WeaponStateBase::OnAbort(), WeaponChambering_Base::OnAbort(), OnAbort(), WeaponStableState::OnEntry(), WeaponStateJammed::OnEntry(), WeaponStateBase::OnEntry(), WeaponChambering_Base::OnEntry(), WeaponStartAction::OnEntry(), WeaponFire::OnEntry(), OnEntry(), OnEventForRemoteWeapon(), OnExit(), WeaponStableState::OnExit(), WeaponStateJammed::OnExit(), WeaponChambering_Base::OnExit(), WeaponChambering_Cartridge::OnExit(), WeaponStateBase::OnExit(), Weapon::OnStoreLoad(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnStoreLoad(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnStoreSave(), WeaponStartAction::OnUpdate(), PostWeaponEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessEvent(), pushToChamberFromAttachedMagazine(), pushToChamberFromInnerMagazine(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::RandomizeFSMStateEx(), Weapon::ResetWeaponAnimState(), WeaponStateBase::SaveCurrentFSMState(), Weapon::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentUnstableFSMState(), SyncAnimState(), Weapon::SyncEventToRemote(), and HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ValidateAndRepairHelper().
IsWeatherLogEnabled()
static bool IsWeatherLogEnabled () inline static private
References m_DoWeatherLog.
Referenced by Debug::WeatherLog().
QuickbarLogEnable()
static void QuickbarLogEnable (bool enable) inline static private
References m_DoQuickbarLog.
SetLogsEnabled()
static void SetLogsEnabled (bool enable) inline static private
References m_DoLogs.
Referenced by ScriptConsoleGeneralTab::OnClick().
SymptomLogEnable()
static void SymptomLogEnable (bool enable) inline static private
References m_DoSymptomDebugLog.
SyncLogEnable()
static void SyncLogEnable (bool enable) inline static private
References m_DoSyncLog.
WeaponLogEnable()
static void WeaponLogEnable (bool enable) inline static private
References m_DoWeaponLog.
Field Documentation
m_DoActionDebugLog
bool m_DoActionDebugLog static private
Referenced by ActionLogEnable(), Init(), and IsActionLogEnable().
m_DoBaseBuildingLog
bool m_DoBaseBuildingLog static private
Referenced by BaseBuildingLogEnable(), Init(), and IsBaseBuildingLogEnable().
m_DoBleedingChanceLog
bool m_DoBleedingChanceLog static private
Referenced by BleedingChancesLogEnable(), and IsBleedingChancesLogEnable().
m_DoInventoryHFSMLog
bool m_DoInventoryHFSMLog static private
Referenced by Init(), InventoryHFSMLogEnable(), and IsInventoryHFSMLogEnable().
m_DoInventoryMoveLog
bool m_DoInventoryMoveLog static private
Referenced by Init(), InventoryMoveLogEnable(), and IsInventoryMoveLogEnable().
m_DoInventoryReservationLog
bool m_DoInventoryReservationLog static private
Referenced by Init(), InventoryReservationLogEnable(), and IsInventoryReservationLogEnable().
m_DoLogs
bool m_DoLogs static private
Referenced by Init(), IsLogsEnable(), and SetLogsEnabled().
m_DoQuickbarLog
bool m_DoQuickbarLog static private
Referenced by Init(), IsQuickbarLogEnable(), and QuickbarLogEnable().
m_DoSymptomDebugLog
bool m_DoSymptomDebugLog static private
Referenced by Init(), IsSymptomLogEnable(), and SymptomLogEnable().
m_DoSyncLog
bool m_DoSyncLog static private
Referenced by Init(), IsSyncLogEnable(), and SyncLogEnable().
m_DoWeaponLog
bool m_DoWeaponLog static private
Referenced by Init(), IsWeaponLogEnable(), and WeaponLogEnable().
m_DoWeatherLog
bool m_DoWeatherLog static private
Referenced by Init(), and IsWeatherLogEnabled().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/Debug.c