DayZ Scripts: ActionInput Class Reference
ActionInput Class Reference
Private Member Functions
void ActionInput ()
void Init (PlayerBase player, ActionManagerClient am)
void SetEnablity (bool value)
protected void SetInput (string input_name)
int GetInputType ()
UAInput GetUAInput ()
bool JustActivate ()
bool IsActive ()
bool WasEnded ()
void Update ()
void Reset ()
void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask)
ActionBase GetAction ()
ActionTarget GetUsedActionTarget ()
ItemBase GetUsedMainItem ()
array< ActionBase > GetPossibleActions ()
ActionBase GetPossibleAction ()
int GetPossibleActionIndex ()
bool HasTarget ()
void OnActionStart ()
void OnActionEnd ()
void ActionsSelectReset ()
void ForceAction (ActionBase action, ActionTarget target, ItemBase item)
void ForceActionTarget (ActionTarget target)
void ClearForcedAction ()
void ClearForcedTarget ()
bool ForceActionCheck (PlayerBase player)
void SelectNextAction ()
void SelectPrevAction ()
int GetPossibleActionsCount ()
bool HasInput ()
int GetPriority ()
Private Attributes
UAIDWrapper m_input
int m_InputType
int m_Priority
bool m_DetectFromItem
bool m_DetectFromTarget
bool m_DetectFromPlayer
bool m_Enabled
bool m_JustActivate
bool m_HasTarget
PlayerBase m_Player
ref ActionTarget m_ForcedTarget
ref ForcedActionData m_ForcedActionData
ref ActionTarget m_Target
ItemBase m_MainItem
int m_ConditionMask
bool m_Active
Constructor & Destructor Documentation
ActionInput()
void ActionInput () inline private
References m_Active, m_DetectFromItem, m_DetectFromPlayer, m_DetectFromTarget, m_Enabled, m_ForcedActionData, m_ForcedTarget, m_HasTarget, m_JustActivate, and m_Priority.
Member Function Documentation
ActionsSelectReset()
void ActionsSelectReset () inline private
Referenced by OnActionStart(), Reset(), and ActionManagerClient::ResetInputsActions().
ClearForcedAction()
void ClearForcedAction () inline private
References m_ForcedActionData.
Referenced by ActionManagerClient::EjectAction().
ClearForcedTarget()
void ClearForcedTarget () inline private
References m_ForcedTarget.
ForceAction()
void ForceAction (ActionBase action, ActionTarget target, ItemBase item) inline private
References m_ForcedActionData.
Referenced by ActionManagerClient::InjectAction().
ForceActionCheck()
bool ForceActionCheck (PlayerBase player) inline private
References m_ForcedActionData, m_MainItem, and m_Target.
Referenced by NoIndicationActionInputBase::GetAction(), and UpdatePossibleActions().
ForceActionTarget()
void ForceActionTarget (ActionTarget target) inline private
References m_ForcedTarget.
GetAction()
ActionBase GetAction () inline private
Referenced by ActionManagerClient::GetPossibleAction(), and ActionManagerClient::InputsUpdate().
GetInputType()
int GetInputType () inline private
References m_InputType.
Referenced by ActionManagerClient::InputsUpdate().
GetPossibleAction()
ActionBase GetPossibleAction () inline private
GetPossibleActionIndex()
int GetPossibleActionIndex () inline private
Referenced by ActionManagerClient::GetPossibleActionIndex().
GetPossibleActions()
array< ActionBase > GetPossibleActions () inline private
Referenced by ActionManagerClient::GetPossibleActions().
GetPossibleActionsCount()
int GetPossibleActionsCount () inline private
Referenced by ActionManagerClient::GetPossibleActionCount(), ActionManagerClient::SelectNextAction(), and ActionManagerClient::SelectPrevAction().
GetPriority()
int GetPriority () inline private
References m_Priority.
Referenced by ActionManagerClient::SetActioninputOrder().
GetUAInput()
UAInput GetUAInput () inline private
References UAIDWrapper::InputP(), and m_input.
GetUsedActionTarget()
ActionTarget GetUsedActionTarget () inline private
References m_Target.
Referenced by ActionManagerClient::InputsUpdate().
GetUsedMainItem()
ItemBase GetUsedMainItem () inline private
References m_MainItem.
Referenced by ActionManagerClient::InputsUpdate().
HasInput()
bool HasInput () inline private
References m_input.
HasTarget()
bool HasTarget () inline private
Init()
void Init (PlayerBase player, ActionManagerClient am) inline private
References Debug::ActionLog(), LogManager::IsActionLogEnable(), m_Player, and ToString().
IsActive()
bool IsActive () inline private
References m_Active.
JustActivate()
bool JustActivate () inline private
References m_JustActivate.
Referenced by ActionManagerClient::InputsUpdate().
OnActionEnd()
void OnActionEnd () inline private
References Reset().
OnActionStart()
void OnActionStart () inline private
References ActionsSelectReset().
Referenced by ActionManagerClient::HandleInputsOnActionStart().
Reset()
void Reset () inline private
References ActionsSelectReset(), and m_Active.
Referenced by ActionManagerClient::HandleInputsOnActionStart(), OnActionEnd(), and ActionManagerClient::ResetInputsState().
SelectNextAction()
void SelectNextAction () inline private
Referenced by ActionManagerClient::SelectNextAction().
SelectPrevAction()
void SelectPrevAction () inline private
Referenced by ActionManagerClient::SelectPrevAction().
SetEnablity()
void SetEnablity (bool value) inline private
References m_Enabled.
SetInput()
protected void SetInput (string input_name) inline private
References Debug::ActionLog(), UAInputAPI::GetInputByName(), UAInput::GetPersistentWrapper(), GetUApi(), UAIDWrapper::InputP(), LogManager::IsActionLogEnable(), m_input, and ToString().
Referenced by ContinuousWeaponManipulationActionInput::ContinuousWeaponManipulationActionInput(), DropActionInput::DropActionInput(), and WeaponManipulationActionInput::WeaponManipulationActionInput().
Update()
void Update () inline private
References UAIDWrapper::InputP(), UAInput::LocalClick(), UAInput::LocalDoubleClick(), UAInput::LocalHold(), UAInput::LocalHoldBegin(), m_Active, m_Enabled, m_input, m_InputType, and m_JustActivate.
Referenced by ActionManagerClient::InputsUpdate().
UpdatePossibleActions()
void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask) inline private
Referenced by ActionManagerClient::FindContextualUserActions().
WasEnded()
bool WasEnded () inline private
References m_Active.
Referenced by ActionManagerClient::InputsUpdate().
Field Documentation
m_Active
bool m_Active private
Referenced by ActionInput(), IsActive(), Reset(), Update(), and WasEnded().
m_ConditionMask
int m_ConditionMask private
Referenced by NoIndicationActionInputBase::GetAction(), and NoIndicationActionInputBase::UpdatePossibleActions().
m_DetectFromItem
bool m_DetectFromItem private
Referenced by ActionInput().
m_DetectFromPlayer
bool m_DetectFromPlayer private
Referenced by ActionInput().
m_DetectFromTarget
bool m_DetectFromTarget private
Referenced by ActionInput(), and NoIndicationActionInputBase::NoIndicationActionInputBase().
m_Enabled
bool m_Enabled private
Referenced by ActionInput(), SetEnablity(), and Update().
m_ForcedActionData
ref ForcedActionData m_ForcedActionData private
Referenced by ActionInput(), ClearForcedAction(), ForceAction(), ForceActionCheck(), and NoIndicationActionInputBase::GetAction().
m_ForcedTarget
ref ActionTarget m_ForcedTarget private
Referenced by ActionInput(), ClearForcedTarget(), ForceActionTarget(), and UpdatePossibleActions().
m_HasTarget
bool m_HasTarget private
Referenced by ActionInput(), and HasTarget().
m_input
UAIDWrapper m_input private
Referenced by GetUAInput(), HasInput(), SetInput(), and Update().
m_InputType
int m_InputType private
Referenced by ContinuousWeaponManipulationActionInput::ContinuousWeaponManipulationActionInput(), DropActionInput::DropActionInput(), ExternalControlledActionInput::ExternalControlledActionInput(), GetInputType(), InventoryOnlyActionInput::InventoryOnlyActionInput(), Update(), and WeaponManipulationActionInput::WeaponManipulationActionInput().
m_JustActivate
bool m_JustActivate private
Referenced by ActionInput(), JustActivate(), and Update().
m_MainItem
ItemBase m_MainItem private
Referenced by ForceActionCheck(), NoIndicationActionInputBase::GetAction(), GetUsedMainItem(), and NoIndicationActionInputBase::UpdatePossibleActions().
m_Player
PlayerBase m_Player private
Referenced by NoIndicationActionInputBase::GetAction(), and Init().
m_Priority
int m_Priority private
Referenced by ActionInput(), and GetPriority().
m_Target
ref ActionTarget m_Target private
Referenced by ForceActionCheck(), NoIndicationActionInputBase::GetAction(), GetUsedActionTarget(), and NoIndicationActionInputBase::UpdatePossibleActions().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionInput.c