DayZ Scripts: DayZCreatureAI Class Reference
DayZCreatureAI Class Reference
do not process rotations !
Private Member Functions
proto native DayZAnimalInputController GetInputController ()
proto native void StartCommand_Death (int pType, int pDirection)
proto native void StartCommand_Move ()
proto native void StartCommand_Jump ()
proto native void StartCommand_Attack ()
proto native void StartCommand_Hit (int pType, int pDirection)
proto native DayZAnimalCommandScript StartCommand_Script (DayZAnimalCommandScript pInfectedCommand)
scripted commands
proto native DayZAnimalCommandScript StartCommand_ScriptInst (typename pCallbackClass)
proto native DayZAnimalCommandScript GetCommand_Script ()
proto native void SignalAIAttackStarted ()
proto native void SignalAIAttackEnded ()
void DayZAnimal ()
override bool IsHealthVisible ()
override bool IsAnimal ()
override bool IsInventoryVisible ()
override int GetHideIconMask ()
void CommandHandler (float dt, int currentCommandID, bool currentCommandFinished)
bool HandleDeath (int currentCommandID, DayZAnimalInputController inputController)
bool HandleDamageHit (int currentCommandID)
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
void QueueDamageHit (int type, int direction)
bool ComputeDamageHitParams (EntityAI source, string dmgZone, string ammo, out int type, out int direction)
float ComputeHitDirectionAngleDeg (EntityAI source)
int TranslateHitAngleDegToDirectionIndex (float angleDeg)
int FindComponentDirectionOffset (string component)
override protected void EOnContact (IEntity other, Contact extra)
void RegisterHitComponentsForAI ()
register hit components for AI melee (used by attacking AI)
override string GetHitComponentForAI ()
override string GetDefaultHitComponent ()
override string GetDefaultHitPositionComponent ()
override vector GetDefaultHitPosition ()
protected vector SetDefaultHitPosition (string pSelection)
override protected float ConvertNonlethalDamage (float damage, DamageType damageType)
Private Attributes
protected ref array< ref DayZAIHitComponent > m_HitComponentsForAI
Melee hit components (AI targeting)
protected string m_DefaultHitComponent
protected string m_DefaultHitPositionComponent
protected vector m_DefaultHitPosition
bool m_DamageHitToProcess = false
int m_DamageHitType = 0
int m_DamageHitDirection = 0
Detailed Description
do not process rotations !
Member Function Documentation
CommandHandler()
void CommandHandler (float dt, int currentCommandID, bool currentCommandFinished) inline private
for mods
for mods
References DayZAnimalInputController::IsAttack(), DayZCreatureAIInputController::IsJump(), ModCommandHandlerAfter(), ModCommandHandlerBefore(), and ModCommandHandlerInside().
ComputeDamageHitParams()
bool ComputeDamageHitParams (EntityAI source, string dmgZone, string ammo, out int type, out int direction) inline private
ComputeHitDirectionAngleDeg()
float ComputeHitDirectionAngleDeg (EntityAI source) inline private
References Math::Acos(), vector::Dot(), GetPosition, vector::Normalize(), and Math::RAD2DEG.
ConvertNonlethalDamage()
override protected float ConvertNonlethalDamage (float damage, DamageType damageType) inline private
References GameConstants::NL_DAMAGE_CLOSECOMBAT_CONVERSION_ANIMALS, and GameConstants::NL_DAMAGE_FIREARM_CONVERSION_ANIMALS.
DayZAnimal()
void DayZAnimal () inline private
sets default hit position and cache it here (mainly for impact particles)
References GetDefaultHitPositionComponent(), m_HitComponentsForAI, and RegisterHitComponentsForAI().
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
References CFG_AMMO, COMP_TYPE_ANIMAL_BLEEDING, component, ComponentAnimalBleeding::CreateWound(), g_Game, and TotalDamageResult::GetDamage().
EOnContact()
override protected void EOnContact (IEntity other, Contact extra) inline private
Phx contact event
References GetGame().
FindComponentDirectionOffset()
int FindComponentDirectionOffset (string component) inline private
References component.
GetCommand_Script()
proto native DayZAnimalCommandScript GetCommand_Script () private
GetDefaultHitComponent()
override string GetDefaultHitComponent () inline private
References m_DefaultHitComponent.
GetDefaultHitPosition()
override vector GetDefaultHitPosition () inline private
GetDefaultHitPositionComponent()
override string GetDefaultHitPositionComponent () inline private
References m_DefaultHitPositionComponent.
GetHideIconMask()
override int GetHideIconMask () inline private
GetHitComponentForAI()
override string GetHitComponentForAI () inline private
References GetDefaultHitComponent(), m_HitComponentsForAI, and DayZAIHitComponentHelpers::SelectMostProbableHitComponent().
GetInputController()
proto native DayZAnimalInputController GetInputController () private
HandleDamageHit()
bool HandleDamageHit (int currentCommandID) inline private
HandleDeath()
bool HandleDeath (int currentCommandID, DayZAnimalInputController inputController) inline private
References DayZAnimalInputController::IsDead().
IsAnimal()
override bool IsAnimal () inline private
IsHealthVisible()
override bool IsHealthVisible () inline private
IsInventoryVisible()
override bool IsInventoryVisible () inline private
QueueDamageHit()
void QueueDamageHit (int type, int direction) inline private
RegisterHitComponentsForAI()
void RegisterHitComponentsForAI () inline private
register hit components for AI melee (used by attacking AI)
registers default hit compoent for the entity
registers default hit position component for entity
register hit components that are selected by probability
References m_DefaultHitComponent, m_DefaultHitPositionComponent, m_HitComponentsForAI, and DayZAIHitComponentHelpers::RegisterHitComponent().
SetDefaultHitPosition()
protected vector SetDefaultHitPosition (string pSelection) inline private
SignalAIAttackEnded()
proto native void SignalAIAttackEnded () private
SignalAIAttackStarted()
proto native void SignalAIAttackStarted () private
StartCommand_Attack()
proto native void StartCommand_Attack () private
StartCommand_Death()
proto native void StartCommand_Death (int pType, int pDirection) private
StartCommand_Hit()
proto native void StartCommand_Hit (int pType, int pDirection) private
StartCommand_Jump()
proto native void StartCommand_Jump () private
StartCommand_Move()
proto native void StartCommand_Move () private
StartCommand_Script()
proto native DayZAnimalCommandScript StartCommand_Script (DayZAnimalCommandScript pInfectedCommand) private
scripted commands
StartCommand_ScriptInst()
proto native DayZAnimalCommandScript StartCommand_ScriptInst (typename pCallbackClass) private
TranslateHitAngleDegToDirectionIndex()
int TranslateHitAngleDegToDirectionIndex (float angleDeg) inline private
Field Documentation
m_DamageHitDirection
int m_DamageHitDirection = 0 private
m_DamageHitToProcess
bool m_DamageHitToProcess = false private
m_DamageHitType
int m_DamageHitType = 0 private
m_DefaultHitComponent
protected string m_DefaultHitComponent private
m_DefaultHitPosition
protected vector m_DefaultHitPosition private
m_DefaultHitPositionComponent
protected string m_DefaultHitPositionComponent private
m_HitComponentsForAI
protected ref array<ref DayZAIHitComponent> m_HitComponentsForAI private
Melee hit components (AI targeting)
The documentation for this class was generated from the following file:
P:/scripts/3_game/entities/dayzanimal.c