DayZ Scripts: DayZCreatureAIInputController Class Reference
DayZCreatureAIInputController Class Reference
Private Member Functions
proto native void OverrideMovementSpeed (bool state, float movementSpeed)
proto native float GetMovementSpeed ()
proto native void OverrideTurnSpeed (bool state, float turnSpeed)
proto native float GetTurnSpeed ()
proto native void OverrideHeading (bool state, float heading)
proto native float GetHeading ()
proto native void OverrideJump (bool state, int jumpType, float jumpHeight=0)
proto native bool IsJump ()
proto native int GetJumpType ()
proto native float GetJumpHeight ()
proto native void OverrideLookAt (bool state, vector direction)
proto native bool IsLookAtEnabled ()
proto native vector GetLookAtDirectionWS ()
proto native void OverrideAlertLevel (bool state, bool alerted, int level, float inLevel)
proto native int GetAlertLevel ()
proto native float GetAlertInLevel ()
proto native bool IsAlerted ()
proto native void OverrideBehaviourSlot (bool state, int slot)
proto native int GetBehaviourSlot ()
private void DayZCreatureAIInputController ()
never created by script
private void ~DayZCreatureAIInputController ()
never destroyed by script
Constructor & Destructor Documentation
DayZCreatureAIInputController()
private void DayZCreatureAIInputController () inline private
never created by script
~DayZCreatureAIInputController()
private void ~DayZCreatureAIInputController () inline private
never destroyed by script
Member Function Documentation
GetAlertInLevel()
proto native float GetAlertInLevel () private
GetAlertLevel()
proto native int GetAlertLevel () private
GetBehaviourSlot()
proto native int GetBehaviourSlot () private
GetHeading()
proto native float GetHeading () private
GetJumpHeight()
proto native float GetJumpHeight () private
GetJumpType()
proto native int GetJumpType () private
GetLookAtDirectionWS()
proto native vector GetLookAtDirectionWS () private
GetMovementSpeed()
proto native float GetMovementSpeed () private
Referenced by DayZInfected::HandleMove().
GetTurnSpeed()
proto native float GetTurnSpeed () private
IsAlerted()
proto native bool IsAlerted () private
IsJump()
proto native bool IsJump () private
Referenced by DayZCreatureAI::CommandHandler().
IsLookAtEnabled()
proto native bool IsLookAtEnabled () private
OverrideAlertLevel()
proto native void OverrideAlertLevel (bool state, bool alerted, int level, float inLevel) private
Referenced by DayZCreature::ModCommandHandlerBefore().
OverrideBehaviourSlot()
proto native void OverrideBehaviourSlot (bool state, int slot) private
Referenced by DayZCreature::ModCommandHandlerBefore().
OverrideHeading()
proto native void OverrideHeading (bool state, float heading) private
Referenced by DayZCreature::ModCommandHandlerBefore().
OverrideJump()
proto native void OverrideJump (bool state, int jumpType, float jumpHeight = 0) private
Referenced by DayZCreature::ModCommandHandlerBefore().
OverrideLookAt()
proto native void OverrideLookAt (bool state, vector direction) private
OverrideMovementSpeed()
proto native void OverrideMovementSpeed (bool state, float movementSpeed) private
Referenced by DayZCreature::ModCommandHandlerBefore().
OverrideTurnSpeed()
proto native void OverrideTurnSpeed (bool state, float turnSpeed) private
Referenced by DayZCreature::ModCommandHandlerBefore().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Entities/DayZCreatureAIInputController.c