DayZ Scripts: ComponentsBank Class Reference
ComponentsBank Class Reference
Private Member Functions
void ComponentsBank (EntityAI entity_parent)
Component GetComponent (int comp_type, string extended_class_name="")
bool DeleteComponent (int comp_type)
private Component CreateComponent (int comp_type, string extended_class_name="")
bool IsComponentAlreadyExist (int comp_type)
Private Attributes
private EntityAI m_EntityParent
private ref Component m_Components [COMP_TYPE_COUNT]
Constructor & Destructor Documentation
ComponentsBank()
void ComponentsBank (EntityAI entity_parent) inline private
References m_EntityParent.
Member Function Documentation
CreateComponent()
private Component CreateComponent (int comp_type, string extended_class_name = "") inline private
References Empty, Component::Event_OnAwake(), Component::Event_OnInit(), Component::GetNameByType(), IsComponentAlreadyExist(), Component::IsTypeExist(), Component::LogErrorBadCompType(), Component::LogWarningAlredyExist(), m_Components, m_EntityParent, Component::SetParentEntityAI(), and string::ToType().
Referenced by GetComponent().
DeleteComponent()
bool DeleteComponent (int comp_type) inline private
References IsComponentAlreadyExist(), and m_Components.
GetComponent()
Component GetComponent (int comp_type, string extended_class_name = "") inline private
References CreateComponent(), IsComponentAlreadyExist(), Component::IsTypeExist(), Component::LogErrorBadCompType(), and m_Components.
IsComponentAlreadyExist()
bool IsComponentAlreadyExist (int comp_type) inline private
References m_Components.
Referenced by CreateComponent(), DeleteComponent(), and GetComponent().
Field Documentation
m_Components
private ref Component m_Components[COMP_TYPE_COUNT] private
Referenced by CreateComponent(), DeleteComponent(), GetComponent(), and IsComponentAlreadyExist().
m_EntityParent
private EntityAI m_EntityParent private
Referenced by ComponentsBank(), and CreateComponent().
The documentation for this class was generated from the following file:
3_Game/tools/ComponentsBank.c