DayZ Scripts: UIManager Class Reference
UIManager Class Reference
Private Member Functions
proto native UIScriptedMenu EnterScriptedMenu (int id, UIMenuPanel parent)
Create & open menu with specific id (see MenuID) and set its parent.
proto native void EnterServerBrowser (UIMenuPanel parentMenu)
proto native UIScriptedMenu ShowScriptedMenu (UIScriptedMenu menu, UIMenuPanel parent)
proto native void HideScriptedMenu (UIScriptedMenu menu)
proto native Widget GetWidgetUnderCursor ()
proto native bool IsDialogVisible ()
proto native bool IsModalVisible ()
proto native void CloseSpecificDialog (int id)
proto native void CloseDialog ()
proto native void HideDialog ()
UIScriptedMenu CreateScriptedMenu (int id, UIMenuPanel parent)
proto native void ShowDialog (string caption, string text, int id, int butts, int def, int type, UIScriptedMenu handler)
Shows message dialog.
proto native bool ShowCursor (bool visible)
proto native bool IsCursorVisible ()
proto native bool IsDialogQueued ()
proto native bool ShowQueuedDialog ()
proto native int GetLoginQueuePosition ()
proto native bool ScreenFadeVisible ()
proto native void ScreenFadeIn (float duration, string text, int backgroundColor, int textColor)
proto native void ScreenFadeOut (float duration)
proto native bool IsScaledMode ()
proto native void SetScaledMode (bool enabled)
proto native UIScriptedMenu GetMenu ()
Returns most-top open menu.
bool Back ()
Close top window on windows stack, returns true when any window is closed.
bool CloseAll ()
Close all opened menus.
bool CloseAllSubmenus ()
Close all opened menus except first menu.
bool CloseMenu (int id)
Close menu with specific ID (see MenuID)
bool HideMenu (int id)
bool IsMenuOpen (int id)
Returns true if menu with specific ID is opened (see MenuID)
UIScriptedMenu FindMenu (int id)
Returns menu with specific ID if it is open (see MenuID)
void OpenWindow (int id)
void CloseWindow (int id)
void DeleteWindow (UIScriptedWindow window)
bool IsWindowOpened (int id)
void ShowUICursor (bool visible)
Detailed Description
Definition at line 1 of file UIManager.c.
Member Function Documentation
Back()
bool Back () inline private
Close top window on windows stack, returns true when any window is closed.
Definition at line 64 of file UIManager.c.
References UIMenuPanel::Close(), GetMenu(), and IsDialogVisible().
Referenced by UIScriptedMenu::Apply(), Back(), UIScriptedMenu::Back(), UIScriptedMenu::ChangeAccount(), UIScriptedMenu::CloseMenu(), PluginBase::EditorToggle(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnModalResult(), UIScriptedMenu::StopVideo(), PluginBase::ToggleCameraTools(), and UIScriptedMenu::Update().
CloseAll()
bool CloseAll () inline private
Close all opened menus.
Definition at line 80 of file UIManager.c.
References UIMenuPanel::Close(), GetMenu(), and UIMenuPanel::GetParentMenu().
Referenced by MissionBase::CloseAllMenus(), ManBase::CloseInventoryMenu(), MissionBase::DestroyAllMenus(), UIScriptedMenu::GameRetry(), MissionBase::HandleMapToggleByKeyboardShortcut(), OnLoginTimeEvent(), MissionBase::OnMissionFinish(), ManBase::OnPlayerLoaded(), OnRespawnEvent(), ActionUnfoldMapCB::PerformMapChange(), and UpdateLoginQueue().
CloseAllSubmenus()
bool CloseAllSubmenus () inline private
Close all opened menus except first menu.
Definition at line 100 of file UIManager.c.
References UIMenuPanel::Close(), GetMenu(), and UIMenuPanel::GetParentMenu().
Referenced by DisconnectSessionEx().
CloseDialog()
proto native void CloseDialog () private
Referenced by DisconnectSessionEx(), DayZPlayer::LockControls(), ManBase::OnUnconsciousStop(), and ReleaseFocus().
CloseMenu()
bool CloseMenu (int id) inline private
Close menu with specific ID (see MenuID)
Definition at line 119 of file UIManager.c.
References UIMenuPanel::Close(), UIMenuPanel::GetID(), GetMenu(), and UIMenuPanel::GetParentMenu().
Referenced by MissionBase::Continue(), BiosUserManager::OnJoin(), and BiosUserManager::OnPartyHost().
CloseSpecificDialog()
proto native void CloseSpecificDialog (int id) private
CloseWindow()
void CloseWindow (int id) inline private
Definition at line 210 of file UIManager.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, DeleteWindow(), CGame::GetCallQueue(), GetGame(), UIScriptedWindow::GetWindow(), UIScriptedWindow::HideWindow(), and UIScriptedWindow::RemoveFromActiveWindows().
Referenced by UIScriptedWindow::CloseWindow(), and OpenWindow().
CreateScriptedMenu()
UIScriptedMenu CreateScriptedMenu (int id, UIMenuPanel parent) inline private
Definition at line 17 of file UIManager.c.
References EnterScriptedMenu(), and HideScriptedMenu().
DeleteWindow()
void DeleteWindow (UIScriptedWindow window) inline private
Definition at line 230 of file UIManager.c.
Referenced by CloseWindow().
EnterScriptedMenu()
proto native UIScriptedMenu EnterScriptedMenu (int id, UIMenuPanel parent) private
Create & open menu with specific id (see MenuID) and set its parent.
Referenced by CreateScriptedMenu(), PluginBase::EditorToggle(), MissionBase::HandleMapToggleByKeyboardShortcut(), BiosUserManager::OnPartyHost(), UIScriptedMenu::OpenMenu(), MissionBase::Pause(), ActionUnfoldMapCB::PerformMapChange(), SelectGamepad(), MissionBase::ShowChat(), and PluginBase::ToggleCameraTools().
EnterServerBrowser()
proto native void EnterServerBrowser (UIMenuPanel parentMenu) private
FindMenu()
UIScriptedMenu FindMenu (int id) inline private
Returns menu with specific ID if it is open (see MenuID)
Definition at line 161 of file UIManager.c.
References GetMenu().
Referenced by ManBase::CloseMapEx(), UIScriptedMenu::Init(), IsMenuOpen(), UIScriptedMenu::OnClick(), ActionUnfoldMapCB::OnFinish(), ActionReadPaperCB::OnStateChange(), ActionWritePaperCB::OnStateChange(), ManBase::OnUnconsciousStop(), MissionBase::OnUpdate(), InventoryItem::OnVariablesSynchronized(), Hud::RefreshQuickbar(), and EntityAI::UpdateInventoryMenu().
GetLoginQueuePosition()
proto native int GetLoginQueuePosition () private
Referenced by UpdateLoginQueue().
GetMenu()
proto native UIScriptedMenu GetMenu () private
Returns most-top open menu.
Referenced by PluginBase::AddKeyframe(), Back(), CloseAll(), CloseAllSubmenus(), ManBase::CloseInventoryMenu(), CloseMenu(), MissionBase::Continue(), PluginBase::CursorHide(), PluginBase::CursorShow(), PluginBase::DeleteKeyframe(), MissionBaseWorld::DumpCurrentUILayout(), FindMenu(), Icon::FlagAction(), PluginBase::FreeCameraControlDisable(), PluginBase::FreeCameraControlEnable(), HideMenu(), PluginBase::IsCurrentUIPageValid(), PluginBase::IsInConsole(), PluginBase::IsIngame(), BiosUserManager::OnGameNameChanged(), OnLoginTimeEvent(), ScriptedWidgetEventHandler::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnMouseEnter(), OptionSelectorBase::OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), OptionSelectorBase::OnMouseLeave(), OnRespawnEvent(), MissionBase::OnUpdate(), PluginBase::PlayPause(), PluginBase::Save(), Dispatcher::SceneEditorCommand(), Dispatcher::ScriptConsoleAddPrint(), Dispatcher::ScriptConsoleGetSelectedItem(), Dispatcher::ScriptConsoleHistoryBack(), Dispatcher::ScriptConsoleHistoryForward(), SelectGamepad(), ScriptedWidgetEventHandler::SelectPlayer(), SetDatabaseID(), ScriptedWidgetEventHandler::ShowActionMenu(), HandsContainer::ShowActionMenuCombine(), Icon::ShowActionMenuCombine(), MissionBase::ShowInventory(), PluginBase::SpawnFromClipboard(), and UpdateLoginQueue().
GetWidgetUnderCursor()
proto native Widget GetWidgetUnderCursor () private
HideDialog()
proto native void HideDialog () private
Referenced by MissionBase::DestroyAllMenus(), and MissionBase::OnMissionFinish().
HideMenu()
bool HideMenu (int id) inline private
Definition at line 136 of file UIManager.c.
References GetMenu(), and HideScriptedMenu().
HideScriptedMenu()
proto native void HideScriptedMenu (UIScriptedMenu menu) private
Referenced by CreateScriptedMenu(), MissionBase::HideInventory(), and HideMenu().
IsCursorVisible()
proto native bool IsCursorVisible () private
IsDialogQueued()
proto native bool IsDialogQueued () private
IsDialogVisible()
proto native bool IsDialogVisible () private
Referenced by Back(), and MissionBase::OnUpdate().
IsMenuOpen()
bool IsMenuOpen (int id) inline private
Returns true if menu with specific ID is opened (see MenuID)
Definition at line 155 of file UIManager.c.
References FindMenu().
Referenced by MissionBase::HandleMapToggleByKeyboardShortcut(), MissionBase::IsPaused(), Update(), and ActionManagerClient::Update().
IsModalVisible()
proto native bool IsModalVisible () private
IsScaledMode()
proto native bool IsScaledMode () private
IsWindowOpened()
bool IsWindowOpened (int id) inline private
Definition at line 235 of file UIManager.c.
References UIScriptedWindow::GetWindow().
OpenWindow()
void OpenWindow (int id) inline private
Definition at line 179 of file UIManager.c.
References UIScriptedWindow::AddToActiveWindows(), CloseWindow(), Mission::CreateScriptedWindow(), GetGame(), CGame::GetMission(), UIScriptedWindow::GetWindow(), GUI_WINDOW_MISSION_LOADER, and UIScriptedWindow::Init().
ScreenFadeIn()
proto native void ScreenFadeIn (float duration, string text, int backgroundColor, int textColor) private
Referenced by DayZPlayer::ShowDeadScreen(), and ManBase::ShowUnconsciousScreen().
ScreenFadeOut()
proto native void ScreenFadeOut (float duration) private
Referenced by UIScriptedMenu::Init(), LoadProgressUpdate(), MissionBase::OnUpdate(), DayZPlayer::ShowDeadScreen(), and ManBase::ShowUnconsciousScreen().
ScreenFadeVisible()
proto native bool ScreenFadeVisible () private
SetScaledMode()
proto native void SetScaledMode (bool enabled) private
ShowCursor()
proto native bool ShowCursor (bool visible) private
Referenced by UIScriptedMenu::OnHide(), UIScriptedMenu::OnMouseButtonDown(), UIScriptedMenu::Play(), ShowUICursor(), and UIScriptedMenu::Stop().
ShowDialog()
proto native void ShowDialog (string caption, string text, int id, int butts, int def, int type, UIScriptedMenu handler) private
Shows message dialog.
Parameters
caption
text
id custom user id
butts DialogBoxType
def DialogBoxButton
type DialogMessageType
handler
usage :
const int QUIT_DIALOG_ID = 76;
GetGame().GetUIManager().ShowDialog("Quit", "Do You really want to quit?", QUIT_DIALOG_ID, DBT_YESNO, DBB_YES, DMT_QUESTION, this);
...
// after user pass dialog, callback on menu/event handler is called
ScriptedWidgetEventHandler::OnModalResult(Widget  w, int  x, int  y, int  code,  int  result)
{
  if (code == QUIT_DIALOG_ID && result == DBB_YES) // yes this is callback for dialog we show earlier and user press YES button
  {
      Quit();
  }
}
Referenced by UIScriptedMenu::Exit(), HandleError(), UIScriptedMenu::Init(), OnlineServices::OnAutoConnectToEmptyServer(), UIScriptedMenu::OnClick(), ScriptedWidgetEventHandler::OnClick(), UIScriptedMenu::OnClick_Respawn(), and UIScriptedMenu::Play().
ShowQueuedDialog()
proto native bool ShowQueuedDialog () private
Referenced by CheckDialogs().
ShowScriptedMenu()
proto native UIScriptedMenu ShowScriptedMenu (UIScriptedMenu menu, UIMenuPanel parent) private
Referenced by OnLoginTimeEvent(), MissionBase::ShowInventory(), and UpdateLoginQueue().
ShowUICursor()
void ShowUICursor (bool visible) inline private
Definition at line 246 of file UIManager.c.
References ShowCursor().
Referenced by ScriptedWidgetEventHandler::Apply(), PluginBase::CaptureFocus(), CaptureFocus(), PluginBase::FreeCameraControlDisable(), PluginBase::FreeCameraControlEnable(), Inventory(), UIMenuPanel::LockControls(), DayZPlayer::LockControls(), UIScriptedMenu::OnHide(), MissionBase::OnMissionStart(), UIScriptedMenu::OnShow(), PluginBase::ReleaseFocus(), ReleaseFocus(), PluginBase::SetDeveloperItemClientEx(), PluginBase::ToggleFocus(), and UIMenuPanel::UnlockControls().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/UIManager.c