DayZ Scripts: StatDebugObject Class Reference
StatDebugObject Class Reference
Private Member Functions
void StatDebugObject (string name, float value, eRemoteDebugType type)
void Debug ()
string GetName ()
string GetValue ()
void SetType (eRemoteDebugType type)
eRemoteDebugType GetType ()
Private Attributes
string m_Name
float m_Value
eRemoteDebugType m_Type
Constructor & Destructor Documentation
StatDebugObject()
void StatDebugObject (string name, float value, eRemoteDebugType type) inline private
References m_Name, m_Type, m_Value, and name.
Member Function Documentation
Debug()
void Debug () inline private
References m_Name, m_Value, PrintString(), and float::ToString().
GetName()
string GetName () inline private
References m_Name.
GetType()
eRemoteDebugType GetType () inline private
References m_Type.
Referenced by SerializeNames(), and SerializeValues().
GetValue()
string GetValue () inline private
References m_Value, and float::ToString().
SetType()
void SetType (eRemoteDebugType type) inline private
References m_Type.
Field Documentation
m_Name
string m_Name private
Referenced by Debug(), GetName(), and StatDebugObject().
m_Type
eRemoteDebugType m_Type private
Referenced by GetType(), SetType(), and StatDebugObject().
m_Value
float m_Value private
Referenced by Debug(), GetValue(), and StatDebugObject().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerStats/StatDebugObject.c