DayZ Scripts: AttachmentCategoriesContainer Class Reference
AttachmentCategoriesContainer Class Reference
Private Member Functions
void AttachmentCategoriesContainer (LayoutHolder parent, int sort=-1)
void SetEntity (EntityAI entity)
void SetHeaderName ()
override bool IsDisplayable ()
override void UpdateInterval ()
void LoadAttachmentCategoriesIcon (SlotsContainer items_cont, string icon_name, int slot_number)
int GetAttachmentCategoriesCount (string config_path)
SlotsContainer GetSlotsContainer (int icons_row)
SlotsIcon GetCargoSlotsIcon ()
void ShowInSlots (string category, bool show)
override bool CanDisplayAnyCategory ()
override void UpdateRadialIcon ()
string GetAttachmentCategory (string config_path_attachment_categories, int i)
string GetIconName (string config_path_attachment_categories, string attachment_category)
int GetViewIndex (string config_path_attachment_categories, string attachment_category)
void MouseClick (Widget w)
override void ExpandCollapseContainer ()
bool IsHeaderActive ()
void InitIconsContainers ()
void InitGhostSlots ()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override void CollapseButtonOnMouseButtonDown (Widget w)
override void Open ()
override void Close ()
override void OnHide ()
override bool CanOpenCloseContainerEx (EntityAI focusedEntity)
override bool CanSplitEx (EntityAI focusedEntity)
Private Attributes
protected ref map< string, int > m_CategorySlotIndex
protected int m_SlotsCount
protected SlotsIcon m_CargoSlotsIcon
Constructor & Destructor Documentation
AttachmentCategoriesContainer()
void AttachmentCategoriesContainer (LayoutHolder parent, int sort = -1) inline private
References m_CategorySlotIndex.
Member Function Documentation
CanDisplayAnyCategory()
override bool CanDisplayAnyCategory () inline private
References Class::CastTo(), AttachmentCategoriesRow::GetCategoryIdentifier(), m_Entity, and m_SlotsCount.
Referenced by IsDisplayable(), and UpdateRadialIcon().
CanOpenCloseContainerEx()
override bool CanOpenCloseContainerEx (EntityAI focusedEntity) inline private
References SlotsIcon::GetContainer(), and ClosableContainer::IsDisplayable().
CanSplitEx()
override bool CanSplitEx (EntityAI focusedEntity) inline private
Close()
override void Close () inline private
References SlotsIcon::GetObject(), m_CargoSlotsIcon, and OnHide().
CollapseButtonOnMouseButtonDown()
override void CollapseButtonOnMouseButtonDown (Widget w) inline private
References Container::Close(), CollapsibleContainer::m_CollapsibleHeader, CollapsibleContainer::m_Hidden, OnHide(), CollapsibleContainer::OnShow(), CollapsibleContainer::SetCollapsibleHeaderArrowState(), CollapsibleHeader::SetHeaderVisible(), and CollapsibleContainer::UpdateCollapseButtons().
DraggingOverHeader()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
References ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), name, ColorManager::RED_COLOR, ColorManager::SetColor(), and ItemManager::ShowSourceDropzone().
ExpandCollapseContainer()
override void ExpandCollapseContainer () inline private
References SlotsIcon::GetContainer().
GetAttachmentCategoriesCount()
int GetAttachmentCategoriesCount (string config_path) inline private
References CGame::ConfigGetChildrenCount(), and GetGame().
Referenced by InitGhostSlots(), and InitIconsContainers().
GetAttachmentCategory()
string GetAttachmentCategory (string config_path_attachment_categories, int i) inline private
References CGame::ConfigGetChildName(), and GetGame().
Referenced by InitGhostSlots().
GetCargoSlotsIcon()
SlotsIcon GetCargoSlotsIcon () inline private
References m_CargoSlotsIcon.
GetIconName()
string GetIconName (string config_path_attachment_categories, string attachment_category) inline private
References CGame::ConfigGetText(), and GetGame().
Referenced by InitGhostSlots().
GetSlotsContainer()
SlotsContainer GetSlotsContainer (int icons_row) inline private
References AttachmentCategoriesSlotsContainer::GetSlotsContainer().
Referenced by InitGhostSlots(), and ShowInSlots().
GetViewIndex()
int GetViewIndex (string config_path_attachment_categories, string attachment_category) inline private
References CGame::ConfigGetInt(), and GetGame().
InitGhostSlots()
void InitGhostSlots () inline private
References CGame::ConfigGetText(), GetAttachmentCategoriesCount(), GetAttachmentCategory(), GetGame(), SlotsIcon::GetGhostSlot(), GetIconName(), SlotsIcon::GetRadialIconPanel(), SlotsContainer::GetSlotIcon(), GetSlotsContainer(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, AttachmentCategoriesRow::Init(), CollapsibleContainer::Insert(), ITEMS_IN_ROW, LoadAttachmentCategoriesIcon(), m_CargoSlotsIcon, m_CategorySlotIndex, m_Entity, m_SlotsCount, name, ClosableContainer::Open(), SlotsIcon::SetContainer(), SlotsIcon::SetSlotDisplayName(), and StaticGUIUtils::VerifyIconImageString().
Referenced by SetEntity().
InitIconsContainers()
void InitIconsContainers () inline private
References GetAttachmentCategoriesCount(), ITEMS_IN_ROW, m_Entity, and m_SlotsCount.
Referenced by SetEntity().
IsDisplayable()
override bool IsDisplayable () inline private
References CanDisplayAnyCategory(), and Container::IsEmpty().
Referenced by Open().
IsHeaderActive()
bool IsHeaderActive () inline private
References CollapsibleContainer::m_CollapsibleHeader.
LoadAttachmentCategoriesIcon()
void LoadAttachmentCategoriesIcon (SlotsContainer items_cont, string icon_name, int slot_number) inline private
References SlotsIcon::GetGhostSlot(), SlotsContainer::GetSlotIcon(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, and StaticGUIUtils::VerifyIconImageString().
Referenced by InitGhostSlots().
MouseClick()
void MouseClick (Widget w) inline private
References ClosableContainer::Close(), SlotsIcon::GetContainer(), ClosableContainer::IsOpened(), and ClosableContainer::Open().
OnDropReceivedFromHeader()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
References GetGame(), ItemPreviewWidget::GetItem(), CGame::GetPlayer(), m_Entity, and name.
OnHide()
override void OnHide () inline private
References SlotsIcon::IsVisible(), m_CargoSlotsIcon, CollapsibleContainer::m_CollapsibleHeader, and CollapsibleHeader::SetHeaderVisible().
Referenced by Close(), and CollapseButtonOnMouseButtonDown().
Open()
override void Open () inline private
References IsDisplayable(), and CollapsibleContainer::OnShow().
SetEntity()
void SetEntity (EntityAI entity) inline private
References WidgetEventHandler::GetInstance(), InitGhostSlots(), InitIconsContainers(), m_Entity, m_Parent, m_RootWidget, WidgetEventHandler::RegisterOnChildAdd(), WidgetEventHandler::RegisterOnChildRemove(), and SetHeaderName().
Referenced by VicinityContainer::UpdateInterval().
SetHeaderName()
void SetHeaderName () inline private
References CollapsibleContainer::m_CollapsibleHeader, m_Entity, and Header::SetName().
Referenced by SetEntity().
ShowInSlots()
void ShowInSlots (string category, bool show) inline private
References SlotsContainer::GetSlotIcon(), GetSlotsContainer(), ITEMS_IN_ROW, and m_CategorySlotIndex.
Referenced by UpdateInterval().
UpdateInterval()
override void UpdateInterval () inline private
References AttachmentCategoriesRow::GetCategoryIdentifier(), AttachmentCategoriesSlotsContainer::IsDisplayable(), ClosableContainer::IsDisplayable(), m_CargoSlotsIcon, CollapsibleContainer::m_CollapsibleHeader, m_Entity, CollapsibleContainer::m_Hidden, m_SlotsCount, Container::OnShow(), ShowInSlots(), SlotsIcon::UpdateInterval(), and AttachmentCategoriesRow::UpdateInterval().
UpdateRadialIcon()
override void UpdateRadialIcon () inline private
References CanDisplayAnyCategory(), m_Entity, and CollapsibleContainer::m_Hidden.
Field Documentation
m_CargoSlotsIcon
protected SlotsIcon m_CargoSlotsIcon private
Referenced by Close(), GetCargoSlotsIcon(), InitGhostSlots(), OnHide(), and UpdateInterval().
m_CategorySlotIndex
protected ref map<string, int> m_CategorySlotIndex private
Referenced by AttachmentCategoriesContainer(), InitGhostSlots(), and ShowInSlots().
m_SlotsCount
protected int m_SlotsCount private
Referenced by CanDisplayAnyCategory(), InitGhostSlots(), InitIconsContainers(), and UpdateInterval().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Inherited/AttachmentCategoriesContainer.c