DayZ Scripts: WBModuleDef Class Reference
WBModuleDef Class Reference
Private Member Functions
proto native external bool SetOpenedResource (string filename)
proto native external int GetNumContainers ()
proto native external BaseContainer GetContainer (int index=0)
proto external bool GetCmdLine (string name, out string value)
proto native external bool Save ()
proto native external bool Close ()
Detailed Description
Definition at line 19 of file workbenchApi.c.
Member Function Documentation
Close()
proto native external bool Close () private
Referenced by ResavePlugin::RunCommandline().
GetCmdLine()
proto external bool GetCmdLine (string name, out string value) private
Referenced by ResavePlugin::RunCommandline().
GetContainer()
proto native external BaseContainer GetContainer (int index = 0) private
Referenced by CheckLocalisationPlugin::CheckTextIDs().
GetNumContainers()
proto native external int GetNumContainers () private
Save()
proto native external bool Save () private
Referenced by ResavePlugin::Resave().
SetOpenedResource()
proto native external bool SetOpenedResource (string filename) private
Referenced by CheckLocalisationPlugin::CheckTextIDs(), and ResavePlugin::Resave().
The documentation for this class was generated from the following file:
P:/scripts/1_Core/workbenchApi.c