DayZ Scripts: WeaponGuardBase Class Reference
WeaponGuardBase Class Reference
represents guard on a transition from state to state
Private Member Functions
bool GuardCondition (WeaponEventBase e)
void GuardAnd (WeaponGuardBase arg0=NULL, WeaponGuardBase arg1=NULL)
override bool GuardCondition (WeaponEventBase e)
void GuardNot (WeaponGuardBase arg0=NULL)
override bool GuardCondition (WeaponEventBase e)
void GuardOr (WeaponGuardBase arg0=NULL, WeaponGuardBase arg1=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardJammed (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardIsDestroyed (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardHasAmmoInnerMagazine (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardHasAmmoInEvent (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardHasMag (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardChamberEmpty (Weapon_Base w=NULL, int muzzle_index=0)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardCurrentChamberEmpty (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardAnyChamberEmpty (Weapon_Base w=NULL, int muzzle_index=0)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardChamberFull (Weapon_Base w=NULL, int muzzle_index=0)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardCurrentChamberFull (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardInnerMagazineFull (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardInnerMagazineFullShareChamber (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardChamberFiredOut (Weapon_Base w=NULL, int muzzle_index=0)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardCurrentChamberFiredOut (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardAnyChamberFiredOut (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardCanAttachMag (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardCanSwapMag (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardCanDetachMag (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardChamberHasRoomForMoreThanOne (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardChamberHasRoomForOne (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardChamberMultiHasRoomBulltet (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardChamberMultiHasRoomBulltetIgnoreLast (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardHasAmmoInLoopedState (WeaponChambering_Base state)
override bool GuardCondition (WeaponEventBase e)
void WeaponGuardMagazinesHaveEqualSizes (Weapon_Base w=NULL)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
Private Attributes
ref WeaponGuardBase m_arg0
ref WeaponGuardBase m_arg1
protected Weapon_Base m_weapon
protected int m_muzzle
WeaponChambering_Base m_state
Detailed Description
represents guard on a transition from state to state
Definition at line 4 of file Guards.c.
Member Function Documentation
GuardAnd()
void GuardAnd (WeaponGuardBase arg0 = NULL, WeaponGuardBase arg1 = NULL) inline private
Definition at line 19 of file Guards.c.
GuardCondition() [1/29]
bool GuardCondition (WeaponEventBase e) inline private
Definition at line 11 of file Guards.c.
GuardCondition() [2/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 21 of file Guards.c.
References LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
GuardCondition() [3/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 35 of file Guards.c.
References LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
GuardCondition() [4/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 50 of file Guards.c.
References LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
GuardCondition() [5/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 65 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [6/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 84 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [7/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 120 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [8/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 138 of file Guards.c.
References LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, m_weapon, and wpnDebugPrint().
GuardCondition() [9/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 157 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [10/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 177 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [11/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 194 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [12/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 213 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [13/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 234 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [14/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 251 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [15/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 270 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [16/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 288 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [17/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 308 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [18/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 325 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [19/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 343 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [20/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 364 of file Guards.c.
References LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, m_weapon, and wpnDebugPrint().
GuardCondition() [21/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 382 of file Guards.c.
References LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, m_weapon, and wpnDebugPrint().
GuardCondition() [22/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 401 of file Guards.c.
References LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, m_weapon, and wpnDebugPrint().
GuardCondition() [23/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 419 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [24/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 437 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [25/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 455 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [26/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 476 of file Guards.c.
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [27/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 506 of file Guards.c.
References LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
GuardCondition() [28/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 524 of file Guards.c.
References Error(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, m_weapon, magazinesHaveEqualSizes(), and wpnDebugPrint().
GuardCondition() [29/29]
override bool GuardCondition (WeaponEventBase e) inline private
Definition at line 548 of file Guards.c.
References WeaponEventBase::m_player.
GuardNot()
void GuardNot (WeaponGuardBase arg0 = NULL) inline private
Definition at line 33 of file Guards.c.
GuardOr()
void GuardOr (WeaponGuardBase arg0 = NULL, WeaponGuardBase arg1 = NULL) inline private
Definition at line 48 of file Guards.c.
WeaponGuardAnyChamberEmpty()
void WeaponGuardAnyChamberEmpty (Weapon_Base w = NULL, int muzzle_index = 0) inline private
Definition at line 211 of file Guards.c.
References m_weapon.
WeaponGuardAnyChamberFiredOut()
void WeaponGuardAnyChamberFiredOut (Weapon_Base w = NULL) inline private
Definition at line 341 of file Guards.c.
References m_weapon.
WeaponGuardCanAttachMag()
void WeaponGuardCanAttachMag (Weapon_Base w = NULL) inline private
Definition at line 362 of file Guards.c.
References m_weapon.
WeaponGuardCanDetachMag()
void WeaponGuardCanDetachMag (Weapon_Base w = NULL) inline private
Definition at line 399 of file Guards.c.
References m_weapon.
WeaponGuardCanSwapMag()
void WeaponGuardCanSwapMag (Weapon_Base w = NULL) inline private
Definition at line 380 of file Guards.c.
References m_weapon.
WeaponGuardChamberEmpty()
void WeaponGuardChamberEmpty (Weapon_Base w = NULL, int muzzle_index = 0) inline private
Definition at line 175 of file Guards.c.
References m_weapon.
WeaponGuardChamberFiredOut()
void WeaponGuardChamberFiredOut (Weapon_Base w = NULL, int muzzle_index = 0) inline private
Definition at line 306 of file Guards.c.
References m_weapon.
WeaponGuardChamberFull()
void WeaponGuardChamberFull (Weapon_Base w = NULL, int muzzle_index = 0) inline private
Definition at line 232 of file Guards.c.
References m_weapon.
WeaponGuardChamberHasRoomForMoreThanOne()
void WeaponGuardChamberHasRoomForMoreThanOne (Weapon_Base w = NULL) inline private
Definition at line 417 of file Guards.c.
References m_weapon.
WeaponGuardChamberHasRoomForOne()
void WeaponGuardChamberHasRoomForOne (Weapon_Base w = NULL) inline private
Definition at line 435 of file Guards.c.
References m_weapon.
WeaponGuardChamberMultiHasRoomBulltet()
void WeaponGuardChamberMultiHasRoomBulltet (Weapon_Base w = NULL) inline private
Definition at line 453 of file Guards.c.
References m_weapon.
WeaponGuardChamberMultiHasRoomBulltetIgnoreLast()
void WeaponGuardChamberMultiHasRoomBulltetIgnoreLast (Weapon_Base w = NULL) inline private
Definition at line 474 of file Guards.c.
References m_weapon.
WeaponGuardCurrentChamberEmpty()
void WeaponGuardCurrentChamberEmpty (Weapon_Base w = NULL) inline private
Definition at line 192 of file Guards.c.
References m_weapon.
WeaponGuardCurrentChamberFiredOut()
void WeaponGuardCurrentChamberFiredOut (Weapon_Base w = NULL) inline private
Definition at line 323 of file Guards.c.
References m_weapon.
WeaponGuardCurrentChamberFull()
void WeaponGuardCurrentChamberFull (Weapon_Base w = NULL) inline private
Definition at line 249 of file Guards.c.
References m_weapon.
WeaponGuardHasAmmoInEvent()
void WeaponGuardHasAmmoInEvent (Weapon_Base w = NULL) inline private
Definition at line 136 of file Guards.c.
References m_weapon.
WeaponGuardHasAmmoInLoopedState()
void WeaponGuardHasAmmoInLoopedState (WeaponChambering_Base state) inline private
Definition at line 504 of file Guards.c.
WeaponGuardHasAmmoInnerMagazine()
void WeaponGuardHasAmmoInnerMagazine (Weapon_Base w = NULL) inline private
Definition at line 118 of file Guards.c.
References m_weapon.
WeaponGuardHasMag()
void WeaponGuardHasMag (Weapon_Base w = NULL) inline private
Definition at line 155 of file Guards.c.
References m_weapon.
WeaponGuardInnerMagazineFull()
void WeaponGuardInnerMagazineFull (Weapon_Base w = NULL) inline private
Definition at line 268 of file Guards.c.
References m_weapon.
WeaponGuardInnerMagazineFullShareChamber()
void WeaponGuardInnerMagazineFullShareChamber (Weapon_Base w = NULL) inline private
Definition at line 286 of file Guards.c.
References m_weapon.
WeaponGuardIsDestroyed()
void WeaponGuardIsDestroyed (Weapon_Base w = NULL) inline private
Definition at line 82 of file Guards.c.
References m_weapon.
WeaponGuardJammed()
void WeaponGuardJammed (Weapon_Base w = NULL) inline private
Definition at line 63 of file Guards.c.
References m_weapon.
WeaponGuardMagazinesHaveEqualSizes()
void WeaponGuardMagazinesHaveEqualSizes (Weapon_Base w = NULL) inline private
Definition at line 522 of file Guards.c.
References m_weapon.
Field Documentation
m_arg0
ref WeaponGuardBase m_arg0 private
Definition at line 16 of file Guards.c.
m_arg1
ref WeaponGuardBase m_arg1 private
Definition at line 17 of file Guards.c.
m_muzzle
protected int m_muzzle private
Definition at line 174 of file Guards.c.
m_state
WeaponChambering_Base m_state private
Definition at line 503 of file Guards.c.
m_weapon
protected Weapon_Base m_weapon private
Definition at line 62 of file Guards.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Firearms/FSM/Guards.c