DayZ Scripts: HitInfo Class Reference
HitInfo Class Reference
Private Member Functions
proto native float GetSurfaceNoiseMultiplier ()
proto native string GetAmmoType ()
proto native vector GetPosition ()
proto native vector GetSurfaceNormal ()
proto native string GetSurface ()
proto native bool IsWater ()
Member Function Documentation
GetAmmoType()
proto native string GetAmmoType () private
Referenced by CGame::ExplosionEffectsEx().
GetPosition()
proto native vector GetPosition () private
Referenced by CGame::ExplosionEffectsEx().
GetSurface()
proto native string GetSurface () private
Referenced by CGame::ExplosionEffectsEx().
GetSurfaceNoiseMultiplier()
proto native float GetSurfaceNoiseMultiplier () private
Referenced by CGame::ExplosionEffectsEx().
GetSurfaceNormal()
proto native vector GetSurfaceNormal () private
Referenced by CGame::ExplosionEffectsEx().
IsWater()
proto native bool IsWater () private
Referenced by CGame::ExplosionEffectsEx().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/HitInfo.c