DayZ Scripts: InventoryItemType Class Reference
InventoryItemType Class Reference
Private Member Functions
private void InventoryItemType ()
private void ~InventoryItemType ()
void LoadSoundEvents ()
AnimSoundEvent GetSoundEvent (int event_id)
proto native owned string GetName ()
Private Attributes
ref array< ref AnimSoundEvent > m_animSoundEvents
Constructor & Destructor Documentation
InventoryItemType()
private void InventoryItemType () inline private
References LoadSoundEvents().
~InventoryItemType()
private void ~InventoryItemType () private
Member Function Documentation
GetName()
proto native owned string GetName () private
Referenced by LoadSoundEvents().
GetSoundEvent()
AnimSoundEvent GetSoundEvent (int event_id) inline private
References m_animSoundEvents.
Referenced by DayZPlayer::ProcessWeaponEvent().
LoadSoundEvents()
void LoadSoundEvents () inline private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), GetName(), and m_animSoundEvents.
Referenced by InventoryItemType().
Field Documentation
m_animSoundEvents
ref array<ref AnimSoundEvent> m_animSoundEvents private
Referenced by GetSoundEvent(), and LoadSoundEvents().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/InventoryItemType.c