DayZ Scripts: AnimationTimer Class Reference
AnimationTimer Class Reference
Tools
AnimationTimer class. This timer is for animating float value.
usage:
Private Member Functions
void AnimationTimer (int category=CALL_CATEGORY_SYSTEM)
void ~AnimationTimer ()
void Run (float targetVal, Managed obj, string updateFunc, string finishedFunc, float startingVal=0, bool loop=false, float speed=1.0, Param params=null, int category=CALL_CATEGORY_SYSTEM)
float GetValue ()
Returns actual animated value.
override bool IsRunning ()
override void Tick (float timeslice)
Ticks the timer, is called by timer subsystem.
Private Attributes
private bool m_Active
private float m_TargetValue
private float m_TargetValueOriginal
private float m_Value
protected Managed m_TargetObject
protected string m_UpdateFunction
protected string m_FinishedFunction
protected ref Param m_Params
Detailed Description
AnimationTimer class. This timer is for animating float value.
usage:
class MyObject
{
   ref AnimationTimer myAnim;
   void MyObject()
   {
    myAnim = new AnimationTimer();
    myAnim.Run(60, this, "Refresh");
   }
   void Refresh()
   {
    Print(myAnim.GetValue());
   }
};
Definition at line 639 of file tools.c.
Constructor & Destructor Documentation
AnimationTimer()
void AnimationTimer (int category = CALL_CATEGORY_SYSTEM) inline private
Definition at line 650 of file tools.c.
References OnInit().
~AnimationTimer()
void ~AnimationTimer () inline private
Definition at line 655 of file tools.c.
References SetRunning().
Member Function Documentation
GetValue()
float GetValue () inline private
Returns actual animated value.
Definition at line 678 of file tools.c.
References m_Value.
Referenced by Land_Underground_EntranceBase::OnUpdateServer(), OnUpdateTimerIn(), and OnUpdateTimerOut().
IsRunning()
override bool IsRunning () inline private
Definition at line 682 of file tools.c.
References m_Active.
Run()
void Run (float targetVal, Managed obj, string updateFunc, string finishedFunc, float startingVal = 0, bool loop = false, float speed = 1.0, Param params = null, int category = CALL_CATEGORY_SYSTEM) inline private
Definition at line 660 of file tools.c.
References m_Active, m_FinishedFunction, m_loop, m_Params, m_TargetObject, m_TargetValue, m_TargetValueOriginal, m_time, m_UpdateFunction, m_Value, and SetRunning().
Referenced by Land_Underground_Stairs_Exit::OnDoorStateChangedServer(), and OnUndergroundPresenceUpdate().
Tick()
override void Tick (float timeslice) inline private
Ticks the timer, is called by timer subsystem.
Definition at line 689 of file tools.c.
References Math::AbsFloat(), ScriptModule::CallFunction(), CGame::GameScript, GetGame(), m_Active, m_FinishedFunction, m_loop, m_Params, m_TargetObject, m_TargetValue, m_TargetValueOriginal, m_time, m_UpdateFunction, and m_Value.
Field Documentation
m_Active
private bool m_Active private
Definition at line 641 of file tools.c.
Referenced by IsRunning(), Run(), and Tick().
m_FinishedFunction
protected string m_FinishedFunction private
Definition at line 647 of file tools.c.
Referenced by Run(), and Tick().
m_Params
protected ref Param m_Params private
Definition at line 648 of file tools.c.
Referenced by Run(), and Tick().
m_TargetObject
protected Managed m_TargetObject private
Definition at line 645 of file tools.c.
Referenced by Run(), and Tick().
m_TargetValue
private float m_TargetValue private
Definition at line 642 of file tools.c.
Referenced by Run(), and Tick().
m_TargetValueOriginal
private float m_TargetValueOriginal private
Definition at line 643 of file tools.c.
Referenced by Run(), and Tick().
m_UpdateFunction
protected string m_UpdateFunction private
Definition at line 646 of file tools.c.
Referenced by Run(), and Tick().
m_Value
private float m_Value private
Definition at line 644 of file tools.c.
Referenced by GetValue(), Run(), and Tick().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/tools.c