DayZ Scripts: ActionGetInTransport Class Reference
ActionGetInTransport Class Reference
Private Member Functions
void ActionGetInTransport ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void Start (ActionData action_data)
override void OnStartServer (ActionData action_data)
override bool CanBeUsedInRestrain ()
override void OnUpdate (ActionData action_data)
override int GetActionCategory ()
override void OnEndClient (ActionData action_data)
override void OnEndServer (ActionData action_data)
Constructor & Destructor Documentation
ActionGetInTransport()
void ActionGetInTransport () inline private
References m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Class::CastTo(), and Transport::IsAreaAtDoorFree().
CanBeUsedInRestrain()
override bool CanBeUsedInRestrain () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References m_ConditionItem, and m_ConditionTarget.
GetActionCategory()
override int GetActionCategory () inline private
References AC_INTERACT.
GetInputType()
override GetInputType () inline private
HasProgress()
override bool HasProgress () inline private
OnEndClient()
override void OnEndClient (ActionData action_data) inline private
References ActionData::m_Player.
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
References ActionData::m_Player, and ActionData::m_Target.
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
References ActionData::m_Target.
OnUpdate()
override void OnUpdate (ActionData action_data) inline private
References End(), ActionData::m_Player, ActionData::m_State, and UA_START.
Start()
override void Start (ActionData action_data) inline private
References GetDayZGame(), ActionData::m_Player, ActionData::m_Target, and HumanCommandVehicle::SetVehicleType().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionGetInTransport.c