DayZ Scripts: DayZPlayerCameraBase Class Reference
DayZPlayerCameraBase Class Reference
this is main camera class
Private Member Functions
void DayZPlayerCamera1stPerson (DayZPlayer pPlayer, HumanInputController pInput)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override vector GetBaseAngles ()
override vector GetAdditiveAngles ()
override string GetCameraName ()
void DayZPlayerCamera3rdPerson (DayZPlayer pPlayer, HumanInputController pInput)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override vector GetBaseAngles ()
override vector GetAdditiveAngles ()
override string GetCameraName ()
void DayZPlayerCameraIronsights (DayZPlayer pPlayer, HumanInputController pInput)
void SetupSightEntities ()
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
EntityAI GetCurrentSightEntity ()
bool GetCurrentSightInfo (out vector camPos, out vector camDir)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override vector GetBaseAngles ()
override vector GetAdditiveAngles ()
void AdjustCameraParameters (float pDt, inout DayZPlayerCameraResult pOutResult)
float HoldBreathFOVEffect (float pDt)
override void SetCameraPP (bool state, DayZPlayerCamera launchedFrom)
override string GetCameraName ()
override void SetCameraPPDelay (DayZPlayerCamera pPrevCamera)
void UpdateBatteryOptics (EntityAI entity)
Private Attributes
protected int m_iBoneIndex = -1
main bone
protected vector m_OffsetLS
position offset
protected float m_fUpDownAngle
up down angle in rad
protected float m_fUpDownAngleAdd
up down angle in rad
protected float m_fLeftRightAngle
left right angle in rad (in freelook only)
protected float m_fLeftRightAngleAdd
left right angle in rad (in freelook only)
protected vector m_CameraOffsetMS
model space offset
protected vector m_CameraOffsetLS
local space offset
protected float m_fDistance
distance from start
protected float m_fShoulderWidth
shoulder camera widths
protected bool m_bShoulderInLS
true - shoulder is in local space
protected float m_fRoll
camera roll (deprecated)
protected float m_fLeanDistance
shift on leaning
protected float m_fCameraLRShoulder
shoulder offsets
protected float m_fCameraLRShoulderVel [1]
protected float m_fPredictCollisionRadius
collision prediction
ref HumanMovementState m_MovementState = new HumanMovementState()
movement state
protected bool m_isEntering = false
protected bool m_opticsHasWeaponOverride = false
protected ref array< float > temp_array
protected PPERequester_CameraADS m_RequesterADS
float m_velocityYaw [1]
camera dynamics
float m_velocityPitch [1]
float m_dynamicsStrength
float m_dynamicsSmoothTime
vector m_SightMisalignmentModifier
float m_movementTimeAcc
float m_movementAmplitudeX
float m_movementAmplitudeY
float m_movementFrequencyX
float m_movementFrequencyY
protected float m_fShootFromCamera = 0.0
settings
protected vector m_OpticsCamPos
protected vector m_OpticsCamDir
Static Private Attributes
static const float CONST_UD_MIN = -85.0
down limit
static const float CONST_UD_MAX = 85.0
up limit
static const float CONST_LR_MIN = -160.0
down limit
static const float CONST_LR_MAX = 160.0
up limit
static const float CONST_UD_MIN_BACK = -25.0
down limit on back
Detailed Description
this is main camera class
Definition at line 4 of file DayZPlayerCamera1stPerson.c.
Member Function Documentation
AdjustCameraParameters()
void AdjustCameraParameters (float pDt, inout DayZPlayerCameraResult pOutResult) inline private
Definition at line 220 of file DayZPlayerCameraIronsights.c.
References HoldBreathFOVEffect(), m_fShootFromCamera, and m_iBoneIndex.
Referenced by OnUpdate().
DayZPlayerCamera1stPerson()
void DayZPlayerCamera1stPerson (DayZPlayer pPlayer, HumanInputController pInput) inline private
Definition at line 13 of file DayZPlayerCamera1stPerson.c.
References m_iBoneIndex, m_OffsetLS, and Print().
DayZPlayerCamera3rdPerson()
void DayZPlayerCamera3rdPerson (DayZPlayer pPlayer, HumanInputController pInput) inline private
Definition at line 12 of file DayZPlayerCamera3rdPerson.c.
References HumanInputController::Camera3rdIsRightShoulder(), m_CurrentCameraRoll, m_fCameraLRShoulder, m_fCameraLRShoulderVel, m_fLeanDistance, m_fPredictCollisionRadius, and m_WeaponSwayModifier.
DayZPlayerCameraIronsights()
void DayZPlayerCameraIronsights (DayZPlayer pPlayer, HumanInputController pInput) inline private
Definition at line 32 of file DayZPlayerCameraIronsights.c.
References Class::CastTo(), GetCurrentSightInfo(), Init(), m_iBoneIndex, m_WeaponSwayModifier, Print(), and SetupSightEntities().
GetAdditiveAngles() [1/3]
override vector GetAdditiveAngles () inline private
Definition at line 76 of file DayZPlayerCamera1stPerson.c.
References m_fLeftRightAngleAdd, and m_fUpDownAngleAdd.
GetAdditiveAngles() [2/3]
override vector GetAdditiveAngles () inline private
Definition at line 120 of file DayZPlayerCamera3rdPerson.c.
References m_fLeftRightAngleAdd, and m_fUpDownAngleAdd.
GetAdditiveAngles() [3/3]
override vector GetAdditiveAngles () inline private
Definition at line 211 of file DayZPlayerCameraIronsights.c.
References m_fLeftRightAngleAdd, and m_fUpDownAngleAdd.
GetBaseAngles() [1/3]
override vector GetBaseAngles () inline private
Definition at line 67 of file DayZPlayerCamera1stPerson.c.
References m_fLeftRightAngle, and m_fUpDownAngle.
GetBaseAngles() [2/3]
override vector GetBaseAngles () inline private
Definition at line 111 of file DayZPlayerCamera3rdPerson.c.
References m_fLeftRightAngle, and m_fUpDownAngle.
GetBaseAngles() [3/3]
override vector GetBaseAngles () inline private
Definition at line 202 of file DayZPlayerCameraIronsights.c.
References m_fLeftRightAngle, and m_fUpDownAngle.
GetCameraName() [1/3]
override string GetCameraName () inline private
Definition at line 85 of file DayZPlayerCamera1stPerson.c.
GetCameraName() [2/3]
override string GetCameraName () inline private
Definition at line 129 of file DayZPlayerCamera3rdPerson.c.
GetCameraName() [3/3]
override string GetCameraName () inline private
Definition at line 315 of file DayZPlayerCameraIronsights.c.
GetCurrentSightEntity()
EntityAI GetCurrentSightEntity () inline private
Definition at line 103 of file DayZPlayerCameraIronsights.c.
References m_opticsUsed, and m_weaponUsed.
Referenced by GetCurrentSightInfo(), and OnUpdate().
GetCurrentSightInfo()
bool GetCurrentSightInfo (out vector camPos, out vector camDir) inline private
Definition at line 111 of file DayZPlayerCameraIronsights.c.
References ErrorEx, GetCurrentSightEntity(), m_opticsUsed, and m_weaponUsed.
Referenced by DayZPlayerCameraIronsights().
HoldBreathFOVEffect()
float HoldBreathFOVEffect (float pDt) inline private
Definition at line 236 of file DayZPlayerCameraIronsights.c.
References GameConstants::DZPLAYER_CAMERA_FOV_EYEZOOM, GameConstants::DZPLAYER_CAMERA_FOV_IRONSIGHTS, m_fFovAbsolute, m_fFovAbsVel, m_pPlayer, and Math::SmoothCD().
Referenced by AdjustCameraParameters().
OnActivate() [1/3]
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult) inline private
Definition at line 26 of file DayZPlayerCamera1stPerson.c.
References m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fUpDownAngle, and m_fUpDownAngleAdd.
OnActivate() [2/3]
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult) inline private
Definition at line 32 of file DayZPlayerCamera3rdPerson.c.
References m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fUpDownAngle, and m_fUpDownAngleAdd.
OnActivate() [3/3]
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult) inline private
Definition at line 87 of file DayZPlayerCameraIronsights.c.
References m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fUpDownAngle, and m_fUpDownAngleAdd.
OnUpdate() [1/3]
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult) inline private
update angles from input
Definition at line 43 of file DayZPlayerCamera1stPerson.c.
References CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, CONST_UD_MIN, GetCurrentOrientation(), InitCameraOnPlayer(), m_CurrentCameraPitch, m_CurrentCameraYaw, m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fUpDownAngle, m_fUpDownAngleAdd, m_iBoneIndex, m_OffsetLS, m_pPlayer, ProcessCameraShake(), StdFovUpdate(), UpdateCameraNV(), UpdateLRAngleUnlocked(), UpdateUDAngleUnlocked(), and Math3D::YawPitchRollMatrix().
OnUpdate() [2/3]
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult) inline private
update angles from input
base bone pos
apply shoulder dist
store distance
Definition at line 49 of file DayZPlayerCamera3rdPerson.c.
References HumanInputController::Camera3rdIsRightShoulder(), CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, CONST_UD_MIN, GetCurrentOrientation(), InitCameraOnPlayer(), m_bShoulderInLS, m_CameraOffsetLS, m_CameraOffsetMS, m_CurrentCameraPitch, m_CurrentCameraYaw, m_fCameraLRShoulder, m_fCameraLRShoulderVel, m_fDistance, m_fLeanDistance, HumanMovementState::m_fLeaning, m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fPredictCollisionRadius, m_fShoulderWidth, m_fUpDownAngle, m_fUpDownAngleAdd, m_iBoneIndex, m_MovementState, m_pInput, m_pPlayer, ProcessCameraShake(), Math::SmoothCD(), StdFovUpdate(), UpdateCameraNV(), UpdateLRAngleUnlocked(), UpdateUDAngleUnlocked(), and Math3D::YawPitchRollMatrix().
OnUpdate() [3/3]
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult) inline private
update angles from input
Definition at line 136 of file DayZPlayerCameraIronsights.c.
References AdjustCameraParameters(), CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, CONST_UD_MIN, CONST_UD_MIN_BACK, HumanInputController::GetAimDelta(), HumanCommandMove::GetCurrentMovementSpeed(), GetCurrentSightEntity(), GetGame(), GetPlayer(), HumanItemAccessor(), m_CameraShake, m_CurrentCameraPitch, m_CurrentCameraYaw, m_fLeftRightAngle, m_fLeftRightAngleAdd, m_fUpDownAngle, m_fUpDownAngleAdd, m_iBoneIndex, m_pInput, m_pPlayer, Math3D::MatrixMultiply4(), Math::PI2, Math::RAD2DEG, Math::Sin(), Math::SmoothCD(), CameraShake::Update(), UpdateBatteryOptics(), UpdateCameraNV(), UpdateLRAngleUnlocked(), UpdateUDAngleUnlocked(), x, y, Math3D::YawPitchRollMatrix(), and vector::Zero.
SetCameraPP()
override void SetCameraPP (bool state, DayZPlayerCamera launchedFrom) inline private
Definition at line 256 of file DayZPlayerCameraIronsights.c.
References GetCameraNVType(), IsCameraNV(), m_opticsUsed, m_pPlayer, m_weaponUsed, and SetNVPostprocess().
Referenced by OnActivate(), and UpdateCameraNV().
SetCameraPPDelay()
override void SetCameraPPDelay (DayZPlayerCamera pPrevCamera) inline private
Definition at line 320 of file DayZPlayerCameraIronsights.c.
References m_CameraPPDelay, DayZPlayerCameras::TIME_CAMERACHANGE_01, and DayZPlayerCameras::TIME_CAMERACHANGE_02.
Referenced by OnActivate().
SetupSightEntities()
void SetupSightEntities () inline private
Definition at line 62 of file DayZPlayerCameraIronsights.c.
References m_opticsUsed, m_pPlayer, and m_weaponUsed.
Referenced by DayZPlayerCameraIronsights().
UpdateBatteryOptics()
void UpdateBatteryOptics (EntityAI entity) inline private
Definition at line 338 of file DayZPlayerCameraIronsights.c.
Referenced by OnUpdate().
Field Documentation
CONST_LR_MAX
static const float CONST_LR_MAX = 160.0 static private
up limit
Definition at line 10 of file DayZPlayerCamera1stPerson.c.
CONST_LR_MIN
static const float CONST_LR_MIN = -160.0 static private
down limit
Definition at line 9 of file DayZPlayerCamera1stPerson.c.
CONST_UD_MAX
static const float CONST_UD_MAX = 85.0 static private
up limit
Definition at line 7 of file DayZPlayerCamera1stPerson.c.
CONST_UD_MIN
static const float CONST_UD_MIN = -85.0 static private
down limit
Definition at line 6 of file DayZPlayerCamera1stPerson.c.
Referenced by OnUpdate().
CONST_UD_MIN_BACK
const float CONST_UD_MIN_BACK = -25.0 static private
down limit on back
Definition at line 7 of file DayZPlayerCameraIronsights.c.
Referenced by OnUpdate().
m_bShoulderInLS
protected bool m_bShoulderInLS private
true - shoulder is in local space
Definition at line 140 of file DayZPlayerCamera3rdPerson.c.
m_CameraOffsetLS
protected vector m_CameraOffsetLS private
local space offset
Definition at line 137 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate().
m_CameraOffsetMS
protected vector m_CameraOffsetMS private
model space offset
Definition at line 136 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate(), and OnUpdate().
m_dynamicsSmoothTime
float m_dynamicsSmoothTime private
Definition at line 22 of file DayZPlayerCameraIronsights.c.
m_dynamicsStrength
float m_dynamicsStrength private
Definition at line 21 of file DayZPlayerCameraIronsights.c.
m_fCameraLRShoulder
protected float m_fCameraLRShoulder private
shoulder offsets
Definition at line 152 of file DayZPlayerCamera3rdPerson.c.
m_fCameraLRShoulderVel
protected float m_fCameraLRShoulderVel[1] private
Definition at line 153 of file DayZPlayerCamera3rdPerson.c.
m_fDistance
protected float m_fDistance private
distance from start
Definition at line 138 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate(), and OnUpdate().
m_fLeanDistance
protected float m_fLeanDistance private
shift on leaning
Definition at line 142 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate().
m_fLeftRightAngle
protected float m_fLeftRightAngle private
left right angle in rad (in freelook only)
Definition at line 95 of file DayZPlayerCamera1stPerson.c.
Referenced by GetBaseAngles(), and GetBaseAngles().
m_fLeftRightAngleAdd
protected float m_fLeftRightAngleAdd private
left right angle in rad (in freelook only)
Definition at line 96 of file DayZPlayerCamera1stPerson.c.
Referenced by GetAdditiveAngles(), and GetAdditiveAngles().
m_fPredictCollisionRadius
protected float m_fPredictCollisionRadius private
collision prediction
Definition at line 156 of file DayZPlayerCamera3rdPerson.c.
Referenced by OnUpdate().
m_fRoll
protected float m_fRoll private
camera roll (deprecated)
Definition at line 141 of file DayZPlayerCamera3rdPerson.c.
m_fShootFromCamera
protected float m_fShootFromCamera = 0.0 private
settings
Definition at line 346 of file DayZPlayerCameraIronsights.c.
Referenced by AdjustCameraParameters().
m_fShoulderWidth
protected float m_fShoulderWidth private
shoulder camera widths
Definition at line 139 of file DayZPlayerCamera3rdPerson.c.
m_fUpDownAngle
protected float m_fUpDownAngle private
up down angle in rad
runtime values
up down angle in rad
Definition at line 93 of file DayZPlayerCamera1stPerson.c.
Referenced by GetBaseAngles(), and GetBaseAngles().
m_fUpDownAngleAdd
protected float m_fUpDownAngleAdd private
up down angle in rad
Definition at line 94 of file DayZPlayerCamera1stPerson.c.
Referenced by GetAdditiveAngles(), and GetAdditiveAngles().
m_iBoneIndex
protected int m_iBoneIndex = -1 private
main bone
runtime values
runtime config
main bone
right hand dummy bone index
Definition at line 90 of file DayZPlayerCamera1stPerson.c.
Referenced by AdjustCameraParameters().
m_isEntering
protected bool m_isEntering = false private
Definition at line 12 of file DayZPlayerCameraIronsights.c.
m_movementAmplitudeX
float m_movementAmplitudeX private
Definition at line 26 of file DayZPlayerCameraIronsights.c.
m_movementAmplitudeY
float m_movementAmplitudeY private
Definition at line 27 of file DayZPlayerCameraIronsights.c.
m_movementFrequencyX
float m_movementFrequencyX private
Definition at line 28 of file DayZPlayerCameraIronsights.c.
m_movementFrequencyY
float m_movementFrequencyY private
Definition at line 29 of file DayZPlayerCameraIronsights.c.
m_MovementState
ref HumanMovementState m_MovementState = new HumanMovementState() private
movement state
Definition at line 159 of file DayZPlayerCamera3rdPerson.c.
m_movementTimeAcc
float m_movementTimeAcc private
Definition at line 25 of file DayZPlayerCameraIronsights.c.
m_OffsetLS
protected vector m_OffsetLS private
position offset
Definition at line 91 of file DayZPlayerCamera1stPerson.c.
m_OpticsCamDir
protected vector m_OpticsCamDir private
Definition at line 351 of file DayZPlayerCameraIronsights.c.
m_OpticsCamPos
protected vector m_OpticsCamPos private
Definition at line 350 of file DayZPlayerCameraIronsights.c.
m_opticsHasWeaponOverride
protected bool m_opticsHasWeaponOverride = false private
Definition at line 13 of file DayZPlayerCameraIronsights.c.
m_RequesterADS
protected PPERequester_CameraADS m_RequesterADS private
Definition at line 16 of file DayZPlayerCameraIronsights.c.
m_SightMisalignmentModifier
vector m_SightMisalignmentModifier private
Definition at line 23 of file DayZPlayerCameraIronsights.c.
m_velocityPitch
float m_velocityPitch[1] private
Definition at line 20 of file DayZPlayerCameraIronsights.c.
m_velocityYaw
float m_velocityYaw[1] private
camera dynamics
Definition at line 19 of file DayZPlayerCameraIronsights.c.
temp_array
protected ref array<float> temp_array private
Definition at line 14 of file DayZPlayerCameraIronsights.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCamera1stPerson.c
P:/scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCamera3rdPerson.c
P:/scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCameraIronsights.c