DayZ Scripts: DayZPlayerUtils Class Reference
DayZPlayerUtils Class Reference
Private Member Functions
private void DayZPlayerUtils ()
cannot be instantiated
Static Private Member Functions
static proto native void EnableDebugDraw (bool pEnable)
enables debug draw in functions
static proto native void DrawDebugText (string text, vector pos, float size)
static proto native void DrawStartFrame ()
clear info - new draw starts
static proto native void DrawDebugBox (vector pos, float size, int color)
draws debug box (color=red)
static proto native bool DebugOverrideAnimationTranslation (string pAnimName, vector pTranslation)
overrides total animation translation
static proto native bool DebugOverrideAnimationRotation (string pAnimName, vector pRotation)
overrides total animation rotation
static proto native bool DebugOverrideAnimationSpeed (string pAnimName, float pSpeed)
overrides total animation speed
static proto float LinearRangeClamp (float pValueX, float pValueY, float pLimits[])
static proto native void PhysicsGetEntitiesInBox (vector min, vector max, out array< EntityAI > entList)
returns entities overlapping/touching in AABB box -
static proto native void SceneGetEntitiesInBox (vector min, vector max, out array< EntityAI > entList)
returns entities overlapping/touching in AABB box -
static proto native void GetEntitiesInCone (vector pos, vector dir, float angle, float dist, float minHeigh, float maxHeight, out array< Object > entList)
returns entities in height-extended 2D cone
static Object GetMeleeTarget (vector pos, vector dir, float angle, float dist, float minHeight, float maxHeight, EntityAI pToIgnore, array< typename > targetableObjects, out array< Object > allTargets=NULL)
returns fight target
static proto native bool PlayerCanChangeStance (DayZPlayer pPlayer, int pTargetStance, bool forceCheck=false)
static proto native bool FindMagazinesForAmmo (DayZPlayer player, string ammoTypeName, out array< Magazine > mags)
inventory DayZPlayer utils
static Magazine SelectStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, Magazine exclude_mag, float damage, string magTypeName)
static bool HandleDropMagazine (DayZPlayer player, Magazine mag)
static bool HandleDropCartridge (DayZPlayer player, float damage, string cartTypeName, string magTypeName)
static bool HandleStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, float damage, string cartTypeName, string magTypeName, bool CanDrop=true)
static proto native bool InitComponentCollisions (Human player, array< ref ComponentCollisionBox > boxes, array< ref ComponentCollisionCapsule > capsules)
initializes table of component collisions
static proto native bool IsComponentCollisionInitialized ()
static proto native void ClearComponentCollisions ()
static proto native vector GetMemoryPointPositionBoneRelative (DayZPlayer pPlayer, int pBoneIndex, int pPointIndex)
static void InitPlayerComponentCollisions (Human player)
static int ConvertStanceMaskToStanceIdx (int stanceMask)
static EWaterLevels CheckWaterLevel (DayZPlayer pPlayer, out vector waterLevel)
static private void InitCachedEntList ()
Static Private Attributes
static private ref array< Object > m_CachedEntList
Detailed Description
Definition at line 4 of file DayZPlayerUtils.c.
Constructor & Destructor Documentation
DayZPlayerUtils()
private void DayZPlayerUtils () inline private
cannot be instantiated
Definition at line 450 of file DayZPlayerUtils.c.
Member Function Documentation
CheckWaterLevel()
static EWaterLevels CheckWaterLevel (DayZPlayer pPlayer, out vector waterLevel) inline static private
if total water depth >= 1.5m && character is 1.5m in water
Definition at line 414 of file DayZPlayerUtils.c.
References HumanCommandSwim(), SHumanCommandSwimSettings::m_fToCrouchLevel, SHumanCommandSwimSettings::m_fToErectLevel, and SHumanCommandSwimSettings::m_fWaterLevelIn.
Referenced by DayZPlayerImplementSwimming::CheckSwimmingStart().
ClearComponentCollisions()
ClearComponentCollisions () static private
ConvertStanceMaskToStanceIdx()
static int ConvertStanceMaskToStanceIdx (int stanceMask) inline static private
Definition at line 388 of file DayZPlayerUtils.c.
Referenced by Can(), and EmoteBase::EmoteFBStanceCheck().
DebugOverrideAnimationRotation()
static proto native bool DebugOverrideAnimationRotation (string pAnimName, vector pRotation) static private
overrides total animation rotation
DebugOverrideAnimationSpeed()
static proto native bool DebugOverrideAnimationSpeed (string pAnimName, float pSpeed) static private
overrides total animation speed
DebugOverrideAnimationTranslation()
static proto native bool DebugOverrideAnimationTranslation (string pAnimName, vector pTranslation) static private
overrides total animation translation
DrawDebugBox()
static proto native void DrawDebugBox (vector pos, float size, int color) static private
draws debug box (color=red)
DrawDebugText()
static proto native void DrawDebugText (string text, vector pos, float size) static private
DrawStartFrame()
static proto native void DrawStartFrame () static private
clear info - new draw starts
EnableDebugDraw()
static proto native void EnableDebugDraw (bool pEnable) static private
enables debug draw in functions
FindMagazinesForAmmo()
FindMagazinesForAmmo (DayZPlayer player, string ammoTypeName, out array< Magazine > mags) static private
inventory DayZPlayer utils
searches inventory for all magazines that can hold specified ammo type
Parameters
[in] player DayZPlayer
[in] ammoTypeName type name of the cartridge
[out] mags array filled with suitable magazines
Returns
true if found at least one
Referenced by HandleStoreCartridge(), and SelectStoreCartridge().
GetEntitiesInCone()
GetEntitiesInCone (vector pos, vector dir, float angle, float dist, float minHeigh, float maxHeight, out array< Object > entList) static private
returns entities in height-extended 2D cone
Parameters
[in] angle angle in degrees
[in] minHeigh cone 3D-extension Y min
[in] maxHeight cone 3D-extension Y max
Note
the detection hits points/faces from ANY non-edit model geometry, including resolution LODs, regardless of animation hiding (scaling). That is why certain animated objects, like flags in folded state, get detected from significant distance away!
Referenced by GetMeleeTarget(), and VicinityItemManager::RefreshVicinityItems().
GetMeleeTarget()
static Object GetMeleeTarget (vector pos, vector dir, float angle, float dist, float minHeight, float maxHeight, EntityAI pToIgnore, array< typename > targetableObjects, out array< Object > allTargets = NULL) inline static private
returns fight target
Definition at line 81 of file DayZPlayerUtils.c.
References Class::CastTo(), Math::DEG2RAD, GetEntitiesInCone(), InitCachedEntList(), vector::LengthSq(), m_CachedEntList, Math::Tan(), and Vector().
Referenced by DayZInfected::ChaseAttackLogic(), and DayZInfected::FightAttackLogic().
GetMemoryPointPositionBoneRelative()
static proto native vector GetMemoryPointPositionBoneRelative (DayZPlayer pPlayer, int pBoneIndex, int pPointIndex) static private
HandleDropCartridge()
static bool HandleDropCartridge (DayZPlayer player, float damage, string cartTypeName, string magTypeName) inline static private
Definition at line 260 of file DayZPlayerUtils.c.
References Class::CastTo().
Referenced by HandleStoreCartridge(), and WeaponChambering_Base::OnAbort().
HandleDropMagazine()
static bool HandleDropMagazine (DayZPlayer player, Magazine mag) inline static private
Definition at line 241 of file DayZPlayerUtils.c.
References Error(), GameInventory::LocationSyncMoveEntity(), Math3D::MatrixIdentity4(), GameInventory::PrepareDropEntityPos(), and InventoryLocation::SetGround().
Referenced by WeaponStateBase::OnAbort(), OnAbort(), and WeaponStateBase::OnExit().
HandleStoreCartridge()
static bool HandleStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, float damage, string cartTypeName, string magTypeName, bool CanDrop = true) inline static private
Definition at line 279 of file DayZPlayerUtils.c.
References Class::CastTo(), ECE_IN_INVENTORY, FindMagazinesForAmmo(), GetGame(), HandleDropCartridge(), and RF_DEFAULT.
Referenced by ejectBulletAndStoreInMagazine(), and ActionEmptyMagazine::OnExecuteServer().
InitCachedEntList()
static private void InitCachedEntList () inline static private
Definition at line 453 of file DayZPlayerUtils.c.
References m_CachedEntList.
Referenced by GetMeleeTarget().
InitComponentCollisions()
InitComponentCollisions (Human player, array< ref ComponentCollisionBox > boxes, array< ref ComponentCollisionCapsule > capsules) static private
initializes table of component collisions
Parameters
[in] player DayZPlayer
[in] boxes array filled with box
See also
ComponentCollisionBox
Parameters
[in] capsules array filled with capsules
See also
ComponentCollisionCapsule
Returns
true if success
Referenced by InitPlayerComponentCollisions().
InitPlayerComponentCollisions()
static void InitPlayerComponentCollisions (Human player) inline static private
Definition at line 365 of file DayZPlayerUtils.c.
References ComponentCollisionBox(), Error(), InitComponentCollisions(), and IsComponentCollisionInitialized().
IsComponentCollisionInitialized()
IsComponentCollisionInitialized () static private
Returns
true if already initialized
Referenced by InitPlayerComponentCollisions().
LinearRangeClamp()
static proto float LinearRangeClamp (float pValueX, float pValueY, float pLimits[]) static private
pLimits in form Xvalue, Ymin, Ymax, Xvalue1, Ymin1, Ymax1, .... sample 0, 0, 5, 1, 2, 3, 2, 0, 1 for X <= 0 it clamps Y to Rangle (0,5)
for X == 0.5 it clamps Y to Rangle (1,4)
for X == 1 it clamps Y to Rangle (2,3)
for X == 1.5 it clamps Y to Rangle (1,2)
for X >= 2 it clamps Y to Rangle (0,1)
Referenced by DayZPlayerImplementAiming::ProcessAimFilters().
PhysicsGetEntitiesInBox()
static proto native void PhysicsGetEntitiesInBox (vector min, vector max, out array< EntityAI > entList) static private
returns entities overlapping/touching in AABB box -
PlayerCanChangeStance()
static proto native bool PlayerCanChangeStance (DayZPlayer pPlayer, int pTargetStance, bool forceCheck = false) static private
Referenced by ManBase::BrokenLegForceProne(), Can(), DayZPlayer::CanJump(), DayZPlayer::CanPickupHeavyItem(), EmoteBase::EmoteFBStanceCheck(), HandleFightLogic(), and DayZPlayerImplementSwimming::HandleSwimming().
SceneGetEntitiesInBox()
static proto native void SceneGetEntitiesInBox (vector min, vector max, out array< EntityAI > entList) static private
returns entities overlapping/touching in AABB box -
SelectStoreCartridge()
static Magazine SelectStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, Magazine exclude_mag, float damage, string magTypeName) inline static private
Definition at line 190 of file DayZPlayerUtils.c.
References Class::CastTo(), ECE_IN_INVENTORY, FindMagazinesForAmmo(), GetGame(), and RF_DEFAULT.
Referenced by WeaponStateBase::OnEntry().
Field Documentation
m_CachedEntList
private ref array<Object> m_CachedEntList static private
Definition at line 446 of file DayZPlayerUtils.c.
Referenced by GetMeleeTarget(), and InitCachedEntList().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/DayZPlayerUtils.c