DayZ Scripts: Container Class Reference
Container Class Reference
Private Member Functions
void CargoContainer (LayoutHolder parent, bool is_attachment=false)
void ~CargoContainer ()
int GetCargoIndex ()
void AddedToCargoEx (EntityAI item, bool refresh=true)
void AddedToCargo (EntityAI item)
void RemovedFromCargo (EntityAI item)
void MovedInCargo (EntityAI item)
void SetLock (EntityAI item)
void ReleaseLock (EntityAI item)
override void SetLayoutName ()
void SetEntity (EntityAI item, int cargo_index=0, bool immedUpdate=true)
EntityAI GetEntity ()
void UpdateHeaderText ()
void InitGridHeight ()
void UpdateSize ()
float GetIconSize ()
float GetSpaceSize ()
int GetCargoCapacity ()
int GetMaxCargoCapacity ()
Icon GetIcon (EntityAI item)
Icon GetIcon (int index)
Icon GetFocusedIcon ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
void UpdateSelection ()
void UpdateRowVisibility (int count)
override void Refresh ()
void RefreshImpl ()
override void UpdateInterval ()
Icon InitIconEx (Icon icon, EntityAI item, int pos_x, int pos_y, bool refresh=true)
Icon InitIcon (Icon icon, EntityAI item, int pos_x, int pos_y)
bool HasItem (EntityAI item)
override bool TransferItemToVicinity ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
override void SetLastFocus ()
override void Unfocus ()
override void UnfocusAll ()
override void SetNextActive ()
override void SetPreviousActive (bool force=false)
override void SetNextRightActive ()
override void SetNextLeftActive ()
override EntityAI GetFocusedItem ()
override void SetLastActive ()
override void SetActive (bool active)
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override bool IsEmpty ()
int GetRecipeCount (bool recipe_anywhere, ItemBase entity1, ItemBase entity2, PlayerBase player)
override bool CanEquip ()
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool TransferItem ()
override bool SplitItem ()
override bool EquipItem ()
override bool SelectItem ()
override bool Select ()
override bool Combine ()
void ShowFalseCargoHeader (bool show)
void SetAlternateFalseTextHeaderWidget (TextWidget w)
void ClosableContainer (LayoutHolder parent, int sort=-1)
override bool IsDisplayable ()
override void UpdateRadialIcon ()
void SetOpenState (bool state)
override Header GetHeader ()
override void Open ()
override void Close ()
override void SetLayoutName ()
override void OnShow ()
override LayoutHolder Get (int x)
override void Refresh ()
void CloseButtonOnMouseButtonDown ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
void MoveContainerUp (Widget cont)
void MoveContainerDown (Widget cont)
override void CheckHeaderDragability ()
Private Attributes
protected const int ROWS_NUMBER_XBOX = 5
protected CargoBase m_Cargo
protected int m_CargoIndex = -1
protected int m_FocusedItemPosition = -1
protected ref array< ref CargoContainerRow > m_Rows
protected ref array< ref Icon > m_Icons
protected ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedItemPositions
protected ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedLockPositions
protected float m_IconSize
protected float m_SpaceSize
protected bool m_IsAttachment
protected TextWidget m_FalseHeaderTextWidget
protected TextWidget m_AlternateFalseHeaderTextWidget
protected Widget m_CargoHeader
protected Widget m_CargoContainer
protected Widget m_ItemsContainer
protected ref SizeToChild m_Resizer1
protected ref SizeToChild m_Resizer2
protected ref Timer m_ResizeTimer
protected ref ClosableHeader m_ClosableHeader
protected bool m_LockCargo
Detailed Description
Definition at line 2 of file CargoContainer.c.
Constructor & Destructor Documentation
~CargoContainer()
void ~CargoContainer () inline private
Definition at line 50 of file CargoContainer.c.
References m_Entity, ScriptedWidgetEventHandler::Remove(), and SetLock().
Member Function Documentation
AddedToCargo()
void AddedToCargo (EntityAI item) inline private
Definition at line 108 of file CargoContainer.c.
References AddedToCargoEx().
AddedToCargoEx()
void AddedToCargoEx (EntityAI item, bool refresh = true) inline private
Definition at line 64 of file CargoContainer.c.
References InventoryLocation::GetCol(), CargoBase::GetItem(), CargoBase::GetItemCount(), InventoryLocation::GetRow(), InitIconEx(), Math::Min(), Refresh(), UpdateHeaderText(), x, and y.
Referenced by AddedToCargo(), and SetEntity().
CanCombine()
override bool CanCombine () inline private
Definition at line 781 of file CargoContainer.c.
References ItemManager::GetCombinationFlags(), GetFocusedIcon(), GetGame(), GetObject(), and GetPlayer().
Referenced by UpdateConsoleToolbar(), and UpdateInterval().
CanCombineAmmo()
override bool CanCombineAmmo () inline private
Definition at line 793 of file CargoContainer.c.
References ActionManagerClient::CanPerformActionFromInventory(), ActionManagerClient::CanSetActionFromInventory(), GetActionManager(), GetFocusedIcon(), GetGame(), GetObject(), and GetPlayer().
Referenced by UpdateConsoleToolbar(), and UpdateInterval().
CanEquip()
override bool CanEquip () inline private
Definition at line 767 of file CargoContainer.c.
References GetFocusedIcon(), GetGame(), GetObject(), and CGame::GetPlayer().
Referenced by UpdateConsoleToolbar().
CargoContainer()
void CargoContainer (LayoutHolder parent, bool is_attachment = false) inline private
Definition at line 28 of file CargoContainer.c.
References m_CargoContainer, and m_RootWidget.
Referenced by HandsContainer::AttachmentAdded(), HandsContainer::AttachmentRemoved(), HandsContainer::DestroyCargo(), HandsContainer::ShowAtt(), and HandsContainer::UnfocusGrid().
CheckHeaderDragability()
override void CheckHeaderDragability () inline private
Definition at line 181 of file ClosableContainer.c.
References CancelWidgetDragging(), GetDragWidget(), ScriptedWidgetEventHandler::GetMainWidget(), and m_Entity.
Referenced by LayoutHolder::UpdateInterval().
ClosableContainer()
void ClosableContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 6 of file ClosableContainer.c.
References m_RootWidget.
Close()
override void Close () inline private
Definition at line 79 of file ClosableContainer.c.
References ItemManager::GetInstance(), m_Entity, m_Parent, OnHide(), and ItemManager::SetDefaultOpenState().
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), AttachmentCategoriesRow::OnMouseButtonDown(), CollapsibleContainer::Toggle(), and LayoutHolder::Toggle().
CloseButtonOnMouseButtonDown()
void CloseButtonOnMouseButtonDown () inline private
Definition at line 116 of file ClosableContainer.c.
References ClosableContainer::Close().
Combine()
override bool Combine () inline private
Definition at line 937 of file CargoContainer.c.
References Icon::CombineItems(), GetFocusedIcon(), GetGame(), Icon::GetObject(), and CGame::GetPlayer().
EquipItem()
override bool EquipItem () inline private
Definition at line 843 of file CargoContainer.c.
References GetFocusedIcon(), GetGame(), GetObject(), and CGame::GetPlayer().
Referenced by UpdateInterval().
Get()
override LayoutHolder Get (int x) inline private
Definition at line 101 of file ClosableContainer.c.
References LayoutHolder::Count(), LayoutHolder::Get(), and x.
Referenced by ClosableContainer::AttachmentRemoved(), ZombieContainer::GetSlotsIcon(), ZombieContainer::GetWidgetSlot(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), VicinitySlotsContainer::MouseClick(), ClosableContainer::RecomputeContainers(), VicinitySlotsContainer::RecomputeNumberOfContainers(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinitySlotsContainer::~VicinitySlotsContainer().
GetCargoCapacity()
int GetCargoCapacity () inline private
Definition at line 372 of file CargoContainer.c.
References CargoBase::GetItemCount(), CargoBase::GetItemSize(), x, and y.
Referenced by UpdateHeaderText().
GetCargoIndex()
int GetCargoIndex () inline private
Definition at line 62 of file CargoContainer.c.
References m_CargoIndex.
GetEntity()
EntityAI GetEntity () inline private
Definition at line 280 of file CargoContainer.c.
References m_Entity.
GetFocusedContainerHeight() [1/2]
override float GetFocusedContainerHeight (bool contents = false) inline private
Definition at line 427 of file CargoContainer.c.
References GetFocusedIcon(), x, and y.
Referenced by LeftArea::GetCurrentContainerBottomY(), RightArea::GetCurrentContainerBottomY(), LayoutHolder::ScrollToActiveContainer(), and HandsContainer::ScrollToActiveContainer().
GetFocusedContainerHeight() [2/2]
override float GetFocusedContainerHeight (bool contents = false) inline private
Definition at line 121 of file ClosableContainer.c.
References LayoutHolder::GetFocusedContainerHeight(), x, and y.
GetFocusedContainerYPos() [1/2]
override float GetFocusedContainerYPos (bool contents = false) inline private
Definition at line 437 of file CargoContainer.c.
References GetFocusedIcon(), x, and y.
GetFocusedContainerYPos() [2/2]
override float GetFocusedContainerYPos (bool contents = false) inline private
Definition at line 131 of file ClosableContainer.c.
References LayoutHolder::GetFocusedContainerYPos(), x, and y.
GetFocusedContainerYScreenPos() [1/2]
override float GetFocusedContainerYScreenPos (bool contents = false) inline private
Definition at line 447 of file CargoContainer.c.
References GetFocusedIcon(), x, and y.
Referenced by LeftArea::GetCurrentContainerBottomY(), RightArea::GetCurrentContainerBottomY(), LeftArea::GetCurrentContainerTopY(), RightArea::GetCurrentContainerTopY(), LayoutHolder::ScrollToActiveContainer(), and HandsContainer::ScrollToActiveContainer().
GetFocusedContainerYScreenPos() [2/2]
override float GetFocusedContainerYScreenPos (bool contents = false) inline private
Definition at line 141 of file ClosableContainer.c.
References LayoutHolder::GetFocusedContainerYScreenPos(), x, and y.
GetFocusedIcon()
Icon GetFocusedIcon () inline private
Definition at line 422 of file CargoContainer.c.
References GetIcon().
Referenced by CanCombine(), CanCombineAmmo(), CanEquip(), Combine(), EquipItem(), GetFocusedContainerHeight(), GetFocusedContainerYPos(), GetFocusedContainerYScreenPos(), GetFocusedItem(), IsItemActive(), IsItemWithQuantityActive(), SelectItem(), SetLastActive(), SplitItem(), TransferItem(), TransferItemToVicinity(), and Unfocus().
GetFocusedItem()
override EntityAI GetFocusedItem () inline private
Definition at line 708 of file CargoContainer.c.
References GetFocusedIcon(), and Icon::GetObject().
Referenced by VicinitySlotsContainer::CanCombine(), VicinitySlotsContainer::CanCombineAmmo(), VicinitySlotsContainer::CanEquip(), VicinitySlotsContainer::Combine(), VicinitySlotsContainer::EquipItem(), ZombieContainer::EquipItem(), VicinityContainer::ExpandCollapseContainer(), Attachments::GetFocusedItem(), VicinitySlotsContainer::InspectItem(), VicinitySlotsContainer::IsEmptyItemActive(), ZombieContainer::IsEmptyItemActive(), VicinitySlotsContainer::IsItemActive(), VicinitySlotsContainer::IsItemWithContainerActive(), ZombieContainer::IsItemWithContainerActive(), VicinitySlotsContainer::IsItemWithQuantityActive(), ZombieContainer::IsItemWithQuantityActive(), VicinitySlotsContainer::IsTakeable(), HandsContainer::OnSelectButton(), Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), VicinitySlotsContainer::TransferItem(), ZombieContainer::TransferItem(), ZombieContainer::TransferItemToVicinity(), and UpdateInterval().
GetHeader()
override Header GetHeader () inline private
Definition at line 62 of file ClosableContainer.c.
Referenced by LayoutHolder::GetFocusedContainerHeight(), LayoutHolder::GetFocusedContainerYScreenPos(), LayoutHolder::SetActive(), LayoutHolder::SetLastActive(), VicinityContainer::UpdateHeader(), and UpdateHeaderText().
GetIcon() [1/2]
Icon GetIcon (EntityAI item) inline private
Definition at line 399 of file CargoContainer.c.
References LayoutHolder::Get().
GetIcon() [2/2]
Icon GetIcon (int index) inline private
Definition at line 409 of file CargoContainer.c.
References GetIcon(), CargoBase::GetItem(), CargoBase::GetItemCount(), and Print().
GetIconSize()
float GetIconSize () inline private
Definition at line 362 of file CargoContainer.c.
References m_IconSize.
GetMaxCargoCapacity()
int GetMaxCargoCapacity () inline private
Definition at line 389 of file CargoContainer.c.
References CargoBase::GetHeight(), and CargoBase::GetWidth().
Referenced by UpdateHeaderText().
GetRecipeCount()
int GetRecipeCount (bool recipe_anywhere, ItemBase entity1, ItemBase entity2, PlayerBase player) inline private
Definition at line 761 of file CargoContainer.c.
References GetPlugin().
GetSpaceSize()
float GetSpaceSize () inline private
Definition at line 367 of file CargoContainer.c.
References m_SpaceSize.
HasItem()
bool HasItem (EntityAI item) inline private
Definition at line 564 of file CargoContainer.c.
InitGridHeight()
void InitGridHeight () inline private
Definition at line 315 of file CargoContainer.c.
References m_Entity, and y.
Referenced by SetEntity().
InitIcon()
Icon InitIcon (Icon icon, EntityAI item, int pos_x, int pos_y) inline private
Definition at line 559 of file CargoContainer.c.
References InitIconEx().
InitIconEx()
Icon InitIconEx (Icon icon, EntityAI item, int pos_x, int pos_y, bool refresh = true) inline private
Definition at line 532 of file CargoContainer.c.
References GetGame(), CGame::GetInventoryItemSize(), Icon::InitEx(), Icon::SetCargoPos(), Icon::SetPosEx(), Icon::SetPosX(), Icon::SetPosY(), and Icon::SetSize().
Referenced by AddedToCargoEx(), and InitIcon().
IsDisplayable()
override bool IsDisplayable () inline private
Definition at line 17 of file ClosableContainer.c.
Referenced by LayoutHolder::RecomputeOpenedContainers(), and VicinitySlotsContainer::ShowItemsInContainers().
IsEmpty()
override bool IsEmpty () inline private
Definition at line 756 of file CargoContainer.c.
Referenced by AttachmentsWrapper::IsDisplayable(), AttachmentCategoriesContainer::IsDisplayable(), Attachments::IsEmpty(), IsItemWithQuantityActive(), and UpdateConsoleToolbar().
IsItemActive()
override bool IsItemActive () inline private
Definition at line 736 of file CargoContainer.c.
References GetFocusedIcon(), and GetObject().
Referenced by UpdateConsoleToolbar().
IsItemWithQuantityActive()
override bool IsItemWithQuantityActive () inline private
Definition at line 746 of file CargoContainer.c.
References GetFocusedIcon(), GetObject(), QuantityConversions::HasItemQuantity(), and IsEmpty().
Referenced by UpdateConsoleToolbar().
MoveContainerDown()
void MoveContainerDown (Widget cont) inline private
Definition at line 166 of file ClosableContainer.c.
References InventoryLocation::GetSlot(), Inventory(), InventoryLocation::IsValid(), and m_Entity.
MoveContainerUp()
void MoveContainerUp (Widget cont) inline private
Definition at line 151 of file ClosableContainer.c.
References InventoryLocation::GetSlot(), Inventory(), InventoryLocation::IsValid(), and m_Entity.
MovedInCargo()
void MovedInCargo (EntityAI item) inline private
Definition at line 142 of file CargoContainer.c.
References InventoryLocation::GetCol(), InventoryLocation::GetRow(), Icon::SetCargoPos(), UpdateSelection(), x, and y.
OnShow()
override void OnShow () inline private
Definition at line 93 of file ClosableContainer.c.
References ClosableContainer::IsOpened().
Referenced by AttachmentCategoriesContainer::UpdateInterval().
Open()
override void Open () inline private
Definition at line 67 of file ClosableContainer.c.
References ItemManager::GetInstance(), ClosableContainer::IsDisplayable(), m_Entity, m_Parent, OnShow(), and ItemManager::SetDefaultOpenState().
Referenced by AttachmentCategoriesRow::OnMouseButtonDown(), CollapsibleContainer::OnShow(), and LayoutHolder::Toggle().
Refresh() [1/2]
override void Refresh () inline private
Definition at line 504 of file CargoContainer.c.
Referenced by AddedToCargoEx(), LayoutHolder::Insert(), LayoutHolder::Remove(), RemovedFromCargo(), and SetEntity().
Refresh() [2/2]
override void Refresh () inline private
Definition at line 108 of file ClosableContainer.c.
RefreshImpl()
void RefreshImpl () inline private
Definition at line 515 of file CargoContainer.c.
References UpdateRowVisibility(), and UpdateSelection().
ReleaseLock()
void ReleaseLock (EntityAI item) inline private
Definition at line 197 of file CargoContainer.c.
References LayoutHolder::Get(), and LayoutHolder::Remove().
RemovedFromCargo()
void RemovedFromCargo (EntityAI item) inline private
Definition at line 113 of file CargoContainer.c.
References CargoBase::GetItem(), CargoBase::GetItemCount(), Math::Min(), Refresh(), and UpdateHeaderText().
Select()
override bool Select () inline private
Definition at line 872 of file CargoContainer.c.
References GameInventory::CanSwapEntitiesEx(), GetFocusedItem(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), ItemManager::GetSelectedContainer(), ItemManager::GetSelectedItem(), m_Entity, SetActive(), SetActive(), and SetDefaultFocus().
Referenced by HandsContainer::OnSelectButton(), AttachmentCategoriesRow::Select(), and UpdateInterval().
SelectItem()
override bool SelectItem () inline private
Definition at line 857 of file CargoContainer.c.
References GetFocusedIcon(), ItemManager::GetInstance(), Icon::GetObject(), ItemBase::IsTakeable(), and ItemManager::SetSelectedItem().
Referenced by EnableMicromanagement(), and RightArea::SelectItem().
SetActive()
override void SetActive (bool active) inline private
Definition at line 730 of file CargoContainer.c.
References UpdateSelection().
Referenced by MoveFocusByArea(), LayoutHolder::RecomputeOpenedContainers(), ResetFocusedContainers(), Select(), LayoutHolder::SetActive(), AttachmentsGroupContainer::SetNextActive(), LayoutHolder::SetNextActive(), AttachmentsGroupContainer::SetPreviousActive(), and UpdateInterval().
SetAlternateFalseTextHeaderWidget()
void SetAlternateFalseTextHeaderWidget (TextWidget w) inline private
Definition at line 960 of file CargoContainer.c.
References m_AlternateFalseHeaderTextWidget, and UpdateHeaderText().
SetDefaultFocus()
override void SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 587 of file CargoContainer.c.
References Unfocus(), and UpdateSelection().
Referenced by Select(), LayoutHolder::SetActive(), LayoutHolder::SetFirstActive(), and SetLastFocus().
SetEntity()
void SetEntity (EntityAI item, int cargo_index = 0, bool immedUpdate = true) inline private
Definition at line 237 of file CargoContainer.c.
References AddedToCargoEx(), CargoBase::GetItem(), CargoBase::GetItemCount(), InitGridHeight(), m_Entity, m_ItemsContainer, Refresh(), SetLock(), and UpdateHeaderText().
SetLastActive()
override void SetLastActive () inline private
Definition at line 719 of file CargoContainer.c.
References GetFocusedIcon(), Icon::SetActive(), and UpdateSelection().
Referenced by Attachments::SetLastActive(), LayoutHolder::SetLastActive(), AttachmentsGroupContainer::SetPreviousActive(), and LayoutHolder::SetPreviousActive().
SetLastFocus()
override void SetLastFocus () inline private
Definition at line 596 of file CargoContainer.c.
References SetDefaultFocus().
Referenced by LayoutHolder::SetLastActive().
SetLayoutName() [1/2]
override void SetLayoutName () inline private
Definition at line 210 of file CargoContainer.c.
References WidgetLayoutName::CargoContainerMedium, WidgetLayoutName::CargoContainerNarrow, WidgetLayoutName::CargoContainerWide, WidgetLayoutName::CargoContainerXbox, and InventoryMenu().
SetLayoutName() [2/2]
override void SetLayoutName () inline private
Definition at line 88 of file ClosableContainer.c.
References WidgetLayoutName::ClosableContainer.
SetLock()
void SetLock (EntityAI item) inline private
Definition at line 176 of file CargoContainer.c.
References InventoryLocation::GetCol(), InventoryLocation::GetFlip(), GetGame(), CGame::GetPlayer(), GetPlayer(), InventoryLocation::GetRow(), and m_Entity.
SetNextActive()
override void SetNextActive () inline private
Definition at line 622 of file CargoContainer.c.
References ROWS_NUMBER_XBOX, SetActive(), Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor(), AttachmentsGroupContainer::SetNextActive(), and LayoutHolder::SetNextActive().
SetNextLeftActive()
override void SetNextLeftActive () inline private
Definition at line 684 of file CargoContainer.c.
References ROWS_NUMBER_XBOX, Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor(), and LayoutHolder::SetNextLeftActive().
SetNextRightActive()
override void SetNextRightActive () inline private
Definition at line 660 of file CargoContainer.c.
References ROWS_NUMBER_XBOX, Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor(), and LayoutHolder::SetNextRightActive().
SetOpenState()
void SetOpenState (bool state) inline private
Definition at line 48 of file ClosableContainer.c.
References ItemManager::GetInstance(), m_Entity, OnHide(), OnShow(), and ItemManager::SetDefaultOpenState().
SetPreviousActive()
override void SetPreviousActive (bool force = false) inline private
Definition at line 643 of file CargoContainer.c.
References ROWS_NUMBER_XBOX, SetActive(), Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor(), LayoutHolder::Remove(), AttachmentsGroupContainer::SetPreviousActive(), and LayoutHolder::SetPreviousActive().
ShowFalseCargoHeader()
void ShowFalseCargoHeader (bool show) inline private
Definition at line 955 of file CargoContainer.c.
SplitItem()
override bool SplitItem () inline private
Definition at line 821 of file CargoContainer.c.
References LayoutHolder::Get(), GetFocusedIcon(), GetObject(), and Icon::SetQuantity().
Referenced by UpdateInterval().
TransferItem()
override bool TransferItem () inline private
Definition at line 807 of file CargoContainer.c.
References GetFocusedIcon(), GetGame(), GetObject(), and CGame::GetPlayer().
Referenced by UpdateInterval().
TransferItemToVicinity()
override bool TransferItemToVicinity () inline private
Definition at line 569 of file CargoContainer.c.
References GetFocusedIcon(), GetGame(), GetObject(), and CGame::GetPlayer().
Referenced by UpdateInterval().
Unfocus()
override void Unfocus () inline private
Definition at line 601 of file CargoContainer.c.
References GetFocusedIcon(), and Icon::SetActive().
Referenced by LayoutHolder::SetActive(), SetDefaultFocus(), SetNextActive(), SetNextLeftActive(), SetNextRightActive(), and SetPreviousActive().
UnfocusAll()
override void UnfocusAll () inline private
Definition at line 610 of file CargoContainer.c.
Referenced by Attachments::UnfocusAll(), and PlayerContainer::UnfocusPlayerAttachmentsContainer().
UpdateHeaderText()
void UpdateHeaderText () inline private
Definition at line 285 of file CargoContainer.c.
References GetCargoCapacity(), GetHeader(), GetMaxCargoCapacity(), GetParent(), InventoryMenu(), m_Entity, name, Header::SetName(), string::ToUpper(), x, and y.
Referenced by AddedToCargoEx(), RemovedFromCargo(), SetAlternateFalseTextHeaderWidget(), and SetEntity().
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 521 of file CargoContainer.c.
Referenced by PlayerContainer::UpdateInterval().
UpdateRadialIcon()
override void UpdateRadialIcon () inline private
Definition at line 28 of file ClosableContainer.c.
References ClosableContainer::IsDisplayable(), ClosableContainer::IsOpened(), m_Entity, and ScriptedWidgetEventHandler::Show().
Referenced by VicinitySlotsContainer::ShowItemsInContainers(), and Attachments::UpdateInterval().
UpdateRowVisibility()
void UpdateRowVisibility (int count) inline private
Definition at line 472 of file CargoContainer.c.
References Math::Ceil(), m_CargoContainer, m_Entity, m_ItemsContainer, and Math::Max().
Referenced by RefreshImpl().
UpdateSelection()
void UpdateSelection () inline private
Definition at line 457 of file CargoContainer.c.
References GetIcon(), Inventory(), m_IsActive, and Icon::SetActive().
Referenced by MovedInCargo(), RefreshImpl(), SetActive(), SetDefaultFocus(), SetLastActive(), SetNextActive(), SetNextLeftActive(), SetNextRightActive(), and SetPreviousActive().
UpdateSize()
void UpdateSize () inline private
Definition at line 357 of file CargoContainer.c.
Field Documentation
m_AlternateFalseHeaderTextWidget
protected TextWidget m_AlternateFalseHeaderTextWidget private
Definition at line 20 of file CargoContainer.c.
Referenced by SetAlternateFalseTextHeaderWidget().
m_Cargo
protected CargoBase m_Cargo private
Definition at line 6 of file CargoContainer.c.
m_CargoContainer
protected Widget m_CargoContainer private
Definition at line 22 of file CargoContainer.c.
Referenced by CargoContainer(), and UpdateRowVisibility().
m_CargoHeader
protected Widget m_CargoHeader private
Definition at line 21 of file CargoContainer.c.
m_CargoIndex
protected int m_CargoIndex = -1 private
Definition at line 7 of file CargoContainer.c.
Referenced by GetCargoIndex().
m_ClosableHeader
protected ref ClosableHeader m_ClosableHeader private
Definition at line 3 of file ClosableContainer.c.
m_FalseHeaderTextWidget
protected TextWidget m_FalseHeaderTextWidget private
Definition at line 19 of file CargoContainer.c.
m_FocusedItemPosition
protected int m_FocusedItemPosition = -1 private
Definition at line 9 of file CargoContainer.c.
m_Icons
protected ref array<ref Icon> m_Icons private
Definition at line 11 of file CargoContainer.c.
m_IconSize
protected float m_IconSize private
Definition at line 15 of file CargoContainer.c.
Referenced by GetIconSize().
m_IsAttachment
protected bool m_IsAttachment private
Definition at line 18 of file CargoContainer.c.
m_ItemsContainer
protected Widget m_ItemsContainer private
Definition at line 23 of file CargoContainer.c.
Referenced by SetEntity(), and UpdateRowVisibility().
m_LockCargo
protected bool m_LockCargo private
Definition at line 4 of file ClosableContainer.c.
m_Resizer1
protected ref SizeToChild m_Resizer1 private
Definition at line 24 of file CargoContainer.c.
m_Resizer2
protected ref SizeToChild m_Resizer2 private
Definition at line 25 of file CargoContainer.c.
m_ResizeTimer
protected ref Timer m_ResizeTimer private
Definition at line 26 of file CargoContainer.c.
m_Rows
protected ref array<ref CargoContainerRow> m_Rows private
Definition at line 10 of file CargoContainer.c.
m_ShowedItemPositions
protected ref map<EntityAI, ref Param3<ref Icon, int, int> > m_ShowedItemPositions private
Definition at line 12 of file CargoContainer.c.
m_ShowedLockPositions
protected ref map<EntityAI, ref Param3<ref Icon, int, int> > m_ShowedLockPositions private
Definition at line 13 of file CargoContainer.c.
m_SpaceSize
protected float m_SpaceSize private
Definition at line 16 of file CargoContainer.c.
Referenced by GetSpaceSize().
ROWS_NUMBER_XBOX
protected const int ROWS_NUMBER_XBOX = 5 private
Definition at line 4 of file CargoContainer.c.
Referenced by SetNextActive(), SetNextLeftActive(), SetNextRightActive(), and SetPreviousActive().
The documentation for this class was generated from the following files:
P:/scripts/5_Mission/GUI/InventoryNew/ContainedItems/CargoContainer.c
P:/scripts/5_Mission/GUI/InventoryNew/Containers/ClosableContainer.c