DayZ Scripts: HumanCommandWeapons Class Reference
HumanCommandWeapons Class Reference
Private Member Functions
private void HumanCommandWeapons ()
private void ~HumanCommandWeapons ()
proto native bool IsActionFinished ()
proto native int GetRunningAction ()
returns -1 when no action is running or RELOAD,MECHANISM, ....
proto native int GetRunningActionType ()
returns -1 when no action is running or appropriate action type
proto native void SetActionProgressParams (float pStart, float pEnd)
sets start and end animation position - f.e. for reload clip action
proto native bool StartAction (WeaponActions pAction, int pActionType)
start reload,mechanism,chambering,unjam ...
proto native void RegisterEvent (string pName, int pId)
register events
proto native int IsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
proto native bool IsInWeaponReloadBulletSwitchState ()
returns true when clip visual change is needed for reload clip action
proto native void SetADS (bool pState)
sets head tilt to optics
proto native void LiftWeapon (bool pState)
command for lifting weapon near obstacled (works only when weapon is raised)
void RegisterDefaultEvents ()
proto native void SetInitState (int pFrameIndex)
proto native float GetBaseAimingAngleUD ()
returns base aiming angle UD - without sway/offsets/...
proto native float GetBaseAimingAngleLR ()
returns base aiming angle LR - without sway/offsets/...
proto native void SetThrowingMode (bool pState)
proto native bool IsThrowingMode ()
proto native void ThrowItem (int throwType)
proto native bool WasItemLeaveHandsEvent ()
proto native int DebugIsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
proto native void DebugResetEvents ()
Static Private Member Functions
proto static native void StaticSetInitState (Human pHuman, int pFrameIdx)
just static version of SetInitState
Detailed Description
Definition at line 968 of file human.c.
Constructor & Destructor Documentation
HumanCommandWeapons()
private void HumanCommandWeapons () inline private
Definition at line 970 of file human.c.
~HumanCommandWeapons()
private void ~HumanCommandWeapons () inline private
Definition at line 971 of file human.c.
Member Function Documentation
DebugIsEvent()
proto native int DebugIsEvent () private
return -1 when there is no event, otherwise it returns pId of event from animation
Referenced by PluginDayzPlayerDebug_Weapons::Tick().
DebugResetEvents()
proto native void DebugResetEvents () private
Referenced by PluginDayzPlayerDebug_Weapons::PluginDayzPlayerDebug_Weapons().
GetBaseAimingAngleLR()
proto native float GetBaseAimingAngleLR () private
returns base aiming angle LR - without sway/offsets/...
Referenced by HandleProneKick(), and DayZPlayerImplementThrowing::HandleThrowing().
GetBaseAimingAngleUD()
proto native float GetBaseAimingAngleUD () private
returns base aiming angle UD - without sway/offsets/...
Referenced by DayZPlayerImplementThrowing::HandleThrowing().
GetRunningAction()
proto native int GetRunningAction () private
returns -1 when no action is running or RELOAD,MECHANISM, ....
Referenced by FirearmActionAttachMagazine::ActionCondition(), FirearmActionAttachMagazineQuick::ActionCondition(), FirearmActionLoadBullet::ActionCondition(), FirearmActionLoadBulletQuick::ActionCondition(), DayZPlayer::CommandHandlerDebug(), HandleInventory(), HandleWeaponEvents(), HandStateBase::OnEntry(), WeaponStateBase::OnEntry(), and PluginDayzPlayerDebug_Weapons::Tick().
GetRunningActionType()
proto native int GetRunningActionType () private
returns -1 when no action is running or appropriate action type
Referenced by HandleInventory(), HandleWeaponEvents(), HandStateBase::OnEntry(), WeaponStateBase::OnEntry(), and PluginDayzPlayerDebug_Weapons::Tick().
IsActionFinished()
proto native bool IsActionFinished () private
Referenced by DayZPlayer::CommandHandlerDebug(), HandleInventory(), HandleWeaponEvents(), HandStateBase::OnEntry(), WeaponStateBase::OnEntry(), and Play().
IsEvent()
proto native int IsEvent () private
return -1 when there is no event, otherwise it returns pId of event from animation
Referenced by DayZPlayer::CommandHandlerDebug(), HandleInventory(), and HandleWeaponEvents().
IsInWeaponReloadBulletSwitchState()
proto native bool IsInWeaponReloadBulletSwitchState () private
returns true when clip visual change is needed for reload clip action
IsThrowingMode()
proto native bool IsThrowingMode () private
Referenced by DayZPlayerImplementThrowing::HandleThrowing().
LiftWeapon()
proto native void LiftWeapon (bool pState) private
command for lifting weapon near obstacled (works only when weapon is raised)
Referenced by ManBase::ProcessLiftWeapon(), and ManBase::SendLiftWeaponSync().
RegisterDefaultEvents()
void RegisterDefaultEvents () inline private
Definition at line 1004 of file human.c.
References RegisterEvent().
RegisterEvent()
proto native void RegisterEvent (string pName, int pId) private
register events
Referenced by RegisterDefaultEvents().
SetActionProgressParams()
proto native void SetActionProgressParams (float pStart, float pEnd) private
sets start and end animation position - f.e. for reload clip action
Referenced by PluginDayzPlayerDebug_Weapons::CommandHandler(), and DayZPlayerImplementThrowing::HandleThrowing().
SetADS()
proto native void SetADS (bool pState) private
sets head tilt to optics
Referenced by DayZPlayer::ExitSights(), DayZPlayer::HandleADS(), DayZPlayer::SetIronsights(), and DayZPlayer::SetOptics().
SetInitState()
proto native void SetInitState (int pFrameIndex) private
this sets to a weapon init state each weapon has a different weapon state those states are defined by animation set by AddItemInHandsProfileIK - in DayZPlayerCfgBase.c each frame of animation is one init state
Referenced by PluginDayzPlayerDebug_Weapons::OnClick(), WeaponManager::RefreshAnimationState(), and SyncAnimState().
SetThrowingMode()
proto native void SetThrowingMode (bool pState) private
Referenced by DayZPlayerImplementThrowing::HandleThrowing().
StartAction()
proto native bool StartAction (WeaponActions pAction, int pActionType) private
start reload,mechanism,chambering,unjam ...
Referenced by PluginDayzPlayerDebug_Weapons::CommandHandler(), DayZPlayer::CommandHandlerDebug(), HandStateBase::OnEntry(), WeaponStateBase::OnEntry(), and WeaponStartAction::OnUpdate().
StaticSetInitState()
proto static native void StaticSetInitState (Human pHuman, int pFrameIdx) static private
just static version of SetInitState
Referenced by SyncAnimState().
ThrowItem()
proto native void ThrowItem (int throwType) private
Referenced by DayZPlayerImplementThrowing::HandleThrowing().
WasItemLeaveHandsEvent()
proto native bool WasItemLeaveHandsEvent () private
Referenced by DayZPlayerImplementThrowing::HandleThrowing().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/human.c