DayZ Scripts: DayZCreatureAIType Class Reference
DayZCreatureAIType Class Reference
Private Member Functions
private void DayZCreatureAIType ()
private void ~DayZCreatureAIType ()
void LoadAnimSoundEvents ()
void LoadAnimSoundVoiceEvents ()
void LoadAnimStepEvents ()
void LoadAnimDamageEvents ()
private void LoadParams ()
AnimStepEvent GetStepEvent (int event_id)
AnimSoundEvent GetSoundEvent (int event_id)
AnimSoundVoiceEvent GetSoundVoiceEvent (int event_id)
AnimDamageEvent GetDamageEvent (int event_id)
proto native owned string GetName ()
Private Attributes
ref array< ref AnimSoundEvent > m_animSoundEvents
ref array< ref AnimSoundVoiceEvent > m_animSoundVoiceEvents
ref array< ref AnimStepEvent > m_animStepEvents
ref array< ref AnimDamageEvent > m_animDamageEvents
string m_CfgPath
string m_AnimEventsCfgPath
Detailed Description
Definition at line 1 of file DayZAnimalType.c.
Constructor & Destructor Documentation
DayZCreatureAIType()
private void DayZCreatureAIType () inline private
Definition at line 11 of file DayZCreatureAIType.c.
References GetName(), LoadParams(), m_AnimEventsCfgPath, and m_CfgPath.
~DayZCreatureAIType()
private void ~DayZCreatureAIType () inline private
Definition at line 18 of file DayZCreatureAIType.c.
Member Function Documentation
GetDamageEvent()
AnimDamageEvent GetDamageEvent (int event_id) inline private
Definition at line 142 of file DayZCreatureAIType.c.
References m_animDamageEvents.
GetName()
proto native owned string GetName () private
Referenced by DayZCreatureAIType(), and RegisterAttacks().
GetSoundEvent()
AnimSoundEvent GetSoundEvent (int event_id) inline private
Definition at line 114 of file DayZCreatureAIType.c.
References m_animSoundEvents.
GetSoundVoiceEvent()
AnimSoundVoiceEvent GetSoundVoiceEvent (int event_id) inline private
Definition at line 128 of file DayZCreatureAIType.c.
References m_animSoundVoiceEvents.
GetStepEvent()
AnimStepEvent GetStepEvent (int event_id) inline private
Definition at line 100 of file DayZCreatureAIType.c.
References m_animStepEvents.
LoadAnimDamageEvents()
void LoadAnimDamageEvents () inline private
Definition at line 75 of file DayZCreatureAIType.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), m_animDamageEvents, and m_AnimEventsCfgPath.
Referenced by LoadParams().
LoadAnimSoundEvents()
void LoadAnimSoundEvents () inline private
Definition at line 23 of file DayZCreatureAIType.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), m_AnimEventsCfgPath, and m_animSoundEvents.
Referenced by LoadParams().
LoadAnimSoundVoiceEvents()
void LoadAnimSoundVoiceEvents () inline private
Definition at line 41 of file DayZCreatureAIType.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), m_AnimEventsCfgPath, and m_animSoundVoiceEvents.
Referenced by LoadParams().
LoadAnimStepEvents()
void LoadAnimStepEvents () inline private
Definition at line 59 of file DayZCreatureAIType.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), m_AnimEventsCfgPath, and m_animStepEvents.
Referenced by LoadParams().
LoadParams()
private void LoadParams () inline private
Definition at line 92 of file DayZCreatureAIType.c.
References LoadAnimDamageEvents(), LoadAnimSoundEvents(), LoadAnimSoundVoiceEvents(), and LoadAnimStepEvents().
Referenced by DayZCreatureAIType().
Field Documentation
m_animDamageEvents
ref array<ref AnimDamageEvent> m_animDamageEvents private
Definition at line 6 of file DayZCreatureAIType.c.
Referenced by GetDamageEvent(), and LoadAnimDamageEvents().
m_AnimEventsCfgPath
string m_AnimEventsCfgPath private
Definition at line 9 of file DayZCreatureAIType.c.
Referenced by DayZCreatureAIType(), LoadAnimDamageEvents(), LoadAnimSoundEvents(), LoadAnimSoundVoiceEvents(), and LoadAnimStepEvents().
m_animSoundEvents
ref array<ref AnimSoundEvent> m_animSoundEvents private
Definition at line 3 of file DayZCreatureAIType.c.
Referenced by GetSoundEvent(), and LoadAnimSoundEvents().
m_animSoundVoiceEvents
ref array<ref AnimSoundVoiceEvent> m_animSoundVoiceEvents private
Definition at line 4 of file DayZCreatureAIType.c.
Referenced by GetSoundVoiceEvent(), and LoadAnimSoundVoiceEvents().
m_animStepEvents
ref array<ref AnimStepEvent> m_animStepEvents private
Definition at line 5 of file DayZCreatureAIType.c.
Referenced by GetStepEvent(), and LoadAnimStepEvents().
m_CfgPath
string m_CfgPath private
Definition at line 8 of file DayZCreatureAIType.c.
Referenced by DayZCreatureAIType().
The documentation for this class was generated from the following files:
P:/scripts/3_Game/Entities/DayZAnimalType.c
P:/scripts/3_Game/Entities/DayZCreatureAIType.c