DayZ Scripts: Entity Class Reference
Entity Class Reference
Private Member Functions
proto native void SetNearPlane (float nearPlane)
proto native float GetNearPlane ()
proto native void SetActive (bool active)
Sets this camera as active.
proto native bool IsActive ()
Is this camera active?
proto native void SetFOV (float fov)
Field of View settings.
proto native void SetFocus (float distance, float blur)
Depth of Field settings.
proto native void LookAt (vector targetPos)
Orientation change by lookAt point.
void EntityAI ()
void ~EntityAI ()
void InitItemVariables ()
void DeferredInit ()
bool IsInitialized ()
int GetHideIconMask ()
should the item's icon be hidden in any part of the inventory?
Component CreateComponent (int comp_type, string extended_class_name="")
CreateComponent.
Component GetComponent (int comp_type, string extended_class_name="")
GetComponent.
bool DeleteComponent (int comp_type)
DeleteComponent.
string GetDestructionBehaviour ()
bool IsDestructionBehaviour ()
bool HasComponent (int comp_type)
IsComponentExist.
void MaxLifetimeRefreshCalc ()
Calculates if the max lifetime is higher than refresher frequency (i.e. gets kept alive by refresher)
bool IsRefresherSignalingViable ()
void InitDamageZoneMapping ()
Initializes script-side map of damage zones and their components (named selections in models)
void InitDamageZoneDisplayNameMapping ()
Initialize map of damage zone display names for more optimized retrieval.
protected float ConvertNonlethalDamage (float damage, DamageType damageType)
float ConvertNonlethalDamage (float damage)
DEPRECATED - for legacy purposes.
DamageZoneMap GetEntityDamageZoneMap ()
map< int, string > GetEntityDamageDisplayNameMap ()
bool CanDisplayWeight ()
'displayWeight' in item config
void Log (string msg, string fnc_name="n/a")
Log.
void LogWarning (string msg, string fnc_name="n/a")
LogWarning.
void LogError (string msg, string fnc_name="n/a")
LogError.
bool HasFlammableMaterial ()
Override this method to return TRUE when this item has or can provide fire. Evaluated on server and client.
bool CanBeIgnitedBy (EntityAI igniter=NULL)
Override this method so it checks whenever this item can be ignited right now or not. Evaluated on Server and Client.
bool CanIgniteItem (EntityAI ignite_target=NULL)
Override this method and check if the given item can be ignited right now by this one. Evaluated on Server and Client.
bool IsIgnited ()
Override this method and make it so it returns whenever this item is on fire right now or not. Evaluated on Server and Client.
bool DisassembleOnLastDetach ()
bool IsBasebuildingKit ()
bool PlacementCanBeRotated ()
Should return false if you want to disable hologram rotation.
void OnIgnitedTarget (EntityAI target_item)
Executed on Server when this item ignites some target item.
void OnIgnitedThis (EntityAI fire_source)
Executed on Server when some item ignited this one.
void OnIgnitedTargetFailed (EntityAI target_item)
Executed on Server when this item failed to ignite target item.
void OnIgnitedThisFailed (EntityAI fire_source)
Executed on Server when some item failed to ignite this one.
bool IsTargetIgnitionSuccessful (EntityAI item_target)
Final evaluation just before the target item is actually ignited. Evaluated on Server.
bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
Final evaluation just before this item is actually ignited from fire source. Evaluated on Server.
void OnPlacementStarted (Man player)
void OnHologramBeingPlaced (Man player)
void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
void OnPlacementCancelled (Man player)
bool CanBePlaced (Man player, vector position)
string CanBePlacedFailMessage (Man player, vector position)
Method which returns message why object can't be placed at given position.
bool DoPlacingHeightCheck ()
Do the roof check when placing this?
float HeightCheckOverride ()
used as script-side override of distance for specific height checks
float HeightStartCheckOverride ()
used as script-side override of start pos for specific height checks
bool IsEmpty ()
is this container empty or not, checks both cargo and attachments
bool IsSplitable ()
returns just the configured 'canBeSplit' bool
bool CanBeSplit ()
returns current splitability
bool HasAnyCargo ()
is this container empty or not, checks only cargo
array< EntityAI > GetAttachmentsWithCargo ()
array< EntityAI > GetAttachmentsWithAttachments ()
bool IsRoofAbove ()
void SetRoofAbove (bool state)
void CheckForRoofLimited (float timeTresholdMS=3000)
Roof check for entity, limited by time (anti-spam solution)
int GetAgents ()
void RemoveAgent (int agent_id)
void RemoveAllAgents ()
void RemoveAllAgentsExcept (int agent_to_keep)
void InsertAgent (int agent, float count=1)
override bool IsEntityAI ()
bool IsInventoryVisible ()
bool IsPlayer ()
bool IsAnimal ()
bool IsZombie ()
bool IsZombieMilitary ()
bool IsIgnoredByConstruction ()
bool CanBeTargetedByAI (EntityAI ai)
bool CanBeBackstabbed ()
override void Delete ()
Delete this object in next frame.
void DeleteOnClient ()
void DeleteSafe ()
void DeleteSave ()
bool IsSetForDeletion ()
override bool CanBeActionTarget ()
void SetPrepareToDelete ()
bool IsPreparedToDelete ()
void CheckForDestroy ()
bool IsPrepareToDelete ()
bool TryDelete ()
void OnBeforeTryDelete ()
proto native EntityAI GetHierarchyRoot ()
Returns root of current hierarchy (for example: if this entity is in Backpack on gnd, returns Backpack)
proto native Man GetHierarchyRootPlayer ()
Returns root of current hierarchy cast to Man.
proto native EntityAI GetHierarchyParent ()
Returns direct parent of current entity.
proto native CEItemProfile GetEconomyProfile ()
Get economy item profile (if assigned, otherwise null)
int GetHierarchyLevel (int lvl=0)
void OnInventoryInit ()
void EEInit ()
Called upon object creation.
void EEDelete (EntityAI parent)
Called right before object deleting.
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
void OnChildItemRemoved (InventoryItem item)
void OnChildItemReceived (InventoryItem item)
void OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void EEParentedTo (EntityAI parent)
Called from 'IEntity.AddChild'.
void EEParentedFrom (EntityAI parent)
Called from 'IEntity.RemoveChild' or 'IEntity.AddChild' when hierarchy changes.
void EEInventoryIn (Man newParentMan, EntityAI diz, EntityAI newParent)
void EEInventoryOut (Man oldParentMan, EntityAI diz, EntityAI newParent)
void EEAmmoChanged ()
void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
void OnDamageDestroyed (int oldLevel)
Called when the health gets to the min value, 'oldLevel' is previous health level, 'oldLevel' -1 means this entity was just spawned.
void AttemptDestructionBehaviour (int oldLevel, int newLevel, string zone)
void SetTakeable (bool pState)
void EEKilled (Object killer)
called on server when the entity is killed
bool ReplaceOnDeath ()
string GetDeadItemName ()
bool KeepHealthOnReplace ()
void DeathUpdate ()
void OnAttachmentRuined (EntityAI attachment)
Called when some attachment of this parent is ruined. Called on server and client side.
void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos)
void EEItemAttached (EntityAI item, string slot_name)
void SwitchItemSelectionTexture (EntityAI item, string slot_name)
void SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par=null)
void EEItemDetached (EntityAI item, string slot_name)
void EECargoIn (EntityAI item)
void EECargoOut (EntityAI item)
void EECargoMove (EntityAI item)
ScriptInvoker GetOnItemAttached ()
ScriptInvoker GetOnItemDetached ()
ScriptInvoker GetOnItemAddedIntoCargo ()
ScriptInvoker GetOnItemRemovedFromCargo ()
ScriptInvoker GetOnItemMovedInCargo ()
ScriptInvoker GetOnItemFlipped ()
ScriptInvoker GetOnViewIndexChanged ()
ScriptInvoker GetOnSetLock ()
ScriptInvoker GetOnReleaseLock ()
ScriptInvoker GetOnAttachmentSetLock ()
ScriptInvoker GetOnAttachmentReleaseLock ()
ScriptInvoker GetOnHitByInvoker ()
ScriptInvoker GetOnKilledInvoker ()
void OnMovedInsideCargo (EntityAI container)
Called when this item enters cargo of some container.
void OnRemovedFromCargo (EntityAI container)
Called when this item exits cargo of some container.
void OnMovedWithinCargo (EntityAI container)
Called when this item moves within cargo of some container.
void EEOnAfterLoad ()
Called when entity is part of "connected system" and being restored after load.
void EEOnCECreate ()
Called when entity is being created as new by CE/ Debug.
void AfterStoreLoad ()
Called when entity is being loaded from DB or Storage (after all children loaded)
void OnBinLoadItemsDropped ()
Called when an item fails to get loaded into the inventory of an entity and gets dropped.
void HideAllSelections ()
Sets all animation values to 1, making them INVISIBLE if they are configured in models.cfg in such way. These selections must also be defined in the entity's config class in 'AnimationSources'.
void ShowAllSelections ()
Sets all animation values to 0, making them VISIBLE if they are configured in models.cfg in such way. These selections must also be defined in the entity's config class in 'AnimationSources'.
bool CanReceiveAttachment (EntityAI attachment, int slotId)
calls this->CanReceiveAttachment(attachment)
bool CanLoadAttachment (EntityAI attachment)
bool CanPutAsAttachment (EntityAI parent)
calls this->CanPutAsAttachment(parent)
bool CanSwitchDuringAttach (EntityAI parent)
bool CanReleaseAttachment (EntityAI attachment)
calls this->CanReleaseAttachment(attachment)
bool CanDetachAttachment (EntityAI parent)
calls this->CanDetachAttachment(parent)
bool CanBeFSwaped ()
bool CanCombineAttachment (notnull EntityAI e, int slot, bool stack_max_limit=false)
bool CanBeCombined (EntityAI other_item, bool reservation_check=true, bool stack_max_limit=false)
void CombineItemsEx (EntityAI entity2, bool use_stack_max=false)
void SplitIntoStackMaxEx (EntityAI destination_entity, int slot_id)
void CombineItemsClient (EntityAI entity2, bool use_stack_max=false)
void SplitIntoStackMaxClient (EntityAI destination_entity, int slot_id)
bool CanReceiveItemIntoCargo (EntityAI item)
calls this->CanReceiveItemIntoCargo(item)
bool CanLoadItemIntoCargo (EntityAI item)
calls this->CanLoadItemIntoCargo(item), is called on server start when loading in the storage
bool CanPutInCargo (EntityAI parent)
calls this->CanPutInCargo(parent)
bool CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity)
calls this->CanSwapItemInCargo(child_entity, new_entity)
bool CanReleaseCargo (EntityAI cargo)
calls this->CanReleaseCargo(cargo)
bool CanRemoveFromCargo (EntityAI parent)
calls this->CanRemoveFromCargo(parent)
bool CanReceiveItemIntoHands (EntityAI item_to_hands)
calls this->CanReceiveItemIntoHands(item_to_hands)
bool AreChildrenAccessible ()
bool IsBeingPlaced ()
override bool IsHologram ()
bool CanSaveItemInHands (EntityAI item_in_hands)
bool CanPutIntoHands (EntityAI parent)
calls this->CanPutIntoHands(parent)
bool CanReleaseFromHands (EntityAI handheld)
calls this->CanReleaseFromHands(handheld)
bool CanRemoveFromHands (EntityAI parent)
calls this->CanRemoveFromHands(parent)
bool CanDisplayAttachmentSlot (string slot_name)
bool CanDisplayAttachmentSlot (int slot_id)
bool CanDisplayAnyAttachmentSlot ()
bool CanDisplayAttachmentCategory (string category_name)
bool CanDisplayCargo ()
bool CanAssignToQuickbar ()
bool CanAssignAttachmentsToQuickbar ()
bool IgnoreOutOfReachCondition ()
void OnWasAttached (EntityAI parent, int slot_id)
void OnWasDetached (EntityAI parent, int slot_id)
void OnCargoChanged ()
bool IsTakeable ()
proto native GameInventory GetInventory ()
proto native void CreateAndInitInventory ()
proto native void DestroyInventory ()
int GetSlotsCountCorrect ()
EntityAI FindAttachmentBySlotName (string slot_name)
bool IsLockedInSlot ()
bool PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
Put item anywhere into this entity (as attachment or into cargo, recursively)
bool LocalTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
bool ServerTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
bool PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool LocalTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool ServerTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool PredictiveTakeEntityToCargo (notnull EntityAI item)
Put item into into cargo.
bool LocalTakeEntityToCargo (notnull EntityAI item)
bool ServerTakeEntityToCargo (notnull EntityAI item)
bool PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
bool LocalTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
bool ServerTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
bool PredictiveTakeEntityToCargoEx (notnull EntityAI item, int idx, int row, int col)
Put item into into cargo on specific cargo location.
bool LocalTakeEntityToCargoEx (notnull EntityAI item, int idx, int row, int col)
bool PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
bool LocalTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
bool ServerTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
bool PredictiveTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
Returns if item can be added as attachment on specific slot. Note that slot index IS NOT slot ID! Slot ID is defined in DZ/data/config.cpp.
bool LocalTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
bool ServerTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
bool PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
bool LocalTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
bool ServerTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
bool PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
bool LocalTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
bool ServerTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
bool PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
bool LocalTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
bool ServerTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
bool PredictiveTakeEntityAsAttachment (notnull EntityAI item)
Put item into as attachment.
bool LocalTakeEntityAsAttachment (notnull EntityAI item)
bool ServerTakeEntityAsAttachment (notnull EntityAI item)
bool PredictiveDropEntity (notnull EntityAI item)
bool LocalDropEntity (notnull EntityAI item)
bool ServerDropEntity (notnull EntityAI item)
EntityAI GetAttachmentByType (typename type)
Get attached entity by type.
EntityAI GetAttachmentByConfigTypeName (string type)
Get attached entity by config type name.
bool CanDropEntity (notnull EntityAI item)
Returns if item can be dropped out from this entity.
EntityAI SpawnInInventoryOrGroundPos (string object_name, GameInventory inv, vector pos)
EntityAI SpawnEntityOnGroundPos (string object_name, vector pos)
EntityAI SpawnEntityOnGround (string object_name, vector mat[4])
bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
void SetWet (float value, bool allow_client=false)
void AddWet (float value)
void SetWetMax ()
float GetWet ()
float GetWetMax ()
float GetWetMin ()
float GetWetInit ()
bool HasWetness ()
void OnWetChanged (float newVal, float oldVal)
void OnWetLevelChanged (EWetnessLevel newLevel, EWetnessLevel oldLevel)
EWetnessLevel GetWetLevel ()
bool HasQuantity ()
bool SetQuantity (float value, bool destroy_config=true, bool destroy_forced=false, bool allow_client=false, bool clamp_to_stack_max=true)
float GetQuantity ()
float GetQuantityNormalized ()
int GetQuantityMax ()
int GetQuantityMin ()
void SetQuantityToMinimum ()
int GetTargetQuantityMax (int attSlotID=-1)
int GetQuickBarBonus ()
bool UseConfigInitTemperature ()
protected void InitTemperature ()
void SetTemperatureDirect (float value, bool allow_client=false)
void SetTemperature (float value, bool allow_client=false)
not really deprecated, but missing context info from TemperatureData. Default values used instead.
void AddTemperature (float value)
void SetTemperatureEx (TemperatureData data)
sets temperature, handles base overheating and freezing state progression logics
void RefreshTemperatureAccess (TemperatureData data)
refreshes access without setting temperature, keeps the source locked in
void InterpolateTempData (TemperatureDataInterpolated data)
void SetTemperatureMax ()
presumably for debug purposes?
float GetTemperature ()
float GetTemperatureInit ()
float GetTemperatureMin ()
float GetTemperatureMax ()
bool GetCookingTargetTemperature (out float temperature)
specifically for cooking system, to get heat source target temperatures
float GetHeatPermeabilityCoef ()
Returns temperature change speed multiplier for this item and all its children (multiplicative interaction)
float GetTemperatureFreezeThreshold ()
float GetTemperatureThawThreshold ()
float GetTemperatureFreezeTime ()
float GetTemperatureThawTime ()
float GetFreezeThawProgress ()
on server only
protected void SetFreezeThawProgress (float val)
0->1 when freezing, 1->0 when thawing
bool CanFreeze ()
bool GetIsFrozen ()
void SetFrozen (bool frozen)
protected void HandleFreezingProgression (float deltaHeat, TemperatureData data)
void OnFreezeStateChangeClient ()
void OnFreezeStateChangeServer ()
bool CanItemOverheat ()
Overheat time CAN be 0, GameConstants.TEMPERATURE_TIME_OVERHEAT_MIN is ignored if so.
float GetItemOverheatThreshold ()
if undefined, max temperature used as default
float GetItemOverheatTime ()
any configured value >= 0 will simulate overheating
bool IsItemOverheated ()
float GetItemOverheatProgress ()
void SetItemOverheatProgress (float val, float deltaTime=0)
protected void OnItemOverheatStart ()
override to implement desired overheat behavior on entity
protected void OnItemOverheat (float deltaTime)
protected void OnItemOverheatEnd ()
note, that the deltaTime could be reverse-calculated and not totally accurate
protected void HandleItemOverheating (float deltaHeat, TemperatureData data)
void SetLiquidType (int value, bool allow_client=false)
int GetLiquidType ()
void SetColor (int r, int g, int b, int a)
void GetColor (out int r, out int g, out int b, out int a)
void SetStoreLoad (bool value)
bool IsStoreLoad ()
void SetStoreLoadedQuantity (float value)
float GetStoreLoadedQuantity ()
void SetCleanness (int value, bool allow_client=false)
int GetCleanness ()
bool IsServerCheck (bool allow_client)
HiddenSelectionsData GetHiddenSelectionsData ()
int GetHiddenSelectionIndex (string selection)
Returns index of the string found in cfg array 'hiddenSelections'. If it's not found then it returns -1.
override TStringArray GetHiddenSelections ()
Returns the hiddenSelectionsTextures array from the object's config.
override TStringArray GetHiddenSelectionsTextures ()
Returns the hiddenSelectionsTextures array from the object's config.
override TStringArray GetHiddenSelectionsMaterials ()
Returns the hiddenSelectionsMaterials array from the object's config.
proto native void PlaceOnSurfaceRotated (out vector trans[4], vector pos, float dx=0, float dz=0, float fAngle=0, bool align=false)
proto native void RegisterNetSyncVariableBool (string variableName)
registers bool variable synchronized over network
proto native void RegisterNetSyncVariableBoolSignal (string variableName)
when bool variable is true, it's sent to clients and become false again
proto native void RegisterNetSyncVariableInt (string variableName, int minValue=0, int maxValue=0)
registers int variable synchronized over network
proto native void RegisterNetSyncVariableFloat (string variableName, float minValue=0, float maxValue=0, int precision=1)
registers float variable synchronized over network
proto native void RegisterNetSyncVariableObject (string variableName)
registers object variable synchronized over network, only synchronizes if network id is assigned. Doesn't handle object despawn on client
proto native void UpdateNetSyncVariableInt (string variableName, float minValue=0, float maxValue=0)
proto native void UpdateNetSyncVariableFloat (string variableName, float minValue=0, float maxValue=0, int precision=1)
proto native void SwitchLight (bool isOn)
proto native void SetSimpleHiddenSelectionState (int index, bool state)
Simple hidden selection state; 0 == hidden.
proto native bool IsSimpleHiddenSelectionVisible (int index)
proto native void SetObjectTexture (int index, string texture_name)
Change texture in hiddenSelections.
proto native owned string GetObjectTexture (int index)
proto native void SetObjectMaterial (int index, string mat_name)
Change material in hiddenSelections.
proto native owned string GetObjectMaterial (int index)
proto native bool IsPilotLight ()
proto native void SetPilotLight (bool isOn)
void OnStoreSave (ParamsWriteContext ctx)
Engine calls this function to collect data from entity to store for persistence (on server side).
bool OnStoreLoad (ParamsReadContext ctx, int version)
Called when data is loaded from persistence (on server side).
proto native void SetSynchDirty ()
Sets object synchronization dirty flag, which signalize that object wants to be synchronized (take effect only in MP on server side)
void OnVariablesSynchronized ()
Called on clients after receiving synchronization data from server.
bool IsVariableSet (int variable)
'true' if this variable has ever been changed from default
void SetVariableMask (int variable)
void RemoveItemVariable (int variable)
Removes variable from variable mask, making it appear as though the variable has never been changed from default.
void TransferVariablesFloat (array< float > float_vars)
array< float > GetVariablesFloat ()
void SaveVariables (ParamsWriteContext ctx)
bool LoadVariables (ParamsReadContext ctx, int version=-1)
void WriteVarsToCTX (ParamsWriteContext ctx)
Writes to storage CTX.
bool ReadVarsFromCTX (ParamsReadContext ctx, int version=-1)
Reads from storage CTX.
void SerializeNumericalVars (array< float > floats_out)
void DeSerializeNumericalVars (array< float > floats)
proto native void SetAITargetCallbacks (AbstractAITargetCallbacks callbacks)
override void EOnFrame (IEntity other, float timeSlice)
string GetDebugText ()
void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4)
void OnDebugButtonPressClient (int button_index)
void OnDebugButtonPressServer (int button_index)
Shape DebugBBoxDraw ()
void DebugBBoxSetColor (int color)
void DebugBBoxDelete ()
Shape DebugDirectionDraw (float distance=1)
void DebugDirectionSetColor (int color)
void DebugDirectionDelete ()
void HideSelection (string selection_name)
Hides selection of the given name. Must be configed in config.cpp and models.cfg.
void ShowSelection (string selection_name)
Shows selection of the given name. Must be configed in config.hpp and models.cfg.
proto void GetPersistentID (out int b1, out int b2, out int b3, out int b4)
proto native void SetLifetime (float fLifeTime)
Set (override) remaining economy lifetime (seconds)
proto native float GetLifetime ()
Get remaining economy lifetime (seconds)
proto native void IncreaseLifetime ()
Reset economy lifetime to default (seconds)
proto native void SetLifetimeMax (float fLifeTime)
Set (override) max economy lifetime per entity instance (seconds)
proto native float GetLifetimeMax ()
Get max economy lifetime per instance - default is from DB (seconds)
void IncreaseLifetimeUp ()
Reset economy lifetime to default across entity hierarchy all the way to the topmost entity.
ComponentBodyStaging GetCompBS ()
Use this to access Body Staging component on dead character. Returns NULL if the given object lacks such component.
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
float GetWetWeightModifier ()
float GetConfigWeightModified ()
int GetWeight ()
void ClearWeightDirty ()
void SetWeightDirty ()
float GetInventoryAndCargoWeight (bool forceRecalc=false)
protected float GetWeightSpecialized (bool forceRecalc=false)
returns weight of the entity in a way that's specific to the entity type and is internal to the weight system calculation, to obtain entity's weight, use the 'GetWeightEx' method instead
float GetWeightEx (bool forceRecalc=false)
returns overall weight of the entity, 'forceRecalc = true' is meant to be used only when debugging, using it in gameplay code is higly inadvisable as it bypasses the weight caching and has adverse effect on performance
void UpdateWeight (WeightUpdateType updateType=WeightUpdateType.FULL, float weightAdjustment=0)
float GetSingleInventoryItemWeightEx ()
void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
bool OnAction (int action_id, Man player, ParamsReadContext ctx)
string GetHitComponentForAI ()
Returns hit component for the Entity (overriden for each Type - PlayerBase, DayZInfected, DayZAnimal, etc.)
string GetDefaultHitComponent ()
returns default hit component for the Entity (overriden for each Type - PlayerBase, DayZInfected, DayZAnimal, etc.)
string GetDefaultHitPositionComponent ()
returns default hit position component name for the Entity (overriden by type if needed - used mainly as support for impact particles)
array< string > GetSuitableFinisherHitComponents ()
vector GetDefaultHitPosition ()
int GetMeleeTargetType ()
value is related to EMeleeTargetType
string GetAttachmentSoundType ()
returns sound type of attachment (used for clothing and weapons on DayZPlayerImplement, paired with Anim*Type enum from DayZAnimEvents)
bool IsHeavyBehaviour ()
returns item behaviour of item (more in ItemBase)
bool IsOneHandedBehaviour ()
returns item behaviour of item (more in ItemBase)
bool IsTwoHandedBehaviour ()
returns item behaviour of item (more in ItemBase)
string ChangeIntoOnAttach (string slot)
string ChangeIntoOnDetach ()
bool CanHaveTemperature ()
returns true used on selected items that have a temperature effect and can processes temperature changes
bool IsSelfAdjustingTemperature ()
void OnCEUpdate ()
Central economy calls this function whenever going over all the entities.
void ProcessVariables ()
void OnDebugSpawnEx (DebugSpawnParams params)
void OnDebugSpawn ()
override EntityAI ProcessMeleeItemDamage (int mode=0)
float GetLiquidThroughputCoef ()
Returns liquid throughput coeficient.
string GetInvulnerabilityTypeString ()
void ProcessInvulnerabilityCheck (string servercfg_param)
void SetBayonetAttached (bool pState, int slot_idx=-1)
bool HasBayonetAttached ()
int GetBayonetAttachmentIdx ()
void SetButtstockAttached (bool pState, int slot_idx=-1)
bool HasButtstockAttached ()
int GetButtstockAttachmentIdx ()
void SetInvisibleRecursive (bool invisible, EntityAI parent=null, array< int > attachments=null)
void SoundHardTreeFallingPlay ()
void SoundSoftTreeFallingPlay ()
void SoundHardBushFallingPlay ()
void SoundSoftBushFallingPlay ()
void RegisterTransportHit (Transport transport)
bool GetInventoryHandAnimation (notnull InventoryLocation loc, out int value)
bool TranslateSlotFromSelection (string selection_name, out int slot_id)
bool IsUniversalTemperatureSource ()
Universal Temperature Sources Helpers.
UTemperatureSource GetUniversalTemperatureSource ()
void SetUniversalTemperatureSource (UTemperatureSource uts)
vector GetUniversalTemperatureSourcePosition ()
RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
Remotely controlled devices helpers.
void PairRemote (notnull EntityAI trigger)
void UnpairRemote ()
EntityAI GetPairDevice ()
void SetPersistentPairID (int id)
bool HasTurnableValveBehavior ()
Turnable Valve behaviour.
bool IsValveTurnable (int pValveIndex)
int GetTurnableValveIndex (int pComponentIndex)
void ExecuteActionsConnectedToValve (int pValveIndex)
private void InitAttachmentExclusionValues ()
private void InitInherentSlotExclusionMap ()
map stored on instance to better respond to various state changes
protected set< int > GetAttachmentExclusionInitSlotValue (int slotId)
override this to modify slot behavior for specific items, or just set 'm_AttachmentExclusionMaskGlobal' value for simple items
protected void InitLegacyConfigExclusionValues ()
protected bool InitLegacyExclusionCheck ()
protected void InitLegacySlotExclusionValuesImplicit ()
adding base one-directional relations between headgear, masks, eyewear, and headstraps (exception)
protected void InitLegacySlotExclusionValuesDerived ()
protected void InitGlobalExclusionValues ()
override to init part of the mask, independent of slot-specific behavior
protected void AddSingleExclusionValueGlobal (EAttExclusions value)
to help with item staging exclusions
protected void ClearSingleExclusionValueGlobal (EAttExclusions value)
to help with item staging exclusions
protected void SetAttachmentExclusionMaskGlobal (set< int > values)
protected void SetAttachmentExclusionMaskSlot (int slotId, set< int > values)
sets values for specific slot
private void PropagateExclusionValueRecursive (set< int > values, int slotId)
private void ClearExclusionValueRecursive (set< int > values, int slotId)
set< int > GetAttachmentExclusionMaskAll (int slotId)
Slot-specific, children (attachments), and additional (state etc.) masks combined.
set< int > GetAttachmentExclusionMaskSlot (int slotId)
Specific slot behavior.
set< int > GetAttachmentExclusionMaskGlobal ()
Global mask value, independent of slot-specific behavior!
set< int > GetAttachmentExclusionMaskChildren ()
Mask value coming from the item's attachments.
private bool HasInternalExclusionConflicts (int targetSlot)
checks if any attachment or item state would interfere with this being attached into a different slot (Headgear -> Mask)
protected bool IsExclusionFlagPresent (set< int > values)
checks 'this' if the incoming flag is present for the current state (slot behavior and others)
protected bool IsExclusionFlagPresentRecursive (set< int > values, int targetSlot)
Gets flag from what is effectively an owner.
protected bool CheckExclusionAccessCondition (int occupiedSlot, int targetSlot, set< int > value, inout set< int > adjustedValue)
protected void AdjustExclusionAccessCondition (int occupiedSlot, int testedSlot, set< int > value, inout set< int > adjustedValue)
if we want to filter
protected bool CheckExclusionAccessPropagation (int occupiedSlot, int targetSlot, set< int > value, inout set< int > adjustedValue)
special propagation contition
protected void AdjustExclusionAccessPropagation (int occupiedSlot, int testedSlot, set< int > value, inout set< int > adjustedValue)
if we want to filter propagation specifically; DO NOT override unless you know what you are doing.
bool IsManagingArrows ()
ArrowManagerBase GetArrowManager ()
void SetFromProjectile (ProjectileStoppedInfo info)
void ClearInventory ()
proto native void SetLightType (int pType)
proto native int GetLightType ()
proto native void SetEnabled (bool pState)
proto native bool IsEnabled ()
proto native void SetCastShadow (bool pState)
proto native bool GetCastShadow ()
proto native bool EnableSpecular (bool pState)
proto native bool EnableLinear (bool pState)
proto native void SetPulseCoef (float pState)
proto native void SetVisibleDuringDaylight (bool pState)
proto native bool IsVisibleDuringDaylight ()
proto native void SetRadius (float pValue)
proto native float GetRadius ()
proto native void EnableHeatHaze (bool pState)
proto native void SetHeatHazeRadius (float pValue)
proto native float GetHeatHazeRadius ()
proto native void SetHeatHazePower (float pValue)
proto native float GetHeatHazePower ()
proto native void SetDiffuseColor (float pRed, float pGreen, float pBlue)
proto native void SetDiffuseColorV (vector pColorVector)
proto native void SetDiffuseAlpha (float pAlpha)
proto native vector GetDiffuseColorV ()
proto native float GetDiffuseAlpha ()
proto native void SetAmbientColor (float pRed, float pGreen, float pBlue)
proto native void SetAmbientColorV (vector pColorVector)
proto native void SetAmbientAlpha (float pAlpha)
proto native vector GetAmbientColorV ()
proto native float GetAmbientAlpha ()
proto native void SetBrightness (float pValue)
proto native float GetBrightness ()
proto native void SetFlareVisible (bool pState)
proto native bool IsFlareVisible ()
proto native void SetFlareRelPosition (vector pPosition)
proto native vector GetFlareRelPosition ()
proto native void SetSpotLightAngle (float pValue)
proto native float GetSpotLightAngle ()
proto native float GetSoundLength ()
bool IsSkinned ()
Skinning.
void SetAsSkinned ()
bool CanBeSkinnedWith (EntityAI tool)
ComponentEnergyManager GetCompEM ()
bool HasEnergyManager ()
If this item has class EnergyManager in its config then it returns true. Otherwise returns false.
void OnWorkStart ()
Energy manager event: Called only once when this device starts doing its work.
void OnWork (float consumed_energy)
Energy manager event: Called every device update if its supposed to do some work. The update can be every second or at random, depending on its manipulation.
void OnWorkStop ()
Energy manager event: Called when the device stops working (was switched OFF or ran out of energy)
void OnSwitchOn ()
Energy manager event: Called when the device is switched on.
void OnSwitchOff ()
Energy manager event: Called when the device is switched OFF.
void OnIsPlugged (EntityAI source_device)
Energy manager event: Called when this device is plugged into some energy source.
void OnIsUnplugged (EntityAI last_energy_source)
Energy manager event: Called when this device is UNPLUGGED from the energy source.
void OnOwnSocketTaken (EntityAI device)
Energy manager event: When something is plugged into this device.
void OnOwnSocketReleased (EntityAI device)
Energy manager event: When something is UNPLUGGED from this device.
void OnInitEnergy ()
Energy manager event: Object's initialization. Energy Manager is fully initialized by this point.
void OnEnergyConsumed ()
Energy manager event: Called when energy was consumed on this device. ALWAYS CALL super.OnEnergyConsumed() !!!
void OnEnergyAdded ()
Energy manager event: Called when energy was added on this device. ALWAYS CALL super.OnEnergyAdded() !!!
Static Private Member Functions
static proto native Camera GetCurrentCamera ()
Returns active Camera instance (note: player's camera is not Camera instance - thus it return null)
static proto native float GetCurrentFOV ()
Returns FOV of current camera object.
static proto native void InterpolateTo (Camera targetCamera, float time, int type)
Interpolation between camera instances (current camera becomes targetCamera at the end of interpolation)
static EWetnessLevel GetWetLevelInternal (float wetness)
Private Attributes
bool m_DeathSyncSent
bool m_KilledByHeadshot
bool m_PreparedToDelete = false
bool m_RefresherViable = false
bool m_WeightDirty = 1
protected bool m_RoofAbove = false
private ref map< int, ref set< int > > m_AttachmentExclusionSlotMap
private ref set< int > m_AttachmentExclusionMaskGlobal
private ref set< int > m_AttachmentExclusionMaskChildren
ref DestructionEffectBase m_DestructionBehaviourObj
ref KillerData m_KillerData
private ref HiddenSelectionsData m_HiddenSelectionsData
const int DEAD_REPLACE_DELAY = 250
const int DELETE_CHECK_DELAY = 100
ref array< EntityAI > m_AttachmentsWithCargo
ref array< EntityAI > m_AttachmentsWithAttachments
ref InventoryLocation m_OldLocation
protected ref DamageZoneMap m_DamageZoneMap
private ref map< int, string > m_DamageDisplayNameMap = new map<int, string>
float m_Weight
float m_WeightEx
float m_ConfigWeight = ConfigGetInt("weight")
protected bool m_CanDisplayWeight
private float m_LastUpdatedTime
protected float m_ElapsedSinceLastUpdate
protected float m_PreviousRoofTestTime = 0
protected UTemperatureSource m_UniversalTemperatureSource
bool m_PendingDelete = false
bool m_Initialized = false
bool m_TransportHitRegistered = false
vector m_TransportHitVelocity
int m_VariablesMask
float m_VarTemperature
float m_VarTemperatureInit
float m_VarTemperatureMin
float m_VarTemperatureMax
float m_VarTemperatureFreezeThreshold
float m_VarTemperatureThawThreshold
float m_VarTemperatureFreezeTime
float m_VarTemperatureThawTime
float m_VarTemperatureOverheatTime
float m_VarHeatPermeabilityCoef
protected ref TemperatureAccessComponent m_TAC
protected bool m_IsFrozen
protected bool m_IsFrozenLocal
protected float m_FreezeThawProgress
protected float m_OverheatProgress
protected ref ScriptInvoker m_OnItemAttached
protected ref ScriptInvoker m_OnItemDetached
protected ref ScriptInvoker m_OnItemAddedIntoCargo
protected ref ScriptInvoker m_OnItemRemovedFromCargo
protected ref ScriptInvoker m_OnItemMovedInCargo
protected ref ScriptInvoker m_OnItemFlipped
protected ref ScriptInvoker m_OnViewIndexChanged
protected ref ScriptInvoker m_OnSetLock
protected ref ScriptInvoker m_OnReleaseLock
protected ref ScriptInvoker m_OnAttachmentSetLock
protected ref ScriptInvoker m_OnAttachmentReleaseLock
protected ref ScriptInvoker m_OnHitByInvoker
protected ref ScriptInvoker m_OnKilledInvoker
private ref ComponentsBank m_ComponentsBank
ComponentEnergyManager m_EM
int m_ViewIndex = 0
void SetViewIndex (int index)
Sets item preview index.
int GetViewIndex ()
Returns item preview index !!!! IF OVERRIDING with more dynamic events call GetOnViewIndexChanged() in constructor on client !!!!
Constructor & Destructor Documentation
~EntityAI()
void ~EntityAI () inline private
Member Function Documentation
AddSingleExclusionValueGlobal()
protected void AddSingleExclusionValueGlobal (EAttExclusions value) inline private
to help with item staging exclusions
AddTemperature()
void AddTemperature (float value) inline private
AddWet()
void AddWet (float value) private
AdjustExclusionAccessCondition()
protected void AdjustExclusionAccessCondition (int occupiedSlot, int testedSlot, set< int > value, inout set< int > adjustedValue) inline private
if we want to filter
AdjustExclusionAccessPropagation()
protected void AdjustExclusionAccessPropagation (int occupiedSlot, int testedSlot, set< int > value, inout set< int > adjustedValue) inline private
if we want to filter propagation specifically; DO NOT override unless you know what you are doing.
AfterStoreLoad()
void AfterStoreLoad () inline private
Called when entity is being loaded from DB or Storage (after all children loaded)
AreChildrenAccessible()
bool AreChildrenAccessible () inline private
References InventoryLocation::GetType(), GameConstants::INVENTORY_MAX_REACHABLE_DEPTH_ATT, and InventoryLocation::IsValid().
AttemptDestructionBehaviour()
void AttemptDestructionBehaviour (int oldLevel, int newLevel, string zone) inline private
References ErrorEx, GetDestructionBehaviour(), IsDestructionBehaviour(), and DestructionEffectBase::OnHealthLevelChanged().
CanAssignAttachmentsToQuickbar()
CanAssignAttachmentsToQuickbar () inline private
Returns
true if attached item can be assigned to quickbar safely
CanAssignToQuickbar()
CanAssignToQuickbar () inline private
Returns
true if item can be assigned to quickbar safely
CanBeActionTarget()
override bool CanBeActionTarget () inline private
CanBeBackstabbed()
bool CanBeBackstabbed () inline private
CanBeCombined()
bool CanBeCombined (EntityAI other_item, bool reservation_check = true, bool stack_max_limit = false) inline private
CanBeFSwaped()
bool CanBeFSwaped () inline private
CanBeIgnitedBy()
bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Override this method so it checks whenever this item can be ignited right now or not. Evaluated on Server and Client.
CanBePlaced()
bool CanBePlaced (Man player, vector position) inline private
CanBePlacedFailMessage()
string CanBePlacedFailMessage (Man player, vector position) inline private
Method which returns message why object can't be placed at given position.
CanBeSkinnedWith()
bool CanBeSkinnedWith (EntityAI tool) inline private
CanBeSplit()
bool CanBeSplit () inline private
returns current splitability
CanBeTargetedByAI()
bool CanBeTargetedByAI (EntityAI ai) inline private
References dBodyIsActive(), and EntityAI::IsMan().
CanCombineAttachment()
bool CanCombineAttachment (notnull EntityAI e, int slot, bool stack_max_limit = false) inline private
CanDetachAttachment()
CanDetachAttachment (EntityAI parent) inline private
calls this->CanDetachAttachment(parent)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, parent, "CanDetachAttachment");
CanDisplayAnyAttachmentSlot()
CanDisplayAnyAttachmentSlot () inline private
Returns
true if any attachment slot can be shown
References CanDisplayAttachmentSlot().
CanDisplayAttachmentCategory()
CanDisplayAttachmentCategory (string category_name) inline private
Parameters
category_name->name of the attachment category that will or won't be displayed
Returns
true if attachment icon can be displayed in UI (inventory)
CanDisplayAttachmentSlot() [1/2]
bool CanDisplayAttachmentSlot (int slot_id) inline private
References InventorySlots::GetShowForSlotId().
CanDisplayAttachmentSlot() [2/2]
bool CanDisplayAttachmentSlot (string slot_name) inline private
References InventorySlots::GetShowForSlotId(), InventorySlots::GetSlotIdFromString(), and Debug::LogWarning().
CanDisplayCargo()
CanDisplayCargo () inline private
Returns
true if cargo can be displayed in UI (inventory)
CanDisplayWeight()
bool CanDisplayWeight () inline private
'displayWeight' in item config
CanDropEntity()
bool CanDropEntity (notnull EntityAI item) inline private
Returns if item can be dropped out from this entity.
CanFreeze()
bool CanFreeze () inline private
References CanHaveTemperature(), GetTemperatureFreezeThreshold(), and GetTemperatureThawThreshold().
CanHaveTemperature()
bool CanHaveTemperature () inline private
returns true used on selected items that have a temperature effect and can processes temperature changes
CanIgniteItem()
bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Override this method and check if the given item can be ignited right now by this one. Evaluated on Server and Client.
CanItemOverheat()
bool CanItemOverheat () inline private
Overheat time CAN be 0, GameConstants.TEMPERATURE_TIME_OVERHEAT_MIN is ignored if so.
CanLoadAttachment()
bool CanLoadAttachment (EntityAI attachment) inline private
CanLoadItemIntoCargo()
CanLoadItemIntoCargo (EntityAI item) inline private
calls this->CanLoadItemIntoCargo(item), is called on server start when loading in the storage
Returns
true if action allowed
Note
: return scriptConditionExecute(this, item, "CanLoadItemIntoCargo");
CanPutAsAttachment()
CanPutAsAttachment (EntityAI parent) inline private
calls this->CanPutAsAttachment(parent)
Parameters
[in] parent target entity this is trying to attach to
Returns
true if action allowed
Note
: engine code is scriptConditionExecute(this, parent, "CanPutAsAttachment")
References IsHologram().
CanPutInCargo()
CanPutInCargo (EntityAI parent) inline private
calls this->CanPutInCargo(parent)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, parent, "CanPutInCargo");
References IsHologram().
CanPutIntoHands()
CanPutIntoHands (EntityAI parent) inline private
calls this->CanPutIntoHands(parent)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, parent, "CanPutIntoHands");
References IsHologram().
CanReceiveAttachment()
CanReceiveAttachment (EntityAI attachment, int slotId) inline private
calls this->CanReceiveAttachment(attachment)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, attachment, "CanReceiveAttachment");
References InventoryLocation::GetSlot(), and InventoryLocation::GetType().
CanReceiveItemIntoCargo()
CanReceiveItemIntoCargo (EntityAI item) inline private
calls this->CanReceiveItemIntoCargo(item)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, item, "CanReceiveItemIntoCargo");
CanReceiveItemIntoHands()
CanReceiveItemIntoHands (EntityAI item_to_hands) inline private
calls this->CanReceiveItemIntoHands(item_to_hands)
Returns
true if action allowed
Note
: scriptConditionExecute(this, item_to_hands, "CanReceiveItemIntoHands");
CanReleaseAttachment()
CanReleaseAttachment (EntityAI attachment) inline private
calls this->CanReleaseAttachment(attachment)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, attachment, "CanReleaseAttachment");
References InventoryLocation::GetSlot(), and InventoryLocation::IsValid().
CanReleaseCargo()
CanReleaseCargo (EntityAI cargo) inline private
calls this->CanReleaseCargo(cargo)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, cargo, "CanReleaseCargo");
CanReleaseFromHands()
CanReleaseFromHands (EntityAI handheld) inline private
calls this->CanReleaseFromHands(handheld)
Returns
true if action allowed
Note
: scriptConditionExecute(this, handheld, "CanReleaseFromHands");
CanRemoveFromCargo()
CanRemoveFromCargo (EntityAI parent) inline private
calls this->CanRemoveFromCargo(parent)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, parent, "CanRemoveFromCargo");
CanRemoveFromHands()
CanRemoveFromHands (EntityAI parent) inline private
calls this->CanRemoveFromHands(parent)
Returns
true if action allowed
Note
: return scriptConditionExecute(this, parent, "CanRemoveFromHands");
CanSaveItemInHands()
bool CanSaveItemInHands (EntityAI item_in_hands) inline private
CanSwapEntities()
bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination) inline private
CanSwapItemInCargo()
CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity) inline private
calls this->CanSwapItemInCargo(child_entity, new_entity)
Returns
true if action allowed
Note
: return ScriptConditionExecute(GetOwner(), child_entity, "CanSwapItemInCargo", new_entity);
CanSwitchDuringAttach()
bool CanSwitchDuringAttach (EntityAI parent) inline private
ChangeIntoOnAttach()
string ChangeIntoOnAttach (string slot) inline private
ChangeIntoOnDetach()
string ChangeIntoOnDetach () inline private
CheckExclusionAccessCondition()
protected bool CheckExclusionAccessCondition (int occupiedSlot, int targetSlot, set< int > value, inout set< int > adjustedValue) inline private
CheckExclusionAccessPropagation()
protected bool CheckExclusionAccessPropagation (int occupiedSlot, int targetSlot, set< int > value, inout set< int > adjustedValue) inline private
special propagation contition
References InventorySlots::INVALID.
CheckForDestroy()
void CheckForDestroy () inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and IsPrepareToDelete().
CheckForRoofLimited()
void CheckForRoofLimited (float timeTresholdMS = 3000) private
Roof check for entity, limited by time (anti-spam solution)
ClearExclusionValueRecursive()
private void ClearExclusionValueRecursive (set< int > values, int slotId) inline private
References InventoryLocation::GetSlot().
ClearInventory()
void ClearInventory () private
ClearSingleExclusionValueGlobal()
protected void ClearSingleExclusionValueGlobal (EAttExclusions value) inline private
to help with item staging exclusions
ClearWeightDirty()
void ClearWeightDirty () inline private
CombineItemsClient()
void CombineItemsClient (EntityAI entity2, bool use_stack_max = false) inline private
CombineItemsEx()
void CombineItemsEx (EntityAI entity2, bool use_stack_max = false) private
ConvertNonlethalDamage() [1/2]
float ConvertNonlethalDamage (float damage) inline private
DEPRECATED - for legacy purposes.
ConvertNonlethalDamage() [2/2]
protected float ConvertNonlethalDamage (float damage, DamageType damageType) inline private
CreateAndInitInventory()
proto native void CreateAndInitInventory () private
CreateComponent()
Component CreateComponent (int comp_type, string extended_class_name = "") inline private
CreateComponent.
DeathUpdate()
void DeathUpdate () inline private
References ECE_OBJECT_SWAP, GetDeadItemName(), GetGame(), GetOrientation(), GetPosition, KeepHealthOnReplace(), and RF_ORIGINAL.
DebugBBoxDelete()
void DebugBBoxDelete () inline private
References COMP_TYPE_ETITY_DEBUG.
DebugBBoxDraw()
Shape DebugBBoxDraw () inline private
References COMP_TYPE_ETITY_DEBUG.
DebugBBoxSetColor()
void DebugBBoxSetColor (int color) inline private
References COMP_TYPE_ETITY_DEBUG.
DebugDirectionDelete()
void DebugDirectionDelete () inline private
References COMP_TYPE_ETITY_DEBUG.
DebugDirectionDraw()
Shape DebugDirectionDraw (float distance = 1) inline private
References COMP_TYPE_ETITY_DEBUG.
DebugDirectionSetColor()
void DebugDirectionSetColor (int color) inline private
References COMP_TYPE_ETITY_DEBUG.
DeferredInit()
void DeferredInit () inline private
References m_Initialized.
Delete()
override void Delete () inline private
Delete this object in next frame.
Returns
void
ItemBase item = GetGame().GetPlayer().CreateInInventory("GrenadeRGD5");
item.Delete();
DeleteComponent()
bool DeleteComponent (int comp_type) inline private
DeleteComponent.
DeleteOnClient()
void DeleteOnClient () inline private
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), and GetGame().
DeleteSafe()
void DeleteSafe () inline private
References GetGame().
DeleteSave()
void DeleteSave () inline private
DeSerializeNumericalVars()
void DeSerializeNumericalVars (array< float > floats) inline private
References Math::Round(), and VARIABLE_TEMPERATURE.
DestroyInventory()
proto native void DestroyInventory () private
DisassembleOnLastDetach()
bool DisassembleOnLastDetach () inline private
DoPlacingHeightCheck()
bool DoPlacingHeightCheck () inline private
Do the roof check when placing this?
EEAmmoChanged()
void EEAmmoChanged () inline private
EECargoIn()
void EECargoIn (EntityAI item) inline private
EECargoMove()
void EECargoMove (EntityAI item) inline private
EECargoOut()
void EECargoOut (EntityAI item) inline private
EEDelete()
void EEDelete (EntityAI parent) inline private
Called right before object deleting.
References ComponentEnergyManager::OnDeviceDestroyed().
EEHealthLevelChanged()
void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
References OnDamageDestroyed(), and GameConstants::STATE_RUINED.
EEHitBy()
void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
References component.
EEHitByRemote()
void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos) inline private
EEInit()
void EEInit () inline private
Called upon object creation.
References CanHaveTemperature(), and GetGame().
EEInventoryIn()
void EEInventoryIn (Man newParentMan, EntityAI diz, EntityAI newParent) inline private
EEInventoryOut()
void EEInventoryOut (Man oldParentMan, EntityAI diz, EntityAI newParent) inline private
References GetGame(), and CGame::GetTickTime().
EEItemAttached()
void EEItemAttached (EntityAI item, string slot_name) inline private
References COMP_TYPE_COUNT, InventorySlots::GetSlotIdFromString(), and ComponentEnergyManager::OnAttachmentAdded().
EEItemDetached()
void EEItemDetached (EntityAI item, string slot_name) inline private
References COMP_TYPE_COUNT, InventorySlots::GetSlotIdFromString(), and ComponentEnergyManager::OnAttachmentRemoved().
EEItemLocationChanged()
void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
References Error(), OnItemAttachmentSlotChanged(), OnItemLocationChanged(), OnWasAttached(), and OnWasDetached().
EEKilled()
void EEKilled (Object killer) inline private
called on server when the entity is killed
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), DeathUpdate(), CGame::GetAnalyticsServer(), CGame::GetCallQueue(), GetGame(), AnalyticsManagerServer::OnEntityKilled(), and ReplaceOnDeath().
EEOnAfterLoad()
void EEOnAfterLoad () inline private
Called when entity is part of "connected system" and being restored after load.
References ComponentEnergyManager::GetEnergySourceStorageIDb1(), ComponentEnergyManager::GetEnergySourceStorageIDb2(), ComponentEnergyManager::GetEnergySourceStorageIDb3(), ComponentEnergyManager::GetEnergySourceStorageIDb4(), CGame::GetEntityByPersitentID(), GetGame(), ComponentEnergyManager::GetRestorePlugState(), and ComponentEnergyManager::PlugThisInto().
EEOnCECreate()
void EEOnCECreate () inline private
Called when entity is being created as new by CE/ Debug.
EEParentedFrom()
void EEParentedFrom (EntityAI parent) inline private
Called from 'IEntity.RemoveChild' or 'IEntity.AddChild' when hierarchy changes.
EEParentedTo()
void EEParentedTo (EntityAI parent) inline private
Called from 'IEntity.AddChild'.
EnableHeatHaze()
proto native void EnableHeatHaze (bool pState) private
EnableLinear()
proto native bool EnableLinear (bool pState) private
EnableSpecular()
proto native bool EnableSpecular (bool pState) private
EntityAI()
void EntityAI () inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), COMP_TYPE_ENERGY_MANAGER, CGame::ConfigIsExisting(), CGame::GetCallQueue(), GetGame(), GetType(), and InitItemVariables().
EOnFrame()
override void EOnFrame (IEntity other, float timeSlice) inline private
References COMP_TYPE_COUNT.
ExecuteActionsConnectedToValve()
void ExecuteActionsConnectedToValve (int pValveIndex) private
FindAttachmentBySlotName()
EntityAI FindAttachmentBySlotName (string slot_name) inline private
References GetGame(), InventorySlots::GetSlotIdFromString(), and InventorySlots::INVALID.
GetAgents()
int GetAgents () inline private
GetAmbientAlpha()
proto native float GetAmbientAlpha () private
GetAmbientColorV()
proto native vector GetAmbientColorV () private
GetArrowManager()
ArrowManagerBase GetArrowManager () inline private
GetAttachmentByConfigTypeName()
EntityAI GetAttachmentByConfigTypeName (string type) inline private
Get attached entity by config type name.
GetAttachmentByType()
EntityAI GetAttachmentByType (typename type) inline private
Get attached entity by type.
GetAttachmentExclusionInitSlotValue()
protected set< int > GetAttachmentExclusionInitSlotValue (int slotId) inline private
override this to modify slot behavior for specific items, or just set 'm_AttachmentExclusionMaskGlobal' value for simple items
GetAttachmentExclusionMaskAll()
set< int > GetAttachmentExclusionMaskAll (int slotId) inline private
Slot-specific, children (attachments), and additional (state etc.) masks combined.
GetAttachmentExclusionMaskChildren()
set< int > GetAttachmentExclusionMaskChildren () inline private
Mask value coming from the item's attachments.
GetAttachmentExclusionMaskGlobal()
set< int > GetAttachmentExclusionMaskGlobal () inline private
Global mask value, independent of slot-specific behavior!
GetAttachmentExclusionMaskSlot()
set< int > GetAttachmentExclusionMaskSlot (int slotId) inline private
Specific slot behavior.
GetAttachmentSoundType()
string GetAttachmentSoundType () inline private
returns sound type of attachment (used for clothing and weapons on DayZPlayerImplement, paired with Anim*Type enum from DayZAnimEvents)
GetAttachmentsWithAttachments()
array< EntityAI > GetAttachmentsWithAttachments () inline private
GetAttachmentsWithCargo()
array< EntityAI > GetAttachmentsWithCargo () inline private
GetBayonetAttachmentIdx()
int GetBayonetAttachmentIdx () inline private
GetBrightness()
proto native float GetBrightness () private
GetButtstockAttachmentIdx()
int GetButtstockAttachmentIdx () inline private
GetCastShadow()
proto native bool GetCastShadow () private
GetCleanness()
int GetCleanness () inline private
GetColor()
void GetColor (out int r, out int g, out int b, out int a) inline private
GetCompBS()
ComponentBodyStaging GetCompBS () inline private
Use this to access Body Staging component on dead character. Returns NULL if the given object lacks such component.
References COMP_TYPE_BODY_STAGING.
GetCompEM()
ComponentEnergyManager GetCompEM () inline private
energy manager ENERGY MANAGER:Documentation: Confluence >> Camping & Squatting >> Electricity >> Energy Manager functionalities Use this to access Energy Manager component on your device. Returns NULL if the given object lacks such component.
References COMP_TYPE_ENERGY_MANAGER.
GetComponent()
Component GetComponent (int comp_type, string extended_class_name = "") inline private
GetComponent.
GetConfigWeightModified()
float GetConfigWeightModified () inline private
GetCookingTargetTemperature()
bool GetCookingTargetTemperature (out float temperature) inline private
specifically for cooking system, to get heat source target temperatures
GetCurrentCamera()
static proto native Camera GetCurrentCamera () static private
Returns active Camera instance (note: player's camera is not Camera instance - thus it return null)
Returns
Camera active Camera instance
GetCurrentFOV()
static proto native float GetCurrentFOV () static private
Returns FOV of current camera object.
Returns
float FOV of current camera object
GetDeadItemName()
string GetDeadItemName () inline private
GetDebugActions()
void GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline private
References SAT_DEBUG_ACTION.
GetDebugButtonNames()
void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4) inline private
GetDebugText()
string GetDebugText () inline private
References string::Empty, ComponentEnergyManager::GetEnergySource(), ComponentEnergyManager::IsSwitchedOn(), and ComponentEnergyManager::IsWorking().
GetDefaultHitComponent()
string GetDefaultHitComponent () inline private
returns default hit component for the Entity (overriden for each Type - PlayerBase, DayZInfected, DayZAnimal, etc.)
returns Global so it is obvious you need to configure that properly on entity
References GetType(), and Debug::LogError().
GetDefaultHitPosition()
vector GetDefaultHitPosition () inline private
References GetType(), Debug::LogError(), and vector::Zero.
GetDefaultHitPositionComponent()
string GetDefaultHitPositionComponent () inline private
returns default hit position component name for the Entity (overriden by type if needed - used mainly as support for impact particles)
References GetType(), and Debug::LogError().
GetDestructionBehaviour()
string GetDestructionBehaviour () inline private
GetDiffuseAlpha()
proto native float GetDiffuseAlpha () private
GetDiffuseColorV()
proto native vector GetDiffuseColorV () private
GetEconomyProfile()
proto native CEItemProfile GetEconomyProfile () private
Get economy item profile (if assigned, otherwise null)
GetEntityDamageDisplayNameMap()
map< int, string > GetEntityDamageDisplayNameMap () inline private
GetEntityDamageZoneMap()
DamageZoneMap GetEntityDamageZoneMap () inline private
GetFlareRelPosition()
proto native vector GetFlareRelPosition () private
GetFreezeThawProgress()
float GetFreezeThawProgress () inline private
on server only
GetHeatHazePower()
proto native float GetHeatHazePower () private
GetHeatHazeRadius()
proto native float GetHeatHazeRadius () private
GetHeatPermeabilityCoef()
float GetHeatPermeabilityCoef () inline private
Returns temperature change speed multiplier for this item and all its children (multiplicative interaction)
Note
Values > 1 accelerate, values in <0,1) interval decelerate. Values < 0 should not be used here, but I'm not your mom.
GetHiddenSelectionIndex()
int GetHiddenSelectionIndex (string selection) inline private
Returns index of the string found in cfg array 'hiddenSelections'. If it's not found then it returns -1.
GetHiddenSelections()
override TStringArray GetHiddenSelections () inline private
Returns the hiddenSelectionsTextures array from the object's config.
GetHiddenSelectionsData()
HiddenSelectionsData GetHiddenSelectionsData () inline private
GetHiddenSelectionsMaterials()
override TStringArray GetHiddenSelectionsMaterials () inline private
Returns the hiddenSelectionsMaterials array from the object's config.
GetHiddenSelectionsTextures()
override TStringArray GetHiddenSelectionsTextures () inline private
Returns the hiddenSelectionsTextures array from the object's config.
GetHideIconMask()
int GetHideIconMask () inline private
should the item's icon be hidden in any part of the inventory?
GetHierarchyLevel()
int GetHierarchyLevel (int lvl = 0) inline private
GetHierarchyParent()
proto native EntityAI GetHierarchyParent () private
Returns direct parent of current entity.
GetHierarchyRoot()
proto native EntityAI GetHierarchyRoot () private
Returns root of current hierarchy (for example: if this entity is in Backpack on gnd, returns Backpack)
GetHierarchyRootPlayer()
proto native Man GetHierarchyRootPlayer () private
Returns root of current hierarchy cast to Man.
GetHitComponentForAI()
string GetHitComponentForAI () inline private
Returns hit component for the Entity (overriden for each Type - PlayerBase, DayZInfected, DayZAnimal, etc.)
returns Global so it is obvious you need to configure that properly on entity
References GetType(), and Debug::LogError().
GetInventory()
proto native GameInventory GetInventory () private
GetInventoryAndCargoWeight()
float GetInventoryAndCargoWeight (bool forceRecalc = false) inline private
References CargoBase::GetItem(), and CargoBase::GetItemCount().
GetInventoryHandAnimation()
bool GetInventoryHandAnimation (notnull InventoryLocation loc, out int value) inline private
GetInvulnerabilityTypeString()
string GetInvulnerabilityTypeString () inline private
GetIsFrozen()
bool GetIsFrozen () inline private
GetItemOverheatProgress()
float GetItemOverheatProgress () inline private
GetItemOverheatThreshold()
float GetItemOverheatThreshold () inline private
if undefined, max temperature used as default
GetItemOverheatTime()
float GetItemOverheatTime () inline private
any configured value >= 0 will simulate overheating
GetLifetime()
proto native float GetLifetime () private
Get remaining economy lifetime (seconds)
GetLifetimeMax()
proto native float GetLifetimeMax () private
Get max economy lifetime per instance - default is from DB (seconds)
GetLightType()
proto native int GetLightType () private
GetLiquidThroughputCoef()
float GetLiquidThroughputCoef () inline private
Returns liquid throughput coeficient.
References LIQUID_THROUGHPUT_DEFAULT.
GetLiquidType()
int GetLiquidType () inline private
GetMeleeTargetType()
int GetMeleeTargetType () inline private
value is related to EMeleeTargetType
GetNearPlane()
proto native float GetNearPlane () private
get near plane of camera
GetObjectMaterial()
proto native owned string GetObjectMaterial (int index) private
GetObjectTexture()
proto native owned string GetObjectTexture (int index) private
GetOnAttachmentReleaseLock()
ScriptInvoker GetOnAttachmentReleaseLock () inline private
GetOnAttachmentSetLock()
ScriptInvoker GetOnAttachmentSetLock () inline private
GetOnHitByInvoker()
ScriptInvoker GetOnHitByInvoker () inline private
GetOnItemAddedIntoCargo()
ScriptInvoker GetOnItemAddedIntoCargo () inline private
GetOnItemAttached()
ScriptInvoker GetOnItemAttached () inline private
GetOnItemDetached()
ScriptInvoker GetOnItemDetached () inline private
GetOnItemFlipped()
ScriptInvoker GetOnItemFlipped () inline private
GetOnItemMovedInCargo()
ScriptInvoker GetOnItemMovedInCargo () inline private
GetOnItemRemovedFromCargo()
ScriptInvoker GetOnItemRemovedFromCargo () inline private
GetOnKilledInvoker()
ScriptInvoker GetOnKilledInvoker () inline private
GetOnReleaseLock()
ScriptInvoker GetOnReleaseLock () inline private
GetOnSetLock()
ScriptInvoker GetOnSetLock () inline private
GetOnViewIndexChanged()
ScriptInvoker GetOnViewIndexChanged () inline private
GetPairDevice()
EntityAI GetPairDevice () private
GetPersistentID()
proto void GetPersistentID (out int b1, out int b2, out int b3, out int b4) private
Returns blocks of bits of persistence id of this entity. This id stays the same even after server restart.
GetQuantity()
float GetQuantity () inline private
GetQuantityMax()
int GetQuantityMax () inline private
GetQuantityMin()
int GetQuantityMin () inline private
GetQuantityNormalized()
float GetQuantityNormalized () inline private
GetQuickBarBonus()
int GetQuickBarBonus () inline private
GetRadius()
proto native float GetRadius () private
GetRemotelyActivatedItemBehaviour()
RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour () private
Remotely controlled devices helpers.
GetSingleInventoryItemWeightEx()
float GetSingleInventoryItemWeightEx () inline private
GetSlotsCountCorrect()
int GetSlotsCountCorrect () inline private
GetSoundLength()
proto native float GetSoundLength () private
GetSpotLightAngle()
proto native float GetSpotLightAngle () private
GetStoreLoadedQuantity()
float GetStoreLoadedQuantity () inline private
GetSuitableFinisherHitComponents()
array< string > GetSuitableFinisherHitComponents () inline private
References GetType(), and Debug::LogError().
GetTargetQuantityMax()
int GetTargetQuantityMax (int attSlotID = -1) inline private
GetTemperature()
float GetTemperature () inline private
GetTemperatureFreezeThreshold()
float GetTemperatureFreezeThreshold () inline private
GetTemperatureFreezeTime()
float GetTemperatureFreezeTime () inline private
GetTemperatureInit()
float GetTemperatureInit () inline private
GetTemperatureMax()
float GetTemperatureMax () inline private
GetTemperatureMin()
float GetTemperatureMin () inline private
GetTemperatureThawThreshold()
float GetTemperatureThawThreshold () inline private
GetTemperatureThawTime()
float GetTemperatureThawTime () inline private
GetTurnableValveIndex()
int GetTurnableValveIndex (int pComponentIndex) private
GetUniversalTemperatureSource()
UTemperatureSource GetUniversalTemperatureSource () inline private
GetUniversalTemperatureSourcePosition()
vector GetUniversalTemperatureSourcePosition () inline private
References GetPosition.
GetVariablesFloat()
array< float > GetVariablesFloat () inline private
References CachedObjectsArrays::ARRAY_FLOAT, and SerializeNumericalVars().
GetViewIndex()
int GetViewIndex () inline private
Returns item preview index !!!! IF OVERRIDING with more dynamic events call GetOnViewIndexChanged() in constructor on client !!!!
References InventoryLocation::GetType().
GetWeight()
int GetWeight () inline private
GetWeightEx()
float GetWeightEx (bool forceRecalc = false) inline private
returns overall weight of the entity, 'forceRecalc = true' is meant to be used only when debugging, using it in gameplay code is higly inadvisable as it bypasses the weight caching and has adverse effect on performance
References DumpStack(), GetWeightSpecialized(), and Print().
GetWeightSpecialized()
protected float GetWeightSpecialized (bool forceRecalc = false) inline private
returns weight of the entity in a way that's specific to the entity type and is internal to the weight system calculation, to obtain entity's weight, use the 'GetWeightEx' method instead
GetWet()
float GetWet () inline private
GetWetInit()
float GetWetInit () inline private
GetWetLevel()
EWetnessLevel GetWetLevel () private
GetWetLevelInternal()
static EWetnessLevel GetWetLevelInternal (float wetness) inline static private
References GameConstants::STATE_DAMP, GameConstants::STATE_DRENCHED, GameConstants::STATE_SOAKING_WET, and GameConstants::STATE_WET.
GetWetMax()
float GetWetMax () inline private
GetWetMin()
float GetWetMin () inline private
GetWetWeightModifier()
float GetWetWeightModifier () inline private
References GetWetLevel(), and CfgGameplayHandler::GetWetnessWeightModifiers().
HandleFreezingProgression()
protected void HandleFreezingProgression (float deltaHeat, TemperatureData data) inline private
References Math::Clamp(), GetTemperatureFreezeTime(), GetTemperatureThawTime(), Math::Lerp(), TemperatureData::m_InterpolatedFraction, TemperatureData::m_UpdateTimeCoef, TemperatureData::m_UpdateTimeInfo, Math::Max(), GameConstants::TEMP_COEF_COOLING_GLOBAL, GameConstants::TEMPERATURE_FREEZETHAW_LEGACY_COEF, GameConstants::TEMPERATURE_RATE_AVERAGE_ABS, GameConstants::TEMPERATURE_SENSITIVITY_THRESHOLD, GameConstants::TEMPERATURE_TIME_FREEZE_MIN, and GameConstants::TEMPERATURE_TIME_THAW_MIN.
HandleItemOverheating()
protected void HandleItemOverheating (float deltaHeat, TemperatureData data) inline private
References Math::Clamp(), Math::Lerp(), TemperatureData::m_InterpolatedFraction, TemperatureData::m_UpdateTimeInfo, Math::Max(), GameConstants::TEMPERATURE_RATE_AVERAGE_ABS, and GameConstants::TEMPERATURE_TIME_OVERHEAT_MIN.
HasAnyCargo()
bool HasAnyCargo () inline private
is this container empty or not, checks only cargo
References CargoBase::GetItemCount().
HasBayonetAttached()
bool HasBayonetAttached () inline private
HasButtstockAttached()
bool HasButtstockAttached () inline private
HasComponent()
bool HasComponent (int comp_type) inline private
IsComponentExist.
HasEnergyManager()
bool HasEnergyManager () inline private
If this item has class EnergyManager in its config then it returns true. Otherwise returns false.
References COMP_TYPE_ENERGY_MANAGER.
HasFlammableMaterial()
bool HasFlammableMaterial () inline private
Override this method to return TRUE when this item has or can provide fire. Evaluated on server and client.
HasInternalExclusionConflicts()
private bool HasInternalExclusionConflicts (int targetSlot) inline private
checks if any attachment or item state would interfere with this being attached into a different slot (Headgear -> Mask)
HasQuantity()
bool HasQuantity () inline private
HasTurnableValveBehavior()
bool HasTurnableValveBehavior () private
Turnable Valve behaviour.
HasWetness()
bool HasWetness () inline private
References GetWetMax(), and GetWetMin().
HeightCheckOverride()
float HeightCheckOverride () inline private
used as script-side override of distance for specific height checks
HeightStartCheckOverride()
float HeightStartCheckOverride () inline private
used as script-side override of start pos for specific height checks
HideAllSelections()
void HideAllSelections () inline private
Sets all animation values to 1, making them INVISIBLE if they are configured in models.cfg in such way. These selections must also be defined in the entity's config class in 'AnimationSources'.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), and GetType().
HideSelection()
void HideSelection (string selection_name) inline private
Hides selection of the given name. Must be configed in config.cpp and models.cfg.
IgnoreOutOfReachCondition()
IgnoreOutOfReachCondition () inline private
Returns
if true, attachment condition for out of reach (inventory) will be ignored
References GetGame(), and CGame::GetPlayer().
IncreaseLifetime()
proto native void IncreaseLifetime () private
Reset economy lifetime to default (seconds)
IncreaseLifetimeUp()
void IncreaseLifetimeUp () inline private
Reset economy lifetime to default across entity hierarchy all the way to the topmost entity.
InitAttachmentExclusionValues()
private void InitAttachmentExclusionValues () inline private
InitDamageZoneDisplayNameMapping()
void InitDamageZoneDisplayNameMapping () inline private
Initialize map of damage zone display names for more optimized retrieval.
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, string::Format(), CGame::FormatRawConfigStringKeys(), GetDisplayName(), GetGame(), GetType(), and path.
InitDamageZoneMapping()
void InitDamageZoneMapping () inline private
Initializes script-side map of damage zones and their components (named selections in models)
InitGlobalExclusionValues()
protected void InitGlobalExclusionValues () private
override to init part of the mask, independent of slot-specific behavior
InitInherentSlotExclusionMap()
private void InitInherentSlotExclusionMap () inline private
map stored on instance to better respond to various state changes
References InventorySlots::INVALID.
InitItemVariables()
void InitItemVariables () inline private
References CanHaveTemperature(), Math::Clamp(), GetGame(), float::LOWEST, and MAX.
InitLegacyConfigExclusionValues()
protected void InitLegacyConfigExclusionValues () inline private
InitLegacyExclusionCheck()
protected bool InitLegacyExclusionCheck () inline private
InitLegacySlotExclusionValuesDerived()
protected void InitLegacySlotExclusionValuesDerived () inline private
InitLegacySlotExclusionValuesImplicit()
InitLegacySlotExclusionValuesImplicit () inline private
adding base one-directional relations between headgear, masks, eyewear, and headstraps (exception)
Note
: 'InitLegacyConfigExclusionValues' adds them the other way if the item does not have any script-side exclusions AND has some legacy config parameter.
InitTemperature()
protected void InitTemperature () inline private
References g_Game, GetTemperatureFreezeThreshold(), and EntityAI::IsMan().
InsertAgent()
void InsertAgent (int agent, float count = 1) private
InterpolateTempData()
void InterpolateTempData (TemperatureDataInterpolated data) inline private
InterpolateTo()
static proto native void InterpolateTo (Camera targetCamera, float time, int type) static private
Interpolation between camera instances (current camera becomes targetCamera at the end of interpolation)
Parameters
targetCamera to which camera we want to interpolate
time true interpolation time
type 0 = without dynamics 1 = first half - acceleration, second half deceleration 2 = first third - acceleration, second third - linear movement, last third - deceleration
IsActive()
proto native bool IsActive () private
Is this camera active?
Returns
bool true if this camera is active
IsAnimal()
bool IsAnimal () inline private
IsBasebuildingKit()
bool IsBasebuildingKit () inline private
IsBeingPlaced()
bool IsBeingPlaced () inline private
IsDestructionBehaviour()
bool IsDestructionBehaviour () inline private
IsEmpty()
bool IsEmpty () inline private
is this container empty or not, checks both cargo and attachments
IsEnabled()
proto native bool IsEnabled () private
IsEntityAI()
override bool IsEntityAI () inline private
IsExclusionFlagPresent()
protected bool IsExclusionFlagPresent (set< int > values) inline private
checks 'this' if the incoming flag is present for the current state (slot behavior and others)
References slotName.
IsExclusionFlagPresentRecursive()
protected bool IsExclusionFlagPresentRecursive (set< int > values, int targetSlot) inline private
Gets flag from what is effectively an owner.
References InventoryLocation::GetSlot().
IsFlareVisible()
proto native bool IsFlareVisible () private
IsHeavyBehaviour()
bool IsHeavyBehaviour () inline private
returns item behaviour of item (more in ItemBase)
IsHologram()
override bool IsHologram () inline private
IsIgnited()
bool IsIgnited () inline private
Override this method and make it so it returns whenever this item is on fire right now or not. Evaluated on Server and Client.
References ComponentEnergyManager::IsWorking().
IsIgnoredByConstruction()
bool IsIgnoredByConstruction () inline private
IsInitialized()
bool IsInitialized () inline private
References m_Initialized.
IsInventoryVisible()
bool IsInventoryVisible () inline private
References GetParent().
IsItemOverheated()
bool IsItemOverheated () inline private
IsLockedInSlot()
IsLockedInSlot () inline private
Returns
true if entity is locked in attachment slot
References InventoryLocation::GetSlot().
IsManagingArrows()
bool IsManagingArrows () inline private
IsOneHandedBehaviour()
bool IsOneHandedBehaviour () inline private
returns item behaviour of item (more in ItemBase)
IsPilotLight()
proto native bool IsPilotLight () private
IsPlayer()
bool IsPlayer () inline private
IsPreparedToDelete()
bool IsPreparedToDelete () inline private
IsPrepareToDelete()
bool IsPrepareToDelete () inline private
IsRefresherSignalingViable()
bool IsRefresherSignalingViable () inline private
IsRoofAbove()
bool IsRoofAbove () inline private
IsSelfAdjustingTemperature()
bool IsSelfAdjustingTemperature () inline private
IsServerCheck()
bool IsServerCheck (bool allow_client) inline private
References Error(), g_Game, and GetGame().
IsSetForDeletion()
bool IsSetForDeletion () inline private
References IsPendingDeletion().
IsSimpleHiddenSelectionVisible()
proto native bool IsSimpleHiddenSelectionVisible (int index) private
IsSkinned()
bool IsSkinned () inline private
Skinning.
IsSplitable()
bool IsSplitable () inline private
returns just the configured 'canBeSplit' bool
IsStoreLoad()
bool IsStoreLoad () inline private
IsTakeable()
bool IsTakeable () inline private
IsTargetIgnitionSuccessful()
bool IsTargetIgnitionSuccessful (EntityAI item_target) inline private
Final evaluation just before the target item is actually ignited. Evaluated on Server.
IsThisIgnitionSuccessful()
bool IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Final evaluation just before this item is actually ignited from fire source. Evaluated on Server.
IsTwoHandedBehaviour()
bool IsTwoHandedBehaviour () inline private
returns item behaviour of item (more in ItemBase)
IsUniversalTemperatureSource()
bool IsUniversalTemperatureSource () inline private
Universal Temperature Sources Helpers.
IsValveTurnable()
bool IsValveTurnable (int pValveIndex) private
IsVariableSet()
bool IsVariableSet (int variable) inline private
'true' if this variable has ever been changed from default
IsVisibleDuringDaylight()
proto native bool IsVisibleDuringDaylight () private
IsZombie()
bool IsZombie () inline private
IsZombieMilitary()
bool IsZombieMilitary () inline private
KeepHealthOnReplace()
bool KeepHealthOnReplace () inline private
LoadVariables()
bool LoadVariables (ParamsReadContext ctx, int version = -1) inline private
References ItemVariableFlags::FLOAT, Serializer::Read(), and ReadVarsFromCTX().
LocalDropEntity()
bool LocalDropEntity (notnull EntityAI item) inline private
LocalTakeEntityAsAttachment()
bool LocalTakeEntityAsAttachment (notnull EntityAI item) inline private
LocalTakeEntityAsAttachmentEx()
bool LocalTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline private
LocalTakeEntityToCargo()
bool LocalTakeEntityToCargo (notnull EntityAI item) inline private
LocalTakeEntityToCargoEx()
bool LocalTakeEntityToCargoEx (notnull EntityAI item, int idx, int row, int col) inline private
LocalTakeEntityToInventory()
bool LocalTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline private
LocalTakeEntityToTargetAttachment()
bool LocalTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline private
LocalTakeEntityToTargetAttachmentEx()
bool LocalTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline private
LocalTakeEntityToTargetCargo()
bool LocalTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline private
LocalTakeEntityToTargetCargoEx()
bool LocalTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline private
LocalTakeEntityToTargetInventory()
bool LocalTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
LocalTakeToDst()
bool LocalTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline private
Log()
void Log (string msg, string fnc_name = "n/a") inline private
Log.
References GetType(), and Debug::Log().
LogError()
void LogError (string msg, string fnc_name = "n/a") inline private
LogError.
References GetType(), and Debug::LogError().
LogWarning()
void LogWarning (string msg, string fnc_name = "n/a") inline private
LogWarning.
References GetType(), and Debug::LogWarning().
LookAt()
proto native void LookAt (vector targetPos) private
Orientation change by lookAt point.
Parameters
targetPos where to look at
MaxLifetimeRefreshCalc()
void MaxLifetimeRefreshCalc () inline private
Calculates if the max lifetime is higher than refresher frequency (i.e. gets kept alive by refresher)
References GetCEApi(), GetGame(), and GameConstants::REFRESHER_FREQUENCY_DEFAULT.
OnAction()
bool OnAction (int action_id, Man player, ParamsReadContext ctx) inline private
References GetSingleInventoryItemWeightEx(), GetType(), Debug::Log(), and ToString().
OnAttachmentRuined()
void OnAttachmentRuined (EntityAI attachment) private
Called when some attachment of this parent is ruined. Called on server and client side.
OnBeforeTryDelete()
void OnBeforeTryDelete () private
OnBinLoadItemsDropped()
void OnBinLoadItemsDropped () inline private
Called when an item fails to get loaded into the inventory of an entity and gets dropped.
OnCargoChanged()
void OnCargoChanged () inline private
OnCEUpdate()
void OnCEUpdate () inline private
Central economy calls this function whenever going over all the entities.
void OnCEUpdate()
{
    // dont forget to propagate this call trough class hierarchy! - always at the start of the function
    super.OnCEUpdate();
    // use m_ElapsedSinceLastUpdate for time-related purposes
}
References GetGame(), CGame::GetTickTime(), and ProcessVariables().
OnChildItemReceived()
void OnChildItemReceived (InventoryItem item) inline private
OnChildItemRemoved()
void OnChildItemRemoved (InventoryItem item) inline private
OnDamageDestroyed()
void OnDamageDestroyed (int oldLevel) private
Called when the health gets to the min value, 'oldLevel' is previous health level, 'oldLevel' -1 means this entity was just spawned.
OnDebugButtonPressClient()
void OnDebugButtonPressClient (int button_index) inline private
OnDebugButtonPressServer()
void OnDebugButtonPressServer (int button_index) inline private
OnDebugSpawn()
void OnDebugSpawn () inline private
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), CGame::ConfigGetText(), GetGame(), path, and x.
OnDebugSpawnEx()
void OnDebugSpawnEx (DebugSpawnParams params) inline private
References OnDebugSpawn.
OnEnergyAdded()
void OnEnergyAdded () inline private
Energy manager event: Called when energy was added on this device. ALWAYS CALL super.OnEnergyAdded() !!!
OnEnergyConsumed()
void OnEnergyConsumed () inline private
Energy manager event: Called when energy was consumed on this device. ALWAYS CALL super.OnEnergyConsumed() !!!
OnExplosionEffects()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) inline private
References g_Game.
OnFreezeStateChangeClient()
void OnFreezeStateChangeClient () private
OnFreezeStateChangeServer()
void OnFreezeStateChangeServer () private
OnHologramBeingPlaced()
void OnHologramBeingPlaced (Man player) private
OnIgnitedTarget()
void OnIgnitedTarget (EntityAI target_item) inline private
Executed on Server when this item ignites some target item.
OnIgnitedTargetFailed()
void OnIgnitedTargetFailed (EntityAI target_item) inline private
Executed on Server when this item failed to ignite target item.
OnIgnitedThis()
void OnIgnitedThis (EntityAI fire_source) inline private
Executed on Server when some item ignited this one.
OnIgnitedThisFailed()
void OnIgnitedThisFailed (EntityAI fire_source) inline private
Executed on Server when some item failed to ignite this one.
OnInitEnergy()
void OnInitEnergy () inline private
Energy manager event: Object's initialization. Energy Manager is fully initialized by this point.
OnInventoryInit()
void OnInventoryInit () inline private
OnIsPlugged()
void OnIsPlugged (EntityAI source_device) inline private
Energy manager event: Called when this device is plugged into some energy source.
OnIsUnplugged()
void OnIsUnplugged (EntityAI last_energy_source) inline private
Energy manager event: Called when this device is UNPLUGGED from the energy source.
OnItemAttachmentSlotChanged()
void OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
OnItemLocationChanged()
void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
OnItemOverheat()
protected void OnItemOverheat (float deltaTime) private
OnItemOverheatEnd()
protected void OnItemOverheatEnd () private
note, that the deltaTime could be reverse-calculated and not totally accurate
OnItemOverheatStart()
protected void OnItemOverheatStart () private
override to implement desired overheat behavior on entity
OnMovedInsideCargo()
void OnMovedInsideCargo (EntityAI container) inline private
Called when this item enters cargo of some container.
References ComponentEnergyManager::HandleMoveInsideCargo().
OnMovedWithinCargo()
void OnMovedWithinCargo (EntityAI container) inline private
Called when this item moves within cargo of some container.
OnOwnSocketReleased()
void OnOwnSocketReleased (EntityAI device) inline private
Energy manager event: When something is UNPLUGGED from this device.
OnOwnSocketTaken()
void OnOwnSocketTaken (EntityAI device) inline private
Energy manager event: When something is plugged into this device.
OnPlacementCancelled()
void OnPlacementCancelled (Man player) private
OnPlacementComplete()
void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") private
OnPlacementStarted()
void OnPlacementStarted (Man player) private
OnRemovedFromCargo()
void OnRemovedFromCargo (EntityAI container) inline private
Called when this item exits cargo of some container.
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
References GetGame(), and Serializer::Read().
OnStoreLoad()
bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Called when data is loaded from persistence (on server side).
void OnStoreLoad(ParamsReadContext ctx, int version)
{
    // dont forget to propagate this call trough class hierarchy!
    if ( !super.OnStoreLoad(ctx, version) )
        return false;
    // read data loaded from game database (format and order of reading must be the same as writing!)
    int a;
    if ( !ctx.Read(a) )
        return false;
    float b;
    if ( !ctx.Read(b) )
        return false;
    return true;
}
References Serializer::Read(), ComponentEnergyManager::RestorePlugState(), ComponentEnergyManager::SetEnergy(), ComponentEnergyManager::SetPassiveState(), ComponentEnergyManager::StoreEnergySourceIDs(), and ComponentEnergyManager::SwitchOn().
OnStoreSave()
void OnStoreSave (ParamsWriteContext ctx) inline private
Engine calls this function to collect data from entity to store for persistence (on server side).
void OnStoreSave(ParamsWriteContext ctx)
{
    // dont forget to propagate this call trough class hierarchy!
    super.OnStoreSave(ctx);
    // write any data (using params) you want to store
    int   a = 5;
    float b = 6.0;
    ctx.Write(a);
    ctx.Write(b);
}
References ComponentEnergyManager::GetEnergy(), ComponentEnergyManager::GetEnergySource(), ComponentEnergyManager::IsPassive(), ComponentEnergyManager::IsPlugged(), ComponentEnergyManager::IsSwitchedOn(), and Serializer::Write().
OnSwitchOff()
void OnSwitchOff () inline private
Energy manager event: Called when the device is switched OFF.
OnSwitchOn()
void OnSwitchOn () inline private
Energy manager event: Called when the device is switched on.
OnVariablesSynchronized()
void OnVariablesSynchronized () inline private
Called on clients after receiving synchronization data from server.
References ComponentEnergyManager::DeviceUpdate(), Error(), ComponentEnergyManager::GetEnergySourceNetworkIDHigh(), ComponentEnergyManager::GetEnergySourceNetworkIDLow(), GetGame(), ComponentEnergyManager::GetPreviousSwitchState(), ComponentEnergyManager::IsSwitchedOn(), ComponentEnergyManager::PlugThisInto(), ComponentEnergyManager::StartUpdates(), ComponentEnergyManager::SwitchOff(), ComponentEnergyManager::SwitchOn(), and ComponentEnergyManager::UnplugThis().
OnWasAttached()
void OnWasAttached (EntityAI parent, int slot_id) private
OnWasDetached()
void OnWasDetached (EntityAI parent, int slot_id) inline private
OnWetChanged()
void OnWetChanged (float newVal, float oldVal) private
OnWetLevelChanged()
void OnWetLevelChanged (EWetnessLevel newLevel, EWetnessLevel oldLevel) private
OnWork()
void OnWork (float consumed_energy) inline private
Energy manager event: Called every device update if its supposed to do some work. The update can be every second or at random, depending on its manipulation.
OnWorkStart()
void OnWorkStart () inline private
Energy manager event: Called only once when this device starts doing its work.
OnWorkStop()
void OnWorkStop () inline private
Energy manager event: Called when the device stops working (was switched OFF or ran out of energy)
PairRemote()
void PairRemote (notnull EntityAI trigger) private
PlacementCanBeRotated()
bool PlacementCanBeRotated () inline private
Should return false if you want to disable hologram rotation.
PlaceOnSurfaceRotated()
proto native void PlaceOnSurfaceRotated (out vector trans[4], vector pos, float dx = 0, float dz = 0, float fAngle = 0, bool align = false) private
PredictiveDropEntity()
bool PredictiveDropEntity (notnull EntityAI item) inline private
PredictiveTakeEntityAsAttachment()
bool PredictiveTakeEntityAsAttachment (notnull EntityAI item) inline private
Put item into as attachment.
References GetGame().
PredictiveTakeEntityAsAttachmentEx()
bool PredictiveTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline private
Returns if item can be added as attachment on specific slot. Note that slot index IS NOT slot ID! Slot ID is defined in DZ/data/config.cpp.
References GetGame().
PredictiveTakeEntityToCargo()
bool PredictiveTakeEntityToCargo (notnull EntityAI item) inline private
Put item into into cargo.
References GetGame().
PredictiveTakeEntityToCargoEx()
bool PredictiveTakeEntityToCargoEx (notnull EntityAI item, int idx, int row, int col) inline private
Put item into into cargo on specific cargo location.
References GetGame().
PredictiveTakeEntityToInventory()
bool PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline private
Put item anywhere into this entity (as attachment or into cargo, recursively)
References GetGame().
PredictiveTakeEntityToTargetAttachment()
bool PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline private
References GetGame().
PredictiveTakeEntityToTargetAttachmentEx()
bool PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline private
References GetGame().
PredictiveTakeEntityToTargetCargo()
bool PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline private
References GetGame().
PredictiveTakeEntityToTargetCargoEx()
bool PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline private
References GetGame().
PredictiveTakeEntityToTargetInventory()
bool PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
References GetGame().
PredictiveTakeToDst()
bool PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline private
References GetGame().
ProcessInvulnerabilityCheck()
void ProcessInvulnerabilityCheck (string servercfg_param) inline private
References CfgGameplayHandler::GetDisableBaseDamage(), CfgGameplayHandler::GetDisableContainerDamage(), and GetGame().
ProcessMeleeItemDamage()
override EntityAI ProcessMeleeItemDamage (int mode = 0) inline private
References GetGame(), and MELEE_ITEM_DAMAGE.
ProcessVariables()
void ProcessVariables () inline private
References CanHaveTemperature(), g_Game, IsSelfAdjustingTemperature(), and GameConstants::TEMP_COEF_WORLD.
PropagateExclusionValueRecursive()
private void PropagateExclusionValueRecursive (set< int > values, int slotId) inline private
References InventoryLocation::GetSlot().
ReadVarsFromCTX()
bool ReadVarsFromCTX (ParamsReadContext ctx, int version = -1) inline private
Reads from storage CTX.
References Serializer::Read(), and VARIABLE_TEMPERATURE.
RefreshTemperatureAccess()
void RefreshTemperatureAccess (TemperatureData data) inline private
refreshes access without setting temperature, keeps the source locked in
References CanHaveTemperature(), and Debug::Log().
RegisterNetSyncVariableBool()
RegisterNetSyncVariableBool (string variableName) private
registers bool variable synchronized over network
Parameters
[in] variableName which variable should be synchronized
RegisterNetSyncVariableBoolSignal()
RegisterNetSyncVariableBoolSignal (string variableName) private
when bool variable is true, it's sent to clients and become false again
Parameters
[in] variableName which variable should be synchronized
RegisterNetSyncVariableFloat()
RegisterNetSyncVariableFloat (string variableName, float minValue = 0, float maxValue = 0, int precision = 1) private
registers float variable synchronized over network
Parameters
[in] variableName which variable should be synchronized
[in] minValue minimal value used for quantization (when minValue == maxValue, no quatization is done)
[in] maxValue maximal value used for quantization (when minValue == maxValue, no quatization is done)
[in] precision precision in number of digits after decimal point
RegisterNetSyncVariableInt()
RegisterNetSyncVariableInt (string variableName, int minValue = 0, int maxValue = 0) private
registers int variable synchronized over network
Parameters
[in] variableName which variable should be synchronized
[in] minValue minimal value used for quantization (when minValue == maxValue, no quatization is done)
[in] maxValue maximal value used for quantization (when minValue == maxValue, no quatization is done)
RegisterNetSyncVariableObject()
RegisterNetSyncVariableObject (string variableName) private
registers object variable synchronized over network, only synchronizes if network id is assigned. Doesn't handle object despawn on client
Parameters
[in] variableName which variable should be synchronized
RegisterTransportHit()
void RegisterTransportHit (Transport transport) inline private
References dBodyApplyImpulse(), GetVelocity(), vector::Length(), and vector::Normalize().
RemoveAgent()
void RemoveAgent (int agent_id) private
RemoveAllAgents()
void RemoveAllAgents () private
RemoveAllAgentsExcept()
void RemoveAllAgentsExcept (int agent_to_keep) private
RemoveItemVariable()
void RemoveItemVariable (int variable) inline private
Removes variable from variable mask, making it appear as though the variable has never been changed from default.
ReplaceOnDeath()
bool ReplaceOnDeath () inline private
SaveVariables()
void SaveVariables (ParamsWriteContext ctx) inline private
References ItemVariableFlags::FLOAT, Serializer::Write(), and WriteVarsToCTX().
SerializeNumericalVars()
void SerializeNumericalVars (array< float > floats_out) inline private
References VARIABLE_TEMPERATURE.
ServerDropEntity()
bool ServerDropEntity (notnull EntityAI item) inline private
ServerTakeEntityAsAttachment()
bool ServerTakeEntityAsAttachment (notnull EntityAI item) inline private
ServerTakeEntityAsAttachmentEx()
bool ServerTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline private
ServerTakeEntityToCargo()
bool ServerTakeEntityToCargo (notnull EntityAI item) inline private
ServerTakeEntityToInventory()
bool ServerTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline private
ServerTakeEntityToTargetAttachment()
bool ServerTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline private
ServerTakeEntityToTargetAttachmentEx()
bool ServerTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline private
ServerTakeEntityToTargetCargo()
bool ServerTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline private
ServerTakeEntityToTargetCargoEx()
bool ServerTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline private
ServerTakeEntityToTargetInventory()
bool ServerTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
ServerTakeToDst()
bool ServerTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline private
SetActive()
proto native void SetActive (bool active) private
Sets this camera as active.
SetAITargetCallbacks()
proto native void SetAITargetCallbacks (AbstractAITargetCallbacks callbacks) private
SetAmbientAlpha()
proto native void SetAmbientAlpha (float pAlpha) private
SetAmbientColor()
proto native void SetAmbientColor (float pRed, float pGreen, float pBlue) private
SetAmbientColorV()
proto native void SetAmbientColorV (vector pColorVector) private
SetAsSkinned()
void SetAsSkinned () inline private
SetAttachmentExclusionMaskGlobal()
protected void SetAttachmentExclusionMaskGlobal (set< int > values) inline private
SetAttachmentExclusionMaskSlot()
protected void SetAttachmentExclusionMaskSlot (int slotId, set< int > values) inline private
sets values for specific slot
References ErrorEx.
SetBayonetAttached()
void SetBayonetAttached (bool pState, int slot_idx = -1) inline private
SetBrightness()
proto native void SetBrightness (float pValue) private
SetButtstockAttached()
void SetButtstockAttached (bool pState, int slot_idx = -1) inline private
SetCastShadow()
proto native void SetCastShadow (bool pState) private
SetCleanness()
void SetCleanness (int value, bool allow_client = false) private
SetColor()
void SetColor (int r, int g, int b, int a) private
SetDiffuseAlpha()
proto native void SetDiffuseAlpha (float pAlpha) private
SetDiffuseColor()
proto native void SetDiffuseColor (float pRed, float pGreen, float pBlue) private
SetDiffuseColorV()
proto native void SetDiffuseColorV (vector pColorVector) private
SetEnabled()
proto native void SetEnabled (bool pState) private
SetFlareRelPosition()
proto native void SetFlareRelPosition (vector pPosition) private
SetFlareVisible()
proto native void SetFlareVisible (bool pState) private
SetFocus()
proto native void SetFocus (float distance, float blur) private
Depth of Field settings.
Parameters
distance DOF distance parameter
blur DOF blur parameter
SetFOV()
proto native void SetFOV (float fov) private
Field of View settings.
Parameters
fov FOV angle in radians
SetFreezeThawProgress()
protected void SetFreezeThawProgress (float val) inline private
0->1 when freezing, 1->0 when thawing
SetFromProjectile()
void SetFromProjectile (ProjectileStoppedInfo info) inline private
SetFrozen()
void SetFrozen (bool frozen) inline private
SetHeatHazePower()
proto native void SetHeatHazePower (float pValue) private
SetHeatHazeRadius()
proto native void SetHeatHazeRadius (float pValue) private
SetInvisibleRecursive()
void SetInvisibleRecursive (bool invisible, EntityAI parent = null, array< int > attachments = null) inline private
SetItemOverheatProgress()
void SetItemOverheatProgress (float val, float deltaTime = 0) inline private
References Math::Clamp().
SetLifetime()
proto native void SetLifetime (float fLifeTime) private
Set (override) remaining economy lifetime (seconds)
SetLifetimeMax()
proto native void SetLifetimeMax (float fLifeTime) private
Set (override) max economy lifetime per entity instance (seconds)
SetLightType()
proto native void SetLightType (int pType) private
SetLiquidType()
void SetLiquidType (int value, bool allow_client = false) private
SetNearPlane()
proto native void SetNearPlane (float nearPlane) private
set near plane of camera
Parameters
nearPlane clamped internally to 0.01m
SetObjectMaterial()
proto native void SetObjectMaterial (int index, string mat_name) private
Change material in hiddenSelections.
SetObjectTexture()
proto native void SetObjectTexture (int index, string texture_name) private
Change texture in hiddenSelections.
SetPersistentPairID()
void SetPersistentPairID (int id) inline private
References GetRemotelyActivatedItemBehaviour(), and RemotelyActivatedItemBehaviour::SetPersistentPairID().
SetPilotLight()
proto native void SetPilotLight (bool isOn) private
SetPrepareToDelete()
void SetPrepareToDelete () inline private
SetPulseCoef()
proto native void SetPulseCoef (float pState) private
SetQuantity()
bool SetQuantity (float value, bool destroy_config = true, bool destroy_forced = false, bool allow_client = false, bool clamp_to_stack_max = true) private
SetQuantityToMinimum()
void SetQuantityToMinimum () private
SetRadius()
proto native void SetRadius (float pValue) private
SetRoofAbove()
void SetRoofAbove (bool state) inline private
SetSimpleHiddenSelectionState()
proto native void SetSimpleHiddenSelectionState (int index, bool state) private
Simple hidden selection state; 0 == hidden.
SetSpotLightAngle()
proto native void SetSpotLightAngle (float pValue) private
SetStoreLoad()
void SetStoreLoad (bool value) private
SetStoreLoadedQuantity()
void SetStoreLoadedQuantity (float value) private
SetSynchDirty()
proto native void SetSynchDirty () private
Sets object synchronization dirty flag, which signalize that object wants to be synchronized (take effect only in MP on server side)
SetTakeable()
void SetTakeable (bool pState) private
SetTemperature()
void SetTemperature (float value, bool allow_client = false) inline private
not really deprecated, but missing context info from TemperatureData. Default values used instead.
SetTemperatureDirect()
void SetTemperatureDirect (float value, bool allow_client = false) inline private
References Math::Clamp(), and VARIABLE_TEMPERATURE.
SetTemperatureEx()
void SetTemperatureEx (TemperatureData data) inline private
sets temperature, handles base overheating and freezing state progression logics
CanFreeze
References CanHaveTemperature(), CanItemOverheat(), Math::Clamp(), GetItemOverheatThreshold(), GetTemperatureFreezeThreshold(), GetTemperatureThawThreshold(), Debug::Log(), and TemperatureData::m_AdjustedTarget.
SetTemperatureMax()
void SetTemperatureMax () inline private
presumably for debug purposes?
References GetTemperatureFreezeThreshold().
SetUniversalTemperatureSource()
void SetUniversalTemperatureSource (UTemperatureSource uts) inline private
SetVariableMask()
void SetVariableMask (int variable) inline private
References GetGame().
SetViewIndex()
void SetViewIndex (int index) inline private
Sets item preview index.
References GetGame().
SetVisibleDuringDaylight()
proto native void SetVisibleDuringDaylight (bool pState) private
SetWeightDirty()
void SetWeightDirty () inline private
References DumpStack(), and Print().
SetWet()
void SetWet (float value, bool allow_client = false) private
SetWetMax()
void SetWetMax () private
ShowAllSelections()
void ShowAllSelections () inline private
Sets all animation values to 0, making them VISIBLE if they are configured in models.cfg in such way. These selections must also be defined in the entity's config class in 'AnimationSources'.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), and GetType().
ShowSelection()
void ShowSelection (string selection_name) inline private
Shows selection of the given name. Must be configed in config.hpp and models.cfg.
SoundHardBushFallingPlay()
void SoundHardBushFallingPlay () inline private
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
SoundHardTreeFallingPlay()
void SoundHardTreeFallingPlay () inline private
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
SoundSoftBushFallingPlay()
void SoundSoftBushFallingPlay () inline private
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
SoundSoftTreeFallingPlay()
void SoundSoftTreeFallingPlay () inline private
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
SpawnEntityOnGround()
EntityAI SpawnEntityOnGround (string object_name, vector mat[4]) inline private
References ECE_PLACE_ON_SURFACE, RF_DEFAULT, InventoryLocation::SetGround(), and SpawnEntity().
SpawnEntityOnGroundPos()
EntityAI SpawnEntityOnGroundPos (string object_name, vector pos) inline private
References ECE_PLACE_ON_SURFACE, Math3D::MatrixIdentity4(), RF_DEFAULT, InventoryLocation::SetGround(), and SpawnEntity().
SpawnInInventoryOrGroundPos()
EntityAI SpawnInInventoryOrGroundPos (string object_name, GameInventory inv, vector pos) inline private
References GameInventory::CreateInInventory().
SplitIntoStackMaxClient()
void SplitIntoStackMaxClient (EntityAI destination_entity, int slot_id) private
SplitIntoStackMaxEx()
void SplitIntoStackMaxEx (EntityAI destination_entity, int slot_id) private
SwitchItemSelectionTexture()
void SwitchItemSelectionTexture (EntityAI item, string slot_name) private
SwitchItemSelectionTextureEx()
void SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par = null) private
SwitchLight()
proto native void SwitchLight (bool isOn) private
TransferVariablesFloat()
void TransferVariablesFloat (array< float > float_vars) inline private
References DeSerializeNumericalVars().
TranslateSlotFromSelection()
bool TranslateSlotFromSelection (string selection_name, out int slot_id) inline private
TryDelete()
bool TryDelete () inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), IsPrepareToDelete(), and Debug::Log().
UnpairRemote()
void UnpairRemote () private
UpdateNetSyncVariableFloat()
proto native void UpdateNetSyncVariableFloat (string variableName, float minValue = 0, float maxValue = 0, int precision = 1) private
UpdateNetSyncVariableInt()
proto native void UpdateNetSyncVariableInt (string variableName, float minValue = 0, float maxValue = 0) private
UpdateWeight()
void UpdateWeight (WeightUpdateType updateType = WeightUpdateType.FULL, float weightAdjustment = 0) private
UseConfigInitTemperature()
bool UseConfigInitTemperature () inline private
References IsCorpse(), and EntityAI::IsMan().
WriteVarsToCTX()
void WriteVarsToCTX (ParamsWriteContext ctx) inline private
Writes to storage CTX.
References VARIABLE_TEMPERATURE, and Serializer::Write().
Field Documentation
DEAD_REPLACE_DELAY
const int DEAD_REPLACE_DELAY = 250 private
DELETE_CHECK_DELAY
const int DELETE_CHECK_DELAY = 100 private
m_AttachmentExclusionMaskChildren
private ref set<int> m_AttachmentExclusionMaskChildren private
m_AttachmentExclusionMaskGlobal
private ref set<int> m_AttachmentExclusionMaskGlobal private
m_AttachmentExclusionSlotMap
private ref map<int,ref set<int> > m_AttachmentExclusionSlotMap private
m_AttachmentsWithAttachments
ref array<EntityAI> m_AttachmentsWithAttachments private
m_AttachmentsWithCargo
ref array<EntityAI> m_AttachmentsWithCargo private
m_CanDisplayWeight
protected bool m_CanDisplayWeight private
m_ComponentsBank
private ref ComponentsBank m_ComponentsBank private
m_ConfigWeight
float m_ConfigWeight = ConfigGetInt("weight") private
m_DamageDisplayNameMap
private ref map<int, string> m_DamageDisplayNameMap = new map<int, string> private
m_DamageZoneMap
protected ref DamageZoneMap m_DamageZoneMap private
m_DeathSyncSent
bool m_DeathSyncSent private
m_DestructionBehaviourObj
ref DestructionEffectBase m_DestructionBehaviourObj private
m_ElapsedSinceLastUpdate
protected float m_ElapsedSinceLastUpdate private
m_EM
ComponentEnergyManager m_EM private
m_FreezeThawProgress
protected float m_FreezeThawProgress private
m_HiddenSelectionsData
private ref HiddenSelectionsData m_HiddenSelectionsData private
m_Initialized
bool m_Initialized = false private
m_IsFrozen
protected bool m_IsFrozen private
m_IsFrozenLocal
protected bool m_IsFrozenLocal private
m_KilledByHeadshot
bool m_KilledByHeadshot private
m_KillerData
ref KillerData m_KillerData private
m_LastUpdatedTime
private float m_LastUpdatedTime private
m_OldLocation
ref InventoryLocation m_OldLocation private
m_OnAttachmentReleaseLock
protected ref ScriptInvoker m_OnAttachmentReleaseLock private
m_OnAttachmentSetLock
protected ref ScriptInvoker m_OnAttachmentSetLock private
m_OnHitByInvoker
protected ref ScriptInvoker m_OnHitByInvoker private
m_OnItemAddedIntoCargo
protected ref ScriptInvoker m_OnItemAddedIntoCargo private
m_OnItemAttached
protected ref ScriptInvoker m_OnItemAttached private
m_OnItemDetached
protected ref ScriptInvoker m_OnItemDetached private
m_OnItemFlipped
protected ref ScriptInvoker m_OnItemFlipped private
m_OnItemMovedInCargo
protected ref ScriptInvoker m_OnItemMovedInCargo private
m_OnItemRemovedFromCargo
protected ref ScriptInvoker m_OnItemRemovedFromCargo private
m_OnKilledInvoker
protected ref ScriptInvoker m_OnKilledInvoker private
m_OnReleaseLock
protected ref ScriptInvoker m_OnReleaseLock private
m_OnSetLock
protected ref ScriptInvoker m_OnSetLock private
m_OnViewIndexChanged
protected ref ScriptInvoker m_OnViewIndexChanged private
m_OverheatProgress
protected float m_OverheatProgress private
m_PendingDelete
bool m_PendingDelete = false private
m_PreparedToDelete
bool m_PreparedToDelete = false private
m_PreviousRoofTestTime
protected float m_PreviousRoofTestTime = 0 private
m_RefresherViable
bool m_RefresherViable = false private
m_RoofAbove
protected bool m_RoofAbove = false private
m_TAC
protected ref TemperatureAccessComponent m_TAC private
m_TransportHitRegistered
bool m_TransportHitRegistered = false private
m_TransportHitVelocity
vector m_TransportHitVelocity private
m_UniversalTemperatureSource
protected UTemperatureSource m_UniversalTemperatureSource private
m_VarHeatPermeabilityCoef
float m_VarHeatPermeabilityCoef private
m_VariablesMask
int m_VariablesMask private
m_VarTemperature
float m_VarTemperature private
m_VarTemperatureFreezeThreshold
float m_VarTemperatureFreezeThreshold private
m_VarTemperatureFreezeTime
float m_VarTemperatureFreezeTime private
m_VarTemperatureInit
float m_VarTemperatureInit private
m_VarTemperatureMax
float m_VarTemperatureMax private
m_VarTemperatureMin
float m_VarTemperatureMin private
m_VarTemperatureOverheatTime
float m_VarTemperatureOverheatTime private
m_VarTemperatureThawThreshold
float m_VarTemperatureThawThreshold private
m_VarTemperatureThawTime
float m_VarTemperatureThawTime private
m_ViewIndex
int m_ViewIndex = 0 private
view index Item view index is used to setup which camera will be used in item view widget in inventory. With this index you can setup various camera angles for different item states (e.g. fireplace, weapons).
m_Weight
float m_Weight private
m_WeightDirty
bool m_WeightDirty = 1 private
m_WeightEx
float m_WeightEx private
The documentation for this class was generated from the following files:
P:/scripts/3_Game/Entities/Camera.c
P:/scripts/3_Game/Entities/EntityAI.c
P:/scripts/3_Game/Entities/EntityLightSource.c
P:/scripts/3_Game/Entities/SoundOnVehicle.c