DayZ Scripts: DayZAnimalInputController Class Reference
DayZAnimalInputController Class Reference
Private Member Functions
proto native bool IsDead ()
proto native bool IsAttack ()
proto native void OverrideBehaviourAction (bool state, int action)
proto native int GetBehaviourAction ()
private void DayZAnimalInputController ()
never created by script
private void ~DayZAnimalInputController ()
never destroyed by script
Constructor & Destructor Documentation
DayZAnimalInputController()
private void DayZAnimalInputController () inline private
never created by script
~DayZAnimalInputController()
private void ~DayZAnimalInputController () inline private
never destroyed by script
Member Function Documentation
GetBehaviourAction()
proto native int GetBehaviourAction () private
IsAttack()
proto native bool IsAttack () private
Referenced by DayZCreatureAI::CommandHandler().
IsDead()
proto native bool IsDead () private
Referenced by DayZCreatureAI::HandleDeath().
OverrideBehaviourAction()
proto native void OverrideBehaviourAction (bool state, int action) private
Referenced by DayZCreature::ModCommandHandlerBefore().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Entities/DayZAnimalInputController.c