DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionForceConsume.c File Reference
ActionForceConsume.c File Reference
Data Structures
class ActionForceConsumeCB
Functions
void ActionForceConsume ()
override void CreateConditionComponents ()
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
protected void PlaySound (PlayerBase player)
Variables
ActionForceConsumeCB SOUND_REPEAT_INTERVAL = 1.5
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
References Math::AbsFloat().
ActionForceConsume()
void ActionForceConsume ()
References m_CommandUID, and m_StanceMask.
CreateConditionComponents()
override void CreateConditionComponents ()
References UAMaxDistances::DEFAULT.
OnEndServer()
override void OnEndServer (ActionData action_data)
References CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), PlaySound(), and ScriptCallQueue::Remove().
OnStartServer()
override void OnStartServer (ActionData action_data)
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), PlaySound(), and SOUND_REPEAT_INTERVAL.
PlaySound()
protected void PlaySound (PlayerBase player)
Variable Documentation
SOUND_REPEAT_INTERVAL
ActionForceConsumeCB SOUND_REPEAT_INTERVAL = 1.5
Referenced by OnStartServer().