DayZ Scripts: PluginDayzPlayerDebugUserData Class Reference
PluginDayzPlayerDebugUserData Class Reference
Private Member Functions
void PluginDayzPlayerDebugUserData (string name, int category, int pUserData, bool pFullBody, int pStanceMask=-1)
int GetInt ()
bool IsFullBody ()
int GetStanceMask ()
int GetCategory ()
string GetName ()
string GetNameUnique ()
Private Attributes
protected int m_iUserData
protected bool m_bIsFullBody
protected int m_iStanceMask
protected int m_Category
protected string m_Name
Constructor & Destructor Documentation
PluginDayzPlayerDebugUserData()
void PluginDayzPlayerDebugUserData (string name, int category, int pUserData, bool pFullBody, int pStanceMask = -1) inline private
References m_bIsFullBody, m_Category, m_iStanceMask, m_iUserData, m_Name, and name.
Member Function Documentation
GetCategory()
int GetCategory () inline private
References m_Category.
Referenced by DisplayActions(), and GetNameUnique().
GetInt()
int GetInt () inline private
References m_iUserData.
Referenced by Actions_Start().
GetName()
string GetName () inline private
References m_Name.
Referenced by DisplayActions().
GetNameUnique()
string GetNameUnique () inline private
References GetCategory(), and m_Name.
Referenced by RegisterAnimation().
GetStanceMask()
int GetStanceMask () inline private
References m_iStanceMask.
Referenced by Actions_Start().
IsFullBody()
bool IsFullBody () inline private
References m_bIsFullBody.
Referenced by Actions_Start().
Field Documentation
m_bIsFullBody
protected bool m_bIsFullBody private
Referenced by IsFullBody(), and PluginDayzPlayerDebugUserData().
m_Category
protected int m_Category private
Referenced by GetCategory(), and PluginDayzPlayerDebugUserData().
m_iStanceMask
protected int m_iStanceMask private
Referenced by GetStanceMask(), and PluginDayzPlayerDebugUserData().
m_iUserData
protected int m_iUserData private
Referenced by GetInt(), and PluginDayzPlayerDebugUserData().
m_Name
protected string m_Name private
Referenced by GetName(), GetNameUnique(), and PluginDayzPlayerDebugUserData().
The documentation for this class was generated from the following file:
P:/scripts/4_world/plugins/pluginbase/plugindayzplayerdebug.c