DayZ Scripts: SelectionTranslation Class Reference
SelectionTranslation Class Reference
Private Member Functions
void SelectionTranslation (Head_Default head, int idx)
void InitTranslatedSelections (int idx)
bool SearchAndTranslate (string path, int idx)
void SetSelectionState (bool state)
bool GetSelectionState ()
ref array< int > GetTranslatedSelections ()
Private Attributes
bool m_SelectionState
bool m_TranslationFinished = false
string m_BasePath
ref array< int > m_TranslatedSelections
Head_Default m_Head
Detailed Description
Definition at line 67 of file Head.c.
Constructor & Destructor Documentation
SelectionTranslation()
void SelectionTranslation (Head_Default head, int idx) inline private
Definition at line 76 of file Head.c.
References InitTranslatedSelections(), m_BasePath, and m_Head.
Member Function Documentation
GetSelectionState()
bool GetSelectionState () inline private
Definition at line 148 of file Head.c.
References m_SelectionState.
Referenced by ManBase::UpdateHairSelectionVisibility().
GetTranslatedSelections()
ref array< int > GetTranslatedSelections () inline private
Definition at line 153 of file Head.c.
References m_TranslatedSelections.
Referenced by ManBase::UpdateTranslatedSelections().
InitTranslatedSelections()
void InitTranslatedSelections (int idx) inline private
Definition at line 83 of file Head.c.
References g_Game, m_BasePath, m_Head, m_TranslatedSelections, m_TranslationFinished, path, and SearchAndTranslate().
Referenced by SelectionTranslation().
SearchAndTranslate()
bool SearchAndTranslate (string path, int idx) inline private
Definition at line 117 of file Head.c.
References g_Game, m_Head, m_TranslatedSelections, m_TranslationFinished, and path.
Referenced by InitTranslatedSelections().
SetSelectionState()
void SetSelectionState (bool state) inline private
Definition at line 143 of file Head.c.
References m_SelectionState.
Referenced by Head::InitSelectionTranslation(), and ManBase::SetHairLevelToHide().
Field Documentation
m_BasePath
string m_BasePath private
Definition at line 72 of file Head.c.
Referenced by InitTranslatedSelections(), and SelectionTranslation().
m_Head
Head_Default m_Head private
Definition at line 74 of file Head.c.
Referenced by InitTranslatedSelections(), SearchAndTranslate(), and SelectionTranslation().
m_SelectionState
bool m_SelectionState private
Definition at line 69 of file Head.c.
Referenced by GetSelectionState(), and SetSelectionState().
m_TranslatedSelections
ref array<int> m_TranslatedSelections private
Definition at line 73 of file Head.c.
Referenced by GetTranslatedSelections(), InitTranslatedSelections(), and SearchAndTranslate().
m_TranslationFinished
bool m_TranslationFinished = false private
Definition at line 71 of file Head.c.
Referenced by InitTranslatedSelections(), and SearchAndTranslate().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ManBase/BodyParts/Head.c