DayZ Scripts: KitBase Class Reference
KitBase Class Reference
Private Member Functions
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool DoPlacingHeightCheck ()
override float HeightCheckOverride ()
override void DisassembleKit (ItemBase item)
override void OnDebugSpawn ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool DoPlacingHeightCheck ()
override float HeightCheckOverride ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override string GetDeployFinishSoundset ()
override void DisassembleKit (ItemBase item)
override void OnDebugSpawn ()
override bool PlacementCanBeRotated ()
override bool DoPlacingHeightCheck ()
override float HeightCheckOverride ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void DisassembleKit (ItemBase item)
override void OnDebugSpawn ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool DoPlacingHeightCheck ()
override float HeightCheckOverride ()
override void DisassembleKit (ItemBase item)
override void OnDebugSpawn ()
Detailed Description
Definition at line 1 of file FenceKit.c.
Member Function Documentation
CanReceiveAttachment() [1/4]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 3 of file FenceKit.c.
CanReceiveAttachment() [2/4]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 3 of file ShelterKit.c.
CanReceiveAttachment() [3/4]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 18 of file TotemKit.c.
CanReceiveAttachment() [4/4]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 3 of file WatchtowerKit.c.
References ItemBase::CanReceiveAttachment().
DisassembleKit() [1/4]
override void DisassembleKit (ItemBase item) inline private
Definition at line 48 of file FenceKit.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and IsHologram().
Referenced by ItemBase::EEItemDetached().
DisassembleKit() [2/4]
override void DisassembleKit (ItemBase item) inline private
Definition at line 61 of file ShelterKit.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and IsHologram().
DisassembleKit() [3/4]
override void DisassembleKit (ItemBase item) inline private
Definition at line 52 of file TotemKit.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and IsHologram().
DisassembleKit() [4/4]
override void DisassembleKit (ItemBase item) inline private
Definition at line 44 of file WatchtowerKit.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and IsHologram().
DoPlacingHeightCheck() [1/4]
override bool DoPlacingHeightCheck () inline private
Definition at line 38 of file FenceKit.c.
DoPlacingHeightCheck() [2/4]
override bool DoPlacingHeightCheck () inline private
Definition at line 36 of file ShelterKit.c.
DoPlacingHeightCheck() [3/4]
override bool DoPlacingHeightCheck () inline private
Definition at line 8 of file TotemKit.c.
DoPlacingHeightCheck() [4/4]
override bool DoPlacingHeightCheck () inline private
Definition at line 34 of file WatchtowerKit.c.
GetDeployFinishSoundset()
override string GetDeployFinishSoundset () inline private
Definition at line 56 of file ShelterKit.c.
GetDeploySoundset()
override string GetDeploySoundset () inline private
Definition at line 46 of file ShelterKit.c.
GetLoopDeploySoundset()
override string GetLoopDeploySoundset () inline private
Definition at line 51 of file ShelterKit.c.
Referenced by ItemBase::PlayDeployLoopSound().
HeightCheckOverride() [1/4]
override float HeightCheckOverride () inline private
Definition at line 43 of file FenceKit.c.
HeightCheckOverride() [2/4]
override float HeightCheckOverride () inline private
Definition at line 41 of file ShelterKit.c.
HeightCheckOverride() [3/4]
override float HeightCheckOverride () inline private
Definition at line 13 of file TotemKit.c.
HeightCheckOverride() [4/4]
override float HeightCheckOverride () inline private
Definition at line 39 of file WatchtowerKit.c.
OnDebugSpawn() [1/4]
override void OnDebugSpawn () inline private
Definition at line 61 of file FenceKit.c.
References GetPosition.
OnDebugSpawn() [2/4]
override void OnDebugSpawn () inline private
Definition at line 74 of file ShelterKit.c.
References GetPosition.
OnDebugSpawn() [3/4]
override void OnDebugSpawn () inline private
Definition at line 68 of file TotemKit.c.
References GetPosition.
OnDebugSpawn() [4/4]
override void OnDebugSpawn () inline private
Definition at line 57 of file WatchtowerKit.c.
References GetPosition.
OnPlacementComplete() [1/4]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 19 of file FenceKit.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and SetIsDeploySound().
OnPlacementComplete() [2/4]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 18 of file ShelterKit.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and SetIsDeploySound().
OnPlacementComplete() [3/4]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 34 of file TotemKit.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and SetIsDeploySound().
OnPlacementComplete() [4/4]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 16 of file WatchtowerKit.c.
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and SetIsDeploySound().
PlacementCanBeRotated()
override bool PlacementCanBeRotated () inline private
Definition at line 3 of file TotemKit.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/FenceKit.c
P:/scripts/4_World/Entities/ItemBase/ShelterKit.c
P:/scripts/4_World/Entities/ItemBase/TotemKit.c
P:/scripts/4_World/Entities/ItemBase/WatchtowerKit.c