DayZ Scripts: ActionConsumeSingle Class Reference
ActionConsumeSingle Class Reference
Private Member Functions
void ActionConsumeSingle ()
int GetConsumedQuantity ()
override bool HasProneException ()
override bool HasTarget ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
Private Attributes
const int DEFAULT_CONSUMED_QUANTITY = 1
Detailed Description
Definition at line 9 of file ActionConsumeSingle.c.
Constructor & Destructor Documentation
ActionConsumeSingle()
void ActionConsumeSingle () inline private
Definition at line 13 of file ActionConsumeSingle.c.
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 42 of file ActionConsumeSingle.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 36 of file ActionConsumeSingle.c.
References m_ConditionItem, and m_ConditionTarget.
GetConsumedQuantity()
int GetConsumedQuantity () inline private
Definition at line 21 of file ActionConsumeSingle.c.
References DEFAULT_CONSUMED_QUANTITY.
Referenced by OnExecuteServer().
HasProneException()
override bool HasProneException () inline private
Definition at line 26 of file ActionConsumeSingle.c.
HasTarget()
override bool HasTarget () inline private
Definition at line 31 of file ActionConsumeSingle.c.
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
Definition at line 55 of file ActionConsumeSingle.c.
References AnimatedActionBase::GetProgress(), ActionData::m_MainItem, and ActionData::m_Player.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
Definition at line 47 of file ActionConsumeSingle.c.
References GetConsumedQuantity(), ActionData::m_MainItem, and ActionData::m_Player.
Field Documentation
DEFAULT_CONSUMED_QUANTITY
const int DEFAULT_CONSUMED_QUANTITY = 1 private
Definition at line 11 of file ActionConsumeSingle.c.
Referenced by GetConsumedQuantity().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionConsumeSingle.c