DayZ Scripts: ActionDrainLiquid Class Reference
ActionDrainLiquid Class Reference
Private Member Functions
void ActionDrainLiquid ()
override void CreateConditionComponents ()
override bool HasProneException ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override void OnStartAnimationLoop (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
Detailed Description
Definition at line 11 of file ActionDrainLiquid.c.
Constructor & Destructor Documentation
ActionDrainLiquid()
void ActionDrainLiquid () inline private
Definition at line 13 of file ActionDrainLiquid.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 33 of file ActionDrainLiquid.c.
References Liquid::CanTransfer().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 22 of file ActionDrainLiquid.c.
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool HasProneException () inline private
Definition at line 28 of file ActionDrainLiquid.c.
OnEndAnimationLoop()
override void OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 61 of file ActionDrainLiquid.c.
References GetGame(), ActionData::m_Target, and CGame::RPCSingleParam().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 44 of file ActionDrainLiquid.c.
References ActionData::m_Player, and m_SpecialtyWeight.
OnStartAnimationLoop()
override void OnStartAnimationLoop (ActionData action_data) inline private
Definition at line 50 of file ActionDrainLiquid.c.
References GetGame(), ActionData::m_Target, and CGame::RPCSingleParam().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionDrainLiquid.c