DayZ Scripts: PlayerContainer Class Reference
PlayerContainer Class Reference
Private Member Functions
override void UpdateRadialIcon ()
bool HasEntityContainerVisible (EntityAI entity)
SlotsIcon GetSlotsIcon (int row, int column)
void PlayerContainer (LayoutHolder parent, int sort=-1)
void ~PlayerContainer ()
void ItemAttached (EntityAI item, string slot_name)
void ItemDetached (EntityAI item, string slot_name)
void OnAttachmentReservationSet (EntityAI item, int slot_id)
void OnAttachmentReservationRelease (EntityAI item, int slot_id)
void AddSlotsContainer (int row_count)
void MouseClick (Widget w, int x, int y, int button)
float GetMainContainerTopPos ()
float GetMainContainerBottomPos ()
override void Insert (LayoutHolder container, int pos=-1, bool immedUpdate=true)
bool IsItemWithContainerActive ()
override bool IsItemWithQuantityActive ()
override bool IsItemActive ()
bool IsEmptyItemActive ()
void UnfocusPlayerAttachmentsContainer ()
void DoubleClick (Widget w, int x, int y, int button)
override void ExpandCollapseContainer ()
bool IsContainerWithCargoActive ()
bool IsItemWithAttachmentsActive ()
override bool TransferItemToVicinity ()
override bool InspectItem ()
int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2)
override bool CanCombine ()
override bool SplitItem ()
override bool EquipItem ()
override bool TransferItem ()
override EntityAI GetFocusedItem ()
override bool Combine ()
override bool Select ()
void SetPlayer (PlayerBase player)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
ItemPreviewWidget GetItemPreviewWidget (Widget w)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override void DraggingOver (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromGhostArea (Widget w, int x, int y, Widget receiver)
void SwapItemsInOrder (int slot1, int slot2)
override void UpdateInterval ()
void ToggleContainer (Widget w, EntityAI item)
void ToggleWidget (Widget w)
override void CollapseButtonOnMouseButtonDown (Widget w)
bool IsPlayerEquipmentActive ()
override void Refresh ()
override bool OnChildRemove (Widget w, Widget child)
override bool OnChildAdd (Widget w, Widget child)
Private Attributes
protected ref AttachmentsGroupContainer m_PlayerAttachmentsContainer
protected ref map< int, SlotsIcon > m_InventorySlots
protected ref map< EntityAI, ref Container > m_ShowedItems = new ref map<EntityAI, ref Container>
protected ref map< int, ref Container > m_ShowedItemsIDs = new ref map<int, ref Container>
protected PlayerBase m_Player
protected const int HEADER_INDEX_OFFSET = 2
Detailed Description
Definition at line 1 of file PlayerContainer.c.
Constructor & Destructor Documentation
PlayerContainer()
void PlayerContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 34 of file PlayerContainer.c.
References AddSlotsContainer(), SlotsIcon::Clear(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), SlotsIcon::GetGhostSlot(), CollapsibleContainer::GetHeader(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), InventorySlots::GetSlotDisplayName(), InventorySlots::GetSlotIdFromString(), GetSlotsIcon(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, ITEMS_IN_ROW, CollapsibleContainer::m_CollapsibleHeader, m_InventorySlots, m_PlayerAttachmentsContainer, m_RootWidget, path, WidgetEventHandler::RegisterOnChildAdd(), WidgetEventHandler::RegisterOnChildRemove(), WidgetEventHandler::RegisterOnDoubleClick(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), AttachmentsGroupContainer::SetHeader(), CollapsibleContainer::SetHeader(), Header::SetName(), SlotsIcon::SetSlotDisplayName(), SlotsIcon::SetSlotID(), and StaticGUIUtils::VerifyIconImageString().
~PlayerContainer()
void ~PlayerContainer () inline private
Definition at line 104 of file PlayerContainer.c.
References ItemAttached(), ItemDetached(), m_Player, OnAttachmentReservationRelease(), and OnAttachmentReservationSet().
Member Function Documentation
AddSlotsContainer()
void AddSlotsContainer (int row_count) inline private
Definition at line 221 of file PlayerContainer.c.
References m_Player, and m_PlayerAttachmentsContainer.
Referenced by PlayerContainer().
CanCombine()
override bool CanCombine () inline private
Definition at line 507 of file PlayerContainer.c.
References ItemManager::GetCombinationFlags(), GetFocusedItem(), GetGame(), and GetPlayer().
Referenced by UpdateConsoleToolbar().
CollapseButtonOnMouseButtonDown()
override void CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 1082 of file PlayerContainer.c.
Combine()
override bool Combine () inline private
Definition at line 583 of file PlayerContainer.c.
References Icon::CombineItems(), GetFocusedItem(), GetGame(), ItemManager::GetHandsPreview(), HandsPreview::GetIcon(), ItemManager::GetInstance(), and GetPlayer().
Referenced by RightArea::Combine().
DoubleClick()
void DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 370 of file PlayerContainer.c.
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), InventoryMenu(), SlotsIcon::IsReserved(), m_Player, MENU_INVENTORY, name, string::Replace(), and ToggleWidget().
DraggingOver()
override void DraggingOver (Widget w, int x, int y, Widget receiver) inline private
Definition at line 801 of file PlayerContainer.c.
References GameInventory::CanSwapEntitiesEx(), ColorManager::COMBINE_COLOR, SlotsIcon::GetEntity(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetItemPreviewWidget(), ItemManager::GetRightDropzone(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), SlotsIcon::IsReserved(), m_Player, ColorManager::RED_COLOR, ColorManager::SetColor(), and ColorManager::SWAP_COLOR.
DraggingOverHeader()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 767 of file PlayerContainer.c.
References ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetItemPreviewWidget(), ItemManager::GetRightDropzone(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_Player, ColorManager::RED_COLOR, and ColorManager::SetColor().
Referenced by RightArea::DraggingOverHeader().
EquipItem()
override bool EquipItem () inline private
Definition at line 525 of file PlayerContainer.c.
References GetFocusedItem(), GetGame(), and CGame::GetPlayer().
Referenced by RightArea::EquipItem().
ExpandCollapseContainer()
override void ExpandCollapseContainer () inline private
Definition at line 442 of file PlayerContainer.c.
References m_PlayerAttachmentsContainer, and ToggleWidget().
Referenced by RightArea::ExpandCollapseContainer().
GetFocusedItem()
override EntityAI GetFocusedItem () inline private
Definition at line 578 of file PlayerContainer.c.
Referenced by CanCombine(), Combine(), EquipItem(), InspectItem(), IsEmptyItemActive(), IsItemActive(), IsItemWithContainerActive(), IsItemWithQuantityActive(), TransferItem(), and TransferItemToVicinity().
GetItemPreviewWidget()
ItemPreviewWidget GetItemPreviewWidget (Widget w) inline private
Definition at line 750 of file PlayerContainer.c.
References name, and string::Replace().
Referenced by DraggingOver(), DraggingOverHeader(), OnDropReceivedFromGhostArea(), and OnDropReceivedFromHeader().
GetMainContainerBottomPos()
float GetMainContainerBottomPos () inline private
Definition at line 300 of file PlayerContainer.c.
References x, and y.
GetMainContainerTopPos()
float GetMainContainerTopPos () inline private
Definition at line 293 of file PlayerContainer.c.
References x, and y.
GetRecipeCount()
int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2) inline private
Definition at line 501 of file PlayerContainer.c.
References GetGame(), GetPlayer(), and GetPlugin().
GetSlotsIcon()
SlotsIcon GetSlotsIcon (int row, int column) inline private
Definition at line 29 of file PlayerContainer.c.
References AttachmentsGroupContainer::GetSlotsIcon(), and m_PlayerAttachmentsContainer.
Referenced by PlayerContainer(), and SetPlayer().
HasEntityContainerVisible()
bool HasEntityContainerVisible (EntityAI entity) inline private
Definition at line 23 of file PlayerContainer.c.
References ClosableContainer::IsOpened(), and m_ShowedItems.
Referenced by RightArea::HasEntityContainerVisible().
Insert()
override void Insert (LayoutHolder container, int pos = -1, bool immedUpdate = true) inline private
Definition at line 310 of file PlayerContainer.c.
InspectItem()
override bool InspectItem () inline private
Definition at line 482 of file PlayerContainer.c.
References GetFocusedItem(), GetGame(), CGame::GetPlayer(), and InspectItem().
Referenced by RightArea::InspectItem(), InspectItem(), and MouseClick().
IsContainerWithCargoActive()
bool IsContainerWithCargoActive () inline private
Definition at line 450 of file PlayerContainer.c.
Referenced by UpdateConsoleToolbar().
IsEmptyItemActive()
bool IsEmptyItemActive () inline private
Definition at line 359 of file PlayerContainer.c.
References GetFocusedItem().
Referenced by UpdateConsoleToolbar().
IsItemActive()
override bool IsItemActive () inline private
Definition at line 353 of file PlayerContainer.c.
References GetFocusedItem(), IsItemWithContainerActive(), and IsItemWithQuantityActive().
Referenced by UpdateConsoleToolbar().
IsItemWithAttachmentsActive()
bool IsItemWithAttachmentsActive () inline private
Definition at line 455 of file PlayerContainer.c.
Referenced by UpdateConsoleToolbar().
IsItemWithContainerActive()
bool IsItemWithContainerActive () inline private
Definition at line 341 of file PlayerContainer.c.
References GetFocusedItem().
Referenced by IsItemActive(), and UpdateConsoleToolbar().
IsItemWithQuantityActive()
override bool IsItemWithQuantityActive () inline private
Definition at line 347 of file PlayerContainer.c.
References GetFocusedItem(), and QuantityConversions::HasItemQuantity().
Referenced by IsItemActive(), and UpdateConsoleToolbar().
IsPlayerEquipmentActive()
bool IsPlayerEquipmentActive () inline private
Definition at line 1087 of file PlayerContainer.c.
Referenced by RightArea::IsPlayerEquipmentActive(), and UpdateConsoleToolbar().
ItemAttached()
void ItemAttached (EntityAI item, string slot_name) inline private
Definition at line 115 of file PlayerContainer.c.
References CGame::ConfigIsExisting(), GetGame(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), SlotsIcon::GetRadialIconPanel(), InventorySlots::GetSlotIdFromString(), SlotsIcon::Init(), Inventory(), ClosableContainer::IsOpened(), SlotsIcon::IsReserved(), m_InventorySlots, m_Player, m_ShowedItems, name, Refresh(), and WidgetEventHandler::RegisterOnMouseButtonUp().
Referenced by SetPlayer(), and ~PlayerContainer().
ItemDetached()
void ItemDetached (EntityAI item, string slot_name) inline private
Definition at line 180 of file PlayerContainer.c.
References SlotsIcon::Clear(), InventorySlots::GetSlotIdFromString(), Inventory(), m_InventorySlots, m_ShowedItems, Refresh(), and CollapsibleContainer::Remove().
Referenced by SetPlayer(), and ~PlayerContainer().
MouseClick()
void MouseClick (Widget w, int x, int y, int button) inline private
Definition at line 228 of file PlayerContainer.c.
References g_Game, GetDayZGame(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), SlotsIcon::GetSlotID(), InspectItem(), IsLeftCtrlDown(), SlotsIcon::IsReserved(), m_Player, and ItemManager::SetWidgetDraggable().
OnAttachmentReservationRelease()
void OnAttachmentReservationRelease (EntityAI item, int slot_id) inline private
Definition at line 215 of file PlayerContainer.c.
References SlotsIcon::Clear(), and m_InventorySlots.
Referenced by SetPlayer(), and ~PlayerContainer().
OnAttachmentReservationSet()
void OnAttachmentReservationSet (EntityAI item, int slot_id) inline private
Definition at line 205 of file PlayerContainer.c.
References SlotsIcon::Init(), and m_InventorySlots.
Referenced by SetPlayer(), and ~PlayerContainer().
OnChildAdd()
override bool OnChildAdd (Widget w, Widget child) inline private
Definition at line 1111 of file PlayerContainer.c.
References Refresh().
OnChildRemove()
override bool OnChildRemove (Widget w, Widget child) inline private
Definition at line 1105 of file PlayerContainer.c.
References Refresh().
OnDropReceivedFromGhostArea()
void OnDropReceivedFromGhostArea (Widget w, int x, int y, Widget receiver) inline private
Definition at line 895 of file PlayerContainer.c.
References GameInventory::CanSwapEntitiesEx(), CombineItemsClient(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetItemPreviewWidget(), InventoryLocation::GetParent(), CGame::GetPlayer(), GetPlayer(), SlotsIcon::GetSlotID(), ItemManager::HideDropzones(), InventoryMenu(), SlotsIcon::IsReserved(), InventoryLocation::IsValid(), m_Player, MENU_INVENTORY, ItemManager::SetIsDragging(), and SplitItemUtils::TakeOrSplitToInventory().
OnDropReceivedFromHeader()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 726 of file PlayerContainer.c.
References ItemPreviewWidget::GetItem(), GetItemPreviewWidget(), and m_Player.
Refresh()
override void Refresh () inline private
Definition at line 1097 of file PlayerContainer.c.
References m_RootWidget.
Referenced by ItemAttached(), ItemDetached(), OnChildAdd(), OnChildRemove(), RightArea::Refresh(), ToggleContainer(), and ToggleWidget().
Select()
override bool Select () inline private
Definition at line 604 of file PlayerContainer.c.
References GameInventory::CanSwapEntitiesEx(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), InventoryLocation::GetParent(), GetPlayer(), ItemManager::GetSelectedItem(), SlotsIcon::GetSlotID(), SlotsIcon::IsReserved(), m_Player, and ItemManager::SetSelectedItem().
Referenced by RightArea::Select().
SetPlayer()
void SetPlayer (PlayerBase player) inline private
Definition at line 681 of file PlayerContainer.c.
References SlotsIcon::Clear(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), GetGame(), InventorySlots::GetSlotIdFromString(), GetSlotsIcon(), ItemAttached(), ItemDetached(), ITEMS_IN_ROW, m_Player, OnAttachmentReservationRelease(), OnAttachmentReservationSet(), and SlotsIcon::SetSlotParent().
Referenced by RightArea::RightArea(), and VicinityContainer::UpdateInterval().
SplitItem()
override bool SplitItem () inline private
Definition at line 515 of file PlayerContainer.c.
Referenced by RightArea::SplitItem().
SwapItemsInOrder()
void SwapItemsInOrder (int slot1, int slot2) inline private
Definition at line 1005 of file PlayerContainer.c.
References m_Player, and m_ShowedItems.
Referenced by RightArea::SwapItemsInOrder().
ToggleContainer()
void ToggleContainer (Widget w, EntityAI item) inline private
Definition at line 1050 of file PlayerContainer.c.
References InventoryLocation::GetSlot(), m_InventorySlots, m_ShowedItems, and Refresh().
Referenced by ToggleWidget().
ToggleWidget()
void ToggleWidget (Widget w) inline private
Definition at line 1064 of file PlayerContainer.c.
References ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::IsDragging(), name, Refresh(), string::Replace(), and ToggleContainer().
Referenced by DoubleClick(), and ExpandCollapseContainer().
TransferItem()
override bool TransferItem () inline private
Definition at line 543 of file PlayerContainer.c.
References GetFocusedItem(), GetGame(), GetParent(), and CGame::GetPlayer().
Referenced by RightArea::TransferItem().
TransferItemToVicinity()
override bool TransferItemToVicinity () inline private
Definition at line 460 of file PlayerContainer.c.
References GetFocusedItem(), GetGame(), and CGame::GetPlayer().
Referenced by RightArea::TransferItemToVicinity().
UnfocusPlayerAttachmentsContainer()
void UnfocusPlayerAttachmentsContainer () inline private
Definition at line 365 of file PlayerContainer.c.
References m_PlayerAttachmentsContainer, and Container::UnfocusAll().
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 1028 of file PlayerContainer.c.
References m_InventorySlots, m_ShowedItems, Container::UpdateInterval(), and SlotsIcon::UpdateInterval().
Referenced by RightArea::UpdateInterval().
UpdateRadialIcon()
override void UpdateRadialIcon () inline private
Definition at line 11 of file PlayerContainer.c.
References CollapsibleContainer::IsHidden(), and m_Player.
Field Documentation
HEADER_INDEX_OFFSET
protected const int HEADER_INDEX_OFFSET = 2 private
Definition at line 9 of file PlayerContainer.c.
m_InventorySlots
protected ref map<int, SlotsIcon> m_InventorySlots private
Definition at line 4 of file PlayerContainer.c.
Referenced by ItemAttached(), ItemDetached(), OnAttachmentReservationRelease(), OnAttachmentReservationSet(), PlayerContainer(), ToggleContainer(), and UpdateInterval().
m_Player
protected PlayerBase m_Player private
Definition at line 7 of file PlayerContainer.c.
Referenced by AddSlotsContainer(), DoubleClick(), DraggingOver(), DraggingOverHeader(), ItemAttached(), MouseClick(), OnDropReceivedFromGhostArea(), OnDropReceivedFromHeader(), Select(), SetPlayer(), SwapItemsInOrder(), UpdateRadialIcon(), and ~PlayerContainer().
m_PlayerAttachmentsContainer
protected ref AttachmentsGroupContainer m_PlayerAttachmentsContainer private
Definition at line 3 of file PlayerContainer.c.
Referenced by AddSlotsContainer(), ExpandCollapseContainer(), GetSlotsIcon(), PlayerContainer(), and UnfocusPlayerAttachmentsContainer().
m_ShowedItems
protected ref map<EntityAI, ref Container> m_ShowedItems = new ref map<EntityAI, ref Container> private
Definition at line 5 of file PlayerContainer.c.
Referenced by HasEntityContainerVisible(), ItemAttached(), ItemDetached(), SwapItemsInOrder(), ToggleContainer(), and UpdateInterval().
m_ShowedItemsIDs
protected ref map<int, ref Container> m_ShowedItemsIDs = new ref map<int, ref Container> private
Definition at line 6 of file PlayerContainer.c.
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Inherited/PlayerContainer.c