DayZ Scripts: EntityPlacementCallback Class Reference
EntityPlacementCallback Class Reference
Private Member Functions
void EntityPlacementCallback ()
void ~EntityPlacementCallback ()
void ClearDebugShapes ()
override void OnSetup ()
override void OnDebug (vector p0, vector p1, bool hasHit, bool found)
override bool OnFirstContact (Object other)
override bool OnQuery (Object other)
override bool OnCollide (Object other)
Constructor & Destructor Documentation
EntityPlacementCallback()
void EntityPlacementCallback () inline private
~EntityPlacementCallback()
void ~EntityPlacementCallback () inline private
References ClearDebugShapes().
Member Function Documentation
ClearDebugShapes()
void ClearDebugShapes () inline private
Referenced by OnSetup(), and ~EntityPlacementCallback().
OnCollide()
override bool OnCollide (Object other) inline private
OnDebug()
override void OnDebug (vector p0, vector p1, bool hasHit, bool found) inline private
References m_Extents, m_Transform, and Shape.
OnFirstContact()
override bool OnFirstContact (Object other) inline private
OnQuery()
override bool OnQuery (Object other) inline private
References Class::CastTo().
OnSetup()
override void OnSetup () inline private
References Class::CastTo(), ClearDebugShapes(), Math::Cos(), DiagMenu::GetBool(), HumanInputController::GetHeadingAngle(), m_DebugEnabled, m_DirectionFunc, m_Owner, m_OwnerDirection, m_OwnerPosition, vector::Normalized(), Math::PI_HALF, and Math::Sin().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Systems/Inventory/EntityPlacementCallback.c