DayZ Scripts: ChatLine Class Reference
ChatLine Class Reference
Private Member Functions
void ChatLine (Widget root_widget)
void ~ChatLine ()
void Set (ChatMessageEventParams params)
private void SetColour (int colour)
protected void SetColorByParam (string pParamValue, int pFallback)
void Clear ()
protected int ColorNameToColor (string pColorName)
Private Attributes
const float FADE_TIMEOUT = 30
const float FADE_OUT_DURATION = 3
const float FADE_IN_DURATION = 0.5
private const string RADIO_PREFIX = "(" + "#str_radio" + ") "
private const string GAME_PREFIX = "(" + "#layout_chat_game" + ") "
private const string ADMIN_PREFIX = "(" + "#STR_MP_MASTER" + ") "
private const int DEFAULT_COLOUR = ARGB(255, 255, 255, 255)
private const int GAME_TEXT_COLOUR = ARGB(255, 255, 0, 0)
private const int ADMIN_TEXT_COLOUR = ARGB(255, 255, 255, 0)
Widget m_RootWidget
TextWidget m_NameWidget
TextWidget m_TextWidget
private ref WidgetFadeTimer m_FadeTimer
private ref Timer m_TimeoutTimer
Constructor & Destructor Documentation
ChatLine()
void ChatLine (Widget root_widget) inline private
References CALL_CATEGORY_GUI, WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_FadeTimer, m_NameWidget, m_RootWidget, m_TextWidget, and m_TimeoutTimer.
~ChatLine()
void ~ChatLine () inline private
References m_TextWidget.
Member Function Documentation
Clear()
void Clear () inline private
References m_FadeTimer, m_RootWidget, m_TimeoutTimer, and Timer::Stop().
ColorNameToColor()
protected int ColorNameToColor (string pColorName) inline private
References COLOR_BLUE, COLOR_GREEN, COLOR_RED, and COLOR_YELLOW.
Referenced by SetColorByParam().
Set()
void Set (ChatMessageEventParams params) inline private
References ADMIN_PREFIX, ADMIN_TEXT_COLOUR, DEFAULT_COLOUR, FADE_IN_DURATION, FADE_OUT_DURATION, FADE_TIMEOUT, GAME_PREFIX, GAME_TEXT_COLOUR, m_FadeTimer, m_NameWidget, m_RootWidget, m_TextWidget, m_TimeoutTimer, RADIO_PREFIX, SetColorByParam(), and SetColour().
Referenced by Chat::AddInternal().
SetColorByParam()
protected void SetColorByParam (string pParamValue, int pFallback) inline private
References ColorNameToColor(), and SetColour().
Referenced by Set().
SetColour()
private void SetColour (int colour) inline private
References m_NameWidget, and m_TextWidget.
Referenced by Set(), and SetColorByParam().
Field Documentation
ADMIN_PREFIX
private const string ADMIN_PREFIX = "(" + "#STR_MP_MASTER" + ") " private
Referenced by Set().
ADMIN_TEXT_COLOUR
private const int ADMIN_TEXT_COLOUR = ARGB(255, 255, 255, 0) private
Referenced by Set().
DEFAULT_COLOUR
private const int DEFAULT_COLOUR = ARGB(255, 255, 255, 255) private
Referenced by Set().
FADE_IN_DURATION
const float FADE_IN_DURATION = 0.5 private
Referenced by Set().
FADE_OUT_DURATION
const float FADE_OUT_DURATION = 3 private
Referenced by Set().
FADE_TIMEOUT
const float FADE_TIMEOUT = 30 private
Referenced by Set().
GAME_PREFIX
private const string GAME_PREFIX = "(" + "#layout_chat_game" + ") " private
Referenced by Set().
GAME_TEXT_COLOUR
private const int GAME_TEXT_COLOUR = ARGB(255, 255, 0, 0) private
Referenced by Set().
m_FadeTimer
private ref WidgetFadeTimer m_FadeTimer private
Referenced by ChatLine(), Clear(), and Set().
m_NameWidget
TextWidget m_NameWidget private
Referenced by ChatLine(), Set(), and SetColour().
m_RootWidget
Widget m_RootWidget private
Referenced by Chat::AddInternal(), ChatLine(), Clear(), and Set().
m_TextWidget
TextWidget m_TextWidget private
Referenced by ChatLine(), Set(), SetColour(), and ~ChatLine().
m_TimeoutTimer
private ref Timer m_TimeoutTimer private
Referenced by ChatLine(), Clear(), and Set().
RADIO_PREFIX
private const string RADIO_PREFIX = "(" + "#str_radio" + ") " private
Referenced by Set().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/Chat/ChatLine.c