DayZ Scripts: PoweredOptic_Base Class Reference
PoweredOptic_Base Class Reference
Private Member Functions
void NVGoggles ()
override void SetActions ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWork (float consumed_energy)
void LoweredCheck ()
void RotateGoggles (bool state)
void SwitchOnNVGCheck ()
override int GetCurrentNVType ()
override bool IsNVG ()
void Rangefinder ()
float GetMeasurementUpdateInterval ()
override void OnWorkStart ()
override void OnWorkStop ()
void StartPeriodicMeasurement ()
void StopPeriodicMeasurement ()
void DoMeasurement ()
override void SetActions ()
override void OnDebugSpawn ()
Private Attributes
bool m_IsLowered
Clothing m_Strap
ref Timer m_WorkCheckTimer
protected ref Timer m_Timer
protected TextWidget m_RangeText
Static Private Attributes
static const float RANGEFINDER_MAX_DISTANCE = 913.4856
Member Function Documentation
DoMeasurement()
void DoMeasurement () inline private
References vector::Distance(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), GetPlayer(), RANGEFINDER_MAX_DISTANCE, DayZPhysics::RaycastRV(), Math::Round(), and float::ToString().
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name) inline private
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name) inline private
GetCurrentNVType()
override int GetCurrentNVType () inline private
References Error().
GetMeasurementUpdateInterval()
float GetMeasurementUpdateInterval () inline private
Referenced by StartPeriodicMeasurement().
IsNVG()
override bool IsNVG () inline private
LoweredCheck()
void LoweredCheck () inline private
NVGoggles()
void NVGoggles () inline private
References RotateGoggles().
OnDebugSpawn()
override void OnDebugSpawn () inline private
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
References RotateGoggles().
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id) inline private
References RotateGoggles().
OnWork()
override void OnWork (float consumed_energy) inline private
References GetGame(), and RotateGoggles().
OnWorkStart() [1/2]
override void OnWorkStart () inline private
References GetGame(), and RotateGoggles().
OnWorkStart() [2/2]
override void OnWorkStart () inline private
References GetGame(), GetPlayer(), and StartPeriodicMeasurement().
OnWorkStop() [1/2]
override void OnWorkStop () inline private
References GetGame().
OnWorkStop() [2/2]
override void OnWorkStop () inline private
References GetGame(), GetPlayer(), and StopPeriodicMeasurement().
Rangefinder()
void Rangefinder () inline private
RotateGoggles()
void RotateGoggles (bool state) inline private
Referenced by NVGoggles(), OnWasAttached(), OnWasDetached(), OnWork(), and OnWorkStart().
SetActions() [1/2]
override void SetActions () inline private
References AddAction(), and RemoveAction().
SetActions() [2/2]
override void SetActions () inline private
References AddAction(), and RemoveAction().
StartPeriodicMeasurement()
void StartPeriodicMeasurement () inline private
References CALL_CATEGORY_GAMEPLAY, GetGame(), GetMeasurementUpdateInterval(), and m_Timer.
Referenced by OnWorkStart().
StopPeriodicMeasurement()
void StopPeriodicMeasurement () inline private
References m_RangeText, m_Timer, and Timer::Stop().
Referenced by OnWorkStop().
SwitchOnNVGCheck()
void SwitchOnNVGCheck () inline private
Field Documentation
m_IsLowered
bool m_IsLowered private
m_RangeText
protected TextWidget m_RangeText private
Referenced by StopPeriodicMeasurement().
m_Strap
Clothing m_Strap private
m_Timer
protected ref Timer m_Timer private
m_WorkCheckTimer
ref Timer m_WorkCheckTimer private
RANGEFINDER_MAX_DISTANCE
const float RANGEFINDER_MAX_DISTANCE = 913.4856 static private
Referenced by DoMeasurement().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/NVGoggles.c
P:/scripts/4_World/Entities/ItemBase/Rangefinder.c