DayZ Scripts: P:/scripts/4_World/Entities/Grenade_Base/RDG2SmokeGrenade_ColorBase.c File Reference
RDG2SmokeGrenade_ColorBase.c File Reference
Data Structures
class SmokeGrenadeBase
class RDG2SmokeGrenade_ColorBase
Functions
class RDG2SmokeGrenade_Black extends RDG2SmokeGrenade_ColorBase RDG2SmokeGrenade_White ()
void RDG2SmokeGrenade_Black ()
Function Documentation
RDG2SmokeGrenade_Black()
void RDG2SmokeGrenade_Black ()
References ParticleList::GRENADE_RDG2_WHITE_END, ParticleList::GRENADE_RDG2_WHITE_LOOP, ParticleList::GRENADE_RDG2_WHITE_START, SetParticleSmokeEnd(), SetParticleSmokeLoop(), and SetParticleSmokeStart().
RDG2SmokeGrenade_White()
class RDG2SmokeGrenade_Black extends RDG2SmokeGrenade_ColorBase RDG2SmokeGrenade_White ()