DayZ Scripts: PlayerStatBase Class Reference
PlayerStatBase Class Reference
Private Member Functions
void OnStoreSave (ParamsWriteContext ctx)
bool OnStoreLoad (ParamsReadContext ctx)
void OnRPC (ParamsReadContext ctx)
float Get ()
string GetLabel ()
void SetByFloat (float value)
void SetByFloatEx (float value, string system="")
bool IsSynced ()
array< PlayerStatRecord > GetRecords ()
void Init (int id)
void SerializeValue (array< ref StatDebugObject > objects, int flags)
float GetNormalized ()
float GetMax ()
float GetMin ()
int GetType ()
void PlayerStat (T min, T max, T init, string label, int flags)
override void Init (int id)
override void SerializeValue (array< ref StatDebugObject > objects, int flags)
PlayerStats GetManager ()
void Set (T value, string system="")
void SetByFloat (float value, string system="")
override void SetByFloatEx (float value, string system="")
void Add (T value, string system="")
override float Get ()
override string GetLabel ()
override float GetMax ()
override float GetMin ()
override float GetNormalized ()
override array< PlayerStatRecord > GetRecords ()
void CreateRecord (float value, string system)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx)
Private Attributes
int m_Type
protected T m_MinValue
protected T m_MaxValue
protected T m_Value
protected string m_ValueLabel
protected int m_Flags
ref array< PlayerStatRecord > m_Records
PlayerStats m_Manager
Member Function Documentation
Add()
void Add (T value, string system = "") inline private
References m_Value, and Set().
CreateRecord()
void CreateRecord (float value, string system) inline private
References GetGame(), and GetTime().
Get() [1/2]
float Get () private
Referenced by GetNormalized(), and SerializeValue().
Get() [2/2]
override float Get () inline private
References m_Value.
GetLabel() [1/2]
string GetLabel () private
Referenced by SerializeValue().
GetLabel() [2/2]
override string GetLabel () inline private
References m_ValueLabel.
GetManager()
PlayerStats GetManager () inline private
References m_Manager.
GetMax() [1/2]
float GetMax () private
Referenced by GetNormalized().
GetMax() [2/2]
override float GetMax () inline private
References m_MaxValue.
GetMin() [1/2]
float GetMin () private
Referenced by GetNormalized().
GetMin() [2/2]
override float GetMin () inline private
References m_MinValue.
GetNormalized() [1/2]
float GetNormalized () private
GetNormalized() [2/2]
override float GetNormalized () inline private
References Get(), GetMax(), GetMin(), and Math::InverseLerp().
GetRecords() [1/2]
array< PlayerStatRecord > GetRecords () private
GetRecords() [2/2]
override array< PlayerStatRecord > GetRecords () inline private
References m_Records.
GetType()
int GetType () inline private
References m_Type.
Init() [1/2]
void Init (int id) private
Referenced by RegisterStat().
Init() [2/2]
override void Init (int id) inline private
References m_Type.
IsSynced()
bool IsSynced () private
OnRPC()
void OnRPC (ParamsReadContext ctx) private
OnStoreLoad() [1/2]
bool OnStoreLoad (ParamsReadContext ctx) private
OnStoreLoad() [2/2]
override bool OnStoreLoad (ParamsReadContext ctx) inline private
References m_Value, and Serializer::Read().
OnStoreSave() [1/2]
void OnStoreSave (ParamsWriteContext ctx) private
OnStoreSave() [2/2]
override void OnStoreSave (ParamsWriteContext ctx) inline private
References m_Value, and Serializer::Write().
PlayerStat()
void PlayerStat (T min, T max, T init, string label, int flags) inline private
References init, m_MaxValue, m_MinValue, and m_Value.
SerializeValue() [1/2]
void SerializeValue (array< ref StatDebugObject > objects, int flags) private
SerializeValue() [2/2]
override void SerializeValue (array< ref StatDebugObject > objects, int flags) inline private
References Get(), and GetLabel().
Set()
void Set (T value, string system = "") inline private
References m_MaxValue, m_MaxValue, m_MinValue, m_MinValue, and m_Value.
Referenced by Add(), and SetByFloat().
SetByFloat() [1/2]
void SetByFloat (float value) private
Referenced by SetByFloatEx().
SetByFloat() [2/2]
void SetByFloat (float value, string system = "") inline private
References Set().
SetByFloatEx() [1/2]
void SetByFloatEx (float value, string system = "") private
SetByFloatEx() [2/2]
override void SetByFloatEx (float value, string system = "") inline private
References SetByFloat().
Field Documentation
m_Flags
protected int m_Flags private
m_Manager
PlayerStats m_Manager private
Referenced by GetManager().
m_MaxValue
protected T m_MaxValue private
Referenced by GetMax(), and Set().
m_MinValue
protected T m_MinValue private
Referenced by GetMin(), and Set().
m_Records
ref array<PlayerStatRecord> m_Records private
Referenced by GetRecords().
m_Type
int m_Type private
Referenced by GetType().
m_Value
protected T m_Value private
Referenced by Get().
m_ValueLabel
protected string m_ValueLabel private
Referenced by GetLabel().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerStats/PlayerStatBase.c