DayZ Scripts: EffectBoatWaterBase Class Reference
EffectBoatWaterBase Class Reference
Private Member Functions
override void AttachTo (Object obj, vector local_pos="0 0 0", vector local_ori="0 0 0", bool force_rotation_to_world=false)
void SetParticleState (int state)
protected void EnableEmitor (Particle ptc, int id, bool enable)
protected void UpdateSpeedState (Particle ptc, float speed)
void Update ()
protected void UpdatePosToSeaLevel (float surfaceOffset=0)
Private Attributes
protected int m_EmitorCount
protected int m_SpeedSlow
protected int m_SpeedMedium
protected int m_SpeedFast
protected EBoatSpeed m_SpeedState
protected BoatScript m_Boat
protected vector m_MemPointPos
Member Function Documentation
AttachTo()
override void AttachTo (Object obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0", bool force_rotation_to_world = false) inline private
References m_Boat, and m_MemPointPos.
Referenced by BoatScript::BoatScript().
EnableEmitor()
protected void EnableEmitor (Particle ptc, int id, bool enable) inline private
References Particle::GetParameterOriginal(), and Particle::SetParameter().
Referenced by Update(), UpdateSpeedState(), and EffectBoatWaterBack::UpdateSpeedState().
SetParticleState()
void SetParticleState (int state) inline private
References IsPlaying(), EffectParticle::SetParticleID(), EffectParticle::Start(), and EffectParticle::Stop().
Referenced by EffectBoatWaterBack::EffectBoatWaterBack(), EffectBoatWaterFront(), and EffectBoatWaterSide().
Update()
void Update () inline private
References IsPlaying(), m_SpeedState, and EffectParticle::Start().
Referenced by BoatScript::UpdateParticles().
UpdatePosToSeaLevel()
protected void UpdatePosToSeaLevel (float surfaceOffset = 0) inline private
References GetGame(), m_Boat, m_MemPointPos, EffectParticle::SetCurrentLocalPosition(), and CGame::SurfaceGetSeaLevel().
Referenced by Update().
UpdateSpeedState()
protected void UpdateSpeedState (Particle ptc, float speed) inline private
Referenced by Update().
Field Documentation
m_Boat
protected BoatScript m_Boat private
Referenced by AttachTo(), EffectBoatWaterBack::Update(), and UpdatePosToSeaLevel().
m_EmitorCount
protected int m_EmitorCount private
Referenced by EffectBoatWaterBack::EffectBoatWaterBack(), Update(), EffectBoatWaterBack::Update(), UpdateSpeedState(), and EffectBoatWaterBack::UpdateSpeedState().
m_MemPointPos
protected vector m_MemPointPos private
Referenced by AttachTo(), and UpdatePosToSeaLevel().
m_SpeedFast
protected int m_SpeedFast private
Referenced by EffectBoatWaterBack::EffectBoatWaterBack(), EffectBoatWaterBack::Update(), and EffectBoatWaterBack::UpdateSpeedState().
m_SpeedMedium
protected int m_SpeedMedium private
Referenced by EffectBoatWaterBack::EffectBoatWaterBack(), and EffectBoatWaterBack::UpdateSpeedState().
m_SpeedSlow
protected int m_SpeedSlow private
Referenced by EffectBoatWaterBack::EffectBoatWaterBack(), and EffectBoatWaterBack::UpdateSpeedState().
m_SpeedState
protected EBoatSpeed m_SpeedState private
Referenced by Update(), UpdateSpeedState(), and EffectBoatWaterBack::UpdateSpeedState().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Effects/BoatWaterEffects.c