DayZ Scripts: HumanInventoryWithFSM Class Reference
HumanInventoryWithFSM Class Reference
HumanInventory... with FSM (synchronous, no anims)
Private Member Functions
void HumanInventoryWithFSM ()
void CreateStableStates ()
override void Init ()
bool CanProcessHandEvents ()
override bool ProcessHandEvent (HandEventBase e)
hand's fsm handling of events @NOTE: warning: ProcessHandEvent can be called only within DayZPlayer::HandleInventory (or CommandHandler)
bool ProcessHandAbortEvent (HandEventBase e)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
int GetCurrentStateID ()
bool IsIdle ()
void NetSyncCurrentStateID (int id)
Engine callback - network synchronization of FSM's state. not intended to direct use.
Private Attributes
protected ref HandFSM m_FSM
protected ref HandStateBase m_Empty
hand slot state machine
protected ref HandStateBase m_Equipped
Detailed Description
HumanInventory... with FSM (synchronous, no anims)
Constructor & Destructor Documentation
HumanInventoryWithFSM()
void HumanInventoryWithFSM () inline private
References m_FSM.
Member Function Documentation
CanProcessHandEvents()
bool CanProcessHandEvents () inline private
References m_FSM.
CreateStableStates()
void CreateStableStates () inline private
References HumanInventory::GetManOwner(), m_Empty, and m_Equipped.
Referenced by Init().
GetCurrentStateID()
GetCurrentStateID () inline private
Returns
identifier of current stable state
References m_FSM.
Init()
override void Init () inline private
References CreateStableStates(), HumanInventory::GetManOwner(), hndDebugPrint(), m_Empty, m_Equipped, and m_FSM.
IsIdle()
bool IsIdle () inline private
References m_FSM.
Referenced by HandleFightLogic().
NetSyncCurrentStateID()
NetSyncCurrentStateID (int id) inline private
Engine callback - network synchronization of FSM's state. not intended to direct use.
References m_FSM.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
ProcessHandAbortEvent()
bool ProcessHandAbortEvent (HandEventBase e) inline private
References HumanInventory::GetManOwner(), hndDebugSpam(), and m_FSM.
ProcessHandEvent()
ProcessHandEvent (HandEventBase e) inline private
hand's fsm handling of events @NOTE: warning: ProcessHandEvent can be called only within DayZPlayer::HandleInventory (or CommandHandler)
References HumanInventory::GetManOwner(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_FSM.
Field Documentation
m_Empty
protected ref HandStateBase m_Empty private
hand slot state machine
Referenced by CreateStableStates(), and Init().
m_Equipped
protected ref HandStateBase m_Equipped private
Referenced by CreateStableStates(), and Init().
m_FSM
protected ref HandFSM m_FSM private
Referenced by CanProcessHandEvents(), GetCurrentStateID(), HumanInventoryWithFSM(), Init(), IsIdle(), NetSyncCurrentStateID(), ProcessHandAbortEvent(), and ProcessHandEvent().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/Inventory/HumanInventoryWithFSM.c