DayZ Scripts: Hit_MeatBones Class Reference
Hit_MeatBones Class Reference
Private Member Functions
void Hit_MeatBones ()
override float CalculateStoppingForce (float in_speedf, float out_speedf, string ammoType, float weight)
override void Event_OnStarted ()
void BloodSplatGround (vector start_pos, vector speed_vector, float decay_coef)
void BloodSplatWall ()
override void OnEnterCalculations (Particle p)
override void OnExitCalculations (Particle p, float outSpeedf)
Private Attributes
float m_ScalingByDistance
Detailed Description
Definition at line 1 of file Hit_MeatBones.c.
Constructor & Destructor Documentation
Hit_MeatBones()
void Hit_MeatBones () inline private
Definition at line 5 of file Hit_MeatBones.c.
References ParticleList::IMPACT_MEATBONES_ENTER, ParticleList::IMPACT_MEATBONES_EXIT, ParticleList::IMPACT_MEATBONES_RICOCHET, EffBulletImpactBase::m_AngledEnter, EffBulletImpactBase::m_EnterSplashCoef, EffBulletImpactBase::m_ExitSplashCoef, m_ScalingByDistance, EffBulletImpactBase::MIN_SCALING_PARAM, EffBulletImpactBase::SetEnterParticle(), EffBulletImpactBase::SetExitParticle(), and EffBulletImpactBase::SetRicochetParticle().
Member Function Documentation
BloodSplatGround()
void BloodSplatGround (vector start_pos, vector speed_vector, float decay_coef) inline private
Definition at line 68 of file Hit_MeatBones.c.
References ParticleList::BLOOD_SURFACE_CHUNKS, BloodSplatWall(), GetGame(), EffectParticle::GetParticle(), CGame::GetSurfaceOrientation(), EffBulletImpactBase::m_StoppingForce, ParticleManager(), SEffectManager::PlayInWorld(), Math::RandomFloat(), Particle::ScaleParticleParam(), CGame::SurfaceY(), and Vector().
Referenced by Event_OnStarted().
BloodSplatWall()
void BloodSplatWall () inline private
Definition at line 103 of file Hit_MeatBones.c.
Referenced by BloodSplatGround().
CalculateStoppingForce()
override float CalculateStoppingForce (float in_speedf, float out_speedf, string ammoType, float weight) inline private
Definition at line 19 of file Hit_MeatBones.c.
References EffBulletImpactBase::DEFAULT_PROJECTILE_WEIGHT, EffBulletImpactBase::m_DirectHit, and EffBulletImpactBase::m_ImpactType.
Event_OnStarted()
override void Event_OnStarted () inline private
Definition at line 51 of file Hit_MeatBones.c.
References BloodSplatGround(), GetPosition, vector::Length(), EffBulletImpactBase::m_ExitPos, EffBulletImpactBase::m_ImpactType, EffBulletImpactBase::m_InSpeed, and EffBulletImpactBase::m_OutSpeed.
OnEnterCalculations()
override void OnEnterCalculations (Particle p) inline private
Definition at line 128 of file Hit_MeatBones.c.
References vector::Distance(), CGame::GetCurrentCameraPosition(), GetDayZGame(), GetGame(), EffBulletImpactBase::m_AmmoType, EffBulletImpactBase::m_EnterSplashCoef, EffBulletImpactBase::m_Pos, m_ScalingByDistance, EffBulletImpactBase::m_StoppingForce, EffBulletImpactBase::MIN_SCALING_PARAM, and Particle::ScaleParticleParam().
OnExitCalculations()
override void OnExitCalculations (Particle p, float outSpeedf) inline private
Definition at line 179 of file Hit_MeatBones.c.
References EffBulletImpactBase::m_ExitSplashCoef, EffBulletImpactBase::MIN_SCALING_PARAM, and Particle::ScaleParticleParam().
Field Documentation
m_ScalingByDistance
float m_ScalingByDistance private
Definition at line 3 of file Hit_MeatBones.c.
Referenced by Hit_MeatBones(), and OnEnterCalculations().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Effects/EffectParticle/BulletImpactBase/Hit_MeatBones.c