DayZ Scripts: CollapsibleContainer Class Reference
CollapsibleContainer Class Reference
Private Member Functions
void CollapsibleContainer (LayoutHolder parent, int sort=-1)
override void SetLayoutName ()
EntityAI GetEntity ()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override void Refresh ()
override void OnShow ()
override void OnHide ()
override void Insert (LayoutHolder container, int pos=-1, bool immedUpdate=true)
override void Remove (LayoutHolder container)
bool CanDisplayAnyCategory ()
void UpdateCollapseButtons ()
void LoadDefaultState ()
bool IsHidden ()
void CollapseButtonOnMouseButtonDown (Widget w)
override void Toggle ()
override bool OnChildRemove (Widget w, Widget child)
override bool OnChildAdd (Widget w, Widget child)
override Header GetHeader ()
override void SetHeader (Header header)
void SetCollapsibleHeaderArrowState (bool open)
Private Attributes
protected ref CollapsibleHeader m_CollapsibleHeader
protected bool m_Hidden
Detailed Description
Definition at line 1 of file CollapsibleContainer.c.
Constructor & Destructor Documentation
CollapsibleContainer()
void CollapsibleContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 6 of file CollapsibleContainer.c.
References m_CollapsibleHeader.
Member Function Documentation
CanDisplayAnyCategory()
bool CanDisplayAnyCategory () inline private
Definition at line 86 of file CollapsibleContainer.c.
CollapseButtonOnMouseButtonDown()
void CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 131 of file CollapsibleContainer.c.
References Toggle().
GetEntity()
EntityAI GetEntity () inline private
Definition at line 24 of file CollapsibleContainer.c.
References m_Entity.
GetHeader()
override Header GetHeader () inline private
Definition at line 176 of file CollapsibleContainer.c.
References m_CollapsibleHeader.
Referenced by PlayerContainer::PlayerContainer(), and ZombieContainer::ZombieContainer().
Insert()
override void Insert (LayoutHolder container, int pos = -1, bool immedUpdate = true) inline private
Definition at line 66 of file CollapsibleContainer.c.
References m_Hidden, SetCollapsibleHeaderArrowState(), and UpdateCollapseButtons().
Referenced by AttachmentCategoriesContainer::InitGhostSlots().
IsHidden()
bool IsHidden () inline private
Definition at line 126 of file CollapsibleContainer.c.
References m_Hidden.
Referenced by PlayerContainer::UpdateRadialIcon(), and ZombieContainer::UpdateRadialIcon().
LoadDefaultState()
void LoadDefaultState () inline private
Definition at line 111 of file CollapsibleContainer.c.
References ItemManager::GetDefaultHeaderOpenState(), ItemManager::GetInstance(), m_Hidden, OnHide(), and OnShow().
Referenced by VicinityContainer::VicinityContainer().
OnChildAdd()
override bool OnChildAdd (Widget w, Widget child) inline private
Definition at line 169 of file CollapsibleContainer.c.
OnChildRemove()
override bool OnChildRemove (Widget w, Widget child) inline private
Definition at line 162 of file CollapsibleContainer.c.
OnDropReceivedFromHeader()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 29 of file CollapsibleContainer.c.
OnHide()
override void OnHide () inline private
Definition at line 52 of file CollapsibleContainer.c.
References m_CollapsibleHeader, m_Hidden, and SetCollapsibleHeaderArrowState().
Referenced by LoadDefaultState(), and Toggle().
OnShow()
override void OnShow () inline private
Definition at line 36 of file CollapsibleContainer.c.
References m_Hidden, Container::Open(), and SetCollapsibleHeaderArrowState().
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), LoadDefaultState(), AttachmentCategoriesContainer::Open(), and Toggle().
Refresh()
override void Refresh () inline private
Definition at line 31 of file CollapsibleContainer.c.
Referenced by ZombieContainer::ItemAttached(), ZombieContainer::ItemDetached(), and VicinityContainer::UpdateInterval().
Remove()
override void Remove (LayoutHolder container) inline private
Definition at line 79 of file CollapsibleContainer.c.
References UpdateCollapseButtons().
Referenced by PlayerContainer::ItemDetached(), ZombieContainer::ItemDetached(), and VicinityContainer::UpdateInterval().
SetCollapsibleHeaderArrowState()
void SetCollapsibleHeaderArrowState (bool open) inline private
Definition at line 186 of file CollapsibleContainer.c.
References m_CollapsibleHeader, and CollapsibleHeader::SetArrowButtonOpened().
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), Insert(), OnHide(), OnShow(), and Toggle().
SetHeader()
override void SetHeader (Header header) inline private
Definition at line 181 of file CollapsibleContainer.c.
References m_CollapsibleHeader.
Referenced by PlayerContainer::PlayerContainer(), and ZombieContainer::ZombieContainer().
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 19 of file CollapsibleContainer.c.
References WidgetLayoutName::CollapsibleContainer.
Toggle()
override void Toggle () inline private
Definition at line 136 of file CollapsibleContainer.c.
References Container::Close(), m_Hidden, OnHide(), OnShow(), SetCollapsibleHeaderArrowState(), and UpdateCollapseButtons().
Referenced by CollapseButtonOnMouseButtonDown().
UpdateCollapseButtons()
void UpdateCollapseButtons () inline private
Definition at line 91 of file CollapsibleContainer.c.
References m_CollapsibleHeader, and Header::ShowCollapseButton().
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), Insert(), Remove(), Toggle(), and VicinityContainer::UpdateInterval().
Field Documentation
m_CollapsibleHeader
protected ref CollapsibleHeader m_CollapsibleHeader private
Definition at line 3 of file CollapsibleContainer.c.
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), CollapsibleContainer(), GetHeader(), AttachmentCategoriesContainer::IsHeaderActive(), OnHide(), AttachmentCategoriesContainer::OnHide(), PlayerContainer::PlayerContainer(), SetCollapsibleHeaderArrowState(), SetHeader(), AttachmentCategoriesContainer::SetHeaderName(), ZombieContainer::SetHeaderName(), UpdateCollapseButtons(), AttachmentCategoriesContainer::UpdateInterval(), and VicinityContainer::VicinityContainer().
m_Hidden
protected bool m_Hidden private
Definition at line 4 of file CollapsibleContainer.c.
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), VicinityContainer::CollapseButtonOnMouseButtonDown(), Insert(), IsHidden(), LoadDefaultState(), OnHide(), OnShow(), Toggle(), AttachmentCategoriesContainer::UpdateInterval(), and AttachmentCategoriesContainer::UpdateRadialIcon().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Containers/CollapsibleContainer.c