DayZ Scripts: CAContinuousQuantityExtinguish Class Reference
CAContinuousQuantityExtinguish Class Reference
Private Member Functions
void CAContinuousQuantityExtinguish (float quantity_used_per_second, float time_to_repeat, float wetness_gain_multiplier)
override void CalcAndSetQuantity (ActionData action_data)
override int Interrupt (ActionData action_data)
void MultiplyQuantityUsed (float coef)
Private Attributes
private float m_WetnessGainMultiplier = 1.0
Detailed Description
Definition at line 1 of file CAContinuousQuantityExtinguish.c.
Constructor & Destructor Documentation
CAContinuousQuantityExtinguish()
void CAContinuousQuantityExtinguish (float quantity_used_per_second, float time_to_repeat, float wetness_gain_multiplier) inline private
Definition at line 5 of file CAContinuousQuantityExtinguish.c.
References CAContinuousQuantityRepeat::m_DefaultTimeToRepeat, CAContinuousQuantityRepeat::m_QuantityUsedPerSecond, and m_WetnessGainMultiplier.
Member Function Documentation
CalcAndSetQuantity()
override void CalcAndSetQuantity (ActionData action_data) inline private
Definition at line 12 of file CAContinuousQuantityExtinguish.c.
References GetGame(), ActionData::m_MainItem, CAContinuousQuantityRepeat::m_SpentQuantity, CAContinuousQuantityRepeat::m_SpentUnits, ActionData::m_Target, m_WetnessGainMultiplier, and CABase::SetACData().
Interrupt()
override int Interrupt (ActionData action_data) inline private
Definition at line 38 of file CAContinuousQuantityExtinguish.c.
References GetGame(), ActionData::m_Player, and UASoftSkillsWeight::ROUGH_MEDIUM.
MultiplyQuantityUsed()
void MultiplyQuantityUsed (float coef) inline private
Definition at line 48 of file CAContinuousQuantityExtinguish.c.
References CAContinuousQuantityRepeat::m_QuantityUsedPerSecond.
Referenced by ActionExtinguishFireplaceByExtinguisherCB::CreateActionComponent(), and ActionExtinguishFireplaceByLiquidCB::CreateActionComponent().
Field Documentation
m_WetnessGainMultiplier
private float m_WetnessGainMultiplier = 1.0 private
Definition at line 3 of file CAContinuousQuantityExtinguish.c.
Referenced by CAContinuousQuantityExtinguish(), and CalcAndSetQuantity().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousQuantityExtinguish.c