DayZ Scripts: ActionRepackTentCB Class Reference
ActionRepackTentCB Class Reference
Private Member Functions
override void CreateActionComponent ()
void DropDuringRepacking ()
Member Function Documentation
CreateActionComponent()
override void CreateActionComponent () inline private
References ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, and UATimeSpent::UNPACK.
DropDuringRepacking()
void DropDuringRepacking () inline private
References UAMaxDistances::DEFAULT, vector::DistanceSq(), GetGame(), ActionBaseCB::m_ActionData, ActionData::m_MainItem, ActionData::m_Player, Math3D::MatrixToQuat(), InventoryLocation::SetGroundEx(), CGame::SurfaceY(), and Math3D::YawPitchRollMatrix().
Referenced by ActionRepackTent::OnStartAnimationLoopClient(), and ActionRepackTent::OnStartAnimationLoopServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionRepackTent.c