DayZ Scripts: DayZIntroScene Class Reference
DayZIntroScene Class Reference
Private Member Functions
void DayZIntroScene ()
void ~DayZIntroScene ()
IntroSceneCharacter GetIntroCharacter ()
Camera GetIntroCamera ()
void ResetIntroCamera ()
protected void SetInitPostprocesses ()
Since this can get created at the same time as DayZGame, non-static postprocesses need to be deffered.
protected void GetSelectedUserName ()
protected vector SwapYZ (vector vec)
protected vector SnapToGround (vector pos)
Private Attributes
protected ref IntroSceneCharacter m_Character
protected Camera m_Camera
protected vector m_CameraTrans [4]
protected vector m_CharacterPos
protected vector m_CharacterRot
protected Weather m_Weather
protected vector m_Target
protected ref OptionsMenu m_OptionsMenu
Detailed Description
Definition at line 1 of file DayZIntroScene.c.
Constructor & Destructor Documentation
DayZIntroScene()
void DayZIntroScene () inline private
Definition at line 13 of file DayZIntroScene.c.
References Math::Atan2(), ScriptCallQueue::Call(), CALL_CATEGORY_GUI, Class::CastTo(), Math3D::DirectionAndUpMatrix(), g_Game, CGame::GetCallQueue(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), PPEffects::Init(), Managed::IntroSceneCharacter(), m_Camera, m_CameraTrans, m_Character, m_CharacterPos, m_CharacterRot, m_Target, m_Weather, Math3D::MatrixIdentity4(), vector::Multiply4(), CGame::ObjectDelete(), Math::RAD2DEG, Math::RandomInt(), WeatherPhenomenon::Set(), World::SetDate(), SetInitPostprocesses(), WeatherPhenomenon::SetLimits(), Weather::SetStorm(), Weather::SetWindFunctionParams(), Weather::SetWindMaximumSpeed(), Weather::SetWindSpeed(), SnapToGround(), CGame::SurfaceY(), SwapYZ(), and Vector().
~DayZIntroScene()
void ~DayZIntroScene () inline private
Definition at line 102 of file DayZIntroScene.c.
References PPEManagerStatic::GetPPEManager().
Member Function Documentation
GetIntroCamera()
Camera GetIntroCamera () inline private
Definition at line 119 of file DayZIntroScene.c.
References m_Camera.
Referenced by UIScriptedMenu::OnShow(), and ResetIntroCamera().
GetIntroCharacter()
IntroSceneCharacter GetIntroCharacter () inline private
Definition at line 111 of file DayZIntroScene.c.
References m_Character.
Referenced by UIScriptedMenu::CanSaveDefaultCharacter(), UIScriptedMenu::ConnectLastSession(), UIScriptedMenu::NextCharacter(), UIScriptedMenu::OnChangeCharacter(), UIScriptedMenu::OnMouseEnter(), UIScriptedMenu::OnShow(), UIScriptedMenu::PreviousCharacter(), and ResetIntroCamera().
GetSelectedUserName()
protected void GetSelectedUserName () inline private
Definition at line 142 of file DayZIntroScene.c.
References GameConstants::DEFAULT_CHARACTER_NAME, g_Game, GetGame(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), and name.
ResetIntroCamera()
void ResetIntroCamera () inline private
Definition at line 127 of file DayZIntroScene.c.
References Managed::GetCharacterObj(), GetIntroCamera(), GetIntroCharacter(), Managed::GetPosition(), and Vector().
Referenced by UIScriptedMenu::Init().
SetInitPostprocesses()
protected void SetInitPostprocesses () inline private
Since this can get created at the same time as DayZGame, non-static postprocesses need to be deffered.
Definition at line 137 of file DayZIntroScene.c.
Referenced by DayZIntroScene().
SnapToGround()
protected vector SnapToGround (vector pos) inline private
Definition at line 170 of file DayZIntroScene.c.
References GetGame(), CGame::SurfaceY(), and Vector().
Referenced by DayZIntroScene().
SwapYZ()
protected vector SwapYZ (vector vec) inline private
Definition at line 159 of file DayZIntroScene.c.
Referenced by DayZIntroScene().
Field Documentation
m_Camera
protected Camera m_Camera private
Definition at line 4 of file DayZIntroScene.c.
Referenced by DayZIntroScene(), DayZIntroScenePC::DayZIntroScenePC(), and GetIntroCamera().
m_CameraTrans
protected vector m_CameraTrans[4] private
Definition at line 5 of file DayZIntroScene.c.
Referenced by DayZIntroScene().
m_Character
protected ref IntroSceneCharacter m_Character private
Definition at line 3 of file DayZIntroScene.c.
Referenced by DayZIntroScenePC::CharacterRotate(), DayZIntroScenePC::CharacterRotationStart(), DayZIntroScene(), GetIntroCharacter(), and DayZIntroScenePC::Update().
m_CharacterPos
protected vector m_CharacterPos private
Definition at line 6 of file DayZIntroScene.c.
Referenced by DayZIntroScene(), and DayZIntroScenePC::DayZIntroScenePC().
m_CharacterRot
protected vector m_CharacterRot private
Definition at line 7 of file DayZIntroScene.c.
Referenced by DayZIntroScenePC::CharacterRotate(), DayZIntroScenePC::CharacterRotationStart(), and DayZIntroScene().
m_OptionsMenu
protected ref OptionsMenu m_OptionsMenu private
Definition at line 11 of file DayZIntroScene.c.
m_Target
protected vector m_Target private
Definition at line 9 of file DayZIntroScene.c.
Referenced by DayZIntroScene().
m_Weather
protected Weather m_Weather private
Definition at line 8 of file DayZIntroScene.c.
Referenced by DayZIntroScene().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/DayZIntroScene.c