DayZ Scripts: AmmoTypesAPI Class Reference
AmmoTypesAPI Class Reference
Private Member Functions
private void AmmoTypesAPI ()
private void ~AmmoTypesAPI ()
Static Private Member Functions
static proto bool Exists (string ammoType)
Check if ammoType exists (registered in cfgAmmoTypes)
static proto bool GetAmmoType (string magazineType, out string ammoType)
Get the default ammoType of a magazine.
static bool MagazineTypeToAmmoType (string magazineType, out string ammoType)
Helper method.
Constructor & Destructor Documentation
AmmoTypesAPI()
private void AmmoTypesAPI () inline private
~AmmoTypesAPI()
private void ~AmmoTypesAPI () inline private
Member Function Documentation
Exists()
static proto bool Exists (string ammoType) static private
Check if ammoType exists (registered in cfgAmmoTypes)
Referenced by MagazineTypeToAmmoType().
GetAmmoType()
static proto bool GetAmmoType (string magazineType, out string ammoType) static private
Get the default ammoType of a magazine.
Referenced by MagazineTypeToAmmoType().
MagazineTypeToAmmoType()
static bool MagazineTypeToAmmoType (string magazineType, out string ammoType) inline static private
Helper method.
References ErrorEx, Exists(), and GetAmmoType().
Referenced by Weapon::FillChamber(), and Weapon::FillInnerMagazine().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Global/AmmoTypes.c