DayZ Scripts: SyncEvents Class Reference
SyncEvents Class Reference
Static Private Member Functions
static void RegisterEvents ()
static void Event_OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx)
static void OnSyncEvent (ESyncEvent event_type, SyncData data, Object target)
static void SendPlayerList ()
static void SendEntityKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot)
static void SendPlayerIgnatedFireplace (Man player, EFireIgniteType ignite_type)
static private void SendSyncEvent (ERPCs rpc_event_id, ESyncEvent sync_event_type, SyncData data=null, bool guaranteed=true, PlayerIdentity player_target=null)
static private void SendSyncEventEx (ERPCs rpc_event_id, ESyncEvent sync_event_type, SyncData data=null, bool guaranteed=true, Man recipient=null)
Member Function Documentation
Event_OnRPC()
static void Event_OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx) inline static private
References GetGame(), OnSyncEvent(), and Serializer::Read().
Referenced by RegisterEvents().
OnSyncEvent()
static void OnSyncEvent (ESyncEvent event_type, SyncData data, Object target) inline static private
References SyncData::m_EntityKill, SyncData::m_ServerPlayerList, SyncData::m_SyncInt, ClientData::SyncEvent_OnEntityKilled, ClientData::SyncEvent_OnPlayerIgnitedFireplace, and ClientData::SyncEvent_OnRecievedPlayerList().
Referenced by Event_OnRPC().
RegisterEvents()
static void RegisterEvents () inline static private
References Event_OnRPC(), GetGame(), and Print().
Referenced by MissionBase::MissionGameplay().
SendEntityKilled()
static void SendEntityKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot) inline static private
References SyncData::m_EntityKill, SyncEntityKillInfo::m_EntityKiller, SyncEntityKillInfo::m_EntitySource, SyncEntityKillInfo::m_EntityVictim, SyncEntityKillInfo::m_IsHeadShot, and SendSyncEventEx().
Referenced by ManBase::OnCommandHandlerTick().
SendPlayerIgnatedFireplace()
static void SendPlayerIgnatedFireplace (Man player, EFireIgniteType ignite_type) inline static private
References SyncData::m_SyncInt, and SendSyncEvent().
Referenced by FireplaceBase::OnIgnitedThis().
SendPlayerList()
static void SendPlayerList () inline static private
References SyncPlayerList::CreatePlayerList(), SyncData::m_ServerPlayerList, and SendSyncEvent().
Referenced by MissionBase::OnEvent(), and MissionBase::PlayerDisconnected().
SendSyncEvent()
static private void SendSyncEvent (ERPCs rpc_event_id, ESyncEvent sync_event_type, SyncData data = null, bool guaranteed = true, PlayerIdentity player_target = null) inline static private
References GetGame(), and CGame::RPCSingleParam().
Referenced by SendPlayerIgnatedFireplace(), SendPlayerList(), and SendSyncEventEx().
SendSyncEventEx()
static private void SendSyncEventEx (ERPCs rpc_event_id, ESyncEvent sync_event_type, SyncData data = null, bool guaranteed = true, Man recipient = null) inline static private
References SendSyncEvent().
Referenced by SendEntityKilled().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/SyncEvents.c