DayZ Scripts: Param Class Reference
Param Class Reference
Tools
Base Param Class with no parameters. Used as general purpose parameter overloaded with Param1 to Param4 templates.
Private Member Functions
bool Serialize (Serializer ctx)
bool Deserializer (Serializer ctx)
void Param1 (T1 p1)
override bool Serialize (Serializer ctx)
override bool Deserializer (Serializer ctx)
void Param2 (T1 p1, T2 p2)
override bool Serialize (Serializer ctx)
override bool Deserializer (Serializer ctx)
void Param3 (T1 p1, T2 p2, T3 p3)
override bool Serialize (Serializer ctx)
override bool Deserializer (Serializer ctx)
void Param4 (T1 p1, T2 p2, T3 p3, T4 p4)
override bool Serialize (Serializer ctx)
override bool Deserializer (Serializer ctx)
void Param5 (T1 p1, T2 p2, T3 p3, T4 p4, T5 p5)
override bool Serialize (Serializer ctx)
override bool Deserializer (Serializer ctx)
void Param6 (T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6)
override bool Serialize (Serializer ctx)
override bool Deserializer (Serializer ctx)
Private Attributes
T1 param1
T2 param2
T3 param3
T4 param4
T5 param5
T6 param6
Detailed Description
Base Param Class with no parameters. Used as general purpose parameter overloaded with Param1 to Param4 templates.
Param Class Template with six parameters.
Param Class Template with five parameters.
Param Class Template with four parameters.
usage:
Param Class Template with three parameters.
usage:
Param Class Template with two parameters.
usage:
Param Class Template with one parameter.
usage:
Param paramA = new Param1<int>(55);
Param paramB = new Param1<string>("Hello");
Param param = new Param2<float, string>(3.14, "Pi");
Param param = new Param3<float, string, bool>(2.89, "Lala", true);
Param param = new Param4<int, bool, float, string>(100, false, 79.9, "Test");
Member Function Documentation
Deserializer() [1/7]
bool Deserializer (Serializer ctx) inline private
Deserializer() [2/7]
override bool Deserializer (Serializer ctx) inline private
References Serializer::Read().
Deserializer() [3/7]
override bool Deserializer (Serializer ctx) inline private
References Serializer::Read().
Deserializer() [4/7]
override bool Deserializer (Serializer ctx) inline private
References Serializer::Read().
Deserializer() [5/7]
override bool Deserializer (Serializer ctx) inline private
References Serializer::Read().
Deserializer() [6/7]
override bool Deserializer (Serializer ctx) inline private
References Serializer::Read().
Deserializer() [7/7]
override bool Deserializer (Serializer ctx) inline private
References Serializer::Read().
Param1()
void Param1 (T1 p1) inline private
Param2()
void Param2 (T1 p1, T2 p2) inline private
Param3()
void Param3 (T1 p1, T2 p2, T3 p3) inline private
Param4()
void Param4 (T1 p1, T2 p2, T3 p3, T4 p4) inline private
Param5()
void Param5 (T1 p1, T2 p2, T3 p3, T4 p4, T5 p5) inline private
Param6()
void Param6 (T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6) inline private
Serialize() [1/7]
bool Serialize (Serializer ctx) inline private
Serialize() [2/7]
override bool Serialize (Serializer ctx) inline private
References Serializer::Write().
Serialize() [3/7]
override bool Serialize (Serializer ctx) inline private
References Serializer::Write().
Serialize() [4/7]
override bool Serialize (Serializer ctx) inline private
References Serializer::Write().
Serialize() [5/7]
override bool Serialize (Serializer ctx) inline private
References Serializer::Write().
Serialize() [6/7]
override bool Serialize (Serializer ctx) inline private
References Serializer::Write().
Serialize() [7/7]
override bool Serialize (Serializer ctx) inline private
References Serializer::Write().
Field Documentation
param1
T1 param1 private
Referenced by PPEDOF::SetFinalParameterValue(), PPEExposureNative::SetFinalParameterValue(), PPEEyeAccomodationNative::SetFinalParameterValue(), PPELightIntensityParamsNative::SetFinalParameterValue(), and PPEClassBase::SetFinalParameterValue().
param2
T2 param2 private
param3
T3 param3 private
param4
T4 param4 private
param5
T5 param5 private
param6
T6 param6 private
The documentation for this class was generated from the following file:
P:/scripts/1_core/param.c