DayZ Scripts: FireworksLauncher Class Reference
FireworksLauncher Class Reference
Private Member Functions
void FireworksLauncher ()
void ~FireworksLauncher ()
override protected bool UsesGlobalDeploy ()
override bool IsDeployable ()
override float GetDeployTime ()
how long it takes to deploy this item in seconds
protected void SetupColorSequences ()
string GetColorSequence ()
override protected void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override protected float GetMaxAllowedWetness ()
override protected float GetEventDelay ()
protected string GetFuseSoundSet ()
protected int GetMaxShots ()
protected float GetFuseDelay ()
protected string GetAmmoType ()
protected int GetDamageType ()
override protected void OnStateChangedServer (EFireworksState currentState)
override protected void OnStateChangedClient (EFireworksState currentState)
override void OnIgnitedThis (EntityAI fire_source)
Executed on Server when some item ignited this one.
override protected bool CanPutInCargo (EntityAI parent)
override protected bool CanPutIntoHands (EntityAI parent)
protected void OnFuseIgnitedServer ()
protected void OnFuseIgnitedClient ()
protected void OnFiringStartServer ()
protected void OnFiringStartClient ()
protected void OnFiringStop ()
protected void RestartEventTimer ()
Starts event timer.
override protected bool IsIgnited ()
override protected bool CanIgniteItem (EntityAI ignite_target=NULL)
override protected void OnEventServer (int type)
Called periodically but only after the entity gets ignited.
protected void OnIndexChangedClient ()
protected FireworksLauncherClientEventBase SpawnEvent ()
override protected void OnVariablesSynchronized ()
override protected void OnStoreSave (ParamsWriteContext ctx)
override protected bool OnStoreLoad (ParamsReadContext ctx, int version)
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
Private Attributes
int m_Index
int m_IndexPrev
int m_ColorSequenceIndex
ref Timer m_TimerFuse
ref array< ref FireworksLauncherClientEventBase > m_Events
EffectSound m_FuseSoundStart
EffectSound m_FuseSound
ParticleSource m_ParticleFuse
ParticleSource m_ParticleAfterBurnEnd
ref array< string > m_ColorSequence
Constructor & Destructor Documentation
FireworksLauncher()
void FireworksLauncher () inline private
References EnumTools::GetLastEnumValue(), GetMaxShots(), m_ColorSequence, m_ColorSequenceIndex, m_RandomSeed, Math::RandomInt(), Math::RandomIntInclusive(), and SetupColorSequences().
~FireworksLauncher()
void ~FireworksLauncher () inline private
References SEffectManager::DestroyEffect(), m_FuseSound, and m_FuseSoundStart.
Member Function Documentation
CanIgniteItem()
override protected bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
CanPutInCargo()
override protected bool CanPutInCargo (EntityAI parent) inline private
References GetState().
CanPutIntoHands()
override protected bool CanPutIntoHands (EntityAI parent) inline private
References GetState().
GetAmmoType()
protected string GetAmmoType () inline private
Referenced by OnEventServer().
GetColorSequence()
string GetColorSequence () inline private
References ErrorEx, m_ColorSequence, and m_ColorSequenceIndex.
Referenced by FireworksLauncherClientEvent::FireworksLauncherClientEvent().
GetDamageType()
protected int GetDamageType () inline private
Referenced by OnEventServer().
GetDeploySoundset()
override string GetDeploySoundset () inline private
GetDeployTime()
override float GetDeployTime () inline private
how long it takes to deploy this item in seconds
GetEventDelay()
override protected float GetEventDelay () inline private
References Math::RandomFloatInclusive().
Referenced by RestartEventTimer().
GetFuseDelay()
protected float GetFuseDelay () inline private
Referenced by OnFuseIgnitedServer().
GetFuseSoundSet()
protected string GetFuseSoundSet () inline private
Referenced by OnFuseIgnitedClient().
GetLoopDeploySoundset()
override string GetLoopDeploySoundset () inline private
GetMaxAllowedWetness()
override protected float GetMaxAllowedWetness () inline private
References GameConstants::STATE_WET.
GetMaxShots()
protected int GetMaxShots () inline private
Referenced by FireworksLauncher(), and OnEventServer().
IsDeployable()
override bool IsDeployable () inline private
IsIgnited()
override protected bool IsIgnited () inline private
References GetState().
OnEventServer()
override protected void OnEventServer (int type) inline private
Called periodically but only after the entity gets ignited.
References GetAmmoType(), GetDamageType(), GetMaxShots(), GetPosition, m_Index, m_TimerEvent, RestartEventTimer(), and SetState().
Referenced by OnFiringStartServer().
OnFiringStartClient()
protected void OnFiringStartClient () inline private
References m_FuseSound, m_ParticleFuse, EffectSound::Stop(), and ParticleSource::StopParticle().
Referenced by OnStateChangedClient().
OnFiringStartServer()
protected void OnFiringStartServer () inline private
References OnEventServer().
Referenced by OnStateChangedServer().
OnFiringStop()
protected void OnFiringStop () inline private
OnFuseIgnitedClient()
protected void OnFuseIgnitedClient () inline private
References ParticleList::FIREWORKS_FUSE, GetFuseSoundSet(), GetPosition, m_FuseSound, m_FuseSoundStart, m_ParticleFuse, ParticleManager(), ParticleSource::SetOwner(), and vector::VectorToAngles().
Referenced by OnStateChangedClient().
OnFuseIgnitedServer()
protected void OnFuseIgnitedServer () inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetFuseDelay(), GetGame(), and SetState().
Referenced by OnStateChangedServer().
OnIgnitedThis()
override void OnIgnitedThis (EntityAI fire_source) inline private
Executed on Server when some item ignited this one.
References m_Events, m_Index, m_TimerEvent, and Timer::Stop().
OnIndexChangedClient()
protected void OnIndexChangedClient () inline private
References m_Events, m_Index, m_State, and SpawnEvent().
Referenced by OnVariablesSynchronized().
OnPlacementComplete()
override protected void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
References GetGame(), GetState(), and SetState().
OnStateChangedClient()
override protected void OnStateChangedClient (EFireworksState currentState) inline private
References OnFiringStartClient(), and OnFuseIgnitedClient().
OnStateChangedServer()
override protected void OnStateChangedServer (EFireworksState currentState) inline private
References OnFiringStartServer(), and OnFuseIgnitedServer().
OnStoreLoad()
override protected bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References m_Index, m_State, Serializer::Read(), and SetState().
OnStoreSave()
override protected void OnStoreSave (ParamsWriteContext ctx) inline private
References m_Index, m_State, and Serializer::Write().
OnVariablesSynchronized()
override protected void OnVariablesSynchronized () inline private
References m_Index, m_IndexPrev, m_RandomSeed, OnIndexChangedClient(), and Math::Randomize().
RestartEventTimer()
protected void RestartEventTimer () inline private
Starts event timer.
References GetEventDelay(), and m_TimerEvent.
Referenced by OnEventServer().
SetupColorSequences()
protected void SetupColorSequences () inline private
References m_ColorSequence.
Referenced by FireworksLauncher().
SpawnEvent()
protected FireworksLauncherClientEventBase SpawnEvent () inline private
References m_Index.
Referenced by OnIndexChangedClient().
UsesGlobalDeploy()
override protected bool UsesGlobalDeploy () inline private
Field Documentation
m_ColorSequence
ref array<string> m_ColorSequence private
Referenced by FireworksLauncher(), GetColorSequence(), SetupColorSequences(), and Anniversary_FireworksLauncher::SetupColorSequences().
m_ColorSequenceIndex
int m_ColorSequenceIndex private
Referenced by FireworksLauncher(), and GetColorSequence().
m_Events
ref array<ref FireworksLauncherClientEventBase> m_Events private
Referenced by OnIgnitedThis(), and OnIndexChangedClient().
m_FuseSound
EffectSound m_FuseSound private
Referenced by OnFiringStartClient(), OnFuseIgnitedClient(), and ~FireworksLauncher().
m_FuseSoundStart
EffectSound m_FuseSoundStart private
Referenced by OnFuseIgnitedClient(), and ~FireworksLauncher().
m_Index
int m_Index private
Referenced by OnEventServer(), OnIgnitedThis(), OnIndexChangedClient(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), SpawnEvent(), and Anniversary_FireworksLauncher::SpawnEvent().
m_IndexPrev
int m_IndexPrev private
Referenced by OnVariablesSynchronized().
m_ParticleAfterBurnEnd
ParticleSource m_ParticleAfterBurnEnd private
m_ParticleFuse
ParticleSource m_ParticleFuse private
Referenced by OnFiringStartClient(), and OnFuseIgnitedClient().
m_TimerFuse
ref Timer m_TimerFuse private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Gear/Tools/FireworksLauncher.c