DayZ Scripts: Heatpack Class Reference
Heatpack Class Reference
Private Member Functions
override bool CanHaveTemperature ()
override void OnWorkStart ()
override void OnWork (float consumed_energy)
override void OnWorkStop ()
override void SetActions ()
Member Function Documentation
CanHaveTemperature()
override bool CanHaveTemperature () inline private
OnWork()
override void OnWork (float consumed_energy) inline private
References GetGame(), and SetTemperature().
OnWorkStart()
override void OnWorkStart () inline private
References GetGame(), and SetTemperature().
OnWorkStop()
override void OnWorkStop () inline private
References GetGame().
SetActions()
override void SetActions () inline private
References AddAction().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Heatpack.c