DayZ Scripts: FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase > Class Reference
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase > Class Reference
Private Member Functions
void FSMBase ()
fsm transition table
FSMStateBase GetCurrentState ()
returns currently active state
void SetInitialState (FSMStateBase initial_state)
sets the initial_state for starting the machine
void Start (FSMEventBase initial_event=NULL)
starts the state machine by entering the initial_state (using intial_event as argument to initial state's onEntry)
bool IsRunning ()
returns true if machine is in running state
void Terminate (FSMEventBase terminal_event=NULL)
terminates the state machine
void Update (float dt)
if machine running, call OnUpdate() on current state
void AddTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t)
adds transition into transition table
ProcessEventResult ProcessEvent (FSMEventBase e)
instructs the state machine to process the event e
protected ProcessEventResult ProcessLocalTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e)
instructs the state machine to process the event locally - no hierarchy is crossed
Private Attributes
protected ref FSMStateBase m_state
protected ref FSMStateBase m_initialState
current fsm state
protected ref FSMEventBase m_initialEvent
configurable initial state of the machine
protected ref array< ref FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > > m_transitions
configurable initial event to start the machine (null by default)
Detailed Description
Definition at line 46 of file FSMBase.c.
Constructor & Destructor Documentation
FSMBase()
void FSMBase () inline private
fsm transition table
Definition at line 53 of file FSMBase.c.
Member Function Documentation
AddTransition()
AddTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t) inline private
adds transition into transition table
Definition at line 116 of file FSMBase.c.
GetCurrentState()
GetCurrentState () inline private
returns currently active state
Returns
current state the FSM is in (or NULL)
Definition at line 62 of file FSMBase.c.
IsRunning()
IsRunning () inline private
returns true if machine is in running state
Definition at line 90 of file FSMBase.c.
ProcessEvent()
ProcessEvent (FSMEventBase e) inline private
instructs the state machine to process the event e
Parameters
[in] e event that will be used to find suitable transition from current state
Returns
FSM_OK if transition found and allowed by guard (if any)
Definition at line 126 of file FSMBase.c.
ProcessLocalTransition()
ProcessLocalTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e) inline private
instructs the state machine to process the event locally - no hierarchy is crossed
Parameters
[in] t the transition in m_transitions
[in] e event that will be used to process transition from current state
Returns
FSM_OK or FSM_TERMINATED
Definition at line 153 of file FSMBase.c.
References fsmbDebugPrint().
SetInitialState()
SetInitialState (FSMStateBase initial_state) inline private
sets the initial_state for starting the machine
Definition at line 70 of file FSMBase.c.
Start()
Start (FSMEventBase initial_event = NULL) inline private
starts the state machine by entering the initial_state (using intial_event as argument to initial state's onEntry)
Parameters
[in] e optional event for starting the machind
Definition at line 79 of file FSMBase.c.
References fsmbDebugPrint(), ToString(), and string::ToString().
Terminate()
Terminate (FSMEventBase terminal_event = NULL) inline private
terminates the state machine
Definition at line 95 of file FSMBase.c.
References IsRunning().
Update()
Update (float dt) inline private
if machine running, call OnUpdate() on current state
Definition at line 107 of file FSMBase.c.
References IsRunning().
Field Documentation
m_initialEvent
protected ref FSMEventBase m_initialEvent private
configurable initial state of the machine
Definition at line 50 of file FSMBase.c.
m_initialState
protected ref FSMStateBase m_initialState private
current fsm state
Definition at line 49 of file FSMBase.c.
m_state
protected ref FSMStateBase m_state private
Definition at line 48 of file FSMBase.c.
m_transitions
protected ref array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> > m_transitions private
configurable initial event to start the machine (null by default)
Definition at line 51 of file FSMBase.c.
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/FSMBase.c