DayZ Scripts: Cauldron Class Reference
Cauldron Class Reference
Private Member Functions
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool IsOpen ()
override bool CanHaveWetness ()
override float GetQuantityNormalizedScripted ()
override void SetActions ()
Member Function Documentation
CanHaveWetness()
override bool CanHaveWetness () inline private
CanLoadItemIntoCargo()
override bool CanLoadItemIntoCargo (EntityAI item) inline private
References IsCargoException4x3().
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
References IsCargoException4x3().
CanReceiveItemIntoCargo()
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
References IsCargoException4x3().
GetEmptyingEndSoundsetHard()
override string GetEmptyingEndSoundsetHard () inline private
GetEmptyingEndSoundsetSoft()
override string GetEmptyingEndSoundsetSoft () inline private
GetEmptyingEndSoundsetWater()
override string GetEmptyingEndSoundsetWater () inline private
GetEmptyingLoopSoundsetHard()
override string GetEmptyingLoopSoundsetHard () inline private
GetEmptyingLoopSoundsetSoft()
override string GetEmptyingLoopSoundsetSoft () inline private
GetEmptyingLoopSoundsetWater()
override string GetEmptyingLoopSoundsetWater () inline private
GetPouringSoundset()
override string GetPouringSoundset () inline private
GetQuantityNormalizedScripted()
override float GetQuantityNormalizedScripted () inline private
IsContainer()
override bool IsContainer () inline private
IsOpen()
override bool IsOpen () inline private
SetActions()
override void SetActions () inline private
References AddAction(), and RemoveAction().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/Cauldron.c