DayZ Scripts: InventoryInputUserData Class Reference
InventoryInputUserData Class Reference
Static Private Member Functions
static void SerializeDestroy (ParamsWriteContext ctx, notnull InventoryLocation src)
static void SendInputUserDataDestroy (notnull InventoryLocation src)
static void SerializeMove (ParamsWriteContext ctx, int type, notnull InventoryLocation src, notnull InventoryLocation dst)
move
static void SendInputUserDataMove (int type, notnull InventoryLocation src, notnull InventoryLocation dst)
static void SendServerMove (Man player, int type, notnull InventoryLocation src, notnull InventoryLocation dst)
static void SerializeSwap (ParamsWriteContext ctx, notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap)
swap
static void SendInputUserDataSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap=false)
static void SendServerSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap=false)
static void SerializeHandEvent (ParamsWriteContext ctx, HandEventBase e)
hand
static void SendInputUserDataHandEvent (HandEventBase e)
static void SendServerHandEventViaInventoryCommand (notnull Man player, HandEventBase e)
Detailed Description
Definition at line 2 of file InventoryInputUserData.c.
Member Function Documentation
SendInputUserDataDestroy()
static void SendInputUserDataDestroy (notnull InventoryLocation src) inline static private
Definition at line 114 of file InventoryInputUserData.c.
References InventoryLocation::DumpToStringNullSafe(), GetGame(), ScriptInputUserData::Send(), SerializeDestroy(), and syncDebugPrint().
SendInputUserDataHandEvent()
static void SendInputUserDataHandEvent (HandEventBase e) inline static private
Definition at line 79 of file InventoryInputUserData.c.
References HandEventBase::DumpToString(), GetGame(), GetTime(), ScriptInputUserData::Send(), SerializeHandEvent(), and syncDebugPrint().
Referenced by HandleHandEvent().
SendInputUserDataMove()
static void SendInputUserDataMove (int type, notnull InventoryLocation src, notnull InventoryLocation dst) inline static private
Definition at line 13 of file InventoryInputUserData.c.
References InventoryLocation::DumpToStringNullSafe(), GetGame(), GetTime(), ScriptInputUserData::Send(), SerializeMove(), and syncDebugPrint().
Referenced by HandleTakeToDst().
SendInputUserDataSwap()
static void SendInputUserDataSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap = false) inline static private
Definition at line 48 of file InventoryInputUserData.c.
References InventoryLocation::DumpToStringNullSafe(), GetGame(), GetTime(), ScriptInputUserData::Send(), SerializeSwap(), and syncDebugPrint().
Referenced by HandleForceSwapEntities(), and HandleSwapEntities().
SendServerHandEventViaInventoryCommand()
static void SendServerHandEventViaInventoryCommand (notnull Man player, HandEventBase e) inline static private
Definition at line 90 of file InventoryInputUserData.c.
References HandEventBase::DumpToString(), Error(), GetGame(), HandEventBase::IsServerSideOnly(), SerializeHandEvent(), GameInventory::ServerHandEvent(), and syncDebugPrint().
Referenced by HandleHandEvent().
SendServerMove()
static void SendServerMove (Man player, int type, notnull InventoryLocation src, notnull InventoryLocation dst) inline static private
Definition at line 24 of file InventoryInputUserData.c.
References InventoryLocation::DumpToStringNullSafe(), GetGame(), SerializeMove(), GameInventory::ServerLocationSyncMoveEntity(), and syncDebugPrint().
Referenced by GameInventory::TakeToDst().
SendServerSwap()
static void SendServerSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap = false) inline static private
Definition at line 59 of file InventoryInputUserData.c.
References InventoryLocation::DumpToStringNullSafe(), GetGame(), SerializeSwap(), GameInventory::ServerLocationSwap(), and syncDebugPrint().
SerializeDestroy()
static void SerializeDestroy (ParamsWriteContext ctx, notnull InventoryLocation src) inline static private
Definition at line 107 of file InventoryInputUserData.c.
References INPUT_UDT_INVENTORY, and Serializer::Write().
Referenced by SendInputUserDataDestroy().
SerializeHandEvent()
static void SerializeHandEvent (ParamsWriteContext ctx, HandEventBase e) inline static private
hand
Definition at line 72 of file InventoryInputUserData.c.
References INPUT_UDT_INVENTORY, Serializer::Write(), and HandEventBase::WriteToContext().
Referenced by HandEvent(), OnUpdate(), SendInputUserDataHandEvent(), SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), and ValidateHandEvent().
SerializeMove()
static void SerializeMove (ParamsWriteContext ctx, int type, notnull InventoryLocation src, notnull InventoryLocation dst) inline static private
move
Definition at line 5 of file InventoryInputUserData.c.
References INPUT_UDT_INVENTORY, and Serializer::Write().
Referenced by OnUpdate(), SendInputUserDataMove(), SendServerMove(), and TakeToDst().
SerializeSwap()
static void SerializeSwap (ParamsWriteContext ctx, notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap) inline static private
swap
Definition at line 37 of file InventoryInputUserData.c.
References INPUT_UDT_INVENTORY, and Serializer::Write().
Referenced by SendInputUserDataSwap(), SendServerSwap(), and ValidateSwap().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/Inventory/InventoryInputUserData.c