DayZ Scripts: DayZPlayerTypeVoiceSoundLookupTable Class Reference
DayZPlayerTypeVoiceSoundLookupTable Class Reference
Private Member Functions
void DayZPlayerTypeVoiceSoundLookupTableImpl ()
override SoundObjectBuilder GetSoundBuilder (int eventId, int parameterHash)
override NoiseParams GetNoiseParams (int eventId)
Static Private Member Functions
static DayZPlayerTypeVoiceSoundLookupTableImpl GetInstance ()
Private Attributes
private autoptr map< int, ref PlayerVoiceLookupTable > m_pSoundTableInstances
private autoptr map< int, PlayerVoiceLookupTable > m_pSoundTables
Static Private Attributes
static private ref DayZPlayerTypeVoiceSoundLookupTableImpl m_instance
Member Function Documentation
DayZPlayerTypeVoiceSoundLookupTableImpl()
void DayZPlayerTypeVoiceSoundLookupTableImpl () inline private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), CGame::ConfigGetText(), GetGame(), string::Hash(), m_pSoundTableInstances, m_pSoundTables, and PlayerVoiceLookupTable().
Referenced by GetInstance().
GetInstance()
static DayZPlayerTypeVoiceSoundLookupTableImpl GetInstance () inline static private
References DayZPlayerTypeVoiceSoundLookupTableImpl(), m_instance, and m_instance.
Referenced by DayZPlayerTypeRegisterSounds().
GetNoiseParams()
override NoiseParams GetNoiseParams (int eventId) inline private
References m_pSoundTables, and PlayerVoiceLookupTable().
GetSoundBuilder()
override SoundObjectBuilder GetSoundBuilder (int eventId, int parameterHash) inline private
References m_pSoundTables, and PlayerVoiceLookupTable().
Referenced by DayZPlayer::ProcessVoiceEvent().
Field Documentation
m_instance
private ref DayZPlayerTypeVoiceSoundLookupTableImpl m_instance static private
Referenced by GetInstance().
m_pSoundTableInstances
private autoptr map<int, ref PlayerVoiceLookupTable> m_pSoundTableInstances private
m_pSoundTables
private autoptr map<int, PlayerVoiceLookupTable> m_pSoundTables private
The documentation for this class was generated from the following file:
4_World/Entities/ManBase/DayZPlayer/DayZPlayerCfgSounds.c