DayZ Scripts: P:/scripts/4_World/Systems/UniversalTemperatureSource/UniversalTemperatureSourceLambdaBaseImpl.c File Reference
UniversalTemperatureSourceLambdaBaseImpl.c File Reference
Data Structures
class UniversalTemperatureSourceLambdaBaseImpl
Functions
UniversalTemperatureSourceLambdaBaseImpl UniversalTemperatureSourceLambdaBase UniversalTemperatureSourceLambdaEngine ()
override void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings, vector position, out notnull array< Object > nearestObjects)
override void WarmAndCoolItemsInVicinity (UniversalTemperatureSourceSettings pSettings, vector position, out notnull array< Object > nearestObjects)
protected void UpdateVicinityTemperatureRecursive (EntityAI ent, TemperatureData dta, float heatPermeabilityCoef=1.0)
override void Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues)
override void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings)
DEPRECATED.
Function Documentation
DryItemsInVicinity() [1/2]
override void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings)
DEPRECATED.
DryItemsInVicinity() [2/2]
override void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings, vector position, out notnull array< Object > nearestObjects)
heat transfer to items (not in player possession)
Execute()
override void Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues)
UniversalTemperatureSourceLambdaEngine()
UniversalTemperatureSourceLambdaBaseImpl UniversalTemperatureSourceLambdaBase UniversalTemperatureSourceLambdaEngine ()
Referenced by ItemBase::EEInit(), Boat_01_ColorBase::EEInit(), CarScript::EEInit(), and OnDebugSpawn().
UpdateVicinityTemperatureRecursive()
protected void UpdateVicinityTemperatureRecursive (EntityAI ent, TemperatureData dta, float heatPermeabilityCoef = 1.0)
WarmAndCoolItemsInVicinity()
override void WarmAndCoolItemsInVicinity (UniversalTemperatureSourceSettings pSettings, vector position, out notnull array< Object > nearestObjects)
dist factor minimum should be at 0