DayZ Scripts: ActionDigGardenPlot Class Reference
ActionDigGardenPlot Class Reference
Private Member Functions
void ActionDigGardenPlot ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void SetupAnimation (ItemBase item)
void CheckSurfaceBelowGardenPlot (PlayerBase player, GardenPlot item_GP, Hologram hologram)
override void DropDuringPlacing (PlayerBase player)
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Private Attributes
GardenPlot m_GardenPlot
Constructor & Destructor Documentation
ActionDigGardenPlot()
void ActionDigGardenPlot () inline private
References m_CommandUID, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Class::CastTo(), CheckSurfaceBelowGardenPlot(), GetGame(), Hologram::GetProjectionEntity(), and Hologram::IsColliding().
CheckSurfaceBelowGardenPlot()
void CheckSurfaceBelowGardenPlot (PlayerBase player, GardenPlot item_GP, Hologram hologram) inline private
References Hologram::GetLeftCloseProjectionVector(), Hologram::GetLeftFarProjectionVector(), Hologram::GetRightCloseProjectionVector(), Hologram::GetRightFarProjectionVector(), and Hologram::SetIsCollidingGPlot().
Referenced by ActionCondition().
DropDuringPlacing()
override void DropDuringPlacing (PlayerBase player) inline private
OnFinishProgressClient()
override void OnFinishProgressClient (ActionData action_data) inline private
References PlaceObjectActionData::m_AlreadyPlaced.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References CGame::ClearJuncture(), GetGame(), PlaceObjectActionData::m_AlreadyPlaced, and m_GardenPlot.
SetupAnimation()
override void SetupAnimation (ItemBase item) inline private
References m_CommandUID.
Field Documentation
m_GardenPlot
GardenPlot m_GardenPlot private
Referenced by OnFinishProgressServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionDigGardenPlot.c