DayZ Scripts: ActionTargetsCursor Class Reference
ActionTargetsCursor Class Reference
Private Member Functions
void ActionTargetsCursor ()
void ~ActionTargetsCursor ()
void SetHealthVisibility (bool state)
void SetQuantityVisibility (bool state)
void SetInteractXboxIcon (string imageset_name, string image_name)
DEPRECATED.
void SetContinuousInteractXboxIcon (string imageset_name, string image_name)
void SetSingleXboxIcon (string imageset_name, string image_name)
void SetContinuousXboxIcon (string imageset_name, string image_name)
protected void SetXboxIcon (string name, string imageset_name, string image_name)
protected void SetControllerIcon (string pWidgetName, string pInputName)
protected void OnWidgetScriptInit (Widget w)
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
private void UpdateControllerInputIcons ()
Loads icons from the latest keybinds.
private void UpdatePCIconsVisibility ()
Contains logic for icon set switching (Gamepad/M&K)
protected void PrepareCursorContent ()
protected void BuildFixedCursor ()
protected void BuildFloatingCursor (bool forceRebuild)
override bool OnUpdate (Widget w)
protected void HideWidget ()
void Update ()
protected void ShowXboxHidePCIcons (string widget, bool show_xbox_icon)
protected vector TransformToScreenPos (vector pWorldPos)
transform world pos to screen pos (related to parent widget size)
protected void GetOnScreenPosition (out float x, out float y)
protected bool IsComponentInSelection (array< Selection > selection, string compName)
protected void GetPlayer ()
protected void GetActionManager ()
protected void GetActions ()
get actions from Action Manager
protected void GetTarget ()
protected string GetActionDesc (ActionBase action)
protected string GetItemDesc (ActionBase action)
protected int GetItemHealth ()
protected void GetItemQuantity (out int q_type, out float q_cur, out int q_min, out int q_max)
protected void GetItemCargoCount (out int cargoCount)
returns number of items in cargo for targeted entity
protected void SetItemDesc (string descText, int cargoCount, string itemWidget, string descWidget)
protected void SetItemHealth (int health, string itemWidget, string healthWidget, bool enabled)
protected void SetItemQuantity (int type, float current, int min, int max, string itemWidget, string quantityPBWidget, string quantityTextWidget, bool enabled)
protected void SetActionWidget (ActionBase action, string descText, string actionWidget, string descWidget)
protected void SetMultipleInteractAction (string multiActionsWidget, string multiActionsWidget_NotSelect)
shows arrows near the interact action if there are more than one available
protected void SetMultipleContinuousInteractAction (string multiActionsWidget, string multiActionsWidget_NotSelect)
protected void SetMultipleItemAction (string multiActionsWidget, string multiActionsWidget_NotSelect)
protected void SetMultipleContinuousItemAction (string multiActionsWidget, string multiActionsWidget_NotSelect)
protected void SetInteractActionIcon (string actionWidget, string actionIconFrameWidget, string actionIconWidget, string actionIconTextWidget)
protected void CheckRefresherFlagVisibility (Object object)
protected int AttachmentsWithInventoryOrCargoCount (notnull GameInventory inventory)
protected IngameHud GetHud ()
Private Attributes
private const ref array< typename > VISION_OBSTRUCTION_PPEFFECTS_TYPES
protected PlayerBase m_Player
protected ActionTarget m_Target
protected ref ATCCachedObject m_CachedObject
protected Object m_DisplayInteractTarget
protected ActionBase m_Interact
protected ActionBase m_ContinuousInteract
protected ActionBase m_Single
protected ActionBase m_Continuous
protected ActionManagerClient m_AM
protected IngameHud m_Hud
protected UAIDWrapper m_UseActionWrapper
protected int m_InteractActionsNum
protected int m_ContinuousInteractActionsNum
protected int m_ItemActionsNum
protected int m_ContinuousItemActionsNum
protected m_SelectedActionCategory
protected bool m_HealthEnabled
protected bool m_QuantityEnabled
protected bool m_FixedOnPosition
protected bool m_Hidden
protected Widget m_Root
protected Widget m_Container
protected Widget m_ItemLeft
protected float m_MaxWidthChild
widget width
protected float m_RootWidth
protected float m_RootHeight
Constructor & Destructor Documentation
ActionTargetsCursor()
void ActionTargetsCursor () inline private
References GetGame(), GetHud(), UAInputAPI::GetInputByID(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), UAInput::GetPersistentWrapper(), GetUApi(), ScriptInvoker::Insert(), m_AM, m_CachedObject, m_Continuous, m_ContinuousInteract, m_DisplayInteractTarget, m_HealthEnabled, m_Hidden, m_Hud, m_Interact, m_QuantityEnabled, m_Single, m_UseActionWrapper, OnInputDeviceChanged(), and OnInputPresetChanged().
~ActionTargetsCursor()
void ~ActionTargetsCursor () inline private
Member Function Documentation
AttachmentsWithInventoryOrCargoCount()
protected int AttachmentsWithInventoryOrCargoCount (notnull GameInventory inventory) inline private
References CargoBase::GetItemCount().
BuildFixedCursor()
protected void BuildFixedCursor () inline private
References GetScreenSize(), m_Root, PrepareCursorContent(), x, and y.
Referenced by Update().
BuildFloatingCursor()
protected void BuildFloatingCursor (bool forceRebuild) inline private
Get OnScreenPos when forced or targeted component differs
in case of cached item, all above is reused except the position
References Math::Ceil(), ATCCachedObject::GetCursorCompIdx(), ATCCachedObject::GetCursorWorldPos(), GetOnScreenPosition(), m_CachedObject, m_Root, m_Target, PrepareCursorContent(), and TransformToScreenPos().
Referenced by Update().
CheckRefresherFlagVisibility()
protected void CheckRefresherFlagVisibility (Object object) inline private
References Class::CastTo(), m_Player, and m_Root.
GetActionDesc()
protected string GetActionDesc (ActionBase action) inline private
Referenced by PrepareCursorContent().
GetActionManager()
protected void GetActionManager () inline private
References Class::CastTo(), m_AM, and m_Player.
Referenced by Update().
GetActions()
protected void GetActions () inline private
get actions from Action Manager
Referenced by Update().
GetHud()
protected IngameHud GetHud () inline private
References GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
Referenced by ActionTargetsCursor().
GetItemCargoCount()
protected void GetItemCargoCount (out int cargoCount) inline private
returns number of items in cargo for targeted entity
default cargo count
Referenced by PrepareCursorContent().
GetItemDesc()
protected string GetItemDesc (ActionBase action) inline private
References m_DisplayInteractTarget, m_Target, LOD::NAME_FIRE, LOD::NAME_VIEW, and EntityAI::ShowZonesHealth().
Referenced by PrepareCursorContent().
GetItemHealth()
protected int GetItemHealth () inline private
References m_DisplayInteractTarget, m_Interact, m_Target, LOD::NAME_FIRE, and LOD::NAME_VIEW.
Referenced by PrepareCursorContent().
GetItemQuantity()
protected void GetItemQuantity (out int q_type, out float q_cur, out int q_min, out int q_max) inline private
References Class::CastTo(), QuantityConversions::GetItemQuantity(), QuantityConversions::HasItemQuantity(), m_DisplayInteractTarget, m_Interact, and m_Target.
Referenced by PrepareCursorContent().
GetOnScreenPosition()
protected void GetOnScreenPosition (out float x, out float y) inline private
kept for backward compatibility
Get memory LOD from p3d
save selection from memory lod
cache current object and the widget world pos
doors/handles
single vertex in selection
multiple vertices in selection
cache current object and the widget world pos
do not store component index for doors/handles
ladders handling
cache current object and the widget world pos
do not store component index for ladders
References Math::AbsFloat(), string::Contains(), vector::DistanceSq(), GetName(), LOD::GetSelections(), GetType(), HasFixedActionTargetCursorPosition(), IsComponentInSelection(), m_CachedObject, m_FixedOnPosition, m_Player, m_Target, LOD::NAME_MEMORY, ATCCachedObject::Store(), TransformToScreenPos(), x, y, and vector::Zero.
Referenced by BuildFloatingCursor().
GetPlayer()
protected void GetPlayer () inline private
References Class::CastTo(), GetGame(), GetPlayer(), and m_Player.
Referenced by GetPlayer(), and Update().
GetTarget()
protected void GetTarget () inline private
References ActionManagerClient::FindActionTarget(), InventoryLocation::GetType(), ItemBase::IsTakeable(), m_AM, m_Hidden, m_Player, and m_Target.
Referenced by Update().
HideWidget()
protected void HideWidget () inline private
References ATCCachedObject::Invalidate(), m_CachedObject, and m_Root.
Referenced by Update().
IsComponentInSelection()
protected bool IsComponentInSelection (array< Selection > selection, string compName) inline private
Referenced by GetOnScreenPosition().
OnInputDeviceChanged()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
References UpdatePCIconsVisibility().
Referenced by ActionTargetsCursor().
OnInputPresetChanged()
protected void OnInputPresetChanged () inline private
References UpdateControllerInputIcons().
Referenced by ActionTargetsCursor().
OnUpdate()
override bool OnUpdate (Widget w) inline private
References m_Root, and Update().
OnWidgetScriptInit()
protected void OnWidgetScriptInit (Widget w) inline private
UA -> widget icon
References m_Container, m_ItemLeft, m_Root, UpdateControllerInputIcons(), and UpdatePCIconsVisibility().
PrepareCursorContent()
protected void PrepareCursorContent () inline private
item health
quantity
cargo in item
fill the widget with data
References GetActionDesc(), GetItemCargoCount(), GetItemDesc(), GetItemHealth(), GetItemQuantity(), m_Continuous, m_ContinuousInteract, m_HealthEnabled, m_Interact, m_QuantityEnabled, m_Single, SetActionWidget(), SetInteractActionIcon(), SetItemDesc(), SetItemHealth(), SetItemQuantity(), SetMultipleContinuousInteractAction(), SetMultipleContinuousItemAction(), SetMultipleInteractAction(), and SetMultipleItemAction().
Referenced by BuildFixedCursor(), and BuildFloatingCursor().
SetActionWidget()
protected void SetActionWidget (ActionBase action, string descText, string actionWidget, string descWidget) inline private
References Class::CastTo(), m_AM, m_MaxWidthChild, m_Root, x, and y.
Referenced by PrepareCursorContent().
SetContinuousInteractXboxIcon()
void SetContinuousInteractXboxIcon (string imageset_name, string image_name) private
SetContinuousXboxIcon()
void SetContinuousXboxIcon (string imageset_name, string image_name) private
SetControllerIcon()
protected void SetControllerIcon (string pWidgetName, string pInputName) inline private
References InputUtils::GetRichtextButtonIconFromInputAction(), and m_Root.
Referenced by UpdateControllerInputIcons().
SetHealthVisibility()
void SetHealthVisibility (bool state) inline private
References m_HealthEnabled.
SetInteractActionIcon()
protected void SetInteractActionIcon (string actionWidget, string actionIconFrameWidget, string actionIconWidget, string actionIconTextWidget) inline private
References Class::CastTo(), InputUtils::GetButtonNameFromInput(), GetDayZGame(), UAIDWrapper::InputP(), m_Root, and m_UseActionWrapper.
Referenced by PrepareCursorContent().
SetInteractXboxIcon()
void SetInteractXboxIcon (string imageset_name, string image_name) private
DEPRECATED.
SetItemDesc()
protected void SetItemDesc (string descText, int cargoCount, string itemWidget, string descWidget) inline private
Last message from finished User Action on target (Thermometer, Blood Test Kit, etc.)
when cargo in container
References Class::CastTo(), string::Format(), string::Length(), m_Root, m_Target, and string::ToUpper().
Referenced by PrepareCursorContent().
SetItemHealth()
protected void SetItemHealth (int health, string itemWidget, string healthWidget, bool enabled) inline private
References Class::CastTo(), ItemManager::GetItemHealthColor(), and m_Root.
Referenced by PrepareCursorContent().
SetItemQuantity()
protected void SetItemQuantity (int type, float current, int min, int max, string itemWidget, string quantityPBWidget, string quantityTextWidget, bool enabled) inline private
References Class::CastTo(), m_Root, QUANTITY_COUNT, QUANTITY_HIDDEN, QUANTITY_PROGRESS, Math::Round(), and float::ToString().
Referenced by PrepareCursorContent().
SetMultipleContinuousInteractAction()
protected void SetMultipleContinuousInteractAction (string multiActionsWidget, string multiActionsWidget_NotSelect) inline private
References m_ContinuousInteractActionsNum, m_Root, and m_SelectedActionCategory.
Referenced by PrepareCursorContent().
SetMultipleContinuousItemAction()
protected void SetMultipleContinuousItemAction (string multiActionsWidget, string multiActionsWidget_NotSelect) inline private
References ContinuousDefaultActionInput(), m_ContinuousItemActionsNum, m_Root, and m_SelectedActionCategory.
Referenced by PrepareCursorContent().
SetMultipleInteractAction()
protected void SetMultipleInteractAction (string multiActionsWidget, string multiActionsWidget_NotSelect) inline private
shows arrows near the interact action if there are more than one available
Referenced by PrepareCursorContent().
SetMultipleItemAction()
protected void SetMultipleItemAction (string multiActionsWidget, string multiActionsWidget_NotSelect) inline private
References m_ItemActionsNum, m_Root, and m_SelectedActionCategory.
Referenced by PrepareCursorContent().
SetQuantityVisibility()
void SetQuantityVisibility (bool state) inline private
References m_QuantityEnabled.
SetSingleXboxIcon()
void SetSingleXboxIcon (string imageset_name, string image_name) private
SetXboxIcon()
protected void SetXboxIcon (string name, string imageset_name, string image_name) private
ShowXboxHidePCIcons()
protected void ShowXboxHidePCIcons (string widget, bool show_xbox_icon) inline private
References m_Root.
Referenced by UpdatePCIconsVisibility().
TransformToScreenPos()
protected vector TransformToScreenPos (vector pWorldPos) inline private
transform world pos to screen pos (related to parent widget size)
get relative pos for screen from world pos vector
get size of parent widget
calculate corrent position from relative pos and parent widget size
Referenced by BuildFloatingCursor(), and GetOnScreenPosition().
Update()
void Update () inline private
don't show floating widget if it's disabled in profile or the player is unconscious
check if action has target, otherwise don't show the widget
cursor with fixed position (environment interaction mainly)
build cursor for new target
use cached version for known target - recalculate onscreen pos only
References BuildFixedCursor(), BuildFloatingCursor(), ScriptedWidgetEventHandler::CheckRefresherFlagVisibility(), g_Game, ATCCachedObject::Get(), GetActionManager(), GetActions(), GetDayZGame(), GetGame(), GetPlayer(), PPEManagerStatic::GetPPEManager(), GetTarget(), HideWidget(), ATCCachedObject::Invalidate(), m_AM, m_CachedObject, m_Continuous, m_ContinuousInteract, m_FixedOnPosition, m_Hidden, m_Hud, m_Interact, m_MaxWidthChild, m_Player, m_Root, m_Single, m_Target, and VISION_OBSTRUCTION_PPEFFECTS_TYPES.
Referenced by OnUpdate(), and Hud::Update().
UpdateControllerInputIcons()
private void UpdateControllerInputIcons () inline private
Loads icons from the latest keybinds.
References SetControllerIcon().
Referenced by OnInputPresetChanged(), and OnWidgetScriptInit().
UpdatePCIconsVisibility()
private void UpdatePCIconsVisibility () inline private
Contains logic for icon set switching (Gamepad/M&K)
References Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), Input::IsEnabledMouseAndKeyboardEvenOnServer(), and ShowXboxHidePCIcons().
Referenced by OnInputDeviceChanged(), and OnWidgetScriptInit().
Field Documentation
m_AM
protected ActionManagerClient m_AM private
Referenced by ActionTargetsCursor(), GetActionManager(), GetTarget(), SetActionWidget(), and Update().
m_CachedObject
protected ref ATCCachedObject m_CachedObject private
Referenced by ActionTargetsCursor(), BuildFloatingCursor(), GetOnScreenPosition(), HideWidget(), and Update().
m_Container
protected Widget m_Container private
Referenced by OnWidgetScriptInit().
m_Continuous
protected ActionBase m_Continuous private
Referenced by ActionTargetsCursor(), PrepareCursorContent(), and Update().
m_ContinuousInteract
protected ActionBase m_ContinuousInteract private
Referenced by ActionTargetsCursor(), PrepareCursorContent(), and Update().
m_ContinuousInteractActionsNum
protected int m_ContinuousInteractActionsNum private
Referenced by SetMultipleContinuousInteractAction().
m_ContinuousItemActionsNum
protected int m_ContinuousItemActionsNum private
Referenced by SetMultipleContinuousItemAction().
m_DisplayInteractTarget
protected Object m_DisplayInteractTarget private
Referenced by ActionTargetsCursor(), GetItemDesc(), GetItemHealth(), and GetItemQuantity().
m_FixedOnPosition
protected bool m_FixedOnPosition private
Referenced by GetOnScreenPosition(), and Update().
m_HealthEnabled
protected bool m_HealthEnabled private
Referenced by ActionTargetsCursor(), PrepareCursorContent(), and SetHealthVisibility().
m_Hidden
protected bool m_Hidden private
Referenced by ActionTargetsCursor(), GetTarget(), and Update().
m_Hud
protected IngameHud m_Hud private
Referenced by ActionTargetsCursor(), and Update().
m_Interact
protected ActionBase m_Interact private
Referenced by ActionTargetsCursor(), GetItemHealth(), GetItemQuantity(), PrepareCursorContent(), and Update().
m_InteractActionsNum
protected int m_InteractActionsNum private
m_ItemActionsNum
protected int m_ItemActionsNum private
Referenced by SetMultipleItemAction().
m_ItemLeft
protected Widget m_ItemLeft private
Referenced by OnWidgetScriptInit().
m_MaxWidthChild
protected float m_MaxWidthChild private
widget width
Referenced by SetActionWidget(), and Update().
m_Player
protected PlayerBase m_Player private
Referenced by CheckRefresherFlagVisibility(), GetActionManager(), GetOnScreenPosition(), GetPlayer(), GetTarget(), and Update().
m_QuantityEnabled
protected bool m_QuantityEnabled private
Referenced by ActionTargetsCursor(), PrepareCursorContent(), and SetQuantityVisibility().
m_Root
protected Widget m_Root private
Referenced by BuildFixedCursor(), BuildFloatingCursor(), CheckRefresherFlagVisibility(), HideWidget(), OnUpdate(), OnWidgetScriptInit(), SetActionWidget(), SetControllerIcon(), SetInteractActionIcon(), SetItemDesc(), SetItemHealth(), SetItemQuantity(), SetMultipleContinuousInteractAction(), SetMultipleContinuousItemAction(), SetMultipleItemAction(), ShowXboxHidePCIcons(), and Update().
m_RootHeight
protected float m_RootHeight private
m_RootWidth
protected float m_RootWidth private
m_SelectedActionCategory
protected m_SelectedActionCategory private
Referenced by SetMultipleContinuousInteractAction(), SetMultipleContinuousItemAction(), and SetMultipleItemAction().
m_Single
protected ActionBase m_Single private
Referenced by ActionTargetsCursor(), PrepareCursorContent(), and Update().
m_Target
protected ActionTarget m_Target private
Referenced by BuildFloatingCursor(), GetItemDesc(), GetItemHealth(), GetItemQuantity(), GetOnScreenPosition(), GetTarget(), SetItemDesc(), and Update().
m_UseActionWrapper
protected UAIDWrapper m_UseActionWrapper private
Referenced by ActionTargetsCursor(), and SetInteractActionIcon().
VISION_OBSTRUCTION_PPEFFECTS_TYPES
private const ref array<typename> VISION_OBSTRUCTION_PPEFFECTS_TYPES private
Initial value:
= {
        PPERequester_BurlapSackEffects,
        PPERequester_FlashbangEffects
    }
Referenced by Update().
The documentation for this class was generated from the following file:
P:/scripts/5_mission/gui/actiontargetscursor.c