DayZ Scripts: CarScript Class Reference
CarScript Class Reference
Private Member Functions
void CivilianSedan ()
override void EEInit ()
override void OnEngineStart ()
override void OnEngineStop ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override int GetAnimInstance ()
override float GetTransportCameraDistance ()
override int GetSeatAnimationType (int posIdx)
override CarLightBase CreateFrontLight ()
override CarRearLightBase CreateRearLight ()
override bool CanReleaseAttachment (EntityAI attachment)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayCargo ()
override int GetCarDoorsState (string slotType)
override bool CrewCanGetThrough (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override string GetAnimSourceFromSelection (string selection)
override bool IsVitalTruckBattery ()
override bool IsVitalGlowPlug ()
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override void OnDebugSpawn ()
void Hatchback_02 ()
override void EEInit ()
override void OnEngineStart ()
override void OnEngineStop ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override int GetAnimInstance ()
override int GetSeatAnimationType (int posIdx)
override CarRearLightBase CreateRearLight ()
override CarLightBase CreateFrontLight ()
override bool CanReleaseAttachment (EntityAI attachment)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayCargo ()
override int GetCarDoorsState (string slotType)
override bool CrewCanGetThrough (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override string GetAnimSourceFromSelection (string selection)
override bool IsVitalTruckBattery ()
override bool IsVitalGlowPlug ()
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override void OnDebugSpawn ()
void Offroad_02 ()
override void EEInit ()
override void OnEngineStart ()
override void OnEngineStop ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override int GetAnimInstance ()
override float GetTransportCameraDistance ()
override int GetSeatAnimationType (int posIdx)
override CarLightBase CreateFrontLight ()
override CarRearLightBase CreateRearLight ()
override bool CanReleaseAttachment (EntityAI attachment)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayCargo ()
override int GetCarDoorsState (string slotType)
override bool CrewCanGetThrough (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override string GetAnimSourceFromSelection (string selection)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool IsVitalTruckBattery ()
override bool IsVitalSparkPlug ()
override bool IsVitalRadiator ()
override void OnDebugSpawn ()
void OffroadHatchback ()
override void EEInit ()
override void OnEngineStart ()
override void OnEngineStop ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override int GetAnimInstance ()
override float GetTransportCameraDistance ()
override int GetSeatAnimationType (int posIdx)
override CarRearLightBase CreateRearLight ()
override CarLightBase CreateFrontLight ()
override bool CanReleaseAttachment (EntityAI attachment)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayCargo ()
override int GetCarDoorsState (string slotType)
override bool CrewCanGetThrough (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override string GetAnimSourceFromSelection (string selection)
override string GetDoorConditionPointFromSelection (string selection)
override int GetCrewIndex (string selection)
override bool IsVitalTruckBattery ()
override bool IsVitalGlowPlug ()
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override int GetSeatIndexFromDoor (string pDoorSelection)
override void SetActions ()
override void OnDebugSpawn ()
void Sedan_02 ()
override void EEInit ()
override void OnEngineStart ()
override void OnEngineStop ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override int GetAnimInstance ()
override int GetSeatAnimationType (int posIdx)
override CarLightBase CreateFrontLight ()
override CarRearLightBase CreateRearLight ()
override bool CanReleaseAttachment (EntityAI attachment)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayCargo ()
override int GetCarDoorsState (string slotType)
override bool CrewCanGetThrough (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override string GetAnimSourceFromSelection (string selection)
override bool IsVitalTruckBattery ()
override bool IsVitalGlowPlug ()
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override void OnDebugSpawn ()
void Truck_01_Base ()
override void EEInit ()
override void OnEngineStart ()
override void OnEngineStop ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override float GetTransportCameraDistance ()
override vector GetTransportCameraOffset ()
override int GetAnimInstance ()
override int GetSeatAnimationType (int posIdx)
override CarLightBase CreateFrontLight ()
override CarRearLightBase CreateRearLight ()
override bool CanReleaseAttachment (EntityAI attachment)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override bool CrewCanGetThrough (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override void OnAnimationPhaseStarted (string animSource, float phase)
override int GetCarDoorsState (string slotType)
override string GetAnimSourceFromSelection (string selection)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override int GetSeatIndexFromDoor (string pDoorSelection)
override bool IsVitalCarBattery ()
override bool IsVitalSparkPlug ()
override bool IsVitalGlowPlug ()
override bool IsVitalEngineBelt ()
override bool IsVitalRadiator ()
override void SetActions ()
override void OnDebugSpawn ()
void Truck_02 ()
override void EEInit ()
override void OnEngineStart ()
override void OnEngineStop ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override int GetAnimInstance ()
override int GetSeatAnimationType (int posIdx)
override int GetCarDoorsState (string slotType)
override bool CrewCanGetThrough (int posIdx)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override string GetAnimSourceFromSelection (string selection)
override bool IsVitalCarBattery ()
override bool IsVitalSparkPlug ()
override bool IsVitalGlowPlug ()
override bool IsVitalEngineBelt ()
override bool IsVitalRadiator ()
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override int GetSeatIndexFromDoor (string pDoorSelection)
override void OnDebugSpawn ()
void Van_01 ()
override void EEInit ()
override void OnEngineStart ()
override void OnEngineStop ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override int GetAnimInstance ()
override int GetSeatAnimationType (int posIdx)
override int GetCarDoorsState (string slotType)
override bool CrewCanGetThrough (int posIdx)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override string GetAnimSourceFromSelection (string selection)
override string GetDoorConditionPointFromSelection (string selection)
override bool IsVitalTruckBattery ()
override bool IsVitalGlowPlug ()
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
Private Attributes
protected ref UniversalTemperatureSource m_UTSource
protected ref UniversalTemperatureSourceSettings m_UTSSettings
protected ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine
Detailed Description
Definition at line 1 of file CivilianSedan.c.
Member Function Documentation
CanDisplayAttachmentCategory() [1/5]
override bool CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 136 of file CivilianSedan.c.
References string::Contains(), GetCarDoorsState(), and string::ToLower().
CanDisplayAttachmentCategory() [2/5]
override bool CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 134 of file Hatchback_02.c.
References string::Contains(), GetCarDoorsState(), and string::ToLower().
CanDisplayAttachmentCategory() [3/5]
override bool CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 148 of file Offroad_02.c.
References string::Contains(), GetCarDoorsState(), and string::ToLower().
CanDisplayAttachmentCategory() [4/5]
override bool CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 141 of file OffroadHatchback.c.
References string::Contains(), GetCarDoorsState(), and string::ToLower().
CanDisplayAttachmentCategory() [5/5]
override bool CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 150 of file Sedan_02.c.
References string::Contains(), GetCarDoorsState(), and string::ToLower().
CanDisplayCargo() [1/5]
override bool CanDisplayCargo () inline private
Definition at line 153 of file CivilianSedan.c.
References GetCarDoorsState().
CanDisplayCargo() [2/5]
override bool CanDisplayCargo () inline private
Definition at line 151 of file Hatchback_02.c.
References GetCarDoorsState().
CanDisplayCargo() [3/5]
override bool CanDisplayCargo () inline private
Definition at line 167 of file Offroad_02.c.
References GetCarDoorsState().
CanDisplayCargo() [4/5]
override bool CanDisplayCargo () inline private
Definition at line 160 of file OffroadHatchback.c.
References GetCarDoorsState().
CanDisplayCargo() [5/5]
override bool CanDisplayCargo () inline private
Definition at line 177 of file Sedan_02.c.
References GetCarDoorsState().
CanManipulateSpareWheel() [1/6]
override protected bool CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 131 of file CivilianSedan.c.
References GetCarDoorsState().
Referenced by CanReceiveAttachment(), and CanReleaseAttachment().
CanManipulateSpareWheel() [2/6]
override protected bool CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 129 of file Hatchback_02.c.
References GetCarDoorsState().
CanManipulateSpareWheel() [3/6]
override protected bool CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 143 of file Offroad_02.c.
References GetCarDoorsState().
CanManipulateSpareWheel() [4/6]
override protected bool CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 136 of file OffroadHatchback.c.
References GetCarDoorsState().
CanManipulateSpareWheel() [5/6]
override protected bool CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 145 of file Sedan_02.c.
References GetCarDoorsState().
CanManipulateSpareWheel() [6/6]
override protected bool CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 132 of file Truck_01_Base.c.
CanReachDoorsFromSeat() [1/8]
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 379 of file CivilianSedan.c.
Referenced by ActionCarDoors::ActionCondition().
CanReachDoorsFromSeat() [2/8]
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 361 of file Hatchback_02.c.
CanReachDoorsFromSeat() [3/8]
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 358 of file Offroad_02.c.
CanReachDoorsFromSeat() [4/8]
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 408 of file OffroadHatchback.c.
CanReachDoorsFromSeat() [5/8]
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 386 of file Sedan_02.c.
CanReachDoorsFromSeat() [6/8]
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 307 of file Truck_01_Base.c.
CanReachDoorsFromSeat() [7/8]
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 244 of file Truck_02.c.
CanReachDoorsFromSeat() [8/8]
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 303 of file Van_01.c.
CanReachSeatFromSeat() [1/8]
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 359 of file CivilianSedan.c.
CanReachSeatFromSeat() [2/8]
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 344 of file Hatchback_02.c.
CanReachSeatFromSeat() [3/8]
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 341 of file Offroad_02.c.
CanReachSeatFromSeat() [4/8]
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 382 of file OffroadHatchback.c.
CanReachSeatFromSeat() [5/8]
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 366 of file Sedan_02.c.
CanReachSeatFromSeat() [6/8]
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 294 of file Truck_01_Base.c.
CanReachSeatFromSeat() [7/8]
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 226 of file Truck_02.c.
CanReachSeatFromSeat() [8/8]
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 277 of file Van_01.c.
CanReleaseAttachment() [1/6]
override bool CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 115 of file CivilianSedan.c.
References GetCarDoorsState().
CanReleaseAttachment() [2/6]
override bool CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 110 of file Hatchback_02.c.
References GetCarDoorsState().
CanReleaseAttachment() [3/6]
override bool CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 115 of file Offroad_02.c.
References GetCarDoorsState().
CanReleaseAttachment() [4/6]
override bool CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 117 of file OffroadHatchback.c.
References GetCarDoorsState().
CanReleaseAttachment() [5/6]
override bool CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 110 of file Sedan_02.c.
References GetCarDoorsState().
CanReleaseAttachment() [6/6]
override bool CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 117 of file Truck_01_Base.c.
CivilianSedan()
void CivilianSedan () inline private
Definition at line 7 of file CivilianSedan.c.
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
CreateFrontLight() [1/6]
override CarLightBase CreateFrontLight () inline private
Definition at line 104 of file CivilianSedan.c.
Referenced by UpdateLightsClient().
CreateFrontLight() [2/6]
override CarLightBase CreateFrontLight () inline private
Definition at line 105 of file Hatchback_02.c.
CreateFrontLight() [3/6]
override CarLightBase CreateFrontLight () inline private
Definition at line 104 of file Offroad_02.c.
CreateFrontLight() [4/6]
override CarLightBase CreateFrontLight () inline private
Definition at line 112 of file OffroadHatchback.c.
CreateFrontLight() [5/6]
override CarLightBase CreateFrontLight () inline private
Definition at line 99 of file Sedan_02.c.
CreateFrontLight() [6/6]
override CarLightBase CreateFrontLight () inline private
Definition at line 106 of file Truck_01_Base.c.
CreateRearLight() [1/6]
override CarRearLightBase CreateRearLight () inline private
Definition at line 110 of file CivilianSedan.c.
Referenced by UpdateLightsClient().
CreateRearLight() [2/6]
override CarRearLightBase CreateRearLight () inline private
Definition at line 99 of file Hatchback_02.c.
CreateRearLight() [3/6]
override CarRearLightBase CreateRearLight () inline private
Definition at line 110 of file Offroad_02.c.
CreateRearLight() [4/6]
override CarRearLightBase CreateRearLight () inline private
Definition at line 107 of file OffroadHatchback.c.
CreateRearLight() [5/6]
override CarRearLightBase CreateRearLight () inline private
Definition at line 105 of file Sedan_02.c.
CreateRearLight() [6/6]
override CarRearLightBase CreateRearLight () inline private
Definition at line 112 of file Truck_01_Base.c.
CrewCanGetThrough() [1/8]
override bool CrewCanGetThrough (int posIdx) inline private
Definition at line 205 of file CivilianSedan.c.
References GetCarDoorsState().
CrewCanGetThrough() [2/8]
override bool CrewCanGetThrough (int posIdx) inline private
Definition at line 197 of file Hatchback_02.c.
References GetCarDoorsState().
CrewCanGetThrough() [3/8]
override bool CrewCanGetThrough (int posIdx) inline private
Definition at line 213 of file Offroad_02.c.
References GetCarDoorsState().
CrewCanGetThrough() [4/8]
override bool CrewCanGetThrough (int posIdx) inline private
Definition at line 203 of file OffroadHatchback.c.
References GetCarDoorsState().
CrewCanGetThrough() [5/8]
override bool CrewCanGetThrough (int posIdx) inline private
Definition at line 223 of file Sedan_02.c.
References GetCarDoorsState().
CrewCanGetThrough() [6/8]
override bool CrewCanGetThrough (int posIdx) inline private
Definition at line 147 of file Truck_01_Base.c.
References GetCarDoorsState().
CrewCanGetThrough() [7/8]
override bool CrewCanGetThrough (int posIdx) inline private
Definition at line 125 of file Truck_02.c.
References GetCarDoorsState().
CrewCanGetThrough() [8/8]
override bool CrewCanGetThrough (int posIdx) inline private
Definition at line 143 of file Van_01.c.
References GetCarDoorsState().
EEInit() [1/8]
override void EEInit () inline private
Definition at line 26 of file CivilianSedan.c.
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [2/8]
override void EEInit () inline private
Definition at line 26 of file Hatchback_02.c.
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [3/8]
override void EEInit () inline private
Definition at line 26 of file Offroad_02.c.
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [4/8]
override void EEInit () inline private
Definition at line 28 of file OffroadHatchback.c.
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [5/8]
override void EEInit () inline private
Definition at line 26 of file Sedan_02.c.
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [6/8]
override void EEInit () inline private
Definition at line 27 of file Truck_01_Base.c.
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [7/8]
override void EEInit () inline private
Definition at line 13 of file Truck_02.c.
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [8/8]
override void EEInit () inline private
Definition at line 12 of file Van_01.c.
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [1/8]
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 65 of file CivilianSedan.c.
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [2/8]
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 65 of file Hatchback_02.c.
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [3/8]
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 65 of file Offroad_02.c.
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [4/8]
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 67 of file OffroadHatchback.c.
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [5/8]
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 65 of file Sedan_02.c.
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [6/8]
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 66 of file Truck_01_Base.c.
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [7/8]
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 52 of file Truck_02.c.
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [8/8]
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 51 of file Van_01.c.
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
GetAnimInstance() [1/8]
override int GetAnimInstance () inline private
Definition at line 76 of file CivilianSedan.c.
GetAnimInstance() [2/8]
override int GetAnimInstance () inline private
Definition at line 76 of file Hatchback_02.c.
GetAnimInstance() [3/8]
override int GetAnimInstance () inline private
Definition at line 76 of file Offroad_02.c.
GetAnimInstance() [4/8]
override int GetAnimInstance () inline private
Definition at line 78 of file OffroadHatchback.c.
GetAnimInstance() [5/8]
override int GetAnimInstance () inline private
Definition at line 76 of file Sedan_02.c.
GetAnimInstance() [6/8]
override int GetAnimInstance () inline private
Definition at line 87 of file Truck_01_Base.c.
GetAnimInstance() [7/8]
override int GetAnimInstance () inline private
Definition at line 63 of file Truck_02.c.
GetAnimInstance() [8/8]
override int GetAnimInstance () inline private
Definition at line 63 of file Van_01.c.
GetAnimSourceFromSelection() [1/8]
override string GetAnimSourceFromSelection (string selection) inline private
Definition at line 328 of file CivilianSedan.c.
Referenced by ActionAnimateCarSelection::ActionCondition(), ActionAnimateSeats::ActionCondition(), ActionCarDoors::ActionCondition(), ActionCarDoorsOutside::ActionCondition(), ActionCarDoors::OnStartServer(), and ActionCarDoorsOutside::OnStartServer().
GetAnimSourceFromSelection() [2/8]
override string GetAnimSourceFromSelection (string selection) inline private
Definition at line 312 of file Hatchback_02.c.
GetAnimSourceFromSelection() [3/8]
override string GetAnimSourceFromSelection (string selection) inline private
Definition at line 320 of file Offroad_02.c.
GetAnimSourceFromSelection() [4/8]
override string GetAnimSourceFromSelection (string selection) inline private
Definition at line 321 of file OffroadHatchback.c.
GetAnimSourceFromSelection() [5/8]
override string GetAnimSourceFromSelection (string selection) inline private
Definition at line 334 of file Sedan_02.c.
GetAnimSourceFromSelection() [6/8]
override string GetAnimSourceFromSelection (string selection) inline private
Definition at line 273 of file Truck_01_Base.c.
GetAnimSourceFromSelection() [7/8]
override string GetAnimSourceFromSelection (string selection) inline private
Definition at line 180 of file Truck_02.c.
GetAnimSourceFromSelection() [8/8]
override string GetAnimSourceFromSelection (string selection) inline private
Definition at line 222 of file Van_01.c.
GetCarDoorsState() [1/8]
override int GetCarDoorsState (string slotType) inline private
Definition at line 164 of file CivilianSedan.c.
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
Referenced by ActionLockAttachment::ActionCondition(), ActionCondition(), ActionAnimateSeats::ActionCondition(), ActionCarDoors::ActionCondition(), InventoryItemSuper::CanDetachAttachment(), CanDisplayAttachmentCategory(), CanDisplayCargo(), CanManipulateSpareWheel(), CanReleaseAttachment(), CrewCanGetThrough(), and OnSound().
GetCarDoorsState() [2/8]
override int GetCarDoorsState (string slotType) inline private
Definition at line 162 of file Hatchback_02.c.
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
GetCarDoorsState() [3/8]
override int GetCarDoorsState (string slotType) inline private
Definition at line 178 of file Offroad_02.c.
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
GetCarDoorsState() [4/8]
override int GetCarDoorsState (string slotType) inline private
Definition at line 175 of file OffroadHatchback.c.
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
GetCarDoorsState() [5/8]
override int GetCarDoorsState (string slotType) inline private
Definition at line 188 of file Sedan_02.c.
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
GetCarDoorsState() [6/8]
override int GetCarDoorsState (string slotType) inline private
Definition at line 251 of file Truck_01_Base.c.
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
GetCarDoorsState() [7/8]
override int GetCarDoorsState (string slotType) inline private
Definition at line 81 of file Truck_02.c.
References Class::CastTo().
GetCarDoorsState() [8/8]
override int GetCarDoorsState (string slotType) inline private
Definition at line 89 of file Van_01.c.
References Class::CastTo().
GetCrewIndex()
override int GetCrewIndex (string selection) inline private
Definition at line 359 of file OffroadHatchback.c.
GetDoorConditionPointFromSelection() [1/2]
override string GetDoorConditionPointFromSelection (string selection) inline private
Definition at line 342 of file OffroadHatchback.c.
Referenced by CanReachSeatFromDoors().
GetDoorConditionPointFromSelection() [2/2]
override string GetDoorConditionPointFromSelection (string selection) inline private
Definition at line 244 of file Van_01.c.
GetDoorInvSlotNameFromSeatPos() [1/6]
override string GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 262 of file CivilianSedan.c.
Referenced by ActionCarDoors::ActionCondition().
GetDoorInvSlotNameFromSeatPos() [2/6]
override string GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 258 of file Hatchback_02.c.
GetDoorInvSlotNameFromSeatPos() [3/6]
override string GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 270 of file Offroad_02.c.
GetDoorInvSlotNameFromSeatPos() [4/6]
override string GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 259 of file OffroadHatchback.c.
GetDoorInvSlotNameFromSeatPos() [5/6]
override string GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 280 of file Sedan_02.c.
GetDoorInvSlotNameFromSeatPos() [6/6]
override string GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 183 of file Truck_01_Base.c.
GetDoorSelectionNameFromSeatPos() [1/6]
override string GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 241 of file CivilianSedan.c.
Referenced by ActionCarDoors::ActionCondition(), and ActionCarDoors::OnStartServer().
GetDoorSelectionNameFromSeatPos() [2/6]
override string GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 237 of file Hatchback_02.c.
GetDoorSelectionNameFromSeatPos() [3/6]
override string GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 249 of file Offroad_02.c.
GetDoorSelectionNameFromSeatPos() [4/6]
override string GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 244 of file OffroadHatchback.c.
GetDoorSelectionNameFromSeatPos() [5/6]
override string GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 259 of file Sedan_02.c.
GetDoorSelectionNameFromSeatPos() [6/6]
override string GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 168 of file Truck_01_Base.c.
GetSeatAnimationType() [1/8]
override int GetSeatAnimationType (int posIdx) inline private
Definition at line 86 of file CivilianSedan.c.
GetSeatAnimationType() [2/8]
override int GetSeatAnimationType (int posIdx) inline private
Definition at line 81 of file Hatchback_02.c.
GetSeatAnimationType() [3/8]
override int GetSeatAnimationType (int posIdx) inline private
Definition at line 86 of file Offroad_02.c.
GetSeatAnimationType() [4/8]
override int GetSeatAnimationType (int posIdx) inline private
Definition at line 88 of file OffroadHatchback.c.
GetSeatAnimationType() [5/8]
override int GetSeatAnimationType (int posIdx) inline private
Definition at line 81 of file Sedan_02.c.
GetSeatAnimationType() [6/8]
override int GetSeatAnimationType (int posIdx) inline private
Definition at line 92 of file Truck_01_Base.c.
GetSeatAnimationType() [7/8]
override int GetSeatAnimationType (int posIdx) inline private
Definition at line 68 of file Truck_02.c.
GetSeatAnimationType() [8/8]
override int GetSeatAnimationType (int posIdx) inline private
Definition at line 69 of file Van_01.c.
GetSeatIndexFromDoor() [1/3]
override int GetSeatIndexFromDoor (string pDoorSelection) inline private
Definition at line 428 of file OffroadHatchback.c.
Referenced by ActionCarDoorsOutside::ActionCondition().
GetSeatIndexFromDoor() [2/3]
override int GetSeatIndexFromDoor (string pDoorSelection) inline private
Definition at line 321 of file Truck_01_Base.c.
GetSeatIndexFromDoor() [3/3]
override int GetSeatIndexFromDoor (string pDoorSelection) inline private
Definition at line 266 of file Truck_02.c.
GetTransportCameraDistance() [1/4]
override float GetTransportCameraDistance () inline private
Definition at line 81 of file CivilianSedan.c.
GetTransportCameraDistance() [2/4]
override float GetTransportCameraDistance () inline private
Definition at line 81 of file Offroad_02.c.
GetTransportCameraDistance() [3/4]
override float GetTransportCameraDistance () inline private
Definition at line 83 of file OffroadHatchback.c.
GetTransportCameraDistance() [4/4]
override float GetTransportCameraDistance () inline private
Definition at line 77 of file Truck_01_Base.c.
GetTransportCameraOffset()
override vector GetTransportCameraOffset () inline private
Definition at line 82 of file Truck_01_Base.c.
Hatchback_02()
void Hatchback_02 () inline private
Definition at line 7 of file Hatchback_02.c.
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
IsVitalCarBattery() [1/2]
override bool IsVitalCarBattery () inline private
Definition at line 336 of file Truck_01_Base.c.
Referenced by ActionSwitchLights::ActionCondition(), EOnPostSimulate(), GetBattery(), OnBeforeEngineStart(), and SpawnUniversalParts().
IsVitalCarBattery() [2/2]
override bool IsVitalCarBattery () inline private
Definition at line 201 of file Truck_02.c.
IsVitalEngineBelt() [1/2]
override bool IsVitalEngineBelt () inline private
Definition at line 351 of file Truck_01_Base.c.
IsVitalEngineBelt() [2/2]
override bool IsVitalEngineBelt () inline private
Definition at line 216 of file Truck_02.c.
IsVitalGlowPlug() [1/7]
override bool IsVitalGlowPlug () inline private
Definition at line 354 of file CivilianSedan.c.
Referenced by EOnPostSimulate(), OnBeforeEngineStart(), and SpawnUniversalParts().
IsVitalGlowPlug() [2/7]
override bool IsVitalGlowPlug () inline private
Definition at line 339 of file Hatchback_02.c.
IsVitalGlowPlug() [3/7]
override bool IsVitalGlowPlug () inline private
Definition at line 377 of file OffroadHatchback.c.
IsVitalGlowPlug() [4/7]
override bool IsVitalGlowPlug () inline private
Definition at line 361 of file Sedan_02.c.
IsVitalGlowPlug() [5/7]
override bool IsVitalGlowPlug () inline private
Definition at line 346 of file Truck_01_Base.c.
IsVitalGlowPlug() [6/7]
override bool IsVitalGlowPlug () inline private
Definition at line 211 of file Truck_02.c.
IsVitalGlowPlug() [7/7]
override bool IsVitalGlowPlug () inline private
Definition at line 271 of file Van_01.c.
IsVitalRadiator() [1/3]
override bool IsVitalRadiator () inline private
Definition at line 385 of file Offroad_02.c.
Referenced by EOnPostSimulate(), Hud::RefreshVehicleHud(), and SpawnUniversalParts().
IsVitalRadiator() [2/3]
override bool IsVitalRadiator () inline private
Definition at line 356 of file Truck_01_Base.c.
IsVitalRadiator() [3/3]
override bool IsVitalRadiator () inline private
Definition at line 221 of file Truck_02.c.
IsVitalSparkPlug() [1/3]
override bool IsVitalSparkPlug () inline private
Definition at line 380 of file Offroad_02.c.
Referenced by EOnPostSimulate(), OnBeforeEngineStart(), and SpawnUniversalParts().
IsVitalSparkPlug() [2/3]
override bool IsVitalSparkPlug () inline private
Definition at line 341 of file Truck_01_Base.c.
IsVitalSparkPlug() [3/3]
override bool IsVitalSparkPlug () inline private
Definition at line 206 of file Truck_02.c.
IsVitalTruckBattery() [1/6]
override bool IsVitalTruckBattery () inline private
Definition at line 349 of file CivilianSedan.c.
Referenced by ActionSwitchLights::ActionCondition(), EOnPostSimulate(), GetBattery(), OnBeforeEngineStart(), and SpawnUniversalParts().
IsVitalTruckBattery() [2/6]
override bool IsVitalTruckBattery () inline private
Definition at line 334 of file Hatchback_02.c.
IsVitalTruckBattery() [3/6]
override bool IsVitalTruckBattery () inline private
Definition at line 375 of file Offroad_02.c.
IsVitalTruckBattery() [4/6]
override bool IsVitalTruckBattery () inline private
Definition at line 372 of file OffroadHatchback.c.
IsVitalTruckBattery() [5/6]
override bool IsVitalTruckBattery () inline private
Definition at line 356 of file Sedan_02.c.
IsVitalTruckBattery() [6/6]
override bool IsVitalTruckBattery () inline private
Definition at line 265 of file Van_01.c.
Offroad_02()
void Offroad_02 () inline private
Definition at line 7 of file Offroad_02.c.
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
OffroadHatchback()
void OffroadHatchback () inline private
Definition at line 7 of file OffroadHatchback.c.
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_CarSeatShiftInSound, m_CarSeatShiftOutSound, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
OnAnimationPhaseStarted()
override void OnAnimationPhaseStarted (string animSource, float phase) inline private
Definition at line 223 of file Truck_01_Base.c.
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
OnDebugSpawn() [1/7]
override void OnDebugSpawn () inline private
Definition at line 399 of file CivilianSedan.c.
References FillUpCarFluids(), SpawnAdditionalItems(), and SpawnUniversalParts().
OnDebugSpawn() [2/7]
override void OnDebugSpawn () inline private
Definition at line 378 of file Hatchback_02.c.
References FillUpCarFluids(), SpawnAdditionalItems(), and SpawnUniversalParts().
OnDebugSpawn() [3/7]
override void OnDebugSpawn () inline private
Definition at line 390 of file Offroad_02.c.
References FillUpCarFluids(), SpawnAdditionalItems(), and SpawnUniversalParts().
OnDebugSpawn() [4/7]
override void OnDebugSpawn () inline private
Definition at line 448 of file OffroadHatchback.c.
References FillUpCarFluids(), SpawnAdditionalItems(), and SpawnUniversalParts().
OnDebugSpawn() [5/7]
override void OnDebugSpawn () inline private
Definition at line 406 of file Sedan_02.c.
References FillUpCarFluids(), SpawnAdditionalItems(), and SpawnUniversalParts().
OnDebugSpawn() [6/7]
override void OnDebugSpawn () inline private
Definition at line 373 of file Truck_01_Base.c.
References FillUpCarFluids(), SpawnAdditionalItems(), and SpawnUniversalParts().
OnDebugSpawn() [7/7]
override void OnDebugSpawn () inline private
Definition at line 280 of file Truck_02.c.
References Class::CastTo().
OnEngineStart() [1/8]
override void OnEngineStart () inline private
Definition at line 45 of file CivilianSedan.c.
References GetGame(), and m_UTSource.
OnEngineStart() [2/8]
override void OnEngineStart () inline private
Definition at line 45 of file Hatchback_02.c.
References GetGame(), and m_UTSource.
OnEngineStart() [3/8]
override void OnEngineStart () inline private
Definition at line 45 of file Offroad_02.c.
References GetGame(), and m_UTSource.
OnEngineStart() [4/8]
override void OnEngineStart () inline private
Definition at line 47 of file OffroadHatchback.c.
References GetGame(), and m_UTSource.
OnEngineStart() [5/8]
override void OnEngineStart () inline private
Definition at line 45 of file Sedan_02.c.
References GetGame(), and m_UTSource.
OnEngineStart() [6/8]
override void OnEngineStart () inline private
Definition at line 46 of file Truck_01_Base.c.
References GetGame(), and m_UTSource.
OnEngineStart() [7/8]
override void OnEngineStart () inline private
Definition at line 32 of file Truck_02.c.
References GetGame(), and m_UTSource.
OnEngineStart() [8/8]
override void OnEngineStart () inline private
Definition at line 31 of file Van_01.c.
References GetGame(), and m_UTSource.
OnEngineStop() [1/8]
override void OnEngineStop () inline private
Definition at line 55 of file CivilianSedan.c.
References GetGame(), and m_UTSource.
OnEngineStop() [2/8]
override void OnEngineStop () inline private
Definition at line 55 of file Hatchback_02.c.
References GetGame(), and m_UTSource.
OnEngineStop() [3/8]
override void OnEngineStop () inline private
Definition at line 55 of file Offroad_02.c.
References GetGame(), and m_UTSource.
OnEngineStop() [4/8]
override void OnEngineStop () inline private
Definition at line 57 of file OffroadHatchback.c.
References GetGame(), and m_UTSource.
OnEngineStop() [5/8]
override void OnEngineStop () inline private
Definition at line 55 of file Sedan_02.c.
References GetGame(), and m_UTSource.
OnEngineStop() [6/8]
override void OnEngineStop () inline private
Definition at line 56 of file Truck_01_Base.c.
References GetGame(), and m_UTSource.
OnEngineStop() [7/8]
override void OnEngineStop () inline private
Definition at line 42 of file Truck_02.c.
References GetGame(), and m_UTSource.
OnEngineStop() [8/8]
override void OnEngineStop () inline private
Definition at line 41 of file Van_01.c.
References GetGame(), and m_UTSource.
OnSound() [1/8]
override float OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 285 of file CivilianSedan.c.
References Math::Clamp(), GetCarDoorsState(), and GameConstants::STATE_RUINED.
OnSound() [2/8]
override float OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 279 of file Hatchback_02.c.
References Math::Clamp(), and GetCarDoorsState().
OnSound() [3/8]
override float OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 287 of file Offroad_02.c.
References Math::Clamp(), and GetCarDoorsState().
OnSound() [4/8]
override float OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 276 of file OffroadHatchback.c.
References Math::Clamp(), GetCarDoorsState(), and GameConstants::STATE_RUINED.
OnSound() [5/8]
override float OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 301 of file Sedan_02.c.
References Math::Clamp(), and GetCarDoorsState().
OnSound() [6/8]
override float OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 198 of file Truck_01_Base.c.
References Math::Clamp(), and GetCarDoorsState().
OnSound() [7/8]
override float OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 152 of file Truck_02.c.
References GetCarDoorsState().
OnSound() [8/8]
override float OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 184 of file Van_01.c.
References GetCarDoorsState().
Sedan_02()
void Sedan_02 () inline private
Definition at line 7 of file Sedan_02.c.
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_dmgContactCoef, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
SetActions() [1/2]
override void SetActions () inline private
Definition at line 441 of file OffroadHatchback.c.
References AddAction().
Referenced by InitializeActions().
SetActions() [2/2]
override void SetActions () inline private
Definition at line 361 of file Truck_01_Base.c.
References ActionDetachFromTarget_SpecificSlot_MetalSheets(), ActionDetachFromTarget_SpecificSlot_WoodenLogs(), ActionDetachFromTarget_SpecificSlotsCategory_WoodenCrate(), and AddAction().
Truck_01_Base()
void Truck_01_Base () inline private
Definition at line 7 of file Truck_01_Base.c.
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_enginePtcPos, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
Truck_02()
void Truck_02 () inline private
Definition at line 7 of file Truck_02.c.
References m_enginePtcPos.
Van_01()
void Van_01 () inline private
Definition at line 7 of file Van_01.c.
Field Documentation
m_UTSLEngine
protected ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine private
Definition at line 5 of file CivilianSedan.c.
m_UTSource
protected ref UniversalTemperatureSource m_UTSource private
Definition at line 3 of file CivilianSedan.c.
m_UTSSettings
protected ref UniversalTemperatureSourceSettings m_UTSSettings private
Definition at line 4 of file CivilianSedan.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Vehicles/InheritedCars/CivilianSedan.c
P:/scripts/4_World/Entities/Vehicles/InheritedCars/Hatchback_02.c
P:/scripts/4_World/Entities/Vehicles/InheritedCars/Offroad_02.c
P:/scripts/4_World/Entities/Vehicles/InheritedCars/OffroadHatchback.c
P:/scripts/4_World/Entities/Vehicles/InheritedCars/Sedan_02.c
P:/scripts/4_World/Entities/Vehicles/InheritedCars/Truck_01_Base.c
P:/scripts/4_World/Entities/Vehicles/InheritedCars/Truck_02.c
P:/scripts/4_World/Entities/Vehicles/InheritedCars/Van_01.c