DayZ Scripts: FireplaceBase Class Reference
FireplaceBase Class Reference
Private Member Functions
void BarrelHoles_ColorBase ()
override int GetDamageSystemVersionChange ()
override string GetInvulnerabilityTypeString ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override bool CanDetachAttachment (EntityAI parent)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool IsBarrelWithHoles ()
override void OnVariablesSynchronized ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanLoadAttachment (EntityAI attachment)
override void EEItemAttached (EntityAI item, string slot_name)
override bool IsPrepareToDelete ()
override void EEItemDetached (EntityAI item, string slot_name)
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool CanReleaseCargo (EntityAI cargo)
override bool CanPutIntoHands (EntityAI parent)
override bool CanDisplayCargo ()
override bool CanDisplayAttachmentCategory (string category_name)
override void Open ()
void OpenLoad ()
override void Close ()
void CloseLoad ()
override bool IsOpen ()
protected void UpdateVisualState ()
override bool CanExtinguishFire ()
override bool CanShowSmoke ()
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool IsIgnited ()
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
void SoundBarrelOpenPlay ()
void SoundBarrelClosePlay ()
void DestroyClutterCutter (Object clutter_cutter)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
override string GetPlaceSoundset ()
override void SetActions ()
override void OnDebugSpawn ()
void Fireplace ()
override bool IsBaseFireplace ()
override void EOnTouch (IEntity other, int extra)
override void EOnContact (IEntity other, Contact extra)
void ContactEvent (IEntity other, vector position)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanDisplayAttachmentSlot (int slot_id)
override bool CanLoadAttachment (EntityAI attachment)
override bool CanReleaseAttachment (EntityAI attachment)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void SetCookingEquipment (ItemBase equipment)
override void OnBeforeTryDelete ()
override bool IsPrepareToDelete ()
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool CanPutIntoHands (EntityAI parent)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanAssignAttachmentsToQuickbar ()
override float HeightStartCheckOverride ()
override bool CanShowSmoke ()
void DestroyClutterCutter (Object clutter_cutter)
override void RefreshPhysics ()
override void RefreshFireplacePhysics ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool IsIgnited ()
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
override string GetPlaceSoundset ()
override void SetActions ()
void FireplaceIndoor ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void SetFirePointIndex (int fire_point_index)
void SetSmokePointPosition (vector smoke_point_pos)
override protected vector GetSmokeEffectPosition ()
override void ParticleSmallSmokeStart ()
override void ParticleNormalSmokeStart ()
override bool IsFireplaceIndoor ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanPutIntoHands (EntityAI parent)
override bool CanRemoveFromHands (EntityAI player)
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool IsIgnited ()
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
void OvenIndoor ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void SetFirePointIndex (int fire_point_index)
void SetSmokePointPosition (vector smoke_point_pos)
override protected vector GetSmokeEffectPosition ()
override void ParticleSmallSmokeStart ()
override void ParticleNormalSmokeStart ()
override bool IsIndoorOven ()
override bool CanReleaseAttachment (EntityAI attachment)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanRemoveFromHands (EntityAI player)
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool IsIgnited ()
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
Static Private Member Functions
static Fireplace IgniteEntityAsFireplace (notnull EntityAI entity, notnull EntityAI fire_source)
static bool CanIgniteEntityAsFireplace (notnull EntityAI entity)
static int GetFirePointIndex (string action_selection)
static bool CanPlaceFireplaceInSelectedSpot (Object building, int fire_point_index, out vector fire_point_pos_world, out vector fire_point_rot_world)
static int GetFirePointIndex (string action_selection)
static bool CanPlaceFireplaceInSelectedSpot (Object building, int fire_point_index, out vector fire_point_pos_world, out vector fire_point_rot_world)
Private Attributes
const string ANIMATION_OPENED = "LidOff"
const string ANIMATION_CLOSED = "LidOn"
protected bool m_IsOpenedClient = false
protected ref OpenableBehaviour m_Openable
bool m_ContactEventProcessing
protected float m_SmokePosX
protected float m_SmokePosY
protected float m_SmokePosZ
protected int m_FirePointIndex = 1
Static Private Attributes
static const string FIREPOINT_ACTION_SELECTION = "fireplace_action"
static const string FIREPOINT_FIRE_POSITION = "fireplace_point"
static const string FIREPOINT_PLACE_ROT = "fireplace_rot"
static const string FIREPOINT_SMOKE_POSITION = "fireplace_smoke"
static const string OVENPOINT_ACTION_SELECTION = "oven_action"
static const string OVENPOINT_FIRE_POSITION = "oven_point"
static const string OVENPOINT_PLACE_ROT = "oven_rot"
static const string OVENPOINT_SMOKE_POSITION = "oven_smoke"
Detailed Description
Definition at line 1 of file BarrelHoles_ColorBase.c.
Member Function Documentation
AfterStoreLoad()
override void AfterStoreLoad () inline private
Definition at line 556 of file Fireplace.c.
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), GetOrientation(), GetPosition, IsBurning(), m_ClutterCutter, and OBJECT_CLUTTER_CUTTER.
BarrelHoles_ColorBase()
void BarrelHoles_ColorBase () inline private
Definition at line 11 of file BarrelHoles_ColorBase.c.
References ParticleList::BARREL_FIRE_END, ParticleList::BARREL_FIRE_START, ParticleList::BARREL_FIRE_STEAM_2END, ParticleList::BARREL_NORMAL_FIRE, ParticleList::BARREL_NORMAL_SMOKE, ParticleList::BARREL_SMALL_FIRE, ParticleList::BARREL_SMALL_SMOKE, GetInvulnerabilityTypeString(), m_LightDistance, PARTICLE_FIRE_END, PARTICLE_FIRE_START, PARTICLE_NORMAL_FIRE, PARTICLE_NORMAL_SMOKE, PARTICLE_SMALL_FIRE, PARTICLE_SMALL_SMOKE, and PARTICLE_STEAM_END.
CanAssignAttachmentsToQuickbar()
override bool CanAssignAttachmentsToQuickbar () inline private
Definition at line 464 of file Fireplace.c.
CanBeIgnitedBy() [1/4]
override bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 474 of file BarrelHoles_ColorBase.c.
References HasAnyKindling(), IsBurning(), and IsOpen().
CanBeIgnitedBy() [2/4]
override bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 580 of file Fireplace.c.
References HasAnyKindling(), and IsBurning().
CanBeIgnitedBy() [3/4]
override bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 321 of file FireplaceIndoor.c.
References HasAnyKindling().
CanBeIgnitedBy() [4/4]
override bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 303 of file OvenIndoor.c.
References HasAnyKindling().
CanDetachAttachment()
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 56 of file BarrelHoles_ColorBase.c.
References GetNumberOfItems().
CanDisplayAttachmentCategory() [1/2]
override bool CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 368 of file BarrelHoles_ColorBase.c.
References IsOpen().
CanDisplayAttachmentCategory() [2/2]
override bool CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 442 of file Fireplace.c.
References IsOven().
CanDisplayAttachmentSlot()
override bool CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 94 of file Fireplace.c.
References InventorySlots::GetSlotName().
CanDisplayCargo()
override bool CanDisplayCargo () inline private
Definition at line 356 of file BarrelHoles_ColorBase.c.
References IsOpen().
CanExtinguishFire()
override bool CanExtinguishFire () inline private
Definition at line 452 of file BarrelHoles_ColorBase.c.
References IsBurning(), and IsOpen().
Referenced by ActionExtinguishFireplaceByExtinguisher::ActionCondition(), and ActionExtinguishFireplaceByLiquid::ActionCondition().
CanIgniteEntityAsFireplace()
static bool CanIgniteEntityAsFireplace (notnull EntityAI entity) inline static private
Definition at line 734 of file Fireplace.c.
References IsEntityOnInteriorSurface().
CanIgniteItem() [1/4]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 484 of file BarrelHoles_ColorBase.c.
References IsBurning(), and IsOpen().
CanIgniteItem() [2/4]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 585 of file Fireplace.c.
References IsBurning().
CanIgniteItem() [3/4]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 331 of file FireplaceIndoor.c.
References IsBurning().
CanIgniteItem() [4/4]
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 313 of file OvenIndoor.c.
References IsBurning().
CanLoadAttachment() [1/2]
override bool CanLoadAttachment (EntityAI attachment) inline private
Definition at line 154 of file BarrelHoles_ColorBase.c.
References ItemBase::CanLoadAttachment(), GetHealthLevel(), and GameConstants::STATE_RUINED.
CanLoadAttachment() [2/2]
override bool CanLoadAttachment (EntityAI attachment) inline private
IsOven() &&
Definition at line 106 of file Fireplace.c.
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ATTACHMENT_STONES, and ATTACHMENT_TRIPOD.
CanLoadItemIntoCargo() [1/2]
override bool CanLoadItemIntoCargo (EntityAI item) inline private
Definition at line 315 of file BarrelHoles_ColorBase.c.
References GetHealthLevel(), and GameConstants::STATE_RUINED.
CanLoadItemIntoCargo() [2/2]
override bool CanLoadItemIntoCargo (EntityAI item) inline private
Definition at line 415 of file Fireplace.c.
CanPlaceFireplaceInSelectedSpot() [1/2]
static bool CanPlaceFireplaceInSelectedSpot (Object building, int fire_point_index, out vector fire_point_pos_world, out vector fire_point_rot_world) inline static private
Definition at line 99 of file FireplaceIndoor.c.
References GetGame(), CGame::GetObjectsAtPosition3D(), and string::ToString().
CanPlaceFireplaceInSelectedSpot() [2/2]
static bool CanPlaceFireplaceInSelectedSpot (Object building, int fire_point_index, out vector fire_point_pos_world, out vector fire_point_rot_world) inline static private
Definition at line 99 of file OvenIndoor.c.
References GetGame(), CGame::GetObjectsAtPosition3D(), and string::ToString().
CanPutInCargo() [1/4]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 287 of file BarrelHoles_ColorBase.c.
References DirectCookingSlotsInUse(), IsBurning(), IsCargoEmpty(), and IsOpen().
CanPutInCargo() [2/4]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 386 of file Fireplace.c.
References HasAshes(), HasCookingStand(), HasStoneCircle(), HasStones(), IsBurning(), IsCargoEmpty(), and IsOven().
CanPutInCargo() [3/4]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 288 of file FireplaceIndoor.c.
CanPutInCargo() [4/4]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 276 of file OvenIndoor.c.
CanPutIntoHands() [1/4]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 335 of file BarrelHoles_ColorBase.c.
References DirectCookingSlotsInUse(), IsBurning(), IsCargoEmpty(), IsOpen(), and SmokingSlotsInUse().
CanPutIntoHands() [2/4]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 427 of file Fireplace.c.
References HasAshes(), HasCookingStand(), HasStoneCircle(), HasStones(), IsBurning(), IsCargoEmpty(), and IsOven().
CanPutIntoHands() [3/4]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 305 of file FireplaceIndoor.c.
CanPutIntoHands() [4/4]
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 287 of file OvenIndoor.c.
CanReceiveAttachment() [1/2]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 128 of file BarrelHoles_ColorBase.c.
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ItemBase::CanReceiveAttachment(), GetHealthLevel(), IsFuel(), IsKindling(), IsOpen(), and GameConstants::STATE_RUINED.
CanReceiveAttachment() [2/2]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 46 of file Fireplace.c.
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ATTACHMENT_STONES, IsBurning(), and IsOven().
CanReceiveItemIntoCargo() [1/3]
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 304 of file BarrelHoles_ColorBase.c.
References GetHealthLevel(), IsOpen(), and GameConstants::STATE_RUINED.
CanReceiveItemIntoCargo() [2/3]
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 407 of file Fireplace.c.
CanReceiveItemIntoCargo() [3/3]
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 299 of file FireplaceIndoor.c.
CanReleaseAttachment() [1/2]
override bool CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 150 of file Fireplace.c.
References ATTACHMENT_STONES, HasStoneCircle(), IsBurning(), and IsOven().
CanReleaseAttachment() [2/2]
override bool CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 160 of file OvenIndoor.c.
References IsBurning(), IsFuel(), and IsKindling().
CanReleaseCargo()
override bool CanReleaseCargo (EntityAI cargo) inline private
Definition at line 329 of file BarrelHoles_ColorBase.c.
References IsOpen().
CanRemoveFromCargo() [1/4]
override bool CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 298 of file BarrelHoles_ColorBase.c.
CanRemoveFromCargo() [2/4]
override bool CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 401 of file Fireplace.c.
CanRemoveFromCargo() [3/4]
override bool CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 293 of file FireplaceIndoor.c.
CanRemoveFromCargo() [4/4]
override bool CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 281 of file OvenIndoor.c.
CanRemoveFromHands() [1/2]
override bool CanRemoveFromHands (EntityAI player) inline private
Definition at line 310 of file FireplaceIndoor.c.
CanRemoveFromHands() [2/2]
override bool CanRemoveFromHands (EntityAI player) inline private
Definition at line 292 of file OvenIndoor.c.
CanShowSmoke() [1/2]
override bool CanShowSmoke () inline private
Definition at line 463 of file BarrelHoles_ColorBase.c.
References IsOpen().
Referenced by RefreshFireParticlesAndSounds().
CanShowSmoke() [2/2]
override bool CanShowSmoke () inline private
Definition at line 475 of file Fireplace.c.
References IsOven().
Close()
override void Close () inline private
Definition at line 412 of file BarrelHoles_ColorBase.c.
References m_RoofAbove, SetTakeable(), and SoundSynchRemote().
CloseLoad()
void CloseLoad () inline private
Definition at line 422 of file BarrelHoles_ColorBase.c.
References m_RoofAbove, and SetTakeable().
ContactEvent()
void ContactEvent (IEntity other, vector position) inline private
Definition at line 34 of file Fireplace.c.
References dBodyIsActive(), and GetGame().
Referenced by EOnContact(), and EOnTouch().
DestroyClutterCutter() [1/2]
void DestroyClutterCutter (Object clutter_cutter) inline private
Definition at line 526 of file BarrelHoles_ColorBase.c.
References GetGame(), and CGame::ObjectDelete().
DestroyClutterCutter() [2/2]
void DestroyClutterCutter (Object clutter_cutter) inline private
Definition at line 481 of file Fireplace.c.
References GetGame(), and CGame::ObjectDelete().
EEItemAttached() [1/4]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 164 of file BarrelHoles_ColorBase.c.
References AddToFireConsumables(), GetGame(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, and RefreshFireplaceVisuals().
EEItemAttached() [2/4]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 181 of file Fireplace.c.
References AddToFireConsumables(), ANIMATION_CAULDRON_HANDLE, ANIMATION_COOKWARE_HANDLE, ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, GetGame(), IsFuel(), IsKindling(), IsOven(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), and SetCookingEquipment().
EEItemAttached() [3/4]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 160 of file FireplaceIndoor.c.
References AddToFireConsumables(), GetGame(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, and RefreshFireplaceVisuals().
EEItemAttached() [4/4]
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 176 of file OvenIndoor.c.
References AddToFireConsumables(), GetGame(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, and RefreshFireplaceVisuals().
EEItemDetached() [1/4]
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 231 of file BarrelHoles_ColorBase.c.
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ClearCookingEquipment(), GetFireConsumableByItem(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), and RemoveFromFireConsumables().
EEItemDetached() [2/4]
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 268 of file Fireplace.c.
References ANIMATION_CAULDRON_HANDLE, ANIMATION_COOKWARE_HANDLE, ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ClearCookingEquipment(), GetFireConsumableByItem(), GetGame(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), and RemoveFromFireConsumables().
EEItemDetached() [3/4]
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 221 of file FireplaceIndoor.c.
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ClearCookingEquipment(), GetFireConsumableByItem(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), and RemoveFromFireConsumables().
EEItemDetached() [4/4]
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 221 of file OvenIndoor.c.
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ClearCookingEquipment(), GetFireConsumableByItem(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), and RemoveFromFireConsumables().
EOnContact()
override void EOnContact (IEntity other, Contact extra) inline private
Definition at line 29 of file Fireplace.c.
References ContactEvent(), and Contact::Position.
EOnTouch()
override void EOnTouch (IEntity other, int extra) inline private
Definition at line 24 of file Fireplace.c.
References ContactEvent(), and GetPosition.
Fireplace()
void Fireplace () inline private
Definition at line 5 of file Fireplace.c.
References ParticleList::CAMP_FIRE_END, ParticleList::CAMP_FIRE_START, ParticleList::CAMP_NORMAL_FIRE, ParticleList::CAMP_NORMAL_SMOKE, ParticleList::CAMP_SMALL_FIRE, ParticleList::CAMP_SMALL_SMOKE, ParticleList::CAMP_STEAM_2END, PARTICLE_FIRE_END, PARTICLE_FIRE_START, PARTICLE_NORMAL_FIRE, PARTICLE_NORMAL_SMOKE, PARTICLE_SMALL_FIRE, PARTICLE_SMALL_SMOKE, and PARTICLE_STEAM_END.
FireplaceIndoor()
void FireplaceIndoor () inline private
Definition at line 13 of file FireplaceIndoor.c.
References ParticleList::HOUSE_FIRE_END, ParticleList::HOUSE_FIRE_START, ParticleList::HOUSE_FIRE_STEAM_2END, ParticleList::HOUSE_NORMAL_FIRE, ParticleList::HOUSE_NORMAL_SMOKE, ParticleList::HOUSE_SMALL_FIRE, ParticleList::HOUSE_SMALL_SMOKE, m_LightDistance, m_RoofAbove, PARTICLE_FIRE_END, PARTICLE_FIRE_START, PARTICLE_NORMAL_FIRE, PARTICLE_NORMAL_SMOKE, PARTICLE_SMALL_FIRE, PARTICLE_SMALL_SMOKE, and PARTICLE_STEAM_END.
GetDamageSystemVersionChange()
override int GetDamageSystemVersionChange () inline private
Definition at line 32 of file BarrelHoles_ColorBase.c.
GetFirePointIndex() [1/2]
static int GetFirePointIndex (string action_selection) inline static private
Definition at line 88 of file FireplaceIndoor.c.
References string::Length(), string::Substring(), and string::ToInt().
GetFirePointIndex() [2/2]
static int GetFirePointIndex (string action_selection) inline static private
Definition at line 88 of file OvenIndoor.c.
References string::Length(), string::Substring(), and string::ToInt().
GetInvulnerabilityTypeString()
override string GetInvulnerabilityTypeString () inline private
Definition at line 37 of file BarrelHoles_ColorBase.c.
GetPlaceSoundset() [1/2]
override string GetPlaceSoundset () inline private
Definition at line 552 of file BarrelHoles_ColorBase.c.
GetPlaceSoundset() [2/2]
override string GetPlaceSoundset () inline private
Definition at line 758 of file Fireplace.c.
GetSmokeEffectPosition() [1/2]
override protected vector GetSmokeEffectPosition () inline private
Definition at line 135 of file FireplaceIndoor.c.
References Vector().
Referenced by ParticleNormalSmokeStart(), ParticleNormalSmokeStart(), ParticleSmallSmokeStart(), and ParticleSmallSmokeStart().
GetSmokeEffectPosition() [2/2]
override protected vector GetSmokeEffectPosition () inline private
Definition at line 135 of file OvenIndoor.c.
References Vector().
HasFlammableMaterial() [1/4]
override bool HasFlammableMaterial () inline private
Definition at line 469 of file BarrelHoles_ColorBase.c.
HasFlammableMaterial() [2/4]
override bool HasFlammableMaterial () inline private
Definition at line 575 of file Fireplace.c.
HasFlammableMaterial() [3/4]
override bool HasFlammableMaterial () inline private
Definition at line 316 of file FireplaceIndoor.c.
HasFlammableMaterial() [4/4]
override bool HasFlammableMaterial () inline private
Definition at line 298 of file OvenIndoor.c.
HeightStartCheckOverride()
override float HeightStartCheckOverride () inline private
Definition at line 469 of file Fireplace.c.
IgniteEntityAsFireplace()
static Fireplace IgniteEntityAsFireplace (notnull EntityAI entity, notnull EntityAI fire_source) inline static private
Definition at line 702 of file Fireplace.c.
References ECE_PLACE_ON_SURFACE, and GetGame().
IsBarrelWithHoles()
override bool IsBarrelWithHoles () inline private
Definition at line 94 of file BarrelHoles_ColorBase.c.
Referenced by GetSteamPosition(), RefreshFireplaceVisuals(), and StartHeating().
IsBaseFireplace()
override bool IsBaseFireplace () inline private
Definition at line 19 of file Fireplace.c.
Referenced by ActionCondition(), ActionCookOnStick::ActionCondition(), ActionIgniteFireplaceByAir::ActionCondition(), GetSteamPosition(), OnVariablesSynchronized(), and StartHeating().
IsFireplaceIndoor()
override bool IsFireplaceIndoor () inline private
Definition at line 155 of file FireplaceIndoor.c.
Referenced by ActionCookOnStick::ActionCondition(), ActionIgniteFireplaceByAir::ActionCondition(), GetSteamPosition(), RefreshFireplaceVisuals(), StartFire(), StartHeating(), and StopFire().
IsIgnited() [1/4]
override bool IsIgnited () inline private
Definition at line 494 of file BarrelHoles_ColorBase.c.
References IsBurning().
IsIgnited() [2/4]
override bool IsIgnited () inline private
Definition at line 590 of file Fireplace.c.
References IsBurning().
IsIgnited() [3/4]
override bool IsIgnited () inline private
Definition at line 341 of file FireplaceIndoor.c.
References IsBurning().
IsIgnited() [4/4]
override bool IsIgnited () inline private
Definition at line 323 of file OvenIndoor.c.
References IsBurning().
IsIndoorOven()
override bool IsIndoorOven () inline private
Definition at line 155 of file OvenIndoor.c.
Referenced by GetSteamPosition(), and RefreshFireplaceVisuals().
IsOpen()
override bool IsOpen () inline private
Definition at line 432 of file BarrelHoles_ColorBase.c.
IsPrepareToDelete() [1/2]
override bool IsPrepareToDelete () inline private
Definition at line 226 of file BarrelHoles_ColorBase.c.
IsPrepareToDelete() [2/2]
override bool IsPrepareToDelete () inline private
Definition at line 379 of file Fireplace.c.
References HasAshes(), and IsBurning().
IsThisIgnitionSuccessful() [1/4]
override bool IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 531 of file BarrelHoles_ColorBase.c.
References HasAnyKindling(), IsOnWaterSurface(), and IsOpen().
IsThisIgnitionSuccessful() [2/4]
override bool IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 636 of file Fireplace.c.
References GetGame(), GetIgniteFailure(), HasAnyKindling(), IsCeilingHighEnoughForSmoke(), IsOnInteriorSurface(), IsOnWaterSurface(), IsOven(), IsRainingAbove(), IsWet(), IsWindy(), CGame::RPCSingleParam(), and SetIgniteFailure().
IsThisIgnitionSuccessful() [3/4]
override bool IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 356 of file FireplaceIndoor.c.
References GetGame(), GetIgniteFailure(), HasAnyKindling(), IsWet(), CGame::RPCSingleParam(), and SetIgniteFailure().
IsThisIgnitionSuccessful() [4/4]
override bool IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 338 of file OvenIndoor.c.
References HasAnyKindling(), and IsWet().
OnBeforeTryDelete()
override void OnBeforeTryDelete () inline private
Definition at line 373 of file Fireplace.c.
References m_HalfExtents.
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 568 of file BarrelHoles_ColorBase.c.
OnIgnitedTarget() [1/4]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 499 of file BarrelHoles_ColorBase.c.
OnIgnitedTarget() [2/4]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 595 of file Fireplace.c.
OnIgnitedTarget() [3/4]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 346 of file FireplaceIndoor.c.
OnIgnitedTarget() [4/4]
override void OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 328 of file OvenIndoor.c.
OnIgnitedThis() [1/4]
override void OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 503 of file BarrelHoles_ColorBase.c.
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, CGame::GetCallQueue(), GetGame(), GetOrientation(), GetPosition, OBJECT_CLUTTER_CUTTER, and StartFire().
Referenced by OnDebugButtonPressServer().
OnIgnitedThis() [2/4]
override void OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 599 of file Fireplace.c.
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, CGame::GetCallQueue(), GetGame(), GetOrientation(), GetPosition, OBJECT_CLUTTER_CUTTER, SyncEvents::SendPlayerIgnatedFireplace(), and StartFire().
OnIgnitedThis() [3/4]
override void OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 350 of file FireplaceIndoor.c.
References StartFire().
OnIgnitedThis() [4/4]
override void OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 332 of file OvenIndoor.c.
References StartFire().
OnStoreLoad() [1/4]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 71 of file BarrelHoles_ColorBase.c.
References Serializer::Read().
OnStoreLoad() [2/4]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 533 of file Fireplace.c.
References m_HasStoneCircle, m_IsOven, and Serializer::Read().
OnStoreLoad() [3/4]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 50 of file FireplaceIndoor.c.
References m_FirePointIndex, and Serializer::Read().
OnStoreLoad() [4/4]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 50 of file OvenIndoor.c.
References m_FirePointIndex, and Serializer::Read().
OnStoreSave() [1/4]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 64 of file BarrelHoles_ColorBase.c.
References Serializer::Write().
OnStoreSave() [2/4]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 519 of file Fireplace.c.
References GetGame(), m_HasStoneCircle, m_IsOven, and Serializer::Write().
OnStoreSave() [3/4]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 37 of file FireplaceIndoor.c.
References m_FirePointIndex, and Serializer::Write().
OnStoreSave() [4/4]
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 37 of file OvenIndoor.c.
References m_FirePointIndex, and Serializer::Write().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Definition at line 99 of file BarrelHoles_ColorBase.c.
References IsBeingPlaced(), IsOpen(), IsSoundSynchRemote(), m_Initialized, and RefreshFireParticlesAndSounds().
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 42 of file BarrelHoles_ColorBase.c.
References Open().
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 49 of file BarrelHoles_ColorBase.c.
References Close().
Open()
override void Open () inline private
Definition at line 391 of file BarrelHoles_ColorBase.c.
References m_RoofAbove, SetTakeable(), and SoundSynchRemote().
OpenLoad()
void OpenLoad () inline private
Definition at line 402 of file BarrelHoles_ColorBase.c.
References m_RoofAbove, and SetTakeable().
OvenIndoor()
void OvenIndoor () inline private
Definition at line 13 of file OvenIndoor.c.
References ParticleList::BARREL_FIRE_STEAM_2END, ParticleList::HOUSE_NORMAL_SMOKE, ParticleList::HOUSE_SMALL_SMOKE, m_LightDistance, m_RoofAbove, ParticleList::OVEN_FIRE_END, ParticleList::OVEN_FIRE_START, ParticleList::OVEN_NORMAL_FIRE, ParticleList::OVEN_SMALL_FIRE, PARTICLE_FIRE_END, PARTICLE_FIRE_START, PARTICLE_NORMAL_FIRE, PARTICLE_NORMAL_SMOKE, PARTICLE_SMALL_FIRE, PARTICLE_SMALL_SMOKE, and PARTICLE_STEAM_END.
ParticleNormalSmokeStart() [1/2]
override void ParticleNormalSmokeStart () inline private
Definition at line 147 of file FireplaceIndoor.c.
References GetSmokeEffectPosition(), m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleNormalSmokeStart() [2/2]
override void ParticleNormalSmokeStart () inline private
Definition at line 147 of file OvenIndoor.c.
References GetSmokeEffectPosition(), m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, and PlayParticle().
ParticleSmallSmokeStart() [1/2]
override void ParticleSmallSmokeStart () inline private
Definition at line 141 of file FireplaceIndoor.c.
References GetSmokeEffectPosition(), m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSmallSmokeStart() [2/2]
override void ParticleSmallSmokeStart () inline private
Definition at line 141 of file OvenIndoor.c.
References GetSmokeEffectPosition(), m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, and PlayParticle().
RefreshFireplacePhysics()
override void RefreshFireplacePhysics () inline private
Definition at line 513 of file Fireplace.c.
References RefreshPhysics().
Referenced by OnItemLocationChanged(), and RefreshFireplaceVisuals().
RefreshPhysics()
override void RefreshPhysics () inline private
Definition at line 486 of file Fireplace.c.
References AddProxyPhysics(), ANIMATION_OVEN, ANIMATION_TRIPOD, ATTACHMENT_TRIPOD, IsItemTypeAttached(), IsOven(), and RemoveProxyPhysics().
Referenced by RefreshFireplacePhysics().
SetActions() [1/2]
override void SetActions () inline private
Definition at line 557 of file BarrelHoles_ColorBase.c.
References AddAction().
SetActions() [2/2]
override void SetActions () inline private
Definition at line 763 of file Fireplace.c.
References ActionBuildOven(), ActionBuildStoneCircle(), ActionDismantleOven(), ActionDismantleStoneCircle(), and AddAction().
SetCookingEquipment()
override void SetCookingEquipment (ItemBase equipment) inline private
Definition at line 354 of file Fireplace.c.
Referenced by ClearCookingEquipment(), EEItemAttached(), and EEItemAttached().
SetFirePointIndex() [1/2]
void SetFirePointIndex (int fire_point_index) inline private
Definition at line 94 of file FireplaceIndoor.c.
References m_FirePointIndex.
SetFirePointIndex() [2/2]
void SetFirePointIndex (int fire_point_index) inline private
Definition at line 94 of file OvenIndoor.c.
References m_FirePointIndex.
SetSmokePointPosition() [1/2]
void SetSmokePointPosition (vector smoke_point_pos) inline private
Definition at line 125 of file FireplaceIndoor.c.
SetSmokePointPosition() [2/2]
void SetSmokePointPosition (vector smoke_point_pos) inline private
Definition at line 125 of file OvenIndoor.c.
SoundBarrelClosePlay()
void SoundBarrelClosePlay () inline private
Definition at line 520 of file BarrelHoles_ColorBase.c.
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
SoundBarrelOpenPlay()
void SoundBarrelOpenPlay () inline private
Definition at line 514 of file BarrelHoles_ColorBase.c.
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
UpdateVisualState()
protected void UpdateVisualState () inline private
Definition at line 437 of file BarrelHoles_ColorBase.c.
References IsOpen().
Field Documentation
ANIMATION_CLOSED
const string ANIMATION_CLOSED = "LidOn" private
Definition at line 5 of file BarrelHoles_ColorBase.c.
ANIMATION_OPENED
const string ANIMATION_OPENED = "LidOff" private
Definition at line 4 of file BarrelHoles_ColorBase.c.
FIREPOINT_ACTION_SELECTION
const string FIREPOINT_ACTION_SELECTION = "fireplace_action" static private
Definition at line 8 of file FireplaceIndoor.c.
FIREPOINT_FIRE_POSITION
const string FIREPOINT_FIRE_POSITION = "fireplace_point" static private
Definition at line 9 of file FireplaceIndoor.c.
FIREPOINT_PLACE_ROT
const string FIREPOINT_PLACE_ROT = "fireplace_rot" static private
Definition at line 10 of file FireplaceIndoor.c.
FIREPOINT_SMOKE_POSITION
const string FIREPOINT_SMOKE_POSITION = "fireplace_smoke" static private
Definition at line 11 of file FireplaceIndoor.c.
m_ContactEventProcessing
bool m_ContactEventProcessing private
Definition at line 3 of file Fireplace.c.
m_FirePointIndex
protected int m_FirePointIndex = 1 private
Definition at line 6 of file FireplaceIndoor.c.
m_IsOpenedClient
protected bool m_IsOpenedClient = false private
Definition at line 7 of file BarrelHoles_ColorBase.c.
m_Openable
protected ref OpenableBehaviour m_Openable private
Definition at line 9 of file BarrelHoles_ColorBase.c.
m_SmokePosX
protected float m_SmokePosX private
Definition at line 3 of file FireplaceIndoor.c.
m_SmokePosY
protected float m_SmokePosY private
Definition at line 4 of file FireplaceIndoor.c.
m_SmokePosZ
protected float m_SmokePosZ private
Definition at line 5 of file FireplaceIndoor.c.
OVENPOINT_ACTION_SELECTION
const string OVENPOINT_ACTION_SELECTION = "oven_action" static private
Definition at line 8 of file OvenIndoor.c.
OVENPOINT_FIRE_POSITION
const string OVENPOINT_FIRE_POSITION = "oven_point" static private
Definition at line 9 of file OvenIndoor.c.
OVENPOINT_PLACE_ROT
const string OVENPOINT_PLACE_ROT = "oven_rot" static private
Definition at line 10 of file OvenIndoor.c.
OVENPOINT_SMOKE_POSITION
const string OVENPOINT_SMOKE_POSITION = "oven_smoke" static private
Definition at line 11 of file OvenIndoor.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/FireplaceBase/BarrelHoles_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/FireplaceBase/Fireplace.c
P:/scripts/4_World/Entities/ItemBase/FireplaceBase/FireplaceIndoor.c
P:/scripts/4_World/Entities/ItemBase/FireplaceBase/OvenIndoor.c