DayZ Scripts: BleedChanceData Class Reference
BleedChanceData Class Reference
Static data of bleeding chance probabilities; currently used for melee only.
Static Private Member Functions
static void InitBleedChanceData ()
static void InitMeleeChanceMap ()
static void InitInfectedChanceMap ()
static void Cleanup ()
static bool CalculateBleedChance (string damageType, float bloodDamage, float bleedThreshold, out float bleedChance)
returns 'false' when damageType is unhandled
Static Private Attributes
static const float BLOOD_HITPOINTS_UNIVERSAL = 100.0
static ref map< string, ref BleedChanceMaxMap > m_DamageTypeMap
Detailed Description
Static data of bleeding chance probabilities; currently used for melee only.
Member Function Documentation
CalculateBleedChance()
static bool CalculateBleedChance (string damageType, float bloodDamage, float bleedThreshold, out float bleedChance) inline static private
returns 'false' when damageType is unhandled
References Debug::BleedingChancesLog(), BLOOD_HITPOINTS_UNIVERSAL, Math::Ceil(), Math::Floor(), Math::InverseLerp(), LogManager::IsBleedingChancesLogEnable(), Math::Lerp(), m_DamageTypeMap, Math::Max(), Math::Min(), and float::ToString().
Referenced by BleedingSourcesManagerBase::ProcessHit().
Cleanup()
static void Cleanup () inline static private
References m_DamageTypeMap.
Referenced by CGame::~DayZGame().
InitBleedChanceData()
static void InitBleedChanceData () inline static private
References InitInfectedChanceMap(), InitMeleeChanceMap(), and m_DamageTypeMap.
Referenced by CGame::DayZGame().
InitInfectedChanceMap()
static void InitInfectedChanceMap () inline static private
References BLOOD_HITPOINTS_UNIVERSAL, ErrorEx, and m_DamageTypeMap.
Referenced by InitBleedChanceData().
InitMeleeChanceMap()
static void InitMeleeChanceMap () inline static private
References BLOOD_HITPOINTS_UNIVERSAL, ErrorEx, and m_DamageTypeMap.
Referenced by InitBleedChanceData().
Field Documentation
BLOOD_HITPOINTS_UNIVERSAL
const float BLOOD_HITPOINTS_UNIVERSAL = 100.0 static private
Referenced by CalculateBleedChance(), InitInfectedChanceMap(), and InitMeleeChanceMap().
m_DamageTypeMap
ref map<string,ref BleedChanceMaxMap> m_DamageTypeMap static private
Referenced by CalculateBleedChance(), Cleanup(), InitBleedChanceData(), InitInfectedChanceMap(), and InitMeleeChanceMap().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/BleedChanceData.c