DayZ Scripts: StaticConstructionMethods Class Reference
StaticConstructionMethods Class Reference
Static Private Member Functions
static void SpawnConstructionMaterialPiles (notnull EntityAI entity, Man player, string cfg_path, string main_part_name, string damagezone_name="", bool is_base=false)
spawns material from any construction; 'player' parameter optional
Member Function Documentation
SpawnConstructionMaterialPiles()
static void SpawnConstructionMaterialPiles (notnull EntityAI entity, Man player, string cfg_path, string main_part_name, string damagezone_name = "", bool is_base = false) inline static private
spawns material from any construction; 'player' parameter optional
References bsbDebugPrint(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetInt(), CGame::ConfigGetText(), Construction(), Math::Floor(), GetGame(), InventoryLocation::GetItem(), InventoryLocation::GetSlot(), LogManager::IsBaseBuildingLogEnable(), Math::Max(), CGame::ObjectModelToWorld(), and GameInventory::SetGroundPosByOwner().
Referenced by TentBase::Deconstruct(), and ReceiveMaterialsServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/BaseBuilding/Construction.c