DayZ Scripts: P:/scripts/4_World/Classes/SoundEvents/InfectedSoundEvents/Events/MindStates.c File Reference
MindStates.c File Reference
Data Structures
class InfectedSoundEventBase
class MindStateSoundEventBase
Functions
class MindStateSoundEventBase extends InfectedSoundEventBase CalmIdleSoundEvent ()
override bool CanPlay ()
class CalmMoveSoundEvent extends MindStateSoundEventBase DisturbedIdleSoundEvent ()
void CalmMoveSoundEvent ()
class ChaseMoveSoundEvent extends MindStateSoundEventBase AlertedIdleSoundEvent ()
void ChaseMoveSoundEvent ()
Function Documentation
AlertedIdleSoundEvent()
class ChaseMoveSoundEvent extends MindStateSoundEventBase AlertedIdleSoundEvent ()
Definition at line 43 of file MindStates.c.
Referenced by InfectedSoundEventHandler().
CalmIdleSoundEvent()
class MindStateSoundEventBase extends InfectedSoundEventBase CalmIdleSoundEvent ()
Definition at line 1 of file MindStates.c.
Referenced by InfectedSoundEventHandler().
CalmMoveSoundEvent()
void CalmMoveSoundEvent ()
Definition at line 36 of file MindStates.c.
References m_ID, m_SoundSetNameRoot, and m_Type.
Referenced by InfectedSoundEventHandler().
CanPlay()
override bool CanPlay ()
Definition at line 16 of file MindStates.c.
References m_ID, m_SoundSetNameRoot, and m_Type.
ChaseMoveSoundEvent()
void ChaseMoveSoundEvent ()
Definition at line 56 of file MindStates.c.
References m_ID, m_SoundSetNameRoot, and m_Type.
Referenced by InfectedSoundEventHandler().
DisturbedIdleSoundEvent()
class CalmMoveSoundEvent extends MindStateSoundEventBase DisturbedIdleSoundEvent ()
Definition at line 23 of file MindStates.c.
Referenced by InfectedSoundEventHandler().