DayZ Scripts: PaintItem Class Reference
PaintItem Class Reference
Static Private Member Functions
static void Paint (ItemBase item_tool, ItemBase item_target, string base_name, PlayerBase player, float specialty_weight=0)
WIll open the 'item_target' by spawning a new entity and transferring item variables to the new one.
static bool CanPaintItem (ItemBase item_tool, ItemBase item_target)
static void SwitchItems (EntityAI old_item, string new_item, PlayerBase player)
Will switch the 'item' for a new game entity, the new entity's classname will be formed by adding the 'suffix' to the classname of the old 'item'.
Member Function Documentation
CanPaintItem()
static bool CanPaintItem (ItemBase item_tool, ItemBase item_target) inline static private
Referenced by RecipeBase::CanDo().
Paint()
static void Paint (ItemBase item_tool, ItemBase item_target, string base_name, PlayerBase player, float specialty_weight = 0) inline static private
WIll open the 'item_target' by spawning a new entity and transferring item variables to the new one.
References SwitchItems().
Referenced by RecipeBase::Do().
SwitchItems()
static void SwitchItems (EntityAI old_item, string new_item, PlayerBase player) inline static private
Will switch the 'item' for a new game entity, the new entity's classname will be formed by adding the 'suffix' to the classname of the old 'item'.
Referenced by Paint().
The documentation for this class was generated from the following file:
4_World/Static/PaintItem.c