DayZ Scripts: Transport Class Reference
Transport Class Reference
Base native class for all motorized wheeled vehicles.
Private Member Functions
protected override event GetOwnerStateType ()
protected override event GetMoveType ()
proto native float GetThrottle ()
Returns the actual throttle value in range <0, 1>.
proto native void SetThrottle (float value)
Sets the future throttle value.
proto native float GetSteering ()
Returns the actual steering value in range <-1, 1>.
proto native void SetSteering (float value)
Sets the future steering value.
proto native int GetGearCount ()
Returns the number of gears.
proto native int GetNeutralGear ()
Returns the index of the neutral gear.
proto native int GetGear ()
Returns the index of the future gear, -1 if there is no engine.
proto native int GetCurrentGear ()
Returns the index of the current gear, -1 if there is no engine.
proto native int GetClutch ()
Returns the value of how much the clutch is disengaged.
proto native void ShiftUp ()
Shifts the future gear up, triggering gearbox simulation.
proto native void ShiftTo (int gear)
Shifts the future gear to selected gear, triggering gearbox simulation.
proto native void ShiftDown ()
Shifts the future gear down, triggering gearbox simulation.
proto native bool HasEngine ()
Returns if there is an engine.
proto native float EngineGetRPMMin ()
Returns engine's min operating rpm.
proto native float EngineGetRPMIdle ()
Returns engine's idle rpm before engine stalls.
proto native float EngineGetRPMMax ()
Returns engine's max rpm before engine blows up.
proto native float EngineGetRPMRedline ()
Returns engine's maximal working rpm without damaging the engine.
proto native float EngineGetRPM ()
Returns engine's rpm value.
proto native bool EngineIsOn ()
Returns true when engine is running, false otherwise.
proto native void EngineStart ()
Starts the engine.
proto native void EngineStop ()
Stops the engine.
proto native vector PropellerGetPosition ()
Returns the propeller position in local space.
proto native float PropellerGetAngularVelocity ()
Returns the angular velocity of the propeller.
proto native float GetFluidCapacity (BoatFluid fluid)
proto native float GetFluidFraction (BoatFluid fluid)
proto native void Leak (BoatFluid fluid, float amount)
Removes from the specified fluid the specified amount.
proto native void LeakAll (BoatFluid fluid)
Removes all the specified fluid from vehicle.
proto native void Fill (BoatFluid fluid, float amount)
Adds to the specified fluid the specified amount.
void OnInput (float dt)
bool OnBeforeEngineStart ()
void OnEngineStart ()
void OnEngineStop ()
void OnGearChanged (int newGear, int oldGear)
void OnFluidChanged (BoatFluid fluid, float newValue, float oldValue)
float OnSound (BoatSoundCtrl ctrl, float oldValue)
proto native CarController GetController ()
DEPRECATED, left for backwards compatibility, the methods of this class are now directly accessible on Car itself.
proto native float GetSpeedometer ()
Returns the current speed of the vehicle in km/h.
float GetSpeedometerAbsolute ()
Returns the current speed of the vehicle in km/h. Value is absolute.
override bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight=0.5, float horizontalExtents=0.5, float playerHeight=1.7)
override Shape DebugFreeAreaAtDoor (int currentSeat, float maxAllowedObjHeight=0.5, float horizontalExtents=0.5, float playerHeight=1.7)
proto native float GetSteering ()
Returns the current steering value in range <-1, 1>.
proto native void SetSteering (float in, bool analog=false)
proto native float GetThrustTurbo ()
Returns the current thrust turbo modifier value in range <0, 1>.
proto native float GetThrustGentle ()
Returns the current thrust gentle modifier value in range <0, 1>.
proto native float GetThrust ()
Returns the current thrust value in range <0, 1>.
proto native void SetThrust (float in, float gentle=0, float turbo=0)
proto native float GetBrake ()
Returns the current brake value in range <0, 1>.
proto native void SetBrake (float in, float panic=0, bool gentle=false)
proto native float GetHandbrake ()
Returns the current handbrake value in range <0, 1>.
proto native void SetHandbrake (float in)
proto native void SetBrakesActivateWithoutDriver (bool activate=true)
proto native float GetClutch ()
Returns the current clutch value in range <0, 1>.
proto native void SetClutchState (bool in)
proto native int GetGear ()
Returns index of the current gear.
proto native void ShiftUp ()
proto native void ShiftTo (CarGear gear)
proto native void ShiftDown ()
proto native float GetFluidCapacity (CarFluid fluid)
proto native float GetFluidFraction (CarFluid fluid)
proto native void Leak (CarFluid fluid, float amount)
Removes from the specified fluid the specified amount.
proto native void LeakAll (CarFluid fluid)
Removes all the specified fluid from vehicle.
proto native void Fill (CarFluid fluid, float amount)
Adds to the specified fluid the specified amount.
void OnFluidChanged (CarFluid fluid, float newValue, float oldValue)
proto native float EngineGetRPMMin ()
Returns engine's min operating rpm.
proto native float EngineGetRPMIdle ()
Returns engine's idle rpm before engine stalls.
proto native float EngineGetRPMMax ()
Returns engine's max rpm before engine blows up.
proto native float EngineGetRPMRedline ()
Returns engine's maximal working rpm without damaging the engine.
proto native float EngineGetRPM ()
Returns engine's rpm value.
proto native bool EngineIsOn ()
Returns true when engine is running, false otherwise.
proto native void EngineStart ()
Starts the engine.
bool OnBeforeEngineStart ()
void OnEngineStart ()
Is called every time the engine starts.
proto native void EngineStop ()
Stops the engine.
void OnEngineStop ()
Is called every time the engine stops.
proto native vector GetEnginePos ()
Get actual position of engine (model space)
proto native void SetEnginePos (vector pos)
Override the position of engine (model space)
proto native int GetGearsCount ()
Returns total number of gears.
proto native CarGearboxType GearboxGetType ()
Returns gearbox type. See CarGearboxType enum for more info.
proto native CarAutomaticGearboxMode GearboxGetMode ()
Returns gearbox mode. This is useful when car has automatic gearbox.
void OnGearChanged (int newGear, int oldGear)
proto native bool WheelIsAnyLocked ()
Returns true if any of the wheels are locked in terms of its movement.
proto native float WheelGetAngularVelocity (int wheelIdx)
proto native bool WheelHasContact (int wheelIdx)
proto native vector WheelGetContactPosition (int wheelIdx)
proto native vector WheelGetContactNormal (int wheelIdx)
proto native vector WheelGetDirection (int wheelIdx)
proto native SurfaceInfo WheelGetSurface (int wheelIdx)
proto native CarWheelWaterState WheelGetWaterState (int wheelIdx)
proto native EntityAI WheelGetEntity (int wheelIdx)
proto native bool WheelIsLocked (int wheelIdx)
proto native int WheelCount ()
How many wheel can be attached to a car (hubs only)
proto native int WheelCountPresent ()
Number of actually attached wheels (hubs only)
void OnContact (string zoneName, vector localPos, IEntity other, Contact data)
float OnSound (CarSoundCtrl ctrl, float oldValue)
void OnInput (float dt)
void OnUpdate (float dt)
proto native void ForcePosition (vector pos)
proto native void ForceDirection (vector dir)
Detailed Description
Base native class for all motorized wheeled vehicles.
Base native class for helicopter.
Member Function Documentation
DebugFreeAreaAtDoor()
override Shape DebugFreeAreaAtDoor (int currentSeat, float maxAllowedObjHeight = 0.5, float horizontalExtents = 0.5, float playerHeight = 1.7) inline private
References ARGB(), Debug::DrawBox(), GetSpeedometerAbsolute(), IsAreaAtDoorFree(), and Shape.
EngineGetRPM() [1/2]
proto native float EngineGetRPM () private
Returns engine's rpm value.
EngineGetRPM() [2/2]
proto native float EngineGetRPM () private
Returns engine's rpm value.
EngineGetRPMIdle() [1/2]
proto native float EngineGetRPMIdle () private
Returns engine's idle rpm before engine stalls.
EngineGetRPMIdle() [2/2]
proto native float EngineGetRPMIdle () private
Returns engine's idle rpm before engine stalls.
EngineGetRPMMax() [1/2]
proto native float EngineGetRPMMax () private
Returns engine's max rpm before engine blows up.
EngineGetRPMMax() [2/2]
proto native float EngineGetRPMMax () private
Returns engine's max rpm before engine blows up.
EngineGetRPMMin() [1/2]
proto native float EngineGetRPMMin () private
Returns engine's min operating rpm.
EngineGetRPMMin() [2/2]
proto native float EngineGetRPMMin () private
Returns engine's min operating rpm.
EngineGetRPMRedline() [1/2]
proto native float EngineGetRPMRedline () private
Returns engine's maximal working rpm without damaging the engine.
EngineGetRPMRedline() [2/2]
proto native float EngineGetRPMRedline () private
Returns engine's maximal working rpm without damaging the engine.
EngineIsOn() [1/2]
proto native bool EngineIsOn () private
Returns true when engine is running, false otherwise.
EngineIsOn() [2/2]
proto native bool EngineIsOn () private
Returns true when engine is running, false otherwise.
EngineStart() [1/2]
proto native void EngineStart () private
Starts the engine.
Referenced by OnFinishProgress().
EngineStart() [2/2]
proto native void EngineStart () private
Starts the engine.
EngineStop() [1/2]
proto native void EngineStop () private
Stops the engine.
EngineStop() [2/2]
proto native void EngineStop () private
Stops the engine.
Fill() [1/2]
proto native void Fill (BoatFluid fluid, float amount) private
Adds to the specified fluid the specified amount.
Fill() [2/2]
proto native void Fill (CarFluid fluid, float amount) private
Adds to the specified fluid the specified amount.
ForceDirection()
proto native void ForceDirection (vector dir) private
ForcePosition()
proto native void ForcePosition (vector pos) private
GearboxGetMode()
proto native CarAutomaticGearboxMode GearboxGetMode () private
Returns gearbox mode. This is useful when car has automatic gearbox.
GearboxGetType()
proto native CarGearboxType GearboxGetType () private
Returns gearbox type. See CarGearboxType enum for more info.
GetBrake()
proto native float GetBrake () private
Returns the current brake value in range <0, 1>.
GetClutch() [1/2]
proto native int GetClutch () private
Returns the value of how much the clutch is disengaged.
GetClutch() [2/2]
proto native float GetClutch () private
Returns the current clutch value in range <0, 1>.
GetController()
proto native CarController GetController () private
DEPRECATED, left for backwards compatibility, the methods of this class are now directly accessible on Car itself.
GetCurrentGear()
proto native int GetCurrentGear () private
Returns the index of the current gear, -1 if there is no engine.
GetEnginePos()
proto native vector GetEnginePos () private
Get actual position of engine (model space)
GetFluidCapacity() [1/2]
proto native float GetFluidCapacity (BoatFluid fluid) private
Returns tank capacity for the specified vehicle's fluid.
Parameters
fluid the specified fluid type
GetFluidCapacity() [2/2]
proto native float GetFluidCapacity (CarFluid fluid) private
Returns tank capacity for the specified vehicle's fluid.
Parameters
fluid the specified fluid type
GetFluidFraction() [1/2]
proto native float GetFluidFraction (BoatFluid fluid) private
Returns fraction value (in range <0, 1>) of the current state of the specified vehicle's fluid.
Parameters
[in] fluid the specified fluid type
GetFluidFraction() [2/2]
proto native float GetFluidFraction (CarFluid fluid) private
Returns fraction value (in range <0, 1>) of the current state of the specified vehicle's fluid.
Parameters
[in] fluid the specified fluid type
GetGear() [1/2]
proto native int GetGear () private
Returns the index of the future gear, -1 if there is no engine.
GetGear() [2/2]
proto native int GetGear () private
Returns index of the current gear.
GetGearCount()
proto native int GetGearCount () private
Returns the number of gears.
GetGearsCount()
proto native int GetGearsCount () private
Returns total number of gears.
GetHandbrake()
proto native float GetHandbrake () private
Returns the current handbrake value in range <0, 1>.
GetMoveType()
protected override event GetMoveType () inline private
GetNeutralGear()
proto native int GetNeutralGear () private
Returns the index of the neutral gear.
GetOwnerStateType()
protected override event GetOwnerStateType () inline private
GetSpeedometer()
proto native float GetSpeedometer () private
Returns the current speed of the vehicle in km/h.
Referenced by GetSpeedometerAbsolute().
GetSpeedometerAbsolute()
float GetSpeedometerAbsolute () inline private
Returns the current speed of the vehicle in km/h. Value is absolute.
References Math::AbsFloat(), and GetSpeedometer().
Referenced by ActionStopEngine::ActionCondition(), DebugFreeAreaAtDoor(), and IsAreaAtDoorFree().
GetSteering() [1/2]
proto native float GetSteering () private
Returns the actual steering value in range <-1, 1>.
GetSteering() [2/2]
proto native float GetSteering () private
Returns the current steering value in range <-1, 1>.
GetThrottle()
proto native float GetThrottle () private
Returns the actual throttle value in range <0, 1>.
GetThrust()
proto native float GetThrust () private
Returns the current thrust value in range <0, 1>.
GetThrustGentle()
proto native float GetThrustGentle () private
Returns the current thrust gentle modifier value in range <0, 1>.
GetThrustTurbo()
proto native float GetThrustTurbo () private
Returns the current thrust turbo modifier value in range <0, 1>.
HasEngine()
proto native bool HasEngine () private
Returns if there is an engine.
IsAreaAtDoorFree()
override bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight = 0.5, float horizontalExtents = 0.5, float playerHeight = 1.7) inline private
References GetSpeedometerAbsolute(), and IsAreaAtDoorFree().
Referenced by ActionGetInTransport::ActionCondition(), ActionGetOutTransport::ActionCondition(), DebugFreeAreaAtDoor(), EntityAI::DebugFreeAreaAtDoor(), IsAreaAtDoorFree(), and EntityAI::IsAreaAtDoorFree().
Leak() [1/2]
proto native void Leak (BoatFluid fluid, float amount) private
Removes from the specified fluid the specified amount.
Leak() [2/2]
proto native void Leak (CarFluid fluid, float amount) private
Removes from the specified fluid the specified amount.
LeakAll() [1/2]
proto native void LeakAll (BoatFluid fluid) private
Removes all the specified fluid from vehicle.
LeakAll() [2/2]
proto native void LeakAll (CarFluid fluid) private
Removes all the specified fluid from vehicle.
OnBeforeEngineStart() [1/2]
bool OnBeforeEngineStart () inline private
Is called every time the game wants to start the engine.
Returns
true if the engine can start, false otherwise.
OnBeforeEngineStart() [2/2]
bool OnBeforeEngineStart () inline private
Is called every time the game wants to start the engine.
Returns
true if the engine can start, false otherwise.
OnContact()
void OnContact (string zoneName, vector localPos, IEntity other, Contact data) inline private
Is called every time when vehicle collides with other object.
Parameters
[in] zoneName configured vehicle's zone that was hit
[in] localPos position where the vehicle was hit in vehicle's space
[in] other object with which the vehicle is colliding
[in] data contact properties
OnEngineStart() [1/2]
void OnEngineStart () inline private
Is called every time the engine starts.
OnEngineStart() [2/2]
void OnEngineStart () inline private
Is called every time the engine starts.
OnEngineStop() [1/2]
void OnEngineStop () inline private
Is called every time the engine stops.
OnEngineStop() [2/2]
void OnEngineStop () inline private
Is called every time the engine stops.
OnFluidChanged() [1/2]
void OnFluidChanged (BoatFluid fluid, float newValue, float oldValue) inline private
Is called every time when the specified vehicle's fluid level changes. This callback is called on owner only.
Parameters
[in] fluid fluid identifier,
See also
BoatFluid
Parameters
[in] newValue new fluid level
[in] oldValue previous fluid level before change
OnFluidChanged() [2/2]
void OnFluidChanged (CarFluid fluid, float newValue, float oldValue) inline private
Is called every time when the specified vehicle's fluid level changes eg. when vehicle is consuming fuel.
Parameters
[in] fluid fluid identifier,
See also
CarFluid
Parameters
[in] newValue new fluid level
[in] oldValue previous fluid level before change
OnGearChanged() [1/2]
void OnGearChanged (int newGear, int oldGear) inline private
Is called every time when the simulation changed gear.
Parameters
[in] newGear new gear level
[in] oldGear previous gear level before gear shift
OnGearChanged() [2/2]
void OnGearChanged (int newGear, int oldGear) inline private
Is called every time when the simulation changed gear.
Parameters
[in] newGear new gear level
[in] oldGear previous gear level before gear shift
OnInput() [1/2]
void OnInput (float dt) inline private
Called every physics simulation step before inputs are applied.
OnInput() [2/2]
void OnInput (float dt) inline private
Is called after every input simulation step.
Note that the player character and other systems can always change the internal state. It is highly recommended to store state of custom inputs elsewhere and call Setters here.
Parameters
[in] dt frame time in seconds
OnSound() [1/2]
float OnSound (BoatSoundCtrl ctrl, float oldValue) inline private
Is called every sound simulation step. In this callback, user can modify behaviour of sound controllers.
Parameters
[in] ctrl sound controller identifier,
See also
BoatSoundCtrl
Parameters
[in] oldValue already computed value by the game code
Returns
new value of the specified sound controller.
OnSound() [2/2]
float OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Is called every sound simulation step. In this callback, user can modify behaviour of sound controllers.
Parameters
[in] ctrl sound controller identifier,
See also
CarSoundCtrl
Parameters
[in] oldValue already computed value by the game code
Returns
new value of the specified sound controller.
OnUpdate()
void OnUpdate (float dt) inline private
Is called every game frame.
Parameters
[in] dt frame time in seconds
PropellerGetAngularVelocity()
proto native float PropellerGetAngularVelocity () private
Returns the angular velocity of the propeller.
PropellerGetPosition()
proto native vector PropellerGetPosition () private
Returns the propeller position in local space.
SetBrake()
proto native void SetBrake (float in, float panic = 0, bool gentle = false) private
Sets the brake value.
Parameters
in should be in range <0, 1>
panic should be in range <0, 1>
SetBrakesActivateWithoutDriver()
proto native void SetBrakesActivateWithoutDriver (bool activate = true) private
Sets if brakes should activate without a driver present
SetClutchState()
proto native void SetClutchState (bool in) private
Sets the clutch state.
SetEnginePos()
proto native void SetEnginePos (vector pos) private
Override the position of engine (model space)
SetHandbrake()
proto native void SetHandbrake (float in) private
Sets the handbrake value.
Parameters
in should be in range <0, 1>
SetSteering() [1/2]
proto native void SetSteering (float in, bool analog = false) private
Sets the steering value.
Parameters
in should be in range <-1, 1>
analog indicates if the input value was taken from analog controller
SetSteering() [2/2]
proto native void SetSteering (float value) private
Sets the future steering value.
SetThrottle()
proto native void SetThrottle (float value) private
Sets the future throttle value.
SetThrust()
proto native void SetThrust (float in, float gentle = 0, float turbo = 0) private
Sets the thrust value.
Parameters
in should be in range <0, 1>
gentle should be in range <0, 1>, thrust modifier
turbo should be in range <0, 1>, thrust modifier
ShiftDown() [1/2]
proto native void ShiftDown () private
Shifts the future gear down, triggering gearbox simulation.
ShiftDown() [2/2]
proto native void ShiftDown () private
ShiftTo() [1/2]
proto native void ShiftTo (CarGear gear) private
ShiftTo() [2/2]
proto native void ShiftTo (int gear) private
Shifts the future gear to selected gear, triggering gearbox simulation.
ShiftUp() [1/2]
proto native void ShiftUp () private
Shifts the future gear up, triggering gearbox simulation.
ShiftUp() [2/2]
proto native void ShiftUp () private
WheelCount()
proto native int WheelCount () private
How many wheel can be attached to a car (hubs only)
WheelCountPresent()
proto native int WheelCountPresent () private
Number of actually attached wheels (hubs only)
WheelGetAngularVelocity()
proto native float WheelGetAngularVelocity (int wheelIdx) private
Returns the raw angular velocity of the wheel, unstable value
Parameters
[in] wheelIdx index of the wheel, they are counted from left-front to rear-right
WheelGetContactNormal()
proto native vector WheelGetContactNormal (int wheelIdx) private
Returns the normal of contact in world space, only valid if there was an actual contact
Parameters
[in] wheelIdx index of the wheel, they are counted from left-front to rear-right
WheelGetContactPosition()
proto native vector WheelGetContactPosition (int wheelIdx) private
Returns the position of contact in world space, only valid if there was an actual contact
Parameters
[in] wheelIdx index of the wheel, they are counted from left-front to rear-right
WheelGetDirection()
proto native vector WheelGetDirection (int wheelIdx) private
Returns the direction pointing forwards that the wheel is facing
Parameters
[in] wheelIdx index of the wheel, they are counted from left-front to rear-right
WheelGetEntity()
proto native EntityAI WheelGetEntity (int wheelIdx) private
Returns the entity attached that represents the wheel
Parameters
[in] wheelIdx index of the wheel, they are counted from left-front to rear-right
WheelGetSurface()
proto native SurfaceInfo WheelGetSurface (int wheelIdx) private
Returns the surface that the wheel is nearby
Parameters
[in] wheelIdx index of the wheel, they are counted from left-front to rear-right
WheelGetWaterState()
proto native CarWheelWaterState WheelGetWaterState (int wheelIdx) private
Returns the state that the wheel is in with water
Parameters
[in] wheelIdx index of the wheel, they are counted from left-front to rear-right
WheelHasContact()
proto native bool WheelHasContact (int wheelIdx) private
Returns true if given wheel is making any contact
Parameters
[in] wheelIdx index of the wheel, they are counted from left-front to rear-right
WheelIsAnyLocked()
proto native bool WheelIsAnyLocked () private
Returns true if any of the wheels are locked in terms of its movement.
WheelIsLocked()
proto native bool WheelIsLocked (int wheelIdx) private
Returns true if given wheel is locked in terms of its movement.
Parameters
[in] wheelIdx index of the wheel, they are counted from left-front to rear-right
The documentation for this class was generated from the following files:
P:/scripts/3_Game/Vehicles/Boat.c
P:/scripts/3_Game/Vehicles/Car.c