DayZ Scripts: AreaDamageTriggerBase Class Reference
AreaDamageTriggerBase Class Reference
Private Member Functions
override void OnStayServerEvent (TriggerInsider insider, float deltaTime)
void AreaDamageTrigger ()
override void EOnTouch (IEntity other, int extra)
override void SetExtents (vector mins, vector maxs)
override void SetAreaDamageManager (AreaDamageManager adType)
void SetAreaDamageType (AreaDamageBase adType)
override void OnEnter (Object obj)
override void OnLeave (Object obj)
override protected void UpdateInsiders (int timeout)
Private Attributes
protected ref AreaDamageBase m_AreaDamageType
protected vector m_ExtentMin
protected vector m_ExtentMax
protected float m_InnerDistance
protected int m_TriggerUpdateMs
Member Function Documentation
AreaDamageTrigger()
void AreaDamageTrigger () inline private
References m_ExtentMax, m_ExtentMin, and vector::Zero.
EOnTouch()
override void EOnTouch (IEntity other, int extra) inline private
References AddInsider(), and Class::CastTo().
OnEnter()
override void OnEnter (Object obj) inline private
References GetGame().
OnLeave()
override void OnLeave (Object obj) inline private
References GetGame().
Referenced by UpdateInsiders().
OnStayServerEvent()
override void OnStayServerEvent (TriggerInsider insider, float deltaTime) inline private
References m_AreaDamageManager.
SetAreaDamageManager()
override void SetAreaDamageManager (AreaDamageManager adType) inline private
Referenced by CreateDamageTriggerEx().
SetAreaDamageType()
void SetAreaDamageType (AreaDamageBase adType) inline private
SetExtents()
override void SetExtents (vector mins, vector maxs) inline private
References GetRadius(), m_ExtentMax, and m_ExtentMin.
Referenced by CreateDamageTriggerEx(), and SetExtents().
UpdateInsiders()
override protected void UpdateInsiders (int timeout) inline private
DEBUG
References vector::DistanceSq(), g_Game, GetGame(), TriggerInsider::GetObject(), GetPosition, OnLeave(), and TriggerInsider::timeStamp.
Field Documentation
m_AreaDamageType
protected ref AreaDamageBase m_AreaDamageType private
m_ExtentMax
protected vector m_ExtentMax private
m_ExtentMin
protected vector m_ExtentMin private
m_InnerDistance
protected float m_InnerDistance private
m_TriggerUpdateMs
protected int m_TriggerUpdateMs private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/AreaDamage/AreaDamageNew/AreaDamageTriggerDirect.c
P:/scripts/4_World/Classes/AreaDamage/AreaDamageTrigger.c