DayZ Scripts: float Class Reference
float Class Reference
Private Member Functions
proto string ToString ()
Private Attributes
const float MIN = FLT_MIN
const float MAX = FLT_MAX
const float LOWEST = -FLT_MAX
Member Function Documentation
ToString()
proto string ToString () private
Referenced by HudDebugWinBase::AddValue(), BleedChanceData::CalculateBleedChance(), PluginBase::CheckInit(), StatDebugObject::Debug(), WeaponDebug::DisplayGeneralInfo(), WeaponDebug::DisplayTargetInfo(), PoweredOptic_Base::DoMeasurement(), CAContinuousTransferQuantity::Execute(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState(), Environment::GetDebugMessage(), AlarmClock_ColorBase::GetDebugText(), KitchenTimer::GetDebugText(), PluginBase::GetHitMessage(), VicinitySlotsContainer::GetItemQuantityText(), QuantityConversions::GetItemQuantityText(), PlayerStatRecord::GetStringOutput(), GetStrValue(), StatDebugObject::GetValue(), ScriptedWidgetEventHandler::GetValueString(), Weapon::GetWeightSpecialized(), ScriptConsoleItemsTab::Init(), ScriptConsoleWeatherTab::InitValues(), UIScriptedMenu::NextPrevPage(), HumanCommandActionCallback::OnAnimationEvent(), UIScriptedMenu::OnClick(), ActionMeasureTemperatureSelf::OnFinishProgressClient(), ManBase::OnRPC(), OpenAndSwitchLambda::OnSuccess(), OnUpdate(), OnUpdate(), ScriptConsoleEnfScriptTab::PrintS(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessAbortEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessEvent(), BleedingSourcesManagerBase::ProcessHit(), UIScriptedMenu::Refresh(), ScriptedWidgetEventHandler::SetAcceleration(), DebugMonitor::SetBlood(), UIScriptedMenu::SetBlurValue(), ScriptedWidgetEventHandler::SetDOF(), ScriptedWidgetEventHandler::SetEventTime(), ScriptedWidgetEventHandler::SetFOV(), DebugMonitor::SetHealth(), ScriptedWidgetEventHandler::SetInterpTime(), ActionTargetsCursor::SetItemQuantity(), ScriptedWidgetEventHandler::SetItemQuantity(), PluginFileHandler::SetParameterFloat(), DayZProfilesOptions::SetProfileOptionFloat(), WeightDebugData::SetWeight(), Managed::ShowDebugValues(), ScriptConsoleItemsTab::ShowItemButtons(), ScriptConsoleWeatherTab::Update(), UpdateDamageWidget(), UpdateDistanceWidget(), ScriptConsoleWeatherTab::UpdateEditboxValues(), UIScriptedMenu::UpdateItemInfoQuantity(), UIScriptedMenu::UpdateItemInfoTemperature(), UIPopupScript::UpdateSliderWindForce(), PluginBase::UpdateStatWidget(), and HudDebugWinBase::UpdateValues().
Field Documentation
LOWEST
const float LOWEST = -FLT_MAX private
Referenced by InventoryItem::AfterStoreLoad(), InitValues(), and TruncateVec().
MAX
const float MAX = FLT_MAX private
Referenced by GetMeleeTargetEx(), UniversalTemperatureSourceDebug::GetTemperature(), SendEvent(), and TruncateVec().
MIN
const float MIN = FLT_MIN private
The documentation for this class was generated from the following file:
1_Core/proto/EnConvert.c