DayZ Scripts: BroomBase Class Reference
BroomBase Class Reference
Private Member Functions
override void Init ()
override void SetActions ()
override bool CanReceiveUpgrade ()
override void OnWorkStart ()
override void ApplyResultModifications (ItemBase result)
override bool CanTransformIntoStick ()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void CalculateQuantity ()
override void UpdateParticle ()
void DebugSetHealthAndEnergy (float time)
override void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4)
override void OnDebugButtonPressServer (int button_index)
Detailed Description
Definition at line 1 of file Broom.c.
Member Function Documentation
ApplyResultModifications()
override void ApplyResultModifications (ItemBase result) inline private
Definition at line 29 of file Broom.c.
CalculateQuantity()
override void CalculateQuantity () inline private
Definition at line 52 of file Broom.c.
References GetGame(), and Math::Min().
Referenced by OnWorkStart().
CanReceiveUpgrade()
override bool CanReceiveUpgrade () inline private
Definition at line 18 of file Broom.c.
CanTransformIntoStick()
override bool CanTransformIntoStick () inline private
Definition at line 35 of file Broom.c.
References GetEnergy(), GetGame(), and FlammableBase::IsIgnited().
DebugSetHealthAndEnergy()
void DebugSetHealthAndEnergy (float time) inline private
Definition at line 85 of file Broom.c.
References Math::InverseLerp().
Referenced by OnDebugButtonPressServer().
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
Definition at line 44 of file Broom.c.
References component.
GetDebugButtonNames()
override void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4) inline private
Definition at line 93 of file Broom.c.
Init()
override void Init () inline private
Definition at line 3 of file Broom.c.
References FlammableBase::m_DecraftResult, FlammableBase::m_ParticleLocalPos, and Vector().
OnDebugButtonPressServer()
override void OnDebugButtonPressServer (int button_index) inline private
Definition at line 102 of file Broom.c.
References DebugSetHealthAndEnergy(), and FlammableBase::OnIgnitedThis().
OnWorkStart()
override void OnWorkStart () inline private
Definition at line 23 of file Broom.c.
References CalculateQuantity().
SetActions()
override void SetActions () inline private
Definition at line 10 of file Broom.c.
References AddAction().
UpdateParticle()
override void UpdateParticle () inline private
Definition at line 66 of file Broom.c.
References ParticleList::BROOM_TORCH_T1, GetQuantity(), GetQuantityMax(), FlammableBase::m_FireParticle, FlammableBase::m_ParticleLocalPos, Math::Max(), ParticleManager(), and Particle::ScaleParticleParamFromOriginal().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Gear/Tools/Broom.c