DayZ Scripts: Land_WarheadStorage_PowerStation Class Reference
Land_WarheadStorage_PowerStation Class Reference
Private Member Functions
void Land_WarheadStorage_PowerStation ()
override void DeferredInit ()
override void OnVariablesSynchronized ()
vector GetPowerGeneratorSpawnPos ()
protected void LinkPowerGeneratorServer ()
PowerGeneratorStatic GetPowerGenerator ()
void AnimateLever (int index, int state=-1)
void PlayLeverSound (string leverName, int state)
protected void StartTimer ()
protected void CheckStopTimer ()
void Tick ()
protected void OnLeverToggled ()
protected void TurnAllLeversOff ()
string GetLeverComponentNameByLeverIndex (int leverIndex)
int GetLeverIndexByComponentName (string name)
protected void UpdateLeverStatesServer ()
void OnGeneratorStart ()
void OnGeneratorStop ()
override void OnAnimationPhaseStarted (string animSource, float phase)
protected Land_WarheadStorage_Main GetClosestBunker ()
protected void DebugPrepareGenerator ()
Static Private Member Functions
static void RegisterBunker (Land_WarheadStorage_Main bunker)
static void UnregisterBunker (Land_WarheadStorage_Main bunker)
Private Attributes
protected bool m_InitBunkerState
protected ref Timer m_UpdateTimer
protected int m_LeverStatesBits
protected int m_LastActivatedLeverId
protected PowerGeneratorStatic m_PowerGenerator
protected bool m_IsPowerGeneratorRunning
protected int m_PlaySparks
protected const string LEVERS_POS_MEMPOINT = "leverup_axis"
protected const string GENERATOR_POS_MEMPOINT = "generator_pos"
protected const string SWITCH_UP_SOUND = "Power_Station_Switch_Up_SoundSet"
protected const string SWITCH_DOWN_SOUND = "Power_Station_Switch_Down_SoundSet"
protected const string SPARKLES_SOUND = "Power_Station_generator_overpowered_SoundSet"
Static Private Attributes
static protected ref set< Land_WarheadStorage_Main > m_Bunkers
Constructor & Destructor Documentation
Land_WarheadStorage_PowerStation()
void Land_WarheadStorage_PowerStation () inline private
References m_PlaySparks.
Member Function Documentation
AnimateLever()
void AnimateLever (int index, int state = -1) inline private
References GetGame(), GetLeverComponentNameByLeverIndex(), and StartTimer().
Referenced by ActionOperatePanelPowerStation::OnStart(), and TurnAllLeversOff().
CheckStopTimer()
protected void CheckStopTimer () inline private
References m_UpdateTimer.
Referenced by Tick().
DebugPrepareGenerator()
protected void DebugPrepareGenerator () inline private
References GetGame(), and m_PowerGenerator.
DeferredInit()
override void DeferredInit () inline private
References GetGame(), LinkPowerGeneratorServer(), and CGame::RegisterNetworkStaticObject().
GetClosestBunker()
protected Land_WarheadStorage_Main GetClosestBunker () inline private
References vector::DistanceSq(), GetGame(), GetPosition, CGame::IsServer(), m_Bunkers, m_InitBunkerState, m_PowerGenerator, and Land_WarheadStorage_Main::SetPowerServer().
Referenced by OnGeneratorStart(), OnGeneratorStop(), and UpdateLeverStatesServer().
GetLeverComponentNameByLeverIndex()
string GetLeverComponentNameByLeverIndex (int leverIndex) inline private
Referenced by AnimateLever(), Tick(), and TurnAllLeversOff().
GetLeverIndexByComponentName()
int GetLeverIndexByComponentName (string name) inline private
References name.
Referenced by ActionOperatePanelPowerStation::ActionCondition(), and ActionOperatePanelPowerStation::OnStart().
GetPowerGenerator()
PowerGeneratorStatic GetPowerGenerator () inline private
References m_PowerGenerator.
Referenced by PowerGeneratorStatic::EEOnAfterLoad().
GetPowerGeneratorSpawnPos()
vector GetPowerGeneratorSpawnPos () inline private
References GENERATOR_POS_MEMPOINT.
Referenced by LinkPowerGeneratorServer().
LinkPowerGeneratorServer()
protected void LinkPowerGeneratorServer () inline private
References ECE_CREATEPHYSICS, ECE_NOLIFETIME, ECE_SETUP, ECE_UPDATEPATHGRAPH, PowerGeneratorStatic::GetClosestGenerator(), GetGame(), GetOrientation(), GetPowerGeneratorSpawnPos(), m_PowerGenerator, OnGeneratorStart(), RF_IGNORE, and PowerGeneratorStatic::SetParent().
Referenced by DeferredInit().
OnAnimationPhaseStarted()
override void OnAnimationPhaseStarted (string animSource, float phase) inline private
References string::Contains(), and PlayLeverSound().
OnGeneratorStart()
void OnGeneratorStart () inline private
References GetClosestBunker(), GetGame(), m_IsPowerGeneratorRunning, m_PlaySparks, and Land_WarheadStorage_Main::SetPowerServer().
Referenced by LinkPowerGeneratorServer(), and PowerGeneratorStatic::OnWorkStart().
OnGeneratorStop()
void OnGeneratorStop () inline private
References GetClosestBunker(), GetGame(), m_IsPowerGeneratorRunning, Land_WarheadStorage_Main::SetPowerServer(), and TurnAllLeversOff().
Referenced by PowerGeneratorStatic::OnWorkStop().
OnLeverToggled()
protected void OnLeverToggled () inline private
References Math::GetNumberOfSetBits(), m_IsPowerGeneratorRunning, m_LastActivatedLeverId, m_LeverStatesBits, m_PlaySparks, m_PowerGenerator, and TurnAllLeversOff().
Referenced by Tick().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References ParticleList::LEVER_SPARKS, m_PlaySparks, ParticleManager(), SEffectManager::PlaySoundCachedParams(), EffectSound::SetAutodestroy(), and SPARKLES_SOUND.
PlayLeverSound()
void PlayLeverSound (string leverName, int state) inline private
References LEVERS_POS_MEMPOINT, EffectSound::SetAutodestroy(), SWITCH_DOWN_SOUND, and SWITCH_UP_SOUND.
Referenced by OnAnimationPhaseStarted().
RegisterBunker()
static void RegisterBunker (Land_WarheadStorage_Main bunker) inline static private
References m_Bunkers.
Referenced by Land_WarheadStorage_Main::Land_WarheadStorage_Main().
StartTimer()
protected void StartTimer () inline private
References m_UpdateTimer.
Referenced by AnimateLever().
Tick()
void Tick () inline private
References CheckStopTimer(), GetLeverComponentNameByLeverIndex(), m_LastActivatedLeverId, m_LeverStatesBits, OnLeverToggled(), and UpdateLeverStatesServer().
TurnAllLeversOff()
protected void TurnAllLeversOff () inline private
References AnimateLever(), and GetLeverComponentNameByLeverIndex().
Referenced by OnGeneratorStop(), and OnLeverToggled().
UnregisterBunker()
static void UnregisterBunker (Land_WarheadStorage_Main bunker) inline static private
References ErrorEx, and m_Bunkers.
Referenced by Land_WarheadStorage_Main::~Land_WarheadStorage_Main().
UpdateLeverStatesServer()
protected void UpdateLeverStatesServer () inline private
References GetClosestBunker(), m_LeverStatesBits, and Land_WarheadStorage_Main::SetLeverStatesServer().
Referenced by Tick().
Field Documentation
GENERATOR_POS_MEMPOINT
protected const string GENERATOR_POS_MEMPOINT = "generator_pos" private
Referenced by GetPowerGeneratorSpawnPos().
LEVERS_POS_MEMPOINT
protected const string LEVERS_POS_MEMPOINT = "leverup_axis" private
Referenced by PlayLeverSound().
m_Bunkers
protected ref set<Land_WarheadStorage_Main> m_Bunkers static private
Referenced by GetClosestBunker(), RegisterBunker(), and UnregisterBunker().
m_InitBunkerState
protected bool m_InitBunkerState private
Referenced by GetClosestBunker().
m_IsPowerGeneratorRunning
protected bool m_IsPowerGeneratorRunning private
Referenced by OnGeneratorStart(), OnGeneratorStop(), and OnLeverToggled().
m_LastActivatedLeverId
protected int m_LastActivatedLeverId private
Referenced by OnLeverToggled(), and Tick().
m_LeverStatesBits
protected int m_LeverStatesBits private
Referenced by OnLeverToggled(), Tick(), and UpdateLeverStatesServer().
m_PlaySparks
protected int m_PlaySparks private
Referenced by Land_WarheadStorage_PowerStation(), OnGeneratorStart(), OnLeverToggled(), and OnVariablesSynchronized().
m_PowerGenerator
protected PowerGeneratorStatic m_PowerGenerator private
Referenced by DebugPrepareGenerator(), GetClosestBunker(), GetPowerGenerator(), LinkPowerGeneratorServer(), and OnLeverToggled().
m_UpdateTimer
protected ref Timer m_UpdateTimer private
Referenced by CheckStopTimer(), and StartTimer().
SPARKLES_SOUND
protected const string SPARKLES_SOUND = "Power_Station_generator_overpowered_SoundSet" private
Referenced by OnVariablesSynchronized().
SWITCH_DOWN_SOUND
protected const string SWITCH_DOWN_SOUND = "Power_Station_Switch_Down_SoundSet" private
Referenced by PlayLeverSound().
SWITCH_UP_SOUND
protected const string SWITCH_UP_SOUND = "Power_Station_Switch_Up_SoundSet" private
Referenced by PlayLeverSound().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Building/Underground/Land_WarheadStorage_PowerStation.c