DayZ Scripts: SoundSetMap Class Reference
SoundSetMap Class Reference
Static Private Member Functions
static void Init ()
static string GetSoundSetName (int id)
static int GetSoundSetID (string name)
Static Private Attributes
static ref map< int, string > m_SoundSetMapIDByID = new map<int, string>
static ref map< string, int > m_SoundSetMapIDByName = new map<string, int>
Detailed Description
Definition at line 1 of file SoundSetMap.c.
Member Function Documentation
GetSoundSetID()
static int GetSoundSetID (string name) inline static private
Definition at line 27 of file SoundSetMap.c.
References m_SoundSetMapIDByName, and name.
GetSoundSetName()
static string GetSoundSetName (int id) inline static private
Definition at line 22 of file SoundSetMap.c.
References m_SoundSetMapIDByID.
Init()
static void Init () inline static private
Definition at line 6 of file SoundSetMap.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), m_SoundSetMapIDByID, m_SoundSetMapIDByName, and path.
Referenced by MissionBaseWorld::MissionBase().
Field Documentation
m_SoundSetMapIDByID
ref map<int, string> m_SoundSetMapIDByID = new map<int, string> static private
Definition at line 3 of file SoundSetMap.c.
Referenced by GetSoundSetName(), and Init().
m_SoundSetMapIDByName
ref map<string, int> m_SoundSetMapIDByName = new map<string, int> static private
Definition at line 4 of file SoundSetMap.c.
Referenced by GetSoundSetID(), and Init().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/SoundSetMap.c