DayZ Scripts: HungerMdfr Class Reference
HungerMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
protected float m_EnergyDelta
protected float m_LastEnergyLevel
ref HumanMovementState m_MovementState = new HumanMovementState()
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
Init()
override void Init () inline private
References DEFAULT_TICK_TIME_INACTIVE, DisableDeactivateCheck(), m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnReconnect()
override void OnReconnect (PlayerBase player) inline private
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
References PlayerConstants::CONSUMPTION_MULTIPLIER_BASE, PlayerConstants::LOW_ENERGY_DAMAGE_PER_SEC, PlayerConstants::LOW_ENERGY_THRESHOLD, HumanMovementState::m_iMovement, m_MovementState, PlayerStomach(), and PlayerConstants::SL_ENERGY_MAX.
Field Documentation
m_EnergyDelta
protected float m_EnergyDelta private
m_LastEnergyLevel
protected float m_LastEnergyLevel private
m_MovementState
ref HumanMovementState m_MovementState = new HumanMovementState() private
Referenced by OnTick().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/Hunger.c