DayZ Scripts: IEntity Class Reference
IEntity Class Reference
Entity system » Entity editor attribute system
Private Member Functions
private void ~Object ()
private void Object ()
bool CanBeSkinned ()
void Delete ()
Delete this object in next frame.
proto native void AddProxyPhysics (string proxySelectionName)
proto native void RemoveProxyPhysics (string proxySelectionName)
void OnEnterTrigger (ScriptedEntity trigger)
Object entered trigger.
void OnLeaveTrigger (ScriptedEntity trigger)
Object left trigger.
proto native bool GetLODS (notnull out array< LOD > lods)
Retrieve all LODS
proto native owned string GetLODName (LOD lod)
Retrieve LOD name.
proto native vector GetBoundingCenter ()
LOD GetLODByName (string name)
Retrieve LOD by given name.
TStringArray GetHiddenSelections ()
Returns the hiddenSelections array from the object's config.
TStringArray GetHiddenSelectionsTextures ()
Returns the hiddenSelectionsTextures array from the object's config.
TStringArray GetHiddenSelectionsMaterials ()
Returns the hiddenSelectionsMaterials array from the object's config.
void Explode (int damageType, string ammoType="")
Creates an explosion on this object by its ammoType in config.
void SynchExplosion ()
void OnExplodeClient ()
Called on clients when this object explodes.
void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
proto native owned string GetActionComponentName (int componentIndex, string geometry="")
returns action component name by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
proto native owned vector GetActionComponentPosition (int componentIndex, string geometry="")
returns action component position by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
proto native owned int GetActionComponentNameList (int componentIndex, TStringArray nameList, string geometry="")
outputs action component name list by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode). Returns -1 (not found), 0 (found default component only), or 1 (found named component)
proto native bool IsActionComponentPartOfSelection (int componentIndex, string selectionName, string geometry="")
return true if selection containts action component, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
proto void GetActionComponentsForSelectionName (int level, string selectionName, TIntArray componentIndices)
outputs action component index list by given selection, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
proto vector GetActionComponentCenter (int level, int componentIndex)
The center of the component, in model space.
proto vector GetActionComponentCenterOOB (int level, int componentIndex)
The center of the component, in model space.
proto void GetActionComponentMinMax (int level, int componentIndex, out vector min, out vector max)
The AABB of the component.
proto native bool ToDelete ()
Flag to determine this object is marked to be deleted soon.
proto native bool IsPendingDeletion ()
proto native int GetGeometryLevel ()
Native functions for getting the level used for calculating the pivot.
proto native int GetFireGeometryLevel ()
proto native int GetViewGeometryLevel ()
proto native int GetMemoryLevel ()
proto int GetBonePivot (int level, int component)
Get the pivot point of the bone from the component index in the LOD, level can be geometry, fire, view or memory.
proto native void GetBonePivotsForAnimationSource (int level, string animationSource, out TIntArray pivots)
Get the pivots assigned to the animation source at the specified LOD.
proto native vector GetBonePositionLS (int pivot)
returns local space, model space, world space position of the bone
proto native vector GetBonePositionMS (int pivot)
proto native vector GetBonePositionWS (int pivot)
proto native void GetBoneRotationLS (int pivot, out float quaternion[4])
returns local space, model space, world space orientation (quaternion) of a bone
proto native void GetBoneRotationMS (int pivot, out float quaternion[4])
proto native void GetBoneRotationWS (int pivot, out float quaternion[4])
proto native void GetBoneTransformLS (int pivot, out vector transform[4])
returns local space, model space, world space transformations of a bone
proto native void GetBoneTransformMS (int pivot, out vector transform[4])
proto native void GetBoneTransformWS (int pivot, out vector transform[4])
proto native void GetTightlyPackedCorners (ETransformationAxis axis, out vector corners[4])
Get corner positions in worldspace aligned to the orientation of the object (currently only TOP/BOTTOM supported)
proto native vector GetPosition ()
Retrieve position.
proto native vector GetWorldPosition ()
proto native void SetPosition (vector vPos)
Set position.
proto native void PlaceOnSurface ()
Place object on surface.
proto native vector GetOrientation ()
Retrieve orientation (yaw, pitch, roll) in degrees
proto native void SetOrientation (vector vOrientation)
Set orientation (yaw, pitch, roll) in degrees
proto native vector GetDirection ()
Retrieve direction vector.
proto native void SetDirection (vector vPos)
Set direction of object.
proto native vector GetDirectionUp ()
Retrieve direction up vector.
proto native vector GetDirectionAside ()
Retrieve direction aside vector.
proto native vector GetLocalPos (vector vPos)
Calculate local position of other entity to this entity.
proto native vector GetGlobalPos (vector vPos)
Calculate global position to this entity from local position.
proto native vector GetSpeed ()
Retrieve object's speed in global space.
proto native vector GetModelSpeed ()
Retrieve object's speed in local space.
proto native bool CanAffectPathgraph ()
Returns true if object's geometry can affect pathgraph generation.
proto native void SetAffectPathgraph (bool fromConfig, bool affect)
Sets if object's geometry affects pathgraph generation. If first parameter is true, it ignores second parameter and sets affecting pathgraph by parameter set in object's config.
proto float ClippingInfo (out vector minMax[2])
Get Clipping info.
proto native bool GetCollisionBox (out vector minMax[2])
Gets collision bounding box.
proto native float GetCollisionRadius ()
Gets collision radius (bounding sphere)
proto native float GetDamage ()
Get total damage (clipped to range 0..1)
proto native void GetSelectionList (out TStringArray selectionList)
float GetSurfaceNoise ()
Returns noise multiplier of surface under object.
string GetSurfaceType ()
Returns type of surface under object.
bool HasSelection (string selection)
Returns true if the given selection was found in the p3d file. False if otherwise.
bool HasAnimation (string anim_name)
Searches object's config for the given animation name. Returns true if it was found, or false if not.
proto native int GetMemoryPointIndex (string memoryPointName)
If Returns true if this item has EnergyManager in its config. Otherwise returns false.
proto native vector GetMemoryPointPos (string memoryPointName)
proto native vector GetMemoryPointPosByIndex (int pointIndex)
proto native bool MemoryPointExists (string memoryPoint)
proto native void CreateDynamicPhysics (int interactionLayers)
proto native void EnableDynamicCCD (bool state)
proto native void SetDynamicPhysicsLifeTime (float lifeTime)
void OnTreeCutDown (EntityAI cutting_entity)
Called when tree is chopped down. 'cutting_entity' can be tool, or player, if cutting bush with bare hands.
string GetType ()
Get config class of object.
string GetDisplayName ()
Get display name of entity.
bool DisplayNameRuinAttach ()
string GetModelName ()
Returns name of the model of this object without the '.p3d' suffix.
proto native owned string GetShapeName ()
Return path and name of the model.
int Release ()
bool IsKindOf (string type)
Check config class name of the object.
bool IsAlive ()
bool IsMan ()
Returns if this entity is Man.
bool IsDayZCreature ()
Checks if this instance is of type DayZCreature.
bool IsEntityAI ()
Returns if this entity is EntityAI.
bool IsStaticTransmitter ()
Returns if this entity is Static Transmitter.
bool IsTransmitter ()
Returns if this entity is a non-static Transmitter.
bool IsItemBase ()
Returns if this entity is ItemBase.
bool IsContainer ()
bool IsMagazine ()
Returns if this entity is Magazine.
bool IsAmmoPile ()
Returns if this entity is Ammo Pile.
bool IsInventoryItem ()
Returns if this entity is InventoryItem.
bool IsClothing ()
Returns if this entity is Clothing.
bool IsFireplace ()
Returns if this entity is fireplacebase.
bool IsTree ()
Returns if this entity is tree.
bool IsRock ()
Returns if this entity is rock.
bool IsWoodBase ()
Returns whether object is PlanBase.
bool IsBush ()
Returns if this entity is bush.
bool IsCuttable ()
bool IsPeltBase ()
Returns if this entity is Pelt_Base.
bool IsWeapon ()
Returns if this entity is Weapon.
bool IsMeleeWeapon ()
returns if this entity is Melee Weapon
bool IsBuilding ()
Returns if this entity is Building.
EWaterSourceObjectType GetWaterSourceObjectType ()
int GetLiquidSourceType ()
bool IsWell ()
bool ShootsExplosiveAmmo ()
Returns if this entity is a weapon which can shoot explosive ammo.
bool IsFuelStation ()
Returns if this entity is Fuel Station (extends Building)
bool IsTransport ()
Returns if this entity is transport.
bool IsElectricAppliance ()
Returns if this is an appliance, that can be plugged into electric circuit (== not energy source)
bool CanUseConstruction ()
Returns if this entity can be constucted,deconstructed (e.g. fence,watchtower)
bool CanUseConstructionBuild ()
Returns if this entity can be built, specifically.
bool CanUseHandConstruction ()
Returns if this entity can be constructed without tools.
bool IsBeingBackstabbed ()
void SetBeingBackstabbed (int backstabType)
bool IsFood ()
Returns if this entity if a food item.
bool IsFruit ()
bool IsMeat ()
bool IsCorpse ()
bool IsMushroom ()
bool IsHealthVisible ()
Returns if the health of this entity should be displayed (widgets, inventory)
bool ShowZonesHealth ()
Returns true if the health of damage zones should be displayed (instead of global HP of the entity) (action widgets)
bool IsParticle ()
bool IsItemTent ()
bool IsScriptedLight ()
bool IsHologram ()
bool HasProxyParts ()
bool CanObstruct ()
bool CanProxyObstruct ()
bool CanProxyObstructSelf ()
can the object's own proxy geometry obstruct it? Currently checking 'ObjIntersectView'
bool CanBeIgnoredByDroppedItem ()
bool CanBeAutoDeleted ()
bool DisableVicinityIcon ()
Disables icon in the vicinity, useful for large, immovable items, that are not buildings.
proto void GetNetworkID (out int lowBits, out int highBits)
string GetNetworkIDString ()
override string GetDebugName ()
proto string GetDebugNameNative ()
native GetDebugName which is internally overloaded where needed
void RPC (int rpc_type, array< ref Param > params, bool guaranteed, PlayerIdentity recipient=NULL)
Remote procedure call shortcut, see CGame.RPC / CGame.RPCSingleParam.
void RPCSingleParam (int rpc_type, Param param, bool guaranteed, PlayerIdentity recipient=NULL)
Remote procedure call shortcut, see CGame.RPCSingleParam / CGame.RPC.
void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
vector GetSelectionPositionOld (string name)
vector GetSelectionPositionLS (string name)
vector GetSelectionPositionMS (string name)
vector GetSelectionPositionWS (string name)
vector ModelToWorld (vector modelPos)
vector WorldToModel (vector worldPos)
proto string ConfigGetString (string entryName)
proto string ConfigGetStringRaw (string entryName)
Get a raw strings from config entry.
proto int ConfigGetInt (string entryName)
bool ConfigGetBool (string entryName)
proto float ConfigGetFloat (string entryName)
proto vector ConfigGetVector (string entryName)
proto native void ConfigGetTextArray (string entryName, out TStringArray values)
Get array of strings from config entry.
proto native void ConfigGetTextArrayRaw (string entryName, out TStringArray values)
Get array of raw strings from config entry.
proto native void ConfigGetFloatArray (string entryName, out TFloatArray values)
Get array of floats from config entry.
proto native void ConfigGetIntArray (string entryName, out TIntArray values)
Get array of integers from config entry.
proto native bool ConfigIsExisting (string entryName)
Checks if given entry exists.
bool KindOf (string tag)
Compares config class name to given string.
bool IsAnyInherited (array< typename > typenames)
proto native bool IsPlainObject ()
Is this just static object without config? So we can avoid calling unnecessary methods.
proto native bool IsScenery ()
Is this Scenery? (handy for excluding terain when it is not needed)
proto native bool HasDamageSystem ()
Checks if object's DamageSystem has been initialized(despite the name, does not really reliably answer the question whether the object is configured to have damage system or not)
proto native bool IsDamageDestroyed ()
Checks if object is destroyed.
proto native void SetDestructTime (float time)
Sets the time over which to perform DestructTent/DestructTree.
proto native float GetHealth (string zoneName, string healthType)
Returns current state of health.
proto native float GetHealth01 (string zoneName, string healthType)
Returns current state of health in range <0, 1>.
proto native float GetMaxHealth (string zoneName, string healthType)
Returns maximum value of health.
proto native void SetHealth (string zoneName, string healthType, float value)
Sets current state of health.
proto native void SetFullHealth ()
Sets full health to all zones and removes fatal damage when applicable.
proto native void AddHealth (string zoneName, string healthType, float value)
Adds health.
proto native void DecreaseHealth (string zoneName, string healthType, float value)
Decreases health.
proto native bool GetAdditionalHealthTypes (string zoneName, TStringArray outHealthTypes)
List of additional health types in given zone.
void DecreaseHealth (string zoneName, string healthType, float value, bool auto_delete)
Decreases health with the option of auto-deleting the object if its ruined.
float GetHealth ()
Equivalent of GetHealth("", "");.
float GetHealth01 ()
Equivalent of GetHealth01("", "");.
float GetMaxHealth ()
Equivalent of GetMaxHealth("", "");.
void SetHealth (float health)
Equivalent of SetHealth("", "", float value);.
void SetGlobalHealth (float health)
Equivalent of SetHealth("", "", float value);.
void SetHealthLevel (int healthLevel, string zone="")
Sets specific health level. It will use the cutoff value as returned by 'GetHealthLevelValue' as the health value for the given health level, which means it will always be set to the max health as allowed by the given health level.
void AddHealthLevel (int healthLevelDelta, string zone="")
Similar to 'SetHealthLevel', but allows to jump up/down 'healthLevelDelta' amount of health levels from the current one. Positive values cause health level increase, therefore damage the item, and vice-versa.
void SetHealth01 (string zoneName, string healthType, float coef)
Sets health relative to its maximum.
void SetHealthMax (string zoneName="", string healthType="")
Sets health to its maximum (zone or global)
void AddHealth (float add_health)
Equivalent of AddHealth("", "", float value);.
void DecreaseHealth (float dec_health, bool auto_delete=true)
Equivalent of DecreaseHealth("", "", float value, bool auto_delete);.
void DecreaseHealthCoef (float dec_health_coef, bool auto_delete=true)
Decreases health by the given coeficient.
proto native void ProcessDirectDamage (int damageType, EntityAI source, string componentName, string ammoName, vector modelPos, float damageCoef=1.0, int flags=0)
Applies damage on object.
bool EEOnDamageCalculated (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
Event called from C++ right before damage is applied.
proto native void GetDamageZones (out TStringArray dmgZones)
Obtains a list of nammes of all object's damage zones.
proto native vector GetDamageZonePos (string zoneName)
Obtains middle position of damage zone based on it's name.
proto native owned string GetDamageZoneNameByComponentIndex (int componentIndex)
Obtains name of damage zone based on index of specific component.
proto native int GetHealthLevel (string zone="")
Returns global health level specified in object's config class parameter healthLevels (range is usually 0..4, 0 = pristine, 1 = worn, 2 = damaged, 3 = badly damaged, 4 = ruined but can be changed).
proto native int GetNumberOfHealthLevels (string zone="")
Returns global number of health levels specified in object's config class parameter healthLevels (range is usually 0..4, 0 = pristine, 1 = worn, 2 = damaged, 3 = badly damaged, 4 = ruined but can be changed).
proto native float GetHealthLevelValue (int healthLevel, string zone="")
Returns cutoff value for health level specified in object's config class parameter healthLevels.
proto native bool GetAllowDamage ()
Returns if object can receive damage.
proto native void SetAllowDamage (bool val)
Enable or disable object to receive damage.
proto native bool GetCanBeDestroyed ()
Returns if object is destroyable.
proto native void SetCanBeDestroyed (bool val)
Enable or disable destruction of object (after health is depleated)
bool IsRuined ()
Returns whether the object is ruined (0 Health).
void OnSimulationEnabled ()
Event called from C++ when simulation is enabled.
void OnSimulationDisabled ()
Event called from C++ when simulation is disabled.
void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
SoundOnVehicle PlaySound (string sound_name, float range, bool create_local=true)
Plays the given sound once on this object's instance. Range is in meters. Created sound is only local, unless create_local is set to false. Returns the sound itself.
SoundOnVehicle PlaySoundLoop (string sound_name, float range, bool create_local=true)
Plays the given sound in loop on this object's instance. Range is in meters. Created sound is only local, unless create_local is set to false. Returns the sound itself.
bool PlaySoundSet (out EffectSound sound, string sound_set, float fade_in, float fade_out, bool loop=false)
EffectSound - plays soundset on this object and returns state of the sound (true - played, false - not played)
bool PlaySoundSetLoop (out EffectSound sound, string sound_set, float fade_in, float fade_out)
EffectSound - plays soundset on this object in loop and returns state of the sound (true - played, false - not played)
bool PlaySoundSetAtMemoryPointLoopedSafe (out EffectSound sound, string soundSet, string memoryPoint, float play_fade_in=0, float stop_fade_out=0)
Same as PlaySoundSetAtMemoryPointLooped, only requests stoppage of the currently playing EffectSound if it already exists and playing, before playing the new sound.
bool PlaySoundSetAtMemoryPointLooped (out EffectSound sound, string soundSet, string memoryPoint, float play_fade_in=0, float stop_fade_out=0)
bool PlaySoundSetAtMemoryPoint (out EffectSound sound, string soundSet, string memoryPoint, bool looped=false, float play_fade_in=0, float stop_fade_out=0)
bool StopSoundSet (out EffectSound sound)
EffectSound - stops soundset and returns state of the sound (true - stopped, false - not playing)
void PostAreaDamageActions ()
void PreAreaDamageActions ()
void SpawnDamageDealtEffect ()
void OnReceivedHit (ImpactEffectsData hitData)
void OnPlayerRecievedHit ()
DEPRECATED.
bool HasNetworkID ()
bool NameOverride (out string output)
bool DescriptionOverride (out string output)
EntityAI ProcessMeleeItemDamage (int mode=0)
bool CanBeRepairedToPristine ()
vector GetCenter ()
void AddArrow (Object arrow, int componentIndex, vector closeBonePosWS, vector closeBoneRotWS)
bool CanBeActionTarget ()
bool HasFixedActionTargetCursorPosition ()
Event methods
Event method stubs. Reimplement these in inherited entities to receive event calls
event protected void EOnTouch (IEntity other, int extra)
EntityEvent.TOUCH.
event protected void EOnInit (IEntity other, int extra)
EntityEvent.INIT.
event protected void EOnExtra (IEntity other, int extra)
EntityEvent.EXTRA.
event protected void EOnNotVisible (IEntity other, int extra)
EntityEvent.NOTVISIBLE.
event protected void EOnFrame (IEntity other, float timeSlice)
EntityEvent.FRAME.
event protected int EOnVisible (IEntity other, int extra)
EntityEvent.VISIBLE.
event protected void EOnPostFrame (IEntity other, int extra)
EntityEvent.POSTFRAME.
event protected void EOnWorldProcess (IEntity other, int extra)
EntityEvent.WORLDPROCESS.
event protected void EOnAnimEvent (IEntity other, AnimEvent extra)
EntityEvent.ANIMEVENT.
event protected void EOnSoundEvent (IEntity other, SoundEvent extra)
EntityEvent.SOUNDEVENT.
event protected void EOnSimulate (IEntity other, float dt)
EntityEvent.SIMULATE.
event protected void EOnPostSimulate (IEntity other, float timeSlice)
EntityEvent.POSTSIMULATE.
event protected void EOnJointBreak (IEntity other, int extra)
EntityEvent.JOINTBREAK.
event protected void EOnPhysicsMove (IEntity other, int extra)
EntityEvent.PHYSICSMOVE.
event protected void EOnContact (IEntity other, Contact extra)
EntityEvent.CONTACT.
protected void EOnUser0 (IEntity other, int extra)
EntityEvent.EV_USER+0.
protected void EOnUser1 (IEntity other, int extra)
EntityEvent.EV_USER+1.
event protected void EOnEnter (IEntity other, int extra)
EntityEvent.ENTER.
event protected void EOnLeave (IEntity other, int extra)
EntityEvent.LEAVE.
protected void EOnUser4 (IEntity other, int extra)
EntityEvent.EV_USER+4.
protected void EOnDummy020 (IEntity other, int extra)
Placeholder.
protected void EOnDummy021 (IEntity other, int extra)
Placeholder.
protected void EOnDummy022 (IEntity other, int extra)
Placeholder.
protected void EOnDummy023 (IEntity other, int extra)
Placeholder.
protected void EOnDummy024 (IEntity other, int extra)
Placeholder.
protected void EOnDummy025 (IEntity other, int extra)
Placeholder.
protected void EOnDummy026 (IEntity other, int extra)
Placeholder.
protected void EOnDummy027 (IEntity other, int extra)
Placeholder.
protected void EOnDummy028 (IEntity other, int extra)
Placeholder.
protected void EOnDummy029 (IEntity other, int extra)
Placeholder.
protected void EOnDummy030 (IEntity other, int extra)
Placeholder.
protected void EOnDummy031 (IEntity other, int extra)
Placeholder.
Transformation methods
Setting and getting of entity transformation
proto external void GetTransform (out vector mat[])
Returns transformation of Entity. It returns only so much vectors as array is big.
proto external void GetRenderTransform (out vector mat[])
Returns render transformation of Entity. Must pass in vector array size of 4.
proto external void GetLocalTransform (out vector mat[])
Returns local transformation of Entity. It returns only so much vectors as array is big.
proto native external vector GetTransformAxis (int axis)
Returns one row of Entity transformation matrix.
proto native external void SetTransform (vector mat[4])
Sets entity transformation.
proto native external vector GetOrigin ()
Returns origin of Entity.
proto external vector GetLocalPosition ()
Returns local position of Entity.
proto native external vector GetYawPitchRoll ()
Returns orientation of Entity in world space (Yaw, Pitch, Roll)
proto native external vector GetAngles ()
Same as GetYawPitchRoll, but returns rotation vector around X, Y and Z axis.
proto native external vector GetLocalYawPitchRoll ()
Returns local orientation when it's in hierarchy (Yaw, Pitch, Roll)
proto native external vector GetLocalAngles ()
Same as GetLocalYawPitchRoll, but returns rotation vector around X, Y and Z axis.
proto native external void SetYawPitchRoll (vector angles)
Sets angles for entity (Yaw, Pitch, Roll)
proto native external void SetAngles (vector angles)
Same as SetYawPitchRoll, but sets rotation around X, Y and Z axis.
proto native external void SetOrigin (vector orig)
Sets origin for entity.
proto native external float GetScale ()
proto native external void SetScale (float scale)
proto native external vector VectorToParent (vector vec)
Transforms local vector to world space.
proto native external vector CoordToParent (vector coord)
Transforms local position to world space.
proto native external vector VectorToLocal (vector vec)
Transforms world space vector to local space.
proto native external vector CoordToLocal (vector coord)
Transforms world space position to local space.
Name/ID methods <br>
proto native int GetID ()
Return unique entity ID.
proto native void SetID (int id)
Set unique entity ID.
proto native void SetName (string name)
proto native external owned string GetName ()
Hierarchy methods
Scene hierarchy management
proto native external bool AddChild (notnull IEntity child, int pivot, bool positionOnly=false)
Adds child entity to this entity.
proto native external bool RemoveChild (notnull IEntity child, bool keepTransform=false)
Removes child entity from hierarchy.
proto native bool IsHierarchyPositionOnly ()
Returns if the hierarchy component was created with positionOnly.
proto native int GetHierarchyPivot ()
Returns the hierarchy component pivot.
proto native IEntity GetParent ()
Returns pointer to parent Entity in hierarchy.
proto native IEntity GetChildren ()
Returns pointer to first child Entity in hierarchy.
proto native IEntity GetSibling ()
Returns pointer to next child Entity on the same hierarchy.
proto external void GetBounds (out vector mins, out vector maxs)
Returns local bounding box of model on Entity.
proto external void GetWorldBounds (out vector mins, out vector maxs)
Returns quantized world-bound-box of Entity.
Simulation/handling properties
Flags that affects simulation and entity handling behavior
proto native external EntityFlags GetFlags ()
Returns Entity flags.
proto native external bool IsFlagSet (EntityFlags flags)
Test if one or more of specified flags are set.
proto native external EntityFlags SetFlags (EntityFlags flags, bool recursively)
Sets Entity flags. It's OR operation, not rewrite. Returns previous flags.
proto native external EntityFlags ClearFlags (EntityFlags flags, bool recursively)
Clear Entity flags. Returns cleared flags.
proto native external EntityEvent GetEventMask ()
Returns current event mask.
proto native external EntityEvent SetEventMask (EntityEvent e)
Sets event mask.
proto native external EntityEvent ClearEventMask (EntityEvent e)
Clears event mask.
proto external volatile void SendEvent (notnull IEntity actor, EntityEvent e, void extra)
Dynamic event invokation. Parameters are the same as in IEntity::EOnXXXX() methods.
Visual component methods
Manipulation with visual component - model, particle effect etc
proto native external void SetObject (vobject object, string options)
proto native vobject GetVObject ()
Returns visual object set to this Entity. No reference is added.
proto native external int Animate (float speed, int loop)
Updates animation (either xob, or particle, whatever)
proto native external int AnimateEx (float speed, int loop, out vector lin, out vector ang)
Updates animation (either xob, or particle, whatever)
proto native external int SetCameraMask (int mask)
Sets visibility mask for cameras, where Entity will be rendered.
proto native external void FilterNextTrace ()
When called, the Entity is excluded from consequent TraceMove/TraceLine.
proto native external int Update ()
Static Private Member Functions
static string GetDebugName (Object o)
Detailed Description
Internal ancestor of all Entity implementations.
Constructor & Destructor Documentation
~Object()
private void ~Object () private
Member Function Documentation
AddArrow()
void AddArrow (Object arrow, int componentIndex, vector closeBonePosWS, vector closeBoneRotWS) inline private
References AddChild(), Math3D::MatrixInvMultiply4(), and Math3D::MatrixOrthogonalize4().
AddHealth() [1/2]
void AddHealth (float add_health) inline private
Equivalent of AddHealth("", "", float value);.
AddHealth() [2/2]
proto native void AddHealth (string zoneName, string healthType, float value) private
Adds health.
Parameters
zoneName if empty string, sets state of global health
healthType if empty string, sets state of main health
AddHealthLevel()
void AddHealthLevel (int healthLevelDelta, string zone = "") inline private
Similar to 'SetHealthLevel', but allows to jump up/down 'healthLevelDelta' amount of health levels from the current one. Positive values cause health level increase, therefore damage the item, and vice-versa.
References Math::Clamp().
AddProxyPhysics()
proto native void AddProxyPhysics (string proxySelectionName) private
CanAffectPathgraph()
proto native bool CanAffectPathgraph () private
Returns true if object's geometry can affect pathgraph generation.
CanBeActionTarget()
bool CanBeActionTarget () inline private
References IsHologram().
CanBeAutoDeleted()
bool CanBeAutoDeleted () inline private
CanBeIgnoredByDroppedItem()
bool CanBeIgnoredByDroppedItem () inline private
References IsDayZCreature(), and IsItemBase().
CanBeRepairedToPristine()
bool CanBeRepairedToPristine () inline private
CanBeSkinned()
bool CanBeSkinned () inline private
CanObstruct()
bool CanObstruct () inline private
CanProxyObstruct()
bool CanProxyObstruct () inline private
References CanUseConstruction().
CanProxyObstructSelf()
bool CanProxyObstructSelf () inline private
can the object's own proxy geometry obstruct it? Currently checking 'ObjIntersectView'
CanUseConstruction()
bool CanUseConstruction () inline private
Returns if this entity can be constucted,deconstructed (e.g. fence,watchtower)
CanUseConstructionBuild()
bool CanUseConstructionBuild () inline private
Returns if this entity can be built, specifically.
CanUseHandConstruction()
bool CanUseHandConstruction () inline private
Returns if this entity can be constructed without tools.
ClippingInfo()
proto float ClippingInfo (out vector minMax[2]) private
Get Clipping info.
Parameters
minMax array[2] of vectors, into minMax[0] is returned min, into minMax[1] is returned max
Returns
radius of bounding box
vector minMax[2];
float radius = GetGame().GetPlayer().ClippingInfo(minMax);
Print(minMax);
Print(radius);
ConfigGetBool()
bool ConfigGetBool (string entryName) inline private
ConfigGetFloat()
proto float ConfigGetFloat (string entryName) private
ConfigGetFloatArray()
proto native void ConfigGetFloatArray (string entryName, out TFloatArray values) private
Get array of floats from config entry.
Parameters
entryName
value output
ConfigGetInt()
proto int ConfigGetInt (string entryName) private
ConfigGetIntArray()
proto native void ConfigGetIntArray (string entryName, out TIntArray values) private
Get array of integers from config entry.
Parameters
entryName
value output
ConfigGetString()
proto string ConfigGetString (string entryName) private
ConfigGetStringRaw()
proto string ConfigGetStringRaw (string entryName) private
Get a raw strings from config entry.
Parameters
entryName
Returns
value output string
Note
use 'FormatRawConfigStringKeys' method to change localization keys to script-friendly
ConfigGetTextArray()
proto native void ConfigGetTextArray (string entryName, out TStringArray values) private
Get array of strings from config entry.
Parameters
entryName
value output
ConfigGetTextArrayRaw()
proto native void ConfigGetTextArrayRaw (string entryName, out TStringArray values) private
Get array of raw strings from config entry.
Parameters
entryName
value output in raw format (localization keys '$STR_' are not translated).
Note
use 'FormatRawConfigStringKeys' method to change localization keys to script-friendly
ConfigGetVector()
proto vector ConfigGetVector (string entryName) private
ConfigIsExisting()
proto native bool ConfigIsExisting (string entryName) private
Checks if given entry exists.
Parameters
entryName
CreateDynamicPhysics()
proto native void CreateDynamicPhysics (int interactionLayers) private
DecreaseHealth() [1/3]
void DecreaseHealth (float dec_health, bool auto_delete = true) inline private
Equivalent of DecreaseHealth("", "", float value, bool auto_delete);.
DecreaseHealth() [2/3]
proto native void DecreaseHealth (string zoneName, string healthType, float value) private
Decreases health.
Parameters
zoneName if empty string, sets state of global health
healthType if empty string, sets state of main health
DecreaseHealth() [3/3]
void DecreaseHealth (string zoneName, string healthType, float value, bool auto_delete) inline private
Decreases health with the option of auto-deleting the object if its ruined.
Parameters
zoneName if empty string, sets state of global health
healthType if empty string, sets state of main health
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), and GetGame().
DecreaseHealthCoef()
void DecreaseHealthCoef (float dec_health_coef, bool auto_delete = true) inline private
Decreases health by the given coeficient.
Delete()
void Delete () inline private
Delete this object in next frame.
Returns
void
ItemBase item = GetGame().GetPlayer().CreateInInventory("GrenadeRGD5");
item.Delete();
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), and GetGame().
DescriptionOverride()
bool DescriptionOverride (out string output) inline private
DisableVicinityIcon()
bool DisableVicinityIcon () inline private
Disables icon in the vicinity, useful for large, immovable items, that are not buildings.
DisplayNameRuinAttach()
bool DisplayNameRuinAttach () inline private
EEOnDamageCalculated()
bool EEOnDamageCalculated (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
Event called from C++ right before damage is applied.
Returns
whether to apply the damage or not
EnableDynamicCCD()
proto native void EnableDynamicCCD (bool state) private
Explode()
void Explode (int damageType, string ammoType = "") inline private
Creates an explosion on this object by its ammoType in config.
References GetGame(), and GetPosition.
GetActionComponentCenter()
proto vector GetActionComponentCenter (int level, int componentIndex) private
The center of the component, in model space.
GetActionComponentCenterOOB()
proto vector GetActionComponentCenterOOB (int level, int componentIndex) private
The center of the component, in model space.
GetActionComponentMinMax()
proto void GetActionComponentMinMax (int level, int componentIndex, out vector min, out vector max) private
The AABB of the component.
GetActionComponentName()
proto native owned string GetActionComponentName (int componentIndex, string geometry = "") private
returns action component name by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
GetActionComponentNameList()
proto native owned int GetActionComponentNameList (int componentIndex, TStringArray nameList, string geometry = "") private
outputs action component name list by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode). Returns -1 (not found), 0 (found default component only), or 1 (found named component)
GetActionComponentPosition()
proto native owned vector GetActionComponentPosition (int componentIndex, string geometry = "") private
returns action component position by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
GetActionComponentsForSelectionName()
proto void GetActionComponentsForSelectionName (int level, string selectionName, TIntArray componentIndices) private
outputs action component index list by given selection, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
GetActions()
void GetActions (typename action_input_type , out array< ActionBase_Basic > actions) inline private
GetAdditionalHealthTypes()
proto native bool GetAdditionalHealthTypes (string zoneName, TStringArray outHealthTypes) private
List of additional health types in given zone.
Parameters
zoneName if empty string, global will be used
outHealthType List of the types found (does not clear the existing content)
Returns
false on any error (uninitialized system, bad zone name)
GetAllowDamage()
proto native bool GetAllowDamage () private
Returns if object can receive damage.
GetBonePivot()
proto int GetBonePivot (int level, int component) private
Get the pivot point of the bone from the component index in the LOD, level can be geometry, fire, view or memory.
GetBonePivotsForAnimationSource()
proto native void GetBonePivotsForAnimationSource (int level, string animationSource, out TIntArray pivots) private
Get the pivots assigned to the animation source at the specified LOD.
GetBonePositionLS()
proto native vector GetBonePositionLS (int pivot) private
returns local space, model space, world space position of the bone
GetBonePositionMS()
proto native vector GetBonePositionMS (int pivot) private
GetBonePositionWS()
proto native vector GetBonePositionWS (int pivot) private
GetBoneRotationLS()
proto native void GetBoneRotationLS (int pivot, out float quaternion[4]) private
returns local space, model space, world space orientation (quaternion) of a bone
GetBoneRotationMS()
proto native void GetBoneRotationMS (int pivot, out float quaternion[4]) private
GetBoneRotationWS()
proto native void GetBoneRotationWS (int pivot, out float quaternion[4]) private
GetBoneTransformLS()
proto native void GetBoneTransformLS (int pivot, out vector transform[4]) private
returns local space, model space, world space transformations of a bone
GetBoneTransformMS()
proto native void GetBoneTransformMS (int pivot, out vector transform[4]) private
GetBoneTransformWS()
proto native void GetBoneTransformWS (int pivot, out vector transform[4]) private
GetBoundingCenter()
proto native vector GetBoundingCenter () private
GetCanBeDestroyed()
proto native bool GetCanBeDestroyed () private
Returns if object is destroyable.
GetCenter()
vector GetCenter () inline private
References GetPosition, and Vector().
GetCollisionBox()
proto native bool GetCollisionBox (out vector minMax[2]) private
Gets collision bounding box.
Parameters
minMax array[2] of vectors, into minMax[0] is returned min, into minMax[1] is returned max
Returns
true if collision box exists, false otherwise
vector minMax[2];
if(GetGame().GetPlayer().GetCollisionBox(minMax))
    Print("has box");
GetCollisionRadius()
proto native float GetCollisionRadius () private
Gets collision radius (bounding sphere)
Returns
bounding sphere radius
GetDamage()
proto native float GetDamage () private
Get total damage (clipped to range 0..1)
GetDamageZoneNameByComponentIndex()
proto native owned string GetDamageZoneNameByComponentIndex (int componentIndex) private
Obtains name of damage zone based on index of specific component.
Parameters
index of the component
GetDamageZonePos()
proto native vector GetDamageZonePos (string zoneName) private
Obtains middle position of damage zone based on it's name.
Parameters
name of the damage zone
GetDamageZones()
proto native void GetDamageZones (out TStringArray dmgZones) private
Obtains a list of nammes of all object's damage zones.
Parameters
list of names
GetDebugName() [1/2]
override string GetDebugName () inline private
References GetDebugNameNative().
GetDebugName() [2/2]
static string GetDebugName (Object o) inline static private
GetDebugNameNative()
proto string GetDebugNameNative () private
native GetDebugName which is internally overloaded where needed
GetDirection()
proto native vector GetDirection () private
Retrieve direction vector.
GetDirectionAside()
proto native vector GetDirectionAside () private
Retrieve direction aside vector.
GetDirectionUp()
proto native vector GetDirectionUp () private
Retrieve direction up vector.
GetDisplayName()
string GetDisplayName () inline private
Get display name of entity.
References GetGame(), and CGame::ObjectGetDisplayName().
GetFireGeometryLevel()
proto native int GetFireGeometryLevel () private
GetGeometryLevel()
proto native int GetGeometryLevel () private
Native functions for getting the level used for calculating the pivot.
GetGlobalPos()
proto native vector GetGlobalPos (vector vPos) private
Calculate global position to this entity from local position.
GetHealth() [1/2]
float GetHealth () inline private
Equivalent of GetHealth("", "");.
GetHealth() [2/2]
proto native float GetHealth (string zoneName, string healthType) private
Returns current state of health.
Parameters
zoneName if empty string, returns state of global health
healthType if empty string, returns state of main health
GetHealth01() [1/2]
float GetHealth01 () inline private
Equivalent of GetHealth01("", "");.
GetHealth01() [2/2]
proto native float GetHealth01 (string zoneName, string healthType) private
Returns current state of health in range <0, 1>.
Parameters
zoneName if empty string, returns state of global health
healthType if empty string, returns state of main health
GetHealthLevel()
proto native int GetHealthLevel (string zone = "") private
Returns global health level specified in object's config class parameter healthLevels (range is usually 0..4, 0 = pristine, 1 = worn, 2 = damaged, 3 = badly damaged, 4 = ruined but can be changed).
Parameters
zoneName if empty string, returns state of global health level
GetHealthLevelValue()
proto native float GetHealthLevelValue (int healthLevel, string zone = "") private
Returns cutoff value for health level specified in object's config class parameter healthLevels.
Parameters
zoneName if empty string, returns number of global health levels
healthLevel the health level to get the value from
GetHiddenSelections()
TStringArray GetHiddenSelections () inline private
Returns the hiddenSelections array from the object's config.
References HiddenSelectionsData::GetHiddenSelectionsConfig(), and GetType().
GetHiddenSelectionsMaterials()
TStringArray GetHiddenSelectionsMaterials () inline private
Returns the hiddenSelectionsMaterials array from the object's config.
References HiddenSelectionsData::GetHiddenSelectionsMaterialsConfig(), and GetType().
GetHiddenSelectionsTextures()
TStringArray GetHiddenSelectionsTextures () inline private
Returns the hiddenSelectionsTextures array from the object's config.
References HiddenSelectionsData::GetHiddenSelectionsTexturesConfig(), and GetType().
GetLiquidSourceType()
int GetLiquidSourceType () inline private
References LIQUID_NONE.
GetLocalPos()
proto native vector GetLocalPos (vector vPos) private
Calculate local position of other entity to this entity.
GetLODByName()
LOD GetLODByName (string name) inline private
Retrieve LOD by given name.
References name, and string::ToLower().
GetLODName()
proto native owned string GetLODName (LOD lod) private
Retrieve LOD name.
GetLODS()
proto native bool GetLODS (notnull out array< LOD > lods) private
Retrieve all LODS
GetMaxHealth() [1/2]
float GetMaxHealth () inline private
Equivalent of GetMaxHealth("", "");.
GetMaxHealth() [2/2]
proto native float GetMaxHealth (string zoneName, string healthType) private
Returns maximum value of health.
Parameters
zoneName if empty string, returns state of global health
healthType if empty string, returns state of main health
GetMemoryLevel()
proto native int GetMemoryLevel () private
GetMemoryPointIndex()
proto native int GetMemoryPointIndex (string memoryPointName) private
If Returns true if this item has EnergyManager in its config. Otherwise returns false.
GetMemoryPointPos()
proto native vector GetMemoryPointPos (string memoryPointName) private
GetMemoryPointPosByIndex()
proto native vector GetMemoryPointPosByIndex (int pointIndex) private
GetModelName()
string GetModelName () inline private
Returns name of the model of this object without the '.p3d' suffix.
References GetGame(), CGame::GetModelName(), and GetType().
GetModelSpeed()
proto native vector GetModelSpeed () private
Retrieve object's speed in local space.
GetNetworkID()
proto void GetNetworkID (out int lowBits, out int highBits) private
Returns low and high bits of networkID. This id is shared between client and server for whole server-client session.
GetNetworkIDString()
string GetNetworkIDString () inline private
GetNumberOfHealthLevels()
proto native int GetNumberOfHealthLevels (string zone = "") private
Returns global number of health levels specified in object's config class parameter healthLevels (range is usually 0..4, 0 = pristine, 1 = worn, 2 = damaged, 3 = badly damaged, 4 = ruined but can be changed).
Parameters
zoneName if empty string, returns number of global health levels
GetOrientation()
proto native vector GetOrientation () private
Retrieve orientation (yaw, pitch, roll) in degrees
Returns
vector of yaw, pitch and roll angles (x = yaw, y = pitch, z = roll)
GetPosition()
proto native vector GetPosition () private
Retrieve position.
GetSelectionList()
proto native void GetSelectionList (out TStringArray selectionList) private
GetSelectionPositionLS()
vector GetSelectionPositionLS (string name) inline private
References GetGame(), name, and CGame::ObjectGetSelectionPositionLS().
GetSelectionPositionMS()
vector GetSelectionPositionMS (string name) inline private
References GetGame(), name, and CGame::ObjectGetSelectionPositionMS().
GetSelectionPositionOld()
vector GetSelectionPositionOld (string name) inline private
References GetGame(), name, and CGame::ObjectGetSelectionPosition().
GetSelectionPositionWS()
vector GetSelectionPositionWS (string name) inline private
References GetGame(), name, and CGame::ObjectGetSelectionPositionWS().
GetShapeName()
proto native owned string GetShapeName () private
Return path and name of the model.
GetSpeed()
proto native vector GetSpeed () private
Retrieve object's speed in global space.
GetSurfaceNoise()
float GetSurfaceNoise () inline private
Returns noise multiplier of surface under object.
References GetGame(), GetPosition, and CGame::SurfaceGetNoiseMultiplier().
GetSurfaceType()
string GetSurfaceType () inline private
Returns type of surface under object.
References GetGame(), and CGame::SurfaceUnderObject().
GetTightlyPackedCorners()
proto native void GetTightlyPackedCorners (ETransformationAxis axis, out vector corners[4]) private
Get corner positions in worldspace aligned to the orientation of the object (currently only TOP/BOTTOM supported)
Parameters
axis The axis the object is aligned to
corners array[4] of vector, each a corner aligned to the axis ({0,0}, {0,1}, {1,0}, {1,1})
Returns
true if collision box exists, false otherwise
GetType()
string GetType () inline private
Get config class of object.
References GetGame(), and CGame::ObjectGetType().
GetViewGeometryLevel()
proto native int GetViewGeometryLevel () private
GetWaterSourceObjectType()
EWaterSourceObjectType GetWaterSourceObjectType () inline private
GetWorldPosition()
proto native vector GetWorldPosition () private
Returns world position. This function takes proxy transformation into account.
HasAnimation()
bool HasAnimation (string anim_name) inline private
Searches object's config for the given animation name. Returns true if it was found, or false if not.
References GetGame(), and GetType().
HasDamageSystem()
proto native bool HasDamageSystem () private
Checks if object's DamageSystem has been initialized(despite the name, does not really reliably answer the question whether the object is configured to have damage system or not)
HasFixedActionTargetCursorPosition()
bool HasFixedActionTargetCursorPosition () inline private
HasNetworkID()
bool HasNetworkID () inline private
HasProxyParts()
bool HasProxyParts () inline private
HasSelection()
bool HasSelection (string selection) inline private
Returns true if the given selection was found in the p3d file. False if otherwise.
IsActionComponentPartOfSelection()
proto native bool IsActionComponentPartOfSelection (int componentIndex, string selectionName, string geometry = "") private
return true if selection containts action component, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
IsAlive()
bool IsAlive () inline private
IsAmmoPile()
bool IsAmmoPile () inline private
Returns if this entity is Ammo Pile.
IsAnyInherited()
bool IsAnyInherited (array< typename > typenames) inline private
IsBeingBackstabbed()
bool IsBeingBackstabbed () inline private
IsBuilding()
bool IsBuilding () inline private
Returns if this entity is Building.
IsBush()
bool IsBush () inline private
Returns if this entity is bush.
IsClothing()
bool IsClothing () inline private
Returns if this entity is Clothing.
IsContainer()
bool IsContainer () inline private
IsCorpse()
bool IsCorpse () inline private
IsCuttable()
bool IsCuttable () inline private
IsDamageDestroyed()
proto native bool IsDamageDestroyed () private
Checks if object is destroyed.
IsDayZCreature()
bool IsDayZCreature () inline private
Checks if this instance is of type DayZCreature.
IsElectricAppliance()
bool IsElectricAppliance () inline private
Returns if this is an appliance, that can be plugged into electric circuit (== not energy source)
IsEntityAI()
bool IsEntityAI () inline private
Returns if this entity is EntityAI.
IsFireplace()
bool IsFireplace () inline private
Returns if this entity is fireplacebase.
IsFood()
bool IsFood () inline private
Returns if this entity if a food item.
References IsCorpse(), IsFruit(), IsMeat(), and IsMushroom().
IsFruit()
bool IsFruit () inline private
IsFuelStation()
bool IsFuelStation () inline private
Returns if this entity is Fuel Station (extends Building)
IsHealthVisible()
bool IsHealthVisible () inline private
Returns if the health of this entity should be displayed (widgets, inventory)
IsHologram()
bool IsHologram () inline private
IsInventoryItem()
bool IsInventoryItem () inline private
Returns if this entity is InventoryItem.
IsItemBase()
bool IsItemBase () inline private
Returns if this entity is ItemBase.
IsItemTent()
bool IsItemTent () inline private
IsKindOf()
bool IsKindOf (string type) inline private
Check config class name of the object.
References GetGame(), and CGame::ObjectIsKindOf().
IsMagazine()
bool IsMagazine () inline private
Returns if this entity is Magazine.
IsMan()
bool IsMan () inline private
Returns if this entity is Man.
IsMeat()
bool IsMeat () inline private
IsMeleeWeapon()
bool IsMeleeWeapon () inline private
returns if this entity is Melee Weapon
IsMushroom()
bool IsMushroom () inline private
IsParticle()
bool IsParticle () inline private
IsPeltBase()
bool IsPeltBase () inline private
Returns if this entity is Pelt_Base.
IsPendingDeletion()
proto native bool IsPendingDeletion () private
Determine whether this object is in the deletion ProcessDirectDamage Is useful in the case where a parent is being deleted, since the children will be deleted first So to know if something was removed or detached from it's parent, use this check to see if it is because the parent is being deleted
IsPlainObject()
proto native bool IsPlainObject () private
Is this just static object without config? So we can avoid calling unnecessary methods.
IsRock()
bool IsRock () inline private
Returns if this entity is rock.
IsRuined()
bool IsRuined () inline private
Returns whether the object is ruined (0 Health).
Returns
bool true = item has 0 Health or less
if (item.IsRuined())
{
    Print("Object is ruined!");
}
IsScenery()
proto native bool IsScenery () private
Is this Scenery? (handy for excluding terain when it is not needed)
IsScriptedLight()
bool IsScriptedLight () inline private
IsStaticTransmitter()
bool IsStaticTransmitter () inline private
Returns if this entity is Static Transmitter.
IsTransmitter()
bool IsTransmitter () inline private
Returns if this entity is a non-static Transmitter.
IsTransport()
bool IsTransport () inline private
Returns if this entity is transport.
IsTree()
bool IsTree () inline private
Returns if this entity is tree.
IsWeapon()
bool IsWeapon () inline private
Returns if this entity is Weapon.
IsWell()
bool IsWell () inline private
Returns if this entity is Well (extends Building) DEPRECATED by GetWaterSourceObjectType
IsWoodBase()
bool IsWoodBase () inline private
Returns whether object is PlanBase.
KindOf()
bool KindOf (string tag) inline private
Compares config class name to given string.
References GetType().
MemoryPointExists()
proto native bool MemoryPointExists (string memoryPoint) private
ModelToWorld()
vector ModelToWorld (vector modelPos) inline private
References GetGame(), and CGame::ObjectModelToWorld().
NameOverride()
bool NameOverride (out string output) inline private
Object()
private void Object () private
OnEnterTrigger()
void OnEnterTrigger (ScriptedEntity trigger) inline private
Object entered trigger.
OnExplodeClient()
void OnExplodeClient () inline private
Called on clients when this object explodes.
References GetPosition, AmmoEffects::PlayAmmoEffect(), and AmmoEffects::PlayAmmoParticle().
OnExplosionEffects()
void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) inline private
OnLeaveTrigger()
void OnLeaveTrigger (ScriptedEntity trigger) inline private
Object left trigger.
OnPlayerRecievedHit()
void OnPlayerRecievedHit () private
DEPRECATED.
OnReceivedHit()
void OnReceivedHit (ImpactEffectsData hitData) private
OnRPC()
void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) private
Called after remote procedure call is recieved for this object.
Parameters
rpc_type user defined identification of RPC
ctx read context for params
OnSimulationDisabled()
void OnSimulationDisabled () inline private
Event called from C++ when simulation is disabled.
OnSimulationEnabled()
void OnSimulationEnabled () inline private
Event called from C++ when simulation is enabled.
OnTreeCutDown()
void OnTreeCutDown (EntityAI cutting_entity) private
Called when tree is chopped down. 'cutting_entity' can be tool, or player, if cutting bush with bare hands.
PlaceOnSurface()
proto native void PlaceOnSurface () private
Place object on surface.
PlaySound()
SoundOnVehicle PlaySound (string sound_name, float range, bool create_local = true) inline private
Plays the given sound once on this object's instance. Range is in meters. Created sound is only local, unless create_local is set to false. Returns the sound itself.
References CGame::CreateSoundOnObject(), and GetGame().
PlaySoundLoop()
SoundOnVehicle PlaySoundLoop (string sound_name, float range, bool create_local = true) inline private
Plays the given sound in loop on this object's instance. Range is in meters. Created sound is only local, unless create_local is set to false. Returns the sound itself.
References CGame::CreateSoundOnObject(), and GetGame().
PlaySoundSet()
bool PlaySoundSet (out EffectSound sound, string sound_set, float fade_in, float fade_out, bool loop = false) inline private
EffectSound - plays soundset on this object and returns state of the sound (true - played, false - not played)
References GetGame(), SEffectManager::PlaySoundOnObject(), and EffectSound::SetAutodestroy().
PlaySoundSetAtMemoryPoint()
bool PlaySoundSetAtMemoryPoint (out EffectSound sound, string soundSet, string memoryPoint, bool looped = false, float play_fade_in = 0, float stop_fade_out = 0) inline private
References ErrorEx, and SEffectManager::PlaySoundEnviroment().
PlaySoundSetAtMemoryPointLooped()
bool PlaySoundSetAtMemoryPointLooped (out EffectSound sound, string soundSet, string memoryPoint, float play_fade_in = 0, float stop_fade_out = 0) inline private
PlaySoundSetAtMemoryPointLoopedSafe()
bool PlaySoundSetAtMemoryPointLoopedSafe (out EffectSound sound, string soundSet, string memoryPoint, float play_fade_in = 0, float stop_fade_out = 0) inline private
Same as PlaySoundSetAtMemoryPointLooped, only requests stoppage of the currently playing EffectSound if it already exists and playing, before playing the new sound.
PlaySoundSetLoop()
bool PlaySoundSetLoop (out EffectSound sound, string sound_set, float fade_in, float fade_out) inline private
EffectSound - plays soundset on this object in loop and returns state of the sound (true - played, false - not played)
PostAreaDamageActions()
void PostAreaDamageActions () private
PreAreaDamageActions()
void PreAreaDamageActions () private
ProcessDirectDamage()
proto native void ProcessDirectDamage (int damageType, EntityAI source, string componentName, string ammoName, vector modelPos, float damageCoef = 1.0, int flags = 0) private
Applies damage on object.
Parameters
damageType DT_CLOSE_COMBAT/DT_FIRE_ARM/DT_EXPLOSION/DT_CUSTOM
source source of damage
componentName which 'DamageZone' was hit (NOT a component name, actually!)
ammoName ammoType, which defines how much damage should be applied
directHitModelPos local position of hit
damageCoef multiplier of applied damage
flags enables/disables special behaviour depending on the flags used (ProcessDirectDamageFlags type)
ProcessMeleeItemDamage()
EntityAI ProcessMeleeItemDamage (int mode = 0) inline private
Release()
int Release () inline private
References GetGame(), and CGame::ObjectRelease().
RemoveProxyPhysics()
proto native void RemoveProxyPhysics (string proxySelectionName) private
RPC()
void RPC (int rpc_type, array< ref Param > params, bool guaranteed, PlayerIdentity recipient = NULL) inline private
Remote procedure call shortcut, see CGame.RPC / CGame.RPCSingleParam.
References GetGame(), and CGame::RPC().
RPCSingleParam()
void RPCSingleParam (int rpc_type, Param param, bool guaranteed, PlayerIdentity recipient = NULL) inline private
Remote procedure call shortcut, see CGame.RPCSingleParam / CGame.RPC.
References GetGame(), and CGame::RPCSingleParam().
SetAffectPathgraph()
proto native void SetAffectPathgraph (bool fromConfig, bool affect) private
Sets if object's geometry affects pathgraph generation. If first parameter is true, it ignores second parameter and sets affecting pathgraph by parameter set in object's config.
SetAllowDamage()
proto native void SetAllowDamage (bool val) private
Enable or disable object to receive damage.
Parameters
enable or disable
SetBeingBackstabbed()
void SetBeingBackstabbed (int backstabType) inline private
SetCanBeDestroyed()
proto native void SetCanBeDestroyed (bool val) private
Enable or disable destruction of object (after health is depleated)
Parameters
enable or disable
SetDestructTime()
proto native void SetDestructTime (float time) private
Sets the time over which to perform DestructTent/DestructTree.
Parameters
time time over which to perform DestructTent/DestructTree
SetDirection()
proto native void SetDirection (vector vPos) private
Set direction of object.
Parameters
vDirection,direction vector
Note
object up vector is always y-axis
SetDynamicPhysicsLifeTime()
proto native void SetDynamicPhysicsLifeTime (float lifeTime) private
SetFullHealth()
proto native void SetFullHealth () private
Sets full health to all zones and removes fatal damage when applicable.
SetGlobalHealth()
void SetGlobalHealth (float health) inline private
Equivalent of SetHealth("", "", float value);.
SetHealth() [1/2]
void SetHealth (float health) inline private
Equivalent of SetHealth("", "", float value);.
SetHealth() [2/2]
proto native void SetHealth (string zoneName, string healthType, float value) private
Sets current state of health.
Parameters
zoneName if empty string, sets state of global health
healthType if empty string, sets state of main health
SetHealth01()
void SetHealth01 (string zoneName, string healthType, float coef) inline private
Sets health relative to its maximum.
SetHealthLevel()
void SetHealthLevel (int healthLevel, string zone = "") inline private
Sets specific health level. It will use the cutoff value as returned by 'GetHealthLevelValue' as the health value for the given health level, which means it will always be set to the max health as allowed by the given health level.
SetHealthMax()
void SetHealthMax (string zoneName = "", string healthType = "") inline private
Sets health to its maximum (zone or global)
SetOrientation()
proto native void SetOrientation (vector vOrientation) private
Set orientation (yaw, pitch, roll) in degrees
Parameters
vOrientation,vector of yaw, pitch and roll angles (x = yaw, y = pitch, z = roll)
SetPosition()
proto native void SetPosition (vector vPos) private
Set position.
ShootsExplosiveAmmo()
bool ShootsExplosiveAmmo () inline private
Returns if this entity is a weapon which can shoot explosive ammo.
ShowZonesHealth()
bool ShowZonesHealth () inline private
Returns true if the health of damage zones should be displayed (instead of global HP of the entity) (action widgets)
SpawnDamageDealtEffect()
void SpawnDamageDealtEffect () private
StopSoundSet()
bool StopSoundSet (out EffectSound sound) inline private
EffectSound - stops soundset and returns state of the sound (true - stopped, false - not playing)
References GetGame().
SynchExplosion()
void SynchExplosion () inline private
References GetGame(), and CGame::RPCSingleParam().
ToDelete()
proto native bool ToDelete () private
Flag to determine this object is marked to be deleted soon.
WorldToModel()
vector WorldToModel (vector worldPos) inline private
References GetGame(), and CGame::ObjectWorldToModel().
The documentation for this class was generated from the following files:
P:/scripts/1_Core/proto/EnEntity.c
P:/scripts/3_Game/Entities/Object.c