DayZ Scripts: CABase Class Reference
CABase Class Reference
Private Member Functions
void Init (ActionData action_data)
void Setup (ActionData action_data)
int Execute (ActionData action_data)
int Cancel (ActionData action_data)
int Interrupt (ActionData action_data)
void SetACData (Param units)
Param GetACData ()
bool IsContinuousAction ()
float GetProgress ()
Private Attributes
protected ActionBase m_Action
protected float m_LastTick
protected ref Param m_ACData
protected ref Param2< float, float > m_ProgressParam
Detailed Description
Definition at line 1 of file CABase.c.
Member Function Documentation
Cancel()
int Cancel (ActionData action_data) inline private
Definition at line 29 of file CABase.c.
References UA_CANCEL.
Referenced by ActionContinuousBaseCB::UserEndsAction().
Execute()
int Execute (ActionData action_data) inline private
Definition at line 24 of file CABase.c.
References UA_ERROR.
Referenced by ActionBaseCB::ProgressActionComponent().
GetACData()
Param GetACData () inline private
Definition at line 48 of file CABase.c.
References m_ACData.
Referenced by ActionCollectBloodSelf::OnEndServer(), ActionCollectBloodTarget::OnEndServer(), ActionCollectSampleSelf::OnEndServer(), ActionCollectSampleTarget::OnEndServer(), ActionDisinfectPlantBit::OnExecuteServer(), ActionRepairWithToolFromHands::OnExecuteServer(), ActionDisinfectPlant::OnFinishProgressClient(), ActionWaterPlant::OnFinishProgressClient(), ActionDisinfectPlant::OnFinishProgressServer(), OnFinishProgressServer(), ActionWaterPlant::OnFinishProgressServer(), ActionGiveSalineSelf::OnFinishProgressServer(), and ActionGiveSalineTarget::OnFinishProgressServer().
GetProgress()
float GetProgress () inline private
Definition at line 62 of file CABase.c.
Referenced by ActionBaseCB::GetActionComponentProgress(), and AnimatedActionBase::GetProgress().
Init()
void Init (ActionData action_data) inline private
Definition at line 8 of file CABase.c.
References GetGame(), CGame::GetTime(), m_ACData, ActionData::m_Action, m_Action, m_LastTick, m_ProgressParam, and Setup().
Referenced by ActionContinuousBaseCB::InitActionComponent(), ActionInteractBaseCB::InitActionComponent(), and ActionSingleUseBaseCB::InitActionComponent().
Interrupt()
int Interrupt (ActionData action_data) inline private
Definition at line 34 of file CABase.c.
References Cancel(), and UA_INTERRUPT.
Referenced by ActionUnfoldMapCB::OnFinish(), and ActionBaseCB::OnFinish().
IsContinuousAction()
bool IsContinuousAction () inline private
Definition at line 57 of file CABase.c.
SetACData()
void SetACData (Param units) inline private
Definition at line 40 of file CABase.c.
References m_ACData.
Referenced by CAContinuousEmpty::CalcAndSetQuantity(), CAContinuousEmptyMagazine::CalcAndSetQuantity(), CAContinuousFill::CalcAndSetQuantity(), CAContinuousFillBrakes::CalcAndSetQuantity(), CAContinuousFillCoolant::CalcAndSetQuantity(), CAContinuousFillFuel::CalcAndSetQuantity(), CAContinuousFillOil::CalcAndSetQuantity(), CAContinuousFillPowerGenerator::CalcAndSetQuantity(), CAContinuousQuantity::CalcAndSetQuantity(), CAContinuousQuantityBloodTransfer::CalcAndSetQuantity(), CAContinuousQuantityEdible::CalcAndSetQuantity(), CAContinuousQuantityExtinguish::CalcAndSetQuantity(), CAContinuousQuantityLiquidTransfer::CalcAndSetQuantity(), CAContinuousQuantityRepeat::CalcAndSetQuantity(), CAContinuousTransferQuantity::CalcAndSetQuantity(), CASingleUseQuantity::CalcAndSetQuantity(), CASingleUseQuantityEdible::CalcAndSetQuantity(), CAContinuousRepeat::Cancel(), CAContinuousTime::Cancel(), CAContinuousCraft::Execute(), CAContinuousMineWood::Execute(), CAContinuousRepeat::Execute(), CAContinuousRepeatFishing::Execute(), CAContinuousRepeatStartEngine::Execute(), CAContinuousTime::Execute(), CAContinuousTimeCooking::Execute(), CAContinuousWringClothes::Execute(), and CAInteractLoop::Execute().
Setup()
void Setup (ActionData action_data) inline private
Definition at line 20 of file CABase.c.
Referenced by Init().
Field Documentation
m_ACData
protected ref Param m_ACData private
Definition at line 5 of file CABase.c.
Referenced by GetACData(), Init(), and SetACData().
m_Action
protected ActionBase m_Action private
Definition at line 3 of file CABase.c.
Referenced by CAContinuousDisinfectPlant::Execute(), CAContinuousFertilizeGardenSlot::Execute(), CAContinuousFillBrakes::Execute(), CAContinuousFillCoolant::Execute(), CAContinuousFillFuel::Execute(), CAContinuousFillOil::Execute(), CAContinuousQuantity::Execute(), CAContinuousQuantityLiquidTransfer::Execute(), CAContinuousQuantityRepeat::Execute(), CAContinuousTimeCooking::Execute(), CAContinuousTransferQuantity::Execute(), CAContinuousWaterPlant::Execute(), CAContinuousWaterSlot::Execute(), CAContinuousWringClothes::Execute(), CAContinuousMineRock::GetMiningData(), CAContinuousMineWood::GetMiningData(), Init(), CAContinuousEmpty::Setup(), CAContinuousFill::Setup(), CAContinuousFillPowerGenerator::Setup(), CAContinuousMineWood::Setup(), CAContinuousRepeat::Setup(), CAContinuousTime::Setup(), CAContinuousTimeCooking::Setup(), and CAInteractLoop::Setup().
m_LastTick
protected float m_LastTick private
Definition at line 4 of file CABase.c.
Referenced by Init().
m_ProgressParam
protected ref Param2<float,float> m_ProgressParam private
Definition at line 6 of file CABase.c.
Referenced by Init().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionComponents/CABase.c