DayZ Scripts: AttachmentCategoriesSlotsContainer Class Reference
AttachmentCategoriesSlotsContainer Class Reference
Private Member Functions
void AttachmentCategoriesSlotsContainer (LayoutHolder parent, int index)
override bool IsDisplayable ()
override void SetLayoutName ()
SlotsContainer GetSlotsContainer ()
override EntityAI GetFocusedItem ()
int GetParentID ()
int GetFocusedID ()
void ExpandCollapseContainer (bool expand)
override bool SelectItem ()
override bool Select ()
override bool Combine ()
override bool TransferItemToVicinity ()
override bool TransferItem ()
override bool SplitItem ()
override bool EquipItem ()
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool IsEmpty ()
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
string GetAttachmentCategory (string config_path_attachment_categories, int i)
string GetIconName (string config_path_attachment_categories, string attachment_category)
Private Attributes
ref SlotsContainer m_ItemsCont
Detailed Description
Definition at line 1 of file AttachmentCategoriesSlotsContainer.c.
Constructor & Destructor Documentation
AttachmentCategoriesSlotsContainer()
void AttachmentCategoriesSlotsContainer (LayoutHolder parent, int index) inline private
Definition at line 5 of file AttachmentCategoriesSlotsContainer.c.
References WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), SlotsContainer::GetSlotIcon(), ITEMS_IN_ROW, m_ItemsCont, m_Parent, WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnMouseButtonDown(), WidgetEventHandler::RegisterOnMouseEnter(), and WidgetEventHandler::RegisterOnMouseLeave().
Member Function Documentation
CanCombine()
override bool CanCombine () inline private
Definition at line 107 of file AttachmentCategoriesSlotsContainer.c.
CanCombineAmmo()
override bool CanCombineAmmo () inline private
Definition at line 112 of file AttachmentCategoriesSlotsContainer.c.
Combine()
override bool Combine () inline private
Definition at line 82 of file AttachmentCategoriesSlotsContainer.c.
EquipItem()
override bool EquipItem () inline private
Definition at line 102 of file AttachmentCategoriesSlotsContainer.c.
ExpandCollapseContainer()
void ExpandCollapseContainer (bool expand) inline private
Definition at line 66 of file AttachmentCategoriesSlotsContainer.c.
References SlotsContainer::GetFocusedSlotsIcon(), SlotsIcon::GetRadialIcon(), SlotsIcon::GetRadialIconClosed(), and m_ItemsCont.
GetAttachmentCategory()
string GetAttachmentCategory (string config_path_attachment_categories, int i) inline private
Definition at line 132 of file AttachmentCategoriesSlotsContainer.c.
References CGame::ConfigGetChildName(), and GetGame().
GetFocusedID()
int GetFocusedID () inline private
Definition at line 61 of file AttachmentCategoriesSlotsContainer.c.
References SlotsContainer::GetFocusedSlotsIcon(), and m_ItemsCont.
GetFocusedItem()
override EntityAI GetFocusedItem () inline private
Definition at line 51 of file AttachmentCategoriesSlotsContainer.c.
References SlotsContainer::GetFocusedSlotsIcon(), ItemPreviewWidget::GetItem(), SlotsIcon::GetRender(), and m_ItemsCont.
GetIconName()
string GetIconName (string config_path_attachment_categories, string attachment_category) inline private
Definition at line 139 of file AttachmentCategoriesSlotsContainer.c.
References CGame::ConfigGetText(), and GetGame().
GetParentID()
int GetParentID () inline private
Definition at line 56 of file AttachmentCategoriesSlotsContainer.c.
References m_ItemsCont.
GetSlotsContainer()
SlotsContainer GetSlotsContainer () inline private
Definition at line 46 of file AttachmentCategoriesSlotsContainer.c.
References m_ItemsCont.
Referenced by AttachmentCategoriesContainer::GetSlotsContainer().
IsDisplayable()
override bool IsDisplayable () inline private
Definition at line 30 of file AttachmentCategoriesSlotsContainer.c.
Referenced by AttachmentCategoriesContainer::UpdateInterval().
IsEmpty()
override bool IsEmpty () inline private
Definition at line 117 of file AttachmentCategoriesSlotsContainer.c.
IsItemActive()
override bool IsItemActive () inline private
Definition at line 122 of file AttachmentCategoriesSlotsContainer.c.
IsItemWithQuantityActive()
override bool IsItemWithQuantityActive () inline private
Definition at line 127 of file AttachmentCategoriesSlotsContainer.c.
Select()
override bool Select () inline private
Definition at line 77 of file AttachmentCategoriesSlotsContainer.c.
SelectItem()
override bool SelectItem () inline private
Definition at line 72 of file AttachmentCategoriesSlotsContainer.c.
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 41 of file AttachmentCategoriesSlotsContainer.c.
References WidgetLayoutName::Container.
SplitItem()
override bool SplitItem () inline private
Definition at line 97 of file AttachmentCategoriesSlotsContainer.c.
TransferItem()
override bool TransferItem () inline private
Definition at line 92 of file AttachmentCategoriesSlotsContainer.c.
TransferItemToVicinity()
override bool TransferItemToVicinity () inline private
Definition at line 87 of file AttachmentCategoriesSlotsContainer.c.
Field Documentation
m_ItemsCont
ref SlotsContainer m_ItemsCont private
Definition at line 3 of file AttachmentCategoriesSlotsContainer.c.
Referenced by AttachmentCategoriesSlotsContainer(), ExpandCollapseContainer(), GetFocusedID(), GetFocusedItem(), GetParentID(), and GetSlotsContainer().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Inherited/AttachmentCategoriesSlotsContainer.c