DayZ Scripts: HumanCommandActionCallback Class Reference
HumanCommandActionCallback Class Reference
Private Member Functions
override void OnFinish (bool pCanceled)
void Init (float run_time, PlayerBase player)
bool CancelCondition ()
override bool IsSymptomCallback ()
void PluginDayzPlayerActionCallback ()
void ~PluginDayzPlayerActionCallback ()
override void OnFinish (bool pCanceled)
bool CancelCondition ()
override void OnAnimationEvent (int pEventID)
override void OnStateChange (int pOldState, int pCurrentState)
Private Attributes
float m_RunTime
float m_StartingTime
PlayerBase m_Player
float m_fTimeStart
TextWidget m_pStateWidget
TextWidget m_pAnimEventWidget
Detailed Description
Definition at line 1 of file StateCB.c.
Constructor & Destructor Documentation
~PluginDayzPlayerActionCallback()
void ~PluginDayzPlayerActionCallback () inline private
Definition at line 71 of file PluginDayzPlayerDebug.c.
References Print().
Member Function Documentation
CancelCondition() [1/2]
bool CancelCondition () inline private
Definition at line 30 of file StateCB.c.
References GetGame(), and GetTime().
CancelCondition() [2/2]
bool CancelCondition () inline private
Definition at line 89 of file PluginDayzPlayerDebug.c.
References DefaultCancelCondition().
Init()
void Init (float run_time, PlayerBase player) inline private
Definition at line 17 of file StateCB.c.
References EnableCancelCondition(), GetGame(), CGame::GetTime(), and m_Player.
IsSymptomCallback()
override bool IsSymptomCallback () inline private
Definition at line 42 of file StateCB.c.
OnAnimationEvent()
override void OnAnimationEvent (int pEventID) inline private
Definition at line 95 of file PluginDayzPlayerDebug.c.
References GetWorldTime(), m_fTimeStart, and float::ToString().
OnFinish() [1/2]
override void OnFinish (bool pCanceled) inline private
Definition at line 8 of file StateCB.c.
References m_Player.
OnFinish() [2/2]
override void OnFinish (bool pCanceled) inline private
Definition at line 76 of file PluginDayzPlayerDebug.c.
OnStateChange()
override void OnStateChange (int pOldState, int pCurrentState) inline private
Definition at line 105 of file PluginDayzPlayerDebug.c.
References GetStateString().
PluginDayzPlayerActionCallback()
void PluginDayzPlayerActionCallback () inline private
Definition at line 61 of file PluginDayzPlayerDebug.c.
Field Documentation
m_fTimeStart
float m_fTimeStart private
Definition at line 116 of file PluginDayzPlayerDebug.c.
Referenced by OnAnimationEvent().
m_pAnimEventWidget
TextWidget m_pAnimEventWidget private
Definition at line 118 of file PluginDayzPlayerDebug.c.
m_Player
PlayerBase m_Player private
Definition at line 6 of file StateCB.c.
m_pStateWidget
TextWidget m_pStateWidget private
Definition at line 117 of file PluginDayzPlayerDebug.c.
m_RunTime
float m_RunTime private
Definition at line 4 of file StateCB.c.
m_StartingTime
float m_StartingTime private
Definition at line 5 of file StateCB.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/PlayerSymptoms/StateCB.c
P:/scripts/4_World/Plugins/PluginBase/PluginDayzPlayerDebug.c