DayZ Scripts: SEffectManager Class Reference
SEffectManager Class Reference
Manager class for managing Effect (EffectParticle, EffectSound)
Static Private Member Functions
Generic playback
Methods for playing Effect
Note
Since 1.15, these should work on EffectSound as well
static int PlayInWorld (notnull Effect eff, vector pos)
Play an Effect.
static int PlayOnObject (notnull Effect eff, Object obj, vector local_pos="0 0 0", vector local_ori="0 0 0", bool force_rotation_relative_to_world=false)
Play an Effect.
static void Stop (int effect_id)
Stops the Effect.
Create/Play sound
Methods for playing/creating sound
static EffectSound CreateSound (string sound_set, vector position, float play_fade_in=0, float stop_fade_out=0, bool loop=false, bool enviroment=false)
Create an EffectSound.
static EffectSound PlaySound (string sound_set, vector position, float play_fade_in=0, float stop_fade_out=0, bool loop=false)
Create and play an EffectSound.
static EffectSound PlaySoundParams (notnull SoundParams params, vector position, float play_fade_in=0, float stop_fade_out=0, bool loop=false)
Create and play an EffectSound.
static EffectSound PlaySoundCachedParams (string sound_set, vector position, float play_fade_in=0, float stop_fade_out=0, bool loop=false)
Create and play an EffectSound, using or creating cached SoundParams.
static EffectSound PlaySoundEnviroment (string sound_set, vector position, float play_fade_in=0, float stop_fade_out=0, bool loop=false)
Create and play an EffectSound, updating environment variables.
static EffectSound PlaySoundOnObject (string sound_set, Object parent_object, float play_fade_in=0, float stop_fade_out=0, bool loop=false)
Create and play an EffectSound.
Generic API
General methods used for SEffectManager
static void DestroyEffect (Effect effect)
Unregisters, stops and frees the Effect.
static bool IsEffectExist (int effect_id)
Checks whether an Effect ID is registered in SEffectManager.
static Effect GetEffectByID (int effect_id)
Gets the Effect with the given registered Effect ID.
static int EffectRegister (Effect effect)
Registers Effect in SEffectManager.
static protected int GetFreeEffecterID ()
static void EffectUnregister (int id)
Unregisters Effect in SEffectManager.
static void EffectUnregisterEx (Effect effect)
Unregisters Effect in SEffectManager.
static protected int GetFreeEffectID ()
Helper function for EffectRegister to decide an Effect ID.
Sound helpers
Sound specific helper methods
static bool DestroySound (EffectSound sound_effect)
Legacy, backwards compatibility.
static SoundParams GetCachedSoundParam (string soundset)
Get or create a cached SoundParams object.
Events
Various events that can be overriden for custom behaviour
static void Event_OnSoundWaveEnded (EffectSound effect_sound)
Event called from EffectSound.Event_OnSoundWaveEnded.
static void Event_OnFrameUpdate (float time_delta)
Event called on frame.
Lifetime
Creation and cleanup
static void Init ()
Initialize the containers.
static void InitServer ()
static void Cleanup ()
Cleanup method to properly clean up the static data.
static int CreateParticleServer (vector pos, EffecterParameters parameters)
returns unique effecter ID
static void ReinitParticleServer (int effecterID, EffecterParameters parameters)
allows re-initializing existing effecter with new parameters (extept m_EffecterType, obviously)
static void ReactivateParticleServer (int effecterID)
static void StartParticleServer (int effecterID)
static void StopParticleServer (int effecterID)
static void DestroyEffecterParticleServer (int effecterID)
static void OnUpdate (float timeslice)
Static Private Attributes
static protected ref map< int, ref Effect > m_EffectsMap
Static map of all registered effects <id, Effect>
static protected ref array< int > m_FreeEffectIDs
Static array of IDs that were previously used, but freed up by unregistering.
static protected int m_HighestFreeEffectID = 1
Counter for quickly getting the next ID if FreeEffectIDs array is empty.
static const int INVALID_ID = 0
As the counter starts at 1, Effect ID can never be 0.
static protected bool m_IsCleanup
Bool to check whether Cleanup is happening, which means that the maps should no longer be accessed.
static protected bool m_IsInitialized
Bool to check whether Init was called.
static protected ref map< string, ref SoundParams > m_ParamsMap
Static map of cached sound params, to prevent having to recreate them.
static ref ScriptInvoker Event_OnFrameUpdate
Static invoker for the SEffectManager.Event_OnFrameUpdate called form MissionGameplay.OnUpdate.
static protected ref map< int, EffecterBase > m_EffectersMap
static protected ref array< int > m_FreeEffecterIDs
Static array of IDs that were previously used, but freed up by unregistering Effecters.
static protected int m_HighestFreeEffecterID = 1
Detailed Description
Manager class for managing Effect (EffectParticle, EffectSound)
Warning
Keeps a ref to any Effect registered (Created/Played), make sure to perform the necessary cleanup
Member Function Documentation
Cleanup()
static void Cleanup () inline static private
Cleanup method to properly clean up the static data.
Note
Will be called when MissionBase is destroyed
References ScriptInvoker::Clear(), Effect(), EffecterBase(), ErrorEx, Event_OnFrameUpdate, GetGame(), m_EffectersMap, m_EffectsMap, m_HighestFreeEffectID, m_IsCleanup, m_IsInitialized, m_ParamsMap, and Print().
Referenced by MissionBaseWorld::MissionBase(), and CGame::~CGame().
CreateParticleServer()
static int CreateParticleServer (vector pos, EffecterParameters parameters) inline static private
returns unique effecter ID
References ECE_PLACE_ON_SURFACE, EffecterBase(), GetFreeEffecterID(), GetGame(), and m_EffectersMap.
Referenced by ItemBase::PlayCatchParticleSynced(), and ActionFishingNew::PlaySplashEffectSynced().
CreateSound()
static EffectSound CreateSound (string sound_set, vector position, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false, bool enviroment = false) inline static private
Create an EffectSound.
Warning
Read PlayInWorld warning
Parameters
sound_set string The sound set name of the sound
position vector The position to play the sound
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
enviroment bool Whether to set environment variables (Optional)
Returns
EffectSound The created EffectSound
References EffectRegister(), EffectSound::SetEnviromentVariables(), EffectSound::SetSoundFadeIn(), EffectSound::SetSoundFadeOut(), EffectSound::SetSoundLoop(), and EffectSound::SetSoundSet().
Referenced by BoatScript::HandleBoatSplashSound(), HandleEngineSound(), FlashbangEffect::PlaySound(), PlaySound(), PlaySoundCachedParams(), PlaySoundEnviroment(), PlaySoundOnObject(), PlaySoundParams(), and UpdateMusic().
DestroyEffect()
static void DestroyEffect (Effect effect) inline static private
Unregisters, stops and frees the Effect.
Parameters
effect_sound EffectSound The EffectSound to free
Referenced by BoatScript::CleanupEffects(), CleanupEffects(), CleanupSound(), Destroy(), ActionBuildShelter::DestroyActionLoopSound(), DestroySound(), EEDelete(), Roadflare::EEDelete(), ManBase::EEDelete(), House::EEDelete(), OnRingingStartClient(), OnRingingStopClient(), InventoryItem::OnRPC(), OnVariablesSynchronized(), ItemBase::OnWorkStop(), RemoveParticle(), ManBase::SetDecayEffects(), FlashbangEffect::StopSound(), KitchenTimer::TurnOff(), ~Bottle_Base(), ~ClockBase(), DayZIntroSceneXbox::~DayZIntroSceneXbox(), ItemBase::~Defibrillator(), DestructionEffectBase::~DestructionEffectBase(), FireworksLauncher::~FireworksLauncher(), FireworksLauncherClientEvent::~FireworksLauncherClientEvent(), FlashbangEffect::~FlashbangEffect(), InventoryItem::~ItemBase(), ~LandMineTrap(), ~LargeTent(), Backpack_Base::~LargeTentBackPack(), ParticleEffecter::~ParticleEffecter(), ManBase::~PlayerBase(), ItemBase::~PowerGeneratorBase(), and ~TreeEffecter().
DestroyEffecterParticleServer()
static void DestroyEffecterParticleServer (int effecterID) inline static private
References EffecterBase(), and m_EffectersMap.
Referenced by DecreaseLifespan(), ActionFishingNewCB::DestroySplashEffectSynced(), OnEndServer(), and ItemBase::SetActive().
DestroySound()
static bool DestroySound (EffectSound sound_effect) inline static private
Legacy, backwards compatibility.
Parameters
sound_effect EffectSound The EffectSound to free
Returns
bool A bool which is always true
References DestroyEffect().
Referenced by CleanSoundEffects(), CleanUpOnClosedClient(), and Land_Underground_Stairs_Exit::CleanUpOnClosedClient().
EffectRegister()
static int EffectRegister (Effect effect) inline static private
Registers Effect in SEffectManager.
Note
Already handled in SEffectManager Create/Play methods
This will make SEffectManager hold a strong ref for the Effect
Parameters
effect Effect The Effect to register
Returns
int The Effect ID
References ErrorEx, GetFreeEffectID(), m_EffectsMap, and m_IsCleanup.
Referenced by CreateSound(), PlayInWorld(), and PlayOnObject().
EffectUnregister()
static void EffectUnregister (int id) inline static private
Unregisters Effect in SEffectManager.
Note
Will automatically occur on stop when the Effect is AutoDestroy
ID can be gotten from the Effect by calling Effect.GetID
Generic Play methods will also return the ID
Parameters
id int The ID of the Effect to unregister
References Effect(), m_EffectsMap, m_FreeEffectIDs, and m_IsCleanup.
Referenced by EffectUnregisterEx(), and ~Effect().
EffectUnregisterEx()
static void EffectUnregisterEx (Effect effect) inline static private
Unregisters Effect in SEffectManager.
Parameters
effect Effect The Effect to unregister
References EffectUnregister().
Referenced by BoatScript::CleanupEffects().
Event_OnFrameUpdate()
static void Event_OnFrameUpdate (float time_delta) inline static private
Event called on frame.
Note
Called from MissionGameplay.OnUpdate
Effects register themselves by Effect.SetEnableEventFrame(true)
EffectSound is automatically registered
Parameters
time_delta float Time passed since the previous frame
References Event_OnFrameUpdate, and ScriptInvoker::Invoke().
Event_OnSoundWaveEnded()
static void Event_OnSoundWaveEnded (EffectSound effect_sound) inline static private
Event called from EffectSound.Event_OnSoundWaveEnded.
Note
Every registered sound is registered to call this
Parameters
effect_sound EffectSound The EffectSound calling the event
Referenced by EffectSound::Event_OnRegistered(), and EffectSound::Event_OnUnregistered().
GetCachedSoundParam()
static SoundParams GetCachedSoundParam (string soundset) inline static private
Get or create a cached SoundParams object.
Parameters
soundset string The sound set name of the sound
Returns
SoundParams The cached SoundParams for the given soundset
References m_ParamsMap.
Referenced by PlaySoundCachedParams().
GetEffectByID()
static Effect GetEffectByID (int effect_id) inline static private
Gets the Effect with the given registered Effect ID.
Parameters
effect_id int The Effect ID
Returns
Effect The Effect registered to the ID or null
References m_EffectsMap, and m_IsCleanup.
GetFreeEffecterID()
static protected int GetFreeEffecterID () inline static private
References m_FreeEffecterIDs, and m_HighestFreeEffecterID.
Referenced by CreateParticleServer().
GetFreeEffectID()
static protected int GetFreeEffectID () inline static private
Helper function for EffectRegister to decide an Effect ID.
Returns
int A currently unused Effect ID
References m_FreeEffectIDs, and m_HighestFreeEffectID.
Referenced by EffectRegister().
Init()
static void Init () inline static private
Initialize the containers.
Note
This is done this way, to have these not exist on server
References Event_OnFrameUpdate, m_EffectsMap, m_FreeEffectIDs, m_IsInitialized, and m_ParamsMap.
Referenced by CGame::CGame().
InitServer()
static void InitServer () inline static private
References m_EffectersMap, and m_FreeEffecterIDs.
Referenced by CGame::CGame().
IsEffectExist()
static bool IsEffectExist (int effect_id) inline static private
Checks whether an Effect ID is registered in SEffectManager.
Parameters
effect_id int The Effect ID to check
Returns
bool Whether there is an Effect registered for this ID
References m_EffectsMap, and m_IsCleanup.
Referenced by CreateCarDestroyedEffect(), EOnPostSimulate(), and ManBase::SetDecayEffects().
OnUpdate()
static void OnUpdate (float timeslice) inline static private
References EffecterBase(), and m_EffectersMap.
Referenced by CGame::OnUpdate().
PlayInWorld()
static int PlayInWorld (notnull Effect eff, vector pos) inline static private
Play an Effect.
Warning
As the Effect is automatically registered, it will not be freed automatically (because of the ref) Unless 'SetAutodestroy(true)' is called on the created 'Effect', which will clean it up when the sound stop Alternatively, SEffectManager.DestroyEffect can be called manually, which will also unregister and cleanup
Parameters
eff Effect The Effect to play
pos vector The position to play the Effect
Returns
int The registered ID of the Effect
References EffectRegister().
Referenced by Hit_MeatBones::BloodSplatGround(), CreateParticle(), ImpactMaterials::EvaluateImpactEffect(), ManBase::OnParticleEvent(), ParticleEffecter::OnVariablesSynchronized(), OnVariablesSynchronized(), AmmoEffects::PlayAmmoEffect(), BleedingSourcesManagerBase::SetDiag(), DayZIntroSceneXbox::SetupParticles(), and Explosion::SpawnEffect().
PlayOnObject()
static int PlayOnObject (notnull Effect eff, Object obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0", bool force_rotation_relative_to_world = false) inline static private
Play an Effect.
Warning
Read PlayInWorld warning
Parameters
eff Effect The Effect to play
obj Object The parent of the Effect
local_pos vector The local position to play the Effect in relation to the parent (Optional)
local_ori vector The local orientation to play the Effect in relation to the parent (Optional)
force_rotation_relative_to_world bool Whether to force the orientation to stay in WS (Optional)
Returns
int The registered ID of the Effect
References EffectRegister(), ErrorEx, and EffectParticle::ForceParticleRotationRelativeToWorld().
Referenced by CreateCarDestroyedEffect(), EOnPostSimulate(), ManBase::SetDecayEffects(), and ItemBase::StartLoopSound().
PlaySound()
static EffectSound PlaySound (string sound_set, vector position, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false) inline static private
Create and play an EffectSound.
Warning
Calls CreateSound, read CreateSound warning
Parameters
sound_set string The sound set name of the sound
position vector The position to play the sound
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
Returns
EffectSound The created EffectSound
References CreateSound(), and EffectSound::SoundPlay().
Referenced by CGame::DelayedMidAirDetonation(), House::EEInit(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), HandleDoorsSound(), HandleEngineSound(), BoatScript::HandleEngineSound(), HandleSeatAdjustmentSound(), CarScript::OnAnimationPhaseStarted(), Weapon::OnFireModeChange(), InventoryItem::OnRPC(), CGame::OnRPC(), OnSteppedOn(), InventoryItemSuper::OnWasAttached(), InventoryItemSuper::OnWasDetached(), SpookyEventBase::Perform(), ActionBuildShelter::PlayActionFinishSound(), ActionBuildShelter::PlayActionLoopSound(), ActionBuildShelter::PlayActionStartSound(), InventoryItem::PlayAttachSound(), InventoryItem::PlayDeployFinishSound(), InventoryItem::PlayDeployLoopSoundEx(), InventoryItem::PlayDeploySound(), PlayDisarmingLoopSound(), InventoryItem::PlayPlaceSound(), PlayRepackingLoopSound(), Backpack_Base::PlayRepackingLoopSound(), PlaySoundActivate(), TrapBase::PlaySoundBiteEmpty(), TrapBase::PlaySoundBiteLeg(), TrapBase::PlaySoundOpen(), Barrel_ColorBase::SoundBarrelClosePlay(), FireplaceBase::SoundBarrelClosePlay(), Barrel_ColorBase::SoundBarrelOpenPlay(), FireplaceBase::SoundBarrelOpenPlay(), Edible_Base::SoundCookingStart(), Entity::SoundHardBushFallingPlay(), Entity::SoundHardTreeFallingPlay(), Entity::SoundSoftBushFallingPlay(), Entity::SoundSoftTreeFallingPlay(), ItemBase::SoundTentClosePlay(), ItemBase::SoundTentCloseWindowPlay(), ItemBase::SoundTentOpenPlay(), ItemBase::SoundTentOpenWindowPlay(), StartActivate(), and GeyserTrigger::UpdateGeyserState().
PlaySoundCachedParams()
static EffectSound PlaySoundCachedParams (string sound_set, vector position, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false) inline static private
Create and play an EffectSound, using or creating cached SoundParams.
Warning
Calls CreateSound, read CreateSound warning
Parameters
sound_set string The sound set name of the sound
position vector The position to play the sound
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
Returns
EffectSound The created EffectSound
References CreateSound(), GetCachedSoundParam(), SoundParams::GetName(), and EffectSound::SoundPlayEx().
Referenced by Land_WarheadStorage_PowerStation::OnVariablesSynchronized(), BoatScript::PlaySound(), and PlaySoundEx().
PlaySoundEnviroment()
static EffectSound PlaySoundEnviroment (string sound_set, vector position, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false) inline static private
Create and play an EffectSound, updating environment variables.
Warning
Calls CreateSound, read CreateSound warning
Parameters
sound_set string The sound set name of the sound
position vector The position to play the sound
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
Returns
EffectSound The created EffectSound
References CreateSound(), and EffectSound::SoundPlay().
Referenced by ScriptConsoleSoundsTab::HandleKeys(), ScriptConsoleSoundsTab::OnClick(), ItemBase::PlayCatchSound(), and IEntity::PlaySoundSetAtMemoryPoint().
PlaySoundOnObject()
static EffectSound PlaySoundOnObject (string sound_set, Object parent_object, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false) inline static private
Create and play an EffectSound.
Warning
Calls CreateSound, read CreateSound warning
Parameters
sound_set string The sound set name of the sound
parent_object Object The parent Object for the sound to follow
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
Returns
EffectSound The created EffectSound
References CreateSound(), EffectSound::SetParent(), EffectSound::SoundPlay(), and vector::Zero.
Referenced by ItemBase::DischargeClient(), ManBase::EEHitByRemote(), ManBase::OnBleedingSourceAdded(), ItemBase::OnIsCharged(), ManBase::OnPlayerRecievedHit(), ItemBase::OnWorkStart(), PlayEmptyingLoopSound(), PlayPouringLoopSound(), PlaySound(), IEntity::PlaySoundSet(), and StopEmptyingLoopSound().
PlaySoundParams()
static EffectSound PlaySoundParams (notnull SoundParams params, vector position, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false) inline static private
Create and play an EffectSound.
Warning
Calls CreateSound, read CreateSound warning
Parameters
params SoundParams Params to create the sound with
position vector The position to play the sound
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
Returns
EffectSound The created EffectSound
References CreateSound(), and EffectSound::SoundPlayEx().
ReactivateParticleServer()
static void ReactivateParticleServer (int effecterID) inline static private
References EffecterBase(), and m_EffectersMap.
Referenced by ItemBase::PlayCatchParticleSynced(), and ActionFishingNew::PlaySplashEffectSynced().
ReinitParticleServer()
static void ReinitParticleServer (int effecterID, EffecterParameters parameters) inline static private
allows re-initializing existing effecter with new parameters (extept m_EffecterType, obviously)
References EffecterBase(), and m_EffectersMap.
Referenced by ItemBase::PlayCatchParticleSynced(), and ActionFishingNew::PlaySplashEffectSynced().
StartParticleServer()
static void StartParticleServer (int effecterID) inline static private
References EffecterBase(), and m_EffectersMap.
Stop()
static void Stop (int effect_id) inline static private
Stops the Effect.
Parameters
effect_id int The ID of the Effect to Stop
References Effect(), ErrorEx, and m_EffectsMap.
Referenced by EOnPostSimulate().
StopParticleServer()
static void StopParticleServer (int effecterID) inline static private
References EffecterBase(), and m_EffectersMap.
Field Documentation
Event_OnFrameUpdate
ref ScriptInvoker Event_OnFrameUpdate static private
Static invoker for the SEffectManager.Event_OnFrameUpdate called form MissionGameplay.OnUpdate.
Referenced by Cleanup(), Event_OnFrameUpdate(), Init(), MissionBase::OnUpdate(), and SetEnableEventFrame().
INVALID_ID
const int INVALID_ID = 0 static private
As the counter starts at 1, Effect ID can never be 0.
Referenced by Event_OnUnregistered().
m_EffectersMap
protected ref map<int, EffecterBase> m_EffectersMap static private
Referenced by Cleanup(), CreateParticleServer(), DestroyEffecterParticleServer(), InitServer(), OnUpdate(), ReactivateParticleServer(), ReinitParticleServer(), StartParticleServer(), and StopParticleServer().
m_EffectsMap
protected ref map<int, ref Effect> m_EffectsMap static private
Static map of all registered effects <id, Effect>
Referenced by Cleanup(), EffectRegister(), EffectUnregister(), GetEffectByID(), Init(), IsEffectExist(), and Stop().
m_FreeEffecterIDs
protected ref array<int> m_FreeEffecterIDs static private
Static array of IDs that were previously used, but freed up by unregistering Effecters.
Referenced by GetFreeEffecterID(), and InitServer().
m_FreeEffectIDs
protected ref array<int> m_FreeEffectIDs static private
Static array of IDs that were previously used, but freed up by unregistering.
Referenced by EffectUnregister(), GetFreeEffectID(), and Init().
m_HighestFreeEffecterID
protected int m_HighestFreeEffecterID = 1 static private
Referenced by GetFreeEffecterID().
m_HighestFreeEffectID
protected int m_HighestFreeEffectID = 1 static private
Counter for quickly getting the next ID if FreeEffectIDs array is empty.
Referenced by Cleanup(), and GetFreeEffectID().
m_IsCleanup
protected bool m_IsCleanup static private
Bool to check whether Cleanup is happening, which means that the maps should no longer be accessed.
Referenced by Cleanup(), EffectRegister(), EffectUnregister(), GetEffectByID(), and IsEffectExist().
m_IsInitialized
protected bool m_IsInitialized static private
Bool to check whether Init was called.
Referenced by Cleanup(), and Init().
m_ParamsMap
protected ref map<string, ref SoundParams> m_ParamsMap static private
Static map of cached sound params, to prevent having to recreate them.
Referenced by Cleanup(), GetCachedSoundParam(), and Init().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/EffectManager.c