DayZ Scripts: Environment Class Reference
Environment Class Reference
Private Member Functions
void Environment (PlayerBase pPlayer)
void Init ()
void Update (float pDelta)
bool IsTemperatureSet ()
protected float GetPlayerHeat ()
Returns heat player generated based on player's movement speed (for now)
bool IsUnderRoof ()
protected bool IsWaterContact ()
bool IsInsideBuilding ()
protected bool IsInsideVehicle ()
private bool IsUnderRoofBuilding ()
protected bool IsRaining ()
protected bool IsSnowing ()
protected bool DetermineHeatcomfortBehavior ()
protected void CheckUnderRoof ()
Checks whether Player is sheltered.
protected void CheckWaterContact (out float pWaterLevel)
float GetWindModifierPerSurface ()
float GetTemperature ()
float GetTargetHeatComfort ()
protected float GetEnvironmentTemperature ()
float GetWetDelta ()
protected void CollectAndSetPlayerData ()
protected void CollectAndSetEnvironmentData ()
void SetEnvironmentTemperature ()
void SetAreaGenericColdness ()
Determines whether player is in cold area which restricts use of some actions (digging)
protected float WindEffectTemperatureValue (float temperatureInput)
protected void ProcessWetnessByWaterLevel (float pWaterLevel)
process attachments by water depth
protected void ProcessItemsWetness (array< int > pSlotIds)
protected void ProcessItemsDryness ()
protected void ApplyWetnessToItem (ItemBase pItem)
protected void ApplyDrynessToItem (ItemBase pItem)
protected void ApplyDrynessToItemEx (ItemBase pItem, EnvironmentDrynessData pDrynessData)
protected void ProcessHeatComfort ()
Calculates and process player's heatcomfort related to body parts.
protected void SetTargetHeatComfort (float value)
protected void SetHeatcomfortDirectly ()
protected void ProcessHeatBuffer (float heatComfortCloths)
protected float GetApplicableHeatbuffer ()
protected void ProcessItemsTemperature (array< int > pBodyPartIds)
go through all items in player's possession cool/warm them to neutral temperature
protected void ProcessItemsInHandsTemperature ()
protected void ProcessItemHierarchyRecursive (ItemBase item, float heatPermeabilityCoef=1.0)
protected void SetProcessedItemTemperature (ItemBase item, float heatPermeabilityCoef=1.0)
protected float EnvTempToCoef (float pTemp)
protected void BodyPartHeatProperties (int pBodyPartId, float pCoef, out float pHeatComfort, out float pHeat)
returns enhanced heat comfort for given body part
protected float NakedBodyPartHeatComfortPenalty (int pBodyPartSlotId, float pCoef)
protected void GatherTemperatureSources ()
protected void SetItemHeatingCoef (float val)
protected void ProcessTemperatureSources ()
protected void OnTemperatureSourcesEnter ()
protected void OnTemperatureSourcesLeft ()
protected void SetEnvironmentSnapshotData ()
float GetUniversalSourcesTemperageAverage ()
float CalcTemperatureFromTemperatureSource (notnull UTemperatureSource uts)
string GetDebugMessage ()
debug
int GetNextRoofCheck ()
float GetWaterLevel ()
private bool IsNeutralTemperature (float temperature, float lowerLimit=GameConstants.ITEM_TEMPERATURE_NEUTRAL_ZONE_LOWER_LIMIT, float upperLimit=GameConstants.ITEM_TEMPERATURE_NEUTRAL_ZONE_UPPER_LIMIT)
private float NormalizedTemperature (float temperature, float lowerLimit=GameConstants.ENVIRO_LOW_TEMP_LIMIT, float upperLimit=GameConstants.ENVIRO_HIGH_TEMP_LIMIT)
private void LogDryWetProcess (string message, bool indented=false)
private void LogItemHeat (string message, bool indented=false)
void Init (PlayerBase pPlayer)
protected bool OverridenHeatComfort (out float value)
void AddToEnvironmentTemperature (float pTemperature)
protected void ProcessItemsHeat ()
protected void ProcessWetnessByRain ()
float GetTemperatureHeightCorrection ()
protected void BodyPartHeatProperties (array< int > pBodyPartIds, float pCoef, out float pHeatComfort, out float pHeat)
returns weighted avg heat comfort for bodypart
float GetDayOrNight ()
Private Attributes
const float RAIN_LIMIT_LOW = 0.05
protected const float SNOWFALL_LIMIT_LOW = 0.5
protected const float SNOWFALL_WIND_COMBINED_THRESHOLD = 1.3
const float WATER_LEVEL_HIGH = 1.5
const float WATER_LEVEL_MID = 1.2
const float WATER_LEVEL_LOW = 0.5
const float WATER_LEVEL_NONE = 0.15
protected float m_WetDryTick
protected float m_ItemsWetnessMax
protected float m_RoofCheckTimer
keeps wetness of most wet item in player's possesion
protected PlayerBase m_Player
protected float m_PlayerHeightPos
protected float m_PlayerSpeed
protected float m_PlayerTemperature
protected float m_PlayerHeat
protected float m_HeatComfort
protected float m_TargetHeatComfort
player's heatcomfort (buffered, stored in player stats)
protected float m_Rain = 0
target value of heatcomfort (non-buffered)
protected float m_Snowfall = 0
protected float m_Wind = 0
protected float m_Fog = 0
protected float m_DayOrNight = 0
protected float m_Clouds = 0
protected float m_EnvironmentTemperature
protected float m_Time = 0
protected string m_SurfaceType
protected int m_LiquidType
protected float m_ItemTemperatureCoef
protected float m_WaterLevel
protected bool m_IsUnderRoof
private bool m_IsUnderRoofBuilding
protected bool m_IsInWater
protected bool m_IsTempSet
protected float m_HeatBufferTimer
protected ref array< int > m_SlotIdsComplete
reused as state toggle
protected ref array< int > m_SlotIdsUpper
protected ref array< int > m_SlotIdsBottom
protected ref array< int > m_SlotIdsLower
protected ref array< int > m_HeadParts
protected ref array< int > m_BodyParts
protected ref array< int > m_FeetParts
protected ref WorldData m_WorldData
protected bool m_HasTemperatureSources
protected float m_UTSAverageTemperature
protected ref array< UTemperatureSource > m_UTemperatureSources
protected ref SimpleMovingAverage< float > m_UTSAverageTemperatureBuffer
protected ref SimpleMovingAverage< float > m_AverageHeatComfortBuffer
protected int m_HeatComfortBehaviorCategory
protected ref EnvironmentSnapshotData m_EnvironmentSnapshot
private bool m_Initialized
used for calculations before the data modification
protected float m_HeatSourceTemp
DEPRECATED.
protected ref SimpleMovingAverage< float > m_WindAverageBuffer
Constructor & Destructor Documentation
Environment()
void Environment (PlayerBase pPlayer) inline private
References m_Player.
Member Function Documentation
AddToEnvironmentTemperature()
void AddToEnvironmentTemperature (float pTemperature) private
ApplyDrynessToItem()
protected void ApplyDrynessToItem (ItemBase pItem) inline private
References ApplyDrynessToItemEx().
ApplyDrynessToItemEx()
protected void ApplyDrynessToItemEx (ItemBase pItem, EnvironmentDrynessData pDrynessData) inline private
adds wetness to item inside parent item containing liquid
adds wetness to item inside wet parent item
References ApplyDrynessToItemEx(), Class::CastTo(), GameConstants::ENVIRO_TICK_RATE, InventoryLocation::GetParent(), LogDryWetProcess(), m_ItemsWetnessMax, m_Player, GameConstants::STATE_DAMP, and GameConstants::STATE_SOAKING_WET.
Referenced by ApplyDrynessToItem(), ApplyDrynessToItemEx(), and ProcessItemsDryness().
ApplyWetnessToItem()
protected void ApplyWetnessToItem (ItemBase pItem) inline private
References ApplyWetnessToItem(), Class::CastTo(), GameConstants::ENVIRO_TICK_RATE, InventoryLocation::GetParent(), GetWetDelta(), LogDryWetProcess(), m_ItemsWetnessMax, m_Player, and GameConstants::STATE_SOAKING_WET.
Referenced by ApplyWetnessToItem(), and ProcessItemsWetness().
BodyPartHeatProperties() [1/2]
protected void BodyPartHeatProperties (array< int > pBodyPartIds, float pCoef, out float pHeatComfort, out float pHeat) inline private
returns weighted avg heat comfort for bodypart
go through all body parts we've defined for that zone (ex.: head, body, feet)
References EnumTools::EnumToString(), GameConstants::ENVIRO_HEATISOLATION_BACK_WEIGHT, GameConstants::ENVIRO_HEATISOLATION_VEST_WEIGHT, GameConstants::ITEM_TEMPERATURE_NEUTRAL_ZONE_UPPER_LIMIT, LogItemHeat(), m_Player, and NormalizedTemperature().
BodyPartHeatProperties() [2/2]
protected void BodyPartHeatProperties (int pBodyPartId, float pCoef, out float pHeatComfort, out float pHeat) inline private
returns enhanced heat comfort for given body part
References EnumTools::EnumToString(), GameConstants::ITEM_TEMPERATURE_NEUTRAL_ZONE_UPPER_LIMIT, LogItemHeat(), m_Player, and NormalizedTemperature().
Referenced by ProcessHeatComfort().
CalcTemperatureFromTemperatureSource()
float CalcTemperatureFromTemperatureSource (notnull UTemperatureSource uts) inline private
heat transfer through air to player (env temperature)
References vector::Distance(), Math::InverseLerp(), m_Player, and Math::Max().
Referenced by ProcessTemperatureSources().
CheckUnderRoof()
protected void CheckUnderRoof () inline private
Checks whether Player is sheltered.
References IsInsideVehicle(), m_IsUnderRoof, m_IsUnderRoofBuilding, m_Player, and DayZPhysics::RayCastBullet().
Referenced by Update().
CheckWaterContact()
protected void CheckWaterContact (out float pWaterLevel) inline private
no valid surface under character
sync info about water contact to player
update active surface
References g_Game, IsUnderRoofBuilding(), LIQUID_FRESHWATER, LIQUID_HOTWATER, LIQUID_RIVERWATER, LIQUID_SALTWATER, LIQUID_STILLWATER, LIQUID_WATER, HumanMovementState::m_iMovement, m_IsInWater, m_LiquidType, m_Player, m_SurfaceType, WATER_LEVEL_HIGH, and WATER_LEVEL_MID.
Referenced by Update().
CollectAndSetEnvironmentData()
protected void CollectAndSetEnvironmentData () inline private
References g_Game, WeatherPhenomenon::GetActual(), Weather::GetFog(), Weather::GetOvercast(), Weather::GetRain(), Weather::GetSnowfall(), m_Clouds, m_DayOrNight, m_Fog, m_Rain, m_Snowfall, m_Wind, SetAreaGenericColdness(), and SetEnvironmentTemperature().
Referenced by Update().
CollectAndSetPlayerData()
protected void CollectAndSetPlayerData () inline private
References HumanCommandMove::GetCurrentMovementSpeed(), GetPlayerHeat(), m_Player, m_PlayerHeat, m_PlayerHeightPos, and m_PlayerSpeed.
Referenced by Update().
DetermineHeatcomfortBehavior()
protected bool DetermineHeatcomfortBehavior () inline private
References IsInsideVehicle(), m_HeatComfortBehaviorCategory, and m_Player.
Referenced by Update().
EnvTempToCoef()
protected float EnvTempToCoef (float pTemp) inline private
References GameConstants::ENVIRO_PLAYER_COMFORT_TEMP, and GameConstants::ENVIRO_TEMP_EFFECT_ON_PLAYER.
Referenced by ProcessHeatComfort().
GatherTemperatureSources()
protected void GatherTemperatureSources () inline private
next temp source is too far
skip - this TS is not affecting player entities
References vector::DistanceSq(), GameConstants::ENVIRO_TEMP_SOURCES_LOOKUP_RADIUS, GetGame(), CGame::GetObjectsAtPosition(), m_Player, m_UTemperatureSources, and Math::SqrFloat().
Referenced by Update().
GetApplicableHeatbuffer()
protected float GetApplicableHeatbuffer () inline private
References m_Player, and Math::Round().
Referenced by ProcessHeatBuffer().
GetDayOrNight()
float GetDayOrNight () inline private
References m_DayOrNight.
GetDebugMessage()
string GetDebugMessage () inline private
debug
References g_Game, WorldData::GetBaseEnvTemperature(), WorldData::GetBaseEnvTemperatureAtObject(), GetNextRoofCheck(), GetTargetHeatComfort(), GetWetDelta(), GetWindModifierPerSurface(), IsInsideBuilding(), IsWaterContact(), m_Clouds, m_DayOrNight, m_EnvironmentTemperature, m_Fog, m_HeatComfort, m_IsUnderRoof, m_Player, m_Rain, m_Snowfall, m_WaterLevel, m_Wind, m_WorldData, bool::ToString(), float::ToString(), WorldDataDaytime::ToString(), and WATER_LEVEL_NONE.
GetEnvironmentTemperature()
protected float GetEnvironmentTemperature () inline private
References Math::AbsFloat(), GameConstants::ENVIRO_FOG_TEMP_EFFECT, GameConstants::ENVIRO_TEMPERATURE_INSIDE_VEHICLE_COEF, GameConstants::ENVIRO_TEMPERATURE_UNDERROOF_COEF, WorldData::GetBaseEnvTemperatureAtObject(), WorldData::GetLiquidTypeEnviroTemperature(), GetWindModifierPerSurface(), IsInsideBuilding(), IsInsideVehicle(), IsUnderRoof(), IsWaterContact(), m_Clouds, WorldData::m_CloudsTemperatureEffectModifier, m_Fog, m_IsUnderRoofBuilding, m_LiquidType, m_Player, m_UTSAverageTemperature, m_WorldData, and WindEffectTemperatureValue().
Referenced by GetWetDelta(), and SetEnvironmentTemperature().
GetNextRoofCheck()
int GetNextRoofCheck () inline private
References GameConstants::ENVIRO_TICK_ROOF_RC_CHECK, and m_RoofCheckTimer.
Referenced by GetDebugMessage().
GetPlayerHeat()
protected float GetPlayerHeat () inline private
Returns heat player generated based on player's movement speed (for now)
References GameConstants::ENVIRO_DEFAULT_ENTITY_HEAT, and m_PlayerSpeed.
Referenced by CollectAndSetPlayerData(), and ProcessHeatComfort().
GetTargetHeatComfort()
float GetTargetHeatComfort () inline private
References m_TargetHeatComfort.
Referenced by GetDebugMessage().
GetTemperature()
float GetTemperature () inline private
References m_EnvironmentTemperature.
GetTemperatureHeightCorrection()
float GetTemperatureHeightCorrection () inline private
References m_PlayerHeightPos, WorldData::m_TemperaturePerHeightReductionModifier, m_WorldData, and Math::Max().
GetUniversalSourcesTemperageAverage()
float GetUniversalSourcesTemperageAverage () inline private
References m_UTSAverageTemperature.
GetWaterLevel()
float GetWaterLevel () inline private
References IsWaterContact(), m_WaterLevel, and WATER_LEVEL_NONE.
GetWetDelta()
float GetWetDelta () inline private
player is getting wet by movement/swimming in water (+differentiate wetDelta by water level)
player is drying
References GameConstants::ENVIRO_CLOUD_DRY_EFFECT, GameConstants::ENVIRO_DRY_INCREMENT, GameConstants::ENVIRO_FOG_DRY_EFFECT, GameConstants::ENVIRO_SNOW_WET_COEF, GameConstants::ENVIRO_TICKS_TO_WETNESS_CALCULATION, GameConstants::ENVIRO_WET_INCREMENT, GameConstants::ENVIRO_WIND_EFFECT, GetEnvironmentTemperature(), IsInsideBuilding(), IsInsideVehicle(), IsRaining(), IsSnowing(), IsUnderRoof(), IsWaterContact(), m_Clouds, m_Fog, m_PlayerHeat, m_Rain, m_Snowfall, m_WaterLevel, m_Wind, Math::Max(), SNOWFALL_LIMIT_LOW, SNOWFALL_WIND_COMBINED_THRESHOLD, WATER_LEVEL_HIGH, WATER_LEVEL_LOW, WATER_LEVEL_MID, and WATER_LEVEL_NONE.
Referenced by ApplyWetnessToItem(), and GetDebugMessage().
GetWindModifierPerSurface()
float GetWindModifierPerSurface () inline private
References g_Game, IsUnderRoofBuilding(), and m_SurfaceType.
Referenced by GetDebugMessage(), and GetEnvironmentTemperature().
Init() [1/2]
void Init () inline private
whole body slots
upper body part slots
bottom body part slots
lower body part slots
heat comfort related slots
References g_Game, WorldData::GetBaseEnvTemperatureAtObject(), m_AverageHeatComfortBuffer, m_BodyParts, m_EnvironmentTemperature, m_FeetParts, m_HeadParts, m_HeatBufferTimer, m_HeatComfort, m_HeatComfortBehaviorCategory, m_Initialized, m_IsInWater, m_IsUnderRoof, m_Player, m_PlayerSpeed, m_RoofCheckTimer, m_SlotIdsBottom, m_SlotIdsComplete, m_SlotIdsLower, m_SlotIdsUpper, m_SurfaceType, m_UTemperatureSources, m_UTSAverageTemperature, m_UTSAverageTemperatureBuffer, m_WaterLevel, m_WetDryTick, m_WorldData, and SetEnvironmentSnapshotData().
Referenced by Init().
Init() [2/2]
void Init (PlayerBase pPlayer) inline private
References Init().
IsInsideBuilding()
bool IsInsideBuilding () inline private
References m_Player.
Referenced by GetDebugMessage(), GetEnvironmentTemperature(), GetWetDelta(), NakedBodyPartHeatComfortPenalty(), and Update().
IsInsideVehicle()
protected bool IsInsideVehicle () inline private
References m_Player.
Referenced by CheckUnderRoof(), DetermineHeatcomfortBehavior(), GetEnvironmentTemperature(), GetWetDelta(), NakedBodyPartHeatComfortPenalty(), and Update().
IsNeutralTemperature()
private bool IsNeutralTemperature (float temperature, float lowerLimit = GameConstants.ITEM_TEMPERATURE_NEUTRAL_ZONE_LOWER_LIMIT, float upperLimit = GameConstants.ITEM_TEMPERATURE_NEUTRAL_ZONE_UPPER_LIMIT) inline private
Referenced by ProcessHeatComfort().
IsRaining()
protected bool IsRaining () inline private
References m_Rain, and RAIN_LIMIT_LOW.
Referenced by GetWetDelta(), and Update().
IsSnowing()
protected bool IsSnowing () inline private
References m_Snowfall, and SNOWFALL_LIMIT_LOW.
Referenced by GetWetDelta(), and Update().
IsTemperatureSet()
bool IsTemperatureSet () inline private
References m_IsTempSet.
IsUnderRoof()
bool IsUnderRoof () inline private
References m_IsUnderRoof.
Referenced by GetEnvironmentTemperature(), GetWetDelta(), NakedBodyPartHeatComfortPenalty(), and Update().
IsUnderRoofBuilding()
private bool IsUnderRoofBuilding () inline private
References m_IsUnderRoofBuilding.
Referenced by CheckWaterContact(), and GetWindModifierPerSurface().
IsWaterContact()
protected bool IsWaterContact () inline private
References m_IsInWater.
Referenced by GetDebugMessage(), GetEnvironmentTemperature(), GetWaterLevel(), GetWetDelta(), NakedBodyPartHeatComfortPenalty(), and Update().
LogDryWetProcess()
private void LogDryWetProcess (string message, bool indented = false) inline private
References Debug::Log().
Referenced by ApplyDrynessToItemEx(), ApplyWetnessToItem(), ProcessItemsDryness(), and ProcessItemsWetness().
LogItemHeat()
private void LogItemHeat (string message, bool indented = false) inline private
References Debug::Log().
Referenced by BodyPartHeatProperties(), BodyPartHeatProperties(), and ProcessHeatComfort().
NakedBodyPartHeatComfortPenalty()
protected float NakedBodyPartHeatComfortPenalty (int pBodyPartSlotId, float pCoef) inline private
References GameConstants::ENVIRO_ISOLATION_WETFACTOR_DRENCHED, GameConstants::ENVIRO_NAKED_BODY_PENALTY_RAIN_MIN_VALUE, GameConstants::ENVIRO_NAKED_BODY_PENALTY_SNOWFALL_MIN_VALUE, IsInsideBuilding(), IsInsideVehicle(), IsUnderRoof(), IsWaterContact(), m_Rain, and m_Snowfall.
Referenced by ProcessHeatComfort().
NormalizedTemperature()
private float NormalizedTemperature (float temperature, float lowerLimit = GameConstants.ENVIRO_LOW_TEMP_LIMIT, float upperLimit = GameConstants.ENVIRO_HIGH_TEMP_LIMIT) inline private
References Math::Clamp(), Math::InverseLerp(), GameConstants::ITEM_TEMPERATURE_NEUTRAL_ZONE_LOWER_LIMIT, and GameConstants::ITEM_TEMPERATURE_NEUTRAL_ZONE_UPPER_LIMIT.
Referenced by BodyPartHeatProperties(), and BodyPartHeatProperties().
OnTemperatureSourcesEnter()
protected void OnTemperatureSourcesEnter () private
Referenced by ProcessTemperatureSources().
OnTemperatureSourcesLeft()
protected void OnTemperatureSourcesLeft () private
Referenced by ProcessTemperatureSources().
OverridenHeatComfort()
protected bool OverridenHeatComfort (out float value) private
ProcessHeatBuffer()
protected void ProcessHeatBuffer (float heatComfortCloths) inline private
dynamic HB cap based on actual heatcomfort (from cloths)
References GameConstants::ENVIRO_HEATCOMFORT_WEIGHT_SUMMARY, GameConstants::ENVIRO_PLAYER_HEATBUFFER_CAPACITY_MIN, GameConstants::ENVIRO_PLAYER_HEATBUFFER_DECREASE, GameConstants::ENVIRO_PLAYER_HEATBUFFER_INCREASE, GameConstants::ENVIRO_PLAYER_HEATBUFFER_TEMP_AFFECT, GameConstants::ENVIRO_PLAYER_HEATBUFFER_WATEREFFECT, GetApplicableHeatbuffer(), Math::InverseLerp(), m_EnvironmentSnapshot, m_HasTemperatureSources, m_HeatBufferTimer, m_HeatComfort, m_HeatComfortBehaviorCategory, m_IsInWater, m_Player, m_UTSAverageTemperature, m_WaterLevel, and PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_WARNING.
Referenced by ProcessHeatComfort().
ProcessHeatComfort()
protected void ProcessHeatComfort () inline private
Calculates and process player's heatcomfort related to body parts.
Heat Comfort Penalty
heatcomfort body parts penalties
References Math::AbsFloat(), BodyPartHeatProperties(), Math::Clamp(), GameConstants::ENVIRO_HEATCOMFORT_BACK_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_BODY_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_FEET_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_GLOVES_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_HEADGEAR_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_HIPS_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_LEGS_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_MASK_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_MAX_STEP_SIZE, GameConstants::ENVIRO_HEATCOMFORT_VEST_WEIGHT, GameConstants::ENVIRO_STOMACH_WEIGHT, EnvTempToCoef(), GetPlayerHeat(), IsNeutralTemperature(), LogItemHeat(), m_AverageHeatComfortBuffer, m_EnvironmentTemperature, m_HeatComfort, m_Player, NakedBodyPartHeatComfortPenalty(), ProcessHeatBuffer(), Math::Round(), SetEnvironmentSnapshotData(), and SetTargetHeatComfort().
Referenced by ProcessItemsHeat(), and Update().
ProcessItemHierarchyRecursive()
protected void ProcessItemHierarchyRecursive (ItemBase item, float heatPermeabilityCoef = 1.0) inline private
References Class::CastTo(), ItemBase::IsSelfAdjustingTemperature(), ProcessItemHierarchyRecursive(), and SetProcessedItemTemperature().
Referenced by ProcessItemHierarchyRecursive(), ProcessItemsInHandsTemperature(), and ProcessItemsTemperature().
ProcessItemsDryness()
protected void ProcessItemsDryness () inline private
References ApplyDrynessToItemEx(), vector::Distance(), GameConstants::ENVIRO_TICK_RATE, GetPosition, LogDryWetProcess(), m_HasTemperatureSources, m_Player, m_UTemperatureSources, and Math::Max().
Referenced by Update().
ProcessItemsHeat()
protected void ProcessItemsHeat () inline private
References ProcessHeatComfort().
ProcessItemsInHandsTemperature()
protected void ProcessItemsInHandsTemperature () inline private
References ItemBase::IsSelfAdjustingTemperature(), m_Player, ProcessItemHierarchyRecursive(), and SetProcessedItemTemperature().
Referenced by Update().
ProcessItemsTemperature()
protected void ProcessItemsTemperature (array< int > pBodyPartIds) inline private
go through all items in player's possession cool/warm them to neutral temperature
go through all body parts we've defined for that zone (ex.: head, body, feet)
References ItemBase::IsSelfAdjustingTemperature(), m_Player, ProcessItemHierarchyRecursive(), and SetProcessedItemTemperature().
Referenced by Update().
ProcessItemsWetness()
protected void ProcessItemsWetness (array< int > pSlotIds) inline private
References ApplyWetnessToItem(), GameConstants::ENVIRO_TICK_RATE, LogDryWetProcess(), and m_Player.
Referenced by ProcessWetnessByRain(), ProcessWetnessByWaterLevel(), and Update().
ProcessTemperatureSources()
protected void ProcessTemperatureSources () inline private
adds average of 2 most significat sources to buffer
References CalcTemperatureFromTemperatureSource(), m_HasTemperatureSources, m_UTemperatureSources, m_UTSAverageTemperature, m_UTSAverageTemperatureBuffer, OnTemperatureSourcesEnter(), OnTemperatureSourcesLeft(), SetItemHeatingCoef(), and GameConstants::TEMP_COEF_INVENTORY.
Referenced by Update().
ProcessWetnessByRain()
protected void ProcessWetnessByRain () inline private
References m_SlotIdsComplete, and ProcessItemsWetness().
ProcessWetnessByWaterLevel()
protected void ProcessWetnessByWaterLevel (float pWaterLevel) inline private
process attachments by water depth
References m_SlotIdsBottom, m_SlotIdsComplete, m_SlotIdsLower, m_SlotIdsUpper, ProcessItemsWetness(), WATER_LEVEL_HIGH, WATER_LEVEL_LOW, WATER_LEVEL_MID, and WATER_LEVEL_NONE.
Referenced by Update().
SetAreaGenericColdness()
void SetAreaGenericColdness () inline private
Determines whether player is in cold area which restricts use of some actions (digging)
References GameConstants::COLD_AREA_TEMPERATURE_THRESHOLD, WorldData::GetBaseEnvTemperatureAtObject(), m_Player, and m_WorldData.
Referenced by CollectAndSetEnvironmentData().
SetEnvironmentSnapshotData()
protected void SetEnvironmentSnapshotData () inline private
References m_EnvironmentSnapshot, and m_TargetHeatComfort.
Referenced by Init(), and ProcessHeatComfort().
SetEnvironmentTemperature()
void SetEnvironmentTemperature () inline private
References GetEnvironmentTemperature(), m_EnvironmentTemperature, and m_IsTempSet.
Referenced by CollectAndSetEnvironmentData().
SetHeatcomfortDirectly()
protected void SetHeatcomfortDirectly () inline private
References m_AverageHeatComfortBuffer, m_HeatComfort, m_HeatComfortBehaviorCategory, m_Player, and SetTargetHeatComfort().
Referenced by Update().
SetItemHeatingCoef()
protected void SetItemHeatingCoef (float val) inline private
References m_ItemTemperatureCoef.
Referenced by ProcessTemperatureSources().
SetProcessedItemTemperature()
protected void SetProcessedItemTemperature (ItemBase item, float heatPermeabilityCoef = 1.0) inline private
References GameConstants::ENVIRO_TICK_RATE, GameConstants::ITEM_TEMPERATURE_NEUTRAL_ZONE_MIDDLE, and m_ItemTemperatureCoef.
Referenced by ProcessItemHierarchyRecursive(), ProcessItemsInHandsTemperature(), and ProcessItemsTemperature().
SetTargetHeatComfort()
protected void SetTargetHeatComfort (float value) inline private
References m_TargetHeatComfort.
Referenced by ProcessHeatComfort(), and SetHeatcomfortDirectly().
Update()
void Update (float pDelta) inline private
check if player is under roof (only if the Building check is false)
Updates data
Process temperatures
heat comfort calculation
Process item wetness/dryness
setting of wetness/dryiness of player
reset item wetness counter;
References CheckUnderRoof(), CheckWaterContact(), CollectAndSetEnvironmentData(), CollectAndSetPlayerData(), DetermineHeatcomfortBehavior(), GameConstants::ENVIRO_TICK_RATE, GameConstants::ENVIRO_TICK_ROOF_RC_CHECK, GameConstants::ENVIRO_TICKS_TO_WETNESS_CALCULATION, GatherTemperatureSources(), IsInsideBuilding(), IsInsideVehicle(), IsRaining(), IsSnowing(), IsUnderRoof(), IsWaterContact(), m_BodyParts, m_FeetParts, m_HeadParts, m_Initialized, m_ItemsWetnessMax, m_Player, m_RoofCheckTimer, m_SlotIdsComplete, m_Time, m_WaterLevel, m_WetDryTick, ProcessHeatComfort(), ProcessItemsDryness(), ProcessItemsInHandsTemperature(), ProcessItemsTemperature(), ProcessItemsWetness(), ProcessTemperatureSources(), ProcessWetnessByWaterLevel(), SetHeatcomfortDirectly(), SNOWFALL_WIND_COMBINED_THRESHOLD, and GameConstants::STATE_WET.
WindEffectTemperatureValue()
protected float WindEffectTemperatureValue (float temperatureInput) inline private
References GameConstants::ENVIRO_WIND_CHILL_LIMIT, GameConstants::ENVIRO_WIND_EFFECT_SLOPE, WorldData::GetWindCoef(), m_Wind, and m_WorldData.
Referenced by GetEnvironmentTemperature().
Field Documentation
m_AverageHeatComfortBuffer
protected ref SimpleMovingAverage<float> m_AverageHeatComfortBuffer private
Referenced by Init(), ProcessHeatComfort(), and SetHeatcomfortDirectly().
m_BodyParts
protected ref array<int> m_BodyParts private
Referenced by Init(), and Update().
m_Clouds
protected float m_Clouds = 0 private
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetEnvironmentTemperature(), and GetWetDelta().
m_DayOrNight
protected float m_DayOrNight = 0 private
Referenced by CollectAndSetEnvironmentData(), GetDayOrNight(), and GetDebugMessage().
m_EnvironmentSnapshot
protected ref EnvironmentSnapshotData m_EnvironmentSnapshot private
Referenced by ProcessHeatBuffer(), and SetEnvironmentSnapshotData().
m_EnvironmentTemperature
protected float m_EnvironmentTemperature private
Referenced by GetDebugMessage(), GetTemperature(), Init(), ProcessHeatComfort(), and SetEnvironmentTemperature().
m_FeetParts
protected ref array<int> m_FeetParts private
Referenced by Init(), and Update().
m_Fog
protected float m_Fog = 0 private
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetEnvironmentTemperature(), and GetWetDelta().
m_HasTemperatureSources
protected bool m_HasTemperatureSources private
Referenced by ProcessHeatBuffer(), ProcessItemsDryness(), and ProcessTemperatureSources().
m_HeadParts
protected ref array<int> m_HeadParts private
Referenced by Init(), and Update().
m_HeatBufferTimer
protected float m_HeatBufferTimer private
Referenced by Init(), and ProcessHeatBuffer().
m_HeatComfort
protected float m_HeatComfort private
Referenced by GetDebugMessage(), Init(), ProcessHeatBuffer(), ProcessHeatComfort(), and SetHeatcomfortDirectly().
m_HeatComfortBehaviorCategory
protected int m_HeatComfortBehaviorCategory private
Referenced by DetermineHeatcomfortBehavior(), Init(), ProcessHeatBuffer(), and SetHeatcomfortDirectly().
m_HeatSourceTemp
protected float m_HeatSourceTemp private
DEPRECATED.
m_Initialized
private bool m_Initialized private
used for calculations before the data modification
Referenced by Init(), and Update().
m_IsInWater
protected bool m_IsInWater private
Referenced by CheckWaterContact(), Init(), IsWaterContact(), and ProcessHeatBuffer().
m_IsTempSet
protected bool m_IsTempSet private
Referenced by IsTemperatureSet(), and SetEnvironmentTemperature().
m_IsUnderRoof
protected bool m_IsUnderRoof private
Referenced by CheckUnderRoof(), GetDebugMessage(), Init(), and IsUnderRoof().
m_IsUnderRoofBuilding
private bool m_IsUnderRoofBuilding private
Referenced by CheckUnderRoof(), GetEnvironmentTemperature(), and IsUnderRoofBuilding().
m_ItemsWetnessMax
protected float m_ItemsWetnessMax private
Referenced by ApplyDrynessToItemEx(), ApplyWetnessToItem(), and Update().
m_ItemTemperatureCoef
protected float m_ItemTemperatureCoef private
Referenced by SetItemHeatingCoef(), and SetProcessedItemTemperature().
m_LiquidType
protected int m_LiquidType private
Referenced by CheckWaterContact(), and GetEnvironmentTemperature().
m_Player
protected PlayerBase m_Player private
Referenced by ApplyDrynessToItemEx(), ApplyWetnessToItem(), BodyPartHeatProperties(), BodyPartHeatProperties(), CalcTemperatureFromTemperatureSource(), CheckUnderRoof(), CheckWaterContact(), CollectAndSetPlayerData(), DetermineHeatcomfortBehavior(), Environment(), GatherTemperatureSources(), GetApplicableHeatbuffer(), GetDebugMessage(), GetEnvironmentTemperature(), Init(), IsInsideBuilding(), IsInsideVehicle(), ProcessHeatBuffer(), ProcessHeatComfort(), ProcessItemsDryness(), ProcessItemsInHandsTemperature(), ProcessItemsTemperature(), ProcessItemsWetness(), SetAreaGenericColdness(), SetHeatcomfortDirectly(), and Update().
m_PlayerHeat
protected float m_PlayerHeat private
Referenced by CollectAndSetPlayerData(), and GetWetDelta().
m_PlayerHeightPos
protected float m_PlayerHeightPos private
Referenced by CollectAndSetPlayerData(), and GetTemperatureHeightCorrection().
m_PlayerSpeed
protected float m_PlayerSpeed private
Referenced by CollectAndSetPlayerData(), GetPlayerHeat(), and Init().
m_PlayerTemperature
protected float m_PlayerTemperature private
m_Rain
protected float m_Rain = 0 private
target value of heatcomfort (non-buffered)
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetWetDelta(), IsRaining(), and NakedBodyPartHeatComfortPenalty().
m_RoofCheckTimer
protected float m_RoofCheckTimer private
keeps wetness of most wet item in player's possesion
Referenced by GetNextRoofCheck(), Init(), and Update().
m_SlotIdsBottom
protected ref array<int> m_SlotIdsBottom private
Referenced by Init(), and ProcessWetnessByWaterLevel().
m_SlotIdsComplete
protected ref array<int> m_SlotIdsComplete private
reused as state toggle
Referenced by Init(), ProcessWetnessByRain(), ProcessWetnessByWaterLevel(), and Update().
m_SlotIdsLower
protected ref array<int> m_SlotIdsLower private
Referenced by Init(), and ProcessWetnessByWaterLevel().
m_SlotIdsUpper
protected ref array<int> m_SlotIdsUpper private
Referenced by Init(), and ProcessWetnessByWaterLevel().
m_Snowfall
protected float m_Snowfall = 0 private
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetWetDelta(), IsSnowing(), and NakedBodyPartHeatComfortPenalty().
m_SurfaceType
protected string m_SurfaceType private
Referenced by CheckWaterContact(), GetWindModifierPerSurface(), and Init().
m_TargetHeatComfort
protected float m_TargetHeatComfort private
player's heatcomfort (buffered, stored in player stats)
Referenced by GetTargetHeatComfort(), SetEnvironmentSnapshotData(), and SetTargetHeatComfort().
m_Time
protected float m_Time = 0 private
Referenced by Update().
m_UTemperatureSources
protected ref array<UTemperatureSource> m_UTemperatureSources private
Referenced by GatherTemperatureSources(), Init(), ProcessItemsDryness(), and ProcessTemperatureSources().
m_UTSAverageTemperature
protected float m_UTSAverageTemperature private
Referenced by GetEnvironmentTemperature(), GetUniversalSourcesTemperageAverage(), Init(), ProcessHeatBuffer(), and ProcessTemperatureSources().
m_UTSAverageTemperatureBuffer
protected ref SimpleMovingAverage<float> m_UTSAverageTemperatureBuffer private
Referenced by Init(), and ProcessTemperatureSources().
m_WaterLevel
protected float m_WaterLevel private
Referenced by GetDebugMessage(), GetWaterLevel(), GetWetDelta(), Init(), ProcessHeatBuffer(), and Update().
m_WetDryTick
protected float m_WetDryTick private
Referenced by Init(), and Update().
m_Wind
protected float m_Wind = 0 private
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetWetDelta(), and WindEffectTemperatureValue().
m_WindAverageBuffer
protected ref SimpleMovingAverage<float> m_WindAverageBuffer private
m_WorldData
protected ref WorldData m_WorldData private
Referenced by GetDebugMessage(), GetEnvironmentTemperature(), GetTemperatureHeightCorrection(), Init(), SetAreaGenericColdness(), and WindEffectTemperatureValue().
RAIN_LIMIT_LOW
const float RAIN_LIMIT_LOW = 0.05 private
Referenced by IsRaining().
SNOWFALL_LIMIT_LOW
protected const float SNOWFALL_LIMIT_LOW = 0.5 private
Referenced by GetWetDelta(), and IsSnowing().
SNOWFALL_WIND_COMBINED_THRESHOLD
protected const float SNOWFALL_WIND_COMBINED_THRESHOLD = 1.3 private
Referenced by GetWetDelta(), and Update().
WATER_LEVEL_HIGH
const float WATER_LEVEL_HIGH = 1.5 private
Referenced by CheckWaterContact(), GetWetDelta(), and ProcessWetnessByWaterLevel().
WATER_LEVEL_LOW
const float WATER_LEVEL_LOW = 0.5 private
Referenced by GetWetDelta(), and ProcessWetnessByWaterLevel().
WATER_LEVEL_MID
const float WATER_LEVEL_MID = 1.2 private
Referenced by CheckWaterContact(), GetWetDelta(), and ProcessWetnessByWaterLevel().
WATER_LEVEL_NONE
const float WATER_LEVEL_NONE = 0.15 private
Referenced by GetDebugMessage(), GetWaterLevel(), GetWetDelta(), and ProcessWetnessByWaterLevel().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/Environment/Environment.c