DayZ Scripts: CAContinuousWringClothes Class Reference
CAContinuousWringClothes Class Reference
Private Member Functions
void CAContinuousWringClothes (float quantity_used_per_second, float time_to_repeat)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override float GetProgress ()
Private Attributes
protected float m_InitItemQuantity
protected float m_SpentQuantityTotal
Detailed Description
Definition at line 1 of file CAContinuousWringClothes.c.
Constructor & Destructor Documentation
CAContinuousWringClothes()
void CAContinuousWringClothes (float quantity_used_per_second, float time_to_repeat) inline private
Definition at line 6 of file CAContinuousWringClothes.c.
References CAContinuousQuantityRepeat::m_DefaultTimeToRepeat, m_InitItemQuantity, and CAContinuousQuantityRepeat::m_QuantityUsedPerSecond.
Member Function Documentation
Execute()
override int Execute (ActionData action_data) inline private
Definition at line 24 of file CAContinuousWringClothes.c.
References GetGame(), CABase::m_Action, CAContinuousQuantityRepeat::m_AdjustedQuantityUsedPerSecond, CAContinuousQuantityRepeat::m_DefaultTimeToRepeat, m_InitItemQuantity, ActionData::m_MainItem, ActionData::m_Player, CAContinuousQuantityRepeat::m_QuantityUsedPerSecond, CAContinuousQuantityRepeat::m_SpentQuantity, m_SpentQuantityTotal, CAContinuousQuantityRepeat::m_SpentUnits, CAContinuousQuantityRepeat::m_TimeElpased, CAContinuousBase::OnCompletePogress(), CABase::SetACData(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float GetProgress () inline private
Definition at line 78 of file CAContinuousWringClothes.c.
References CAContinuousQuantityRepeat::m_DefaultTimeToRepeat, and CAContinuousQuantityRepeat::m_TimeElpased.
Setup()
override void Setup (ActionData action_data) inline private
Definition at line 13 of file CAContinuousWringClothes.c.
References m_InitItemQuantity, and ActionData::m_MainItem.
Field Documentation
m_InitItemQuantity
protected float m_InitItemQuantity private
Definition at line 3 of file CAContinuousWringClothes.c.
Referenced by CAContinuousWringClothes(), Execute(), and Setup().
m_SpentQuantityTotal
protected float m_SpentQuantityTotal private
Definition at line 4 of file CAContinuousWringClothes.c.
Referenced by Execute().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousWringClothes.c