DayZ Scripts: PlayerStats Class Reference
PlayerStats Class Reference
Private Member Functions
void PlayerStats (Man player)
void Init (Man player)
PlayerStatsPCO_Base GetPCO (int version=-1)
void ~PlayerStats ()
PlayerStatBase GetStatObject (int id)
void SetAllowLogs (bool enable)
bool GetAllowLogs ()
void GetDebugInfo (array< ref StatDebugObject > objects, int flags)
void GatherAllRecords ()
void SaveStats (ParamsWriteContext ctx)
bool LoadStats (ParamsReadContext ctx, int version)
void ResetAllStats ()
Private Attributes
ref array< ref PlayerStatBase > m_PlayerStats
ref array< ref StatDebugObject > m_PlayerStatsDebug
ref PCOHandlerStats m_PCOhandler = new PCOHandlerStats()
ref Timer m_SyncTimer
Man m_Player
bool m_AllowLogs
string m_System = "Stats"
Constructor & Destructor Documentation
PlayerStats()
void PlayerStats (Man player) inline private
References Init().
~PlayerStats()
void ~PlayerStats () inline private
Member Function Documentation
GatherAllRecords()
void GatherAllRecords () inline private
GetAllowLogs()
bool GetAllowLogs () inline private
References m_AllowLogs.
GetDebugInfo()
void GetDebugInfo (array< ref StatDebugObject > objects, int flags) inline private
GetPCO()
PlayerStatsPCO_Base GetPCO (int version = -1) inline private
References PCOHandlerStats::GetPCO(), and m_PCOhandler.
Referenced by GetStatObject(), LoadStats(), ResetAllStats(), and SaveStats().
GetStatObject()
PlayerStatBase GetStatObject (int id) inline private
References GetPCO().
Init()
void Init (Man player) inline private
References m_Player.
LoadStats()
bool LoadStats (ParamsReadContext ctx, int version) inline private
References GetPCO().
ResetAllStats()
void ResetAllStats () inline private
References GetPCO().
SaveStats()
void SaveStats (ParamsWriteContext ctx) inline private
References GetGame(), GetPCO(), and CGame::SaveVersion().
SetAllowLogs()
void SetAllowLogs (bool enable) inline private
References m_AllowLogs.
Field Documentation
m_AllowLogs
bool m_AllowLogs private
Referenced by GetAllowLogs(), and SetAllowLogs().
m_PCOhandler
ref PCOHandlerStats m_PCOhandler = new PCOHandlerStats() private
Referenced by GetPCO().
m_Player
Man m_Player private
Referenced by Init().
m_PlayerStats
ref array<ref PlayerStatBase> m_PlayerStats private
m_PlayerStatsDebug
ref array<ref StatDebugObject> m_PlayerStatsDebug private
m_SyncTimer
ref Timer m_SyncTimer private
m_System
string m_System = "Stats" private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerStats/PlayerStats.c