DayZ Scripts: ActionCarHornBase Class Reference
ActionCarHornBase Class Reference
Static Private Member Functions
static bool ActionCondition (PlayerBase player)
static void SetCarHornState (CarHornActionData pActionData, int pState)
static protected bool PlayerIsDriver (Transport trans, PlayerBase player)
static protected bool BatteryIsVital (ItemBase battery)
Detailed Description
Definition at line 1 of file ActionCarHorn.c.
Member Function Documentation
ActionCondition()
static bool ActionCondition (PlayerBase player) inline static private
Definition at line 3 of file ActionCarHorn.c.
References BatteryIsVital(), Class::CastTo(), HumanCommandVehicle::GetTransport(), and PlayerIsDriver().
Referenced by ActionCondition(), and ActionCarHornLong::ActionCondition().
BatteryIsVital()
static protected bool BatteryIsVital (ItemBase battery) inline static private
Definition at line 44 of file ActionCarHorn.c.
References GameConstants::STATE_DAMAGED.
Referenced by ActionCondition().
PlayerIsDriver()
static protected bool PlayerIsDriver (Transport trans, PlayerBase player) inline static private
Definition at line 39 of file ActionCarHorn.c.
Referenced by ActionCondition().
SetCarHornState()
static void SetCarHornState (CarHornActionData pActionData, int pState) inline static private
Definition at line 28 of file ActionCarHorn.c.
References CarHornActionData::m_Car, and ActionData::m_Player.
Referenced by OnEndInput(), ActionCarHornLong::OnEndInput(), OnEndServer(), ActionCarHornLong::OnEndServer(), OnStartServer(), and ActionCarHornLong::OnStartServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/Vehicles/ActionCarHorn.c