DayZ Scripts: EnProfilerTests Class Reference
EnProfilerTests Class Reference
Private Member Functions
void EnProfilerTests ()
void ~EnProfilerTests ()
TFResult TestToggling ()
TFResult TestTogglingImmediate ()
TFResult TestSetFlags ()
TFResult TestClearFlags ()
TFResult TestAddFlags ()
TFResult TestModule ()
TFResult TestClassTimeData ()
TFResult TestClassCountData ()
TFResult TestFuncTimeData ()
TFResult TestFuncCountData ()
float Sleep (float timeS)
float StringFormat ()
float StringConcat ()
void TestFuncCountDataHelper ()
Static Private Member Functions
static void TestFuncCountDataHelperStatic ()
Private Attributes
bool m_bWasProfilerEnabled
Remember this, so we can restore the previous state before the test!
Detailed Description
Definition at line 1 of file EnProfilerTests.c.
Constructor & Destructor Documentation
EnProfilerTests()
void EnProfilerTests () inline private
Definition at line 9 of file EnProfilerTests.c.
References AddInitTest(), EnProfiler::IsEnabledC(), and m_bWasProfilerEnabled.
~EnProfilerTests()
void ~EnProfilerTests () inline private
Definition at line 28 of file EnProfilerTests.c.
References EnProfiler::Enable(), and m_bWasProfilerEnabled.
Member Function Documentation
Sleep()
float Sleep (float timeS) inline private
Definition at line 707 of file EnProfilerTests.c.
References GetGame(), and CGame::GetTickTime().
Referenced by TestModule().
StringConcat()
float StringConcat () inline private
Definition at line 734 of file EnProfilerTests.c.
References GetGame(), CGame::GetTickTime(), and Type.
Referenced by TestFuncTimeData().
StringFormat()
float StringFormat () inline private
Definition at line 720 of file EnProfilerTests.c.
References GetGame(), CGame::GetTickTime(), and Type.
Referenced by TestFuncTimeData().
TestAddFlags()
TFResult TestAddFlags () inline private
Definition at line 157 of file EnProfilerTests.c.
References EnProfiler::AddFlags(), Assert(), EnProfiler::ClearFlags(), EnProfiler::GetFlags(), NTFR(), and EnProfiler::SetFlags().
TestClassCountData()
TFResult TestClassCountData () inline private
Definition at line 429 of file EnProfilerTests.c.
References Assert(), EnProfiler::Enable(), EnProfiler::GetAllocationsOfClass(), EnProfiler::GetInstancesOfClass(), NTFR(), EnProfiler::RequestImmediateData(), and Debug::TFLog().
TestClassTimeData()
TFResult TestClassTimeData () inline private
Definition at line 381 of file EnProfilerTests.c.
References Math::AbsFloat(), Assert(), EnProfiler::Enable(), EnProfiler::GetTimeOfClass(), EnProfiler::GetTimeResolution(), NTFR(), EnProfiler::RequestImmediateData(), EnProfiler::SetTimeResolution(), and Debug::TFLog().
TestClearFlags()
TFResult TestClearFlags () inline private
Definition at line 120 of file EnProfilerTests.c.
References Assert(), EnProfiler::ClearFlags(), EnProfiler::GetFlags(), NTFR(), EnProfiler::RemoveFlags(), and EnProfiler::SetFlags().
TestFuncCountData()
TFResult TestFuncCountData () inline private
Definition at line 544 of file EnProfilerTests.c.
References Assert(), ScriptModule::Call(), ScriptModule::CallFunction(), ScriptModule::CallFunctionParams(), EnProfiler::Enable(), ErrorEx, CGame::GameScript, EnProfiler::GetCountOfFunc(), EnProfiler::GetCountOfFuncG(), GetDayZGame(), GetGame(), CGame::GetHostName(), ErrorModuleHandler::GetInstance(), CGame::IsServer(), NTFR(), EnProfiler::RequestImmediateData(), TestFuncCountDataHelper(), TestFuncCountDataHelperStatic(), and Type.
TestFuncCountDataHelper()
void TestFuncCountDataHelper () inline private
Definition at line 748 of file EnProfilerTests.c.
Referenced by TestFuncCountData().
TestFuncCountDataHelperStatic()
static void TestFuncCountDataHelperStatic () inline static private
Definition at line 755 of file EnProfilerTests.c.
Referenced by TestFuncCountData().
TestFuncTimeData()
TFResult TestFuncTimeData () inline private
Definition at line 481 of file EnProfilerTests.c.
References Math::AbsFloat(), Assert(), EnProfiler::Enable(), EnProfiler::GetTimeOfFunc(), EnProfiler::GetTimeResolution(), NTFR(), EnProfiler::RequestImmediateData(), EnProfiler::SetTimeResolution(), StringConcat(), StringFormat(), Debug::TFLog(), and Type.
TestModule()
TFResult TestModule () inline private
Definition at line 189 of file EnProfilerTests.c.
References Assert(), BTFR(), EnProfiler::Enable(), EnProfiler::GetFlags(), EnProfiler::GetModule(), EnProfiler::GetTimeOfFunc(), EnProfiler::GetTimePerClass(), EnProfiler::GetTimePerFunc(), EnProfiler::GetTimeResolution(), EnProfiler::NameToModule(), NTFR(), EnProfiler::RemoveFlags(), EnProfiler::RequestImmediateData(), EnProfiler::ResetSession(), EnProfiler::SetFlags(), EnProfiler::SetModule(), EnProfiler::SetTimeResolution(), Sleep(), EnProfiler::SortData(), EnumTools::StringToEnum(), Debug::TFLog(), and Type.
TestSetFlags()
TFResult TestSetFlags () inline private
Definition at line 67 of file EnProfilerTests.c.
References Assert(), EnumTools::GetEnumSize(), EnumTools::GetEnumValue(), EnProfiler::GetFlags(), NTFR(), and EnProfiler::SetFlags().
TestToggling()
TFResult TestToggling () inline private
Definition at line 37 of file EnProfilerTests.c.
References Assert(), BTFR(), EnProfiler::Enable(), EnProfiler::IsEnabledP(), and NTFR().
TestTogglingImmediate()
TFResult TestTogglingImmediate () inline private
Definition at line 52 of file EnProfilerTests.c.
References Assert(), BTFR(), EnProfiler::Enable(), EnProfiler::IsEnabledC(), and NTFR().
Field Documentation
m_bWasProfilerEnabled
bool m_bWasProfilerEnabled private
Remember this, so we can restore the previous state before the test!
Definition at line 4 of file EnProfilerTests.c.
Referenced by EnProfilerTests(), and ~EnProfilerTests().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/TFTests/EnProfilerTests.c