DayZ Scripts: DamageData Class Reference
DamageData Class Reference
Private Member Functions
void DamageData (float value_global, float value_blood, float value_shock)
float GetValueGlobal ()
float GetValueShock ()
float GetValueBlood ()
Private Attributes
float m_ValueGlobal
float m_ValueBlood
float m_ValueShock
Detailed Description
Definition at line 1 of file DamageData.c.
Constructor & Destructor Documentation
DamageData()
void DamageData (float value_global, float value_blood, float value_shock) inline private
Definition at line 7 of file DamageData.c.
References m_ValueBlood, m_ValueGlobal, and m_ValueShock.
Member Function Documentation
GetValueBlood()
float GetValueBlood () inline private
Definition at line 24 of file DamageData.c.
References m_ValueBlood.
Referenced by UpdateDamageWidget().
GetValueGlobal()
float GetValueGlobal () inline private
Definition at line 14 of file DamageData.c.
References m_ValueGlobal.
Referenced by UpdateDamageWidget().
GetValueShock()
float GetValueShock () inline private
Definition at line 19 of file DamageData.c.
References m_ValueShock.
Referenced by UpdateDamageWidget().
Field Documentation
m_ValueBlood
float m_ValueBlood private
Definition at line 4 of file DamageData.c.
Referenced by DamageData(), and GetValueBlood().
m_ValueGlobal
float m_ValueGlobal private
Definition at line 3 of file DamageData.c.
Referenced by DamageData(), and GetValueGlobal().
m_ValueShock
float m_ValueShock private
Definition at line 5 of file DamageData.c.
Referenced by DamageData(), and GetValueShock().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/RemotePlayerDebug/DamageData.c