DayZ Scripts: OnlineServices Class Reference
OnlineServices Class Reference
Static Private Member Functions
static void Init ()
static bool IsInitialized ()
static void GetClientServices ()
static bool ErrorCaught (EBiosError error)
static void LoadServers (notnull GetServersInput inputValues)
static void GetFavoriteServers (TStringArray favServers)
static void GetCachedFavServerInfo (array< ref CachedServerInfo > favServersInfoCache)
static void SetServerFavorited (string ipAddress, int port, int steamQueryPort, bool is_favorited)
static void GetCurrentServerInfo (string ip, int port)
static GetServersResultRow GetCurrentServerInfo ()
static void ClearCurrentServerInfo ()
static void SetInviteServerInfo (string ip, int port)
static void GetInviteServerInfo (out string ip, out int port)
static void OnLoadServersAsync (GetServersResult result_list, EBiosError error, string response)
static void LoadFriends ()
static void ShowUserProfile (string uid)
static void OnUserProfileAsync (EBiosError error)
static void OnFriendsAsync (BiosFriendInfoArray friend_list, EBiosError error)
static void LoadPermissions (array< string > player_list)
static void OnPermissionsAsync (BiosPrivacyUidResultArray result_list, EBiosError error)
static bool IsPlayerMuted (string id)
static bool MutePlayer (string id, bool mute)
static map< string, bool > GetMuteList ()
static void ShowInviteScreen ()
static void LoadMPPrivilege ()
static void LoadVoicePrivilege ()
static void OnLoadMPPrivilege (EBiosError err)
static void OnLoadVoicePrivilege (EBiosError err)
static void SetSessionHandle (string handle)
static string GetSessionHandle ()
static void GetSession ()
static BiosUser GetBiosUser ()
static void SetBiosUser (BiosUser user)
static bool GetMultiplayState ()
static void SetMultiplayState (bool state)
static void EnterGameplaySession ()
static void LeaveGameplaySession ()
static void SetGameplayActivity ()
static void SetPendingInviteList (array< string > invitees)
static array< string > GetPendingInviteList ()
static void ClearPendingInviteList (array< string > invitees)
static void AutoConnectToEmptyServer ()
static GetServersResultRow GetRandomFreeResult (GetFirstServerWithEmptySlotResult results)
static void OnAutoConnectToEmptyServer (GetFirstServerWithEmptySlotResult result_list, EBiosError error)
static void GetServerModList (string server_id)
static void OnGetServerModList (GetServerModListResult result_list, EBiosError error)
static bool IsGameTrial (bool sim)
static bool IsGameActive (bool sim)
static bool CheckUpdate ()
static void PromptUpdate ()
Static Private Attributes
static ref ScriptInvoker m_FriendsAsyncInvoker = new ScriptInvoker()
static ref ScriptInvoker m_PermissionsAsyncInvoker = new ScriptInvoker()
static ref ScriptInvoker m_ServersAsyncInvoker = new ScriptInvoker()
static ref ScriptInvoker m_ServerAsyncInvoker = new ScriptInvoker()
static ref ScriptInvoker m_MuteUpdateAsyncInvoker = new ScriptInvoker()
static ref ScriptInvoker m_ServerModLoadAsyncInvoker = new ScriptInvoker()
static ref BiosClientServices m_ClientServices
static ref TrialService m_TrialService
static protected string m_InviteServerIP
static protected int m_InviteServerPort
static protected string m_CurrentServerIP
static protected int m_CurrentServerPort
static protected ref GetServersResultRow m_CurrentServerInfo
static protected ref map< string, ref BiosFriendInfo > m_FriendsList
static protected ref map< string, bool > m_MuteList
static protected ref map< string, ref BiosPrivacyPermissionResultArray > m_PermissionsList
static protected bool m_FirstFriendsLoad = true
static protected bool m_MultiplayState = false
static protected ref array< string > m_PendingInvites
static protected ref BiosUser m_BiosUser
static int m_AutoConnectTries = 0
Detailed Description
Definition at line 1 of file OnlineServices.c.
Member Function Documentation
AutoConnectToEmptyServer()
static void AutoConnectToEmptyServer () inline static private
Definition at line 621 of file OnlineServices.c.
References GetClientServices(), BiosLobbyService::GetFirstServerWithEmptySlot(), BiosClientServices::GetLobbyService(), m_AutoConnectTries, m_ClientServices, and GetFirstServerWithEmptySlotInput::SetOfficial().
Referenced by UIScriptedMenu::AutoConnect().
CheckUpdate()
static bool CheckUpdate () inline static private
Definition at line 721 of file OnlineServices.c.
References BiosPackageService::CheckUpdateAsync(), GetClientServices(), BiosClientServices::GetPackageService(), and m_ClientServices.
Referenced by DayZIntroSceneXbox::CheckXboxClientUpdate().
ClearCurrentServerInfo()
static void ClearCurrentServerInfo () inline static private
Definition at line 175 of file OnlineServices.c.
References m_CurrentServerInfo, m_CurrentServerIP, and m_CurrentServerPort.
Referenced by CGame::OnEvent().
ClearPendingInviteList()
static void ClearPendingInviteList (array< string > invitees) inline static private
Definition at line 615 of file OnlineServices.c.
References m_PendingInvites.
EnterGameplaySession()
static void EnterGameplaySession () inline static private
Definition at line 528 of file OnlineServices.c.
References BiosSessionService::EnterGameplaySessionAsync(), GetClientServices(), GetGame(), BiosClientServices::GetSessionService(), m_ClientServices, and SetMultiplayState().
Referenced by CGame::OnEvent().
ErrorCaught()
static bool ErrorCaught (EBiosError error) inline static private
Definition at line 82 of file OnlineServices.c.
References ErrorModuleHandler::GetClientMessage(), and DebugPrint::LogErrorAndTrace().
Referenced by LoadMPPrivilege(), LoadPermissions(), LoadVoicePrivilege(), OnAutoConnectToEmptyServer(), BiosSessionService::OnEnterGameplaySession(), OnFriendsAsync(), OnGetServerModList(), BiosSessionService::OnGetSessionError(), BiosUserManager::OnJoin(), OnLoadMPPrivilege(), OnLoadServersAsync(), OnLoadVoicePrivilege(), OnPermissionsAsync(), BiosPackageService::OnPromptUpdate(), BiosSessionService::OnSetActivity(), BiosSessionService::OnShowInviteToGameplaySession(), BiosPackageService::OnShowStore(), BiosUserManager::OnUserDatabaseId(), BiosUserManager::OnUserLoggedOn(), BiosUserManager::OnUserPicked(), OnUserProfileAsync(), and ShowInviteScreen().
GetBiosUser()
static BiosUser GetBiosUser () inline static private
Definition at line 501 of file OnlineServices.c.
References m_BiosUser.
Referenced by CGame::DisconnectSessionEx().
GetCachedFavServerInfo()
static void GetCachedFavServerInfo (array< ref CachedServerInfo > favServersInfoCache) inline static private
Definition at line 114 of file OnlineServices.c.
References BiosLobbyService::GetCachedFavoriteServerInfo(), BiosClientServices::GetLobbyService(), and m_ClientServices.
Referenced by ServerBrowserTabPc::RefreshList().
GetClientServices()
static void GetClientServices () inline static private
Definition at line 57 of file OnlineServices.c.
References Error(), BiosUser::GetClientServices(), GetGame(), BiosUserManager::GetSelectedUser(), BiosUserManager::GetUserList(), CGame::GetUserManager(), and m_ClientServices.
Referenced by AutoConnectToEmptyServer(), CheckUpdate(), EnterGameplaySession(), GetCurrentServerInfo(), GetServerModList(), GetSession(), GetSessionHandle(), Init(), LeaveGameplaySession(), LoadFriends(), LoadMPPrivilege(), LoadPermissions(), LoadServers(), LoadVoicePrivilege(), PromptUpdate(), SetGameplayActivity(), SetPendingInviteList(), SetServerFavorited(), SetSessionHandle(), ShowInviteScreen(), and ShowUserProfile().
GetCurrentServerInfo() [1/2]
static GetServersResultRow GetCurrentServerInfo () inline static private
Definition at line 167 of file OnlineServices.c.
References g_Game, and m_CurrentServerInfo.
GetCurrentServerInfo() [2/2]
static void GetCurrentServerInfo (string ip, int port) inline static private
Definition at line 139 of file OnlineServices.c.
References GetClientServices(), BiosClientServices::GetLobbyService(), BiosLobbyService::GetServers(), m_ClientServices, m_CurrentServerIP, m_CurrentServerPort, GetServersInput::m_Page, GetServersInput::m_Platform, GetServersInput::m_RowsPerPage, GetServersInput::SetHostIp(), and GetServersInput::SetHostPort().
Referenced by CGame::RefreshCurrentServerInfo(), and UIScriptedMenu::SetServerInfo().
GetFavoriteServers()
static void GetFavoriteServers (TStringArray favServers) inline static private
Definition at line 109 of file OnlineServices.c.
References BiosLobbyService::GetFavoriteServers(), BiosClientServices::GetLobbyService(), and m_ClientServices.
Referenced by UIScriptedMenu::LoadFavoriteServers().
GetInviteServerInfo()
static void GetInviteServerInfo (out string ip, out int port) inline static private
Definition at line 188 of file OnlineServices.c.
References m_InviteServerIP, and m_InviteServerPort.
Referenced by UIScriptedMenu::Update().
GetMultiplayState()
static bool GetMultiplayState () inline static private
Definition at line 512 of file OnlineServices.c.
References m_MultiplayState.
Referenced by ClientData::SyncEvent_OnRecievedPlayerList().
GetMuteList()
static map< string, bool > GetMuteList () inline static private
Definition at line 387 of file OnlineServices.c.
References m_MuteList.
Referenced by UIScriptedMenu::Init().
GetPendingInviteList()
static array< string > GetPendingInviteList () inline static private
Definition at line 594 of file OnlineServices.c.
References ClientData::GetSimplePlayerList(), and m_PendingInvites.
Referenced by BiosSessionService::OnEnterGameplaySession(), and SetPendingInviteList().
GetRandomFreeResult()
static GetServersResultRow GetRandomFreeResult (GetFirstServerWithEmptySlotResult results) inline static private
Definition at line 633 of file OnlineServices.c.
References GetFirstServerWithEmptySlotResult::m_Result, and GetServersResult::m_Results.
Referenced by OnAutoConnectToEmptyServer().
GetServerModList()
static void GetServerModList (string server_id) inline static private
Definition at line 682 of file OnlineServices.c.
References GetClientServices(), BiosClientServices::GetLobbyService(), BiosLobbyService::GetServerModList(), and m_ClientServices.
Referenced by ScriptedWidgetEventHandler::SetExpand().
GetSession()
static void GetSession () inline static private
Definition at line 492 of file OnlineServices.c.
References GetClientServices(), GetSessionHandle(), BiosClientServices::GetSessionService(), m_ClientServices, and BiosSessionService::TryGetSession().
Referenced by BiosUserManager::OnJoin(), and CGame::TryConnect().
GetSessionHandle()
static string GetSessionHandle () inline static private
Definition at line 482 of file OnlineServices.c.
References GetClientServices(), BiosClientServices::GetSessionService(), m_ClientServices, and BiosSessionService::m_CurrentHandle.
Referenced by GetSession().
Init()
static void Init () inline static private
Definition at line 30 of file OnlineServices.c.
References GetClientServices(), m_FriendsList, m_MuteList, m_PermissionsList, and m_TrialService.
Referenced by CGame::OnEvent().
IsGameActive()
static bool IsGameActive (bool sim) inline static private
Definition at line 710 of file OnlineServices.c.
References TrialService::IsGameActive(), and m_TrialService.
Referenced by CGame::IsDigitalCopy().
IsGameTrial()
static bool IsGameTrial (bool sim) inline static private
Definition at line 699 of file OnlineServices.c.
References TrialService::IsGameTrial(), and m_TrialService.
IsInitialized()
static bool IsInitialized () inline static private
Definition at line 52 of file OnlineServices.c.
References m_ClientServices.
IsPlayerMuted()
static bool IsPlayerMuted (string id) inline static private
Definition at line 357 of file OnlineServices.c.
References m_MuteList.
Referenced by UIScriptedMenu::Init(), and ScriptedWidgetEventHandler::ReloadLocal().
LeaveGameplaySession()
static void LeaveGameplaySession () inline static private
Definition at line 543 of file OnlineServices.c.
References GetClientServices(), BiosClientServices::GetSessionService(), BiosSessionService::LeaveGameplaySessionAsync(), m_ClientServices, m_CurrentServerInfo, m_CurrentServerIP, m_CurrentServerPort, m_FirstFriendsLoad, m_FriendsList, and SetMultiplayState().
Referenced by CGame::OnEvent().
LoadFriends()
static void LoadFriends () inline static private
Definition at line 234 of file OnlineServices.c.
References GetClientServices(), BiosSocialService::GetFriendsAsync(), BiosClientServices::GetSocialService(), DebugPrint::LogErrorAndTrace(), and m_ClientServices.
Referenced by ClientData::SyncEvent_OnRecievedPlayerList().
LoadMPPrivilege()
static void LoadMPPrivilege () inline static private
Definition at line 412 of file OnlineServices.c.
References ErrorCaught(), GetClientServices(), BiosClientServices::GetPrivacyService(), BiosPrivacyService::GetPrivilegeAsync(), DebugPrint::LogErrorAndTrace(), m_ClientServices, and OnLoadMPPrivilege().
Referenced by CGame::ConnectFromServerBrowser(), ConnectErrorScriptModuleUI::OnModalResult(), and CGame::SelectGamepad().
LoadPermissions()
static void LoadPermissions (array< string > player_list) inline static private
Definition at line 311 of file OnlineServices.c.
References ErrorCaught(), GetClientServices(), BiosPrivacyService::GetPermissionsAsync(), BiosClientServices::GetPrivacyService(), DebugPrint::LogErrorAndTrace(), and m_ClientServices.
Referenced by ClientData::SyncEvent_OnRecievedPlayerList().
LoadServers()
static void LoadServers (notnull GetServersInput inputValues) inline static private
Definition at line 96 of file OnlineServices.c.
References GetClientServices(), BiosClientServices::GetLobbyService(), BiosLobbyService::GetServers(), DebugPrint::LogErrorAndTrace(), and m_ClientServices.
Referenced by GetNextPage(), ServerBrowserTabConsolePages::RefreshList(), ServerBrowserTabPc::RefreshList(), and RefreshList().
LoadVoicePrivilege()
static void LoadVoicePrivilege () inline static private
Definition at line 429 of file OnlineServices.c.
References ErrorCaught(), GetClientServices(), BiosClientServices::GetPrivacyService(), BiosPrivacyService::GetPrivilegeAsync(), DebugPrint::LogErrorAndTrace(), and m_ClientServices.
Referenced by CGame::OnEvent().
MutePlayer()
static bool MutePlayer (string id, bool mute) inline static private
Definition at line 366 of file OnlineServices.c.
References INPUT_UDT_USER_MUTE_XBOX, m_MuteList, ScriptInputUserData::Send(), and Serializer::Write().
Referenced by ScriptedWidgetEventHandler::ToggleMute().
OnAutoConnectToEmptyServer()
static void OnAutoConnectToEmptyServer (GetFirstServerWithEmptySlotResult result_list, EBiosError error) inline static private
Definition at line 652 of file OnlineServices.c.
References ErrorCaught(), g_Game, BiosLobbyService::GetFirstServerWithEmptySlot(), GetGame(), BiosClientServices::GetLobbyService(), GetRandomFreeResult(), CGame::GetUIManager(), m_AutoConnectTries, m_ClientServices, GetFirstServerWithEmptySlotInput::SetOfficial(), and UIManager::ShowDialog().
Referenced by BiosLobbyService::OnGetFirstServerWithEmptySlot().
OnFriendsAsync()
static void OnFriendsAsync (BiosFriendInfoArray friend_list, EBiosError error) inline static private
Definition at line 265 of file OnlineServices.c.
References NotificationSystem::AddNotification(), BiosFriendInfo::Compare(), ErrorCaught(), ScriptInvoker::Invoke(), m_FirstFriendsLoad, m_FriendsAsyncInvoker, m_FriendsList, ClientData::m_LastNewPlayers, SyncPlayerList::m_PlayerList, and BiosFriendInfo::m_Uid.
Referenced by BiosSocialService::OnFriendsAsync().
OnGetServerModList()
static void OnGetServerModList (GetServerModListResult result_list, EBiosError error) inline static private
Definition at line 691 of file OnlineServices.c.
References ErrorCaught(), ScriptInvoker::Invoke(), and m_ServerModLoadAsyncInvoker.
Referenced by BiosLobbyService::OnServerModList().
OnLoadMPPrivilege()
static void OnLoadMPPrivilege (EBiosError err) inline static private
Definition at line 442 of file OnlineServices.c.
References ErrorCaught(), and g_Game.
Referenced by LoadMPPrivilege(), and BiosPrivacyService::OnPrivilege().
OnLoadServersAsync()
static void OnLoadServersAsync (GetServersResult result_list, EBiosError error, string response) inline static private
Definition at line 194 of file OnlineServices.c.
References ErrorCaught(), ScriptInvoker::Invoke(), m_CurrentServerInfo, m_CurrentServerIP, m_CurrentServerPort, GetServersResult::m_Results, and m_ServersAsyncInvoker.
Referenced by BiosLobbyService::OnDoneAsync().
OnLoadVoicePrivilege()
static void OnLoadVoicePrivilege (EBiosError err) inline static private
Definition at line 462 of file OnlineServices.c.
References World::DisableReceiveVoN(), World::DisableTransmitVoN(), ErrorCaught(), g_Game, GetGame(), and CGame::GetWorld().
Referenced by BiosPrivacyService::OnPrivilege().
OnPermissionsAsync()
static void OnPermissionsAsync (BiosPrivacyUidResultArray result_list, EBiosError error) inline static private
Definition at line 327 of file OnlineServices.c.
References BiosPrivacyPermissionResult::Compare(), ErrorCaught(), ScriptInvoker::Invoke(), m_PermissionsAsyncInvoker, m_PermissionsList, BiosPrivacyUidResult::m_Results, and BiosPrivacyUidResult::m_Uid.
Referenced by BiosPrivacyService::OnPermissions().
OnUserProfileAsync()
static void OnUserProfileAsync (EBiosError error) inline static private
Definition at line 260 of file OnlineServices.c.
References ErrorCaught().
Referenced by BiosSocialService::OnUserProfileAsync().
PromptUpdate()
static void PromptUpdate () inline static private
Definition at line 737 of file OnlineServices.c.
References GetClientServices(), BiosClientServices::GetPackageService(), m_ClientServices, and BiosPackageService::PromptUpdateAsync().
Referenced by BiosPackageService::OnCheckUpdate().
SetBiosUser()
static void SetBiosUser (BiosUser user) inline static private
Definition at line 506 of file OnlineServices.c.
References m_BiosUser.
Referenced by BiosUserManager::OnJoin(), and CGame::SelectGamepad().
SetGameplayActivity()
static void SetGameplayActivity () inline static private
Definition at line 561 of file OnlineServices.c.
References GetClientServices(), GetGame(), BiosClientServices::GetSessionService(), m_ClientServices, and BiosSessionService::SetGameplayActivityAsync().
SetInviteServerInfo()
static void SetInviteServerInfo (string ip, int port) inline static private
Definition at line 182 of file OnlineServices.c.
References m_InviteServerIP, and m_InviteServerPort.
Referenced by BiosSessionService::OnGetGameplaySession().
SetMultiplayState()
static void SetMultiplayState (bool state) inline static private
Definition at line 517 of file OnlineServices.c.
References BiosClientServices::GetSessionService(), ClientData::GetSimplePlayerList(), m_ClientServices, m_MultiplayState, and BiosSessionService::SetMultiplayState().
Referenced by EnterGameplaySession(), LeaveGameplaySession(), CGame::OnEvent(), CGame::OnMPConnectionLostEvent(), DayZPlayer::ShowDeadScreen(), and ClientData::SyncEvent_OnRecievedPlayerList().
SetPendingInviteList()
static void SetPendingInviteList (array< string > invitees) inline static private
Definition at line 575 of file OnlineServices.c.
References GetClientServices(), GetGame(), GetPendingInviteList(), BiosClientServices::GetSessionService(), BiosSessionService::InviteToGameplaySessionAsync(), m_ClientServices, and m_PendingInvites.
Referenced by BiosUserManager::OnPartyHost().
SetServerFavorited()
static void SetServerFavorited (string ipAddress, int port, int steamQueryPort, bool is_favorited) inline static private
Definition at line 119 of file OnlineServices.c.
References BiosLobbyService::AddServerFavorite(), GetClientServices(), BiosClientServices::GetLobbyService(), DebugPrint::LogErrorAndTrace(), m_ClientServices, and BiosLobbyService::RemoveServerFavorite().
Referenced by ScriptedWidgetEventHandler::ToggleFavorite().
SetSessionHandle()
static void SetSessionHandle (string handle) inline static private
Definition at line 473 of file OnlineServices.c.
References GetClientServices(), BiosClientServices::GetSessionService(), m_ClientServices, and BiosSessionService::m_CurrentHandle.
Referenced by BiosUserManager::OnJoin().
ShowInviteScreen()
static void ShowInviteScreen () inline static private
Definition at line 392 of file OnlineServices.c.
References ErrorCaught(), GetClientServices(), GetGame(), BiosClientServices::GetSessionService(), DebugPrint::LogErrorAndTrace(), m_ClientServices, and BiosSessionService::ShowInviteToGameplaySessionAsync().
Referenced by UIScriptedMenu::OnClick().
ShowUserProfile()
static void ShowUserProfile (string uid) inline static private
Definition at line 247 of file OnlineServices.c.
References GetClientServices(), BiosClientServices::GetSocialService(), DebugPrint::LogErrorAndTrace(), m_ClientServices, and BiosSocialService::ShowUserProfileAsync().
Referenced by ScriptedWidgetEventHandler::OnDoubleClick(), and UIScriptedMenu::Update().
Field Documentation
m_AutoConnectTries
int m_AutoConnectTries = 0 static private
Definition at line 620 of file OnlineServices.c.
Referenced by AutoConnectToEmptyServer(), and OnAutoConnectToEmptyServer().
m_BiosUser
protected ref BiosUser m_BiosUser static private
Definition at line 28 of file OnlineServices.c.
Referenced by GetBiosUser(), and SetBiosUser().
m_ClientServices
ref BiosClientServices m_ClientServices static private
Definition at line 10 of file OnlineServices.c.
Referenced by AutoConnectToEmptyServer(), CheckUpdate(), EnterGameplaySession(), GetCachedFavServerInfo(), GetClientServices(), GetCurrentServerInfo(), GetFavoriteServers(), GetServerModList(), GetSession(), GetSessionHandle(), IsInitialized(), LeaveGameplaySession(), LoadFriends(), LoadMPPrivilege(), LoadPermissions(), LoadServers(), LoadVoicePrivilege(), OnAutoConnectToEmptyServer(), PromptUpdate(), SetGameplayActivity(), SetMultiplayState(), SetPendingInviteList(), SetServerFavorited(), SetSessionHandle(), ShowInviteScreen(), ShowUserProfile(), and ClientData::SyncEvent_OnRecievedPlayerList().
m_CurrentServerInfo
protected ref GetServersResultRow m_CurrentServerInfo static private
Definition at line 17 of file OnlineServices.c.
Referenced by ClearCurrentServerInfo(), GetCurrentServerInfo(), LeaveGameplaySession(), and OnLoadServersAsync().
m_CurrentServerIP
protected string m_CurrentServerIP static private
Definition at line 15 of file OnlineServices.c.
Referenced by ClearCurrentServerInfo(), GetCurrentServerInfo(), LeaveGameplaySession(), and OnLoadServersAsync().
m_CurrentServerPort
protected int m_CurrentServerPort static private
Definition at line 16 of file OnlineServices.c.
Referenced by ClearCurrentServerInfo(), GetCurrentServerInfo(), LeaveGameplaySession(), and OnLoadServersAsync().
m_FirstFriendsLoad
protected bool m_FirstFriendsLoad = true static private
Definition at line 24 of file OnlineServices.c.
Referenced by LeaveGameplaySession(), and OnFriendsAsync().
m_FriendsAsyncInvoker
ref ScriptInvoker m_FriendsAsyncInvoker = new ScriptInvoker() static private
Definition at line 3 of file OnlineServices.c.
Referenced by OnFriendsAsync().
m_FriendsList
protected ref map<string, ref BiosFriendInfo> m_FriendsList static private
Definition at line 20 of file OnlineServices.c.
Referenced by Init(), LeaveGameplaySession(), and OnFriendsAsync().
m_InviteServerIP
protected string m_InviteServerIP static private
Definition at line 13 of file OnlineServices.c.
Referenced by GetInviteServerInfo(), and SetInviteServerInfo().
m_InviteServerPort
protected int m_InviteServerPort static private
Definition at line 14 of file OnlineServices.c.
Referenced by GetInviteServerInfo(), and SetInviteServerInfo().
m_MultiplayState
protected bool m_MultiplayState = false static private
Definition at line 25 of file OnlineServices.c.
Referenced by GetMultiplayState(), and SetMultiplayState().
m_MuteList
protected ref map<string, bool> m_MuteList static private
Definition at line 21 of file OnlineServices.c.
Referenced by GetMuteList(), Init(), IsPlayerMuted(), and MutePlayer().
m_MuteUpdateAsyncInvoker
ref ScriptInvoker m_MuteUpdateAsyncInvoker = new ScriptInvoker() static private
Definition at line 7 of file OnlineServices.c.
m_PendingInvites
protected ref array<string> m_PendingInvites static private
Definition at line 26 of file OnlineServices.c.
Referenced by ClearPendingInviteList(), GetPendingInviteList(), and SetPendingInviteList().
m_PermissionsAsyncInvoker
ref ScriptInvoker m_PermissionsAsyncInvoker = new ScriptInvoker() static private
Definition at line 4 of file OnlineServices.c.
Referenced by UIScriptedMenu::Init(), OnPermissionsAsync(), and UIScriptedMenu::~InGameMenuXbox().
m_PermissionsList
protected ref map<string, ref BiosPrivacyPermissionResultArray> m_PermissionsList static private
Definition at line 22 of file OnlineServices.c.
Referenced by Init(), and OnPermissionsAsync().
m_ServerAsyncInvoker
ref ScriptInvoker m_ServerAsyncInvoker = new ScriptInvoker() static private
Definition at line 6 of file OnlineServices.c.
m_ServerModLoadAsyncInvoker
ref ScriptInvoker m_ServerModLoadAsyncInvoker = new ScriptInvoker() static private
Definition at line 8 of file OnlineServices.c.
Referenced by UIScriptedMenu::Init(), OnGetServerModList(), and UIScriptedMenu::~ServerBrowserMenuNew().
m_ServersAsyncInvoker
ref ScriptInvoker m_ServersAsyncInvoker = new ScriptInvoker() static private
Definition at line 5 of file OnlineServices.c.
Referenced by UIScriptedMenu::Init(), ServerBrowserTab::LoadingServersStop(), OnLoadServersAsync(), ServerBrowserTab::RefreshList(), UIScriptedMenu::SetServersLoadingTab(), and UIScriptedMenu::~ServerBrowserMenuNew().
m_TrialService
ref TrialService m_TrialService static private
Definition at line 11 of file OnlineServices.c.
Referenced by Init(), IsGameActive(), and IsGameTrial().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Client/OnlineServices.c