DayZ Scripts: ActionGetOutTransport Class Reference
ActionGetOutTransport Class Reference
Private Member Functions
void ActionGetOutTransport ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
void ProcessGetOutTransportActionData (Transport veh, GetOutTransportActionData got_action_data)
override void OnStart (ActionData action_data)
override void OnStartServer (ActionData action_data)
void Unhide (PlayerBase player)
override void OnUpdate (ActionData action_data)
override bool CanBeUsedInRestrain ()
override bool CanBeUsedInVehicle ()
override int GetActionCategory ()
override void OnEnd (ActionData action_data)
override void OnEndServer (ActionData action_data)
void ApplyJumpOutDmg (ActionData action_data)
void ProcessGetOutActionData (Car car, GetOutTransportActionData got_action_data)
Private Attributes
const int DMG_FACTOR = 60
const int SHOCK_FACTOR = 15
const int LOW_SPEED_VALUE = 20
const int HIGH_SPEED_VALUE = 30
protected const float CAR_JUMPOUT_THRESHOLD = 8.0
protected const float BOAT_JUMPOUT_THRESHOLD = 5.0
const int HEALTH_LOW_SPEED_VALUE = 30
const int HEALTH_HIGH_SPEED_VALUE = 70
int m_DmgFactor
int m_ShockFactor
Constructor & Destructor Documentation
ActionGetOutTransport()
void ActionGetOutTransport () inline private
References ActionBase::m_StanceMask, and ActionBase::m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References HumanCommandVehicle::GetTransport(), and Transport::IsAreaAtDoorFree().
ApplyJumpOutDmg()
void ApplyJumpOutDmg (ActionData action_data) inline private
References Class::CastTo(), GetOutTransportActionData::m_Vehicle, and BoatScript::OnVehicleJumpOutServer().
Referenced by OnEndServer().
CanBeUsedInRestrain()
override bool CanBeUsedInRestrain () inline private
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle () inline private
CreateActionData()
override ActionData CreateActionData () inline private
References ActionData.
CreateConditionComponents()
override void CreateConditionComponents () inline private
References ActionBase::m_ConditionItem, and ActionBase::m_ConditionTarget.
GetActionCategory()
override int GetActionCategory () inline private
References AC_INTERACT.
GetInputType()
override GetInputType () inline private
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
References GetOutTransportActionData::m_WasJumpingOutAnim.
HasProgress()
override bool HasProgress () inline private
OnEnd()
override void OnEnd (ActionData action_data) inline private
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
References ApplyJumpOutDmg(), GetOutTransportActionData::m_Speed, GetOutTransportActionData::m_Vehicle, GetOutTransportActionData::m_WasJumpingOut, and GetOutTransportActionData::m_WasJumpingOutAnim.
OnStart()
override void OnStart (ActionData action_data) inline private
References GetDayZGame(), HumanCommandVehicle::GetOutVehicle(), HumanCommandVehicle::GetTransport(), HumanCommandVehicle::JumpOutVehicle(), GetOutTransportActionData::m_WasJumpingOutAnim, and ProcessGetOutTransportActionData().
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
References Class::CastTo(), and HumanCommandVehicle::GetTransport().
OnUpdate()
override void OnUpdate (ActionData action_data) inline private
References End(), and UA_START.
ProcessGetOutActionData()
void ProcessGetOutActionData (Car car, GetOutTransportActionData got_action_data) private
ProcessGetOutTransportActionData()
void ProcessGetOutTransportActionData (Transport veh, GetOutTransportActionData got_action_data) inline private
References BOAT_JUMPOUT_THRESHOLD, CAR_JUMPOUT_THRESHOLD, dBodyGetVelocityAt(), GetOutTransportActionData::m_JumpingOutThreshold, GetOutTransportActionData::m_Speed, GetOutTransportActionData::m_Vehicle, GetOutTransportActionData::m_WasJumpingOut, GetOutTransportActionData::m_WasJumpingOutAnim, and vector::Normalize().
Referenced by OnStart(), and SetupAction().
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
References Serializer::Read().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
References HumanCommandVehicle::GetTransport(), and ProcessGetOutTransportActionData().
Unhide()
void Unhide (PlayerBase player) private
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
References GetOutTransportActionData::m_WasJumpingOutAnim, and Serializer::Write().
Field Documentation
BOAT_JUMPOUT_THRESHOLD
protected const float BOAT_JUMPOUT_THRESHOLD = 5.0 private
Referenced by ProcessGetOutTransportActionData().
CAR_JUMPOUT_THRESHOLD
protected const float CAR_JUMPOUT_THRESHOLD = 8.0 private
Referenced by ProcessGetOutTransportActionData().
DMG_FACTOR
const int DMG_FACTOR = 60 private
Referenced by OnVehicleJumpOutServer().
HEALTH_HIGH_SPEED_VALUE
const int HEALTH_HIGH_SPEED_VALUE = 70 private
Referenced by BoatScript::OnVehicleJumpOutServer(), and OnVehicleJumpOutServer().
HEALTH_LOW_SPEED_VALUE
const int HEALTH_LOW_SPEED_VALUE = 30 private
Referenced by BoatScript::OnVehicleJumpOutServer(), and OnVehicleJumpOutServer().
HIGH_SPEED_VALUE
const int HIGH_SPEED_VALUE = 30 private
Referenced by OnVehicleJumpOutServer().
LOW_SPEED_VALUE
const int LOW_SPEED_VALUE = 20 private
Referenced by OnVehicleJumpOutServer().
m_DmgFactor
int m_DmgFactor private
m_ShockFactor
int m_ShockFactor private
SHOCK_FACTOR
const int SHOCK_FACTOR = 15 private
Referenced by OnVehicleJumpOutServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionGetOutTransport.c