DayZ Scripts: AnniversaryFireworksLauncherClientEvent Class Reference
AnniversaryFireworksLauncherClientEvent Class Reference
Private Member Functions
override protected int GetExplParticleFromSequence ()
override protected void SetupLight (PointLightBase light)
override protected void SpawnSecondaryExplosion ()
Member Function Documentation
GetExplParticleFromSequence()
override protected int GetExplParticleFromSequence () inline private
References ErrorEx, ParticleList::FIREWORKS_EXPLOSION_RED, ParticleList::FIREWORKS_EXPLOSION_THANKS1, ParticleList::FIREWORKS_EXPLOSION_THANKS2, ParticleList::FIREWORKS_EXPLOSION_THANKS3, ParticleList::FIREWORKS_EXPLOSION_THANKS4, ParticleList::FIREWORKS_EXPLOSION_THANKS5, and FireworksLauncherClientEvent::m_Color.
Referenced by OnExplode().
SetupLight()
override protected void SetupLight (PointLightBase light) inline private
References ErrorEx, and FireworksLauncherClientEvent::m_Color.
SpawnSecondaryExplosion()
override protected void SpawnSecondaryExplosion () inline private
References FireworksLauncherClientEvent::GetExplosionPosition(), FireworksLauncherClientEvent::m_Events, FireworksLauncherClientEvent::m_Index, FireworksLauncherClientEvent::m_Item, and FireworksLauncherClientEvent::RequestSecondaryExplosion().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Gear/Tools/FireworksLauncherAnniversary.c