DayZ Scripts: StaminaSoundHandlerBase Class Reference
StaminaSoundHandlerBase Class Reference
Private Member Functions
void PostponeStamina (float time)
override void Update ()
Private Attributes
float m_PostponeTime = -1
float m_LastTick
bool m_UpdateTimerRunning
bool m_StaminaUpEndPlayed = true
ref Timer m_ClientCharacterTick = new Timer
ref Timer m_ClientCharacterDistanceCheck = new Timer
Member Function Documentation
PostponeStamina()
void PostponeStamina (float time) inline private
References GetGame(), and CGame::GetTime().
Update()
override void Update () inline private
References GetGame(), GetTime(), m_Player, and DayZPlayer::PlaySoundEvent().
Field Documentation
m_ClientCharacterDistanceCheck
ref Timer m_ClientCharacterDistanceCheck = new Timer private
m_ClientCharacterTick
ref Timer m_ClientCharacterTick = new Timer private
m_LastTick
float m_LastTick private
m_PostponeTime
float m_PostponeTime = -1 private
m_StaminaUpEndPlayed
bool m_StaminaUpEndPlayed = true private
m_UpdateTimerRunning
bool m_UpdateTimerRunning private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/StaminaSoundHandler.c