DayZ Scripts: ActionRepairTentPart Class Reference
ActionRepairTentPart Class Reference
Private Member Functions
void ActionRepairTentPart ()
override void CreateConditionComponents ()
override bool IsUsingProxies ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override ActionData CreateActionData ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Private Attributes
m_LastValidType
string m_CurrentDamageZone = ""
int m_LastValidComponentIndex = -1
Constructor & Destructor Documentation
ActionRepairTentPart()
void ActionRepairTentPart () inline private
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Class::CastTo(), GetPlugin(), m_CurrentDamageZone, m_LastValidComponentIndex, m_LastValidType, and GameConstants::STATE_RUINED.
CreateActionData()
override ActionData CreateActionData () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
References RepairTentPartActionReciveData::m_DamageZoneRecived.
HasTarget()
override bool HasTarget () inline private
Referenced by ReadFromContext(), and WriteToContext().
IsUsingProxies()
override bool IsUsingProxies () inline private
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References GetGame(), m_CurrentDamageZone, ActionData::m_MainItem, and ActionData::m_Target.
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
References HasTarget(), RepairTentPartActionReciveData::m_DamageZoneRecived, and Serializer::Read().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
References Class::CastTo(), HasTarget(), m_CurrentDamageZone, and Serializer::Write().
Field Documentation
m_CurrentDamageZone
string m_CurrentDamageZone = "" private
Referenced by ActionCondition(), OnFinishProgressServer(), and WriteToContext().
m_LastValidComponentIndex
int m_LastValidComponentIndex = -1 private
Referenced by ActionCondition().
m_LastValidType
m_LastValidType private
Referenced by ActionCondition().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionRepairTentPart.c