DayZ Scripts: HitDirectionImagesBase Class Reference
HitDirectionImagesBase Class Reference
Private Member Functions
void HitDirectionImagesBase ()
protected void PerformRegisterImages ()
protected void RegisterImage (string layout_path, string image_name)
protected void RandomizeImageIdx ()
protected array< string > GetTypeLayoutPathArray ()
protected array< string > GetTypeImagePathArray ()
void GetCurrentImageData (out Widget layout, out Widget image)
Layout should be sufficient for generic manipulation of the hit image.
Private Attributes
int m_ImageIndex
Detailed Description
Definition at line 2 of file HitDirectionImagesBase.c.
Constructor & Destructor Documentation
HitDirectionImagesBase()
void HitDirectionImagesBase () inline private
Definition at line 6 of file HitDirectionImagesBase.c.
References GetTypeImagePathArray(), GetTypeLayoutPathArray(), PerformRegisterImages(), and RandomizeImageIdx().
Member Function Documentation
GetCurrentImageData()
void GetCurrentImageData (out Widget layout, out Widget image) inline private
Layout should be sufficient for generic manipulation of the hit image.
Definition at line 40 of file HitDirectionImagesBase.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), GetTypeImagePathArray(), GetTypeLayoutPathArray(), CGame::GetWorkspace(), and m_ImageIndex.
Referenced by HitDirectionEffectBase::HitDirectionEffectBase().
GetTypeImagePathArray()
protected array< string > GetTypeImagePathArray () inline private
Definition at line 37 of file HitDirectionImagesBase.c.
Referenced by GetCurrentImageData(), HitDirectionImagesBase(), RandomizeImageIdx(), and RegisterImage().
GetTypeLayoutPathArray()
protected array< string > GetTypeLayoutPathArray () inline private
Definition at line 36 of file HitDirectionImagesBase.c.
Referenced by GetCurrentImageData(), HitDirectionImagesBase(), and RegisterImage().
PerformRegisterImages()
protected void PerformRegisterImages () inline private
Definition at line 16 of file HitDirectionImagesBase.c.
Referenced by HitDirectionImagesBase().
RandomizeImageIdx()
protected void RandomizeImageIdx () inline private
Definition at line 31 of file HitDirectionImagesBase.c.
References Count, GetTypeImagePathArray(), m_ImageIndex, and Math::RandomIntInclusive().
Referenced by HitDirectionImagesBase().
RegisterImage()
protected void RegisterImage (string layout_path, string image_name) inline private
Definition at line 25 of file HitDirectionImagesBase.c.
References GetTypeImagePathArray(), and GetTypeLayoutPathArray().
Field Documentation
m_ImageIndex
int m_ImageIndex private
Definition at line 4 of file HitDirectionImagesBase.c.
Referenced by GetCurrentImageData(), and RandomizeImageIdx().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/HitIndication/HitDirectionImages/HitDirectionImagesBase.c