DayZ Scripts: AttachmentsWrapper Class Reference
AttachmentsWrapper Class Reference
Private Member Functions
void AttachmentsWrapper (LayoutHolder parent)
void SetParent (Attachments atts)
override bool Select ()
override bool SelectItem ()
override bool Combine ()
override bool TransferItemToVicinity ()
override bool TransferItem ()
override bool InspectItem ()
override bool SplitItem ()
override bool EquipItem ()
override bool CanEquip ()
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool IsDisplayable ()
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override void UpdateInterval ()
int GetFocusedSlot ()
void ShowFalseAttachmentsHeader (bool show)
void SetFalseAttachmentsHeaderText (string text)
TextWidget GetFalseHeaderTextWidget ()
Private Attributes
Attachments m_Attachments
protected Widget m_AttachmentsFalseHeader
protected RichTextWidget m_AttachmentsFalseHeaderText
Detailed Description
Definition at line 1 of file AttachmentsWrapper.c.
Constructor & Destructor Documentation
AttachmentsWrapper()
void AttachmentsWrapper (LayoutHolder parent) inline private
Definition at line 7 of file AttachmentsWrapper.c.
References m_AttachmentsFalseHeader, m_AttachmentsFalseHeaderText, and m_RootWidget.
Member Function Documentation
CanCombine()
override bool CanCombine () inline private
Definition at line 64 of file AttachmentsWrapper.c.
References Attachments::CanCombine(), and m_Attachments.
CanCombineAmmo()
override bool CanCombineAmmo () inline private
Definition at line 69 of file AttachmentsWrapper.c.
References Attachments::CanCombineAmmo(), and m_Attachments.
CanEquip()
override bool CanEquip () inline private
Definition at line 59 of file AttachmentsWrapper.c.
References Attachments::CanEquip(), and m_Attachments.
Combine()
override bool Combine () inline private
Definition at line 29 of file AttachmentsWrapper.c.
References Attachments::Combine(), and m_Attachments.
EquipItem()
override bool EquipItem () inline private
Definition at line 54 of file AttachmentsWrapper.c.
References Attachments::EquipItem(), and m_Attachments.
GetFalseHeaderTextWidget()
TextWidget GetFalseHeaderTextWidget () inline private
Definition at line 110 of file AttachmentsWrapper.c.
References m_AttachmentsFalseHeaderText.
Referenced by Attachments::GetFalseHeaderTextWidget().
GetFocusedSlot()
int GetFocusedSlot () inline private
Definition at line 95 of file AttachmentsWrapper.c.
References Attachments::GetFocusedSlot(), and m_Attachments.
InspectItem()
override bool InspectItem () inline private
Definition at line 44 of file AttachmentsWrapper.c.
References Attachments::InspectItem(), and m_Attachments.
IsDisplayable()
override bool IsDisplayable () inline private
Definition at line 74 of file AttachmentsWrapper.c.
References Container::IsEmpty().
IsItemActive()
override bool IsItemActive () inline private
Definition at line 79 of file AttachmentsWrapper.c.
References Attachments::IsItemActive(), and m_Attachments.
IsItemWithQuantityActive()
override bool IsItemWithQuantityActive () inline private
Definition at line 84 of file AttachmentsWrapper.c.
References Attachments::IsItemWithQuantityActive(), and m_Attachments.
Select()
override bool Select () inline private
Definition at line 19 of file AttachmentsWrapper.c.
References m_Attachments, and Attachments::Select().
SelectItem()
override bool SelectItem () inline private
Definition at line 24 of file AttachmentsWrapper.c.
References m_Attachments, and Attachments::SelectItem().
SetFalseAttachmentsHeaderText()
void SetFalseAttachmentsHeaderText (string text) inline private
Definition at line 105 of file AttachmentsWrapper.c.
References m_AttachmentsFalseHeaderText.
Referenced by Attachments::InitAttachmentGrid(), and Attachments::SetFalseAttachmentsHeaderText().
SetParent()
void SetParent (Attachments atts) inline private
Definition at line 14 of file AttachmentsWrapper.c.
References m_Attachments.
Referenced by Attachments::InitAttachmentGrid().
ShowFalseAttachmentsHeader()
void ShowFalseAttachmentsHeader (bool show) inline private
Definition at line 100 of file AttachmentsWrapper.c.
References m_AttachmentsFalseHeader.
Referenced by Attachments::ShowFalseAttachmentsHeader().
SplitItem()
override bool SplitItem () inline private
Definition at line 49 of file AttachmentsWrapper.c.
References m_Attachments, and Attachments::SplitItem().
TransferItem()
override bool TransferItem () inline private
Definition at line 39 of file AttachmentsWrapper.c.
References m_Attachments, and Attachments::TransferItem().
TransferItemToVicinity()
override bool TransferItemToVicinity () inline private
Definition at line 34 of file AttachmentsWrapper.c.
References m_Attachments, and Attachments::TransferItemToVicinity().
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 89 of file AttachmentsWrapper.c.
References m_Attachments, and Attachments::UpdateInterval().
Field Documentation
m_Attachments
Attachments m_Attachments private
Definition at line 3 of file AttachmentsWrapper.c.
Referenced by CanCombine(), CanCombineAmmo(), CanEquip(), Combine(), EquipItem(), GetFocusedSlot(), InspectItem(), IsItemActive(), IsItemWithQuantityActive(), Select(), SelectItem(), SetParent(), SplitItem(), TransferItem(), TransferItemToVicinity(), and UpdateInterval().
m_AttachmentsFalseHeader
protected Widget m_AttachmentsFalseHeader private
Definition at line 4 of file AttachmentsWrapper.c.
Referenced by AttachmentsWrapper(), and ShowFalseAttachmentsHeader().
m_AttachmentsFalseHeaderText
protected RichTextWidget m_AttachmentsFalseHeaderText private
Definition at line 5 of file AttachmentsWrapper.c.
Referenced by AttachmentsWrapper(), GetFalseHeaderTextWidget(), and SetFalseAttachmentsHeaderText().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Containers/AttachmentsWrapper.c