DayZ Scripts: BloodTypes Class Reference
BloodTypes Class Reference
Static Private Member Functions
static int GenerateBloodType ()
static bool MatchBloodCompatibility (int bloodtypetarget, int bloodtype)
static string GetBloodTypeName (int bloodtype, out string type, out bool positive)
Static Private Attributes
static const int NUM_OF_BLOOD_TYPES = 8
Detailed Description
Definition at line 1 of file BloodType.c.
Member Function Documentation
GenerateBloodType()
static int GenerateBloodType () inline static private
Definition at line 7 of file BloodType.c.
References LIQUID_BLOOD_0_N, LIQUID_BLOOD_0_P, LIQUID_BLOOD_A_N, LIQUID_BLOOD_A_P, LIQUID_BLOOD_AB_N, LIQUID_BLOOD_AB_P, LIQUID_BLOOD_B_N, LIQUID_BLOOD_B_P, NUM_OF_BLOOD_TYPES, and Math::RandomInt().
Referenced by PlayerStatsPCO_Base::Init().
GetBloodTypeName()
static string GetBloodTypeName (int bloodtype, out string type, out bool positive) inline static private
Definition at line 89 of file BloodType.c.
References LIQUID_BLOOD_0_N, LIQUID_BLOOD_0_P, LIQUID_BLOOD_A_N, LIQUID_BLOOD_A_P, LIQUID_BLOOD_AB_N, LIQUID_BLOOD_AB_P, LIQUID_BLOOD_B_N, and LIQUID_BLOOD_B_P.
Referenced by RecipeBase::Do(), ActionTestBloodTarget::OnFinishProgressClient(), Hud::UpdateBloodName(), UIScriptedMenu::UpdateItemInfoLiquidType(), and HudDebugWinBase::UpdateValues().
MatchBloodCompatibility()
static bool MatchBloodCompatibility (int bloodtypetarget, int bloodtype) inline static private
Definition at line 39 of file BloodType.c.
References LIQUID_BLOOD_0_N, LIQUID_BLOOD_0_P, LIQUID_BLOOD_A_N, LIQUID_BLOOD_A_P, LIQUID_BLOOD_AB_N, LIQUID_BLOOD_AB_P, LIQUID_BLOOD_B_N, LIQUID_BLOOD_B_P, and Debug::Log().
Referenced by CAContinuousQuantityBloodTransfer::CalcAndSetQuantity(), ActionGiveBloodSelf::OnEndServer(), and ActionGiveBloodTarget::OnEndServer().
Field Documentation
NUM_OF_BLOOD_TYPES
const int NUM_OF_BLOOD_TYPES = 8 static private
Definition at line 3 of file BloodType.c.
Referenced by GenerateBloodType().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/BloodType.c