DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionPushObject.c File Reference
ActionPushObject.c File Reference
Data Structures
class ActionPushObjectDataReceiveData
class CAContinuousRepeatPushObject
class ActionPushObject
Functions
override void CreateActionComponent ()
override void ProgressActionComponent ()
override void EndActionComponent ()
protected void ApplyForce (ActionPushObjectData actionData)
Variables
ActionPushObjectDataReceiveData m_NeedUpdate
int m_EndType = 0
vector m_Origin = "0 0 0"
Object m_Object
CAContinuousRepeatPushObject PUSH_FORCE_INCREMENT = 3000.0
protected ActionPushObjectData m_ActionDataPushObject
Function Documentation
ApplyForce()
protected void ApplyForce (ActionPushObjectData actionData)
References dBodyApplyImpulseAt(), dBodyGetMass(), Easing::EaseInOutSine(), PUSH_FORCE_INCREMENT, and vector::Zero.
CreateActionComponent()
override void CreateActionComponent ()
EndActionComponent()
override void EndActionComponent ()
References ActionContinuousBase::HasAlternativeInterrupt(), m_ActionDataPushObject, ActionBaseCB::SetCommand(), UA_CANCEL, and UA_FINISHED.
ProgressActionComponent()
override void ProgressActionComponent ()
References ApplyForce().
Variable Documentation
m_ActionDataPushObject
protected ActionPushObjectData m_ActionDataPushObject
Referenced by EndActionComponent().
m_EndType
int m_EndType = 0
m_NeedUpdate
ActionPushObjectDataReceiveData m_NeedUpdate
m_Object
Object m_Object
Referenced by GetObject().
m_Origin
vector m_Origin = "0 0 0"
PUSH_FORCE_INCREMENT
CAContinuousRepeatPushObject PUSH_FORCE_INCREMENT = 3000.0
Referenced by ApplyForce().