DayZ Scripts: ScriptConsoleSoundsTab Class Reference
ScriptConsoleSoundsTab Class Reference
Private Member Functions
void ScriptConsoleSoundsTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void ~ScriptConsoleSoundsTab (Widget root)
override bool OnChange (Widget w, int x, int y, bool finished)
void UpdateMousePos ()
protected void PrepareFilters (string filter, out TStringArray filters)
protected void ChangeFilter (TStringArray classes, TextListboxWidget widget, EditBoxWidget filterWidget, int categoryMask=-1, bool ignoreScope=false)
override void Update (float timeslice)
protected void HandleKeys ()
protected void SetMapPos (vector pos)
protected vector GetMapPos ()
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
protected TStringArray GetSoundClasses ()
protected void ChangeFilterSound ()
Private Attributes
protected bool m_PlayerPosRefreshBlocked
protected vector m_MapPos
protected ButtonWidget m_CopySoundset
protected ButtonWidget m_PlaySoundset
protected ButtonWidget m_PlaySoundsetLooped
protected ButtonWidget m_StopSoundset
protected EditBoxWidget m_SoundFilter
protected TextListboxWidget m_SoundsTextListbox
protected ref Timer m_RefreshFilterTimer = new Timer()
protected MapWidget m_DebugMapWidget
protected TextWidget m_MapDistWidget
protected TextWidget m_MouseCurPos
protected TextWidget m_MapHeadingWidget
Static Private Attributes
static protected float DEBUG_MAP_ZOOM = 1
static protected EffectSound m_SoundSet
Constructor & Destructor Documentation
ScriptConsoleSoundsTab()
void ScriptConsoleSoundsTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline private
References ChangeFilterSound(), DEBUG_MAP_ZOOM, GetGame(), GetPlayer(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_CopySoundset, m_DebugMapWidget, m_MapDistWidget, m_MapHeadingWidget, m_MouseCurPos, m_PlaySoundset, m_PlaySoundsetLooped, m_SoundFilter, m_SoundsTextListbox, m_StopSoundset, SetMapPos(), MapWidget::SetMapPos(), and MapWidget::SetScale().
~ScriptConsoleSoundsTab()
void ~ScriptConsoleSoundsTab (Widget root) inline private
References DEBUG_MAP_ZOOM, MapWidget::GetScale(), and m_DebugMapWidget.
Member Function Documentation
ChangeFilter()
protected void ChangeFilter (TStringArray classes, TextListboxWidget widget, EditBoxWidget filterWidget, int categoryMask = -1, bool ignoreScope = false) inline private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), string::Contains(), GetGame(), PrepareFilters(), and string::ToLower().
Referenced by ChangeFilterSound().
ChangeFilterSound()
protected void ChangeFilterSound () inline private
References ChangeFilter(), GetSoundClasses(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_SoundFilter, and m_SoundsTextListbox.
Referenced by OnClick(), and ScriptConsoleSoundsTab().
GetMapPos()
protected vector GetMapPos () inline private
References m_MapPos.
Referenced by HandleKeys(), OnClick(), Update(), and UpdateMousePos().
GetSoundClasses()
protected TStringArray GetSoundClasses () inline private
References CFG_SOUND_SETS.
Referenced by ChangeFilterSound().
HandleKeys()
protected void HandleKeys () inline private
References GetMapPos(), KeyState(), m_SoundSet, m_SoundsTextListbox, SEffectManager::PlaySoundEnviroment(), EffectSound::SetAutodestroy(), and EffectSound::Stop().
Referenced by Update().
OnChange()
override bool OnChange (Widget w, int x, int y, bool finished) inline private
References m_RefreshFilterTimer, m_SoundFilter, x, and y.
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References ScriptConsoleTabBase::AddItemToClipboard(), ChangeFilterSound(), GetMapPos(), m_CopySoundset, m_PlaySoundset, m_PlaySoundsetLooped, m_SoundFilter, m_SoundSet, m_SoundsTextListbox, m_StopSoundset, SEffectManager::PlaySoundEnviroment(), EffectSound::Stop(), x, and y.
OnMouseButtonDown()
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
References GetGame(), GetMousePos(), GetPlayer(), m_DebugMapWidget, m_PlayerPosRefreshBlocked, MapWidget::ScreenToMap(), SetMapPos(), CGame::SurfaceY(), x, and y.
PrepareFilters()
protected void PrepareFilters (string filter, out TStringArray filters) inline private
References string::Split(), string::ToLower(), and string::Trim().
Referenced by ChangeFilter().
SetMapPos()
protected void SetMapPos (vector pos) inline private
References m_MapPos.
Referenced by OnMouseButtonDown(), and ScriptConsoleSoundsTab().
Update()
override void Update (float timeslice) inline private
References MapWidget::AddUserMark(), MapWidget::ClearUserMarks(), COLOR_GREEN, COLOR_RED, GetGame(), GetMapPos(), GetPlayer(), HandleKeys(), m_DebugMapWidget, and UpdateMousePos().
UpdateMousePos()
void UpdateMousePos () inline private
References Math3D::AngleFromPosition(), CGame::GetCurrentCameraDirection(), GetGame(), GetMapPos(), GetMousePos(), CGame::GetPlayer(), GetPlayer(), m_DebugMapWidget, m_MapDistWidget, m_MapHeadingWidget, m_MouseCurPos, Math::RAD2DEG, MapWidget::ScreenToMap(), CGame::SurfaceY(), float::ToString(), x, and y.
Referenced by Update().
Field Documentation
DEBUG_MAP_ZOOM
protected float DEBUG_MAP_ZOOM = 1 static private
Referenced by ScriptConsoleSoundsTab(), and ~ScriptConsoleSoundsTab().
m_CopySoundset
protected ButtonWidget m_CopySoundset private
Referenced by OnClick(), and ScriptConsoleSoundsTab().
m_DebugMapWidget
protected MapWidget m_DebugMapWidget private
Referenced by OnMouseButtonDown(), ScriptConsoleSoundsTab(), Update(), UpdateMousePos(), and ~ScriptConsoleSoundsTab().
m_MapDistWidget
protected TextWidget m_MapDistWidget private
Referenced by ScriptConsoleSoundsTab(), and UpdateMousePos().
m_MapHeadingWidget
protected TextWidget m_MapHeadingWidget private
Referenced by ScriptConsoleSoundsTab(), and UpdateMousePos().
m_MapPos
protected vector m_MapPos private
Referenced by GetMapPos(), and SetMapPos().
m_MouseCurPos
protected TextWidget m_MouseCurPos private
Referenced by ScriptConsoleSoundsTab(), and UpdateMousePos().
m_PlayerPosRefreshBlocked
protected bool m_PlayerPosRefreshBlocked private
Referenced by OnMouseButtonDown().
m_PlaySoundset
protected ButtonWidget m_PlaySoundset private
Referenced by OnClick(), and ScriptConsoleSoundsTab().
m_PlaySoundsetLooped
protected ButtonWidget m_PlaySoundsetLooped private
Referenced by OnClick(), and ScriptConsoleSoundsTab().
m_RefreshFilterTimer
protected ref Timer m_RefreshFilterTimer = new Timer() private
Referenced by OnChange().
m_SoundFilter
protected EditBoxWidget m_SoundFilter private
Referenced by ChangeFilterSound(), OnChange(), OnClick(), and ScriptConsoleSoundsTab().
m_SoundSet
protected EffectSound m_SoundSet static private
Referenced by HandleKeys(), and OnClick().
m_SoundsTextListbox
protected TextListboxWidget m_SoundsTextListbox private
Referenced by ChangeFilterSound(), HandleKeys(), OnClick(), and ScriptConsoleSoundsTab().
m_StopSoundset
protected ButtonWidget m_StopSoundset private
Referenced by OnClick(), and ScriptConsoleSoundsTab().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptConsoleSoundsTab.c