DayZ Scripts: TrapSpawnBase Class Reference
TrapSpawnBase Class Reference
Private Member Functions
void Trap_FishNet ()
override void OnVariablesSynchronized ()
override void SpawnCatch ()
override bool IsPlaceableAtPosition (vector position)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool IsDeployable ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
void Trap_RabbitSnare ()
override bool CanBePlaced (Man player, vector position)
override void OnVariablesSynchronized ()
override void SetupTrap ()
override void SpawnCatch ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool IsDeployable ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override void SetActions ()
override void AlignCatch (ItemBase obj, string catch_name)
void Trap_SmallFish ()
override void OnVariablesSynchronized ()
override void SpawnCatch ()
override bool IsPlaceableAtPosition (vector position)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
Detailed Description
Definition at line 1 of file Trap_FishNet.c.
Member Function Documentation
AlignCatch()
override void AlignCatch (ItemBase obj, string catch_name) inline private
Definition at line 191 of file Trap_RabbitSnare.c.
References GetDirection(), GetOrientation(), and vector::Perpend().
CanBePlaced()
override bool CanBePlaced (Man player, vector position) inline private
Definition at line 31 of file Trap_RabbitSnare.c.
References g_Game, and m_IsBeingPlaced.
CanReceiveAttachment() [1/2]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 100 of file Trap_FishNet.c.
CanReceiveAttachment() [2/2]
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 96 of file Trap_SmallFish.c.
GetDeploySoundset() [1/2]
override string GetDeploySoundset () inline private
Definition at line 174 of file Trap_FishNet.c.
GetDeploySoundset() [2/2]
override string GetDeploySoundset () inline private
Definition at line 166 of file Trap_RabbitSnare.c.
GetLoopDeploySoundset() [1/2]
override string GetLoopDeploySoundset () inline private
Definition at line 179 of file Trap_FishNet.c.
Referenced by ItemBase::PlayDeployLoopSound().
GetLoopDeploySoundset() [2/2]
override string GetLoopDeploySoundset () inline private
Definition at line 171 of file Trap_RabbitSnare.c.
IsDeployable() [1/2]
override bool IsDeployable () inline private
Definition at line 169 of file Trap_FishNet.c.
IsDeployable() [2/2]
override bool IsDeployable () inline private
Definition at line 161 of file Trap_RabbitSnare.c.
IsPlaceableAtPosition() [1/2]
override bool IsPlaceableAtPosition (vector position) inline private
Definition at line 95 of file Trap_FishNet.c.
Referenced by ActionActivateTrap::ActionCondition(), ItemBase::CanBePlaced(), Hologram::EvaluateCollision(), and ItemBase::IsPlaceable().
IsPlaceableAtPosition() [2/2]
override bool IsPlaceableAtPosition (vector position) inline private
Definition at line 91 of file Trap_SmallFish.c.
OnPlacementComplete() [1/2]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 162 of file Trap_FishNet.c.
References SetIsPlaceSound().
Referenced by ActionActivateTrap::OnFinishProgressServer().
OnPlacementComplete() [2/2]
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 154 of file Trap_RabbitSnare.c.
References SetIsPlaceSound().
OnVariablesSynchronized() [1/3]
override void OnVariablesSynchronized () inline private
Definition at line 29 of file Trap_FishNet.c.
References IsPlaceSound(), and PlayPlaceSound().
OnVariablesSynchronized() [2/3]
override void OnVariablesSynchronized () inline private
Definition at line 43 of file Trap_RabbitSnare.c.
References IsPlaceSound(), and PlayPlaceSound().
OnVariablesSynchronized() [3/3]
override void OnVariablesSynchronized () inline private
Definition at line 28 of file Trap_SmallFish.c.
References IsPlaceSound(), and PlayPlaceSound().
SetActions()
override void SetActions () inline private
Definition at line 176 of file Trap_RabbitSnare.c.
References ActionDeployObject(), AddAction(), and RemoveAction().
SetupTrap()
override void SetupTrap () inline private
Definition at line 53 of file Trap_RabbitSnare.c.
References GetGame(), IsRuined(), SetActive(), SetOrientation(), and SetPosition().
SpawnCatch() [1/3]
override void SpawnCatch () inline private
Definition at line 43 of file Trap_FishNet.c.
References AddDefect(), ECE_NONE, GetGame(), GetPosition, Math::RandomFloat(), and Math::RandomInt().
SpawnCatch() [2/3]
override void SpawnCatch () inline private
Definition at line 80 of file Trap_RabbitSnare.c.
References AddDefect(), ECE_PLACE_ON_SURFACE, GetGame(), Math::RandomFloat(), Math::RandomInt(), and Math::RandomIntInclusive().
SpawnCatch() [3/3]
override void SpawnCatch () inline private
Definition at line 38 of file Trap_SmallFish.c.
References AddDefect(), ECE_NONE, GetGame(), GetPosition, Math::RandomFloat(), and Math::RandomInt().
Trap_FishNet()
void Trap_FishNet () inline private
Definition at line 3 of file Trap_FishNet.c.
References m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DefectRate, m_InitWaitTime, and Math::RandomFloat().
Trap_RabbitSnare()
void Trap_RabbitSnare () inline private
Definition at line 3 of file Trap_RabbitSnare.c.
References m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DefectRate, m_InitWaitTime, and Math::RandomInt().
Trap_SmallFish()
void Trap_SmallFish () inline private
Definition at line 3 of file Trap_SmallFish.c.
References m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DefectRate, m_InitWaitTime, and Math::RandomFloat().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/TrapSpawnBase/Trap_FishNet.c
P:/scripts/4_World/Entities/ItemBase/TrapSpawnBase/Trap_RabbitSnare.c
P:/scripts/4_World/Entities/ItemBase/TrapSpawnBase/Trap_SmallFish.c