DayZ Scripts: BitArray Class Reference
BitArray Class Reference
Static Private Member Functions
static int IDToIndex (int id)
static int IDToMask (int id)
static array< int > CreateMaskArray (int size)
Creates an array which will be able to accomodate 'size' number of unique IDs.
static int GetBitCount (array< int > bit_array)
Returns number of bits this array can hold.
static int IDToNumOfItems (int id)
Returns number of INTs required to hold this ID minus 1(ie for 32, the result is 0, for 33, the result is 1)
static array< int > CreateArrayWithID (int id)
static bool IsMaskContainID (array< int > bit_array, int id)
static bool AddIDToMask (array< int > bit_array, int id)
Detailed Description
Definition at line 5 of file BitArray.c.
Member Function Documentation
AddIDToMask()
static bool AddIDToMask (array< int > bit_array, int id) inline static private
Definition at line 85 of file BitArray.c.
References IDToMask(), and IDToNumOfItems().
CreateArrayWithID()
static array< int > CreateArrayWithID (int id) inline static private
Definition at line 47 of file BitArray.c.
References IDToMask(), and IDToNumOfItems().
CreateMaskArray()
static array< int > CreateMaskArray (int size) inline static private
Creates an array which will be able to accomodate 'size' number of unique IDs.
Definition at line 21 of file BitArray.c.
References IDToNumOfItems().
GetBitCount()
static int GetBitCount (array< int > bit_array) inline static private
Returns number of bits this array can hold.
Definition at line 34 of file BitArray.c.
References BIT_INT_SIZE.
IDToIndex()
static int IDToIndex (int id) inline static private
Definition at line 7 of file BitArray.c.
References BIT_INT_SIZE, and IDToNumOfItems().
Referenced by IDToMask().
IDToMask()
static int IDToMask (int id) inline static private
Definition at line 14 of file BitArray.c.
References IDToIndex().
Referenced by AddIDToMask(), CreateArrayWithID(), and IsMaskContainID().
IDToNumOfItems()
static int IDToNumOfItems (int id) inline static private
Returns number of INTs required to hold this ID minus 1(ie for 32, the result is 0, for 33, the result is 1)
Definition at line 40 of file BitArray.c.
References BIT_INT_SIZE.
Referenced by AddIDToMask(), CreateArrayWithID(), CreateMaskArray(), IDToIndex(), and IsMaskContainID().
IsMaskContainID()
static bool IsMaskContainID (array< int > bit_array, int id) inline static private
Definition at line 62 of file BitArray.c.
References IDToMask(), and IDToNumOfItems().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/BitArray.c