DayZ Scripts: MapWidget Class Reference
MapWidget Class Reference
Private Member Functions
proto native void ClearUserMarks ()
proto native void AddUserMark (vector pos, string text, int color, string texturePath)
proto native vector GetMapPos ()
proto native void SetMapPos (vector worldPos)
proto native float GetScale ()
proto native void SetScale (float scale)
proto native float GetContourInterval ()
proto native float GetCellSize (float pLegendWidth)
proto native vector MapToScreen (vector worldPos)
proto native vector ScreenToMap (vector screenPos)
Member Function Documentation
AddUserMark()
proto native void AddUserMark (vector pos, string text, int color, string texturePath) private
Referenced by ScriptConsoleGeneralTab::Update().
ClearUserMarks()
proto native void ClearUserMarks () private
Referenced by ScriptConsoleGeneralTab::Update().
GetCellSize()
proto native float GetCellSize (float pLegendWidth) private
GetContourInterval()
proto native float GetContourInterval () private
GetMapPos()
proto native vector GetMapPos () private
GetScale()
proto native float GetScale () private
Referenced by ScriptConsoleGeneralTab::~ScriptConsoleGeneralTab().
MapToScreen()
proto native vector MapToScreen (vector worldPos) private
ScreenToMap()
proto native vector ScreenToMap (vector screenPos) private
Referenced by MapHandler::OnDoubleClick(), ScriptConsoleGeneralTab::OnDoubleClick(), MapHandler::OnKeyDown(), ScriptConsoleGeneralTab::OnMouseButtonDown(), and ScriptConsoleGeneralTab::UpdateMousePos().
SetMapPos()
proto native void SetMapPos (vector worldPos) private
Referenced by ScriptConsoleGeneralTab::Init().
SetScale()
proto native void SetScale (float scale) private
Referenced by ScriptConsoleGeneralTab::Init().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/gameplay.c