DayZ Scripts: BiosUser Class Reference
BiosUser Class Reference
Private Member Functions
proto native owned string GetName ()
proto native owned string GetUid ()
proto native BiosClientServices GetClientServices ()
proto native bool IsOnline ()
Detailed Description
Definition at line 8 of file BiosUserManager.c.
Member Function Documentation
GetClientServices()
proto native BiosClientServices GetClientServices () private
Referenced by OnlineServices::GetClientServices().
GetName()
proto native owned string GetName () private
Referenced by DayZIntroScene::GetSelectedUserName(), BiosUserManager::OnGameNameChanged(), UIScriptedMenu::Refresh(), SelectGamepad(), Managed::SetupPlayerName(), and DayZIntroSceneXbox::UpdateSelectedUserName().
GetUid()
proto native owned string GetUid () private
Referenced by ScriptedWidgetEventHandler::IsLocalPlayer(), and UIScriptedMenu::IsLocalPlayer().
IsOnline()
proto native bool IsOnline () private
Referenced by BiosUserManager::OnPartyHost(), and SelectUser().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Services/BiosUserManager.c