DayZ Scripts: HumanInputController Class Reference
HumanInputController Class Reference
Private Member Functions
proto native void SetDisabled (bool pState)
disables input controller
proto void GetMovement (out float pSpeed, out vector pLocalDirection)
returns pSpeed 0,1..2..3 (idle, walk, run, sprint), local normalized direction vector
proto native float GetHeadingAngle ()
returns main heading angle (in radians) -PI .. PI (this is world Y angle player is actualy pointing the camera)
proto native vector GetAimChange ()
returns per tick aim change (in radians)
proto native vector GetAimDelta (float dt)
returns aim change (in radians)
proto native vector GetTracking ()
returns absolute tracking change (in radians)
proto native bool CameraViewChanged ()
1st/3rd person camera view
proto native bool CameraIsFreeLook ()
returns true if freelook is active
proto native void ResetFreeLookToggle ()
reset freelook toggle
proto native bool CameraIsTracking ()
returns if camera is tracking (using IR device)
proto native bool Camera3rdIsRightShoulder ()
returns true if camera is on right/ false-left shoulder
proto native bool IsJumpClimb ()
jump/climb action was pressed
proto native bool IsMeleeEvade ()
returns pressed SHIFT (melee evade)
proto native bool IsMeleeFastAttackModifier ()
returns SHIFT down (melee fast/heavy) attack modifier
proto native int IsMeleeLREvade ()
returns 0,1,2 = none,left,right
proto native bool IsMeleeWeaponAttack ()
return weapon melee attack modifier
proto native bool WeaponWasRaiseClick ()
returns true if weapon click perfomed recently (before raise specifically)
proto native bool IsWeaponRaised ()
returns true if weapon is raised
proto native bool WeaponADS ()
returns true if weapon ADS mode
proto native void ResetADS ()
resets ADS mode to default
proto native bool IsThrowingModeChange ()
returns true if change of throwing mode has been requested
proto native void ResetThrowingMode ()
resets Throwing mode
proto native bool IsWalkToggled ()
returns true if Walk set to toggle
proto native bool IsUseButton ()
Deprecated; returns true if Use/Attack button is pressed (== true for multiple ticks). Synced.
proto native bool IsUseButtonDown ()
Deprecated; returns true if Use/Attack button has just been pressed (== true for 1 tick only). Synced.
proto native bool IsUseItemButton ()
returns true if 'UADefaultAction' button is pressed (== true for multiple ticks). Synced.
proto native bool IsUseItemButtonDown ()
returns true if 'UADefaultAction' button has just been pressed (== true for 1 tick only). Synced.
proto native bool IsAttackButton ()
returns true if 'UAFire' button is pressed (== true for multiple ticks). Synced.
proto native bool IsAttackButtonDown ()
returns true if 'UAFire' button has just been pressed (== true for 1 tick only). Synced.
proto native bool IsSingleUse ()
single 'UADefaultAction' (== true for 1 tick only) + not raised
proto native bool IsContinuousUse ()
Long click 'UADefaultAction' (== true for multiple ticks) + not raised.
proto native bool IsContinuousUseStart ()
is start of cont. 'UADefaultAction' (== true for 1 tick only) + not raised
proto native bool IsContinuousUseEnd ()
is end of cont. 'UADefaultAction' (== true for 1 tick only) + not raised
proto native bool IsImmediateAction ()
proto native bool IsReloadOrMechanismSingleUse ()
weapon handling
proto native bool IsReloadOrMechanismContinuousUse ()
R - reloading / bolting - long press (== true for multiple ticks)
proto native bool IsReloadOrMechanismContinuousUseStart ()
R - reloading / bolting (== true for 1 tick only)
proto native bool IsReloadOrMechanismContinuousUseEnd ()
R - reloading / bolting - long press (== true for multiple ticks)
proto native bool IsZoom ()
zooming
proto native bool IsZoomToggle ()
zooming toggle
proto native void ResetZoomToggle ()
reset zoom toggle
proto native bool IsSightChange ()
sight has been changed (in/out ironsights)
proto native bool IsZoomIn ()
proto native bool IsZoomOut ()
proto native bool IsFireModeChange ()
fire mode has changed
proto native bool IsZeroingUp ()
zeroing up
proto native bool IsZeroingDown ()
zeroing down
proto native bool IsHoldBreath ()
holding breath
proto native void ResetHoldBreath ()
reset hold breath toggle
proto native int IsGestureSlot ()
proto native bool IsOtherController ()
returns true, if player controls other entity (vehicle for example)
proto native int IsQuickBarSlot ()
returns 1..10 if some quickbar slot is used, 0 otherwise
proto native bool IsQuickBarSingleUse ()
proto native bool IsQuickBarContinuousUse ()
proto native bool IsQuickBarContinuousUseStart ()
proto native bool IsQuickBarContinuousUseEnd ()
proto native void LimitsDisableSprint (bool pDisable)
this disables sprint
proto native bool LimitsIsSprintDisabled ()
is sprint disabled
proto native void OverrideMovementSpeed (bool pOverride, float pVal)
proto native void OverrideMovementAngle (bool pOverride, float pVal)
proto native void OverrideAimChangeX (bool pOverride, float pVal)
proto native void OverrideAimChangeY (bool pOverride, float pVal)
proto native void OverrideMeleeEvade (bool pOverride, bool pValue)
proto native void OverrideRaise (bool pOverride, bool pValue)
proto native void Override3rdIsRightShoulder (bool pOverride, bool pValue)
private void HumanInputController ()
never created by script
private void ~HumanInputController ()
never created by script
Detailed Description
Definition at line 14 of file human.c.
Constructor & Destructor Documentation
HumanInputController()
private void HumanInputController () inline private
never created by script
Definition at line 252 of file human.c.
~HumanInputController()
private void ~HumanInputController () inline private
never created by script
Definition at line 257 of file human.c.
Member Function Documentation
Camera3rdIsRightShoulder()
proto native bool Camera3rdIsRightShoulder () private
returns true if camera is on right/ false-left shoulder
Referenced by DayZPlayerCameraBase::DayZPlayerCamera3rdPerson(), DayZPlayerCamera3rdPersonErcRaised::DayZPlayerCamera3rdPersonErcRaisedMelee(), and DayZPlayerCameraBase::OnUpdate().
CameraIsFreeLook()
proto native bool CameraIsFreeLook () private
returns true if freelook is active
Referenced by ManBase::CommandHandler(), SelectCrossHair(), UpdateLRAngle(), UpdateLRAngleLookAt(), UpdateLRAngleUnlocked(), UpdateUDAngle(), and UpdateUDAngleUnlocked().
CameraIsTracking()
proto native bool CameraIsTracking () private
returns if camera is tracking (using IR device)
Referenced by FloatingCrossHair(), UpdateLRAngle(), UpdateLRAngleUnlocked(), UpdateUDAngle(), and UpdateUDAngleUnlocked().
CameraViewChanged()
proto native bool CameraViewChanged () private
1st/3rd person camera view
Referenced by DayZPlayer::HandleView().
GetAimChange()
proto native vector GetAimChange () private
returns per tick aim change (in radians)
Referenced by UpdateLRAngle(), UpdateLRAngleLookAt(), and UpdateUDAngle().
GetAimDelta()
proto native vector GetAimDelta (float dt) private
returns aim change (in radians)
Referenced by DayZPlayerCameraBase::OnUpdate(), UpdateLRAngleUnlocked(), and UpdateUDAngleUnlocked().
GetHeadingAngle()
proto native float GetHeadingAngle () private
returns main heading angle (in radians) -PI .. PI (this is world Y angle player is actualy pointing the camera)
Referenced by FloatingCrossHair(), GetHeadingAngle(), and EntityPlacementCallback::OnSetup().
GetMovement()
proto void GetMovement (out float pSpeed, out vector pLocalDirection) private
returns pSpeed 0,1..2..3 (idle, walk, run, sprint), local normalized direction vector
Referenced by DayZPlayer::HandleView().
GetTracking()
proto native vector GetTracking () private
returns absolute tracking change (in radians)
Referenced by UpdateLRAngle(), UpdateLRAngleUnlocked(), UpdateUDAngle(), and UpdateUDAngleUnlocked().
IsAttackButton()
proto native bool IsAttackButton () private
returns true if 'UAFire' button is pressed (== true for multiple ticks). Synced.
Referenced by DayZPlayerImplementThrowing::HandleThrowing(), DayZPlayer::HandleWeapons(), WeaponStartAction::OnUpdate(), and WeaponStateBase::OnUpdate().
IsAttackButtonDown()
proto native bool IsAttackButtonDown () private
returns true if 'UAFire' button has just been pressed (== true for 1 tick only). Synced.
Referenced by HandleFightLogic(), and DayZPlayer::HandleWeapons().
IsContinuousUse()
proto native bool IsContinuousUse () private
Long click 'UADefaultAction' (== true for multiple ticks) + not raised.
IsContinuousUseEnd()
proto native bool IsContinuousUseEnd () private
is end of cont. 'UADefaultAction' (== true for 1 tick only) + not raised
IsContinuousUseStart()
proto native bool IsContinuousUseStart () private
is start of cont. 'UADefaultAction' (== true for 1 tick only) + not raised
Referenced by Update().
IsFireModeChange()
proto native bool IsFireModeChange () private
fire mode has changed
Referenced by DayZPlayer::HandleWeapons().
IsGestureSlot()
proto native int IsGestureSlot () private
returns 1..12 if F1 - F12 us pressed, 0 otherwise Deprecated; slots no longer used, bindable input actions instead
IsHoldBreath()
proto native bool IsHoldBreath () private
holding breath
Referenced by DayZPlayer::HandleWeapons().
IsImmediateAction()
proto native bool IsImmediateAction () private
is immediate action triggered - 1 tick only Middle Button + not raised !
IsJumpClimb()
proto native bool IsJumpClimb () private
jump/climb action was pressed
Referenced by DayZPlayer::CommandHandler().
IsMeleeEvade()
proto native bool IsMeleeEvade () private
returns pressed SHIFT (melee evade)
IsMeleeFastAttackModifier()
proto native bool IsMeleeFastAttackModifier () private
returns SHIFT down (melee fast/heavy) attack modifier
Referenced by GetAttackTypeFromInputs().
IsMeleeLREvade()
proto native int IsMeleeLREvade () private
returns 0,1,2 = none,left,right
Referenced by HandleFightLogic().
IsMeleeWeaponAttack()
proto native bool IsMeleeWeaponAttack () private
return weapon melee attack modifier
Referenced by DayZPlayer::CommandHandler(), and HandleFightLogic().
IsOtherController()
proto native bool IsOtherController () private
returns true, if player controls other entity (vehicle for example)
IsQuickBarContinuousUse()
proto native bool IsQuickBarContinuousUse () private
Long click use (== true for multiple ticks) long quickbar + not raised !
IsQuickBarContinuousUseEnd()
proto native bool IsQuickBarContinuousUseEnd () private
is end of cont use (== true for 1 tick only) long quickbar + not raised !
Referenced by ManBase::CommandHandler().
IsQuickBarContinuousUseStart()
proto native bool IsQuickBarContinuousUseStart () private
is start of cont use (== true for 1 tick only) long quickbar + not raised !
Referenced by ManBase::CommandHandler().
IsQuickBarSingleUse()
proto native bool IsQuickBarSingleUse () private
single use (== true for 1 tick only) quickbar + not raised !
Referenced by ManBase::CommandHandler().
IsQuickBarSlot()
proto native int IsQuickBarSlot () private
returns 1..10 if some quickbar slot is used, 0 otherwise
Referenced by CancelContinuousUse(), and ManBase::CommandHandler().
IsReloadOrMechanismContinuousUse()
proto native bool IsReloadOrMechanismContinuousUse () private
R - reloading / bolting - long press (== true for multiple ticks)
Referenced by WeaponStartAction::OnUpdate().
IsReloadOrMechanismContinuousUseEnd()
proto native bool IsReloadOrMechanismContinuousUseEnd () private
R - reloading / bolting - long press (== true for multiple ticks)
IsReloadOrMechanismContinuousUseStart()
proto native bool IsReloadOrMechanismContinuousUseStart () private
R - reloading / bolting (== true for 1 tick only)
IsReloadOrMechanismSingleUse()
proto native bool IsReloadOrMechanismSingleUse () private
weapon handling
R - reloading / bolting (== true for 1 tick only)
IsSightChange()
proto native bool IsSightChange () private
sight has been changed (in/out ironsights)
IsSingleUse()
proto native bool IsSingleUse () private
single 'UADefaultAction' (== true for 1 tick only) + not raised
Referenced by Update().
IsThrowingModeChange()
proto native bool IsThrowingModeChange () private
returns true if change of throwing mode has been requested
Referenced by DayZPlayerImplementThrowing::HandleThrowing().
IsUseButton()
proto native bool IsUseButton () private
Deprecated; returns true if Use/Attack button is pressed (== true for multiple ticks). Synced.
Note
Returns state of both 'UADefaultAction' and 'UAFire' input actions. Those are now separated in the methods below.
IsUseButtonDown()
proto native bool IsUseButtonDown () private
Deprecated; returns true if Use/Attack button has just been pressed (== true for 1 tick only). Synced.
Note
Returns state of both 'UADefaultAction' and 'UAFire' input actions. Those are now separated in the methods below.
IsUseItemButton()
proto native bool IsUseItemButton () private
returns true if 'UADefaultAction' button is pressed (== true for multiple ticks). Synced.
IsUseItemButtonDown()
proto native bool IsUseItemButtonDown () private
returns true if 'UADefaultAction' button has just been pressed (== true for 1 tick only). Synced.
IsWalkToggled()
proto native bool IsWalkToggled () private
returns true if Walk set to toggle
IsWeaponRaised()
proto native bool IsWeaponRaised () private
returns true if weapon is raised
Referenced by DayZPlayerImplementThrowing::CanChangeThrowingStance(), DayZPlayerImplementThrowing::CanContinueThrowing(), CanPlayEmote(), HandleFightLogic(), and Update().
IsZeroingDown()
proto native bool IsZeroingDown () private
zeroing down
Referenced by DayZPlayer::HandleWeapons().
IsZeroingUp()
proto native bool IsZeroingUp () private
zeroing up
Referenced by DayZPlayer::HandleWeapons().
IsZoom()
proto native bool IsZoom () private
zooming
IsZoomIn()
proto native bool IsZoomIn () private
IsZoomOut()
proto native bool IsZoomOut () private
IsZoomToggle()
proto native bool IsZoomToggle () private
zooming toggle
Referenced by DayZPlayer::HandleView().
LimitsDisableSprint()
proto native void LimitsDisableSprint (bool pDisable) private
this disables sprint
Referenced by ManBase::CommandHandler(), and MissionBase::PlayerControlEnable().
LimitsIsSprintDisabled()
proto native bool LimitsIsSprintDisabled () private
is sprint disabled
Override3rdIsRightShoulder()
proto native void Override3rdIsRightShoulder (bool pOverride, bool pValue) private
Referenced by DayZPlayerCamera3rdPersonErcRaised::DayZPlayerCamera3rdPersonErcRaisedMelee(), and DayZPlayerCamera3rdPersonErcRaised::~DayZPlayerCamera3rdPersonErcRaisedMelee().
OverrideAimChangeX()
proto native void OverrideAimChangeX (bool pOverride, float pVal) private
OverrideAimChangeY()
proto native void OverrideAimChangeY (bool pOverride, float pVal) private
OverrideMeleeEvade()
proto native void OverrideMeleeEvade (bool pOverride, bool pValue) private
OverrideMovementAngle()
proto native void OverrideMovementAngle (bool pOverride, float pVal) private
OverrideMovementSpeed()
proto native void OverrideMovementSpeed (bool pOverride, float pVal) private
OverrideRaise()
proto native void OverrideRaise (bool pOverride, bool pValue) private
ResetADS()
proto native void ResetADS () private
resets ADS mode to default
Referenced by ManBase::CommandHandler(), and DayZPlayer::HandleADS().
ResetFreeLookToggle()
proto native void ResetFreeLookToggle () private
reset freelook toggle
Referenced by DayZPlayer::HandleADS(), and DayZPlayer::HandleOptic().
ResetHoldBreath()
proto native void ResetHoldBreath () private
reset hold breath toggle
ResetThrowingMode()
proto native void ResetThrowingMode () private
resets Throwing mode
ResetZoomToggle()
proto native void ResetZoomToggle () private
reset zoom toggle
SetDisabled()
proto native void SetDisabled (bool pState) private
disables input controller
WeaponADS()
proto native bool WeaponADS () private
returns true if weapon ADS mode
Referenced by DayZPlayer::HandleADS().
WeaponWasRaiseClick()
proto native bool WeaponWasRaiseClick () private
returns true if weapon click perfomed recently (before raise specifically)
The documentation for this class was generated from the following file:
P:/scripts/3_Game/human.c