DayZ Scripts: HungerNotfr Class Reference
HungerNotfr Class Reference
Private Member Functions
void HungerNotfr (NotifiersManager manager)
override int GetNotifierType ()
override void DisplayTendency (float delta)
override void DisplayBadge ()
override void HideBadge ()
override float GetObservedValue ()
Private Attributes
protected const float DEC_TRESHOLD_LOW = 0
protected const float DEC_TRESHOLD_MED = -0.35
protected const float DEC_TRESHOLD_HIGH = -0.57
protected const float INC_TRESHOLD_LOW = 0
protected const float INC_TRESHOLD_MED = 0.35
protected const float INC_TRESHOLD_HIGH = 0.57
Detailed Description
Definition at line 1 of file HungerNotfr.c.
Constructor & Destructor Documentation
HungerNotfr()
void HungerNotfr (NotifiersManager manager) inline private
Definition at line 10 of file HungerNotfr.c.
Member Function Documentation
DisplayBadge()
override void DisplayBadge () inline private
Definition at line 46 of file HungerNotfr.c.
DisplayTendency()
override void DisplayTendency (float delta) inline private
Definition at line 19 of file HungerNotfr.c.
References NotifierBase::CalculateTendency(), DEC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, GetElement(), NotifierBase::GetVirtualHud(), INC_TRESHOLD_HIGH, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, and NotifierBase::m_Player.
GetNotifierType()
override int GetNotifierType () inline private
Definition at line 14 of file HungerNotfr.c.
GetObservedValue()
override float GetObservedValue () inline private
Definition at line 56 of file HungerNotfr.c.
References NotifierBase::m_Player.
HideBadge()
override void HideBadge () inline private
Definition at line 51 of file HungerNotfr.c.
Field Documentation
DEC_TRESHOLD_HIGH
protected const float DEC_TRESHOLD_HIGH = -0.57 private
Definition at line 5 of file HungerNotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_LOW
protected const float DEC_TRESHOLD_LOW = 0 private
Definition at line 3 of file HungerNotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_MED
protected const float DEC_TRESHOLD_MED = -0.35 private
Definition at line 4 of file HungerNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_HIGH
protected const float INC_TRESHOLD_HIGH = 0.57 private
Definition at line 8 of file HungerNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_LOW
protected const float INC_TRESHOLD_LOW = 0 private
Definition at line 6 of file HungerNotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_MED
protected const float INC_TRESHOLD_MED = 0.35 private
Definition at line 7 of file HungerNotfr.c.
Referenced by DisplayTendency().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerNotifiers/Notifiers/HungerNotfr.c