DayZ Scripts: ActionUnlockDoors Class Reference
ActionUnlockDoors Class Reference
Private Member Functions
void ActionUnlockDoors ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
protected void UnlockDoor (ActionTarget target)
override void OnFinishProgressServer (ActionData action_data)
override bool IsLockTargetOnUse ()
Private Attributes
protected const float APPLIED_DMG = 6
Constructor & Destructor Documentation
ActionUnlockDoors()
void ActionUnlockDoors () inline private
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, ActionBase::m_FullBody, ActionBase::m_StanceMask, and ActionBase::m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Class::CastTo(), UAMaxDistances::DEFAULT, ActionBase::IsBuilding(), and ActionBase::IsInReach().
CreateConditionComponents()
override void CreateConditionComponents () inline private
References ActionBase::m_ConditionItem, and ActionBase::m_ConditionTarget.
IsLockTargetOnUse()
override bool IsLockTargetOnUse () inline private
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References APPLIED_DMG, and UnlockDoor().
UnlockDoor()
protected void UnlockDoor (ActionTarget target) inline private
References Class::CastTo().
Referenced by OnFinishProgressServer().
Field Documentation
APPLIED_DMG
protected const float APPLIED_DMG = 6 private
Referenced by OnFinishProgressServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionUnlockDoors.c