DayZ Scripts: MissionBaseWorld Class Reference
MissionBaseWorld Class Reference
Private Member Functions
void MissionBase ()
void ~MissionBase ()
override ObjectSnapCallback GetInventoryDropCallback ()
override void OnUpdate (float timeslice)
override void OnEvent (EventType eventTypeId, Param params)
void InitialiseWorldData ()
void InitWorldYieldDataDefaults (CatchYieldBank bank)
Used to initialize defaults to WorldData base class from 4_World module. For proper init of your custom world, use 'InitYieldBank' method in the inherited world data.
override WorldLighting GetWorldLighting ()
override WorldData GetWorldData ()
override DynamicMusicPlayer GetDynamicMusicPlayer ()
override UIScriptedMenu CreateScriptedMenu (int id)
void SpawnItems ()
void UpdateInputDevicesAvailability ()
override void OnKeyPress (int key)
void DumpCurrentUILayout ()
void DumpWidget (Widget w, int tabs)
override void OnKeyRelease (int key)
override void OnMouseButtonPress (int button)
override void OnMouseButtonRelease (int button)
void OnLog (string msg_log)
void UpdateDummyScheduler ()
override void AddDummyPlayerToScheduler (Man player)
Private Attributes
PluginDeveloper m_ModuleDeveloper
PluginKeyBinding m_ModuleKeyBinding ref WidgetEventHandler m_WidgetEventHandler
ref WorldData m_WorldData
ref WorldLighting m_WorldLighting
ref array< PlayerBase > m_DummyPlayers = new array<PlayerBase>
autoptr ObjectSnapCallback m_InventoryDropCallback
protected ref DynamicMusicPlayer m_DynamicMusicPlayer
protected ref DynamicMusicPlayerRegistry m_DynamicMusicPlayerRegistry
int m_WidgetsTotal
int m_WidgetsInvisible
PluginAdditionalInfo m_ModuleServerInfo
DEPRECATED.
Constructor & Destructor Documentation
~MissionBase()
void ~MissionBase () inline private
References TriggerEffectManager::DestroyInstance(), GetDayZGame(), GetGame(), and PluginManagerDelete().
Member Function Documentation
AddDummyPlayerToScheduler()
override void AddDummyPlayerToScheduler (Man player) inline private
CreateScriptedMenu()
override UIScriptedMenu CreateScriptedMenu (int id) inline private
References InventoryMenu(), MENU_BOOK, MENU_CAMERA_TOOLS, MENU_CHARACTER, MENU_CHAT_INPUT, MENU_CONNECT_ERROR, MENU_CONTROLS_PRESET, MENU_CREDITS, MENU_EARLYACCESS, MENU_GESTURES, MENU_HELP_SCREEN, MENU_INGAME, MENU_INSPECT, MENU_INVENTORY, MENU_INVITE_TIMER, MENU_KEYBINDINGS, MENU_LOADING, MENU_LOC_ADD, MENU_LOGIN_QUEUE, MENU_LOGIN_TIME, MENU_LOGOUT, MENU_MAIN, MENU_MAP, MENU_MISSION_LOADER, MENU_NOTE, MENU_OPTIONS, MENU_RADIAL_QUICKBAR, MENU_RESPAWN_DIALOGUE, MENU_SCENE_EDITOR, MENU_SCRIPTCONSOLE, MENU_SCRIPTCONSOLE_DIALOG_PRESET_NAME, MENU_SCRIPTCONSOLE_DIALOG_PRESET_RENAME, MENU_SCRIPTCONSOLE_UNIVERSAL_INFO_DIALOG, MENU_SERVER_BROWSER, MENU_STARTUP, MENU_TITLE_SCREEN, MENU_TUTORIAL, MENU_VIDEO, MENU_WARNING_INPUTDEVICE_DISCONNECT, MENU_WARNING_ITEMDROP, MENU_WARNING_TELEPORT, and MENU_XBOX_CONTROLS.
DumpCurrentUILayout()
void DumpCurrentUILayout () inline private
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and Print().
DumpWidget()
void DumpWidget (Widget w, int tabs) inline private
References Print().
GetDynamicMusicPlayer()
override DynamicMusicPlayer GetDynamicMusicPlayer () inline private
GetInventoryDropCallback()
override ObjectSnapCallback GetInventoryDropCallback () inline private
GetWorldData()
override WorldData GetWorldData () inline private
GetWorldLighting()
override WorldLighting GetWorldLighting () inline private
InitialiseWorldData()
void InitialiseWorldData () inline private
References GetGame(), CGame::GetWorldName(), m_DynamicMusicPlayerRegistry, and string::ToLower().
InitWorldYieldDataDefaults()
void InitWorldYieldDataDefaults (CatchYieldBank bank) inline private
Used to initialize defaults to WorldData base class from 4_World module. For proper init of your custom world, use 'InitYieldBank' method in the inherited world data.
References CatchYieldBank::RegisterYieldItem().
MissionBase()
void MissionBase () inline private
References SEffectManager::Cleanup(), DynamicMusicPlayer(), GetDayZGame(), GetUApi(), SoundSetMap::Init(), m_DynamicMusicPlayerRegistry, PluginManagerInit(), SetDispatcher(), UAInputAPI::UpdateControls(), and MissionBase::UpdateInputDevicesAvailability().
OnEvent()
override void OnEvent (EventType eventTypeId, Param params) inline private
OnKeyPress()
override void OnKeyPress (int key) inline private
OnKeyRelease()
override void OnKeyRelease (int key) inline private
References GetGame().
OnLog()
void OnLog (string msg_log) inline private
References GetGame(), and MissionBase::IsServer().
OnMouseButtonPress()
override void OnMouseButtonPress (int button) inline private
References GetGame().
OnMouseButtonRelease()
override void OnMouseButtonRelease (int button) inline private
References GetGame().
OnUpdate()
override void OnUpdate (float timeslice) inline private
SpawnItems()
void SpawnItems () private
UpdateDummyScheduler()
void UpdateDummyScheduler () inline private
UpdateInputDevicesAvailability()
void UpdateInputDevicesAvailability () inline private
References g_Game.
Field Documentation
m_DummyPlayers
ref array<PlayerBase> m_DummyPlayers = new array<PlayerBase> private
m_DynamicMusicPlayer
protected ref DynamicMusicPlayer m_DynamicMusicPlayer private
m_DynamicMusicPlayerRegistry
protected ref DynamicMusicPlayerRegistry m_DynamicMusicPlayerRegistry private
m_InventoryDropCallback
autoptr ObjectSnapCallback m_InventoryDropCallback private
m_ModuleDeveloper
PluginDeveloper m_ModuleDeveloper private
m_ModuleServerInfo
PluginAdditionalInfo m_ModuleServerInfo private
DEPRECATED.
m_WidgetEventHandler
PluginKeyBinding m_ModuleKeyBinding ref WidgetEventHandler m_WidgetEventHandler private
m_WidgetsInvisible
int m_WidgetsInvisible private
m_WidgetsTotal
int m_WidgetsTotal private
m_WorldData
ref WorldData m_WorldData private
m_WorldLighting
ref WorldLighting m_WorldLighting private
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/mission/missionBase.c