DayZ Scripts: WeightDebugData Class Reference
WeightDebugData Class Reference
Private Member Functions
void WeightDebugData (EntityAI entity)
void SetWeight (float weight)
void SetCalcDetails (string details)
void AddCalcDetails (string details)
void Output ()
Private Attributes
string m_Classname
string m_Weight
int m_InventoryDepth
string m_CalcDetails
Detailed Description
Definition at line 702 of file Debug.c.
Constructor & Destructor Documentation
WeightDebugData()
void WeightDebugData (EntityAI entity) inline private
Definition at line 709 of file Debug.c.
References m_Classname, and m_InventoryDepth.
Member Function Documentation
AddCalcDetails()
void AddCalcDetails (string details) inline private
Definition at line 726 of file Debug.c.
References m_CalcDetails.
Referenced by Weapon::GetWeightSpecialized().
Output()
void Output () inline private
Definition at line 731 of file Debug.c.
References m_CalcDetails, m_Classname, m_InventoryDepth, m_Weight, and Print().
SetCalcDetails()
void SetCalcDetails (string details) inline private
Definition at line 720 of file Debug.c.
References m_CalcDetails.
Referenced by Weapon::GetWeightSpecialized(), InventoryItem::GetWeightSpecialized(), Ammunition_Base::GetWeightSpecialized(), and ManBase::GetWeightSpecialized().
SetWeight()
void SetWeight (float weight) inline private
Definition at line 715 of file Debug.c.
References m_Weight, and float::ToString().
Field Documentation
m_CalcDetails
string m_CalcDetails private
Definition at line 707 of file Debug.c.
Referenced by AddCalcDetails(), Output(), and SetCalcDetails().
m_Classname
string m_Classname private
Definition at line 704 of file Debug.c.
Referenced by Output(), and WeightDebugData().
m_InventoryDepth
int m_InventoryDepth private
Definition at line 706 of file Debug.c.
Referenced by Output(), and WeightDebugData().
m_Weight
string m_Weight private
Definition at line 705 of file Debug.c.
Referenced by Output(), and SetWeight().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/Debug.c