DayZ Scripts: P:/scripts/4_World/Entities/ScriptedEntities/Triggers/ContaminatedTrigger.c File Reference
ContaminatedTrigger.c File Reference
Data Structures
class EffectTrigger
class ContaminatedTrigger_Local
Functions
void ContaminatedTrigger_Dynamic ()
void SetAreaState (int state)
override protected void OnStayClientEvent (TriggerInsider insider, float deltaTime)
override void OnVariablesSynchronized ()
Variables
class ContaminatedTrigger extends EffectTrigger m_AreaState
Function Documentation
ContaminatedTrigger_Dynamic()
void ContaminatedTrigger_Dynamic ()
References TriggerEffectManager::GetInstance(), and m_Manager.
Referenced by ContaminatedArea_Dynamic::CreateTrigger(), and ContaminatedArea_Dynamic::SetDecayState().
OnStayClientEvent()
override protected void OnStayClientEvent (TriggerInsider insider, float deltaTime)
References TriggerInsider::GetObject(), m_AreaState, and m_PPERequester.
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
References m_AreaState, and m_PPERequester.
SetAreaState()
void SetAreaState (int state)
References m_AreaState.
Variable Documentation
m_AreaState
class ContaminatedTrigger extends EffectTrigger m_AreaState
Referenced by OnStayClientEvent(), OnVariablesSynchronized(), and SetAreaState().