DayZ Scripts: Bottle_Base Class Reference
Bottle_Base Class Reference
Private Member Functions
void CanisterGasoline ()
void ~CanisterGasoline ()
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override float GetLiquidThroughputCoef ()
override bool CanPutInCargo (EntityAI parent)
override bool IsOpen ()
void Canteen ()
void ~Canteen ()
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override bool CanPutInCargo (EntityAI parent)
override bool IsOpen ()
override void EEOnCECreate ()
void Cauldron ()
void ~Cauldron ()
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool IsOpen ()
override bool CanHaveWetness ()
override void SetActions ()
void Pot ()
void ~Pot ()
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool IsOpen ()
override bool CanHaveWetness ()
override void SetActions ()
void WaterBottle ()
void ~WaterBottle ()
override bool IsContainer ()
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override bool CanPutInCargo (EntityAI parent)
override bool IsOpen ()
override void EEOnCECreate ()
Constructor & Destructor Documentation
~CanisterGasoline()
void ~CanisterGasoline () inline private
~Canteen()
void ~Canteen () inline private
~Cauldron()
void ~Cauldron () inline private
~Pot()
void ~Pot () private
~WaterBottle()
void ~WaterBottle () inline private
Member Function Documentation
CanHaveWetness() [1/2]
override bool CanHaveWetness () inline private
CanHaveWetness() [2/2]
override bool CanHaveWetness () inline private
CanisterGasoline()
void CanisterGasoline () inline private
CanLoadItemIntoCargo() [1/2]
override bool CanLoadItemIntoCargo (EntityAI item) inline private
References IsCargoException4x3().
CanLoadItemIntoCargo() [2/2]
override bool CanLoadItemIntoCargo (EntityAI item) inline private
References IsCargoException4x3().
CanPutInCargo() [1/5]
override bool CanPutInCargo (EntityAI parent) inline private
CanPutInCargo() [2/5]
override bool CanPutInCargo (EntityAI parent) inline private
CanPutInCargo() [3/5]
override bool CanPutInCargo (EntityAI parent) inline private
References IsCargoException4x3().
CanPutInCargo() [4/5]
override bool CanPutInCargo (EntityAI parent) inline private
References IsCargoException4x3().
CanPutInCargo() [5/5]
override bool CanPutInCargo (EntityAI parent) inline private
CanReceiveItemIntoCargo() [1/2]
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
References IsCargoException4x3().
CanReceiveItemIntoCargo() [2/2]
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
References IsCargoException4x3().
Canteen()
void Canteen () inline private
Cauldron()
void Cauldron () inline private
EEOnCECreate() [1/2]
override void EEOnCECreate () inline private
References InsertAgent(), and Math::RandomInt().
EEOnCECreate() [2/2]
override void EEOnCECreate () inline private
References InsertAgent(), and Math::RandomInt().
GetEmptyingEndSoundsetHard() [1/5]
override string GetEmptyingEndSoundsetHard () inline private
Referenced by GetEmptyingEndSoundset().
GetEmptyingEndSoundsetHard() [2/5]
override string GetEmptyingEndSoundsetHard () inline private
GetEmptyingEndSoundsetHard() [3/5]
override string GetEmptyingEndSoundsetHard () inline private
GetEmptyingEndSoundsetHard() [4/5]
override string GetEmptyingEndSoundsetHard () inline private
GetEmptyingEndSoundsetHard() [5/5]
override string GetEmptyingEndSoundsetHard () inline private
GetEmptyingEndSoundsetSoft() [1/5]
override string GetEmptyingEndSoundsetSoft () inline private
Referenced by GetEmptyingEndSoundset().
GetEmptyingEndSoundsetSoft() [2/5]
override string GetEmptyingEndSoundsetSoft () inline private
GetEmptyingEndSoundsetSoft() [3/5]
override string GetEmptyingEndSoundsetSoft () inline private
GetEmptyingEndSoundsetSoft() [4/5]
override string GetEmptyingEndSoundsetSoft () inline private
GetEmptyingEndSoundsetSoft() [5/5]
override string GetEmptyingEndSoundsetSoft () inline private
GetEmptyingEndSoundsetWater() [1/5]
override string GetEmptyingEndSoundsetWater () inline private
Referenced by GetEmptyingEndSoundset().
GetEmptyingEndSoundsetWater() [2/5]
override string GetEmptyingEndSoundsetWater () inline private
GetEmptyingEndSoundsetWater() [3/5]
override string GetEmptyingEndSoundsetWater () inline private
GetEmptyingEndSoundsetWater() [4/5]
override string GetEmptyingEndSoundsetWater () inline private
GetEmptyingEndSoundsetWater() [5/5]
override string GetEmptyingEndSoundsetWater () inline private
GetEmptyingLoopSoundsetHard() [1/5]
override string GetEmptyingLoopSoundsetHard () inline private
Referenced by GetEmptyingLoopSoundset().
GetEmptyingLoopSoundsetHard() [2/5]
override string GetEmptyingLoopSoundsetHard () inline private
GetEmptyingLoopSoundsetHard() [3/5]
override string GetEmptyingLoopSoundsetHard () inline private
GetEmptyingLoopSoundsetHard() [4/5]
override string GetEmptyingLoopSoundsetHard () inline private
GetEmptyingLoopSoundsetHard() [5/5]
override string GetEmptyingLoopSoundsetHard () inline private
GetEmptyingLoopSoundsetSoft() [1/5]
override string GetEmptyingLoopSoundsetSoft () inline private
Referenced by GetEmptyingLoopSoundset().
GetEmptyingLoopSoundsetSoft() [2/5]
override string GetEmptyingLoopSoundsetSoft () inline private
GetEmptyingLoopSoundsetSoft() [3/5]
override string GetEmptyingLoopSoundsetSoft () inline private
GetEmptyingLoopSoundsetSoft() [4/5]
override string GetEmptyingLoopSoundsetSoft () inline private
GetEmptyingLoopSoundsetSoft() [5/5]
override string GetEmptyingLoopSoundsetSoft () inline private
GetEmptyingLoopSoundsetWater() [1/5]
override string GetEmptyingLoopSoundsetWater () inline private
Referenced by GetEmptyingLoopSoundset().
GetEmptyingLoopSoundsetWater() [2/5]
override string GetEmptyingLoopSoundsetWater () inline private
GetEmptyingLoopSoundsetWater() [3/5]
override string GetEmptyingLoopSoundsetWater () inline private
GetEmptyingLoopSoundsetWater() [4/5]
override string GetEmptyingLoopSoundsetWater () inline private
GetEmptyingLoopSoundsetWater() [5/5]
override string GetEmptyingLoopSoundsetWater () inline private
GetLiquidThroughputCoef()
override float GetLiquidThroughputCoef () inline private
References LIQUID_THROUGHPUT_GASOLINECANISTER.
Referenced by ActionEmptyBottleBaseCB::CreateActionComponent().
GetPouringSoundset() [1/5]
override string GetPouringSoundset () inline private
Referenced by PlayPouringLoopSound().
GetPouringSoundset() [2/5]
override string GetPouringSoundset () inline private
GetPouringSoundset() [3/5]
override string GetPouringSoundset () inline private
GetPouringSoundset() [4/5]
override string GetPouringSoundset () inline private
GetPouringSoundset() [5/5]
override string GetPouringSoundset () inline private
IsContainer() [1/5]
override bool IsContainer () inline private
IsContainer() [2/5]
override bool IsContainer () inline private
IsContainer() [3/5]
override bool IsContainer () inline private
IsContainer() [4/5]
override bool IsContainer () inline private
IsContainer() [5/5]
override bool IsContainer () inline private
IsOpen() [1/5]
override bool IsOpen () inline private
IsOpen() [2/5]
override bool IsOpen () inline private
IsOpen() [3/5]
override bool IsOpen () inline private
IsOpen() [4/5]
override bool IsOpen () inline private
IsOpen() [5/5]
override bool IsOpen () inline private
Pot()
void Pot () private
SetActions() [1/2]
override void SetActions () inline private
References AddAction(), and RemoveAction().
SetActions() [2/2]
override void SetActions () inline private
References AddAction(), and RemoveAction().
WaterBottle()
void WaterBottle () inline private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/CanisterGasoline.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/Canteen.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/Cauldron.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/Pot.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/WaterBottle.c