DayZ Scripts: TimerBase Class Reference
TimerBase Class Reference
Tools
Simple class for fading Widgets.
Private Member Functions
void WidgetFadeTimer ()
void FadeIn (Widget w, float time, bool continue_=false)
Make "fade in" effect on Widget (transparency goes from 0.0 to 1.0)
void FadeOut (Widget w, float time, bool continue_=false)
Make "fade out" effect on Widget (transparency goes from 1.0 to 0.0)
override private void OnTimer ()
override private void OnUpdate ()
void Timer (int category=CALL_CATEGORY_SYSTEM)
void Run (float duration, Managed obj, string fn_name, Param params=NULL, bool loop=false)
Starts timer.
override protected void OnTimer ()
override void Stop ()
Private Attributes
private Widget m_widget
bool m_fadeIn
float m_alpha
protected Managed m_target
protected string m_function
protected ref Param m_params
Detailed Description
Simple class for fading Widgets.
Timer class. Use when you want call function after some time, or repeatedly in time intervals. Call is not executed after the Timer object is deleted.
usage:
class MyObject
{
   ref Timer myTimer1;
   ref Timer myTimer2;
   ref Timer myTimer3;
   void MyObject()
   {
    myTimer1 = new Timer();
    myTimer1.Run(10, this, "Refresh"); // calls "Refresh" on "this" after 10 seconds
    myTimer2 = new Timer();
    myTimer2.Run(10, this, "Refresh", NULL, true); // calls "Refresh" on "this" every 10 seconds, until Pause or Stop is called
    myTimer3 = new Timer();
    myTimer3.Run(15, this, "Show", new Param1<bool>(false)); // calls "Show" on "this" with one bool argument after 15 seconds
   }
   void Refresh();
   void Show(bool visible);
}
Definition at line 418 of file tools.c.
Member Function Documentation
FadeIn()
void FadeIn (Widget w, float time, bool continue_ = false) inline private
Make "fade in" effect on Widget (transparency goes from 0.0 to 1.0)
Parameters
w widget which will be faded
time duration of effect
continue - if True continue from current alpha value, otherwise always begin from 0.0 alpha
Definition at line 436 of file tools.c.
References m_time, and OnStart().
FadeOut()
void FadeOut (Widget w, float time, bool continue_ = false) inline private
Make "fade out" effect on Widget (transparency goes from 1.0 to 0.0)
Parameters
w widget which will be faded
time duration of effect
continue - if True continue from current alpha value, otherwise always begin from 1.0 alpha
Definition at line 471 of file tools.c.
References m_alpha, m_time, and OnStart().
OnTimer() [1/2]
override private void OnTimer () inline private
Definition at line 500 of file tools.c.
Referenced by Tick().
OnTimer() [2/2]
override protected void OnTimer () inline private
Definition at line 593 of file tools.c.
References ScriptModule::CallFunction(), ScriptModule::CallFunctionParams(), CGame::GameScript, and GetGame().
OnUpdate()
override private void OnUpdate () inline private
Definition at line 516 of file tools.c.
References m_duration, m_time, and Math::Max().
Referenced by Tick().
Run()
void Run (float duration, Managed obj, string fn_name, Param params = NULL, bool loop = false) inline private
Starts timer.
Parameters
duration function is executed after this time (in seconds).
obj target object on which function will be executed
fn_name name of function (on object "obj") which will be executed
params function arguments see Param for usage, default NULL (no arguments)
loop when true, timer is looped endlessly and function is executed after every loop.
Definition at line 584 of file tools.c.
References OnStart().
Stop()
override void Stop () inline private
Definition at line 606 of file tools.c.
Timer()
void Timer (int category = CALL_CATEGORY_SYSTEM) inline private
Definition at line 571 of file tools.c.
References OnInit().
WidgetFadeTimer()
void WidgetFadeTimer () inline private
Definition at line 424 of file tools.c.
References CALL_CATEGORY_GUI, and OnInit().
Field Documentation
m_alpha
float m_alpha private
Definition at line 422 of file tools.c.
Referenced by FadeOut().
m_fadeIn
bool m_fadeIn private
Definition at line 421 of file tools.c.
m_function
protected string m_function private
Definition at line 568 of file tools.c.
m_params
protected ref Param m_params private
Definition at line 569 of file tools.c.
m_target
protected Managed m_target private
Definition at line 567 of file tools.c.
m_widget
private Widget m_widget private
Definition at line 420 of file tools.c.
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/tools.c