DayZ Scripts: FishYieldItemBase Class Reference
FishYieldItemBase Class Reference
Private Member Functions
override void Init ()
float GetCycleTimeForYieldItem (CatchingContextFishingRodAction ctx)
override float GetBaitTypeSensitivity (ECatchingBaitCategories type)
override string GetCatchDeathSoundset ()
override string GetCatchAINoise ()
override int GetCatchParticleID ()
Private Attributes
protected float m_HourlyCycleLengthCoefs [24]
Member Function Documentation
GetBaitTypeSensitivity()
override float GetBaitTypeSensitivity (ECatchingBaitCategories type) inline private
GetCatchAINoise()
override string GetCatchAINoise () inline private
GetCatchDeathSoundset()
override string GetCatchDeathSoundset () inline private
GetCatchParticleID()
override int GetCatchParticleID () inline private
References ParticleList::FISHING_SIGNAL_SPLASH.
GetCycleTimeForYieldItem()
float GetCycleTimeForYieldItem (CatchingContextFishingRodAction ctx) inline private
References UAFishingConstants::CYCLE_LENGTH_MAX, UAFishingConstants::CYCLE_LENGTH_MIN, Math::Floor(), GetGame(), Math::Lerp(), and m_HourlyCycleLengthCoefs.
Referenced by CarchingResultFishingAction::GetCurrentCycleTime().
Init()
override void Init () inline private
References m_HourlyCycleLengthCoefs, YieldItemBase::m_QualityBase, and AnimalCatchingConstants::QUALITY_FISH_BASE.
Field Documentation
m_HourlyCycleLengthCoefs
protected float m_HourlyCycleLengthCoefs[24] private
Referenced by GetCycleTimeForYieldItem(), Init(), YieldItemWalleyePollock::Init(), and YieldItemShrimp::Init().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Systems/AnimalCatchingSystem/YieldItems/YieldsFish.c