DayZ Scripts: CreditsElement Class Reference
CreditsElement Class Reference
Private Member Functions
void CreditsDepartmentElement (int index, Widget parent, JsonDataCreditsDepartment department_data)
void LoadDataAsync (array< ref JsonDataCreditsSection > department_data)
void CreditsGraphicalElement (int index, Widget parent)
Private Attributes
protected TextWidget m_DepartmentTitle
protected GridSpacerWidget m_DepartmentSections
protected ref array< ref CreditsDepartmentSection > m_DepartmentSectionEntries = new array<ref CreditsDepartmentSection>
Member Function Documentation
CreditsDepartmentElement()
void CreditsDepartmentElement (int index, Widget parent, JsonDataCreditsDepartment department_data) inline private
References WorkspaceWidget::CreateWidgets(), JsonDataCreditsDepartment::DepartmentName, GetGame(), CGame::GetWorkspace(), LoadDataAsync(), m_Root, and JsonDataCreditsDepartment::Sections.
CreditsGraphicalElement()
void CreditsGraphicalElement (int index, Widget parent) inline private
LoadDataAsync()
void LoadDataAsync (array< ref JsonDataCreditsSection > department_data) inline private
References CreditsDepartmentSection().
Referenced by CreditsDepartmentElement(), and CreditsDepartmentSection().
Field Documentation
m_DepartmentSectionEntries
protected ref array<ref CreditsDepartmentSection> m_DepartmentSectionEntries = new array<ref CreditsDepartmentSection> private
m_DepartmentSections
protected GridSpacerWidget m_DepartmentSections private
m_DepartmentTitle
protected TextWidget m_DepartmentTitle private
The documentation for this class was generated from the following files:
P:/scripts/5_Mission/GUI/NewUI/Credits/Elements/CreditsDepartmentElement.c
P:/scripts/5_Mission/GUI/NewUI/Credits/Elements/CreditsGraphicalElement.c