DayZ Scripts: ActionDeployBase Class Reference
ActionDeployBase Class Reference
Private Member Functions
void ActionDeployBase ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool HasProgress ()
override ActionData CreateActionData ()
override void OnFinishProgressServer (ActionData action_data)
void DropDuringPlacing (PlayerBase player)
void MoveEntityToFinalPosition (ActionData action_data, vector position, vector orientation)
void MoveEntityToFinalPositionSinglePlayer (ActionData action_data, InventoryLocation source, InventoryLocation destination)
Private Attributes
protected const float POSITION_OFFSET = 0.5
Constructor & Destructor Documentation
ActionDeployBase()
void ActionDeployBase () inline private
References AnimatedActionBase::m_CallbackClass, m_FullBody, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
CreateActionData()
override ActionData CreateActionData () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References m_ConditionItem, and m_ConditionTarget.
DropDuringPlacing()
void DropDuringPlacing (PlayerBase player) inline private
References Class::CastTo(), and ItemBase::IsBasebuildingKit().
HasProgress()
override bool HasProgress () inline private
HasTarget()
override bool HasTarget () inline private
MoveEntityToFinalPosition()
void MoveEntityToFinalPosition (ActionData action_data, vector position, vector orientation) inline private
References GetGame(), ItemBase::IsBasebuildingKit(), ActionData::m_MainItem, ActionData::m_Player, Math3D::MatrixToQuat(), MoveEntityToFinalPositionSinglePlayer(), InventoryLocation::SetGroundEx(), and Math3D::YawPitchRollMatrix().
Referenced by OnFinishProgressServer().
MoveEntityToFinalPositionSinglePlayer()
void MoveEntityToFinalPositionSinglePlayer (ActionData action_data, InventoryLocation source, InventoryLocation destination) inline private
References ActionData::m_Player.
Referenced by MoveEntityToFinalPosition().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References CGame::ClearJunctureEx(), GetGame(), PlaceObjectActionData::m_AlreadyPlaced, ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, MoveEntityToFinalPosition(), and POSITION_OFFSET.
Field Documentation
POSITION_OFFSET
protected const float POSITION_OFFSET = 0.5 private
Referenced by OnFinishProgressServer().
The documentation for this class was generated from the following file:
P:/scripts/4_world/classes/useractionscomponent/actions/continuous/deployactions/actiondeploybase.c