DayZ Scripts: P:/scripts/3_Game/Systems/AnimalCatching/CatchingContextBase.c File Reference
CatchingContextBase.c File Reference
Data Structures
class BaitData
Functions
void CatchingContextBase (Param par)
protected void Init (Param par)
protected void DeserializeData (Param par)
protected void InitBaitCompatibilityMap ()
protected void SetupInitialTypes ()
protected void ParseYieldItemsForCompatibility (array< ECatchingBaitCategories > excludedTypes=null)
protected void SetupProbabilityArray ()
YieldsMap GetYieldsMap ()
protected void CreateResultDataStructure ()
override if using another result
protected void InitCatchMasks ()
protected void InitCatchMethodMask ()
protected void InitCatchEnviroMask ()
protected int GetCatchMethodMask ()
override using 'ECatchMethodMask'
protected int GetCatchEnviroMask ()
protected bool CheckMaskCompatibility (YieldItemBase yItem)
protected bool CheckBaitCompatibility (YieldItemBase yItem, array< ECatchingBaitCategories > excludedTypes=null)
void UpdateCatchingItemData ()
protected void InitCatchingItemData ()
protected void InitItemValues (EntityAI item)
override to init context-specific values
protected void ClearCatchingItemData ()
called before actual item data initialization
protected void RecalculateProcessingData ()
Calculates and sets all data used in ongoing calculations.
bool IsValid ()
Checks if the ScriptCaller is valid.
void GenerateResult ()
void UpdateBaseProbability (YieldItemBase yItem)
updates base probability when catching the specific item (some context subclasses only)
bool ModifySignalProbability (inout float probability)
float GetQualityModifier ()
void SetResultChanceOverride (bool ovrd, float val=0.0)
void SetResultQualityOverride (bool ovrd, float val=0.0)
bool RollCatch ()
EntityAI SpawnAndSetupCatch (out int yItemIdx, vector v=vector.Zero)
Variables
class BaitData m_MainItem
protected YieldsMap m_YieldsMapAll
protected bool m_IsValid
protected int m_MethodMask
protected int m_EnviroMask
protected float m_QualityBaseMod
protected float m_QualityDispersionMinMod
protected float m_QualityDispersionMaxMod
protected ref map< int, ref BaitData > m_BaitCompatibilityMap
protected ref array< YieldItemBase > m_CompatibleItems
protected ref array< YieldItemBase > m_ExcludedItems
protected ref array< int > m_ProbabilityArray
protected ref CatchingResultBasic m_Result
Function Documentation
CatchingContextBase()
void CatchingContextBase (Param par)
References CatchingContextBase(), and Init().
Referenced by CatchingContextBase(), and InitCatchMethodMask().
CheckBaitCompatibility()
protected bool CheckBaitCompatibility (YieldItemBase yItem, array< ECatchingBaitCategories > excludedTypes = null)
References YieldItemBase::GetBaitTypeSensitivity(), IsCLIParam(), m_BaitCompatibilityMap, m_ExcludedItems, Math::Max(), and Print().
Referenced by ParseYieldItemsForCompatibility().
CheckMaskCompatibility()
protected bool CheckMaskCompatibility (YieldItemBase yItem)
References GetCatchEnviroMask(), GetCatchMethodMask(), YieldItemBase::GetEnviroMask(), and YieldItemBase::GetMethodMask().
Referenced by ParseYieldItemsForCompatibility().
ClearCatchingItemData()
protected void ClearCatchingItemData ()
called before actual item data initialization
References m_QualityBaseMod, m_QualityDispersionMaxMod, and m_QualityDispersionMinMod.
Referenced by InitCatchingItemData().
CreateResultDataStructure()
protected void CreateResultDataStructure ()
override if using another result
References ErrorEx, m_IsValid, m_MainItem, and m_Result.
Referenced by Init().
DeserializeData()
protected void DeserializeData (Param par)
References m_MethodMask, and AnimalCatchingConstants::MASK_METHOD_FISHTRAP_LARGE.
Referenced by Init().
GenerateResult()
void GenerateResult ()
References Class::CastTo(), m_IsValid, m_ProbabilityArray, m_Result, m_YieldsMapAll, CatchingResultBasic::SetYieldItem(), and UpdateBaseProbability().
Referenced by CatchingContextTrapsBase::Init().
GetCatchEnviroMask()
protected int GetCatchEnviroMask ()
References m_EnviroMask.
Referenced by CheckMaskCompatibility(), and CatchingContextTrapsBase::UpdateTrapEnviroMask().
GetCatchMethodMask()
protected int GetCatchMethodMask ()
override using 'ECatchMethodMask'
References m_MethodMask.
Referenced by CheckMaskCompatibility().
GetQualityModifier()
float GetQualityModifier ()
References m_QualityBaseMod, m_QualityDispersionMaxMod, m_QualityDispersionMinMod, and Math::RandomFloatInclusive().
GetYieldsMap()
YieldsMap GetYieldsMap ()
References m_YieldsMapAll.
Init()
protected void Init (Param par)
References CreateResultDataStructure(), DeserializeData(), WorldData::GetCatchYieldBank(), GetGame(), CGame::GetMission(), Mission::GetWorldData(), CatchYieldBank::GetYieldsMap(), InitCatchingItemData(), InitCatchMasks(), m_IsValid, m_YieldsMapAll, SetupInitialTypes(), and SetupProbabilityArray().
InitBaitCompatibilityMap()
protected void InitBaitCompatibilityMap ()
References m_BaitCompatibilityMap.
Referenced by InitCatchingItemData().
InitCatchEnviroMask()
protected void InitCatchEnviroMask ()
References m_EnviroMask.
Referenced by InitCatchMasks().
InitCatchingItemData()
protected void InitCatchingItemData ()
References ClearCatchingItemData(), ErrorEx, InitBaitCompatibilityMap(), InitItemValues(), m_IsValid, and m_MainItem.
Referenced by Init(), UpdateCatchingItemData(), and CatchingContextTrapsBase::UpdateDataAndMasks().
InitCatchMasks()
protected void InitCatchMasks ()
References InitCatchEnviroMask(), and InitCatchMethodMask().
Referenced by Init().
InitCatchMethodMask()
override protected void InitCatchMethodMask ()
References m_MethodMask.
Referenced by InitCatchMasks().
InitItemValues()
protected void InitItemValues (EntityAI item)
override to init context-specific values
Referenced by InitCatchingItemData().
IsValid()
bool IsValid ()
Checks if the ScriptCaller is valid.
References m_IsValid.
ModifySignalProbability()
bool ModifySignalProbability (inout float probability)
ParseYieldItemsForCompatibility()
protected void ParseYieldItemsForCompatibility (array< ECatchingBaitCategories > excludedTypes = null)
References CheckBaitCompatibility(), CheckMaskCompatibility(), m_CompatibleItems, m_ExcludedItems, and m_YieldsMapAll.
Referenced by SetupInitialTypes().
RecalculateProcessingData()
protected void RecalculateProcessingData ()
Calculates and sets all data used in ongoing calculations.
Referenced by UpdateCatchingItemData().
RollCatch()
bool RollCatch ()
References m_Result, CatchingResultBasic::RollChance(), and CatchingResultBasic::UpdateCatchChance().
SetResultChanceOverride()
void SetResultChanceOverride (bool ovrd, float val = 0.0)
References m_Result, and CatchingResultBasic::SetCatchChanceOverride().
SetResultQualityOverride()
void SetResultQualityOverride (bool ovrd, float val = 0.0)
References m_Result, and CatchingResultBasic::SetQualityOverride().
SetupInitialTypes()
protected void SetupInitialTypes ()
References ErrorEx, m_CompatibleItems, m_ExcludedItems, m_IsValid, m_MainItem, and ParseYieldItemsForCompatibility().
Referenced by Init().
SetupProbabilityArray()
protected void SetupProbabilityArray ()
References ErrorEx, YieldItemBase::GetType(), YieldItemBase::GetYieldWeight(), string::Hash(), m_CompatibleItems, m_IsValid, m_MainItem, and m_ProbabilityArray.
Referenced by Init(), and CatchingContextTrapsBase::UpdateDataAndMasks().
SpawnAndSetupCatch()
EntityAI SpawnAndSetupCatch (out int yItemIdx, vector v = vector.Zero)
References ErrorEx, m_IsValid, m_MainItem, m_Result, CatchingResultBasic::SpawnAndSetup(), and CatchingResultBasic::UpdateCatchQuality().
UpdateBaseProbability()
void UpdateBaseProbability (YieldItemBase yItem)
updates base probability when catching the specific item (some context subclasses only)
Referenced by GenerateResult().
UpdateCatchingItemData()
void UpdateCatchingItemData ()
References InitCatchingItemData(), and RecalculateProcessingData().
Referenced by CatchingContextFishingRodAction::OnAfterSpawnSignalHit(), CatchingContextFishingRodAction::OnSignalMiss(), and CatchingContextFishingRodAction::OnSignalPass().
Variable Documentation
m_BaitCompatibilityMap
protected ref map<int,ref BaitData> m_BaitCompatibilityMap
Referenced by CheckBaitCompatibility(), InitBaitCompatibilityMap(), CatchingContextTrapsBase::InitItemValues(), CatchingContextTrapsBase::UpdateBaseProbability(), and CatchingContextTrapsBase::UpdateUsedBait().
m_CompatibleItems
protected ref array<YieldItemBase> m_CompatibleItems
Referenced by ParseYieldItemsForCompatibility(), SetupInitialTypes(), and SetupProbabilityArray().
m_EnviroMask
protected int m_EnviroMask
Referenced by GetCatchEnviroMask(), InitCatchEnviroMask(), CatchingContextFishingRodAction::InitCatchEnviroMask(), CatchingContextTrapsBase::InitCatchEnviroMask(), and CatchingContextTrapsBase::SetTrapEnviroMask().
m_ExcludedItems
protected ref array<YieldItemBase> m_ExcludedItems
Referenced by CheckBaitCompatibility(), ParseYieldItemsForCompatibility(), and SetupInitialTypes().
m_IsValid
protected bool m_IsValid
Referenced by CreateResultDataStructure(), GenerateResult(), Init(), InitCatchingItemData(), IsValid(), SetupInitialTypes(), SetupProbabilityArray(), and SpawnAndSetupCatch().
m_MainItem
ItemBase m_MainItem
Referenced by _GetSelectedActions(), AnimateRod(), CreateResultDataStructure(), CatchingContextFishingRodAction::CreateResultDataStructure(), CatchingContextTrapsBase::CreateResultDataStructure(), CatchingContextFishingBase::DeserializeData(), CatchingContextTrapsBase::DeserializeData(), CatchingContextFishingRodAction::Init(), CatchingContextTrapsBase::InitCatchEnviroMask(), InitCatchingItemData(), SetupInitialTypes(), SetupProbabilityArray(), SpawnAndSetupCatch(), UpdatePossibleActions(), CarHornShortActionInput::UpdatePossibleActions(), ToggleLightsActionInput::UpdatePossibleActions(), ToggleNVGActionInput::UpdatePossibleActions(), and CatchingContextTrapsBase::UpdateUsedBait().
m_MethodMask
protected int m_MethodMask
Referenced by DeserializeData(), GetCatchMethodMask(), InitCatchMethodMask(), and CatchingContextFishingRodAction::InitCatchMethodMask().
m_ProbabilityArray
protected ref array<int> m_ProbabilityArray
Referenced by GenerateResult(), CatchingContextFishingRodAction::GenerateResult(), and SetupProbabilityArray().
m_QualityBaseMod
protected float m_QualityBaseMod
Referenced by ClearCatchingItemData(), CatchingContextTrapsBase::ClearCatchingItemData(), GetQualityModifier(), CatchingContextFishingRodAction::InitItemValues(), and CatchingContextTrapsBase::InitItemValues().
m_QualityDispersionMaxMod
protected float m_QualityDispersionMaxMod
Referenced by ClearCatchingItemData(), CatchingContextTrapsBase::ClearCatchingItemData(), GetQualityModifier(), CatchingContextFishingRodAction::InitItemValues(), and CatchingContextTrapsBase::InitItemValues().
m_QualityDispersionMinMod
protected float m_QualityDispersionMinMod
Referenced by ClearCatchingItemData(), CatchingContextTrapsBase::ClearCatchingItemData(), GetQualityModifier(), CatchingContextFishingRodAction::InitItemValues(), and CatchingContextTrapsBase::InitItemValues().
m_Result
protected ref CatchingResultBasic m_Result
Referenced by CreateResultDataStructure(), CatchingContextFishingRodAction::CreateResultDataStructure(), CatchingContextTrapsBase::CreateResultDataStructure(), GenerateResult(), CatchingContextFishingRodAction::GenerateResult(), CatchingContextFishingRodAction::GetActionCycleTime(), CatchingContextFishingRodAction::GetResultParticleId(), CatchingContextFishingRodAction::RecalculateProcessingData(), RollCatch(), array::Run(), SetResultChanceOverride(), SetResultQualityOverride(), SpawnAndSetupCatch(), and array::TFCaller().
m_YieldsMapAll
protected YieldsMap m_YieldsMapAll
Referenced by GenerateResult(), CatchingContextFishingRodAction::GenerateResult(), GetYieldsMap(), Init(), and ParseYieldItemsForCompatibility().