DayZ Scripts: P:/scripts/3_Game/Sound.c File Reference
Sound.c File Reference
Data Structures
class SoundObjectBuilder
class SoundParams
class AbstractWave
Enumerations
enum WaveKind
Functions
enum WaveKind AbstractSoundScene ()
private void ~AbstractSoundScene ()
proto native AbstractWave Play2D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
proto native AbstractWave Play3D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
proto native SoundObject BuildSoundObject (SoundObjectBuilder soundObjectbuilder)
proto native float GetRadioVolume ()
proto native void SetRadioVolume (float vol, float time)
proto native float GetSpeechExVolume ()
proto native void SetSpeechExVolume (float vol, float time)
proto native float GetMusicVolume ()
proto native void SetMusicVolume (float vol, float time)
proto native float GetSoundVolume ()
proto native void SetSoundVolume (float vol, float time)
proto native float GetVOIPVolume ()
proto native void SetVOIPVolume (float vol, float time)
proto native float GetSilenceThreshold ()
proto native float GetAudioLevel ()
class SoundObjectBuilder SoundObject (SoundParams soundParams)
void SoundObjectBuilder (SoundParams soundParams)
SoundObject BuildSoundObject ()
proto native void Initialize (SoundParams soundParams)
proto native void AddEnvSoundVariables (vector position)
proto native void AddVariable (string name, float value)
proto void AddVariables (notnull array< string > names, array< float > values=null)
void UpdateEnvSoundControllers (vector position)
Deprecated - same functionality, just poor naming.
void SetVariable (string name, float value)
Deprecated - same functionality, just poor naming.
proto void UpdateVariables (notnull array< float > values)
proto native void SetParent (IEntity parent, int pivot=-1)
proto native IEntity GetParent ()
Get parent of the Effect.
proto native int GetHierarchyPivot ()
proto native void SetPosition (vector position)
Note: Sets the position locally if parented, retrieves globally with the sound offset.
proto native vector GetPosition ()
Get the world position of the Effect.
proto native void SetSpeed (vector speed)
Note: Sets the speed locally if parented, retrieves globally with the parent speed.
proto native vector GetSpeed ()
proto native void SetOcclusionObstruction (float occlusion, float obstruction)
proto native void SetKind (WaveKind kind)
Variables
WAVEEFFECT
WAVEEFFECTEX
WAVESPEECH
WAVEMUSIC
WAVESPEECHEX
WAVEENVIRONMENT
WAVEENVIRONMENTEX
WAVEWEAPONS
WAVEWEAPONSEX
WAVEATTALWAYS
WAVEUI
class SoundParams Event_OnSoundWaveStarted = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveStopped = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveLoaded = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveHeaderLoaded = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveEnded = new ScriptInvoker()
Enumeration Type Documentation
WaveKind
enum WaveKind
Function Documentation
AbstractSoundScene()
enum WaveKind AbstractSoundScene ()
AddEnvSoundVariables()
proto native void AddEnvSoundVariables (vector position)
AddVariable()
proto native void AddVariable (string name, float value)
AddVariables()
proto void AddVariables (notnull array< string > names, array< float > values = null)
BuildSoundObject() [1/2]
SoundObject BuildSoundObject ()
References WAVEEFFECT, WAVEEFFECTEX, WAVEMUSIC, and WAVESPEECH.
BuildSoundObject() [2/2]
proto native SoundObject BuildSoundObject (SoundObjectBuilder soundObjectbuilder)
GetAudioLevel()
proto native float GetAudioLevel ()
Referenced by ScriptedWidgetEventHandler::UpdateAudioLevel().
GetHierarchyPivot()
proto native int GetHierarchyPivot ()
GetMusicVolume()
proto native float GetMusicVolume ()
GetPosition()
proto native vector GetPosition ()
Get the world position of the Effect.
Warning
Only gets the cached variable, for immediate effect use GetCurrent variant
Returns
vector The world position of the Effect
References m_AreaPosition, and m_Position.
Referenced by FireplaceBase::AfterStoreLoad(), ManBase::AfterStoreLoad(), UIScriptedMenu::CameraToolsMenu(), DayZInfected::ChaseAttackLogic(), CheckAllowUpdate(), DayZInfected::ComputeHitDirectionAngle(), DayZCreatureAI::ComputeHitDirectionAngleDeg(), DayZInfected::ComputeHitDirectionAngleEx(), CreateLight(), Grenade_Base::CreateLight(), ItemBase::CreateRope(), CreateTrigger(), Entity::DeathUpdate(), DayZAnimal::DeathUpdate(), KitBase::DisassembleKit(), ItemBase::DoMeasurement(), ScriptConsoleItemsTab::DrawItems(), ManBase::DropItem(), ContaminatedArea_Dynamic::EEInit(), House::EEInit(), GeyserTrigger::EEInit(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), FlammableBase::EEItemDetached(), Ammo_40mm_Explosive::EEKilled(), ContaminatedArea_Dynamic::EEOnCECreate(), Inventory_Base::EmptySeedPack(), InventoryItem::EOnContact(), DynamicArea_Flare::EOnFrame(), DayZSpectator::EOnFrame(), FireplaceBase::EOnTouch(), EOnTouch(), DayZInfected::EvaluateCrawlTransitionAnimation(), DayZPlayer::EvaluateDamageHitAnimation(), DayZPlayer::EvaluateDeathAnimation(), Hit_MeatBones::Event_OnStarted(), IEntity::Explode(), Explode(), CGame::ExplosionEffects(), ExplosivesBase(), DayZInfected::FightAttackLogic(), DayZInfected::FightLogic(), GenerateCarHornAINoise(), DayZInfected::GetAttackPitch(), WorldData::GetBaseEnvTemperatureAtObject(), GetCeilingHeight(), IEntity::GetCenter(), Land_WarheadStorage_PowerStation::GetClosestBunker(), GetClosestCarWheel(), GetClosestDoor(), EffectSound::GetCurrentLocalPosition(), EffectSound::GetCurrentPosition(), GetEmptyingEndSoundset(), GetEmptyingLoopSoundset(), ItemBase::GetKitSpawnPosition(), BaseBuildingBase::GetKitSpawnPosition(), IEntity::GetSurfaceNoise(), Entity::GetUniversalTemperatureSourcePosition(), BoatScript::HandleBoatSplashSound(), EntityLightSource::HandleDancingShadows(), HandleDoorsSound(), BaseBuildingBase::HandleRefreshers(), HandleSeatAdjustmentSound(), DayZPlayer::HandleView(), Heating(), BaseBuildingBase::InsertRefresherPosition(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), ManBase::IsFacingTarget(), BaseBuildingBase::IsPlayerInside(), TentBase::IsPlayerInside(), ItemBase::IsPlayerInVicinity(), RemoteDetonatorTrigger::OnActivatedByItem(), CarScript::OnAnimationPhaseStarted(), OnCEUpdate(), RemoteDetonatorTrigger::OnCEUpdate(), BaseBuildingBase::OnCEUpdate(), ManBase::OnConnect(), Grenade_ChemGas::OnDamageDestroyed(), ClaymoreMine::OnDebugSpawn(), RifleSingleShot_Base::OnDebugSpawn(), KitBase::OnDebugSpawn(), OnDebugSpawn(), FishingRod_Base_New::OnDebugSpawn(), Crossbow_Base::OnDebugSpawnEx(), FireworksLauncher::OnEventServer(), Anniversary_FireworksLauncher::OnEventServer(), Grenade_ChemGas::OnExplode(), IEntity::OnExplodeClient(), Weapon::OnFireModeChange(), FireworksLauncher::OnFuseIgnitedClient(), PluginBase::OnGUITimer(), FireplaceBase::OnIgnitedThis(), GardenBase::OnPlacementComplete(), KitBase::OnPlacementComplete(), InventoryItem::OnRPC(), CGame::OnRPC(), DayZPlayer::OnStepEvent(), OnSteppedOn(), GardenBase::OnStoreLoad(), ItemBase::OnStoreLoad(), AlarmClock_ColorBase::OnUpdate(), KitchenTimer::OnUpdate(), BotStateBase::OnUpdate(), AnniversarySpotLight::OnVariablesSynchronized(), InventoryItemSuper::OnWasAttached(), InventoryItemSuper::OnWasDetached(), OnWork(), OnWorkStart(), ItemBase::ParticleTest(), BaseBuildingBase::PerformRoofCheckForBase(), ItemBase::PlaceOnGround(), InventoryItem::PlayAttachSound(), InventoryItem::PlayDeployFinishSound(), InventoryItem::PlayDeployLoopSoundEx(), InventoryItem::PlayDeploySound(), PlayDisarmingLoopSound(), EntityAI::PlayImpactSound(), InventoryItem::PlayPlaceSound(), PlayRepackingLoopSound(), Backpack_Base::PlayRepackingLoopSound(), DayZCreature::PlaySound(), EntityAI::PlaySound(), DayZPlayer::PlaySound(), BoatScript::PlaySound(), PlaySoundActivate(), TrapBase::PlaySoundBiteEmpty(), TrapBase::PlaySoundBiteLeg(), PlaySoundEx(), TrapBase::PlaySoundOpen(), PlayVFX(), Environment::ProcessItemsDryness(), DayZCreature::ProcessSoundEvent(), DayZPlayer::ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), RefreshFireplaceVisuals(), ItemBase::RemovePlant(), BaseBuildingBase::RemoveRefresherPosition(), House::RequestSoundEvent(), ManBase::SaySoundSet(), ManBase::SetContaminatedEffectEx(), SetParticlePosition(), BaseBuildingBase::SetRefresherActive(), Barrel_ColorBase::SoundBarrelClosePlay(), FireplaceBase::SoundBarrelClosePlay(), Barrel_ColorBase::SoundBarrelOpenPlay(), FireplaceBase::SoundBarrelOpenPlay(), Edible_Base::SoundCookingStart(), Entity::SoundHardBushFallingPlay(), Entity::SoundHardTreeFallingPlay(), EffectSound::SoundLoadEx(), EffectSound::SoundPlayEx(), Entity::SoundSoftBushFallingPlay(), Entity::SoundSoftTreeFallingPlay(), ItemBase::SoundTentClosePlay(), ItemBase::SoundTentCloseWindowPlay(), ItemBase::SoundTentOpenPlay(), ItemBase::SoundTentOpenWindowPlay(), ManBase::SpawnEntityOnGroundOnCursorDir(), TentBase::SpawnKit(), PluginBase::SpawnNewInfectedEntity(), CrashBase::SpawnRandomDeers(), UndergroundTriggerCarrierBase::SpawnTrigger(), HotSpringTrigger::SpawnVaporEffect(), VolcanicTrigger::SpawnVaporEffect(), FlammableBase::StandUp(), EffectParticle::Start(), StartActivate(), Particle::StopParticle(), TestOwnership(), EntityLightSource::TryShadowOptimization(), FlammableBase::TryTransformIntoStick(), AreaDamageTriggerBase::UpdateInsiders(), UpdateMusic(), ManBase::UpdatePlayerMeasures(), ScriptedWidgetEventHandler::UpdatePos(), and ItemBase::UpdatePreyPos().
GetRadioVolume()
proto native float GetRadioVolume ()
GetSilenceThreshold()
proto native float GetSilenceThreshold ()
GetSoundVolume()
proto native float GetSoundVolume ()
GetSpeechExVolume()
proto native float GetSpeechExVolume ()
GetSpeed()
proto native vector GetSpeed ()
GetVOIPVolume()
proto native float GetVOIPVolume ()
Initialize()
proto native void Initialize (SoundParams soundParams)
Play2D()
proto native AbstractWave Play2D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
Play3D()
proto native AbstractWave Play3D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
SetKind()
proto native void SetKind (WaveKind kind)
SetMusicVolume()
proto native void SetMusicVolume (float vol, float time)
SetOcclusionObstruction()
proto native void SetOcclusionObstruction (float occlusion, float obstruction)
SetParent()
proto native void SetParent (IEntity parent, int pivot = -1)
Note: 'SoundObject' is not an Entity, and therefore can not be accessed by using 'IEntity.GetChildren', though internally 'SoundObject.SetParent' is similiar to 'IEntity.AddChild' by creating an 'EntityHierarchyComponent'
SetRadioVolume()
proto native void SetRadioVolume (float vol, float time)
SetSoundVolume()
proto native void SetSoundVolume (float vol, float time)
SetSpeechExVolume()
proto native void SetSpeechExVolume (float vol, float time)
SetSpeed()
proto native void SetSpeed (vector speed)
Note: Sets the speed locally if parented, retrieves globally with the parent speed.
SetVariable()
void SetVariable (string name, float value)
Deprecated - same functionality, just poor naming.
SetVOIPVolume()
proto native void SetVOIPVolume (float vol, float time)
SoundObject()
class SoundObjectBuilder SoundObject (SoundParams soundParams)
Referenced by DayZPlayer::HandleView(), DayZPlayer::OnStepEvent(), EntityAI::PlayImpactSound(), MissionBase::PlayMusic(), EntityAI::PlaySoundByAnimEvent(), PlayTrack(), DayZPlayer::ProcessAttachmentEvent(), DayZCreature::ProcessSoundEvent(), DayZPlayer::ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), DayZPlayer::ProcessVoiceEvent(), DayZInfected::ProcessVoiceFX(), and DayZPlayer::ProcessWeaponEvent().
SoundObjectBuilder()
void SoundObjectBuilder (SoundParams soundParams)
UpdateEnvSoundControllers()
void UpdateEnvSoundControllers (vector position)
Deprecated - same functionality, just poor naming.
UpdateVariables()
proto void UpdateVariables (notnull array< float > values)
~AbstractSoundScene()
private void ~AbstractSoundScene ()
Variable Documentation
Event_OnSoundWaveEnded
ref ScriptInvoker Event_OnSoundWaveEnded = new ScriptInvoker()
Event_OnSoundWaveHeaderLoaded
ref ScriptInvoker Event_OnSoundWaveHeaderLoaded = new ScriptInvoker()
Event_OnSoundWaveLoaded
ref ScriptInvoker Event_OnSoundWaveLoaded = new ScriptInvoker()
Event_OnSoundWaveStarted
class SoundParams Event_OnSoundWaveStarted = new ScriptInvoker()
Event_OnSoundWaveStopped
ref ScriptInvoker Event_OnSoundWaveStopped = new ScriptInvoker()
WAVEATTALWAYS
WAVEATTALWAYS
WAVEEFFECT
WAVEEFFECT
Referenced by BuildSoundObject().
WAVEEFFECTEX
WAVEEFFECTEX
Referenced by BuildSoundObject().
WAVEENVIRONMENT
WAVEENVIRONMENT
WAVEENVIRONMENTEX
WAVEENVIRONMENTEX
WAVEMUSIC
WAVEMUSIC
Referenced by BuildSoundObject().
WAVESPEECH
WAVESPEECH
Referenced by BuildSoundObject().
WAVESPEECHEX
WAVESPEECHEX
WAVEUI
WAVEUI
WAVEWEAPONS
WAVEWEAPONS
WAVEWEAPONSEX
WAVEWEAPONSEX