DayZ Scripts: JsonUndergroundAreaTriggerData Class Reference
JsonUndergroundAreaTriggerData Class Reference
Private Member Functions
vector GetPosition ()
vector GetOrientation ()
vector GetSize ()
Private Attributes
ref array< float > Position
ref array< float > Orientation
ref array< float > Size
float EyeAccommodation
float InterpolationSpeed
ref array< ref JsonUndergroundAreaBreadcrumb > Breadcrumbs
Member Function Documentation
GetOrientation()
vector GetOrientation () inline private
References Orientation, and Vector().
Referenced by UndergroundAreaLoader::SpawnTriggerCarrier().
GetPosition()
vector GetPosition () inline private
References Position, and Vector().
Referenced by UndergroundAreaLoader::SpawnTriggerCarrier().
GetSize()
vector GetSize () inline private
References Size, and Vector().
Referenced by Init().
Field Documentation
Breadcrumbs
ref array<ref JsonUndergroundAreaBreadcrumb> Breadcrumbs private
Referenced by Init().
EyeAccommodation
float EyeAccommodation private
Referenced by Init().
InterpolationSpeed
float InterpolationSpeed private
Referenced by Init().
Orientation
ref array<float> Orientation private
Referenced by GetOrientation().
Position
ref array<float> Position private
Referenced by GetPosition().
Size
ref array<float> Size private
Referenced by GetSize().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/UndergroundAreaLoader.c