DayZ Scripts: P:/scripts/4_World/Entities/ItemBase/SeedPackBase.c File Reference
SeedPackBase.c File Reference
Data Structures
class Inventory_Base
Functions
void EmptySeedsPackLambda (EntityAI old_item, string new_item_type, PlayerBase player, int count)
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
override void OnSuccess (EntityAI new_item)
Variables
class SeedPackBase extends Inventory_Base m_ItemCount
Function Documentation
CopyOldPropertiesToNew()
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
References Class::CastTo(), and m_ItemCount.
EmptySeedsPackLambda()
void EmptySeedsPackLambda (EntityAI old_item, string new_item_type, PlayerBase player, int count)
References m_ItemCount.
Referenced by Inventory_Base::EmptySeedPack().
OnSuccess()
override void OnSuccess (EntityAI new_item)
References ECE_PLACE_ON_SURFACE, and GetGame().
Variable Documentation
m_ItemCount
class SeedPackBase extends Inventory_Base m_ItemCount
Referenced by CopyOldPropertiesToNew(), and EmptySeedsPackLambda().