DayZ Scripts: P:/scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCfgSounds.c File Reference
DayZPlayerCfgSounds.c File Reference
Data Structures
class DayZPlayerTypeStepSoundLookupTable
class DayZPlayerTypeVoiceSoundLookupTable
Functions
class DayZPlayerTypeStepSoundLookupTableImpl extends DayZPlayerTypeStepSoundLookupTable DayZPlayerTypeAttachmentSoundLookupTableImpl ()
void DayZPlayerTypeStepSoundLookupTableImpl ()
override SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
static DayZPlayerTypeStepSoundLookupTableImpl GetInstance ()
override SoundObjectBuilder GetSoundBuilder (int eventId, string slotName, int attachmentHash)
class DayZPlayerTypeVoiceSoundLookupTableImpl extends DayZPlayerTypeVoiceSoundLookupTable DayZPlayerTypeSoundTableImpl ()
void DayZPlayerTypeVoiceSoundLookupTableImpl ()
override SoundObjectBuilder GetSoundBuilder (int eventId, int parameterHash)
override NoiseParams GetNoiseParams (int eventId)
override AnimSoundEvent GetSoundEvent (int event_id)
void DayZPlayerTypeRegisterSounds (DayZPlayerType pType)
Variables
static private ref DayZPlayerTypeStepSoundLookupTableImpl m_instance
private autoptr map< int, ref StepSoundLookupTable > m_pSoundTableInstances
private autoptr map< int, StepSoundLookupTable > m_pSoundTables
private ref array< ref AnimSoundEvent > m_animSoundEvents
Function Documentation
DayZPlayerTypeAttachmentSoundLookupTableImpl()
class DayZPlayerTypeStepSoundLookupTableImpl extends DayZPlayerTypeStepSoundLookupTable DayZPlayerTypeAttachmentSoundLookupTableImpl ()
Referenced by DayZPlayerTypeRegisterSounds().
DayZPlayerTypeRegisterSounds()
void DayZPlayerTypeRegisterSounds (DayZPlayerType pType)
register events
load and register step sound lookup table
References DayZPlayerTypeAttachmentSoundLookupTableImpl(), DayZPlayerTypeSoundTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTableImpl(), GetGame(), DayZPlayerTypeStepSoundLookupTable::GetInstance(), DayZPlayerTypeVoiceSoundLookupTable::GetInstance(), CGame::ProfilerStart(), and CGame::ProfilerStop().
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeCreate().
DayZPlayerTypeSoundTableImpl()
class DayZPlayerTypeVoiceSoundLookupTableImpl extends DayZPlayerTypeVoiceSoundLookupTable DayZPlayerTypeSoundTableImpl ()
Referenced by DayZPlayerTypeRegisterSounds().
DayZPlayerTypeStepSoundLookupTableImpl()
void DayZPlayerTypeStepSoundLookupTableImpl ()
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), CGame::ConfigGetText(), GetGame(), string::Hash(), m_pSoundTableInstances, m_pSoundTables, and slotName.
Referenced by DayZPlayerTypeRegisterSounds().
DayZPlayerTypeVoiceSoundLookupTableImpl()
void DayZPlayerTypeVoiceSoundLookupTableImpl ()
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), and m_animSoundEvents.
Referenced by DayZPlayerTypeRegisterSounds().
GetInstance()
static DayZPlayerTypeSoundTableImpl GetInstance () static
References GetGame(), string::Hash(), m_pSoundTableInstances, and PlayerVoiceLookupTable().
GetNoiseParams()
override NoiseParams GetNoiseParams (int eventId)
GetSoundBuilder() [1/3]
override SoundObjectBuilder GetSoundBuilder (int eventId, int parameterHash)
GetSoundBuilder() [2/3]
override SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
GetSoundBuilder() [3/3]
override SoundObjectBuilder GetSoundBuilder (int eventId, string slotName, int attachmentHash)
References SoundLookupTable::GetSoundBuilder(), m_pSoundTables, and slotName.
GetSoundEvent()
override AnimSoundEvent GetSoundEvent (int event_id)
References m_animSoundEvents.
Variable Documentation
m_animSoundEvents
private ref array<ref AnimSoundEvent> m_animSoundEvents
Referenced by DayZPlayerTypeVoiceSoundLookupTableImpl(), and GetSoundEvent().
m_instance
static private ref DayZPlayerTypeSoundTableImpl m_instance static
m_pSoundTableInstances
private autoptr map< int, ref PlayerVoiceLookupTable > m_pSoundTableInstances
Referenced by DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), and GetInstance().
m_pSoundTables
private autoptr map< int, PlayerVoiceLookupTable > m_pSoundTables
Referenced by DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::GetNoiseParams(), DayZPlayerTypeVoiceSoundLookupTable::GetSoundBuilder(), DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder(), and GetSoundBuilder().