DayZ Scripts: PPEColors Class Reference
PPEColors Class Reference
Colors - PostProcessEffectType.Colors.
Private Member Functions
override int GetPostProcessEffectID ()
override string GetDefaultMaterialPath ()
override void RegisterMaterialParameters ()
Static Private Attributes
static const int PARAM_BRIGHTNESS = 0
static const int PARAM_CONTRAST = 1
static const int PARAM_OFFSET = 2
static const int PARAM_OVERLAYFACTOR = 3
static const int PARAM_OVERLAYCOLOR = 4
static const int PARAM_SATURATION = 5
static const int PARAM_COLORIZATIONCOLOR = 6
static const int PARAM_DESATURATIONWEIGHTS = 7
Detailed Description
Colors - PostProcessEffectType.Colors.
Member Function Documentation
GetDefaultMaterialPath()
override string GetDefaultMaterialPath () inline private
GetPostProcessEffectID()
override int GetPostProcessEffectID () inline private
RegisterMaterialParameters()
override void RegisterMaterialParameters () inline private
References PARAM_BRIGHTNESS, PARAM_COLORIZATIONCOLOR, PARAM_CONTRAST, PARAM_DESATURATIONWEIGHTS, PARAM_OFFSET, PARAM_OVERLAYCOLOR, PARAM_OVERLAYFACTOR, PARAM_SATURATION, PPEMatClassParameterFloatSaturation(), PPEClassBase::RegisterParameterColor(), PPEClassBase::RegisterParameterColorEx(), PPEClassBase::RegisterParameterScalarFloat(), PPEClassBase::RegisterParameterScalarFloatEx(), and PPEClassBase::RegisterParameterVector().
Field Documentation
PARAM_BRIGHTNESS
const int PARAM_BRIGHTNESS = 0 static private
Referenced by RegisterMaterialParameters().
PARAM_COLORIZATIONCOLOR
const int PARAM_COLORIZATIONCOLOR = 6 static private
Referenced by RegisterMaterialParameters().
PARAM_CONTRAST
const int PARAM_CONTRAST = 1 static private
Referenced by RegisterMaterialParameters().
PARAM_DESATURATIONWEIGHTS
const int PARAM_DESATURATIONWEIGHTS = 7 static private
Referenced by RegisterMaterialParameters().
PARAM_OFFSET
const int PARAM_OFFSET = 2 static private
Referenced by RegisterMaterialParameters().
PARAM_OVERLAYCOLOR
const int PARAM_OVERLAYCOLOR = 4 static private
Referenced by RegisterMaterialParameters().
PARAM_OVERLAYFACTOR
const int PARAM_OVERLAYFACTOR = 3 static private
Referenced by RegisterMaterialParameters().
PARAM_SATURATION
const int PARAM_SATURATION = 5 static private
Referenced by RegisterMaterialParameters().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/PPEManager/Materials/MatClasses/PPEColors.c