DayZ Scripts: ActionHandcuffTarget Class Reference
ActionHandcuffTarget Class Reference
Private Member Functions
void ActionHandcuffTarget ()
override void CreateConditionComponents ()
override void OnExecuteServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
Constructor & Destructor Documentation
ActionHandcuffTarget()
void ActionHandcuffTarget () inline private
References AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
CreateConditionComponents()
override void CreateConditionComponents () inline private
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
References CGame::GetAnalyticsClient(), GetGame(), and AnalyticsManagerClient::OnActionRestrain().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
References ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionHandcuffTarget.c