DayZ Scripts: ScriptConsoleEnfScriptTab Class Reference
ScriptConsoleEnfScriptTab Class Reference
Private Member Functions
void ScriptConsoleEnfScriptTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void ~ScriptConsoleEnfScriptTab ()
override void OnSelected ()
void Add (string message, bool isReload=false)
protected void Clear (bool clearFile=false)
protected void ReloadScriptOutput ()
void HistoryBack ()
void HistoryForward ()
protected void RunEnscript ()
protected void ColorRunButton (bool success)
protected void ResetRunButtonColor ()
protected void RunEnscriptServer ()
protected void EnscriptHistoryBack ()
protected void EnscriptHistoryForward ()
override void OnRPCEx (int rpc_type, ParamsReadContext ctx)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
override void Show (bool show, ScriptConsoleTabBase selectedHandler)
Static Private Member Functions
static void PrintS (string message)
static void PrintS (bool message)
static void PrintS (int message)
static void PrintS (float message)
static void PrintS (vector message)
static void PrintS (Object message)
Private Attributes
protected int m_EnscriptHistoryRow
protected int m_EnscriptHistoryRowServer
protected ref TStringArray m_EnscriptConsoleHistory
protected ref TStringArray m_EnscriptConsoleHistoryServer
protected PluginLocalEnscriptHistory m_ModuleLocalEnscriptHistory
protected PluginLocalEnscriptHistoryServer m_ModuleLocalEnscriptHistoryServer
protected MultilineEditBoxWidget m_EnfScriptEdit
protected ButtonWidget m_EnfScriptRun
protected ButtonWidget m_EnfScriptClear
protected TextListboxWidget m_ScriptOutputListbox
protected bool m_AllowScriptOutput
protected int m_RunColor
Static Private Attributes
static protected ScriptConsoleEnfScriptTab m_Instance
static ref TStringArray m_ScriptOutputHistory = new TStringArray()
Constructor & Destructor Documentation
ScriptConsoleEnfScriptTab()
void ScriptConsoleEnfScriptTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline private
References GetPlugin(), m_EnfScriptClear, m_EnfScriptEdit, m_EnfScriptRun, m_EnscriptConsoleHistory, m_EnscriptConsoleHistoryServer, m_Instance, m_ModuleLocalEnscriptHistory, m_ModuleLocalEnscriptHistoryServer, m_RunColor, and m_ScriptOutputListbox.
~ScriptConsoleEnfScriptTab()
void ~ScriptConsoleEnfScriptTab () inline private
References m_Instance.
Member Function Documentation
Add()
void Add (string message, bool isReload = false) inline private
References Empty, m_AllowScriptOutput, m_ScriptOutputHistory, m_ScriptOutputListbox, and String().
Referenced by PrintS(), ReloadScriptOutput(), and Dispatcher::ScriptConsoleAddPrint().
Clear()
protected void Clear (bool clearFile = false) inline private
References Debug::ClearLogs(), and m_ScriptOutputListbox.
ColorRunButton()
protected void ColorRunButton (bool success) inline private
References ARGB(), CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), m_EnfScriptRun, and ResetRunButtonColor().
Referenced by OnRPCEx(), and RunEnscript().
EnscriptHistoryBack()
protected void EnscriptHistoryBack () inline private
References m_EnfScriptEdit, m_EnscriptConsoleHistory, and m_EnscriptHistoryRow.
Referenced by HistoryBack().
EnscriptHistoryForward()
protected void EnscriptHistoryForward () inline private
References m_EnfScriptEdit, m_EnscriptConsoleHistory, and m_EnscriptHistoryRow.
Referenced by HistoryForward().
HistoryBack()
void HistoryBack () inline private
References EnscriptHistoryBack().
Referenced by Dispatcher::ScriptConsoleHistoryBack().
HistoryForward()
void HistoryForward () inline private
References EnscriptHistoryForward().
Referenced by Dispatcher::ScriptConsoleHistoryForward().
OnChange()
override bool OnChange (Widget w, int x, int y, bool finished) inline private
References x, and y.
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References m_EnfScriptClear, m_EnfScriptRun, m_ScriptOutputHistory, m_ScriptOutputListbox, RunEnscript(), x, and y.
OnRPCEx()
override void OnRPCEx (int rpc_type, ParamsReadContext ctx) inline private
References ColorRunButton(), CachedObjectsParams::PARAM1_BOOL, and Serializer::Read().
OnSelected()
override void OnSelected () inline private
References m_EnfScriptEdit, m_EnscriptConsoleHistory, m_EnscriptHistoryRow, and ReloadScriptOutput().
PrintS() [1/6]
static void PrintS (bool message) inline static private
References PrintS(), and bool::ToString().
PrintS() [2/6]
static void PrintS (float message) inline static private
References PrintS(), and float::ToString().
PrintS() [3/6]
static void PrintS (int message) inline static private
References PrintS().
PrintS() [4/6]
static void PrintS (Object message) inline static private
References PrintS().
PrintS() [5/6]
static void PrintS (string message) inline static private
References Add(), m_Instance, and Print().
Referenced by PrintS(), PrintS(), PrintS(), PrintS(), and PrintS().
PrintS() [6/6]
static void PrintS (vector message) inline static private
References PrintS(), and vector::ToString().
ReloadScriptOutput()
protected void ReloadScriptOutput () inline private
References Add(), m_AllowScriptOutput, m_ScriptOutputHistory, and m_ScriptOutputListbox.
Referenced by OnSelected().
ResetRunButtonColor()
protected void ResetRunButtonColor () inline private
References m_EnfScriptRun, and m_RunColor.
Referenced by ColorRunButton().
RunEnscript()
protected void RunEnscript () inline private
References _player, ColorRunButton(), CGame::ExecuteEnforceScript(), GetGame(), GetPlayer(), m_AllowScriptOutput, m_EnfScriptEdit, m_EnscriptConsoleHistory, m_ModuleLocalEnscriptHistory, and string::Replace().
Referenced by OnClick().
RunEnscriptServer()
protected void RunEnscriptServer () inline private
References GetGame(), GetPlayer(), m_EnfScriptEdit, m_EnscriptConsoleHistoryServer, m_ModuleLocalEnscriptHistoryServer, CachedObjectsParams::PARAM1_STRING, and CGame::RPCSingleParam().
Show()
override void Show (bool show, ScriptConsoleTabBase selectedHandler) inline private
References ScriptConsoleTabBase::m_Root.
Field Documentation
m_AllowScriptOutput
protected bool m_AllowScriptOutput private
Referenced by Add(), ReloadScriptOutput(), and RunEnscript().
m_EnfScriptClear
protected ButtonWidget m_EnfScriptClear private
Referenced by OnClick(), and ScriptConsoleEnfScriptTab().
m_EnfScriptEdit
protected MultilineEditBoxWidget m_EnfScriptEdit private
Referenced by EnscriptHistoryBack(), EnscriptHistoryForward(), OnSelected(), RunEnscript(), RunEnscriptServer(), and ScriptConsoleEnfScriptTab().
m_EnfScriptRun
protected ButtonWidget m_EnfScriptRun private
Referenced by ColorRunButton(), OnClick(), ResetRunButtonColor(), and ScriptConsoleEnfScriptTab().
m_EnscriptConsoleHistory
protected ref TStringArray m_EnscriptConsoleHistory private
Referenced by EnscriptHistoryBack(), EnscriptHistoryForward(), OnSelected(), RunEnscript(), and ScriptConsoleEnfScriptTab().
m_EnscriptConsoleHistoryServer
protected ref TStringArray m_EnscriptConsoleHistoryServer private
Referenced by RunEnscriptServer(), and ScriptConsoleEnfScriptTab().
m_EnscriptHistoryRow
protected int m_EnscriptHistoryRow private
Referenced by EnscriptHistoryBack(), EnscriptHistoryForward(), and OnSelected().
m_EnscriptHistoryRowServer
protected int m_EnscriptHistoryRowServer private
m_Instance
protected ScriptConsoleEnfScriptTab m_Instance static private
Referenced by PrintS(), ScriptConsoleEnfScriptTab(), and ~ScriptConsoleEnfScriptTab().
m_ModuleLocalEnscriptHistory
protected PluginLocalEnscriptHistory m_ModuleLocalEnscriptHistory private
Referenced by RunEnscript(), and ScriptConsoleEnfScriptTab().
m_ModuleLocalEnscriptHistoryServer
protected PluginLocalEnscriptHistoryServer m_ModuleLocalEnscriptHistoryServer private
Referenced by RunEnscriptServer(), and ScriptConsoleEnfScriptTab().
m_RunColor
protected int m_RunColor private
Referenced by ResetRunButtonColor(), and ScriptConsoleEnfScriptTab().
m_ScriptOutputHistory
ref TStringArray m_ScriptOutputHistory = new TStringArray() static private
Referenced by Add(), OnClick(), and ReloadScriptOutput().
m_ScriptOutputListbox
protected TextListboxWidget m_ScriptOutputListbox private
Referenced by Add(), Clear(), OnClick(), ReloadScriptOutput(), and ScriptConsoleEnfScriptTab().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptConsoleEnfScriptTab.c