DayZ Scripts: WarningMenuBase Class Reference
WarningMenuBase Class Reference
Private Member Functions
void WarningMenuBase ()
void ~WarningMenuBase ()
override Widget Init ()
string GetText ()
override bool OnClick (Widget w, int x, int y, int button)
override void Update (float timeslice)
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
protected void UpdateControlsElements ()
protected void UpdateControlsElementVisibility ()
Private Attributes
protected ButtonWidget m_OkButton
protected MultilineTextWidget m_Description
Constructor & Destructor Documentation
WarningMenuBase()
void WarningMenuBase () inline private
References Mission::AddActiveInputExcludes(), GetGame(), Mission::GetHud(), CGame::GetMission(), Hud::ShowHudUI(), and Hud::ShowQuickbarUI().
~WarningMenuBase()
void ~WarningMenuBase () inline private
References GetGame(), Mission::GetHud(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), OnInputDeviceChanged(), OnInputPresetChanged(), ScriptInvoker::Remove(), Mission::RemoveActiveInputExcludes(), Hud::ShowHudUI(), and Hud::ShowQuickbarUI().
Member Function Documentation
GetText()
string GetText () inline private
Referenced by Init().
Init()
override Widget Init () inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), GetText(), CGame::GetWorkspace(), ScriptInvoker::Insert(), m_Description, m_OkButton, OnInputDeviceChanged(), and OnInputPresetChanged().
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References Close(), IDC_OK, x, and y.
OnInputDeviceChanged()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
References UpdateControlsElements(), and UpdateControlsElementVisibility().
Referenced by Init(), and ~WarningMenuBase().
OnInputPresetChanged()
protected void OnInputPresetChanged () inline private
References UpdateControlsElements().
Referenced by Init(), and ~WarningMenuBase().
Update()
override void Update (float timeslice) inline private
References Close(), and GetUApi().
UpdateControlsElements()
protected void UpdateControlsElements () inline private
References InputUtils::GetRichtextButtonIconFromInputAction(), and InputUtils::ICON_SCALE_TOOLBAR.
Referenced by OnInputDeviceChanged(), and OnInputPresetChanged().
UpdateControlsElementVisibility()
protected void UpdateControlsElementVisibility () inline private
References Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), Input::IsEnabledMouseAndKeyboard(), and m_OkButton.
Referenced by OnInputDeviceChanged().
Field Documentation
m_Description
protected MultilineTextWidget m_Description private
Referenced by Init().
m_OkButton
protected ButtonWidget m_OkButton private
Referenced by Init(), and UpdateControlsElementVisibility().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ItemDropWarningMenu.c