DayZ Scripts: UniversalTemperatureSourceLambdaBaseImpl Class Reference
UniversalTemperatureSourceLambdaBaseImpl Class Reference
Private Member Functions
override void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings, vector position, out notnull array< Object > nearestObjects)
override void WarmAndCoolItemsInVicinity (UniversalTemperatureSourceSettings pSettings, vector position, out notnull array< Object > nearestObjects)
protected void UpdateVicinityTemperatureRecursive (EntityAI ent, TemperatureData dta, float heatPermeabilityCoef=1.0)
override void Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues)
override void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings)
DEPRECATED.
Member Function Documentation
DryItemsInVicinity() [1/2]
override void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings) inline private
DEPRECATED.
References DryItemsInVicinity(), GetGame(), CGame::GetObjectsAtPosition(), UniversalTemperatureSourceSettings::m_Parent, UniversalTemperatureSourceSettings::m_Position, and UniversalTemperatureSourceSettings::m_RangeMax.
DryItemsInVicinity() [2/2]
override void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings, vector position, out notnull array< Object > nearestObjects) inline private
heat transfer to items (not in player possession)
References Math::Clamp(), vector::Distance(), UniversalTemperatureSourceLambdaBase::m_ExecuteInterval, UniversalTemperatureSourceSettings::m_Parent, Math::Max(), and GameConstants::STATE_DAMP.
Referenced by DryItemsInVicinity(), and Execute().
Execute()
override void Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues) inline private
References DryItemsInVicinity(), GetGame(), CGame::GetObjectsAtPosition(), UniversalTemperatureSourceSettings::m_Parent, UniversalTemperatureSourceSettings::m_Position, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureItemCap, and WarmAndCoolItemsInVicinity().
UpdateVicinityTemperatureRecursive()
protected void UpdateVicinityTemperatureRecursive (EntityAI ent, TemperatureData dta, float heatPermeabilityCoef = 1.0) inline private
References Math::AbsFloat(), Class::CastTo(), TemperatureData::m_AdjustedTarget, TemperatureData::m_HeatPermeabilityCoef, GameConstants::TEMPERATURE_SENSITIVITY_THRESHOLD, and UpdateVicinityTemperatureRecursive().
Referenced by UpdateVicinityTemperatureRecursive(), and WarmAndCoolItemsInVicinity().
WarmAndCoolItemsInVicinity()
override void WarmAndCoolItemsInVicinity (UniversalTemperatureSourceSettings pSettings, vector position, out notnull array< Object > nearestObjects) inline private
dist factor minimum should be at 0
References Math::AbsFloat(), Class::CastTo(), vector::Distance(), Math::InverseLerp(), UniversalTemperatureSourceLambdaBase::m_ExecuteInterval, UniversalTemperatureSourceSettings::m_Parent, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureItemCap, UniversalTemperatureSourceSettings::m_TemperatureItemCoef, Math::Max(), GameConstants::TEMPERATURE_SENSITIVITY_THRESHOLD, and UpdateVicinityTemperatureRecursive().
Referenced by Execute().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Systems/UniversalTemperatureSource/UniversalTemperatureSourceLambdaBaseImpl.c