DayZ Scripts: ActionCheckPulse Class Reference
ActionCheckPulse Class Reference
Private Member Functions
void ActionCheckPulse ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
override void OnEndServer (ActionData action_data)
Static Private Member Functions
static string GetPulseMessage (EPulseType pulse_type, int blood_level)
Private Attributes
const int TARGET_IRREGULAR_PULSE_BIT = 1 << 31
Detailed Description
Definition at line 1 of file ActionCheckPulse.c.
Constructor & Destructor Documentation
ActionCheckPulse()
void ActionCheckPulse () inline private
Definition at line 4 of file ActionCheckPulse.c.
References AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 61 of file ActionCheckPulse.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 11 of file ActionCheckPulse.c.
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetPulseMessage()
static string GetPulseMessage (EPulseType pulse_type, int blood_level) inline static private
Definition at line 17 of file ActionCheckPulse.c.
Referenced by ManBase::OnRPC().
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
Definition at line 97 of file ActionCheckPulse.c.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
Definition at line 87 of file ActionCheckPulse.c.
References ActionData::m_Player, and ActionData::m_Target.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
Definition at line 71 of file ActionCheckPulse.c.
References GetGame(), ActionData::m_Player, ActionData::m_Target, CachedObjectsParams::PARAM1_INT, CGame::RPCSingleParam(), and TARGET_IRREGULAR_PULSE_BIT.
Field Documentation
TARGET_IRREGULAR_PULSE_BIT
const int TARGET_IRREGULAR_PULSE_BIT = 1 << 31 private
Definition at line 3 of file ActionCheckPulse.c.
Referenced by OnExecuteServer(), and ManBase::OnRPC().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/Medical/ActionCheckPulse.c