DayZ Scripts: ActionInteractBaseCB Class Reference
ActionInteractBaseCB Class Reference
Private Member Functions
override void CreateActionComponent ()
override void OnAnimationEvent (int pEventID)
override void InitActionComponent ()
override void EndActionComponent ()
Member Function Documentation
CreateActionComponent()
override void CreateActionComponent () inline private
References ActionData::m_ActionComponent, and ActionBaseCB::m_ActionData.
Referenced by InitActionComponent().
EndActionComponent()
override void EndActionComponent () inline private
References ActionBaseCB::m_ActionData, ActionData::m_State, ActionBaseCB::SetCommand(), and UA_FINISHED.
InitActionComponent()
override void InitActionComponent () inline private
References Debug::ActionLog(), CreateActionComponent(), CABase::Init(), LogManager::IsActionLogEnable(), ActionData::m_Action, ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, ActionBaseCB::m_Canceled, ActionBaseCB::m_Interrupted, ActionData::m_Player, ActionBaseCB::m_SoundObject, ActionData::m_State, RegisterAnimationEvent(), UA_ANIM_EVENT, and UA_PROCESSING.
OnAnimationEvent()
override void OnAnimationEvent (int pEventID) inline private
References Debug::ActionLog(), LogManager::IsActionLogEnable(), ActionData::m_Action, ActionBaseCB::m_ActionData, ActionBaseCB::m_Interrupted, ActionData::m_Player, AnimatedActionBase::OnAnimationEvent(), and UA_ANIM_EVENT.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/ActionInteractBase.c