DayZ Scripts: AttachmentsOutOfReach Class Reference
AttachmentsOutOfReach Class Reference
Static Private Member Functions
static bool IsAttachmentReachable (EntityAI e, string att_slot_name="", int slot_id=-1, float range=1.5)
static vector GetAttachmentPosition (EntityAI e, int slot_id)
static protected map< int, vector > CreateAttachmentPosition (EntityAI entity)
Static Private Attributes
static protected ref map< string, ref map< int, vector > > m_AttData
Detailed Description
Definition at line 1 of file AttachmentsOutOfReach.c.
Member Function Documentation
CreateAttachmentPosition()
static protected map< int, vector > CreateAttachmentPosition (EntityAI entity) inline static private
Definition at line 80 of file AttachmentsOutOfReach.c.
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), string::Contains(), GetGame(), LOD::GetSelections(), InventorySlots::GetSlotIdFromString(), string::Length(), LOD::NAME_VIEW, string::Substring(), string::ToLower(), and x.
Referenced by GetAttachmentPosition().
GetAttachmentPosition()
static vector GetAttachmentPosition (EntityAI e, int slot_id) inline static private
Definition at line 61 of file AttachmentsOutOfReach.c.
References CreateAttachmentPosition(), and m_AttData.
Referenced by IsAttachmentReachable().
IsAttachmentReachable()
static bool IsAttachmentReachable (EntityAI e, string att_slot_name = "", int slot_id = -1, float range = 1.5) inline static private
Definition at line 5 of file AttachmentsOutOfReach.c.
References Math::AbsFloat(), vector::Distance(), GetAttachmentPosition(), GetGame(), GetPlayer(), InventorySlots::GetSlotIdFromString(), and InventorySlots::GetSlotName().
Referenced by Icon::MouseClick(), AttachmentCategoriesRow::RefreshSlot(), Attachments::Select(), UpdateConsoleToolbar(), and Attachments::UpdateInterval().
Field Documentation
m_AttData
protected ref map<string, ref map<int, vector> > m_AttData static private
Definition at line 3 of file AttachmentsOutOfReach.c.
Referenced by GetAttachmentPosition().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Systems/Inventory/AttachmentsOutOfReach.c