DayZ Scripts: StaminaModifiers Class Reference
StaminaModifiers Class Reference
Private Member Functions
void StaminaModifiers ()
void RegisterFixed (EStaminaModifiers modifier, float value, float cooldown=GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION)
register single value modifier - depletes stamina for that value
void RegisterRandomized (EStaminaModifiers modifier, float minValue, float maxValue, float cooldown=GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION)
register randomized modifier - stamina will be depleted by value between min and max value;
void RegisterLinear (EStaminaModifiers modifier, float startValue, float endValue, float startTime, float duration, float cooldown=GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION)
register lerped modifier - depletes stamina for startValue, and, after a startTime, lerps to endValue over duration
void RegisterExponential (EStaminaModifiers modifier, float startValue, float exponent, float startTime, float duration, float cooldown=GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION)
register exponential modifier - depletes stamina for startValue, and, after a startTime, lerps from 0 to exponent over duration
StaminaModifier GetModifierData (EStaminaModifiers modifier)
Private Attributes
const int FIXED = 0
const int RANDOMIZED = 1
const int LINEAR = 2
const int EXPONENTIAL = 3
protected ref map< EStaminaModifiers, ref StaminaModifier > m_StaminaModifiers
Detailed Description
Definition at line 178 of file StaminaHandler.c.
Constructor & Destructor Documentation
StaminaModifiers()
void StaminaModifiers () inline private
Definition at line 187 of file StaminaHandler.c.
References m_StaminaModifiers.
Member Function Documentation
GetModifierData()
StaminaModifier GetModifierData (EStaminaModifiers modifier) inline private
Definition at line 228 of file StaminaHandler.c.
References m_StaminaModifiers.
Referenced by DepleteStamina(), and ResetCooldown().
RegisterExponential()
void RegisterExponential (EStaminaModifiers modifier, float startValue, float exponent, float startTime, float duration, float cooldown = GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION) inline private
register exponential modifier - depletes stamina for startValue, and, after a startTime, lerps from 0 to exponent over duration
Definition at line 222 of file StaminaHandler.c.
References EXPONENTIAL, m_StaminaModifiers, and StaminaModifier().
Referenced by RegisterStaminaModifiers().
RegisterFixed()
void RegisterFixed (EStaminaModifiers modifier, float value, float cooldown = GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION) inline private
register single value modifier - depletes stamina for that value
init of StaminaModifier - type and min, max values (min is not relevant for that type)
Definition at line 193 of file StaminaHandler.c.
References FIXED, m_StaminaModifiers, and StaminaModifier().
Referenced by RegisterStaminaModifiers().
RegisterLinear()
void RegisterLinear (EStaminaModifiers modifier, float startValue, float endValue, float startTime, float duration, float cooldown = GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION) inline private
register lerped modifier - depletes stamina for startValue, and, after a startTime, lerps to endValue over duration
Definition at line 215 of file StaminaHandler.c.
References LINEAR, m_StaminaModifiers, and StaminaModifier().
RegisterRandomized()
void RegisterRandomized (EStaminaModifiers modifier, float minValue, float maxValue, float cooldown = GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION) inline private
register randomized modifier - stamina will be depleted by value between min and max value;
init of StaminaModifier - type, min, max values
Definition at line 204 of file StaminaHandler.c.
References m_StaminaModifiers, RANDOMIZED, and StaminaModifier().
Referenced by RegisterStaminaModifiers().
Field Documentation
EXPONENTIAL
const int EXPONENTIAL = 3 private
Definition at line 183 of file StaminaHandler.c.
Referenced by DepleteStamina(), and RegisterExponential().
FIXED
const int FIXED = 0 private
Definition at line 180 of file StaminaHandler.c.
Referenced by DepleteStamina(), and RegisterFixed().
LINEAR
const int LINEAR = 2 private
Definition at line 182 of file StaminaHandler.c.
Referenced by DepleteStamina(), and RegisterLinear().
m_StaminaModifiers
protected ref map<EStaminaModifiers, ref StaminaModifier> m_StaminaModifiers private
Definition at line 185 of file StaminaHandler.c.
Referenced by GetModifierData(), RegisterExponential(), RegisterFixed(), RegisterLinear(), RegisterRandomized(), and StaminaModifiers().
RANDOMIZED
const int RANDOMIZED = 1 private
Definition at line 181 of file StaminaHandler.c.
Referenced by DepleteStamina(), and RegisterRandomized().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/StaminaHandler.c