DayZ Scripts: DayZPlayerTypeUtils Class Reference
DayZPlayerTypeUtils Class Reference
Static Private Member Functions
static void DayZPlayerTypeCreate (DayZPlayerType pType)
static void DayZPlayerTypeInitMovement (DayZPlayerType pType)
Member Function Documentation
DayZPlayerTypeCreate()
static void DayZPlayerTypeCreate (DayZPlayerType pType) inline static private
register all item types
register all sounds
register camera creators
other configs
References DayZPlayerTypeRegisterItems(), DayZPlayerTypeRegisterSounds(), and DayZPlayerCameras::RegisterCameras().
Referenced by DayZPlayerTypeCreate().
DayZPlayerTypeInitMovement()
static void DayZPlayerTypeInitMovement (DayZPlayerType pType) inline static private
set move settings:
run sprint (SHIFT HOLD) filter
< filter span value [s]
< filter speed value [val/s]
WSAD direction filter
< direction filter timeout [s]
< sprint direction filter timeout [s]
< direction filter max rot speed [rad/s]
< max sprint angle [rad]
< this is when char starts tu turn
< this is end norm time (turn amount is not updated after this time)
< this is norm time when new turn from old turn is evaluated again (turn->turn)
<
<
<
<
< Water level (in meters) - m_iMaxSpeedNormal_WaterLevelLow and m_iMaxSpeedFast_WaterLevelLow are applied when character is deeper
< Water level (in meters) - m_iMaxSpeedNormal_WaterLevelHigh and m_iMaxSpeedFast_WaterLevelHigh are applied when character is deeper
< Max movement speed for m_fWaterLevelSpeedRectrictionLow when character doesn't want to sprint (-1 means no change)
< Max movement speed for m_fWaterLevelSpeedRectrictionLow when character wants to sprint (-1 means no change)
< Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character doesn't want to sprint (-1 means no change)
< Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character wants to sprint (-1 means no change)
animation speed settings example
References CfgGameplayHandler::GetMovementTimeToSprint(), CfgGameplayHandler::GetMovementTimeToStrafeJog(), and SHumanCommandMoveSettings().
Referenced by DayZPlayerTypeInitMovement().
The documentation for this class was generated from the following file:
P:/scripts/4_world/entities/manbase/dayzplayer/dayzplayercfgbase.c