DayZ Scripts: WeaponFire Class Reference
WeaponFire Class Reference
Private Member Functions
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
Member Function Documentation
OnEntry() [1/3]
override void OnEntry (WeaponEventBase e) inline private
References Class::CastTo(), LogManager::IsWeaponLogEnable(), m_dtAccumulator, WeaponEventBase::m_player, m_weapon, TryFireWeapon(), and wpnPrint().
Referenced by BotStateBase::OnEntry().
OnEntry() [2/3]
override void OnEntry (WeaponEventBase e) inline private
References LogManager::IsWeaponLogEnable(), m_weapon, pushToChamberFromAttachedMagazine(), and wpnDebugPrint().
OnEntry() [3/3]
override void OnEntry (WeaponEventBase e) inline private
References LogManager::IsWeaponLogEnable(), m_weapon, pushToChamberFromInnerMagazine(), and wpnDebugPrint().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponFire.c