DayZ Scripts: AnalyticsManagerServer Class Reference
AnalyticsManagerServer Class Reference
Private Member Functions
void OnPlayerConnect (Man player)
void OnPlayerDisconnect (Man player)
void OnEntityHit (EntityAI source, Man target)
protected void OnPlayerToPlayerHit (Man shooter, Man target)
void OnEntityKilled (Object killer, EntityAI target)
protected void OnPlayerKilled (Man killer, EntityAI target)
protected void OnInfectedKilled (Man killer, EntityAI target)
Private Attributes
const string STAT_DISTANCE = "dist"
const string STAT_PLAYTIME = "playtime"
const string STAT_PLAYERS_KILLED = "players_killed"
const string STAT_INFECTED_KILLED = "infected_killed"
const string STAT_LONGEST_SURVIVOR_HIT = "longest_survivor_hit"
Detailed Description
Definition at line 1 of file AnalyticsManagerServer.c.
Member Function Documentation
OnEntityHit()
void OnEntityHit (EntityAI source, Man target) inline private
Definition at line 41 of file AnalyticsManagerServer.c.
References OnPlayerToPlayerHit().
Referenced by ManBase::EEHitBy().
OnEntityKilled()
void OnEntityKilled (Object killer, EntityAI target) inline private
Definition at line 78 of file AnalyticsManagerServer.c.
References OnInfectedKilled(), and OnPlayerKilled().
Referenced by Plastic_Explosive::EEKilled(), and Ammo_40mm_Smoke_ColorBase::EEKilled().
OnInfectedKilled()
protected void OnInfectedKilled (Man killer, EntityAI target) inline private
Definition at line 113 of file AnalyticsManagerServer.c.
References STAT_INFECTED_KILLED.
Referenced by OnEntityKilled().
OnPlayerConnect()
void OnPlayerConnect (Man player) inline private
Definition at line 9 of file AnalyticsManagerServer.c.
References STAT_DISTANCE, STAT_INFECTED_KILLED, STAT_LONGEST_SURVIVOR_HIT, STAT_PLAYERS_KILLED, and STAT_PLAYTIME.
Referenced by ManBase::OnConnect().
OnPlayerDisconnect()
void OnPlayerDisconnect (Man player) inline private
Definition at line 20 of file AnalyticsManagerServer.c.
References STAT_DISTANCE, and STAT_PLAYTIME.
Referenced by ManBase::OnDisconnect().
OnPlayerKilled()
protected void OnPlayerKilled (Man killer, EntityAI target) inline private
Definition at line 98 of file AnalyticsManagerServer.c.
References STAT_PLAYERS_KILLED.
Referenced by OnEntityKilled().
OnPlayerToPlayerHit()
protected void OnPlayerToPlayerHit (Man shooter, Man target) inline private
Definition at line 53 of file AnalyticsManagerServer.c.
References vector::Distance(), and STAT_LONGEST_SURVIVOR_HIT.
Referenced by OnEntityHit().
Field Documentation
STAT_DISTANCE
const string STAT_DISTANCE = "dist" private
Definition at line 3 of file AnalyticsManagerServer.c.
Referenced by OnPlayerConnect(), OnPlayerDisconnect(), and ScriptedWidgetEventHandler::UpdateStats().
STAT_INFECTED_KILLED
const string STAT_INFECTED_KILLED = "infected_killed" private
Definition at line 6 of file AnalyticsManagerServer.c.
Referenced by OnInfectedKilled(), OnPlayerConnect(), and ScriptedWidgetEventHandler::UpdateStats().
STAT_LONGEST_SURVIVOR_HIT
const string STAT_LONGEST_SURVIVOR_HIT = "longest_survivor_hit" private
Definition at line 7 of file AnalyticsManagerServer.c.
Referenced by OnPlayerConnect(), OnPlayerToPlayerHit(), and ScriptedWidgetEventHandler::UpdateStats().
STAT_PLAYERS_KILLED
const string STAT_PLAYERS_KILLED = "players_killed" private
Definition at line 5 of file AnalyticsManagerServer.c.
Referenced by OnPlayerConnect(), OnPlayerKilled(), and ScriptedWidgetEventHandler::UpdateStats().
STAT_PLAYTIME
const string STAT_PLAYTIME = "playtime" private
Definition at line 4 of file AnalyticsManagerServer.c.
Referenced by OnPlayerConnect(), OnPlayerDisconnect(), and ScriptedWidgetEventHandler::UpdateStats().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Analytics/AnalyticsManagerServer.c