DayZ Scripts: ItemManager Class Reference
ItemManager Class Reference
Private Member Functions
void ItemManager (Widget root)
void SetItemMicromanagmentMode (bool item_micromanagment_mode)
bool IsMicromanagmentMode ()
HandsPreview GetHandsPreview ()
void SetHandsPreview (HandsPreview hansd_preview)
EntityAI GetSelectedItem ()
Container GetSelectedContainer ()
Widget GetSelectedWidget ()
SlotsIcon GetSelectedIcon ()
void SetSelectedItem (EntityAI selected_item, Container selected_container, Widget selected_widget, SlotsIcon selected_icon)
void ClearDefaultOpenStates ()
void ClearDefaultHeaderOpenStates ()
void SetDefaultOpenState (string type, bool is_opened)
void SetDefaultHeaderOpenState (string type, bool is_opened)
void SetDefaultOpenStateHands (bool is_opened)
bool GetDefaultOpenStateHands ()
void SerializeDefaultHeaderOpenStates ()
void DeserializeDefaultHeaderOpenStates ()
void SerializeDefaultOpenStates ()
void DeserializeDefaultOpenStates ()
bool GetDefaultOpenState (string type)
bool GetDefaultHeaderOpenState (string type)
void HideDropzones ()
void ShowSourceDropzone (EntityAI item)
Widget GetLeftDropzone ()
Widget GetRightDropzone ()
Widget GetCenterDropzone ()
EntityAI GetHoveredItem ()
void SetDraggedItem (EntityAI dragged_item)
EntityAI GetDraggedItem ()
void SetDraggedIcon (Icon dragged_icon)
Icon GetDraggedIcon ()
void SetIsDragging (bool is_dragging)
bool IsDragging ()
void HideTooltip ()
void HideTooltipSlot ()
void SetTemperature (EntityAI item, Widget item_w)
void SetIconTemperature (EntityAI item, Widget item_w)
void PrepareTooltip (EntityAI item, int x=0, int y=0)
void PrepareSlotsTooltip (string name, string desc, int x=0, int y=0)
position is currentlycalculated from the owning 'm_TooltipSourceWidget' directly
void CalculateTooltipSlotPosition (int x=0, int y=0)
void UpdateTooltipSlotPosition ()
void SetTooltipWidget (Widget w)
bool EvaluateContainerDragabilityDefault (EntityAI entity)
void SetWidgetDraggable (Widget w, bool draggable)
void ShowTooltip ()
void ShowTooltipSlot ()
Static Private Member Functions
static ItemManager GetInstance ()
static int GetItemHealthColor (int pHealthLevel)
static int GetItemHealthColor (EntityAI item, string zone="")
static int ColorFromFloat (float fraction)
static int GetCombinationFlags (EntityAI entity1, EntityAI entity2)
static int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2)
Private Attributes
protected bool m_IsDragging
protected EntityAI m_HoveredItem
protected bool m_SlotInfoShown
protected EntityAI m_DraggedItem
protected Icon m_DraggedIcon
protected ref Widget m_TooltipWidget
protected ref Widget m_TooltipSlotWidget
protected ref Widget m_TooltipCategoryWidget
protected ItemPreviewWidget m_ItemPreviewWidget
protected Widget m_RootWidget
protected ref map< string, bool > m_DefautOpenStates
protected ref map< string, bool > m_DefautHeaderOpenStates
protected int m_HandsDefaultOpenState
protected ref Timer m_ToolTipTimer
protected ref Timer m_TooltipSlotTimer
protected EntityAI m_SelectedItem
protected Container m_SelectedContainer
protected Widget m_SelectedWidget
protected SlotsIcon m_SelectedIcon
protected HandsPreview m_HandsPreview
protected bool m_ItemMicromanagmentMode
protected Widget m_LeftDropzone
protected Widget m_CenterDropzone
protected Widget m_RightDropzone
protected int m_TooltipPosX
protected int m_TooltipPosY
protected Widget m_TooltipSourceWidget
protected const float TOOLTIP_DELAY = 0.25
Static Private Attributes
private static ref ItemManager m_Instance
Detailed Description
Definition at line 1 of file ItemManager.c.
Constructor & Destructor Documentation
ItemManager()
void ItemManager (Widget root) inline private
Definition at line 43 of file ItemManager.c.
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_DefautHeaderOpenStates, m_DefautOpenStates, m_Instance, m_RootWidget, m_SlotInfoShown, m_TooltipSlotWidget, and m_TooltipWidget.
Member Function Documentation
CalculateTooltipSlotPosition()
void CalculateTooltipSlotPosition (int x = 0, int y = 0) inline private
Definition at line 551 of file ItemManager.c.
References SlotsIcon::GetNormalHeight(), SlotsIcon::GetNormalWidth(), GetScreenSize(), m_TooltipPosX, m_TooltipPosY, m_TooltipSlotWidget, m_TooltipSourceWidget, x, and y.
Referenced by UpdateTooltipSlotPosition().
ClearDefaultHeaderOpenStates()
void ClearDefaultHeaderOpenStates () inline private
Definition at line 115 of file ItemManager.c.
References m_DefautHeaderOpenStates.
Referenced by DeserializeDefaultHeaderOpenStates().
ClearDefaultOpenStates()
void ClearDefaultOpenStates () inline private
Definition at line 110 of file ItemManager.c.
References m_DefautOpenStates.
Referenced by DeserializeDefaultOpenStates().
ColorFromFloat()
static int ColorFromFloat (float fraction) inline static private
Definition at line 402 of file ItemManager.c.
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, and Colors::COLOR_WORN.
DeserializeDefaultHeaderOpenStates()
void DeserializeDefaultHeaderOpenStates () inline private
Definition at line 163 of file ItemManager.c.
References ClearDefaultHeaderOpenStates(), GetGame(), CGame::GetProfileStringList(), and SetDefaultHeaderOpenState().
Referenced by Deserialize().
DeserializeDefaultOpenStates()
void DeserializeDefaultOpenStates () inline private
Definition at line 196 of file ItemManager.c.
References ClearDefaultOpenStates(), GetGame(), CGame::GetProfileStringList(), and SetDefaultOpenState().
Referenced by Deserialize().
EvaluateContainerDragabilityDefault()
bool EvaluateContainerDragabilityDefault (EntityAI entity) inline private
Definition at line 630 of file ItemManager.c.
References GetGame(), and GetPlayer().
Referenced by VicinitySlotsContainer::MouseButtonDown(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinityContainer::UpdateHeader().
GetCenterDropzone()
Widget GetCenterDropzone () inline private
Definition at line 291 of file ItemManager.c.
References m_CenterDropzone, and m_RootWidget.
Referenced by HandsContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), Icon::DraggingOverSwap(), HideDropzones(), Icon::ShowActionMenuCombine(), and ShowSourceDropzone().
GetCombinationFlags()
static int GetCombinationFlags (EntityAI entity1, EntityAI entity2) inline static private
Definition at line 670 of file ItemManager.c.
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, ItemBase::CanBeCombined(), ActionManagerClient::CanPerformActionFromInventory(), ActionManagerClient::CanSetActionFromInventory(), Class::CastTo(), InventoryCombinationFlags::COMBINE_QUANTITY2, GetGame(), GetPlayer(), GetRecipeCount(), m_player, InventoryCombinationFlags::PERFORM_ACTION, InventoryCombinationFlags::RECIPE_ANYWHERE, and InventoryCombinationFlags::SET_ACTION.
Referenced by Attachments::CanCombine(), Container::CanCombine(), PlayerContainer::CanCombine(), VicinitySlotsContainer::CanCombine(), Icon::Combine(), Icon::CombineItems(), and Icon::DraggingOverCombine().
GetDefaultHeaderOpenState()
bool GetDefaultHeaderOpenState (string type) inline private
Definition at line 224 of file ItemManager.c.
References m_DefautHeaderOpenStates.
Referenced by CollapsibleContainer::LoadDefaultState().
GetDefaultOpenState()
bool GetDefaultOpenState (string type) inline private
Definition at line 212 of file ItemManager.c.
References m_DefautOpenStates.
GetDefaultOpenStateHands()
bool GetDefaultOpenStateHands () inline private
Definition at line 138 of file ItemManager.c.
References GetGame(), CGame::GetProfileString(), m_HandsDefaultOpenState, and string::ToInt().
GetDraggedIcon()
Icon GetDraggedIcon () inline private
Definition at line 318 of file ItemManager.c.
References m_DraggedIcon.
Referenced by Icon::DropReceivedFromMain(), and Icon::Swap().
GetDraggedItem()
EntityAI GetDraggedItem () inline private
Definition at line 308 of file ItemManager.c.
References m_DraggedItem.
Referenced by ColorManager::GetItemColor(), InventoryGridController::OnItemDropReceived(), AttachmentCategoriesRow::RefreshSlot(), Attachments::UpdateInterval(), ClosableContainer::UpdateInterval(), and UpdateInterval().
GetHandsPreview()
HandsPreview GetHandsPreview () inline private
Definition at line 72 of file ItemManager.c.
References m_HandsPreview.
Referenced by Attachments::Combine(), PlayerContainer::Combine(), and VicinitySlotsContainer::Combine().
GetHoveredItem()
EntityAI GetHoveredItem () inline private
Definition at line 298 of file ItemManager.c.
References m_HoveredItem.
Referenced by UpdateInterval().
GetInstance()
static ItemManager GetInstance () inline static private
Definition at line 236 of file ItemManager.c.
References m_Instance.
Referenced by SlotsIcon::Clear(), Container::Close(), ClosableContainer::Close(), VicinityContainer::CollapseButtonOnMouseButtonDown(), Attachments::Combine(), PlayerContainer::Combine(), VicinitySlotsContainer::Combine(), Icon::Combine(), Icon::CreateWhiteBackground(), Deserialize(), Icon::DestroyWhiteBackground(), DisableMicromanagement(), Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), Icon::DropReceivedFromMain(), EnableMicromanagement(), ColorManager::GetItemColor(), HandsContainer::HandsContainer(), ScriptedWidgetEventHandler::HideOwnedSlotsTooltip(), ScriptedWidgetEventHandler::HideOwnedTooltip(), Icon::Icon(), SlotsIcon::Init(), Icon::InitLock(), CollapsibleContainer::LoadDefaultState(), VicinitySlotsContainer::MouseButtonDown(), Icon::MouseClick(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), MoveFocusByArea(), Icon::OnDraggingOverBackground(), ClosableHeader::OnDragHeader(), ClosableHeader::OnDropHeader(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), OnHide(), SlotsIcon::OnIconDrag(), SlotsIcon::OnIconDrop(), InventoryGridController::OnItemDrop(), InventoryGridController::OnItemDropReceived(), HandsContainer::OnSelectButton(), OnShow(), MissionBase::OnUpdate(), Container::Open(), ClosableContainer::Open(), ScriptedWidgetEventHandler::PrepareOwnedSlotsTooltip(), ScriptedWidgetEventHandler::PrepareOwnedTooltip(), AttachmentCategoriesRow::RefreshSlot(), Attachments::Select(), Container::Select(), HandsPreview::Select(), AttachmentCategoriesRow::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), Attachments::SelectItem(), Container::SelectItem(), HandsPreview::SelectItem(), SlotsContainer::SelectItem(), Serialize(), Container::SetOpenState(), Icon::SetTemperature(), SlotsIcon::SetTemperature(), Icon::ShowActionMenuCombine(), VicinitySlotsContainer::ShowItemsInContainers(), Icon::Swap(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), PlayerContainer::ToggleWidget(), VicinityContainer::UpdateHeader(), Attachments::UpdateInterval(), HandsPreview::UpdateInterval(), ClosableContainer::UpdateInterval(), UpdateInterval(), IconsContainer::UpdateItemsTemperature(), Icon::~Icon(), and SlotsIcon::~SlotsIcon().
GetItemHealthColor() [1/2]
static int GetItemHealthColor (EntityAI item, string zone = "") inline static private
Definition at line 378 of file ItemManager.c.
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, Colors::COLOR_WORN, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
GetItemHealthColor() [2/2]
static int GetItemHealthColor (int pHealthLevel) inline static private
Definition at line 357 of file ItemManager.c.
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, Colors::COLOR_WORN, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
Referenced by Hud::RefreshVehicleHud().
GetLeftDropzone()
Widget GetLeftDropzone () inline private
Definition at line 276 of file ItemManager.c.
References m_LeftDropzone, and m_RootWidget.
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), HideDropzones(), Icon::OnDraggingOverBackground(), SlotsIcon::OnIconDrag(), and ShowSourceDropzone().
GetRecipeCount()
static int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2) inline static private
Definition at line 734 of file ItemManager.c.
References GetGame(), GetPlayer(), and GetPlugin().
Referenced by GetCombinationFlags().
GetRightDropzone()
Widget GetRightDropzone () inline private
Definition at line 284 of file ItemManager.c.
References m_RightDropzone, and m_RootWidget.
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), HideDropzones(), Icon::OnDraggingOverBackground(), SlotsIcon::OnIconDrag(), and ShowSourceDropzone().
GetSelectedContainer()
Container GetSelectedContainer () inline private
Definition at line 87 of file ItemManager.c.
References m_SelectedContainer.
Referenced by Container::Select().
GetSelectedIcon()
SlotsIcon GetSelectedIcon () inline private
Definition at line 97 of file ItemManager.c.
References m_SelectedIcon.
Referenced by Attachments::Select(), VicinitySlotsContainer::Select(), and ZombieContainer::Select().
GetSelectedItem()
EntityAI GetSelectedItem () inline private
Definition at line 82 of file ItemManager.c.
References m_SelectedItem.
Referenced by HandsContainer::OnSelectButton(), MissionBase::OnUpdate(), Attachments::Select(), Container::Select(), HandsPreview::Select(), AttachmentCategoriesRow::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), and ZombieContainer::Select().
GetSelectedWidget()
Widget GetSelectedWidget () inline private
Definition at line 92 of file ItemManager.c.
References m_SelectedWidget.
HideDropzones()
void HideDropzones () inline private
Definition at line 241 of file ItemManager.c.
References GetCenterDropzone(), GetLeftDropzone(), and GetRightDropzone().
Referenced by Icon::Combine(), Icon::DestroyWhiteBackground(), Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), Icon::DropReceivedFromMain(), Icon::OnDraggingOverBackground(), ClosableHeader::OnDropHeader(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), SlotsIcon::OnIconDrag(), SlotsIcon::OnIconDrop(), InventoryGridController::OnItemDrop(), Icon::ShowActionMenuCombine(), ShowSourceDropzone(), Icon::Swap(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), Icon::~Icon(), and SlotsIcon::~SlotsIcon().
HideTooltip()
void HideTooltip () inline private
Definition at line 338 of file ItemManager.c.
References HideTooltipSlot(), m_HoveredItem, m_ToolTipTimer, and m_TooltipWidget.
Referenced by ScriptedWidgetEventHandler::HideOwnedTooltip(), OnHide(), PrepareSlotsTooltip(), and PrepareTooltip().
HideTooltipSlot()
void HideTooltipSlot () inline private
Definition at line 347 of file ItemManager.c.
References m_SlotInfoShown, m_TooltipSlotTimer, and m_TooltipSlotWidget.
Referenced by ScriptedWidgetEventHandler::HideOwnedSlotsTooltip(), and HideTooltip().
IsDragging()
bool IsDragging () inline private
Definition at line 333 of file ItemManager.c.
References m_IsDragging.
Referenced by PrepareTooltip(), VicinitySlotsContainer::ShowItemsInContainers(), PlayerContainer::ToggleWidget(), HandsPreview::UpdateInterval(), and IconsContainer::UpdateItemsTemperature().
IsMicromanagmentMode()
bool IsMicromanagmentMode () inline private
Definition at line 67 of file ItemManager.c.
References m_ItemMicromanagmentMode.
Referenced by DisableMicromanagement(), EnableMicromanagement(), MoveFocusByArea(), HandsContainer::OnSelectButton(), HandsPreview::Select(), and UpdateInterval().
PrepareSlotsTooltip()
void PrepareSlotsTooltip (string name, string desc, int x = 0, int y = 0) inline private
position is currentlycalculated from the owning 'm_TooltipSourceWidget' directly
Definition at line 536 of file ItemManager.c.
References HideTooltip(), m_SlotInfoShown, m_TooltipSlotTimer, m_TooltipSlotWidget, name, and TOOLTIP_DELAY.
Referenced by ScriptedWidgetEventHandler::PrepareOwnedSlotsTooltip().
PrepareTooltip()
void PrepareTooltip (EntityAI item, int x = 0, int y = 0) inline private
Definition at line 473 of file ItemManager.c.
References GetGame(), GetInput(), GetMousePos(), GetScreenSize(), HideTooltip(), IsDragging(), m_HoveredItem, m_ItemPreviewWidget, m_RootWidget, m_ToolTipTimer, m_TooltipWidget, ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetView(), TOOLTIP_DELAY, x, and y.
Referenced by ScriptedWidgetEventHandler::PrepareOwnedTooltip().
SerializeDefaultHeaderOpenStates()
void SerializeDefaultHeaderOpenStates () inline private
Definition at line 146 of file ItemManager.c.
References GetGame(), m_DefautHeaderOpenStates, CGame::SaveProfile(), and CGame::SetProfileStringList().
Referenced by Serialize().
SerializeDefaultOpenStates()
void SerializeDefaultOpenStates () inline private
Definition at line 179 of file ItemManager.c.
References GetGame(), m_DefautOpenStates, CGame::SaveProfile(), and CGame::SetProfileStringList().
Referenced by Serialize().
SetDefaultHeaderOpenState()
void SetDefaultHeaderOpenState (string type, bool is_opened) inline private
Definition at line 125 of file ItemManager.c.
References m_DefautHeaderOpenStates.
Referenced by VicinityContainer::CollapseButtonOnMouseButtonDown(), and DeserializeDefaultHeaderOpenStates().
SetDefaultOpenState()
void SetDefaultOpenState (string type, bool is_opened) inline private
Definition at line 120 of file ItemManager.c.
References m_DefautOpenStates.
Referenced by Container::Close(), ClosableContainer::Close(), DeserializeDefaultOpenStates(), Container::Open(), ClosableContainer::Open(), and Container::SetOpenState().
SetDefaultOpenStateHands()
void SetDefaultOpenStateHands (bool is_opened) inline private
Definition at line 130 of file ItemManager.c.
References GetGame(), m_HandsDefaultOpenState, CGame::SaveProfile(), and CGame::SetProfileString().
SetDraggedIcon()
void SetDraggedIcon (Icon dragged_icon) inline private
Definition at line 313 of file ItemManager.c.
References m_DraggedIcon.
Referenced by Icon::CreateWhiteBackground(), and SetIsDragging().
SetDraggedItem()
void SetDraggedItem (EntityAI dragged_item) inline private
Definition at line 303 of file ItemManager.c.
References m_DraggedItem.
Referenced by Icon::CreateWhiteBackground(), SlotsIcon::OnIconDrag(), and SetIsDragging().
SetHandsPreview()
void SetHandsPreview (HandsPreview hansd_preview) inline private
Definition at line 77 of file ItemManager.c.
References m_HandsPreview.
Referenced by HandsContainer::HandsContainer().
SetIconTemperature()
void SetIconTemperature (EntityAI item, Widget item_w) inline private
Definition at line 449 of file ItemManager.c.
References ColorManager::BASE_COLOR, ColorManager::GetInstance(), and ColorManager::GetItemColor().
Referenced by Icon::SetTemperature(), and SlotsIcon::SetTemperature().
SetIsDragging()
void SetIsDragging (bool is_dragging) inline private
Definition at line 323 of file ItemManager.c.
References m_IsDragging, SetDraggedIcon(), and SetDraggedItem().
Referenced by Icon::Combine(), Icon::CreateWhiteBackground(), Icon::DestroyWhiteBackground(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), Icon::DropReceivedFromMain(), ClosableHeader::OnDragHeader(), ClosableHeader::OnDropHeader(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), SlotsIcon::OnIconDrag(), SlotsIcon::OnIconDrop(), Icon::Swap(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), Icon::~Icon(), and SlotsIcon::~SlotsIcon().
SetItemMicromanagmentMode()
void SetItemMicromanagmentMode (bool item_micromanagment_mode) inline private
Definition at line 62 of file ItemManager.c.
References m_ItemMicromanagmentMode.
Referenced by DisableMicromanagement(), EnableMicromanagement(), OnHide(), and OnShow().
SetSelectedItem()
void SetSelectedItem (EntityAI selected_item, Container selected_container, Widget selected_widget, SlotsIcon selected_icon) inline private
Definition at line 102 of file ItemManager.c.
References m_SelectedContainer, m_SelectedIcon, m_SelectedItem, and m_SelectedWidget.
Referenced by DisableMicromanagement(), Icon::Icon(), OnHide(), OnShow(), Attachments::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), Attachments::SelectItem(), Container::SelectItem(), HandsPreview::SelectItem(), and SlotsContainer::SelectItem().
SetTemperature()
void SetTemperature (EntityAI item, Widget item_w) inline private
Definition at line 418 of file ItemManager.c.
References ColorManager::GetInstance(), ColorManager::GetItemColor(), name, and string::Replace().
Referenced by VicinitySlotsContainer::ShowItemsInContainers().
SetTooltipWidget()
void SetTooltipWidget (Widget w) inline private
Definition at line 625 of file ItemManager.c.
References m_TooltipSourceWidget.
Referenced by ScriptedWidgetEventHandler::PrepareOwnedSlotsTooltip().
SetWidgetDraggable()
void SetWidgetDraggable (Widget w, bool draggable) inline private
Definition at line 644 of file ItemManager.c.
Referenced by SlotsIcon::Clear(), SlotsIcon::Init(), Icon::InitLock(), VicinitySlotsContainer::MouseButtonDown(), Icon::MouseClick(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinityContainer::UpdateHeader().
ShowSourceDropzone()
void ShowSourceDropzone (EntityAI item) inline private
Definition at line 248 of file ItemManager.c.
References GetCenterDropzone(), GetGame(), GetLeftDropzone(), GetPlayer(), GetRightDropzone(), InventoryLocation::GetType(), HideDropzones(), and ShowSourceDropzone().
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), Icon::ShowActionMenuCombine(), and ShowSourceDropzone().
ShowTooltip()
void ShowTooltip () inline private
Definition at line 655 of file ItemManager.c.
References m_ItemPreviewWidget, and m_TooltipWidget.
ShowTooltipSlot()
void ShowTooltipSlot () inline private
Definition at line 663 of file ItemManager.c.
References m_TooltipPosX, m_TooltipPosY, m_TooltipSlotWidget, and UpdateTooltipSlotPosition().
UpdateTooltipSlotPosition()
void UpdateTooltipSlotPosition () inline private
Definition at line 618 of file ItemManager.c.
References CalculateTooltipSlotPosition(), m_TooltipSourceWidget, x, and y.
Referenced by ShowTooltipSlot().
Field Documentation
m_CenterDropzone
protected Widget m_CenterDropzone private
Definition at line 30 of file ItemManager.c.
Referenced by GetCenterDropzone().
m_DefautHeaderOpenStates
protected ref map<string, bool> m_DefautHeaderOpenStates private
Definition at line 15 of file ItemManager.c.
Referenced by ClearDefaultHeaderOpenStates(), GetDefaultHeaderOpenState(), ItemManager(), SerializeDefaultHeaderOpenStates(), and SetDefaultHeaderOpenState().
m_DefautOpenStates
protected ref map<string, bool> m_DefautOpenStates private
Definition at line 14 of file ItemManager.c.
Referenced by ClearDefaultOpenStates(), GetDefaultOpenState(), ItemManager(), SerializeDefaultOpenStates(), and SetDefaultOpenState().
m_DraggedIcon
protected Icon m_DraggedIcon private
Definition at line 8 of file ItemManager.c.
Referenced by GetDraggedIcon(), and SetDraggedIcon().
m_DraggedItem
protected EntityAI m_DraggedItem private
Definition at line 7 of file ItemManager.c.
Referenced by GetDraggedItem(), and SetDraggedItem().
m_HandsDefaultOpenState
protected int m_HandsDefaultOpenState private
Definition at line 16 of file ItemManager.c.
Referenced by GetDefaultOpenStateHands(), and SetDefaultOpenStateHands().
m_HandsPreview
protected HandsPreview m_HandsPreview private
Definition at line 25 of file ItemManager.c.
Referenced by GetHandsPreview(), and SetHandsPreview().
m_HoveredItem
protected EntityAI m_HoveredItem private
Definition at line 5 of file ItemManager.c.
Referenced by GetHoveredItem(), HideTooltip(), and PrepareTooltip().
m_Instance
private static ref ItemManager m_Instance static private
Definition at line 3 of file ItemManager.c.
Referenced by GetInstance(), and ItemManager().
m_IsDragging
protected bool m_IsDragging private
Definition at line 4 of file ItemManager.c.
Referenced by IsDragging(), and SetIsDragging().
m_ItemMicromanagmentMode
protected bool m_ItemMicromanagmentMode private
Definition at line 27 of file ItemManager.c.
Referenced by IsMicromanagmentMode(), and SetItemMicromanagmentMode().
m_ItemPreviewWidget
protected ItemPreviewWidget m_ItemPreviewWidget private
Definition at line 12 of file ItemManager.c.
Referenced by PrepareTooltip(), and ShowTooltip().
m_LeftDropzone
protected Widget m_LeftDropzone private
Definition at line 29 of file ItemManager.c.
Referenced by GetLeftDropzone().
m_RightDropzone
protected Widget m_RightDropzone private
Definition at line 31 of file ItemManager.c.
Referenced by GetRightDropzone().
m_RootWidget
protected Widget m_RootWidget private
Definition at line 13 of file ItemManager.c.
Referenced by GetCenterDropzone(), GetLeftDropzone(), GetRightDropzone(), ItemManager(), and PrepareTooltip().
m_SelectedContainer
protected Container m_SelectedContainer private
Definition at line 21 of file ItemManager.c.
Referenced by GetSelectedContainer(), and SetSelectedItem().
m_SelectedIcon
protected SlotsIcon m_SelectedIcon private
Definition at line 23 of file ItemManager.c.
Referenced by GetSelectedIcon(), and SetSelectedItem().
m_SelectedItem
protected EntityAI m_SelectedItem private
Definition at line 20 of file ItemManager.c.
Referenced by GetSelectedItem(), and SetSelectedItem().
m_SelectedWidget
protected Widget m_SelectedWidget private
Definition at line 22 of file ItemManager.c.
Referenced by GetSelectedWidget(), and SetSelectedItem().
m_SlotInfoShown
protected bool m_SlotInfoShown private
Definition at line 6 of file ItemManager.c.
Referenced by HideTooltipSlot(), ItemManager(), and PrepareSlotsTooltip().
m_TooltipCategoryWidget
protected ref Widget m_TooltipCategoryWidget private
Definition at line 11 of file ItemManager.c.
m_TooltipPosX
protected int m_TooltipPosX private
Definition at line 33 of file ItemManager.c.
Referenced by CalculateTooltipSlotPosition(), and ShowTooltipSlot().
m_TooltipPosY
protected int m_TooltipPosY private
Definition at line 34 of file ItemManager.c.
Referenced by CalculateTooltipSlotPosition(), and ShowTooltipSlot().
m_TooltipSlotTimer
protected ref Timer m_TooltipSlotTimer private
Definition at line 18 of file ItemManager.c.
Referenced by HideTooltipSlot(), and PrepareSlotsTooltip().
m_TooltipSlotWidget
protected ref Widget m_TooltipSlotWidget private
Definition at line 10 of file ItemManager.c.
Referenced by CalculateTooltipSlotPosition(), HideTooltipSlot(), ItemManager(), PrepareSlotsTooltip(), and ShowTooltipSlot().
m_TooltipSourceWidget
protected Widget m_TooltipSourceWidget private
Definition at line 35 of file ItemManager.c.
Referenced by CalculateTooltipSlotPosition(), SetTooltipWidget(), and UpdateTooltipSlotPosition().
m_ToolTipTimer
protected ref Timer m_ToolTipTimer private
Definition at line 17 of file ItemManager.c.
Referenced by HideTooltip(), and PrepareTooltip().
m_TooltipWidget
protected ref Widget m_TooltipWidget private
Definition at line 9 of file ItemManager.c.
Referenced by HideTooltip(), ItemManager(), PrepareTooltip(), and ShowTooltip().
TOOLTIP_DELAY
protected const float TOOLTIP_DELAY = 0.25 private
Definition at line 38 of file ItemManager.c.
Referenced by PrepareSlotsTooltip(), and PrepareTooltip().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/ItemManager.c