DayZ Scripts: ActionTakeHybridAttachmentToHands Class Reference
ActionTakeHybridAttachmentToHands Class Reference
Private Member Functions
void ActionTakeHybridAttachmentToHands ()
override void CreateConditionComponents ()
override bool HasProneException ()
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanContinue (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
protected void OnExecuteImpl (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override void CreateAndSetupActionCallback (ActionData action_data)
Constructor & Destructor Documentation
ActionTakeHybridAttachmentToHands()
void ActionTakeHybridAttachmentToHands () inline private
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References ItemBase::IsTakeable().
CanContinue()
override bool CanContinue (ActionData action_data) inline private
CreateAndSetupActionCallback()
override void CreateAndSetupActionCallback (ActionData action_data) inline private
References Class::CastTo(), AnimatedActionBase::GetCallbackClassTypename(), ActionData::m_Callback, ActionData::m_Player, and ActionData::m_Target.
CreateConditionComponents()
override void CreateConditionComponents () inline private
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType () inline private
HasProgress()
override bool HasProgress () inline private
HasProneException()
override bool HasProneException () inline private
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
References OnExecuteImpl().
OnExecuteImpl()
protected void OnExecuteImpl (ActionData action_data) inline private
References ClearInventoryReservationEx(), ActionData::m_Player, and ActionData::m_Target.
Referenced by OnExecuteClient(), and OnExecuteServer().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
References GetGame(), and OnExecuteImpl().
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/Actions/Interact/ActionTakeHybridAttachmentToHands.c