DayZ Scripts: TriggerEvents Class Reference
TriggerEvents Class Reference
Private Member Functions
OnEnter
Called when an object enters the trigger
protected void Enter (TriggerInsider insider)
protected void OnEnterBeginEvent (TriggerInsider insider)
protected void OnEnterServerEvent (TriggerInsider insider)
protected void OnEnterClientEvent (TriggerInsider insider)
protected void OnEnterEndEvent (TriggerInsider insider)
OnStayStart
Called at the beginning of an update loop
protected void StayStart (int nrOfInsiders)
protected void OnStayStartBeginEvent (int nrOfInsiders)
protected void OnStayStartServerEvent (int nrOfInsiders)
protected void OnStayStartClientEvent (int nrOfInsiders)
protected void OnStayStartEndEvent (int nrOfInsiders)
OnStay
Called in the update loop
protected void Stay (TriggerInsider insider, float deltaTime)
protected void OnStayBeginEvent (TriggerInsider insider, float deltaTime)
protected void OnStayServerEvent (TriggerInsider insider, float deltaTime)
protected void OnStayClientEvent (TriggerInsider insider, float deltaTime)
protected void OnStayEndEvent (TriggerInsider insider, float deltaTime)
OnStayFinish
Called at the end of an update loop
protected void StayFinish ()
protected void OnStayFinishBeginEvent ()
protected void OnStayFinishServerEvent ()
protected void OnStayFinishClientEvent ()
protected void OnStayFinishEndEvent ()
OnLeave
Called when an object leaves the trigger
protected void Leave (TriggerInsider insider)
protected void OnLeaveBeginEvent (TriggerInsider insider)
protected void OnLeaveServerEvent (TriggerInsider insider)
protected void OnLeaveClientEvent (TriggerInsider insider)
protected void OnLeaveEndEvent (TriggerInsider insider)
Detailed Description
Events API for triggers, keep in sync with AreaDamageEvents for consistency NOTE: The deltaTime passed in is the one for the Insider specifically.
Definition at line 3 of file TriggerEvents.c.
Member Function Documentation
Enter()
protected void Enter (TriggerInsider insider) inline private
Definition at line 9 of file TriggerEvents.c.
References GetDebugName(), GetGame(), TriggerInsider::GetObject(), OnEnterBeginEvent(), OnEnterClientEvent(), OnEnterEndEvent(), OnEnterServerEvent(), and Debug::TriggerLog().
Referenced by Trigger::AddInsider().
Leave()
protected void Leave (TriggerInsider insider) inline private
Definition at line 109 of file TriggerEvents.c.
References GetDebugName(), GetGame(), TriggerInsider::GetObject(), OnLeaveBeginEvent(), OnLeaveClientEvent(), OnLeaveEndEvent(), OnLeaveServerEvent(), and Debug::TriggerLog().
Referenced by Trigger::RemoveInsider().
OnEnterBeginEvent()
protected void OnEnterBeginEvent (TriggerInsider insider) inline private
Definition at line 24 of file TriggerEvents.c.
Referenced by Enter().
OnEnterClientEvent()
protected void OnEnterClientEvent (TriggerInsider insider) inline private
Definition at line 26 of file TriggerEvents.c.
Referenced by Enter().
OnEnterEndEvent()
protected void OnEnterEndEvent (TriggerInsider insider) inline private
Definition at line 27 of file TriggerEvents.c.
Referenced by Enter().
OnEnterServerEvent()
protected void OnEnterServerEvent (TriggerInsider insider) inline private
Definition at line 25 of file TriggerEvents.c.
Referenced by Enter().
OnLeaveBeginEvent()
protected void OnLeaveBeginEvent (TriggerInsider insider) inline private
Definition at line 124 of file TriggerEvents.c.
Referenced by Leave().
OnLeaveClientEvent()
protected void OnLeaveClientEvent (TriggerInsider insider) inline private
Definition at line 126 of file TriggerEvents.c.
Referenced by Leave().
OnLeaveEndEvent()
protected void OnLeaveEndEvent (TriggerInsider insider) inline private
Definition at line 127 of file TriggerEvents.c.
Referenced by Leave().
OnLeaveServerEvent()
protected void OnLeaveServerEvent (TriggerInsider insider) inline private
Definition at line 125 of file TriggerEvents.c.
Referenced by Leave().
OnStayBeginEvent()
protected void OnStayBeginEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 74 of file TriggerEvents.c.
Referenced by Stay().
OnStayClientEvent()
protected void OnStayClientEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 76 of file TriggerEvents.c.
Referenced by Stay().
OnStayEndEvent()
protected void OnStayEndEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 77 of file TriggerEvents.c.
Referenced by Stay().
OnStayFinishBeginEvent()
protected void OnStayFinishBeginEvent () inline private
Definition at line 99 of file TriggerEvents.c.
Referenced by StayFinish().
OnStayFinishClientEvent()
protected void OnStayFinishClientEvent () inline private
Definition at line 101 of file TriggerEvents.c.
Referenced by StayFinish().
OnStayFinishEndEvent()
protected void OnStayFinishEndEvent () inline private
Definition at line 102 of file TriggerEvents.c.
Referenced by StayFinish().
OnStayFinishServerEvent()
protected void OnStayFinishServerEvent () inline private
Definition at line 100 of file TriggerEvents.c.
Referenced by StayFinish().
OnStayServerEvent()
protected void OnStayServerEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 75 of file TriggerEvents.c.
Referenced by Stay().
OnStayStartBeginEvent()
protected void OnStayStartBeginEvent (int nrOfInsiders) inline private
Definition at line 49 of file TriggerEvents.c.
Referenced by StayStart().
OnStayStartClientEvent()
protected void OnStayStartClientEvent (int nrOfInsiders) inline private
Definition at line 51 of file TriggerEvents.c.
Referenced by StayStart().
OnStayStartEndEvent()
protected void OnStayStartEndEvent (int nrOfInsiders) inline private
Definition at line 52 of file TriggerEvents.c.
Referenced by StayStart().
OnStayStartServerEvent()
protected void OnStayStartServerEvent (int nrOfInsiders) inline private
Definition at line 50 of file TriggerEvents.c.
Referenced by StayStart().
Stay()
protected void Stay (TriggerInsider insider, float deltaTime) inline private
Definition at line 59 of file TriggerEvents.c.
References GetDebugName(), GetGame(), TriggerInsider::GetObject(), OnStayBeginEvent(), OnStayClientEvent(), OnStayEndEvent(), OnStayServerEvent(), and Debug::TriggerLog().
Referenced by Trigger::UpdateInsiders().
StayFinish()
protected void StayFinish () inline private
Definition at line 84 of file TriggerEvents.c.
References GetDebugName(), GetGame(), OnStayFinishBeginEvent(), OnStayFinishClientEvent(), OnStayFinishEndEvent(), OnStayFinishServerEvent(), and Debug::TriggerLog().
Referenced by Trigger::UpdateInsiders().
StayStart()
protected void StayStart (int nrOfInsiders) inline private
Definition at line 34 of file TriggerEvents.c.
References GetDebugName(), GetGame(), OnStayStartBeginEvent(), OnStayStartClientEvent(), OnStayStartEndEvent(), OnStayStartServerEvent(), and Debug::TriggerLog().
Referenced by Trigger::UpdateInsiders().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ScriptedEntities/Triggers/TriggerEvents.c