DayZ Scripts: PlayerBase Class Reference
PlayerBase Class Reference
Private Member Functions
override void OnGameplayDataHandlerSync ()
Static Private Member Functions
static void CreatePersonalLight ()
Creates PL if it doesn't exist already.
static void SwitchPersonalLight (bool state)
Controls the ON/OFF switch of the Personal Light. PL will still shine only if the server allows it.
static void UpdatePersonalLight ()
Updates state of PL.
static void UpdateHitDirectionValues ()
Static Private Attributes
static ScriptedLightBase m_PersonalLight
static bool m_PersonalLightEnabledOnCurrentServer = false
static bool m_PersonalLightDisabledByDebug = false
static bool m_PersonalLightIsSwitchedOn = true
Detailed Description
Definition at line 1 of file PlayerBaseClient.c.
Member Function Documentation
CreatePersonalLight()
static void CreatePersonalLight () inline static private
Creates PL if it doesn't exist already.
Definition at line 9 of file PlayerBaseClient.c.
References GetGame().
OnGameplayDataHandlerSync()
override void OnGameplayDataHandlerSync () inline private
Definition at line 39 of file PlayerBaseClient.c.
References CfgGameplayHandler::GetDisablePersonalLight().
Referenced by ManBase::OnSelectPlayer().
SwitchPersonalLight()
static void SwitchPersonalLight (bool state) inline static private
Controls the ON/OFF switch of the Personal Light. PL will still shine only if the server allows it.
Definition at line 49 of file PlayerBaseClient.c.
References GetGame().
UpdateHitDirectionValues()
static void UpdateHitDirectionValues () inline static private
Definition at line 76 of file PlayerBaseClient.c.
References HitDirectionEffectBase::CheckValues().
UpdatePersonalLight()
static void UpdatePersonalLight () inline static private
Updates state of PL.
Definition at line 59 of file PlayerBaseClient.c.
References GetCLIParam().
Field Documentation
m_PersonalLight
ScriptedLightBase m_PersonalLight static private
Definition at line 3 of file PlayerBaseClient.c.
m_PersonalLightDisabledByDebug
bool m_PersonalLightDisabledByDebug = false static private
Definition at line 5 of file PlayerBaseClient.c.
m_PersonalLightEnabledOnCurrentServer
bool m_PersonalLightEnabledOnCurrentServer = false static private
Definition at line 4 of file PlayerBaseClient.c.
m_PersonalLightIsSwitchedOn
bool m_PersonalLightIsSwitchedOn = true static private
Definition at line 6 of file PlayerBaseClient.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ManBase/PlayerBaseClient.c