DayZ Scripts: ToolBase Class Reference
ToolBase Class Reference
Private Member Functions
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Cleaver ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void CombatKnife ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Machete ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void FirefighterAxe ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override bool CanPutAsAttachment (EntityAI parent)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override bool CanPutAsAttachment (EntityAI parent)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Machete ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Machete ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Pliers ()
override void SetActions ()
void Screwdriver ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Sickle ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override void SetActions ()
void Sword ()
override bool IsMeleeFinisher ()
override void SetActions ()
override void SetActions ()
Member Function Documentation
CanPutAsAttachment() [1/2]
override bool CanPutAsAttachment (EntityAI parent) inline private
CanPutAsAttachment() [2/2]
override bool CanPutAsAttachment (EntityAI parent) inline private
Cleaver()
void Cleaver () inline private
CombatKnife()
void CombatKnife () inline private
FirefighterAxe()
void FirefighterAxe () inline private
GetValidFinishers() [1/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [2/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [3/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [4/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [5/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [6/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [7/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [8/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [9/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [10/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [11/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [12/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [13/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [14/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [15/16]
override array< int > GetValidFinishers () inline private
GetValidFinishers() [16/16]
override array< int > GetValidFinishers () inline private
IsMeleeFinisher() [1/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [2/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [3/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [4/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [5/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [6/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [7/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [8/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [9/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [10/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [11/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [12/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [13/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [14/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [15/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [16/17]
override bool IsMeleeFinisher () inline private
IsMeleeFinisher() [17/17]
override bool IsMeleeFinisher () inline private
Machete() [1/3]
void Machete () inline private
Machete() [2/3]
void Machete () inline private
Machete() [3/3]
void Machete () inline private
OnWasAttached() [1/2]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
OnWasAttached() [2/2]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
OnWasDetached() [1/2]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
OnWasDetached() [2/2]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Pliers()
void Pliers () inline private
Screwdriver()
void Screwdriver () inline private
SetActions() [1/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [2/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [3/22]
override void SetActions () inline private
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [4/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [5/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [6/22]
override void SetActions () inline private
References ActionMineTree(), ActionSkinning(), and AddAction().
SetActions() [7/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [8/22]
override void SetActions () inline private
References ActionMineTree(), ActionSkinning(), and AddAction().
SetActions() [9/22]
override void SetActions () inline private
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [10/22]
override void SetActions () inline private
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [11/22]
override void SetActions () inline private
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [12/22]
override void SetActions () inline private
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [13/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [14/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [15/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [16/22]
override void SetActions () inline private
References ActionDisarmExplosive(), and AddAction().
SetActions() [17/22]
override void SetActions () inline private
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [18/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [19/22]
override void SetActions () inline private
References ActionDisarmExplosive(), ActionDisarmMine(), ActionSkinning(), and AddAction().
SetActions() [20/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [21/22]
override void SetActions () inline private
References ActionSkinning(), and AddAction().
SetActions() [22/22]
override void SetActions () inline private
References ActionMineTree(), ActionSkinning(), and AddAction().
Sickle()
void Sickle () inline private
Sword()
void Sword () inline private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/BoneKnife.c
P:/scripts/4_World/Entities/ItemBase/Cleaver.c
P:/scripts/4_World/Entities/ItemBase/CombatKnife.c
P:/scripts/4_World/Entities/ItemBase/CrudeMachete.c
P:/scripts/4_World/Entities/ItemBase/FangeKnife.c
P:/scripts/4_World/Entities/ItemBase/FirefighterAxe.c
P:/scripts/4_World/Entities/ItemBase/Hacksaw.c
P:/scripts/4_World/Entities/ItemBase/Hatchet.c
P:/scripts/4_World/Entities/ItemBase/HuntingKnife.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/AK_Bayonet.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/M9A1_Bayonet.c
P:/scripts/4_World/Entities/ItemBase/KitchenKnife.c
P:/scripts/4_World/Entities/ItemBase/KukriKnife.c
P:/scripts/4_World/Entities/ItemBase/Machete.c
P:/scripts/4_World/Entities/ItemBase/OrientalMachete.c
P:/scripts/4_World/Entities/ItemBase/Pliers.c
P:/scripts/4_World/Entities/ItemBase/Screwdriver.c
P:/scripts/4_World/Entities/ItemBase/Sickle.c
P:/scripts/4_World/Entities/ItemBase/SteakKnife.c
P:/scripts/4_World/Entities/ItemBase/StoneKnife.c
P:/scripts/4_World/Entities/ItemBase/Sword.c
P:/scripts/4_World/Entities/ItemBase/WoodAxe.c