DayZ Scripts: HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase > Class Reference
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase > Class Reference
Private Member Functions
void HFSMBase (FSMStateBase ownerState=NULL)
FSMStateBase GetCurrentState ()
FSMStateBase GetOwnerState ()
bool GetHierarchyPath (FSMStateBase state, out array< FSMStateBase > path)
returns hierarchic state (path to root) of a state
void SetInitialState (FSMStateBase initial_state)
void AddTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t)
adds transition into transition table
void Start (FSMEventBase initial_event=NULL, bool useExistingState=false)
starts the state machine by entering the initial_state (using intial_event as argument to initial state's onEntry)
bool IsRunning ()
returns true if machine is in running state
void Terminate (FSMEventBase terminal_event=NULL)
terminates the state machine
void Abort (FSMEventBase abort_event=NULL)
void Update (float dt)
if machine running, call OnUpdate() on current state
protected ProcessEventResult ProcessAbortTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e)
FSMStateBase FindAbortDestinationState (FSMEventBase e)
i
FSMStateBase ProcessAbortEvent (FSMEventBase e, out ProcessEventResult result)
instructs the hierarchical state machine to process the event e
ProcessEventResult ProcessEvent (FSMEventBase e)
instructs the hierarchical state machine to process the event e
protected int FindFirstUnguardedTransition (FSMEventBase e)
FSMStateBase FindTransitionState (FSMStateBase s, FSMEventBase e)
FSMStateBase FindGuardedTransitionState (FSMStateBase s, FSMEventBase e)
protected int FindFirstCompletionTransition ()
protected ProcessEventResult ProcessLocalTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e)
instructs the state machine to process the event locally - no hierarchy is crossed
protected ProcessEventResult LocalTransition (int i, FSMEventBase e)
protected ProcessEventResult ProcessCompletionTransitions ()
Private Attributes
protected ref FSMStateBase m_State
protected FSMStateBase m_OwnerState
current fsm state
protected ref FSMStateBase m_InitialState
state that owns this fsm (or null if root)
protected ref array< ref FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > > m_Transitions = new array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase>>
configurable initial state of the machine
protected bool m_HasCompletions = false
fsm transition table
Detailed Description
Definition at line 19 of file HFSMBase.c.
Constructor & Destructor Documentation
HFSMBase()
void HFSMBase (FSMStateBase ownerState = NULL) inline private
Definition at line 27 of file HFSMBase.c.
Member Function Documentation
Abort()
void Abort (FSMEventBase abort_event = NULL) inline private
Definition at line 117 of file HFSMBase.c.
References fsmDebugPrint(), IsRunning(), m_State, ToString(), and string::ToString().
AddTransition()
AddTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t) inline private
adds transition into transition table
Definition at line 74 of file HFSMBase.c.
References Print().
FindAbortDestinationState()
FindAbortDestinationState (FSMEventBase e) inline private
i
Parameters
[in] e event that will be used to find suitable transition from current state
Returns
FSM_OK if transition found and allowed by guard (if any)
FSM_NO_TRANSITION if no unguarded transition found in submachine or local machine
FSM_TERMINATED state machine has terminated
FSM_ABORTED state machine has aborted
Definition at line 175 of file HFSMBase.c.
References fsmDebugPrint(), m_State, ToString(), float::ToString(), string::ToString(), and Type.
FindFirstCompletionTransition()
protected int FindFirstCompletionTransition () inline private
Definition at line 439 of file HFSMBase.c.
References IsRunning(), and m_State.
FindFirstUnguardedTransition()
protected int FindFirstUnguardedTransition (FSMEventBase e) inline private
Definition at line 381 of file HFSMBase.c.
References m_State.
FindGuardedTransitionState()
FSMStateBase FindGuardedTransitionState (FSMStateBase s, FSMEventBase e) inline private
Definition at line 419 of file HFSMBase.c.
FindTransitionState()
FSMStateBase FindTransitionState (FSMStateBase s, FSMEventBase e) inline private
Definition at line 403 of file HFSMBase.c.
GetCurrentState()
GetCurrentState () inline private
Returns
returns currently active state within this machine (i.e. not hierarchic state)
Definition at line 35 of file HFSMBase.c.
References m_State.
GetHierarchyPath()
GetHierarchyPath (FSMStateBase state, out array< FSMStateBase > path) inline private
returns hierarchic state (path to root) of a state
Parameters
[in] state state the path is starting
[out] path current hierarchic state
Returns
true if current state returned in path argument, false otherwise
Definition at line 52 of file HFSMBase.c.
References path.
GetOwnerState()
GetOwnerState () inline private
Returns
returns state that is owner of this fsm submachine. returns null if this is a root machine.
Definition at line 42 of file HFSMBase.c.
IsRunning()
IsRunning () inline private
returns true if machine is in running state
Definition at line 104 of file HFSMBase.c.
References m_State.
LocalTransition()
protected ProcessEventResult LocalTransition (int i, FSMEventBase e) inline private
Definition at line 509 of file HFSMBase.c.
ProcessAbortEvent()
ProcessAbortEvent (FSMEventBase e, out ProcessEventResult result) inline private
instructs the hierarchical state machine to process the event e
Parameters
[in] e event that will be used to find suitable transition from current state
Returns
FSM_OK if transition found and allowed by guard (if any)
FSM_NO_TRANSITION if no unguarded transition found in submachine or local machine
FSM_TERMINATED state machine has terminated
FSM_ABORTED state machine has aborted
Definition at line 214 of file HFSMBase.c.
References fsmDebugPrint(), m_State, ToString(), float::ToString(), string::ToString(), and Type.
ProcessAbortTransition()
protected ProcessEventResult ProcessAbortTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e) inline private
Definition at line 135 of file HFSMBase.c.
References fsmDebugPrint(), and m_State.
ProcessCompletionTransitions()
protected ProcessEventResult ProcessCompletionTransitions () inline private
Definition at line 516 of file HFSMBase.c.
References Error().
ProcessEvent()
ProcessEvent (FSMEventBase e) inline private
instructs the hierarchical state machine to process the event e
Parameters
[in] e event that will be used to find suitable transition from current state
Returns
FSM_OK if transition found and allowed by guard (if any)
FSM_NO_TRANSITION if no unguarded transition found in submachine or local machine
FSM_TERMINATED state machine has terminated
Definition at line 316 of file HFSMBase.c.
References Error(), fsmDebugPrint(), fsmDebugSpam(), m_State, ToString(), float::ToString(), string::ToString(), and Type.
ProcessLocalTransition()
ProcessLocalTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e) inline private
instructs the state machine to process the event locally - no hierarchy is crossed
Parameters
[in] t the transition in m_Transitions
[in] e event that will be used to process transition from current state
Returns
FSM_OK or FSM_TERMINATED
Definition at line 471 of file HFSMBase.c.
References fsmDebugPrint(), and m_State.
SetInitialState()
SetInitialState (FSMStateBase initial_state) inline private
Parameters
[in] initial_state state the machine will be entered to after Start()
[in] initial_event event that will be used to start the machine
Definition at line 67 of file HFSMBase.c.
Start()
Start (FSMEventBase initial_event = NULL, bool useExistingState = false) inline private
starts the state machine by entering the initial_state (using intial_event as argument to initial state's onEntry)
Parameters
[in] e optional event for starting the machind
Definition at line 89 of file HFSMBase.c.
References fsmDebugPrint(), m_State, ToString(), and string::ToString().
Terminate()
Terminate (FSMEventBase terminal_event = NULL) inline private
terminates the state machine
Definition at line 108 of file HFSMBase.c.
References fsmDebugPrint(), IsRunning(), m_State, ToString(), and string::ToString().
Update()
Update (float dt) inline private
if machine running, call OnUpdate() on current state
Definition at line 129 of file HFSMBase.c.
References IsRunning(), and m_State.
Field Documentation
m_HasCompletions
protected bool m_HasCompletions = false private
fsm transition table
Definition at line 25 of file HFSMBase.c.
m_InitialState
protected ref FSMStateBase m_InitialState private
state that owns this fsm (or null if root)
Definition at line 23 of file HFSMBase.c.
m_OwnerState
protected FSMStateBase m_OwnerState private
current fsm state
Definition at line 22 of file HFSMBase.c.
m_State
protected ref FSMStateBase m_State private
Definition at line 21 of file HFSMBase.c.
m_Transitions
protected ref array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> > m_Transitions = new array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase>> private
configurable initial state of the machine
Definition at line 24 of file HFSMBase.c.
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/HFSMBase.c