DayZ Scripts: ClientKickedModule Class Reference
ClientKickedModule Class Reference
Private Member Functions
void ClientKickedModule ()
override void InitOptionalVariables ()
override void FillErrorDataMap ()
Constructor & Destructor Documentation
ClientKickedModule()
void ClientKickedModule () inline private
Member Function Documentation
FillErrorDataMap()
override void FillErrorDataMap () inline private
References AUTH_PREFIX, CLIENT_MUST_UPDATE, InsertDialogueErrorProperties(), InsertErrorProperties(), InsertExtendedPrefixDialogueErrorProperties(), InsertExtendedPrefixSplitDialogueErrorProperties(), InsertPrefixDialogueErrorProperties(), InsertSplitDialogueErrorProperties(), LOGIN_PREFIX, MODS, RESPAWN_PREFIX, SERVER_MUST_UPDATE, UNM_MESSAGE, VE_PREFIX, and VERIFY.
InitOptionalVariables()
override void InitOptionalVariables () inline private
References m_Header, and m_Prefix.
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Global/ErrorModuleHandler/ClientKickedModule.c