DayZ Scripts: UnboxLambda Class Reference
UnboxLambda Class Reference
Private Member Functions
void UnboxLambda (EntityAI old_item, string new_item_type, PlayerBase player, int count)
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
override void OnSuccess (EntityAI new_item)
Private Attributes
int m_ItemCount
Detailed Description
Definition at line 72 of file ActionUnpackBox.c.
Constructor & Destructor Documentation
UnboxLambda()
void UnboxLambda (EntityAI old_item, string new_item_type, PlayerBase player, int count) inline private
Definition at line 75 of file ActionUnpackBox.c.
References m_ItemCount.
Member Function Documentation
CopyOldPropertiesToNew()
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item) inline private
Definition at line 77 of file ActionUnpackBox.c.
References Class::CastTo(), GetGame(), m_ItemCount, ReplaceItemWithNewLambdaBase::m_NewItemType, and Print().
OnSuccess()
override void OnSuccess (EntityAI new_item) inline private
Definition at line 97 of file ActionUnpackBox.c.
References ECE_PLACE_ON_SURFACE, and GetGame().
Field Documentation
m_ItemCount
int m_ItemCount private
Definition at line 74 of file ActionUnpackBox.c.
Referenced by CopyOldPropertiesToNew(), and UnboxLambda().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionUnpackBox.c