DayZ Scripts: P:/scripts/3_Game/tools/LogTemplates.c File Reference
LogTemplates.c File Reference
Data Structures
class LogTemplates
Typedefs
typedef Param3< string, string, string > LogTemplate
typedef int LogTemplateID
Functions
class LogTemplates Log (string message, LogTemplateID template_id=0)
Creates debug log (optional) from LogTemplate which are registred.
static private void RegisterLogTamplate (LogTemplateID template_id, string author, string plugin, string label)
static void Init ()
static LogTemplate GetTemplate (LogTemplateID template_id)
void LogInfo (string message, LogTemplateID template_id=0)
Creates info log (optional) from LogTemplate which are registred.
void LogWarning (string message, LogTemplateID template_id=0)
Creates warning log (optional) from LogTemplate which are registred.
void LogError (string message, LogTemplateID template_id=0)
Creates error log (optional) from LogTemplate which are registred.
void SQFPrint (string sqf_msg)
void SQFLog (string sqf_msg)
Variables
static private ref map< LogTemplateID, ref LogTemplate > m_LogTemplates
static LogTemplateID TEMPLATE_UNKNOWN = 0
static LogTemplateID TEMPLATE_JANOSIK = 1
static LogTemplateID TEMPLATE_PLAYER_WEIGHT = 2
static LogTemplateID TEMPLATE_BROADCAST = 3
Typedef Documentation
LogTemplate
typedef Param3<string, string, string> LogTemplate
LogTemplateID
typedef int LogTemplateID
Function Documentation
GetTemplate()
static LogTemplate GetTemplate (LogTemplateID template_id) static
Init()
static void Init () static
Log()
class LogTemplates Log (string message, LogTemplateID template_id = 0)
Creates debug log (optional) from LogTemplate which are registred.
Parameters
template_id LogTemplateID ID of LogTemplate which was registred in proto/Logtemplate.h -> "class LogTemplates"
message string Debug message for log
Returns
void
Log("This is some debug log message", TEMPLATE_JINDRICH);
>> output to scriptExt.log (for GamutLogViewer)
Referenced by Debug(), UIPopupScript::OnClick(), PluginFileHandler::SaveParameter(), and SQFLog().
LogError()
void LogError (string message, LogTemplateID template_id = 0)
Creates error log (optional) from LogTemplate which are registred.
Parameters
template_id LogTemplateID ID of LogTemplate which was registred in proto/Logtemplate.h -> "class LogTemplates"
message string Error message for log
Returns
void
LogT(TEMPLATE_JINDRICH, "This is some error log message");
>> output to scriptExt.log (for GamutLogViewer)
References LogTemplates::GetTemplate(), and Debug::LogError().
Referenced by GameInventory::OnServerInventoryCommandStatic().
LogInfo()
void LogInfo (string message, LogTemplateID template_id = 0)
Creates info log (optional) from LogTemplate which are registred.
Parameters
template_id LogTemplateID ID of LogTemplate which was registred in proto/Logtemplate.h -> "class LogTemplates"
message string Info message for log
Returns
void
LogInfo("This is some info log message", TEMPLATE_JINDRICH);
>> output to scriptExt.log (for GamutLogViewer)
References LogTemplates::GetTemplate(), and Debug::LogInfo().
LogWarning()
void LogWarning (string message, LogTemplateID template_id = 0)
Creates warning log (optional) from LogTemplate which are registred.
Parameters
template_id LogTemplateID ID of LogTemplate which was registred in proto/Logtemplate.h -> "class LogTemplates"
message string Warning message for log
Returns
void
LogT(TEMPLATE_JINDRICH, "This is some warning log message");
>> output to scriptExt.log (for GamutLogViewer)
References LogTemplates::GetTemplate(), and Debug::LogWarning().
RegisterLogTamplate()
static private void RegisterLogTamplate (LogTemplateID template_id, string author, string plugin, string label) static
SQFLog()
void SQFLog (string sqf_msg)
References Log().
SQFPrint()
void SQFPrint (string sqf_msg)
References Print().
Variable Documentation
m_LogTemplates
private ref map<LogTemplateID, ref LogTemplate> m_LogTemplates static
TEMPLATE_BROADCAST
LogTemplateID TEMPLATE_BROADCAST = 3 static
TEMPLATE_JANOSIK
LogTemplateID TEMPLATE_JANOSIK = 1 static
TEMPLATE_PLAYER_WEIGHT
LogTemplateID TEMPLATE_PLAYER_WEIGHT = 2 static
TEMPLATE_UNKNOWN
LogTemplateID TEMPLATE_UNKNOWN = 0 static