DayZ Scripts: ScriptConsoleToolTipEventHandler Class Reference
ScriptConsoleToolTipEventHandler Class Reference
Private Member Functions
void OnWidgetScriptInit (Widget w)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
protected bool Tick ()
protected void DisplayHint (string message)
protected void HideHint ()
protected string GetMessage ()
protected void HoverSuccess ()
protected void HoverInterrupt ()
Private Attributes
reference string HintMessage
protected Widget m_Root
protected float m_HoverTime
protected bool m_HoverSuccessTriggered
protected Widget m_CurrentHoverWidget
protected Widget m_HintWidgetRoot
protected ImageWidget m_HintWidgetBackground
protected RichTextWidget m_HintWidget
protected ref Timer m_Timer
Member Function Documentation
DisplayHint()
protected void DisplayHint (string message) inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), GetMousePos(), GetScreenSize(), CGame::GetWorkspace(), m_HintWidget, m_HintWidgetBackground, and m_HintWidgetRoot.
Referenced by HoverSuccess().
GetMessage()
protected string GetMessage () inline private
References HintMessage.
Referenced by HoverSuccess().
HideHint()
protected void HideHint () inline private
References m_HintWidgetRoot.
Referenced by HoverInterrupt().
HoverInterrupt()
protected void HoverInterrupt () inline private
References HideHint(), m_CurrentHoverWidget, m_HoverSuccessTriggered, m_HoverTime, and m_Timer.
Referenced by OnMouseLeave(), and Tick().
HoverSuccess()
protected void HoverSuccess () inline private
References DisplayHint(), GetMessage(), and m_HoverSuccessTriggered.
Referenced by Tick().
OnMouseEnter()
override bool OnMouseEnter (Widget w, int x, int y) inline private
References m_CurrentHoverWidget, and m_Timer.
OnMouseLeave()
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
References HoverInterrupt().
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w) inline private
References m_Root.
Tick()
protected bool Tick () inline private
References HoverInterrupt(), HoverSuccess(), m_CurrentHoverWidget, m_HoverSuccessTriggered, m_HoverTime, and m_Root.
Field Documentation
HintMessage
reference string HintMessage private
Referenced by GetMessage().
m_CurrentHoverWidget
protected Widget m_CurrentHoverWidget private
Referenced by HoverInterrupt(), OnMouseEnter(), and Tick().
m_HintWidget
protected RichTextWidget m_HintWidget private
Referenced by DisplayHint().
m_HintWidgetBackground
protected ImageWidget m_HintWidgetBackground private
Referenced by DisplayHint().
m_HintWidgetRoot
protected Widget m_HintWidgetRoot private
Referenced by DisplayHint(), and HideHint().
m_HoverSuccessTriggered
protected bool m_HoverSuccessTriggered private
Referenced by HoverInterrupt(), HoverSuccess(), and Tick().
m_HoverTime
protected float m_HoverTime private
Referenced by HoverInterrupt(), and Tick().
m_Root
protected Widget m_Root private
Referenced by OnWidgetScriptInit(), and Tick().
m_Timer
protected ref Timer m_Timer private
Referenced by HoverInterrupt(), and OnMouseEnter().
The documentation for this class was generated from the following file:
5_Mission/GUI/ScriptConsole.c