DayZ Scripts: ServerBrowserHelperFunctions Class Reference
ServerBrowserHelperFunctions Class Reference
Private Member Functions
void ServerBrowserHelperFunctions ()
Static Private Member Functions
static void AddMapInfo (string mapName, string mapDisplayName)
static string GetInternalMapName (string mapName)
static string GetMapDisplayName (string mapName)
static string GetServerMapImagePath (string mapName)
static ServerBrowserHelperFunctions GetInstance ()
Static Private Attributes
static ref ServerBrowserHelperFunctions s_ServerBrowserHelperFunctions
static protected const string CHERNARUS_MAP_IMAGE = ""
static protected const string LIVONIA_MAP_IMAGE = ""
static protected const string SAKHAL_MAP_IMAGE = ""
static protected const string LOWERCASE_ALPHABET = "abcdefghijklmnopqrstuvwxyz"
static ref map< string, string > INTERNAL_MAP_NAMES = new map<string, string>
Constructor & Destructor Documentation
ServerBrowserHelperFunctions()
void ServerBrowserHelperFunctions () inline private
References INTERNAL_MAP_NAMES.
Referenced by GetInstance().
Member Function Documentation
AddMapInfo()
static void AddMapInfo (string mapName, string mapDisplayName) inline static private
References INTERNAL_MAP_NAMES.
GetInstance()
static ServerBrowserHelperFunctions GetInstance () inline static private
References s_ServerBrowserHelperFunctions, and ServerBrowserHelperFunctions().
Referenced by ScriptedWidgetEventHandler::LoadMapFilterOptions().
GetInternalMapName()
static string GetInternalMapName (string mapName) inline static private
References INTERNAL_MAP_NAMES.
Referenced by ScriptedWidgetEventHandler::GetFilterOptionsConsoles(), and ScriptedWidgetEventHandler::GetFilterOptionsPC().
GetMapDisplayName()
static string GetMapDisplayName (string mapName) inline static private
References string::IndexOf(), INTERNAL_MAP_NAMES, LOWERCASE_ALPHABET, string::ToLower(), and string::ToUpper().
Referenced by GetServersResultRow::GetValueStr(), and ScriptedWidgetEventHandler::SetServerMapName().
GetServerMapImagePath()
static string GetServerMapImagePath (string mapName) inline static private
References CHERNARUS_MAP_IMAGE, LIVONIA_MAP_IMAGE, SAKHAL_MAP_IMAGE, and string::ToLower().
Referenced by ScriptedWidgetEventHandler::SetServerMap().
Field Documentation
CHERNARUS_MAP_IMAGE
protected const string CHERNARUS_MAP_IMAGE = "" static private
Referenced by GetServerMapImagePath().
INTERNAL_MAP_NAMES
ref map<string, string> INTERNAL_MAP_NAMES = new map<string, string> static private
Referenced by AddMapInfo(), GetInternalMapName(), GetMapDisplayName(), ScriptedWidgetEventHandler::LoadMapFilterOptions(), and ServerBrowserHelperFunctions().
LIVONIA_MAP_IMAGE
protected const string LIVONIA_MAP_IMAGE = "" static private
Referenced by GetServerMapImagePath().
LOWERCASE_ALPHABET
protected const string LOWERCASE_ALPHABET = "abcdefghijklmnopqrstuvwxyz" static private
Referenced by GetMapDisplayName().
s_ServerBrowserHelperFunctions
ref ServerBrowserHelperFunctions s_ServerBrowserHelperFunctions static private
Referenced by GetInstance().
SAKHAL_MAP_IMAGE
protected const string SAKHAL_MAP_IMAGE = "" static private
Referenced by GetServerMapImagePath().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Services/BiosLobbyService.c