DayZ Scripts: ScriptConsoleItemsTab Class Reference
ScriptConsoleItemsTab Class Reference
Private Member Functions
void ScriptConsoleItemsTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void ~ScriptConsoleItemsTab ()
protected void Init ()
override bool OnKeyDown (Widget w, int x, int y, int key)
void SelectObject (bool hide_presets=true)
void SelectPreset ()
int GetCurrentPresetIndex ()
int GetCurrentItemIndex ()
bool IsCurrentPresetFixed ()
bool IsPresetFixed (string preset_name)
int GetPresetIndexByName (string preset_name)
void ShowItemButtons ()
void HideItemButtons ()
void ShowItemTransferButtons ()
void ItemMoveUp ()
void ItemMoveDown ()
void SaveProfileSpawnDistance ()
void RenamePreset (string new_preset_name)
void SpawnPreset (EntityAI target, bool clear_inventory, string preset_name, InventoryLocationType location=InventoryLocationType.ATTACHMENT, float distance=0)
void SetDefaultPreset (int preset_index)
void SetObject (string object)
void SetPreviewObject (string object)
void AddItemToPreset ()
void ShowPresetButtons ()
void RemoveItemFromPreset ()
string GetCurrentPresetName ()
string GetCurrentItemName ()
string GetCurrentObjectName ()
void RefreshLists ()
void RenderPresets ()
void RenderPresetItems ()
void NewPreset (string preset_name)
void DeletePreset ()
int GetFilterColor (string color)
void PrepareFilters (string filter, out TStringArray filters, out TIntArray colors)
void ChangeFilter (TStringArray classes, TextListboxWidget widget, MultilineEditBoxWidget filterWidget, int categoryMask=-1, bool ignoreScope=false)
void SetFilterOrder (bool reversed)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override void Update (float timeslice)
void SetTextSpawnButton (ButtonWidget w, bool special, string suffix=" Special")
void UpdateButtonNames ()
TStringArray GetItemsClasses ()
protected string PreprocessFilterText (MultilineEditBoxWidget w)
void ChangeFilterItems (bool forced=false)
private bool ListItemRelatedActions ()
Static Private Member Functions
static void DrawItems (string type, float distance=0)
static void DrawItemsClear ()
static string GetLastSelectedObject ()
Private Attributes
protected const string CONST_DEFAULT_PRESET_PREFIX = "[Default]"
protected ref array< Widget > m_CategoryButtonsWidgets = new array<Widget>
protected ref array< string > m_CategoryButtonsNames = {"FIREARMS","MELEE","ATTACHMENTS","MAGAZINES","AMMO","FOOD","MEDICAL","CARS","BACKPACKS","B-BUILDING"}
protected ref map< Widget, string > m_SpawnButtonsOriginalText = new map<Widget, string>()
protected int m_CategoryMask
protected MissionGameplay m_MissionGameplay
protected ref Timer m_RefreshFilterTimer = new Timer()
protected PluginDeveloper m_Developer
protected bool m_FilterOrderReversed
protected string m_SelectedObject
protected string m_FilterTextPrev
protected CheckBoxWidget m_CategoryMergeType
protected CheckBoxWidget m_ItemPreviewCheckbox
protected CheckBoxWidget m_ShowProtected
protected CheckBoxWidget m_ClearInventory
protected TextListboxWidget m_ObjectsTextListbox
protected TextListboxWidget m_PresetsTextListbox
protected TextListboxWidget m_PresetItemsTextListbox
protected ButtonWidget m_DrawInWorld
protected ButtonWidget m_DrawInWorldClear
protected ButtonWidget m_PresetNewButton
protected ButtonWidget m_PresetDeleteButton
protected ButtonWidget m_PresetRenameButton
protected ButtonWidget m_PresetSetDefaultButton
protected ButtonWidget m_PresetAddItemtButton
protected ButtonWidget m_ItemNameCopy
protected ButtonWidget m_PresetRemoveItemButton
protected ButtonWidget m_ItemMoveUpButton
protected ButtonWidget m_ItemMoveDownButton
protected ButtonWidget m_FilterOrderButton
protected ButtonWidget m_SpawnInInvButton
protected ButtonWidget m_SpawnGroundButton
protected ButtonWidget m_SpawnGroundPatternGrid
protected ButtonWidget m_SpawnOnTarget
protected ButtonWidget m_SpawnOnCursor
protected ButtonWidget m_SpawnInHands
protected ButtonWidget m_SpawnBatchButton
protected ButtonWidget m_ListActions
protected MultilineEditBoxWidget m_ObjectFilter
protected EditBoxWidget m_SpawnDistanceEditBox
protected EditBoxWidget m_RectSpawnRow
protected EditBoxWidget m_RectSpawnColumn
protected EditBoxWidget m_RectSpawnRowStep
protected EditBoxWidget m_RectSpawnColumnStep
protected EditBoxWidget m_DrawDistanceWidget
protected EditBoxWidget m_QuantityEditBox
protected EditBoxWidget m_DamageEditBox
protected EditBoxWidget m_BatchSpawnQuantity
protected CheckBoxWidget m_WithPhysicsCheckbox
protected ButtonWidget m_ReloadShapeButton
protected TextWidget m_ItemDamageLabel
protected TextWidget m_ItemQuantityLabel
protected TextWidget m_SelectedObjectText
protected TextWidget m_SelectedObjectLocalized
protected ItemPreviewWidget m_ItemPreviewWidget
protected ImageWidget m_FilterOrderImage
Static Private Attributes
static protected int ITEMS_SELECTED_ROW = -1
static protected int PRESETS_SELECTED_ROW = 0
static protected int ITEMS_IN_PRESET_SELECTED_ROW
static protected float DRAW_DISTANCE = 1000
static protected bool CLEAR_IVN
static protected int m_ObjectsScope = 2
static protected string m_LastSelectedObject
static protected int m_SelectedObjectIsPreset = -1
static protected ref array< Shape > m_DebugShapes = new array<Shape>
static protected EntityAI m_PreviewEntity
static protected float m_ItemQuantity = 1
static protected bool m_WithPhysics = false
Constructor & Destructor Documentation
ScriptConsoleItemsTab()
void ScriptConsoleItemsTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline private
References GetPlugin(), Init(), m_BatchSpawnQuantity, m_CategoryMergeType, m_ClearInventory, m_DamageEditBox, m_Developer, m_DrawDistanceWidget, m_DrawInWorld, m_DrawInWorldClear, m_FilterOrderButton, m_FilterOrderImage, m_ItemDamageLabel, m_ItemMoveDownButton, m_ItemMoveUpButton, m_ItemNameCopy, m_ItemPreviewCheckbox, m_ItemPreviewWidget, m_ItemQuantityLabel, m_ListActions, m_ObjectFilter, m_ObjectsTextListbox, m_PresetAddItemtButton, m_PresetDeleteButton, m_PresetItemsTextListbox, m_PresetNewButton, m_PresetRemoveItemButton, m_PresetRenameButton, m_PresetSetDefaultButton, m_PresetsTextListbox, m_QuantityEditBox, m_RectSpawnColumn, m_RectSpawnColumnStep, m_RectSpawnRow, m_RectSpawnRowStep, m_ReloadShapeButton, m_SelectedObjectLocalized, m_SelectedObjectText, m_ShowProtected, m_SpawnBatchButton, m_SpawnButtonsOriginalText, m_SpawnDistanceEditBox, m_SpawnGroundButton, m_SpawnInHands, m_SpawnInInvButton, m_SpawnOnCursor, m_SpawnOnTarget, and m_WithPhysicsCheckbox.
~ScriptConsoleItemsTab()
void ~ScriptConsoleItemsTab () inline private
References ITEMS_IN_PRESET_SELECTED_ROW, ITEMS_SELECTED_ROW, m_CategoryMask, ScriptConsoleTabBase::m_ConfigDebugProfile, m_ItemQuantity, m_ObjectsTextListbox, m_PresetItemsTextListbox, m_PresetsTextListbox, m_PreviewEntity, m_QuantityEditBox, m_RefreshFilterTimer, m_WithPhysics, m_WithPhysicsCheckbox, PRESETS_SELECTED_ROW, and Timer::Stop().
Member Function Documentation
AddItemToPreset()
void AddItemToPreset () inline private
References GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_ObjectsTextListbox, and RenderPresetItems().
Referenced by OnClick().
ChangeFilter()
void ChangeFilter (TStringArray classes, TextListboxWidget widget, MultilineEditBoxWidget filterWidget, int categoryMask = -1, bool ignoreScope = false) inline private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), string::Contains(), GetGame(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_FilterOrderReversed, m_ObjectsScope, PrepareFilters(), and string::ToLower().
Referenced by ChangeFilterItems().
ChangeFilterItems()
void ChangeFilterItems (bool forced = false) inline private
References ChangeFilter(), GetItemsClasses(), m_CategoryMask, ScriptConsoleTabBase::m_ConfigDebugProfile, m_FilterTextPrev, m_ObjectFilter, m_ObjectsTextListbox, and PreprocessFilterText().
Referenced by Init(), OnChange(), OnClick(), and SetFilterOrder().
DeletePreset()
void DeletePreset () inline private
References GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, and RefreshLists().
Referenced by OnClick().
DrawItems()
static void DrawItems (string type, float distance = 0) inline static private
need better logic for cleaning
References COLOR_RED, DRAW_DISTANCE, GetGame(), CGame::GetObjectsAtPosition(), GetPlayer(), GetPosition, Debug::Log(), m_DebugShapes, and Shape.
Referenced by OnClick(), and OnKeyDown().
DrawItemsClear()
static void DrawItemsClear () inline static private
References m_DebugShapes, and Shape.
Referenced by OnClick().
GetCurrentItemIndex()
int GetCurrentItemIndex () inline private
References m_PresetItemsTextListbox.
Referenced by GetCurrentItemName(), ItemMoveDown(), ItemMoveUp(), OnChange(), RemoveItemFromPreset(), ShowItemButtons(), and ShowItemTransferButtons().
GetCurrentItemName()
string GetCurrentItemName () inline private
References GetCurrentItemIndex(), and m_PresetItemsTextListbox.
Referenced by Init(), OnClick(), and OnItemSelected().
GetCurrentObjectName()
string GetCurrentObjectName () inline private
References m_ObjectsTextListbox.
Referenced by Init(), OnDoubleClick(), and SelectObject().
GetCurrentPresetIndex()
int GetCurrentPresetIndex () inline private
References m_PresetsTextListbox.
Referenced by AddItemToPreset(), DeletePreset(), GetCurrentPresetName(), IsCurrentPresetFixed(), ItemMoveDown(), ItemMoveUp(), OnClick(), RemoveItemFromPreset(), RenamePreset(), RenderPresetItems(), SetDefaultPreset(), ShowItemTransferButtons(), and SpawnPreset().
GetCurrentPresetName()
string GetCurrentPresetName () inline private
References GetCurrentPresetIndex(), and m_PresetsTextListbox.
Referenced by AddItemToPreset(), DeletePreset(), UIScriptedMenu::Init(), ItemMoveDown(), ItemMoveUp(), OnChange(), OnClick(), RemoveItemFromPreset(), RenamePreset(), RenderPresetItems(), SelectPreset(), SetDefaultPreset(), and ShowItemButtons().
GetFilterColor()
int GetFilterColor (string color) inline private
References ARGB().
Referenced by PrepareFilters().
GetItemsClasses()
TStringArray GetItemsClasses () inline private
References CFG_AMMO, CFG_MAGAZINESPATH, CFG_VEHICLESPATH, and CFG_WEAPONSPATH.
Referenced by ChangeFilterItems().
GetLastSelectedObject()
static string GetLastSelectedObject () inline static private
References m_LastSelectedObject.
Referenced by Dispatcher::CallMethod().
GetPresetIndexByName()
int GetPresetIndexByName (string preset_name) inline private
References m_PresetsTextListbox.
Referenced by IsPresetFixed(), RenderPresets(), and SetDefaultPreset().
HideItemButtons()
void HideItemButtons () inline private
References m_ItemMoveDownButton, and m_ItemMoveUpButton.
Referenced by Init(), OnDoubleClick(), SelectObject(), and ShowPresetButtons().
Init()
protected void Init () inline private
References ARGB(), ChangeFilterItems(), DRAW_DISTANCE, GetCurrentItemName(), GetCurrentObjectName(), GetGame(), HideItemButtons(), ITEMS_IN_PRESET_SELECTED_ROW, ITEMS_SELECTED_ROW, m_BatchSpawnQuantity, m_CategoryButtonsNames, m_CategoryButtonsWidgets, m_CategoryMask, m_CategoryMergeType, ScriptConsoleTabBase::m_ConfigDebugProfile, m_DrawDistanceWidget, m_ItemPreviewCheckbox, m_ItemQuantity, m_LastSelectedObject, m_MissionGameplay, m_ObjectFilter, m_ObjectsScope, m_ObjectsTextListbox, ScriptConsoleTabBase::m_ParentRoot, m_PresetDeleteButton, m_PresetItemsTextListbox, m_PresetRenameButton, m_PresetsTextListbox, m_QuantityEditBox, m_RectSpawnColumn, m_RectSpawnColumnStep, m_RectSpawnRow, m_RectSpawnRowStep, m_RefreshFilterTimer, m_SelectedObject, m_SelectedObjectIsPreset, m_SelectedObjectText, m_ShowProtected, m_SpawnDistanceEditBox, m_WithPhysics, m_WithPhysicsCheckbox, name, PRESETS_SELECTED_ROW, RenderPresetItems(), RenderPresets(), SelectPreset(), SetFilterOrder(), SetObject(), ShowItemTransferButtons(), and float::ToString().
Referenced by ScriptConsoleItemsTab().
IsCurrentPresetFixed()
bool IsCurrentPresetFixed () inline private
References GetCurrentPresetIndex(), and m_PresetsTextListbox.
Referenced by RenderPresetItems(), ShowItemButtons(), ShowItemTransferButtons(), ShowPresetButtons(), and SpawnPreset().
IsPresetFixed()
bool IsPresetFixed (string preset_name) inline private
References GetPresetIndexByName(), and m_PresetsTextListbox.
Referenced by RenderPresets(), SelectPreset(), and SetDefaultPreset().
ItemMoveDown()
void ItemMoveDown () inline private
References GetCurrentItemIndex(), GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_PresetItemsTextListbox, and RenderPresetItems().
Referenced by OnClick().
ItemMoveUp()
void ItemMoveUp () inline private
References GetCurrentItemIndex(), GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_PresetItemsTextListbox, and RenderPresetItems().
Referenced by OnClick().
ListItemRelatedActions()
private bool ListItemRelatedActions () inline private
References ContinuousDefaultActionInput(), string::Format(), g_Game, EntityAI::GetActions(), GetPlugin(), ActionBase::GetText(), m_PreviewEntity, ScriptConsoleTabBase::m_ScriptConsole, and MENU_SCRIPTCONSOLE_UNIVERSAL_INFO_DIALOG.
Referenced by OnClick().
NewPreset()
void NewPreset (string preset_name) inline private
References ScriptConsoleTabBase::m_ConfigDebugProfile, and RefreshLists().
Referenced by UIScriptedMenu::OnClick().
OnChange()
override bool OnChange (Widget w, int x, int y, bool finished) inline private
References ARGB(), ChangeFilterItems(), CLEAR_IVN, DRAW_DISTANCE, GetCurrentItemIndex(), GetCurrentPresetName(), m_BatchSpawnQuantity, m_CategoryButtonsWidgets, m_CategoryMask, m_ClearInventory, ScriptConsoleTabBase::m_ConfigDebugProfile, m_DamageEditBox, m_DrawDistanceWidget, m_ObjectsScope, m_QuantityEditBox, m_RectSpawnColumn, m_RectSpawnColumnStep, m_RectSpawnRow, m_RectSpawnRowStep, m_ShowProtected, m_WithPhysicsCheckbox, Math::Pow(), x, and y.
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References ScriptConsoleTabBase::AddItemToClipboard(), AddItemToPreset(), ChangeFilterItems(), CLEAR_IVN, DeletePreset(), DrawItems(), DrawItemsClear(), g_Game, CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetCurrentItemName(), GetCurrentPresetIndex(), GetCurrentPresetName(), GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), DeveloperFreeCamera::IsFreeCameraEnabled(), ItemMoveDown(), ItemMoveUp(), ListItemRelatedActions(), m_BatchSpawnQuantity, m_CategoryMergeType, ScriptConsoleTabBase::m_ConfigDebugProfile, m_DamageEditBox, m_Developer, m_DrawInWorld, m_DrawInWorldClear, m_FilterOrderButton, m_FilterOrderReversed, ScriptConsoleTabBase::m_IsShiftDown, m_ItemMoveDownButton, m_ItemMoveUpButton, m_ItemNameCopy, m_ItemPreviewCheckbox, m_ItemPreviewWidget, m_ListActions, m_MissionGameplay, m_ObjectFilter, m_ObjectsTextListbox, m_PresetAddItemtButton, m_PresetDeleteButton, m_PresetItemsTextListbox, m_PresetNewButton, m_PresetRemoveItemButton, m_PresetRenameButton, m_PresetSetDefaultButton, m_PresetsTextListbox, m_PreviewEntity, m_QuantityEditBox, m_RectSpawnColumn, m_RectSpawnColumnStep, m_RectSpawnRow, m_RectSpawnRowStep, m_ReloadShapeButton, ScriptConsoleTabBase::m_ScriptConsole, m_SelectedObject, m_SelectedObjectIsPreset, m_SelectedObjectText, m_SpawnBatchButton, m_SpawnDistanceEditBox, m_SpawnGroundButton, m_SpawnGroundPatternGrid, m_SpawnInHands, m_SpawnInInvButton, m_SpawnOnCursor, m_SpawnOnTarget, m_WithPhysicsCheckbox, MENU_SCRIPTCONSOLE_DIALOG_PRESET_NAME, MENU_SCRIPTCONSOLE_DIALOG_PRESET_RENAME, DayZPhysics::RaycastRV(), RemoveItemFromPreset(), SaveProfileSpawnDistance(), SelectObject(), SelectPreset(), SetDefaultPreset(), SetFilterOrder(), ItemPreviewWidget::SetItem(), SetObject(), ShowItemButtons(), ShowItemTransferButtons(), SpawnPreset(), x, and y.
OnDoubleClick()
override bool OnDoubleClick (Widget w, int x, int y, int button) inline private
References CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetCurrentObjectName(), GetGame(), GetPlayer(), HideItemButtons(), m_Developer, m_LastSelectedObject, m_ObjectsTextListbox, m_PresetItemsTextListbox, m_QuantityEditBox, m_SelectedObject, m_SelectedObjectIsPreset, m_SelectedObjectText, m_SpawnDistanceEditBox, DayZPhysics::RaycastRV(), SaveProfileSpawnDistance(), ShowItemTransferButtons(), x, and y.
OnItemSelected()
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
References GetCurrentItemName(), m_ObjectsTextListbox, m_PresetItemsTextListbox, m_PresetsTextListbox, m_SelectedObjectIsPreset, m_SelectedObjectText, SelectObject(), SelectPreset(), SetObject(), ShowItemButtons(), ShowItemTransferButtons(), x, and y.
OnKeyDown()
override bool OnKeyDown (Widget w, int x, int y, int key) inline private
References DrawItems(), m_SelectedObject, x, and y.
PrepareFilters()
void PrepareFilters (string filter, out TStringArray filters, out TIntArray colors) inline private
References ARGB(), GetFilterColor(), string::Split(), string::ToLower(), and string::Trim().
Referenced by ChangeFilter().
PreprocessFilterText()
protected string PreprocessFilterText (MultilineEditBoxWidget w) inline private
References string::Contains(), and string::Replace().
Referenced by ChangeFilterItems().
RefreshLists()
void RefreshLists () inline private
References RenderPresetItems(), and RenderPresets().
Referenced by DeletePreset(), NewPreset(), and RenamePreset().
RemoveItemFromPreset()
void RemoveItemFromPreset () inline private
References GetCurrentItemIndex(), GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, and RenderPresetItems().
Referenced by OnClick().
RenamePreset()
void RenamePreset (string new_preset_name) inline private
References GetCurrentPresetIndex(), GetCurrentPresetName(), ScriptConsoleTabBase::m_ConfigDebugProfile, and RefreshLists().
Referenced by UIScriptedMenu::OnClick().
RenderPresetItems()
void RenderPresetItems () inline private
References GetCurrentPresetIndex(), GetCurrentPresetName(), IsCurrentPresetFixed(), ScriptConsoleTabBase::m_ConfigDebugProfile, ScriptConsoleTabBase::m_ConfigDebugProfileFixed, and m_PresetItemsTextListbox.
Referenced by AddItemToPreset(), Init(), ItemMoveDown(), ItemMoveUp(), RefreshLists(), RemoveItemFromPreset(), and SelectPreset().
RenderPresets()
void RenderPresets () inline private
References CONST_DEFAULT_PRESET_PREFIX, GetPresetIndexByName(), IsPresetFixed(), ScriptConsoleTabBase::m_ConfigDebugProfile, ScriptConsoleTabBase::m_ConfigDebugProfileFixed, and m_PresetsTextListbox.
Referenced by Init(), and RefreshLists().
SaveProfileSpawnDistance()
void SaveProfileSpawnDistance () inline private
References ScriptConsoleTabBase::m_ConfigDebugProfile, and m_SpawnDistanceEditBox.
Referenced by OnClick(), and OnDoubleClick().
SelectObject()
void SelectObject (bool hide_presets = true) inline private
References GetCurrentObjectName(), HideItemButtons(), m_LastSelectedObject, m_PresetItemsTextListbox, m_SelectedObject, m_SelectedObjectIsPreset, m_SelectedObjectText, SetObject(), and ShowItemTransferButtons().
Referenced by OnClick(), and OnItemSelected().
SelectPreset()
void SelectPreset () inline private
References GetCurrentPresetName(), IsPresetFixed(), m_ClearInventory, ScriptConsoleTabBase::m_ConfigDebugProfileFixed, m_ObjectsTextListbox, m_SelectedObject, m_SelectedObjectIsPreset, m_SelectedObjectText, RenderPresetItems(), ShowItemTransferButtons(), ShowPresetButtons(), and string::ToLower().
Referenced by Init(), OnClick(), and OnItemSelected().
SetDefaultPreset()
void SetDefaultPreset (int preset_index) inline private
References CONST_DEFAULT_PRESET_PREFIX, GetCurrentPresetIndex(), GetCurrentPresetName(), GetPresetIndexByName(), IsPresetFixed(), ScriptConsoleTabBase::m_ConfigDebugProfile, and m_PresetsTextListbox.
Referenced by OnClick().
SetFilterOrder()
void SetFilterOrder (bool reversed) inline private
References ChangeFilterItems(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_FilterOrderImage, and m_FilterOrderReversed.
Referenced by Init(), and OnClick().
SetObject()
void SetObject (string object) inline private
References ScriptConsoleTabBase::m_ConfigDebugProfile, m_SelectedObject, and SetPreviewObject().
Referenced by Init(), OnClick(), OnItemSelected(), and SelectObject().
SetPreviewObject()
void SetPreviewObject (string object) inline private
References dBodyDestroy(), ECE_CREATEPHYSICS, ECE_LOCAL, ECE_TRACE, GetGame(), m_ItemPreviewWidget, m_PreviewEntity, m_SelectedObjectLocalized, and ItemPreviewWidget::SetItem().
Referenced by SetObject().
SetTextSpawnButton()
void SetTextSpawnButton (ButtonWidget w, bool special, string suffix = " Special") inline private
References m_SpawnButtonsOriginalText.
Referenced by UpdateButtonNames().
ShowItemButtons()
void ShowItemButtons () inline private
References GetCurrentItemIndex(), GetCurrentPresetName(), IsCurrentPresetFixed(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_DamageEditBox, m_ItemDamageLabel, m_ItemMoveDownButton, m_ItemMoveUpButton, m_ItemQuantityLabel, m_QuantityEditBox, m_WithPhysicsCheckbox, ShowItemTransferButtons(), and float::ToString().
Referenced by OnClick(), and OnItemSelected().
ShowItemTransferButtons()
void ShowItemTransferButtons () inline private
References GetCurrentItemIndex(), GetCurrentPresetIndex(), IsCurrentPresetFixed(), m_ItemNameCopy, m_ObjectsTextListbox, m_PresetAddItemtButton, and m_PresetRemoveItemButton.
Referenced by Init(), OnClick(), OnDoubleClick(), OnItemSelected(), SelectObject(), SelectPreset(), and ShowItemButtons().
ShowPresetButtons()
void ShowPresetButtons () inline private
References HideItemButtons(), IsCurrentPresetFixed(), m_PresetDeleteButton, and m_PresetRenameButton.
Referenced by SelectPreset().
SpawnPreset()
void SpawnPreset (EntityAI target, bool clear_inventory, string preset_name, InventoryLocationType location = InventoryLocationType.ATTACHMENT, float distance = 0) inline private
References GetCurrentPresetIndex(), GetGame(), GetPlayer(), GetPlugin(), IsCurrentPresetFixed(), ScriptConsoleTabBase::m_ConfigDebugProfile, ScriptConsoleTabBase::m_ConfigDebugProfileFixed, m_Developer, ScriptRPC::Send(), and Serializer::Write().
Referenced by OnClick().
Update()
override void Update (float timeslice) inline private
References UpdateButtonNames().
UpdateButtonNames()
void UpdateButtonNames () inline private
References ScriptConsoleTabBase::m_IsShiftDown, m_SpawnBatchButton, m_SpawnGroundButton, m_SpawnInHands, m_SpawnInInvButton, m_SpawnOnCursor, m_SpawnOnTarget, and SetTextSpawnButton().
Referenced by Update().
Field Documentation
CLEAR_IVN
protected bool CLEAR_IVN static private
Referenced by OnChange(), and OnClick().
CONST_DEFAULT_PRESET_PREFIX
protected const string CONST_DEFAULT_PRESET_PREFIX = "[Default]" private
Referenced by RenderPresets(), and SetDefaultPreset().
DRAW_DISTANCE
protected float DRAW_DISTANCE = 1000 static private
Referenced by DrawItems(), Init(), and OnChange().
ITEMS_IN_PRESET_SELECTED_ROW
protected int ITEMS_IN_PRESET_SELECTED_ROW static private
Referenced by Init(), and ~ScriptConsoleItemsTab().
ITEMS_SELECTED_ROW
protected int ITEMS_SELECTED_ROW = -1 static private
Referenced by Init(), and ~ScriptConsoleItemsTab().
m_BatchSpawnQuantity
protected EditBoxWidget m_BatchSpawnQuantity private
Referenced by Init(), OnChange(), OnClick(), and ScriptConsoleItemsTab().
m_CategoryButtonsNames
protected ref array<string> m_CategoryButtonsNames = {"FIREARMS","MELEE","ATTACHMENTS","MAGAZINES","AMMO","FOOD","MEDICAL","CARS","BACKPACKS","B-BUILDING"} private
Referenced by Init().
m_CategoryButtonsWidgets
protected ref array<Widget> m_CategoryButtonsWidgets = new array<Widget> private
Referenced by Init(), and OnChange().
m_CategoryMask
protected int m_CategoryMask private
Referenced by ChangeFilterItems(), Init(), OnChange(), and ~ScriptConsoleItemsTab().
m_CategoryMergeType
protected CheckBoxWidget m_CategoryMergeType private
Referenced by Init(), OnClick(), and ScriptConsoleItemsTab().
m_ClearInventory
protected CheckBoxWidget m_ClearInventory private
Referenced by OnChange(), ScriptConsoleItemsTab(), and SelectPreset().
m_DamageEditBox
protected EditBoxWidget m_DamageEditBox private
Referenced by OnChange(), OnClick(), ScriptConsoleItemsTab(), and ShowItemButtons().
m_DebugShapes
protected ref array<Shape> m_DebugShapes = new array<Shape> static private
Referenced by DrawItems(), and DrawItemsClear().
m_Developer
protected PluginDeveloper m_Developer private
Referenced by OnClick(), OnDoubleClick(), ScriptConsoleItemsTab(), and SpawnPreset().
m_DrawDistanceWidget
protected EditBoxWidget m_DrawDistanceWidget private
Referenced by Init(), OnChange(), and ScriptConsoleItemsTab().
m_DrawInWorld
protected ButtonWidget m_DrawInWorld private
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_DrawInWorldClear
protected ButtonWidget m_DrawInWorldClear private
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_FilterOrderButton
protected ButtonWidget m_FilterOrderButton private
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_FilterOrderImage
protected ImageWidget m_FilterOrderImage private
Referenced by ScriptConsoleItemsTab(), and SetFilterOrder().
m_FilterOrderReversed
protected bool m_FilterOrderReversed private
Referenced by ChangeFilter(), OnClick(), and SetFilterOrder().
m_FilterTextPrev
protected string m_FilterTextPrev private
Referenced by ChangeFilterItems().
m_ItemDamageLabel
protected TextWidget m_ItemDamageLabel private
Referenced by ScriptConsoleItemsTab(), and ShowItemButtons().
m_ItemMoveDownButton
protected ButtonWidget m_ItemMoveDownButton private
Referenced by HideItemButtons(), OnClick(), ScriptConsoleItemsTab(), and ShowItemButtons().
m_ItemMoveUpButton
protected ButtonWidget m_ItemMoveUpButton private
Referenced by HideItemButtons(), OnClick(), ScriptConsoleItemsTab(), and ShowItemButtons().
m_ItemNameCopy
protected ButtonWidget m_ItemNameCopy private
Referenced by OnClick(), ScriptConsoleItemsTab(), and ShowItemTransferButtons().
m_ItemPreviewCheckbox
protected CheckBoxWidget m_ItemPreviewCheckbox private
Referenced by Init(), OnClick(), and ScriptConsoleItemsTab().
m_ItemPreviewWidget
protected ItemPreviewWidget m_ItemPreviewWidget private
Referenced by OnClick(), ScriptConsoleItemsTab(), and SetPreviewObject().
m_ItemQuantity
protected float m_ItemQuantity = 1 static private
Referenced by Init(), and ~ScriptConsoleItemsTab().
m_ItemQuantityLabel
protected TextWidget m_ItemQuantityLabel private
Referenced by ScriptConsoleItemsTab(), and ShowItemButtons().
m_LastSelectedObject
protected string m_LastSelectedObject static private
Referenced by GetLastSelectedObject(), Init(), OnDoubleClick(), and SelectObject().
m_ListActions
protected ButtonWidget m_ListActions private
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_MissionGameplay
protected MissionGameplay m_MissionGameplay private
Referenced by Init(), and OnClick().
m_ObjectFilter
protected MultilineEditBoxWidget m_ObjectFilter private
Referenced by ChangeFilterItems(), Init(), OnClick(), and ScriptConsoleItemsTab().
m_ObjectsScope
protected int m_ObjectsScope = 2 static private
Referenced by ChangeFilter(), Init(), and OnChange().
m_ObjectsTextListbox
protected TextListboxWidget m_ObjectsTextListbox private
Referenced by AddItemToPreset(), ChangeFilterItems(), GetCurrentObjectName(), Init(), OnClick(), OnDoubleClick(), OnItemSelected(), ScriptConsoleItemsTab(), SelectPreset(), ShowItemTransferButtons(), and ~ScriptConsoleItemsTab().
m_PresetAddItemtButton
protected ButtonWidget m_PresetAddItemtButton private
Referenced by OnClick(), ScriptConsoleItemsTab(), and ShowItemTransferButtons().
m_PresetDeleteButton
protected ButtonWidget m_PresetDeleteButton private
Referenced by Init(), OnClick(), ScriptConsoleItemsTab(), and ShowPresetButtons().
m_PresetItemsTextListbox
protected TextListboxWidget m_PresetItemsTextListbox private
Referenced by GetCurrentItemIndex(), GetCurrentItemName(), Init(), ItemMoveDown(), ItemMoveUp(), OnClick(), OnDoubleClick(), OnItemSelected(), RenderPresetItems(), ScriptConsoleItemsTab(), SelectObject(), and ~ScriptConsoleItemsTab().
m_PresetNewButton
protected ButtonWidget m_PresetNewButton private
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_PresetRemoveItemButton
protected ButtonWidget m_PresetRemoveItemButton private
Referenced by OnClick(), ScriptConsoleItemsTab(), and ShowItemTransferButtons().
m_PresetRenameButton
protected ButtonWidget m_PresetRenameButton private
Referenced by Init(), OnClick(), ScriptConsoleItemsTab(), and ShowPresetButtons().
m_PresetSetDefaultButton
protected ButtonWidget m_PresetSetDefaultButton private
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_PresetsTextListbox
protected TextListboxWidget m_PresetsTextListbox private
Referenced by GetCurrentPresetIndex(), GetCurrentPresetName(), GetPresetIndexByName(), Init(), IsCurrentPresetFixed(), IsPresetFixed(), OnClick(), OnItemSelected(), RenderPresets(), ScriptConsoleItemsTab(), SetDefaultPreset(), and ~ScriptConsoleItemsTab().
m_PreviewEntity
protected EntityAI m_PreviewEntity static private
Referenced by ListItemRelatedActions(), OnClick(), SetPreviewObject(), and ~ScriptConsoleItemsTab().
m_QuantityEditBox
protected EditBoxWidget m_QuantityEditBox private
Referenced by Init(), OnChange(), OnClick(), OnDoubleClick(), ScriptConsoleItemsTab(), ShowItemButtons(), and ~ScriptConsoleItemsTab().
m_RectSpawnColumn
protected EditBoxWidget m_RectSpawnColumn private
Referenced by Init(), OnChange(), OnClick(), and ScriptConsoleItemsTab().
m_RectSpawnColumnStep
protected EditBoxWidget m_RectSpawnColumnStep private
Referenced by Init(), OnChange(), OnClick(), and ScriptConsoleItemsTab().
m_RectSpawnRow
protected EditBoxWidget m_RectSpawnRow private
Referenced by Init(), OnChange(), OnClick(), and ScriptConsoleItemsTab().
m_RectSpawnRowStep
protected EditBoxWidget m_RectSpawnRowStep private
Referenced by Init(), OnChange(), OnClick(), and ScriptConsoleItemsTab().
m_RefreshFilterTimer
protected ref Timer m_RefreshFilterTimer = new Timer() private
Referenced by Init(), and ~ScriptConsoleItemsTab().
m_ReloadShapeButton
protected ButtonWidget m_ReloadShapeButton private
Referenced by OnClick(), and ScriptConsoleItemsTab().
m_SelectedObject
protected string m_SelectedObject private
Referenced by Init(), OnClick(), OnDoubleClick(), OnKeyDown(), SelectObject(), SelectPreset(), and SetObject().
m_SelectedObjectIsPreset
protected int m_SelectedObjectIsPreset = -1 static private
Referenced by Init(), OnClick(), OnDoubleClick(), OnItemSelected(), SelectObject(), and SelectPreset().
m_SelectedObjectLocalized
protected TextWidget m_SelectedObjectLocalized private
Referenced by ScriptConsoleItemsTab(), and SetPreviewObject().
m_SelectedObjectText
protected TextWidget m_SelectedObjectText private
Referenced by Init(), OnClick(), OnDoubleClick(), OnItemSelected(), ScriptConsoleItemsTab(), SelectObject(), and SelectPreset().
m_ShowProtected
protected CheckBoxWidget m_ShowProtected private
Referenced by Init(), OnChange(), and ScriptConsoleItemsTab().
m_SpawnBatchButton
protected ButtonWidget m_SpawnBatchButton private
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_SpawnButtonsOriginalText
protected ref map<Widget, string> m_SpawnButtonsOriginalText = new map<Widget, string>() private
Referenced by ScriptConsoleItemsTab(), and SetTextSpawnButton().
m_SpawnDistanceEditBox
protected EditBoxWidget m_SpawnDistanceEditBox private
Referenced by Init(), OnClick(), OnDoubleClick(), SaveProfileSpawnDistance(), and ScriptConsoleItemsTab().
m_SpawnGroundButton
protected ButtonWidget m_SpawnGroundButton private
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_SpawnGroundPatternGrid
protected ButtonWidget m_SpawnGroundPatternGrid private
Referenced by OnClick().
m_SpawnInHands
protected ButtonWidget m_SpawnInHands private
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_SpawnInInvButton
protected ButtonWidget m_SpawnInInvButton private
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_SpawnOnCursor
protected ButtonWidget m_SpawnOnCursor private
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_SpawnOnTarget
protected ButtonWidget m_SpawnOnTarget private
Referenced by OnClick(), ScriptConsoleItemsTab(), and UpdateButtonNames().
m_WithPhysics
protected bool m_WithPhysics = false static private
Referenced by Init(), and ~ScriptConsoleItemsTab().
m_WithPhysicsCheckbox
protected CheckBoxWidget m_WithPhysicsCheckbox private
Referenced by Init(), OnChange(), OnClick(), ScriptConsoleItemsTab(), ShowItemButtons(), and ~ScriptConsoleItemsTab().
PRESETS_SELECTED_ROW
protected int PRESETS_SELECTED_ROW = 0 static private
Referenced by Init(), and ~ScriptConsoleItemsTab().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptConsoleItemsTab.c