DayZ Scripts: AnalyticsManagerClient Class Reference
AnalyticsManagerClient Class Reference
Private Member Functions
void RegisterEvents ()
void UnregisterEvents ()
void OnActionEat ()
void OnActionDrink ()
void OnActionCookedSteak ()
void OnActionFinishedShaveSelf ()
void OnActionFinishedGutDeer ()
void OnActionRestrain ()
void OnActionBandageTarget ()
void OnItemAttachedAtPlayer (EntityAI item, string slot_name)
void Event_OnPlayerIgnitedFireplace (EFireIgniteType ignite_type)
void Event_OnEntityKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot)
Static Private Attributes
static const int GEAR_COUNT = 3
static string m_FullGear [GEAR_COUNT] = {"Shoulder","Melee","Back"}
Detailed Description
Definition at line 1 of file AnalyticsManagerClient.c.
Member Function Documentation
Event_OnEntityKilled()
void Event_OnEntityKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot) inline private
Definition at line 173 of file AnalyticsManagerClient.c.
References GetGame(), GetID(), GetPlayer(), and Achievements::OnPlayerKilled().
Referenced by RegisterEvents(), and UnregisterEvents().
Event_OnPlayerIgnitedFireplace()
void Event_OnPlayerIgnitedFireplace (EFireIgniteType ignite_type) inline private
Definition at line 148 of file AnalyticsManagerClient.c.
References Achievements::OnActionIgniteDrill(), Achievements::OnActionIgniteMatchbox(), and Achievements::OnActionIgniteRoadflare().
Referenced by RegisterEvents(), and UnregisterEvents().
OnActionBandageTarget()
void OnActionBandageTarget () inline private
Definition at line 69 of file AnalyticsManagerClient.c.
References Achievements::OnActionMedsSurvivor().
Referenced by ActionBandageTarget::OnFinishProgressClient().
OnActionCookedSteak()
void OnActionCookedSteak () inline private
Definition at line 37 of file AnalyticsManagerClient.c.
References Achievements::OnCookedSteak().
Referenced by CAContinuousTimeCooking::Execute().
OnActionDrink()
void OnActionDrink () inline private
Definition at line 29 of file AnalyticsManagerClient.c.
References Achievements::OnActionDrink().
Referenced by AnimatedActionBase::End().
OnActionEat()
void OnActionEat () inline private
Definition at line 21 of file AnalyticsManagerClient.c.
References Achievements::OnActionEat().
Referenced by AnimatedActionBase::End().
OnActionFinishedGutDeer()
void OnActionFinishedGutDeer () inline private
Definition at line 53 of file AnalyticsManagerClient.c.
References Achievements::OnActionGutDeer().
Referenced by ActionSkinning::OnFinishProgressClient().
OnActionFinishedShaveSelf()
void OnActionFinishedShaveSelf () inline private
Definition at line 45 of file AnalyticsManagerClient.c.
References Achievements::OnActionShave().
Referenced by ActionShave::OnFinishProgressClient().
OnActionRestrain()
void OnActionRestrain () inline private
Definition at line 61 of file AnalyticsManagerClient.c.
References Achievements::OnActionHandcuff().
Referenced by ActionHandcuffTarget::OnExecuteClient(), and ActionRestrainTarget::OnFinishProgressClient().
OnItemAttachedAtPlayer()
void OnItemAttachedAtPlayer (EntityAI item, string slot_name) inline private
Definition at line 77 of file AnalyticsManagerClient.c.
References GameInventory::FindAttachment(), GEAR_COUNT, GetDayZGame(), HumanInventory::GetEntityInHands(), GetGame(), GetGameState(), CGame::GetPlayer(), InventorySlots::GetSlotIdFromString(), m_FullGear, and Achievements::OnEquippedFullGear().
Referenced by ManBase::EEItemAttached(), and InventoryItem::EEItemLocationChanged().
RegisterEvents()
void RegisterEvents () inline private
Definition at line 6 of file AnalyticsManagerClient.c.
References Event_OnEntityKilled(), Event_OnPlayerIgnitedFireplace(), ScriptInvoker::Insert(), ClientData::SyncEvent_OnEntityKilled, and ClientData::SyncEvent_OnPlayerIgnitedFireplace.
UnregisterEvents()
void UnregisterEvents () inline private
Definition at line 12 of file AnalyticsManagerClient.c.
References Event_OnEntityKilled(), Event_OnPlayerIgnitedFireplace(), ScriptInvoker::Remove(), ClientData::SyncEvent_OnEntityKilled, and ClientData::SyncEvent_OnPlayerIgnitedFireplace.
Field Documentation
GEAR_COUNT
const int GEAR_COUNT = 3 static private
Definition at line 3 of file AnalyticsManagerClient.c.
Referenced by OnItemAttachedAtPlayer().
m_FullGear
string m_FullGear[GEAR_COUNT] = {"Shoulder","Melee","Back"} static private
Definition at line 4 of file AnalyticsManagerClient.c.
Referenced by OnItemAttachedAtPlayer().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Analytics/AnalyticsManagerClient.c