DayZ Scripts: CAContinuousCraft Class Reference
CAContinuousCraft Class Reference
Private Member Functions
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override float GetProgress ()
Detailed Description
Definition at line 1 of file CAContinuousCraft.c.
Member Function Documentation
Execute()
override int Execute (ActionData action_data) inline private
Definition at line 34 of file CAContinuousCraft.c.
References CAContinuousTime::m_AdjustedTimeToComplete, ActionData::m_Player, CAContinuousTime::m_SpentUnits, CAContinuousTime::m_TimeElpased, CAContinuousBase::OnCompletePogress(), CABase::SetACData(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float GetProgress () inline private
Definition at line 58 of file CAContinuousCraft.c.
References CAContinuousTime::m_AdjustedTimeToComplete, and CAContinuousTime::m_TimeElpased.
Setup()
override void Setup (ActionData action_data) inline private
Definition at line 3 of file CAContinuousCraft.c.
References Class::CastTo(), GetPlugin(), CAContinuousTime::m_AdjustedTimeToComplete, ActionData::m_Player, CAContinuousTime::m_SpentUnits, and CAContinuousTime::m_TimeElpased.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousCraft.c