DayZ Scripts: StaticObj_Roadblock_Wood_Small Class Reference
StaticObj_Roadblock_Wood_Small Class Reference
Private Member Functions
override void EEInit ()
override void EEDelete (EntityAI parent)
Private Attributes
PointLightBase m_BlinkingLight
Member Function Documentation
EEDelete()
override void EEDelete (EntityAI parent) inline private
References GetGame(), and m_BlinkingLight.
EEInit()
override void EEInit () inline private
References EntranceLight(), GetGame(), and m_BlinkingLight.
Field Documentation
m_BlinkingLight
PointLightBase m_BlinkingLight private
Referenced by EEDelete(), and EEInit().
The documentation for this class was generated from the following file:
P:/scripts/4_world/entities/building/wrecks/staticobj_roadblock_wood_small.c