DayZ Scripts: Weapon Class Reference
Weapon Class Reference
script counterpart to engine's class Weapon
Private Member Functions
void Weapon_Base ()
void InitStateMachine ()
override void EEInit ()
void SetInitialState (WeaponStableState initState)
override protected float GetWeightSpecialized (bool forceRecalc=false)
void AssembleGun ()
override on weapons with some assembly required
bool CanProcessAction (int action, int actionType)
bool HasActionAbility (int action, int actionType)
query if weapon supports action and actionType
int GetAbilityCount ()
AbilityRecord GetAbility (int index)
bool CanProcessWeaponEvents ()
WeaponStateBase GetCurrentState ()
returns currently active state
bool IsWaitingForActionFinish ()
returns true if state machine started playing action/actionType and waits for finish
bool IsIdle ()
bool ProcessWeaponEvent (WeaponEventBase e)
weapon's fsm handling of events @NOTE: warning: ProcessWeaponEvent can be called only within DayZPlayer::HandleWeapons (or CommandHandler)
bool ProcessWeaponAbortEvent (WeaponEventBase e)
bool CanChamberBullet (int muzzleIndex, Magazine mag)
void SetWeaponAnimState (int state)
void ResetWeaponAnimState ()
int GetWeaponAnimState ()
void EEFired (int muzzleType, int mode, string ammoType)
bool JamCheck (int muzzleIndex)
void ShowBullet (int muzzleIndex)
void HideBullet (int muzzleIndex)
bool IsJammed ()
bool CanEjectBullet ()
void SetJammed (bool value)
float GetSyncChanceToJam ()
float GetChanceToJam ()
void SyncSelectionState (bool has_bullet, bool has_mag)
void ForceSyncSelectionState ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void SaveCurrentFSMState (ParamsWriteContext ctx)
bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
override void OnStoreSave (ParamsWriteContext ctx)
int GetInternalStateID ()
int GetCurrentStableStateID ()
tries to return identifier of current stable state (or nearest stable state if unstable state is currently running)
void RandomizeFSMState ()
With the parameters given, selects a random suitable state for the FSM of the weapon @WARNING: Weapon_Base.Synchronize call might be needed, if this method is called while clients are connected.
protected array< MuzzleState > GetMuzzleStates ()
Helper method for RandomizeFSMState.
override int GetSlotsCountCorrect ()
Returns number of slots for attachments corrected for weapons.
Private Attributes
const int SAMF_DEFAULT = WeaponWithAmmoFlags.CHAMBER | WeaponWithAmmoFlags.MAX_CAPACITY_MAG
Full highest capacity magazine + chambered round.
const int SAMF_RNG = WeaponWithAmmoFlags.CHAMBER_RNG | WeaponWithAmmoFlags.QUANTITY_RNG
Random bullet quantity + maybe chambered round.
protected const float DEFAULT_DAMAGE_ON_SHOT = 0.05
protected ref array< ref AbilityRecord > m_abilities = new array<ref AbilityRecord>
protected ref WeaponFSM m_fsm
weapon abilities
protected bool m_isJammed = false
weapon state machine
protected bool m_LiftWeapon = false
protected bool m_BayonetAttached
protected bool m_ButtstockAttached
protected int m_BurstCount
protected int m_BayonetAttachmentIdx
protected int m_ButtstockAttachmentIdx
protected int m_weaponAnimState = -1
protected int m_magazineSimpleSelectionIndex = -1
animation state the weapon is in, -1 == uninitialized
protected int m_weaponHideBarrelIdx = -1
protected float m_DmgPerShot = 0
protected float m_WeaponLength
ref array< int > m_bulletSelectionIndex = new array<int>
ref array< float > m_DOFProperties
ref array< float > m_ChanceToJam = new array<float>
protected float m_ChanceToJamSync = 0
protected ref PropertyModifiers m_PropertyModifierObject
protected PhxInteractionLayers hit_mask = PhxInteractionLayers.CHARACTER | PhxInteractionLayers.BUILDING | PhxInteractionLayers.DOOR | PhxInteractionLayers.VEHICLE | PhxInteractionLayers.ROADWAY | PhxInteractionLayers.TERRAIN | PhxInteractionLayers.ITEM_SMALL | PhxInteractionLayers.ITEM_LARGE | PhxInteractionLayers.FENCE | PhxInteractionLayers.AI
Weapon With Ammo
Helpers for spawning ammo/magazine in weapon For the flags, either a combination of WeaponWithAmmoFlags can be used Or one of the preset 'const int' with 'SAMF_' prefix (SAMF_DEFAULT, SAMF_RNG)
bool SpawnAmmo (string magazineType="", int flags=WeaponWithAmmoFlags.CHAMBER)
General method trying to attch magazine, fill inner magazine and fill chamber.
Magazine SpawnAttachedMagazine (string magazineType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Try to spawn and attach a magazine.
bool FillInnerMagazine (string ammoType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Try to fill the inner magazine.
bool FillChamber (string ammoType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Try to fill the chamber.
override int GetSlotsCountCorrect ()
Returns number of slots for attachments corrected for weapons.
PropertyModifiers GetPropertyModifierObject ()
void OnFire (int muzzle_index)
void OnFireModeChange (int fireMode)
void ValidateAndRepair ()
override void OnInventoryEnter (Man player)
override void OnInventoryExit (Man player)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanRemoveFromHands (EntityAI parent)
bool IsRemoteWeapon ()
void SyncEventToRemote (WeaponEventBase e)
RecoilBase SpawnRecoilObject ()
int GetWeaponSpecificCommand (int weaponAction, int subCommand)
bool CanFire ()
bool CanEnterIronsights ()
bool InitDOFProperties (out array< float > temp_array)
Initializes DOF properties for weapon's ironsight/optics cameras.
bool InitReliability (out array< float > reliability_array)
bool InitWeaponLength ()
gets weapon length from config for weaponlift raycast
ref array< float > GetWeaponDOF ()
bool LiftWeaponCheck (PlayerBase player)
void SetSyncJammingChance (float jamming_chance)
bool EjectCartridge (int muzzleIndex, out float ammoDamage, out string ammoTypeName)
unload bullet from chamber or internal magazine
bool CopyWeaponStateFrom (notnull Weapon_Base src)
override void SetBayonetAttached (bool pState, int slot_idx=-1)
attachment helpers (firearm melee)
override bool HasBayonetAttached ()
override int GetBayonetAttachmentIdx ()
override void SetButtstockAttached (bool pState, int slot_idx=-1)
override bool HasButtstockAttached ()
override int GetButtstockAttachmentIdx ()
void HideWeaponBarrel (bool state)
void ShowMagazine ()
void HideMagazine ()
override EntityAI ProcessMeleeItemDamage (int mode=0)
bool IsShowingChamberedBullet ()
int GetBurstCount ()
void ResetBurstCount ()
override void SetActions ()
override void OnDebugSpawn ()
static Weapon_Base CreateWeaponWithAmmo (string weaponType, string magazineType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Create weapon with ammo.
Detailed Description
script counterpart to engine's class Weapon
Definition at line 48 of file InventoryItem.c.
Member Function Documentation
AfterStoreLoad()
override void AfterStoreLoad () inline private
Definition at line 539 of file Weapon_Base.c.
AssembleGun()
void AssembleGun () private
override on weapons with some assembly required
CanChamberBullet()
bool CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 279 of file Weapon_Base.c.
References IsChamberFiredOut(), and IsChamberFull().
CanEjectBullet()
bool CanEjectBullet () inline private
Definition at line 363 of file Weapon_Base.c.
CanEnterIronsights()
bool CanEnterIronsights () inline private
Definition at line 1124 of file Weapon_Base.c.
CanFire()
bool CanFire () inline private
Definition at line 1117 of file Weapon_Base.c.
References IsChamberFiredOut(), IsDamageDestroyed(), and IsJammed().
CanProcessAction()
bool CanProcessAction (int action, int actionType) inline private
Definition at line 191 of file Weapon_Base.c.
CanProcessWeaponEvents()
CanProcessWeaponEvents () inline private
Returns
true if weapon has running fsm
Definition at line 225 of file Weapon_Base.c.
CanReleaseAttachment()
override bool CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 1044 of file Weapon_Base.c.
CanRemoveFromHands()
override bool CanRemoveFromHands (EntityAI parent) inline private
Definition at line 1063 of file Weapon_Base.c.
References IsIdle(), LogManager::IsWeaponLogEnable(), Type, and wpnDebugPrint().
CopyWeaponStateFrom()
bool CopyWeaponStateFrom (notnull Weapon_Base src) inline private
Definition at line 1282 of file Weapon_Base.c.
References ScriptReadWriteContext::GetReadContext(), ScriptReadWriteContext::GetWriteContext(), and OnStoreLoad().
CreateWeaponWithAmmo()
CreateWeaponWithAmmo (string weaponType, string magazineType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline static private
Create weapon with ammo.
Parameters
[in] weaponType string The weapon to create
[in] magazineType string The magazine to attach or ammo to load, passing in empty string will select random
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
The created weapon
Definition at line 655 of file Weapon_Base.c.
References ECE_PLACE_ON_SURFACE, ErrorEx, GetGame(), and vector::Zero.
EEFired()
void EEFired (int muzzleType, int mode, string ammoType) inline private
Definition at line 296 of file Weapon_Base.c.
References GetGame(), and IncreaseOverheating().
EEInit()
override void EEInit () inline private
Definition at line 115 of file Weapon_Base.c.
References Weapon_Base::AssembleGun(), ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), and GetGame().
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 998 of file Weapon_Base.c.
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 1005 of file Weapon_Base.c.
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 1012 of file Weapon_Base.c.
References HumanCommandMove::SetMeleeBlock().
EjectCartridge()
EjectCartridge (int muzzleIndex, out float ammoDamage, out string ammoTypeName) inline private
unload bullet from chamber or internal magazine
@NOTE: EjectCartridge = GetCartridgeInfo + PopCartridge
Parameters
[in] muzzleIndex
[out] ammoDamage damage of the ammo
[out] ammoTypeName type name of the ejected ammo
Returns
true if bullet removed from chamber
Definition at line 1267 of file Weapon_Base.c.
FillChamber()
FillChamber (string ammoType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline private
Try to fill the chamber.
Parameters
[in] ammoType string The ammo to load, passing in empty string will select random
Note
It is best to fill in the actual 'ammo', as in the ones usually prefixed by 'Bullet_', to skip searching for it
Parameters
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
Whether any chamber was filled
Definition at line 824 of file Weapon_Base.c.
References AmmoTypesAPI::MagazineTypeToAmmoType(), Math::RandomIntInclusive(), and Synchronize().
FillInnerMagazine()
FillInnerMagazine (string ammoType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline private
Try to fill the inner magazine.
Parameters
[in] ammoType string The ammo to load, passing in empty string will select random
Note
It is best to fill in the actual 'ammo', as in the ones usually prefixed by 'Bullet_', to skip searching for it
Parameters
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
Whether any ammo was added to the gun or not
Definition at line 756 of file Weapon_Base.c.
References AmmoTypesAPI::MagazineTypeToAmmoType(), and Math::RandomIntInclusive().
ForceSyncSelectionState()
void ForceSyncSelectionState () inline private
Definition at line 389 of file Weapon_Base.c.
References Weapon_Base::HideBullet(), IsChamberFull(), and Weapon_Base::ShowBullet().
GetAbility()
GetAbility (int index) inline private
Parameters
[in] index index into m_abilities storage
Returns
ability record
Definition at line 220 of file Weapon_Base.c.
GetAbilityCount()
GetAbilityCount () inline private
Returns
number of stored abilities
Definition at line 215 of file Weapon_Base.c.
GetBayonetAttachmentIdx()
override int GetBayonetAttachmentIdx () inline private
Definition at line 1328 of file Weapon_Base.c.
GetBurstCount()
int GetBurstCount () inline private
Definition at line 1414 of file Weapon_Base.c.
GetButtstockAttachmentIdx()
override int GetButtstockAttachmentIdx () inline private
Definition at line 1344 of file Weapon_Base.c.
GetChanceToJam()
float GetChanceToJam () inline private
Definition at line 366 of file Weapon_Base.c.
GetCurrentStableStateID()
GetCurrentStableStateID () inline private
tries to return identifier of current stable state (or nearest stable state if unstable state is currently running)
Definition at line 589 of file Weapon_Base.c.
GetCurrentState()
GetCurrentState () inline private
returns currently active state
Returns
current state the FSM is in (or NULL)
Definition at line 231 of file Weapon_Base.c.
GetInternalStateID()
int GetInternalStateID () inline private
Definition at line 579 of file Weapon_Base.c.
GetMuzzleStates()
protected array< MuzzleState > GetMuzzleStates () inline private
Helper method for RandomizeFSMState.
Definition at line 618 of file Weapon_Base.c.
References ErrorEx, IsChamberFiredOut(), and IsChamberFull().
GetPropertyModifierObject()
PropertyModifiers GetPropertyModifierObject () inline private
Definition at line 923 of file Weapon_Base.c.
GetSlotsCountCorrect() [1/2]
override int GetSlotsCountCorrect () inline private
Returns number of slots for attachments corrected for weapons.
Definition at line 915 of file Weapon_Base.c.
GetSlotsCountCorrect() [2/2]
override int GetSlotsCountCorrect () inline private
Returns number of slots for attachments corrected for weapons.
Definition at line 6 of file BinocularsBase.c.
GetSyncChanceToJam()
float GetSyncChanceToJam () inline private
Definition at line 365 of file Weapon_Base.c.
GetWeaponAnimState()
int GetWeaponAnimState () inline private
Definition at line 294 of file Weapon_Base.c.
GetWeaponDOF()
ref array< float > GetWeaponDOF () inline private
Definition at line 1166 of file Weapon_Base.c.
GetWeaponSpecificCommand()
int GetWeaponSpecificCommand (int weaponAction, int subCommand) inline private
Definition at line 1112 of file Weapon_Base.c.
GetWeightSpecialized()
override protected float GetWeightSpecialized (bool forceRecalc = false) inline private
Definition at line 128 of file Weapon_Base.c.
References WeightDebugData::AddCalcDetails(), g_Game, Ammunition_Base::GetAmmoWeightByBulletType(), WeightDebugData::SetCalcDetails(), and float::ToString().
HasActionAbility()
HasActionAbility (int action, int actionType) inline private
query if weapon supports action and actionType
Parameters
[in] action one of Human.actions (i.e. RELOAD, MECHANISM, ...)
[in] actionType one of Human.actionTypes (i.e. CHAMBERING_ONEBULLET_CLOSED, MECHANISM_CLOSED...)
Returns
true if weapon supports operation
Definition at line 201 of file Weapon_Base.c.
References AbilityRecord::m_action, and AbilityRecord::m_actionType.
HasBayonetAttached()
override bool HasBayonetAttached () inline private
Definition at line 1323 of file Weapon_Base.c.
HasButtstockAttached()
override bool HasButtstockAttached () inline private
Definition at line 1339 of file Weapon_Base.c.
HideBullet()
void HideBullet (int muzzleIndex) inline private
Definition at line 352 of file Weapon_Base.c.
HideMagazine()
void HideMagazine () inline private
Definition at line 1369 of file Weapon_Base.c.
HideWeaponBarrel()
void HideWeaponBarrel (bool state) inline private
Definition at line 1349 of file Weapon_Base.c.
References GetGame().
InitDOFProperties()
bool InitDOFProperties (out array< float > temp_array) inline private
Initializes DOF properties for weapon's ironsight/optics cameras.
Definition at line 1134 of file Weapon_Base.c.
References CGame::ConfigGetFloatArray(), GetGame(), and GetType().
InitReliability()
bool InitReliability (out array< float > reliability_array) inline private
Definition at line 1144 of file Weapon_Base.c.
References CGame::ConfigGetFloatArray(), GetGame(), and GetType().
InitStateMachine()
void InitStateMachine () inline private
Definition at line 113 of file Weapon_Base.c.
InitWeaponLength()
bool InitWeaponLength () inline private
gets weapon length from config for weaponlift raycast
Definition at line 1155 of file Weapon_Base.c.
IsIdle()
bool IsIdle () inline private
Definition at line 241 of file Weapon_Base.c.
IsJammed()
bool IsJammed () inline private
Definition at line 362 of file Weapon_Base.c.
IsRemoteWeapon()
bool IsRemoteWeapon () inline private
Definition at line 1073 of file Weapon_Base.c.
References InventoryLocation::GetParent(), and InventoryLocation::GetType().
IsShowingChamberedBullet()
bool IsShowingChamberedBullet () inline private
Definition at line 1409 of file Weapon_Base.c.
IsWaitingForActionFinish()
IsWaitingForActionFinish () inline private
returns true if state machine started playing action/actionType and waits for finish
Definition at line 236 of file Weapon_Base.c.
JamCheck()
bool JamCheck (int muzzleIndex) inline private
Definition at line 329 of file Weapon_Base.c.
LiftWeaponCheck()
bool LiftWeaponCheck (PlayerBase player) inline private
snippet below measures distance from "RightHandIndex1" bone for lifting calibration
Definition at line 1172 of file Weapon_Base.c.
References CGame::GetCurrentCameraDirection(), GetGame(), HumanMovementState::IsRaised(), Print(), DayZPhysics::RayCastBullet(), and vector::Zero.
LoadCurrentFSMState()
bool LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 506 of file Weapon_Base.c.
References Error(), GetType(), WeaponStableState::HasBullet(), WeaponStableState::HasMagazine(), LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 1439 of file Weapon_Base.c.
OnFire()
void OnFire (int muzzle_index) inline private
Definition at line 932 of file Weapon_Base.c.
OnFireModeChange()
void OnFireModeChange (int fireMode) inline private
Definition at line 960 of file Weapon_Base.c.
References GetGame(), GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
OnInventoryEnter()
override void OnInventoryEnter (Man player) inline private
Definition at line 983 of file Weapon_Base.c.
OnInventoryExit()
override void OnInventoryExit (Man player) inline private
Definition at line 992 of file Weapon_Base.c.
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 1030 of file Weapon_Base.c.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 416 of file Weapon_Base.c.
References Error(), LogManager::IsWeaponLogEnable(), Serializer::Read(), and wpnDebugPrint().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 551 of file Weapon_Base.c.
References Serializer::Write().
ProcessMeleeItemDamage()
override EntityAI ProcessMeleeItemDamage (int mode = 0) inline private
Definition at line 1377 of file Weapon_Base.c.
ProcessWeaponAbortEvent()
ProcessWeaponAbortEvent (WeaponEventBase e) inline private
@NOTE: warning: ProcessWeaponEvent can be called only within DayZPlayer::HandleWeapons (or CommandHandler)
Definition at line 270 of file Weapon_Base.c.
ProcessWeaponEvent()
ProcessWeaponEvent (WeaponEventBase e) inline private
weapon's fsm handling of events @NOTE: warning: ProcessWeaponEvent can be called only within DayZPlayer::HandleWeapons (or CommandHandler)
Definition at line 250 of file Weapon_Base.c.
References WeaponEventBase::GetEventID().
RandomizeFSMState()
RandomizeFSMState () inline private
With the parameters given, selects a random suitable state for the FSM of the weapon @WARNING: Weapon_Base.Synchronize call might be needed, if this method is called while clients are connected.
Definition at line 602 of file Weapon_Base.c.
References IsJammed().
ResetBurstCount()
void ResetBurstCount () inline private
Definition at line 1419 of file Weapon_Base.c.
ResetWeaponAnimState()
void ResetWeaponAnimState () inline private
Definition at line 289 of file Weapon_Base.c.
References fsmDebugSpam().
SaveCurrentFSMState()
void SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 491 of file Weapon_Base.c.
References Error(), GetType(), LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
SetActions()
override void SetActions () inline private
Definition at line 1424 of file Weapon_Base.c.
References AddAction(), and FirearmActionLoadBulletQuick().
SetBayonetAttached()
override void SetBayonetAttached (bool pState, int slot_idx = -1) inline private
attachment helpers (firearm melee)
Definition at line 1317 of file Weapon_Base.c.
SetButtstockAttached()
override void SetButtstockAttached (bool pState, int slot_idx = -1) inline private
Definition at line 1333 of file Weapon_Base.c.
SetInitialState()
void SetInitialState (WeaponStableState initState) inline private
Definition at line 122 of file Weapon_Base.c.
SetJammed()
void SetJammed (bool value) inline private
Definition at line 364 of file Weapon_Base.c.
SetSyncJammingChance()
void SetSyncJammingChance (float jamming_chance) inline private
Definition at line 1252 of file Weapon_Base.c.
SetWeaponAnimState()
void SetWeaponAnimState (int state) inline private
Definition at line 284 of file Weapon_Base.c.
ShowBullet()
void ShowBullet (int muzzleIndex) inline private
Definition at line 342 of file Weapon_Base.c.
ShowMagazine()
void ShowMagazine () inline private
Definition at line 1361 of file Weapon_Base.c.
SpawnAmmo()
SpawnAmmo (string magazineType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline private
General method trying to attch magazine, fill inner magazine and fill chamber.
Parameters
[in] magazineType string The magazine to attach or ammo to load, passing in empty string will select random
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
whether anything was spawned or done
Definition at line 675 of file Weapon_Base.c.
SpawnAttachedMagazine()
SpawnAttachedMagazine (string magazineType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline private
Try to spawn and attach a magazine.
Parameters
[in] magazineType string The magazine to attach, passing in empty string will select random
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
The created magazine or null
Definition at line 698 of file Weapon_Base.c.
References ErrorEx, GetDebugName(), Math::RandomIntInclusive(), and Synchronize().
SpawnRecoilObject()
RecoilBase SpawnRecoilObject () inline private
Definition at line 1107 of file Weapon_Base.c.
SyncEventToRemote()
void SyncEventToRemote (WeaponEventBase e) inline private
Definition at line 1089 of file Weapon_Base.c.
References WeaponEventBase::GetEventID(), INPUT_UDT_WEAPON_REMOTE_EVENT, LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, WeaponEventBase::m_player, wpnDebugPrint(), Serializer::Write(), and WeaponEventBase::WriteToContext().
SyncSelectionState()
void SyncSelectionState (bool has_bullet, bool has_mag) inline private
Definition at line 376 of file Weapon_Base.c.
ValidateAndRepair()
void ValidateAndRepair () inline private
Definition at line 977 of file Weapon_Base.c.
Weapon_Base()
void Weapon_Base () inline private
Definition at line 67 of file Weapon_Base.c.
References GetGame(), and Weapon_Base::InitStateMachine().
Field Documentation
DEFAULT_DAMAGE_ON_SHOT
protected const float DEFAULT_DAMAGE_ON_SHOT = 0.05 private
Definition at line 45 of file Weapon_Base.c.
hit_mask
protected PhxInteractionLayers hit_mask = PhxInteractionLayers.CHARACTER | PhxInteractionLayers.BUILDING | PhxInteractionLayers.DOOR | PhxInteractionLayers.VEHICLE | PhxInteractionLayers.ROADWAY | PhxInteractionLayers.TERRAIN | PhxInteractionLayers.ITEM_SMALL | PhxInteractionLayers.ITEM_LARGE | PhxInteractionLayers.FENCE | PhxInteractionLayers.AI private
Definition at line 65 of file Weapon_Base.c.
m_abilities
protected ref array<ref AbilityRecord> m_abilities = new array<ref AbilityRecord> private
Definition at line 46 of file Weapon_Base.c.
m_BayonetAttached
protected bool m_BayonetAttached private
Definition at line 50 of file Weapon_Base.c.
m_BayonetAttachmentIdx
protected int m_BayonetAttachmentIdx private
Definition at line 53 of file Weapon_Base.c.
m_bulletSelectionIndex
ref array<int> m_bulletSelectionIndex = new array<int> private
Definition at line 60 of file Weapon_Base.c.
m_BurstCount
protected int m_BurstCount private
Definition at line 52 of file Weapon_Base.c.
m_ButtstockAttached
protected bool m_ButtstockAttached private
Definition at line 51 of file Weapon_Base.c.
m_ButtstockAttachmentIdx
protected int m_ButtstockAttachmentIdx private
Definition at line 54 of file Weapon_Base.c.
m_ChanceToJam
ref array<float> m_ChanceToJam = new array<float> private
Definition at line 62 of file Weapon_Base.c.
m_ChanceToJamSync
protected float m_ChanceToJamSync = 0 private
Definition at line 63 of file Weapon_Base.c.
m_DmgPerShot
protected float m_DmgPerShot = 0 private
Definition at line 58 of file Weapon_Base.c.
m_DOFProperties
ref array<float> m_DOFProperties private
Definition at line 61 of file Weapon_Base.c.
m_fsm
protected ref WeaponFSM m_fsm private
weapon abilities
Definition at line 47 of file Weapon_Base.c.
m_isJammed
protected bool m_isJammed = false private
weapon state machine
Definition at line 48 of file Weapon_Base.c.
m_LiftWeapon
protected bool m_LiftWeapon = false private
Definition at line 49 of file Weapon_Base.c.
m_magazineSimpleSelectionIndex
protected int m_magazineSimpleSelectionIndex = -1 private
animation state the weapon is in, -1 == uninitialized
Definition at line 56 of file Weapon_Base.c.
m_PropertyModifierObject
protected ref PropertyModifiers m_PropertyModifierObject private
Definition at line 64 of file Weapon_Base.c.
m_weaponAnimState
protected int m_weaponAnimState = -1 private
Definition at line 55 of file Weapon_Base.c.
m_weaponHideBarrelIdx
protected int m_weaponHideBarrelIdx = -1 private
Definition at line 57 of file Weapon_Base.c.
m_WeaponLength
protected float m_WeaponLength private
Definition at line 59 of file Weapon_Base.c.
SAMF_DEFAULT
const int SAMF_DEFAULT = WeaponWithAmmoFlags.CHAMBER | WeaponWithAmmoFlags.MAX_CAPACITY_MAG private
Full highest capacity magazine + chambered round.
Definition at line 41 of file Weapon_Base.c.
SAMF_RNG
const int SAMF_RNG = WeaponWithAmmoFlags.CHAMBER_RNG | WeaponWithAmmoFlags.QUANTITY_RNG private
Random bullet quantity + maybe chambered round.
Definition at line 43 of file Weapon_Base.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Core/Inherited/InventoryItem.c
P:/scripts/4_World/Entities/Firearms/Weapon_Base.c
P:/scripts/4_World/Entities/ItemBase/BinocularsBase.c