DayZ Scripts: OptionSelector Class Reference
OptionSelector Class Reference
Private Member Functions
void OptionSelectorMultistate (Widget parent, int current_index, ScriptedWidgetEventHandler parent_c, bool disabled, notnull array< string > options)
void LoadNewValues (notnull array< string > options, int current_index)
override void SetNextOption ()
override void SetPrevOption ()
void PerformSetOption (int index)
void SetCanSwitch (bool value)
bool CanSwitch ()
void SetValue (int value, bool fire_event=true)
void SetValue (string value, bool fire_event=true)
void SetRandomValue ()
int GetValue ()
override void SetStringOption (string option, bool fire_event=true)
Private Attributes
protected bool m_CanSwitch
Detailed Description
Definition at line 1 of file OptionSelectorMultistate.c.
Member Function Documentation
CanSwitch()
bool CanSwitch () inline private
Definition at line 78 of file OptionSelectorMultistate.c.
References m_CanSwitch.
GetValue()
int GetValue () inline private
Definition at line 113 of file OptionSelectorMultistate.c.
LoadNewValues()
void LoadNewValues (notnull array< string > options, int current_index) inline private
Definition at line 28 of file OptionSelectorMultistate.c.
References SetValue().
OptionSelectorMultistate()
void OptionSelectorMultistate (Widget parent, int current_index, ScriptedWidgetEventHandler parent_c, bool disabled, notnull array< string > options) inline private
Definition at line 5 of file OptionSelectorMultistate.c.
References Error().
PerformSetOption()
void PerformSetOption (int index) inline private
Definition at line 66 of file OptionSelectorMultistate.c.
Referenced by SetNextOption(), and SetPrevOption().
SetCanSwitch()
void SetCanSwitch (bool value) inline private
Definition at line 73 of file OptionSelectorMultistate.c.
SetNextOption()
override void SetNextOption () inline private
Definition at line 34 of file OptionSelectorMultistate.c.
References PerformSetOption().
Referenced by OptionSelectorBase::OnClick(), and OptionSelectorBase::OnMouseButtonUp().
SetPrevOption()
override void SetPrevOption () inline private
Definition at line 50 of file OptionSelectorMultistate.c.
References PerformSetOption().
Referenced by OptionSelectorBase::OnMouseButtonUp().
SetRandomValue()
void SetRandomValue () inline private
Definition at line 106 of file OptionSelectorMultistate.c.
References Math::RandomInt().
SetStringOption()
override void SetStringOption (string option, bool fire_event = true) inline private
Definition at line 118 of file OptionSelectorMultistate.c.
SetValue() [1/2]
void SetValue (int value, bool fire_event = true) inline private
Definition at line 83 of file OptionSelectorMultistate.c.
Referenced by LoadNewValues().
SetValue() [2/2]
void SetValue (string value, bool fire_event = true) inline private
Definition at line 94 of file OptionSelectorMultistate.c.
Field Documentation
m_CanSwitch
protected bool m_CanSwitch private
Definition at line 3 of file OptionSelectorMultistate.c.
Referenced by CanSwitch().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/NewUI/OptionSelectorMultistate.c