DayZ Scripts: Watermark Class Reference
Watermark Class Reference
Private Member Functions
void Watermark (Widget parent)
Private Attributes
protected Widget m_Root
protected ImageWidget m_WatermarkImage
protected TextWidget m_WatermarkLabel
protected TextWidget m_WatermarkBuild
Constructor & Destructor Documentation
Watermark()
void Watermark (Widget parent) inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetVersion(), CGame::GetWorkspace(), m_Root, m_WatermarkBuild, m_WatermarkImage, and m_WatermarkLabel.
Field Documentation
m_Root
protected Widget m_Root private
Referenced by Watermark().
m_WatermarkBuild
protected TextWidget m_WatermarkBuild private
Referenced by Watermark().
m_WatermarkImage
protected ImageWidget m_WatermarkImage private
Referenced by Watermark().
m_WatermarkLabel
protected TextWidget m_WatermarkLabel private
Referenced by Watermark().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/Watermark.c