DayZ Scripts: Workbench Class Reference
Workbench Class Reference
Static Private Member Functions
static proto native WBModuleDef GetModule (string type)
static proto native bool OpenModule (string type)
static proto native bool CloseModule (string type)
static proto native void Dialog (string caption, string text)
static proto int ScriptDialog (string caption, string text, Class data)
static proto bool SearchResources (string filter, func callback)
static proto native int RunCmd (string command, bool wait=false)
static proto void GetCwd (out string currentDir)
static proto bool GetAbsolutePath (string relativePath, out string absPath)
Detailed Description
Definition at line 6 of file workbenchApi.c.
Member Function Documentation
CloseModule()
static proto native bool CloseModule (string type) static private
Dialog()
static proto native void Dialog (string caption, string text) static private
Referenced by CheckLocalisationPlugin::Run().
GetAbsolutePath()
static proto bool GetAbsolutePath (string relativePath, out string absPath) static private
Referenced by SVNBlamePlugin::Run(), SVNDiffPlugin::Run(), OpenDirPlugin::Run(), and SVNShowLogPlugin::Run().
GetCwd()
static proto void GetCwd (out string currentDir) static private
Referenced by OpenDirPlugin::Run(), and DayZTool::RunDayZBat().
GetModule()
static proto native WBModuleDef GetModule (string type) static private
Referenced by SVNBlamePlugin::Run(), CheckLocalisationPlugin::Run(), SVNDiffPlugin::Run(), OpenDirPlugin::Run(), ResavePlugin::Run(), SVNShowLogPlugin::Run(), and ResavePlugin::RunCommandline().
OpenModule()
static proto native bool OpenModule (string type) static private
RunCmd()
static proto native int RunCmd (string command, bool wait = false) static private
Referenced by SVNBlamePlugin::Run(), SVNDiffPlugin::Run(), OpenDirPlugin::Run(), SVNShowLogPlugin::Run(), and DayZTool::RunDayZBat().
ScriptDialog()
static proto int ScriptDialog (string caption, string text, Class data) static private
Referenced by DayZTool::Configure(), SVNBlamePlugin::Configure(), SVNDiffPlugin::Configure(), OpenDirPlugin::Configure(), SVNShowLogPlugin::Configure(), and ResavePlugin::Run().
SearchResources()
static proto bool SearchResources (string filter, func callback) static private
Referenced by CheckLocalisationPlugin::Run(), ResavePlugin::Run(), and ResavePlugin::RunCommandline().
The documentation for this class was generated from the following file:
P:/scripts/1_Core/workbenchApi.c