DayZ Scripts: Roadflare Class Reference
Roadflare Class Reference
Private Member Functions
void Roadflare ()
void SetModelState (int enum_state)
override void EEDelete (EntityAI parent)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void UpdateModelSelections ()
override void OnWorkStart ()
void SetBurningState (int state_number)
void SetBurningStateSynchronized (int state_number)
override void OnWork (float consumed_energy)
override void OnWorkStop ()
void UpdateActiveParticles ()
void DestroyParticle (Particle p)
void DestroyParticleEx (out Particle p)
void DestroyAllParticles ()
void StopSmoking ()
override void OnInventoryExit (Man player)
override bool CanPutInCargo (EntityAI parent)
override void OnInventoryEnter (Man player)
override void OnActivatedByItem (notnull ItemBase item)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void OnVariablesSynchronized ()
override void SetActions ()
Private Attributes
private int m_BurningState = RoadflareBurningState.NOT_BURNING
RoadflareLight m_Light
protected Particle m_ParInitialFire
protected Particle m_ParMainFire
protected Particle m_ParFinalFire
protected Particle m_ParJustSmoke
protected EffectSound m_BurningSound
protected EffectSound m_IgniteSound
ref Timer m_FinalSmokeTimer
private int m_ModelState = RoadflareModelStates.DEFAULT
ref NoiseParams m_NoisePar
private float m_NoiseTimer
Static Private Attributes
static protected const int INITIAL_BURNING_STATE_TIME = 5
static protected const int FINAL_BURNING_STATE_TIME = 60
static protected vector m_FlameLocalPos = "0 0.285 0"
static protected int PARTICLE_INIT_FIRE = ParticleList.ROADFLARE_BURNING_INIT
static protected int PARTICLE_MAIN_FIRE = ParticleList.ROADFLARE_BURNING_MAIN
static protected int PARTICLE_FINAL_FIRE = ParticleList.ROADFLARE_BURNING_ENDING
static protected int PARTICLE_FINAL_SMOKE = ParticleList.ROADFLARE_BURNING_SMOKE
static protected const string BURNING_SOUND = "roadflareLoop_SoundSet"
static protected const string IGNITE_SOUND = "roadflareTurnOn_SoundSet"
static protected const int BURNING_NOISE_RANGE = 30
static const string STANDS_FOLDED = "Sticks_Flare_Folded"
static const string STANDS_UNFOLDED = "Sticks_Flare_Unfolded"
static const string FLARE_CAP = "Flare_cap"
static const string UNIGNITED_TIP = "Pristine"
static const string IGNITED_TIP = "Burning"
static const string EXTINGUISHED_TIP = "Burned_out"
static const int SELECTION_Burning = 0
static const int SELECTION_Burned_out = 1
static const int SELECTION_Pristine = 2
static const int SELECTION_All = 3
static const string DEFAULT_TEXTURE = "dz\\gear\\consumables\\data\\road_flare_co.paa"
static const string BURNING_TEXTURE = "dz\\gear\\consumables\\data\\road_flare_e_co.paa"
static const string DEFAULT_MATERIAL = "dz\\gear\\consumables\\data\\road_flare.rvmat"
static const string BURNING_MATERIAL = "dz\\gear\\consumables\\data\\road_flare_on.rvmat"
Detailed Description
Definition at line 24 of file Roadflare.c.
Constructor & Destructor Documentation
Roadflare()
void Roadflare () inline private
Definition at line 82 of file Roadflare.c.
Member Function Documentation
CanIgniteItem()
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 464 of file Roadflare.c.
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 434 of file Roadflare.c.
References m_BurningState.
DestroyAllParticles()
void DestroyAllParticles () inline private
Definition at line 400 of file Roadflare.c.
References DestroyParticleEx(), m_ParFinalFire, m_ParInitialFire, m_ParJustSmoke, and m_ParMainFire.
Referenced by EEDelete(), and UpdateActiveParticles().
DestroyParticle()
void DestroyParticle (Particle p) inline private
Definition at line 384 of file Roadflare.c.
References Particle::SetWiggle(), and Particle::Stop().
Referenced by DestroyParticleEx().
DestroyParticleEx()
void DestroyParticleEx (out Particle p) inline private
Definition at line 393 of file Roadflare.c.
References DestroyParticle().
Referenced by DestroyAllParticles(), and UpdateActiveParticles().
EEDelete()
override void EEDelete (EntityAI parent) inline private
Definition at line 94 of file Roadflare.c.
References DestroyAllParticles(), SEffectManager::DestroyEffect(), GetGame(), m_BurningSound, m_FinalSmokeTimer, m_IgniteSound, and m_Light.
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 456 of file Roadflare.c.
References TripwireTrap().
OnInventoryEnter()
override void OnInventoryEnter (Man player) inline private
Definition at line 448 of file Roadflare.c.
References STANDS_FOLDED, and STANDS_UNFOLDED.
OnInventoryExit()
override void OnInventoryExit (Man player) inline private
Definition at line 416 of file Roadflare.c.
References m_BurningState, SetOrientation(), STANDS_FOLDED, STANDS_UNFOLDED, and Vector().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 118 of file Roadflare.c.
References Serializer::Read(), and SetModelState().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 111 of file Roadflare.c.
References m_ModelState, and Serializer::Write().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Definition at line 469 of file Roadflare.c.
References UpdateActiveParticles().
OnWork()
override void OnWork (float consumed_energy) inline private
Definition at line 236 of file Roadflare.c.
References FINAL_BURNING_STATE_TIME, GetGame(), INITIAL_BURNING_STATE_TIME, m_BurningState, SetBurningStateSynchronized(), and UpdateActiveParticles().
OnWorkStart()
override void OnWorkStart () inline private
Definition at line 190 of file Roadflare.c.
References BURNING_SOUND, GetGame(), IGNITE_SOUND, m_BurningSound, m_IgniteSound, m_Light, PlaySoundSet(), PlaySoundSetLoop(), SetBurningState(), SetModelState(), and Vector().
OnWorkStop()
override void OnWorkStop () inline private
Definition at line 286 of file Roadflare.c.
References CALL_CATEGORY_SYSTEM, GetEnergy(), GetGame(), m_BurningSound, m_FinalSmokeTimer, m_Light, SetBurningState(), SetBurningStateSynchronized(), SetHealth(), SetModelState(), StopSoundSet(), and UpdateActiveParticles().
SetActions()
override void SetActions () inline private
Definition at line 476 of file Roadflare.c.
References ActionAttach(), ActionDetach(), ActionLightItemOnFire(), and AddAction().
SetBurningState()
void SetBurningState (int state_number) inline private
Definition at line 220 of file Roadflare.c.
References m_BurningState.
Referenced by OnWorkStart(), and OnWorkStop().
SetBurningStateSynchronized()
void SetBurningStateSynchronized (int state_number) inline private
Definition at line 226 of file Roadflare.c.
References GetGame(), and m_BurningState.
Referenced by OnWork(), OnWorkStop(), and StopSmoking().
SetModelState()
void SetModelState (int enum_state) inline private
Definition at line 88 of file Roadflare.c.
References m_ModelState, and UpdateModelSelections().
Referenced by ActionTurnOnWhileInHands::OnStartClient(), ActionTurnOnWhileInHands::OnStartServer(), OnStoreLoad(), OnWorkStart(), and OnWorkStop().
StopSmoking()
void StopSmoking () inline private
Definition at line 409 of file Roadflare.c.
References SetBurningStateSynchronized(), and UpdateActiveParticles().
UpdateActiveParticles()
void UpdateActiveParticles () inline private
Definition at line 327 of file Roadflare.c.
References DestroyAllParticles(), DestroyParticleEx(), GetGame(), m_BurningState, m_FlameLocalPos, m_ParFinalFire, m_ParInitialFire, m_ParJustSmoke, m_ParMainFire, PARTICLE_FINAL_FIRE, PARTICLE_FINAL_SMOKE, PARTICLE_INIT_FIRE, PARTICLE_MAIN_FIRE, ParticleManager(), and Particle::SetWiggle().
Referenced by OnVariablesSynchronized(), OnWork(), OnWorkStop(), and StopSmoking().
UpdateModelSelections()
void UpdateModelSelections () inline private
Definition at line 132 of file Roadflare.c.
References DEFAULT_MATERIAL, DEFAULT_TEXTURE, EXTINGUISHED_TIP, FLARE_CAP, IGNITED_TIP, m_ModelState, SELECTION_Burned_out, SELECTION_Pristine, and UNIGNITED_TIP.
Referenced by SetModelState().
Field Documentation
BURNING_MATERIAL
const string BURNING_MATERIAL = "dz\\gear\\consumables\\data\\road_flare_on.rvmat" static private
Definition at line 76 of file Roadflare.c.
BURNING_NOISE_RANGE
protected const int BURNING_NOISE_RANGE = 30 static private
Definition at line 51 of file Roadflare.c.
BURNING_SOUND
protected const string BURNING_SOUND = "roadflareLoop_SoundSet" static private
Definition at line 49 of file Roadflare.c.
Referenced by OnWorkStart().
BURNING_TEXTURE
const string BURNING_TEXTURE = "dz\\gear\\consumables\\data\\road_flare_e_co.paa" static private
Definition at line 73 of file Roadflare.c.
DEFAULT_MATERIAL
const string DEFAULT_MATERIAL = "dz\\gear\\consumables\\data\\road_flare.rvmat" static private
Definition at line 75 of file Roadflare.c.
Referenced by UpdateModelSelections().
DEFAULT_TEXTURE
const string DEFAULT_TEXTURE = "dz\\gear\\consumables\\data\\road_flare_co.paa" static private
Definition at line 72 of file Roadflare.c.
Referenced by UpdateModelSelections().
EXTINGUISHED_TIP
const string EXTINGUISHED_TIP = "Burned_out" static private
Definition at line 65 of file Roadflare.c.
Referenced by UpdateModelSelections().
FINAL_BURNING_STATE_TIME
protected const int FINAL_BURNING_STATE_TIME = 60 static private
Definition at line 28 of file Roadflare.c.
Referenced by OnWork().
FLARE_CAP
const string FLARE_CAP = "Flare_cap" static private
Definition at line 62 of file Roadflare.c.
Referenced by UpdateModelSelections().
IGNITE_SOUND
protected const string IGNITE_SOUND = "roadflareTurnOn_SoundSet" static private
Definition at line 50 of file Roadflare.c.
Referenced by OnWorkStart().
IGNITED_TIP
const string IGNITED_TIP = "Burning" static private
Definition at line 64 of file Roadflare.c.
Referenced by UpdateModelSelections().
INITIAL_BURNING_STATE_TIME
protected const int INITIAL_BURNING_STATE_TIME = 5 static private
Definition at line 27 of file Roadflare.c.
Referenced by OnWork().
m_BurningSound
protected EffectSound m_BurningSound private
Definition at line 47 of file Roadflare.c.
Referenced by EEDelete(), OnWorkStart(), and OnWorkStop().
m_BurningState
private int m_BurningState = RoadflareBurningState.NOT_BURNING private
Definition at line 30 of file Roadflare.c.
Referenced by CanPutInCargo(), OnInventoryExit(), OnWork(), SetBurningState(), SetBurningStateSynchronized(), and UpdateActiveParticles().
m_FinalSmokeTimer
ref Timer m_FinalSmokeTimer private
Definition at line 54 of file Roadflare.c.
Referenced by EEDelete(), and OnWorkStop().
m_FlameLocalPos
protected vector m_FlameLocalPos = "0 0.285 0" static private
Definition at line 29 of file Roadflare.c.
Referenced by UpdateActiveParticles().
m_IgniteSound
protected EffectSound m_IgniteSound private
Definition at line 48 of file Roadflare.c.
Referenced by EEDelete(), and OnWorkStart().
m_Light
RoadflareLight m_Light private
Definition at line 33 of file Roadflare.c.
Referenced by EEDelete(), OnWorkStart(), and OnWorkStop().
m_ModelState
private int m_ModelState = RoadflareModelStates.DEFAULT private
Definition at line 57 of file Roadflare.c.
Referenced by OnStoreSave(), SetModelState(), and UpdateModelSelections().
m_NoisePar
ref NoiseParams m_NoisePar private
Definition at line 79 of file Roadflare.c.
m_NoiseTimer
private float m_NoiseTimer private
Definition at line 80 of file Roadflare.c.
m_ParFinalFire
protected Particle m_ParFinalFire private
Definition at line 38 of file Roadflare.c.
Referenced by DestroyAllParticles(), and UpdateActiveParticles().
m_ParInitialFire
protected Particle m_ParInitialFire private
Definition at line 36 of file Roadflare.c.
Referenced by DestroyAllParticles(), and UpdateActiveParticles().
m_ParJustSmoke
protected Particle m_ParJustSmoke private
Definition at line 39 of file Roadflare.c.
Referenced by DestroyAllParticles(), and UpdateActiveParticles().
m_ParMainFire
protected Particle m_ParMainFire private
Definition at line 37 of file Roadflare.c.
Referenced by DestroyAllParticles(), and UpdateActiveParticles().
PARTICLE_FINAL_FIRE
protected int PARTICLE_FINAL_FIRE = ParticleList.ROADFLARE_BURNING_ENDING static private
Definition at line 43 of file Roadflare.c.
Referenced by UpdateActiveParticles().
PARTICLE_FINAL_SMOKE
protected int PARTICLE_FINAL_SMOKE = ParticleList.ROADFLARE_BURNING_SMOKE static private
Definition at line 44 of file Roadflare.c.
Referenced by UpdateActiveParticles().
PARTICLE_INIT_FIRE
protected int PARTICLE_INIT_FIRE = ParticleList.ROADFLARE_BURNING_INIT static private
Definition at line 41 of file Roadflare.c.
Referenced by UpdateActiveParticles().
PARTICLE_MAIN_FIRE
protected int PARTICLE_MAIN_FIRE = ParticleList.ROADFLARE_BURNING_MAIN static private
Definition at line 42 of file Roadflare.c.
Referenced by UpdateActiveParticles().
SELECTION_All
const int SELECTION_All = 3 static private
Definition at line 70 of file Roadflare.c.
SELECTION_Burned_out
const int SELECTION_Burned_out = 1 static private
Definition at line 68 of file Roadflare.c.
Referenced by UpdateModelSelections().
SELECTION_Burning
const int SELECTION_Burning = 0 static private
Definition at line 67 of file Roadflare.c.
SELECTION_Pristine
const int SELECTION_Pristine = 2 static private
Definition at line 69 of file Roadflare.c.
Referenced by UpdateModelSelections().
STANDS_FOLDED
const string STANDS_FOLDED = "Sticks_Flare_Folded" static private
Definition at line 60 of file Roadflare.c.
Referenced by OnInventoryEnter(), and OnInventoryExit().
STANDS_UNFOLDED
const string STANDS_UNFOLDED = "Sticks_Flare_Unfolded" static private
Definition at line 61 of file Roadflare.c.
Referenced by OnInventoryEnter(), and OnInventoryExit().
UNIGNITED_TIP
const string UNIGNITED_TIP = "Pristine" static private
Definition at line 63 of file Roadflare.c.
Referenced by UpdateModelSelections().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Roadflare.c