DayZ Scripts: UniversalTemperatureSourceDebug Class Reference
UniversalTemperatureSourceDebug Class Reference
Private Member Functions
void UniversalTemperatureSource (EntityAI pParent, UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceLambdaBase pLambda)
void ~UniversalTemperatureSource ()
void Init (EntityAI pParent)
vector GetPosition ()
float GetFullRange ()
float GetMaxRange ()
float GetTemperature ()
float GetTemperatureRaw ()
float GetTemperatureMin ()
float GetTemperatureMax ()
EntityAI GetParent ()
bool IsActive ()
void SetActive (bool pActive)
void SetDefferedActive (bool pActive, float pSeconds)
void ChangeSettings (UniversalTemperatureSourceSettings pSettings)
void Update (UniversalTemperatureSourceSettings settings, UniversalTemperatureSourceLambdaBase lambda)
Private Attributes
protected bool m_Active protected ref UniversalTemperatureSourceTimer m_Timer
protected UniversalTemperatureSourceSettings m_Settings
protected ref UniversalTemperatureSourceResult m_ResultValues
protected ref UniversalTemperatureSourceLambdaBase m_Lambda
Constructor & Destructor Documentation
~UniversalTemperatureSource()
void ~UniversalTemperatureSource () inline private
Member Function Documentation
ChangeSettings()
void ChangeSettings (UniversalTemperatureSourceSettings pSettings) inline private
References m_Timer.
GetFullRange()
float GetFullRange () inline private
References UniversalTemperatureSourceSettings::m_RangeFull.
GetMaxRange()
float GetMaxRange () inline private
References UniversalTemperatureSourceSettings::m_RangeMax.
GetParent()
EntityAI GetParent () inline private
References UniversalTemperatureSourceSettings::m_Parent.
GetPosition()
vector GetPosition () inline private
References UniversalTemperatureSourceSettings::m_Position.
GetTemperature()
float GetTemperature () inline private
References UniversalTemperatureSourceSettings::m_TemperatureCap, float::MAX, and Math::Min().
GetTemperatureMax()
float GetTemperatureMax () inline private
References UniversalTemperatureSourceSettings::m_TemperatureMax.
GetTemperatureMin()
float GetTemperatureMin () inline private
References UniversalTemperatureSourceSettings::m_TemperatureMin.
GetTemperatureRaw()
float GetTemperatureRaw () inline private
Init()
void Init (EntityAI pParent) inline private
References UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_Parent, UniversalTemperatureSourceSettings::m_Position, m_Timer, UniversalTemperatureSourceSettings::m_Updateable, UniversalTemperatureSourceSettings::m_UpdateInterval, and SetActive().
IsActive()
bool IsActive () inline private
References UniversalTemperatureSourceSettings::m_ManualUpdate, and m_Timer.
SetActive()
void SetActive (bool pActive) inline private
References UniversalTemperatureSourceSettings::m_ManualUpdate, m_Timer, and Timer::Stop().
SetDefferedActive()
void SetDefferedActive (bool pActive, float pSeconds) inline private
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLaterByName(), CGame::GetCallQueue(), and GetGame().
UniversalTemperatureSource()
void UniversalTemperatureSource (EntityAI pParent, UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceLambdaBase pLambda) inline private
References Init(), and m_Timer.
Update()
void Update (UniversalTemperatureSourceSettings settings, UniversalTemperatureSourceLambdaBase lambda) inline private
References UniversalTemperatureSourceLambdaBase::Execute(), IsActive(), UniversalTemperatureSourceSettings::m_Parent, and UniversalTemperatureSourceSettings::m_Position.
Field Documentation
m_Lambda
protected ref UniversalTemperatureSourceLambdaBase m_Lambda private
m_ResultValues
protected ref UniversalTemperatureSourceResult m_ResultValues private
m_Settings
protected UniversalTemperatureSourceSettings m_Settings private
m_Timer
protected bool m_Active protected ref UniversalTemperatureSourceTimer m_Timer private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/UniversalTemperatureSource/UniversalTemperatureSource.c