DayZ Scripts: ActionEatMeat Class Reference
ActionEatMeat Class Reference
Private Member Functions
void ActionEatMeat ()
override void ApplyModifiers (ActionData action_data)
Constructor & Destructor Documentation
ActionEatMeat()
void ActionEatMeat () inline private
References AnimatedActionBase::m_CallbackClass.
Member Function Documentation
ApplyModifiers()
override void ApplyModifiers (ActionData action_data) inline private
References GetPlugin(), Edible_Base::IsMeat(), ActionData::m_MainItem, ActionData::m_Player, and PluginLifespan().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionEatMeat.c