DayZ Scripts: P:/scripts/4_World/Entities/ItemBase/Edible_Base.c File Reference
Edible_Base.c File Reference
Data Structures
class ItemBase
Functions
class Edible_Base extends ItemBase ReplaceEdibleWithNewLambda (EntityAI old_item, string new_item_type, PlayerBase player)
void Edible_Base ()
override void EEInit ()
override void EEDelete (EntityAI parent)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void UpdateVisuals ()
bool Consume (float amount, PlayerBase consumer)
void OnConsume (float amount, PlayerBase consumer)
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
void Synchronize ()
override void OnVariablesSynchronized ()
void MakeSoundsOnClient (bool soundstate)
protected void RefreshAudio ()
protected void RemoveAudio ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void AfterStoreLoad ()
FoodStage GetFoodStage ()
override bool IsMeat ()
override bool IsCorpse ()
override bool IsFruit ()
override bool IsMushroom ()
static float GetFoodTotalVolume (ItemBase item, string classname="", int food_stage=0)
static float GetFoodEnergy (ItemBase item, string classname="", int food_stage=0)
static float GetFoodWater (ItemBase item, string classname="", int food_stage=0)
static float GetFoodNutritionalIndex (ItemBase item, string classname="", int food_stage=0)
static float GetFoodToxicity (ItemBase item, string classname="", int food_stage=0)
static int GetFoodAgents (ItemBase item, string classname="", int food_stage=0)
static float GetFoodDigestibility (ItemBase item, string classname="", int food_stage=0)
static NutritionalProfile GetNutritionalProfile (ItemBase item, string classname="", int food_stage=0)
FoodStageType GetFoodStageType ()
bool IsFoodRaw ()
bool IsFoodBaked ()
bool IsFoodBoiled ()
bool IsFoodDried ()
bool IsFoodBurned ()
bool IsFoodRotten ()
void ChangeFoodStage (FoodStageType new_food_stage_type)
FoodStageType GetNextFoodStageType (CookingMethodType cooking_method)
string GetFoodStageName (FoodStageType food_stage_type)
bool CanChangeToNewStage (CookingMethodType cooking_method)
void TransferFoodStage (notnull Edible_Base source)
float GetCookingTime ()
void SetCookingTime (float time)
void ReplaceEdibleWithNew (string typeName)
override void SetActions ()
protected void SoundCookingStart (string sound_name)
protected void SoundCookingStop ()
override bool CanHaveTemperature ()
override bool CanDecay ()
override bool CanProcessDecay ()
override void ProcessDecay (float delta, bool hasRootAsPlayer)
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
float GetDecayTimer ()
float GetDecayDelta ()
FoodStageType GetLastDecayStage ()
Variables
const string DIRECT_COOKING_SLOT_NAME = "DirectCooking"
const string SOUND_BAKING_START = "Baking_SoundSet"
const string SOUND_BAKING_DONE = "Baking_Done_SoundSet"
const string SOUND_BURNING_DONE = "Food_Burning_SoundSet"
protected bool m_MakeCookingSounds
protected SoundOnVehicle m_SoundCooking
protected EffectSound m_SoundEffectCooking
DEPRECATED.
protected string m_SoundPlaying
ref FoodStage m_FoodStage
protected float m_DecayTimer
protected float m_DecayDelta = 0.0
protected FoodStageType m_LastDecayStage = FoodStageType.NONE
Function Documentation
AfterStoreLoad()
override void AfterStoreLoad ()
Definition at line 1020 of file Edible_Base.c.
CanBeCooked()
override bool CanBeCooked ()
Definition at line 895 of file Edible_Base.c.
CanBeCookedOnStick()
override bool CanBeCookedOnStick ()
Definition at line 900 of file Edible_Base.c.
CanChangeToNewStage()
bool CanChangeToNewStage (CookingMethodType cooking_method)
Definition at line 1256 of file Edible_Base.c.
Referenced by ItemBase::ProcessDecay().
CanDecay()
override bool CanDecay ()
Definition at line 1340 of file Edible_Base.c.
CanHaveTemperature()
override bool CanHaveTemperature ()
Definition at line 1335 of file Edible_Base.c.
CanProcessDecay()
override bool CanProcessDecay ()
Definition at line 1345 of file Edible_Base.c.
ChangeFoodStage()
void ChangeFoodStage (FoodStageType new_food_stage_type)
Definition at line 1241 of file Edible_Base.c.
Referenced by Apple::EEOnCECreate(), GreenBellPepper::EEOnCECreate(), Pear::EEOnCECreate(), Plum::EEOnCECreate(), Potato::EEOnCECreate(), Tomato::EEOnCECreate(), Zucchini::EEOnCECreate(), MushroomBase::EEOnCECreate(), ItemBase::OnAction(), ItemBase::ProcessDecay(), and ItemBase::TransferFoodStage().
Consume()
bool Consume (float amount, PlayerBase consumer)
Definition at line 885 of file Edible_Base.c.
Edible_Base()
void Edible_Base ()
Definition at line 818 of file Edible_Base.c.
EEDelete()
override void EEDelete (EntityAI parent)
Definition at line 844 of file Edible_Base.c.
EEInit()
override void EEInit ()
Definition at line 836 of file Edible_Base.c.
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
disable sounds (from cooking)
check for DirectCooking slot name
Definition at line 852 of file Edible_Base.c.
GetCookingTime()
float GetCookingTime ()
Definition at line 1276 of file Edible_Base.c.
GetDebugActions()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
Definition at line 1540 of file Edible_Base.c.
GetDecayDelta()
float GetDecayDelta ()
Definition at line 1589 of file Edible_Base.c.
GetDecayTimer()
float GetDecayTimer ()
Definition at line 1584 of file Edible_Base.c.
GetFoodAgents()
static int GetFoodAgents (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1136 of file Edible_Base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodDigestibility()
static float GetFoodDigestibility (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1151 of file Edible_Base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodEnergy()
static float GetFoodEnergy (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1075 of file Edible_Base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodNutritionalIndex()
static float GetFoodNutritionalIndex (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1105 of file Edible_Base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodStage()
FoodStage GetFoodStage ()
Definition at line 1029 of file Edible_Base.c.
Referenced by ItemBase::CanChangeToNewStage(), ItemBase::ChangeFoodStage(), ItemBase::GetCookingTime(), ItemBase::GetFoodStageName(), ItemBase::GetFoodStageType(), ItemBase::GetNextFoodStageType(), ItemBase::IsFoodBaked(), ItemBase::IsFoodBoiled(), ItemBase::IsFoodBurned(), ItemBase::IsFoodDried(), ItemBase::IsFoodRaw(), ItemBase::IsFoodRotten(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::SetCookingTime(), and ItemBase::UpdateVisuals().
GetFoodStageName()
string GetFoodStageName (FoodStageType food_stage_type)
Definition at line 1251 of file Edible_Base.c.
GetFoodStageType()
FoodStageType GetFoodStageType ()
Definition at line 1174 of file Edible_Base.c.
Referenced by ItemBase::CanProcessDecay(), ItemBase::OnAction(), ItemBase::ProcessDecay(), and ItemBase::RefreshAudio().
GetFoodTotalVolume()
static float GetFoodTotalVolume (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1059 of file Edible_Base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodToxicity()
static float GetFoodToxicity (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1121 of file Edible_Base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodWater()
static float GetFoodWater (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1090 of file Edible_Base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetLastDecayStage()
FoodStageType GetLastDecayStage ()
Definition at line 1594 of file Edible_Base.c.
GetNextFoodStageType()
FoodStageType GetNextFoodStageType (CookingMethodType cooking_method)
Definition at line 1246 of file Edible_Base.c.
GetNutritionalProfile()
static NutritionalProfile GetNutritionalProfile (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1166 of file Edible_Base.c.
IsCorpse()
override bool IsCorpse ()
Definition at line 1040 of file Edible_Base.c.
Referenced by IEntity::IsFood().
IsFoodBaked()
bool IsFoodBaked ()
Definition at line 1190 of file Edible_Base.c.
IsFoodBoiled()
bool IsFoodBoiled ()
Definition at line 1200 of file Edible_Base.c.
IsFoodBurned()
bool IsFoodBurned ()
Definition at line 1220 of file Edible_Base.c.
IsFoodDried()
bool IsFoodDried ()
Definition at line 1210 of file Edible_Base.c.
IsFoodRaw()
bool IsFoodRaw ()
Definition at line 1180 of file Edible_Base.c.
IsFoodRotten()
bool IsFoodRotten ()
Definition at line 1230 of file Edible_Base.c.
IsFruit()
override bool IsFruit ()
Definition at line 1045 of file Edible_Base.c.
Referenced by IEntity::IsFood().
IsMeat()
override bool IsMeat ()
Definition at line 1035 of file Edible_Base.c.
Referenced by IEntity::IsFood().
IsMushroom()
override bool IsMushroom ()
Definition at line 1050 of file Edible_Base.c.
Referenced by IEntity::IsFood(), and ItemBase::ProcessDecay().
MakeSoundsOnClient()
void MakeSoundsOnClient (bool soundstate)
Definition at line 939 of file Edible_Base.c.
Referenced by ItemBase::EEItemLocationChanged().
OnAction()
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
Definition at line 1551 of file Edible_Base.c.
OnConsume()
void OnConsume (float amount, PlayerBase consumer)
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 992 of file Edible_Base.c.
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
Definition at line 978 of file Edible_Base.c.
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 918 of file Edible_Base.c.
ProcessDecay()
override void ProcessDecay (float delta, bool hasRootAsPlayer)
Definition at line 1350 of file Edible_Base.c.
RefreshAudio()
protected void RefreshAudio ()
Definition at line 946 of file Edible_Base.c.
Referenced by ItemBase::OnVariablesSynchronized().
RemoveAudio()
protected void RemoveAudio ()
Definition at line 969 of file Edible_Base.c.
Referenced by ItemBase::EEDelete(), and ItemBase::OnVariablesSynchronized().
ReplaceEdibleWithNew()
void ReplaceEdibleWithNew (string typeName)
Definition at line 1290 of file Edible_Base.c.
Referenced by BakedBeansCan::Open(), PeachesCan::Open(), SardinesCan::Open(), SpaghettiCan::Open(), TacticalBaconCan::Open(), TunaCan::Open(), DogFoodCan::Open(), CatFoodCan::Open(), PorkCan::Open(), Lunchmeat::Open(), UnknownFoodCan::Open(), Pajka::Open(), Pate::Open(), and BrisketSpread::Open().
ReplaceEdibleWithNewLambda()
class Edible_Base extends ItemBase ReplaceEdibleWithNewLambda (EntityAI old_item, string new_item_type, PlayerBase player)
Definition at line 1 of file Edible_Base.c.
Referenced by ItemBase::ReplaceEdibleWithNew().
SetActions()
override void SetActions ()
Definition at line 1302 of file Edible_Base.c.
SetCookingTime()
void SetCookingTime (float time)
Definition at line 1281 of file Edible_Base.c.
SoundCookingStart()
protected void SoundCookingStart (string sound_name)
Definition at line 1310 of file Edible_Base.c.
Referenced by ItemBase::RefreshAudio(), and RefreshAudioVisuals().
SoundCookingStop()
protected void SoundCookingStop ()
Definition at line 1323 of file Edible_Base.c.
Referenced by ItemBase::RemoveAudio(), RemoveAudioVisuals(), and ItemBase::SoundCookingStart().
Synchronize()
void Synchronize ()
Definition at line 908 of file Edible_Base.c.
TransferFoodStage()
void TransferFoodStage (notnull Edible_Base source)
Definition at line 1262 of file Edible_Base.c.
UpdateVisuals()
void UpdateVisuals ()
Definition at line 877 of file Edible_Base.c.
Variable Documentation
DIRECT_COOKING_SLOT_NAME
const string DIRECT_COOKING_SLOT_NAME = "DirectCooking"
Definition at line 803 of file Edible_Base.c.
Referenced by ItemBase::EEItemLocationChanged().
m_DecayDelta
protected float m_DecayDelta = 0.0
Definition at line 815 of file Edible_Base.c.
Referenced by ItemBase::GetDecayDelta(), ItemBase::ProcessDecay(), and ItemBase::TransferFoodStage().
m_DecayTimer
protected float m_DecayTimer
Definition at line 814 of file Edible_Base.c.
Referenced by ItemBase::GetDecayTimer(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), PluginBase::PluginObjectsInteractionManager(), ItemBase::ProcessDecay(), and ItemBase::TransferFoodStage().
m_FoodStage
ref FoodStage m_FoodStage
Definition at line 813 of file Edible_Base.c.
Referenced by ItemBase::Edible_Base(), and ItemBase::GetFoodStage().
m_LastDecayStage
protected FoodStageType m_LastDecayStage = FoodStageType.NONE
Definition at line 816 of file Edible_Base.c.
Referenced by ItemBase::GetLastDecayStage(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::ProcessDecay(), and ItemBase::TransferFoodStage().
m_MakeCookingSounds
protected bool m_MakeCookingSounds
Definition at line 809 of file Edible_Base.c.
Referenced by ItemBase::MakeSoundsOnClient(), ItemBase::OnVariablesSynchronized(), and ItemBase::RemoveAudio().
m_SoundCooking
protected SoundOnVehicle m_SoundCooking
Definition at line 810 of file Edible_Base.c.
m_SoundEffectCooking
protected EffectSound m_SoundEffectCooking
DEPRECATED.
Definition at line 811 of file Edible_Base.c.
Referenced by ItemBase::SoundCookingStart(), and ItemBase::SoundCookingStop().
m_SoundPlaying
protected string m_SoundPlaying
Definition at line 812 of file Edible_Base.c.
Referenced by ItemBase::Edible_Base(), ItemBase::SoundCookingStart(), and ItemBase::SoundCookingStop().
SOUND_BAKING_DONE
const string SOUND_BAKING_DONE = "Baking_Done_SoundSet"
Definition at line 806 of file Edible_Base.c.
Referenced by ItemBase::RefreshAudio(), and RefreshAudioVisuals().
SOUND_BAKING_START
const string SOUND_BAKING_START = "Baking_SoundSet"
Definition at line 805 of file Edible_Base.c.
Referenced by ItemBase::RefreshAudio(), and RefreshAudioVisuals().
SOUND_BURNING_DONE
const string SOUND_BURNING_DONE = "Food_Burning_SoundSet"
Definition at line 807 of file Edible_Base.c.
Referenced by ItemBase::RefreshAudio(), and RefreshAudioVisuals().