DayZ Scripts: PluginBase Class Reference
PluginBase Class Reference
Private Member Functions
void PluginBase ()
void ~PluginBase ()
void OnInit ()
void OnUpdate (float delta_time)
void OnDestroy ()
void Log (string msg, string label)
string GetModuleName ()
GetModuleType ()
void PluginAdminLog ()
void ~PluginAdminLog ()
void LogPrint (string message)
string GetPlayerPrefix (PlayerBase player, PlayerIdentity identity)
string GetHitMessage (TotalDamageResult damageResult, int component, string zone, string ammo)
void PlayerKilled (PlayerBase player, Object source)
void PlayerHitBy (TotalDamageResult damageResult, int damageType, PlayerBase player, EntityAI source, int component, string dmgZone, string ammo)
void UnconStart (PlayerBase player)
void UnconStop (PlayerBase player)
void OnPlacementComplete (Man player, ItemBase item)
void OnContinouousAction (ActionData action_data)
void Suicide (PlayerBase player)
void BleedingOut (PlayerBase player)
void TotemFlagChange (bool top, notnull PlayerBase player, notnull EntityAI totem)
void PlayerList ()
void DirectAdminLogPrint (string str)
override void OnInit ()
void ToggleCameraTools ()
void CursorHide ()
void CursorShow ()
void Save ()
void PlayPause ()
void AddKeyframe ()
void DeleteKeyframe ()
void PluginConfigViewer ()
string MakeTabs (int count, bool inheritance=false)
string GetOnlyChildPath (string config_class_path, string class_path)
string GetBaseClassPath (string config_class_path, string class_path, string config_class)
string GetBaseClassPathCombined (string child_path, string base_class)
string GetBaseClassPathRecursive (string config_class_path, string class_path, string config_class)
bool ContainsFirstClass (string config_class_path, string class_path)
TStringArray GetConfigRecursive (string path, string name, string config_class_path, string config_class, local array< string > overridden, int depth=0, local bool check_base_class_of_class=false)
TStringArray GetConfig (string class_path, string filter_char)
TStringArray GetConfigVariables (string class_path)
TStringArray GetConfigHierarchy (string class_path)
void PluginDayZInfectedDebug ()
void ~PluginDayZInfectedDebug ()
void ToggleDebugWindowEvent ()
void ToggleDebugWindowSetMode (int pMode)
void CaptureFocus ()
void ReleaseFocus ()
void Show ()
void Hide ()
void ShowWidgets (bool show)
override void OnUpdate (float delta_time)
void CreateModuleWidgets ()
void DestroyModuleWidgets ()
void ShowCard (int pCard)
bool OnClick (Widget w, int x, int y, int button)
buttons clicks
bool OnChange (Widget w, int x, int y, bool finished)
void ResetValues ()
void SpawnNewInfectedEntity ()
protected void PossesInfected ()
void CommandHandler (DayZInfected infected)
void Tick ()
void InitAttacks ()
private void CleanupDebugShapes (array< Shape > shapesArr)
void TeleportAtCursor ()
Set Player position at his cursor position in the world.
void Teleport (PlayerBase player, vector position)
Teleport player at position.
void ToggleFreeCameraBackPos ()
Enable / Disable Free camera (Fly mod)
void ToggleFreeCamera ()
Enable / Disable Free camera (Fly mod) - disable of camera will teleport player at current free camera position.
bool IsEnabledFreeCamera ()
void PluginDeveloper ()
override void OnInit ()
void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx)
void PrintLogClient (string msg_log)
void SendServerLogToClient (string msg)
void OnRPCSyncSceneObject (ParamsReadContext ctx)
void OnRPCPluginDayzCreatureDebug (PlayerBase player, int rpc_type, ParamsReadContext ctx)
void HandleSetTime (PlayerBase player, ParamsReadContext ctx)
void HandlePresetSpawn (PlayerBase player, string presetName, EntityAI target)
void OnRPCServerLogRecieved (ParamsReadContext ctx)
void OnRPCClearInventory (PlayerBase player)
void OnRPCSpawnEntityOnCursorDir (PlayerBase player, ParamsReadContext ctx)
void OnRPCSpawnEntityOnGround (PlayerBase player, ParamsReadContext ctx)
void OnRPCSpawnEntityOnGroundPatternGrid (PlayerBase player, ParamsReadContext ctx)
void OnRPCSpawnEntity (PlayerBase player, ParamsReadContext ctx)
void OnSetFreeCameraEvent (PlayerBase player, FreeDebugCamera camera)
void OnSpawnErrorReport (string name)
void SetupSpawnedEntity (PlayerBase player, EntityAI entity, float health, float quantity=-1, bool special=false, string presetName="")
void SpawnEntityOnGroundPatternGrid (PlayerBase player, string item_name, int count, float health, float quantity, int rows, int columns, float gapRow=1, float gapColumn=1, bool special=false)
void SpawnItemOnCrosshair (notnull PlayerBase player, string itemName, float health, float quantity, float maxDist=100, bool allowFreeflight=false, bool special=false)
EntityAI SpawnEntityOnGroundPos (PlayerBase player, string item_name, float health, float quantity, vector pos, bool special=false)
spawns entity on exact position
EntityAI SpawnEntityOnCursorDir (PlayerBase player, string item_name, float quantity, float distance, float health=-1, bool special=false, string presetName="")
spawns entity in direction of cursor at specified distance
EntityAI SpawnEntityInInventory (EntityAI target, string className, float health, float quantity, bool special=false, string presetName="")
tries to spawn item somewhere in inventory
EntityAI SpawnEntityInPlayerInventory (PlayerBase player, string item_name, float health, float quantity, bool special=false, string presetName="")
EntityAI SpawnEntityAsAttachment (PlayerBase player, EntityAI parent, string att_name, float health, float quantity)
tries to spawn item as attachment
EntityAI SpawnFromClipboard ()
void ClearInventory (EntityAI entity)
void ToggleHelpScreen ()
void ToggleScriptConsole ()
void ToggleMissionLoader ()
private void ScriptHistoryNext ()
private void ScriptHistoryBack ()
private bool IsIngame ()
private bool IsInConsole ()
int QuickSortPartition (TStringArray arr, int left, int right)
void QuickSort (TStringArray arr, int left, int right)
void SortStringArray (TStringArray arr)
void ResetGUI ()
void SetDeveloperItemClient ()
void CheckInit ()
void Init ()
override void OnUpdate (float delta_time)
override void OnDestroy ()
vector CalculatePos ()
void CheckInit ()
void Init ()
override void OnUpdate (float delta_time)
void PluginDrawCheckerboard ()
void ~PluginDrawCheckerboard ()
void CreateWidgetOverlay ()
bool IsActive ()
bool IsEven (int num)
even or odd
void ShowWidgets (bool show)
void Show ()
void Hide ()
override void OnUpdate (float delta_time)
void SetWatching (bool enable)
bool GetWatching ()
void GatherPlayerInfo ()
void SendDebug ()
void OnDamageEvent (PlayerBase player, TotalDamageResult damageResult)
void OnRequestReceived (PlayerBase player, bool enable)
void OnRPC (ParamsReadContext ctx, PlayerBase player)
void PluginUniversalTemperatureSourceClient ()
override void OnInit ()
override void OnUpdate (float delta_time)
void InitWidgets ()
void DrawDebugs ()
protected void ProcessUniversalTemperatureSources ()
protected float CalcTemperatureFromTemperatureSource (notnull UTemperatureSourceDebug utsd)
void EnableWidgets (bool enable)
void UpdateStatWidgets ()
void UpdateStatWidget (int rowIndex, UTemperatureSourceDebug utsd)
void RequestUniversalTemperatureSources (PlayerBase player, int enable)
void PrintedDebug ()
void OnRPC (ParamsReadContext ctx)
void PluginUniversalTemperatureSourceServer ()
override void OnUpdate (float delta_time)
void GatherTemperatureSources (PlayerBase player)
void SendDebug ()
void OnRequestReceived (PlayerBase player, bool enable)
void OnRPC (ParamsReadContext ctx, PlayerBase player)
void PluginDeveloperSync ()
override void OnInit ()
void EnableUpdate (bool enable, int type, PlayerBase player)
void Update ()
void SetSystemInBitmask (PlayerBase player, int system_bit, bool state)
bool IsSetSystemInBitmask (PlayerBase player, int system_bit)
void RegisterPlayer (PlayerBase player)
bool IsPlayerRegistered (PlayerBase player)
void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx)
bool GetRPCUpdateState (ParamsReadContext ctx)
int GetRPCModifierID (ParamsReadContext ctx)
void GetRPCModifierLock (ParamsReadContext ctx, out int id, out bool lock)
void SendRPCStats (PlayerBase player)
void OnRPCStats (ParamsReadContext ctx)
void UpdateStatsLocal ()
void OnRPCStatSet (ParamsReadContext ctx, PlayerBase player)
void SendRPCLevels (PlayerBase player)
void OnRPCLevels (ParamsReadContext ctx)
void SendRPCMods (PlayerBase player)
void SendRPCModsDetail (PlayerBase player)
void OnRPCMods (ParamsReadContext ctx)
void OnRPCModsDetailed (ParamsReadContext ctx)
void RequestDetailedInfo (int id, notnull PlayerBase player)
void ActivateModifier (int id, PlayerBase player=NULL)
void DeactivateModifier (int id, PlayerBase player=NULL)
void LockModifier (int id, bool lock, PlayerBase player=NULL)
bool IsModifierLocked (int id, PlayerBase player=NULL)
void SendRPCTemp (PlayerBase player)
void OnRPCTemp (ParamsReadContext ctx, PlayerBase player)
void SendRPCAgents (PlayerBase player)
void OnRPCAgents (ParamsReadContext ctx)
void SendRPCStomach (PlayerBase player)
void OnRPCStomach (ParamsReadContext ctx)
void CaptureFocus ()
void ReleaseFocus ()
void ToggleFocus ()
void PluginFileHandler ()
void ~PluginFileHandler ()
override void OnInit ()
string GetFileName ()
void ClearFileNoSave ()
bool LoadFile ()
bool SaveFile ()
bool IsReadOnly ()
void AddText (string text)
void AddNewLineNoSave (string text)
TStringArray GetFileContent ()
void PluginHorticulture ()
void LoadFromCfg ()
string GetPlantType (Object obj)
float GetSurfaceFertility (string surface_type)
bool GiveWormsToPlayer (PlayerBase player, float chance)
PlantMaterialHealth GetPlantMaterial (string plant_type)
void PluginKeyBinding ()
override void OnInit ()
override void OnDestroy ()
void OnKeyPress (int key)
void OnKeyRelease (int key)
void OnMouseButtonPress (int button)
void OnMouseButtonRelease (int button)
void OnFrame ()
array< ref KeyBinding > GetKeyBindings ()
array< ref MouseBinding > GetMouseBindings ()
protected void RegisterKeyBind (int ui_id, int key_code1, int key_code2, string plugin_name, string fnc_name, string info_shortcut, string info_description)
protected void RegisterMouseBind (int ui_id, int mouse_button, int mouse_event, string plugin_name, string fnc_name, string info_shortcut, string info_description)
protected bool IsCurrentUIPageValid (int ui_page_request)
bool CheckMask (int source_mask, int target_mask)
protected void OnMouse (int event_id, int button)
protected MouseButtonInfo GetMouseButtonInfo (int button)
protected bool IsKeyPressed (int key)
void PluginMessageManager ()
void Broadcast (int index)
Broadcasts an empty message on a channel provided in the 'index' parameter.
void BroadcastInt (int index, int value)
Broadcasts a message on a channel provided in the 'index' parameter, passes the Int variable.
void BroadcastFloat (int index, float value)
void BroadcastString (int index, string value)
void BroadcastParam (int index, Param params)
Broadcasts a message on a channel provided in the 'index' parameter, passes the Param type object to the reciever.
void Subscribe (MessageReceiverBase receiver, int index)
Subscribes an object to listen to messages on a channel provided in the 'index' parameter.
void Unsubscribe (MessageReceiverBase receiver, int index)
void UnsubscribeAll (MessageReceiverBase receiver)
void PluginObjectsInteractionManager ()
bool IsFree (Object target)
void Lock (Object target)
void Release (Object target)
void Decay ()
void SwitchPermanentCrossHair (bool state)
void PluginPlayerStatus ()
void SetNotifier (int key, int index=9, string label="", int color=0xFFFFFFFF)
void DisplayTendency (int key, int tendency, int status=1)
void SetBadge (int key, int value)
void SetStamina (int value, int range)
void SetStance (int value)
bool Repair (PlayerBase player, ItemBase repair_kit, Object item, float specialty_weight, string damage_zone="", bool use_kit_qty=true)
void CalculateHealth (PlayerBase player, ItemBase kit, Object item, float specialty_weight, string damage_zone="", bool use_kit_qty=true)
bool CanRepair (ItemBase repair_kit, Object item, string damage_zone="")
private bool IsRepairValid (int repair_kit_type, int repairable_with_type)
private bool CanRepairToPristine (PlayerBase player)
Player can repair items to 100%; currently unused.
private bool CanBeRepairedToPristine (Object item)
Item can be repaired to 100%.
private float GetKitRepairCost (ItemBase repair_kit, Object item)
void PluginSceneManager ()
void ~PluginSceneManager ()
override void OnInit ()
override void OnDestroy ()
void OnMouseWheel (int wheel)
void OnUIEditorOpened ()
void OnUIEditorClosed ()
void Event_OnClick ()
void Event_OnClickMiddle ()
void Event_OnDrag ()
SceneObject Event_OnDoubleClick ()
void InitLoad ()
void RestoreSceneObjectsLinks ()
void ExecuteInitScripts ()
void EditorToggle ()
bool IsOpened ()
void SelectClassName (string class_name)
void FreeCameraControlEnable ()
void FreeCameraControlDisable ()
void DeleteSelectedObject ()
void SelectObject (SceneObject obj)
SceneObject GetSelectedSceneObject ()
void SelectedObjectDuplicate ()
void SelectedObjectSetRot (float dir)
void SelectedObjectSetPosX (float value)
void SelectedObjectSetPosY (float value)
void SelectedObjectSetPosZ (float value)
void SelectedObjectSetDamage (float value)
void SelectedObjectFocus ()
void SelectedObjectAddAttachment (string att_name)
void SelectedObjectRemoveAttachment (EntityAI e)
void LinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2)
void UnlinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2)
bool AreSceneObjectsLinked (SceneObject scene_object1, SceneObject scene_object2)
void SetDrawSelection (bool draw)
bool GetDrawSelection ()
void SetLoadPlayerPos (bool save)
bool GetLoadPlayerPos ()
void SetRotationAngle (int angle)
int GetRotationAngle ()
void SceneLoad (string scene_name)
void SceneUnload ()
void SceneSave ()
bool SceneCanDelete (string scene_name)
bool SceneDelete (string scene_name)
void SceneDuplicate (string scene_name)
void SceneRename (string scene_name, string new_name)
string SceneGetName ()
void SetWeather (float overcast, float rain, float fog, float wind_force)
void SetDate (int year, int month, int day, int hour, int minute)
void SelectAndFocusPlayerObject ()
void ExecuteEnforceScript (int index, SceneObject scene_object, string script)
void RulerToggle ()
bool IsRulerActivated ()
void RulerAddPoint ()
void RulerClearVisuals ()
void RulerDelete ()
SceneData GetLoadedScene ()
int GetSelectedSceneObjectIndex ()
array< ref SceneObject > GetSceneObjects ()
array< ref ScenePlayer > GetScenePlayers ()
array< ref SceneObject > GetSceneObjectsAll ()
SceneObject GetSceneObjectByIndex (int index)
SceneObject GetSceneObjectByEntity (EntityAI entity)
TStringArray GetSceneList ()
void DeleteSceneObject (SceneObject obj)
private void DeselectObject ()
protected void EditorUpdate ()
private void SceneEditorMenuCmdRefresh ()
private void SceneEditorMenuCmdPopup (string message)
private void SceneEditorMenuCmdSave ()
private bool IsMouseInScene ()
private void EditorUpdateRuler ()
private vector GetMousePositionInScene ()
override void OnInit ()
override void OnUpdate (float delta_time)
override void OnDestroy ()
void Show ()
void Hide ()
void OnGUITimer ()
void PluginTransmissionAgents ()
void RegisterAgent (AgentBase agent)
void ConstructSimpleAgentList ()
map< int, ref AgentBase > GetAgentList ()
map< int, string > GetSimpleAgentList ()
void RemoveAllAgents (EntityAI target)
protected float GetAgentTransferabilityIn (int agent_id)
bool GrowDuringAntibioticsAttack (int agent_id, PlayerBase player)
float GetAgentDieOffSpeedEx (int agent_id, PlayerBase player)
EStatLevels GetAgentPotencyEx (int agent_id, PlayerBase player)
float GetAgentInvasibilityEx (int agent_id, PlayerBase player)
float GetAgentAntiboticsResistance (int agent_id)
float GetAgentAntiboticsResistanceEx (int agent_id, PlayerBase player)
protected float GetAgentTransferabilityOut (int agent_id)
protected float GetAgentTransferabilityAirOut (int agent_id)
float GetAgentInvasibility (int agent_id)
float GetAgentDigestibility (int agent_id)
float GetDieOffSpeed (int agent_id)
EStatLevels GetPotency (int agent_id)
float TransmitAgentsEx (EntityAI source, EntityAI target, int pathway, int dose_size=1000, int agents=0)
void TransmitAgents (EntityAI source, EntityAI target, int pathway, int dose_size=1000)
protected void InjectAgentsWithoutPlayer (EntityAI target, int agents)
protected void InjectAgentsWithPlayer (EntityAI target, int agents, float protection, int dose_size, int inject_type)
will add agents to a given target, using chance of transmission and full dose size if chance succeeds
protected void InjectAgentsWithPlayerCount (EntityAI target, int agents, float protection, int dose_size, int inject_type)
will add agents to a given target, with no probability, but the dose size is modified by m_TransferabilityOut of the agent
protected float InjectAgentWithPlayerDose (EntityAI target, int agent, float protection, float dose_size, int inject_type)
will add agent to a given target
protected float GetProtectionLevel (int type, int slot, Man player)
protected float CalculateAgentsToTransmit (int agent_id, float protection, int dose_size, int inject_type)
protected bool DetermineChanceToTransmit (int agent_id, float protection, int inject_type)
void PluginVariables ()
void ~PluginVariables ()
void RegisterVariable (string name)
string GetName (int id)
int GetID (string name)
Static Private Member Functions
static int GetPlayerListTimer ()
static PluginCameraTools GetInstance ()
static PluginDeveloper GetInstance ()
static void SetDeveloperItemClientEx (notnull Object entity, bool getFocus=false)
static bool FileDuplicate (string source_name, string dest_name)
static bool FileDelete (string file)
static void FileRename (string source_name, string dest_name)
static PluginSceneManager GetInstance ()
static string GetNameByID (int agent_id)
static void RemoveAgent (EntityAI target, int agent_id)
static int GetAgentMaxCount (int agent_id)
static void BuildAgentArray (int agents, array< int > agents_out)
static float GetProtectionLevelEx (int type, int slot, Man player, bool consider_filter=true, int system=0)
Private Attributes
string m_PlayerName
string m_Pid
vector m_Position
string m_PlayerPrefix
string m_PlayerPrefix2
string m_Message
string m_DisplayName
string m_HitMessage
float m_Distance
PlayerBase m_Player
PlayerBase m_Source
string m_ItemInHands
string m_PosArray [3]
int m_DotIndex
PlayerStat< float > m_StatWater
PlayerStat< float > m_StatEnergy
BleedingSourcesManagerServer m_BleedMgr
protected int m_HitFilter
protected int m_PlacementFilter
protected int m_ActionsFilter
protected int m_PlayerListFilter
ref Timer m_Timer
autoptr array< Man > m_PlayerArray
const int TIMER_PLAYERLIST = GetPlayerListTimer()
int m_CurrentMode = 0
bool m_HasFocus = false
bool m_IsActive = false
Widget m_MainWnd
main controls
ButtonWidget m_SpawnEntityButton
ButtonWidget m_CardMovementButton
ButtonWidget m_CardFightButton
Widget m_CardMovementFrame
Widget m_CardFightFrame
TextWidget m_StatusText
XComboBoxWidget m_StanceCB
movement card
XComboBoxWidget m_MindStateCB
EditBoxWidget m_MovementSpeedEB
ButtonWidget m_StartTurnButton
XComboBoxWidget m_TurnTypeCB
EditBoxWidget m_TurnDirectionEB
XComboBoxWidget m_VaultingCB
ButtonWidget m_StartVaultButton
ButtonWidget m_KnucleOutButton
XComboBoxWidget m_CrawlingTypeCB
ButtonWidget m_StartCrawlingButton
EditBoxWidget m_HitDirEB
fight card
XComboBoxWidget m_HitTypeCB
XComboBoxWidget m_HitBodyPartCB
ButtonWidget m_StartHitButton
XComboBoxWidget m_DeathTypeCB
ButtonWidget m_StartDeathButton
XComboBoxWidget m_AttackTypeCB
XComboBoxWidget m_AttackDirCB
ButtonWidget m_StartAttackButton
DayZInfected m_ControlledInfected
controlled instance
bool m_CH_DoTurn = false
command handler values
bool m_CH_DoVault = false
bool m_CH_DoKnucleOut = false
bool m_CH_GoToCrawl = false
bool m_CH_DoHit = false
bool m_CH_StartDeath = false
bool m_CH_DoAttack = false
ref PluginDayZInfectedDebugUIHandler m_pUIHandler
ref array< ref PluginDayZInfectedDebugAttackDesc > m_AttackDescriptors = new array<ref PluginDayZInfectedDebugAttackDesc>
private ref array< Shape > m_DebugShapes = new array<Shape>()
ref Timer m_TickTimer
status refresh timer
protected bool m_IsWinHolding
protected int m_FeaturesMask
UIScriptedMenu m_ScriptConsole
PluginDeveloper m_ModuleDeveloper
PlayerBase m_Character
bool m_Initialized
vector m_cam_pos
vector m_character_pos
vector m_camera_dir
vector m_cameraTrans [4]
vector m_demoPos
vector m_demoRot
vector m_camera_orientation
const float FOV = 0.5236
ItemBase m_Ruler
private ref Widget m_MainWindow
private bool m_IsActive
ref set< PlayerBase > m_ClientList = new set<PlayerBase>
ref array< ref RemotePlayerStatDebug > m_PlayerDebugStats = new array<ref RemotePlayerStatDebug>
ref map< PlayerBase, ref RemotePlayerDamageDebug > m_PlayerDebugDamage = new map<PlayerBase, ref RemotePlayerDamageDebug>
float m_AccuTime
const int INTERVAL = 1
eRemoteDebugType m_DebugType
bool m_Watching
const int MAX_SIMULTANEOUS_UTS = 10
protected float m_UTSAverageTemperature
protected ref array< ref UTemperatureSourceDebug > m_UTemperatureSourceDebugs
protected ref Widget m_RootWidget [MAX_SIMULTANEOUS_UTS]
protected TextListboxWidget m_StatListWidgets [MAX_SIMULTANEOUS_UTS]
protected TextWidget m_HeaderWidget [MAX_SIMULTANEOUS_UTS]
protected PlayerBase m_Player
const float LOOKUP_RADIUS = 20
[s]
protected float m_AccuTime
[m]
protected ref set< PlayerBase > m_ClientList
int m_DetailedInfoRequested = 0
ref Timer m_UpdateTimer
ref map< PlayerBase, ref RegisterPlayerData > m_RegisteredPlayers
ref array< ref SyncedValue > m_PlayerStatsSynced
ref array< ref Param > m_PlayerStomachSynced
ref array< ref SyncedValueLevel > m_PlayerLevelsSynced
ref array< ref SyncedValueModifier > m_PlayerModsSynced
string m_PlayerModsDetailedSynced
string m_EnvironmentDebugMessage
ref array< ref SyncedValueAgent > m_PlayerAgentsSynced
bool m_StatsUpdateStatus
bool m_LevelsUpdateStatus
bool m_ModsUpdateStatus
bool m_AgentsUpdateStatus
bool m_StomachUpdateStatus
bool m_ReadOnly
int m_LineLimit
ref TStringArray m_FileContent
ref map< string, ref PlantMaterialHealth > m_PlantMaterials
protected const int CLICK_TIME = 200
protected const int DOUBLE_CLICK_TIME = 300
protected const int HOLD_CLICK_TIME_MIN = 300
protected ref array< ref KeyBinding > m_KeyBindings
protected ref array< ref MouseButtonInfo > m_MouseButtons
protected ref array< ref MouseBinding > m_MouseBindings
int channelsUsed = 0
ref array< ref MessageReceiverBase > channelList [NUM_OF_CHANNELS]
private ref array< Object > m_LockedObjects
private ref array< float > m_LockedObjectsDecay
private const float TIME_TO_FORCED_UNLOCK = 60
private const float TICK_RATE = 10
private ref Timer m_DecayTimer
private Hud m_Hud
ref multiMap< int, string > m_NotifiersLabel
ref multiMap< int, int > m_NotifiersIndexColor
private ref multiMap< int, string > m_NotifiersIcons
bool m_RulerActivated
ref array< vector > m_RulerPoints
ref array< Shape > m_RulerLines
ref array< Shape > m_RulerSpheres
protected PluginDeveloper m_ModuleDeveloper
protected PluginConfigScene m_ModuleConfigScene
protected PluginConfigDebugProfile m_ModuleConfigDebugProfile
protected float m_TimeLastClickRelease
protected float m_TimeLastClickPress
protected int m_PressedMouseID
protected bool m_IsDragging
protected ref array< Shape > m_ShapesSceneObjects
protected ref map< int, KeyBinding > m_KeyBindings
protected ref SceneData m_SceneData
protected SceneObject m_SelectedObject
protected string m_ClassBrowserSelected
protected bool m_IsOpen
ref SoundParams m_soundParams
ref SoundObjectBuilder m_soundBuilder
ref SoundObject m_soundObject
float fadeInVolume = 1.1
float fadeOutVolume = 0.9
AbstractWave m_wave
ref map< int, string > m_SimpleAgentList = new map<int, string>
bool m_IsConstructed = false
int m_Id
ref map< int, string > m_Variables
Static Private Attributes
static protected PluginCameraTools m_Instance
static protected bool m_IsOpen
static PluginKeyBinding instance
static string SCENE_DEFAULT_NAME = "default"
static string SCENE_SUFIX = "scene"
static PlayerBase PLAYER
static PluginSceneManager instance
static const int SCENE_EDITOR_CMD_REFRESH = 0
static const int SCENE_EDITOR_CMD_POPUP = 1
static const int SCENE_EDITOR_CMD_SAVE = 2
static ref map< int, ref AgentBase > m_AgentList = new map<int, ref AgentBase>
Detailed Description
Class PluginMessageManager provides some basic Message Distribution mechanics, if you get instance of this plugin class on your object, you can use its methods to broadcast messages.
Constructor & Destructor Documentation
PluginBase()
void PluginBase () private
~PluginBase()
void ~PluginBase () private
~PluginAdminLog()
void ~PluginAdminLog () inline private
~PluginDayZInfectedDebug()
void ~PluginDayZInfectedDebug () inline private
References DestroyModuleWidgets().
~PluginDrawCheckerboard()
void ~PluginDrawCheckerboard () inline private
~PluginFileHandler()
void ~PluginFileHandler () inline private
~PluginSceneManager()
void ~PluginSceneManager () inline private
~PluginVariables()
void ~PluginVariables () inline private
Member Function Documentation
ActivateModifier()
void ActivateModifier (int id, PlayerBase player = NULL) inline private
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
Referenced by OnRPC().
AddKeyframe()
void AddKeyframe () inline private
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnKeyPress().
AddNewLineNoSave()
void AddNewLineNoSave (string text) inline private
AddText()
void AddText (string text) inline private
AreSceneObjectsLinked()
bool AreSceneObjectsLinked (SceneObject scene_object1, SceneObject scene_object2) inline private
References SceneObject::IsLinkedWithSceneObject().
BleedingOut()
void BleedingOut (PlayerBase player) inline private
References GetPlayerPrefix(), and LogPrint().
Broadcast()
void Broadcast (int index) inline private
Broadcasts an empty message on a channel provided in the 'index' parameter.
References LayoutHolder::Count(), LayoutHolder::Get(), MessageReceiverBase::OnReceive(), and x.
BroadcastFloat()
void BroadcastFloat (int index, float value) inline private
References LayoutHolder::Count(), LayoutHolder::Get(), MessageReceiverBase::OnReceiveFloat(), and x.
BroadcastInt()
void BroadcastInt (int index, int value) inline private
Broadcasts a message on a channel provided in the 'index' parameter, passes the Int variable.
References LayoutHolder::Count(), LayoutHolder::Get(), MessageReceiverBase::OnReceiveInt(), and x.
BroadcastParam()
void BroadcastParam (int index, Param params) inline private
Broadcasts a message on a channel provided in the 'index' parameter, passes the Param type object to the reciever.
References LayoutHolder::Count(), LayoutHolder::Get(), and x.
BroadcastString()
void BroadcastString (int index, string value) inline private
References LayoutHolder::Count(), LayoutHolder::Get(), Print(), and x.
BuildAgentArray()
static void BuildAgentArray (int agents, array< int > agents_out) inline static private
References BIT_INT_SIZE.
CalcTemperatureFromTemperatureSource()
protected float CalcTemperatureFromTemperatureSource (notnull UTemperatureSourceDebug utsd) inline private
heat transfer through air to player (env temperature)
dist factor minimum should be at 0
References vector::Distance(), m_Player, and Math::Max().
Referenced by ProcessUniversalTemperatureSources().
CalculateAgentsToTransmit()
protected float CalculateAgentsToTransmit (int agent_id, float protection, int dose_size, int inject_type) inline private
References GetAgentTransferabilityAirOut(), GetAgentTransferabilityIn(), and GetAgentTransferabilityOut().
Referenced by InjectAgentsWithPlayerCount(), and InjectAgentWithPlayerDose().
CalculateHealth()
void CalculateHealth (PlayerBase player, ItemBase kit, Object item, float specialty_weight, string damage_zone = "", bool use_kit_qty = true) inline private
References CanBeRepairedToPristine(), CanRepairToPristine(), Class::CastTo(), Math::Clamp(), GetKitRepairCost(), and GameConstants::STATE_WORN.
Referenced by Repair().
CalculatePos()
vector CalculatePos () inline private
References Math3D::DirectionAndUpMatrix(), GetGame(), m_demoPos, Math3D::MatrixIdentity4(), vector::Multiply4(), CGame::SurfaceY(), and Vector().
Referenced by OnUpdate().
CanBeRepairedToPristine()
private bool CanBeRepairedToPristine (Object item) inline private
Item can be repaired to 100%.
Referenced by CalculateHealth(), and Repair().
CanRepair()
bool CanRepair (ItemBase repair_kit, Object item, string damage_zone = "") inline private
References IsRepairValid(), GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
CanRepairToPristine()
private bool CanRepairToPristine (PlayerBase player) inline private
Player can repair items to 100%; currently unused.
Referenced by CalculateHealth(), and Repair().
CaptureFocus() [1/2]
void CaptureFocus () inline private
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), m_HasFocus, and UIManager::ShowUICursor().
Referenced by ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), and ToggleDebugWindowSetMode().
CaptureFocus() [2/2]
void CaptureFocus () inline private
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), and UIManager::ShowUICursor().
CheckInit() [1/2]
void CheckInit () inline private
References Init(), Log(), m_Initialized, Print(), float::ToString(), and vector::ToString().
CheckInit() [2/2]
void CheckInit () inline private
References Init().
CheckMask()
bool CheckMask (int source_mask, int target_mask) inline private
CleanupDebugShapes()
private void CleanupDebugShapes (array< Shape > shapesArr) inline private
References Debug::RemoveShape().
Referenced by OnUpdate(), and ToggleDebugWindowSetMode().
ClearFileNoSave()
void ClearFileNoSave () inline private
ClearInventory()
void ClearInventory (EntityAI entity) inline private
References GetGame().
CommandHandler()
void CommandHandler (DayZInfected infected) inline private
ConstructSimpleAgentList()
void ConstructSimpleAgentList () inline private
Referenced by GetSimpleAgentList().
ContainsFirstClass()
bool ContainsFirstClass (string config_class_path, string class_path) inline private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetType(), ContainsFirstClass(), GetGame(), string::IndexOf(), string::Length(), name, and string::Substring().
Referenced by ContainsFirstClass(), and GetBaseClassPathRecursive().
CreateModuleWidgets()
void CreateModuleWidgets () inline private
main controls
movement card
fight card
fill some controls
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), InitAttacks(), m_MainWnd, m_pUIHandler, and ShowCard().
Referenced by PluginDayZInfectedDebug(), and PluginDayzPlayerDebug().
CreateWidgetOverlay()
void CreateWidgetOverlay () inline private
row counter
sets alpha level for even/odd child
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), and IsEven().
Referenced by PluginDrawCheckerboard().
CursorHide()
void CursorHide () inline private
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnHide().
CursorShow()
void CursorShow () inline private
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnShow().
DeactivateModifier()
void DeactivateModifier (int id, PlayerBase player = NULL) inline private
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
Referenced by OnRPC().
Decay()
void Decay () inline private
References TICK_RATE.
DeleteKeyframe()
void DeleteKeyframe () inline private
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnKeyPress().
DeleteSceneObject()
void DeleteSceneObject (SceneObject obj) inline private
References GetGame(), SceneObject::GetObject(), GetPlayer(), and SceneObject::UnlinkAll().
DeleteSelectedObject()
void DeleteSelectedObject () inline private
References SceneObject::IsPlayer().
DeselectObject()
private void DeselectObject () inline private
References m_SelectedObject.
DestroyModuleWidgets()
void DestroyModuleWidgets () inline private
References m_MainWnd.
Referenced by ~PluginDayZInfectedDebug(), and ~PluginDayzPlayerDebug().
DetermineChanceToTransmit()
protected bool DetermineChanceToTransmit (int agent_id, float protection, int inject_type) inline private
References GetAgentTransferabilityAirOut(), GetAgentTransferabilityIn(), GetAgentTransferabilityOut(), and Math::RandomFloat01().
Referenced by InjectAgentsWithPlayer().
DirectAdminLogPrint()
void DirectAdminLogPrint (string str) inline private
References LogPrint().
DisplayTendency()
void DisplayTendency (int key, int tendency, int status = 1) inline private
References Hud::DisplayNotifier(), GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
DrawDebugs()
void DrawDebugs () inline private
References DbgUI::Begin(), COLOR_BLUE_A, COLOR_GREEN_A, COLOR_RED_A, COLOR_YELLOW_A, Debug::DrawArrow(), Debug::DrawCylinder(), DbgUI::End(), m_Player, m_UTemperatureSourceDebugs, ProcessUniversalTemperatureSources(), and DbgUI::Text().
Referenced by OnUpdate().
EditorToggle()
void EditorToggle () inline private
References UIManager::Back(), UIManager::EnterScriptedMenu(), GetGame(), CGame::GetUIManager(), IsOpened(), and MENU_SCENE_EDITOR.
EditorUpdate()
protected void EditorUpdate () inline private
References SceneObject::EditorLineAdd(), SceneObject::EditorLineRemove(), SceneObject::EditorShapeAdd(), SceneObject::EditorShapeDeselect(), SceneObject::EditorShapeRemove(), SceneObject::EditorShapeSelect(), GetGame(), SceneObject::GetLinkedSceneObjects(), and IsOpened().
EditorUpdateRuler()
private void EditorUpdateRuler () inline private
References Debug::DrawLine(), and Debug::DrawSphere().
EnableUpdate()
void EnableUpdate (bool enable, int type, PlayerBase player) inline private
References IsPlayerRegistered(), m_UpdateTimer, RegisterPlayer(), SetSystemInBitmask(), and Timer::Stop().
Referenced by OnRPC(), and OnRPCTemp().
EnableWidgets()
void EnableWidgets (bool enable) inline private
References m_RootWidget, and MAX_SIMULTANEOUS_UTS.
Referenced by RequestPlayerInfo(), and RequestUniversalTemperatureSources().
Event_OnClick()
void Event_OnClick () inline private
References GetGame(), CGame::GetPointerDirection(), and DayZPhysics::RaycastRV().
Event_OnClickMiddle()
void Event_OnClickMiddle () inline private
References GetGame(), CGame::GetPointerDirection(), SceneObject::IsPlayer(), and DayZPhysics::RaycastRV().
Event_OnDoubleClick()
SceneObject Event_OnDoubleClick () inline private
References GetGame(), CGame::GetPointerDirection(), and DayZPhysics::RaycastRV().
Event_OnDrag()
void Event_OnDrag () inline private
References GetGame(), CGame::GetPointerDirection(), and DayZPhysics::RaycastRV().
ExecuteEnforceScript()
void ExecuteEnforceScript (int index, SceneObject scene_object, string script) inline private
References CGame::ExecuteEnforceScript(), GetGame(), and SceneObject::GetObject().
ExecuteInitScripts()
void ExecuteInitScripts () inline private
References SceneObject::GetInitScript().
FileDelete()
static bool FileDelete (string file) inline static private
References DeleteFile().
FileDuplicate()
static bool FileDuplicate (string source_name, string dest_name) inline static private
References CopyFile().
FileRename()
static void FileRename (string source_name, string dest_name) inline static private
FreeCameraControlDisable()
void FreeCameraControlDisable () inline private
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), UIManager::GetMenu(), CGame::GetUIManager(), UIScriptedMenu::OnShow(), and UIManager::ShowUICursor().
FreeCameraControlEnable()
void FreeCameraControlEnable () inline private
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), UIManager::GetMenu(), CGame::GetUIManager(), UIScriptedMenu::OnHide(), and UIManager::ShowUICursor().
GatherPlayerInfo()
void GatherPlayerInfo () inline private
References GetGame(), CGame::GetPlayers(), m_PlayerDebugStats, and RemotePlayerStatDebug().
Referenced by SendDebug().
GatherTemperatureSources()
void GatherTemperatureSources (PlayerBase player) inline private
References GetGame(), and CGame::GetObjectsAtPosition().
Referenced by SendDebug().
GetAgentAntiboticsResistance()
float GetAgentAntiboticsResistance (int agent_id) inline private
GetAgentAntiboticsResistanceEx()
float GetAgentAntiboticsResistanceEx (int agent_id, PlayerBase player) inline private
GetAgentDieOffSpeedEx()
float GetAgentDieOffSpeedEx (int agent_id, PlayerBase player) inline private
GetAgentDigestibility()
float GetAgentDigestibility (int agent_id) inline private
GetAgentInvasibility()
float GetAgentInvasibility (int agent_id) inline private
GetAgentInvasibilityEx()
float GetAgentInvasibilityEx (int agent_id, PlayerBase player) inline private
GetAgentList()
map< int, ref AgentBase > GetAgentList () inline private
References m_AgentList.
GetAgentMaxCount()
static int GetAgentMaxCount (int agent_id) inline static private
GetAgentPotencyEx()
EStatLevels GetAgentPotencyEx (int agent_id, PlayerBase player) inline private
GetAgentTransferabilityAirOut()
protected float GetAgentTransferabilityAirOut (int agent_id) inline private
Referenced by CalculateAgentsToTransmit(), and DetermineChanceToTransmit().
GetAgentTransferabilityIn()
protected float GetAgentTransferabilityIn (int agent_id) inline private
Referenced by CalculateAgentsToTransmit(), and DetermineChanceToTransmit().
GetAgentTransferabilityOut()
protected float GetAgentTransferabilityOut (int agent_id) inline private
Referenced by CalculateAgentsToTransmit(), and DetermineChanceToTransmit().
GetBaseClassPath()
string GetBaseClassPath (string config_class_path, string class_path, string config_class) inline private
References CGame::ConfigGetFullPath(), string::Get(), GetBaseClassPathRecursive(), GetGame(), GetOnlyChildPath(), and string::Length().
Referenced by GetConfigRecursive().
GetBaseClassPathCombined()
string GetBaseClassPathCombined (string child_path, string base_class) inline private
References string::IndexOfFrom(), and string::Substring().
Referenced by GetConfigRecursive().
GetBaseClassPathRecursive()
string GetBaseClassPathRecursive (string config_class_path, string class_path, string config_class) inline private
References CGame::ConfigGetFullPath(), ContainsFirstClass(), string::Get(), GetBaseClassPathRecursive(), and GetGame().
Referenced by GetBaseClassPath(), and GetBaseClassPathRecursive().
GetConfig()
TStringArray GetConfig (string class_path, string filter_char) inline private
References class_name, CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), string::Get(), GetConfigRecursive(), GetGame(), GetPlugin(), string::IndexOf(), string::Length(), MakeTabs(), string::Split(), string::Substring(), and string::ToLower().
Referenced by GetConfigHierarchy(), and GetConfigVariables().
GetConfigHierarchy()
TStringArray GetConfigHierarchy (string class_path) inline private
References GetConfig().
GetConfigRecursive()
TStringArray GetConfigRecursive (string path, string name, string config_class_path, string config_class, local array< string > overridden, int depth = 0, local bool check_base_class_of_class = false) inline private
References CGame::ConfigGetBaseName(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFullPath(), CGame::ConfigGetTextArray(), CGame::ConfigGetType(), GetBaseClassPath(), GetBaseClassPathCombined(), GetConfigRecursive(), GetGame(), string::Length(), MakeTabs(), name, path, string::Substring(), and string::ToLower().
Referenced by GetConfig(), and GetConfigRecursive().
GetConfigVariables()
TStringArray GetConfigVariables (string class_path) inline private
References GetConfig().
GetDieOffSpeed()
float GetDieOffSpeed (int agent_id) inline private
GetDrawSelection()
bool GetDrawSelection () inline private
GetFileContent()
TStringArray GetFileContent () inline private
GetFileName()
string GetFileName () inline private
References string::Empty.
GetHitMessage()
string GetHitMessage (TotalDamageResult damageResult, int component, string zone, string ammo) inline private
References component, TotalDamageResult::GetHighestDamage(), and float::ToString().
Referenced by PlayerHitBy().
GetID()
int GetID (string name) inline private
References name.
GetInstance() [1/3]
static PluginCameraTools GetInstance () inline static private
References m_Instance.
GetInstance() [2/3]
static PluginDeveloper GetInstance () inline static private
References GetPlugin().
GetInstance() [3/3]
static PluginSceneManager GetInstance () inline static private
References GetPlugin().
GetKeyBindings()
array< ref KeyBinding > GetKeyBindings () inline private
GetKitRepairCost()
private float GetKitRepairCost (ItemBase repair_kit, Object item) inline private
Referenced by CalculateHealth().
GetLoadedScene()
SceneData GetLoadedScene () inline private
GetLoadPlayerPos()
bool GetLoadPlayerPos () inline private
GetModuleName()
string GetModuleName () inline private
Referenced by GetModuleType(), and Log().
GetModuleType()
GetModuleType () inline private
References GetModuleName(), and string::ToType().
GetMouseBindings()
array< ref MouseBinding > GetMouseBindings () inline private
GetMouseButtonInfo()
protected MouseButtonInfo GetMouseButtonInfo (int button) inline private
References MouseButtonInfo::GetButtonID().
GetMousePositionInScene()
private vector GetMousePositionInScene () inline private
References GetGame(), CGame::GetPointerDirection(), and DayZPhysics::RaycastRV().
GetName()
string GetName (int id) inline private
References string::Get().
GetNameByID()
static string GetNameByID (int agent_id) inline static private
References string::Get().
GetOnlyChildPath()
string GetOnlyChildPath (string config_class_path, string class_path) inline private
References string::Length(), string::Substring(), and string::Trim().
Referenced by GetBaseClassPath().
GetPlantMaterial()
PlantMaterialHealth GetPlantMaterial (string plant_type) inline private
GetPlantType()
string GetPlantType (Object obj) inline private
References CGame::ConfigGetText(), and GetGame().
GetPlayerListTimer()
static int GetPlayerListTimer () inline static private
GetPlayerPrefix()
string GetPlayerPrefix (PlayerBase player, PlayerIdentity identity) inline private
References PlayerIdentityBase::GetId(), PlayerIdentityBase::GetName(), string::IndexOf(), m_Position, string::Substring(), and vector::ToString().
Referenced by BleedingOut(), OnContinouousAction(), OnPlacementComplete(), PlayerHitBy(), PlayerKilled(), PlayerList(), Suicide(), TotemFlagChange(), UnconStart(), and UnconStop().
GetPotency()
EStatLevels GetPotency (int agent_id) inline private
GetProtectionLevel()
protected float GetProtectionLevel (int type, int slot, Man player) inline private
References GetProtectionLevelEx().
Referenced by TransmitAgentsEx().
GetProtectionLevelEx()
static float GetProtectionLevelEx (int type, int slot, Man player, bool consider_filter = true, int system = 0) inline static private
Referenced by GetProtectionLevel().
GetRotationAngle()
int GetRotationAngle () inline private
GetRPCModifierID()
int GetRPCModifierID (ParamsReadContext ctx) inline private
References Serializer::Read().
Referenced by OnRPC().
GetRPCModifierLock()
void GetRPCModifierLock (ParamsReadContext ctx, out int id, out bool lock) inline private
References Serializer::Read().
Referenced by OnRPC().
GetRPCUpdateState()
bool GetRPCUpdateState (ParamsReadContext ctx) inline private
References Serializer::Read().
Referenced by OnRPC(), and OnRPCTemp().
GetSceneList()
TStringArray GetSceneList () inline private
GetSceneObjectByEntity()
SceneObject GetSceneObjectByEntity (EntityAI entity) inline private
References SceneObject::GetObject().
GetSceneObjectByIndex()
SceneObject GetSceneObjectByIndex (int index) inline private
GetSceneObjects()
array< ref SceneObject > GetSceneObjects () inline private
GetSceneObjectsAll()
array< ref SceneObject > GetSceneObjectsAll () inline private
GetScenePlayers()
array< ref ScenePlayer > GetScenePlayers () inline private
GetSelectedSceneObject()
SceneObject GetSelectedSceneObject () inline private
References m_SelectedObject.
GetSelectedSceneObjectIndex()
int GetSelectedSceneObjectIndex () inline private
GetSimpleAgentList()
map< int, string > GetSimpleAgentList () inline private
References ConstructSimpleAgentList(), and m_SimpleAgentList.
GetSurfaceFertility()
float GetSurfaceFertility (string surface_type) inline private
GetWatching()
bool GetWatching () inline private
References m_Watching.
Referenced by OnDamageEvent().
GiveWormsToPlayer()
bool GiveWormsToPlayer (PlayerBase player, float chance) inline private
References Math::RandomFloat01().
GrowDuringAntibioticsAttack()
bool GrowDuringAntibioticsAttack (int agent_id, PlayerBase player) inline private
HandlePresetSpawn()
void HandlePresetSpawn (PlayerBase player, string presetName, EntityAI target) inline private
References class_name.
Referenced by OnRPC().
HandleSetTime()
void HandleSetTime (PlayerBase player, ParamsReadContext ctx) inline private
References GetGame(), CGame::GetWorld(), Serializer::Read(), and World::SetDate().
Referenced by OnRPC().
Hide() [1/3]
void Hide () inline private
References GetUApi(), m_IsActive, m_TickTimer, ShowWidgets(), and UAInputAPI::UpdateControls().
Referenced by SetDebugShowMode(), ToggleDebugWindowEventOld(), ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), and ToggleDebugWindowSetMode().
Hide() [2/3]
void Hide () inline private
References m_IsActive, and ShowWidgets().
Hide() [3/3]
void Hide () inline private
References m_TickTimer.
Init() [1/2]
void Init () inline private
References GetGame(), and m_Initialized.
Referenced by CheckInit().
Init() [2/2]
void Init () inline private
References GetGame(), and m_Initialized.
InitAttacks()
void InitAttacks () inline private
References PluginDayZInfectedDebugAttackDesc().
Referenced by CreateModuleWidgets().
InitLoad()
void InitLoad () inline private
References GetGame(), GetPlayer(), and PLAYER.
InitWidgets()
void InitWidgets () inline private
References WorkspaceWidget::CreateWidgets(), FindAnyWidget(), GetGame(), CGame::GetWorkspace(), m_RootWidget, m_StatListWidgets, and MAX_SIMULTANEOUS_UTS.
Referenced by OnInit(), and OnInit().
InjectAgentsWithoutPlayer()
protected void InjectAgentsWithoutPlayer (EntityAI target, int agents) inline private
Referenced by TransmitAgentsEx().
InjectAgentsWithPlayer()
protected void InjectAgentsWithPlayer (EntityAI target, int agents, float protection, int dose_size, int inject_type) inline private
will add agents to a given target, using chance of transmission and full dose size if chance succeeds
References DetermineChanceToTransmit(), Math::GetNthBitSet(), Math::GetNumberOfSetBits(), and Math::Pow().
Referenced by TransmitAgentsEx().
InjectAgentsWithPlayerCount()
protected void InjectAgentsWithPlayerCount (EntityAI target, int agents, float protection, int dose_size, int inject_type) inline private
will add agents to a given target, with no probability, but the dose size is modified by m_TransferabilityOut of the agent
References CalculateAgentsToTransmit(), Math::GetNthBitSet(), Math::GetNumberOfSetBits(), and Math::Pow().
Referenced by TransmitAgentsEx().
InjectAgentWithPlayerDose()
protected float InjectAgentWithPlayerDose (EntityAI target, int agent, float protection, float dose_size, int inject_type) inline private
will add agent to a given target
References CalculateAgentsToTransmit().
Referenced by TransmitAgentsEx().
IsActive()
bool IsActive () inline private
References m_IsActive.
IsCurrentUIPageValid()
protected bool IsCurrentUIPageValid (int ui_page_request) inline private
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), MENU_ANY, and MENU_NONE.
IsEnabledFreeCamera()
bool IsEnabledFreeCamera () inline private
References DeveloperFreeCamera::IsFreeCameraEnabled().
IsEven()
bool IsEven (int num) inline private
even or odd
Referenced by CreateWidgetOverlay().
IsFree()
bool IsFree (Object target) inline private
Referenced by Lock().
IsInConsole()
private bool IsInConsole () inline private
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and MENU_SCRIPTCONSOLE.
IsIngame()
private bool IsIngame () inline private
References GetGame(), UIManager::GetMenu(), and CGame::GetUIManager().
IsKeyPressed()
protected bool IsKeyPressed (int key) inline private
References KeyState().
IsModifierLocked()
bool IsModifierLocked (int id, PlayerBase player = NULL) inline private
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
IsMouseInScene()
private bool IsMouseInScene () inline private
References GetWidgetUnderCursor().
IsOpened()
bool IsOpened () inline private
IsPlayerRegistered()
bool IsPlayerRegistered (PlayerBase player) inline private
Referenced by EnableUpdate(), IsSetSystemInBitmask(), RegisterPlayer(), and SetSystemInBitmask().
IsReadOnly()
bool IsReadOnly () inline private
IsRepairValid()
private bool IsRepairValid (int repair_kit_type, int repairable_with_type) inline private
Referenced by CanRepair().
IsRulerActivated()
bool IsRulerActivated () inline private
IsSetSystemInBitmask()
bool IsSetSystemInBitmask (PlayerBase player, int system_bit) inline private
References IsPlayerRegistered().
Referenced by RequestDetailedInfo().
LinkSceneObjects()
void LinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2) inline private
References SceneObject::LinkSceneObject().
LoadFile()
bool LoadFile () inline private
References CloseFile(), FGets(), PluginFileHandler::GetFileName(), and OpenFile().
LoadFromCfg()
void LoadFromCfg () inline private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), GetGame(), PlantMaterialHealth::m_HealthyMat, PlantMaterialHealth::m_HealthyTex, PlantMaterialHealth::m_InfestedMat, and PlantMaterialHealth::m_InfestedTex.
Referenced by PluginHorticulture(), and PluginLifespan().
Lock()
void Lock (Object target) inline private
References IsFree().
LockModifier()
void LockModifier (int id, bool lock, PlayerBase player = NULL) inline private
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
Referenced by OnRPC().
Log()
void Log (string msg, string label) inline private
References GetModuleName(), and Debug::Log().
Referenced by CheckInit().
LogPrint()
void LogPrint (string message) inline private
References CGame::AdminLog(), and GetGame().
Referenced by BleedingOut(), DirectAdminLogPrint(), OnContinouousAction(), OnPlacementComplete(), PlayerHitBy(), PlayerKilled(), PlayerList(), Suicide(), TotemFlagChange(), UnconStart(), and UnconStop().
MakeTabs()
string MakeTabs (int count, bool inheritance = false) inline private
Referenced by GetConfig(), and GetConfigRecursive().
OnChange()
bool OnChange (Widget w, int x, int y, bool finished) inline private
OnClick()
bool OnClick (Widget w, int x, int y, int button) inline private
buttons clicks
References ResetValues(), ShowCard(), and SpawnNewInfectedEntity().
OnContinouousAction()
void OnContinouousAction (ActionData action_data) inline private
References GetPlayerPrefix(), LogPrint(), ActionData::m_Action, m_ActionsFilter, and ActionData::m_Player.
OnDamageEvent()
void OnDamageEvent (PlayerBase player, TotalDamageResult damageResult) inline private
References RemotePlayerDamageDebug::AddDamage(), TotalDamageResult::GetDamage(), GetWatching(), and m_PlayerDebugDamage.
OnDestroy() [1/5]
void OnDestroy () private
Referenced by PluginManager::~PluginManager().
OnDestroy() [2/5]
override void OnDestroy () inline private
References g_Game.
OnDestroy() [3/5]
override void OnDestroy () inline private
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), and ScriptInvoker::Remove().
OnDestroy() [4/5]
override void OnDestroy () inline private
OnDestroy() [5/5]
override void OnDestroy () inline private
References m_TickTimer.
OnFrame()
void OnFrame () inline private
References MouseButtonInfo::GetButtonID(), GetGame(), CGame::GetTime(), MouseButtonInfo::GetTimeLastPress(), MouseButtonInfo::IsButtonDown(), and MB_EVENT_DRAG.
OnGUITimer()
void OnGUITimer () inline private
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::Button(), DbgUI::End(), DbgUI::EndCleanupScope(), GetGame(), GetPlayer(), GetPosition, CGame::GetSoundScene(), DbgUI::InputFloat(), DbgUI::InputText(), DbgUI::PopID(), DbgUI::PushID_Int(), DbgUI::PushID_Str(), DbgUI::SameLine(), and DbgUI::Text().
OnInit() [1/9]
void OnInit () private
OnInit() [2/9]
override void OnInit () inline private
References m_Instance.
OnInit() [3/9]
override void OnInit () inline private
References DeveloperFreeCamera::OnInit().
OnInit() [4/9]
override void OnInit () inline private
References InitWidgets().
OnInit() [5/9]
override void OnInit () inline private
References CALL_CATEGORY_GAMEPLAY, GetGame(), and m_UpdateTimer.
OnInit() [6/9]
override void OnInit () inline private
OnInit() [7/9]
override void OnInit () inline private
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), MB_EVENT_CLICK, MB_EVENT_DOUBLECLICK, MB_EVENT_DRAG, MB_EVENT_PRESS, MB_EVENT_RELEASE, MENU_ANY, MENU_CAMERA_TOOLS, MENU_NONE, MENU_SCENE_EDITOR, and MENU_SCRIPTCONSOLE.
OnInit() [8/9]
override void OnInit () inline private
References GetPlugin().
OnInit() [9/9]
override void OnInit () inline private
References m_TickTimer.
OnKeyPress()
void OnKeyPress (int key) inline private
References ScriptModule::CallFunction(), CGame::GameScript, KeyBinding::GetCallbackFunction(), KeyBinding::GetCallbackTarget(), GetGame(), KeyBinding::GetKey1(), KeyBinding::GetKey2(), GetPlugin(), KeyBinding::GetUIMenuID(), and string::ToType().
OnKeyRelease()
void OnKeyRelease (int key) inline private
OnMouse()
protected void OnMouse (int event_id, int button) inline private
References ScriptModule::CallFunction(), CGame::GameScript, MouseBinding::GetButtonID(), MouseBinding::GetCallbackFunction(), MouseBinding::GetCallbackTarget(), GetGame(), MouseBinding::GetMouseEvent(), GetPlugin(), MouseBinding::GetUIMenuID(), and string::ToType().
OnMouseButtonPress()
void OnMouseButtonPress (int button) inline private
References MB_EVENT_PRESS, and MouseButtonInfo::Press().
OnMouseButtonRelease()
void OnMouseButtonRelease (int button) inline private
References GetGame(), CGame::GetTime(), MouseButtonInfo::GetTimeLastPress(), MouseButtonInfo::GetTimeLastRelease(), MB_EVENT_CLICK, MB_EVENT_DOUBLECLICK, MB_EVENT_RELEASE, and MouseButtonInfo::Release().
OnMouseWheel()
void OnMouseWheel (int wheel) inline private
OnPlacementComplete()
void OnPlacementComplete (Man player, ItemBase item) inline private
References GetPlayerPrefix(), and LogPrint().
OnRequestReceived() [1/2]
void OnRequestReceived (PlayerBase player, bool enable) inline private
References SetWatching().
Referenced by OnRPC().
OnRequestReceived() [2/2]
void OnRequestReceived (PlayerBase player, bool enable) inline private
OnRPC() [1/5]
void OnRPC (ParamsReadContext ctx) inline private
References Serializer::Read().
OnRPC() [2/5]
void OnRPC (ParamsReadContext ctx, PlayerBase player) inline private
References OnRequestReceived(), and Serializer::Read().
OnRPC() [3/5]
void OnRPC (ParamsReadContext ctx, PlayerBase player) inline private
References OnRequestReceived(), and Serializer::Read().
OnRPC() [4/5]
void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline private
References HandlePresetSpawn(), HandleSetTime(), DeveloperTeleport::OnRPC(), OnRPCClearInventory(), OnRPCPluginDayzCreatureDebug(), OnRPCServerLogRecieved(), OnRPCSpawnEntity(), OnRPCSpawnEntityOnCursorDir(), OnRPCSpawnEntityOnGround(), OnRPCSpawnEntityOnGroundPatternGrid(), OnRPCSyncSceneObject(), and Serializer::Read().
Referenced by ManBase::OnRPC().
OnRPC() [5/5]
void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline private
References ActivateModifier(), DeactivateModifier(), EnableUpdate(), GetGame(), GetRPCModifierID(), GetRPCModifierLock(), GetRPCUpdateState(), LockModifier(), OnRPCAgents(), OnRPCLevels(), OnRPCMods(), OnRPCModsDetailed(), OnRPCStats(), OnRPCStatSet(), OnRPCStomach(), OnRPCTemp(), and RequestDetailedInfo().
OnRPCAgents()
void OnRPCAgents (ParamsReadContext ctx) inline private
References Serializer::Read(), and SyncedValueAgent().
Referenced by OnRPC().
OnRPCClearInventory()
void OnRPCClearInventory (PlayerBase player) inline private
References ClearInventory().
Referenced by OnRPC().
OnRPCLevels()
void OnRPCLevels (ParamsReadContext ctx) inline private
References Serializer::Read(), and SyncedValueLevel().
Referenced by OnRPC().
OnRPCMods()
void OnRPCMods (ParamsReadContext ctx) inline private
References int, and Serializer::Read().
Referenced by OnRPC().
OnRPCModsDetailed()
void OnRPCModsDetailed (ParamsReadContext ctx) inline private
References Serializer::Read().
Referenced by OnRPC().
OnRPCPluginDayzCreatureDebug()
void OnRPCPluginDayzCreatureDebug (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline private
References GetPlugin(), and PluginDayZCreatureAIDebug().
Referenced by OnRPC().
OnRPCServerLogRecieved()
void OnRPCServerLogRecieved (ParamsReadContext ctx) inline private
References Serializer::Read(), and Debug::ReceivedLogMessageFromServer().
Referenced by OnRPC().
OnRPCSpawnEntity()
void OnRPCSpawnEntity (PlayerBase player, ParamsReadContext ctx) inline private
References Serializer::Read(), and SpawnEntityInInventory().
Referenced by OnRPC().
OnRPCSpawnEntityOnCursorDir()
void OnRPCSpawnEntityOnCursorDir (PlayerBase player, ParamsReadContext ctx) inline private
References Serializer::Read(), and SpawnEntityOnCursorDir().
Referenced by OnRPC().
OnRPCSpawnEntityOnGround()
void OnRPCSpawnEntityOnGround (PlayerBase player, ParamsReadContext ctx) inline private
References Serializer::Read(), and SpawnEntityOnGroundPos().
Referenced by OnRPC().
OnRPCSpawnEntityOnGroundPatternGrid()
void OnRPCSpawnEntityOnGroundPatternGrid (PlayerBase player, ParamsReadContext ctx) inline private
References Serializer::Read(), and SpawnEntityOnGroundPatternGrid().
Referenced by OnRPC().
OnRPCStats()
void OnRPCStats (ParamsReadContext ctx) inline private
References Serializer::Read().
Referenced by OnRPC().
OnRPCStatSet()
void OnRPCStatSet (ParamsReadContext ctx, PlayerBase player) inline private
References Count, Get(), and Serializer::Read().
Referenced by OnRPC().
OnRPCStomach()
void OnRPCStomach (ParamsReadContext ctx) inline private
References Serializer::Read().
Referenced by OnRPC().
OnRPCSyncSceneObject()
void OnRPCSyncSceneObject (ParamsReadContext ctx) inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallByName(), CGame::GetCallQueue(), GetGame(), GetPlugin(), SceneData::GetSceneObjectByEntityAI(), and Serializer::Read().
Referenced by OnRPC().
OnRPCTemp()
void OnRPCTemp (ParamsReadContext ctx, PlayerBase player) inline private
References EnableUpdate(), GetGame(), GetRPCUpdateState(), CachedObjectsParams::PARAM1_STRING, and Serializer::Read().
Referenced by OnRPC().
OnSetFreeCameraEvent()
void OnSetFreeCameraEvent (PlayerBase player, FreeDebugCamera camera) inline private
References DeveloperFreeCamera::OnSetFreeCameraEvent().
OnSpawnErrorReport()
void OnSpawnErrorReport (string name) inline private
References name, and PrintString().
Referenced by SpawnEntityAsAttachment(), SpawnEntityInPlayerInventory(), SpawnEntityOnCursorDir(), and SpawnEntityOnGroundPos().
OnUIEditorClosed()
void OnUIEditorClosed () inline private
OnUIEditorOpened()
void OnUIEditorOpened () inline private
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, DeveloperFreeCamera::EnableFreeCameraSceneEditor(), CGame::GetCallQueue(), GetGame(), and GetPlayer().
OnUpdate() [1/8]
void OnUpdate (float delta_time) private
Referenced by PluginManager::MainOnUpdate().
OnUpdate() [2/8]
override void OnUpdate (float delta_time) inline private
References CleanupDebugShapes(), Debug::DrawSphere(), and m_IsActive.
OnUpdate() [3/8]
override void OnUpdate (float delta_time) inline private
References Math::Atan2(), CalculatePos(), m_Initialized, vector::Normalize(), and Math::RAD2DEG.
OnUpdate() [4/8]
override void OnUpdate (float delta_time) inline private
References m_Initialized, and vector::Normalize().
OnUpdate() [5/8]
override void OnUpdate (float delta_time) inline private
References SendDebug().
OnUpdate() [6/8]
override void OnUpdate (float delta_time) inline private
References DrawDebugs(), m_Player, and UpdateStatWidgets().
OnUpdate() [7/8]
override void OnUpdate (float delta_time) inline private
References SendDebug().
OnUpdate() [8/8]
override void OnUpdate (float delta_time) inline private
PlayerHitBy()
void PlayerHitBy (TotalDamageResult damageResult, int damageType, PlayerBase player, EntityAI source, int component, string dmgZone, string ammo) inline private
References component, DayZPlayerImplementFallDamage(), vector::Distance(), TotalDamageResult::GetDamage(), GetHitMessage(), GetPlayerPrefix(), EntityAI::IsMeleeWeapon(), and LogPrint().
PlayerKilled()
void PlayerKilled (PlayerBase player, Object source) inline private
References vector::Distance(), string::Get(), GetPlayerPrefix(), LogPrint(), and string::ToString().
PlayerList()
void PlayerList () inline private
References GetGame(), GetPlayerPrefix(), CGame::GetPlayers(), LogPrint(), m_Player, and m_PlayerArray.
PlayPause()
void PlayPause () inline private
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnKeyPress().
PluginAdminLog()
void PluginAdminLog () inline private
References GetGame(), m_ActionsFilter, m_Timer, and CGame::ServerConfigGetInt().
PluginConfigViewer()
void PluginConfigViewer () inline private
PluginDayZInfectedDebug()
void PluginDayZInfectedDebug () inline private
References CreateModuleWidgets().
PluginDeveloper()
void PluginDeveloper () inline private
PluginDeveloperSync()
void PluginDeveloperSync () inline private
PluginDrawCheckerboard()
void PluginDrawCheckerboard () inline private
References CreateWidgetOverlay().
PluginFileHandler()
void PluginFileHandler () inline private
PluginHorticulture()
void PluginHorticulture () inline private
References LoadFromCfg().
PluginKeyBinding()
void PluginKeyBinding () inline private
PluginMessageManager()
void PluginMessageManager () inline private
References NUM_OF_CHANNELS.
PluginObjectsInteractionManager()
void PluginObjectsInteractionManager () inline private
References m_DecayTimer.
PluginPlayerStatus()
void PluginPlayerStatus () inline private
References NTFKEY_BACTERIA, NTFKEY_BLEEDISH, NTFKEY_FEVERISH, NTFKEY_FRACTURE, NTFKEY_HUNGRY, NTFKEY_SICK, and NTFKEY_THIRSTY.
PluginSceneManager()
void PluginSceneManager () inline private
PluginTransmissionAgents()
void PluginTransmissionAgents () inline private
References RegisterAgent().
PluginUniversalTemperatureSourceClient()
void PluginUniversalTemperatureSourceClient () inline private
PluginUniversalTemperatureSourceServer()
void PluginUniversalTemperatureSourceServer () inline private
PluginVariables()
void PluginVariables () inline private
References m_Id, and RegisterVariable().
PossesInfected()
protected void PossesInfected () inline private
References ResetValues().
PrintedDebug()
void PrintedDebug () inline private
References m_UTemperatureSourceDebugs, and PrintString().
PrintLogClient()
void PrintLogClient (string msg_log) inline private
References CALL_ID_SCR_CNSL_ADD_PRINT, CallMethod(), g_Game, and MENU_SCRIPTCONSOLE.
ProcessUniversalTemperatureSources()
protected void ProcessUniversalTemperatureSources () inline private
next temp source is too far (not cleaned on server, like in Environment, client need to know about all sources in MAXRANGE)
References CalcTemperatureFromTemperatureSource(), vector::DistanceSq(), m_Player, m_UTemperatureSourceDebugs, and Math::SqrFloat().
Referenced by DrawDebugs().
QuickSort()
void QuickSort (TStringArray arr, int left, int right) inline private
References QuickSort(), and QuickSortPartition().
Referenced by QuickSort(), and SortStringArray().
QuickSortPartition()
int QuickSortPartition (TStringArray arr, int left, int right) inline private
Referenced by QuickSort().
RegisterAgent()
void RegisterAgent (AgentBase agent) inline private
Referenced by PluginTransmissionAgents().
RegisterKeyBind()
protected void RegisterKeyBind (int ui_id, int key_code1, int key_code2, string plugin_name, string fnc_name, string info_shortcut, string info_description) inline private
RegisterMouseBind()
protected void RegisterMouseBind (int ui_id, int mouse_button, int mouse_event, string plugin_name, string fnc_name, string info_shortcut, string info_description) inline private
RegisterPlayer()
void RegisterPlayer (PlayerBase player) inline private
References IsPlayerRegistered(), and RegisterPlayerData().
Referenced by EnableUpdate().
RegisterVariable()
void RegisterVariable (string name) inline private
References m_Id, and name.
Referenced by PluginVariables().
Release()
void Release (Object target) inline private
ReleaseFocus() [1/2]
void ReleaseFocus () inline private
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), m_HasFocus, and UIManager::ShowUICursor().
Referenced by ToggleDebugWindowEventOld(), ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), ToggleDebugWindowSetMode(), and ~PluginDayzPlayerDebug().
ReleaseFocus() [2/2]
void ReleaseFocus () inline private
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), and UIManager::ShowUICursor().
RemoveAgent()
static void RemoveAgent (EntityAI target, int agent_id) inline static private
RemoveAllAgents()
void RemoveAllAgents (EntityAI target) inline private
Repair()
bool Repair (PlayerBase player, ItemBase repair_kit, Object item, float specialty_weight, string damage_zone = "", bool use_kit_qty = true) inline private
References CalculateHealth(), CanBeRepairedToPristine(), CanRepairToPristine(), Debug::Log(), GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
RequestDetailedInfo()
void RequestDetailedInfo (int id, notnull PlayerBase player) inline private
References Math::AbsInt(), IsSetSystemInBitmask(), and SetSystemInBitmask().
Referenced by OnRPC().
RequestUniversalTemperatureSources()
void RequestUniversalTemperatureSources (PlayerBase player, int enable) inline private
References EnableWidgets(), m_Player, ScriptRPC::Send(), and Serializer::Write().
ResetGUI()
void ResetGUI () inline private
References GetGame(), CGame::GetMission(), and Mission::ResetGUI().
ResetValues()
void ResetValues () inline private
References m_MainWnd.
Referenced by OnClick(), and PossesInfected().
RestoreSceneObjectsLinks()
void RestoreSceneObjectsLinks () inline private
References SceneObject::LinkSceneObject(), and SceneObject::m_LinkedSceneObjectsIndices.
RulerAddPoint()
void RulerAddPoint () inline private
RulerClearVisuals()
void RulerClearVisuals () inline private
RulerDelete()
void RulerDelete () inline private
RulerToggle()
void RulerToggle () inline private
Save()
void Save () inline private
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnKeyPress().
SaveFile()
bool SaveFile () inline private
References CloseFile(), FPrintln(), PluginFileHandler::GetFileName(), and OpenFile().
SceneCanDelete()
bool SceneCanDelete (string scene_name) inline private
SceneDelete()
bool SceneDelete (string scene_name) inline private
SceneDuplicate()
void SceneDuplicate (string scene_name) inline private
SceneEditorMenuCmdPopup()
private void SceneEditorMenuCmdPopup (string message) inline private
References CALL_ID_SCENE_EDITOR_COMMAND, and CallMethod().
SceneEditorMenuCmdRefresh()
private void SceneEditorMenuCmdRefresh () inline private
References CALL_ID_SCENE_EDITOR_COMMAND, and CallMethod().
SceneEditorMenuCmdSave()
private void SceneEditorMenuCmdSave () inline private
References CALL_ID_SCENE_EDITOR_COMMAND, and CallMethod().
SceneGetName()
string SceneGetName () inline private
References STRING_EMPTY.
SceneLoad()
void SceneLoad (string scene_name) inline private
References GetGame().
SceneRename()
void SceneRename (string scene_name, string new_name) inline private
SceneSave()
void SceneSave () inline private
SceneUnload()
void SceneUnload () inline private
ScriptHistoryBack()
private void ScriptHistoryBack () inline private
References CALL_ID_SCR_CNSL_HISTORY_BACK, CallMethod(), g_Game, and MENU_SCRIPTCONSOLE.
ScriptHistoryNext()
private void ScriptHistoryNext () inline private
References CALL_ID_SCR_CNSL_HISTORY_NEXT, CallMethod(), g_Game, and MENU_SCRIPTCONSOLE.
SelectAndFocusPlayerObject()
void SelectAndFocusPlayerObject () inline private
References GetGame(), and GetPlayer().
SelectClassName()
void SelectClassName (string class_name) inline private
References class_name.
SelectedObjectAddAttachment()
void SelectedObjectAddAttachment (string att_name) inline private
SelectedObjectDuplicate()
void SelectedObjectDuplicate () inline private
References SceneObject::AddAttachment(), SceneObject::GetAttachments(), SceneObject::GetObject(), SceneObject::GetPosition(), SceneObject::GetRotation(), SceneObject::GetTypeName(), PLAYER, SceneObject::SetRotation(), and Vector().
SelectedObjectFocus()
void SelectedObjectFocus () inline private
References SceneObject::GetPosition(), SceneObject::GetSize(), and vector::Normalize().
SelectedObjectRemoveAttachment()
void SelectedObjectRemoveAttachment (EntityAI e) inline private
SelectedObjectSetDamage()
void SelectedObjectSetDamage (float value) inline private
References Math::Clamp(), SceneObject::GetObject(), and SceneObject::SetHealth().
SelectedObjectSetPosX()
void SelectedObjectSetPosX (float value) inline private
References SceneObject::GetPosition(), and SceneObject::SetPosition().
SelectedObjectSetPosY()
void SelectedObjectSetPosY (float value) inline private
References SceneObject::GetPosition(), and SceneObject::SetPosition().
SelectedObjectSetPosZ()
void SelectedObjectSetPosZ (float value) inline private
References SceneObject::GetPosition(), and SceneObject::SetPosition().
SelectedObjectSetRot()
void SelectedObjectSetRot (float dir) inline private
SelectObject()
void SelectObject (SceneObject obj) inline private
References m_SelectedObject.
SendDebug() [1/2]
void SendDebug () inline private
References GatherPlayerInfo(), m_PlayerDebugDamage, m_PlayerDebugDamage, m_PlayerDebugStats, ScriptRPC::Send(), and Serializer::Write().
Referenced by OnUpdate().
SendDebug() [2/2]
void SendDebug () inline private
References GatherTemperatureSources(), m_ClientList, ScriptRPC::Send(), and Serializer::Write().
SendRPCAgents()
void SendRPCAgents (PlayerBase player) inline private
References GetDayZGame(), and GetGame().
Referenced by Update().
SendRPCLevels()
void SendRPCLevels (PlayerBase player) inline private
References GetDayZGame().
Referenced by Update().
SendRPCMods()
void SendRPCMods (PlayerBase player) inline private
References GetDayZGame(), ModifiersManager(), and name.
Referenced by Update().
SendRPCModsDetail()
void SendRPCModsDetail (PlayerBase player) inline private
References GetDayZGame(), and ModifiersManager().
Referenced by Update().
SendRPCStats()
void SendRPCStats (PlayerBase player) inline private
References Count, Get(), and GetDayZGame().
Referenced by Update().
SendRPCStomach()
void SendRPCStomach (PlayerBase player) inline private
References GetDayZGame().
Referenced by Update().
SendRPCTemp()
void SendRPCTemp (PlayerBase player) inline private
References GetDayZGame(), and CachedObjectsParams::PARAM1_STRING.
Referenced by Update().
SendServerLogToClient()
void SendServerLogToClient (string msg) inline private
References GetGame(), and CGame::GetPlayers().
SetBadge()
void SetBadge (int key, int value) inline private
References Hud::DisplayBadge(), GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
SetDate()
void SetDate (int year, int month, int day, int hour, int minute) inline private
SetDeveloperItemClient()
void SetDeveloperItemClient () inline private
References ActionTarget, GetGame(), GetPlayer(), and SetDeveloperItemClientEx().
SetDeveloperItemClientEx()
static void SetDeveloperItemClientEx (notnull Object entity, bool getFocus = false) inline static private
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), GetPlayer(), GetPlugin(), CGame::GetUIManager(), PluginItemDiagnostic(), CGame::RPCSingleParam(), and UIManager::ShowUICursor().
Referenced by SetDeveloperItemClient().
SetDrawSelection()
void SetDrawSelection (bool draw) inline private
SetLoadPlayerPos()
void SetLoadPlayerPos (bool save) inline private
SetNotifier()
void SetNotifier (int key, int index = 9, string label = "", int color = 0xFFFFFFFF) inline private
SetRotationAngle()
void SetRotationAngle (int angle) inline private
SetStamina()
void SetStamina (int value, int range) inline private
References Math::Clamp(), GetGame(), Mission::GetHud(), CGame::GetMission(), mission, and Hud::SetStamina().
SetStance()
void SetStance (int value) inline private
References Hud::DisplayStance(), GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
SetSystemInBitmask()
void SetSystemInBitmask (PlayerBase player, int system_bit, bool state) inline private
References IsPlayerRegistered().
Referenced by EnableUpdate(), and RequestDetailedInfo().
SetupSpawnedEntity()
void SetupSpawnedEntity (PlayerBase player, EntityAI entity, float health, float quantity = -1, bool special = false, string presetName = "") inline private
References GetGame(), CGame::GetSurfaceOrientation(), and SetupSpawnedItem().
Referenced by SpawnEntityOnCursorDir(), and SpawnEntityOnGroundPos().
SetWatching()
void SetWatching (bool enable) inline private
Referenced by OnRequestReceived().
SetWeather()
void SetWeather (float overcast, float rain, float fog, float wind_force) inline private
Show() [1/3]
void Show () inline private
References UAInputAPI::ActivateExclude(), GetUApi(), m_IsActive, m_TickTimer, ShowWidgets(), and UAInputAPI::UpdateControls().
Referenced by SetDebugShowMode(), ToggleDebugWindowEventOld(), ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), and ToggleDebugWindowSetMode().
Show() [2/3]
void Show () inline private
References m_IsActive, and ShowWidgets().
Show() [3/3]
void Show () inline private
References m_TickTimer.
ShowCard()
void ShowCard (int pCard) inline private
Referenced by CreateModuleWidgets(), CreateModuleWidgets(), and OnClick().
ShowWidgets() [1/2]
void ShowWidgets (bool show) inline private
References m_MainWnd.
Referenced by Hide(), Hide(), Show(), and Show().
ShowWidgets() [2/2]
void ShowWidgets (bool show) inline private
SortStringArray()
void SortStringArray (TStringArray arr) inline private
References QuickSort().
SpawnEntityAsAttachment()
SpawnEntityAsAttachment (PlayerBase player, EntityAI parent, string att_name, float health, float quantity) inline private
tries to spawn item as attachment
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
Returns
entity if ok, null otherwise
References GameInventory::CreateInInventory(), GetGame(), OnSpawnErrorReport(), and SetupSpawnedItem().
SpawnEntityInInventory()
SpawnEntityInInventory (EntityAI target, string className, float health, float quantity, bool special = false, string presetName = "") inline private
tries to spawn item somewhere in inventory
SpawnEntityInInventory queries future parent about free inventory location of the future item
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
Returns
entity if ok, null otherwise
References ECE_IN_INVENTORY, GetGame(), CGame::GetPlayer(), GetPlayer(), RF_DEFAULT, SetupSpawnedItem(), and SpawnEntityInPlayerInventory().
Referenced by OnRPCSpawnEntity().
SpawnEntityInPlayerInventory()
EntityAI SpawnEntityInPlayerInventory (PlayerBase player, string item_name, float health, float quantity, bool special = false, string presetName = "") inline private
References ECE_IN_INVENTORY, GetGame(), InventoryLocation::GetParent(), InventoryLocation::GetSlot(), OnSpawnErrorReport(), RF_DEFAULT, SetupSpawnedItem(), and SpawnEntityOnGroundPos().
Referenced by SpawnEntityInInventory().
SpawnEntityOnCursorDir()
SpawnEntityOnCursorDir (PlayerBase player, string item_name, float quantity, float distance, float health = -1, bool special = false, string presetName = "") inline private
spawns entity in direction of cursor at specified distance
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
[in] distance distance of the item from player
Returns
entity if ok, null otherwise
References GetGame(), EntityAI::IsBuilding(), OnSpawnErrorReport(), and SetupSpawnedEntity().
Referenced by OnRPCSpawnEntityOnCursorDir(), and SpawnFromClipboard().
SpawnEntityOnGroundPatternGrid()
void SpawnEntityOnGroundPatternGrid (PlayerBase player, string item_name, int count, float health, float quantity, int rows, int columns, float gapRow = 1, float gapColumn = 1, bool special = false) inline private
References GetGame(), vector::Perpend(), and SpawnEntityOnGroundPos().
Referenced by OnRPCSpawnEntityOnGroundPatternGrid().
SpawnEntityOnGroundPos()
SpawnEntityOnGroundPos (PlayerBase player, string item_name, float health, float quantity, vector pos, bool special = false) inline private
spawns entity on exact position
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
[in] pos position where to spawn
Returns
entity if ok, null otherwise
References GetGame(), OnSpawnErrorReport(), and SetupSpawnedEntity().
Referenced by OnRPCSpawnEntityOnGround(), SpawnEntityInPlayerInventory(), SpawnEntityOnGroundPatternGrid(), and SpawnItemOnCrosshair().
SpawnFromClipboard()
EntityAI SpawnFromClipboard () inline private
References string::Contains(), CGame::CopyFromClipboard(), GetGame(), UIManager::GetMenu(), GetPlayer(), CGame::GetUIManager(), DeveloperFreeCamera::IsFreeCameraEnabled(), SpawnEntityOnCursorDir(), SpawnItemOnCrosshair(), string::Split(), and string::Trim().
SpawnItemOnCrosshair()
void SpawnItemOnCrosshair (notnull PlayerBase player, string itemName, float health, float quantity, float maxDist = 100, bool allowFreeflight = false, bool special = false) inline private
References CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), DayZPhysics::RayCastBullet(), SpawnEntityOnGroundPos(), and vector::Zero.
Referenced by SpawnFromClipboard().
SpawnNewInfectedEntity()
void SpawnNewInfectedEntity () inline private
References ECE_EQUIP_ATTACHMENTS, ECE_INITAI, ECE_PLACE_ON_SURFACE, GetGame(), GetPlayer(), and GetPosition.
Referenced by OnClick().
Subscribe()
void Subscribe (MessageReceiverBase receiver, int index) inline private
Subscribes an object to listen to messages on a channel provided in the 'index' parameter.
Suicide()
void Suicide (PlayerBase player) inline private
References GetPlayerPrefix(), and LogPrint().
SwitchPermanentCrossHair()
void SwitchPermanentCrossHair (bool state) inline private
References GetGame(), Mission::GetHud(), CGame::GetMission(), m_Hud, and Hud::SetPermanentCrossHair().
Teleport()
void Teleport (PlayerBase player, vector position) inline private
Teleport player at position.
References DeveloperTeleport::SetPlayerPosition().
TeleportAtCursor()
void TeleportAtCursor () inline private
Set Player position at his cursor position in the world.
References DeveloperTeleport::TeleportAtCursorEx().
Tick()
void Tick () inline private
ToggleCameraTools()
void ToggleCameraTools () inline private
References UIManager::Back(), UIManager::EnterScriptedMenu(), GetGame(), CGame::GetUIManager(), and MENU_CAMERA_TOOLS.
ToggleDebugWindowEvent()
void ToggleDebugWindowEvent () inline private
References m_CurrentMode, and ToggleDebugWindowSetMode().
ToggleDebugWindowSetMode()
void ToggleDebugWindowSetMode (int pMode) inline private
References CaptureFocus(), CleanupDebugShapes(), Hide(), ReleaseFocus(), and Show().
Referenced by ToggleDebugWindowEvent(), and ToggleDebugWindowEvent().
ToggleFocus()
void ToggleFocus () inline private
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), GetInput(), CGame::GetUIManager(), Input::ResetGameFocus(), and UIManager::ShowUICursor().
ToggleFreeCamera()
void ToggleFreeCamera () inline private
Enable / Disable Free camera (Fly mod) - disable of camera will teleport player at current free camera position.
References DeveloperFreeCamera::FreeCameraToggle(), GetGame(), and GetPlayer().
ToggleFreeCameraBackPos()
void ToggleFreeCameraBackPos () inline private
Enable / Disable Free camera (Fly mod)
References DeveloperFreeCamera::FreeCameraToggle(), GetGame(), and GetPlayer().
ToggleHelpScreen()
void ToggleHelpScreen () inline private
References g_Game, and MENU_HELP_SCREEN.
ToggleMissionLoader()
void ToggleMissionLoader () inline private
References g_Game, and GUI_WINDOW_MISSION_LOADER.
ToggleScriptConsole()
void ToggleScriptConsole () inline private
References Mission::AddActiveInputExcludes(), g_Game, GetGame(), CGame::GetMission(), GetPlayer(), MENU_SCRIPTCONSOLE, and Mission::RemoveActiveInputExcludes().
TotemFlagChange()
void TotemFlagChange (bool top, notnull PlayerBase player, notnull EntityAI totem) inline private
References GetPlayerPrefix(), LogPrint(), and m_ActionsFilter.
TransmitAgents()
void TransmitAgents (EntityAI source, EntityAI target, int pathway, int dose_size = 1000) inline private
References TransmitAgentsEx().
TransmitAgentsEx()
float TransmitAgentsEx (EntityAI source, EntityAI target, int pathway, int dose_size = 1000, int agents = 0) inline private
References AGT_AIRBOURNE_BIOLOGICAL, AGT_AIRBOURNE_CHEMICAL, AGT_INV_IN, AGT_INV_OUT, AGT_ITEM_TO_FLESH, AGT_TRANSFER_COPY, AGT_UACTION_CONSUME, AGT_UACTION_TO_ITEM, AGT_UACTION_TO_PLAYER, AGT_UACTION_TOUCH, AGT_WATER_POND, DEF_BIOLOGICAL, DEF_CHEMICAL, GetProtectionLevel(), InjectAgentsWithoutPlayer(), InjectAgentsWithPlayer(), InjectAgentsWithPlayerCount(), InjectAgentWithPlayerDose(), and Math::Max().
Referenced by TransmitAgents().
UnconStart()
void UnconStart (PlayerBase player) inline private
References GetPlayerPrefix(), and LogPrint().
UnconStop()
void UnconStop (PlayerBase player) inline private
References GetPlayerPrefix(), and LogPrint().
UnlinkSceneObjects()
void UnlinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2) inline private
References SceneObject::UnlinkSceneObject().
Unsubscribe()
void Unsubscribe (MessageReceiverBase receiver, int index) inline private
UnsubscribeAll()
void UnsubscribeAll (MessageReceiverBase receiver) inline private
References channelsUsed.
Update()
void Update () inline private
!!!! Highly suspect
References GetDayZGame(), SendRPCAgents(), SendRPCLevels(), SendRPCMods(), SendRPCModsDetail(), SendRPCStats(), SendRPCStomach(), and SendRPCTemp().
UpdateStatsLocal()
void UpdateStatsLocal () inline private
References Count, Get(), GetDayZGame(), and GetPlayer().
UpdateStatWidget()
void UpdateStatWidget (int rowIndex, UTemperatureSourceDebug utsd) inline private
References vector::Distance(), m_Player, m_StatListWidgets, and float::ToString().
Referenced by UpdateStatWidgets().
UpdateStatWidgets()
void UpdateStatWidgets () inline private
References GetGame(), CGame::GetScreenPos(), m_RootWidget, MAX_SIMULTANEOUS_UTS, and UpdateStatWidget().
Referenced by OnUpdate().
Field Documentation
channelList
ref array<ref MessageReceiverBase> channelList[NUM_OF_CHANNELS] private
channelsUsed
int channelsUsed = 0 private
Referenced by UnsubscribeAll().
CLICK_TIME
protected const int CLICK_TIME = 200 private
DOUBLE_CLICK_TIME
protected const int DOUBLE_CLICK_TIME = 300 private
fadeInVolume
float fadeInVolume = 1.1 private
fadeOutVolume
float fadeOutVolume = 0.9 private
FOV
const float FOV = 0.5236 private
HOLD_CLICK_TIME_MIN
protected const int HOLD_CLICK_TIME_MIN = 300 private
instance [1/2]
PluginKeyBinding instance static private
instance [2/2]
PluginSceneManager instance static private
INTERVAL
const int INTERVAL = 1 private
LOOKUP_RADIUS
const float LOOKUP_RADIUS = 20 private
[s]
m_AccuTime [1/2]
float m_AccuTime private
m_AccuTime [2/2]
protected float m_AccuTime private
[m]
m_ActionsFilter
protected int m_ActionsFilter private
m_AgentList
ref map<int, ref AgentBase> m_AgentList = new map<int, ref AgentBase> static private
Referenced by GetAgentList().
m_AgentsUpdateStatus
bool m_AgentsUpdateStatus private
m_AttackDescriptors
ref array<ref PluginDayZInfectedDebugAttackDesc> m_AttackDescriptors = new array<ref PluginDayZInfectedDebugAttackDesc> private
m_AttackDirCB
XComboBoxWidget m_AttackDirCB private
m_AttackTypeCB
XComboBoxWidget m_AttackTypeCB private
m_BleedMgr
BleedingSourcesManagerServer m_BleedMgr private
m_cam_pos
vector m_cam_pos private
m_camera_dir
vector m_camera_dir private
m_camera_orientation
vector m_camera_orientation private
m_cameraTrans
vector m_cameraTrans[4] private
m_CardFightButton
ButtonWidget m_CardFightButton private
m_CardFightFrame
Widget m_CardFightFrame private
m_CardMovementButton
ButtonWidget m_CardMovementButton private
m_CardMovementFrame
Widget m_CardMovementFrame private
m_CH_DoAttack
bool m_CH_DoAttack = false private
m_CH_DoHit
bool m_CH_DoHit = false private
m_CH_DoKnucleOut
bool m_CH_DoKnucleOut = false private
m_CH_DoTurn
bool m_CH_DoTurn = false private
command handler values
m_CH_DoVault
bool m_CH_DoVault = false private
m_CH_GoToCrawl
bool m_CH_GoToCrawl = false private
m_CH_StartDeath
bool m_CH_StartDeath = false private
m_Character
PlayerBase m_Character private
m_character_pos
vector m_character_pos private
m_ClassBrowserSelected
protected string m_ClassBrowserSelected private
m_ClientList [1/2]
ref set<PlayerBase> m_ClientList = new set<PlayerBase> private
Referenced by SendDebug().
m_ClientList [2/2]
protected ref set<PlayerBase> m_ClientList private
m_ControlledInfected
DayZInfected m_ControlledInfected private
controlled instance
m_CrawlingTypeCB
XComboBoxWidget m_CrawlingTypeCB private
m_CurrentMode
int m_CurrentMode = 0 private
m_DeathTypeCB
XComboBoxWidget m_DeathTypeCB private
m_DebugShapes
private ref array<Shape> m_DebugShapes = new array<Shape>() private
m_DebugType
eRemoteDebugType m_DebugType private
m_DecayTimer
private ref Timer m_DecayTimer private
m_demoPos
vector m_demoPos private
Referenced by CalculatePos().
m_demoRot
vector m_demoRot private
m_DetailedInfoRequested
int m_DetailedInfoRequested = 0 private
m_DisplayName
string m_DisplayName private
m_Distance
float m_Distance private
m_DotIndex
int m_DotIndex private
m_EnvironmentDebugMessage
string m_EnvironmentDebugMessage private
m_FeaturesMask
protected int m_FeaturesMask private
m_FileContent
ref TStringArray m_FileContent private
m_HasFocus
bool m_HasFocus = false private
m_HeaderWidget
protected TextWidget m_HeaderWidget[MAX_SIMULTANEOUS_UTS] private
m_HitBodyPartCB
XComboBoxWidget m_HitBodyPartCB private
m_HitDirEB
EditBoxWidget m_HitDirEB private
fight card
m_HitFilter
protected int m_HitFilter private
m_HitMessage
string m_HitMessage private
m_HitTypeCB
XComboBoxWidget m_HitTypeCB private
m_Hud
private Hud m_Hud private
m_Id
int m_Id private
m_Initialized
bool m_Initialized private
m_Instance
protected PluginCameraTools m_Instance static private
m_IsActive [1/2]
bool m_IsActive = false private
Referenced by IsActive(), and IsActive().
m_IsActive [2/2]
private bool m_IsActive private
m_IsConstructed
bool m_IsConstructed = false private
m_IsDragging
protected bool m_IsDragging private
m_IsOpen [1/2]
protected bool m_IsOpen static private
m_IsOpen [2/2]
protected bool m_IsOpen private
m_IsWinHolding
protected bool m_IsWinHolding private
m_ItemInHands
string m_ItemInHands private
m_KeyBindings [1/2]
protected ref array<ref KeyBinding> m_KeyBindings private
m_KeyBindings [2/2]
protected ref map<int, KeyBinding> m_KeyBindings private
m_KnucleOutButton
ButtonWidget m_KnucleOutButton private
m_LevelsUpdateStatus
bool m_LevelsUpdateStatus private
m_LineLimit
int m_LineLimit private
m_LockedObjects
private ref array<Object> m_LockedObjects private
m_LockedObjectsDecay
private ref array<float> m_LockedObjectsDecay private
m_MainWindow
private ref Widget m_MainWindow private
m_MainWnd
Widget m_MainWnd private
main controls
Referenced by DestroyModuleWidgets(), and DestroyModuleWidgets().
m_Message
string m_Message private
m_MindStateCB
XComboBoxWidget m_MindStateCB private
m_ModsUpdateStatus
bool m_ModsUpdateStatus private
m_ModuleConfigDebugProfile
protected PluginConfigDebugProfile m_ModuleConfigDebugProfile private
m_ModuleConfigScene
protected PluginConfigScene m_ModuleConfigScene private
m_ModuleDeveloper [1/2]
PluginDeveloper m_ModuleDeveloper private
m_ModuleDeveloper [2/2]
protected PluginDeveloper m_ModuleDeveloper private
m_MouseBindings
protected ref array<ref MouseBinding> m_MouseBindings private
m_MouseButtons
protected ref array<ref MouseButtonInfo> m_MouseButtons private
m_MovementSpeedEB
EditBoxWidget m_MovementSpeedEB private
m_NotifiersIcons
private ref multiMap<int, string> m_NotifiersIcons private
m_NotifiersIndexColor
ref multiMap<int, int> m_NotifiersIndexColor private
m_NotifiersLabel
ref multiMap<int, string> m_NotifiersLabel private
m_Pid
string m_Pid private
m_PlacementFilter
protected int m_PlacementFilter private
m_PlantMaterials
ref map<string, ref PlantMaterialHealth> m_PlantMaterials private
m_Player [1/2]
PlayerBase m_Player private
m_Player [2/2]
protected PlayerBase m_Player private
m_PlayerAgentsSynced
ref array<ref SyncedValueAgent> m_PlayerAgentsSynced private
m_PlayerArray
autoptr array<Man> m_PlayerArray private
Referenced by PlayerList().
m_PlayerDebugDamage
ref map<PlayerBase, ref RemotePlayerDamageDebug> m_PlayerDebugDamage = new map<PlayerBase, ref RemotePlayerDamageDebug> private
Referenced by SendDebug().
m_PlayerDebugStats
ref array<ref RemotePlayerStatDebug> m_PlayerDebugStats = new array<ref RemotePlayerStatDebug> private
m_PlayerLevelsSynced
ref array<ref SyncedValueLevel> m_PlayerLevelsSynced private
m_PlayerListFilter
protected int m_PlayerListFilter private
m_PlayerModsDetailedSynced
string m_PlayerModsDetailedSynced private
m_PlayerModsSynced
ref array<ref SyncedValueModifier> m_PlayerModsSynced private
m_PlayerName
string m_PlayerName private
m_PlayerPrefix
string m_PlayerPrefix private
m_PlayerPrefix2
string m_PlayerPrefix2 private
m_PlayerStatsSynced
ref array<ref SyncedValue> m_PlayerStatsSynced private
m_PlayerStomachSynced
ref array<ref Param> m_PlayerStomachSynced private
m_PosArray
string m_PosArray[3] private
m_Position
vector m_Position private
m_PressedMouseID
protected int m_PressedMouseID private
m_pUIHandler
ref PluginDayZInfectedDebugUIHandler m_pUIHandler private
m_ReadOnly
bool m_ReadOnly private
m_RegisteredPlayers
ref map<PlayerBase, ref RegisterPlayerData> m_RegisteredPlayers private
m_RootWidget
protected ref Widget m_RootWidget[MAX_SIMULTANEOUS_UTS] private
m_Ruler
ItemBase m_Ruler private
m_RulerActivated
bool m_RulerActivated private
m_RulerLines
ref array<Shape> m_RulerLines private
m_RulerPoints
ref array<vector> m_RulerPoints private
m_RulerSpheres
ref array<Shape> m_RulerSpheres private
m_SceneData
protected ref SceneData m_SceneData private
m_ScriptConsole
UIScriptedMenu m_ScriptConsole private
m_SelectedObject
protected SceneObject m_SelectedObject private
m_ShapesSceneObjects
protected ref array<Shape> m_ShapesSceneObjects private
m_SimpleAgentList
ref map<int, string> m_SimpleAgentList = new map<int, string> private
Referenced by GetSimpleAgentList().
m_soundBuilder
ref SoundObjectBuilder m_soundBuilder private
m_soundObject
ref SoundObject m_soundObject private
m_soundParams
ref SoundParams m_soundParams private
m_Source
PlayerBase m_Source private
m_SpawnEntityButton
ButtonWidget m_SpawnEntityButton private
m_StanceCB
XComboBoxWidget m_StanceCB private
movement card
m_StartAttackButton
ButtonWidget m_StartAttackButton private
m_StartCrawlingButton
ButtonWidget m_StartCrawlingButton private
m_StartDeathButton
ButtonWidget m_StartDeathButton private
m_StartHitButton
ButtonWidget m_StartHitButton private
m_StartTurnButton
ButtonWidget m_StartTurnButton private
m_StartVaultButton
ButtonWidget m_StartVaultButton private
m_StatEnergy
PlayerStat<float> m_StatEnergy private
m_StatListWidgets
protected TextListboxWidget m_StatListWidgets[MAX_SIMULTANEOUS_UTS] private
m_StatsUpdateStatus
bool m_StatsUpdateStatus private
m_StatusText
TextWidget m_StatusText private
m_StatWater
PlayerStat<float> m_StatWater private
m_StomachUpdateStatus
bool m_StomachUpdateStatus private
m_TickTimer
ref Timer m_TickTimer private
status refresh timer
m_TimeLastClickPress
protected float m_TimeLastClickPress private
m_TimeLastClickRelease
protected float m_TimeLastClickRelease private
m_Timer
ref Timer m_Timer private
m_TurnDirectionEB
EditBoxWidget m_TurnDirectionEB private
m_TurnTypeCB
XComboBoxWidget m_TurnTypeCB private
m_UpdateTimer
ref Timer m_UpdateTimer private
m_UTemperatureSourceDebugs
protected ref array< ref UTemperatureSourceDebug > m_UTemperatureSourceDebugs private
Referenced by DrawDebugs(), PrintedDebug(), and ProcessUniversalTemperatureSources().
m_UTSAverageTemperature
protected float m_UTSAverageTemperature private
m_Variables
ref map<int, string> m_Variables private
m_VaultingCB
XComboBoxWidget m_VaultingCB private
m_Watching
bool m_Watching private
Referenced by GetWatching().
m_wave
AbstractWave m_wave private
MAX_SIMULTANEOUS_UTS
const int MAX_SIMULTANEOUS_UTS = 10 private
Referenced by EnableWidgets(), InitWidgets(), and UpdateStatWidgets().
PLAYER
PlayerBase PLAYER static private
SCENE_DEFAULT_NAME
string SCENE_DEFAULT_NAME = "default" static private
SCENE_EDITOR_CMD_POPUP
const int SCENE_EDITOR_CMD_POPUP = 1 static private
SCENE_EDITOR_CMD_REFRESH
const int SCENE_EDITOR_CMD_REFRESH = 0 static private
SCENE_EDITOR_CMD_SAVE
const int SCENE_EDITOR_CMD_SAVE = 2 static private
SCENE_SUFIX
string SCENE_SUFIX = "scene" static private
TICK_RATE
private const float TICK_RATE = 10 private
Referenced by Decay().
TIME_TO_FORCED_UNLOCK
private const float TIME_TO_FORCED_UNLOCK = 60 private
TIMER_PLAYERLIST
const int TIMER_PLAYERLIST = GetPlayerListTimer() private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Plugins/PluginBase.c
P:/scripts/4_World/Plugins/PluginBase/PluginAdminLog.c
P:/scripts/4_World/Plugins/PluginBase/PluginCameraTools.c
P:/scripts/4_World/Plugins/PluginBase/PluginDayZInfectedDebug.c
P:/scripts/4_World/Plugins/PluginBase/PluginDeveloper.c
P:/scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginCharPlacement.c
P:/scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginDoorRuler.c
P:/scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginDrawCheckerboard.c
P:/scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginRemotePlayerDebugServer.c
P:/scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginUniversalTemperatureSourceClient.c
P:/scripts/4_World/Plugins/PluginBase/PluginDeveloper/PluginUniversalTemperatureSourceServer.c
P:/scripts/4_World/Plugins/PluginBase/PluginDeveloperSync.c
P:/scripts/4_World/Plugins/PluginBase/PluginFileHandler.c
P:/scripts/4_World/Plugins/PluginBase/PluginHorticulture.c
P:/scripts/4_World/Plugins/PluginBase/PluginKeyBinding.c
P:/scripts/4_World/Plugins/PluginBase/PluginMessageManager.c
P:/scripts/4_World/Plugins/PluginBase/PluginObjectsInteractionManager.c
P:/scripts/4_World/Plugins/PluginBase/PluginPermanentCrossHair.c
P:/scripts/4_World/Plugins/PluginBase/PluginPlayerStatus.c
P:/scripts/4_World/Plugins/PluginBase/PluginSceneManager.c
P:/scripts/4_World/Plugins/PluginBase/PluginSoundDebug.c
P:/scripts/4_World/Plugins/PluginBase/PluginTransmissionAgents.c
P:/scripts/4_World/Plugins/PluginBase/PluginVariables.c
P:/scripts/4_World/Plugins/PluginBase/PluginConfigViewer.c
P:/scripts/4_World/Plugins/PluginBase/PluginRepairing.c