DayZ Scripts: FireplaceIndoor Class Reference
FireplaceIndoor Class Reference
Private Member Functions
void FireplaceIndoor ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void SetFirePointIndex (int fire_point_index)
void SetSmokePointPosition (vector smoke_point_pos)
override protected vector GetSmokeEffectPosition ()
override void ParticleSmallSmokeStart ()
override void ParticleNormalSmokeStart ()
override bool IsFireplaceIndoor ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override bool CanPutInCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanPutIntoHands (EntityAI parent)
override bool CanRemoveFromHands (EntityAI player)
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool IsIgnited ()
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
Static Private Member Functions
static int GetFirePointIndex (string action_selection)
static bool CanPlaceFireplaceInSelectedSpot (Object building, int fire_point_index, out vector fire_point_pos_world, out vector fire_point_rot_world)
Private Attributes
protected float m_SmokePosX
protected float m_SmokePosY
protected float m_SmokePosZ
protected int m_FirePointIndex = 1
Static Private Attributes
static const string FIREPOINT_ACTION_SELECTION = "fireplace_action"
static const string FIREPOINT_FIRE_POSITION = "fireplace_point"
static const string FIREPOINT_PLACE_ROT = "fireplace_rot"
static const string FIREPOINT_SMOKE_POSITION = "fireplace_smoke"
Constructor & Destructor Documentation
FireplaceIndoor()
void FireplaceIndoor () inline private
References ParticleList::HOUSE_FIRE_END, ParticleList::HOUSE_FIRE_START, ParticleList::HOUSE_FIRE_STEAM_2END, ParticleList::HOUSE_NORMAL_FIRE, ParticleList::HOUSE_NORMAL_SMOKE, ParticleList::HOUSE_SMALL_FIRE, ParticleList::HOUSE_SMALL_SMOKE, UniversalTemperatureSourceSettings::m_ActiveTemperatureThreshold, UniversalTemperatureSourceSettings::m_EnableOnTemperatureControl, UniversalTemperatureSourceSettings::m_InactiveTemperatureThreshold, m_LightDistance, m_UTSSettings, PARTICLE_FIRE_END, PARTICLE_FIRE_START, PARTICLE_NORMAL_FIRE, PARTICLE_NORMAL_SMOKE, PARTICLE_SMALL_FIRE, PARTICLE_SMALL_SMOKE, and PARTICLE_STEAM_END.
Member Function Documentation
CanBeIgnitedBy()
override bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
References HasAnyKindling().
CanIgniteItem()
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
References IsBurning().
CanPlaceFireplaceInSelectedSpot()
static bool CanPlaceFireplaceInSelectedSpot (Object building, int fire_point_index, out vector fire_point_pos_world, out vector fire_point_rot_world) inline static private
References FIREPOINT_FIRE_POSITION, FIREPOINT_PLACE_ROT, GetGame(), and CGame::GetObjectsAtPosition3D().
Referenced by ActionCreateIndoorFireplace::ActionCondition(), and ActionPlaceFireplaceIndoor::ActionCondition().
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
CanPutIntoHands()
override bool CanPutIntoHands (EntityAI parent) inline private
CanReceiveItemIntoCargo()
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
CanRemoveFromCargo()
override bool CanRemoveFromCargo (EntityAI parent) inline private
CanRemoveFromHands()
override bool CanRemoveFromHands (EntityAI player) inline private
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name) inline private
References AddToFireConsumables(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, and RefreshFireplaceVisuals().
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name) inline private
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, CheckForDestroy(), ClearCookingEquipment(), GetFireConsumableByItem(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), FryingPan::RemoveAudioVisualsOnClient(), and RemoveFromFireConsumables().
GetFirePointIndex()
static int GetFirePointIndex (string action_selection) inline static private
References string::Length(), string::Substring(), and string::ToInt().
Referenced by ActionCreateIndoorFireplace::ActionCondition(), and ActionPlaceFireplaceIndoor::ActionCondition().
GetSmokeEffectPosition()
override protected vector GetSmokeEffectPosition () inline private
References m_SmokePosX, m_SmokePosY, m_SmokePosZ, and Vector().
Referenced by ParticleNormalSmokeStart(), and ParticleSmallSmokeStart().
HasFlammableMaterial()
override bool HasFlammableMaterial () inline private
IsFireplaceIndoor()
override bool IsFireplaceIndoor () inline private
IsIgnited()
override bool IsIgnited () inline private
References IsBurning().
IsThisIgnitionSuccessful()
override bool IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
References GetGame(), GetIgniteFailure(), HasAnyKindling(), IsWet(), CGame::RPCSingleParam(), and SetIgniteFailure().
OnIgnitedTarget()
override void OnIgnitedTarget (EntityAI ignited_item) inline private
OnIgnitedThis()
override void OnIgnitedThis (EntityAI fire_source) inline private
References StartFire().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References m_FirePointIndex, m_SmokePosX, m_SmokePosY, m_SmokePosZ, and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
References m_FirePointIndex, m_SmokePosX, m_SmokePosY, m_SmokePosZ, and Serializer::Write().
ParticleNormalSmokeStart()
override void ParticleNormalSmokeStart () inline private
References GetSmokeEffectPosition(), m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, and PlayParticle().
ParticleSmallSmokeStart()
override void ParticleSmallSmokeStart () inline private
References GetSmokeEffectPosition(), m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, and PlayParticle().
SetFirePointIndex()
void SetFirePointIndex (int fire_point_index) inline private
References m_FirePointIndex.
Referenced by CopyOldPropertiesToNew(), and ActionCreateIndoorFireplace::OnExecuteServer().
SetSmokePointPosition()
void SetSmokePointPosition (vector smoke_point_pos) inline private
References m_SmokePosX, m_SmokePosY, and m_SmokePosZ.
Referenced by CopyOldPropertiesToNew(), and ActionCreateIndoorFireplace::OnExecuteServer().
Field Documentation
FIREPOINT_ACTION_SELECTION
const string FIREPOINT_ACTION_SELECTION = "fireplace_action" static private
Referenced by ActionCreateIndoorFireplace::ActionCondition(), and ActionPlaceFireplaceIndoor::ActionCondition().
FIREPOINT_FIRE_POSITION
const string FIREPOINT_FIRE_POSITION = "fireplace_point" static private
Referenced by CanPlaceFireplaceInSelectedSpot().
FIREPOINT_PLACE_ROT
const string FIREPOINT_PLACE_ROT = "fireplace_rot" static private
Referenced by ActionCreateIndoorFireplace::ActionCondition(), ActionPlaceFireplaceIndoor::ActionCondition(), and CanPlaceFireplaceInSelectedSpot().
FIREPOINT_SMOKE_POSITION
const string FIREPOINT_SMOKE_POSITION = "fireplace_smoke" static private
Referenced by FireplaceToIndoorsLambda(), and ActionCreateIndoorFireplace::OnExecuteServer().
m_FirePointIndex
protected int m_FirePointIndex = 1 private
Referenced by OnStoreLoad(), OnStoreSave(), and SetFirePointIndex().
m_SmokePosX
protected float m_SmokePosX private
Referenced by GetSmokeEffectPosition(), OnStoreLoad(), OnStoreSave(), and SetSmokePointPosition().
m_SmokePosY
protected float m_SmokePosY private
Referenced by GetSmokeEffectPosition(), OnStoreLoad(), OnStoreSave(), and SetSmokePointPosition().
m_SmokePosZ
protected float m_SmokePosZ private
Referenced by GetSmokeEffectPosition(), OnStoreLoad(), OnStoreSave(), and SetSmokePointPosition().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/FireplaceBase/FireplaceIndoor.c