DayZ Scripts: Surface Class Reference
Surface Class Reference
Static Private Member Functions
static int GetStepsParticleID (string surface_name)
static int GetWheelParticleID (string surface_name)
static int GetParamInt (string surface_name, string param_name)
static float GetParamFloat (string surface_name, string param_name)
static string GetParamText (string surfaceName, string paramName)
static bool AllowedWaterSurface (float pHeight, string pSurface, array< string > pAllowedSurfaceList)
static bool CheckLiquidSource (float pHeight, string pSurface, int allowedWaterSourceMask)
Member Function Documentation
AllowedWaterSurface()
static bool AllowedWaterSurface (float pHeight, string pSurface, array< string > pAllowedSurfaceList) inline static private
References g_Game, string::Replace(), and UAWaterType::SEA.
Referenced by CCTWaterSurface::Can(), and ItemBase::IsSurfaceWater().
CheckLiquidSource()
static bool CheckLiquidSource (float pHeight, string pSurface, int allowedWaterSourceMask) inline static private
References g_Game, SurfaceInfo::GetByName(), SurfaceInfo::GetLiquidType(), and LIQUID_SALTWATER.
Referenced by Can().
GetParamFloat()
static float GetParamFloat (string surface_name, string param_name) inline static private
References CGame::ConfigGetFloat(), and GetGame().
Referenced by DealEvinronmentAdjustedDmg(), GetSurfaceWetnessOnHeatModifier(), and ManBase::ProcessFeetDamageServer().
GetParamInt()
static int GetParamInt (string surface_name, string param_name) inline static private
References CGame::ConfigGetInt(), and GetGame().
GetParamText()
static string GetParamText (string surfaceName, string paramName) inline static private
References CGame::ConfigGetText(), and GetGame().
Referenced by GetObjectNameFromSurfaceConfig().
GetStepsParticleID()
static int GetStepsParticleID (string surface_name) inline static private
References SurfaceInfo::GetByName(), and SurfaceInfo::GetStepParticleId().
Referenced by DayZPlayer::OnStepEvent().
GetWheelParticleID()
static int GetWheelParticleID (string surface_name) inline static private
References SurfaceInfo::GetByName(), and SurfaceInfo::GetWheelParticleId().
Referenced by EffWheelSmoke::SetSurface().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/Surface.c