DayZ Scripts: HandEventBase Class Reference
HandEventBase Class Reference
Abstracted event, not to be used, only inherited.
Private Member Functions
void HandEventTake (Man p=null, InventoryLocation src=null)
override InventoryLocation GetDst ()
override bool CheckRequestSrc ()
override bool CheckRequest ()
override bool CanPerformEventEx (InventoryValidation validation)
override bool AcquireInventoryJunctureFromServer (notnull Man player)
void HandEventMoveTo (Man p=null, InventoryLocation src=null, InventoryLocation dst=null)
destination for item in hands
override void ReadFromContext (ParamsReadContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
override InventoryLocation GetDst ()
override bool CheckRequestSrc ()
override bool CheckRequest ()
override bool CanPerformEvent ()
override bool AcquireInventoryJunctureFromServer (notnull Man player)
override string DumpToString ()
override InventoryLocation GetDst ()
override bool CheckRequestSrc ()
override bool CheckRequest ()
override bool CanPerformEvent ()
override bool AcquireInventoryJunctureFromServer (notnull Man player)
void HandEventSwap (Man p=null, InventoryLocation src=null, InventoryLocation src2=null, InventoryLocation dst=null, InventoryLocation dst2=null)
override void ReadFromContext (ParamsReadContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
override InventoryLocation GetDst ()
override EntityAI GetSecondSrcEntity ()
override bool CheckRequestSrc ()
override bool CheckRequest ()
override bool CanPerformEvent ()
override bool AcquireInventoryJunctureFromServer (notnull Man player)
override string DumpToString ()
void CheckAndExecuteForceStandUp ()
override bool ReserveInventory ()
override void ClearInventoryReservation ()
void HandEventDestroy (Man p=null, InventoryLocation src=null)
override bool IsServerSideOnly ()
void HandEventCreated (Man p=null, InventoryLocation src=null)
void HandEventDestroyed (Man p=null, InventoryLocation src=null)
void HandEvengReplaceWithNewBase (Man p=null, InventoryLocation src=null, ReplaceItemWithNewLambdaBase lambda=NULL)
override void ReadFromContext (ParamsReadContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
override bool IsServerSideOnly ()
override InventoryLocation GetDst ()
override string DumpToString ()
void HandEventReplaced (Man p=null, InventoryLocation src=null)
void HandAnimEventChanged (Man p=null, InventoryLocation src=null)
void HandEventHumanCommandActionFinished (Man p=null, InventoryLocation src=null)
void HandEventHumanCommandActionAborted (Man p=null, InventoryLocation src=null)
Private Attributes
ref InventoryLocation m_Dst
ref InventoryLocation m_Src2
destination for new item (i.e. hands)
ref InventoryLocation m_Dst2
src of old item in hands
int m_Animation2ID = -1
destination for old item that was in hands
string m_Type
ref ReplaceItemWithNewLambdaBase m_Lambda
Detailed Description
Abstracted event, not to be used, only inherited.
represents event that triggers transition from state to state
triggered when animation action aborts
triggered when animation action finishes
Member Function Documentation
AcquireInventoryJunctureFromServer() [1/4]
override bool AcquireInventoryJunctureFromServer (notnull Man player) inline private
References DumpToString(), Error(), GetDst(), GetSrc(), and TryAcquireInventoryJunctureFromServer().
Referenced by ValidateHandEvent().
AcquireInventoryJunctureFromServer() [2/4]
override bool AcquireInventoryJunctureFromServer (notnull Man player) inline private
References DumpToString(), Error(), GetDst(), GetSrc(), and TryAcquireInventoryJunctureFromServer().
AcquireInventoryJunctureFromServer() [3/4]
override bool AcquireInventoryJunctureFromServer (notnull Man player) inline private
References DumpToString(), Error(), GetDst(), GetSrc(), and TryAcquireInventoryJunctureFromServer().
AcquireInventoryJunctureFromServer() [4/4]
override bool AcquireInventoryJunctureFromServer (notnull Man player) inline private
References m_Src, and TryAcquireTwoInventoryJuncturesFromServer().
CanPerformEvent() [1/3]
override bool CanPerformEvent () inline private
References GetDst(), GetEventID(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationCanMoveEntity(), and m_Player.
Referenced by CanPerformEventEx().
CanPerformEvent() [2/3]
override bool CanPerformEvent () inline private
References GetDst(), GetEventID(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationCanMoveEntity(), and m_Player.
CanPerformEvent() [3/3]
override bool CanPerformEvent () inline private
References GameInventory::CanForceSwapEntitiesEx(), GetEventID(), GetItem(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
CanPerformEventEx()
override bool CanPerformEventEx (InventoryValidation validation) inline private
References GetDst(), GetEventID(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationCanMoveEntity(), InventoryValidation::m_IsJuncture, and m_Player.
Referenced by HandEvent(), HandleHandEvent(), and ValidateHandEvent().
CheckAndExecuteForceStandUp()
void CheckAndExecuteForceStandUp () inline private
References InventoryLocation::GetItem(), m_Player, and m_Src.
CheckRequest() [1/4]
override bool CheckRequest () inline private
References GameInventory::c_MaxItemDistanceRadius, GameInventory::CheckMoveToDstRequest(), GetDst(), GetSrc(), and m_Player.
Referenced by CheckRequestEx().
CheckRequest() [2/4]
override bool CheckRequest () inline private
References GameInventory::c_MaxItemDistanceRadius, GameInventory::CheckMoveToDstRequest(), GetDst(), GetSrc(), and m_Player.
CheckRequest() [3/4]
override bool CheckRequest () inline private
References GameInventory::c_MaxItemDistanceRadius, GameInventory::CheckMoveToDstRequest(), GetDst(), GetSrc(), and m_Player.
CheckRequest() [4/4]
override bool CheckRequest () inline private
References GameInventory::c_MaxItemDistanceRadius, GameInventory::CheckSwapItemsRequest(), GetEventID(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), m_Player, and m_Src.
CheckRequestSrc() [1/4]
override bool CheckRequestSrc () inline private
References GameInventory::c_MaxItemDistanceRadius, GameInventory::CheckRequestSrc(), InventoryLocation::DumpToStringNullSafe(), GetEventID(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsSyncLogEnable(), m_Player, and syncDebugPrint().
Referenced by ValidateHandEvent().
CheckRequestSrc() [2/4]
override bool CheckRequestSrc () inline private
References GameInventory::c_MaxItemDistanceRadius, GameInventory::CheckRequestSrc(), InventoryLocation::DumpToStringNullSafe(), GetEventID(), GetSrc(), LogManager::IsSyncLogEnable(), m_Player, and syncDebugPrint().
CheckRequestSrc() [3/4]
override bool CheckRequestSrc () inline private
References GameInventory::c_MaxItemDistanceRadius, GameInventory::CheckRequestSrc(), InventoryLocation::DumpToStringNullSafe(), GetEventID(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
CheckRequestSrc() [4/4]
override bool CheckRequestSrc () inline private
References GameInventory::c_MaxItemDistanceRadius, GameInventory::CheckRequestSrc(), InventoryLocation::DumpToStringNullSafe(), GetEventID(), GetSrc(), LogManager::IsSyncLogEnable(), m_Player, and syncDebugPrint().
ClearInventoryReservation()
override void ClearInventoryReservation () inline private
References m_Player.
Referenced by DeferredHandEvent::ClearInventoryReservation(), and ValidateHandEvent().
DumpToString() [1/3]
override string DumpToString () inline private
References InventoryLocation::DumpToStringNullSafe(), GetEventID(), m_Player, and m_Src.
Referenced by AcquireInventoryJunctureFromServer(), HandGuardBase::GuardCondition(), HandleHandEvent(), GameInventory::OnServerInventoryCommandStatic(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), HumanInventory::ReplaceItemInHandsWithNewImpl(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), SyncHandEventToRemote(), and ValidateHandEvent().
DumpToString() [2/3]
override string DumpToString () inline private
References InventoryLocation::DumpToStringNullSafe(), GetEventID(), m_Player, and m_Src.
DumpToString() [3/3]
override string DumpToString () inline private
References InventoryLocation::DumpToStringNullSafe(), GetDst(), GetEventID(), GetSrc(), and m_Player.
GetDst() [1/5]
override InventoryLocation GetDst () inline private
References GetSrcEntity(), m_Player, and InventoryLocation::SetHands().
Referenced by AcquireInventoryJunctureFromServer(), HandActionBase::Action(), CanPerformEvent(), CanPerformEventEx(), CheckRequest(), ClearInventoryReservation(), HandGuardBase::GuardCondition(), HandEvent(), HandleHandEvent(), HandStateEquipped::OnEntry(), HandStateBase::OnEntry(), OnInventoryJunctureFailureFromServer(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), ReserveInventory(), SendServerHandEventViaJuncture(), and ValidateHandEvent().
GetDst() [2/5]
override InventoryLocation GetDst () inline private
References m_Dst.
GetDst() [3/5]
override InventoryLocation GetDst () inline private
GetDst() [4/5]
override InventoryLocation GetDst () inline private
GetDst() [5/5]
override InventoryLocation GetDst () inline private
References GetSrcEntity(), m_Player, and InventoryLocation::SetHands().
GetSecondSrcEntity()
override EntityAI GetSecondSrcEntity () inline private
Referenced by ValidateHandEvent().
HandAnimEventChanged()
void HandAnimEventChanged (Man p = null, InventoryLocation src = null) inline private
References m_EventID.
Referenced by HandEventFactory().
HandEvengReplaceWithNewBase()
void HandEvengReplaceWithNewBase (Man p = null, InventoryLocation src = null, ReplaceItemWithNewLambdaBase lambda = NULL) inline private
References m_EventID.
HandEventCreated()
void HandEventCreated (Man p = null, InventoryLocation src = null) inline private
References m_EventID.
Referenced by HandEventFactory().
HandEventDestroy()
void HandEventDestroy (Man p = null, InventoryLocation src = null) inline private
References m_EventID.
Referenced by HandEventFactory().
HandEventDestroyed()
void HandEventDestroyed (Man p = null, InventoryLocation src = null) inline private
References m_EventID.
Referenced by HandEventFactory().
HandEventHumanCommandActionAborted()
void HandEventHumanCommandActionAborted (Man p = null, InventoryLocation src = null) inline private
References m_EventID.
Referenced by HandEventFactory().
HandEventHumanCommandActionFinished()
void HandEventHumanCommandActionFinished (Man p = null, InventoryLocation src = null) inline private
References m_EventID.
Referenced by HandEventFactory().
HandEventMoveTo()
void HandEventMoveTo (Man p = null, InventoryLocation src = null, InventoryLocation dst = null) inline private
destination for item in hands
References m_EventID.
Referenced by HandEventFactory().
HandEventReplaced()
void HandEventReplaced (Man p = null, InventoryLocation src = null) inline private
References m_EventID.
Referenced by HandEventFactory().
HandEventSwap()
void HandEventSwap (Man p = null, InventoryLocation src = null, InventoryLocation src2 = null, InventoryLocation dst = null, InventoryLocation dst2 = null) inline private
References m_EventID.
HandEventTake()
void HandEventTake (Man p = null, InventoryLocation src = null) inline private
References m_EventID.
Referenced by HandEventFactory().
IsServerSideOnly() [1/2]
override bool IsServerSideOnly () inline private
Referenced by HandleHandEvent(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), and SendServerHandEventViaJuncture().
IsServerSideOnly() [2/2]
override bool IsServerSideOnly () inline private
ReadFromContext() [1/3]
override void ReadFromContext (ParamsReadContext ctx) inline private
References InventoryLocation::ReadFromContext().
Referenced by CreateHandEventFromContext().
ReadFromContext() [2/3]
override void ReadFromContext (ParamsReadContext ctx) inline private
References Serializer::Read(), and InventoryLocation::ReadFromContext().
ReadFromContext() [3/3]
override void ReadFromContext (ParamsReadContext ctx) inline private
References Error(), m_Type, and Serializer::Read().
ReserveInventory()
override bool ReserveInventory () inline private
References GameInventory::c_InventoryReservationTimeoutShortMS, and m_Player.
Referenced by HumanInventory::ForceSwapEntities(), and DeferredHandEvent::ReserveInventory().
WriteToContext() [1/3]
override void WriteToContext (ParamsWriteContext ctx) inline private
Referenced by InventoryInputUserData::SerializeHandEvent(), and SyncHandEventToRemote().
WriteToContext() [2/3]
override void WriteToContext (ParamsWriteContext ctx) inline private
References Serializer::Write().
WriteToContext() [3/3]
override void WriteToContext (ParamsWriteContext ctx) inline private
References Error(), m_Type, and Serializer::Write().
Field Documentation
m_Animation2ID
int m_Animation2ID = -1 private
destination for old item that was in hands
m_Dst
ref InventoryLocation m_Dst private
Referenced by HandActionBase::Action(), GetDst(), and HandStateBase::OnEntry().
m_Dst2
ref InventoryLocation m_Dst2 private
src of old item in hands
m_Lambda
ref ReplaceItemWithNewLambdaBase m_Lambda private
m_Src2
ref InventoryLocation m_Src2 private
destination for new item (i.e. hands)
m_Type
string m_Type private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/Inventory/Hand_Events.c