DayZ Scripts: Rifle_Base Class Reference
Rifle_Base Class Reference
base for rifles @NOTE name copies config base class
Private Member Functions
override RecoilBase SpawnRecoilObject ()
override void InitStateMachine ()
override bool CanEnterIronsights ()
override void SetActions ()
override void OnDebugSpawn ()
override void InitStateMachine ()
override bool CanChamberBullet (int muzzleIndex, Magazine mag)
override void SetActions ()
void RifleBoltFree_Base ()
override void InitStateMachine ()
override float GetChanceToJam ()
override void SetActions ()
void RifleBoltLock_Base ()
override void InitStateMachine ()
override float GetChanceToJam ()
override void SetActions ()
void RifleSingleShot_Base ()
override void InitStateMachine ()
override float GetChanceToJam ()
Private Attributes
ref WeaponStateBase C0
ref WeaponStateBase C1
ref WeaponStateBase L0
ref WeaponStateBase JF
ref WeaponStableState D0
ref WeaponStableState C0
ref WeaponStableState C1
ref WeaponStableState DF
ref WeaponStableState JF
ref WeaponStableState C00
ref WeaponStableState C10
ref WeaponStableState C11
ref WeaponStableState C01
ref WeaponStableState JF0
ref WeaponStableState JF1
ref WeaponStableState O00
ref WeaponStableState O01
Detailed Description
base for rifles @NOTE name copies config base class
Definition at line 69 of file SKS.c.
Member Function Documentation
CanChamberBullet()
override bool CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 219 of file Repeater.c.
CanEnterIronsights()
override bool CanEnterIronsights () inline private
Definition at line 250 of file SKS.c.
GetChanceToJam() [1/3]
override float GetChanceToJam () inline private
Definition at line 358 of file RifleBoltFree_Base.c.
GetChanceToJam() [2/3]
override float GetChanceToJam () inline private
Definition at line 473 of file RifleBoltLock_Base.c.
GetChanceToJam() [3/3]
override float GetChanceToJam () inline private
Definition at line 191 of file RifleSingleShot_Base.c.
InitStateMachine() [1/5]
override void InitStateMachine () inline private
Definition at line 81 of file SKS.c.
References SKS_CLO_BU0, SKS_CLO_BU1, SKS_JAM_BU1, and SKS_OPN_BU0.
InitStateMachine() [2/5]
override void InitStateMachine () inline private
Definition at line 75 of file Repeater.c.
InitStateMachine() [3/5]
override void InitStateMachine () inline private
Definition at line 106 of file RifleBoltFree_Base.c.
References RBF_CLO_BU0_MA0, RBF_CLO_BU0_MA1, RBF_CLO_BU1_MA0, RBF_CLO_BU1_MA1, RBF_JAM_BU1_MA0, RBF_JAM_BU1_MA1, and WeaponGuardHasAmmo().
InitStateMachine() [4/5]
override void InitStateMachine () inline private
Definition at line 134 of file RifleBoltLock_Base.c.
References RBL_CLO_BU0_MA0, RBL_CLO_BU0_MA1, RBL_CLO_BU1_MA0, RBL_CLO_BU1_MA1, RBL_JAM_BU1_MA0, RBL_JAM_BU1_MA1, RBL_OPN_BU0_MA0, RBL_OPN_BU0_MA1, and WeaponGuardHasAmmo().
InitStateMachine() [5/5]
override void InitStateMachine () inline private
Definition at line 71 of file RifleSingleShot_Base.c.
References E, F, and L.
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 268 of file SKS.c.
References GameInventory::CreateInInventory().
RifleBoltFree_Base()
void RifleBoltFree_Base () inline private
Definition at line 101 of file RifleBoltFree_Base.c.
RifleBoltLock_Base()
void RifleBoltLock_Base () inline private
Definition at line 130 of file RifleBoltLock_Base.c.
RifleSingleShot_Base()
void RifleSingleShot_Base () inline private
Definition at line 67 of file RifleSingleShot_Base.c.
SetActions() [1/4]
override void SetActions () inline private
Definition at line 258 of file SKS.c.
References AddAction(), FirearmActionLoadBulletQuick(), and RemoveAction().
SetActions() [2/4]
override void SetActions () inline private
Definition at line 224 of file Repeater.c.
References AddAction(), FirearmActionLoadBulletQuick(), and RemoveAction().
SetActions() [3/4]
override void SetActions () inline private
Definition at line 375 of file RifleBoltFree_Base.c.
References AddAction().
SetActions() [4/4]
override void SetActions () inline private
Definition at line 490 of file RifleBoltLock_Base.c.
References AddAction().
SpawnRecoilObject()
override RecoilBase SpawnRecoilObject () inline private
Definition at line 76 of file SKS.c.
Field Documentation
C0 [1/2]
ref WeaponStateBase C0 private
Definition at line 71 of file SKS.c.
C0 [2/2]
ref WeaponStableState C0 private
Definition at line 69 of file Repeater.c.
C00
ref WeaponStableState C00 private
Definition at line 94 of file RifleBoltFree_Base.c.
C01
ref WeaponStableState C01 private
Definition at line 97 of file RifleBoltFree_Base.c.
C1 [1/2]
ref WeaponStateBase C1 private
Definition at line 72 of file SKS.c.
C1 [2/2]
ref WeaponStableState C1 private
Definition at line 70 of file Repeater.c.
C10
ref WeaponStableState C10 private
Definition at line 95 of file RifleBoltFree_Base.c.
C11
ref WeaponStableState C11 private
Definition at line 96 of file RifleBoltFree_Base.c.
D0
ref WeaponStableState D0 private
Definition at line 68 of file Repeater.c.
DF
ref WeaponStableState DF private
Definition at line 71 of file Repeater.c.
JF [1/2]
ref WeaponStateBase JF private
Definition at line 74 of file SKS.c.
JF [2/2]
ref WeaponStableState JF private
Definition at line 72 of file Repeater.c.
JF0
ref WeaponStableState JF0 private
Definition at line 98 of file RifleBoltFree_Base.c.
JF1
ref WeaponStableState JF1 private
Definition at line 99 of file RifleBoltFree_Base.c.
L0
ref WeaponStateBase L0 private
Definition at line 73 of file SKS.c.
O00
ref WeaponStableState O00 private
Definition at line 125 of file RifleBoltLock_Base.c.
O01
ref WeaponStableState O01 private
Definition at line 126 of file RifleBoltLock_Base.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Firearms/AutomaticRifle/SKS.c
P:/scripts/4_World/Entities/Firearms/Rifle/Repeater.c
P:/scripts/4_World/Entities/Firearms/RifleBoltFree_Base.c
P:/scripts/4_World/Entities/Firearms/RifleBoltLock_Base.c
P:/scripts/4_World/Entities/Firearms/RifleSingleShot_Base.c