DayZ Scripts: EffEngineSmoke Class Reference
EffEngineSmoke Class Reference
Private Member Functions
void EffEngineSmoke ()
override void SetParticleStateLight ()
override void SetParticleStateHeavy ()
override void Event_OnFrameUpdate (float time_delta)
Private Attributes
private float m_Time
Static Private Attributes
static private float m_UpdateInterval = 2
Detailed Description
Definition at line 1 of file EngineSmoke.c.
Constructor & Destructor Documentation
EffEngineSmoke()
void EffEngineSmoke () inline private
Definition at line 6 of file EngineSmoke.c.
References SetEnableEventFrame().
Member Function Documentation
Event_OnFrameUpdate()
override void Event_OnFrameUpdate (float time_delta) inline private
Definition at line 21 of file EngineSmoke.c.
References GetAttachmentParent(), EffectParticle::GetParticle(), Particle::GetParticleID(), m_Time, m_UpdateInterval, Particle::ScaleParticleParamFromOriginal(), and EffVehicleSmoke::SetParticleState().
SetParticleStateHeavy()
override void SetParticleStateHeavy () inline private
Definition at line 16 of file EngineSmoke.c.
References ParticleList::HATCHBACK_ENGINE_OVERHEATED, and EffVehicleSmoke::SetParticleState().
SetParticleStateLight()
override void SetParticleStateLight () inline private
Definition at line 11 of file EngineSmoke.c.
References ParticleList::HATCHBACK_ENGINE_OVERHEATING, and EffVehicleSmoke::SetParticleState().
Field Documentation
m_Time
private float m_Time private
Definition at line 3 of file EngineSmoke.c.
Referenced by Event_OnFrameUpdate().
m_UpdateInterval
private float m_UpdateInterval = 2 static private
Definition at line 4 of file EngineSmoke.c.
Referenced by Event_OnFrameUpdate().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Effects/EffectParticle/VehicleSmoke/EngineSmoke.c