DayZ Scripts: P:/scripts/3_Game/tools/Debug.c File Reference
Debug.c File Reference
Data Structures
class Debug
class LogManager
class WeightDebugData
Functions
static WeightDebugData GetWeightDebug (EntityAI entity)
static void ClearWeightDebug ()
static void PrintAll (EntityAI entity)
static void SetVerbosityFlags (WeightDebugType type)
Variables
class LogManager NONE = 0
class LogManager RECALC_FORCED = 1
class LogManager RECALC_DIRTY = 2
class LogManager DUMP_STACK = 4
class LogManager SET_DIRTY_FLAG = 8
class LogManager EntityAI = 8
class LogManager m_WeightDebugData = new map<EntityAI, ref WeightDebugData>()
static WeightDebugType m_VerbosityFlags
Function Documentation
ClearWeightDebug()
static void ClearWeightDebug () static
References m_WeightDebugData.
GetWeightDebug()
static WeightDebugData GetWeightDebug (EntityAI entity) static
References m_WeightDebugData.
PrintAll()
static void PrintAll (EntityAI entity) static
References GameInventory::EnumerateInventory(), and m_WeightDebugData.
SetVerbosityFlags()
static void SetVerbosityFlags (WeightDebugType type) static
References m_VerbosityFlags.
Variable Documentation
DUMP_STACK
class LogManager DUMP_STACK = 4
EntityAI
class LogManager EntityAI = 8
m_VerbosityFlags
WeightDebugType m_VerbosityFlags static
Referenced by SetVerbosityFlags().
m_WeightDebugData
class LogManager m_WeightDebugData = new map<EntityAI, ref WeightDebugData>()
Referenced by ClearWeightDebug(), GetWeightDebug(), and PrintAll().
NONE
class LogManager NONE = 0
RECALC_DIRTY
class LogManager RECALC_DIRTY = 2
RECALC_FORCED
class LogManager RECALC_FORCED = 1
SET_DIRTY_FLAG
class LogManager SET_DIRTY_FLAG = 8