DayZ Scripts: NoIndicationActionInputBase Class Reference
NoIndicationActionInputBase Class Reference
Private Member Functions
void NoIndicationActionInputBase (PlayerBase player)
override void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask)
override ActionBase GetAction ()
override ActionBase GetPossibleAction ()
Detailed Description
Definition at line 554 of file ActionInput.c.
Constructor & Destructor Documentation
NoIndicationActionInputBase()
void NoIndicationActionInputBase (PlayerBase player) inline private
Definition at line 556 of file ActionInput.c.
References ActionInput::m_DetectFromTarget.
Member Function Documentation
GetAction()
override ActionBase GetAction () inline private
Definition at line 568 of file ActionInput.c.
References ActionBase(), ActionInput::ForceActionCheck(), ActionInput::m_ConditionMask, ActionInput::m_ForcedActionData, ActionInput::m_MainItem, ActionInput::m_Player, ActionInput::m_Target, and Type.
Referenced by GetPossibleAction().
GetPossibleAction()
override ActionBase GetPossibleAction () inline private
Definition at line 595 of file ActionInput.c.
References GetAction().
UpdatePossibleActions()
override void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask) inline private
Definition at line 561 of file ActionInput.c.
References ActionInput::m_ConditionMask, ActionInput::m_MainItem, and ActionInput::m_Target.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionInput.c