DayZ Scripts: Chat Class Reference
Chat Class Reference
Private Member Functions
void Chat ()
void ~Chat ()
void Init (Widget root_widget)
void Destroy ()
void Clear ()
void Add (ChatMessageEventParams params)
void AddInternal (ChatMessageEventParams params)
Private Attributes
const int LINE_COUNT = 12
protected Widget m_RootWidget
protected int m_LineHeight
protected int m_LastLine
protected ref array< ref ChatLine > m_Lines
Detailed Description
channel type, possible values CCSystem(1) CCAdmin(2) CCDirect(4) CCMegaphone(8) CCTransmitter(16) CCPublicAddressSystem(32) CCBattlEye(64)
Constructor & Destructor Documentation
Chat()
void Chat () inline private
References m_Lines.
~Chat()
void ~Chat () inline private
References Destroy().
Member Function Documentation
Add()
void Add (ChatMessageEventParams params) inline private
References AddInternal(), Math::Clamp(), g_Game, and Print().
AddInternal()
void AddInternal (ChatMessageEventParams params) inline private
References LINE_COUNT, m_LastLine, m_LineHeight, m_Lines, ChatLine::m_RootWidget, ChatLine::Set(), x, and y.
Referenced by Add().
Clear()
void Clear () inline private
References LINE_COUNT, and m_Lines.
Destroy()
void Destroy () inline private
References m_Lines.
Referenced by Init(), and ~Chat().
Init()
void Init (Widget root_widget) inline private
References Destroy(), LINE_COUNT, m_LastLine, m_LineHeight, m_Lines, and m_RootWidget.
Field Documentation
LINE_COUNT
const int LINE_COUNT = 12 private
Referenced by AddInternal(), Clear(), and Init().
m_LastLine
protected int m_LastLine private
Referenced by AddInternal(), and Init().
m_LineHeight
protected int m_LineHeight private
Referenced by AddInternal(), and Init().
m_Lines
protected ref array<ref ChatLine> m_Lines private
Referenced by AddInternal(), Chat(), Clear(), Destroy(), and Init().
m_RootWidget
protected Widget m_RootWidget private
Referenced by Init().
The documentation for this class was generated from the following file:
5_Mission/GUI/Chat/Chat.c