DayZ Scripts: WeaponStartAction Class Reference
WeaponStartAction Class Reference
simple class starting animation action specified by m_action and m_actionType
Private Member Functions
override void OnEntry (WeaponEventBase e)
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override void OnEntry (WeaponEventBase e)
override bool IsWaitingForActionFinish ()
override void OnUpdate (float dt)
override void OnExit (WeaponEventBase e)
override bool IsWaitingForActionFinish ()
override void OnEntry (WeaponEventBase e)
override void OnUpdate (float dt)
override void OnExit (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override bool IsWaitingForActionFinish ()
override void OnEntry (WeaponEventBase e)
override void OnUpdate (float dt)
override void OnExit (WeaponEventBase e)
void WeaponUnjamming_Start (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (WeaponEventBase e)
override void OnUpdate (float dt)
override void OnExit (WeaponEventBase e)
Private Attributes
float m_dtAccumulator
float m_jamTime
Detailed Description
simple class starting animation action specified by m_action and m_actionType
Definition at line 2 of file WeaponChambering.c.
Member Function Documentation
IsWaitingForActionFinish() [1/7]
override bool IsWaitingForActionFinish () inline private
Definition at line 14 of file WeaponChambering.c.
IsWaitingForActionFinish() [2/7]
override bool IsWaitingForActionFinish () inline private
Definition at line 618 of file WeaponChambering.c.
IsWaitingForActionFinish() [3/7]
override bool IsWaitingForActionFinish () inline private
Definition at line 4 of file WeaponChamberingLooped.c.
IsWaitingForActionFinish() [4/7]
override bool IsWaitingForActionFinish () inline private
Definition at line 54 of file WeaponCharging.c.
IsWaitingForActionFinish() [5/7]
override bool IsWaitingForActionFinish () inline private
Definition at line 16 of file WeaponFire.c.
IsWaitingForActionFinish() [6/7]
override bool IsWaitingForActionFinish () inline private
Definition at line 48 of file WeaponFire.c.
IsWaitingForActionFinish() [7/7]
override bool IsWaitingForActionFinish () inline private
Definition at line 269 of file WeaponFire.c.
OnAbort()
override void OnAbort (WeaponEventBase e) inline private
Definition at line 91 of file WeaponFire.c.
References m_weapon.
OnEntry() [1/5]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 4 of file WeaponChambering.c.
References m_weapon.
OnEntry() [2/5]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 6 of file WeaponFire.c.
References m_dtAccumulator, and m_weapon.
OnEntry() [3/5]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 50 of file WeaponFire.c.
References Class::CastTo(), LogManager::IsWeaponLogEnable(), m_dtAccumulator, WeaponEventBase::m_player, m_weapon, TryFireWeapon(), and wpnPrint().
OnEntry() [4/5]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 271 of file WeaponFire.c.
References Class::CastTo(), LogManager::IsWeaponLogEnable(), m_dtAccumulator, WeaponEventBase::m_player, m_weapon, TryFireWeapon(), and wpnPrint().
OnEntry() [5/5]
override void OnEntry (WeaponEventBase e) inline private
Definition at line 22 of file WeaponUnjamming.c.
OnExit() [1/4]
override void OnExit (WeaponEventBase e) inline private
Definition at line 35 of file WeaponFire.c.
References m_dtAccumulator.
OnExit() [2/4]
override void OnExit (WeaponEventBase e) inline private
Definition at line 84 of file WeaponFire.c.
References m_dtAccumulator.
OnExit() [3/4]
override void OnExit (WeaponEventBase e) inline private
Definition at line 307 of file WeaponFire.c.
References m_dtAccumulator.
OnExit() [4/4]
override void OnExit (WeaponEventBase e) inline private
Definition at line 64 of file WeaponUnjamming.c.
References m_dtAccumulator.
OnUpdate() [1/4]
override void OnUpdate (float dt) inline private
Definition at line 18 of file WeaponFire.c.
References Class::CastTo(), HumanInputController::IsAttackButton(), m_dtAccumulator, and m_weapon.
OnUpdate() [2/4]
override void OnUpdate (float dt) inline private
Definition at line 70 of file WeaponFire.c.
References Class::CastTo(), m_dtAccumulator, and m_weapon.
OnUpdate() [3/4]
override void OnUpdate (float dt) inline private
Definition at line 293 of file WeaponFire.c.
References Class::CastTo(), m_dtAccumulator, and m_weapon.
OnUpdate() [4/4]
override void OnUpdate (float dt) inline private
Definition at line 27 of file WeaponUnjamming.c.
References Class::CastTo(), HumanInputController::IsReloadOrMechanismContinuousUse(), LogManager::IsWeaponLogEnable(), m_dtAccumulator, m_weapon, HumanCommandWeapons::StartAction(), and wpnDebugPrint().
WeaponUnjamming_Start()
void WeaponUnjamming_Start (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 16 of file WeaponUnjamming.c.
References m_dtAccumulator.
Field Documentation
m_dtAccumulator
float m_dtAccumulator private
Definition at line 4 of file WeaponFire.c.
m_jamTime
float m_jamTime private
Definition at line 14 of file WeaponUnjamming.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponChambering.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponFire.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponUnjamming.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponChamberingLooped.c
P:/scripts/4_World/Entities/Firearms/FSM/States/WeaponCharging.c