DayZ Scripts: KazuarOptic Class Reference
KazuarOptic Class Reference
Private Member Functions
override void InitOpticMode ()
override int GetCurrentNVType ()
override void OnOpticModeChange ()
override void OnOpticEnter ()
override void UpdateSelectionVisibility ()
override void SetActions ()
Member Function Documentation
GetCurrentNVType()
override int GetCurrentNVType () inline private
References Error(), ItemOptics::IsWorking(), ItemOptics::m_CurrentOpticMode, GameConstants::OPTICS_STATE_DAY, and GameConstants::OPTICS_STATE_NIGHTVISION.
InitOpticMode()
override void InitOpticMode () inline private
References GameConstants::OPTICS_STATE_NIGHTVISION, and ItemOptics::SetCurrentOpticMode().
OnOpticEnter()
override void OnOpticEnter () inline private
References ItemOptics::HideSelection().
OnOpticModeChange()
override void OnOpticModeChange () inline private
References UpdateSelectionVisibility().
SetActions()
override void SetActions () inline private
References AddAction().
UpdateSelectionVisibility()
override void UpdateSelectionVisibility () inline private
References ItemOptics::GetCurrentOpticMode(), GetGame(), ItemOptics::HideSelection(), ItemOptics::IsInOptics(), GameConstants::OPTICS_STATE_DAY, GameConstants::OPTICS_STATE_NIGHTVISION, and ItemOptics::ShowSelection().
Referenced by OnOpticModeChange().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/Optics.c