DayZ Scripts: ActionRemoveSeed Class Reference
ActionRemoveSeed Class Reference
Private Member Functions
void ActionRemoveSeed ()
override GetInputType ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool InventoryReservation (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
Private Attributes
SeedBase m_Seed
Constructor & Destructor Documentation
ActionRemoveSeed()
void ActionRemoveSeed () inline private
References ActionBase::m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Class::CastTo(), and m_Seed.
CreateConditionComponents()
override void CreateConditionComponents () inline private
References ActionBase::m_ConditionItem, ActionBase::m_ConditionTarget, and UAMaxDistances::SMALL.
GetInputType()
override GetInputType () inline private
InventoryReservation()
override bool InventoryReservation (ActionData action_data) inline private
References GameInventory::c_InventoryReservationTimeoutMS, and m_Seed.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
References ActionBase::ClearInventoryReservationEx(), InventoryLocation::GetSlot(), m_Seed, and InventoryLocation::SetHands().
Field Documentation
m_Seed
SeedBase m_Seed private
Referenced by ActionCondition(), InventoryReservation(), and OnExecuteClient().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionRemoveSeed.c