DayZ Scripts: ActionTakeMaterialToHandsSwitch Class Reference
ActionTakeMaterialToHandsSwitch Class Reference
DEPRECATED.
Private Member Functions
void ActionTakeMaterialToHandsSwitch ()
override void CreateConditionComponents ()
override bool IsInstant ()
override bool RemoveForceTargetAfterUse ()
override bool UseAcknowledgment ()
override GetInputType ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void Start (ActionData action_data)
Detailed Description
DEPRECATED.
Constructor & Destructor Documentation
ActionTakeMaterialToHandsSwitch()
void ActionTakeMaterialToHandsSwitch () inline private
References ActionBase::m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References ConstructionActionData::GetAttachmentsToDetachCount(), BaseBuildingBase::IsPlayerInside(), and ConstructionActionData::RefreshAttachmentsToDetach().
CreateConditionComponents()
override void CreateConditionComponents () inline private
References UAMaxDistances::BASEBUILDING, ActionBase::m_ConditionItem, and ActionBase::m_ConditionTarget.
GetInputType()
override GetInputType () inline private
IsInstant()
override bool IsInstant () inline private
RemoveForceTargetAfterUse()
override bool RemoveForceTargetAfterUse () inline private
Start()
override void Start (ActionData action_data) inline private
References ConstructionActionData::SetNextAttachmentIndex().
UseAcknowledgment()
override bool UseAcknowledgment () inline private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionTakeMaterialToHandsSwitch.c