DayZ Scripts: VomitSymptom Class Reference
VomitSymptom Class Reference
Private Member Functions
override void OnInit ()
bool IsContaminationActive ()
override void SetParam (Param p)
override void OnAnimationStart ()
override void OnAnimationFinish ()
override bool CanActivate ()
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override SmptAnimMetaBase SpawnAnimMetaObject ()
override bool IsSyncToRemotes ()
Private Attributes
const int BLOOD_LOSS = 250
private float m_VomitContentPercentage
Static Private Attributes
static const float STAMINA_DEPLETION_MULTIPLIER = 1.3
static const float STAMINA_RECOVERY_MULTIPLIER = 0.5
Member Function Documentation
CanActivate()
override bool CanActivate () inline private
References SymptomManager::GetCurrentCommandID(), and SymptomBase::m_Manager.
IsContaminationActive()
bool IsContaminationActive () inline private
References SymptomBase::m_Player.
Referenced by OnAnimationFinish(), and OnAnimationStart().
IsSyncToRemotes()
override bool IsSyncToRemotes () inline private
OnAnimationFinish()
override void OnAnimationFinish () inline private
deplete stamina
References GetPlugin(), IsContaminationActive(), SymptomBase::m_Player, and PluginLifespan().
OnAnimationStart()
override void OnAnimationStart () inline private
References BLOOD_LOSS, IsContaminationActive(), SymptomBase::m_Player, and m_VomitContentPercentage.
OnGetActivatedServer()
override void OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
References SymptomBase::GetDuration(), and SymptomBase::PlayAnimationFB().
OnInit()
override void OnInit () inline private
References SymptomBase::m_DestroyOnAnimFinish, SymptomBase::m_Duration, SymptomBase::m_ID, SymptomBase::m_MaxCount, SymptomBase::m_Priority, SymptomBase::m_SymptomType, and SymptomBase::m_SyncToClient.
SetParam()
override void SetParam (Param p) inline private
References m_VomitContentPercentage.
SpawnAnimMetaObject()
override SmptAnimMetaBase SpawnAnimMetaObject () inline private
Field Documentation
BLOOD_LOSS
const int BLOOD_LOSS = 250 private
Referenced by OnAnimationStart().
m_VomitContentPercentage
private float m_VomitContentPercentage private
Referenced by OnAnimationStart(), and SetParam().
STAMINA_DEPLETION_MULTIPLIER
const float STAMINA_DEPLETION_MULTIPLIER = 1.3 static private
Referenced by StaminaHandler::Init().
STAMINA_RECOVERY_MULTIPLIER
const float STAMINA_RECOVERY_MULTIPLIER = 0.5 static private
Referenced by StaminaHandler::Init().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerSymptoms/States/Primary/VomitState.c