DayZ Scripts: SmokeSimulation Class Reference
SmokeSimulation Class Reference
Private Member Functions
void SmokeSimulation ()
void OnFire (Entity flare)
void ~SmokeSimulation ()
Private Attributes
protected Particle m_ParMainSmoke
int particle_id
Detailed Description
Definition at line 1 of file SmokeSimulation.c.
Constructor & Destructor Documentation
SmokeSimulation()
void SmokeSimulation () inline private
Definition at line 6 of file SmokeSimulation.c.
References ParticleList::GRENADE_M18_PURPLE_LOOP, and particle_id.
~SmokeSimulation()
void ~SmokeSimulation () inline private
Definition at line 17 of file SmokeSimulation.c.
References m_ParMainSmoke, and Particle::Stop().
Member Function Documentation
OnFire()
void OnFire (Entity flare) inline private
Definition at line 11 of file SmokeSimulation.c.
References m_ParMainSmoke, particle_id, ParticleManager(), and Particle::SetWiggle().
Field Documentation
m_ParMainSmoke
protected Particle m_ParMainSmoke private
Definition at line 3 of file SmokeSimulation.c.
Referenced by OnFire(), and ~SmokeSimulation().
particle_id
int particle_id private
Definition at line 4 of file SmokeSimulation.c.
Referenced by OnFire(), SmokeSimulation(), and SmokeSimulation_Green::SmokeSimulation_Green().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Firearms/SmokeSimulation.c