DayZ Scripts: Land_Underground_EntranceBase Class Reference
Land_Underground_EntranceBase Class Reference
Private Member Functions
void Land_Underground_EntranceBase ()
void CreateLights ()
void ~Land_Underground_EntranceBase ()
void CleanUpOnDeleteClient ()
void CleanUpOnClosedClient ()
bool CanManipulate (Param param=null)
void Manipulate (Param param=null)
void NavmeshUpdate ()
void OnUpdateClient (float timeSlice)
override void EOnPostSimulate (IEntity other, float timeSlice)
void OnUpdateServer ()
void GetConnectedPanels (array< Land_Underground_Panel > panels)
bool CheckShouldPlayPersistent (EUndegroundEntranceState state, EUndegroundEntranceState lastValidState)
float AdjustTime (float originalTime, float adjustedTime=-1)
float GetOpeningTime ()
void RequestLatentTransition (float time, EUndegroundEntranceState targetState=EUndegroundEntranceState.UNINITIALIZED)
void SetDoorStateServer (EUndegroundEntranceState newState)
void OnDoorStateChangedServer (EUndegroundEntranceState newState)
void OnDoorStateChangedClient (EUndegroundEntranceState newState, EUndegroundEntranceState prevState)
void OpenServer (bool force=false)
void HandleVisualPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState)
void HandleAudioPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState)
void OnFinishedTimerServer ()
override void OnVariablesSynchronized ()
bool IsInitDoorStateSync ()
Private Attributes
EUndegroundEntranceState m_DoorState = EUndegroundEntranceState.CLOSED
EUndegroundEntranceState m_DoorStatePrev = EUndegroundEntranceState.UNINITIALIZED
float m_AnimPhase
ref AnimationTimer m_AnimTimerDoorServer
ref Timer m_NavmeshTimer
ref array< Land_Underground_Panel > m_ConnectedPanels
EUndegroundDoorType m_DoorType
EntranceLight m_InteriorLight1
EntranceLight m_InteriorLight2
EntranceLight m_InteriorLight3
Detailed Description
Definition at line 51 of file Land_Underground_Entrance.c.
Constructor & Destructor Documentation
Land_Underground_EntranceBase()
void Land_Underground_EntranceBase () inline private
Definition at line 65 of file Land_Underground_Entrance.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CreateLights(), CGame::GetCallQueue(), GetGame(), EnumTools::GetLastEnumValue(), Land_Underground_Panel(), and m_DoorType.
~Land_Underground_EntranceBase()
void ~Land_Underground_EntranceBase () inline private
Definition at line 79 of file Land_Underground_Entrance.c.
References CleanUpOnDeleteClient(), and Land_Underground_Panel().
Member Function Documentation
AdjustTime()
float AdjustTime (float originalTime, float adjustedTime = -1) inline private
Definition at line 152 of file Land_Underground_Entrance.c.
Referenced by Land_Underground_Stairs_Exit::GetOpeningTime(), OnDoorStateChangedServer(), Land_Underground_Stairs_Exit::OnDoorStateChangedServer(), and OnUpdateServer().
CanManipulate()
bool CanManipulate (Param param = null) inline private
Definition at line 98 of file Land_Underground_Entrance.c.
References m_DoorState.
Referenced by CanInteract().
CheckShouldPlayPersistent()
bool CheckShouldPlayPersistent (EUndegroundEntranceState state, EUndegroundEntranceState lastValidState) inline private
Definition at line 147 of file Land_Underground_Entrance.c.
References IsInitDoorStateSync(), and m_DoorState.
Referenced by HandleAudioPlayback(), and HandleVisualPlayback().
CleanUpOnClosedClient()
void CleanUpOnClosedClient () private
Referenced by CleanUpOnDeleteClient(), and OnDoorStateChangedClient().
CleanUpOnDeleteClient()
void CleanUpOnDeleteClient () inline private
Definition at line 89 of file Land_Underground_Entrance.c.
References CleanUpOnClosedClient().
Referenced by ~Land_Underground_EntranceBase().
CreateLights()
void CreateLights () private
Referenced by Land_Underground_EntranceBase().
EOnPostSimulate()
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 115 of file Land_Underground_Entrance.c.
References OnUpdateClient().
GetConnectedPanels()
void GetConnectedPanels (array< Land_Underground_Panel > panels) inline private
Definition at line 129 of file Land_Underground_Entrance.c.
References Land_Underground_Panel().
Referenced by OnDoorStateChangedClient().
GetOpeningTime()
float GetOpeningTime () inline private
Definition at line 170 of file Land_Underground_Entrance.c.
Referenced by OnDoorStateChangedServer(), and OnUpdateServer().
HandleAudioPlayback()
void HandleAudioPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState) private
Referenced by OnDoorStateChangedClient().
HandleVisualPlayback()
void HandleVisualPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState) private
Referenced by OnDoorStateChangedClient().
IsInitDoorStateSync()
bool IsInitDoorStateSync () inline private
Definition at line 244 of file Land_Underground_Entrance.c.
References m_DoorStatePrev.
Referenced by CheckShouldPlayPersistent().
Manipulate()
void Manipulate (Param param = null) inline private
Definition at line 103 of file Land_Underground_Entrance.c.
References OpenServer().
Referenced by Interact().
NavmeshUpdate()
void NavmeshUpdate () inline private
Definition at line 108 of file Land_Underground_Entrance.c.
References GetGame(), and CGame::UpdatePathgraphRegionByObject().
Referenced by OnDoorStateChangedServer().
OnDoorStateChangedClient()
void OnDoorStateChangedClient (EUndegroundEntranceState newState, EUndegroundEntranceState prevState) inline private
Definition at line 193 of file Land_Underground_Entrance.c.
References CleanUpOnClosedClient(), GetConnectedPanels(), HandleAudioPlayback(), HandleVisualPlayback(), Land_Underground_Panel(), and m_ConnectedPanels.
Referenced by OnVariablesSynchronized().
OnDoorStateChangedServer()
void OnDoorStateChangedServer (EUndegroundEntranceState newState) private
Referenced by SetDoorStateServer().
OnFinishedTimerServer()
void OnFinishedTimerServer () private
OnUpdateClient()
void OnUpdateClient (float timeSlice) private
Referenced by EOnPostSimulate().
OnUpdateServer()
void OnUpdateServer () inline private
Definition at line 122 of file Land_Underground_Entrance.c.
References AdjustTime(), GetOpeningTime(), AnimationTimer::GetValue(), m_AnimPhase, and m_AnimTimerDoorServer.
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Definition at line 233 of file Land_Underground_Entrance.c.
References m_DoorState, m_DoorStatePrev, and OnDoorStateChangedClient().
OpenServer()
void OpenServer (bool force = false) inline private
Definition at line 219 of file Land_Underground_Entrance.c.
References GetGame(), m_DoorState, CGame::RegisterNetworkStaticObject(), and SetDoorStateServer().
Referenced by Manipulate().
RequestLatentTransition()
void RequestLatentTransition (float time, EUndegroundEntranceState targetState = EUndegroundEntranceState.UNINITIALIZED) inline private
Definition at line 175 of file Land_Underground_Entrance.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), m_DoorState, and SetDoorStateServer().
Referenced by OnDoorStateChangedServer(), and Land_Underground_Stairs_Exit::OnDoorStateChangedServer().
SetDoorStateServer()
void SetDoorStateServer (EUndegroundEntranceState newState) inline private
Definition at line 184 of file Land_Underground_Entrance.c.
References m_DoorState, and OnDoorStateChangedServer().
Referenced by OpenServer(), and RequestLatentTransition().
Field Documentation
m_AnimPhase
float m_AnimPhase private
Definition at line 55 of file Land_Underground_Entrance.c.
Referenced by OnUpdateServer().
m_AnimTimerDoorServer
ref AnimationTimer m_AnimTimerDoorServer private
Definition at line 56 of file Land_Underground_Entrance.c.
Referenced by Land_Underground_Stairs_Exit::OnDoorStateChangedServer(), and OnUpdateServer().
m_ConnectedPanels
ref array<Land_Underground_Panel> m_ConnectedPanels private
Definition at line 58 of file Land_Underground_Entrance.c.
Referenced by OnDoorStateChangedClient().
m_DoorState
EUndegroundEntranceState m_DoorState = EUndegroundEntranceState.CLOSED private
Definition at line 53 of file Land_Underground_Entrance.c.
Referenced by CanManipulate(), CheckShouldPlayPersistent(), OnVariablesSynchronized(), OpenServer(), RequestLatentTransition(), and SetDoorStateServer().
m_DoorStatePrev
EUndegroundEntranceState m_DoorStatePrev = EUndegroundEntranceState.UNINITIALIZED private
Definition at line 54 of file Land_Underground_Entrance.c.
Referenced by IsInitDoorStateSync(), and OnVariablesSynchronized().
m_DoorType
EUndegroundDoorType m_DoorType private
Definition at line 59 of file Land_Underground_Entrance.c.
Referenced by GetLinkedDoorType(), Land_Underground_EntranceBase(), and Land_Underground_Stairs_Exit::Land_Underground_Stairs_Exit().
m_InteriorLight1
EntranceLight m_InteriorLight1 private
Definition at line 61 of file Land_Underground_Entrance.c.
Referenced by Land_Underground_Stairs_Exit::CreateLights().
m_InteriorLight2
EntranceLight m_InteriorLight2 private
Definition at line 62 of file Land_Underground_Entrance.c.
Referenced by Land_Underground_Stairs_Exit::CreateLights().
m_InteriorLight3
EntranceLight m_InteriorLight3 private
Definition at line 63 of file Land_Underground_Entrance.c.
m_NavmeshTimer
ref Timer m_NavmeshTimer private
Definition at line 57 of file Land_Underground_Entrance.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Building/Underground/Entrance/Land_Underground_Entrance.c