DayZ Scripts: 3_Game/human.c File Reference
human.c File Reference
Data Structures
class HumanInputController
class HumanAnimInterface
class HumanCommandMove
class HumanCommandMelee2
class HumanCommandDeathCallback
class HumanCommandUnconscious
class HumanCommandLadder
class HumanCommandVehicle
class HumanCommandClimb
command itself
class HumanCommandWeapons
class HumanMovementState
Typedefs
typedef int TAnimGraphVariable
typedef int TAnimGraphTag
typedef int TAnimGraphEvent
Enumerations
enum HumanInputControllerOverrideType { DISABLED , ENABLED , ONE_FRAME }
enum ClimbStates {
STATE_MOVE , STATE_TAKEOFF , STATE_ONTOP , STATE_FALLING ,
STATE_FINISH
}
state of climb command
enum WeaponActions {
INTERRUPT = 15 , NONE = -1 , RELOAD = 0 , MECHANISM = 1 ,
CHAMBERING = 2 , CHAMBERING_LOADER = 3 , UNJAMMING = 4 , FIRE = 5 ,
HIDE = 6 , SHOW = 7 , RELOAD_CLIP = 8
}
actions
enum WeaponActionReloadTypes {
RELOADRIFLE_MAGAZINE_BULLET = 0 , RELOADRIFLE_NOMAGAZINE_BULLET = 1 , RELOADRIFLE_MAGAZINE_NOBULLET = 2 , RELOADRIFLE_NOMAGAZINE_NOBULLET = 3 ,
RELOADRIFLE_MAGAZINE_NOBULLET_OPEN = 4 , RELOADRIFLE_NOMAGAZINE_NOBULLET_OPEN = 5 , RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_UNCOCKED = 8 , RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_UNCOCKED = 9 ,
RELOADPISTOL_MAGAZINE_BULLET_CLOSED = 10 , RELOADPISTOL_NOMAGAZINE_BULLET_CLOSED = 11 , RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_COCKED = 12 , RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_COCKED = 13 ,
RELOADPISTOL_NOMAGAZINE_NOBULLET_OPENED = 14 , RELOADPISTOL_MAGAZINE_NOBULLET_OPENED = 15 , RELOAD_MAGAZINE_DETACH = 16 , RELOADRIFLE_MAGAZINE_DETACH = 17 ,
RELOADSRIFLE_MAGAZINE_BULLET = 20 , RELOADSRIFLE_NOMAGAZINE_BULLET = 21 , RELOADSRIFLE_MAGAZINE_NOBULLET = 22 , RELOADSRIFLE_NOMAGAZINE_NOBULLET = 23
}
enum WeaponActionReloadClipTypes { RELOADRIFLE_CLIP_NOBULLET = 0 , RELOADRIFLE_CLIP_BULLET = 1 }
enum WeaponActionChamberingTypes {
CHAMBERING_END = -1 , CHAMBERING_ONEBULLET_OPENED = 0 , CHAMBERING_ONEBULLET_CLOSED = 1 , CHAMBERING_ONEBULLET_CLOSED_UNCOCKED = 2 ,
CHAMBERING_ONEBULLET_UNIQUE_OPENED = 3 , CHAMBERING_ONEBULLET_UNIQUE_CLOSED = 4 , CHAMBERING_TWOBULLETS_START = 6 , CHAMBERING_TWOBULLETS_END = 7 ,
CHAMBERING_STARTLOOPABLE_CLOSED = 10 , CHAMBERING_ENDLOOPABLE = 11 , CHAMBERING_STARTLOOPABLE_CLOSED_KEEP = 12 , CHAMBERING_STARTLOOPABLE_OPENED = 13 ,
CHAMBERING_STARTLOOPABLE_SHOTGUN_UNCOCKED = 15 , CHAMBERING_STARTLOOPABLE_SHOTGUN_COCKED = 16 , CHAMBERING_DOUBLE_1 = 17 , CHAMBERING_DOUBLE_2 = 18 ,
CHAMBERING_DOUBLE_3 = 19 , CHAMBERING_DOUBLE_4 = 20 , CHAMBERING_CROSSBOW_OPENED = 21 , CHAMBERING_CROSSBOW_CLOSED = 22 ,
CHAMBERING_CROSSBOW_FULL = 23
}
enum WeaponActionChamberingLoaderTypes { CHAMBERINGLOADER_OPENED = 0 , CHAMBERINGLOADER_CLOSED = 1 }
enum WeaponActionUnjammingTypes { UNJAMMING_START = 1 , UNJAMMING_END = 0 , UNJAMMING_INTERRUPT = -1 }
enum WeaponActionFireTypes {
FIRE_NORMAL = 0 , FIRE_LAST = 1 , FIRE_COCKED = 2 , FIRE_UNCOCKED = 3 ,
FIRE_DRY = 4 , FIRE_JAM = 5
}
enum WeaponHideShowTypes {
HIDESHOW_SLOT_2HDLEFTBACK = 0 , HIDESHOW_SLOT_RFLLEFTBACK = 1 , HIDESHOW_SLOT_1HDLEFTBACK = 2 , HIDESHOW_SLOT_2HDRIGHTBACK = 3 ,
HIDESHOW_SLOT_RFLRIGHTBACK = 4 , HIDESHOW_SLOT_1HDRIGHTBACK = 5 , HIDESHOW_SLOT_PISTOLBELT = 6 , HIDESHOW_SLOT_PISTOLCHEST = 7 ,
HIDESHOW_SLOT_KNIFEBACK = 8 , HIDESHOW_SLOT_INVENTORY = 9
}
enum WeaponEvents {
ATTACHMENT_HIDE , ATTACHMENT_SHOW , BULLET_EJECT , BULLET_HIDE ,
BULLET_HIDE2 , BULLET_IN_CHAMBER , BULLET_IN_MAGAZINE , BULLET_SHOW ,
BULLET_SHOW2 , CANUNJAM_END , CANUNJAM_START , COCKED ,
MAGAZINE_ATTACHED , MAGAZINE_DETACHED , MAGAZINE_HIDE , MAGAZINE_SHOW ,
SLIDER_OPEN , UNJAMMED , HAMMER_UNCOCKED , CHANGE_HIDE ,
CHANGE_SHOW , CYLINDER_ROTATE
}
events
enum HumanMoveCommandID
do not process rotations !
Functions
class HumanAnimInterface HumanCommandActionCallback ()
private void HumanAnimInterface ()
private void ~HumanAnimInterface ()
proto native TAnimGraphCommand BindCommand (string pCommandName)
returns command index -
proto native TAnimGraphVariable BindVariableFloat (string pVariable)
proto native TAnimGraphVariable BindVariableInt (string pVariable)
proto native TAnimGraphVariable BindVariableBool (string pVariable)
proto native TAnimGraphTag BindTag (string pTagName)
proto native TAnimGraphEvent BindEvent (string pEventName)
private void ~HumanCommandActionCallback ()
proto native Human GetHuman ()
get the human this cb belongs to
proto native void Cancel ()
cancels action
proto native void InternalCommand (int pInternalCommandId)
proto native void SetAligning (vector pPositionWS, vector pDirectionWS)
enables character aligning to desired position and direction in world space
proto native void ResetAligning ()
disables character aligning
proto native void EnableCancelCondition (bool pEnable)
proto native bool DefaultCancelCondition ()
system implemented cancel condition (now raise or sprint cancels action)
proto native void RegisterAnimationEvent (string pAnimationEventStr, int pId)
registers animation event, when event registered and received - it sends OnAnimationEvent with registered id
proto native void EnableStateChangeCallback ()
enables state change callback OnStateChange
proto native int GetState ()
returns one of STATE_...
static string GetStateString (int pState)
returns debug string of current state
string GetStateString ()
returns debug string of current state
void OnAnimationEvent (int pEventID)
calls animation event -> must be registered with RegisterAnimationEvent
void OnFinish (bool pCanceled)
called ALWAYS! when action is finished (normal finish or cancel -> pCanceled)
void OnStateChange (int pOldState, int pCurrentState)
called when enabled by EnableStateChangeCallback and state changes, call GetState() to get actual state
bool IsUserActionCallback ()
bool IsGestureCallback ()
bool IsSymptomCallback ()
class HumanCommandMove HumanCommandMelee ()
private void HumanCommandMove ()
private void ~HumanCommandMove ()
proto native float GetCurrentMovementAngle ()
proto bool GetCurrentInputAngle (out float pAngle)
proto native float GetCurrentMovementSpeed ()
0,1,2..3 idle, walk, run, sprint
proto native bool IsChangingStance ()
returns true if character is changing stance
proto native bool IsOnBack ()
return true if prone is on back
proto native bool IsInRoll ()
return true if character barrel rolling
proto native bool IsLeavingUncon ()
return true if character transitions out of uncon
proto native bool IsStandingFromBack ()
return true if prone on back is chaning to crounch/stand
proto native void StartMeleeEvade ()
marks command to continue to combo
proto native void StartMeleeEvadeA (float pDirAngle)
marks command to continue to combo, pDirAngle specifies angle
proto native bool IsMeleeEvade ()
this is true when in melee evade
proto native void SetMeleeBlock (bool pBlock)
this enables/disables block
proto native void ForceStance (int pStanceIdx)
proto native void ForceStanceUp (int pStanceIdx)
proto native void SetRunSprintFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fRunSpringTimeout
proto native void SetDirectionFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterTimeout
proto native void SetDirectionSprintFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterSprintTimeout
proto native void SetTurnSpanModifier (float value)
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingFilterSpan
proto native void SetTurnSpanSprintModifier (float value)
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingSprintFilterSpan
proto native void SetCurrentWaterLevel (float value)
sets water level (depth)
private void ~HumanCommandMelee ()
proto native void ContinueCombo ()
marks command to continue to combo
proto native bool IsInComboRange ()
returns true if hit is in range, where person can continue to combo
proto native bool WasHit ()
is true only once after hit event
class HumanCommandMelee2 HumanCommandFall ()
private void HumanCommandMelee2 ()
private void ~HumanCommandMelee2 ()
proto native void ContinueCombo (bool pHeavyHit, float pComboValue, EntityAI target=null, vector hitPos=vector.Zero)
marks command to continue to combo
proto native int GetComboCount ()
proto native int GetCurrentHitType ()
proto native bool IsFinisher ()
private void ~HumanCommandFall ()
proto native bool PhysicsLanded ()
this is true when fall has physically landed - need to call Land after this is true
proto native void Land (int pLandType)
end fall with land
proto native bool IsLanding ()
returns true if fall is in landing state
class HumanCommandDeathCallback HumanCommandDeath ()
void OnSimulationEnd ()
bool ShouldSimulationBeDisabled ()
'OnSimulationEnd' is called before this
private void ~HumanCommandDeath ()
class HumanCommandUnconscious HumanCommandDamage ()
private void HumanCommandUnconscious ()
private void ~HumanCommandUnconscious ()
proto native void WakeUp (int targetStance=-1)
proto native bool IsWakingUp ()
proto native bool IsOnLand ()
proto native bool IsInWater ()
private void ~HumanCommandDamage ()
class HumanCommandLadder HumanCommandSwim ()
private void HumanCommandLadder ()
private void ~HumanCommandLadder ()
proto native bool CanExit ()
returns true if on exiting point
proto native void Exit ()
proto static native bool DebugDrawLadder (Building pBuilding, int pLadderIndex)
debug draws any ladder
proto static native int DebugGetLadderIndex (string pComponentName)
proto native vector GetLogoutPosition ()
private void ~HumanCommandSwim ()
proto native void StopSwimming ()
proto static native vector WaterLevelCheck (Human pHuman, vector pPosition)
private void HumanCommandClimb ()
private void ~HumanCommandClimb ()
proto native vector GetGrabPointWS ()
returns world space position of climbing grab point
proto native vector GetClimbOverStandPointWS ()
returns world space position of landspot after climbing over
proto static native bool DoClimbTest (Human pHuman, SHumanCommandClimbResult pResult, int pDebugDrawLevel)
proto static native bool DebugDrawClimb (Human pHuman, int pLevel)
private void ~HumanCommandFullBodyDamage ()
string WeaponActionTypeToString (int A, int AT)
class HumanCommandWeapons HumanCommandAdditives ()
private void HumanCommandWeapons ()
private void ~HumanCommandWeapons ()
proto native bool IsActionFinished ()
proto native int GetRunningAction ()
returns -1 when no action is running or RELOAD,MECHANISM, ....
proto native int GetRunningActionType ()
returns -1 when no action is running or appropriate action type
proto native void SetActionProgressParams (float pStart, float pEnd)
sets start and end animation position - f.e. for reload clip action
proto native bool StartAction (WeaponActions pAction, int pActionType)
start reload,mechanism,chambering,unjam ...
proto native void RegisterEvent (string pName, int pId)
register events
proto native int IsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
proto native bool IsInWeaponReloadBulletSwitchState ()
returns true when clip visual change is needed for reload clip action
proto native void SetADS (bool pState)
sets head tilt to optics
proto native void LiftWeapon (bool pState)
command for lifting weapon near obstacled (works only when weapon is raised)
void RegisterDefaultEvents ()
proto native void SetInitState (int pFrameIndex)
proto static native void StaticSetInitState (Human pHuman, int pFrameIdx)
just static version of SetInitState
proto native float GetBaseAimingAngleUD ()
returns base aiming angle UD - without sway/offsets/...
proto native float GetBaseAimingAngleLR ()
returns base aiming angle LR - without sway/offsets/...
proto native void SetThrowingMode (bool pState)
proto native bool IsThrowingMode ()
proto native void ThrowItem (int throwType)
proto native bool WasItemLeaveHandsEvent ()
proto native int DebugIsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
proto native void DebugResetEvents ()
private void ~HumanCommandAdditives ()
proto native void SetInjured (float pValue, bool pInterpolate)
sets injury level 0..1, interpolate == false -> resets the value, otherwise it's interpolating towards the new value
proto native void SetExhaustion (float pValue, bool pInterpolate)
sets exhaustion level 0..1, interpolate == false -> resets the value, otherwise it's interpolating towards the new value
proto native void SetTalking (bool pValue)
sets talking
proto native void StartModifier (int pType)
starts modifier
proto native void CancelModifier ()
cancels modifier
proto native bool IsModifierActive ()
is modifier active
class HumanMovementState OnActivate ()
HumanCommandScript fully scriptable command.
bool IsRaised ()
bool IsRaisedInProne ()
bool IsInProne ()
bool IsInRaisedProne ()
bool IsLeaning ()
void OnDeactivate ()
called when command ends
proto native void SetFlagFinished (bool pFinished)
this terminates human command script and shows CommandHandler(... pCurrentCommandFinished == true);
void PreAnimUpdate (float pDt)
proto native void PreAnim_CallCommand (int pCommand, int pParamInt, float pParamFloat)
function usable in PreAnimUpdate or in !!! OnActivate !!!
proto native void PreAnim_SetFloat (int pVar, float pFlt)
proto native void PreAnim_SetInt (int pVar, int pInt)
proto native void PreAnim_SetBool (int pVar, bool pBool)
proto native void PreAnim_SetFilteredHeading (float pYawAngle, float pFilterDt, float pMaxYawSpeed)
sets character rotation (heading)
void PrePhysUpdate (float pDt)
proto native bool PrePhys_IsEvent (int pEvent)
script function usable in PrePhysUpdate
proto native bool PrePhys_IsTag (int pTag)
proto native bool PrePhys_GetTranslation (out vector pOutTransl)
proto native bool PrePhys_GetRotation (out float pOutRot[4])
proto native void PrePhys_SetTranslation (vector pInTransl)
proto native void PrePhys_SetRotation (float pInRot[4])
bool PostPhysUpdate (float pDt)
proto native void PostPhys_GetPosition (out vector pOutTransl)
script function usable in PostPhysUpdate
proto native void PostPhys_GetRotation (out float pOutRot[4])
vec3 in world space
proto native void PostPhys_SetPosition (vector pInTransl)
quaternion in world space
proto native void PostPhys_SetRotation (float pInRot[4])
vec3 in world space
proto native void PostPhys_LockRotation ()
quaternion in world space
enum HumanMoveCommandID GetTransformWS (out vector pTm[4])
gets human transform in World Space
proto native bool CheckFreeSpace (vector localDir, float distance, bool useHeading, vector posOffset=vector.Zero, float xzScale=1.0)
makes test if there's enough space for character's collider assuming that character can be pushed away from obstacle - usable for checking if character is in some tight space
proto float CollisionMoveTest (vector dir, vector offset, float xzScale, IEntity ignoreEntity, out IEntity hitEntity, out vector hitPosition, out vector hitNormal)
makes test if character can physically move in given direction - length of dir means distance, returns distance fraction
proto native void LinkToLocalSpaceOf (notnull IEntity child, vector pLocalSpaceMatrix[4])
proto native void UnlinkFromLocalSpace ()
proto native int GetBoneIndexByName (string pBoneName)
returns bone index for a name (-1 if pBoneName doesn't exist)
proto native HumanAnimInterface GetAnimInterface ()
returns animation interface - usable in HumanCommandScript implementations
proto native bool PhysicsIsFalling (bool pValidate)
returns true if physics controller is falling
proto native void PhysicsGetVelocity (out vector pVelocity)
outs pVelocity - linear velocity of PHYSICS CONTROLLER
proto native void PhysicsEnableGravity (bool pEnable)
proto native bool PhysicsIsSolid ()
proto native void PhysicsSetSolid (bool pSolid)
proto native void PhysicsSetRagdoll (bool pEnable)
Sets and synchronize interaction layers 'RAGDOLL' and 'RAGDOLL_NO_CHARACTER' to prevent body stacking and players going through dead creatures.
proto native HumanInputController GetInputController ()
returns human input controller
proto native HumanItemAccessor GetItemAccessor ()
proto native void GetMovementState (HumanMovementState pState)
returns movement state (current command id,)
proto native int GetCurrentCommandID ()
returns current command ID (see DayZPlayerConstants.COMMANDID_...)
proto native HumanCommandMove StartCommand_Move ()
--— MOVE --—
proto native HumanCommandMove GetCommand_Move ()
proto native HumanCommandMelee StartCommand_Melee (EntityAI pTarget)
--— MELEE --—
proto native HumanCommandMelee GetCommand_Melee ()
proto native HumanCommandMelee2 StartCommand_Melee2 (EntityAI pTarget, int pHitType, float pComboValue, vector hitPos=vector.Zero)
starts command - melee2
proto native HumanCommandMelee2 GetCommand_Melee2 ()
proto native HumanCommandFall StartCommand_Fall (float pYVelocity)
--— FALL --—
proto native HumanCommandFall GetCommand_Fall ()
proto native HumanCommandLadder StartCommand_Ladder (Building pBuilding, int pLadderIndex)
--— LADDER --—
proto native HumanCommandLadder GetCommand_Ladder ()
proto native HumanCommandSwim StartCommand_Swim ()
--— LADDER --—
proto native HumanCommandSwim GetCommand_Swim ()
proto native HumanCommandVehicle StartCommand_Vehicle (Transport pTransport, int pTransportPositionIndex, int pVehicleSeat, bool fromUnconscious=false)
--— VEHICLE --—
proto native HumanCommandVehicle GetCommand_Vehicle ()
proto native HumanCommandClimb StartCommand_Climb (SHumanCommandClimbResult pClimbResult, int pType)
--— CLIMB --—
proto native HumanCommandClimb GetCommand_Climb ()
proto native HumanCommandDeathCallback StartCommand_Death (int pType, float pDirection, typename pCallbackClass)
--— Death --—
proto native HumanCommandDeathCallback GetCommand_Death ()
proto native HumanCommandUnconscious StartCommand_Unconscious (float pType)
starts command - unconscious
proto native HumanCommandUnconscious GetCommand_Unconscious ()
proto native HumanCommandFullBodyDamage StartCommand_Damage (int pType, float pDirection)
--— FullBody Damages --—
proto native HumanCommandFullBodyDamage GetCommand_Damage ()
proto native HumanCommandActionCallback StartCommand_Action (int pActionID, typename pCallbackClass, int pStanceMask)
--— ACTIONS --—
proto native HumanCommandActionCallback GetCommand_Action ()
is human is in command action - returns its callback, if current command is action
proto native int GetCommandModifierCount ()
proto native int GetCommandModifierID (int pIndex)
returns COMMANDID_ .. type id of command modifier on index pIndex
proto native HumanCommandAdditives GetCommandModifier_Additives ()
default (always-on modifiers)
proto native HumanCommandWeapons GetCommandModifier_Weapons ()
returns interface for handling weapons
proto native HumanCommandActionCallback AddCommandModifier_Action (int pActionID, typename pCallbackClass)
adds action command modifier, creates callback instance for you
proto native void DeleteCommandModifier_Action (HumanCommandActionCallback pCallback)
force remove - normally if action is ended or interrupted - this is not needed to call
proto native HumanCommandActionCallback GetCommandModifier_Action ()
returns callback for action if any is active, null if nothing runs
proto native HumanCommandDamage AddCommandModifier_Damage (int pType, float pDirection)
— modifier for light Damages
proto native void DeleteCommandModifier_Damage (HumanCommandDamage pDamage)
proto native HumanCommandDamage GetCommandModifier_Damage ()
proto native HumanCommandScript StartCommand_Script (HumanCommandScript pHumanCommand)
— SCRIPTED COMMANDS
proto native HumanCommandScript StartCommand_ScriptInst (typename pCallbackClass)
proto native HumanCommandScript GetCommand_Script ()
is human is in command action - returns its callback, if current command is action
proto native owned string DebugGetItemClass ()
returns current item's class name
proto native owned string DebugGetItemSuperClass ()
returns current item's class that is found in config
proto native owned string DebugGetItemAnimInstance ()
returns current item's animation instance
proto native void StartDeath ()
proto native void ResetDeath ()
proto native void ResetDeathCooldown ()
proto native bool IsDeathProcessed ()
proto native bool IsDeathConditionMet ()
void OnCommandMoveStart ()
void OnCommandMoveFinish ()
void OnCommandMeleeStart ()
void OnCommandMeleeFinish ()
void OnCommandMelee2Start ()
void OnCommandMelee2Finish ()
void OnCommandFallStart ()
void OnCommandFallFinish ()
void OnCommandClimbStart ()
void OnCommandClimbFinish ()
void OnCommandDeathStart ()
void OnCommandDeathFinish ()
void OnCommandUnconsciousStart ()
void OnCommandUnconsciousFinish ()
void OnCommandDamageFullbodyStart ()
void OnCommandDamageFullbodyFinish ()
void OnCommandDamageAdditiveStart ()
void OnCommandDamageAdditiveFinish ()
void OnCommandLadderStart ()
void OnCommandLadderFinish ()
void OnCommandSwimStart ()
void OnCommandSwimFinish ()
void OnCommandVehicleStart ()
void OnCommandVehicleFinish ()
void OnCommandActionFullbodyStart ()
void OnCommandActionFullbodyFinish ()
void OnCommandActionAdditiveStart ()
void OnCommandActionAdditiveFinish ()
void OnStanceChange (int previousStance, int newStance)
gets called on stance change
bool CanChangeStance (int previousStance, int newStance)
Called by code to see if it can.
bool CanRoll ()
void OnRollStart (bool isToTheRight)
void OnRollFinish ()
Variables
class HumanInputController TAnimGraphCommand
static const int STATE_NONE = 0
undef state - not running anymore
static const int STATE_LOOP_IN = 1
looped state
static const int STATE_LOOP_LOOP = 2
static const int STATE_LOOP_END = 3
static const int STATE_LOOP_END2 = 4
static const int STATE_LOOP_LOOP2 = 5
static const int STATE_LOOP_ACTION = 6
static const int STATE_NORMAL = 7
one time state
static const int HIT_TYPE_LIGHT = 0
static const int HIT_TYPE_HEAVY = 1
static const int HIT_TYPE_FINISHER = 2
static const int HIT_TYPE_FINISHER_NECK = 3
static const int LANDTYPE_NONE = 0
static const int LANDTYPE_LIGHT = 1
static const int LANDTYPE_MEDIUM = 2
static const int LANDTYPE_HEAVY = 3
class HumanCommandVehicle m_bIsClimb
result from static test
bool m_bIsClimbOver
bool m_bFinishWithFall
bool m_bHasParent
float m_fClimbHeight
vector m_ClimbGrabPoint
vector m_ClimbGrabPointNormal
grab point for climb && climb over (in local space of it's parent)
vector m_ClimbStandPoint
normal to grabpoint position (used for character orientation)
vector m_ClimbOverStandPoint
where climb ends (in local space of it's parent)
IEntity m_GrabPointParent
where climb over ends (in local space of it's parent)
IEntity m_ClimbStandPointParent
parent of grabpoint
IEntity m_ClimbOverStandPointParent
enum WeaponActions HumanCommandFullBodyDamage
enum WeaponActionReloadClipTypes MECHANISM_OPENED = 0
mechanism action types
enum WeaponActionReloadClipTypes MECHANISM_CLOSED = 1
enum WeaponActionReloadClipTypes MECHANISM_SPECIAL = 2
enum WeaponActionReloadClipTypes MECHANISM_CLOSED_UNCOCKED = 3
int m_CommandTypeId
int m_iStanceIdx
current command's id
int m_iMovement
current stance (DayZPlayerConstants.STANCEIDX_ERECT, ...), only if the command has a stance
float m_fLeaning
current movement (0 idle, 1 walk, 2-run, 3-sprint), only if the command has a movement
int m_LocalMovement = -1
leaning state (not all commands need to have all movements)
None = 0
CommandMove = 1
CommandMelee = 2
CommandMelee2 = 4
CommandFall = 8
CommandClimb = 16
CommandDeath = 32
CommandUnconscious = 64
CommandDamageFullbody = 128
CommandDamageAdditive = 256
CommandLadder = 512
CommandSwim = 1024
CommandVehicle = 2048
CommandActionFullbody = 4096
CommandActionAdditive = 8192
Detailed Description
this file is interface to Human
Typedef Documentation
TAnimGraphEvent
typedef int TAnimGraphEvent
TAnimGraphTag
typedef int TAnimGraphTag
TAnimGraphVariable
typedef int TAnimGraphVariable
Enumeration Type Documentation
ClimbStates
enum ClimbStates
state of climb command
Enumerator
STATE_MOVE
STATE_TAKEOFF
STATE_ONTOP
STATE_FALLING
STATE_FINISH
HumanInputControllerOverrideType
enum HumanInputControllerOverrideType
Enumerator
DISABLED
ENABLED
ONE_FRAME
Permenantly active until DISABLED is passed.
HumanMoveCommandID
enum HumanMoveCommandID
do not process rotations !
used in script-side identification of animation commands on human (swim, fall, move...)
WeaponActionChamberingLoaderTypes
enum WeaponActionChamberingLoaderTypes
Enumerator
CHAMBERINGLOADER_OPENED
CHAMBERINGLOADER_CLOSED
WeaponActionChamberingTypes
enum WeaponActionChamberingTypes
Enumerator
CHAMBERING_END
CHAMBERING_ONEBULLET_OPENED
chambering action types
CHAMBERING_ONEBULLET_CLOSED
CHAMBERING_ONEBULLET_CLOSED_UNCOCKED
CHAMBERING_ONEBULLET_UNIQUE_OPENED
CHAMBERING_ONEBULLET_UNIQUE_CLOSED
CHAMBERING_TWOBULLETS_START
CHAMBERING_TWOBULLETS_END
CHAMBERING_STARTLOOPABLE_CLOSED
CHAMBERING_ENDLOOPABLE
CHAMBERING_STARTLOOPABLE_CLOSED_KEEP
CHAMBERING_STARTLOOPABLE_OPENED
CHAMBERING_STARTLOOPABLE_SHOTGUN_UNCOCKED
CHAMBERING_STARTLOOPABLE_SHOTGUN_COCKED
CHAMBERING_DOUBLE_1
CHAMBERING_DOUBLE_2
CHAMBERING_DOUBLE_3
CHAMBERING_DOUBLE_4
CHAMBERING_CROSSBOW_OPENED
CHAMBERING_CROSSBOW_CLOSED
CHAMBERING_CROSSBOW_FULL
WeaponActionFireTypes
enum WeaponActionFireTypes
Enumerator
FIRE_NORMAL
FIRE_LAST
FIRE_COCKED
FIRE_UNCOCKED
FIRE_DRY
FIRE_JAM
WeaponActionReloadClipTypes
enum WeaponActionReloadClipTypes
Enumerator
RELOADRIFLE_CLIP_NOBULLET
RELOADRIFLE_CLIP_BULLET
WeaponActionReloadTypes
enum WeaponActionReloadTypes
action types reload action types
Enumerator
RELOADRIFLE_MAGAZINE_BULLET
reload action types - rifles
RELOADRIFLE_NOMAGAZINE_BULLET
RELOADRIFLE_MAGAZINE_NOBULLET
RELOADRIFLE_NOMAGAZINE_NOBULLET
RELOADRIFLE_MAGAZINE_NOBULLET_OPEN
RELOADRIFLE_NOMAGAZINE_NOBULLET_OPEN
RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_UNCOCKED
RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_UNCOCKED
RELOADPISTOL_MAGAZINE_BULLET_CLOSED
RELOADPISTOL_NOMAGAZINE_BULLET_CLOSED
RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_COCKED
RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_COCKED
RELOADPISTOL_NOMAGAZINE_NOBULLET_OPENED
RELOADPISTOL_MAGAZINE_NOBULLET_OPENED
RELOAD_MAGAZINE_DETACH
RELOADRIFLE_MAGAZINE_DETACH
RELOADSRIFLE_MAGAZINE_BULLET
RELOADSRIFLE_NOMAGAZINE_BULLET
RELOADSRIFLE_MAGAZINE_NOBULLET
RELOADSRIFLE_NOMAGAZINE_NOBULLET
WeaponActions
enum WeaponActions
actions
Enumerator
INTERRUPT
NONE
RELOAD
MECHANISM
CHAMBERING
CHAMBERING_LOADER
UNJAMMING
FIRE
HIDE
SHOW
RELOAD_CLIP
WeaponActionUnjammingTypes
enum WeaponActionUnjammingTypes
Enumerator
UNJAMMING_START
unjam action types
UNJAMMING_END
UNJAMMING_INTERRUPT
WeaponEvents
enum WeaponEvents
events
Enumerator
ATTACHMENT_HIDE
ATTACHMENT_SHOW
BULLET_EJECT
BULLET_HIDE
BULLET_HIDE2
BULLET_IN_CHAMBER
BULLET_IN_MAGAZINE
BULLET_SHOW
BULLET_SHOW2
CANUNJAM_END
CANUNJAM_START
COCKED
MAGAZINE_ATTACHED
MAGAZINE_DETACHED
MAGAZINE_HIDE
MAGAZINE_SHOW
SLIDER_OPEN
UNJAMMED
HAMMER_UNCOCKED
CHANGE_HIDE
CHANGE_SHOW
CYLINDER_ROTATE
WeaponHideShowTypes
enum WeaponHideShowTypes
Enumerator
HIDESHOW_SLOT_2HDLEFTBACK
HIDESHOW_SLOT_RFLLEFTBACK
HIDESHOW_SLOT_1HDLEFTBACK
HIDESHOW_SLOT_2HDRIGHTBACK
HIDESHOW_SLOT_RFLRIGHTBACK
HIDESHOW_SLOT_1HDRIGHTBACK
HIDESHOW_SLOT_PISTOLBELT
HIDESHOW_SLOT_PISTOLCHEST
HIDESHOW_SLOT_KNIFEBACK
HIDESHOW_SLOT_INVENTORY
Function Documentation
AddCommandModifier_Action()
proto native HumanCommandActionCallback AddCommandModifier_Action (int pActionID, typename pCallbackClass)
adds action command modifier, creates callback instance for you
Referenced by DayZPlayer::CommandHandler().
AddCommandModifier_Damage()
proto native HumanCommandDamage AddCommandModifier_Damage (int pType, float pDirection)
— modifier for light Damages
starts additive damage
Referenced by DayZPlayer::CommandHandlerDebug(), and DayZPlayer::HandleDamageHit().
BindCommand()
proto native TAnimGraphCommand BindCommand (string pCommandName)
returns command index -
BindEvent()
proto native TAnimGraphEvent BindEvent (string pEventName)
BindTag()
proto native TAnimGraphTag BindTag (string pTagName)
BindVariableBool()
proto native TAnimGraphVariable BindVariableBool (string pVariable)
BindVariableFloat()
proto native TAnimGraphVariable BindVariableFloat (string pVariable)
BindVariableInt()
proto native TAnimGraphVariable BindVariableInt (string pVariable)
Cancel()
proto native void Cancel ()
cancels action
cancels command melee and goes to HumanCommandMove
Referenced by CABase::Interrupt().
CancelModifier()
proto native void CancelModifier ()
cancels modifier
CanChangeStance()
bool CanChangeStance (int previousStance, int newStance)
Called by code to see if it can.
CanExit()
proto native bool CanExit ()
returns true if on exiting point
CanRoll()
bool CanRoll ()
CheckFreeSpace()
proto native bool CheckFreeSpace (vector localDir, float distance, bool useHeading, vector posOffset = vector.Zero, float xzScale = 1.0)
makes test if there's enough space for character's collider assuming that character can be pushed away from obstacle - usable for checking if character is in some tight space
CollisionMoveTest()
proto float CollisionMoveTest (vector dir, vector offset, float xzScale, IEntity ignoreEntity, out IEntity hitEntity, out vector hitPosition, out vector hitNormal)
makes test if character can physically move in given direction - length of dir means distance, returns distance fraction
ContinueCombo() [1/2]
proto native void ContinueCombo ()
marks command to continue to combo
ContinueCombo() [2/2]
proto native void ContinueCombo (bool pHeavyHit, float pComboValue, EntityAI target = null, vector hitPos = vector.Zero)
marks command to continue to combo
DebugDrawClimb()
proto static native bool DebugDrawClimb (Human pHuman, int pLevel) static
debug draws climb heauristics int pLevel = 1 result, 2 - capsules (3 - all)
DebugDrawLadder()
proto static native bool DebugDrawLadder (Building pBuilding, int pLadderIndex) static
debug draws any ladder
DebugGetItemAnimInstance()
proto native owned string DebugGetItemAnimInstance ()
returns current item's animation instance
DebugGetItemClass()
proto native owned string DebugGetItemClass ()
returns current item's class name
DebugGetItemSuperClass()
proto native owned string DebugGetItemSuperClass ()
returns current item's class that is found in config
DebugGetLadderIndex()
proto static native int DebugGetLadderIndex (string pComponentName) static
DebugIsEvent()
proto native int DebugIsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
DebugResetEvents()
proto native void DebugResetEvents ()
DefaultCancelCondition()
proto native bool DefaultCancelCondition ()
system implemented cancel condition (now raise or sprint cancels action)
Referenced by ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), and HumanCommandActionCallback::CancelCondition().
DeleteCommandModifier_Action()
proto native void DeleteCommandModifier_Action (HumanCommandActionCallback pCallback)
force remove - normally if action is ended or interrupted - this is not needed to call
DeleteCommandModifier_Damage()
proto native void DeleteCommandModifier_Damage (HumanCommandDamage pDamage)
DoClimbTest()
proto static native bool DoClimbTest (Human pHuman, SHumanCommandClimbResult pResult, int pDebugDrawLevel) static
debug draws climb heauristics pDebugDrawLevel viz DebugDrawClimb
EnableCancelCondition()
proto native void EnableCancelCondition (bool pEnable)
enables calling cancel condition default is disabled when enabled - there must be a function "bool CancelCondition()" implemented
Referenced by ActionUnfoldMapCB::ActionUnfoldMapCB(), HumanCommandActionCallback::Init(), ActionContinuousBaseCB::InitActionComponent(), and ActionInteractLoopBaseCB::InitActionComponent().
EnableStateChangeCallback()
proto native void EnableStateChangeCallback ()
enables state change callback OnStateChange
Referenced by ActionUnfoldMapCB::ActionUnfoldMapCB(), CreateActionComponent(), ActionReadPaperCB::CreateActionComponent(), and ActionWritePaperCB::CreateActionComponent().
Exit()
proto native void Exit ()
ForceStance()
proto native void ForceStance (int pStanceIdx)
pStanceIds is one of STANCEIDX_ERECT,STANCEIDX_CROUCH,STANCEIDX_PRONE,STANCEIDX_RAISEDERECT,STANCEIDX_RAISEDCROUCH,STANCEIDX_RAISEDPRONE, or -1 when release the stance lock
ForceStanceUp()
proto native void ForceStanceUp (int pStanceIdx)
pStanceIds is one of STANCEIDX_ERECT,STANCEIDX_CROUCH this forces to stand up to required stance
GetAnimInterface()
proto native HumanAnimInterface GetAnimInterface ()
returns animation interface - usable in HumanCommandScript implementations
GetBaseAimingAngleLR()
proto native float GetBaseAimingAngleLR ()
returns base aiming angle LR - without sway/offsets/...
GetBaseAimingAngleUD()
proto native float GetBaseAimingAngleUD ()
returns base aiming angle UD - without sway/offsets/...
GetBoneIndexByName()
proto native int GetBoneIndexByName (string pBoneName)
returns bone index for a name (-1 if pBoneName doesn't exist)
GetClimbOverStandPointWS()
proto native vector GetClimbOverStandPointWS ()
returns world space position of landspot after climbing over
GetComboCount()
proto native int GetComboCount ()
GetCommand_Action()
proto native HumanCommandActionCallback GetCommand_Action ()
is human is in command action - returns its callback, if current command is action
Referenced by ManBase::BrokenLegForceProne().
GetCommand_Climb()
proto native HumanCommandClimb GetCommand_Climb ()
GetCommand_Damage()
proto native HumanCommandFullBodyDamage GetCommand_Damage ()
Referenced by DayZPlayer::IsInFullbodyDamageAnimation().
GetCommand_Death()
proto native HumanCommandDeathCallback GetCommand_Death ()
GetCommand_Fall()
proto native HumanCommandFall GetCommand_Fall ()
Referenced by DayZPlayer::EEHitBy(), DayZPlayer::IsLanded(), and DayZPlayer::OnLand().
GetCommand_Ladder()
proto native HumanCommandLadder GetCommand_Ladder ()
Referenced by ManBase::OnStoreSave(), and DayZPlayer::ProcessSoundEvent().
GetCommand_Melee()
proto native HumanCommandMelee GetCommand_Melee ()
Referenced by ManBase::OnQuickBarContinuousUseStart(), and ManBase::OnQuickBarSingleUse().
GetCommand_Melee2()
proto native HumanCommandMelee2 GetCommand_Melee2 ()
Referenced by DayZPlayer::AimingModel(), DayZPlayer::EEHitBy(), and DayZPlayer::HandleADS().
GetCommand_Move()
proto native HumanCommandMove GetCommand_Move ()
Referenced by ManBase::BrokenLegForceProne(), DayZPlayer::CanJump(), ManBase::CanRoll(), DayZPlayer::CommandHandler(), ManBase::ContaminatedParticleAdjustment(), ManBase::EEItemIntoHands(), DayZInfected::EOnInit(), ForceStandUpForHeavyItems(), DayZInfected::HandleMindStateChange(), DayZPlayer::HeadingModel(), ManBase::IsRolling(), and ManBase::UpdateMovementInertia().
GetCommand_Script()
proto native HumanCommandScript GetCommand_Script ()
is human is in command action - returns its callback, if current command is action
GetCommand_Swim()
proto native HumanCommandSwim GetCommand_Swim ()
GetCommand_Unconscious()
proto native HumanCommandUnconscious GetCommand_Unconscious ()
Referenced by ManBase::CommandHandler(), DayZPlayer::GetTypeOfDeath(), and DayZPlayer::HeadingModel().
GetCommand_Vehicle()
proto native HumanCommandVehicle GetCommand_Vehicle ()
Referenced by DayZPlayer::CameraHandler(), DayZPlayer::CommandHandler(), ManBase::CommandHandler(), DayZPlayer::HandleDamageHit(), DayZPlayer::HandleDeath(), DayZPlayer::HeadingModel(), IsInventoryVisible(), ManBase::OnCommandVehicleStart(), and ManBase::ResetPlayer().
GetCommandModifier_Action()
proto native HumanCommandActionCallback GetCommandModifier_Action ()
returns callback for action if any is active, null if nothing runs
GetCommandModifier_Additives()
proto native HumanCommandAdditives GetCommandModifier_Additives ()
default (always-on modifiers)
returns modifier for additives / small behaviours on human
Referenced by DayZPlayer::CommandHandler(), DayZPlayer::CommandHandlerDebug(), and ManBase::ProcessADDModifier().
GetCommandModifier_Damage()
proto native HumanCommandDamage GetCommandModifier_Damage ()
GetCommandModifier_Weapons()
proto native HumanCommandWeapons GetCommandModifier_Weapons ()
returns interface for handling weapons
Referenced by DayZPlayer::CommandHandler(), DayZPlayer::CommandHandlerDebug(), DayZPlayer::ExitSights(), DayZPlayer::HandleADS(), DayZPlayer::HandleWeapons(), ManBase::ProcessLiftWeapon(), ManBase::SendLiftWeaponSync(), DayZPlayer::SetIronsights(), and DayZPlayer::SetOptics().
GetCommandModifierCount()
proto native int GetCommandModifierCount ()
GetCommandModifierID()
proto native int GetCommandModifierID (int pIndex)
returns COMMANDID_ .. type id of command modifier on index pIndex
GetCurrentCommandID()
proto native int GetCurrentCommandID ()
returns current command ID (see DayZPlayerConstants.COMMANDID_...)
GetCurrentHitType()
proto native int GetCurrentHitType ()
References m_HitType.
GetCurrentInputAngle()
proto bool GetCurrentInputAngle (out float pAngle)
direction held on keyboard/controller -180 -90 0 90 180 angles of input movement (no filtering, no postprocesses) return false in idle states
GetCurrentMovementAngle()
proto native float GetCurrentMovementAngle ()
marks command to continue to combo -180 -90 0 90 180 angles of current movement
GetCurrentMovementSpeed()
proto native float GetCurrentMovementSpeed ()
0,1,2..3 idle, walk, run, sprint
GetGrabPointWS()
proto native vector GetGrabPointWS ()
returns world space position of climbing grab point
GetHuman()
proto native Human GetHuman ()
get the human this cb belongs to
Referenced by GearChangeActionCallback::OnFinish().
GetInputController()
proto native HumanInputController GetInputController ()
returns human input controller
Referenced by DayZCreatureAI::CommandHandler(), DayZInfected::CommandHandler(), DayZPlayer::CommandHandler(), ManBase::CommandHandler(), DayZPlayer::HandleADS(), DayZInfected::HandleMove(), and DayZPlayer::HandleView().
GetItemAccessor()
proto native HumanItemAccessor GetItemAccessor ()
Referenced by DayZPlayer::CanClimb(), DayZPlayer::CanJump(), DayZPlayer::HandleADS(), DayZPlayer::HandleDeath(), DayZPlayer::HeadingModel(), ManBase::HeadingModel(), DayZPlayer::OnItemInHandsChanged(), ManBase::RefreshHandAnimationState(), and ManBase::TryHideItemInHands().
GetLogoutPosition()
proto native vector GetLogoutPosition ()
returns the safe logout position in worldspace the position is closest to the last possible exit point the player passed
GetMovementState()
proto native void GetMovementState (HumanMovementState pState)
returns movement state (current command id,)
Referenced by DayZPlayer::AimingModel(), DayZPlayer::CameraHandler(), DayZPlayer::CommandHandler(), DayZPlayer::EvaluateDamageHitAnimation(), DayZPlayer::HandleADS(), DayZPlayer::HandleWeapons(), DayZPlayer::HeadingModel(), DayZPlayer::IsFireWeaponRaised(), IsPlayerInStance(), and DayZPlayer::OnStepEvent().
GetRunningAction()
proto native int GetRunningAction ()
returns -1 when no action is running or RELOAD,MECHANISM, ....
References ActionData::m_Action, and m_CurrentActionData.
Referenced by ManBase::CanBeRestrained(), ActionManagerClient::FindContextualUserActions(), ManBase::HeadingModel(), and ManBase::OnQuickBarSingleUse().
GetRunningActionType()
proto native int GetRunningActionType ()
returns -1 when no action is running or appropriate action type
GetState()
proto native int GetState ()
returns one of STATE_...
returns the state of climb (enum value of ClimbStates);
References m_State, and Inventory_Base::m_State.
Referenced by ItemBase::CanAttach(), ItemBase::CanBeManipulated(), ItemBase::CanBePacked(), ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), CanDisplayAttachmentSlot(), FireworksLauncher::CanPutInCargo(), FireworksLauncher::CanPutIntoHands(), CanReceiveAttachment(), ItemBase::EEHealthLevelChanged(), GetStateString(), ItemBase::GetViewIndex(), ItemBase::HandleOpeningsPhysics(), FireworksLauncher::IsIgnited(), IsTakeable(), FireworksLauncher::OnPlacementComplete(), RefreshState(), ItemBase::UpdatePhysics(), UpdateProxySelections(), and ItemBase::UpdateVisuals().
GetStateString() [1/2]
string GetStateString ()
returns debug string of current state
References GetState(), and GetStateString().
Referenced by GetStateString(), and HumanCommandActionCallback::OnStateChange().
GetStateString() [2/2]
static string GetStateString (int pState) static
returns debug string of current state
one time state
References STATE_LOOP_ACTION, STATE_LOOP_END, STATE_LOOP_END2, STATE_LOOP_IN, STATE_LOOP_LOOP, STATE_LOOP_LOOP2, STATE_NONE, and STATE_NORMAL.
GetTransformWS()
enum HumanMoveCommandID GetTransformWS (out vector pTm[4])
gets human transform in World Space
Referenced by DayZInfected::AddArrow(), and ManBase::AddArrow().
HumanAnimInterface()
private void HumanAnimInterface ()
HumanCommandActionCallback()
class HumanAnimInterface HumanCommandActionCallback ()
HumanCommandAdditives()
class HumanCommandWeapons HumanCommandAdditives ()
References A.
Referenced by ApplyExhaustion(), DayZPlayer::CommandHandler(), DayZPlayer::CommandHandlerDebug(), WeaponStateBase::OnEntry(), Play(), ManBase::ProcessADDModifier(), Update(), SmptAnimMetaADD::Update(), and PlayerPreview::UpdateInterval().
HumanCommandClimb()
private void HumanCommandClimb ()
HumanCommandDamage()
class HumanCommandUnconscious HumanCommandDamage ()
HumanCommandDeath()
class HumanCommandDeathCallback HumanCommandDeath ()
HumanCommandFall()
class HumanCommandMelee2 HumanCommandFall ()
Referenced by DayZPlayer::CommandHandler(), DayZPlayer::EEHitBy(), DayZPlayer::IsLanded(), ManBase::OnJumpEnd(), DayZPlayer::OnLand(), and SetDirectionSprintFilterModifier().
HumanCommandLadder()
private void HumanCommandLadder ()
HumanCommandMelee()
class HumanCommandMove HumanCommandMelee ()
HumanCommandMelee2()
private void HumanCommandMelee2 ()
HumanCommandMove()
private void HumanCommandMove ()
HumanCommandSwim()
class HumanCommandLadder HumanCommandSwim ()
Referenced by CheckWaterLevel(), EmoteBase::EmoteCondition(), DayZPlayerImplementSwimming::GetCharacterDepth(), DayZPlayerImplementSwimming::GetWaterDepth(), DayZPlayerImplementSwimming::HandleSwimming(), and ActionFillBottleBase::SetupStance().
HumanCommandUnconscious()
private void HumanCommandUnconscious ()
HumanCommandWeapons()
private void HumanCommandWeapons ()
InternalCommand()
proto native void InternalCommand (int pInternalCommandId)
calls internal command pInternalCommandId is one of CMD_ACTIONINT_ ...
Referenced by ActionBaseCB::SetCommand().
IsActionFinished()
proto native bool IsActionFinished ()
IsChangingStance()
proto native bool IsChangingStance ()
returns true if character is changing stance
IsDeathConditionMet()
proto native bool IsDeathConditionMet ()
IsDeathProcessed()
proto native bool IsDeathProcessed ()
IsEvent()
proto native int IsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
IsFinisher()
proto native bool IsFinisher ()
IsGestureCallback()
bool IsGestureCallback ()
IsInComboRange()
proto native bool IsInComboRange ()
returns true if hit is in range, where person can continue to combo
IsInProne()
bool IsInProne ()
IsInRaisedProne()
bool IsInRaisedProne ()
IsInRoll()
proto native bool IsInRoll ()
return true if character barrel rolling
IsInWater()
proto native bool IsInWater ()
Referenced by ManBase::BrokenLegForceProne().
IsInWeaponReloadBulletSwitchState()
proto native bool IsInWeaponReloadBulletSwitchState ()
returns true when clip visual change is needed for reload clip action
IsLanding()
proto native bool IsLanding ()
returns true if fall is in landing state
IsLeaning()
bool IsLeaning ()
IsLeavingUncon()
proto native bool IsLeavingUncon ()
return true if character transitions out of uncon
Referenced by DayZPlayer::HeadingModel().
IsMeleeEvade()
proto native bool IsMeleeEvade ()
this is true when in melee evade
IsModifierActive()
proto native bool IsModifierActive ()
is modifier active
Referenced by ManBase::EEHitBy(), and ManBase::SaveAreaPersistenceFlag().
IsOnBack()
proto native bool IsOnBack ()
return true if prone is on back
is on back in prone stance?
IsOnLand()
proto native bool IsOnLand ()
IsRaised()
bool IsRaised ()
Referenced by ManBase::CanBeRestrained(), DayZPlayer::CanClimb(), DayZPlayer::CanJump(), ManBase::CanSprint(), ManBase::EEItemIntoHands(), DayZPlayer::HandleADS(), DayZPlayer::HandleView(), ManBase::IsMapCallbackCancelInput(), ManBase::OnQuickBarContinuousUseStart(), and ManBase::OnQuickBarSingleUse().
IsRaisedInProne()
bool IsRaisedInProne ()
IsStandingFromBack()
proto native bool IsStandingFromBack ()
return true if prone on back is chaning to crounch/stand
IsSymptomCallback()
bool IsSymptomCallback ()
IsThrowingMode()
proto native bool IsThrowingMode ()
IsUserActionCallback()
bool IsUserActionCallback ()
IsWakingUp()
proto native bool IsWakingUp ()
Land()
proto native void Land (int pLandType)
end fall with land
LiftWeapon()
proto native void LiftWeapon (bool pState)
command for lifting weapon near obstacled (works only when weapon is raised)
LinkToLocalSpaceOf()
proto native void LinkToLocalSpaceOf (notnull IEntity child, vector pLocalSpaceMatrix[4])
OnActivate()
class HumanMovementState OnActivate ()
HumanCommandScript fully scriptable command.
Warning
NON-MANAGED, will be managed by C++ once it is sent to the CommandHandler through Human.StartCommand_Script
Note
So ideally, it is best to set up the HumanCommandScript, not create any instances and start it through Human.StartCommand_ScriptInst In case an instance needs to be created, it needs manual deletion if not sent to the CommandHandler But deleting it while it is in the CommandHandler will cause crashes constructor must have 1st parameter to be Human virtual to be overridden called when command starts
Referenced by Activate(), AntibioticsMdfr::OnReconnect(), CharcoalMdfr::OnReconnect(), FatigueMdfr::OnReconnect(), FeverMdfr::OnReconnect(), HemolyticReactionMdfr::OnReconnect(), PoisoningMdfr::OnReconnect(), WetMdfr::OnReconnect(), DisinfectionMdfr::OnReconnect(), DrowningMdfr::OnReconnect(), EpinephrineMdfr::OnReconnect(), FliesMdfr::OnReconnect(), ImmunityBoost::OnReconnect(), MaskMdfr::OnReconnect(), MorphineMdfr::OnReconnect(), PainKillersMdfr::OnReconnect(), and SalineMdfr::OnReconnect().
OnAnimationEvent()
void OnAnimationEvent (int pEventID)
calls animation event -> must be registered with RegisterAnimationEvent
OnCommandActionAdditiveFinish()
void OnCommandActionAdditiveFinish ()
OnCommandActionAdditiveStart()
void OnCommandActionAdditiveStart ()
OnCommandActionFullbodyFinish()
void OnCommandActionFullbodyFinish ()
OnCommandActionFullbodyStart()
void OnCommandActionFullbodyStart ()
OnCommandClimbFinish()
void OnCommandClimbFinish ()
OnCommandClimbStart()
void OnCommandClimbStart ()
OnCommandDamageAdditiveFinish()
void OnCommandDamageAdditiveFinish ()
OnCommandDamageAdditiveStart()
void OnCommandDamageAdditiveStart ()
OnCommandDamageFullbodyFinish()
void OnCommandDamageFullbodyFinish ()
OnCommandDamageFullbodyStart()
void OnCommandDamageFullbodyStart ()
OnCommandDeathFinish()
void OnCommandDeathFinish ()
OnCommandDeathStart()
void OnCommandDeathStart ()
OnCommandFallFinish()
void OnCommandFallFinish ()
OnCommandFallStart()
void OnCommandFallStart ()
OnCommandLadderFinish()
void OnCommandLadderFinish ()
OnCommandLadderStart()
void OnCommandLadderStart ()
OnCommandMelee2Finish()
void OnCommandMelee2Finish ()
OnCommandMelee2Start()
void OnCommandMelee2Start ()
OnCommandMeleeFinish()
void OnCommandMeleeFinish ()
OnCommandMeleeStart()
void OnCommandMeleeStart ()
OnCommandMoveFinish()
void OnCommandMoveFinish ()
OnCommandMoveStart()
void OnCommandMoveStart ()
OnCommandSwimFinish()
void OnCommandSwimFinish ()
OnCommandSwimStart()
void OnCommandSwimStart ()
OnCommandUnconsciousFinish()
void OnCommandUnconsciousFinish ()
OnCommandUnconsciousStart()
void OnCommandUnconsciousStart ()
OnCommandVehicleFinish()
void OnCommandVehicleFinish ()
OnCommandVehicleStart()
void OnCommandVehicleStart ()
OnDeactivate()
void OnDeactivate ()
called when command ends
Referenced by Deactivate().
OnFinish()
void OnFinish (bool pCanceled)
called ALWAYS! when action is finished (normal finish or cancel -> pCanceled)
OnRollFinish()
void OnRollFinish ()
OnRollStart()
void OnRollStart (bool isToTheRight)
OnSimulationEnd()
void OnSimulationEnd ()
OnStanceChange()
void OnStanceChange (int previousStance, int newStance)
gets called on stance change
OnStateChange()
void OnStateChange (int pOldState, int pCurrentState)
called when enabled by EnableStateChangeCallback and state changes, call GetState() to get actual state
PhysicsEnableGravity()
proto native void PhysicsEnableGravity (bool pEnable)
PhysicsGetVelocity()
proto native void PhysicsGetVelocity (out vector pVelocity)
outs pVelocity - linear velocity of PHYSICS CONTROLLER
Referenced by ManBase::BrokenLegWalkShock().
PhysicsIsFalling()
proto native bool PhysicsIsFalling (bool pValidate)
returns true if physics controller is falling
Referenced by DayZPlayer::CommandHandler(), and ManBase::IsLanded().
PhysicsIsSolid()
proto native bool PhysicsIsSolid ()
PhysicsLanded()
proto native bool PhysicsLanded ()
this is true when fall has physically landed - need to call Land after this is true
PhysicsSetRagdoll()
proto native void PhysicsSetRagdoll (bool pEnable)
Sets and synchronize interaction layers 'RAGDOLL' and 'RAGDOLL_NO_CHARACTER' to prevent body stacking and players going through dead creatures.
Referenced by DayZPlayer::HandleDeath().
PhysicsSetSolid()
proto native void PhysicsSetSolid (bool pSolid)
Referenced by DayZPlayer::HandleDeath().
PostPhys_GetPosition()
proto native void PostPhys_GetPosition (out vector pOutTransl)
script function usable in PostPhysUpdate
PostPhys_GetRotation()
proto native void PostPhys_GetRotation (out float pOutRot[4])
vec3 in world space
PostPhys_LockRotation()
proto native void PostPhys_LockRotation ()
quaternion in world space
PostPhys_SetPosition()
proto native void PostPhys_SetPosition (vector pInTransl)
quaternion in world space
PostPhys_SetRotation()
proto native void PostPhys_SetRotation (float pInRot[4])
vec3 in world space
PostPhysUpdate()
bool PostPhysUpdate (float pDt)
override this ! final adjustment of physics state (after physics was applied) returns true if command continues running / false if command should end (or you can use SetFlagFinished(true))
PreAnim_CallCommand()
proto native void PreAnim_CallCommand (int pCommand, int pParamInt, float pParamFloat)
function usable in PreAnimUpdate or in !!! OnActivate !!!
PreAnim_SetBool()
proto native void PreAnim_SetBool (int pVar, bool pBool)
PreAnim_SetFilteredHeading()
proto native void PreAnim_SetFilteredHeading (float pYawAngle, float pFilterDt, float pMaxYawSpeed)
sets character rotation (heading)
PreAnim_SetFloat()
proto native void PreAnim_SetFloat (int pVar, float pFlt)
PreAnim_SetInt()
proto native void PreAnim_SetInt (int pVar, int pInt)
PreAnimUpdate()
void PreAnimUpdate (float pDt)
override this ! called before any animation is processed here change animation values, add animation commands
PrePhys_GetRotation()
proto native bool PrePhys_GetRotation (out float pOutRot[4])
PrePhys_GetTranslation()
proto native bool PrePhys_GetTranslation (out vector pOutTransl)
PrePhys_IsEvent()
proto native bool PrePhys_IsEvent (int pEvent)
script function usable in PrePhysUpdate
PrePhys_IsTag()
proto native bool PrePhys_IsTag (int pTag)
PrePhys_SetRotation()
proto native void PrePhys_SetRotation (float pInRot[4])
PrePhys_SetTranslation()
proto native void PrePhys_SetTranslation (vector pInTransl)
PrePhysUpdate()
void PrePhysUpdate (float pDt)
override this ! after animation is processed, before physics is processed
RegisterAnimationEvent()
proto native void RegisterAnimationEvent (string pAnimationEventStr, int pId)
registers animation event, when event registered and received - it sends OnAnimationEvent with registered id
RegisterDefaultEvents()
void RegisterDefaultEvents ()
RegisterEvent()
proto native void RegisterEvent (string pName, int pId)
register events
ResetAligning()
proto native void ResetAligning ()
disables character aligning
ResetDeath()
proto native void ResetDeath ()
ResetDeathCooldown()
proto native void ResetDeathCooldown ()
SetActionProgressParams()
proto native void SetActionProgressParams (float pStart, float pEnd)
sets start and end animation position - f.e. for reload clip action
SetADS()
proto native void SetADS (bool pState)
sets head tilt to optics
SetAligning()
proto native void SetAligning (vector pPositionWS, vector pDirectionWS)
enables character aligning to desired position and direction in world space
SetCurrentWaterLevel()
proto native void SetCurrentWaterLevel (float value)
sets water level (depth)
SetDirectionFilterModifier()
proto native void SetDirectionFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterTimeout
SetDirectionSprintFilterModifier()
proto native void SetDirectionSprintFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterSprintTimeout
References HumanCommandFall().
SetExhaustion()
proto native void SetExhaustion (float pValue, bool pInterpolate)
sets exhaustion level 0..1, interpolate == false -> resets the value, otherwise it's interpolating towards the new value
SetFlagFinished()
proto native void SetFlagFinished (bool pFinished)
this terminates human command script and shows CommandHandler(... pCurrentCommandFinished == true);
SetInitState()
proto native void SetInitState (int pFrameIndex)
this sets to a weapon init state each weapon has a different weapon state those states are defined by animation set by AddItemInHandsProfileIK - in DayZPlayerCfgBase.c each frame of animation is one init state
SetInjured()
proto native void SetInjured (float pValue, bool pInterpolate)
sets injury level 0..1, interpolate == false -> resets the value, otherwise it's interpolating towards the new value
SetMeleeBlock()
proto native void SetMeleeBlock (bool pBlock)
this enables/disables block
SetRunSprintFilterModifier()
proto native void SetRunSprintFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fRunSpringTimeout
SetTalking()
proto native void SetTalking (bool pValue)
sets talking
SetThrowingMode()
proto native void SetThrowingMode (bool pState)
SetTurnSpanModifier()
proto native void SetTurnSpanModifier (float value)
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingFilterSpan
SetTurnSpanSprintModifier()
proto native void SetTurnSpanSprintModifier (float value)
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingSprintFilterSpan
ShouldSimulationBeDisabled()
bool ShouldSimulationBeDisabled ()
'OnSimulationEnd' is called before this
StartAction()
proto native bool StartAction (WeaponActions pAction, int pActionType)
start reload,mechanism,chambering,unjam ...
StartCommand_Action()
proto native HumanCommandActionCallback StartCommand_Action (int pActionID, typename pCallbackClass , int pStanceMask)
--— ACTIONS --—
starts command - Action pStanceMask is mix of flags STANCEMASK_ERECT, ...
StartCommand_Climb()
proto native HumanCommandClimb StartCommand_Climb (SHumanCommandClimbResult pClimbResult, int pType)
--— CLIMB --—
starts command - climb
StartCommand_Damage()
proto native HumanCommandFullBodyDamage StartCommand_Damage (int pType, float pDirection)
--— FullBody Damages --—
starts fullbody damage
Referenced by DayZPlayer::CommandHandlerDebug(), and DayZPlayer::HandleDamageHit().
StartCommand_Death()
proto native HumanCommandDeathCallback StartCommand_Death (int pType, float pDirection, typename pCallbackClass)
--— Death --—
starts command - death
Referenced by DayZCreatureAI::HandleDeath(), DayZInfected::HandleDeath(), and DayZPlayer::HandleDeath().
StartCommand_Fall()
proto native HumanCommandFall StartCommand_Fall (float pYVelocity)
--— FALL --—
starts command - fall pYVelocity <= 0 -> fall pYVelocity > 0 -> jump
Referenced by DayZPlayer::CommandHandler().
StartCommand_Ladder()
proto native HumanCommandLadder StartCommand_Ladder (Building pBuilding, int pLadderIndex)
--— LADDER --—
starts command - fall
StartCommand_Melee()
proto native HumanCommandMelee StartCommand_Melee (EntityAI pTarget)
--— MELEE --—
starts command - melee
StartCommand_Melee2()
proto native HumanCommandMelee2 StartCommand_Melee2 (EntityAI pTarget, int pHitType, float pComboValue, vector hitPos = vector.Zero)
starts command - melee2
StartCommand_Move()
proto native HumanCommandMove StartCommand_Move ()
--— MOVE --—
starts command - Move
Referenced by ManBase::BrokenLegForceProne(), DayZCreatureAI::CommandHandler(), DayZInfected::CommandHandler(), DayZPlayer::CommandHandler(), and DayZPlayer::OverrideSlidePoseAngle().
StartCommand_Script()
proto native HumanCommandScript StartCommand_Script (HumanCommandScript pHumanCommand)
— SCRIPTED COMMANDS
starts command - Action pStanceMask is mix of flags STANCEMASK_ERECT, ...
StartCommand_ScriptInst()
proto native HumanCommandScript StartCommand_ScriptInst (typename pCallbackClass)
StartCommand_Swim()
proto native HumanCommandSwim StartCommand_Swim ()
--— LADDER --—
starts command - Swim
Referenced by DayZPlayer::CommandHandler().
StartCommand_Unconscious()
proto native HumanCommandUnconscious StartCommand_Unconscious (float pType)
starts command - unconscious
Referenced by ManBase::CommandHandler().
StartCommand_Vehicle()
proto native HumanCommandVehicle StartCommand_Vehicle (Transport pTransport, int pTransportPositionIndex, int pVehicleSeat, bool fromUnconscious = false)
--— VEHICLE --—
starts command - vehicle
Referenced by DayZPlayer::CommandHandler().
StartDeath()
proto native void StartDeath ()
StartMeleeEvade()
proto native void StartMeleeEvade ()
marks command to continue to combo
StartMeleeEvadeA()
proto native void StartMeleeEvadeA (float pDirAngle)
marks command to continue to combo, pDirAngle specifies angle
StartModifier()
proto native void StartModifier (int pType)
starts modifier
StaticSetInitState()
proto static native void StaticSetInitState (Human pHuman, int pFrameIdx) static
just static version of SetInitState
StopSwimming()
proto native void StopSwimming ()
ThrowItem()
proto native void ThrowItem (int throwType)
UnlinkFromLocalSpace()
proto native void UnlinkFromLocalSpace ()
Referenced by DayZPlayer::HandleDeath().
WakeUp()
proto native void WakeUp (int targetStance = -1)
WasHit()
proto native bool WasHit ()
is true only once after hit event
WasItemLeaveHandsEvent()
proto native bool WasItemLeaveHandsEvent ()
WaterLevelCheck()
proto static native vector WaterLevelCheck (Human pHuman, vector pPosition) static
returns water level from entity position returns in format (totalWaterDepth, characterDepht, 0)
WeaponActionTypeToString()
string WeaponActionTypeToString (int A, int AT)
Referenced by HandleInventory(), HandleWeaponEvents(), HandStateBase::OnEntry(), and WeaponStateBase::OnEntry().
~HumanAnimInterface()
private void ~HumanAnimInterface ()
~HumanCommandActionCallback()
private void ~HumanCommandActionCallback ()
~HumanCommandAdditives()
private void ~HumanCommandAdditives ()
~HumanCommandClimb()
private void ~HumanCommandClimb ()
~HumanCommandDamage()
private void ~HumanCommandDamage ()
~HumanCommandDeath()
private void ~HumanCommandDeath ()
~HumanCommandFall()
private void ~HumanCommandFall ()
~HumanCommandFullBodyDamage()
private void ~HumanCommandFullBodyDamage ()
~HumanCommandLadder()
private void ~HumanCommandLadder ()
~HumanCommandMelee()
private void ~HumanCommandMelee ()
~HumanCommandMelee2()
private void ~HumanCommandMelee2 ()
~HumanCommandMove()
private void ~HumanCommandMove ()
~HumanCommandSwim()
private void ~HumanCommandSwim ()
~HumanCommandUnconscious()
private void ~HumanCommandUnconscious ()
~HumanCommandWeapons()
private void ~HumanCommandWeapons ()
Variable Documentation
CommandActionAdditive
CommandActionAdditive = 8192
CommandActionFullbody
CommandActionFullbody = 4096
CommandClimb
CommandClimb = 16
CommandDamageAdditive
CommandDamageAdditive = 256
CommandDamageFullbody
CommandDamageFullbody = 128
CommandDeath
CommandDeath = 32
CommandFall
CommandFall = 8
CommandLadder
CommandLadder = 512
CommandMelee
CommandMelee = 2
CommandMelee2
CommandMelee2 = 4
CommandMove
CommandMove = 1
CommandSwim
CommandSwim = 1024
CommandUnconscious
CommandUnconscious = 64
CommandVehicle
CommandVehicle = 2048
HIT_TYPE_FINISHER
const int HIT_TYPE_FINISHER = 2 static
HIT_TYPE_FINISHER_NECK
const int HIT_TYPE_FINISHER_NECK = 3 static
HIT_TYPE_HEAVY
const int HIT_TYPE_HEAVY = 1 static
HIT_TYPE_LIGHT
const int HIT_TYPE_LIGHT = 0 static
HumanCommandFullBodyDamage
class HumanCommandClimb HumanCommandFullBodyDamage
LANDTYPE_HEAVY
const int LANDTYPE_HEAVY = 3 static
LANDTYPE_LIGHT
const int LANDTYPE_LIGHT = 1 static
LANDTYPE_MEDIUM
const int LANDTYPE_MEDIUM = 2 static
LANDTYPE_NONE
const int LANDTYPE_NONE = 0 static
m_bFinishWithFall
bool m_bFinishWithFall
m_bHasParent
bool m_bHasParent
m_bIsClimb
class HumanCommandVehicle m_bIsClimb
result from static test
m_bIsClimbOver
bool m_bIsClimbOver
m_ClimbGrabPoint
vector m_ClimbGrabPoint
m_ClimbGrabPointNormal
vector m_ClimbGrabPointNormal
grab point for climb && climb over (in local space of it's parent)
m_ClimbOverStandPoint
vector m_ClimbOverStandPoint
where climb ends (in local space of it's parent)
m_ClimbOverStandPointParent
IEntity m_ClimbOverStandPointParent
m_ClimbStandPoint
vector m_ClimbStandPoint
normal to grabpoint position (used for character orientation)
m_ClimbStandPointParent
IEntity m_ClimbStandPointParent
parent of grabpoint
m_CommandTypeId
int m_CommandTypeId
m_fClimbHeight
float m_fClimbHeight
m_fLeaning
float m_fLeaning
current movement (0 idle, 1 walk, 2-run, 3-sprint), only if the command has a movement
m_GrabPointParent
IEntity m_GrabPointParent
where climb over ends (in local space of it's parent)
m_iMovement
int m_iMovement
current stance (DayZPlayerConstants.STANCEIDX_ERECT, ...), only if the command has a stance
m_iStanceIdx
int m_iStanceIdx
current command's id
m_LocalMovement
int m_LocalMovement = -1
leaning state (not all commands need to have all movements)
MECHANISM_CLOSED
enum WeaponActionReloadClipTypes MECHANISM_CLOSED = 1
MECHANISM_CLOSED_UNCOCKED
enum WeaponActionReloadClipTypes MECHANISM_CLOSED_UNCOCKED = 3
MECHANISM_OPENED
enum WeaponActionReloadClipTypes MECHANISM_OPENED = 0
mechanism action types
MECHANISM_SPECIAL
enum WeaponActionReloadClipTypes MECHANISM_SPECIAL = 2
None
@ None = 0
STATE_LOOP_ACTION
const int STATE_LOOP_ACTION = 6 static
Referenced by GetStateString().
STATE_LOOP_END
const int STATE_LOOP_END = 3 static
Referenced by GetStateString(), and OnStateChange().
STATE_LOOP_END2
const int STATE_LOOP_END2 = 4 static
Referenced by GetStateString(), and OnStateChange().
STATE_LOOP_IN
const int STATE_LOOP_IN = 1 static
looped state
Referenced by GetStateString(), and ActionUnfoldMapCB::OnStateChange().
STATE_LOOP_LOOP
const int STATE_LOOP_LOOP = 2 static
Referenced by ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), GetStateString(), ActionRaiseAndViewCB::OnStateChange(), ActionReadPaperCB::OnStateChange(), ActionUnfoldMapCB::OnStateChange(), and ActionWritePaperCB::OnStateChange().
STATE_LOOP_LOOP2
const int STATE_LOOP_LOOP2 = 5 static
Referenced by ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), and GetStateString().
STATE_NONE
const int STATE_NONE = 0 static
undef state - not running anymore
example of implement of CancelCondition returns true it it should CANCEL the action
Referenced by GetStateString(), OnStateChange(), ActionReadPaperCB::OnStateChange(), and ActionWritePaperCB::OnStateChange().
STATE_NORMAL
const int STATE_NORMAL = 7 static
one time state
Referenced by GetStateString().
TAnimGraphCommand
class HumanInputController TAnimGraphCommand