DayZ Scripts: RecipeBase Class Reference
RecipeBase Class Reference
Private Member Functions
void RecipeBase ()
void Init ()
float GetLengthInSecs ()
float GetSpecialty ()
bool IsRecipeAnywhere ()
bool CheckIngredientMatch (ItemBase item1, ItemBase item2)
void InsertIngredient (int index, string ingredient)
void RemoveIngredient (int index, string ingredient)
void AddResult (string item)
string GetName ()
bool IsInstaRecipe ()
void SpawnItems (ItemBase ingredients[], PlayerBase player, array< ItemBase > spawned_objects)
void ApplyModificationsResults (ItemBase sorted[], array< ItemBase > results, ItemBase result, PlayerBase player)
void DeleleIngredientsPass ()
void ApplyModificationsIngredients (ItemBase sorted[], PlayerBase player)
bool CheckConditions (ItemBase sorted[])
bool CheckRecipe (ItemBase item1, ItemBase item2, PlayerBase player)
void OnSelectedRecipe (ItemBase item1, ItemBase item2, PlayerBase player)
void OnSelected (ItemBase item1, ItemBase item2, PlayerBase player)
void PerformRecipe (ItemBase item1, ItemBase item2, PlayerBase player)
void ApplySoftSkillsSpecialty (PlayerBase player)
bool CanDo (ItemBase ingredients[], PlayerBase player)
void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
int GetID ()
void SetID (int id)
void GetAllItems (array< string > items)
bool IsItemInRecipe (string item)
int GetIngredientMaskForItem (string item)
returns a mask which marks ingredient positions for a given item in this recipe(for example mask of value 3 [....000011] means this item is both ingredient 1 and 2 in this recipe[from right to left])
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override void OnSelected (ItemBase item1, ItemBase item2, PlayerBase player)
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
void TransferItemsToNew (PlayerBase player, ItemBase barrel_old, ItemBase barrel_new)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
override void Init ()
override bool CanDo (ItemBase ingredients[], PlayerBase player)
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight)
Private Attributes
string m_ItemsToCreate [MAXIMUM_RESULTS]
ref array< string > m_Ingredients [MAX_NUMBER_OF_INGREDIENTS]
ItemBase m_Items [MAX_NUMBER_OF_INGREDIENTS]
ItemBase m_IngredientsSorted [MAX_NUMBER_OF_INGREDIENTS]
ref array< ItemBase > m_IngredientsToBeDeleted = new array<ItemBase>
string m_Name
int m_ID
int m_NumberOfResults
float m_AnimationLength = 1
float m_Specialty = 0
bool m_IsInstaRecipe
bool m_AnywhereInInventory
float m_MinQuantityIngredient [MAX_NUMBER_OF_INGREDIENTS]
float m_MaxQuantityIngredient [MAX_NUMBER_OF_INGREDIENTS]
float m_MinDamageIngredient [MAX_NUMBER_OF_INGREDIENTS]
float m_MaxDamageIngredient [MAX_NUMBER_OF_INGREDIENTS]
bool m_IngredientUseSoftSkills [MAX_NUMBER_OF_INGREDIENTS]
float m_IngredientAddHealth [MAX_NUMBER_OF_INGREDIENTS]
float m_IngredientAddQuantity [MAX_NUMBER_OF_INGREDIENTS]
float m_IngredientSetHealth [MAX_NUMBER_OF_INGREDIENTS]
bool m_IngredientDestroy [MAX_NUMBER_OF_INGREDIENTS]
bool m_ResultSetFullQuantity [MAXIMUM_RESULTS]
float m_ResultSetQuantity [MAXIMUM_RESULTS]
float m_ResultSetHealth [MAXIMUM_RESULTS]
float m_ResultSpawnDistance [MAXIMUM_RESULTS]
int m_ResultToInventory [MAXIMUM_RESULTS]
int m_ResultInheritsHealth [MAXIMUM_RESULTS]
int m_ResultInheritsColor [MAXIMUM_RESULTS]
int m_ResultReplacesIngredient [MAXIMUM_RESULTS]
bool m_ResultUseSoftSkills [MAXIMUM_RESULTS]
float m_PercentageUsed = 0.05
Detailed Description
Definition at line 4 of file RecipeBase.c.
Constructor & Destructor Documentation
RecipeBase()
void RecipeBase () inline private
Definition at line 52 of file RecipeBase.c.
References DEFAULT_SPAWN_DISTANCE, Init(), m_Ingredients, m_IngredientsSorted, m_Name, m_NumberOfResults, m_ResultSpawnDistance, MAX_NUMBER_OF_INGREDIENTS, and MAXIMUM_RESULTS.
Member Function Documentation
AddResult()
void AddResult (string item) inline private
Definition at line 153 of file RecipeBase.c.
References m_ItemsToCreate, and m_NumberOfResults.
Referenced by Init().
ApplyModificationsIngredients()
void ApplyModificationsIngredients (ItemBase sorted[], PlayerBase player) inline private
Definition at line 352 of file RecipeBase.c.
References m_IngredientAddHealth, m_IngredientAddQuantity, m_IngredientDestroy, m_IngredientSetHealth, m_IngredientsToBeDeleted, m_IngredientUseSoftSkills, m_Specialty, and MAX_NUMBER_OF_INGREDIENTS.
Referenced by PerformRecipe().
ApplyModificationsResults()
void ApplyModificationsResults (ItemBase sorted[], array< ItemBase > results, ItemBase result, PlayerBase player) inline private
Definition at line 234 of file RecipeBase.c.
References Debug::Log(), m_NumberOfResults, m_ResultInheritsHealth, m_ResultReplacesIngredient, m_ResultSetFullQuantity, m_ResultSetHealth, m_ResultSetQuantity, m_ResultUseSoftSkills, m_Specialty, MAX_NUMBER_OF_INGREDIENTS, and ToString().
Referenced by PerformRecipe().
ApplySoftSkillsSpecialty()
void ApplySoftSkillsSpecialty (PlayerBase player) inline private
Definition at line 553 of file RecipeBase.c.
References m_Specialty.
Referenced by PerformRecipe().
CanDo() [1/196]
bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 558 of file RecipeBase.c.
References MAX_NUMBER_OF_INGREDIENTS.
Referenced by CheckRecipe().
CanDo() [2/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file AttachHolster.c.
CanDo() [3/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file AttachHolsterPouch.c.
CanDo() [4/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file AttachPouch.c.
CanDo() [5/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file AttachPouchesHolster.c.
CanDo() [6/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file BloodTest.c.
CanDo() [7/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 64 of file CleanRags.c.
References Class::CastTo(), and LIQUID_WATER.
CanDo() [8/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 63 of file CleanWeapon.c.
References Class::CastTo(), and GetPlugin().
CanDo() [9/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 102 of file CraftArmbandFlag.c.
CanDo() [10/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 56 of file CraftArmbandRag.c.
CanDo() [11/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 123 of file CraftArmbandRaincoat.c.
CanDo() [12/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 57 of file CraftArrow.c.
CanDo() [13/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftArrowBone.c.
CanDo() [14/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftBait.c.
CanDo() [15/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 55 of file CraftBaseBallBatNailed.c.
CanDo() [16/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftBloodBagIV.c.
CanDo() [17/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftBoneBait.c.
CanDo() [18/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 84 of file CraftBoneHook.c.
CanDo() [19/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftBoneKnife.c.
CanDo() [20/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftBow.c.
CanDo() [21/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 84 of file CraftBurlapStrips.c.
CanDo() [22/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftCamoNetShelter.c.
CanDo() [23/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file CraftCookingStand.c.
References IsEmpty().
CanDo() [24/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftCourierBag.c.
CanDo() [25/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file CraftFenceKit.c.
CanDo() [26/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 74 of file CraftFireplace.c.
CanDo() [27/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file CraftFishingRod.c.
CanDo() [28/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftFishNetTrap.c.
CanDo() [29/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftGasMask_Filter_Improvised.c.
CanDo() [30/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftGhillieAttachment.c.
CanDo() [31/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftGhillieBushrag.c.
CanDo() [32/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftGhillieHood.c.
CanDo() [33/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftGhillieSuit.c.
CanDo() [34/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftGhillieTop.c.
CanDo() [35/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftGorkaHelmetComplete.c.
CanDo() [36/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 80 of file CraftGutsRope.c.
CanDo() [37/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file CraftHandDrillKit.c.
CanDo() [38/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftImprovisedBag.c.
References IsEmpty().
CanDo() [39/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftImprovisedExplosive.c.
CanDo() [40/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftImprovisedLeatherBag.c.
References IsEmpty().
CanDo() [41/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftLeatherCourierBag.c.
CanDo() [42/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 56 of file CraftLeatherSack.c.
CanDo() [43/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftLongTorch.c.
CanDo() [44/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftRabbitSnare.c.
CanDo() [45/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 88 of file CraftRag.c.
CanDo() [46/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftRagRope.c.
CanDo() [47/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftSalineBagIV.c.
CanDo() [48/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftShelterKit.c.
CanDo() [49/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 84 of file CraftSmallFishTrap.c.
CanDo() [50/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftSpearBone.c.
CanDo() [51/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftSpearStone.c.
CanDo() [52/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 61 of file CraftSplint.c.
CanDo() [53/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 61 of file CraftStoneKnife.c.
CanDo() [54/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftSuppressor.c.
CanDo() [55/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 61 of file CraftTannedLeather.c.
References m_PercentageUsed, and Pelt_Base.
CanDo() [56/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftTerritoryFlagKit.c.
CanDo() [57/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftTorch.c.
CanDo() [58/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftTripWire.c.
CanDo() [59/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftTruck01DoubleWheel.c.
CanDo() [60/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file CraftWatchtowerKit.c.
CanDo() [61/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftWoodenCrate.c.
CanDo() [62/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file CraftWoodenPlank.c.
CanDo() [63/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 8 of file CutOutSeeds.c.
CanDo() [64/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 83 of file DeCraftArmband.c.
CanDo() [65/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 87 of file DeCraftBow.c.
CanDo() [66/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 99 of file DeCraftCamoNetShelter.c.
CanDo() [67/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 107 of file DeCraftCarrierComplete.c.
CanDo() [68/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 95 of file DeCraftCarrierHolster.c.
CanDo() [69/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 95 of file DeCraftCarrierPouches.c.
CanDo() [70/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 87 of file DeCraftCookingStand.c.
CanDo() [71/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 98 of file DeCraftCourierBag.c.
CanDo() [72/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file DeCraftDetonator.c.
CanDo() [73/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 97 of file DeCraftFishingRod.c.
CanDo() [74/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 96 of file DeCraftFishNetTrap.c.
CanDo() [75/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 100 of file DeCraftGhillieAttachment.c.
CanDo() [76/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 101 of file DeCraftGhillieBushrag.c.
CanDo() [77/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 101 of file DeCraftGhillieHood.c.
CanDo() [78/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 100 of file DeCraftGhillieSuit.c.
CanDo() [79/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 101 of file DeCraftGhillieTop.c.
CanDo() [80/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 87 of file DeCraftHandDrillKit.c.
CanDo() [81/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 98 of file DeCraftImprovisedBag.c.
CanDo() [82/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 98 of file DeCraftImprovisedLeatherBag.c.
CanDo() [83/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 98 of file DeCraftLeatherCourierBag.c.
CanDo() [84/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 83 of file DeCraftLeatherSack.c.
CanDo() [85/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 87 of file DeCraftSnareTrap.c.
CanDo() [86/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 87 of file DeCraftSpear.c.
CanDo() [87/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 87 of file DeCraftSplint.c.
CanDo() [88/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 87 of file DeCraftTripWire.c.
CanDo() [89/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 74 of file DeCraftTruck01DoubleWheel.c.
CanDo() [90/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 74 of file DeCraftWoodenCrate.c.
References Class::CastTo().
CanDo() [91/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file DisinfectItem.c.
References ItemBase::CanBeDisinfected(), and LIQUID_DISINFECTANT.
CanDo() [92/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 70 of file DrainLiquid.c.
References Liquid::CanTransfer(), and Class::CastTo().
CanDo() [93/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 66 of file ExtinguishTorch.c.
References Class::CastTo(), GROUP_LIQUID_BLOOD, FlammableBase::IsIgnited(), LIQUID_BEER, LIQUID_RIVERWATER, and LIQUID_WATER.
CanDo() [94/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file FillGasMask_Filter.c.
References InventoryLocation::GetParent().
CanDo() [95/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file FillSyringe.c.
CanDo() [96/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 65 of file FuelChainsaw.c.
References Class::CastTo(), and LIQUID_GASOLINE.
CanDo() [97/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 81 of file LoadMagazine.c.
References IsKindOf().
CanDo() [98/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 105 of file OpenCan.c.
CanDo() [99/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file PaintAK101.c.
References PaintItem::CanPaintItem().
CanDo() [100/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAK10130Mag.c.
References PaintItem::CanPaintItem().
CanDo() [101/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file PaintAK74.c.
References PaintItem::CanPaintItem().
CanDo() [102/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAK7430Mag.c.
References PaintItem::CanPaintItem().
CanDo() [103/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAK74HndgrdBlack.c.
CanDo() [104/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAK74HndgrdCamo.c.
CanDo() [105/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAK74WoodBttstckBlack.c.
CanDo() [106/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAK74WoodBttstckCamo.c.
CanDo() [107/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAKFoldingBttstck.c.
References PaintItem::CanPaintItem().
CanDo() [108/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAKMDrumMag.c.
References PaintItem::CanPaintItem().
CanDo() [109/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAKMPalm30Mag.c.
References PaintItem::CanPaintItem().
CanDo() [110/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAKPlasticBttstck.c.
References PaintItem::CanPaintItem().
CanDo() [111/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAKRailHndgrd.c.
References PaintItem::CanPaintItem().
CanDo() [112/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAKS74U.c.
References PaintItem::CanPaintItem().
CanDo() [113/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAKS74UBttstck.c.
References PaintItem::CanPaintItem().
CanDo() [114/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAKWoodBttstckBlack.c.
CanDo() [115/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintAKWoodBttstckCamo.c.
CanDo() [116/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintB95.c.
References PaintItem::CanPaintItem().
CanDo() [117/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintBallisticHelmet.c.
References PaintItem::CanPaintItem().
CanDo() [118/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintCMAG10.c.
References PaintItem::CanPaintItem().
CanDo() [119/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintCMAG20.c.
References PaintItem::CanPaintItem().
CanDo() [120/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintCMAG30.c.
References PaintItem::CanPaintItem().
CanDo() [121/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintCMAG40.c.
References PaintItem::CanPaintItem().
CanDo() [122/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintCz527.c.
References PaintItem::CanPaintItem().
CanDo() [123/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintCz527CamoBlack.c.
CanDo() [124/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintCz527CamoGreen.c.
CanDo() [125/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintDarkMotohelmet.c.
References PaintItem::CanPaintItem().
CanDo() [126/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintFirefighterAxe.c.
References PaintItem::CanPaintItem().
CanDo() [127/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieAttBlack.c.
CanDo() [128/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file PaintGhillieAttGreen.c.
CanDo() [129/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieAttGreenMossy.c.
CanDo() [130/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieBushragBlack.c.
CanDo() [131/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file PaintGhillieBushragGreen.c.
CanDo() [132/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieBushragGreenMossy.c.
CanDo() [133/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file PaintGhillieHoodBlack.c.
CanDo() [134/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieHoodGreen.c.
CanDo() [135/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieHoodGreenMossy.c.
CanDo() [136/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file PaintGhillieSuitBlack.c.
CanDo() [137/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieSuitGreen.c.
CanDo() [138/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieSuitGreenMossy.c.
CanDo() [139/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieTopBlack.c.
CanDo() [140/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieTopGreen.c.
CanDo() [141/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGhillieTopGreenMossy.c.
CanDo() [142/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGorkaHelmet.c.
References PaintItem::CanPaintItem().
CanDo() [143/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintGorkaHelmetComplete.c.
References PaintItem::CanPaintItem().
CanDo() [144/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintM4A1.c.
References PaintItem::CanPaintItem().
CanDo() [145/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintM4CQBBttstck.c.
References PaintItem::CanPaintItem().
CanDo() [146/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintM4MPBttstck.c.
References PaintItem::CanPaintItem().
CanDo() [147/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintM4MPHndgrd.c.
References PaintItem::CanPaintItem().
CanDo() [148/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintM4OEBttstck.c.
References PaintItem::CanPaintItem().
CanDo() [149/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintM4PlasticHndgrd.c.
References PaintItem::CanPaintItem().
CanDo() [150/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintM4RISHndgrd.c.
References PaintItem::CanPaintItem().
CanDo() [151/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 63 of file PaintMosin.c.
References PaintItem::CanPaintItem().
CanDo() [152/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintMosinCamoBlack.c.
CanDo() [153/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintMosinCamoGreen.c.
CanDo() [154/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintMotohelmet.c.
References PaintItem::CanPaintItem().
CanDo() [155/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintRuger1022.c.
References PaintItem::CanPaintItem().
CanDo() [156/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintSawedoffMosin.c.
References PaintItem::CanPaintItem().
CanDo() [157/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintSawedoffMosinCamoBlack.c.
CanDo() [158/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintSawedoffMosinCamoGreen.c.
CanDo() [159/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintSKS.c.
References PaintItem::CanPaintItem().
CanDo() [160/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file PaintZSh3PilotHelmet.c.
References PaintItem::CanPaintItem().
CanDo() [161/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 63 of file PatchItem.c.
References ItemBase::CanBeRepairedByCrafting(), Class::CastTo(), and GetPlugin().
CanDo() [162/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 81 of file PeelPotato.c.
CanDo() [163/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 77 of file PokeHolesBarrel.c.
CanDo() [164/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 70 of file PourLiquid.c.
References Liquid::CanTransfer(), and Class::CastTo().
CanDo() [165/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 81 of file PrepareChicken.c.
CanDo() [166/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 8 of file PrepareFish.c.
CanDo() [167/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 94 of file PrepareRabbit.c.
CanDo() [168/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 65 of file PurifyWater.c.
CanDo() [169/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 60 of file RefuelTorch.c.
CanDo() [170/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 61 of file RepairElectric.c.
References Class::CastTo(), and GetPlugin().
CanDo() [171/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 61 of file RepairEpoxy.c.
References Class::CastTo(), and GetPlugin().
CanDo() [172/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 61 of file RepairEyePatch.c.
CanDo() [173/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 62 of file RepairPlanks.c.
CanDo() [174/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 66 of file RepairWithRags.c.
CanDo() [175/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 63 of file RepairWithTape.c.
References ItemBase::CanBeRepairedByCrafting(), Class::CastTo(), and GetPlugin().
CanDo() [176/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 63 of file SawoffB95.c.
CanDo() [177/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 63 of file SawoffFAMAS.c.
CanDo() [178/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 63 of file SawOffIzh18.c.
References Class::CastTo().
CanDo() [179/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 63 of file SawOffIzh18Shotgun.c.
References Class::CastTo().
CanDo() [180/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 65 of file SawoffMagnum.c.
CanDo() [181/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 63 of file SawoffMosin.c.
CanDo() [182/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 65 of file SawoffMosinPainted.c.
CanDo() [183/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 63 of file SawoffShotgunIzh43.c.
CanDo() [184/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 87 of file SawWoodenLog.c.
CanDo() [185/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 93 of file SharpenBroom.c.
CanDo() [186/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 81 of file SharpenLongStick.c.
CanDo() [187/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 61 of file SharpenMelee.c.
References Class::CastTo(), and GetPlugin().
CanDo() [188/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 81 of file SharpenStick.c.
CanDo() [189/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 99 of file SplitBroom.c.
CanDo() [190/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 67 of file SplitFirewood.c.
CanDo() [191/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 87 of file SplitLongWoodenStick.c.
CanDo() [192/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 84 of file SplitStones.c.
CanDo() [193/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 75 of file Test.c.
CanDo() [194/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 58 of file UpgradeTorchWithLard.c.
References FlammableBase::CanReceiveUpgrade().
CanDo() [195/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 59 of file UpgradeTorchWithLiquidFuel.c.
References FlammableBase::CanReceiveUpgrade(), LIQUID_DIESEL, and LIQUID_GASOLINE.
CanDo() [196/196]
override bool CanDo (ItemBase ingredients[], PlayerBase player) inline private
Definition at line 61 of file WriteLetter.c.
CheckConditions()
bool CheckConditions (ItemBase sorted[]) inline private
Definition at line 424 of file RecipeBase.c.
References m_MaxDamageIngredient, m_MaxQuantityIngredient, m_MinDamageIngredient, m_MinQuantityIngredient, and MAX_NUMBER_OF_INGREDIENTS.
Referenced by CheckRecipe().
CheckIngredientMatch()
bool CheckIngredientMatch (ItemBase item1, ItemBase item2) inline private
Definition at line 90 of file RecipeBase.c.
References GetGame(), IsKindOf(), m_Ingredients, m_IngredientsSorted, m_Items, MAX_NUMBER_OF_INGREDIENTS, and x.
CheckRecipe()
bool CheckRecipe (ItemBase item1, ItemBase item2, PlayerBase player) inline private
Definition at line 474 of file RecipeBase.c.
References CanDo(), CheckConditions(), Error(), IsRecipeAnywhere(), and m_IngredientsSorted.
Referenced by PluginRecipesManagerBase::CheckRecipe(), PluginRecipesManagerBase::GetValidRecipesProper(), and PerformRecipe().
DeleleIngredientsPass()
void DeleleIngredientsPass () inline private
Definition at line 341 of file RecipeBase.c.
References m_IngredientsToBeDeleted.
Referenced by PerformRecipe().
Do() [1/197]
void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 570 of file RecipeBase.c.
Referenced by PerformRecipe().
Do() [2/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 73 of file AttachHolster.c.
References Debug::Log().
Do() [3/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 73 of file AttachHolsterPouch.c.
References Debug::Log().
Do() [4/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 73 of file AttachPouch.c.
References Debug::Log().
Do() [5/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 73 of file AttachPouchesHolster.c.
References Debug::Log().
Do() [6/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file BloodTest.c.
References Class::CastTo(), and BloodTypes::GetBloodTypeName().
Do() [7/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 81 of file CleanRags.c.
References Class::CastTo(), and Math::Clamp().
Do() [8/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 74 of file CleanWeapon.c.
References Class::CastTo(), and GetPlugin().
Do() [9/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 107 of file CraftArmbandFlag.c.
Do() [10/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 61 of file CraftArmbandRag.c.
References Debug::Log().
Do() [11/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 128 of file CraftArmbandRaincoat.c.
Do() [12/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 62 of file CraftArrow.c.
References Debug::Log().
Do() [13/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftArrowBone.c.
References Debug::Log().
Do() [14/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftBait.c.
References Debug::Log().
Do() [15/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 56 of file CraftBaseBallBatBarbed.c.
References Math::RandomIntInclusive().
Do() [16/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftBloodBagIV.c.
References Class::CastTo().
Do() [17/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftBoneBait.c.
References Debug::Log().
Do() [18/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 89 of file CraftBoneHook.c.
References Debug::Log().
Do() [19/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 64 of file CraftBoneKnife.c.
References Class::CastTo().
Do() [20/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 73 of file CraftBow.c.
References Debug::Log().
Do() [21/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 89 of file CraftBurlapStrips.c.
References Debug::Log().
Do() [22/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 72 of file CraftCamoNetShelter.c.
References Debug::Log().
Do() [23/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 70 of file CraftCookingStand.c.
References Debug::Log().
Do() [24/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 64 of file CraftCourierBag.c.
References Debug::Log().
Do() [25/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 69 of file CraftFenceKit.c.
References Debug::Log().
Do() [26/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 87 of file CraftFireplace.c.
References GetGame().
Do() [27/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 74 of file CraftFishingRod.c.
References Debug::Log().
Do() [28/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftFishNetTrap.c.
References Debug::Log().
Do() [29/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftGasMask_Filter_Improvised.c.
References Debug::Log().
Do() [30/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftGhillieAttachment.c.
References Debug::Log().
Do() [31/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftGhillieBushrag.c.
References Debug::Log().
Do() [32/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftGhillieHood.c.
References Debug::Log().
Do() [33/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftGhillieSuit.c.
References Debug::Log().
Do() [34/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftGhillieTop.c.
References Debug::Log().
Do() [35/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftGorkaHelmetComplete.c.
Do() [36/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 85 of file CraftGutsRope.c.
References Debug::Log().
Do() [37/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file CraftHandDrillKit.c.
References Debug::Log().
Do() [38/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 67 of file CraftImprovisedBag.c.
References Debug::Log().
Do() [39/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 64 of file CraftImprovisedExplosive.c.
References Debug::Log().
Do() [40/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 67 of file CraftImprovisedLeatherBag.c.
References Debug::Log().
Do() [41/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 64 of file CraftLeatherCourierBag.c.
References Debug::Log().
Do() [42/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 61 of file CraftLeatherSack.c.
References Debug::Log().
Do() [43/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 64 of file CraftLongTorch.c.
References GetGame(), GetType(), and Debug::Log().
Do() [44/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 60 of file CraftMetalWire.c.
References Print().
Do() [45/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file CraftRabbitSnare.c.
References Debug::Log().
Do() [46/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 101 of file CraftRag.c.
References Class::CastTo().
Do() [47/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftRagRope.c.
References Debug::Log().
Do() [48/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftSalineBagIV.c.
References Class::CastTo(), and Debug::Log().
Do() [49/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 68 of file CraftShelterKit.c.
Do() [50/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 89 of file CraftSmallFishTrap.c.
References Debug::Log().
Do() [51/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 70 of file CraftSpearBone.c.
References Debug::Log().
Do() [52/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 70 of file CraftSpearStone.c.
References Debug::Log().
Do() [53/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 92 of file CraftSplint.c.
References Debug::Log(), and Type.
Do() [54/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 66 of file CraftStoneKnife.c.
References Class::CastTo().
Do() [55/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftSuppressor.c.
References Debug::Log().
Do() [56/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 86 of file CraftTannedLeather.c.
References Class::CastTo(), Debug::Log(), and m_PercentageUsed.
Do() [57/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 79 of file CraftTerritoryFlagKit.c.
References Debug::Log().
Do() [58/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 64 of file CraftTorch.c.
References GetGame(), InventorySlots::GetSlotIdFromString(), GetType(), and Debug::Log().
Do() [59/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftTripWire.c.
References TripwireTrap().
Do() [60/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 79 of file CraftTruck01DoubleWheel.c.
Do() [61/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 68 of file CraftWatchtowerKit.c.
References Debug::Log().
Do() [62/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftWoodenCrate.c.
References Debug::Log().
Do() [63/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file CraftWoodenPlank.c.
References Debug::Log().
Do() [64/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 13 of file CutOutSeeds.c.
References Math::Ceil(), Debug::Log(), and Math::RandomFloat().
Do() [65/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 88 of file DeCraftArmband.c.
References Debug::Log().
Do() [66/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 92 of file DeCraftBow.c.
References Debug::Log().
Do() [67/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 104 of file DeCraftCamoNetShelter.c.
References Debug::Log().
Do() [68/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 121 of file DeCraftCarrierComplete.c.
References Debug::Log().
Do() [69/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 109 of file DeCraftCarrierHolster.c.
References Debug::Log().
Do() [70/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 109 of file DeCraftCarrierPouches.c.
References Debug::Log().
Do() [71/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 92 of file DeCraftCookingStand.c.
References Debug::Log().
Do() [72/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 103 of file DeCraftCourierBag.c.
References Debug::Log().
Do() [73/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file DeCraftDetonator.c.
References Math::RandomFloatInclusive().
Do() [74/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 102 of file DeCraftFishingRod.c.
References Debug::Log().
Do() [75/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 102 of file DeCraftFishNetTrap.c.
References Debug::Log().
Do() [76/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 105 of file DeCraftGhillieAttachment.c.
References Debug::Log().
Do() [77/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 106 of file DeCraftGhillieBushrag.c.
References Debug::Log().
Do() [78/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 106 of file DeCraftGhillieHood.c.
References Debug::Log().
Do() [79/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 105 of file DeCraftGhillieSuit.c.
References Debug::Log().
Do() [80/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 106 of file DeCraftGhillieTop.c.
References Debug::Log().
Do() [81/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 92 of file DeCraftHandDrillKit.c.
References Debug::Log().
Do() [82/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 103 of file DeCraftImprovisedBag.c.
References Debug::Log().
Do() [83/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 103 of file DeCraftImprovisedLeatherBag.c.
References Debug::Log().
Do() [84/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 103 of file DeCraftLeatherCourierBag.c.
References Debug::Log().
Do() [85/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 88 of file DeCraftLeatherSack.c.
References Debug::Log().
Do() [86/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 92 of file DeCraftSnareTrap.c.
References Debug::Log().
Do() [87/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 92 of file DeCraftSpear.c.
References Debug::Log().
Do() [88/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 92 of file DeCraftSplint.c.
References Debug::Log().
Do() [89/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 93 of file DeCraftTripWire.c.
References Debug::Log().
Do() [90/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 84 of file DeCraftTruck01DoubleWheel.c.
Do() [91/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 85 of file DeCraftWoodenCrate.c.
References Class::CastTo(), GetMaxHealth(), Debug::Log(), Math::RandomFloat(), Math::RandomIntInclusive(), GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
Do() [92/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 79 of file DisinfectItem.c.
References Class::CastTo().
Do() [93/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 93 of file DrainLiquid.c.
References Liquid::Transfer().
Do() [94/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 79 of file ExtinguishTorch.c.
References Class::CastTo().
Do() [95/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 86 of file FillGasMask_Filter.c.
References Math::Round().
Do() [96/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file FillSyringe.c.
References Debug::Log().
Do() [97/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 73 of file FuelChainsaw.c.
References Class::CastTo().
Do() [98/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 91 of file LoadMagazine.c.
Do() [99/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 113 of file OpenCan.c.
References Class::CastTo(), and OpenItem::OpenAndSwitch().
Do() [100/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 64 of file PaintAK101.c.
References PaintItem::Paint().
Do() [101/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAK10130Mag.c.
References PaintItem::Paint().
Do() [102/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file PaintAK74.c.
References PaintItem::Paint().
Do() [103/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAK7430Mag.c.
References PaintItem::Paint().
Do() [104/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAK74HndgrdBlack.c.
Do() [105/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAK74HndgrdCamo.c.
Do() [106/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAK74WoodBttstckBlack.c.
Do() [107/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAK74WoodBttstckCamo.c.
Do() [108/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAKFoldingBttstck.c.
References PaintItem::Paint().
Do() [109/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAKMDrumMag.c.
References PaintItem::Paint().
Do() [110/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAKMPalm30Mag.c.
References PaintItem::Paint().
Do() [111/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAKPlasticBttstck.c.
References PaintItem::Paint().
Do() [112/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAKRailHndgrd.c.
References PaintItem::Paint().
Do() [113/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAKS74U.c.
References PaintItem::Paint().
Do() [114/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAKS74UBttstck.c.
References PaintItem::Paint().
Do() [115/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAKWoodBttstckBlack.c.
Do() [116/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintAKWoodBttstckCamo.c.
Do() [117/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintB95.c.
References PaintItem::Paint().
Do() [118/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintBallisticHelmet.c.
References PaintItem::Paint().
Do() [119/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintCMAG10.c.
References PaintItem::Paint().
Do() [120/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintCMAG20.c.
References PaintItem::Paint().
Do() [121/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintCMAG30.c.
References PaintItem::Paint().
Do() [122/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintCMAG40.c.
References PaintItem::Paint().
Do() [123/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintCz527.c.
References PaintItem::Paint().
Do() [124/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintCz527CamoBlack.c.
Do() [125/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintCz527CamoGreen.c.
Do() [126/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintDarkMotohelmet.c.
References PaintItem::Paint().
Do() [127/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintFirefighterAxe.c.
References PaintItem::Paint().
Do() [128/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieAttBlack.c.
Do() [129/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file PaintGhillieAttGreen.c.
References PaintItem::Paint().
Do() [130/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieAttGreenMossy.c.
Do() [131/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieBushragBlack.c.
Do() [132/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file PaintGhillieBushragGreen.c.
References PaintItem::Paint().
Do() [133/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieBushragGreenMossy.c.
Do() [134/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file PaintGhillieHoodBlack.c.
References PaintItem::Paint().
Do() [135/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieHoodGreen.c.
References PaintItem::Paint().
Do() [136/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieHoodGreenMossy.c.
Do() [137/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 63 of file PaintGhillieSuitBlack.c.
References PaintItem::Paint().
Do() [138/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieSuitGreen.c.
Do() [139/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieSuitGreenMossy.c.
Do() [140/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieTopBlack.c.
Do() [141/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieTopGreen.c.
Do() [142/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGhillieTopGreenMossy.c.
Do() [143/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGorkaHelmet.c.
References PaintItem::Paint().
Do() [144/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintGorkaHelmetComplete.c.
References PaintItem::Paint().
Do() [145/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintM4A1.c.
References PaintItem::Paint().
Do() [146/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintM4CQBBttstck.c.
References PaintItem::Paint().
Do() [147/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintM4MPBttstck.c.
References PaintItem::Paint().
Do() [148/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintM4MPHndgrd.c.
References PaintItem::Paint().
Do() [149/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintM4OEBttstck.c.
References PaintItem::Paint().
Do() [150/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintM4PlasticHndgrd.c.
References PaintItem::Paint().
Do() [151/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintM4RISHndgrd.c.
References PaintItem::Paint().
Do() [152/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 68 of file PaintMosin.c.
References PaintItem::Paint().
Do() [153/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintMosinCamoBlack.c.
Do() [154/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintMosinCamoGreen.c.
Do() [155/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintMotohelmet.c.
References PaintItem::Paint().
Do() [156/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintRuger1022.c.
References PaintItem::Paint().
Do() [157/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintSawedoffMosin.c.
References PaintItem::Paint().
Do() [158/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintSawedoffMosinCamoBlack.c.
Do() [159/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintSawedoffMosinCamoGreen.c.
Do() [160/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintSKS.c.
References PaintItem::Paint().
Do() [161/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 65 of file PaintZSh3PilotHelmet.c.
References PaintItem::Paint().
Do() [162/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 74 of file PatchItem.c.
References Class::CastTo(), and GetPlugin().
Do() [163/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 86 of file PeelPotato.c.
References Debug::Log().
Do() [164/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 87 of file PokeHolesBarrel.c.
Do() [165/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 93 of file PourLiquid.c.
References Liquid::Transfer().
Do() [166/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 86 of file PrepareChicken.c.
References DEFAULT_SPAWN_DISTANCE, GetPlugin(), PluginLifespan(), Math::RandomFloatInclusive(), and Math::RandomIntInclusive().
Do() [167/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 13 of file PrepareFish.c.
References Class::CastTo(), GetPlugin(), PluginLifespan(), and Math::RandomFloat().
Do() [168/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 99 of file PrepareRabbit.c.
References DEFAULT_SPAWN_DISTANCE, GetPlugin(), PluginLifespan(), Math::RandomFloatInclusive(), and Math::RandomIntInclusive().
Do() [169/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 70 of file PurifyWater.c.
Do() [170/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 81 of file RefuelTorch.c.
References GetGame().
Do() [171/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 72 of file RepairElectric.c.
References Class::CastTo(), and GetPlugin().
Do() [172/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 72 of file RepairEpoxy.c.
References Class::CastTo(), and GetPlugin().
Do() [173/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 72 of file RepairEyePatch.c.
Do() [174/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 77 of file RepairPlanks.c.
References Type.
Do() [175/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 71 of file RepairWithRags.c.
Do() [176/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 74 of file RepairWithTape.c.
References Class::CastTo(), and GetPlugin().
Do() [177/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 68 of file SawoffB95.c.
Do() [178/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 68 of file SawoffFAMAS.c.
Do() [179/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 82 of file SawOffIzh18.c.
Do() [180/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 82 of file SawOffIzh18Shotgun.c.
Do() [181/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 70 of file SawoffMagnum.c.
Do() [182/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 68 of file SawoffMosin.c.
Do() [183/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 70 of file SawoffMosinPainted.c.
Do() [184/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 68 of file SawoffShotgunIzh43.c.
Do() [185/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 92 of file SawWoodenLog.c.
Do() [186/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 104 of file SharpenBroom.c.
References Class::CastTo().
Do() [187/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 86 of file SharpenLongStick.c.
Do() [188/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 72 of file SharpenMelee.c.
References Class::CastTo(), and GetPlugin().
Do() [189/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 86 of file SharpenStick.c.
References Class::CastTo().
Do() [190/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 117 of file SplitBroom.c.
References Class::CastTo().
Do() [191/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 72 of file SplitFirewood.c.
References Debug::Log().
Do() [192/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 101 of file SplitLongWoodenStick.c.
Do() [193/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 89 of file SplitStones.c.
References Debug::Log().
Do() [194/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 80 of file Test.c.
Do() [195/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 68 of file UpgradeTorchWithLard.c.
References FlammableBase::Upgrade().
Do() [196/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 75 of file UpgradeTorchWithLiquidFuel.c.
References FlammableBase::Upgrade().
Do() [197/197]
override void Do (ItemBase ingredients[], PlayerBase player, array< ItemBase > results, float specialty_weight) inline private
Definition at line 67 of file WriteLetter.c.
References Debug::Log().
GetAllItems()
void GetAllItems (array< string > items) inline private
Definition at line 586 of file RecipeBase.c.
References m_Ingredients, MAX_NUMBER_OF_INGREDIENTS, and x.
GetID()
int GetID () inline private
Definition at line 575 of file RecipeBase.c.
References m_ID.
Referenced by PluginRecipesManagerBase::GetValidRecipesProper(), and PluginRecipesManagerBase::WalkRecipes().
GetIngredientMaskForItem()
int GetIngredientMaskForItem (string item) inline private
returns a mask which marks ingredient positions for a given item in this recipe(for example mask of value 3 [....000011] means this item is both ingredient 1 and 2 in this recipe[from right to left])
Definition at line 613 of file RecipeBase.c.
References int, m_Ingredients, MAX_NUMBER_OF_INGREDIENTS, Math::Pow(), and x.
GetLengthInSecs()
float GetLengthInSecs () inline private
Definition at line 75 of file RecipeBase.c.
References CRAFTING_TIME_UNIT_SIZE, and m_AnimationLength.
GetName()
string GetName () inline private
Definition at line 159 of file RecipeBase.c.
References m_Name.
GetSpecialty()
float GetSpecialty () inline private
Definition at line 80 of file RecipeBase.c.
References m_Specialty.
Init() [1/198]
void Init () private
Referenced by RecipeBase().
Init() [2/198]
override void Init () inline private
Definition at line 3 of file AttachHolster.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [3/198]
override void Init () inline private
Definition at line 3 of file AttachHolsterPouch.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [4/198]
override void Init () inline private
Definition at line 3 of file AttachPouch.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [5/198]
override void Init () inline private
Definition at line 3 of file AttachPouchesHolster.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [6/198]
override void Init () inline private
Definition at line 3 of file BloodTest.c.
References InsertIngredient(), and m_Name.
Init() [7/198]
override void Init () inline private
Definition at line 3 of file CleanRags.c.
References InsertIngredient(), and m_Name.
Init() [8/198]
override void Init () inline private
Definition at line 3 of file CleanWeapon.c.
References InsertIngredient(), and m_Name.
Init() [9/198]
override void Init () inline private
Definition at line 3 of file CraftArmbandFlag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [10/198]
override void Init () inline private
Definition at line 3 of file CraftArmbandRag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [11/198]
override void Init () inline private
Definition at line 3 of file CraftArmbandRaincoat.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [12/198]
override void Init () inline private
Definition at line 3 of file CraftArrow.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [13/198]
override void Init () inline private
Definition at line 3 of file CraftArrowBone.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [14/198]
override void Init () inline private
Definition at line 3 of file CraftBait.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [15/198]
override void Init () inline private
Definition at line 3 of file CraftBaseBallBatBarbed.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [16/198]
override void Init () inline private
Definition at line 3 of file CraftBaseBallBatNailed.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [17/198]
override void Init () inline private
Definition at line 3 of file CraftBloodBagIV.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [18/198]
override void Init () inline private
Definition at line 3 of file CraftBoneBait.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [19/198]
override void Init () inline private
Definition at line 3 of file CraftBoneHook.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [20/198]
override void Init () inline private
Definition at line 3 of file CraftBoneKnife.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [21/198]
override void Init () inline private
Definition at line 3 of file CraftBow.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [22/198]
override void Init () inline private
Definition at line 3 of file CraftBurlapStrips.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [23/198]
override void Init () inline private
Definition at line 3 of file CraftCamoNetShelter.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [24/198]
override void Init () inline private
Definition at line 3 of file CraftCookingStand.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [25/198]
override void Init () inline private
Definition at line 3 of file CraftCourierBag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [26/198]
override void Init () inline private
Definition at line 3 of file CraftFenceKit.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [27/198]
override void Init () inline private
Definition at line 3 of file CraftFireplace.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [28/198]
override void Init () inline private
Definition at line 3 of file CraftFishingRod.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [29/198]
override void Init () inline private
Definition at line 3 of file CraftFishNetTrap.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [30/198]
override void Init () inline private
Definition at line 3 of file CraftGasMask_Filter_Improvised.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [31/198]
override void Init () inline private
Definition at line 3 of file CraftGhillieAttachment.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [32/198]
override void Init () inline private
Definition at line 3 of file CraftGhillieBushrag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [33/198]
override void Init () inline private
Definition at line 3 of file CraftGhillieHood.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [34/198]
override void Init () inline private
Definition at line 3 of file CraftGhillieSuit.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [35/198]
override void Init () inline private
Definition at line 3 of file CraftGhillieTop.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [36/198]
override void Init () inline private
Definition at line 3 of file CraftGorkaHelmetComplete.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [37/198]
override void Init () inline private
Definition at line 3 of file CraftGutsRope.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [38/198]
override void Init () inline private
Definition at line 3 of file CraftHandDrillKit.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [39/198]
override void Init () inline private
Definition at line 3 of file CraftImprovisedBag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [40/198]
override void Init () inline private
Definition at line 3 of file CraftImprovisedExplosive.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [41/198]
override void Init () inline private
Definition at line 3 of file CraftImprovisedLeatherBag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [42/198]
override void Init () inline private
Definition at line 3 of file CraftLeatherCourierBag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [43/198]
override void Init () inline private
Definition at line 3 of file CraftLeatherSack.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [44/198]
override void Init () inline private
Definition at line 3 of file CraftLongTorch.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [45/198]
override void Init () inline private
Definition at line 3 of file CraftMetalWire.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [46/198]
override void Init () inline private
Definition at line 3 of file CraftRabbitSnare.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [47/198]
override void Init () inline private
Definition at line 3 of file CraftRag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [48/198]
override void Init () inline private
Definition at line 3 of file CraftRagRope.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [49/198]
override void Init () inline private
Definition at line 3 of file CraftSalineBagIV.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [50/198]
override void Init () inline private
Definition at line 3 of file CraftShelterKit.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [51/198]
override void Init () inline private
Definition at line 3 of file CraftSmallFishTrap.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [52/198]
override void Init () inline private
Definition at line 3 of file CraftSpearBone.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [53/198]
override void Init () inline private
Definition at line 3 of file CraftSpearStone.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [54/198]
override void Init () inline private
Definition at line 3 of file CraftSplint.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [55/198]
override void Init () inline private
Definition at line 3 of file CraftStoneKnife.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [56/198]
override void Init () inline private
Definition at line 3 of file CraftSuppressor.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [57/198]
override void Init () inline private
Definition at line 6 of file CraftTannedLeather.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [58/198]
override void Init () inline private
Definition at line 3 of file CraftTerritoryFlagKit.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [59/198]
override void Init () inline private
Definition at line 3 of file CraftTorch.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [60/198]
override void Init () inline private
Definition at line 3 of file CraftTripWire.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [61/198]
override void Init () inline private
Definition at line 3 of file CraftTruck01DoubleWheel.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [62/198]
override void Init () inline private
Definition at line 3 of file CraftWatchtowerKit.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [63/198]
override void Init () inline private
Definition at line 3 of file CraftWoodenCrate.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [64/198]
override void Init () inline private
Definition at line 3 of file CraftWoodenPlank.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [65/198]
override void Init () inline private
Definition at line 3 of file CutOutSeeds.c.
Init() [66/198]
override void Init () inline private
Definition at line 5 of file DeCraftArmband.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [67/198]
override void Init () inline private
Definition at line 3 of file DeCraftBow.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [68/198]
override void Init () inline private
Definition at line 3 of file DeCraftCamoNetShelter.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [69/198]
override void Init () inline private
Definition at line 3 of file DeCraftCarrierComplete.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [70/198]
override void Init () inline private
Definition at line 3 of file DeCraftCarrierHolster.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [71/198]
override void Init () inline private
Definition at line 3 of file DeCraftCarrierPouches.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [72/198]
override void Init () inline private
Definition at line 3 of file DeCraftCookingStand.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [73/198]
override void Init () inline private
Definition at line 3 of file DeCraftCourierBag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [74/198]
override void Init () inline private
Definition at line 5 of file DeCraftDetonator.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [75/198]
override void Init () inline private
Definition at line 3 of file DeCraftFishingRod.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [76/198]
override void Init () inline private
Definition at line 3 of file DeCraftFishNetTrap.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [77/198]
override void Init () inline private
Definition at line 3 of file DeCraftGhillieAttachment.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [78/198]
override void Init () inline private
Definition at line 3 of file DeCraftGhillieBushrag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [79/198]
override void Init () inline private
Definition at line 3 of file DeCraftGhillieHood.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [80/198]
override void Init () inline private
Definition at line 3 of file DeCraftGhillieSuit.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [81/198]
override void Init () inline private
Definition at line 3 of file DeCraftGhillieTop.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [82/198]
override void Init () inline private
Definition at line 3 of file DeCraftHandDrillKit.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [83/198]
override void Init () inline private
Definition at line 3 of file DeCraftImprovisedBag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [84/198]
override void Init () inline private
Definition at line 3 of file DeCraftImprovisedLeatherBag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [85/198]
override void Init () inline private
Definition at line 3 of file DeCraftLeatherCourierBag.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [86/198]
override void Init () inline private
Definition at line 3 of file DeCraftLeatherSack.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [87/198]
override void Init () inline private
Definition at line 3 of file DeCraftSnareTrap.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [88/198]
override void Init () inline private
Definition at line 3 of file DeCraftSpear.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [89/198]
override void Init () inline private
Definition at line 3 of file DeCraftSplint.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [90/198]
override void Init () inline private
Definition at line 3 of file DeCraftTripWire.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [91/198]
override void Init () inline private
Definition at line 3 of file DeCraftTruck01DoubleWheel.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [92/198]
override void Init () inline private
Definition at line 3 of file DeCraftWoodenCrate.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [93/198]
override void Init () inline private
Definition at line 3 of file DisinfectItem.c.
References InsertIngredient(), and m_Name.
Init() [94/198]
override void Init () inline private
Definition at line 3 of file DrainLiquid.c.
References InsertIngredient(), and m_Name.
Init() [95/198]
override void Init () inline private
Definition at line 3 of file ExtinguishTorch.c.
References InsertIngredient(), and m_Name.
Init() [96/198]
override void Init () inline private
Definition at line 3 of file FillGasMask_Filter.c.
References InsertIngredient(), and m_Name.
Init() [97/198]
override void Init () inline private
Definition at line 3 of file FillSyringe.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [98/198]
override void Init () inline private
Definition at line 3 of file FuelChainsaw.c.
References InsertIngredient(), and m_Name.
Init() [99/198]
override void Init () inline private
Definition at line 3 of file LoadMagazine.c.
References InsertIngredient(), and m_Name.
Init() [100/198]
override void Init () inline private
Definition at line 3 of file OpenCan.c.
References InsertIngredient(), and m_Name.
Init() [101/198]
override void Init () inline private
Definition at line 3 of file PaintAK101.c.
References InsertIngredient(), and m_Name.
Init() [102/198]
override void Init () inline private
Definition at line 3 of file PaintAK10130Mag.c.
References InsertIngredient(), and m_Name.
Init() [103/198]
override void Init () inline private
Definition at line 3 of file PaintAK74.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [104/198]
override void Init () inline private
Definition at line 3 of file PaintAK7430Mag.c.
References InsertIngredient(), and m_Name.
Init() [105/198]
override void Init () inline private
Definition at line 3 of file PaintAK74HndgrdBlack.c.
References InsertIngredient(), and m_Name.
Init() [106/198]
override void Init () inline private
Definition at line 3 of file PaintAK74HndgrdCamo.c.
References InsertIngredient(), and m_Name.
Init() [107/198]
override void Init () inline private
Definition at line 3 of file PaintAK74WoodBttstckBlack.c.
References InsertIngredient(), and m_Name.
Init() [108/198]
override void Init () inline private
Definition at line 3 of file PaintAK74WoodBttstckCamo.c.
References InsertIngredient(), and m_Name.
Init() [109/198]
override void Init () inline private
Definition at line 3 of file PaintAKFoldingBttstck.c.
References InsertIngredient(), and m_Name.
Init() [110/198]
override void Init () inline private
Definition at line 3 of file PaintAKMDrumMag.c.
References InsertIngredient(), and m_Name.
Init() [111/198]
override void Init () inline private
Definition at line 3 of file PaintAKMPalm30Mag.c.
References InsertIngredient(), and m_Name.
Init() [112/198]
override void Init () inline private
Definition at line 3 of file PaintAKPlasticBttstck.c.
References InsertIngredient(), and m_Name.
Init() [113/198]
override void Init () inline private
Definition at line 3 of file PaintAKRailHndgrd.c.
References InsertIngredient(), and m_Name.
Init() [114/198]
override void Init () inline private
Definition at line 3 of file PaintAKS74U.c.
References InsertIngredient(), and m_Name.
Init() [115/198]
override void Init () inline private
Definition at line 3 of file PaintAKS74UBttstck.c.
References InsertIngredient(), and m_Name.
Init() [116/198]
override void Init () inline private
Definition at line 3 of file PaintAKWoodBttstckBlack.c.
References InsertIngredient(), and m_Name.
Init() [117/198]
override void Init () inline private
Definition at line 3 of file PaintAKWoodBttstckCamo.c.
References InsertIngredient(), and m_Name.
Init() [118/198]
override void Init () inline private
Definition at line 3 of file PaintB95.c.
References InsertIngredient(), and m_Name.
Init() [119/198]
override void Init () inline private
Definition at line 3 of file PaintBallisticHelmet.c.
References InsertIngredient(), and m_Name.
Init() [120/198]
override void Init () inline private
Definition at line 3 of file PaintCMAG10.c.
References InsertIngredient(), and m_Name.
Init() [121/198]
override void Init () inline private
Definition at line 3 of file PaintCMAG20.c.
References InsertIngredient(), and m_Name.
Init() [122/198]
override void Init () inline private
Definition at line 3 of file PaintCMAG30.c.
References InsertIngredient(), and m_Name.
Init() [123/198]
override void Init () inline private
Definition at line 3 of file PaintCMAG40.c.
References InsertIngredient(), and m_Name.
Init() [124/198]
override void Init () inline private
Definition at line 3 of file PaintCz527.c.
References InsertIngredient(), and m_Name.
Init() [125/198]
override void Init () inline private
Definition at line 3 of file PaintCz527CamoBlack.c.
References InsertIngredient(), and m_Name.
Init() [126/198]
override void Init () inline private
Definition at line 3 of file PaintCz527CamoGreen.c.
References InsertIngredient(), and m_Name.
Init() [127/198]
override void Init () inline private
Definition at line 3 of file PaintDarkMotohelmet.c.
References InsertIngredient(), and m_Name.
Init() [128/198]
override void Init () inline private
Definition at line 3 of file PaintFirefighterAxe.c.
References InsertIngredient(), and m_Name.
Init() [129/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieAttBlack.c.
References InsertIngredient(), and m_Name.
Init() [130/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieAttGreen.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [131/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieAttGreenMossy.c.
References InsertIngredient(), and m_Name.
Init() [132/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieBushragBlack.c.
References InsertIngredient(), and m_Name.
Init() [133/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieBushragGreen.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [134/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieBushragGreenMossy.c.
References InsertIngredient(), and m_Name.
Init() [135/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieHoodBlack.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [136/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieHoodGreen.c.
References InsertIngredient(), and m_Name.
Init() [137/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieHoodGreenMossy.c.
References InsertIngredient(), and m_Name.
Init() [138/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieSuitBlack.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [139/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieSuitGreen.c.
References InsertIngredient(), and m_Name.
Init() [140/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieSuitGreenMossy.c.
References InsertIngredient(), and m_Name.
Init() [141/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieTopBlack.c.
References InsertIngredient(), and m_Name.
Init() [142/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieTopGreen.c.
References InsertIngredient(), and m_Name.
Init() [143/198]
override void Init () inline private
Definition at line 3 of file PaintGhillieTopGreenMossy.c.
References InsertIngredient(), and m_Name.
Init() [144/198]
override void Init () inline private
Definition at line 3 of file PaintGorkaHelmet.c.
References InsertIngredient(), and m_Name.
Init() [145/198]
override void Init () inline private
Definition at line 3 of file PaintGorkaHelmetComplete.c.
References InsertIngredient(), and m_Name.
Init() [146/198]
override void Init () inline private
Definition at line 3 of file PaintM4A1.c.
References InsertIngredient(), and m_Name.
Init() [147/198]
override void Init () inline private
Definition at line 3 of file PaintM4CQBBttstck.c.
References InsertIngredient(), and m_Name.
Init() [148/198]
override void Init () inline private
Definition at line 3 of file PaintM4MPBttstck.c.
References InsertIngredient(), and m_Name.
Init() [149/198]
override void Init () inline private
Definition at line 3 of file PaintM4MPHndgrd.c.
References InsertIngredient(), and m_Name.
Init() [150/198]
override void Init () inline private
Definition at line 3 of file PaintM4OEBttstck.c.
References InsertIngredient(), and m_Name.
Init() [151/198]
override void Init () inline private
Definition at line 3 of file PaintM4PlasticHndgrd.c.
References InsertIngredient(), and m_Name.
Init() [152/198]
override void Init () inline private
Definition at line 3 of file PaintM4RISHndgrd.c.
References InsertIngredient(), and m_Name.
Init() [153/198]
override void Init () inline private
Definition at line 3 of file PaintMosin.c.
References InsertIngredient(), and m_Name.
Init() [154/198]
override void Init () inline private
Definition at line 3 of file PaintMosinCamoBlack.c.
References InsertIngredient(), and m_Name.
Init() [155/198]
override void Init () inline private
Definition at line 3 of file PaintMosinCamoGreen.c.
References InsertIngredient(), and m_Name.
Init() [156/198]
override void Init () inline private
Definition at line 3 of file PaintMotohelmet.c.
References InsertIngredient(), and m_Name.
Init() [157/198]
override void Init () inline private
Definition at line 3 of file PaintRuger1022.c.
References InsertIngredient(), and m_Name.
Init() [158/198]
override void Init () inline private
Definition at line 3 of file PaintSawedoffMosin.c.
References InsertIngredient(), and m_Name.
Init() [159/198]
override void Init () inline private
Definition at line 3 of file PaintSawedoffMosinCamoBlack.c.
References InsertIngredient(), and m_Name.
Init() [160/198]
override void Init () inline private
Definition at line 3 of file PaintSawedoffMosinCamoGreen.c.
References InsertIngredient(), and m_Name.
Init() [161/198]
override void Init () inline private
Definition at line 3 of file PaintSKS.c.
References InsertIngredient(), and m_Name.
Init() [162/198]
override void Init () inline private
Definition at line 3 of file PaintZSh3PilotHelmet.c.
References InsertIngredient(), and m_Name.
Init() [163/198]
override void Init () inline private
Definition at line 3 of file PatchItem.c.
References InsertIngredient(), and m_Name.
Init() [164/198]
override void Init () inline private
Definition at line 3 of file PeelPotato.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [165/198]
override void Init () inline private
Definition at line 3 of file PokeHolesBarrel.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [166/198]
override void Init () inline private
Definition at line 3 of file PourLiquid.c.
References InsertIngredient(), and m_Name.
Init() [167/198]
override void Init () inline private
Definition at line 3 of file PrepareChicken.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [168/198]
override void Init () inline private
Definition at line 3 of file PrepareFish.c.
Init() [169/198]
override void Init () inline private
Definition at line 3 of file PrepareRabbit.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [170/198]
override void Init () inline private
Definition at line 3 of file PurifyWater.c.
References InsertIngredient(), and m_Name.
Init() [171/198]
override void Init () inline private
Definition at line 5 of file RefuelTorch.c.
References InsertIngredient(), and m_Name.
Init() [172/198]
override void Init () inline private
Definition at line 3 of file RepairElectric.c.
References InsertIngredient(), and m_Name.
Init() [173/198]
override void Init () inline private
Definition at line 3 of file RepairEpoxy.c.
References InsertIngredient(), and m_Name.
Init() [174/198]
override void Init () inline private
Definition at line 3 of file RepairEyePatch.c.
References InsertIngredient(), and m_Name.
Init() [175/198]
override void Init () inline private
Definition at line 3 of file RepairPlanks.c.
References InsertIngredient(), and m_Name.
Init() [176/198]
override void Init () inline private
Definition at line 3 of file RepairWithRags.c.
References InsertIngredient(), and m_Name.
Init() [177/198]
override void Init () inline private
Definition at line 3 of file RepairWithTape.c.
References InsertIngredient(), and m_Name.
Init() [178/198]
override void Init () inline private
Definition at line 3 of file SawoffB95.c.
References InsertIngredient(), and m_Name.
Init() [179/198]
override void Init () inline private
Definition at line 3 of file SawoffFAMAS.c.
References InsertIngredient(), and m_Name.
Init() [180/198]
override void Init () inline private
Definition at line 3 of file SawOffIzh18.c.
References InsertIngredient(), and m_Name.
Init() [181/198]
override void Init () inline private
Definition at line 3 of file SawOffIzh18Shotgun.c.
References InsertIngredient(), and m_Name.
Init() [182/198]
override void Init () inline private
Definition at line 3 of file SawoffMagnum.c.
References InsertIngredient(), and m_Name.
Init() [183/198]
override void Init () inline private
Definition at line 3 of file SawoffMosin.c.
References InsertIngredient(), and m_Name.
Init() [184/198]
override void Init () inline private
Definition at line 3 of file SawoffMosinPainted.c.
References InsertIngredient(), and m_Name.
Init() [185/198]
override void Init () inline private
Definition at line 3 of file SawoffShotgunIzh43.c.
References InsertIngredient(), and m_Name.
Init() [186/198]
override void Init () inline private
Definition at line 3 of file SawWoodenLog.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [187/198]
override void Init () inline private
Definition at line 3 of file SharpenBroom.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [188/198]
override void Init () inline private
Definition at line 3 of file SharpenLongStick.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [189/198]
override void Init () inline private
Definition at line 3 of file SharpenMelee.c.
References InsertIngredient(), and m_Name.
Init() [190/198]
override void Init () inline private
Definition at line 3 of file SharpenStick.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [191/198]
override void Init () inline private
Definition at line 3 of file SplitBroom.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [192/198]
override void Init () inline private
Definition at line 3 of file SplitFirewood.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [193/198]
override void Init () inline private
Definition at line 3 of file SplitLongWoodenStick.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [194/198]
override void Init () inline private
Definition at line 3 of file SplitStones.c.
References AddResult(), InsertIngredient(), and m_Name.
Init() [195/198]
override void Init () inline private
Definition at line 3 of file Test.c.
References InsertIngredient(), and m_Name.
Init() [196/198]
override void Init () inline private
Definition at line 3 of file UpgradeTorchWithLard.c.
References InsertIngredient(), and m_Name.
Init() [197/198]
override void Init () inline private
Definition at line 3 of file UpgradeTorchWithLiquidFuel.c.
References InsertIngredient(), and m_Name.
Init() [198/198]
override void Init () inline private
Definition at line 3 of file WriteLetter.c.
References InsertIngredient(), and m_Name.
InsertIngredient()
void InsertIngredient (int index, string ingredient) inline private
Definition at line 133 of file RecipeBase.c.
References m_Ingredients.
Referenced by Init().
IsInstaRecipe()
bool IsInstaRecipe () inline private
Definition at line 164 of file RecipeBase.c.
References m_IsInstaRecipe.
IsItemInRecipe()
bool IsItemInRecipe (string item) inline private
Definition at line 599 of file RecipeBase.c.
References m_Ingredients, MAX_NUMBER_OF_INGREDIENTS, and x.
IsRecipeAnywhere()
bool IsRecipeAnywhere () inline private
Definition at line 85 of file RecipeBase.c.
References m_AnywhereInInventory.
Referenced by CheckRecipe().
OnSelected() [1/2]
void OnSelected (ItemBase item1, ItemBase item2, PlayerBase player) inline private
Definition at line 510 of file RecipeBase.c.
Referenced by OnSelectedRecipe().
OnSelected() [2/2]
override void OnSelected (ItemBase item1, ItemBase item2, PlayerBase player) inline private
Definition at line 59 of file LoadMagazine.c.
OnSelectedRecipe()
void OnSelectedRecipe (ItemBase item1, ItemBase item2, PlayerBase player) inline private
Definition at line 499 of file RecipeBase.c.
References Error(), and OnSelected().
PerformRecipe()
void PerformRecipe (ItemBase item1, ItemBase item2, PlayerBase player) inline private
Definition at line 516 of file RecipeBase.c.
References ApplyModificationsIngredients(), ApplyModificationsResults(), ApplySoftSkillsSpecialty(), CheckRecipe(), DeleleIngredientsPass(), Do(), Error(), Debug::Log(), m_IngredientsSorted, m_Specialty, and SpawnItems().
Referenced by PluginRecipesManagerBase::PerformRecipeServer().
RemoveIngredient()
void RemoveIngredient (int index, string ingredient) inline private
Definition at line 139 of file RecipeBase.c.
References m_Ingredients.
SetID()
void SetID (int id) inline private
Definition at line 581 of file RecipeBase.c.
References m_ID.
Referenced by PluginRecipesManagerBase::RegisterRecipe().
SpawnItems()
void SpawnItems (ItemBase ingredients[], PlayerBase player, array< ItemBase > spawned_objects) inline private
Definition at line 172 of file RecipeBase.c.
References Error(), Debug::Log(), m_ItemsToCreate, m_NumberOfResults, m_ResultInheritsColor, m_ResultSpawnDistance, m_ResultToInventory, and ToString().
Referenced by PerformRecipe().
TransferItemsToNew()
void TransferItemsToNew (PlayerBase player, ItemBase barrel_old, ItemBase barrel_new) inline private
Definition at line 91 of file PokeHolesBarrel.c.
Field Documentation
m_AnimationLength
float m_AnimationLength = 1 private
Definition at line 21 of file RecipeBase.c.
Referenced by GetLengthInSecs().
m_AnywhereInInventory
bool m_AnywhereInInventory private
Definition at line 25 of file RecipeBase.c.
Referenced by IsRecipeAnywhere().
m_ID
int m_ID private
Definition at line 19 of file RecipeBase.c.
Referenced by GetID(), and SetID().
m_IngredientAddHealth
float m_IngredientAddHealth[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 34 of file RecipeBase.c.
Referenced by ApplyModificationsIngredients().
m_IngredientAddQuantity
float m_IngredientAddQuantity[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 35 of file RecipeBase.c.
Referenced by ApplyModificationsIngredients().
m_IngredientDestroy
bool m_IngredientDestroy[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 37 of file RecipeBase.c.
Referenced by ApplyModificationsIngredients().
m_Ingredients
ref array<string> m_Ingredients[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 7 of file RecipeBase.c.
Referenced by CheckIngredientMatch(), GetAllItems(), GetIngredientMaskForItem(), InsertIngredient(), IsItemInRecipe(), RecipeBase(), RemoveIngredient(), and PluginRecipesManagerBase::WalkRecipes().
m_IngredientSetHealth
float m_IngredientSetHealth[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 36 of file RecipeBase.c.
Referenced by ApplyModificationsIngredients().
m_IngredientsSorted
ItemBase m_IngredientsSorted[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 11 of file RecipeBase.c.
Referenced by CheckIngredientMatch(), CheckRecipe(), PerformRecipe(), and RecipeBase().
m_IngredientsToBeDeleted
ref array<ItemBase> m_IngredientsToBeDeleted = new array<ItemBase> private
Definition at line 16 of file RecipeBase.c.
Referenced by ApplyModificationsIngredients(), and DeleleIngredientsPass().
m_IngredientUseSoftSkills
bool m_IngredientUseSoftSkills[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 33 of file RecipeBase.c.
Referenced by ApplyModificationsIngredients().
m_IsInstaRecipe
bool m_IsInstaRecipe private
Definition at line 23 of file RecipeBase.c.
Referenced by IsInstaRecipe().
m_Items
ItemBase m_Items[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 9 of file RecipeBase.c.
Referenced by CheckIngredientMatch().
m_ItemsToCreate
string m_ItemsToCreate[MAXIMUM_RESULTS] private
Definition at line 6 of file RecipeBase.c.
Referenced by AddResult(), and SpawnItems().
m_MaxDamageIngredient
float m_MaxDamageIngredient[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 31 of file RecipeBase.c.
Referenced by CheckConditions().
m_MaxQuantityIngredient
float m_MaxQuantityIngredient[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 29 of file RecipeBase.c.
Referenced by CheckConditions().
m_MinDamageIngredient
float m_MinDamageIngredient[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 30 of file RecipeBase.c.
Referenced by CheckConditions().
m_MinQuantityIngredient
float m_MinQuantityIngredient[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 28 of file RecipeBase.c.
Referenced by CheckConditions().
m_Name
string m_Name private
Definition at line 17 of file RecipeBase.c.
Referenced by GetName(), and RecipeBase().
m_NumberOfResults
int m_NumberOfResults private
Definition at line 20 of file RecipeBase.c.
Referenced by AddResult(), ApplyModificationsResults(), RecipeBase(), and SpawnItems().
m_PercentageUsed
float m_PercentageUsed = 0.05 private
Definition at line 3 of file CraftTannedLeather.c.
Referenced by CanDo(), and Do().
m_ResultInheritsColor
int m_ResultInheritsColor[MAXIMUM_RESULTS] private
Definition at line 46 of file RecipeBase.c.
Referenced by SpawnItems().
m_ResultInheritsHealth
int m_ResultInheritsHealth[MAXIMUM_RESULTS] private
Definition at line 45 of file RecipeBase.c.
Referenced by ApplyModificationsResults().
m_ResultReplacesIngredient
int m_ResultReplacesIngredient[MAXIMUM_RESULTS] private
Definition at line 47 of file RecipeBase.c.
Referenced by ApplyModificationsResults().
m_ResultSetFullQuantity
bool m_ResultSetFullQuantity[MAXIMUM_RESULTS] private
Definition at line 40 of file RecipeBase.c.
Referenced by ApplyModificationsResults().
m_ResultSetHealth
float m_ResultSetHealth[MAXIMUM_RESULTS] private
Definition at line 42 of file RecipeBase.c.
Referenced by ApplyModificationsResults().
m_ResultSetQuantity
float m_ResultSetQuantity[MAXIMUM_RESULTS] private
Definition at line 41 of file RecipeBase.c.
Referenced by ApplyModificationsResults().
m_ResultSpawnDistance
float m_ResultSpawnDistance[MAXIMUM_RESULTS] private
Definition at line 43 of file RecipeBase.c.
Referenced by RecipeBase(), and SpawnItems().
m_ResultToInventory
int m_ResultToInventory[MAXIMUM_RESULTS] private
Definition at line 44 of file RecipeBase.c.
Referenced by SpawnItems().
m_ResultUseSoftSkills
bool m_ResultUseSoftSkills[MAXIMUM_RESULTS] private
Definition at line 48 of file RecipeBase.c.
Referenced by ApplyModificationsResults().
m_Specialty
float m_Specialty = 0 private
Definition at line 22 of file RecipeBase.c.
Referenced by ApplyModificationsIngredients(), ApplyModificationsResults(), ApplySoftSkillsSpecialty(), GetSpecialty(), and PerformRecipe().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/Recipes/RecipeBase.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftTannedLeather.c
P:/scripts/4_World/Classes/Recipes/Recipes/AttachHolster.c
P:/scripts/4_World/Classes/Recipes/Recipes/AttachHolsterPouch.c
P:/scripts/4_World/Classes/Recipes/Recipes/AttachPouch.c
P:/scripts/4_World/Classes/Recipes/Recipes/AttachPouchesHolster.c
P:/scripts/4_World/Classes/Recipes/Recipes/BloodTest.c
P:/scripts/4_World/Classes/Recipes/Recipes/CleanRags.c
P:/scripts/4_World/Classes/Recipes/Recipes/CleanWeapon.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftArmbandFlag.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftArmbandRag.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftArmbandRaincoat.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftArrow.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftArrowBone.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftBait.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftBaseBallBatBarbed.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftBaseBallBatNailed.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftBloodBagIV.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftBoneBait.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftBoneHook.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftBoneKnife.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftBow.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftBurlapStrips.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftCamoNetShelter.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftCookingStand.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftCourierBag.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftFenceKit.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftFireplace.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftFishingRod.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftFishNetTrap.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftGasMask_Filter_Improvised.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftGhillieAttachment.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftGhillieBushrag.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftGhillieHood.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftGhillieSuit.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftGhillieTop.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftGorkaHelmetComplete.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftGutsRope.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftHandDrillKit.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftImprovisedBag.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftImprovisedExplosive.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftImprovisedLeatherBag.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftLeatherCourierBag.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftLeatherSack.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftLongTorch.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftMetalWire.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftRabbitSnare.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftRag.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftRagRope.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftSalineBagIV.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftShelterKit.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftSmallFishTrap.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftSpearBone.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftSpearStone.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftSplint.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftStoneKnife.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftSuppressor.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftTerritoryFlagKit.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftTorch.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftTripWire.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftTruck01DoubleWheel.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftWatchtowerKit.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftWoodenCrate.c
P:/scripts/4_World/Classes/Recipes/Recipes/CraftWoodenPlank.c
P:/scripts/4_World/Classes/Recipes/Recipes/CutOutSeeds.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftArmband.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftBow.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftCamoNetShelter.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftCarrierComplete.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftCarrierHolster.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftCarrierPouches.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftCookingStand.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftCourierBag.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftDetonator.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftFishingRod.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftFishNetTrap.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftGhillieAttachment.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftGhillieBushrag.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftGhillieHood.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftGhillieSuit.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftGhillieTop.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftHandDrillKit.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftImprovisedBag.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftImprovisedLeatherBag.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftLeatherCourierBag.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftLeatherSack.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftSnareTrap.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftSpear.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftSplint.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftTripWire.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftTruck01DoubleWheel.c
P:/scripts/4_World/Classes/Recipes/Recipes/DeCraftWoodenCrate.c
P:/scripts/4_World/Classes/Recipes/Recipes/DisinfectItem.c
P:/scripts/4_World/Classes/Recipes/Recipes/DrainLiquid.c
P:/scripts/4_World/Classes/Recipes/Recipes/ExtinguishTorch.c
P:/scripts/4_World/Classes/Recipes/Recipes/FillGasMask_Filter.c
P:/scripts/4_World/Classes/Recipes/Recipes/FillSyringe.c
P:/scripts/4_World/Classes/Recipes/Recipes/FuelChainsaw.c
P:/scripts/4_World/Classes/Recipes/Recipes/LoadMagazine.c
P:/scripts/4_World/Classes/Recipes/Recipes/OpenCan.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAK101.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAK10130Mag.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAK74.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAK7430Mag.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAK74HndgrdBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAK74HndgrdCamo.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAK74WoodBttstckBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAK74WoodBttstckCamo.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAKFoldingBttstck.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAKMDrumMag.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAKMPalm30Mag.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAKPlasticBttstck.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAKRailHndgrd.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAKS74U.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAKS74UBttstck.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAKWoodBttstckBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintAKWoodBttstckCamo.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintB95.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintBallisticHelmet.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintCMAG10.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintCMAG20.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintCMAG30.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintCMAG40.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintCz527.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintCz527CamoBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintCz527CamoGreen.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintDarkMotohelmet.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintFirefighterAxe.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieAttBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieAttGreen.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieAttGreenMossy.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieBushragBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieBushragGreen.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieBushragGreenMossy.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieHoodBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieHoodGreen.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieHoodGreenMossy.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieSuitBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieSuitGreen.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieSuitGreenMossy.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieTopBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieTopGreen.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGhillieTopGreenMossy.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGorkaHelmet.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintGorkaHelmetComplete.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintM4A1.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintM4CQBBttstck.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintM4MPBttstck.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintM4MPHndgrd.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintM4OEBttstck.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintM4PlasticHndgrd.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintM4RISHndgrd.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintMosin.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintMosinCamoBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintMosinCamoGreen.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintMotohelmet.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintRuger1022.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintSawedoffMosin.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintSawedoffMosinCamoBlack.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintSawedoffMosinCamoGreen.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintSKS.c
P:/scripts/4_World/Classes/Recipes/Recipes/PaintZSh3PilotHelmet.c
P:/scripts/4_World/Classes/Recipes/Recipes/PatchItem.c
P:/scripts/4_World/Classes/Recipes/Recipes/PeelPotato.c
P:/scripts/4_World/Classes/Recipes/Recipes/PokeHolesBarrel.c
P:/scripts/4_World/Classes/Recipes/Recipes/PourLiquid.c
P:/scripts/4_World/Classes/Recipes/Recipes/PrepareChicken.c
P:/scripts/4_World/Classes/Recipes/Recipes/PrepareFish.c
P:/scripts/4_World/Classes/Recipes/Recipes/PrepareRabbit.c
P:/scripts/4_World/Classes/Recipes/Recipes/PurifyWater.c
P:/scripts/4_World/Classes/Recipes/Recipes/RefuelTorch.c
P:/scripts/4_World/Classes/Recipes/Recipes/RepairElectric.c
P:/scripts/4_World/Classes/Recipes/Recipes/RepairEpoxy.c
P:/scripts/4_World/Classes/Recipes/Recipes/RepairEyePatch.c
P:/scripts/4_World/Classes/Recipes/Recipes/RepairPlanks.c
P:/scripts/4_World/Classes/Recipes/Recipes/RepairWithRags.c
P:/scripts/4_World/Classes/Recipes/Recipes/RepairWithTape.c
P:/scripts/4_World/Classes/Recipes/Recipes/SawoffB95.c
P:/scripts/4_World/Classes/Recipes/Recipes/SawoffFAMAS.c
P:/scripts/4_World/Classes/Recipes/Recipes/SawOffIzh18.c
P:/scripts/4_World/Classes/Recipes/Recipes/SawOffIzh18Shotgun.c
P:/scripts/4_World/Classes/Recipes/Recipes/SawoffMagnum.c
P:/scripts/4_World/Classes/Recipes/Recipes/SawoffMosin.c
P:/scripts/4_World/Classes/Recipes/Recipes/SawoffMosinPainted.c
P:/scripts/4_World/Classes/Recipes/Recipes/SawoffShotgunIzh43.c
P:/scripts/4_World/Classes/Recipes/Recipes/SawWoodenLog.c
P:/scripts/4_World/Classes/Recipes/Recipes/SharpenBroom.c
P:/scripts/4_World/Classes/Recipes/Recipes/SharpenLongStick.c
P:/scripts/4_World/Classes/Recipes/Recipes/SharpenMelee.c
P:/scripts/4_World/Classes/Recipes/Recipes/SharpenStick.c
P:/scripts/4_World/Classes/Recipes/Recipes/SplitBroom.c
P:/scripts/4_World/Classes/Recipes/Recipes/SplitFirewood.c
P:/scripts/4_World/Classes/Recipes/Recipes/SplitLongWoodenStick.c
P:/scripts/4_World/Classes/Recipes/Recipes/SplitStones.c
P:/scripts/4_World/Classes/Recipes/Recipes/Test.c
P:/scripts/4_World/Classes/Recipes/Recipes/UpgradeTorchWithLard.c
P:/scripts/4_World/Classes/Recipes/Recipes/UpgradeTorchWithLiquidFuel.c
P:/scripts/4_World/Classes/Recipes/Recipes/WriteLetter.c