DayZ Scripts: HumanItemBehaviorCfg Class Reference
HumanItemBehaviorCfg Class Reference
#include <humanitems.h>
Private Member Functions
void SetIK (int pStance, int pMovement, bool pAim, bool pRArm, bool pLArm)
void SetIKStance (int pStance, bool pAim, bool pRArm, bool pLArm)
void SetIKMelee (int pHitType, bool pAim, bool pRArm, bool pLArm)
void SetIKAll (bool pAim, bool pRArm, bool pLArm)
void DayzPlayerItemBehaviorCfg ()
void SetIKTwoHanded ()
void SetIKPoleArms ()
void SetPistols ()
void SetFirearms ()
void SetEmptyHanded ()
void SetTwoHanded ()
void SetToolsOneHanded ()
void SetRestrained ()
void SetSurrender ()
void SetHeavyItems ()
void SetPoleArms ()
Private Attributes
int m_iType
int m_iStanceMask
combinations of STANCEMASK_
int m_StanceMovements [6]
int m_StanceRotation [6]
6 stances -> all has movement mask, STANCEIDX_ ... is index
int m_IKSettings [24]
int m_IKSettingsMelee [2]
[stance][movement] mask for ik
int m_iPerItemCameraUserData
[inpact type] mask for ik (0 - light/1 - heavy)
float m_fMoveHeadingFilterSpan
per item camera user data - can be obtained in runtime by DayZPlayer.GetPerItemCameraUD()
float m_fMoveHeadingSprintFilterSpan
default delay of alignment when moving
float m_fMoveHeadingProneFilterSpan
delay of alignment when sprintinh
float m_fMoveHeadingFilterSpeed
delay of alignment when moving in prone stance
float m_fMeleeEvadeHeadingFilterSpan
max speed of alignment when moving
float m_fMeleeEvadeHeadingFilterSpeed
delay of alignment when evading
bool m_bAttackLean
max speed of alignment when evading
bool m_bJumpAllowed
default false
private bool m_bPlaceholder
default true
Static Private Attributes
static int IKSETTING_AIMING = 0x1
bit mask of ik settings
static int IKSETTING_RHAND = 0x2
static int IKSETTING_LHAND = 0x4
Detailed Description
Definition at line 5 of file humanitems.h.
Member Function Documentation
DayzPlayerItemBehaviorCfg()
void DayzPlayerItemBehaviorCfg () inline private
per item camera user data to be uninitialized
rotational delay to camera direction in move only (filter)
Definition at line 106 of file DayZPlayerCfgBase.c.
References m_iStanceMask, m_StanceMovements, and m_StanceRotation.
SetEmptyHanded()
void SetEmptyHanded () inline private
Definition at line 198 of file DayZPlayerCfgBase.c.
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, DayZPlayerCameras::PERITEMUD_EMPTYHANDED, and SetIKAll().
SetFirearms()
void SetFirearms () inline private
Definition at line 183 of file DayZPlayerCfgBase.c.
References m_iType, SetIKMelee(), and SetIKStance().
SetHeavyItems()
void SetHeavyItems () inline private
Definition at line 274 of file DayZPlayerCfgBase.c.
References m_bAttackLean, m_bJumpAllowed, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, DayZPlayerCameras::PERITEMUD_TWOHANDED, and SetIKAll().
SetIK()
void SetIK (int pStance, int pMovement, bool pAim, bool pRArm, bool pLArm) inline private
Definition at line 44 of file humanitems.h.
References IKSETTING_AIMING, IKSETTING_LHAND, and IKSETTING_RHAND.
SetIKAll()
void SetIKAll (bool pAim, bool pRArm, bool pLArm) inline private
Definition at line 84 of file humanitems.h.
References IKSETTING_AIMING, IKSETTING_LHAND, IKSETTING_RHAND, m_IKSettings, and m_IKSettingsMelee.
Referenced by SetEmptyHanded(), SetHeavyItems(), SetRestrained(), and SetToolsOneHanded().
SetIKMelee()
void SetIKMelee (int pHitType, bool pAim, bool pRArm, bool pLArm) inline private
Definition at line 74 of file humanitems.h.
Referenced by SetFirearms(), SetIKPoleArms(), and SetIKTwoHanded().
SetIKPoleArms()
void SetIKPoleArms () inline private
Definition at line 153 of file DayZPlayerCfgBase.c.
References SetIKMelee(), and SetIKStance().
Referenced by SetPoleArms().
SetIKStance()
void SetIKStance (int pStance, bool pAim, bool pRArm, bool pLArm) inline private
Definition at line 59 of file humanitems.h.
References IKSETTING_AIMING, IKSETTING_LHAND, and IKSETTING_RHAND.
Referenced by SetFirearms(), SetIKPoleArms(), and SetIKTwoHanded().
SetIKTwoHanded()
void SetIKTwoHanded () inline private
Definition at line 140 of file DayZPlayerCfgBase.c.
References SetIKMelee(), and SetIKStance().
Referenced by SetTwoHanded().
SetPistols()
void SetPistols () inline private
Definition at line 166 of file DayZPlayerCfgBase.c.
SetPoleArms()
void SetPoleArms () inline private
Definition at line 288 of file DayZPlayerCfgBase.c.
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, DayZPlayerCameras::PERITEMUD_TWOHANDED, and SetIKPoleArms().
SetRestrained()
void SetRestrained () inline private
Definition at line 240 of file DayZPlayerCfgBase.c.
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, m_StanceRotation, DayZPlayerCameras::PERITEMUD_ONEHANDED, and SetIKAll().
SetSurrender()
void SetSurrender () inline private
Definition at line 258 of file DayZPlayerCfgBase.c.
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, m_StanceRotation, and DayZPlayerCameras::PERITEMUD_EMPTYHANDED.
SetToolsOneHanded()
void SetToolsOneHanded () inline private
Definition at line 226 of file DayZPlayerCfgBase.c.
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, DayZPlayerCameras::PERITEMUD_ONEHANDED, and SetIKAll().
SetTwoHanded()
void SetTwoHanded () inline private
Definition at line 212 of file DayZPlayerCfgBase.c.
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, DayZPlayerCameras::PERITEMUD_TWOHANDED, and SetIKTwoHanded().
Field Documentation
IKSETTING_AIMING
int IKSETTING_AIMING = 0x1 static private
bit mask of ik settings
Definition at line 11 of file humanitems.h.
Referenced by SetIK(), SetIKAll(), and SetIKStance().
IKSETTING_LHAND
int IKSETTING_LHAND = 0x4 static private
Definition at line 13 of file humanitems.h.
Referenced by SetIK(), SetIKAll(), and SetIKStance().
IKSETTING_RHAND
int IKSETTING_RHAND = 0x2 static private
Definition at line 12 of file humanitems.h.
Referenced by SetIK(), SetIKAll(), and SetIKStance().
m_bAttackLean
bool m_bAttackLean private
max speed of alignment when evading
per weapon lean forward
Definition at line 36 of file humanitems.h.
m_bJumpAllowed
bool m_bJumpAllowed private
default false
per weapon lean forward
Definition at line 39 of file humanitems.h.
Referenced by DayZPlayer::CanClimb(), and DayZPlayer::CanJump().
m_bPlaceholder
private bool m_bPlaceholder private
default true
Definition at line 41 of file humanitems.h.
m_fMeleeEvadeHeadingFilterSpan
float m_fMeleeEvadeHeadingFilterSpan private
max speed of alignment when moving
evade caps
Definition at line 31 of file humanitems.h.
m_fMeleeEvadeHeadingFilterSpeed
float m_fMeleeEvadeHeadingFilterSpeed private
delay of alignment when evading
Definition at line 32 of file humanitems.h.
m_fMoveHeadingFilterSpan
float m_fMoveHeadingFilterSpan private
per item camera user data - can be obtained in runtime by DayZPlayer.GetPerItemCameraUD()
movement caps
Definition at line 25 of file humanitems.h.
m_fMoveHeadingFilterSpeed
float m_fMoveHeadingFilterSpeed private
delay of alignment when moving in prone stance
Definition at line 28 of file humanitems.h.
m_fMoveHeadingProneFilterSpan
float m_fMoveHeadingProneFilterSpan private
delay of alignment when sprintinh
Definition at line 27 of file humanitems.h.
m_fMoveHeadingSprintFilterSpan
float m_fMoveHeadingSprintFilterSpan private
default delay of alignment when moving
Definition at line 26 of file humanitems.h.
m_IKSettings
int m_IKSettings[24] private
Definition at line 20 of file humanitems.h.
Referenced by SetIKAll(), and SetIKMelee().
m_IKSettingsMelee
int m_IKSettingsMelee[2] private
[stance][movement] mask for ik
Definition at line 21 of file humanitems.h.
Referenced by SetIKAll().
m_iPerItemCameraUserData
int m_iPerItemCameraUserData private
[inpact type] mask for ik (0 - light/1 - heavy)
Definition at line 22 of file humanitems.h.
m_iStanceMask
int m_iStanceMask private
combinations of STANCEMASK_
Definition at line 17 of file humanitems.h.
m_iType
int m_iType private
Definition at line 15 of file humanitems.h.
Referenced by DayZPlayerImplementThrowing::CanChangeThrowingStance(), DayZPlayerImplementThrowing::CanContinueThrowing(), and DayZPlayerImplementThrowing::HandleThrowing().
m_StanceMovements
int m_StanceMovements[6] private
Definition at line 18 of file humanitems.h.
m_StanceRotation
int m_StanceRotation[6] private
6 stances -> all has movement mask, STANCEIDX_ ... is index
Definition at line 19 of file humanitems.h.
Referenced by DayZPlayer::HeadingModel(), and ManBase::HeadingModel().
The documentation for this class was generated from the following files:
P:/scripts/3_Game/humanitems.h
P:/scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCfgBase.c