DayZ Scripts: WeaponParticlesBase Class Reference
WeaponParticlesBase Class Reference
Private Member Functions
void WeaponParticlesBase (ItemBase muzzle_owner, string config_OnFire_entry)
void OnActivate (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
void OnParticleCreated (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search, Particle p)
void OnDeactivate (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
void OnUpdate (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
bool CheckBoltStateCondition (ItemBase weapon)
bool CheckHealthCondition (int health_label)
bool CheckOverheatingCondition (float overheating_coef)
bool CheckRainCondition (float rain_coef)
int CheckParticleOverride (string ammoType)
vector CheckOrientationOverride (vector local_pos, ItemBase muzzle_owner)
Private Attributes
bool m_IlluminateWorld
bool m_IgnoreIfSuppressed
bool m_OnlyIfBoltIsOpen
int m_MuzzleIndex
int m_OverrideParticle
int m_OnlyWithinHealthLabelMin
int m_OnlyWithinHealthLabelMax
float m_OnlyWithinOverheatLimitsMin
float m_OnlyWithinOverheatLimitsMax
float m_OnlyWithinRainLimitsMin
float m_OnlyWithinRainLimitsMax
string m_OverrideDirectionPoint
string m_OnlyIfBulletIs
string m_OnlyIfWeaponIs
string m_OverridePoint
vector m_OverrideDirectionVector
vector m_PositionOffset
string m_Name
Detailed Description
Definition at line 7 of file WeaponParticles.c.
Constructor & Destructor Documentation
WeaponParticlesBase()
void WeaponParticlesBase (ItemBase muzzle_owner, string config_OnFire_entry) inline private
Definition at line 33 of file WeaponParticles.c.
References CGame::ConfigGetFloat(), CGame::ConfigGetFloatArray(), CGame::ConfigGetInt(), CGame::ConfigGetText(), CGame::ConfigGetVector(), ErrorEx, GetGame(), ParticleList::GetParticleIDByName(), m_IgnoreIfSuppressed, m_IlluminateWorld, m_MuzzleIndex, m_Name, m_OnlyIfBoltIsOpen, m_OnlyIfBulletIs, m_OnlyIfWeaponIs, m_OnlyWithinHealthLabelMax, m_OnlyWithinHealthLabelMin, m_OnlyWithinOverheatLimitsMax, m_OnlyWithinOverheatLimitsMin, m_OnlyWithinRainLimitsMax, m_OnlyWithinRainLimitsMin, m_OverrideDirectionPoint, m_OverrideDirectionVector, m_OverrideParticle, m_OverridePoint, m_PositionOffset, Vector(), and vector::Zero.
Member Function Documentation
CheckBoltStateCondition()
bool CheckBoltStateCondition (ItemBase weapon) inline private
Definition at line 255 of file WeaponParticles.c.
References WeaponStateBase::IsBoltOpen(), and m_OnlyIfBoltIsOpen.
Referenced by OnActivate().
CheckHealthCondition()
bool CheckHealthCondition (int health_label) inline private
Definition at line 268 of file WeaponParticles.c.
References m_OnlyWithinHealthLabelMax, and m_OnlyWithinHealthLabelMin.
Referenced by OnActivate().
CheckOrientationOverride()
vector CheckOrientationOverride (vector local_pos, ItemBase muzzle_owner) inline private
Definition at line 327 of file WeaponParticles.c.
References vector::Direction(), m_OverrideDirectionPoint, m_OverrideDirectionVector, Vector(), and vector::VectorToAngles().
Referenced by OnActivate().
CheckOverheatingCondition()
bool CheckOverheatingCondition (float overheating_coef) inline private
Definition at line 274 of file WeaponParticles.c.
References m_OnlyWithinOverheatLimitsMax, and m_OnlyWithinOverheatLimitsMin.
Referenced by OnActivate().
CheckParticleOverride()
int CheckParticleOverride (string ammoType) inline private
Definition at line 286 of file WeaponParticles.c.
References ErrorEx, GetGame(), ParticleList::GetParticleIDByName(), m_OverrideParticle, and particle_id.
Referenced by OnActivate().
CheckRainCondition()
bool CheckRainCondition (float rain_coef) inline private
Definition at line 280 of file WeaponParticles.c.
References m_OnlyWithinRainLimitsMax, and m_OnlyWithinRainLimitsMin.
Referenced by OnActivate().
OnActivate()
void OnActivate (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline private
Definition at line 165 of file WeaponParticles.c.
References CheckBoltStateCondition(), CheckHealthCondition(), CheckOrientationOverride(), CheckOverheatingCondition(), CheckParticleOverride(), CheckRainCondition(), ErrorEx, GetGame(), ParticleList::IsValidId(), PrtTest::m_GunParticlesState, m_IgnoreIfSuppressed, m_IlluminateWorld, m_MuzzleIndex, m_Name, m_OnlyIfBulletIs, m_OnlyIfWeaponIs, m_OverridePoint, m_PositionOffset, MuzzleFlashLight_1(), OnParticleCreated(), particle_id, ParticleManager(), Math::RandomInt(), and Vector().
OnDeactivate()
void OnDeactivate (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline private
Definition at line 238 of file WeaponParticles.c.
OnParticleCreated()
void OnParticleCreated (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search, Particle p) inline private
Definition at line 233 of file WeaponParticles.c.
Referenced by OnActivate().
OnUpdate()
void OnUpdate (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline private
Definition at line 243 of file WeaponParticles.c.
Field Documentation
m_IgnoreIfSuppressed
bool m_IgnoreIfSuppressed private
Definition at line 10 of file WeaponParticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_IlluminateWorld
bool m_IlluminateWorld private
Definition at line 9 of file WeaponParticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_MuzzleIndex
int m_MuzzleIndex private
Definition at line 12 of file WeaponParticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_Name
string m_Name private
Definition at line 27 of file WeaponParticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_OnlyIfBoltIsOpen
bool m_OnlyIfBoltIsOpen private
Definition at line 11 of file WeaponParticles.c.
Referenced by CheckBoltStateCondition(), and WeaponParticlesBase().
m_OnlyIfBulletIs
string m_OnlyIfBulletIs private
Definition at line 21 of file WeaponParticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_OnlyIfWeaponIs
string m_OnlyIfWeaponIs private
Definition at line 22 of file WeaponParticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_OnlyWithinHealthLabelMax
int m_OnlyWithinHealthLabelMax private
Definition at line 15 of file WeaponParticles.c.
Referenced by CheckHealthCondition(), and WeaponParticlesBase().
m_OnlyWithinHealthLabelMin
int m_OnlyWithinHealthLabelMin private
Definition at line 14 of file WeaponParticles.c.
Referenced by CheckHealthCondition(), and WeaponParticlesBase().
m_OnlyWithinOverheatLimitsMax
float m_OnlyWithinOverheatLimitsMax private
Definition at line 17 of file WeaponParticles.c.
Referenced by CheckOverheatingCondition(), and WeaponParticlesBase().
m_OnlyWithinOverheatLimitsMin
float m_OnlyWithinOverheatLimitsMin private
Definition at line 16 of file WeaponParticles.c.
Referenced by CheckOverheatingCondition(), and WeaponParticlesBase().
m_OnlyWithinRainLimitsMax
float m_OnlyWithinRainLimitsMax private
Definition at line 19 of file WeaponParticles.c.
Referenced by CheckRainCondition(), and WeaponParticlesBase().
m_OnlyWithinRainLimitsMin
float m_OnlyWithinRainLimitsMin private
Definition at line 18 of file WeaponParticles.c.
Referenced by CheckRainCondition(), and WeaponParticlesBase().
m_OverrideDirectionPoint
string m_OverrideDirectionPoint private
Definition at line 20 of file WeaponParticles.c.
Referenced by CheckOrientationOverride(), and WeaponParticlesBase().
m_OverrideDirectionVector
vector m_OverrideDirectionVector private
Definition at line 24 of file WeaponParticles.c.
Referenced by CheckOrientationOverride(), and WeaponParticlesBase().
m_OverrideParticle
int m_OverrideParticle private
Definition at line 13 of file WeaponParticles.c.
Referenced by CheckParticleOverride(), and WeaponParticlesBase().
m_OverridePoint
string m_OverridePoint private
Definition at line 23 of file WeaponParticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_PositionOffset
vector m_PositionOffset private
Definition at line 25 of file WeaponParticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/WeaponParticles.c