DayZ Scripts: PPEMatClassParameterCommandData Class Reference
PPEMatClassParameterCommandData Class Reference
Private Member Functions
void PPEMatClassParameterBool (int mat_idx, int parameter_idx, PPEClassBase parent)
override void InitDefaults ()
override void InitCuttent ()
override int GetParameterVarType ()
override void Update (float timeslice, out Param p_total, out bool setting_defaults, int order)
void PrepareLayerInfo (int layer, bool value, int operator)
override void SetParameterValueDefault (inout Param p_total)
No active requests for the mat. parameter value change, sets the value to DEFAULT.
void PPEMatClassParameterCommandData (int mat_idx, int parameter_idx, PPEClassBase parent)
int GetParameterVarType ()
void SetMaterialIndex (int value)
void SetParameterIndex (int value)
void SetParent (PPEClassBase parent)
void InsertRequestData (PPERequestParamDataBase request_data)
void Update (float timeslice, out Param p_total, out bool setting_defaults, int order)
void ModifyResultValues (inout Param result_values)
Modifies values to be used for setter methods later in the manager update. Currently used only on PPEMatClassParameterColor, TODO!!
void AddPriorityInfo (int priority)
Adds 'layers' to be iterated throug.
void RemovePriorityInfo (int priority)
Currently unused; layer info gets cleared every update.
void RegisterDefaults (Param p)
Adds name and default values from material registration, override on children to properly add for each type.
protected void InitDefaults ()
protected void InitCuttent ()
protected void SetParameterValueDefault (inout Param p_total)
Param GetDefaultValues ()
Careful, formating is such, that param1 is ALWAYS string, containing parameter name, should it be needed. Actual values follow.
Param GetCurrentValues ()
Careful, only actual values, WITHOUT string.
void DbgPrnt (string text)
void PPEMatClassParameterFloat (int mat_idx, int parameter_idx, PPEClassBase parent)
override void InitDefaults ()
override void InitCuttent ()
override int GetParameterVarType ()
override void Update (float timeslice, out Param p_total, out bool setting_defaults, int order)
void PrepareLayerInfo (int layer, float value, int operator)
override void SetParameterValueDefault (inout Param p_total)
No active requests for the mat. parameter value change, sets the value to DEFAULT (zero?)
void PPEMatClassParameterInt (int mat_idx, int parameter_idx, PPEClassBase parent)
override void InitDefaults ()
override void InitCuttent ()
override int GetParameterVarType ()
override void Update (float timeslice, out Param p_total, out bool setting_defaults, int order)
void PrepareLayerInfo (int layer, int value, int operator)
override void SetParameterValueDefault (inout Param p_total)
No active requests for the mat. parameter value change, sets the value to DEFAULT.
override int GetParameterVarType ()
override int GetParameterVarType ()
override int GetParameterVarType ()
Private Attributes
protected ref map< int, ref array< bool, int > > m_LayerInfo
protected PPETemplateDefBool m_Bool
protected bool m_ValueDefault
const int LAYER_INFO_VALUE = 0
const int LAYER_INFO_OPERATOR = 1
ref array< int > m_CommandLayersArray
protected int m_UpdatedCount
protected int m_MaterialIndex
protected int m_ParameterIndex
protected ref ActiveParameterRequestsMap m_RequestMap
protected PPEClassBase m_Parent
protected ref Param m_Defaults
protected ref Param m_CurrentValues
protected ref map< int, ref array< int > > m_Dependencies
protected ref map< int, ref array< float, int > > m_LayerInfo
protected PPETemplateDefFloat m_Float
protected float m_ValueDefault
protected float m_ValueMin
protected float m_ValueMax
protected ref map< int, ref array< int, int > > m_LayerInfo
protected PPETemplateDefInt m_Int
protected int m_ValueDefault
Constructor & Destructor Documentation
PPEMatClassParameterCommandData()
void PPEMatClassParameterCommandData (int mat_idx, int parameter_idx, PPEClassBase parent) inline private
References m_CommandLayersArray, m_MaterialIndex, m_ParameterIndex, m_Parent, m_RequestMap, and m_UpdatedCount.
Member Function Documentation
AddPriorityInfo()
void AddPriorityInfo (int priority) inline private
Adds 'layers' to be iterated throug.
References m_CommandLayersArray.
Referenced by PrepareLayerInfo(), PrepareLayerInfo(), and PrepareLayerInfo().
DbgPrnt()
void DbgPrnt (string text) inline private
GetCurrentValues()
Param GetCurrentValues () inline private
Careful, only actual values, WITHOUT string.
References m_CurrentValues.
Referenced by GetPostProcessCurrentValues(), PPEDOF::SetFinalParameterValue(), PPEExposureNative::SetFinalParameterValue(), PPEEyeAccomodationNative::SetFinalParameterValue(), PPELightIntensityParamsNative::SetFinalParameterValue(), and PPEClassBase::SetFinalParameterValue().
GetDefaultValues()
Param GetDefaultValues () inline private
Careful, formating is such, that param1 is ALWAYS string, containing parameter name, should it be needed. Actual values follow.
References m_Defaults.
Referenced by GetPostProcessDefaultValues().
GetParameterVarType() [1/7]
override int GetParameterVarType () inline private
Referenced by PPEClassBase::SetFinalParameterValue().
GetParameterVarType() [2/7]
int GetParameterVarType () inline private
GetParameterVarType() [3/7]
override int GetParameterVarType () inline private
GetParameterVarType() [4/7]
override int GetParameterVarType () inline private
GetParameterVarType() [5/7]
override int GetParameterVarType () inline private
GetParameterVarType() [6/7]
override int GetParameterVarType () inline private
GetParameterVarType() [7/7]
override int GetParameterVarType () inline private
InitCuttent() [1/4]
override void InitCuttent () inline private
References m_ValueDefault.
Referenced by RegisterDefaults().
InitCuttent() [2/4]
protected void InitCuttent () inline private
InitCuttent() [3/4]
override void InitCuttent () inline private
References m_ValueDefault.
InitCuttent() [4/4]
override void InitCuttent () inline private
References m_ValueDefault.
InitDefaults() [1/4]
override void InitDefaults () inline private
References Class::CastTo(), and m_ValueDefault.
Referenced by RegisterDefaults().
InitDefaults() [2/4]
protected void InitDefaults () inline private
InitDefaults() [3/4]
override void InitDefaults () inline private
References Class::CastTo(), m_Float, m_ValueDefault, m_ValueMax, and m_ValueMin.
InitDefaults() [4/4]
override void InitDefaults () inline private
References Class::CastTo(), and m_ValueDefault.
InsertRequestData()
void InsertRequestData (PPERequestParamDataBase request_data) inline private
References PPERequestParamDataBase::GetRequesterIDX(), and m_RequestMap.
Referenced by PPEClassBase::InsertParamValueData().
ModifyResultValues()
void ModifyResultValues (inout Param result_values) inline private
Modifies values to be used for setter methods later in the manager update. Currently used only on PPEMatClassParameterColor, TODO!!
PPEMatClassParameterBool()
void PPEMatClassParameterBool (int mat_idx, int parameter_idx, PPEClassBase parent) inline private
References m_LayerInfo.
PPEMatClassParameterFloat()
void PPEMatClassParameterFloat (int mat_idx, int parameter_idx, PPEClassBase parent) inline private
References m_LayerInfo.
PPEMatClassParameterInt()
void PPEMatClassParameterInt (int mat_idx, int parameter_idx, PPEClassBase parent) inline private
References m_LayerInfo.
PrepareLayerInfo() [1/3]
void PrepareLayerInfo (int layer, bool value, int operator) inline private
References AddPriorityInfo(), and m_LayerInfo.
Referenced by Update().
PrepareLayerInfo() [2/3]
void PrepareLayerInfo (int layer, float value, int operator) inline private
References AddPriorityInfo(), and m_LayerInfo.
PrepareLayerInfo() [3/3]
void PrepareLayerInfo (int layer, int value, int operator) inline private
References AddPriorityInfo(), and m_LayerInfo.
RegisterDefaults()
void RegisterDefaults (Param p) inline private
Adds name and default values from material registration, override on children to properly add for each type.
References InitCuttent(), InitDefaults(), and m_Defaults.
RemovePriorityInfo()
void RemovePriorityInfo (int priority) inline private
Currently unused; layer info gets cleared every update.
SetMaterialIndex()
void SetMaterialIndex (int value) inline private
References m_MaterialIndex.
SetParameterIndex()
void SetParameterIndex (int value) inline private
References m_ParameterIndex.
SetParameterValueDefault() [1/4]
override void SetParameterValueDefault (inout Param p_total) inline private
No active requests for the mat. parameter value change, sets the value to DEFAULT.
Referenced by Update().
SetParameterValueDefault() [2/4]
protected void SetParameterValueDefault (inout Param p_total) inline private
SetParameterValueDefault() [3/4]
override void SetParameterValueDefault (inout Param p_total) inline private
No active requests for the mat. parameter value change, sets the value to DEFAULT (zero?)
SetParameterValueDefault() [4/4]
override void SetParameterValueDefault (inout Param p_total) inline private
No active requests for the mat. parameter value change, sets the value to DEFAULT.
SetParent()
void SetParent (PPEClassBase parent) inline private
References m_Parent.
Update() [1/4]
override void Update (float timeslice, out Param p_total, out bool setting_defaults, int order) inline private
References Error(), m_LayerInfo, m_Parent, m_ValueDefault, Math::Max(), Math::Min(), PPERequestParamDataBool(), PrepareLayerInfo(), and SetParameterValueDefault().
Update() [2/4]
void Update (float timeslice, out Param p_total, out bool setting_defaults, int order) inline private
References Count, PPEManagerStatic::GetPPEManager(), and m_Dependencies.
Update() [3/4]
override void Update (float timeslice, out Param p_total, out bool setting_defaults, int order) inline private
References Math::Clamp(), Error(), Math::Lerp(), m_LayerInfo, m_Parent, m_ValueDefault, m_ValueDefault, m_ValueMax, m_ValueMax, m_ValueMin, Math::Max(), Math::Min(), PPERequestParamDataFloat(), PrepareLayerInfo(), and SetParameterValueDefault().
Update() [4/4]
override void Update (float timeslice, out Param p_total, out bool setting_defaults, int order) inline private
References Error(), m_LayerInfo, m_Parent, m_ValueDefault, Math::Max(), Math::Min(), PrepareLayerInfo(), and SetParameterValueDefault().
Field Documentation
LAYER_INFO_OPERATOR
const int LAYER_INFO_OPERATOR = 1 private
LAYER_INFO_VALUE
const int LAYER_INFO_VALUE = 0 private
m_Bool
protected PPETemplateDefBool m_Bool private
m_CommandLayersArray
ref array<int> m_CommandLayersArray private
Referenced by AddPriorityInfo(), and PPEMatClassParameterCommandData().
m_CurrentValues
protected ref Param m_CurrentValues private
Referenced by GetCurrentValues().
m_Defaults
protected ref Param m_Defaults private
Referenced by GetDefaultValues(), and RegisterDefaults().
m_Dependencies
protected ref map<int,ref array<int> > m_Dependencies private
Referenced by Update().
m_Float
protected PPETemplateDefFloat m_Float private
m_Int
protected PPETemplateDefInt m_Int private
m_LayerInfo [1/3]
protected ref map<int,ref array<bool,int> > m_LayerInfo private
m_LayerInfo [2/3]
protected ref map<int,ref array<float,int> > m_LayerInfo private
m_LayerInfo [3/3]
protected ref map<int,ref array<int,int> > m_LayerInfo private
m_MaterialIndex
protected int m_MaterialIndex private
Referenced by PPEMatClassParameterCommandData(), and SetMaterialIndex().
m_ParameterIndex
protected int m_ParameterIndex private
Referenced by PPEMatClassParameterCommandData(), and SetParameterIndex().
m_Parent
protected PPEClassBase m_Parent private
Referenced by PPEMatClassParameterCommandData(), and SetParent().
m_RequestMap
protected ref ActiveParameterRequestsMap m_RequestMap private
Referenced by InsertRequestData(), and PPEMatClassParameterCommandData().
m_UpdatedCount
protected int m_UpdatedCount private
Referenced by PPEMatClassParameterCommandData().
m_ValueDefault [1/3]
protected bool m_ValueDefault private
Referenced by Update().
m_ValueDefault [2/3]
protected float m_ValueDefault private
m_ValueDefault [3/3]
protected int m_ValueDefault private
m_ValueMax
protected float m_ValueMax private
Referenced by Update().
m_ValueMin
protected float m_ValueMin private
The documentation for this class was generated from the following files:
P:/scripts/3_Game/PPEManager/Materials/MatParameters/PPEMatClassParameterBool.c
P:/scripts/3_Game/PPEManager/Materials/MatParameters/PPEMatClassParameterCommandData.c
P:/scripts/3_Game/PPEManager/Materials/MatParameters/PPEMatClassParameterFloat.c
P:/scripts/3_Game/PPEManager/Materials/MatParameters/PPEMatClassParameterInt.c
P:/scripts/3_Game/PPEManager/Materials/MatParameters/PPEMatClassParameterResource.c
P:/scripts/3_Game/PPEManager/Materials/MatParameters/PPEMatClassParameterTexture.c
P:/scripts/3_Game/PPEManager/Materials/MatParameters/PPEMatClassParameterVector.c