DayZ Scripts: ArrowManagerPlayer Class Reference
ArrowManagerPlayer Class Reference
Private Member Functions
void ArrowManagerPlayer (PlayerBase player)
bool Save (ParamsWriteContext ctx)
bool Load (ParamsReadContext ctx)
Static Private Member Functions
static private void InitializeHash ()
static private void AddArrowTypeToHash (string ArrowType)
static private GetArrowTypeFromHash (int hash)
Static Private Attributes
static private ref map< int, typename > m_TypeHashTable
Constructor & Destructor Documentation
ArrowManagerPlayer()
void ArrowManagerPlayer (PlayerBase player) inline private
References InitializeHash(), and m_TypeHashTable.
Member Function Documentation
AddArrowTypeToHash()
static private void AddArrowTypeToHash (string ArrowType) inline static private
References string::Hash(), m_TypeHashTable, and string::ToType().
Referenced by InitializeHash().
GetArrowTypeFromHash()
static private GetArrowTypeFromHash (int hash) inline static private
References m_TypeHashTable.
Referenced by Load().
InitializeHash()
static private void InitializeHash () inline static private
References AddArrowTypeToHash(), and m_TypeHashTable.
Referenced by ArrowManagerPlayer().
Load()
bool Load (ParamsReadContext ctx) inline private
References vector::ArrayToVec(), ECE_DYNAMIC_PERSISTENCY, ECE_KEEPHEIGHT, ECE_LOCAL, GetArrowTypeFromHash(), GetGame(), ArrowManagerBase::m_Owner, and Serializer::Read().
Referenced by ManBase::OnStoreLoad().
Save()
bool Save (ParamsWriteContext ctx) inline private
References string::Hash(), ArrowManagerBase::m_Arrows, ArrowManagerBase::VERSION, and Serializer::Write().
Referenced by ManBase::OnStoreSave().
Field Documentation
m_TypeHashTable
private ref map<int,typename> m_TypeHashTable static private
Referenced by AddArrowTypeToHash(), ArrowManagerPlayer(), GetArrowTypeFromHash(), and InitializeHash().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/ArrowManager/ArrowManagerPlayer.c