DayZ Scripts: ActionLockAttachment Class Reference
ActionLockAttachment Class Reference
Private Member Functions
void ActionLockAttachment ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartAnimationLoop (ActionData action_data)
override void OnEnd (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Private Attributes
private const string LOCK_VERSION = "#widget_lock"
private const string UNLOCK_VERSION = "#widget_unlock"
private string m_Name = LOCK_VERSION
Constructor & Destructor Documentation
ActionLockAttachment()
void ActionLockAttachment () inline private
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References CarScript::GetCarDoorsState(), InventoryLocation::GetSlot(), InventorySlots::GetSlotName(), LOCK_VERSION, m_Name, and UNLOCK_VERSION.
CreateConditionComponents()
override void CreateConditionComponents () inline private
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::SMALL.
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
References LOCK_VERSION, m_Text, and UNLOCK_VERSION.
OnEnd()
override void OnEnd (ActionData action_data) inline private
References GetGame(), ActionData::m_MainItem, ActionData::m_Target, and CGame::RPCSingleParam().
OnEndAnimationLoop()
override void OnEndAnimationLoop (ActionData action_data) inline private
References GetGame(), ActionData::m_MainItem, ActionData::m_Target, and CGame::RPCSingleParam().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References ActionData::m_MainItem, and ActionData::m_Target.
OnStartAnimationLoop()
override void OnStartAnimationLoop (ActionData action_data) inline private
References GetGame(), ActionData::m_MainItem, ActionData::m_Target, and CGame::RPCSingleParam().
Field Documentation
LOCK_VERSION
private const string LOCK_VERSION = "#widget_lock" private
Referenced by ActionCondition(), and OnActionInfoUpdate().
m_Name
private string m_Name = LOCK_VERSION private
Referenced by ActionCondition().
UNLOCK_VERSION
private const string UNLOCK_VERSION = "#widget_unlock" private
Referenced by ActionCondition(), and OnActionInfoUpdate().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionLockAttachment.c