DayZ Scripts: DayZSpectator Class Reference
DayZSpectator Class Reference
Private Member Functions
void DayZSpectator ()
override void EOnFrame (IEntity other, float timeSlice)
Private Attributes
private float m_SpeedMultiplier = 1.0
private float m_SendUpdateAcc = 0.0
Constructor & Destructor Documentation
DayZSpectator()
void DayZSpectator () inline private
Member Function Documentation
EOnFrame()
override void EOnFrame (IEntity other, float timeSlice) inline private
References GetGame(), UAInputAPI::GetInputByID(), GetOrientation(), GetPosition, GetUApi(), UAInput::LocalValue(), m_SendUpdateAcc, m_SpeedMultiplier, Math::RAD2DEG, SetPosition(), CGame::SurfaceRoadY(), vector::Up, and CGame::UpdateSpectatorPosition().
Field Documentation
m_SendUpdateAcc
private float m_SendUpdateAcc = 0.0 private
Referenced by EOnFrame().
m_SpeedMultiplier
private float m_SpeedMultiplier = 1.0 private
Referenced by EOnFrame().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/DayZSpectator.c