DayZ Scripts: Pear Class Reference
Pear Class Reference
Private Member Functions
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsFruit ()
override void SetActions ()
override bool CanDecay ()
override void EEOnCECreate ()
Detailed Description
Definition at line 1 of file Pear.c.
Member Function Documentation
CanBeCooked()
override bool CanBeCooked () inline private
Definition at line 3 of file Pear.c.
CanBeCookedOnStick()
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file Pear.c.
CanDecay()
override bool CanDecay () inline private
Definition at line 28 of file Pear.c.
EEOnCECreate()
override void EEOnCECreate () inline private
Definition at line 33 of file Pear.c.
References ChangeFoodStage(), GetMaxHealth(), Math::RandomInt(), and SetHealth().
IsFruit()
override bool IsFruit () inline private
Definition at line 13 of file Pear.c.
SetActions()
override void SetActions () inline private
Definition at line 18 of file Pear.c.
References ActionForceFeed, and AddAction().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Pear.c