DayZ Scripts: TripodBase Class Reference
TripodBase Class Reference
Private Member Functions
override bool HasProxyParts ()
override bool CanDetachAttachment (EntityAI parent)
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
override void OnDebugSpawn ()
override void SetActions ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
Detailed Description
Definition at line 1 of file CookingStand.c.
Member Function Documentation
CanDetachAttachment()
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 8 of file Tripod.c.
CanSwapEntities()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination) inline private
Definition at line 21 of file Tripod.c.
References IsFireplace().
HasProxyParts()
override bool HasProxyParts () inline private
Definition at line 3 of file Tripod.c.
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 34 of file Tripod.c.
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 48 of file Tripod.c.
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 58 of file Tripod.c.
SetActions()
override void SetActions () inline private
Definition at line 40 of file Tripod.c.
References ActionAttach(), ActionDetach(), and AddAction().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/CookingStand.c
P:/scripts/4_World/Entities/ItemBase/Tripod.c