DayZ Scripts: GameplayEffectsData Class Reference
GameplayEffectsData Class Reference
Manages all bleeding indicators and their updates.
Private Member Functions
void GameplayEffectsDataBleeding (array< ref Widget > input, int type, int user_override=-1)
override void Init (array< ref Widget > input, int type, Widget layout_root, int user_override=-1)
override bool HasDefinedHandle ()
override bool DataInitialized ()
override void RegisterData (Param p)
void RegisterBleedingIndicatorInstance (int bit, float flow_modifier)
void SpawnBleedingIndicator (int source_ID, vector position)
int CalculateSeverity (float flow_modifier)
ImageWidget GetNextDropImage ()
void StopBleedingIndicator (int source_ID, bool instant=false)
void UpdateBleedingIndicators (float timeSlice)
void CleanupBleedingIndicators ()
override void Update (float timeSlice=0, Param p=null, int handle=-1)
override void UpdateVisibility (bool state)
override void ForceStop ()
stops and re-sets indicators and images even out of sequence. Should still be tied to the 'player' update, though!
void BuildProbabilityData (int severity, float frequency)
array< float > GetProbabilities (int severity)
void BuildPositioningData ()
vector GenerateSequenceRandomPosition ()
Private Attributes
protected bool m_Initialized
protected bool m_Visible
protected ref map< int, ref BleedingIndicator > m_RegisteredInstances
protected ref array< int > m_CleanupQueue
protected ref array< int > m_RunningIndicators
protected int m_LastDropIdx
protected int m_ImageWidgetCount
protected ref map< int, ref array< float > > m_ProbabilityMap
protected ref array< Widget > m_PositioningFramesArray
protected Widget m_BloodDropsFrame
protected int m_LastPositionFrameUsed
Detailed Description
Manages all bleeding indicators and their updates.
Member Function Documentation
BuildPositioningData()
void BuildPositioningData () inline private
Referenced by Init().
BuildProbabilityData()
void BuildProbabilityData (int severity, float frequency) inline private
References Math::Poisson(), and BleedingIndicationConstants::SEQUENCE_STEPS.
Referenced by Init().
CalculateSeverity()
int CalculateSeverity (float flow_modifier) inline private
References PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_LOW, PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, BleedingIndicationConstants::INDICATOR_SEVERITY_HIGH, BleedingIndicationConstants::INDICATOR_SEVERITY_LOW, and BleedingIndicationConstants::INDICATOR_SEVERITY_MEDIUM.
Referenced by RegisterBleedingIndicatorInstance().
CleanupBleedingIndicators()
void CleanupBleedingIndicators () inline private
Referenced by Update().
DataInitialized()
override bool DataInitialized () inline private
References m_Initialized.
Referenced by GameplayEffectWidgets_base::UpdateWidgets().
ForceStop()
override void ForceStop () inline private
stops and re-sets indicators and images even out of sequence. Should still be tied to the 'player' update, though!
References m_RunningIndicators, and Update().
Referenced by GameplayEffectWidgets_base::StopAllEffects().
GameplayEffectsDataBleeding()
void GameplayEffectsDataBleeding (array< ref Widget > input, int type, int user_override = -1) inline private
References m_Initialized.
GenerateSequenceRandomPosition()
vector GenerateSequenceRandomPosition () inline private
References Math::RandomFloatInclusive(), Math::RandomInt(), Vector(), x, y, and vector::Zero.
Referenced by SpawnBleedingIndicator().
GetNextDropImage()
ImageWidget GetNextDropImage () inline private
GetProbabilities()
array< float > GetProbabilities (int severity) inline private
References ErrorEx.
HasDefinedHandle()
override bool HasDefinedHandle () inline private
Referenced by GameplayEffectWidgets_base::UpdateVisibility(), and GameplayEffectWidgets_base::UpdateWidgets().
Init()
override void Init (array< ref Widget > input, int type, Widget layout_root, int user_override = -1) inline private
References BuildPositioningData(), BuildProbabilityData(), g_Game, BleedingIndicationConstants::INDICATOR_SEVERITY_HIGH, BleedingIndicationConstants::INDICATOR_SEVERITY_LOW, BleedingIndicationConstants::INDICATOR_SEVERITY_MEDIUM, m_Visible, BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_HIGH, BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_LOW, and BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_MEDIUM.
Referenced by GameplayEffectWidgets_base::CreateHandledClass().
RegisterBleedingIndicatorInstance()
void RegisterBleedingIndicatorInstance (int bit, float flow_modifier) inline private
References CalculateSeverity().
Referenced by RegisterData().
RegisterData()
override void RegisterData (Param p) inline private
References Class::CastTo(), ErrorEx, Debug::Log(), m_Initialized, and RegisterBleedingIndicatorInstance().
SpawnBleedingIndicator()
void SpawnBleedingIndicator (int source_ID, vector position) inline private
References GenerateSequenceRandomPosition().
Referenced by Update().
StopBleedingIndicator()
void StopBleedingIndicator (int source_ID, bool instant = false) inline private
Referenced by Update().
Update()
override void Update (float timeSlice = 0, Param p = null, int handle = -1) inline private
References Class::CastTo(), CleanupBleedingIndicators(), Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), m_Visible, GameplayEffectWidgets_base::RemoveActiveEffects(), SpawnBleedingIndicator(), StopBleedingIndicator(), and UpdateBleedingIndicators().
Referenced by GameplayEffectWidgets_base::UpdateWidgets().
UpdateBleedingIndicators()
void UpdateBleedingIndicators (float timeSlice) inline private
Referenced by Update().
UpdateVisibility()
override void UpdateVisibility (bool state) inline private
References g_Game, m_BloodDropsFrame, and m_Visible.
Referenced by GameplayEffectWidgets_base::UpdateVisibility().
Field Documentation
m_BloodDropsFrame
protected Widget m_BloodDropsFrame private
Referenced by UpdateVisibility().
m_CleanupQueue
protected ref array<int> m_CleanupQueue private
m_ImageWidgetCount
protected int m_ImageWidgetCount private
m_Initialized
protected bool m_Initialized private
Referenced by DataInitialized().
m_LastDropIdx
protected int m_LastDropIdx private
m_LastPositionFrameUsed
protected int m_LastPositionFrameUsed private
m_PositioningFramesArray
protected ref array<Widget> m_PositioningFramesArray private
m_ProbabilityMap
protected ref map<int,ref array<float> > m_ProbabilityMap private
m_RegisteredInstances
protected ref map<int,ref BleedingIndicator> m_RegisteredInstances private
m_RunningIndicators
protected ref array<int> m_RunningIndicators private
Referenced by ForceStop().
m_Visible
protected bool m_Visible private
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/mission/GameplayEffectWidgets/GEWidgetsMetaDataBleeding.c