DayZ Scripts: ActionMountBarbedWire Class Reference
ActionMountBarbedWire Class Reference
Private Member Functions
void ActionMountBarbedWire ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override string GetAdminLogMessage (ActionData action_data)
Private Attributes
float m_DamageAmount
string m_SlotName
Detailed Description
Definition at line 9 of file ActionMountBarbedWire.c.
Constructor & Destructor Documentation
ActionMountBarbedWire()
void ActionMountBarbedWire () inline private
Definition at line 14 of file ActionMountBarbedWire.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_DamageAmount, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file ActionMountBarbedWire.c.
References string::Length(), and m_SlotName.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 26 of file ActionMountBarbedWire.c.
References UAMaxDistances::BASEBUILDING, m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string GetAdminLogMessage (ActionData action_data) inline private
Definition at line 90 of file ActionMountBarbedWire.c.
References string::Format(), ActionData::m_Player, and ActionData::m_Target.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 57 of file ActionMountBarbedWire.c.
References ActionData::m_Player, m_SlotName, m_SpecialtyWeight, ActionData::m_Target, and string::ToLower().
Field Documentation
m_DamageAmount
float m_DamageAmount private
Definition at line 11 of file ActionMountBarbedWire.c.
Referenced by ActionMountBarbedWire().
m_SlotName
string m_SlotName private
Definition at line 12 of file ActionMountBarbedWire.c.
Referenced by ActionCondition(), and OnFinishProgressServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionMountBarbedWire.c