DayZ Scripts: P:/scripts/3_Game/BillboardSet.c File Reference
BillboardSet.c File Reference
Data Structures
class BillboardSetHandler
Functions
void BillboardSet (string path)
string GetTextureByType (string type)
protected void LoadConfig (string path)
Variables
class BillboardSetHandler string
class BillboardSetHandler m_TypeTextureMapping = new map<string, string>()
Function Documentation
BillboardSet()
void BillboardSet (string path)
References LoadConfig(), and path.
Referenced by BillboardSetHandler::GetTextureByType(), and BillboardSetHandler::LoadBillboardConfigs().
GetTextureByType()
string GetTextureByType (string type)
References m_TypeTextureMapping.
LoadConfig()
protected void LoadConfig (string path)
References CGame::ConfigGetChildName(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), ErrorEx, g_Game, GetGame(), m_TypeTextureMapping, and path.
Referenced by BillboardSet().
Variable Documentation
m_TypeTextureMapping
class BillboardSetHandler m_TypeTextureMapping = new map<string, string>()
Referenced by GetTextureByType(), and LoadConfig().
string
class BillboardSetHandler string