DayZ Scripts: ClosableContainer Class Reference
ClosableContainer Class Reference
Private Member Functions
void ContainerWithCargo (Container parent, int sort=-1)
override bool IsDisplayable ()
override bool IsEmpty ()
override bool IsItemActive ()
override bool CanEquip ()
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool IsItemWithQuantityActive ()
void LockCargo (bool value)
override void Open ()
override void Close ()
override bool IsOpened ()
override void UpdateInterval ()
override bool IsFirstContainerFocused ()
override bool IsLastContainerFocused ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
override void UnfocusAll ()
override bool SplitItem ()
override bool EquipItem ()
override bool TransferItem ()
override bool TransferItemToVicinity ()
override bool InspectItem ()
void SetEntity (EntityAI entity, int cargo_index=0, bool immedUpdate=true)
EntityAI GetEntity ()
override EntityAI GetFocusedContainerEntity ()
EntityAI GetItemPreviewItem (Widget w)
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever)
void DropReceived (Widget w, int x, int y)
void TakeIntoHands (notnull PlayerBase player, notnull EntityAI item)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override void DraggingOver (Widget w, int x, int y, Widget receiver)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void ContainerWithCargoAndAttachments (LayoutHolder parent, int sort=-1)
void ~ContainerWithCargoAndAttachments ()
void RecomputeContainers ()
void AttachmentAddedEx (EntityAI item, string slot, EntityAI parent, bool immedUpdate=true)
void AttachmentAdded (EntityAI item, string slot, EntityAI parent)
void AttachmentRemoved (EntityAI item, string slot, EntityAI parent)
override void UpdateInterval ()
override EntityAI GetFocusedContainerEntity ()
override void UnfocusAll ()
override bool IsLastIndex ()
override bool IsFirstContainerFocused ()
override bool IsLastContainerFocused ()
override void MoveGridCursor (int direction)
void SetEntity (EntityAI entity, bool immedUpdate=true)
void HideCargo ()
void ShowCargo ()
EntityAI GetEntity ()
ItemPreviewWidget GetItemPreviewWidgetDragOrDrop (Widget w)
EntityAI GetItemPreviewItem (Widget w)
Widget GetItemPreviewWidget (Widget w)
void MouseClick2 (Widget w, int x, int y, int button)
void DropReceived (Widget w, int x, int y, CargoContainer cargo)
void TakeAsAttachment (Widget w, Widget receiver)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromHeader2 (Widget w, int x, int y, Widget receiver)
void DoubleClick (Widget w, int x, int y, int button)
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo)
override void DraggingOver (Widget w, int x, int y, Widget receiver)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
Private Attributes
protected ref CargoContainer m_CargoGrid
protected int m_CargoIndex = -1
protected ref Attachments m_Atts
protected ref map< EntityAI, ref CargoContainer > m_AttachmentCargos
protected ref map< EntityAI, ref AttachmentsWrapper > m_AttachmentAttachmentsContainers
protected ref map< EntityAI, ref Attachments > m_AttachmentAttachments
protected ref array< int > m_AttachmentSlotsSorted
Detailed Description
Definition at line 1 of file ContainerWithCargo.c.
Constructor & Destructor Documentation
~ContainerWithCargoAndAttachments()
void ~ContainerWithCargoAndAttachments () inline private
Definition at line 16 of file ContainerWithCargoAndAttachments.c.
References m_Atts, m_Entity, and ScriptedWidgetEventHandler::Remove().
Member Function Documentation
AttachmentAdded()
void AttachmentAdded (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 139 of file ContainerWithCargoAndAttachments.c.
References AttachmentAddedEx().
AttachmentAddedEx()
void AttachmentAddedEx (EntityAI item, string slot, EntityAI parent, bool immedUpdate = true) inline private
Definition at line 77 of file ContainerWithCargoAndAttachments.c.
References InventorySlots::GetSlotIdFromString(), Inventory(), m_Parent, and RecomputeContainers().
Referenced by AttachmentAdded(), and SetEntity().
AttachmentRemoved()
void AttachmentRemoved (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 144 of file ContainerWithCargoAndAttachments.c.
References Container::Get(), InventorySlots::GetSlotIdFromString(), Inventory(), m_Parent, RecomputeContainers(), and LayoutHolder::Remove().
CanCombine()
override bool CanCombine () inline private
Definition at line 42 of file ContainerWithCargo.c.
CanCombineAmmo()
override bool CanCombineAmmo () inline private
Definition at line 47 of file ContainerWithCargo.c.
CanEquip()
override bool CanEquip () inline private
Definition at line 37 of file ContainerWithCargo.c.
Close()
override void Close () inline private
Definition at line 91 of file ContainerWithCargo.c.
References ItemManager::GetInstance(), m_Entity, m_Parent, OnHide(), and ItemManager::SetDefaultOpenState().
Referenced by Container::CloseButtonOnMouseButtonDown(), and AttachmentCategoriesContainer::MouseClick().
ContainerWithCargo()
void ContainerWithCargo (Container parent, int sort = -1) inline private
Definition at line 6 of file ContainerWithCargo.c.
References WidgetEventHandler::GetInstance(), m_Parent, and WidgetEventHandler::RegisterOnDraggingOver().
Referenced by AttachmentCategoriesRow::RefreshSlot().
ContainerWithCargoAndAttachments()
void ContainerWithCargoAndAttachments (LayoutHolder parent, int sort = -1) inline private
Definition at line 11 of file ContainerWithCargoAndAttachments.c.
References WidgetEventHandler::GetInstance(), and WidgetEventHandler::RegisterOnDraggingOver().
DoubleClick()
void DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 681 of file ContainerWithCargoAndAttachments.c.
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), SlotsIcon::IsReserved(), name, and string::Replace().
DraggingOver() [1/2]
override void DraggingOver (Widget w, int x, int y, Widget receiver) inline private
Definition at line 440 of file ContainerWithCargo.c.
References GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), GetItemPreviewItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_Entity, ColorManager::RED_COLOR, ColorManager::SetColor(), and ItemManager::ShowSourceDropzone().
Referenced by DraggingOverHeader().
DraggingOver() [2/2]
override void DraggingOver (Widget w, int x, int y, Widget receiver) inline private
Definition at line 827 of file ContainerWithCargoAndAttachments.c.
References DraggingOverHeader(), x, and y.
DraggingOverGrid() [1/2]
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever) inline private
Definition at line 250 of file ContainerWithCargo.c.
References GetGame(), CargoBase::GetHeight(), ItemManager::GetInstance(), CargoBase::GetItemCount(), GetItemPreviewItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), CargoBase::GetWidth(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), InventoryLocation::IsValid(), m_Entity, name, ColorManager::RED_COLOR, string::Replace(), InventoryLocation::SetCargoAuto(), ItemManager::ShowSourceDropzone(), x, and y.
DraggingOverGrid() [2/2]
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo) inline private
Definition at line 748 of file ContainerWithCargoAndAttachments.c.
References GetGame(), CargoBase::GetHeight(), ItemManager::GetInstance(), GetItemPreviewItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), CargoBase::GetWidth(), ColorManager::GREEN_COLOR, m_Entity, name, ColorManager::RED_COLOR, string::Replace(), x, and y.
DraggingOverHeader() [1/2]
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 435 of file ContainerWithCargo.c.
References DraggingOver(), x, and y.
Referenced by DraggingOver().
DraggingOverHeader() [2/2]
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 832 of file ContainerWithCargoAndAttachments.c.
References ItemBase::CanBeCombined(), GameInventory::CanSwapEntitiesEx(), Class::CastTo(), ColorManager::COMBINE_COLOR, SlotsIcon::GetEntity(), GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), GetItemPreviewItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), SlotsIcon::IsReserved(), m_Entity, ColorManager::RED_COLOR, ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and ColorManager::SWAP_COLOR.
DropReceived() [1/2]
void DropReceived (Widget w, int x, int y) inline private
Definition at line 339 of file ContainerWithCargo.c.
References ColorManager::BASE_COLOR, InventoryLocation::CompareLocationOnly(), FindAnyWidget(), InventoryLocation::GetFlip(), GetGame(), CargoBase::GetHeight(), ItemManager::GetInstance(), CargoBase::GetItemCount(), GetItemPreviewItem(), GetPlayer(), CargoBase::GetWidth(), ItemManager::HideDropzones(), InventoryLocation::IsValid(), m_Entity, Refresh(), Icon::Refresh(), InventoryLocation::SetCargoAuto(), ItemManager::SetIsDragging(), SplitItemUtils::TakeOrSplitToInventoryLocation(), x, and y.
DropReceived() [2/2]
void DropReceived (Widget w, int x, int y, CargoContainer cargo) inline private
Definition at line 472 of file ContainerWithCargoAndAttachments.c.
References ColorManager::BASE_COLOR, InventoryLocation::CompareLocationOnly(), InventoryLocation::GetFlip(), GetGame(), CargoBase::GetHeight(), ItemManager::GetInstance(), CargoBase::GetItemCount(), GetItemPreviewItem(), GetPlayer(), CargoBase::GetWidth(), ItemManager::HideDropzones(), InventoryLocation::IsValid(), m_Entity, Refresh(), Icon::Refresh(), InventoryLocation::SetCargoAuto(), ItemManager::SetIsDragging(), SplitItemUtils::TakeOrSplitToInventoryLocation(), x, and y.
EquipItem()
override bool EquipItem () inline private
Definition at line 175 of file ContainerWithCargo.c.
GetEntity() [1/2]
EntityAI GetEntity () inline private
Definition at line 220 of file ContainerWithCargo.c.
References m_Entity.
Referenced by OnDropReceivedFromHeader().
GetEntity() [2/2]
EntityAI GetEntity () inline private
Definition at line 356 of file ContainerWithCargoAndAttachments.c.
References m_Entity.
GetFocusedContainerEntity() [1/2]
override EntityAI GetFocusedContainerEntity () inline private
Definition at line 225 of file ContainerWithCargo.c.
References m_Entity.
GetFocusedContainerEntity() [2/2]
override EntityAI GetFocusedContainerEntity () inline private
Definition at line 210 of file ContainerWithCargoAndAttachments.c.
References m_Entity.
GetItemPreviewItem() [1/2]
EntityAI GetItemPreviewItem (Widget w) inline private
Definition at line 230 of file ContainerWithCargo.c.
References ItemPreviewWidget::GetItem(), name, and string::Replace().
Referenced by DraggingOver(), DraggingOverGrid(), DraggingOverHeader(), DropReceived(), OnDropReceivedFromHeader(), and TakeAsAttachment().
GetItemPreviewItem() [2/2]
EntityAI GetItemPreviewItem (Widget w) inline private
Definition at line 368 of file ContainerWithCargoAndAttachments.c.
References ItemPreviewWidget::GetItem(), name, and string::Replace().
GetItemPreviewWidget()
Widget GetItemPreviewWidget (Widget w) inline private
Definition at line 388 of file ContainerWithCargoAndAttachments.c.
References name, and string::Replace().
GetItemPreviewWidgetDragOrDrop()
ItemPreviewWidget GetItemPreviewWidgetDragOrDrop (Widget w) inline private
Definition at line 361 of file ContainerWithCargoAndAttachments.c.
References name, and string::Replace().
HideCargo()
void HideCargo () inline private
Definition at line 332 of file ContainerWithCargoAndAttachments.c.
Referenced by SetEntity(), and UpdateInterval().
InspectItem()
override bool InspectItem () inline private
Definition at line 190 of file ContainerWithCargo.c.
Referenced by MouseClick2().
IsDisplayable()
override bool IsDisplayable () inline private
Definition at line 20 of file ContainerWithCargo.c.
References m_Entity.
Referenced by Container::Open(), SetEntity(), AttachmentCategoriesContainer::UpdateInterval(), and Container::UpdateRadialIcon().
IsEmpty()
override bool IsEmpty () inline private
Definition at line 27 of file ContainerWithCargo.c.
IsFirstContainerFocused() [1/2]
override bool IsFirstContainerFocused () inline private
Definition at line 150 of file ContainerWithCargo.c.
IsFirstContainerFocused() [2/2]
override bool IsFirstContainerFocused () inline private
Definition at line 244 of file ContainerWithCargoAndAttachments.c.
IsItemActive()
override bool IsItemActive () inline private
Definition at line 32 of file ContainerWithCargo.c.
IsItemWithQuantityActive()
override bool IsItemWithQuantityActive () inline private
Definition at line 52 of file ContainerWithCargo.c.
IsLastContainerFocused() [1/2]
override bool IsLastContainerFocused () inline private
Definition at line 155 of file ContainerWithCargo.c.
IsLastContainerFocused() [2/2]
override bool IsLastContainerFocused () inline private
Definition at line 249 of file ContainerWithCargoAndAttachments.c.
References IsLastIndex().
IsLastIndex()
override bool IsLastIndex () inline private
Definition at line 239 of file ContainerWithCargoAndAttachments.c.
Referenced by IsLastContainerFocused().
IsOpened()
override bool IsOpened () inline private
Definition at line 108 of file ContainerWithCargo.c.
Referenced by PlayerContainer::HasEntityContainerVisible(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), AttachmentCategoriesContainer::MouseClick(), Container::OnShow(), UpdateInterval(), and Container::UpdateRadialIcon().
LockCargo()
void LockCargo (bool value) inline private
Definition at line 57 of file ContainerWithCargo.c.
References OnHide().
Referenced by SetEntity(), and UpdateInterval().
MouseClick2()
void MouseClick2 (Widget w, int x, int y, int button) inline private
Definition at line 404 of file ContainerWithCargoAndAttachments.c.
References g_Game, GetDayZGame(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), GetPlayer(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), InspectItem(), IsLeftCtrlDown(), SlotsIcon::IsReserved(), and ItemManager::SetWidgetDraggable().
MoveGridCursor()
override void MoveGridCursor (int direction) inline private
Definition at line 254 of file ContainerWithCargoAndAttachments.c.
References Inventory().
OnDropReceivedFromHeader() [1/2]
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 469 of file ContainerWithCargo.c.
References GetEntity(), GetGame(), GetItemPreviewItem(), GetPlayer(), m_Entity, and SplitItemUtils::TakeOrSplitToInventory().
OnDropReceivedFromHeader() [2/2]
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 671 of file ContainerWithCargoAndAttachments.c.
References TakeAsAttachment().
OnDropReceivedFromHeader2()
void OnDropReceivedFromHeader2 (Widget w, int x, int y, Widget receiver) inline private
Definition at line 676 of file ContainerWithCargoAndAttachments.c.
References TakeAsAttachment().
Open()
override void Open () inline private
Definition at line 74 of file ContainerWithCargo.c.
References ItemManager::GetInstance(), m_Entity, m_Parent, OnShow(), and ItemManager::SetDefaultOpenState().
Referenced by AttachmentCategoriesContainer::InitGhostSlots(), and AttachmentCategoriesContainer::MouseClick().
RecomputeContainers()
void RecomputeContainers () inline private
Definition at line 42 of file ContainerWithCargoAndAttachments.c.
References GameInventory::AttachmentCount(), Container::Get(), GameInventory::GetAttachmentFromIndex(), LayoutHolder::Insert(), and m_Entity.
Referenced by AttachmentAddedEx(), AttachmentRemoved(), and SetEntity().
SetDefaultFocus()
override void SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 160 of file ContainerWithCargo.c.
SetEntity() [1/2]
void SetEntity (EntityAI entity, bool immedUpdate = true) inline private
Definition at line 264 of file ContainerWithCargoAndAttachments.c.
References AttachmentAddedEx(), InventorySlots::GetSlotName(), HideCargo(), IsDisplayable(), m_Entity, m_Parent, name, RecomputeContainers(), ShowCargo(), and string::ToUpper().
SetEntity() [2/2]
void SetEntity (EntityAI entity, int cargo_index = 0, bool immedUpdate = true) inline private
Definition at line 195 of file ContainerWithCargo.c.
References LockCargo(), m_Entity, m_Parent, and Refresh().
ShowCargo()
void ShowCargo () inline private
Definition at line 344 of file ContainerWithCargoAndAttachments.c.
Referenced by SetEntity(), and UpdateInterval().
SplitItem()
override bool SplitItem () inline private
Definition at line 170 of file ContainerWithCargo.c.
TakeAsAttachment()
void TakeAsAttachment (Widget w, Widget receiver) inline private
Definition at line 561 of file ContainerWithCargoAndAttachments.c.
References GameInventory::CanSwapEntitiesEx(), Class::CastTo(), CombineItemsClient(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), GetItemPreviewItem(), CGame::GetPlayer(), GetPlayer(), InventoryLocation::GetSlot(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), ItemManager::HideDropzones(), SlotsIcon::IsReserved(), m_Entity, ItemManager::SetIsDragging(), and SplitItemUtils::TakeOrSplitToInventory().
Referenced by OnDropReceivedFromHeader(), and OnDropReceivedFromHeader2().
TakeIntoHands()
void TakeIntoHands (notnull PlayerBase player, notnull EntityAI item) inline private
Definition at line 416 of file ContainerWithCargo.c.
TransferItem()
override bool TransferItem () inline private
Definition at line 180 of file ContainerWithCargo.c.
TransferItemToVicinity()
override bool TransferItemToVicinity () inline private
Definition at line 185 of file ContainerWithCargo.c.
UnfocusAll() [1/2]
override void UnfocusAll () inline private
Definition at line 165 of file ContainerWithCargo.c.
UnfocusAll() [2/2]
override void UnfocusAll () inline private
Definition at line 215 of file ContainerWithCargoAndAttachments.c.
UpdateInterval() [1/2]
override void UpdateInterval () inline private
Definition at line 113 of file ContainerWithCargo.c.
References ItemManager::GetDraggedItem(), ItemManager::GetInstance(), IsOpened(), LockCargo(), and m_Entity.
UpdateInterval() [2/2]
override void UpdateInterval () inline private
Definition at line 176 of file ContainerWithCargoAndAttachments.c.
References ItemManager::GetDraggedItem(), ItemManager::GetInstance(), HideCargo(), IsOpened(), m_Entity, and ShowCargo().
Field Documentation
m_AttachmentAttachments
protected ref map<EntityAI, ref Attachments> m_AttachmentAttachments private
Definition at line 8 of file ContainerWithCargoAndAttachments.c.
m_AttachmentAttachmentsContainers
protected ref map<EntityAI, ref AttachmentsWrapper> m_AttachmentAttachmentsContainers private
Definition at line 7 of file ContainerWithCargoAndAttachments.c.
m_AttachmentCargos
protected ref map<EntityAI, ref CargoContainer> m_AttachmentCargos private
Definition at line 6 of file ContainerWithCargoAndAttachments.c.
m_AttachmentSlotsSorted
protected ref array<int> m_AttachmentSlotsSorted private
Definition at line 9 of file ContainerWithCargoAndAttachments.c.
m_Atts
protected ref Attachments m_Atts private
Definition at line 3 of file ContainerWithCargoAndAttachments.c.
Referenced by ~ContainerWithCargoAndAttachments().
m_CargoGrid
protected ref CargoContainer m_CargoGrid private
Definition at line 3 of file ContainerWithCargo.c.
m_CargoIndex
protected int m_CargoIndex = -1 private
Definition at line 4 of file ContainerWithCargo.c.
The documentation for this class was generated from the following files:
P:/scripts/5_Mission/GUI/InventoryNew/Inherited/ContainerWithCargo.c
P:/scripts/5_Mission/GUI/InventoryNew/Inherited/ContainerWithCargoAndAttachments.c