DayZ Scripts: DayZCreatureAnimScriptDebug Class Reference
DayZCreatureAnimScriptDebug Class Reference
Private Member Functions
proto native void SetCreature (DayZCreature creature)
proto native int GetVariableCount ()
proto native owned string GetVariableName (int index)
proto native int GetVariableType (int index)
proto native int GetVariableInt (int index)
proto native float GetVariableFloat (int index)
proto native bool GetVariableBool (int index)
proto native int SetVariableInt (int index, int value)
proto native float SetVariableFloat (int index, float value)
proto native bool SetVariableBool (int index, bool value)
proto native int GetCommandCount ()
proto native owned string GetCommandName (int index)
proto native int GetCommandID (int index)
proto native void ActivateCommand (int index, int userInt, float userFloat)
void OnAnimationEventsStart ()
void OnAnimationEvent (string evType, int userInt, string userString)
void OnAnimationPrediction (string predName)
void OnAnimationTag (string tagName)
Private Attributes
const int m_iMaxAnimEventsCount = 50
ref array< string > m_EventsFilter = new array<string>
ref array< ref DayZCreatureAnimScriptDebugAnimEventData > m_AnimEvents = new array<ref DayZCreatureAnimScriptDebugAnimEventData>
ref array< ref DayZCreatureAnimScriptDebugAnimPredictionData > m_AnimPredictions = new array<ref DayZCreatureAnimScriptDebugAnimPredictionData>
ref array< ref DayZCreatureAnimScriptDebugAnimTagData > m_AnimTags = new array<ref DayZCreatureAnimScriptDebugAnimTagData>
Member Function Documentation
ActivateCommand()
proto native void ActivateCommand (int index, int userInt, float userFloat) private
Referenced by ActivateCommand().
GetCommandCount()
proto native int GetCommandCount () private
Referenced by InitDebugObject(), and OnGUI_CommandsEdit().
GetCommandID()
proto native int GetCommandID (int index) private
Referenced by ActivateCommand(), and OnGUI_CommandsEdit().
GetCommandName()
proto native owned string GetCommandName (int index) private
Referenced by OnGUI_CommandsEdit().
GetVariableBool()
proto native bool GetVariableBool (int index) private
Referenced by GetStrValue().
GetVariableCount()
proto native int GetVariableCount () private
Referenced by InitDebugObject(), OnGUI_Variables(), and OnGUI_VariablesEdit().
GetVariableFloat()
proto native float GetVariableFloat (int index) private
Referenced by GetStrValue().
GetVariableInt()
proto native int GetVariableInt (int index) private
Referenced by GetStrValue().
GetVariableName()
proto native owned string GetVariableName (int index) private
Referenced by OnGUI_Variables(), and OnGUI_VariablesEdit().
GetVariableType()
proto native int GetVariableType (int index) private
Referenced by GetStrValue(), GetStrValueType(), and GetVariableType().
OnAnimationEvent()
void OnAnimationEvent (string evType, int userInt, string userString) inline private
References GetWorldTime(), m_AnimEvents, m_EventsFilter, and m_iMaxAnimEventsCount.
OnAnimationEventsStart()
void OnAnimationEventsStart () inline private
References m_AnimPredictions, and m_AnimTags.
OnAnimationPrediction()
void OnAnimationPrediction (string predName) inline private
References m_AnimPredictions.
OnAnimationTag()
void OnAnimationTag (string tagName) inline private
References m_AnimTags.
SetCreature()
proto native void SetCreature (DayZCreature creature) private
Referenced by InitDebugObject().
SetVariableBool()
proto native bool SetVariableBool (int index, bool value) private
Referenced by SetValueBool().
SetVariableFloat()
proto native float SetVariableFloat (int index, float value) private
Referenced by SetValueFloat().
SetVariableInt()
proto native int SetVariableInt (int index, int value) private
Referenced by SetValueInt().
Field Documentation
m_AnimEvents
ref array<ref DayZCreatureAnimScriptDebugAnimEventData> m_AnimEvents = new array<ref DayZCreatureAnimScriptDebugAnimEventData> private
Referenced by OnAnimationEvent(), and OnGUI_AnimEvents().
m_AnimPredictions
ref array<ref DayZCreatureAnimScriptDebugAnimPredictionData> m_AnimPredictions = new array<ref DayZCreatureAnimScriptDebugAnimPredictionData> private
Referenced by OnAnimationEventsStart(), OnAnimationPrediction(), and OnGUI_AnimEvents().
m_AnimTags
ref array<ref DayZCreatureAnimScriptDebugAnimTagData> m_AnimTags = new array<ref DayZCreatureAnimScriptDebugAnimTagData> private
Referenced by OnAnimationEventsStart(), OnAnimationTag(), and OnGUI_AnimEvents().
m_EventsFilter
ref array<string> m_EventsFilter = new array<string> private
Referenced by OnAnimationEvent(), and OnGUI_AnimEvents().
m_iMaxAnimEventsCount
const int m_iMaxAnimEventsCount = 50 private
Referenced by OnAnimationEvent().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Plugins/PluginBase/PluginDayZCreatureAIDebug.c