DayZ Scripts: ActionDetachFromTarget Class Reference
ActionDetachFromTarget Class Reference
Private Member Functions
override void CreateConditionComponents ()
void ActionDetachFromTarget ()
override GetInputType ()
override ActionData CreateActionData ()
int FindSlotIdToDetach (PlayerBase player, ActionTarget target, ItemBase item)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override Object GetDisplayInteractObject (PlayerBase player, ActionTarget target)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void Process (ActionData action_data)
Detailed Description
Definition at line 1 of file ActionDetachFromTarget.c.
Constructor & Destructor Documentation
ActionDetachFromTarget()
void ActionDetachFromTarget () inline private
Definition at line 10 of file ActionDetachFromTarget.c.
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 78 of file ActionDetachFromTarget.c.
References FindSlotIdToDetach(), GetGame(), and InventorySlots::INVALID.
CreateActionData()
override ActionData CreateActionData () inline private
Definition at line 20 of file ActionDetachFromTarget.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 4 of file ActionDetachFromTarget.c.
References m_ConditionItem, and m_ConditionTarget.
FindSlotIdToDetach()
int FindSlotIdToDetach (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 26 of file ActionDetachFromTarget.c.
References InventorySlots::GetSlotIdFromString(), and InventorySlots::INVALID.
Referenced by ActionCondition(), GetDisplayInteractObject(), and SetupAction().
GetDisplayInteractObject()
override Object GetDisplayInteractObject (PlayerBase player, ActionTarget target) inline private
Definition at line 85 of file ActionDetachFromTarget.c.
References FindSlotIdToDetach(), and InventorySlots::INVALID.
GetInputType()
override GetInputType () inline private
Definition at line 15 of file ActionDetachFromTarget.c.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
Definition at line 97 of file ActionDetachFromTarget.c.
References Process().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
Definition at line 102 of file ActionDetachFromTarget.c.
References GetGame(), and Process().
Process()
void Process (ActionData action_data) inline private
Definition at line 108 of file ActionDetachFromTarget.c.
References ClearInventoryReservationEx(), DetachActionData::m_AttSlot, ActionData::m_Player, and ActionData::m_Target.
Referenced by OnExecuteClient(), and OnExecuteServer().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 53 of file ActionDetachFromTarget.c.
References FindSlotIdToDetach(), GetGame(), InventorySlots::INVALID, and DetachActionData::m_AttSlot.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionDetachFromTarget.c