DayZ Scripts: P:/scripts/4_World/Classes/ContaminatedArea/SpookyAreaMisc.c File Reference
SpookyAreaMisc.c File Reference
Data Structures
class SpookyEventWind
class SpookyEventSteps
class SpookyEventBase
class SpookyPlayerStalker
this entity gets attached to each player while present in the spooky area
Functions
SpookyEventWind SpookyEventBase Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
override protected bool CanDo (PlayerBase player, TStringVectorMap surfaceTypes)
override protected void Do (PlayerBase player)
void SpookyTriggerEventsHandler (notnull PlayerBase player)
void ~SpookyTriggerEventsHandler ()
protected void RegisterEvents ()
void Update (float deltaTime)
protected void GatherSurfaces (notnull TStringVectorMap gatheredGurfaces)
protected bool SelectEvent ()
Variables
class SpookyEventBase m_SoundEvents
protected PlayerBase m_Player
protected float m_TimeAccu
protected const float CONSECUTIVE_EVENTS_COOLDOWN = 20
protected const float EVENT_CHECK_FREQUENCY = 2
protected const float FIRST_EVENT_CHECK_DELAY = 15
protected const float SURFACE_CHECK_POINT_DISTANCE = 2
protected float m_NextEventCheck = FIRST_EVENT_CHECK_DELAY
Function Documentation
CanDo()
override protected bool CanDo (PlayerBase player, TStringVectorMap surfaceTypes)
Do()
override protected void Do (PlayerBase player)
GatherSurfaces()
protected void GatherSurfaces (notnull TStringVectorMap gatheredGurfaces)
References COLOR_BLUE, Debug::DrawLine(), DiagMenu::GetBool(), GetGame(), m_Player, SURFACE_CHECK_POINT_DISTANCE, and CGame::SurfaceGetType3D().
Referenced by SelectEvent().
Init()
SpookyEventWind SpookyEventBase Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
RegisterEvents()
protected void RegisterEvents ()
References m_SoundEvents.
Referenced by SpookyTriggerEventsHandler().
SelectEvent()
protected bool SelectEvent ()
References GatherSurfaces(), DiagMenu::GetBool(), GetGame(), CGame::GetTime(), m_Player, m_SoundEvents, SpookyEventBase::Perform(), Print(), and Math::RandomIntInclusive().
Referenced by Update().
SpookyTriggerEventsHandler()
void SpookyTriggerEventsHandler (notnull PlayerBase player)
References m_Player, m_SoundEvents, and RegisterEvents().
Referenced by OnEnterClientEvent().
Update()
void Update (float deltaTime)
References CONSECUTIVE_EVENTS_COOLDOWN, EVENT_CHECK_FREQUENCY, m_NextEventCheck, m_TimeAccu, and SelectEvent().
~SpookyTriggerEventsHandler()
void ~SpookyTriggerEventsHandler ()
References m_SoundEvents.
Variable Documentation
CONSECUTIVE_EVENTS_COOLDOWN
protected const float CONSECUTIVE_EVENTS_COOLDOWN = 20
Referenced by Update().
EVENT_CHECK_FREQUENCY
protected const float EVENT_CHECK_FREQUENCY = 2
Referenced by Update().
FIRST_EVENT_CHECK_DELAY
protected const float FIRST_EVENT_CHECK_DELAY = 15
m_NextEventCheck
protected float m_NextEventCheck = FIRST_EVENT_CHECK_DELAY
Referenced by Update().
m_Player
protected PlayerBase m_Player
m_SoundEvents
class SpookyEventBase m_SoundEvents
Referenced by RegisterEvents(), SelectEvent(), SpookyTriggerEventsHandler(), and ~SpookyTriggerEventsHandler().
m_TimeAccu
protected float m_TimeAccu
Referenced by Update().
SURFACE_CHECK_POINT_DISTANCE
protected const float SURFACE_CHECK_POINT_DISTANCE = 2
Referenced by GatherSurfaces().