DayZ Scripts: PowerGeneratorStatic Class Reference
PowerGeneratorStatic Class Reference
Private Member Functions
void PowerGeneratorStatic ()
void ~PowerGeneratorStatic ()
void SetParent (Land_WarheadStorage_PowerStation parent)
override void OnWorkStart ()
override void OnWorkStop ()
override vector GetSmokeParticlePosition ()
override vector GetSmokeParticleOrientation ()
override bool HasSparkplug ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void EEOnAfterLoad ()
override bool CanReleaseAttachment (EntityAI attachment)
override bool IsTakeable ()
override bool IsActionTargetVisible ()
override bool DisableVicinityIcon ()
Static Private Member Functions
static void RegisterPersistentObject (PowerGeneratorStatic obj)
static void UnregisterPersistentObject (PowerGeneratorStatic obj)
static PowerGeneratorStatic GetClosestGenerator (vector position, float tolerance)
Private Attributes
protected Land_WarheadStorage_PowerStation m_Parent
protected int m_ParentID1
protected int m_ParentID2
protected int m_ParentID3
protected int m_ParentID4
Static Private Attributes
static protected ref set< PowerGeneratorStatic > m_PowerGenerators = new set<PowerGeneratorStatic>()
Constructor & Destructor Documentation
PowerGeneratorStatic()
void PowerGeneratorStatic () inline private
References RegisterPersistentObject().
~PowerGeneratorStatic()
void ~PowerGeneratorStatic () inline private
References UnregisterPersistentObject().
Member Function Documentation
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
CanPutIntoHands()
override bool CanPutIntoHands (EntityAI player) inline private
CanReleaseAttachment()
override bool CanReleaseAttachment (EntityAI attachment) inline private
DisableVicinityIcon()
override bool DisableVicinityIcon () inline private
EEOnAfterLoad()
override void EEOnAfterLoad () inline private
References GetGame(), Land_WarheadStorage_PowerStation::GetPowerGenerator(), m_ParentID1, m_ParentID2, m_ParentID3, and m_ParentID4.
GetClosestGenerator()
static PowerGeneratorStatic GetClosestGenerator (vector position, float tolerance) inline static private
References vector::DistanceSq(), m_PowerGenerators, and float::MAX.
Referenced by Land_WarheadStorage_PowerStation::LinkPowerGeneratorServer().
GetSmokeParticleOrientation()
override vector GetSmokeParticleOrientation () inline private
GetSmokeParticlePosition()
override vector GetSmokeParticlePosition () inline private
HasSparkplug()
override bool HasSparkplug () inline private
References InventorySlots::GetSlotIdFromString().
IsActionTargetVisible()
override bool IsActionTargetVisible () inline private
IsTakeable()
override bool IsTakeable () inline private
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References m_ParentID1, m_ParentID2, m_ParentID3, m_ParentID4, and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
References m_Parent, m_ParentID1, m_ParentID2, m_ParentID3, m_ParentID4, and Serializer::Write().
OnWorkStart()
override void OnWorkStart () inline private
References m_Parent, and Land_WarheadStorage_PowerStation::OnGeneratorStart().
OnWorkStop()
override void OnWorkStop () inline private
References m_Parent, and Land_WarheadStorage_PowerStation::OnGeneratorStop().
RegisterPersistentObject()
static void RegisterPersistentObject (PowerGeneratorStatic obj) inline static private
References m_PowerGenerators.
Referenced by PowerGeneratorStatic().
SetParent()
void SetParent (Land_WarheadStorage_PowerStation parent) inline private
References m_Parent.
Referenced by Land_WarheadStorage_PowerStation::LinkPowerGeneratorServer().
UnregisterPersistentObject()
static void UnregisterPersistentObject (PowerGeneratorStatic obj) inline static private
References m_PowerGenerators.
Referenced by ~PowerGeneratorStatic().
Field Documentation
m_Parent
protected Land_WarheadStorage_PowerStation m_Parent private
Referenced by OnStoreSave(), OnWorkStart(), OnWorkStop(), and SetParent().
m_ParentID1
protected int m_ParentID1 private
Referenced by EEOnAfterLoad(), OnStoreLoad(), and OnStoreSave().
m_ParentID2
protected int m_ParentID2 private
Referenced by EEOnAfterLoad(), OnStoreLoad(), and OnStoreSave().
m_ParentID3
protected int m_ParentID3 private
Referenced by EEOnAfterLoad(), OnStoreLoad(), and OnStoreSave().
m_ParentID4
protected int m_ParentID4 private
Referenced by EEOnAfterLoad(), OnStoreLoad(), and OnStoreSave().
m_PowerGenerators
protected ref set<PowerGeneratorStatic> m_PowerGenerators = new set<PowerGeneratorStatic>() static private
Referenced by GetClosestGenerator(), RegisterPersistentObject(), and UnregisterPersistentObject().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Building/Underground/PowerGeneratorStatic.c