DayZ Scripts: WorldLighting Class Reference
WorldLighting Class Reference
Private Member Functions
void WorldLighting ()
void ~WorldLighting ()
void SetGlobalLighting (int lightingID)
Private Attributes
string lighting_default = "dz\\data\\lighting\\lighting_default.txt"
string lighting_darknight = "dz\\data\\lighting\\lighting_darknight.txt"
Constructor & Destructor Documentation
WorldLighting()
void WorldLighting () inline private
~WorldLighting()
void ~WorldLighting () inline private
Member Function Documentation
SetGlobalLighting()
void SetGlobalLighting (int lightingID) inline private
References GetGame(), CGame::GetWorld(), lighting_darknight, lighting_default, and World::LoadNewLightingCfg().
Referenced by ManBase::UpdateLighting().
Field Documentation
lighting_darknight
string lighting_darknight = "dz\\data\\lighting\\lighting_darknight.txt" private
Referenced by SetGlobalLighting().
lighting_default
string lighting_default = "dz\\data\\lighting\\lighting_default.txt" private
Referenced by SetGlobalLighting().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/WorldLighting.c