DayZ Scripts: ModInfo Class Reference
ModInfo Class Reference
Private Member Functions
proto owned string GetName ()
proto owned string GetPicture ()
proto owned string GetLogo ()
proto owned string GetLogoSmall ()
proto owned string GetLogoOver ()
proto owned string GetTooltip ()
proto owned string GetOverview ()
proto owned string GetAction ()
proto owned string GetAuthor ()
proto owned string GetVersion ()
proto bool GetDefault ()
proto bool GetIsDLC ()
proto bool GetIsOwned ()
proto void GoToStore ()
Static Private Attributes
static const string DEFAULT_PICTURE = "Gui/textures/modlogo_default_co.edds"
static const string DEFAULT_LOGO = "Gui/textures/modlogo_default_co.edds"
static const string DEFAULT_LOGO_SMALL = "Gui/textures/modlogo_default_co.edds"
static const string DEFAULT_LOGO_OVER = "Gui/textures/modlogo_default_hover_co.edds"
static const string DEFAULT_OVERVIEW = ""
Member Function Documentation
GetAction()
proto owned string GetAction () private
GetAuthor()
proto owned string GetAuthor () private
GetDefault()
proto bool GetDefault () private
GetIsDLC()
proto bool GetIsDLC () private
Referenced by UIScriptedMenu::FilterDlcs(), and UIScriptedMenu::FilterDLCs().
GetIsOwned()
proto bool GetIsOwned () private
GetLogo()
proto owned string GetLogo () private
GetLogoOver()
proto owned string GetLogoOver () private
GetLogoSmall()
proto owned string GetLogoSmall () private
GetName()
proto owned string GetName () private
Referenced by UIScriptedMenu::FilterDlcs(), and UIScriptedMenu::FilterDLCs().
GetOverview()
proto owned string GetOverview () private
GetPicture()
proto owned string GetPicture () private
GetTooltip()
proto owned string GetTooltip () private
Referenced by ScriptedWidgetEventHandler::ShowTooltip().
GetVersion()
proto owned string GetVersion () private
GoToStore()
proto void GoToStore () private
Field Documentation
DEFAULT_LOGO
const string DEFAULT_LOGO = "Gui/textures/modlogo_default_co.edds" static private
Referenced by ScriptedWidgetEventHandler::LoadData().
DEFAULT_LOGO_OVER
const string DEFAULT_LOGO_OVER = "Gui/textures/modlogo_default_hover_co.edds" static private
Referenced by ScriptedWidgetEventHandler::LoadData().
DEFAULT_LOGO_SMALL
const string DEFAULT_LOGO_SMALL = "Gui/textures/modlogo_default_co.edds" static private
Referenced by ScriptedWidgetEventHandler::LoadData().
DEFAULT_OVERVIEW
const string DEFAULT_OVERVIEW = "" static private
Referenced by ScriptedWidgetEventHandler::LoadData().
DEFAULT_PICTURE
const string DEFAULT_PICTURE = "Gui/textures/modlogo_default_co.edds" static private
Referenced by ScriptedWidgetEventHandler::LoadData().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/ModInfo.c