DayZ Scripts: Widget UI system
Widget UI system
Data Structures
class WorkspaceWidget
class Widget
class TextWidget
class UIWidget
class EditBoxWidget
class SimpleProgressBarWidget
class BaseListboxWidget
class SimpleListboxWidget
class SpacerWidget
class ScriptedWidgetEventHandler
map: item x vector(index, width, height)
Typedefs
typedef TypeID WidgetType
typedef TypeID EventType
Enumerations
enum WidgetFlags {
SOURCEALPHA , BLEND , ADDITIVE , VISIBLE ,
NOWRAP , CENTER , VCENTER , HEXACTPOS ,
VEXACTPOS , EXACTPOS , HEXACTSIZE , VEXACTSIZE ,
EXACTSIZE , NOFILTER , RALIGN , STRETCH ,
FLIPU , FLIPV , CUSTOMUV , IGNOREPOINTER ,
DISABLED , NOFOCUS , CLIPCHILDREN , RENDER_ALWAYS ,
NOCLEAR , DRAGGABLE
}
enum WidgetAlignment
enum VideoCommand {
PLAY , STOP , REWIND , POSITION ,
REPEAT , ISPLAYING , KILL
}
Legacy, do not use.
enum VideoState {
NONE , PLAYING , PAUSED , STOPPED ,
FINISHED
}
enum VideoCallback {
ON_PLAY , ON_PAUSE , ON_STOP , ON_END ,
ON_LOAD , ON_SEEK , ON_BUFFERING_START , ON_BUFFERING_END
}
enum ControlID {
CID_NONE = 0 , CID_SELECT = 1 , CID_BACK , CID_LEFT ,
CID_RIGHT , CID_UP , CID_DOWN , CID_MENU ,
CID_DRAG , CID_TABLEFT , CID_TABRIGHT , CID_RADIALMENU ,
CID_COUNT
}
Functions
static proto string TranslateString (string stringId)
static proto void SetLV (float lv)
Set global LV of widgets, value between [-15, 0], default: 0, lower value is less bright.
static proto void SetTextLV (float lv)
Set global LV of the text in widgets, value between [-15, 0], default: 0, lower value is less bright.
static proto void SetObjectLighting (float lighting)
Set global lighting of objects in widgets, value between [0, 1], default: 1, lower value is less bright.
proto native owned string GetName ()
proto native void SetName (string name)
proto native owned string GetTypeName ()
proto native WidgetType GetTypeID ()
proto native void Show (bool show, bool immedUpdate=true)
proto native void Enable (bool enable)
proto native int GetFlags ()
proto native int SetFlags (int flags, bool immedUpdate=true)
proto native int GetSort ()
proto native void SetSort (int sort, bool immedUpdate=true)
proto native int ClearFlags (int flags, bool immedUpdate=true)
proto native bool IsControlClass ()
proto native owned string GetStyleName ()
proto void GetUserData (out Class data)
proto native void SetUserData (Class data)
proto native int GetUserID ()
proto native void SetUserID (int id)
proto native bool IsVisible ()
proto native bool IsVisibleHierarchy ()
proto native void SetPos (float x, float y, bool immedUpdate=true)
proto native void SetSize (float w, float h, bool immedUpdate=true)
proto native void SetScreenPos (float x, float y, bool immedUpdate=true)
proto native void SetScreenSize (float w, float h, bool immedUpdate=true)
proto native void SetColor (int color)
proto native int GetColor ()
proto native void SetRotation (float roll, float pitch, float yaw, bool immedUpdate=true)
proto native vector GetRotation ()
returns rotation of widget in order roll, pitch, yaw
proto native void SetAlpha (float alpha)
proto native float GetAlpha ()
proto void GetPos (out float x, out float y)
proto void GetSize (out float width, out float height)
proto void GetScreenPos (out float x, out float y)
proto void GetScreenSize (out float width, out float height)
proto native void SetTransform (vector mat[4], bool immedUpdate=true)
proto native Widget GetParent ()
Get parent of the Effect.
proto native Widget GetChildren ()
proto native Widget GetSibling ()
proto native void AddChild (Widget child, bool immedUpdate=true)
proto native void RemoveChild (Widget child)
proto native volatile void Update ()
proto void GetScript (out Class data)
proto native Widget FindWidget (string pathname)
proto native Widget FindAnyWidget (string pathname)
proto native Widget FindAnyWidgetById (int user_id)
proto native void SetHandler (ScriptedWidgetEventHandler eventHandler)
proto native void Unlink ()
proto native external Widget CreateWidget (WidgetType type, int left, int top, int width, int height, WidgetFlags flags, int color, int sort, Widget parentWidget=NULL)
Create widgets by WidgetType.
proto native external Widget CreateWidgets (string layout, Widget parentWidget=NULL, bool immedUpdate=true)
Create widgets from *.layout file.
proto native Widget GetWidgetUnderCursor ()
proto native Widget CancelWidgetDragging ()
proto native Widget GetDragWidget ()
proto native void ReportMouse (int mousex, int mousey, Widget rootWidget)
proto native void SetTextSpacing (int horiz, int vert)
proto native void SetTextExactSize (int size)
set text exact size. Exact Text flag must be enabled. 0 equals original size.
proto native void SetTextOffset (int left, int top)
proto native void SetText (string text, bool immedUpdate=true)
proto native void SetOutline (int outlineSize, int argb=0xFF000000)
proto native int GetOutlineSize ()
proto native int GetOutlineColor ()
proto native void SetShadow (int shadowSize, int shadowARGB=0xFF000000, float shadowOpacity=1, float shadowOffsetX=0, float shadowOffsetY=0)
proto native int GetShadowSize ()
proto native int GetShadowColor ()
proto native float GetShadowOpacity ()
proto void GetShadowOffset (out float sx, out float sy)
proto native void SetItalic (bool italic)
proto native bool GetItalic ()
proto native void SetBold (bool bold)
proto native bool GetBold ()
proto void GetTextSize (out int sx, out int sy)
Returns text size in pixels.
proto void SetTextFormat (string text, void param1=NULL, void param2=NULL, void param3=NULL, void param4=NULL, void param5=NULL, void param6=NULL, void param7=NULL, void param8=NULL, void param9=NULL)
proto native float GetTextProportion ()
Get text proportion - ratio between button height and button text height in interval <0,1>
proto native void SetTextProportion (float val)
Set text proportion - ratio between button height and button text height in interval <0,1>
proto native float SetLineBreakingOverride (int mode)
proto native float GetContentHeight ()
proto native float GetContentOffset ()
proto native void SetContentOffset (float offset, bool snapToLine=false)
proto native void ElideText (int line, float maxWidth, string str)
proto native int GetNumLines ()
proto native void SetLinesVisibility (int lineFrom, int lineTo, bool visible)
proto native float GetLineWidth (int line)
proto native void SetRefresh (int period, int offset)
when period > 1 then every n-th frame will be rendered. Offset is initial counter.
proto native void SetResolutionScale (float xscale, float ycale)
proto native bool LoadImageFile (int num, string name, bool noCache=false)
proto native void SetImageTexture (int image, RTTextureWidget texture)
proto void GetImageSize (int image, out int sx, out int sy)
returns size of image
proto native bool SetImage (int num)
proto native int GetImage ()
Returns active image.
proto native void SetUV (float uv[4][2])
proto native bool LoadMaskTexture (string resource)
proto native float GetMaskProgress ()
proto native void SetMaskProgress (float value)
proto native float GetMaskTransitionWidth ()
proto native void SetMaskTransitionWidth (float value)
proto native int GetLinesCount ()
proto native int GetCarriageLine ()
proto native int GetCarriagePos ()
proto void GetText (out string text)
proto native void SetLine (int line, string text)
proto void GetLine (int line, out string text)
proto native void SetTextColor (int color)
proto native void SetTextOutline (int outlineSize, int argb=0xFF000000)
proto native int GetTextOutlineSize ()
proto native int GetTextOutlineColor ()
proto native void SetTextShadow (int shadowSize, int shadowARGB=0xFF000000, float shadowOpacity=1.0, float shadowOffsetX=0.0, float shadowOffsetY=0.0)
proto native int GetTextShadowSize ()
proto native int GetTextShadowColor ()
proto native float GetTextShadowOpacity ()
proto native float GetTextShadowOffsetX ()
proto native float GetTextShadowOffsetY ()
proto native void SetTextItalic (bool italic)
proto native bool GetTextItalic ()
proto native void SetTextBold (bool bold)
proto native bool GetTextBold ()
proto native void DrawLine (float x1, float y1, float x2, float y2, float width, int color)
proto native void Clear ()
proto string GetText ()
proto native void SetText (string str)
proto native void SetHideText (bool hide)
proto native void SetMinMax (float minimum, float maximum)
proto native float GetMin ()
proto native float GetMax ()
proto native float GetCurrent ()
proto native void SetCurrent (float curr)
proto native float GetStep ()
proto native void SetStep (float step)
proto native bool GetState ()
proto native bool SetState (bool state)
proto void GetText (out string text)
proto native void SetTextOffset (float xoffset, float yoffset)
proto native void SetTextHorizontalAlignment (int align)
proto native void SetTextVerticalAlignment (int align)
proto native float GetTextProportion ()
Get text proportion - ratio between button height and button text height in interval <0,1>
proto native void SetTextProportion (float val)
Set text proportion - ratio between button height and button text height in interval <0,1>
proto native int AddItem (string item)
proto native void ClearAll ()
proto native void SetItem (int item, string value)
proto native void RemoveItem (int item)
proto native int GetNumItems ()
proto native int SetCurrentItem (int n)
proto native int GetCurrentItem ()
proto native bool IsChecked ()
proto native void SetChecked (bool checked)
proto native void ClearItems ()
proto native void SelectRow (int row)
proto native int GetSelectedRow ()
proto native void RemoveRow (int row)
proto native void EnsureVisible (int row)
proto native int AddItem (string text, Class userData, int column, int row=-1)
Insert new Row, if row = -1, new Row is inserted at the end otherwise at row index.
proto native void SetItem (int position, string text, Class userData, int column)
proto bool GetItemText (int row, int column, out string text)
Get item.
proto void GetItemData (int row, int column, out Class data)
proto native void SetItemColor (int row, int column, int color)
proto native void AddChildAfter (Widget child, Widget after, bool immedUpdate=true)
class SpacerBaseWidget extends UIWidget GetContentAlignmentH ()
proto native void AddChildAfter (Widget child, Widget after, bool immedUpdate=true)
proto native void SetContentAlignmentH (WidgetAlignment alignment)
proto native WidgetAlignment GetContentAlignmentV ()
proto native void SetContentAlignmentV (WidgetAlignment alignment)
proto native bool IsScrollbarVisible ()
proto native float GetContentWidth ()
proto native float GetContentHeight ()
proto native float GetHScrollPos ()
proto native float GetHScrollPos01 ()
proto native bool HScrollStep (int steps)
proto native void HScrollToPos (float pos)
proto native void HScrollToPos01 (float pos01)
proto native void HScrollToWidget (Widget child)
proto native float GetVScrollPos ()
proto native float GetVScrollPos01 ()
proto native bool VScrollStep (int steps)
proto native void VScrollToPos (float pos)
proto native void VScrollToPos01 (float pos01)
proto native void VScrollToWidget (Widget child)
proto native bool Load (string name, bool looping=false, int startTime=0)
Load a video file.
proto native void Unload ()
Unload the video, freeing up all resources.
proto native bool Play ()
Starts video playback.
proto native bool Pause ()
Pauses video playback.
proto native bool Stop ()
Stop video playback (cancels everything and sets it back at time 0)
proto native bool SetTime (int time, bool preload)
Set the desired time for the video (preload decides whether it will already load the next frames too)
proto native int GetTime ()
Get the current time of the video.
proto native int GetTotalTime ()
Get the total time of the video.
proto native void SetLooping (bool looping)
Set whether the video should loop.
proto native bool IsLooping ()
Whether looping is enabled.
proto native bool IsPlaying ()
QoL direct method to check for playing state (buffering while playing will still return true)
proto native VideoState GetState ()
Get the current state of the video.
proto native void DisableSubtitles (bool disable)
Enable/Disable subtitles.
proto native bool IsSubtitlesDisabled ()
Check if subtitles are disabled (enabled by default if available, so it will return false even if there are none)
proto void SetCallback (VideoCallback cb, func fn)
Set a callback for a certain video event.
int Play (VideoCommand cmd)
Legacy, preferably not used, left for backwards compat.
bool LoadVideo (string name, int soundScene)
Legacy, preferably not used, left for backwards compat.
proto native void SetGUIWidget (IEntity ent, int index, RTTextureWidget w)
bool OnClick (Widget w, int x, int y, int button)
bool OnModalResult (Widget w, int x, int y, int code, int result)
bool OnDoubleClick (Widget w, int x, int y, int button)
bool OnSelect (Widget w, int x, int y)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnFocus (Widget w, int x, int y)
bool OnFocusLost (Widget w, int x, int y)
bool OnMouseEnter (Widget w, int x, int y)
bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
bool OnMouseWheel (Widget w, int x, int y, int wheel)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnMouseButtonUp (Widget w, int x, int y, int button)
bool OnController (Widget w, int control, int value)
control is one of ControlID
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnKeyUp (Widget w, int x, int y, int key)
bool OnKeyPress (Widget w, int x, int y, int key)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnDrag (Widget w, int x, int y)
bool OnDragging (Widget w, int x, int y, Widget reciever)
bool OnDraggingOver (Widget w, int x, int y, Widget reciever)
bool OnDrop (Widget w, int x, int y, Widget reciever)
bool OnDropReceived (Widget w, int x, int y, Widget reciever)
bool OnResize (Widget w, int x, int y)
bool OnChildAdd (Widget w, Widget child)
bool OnChildRemove (Widget w, Widget child)
bool OnUpdate (Widget w)
bool OnEvent (EventType eventType, Widget target, int parameter0, int parameter1)
proto native void SetCursorWidget (Widget cursor)
proto native void ShowCursorWidget (bool show)
direct mouse cursor visibility control
proto native bool LoadWidgetImageSet (string filename)
proto native void LoadWidgetStyles (string filename)
proto native bool SetActiveWindow (Widget w, bool resetFocus)
proto native void SetFocus (Widget w)
proto native void SetModal (Widget w)
proto native Widget GetFocus ()
proto native void SetWidgetWorld (RenderTargetWidget w, IEntity wrldEntity, int camera)
proto native bool ReloadTexture (string path)
Variables
WA_LEFT = 0
WA_RIGHT = 1
WA_CENTER = 2
WA_TOP = 0
WA_BOTTOM = 1
WorkspaceWidget Widget ()
Defined in code.
enum VideoCommand GetScrollbarWidth
Detailed Description
Typedef Documentation
EventType
typedef TypeID EventType
WidgetType
typedef TypeID WidgetType
Enumeration Type Documentation
ControlID
enum ControlID
Enumerator
CID_NONE
CID_SELECT
CID_BACK
CID_LEFT
CID_RIGHT
CID_UP
CID_DOWN
CID_MENU
CID_DRAG
CID_TABLEFT
CID_TABRIGHT
CID_RADIALMENU
CID_COUNT
VideoCallback
enum VideoCallback
Enumerator
ON_PLAY
ON_PAUSE
ON_STOP
ON_END
ON_LOAD
ON_SEEK
ON_BUFFERING_START
ON_BUFFERING_END
VideoCommand
enum VideoCommand
Legacy, do not use.
Enumerator
PLAY
STOP
REWIND
POSITION
REPEAT
ISPLAYING
KILL
VideoState
enum VideoState
Enumerator
NONE
There is no video.
PLAYING
The video is playing.
PAUSED
The video is paused.
STOPPED
The video is paused at the beginning of the video.
FINISHED
The video is paused at the end of the video.
WidgetAlignment
enum WidgetAlignment
WidgetFlags
enum WidgetFlags
Enumerator
SOURCEALPHA
BLEND
ADDITIVE
VISIBLE
NOWRAP
CENTER
VCENTER
HEXACTPOS
VEXACTPOS
EXACTPOS
HEXACTSIZE
VEXACTSIZE
EXACTSIZE
NOFILTER
RALIGN
STRETCH
FLIPU
FLIPV
CUSTOMUV
IGNOREPOINTER
DISABLED
NOFOCUS
CLIPCHILDREN
RENDER_ALWAYS
NOCLEAR
DRAGGABLE
Function Documentation
AddChild()
proto native void AddChild (Widget child, bool immedUpdate = true)
Referenced by AddArrow(), IEntity::AddArrow(), DayZInfected::AddArrow(), ManBase::AddArrow(), Particle::AddAsChild(), Particle::CreateParticleEffect(), ManBase::SetDecayEffects(), ManBase::SpawnBreathVaporEffect(), ManBase::SpawnDrowningBubbles(), and UndergroundTriggerCarrierBase::SpawnTrigger().
AddChildAfter() [1/2]
proto native void AddChildAfter (Widget child, Widget after, bool immedUpdate = true)
AddChildAfter() [2/2]
proto native void AddChildAfter (Widget child, Widget after, bool immedUpdate = true) private
AddItem() [1/2]
proto native int AddItem (string item) private
AddItem() [2/2]
proto native int AddItem (string text, Class userData, int column, int row = -1) private
Insert new Row, if row = -1, new Row is inserted at the end otherwise at row index.
CancelWidgetDragging()
proto native Widget CancelWidgetDragging ()
Referenced by Container::CheckHeaderDragability(), SlotsIcon::Clear(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinityContainer::UpdateHeader().
Clear()
proto native void Clear () private
Referenced by InventoryGridController::UpdateItems(), and GameplayEffectWidgets_base::UpdateVisibility().
ClearAll()
proto native void ClearAll () private
ClearFlags()
proto native int ClearFlags (int flags, bool immedUpdate = true)
Referenced by EEKilled(), Grenade_ChemGas::OnDamageDestroyed(), and Ammo_40mm_Explosive::OnDamageDestroyed().
ClearItems()
proto native void ClearItems () private
CreateWidget()
proto native external Widget CreateWidget (WidgetType type, int left, int top, int width, int height, WidgetFlags flags, int color, int sort, Widget parentWidget = NULL) private
Create widgets by WidgetType.
Referenced by GameplayEffectWidgets_base::GameplayEffectWidgets().
CreateWidgets()
proto native external Widget CreateWidgets (string layout, Widget parentWidget = NULL, bool immedUpdate = true) private
Create widgets from *.layout file.
Referenced by AddAgent(), ScriptedWidgetEventHandler::AddItem(), AddModifier(), NotificationUI::AddNotification(), array::AddSubgroup(), ScriptedWidgetEventHandler::AddSubgroup(), ScriptedWidgetEventHandler::AddTab(), HudDebugWinBase::AddValue(), NotificationUI::AddVoiceNotification(), ScriptedWidgetEventHandler::BannerHandlerBase(), ChatLine::ChatLine(), ServerBrowserTab::Construct(), PluginBase::CreateModuleWidgets(), CreateModuleWidgets(), ScriptedWidgetEventHandler::CreateRootWidget(), CGame::CreateTitleScreen(), ScriptedWidgetEventHandler::CreateVideoLoadingEntry(), PluginBase::CreateWidgetOverlay(), CreditsElement::CreditsDepartmentElement(), CreditsDepartmentSection(), CTObjectFollower::CTActor(), ScriptedWidgetEventHandler::CTEvent(), ScriptedWidgetEventHandler::CTKeyframe(), DebugMonitor::DebugMonitor(), ScriptConsoleToolTipEventHandler::DisplayHint(), UIScriptedMenu::DisplayHint(), ScriptedWidgetEventHandler::DropdownPrefab(), ScriptedWidgetEventHandler::GenerateQuickBarBackgroundTiles(), HitDirectionImagesBase::GetCurrentImageData(), Init(), LoginScreenBase::Init(), UIScriptedMenu::Init(), WarningMenuBase::Init(), ScriptConsoleConfigTab::Init(), ScriptedWidgetEventHandler::Init(), Debug::InitCanvas(), InitializeWidgets(), InitWidgets(), PluginBase::InitWidgets(), ItemManager::ItemManager(), ScriptedWidgetEventHandler::KeybindingElement(), ScriptedWidgetEventHandler::KeybindingElementNew(), array::KeybindingsContainer(), ScriptedWidgetEventHandler::KeybindingsGroup(), ScriptedWidgetEventHandler::LayoutHolder(), ScriptedWidgetEventHandler::ModsMenuDetailed(), ScriptedWidgetEventHandler::ModsMenuDetailedEntry(), ScriptedWidgetEventHandler::ModsMenuSimple(), ScriptedWidgetEventHandler::ModsMenuTooltip(), NotificationUI::NotificationUI(), OnClick(), MissionBase::OnInit(), OptionSelectorBase::OptionSelector(), OptionSelectorBase::OptionSelectorEditbox(), OptionSelectorSliderSetup::OptionSelectorLevelMarker(), OptionSelectorSliderSetup::OptionSelectorSlider(), ScriptedWidgetEventHandler::OptionsMenuControls(), ScriptedWidgetEventHandler::OptionsMenuGame(), ScriptedWidgetEventHandler::OptionsMenuSounds(), ScriptedWidgetEventHandler::OptionsMenuVideo(), ScriptedWidgetEventHandler::PlayerListEntryScriptedWidget(), ScriptedWidgetEventHandler::PlayerListScriptedWidget(), Refresh(), GameplayEffectWidgets_base::RegisterLayouts(), ScriptedWidgetEventHandler::ServerBrowserEntry(), Hud::ShowPlayerTag(), SoftSkillManagerDebug(), ScriptedWidgetEventHandler::TutorialKeybinds(), UIPropertyAttachment::UIPropertyAttachment(), and ScriptedWidgetEventHandler::VideoPlayer().
DisableSubtitles()
proto native void DisableSubtitles (bool disable) private
Enable/Disable subtitles.
Warning
Subtitles need font to be assigned to VideoWidget in layout to work
Note
Subtitles are in the format "videoName_Language.srt"
It is best to have the English one without language specified "videoName.srt"
DrawLine()
proto native void DrawLine (float x1, float y1, float x2, float y2, float width, int color) private
Referenced by DrawConnectingLines(), and UIScriptedMenu::DrawConnectingLines().
ElideText()
proto native void ElideText (int line, float maxWidth, string str) private
Enable()
proto native void Enable (bool enable)
Referenced by OptionSelectorBase::OptionSelector().
EnsureVisible()
proto native void EnsureVisible (int row) private
FindAnyWidget()
proto native Widget FindAnyWidget (string pathname)
Referenced by CargoContainerRow::CargoContainerRow(), ClosableHeader::ClosableHeader(), ClosableContainer::DropReceived(), HandsContainer::ElectricityIcon(), ContainerWithElectricManager::ElectricityIcon(), Header::Header(), Icon::Icon(), Icon::InitEx(), InitWidgets(), PluginBase::InitWidgets(), Inventory(), Header::SetItemPreview(), and SlotsContainer::SlotsContainer().
FindAnyWidgetById()
proto native Widget FindAnyWidgetById (int user_id)
FindWidget()
proto native Widget FindWidget (string pathname)
GetAlpha()
proto native float GetAlpha ()
GetBold()
proto native bool GetBold () private
GetCarriageLine()
proto native int GetCarriageLine () private
GetCarriagePos()
proto native int GetCarriagePos () private
GetChildren()
proto native Widget GetChildren ()
Referenced by InventoryItemSuper::EEHealthLevelChanged().
GetColor()
proto native int GetColor ()
Referenced by InventoryItem::GetColorString().
GetContentAlignmentH()
class SpacerBaseWidget extends UIWidget GetContentAlignmentH ()
GetContentAlignmentV()
proto native WidgetAlignment GetContentAlignmentV ()
GetContentHeight() [1/2]
proto native float GetContentHeight () private
GetContentHeight() [2/2]
proto native float GetContentHeight ()
GetContentOffset()
proto native float GetContentOffset () private
GetContentWidth()
proto native float GetContentWidth ()
GetCurrent()
proto native float GetCurrent () private
GetCurrentItem()
proto native int GetCurrentItem () private
GetDragWidget()
proto native Widget GetDragWidget ()
Referenced by Container::CheckHeaderDragability(), ClosableHeader::MouseEnter(), SlotsIcon::MouseEnter(), SlotsIcon::MouseEnterGhostSlot(), SlotsIcon::MouseLeave(), SlotsIcon::MouseLeaveGhostSlot(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinityContainer::UpdateHeader().
GetFlags()
proto native int GetFlags ()
GetFocus()
proto native Widget GetFocus ()
Referenced by GetNextEntry(), GetPrevEntry(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Lighten(), OptionSelectorBase::OnFocus(), and UIScriptedMenu::OnModalResult().
GetHScrollPos()
proto native float GetHScrollPos ()
GetHScrollPos01()
proto native float GetHScrollPos01 ()
GetImage()
proto native int GetImage () private
Returns active image.
GetImageSize()
proto void GetImageSize (int image, out int sx, out int sy) private
returns size of image
GetItalic()
proto native bool GetItalic () private
GetItemData()
proto void GetItemData (int row, int column, out Class data) private
GetItemText()
proto bool GetItemText (int row, int column, out string text) private
Get item.
Parameters
row int Index of row
column int Index of column
Returns
string Value in widget on row and column
string value;
textListboxWidg.GetItemText(2, 0, value);
GetLine()
proto void GetLine (int line, out string text) private
GetLinesCount()
proto native int GetLinesCount () private
GetLineWidth()
proto native float GetLineWidth (int line) private
GetMaskProgress()
proto native float GetMaskProgress () private
Progress determines which alpha values are opaque using the mask. For progress x, pixels with alpha in mask < x will be opaque and alpha in mask > x will be transparent. For smooth transition see GetMaskTransitionWidth.
Returns
Progress from 0 to 1 representing alpha range which is visible in the mask
GetMaskTransitionWidth()
proto native float GetMaskTransitionWidth () private
Transition width 0.1 and progress 0.2 mean that values in mask lower than progress will be opaque. Values higher than (progress + width) will be transparent and values between progress and (progress + width) will be smoothly transitioned.
Returns
Width of the alpha mask transition representing softness of the transition.
GetMax()
proto native float GetMax () private
GetMin()
proto native float GetMin () private
GetName()
string GetName ()
References m_Name.
Referenced by ActionEnterLadder::ActionCondition(), UIScriptedMenu::FilterDLCs(), GetComponentIndex(), ActionTargetsCursor::GetOnScreenPosition(), IsComponentInSelection(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), and HumanInventory::ReplaceItemInHandsWithNewImpl().
GetNumItems()
proto native int GetNumItems () private
GetNumLines()
proto native int GetNumLines () private
GetOutlineColor()
proto native int GetOutlineColor () private
GetOutlineSize()
proto native int GetOutlineSize () private
GetParent()
proto native Widget GetParent ()
Get parent of the Effect.
Note
Same as GetAttachmentParent, but more generic name
Warning
Only gets the cached variable, for immediate effect use GetCurrent variant
Returns
Object The parent of the Effect
References m_ParentObject.
Referenced by BuildPartServer(), DayZPlayer::CameraHandler(), Bolt_Base::CanBeActionTarget(), CanUseToolToBuildPart(), CanUseToolToDismantlePart(), ClosableHeader::ClosableHeader(), CreateCollisionTrigger(), DestroyMaterialsServer(), DestroyPartServer(), EntityLightSource::DetachFromParent(), DismantlePartServer(), DrawDebugCollisionBox(), DropNonUsableMaterialsServer(), DayZPlayer::EOnContact(), GetAttachmentParent(), GetCollisionBoxData(), EffectParticle::GetCurrentLocalPosition(), DayZPlayer::GetDebugText(), GetMaterialType(), ParticleSource::GetParticleParent(), GetRequiredParts(), HasConflictPart(), HasMaterials(), HasMaterialWithQuantityAttached(), HasRequiredPart(), HideConstructionPart(), HideConstructionPartPhysics(), IsColliding(), IsCollidingEx(), EntityAI::IsInTransport(), DayZPlayer::IsInVehicle(), Entity::IsInventoryVisible(), HumanCommandVehicle::IsObjectIgnoredOnGettingOut(), MaterialIsRuined(), EffectParticle::ReAttach(), ReceiveMaterialsServer(), EffectParticle::SetCurrentLocalPosition(), SetLockOnAttachedMaterials(), AttachmentsGroupContainer::SetNextActive(), LayoutHolder::SetNextActive(), AttachmentsGroupContainer::SetPreviousActive(), LayoutHolder::SetPreviousActive(), ShowConstructionPart(), ShowConstructionPartPhysics(), EffectParticle::Start(), Particle::StopParticle(), TakeMaterialsServer(), PlayerContainer::TransferItem(), ZombieContainer::TransferItem(), DayZPlayer::TriggerPullPlayerOutOfVehicle(), UpdateConstructionParts(), Container::UpdateHeaderText(), and VicinityContainer::UpdateInterval().
GetPos()
proto void GetPos (out float x, out float y)
GetRotation()
proto native vector GetRotation ()
returns rotation of widget in order roll, pitch, yaw
GetScreenPos()
proto void GetScreenPos (out float x, out float y)
GetScreenSize()
proto void GetScreenSize (out float width, out float height)
GetScript()
proto void GetScript (out Class data)
GetSelectedRow()
proto native int GetSelectedRow () private
GetShadowColor()
proto native int GetShadowColor () private
GetShadowOffset()
proto void GetShadowOffset (out float sx, out float sy) private
GetShadowOpacity()
proto native float GetShadowOpacity () private
GetShadowSize()
proto native int GetShadowSize () private
GetSibling()
proto native Widget GetSibling ()
Referenced by InventoryItemSuper::EEHealthLevelChanged().
GetSize()
proto void GetSize (out float width, out float height)
GetSort()
proto native int GetSort ()
GetState() [1/2]
proto native bool GetState () private
GetState() [2/2]
proto native VideoState GetState () private
Get the current state of the video.
GetStep()
proto native float GetStep () private
GetStyleName()
proto native owned string GetStyleName ()
GetText() [1/3]
proto string GetText () private
GetText() [2/3]
proto void GetText (out string text) private
GetText() [3/3]
proto void GetText (out string text) private
GetTextBold()
proto native bool GetTextBold () private
GetTextItalic()
proto native bool GetTextItalic () private
GetTextOutlineColor()
proto native int GetTextOutlineColor () private
GetTextOutlineSize()
proto native int GetTextOutlineSize () private
GetTextProportion() [1/2]
proto native float GetTextProportion () private
Get text proportion - ratio between button height and button text height in interval <0,1>
GetTextProportion() [2/2]
proto native float GetTextProportion () private
Get text proportion - ratio between button height and button text height in interval <0,1>
GetTextShadowColor()
proto native int GetTextShadowColor () private
GetTextShadowOffsetX()
proto native float GetTextShadowOffsetX () private
GetTextShadowOffsetY()
proto native float GetTextShadowOffsetY () private
GetTextShadowOpacity()
proto native float GetTextShadowOpacity () private
GetTextShadowSize()
proto native int GetTextShadowSize () private
GetTextSize()
proto void GetTextSize (out int sx, out int sy) private
Returns text size in pixels.
GetTime()
proto native int GetTime () private
Get the current time of the video.
Referenced by Widget::Play().
GetTotalTime()
proto native int GetTotalTime () private
Get the total time of the video.
GetTypeID()
proto native WidgetType GetTypeID ()
GetTypeName()
proto native owned string GetTypeName ()
GetUserData()
proto void GetUserData (out Class data)
GetUserID()
proto native int GetUserID ()
GetVScrollPos()
proto native float GetVScrollPos ()
GetVScrollPos01()
proto native float GetVScrollPos01 ()
GetWidgetUnderCursor()
proto native Widget GetWidgetUnderCursor ()
Referenced by PluginBase::IsMouseInScene().
HScrollStep()
proto native bool HScrollStep (int steps)
HScrollToPos()
proto native void HScrollToPos (float pos)
HScrollToPos01()
proto native void HScrollToPos01 (float pos01)
HScrollToWidget()
proto native void HScrollToWidget (Widget child)
IsChecked()
proto native bool IsChecked () private
IsControlClass()
proto native bool IsControlClass ()
IsLooping()
proto native bool IsLooping () private
Whether looping is enabled.
IsPlaying()
proto native bool IsPlaying () private
QoL direct method to check for playing state (buffering while playing will still return true)
Referenced by Widget::Play().
IsScrollbarVisible()
proto native bool IsScrollbarVisible ()
IsSubtitlesDisabled()
proto native bool IsSubtitlesDisabled () private
Check if subtitles are disabled (enabled by default if available, so it will return false even if there are none)
IsVisible()
proto native bool IsVisible ()
Referenced by UIScriptedMenu::FilterByVisible(), SlotsContainer::IsDisplayable(), UpdateInterval(), and SlotsContainer::VerifySlotsIconVisibility().
IsVisibleHierarchy()
proto native bool IsVisibleHierarchy ()
Load()
proto native bool Load (string name, bool looping = false, int startTime = 0) private
Load a video file.
Referenced by Widget::LoadVideo().
LoadImageFile()
proto native bool LoadImageFile (int num, string name, bool noCache = false) private
Loads image. When image of this 'num' is already loaded, then is replaced by new one.
Parameters
num Number of image (0...7)
name Name of image file
noCache Do not cache the texture
Returns
True when image is loaded, false otherwise
Referenced by Icon::CheckIsWeapon(), and ScriptedWidgetEventHandler::ModsMenuDetailedEntry().
LoadMaskTexture()
proto native bool LoadMaskTexture (string resource) private
Loads texture as mask used for alpha masking.
Parameters
resource Resource name of the texture to load
Returns
True if texture was successfully loaded, false otherwise
LoadVideo()
bool LoadVideo (string name, int soundScene) inline private
Legacy, preferably not used, left for backwards compat.
References Widget::Load(), and name.
LoadWidgetImageSet()
proto native bool LoadWidgetImageSet (string filename)
LoadWidgetStyles()
proto native void LoadWidgetStyles (string filename)
OnChange()
bool OnChange (Widget w, int x, int y, bool finished) private
OnChildAdd()
bool OnChildAdd (Widget w, Widget child) private
OnChildRemove()
bool OnChildRemove (Widget w, Widget child) private
OnClick()
bool OnClick (Widget w, int x, int y, int button) private
OnController()
bool OnController (Widget w, int control, int value) private
control is one of ControlID
OnDoubleClick()
bool OnDoubleClick (Widget w, int x, int y, int button) private
OnDrag()
bool OnDrag (Widget w, int x, int y) private
OnDragging()
bool OnDragging (Widget w, int x, int y, Widget reciever) private
OnDraggingOver()
bool OnDraggingOver (Widget w, int x, int y, Widget reciever) private
OnDrop()
bool OnDrop (Widget w, int x, int y, Widget reciever) private
OnDropReceived()
bool OnDropReceived (Widget w, int x, int y, Widget reciever) private
OnEvent()
bool OnEvent (EventType eventType, Widget target, int parameter0, int parameter1) private
OnFocus()
bool OnFocus (Widget w, int x, int y) private
Referenced by ScriptedWidgetEventHandler::Focus(), ScriptedWidgetEventHandler::OnFocus(), ScriptedWidgetEventHandler::OnMouseEnter(), and ScriptedWidgetEventHandler::OnMouseLeave().
OnFocusLost()
bool OnFocusLost (Widget w, int x, int y) private
Referenced by ScriptedWidgetEventHandler::OnFocusLost(), and ScriptedWidgetEventHandler::OnMouseLeave().
OnItemSelected()
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) private
OnKeyDown()
bool OnKeyDown (Widget w, int x, int y, int key) private
OnKeyPress()
bool OnKeyPress (Widget w, int x, int y, int key) private
OnKeyUp()
bool OnKeyUp (Widget w, int x, int y, int key) private
OnModalResult()
bool OnModalResult (Widget w, int x, int y, int code, int result) private
OnMouseButtonDown()
bool OnMouseButtonDown (Widget w, int x, int y, int button) private
OnMouseButtonUp()
bool OnMouseButtonUp (Widget w, int x, int y, int button) private
OnMouseEnter()
bool OnMouseEnter (Widget w, int x, int y) private
Referenced by ScriptedWidgetEventHandler::OnMouseEnter().
OnMouseLeave()
bool OnMouseLeave (Widget w, Widget enterW, int x, int y) private
Referenced by ScriptedWidgetEventHandler::OnMouseLeave().
OnMouseWheel()
bool OnMouseWheel (Widget w, int x, int y, int wheel) private
OnResize()
bool OnResize (Widget w, int x, int y) private
OnSelect()
bool OnSelect (Widget w, int x, int y) private
OnUpdate()
bool OnUpdate (Widget w) private
Pause()
proto native bool Pause () private
Pauses video playback.
Referenced by Widget::Play().
Play() [1/2]
proto native bool Play () private
Starts video playback.
Referenced by Widget::Play().
Play() [2/2]
int Play (VideoCommand cmd) inline private
Legacy, preferably not used, left for backwards compat.
References Widget::GetTime(), Widget::IsPlaying(), Widget::Pause(), Widget::Play(), Widget::SetLooping(), Widget::SetTime(), and Widget::Unload().
ReloadTexture()
proto native bool ReloadTexture (string path)
RemoveChild()
proto native void RemoveChild (Widget child)
Referenced by InventoryItemSuper::EEHealthLevelChanged().
RemoveItem()
proto native void RemoveItem (int item) private
RemoveRow()
proto native void RemoveRow (int row) private
ReportMouse()
proto native void ReportMouse (int mousex, int mousey, Widget rootWidget)
SelectRow()
proto native void SelectRow (int row) private
SetActiveWindow()
proto native bool SetActiveWindow (Widget w, bool resetFocus)
SetAlpha()
proto native void SetAlpha (float alpha)
SetBold()
proto native void SetBold (bool bold) private
SetCallback()
proto void SetCallback (VideoCallback cb, func fn) private
Set a callback for a certain video event.
SetChecked()
proto native void SetChecked (bool checked) private
SetColor()
proto native void SetColor (int color)
SetContentAlignmentH()
proto native void SetContentAlignmentH (WidgetAlignment alignment)
SetContentAlignmentV()
proto native void SetContentAlignmentV (WidgetAlignment alignment)
SetContentOffset()
proto native void SetContentOffset (float offset, bool snapToLine = false) private
SetCurrent()
proto native void SetCurrent (float curr) private
SetCurrentItem()
proto native int SetCurrentItem (int n) private
SetCursorWidget()
proto native void SetCursorWidget (Widget cursor)
SetFlags()
proto native int SetFlags (int flags, bool immedUpdate = true)
SetFocus()
proto native void SetFocus (Widget w)
Referenced by UIScriptedMenu::BackButtonFocus(), UIScriptedMenu::CheckNewOptions(), UIScriptedMenu::CloseOnline(), UIScriptedMenu::ColorDisable(), ColorDisable(), ServerBrowserTab::ColorDisable(), UIScriptedMenu::ColorDisabled(), OptionSelectorBase::ColorHighlight(), UIScriptedMenu::ColorRed(), ScriptedWidgetEventHandler::ColorRed(), ScriptedWidgetEventHandler::ColorRed(), UIScriptedMenu::ColorWhite(), ScriptedWidgetEventHandler::Focus(), ScriptedWidgetEventHandler::FocusFirst(), GetNextEntry(), GetPrevEntry(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::OnChange(), OptionSelectorBase::OnFocus(), UIScriptedMenu::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnMouseButtonUp(), ScriptedWidgetEventHandler::OnMouseEnter(), OnMouseEnter(), ServerBrowserTab::OnMouseEnter(), UIScriptedMenu::OnMouseLeave(), OptionSelectorBase::OnMouseLeave(), ServerBrowserTab::OnMouseLeave(), UIScriptedMenu::OnShow(), OnShow(), ServerBrowserTab::SetEnableFilters(), ServerBrowserTab::SetFocusServers(), ScriptedWidgetEventHandler::UpdateEntry(), and UIScriptedMenu::UpdateMenuFocus().
SetGUIWidget()
proto native void SetGUIWidget (IEntity ent, int index, RTTextureWidget w)
sets Widget typu RTTextureWidgetTypeID, to which it is possible to reference in shader as $rendertarget it is posible to use only after object selection. When selecting another object, it is necessary to set GUI widget again
SetHandler()
proto native void SetHandler (ScriptedWidgetEventHandler eventHandler)
SetHideText()
proto native void SetHideText (bool hide) private
SetImage()
proto native bool SetImage (int num) private
Switches to another image, if it's loaded
Parameters
num Number of image.
Returns
True when there is such image, false otherwise.
Referenced by ScriptedWidgetEventHandler::Deselect(), and ScriptedWidgetEventHandler::Select().
SetImageTexture()
proto native void SetImageTexture (int image, RTTextureWidget texture) private
SetItalic()
proto native void SetItalic (bool italic) private
SetItem() [1/2]
proto native void SetItem (int item, string value) private
SetItem() [2/2]
proto native void SetItem (int position, string text, Class userData, int column) private
SetItemColor()
proto native void SetItemColor (int row, int column, int color) private
SetLine()
proto native void SetLine (int line, string text) private
SetLineBreakingOverride()
proto native float SetLineBreakingOverride (int mode) private
Referenced by ScriptedWidgetEventHandler::Init(), and ScriptedWidgetEventHandler::ModsMenuDetailedEntry().
SetLinesVisibility()
proto native void SetLinesVisibility (int lineFrom, int lineTo, bool visible) private
SetLooping()
proto native void SetLooping (bool looping) private
Set whether the video should loop.
Referenced by Widget::Play().
SetLV()
static proto void SetLV (float lv) static
Set global LV of widgets, value between [-15, 0], default: 0, lower value is less bright.
SetMaskProgress()
proto native void SetMaskProgress (float value) private
See GetMaskProgress for explanation.
Parameters
value Expected in range [0; 1]
SetMaskTransitionWidth()
proto native void SetMaskTransitionWidth (float value) private
See GetMaskTransitionWidth for transition width explanation.
Parameters
value Expected in range [0; 1]
SetMinMax()
proto native void SetMinMax (float minimum, float maximum) private
SetModal()
proto native void SetModal (Widget w)
SetName()
proto native void SetName (string name)
SetObjectLighting()
static proto void SetObjectLighting (float lighting) static
Set global lighting of objects in widgets, value between [0, 1], default: 1, lower value is less bright.
SetOutline()
proto native void SetOutline (int outlineSize, int argb = 0xFF000000) private
SetPos()
proto native void SetPos (float x, float y, bool immedUpdate = true)
SetRefresh()
proto native void SetRefresh (int period, int offset) private
when period > 1 then every n-th frame will be rendered. Offset is initial counter.
SetResolutionScale()
proto native void SetResolutionScale (float xscale, float ycale) private
SetRotation()
proto native void SetRotation (float roll, float pitch, float yaw, bool immedUpdate = true)
Referenced by ScriptedWidgetEventHandler::CreateFollowedObject().
SetScreenPos()
proto native void SetScreenPos (float x, float y, bool immedUpdate = true)
SetScreenSize()
proto native void SetScreenSize (float w, float h, bool immedUpdate = true)
SetShadow()
proto native void SetShadow (int shadowSize, int shadowARGB = 0xFF000000, float shadowOpacity = 1, float shadowOffsetX = 0, float shadowOffsetY = 0) private
SetSize()
proto native void SetSize (float w, float h, bool immedUpdate = true)
Referenced by updateSlotsCount().
SetSort()
proto native void SetSort (int sort, bool immedUpdate = true)
Referenced by ServerBrowserTab::Construct(), and ServerBrowserTab::ToggleSort().
SetState()
proto native bool SetState (bool state) private
SetStep()
proto native void SetStep (float step) private
SetText() [1/2]
proto native void SetText (string str) private
SetText() [2/2]
proto native void SetText (string text, bool immedUpdate = true) private
Referenced by ScriptedWidgetEventHandler::CreateVideoLoadingEntry(), ScriptConsoleConfigTab::Init(), and ScriptedWidgetEventHandler::LoadData().
SetTextBold()
proto native void SetTextBold (bool bold) private
SetTextColor()
proto native void SetTextColor (int color) private
SetTextExactSize()
proto native void SetTextExactSize (int size) private
set text exact size. Exact Text flag must be enabled. 0 equals original size.
SetTextFormat()
proto void SetTextFormat (string text, void param1 = NULL, void param2 = NULL, void param3 = NULL, void param4 = NULL, void param5 = NULL, void param6 = NULL, void param7 = NULL, void param8 = NULL, void param9 = NULL) private
SetTextHorizontalAlignment()
proto native void SetTextHorizontalAlignment (int align) private
Parameters
align ALIGN_CENTER, ALIGN_LEFT, ALIGN_RIGHT
SetTextItalic()
proto native void SetTextItalic (bool italic) private
SetTextLV()
static proto void SetTextLV (float lv) static
Set global LV of the text in widgets, value between [-15, 0], default: 0, lower value is less bright.
SetTextOffset() [1/2]
proto native void SetTextOffset (float xoffset, float yoffset) private
SetTextOffset() [2/2]
proto native void SetTextOffset (int left, int top) private
SetTextOutline()
proto native void SetTextOutline (int outlineSize, int argb = 0xFF000000) private
SetTextProportion() [1/2]
proto native void SetTextProportion (float val) private
Set text proportion - ratio between button height and button text height in interval <0,1>
SetTextProportion() [2/2]
proto native void SetTextProportion (float val) private
Set text proportion - ratio between button height and button text height in interval <0,1>
SetTextShadow()
proto native void SetTextShadow (int shadowSize, int shadowARGB = 0xFF000000, float shadowOpacity = 1.0, float shadowOffsetX = 0.0, float shadowOffsetY = 0.0) private
SetTextSpacing()
proto native void SetTextSpacing (int horiz, int vert) private
SetTextVerticalAlignment()
proto native void SetTextVerticalAlignment (int align) private
Parameters
align ALIGN_CENTER, ALIGN_TOP, ALIGN_BOTTOM
SetTime()
proto native bool SetTime (int time, bool preload) private
Set the desired time for the video (preload decides whether it will already load the next frames too)
Referenced by Widget::Play().
SetTransform()
proto native void SetTransform (vector mat[4], bool immedUpdate = true)
SetUserData()
proto native void SetUserData (Class data)
SetUserID()
proto native void SetUserID (int id)
SetUV()
proto native void SetUV (float uv[4][2]) private
When WF_CUSTOMUV is set, we can supply our own UV coords instead of computed ones.
Parameters
uv Pointer to array of at least 8 floats (4 corners * 2 floats for u/v)
SetWidgetWorld()
proto native void SetWidgetWorld (RenderTargetWidget w, IEntity wrldEntity, int camera)
Show()
proto native void Show (bool show, bool immedUpdate = true)
ShowCursorWidget()
proto native void ShowCursorWidget (bool show)
direct mouse cursor visibility control
Referenced by CGame::RefreshMouseCursorVisibility().
Stop()
proto native bool Stop () private
Stop video playback (cancels everything and sets it back at time 0)
Referenced by Hud::ShowWalkieTalkie().
TranslateString()
static proto string TranslateString (string stringId) static
Unlink()
proto native void Unlink ()
Unload()
proto native void Unload () private
Unload the video, freeing up all resources.
Referenced by Widget::Play().
Update()
override void Update ()
don't show crosshair if it's disabled in profile or from server
References ScriptModule::CallFunction(), CONTROLLER_DESELECT_TIMEOUT, CONTROLLER_TILT_TRESHOLD_SELECT, g_Game, CGame::GameScript, ScriptedWidgetEventHandler::GetActionManager(), GetAngleInDegrees(), GetCurrentCrossHair(), GetGame(), GetMouseDistance(), GetMousePointerAngle(), GetObjectByDegAngle(), ScriptedWidgetEventHandler::GetPlayer(), CGame::GetTime(), GetZone(), HideRadialSelector(), DayZPlayer::IsPlayerSelected(), IsUsingController(), IsUsingMouse(), last_time, m_AM, m_ControllerAngle, m_ControllerTilt, m_ControllerTimout, m_Handlers, m_IsControllerTimoutEnabled, m_Player, m_player, m_RegisteredClass, m_SelectedObject, m_Stamina, m_StaminaLastValue, m_StaminaZoneOffset, m_UpdateTimer, m_WidgetInitialized, MAX_HANDLERS_COUNT, MOUSE_SAFE_ZONE_RADIUS, ProcessSound(), randomValuesArray, Refresh(), SelectCrossHair(), SetAgents(), SetAllowUpdate(), ShowCrossHair(), ShowRadialSelector(), Timer::Stop(), UpdataControllerInput(), and USAGE_COUNT.
Referenced by ScriptedWidgetEventHandler::ContinuousActionProgress(), CrossHairSelector(), GameplayEffectsData::ForceStop(), Init(), ScriptedWidgetEventHandler::ItemActionsWidget(), ScriptedWidgetEventHandler::ProjectedCrosshair(), RadialProgressBar::RadialProgressBar(), ParticleSource::SetWiggle(), ScriptedWidgetEventHandler::~ContinuousActionProgress(), ~CrossHairSelector(), ScriptedWidgetEventHandler::~ItemActionsWidget(), ScriptedWidgetEventHandler::~ProjectedCrosshair(), and RadialProgressBar::~RadialProgressBar().
VScrollStep()
proto native bool VScrollStep (int steps)
VScrollToPos()
proto native void VScrollToPos (float pos)
VScrollToPos01()
proto native void VScrollToPos01 (float pos01)
VScrollToWidget()
proto native void VScrollToWidget (Widget child)
Variable Documentation
GetScrollbarWidth
class GridSpacerWidget extends SpacerWidget GetScrollbarWidth
WA_BOTTOM
WA_BOTTOM = 1
WA_CENTER
WA_CENTER = 2
WA_LEFT
WA_LEFT = 0
WA_RIGHT
WA_RIGHT = 1
WA_TOP
WA_TOP = 0
Widget
proto private void Widget
Defined in code.