DayZ Scripts: WarmthNotfr Class Reference
WarmthNotfr Class Reference
Private Member Functions
void WarmthNotfr (NotifiersManager manager)
override int GetNotifierType ()
protected DSLevelsTemp DetermineLevel (float value, float m_warning_treshold, float m_critical_treshold, float m_empty_treshold, float p_warning_treshold, float p_critical_treshold, float p_empty_treshold)
override void DisplayTendency (float delta)
override protected float GetObservedValue ()
Private Attributes
private const float DEC_TRESHOLD_LOW = 0
private const float DEC_TRESHOLD_MED = -0.2
private const float DEC_TRESHOLD_HIGH = -0.3
private const float INC_TRESHOLD_LOW = 0
private const float INC_TRESHOLD_MED = 0.2
private const float INC_TRESHOLD_HIGH = 0.3
Constructor & Destructor Documentation
WarmthNotfr()
void WarmthNotfr (NotifiersManager manager) inline private
References NotifierBase::m_TendencyBufferSize.
Member Function Documentation
DetermineLevel()
protected DSLevelsTemp DetermineLevel (float value, float m_warning_treshold, float m_critical_treshold, float m_empty_treshold, float p_warning_treshold, float p_critical_treshold, float p_empty_treshold) inline private
Referenced by DisplayTendency().
DisplayTendency()
override void DisplayTendency (float delta) inline private
References NotifierBase::CalculateTendency(), DEC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, DetermineLevel(), GetElement(), GetObservedValue(), NotifierBase::GetVirtualHud(), INC_TRESHOLD_HIGH, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_CRITICAL, PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_EMPTY, PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_WARNING, PlayerConstants::THRESHOLD_HEAT_COMFORT_PLUS_CRITICAL, PlayerConstants::THRESHOLD_HEAT_COMFORT_PLUS_EMPTY, and PlayerConstants::THRESHOLD_HEAT_COMFORT_PLUS_WARNING.
GetNotifierType()
override int GetNotifierType () inline private
GetObservedValue()
override protected float GetObservedValue () inline private
References NotifierBase::m_Player.
Referenced by DisplayTendency().
Field Documentation
DEC_TRESHOLD_HIGH
private const float DEC_TRESHOLD_HIGH = -0.3 private
Referenced by DisplayTendency().
DEC_TRESHOLD_LOW
private const float DEC_TRESHOLD_LOW = 0 private
Referenced by DisplayTendency().
DEC_TRESHOLD_MED
private const float DEC_TRESHOLD_MED = -0.2 private
Referenced by DisplayTendency().
INC_TRESHOLD_HIGH
private const float INC_TRESHOLD_HIGH = 0.3 private
Referenced by DisplayTendency().
INC_TRESHOLD_LOW
private const float INC_TRESHOLD_LOW = 0 private
Referenced by DisplayTendency().
INC_TRESHOLD_MED
private const float INC_TRESHOLD_MED = 0.2 private
Referenced by DisplayTendency().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerNotifiers/Notifiers/WarmthNotfr.c