DayZ Scripts: ScriptConsoleGeneralTab Class Reference
ScriptConsoleGeneralTab Class Reference
Private Member Functions
void ScriptConsoleGeneralTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
void ~ScriptConsoleGeneralTab ()
protected void Init ()
void RefreshDateWidgets (int year, int month, int day, int hour, int minute)
bool IsLocationNameAvailable (string name)
void LateInit ()
void Teleport (PlayerBase player, vector position)
void ProcessTeleportText (PlayerBase player)
array< float > TextToNumbersArray (string text)
void RefreshLocations ()
string GetCurrentLocationName ()
vector GetCurrentLocationPos ()
void GetCurrentPositionData (out LocationParams data)
bool IsCurrentPositionCustom ()
int GetCurrentPositionIndex ()
bool IsCurrentPositionValid ()
void UpdateHudDebugSetting ()
void RefreshPlayerPosEditBoxes ()
void UpdateTime (bool slider_used)
void UpdateMousePos ()
void SetMapPos (vector pos)
void SetDir (vector dir)
vector GetMapPos ()
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnKeyDown (Widget w, int x, int y, int key)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override void OnRPCEx (int rpc_type, ParamsReadContext ctx)
override void Update (float timeslice)
Private Attributes
protected const string NUMERIC_LETTERS = "0123456789.-"
protected vector m_MapPos
protected bool m_PlayerPosRefreshBlocked
protected ref array< ref RemotePlayerStatDebug > m_PlayerDebugStats = new array<ref RemotePlayerStatDebug>
protected MissionGameplay m_MissionGameplay
protected PluginDeveloper m_Developer
protected SliderWidget m_TimeSlider
protected ref Timer m_LateInit = new Timer()
protected bool m_UpdatePlayerPositions
protected bool m_InitialOpen = true
protected EditBoxWidget m_TeleportHeading
protected EditBoxWidget m_TeleportXYZ
protected EditBoxWidget m_DateYear
protected EditBoxWidget m_DateMonth
protected EditBoxWidget m_DateDay
protected EditBoxWidget m_DateHour
protected EditBoxWidget m_DateMinute
protected ButtonWidget m_LocationAddButton
protected ButtonWidget m_LocationRemoveButton
protected ButtonWidget m_TeleportButton
protected ButtonWidget m_ButtonCopyPos
protected ButtonWidget m_DiagDrawButton
protected ButtonWidget m_DiagToggleButton
protected CheckBoxWidget m_LogsEnabled
protected CheckBoxWidget m_HudDCharStats
protected CheckBoxWidget m_HudDCharLevels
protected CheckBoxWidget m_HudDCharStomach
protected CheckBoxWidget m_HudDCharModifiers
protected CheckBoxWidget m_HudDCharAgents
protected CheckBoxWidget m_HudDCharDebug
protected CheckBoxWidget m_HudDFreeCamCross
protected CheckBoxWidget m_HudDVersion
protected CheckBoxWidget m_HudDHealth
protected CheckBoxWidget m_ShowOthers
protected CheckBoxWidget m_HudDTemperature
protected MapWidget m_DebugMapWidget
protected TextWidget m_PlayerCurPos
protected TextWidget m_PlayerCurDir
protected TextWidget m_MouseCurPos
protected TextWidget m_PlayerMouseDiff
protected TextListboxWidget m_DiagToggleTextListbox
protected TextListboxWidget m_PositionsListbox
protected TextListboxWidget m_DiagDrawmodeTextListbox
protected TextListboxWidget m_HelpTextListboxWidget
Static Private Attributes
static int m_ObjectsScope = 2
static protected vector m_LastEditPos = vector.Zero
static protected vector m_LastEditDir = vector.Zero
static protected float DEBUG_MAP_ZOOM = 1
static protected bool SHOW_OTHERS = 0
Constructor & Destructor Documentation
ScriptConsoleGeneralTab()
void ScriptConsoleGeneralTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline private
References GetGame(), GetPlugin(), Init(), LateInit(), m_ButtonCopyPos, m_DateDay, m_DateHour, m_DateMinute, m_DateMonth, m_DateYear, m_DebugMapWidget, m_Developer, m_DiagDrawButton, m_DiagDrawmodeTextListbox, m_DiagToggleButton, m_DiagToggleTextListbox, m_HelpTextListboxWidget, m_HudDCharAgents, m_HudDCharDebug, m_HudDCharLevels, m_HudDCharModifiers, m_HudDCharStats, m_HudDCharStomach, m_HudDFreeCamCross, m_HudDHealth, m_HudDTemperature, m_HudDVersion, m_LocationAddButton, m_LocationRemoveButton, m_LogsEnabled, m_MissionGameplay, m_MouseCurPos, m_PlayerCurDir, m_PlayerCurPos, m_PlayerMouseDiff, m_PositionsListbox, m_ShowOthers, m_TeleportButton, m_TeleportHeading, m_TeleportXYZ, and m_TimeSlider.
~ScriptConsoleGeneralTab()
void ~ScriptConsoleGeneralTab () inline private
References DEBUG_MAP_ZOOM, GetGame(), GetPlayer(), GetPlugin(), MapWidget::GetScale(), m_DebugMapWidget, and SHOW_OTHERS.
Member Function Documentation
GetCurrentLocationName()
string GetCurrentLocationName () inline private
References GetCurrentPositionData(), and name.
Referenced by OnClick().
GetCurrentLocationPos()
vector GetCurrentLocationPos () inline private
References GetCurrentPositionData(), and vector::Zero.
Referenced by OnClick(), OnDoubleClick(), and OnItemSelected().
GetCurrentPositionData()
void GetCurrentPositionData (out LocationParams data) inline private
References m_PositionsListbox.
Referenced by GetCurrentLocationName(), GetCurrentLocationPos(), and IsCurrentPositionCustom().
GetCurrentPositionIndex()
int GetCurrentPositionIndex () inline private
References m_PositionsListbox.
Referenced by OnClick(), and OnItemSelected().
GetMapPos()
vector GetMapPos () inline private
References m_MapPos.
Referenced by OnClick(), and Update().
Init()
protected void Init () inline private
References DEBUG_MAP_ZOOM, World::GetDate(), CGame::GetDiagDrawModeNames(), CGame::GetDiagModeNames(), GetGame(), GetPlayer(), CGame::GetWorld(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_DebugMapWidget, m_DiagDrawmodeTextListbox, m_DiagToggleTextListbox, m_HudDCharAgents, m_HudDCharDebug, m_HudDCharLevels, m_HudDCharModifiers, m_HudDCharStats, m_HudDCharStomach, m_HudDFreeCamCross, m_HudDHealth, m_HudDTemperature, m_HudDVersion, m_LastEditDir, m_LastEditPos, m_LateInit, m_LogsEnabled, m_TeleportHeading, m_TeleportXYZ, RefreshDateWidgets(), RefreshLocations(), MapWidget::SetMapPos(), MapWidget::SetScale(), vector::ToString(), UpdateHudDebugSetting(), and vector::Zero.
Referenced by ScriptConsoleGeneralTab().
IsCurrentPositionCustom()
bool IsCurrentPositionCustom () inline private
References GetCurrentPositionData().
IsCurrentPositionValid()
bool IsCurrentPositionValid () inline private
References m_PositionsListbox.
Referenced by OnClick(), and OnItemSelected().
IsLocationNameAvailable()
bool IsLocationNameAvailable (string name) inline private
References m_PositionsListbox, and name.
Referenced by UIScriptedMenu::OnClick().
LateInit()
void LateInit () inline private
References GetGame(), GetPlayer(), GetPlugin(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_PositionsListbox, m_ShowOthers, m_UpdatePlayerPositions, and SHOW_OTHERS.
Referenced by ScriptConsoleGeneralTab().
OnChange()
override bool OnChange (Widget w, int x, int y, bool finished) inline private
References GetGame(), GetPlayer(), GetPlugin(), m_DateDay, m_DateHour, m_DateMinute, m_DateMonth, m_DateYear, m_ShowOthers, m_TimeSlider, m_UpdatePlayerPositions, SHOW_OTHERS, UpdateTime(), x, and y.
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, CGame::CopyToClipboard(), g_Game, CGame::GetCallQueue(), GetCurrentLocationName(), GetCurrentLocationPos(), GetCurrentPositionIndex(), CGame::GetDiagModeEnable(), GetGame(), GetMapPos(), GetPlayer(), GetPlugin(), IsCurrentPositionValid(), m_ButtonCopyPos, ScriptConsoleTabBase::m_ConfigDebugProfile, m_DiagDrawButton, m_DiagDrawmodeTextListbox, m_DiagToggleButton, m_DiagToggleTextListbox, m_HudDCharAgents, m_HudDCharDebug, m_HudDCharLevels, m_HudDCharModifiers, m_HudDCharStats, m_HudDCharStomach, m_HudDFreeCamCross, m_HudDHealth, m_HudDTemperature, m_HudDVersion, ScriptConsoleTabBase::m_IsShiftDown, m_LocationAddButton, m_LocationRemoveButton, m_LogsEnabled, m_MissionGameplay, m_PositionsListbox, ScriptConsoleTabBase::m_ScriptConsole, m_TeleportButton, MENU_LOC_ADD, ProcessTeleportText(), RefreshCrosshairVisibility(), RefreshLocations(), CGame::SetDiagDrawMode(), CGame::SetDiagModeEnable(), LogManager::SetLogsEnabled(), ToString(), x, and y.
OnDoubleClick()
override bool OnDoubleClick (Widget w, int x, int y, int button) inline private
References GetCurrentLocationPos(), GetGame(), GetPlayer(), m_DebugMapWidget, m_Developer, m_PositionsListbox, m_TeleportHeading, m_TeleportXYZ, Math::Max(), MapWidget::ScreenToMap(), CGame::SurfaceRoadY(), CGame::SurfaceY(), Teleport(), Vector(), x, and y.
OnItemSelected()
override bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
References GetCurrentLocationPos(), GetCurrentPositionIndex(), IsCurrentPositionValid(), ScriptConsoleTabBase::m_ConfigDebugProfile, m_InitialOpen, m_PositionsListbox, m_TeleportXYZ, vector::ToString(), x, and y.
OnKeyDown()
override bool OnKeyDown (Widget w, int x, int y, int key) inline private
References x, and y.
OnMouseButtonDown()
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
References GetGame(), GetMousePos(), GetPlayer(), m_DebugMapWidget, m_PlayerPosRefreshBlocked, MapWidget::ScreenToMap(), SetMapPos(), CGame::SurfaceY(), x, and y.
OnRPCEx()
override void OnRPCEx (int rpc_type, ParamsReadContext ctx) inline private
References m_PlayerDebugStats, and Serializer::Read().
ProcessTeleportText()
void ProcessTeleportText (PlayerBase player) inline private
References GetGame(), m_Developer, m_LastEditDir, m_LastEditPos, m_TeleportHeading, m_TeleportXYZ, Teleport(), TextToNumbersArray(), vector::ToString(), Vector(), and vector::Zero.
Referenced by OnClick().
RefreshDateWidgets()
void RefreshDateWidgets (int year, int month, int day, int hour, int minute) inline private
References Math::InverseLerp(), m_DateDay, m_DateHour, m_DateMinute, m_DateMonth, m_DateYear, and m_TimeSlider.
Referenced by Init(), and UpdateTime().
RefreshLocations()
void RefreshLocations () inline private
References ScriptConsoleTabBase::m_ConfigDebugProfile, ScriptConsoleTabBase::m_ConfigDebugProfileFixed, m_PositionsListbox, and name.
Referenced by Init(), UIScriptedMenu::OnClick(), and OnClick().
RefreshPlayerPosEditBoxes()
void RefreshPlayerPosEditBoxes () inline private
References GetGame(), CGame::GetPlayer(), GetPlayer(), SetDir(), and SetMapPos().
Referenced by Update().
SetDir()
void SetDir (vector dir) inline private
References m_PlayerCurDir.
Referenced by RefreshPlayerPosEditBoxes().
SetMapPos()
void SetMapPos (vector pos) inline private
References m_MapPos, and m_PlayerCurPos.
Referenced by OnMouseButtonDown(), and RefreshPlayerPosEditBoxes().
Teleport()
void Teleport (PlayerBase player, vector position) inline private
References GetGame(), m_Developer, and CGame::SurfaceY().
Referenced by OnDoubleClick(), and ProcessTeleportText().
TextToNumbersArray()
array< float > TextToNumbersArray (string text) inline private
References string::Contains(), string::Get(), string::Length(), NUMERIC_LETTERS, string::Substring(), and string::ToFloat().
Referenced by ProcessTeleportText().
Update()
override void Update (float timeslice) inline private
References MapWidget::AddUserMark(), MapWidget::ClearUserMarks(), COLOR_BLUE, COLOR_RED, GetGame(), GetMapPos(), MapMarkerTypes::GetMarkerTypeFromID(), GetPlayer(), vector::Length(), m_DebugMapWidget, m_PlayerDebugStats, m_PlayerPosRefreshBlocked, m_UpdatePlayerPositions, RefreshPlayerPosEditBoxes(), RemotePlayerStatDebug(), ToString(), and UpdateMousePos().
UpdateHudDebugSetting()
void UpdateHudDebugSetting () private
Referenced by Init().
UpdateMousePos()
void UpdateMousePos () inline private
References GetGame(), GetMousePos(), CGame::GetPlayer(), GetPlayer(), m_DebugMapWidget, m_MouseCurPos, m_PlayerMouseDiff, MapWidget::ScreenToMap(), CGame::SurfaceY(), x, and y.
Referenced by Update().
UpdateTime()
void UpdateTime (bool slider_used) inline private
References g_Game, GetGame(), CGame::GetPlayer(), GetPlayer(), CGame::GetWorld(), Math::Lerp(), m_DateDay, m_DateHour, m_DateMinute, m_DateMonth, m_DateYear, m_TimeSlider, RefreshDateWidgets(), and World::SetDate().
Referenced by OnChange().
Field Documentation
DEBUG_MAP_ZOOM
protected float DEBUG_MAP_ZOOM = 1 static private
Referenced by Init(), and ~ScriptConsoleGeneralTab().
m_ButtonCopyPos
protected ButtonWidget m_ButtonCopyPos private
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_DateDay
protected EditBoxWidget m_DateDay private
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_DateHour
protected EditBoxWidget m_DateHour private
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_DateMinute
protected EditBoxWidget m_DateMinute private
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_DateMonth
protected EditBoxWidget m_DateMonth private
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_DateYear
protected EditBoxWidget m_DateYear private
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_DebugMapWidget
protected MapWidget m_DebugMapWidget private
Referenced by Init(), OnDoubleClick(), OnMouseButtonDown(), ScriptConsoleGeneralTab(), Update(), UpdateMousePos(), and ~ScriptConsoleGeneralTab().
m_Developer
protected PluginDeveloper m_Developer private
Referenced by OnDoubleClick(), ProcessTeleportText(), ScriptConsoleGeneralTab(), and Teleport().
m_DiagDrawButton
protected ButtonWidget m_DiagDrawButton private
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_DiagDrawmodeTextListbox
protected TextListboxWidget m_DiagDrawmodeTextListbox private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_DiagToggleButton
protected ButtonWidget m_DiagToggleButton private
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_DiagToggleTextListbox
protected TextListboxWidget m_DiagToggleTextListbox private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HelpTextListboxWidget
protected TextListboxWidget m_HelpTextListboxWidget private
Referenced by ScriptConsoleGeneralTab().
m_HudDCharAgents
protected CheckBoxWidget m_HudDCharAgents private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDCharDebug
protected CheckBoxWidget m_HudDCharDebug private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDCharLevels
protected CheckBoxWidget m_HudDCharLevels private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDCharModifiers
protected CheckBoxWidget m_HudDCharModifiers private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDCharStats
protected CheckBoxWidget m_HudDCharStats private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDCharStomach
protected CheckBoxWidget m_HudDCharStomach private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDFreeCamCross
protected CheckBoxWidget m_HudDFreeCamCross private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDHealth
protected CheckBoxWidget m_HudDHealth private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDTemperature
protected CheckBoxWidget m_HudDTemperature private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_HudDVersion
protected CheckBoxWidget m_HudDVersion private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_InitialOpen
protected bool m_InitialOpen = true private
Referenced by OnItemSelected().
m_LastEditDir
protected vector m_LastEditDir = vector.Zero static private
Referenced by Init(), and ProcessTeleportText().
m_LastEditPos
protected vector m_LastEditPos = vector.Zero static private
Referenced by Init(), and ProcessTeleportText().
m_LateInit
protected ref Timer m_LateInit = new Timer() private
Referenced by Init().
m_LocationAddButton
protected ButtonWidget m_LocationAddButton private
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_LocationRemoveButton
protected ButtonWidget m_LocationRemoveButton private
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_LogsEnabled
protected CheckBoxWidget m_LogsEnabled private
Referenced by Init(), OnClick(), and ScriptConsoleGeneralTab().
m_MapPos
protected vector m_MapPos private
Referenced by GetMapPos(), and SetMapPos().
m_MissionGameplay
protected MissionGameplay m_MissionGameplay private
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_MouseCurPos
protected TextWidget m_MouseCurPos private
Referenced by ScriptConsoleGeneralTab(), and UpdateMousePos().
m_ObjectsScope
int m_ObjectsScope = 2 static private
m_PlayerCurDir
protected TextWidget m_PlayerCurDir private
Referenced by ScriptConsoleGeneralTab(), and SetDir().
m_PlayerCurPos
protected TextWidget m_PlayerCurPos private
Referenced by ScriptConsoleGeneralTab(), and SetMapPos().
m_PlayerDebugStats
protected ref array<ref RemotePlayerStatDebug> m_PlayerDebugStats = new array<ref RemotePlayerStatDebug> private
Referenced by OnRPCEx(), and Update().
m_PlayerMouseDiff
protected TextWidget m_PlayerMouseDiff private
Referenced by ScriptConsoleGeneralTab(), and UpdateMousePos().
m_PlayerPosRefreshBlocked
protected bool m_PlayerPosRefreshBlocked private
Referenced by OnMouseButtonDown(), and Update().
m_PositionsListbox
protected TextListboxWidget m_PositionsListbox private
Referenced by GetCurrentPositionData(), GetCurrentPositionIndex(), IsCurrentPositionValid(), IsLocationNameAvailable(), LateInit(), OnClick(), OnDoubleClick(), OnItemSelected(), RefreshLocations(), and ScriptConsoleGeneralTab().
m_ShowOthers
protected CheckBoxWidget m_ShowOthers private
Referenced by LateInit(), OnChange(), and ScriptConsoleGeneralTab().
m_TeleportButton
protected ButtonWidget m_TeleportButton private
Referenced by OnClick(), and ScriptConsoleGeneralTab().
m_TeleportHeading
protected EditBoxWidget m_TeleportHeading private
Referenced by Init(), OnDoubleClick(), ProcessTeleportText(), and ScriptConsoleGeneralTab().
m_TeleportXYZ
protected EditBoxWidget m_TeleportXYZ private
Referenced by Init(), OnDoubleClick(), OnItemSelected(), ProcessTeleportText(), and ScriptConsoleGeneralTab().
m_TimeSlider
protected SliderWidget m_TimeSlider private
Referenced by OnChange(), RefreshDateWidgets(), ScriptConsoleGeneralTab(), and UpdateTime().
m_UpdatePlayerPositions
protected bool m_UpdatePlayerPositions private
Referenced by LateInit(), OnChange(), and Update().
NUMERIC_LETTERS
protected const string NUMERIC_LETTERS = "0123456789.-" private
Referenced by TextToNumbersArray().
SHOW_OTHERS
protected bool SHOW_OTHERS = 0 static private
Referenced by LateInit(), OnChange(), and ~ScriptConsoleGeneralTab().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptConsoleGeneralTab.c