DayZ Scripts: FileIO API
FileIO API
System
Typedefs
typedef int[] ParseHandle
typedef int[] FileHandle
typedef int[] FindFileHandle
Enumerations
enum FileMode { READ , WRITE , APPEND }
enum FileAttr { DIRECTORY , HIDDEN , READONLY , INVALID }
enum FindFileFlags
Functions
proto native ParseHandle BeginParse (string filename)
proto int ParseLine (ParseHandle tp, int num, string tokens[])
proto native void EndParse (ParseHandle file)
proto bool FileExist (string name)
Check existence of file.
proto FileHandle OpenFile (string name, FileMode mode)
Opens File.
proto int ReadFile (FileHandle file, void param_array, int length)
proto void CloseFile (FileHandle file)
Close the File.
proto void FPrint (FileHandle file, void var)
Write to file.
proto void FPrintln (FileHandle file, void var)
Write to file and add new line.
proto int FGets (FileHandle file, string var)
Get line from file, every next call of this function returns next line.
enum FindFileFlags FindFile (string pattern, out string fileName, out FileAttr fileAttributes, FindFileFlags flags)
proto bool FindNextFile (FindFileHandle handle, out string fileName, out FileAttr fileAttributes)
proto native void CloseFindFile (FindFileHandle handle)
proto native bool MakeDirectory (string name)
Makes a directory.
proto native bool DeleteFile (string name)
delete file. Works only on "$profile:" and "$saves:" locations
proto native bool CopyFile (string sourceName, string destName)
copy file. destName must be "$profile:" or "$saves:" location
Detailed Description
Typedef Documentation
FileHandle
typedef int [] FileHandle
Definition at line 390 of file EnSystem.c.
FindFileHandle
typedef int [] FindFileHandle
Definition at line 503 of file EnSystem.c.
ParseHandle
typedef int [] ParseHandle
Definition at line 389 of file EnSystem.c.
Enumeration Type Documentation
FileAttr
enum FileAttr
Enumerator
DIRECTORY
File is directory.
HIDDEN
File is hidden.
READONLY
File is read-only.
INVALID
Invalid file.
Definition at line 505 of file EnSystem.c.
FileMode
enum FileMode
Enumerator
READ
WRITE
APPEND
Definition at line 382 of file EnSystem.c.
FindFileFlags
enum FindFileFlags
Definition at line 513 of file EnSystem.c.
Function Documentation
BeginParse()
proto native ParseHandle BeginParse (string filename)
CloseFile()
proto void CloseFile (FileHandle file)
Close the File.
Parameters
file File handle ID of a opened file
Returns
void
usage :
FileHandle file = OpenFile("$profile:testiik.txt", FileMode.WRITE);
if (file != 0)
{
    FPrintln(file, "line1");
    FPrintln(file, "line2");
    FPrintln(file, "line3");
    CloseFile(file);
}
Referenced by Debug::ClearLogs(), PluginRecipesManagerBase::GenerateHumanReadableRecipeList(), GetControlMappingInfo(), UIScriptedMenu::GetControlMappingInfo(), JsonFileLoader< Class T >::JsonLoadFile(), JsonFileLoader< Class T >::JsonSaveFile(), PluginBase::LoadFile(), UIScriptedMenu::ReloadOutput(), PluginBase::SaveFile(), and Debug::SaveLog().
CloseFindFile()
proto native void CloseFindFile (FindFileHandle handle)
CopyFile()
proto native bool CopyFile (string sourceName, string destName)
copy file. destName must be "$profile:" or "$saves:" location
Referenced by PluginBase::FileDuplicate().
DeleteFile()
proto native bool DeleteFile (string name)
delete file. Works only on "$profile:" and "$saves:" locations
Referenced by PluginBase::FileDelete().
EndParse()
proto native void EndParse (ParseHandle file)
FGets()
proto int FGets (FileHandle file, string var)
Get line from file, every next call of this function returns next line.
Parameters
file File handle ID of a opened file
var Value to write
Returns
int Count of chars or -1 if is not any for read (end of file is EMPTY line)
usage :
FileHandle file_handle = OpenFile("$profile:testiik.txt", FileMode.READ);
string line_content;
while (FGets(file_handle,  line_content) > 0)
{
    Print(line_content);
}
CloseFile(file_handle);
Referenced by GetControlMappingInfo(), UIScriptedMenu::GetControlMappingInfo(), JsonFileLoader< Class T >::JsonLoadFile(), PluginBase::LoadFile(), and UIScriptedMenu::ReloadOutput().
FileExist()
proto bool FileExist (string name)
Check existence of file.
Referenced by Debug::ClearLogs(), EffectAreaLoader::CreateZones(), UndergroundAreaLoader::GetData(), PluginConfigHandler::GetSceneList(), PluginLocalProfile::GetSceneList(), JsonFileLoader< Class T >::JsonLoadFile(), CfgGameplayHandler::LoadData(), UIScriptedMenu::LoadData(), ParticleList::RegisterParticle(), UIScriptedMenu::SaveData(), PluginConfigHandler::SceneDataLoad(), PluginConfigHandler::SceneDuplicate(), and ObjectSpawnerHandler::SpawnObjects().
FindFile()
enum FindFileFlags FindFile (string pattern, out string fileName, out FileAttr fileAttributes, FindFileFlags flags)
Referenced by UIScriptedWindow::GetMissionList(), PluginConfigHandler::GetSceneList(), and PluginLocalProfile::GetSceneList().
FindNextFile()
proto bool FindNextFile (FindFileHandle handle, out string fileName, out FileAttr fileAttributes)
Referenced by UIScriptedWindow::GetMissionList(), PluginConfigHandler::GetSceneList(), and PluginLocalProfile::GetSceneList().
FPrint()
proto void FPrint (FileHandle file, void var)
Write to file.
Parameters
file File handle ID of a opened file
var Value to write
Returns
void
usage :
FileHandle file = OpenFile("$profile:testiik.txt", FileMode.WRITE);
if (file != 0)
{
    FPrint(file, "A");
    FPrint(file, "B");
    FPrint(file, "C");
    CloseFile(file);
}
Referenced by JsonFileLoader< Class T >::JsonSaveFile().
FPrintln()
proto void FPrintln (FileHandle file, void var)
Write to file and add new line.
Parameters
file File handle ID of a opened file
var Value to write
Returns
void
usage :
FileHandle file = OpenFile("$profile:testiik.txt", FileMode.WRITE);
if (file != 0)
{
    FPrintln(file, "line1");
    FPrintln(file, "line2");
    FPrintln(file, "line3");
    CloseFile(file);
}
Referenced by Debug::ClearLogs(), PluginRecipesManagerBase::GenerateHumanReadableRecipeList(), PluginBase::SaveFile(), Debug::SaveLog(), and Canvas::SaveToFile().
MakeDirectory()
proto native bool MakeDirectory (string name)
Makes a directory.
Referenced by PluginConfigHandler::GetSceneList(), PluginLocalProfile::GetSceneList(), UIScriptedMenu::LoadData(), and UIScriptedMenu::SaveData().
OpenFile()
proto FileHandle OpenFile (string name, FileMode mode)
Opens File.
Parameters
name of a file to open, (you can use filesystem prefixes ('$profile','$saves','$mission'). For accessing profile dir use '$profile', e.g. '$profile:myFileName.txt')
mode constants FileMode.WRITE, FileMode.READ or FileMode.APPEND flag can be used
Returns
file handle ID or 0 if fails
usage :
FileHandle file = OpenFile("$profile:testiik.txt", FileMode.WRITE);
//FileHandle file = OpenFile("$profile:testiik.txt", FileMode.APPEND);
if (file != 0)
{
    FPrintln(file, "line1");
    FPrintln(file, "line2");
    FPrintln(file, "line3");
    CloseFile(file);
}
Referenced by Debug::ClearLogs(), PluginRecipesManagerBase::GenerateHumanReadableRecipeList(), GetControlMappingInfo(), UIScriptedMenu::GetControlMappingInfo(), JsonFileLoader< Class T >::JsonLoadFile(), JsonFileLoader< Class T >::JsonSaveFile(), PluginBase::LoadFile(), UIScriptedMenu::ReloadOutput(), PluginBase::SaveFile(), Debug::SaveLog(), and Canvas::SaveToFile().
ParseLine()
proto int ParseLine (ParseHandle tp, int num, string tokens[])
ReadFile()
proto int ReadFile (FileHandle file, void param_array, int length)
Reads raw data from file.
Parameters
param_array Receiving array for the data. Valid types are int[] or string
length Length of data
Returns
number of read bytes