DayZ Scripts: JsonMissionLoaderData Class Reference
JsonMissionLoaderData Class Reference
Static Private Member Functions
static JsonMissionLoaderData GetData ()
Private Attributes
ref TStringArray MissionPaths
Member Function Documentation
GetData()
static JsonMissionLoaderData GetData () inline static private
References CFG_FILE_MISSION_LIST, FileExist(), GetDayZGame(), MissionPaths, and path.
Referenced by Init().
Field Documentation
MissionPaths
ref TStringArray MissionPaths private
Referenced by GetData(), Init(), OnClick(), and OnDoubleClick().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptedWindows/MissionLoader.c