DayZ Scripts: CTObjectFollower Class Reference
CTObjectFollower Class Reference
Private Member Functions
void CTActor (int index, vector pos, vector orient, string type, array< string > items, string hands_item, CameraToolsMenu parent)
void ~CTActor ()
string GetActorType ()
void AddItem (string item)
void SetItems (array< string > items)
array< string > GetItems ()
void SetHandsItem (string item)
string GetHandsItem ()
void Reset ()
Private Attributes
protected int m_Index
protected Widget m_Root
protected TextWidget m_IndexWidget
protected string m_HandsItem
protected ref array< string > m_Items
protected EntityAI m_HandsItemObj
Constructor & Destructor Documentation
~CTActor()
void ~CTActor () inline private
Member Function Documentation
AddItem()
void AddItem (string item) inline private
CTActor()
void CTActor (int index, vector pos, vector orient, string type, array< string > items, string hands_item, CameraToolsMenu parent) inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Menu, m_Orientation, m_Position, SetHandsItem(), and SetItems().
Referenced by ScriptedWidgetEventHandler::OnMouseButtonDown().
GetActorType()
string GetActorType () inline private
GetHandsItem()
string GetHandsItem () inline private
References m_HandsItem.
GetItems()
array< string > GetItems () inline private
References m_Items.
Referenced by Reset().
Reset()
void Reset () inline private
References GetItems(), SetHandsItem(), and SetItems().
SetHandsItem()
void SetHandsItem (string item) inline private
References HumanInventory::CreateInHands(), GetGame(), HumanInventory::LocalDestroyEntity(), and CGame::ObjectDelete().
Referenced by CTActor(), and Reset().
SetItems()
void SetItems (array< string > items) inline private
Referenced by CTActor(), and Reset().
Field Documentation
m_HandsItem
protected string m_HandsItem private
Referenced by GetHandsItem().
m_HandsItemObj
protected EntityAI m_HandsItemObj private
m_Index
protected int m_Index private
m_IndexWidget
protected TextWidget m_IndexWidget private
m_Items
protected ref array<string> m_Items private
Referenced by GetItems().
m_Root
protected Widget m_Root private
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/CameraTools/CTActor.c