DayZ Scripts: ClaymoreMine Class Reference
ClaymoreMine Class Reference
Private Member Functions
void ClaymoreMine ()
override void EOnInit (IEntity other, int extra)
override void EEKilled (Object killer)
override void EEDelete (EntityAI parent)
override protected void InitiateExplosion ()
override void AfterStoreLoad ()
override void OnVariablesSynchronized ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
override void PairRemote (notnull EntityAI trigger)
override EntityAI GetPairDevice ()
override bool CanBeDisarmed ()
override void OnActivatedByItem (notnull ItemBase item)
override void OnArmed ()
override void OnDisarmed (bool pWithTool)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
protected void UpdateVisuals ()
protected void UpdateLED (ERemoteDetonatorLEDState pState, bool pForced=false)
override bool IsTakeable ()
override bool IsDeployable ()
override void SetActions ()
override int GetViewIndex ()
override protected bool UsesGlobalDeploy ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override void OnDebugSpawn ()
Private Attributes
protected const string ANIM_PHASE_PACKED = "Bag"
protected const string ANIM_PHASE_DEPLOYED = "Mine"
protected const string SELECTION_NAME_LED = "LED"
protected ref RemotelyActivatedItemBehaviour m_RAIB
protected ERemoteDetonatorLEDState m_LastLEDState
Constructor & Destructor Documentation
ClaymoreMine()
void ClaymoreMine () inline private
References ParticleList::CLAYMORE_EXPLOSION, m_RAIB, SetAmmoTypes(), SetParticleExplosion(), SetParticleOrientation(), and UpdateLED().
Member Function Documentation
AfterStoreLoad()
override void AfterStoreLoad () inline private
References GetArmed(), UpdateLED(), and UpdateVisuals().
CanBeDisarmed()
override bool CanBeDisarmed () inline private
References GetArmed().
EEDelete()
override void EEDelete (EntityAI parent) inline private
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
EEKilled()
override void EEKilled (Object killer) inline private
EOnInit()
override void EOnInit (IEntity other, int extra) inline private
References UpdateVisuals().
GetDeploySoundset()
override string GetDeploySoundset () inline private
GetLoopDeploySoundset()
override string GetLoopDeploySoundset () inline private
GetPairDevice()
override EntityAI GetPairDevice () inline private
References RemotelyActivatedItemBehaviour::GetPairDevice(), and m_RAIB.
Referenced by OnActivatedByItem().
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour () inline private
References m_RAIB.
GetViewIndex()
override int GetViewIndex () inline private
References GetArmed().
InitiateExplosion()
override protected void InitiateExplosion () inline private
References GetDefused().
IsDeployable()
override bool IsDeployable () inline private
IsTakeable()
override bool IsTakeable () inline private
References GetArmed().
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item) inline private
References GetArmed(), GetGame(), GetPairDevice(), RemotelyActivatedItemBehaviour::IsPaired(), and m_RAIB.
OnArmed()
override void OnArmed () inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), UpdateLED(), and UpdateVisuals().
OnDebugSpawn()
override void OnDebugSpawn () inline private
References Arm(), GetPosition, and PairWithDevice().
OnDisarmed()
override void OnDisarmed (bool pWithTool) inline private
References SetDefused(), UnpairRemote(), UpdateLED(), and UpdateVisuals().
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
References Arm(), GetGame(), PairWithDevice(), and RemoteDetonatorTrigger::SpawnInPlayerHands().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References m_RAIB, RemotelyActivatedItemBehaviour::OnVariableSynchronized(), and UpdateVisuals().
PairRemote()
override void PairRemote (notnull EntityAI trigger) inline private
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
SetActions()
override void SetActions () inline private
References ActionArmExplosive(), ActionDeployObject(), and AddAction().
UpdateLED()
protected void UpdateLED (ERemoteDetonatorLEDState pState, bool pForced = false) inline private
References m_LastLEDState, and SELECTION_NAME_LED.
Referenced by AfterStoreLoad(), ClaymoreMine(), OnArmed(), and OnDisarmed().
UpdateVisuals()
protected void UpdateVisuals () inline private
References ANIM_PHASE_DEPLOYED, ANIM_PHASE_PACKED, GetArmed(), and GetDefused().
Referenced by AfterStoreLoad(), EOnInit(), OnArmed(), OnDisarmed(), and OnVariablesSynchronized().
UsesGlobalDeploy()
override protected bool UsesGlobalDeploy () inline private
Field Documentation
ANIM_PHASE_DEPLOYED
protected const string ANIM_PHASE_DEPLOYED = "Mine" private
Referenced by UpdateVisuals().
ANIM_PHASE_PACKED
protected const string ANIM_PHASE_PACKED = "Bag" private
Referenced by UpdateVisuals().
m_LastLEDState
protected ERemoteDetonatorLEDState m_LastLEDState private
Referenced by UpdateLED().
m_RAIB
protected ref RemotelyActivatedItemBehaviour m_RAIB private
Referenced by ClaymoreMine(), EEItemLocationChanged(), GetPairDevice(), GetRemotelyActivatedItemBehaviour(), OnActivatedByItem(), OnVariablesSynchronized(), and PairRemote().
SELECTION_NAME_LED
protected const string SELECTION_NAME_LED = "LED" private
Referenced by UpdateLED().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ExplosivesBase/ClaymoreMine.c