DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionBuildOven.c File Reference
ActionBuildOven.c File Reference
Data Structures
class ActionBuildOvenCB
Functions
ActionBuildOvenCB ActionContinuousBaseCB ActionBuildOven ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
Function Documentation
ActionBuildOven()
ActionBuildOvenCB ActionContinuousBaseCB ActionBuildOven ()
Referenced by ActionConstructor::RegisterActions(), and FireplaceBase::SetActions().
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
References FireplaceBase::IsBaseFireplace().
CreateActionComponent()
override void CreateActionComponent ()
References m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
CreateConditionComponents()
override void CreateConditionComponents ()
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType ()
HasProgress()
override bool HasProgress ()
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
References ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.