DayZ Scripts: HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase > Class Reference
HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase > Class Reference
Private Member Functions
protected void SetInternalID (WeaponStateBase state)
unique list of states in this machine (automation of save/load)
override void AddTransition (FSMTransition< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase > t)
adds transition into transition table As a side effect registers the state(s) into m_UniqueStates
override protected ProcessEventResult ProcessLocalTransition (FSMTransition< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase > t, WeaponEventBase e)
override protected ProcessEventResult ProcessAbortTransition (FSMTransition< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase > t, WeaponEventBase e)
override WeaponStateBase ProcessAbortEvent (WeaponEventBase e, out ProcessEventResult result)
override ProcessEventResult ProcessEvent (WeaponEventBase e)
WeaponStateBase FindStateForInternalID (int id)
retrieve base state that matches given internal id
WeaponStableState FindStableStateForID (int id)
load from database - reverse lookup for state from saved id
protected bool LoadAndSetCurrentFSMState (ParamsReadContext ctx, int version)
bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
load current state of fsm
bool LoadCurrentUnstableFSMState (ParamsWriteContext ctx, int version)
bool SaveCurrentFSMState (ParamsWriteContext ctx)
save current state of fsm
bool SaveCurrentUnstableFSMState (ParamsWriteContext ctx)
void ValidateAndRepair ()
validate the state of the gun and repair if mismatch
protected bool Internal_ValidateAndRepair ()
validate the state of the gun and repair if mismatch
protected bool ValidateAndRepairHelper (Weapon_Base weapon, string name, bool stateCondition, bool gunCondition, WeaponEventBase e1, WeaponEventBase e2, out WeaponStableState state)
protected void OnFailThresholdBreached (Weapon weapon, string name, bool stateCondition, bool gunCondition)
protected WeaponStableState ValidateAndRepairStateFinder (bool condition, WeaponEventBase e1, WeaponEventBase e2, WeaponStableState state)
bool OnStoreLoad (ParamsReadContext ctx, int version)
load state of fsm
int GetCurrentStableStateID ()
int GetInternalStateID ()
void OnStoreSave (ParamsWriteContext ctx)
save state of fsm
void RandomizeFSMState (bool hasBullet, bool hasMagazine, bool isJammed)
Deprecated, use RandomizeFSMStateEx for better results.
void RandomizeFSMStateEx (array< MuzzleState > muzzleStates, bool hasMagazine, bool isJammed)
With the parameters given, selects a random suitable state for the FSM of the weapon @NOTE: It is better to use Weapon_Base.RandomizeFSMState instead of calling this one @WARNING: Weapon_Base.Synchronize call might be needed, if this method is called while clients are connected.
Private Attributes
private int m_SynchronizeAttempts
private int m_LastSynchronizeTime
protected int m_NextStateId = 0
protected ref array< WeaponStateBase > m_UniqueStates = new array<WeaponStateBase>
counter for InternalID: each state in a fsm is assigned an unique number
Static Private Attributes
static private const int MAX_SYNCHRONIZE_ATTEMPTS = 12
static private const int MIN_SYNCHRONIZE_INTERVAL = 3000
static private const int RESET_SYNCHRONIZE_THRESHOLD = 3600000
Member Function Documentation
AddTransition()
AddTransition (FSMTransition< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase > t) inline private
adds transition into transition table As a side effect registers the state(s) into m_UniqueStates
FindStableStateForID()
FindStableStateForID (int id) inline private
load from database - reverse lookup for state from saved id
Parameters
[in] id the id stored in database during save
References WeaponStableState::GetCurrentStateID().
FindStateForInternalID()
FindStateForInternalID (int id) inline private
retrieve base state that matches given internal id
Parameters
[in] id the id stored in database during save
References WeaponStateBase::GetInternalStateID().
GetCurrentStableStateID()
int GetCurrentStableStateID () inline private
References WeaponStableState::GetCurrentStateID(), and Print().
GetInternalStateID()
int GetInternalStateID () inline private
References WeaponStateBase::GetInternalStateID().
Internal_ValidateAndRepair()
Internal_ValidateAndRepair () inline private
validate the state of the gun and repair if mismatch
Returns
bool whether it performed repairing or not
References WeaponStableState::HasMagazine(), WeaponStableState::IsJammed(), WeaponStableState::IsRepairEnabled(), and m_State.
LoadAndSetCurrentFSMState()
protected bool LoadAndSetCurrentFSMState (ParamsReadContext ctx, int version) inline private
References Error(), LogManager::IsWeaponLogEnable(), m_State, Serializer::Read(), Start(), and wpnDebugPrint().
LoadCurrentFSMState()
LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
load current state of fsm
References LogManager::IsWeaponLogEnable(), m_State, and wpnDebugSpam().
LoadCurrentUnstableFSMState()
bool LoadCurrentUnstableFSMState (ParamsWriteContext ctx, int version) inline private
References Error(), LogManager::IsWeaponLogEnable(), and wpnDebugSpam().
OnFailThresholdBreached()
protected void OnFailThresholdBreached (Weapon weapon, string name, bool stateCondition, bool gunCondition) inline private
References Error(), m_State, and name.
OnStoreLoad()
OnStoreLoad (ParamsReadContext ctx, int version) inline private
load state of fsm
References LogManager::IsWeaponLogEnable(), m_State, Print(), Serializer::Read(), Start(), and wpnDebugPrint().
OnStoreSave()
OnStoreSave (ParamsWriteContext ctx) inline private
save state of fsm
References LogManager::IsWeaponLogEnable(), wpnDebugSpamALot(), and Serializer::Write().
ProcessAbortEvent()
override WeaponStateBase ProcessAbortEvent (WeaponEventBase e, out ProcessEventResult result) inline private
References fsmDebugPrint(), WeaponStateBase::GetParentState(), LogManager::IsInventoryHFSMLogEnable(), m_State, ToString(), float::ToString(), and Type.
ProcessAbortTransition()
override protected ProcessEventResult ProcessAbortTransition (FSMTransition< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase > t, WeaponEventBase e) inline private
References fsmDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), and m_State.
ProcessEvent()
override ProcessEventResult ProcessEvent (WeaponEventBase e) inline private
References WeaponEventBase::DumpToString(), Error(), fsmDebugPrint(), fsmDebugSpam(), LogManager::IsInventoryHFSMLogEnable(), LogManager::IsWeaponLogEnable(), m_State, ToString(), float::ToString(), and Type.
ProcessLocalTransition()
override protected ProcessEventResult ProcessLocalTransition (FSMTransition< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase > t, WeaponEventBase e) inline private
References fsmDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), and m_State.
RandomizeFSMState()
RandomizeFSMState (bool hasBullet, bool hasMagazine, bool isJammed) inline private
Deprecated, use RandomizeFSMStateEx for better results.
RandomizeFSMStateEx()
RandomizeFSMStateEx (array< MuzzleState > muzzleStates, bool hasMagazine, bool isJammed) inline private
With the parameters given, selects a random suitable state for the FSM of the weapon @NOTE: It is better to use Weapon_Base.RandomizeFSMState instead of calling this one @WARNING: Weapon_Base.Synchronize call might be needed, if this method is called while clients are connected.
References ErrorEx, WeaponStableState::GetCurrentStateID(), WeaponStableState::HasMagazine(), WeaponStableState::IsJammed(), LogManager::IsWeaponLogEnable(), m_State, Math::RandomInt(), Start(), and wpnDebugPrint().
SaveCurrentFSMState()
SaveCurrentFSMState (ParamsWriteContext ctx) inline private
save current state of fsm
References Error(), WeaponStateBase::GetInternalStateID(), LogManager::IsWeaponLogEnable(), WeaponStateBase::SaveCurrentFSMState(), wpnDebugPrint(), and Serializer::Write().
SaveCurrentUnstableFSMState()
bool SaveCurrentUnstableFSMState (ParamsWriteContext ctx) inline private
References Error(), WeaponStateBase::GetInternalStateID(), LogManager::IsWeaponLogEnable(), wpnDebugPrint(), wpnDebugSpam(), and Serializer::Write().
SetInternalID()
protected void SetInternalID (WeaponStateBase state) inline private
unique list of states in this machine (automation of save/load)
References WeaponStateBase::GetInternalStateID(), and WeaponStateBase::SetInternalStateID().
ValidateAndRepair()
ValidateAndRepair () inline private
validate the state of the gun and repair if mismatch
ValidateAndRepairHelper()
protected bool ValidateAndRepairHelper (Weapon_Base weapon, string name, bool stateCondition, bool gunCondition, WeaponEventBase e1, WeaponEventBase e2, out WeaponStableState state) inline private
References Error(), g_Game, LogManager::IsWeaponLogEnable(), m_State, name, Start(), and wpnDebugPrint().
ValidateAndRepairStateFinder()
protected WeaponStableState ValidateAndRepairStateFinder (bool condition, WeaponEventBase e1, WeaponEventBase e2, WeaponStableState state) inline private
Field Documentation
m_LastSynchronizeTime
private int m_LastSynchronizeTime private
m_NextStateId
protected int m_NextStateId = 0 private
m_SynchronizeAttempts
private int m_SynchronizeAttempts private
m_UniqueStates
protected ref array<WeaponStateBase> m_UniqueStates = new array<WeaponStateBase> private
counter for InternalID: each state in a fsm is assigned an unique number
MAX_SYNCHRONIZE_ATTEMPTS
private const int MAX_SYNCHRONIZE_ATTEMPTS = 12 static private
MIN_SYNCHRONIZE_INTERVAL
private const int MIN_SYNCHRONIZE_INTERVAL = 3000 static private
RESET_SYNCHRONIZE_THRESHOLD
private const int RESET_SYNCHRONIZE_THRESHOLD = 3600000 static private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Firearms/WeaponFSM.c