DayZ Scripts: HandStateBase Class Reference
HandStateBase Class Reference
represent hand state base
Private Member Functions
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
waiting for active animation action/actionType finish
void HandAnimatedForceSwapping (Man player=null, HandStateBase parent=null)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
void HandAnimatedForceSwapping_Inst (Man player=null, HandStateBase parent=null)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
void HandAnimatedMovingToAtt (Man player=null, HandStateBase parent=null)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
void HandAnimatedSwapping (Man player=null, HandStateBase parent=null)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
void HandAnimatedTakingFromAtt (Man player=null, HandStateBase parent=null)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
void HandStartReplacingItemElsewhereWithNewInHands (Man player=NULL, HandStateBase parent=NULL)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
void HandReplacingItemElsewhereWithNewInHands (Man player=NULL, HandStateBase parent=NULL)
void HandStartReplacingItemInHands (Man player=NULL, HandStateBase parent=NULL)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
void HandReplacingItemInHands (Man player=NULL, HandStateBase parent=NULL)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
void HandStableState (Man player=NULL, HandStateBase parent=NULL, int anim_state=-1)
void SyncAnimState ()
override void OnEntry (HandEventBase e)
override void OnUpdate (float dt)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsIdle ()
idle state does not expect any animation events
int GetCurrentStateID ()
bool HasEntityInHands ()
query for entity in hands
void HandStartAction (Man player=NULL, HandStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
specific action sub-type
override void OnEntry (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsIdle ()
void HandStateBase (Man player=NULL, HandStateBase parent=NULL)
nested state machine (or null)
void SetParentState (HandStateBase parent)
allows construction of hierarchical state machine
HandStateBase GetParentState ()
bool HasFSM ()
HandFSM GetFSM ()
bool ProcessEvent (HandEventBase e)
void AddTransition (HandTransition t)
adds transition into m_FSM transition table
void OnEntry (HandEventBase e)
void OnUpdate (float dt)
void OnAbort (HandEventBase e)
void OnExit (HandEventBase e)
bool IsWaitingForActionFinish ()
bool IsIdle ()
void OnSubMachineChanged (HandStateBase src, HandStateBase dst)
called when sub-machine has changed its state
void OnStateChanged (HandStateBase src, HandStateBase dst)
called on current state when state machine has changed its state
Private Attributes
ref InventoryLocation m_Dst
ref InventoryLocation m_Src1 = null
ref InventoryLocation m_Src2 = null
ref InventoryLocation m_Dst1 = null
ref InventoryLocation m_Dst2 = null
ref HandStartHidingAnimated m_Start
ref HandAnimatedMoveToDst_W4T m_Show
ref HandAnimatedMoveToDst_W4T_Basic m_Hide
ref HandForceSwappingAnimated_Show m_Swap
EntityAI m_Entity
ref HandStartHidingAnimated m_Hide
weapon to be taken
ref InventoryLocation m_ilEntity
ref HandSwappingAnimated_Show m_Show
ref HandTakingAnimated_Hide m_Hide
ref HandTakingAnimated_Show m_Show
ref HandStartReplacingItemElsewhereWithNewInHands m_Replacing
ref HandStartReplacingItemInHands m_Replacing
int m_AnimState
WeaponActions m_Action
int m_ActionType
action to be played
Man m_Player
HandStateBase m_parentState
entity that this state relates to
ref HandFSM m_FSM
hierarchical parent state of this state (or null)
Detailed Description
represent hand state base
Class comes with entry/update/exit hooks that can be overriden in custom states
Constructor & Destructor Documentation
HandStateBase()
void HandStateBase (Man player = NULL, HandStateBase parent = NULL) inline private
nested state machine (or null)
References m_parentState, and m_Player.
Member Function Documentation
AddTransition()
AddTransition (HandTransition t) inline private
adds transition into m_FSM transition table
References Error(), HasFSM(), and m_FSM.
GetCurrentStateID()
int GetCurrentStateID () inline private
GetFSM()
HandFSM GetFSM () inline private
References m_FSM.
GetParentState()
GetParentState () inline private
Returns
state that owns this sub-state (or null if plain state)
References m_parentState.
HandAnimatedForceSwapping()
void HandAnimatedForceSwapping (Man player = null, HandStateBase parent = null) inline private
HandAnimatedForceSwapping_Inst()
void HandAnimatedForceSwapping_Inst (Man player = null, HandStateBase parent = null) inline private
HandAnimatedMovingToAtt()
void HandAnimatedMovingToAtt (Man player = null, HandStateBase parent = null) inline private
HandAnimatedSwapping()
void HandAnimatedSwapping (Man player = null, HandStateBase parent = null) inline private
HandAnimatedTakingFromAtt()
void HandAnimatedTakingFromAtt (Man player = null, HandStateBase parent = null) inline private
HandReplacingItemElsewhereWithNewInHands()
void HandReplacingItemElsewhereWithNewInHands (Man player = NULL, HandStateBase parent = NULL) inline private
References HandStartReplacingItemElsewhereWithNewInHands().
HandReplacingItemInHands()
void HandReplacingItemInHands (Man player = NULL, HandStateBase parent = NULL) inline private
References HandStartReplacingItemInHands().
HandStableState()
void HandStableState (Man player = NULL, HandStateBase parent = NULL, int anim_state = -1) inline private
HandStartAction()
void HandStartAction (Man player = NULL, HandStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
specific action sub-type
References m_Action.
HandStartReplacingItemElsewhereWithNewInHands()
void HandStartReplacingItemElsewhereWithNewInHands (Man player = NULL, HandStateBase parent = NULL) inline private
Referenced by HandReplacingItemElsewhereWithNewInHands().
HandStartReplacingItemInHands()
void HandStartReplacingItemInHands (Man player = NULL, HandStateBase parent = NULL) inline private
Referenced by HandReplacingItemInHands().
HasEntityInHands()
bool HasEntityInHands () inline private
query for entity in hands
HasFSM()
bool HasFSM () inline private
References m_FSM.
Referenced by AddTransition(), IsWaitingForActionFinish(), OnAbort(), OnEntry(), OnUpdate(), and ProcessEvent().
IsIdle() [1/3]
IsIdle () inline private
idle state does not expect any animation events
Returns
true if this state is idle
Referenced by OnHandsStateChanged().
IsIdle() [2/3]
override bool IsIdle () inline private
IsIdle() [3/3]
bool IsIdle () inline private
IsWaitingForActionFinish() [1/4]
IsWaitingForActionFinish () inline private
waiting for active animation action/actionType finish
Returns
true if this state is waiting for finish signal
IsWaitingForActionFinish() [2/4]
override bool IsWaitingForActionFinish () inline private
IsWaitingForActionFinish() [3/4]
override bool IsWaitingForActionFinish () inline private
IsWaitingForActionFinish() [4/4]
bool IsWaitingForActionFinish () inline private
References HasFSM(), and m_FSM.
OnAbort() [1/11]
override void OnAbort (HandEventBase e) inline private
OnAbort() [2/11]
override void OnAbort (HandEventBase e) inline private
References CGame::ClearJuncture(), and GetGame().
OnAbort() [3/11]
override void OnAbort (HandEventBase e) inline private
References CGame::ClearJuncture(), and GetGame().
OnAbort() [4/11]
override void OnAbort (HandEventBase e) inline private
References CGame::ClearJunctureEx(), GetGame(), and m_Entity.
OnAbort() [5/11]
override void OnAbort (HandEventBase e) inline private
References CGame::ClearJuncture(), and GetGame().
OnAbort() [6/11]
override void OnAbort (HandEventBase e) inline private
References CGame::ClearJuncture(), GetGame(), Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
OnAbort() [7/11]
override void OnAbort (HandEventBase e) inline private
OnAbort() [8/11]
override void OnAbort (HandEventBase e) inline private
OnAbort() [9/11]
override void OnAbort (HandEventBase e) inline private
OnAbort() [10/11]
override void OnAbort (HandEventBase e) inline private
OnAbort() [11/11]
void OnAbort (HandEventBase e) inline private
References HasFSM(), hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), m_FSM, ToString(), and Type.
OnEntry() [1/12]
override void OnEntry (HandEventBase e) inline private
References Error(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationCanMoveEntity(), and GameInventory::LocationSyncMoveEntity().
OnEntry() [2/12]
override void OnEntry (HandEventBase e) inline private
References GameInventory::c_InventoryReservationTimeoutShortMS, GetGame(), m_Dst1, and m_Dst2.
OnEntry() [3/12]
override void OnEntry (HandEventBase e) inline private
References GameInventory::c_InventoryReservationTimeoutShortMS, GetGame(), m_Dst1, m_Dst2, m_Src1, and m_Src2.
OnEntry() [4/12]
override void OnEntry (HandEventBase e) inline private
References GameInventory::c_InventoryReservationTimeoutShortMS, HandEventBase::m_Dst, and m_Entity.
OnEntry() [5/12]
override void OnEntry (HandEventBase e) inline private
References GameInventory::c_InventoryReservationTimeoutShortMS, GetGame(), m_Dst1, m_Dst2, m_Src1, and m_Src2.
OnEntry() [6/12]
override void OnEntry (HandEventBase e) inline private
References GameInventory::c_InventoryReservationTimeoutShortMS, HandEventBase::GetDst(), and HandEventBase::m_Dst.
OnEntry() [7/12]
override void OnEntry (HandEventBase e) inline private
References Error(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
OnEntry() [8/12]
override void OnEntry (HandEventBase e) inline private
References Error(), HumanInventory::GetEntityInHands(), EntityAI::GetHumanInventory(), hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
OnEntry() [9/12]
override void OnEntry (HandEventBase e) inline private
OnEntry() [10/12]
override void OnEntry (HandEventBase e) inline private
References SyncAnimState().
OnEntry() [11/12]
override void OnEntry (HandEventBase e) inline private
References Error(), HumanCommandWeapons::GetRunningAction(), HumanCommandWeapons::GetRunningActionType(), hndDebugPrint(), HumanCommandWeapons::IsActionFinished(), LogManager::IsInventoryHFSMLogEnable(), m_Action, HumanCommandWeapons::StartAction(), and WeaponActionTypeToString().
OnEntry() [12/12]
void OnEntry (HandEventBase e) inline private
References HasFSM(), hndDebugPrint(), LogManager::IsInventoryHFSMLogEnable(), m_FSM, ToString(), and Type.
OnExit() [1/12]
override void OnExit (HandEventBase e) inline private
OnExit() [2/12]
override void OnExit (HandEventBase e) inline private
References CGame::ClearJuncture(), and GetGame().
OnExit() [3/12]
override void OnExit (HandEventBase e) inline private
References CGame::ClearJuncture(), and GetGame().
OnExit() [4/12]
override void OnExit (HandEventBase e) inline private
References GetGame(), and m_Entity.
OnExit() [5/12]
override void OnExit (HandEventBase e) inline private
References GetGame().
OnExit() [6/12]
override void OnExit (HandEventBase e) inline private
OnExit() [7/12]
override void OnExit (HandEventBase e) inline private
OnExit() [8/12]
override void OnExit (HandEventBase e) inline private
OnExit() [9/12]
override void OnExit (HandEventBase e) inline private
OnExit() [10/12]
override void OnExit (HandEventBase e) inline private
OnExit() [11/12]
override void OnExit (HandEventBase e) inline private
OnExit() [12/12]
void OnExit (HandEventBase e) inline private
References hndDebugPrint(), and LogManager::IsInventoryHFSMLogEnable().
OnStateChanged()
OnStateChanged (HandStateBase src, HandStateBase dst) inline private
called on current state when state machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
References m_Player.
OnSubMachineChanged()
OnSubMachineChanged (HandStateBase src, HandStateBase dst) inline private
called when sub-machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
OnUpdate() [1/2]
override void OnUpdate (float dt) inline private
References SyncAnimState().
OnUpdate() [2/2]
void OnUpdate (float dt) inline private
References HasFSM(), and m_FSM.
ProcessEvent()
bool ProcessEvent (HandEventBase e) inline private
References HasFSM(), and m_FSM.
SetParentState()
SetParentState (HandStateBase parent) inline private
allows construction of hierarchical state machine
References m_parentState.
SyncAnimState()
void SyncAnimState () inline private
Field Documentation
m_Action
WeaponActions m_Action private
m_ActionType
int m_ActionType private
action to be played
m_AnimState
int m_AnimState private
m_Dst
ref InventoryLocation m_Dst private
m_Dst1
ref InventoryLocation m_Dst1 = null private
Referenced by OnEntry().
m_Dst2
ref InventoryLocation m_Dst2 = null private
Referenced by OnEntry().
m_Entity
EntityAI m_Entity private
m_FSM
ref HandFSM m_FSM private
hierarchical parent state of this state (or null)
Referenced by AddTransition(), GetFSM(), HasFSM(), IsWaitingForActionFinish(), OnAbort(), OnEntry(), OnUpdate(), and ProcessEvent().
m_Hide [1/3]
ref HandStartHidingAnimated m_Hide private
m_Hide [2/3]
ref HandStartHidingAnimated m_Hide private
weapon to be taken
m_Hide [3/3]
ref HandTakingAnimated_Hide m_Hide private
m_ilEntity
ref InventoryLocation m_ilEntity private
m_parentState
HandStateBase m_parentState private
entity that this state relates to
Referenced by GetParentState(), HandStateBase(), and SetParentState().
m_Player
Man m_Player private
Referenced by HandStateBase(), and OnStateChanged().
m_Replacing [1/2]
ref HandStartReplacingItemElsewhereWithNewInHands m_Replacing private
m_Replacing [2/2]
ref HandStartReplacingItemInHands m_Replacing private
m_Show [1/3]
ref HandAnimatedMoveToDst_W4T m_Show private
m_Show [2/3]
ref HandSwappingAnimated_Show m_Show private
m_Show [3/3]
ref HandTakingAnimated_Show m_Show private
m_Src1
ref InventoryLocation m_Src1 = null private
Referenced by OnEntry().
m_Src2
ref InventoryLocation m_Src2 = null private
Referenced by OnEntry().
m_Start
ref HandStartHidingAnimated m_Start private
m_Swap
ref HandForceSwappingAnimated_Show m_Swap private
The documentation for this class was generated from the following files:
3_Game/Systems/Inventory/HandAnimatedForceSwapping.c
3_Game/Systems/Inventory/HandAnimatedMovingToAtt.c
3_Game/Systems/Inventory/HandAnimatedSwapping.c
3_Game/Systems/Inventory/HandAnimatedTakingFromAtt.c
3_Game/Systems/Inventory/HandReplacingItemElsewhereWithNewInHands.c
3_Game/Systems/Inventory/HandReplacingItemInHands.c
3_Game/Systems/Inventory/HandStableState.c
3_Game/Systems/Inventory/HandStartAction.c
3_Game/Systems/Inventory/HandStateBase.c