DayZ Scripts: ToggleLightsActionInput Class Reference
ToggleLightsActionInput Class Reference
Private Member Functions
void ToggleLightsActionInput (PlayerBase player)
override void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask)
override ActionBase GetAction ()
Private Attributes
ref ActionTarget target_new
Constructor & Destructor Documentation
ToggleLightsActionInput()
void ToggleLightsActionInput (PlayerBase player) inline private
References m_Priority, and SetInput().
Member Function Documentation
GetAction()
override ActionBase GetAction () inline private
References m_SelectAction.
UpdatePossibleActions()
override void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask) inline private
References ActionBase(), ActionTarget, Clothing::GetLightSourceItem(), HumanCommandVehicle::GetTransport(), m_MainItem, m_SelectAction, m_Target, target_new, Type, and vector::Zero.
Field Documentation
target_new
ref ActionTarget target_new private
Referenced by UpdatePossibleActions().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionInput.c