DayZ Scripts: ActionUnrestrainTargetCB Class Reference
ActionUnrestrainTargetCB Class Reference
Private Member Functions
override void CreateActionComponent ()
float ObtainUnrestrainTime ()
Private Attributes
const float DEFAULT_UNRESTRAIN_TIME = 2
Member Function Documentation
CreateActionComponent()
override void CreateActionComponent () inline private
References DEBUG_QUICK_UNRESTRAIN_TIME, DEFAULT_UNRESTRAIN_TIME, ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, ActionData::m_Player, and ObtainUnrestrainTime().
ObtainUnrestrainTime()
float ObtainUnrestrainTime () inline private
References CachedObjectsArrays::ARRAY_STRING, class_name, GetGame(), ActionBaseCB::m_ActionData, ActionData::m_Player, and ActionData::m_Target.
Referenced by CreateActionComponent().
Field Documentation
DEFAULT_UNRESTRAIN_TIME
const float DEFAULT_UNRESTRAIN_TIME = 2 private
Referenced by CreateActionComponent().
The documentation for this class was generated from the following file:
P:/scripts/4_world/classes/useractionscomponent/actions/continuous/actionunrestraintarget.c