DayZ Scripts: ActionTakeArrow Class Reference
ActionTakeArrow Class Reference
Private Member Functions
void ActionTakeArrow ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override Object GetDisplayInteractObject (PlayerBase player, ActionTarget target)
override bool CanBeUsedOnBack ()
override bool InventoryReservation (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Constructor & Destructor Documentation
ActionTakeArrow()
void ActionTakeArrow () inline private
References AnimatedActionBase::m_CommandUID, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References ArrowManagerBase::GetFirstArrow().
CanBeUsedOnBack()
override bool CanBeUsedOnBack () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetDisplayInteractObject()
override Object GetDisplayInteractObject (PlayerBase player, ActionTarget target) inline private
References ArrowManagerBase::GetFirstArrow().
InventoryReservation()
override bool InventoryReservation (ActionData action_data) inline private
References GameInventory::c_InventoryReservationTimeoutMS, ArrowManagerBase::GetFirstArrow(), ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
References InventoryLocation::GetItem(), InventoryLocation::GetSlot(), ActionData::m_Player, and ActionData::m_ReservedInventoryLocations.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
References GetGame(), InventoryLocation::GetItem(), ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionTakeArrow.c