DayZ Scripts: CargoGrid Class Reference
CargoGrid Class Reference
Private Member Functions
proto native EntityAI FindEntityInCargoOn (int row, int col)
Member Function Documentation
FindEntityInCargoOn()
FindEntityInCargoOn (int row, int col) private
Returns
get item at coordinates (row, col). col is 0 on xbox.
Referenced by CargoContainerRow::GetIconSize(), CargoContainerRow::SetFocus(), and CargoContainerRow::UnfocusAll().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/Inventory/Cargo.c