DayZ Scripts: StaminaHandler Class Reference
StaminaHandler Class Reference
Private Member Functions
void StaminaHandler (PlayerBase player)
void Init ()
void ActivateDepletionModifier (EStaminaMultiplierTypes type)
void DeactivateDepletionModifier (EStaminaMultiplierTypes type)
void RecalculateDepletionMultiplier ()
void ActivateRecoveryModifier (EStaminaMultiplierTypes type)
void DeactivateRecoveryModifier (EStaminaMultiplierTypes type)
void RecalculateRecoveryMultiplier ()
void Update (float deltaT, int pCurrentCommandID)
void OnRPC (float stamina, float stamina_cap, bool cooldown)
deprecated use, StaminaHandler uses SyncJunctures now
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
called from PlayerBase - syncs stamina values on server with client AND sets the value to match on server and client both (m_StaminaSynced guarantees identical values)
protected void StaminaProcessor_Move (HumanMovementState pHumanMovementState)
protected void StaminaProcessor_Ladder (HumanMovementState pHumanMovementState)
protected void StaminaProcessor_Swimming (HumanMovementState pHumanMovementState)
protected void SyncStamina (float stamina, float stamina_cap, bool cooldown)
stamina sync - server part
protected void SyncAdditionalStaminaInfo (Param par)
Method to sync more info for stamina manager. Template parameter means it is very extendable for further use.
protected void ReadAdditionalStaminaInfo (ParamsReadContext pCtx)
Order of read parameters must match the order of writing above.
protected void RegisterStaminaConsumers ()
protected void RegisterStaminaModifiers ()
protected float CalcStaminaGainBonus ()
Calulates stamina regain bonus coef based on current stamina cap and level.
protected void ApplyExhaustion ()
protected void CheckStaminaState ()
check if the stamina is completely depleted
protected void SetCooldown (float time, int modifier=-1)
set cooldown timer between each consume of stamina
protected void ResetCooldown (int modifier=-1)
Timer GetCooldownTimer (int modifier)
bool HasEnoughStaminaFor (EStaminaConsumers consumer)
bool HasEnoughStaminaToStart (EStaminaConsumers consumer)
void SetStamina (float stamina_value)
float GetStamina ()
float GetStaminaNormalized ()
float GetSyncedStamina ()
float GetSyncedStaminaNormalized ()
float GetStaminaCap ()
float GetStaminaMax ()
void SetDepletionMultiplier (float val)
void SetRecoveryMultiplier (float val)
float GetDepletionMultiplier ()
float GetRecoveryMultiplier ()
void DepleteStamina (EStaminaModifiers modifier, float dT=-1)
Private Attributes
protected float m_PlayerLoad
protected float m_StaminaDelta
protected float m_Stamina
protected float m_StaminaSynced
protected float m_StaminaCap
protected float m_StaminaDepletion
protected float m_StaminaDepletionMultiplier
protected float m_StaminaRecoveryMultiplier
protected float m_Time
protected ref Param3< float, float, bool > m_StaminaParams
protected ref HumanMovementState m_State
protected SHumanCommandMoveSettings m_HumanMoveSettings
protected PlayerBase m_Player
protected bool m_Debug
protected bool m_StaminaDepleted
DEPRECATED.
protected ref map< int, ref Timer > m_TimerMap
ref map< EStaminaMultiplierTypes, float > m_RegisteredDepletionModifiers
ref set< EStaminaMultiplierTypes > m_ActiveDepletionModifiers
ref map< EStaminaMultiplierTypes, float > m_RegisteredRecoveryModifiers
ref set< EStaminaMultiplierTypes > m_ActiveRecoveryModifiers
protected bool m_IsInCooldown
protected ref StaminaConsumers m_StaminaConsumers
protected ref StaminaModifiers m_StaminaModifiers
Constructor & Destructor Documentation
StaminaHandler()
void StaminaHandler (PlayerBase player) inline private
References GetGame(), CfgGameplayHandler::GetStaminaMax(), Init(), m_ActiveDepletionModifiers, m_ActiveRecoveryModifiers, m_HumanMoveSettings, m_IsInCooldown, m_Player, m_RegisteredDepletionModifiers, m_RegisteredRecoveryModifiers, m_Stamina, m_StaminaCap, m_StaminaDepleted, m_StaminaDepletion, m_StaminaDepletionMultiplier, m_StaminaParams, m_StaminaRecoveryMultiplier, m_State, m_Time, m_TimerMap, RegisterStaminaConsumers(), and RegisterStaminaModifiers().
Member Function Documentation
ActivateDepletionModifier()
void ActivateDepletionModifier (EStaminaMultiplierTypes type) inline private
References Error(), m_ActiveDepletionModifiers, m_RegisteredDepletionModifiers, and RecalculateDepletionMultiplier().
ActivateRecoveryModifier()
void ActivateRecoveryModifier (EStaminaMultiplierTypes type) inline private
References Error(), m_ActiveRecoveryModifiers, m_RegisteredRecoveryModifiers, and RecalculateRecoveryMultiplier().
ApplyExhaustion()
protected void ApplyExhaustion () inline private
sets exhaustion look of player based on stamina level
References HumanCommandAdditives(), m_Player, m_Stamina, m_StaminaCap, and Math::Min().
Referenced by Update().
CalcStaminaGainBonus()
protected float CalcStaminaGainBonus () inline private
Calulates stamina regain bonus coef based on current stamina cap and level.
References m_Stamina, m_StaminaDepletion, Math::Min(), and GameConstants::STAMINA_GAIN_BONUS_CAP.
Referenced by StaminaProcessor_Ladder(), StaminaProcessor_Move(), and StaminaProcessor_Swimming().
CheckStaminaState()
protected void CheckStaminaState () inline private
check if the stamina is completely depleted
in case of complete depletion - start a cooldown timer before the regeneration cycle start
References m_IsInCooldown, m_Stamina, m_StaminaDepleted, SetCooldown(), and GameConstants::STAMINA_REGEN_COOLDOWN_EXHAUSTION.
Referenced by Update().
DeactivateDepletionModifier()
void DeactivateDepletionModifier (EStaminaMultiplierTypes type) inline private
References m_ActiveDepletionModifiers, and RecalculateDepletionMultiplier().
DeactivateRecoveryModifier()
void DeactivateRecoveryModifier (EStaminaMultiplierTypes type) inline private
References m_ActiveRecoveryModifiers, and RecalculateRecoveryMultiplier().
DepleteStamina()
void DepleteStamina (EStaminaModifiers modifier, float dT = -1) inline private
run cooldown right after depletion
References Math::AbsFloat(), Class::CastTo(), Math::Clamp(), ErrorEx, StaminaModifierExponential::GetBaseValue(), StaminaModifierExponential::GetDurationAdjusted(), StaminaModifierExponential::GetExponent(), StaminaModifierExponential::GetMultiplier(), CfgGameplayHandler::GetStaminaMax(), StaminaModifierExponential::GetStartTimeAdjustment(), Math::Lerp(), m_Player, m_StaminaDepletion, m_StaminaDepletionMultiplier, m_StaminaModifiers, Math::Max(), Math::Min(), Math::Pow(), Math::RandomFloat(), SetCooldown(), and StaminaModifier().
GetCooldownTimer()
Timer GetCooldownTimer (int modifier) inline private
GetDepletionMultiplier()
float GetDepletionMultiplier () inline private
References m_StaminaDepletionMultiplier.
GetRecoveryMultiplier()
float GetRecoveryMultiplier () inline private
References m_StaminaRecoveryMultiplier.
GetStamina()
float GetStamina () inline private
References m_Stamina.
GetStaminaCap()
float GetStaminaCap () inline private
References m_StaminaCap.
GetStaminaMax()
float GetStaminaMax () inline private
References CfgGameplayHandler::GetStaminaMax().
Referenced by GetStaminaNormalized(), and GetSyncedStaminaNormalized().
GetStaminaNormalized()
float GetStaminaNormalized () inline private
References GetStaminaMax(), and m_Stamina.
GetSyncedStamina()
float GetSyncedStamina () inline private
References m_StaminaSynced.
Referenced by GetSyncedStaminaNormalized().
GetSyncedStaminaNormalized()
float GetSyncedStaminaNormalized () inline private
References GetStaminaMax(), and GetSyncedStamina().
HasEnoughStaminaFor()
bool HasEnoughStaminaFor (EStaminaConsumers consumer) inline private
References StaminaConsumers::HasEnoughStaminaFor(), m_Stamina, m_StaminaCap, m_StaminaConsumers, and m_StaminaDepleted.
HasEnoughStaminaToStart()
bool HasEnoughStaminaToStart (EStaminaConsumers consumer) inline private
References StaminaConsumers::HasEnoughStaminaToStart(), m_Stamina, m_StaminaCap, m_StaminaConsumers, and m_StaminaDepleted.
Init()
void Init () inline private
References m_RegisteredDepletionModifiers, m_RegisteredRecoveryModifiers, MaskMdfr::STAMINA_DEPLETION_MODIFIER, FatigueMdfr::STAMINA_DEPLETION_MULTIPLIER, EpinephrineMdfr::STAMINA_DEPLETION_MULTIPLIER, MaskMdfr::STAMINA_RECOVERY_MODIFIER, FatigueMdfr::STAMINA_RECOVERY_MULTIPLIER, and DrowningMdfr::STAMINA_RECOVERY_MULTIPLIER.
Referenced by StaminaHandler().
OnRPC()
void OnRPC (float stamina, float stamina_cap, bool cooldown) inline private
deprecated use, StaminaHandler uses SyncJunctures now
OnSyncJuncture()
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx) inline private
called from PlayerBase - syncs stamina values on server with client AND sets the value to match on server and client both (m_StaminaSynced guarantees identical values)
References m_IsInCooldown, m_Player, m_Stamina, m_StaminaCap, m_StaminaSynced, Serializer::Read(), ReadAdditionalStaminaInfo(), DayZPlayerSyncJunctures::SJ_STAMINA, and DayZPlayerSyncJunctures::SJ_STAMINA_MISC.
Referenced by ManBase::OnSyncJuncture().
ReadAdditionalStaminaInfo()
protected void ReadAdditionalStaminaInfo (ParamsReadContext pCtx) inline private
Order of read parameters must match the order of writing above.
References m_StaminaDepletionMultiplier, m_StaminaRecoveryMultiplier, and Serializer::Read().
Referenced by OnSyncJuncture().
RecalculateDepletionMultiplier()
void RecalculateDepletionMultiplier () inline private
References m_ActiveDepletionModifiers, m_RegisteredDepletionModifiers, m_StaminaDepletionMultiplier, and SetDepletionMultiplier().
Referenced by ActivateDepletionModifier(), and DeactivateDepletionModifier().
RecalculateRecoveryMultiplier()
void RecalculateRecoveryMultiplier () inline private
References m_ActiveRecoveryModifiers, m_RegisteredRecoveryModifiers, m_StaminaRecoveryMultiplier, and SetRecoveryMultiplier().
Referenced by ActivateRecoveryModifier(), and DeactivateRecoveryModifier().
RegisterStaminaConsumers()
protected void RegisterStaminaConsumers () inline private
References CfgGameplayHandler::GetStaminaMinCap(), m_StaminaConsumers, StaminaConsumers::RegisterConsumer(), GameConstants::STAMINA_CLIMB_THRESHOLD, GameConstants::STAMINA_HOLD_BREATH_THRESHOLD_ACTIVATE, GameConstants::STAMINA_HOLD_BREATH_THRESHOLD_DRAIN, GameConstants::STAMINA_JUMP_THRESHOLD, GameConstants::STAMINA_MELEE_EVADE_THRESHOLD, GameConstants::STAMINA_MELEE_HEAVY_THRESHOLD, GameConstants::STAMINA_ROLL_THRESHOLD, and GameConstants::STAMINA_VAULT_THRESHOLD.
Referenced by StaminaHandler().
RegisterStaminaModifiers()
protected void RegisterStaminaModifiers () inline private
References CfgGameplayHandler::GetMeleeStaminaModifier(), CfgGameplayHandler::GetObstacleTraversalStaminaModifier(), CfgGameplayHandler::GetStaminaMax(), m_StaminaModifiers, GameConstants::STAMINA_DRAIN_CLIMB, GameConstants::STAMINA_DRAIN_JUMP, GameConstants::STAMINA_DRAIN_MELEE_EVADE, GameConstants::STAMINA_DRAIN_MELEE_HEAVY, GameConstants::STAMINA_DRAIN_MELEE_LIGHT, GameConstants::STAMINA_DRAIN_ROLL, GameConstants::STAMINA_DRAIN_VAULT, and StaminaModifiers().
Referenced by StaminaHandler().
ResetCooldown()
protected void ResetCooldown (int modifier = -1) inline private
References m_IsInCooldown, m_StaminaModifiers, and StaminaModifier().
Referenced by SetCooldown().
SetCooldown()
protected void SetCooldown (float time, int modifier = -1) inline private
set cooldown timer between each consume of stamina
References m_IsInCooldown, m_Stamina, m_StaminaDepleted, m_TimerMap, ResetCooldown(), and Timer::Stop().
Referenced by CheckStaminaState(), DepleteStamina(), StaminaProcessor_Ladder(), StaminaProcessor_Move(), and StaminaProcessor_Swimming().
SetDepletionMultiplier()
void SetDepletionMultiplier (float val) inline private
References m_StaminaDepletionMultiplier, m_StaminaRecoveryMultiplier, and SyncAdditionalStaminaInfo().
Referenced by RecalculateDepletionMultiplier().
SetRecoveryMultiplier()
void SetRecoveryMultiplier (float val) inline private
References m_StaminaDepletionMultiplier, m_StaminaRecoveryMultiplier, and SyncAdditionalStaminaInfo().
Referenced by RecalculateRecoveryMultiplier().
SetStamina()
void SetStamina (float stamina_value) inline private
References Math::Clamp(), CfgGameplayHandler::GetStaminaMax(), m_IsInCooldown, m_Stamina, m_StaminaCap, and SyncStamina().
Referenced by ManBase::EEHitBy(), ManBase::ResetPlayer(), and Update().
StaminaProcessor_Ladder()
protected void StaminaProcessor_Ladder (HumanMovementState pHumanMovementState) inline private
References CalcStaminaGainBonus(), CfgGameplayHandler::GetSprintLadderStaminaModifier(), HumanMovementState::m_iMovement, m_IsInCooldown, m_StaminaDelta, SetCooldown(), GameConstants::STAMINA_DRAIN_LADDER_FAST_PER_SEC, GameConstants::STAMINA_GAIN_IDLE_PER_SEC, GameConstants::STAMINA_GAIN_LADDER_PER_SEC, and GameConstants::STAMINA_REGEN_COOLDOWN_DEPLETION.
Referenced by Update().
StaminaProcessor_Move()
protected void StaminaProcessor_Move (HumanMovementState pHumanMovementState) inline private
References CalcStaminaGainBonus(), CfgGameplayHandler::GetSprintStaminaModifierCro(), CfgGameplayHandler::GetSprintStaminaModifierErc(), m_HumanMoveSettings, HumanMovementState::m_iMovement, m_IsInCooldown, HumanMovementState::m_iStanceIdx, m_Player, m_StaminaDelta, SetCooldown(), GameConstants::STAMINA_DRAIN_CROUCHED_SPRINT_PER_SEC, GameConstants::STAMINA_DRAIN_STANDING_SPRINT_PER_SEC, GameConstants::STAMINA_GAIN_IDLE_PER_SEC, GameConstants::STAMINA_GAIN_JOG_PER_SEC, GameConstants::STAMINA_GAIN_ROLL_PER_SEC, GameConstants::STAMINA_GAIN_WALK_PER_SEC, and GameConstants::STAMINA_REGEN_COOLDOWN_DEPLETION.
Referenced by Update().
StaminaProcessor_Swimming()
protected void StaminaProcessor_Swimming (HumanMovementState pHumanMovementState) inline private
References CalcStaminaGainBonus(), CfgGameplayHandler::GetSprintSwimmingStaminaModifier(), HumanMovementState::m_iMovement, m_IsInCooldown, m_StaminaDelta, SetCooldown(), GameConstants::STAMINA_DRAIN_SWIM_FAST_PER_SEC, GameConstants::STAMINA_GAIN_IDLE_PER_SEC, GameConstants::STAMINA_GAIN_SWIM_PER_SEC, and GameConstants::STAMINA_REGEN_COOLDOWN_DEPLETION.
Referenced by Update().
SyncAdditionalStaminaInfo()
protected void SyncAdditionalStaminaInfo (Param par) inline private
Method to sync more info for stamina manager. Template parameter means it is very extendable for further use.
References m_Player, DayZPlayerSyncJunctures::SJ_STAMINA_MISC, and Serializer::Write().
Referenced by SetDepletionMultiplier(), and SetRecoveryMultiplier().
SyncStamina()
protected void SyncStamina (float stamina, float stamina_cap, bool cooldown) inline private
stamina sync - server part
References m_IsInCooldown, m_Player, m_Stamina, m_StaminaCap, DayZPlayerSyncJunctures::SJ_STAMINA, and Serializer::Write().
Referenced by SetStamina().
Update()
void Update (float deltaT, int pCurrentCommandID) inline private
gets the actual players load
StaminaCap calculation starts when PlayerLoad exceeds STAMINA_WEIGHT_LIMIT_THRESHOLD
processed on event
processed on event
processed on event
References ApplyExhaustion(), CheckStaminaState(), GetGame(), CfgGameplayHandler::GetStaminaKgToStaminaPercentPenalty(), CfgGameplayHandler::GetStaminaMax(), CfgGameplayHandler::GetStaminaMinCap(), CfgGameplayHandler::GetStaminaWeightLimitThreshold(), HumanMovementState::m_CommandTypeId, m_IsInCooldown, m_Player, m_PlayerLoad, m_Stamina, m_StaminaCap, m_StaminaDelta, m_StaminaDepletion, m_StaminaDepletionMultiplier, m_StaminaRecoveryMultiplier, m_StaminaSynced, m_State, m_Time, Math::Max(), Math::Min(), SetStamina(), GameConstants::STAMINA_GAIN_IDLE_PER_SEC, GameConstants::STAMINA_KG_TO_GRAMS, GameConstants::STAMINA_SYNC_RATE, StaminaProcessor_Ladder(), StaminaProcessor_Move(), and StaminaProcessor_Swimming().
Referenced by ManBase::CommandHandler().
Field Documentation
m_ActiveDepletionModifiers
ref set<EStaminaMultiplierTypes> m_ActiveDepletionModifiers private
Referenced by ActivateDepletionModifier(), DeactivateDepletionModifier(), RecalculateDepletionMultiplier(), and StaminaHandler().
m_ActiveRecoveryModifiers
ref set<EStaminaMultiplierTypes> m_ActiveRecoveryModifiers private
Referenced by ActivateRecoveryModifier(), DeactivateRecoveryModifier(), RecalculateRecoveryMultiplier(), and StaminaHandler().
m_Debug
protected bool m_Debug private
m_HumanMoveSettings
protected SHumanCommandMoveSettings m_HumanMoveSettings private
Referenced by StaminaHandler(), and StaminaProcessor_Move().
m_IsInCooldown
protected bool m_IsInCooldown private
Referenced by CheckStaminaState(), OnSyncJuncture(), ResetCooldown(), SetCooldown(), SetStamina(), StaminaHandler(), StaminaProcessor_Ladder(), StaminaProcessor_Move(), StaminaProcessor_Swimming(), SyncStamina(), and Update().
m_Player
protected PlayerBase m_Player private
Referenced by ApplyExhaustion(), DepleteStamina(), OnSyncJuncture(), StaminaHandler(), StaminaProcessor_Move(), SyncAdditionalStaminaInfo(), SyncStamina(), and Update().
m_PlayerLoad
protected float m_PlayerLoad private
Referenced by Update().
m_RegisteredDepletionModifiers
ref map<EStaminaMultiplierTypes, float> m_RegisteredDepletionModifiers private
Referenced by ActivateDepletionModifier(), Init(), RecalculateDepletionMultiplier(), and StaminaHandler().
m_RegisteredRecoveryModifiers
ref map<EStaminaMultiplierTypes, float> m_RegisteredRecoveryModifiers private
Referenced by ActivateRecoveryModifier(), Init(), RecalculateRecoveryMultiplier(), and StaminaHandler().
m_Stamina
protected float m_Stamina private
Referenced by ApplyExhaustion(), CalcStaminaGainBonus(), CheckStaminaState(), GetStamina(), GetStaminaNormalized(), HasEnoughStaminaFor(), HasEnoughStaminaToStart(), OnSyncJuncture(), SetCooldown(), SetStamina(), StaminaHandler(), SyncStamina(), and Update().
m_StaminaCap
protected float m_StaminaCap private
Referenced by ApplyExhaustion(), GetStaminaCap(), HasEnoughStaminaFor(), HasEnoughStaminaToStart(), OnSyncJuncture(), SetStamina(), StaminaHandler(), SyncStamina(), and Update().
m_StaminaConsumers
protected ref StaminaConsumers m_StaminaConsumers private
Referenced by HasEnoughStaminaFor(), HasEnoughStaminaToStart(), and RegisterStaminaConsumers().
m_StaminaDelta
protected float m_StaminaDelta private
Referenced by StaminaProcessor_Ladder(), StaminaProcessor_Move(), StaminaProcessor_Swimming(), and Update().
m_StaminaDepleted
protected bool m_StaminaDepleted private
DEPRECATED.
Referenced by CheckStaminaState(), HasEnoughStaminaFor(), HasEnoughStaminaToStart(), SetCooldown(), and StaminaHandler().
m_StaminaDepletion
protected float m_StaminaDepletion private
Referenced by CalcStaminaGainBonus(), DepleteStamina(), StaminaHandler(), and Update().
m_StaminaDepletionMultiplier
protected float m_StaminaDepletionMultiplier private
Referenced by DepleteStamina(), GetDepletionMultiplier(), ReadAdditionalStaminaInfo(), RecalculateDepletionMultiplier(), SetDepletionMultiplier(), SetRecoveryMultiplier(), StaminaHandler(), and Update().
m_StaminaModifiers
protected ref StaminaModifiers m_StaminaModifiers private
Referenced by DepleteStamina(), RegisterStaminaModifiers(), and ResetCooldown().
m_StaminaParams
protected ref Param3<float,float,bool> m_StaminaParams private
Referenced by StaminaHandler().
m_StaminaRecoveryMultiplier
protected float m_StaminaRecoveryMultiplier private
Referenced by GetRecoveryMultiplier(), ReadAdditionalStaminaInfo(), RecalculateRecoveryMultiplier(), SetDepletionMultiplier(), SetRecoveryMultiplier(), StaminaHandler(), and Update().
m_StaminaSynced
protected float m_StaminaSynced private
Referenced by GetSyncedStamina(), OnSyncJuncture(), and Update().
m_State
protected ref HumanMovementState m_State private
Referenced by StaminaHandler(), and Update().
m_Time
protected float m_Time private
Referenced by StaminaHandler(), and Update().
m_TimerMap
protected ref map<int,ref Timer> m_TimerMap private
Referenced by SetCooldown(), and StaminaHandler().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/StaminaHandler.c