DayZ Scripts: PPERequesterBase Class Reference
PPERequesterBase Class Reference
Private Member Functions
void PPERequesterBase (int requester_IDX)
void SetRequesterUpdating (bool state)
Has to be set for the requester to be handled.
void Start (Param par=null)
void Stop (Param par=null)
bool IsRequesterRunning ()
void SetRequesterIDX (int idx)
automatically assigned by PPERequesterBank
int GetRequesterIDX ()
Returns requester index.
int GetCategoryMask ()
mask for mass-handling methods like 'StopAllEffects'
protected void SetTargetValueBool (int mat_id, int param_idx, bool val, int priority_layer, int operator=PPOperators.SET)
protected void SetTargetValueBoolDefault (int mat_id, int param_idx)
protected void SetTargetValueInt (int mat_id, int param_idx, bool relative, int val, int priority_layer, int operator=PPOperators.SET)
protected void SetTargetValueIntDefault (int mat_id, int param_idx)
protected void SetTargetValueFloat (int mat_id, int param_idx, bool relative, float val, int priority_layer, int operator=PPOperators.ADD_RELATIVE)
protected void SetTargetValueFloatDefault (int mat_id, int param_idx)
protected void SetTargetValueColor (int mat_id, int param_idx, ref array< float > val, int priority_layer, int operator=PPOperators.ADD_RELATIVE)
protected void SetTargetValueColorDefault (int mat_id, int param_idx)
protected void QueueValuesSend ()
Sets this requester to update in the manager.
PPERequestParamDataBase GetRequestData (int mat_id, int param_idx, int type)
returns request data for specific parameter, or creates one if one does not exist in this request yet (singletons)
protected PPERequestParamDataBase PrepareData (int mat_id, int param_idx, int type)
map< int, ref map< int, ref PPERequestParamDataBase > > GetActiveRequestStructure ()
protected void ClearRequesterData ()
protected void SendCurrentValueData (PPERequestParamDataBase data)
void OnUpdate (float delta)
protected void OnStart (Param par=null)
protected void OnStop (Param par=null)
automatically resets all material parameters of this requester to defaults
protected float RelativizeValue (float value, int var_type, int mat_id, int param_id, bool relative)
converts all values used to relative values (if not relative already)
protected void SetDefaultValuesAll ()
Sets all requested values to default, ignoring them in further calculations.
void DbgPrnt (string text)
override int GetCategoryMask ()
Private Attributes
protected bool m_IsRunning
protected bool m_ValuesSent
protected int m_IDX
protected bool m_Valid = false
protected ref map< int, ref map< int, ref PPERequestParamDataBase > > m_RequestDataStructure
Constructor & Destructor Documentation
PPERequesterBase()
void PPERequesterBase (int requester_IDX) inline private
References m_IDX, m_IsRunning, m_RequestDataStructure, m_Valid, and m_ValuesSent.
Member Function Documentation
ClearRequesterData()
protected void ClearRequesterData () inline private
References m_RequestDataStructure.
DbgPrnt()
void DbgPrnt (string text) inline private
GetActiveRequestStructure()
map< int, ref map< int, ref PPERequestParamDataBase > > GetActiveRequestStructure () inline private
References m_RequestDataStructure.
Referenced by RemoveActiveRequestFromMaterials().
GetCategoryMask() [1/2]
int GetCategoryMask () inline private
mask for mass-handling methods like 'StopAllEffects'
GetCategoryMask() [2/2]
override int GetCategoryMask () inline private
GetRequestData()
PPERequestParamDataBase GetRequestData (int mat_id, int param_idx, int type) inline private
returns request data for specific parameter, or creates one if one does not exist in this request yet (singletons)
References Error(), m_RequestDataStructure, PPERequestParamDataBase::m_Requester, and PrepareData().
Referenced by SetTargetValueBool(), SetTargetValueBoolDefault(), SetTargetValueColor(), SetTargetValueColorDefault(), SetTargetValueFloat(), SetTargetValueFloatDefault(), SetTargetValueInt(), and SetTargetValueIntDefault().
GetRequesterIDX()
int GetRequesterIDX () inline private
Returns requester index.
References m_IDX.
Referenced by RemoveActiveRequestFromMaterials().
IsRequesterRunning()
bool IsRequesterRunning () inline private
References m_IsRunning.
Referenced by IsAnyRequesterRunning().
OnStart()
protected void OnStart (Param par = null) inline private
References SetRequesterUpdating().
Referenced by Start().
OnStop()
protected void OnStop (Param par = null) inline private
automatically resets all material parameters of this requester to defaults
References SetDefaultValuesAll(), and SetRequesterUpdating().
Referenced by Stop().
OnUpdate()
void OnUpdate (float delta) inline private
References Count, m_RequestDataStructure, m_ValuesSent, SendCurrentValueData(), and SetRequesterUpdating().
Referenced by ProcessRequesterUpdates().
PrepareData()
protected PPERequestParamDataBase PrepareData (int mat_id, int param_idx, int type) inline private
References m_IDX, PPERequestParamDataBool(), and PPERequestParamDataFloat().
Referenced by GetRequestData().
QueueValuesSend()
protected void QueueValuesSend () inline private
Sets this requester to update in the manager.
References m_ValuesSent, and SetRequesterUpdating().
Referenced by SetTargetValueBool(), SetTargetValueBoolDefault(), SetTargetValueColor(), SetTargetValueColorDefault(), SetTargetValueFloat(), SetTargetValueFloatDefault(), SetTargetValueInt(), and SetTargetValueIntDefault().
RelativizeValue()
protected float RelativizeValue (float value, int var_type, int mat_id, int param_id, bool relative) inline private
converts all values used to relative values (if not relative already)
References Math::Clamp(), PPEManagerStatic::GetPPEManager(), and Math::InverseLerp().
Referenced by SetTargetValueFloat().
SendCurrentValueData()
protected void SendCurrentValueData (PPERequestParamDataBase data) inline private
References PPEManagerStatic::GetPPEManager().
Referenced by OnUpdate().
SetDefaultValuesAll()
protected void SetDefaultValuesAll () inline private
Sets all requested values to default, ignoring them in further calculations.
References Count, PPERequestParamDataBase::GetMaterialID(), PPERequestParamDataBase::GetParameterID(), PPERequestParamDataBase::GetVarType(), PPERequestParamDataBase::IsDataActive(), m_RequestDataStructure, SetTargetValueBoolDefault(), SetTargetValueColorDefault(), SetTargetValueFloatDefault(), and SetTargetValueIntDefault().
Referenced by OnStop().
SetRequesterIDX()
void SetRequesterIDX (int idx) inline private
automatically assigned by PPERequesterBank
References m_IDX.
Referenced by Managed::RegisterRequester().
SetRequesterUpdating()
void SetRequesterUpdating (bool state) inline private
Has to be set for the requester to be handled.
References PPEManagerStatic::GetPPEManager(), Debug::Log(), and m_Valid.
Referenced by OnStart(), OnStop(), OnUpdate(), and QueueValuesSend().
SetTargetValueBool()
protected void SetTargetValueBool (int mat_id, int param_idx, bool val, int priority_layer, int operator = PPOperators.SET) inline private
References GetRequestData(), m_RequestDataStructure, PPERequestParamDataBool(), and QueueValuesSend().
SetTargetValueBoolDefault()
protected void SetTargetValueBoolDefault (int mat_id, int param_idx) inline private
References GetRequestData(), m_RequestDataStructure, PPERequestParamDataBool(), and QueueValuesSend().
Referenced by SetDefaultValuesAll().
SetTargetValueColor()
protected void SetTargetValueColor (int mat_id, int param_idx, ref array< float > val, int priority_layer, int operator = PPOperators.ADD_RELATIVE) inline private
References GetRequestData(), m_RequestDataStructure, and QueueValuesSend().
SetTargetValueColorDefault()
protected void SetTargetValueColorDefault (int mat_id, int param_idx) inline private
References GetRequestData(), m_RequestDataStructure, and QueueValuesSend().
Referenced by SetDefaultValuesAll().
SetTargetValueFloat()
protected void SetTargetValueFloat (int mat_id, int param_idx, bool relative, float val, int priority_layer, int operator = PPOperators.ADD_RELATIVE) inline private
References GetRequestData(), m_RequestDataStructure, PPERequestParamDataFloat(), QueueValuesSend(), and RelativizeValue().
SetTargetValueFloatDefault()
protected void SetTargetValueFloatDefault (int mat_id, int param_idx) inline private
References GetRequestData(), m_RequestDataStructure, PPERequestParamDataFloat(), and QueueValuesSend().
Referenced by SetDefaultValuesAll().
SetTargetValueInt()
protected void SetTargetValueInt (int mat_id, int param_idx, bool relative, int val, int priority_layer, int operator = PPOperators.SET) inline private
References GetRequestData(), m_RequestDataStructure, and QueueValuesSend().
SetTargetValueIntDefault()
protected void SetTargetValueIntDefault (int mat_id, int param_idx) inline private
References GetRequestData(), m_RequestDataStructure, and QueueValuesSend().
Referenced by SetDefaultValuesAll().
Start()
void Start (Param par = null) inline private
References m_IsRunning, and OnStart().
Referenced by ManBase::SetContaminatedEffectEx().
Stop()
void Stop (Param par = null) inline private
References m_IsRunning, m_RequestDataStructure, and OnStop().
Field Documentation
m_IDX
protected int m_IDX private
Referenced by GetRequesterIDX(), PPERequesterBase(), PrepareData(), and SetRequesterIDX().
m_IsRunning
protected bool m_IsRunning private
Referenced by IsRequesterRunning(), PPERequesterBase(), Start(), and Stop().
m_RequestDataStructure
protected ref map<int,ref map<int,ref PPERequestParamDataBase> > m_RequestDataStructure private
Referenced by ClearRequesterData(), GetActiveRequestStructure(), GetRequestData(), OnUpdate(), PPERequesterBase(), SetDefaultValuesAll(), SetTargetValueBool(), SetTargetValueBoolDefault(), SetTargetValueColor(), SetTargetValueColorDefault(), SetTargetValueFloat(), SetTargetValueFloatDefault(), SetTargetValueInt(), SetTargetValueIntDefault(), and Stop().
m_Valid
protected bool m_Valid = false private
Referenced by PPERequesterBase(), and SetRequesterUpdating().
m_ValuesSent
protected bool m_ValuesSent private
Referenced by OnUpdate(), PPERequesterBase(), and QueueValuesSend().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/PPEManager/Requesters/PPERequestPlatformsBase.c