DayZ Scripts: DayZPlayerSyncJunctures Class Reference
DayZPlayerSyncJunctures Class Reference
Static Private Member Functions
static void SendDeath (DayZPlayer pPlayer, int pType, float pHitDir)
static bool ReadDeathParams (ParamsReadContext pCtx, out int pType, out float pHitDir)
static void SendDamageHit (DayZPlayer pPlayer, int pType, float pHitDir, bool pFullbody)
static void SendDamageHitEx (DayZPlayer pPlayer, int pType, float pHitDir, bool pFullbody, TotalDamageResult pDamageResult, int pDamageType, EntityAI pSource, string pComponent, string pAmmoType, vector pModelPos)
static bool ReadDamageHitParams (ParamsReadContext pCtx, out int pType, out float pHitDir, out bool pFullbody)
static bool ReadDamageHitParamsEx (ParamsReadContext pCtx, out SyncHitInfo pData)
static void SendInjury (DayZPlayer pPlayer, bool pEnable, eInjuryHandlerLevels level)
static bool ReadInjuryParams (ParamsReadContext pCtx, out bool pEnable, out eInjuryHandlerLevels level)
static void SendPlayerUnconsciousness (DayZPlayer pPlayer, bool enable)
static bool ReadPlayerUnconsciousnessParams (ParamsReadContext pCtx, out bool enable)
static void SendPlayerFBModifier (PlayerBase pPlayer, int type)
static bool ReadPlayerFBModifier (ParamsReadContext pCtx, out int type)
static void SendPlayerSymptomADD (DayZPlayer pPlayer, int type, int state_type)
static bool ReadPlayerSymptomADDParams (ParamsReadContext pCtx, out int type)
static void SendPlayerSymptomFB (DayZPlayer pPlayer, DayZPlayerConstants anim_id, int state_type, int stance_mask, float duration)
static bool ReadPlayerSymptomFBParams (ParamsReadContext pCtx, out DayZPlayerConstants anim_id, out int stance_mask, out float duration)
static void SendActionInterrupt (DayZPlayer pPlayer)
static bool ReadActionInterruptParams (ParamsReadContext pCtx)
static void SendActionAcknowledgment (DayZPlayer pPlayer, int AckID, bool accept)
static void SendWeaponActionAcknowledgment (DayZPlayer pPlayer, int AckID, bool accept)
static bool ReadKuruRequest (ParamsReadContext pCtx, out float amount)
static void SendKuruRequest (DayZPlayer pPlayer, float amount)
static void SendQuickbarSetShortcut (DayZPlayer pPlayer, EntityAI item, int index, bool force=false)
static void SendWeaponJamChance (DayZPlayer pPlayer, float jamChance)
static void SendDeleteItem (DayZPlayer pPlayer, EntityAI item)
static void SendBrokenLegs (DayZPlayer pPlayer, bool canPlaySound, eBrokenLegs currentState, eBrokenLegs localState)
static bool ReadBrokenLegsParams (ParamsReadContext pCtx, out bool canPlaySound, out eBrokenLegs currentState, out eBrokenLegs localState)
static void SendBrokenLegsEx (DayZPlayer pPlayer, int currentState)
static bool ReadBrokenLegsParamsEx (ParamsReadContext pCtx, out int currentState)
static void SendShock (DayZPlayer pPlayer, float shockValue)
static bool ReadShockParams (ParamsReadContext pCtx, out float shockValue)
Static Private Attributes
static const int SJ_DAMAGE_HIT = 0
static const int SJ_INJURY = 1
static const int SJ_ACTION_INTERRUPT = 2
static const int SJ_PLAYER_STATES = 3
static const int SJ_QUICKBAR_SET_SHORTCUT = 4
static const int SJ_INVENTORY = 5
static const int SJ_ACTION_ACK_ACCEPT = 6
static const int SJ_ACTION_ACK_REJECT = 7
static const int SJ_WEAPON_ACTION_ACK_ACCEPT = 8
static const int SJ_WEAPON_ACTION_ACK_REJECT = 9
static const int SJ_WEAPON_SET_JAMMING_CHANCE = 10
static const int SJ_UNCONSCIOUSNESS = 11
static const int SJ_DEATH = 12
static const int SJ_PLAYER_FB_MODIFIER = 13
static const int SJ_PLAYER_ADD_MODIFIER = 14
static const int SJ_KURU_REQUEST = 15
static const int SJ_GESTURE_REQUEST = 16
static const int SJ_INVENTORY_REPAIR = 17
static const int SJ_WEAPON_LIFT = 18
static const int SJ_WEAPON_RAISE_COMPLETED = 19
static const int SJ_DELETE_ITEM = 20
static const int SJ_BROKEN_LEGS = 21
static const int SJ_SHOCK = 22
static const int SJ_STAMINA = 23
static const int SJ_STAMINA_MISC = 24
static const int SJ_ADS_RESET = 25
Detailed Description
Definition at line 4 of file DayZPlayerSyncJunctures.c.
Member Function Documentation
ReadActionInterruptParams()
static bool ReadActionInterruptParams (ParamsReadContext pCtx) inline static private
Definition at line 269 of file DayZPlayerSyncJunctures.c.
ReadBrokenLegsParams()
static bool ReadBrokenLegsParams (ParamsReadContext pCtx, out bool canPlaySound, out eBrokenLegs currentState, out eBrokenLegs localState) inline static private
Definition at line 378 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
ReadBrokenLegsParamsEx()
static bool ReadBrokenLegsParamsEx (ParamsReadContext pCtx, out int currentState) inline static private
Definition at line 398 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
Referenced by ManBase::OnSyncJuncture().
ReadDamageHitParams()
static bool ReadDamageHitParams (ParamsReadContext pCtx, out int pType, out float pHitDir, out bool pFullbody) inline static private
Definition at line 119 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
ReadDamageHitParamsEx()
static bool ReadDamageHitParamsEx (ParamsReadContext pCtx, out SyncHitInfo pData) inline static private
Definition at line 130 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
Referenced by DayZPlayer::OnSyncJuncture().
ReadDeathParams()
static bool ReadDeathParams (ParamsReadContext pCtx, out int pType, out float pHitDir) inline static private
Definition at line 72 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
Referenced by DayZPlayer::OnSyncJuncture().
ReadInjuryParams()
static bool ReadInjuryParams (ParamsReadContext pCtx, out bool pEnable, out eInjuryHandlerLevels level) inline static private
Definition at line 151 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
Referenced by ManBase::OnSyncJuncture().
ReadKuruRequest()
static bool ReadKuruRequest (ParamsReadContext pCtx, out float amount) inline static private
Kuru Disease Shake
Definition at line 304 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
Referenced by ManBase::OnSyncJuncture().
ReadPlayerFBModifier()
static bool ReadPlayerFBModifier (ParamsReadContext pCtx, out int type) inline static private
Definition at line 197 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
ReadPlayerSymptomADDParams()
static bool ReadPlayerSymptomADDParams (ParamsReadContext pCtx, out int type) inline static private
Definition at line 219 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
ReadPlayerSymptomFBParams()
static bool ReadPlayerSymptomFBParams (ParamsReadContext pCtx, out DayZPlayerConstants anim_id, out int stance_mask, out float duration) inline static private
Definition at line 244 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
Referenced by SmptAnimMetaBase::Init().
ReadPlayerUnconsciousnessParams()
static bool ReadPlayerUnconsciousnessParams (ParamsReadContext pCtx, out bool enable) inline static private
Definition at line 175 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
Referenced by ManBase::OnSyncJuncture().
ReadShockParams()
static bool ReadShockParams (ParamsReadContext pCtx, out float shockValue) inline static private
Definition at line 419 of file DayZPlayerSyncJunctures.c.
References Serializer::Read().
Referenced by ManBase::OnSyncJuncture().
SendActionAcknowledgment()
static void SendActionAcknowledgment (DayZPlayer pPlayer, int AckID, bool accept) inline static private
Action Acknowledgment
Definition at line 278 of file DayZPlayerSyncJunctures.c.
References SJ_ACTION_ACK_ACCEPT, SJ_ACTION_ACK_REJECT, and Serializer::Write().
Referenced by ActionManagerServer::OnInputUserDataProcess(), ActionManagerServer::StartDeliveredAction(), and ActionManagerServer::Update().
SendActionInterrupt()
static void SendActionInterrupt (DayZPlayer pPlayer) inline static private
Action interrupt
Definition at line 263 of file DayZPlayerSyncJunctures.c.
References SJ_ACTION_INTERRUPT.
Referenced by ActionManagerServer::Interrupt(), ActionBaseCB::Interrupt(), ActionManagerServer::OnInputUserDataProcess(), ActionManagerServer::StartDeliveredAction(), and ActionManagerServer::Update().
SendBrokenLegs()
static void SendBrokenLegs (DayZPlayer pPlayer, bool canPlaySound, eBrokenLegs currentState, eBrokenLegs localState) inline static private
BrokenLegs
Definition at line 368 of file DayZPlayerSyncJunctures.c.
References SJ_BROKEN_LEGS, and Serializer::Write().
SendBrokenLegsEx()
static void SendBrokenLegsEx (DayZPlayer pPlayer, int currentState) inline static private
Definition at line 390 of file DayZPlayerSyncJunctures.c.
References SJ_BROKEN_LEGS, and Serializer::Write().
Referenced by ManBase::SetBrokenLegs().
SendDamageHit()
static void SendDamageHit (DayZPlayer pPlayer, int pType, float pHitDir, bool pFullbody) inline static private
DamageHit
Definition at line 87 of file DayZPlayerSyncJunctures.c.
References SJ_DAMAGE_HIT, and Serializer::Write().
SendDamageHitEx()
static void SendDamageHitEx (DayZPlayer pPlayer, int pType, float pHitDir, bool pFullbody, TotalDamageResult pDamageResult, int pDamageType, EntityAI pSource, string pComponent, string pAmmoType, vector pModelPos) inline static private
Definition at line 97 of file DayZPlayerSyncJunctures.c.
References TotalDamageResult::GetHighestDamage(), Managed::m_AnimType, SJ_DAMAGE_HIT, and Serializer::Write().
Referenced by DayZPlayer::EEHitBy().
SendDeath()
static void SendDeath (DayZPlayer pPlayer, int pType, float pHitDir) inline static private
Death
Definition at line 63 of file DayZPlayerSyncJunctures.c.
References SJ_DEATH, and Serializer::Write().
Referenced by DayZPlayer::SendDeathJuncture().
SendDeleteItem()
static void SendDeleteItem (DayZPlayer pPlayer, EntityAI item) inline static private
Definition at line 354 of file DayZPlayerSyncJunctures.c.
References SJ_DELETE_ITEM, and Serializer::Write().
Referenced by ManBase::JunctureDeleteItem().
SendInjury()
static void SendInjury (DayZPlayer pPlayer, bool pEnable, eInjuryHandlerLevels level) inline static private
Injury
Definition at line 142 of file DayZPlayerSyncJunctures.c.
References SJ_INJURY, and Serializer::Write().
Referenced by SendValue().
SendKuruRequest()
static void SendKuruRequest (DayZPlayer pPlayer, float amount) inline static private
Definition at line 311 of file DayZPlayerSyncJunctures.c.
References SJ_KURU_REQUEST, and Serializer::Write().
Referenced by BrainDiseaseMdfr::OnTick().
SendPlayerFBModifier()
static void SendPlayerFBModifier (PlayerBase pPlayer, int type) inline static private
Full body
Definition at line 189 of file DayZPlayerSyncJunctures.c.
References SJ_PLAYER_FB_MODIFIER, and Serializer::Write().
SendPlayerSymptomADD()
static void SendPlayerSymptomADD (DayZPlayer pPlayer, int type, int state_type) inline static private
Additive Symptoms
Definition at line 209 of file DayZPlayerSyncJunctures.c.
References SJ_PLAYER_ADD_MODIFIER, and Serializer::Write().
Referenced by SymptomBase::PlayAnimationADD().
SendPlayerSymptomFB()
static void SendPlayerSymptomFB (DayZPlayer pPlayer, DayZPlayerConstants anim_id, int state_type, int stance_mask, float duration) inline static private
Full body Symptoms
Definition at line 232 of file DayZPlayerSyncJunctures.c.
References SJ_PLAYER_STATES, and Serializer::Write().
Referenced by SymptomBase::PlayAnimationFB().
SendPlayerUnconsciousness()
static void SendPlayerUnconsciousness (DayZPlayer pPlayer, bool enable) inline static private
Conscious / Unconscious
Definition at line 166 of file DayZPlayerSyncJunctures.c.
References SJ_UNCONSCIOUSNESS, and Serializer::Write().
Referenced by UnconsciousnessMdfr::OnActivate(), UnconsciousnessMdfr::OnDeactivate(), ManBase::RequestUnconsciousness(), and ManBase::ResetPlayer().
SendQuickbarSetShortcut()
static void SendQuickbarSetShortcut (DayZPlayer pPlayer, EntityAI item, int index, bool force = false) inline static private
Quickbar
Definition at line 323 of file DayZPlayerSyncJunctures.c.
References SJ_QUICKBAR_SET_SHORTCUT, and Serializer::Write().
Referenced by SetEntityShortcut().
SendShock()
static void SendShock (DayZPlayer pPlayer, float shockValue) inline static private
Shock
Definition at line 411 of file DayZPlayerSyncJunctures.c.
References SJ_SHOCK, and Serializer::Write().
Referenced by ShockHandler::Synchronize().
SendWeaponActionAcknowledgment()
static void SendWeaponActionAcknowledgment (DayZPlayer pPlayer, int AckID, bool accept) inline static private
Definition at line 289 of file DayZPlayerSyncJunctures.c.
References SJ_WEAPON_ACTION_ACK_ACCEPT, SJ_WEAPON_ACTION_ACK_REJECT, and Serializer::Write().
Referenced by WeaponManager::OnInputUserDataProcess().
SendWeaponJamChance()
static void SendWeaponJamChance (DayZPlayer pPlayer, float jamChance) inline static private
Definition at line 333 of file DayZPlayerSyncJunctures.c.
References SJ_WEAPON_SET_JAMMING_CHANCE, and Serializer::Write().
Referenced by WeaponManager::Update().
Field Documentation
SJ_ACTION_ACK_ACCEPT
const int SJ_ACTION_ACK_ACCEPT = 6 static private
Definition at line 12 of file DayZPlayerSyncJunctures.c.
Referenced by OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendActionAcknowledgment().
SJ_ACTION_ACK_REJECT
const int SJ_ACTION_ACK_REJECT = 7 static private
Definition at line 13 of file DayZPlayerSyncJunctures.c.
Referenced by OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendActionAcknowledgment().
SJ_ACTION_INTERRUPT
const int SJ_ACTION_INTERRUPT = 2 static private
Definition at line 8 of file DayZPlayerSyncJunctures.c.
Referenced by OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendActionInterrupt().
SJ_ADS_RESET
const int SJ_ADS_RESET = 25 static private
Definition at line 31 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and ManBase::ResetADSPlayerSync().
SJ_BROKEN_LEGS
const int SJ_BROKEN_LEGS = 21 static private
Definition at line 27 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), SendBrokenLegs(), and SendBrokenLegsEx().
SJ_DAMAGE_HIT
const int SJ_DAMAGE_HIT = 0 static private
Definition at line 6 of file DayZPlayerSyncJunctures.c.
Referenced by DayZPlayer::OnSyncJuncture(), SendDamageHit(), and SendDamageHitEx().
SJ_DEATH
const int SJ_DEATH = 12 static private
Definition at line 18 of file DayZPlayerSyncJunctures.c.
Referenced by DayZPlayer::OnSyncJuncture(), and SendDeath().
SJ_DELETE_ITEM
const int SJ_DELETE_ITEM = 20 static private
Definition at line 26 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendDeleteItem().
SJ_GESTURE_REQUEST
const int SJ_GESTURE_REQUEST = 16 static private
Definition at line 22 of file DayZPlayerSyncJunctures.c.
Referenced by OnInputUserDataProcess(), ManBase::OnSyncJuncture(), and ServerRequestEmoteCancel().
SJ_INJURY
const int SJ_INJURY = 1 static private
Definition at line 7 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendInjury().
SJ_INVENTORY
const int SJ_INVENTORY = 5 static private
Definition at line 11 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), ProccessInputData(), SendServerHandEventViaJuncture(), and TakeToDst().
SJ_INVENTORY_REPAIR
const int SJ_INVENTORY_REPAIR = 17 static private
Definition at line 23 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and ProccessInputData().
SJ_KURU_REQUEST
const int SJ_KURU_REQUEST = 15 static private
Definition at line 21 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendKuruRequest().
SJ_PLAYER_ADD_MODIFIER
const int SJ_PLAYER_ADD_MODIFIER = 14 static private
Definition at line 20 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendPlayerSymptomADD().
SJ_PLAYER_FB_MODIFIER
const int SJ_PLAYER_FB_MODIFIER = 13 static private
Definition at line 19 of file DayZPlayerSyncJunctures.c.
Referenced by SendPlayerFBModifier().
SJ_PLAYER_STATES
const int SJ_PLAYER_STATES = 3 static private
Definition at line 9 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendPlayerSymptomFB().
SJ_QUICKBAR_SET_SHORTCUT
const int SJ_QUICKBAR_SET_SHORTCUT = 4 static private
Definition at line 10 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendQuickbarSetShortcut().
SJ_SHOCK
const int SJ_SHOCK = 22 static private
Definition at line 28 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendShock().
SJ_STAMINA
const int SJ_STAMINA = 23 static private
Definition at line 29 of file DayZPlayerSyncJunctures.c.
Referenced by OnSyncJuncture(), ManBase::OnSyncJuncture(), and SyncStamina().
SJ_STAMINA_MISC
const int SJ_STAMINA_MISC = 24 static private
Definition at line 30 of file DayZPlayerSyncJunctures.c.
Referenced by OnSyncJuncture(), ManBase::OnSyncJuncture(), and SyncAdditionalStaminaInfo().
SJ_UNCONSCIOUSNESS
const int SJ_UNCONSCIOUSNESS = 11 static private
Definition at line 17 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendPlayerUnconsciousness().
SJ_WEAPON_ACTION_ACK_ACCEPT
const int SJ_WEAPON_ACTION_ACK_ACCEPT = 8 static private
Definition at line 14 of file DayZPlayerSyncJunctures.c.
Referenced by WeaponManager::OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendWeaponActionAcknowledgment().
SJ_WEAPON_ACTION_ACK_REJECT
const int SJ_WEAPON_ACTION_ACK_REJECT = 9 static private
Definition at line 15 of file DayZPlayerSyncJunctures.c.
Referenced by WeaponManager::OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendWeaponActionAcknowledgment().
SJ_WEAPON_LIFT
const int SJ_WEAPON_LIFT = 18 static private
Definition at line 24 of file DayZPlayerSyncJunctures.c.
Referenced by ManBase::OnSyncJuncture(), and ManBase::ReadLiftWeaponRequest().
SJ_WEAPON_RAISE_COMPLETED
const int SJ_WEAPON_RAISE_COMPLETED = 19 static private
Definition at line 25 of file DayZPlayerSyncJunctures.c.
Referenced by DayZPlayer::OnSyncJuncture(), and DayZPlayer::SendCompleteWeaponRaiseJuncture().
SJ_WEAPON_SET_JAMMING_CHANCE
const int SJ_WEAPON_SET_JAMMING_CHANCE = 10 static private
Definition at line 16 of file DayZPlayerSyncJunctures.c.
Referenced by WeaponManager::OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendWeaponJamChance().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/DayZPlayerSyncJunctures.c