DayZ Scripts: PlayerStatsPCO_Base Class Reference
PlayerStatsPCO_Base Class Reference
Private Member Functions
override int GetVersion ()
override void Init ()
void PlayerStatsPCO_v100 ()
override int GetVersion ()
override void Init ()
override int GetVersion ()
override void Init ()
override int GetVersion ()
override void Init ()
Member Function Documentation
GetVersion() [1/4]
override int GetVersion () inline private
Referenced by PCOHandlerStats::RegisterPCO().
GetVersion() [2/4]
override int GetVersion () inline private
GetVersion() [3/4]
override int GetVersion () inline private
GetVersion() [4/4]
override int GetVersion () inline private
Init() [1/4]
override void Init () inline private
References BloodTypes::GenerateBloodType(), RegisterStat(), and GameConstants::STAMINA_MAX.
Referenced by ResetAllStats().
Init() [2/4]
override void Init () inline private
References BloodTypes::GenerateBloodType(), RegisterStat(), and GameConstants::STAMINA_MAX.
Init() [3/4]
override void Init () inline private
References BloodTypes::GenerateBloodType(), RegisterStat(), and GameConstants::STAMINA_MAX.
Init() [4/4]
override void Init () inline private
References BloodTypes::GenerateBloodType(), CfgGameplayHandler::GetStaminaMax(), RegisterStat(), PlayerConstants::SL_ENERGY_MAX, and PlayerConstants::SL_WATER_MAX.
PlayerStatsPCO_v100()
void PlayerStatsPCO_v100 () inline private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerStats/PlayerStatsPCO.c