DayZ Scripts: ActionOpen Class Reference
ActionOpen Class Reference
Private Member Functions
void ActionOpen ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Constructor & Destructor Documentation
ActionOpen()
void ActionOpen () inline private
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and ActionBase::m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References ActionBase::m_ConditionItem, and ActionBase::m_ConditionTarget.
HasTarget()
override bool HasTarget () inline private
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
References ActionBase::ClearInventoryReservationEx().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
References ActionBase::ClearInventoryReservationEx(), and GetGame().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionOpen.c