DayZ Scripts: AIBehaviourHLData Class Reference
AIBehaviourHLData Class Reference
Private Member Functions
private void AIBehaviourHLData ()
private void ~AIBehaviourHLData ()
void OnParseConfig ()
proto native void ParseBehaviourSlot (string name)
proto native void ParseAlertLevel (string name)
proto native float ReadParamValue (string paramName, float defValue)
Detailed Description
Definition at line 26 of file AIBehaviour.c.
Constructor & Destructor Documentation
AIBehaviourHLData()
private void AIBehaviourHLData () inline private
Definition at line 28 of file AIBehaviour.c.
~AIBehaviourHLData()
private void ~AIBehaviourHLData () inline private
Definition at line 29 of file AIBehaviour.c.
Member Function Documentation
OnParseConfig()
void OnParseConfig () private
ParseAlertLevel()
proto native void ParseAlertLevel (string name) private
Referenced by AIBehaviourHLDataZombie2::OnParseConfig().
ParseBehaviourSlot()
proto native void ParseBehaviourSlot (string name) private
Referenced by AIBehaviourHLDataZombie2::OnParseConfig().
ReadParamValue()
proto native float ReadParamValue (string paramName, float defValue) private
Referenced by AIBehaviourHLDataZombie2::OnParseConfig().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/AIBehaviour.c