DayZ Scripts: LoadingScreen Class Reference
LoadingScreen Class Reference
Private Member Functions
void LoadingScreen (DayZGame game)
void OnTimer ()
DEPRECATED.
void Inc ()
void Dec ()
void EndLoading ()
bool IsLoading ()
void SetTitle (string title)
void SetStatus (string status)
void SetProgress (float val)
void OnUpdate (float timeslice)
void Show ()
void Hide (bool force)
Private Attributes
ref Widget m_WidgetRoot
TextWidget m_TextWidgetTitle
TextWidget m_TextWidgetStatus
TextWidget m_ModdedWarning
ImageWidget m_ImageWidgetBackground
DayZGame m_DayZGame
float m_LastProgressUpdate
ImageWidget m_ImageLogoMid
ImageWidget m_ImageLogoCorner
ImageWidget m_ImageLoadingIcon
ImageWidget m_ImageBackground
ProgressBarWidget m_ProgressLoading
float m_ImageLoadingIconRotation
TextWidget m_ProgressText
int m_Counter
ref Timer m_Timer
Detailed Description
Definition at line 281 of file DayZGame.c.
Constructor & Destructor Documentation
LoadingScreen()
void LoadingScreen (DayZGame game) inline private
Definition at line 302 of file DayZGame.c.
References Class::CastTo(), g_Game, GetGame(), m_Counter, m_DayZGame, m_ImageBackground, m_ImageLoadingIcon, m_ImageLogoCorner, m_ImageLogoMid, m_ImageWidgetBackground, m_ModdedWarning, m_ProgressLoading, m_ProgressText, m_TextWidgetStatus, m_TextWidgetTitle, m_WidgetRoot, ProgressAsync::SetProgressData(), and ProgressAsync::SetUserData().
Member Function Documentation
Dec()
void Dec () inline private
Definition at line 368 of file DayZGame.c.
References EndLoading(), and m_Counter.
Referenced by Hide(), and LoadProgressUpdate().
EndLoading()
void EndLoading () inline private
Definition at line 379 of file DayZGame.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, g_Game, CGame::GetCallQueue(), GetGame(), m_WidgetRoot, ProgressAsync::SetProgressData(), and ProgressAsync::SetUserData().
Referenced by Dec().
Hide()
void Hide (bool force) inline private
Definition at line 453 of file DayZGame.c.
References Dec(), m_Counter, m_WidgetRoot, ProgressAsync::SetProgressData(), and ProgressAsync::SetUserData().
Referenced by LoadingHide().
Inc()
void Inc () inline private
Definition at line 357 of file DayZGame.c.
References m_Counter, m_DayZGame, m_LastProgressUpdate, and Show().
Referenced by LoadProgressUpdate().
IsLoading()
bool IsLoading () inline private
Definition at line 387 of file DayZGame.c.
References m_WidgetRoot.
Referenced by CheckDialogs(), IsLoading(), and OnUpdate().
OnTimer()
void OnTimer () private
DEPRECATED.
OnUpdate()
void OnUpdate (float timeslice) inline private
Definition at line 409 of file DayZGame.c.
Referenced by OnUpdate().
SetProgress()
void SetProgress (float val) inline private
Definition at line 402 of file DayZGame.c.
References m_DayZGame, and m_LastProgressUpdate.
Referenced by LoadProgressUpdate().
SetStatus()
void SetStatus (string status) inline private
Definition at line 397 of file DayZGame.c.
References m_TextWidgetStatus.
Referenced by OnEvent().
SetTitle()
void SetTitle (string title) inline private
Definition at line 392 of file DayZGame.c.
References m_TextWidgetTitle.
Referenced by LoadProgressUpdate().
Show()
void Show () inline private
Definition at line 414 of file DayZGame.c.
References DayZGame(), m_DayZGame, m_ImageBackground, m_ImageLogoCorner, m_ImageLogoMid, m_ImageWidgetBackground, m_ProgressLoading, m_ProgressText, m_TextWidgetStatus, m_TextWidgetTitle, m_WidgetRoot, ProgressAsync::SetProgressData(), and ProgressAsync::SetUserData().
Referenced by DayZGame(), Inc(), and LoadingShow().
Field Documentation
m_Counter
int m_Counter private
Definition at line 299 of file DayZGame.c.
Referenced by Dec(), Hide(), Inc(), and LoadingScreen().
m_DayZGame
DayZGame m_DayZGame private
Definition at line 288 of file DayZGame.c.
Referenced by Inc(), LoadingScreen(), SetProgress(), and Show().
m_ImageBackground
ImageWidget m_ImageBackground private
Definition at line 294 of file DayZGame.c.
Referenced by LoadingScreen(), and Show().
m_ImageLoadingIcon
ImageWidget m_ImageLoadingIcon private
Definition at line 293 of file DayZGame.c.
Referenced by LoadingScreen().
m_ImageLoadingIconRotation
float m_ImageLoadingIconRotation private
Definition at line 296 of file DayZGame.c.
m_ImageLogoCorner
ImageWidget m_ImageLogoCorner private
Definition at line 292 of file DayZGame.c.
Referenced by LoadingScreen(), and Show().
m_ImageLogoMid
ImageWidget m_ImageLogoMid private
Definition at line 291 of file DayZGame.c.
Referenced by LoadingScreen(), and Show().
m_ImageWidgetBackground
ImageWidget m_ImageWidgetBackground private
Definition at line 287 of file DayZGame.c.
Referenced by LoadingScreen(), and Show().
m_LastProgressUpdate
float m_LastProgressUpdate private
Definition at line 289 of file DayZGame.c.
Referenced by Inc(), and SetProgress().
m_ModdedWarning
TextWidget m_ModdedWarning private
Definition at line 286 of file DayZGame.c.
Referenced by LoadingScreen().
m_ProgressLoading
ProgressBarWidget m_ProgressLoading private
Definition at line 295 of file DayZGame.c.
Referenced by LoadingScreen(), and Show().
m_ProgressText
TextWidget m_ProgressText private
Definition at line 297 of file DayZGame.c.
Referenced by LoadingScreen(), and Show().
m_TextWidgetStatus
TextWidget m_TextWidgetStatus private
Definition at line 285 of file DayZGame.c.
Referenced by LoadingScreen(), SetStatus(), and Show().
m_TextWidgetTitle
TextWidget m_TextWidgetTitle private
Definition at line 284 of file DayZGame.c.
Referenced by LoadingScreen(), SetTitle(), and Show().
m_Timer
ref Timer m_Timer private
Definition at line 300 of file DayZGame.c.
m_WidgetRoot
ref Widget m_WidgetRoot private
Definition at line 283 of file DayZGame.c.
Referenced by EndLoading(), Hide(), IsLoading(), LoadingScreen(), and Show().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/DayZGame.c