DayZ Scripts: BoltActionRifle_Base Class Reference
BoltActionRifle_Base Class Reference
Private Member Functions
override void InitStateMachine ()
override void SetActions ()
Private Attributes
ref WeaponStableState C0
ref WeaponStableState C1
ref WeaponStableState D1
ref WeaponStableState JF
Member Function Documentation
InitStateMachine()
override void InitStateMachine () inline private
SetActions()
override void SetActions () inline private
References AddAction(), FirearmActionLoadBulletQuick(), and RemoveAction().
Field Documentation
C0
ref WeaponStableState C0 private
C1
ref WeaponStableState C1 private
D1
ref WeaponStableState D1 private
JF
ref WeaponStableState JF private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Firearms/BoltActionRifleInnerMagazine_Base.c