DayZ Scripts: MapMarkerTypes Class Reference
MapMarkerTypes Class Reference
Static Private Member Functions
static void Init ()
static void RegisterMarkerType (int id, string path)
static string GetMarkerTypeFromID (int id)
Static Private Attributes
static protected ref map< int, string > m_MarkerTypes
Member Function Documentation
GetMarkerTypeFromID()
static string GetMarkerTypeFromID (int id) inline static private
References m_MarkerTypes.
Referenced by UIScriptedMenu::AddMarker(), UIScriptedMenu::LoadMapMarkers(), and ScriptConsoleGeneralTab::Update().
Init()
static void Init () inline static private
References m_MarkerTypes, and RegisterMarkerType().
Referenced by MissionBase::OnInit().
RegisterMarkerType()
static void RegisterMarkerType (int id, string path) inline static private
References m_MarkerTypes, and path.
Referenced by Init().
Field Documentation
m_MarkerTypes
protected ref map<int,string> m_MarkerTypes static private
Referenced by GetMarkerTypeFromID(), Init(), and RegisterMarkerType().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/MapMarkersInfo.c