DayZ Scripts: P:/scripts/5_Mission/GUI/NewUI/ConsoleToolbarHandler.c File Reference
ConsoleToolbarHandler.c File Reference
Data Structures
class ConsoleToolbarWidgetHandlerBase
Functions
ConsoleToolbarWidgetHandlerBase ScriptedWidgetEventHandler UpdateControlsElements (EInputDeviceType pInputDeviceType=EInputDeviceType.UNKNOWN)
void OnWidgetScriptInit (Widget w)
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
Variables
Widget m_ToolbarWidget
RichTextWidget m_ToolbarText
Function Documentation
OnInputDeviceChanged()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w)
References Input::GetCurrentInputDevice(), GetGame(), CGame::GetInput(), and Input::IsEnabledMouseAndKeyboardEvenOnServer().
UpdateControlsElements()
protected void UpdateControlsElements (EInputDeviceType pInputDeviceType = EInputDeviceType.UNKNOWN)
Variable Documentation
m_ToolbarText
RichTextWidget m_ToolbarText
m_ToolbarWidget
Widget m_ToolbarWidget