DayZ Scripts: CatchingResultBasic Class Reference
CatchingResultBasic Class Reference
Private Member Functions
void CatchingResultBasic (EntityAI owner)
void SetYieldItem (YieldItemBase yItem)
int GetYieldItemParticleId ()
protected void SetCatchChance (float val)
protected void SetQuality (float val)
void SetCatchChanceOverride (bool ovrd, float val=0.0)
void SetQualityOverride (bool ovrd, float val=0.0)
void UpdateCatchQuality (CatchingContextBase ctx)
void UpdateCatchChance (CatchingContextBase ctx)
bool RollChance ()
protected float RollChanceSeeded ()
EntityAI SpawnAndSetup (out int yItemIdx, vector v=vector.Zero)
Private Attributes
protected EntityAI m_Owner
protected bool m_OverrideChanceActive = false
protected bool m_OverrideQualityActive = false
protected float m_CatchChance = 1.0
protected float m_Quality = 1.0
protected YieldItemBase m_YItem
Constructor & Destructor Documentation
CatchingResultBasic()
void CatchingResultBasic (EntityAI owner) inline private
References m_Owner.
Member Function Documentation
GetYieldItemParticleId()
int GetYieldItemParticleId () inline private
References YieldItemBase::GetCatchParticleID(), ParticleList::INVALID, and m_YItem.
Referenced by CatchingContextFishingRodAction::GetResultParticleId().
RollChance()
bool RollChance () inline private
References m_CatchChance, m_Owner, Math::RandomFloat01(), and RollChanceSeeded().
Referenced by RollCatch().
RollChanceSeeded()
protected float RollChanceSeeded () inline private
Referenced by RollChance().
SetCatchChance()
protected void SetCatchChance (float val) inline private
References Math::Clamp(), and m_CatchChance.
Referenced by UpdateCatchChance().
SetCatchChanceOverride()
void SetCatchChanceOverride (bool ovrd, float val = 0.0) inline private
References m_CatchChance, and m_OverrideChanceActive.
Referenced by SetResultChanceOverride().
SetQuality()
protected void SetQuality (float val) inline private
References Math::Clamp(), and m_Quality.
Referenced by UpdateCatchQuality().
SetQualityOverride()
void SetQualityOverride (bool ovrd, float val = 0.0) inline private
References m_OverrideQualityActive, and m_Quality.
Referenced by SetResultQualityOverride().
SetYieldItem()
void SetYieldItem (YieldItemBase yItem) inline private
References m_YItem.
Referenced by GenerateResult(), and CatchingContextFishingRodAction::GenerateResult().
SpawnAndSetup()
EntityAI SpawnAndSetup (out int yItemIdx, vector v = vector.Zero) inline private
References ECE_PLACE_ON_SURFACE, GetGame(), YieldItemBase::GetRegistrationIdx(), YieldItemBase::GetType(), m_Owner, m_YItem, and vector::Zero.
Referenced by SpawnAndSetupCatch().
UpdateCatchChance()
void UpdateCatchChance (CatchingContextBase ctx) inline private
References YieldItemBase::GetChanceForYieldItem(), m_OverrideChanceActive, m_YItem, and SetCatchChance().
Referenced by CatchingContextFishingRodAction::RecalculateProcessingData(), and RollCatch().
UpdateCatchQuality()
void UpdateCatchQuality (CatchingContextBase ctx) inline private
References YieldItemBase::GetQualityForYieldItem(), m_OverrideQualityActive, m_YItem, and SetQuality().
Referenced by SpawnAndSetupCatch().
Field Documentation
m_CatchChance
protected float m_CatchChance = 1.0 private
Referenced by RollChance(), SetCatchChance(), and SetCatchChanceOverride().
m_OverrideChanceActive
protected bool m_OverrideChanceActive = false private
Referenced by SetCatchChanceOverride(), and UpdateCatchChance().
m_OverrideQualityActive
protected bool m_OverrideQualityActive = false private
Referenced by SetQualityOverride(), and UpdateCatchQuality().
m_Owner
protected EntityAI m_Owner private
Referenced by CatchingResultBasic(), RollChance(), CatchingResultBase::RollChanceSeeded(), and SpawnAndSetup().
m_Quality
protected float m_Quality = 1.0 private
Referenced by SetQuality(), SetQualityOverride(), CarchingResultFishingAction::SpawnAndSetup(), and CatchingResultTrapBase::SpawnAndSetup().
m_YItem
protected YieldItemBase m_YItem private
Referenced by CarchingResultFishingAction::GetCurrentCycleTime(), GetYieldItemParticleId(), SetYieldItem(), SpawnAndSetup(), UpdateCatchChance(), and UpdateCatchQuality().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/AnimalCatching/CatchingResultBasic.c