DayZ Scripts: ActionSwitchSeats Class Reference
ActionSwitchSeats Class Reference
Private Member Functions
void ActionSwitchSeats ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void Start (ActionData action_data)
override void OnUpdate (ActionData action_data)
override bool CanBeUsedInVehicle ()
Detailed Description
Definition at line 2 of file ActionSwitchSeats.c.
Constructor & Destructor Documentation
ActionSwitchSeats()
void ActionSwitchSeats () inline private
Definition at line 4 of file ActionSwitchSeats.c.
References m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 19 of file ActionSwitchSeats.c.
References Class::CastTo().
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle () inline private
Definition at line 91 of file ActionSwitchSeats.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 13 of file ActionSwitchSeats.c.
References m_ConditionItem, and m_ConditionTarget.
OnUpdate()
override void OnUpdate (ActionData action_data) inline private
Definition at line 78 of file ActionSwitchSeats.c.
References End(), ActionData::m_Player, ActionData::m_State, and UA_START.
Start()
override void Start (ActionData action_data) inline private
Definition at line 53 of file ActionSwitchSeats.c.
References Class::CastTo(), GetGame(), ActionData::m_Player, ActionData::m_Target, and HumanCommandVehicle::SwitchSeat().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/Vehicles/ActionSwitchSeats.c