DayZ Scripts: CCTWaterSurface Class Reference
CCTWaterSurface Class Reference
Private Member Functions
void CCTWaterSurface (float maximal_target_distance=UAMaxDistances.DEFAULT, string surfaceType="")
override bool Can (PlayerBase player, ActionTarget target)
override bool CanContinue (PlayerBase player, ActionTarget target)
Private Attributes
protected const int HEIGHT_DIFF_LIMIT_METERS = 1.0
protected float m_MaximalActionDistanceSq
protected string m_SurfaceType
protected ref array< string > m_AllowedSurfaceList
DEPRECATED.
Detailed Description
Definition at line 1 of file CCTWaterSurface.c.
Constructor & Destructor Documentation
CCTWaterSurface()
void CCTWaterSurface (float maximal_target_distance = UAMaxDistances.DEFAULT, string surfaceType = "") inline private
Definition at line 9 of file CCTWaterSurface.c.
References m_AllowedSurfaceList, m_MaximalActionDistanceSq, and m_SurfaceType.
Member Function Documentation
Can()
override bool Can (PlayerBase player, ActionTarget target) inline private
use hit position from ActionTarget otherwise player's position
special handling for sea
Definition at line 18 of file CCTWaterSurface.c.
References Math::AbsFloat(), Surface::AllowedWaterSurface(), vector::DistanceSq(), g_Game, HEIGHT_DIFF_LIMIT_METERS, m_AllowedSurfaceList, m_MaximalActionDistanceSq, and vector::Zero.
Referenced by ActionFillBottleBase::ActionCondition().
CanContinue()
override bool CanContinue (PlayerBase player, ActionTarget target) inline private
Definition at line 53 of file CCTWaterSurface.c.
Field Documentation
HEIGHT_DIFF_LIMIT_METERS
protected const int HEIGHT_DIFF_LIMIT_METERS = 1.0 private
Definition at line 3 of file CCTWaterSurface.c.
Referenced by Can().
m_AllowedSurfaceList
protected ref array<string> m_AllowedSurfaceList private
DEPRECATED.
Definition at line 7 of file CCTWaterSurface.c.
Referenced by Can(), and CCTWaterSurface().
m_MaximalActionDistanceSq
protected float m_MaximalActionDistanceSq private
Definition at line 5 of file CCTWaterSurface.c.
Referenced by Can(), and CCTWaterSurface().
m_SurfaceType
protected string m_SurfaceType private
Definition at line 6 of file CCTWaterSurface.c.
Referenced by CCTWaterSurface().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/TargetConditionsComponents/CCTWaterSurface.c