DayZ Scripts: ActionSwitchLights Class Reference
ActionSwitchLights Class Reference
Private Member Functions
void ActionSwitchLights ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
override bool CanBeUsedInVehicle ()
Constructor & Destructor Documentation
ActionSwitchLights()
void ActionSwitchLights () inline private
References AnimatedActionBase::m_CommandUID, ActionBase::m_StanceMask, and ActionBase::m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Class::CastTo(), HumanCommandVehicle::GetTransport(), CarScript::IsVitalCarBattery(), and CarScript::IsVitalTruckBattery().
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References ActionBase::m_ConditionItem, and ActionBase::m_ConditionTarget.
GetInputType()
override GetInputType () inline private
HasTarget()
override bool HasTarget () inline private
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
References Class::CastTo(), and HumanCommandVehicle::GetTransport().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/Vehicles/ActionSwitchLights.c