DayZ Scripts: CholeraMdfr Class Reference
CholeraMdfr Class Reference
Private Member Functions
override void Init ()
override string GetDebugText ()
override protected bool ActivateCondition (PlayerBase player)
override protected void OnActivate (PlayerBase player)
override protected void OnDeactivate (PlayerBase player)
override protected bool DeactivateCondition (PlayerBase player)
override protected void OnTick (PlayerBase player, float deltaT)
Private Attributes
private float m_ExhaustionTimer
private bool m_Exhaustion
Static Private Attributes
static const int AGENT_THRESHOLD_ACTIVATE = 250
static const int AGENT_THRESHOLD_DEACTIVATE = 50
static const int CHANCE_OF_VOMIT = 10
static const int CHANCE_OF_VOMIT_AGENT = 30
static const int WATER_DRAIN_FROM_VOMIT = 450
static const int ENERGY_DRAIN_FROM_VOMIT = 310
static const float WATER_LOSS_CHOLERA = 0.5
static const float WATER_LOSS_CHOLERA_MIN = 0.1
static const float STOMACH_MIN_VOLUME = 200
Member Function Documentation
ActivateCondition()
override protected bool ActivateCondition (PlayerBase player) inline private
References AGENT_THRESHOLD_ACTIVATE.
DeactivateCondition()
override protected bool DeactivateCondition (PlayerBase player) inline private
References AGENT_THRESHOLD_DEACTIVATE.
GetDebugText()
override string GetDebugText () inline private
References AGENT_THRESHOLD_ACTIVATE, and AGENT_THRESHOLD_DEACTIVATE.
Init()
override void Init () inline private
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, m_AnalyticsStatsEnabled, m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override protected void OnActivate (PlayerBase player) inline private
References CachedObjectsParams::PARAM1_FLOAT, Math::RandomIntInclusive(), SymptomBase::SetDuration(), and SymptomBase::SetParam().
OnDeactivate()
override protected void OnDeactivate (PlayerBase player) inline private
References m_Exhaustion, and m_ExhaustionTimer.
OnTick()
override protected void OnTick (PlayerBase player, float deltaT) inline private
References CHANCE_OF_VOMIT, CHANCE_OF_VOMIT_AGENT, ENERGY_DRAIN_FROM_VOMIT, m_Exhaustion, m_ExhaustionTimer, m_Player, Math::Max(), CachedObjectsParams::PARAM1_FLOAT, Math::RandomInt(), Math::RandomIntInclusive(), SymptomBase::SetDuration(), SymptomBase::SetParam(), STOMACH_MIN_VOLUME, WATER_DRAIN_FROM_VOMIT, WATER_LOSS_CHOLERA, and WATER_LOSS_CHOLERA_MIN.
Field Documentation
AGENT_THRESHOLD_ACTIVATE
const int AGENT_THRESHOLD_ACTIVATE = 250 static private
Referenced by ActivateCondition(), and GetDebugText().
AGENT_THRESHOLD_DEACTIVATE
const int AGENT_THRESHOLD_DEACTIVATE = 50 static private
Referenced by DeactivateCondition(), and GetDebugText().
CHANCE_OF_VOMIT
const int CHANCE_OF_VOMIT = 10 static private
Referenced by OnTick().
CHANCE_OF_VOMIT_AGENT
const int CHANCE_OF_VOMIT_AGENT = 30 static private
Referenced by OnTick().
ENERGY_DRAIN_FROM_VOMIT
const int ENERGY_DRAIN_FROM_VOMIT = 310 static private
Referenced by OnTick().
m_Exhaustion
private bool m_Exhaustion private
Referenced by OnDeactivate(), and OnTick().
m_ExhaustionTimer
private float m_ExhaustionTimer private
Referenced by OnDeactivate(), and OnTick().
STOMACH_MIN_VOLUME
const float STOMACH_MIN_VOLUME = 200 static private
Referenced by OnTick().
WATER_DRAIN_FROM_VOMIT
const int WATER_DRAIN_FROM_VOMIT = 450 static private
Referenced by OnTick().
WATER_LOSS_CHOLERA
const float WATER_LOSS_CHOLERA = 0.5 static private
Referenced by OnTick().
WATER_LOSS_CHOLERA_MIN
const float WATER_LOSS_CHOLERA_MIN = 0.1 static private
Referenced by OnTick().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/diseases/Cholera.c