DayZ Scripts: YieldItemBase Class Reference
YieldItemBase Class Reference
Private Member Functions
void YieldItemBase (int baseWeight)
void Init ()
string GetType ()
int GetRegistrationIdx ()
void SetRegistrationIdx (int idx)
int GetYieldWeight (CatchingContextBase ctx)
int GetEnviroMask ()
int GetMethodMask ()
float GetBaitTypeSensitivity (ECatchingBaitCategories type)
float GetQualityForYieldItem (CatchingContextBase ctx)
float GetChanceForYieldItem (CatchingContextBase ctx)
string GetCatchDeathSoundset ()
string GetCatchAINoise ()
float GetCatchAINoiseBaseStrength ()
int GetCatchParticleID ()
Private Attributes
protected string m_Type
protected int m_RegistrationIdx = -1
protected int m_BaseWeight
protected float m_QualityBase = AnimalCatchingConstants.QUALITY_GENERIC_BASE
protected int m_EnviroMask
protected int m_MethodMask
Constructor & Destructor Documentation
YieldItemBase()
void YieldItemBase (int baseWeight) inline private
References Init(), and m_BaseWeight.
Member Function Documentation
GetBaitTypeSensitivity()
float GetBaitTypeSensitivity (ECatchingBaitCategories type) inline private
Referenced by CheckBaitCompatibility(), and CatchingContextTrapsBase::UpdateBaseProbability().
GetCatchAINoise()
string GetCatchAINoise () inline private
Referenced by ItemBase::PlayCatchNoise().
GetCatchAINoiseBaseStrength()
float GetCatchAINoiseBaseStrength () inline private
Referenced by ItemBase::PlayCatchNoise().
GetCatchDeathSoundset()
string GetCatchDeathSoundset () inline private
Referenced by ItemBase::PlayCatchSound().
GetCatchParticleID()
int GetCatchParticleID () inline private
References ParticleList::INVALID.
Referenced by CatchingResultBasic::GetYieldItemParticleId(), and ItemBase::PlayCatchParticleSynced().
GetChanceForYieldItem()
float GetChanceForYieldItem (CatchingContextBase ctx) inline private
Referenced by CatchingResultBasic::UpdateCatchChance().
GetEnviroMask()
int GetEnviroMask () inline private
References m_EnviroMask.
Referenced by CheckMaskCompatibility().
GetMethodMask()
int GetMethodMask () inline private
References m_MethodMask.
Referenced by CheckMaskCompatibility().
GetQualityForYieldItem()
float GetQualityForYieldItem (CatchingContextBase ctx) inline private
References m_QualityBase.
Referenced by CatchingResultBasic::UpdateCatchQuality().
GetRegistrationIdx()
int GetRegistrationIdx () inline private
References m_RegistrationIdx.
Referenced by CatchingResultBasic::SpawnAndSetup().
GetType()
string GetType () inline private
References m_Type.
Referenced by CatchYieldBank::RegisterYieldItem(), SetupProbabilityArray(), and CatchingResultBasic::SpawnAndSetup().
GetYieldWeight()
int GetYieldWeight (CatchingContextBase ctx) inline private
References m_BaseWeight.
Referenced by SetupProbabilityArray().
Init()
void Init () private
Referenced by YieldItemBase().
SetRegistrationIdx()
void SetRegistrationIdx (int idx) inline private
References ErrorEx, and m_RegistrationIdx.
Referenced by CatchYieldBank::RegisterYieldItem().
Field Documentation
m_BaseWeight
protected int m_BaseWeight private
Referenced by GetYieldWeight(), and YieldItemBase().
m_EnviroMask
protected int m_EnviroMask private
Referenced by GetEnviroMask(), YieldItemSardines::Init(), YieldItemWalleyePollock::Init(), YieldItemShrimp::Init(), YieldItemJunk::Init(), YieldItemDeadRabbit::Init(), and YieldItemCapraHircusBase::Init().
m_MethodMask
protected int m_MethodMask private
Referenced by GetMethodMask(), YieldItemSardines::Init(), YieldItemWalleyePollock::Init(), YieldItemShrimp::Init(), YieldItemJunk::Init(), YieldItemDeadRabbit::Init(), and YieldItemCapraHircusBase::Init().
m_QualityBase
protected float m_QualityBase = AnimalCatchingConstants.QUALITY_GENERIC_BASE private
Referenced by GetQualityForYieldItem(), and FishYieldItemBase::Init().
m_RegistrationIdx
protected int m_RegistrationIdx = -1 private
Referenced by GetRegistrationIdx(), and SetRegistrationIdx().
m_Type
protected string m_Type private
Referenced by GetType(), YieldItemSardines::Init(), YieldItemWalleyePollock::Init(), YieldItemShrimp::Init(), YieldItemDeadRabbit::Init(), YieldItemDeadChicken_White::Init(), YieldItemDeadChicken_Brown::Init(), and YieldItemJunk::YieldItemJunk().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/AnimalCatching/CatchYieldItemBase.c