DayZ Scripts: MenuData Class Reference
MenuData Class Reference
Private Member Functions
proto native int GetCharactersCount ()
proto native int GetLastPlayedCharacter ()
proto native Man CreateCharacterPerson (int index)
Return Character person or null if character initialization failed (inventory load, or corrupted data)
proto void GetLastServerAddress (int index, out string address)
proto native int GetLastServerPort (int index)
proto void GetLastServerName (int index, out string address)
proto void RequestSetDefaultCharacterData ()
proto bool RequestGetDefaultCharacterData ()
void OnSetDefaultCharacter (ParamsWriteContext ctx)
Actual DefaultCharacter saving.
bool OnGetDefaultCharacter (ParamsReadContext ctx)
Actual DefaultCharacter loading.
proto void GetCharacterName (int index, out string name)
proto native void SetCharacterName (int index, string newName)
proto native void SaveCharacter (bool localPlayer, bool verified)
proto native void SaveDefaultCharacter (Man character)
proto native void SaveCharactersLocal ()
Saves characters menu data to file.
proto native void LoadCharactersLocal ()
Loads characters menu data from file.
proto native void ClearCharacters ()
MenuDefaultCharacterData GetMenuDefaultCharacterDataInstance ()
Detailed Description
Definition at line 864 of file gameplay.c.
Member Function Documentation
ClearCharacters()
proto native void ClearCharacters () private
Referenced by DayZIntroSceneXbox::~DayZIntroSceneXbox().
CreateCharacterPerson()
proto native Man CreateCharacterPerson (int index) private
Return Character person or null if character initialization failed (inventory load, or corrupted data)
Referenced by Managed::CharacterLoad().
GetCharacterName()
proto void GetCharacterName (int index, out string name) private
Referenced by DayZIntroSceneXbox::DayZIntroSceneXbox(), Managed::GetCharacterName(), Managed::GetCharacterNameById(), Managed::LoadCharacterData(), and Managed::SetupPlayerName().
GetCharactersCount()
proto native int GetCharactersCount () private
Referenced by DayZIntroSceneXbox::DayZIntroSceneXbox(), Managed::GetNextCharacterID(), Managed::GetPrevCharacterID(), ManBase::OnSelectPlayer(), and DayZIntroSceneXbox::SaveCharName().
GetLastPlayedCharacter()
proto native int GetLastPlayedCharacter () private
Referenced by DayZIntroSceneXbox::DayZIntroSceneXbox(), Managed::LoadCharacterData(), ManBase::OnSelectPlayer(), and UIScriptedMenu::SetServerInfo().
GetLastServerAddress()
proto void GetLastServerAddress (int index, out string address) private
Referenced by Managed::GetLastPlayedServer(), and UIScriptedMenu::SetServerInfo().
GetLastServerName()
proto void GetLastServerName (int index, out string address) private
Referenced by Managed::GetLastPlayedServer(), and UIScriptedMenu::SetServerInfo().
GetLastServerPort()
proto native int GetLastServerPort (int index) private
Referenced by Managed::GetLastPlayedServer(), and UIScriptedMenu::SetServerInfo().
GetMenuDefaultCharacterDataInstance()
MenuDefaultCharacterData GetMenuDefaultCharacterDataInstance () inline private
Definition at line 919 of file gameplay.c.
References GetGame(), and CGame::GetMenuDefaultCharacterData().
Referenced by OnGetDefaultCharacter(), and OnSetDefaultCharacter().
LoadCharactersLocal()
proto native void LoadCharactersLocal () private
Loads characters menu data from file.
Referenced by MenuDefaultCharacterData::Init().
OnGetDefaultCharacter()
bool OnGetDefaultCharacter (ParamsReadContext ctx) inline private
Actual DefaultCharacter loading.
Definition at line 892 of file gameplay.c.
References Error(), and GetMenuDefaultCharacterDataInstance().
OnSetDefaultCharacter()
void OnSetDefaultCharacter (ParamsWriteContext ctx) inline private
Actual DefaultCharacter saving.
Definition at line 879 of file gameplay.c.
References Error(), GetMenuDefaultCharacterDataInstance(), SaveCharactersLocal(), and MenuDefaultCharacterData::SerializeCharacterData().
RequestGetDefaultCharacterData()
proto bool RequestGetDefaultCharacterData () private
Referenced by UIScriptedMenu::Back(), and CGame::GetMenuDefaultCharacterData().
RequestSetDefaultCharacterData()
proto void RequestSetDefaultCharacterData () private
Referenced by Managed::SaveDefaultCharacter().
SaveCharacter()
proto native void SaveCharacter (bool localPlayer, bool verified) private
SaveCharactersLocal()
proto native void SaveCharactersLocal () private
Saves characters menu data to file.
Referenced by OnSetDefaultCharacter(), Managed::SaveCharName(), and DayZIntroSceneXbox::SaveCharName().
SaveDefaultCharacter()
proto native void SaveDefaultCharacter (Man character) private
SetCharacterName()
proto native void SetCharacterName (int index, string newName) private
Referenced by Managed::SaveCharName(), and DayZIntroSceneXbox::SaveCharName().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/gameplay.c