DayZ Scripts: ActionSingleUseBase Class Reference
ActionSingleUseBase Class Reference
Private Member Functions
void ActionSingleUseBase ()
override GetInputType ()
override int GetActionCategory ()
void ActionPin ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecute (ActionData action_data)
void ActionUnpin ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecute (ActionData action_data)
Constructor & Destructor Documentation
ActionSingleUseBase()
void ActionSingleUseBase () inline private
References AnimatedActionBase::m_CallbackClass, and AnimatedActionBase::m_CommandUID.
Member Function Documentation
ActionCondition() [1/2]
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Grenade_Base::IsPinnable(), and Grenade_Base::IsPinned().
ActionCondition() [2/2]
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References Grenade_Base::IsPinned().
ActionPin()
void ActionPin () inline private
References m_Text.
ActionUnpin()
void ActionUnpin () inline private
References m_Text.
CreateConditionComponents() [1/2]
override void CreateConditionComponents () inline private
References m_ConditionItem, and m_ConditionTarget.
CreateConditionComponents() [2/2]
override void CreateConditionComponents () inline private
References m_ConditionItem, and m_ConditionTarget.
GetActionCategory()
override int GetActionCategory () inline private
References AC_SINGLE_USE.
GetInputType()
override GetInputType () inline private
HasTarget() [1/2]
override bool HasTarget () inline private
HasTarget() [2/2]
override bool HasTarget () inline private
OnExecute() [1/2]
override void OnExecute (ActionData action_data) inline private
References ActionData::m_MainItem, and Grenade_Base::Pin().
OnExecute() [2/2]
override void OnExecute (ActionData action_data) inline private
References ActionData::m_MainItem, and Grenade_Base::Unpin().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/ActionSingleUseBase.c
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionPin.c
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionUnpin.c