DayZ Scripts: 5_Mission/GUI/ItemDropWarningMenu.c File Reference
ItemDropWarningMenu.c File Reference
Data Structures
class WarningMenuBase
class PlayerRepositionWarningMenu
Functions
WarningMenuBase UIScriptedMenu GetText ()
void WarningMenuBase ()
void ~WarningMenuBase ()
override Widget Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
override bool OnClick (Widget w, int x, int y, int button)
override void Update (float timeslice)
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
protected void UpdateControlsElements ()
protected void UpdateControlsElementVisibility ()
Variables
protected ButtonWidget m_OkButton
protected MultilineTextWidget m_Description
Function Documentation
GetText()
WarningMenuBase UIScriptedMenu GetText ()
Init()
override Widget Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
pre-init arrays
OnClick()
override bool OnClick (Widget w, int x, int y, int button)
OnInputDeviceChanged()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
OnInputPresetChanged()
protected void OnInputPresetChanged ()
Update()
override void Update (float timeslice)
UpdateControlsElements()
protected void UpdateControlsElements ()
Referenced by UIScriptedMenu::ChangeCurrentCategory(), UIScriptedMenu::Init(), UIScriptedMenu::OnInputPresetChanged(), and UIScriptedMenu::RefreshGestures().
UpdateControlsElementVisibility()
protected void UpdateControlsElementVisibility ()
WarningMenuBase()
void WarningMenuBase ()
~WarningMenuBase()
void ~WarningMenuBase ()
Variable Documentation
m_Description
protected MultilineTextWidget m_Description
m_OkButton
protected ButtonWidget m_OkButton