DayZ Scripts: Inventory_Base Class Reference
Inventory_Base Class Reference
Private Member Functions
override void SetActions ()
void HescoBox ()
void ~HescoBox ()
override bool HasProxyParts ()
override bool CanPutIntoHands (EntityAI parent)
void Synchronize ()
override void OnVariablesSynchronized ()
void RefreshVisuals ()
int GetState ()
void SetState (int state)
bool CanBeFilledAtPosition (vector position)
bool CanBeManipulated ()
void Fold ()
void Unfold ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void RefreshPhysics ()
void Fill ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool IsDeployable ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
void PlayDeployLoopSound ()
void StopDeployLoopSound ()
override void SetActions ()
override bool CanDetachAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI attachment)
override bool CanPutInCargo (EntityAI parent)
void FryingPan ()
DEPRECATED.
void ~FryingPan ()
override bool IsContainer ()
override bool CanHaveTemperature ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override void SetActions ()
override void EEDelete (EntityAI parent)
void Synchronize ()
override void OnVariablesSynchronized ()
void RemoveAudioVisualsOnClient ()
void RefreshAudioVisualsOnClient (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
void RefreshAudioVisuals (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
void RemoveAudioVisuals ()
void ParticleCookingStart (int particle_id)
void ParticleCookingStop ()
protected void SoundCookingStart (string sound_name)
DEPRECATED.
protected void SoundCookingStop ()
override bool CanDetachAttachment (EntityAI parent)
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override bool CanPutAsAttachment (EntityAI parent)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void SetActions ()
override bool CanDetachAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override bool IsMeleeFinisher ()
override array< int > GetValidFinishers ()
override bool CanPutAsAttachment (EntityAI parent)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void SetActions ()
override void SetActions ()
void SeedPackBase ()
void EmptySeedPack (PlayerBase player)
override void SetActions ()
override void SetActions ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
void XmasLights ()
override bool IsElectricAppliance ()
override void OnWorkStart ()
override void OnWorkStop ()
void AttachToObject (ItemBase parent)
void DetachFromObject (ItemBase parent)
void TurnOnItem (ItemBase item)
void TurnOffItem (ItemBase item)
void HideOnItem (ItemBase item)
override void SetActions ()
Private Attributes
ref Timer m_Timer
ref protected EffectSound m_DeployLoopSound
protected int m_State
protected CookingMethodType m_CookingMethod
protected bool m_CookingIsDone
protected bool m_CookingIsEmpty
protected bool m_CookingIsBurned
protected Particle m_ParticleCooking
protected int m_ParticlePlaying = ParticleList.INVALID
protected int PARTICLE_BAKING_START = ParticleList.COOKING_BAKING_START
protected int PARTICLE_BAKING_DONE = ParticleList.COOKING_BAKING_DONE
protected int PARTICLE_DRYING_START = ParticleList.COOKING_DRYING_START
protected int PARTICLE_DRYING_DONE = ParticleList.COOKING_DRYING_DONE
protected int PARTICLE_BURNING_DONE = ParticleList.COOKING_BURNING_DONE
protected SoundOnVehicle m_SoundCooking
protected EffectSound m_SoundEffectCooking
DEPRECATED.
protected string m_SoundPlaying = ""
const string SOUND_BAKING_START = "Baking_SoundSet"
const string SOUND_BAKING_DONE = "Baking_Done_SoundSet"
DEPRECATED.
const string SOUND_DRYING_START = "Drying_SoundSet"
DEPRECATED.
const string SOUND_DRYING_DONE = "Drying_Done_SoundSet"
DEPRECATED.
const string SOUND_BURNING_DONE = "Food_Burning_SoundSet"
DEPRECATED.
private ItemBase m_AttachedTo = NULL
Static Private Attributes
static const int FOLDED = 0
static const int UNFOLDED = 1
static const int FILLED = 2
static const int PERCENTUAL_DAMAGE = 1
static private const float PACK_DAMAGE_TOLERANCE = 0.5
Detailed Description
Definition at line 1 of file BarbedBaseballBat.c.
Constructor & Destructor Documentation
~HescoBox()
void ~HescoBox () inline private
Definition at line 23 of file HescoBox.c.
References SEffectManager::DestroyEffect(), and m_DeployLoopSound.
~FryingPan()
void ~FryingPan () inline private
Definition at line 37 of file FryingPan.c.
Member Function Documentation
AttachToObject()
void AttachToObject (ItemBase parent) inline private
Definition at line 27 of file XmasLights.c.
References TurnOnItem().
CanBeFilledAtPosition()
bool CanBeFilledAtPosition (vector position) inline private
Definition at line 84 of file HescoBox.c.
References GetGame(), CGame::IsSurfaceDigable(), and CGame::SurfaceGetType().
CanBeManipulated()
bool CanBeManipulated () inline private
Definition at line 92 of file HescoBox.c.
References FOLDED, and GetState().
Referenced by CanPutIntoHands().
CanDetachAttachment() [1/6]
override bool CanDetachAttachment (EntityAI attachment) inline private
Definition at line 27 of file AtlasBipod.c.
CanDetachAttachment() [2/6]
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 3 of file AK_RailHndgrd.c.
CanDetachAttachment() [3/6]
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 3 of file M4_RISHndgrd.c.
CanDetachAttachment() [4/6]
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 3 of file MP5_RailHndgrd.c.
CanDetachAttachment() [5/6]
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 42 of file Nail.c.
CanDetachAttachment() [6/6]
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 59 of file PlantMaterial.c.
CanHaveTemperature()
override bool CanHaveTemperature () inline private
Definition at line 44 of file FryingPan.c.
CanLoadItemIntoCargo()
override bool CanLoadItemIntoCargo (EntityAI item) inline private
Definition at line 71 of file FryingPan.c.
References IsCargoException4x3().
CanPutAsAttachment() [1/6]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file AtlasBipod.c.
CanPutAsAttachment() [2/6]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 13 of file Mosin_Bayonet.c.
CanPutAsAttachment() [3/6]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file Nail.c.
CanPutAsAttachment() [4/6]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file PlantMaterial.c.
CanPutAsAttachment() [5/6]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file Red9Bttstck.c.
CanPutAsAttachment() [6/6]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 13 of file SKS_Bayonet.c.
CanPutInCargo() [1/2]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 3 of file Candle.c.
CanPutInCargo() [2/2]
override bool CanPutInCargo (EntityAI parent) inline private
Definition at line 49 of file FryingPan.c.
References IsCargoException4x3().
CanPutIntoHands()
override bool CanPutIntoHands (EntityAI parent) inline private
Definition at line 33 of file HescoBox.c.
References CanBeManipulated().
CanReceiveItemIntoCargo()
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 60 of file FryingPan.c.
References IsCargoException4x3().
DetachFromObject()
void DetachFromObject (ItemBase parent) inline private
Definition at line 46 of file XmasLights.c.
References HideOnItem(), and TurnOnItem().
EEDelete()
override void EEDelete (EntityAI parent) inline private
Definition at line 92 of file FryingPan.c.
References RemoveAudioVisuals().
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 140 of file HescoBox.c.
EmptySeedPack()
void EmptySeedPack (PlayerBase player) inline private
Definition at line 9 of file SeedPackBase.c.
References CGame::ConfigGetInt(), CGame::ConfigGetText(), CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, EmptySeedsPackLambda(), GetGame(), GetHealth01(), GetPosition, GetType(), CGame::ObjectDelete(), and Math::Round().
Fill()
void Fill () inline private
Definition at line 178 of file HescoBox.c.
References DecreaseHealth(), GetGame(), RefreshPhysics(), SetAllowDamage(), SetState(), and Synchronize().
Referenced by OnStoreLoad().
Fold()
void Fold () inline private
Definition at line 104 of file HescoBox.c.
References DecreaseHealth(), FOLDED, GetGame(), GetMaxHealth(), RefreshPhysics(), SetAllowDamage(), SetState(), and Synchronize().
Referenced by OnStoreLoad().
FryingPan()
void FryingPan () inline private
DEPRECATED.
Definition at line 30 of file FryingPan.c.
GetDeploySoundset()
override string GetDeploySoundset () inline private
Definition at line 255 of file HescoBox.c.
GetLoopDeploySoundset()
override string GetLoopDeploySoundset () inline private
Definition at line 260 of file HescoBox.c.
Referenced by PlayDeployLoopSound().
GetState()
int GetState () inline private
Definition at line 74 of file HescoBox.c.
References m_State.
Referenced by CanBeIgnitedBy(), CanBeManipulated(), OnInventoryEnter(), and RefreshPhysics().
GetValidFinishers() [1/2]
override array< int > GetValidFinishers () inline private
Definition at line 8 of file Mosin_Bayonet.c.
GetValidFinishers() [2/2]
override array< int > GetValidFinishers () inline private
Definition at line 8 of file SKS_Bayonet.c.
HasProxyParts()
override bool HasProxyParts () inline private
Definition at line 28 of file HescoBox.c.
HescoBox()
void HescoBox () inline private
Definition at line 13 of file HescoBox.c.
References FOLDED, FOLDED, and m_State.
HideOnItem()
void HideOnItem (ItemBase item) inline private
Definition at line 94 of file XmasLights.c.
Referenced by DetachFromObject().
IsContainer()
override bool IsContainer () inline private
Definition at line 39 of file FryingPan.c.
IsDeployable()
override bool IsDeployable () inline private
Definition at line 250 of file HescoBox.c.
IsElectricAppliance()
override bool IsElectricAppliance () inline private
Definition at line 10 of file XmasLights.c.
IsMeleeFinisher() [1/2]
override bool IsMeleeFinisher () inline private
Definition at line 3 of file Mosin_Bayonet.c.
IsMeleeFinisher() [2/2]
override bool IsMeleeFinisher () inline private
Definition at line 3 of file SKS_Bayonet.c.
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 238 of file HescoBox.c.
References GetGame(), SetIsDeploySound(), and Unfold().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 203 of file HescoBox.c.
References Fill(), FILLED, Fold(), FOLDED, Serializer::Read(), Unfold(), and UNFOLDED.
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 195 of file HescoBox.c.
References m_State, and Serializer::Write().
OnVariablesSynchronized() [1/2]
override void OnVariablesSynchronized () inline private
Definition at line 47 of file HescoBox.c.
References CanPlayDeployLoopSound(), IsDeploySound(), m_DeployLoopSound, PlayDeployLoopSound(), PlayDeploySound(), RefreshVisuals(), and StopDeployLoopSound().
OnVariablesSynchronized() [2/2]
override void OnVariablesSynchronized () inline private
Definition at line 108 of file FryingPan.c.
References m_CookingIsBurned, m_CookingIsDone, m_CookingIsEmpty, m_CookingMethod, RefreshAudioVisuals(), and RemoveAudioVisuals().
OnWasAttached() [1/3]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 23 of file Mosin_Bayonet.c.
OnWasAttached() [2/3]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 23 of file SKS_Bayonet.c.
OnWasAttached() [3/3]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 3 of file Attachments.c.
OnWasDetached() [1/3]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 33 of file Mosin_Bayonet.c.
OnWasDetached() [2/3]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 33 of file SKS_Bayonet.c.
OnWasDetached() [3/3]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 13 of file Attachments.c.
OnWorkStart()
override void OnWorkStart () inline private
Definition at line 15 of file XmasLights.c.
References TurnOnItem().
OnWorkStop()
override void OnWorkStop () inline private
Definition at line 21 of file XmasLights.c.
References TurnOffItem().
ParticleCookingStart()
void ParticleCookingStart (int particle_id) inline private
Definition at line 176 of file FryingPan.c.
References GetGame(), m_ParticleCooking, m_ParticlePlaying, particle_id, ParticleCookingStop(), and ParticleManager().
Referenced by RefreshAudioVisuals().
ParticleCookingStop()
void ParticleCookingStop () inline private
Definition at line 194 of file FryingPan.c.
References GetGame(), ParticleList::INVALID, m_ParticleCooking, and m_ParticlePlaying.
Referenced by ParticleCookingStart(), and RemoveAudioVisuals().
PlayDeployLoopSound()
void PlayDeployLoopSound () inline private
Definition at line 265 of file HescoBox.c.
References GetGame(), GetLoopDeploySoundset(), GetPosition, EffectSound::IsSoundPlaying(), m_DeployLoopSound, and SEffectManager::PlaySound().
Referenced by OnVariablesSynchronized().
RefreshAudioVisuals()
void RefreshAudioVisuals (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned) inline private
Definition at line 140 of file FryingPan.c.
References PARTICLE_BAKING_DONE, PARTICLE_BAKING_START, PARTICLE_BURNING_DONE, PARTICLE_DRYING_DONE, PARTICLE_DRYING_START, and ParticleCookingStart().
Referenced by OnVariablesSynchronized().
RefreshAudioVisualsOnClient()
void RefreshAudioVisualsOnClient (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned) inline private
Definition at line 130 of file FryingPan.c.
References m_CookingIsBurned, m_CookingIsDone, m_CookingIsEmpty, m_CookingMethod, and Synchronize().
RefreshPhysics()
override void RefreshPhysics () inline private
Definition at line 147 of file HescoBox.c.
References AddProxyPhysics(), FILLED, FOLDED, GetState(), RemoveProxyPhysics(), ToDelete(), and UNFOLDED.
Referenced by Fill(), Fold(), and Unfold().
RefreshVisuals()
void RefreshVisuals () inline private
Definition at line 70 of file HescoBox.c.
Referenced by OnVariablesSynchronized().
RemoveAudioVisuals()
void RemoveAudioVisuals () inline private
Definition at line 171 of file FryingPan.c.
References ParticleCookingStop().
Referenced by EEDelete(), and OnVariablesSynchronized().
RemoveAudioVisualsOnClient()
void RemoveAudioVisualsOnClient () inline private
Definition at line 123 of file FryingPan.c.
References m_CookingMethod, and Synchronize().
SeedPackBase()
void SeedPackBase () inline private
Definition at line 5 of file SeedPackBase.c.
SetActions() [1/10]
override void SetActions () inline private
Definition at line 3 of file Hammer.c.
References AddAction().
SetActions() [2/10]
override void SetActions () inline private
Definition at line 285 of file HescoBox.c.
References ActionDeployObject(), and AddAction().
SetActions() [3/10]
override void SetActions () inline private
Definition at line 82 of file FryingPan.c.
References ActionAttach(), ActionDetach(), and AddAction().
SetActions() [4/10]
override void SetActions () inline private
Definition at line 43 of file Mosin_Bayonet.c.
References AddAction().
SetActions() [5/10]
override void SetActions () inline private
Definition at line 84 of file PlantMaterial.c.
References AddAction().
SetActions() [6/10]
override void SetActions () inline private
Definition at line 43 of file SKS_Bayonet.c.
References AddAction().
SetActions() [7/10]
override void SetActions () inline private
Definition at line 3 of file PipeWrench.c.
References AddAction().
SetActions() [8/10]
override void SetActions () inline private
Definition at line 40 of file SeedPackBase.c.
References AddAction().
SetActions() [9/10]
override void SetActions () inline private
Definition at line 3 of file SledgeHammer.c.
References AddAction().
SetActions() [10/10]
override void SetActions () inline private
Definition at line 113 of file XmasLights.c.
References AddAction().
SetState()
void SetState (int state) inline private
Definition at line 79 of file HescoBox.c.
References m_State.
Referenced by Arm(), Disarm(), Fill(), Fold(), MakeRingingStart(), MakeRingingStop(), OnIgnitedThis(), OnInventoryEnter(), and Unfold().
SoundCookingStart()
protected void SoundCookingStart (string sound_name) private
DEPRECATED.
SoundCookingStop()
protected void SoundCookingStop () private
StopDeployLoopSound()
void StopDeployLoopSound () inline private
Definition at line 276 of file HescoBox.c.
References GetGame(), m_DeployLoopSound, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
Referenced by OnVariablesSynchronized().
Synchronize() [1/2]
void Synchronize () inline private
Definition at line 42 of file HescoBox.c.
Referenced by Fill(), Fold(), RefreshAudioVisualsOnClient(), RemoveAudioVisualsOnClient(), and Unfold().
Synchronize() [2/2]
void Synchronize () inline private
Definition at line 100 of file FryingPan.c.
References GetGame().
TurnOffItem()
void TurnOffItem (ItemBase item) inline private
Definition at line 78 of file XmasLights.c.
Referenced by OnWorkStop(), TurnOnItem(), and XmasLights().
TurnOnItem()
void TurnOnItem (ItemBase item) inline private
Definition at line 55 of file XmasLights.c.
References TurnOffItem().
Referenced by AttachToObject(), DetachFromObject(), and OnWorkStart().
Unfold()
void Unfold () inline private
Definition at line 122 of file HescoBox.c.
References DecreaseHealth(), GetGame(), GetMaxHealth(), RefreshPhysics(), SetAllowDamage(), SetState(), and Synchronize().
Referenced by OnPlacementComplete(), and OnStoreLoad().
XmasLights()
void XmasLights () inline private
Definition at line 5 of file XmasLights.c.
References TurnOffItem().
Field Documentation
FILLED
const int FILLED = 2 static private
Definition at line 5 of file HescoBox.c.
Referenced by OnStoreLoad(), and RefreshPhysics().
FOLDED
const int FOLDED = 0 static private
Definition at line 3 of file HescoBox.c.
Referenced by HescoBox(), OnStoreLoad(), and RefreshPhysics().
m_AttachedTo
private ItemBase m_AttachedTo = NULL private
Definition at line 3 of file XmasLights.c.
m_CookingIsBurned
protected bool m_CookingIsBurned private
Definition at line 7 of file FryingPan.c.
m_CookingIsDone
protected bool m_CookingIsDone private
Definition at line 5 of file FryingPan.c.
m_CookingIsEmpty
protected bool m_CookingIsEmpty private
Definition at line 6 of file FryingPan.c.
m_CookingMethod
protected CookingMethodType m_CookingMethod private
Definition at line 4 of file FryingPan.c.
m_DeployLoopSound
ref protected EffectSound m_DeployLoopSound private
Definition at line 9 of file HescoBox.c.
m_ParticleCooking
protected Particle m_ParticleCooking private
Definition at line 10 of file FryingPan.c.
m_ParticlePlaying
protected int m_ParticlePlaying = ParticleList.INVALID private
Definition at line 11 of file FryingPan.c.
m_SoundCooking
protected SoundOnVehicle m_SoundCooking private
Definition at line 20 of file FryingPan.c.
m_SoundEffectCooking
protected EffectSound m_SoundEffectCooking private
DEPRECATED.
Definition at line 21 of file FryingPan.c.
m_SoundPlaying
protected string m_SoundPlaying = "" private
Definition at line 22 of file FryingPan.c.
m_State
protected int m_State private
Definition at line 11 of file HescoBox.c.
Referenced by GetState(), GetState(), and OnVariablesSynchronized().
m_Timer
ref Timer m_Timer private
Definition at line 8 of file HescoBox.c.
PACK_DAMAGE_TOLERANCE
private const float PACK_DAMAGE_TOLERANCE = 0.5 static private
Definition at line 3 of file SeedPackBase.c.
PARTICLE_BAKING_DONE
protected int PARTICLE_BAKING_DONE = ParticleList.COOKING_BAKING_DONE private
Definition at line 14 of file FryingPan.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BAKING_START
protected int PARTICLE_BAKING_START = ParticleList.COOKING_BAKING_START private
Definition at line 13 of file FryingPan.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BURNING_DONE
protected int PARTICLE_BURNING_DONE = ParticleList.COOKING_BURNING_DONE private
Definition at line 17 of file FryingPan.c.
Referenced by RefreshAudioVisuals().
PARTICLE_DRYING_DONE
protected int PARTICLE_DRYING_DONE = ParticleList.COOKING_DRYING_DONE private
Definition at line 16 of file FryingPan.c.
Referenced by RefreshAudioVisuals().
PARTICLE_DRYING_START
protected int PARTICLE_DRYING_START = ParticleList.COOKING_DRYING_START private
Definition at line 15 of file FryingPan.c.
Referenced by RefreshAudioVisuals().
PERCENTUAL_DAMAGE
const int PERCENTUAL_DAMAGE = 1 static private
Definition at line 6 of file HescoBox.c.
SOUND_BAKING_DONE
const string SOUND_BAKING_DONE = "Baking_Done_SoundSet" private
DEPRECATED.
Definition at line 25 of file FryingPan.c.
SOUND_BAKING_START
const string SOUND_BAKING_START = "Baking_SoundSet" private
Definition at line 24 of file FryingPan.c.
SOUND_BURNING_DONE
const string SOUND_BURNING_DONE = "Food_Burning_SoundSet" private
DEPRECATED.
Definition at line 28 of file FryingPan.c.
SOUND_DRYING_DONE
const string SOUND_DRYING_DONE = "Drying_Done_SoundSet" private
DEPRECATED.
Definition at line 27 of file FryingPan.c.
SOUND_DRYING_START
const string SOUND_DRYING_START = "Drying_SoundSet" private
DEPRECATED.
Definition at line 26 of file FryingPan.c.
UNFOLDED
const int UNFOLDED = 1 static private
Definition at line 4 of file HescoBox.c.
Referenced by OnStoreLoad(), and RefreshPhysics().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/BarbedBaseballBat.c
P:/scripts/4_World/Entities/ItemBase/HescoBox.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/FryingPan.c
P:/scripts/4_World/Entities/ItemBase/SeedPackBase.c
P:/scripts/4_World/Entities/ItemBase/XmasLights.c
P:/scripts/4_World/Entities/ItemBase/Hammer.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/AK_RailHndgrd.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/AtlasBipod.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/Candle.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/M4_RISHndgrd.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/Mosin_Bayonet.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/MP5_RailHndgrd.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/Nail.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/PlantMaterial.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/Red9Bttstck.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/SKS_Bayonet.c
P:/scripts/4_World/Entities/ItemBase/PipeWrench.c
P:/scripts/4_World/Entities/ItemBase/SledgeHammer.c
P:/scripts/4_World/Entities/ItemBase/WeaponAttachments/Attachments.c