DayZ Scripts: Link< Class T > Class Reference
Link< Class T > Class Reference
Private Member Functions
proto private native void Init (T init)
proto private native Object Get ()
void Release ()
void Link (T init)
T Ptr ()
bool IsNull ()
Constructor & Destructor Documentation
Link()
void Link (T init) inline private
References Init(), and init.
Member Function Documentation
Get()
proto private native Object Get () private
Init()
proto private native void Init (T init) private
IsNull()
bool IsNull () inline private
References Get().
Ptr()
T Ptr () inline private
References Get().
Release()
void Release () inline private
References Get().
The documentation for this class was generated from the following file:
P:/scripts/1_Core/proto/proto.c