DayZ Scripts: SurfaceInfo Class Reference
SurfaceInfo Class Reference
Private Member Functions
private void SurfaceInfo ()
private void ~SurfaceInfo ()
proto string GetName ()
proto string GetEntryName ()
proto string GetSurfaceType ()
proto float GetRoughness ()
proto float GetDustness ()
proto float GetBulletPenetrability ()
proto float GetThickness ()
proto float GetDeflection ()
proto float GetTransparency ()
proto float GetAudability ()
proto bool IsLiquid ()
proto bool IsStairs ()
proto bool IsPassthrough ()
proto bool IsSolid ()
proto string GetSoundEnv ()
proto string GetImpact ()
proto int GetLiquidType ()
See 'LiquidTypes' in 'constants.c'.
proto int GetStepParticleId ()
proto int GetWheelParticleId ()
Static Private Member Functions
static proto SurfaceInfo GetByName (string name)
static proto SurfaceInfo GetByFile (string name)
Detailed Description
Unmanaged surface info handle. Provides API to surfaces that are defined as part of 'CfgSurfaces' or exist in an objects .bisurf file. Lifetime is managed in code so don't store handles of this type yourself.
Constructor & Destructor Documentation
SurfaceInfo()
private void SurfaceInfo () inline private
~SurfaceInfo()
private void ~SurfaceInfo () inline private
Member Function Documentation
GetAudability()
proto float GetAudability () private
GetBulletPenetrability()
proto float GetBulletPenetrability () private
GetByFile()
static proto SurfaceInfo GetByFile (string name) static private
Warning: O(n) time complexity where n is the total number of loaded surfaces Note: Will load the surface if not loaded Warning: If the surface name is invalid, it will still create a SurfaceInfo 'CfgSurfaces' can be pathed by having the name prefixed with '#', so 'GetByFile("#cp_grass")' will return same as 'GetByName("cp_grass")'
GetByName()
static proto SurfaceInfo GetByName (string name) static private
Warning: O(n) time complexity where n is the total number of loaded surfaces Note: Will load the surface if not loaded Warning: If the surface name is invalid, it will still create a SurfaceInfo
Referenced by Surface::CheckLiquidSource(), ActionFillBottleBase::GetLiquidType(), Surface::GetStepsParticleID(), and Surface::GetWheelParticleID().
GetDeflection()
proto float GetDeflection () private
GetDustness()
proto float GetDustness () private
GetEntryName()
proto string GetEntryName () private
Referenced by Weapon::LiftWeaponCheck().
GetImpact()
proto string GetImpact () private
GetLiquidType()
proto int GetLiquidType () private
See 'LiquidTypes' in 'constants.c'.
Referenced by Surface::CheckLiquidSource(), and ActionFillBottleBase::GetLiquidType().
GetName()
proto string GetName () private
Referenced by Weapon::LiftWeaponCheck().
GetRoughness()
proto float GetRoughness () private
GetSoundEnv()
proto string GetSoundEnv () private
GetStepParticleId()
proto int GetStepParticleId () private
See 'ParticleList', if config entry not set, value is 'ParticleList.NONE', if config entry is set but doesn't exist, value is 'ParticleList.INVALID'
Referenced by Surface::GetStepsParticleID().
GetSurfaceType()
proto string GetSurfaceType () private
Referenced by Weapon::LiftWeaponCheck().
GetThickness()
proto float GetThickness () private
GetTransparency()
proto float GetTransparency () private
GetWheelParticleId()
proto int GetWheelParticleId () private
Referenced by Surface::GetWheelParticleID().
IsLiquid()
proto bool IsLiquid () private
IsPassthrough()
proto bool IsPassthrough () private
Referenced by Weapon::LiftWeaponCheck().
IsSolid()
proto bool IsSolid () private
Referenced by Weapon::LiftWeaponCheck().
IsStairs()
proto bool IsStairs () private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/SurfaceInfo.c