DayZ Scripts: Math3D library
Math3D library
Data Structures
class Math3D
Enumerations
enum ECurveType { CatmullRom , NaturalCubic , UniformCubic }
Functions
proto native vector Vector (float x, float y, float z)
Vector constructor from components.
private void Math3D ()
private void ~Math3D ()
static proto vector ClipLine (vector start, vector end, vector norm, float d)
static proto float IntersectRaySphere (vector raybase, vector raycos, vector center, float radius)
Tests whether ray is intersecting sphere.
static proto float IntersectRayBox (vector start, vector end, vector mins, vector maxs)
Tests whether ray is intersecting axis aligned box.
static proto bool IntersectSphereBox (vector origin, float radius, vector mins, vector maxs)
Tests whether sphere is intersecting axis aligned box.
static proto bool IntersectSphereCone (vector origin, float radius, vector conepos, vector axis, float angle)
Tests whether sphere is intersecting cone.
static proto bool IntersectWholeSphereCone (vector origin, float radius, vector conepos, vector axis, float angle)
Tests whether sphere is fully inside cone.
static proto bool IntersectCylinderOBB (vector mins, vector maxs, vector obbMat[4], vector cylMat[4], float cylinderRadius, float cylinderHeight)
Tests whether cylinder is intersecting oriented box.
static proto bool IntersectRayCylinder (vector rayStart, vector rayEnd, vector center, float radius, float height)
Tests whether ray is intersecting cylinder.
static proto int IntersectRayPlane (vector rayStart, vector rayEnd, vector planeNormal, float planeDist, out vector intersection)
Tests whether ray is intersecting plane.
static proto void YawPitchRollMatrix (vector ang, out vector mat[3])
Creates rotation matrix from angles.
static proto void DirectionAndUpMatrix (vector dir, vector up, out vector mat[4])
Creates rotation matrix from direction and up vector.
static proto void MatrixMultiply4 (vector mat0[4], vector mat1[4], out vector res[4])
Transforms matrix.
static proto void MatrixMultiply3 (vector mat0[3], vector mat1[3], out vector res[3])
Transforms rotation matrix.
static proto void MatrixInvMultiply4 (vector mat0[4], vector mat1[4], out vector res[4])
Invert-transforms matrix.
static proto void MatrixInvMultiply3 (vector mat0[3], vector mat1[3], out vector res[3])
Invert-transforms rotation matrix.
static proto void MatrixInverse4 (vector mat[4])
Inverses a matrix.
static proto void MatrixInverse3 (vector mat[3])
Inverses a matrix.
static proto void MatrixOrthogonalize4 (vector mat[4])
Orthogonalizes matrix.
static proto void MatrixOrthogonalize3 (vector mat[3])
Orthogonalizes matrix.
static void MatrixIdentity4 (out vector mat[4])
Creates identity matrix.
static void MatrixIdentity3 (out vector mat[3])
Creates identity matrix.
static void ScaleMatrix (float scale, out vector mat[3])
Creates scale matrix.
static void QuatIdentity (out float q[4])
Creates identity quaternion.
static void QuatCopy (float s[4], out float d[4])
Copies quaternion.
static proto void MatrixToQuat (vector mat[3], out float d[4])
Converts rotation matrix to quaternion.
static proto void QuatToMatrix (float q[4], out vector mat[3])
Converts quaternion to rotation matrix.
static proto vector MatrixToAngles (vector mat[3])
Returns angles of rotation matrix.
static proto void QuatLerp (out float qout[4], float q1[4], float q2[4], float frac)
Linear interpolation between q1 and q2 with weight 'frac' (0...1)
static proto void QuatMultiply (out float qout[4], float q1[4], float q2[4])
Multiplies quaternions.
static proto vector QuatToAngles (float q[4])
Returns Angles vector from quaternion.
static proto int CheckBoundBox (vector mins1, vector maxs1, vector mins2, vector maxs2)
Returns 1, when bounding boxes intersects.
static vector GetRandomDir ()
Returns randon normalized direction.
static proto native vector Curve (ECurveType type, float param, notnull array< vector > points)
Computes curve.
static proto vector NearestPoint (vector beg, vector end, vector pos)
Point on line beg .. end nearest to pos.
static proto float AngleFromPosition (vector origin, vector originDir, vector target)
Angle that a target is from the direction of an origin.
static proto void ConePoints (vector origin, float length, float halfAngle, float angleOffset, out vector leftPoint, out vector rightPoint)
Calculates the points of a right 2D cone in 3D space.
Detailed Description
Enumeration Type Documentation
ECurveType
enum ECurveType
Enumerator
CatmullRom
NaturalCubic
UniformCubic
Function Documentation
AngleFromPosition()
static proto float AngleFromPosition (vector origin, vector originDir, vector target) static private
Angle that a target is from the direction of an origin.
Returns
float Angle in radians
Referenced by EvaluateComponentEx(), EvaluateHit_Player(), DayZInfected::FightLogic(), GetMeleeTargetEx(), and ScriptConsoleSoundsTab::UpdateMousePos().
CheckBoundBox()
static proto int CheckBoundBox (vector mins1, vector maxs1, vector mins2, vector maxs2) static private
Returns 1, when bounding boxes intersects.
Parameters
mins1 vector minimum point of first bounding box
maxs1 vector maximum point of first bounding box
mins2 vector minimum point of second bounding box
maxs2 vector maximum point of second bounding box
Returns
int 1 if boundig boxes intersects, otherwise 0
vector mins1 = "1 1 1";
vector maxs1 = "3 3 3";
vector mins2 = "2 2 2";
vector maxs2 = "4 4 4";
Print(Math3D.CheckBoundBox(mins1, maxs1, mins2, maxs2));
>> 1
ClipLine()
static proto vector ClipLine (vector start, vector end, vector norm, float d) static private
ConePoints()
static proto void ConePoints (vector origin, float length, float halfAngle, float angleOffset, out vector leftPoint, out vector rightPoint) static private
Calculates the points of a right 2D cone in 3D space.
Parameters
origin vector Origin of cone
length float Length of the cone
halfAngle float Half of the angle of the cone in radians
angleOffset float Angle offset of the cone in radians (handy for rotating it along with something in the world)
[out] leftPoint vector Left point of the cone
[out] rightPoint vector Right point of the cone
Referenced by Debug::DrawCone(), and MeleeTargetSettings().
Curve()
static proto native vector Curve (ECurveType type, float param, notnull array< vector > points) static private
Computes curve.
Returns
vector
auto points = new array<vector>();
points.Insert(Vector(0, 0, 0));
points.Insert(Vector(5, 0, 0));
points.Insert(Vector(8, 3, 0));
points.Insert(Vector(6, 1, 0));
float t = 0.5;
vector result = Math3D.Curve(ECurveType.CatmullRom, t, points);
Referenced by RecoilBase::GetPositionOnCurve(), and KuruShake::Update().
DirectionAndUpMatrix()
static proto void DirectionAndUpMatrix (vector dir, vector up, out vector mat[4]) static private
Creates rotation matrix from direction and up vector.
Parameters
dir vector direction vector
up vector up vector
[out] mat vector[4] created rotation matrix
vector mat[4];
vector dir = "1 0 1";
vector up = "0 1 0";
DirectionAndUpMatrix(dir, up, mat);
Print(mat);
>> <0.707107,0,-0.707107>,<0,1,0>,<0.707107,0,0.707107>,<0,0,0>
Referenced by PluginBase::CalculatePos(), DayZIntroScene::DayZIntroScene(), and FloatingCrossHair().
GetRandomDir()
static vector GetRandomDir () inline static private
Returns randon normalized direction.
Returns
vector
Print(Math3D.GetRandomDir());
>>vector ret =  0x0000000007c1a1c0 {<0.422565,0,-0.906333>}
References vector::Normalized(), Math::RandomFloatInclusive(), Vector(), x, and y.
IntersectCylinderOBB()
static proto bool IntersectCylinderOBB (vector mins, vector maxs, vector obbMat[4], vector cylMat[4], float cylinderRadius, float cylinderHeight) static private
Tests whether cylinder is intersecting oriented box.
Parameters
mins vector Minimums of bound box
maxs vector Maximums of bound box
obbMat vector Transform of box
cylMat vector Transform of cylinder
cylinderRadius float Radius of cylinder
cylinderHeight float Height of cylinder
Returns
bool True when cylinder is intersecting oriented box
Referenced by CfgPlayerRestrictedAreaHandler::IsCylinderInAreaBox().
IntersectRayBox()
static proto float IntersectRayBox (vector start, vector end, vector mins, vector maxs) static private
Tests whether ray is intersecting axis aligned box.
Parameters
start vector Start of ray
end vector End of ray
mins vector Minimums of bound box
maxs vector Maximums of bound box
Returns
float -1 when not intersecting, else the fraction of ray
IntersectRayCylinder()
static proto bool IntersectRayCylinder (vector rayStart, vector rayEnd, vector center, float radius, float height) static private
Tests whether ray is intersecting cylinder.
Parameters
rayStart vector Start of ray
rayEnd vector End of ray
center vector Center of cylinder
radius float Radius of cylinder
height float Height of cylinder
Returns
bool True when ray is intersecting cylinder
IntersectRayPlane()
static proto int IntersectRayPlane (vector rayStart, vector rayEnd, vector planeNormal, float planeDist, out vector intersection) static private
Tests whether ray is intersecting plane.
Parameters
rayStart vector Start of ray
rayEnd vector End of ray
planeNormal vector Normal of the plane
planeDist float Length of the plane
intersection vector Intersection point of the plane, only valid when return is 3
Returns
int 1 when behind, 2 when in front and 3 when intersecting the plane
IntersectRaySphere()
static proto float IntersectRaySphere (vector raybase, vector raycos, vector center, float radius) static private
Tests whether ray is intersecting sphere.
Parameters
raybase vector Start of ray
raycos vector End of ray
center vector Center of sphere
radius float Radius of sphere
Returns
float -1 when not intersecting, else the fraction of ray
IntersectSphereBox()
static proto bool IntersectSphereBox (vector origin, float radius, vector mins, vector maxs) static private
Tests whether sphere is intersecting axis aligned box.
Parameters
origin vector Origin of sphere
radius float Radius of sphere
mins vector Minimums of bound box
maxs vector Maximums of bound box
Returns
bool True when intersects
IntersectSphereCone()
static proto bool IntersectSphereCone (vector origin, float radius, vector conepos, vector axis, float angle) static private
Tests whether sphere is intersecting cone.
Parameters
origin vector Origin of sphere
radius float Radius of sphere
conepos vector Position of top of cone
axis vector Orientation of cone in direction from top to bottom
angle float Angle of cone in radians
Returns
bool True when sphere is intersecting cone
IntersectWholeSphereCone()
static proto bool IntersectWholeSphereCone (vector origin, float radius, vector conepos, vector axis, float angle) static private
Tests whether sphere is fully inside cone.
Parameters
origin vector Origin of sphere
radius float Radius of sphere
conepos vector Position of top of cone
axis vector Orientation of cone in direction from top to bottom
angle float Angle of cone in radians
Returns
bool True when sphere is fully inside cone
Math3D()
private void Math3D () inline private
MatrixIdentity3()
static void MatrixIdentity3 (out vector mat[3]) inline static private
Creates identity matrix.
Parameters
[out] mat created identity matrix
vector mat[3];
Math3D.MatrixIdentity3(mat);
Print(mat);
>> <1,0,0>,<0,1,0>,<0,0,1>
MatrixIdentity4()
static void MatrixIdentity4 (out vector mat[4]) inline static private
Creates identity matrix.
Parameters
[out] mat created identity matrix
vector mat[4];
Math3D.MatrixIdentity4(mat);
Print(mat);
>> <1,0,0>,<0,1,0>,<0,0,1>,<0,0,0>
References vector::Zero.
Referenced by PluginBase::CalculatePos(), DropEquipAndDestroyRootLambda::CopyOldPropertiesToNew(), DayZIntroScene::DayZIntroScene(), ArrowManagerBase::DropArrow(), FireplaceToIndoorOvenLambda(), FireplaceToIndoorsLambda(), HandleDropMagazine(), CfgPlayerRestrictedAreaHandler::IsCylinderInAreaBox(), ManBase::PredictiveDropEntity(), ReplaceItemWithNewLambdaBase::PrepareLocations(), RemoveAllAttachedChildrenByTypename(), GameInventory::SetGroundPosByOwner(), Entity::SpawnEntityOnGroundPos(), ManBase::SpawnEntityOnGroundPos(), and ContaminatedArea_Dynamic::SpawnItems().
MatrixInverse3()
static proto void MatrixInverse3 (vector mat[3]) static private
Inverses a matrix.
Parameters
[it] mat matrix which should be inversed
MatrixInverse4()
static proto void MatrixInverse4 (vector mat[4]) static private
Inverses a matrix.
Parameters
[it] mat matrix which should be inversed
MatrixInvMultiply3()
static proto void MatrixInvMultiply3 (vector mat0[3], vector mat1[3], out vector res[3]) static private
Invert-transforms rotation matrix.
Parameters
mat0 vector[3] first matrix
mat1 vector[3] second matrix
[out] res vector[3] result of first and second matrix multiplication
vector mat0[3] = { "1.5 2.5 0", "0.1 1.3 0", "0 0 1" }; // rotation matrix
vector mat1[3] = { "1 0.4 0", "0 1 0", "0 1.3 2.7" }; // rotation matrix
vector res[3];
Math3D.MatrixInvMultiply3(mat0, mat1, res)
Print(res);
>> <2.5,0.62,0>,<2.5,1.3,0>,<3.25,1.69,2.7>
MatrixInvMultiply4()
static proto void MatrixInvMultiply4 (vector mat0[4], vector mat1[4], out vector res[4]) static private
Invert-transforms matrix.
Parameters
mat0 vector[4] first matrix
mat1 vector[4] second matrix
[out] res vector[4] inverse result of first and second matrix multiplication
vector mat0[4] = { "2 0 0", "0 3 0", "0 0 1", "0 0 0" }; // scale matrix
vector mat1[4] = { "1 0 0", "0 1 0", "0 0 1", "2 4 1" }; // translation matrix
vector res[4];
Math3D.MatrixInvMultiply4(mat0, mat1, res)
Print(res);
>> <2,0,0>,<0,3,1>,<0,3,1>,<4,12,4>
Referenced by AddArrow(), IEntity::AddArrow(), DayZInfected::AddArrow(), and ManBase::AddArrow().
MatrixMultiply3()
static proto void MatrixMultiply3 (vector mat0[3], vector mat1[3], out vector res[3]) static private
Transforms rotation matrix.
Parameters
mat0 vector[3] first matrix
mat1 vector[3] second matrix
[out] res vector[3] result of first and second matrix multiplication
vector mat0[3] = { "1.5 2.5 0", "0.1 1.3 0", "0 0 1" }; // rotation matrix
vector mat1[3] = { "1 0.4 0", "0 1 0", "0 1.3 2.7" }; // rotation matrix
vector res[3];
Math3D.MatrixMultiply3(mat0, mat1, res)
Print(res);
>> <1.54,3.02,0>,<0.1,1.3,0>,<0.13,1.69,2.7>
Referenced by Hologram::AlignProjectionOnTerrain(), and Weapon::LiftWeaponCheck().
MatrixMultiply4()
static proto void MatrixMultiply4 (vector mat0[4], vector mat1[4], out vector res[4]) static private
Transforms matrix.
Parameters
mat0 vector[4] first matrix
mat1 vector[4] second matrix
[out] res vector[4] result of first and second matrix multiplication
vector mat0[4] = { "2 0 0 0", "0 3 0 0", "0 1 0 0", "0 0 0 1" }; // scale matrix
vector mat1[4] = { "1 0 0 0", "0 1 0 0", "0 1 0 0", "2 4 1 3" }; // translation matrix
vector res[4];
Math3D.MatrixMultiply4(mat0, mat1, res)
Print(res);
>> <2,0,0>,<0,3,0>,<0,3,0>,<4,13,0>
Referenced by EntityAI::IsAreaAtDoorFree(), and DayZPlayerCameraBase::OnUpdate().
MatrixOrthogonalize3()
static proto void MatrixOrthogonalize3 (vector mat[3]) static private
Orthogonalizes matrix.
Parameters
[it] mat matrix which should be orthogonalized
MatrixOrthogonalize4()
static proto void MatrixOrthogonalize4 (vector mat[4]) static private
Orthogonalizes matrix.
Parameters
[it] mat matrix which should be orthogonalized
Referenced by AddArrow(), IEntity::AddArrow(), DayZInfected::AddArrow(), and ManBase::AddArrow().
MatrixToAngles()
static proto vector MatrixToAngles (vector mat[3]) static private
Returns angles of rotation matrix.
Parameters
mat vector[3] rotation matrix
Returns
vector roll, pitch, yaw angles
vector mat[3];
Math3D.RollPitchYawMatrix("70 15 45", mat);
vector ang = Math3D.MatrixToAngles(mat);
Print(ang);
>> <70,15,-45>
Referenced by Hologram::AlignProjectionOnTerrain(), FloatingCrossHair(), and EntityAI::IsAreaAtDoorFree().
MatrixToQuat()
static proto void MatrixToQuat (vector mat[3], out float d[4]) static private
Converts rotation matrix to quaternion.
Parameters
mat vector[3] rotation matrix
[out] d float[4] created quaternion copy
vector mat[3];
vector rot = "70 15 45";
rot.RotationMatrixFromAngles(mat);
float d[4];
Math3D.MatrixToQuat(mat, d);
Print(d);
>> {0.241626,0.566299,-0.118838,0.778973}
Referenced by ActionRepackTentCB::DropDuringRepacking(), FloatingCrossHair(), ActionDeployBase::MoveEntityToFinalPosition(), ItemBase::OnPlacementComplete(), and ThrowAllItemsInInventory().
NearestPoint()
static proto vector NearestPoint (vector beg, vector end, vector pos) static private
Point on line beg .. end nearest to pos.
Returns
vector
Referenced by EvaluateComponentEx(), and GetMeleeTargetEx().
QuatCopy()
static void QuatCopy (float s[4], out float d[4]) inline static private
Copies quaternion.
Parameters
s float[4] quaternion to copy
[out] d float[4] created quaternion copy
float s[4] = { 2, 3, 4, 1 };
float d[4];
Math3D.QuatCopy(s, d);
Print(d);
>> {2,3,4,1}
QuatIdentity()
static void QuatIdentity (out float q[4]) inline static private
Creates identity quaternion.
Parameters
[out] q float[4] created identity quaternion
float q[4];
Math3D.QuatIdentity(q);
Print(q);
>> {0,0,0,1}
QuatLerp()
static proto void QuatLerp (out float qout[4], float q1[4], float q2[4], float frac) static private
Linear interpolation between q1 and q2 with weight 'frac' (0...1)
Parameters
[out] qout float[4] result quaternion
q1 float[4] first quaternion
q2 float[4] second quaternion
frac float interpolation weight
float q1[4] = { 1, 1, 1, 1 };
float q2[4] = { 2, 2, 2, 1 };
float qout[4];
Math3D.QuatLerp(qout, q1, q2, 0.5);
Print(qout);
>> {1.5,1.5,1.5,1}
Referenced by FloatingCrossHair().
QuatMultiply()
static proto void QuatMultiply (out float qout[4], float q1[4], float q2[4]) static private
Multiplies quaternions.
Parameters
[out] qout float[4] result quaternion
q1 float[4] first quaternion
q2 float[4] second quaternion
float q1[4] = { 1, 2, 3, 1 };
float q2[4] = { 2, 2, 2, 1 };
float qout[4];
Math3D.QuatMultiply(qout, q1, q2);
Print(qout);
>> {2,4,6,1}
QuatToAngles()
static proto vector QuatToAngles (float q[4]) static private
Returns Angles vector from quaternion.
Referenced by UIScriptedMenu::SetCameraData(), and UIScriptedMenu::Update().
QuatToMatrix()
static proto void QuatToMatrix (float q[4], out vector mat[3]) static private
Converts quaternion to rotation matrix.
Referenced by FloatingCrossHair().
ScaleMatrix()
static void ScaleMatrix (float scale, out vector mat[3]) inline static private
Creates scale matrix.
Parameters
scale scale coeficient
[out] mat created scale matrix
vector mat[3];
Math3D.ScaleMatrix(2.5, mat);
Print(mat);
>> <2.5,0,0>,<0,2.5,0>,<0,0,2.5>
Vector()
proto native vector Vector (float x, float y, float z)
Vector constructor from components.
Parameters
x float x component
y float y component
z float z component
Returns
vector resulting vector
Print(Vector(1, 2, 3));
>> <1,2,3>
Referenced by vector::ArrayToVec(), Hit_MeatBones::BloodSplatGround(), PluginBase::CalculatePos(), DayZIntroSceneXbox::CameraCreate(), CarLightBase::CarRearLight(), TentBase::CarTent(), Math::CenterOfRectangle(), WeaponParticlesBase::CheckOrientationOverride(), CarLightBase::CivilianSedanFrontLight(), CarRearLightBase::CivilianSedanRearLight(), CGame::CloseCombatEffects(), CreateBridgeArrow(), CreateCarDestroyedEffect(), Particle::CreateOnObject(), SceneData::CreateScenePlayer(), EffectAreaLoader::CreateZones(), DayZIntroScene::DayZIntroScene(), CGame::DelayedMidAirDetonation(), EntityLightSource::DetachFromParent(), ItemBase::DoMeasurement(), Debug::DrawCone(), CfgPlayerRestrictedAreaHandler::DrawPolygonLinesDebug(), BuildingSuper::EEInit(), Explode(), FilterObstructedObjectsByGrouping(), FlareSimulation::FlareParticleUpdate(), FloatingCrossHair(), GameplayEffectsData::GenerateSequenceRandomPosition(), GetBoxCenter(), IEntity::GetCenter(), GetCollisionBoxSize(), Hologram::GetCollisionBoxSize(), GetCurrentOrientation(), GetFireEffectPosition(), ScriptedWidgetEventHandler::GetItemSize(), GetMeleeTarget(), GetMeleeTargetEx(), GetMouseDistance(), JsonUndergroundAreaTriggerData::GetOrientation(), JsonUndergroundAreaTriggerData::GetPosition(), SceneObject::GetPosition(), SceneObject::GetPositionAsString(), GetPositionRandomized(), Math3D::GetRandomDir(), GetRandomizedPosition(), GetRandomPos(), GetRectangularCoordsFromSize(), JsonUndergroundAreaTriggerData::GetSize(), SceneObject::GetSize(), GetSmokeEffectPosition(), FireplaceBase::GetSmokeEffectPosition(), EntityLightSource::HandleDancingShadows(), CarLightBase::Hatchback_02FrontLight(), CarRearLightBase::Hatchback_02RearLight(), BroomBase::Init(), UIScriptedMenu::Init(), Barrel_ColorBase::InitItemVariables(), InitPRAShapeData(), IsColliding(), IsCollidingEx(), Hologram::IsCollidingZeroPos(), IsEntityBehindEntityInAngle(), IsSpaceFor(), IsSpaceForCircle(), IsSpaceForOven(), IsUnderRoofFromToCalculation(), LargeTent(), Weapon::LiftWeaponCheck(), LongTorch::LongTorch(), TentBase::MediumTent(), CarLightBase::Offroad_02FrontLight(), CarRearLightBase::Offroad_02RearLight(), CarLightBase::OffroadHatchbackFrontLight(), CarRearLightBase::OffroadHatchbackRearLight(), WeaponParticlesBase::OnActivate(), FlareSimulation::OnActivation(), ItemBase::OnDebugSpawn(), MapHandler::OnDoubleClick(), ScriptConsoleGeneralTab::OnDoubleClick(), OnDraggingEnd(), FireworksLauncherClientEvent::OnFired(), PointLightBase::OnFrameLightSource(), ItemBase::OnInventoryExit(), Roadflare::OnInventoryExit(), Switchable_Base::OnInventoryExit(), MapHandler::OnKeyDown(), UIScriptedMenu::OnShow(), DayZPlayer::OnStepEvent(), OnUpdateClient(), Roadflare::OnWorkStart(), TentBase::PartyTent(), ScriptConsoleGeneralTab::ProcessTeleportText(), vector::RandomDir(), vector::RandomDir2D(), Particle::RandWiggleVector(), DayZIntroScene::ResetIntroCamera(), SeaChest::SeaChest(), CarLightBase::Sedan_02FrontLight(), CarRearLightBase::Sedan_02RearLight(), PluginBase::SelectedObjectDuplicate(), GameInventory::SetGroundPosByOwnerBounds(), UIScriptedMenu::SetItem(), Hologram::SetOnGround(), AreaDamageComponentRaycasted::SetRaycastLength(), SetWaterLevelHeight(), TentBase::ShelterBase(), DayZIntroScene::SnapToGround(), DayZIntroSceneXbox::SnapToGround(), CrashBase::SpawnRandomDeers(), ThrowAllItemsInInventory(), PlayerRestrictedAreaInstance::TranslateSafePositions(), CarLightBase::Truck_01FrontLight(), CarRearLightBase::Truck_01RearLight(), TruncateVec(), FlammableBase::TryTransformIntoStick(), ScriptedWidgetEventHandler::UpdateItems(), InventoryGridController::UpdateItems(), FlammableBase::UpdateLight(), CGame::UpdatePathgraphRegionByObject(), UIScriptedMenu::UpdateQuickbarItemCard(), ScriptedWidgetEventHandler::UpdateQuickbarItems(), PlayerRestrictedAreaInstance::ValidatePlayerRestrictedAreaPositions(), WeaponParticlesBase::WeaponParticlesBase(), WoodenCrate::WoodenCrate(), CrashBase::Wreck_Mi8_Crashed(), CrashBase::Wreck_SantasSleigh(), and CrashBase::Wreck_UH1Y().
YawPitchRollMatrix()
static proto void YawPitchRollMatrix (vector ang, out vector mat[3]) static private
Creates rotation matrix from angles.
Parameters
ang vector which contains angles
[out] mat vector created rotation matrix
vector mat[3];
YawPitchRollMatrix("70 15 45", mat);
Print(mat);
>> <0.330366,0.0885213,-0.939693>,<0.458809,0.854988,0.241845>,<0.824835,-0.511037,0.241845>
Referenced by AddArrow(), DayZInfected::AddArrow(), ManBase::AddArrow(), Hologram::AlignProjectionOnTerrain(), ActionRepackTentCB::DropDuringRepacking(), InitPRAShapeData(), Weapon::LiftWeaponCheck(), ActionDeployBase::MoveEntityToFinalPosition(), ItemBase::OnPlacementComplete(), DayZPlayerCameraBase::OnUpdate(), OnUpdate(), and ThrowAllItemsInInventory().
~Math3D()
private void ~Math3D () inline private