DayZ Scripts: PPELightIntensityParamsNative Class Reference
PPELightIntensityParamsNative Class Reference
g_Game.NightVissionLightParams, does not directly use materials. Controls light multiplication and filmgrain noise intensity (multiplier)
Private Member Functions
override int GetPostProcessEffectID ()
override void RegisterMaterialParameters ()
override void ApplyValueChanges ()
override void SetFinalParameterValue (int parameter_idx)
Overriden to handle the specific exception.
Static Private Attributes
static const int PARAM_LIGHT_MULT = 0
static const int PARAM_NOISE_MULT = 1
static const int L_0_NVG = 100
static const int L_0_TOXIC_TINT = 200
static const int L_1_NVG = 100
static const int L_1_TOXIC_TINT = 200
Detailed Description
g_Game.NightVissionLightParams, does not directly use materials. Controls light multiplication and filmgrain noise intensity (multiplier)
Member Function Documentation
ApplyValueChanges()
override void ApplyValueChanges () inline private
References PPEClassBase::m_UpdatedParameters, and SetFinalParameterValue().
GetPostProcessEffectID()
override int GetPostProcessEffectID () inline private
RegisterMaterialParameters()
override void RegisterMaterialParameters () inline private
References PARAM_LIGHT_MULT, PARAM_NOISE_MULT, and PPEClassBase::RegisterParameterScalarFloat().
SetFinalParameterValue()
override void SetFinalParameterValue (int parameter_idx) inline private
Overriden to handle the specific exception.
References g_Game, PPEMatClassParameterCommandData::GetCurrentValues(), PPEClassBase::GetParameterCommandData(), Param::param1, PARAM_LIGHT_MULT, and PARAM_NOISE_MULT.
Referenced by ApplyValueChanges().
Field Documentation
L_0_NVG
const int L_0_NVG = 100 static private
Referenced by PPERequester_GameplayBase::SetNVMode().
L_0_TOXIC_TINT
const int L_0_TOXIC_TINT = 200 static private
L_1_NVG
const int L_1_NVG = 100 static private
Referenced by PPERequester_GameplayBase::SetNVMode().
L_1_TOXIC_TINT
const int L_1_TOXIC_TINT = 200 static private
PARAM_LIGHT_MULT
const int PARAM_LIGHT_MULT = 0 static private
Referenced by RegisterMaterialParameters(), SetFinalParameterValue(), and PPERequester_GameplayBase::SetNVMode().
PARAM_NOISE_MULT
const int PARAM_NOISE_MULT = 1 static private
Referenced by RegisterMaterialParameters(), SetFinalParameterValue(), and PPERequester_GameplayBase::SetNVMode().
The documentation for this class was generated from the following file:
3_Game/PPEManager/Materials/MatClasses/Exceptions/PPELightIntensityParamsNative.c