DayZ Scripts: DynamicMusicPlayerRegistry Class Reference
DynamicMusicPlayerRegistry Class Reference
Private Member Functions
void DynamicMusicPlayerRegistry ()
protected void PreloadData ()
protected void RegisterCategorySettings ()
private void RegisterGlobalSettings ()
private void RegisterMenuSettings ()
private void RegisterTimeSettings ()
private void RegisterLocationStaticSettings ()
private void RegisterLocationDynamicSettings ()
protected void RegisterTracksMenu ()
protected void RegisterTracksTime ()
protected void RegisterTracksLocationStatic ()
protected void RegisterTracksLocationDynamic ()
protected void RegisterTrackMenu (string soundSetName, bool hasPriority=false, int timeOfDay=DynamicMusicPlayerTimeOfDay.ANY)
protected void RegisterTrackTime (string soundSetName, int timeOfDay=DynamicMusicPlayerTimeOfDay.ANY)
protected void RegisterTrackLocationStatic (string soundSetName, vector start, vector end, int timeOfDay=DynamicMusicPlayerTimeOfDay.ANY, bool runImmediately=false)
protected void RegisterTrackLocationStaticMultiRectangle (string soundSetName, ref array< ref TVectorArray > locationBoundaries, int timeOfDay=DynamicMusicPlayerTimeOfDay.ANY, bool runImmediately=false)
protected void RegisterTrackLocationDynamic (string soundSetName, int locationType=DynamicMusicLocationTypes.NONE, int timeOfDay=DynamicMusicPlayerTimeOfDay.ANY)
Private Attributes
ref map< EDynamicMusicPlayerCategory, ref DynamicMusicPlayerSettings > m_SettingsByCategory
ref array< ref DynamicMusicTrackData > m_TracksMenu
ref array< ref DynamicMusicTrackData > m_TracksTime
ref array< ref DynamicMusicTrackData > m_TracksLocationStatic
ref array< ref DynamicMusicTrackData > m_TracksLocationStaticPrioritized
ref array< ref DynamicMusicTrackData > m_TracksLocationDynamic
protected string m_WorldName = ""
Constructor & Destructor Documentation
DynamicMusicPlayerRegistry()
void DynamicMusicPlayerRegistry () inline private
References PreloadData().
Member Function Documentation
PreloadData()
protected void PreloadData () inline private
References m_WorldName, RegisterCategorySettings(), RegisterTracksLocationDynamic(), RegisterTracksLocationStatic(), RegisterTracksMenu(), RegisterTracksTime(), and string::ToLower().
Referenced by DynamicMusicPlayerRegistry().
RegisterCategorySettings()
protected void RegisterCategorySettings () inline private
References m_SettingsByCategory, RegisterGlobalSettings(), RegisterLocationDynamicSettings(), RegisterLocationStaticSettings(), RegisterMenuSettings(), and RegisterTimeSettings().
Referenced by PreloadData().
RegisterGlobalSettings()
private void RegisterGlobalSettings () inline private
References DynamicMusicPlayerSettings::m_MaxWaitTimeSeconds, DynamicMusicPlayerSettings::m_MinWaitTimeSeconds, and m_SettingsByCategory.
Referenced by RegisterCategorySettings().
RegisterLocationDynamicSettings()
private void RegisterLocationDynamicSettings () inline private
References DynamicMusicPlayerSettings::m_MaxWaitTimeSeconds, DynamicMusicPlayerSettings::m_MinWaitTimeSeconds, DynamicMusicPlayerSettings::m_PreviousTrackFadeoutSeconds, and m_SettingsByCategory.
Referenced by RegisterCategorySettings().
RegisterLocationStaticSettings()
private void RegisterLocationStaticSettings () inline private
References DynamicMusicPlayerSettings::m_MaxWaitTimeSeconds, DynamicMusicPlayerSettings::m_MinWaitTimeSeconds, DynamicMusicPlayerSettings::m_PreviousTrackFadeoutSeconds, and m_SettingsByCategory.
Referenced by RegisterCategorySettings().
RegisterMenuSettings()
private void RegisterMenuSettings () inline private
References DynamicMusicPlayerSettings::m_MaxWaitTimeSeconds, DynamicMusicPlayerSettings::m_MinWaitTimeSeconds, and m_SettingsByCategory.
Referenced by RegisterCategorySettings().
RegisterTimeSettings()
private void RegisterTimeSettings () inline private
References DynamicMusicPlayerSettings::m_MaxWaitTimeSeconds, DynamicMusicPlayerSettings::m_MinWaitTimeSeconds, and m_SettingsByCategory.
Referenced by RegisterCategorySettings().
RegisterTrackLocationDynamic()
protected void RegisterTrackLocationDynamic (string soundSetName, int locationType = DynamicMusicLocationTypes.NONE, int timeOfDay = DynamicMusicPlayerTimeOfDay.ANY) inline private
References m_TracksLocationDynamic.
Referenced by RegisterTracksLocationDynamic().
RegisterTrackLocationStatic()
protected void RegisterTrackLocationStatic (string soundSetName, vector start, vector end, int timeOfDay = DynamicMusicPlayerTimeOfDay.ANY, bool runImmediately = false) inline private
References m_TracksLocationStatic, and m_TracksLocationStaticPrioritized.
RegisterTrackLocationStaticMultiRectangle()
protected void RegisterTrackLocationStaticMultiRectangle (string soundSetName, ref array< ref TVectorArray > locationBoundaries, int timeOfDay = DynamicMusicPlayerTimeOfDay.ANY, bool runImmediately = false) inline private
References locationBoundaries, m_TracksLocationStatic, and m_TracksLocationStaticPrioritized.
Referenced by DynamicMusicPlayerRegistryChernarus::RegisterTracksLocationStatic(), and DynamicMusicPlayerRegistryEnoch::RegisterTracksLocationStatic().
RegisterTrackMenu()
protected void RegisterTrackMenu (string soundSetName, bool hasPriority = false, int timeOfDay = DynamicMusicPlayerTimeOfDay.ANY) inline private
References m_TracksMenu.
Referenced by RegisterTracksMenu().
RegisterTracksLocationDynamic()
protected void RegisterTracksLocationDynamic () inline private
References DynamicMusicLocationTypes::CONTAMINATED_ZONE, WorldDataDaytime::DAY, m_TracksLocationDynamic, WorldDataDaytime::NIGHT, and RegisterTrackLocationDynamic().
Referenced by PreloadData().
RegisterTracksLocationStatic()
protected void RegisterTracksLocationStatic () inline private
References m_TracksLocationStatic, and m_TracksLocationStaticPrioritized.
Referenced by PreloadData().
RegisterTracksMenu()
protected void RegisterTracksMenu () inline private
References m_TracksMenu, and RegisterTrackMenu().
Referenced by PreloadData().
RegisterTracksTime()
protected void RegisterTracksTime () inline private
References WorldDataDaytime::DAWN, WorldDataDaytime::DAY, WorldDataDaytime::DUSK, m_TracksTime, WorldDataDaytime::NIGHT, and RegisterTrackTime().
Referenced by PreloadData().
RegisterTrackTime()
protected void RegisterTrackTime (string soundSetName, int timeOfDay = DynamicMusicPlayerTimeOfDay.ANY) inline private
References m_TracksTime.
Referenced by RegisterTracksTime().
Field Documentation
m_SettingsByCategory
ref map<EDynamicMusicPlayerCategory, ref DynamicMusicPlayerSettings> m_SettingsByCategory private
Referenced by GetMaxWaitTimePerCategory(), GetMinWaitTimePerCategory(), GetPreviousTrackFadeoutSeconds(), RegisterCategorySettings(), RegisterGlobalSettings(), RegisterLocationDynamicSettings(), RegisterLocationStaticSettings(), RegisterMenuSettings(), and RegisterTimeSettings().
m_TracksLocationDynamic
ref array<ref DynamicMusicTrackData> m_TracksLocationDynamic private
Referenced by DetermineTrackByCategory(), RegisterTrackLocationDynamic(), and RegisterTracksLocationDynamic().
m_TracksLocationStatic
ref array<ref DynamicMusicTrackData> m_TracksLocationStatic private
Referenced by RefreshTracksCache(), RegisterTrackLocationStatic(), RegisterTrackLocationStaticMultiRectangle(), and RegisterTracksLocationStatic().
m_TracksLocationStaticPrioritized
ref array<ref DynamicMusicTrackData> m_TracksLocationStaticPrioritized private
Referenced by RefreshTracksCache(), RegisterTrackLocationStatic(), RegisterTrackLocationStaticMultiRectangle(), and RegisterTracksLocationStatic().
m_TracksMenu
ref array<ref DynamicMusicTrackData> m_TracksMenu private
Referenced by DetermineTrackByCategory(), RegisterTrackMenu(), and RegisterTracksMenu().
m_TracksTime
ref array<ref DynamicMusicTrackData> m_TracksTime private
Referenced by DetermineTrackByCategory(), RegisterTracksTime(), and RegisterTrackTime().
m_WorldName
protected string m_WorldName = "" private
Referenced by DynamicMusicPlayerRegistryChernarus::DynamicMusicPlayerRegistryChernarus(), DynamicMusicPlayerRegistryEnoch::DynamicMusicPlayerRegistryEnoch(), and PreloadData().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/DynamicMusicPlayer/DynamicMusicPlayerRegistry.c