DayZ Scripts: WorldData Class Reference
WorldData Class Reference
Keeps information about currently loaded world, like temperature.
Private Member Functions
void WorldData ()
void Init ()
float GetApproxSunriseTime (float monthday)
float GetApproxSunsetTime (float monthday)
int GetDaytime ()
protected float CalcBaseEnvironmentTemperature (float monthday, float daytime)
void UpdateBaseEnvTemperature (float timeslice)
void UpdateWeatherEffects (Weather weather, float timeslice)
Updates local weather effects.
float ComputeSnowflakeScale (Weather weather)
Returns the desired snowflake scale based on weather simulation state.
float GetBaseEnvTemperature ()
float GetBaseEnvTemperatureAtObject (notnull Object object)
float GetBaseEnvTemperatureAtPosition (vector pos)
float GetBaseEnvTemperatureExact (int month, int day, int hour, int minute)
float GetLiquidTypeEnviroTemperature (int liquidType)
bool WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time)
array< vector > GetArtyFiringPos ()
float GetAgentSpawnChance (eAgents agent)
float GetColdAreaToolDamageModifier ()
void BaseTempDebug (int month, int day)
int GetPollution ()
float GetWindCoef ()
float GetUniversalTemperatureSourceCapModifier ()
protected void CalculateWind (int newWeather, bool suddenChange, out float magnitude, out float direction)
protected void CalculateVolFog (float lerpValue, float windMagnitude, float changeTime)
protected void CreateYieldBank ()
protected void InitYieldBank ()
override this to properly register world-specific yields
protected void SetupWeatherSettings ()
protected void SetupLiquidTemperatures ()
CatchYieldBank GetCatchYieldBank ()
TStringArray GetDefaultPRAPaths ()
float GetDayTemperature ()
float GetNightTemperature ()
override void Init ()
override void SetupWeatherSettings ()
override bool WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time)
protected override void CalculateWind (int newWeather, bool suddenChange, out float magnitude, out float direction)
protected override void CalculateVolFog (float lerpValue, float windMagnitude, float changeTime)
bool LogWeatherData ()
Private Attributes
const float SPAWN_CHANCE_CHOLERA_DEF = 50
const float COLD_AREA_TOOL_DMG_MODIF_DEF = 1
float m_TemperaturePerHeightReductionModifier
directly accesible (defined/overriden in Init())
float m_CloudsTemperatureEffectModifier
amount of °C reduced for each 100 meteres of height above water level
float m_TemperatureInsideBuildingsModifier float m_WaterContactTemperatureModifier protected float SUDDENCHANGE_TIME_MULTIPLIER = 0.2
how many % of environment temperature can be lowered by clouds
protected float SUDDENCHANGE_LENGTH_MULTIPLIER = 0.4
protected float WIND_MAGNITUDE_TIME_MULTIPLIER = 0.1
protected float WIND_DIRECTION_TIME_MULTIPLIER = 0.05
protected Weather m_Weather
protected float m_EnvironmentTemperature
protected bool m_EnTempUpdated
protected float m_Timer
protected float m_MaxTemps [12]
protected float m_MinTemps [12]
protected float m_Sunrise_Jan
protected float m_Sunset_Jan
protected float m_Sunrise_Jul
protected float m_Sunset_Jul
protected ref array< vector > m_FiringPos
protected bool m_Pollution
protected ref CatchYieldBank m_YieldBank
protected ref WorldDataWeatherSettings m_WeatherDefaultSettings
protected ref WorldDataLiquidSettings m_LiquidSettings
protected ref TStringArray m_DefaultPlayerRestrictedAreas
protected int m_BadWeatherChance
weather related
protected int m_ClearWeatherChance
protected bool m_IsSuddenChange
protected float m_WorldWindCoef
protected float m_UniversalTemperatureSourceCapModifier
protected int m_SameWeatherCnt = 0
protected int m_StepValue = 5
protected int m_Chance = 50
protected int m_ChoosenWeather = 1
protected int m_LastWeather = 0
protected float m_DayTemperature = 10
protected float m_NightTemperature = 6
const int CLEAR_WEATHER = 1
DEPRECATED (see WorldDataWeatherConstants)
const int CLOUDY_WEATHER = 2
const int BAD_WEATHER = 3
const int OVERCAST_MIN_TIME = 600
DEPRECATED (see WorldDataWeatherSettings)
const int OVERCAST_MAX_TIME = 900
const float RAIN_THRESHOLD = 0.6
const int RAIN_TIME_MIN = 60
const int RAIN_TIME_MAX = 120
const float STORM_THRESHOLD = 0.9
protected int m_clearWeatherChance = m_ClearWeatherChance
protected int m_badWeatherChance = m_BadWeatherChance
protected int m_sameWeatherCnt = m_SameWeatherCnt
protected int m_stepValue = m_StepValue
protected int m_chance = m_Chance
protected int m_choosenWeather = m_ChoosenWeather
protected int m_lastWeather = m_LastWeather
Static Private Attributes
static protected const ref array< vector > CHERNARUS_ARTY_STRIKE_POS
Detailed Description
Keeps information about currently loaded world, like temperature.
Constructor & Destructor Documentation
WorldData()
void WorldData () inline private
References CreateYieldBank(), Init(), InitYieldBank(), and UpdateBaseEnvTemperature().
Member Function Documentation
BaseTempDebug()
void BaseTempDebug (int month, int day) inline private
References GetBaseEnvTemperatureExact(), and Print().
CalcBaseEnvironmentTemperature()
protected float CalcBaseEnvironmentTemperature (float monthday, float daytime) inline private
References Math::AbsFloat(), Math::Floor(), GetApproxSunriseTime(), GetApproxSunsetTime(), Math::Lerp(), m_MaxTemps, and m_MinTemps.
Referenced by GetBaseEnvTemperatureExact(), and UpdateBaseEnvTemperature().
CalculateVolFog() [1/2]
protected void CalculateVolFog (float lerpValue, float windMagnitude, float changeTime) private
Referenced by Init(), and WeatherOnBeforeChange().
CalculateVolFog() [2/2]
protected override void CalculateVolFog (float lerpValue, float windMagnitude, float changeTime) inline private
References Math::Clamp(), World::GetDate(), Weather::GetDynVolFogHeightBias(), GetGame(), Weather::GetWindMaximumSpeed(), CGame::GetWorld(), Math::Lerp(), m_Weather, Math::RandomInt(), Math::RandomIntInclusive(), Weather::SetDynVolFogDistanceDensity(), Weather::SetDynVolFogHeightBias(), and Weather::SetDynVolFogHeightDensity().
CalculateWind() [1/2]
protected void CalculateWind (int newWeather, bool suddenChange, out float magnitude, out float direction) private
Referenced by WeatherOnBeforeChange().
CalculateWind() [2/2]
protected override void CalculateWind (int newWeather, bool suddenChange, out float magnitude, out float direction) inline private
References WeatherPhenomenon::GetActual(), WeatherPhenomenon::GetForecast(), Weather::GetOvercast(), m_Weather, Math::RandomFloatInclusive(), and Math::RandomIntInclusive().
ComputeSnowflakeScale()
float ComputeSnowflakeScale (Weather weather) inline private
Returns the desired snowflake scale based on weather simulation state.
Parameters
weather Weather instance
References Math::Clamp(), WeatherPhenomenon::GetActual(), Weather::GetOvercast(), Weather::GetWindMaximumSpeed(), Weather::GetWindSpeed(), Math::InverseLerp(), and Math::Lerp().
Referenced by UpdateWeatherEffects().
CreateYieldBank()
protected void CreateYieldBank () inline private
References m_YieldBank.
Referenced by WorldData().
GetAgentSpawnChance()
float GetAgentSpawnChance (eAgents agent) inline private
References SPAWN_CHANCE_CHOLERA_DEF.
Referenced by Bottle_Base::EEOnCECreate().
GetApproxSunriseTime()
float GetApproxSunriseTime (float monthday) inline private
References m_Sunrise_Jan, and m_Sunrise_Jul.
Referenced by CalcBaseEnvironmentTemperature().
GetApproxSunsetTime()
float GetApproxSunsetTime (float monthday) inline private
References m_Sunset_Jan, and m_Sunset_Jul.
Referenced by CalcBaseEnvironmentTemperature().
GetArtyFiringPos()
array< vector > GetArtyFiringPos () inline private
References m_FiringPos.
Referenced by ContaminatedArea_Dynamic::EEOnCECreate().
GetBaseEnvTemperature()
float GetBaseEnvTemperature () inline private
References m_EnvironmentTemperature.
Referenced by Apple::EEOnCECreate(), GreenBellPepper::EEOnCECreate(), Pear::EEOnCECreate(), Plum::EEOnCECreate(), Potato::EEOnCECreate(), Tomato::EEOnCECreate(), Zucchini::EEOnCECreate(), and Environment::GetDebugMessage().
GetBaseEnvTemperatureAtObject()
float GetBaseEnvTemperatureAtObject (notnull Object object) inline private
References GetBaseEnvTemperatureAtPosition(), and GetPosition.
Referenced by Environment::GetDebugMessage(), Environment::GetEnvironmentTemperature(), Environment::Init(), and Environment::SetAreaGenericColdness().
GetBaseEnvTemperatureAtPosition()
float GetBaseEnvTemperatureAtPosition (vector pos) inline private
References m_EnvironmentTemperature, m_TemperaturePerHeightReductionModifier, and Math::Max().
Referenced by GetBaseEnvTemperatureAtObject().
GetBaseEnvTemperatureExact()
float GetBaseEnvTemperatureExact (int month, int day, int hour, int minute) inline private
References CalcBaseEnvironmentTemperature().
Referenced by BaseTempDebug().
GetCatchYieldBank()
CatchYieldBank GetCatchYieldBank () inline private
References m_YieldBank.
Referenced by Init(), ItemBase::PlayCatchEffectsClient(), and ItemBase::PlayCatchEffectsServer().
GetColdAreaToolDamageModifier()
float GetColdAreaToolDamageModifier () inline private
References COLD_AREA_TOOL_DMG_MODIF_DEF.
Referenced by DealEvinronmentAdjustedDmg().
GetDayTemperature()
float GetDayTemperature () inline private
References m_DayTemperature.
GetDaytime()
int GetDaytime () inline private
References WorldDataDaytime::DAWN, WorldDataDaytime::DAY, WorldDataDaytime::DUSK, g_Game, World::GetDate(), GetGame(), CGame::GetWorld(), and WorldDataDaytime::NIGHT.
GetDefaultPRAPaths()
TStringArray GetDefaultPRAPaths () inline private
References m_DefaultPlayerRestrictedAreas.
GetLiquidTypeEnviroTemperature()
float GetLiquidTypeEnviroTemperature (int liquidType) inline private
References ErrorEx, INDEX_NOT_FOUND, m_EnvironmentTemperature, and m_LiquidSettings.
Referenced by FilteringBottle::AffectLiquidContainerOnFill(), Bottle_Base::AffectLiquidContainerOnFill(), ManBase::Consume(), Environment::GetEnvironmentTemperature(), and GetLiquidTypeEnviroTemperature().
GetNightTemperature()
float GetNightTemperature () inline private
References m_NightTemperature.
GetPollution()
int GetPollution () inline private
References m_Pollution.
Referenced by ManBase::Consume(), and PluginBase::TransmitAgentsEx().
GetUniversalTemperatureSourceCapModifier()
float GetUniversalTemperatureSourceCapModifier () inline private
References m_UniversalTemperatureSourceCapModifier.
GetWindCoef()
float GetWindCoef () inline private
References m_WorldWindCoef.
Referenced by Environment::WindEffectTemperatureValue().
Init() [1/2]
void Init () inline private
References g_Game, m_BadWeatherChance, WorldDataWeatherSettings::m_BadWeatherChance, m_ClearWeatherChance, WorldDataWeatherSettings::m_ClearWeatherChance, m_CloudsTemperatureEffectModifier, m_DefaultPlayerRestrictedAreas, m_EnTempUpdated, m_EnvironmentTemperature, m_MaxTemps, m_MinTemps, m_Pollution, m_Sunrise_Jan, m_Sunrise_Jul, m_Sunset_Jan, m_Sunset_Jul, m_TemperaturePerHeightReductionModifier, m_Timer, m_UniversalTemperatureSourceCapModifier, m_Weather, m_WeatherDefaultSettings, m_WorldWindCoef, SetupLiquidTemperatures(), and SetupWeatherSettings().
Referenced by WorldData().
Init() [2/2]
override void Init () inline private
References CalculateVolFog(), CHERNARUS_ARTY_STRIKE_POS, Count, CfgGameplayHandler::GetEnvironmentMaxTemps(), CfgGameplayHandler::GetEnvironmentMinTemps(), GetGame(), Weather::GetOvercast(), Weather::GetWindSpeed(), m_Weather, Math::RandomFloat(), WeatherPhenomenon::Set(), and Weather::SetDynVolFogHeightBias().
InitYieldBank()
protected void InitYieldBank () inline private
override this to properly register world-specific yields
References GetDayZGame(), and m_YieldBank.
Referenced by WorldData().
LogWeatherData()
bool LogWeatherData () inline private
SetupLiquidTemperatures()
protected void SetupLiquidTemperatures () inline private
References LIQUID_CLEANWATER, LIQUID_FRESHWATER, LIQUID_RIVERWATER, LIQUID_SALTWATER, LIQUID_SNOW, LIQUID_STILLWATER, LIQUID_WATER, and m_LiquidSettings.
Referenced by Init().
SetupWeatherSettings() [1/2]
protected void SetupWeatherSettings () inline private
References m_WeatherDefaultSettings.
Referenced by Init().
SetupWeatherSettings() [2/2]
override void SetupWeatherSettings () inline private
UpdateBaseEnvTemperature()
void UpdateBaseEnvTemperature (float timeslice) inline private
References CalcBaseEnvironmentTemperature(), World::GetDate(), GetGame(), CGame::GetWorld(), m_EnTempUpdated, m_EnvironmentTemperature, and m_Timer.
Referenced by WorldData().
UpdateWeatherEffects()
void UpdateWeatherEffects (Weather weather, float timeslice) inline private
Updates local weather effects.
Parameters
weather Weather instance
timeslice Time delta since last update
References ComputeSnowflakeScale(), and Weather::SetSnowflakeScale().
Referenced by CGame::OnUpdate().
WeatherOnBeforeChange() [1/2]
bool WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time) inline private
Referenced by WeatherPhenomenon::OnBeforeChange().
WeatherOnBeforeChange() [2/2]
override bool WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time) inline private
References CalculateVolFog(), CalculateWind(), CloseFile(), FPrintln(), g_Game, WeatherPhenomenon::GetActual(), World::GetDate(), Weather::GetDynVolFogHeightBias(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), Weather::GetWindDirection(), Weather::GetWindMagnitude(), CGame::GetWorld(), IDC_MAIN_QUIT, m_SameWeatherCnt, m_StepValue, m_Weather, OpenFile(), Math::RandomFloatInclusive(), Math::RandomInt(), Math::RandomIntInclusive(), WeatherPhenomenon::Set(), Weather::SetDynVolFogHeightBias(), Weather::SetRainThresholds(), Weather::SetStorm(), Weather::SetWindMaximumSpeed(), and Debug::WeatherLog().
Field Documentation
BAD_WEATHER
const int BAD_WEATHER = 3 private
CHERNARUS_ARTY_STRIKE_POS
protected const ref array<vector> CHERNARUS_ARTY_STRIKE_POS static private
Initial value:
=
    {
        "-500.00 165.00 5231.69",
        "-500.00 300.00 9934.41",
        "10406.86 192.00 15860.00",
        "4811.75 370.00 15860.00",
        "-500.00 453.00 15860.00"
    }
Referenced by Init().
CLEAR_WEATHER
const int CLEAR_WEATHER = 1 private
DEPRECATED (see WorldDataWeatherConstants)
CLOUDY_WEATHER
const int CLOUDY_WEATHER = 2 private
COLD_AREA_TOOL_DMG_MODIF_DEF
const float COLD_AREA_TOOL_DMG_MODIF_DEF = 1 private
Referenced by GetColdAreaToolDamageModifier().
m_BadWeatherChance
protected int m_BadWeatherChance private
weather related
Referenced by Init(), SakhalData::Init(), EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
m_badWeatherChance
protected int m_badWeatherChance = m_BadWeatherChance private
m_Chance
protected int m_Chance = 50 private
Referenced by EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
m_chance
protected int m_chance = m_Chance private
m_ChoosenWeather
protected int m_ChoosenWeather = 1 private
Referenced by EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
m_choosenWeather
protected int m_choosenWeather = m_ChoosenWeather private
m_ClearWeatherChance
protected int m_ClearWeatherChance private
Referenced by Init(), SakhalData::Init(), EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
m_clearWeatherChance
protected int m_clearWeatherChance = m_ClearWeatherChance private
m_CloudsTemperatureEffectModifier
float m_CloudsTemperatureEffectModifier private
amount of °C reduced for each 100 meteres of height above water level
Referenced by Environment::GetEnvironmentTemperature(), Init(), and EnochData::Init().
m_DayTemperature
protected float m_DayTemperature = 10 private
DEPRECATED
Referenced by GetDayTemperature().
m_DefaultPlayerRestrictedAreas
protected ref TStringArray m_DefaultPlayerRestrictedAreas private
Referenced by GetDefaultPRAPaths(), Init(), and SakhalData::Init().
m_EnTempUpdated
protected bool m_EnTempUpdated private
Referenced by Init(), and UpdateBaseEnvTemperature().
m_EnvironmentTemperature
protected float m_EnvironmentTemperature private
Referenced by GetBaseEnvTemperature(), GetBaseEnvTemperatureAtPosition(), GetLiquidTypeEnviroTemperature(), Init(), and UpdateBaseEnvTemperature().
m_FiringPos
protected ref array<vector> m_FiringPos private
Referenced by GetArtyFiringPos(), and EnochData::Init().
m_IsSuddenChange
protected bool m_IsSuddenChange private
Referenced by EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
m_LastWeather
protected int m_LastWeather = 0 private
Referenced by EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
m_lastWeather
protected int m_lastWeather = m_LastWeather private
m_LiquidSettings
protected ref WorldDataLiquidSettings m_LiquidSettings private
Referenced by GetLiquidTypeEnviroTemperature(), SetupLiquidTemperatures(), EnochData::SetupLiquidTemperatures(), and SakhalData::SetupLiquidTemperatures().
m_MaxTemps
protected float m_MaxTemps[12] private
Referenced by CalcBaseEnvironmentTemperature(), Init(), EnochData::Init(), and SakhalData::Init().
m_MinTemps
protected float m_MinTemps[12] private
Referenced by CalcBaseEnvironmentTemperature(), Init(), EnochData::Init(), and SakhalData::Init().
m_NightTemperature
protected float m_NightTemperature = 6 private
Referenced by GetNightTemperature().
m_Pollution
protected bool m_Pollution private
Referenced by GetPollution(), Init(), and SakhalData::Init().
m_SameWeatherCnt
protected int m_SameWeatherCnt = 0 private
Referenced by WeatherOnBeforeChange(), EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
m_sameWeatherCnt
protected int m_sameWeatherCnt = m_SameWeatherCnt private
m_StepValue
protected int m_StepValue = 5 private
Referenced by WeatherOnBeforeChange(), EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
m_stepValue
protected int m_stepValue = m_StepValue private
m_Sunrise_Jan
protected float m_Sunrise_Jan private
Referenced by GetApproxSunriseTime(), Init(), EnochData::Init(), and SakhalData::Init().
m_Sunrise_Jul
protected float m_Sunrise_Jul private
Referenced by GetApproxSunriseTime(), Init(), EnochData::Init(), and SakhalData::Init().
m_Sunset_Jan
protected float m_Sunset_Jan private
Referenced by GetApproxSunsetTime(), Init(), EnochData::Init(), and SakhalData::Init().
m_Sunset_Jul
protected float m_Sunset_Jul private
Referenced by GetApproxSunsetTime(), Init(), EnochData::Init(), and SakhalData::Init().
m_TemperaturePerHeightReductionModifier
float m_TemperaturePerHeightReductionModifier private
directly accesible (defined/overriden in Init())
Referenced by GetBaseEnvTemperatureAtPosition(), Environment::GetTemperatureHeightCorrection(), Init(), and EnochData::Init().
m_Timer
protected float m_Timer private
Referenced by Init(), and UpdateBaseEnvTemperature().
m_UniversalTemperatureSourceCapModifier
protected float m_UniversalTemperatureSourceCapModifier private
Referenced by GetUniversalTemperatureSourceCapModifier(), Init(), EnochData::Init(), and SakhalData::Init().
m_Weather
protected Weather m_Weather private
Referenced by EnochData::CalculateVolFog(), SakhalData::CalculateVolFog(), EnochData::CalculateWind(), SakhalData::CalculateWind(), Init(), EnochData::Init(), SakhalData::Init(), EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
m_WeatherDefaultSettings
protected ref WorldDataWeatherSettings m_WeatherDefaultSettings private
Referenced by EnochData::CalculateVolFog(), EnochData::CalculateWind(), Init(), EnochData::Init(), SakhalData::Init(), SetupWeatherSettings(), EnochData::SetupWeatherSettings(), SakhalData::SetupWeatherSettings(), EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
m_WorldWindCoef
protected float m_WorldWindCoef private
Referenced by GetWindCoef(), Init(), and EnochData::Init().
m_YieldBank
protected ref CatchYieldBank m_YieldBank private
Referenced by CreateYieldBank(), GetCatchYieldBank(), InitYieldBank(), EnochData::InitYieldBank(), and SakhalData::InitYieldBank().
OVERCAST_MAX_TIME
const int OVERCAST_MAX_TIME = 900 private
OVERCAST_MIN_TIME
const int OVERCAST_MIN_TIME = 600 private
DEPRECATED (see WorldDataWeatherSettings)
RAIN_THRESHOLD
const float RAIN_THRESHOLD = 0.6 private
RAIN_TIME_MAX
const int RAIN_TIME_MAX = 120 private
RAIN_TIME_MIN
const int RAIN_TIME_MIN = 60 private
SPAWN_CHANCE_CHOLERA_DEF
const float SPAWN_CHANCE_CHOLERA_DEF = 50 private
Referenced by GetAgentSpawnChance().
STORM_THRESHOLD
const float STORM_THRESHOLD = 0.9 private
SUDDENCHANGE_LENGTH_MULTIPLIER
protected float SUDDENCHANGE_LENGTH_MULTIPLIER = 0.4 private
Referenced by EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
SUDDENCHANGE_TIME_MULTIPLIER
float m_TemperatureInsideBuildingsModifier float m_WaterContactTemperatureModifier protected float SUDDENCHANGE_TIME_MULTIPLIER = 0.2 private
how many % of environment temperature can be lowered by clouds
Referenced by EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
WIND_DIRECTION_TIME_MULTIPLIER
protected float WIND_DIRECTION_TIME_MULTIPLIER = 0.05 private
Referenced by EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
WIND_MAGNITUDE_TIME_MULTIPLIER
protected float WIND_MAGNITUDE_TIME_MULTIPLIER = 0.1 private
Referenced by EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
The documentation for this class was generated from the following files:
P:/scripts/3_Game/WorldData.c
P:/scripts/4_World/Classes/Worlds/ChernarusPlus.c