DayZ Scripts: Header Class Reference
Header Class Reference
Private Member Functions
void Header (LayoutHolder parent, string function_name)
void SetName (string name)
void SetItemPreview (EntityAI entity_ai)
void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override void SetActive (bool active)
void ShowCollapseButton (bool state)
Private Attributes
protected int m_DefaultColor
protected int m_DefaultFontSize
protected EntityAI m_Entity
protected Widget m_CollapseButton
protected Widget m_UpArrowButton
protected Widget m_DownArrowButton
protected TextWidget m_HeaderText
Detailed Description
Definition at line 1 of file Header.c.
Constructor & Destructor Documentation
Header()
void Header (LayoutHolder parent, string function_name) inline private
Definition at line 13 of file Header.c.
References FindAnyWidget(), WidgetEventHandler::GetInstance(), m_CollapseButton, m_DefaultColor, m_DownArrowButton, m_HeaderText, m_Parent, m_UpArrowButton, WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), and WidgetEventHandler::RegisterOnMouseButtonDown().
Member Function Documentation
DraggingOverHeader()
void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 49 of file Header.c.
References m_Parent, x, and y.
OnDropReceivedFromHeader()
void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 58 of file Header.c.
References m_Parent, x, and y.
SetActive()
override void SetActive (bool active) inline private
Definition at line 64 of file Header.c.
References ARGBF(), and m_DefaultColor.
Referenced by LayoutHolder::SetActive(), and LayoutHolder::SetLastActive().
SetItemPreview()
void SetItemPreview (EntityAI entity_ai) inline private
Definition at line 39 of file Header.c.
References FindAnyWidget(), m_Entity, ItemPreviewWidget::SetItem(), and ItemPreviewWidget::SetView().
SetName()
void SetName (string name) inline private
Definition at line 33 of file Header.c.
References m_HeaderText, name, and string::ToUpper().
Referenced by HandsPreview::CreateNewIcon(), AttachmentCategoriesRow::Init(), PlayerContainer::PlayerContainer(), AttachmentCategoriesContainer::SetHeaderName(), ZombieContainer::SetHeaderName(), Container::UpdateHeaderText(), and VicinityContainer::VicinityContainer().
ShowCollapseButton()
void ShowCollapseButton (bool state) inline private
Definition at line 74 of file Header.c.
References m_CollapseButton.
Referenced by CollapsibleContainer::UpdateCollapseButtons().
Field Documentation
m_CollapseButton
protected Widget m_CollapseButton private
Definition at line 8 of file Header.c.
Referenced by Header(), ClosableHeader::MouseLeave(), ShowCollapseButton(), and HandsHeader::ShowCollapseButtons().
m_DefaultColor
protected int m_DefaultColor private
Definition at line 3 of file Header.c.
Referenced by ClosableHeader::ClosableHeader(), HandsHeader::HandsHeader(), Header(), ClosableHeader::SetActive(), and SetActive().
m_DefaultFontSize
protected int m_DefaultFontSize private
Definition at line 4 of file Header.c.
Referenced by ClosableHeader::ClosableHeader(), CollapsibleHeader::CollapsibleHeader(), and HandsHeader::HandsHeader().
m_DownArrowButton
protected Widget m_DownArrowButton private
Definition at line 10 of file Header.c.
Referenced by Header(), and CollapsibleHeader::SetArrowButtonOpened().
m_Entity
protected EntityAI m_Entity private
Definition at line 6 of file Header.c.
Referenced by ClosableHeader::MouseEnter(), ClosableHeader::OnDragHeader(), ClosableHeader::OnDropHeader(), SetItemPreview(), ClosableHeader::UpdateFlip(), and ClosableHeader::~ClosableHeader().
m_HeaderText
protected TextWidget m_HeaderText private
Definition at line 11 of file Header.c.
Referenced by Header(), ClosableHeader::SetName(), and SetName().
m_UpArrowButton
protected Widget m_UpArrowButton private
Definition at line 9 of file Header.c.
Referenced by Header(), and CollapsibleHeader::SetArrowButtonOpened().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/ContainedItems/Headers/Header.c