DayZ Scripts: PMTF Class Reference
PMTF Class Reference
Private Member Functions
int InsertManager (ParticleManager pm)
bool GetManager (int id, out ParticleManager pm)
protected void PrintPMStats (notnull ParticleManager pm)
protected void PrintActiveStats ()
protected ParticleManager CreatePMFixedBlocking (int size)
Private Attributes
private ref map< int, ref ParticleManager > m_Managers = new map<int, ref ParticleManager>()
Static Private Attributes
static private int PM_CREATED = 0
Member Function Documentation
CreatePMFixedBlocking()
protected ParticleManager CreatePMFixedBlocking (int size) inline private
References ParticleManager(), and ParticleManagerSettings().
Referenced by TestCreationSmallBlocking(), PMTPlayback::TestOnePlaying(), and TestOwnership().
GetManager()
bool GetManager (int id, out ParticleManager pm) inline private
References m_Managers.
Referenced by PMTPlayback::CheckOnePlaying(), and CheckTestEvents().
InsertManager()
int InsertManager (ParticleManager pm) inline private
References Assert(), m_Managers, and PM_CREATED.
Referenced by TestEvents(), PMTPlayback::TestOnePlaying(), and TestOwnership().
PrintActiveStats()
protected void PrintActiveStats () inline private
References ParticleSource::GetStaticActiveCount(), Debug::ParticleLog(), and ParticleManager().
Referenced by TestCleanup().
PrintPMStats()
protected void PrintPMStats (notnull ParticleManager pm) inline private
References Debug::ParticleLog().
Referenced by TestCreationSmallBlocking().
Field Documentation
m_Managers
private ref map<int, ref ParticleManager> m_Managers = new map<int, ref ParticleManager>() private
Referenced by GetManager(), and InsertManager().
PM_CREATED
private int PM_CREATED = 0 static private
Referenced by InsertManager().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Particles/Tests/PMTF.c