DayZ Scripts: AreaDamageEvents Class Reference
AreaDamageEvents Class Reference
Events used across AreaDamage API, calling of these needs to be handled by parent.
Private Member Functions
void OnTriggerCreated ()
void OnTriggerDestroyed ()
Called when a trigger is destroyed.
void OnEnterBeginEvent (TriggerInsider insider)
void OnEnterServerEvent (TriggerInsider insider)
void OnEnterClientEvent (TriggerInsider insider)
void OnEnterEndEvent (TriggerInsider insider)
void OnStayStartBeginEvent (int nrOfInsiders)
void OnStayStartServerEvent (int nrOfInsiders)
void OnStayStartClientEvent (int nrOfInsiders)
void OnStayStartEndEvent (int nrOfInsiders)
void OnStayBeginEvent (TriggerInsider insider, float deltaTime)
void OnStayServerEvent (TriggerInsider insider, float deltaTime)
void OnStayClientEvent (TriggerInsider insider, float deltaTime)
void OnStayEndEvent (TriggerInsider insider, float deltaTime)
void OnStayFinishBeginEvent ()
void OnStayFinishServerEvent ()
void OnStayFinishClientEvent ()
void OnStayFinishEndEvent ()
void OnLeaveBeginEvent (TriggerInsider insider)
void OnLeaveServerEvent (TriggerInsider insider)
void OnLeaveClientEvent (TriggerInsider insider)
void OnLeaveEndEvent (TriggerInsider insider)
protected bool OnEvaluateDamage (TriggerInsider insider, float damageCoef)
protected void PreDamageActions ()
protected void PostDamageActions ()
Called after an object was damaged (only when it actually damaged an object)
Detailed Description
Events used across AreaDamage API, calling of these needs to be handled by parent.
Definition at line 2 of file AreaDamageEvents.c.
Member Function Documentation
OnEnterBeginEvent()
void OnEnterBeginEvent (TriggerInsider insider) inline private
Called when an object enters the trigger
Definition at line 13 of file AreaDamageEvents.c.
OnEnterClientEvent()
void OnEnterClientEvent (TriggerInsider insider) inline private
Definition at line 15 of file AreaDamageEvents.c.
OnEnterEndEvent()
void OnEnterEndEvent (TriggerInsider insider) inline private
Definition at line 16 of file AreaDamageEvents.c.
OnEnterServerEvent()
void OnEnterServerEvent (TriggerInsider insider) inline private
Definition at line 14 of file AreaDamageEvents.c.
OnEvaluateDamage()
protected bool OnEvaluateDamage (TriggerInsider insider, float damageCoef) inline private
Called when an object gets evaluated for taking damage
Definition at line 53 of file AreaDamageEvents.c.
Referenced by OnEvaluateDamageEx().
OnLeaveBeginEvent()
void OnLeaveBeginEvent (TriggerInsider insider) inline private
Called when an object leaves the trigger
Definition at line 45 of file AreaDamageEvents.c.
OnLeaveClientEvent()
void OnLeaveClientEvent (TriggerInsider insider) inline private
Definition at line 47 of file AreaDamageEvents.c.
OnLeaveEndEvent()
void OnLeaveEndEvent (TriggerInsider insider) inline private
Definition at line 48 of file AreaDamageEvents.c.
OnLeaveServerEvent()
void OnLeaveServerEvent (TriggerInsider insider) inline private
Definition at line 46 of file AreaDamageEvents.c.
OnStayBeginEvent()
void OnStayBeginEvent (TriggerInsider insider, float deltaTime) inline private
Called in the update loop
Definition at line 29 of file AreaDamageEvents.c.
OnStayClientEvent()
void OnStayClientEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 31 of file AreaDamageEvents.c.
OnStayEndEvent()
void OnStayEndEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 32 of file AreaDamageEvents.c.
OnStayFinishBeginEvent()
void OnStayFinishBeginEvent () inline private
Called at the end of an update loop
Definition at line 37 of file AreaDamageEvents.c.
OnStayFinishClientEvent()
void OnStayFinishClientEvent () inline private
Definition at line 39 of file AreaDamageEvents.c.
OnStayFinishEndEvent()
void OnStayFinishEndEvent () inline private
Definition at line 40 of file AreaDamageEvents.c.
OnStayFinishServerEvent()
void OnStayFinishServerEvent () inline private
Definition at line 38 of file AreaDamageEvents.c.
OnStayServerEvent()
void OnStayServerEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 30 of file AreaDamageEvents.c.
OnStayStartBeginEvent()
void OnStayStartBeginEvent (int nrOfInsiders) inline private
Called at the beginning of an update loop
Definition at line 21 of file AreaDamageEvents.c.
OnStayStartClientEvent()
void OnStayStartClientEvent (int nrOfInsiders) inline private
Definition at line 23 of file AreaDamageEvents.c.
OnStayStartEndEvent()
void OnStayStartEndEvent (int nrOfInsiders) inline private
Definition at line 24 of file AreaDamageEvents.c.
OnStayStartServerEvent()
void OnStayStartServerEvent (int nrOfInsiders) inline private
Definition at line 22 of file AreaDamageEvents.c.
OnTriggerCreated()
void OnTriggerCreated () inline private
Called when a trigger is created
Definition at line 6 of file AreaDamageEvents.c.
Referenced by Spawn().
OnTriggerDestroyed()
void OnTriggerDestroyed () inline private
Called when a trigger is destroyed.
Definition at line 8 of file AreaDamageEvents.c.
Referenced by Destroy().
PostDamageActions()
protected void PostDamageActions () inline private
Called after an object was damaged (only when it actually damaged an object)
Definition at line 60 of file AreaDamageEvents.c.
Referenced by EvaluateDamageInternal().
PreDamageActions()
protected void PreDamageActions () inline private
Called before an object is damaged (only when it actually damaged an object)
Definition at line 58 of file AreaDamageEvents.c.
Referenced by EvaluateDamageInternal().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/AreaDamage/AreaDamageNew/AreaDamageEvents.c