DayZ Scripts: ItemOptics Class Reference
ItemOptics Class Reference
Private Member Functions
void ItemOptics ()
proto native bool EnterOptics ()
switches to optics mode if possible
proto native bool IsInOptics ()
is weapon in optics mode or not
proto native bool ExitOptics ()
switches out of optics mode (if possible)
proto native bool HasWeaponIronsightsOverride ()
is weapon in optics mode or not
proto native bool UseWeaponIronsightsOverride (bool state)
switches into ironsights override settings
proto native bool IsUsingWeaponIronsightsOverride ()
is optics using ironsights override settings or not
proto native int GetStepFOVCount ()
returns number of configured steps
proto native int GetStepFOVIndex ()
returns index of currently used value in 'discretefov' config array
proto native bool SetStepFOVIndex (int step)
sets zoom to fov value defined at given in 'discretefov' config array
proto native bool StepFOVUp ()
sets zoom to next defined (respective to current) value in zoom fov config array
proto native bool StepFOVDown ()
sets zoom to previous (respective to current) defined value in zoom fov config array
proto native float GetCurrentStepFOV ()
returns fov value at current index, or 'OpticsInfo.opticsZoomInit' config value (non-zooming optics)
proto native int GetStepZeroing ()
returns position of currently used value in zeroing config array
proto native bool SetStepZeroing (int step)
proto native bool StepZeroingUp ()
sets zeroing to next defined (respective to current) value in zeroing config array
proto native bool StepZeroingDown ()
sets zeroing to previous (respective to current) defined value in zeroing config array
proto native void GetCameraPoint (out vector pos, out vector dir)
gets camera position & direction in model space of optics entity
proto native float GetZoomInit ()
gets FOV value, when entering optics
proto native float GetZoomMin ()
gets FOV minimum
proto native float GetZoomMax ()
gets FOV maximum
proto native float GetZeroingDistanceZoomMin ()
Gets Zeroing distance at opticsZoomMin.
proto native float GetZeroingDistanceZoomMax ()
Gets Zeroing distance at opticsZoomMax.
proto native void SetZeroingClampDist (float dist)
Sets zeroing clamp for the optics and updates the clamp if dist > 0. Used when attached to weapon.
override void OnWorkStart ()
override void OnWorkStop ()
bool IsWorking ()
void UpdateOpticsReddotVisibility ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnInventoryExit (Man player)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnVariablesSynchronized ()
void InitReddotData ()
void ShowReddot (bool state)
void InitOpticsPPInfo ()
bool InitDOFAvailability ()
optics with more than 1x zoom do not allow DOF changes
void InitOpticsPP (out array< float > mask_array, out array< float > lens_array, out float blur_float)
initializes values for optics' post-processes
void InitCameraOverrideProperties ()
bool InitOpticsDOFProperties (out array< float > temp_array)
Initializes DOF properties for optic's alternate ironsights (ACOG etc.)
bool AllowsDOF ()
returns 'true' for non-magnifying optics
bool IsNVOptic ()
int GetCurrentNVType ()
void SetCurrentOpticMode (int mode)
int GetCurrentOpticMode ()
void OnOpticModeChange ()
optic-specific behaviour to be defined here (override)
void OnOpticEnter ()
void OnOpticExit ()
ref array< float > GetOpticsDOF ()
ref array< float > GetOpticsPPMask ()
ref array< float > GetOpticsPPLens ()
float GetOpticsPPBlur ()
float GetNearPlaneValue ()
void Init2DPreloadType ()
void InitOpticMode ()
void UpdateSelectionVisibility ()
override void SetActions ()
override void OnDebugSpawn ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
void HuntingOptic ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void HideSelection (string selection_name)
override void ShowSelection (string selection_name)
bool ParentUsesWinchesterTypeMount ()
override bool CanPutAsAttachment (EntityAI parent)
void SetPlayer (PlayerBase player)
PlayerBase GetPlayer ()
Private Attributes
bool m_data_set
bool m_allowsDOF
bool m_reddot_displayed bool m_isNVOptic = false
int m_CurrentOpticMode
int m_CurrentOpticModeLocal
int m_reddot_index
float m_blur_float
float m_nearplane_override
string m_optic_sight_texture
string m_optic_sight_material
string m_2D_preload_type
ref array< float > m_mask_array
ref array< float > m_lens_array
ref array< float > m_OpticsDOFProperties
EntityAI m_Parent
protected PlayerBase m_Player
Constructor & Destructor Documentation
ItemOptics()
void ItemOptics () inline private
References Init2DPreloadType(), InitCameraOverrideProperties(), InitOpticMode(), InitOpticsDOFProperties(), InitOpticsPPInfo(), InitReddotData(), m_CurrentOpticModeLocal, m_lens_array, m_mask_array, and m_OpticsDOFProperties.
Member Function Documentation
AllowsDOF()
bool AllowsDOF () inline private
returns 'true' for non-magnifying optics
References m_allowsDOF.
Referenced by Weapon::HideWeaponBarrel(), and SetCameraPP().
CanPutAsAttachment() [1/3]
override bool CanPutAsAttachment (EntityAI parent) inline private
CanPutAsAttachment() [2/3]
override bool CanPutAsAttachment (EntityAI parent) inline private
CanPutAsAttachment() [3/3]
override bool CanPutAsAttachment (EntityAI parent) inline private
EnterOptics()
EnterOptics () private
switches to optics mode if possible
Returns
true if success, false otherwise
Referenced by ActionViewBinoculars::EnterOptics(), ActionViewOptics::EnterOptics(), ActionZoomIn::OnEndServer(), and DayZPlayer::SwitchOptics().
ExitOptics()
ExitOptics () private
switches out of optics mode (if possible)
Returns
true if success, false otherwise
Referenced by ActionZoomOut::OnEndServer(), and DayZPlayer::SwitchOptics().
GetCameraPoint()
GetCameraPoint (out vector pos, out vector dir) private
gets camera position & direction in model space of optics entity
Referenced by DayZPlayerCameraBase::GetCurrentSightInfo(), and GetCurrentSightInfo().
GetCurrentNVType()
int GetCurrentNVType () inline private
Referenced by SetCameraPP().
GetCurrentOpticMode()
int GetCurrentOpticMode () inline private
References m_CurrentOpticMode.
Referenced by ActionToggleNVMode::SwitchMode(), KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
GetCurrentStepFOV()
GetCurrentStepFOV () private
returns fov value at current index, or 'OpticsInfo.opticsZoomInit' config value (non-zooming optics)
Referenced by ManBase::HideClothing(), and HoldBreathFOVEffect().
GetNearPlaneValue()
float GetNearPlaneValue () inline private
References m_nearplane_override.
Referenced by AdjustCameraParameters().
GetOpticsDOF()
ref array< float > GetOpticsDOF () inline private
References m_OpticsDOFProperties.
Referenced by DayZPlayerCameraBase::SetCameraPP(), and SetCameraPP().
GetOpticsPPBlur()
float GetOpticsPPBlur () inline private
References m_blur_float.
Referenced by SetCameraPP().
GetOpticsPPLens()
ref array< float > GetOpticsPPLens () inline private
References m_lens_array.
Referenced by SetCameraPP().
GetOpticsPPMask()
ref array< float > GetOpticsPPMask () inline private
References m_mask_array.
Referenced by SetCameraPP().
GetPlayer()
PlayerBase GetPlayer () inline private
References m_Player.
GetStepFOVCount()
GetStepFOVCount () private
returns number of configured steps
GetStepFOVIndex()
GetStepFOVIndex () private
returns index of currently used value in 'discretefov' config array
Returns
index of currently used value in 'discretefov' config array
GetStepZeroing()
GetStepZeroing () private
returns position of currently used value in zeroing config array
Returns
position of currently used value in zeroing config array
GetZeroingDistanceZoomMax()
GetZeroingDistanceZoomMax () private
Gets Zeroing distance at opticsZoomMax.
GetZeroingDistanceZoomMin()
GetZeroingDistanceZoomMin () private
Gets Zeroing distance at opticsZoomMin.
GetZoomInit()
GetZoomInit () private
gets FOV value, when entering optics
GetZoomMax()
GetZoomMax () private
gets FOV maximum
GetZoomMin()
GetZoomMin () private
gets FOV minimum
HasWeaponIronsightsOverride()
HasWeaponIronsightsOverride () private
is weapon in optics mode or not
Returns
true if optics has defined override optics info for weapon
Referenced by Weapon::CanEnterIronsights(), and DayZPlayerCameraBase::SetupSightEntities().
HideSelection()
override void HideSelection (string selection_name) inline private
References HideSelection().
Referenced by ActionViewBinoculars::EnterOptics(), ActionViewOptics::EnterOptics(), HideSelection(), HuntingOptic(), OnOpticEnter(), KazuarOptic::OnOpticEnter(), StarlightOptic::OnOpticEnter(), OnWasAttached(), OnWasDetached(), ShowSelection(), KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
HuntingOptic()
void HuntingOptic () inline private
References HideSelection().
Init2DPreloadType()
void Init2DPreloadType () inline private
References CGame::ConfigGetText(), GetGame(), GetType(), m_2D_preload_type, and path.
Referenced by ItemOptics().
InitCameraOverrideProperties()
void InitCameraOverrideProperties () inline private
References DayZPlayerCameraOptics(), GetGame(), GetType(), m_nearplane_override, Math::Max(), and path.
Referenced by ItemOptics().
InitDOFAvailability()
bool InitDOFAvailability () inline private
optics with more than 1x zoom do not allow DOF changes
References CGame::ConfigGetFloat(), GameConstants::DZPLAYER_CAMERA_FOV_IRONSIGHTS, GetGame(), GetType(), and path.
Referenced by InitOpticsPPInfo().
InitOpticMode()
void InitOpticMode () inline private
References GameConstants::OPTICS_STATE_DAY, and SetCurrentOpticMode().
Referenced by ItemOptics().
InitOpticsDOFProperties()
bool InitOpticsDOFProperties (out array< float > temp_array) inline private
Initializes DOF properties for optic's alternate ironsights (ACOG etc.)
References CGame::ConfigGetFloatArray(), GetGame(), and GetType().
Referenced by ItemOptics().
InitOpticsPP()
void InitOpticsPP (out array< float > mask_array, out array< float > lens_array, out float blur_float) inline private
initializes values for optics' post-processes
References CGame::ConfigGetFloat(), CGame::ConfigGetFloatArray(), GetGame(), GetType(), and path.
Referenced by InitOpticsPPInfo().
InitOpticsPPInfo()
void InitOpticsPPInfo () inline private
References InitDOFAvailability(), InitOpticsPP(), m_allowsDOF, m_blur_float, m_isNVOptic, m_lens_array, and m_mask_array.
Referenced by ItemOptics().
InitReddotData()
void InitReddotData () inline private
References CGame::ConfigGetText(), GetGame(), GetType(), m_data_set, m_optic_sight_material, m_optic_sight_texture, m_reddot_index, and path.
Referenced by ItemOptics(), and ShowReddot().
IsInOptics()
IsInOptics () private
is weapon in optics mode or not
Returns
true if in optics mode, false otherwise
Referenced by ActionViewBinoculars::ActionCondition(), ActionViewOptics::ActionCondition(), ActionZoomIn::ActionCondition(), ActionZoomOut::ActionCondition(), DayZPlayer::HandleWeapons(), ActionViewOptics::OnEndClient(), ActionViewOptics::OnEndServer(), ActionViewOptics::OnStartAnimationLoopClient(), ActionViewOptics::OnStartAnimationLoopServer(), KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
IsNVOptic()
bool IsNVOptic () inline private
References m_isNVOptic.
Referenced by ActionToggleNVMode::ActionCondition(), Init(), and SetCameraPP().
IsUsingWeaponIronsightsOverride()
IsUsingWeaponIronsightsOverride () private
is optics using ironsights override settings or not
Returns
true if optics is using ironsights override settings
Referenced by DayZPlayer::HandleWeapons().
IsWorking()
bool IsWorking () inline private
Referenced by KazuarOptic::GetCurrentNVType(), StarlightOptic::GetCurrentNVType(), Init(), and UpdateOpticsReddotVisibility().
OnDebugSpawn()
override void OnDebugSpawn () inline private
OnInventoryExit()
override void OnInventoryExit (Man player) inline private
References SetTakeable().
OnOpticEnter()
void OnOpticEnter () inline private
References GetGame(), and HideSelection().
Referenced by DayZPlayer::SwitchOptics().
OnOpticExit()
void OnOpticExit () inline private
References GetGame(), and ShowSelection().
Referenced by DayZPlayer::SwitchOptics().
OnOpticModeChange()
void OnOpticModeChange () inline private
optic-specific behaviour to be defined here (override)
Referenced by OnStoreLoad(), OnVariablesSynchronized(), and SetCurrentOpticMode().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References m_CurrentOpticMode, m_IsStoreLoad, OnOpticModeChange(), and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
References m_CurrentOpticMode, and Serializer::Write().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References m_CurrentOpticMode, m_CurrentOpticModeLocal, and OnOpticModeChange().
OnWasAttached() [1/2]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
References Class::CastTo(), SetTakeable(), and SetZeroingClampDist().
OnWasAttached() [2/2]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
References HideSelection(), m_Parent, ParentUsesWinchesterTypeMount(), and ShowSelection().
OnWasDetached() [1/2]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
References Class::CastTo(), SetTakeable(), and SetZeroingClampDist().
OnWasDetached() [2/2]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
References HideSelection(), m_Parent, and ShowSelection().
OnWorkStart()
override void OnWorkStart () inline private
References GetGame(), and ShowReddot().
OnWorkStop()
override void OnWorkStop () inline private
References GetGame(), and ShowReddot().
ParentUsesWinchesterTypeMount()
bool ParentUsesWinchesterTypeMount () inline private
References m_Parent.
Referenced by OnWasAttached(), and ShowSelection().
SetActions()
override void SetActions () inline private
References AddAction().
SetCurrentOpticMode()
void SetCurrentOpticMode (int mode) inline private
References m_CurrentOpticMode, and OnOpticModeChange().
Referenced by InitOpticMode(), KazuarOptic::InitOpticMode(), StarlightOptic::InitOpticMode(), and ActionToggleNVMode::SwitchMode().
SetPlayer()
void SetPlayer (PlayerBase player) inline private
References m_Player.
SetStepFOVIndex()
SetStepFOVIndex (int step) private
sets zoom to fov value defined at given in 'discretefov' config array
Parameters
[in] index of configured step, range [0..cfg_max]
Returns
true if zoom set
SetStepZeroing()
proto native bool SetStepZeroing (int step) private
SetZeroingClampDist()
SetZeroingClampDist (float dist) private
Sets zeroing clamp for the optics and updates the clamp if dist > 0. Used when attached to weapon.
Referenced by OnWasAttached(), and OnWasDetached().
ShowReddot()
void ShowReddot (bool state) inline private
References ErrorEx, GetGame(), InitReddotData(), m_data_set, m_optic_sight_material, m_optic_sight_texture, and m_reddot_index.
Referenced by OnWorkStart(), OnWorkStop(), and UpdateOpticsReddotVisibility().
ShowSelection()
override void ShowSelection (string selection_name) inline private
References HideSelection(), ParentUsesWinchesterTypeMount(), and ShowSelection().
Referenced by ActionViewBinoculars::ExitOptics(), ActionViewOptics::ExitOptics(), OnOpticExit(), OnWasAttached(), OnWasDetached(), ShowSelection(), KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
StepFOVDown()
StepFOVDown () private
sets zoom to previous (respective to current) defined value in zoom fov config array
Returns
true if zoom set
StepFOVUp()
StepFOVUp () private
sets zoom to next defined (respective to current) value in zoom fov config array
Returns
true if zoom set
StepZeroingDown()
StepZeroingDown () private
sets zeroing to previous (respective to current) defined value in zeroing config array
Returns
true if zeroing set
Referenced by DayZPlayer::HandleWeapons().
StepZeroingUp()
StepZeroingUp () private
sets zeroing to next defined (respective to current) value in zeroing config array
Returns
true if zeroing set
Referenced by DayZPlayer::HandleWeapons().
UpdateOpticsReddotVisibility()
void UpdateOpticsReddotVisibility () inline private
References IsWorking(), and ShowReddot().
Referenced by DayZPlayerCameraBase::UpdateBatteryOptics().
UpdateSelectionVisibility()
void UpdateSelectionVisibility () inline private
UseWeaponIronsightsOverride()
UseWeaponIronsightsOverride (bool state) private
switches into ironsights override settings
Returns
true if switching was successful
Referenced by DayZPlayerCameraBase::GetCurrentSightInfo(), and GetCurrentSightInfo().
Field Documentation
m_2D_preload_type
string m_2D_preload_type private
Referenced by Init2DPreloadType().
m_allowsDOF
bool m_allowsDOF private
Referenced by AllowsDOF(), and InitOpticsPPInfo().
m_blur_float
float m_blur_float private
Referenced by GetOpticsPPBlur(), and InitOpticsPPInfo().
m_CurrentOpticMode
int m_CurrentOpticMode private
Referenced by KazuarOptic::GetCurrentNVType(), StarlightOptic::GetCurrentNVType(), GetCurrentOpticMode(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), and SetCurrentOpticMode().
m_CurrentOpticModeLocal
int m_CurrentOpticModeLocal private
Referenced by ItemOptics(), and OnVariablesSynchronized().
m_data_set
bool m_data_set private
Referenced by InitReddotData(), and ShowReddot().
m_isNVOptic
bool m_reddot_displayed bool m_isNVOptic = false private
Referenced by InitOpticsPPInfo(), and IsNVOptic().
m_lens_array
ref array<float> m_lens_array private
Referenced by GetOpticsPPLens(), InitOpticsPPInfo(), and ItemOptics().
m_mask_array
ref array<float> m_mask_array private
Referenced by GetOpticsPPMask(), InitOpticsPPInfo(), and ItemOptics().
m_nearplane_override
float m_nearplane_override private
Referenced by GetNearPlaneValue(), and InitCameraOverrideProperties().
m_optic_sight_material
string m_optic_sight_material private
Referenced by InitReddotData(), and ShowReddot().
m_optic_sight_texture
string m_optic_sight_texture private
Referenced by InitReddotData(), and ShowReddot().
m_OpticsDOFProperties
ref array<float> m_OpticsDOFProperties private
Referenced by GetOpticsDOF(), and ItemOptics().
m_Parent
EntityAI m_Parent private
m_Player
protected PlayerBase m_Player private
Referenced by ActionViewOptics::OnEndAnimationLoopClient(), ActionViewOptics::OnEndAnimationLoopServer(), ActionViewOptics::OnEndClient(), ActionViewOptics::OnEndServer(), ActionViewOptics::OnStartAnimationLoopClient(), and ActionViewOptics::OnStartAnimationLoopServer().
m_reddot_index
int m_reddot_index private
Referenced by InitReddotData(), and ShowReddot().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Core/Inherited/ItemOptics.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/HuntingOptic.c
P:/scripts/4_World/Entities/ItemBase/PoweredOptic_Base.c
P:/scripts/4_World/Entities/Firearms/Launcher/M79.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/BUISOptic.c
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/M4_CarryHandleOptic.c