DayZ Scripts: ActionEnterLadder Class Reference
ActionEnterLadder Class Reference
Private Member Functions
void ActionEnterLadder ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void Start (ActionData action_data)
override bool IsInstant ()
override bool UseAcknowledgment ()
override bool CanBeUsedSwimming ()
Private Attributes
private const string GEOM_LOD_NAME = LOD.NAME_GEOMETRY
private const string MEM_LOD_NAME = LOD.NAME_MEMORY
Constructor & Destructor Documentation
ActionEnterLadder()
void ActionEnterLadder () inline private
References m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
is action_data.m_Target ? not on ladder and not falling ?
References Math::AbsFloat(), Class::CastTo(), HumanCommandLadder::DebugDrawLadder(), HumanCommandLadder::DebugGetLadderIndex(), vector::DistanceSq(), GetName(), LOD::GetSelections(), UAMaxDistances::LADDERS, string::Length(), MEM_LOD_NAME, string::Substring(), and vector::VectorToAngles().
CanBeUsedSwimming()
override bool CanBeUsedSwimming () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References m_ConditionItem, and m_ConditionTarget.
IsInstant()
override bool IsInstant () inline private
Start()
override void Start (ActionData action_data) inline private
References Class::CastTo(), HumanCommandLadder::DebugGetLadderIndex(), GEOM_LOD_NAME, LOD::GetPropertyCount(), LOD::GetPropertyName(), LOD::GetPropertyValue(), ActionData::m_Player, and ActionData::m_Target.
UseAcknowledgment()
override bool UseAcknowledgment () inline private
Field Documentation
GEOM_LOD_NAME
private const string GEOM_LOD_NAME = LOD.NAME_GEOMETRY private
Referenced by Start().
MEM_LOD_NAME
private const string MEM_LOD_NAME = LOD.NAME_MEMORY private
Referenced by ActionCondition().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionEnterLadder.c