DayZ Scripts: SlotsContainer Class Reference
SlotsContainer Class Reference
Private Member Functions
void SlotsContainer (LayoutHolder parent, EntityAI slot_parent)
override void SetDefaultFocus (bool while_micromanagment_mode=false)
override void SetLastFocus ()
void SetFocus (int index)
void SetVisibleFocus (int index)
int GetVisibleFocus ()
override void SetNextRightActive ()
override void SetNextLeftActive ()
void UpdateIcon ()
override void UnfocusAll ()
override void Unfocus ()
override bool SelectItem ()
override bool IsEmpty ()
override bool IsDisplayable ()
SlotsIcon GetSlotIcon (int index)
override SlotsIcon GetFocusedSlotsIcon ()
override EntityAI GetFocusedItem ()
override void SetLayoutName ()
bool VerifySlotsIconVisibility (int idx=-1)
Returns 'true' if radial icon is VISIBLE and also OPEN (individual icon or any icon, use parameter..)
Private Attributes
protected ref array< ref SlotsIcon > m_Icons
int m_VisibleColumnCount
Detailed Description
Definition at line 1 of file SlotsContainer.c.
Constructor & Destructor Documentation
SlotsContainer()
void SlotsContainer (LayoutHolder parent, EntityAI slot_parent) inline private
Definition at line 6 of file SlotsContainer.c.
References FindAnyWidget(), ITEMS_IN_ROW, and m_Icons.
Member Function Documentation
GetFocusedItem()
override EntityAI GetFocusedItem () inline private
Definition at line 226 of file SlotsContainer.c.
References GetFocusedSlotsIcon(), SlotsIcon::GetObject(), and SlotsIcon::IsReserved().
Referenced by SelectItem(), and UpdateIcon().
GetFocusedSlotsIcon()
override SlotsIcon GetFocusedSlotsIcon () inline private
Definition at line 217 of file SlotsContainer.c.
References m_Icons.
Referenced by AttachmentCategoriesSlotsContainer::ExpandCollapseContainer(), AttachmentCategoriesSlotsContainer::GetFocusedID(), GetFocusedItem(), AttachmentCategoriesSlotsContainer::GetFocusedItem(), and SelectItem().
GetSlotIcon()
SlotsIcon GetSlotIcon (int index) inline private
Definition at line 207 of file SlotsContainer.c.
References m_Icons.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), ZombieContainer::GetSlotsIcon(), AttachmentsGroupContainer::GetSlotsIcon(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), AttachmentCategoriesContainer::InitGhostSlots(), IsDisplayable(), AttachmentCategoriesContainer::LoadAttachmentCategoriesIcon(), VicinitySlotsContainer::RecomputeNumberOfContainers(), AttachmentCategoriesContainer::ShowInSlots(), VicinitySlotsContainer::ShowItemsInContainers(), and UpdateIcon().
GetVisibleFocus()
int GetVisibleFocus () inline private
Definition at line 75 of file SlotsContainer.c.
References SlotsIcon::IsVisible(), and m_Icons.
Referenced by AttachmentsGroupContainer::SetNextActive(), and AttachmentsGroupContainer::SetPreviousActive().
IsDisplayable()
override bool IsDisplayable () inline private
Definition at line 193 of file SlotsContainer.c.
References GetSlotIcon(), and IsVisible().
IsEmpty()
override bool IsEmpty () inline private
Definition at line 188 of file SlotsContainer.c.
SelectItem()
override bool SelectItem () inline private
Definition at line 175 of file SlotsContainer.c.
References SlotsIcon::GetCursorWidget(), GetFocusedItem(), GetFocusedSlotsIcon(), ItemManager::GetInstance(), SlotsIcon::IsOutOfReach(), SlotsIcon::IsReserved(), ItemBase::IsTakeable(), and ItemManager::SetSelectedItem().
SetDefaultFocus()
override void SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 24 of file SlotsContainer.c.
References SlotsIcon::IsVisible(), m_Icons, and SetFocus().
Referenced by SetLastFocus().
SetFocus()
void SetFocus (int index) inline private
Definition at line 45 of file SlotsContainer.c.
References m_Icons, and UpdateIcon().
Referenced by SetDefaultFocus(), and SetVisibleFocus().
SetLastFocus()
override void SetLastFocus () inline private
Definition at line 40 of file SlotsContainer.c.
References SetDefaultFocus().
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 238 of file SlotsContainer.c.
References InventoryMenu(), WidgetLayoutName::InventorySlotsContainerMedium, WidgetLayoutName::InventorySlotsContainerNarrow, WidgetLayoutName::InventorySlotsContainerWide, and WidgetLayoutName::InventorySlotsContainerXbox.
SetNextLeftActive()
override void SetNextLeftActive () inline private
Definition at line 116 of file SlotsContainer.c.
References SlotsIcon::IsVisible(), m_Icons, Unfocus(), and UpdateIcon().
SetNextRightActive()
override void SetNextRightActive () inline private
Definition at line 93 of file SlotsContainer.c.
References SlotsIcon::IsVisible(), m_Icons, Unfocus(), and UpdateIcon().
SetVisibleFocus()
void SetVisibleFocus (int index) inline private
Definition at line 54 of file SlotsContainer.c.
References SlotsIcon::IsVisible(), m_Icons, SetFocus(), and Unfocus().
Referenced by AttachmentsGroupContainer::SetNextActive(), and AttachmentsGroupContainer::SetPreviousActive().
Unfocus()
override void Unfocus () inline private
Definition at line 166 of file SlotsContainer.c.
References m_Icons.
Referenced by SetNextLeftActive(), SetNextRightActive(), and SetVisibleFocus().
UnfocusAll()
override void UnfocusAll () inline private
Definition at line 158 of file SlotsContainer.c.
References m_Icons.
UpdateIcon()
void UpdateIcon () inline private
Definition at line 139 of file SlotsContainer.c.
References SlotsIcon::GetCursorWidget(), GetFocusedItem(), SlotsIcon::GetSlotDesc(), SlotsIcon::GetSlotDisplayName(), GetSlotIcon(), x, and y.
Referenced by SetFocus(), SetNextLeftActive(), and SetNextRightActive().
VerifySlotsIconVisibility()
bool VerifySlotsIconVisibility (int idx = -1) inline private
Returns 'true' if radial icon is VISIBLE and also OPEN (individual icon or any icon, use parameter..)
Definition at line 266 of file SlotsContainer.c.
References IsVisible(), and m_Icons.
Field Documentation
m_Icons
protected ref array<ref SlotsIcon> m_Icons private
Definition at line 3 of file SlotsContainer.c.
Referenced by GetFocusedSlotsIcon(), GetSlotIcon(), GetVisibleFocus(), SetDefaultFocus(), SetFocus(), SetNextLeftActive(), SetNextRightActive(), SetVisibleFocus(), SlotsContainer(), Unfocus(), UnfocusAll(), and VerifySlotsIconVisibility().
m_VisibleColumnCount
int m_VisibleColumnCount private
Definition at line 4 of file SlotsContainer.c.
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/ContainedItems/SlotsContainer.c