DayZ Scripts: LiquidInfo Class Reference
LiquidInfo Class Reference
Private Member Functions
void LiquidInfo (string className, NutritionalProfile profile)
protected void Init (string className)
Private Attributes
string m_LiquidClassName
string m_LiquidDisplayName
int m_LiquidType
float m_TemperatureLiquidFreezeThreshold = float.LOWEST
float m_TemperatureLiquidThawThreshold = float.LOWEST
float m_TemperatureLiquidBoilThreshold = Cooking.LIQUID_BOILING_POINT
float m_Flammability
ref NutritionalProfile m_NutriProfile
Constructor & Destructor Documentation
LiquidInfo()
void LiquidInfo (string className, NutritionalProfile profile) inline private
References Init(), and m_NutriProfile.
Member Function Documentation
Init()
protected void Init (string className) inline private
References CGame::ConfigGetFloat(), CGame::ConfigGetInt(), CGame::ConfigGetTextRaw(), CGame::FormatRawConfigStringKeys(), GetGame(), m_Flammability, m_LiquidClassName, m_LiquidDisplayName, m_LiquidType, m_TemperatureLiquidBoilThreshold, m_TemperatureLiquidFreezeThreshold, m_TemperatureLiquidThawThreshold, and path.
Field Documentation
m_Flammability
float m_Flammability private
Referenced by Init().
m_LiquidClassName
string m_LiquidClassName private
Referenced by GetLiquidClassname(), and Init().
m_LiquidDisplayName
string m_LiquidDisplayName private
Referenced by Init().
m_LiquidType
int m_LiquidType private
Referenced by Init().
m_NutriProfile
ref NutritionalProfile m_NutriProfile private
Referenced by GetNutritionalProfileByName(), GetNutritionalProfileByType(), and LiquidInfo().
m_TemperatureLiquidBoilThreshold
float m_TemperatureLiquidBoilThreshold = Cooking.LIQUID_BOILING_POINT private
Referenced by Init().
m_TemperatureLiquidFreezeThreshold
float m_TemperatureLiquidFreezeThreshold = float.LOWEST private
Referenced by Init().
m_TemperatureLiquidThawThreshold
float m_TemperatureLiquidThawThreshold = float.LOWEST private
Referenced by Init().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/Liquid.c