DayZ Scripts: P:/scripts/4_World/Classes/SoundEvents/ReplaceSoundEvents/ReplaceSoundEventHandler.c File Reference
ReplaceSoundEventHandler.c File Reference
Enumerations
enum ESoundEventType { SOUND_COMMON , SOUND_ATTACHMENT , SOUND_VOICE }
Functions
void ReplaceSoundEventHandler (PlayerBase player)
protected void RegisterEvent (ReplaceSoundEventBase soundEvent)
int GetSoundEventID (int anim_id, ESoundEventType soundType)
ReplaceSoundEventBase GetSoundEventByID (int id, ESoundEventType soundType)
bool PlayReplaceSound (int soundEventID, ESoundEventType soundType, int flags)
Variables
enum ESoundEventType DIG_PRIMARY = 1
enum ESoundEventType DIG_SECONDARY = 1
enum ESoundEventType CLEANHANDS_PRIMARY = 1
enum ESoundEventType int = 1
enum ESoundEventType m_SoundEventReplaceMaps = {}
protected PlayerBase m_Player
protected ref Timer m_UpdateTimer
Enumeration Type Documentation
ESoundEventType
enum ESoundEventType
Enumerator
SOUND_COMMON
SOUND_ATTACHMENT
SOUND_VOICE
Function Documentation
GetSoundEventByID()
ReplaceSoundEventBase GetSoundEventByID (int id, ESoundEventType soundType)
References m_SoundEventReplaceMaps.
Referenced by PlayReplaceSound().
GetSoundEventID()
int GetSoundEventID (int anim_id, ESoundEventType soundType)
References ReplaceSoundEventBase::GetSoundEventID(), and m_SoundEventReplaceMaps.
PlayReplaceSound()
bool PlayReplaceSound (int soundEventID, ESoundEventType soundType, int flags)
References GetSoundEventByID(), ReplaceSoundEventBase::Init(), m_Player, and ReplaceSoundEventBase::Play().
RegisterEvent()
protected void RegisterEvent (ReplaceSoundEventBase soundEvent)
References ReplaceSoundEventBase::GetSoundAnimEventClassID(), ReplaceSoundEventBase::GetSoundEventType(), and m_SoundEventReplaceMaps.
ReplaceSoundEventHandler()
void ReplaceSoundEventHandler (PlayerBase player)
References CleanHandsPrimarySoundEvent(), CleanHandsSecondarySoundEvent, DigPrimarySoundEvent(), DigSecondarySoundEvent, m_Player, and RegisterEvent().
Referenced by ManBase::OnPlayerLoaded().
Variable Documentation
CLEANHANDS_PRIMARY
enum ESoundEventType CLEANHANDS_PRIMARY = 1
DIG_PRIMARY
enum ESoundEventType DIG_PRIMARY = 1
DIG_SECONDARY
enum ESoundEventType DIG_SECONDARY = 1
int
enum ESoundEventType int = 1
m_Player
protected PlayerBase m_Player
m_SoundEventReplaceMaps
enum ESoundEventType m_SoundEventReplaceMaps = {}
Referenced by GetSoundEventByID(), GetSoundEventID(), and RegisterEvent().
m_UpdateTimer
protected ref Timer m_UpdateTimer