DayZ Scripts: HandStartAction Class Reference
HandStartAction Class Reference
simple class starting animation action specified by m_action and m_actionType
Private Member Functions
void HandForceSwapingAnimated_Show (Man player=null, HandStateBase parent=null, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
void HandStartHidingAnimated (Man player=null, HandStateBase parent=null, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
void HandTakingAnimated_Show (Man player=null, HandStateBase parent=null, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override void OnEntry (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnExit (HandEventBase e)
override bool IsWaitingForActionFinish ()
Private Attributes
ref InventoryLocation m_Src1 = null
ref InventoryLocation m_Src2 = null
ref InventoryLocation m_Dst1 = null
ref InventoryLocation m_Dst2 = null
ref InventoryLocation m_Dst
ref InventoryLocation m_Src
Detailed Description
simple class starting animation action specified by m_action and m_actionType
Member Function Documentation
HandForceSwapingAnimated_Show()
void HandForceSwapingAnimated_Show (Man player = null, HandStateBase parent = null, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
HandStartHidingAnimated()
void HandStartHidingAnimated (Man player = null, HandStateBase parent = null, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
HandTakingAnimated_Show()
void HandTakingAnimated_Show (Man player = null, HandStateBase parent = null, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
References m_Src.
IsWaitingForActionFinish() [1/4]
override bool IsWaitingForActionFinish () inline private
IsWaitingForActionFinish() [2/4]
override bool IsWaitingForActionFinish () inline private
IsWaitingForActionFinish() [3/4]
override bool IsWaitingForActionFinish () inline private
IsWaitingForActionFinish() [4/4]
override bool IsWaitingForActionFinish () inline private
OnAbort() [1/4]
override void OnAbort (HandEventBase e) inline private
OnAbort() [2/4]
override void OnAbort (HandEventBase e) inline private
OnAbort() [3/4]
override void OnAbort (HandEventBase e) inline private
OnAbort() [4/4]
override void OnAbort (HandEventBase e) inline private
References m_Src.
OnEntry() [1/4]
override void OnEntry (HandEventBase e) inline private
TODO(kumarjac): THIS IS WHAT IS BEING CALLED FOR SOME REASON!!!!!
References Error(), and GameInventory::LocationSwap().
OnEntry() [2/4]
override void OnEntry (HandEventBase e) inline private
OnEntry() [3/4]
override void OnEntry (HandEventBase e) inline private
References Error(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and GameInventory::LocationSyncMoveEntity().
OnEntry() [4/4]
override void OnEntry (HandEventBase e) inline private
References Error(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), InventoryLocation::IsValid(), GameInventory::LocationSyncMoveEntity(), and m_Src.
OnExit() [1/4]
override void OnExit (HandEventBase e) inline private
OnExit() [2/4]
override void OnExit (HandEventBase e) inline private
OnExit() [3/4]
override void OnExit (HandEventBase e) inline private
OnExit() [4/4]
override void OnExit (HandEventBase e) inline private
References m_Src.
Field Documentation
m_Dst
ref InventoryLocation m_Dst private
m_Dst1
ref InventoryLocation m_Dst1 = null private
m_Dst2
ref InventoryLocation m_Dst2 = null private
m_Src
ref InventoryLocation m_Src private
m_Src1
ref InventoryLocation m_Src1 = null private
m_Src2
ref InventoryLocation m_Src2 = null private
The documentation for this class was generated from the following files:
P:/scripts/3_Game/Systems/Inventory/HandAnimatedForceSwapping.c
P:/scripts/3_Game/Systems/Inventory/HandAnimatedMovingToAtt.c
P:/scripts/3_Game/Systems/Inventory/HandAnimatedTakingFromAtt.c