DayZ Scripts: HeadGear_Base Class Reference
HeadGear_Base Class Reference
hard helmet base
Private Member Functions
override void SetActions ()
override void SetActions ()
override void SetActions ()
void ~BurlapSackCover ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnWasAttached (EntityAI parent, int slot_id)
override bool CanPutInCargo (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
void OnRemovedFromHead (PlayerBase player)
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId)
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId)
override void SetActions ()
override void SetActions ()
override protected void InitGlobalExclusionValues ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId)
override void SetActions ()
override void SetActions ()
Private Attributes
PlayerBase m_Player
Detailed Description
hard helmet base
Constructor & Destructor Documentation
~BurlapSackCover()
void ~BurlapSackCover () inline private
References m_Player, and OnRemovedFromHead().
Member Function Documentation
CanDetachAttachment()
override bool CanDetachAttachment (EntityAI parent) inline private
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
References ECE_PLACE_ON_SURFACE, GetGame(), and RF_DEFAULT.
GetAttachmentExclusionInitSlotValue() [1/4]
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId) inline private
GetAttachmentExclusionInitSlotValue() [2/4]
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId) inline private
GetAttachmentExclusionInitSlotValue() [3/4]
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId) inline private
GetAttachmentExclusionInitSlotValue() [4/4]
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId) inline private
InitGlobalExclusionValues()
override protected void InitGlobalExclusionValues () inline private
OnRemovedFromHead()
void OnRemovedFromHead (PlayerBase player) inline private
Referenced by ~BurlapSackCover().
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
References Class::CastTo(), GetGame(), CGame::GetMission(), Mission::HideInventory(), m_Player, and MENU_INVENTORY.
SetActions() [1/19]
override void SetActions () inline private
References AddAction().
SetActions() [2/19]
override void SetActions () inline private
References AddAction().
SetActions() [3/19]
override void SetActions () inline private
References AddAction().
SetActions() [4/19]
override void SetActions () inline private
References AddAction().
SetActions() [5/19]
override void SetActions () inline private
References AddAction().
SetActions() [6/19]
override void SetActions () inline private
References AddAction().
SetActions() [7/19]
override void SetActions () inline private
References AddAction().
SetActions() [8/19]
override void SetActions () inline private
References AddAction().
SetActions() [9/19]
override void SetActions () inline private
References AddAction().
SetActions() [10/19]
override void SetActions () inline private
References AddAction().
SetActions() [11/19]
override void SetActions () inline private
References AddAction().
SetActions() [12/19]
override void SetActions () inline private
References AddAction().
SetActions() [13/19]
override void SetActions () inline private
References AddAction().
SetActions() [14/19]
override void SetActions () inline private
References AddAction().
SetActions() [15/19]
override void SetActions () inline private
References AddAction().
SetActions() [16/19]
override void SetActions () inline private
References AddAction().
SetActions() [17/19]
override void SetActions () inline private
References AddAction().
SetActions() [18/19]
override void SetActions () inline private
References AddAction().
SetActions() [19/19]
override void SetActions () inline private
References AddAction().
Field Documentation
m_Player
PlayerBase m_Player private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/Clothing/BaseballCap_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BurlapSackCover.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BeanieHat_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BoonieHat_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Chainmail_Coif.c
P:/scripts/4_World/Entities/ItemBase/Clothing/FlatCap_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HeadCover_improvised.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Headdress_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MedicalScrubsHat_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MorozkoHat.c
P:/scripts/4_World/Entities/ItemBase/Clothing/OKZKCap_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PetushokHat_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PilotkaCap.c
P:/scripts/4_World/Entities/ItemBase/Clothing/PrisonerCap.c
P:/scripts/4_World/Entities/ItemBase/Clothing/RadarCap_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/SantasHat.c
P:/scripts/4_World/Entities/ItemBase/Clothing/SherpaHat_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/TankerHelmet.c
P:/scripts/4_World/Entities/ItemBase/Clothing/Ushanka_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/WinterCoif_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/WitchHat.c
P:/scripts/4_World/Entities/ItemBase/Clothing/ZmijovkaCap_ColorBase.c