DayZ Scripts: RadialProgressBar Class Reference
RadialProgressBar Class Reference
Private Member Functions
void RadialProgressBar ()
void ~RadialProgressBar ()
void SetProgress (float progress)
protected void Update (float tDelta)
protected void UpdateChild (Widget child, int index)
void OnWidgetScriptInit (Widget w)
Private Attributes
reference float speed
reference float start_rotation
protected string m_BarHider
protected string m_BarPart
protected Widget m_Root
protected ref AnimatorTimer m_Anim
protected float x
protected float y
protected float z
protected float rotation = 0
protected int stage = 0
Detailed Description
Definition at line 2 of file RadialProgressBar.c.
Constructor & Destructor Documentation
RadialProgressBar()
void RadialProgressBar () inline private
Definition at line 16 of file RadialProgressBar.c.
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), m_Anim, and Update().
~RadialProgressBar()
void ~RadialProgressBar () inline private
Definition at line 23 of file RadialProgressBar.c.
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Remove(), and Update().
Member Function Documentation
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w) inline private
Definition at line 98 of file RadialProgressBar.c.
References AnimatorTimer::AnimateLoop(), m_Anim, m_BarHider, m_BarPart, m_Root, and speed.
SetProgress()
void SetProgress (float progress) inline private
Definition at line 28 of file RadialProgressBar.c.
References rotation, and stage.
Update()
protected void Update (float tDelta) inline private
Definition at line 38 of file RadialProgressBar.c.
References m_Anim, m_Root, AnimatorTimer::Tick(), and UpdateChild().
UpdateChild()
protected void UpdateChild (Widget child, int index) inline private
Definition at line 53 of file RadialProgressBar.c.
References AnimatorTimer::GetTargetValue(), m_Anim, m_BarHider, m_BarPart, Math::RAD2DEG, rotation, stage, and start_rotation.
Referenced by Update().
Field Documentation
m_Anim
protected ref AnimatorTimer m_Anim private
Definition at line 10 of file RadialProgressBar.c.
Referenced by OnWidgetScriptInit(), RadialProgressBar(), Update(), and UpdateChild().
m_BarHider
protected string m_BarHider private
Definition at line 7 of file RadialProgressBar.c.
Referenced by OnWidgetScriptInit(), and UpdateChild().
m_BarPart
protected string m_BarPart private
Definition at line 8 of file RadialProgressBar.c.
Referenced by OnWidgetScriptInit(), and UpdateChild().
m_Root
protected Widget m_Root private
Definition at line 9 of file RadialProgressBar.c.
Referenced by OnWidgetScriptInit(), and Update().
rotation
protected float rotation = 0 private
Definition at line 12 of file RadialProgressBar.c.
Referenced by SetProgress(), and UpdateChild().
speed
reference float speed private
Definition at line 4 of file RadialProgressBar.c.
Referenced by OnWidgetScriptInit().
stage
protected int stage = 0 private
Definition at line 13 of file RadialProgressBar.c.
Referenced by SetProgress(), and UpdateChild().
start_rotation
reference float start_rotation private
Definition at line 5 of file RadialProgressBar.c.
Referenced by UpdateChild().
x
protected float x private
Definition at line 11 of file RadialProgressBar.c.
y
protected float y private
Definition at line 11 of file RadialProgressBar.c.
z
protected float z private
Definition at line 11 of file RadialProgressBar.c.
The documentation for this class was generated from the following file:
P:/scripts/3_Game/GUI/Effects/RadialProgressBar.c