DayZ Scripts: Dispatcher Class Reference
Dispatcher Class Reference
Private Member Functions
Param CallMethod (CallID call_id, Param params)
private void SendLogAtClient (Param1< string > p)
private void ScriptConsoleAddPrint (Param1< string > p)
private void ScriptConsoleHistoryBack ()
private void ScriptConsoleHistoryForward ()
private Param ScriptConsoleGetSelectedItem ()
private void SceneEditorCommand (Param params)
private void MissionGameplayHideInventory ()
override Param CallMethod (CallID call_id, Param params)
Detailed Description
Definition at line 13 of file Dispatcher.c.
Member Function Documentation
CallMethod() [1/2]
Param CallMethod (CallID call_id, Param params) inline private
Definition at line 15 of file Dispatcher.c.
Referenced by CallMethod(), PluginDayzPlayerDebug_Weapons::OnClick(), and Debug::SaveLog().
CallMethod() [2/2]
override Param CallMethod (CallID call_id, Param params) inline private
Definition at line 75 of file DispatcherCaller.c.
References CALL_ID_HIDE_INVENTORY, CALL_ID_SCENE_EDITOR_COMMAND, CALL_ID_SCR_CNSL_ADD_PRINT, CALL_ID_SCR_CNSL_GETSELECTEDITEM, CALL_ID_SCR_CNSL_HISTORY_BACK, CALL_ID_SCR_CNSL_HISTORY_NEXT, CALL_ID_SEND_LOG, MissionGameplayHideInventory(), SceneEditorCommand(), ScriptConsoleAddPrint(), ScriptConsoleHistoryBack(), ScriptConsoleHistoryForward(), and SendLogAtClient().
MissionGameplayHideInventory()
private void MissionGameplayHideInventory () inline private
Definition at line 66 of file DispatcherCaller.c.
References GetGame(), Mission::HideInventory(), and mission.
Referenced by CallMethod().
SceneEditorCommand()
private void SceneEditorCommand (Param params) inline private
Definition at line 56 of file DispatcherCaller.c.
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), MENU_SCENE_EDITOR, and UIScriptedMenu::SceneEditorCommand().
Referenced by CallMethod().
ScriptConsoleAddPrint()
private void ScriptConsoleAddPrint (Param1< string > p) inline private
Definition at line 13 of file DispatcherCaller.c.
References UIScriptedMenu::Add(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and MENU_SCRIPTCONSOLE.
Referenced by CallMethod().
ScriptConsoleGetSelectedItem()
private Param ScriptConsoleGetSelectedItem () inline private
Definition at line 43 of file DispatcherCaller.c.
References UIScriptedMenu::GetCurrentItemName(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and MENU_SCRIPTCONSOLE.
ScriptConsoleHistoryBack()
private void ScriptConsoleHistoryBack () inline private
Definition at line 23 of file DispatcherCaller.c.
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), UIScriptedMenu::HistoryBack(), and MENU_SCRIPTCONSOLE.
Referenced by CallMethod().
ScriptConsoleHistoryForward()
private void ScriptConsoleHistoryForward () inline private
Definition at line 33 of file DispatcherCaller.c.
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), UIScriptedMenu::HistoryForward(), and MENU_SCRIPTCONSOLE.
Referenced by CallMethod().
SendLogAtClient()
private void SendLogAtClient (Param1< string > p) inline private
Definition at line 3 of file DispatcherCaller.c.
References GetPlugin().
Referenced by CallMethod().
The documentation for this class was generated from the following files:
P:/scripts/3_Game/tools/Dispatcher.c
P:/scripts/5_Mission/mission/DispatcherCaller.c