DayZ Scripts: P:/scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCamera3rdPerson.c File Reference
DayZPlayerCamera3rdPerson.c File Reference
Data Structures
class DayZPlayerCameraBase
this is main camera class
class DayZPlayerCamera3rdPersonErc
class DayZPlayerCamera3rdPersonErcRaised
class DayZPlayerCamera3rdPersonCrouch
class DayZPlayerCamera3rdPersonProneBase
Functions
class DayZPlayerCamera3rdPerson extends DayZPlayerCameraBase DayZPlayerCamera3rdPersonErc (DayZPlayer pPlayer, HumanInputController pInput)
void DayZPlayerCamera3rdPerson (DayZPlayer pPlayer, HumanInputController pInput)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override vector GetBaseAngles ()
override vector GetAdditiveAngles ()
override string GetCameraName ()
class DayZPlayerCamera3rdPersonJump extends DayZPlayerCamera3rdPersonErc DayZPlayerCamera3rdPersonClimb (DayZPlayer pPlayer, HumanInputController pInput)
void DayZPlayerCamera3rdPersonJump (DayZPlayer pPlayer, HumanInputController pInput)
class DayZPlayerCamera3rdPersonErcSpr extends DayZPlayerCamera3rdPersonErc DayZPlayerCamera3rdPersonErcRaised (DayZPlayer pPlayer, HumanInputController pInput)
void DayZPlayerCamera3rdPersonErcSpr (DayZPlayer pPlayer, HumanInputController pInput)
override bool IsCamera3rdRaised ()
void DayZPlayerCamera3rdPersonCrouch (DayZPlayer pPlayer, HumanInputController pInput)
float UpdateLRAngleLookAt (float pMin, float pMax, float pDt)
class DayZPlayerCamera3rdPersonProne extends DayZPlayerCamera3rdPersonProneBase DayZPlayerCamera3rdPersonProneRaised (DayZPlayer pPlayer, HumanInputController pInput)
void DayZPlayerCamera3rdPersonProne (DayZPlayer pPlayer, HumanInputController pInput)
Variables
static const float CONST_UD_MIN = -85.0
down limit
static const float CONST_UD_MAX = 85.0
up limit
static const float CONST_LR_MIN = -160.0
down limit
static const float CONST_LR_MAX = 160.0
up limit
protected int m_iBoneIndex = -1
runtime config
protected vector m_CameraOffsetMS
model space offset
protected vector m_CameraOffsetLS
local space offset
protected float m_fDistance
distance from start
protected float m_fShoulderWidth
shoulder camera widths
protected bool m_bShoulderInLS
true - shoulder is in local space
protected float m_fRoll
camera roll (deprecated)
protected float m_fLeanDistance
shift on leaning
protected float m_fUpDownAngle
runtime values
protected float m_fUpDownAngleAdd
up down angle in rad
protected float m_fLeftRightAngle
left right angle in rad (in freelook only)
protected float m_fLeftRightAngleAdd
left right angle in rad (in freelook only)
protected float m_fCameraLRShoulder
shoulder offsets
protected float m_fCameraLRShoulderVel [1]
protected float m_fPredictCollisionRadius
collision prediction
ref HumanMovementState m_MovementState = new HumanMovementState()
movement state
float m_fDelay
runtime config
float m_fDamping
float m_fDelayTimer
runtime values
float m_fJumpStartY
float m_fJumpOffset
float m_jumpOffsetVelocity [1]
protected int m_iPelvisBone
protected float m_fTime
class DayZPlayerCamera3rdPersonErcRaisedMelee extends DayZPlayerCamera3rdPersonErcRaised CONST_CAMERAMOVEMENTHEIGH = 0.4
protected float m_fCameraHeight
protected float m_fCameraHeightVel [1]
class DayZPlayerCamera3rdPersonCrouchRaised extends DayZPlayerCamera3rdPersonCrouch m_LookAtLRAngle
Function Documentation
DayZPlayerCamera3rdPerson()
void DayZPlayerCamera3rdPerson (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 177 of file DayZPlayerCamera3rdPerson.c.
Referenced by Hologram::GetProjectionEntityPosition().
DayZPlayerCamera3rdPersonClimb()
class DayZPlayerCamera3rdPersonJump extends DayZPlayerCamera3rdPersonErc DayZPlayerCamera3rdPersonClimb (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 186 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameras::RegisterCameras().
DayZPlayerCamera3rdPersonCrouch()
void DayZPlayerCamera3rdPersonCrouch (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 383 of file DayZPlayerCamera3rdPerson.c.
References m_CameraOffsetLS, m_CameraOffsetMS, m_fDistance, and m_fShoulderWidth.
DayZPlayerCamera3rdPersonErc()
class DayZPlayerCamera3rdPerson extends DayZPlayerCameraBase DayZPlayerCamera3rdPersonErc (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 4 of file DayZPlayerCamera3rdPerson.c.
References CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, and CONST_UD_MIN.
DayZPlayerCamera3rdPersonErcRaised()
class DayZPlayerCamera3rdPersonErcSpr extends DayZPlayerCamera3rdPersonErc DayZPlayerCamera3rdPersonErcRaised (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 254 of file DayZPlayerCamera3rdPerson.c.
DayZPlayerCamera3rdPersonErcSpr()
void DayZPlayerCamera3rdPersonErcSpr (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 309 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameras::RegisterCameras().
DayZPlayerCamera3rdPersonJump()
void DayZPlayerCamera3rdPersonJump (DayZPlayer pPlayer, HumanInputController pInput)
runtime config
runtime values
Definition at line 242 of file DayZPlayerCamera3rdPerson.c.
References m_CameraOffsetMS, m_fDistance, m_fPredictCollisionRadius, and m_iBoneIndex.
Referenced by DayZPlayerCameras::RegisterCameras().
DayZPlayerCamera3rdPersonProne()
void DayZPlayerCamera3rdPersonProne (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 551 of file DayZPlayerCamera3rdPerson.c.
References m_CameraOffsetLS, m_CameraOffsetMS, m_fDistance, m_fShoulderWidth, and m_iBoneIndex.
Referenced by DayZPlayerCameras::RegisterCameras().
DayZPlayerCamera3rdPersonProneRaised()
class DayZPlayerCamera3rdPersonProne extends DayZPlayerCamera3rdPersonProneBase DayZPlayerCamera3rdPersonProneRaised (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 531 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameras::RegisterCameras().
GetAdditiveAngles()
override vector GetAdditiveAngles ()
Definition at line 285 of file DayZPlayerCamera3rdPerson.c.
GetBaseAngles()
override vector GetBaseAngles ()
Definition at line 276 of file DayZPlayerCamera3rdPerson.c.
GetCameraName()
override string GetCameraName ()
Definition at line 294 of file DayZPlayerCamera3rdPerson.c.
IsCamera3rdRaised()
override bool IsCamera3rdRaised ()
Definition at line 348 of file DayZPlayerCamera3rdPerson.c.
OnActivate()
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
Definition at line 197 of file DayZPlayerCamera3rdPerson.c.
OnUpdate()
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
update angles from input
base bone pos
apply shoulder dist
store distance
basically -> transform up vector (0,1,0) and read x coord -> and set is as roll
prev update
movement height
prev update
update angles from input
this is actually negative to yaw
base bone pos
apply shoulder dist
store distance
Definition at line 214 of file DayZPlayerCamera3rdPerson.c.
UpdateLRAngleLookAt()
float UpdateLRAngleLookAt (float pMin, float pMax, float pDt)
lr angle
Definition at line 442 of file DayZPlayerCamera3rdPerson.c.
References HumanInputController::CameraIsFreeLook(), HumanInputController::GetAimChange(), Limit(), m_bForceFreeLook, m_fLRAngleVel, m_LookAtLRAngle, m_pInput, Math::RAD2DEG, and Math::SmoothCD().
Variable Documentation
CONST_CAMERAMOVEMENTHEIGH
class DayZPlayerCamera3rdPersonErcRaisedMelee extends DayZPlayerCamera3rdPersonErcRaised CONST_CAMERAMOVEMENTHEIGH = 0.4
CONST_LR_MAX
const float CONST_LR_MAX = 160.0 static
up limit
Definition at line 175 of file DayZPlayerCamera3rdPerson.c.
CONST_LR_MIN
const float CONST_LR_MIN = -160.0 static
down limit
Definition at line 174 of file DayZPlayerCamera3rdPerson.c.
CONST_UD_MAX
const float CONST_UD_MAX = 85.0 static
up limit
Definition at line 172 of file DayZPlayerCamera3rdPerson.c.
CONST_UD_MIN
const float CONST_UD_MIN = -85.0 static
down limit
Definition at line 171 of file DayZPlayerCamera3rdPerson.c.
m_bShoulderInLS
protected bool m_bShoulderInLS
true - shoulder is in local space
Definition at line 305 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameraBase::OnUpdate().
m_CameraOffsetLS
protected vector m_CameraOffsetLS
local space offset
Definition at line 302 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonCrouch(), DayZPlayerCamera3rdPersonCrouch::DayZPlayerCamera3rdPersonCrouchRaised(), DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPersonErcSpr(), DayZPlayerCamera3rdPersonProneBase::DayZPlayerCamera3rdPersonProne(), and DayZPlayerCamera3rdPersonProne().
m_CameraOffsetMS
protected vector m_CameraOffsetMS
model space offset
Definition at line 301 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonCrouch(), DayZPlayerCamera3rdPersonCrouch::DayZPlayerCamera3rdPersonCrouchRaised(), DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPersonErcSpr(), DayZPlayerCamera3rdPersonJump(), DayZPlayerCamera3rdPersonProneBase::DayZPlayerCamera3rdPersonProne(), DayZPlayerCamera3rdPersonProne(), and DayZPlayerCamera3rdPersonVehicle().
m_fCameraHeight
protected float m_fCameraHeight
Definition at line 408 of file DayZPlayerCamera3rdPerson.c.
m_fCameraHeightVel
protected float m_fCameraHeightVel[1]
Definition at line 409 of file DayZPlayerCamera3rdPerson.c.
m_fCameraLRShoulder
protected float m_fCameraLRShoulder
shoulder offsets
Definition at line 317 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameraBase::DayZPlayerCamera3rdPerson(), and DayZPlayerCameraBase::OnUpdate().
m_fCameraLRShoulderVel
protected float m_fCameraLRShoulderVel[1]
Definition at line 318 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameraBase::DayZPlayerCamera3rdPerson(), and DayZPlayerCameraBase::OnUpdate().
m_fDamping
float m_fDamping
Definition at line 281 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPersonJump().
m_fDelay
float m_fDelay
runtime config
Definition at line 280 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPersonJump(), and DayZPlayerCamera3rdPersonErc::OnUpdate().
m_fDelayTimer
float m_fDelayTimer
runtime values
Definition at line 284 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonErc::OnUpdate().
m_fDistance
protected float m_fDistance
distance from start
Definition at line 303 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonCrouch().
m_fJumpOffset
float m_fJumpOffset
Definition at line 286 of file DayZPlayerCamera3rdPerson.c.
m_fJumpStartY
float m_fJumpStartY
Definition at line 285 of file DayZPlayerCamera3rdPerson.c.
m_fLeanDistance
protected float m_fLeanDistance
shift on leaning
Definition at line 307 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCameraBase::DayZPlayerCamera3rdPerson().
m_fLeftRightAngle
protected float m_fLeftRightAngle
left right angle in rad (in freelook only)
Definition at line 313 of file DayZPlayerCamera3rdPerson.c.
m_fLeftRightAngleAdd
protected float m_fLeftRightAngleAdd
left right angle in rad (in freelook only)
Definition at line 314 of file DayZPlayerCamera3rdPerson.c.
m_fPredictCollisionRadius
protected float m_fPredictCollisionRadius
collision prediction
Definition at line 321 of file DayZPlayerCamera3rdPerson.c.
m_fRoll
protected float m_fRoll
camera roll (deprecated)
Definition at line 306 of file DayZPlayerCamera3rdPerson.c.
m_fShoulderWidth
protected float m_fShoulderWidth
shoulder camera widths
Definition at line 304 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonCrouch(), DayZPlayerCamera3rdPersonCrouch::DayZPlayerCamera3rdPersonCrouchRaised(), DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPersonErcSpr(), DayZPlayerCamera3rdPersonProneBase::DayZPlayerCamera3rdPersonProne(), DayZPlayerCamera3rdPersonProne(), and DayZPlayerCameraBase::OnUpdate().
m_fTime
protected float m_fTime
Definition at line 351 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPersonErcSpr(), and DayZPlayerCamera3rdPersonErc::OnUpdate().
m_fUpDownAngle
protected float m_fUpDownAngle
runtime values
up down angle in rad
Definition at line 311 of file DayZPlayerCamera3rdPerson.c.
m_fUpDownAngleAdd
protected float m_fUpDownAngleAdd
up down angle in rad
Definition at line 312 of file DayZPlayerCamera3rdPerson.c.
m_iBoneIndex
protected int m_iBoneIndex = -1
runtime config
main bone
Definition at line 300 of file DayZPlayerCamera3rdPerson.c.
m_iPelvisBone
protected int m_iPelvisBone
Definition at line 350 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPersonErcSpr().
m_jumpOffsetVelocity
float m_jumpOffsetVelocity[1]
Definition at line 287 of file DayZPlayerCamera3rdPerson.c.
m_LookAtLRAngle
class DayZPlayerCamera3rdPersonCrouchRaised extends DayZPlayerCamera3rdPersonCrouch m_LookAtLRAngle
Referenced by UpdateLRAngleLookAt().
m_MovementState
ref HumanMovementState m_MovementState = new HumanMovementState()
movement state
Definition at line 324 of file DayZPlayerCamera3rdPerson.c.
Referenced by DayZPlayer::AimingModel(), ManBase::BrokenLegForceProne(), ManBase::BrokenLegWalkShock(), DayZPlayer::CameraHandler(), DayZPlayer::CanClimb(), DayZPlayer::CanJump(), DayZPlayer::CommandHandler(), ManBase::CommandHandler(), InjurySoundHandlerBase::DetermineInjuryZone(), DayZPlayer::EvaluateDamageHitAnimation(), ManBase::GetFeetDamageMoveModifier(), DayZPlayer::HandleADS(), DayZPlayer::HandleDamageHit(), DayZPlayer::HandleView(), DayZPlayer::HandleWeapons(), DayZPlayer::HeadingModel(), ManBase::HeadingModel(), ManBase::IsClimbing(), DayZPlayer::IsClimbingLadder(), ManBase::IsFalling(), DayZPlayer::IsFireWeaponRaised(), ManBase::IsInProne(), ManBase::IsInRasedProne(), DayZPlayer::IsInVehicle(), ManBase::IsLeaning(), ManBase::IsSprinting(), DayZPlayer::IsSwimming(), ManBase::OnCommandHandlerTick(), DayZPlayer::OnMovementChanged(), DayZPlayerCameraBase::OnUpdate(), and ManBase::UpdateBrokenLegs().