DayZ Scripts: UndergroundBunkerHandlerClient Class Reference
UndergroundBunkerHandlerClient Class Reference
Private Member Functions
override protected bool CalculateEyeAcco (float timeSlice)
override protected void CalculateEyeAccoTarget ()
override protected void ProcessLighting (float timeSlice)
override protected void ApplyEyeAcco ()
override protected void ProcessSound (float timeSlice)
Private Attributes
protected bool m_IsDoorOpening
protected float m_AnimPhasePrev
Member Function Documentation
ApplyEyeAcco()
override protected void ApplyEyeAcco () inline private
References m_LightingLerp.
CalculateEyeAcco()
override protected bool CalculateEyeAcco (float timeSlice) inline private
References Math::Clamp(), Easing::EaseInOutCubic(), Easing::EaseOutQuad(), Math::InverseLerp(), m_EyeAcco, m_EyeAccoTarget, and m_IsDoorOpening.
CalculateEyeAccoTarget()
override protected void CalculateEyeAccoTarget () inline private
References m_AnimPhasePrev, m_EyeAccoTarget, m_IsDoorOpening, UndergroundBunkerTrigger::m_LinkedDoorSelection, and m_TransitionalTrigger.
ProcessLighting()
override protected void ProcessLighting (float timeSlice) inline private
ProcessSound()
override protected void ProcessSound (float timeSlice) inline private
References GetGame(), CGame::GetWorld(), m_EyeAcco, and World::SetExplicitVolumeFactor_EnvSounds2D().
Field Documentation
m_AnimPhasePrev
protected float m_AnimPhasePrev private
Referenced by CalculateEyeAccoTarget().
m_IsDoorOpening
protected bool m_IsDoorOpening private
Referenced by CalculateEyeAcco(), and CalculateEyeAccoTarget().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UndergroundBunkerHandlerClient.c