DayZ Scripts: ImpactMaterials Class Reference
ImpactMaterials Class Reference
Static Private Attributes
static ref map< string, typename > m_ImpactEffect
static int m_LastRegisteredMaterial = 0
static ref map< string, int > m_IgnoredAmmo
Map of ammo which will not spawn any impact effect.
static int m_LastRegisteredIgnoredAmmo = 0
Surface effects
Register all hit materials here! When modding, these can be unregistered with 'UnregisterSurface' if so desired
static int PLASTIC = RegisterSurface("Hit_Plastic")
static int SAND = RegisterSurface("Hit_Sand")
static int TEXTILE = RegisterSurface("Hit_Textile")
static int CONCRETE = RegisterSurface("Hit_Concrete")
static int GRAVEL = RegisterSurface("Hit_Gravel")
static int DIRT = RegisterSurface("Hit_Dirt")
static int FOLIAGE = RegisterSurface("Hit_Foliage")
static int GRASS = RegisterSurface("Hit_Grass")
static int WOOD = RegisterSurface("Hit_Wood")
static int METAL = RegisterSurface("Hit_Metal")
static int GLASS = RegisterSurface("Hit_Glass")
static int GLASS_THIN = RegisterSurface("Hit_Glass_Thin")
static int WATER = RegisterSurface("Hit_Water")
static int RUBBER = RegisterSurface("Hit_Rubber")
static int PLASTER = RegisterSurface("Hit_Plaster")
static int MEATBONES = RegisterSurface("Hit_MeatBones")
static int MEATBONES_SHOVEL = RegisterSurface("Hit_MeatBones_MeleeShovel")
static int MEATBONES_PIPEWRENCH = RegisterSurface("Hit_MeatBones_MeleePipeWrench")
static int MEATBONES_WRENCH = RegisterSurface("Hit_MeatBones_MeleeWrench")
static int MEATBONES_FIST = RegisterSurface("Hit_MeatBones_MeleeFist")
static int UNDEFINED = RegisterSurface("Hit_Undefined")
static int ERROR_NO_MATERIAL = RegisterSurface("Hit_ErrorNoMaterial")
Ignored ammo
Register ammo which will not spawn impact effects here When modding, these can be unregistered with 'UnregisterIgnoredAmmo' if so desired
static int FIST = RegisterIgnoredAmmo("MeleeFist")
static int FIST_HEAVY = RegisterIgnoredAmmo("MeleeFist_Heavy")
static int SOFT = RegisterIgnoredAmmo("MeleeSoft")
static int SOFT_HEAVY = RegisterIgnoredAmmo("MeleeSoft_Heavy")
static int DUMMY = RegisterIgnoredAmmo("Dummy_Light")
static int DUMMY_HEAVY = RegisterIgnoredAmmo("Dummy_Heavy")
static int RegisterSurface (string surface)
static bool UnregisterSurface (string surface)
static int RegisterIgnoredAmmo (string ammo)
static bool UnregisterIgnoredAmmo (string ammo)
static GetImpactEffect (string surface, string ammoType)
static void EvaluateImpactEffectEx (ImpactEffectsData pData)
static void EvaluateImpactEffect (Object directHit, int componentIndex, string surface, vector pos, int impact_type, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, bool deflected, string ammoType, bool isWater)
Member Function Documentation
EvaluateImpactEffect()
static void EvaluateImpactEffect (Object directHit, int componentIndex, string surface, vector pos, int impact_type, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, bool deflected, string ammoType, bool isWater) inline static private
References ErrorEx, EffBulletImpactBase::EvaluateEffect(), GetImpactEffect(), m_IgnoredAmmo, SEffectManager::PlayInWorld(), RegisterSurface(), Spawn(), and string::ToType().
Referenced by EvaluateImpactEffectEx().
EvaluateImpactEffectEx()
static void EvaluateImpactEffectEx (ImpactEffectsData pData) inline static private
References EvaluateImpactEffect().
Referenced by CGame::CloseCombatEffects(), and CGame::FirearmEffects().
GetImpactEffect()
static GetImpactEffect (string surface, string ammoType) inline static private
References m_ImpactEffect.
Referenced by EvaluateImpactEffect().
RegisterIgnoredAmmo()
static int RegisterIgnoredAmmo (string ammo) inline static private
References m_IgnoredAmmo, and m_LastRegisteredIgnoredAmmo.
RegisterSurface()
static int RegisterSurface (string surface) inline static private
References m_ImpactEffect, m_LastRegisteredMaterial, and string::ToType().
Referenced by EvaluateImpactEffect().
UnregisterIgnoredAmmo()
static bool UnregisterIgnoredAmmo (string ammo) inline static private
References m_IgnoredAmmo.
UnregisterSurface()
static bool UnregisterSurface (string surface) inline static private
References m_ImpactEffect.
Field Documentation
CONCRETE
int CONCRETE = RegisterSurface("Hit_Concrete") static private
DIRT
int DIRT = RegisterSurface("Hit_Dirt") static private
DUMMY
int DUMMY = RegisterIgnoredAmmo("Dummy_Light") static private
DUMMY_HEAVY
int DUMMY_HEAVY = RegisterIgnoredAmmo("Dummy_Heavy") static private
ERROR_NO_MATERIAL
int ERROR_NO_MATERIAL = RegisterSurface("Hit_ErrorNoMaterial") static private
FIST
int FIST = RegisterIgnoredAmmo("MeleeFist") static private
FIST_HEAVY
int FIST_HEAVY = RegisterIgnoredAmmo("MeleeFist_Heavy") static private
FOLIAGE
int FOLIAGE = RegisterSurface("Hit_Foliage") static private
GLASS
int GLASS = RegisterSurface("Hit_Glass") static private
GLASS_THIN
int GLASS_THIN = RegisterSurface("Hit_Glass_Thin") static private
GRASS
int GRASS = RegisterSurface("Hit_Grass") static private
GRAVEL
int GRAVEL = RegisterSurface("Hit_Gravel") static private
m_IgnoredAmmo
ref map<string, int> m_IgnoredAmmo static private
Map of ammo which will not spawn any impact effect.
Referenced by EvaluateImpactEffect(), RegisterIgnoredAmmo(), and UnregisterIgnoredAmmo().
m_ImpactEffect
ref map<string, typename> m_ImpactEffect static private
Referenced by GetImpactEffect(), RegisterSurface(), and UnregisterSurface().
m_LastRegisteredIgnoredAmmo
int m_LastRegisteredIgnoredAmmo = 0 static private
Referenced by RegisterIgnoredAmmo().
m_LastRegisteredMaterial
int m_LastRegisteredMaterial = 0 static private
Referenced by RegisterSurface().
MEATBONES
int MEATBONES = RegisterSurface("Hit_MeatBones") static private
MEATBONES_FIST
int MEATBONES_FIST = RegisterSurface("Hit_MeatBones_MeleeFist") static private
MEATBONES_PIPEWRENCH
int MEATBONES_PIPEWRENCH = RegisterSurface("Hit_MeatBones_MeleePipeWrench") static private
MEATBONES_SHOVEL
int MEATBONES_SHOVEL = RegisterSurface("Hit_MeatBones_MeleeShovel") static private
MEATBONES_WRENCH
int MEATBONES_WRENCH = RegisterSurface("Hit_MeatBones_MeleeWrench") static private
METAL
int METAL = RegisterSurface("Hit_Metal") static private
PLASTER
int PLASTER = RegisterSurface("Hit_Plaster") static private
PLASTIC
int PLASTIC = RegisterSurface("Hit_Plastic") static private
RUBBER
int RUBBER = RegisterSurface("Hit_Rubber") static private
SAND
int SAND = RegisterSurface("Hit_Sand") static private
SOFT
int SOFT = RegisterIgnoredAmmo("MeleeSoft") static private
SOFT_HEAVY
int SOFT_HEAVY = RegisterIgnoredAmmo("MeleeSoft_Heavy") static private
TEXTILE
int TEXTILE = RegisterSurface("Hit_Textile") static private
UNDEFINED
int UNDEFINED = RegisterSurface("Hit_Undefined") static private
WATER
int WATER = RegisterSurface("Hit_Water") static private
WOOD
int WOOD = RegisterSurface("Hit_Wood") static private
The documentation for this class was generated from the following file:
3_Game/ImpactEffects.c