DayZ Scripts: TotalDamageResult Class Reference
TotalDamageResult Class Reference
Private Member Functions
proto native float GetDamage (string zoneName, string healthType)
proto native float GetHighestDamage (string healthType)
Member Function Documentation
GetDamage()
proto native float GetDamage (string zoneName, string healthType) private
Referenced by DayZCreatureAI::EEHitBy(), DayZInfected::EEHitBy(), InventoryItem::EEHitBy(), ManBase::EEHitBy(), ComponentAnimalBleeding::InflictWoundDamage(), PluginBase::OnDamageEvent(), and PluginBase::PlayerHitBy().
GetHighestDamage()
proto native float GetHighestDamage (string healthType) private
Referenced by DayZPlayer::EvaluateDamageHitAnimation(), PluginBase::GetHitMessage(), and DayZPlayerSyncJunctures::SendDamageHitEx().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/DamageSystem.c