DayZ Scripts: ActionWritePaper Class Reference
ActionWritePaper Class Reference
Private Member Functions
void ActionWritePaper ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnUpdate (ActionData action_data)
override void OnEndRequest (ActionData action_data)
Private Attributes
const float TARGET_DISTANCE = 2
Detailed Description
Definition at line 37 of file ActionWritePaper.c.
Constructor & Destructor Documentation
ActionWritePaper()
void ActionWritePaper () inline private
Definition at line 41 of file ActionWritePaper.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 56 of file ActionWritePaper.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 50 of file ActionWritePaper.c.
References m_ConditionItem, and m_ConditionTarget.
OnEndRequest()
override void OnEndRequest (ActionData action_data) inline private
Definition at line 102 of file ActionWritePaper.c.
References ActionData::m_Callback.
OnStartClient()
override void OnStartClient (ActionData action_data) inline private
Definition at line 65 of file ActionWritePaper.c.
References ItemBase::GetWrittenNoteData(), WrittenNoteData::InitNoteInfo(), ActionData::m_MainItem, and ActionData::m_Target.
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
Definition at line 77 of file ActionWritePaper.c.
References ItemBase::GetWrittenNoteData(), WrittenNoteData::InitNoteInfo(), ActionData::m_MainItem, and ActionData::m_Target.
OnUpdate()
override void OnUpdate (ActionData action_data) inline private
Definition at line 89 of file ActionWritePaper.c.
References GetGame(), ActionData::m_Player, ActionData::m_State, MENU_NOTE, ActionManagerClient::RequestEndAction(), and UA_FINISHED.
Field Documentation
TARGET_DISTANCE
const float TARGET_DISTANCE = 2 private
Definition at line 39 of file ActionWritePaper.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionWritePaper.c