DayZ Scripts: LoginScreenBase Class Reference
LoginScreenBase Class Reference
Private Member Functions
void LoginTimeBase ()
void ~LoginTimeBase ()
override Widget Init ()
override bool OnClick (Widget w, int x, int y, int button)
void Show ()
void Hide ()
void SetTime (int time)
void SetStatus (string status)
void SetRespawn (bool value)
bool IsRespawn ()
override protected bool CanChangeHintPage (float timeAccu)
Private Attributes
protected TextWidget m_txtDescription
protected TextWidget m_txtLabel
protected ButtonWidget m_btnLeave
protected bool m_IsRespawn
private ref FullTimeData m_FullTime
Constructor & Destructor Documentation
~LoginTimeBase()
void ~LoginTimeBase () inline private
References g_Game.
Member Function Documentation
CanChangeHintPage()
override protected bool CanChangeHintPage (float timeAccu) inline private
References GameConstants::LOADING_SCREEN_HINT_INTERVAL, and GameConstants::LOADING_SCREEN_HINT_INTERVAL_MIN.
Referenced by UIScriptedMenu::Update().
Hide()
void Hide () inline private
References m_HintPanel.
Init()
override Widget Init () inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), InputUtils::GetRichtextButtonIconFromInputAction(), CGame::GetWorkspace(), InputUtils::ICON_SCALE_TOOLBAR, and m_btnLeave.
IsRespawn()
bool IsRespawn () inline private
LoginTimeBase()
void LoginTimeBase () inline private
References g_Game.
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References m_btnLeave, x, and y.
SetRespawn()
void SetRespawn (bool value) inline private
SetStatus()
void SetStatus (string status) inline private
SetTime()
void SetTime (int time) inline private
References string::Format(), GetGame(), and CGame::SetLoginTimerFinished().
Show()
void Show () inline private
References m_HintPanel.
Field Documentation
m_btnLeave
protected ButtonWidget m_btnLeave private
m_FullTime
private ref FullTimeData m_FullTime private
m_IsRespawn
protected bool m_IsRespawn private
m_txtDescription
protected TextWidget m_txtDescription private
m_txtLabel
protected TextWidget m_txtLabel private
The documentation for this class was generated from the following file:
3_Game/DayZGame.c