DayZ Scripts: AlarmClock_ColorBase Class Reference
AlarmClock_ColorBase Class Reference
Private Member Functions
override void Init ()
void ~AlarmClock_ColorBase ()
override void SetActions ()
override string GetToggleSound ()
override string GetRingingSound ()
override string GetDestroyedSound ()
override string GetHitSound ()
override void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4)
override string GetExplosiveTriggerSlotName ()
override void OnDebugButtonPressServer (int button_index)
override string GetDebugText ()
void OnUpdate ()
protected void AnimateAlarmHand (float value)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnDebugSpawn ()
Private Attributes
const string RINGING_SOUND = "AlarmClock_Ring_Loop_SoundSet"
const string TURN_TOGGLE_SOUND = "AlarmClock_Turn_Off_SoundSet"
const string DESTROYED_SOUND = "AlarmClock_Destroyed_SoundSet"
const string HIT_SOUND = "AlarmClock_Hit_SoundSet"
Static Private Attributes
static ref NoiseParams m_NoisePar
static NoiseSystem m_NoiseSystem
Detailed Description
Definition at line 1 of file AlarmClock.c.
Constructor & Destructor Documentation
~AlarmClock_ColorBase()
void ~AlarmClock_ColorBase () inline private
Definition at line 27 of file AlarmClock.c.
References OnRingingStopClient().
Member Function Documentation
AnimateAlarmHand()
protected void AnimateAlarmHand (float value) inline private
Definition at line 132 of file AlarmClock.c.
GetDebugButtonNames()
override void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4) inline private
Definition at line 64 of file AlarmClock.c.
GetDebugText()
override string GetDebugText () inline private
Definition at line 79 of file AlarmClock.c.
References GetAlarmInMin(), GetGame(), GetRingingDurationMax(), m_RingingDuration, m_State, and float::ToString().
GetDestroyedSound()
override string GetDestroyedSound () inline private
Definition at line 54 of file AlarmClock.c.
References DESTROYED_SOUND.
GetExplosiveTriggerSlotName()
override string GetExplosiveTriggerSlotName () inline private
Definition at line 69 of file AlarmClock.c.
GetHitSound()
override string GetHitSound () inline private
Definition at line 59 of file AlarmClock.c.
References HIT_SOUND.
GetRingingSound()
override string GetRingingSound () inline private
Definition at line 49 of file AlarmClock.c.
References RINGING_SOUND.
GetToggleSound()
override string GetToggleSound () inline private
Definition at line 44 of file AlarmClock.c.
References TURN_TOGGLE_SOUND.
Init()
override void Init () inline private
Definition at line 12 of file AlarmClock.c.
References GetGame(), CGame::GetNoiseSystem(), GetType(), m_NoisePar, m_NoiseSystem, and NoiseParams().
OnDebugButtonPressServer()
override void OnDebugButtonPressServer (int button_index) inline private
Definition at line 74 of file AlarmClock.c.
References SetAlarmInXMins().
OnDebugSpawn()
override void OnDebugSpawn () inline private
Definition at line 184 of file AlarmClock.c.
References MakeRingingStart(), and TurnOn().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 138 of file AlarmClock.c.
References MakeRingingStart(), Serializer::Read(), SetAlarmTimeServer(), SetState(), and TurnOn().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 176 of file AlarmClock.c.
References m_AlarmTime01, m_State, and Serializer::Write().
OnUpdate()
void OnUpdate () inline private
Definition at line 97 of file AlarmClock.c.
References NoiseSystem::AddNoiseTarget(), ConvertAlarmHand01ToMins12h(), ConvertTimeToMins12h(), World::GetDate(), GetGame(), GetPosition, GetRingingDurationMax(), CGame::GetWorld(), IsAlarmOn(), IsRinging(), m_AlarmTime01, m_NoisePar, m_NoiseSystem, m_RingingDuration, MakeRingingStart(), TurnOff(), and UPDATE_TICK_RATE.
SetActions()
override void SetActions () inline private
Definition at line 35 of file AlarmClock.c.
References ActionTurnOffAlarmClock(), ActionTurnOnAlarmClock(), and AddAction().
Field Documentation
DESTROYED_SOUND
const string DESTROYED_SOUND = "AlarmClock_Destroyed_SoundSet" private
Definition at line 5 of file AlarmClock.c.
Referenced by GetDestroyedSound().
HIT_SOUND
const string HIT_SOUND = "AlarmClock_Hit_SoundSet" private
Definition at line 6 of file AlarmClock.c.
Referenced by GetHitSound().
m_NoisePar
ref NoiseParams m_NoisePar static private
Definition at line 9 of file AlarmClock.c.
Referenced by Init(), and OnUpdate().
m_NoiseSystem
NoiseSystem m_NoiseSystem static private
Definition at line 10 of file AlarmClock.c.
Referenced by Init(), and OnUpdate().
RINGING_SOUND
const string RINGING_SOUND = "AlarmClock_Ring_Loop_SoundSet" private
Definition at line 3 of file AlarmClock.c.
Referenced by GetRingingSound().
TURN_TOGGLE_SOUND
const string TURN_TOGGLE_SOUND = "AlarmClock_Turn_Off_SoundSet" private
Definition at line 4 of file AlarmClock.c.
Referenced by GetToggleSound().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Gear/Tools/AlarmClock.c