DayZ Scripts: P:/scripts/3_Game/Systems/Inventory/WeaponInventory.c File Reference
WeaponInventory.c File Reference
Data Structures
class WeaponInventory
inventory for weapons
Functions
proto native bool TryFireWeapon (EntityAI weapon, int muzzleIndex)
Function Documentation
TryFireWeapon()
proto native bool TryFireWeapon (EntityAI weapon, int muzzleIndex)
Referenced by WeaponStartAction::OnEntry(), WeaponFire::OnEntry(), and OnEntry().