DayZ Scripts: VONManagerBase Class Reference
VONManagerBase Class Reference
Private Member Functions
void VONManagerBase ()
void HideVoiceNotification ()
void ShowVoiceNotification (int level, bool fading)
void HandleInput (Input inp)
void OnVOIPThresholdChanged ()
void OnEvent (EventType eventTypeId, Param params)
bool IsVonToggled ()
Private Attributes
protected bool m_VoNToggled
ref ScriptInvoker m_OnVonStateEvent
ref ScriptInvoker m_OnPartyChatChangedEvent
Constructor & Destructor Documentation
VONManagerBase()
void VONManagerBase () inline private
References m_VoNToggled.
Member Function Documentation
HandleInput()
void HandleInput (Input inp) private
Referenced by MissionBase::OnUpdate().
HideVoiceNotification()
void HideVoiceNotification () private
Referenced by OnEvent(), and UpdateVoiceIcon().
IsVonToggled()
bool IsVonToggled () inline private
References m_VoNToggled.
Referenced by VONManager::IsVONToggled().
OnEvent()
void OnEvent (EventType eventTypeId, Param params) private
Referenced by CGame::OnEvent().
OnVOIPThresholdChanged()
void OnVOIPThresholdChanged () private
Referenced by ScriptedWidgetEventHandler::OptionsMenuSounds().
ShowVoiceNotification()
void ShowVoiceNotification (int level, bool fading) private
Referenced by OnEvent(), and UpdateVoiceIcon().
Field Documentation
m_OnPartyChatChangedEvent
ref ScriptInvoker m_OnPartyChatChangedEvent private
Referenced by ScriptedWidgetEventHandler::OptionsMenuSounds(), and ScriptedWidgetEventHandler::~OptionsMenuSounds().
m_OnVonStateEvent
ref ScriptInvoker m_OnVonStateEvent private
Referenced by ScriptedWidgetEventHandler::OptionsMenuSounds(), and ScriptedWidgetEventHandler::~OptionsMenuSounds().
m_VoNToggled
protected bool m_VoNToggled private
Referenced by IsVonToggled(), and VONManagerBase().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/VONManager.c