DayZ Scripts: RemoteDetonatorTrigger Class Reference
RemoteDetonatorTrigger Class Reference
Private Member Functions
void RemoteDetonatorTrigger ()
override bool IsKit ()
override void OnVariablesSynchronized ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
override void OnCEUpdate ()
override void PairRemote (notnull EntityAI trigger)
override void UnpairRemote ()
override void OnActivatedByItem (notnull ItemBase item)
void SetControlledDevice (EntityAI pDevice)
bool IsConnected ()
EntityAI GetControlledDevice ()
override void OnAnimationPhaseStarted (string animSource, float phase)
override void SetActions ()
Static Private Member Functions
static RemoteDetonatorTrigger SpawnInPlayerHands (notnull EntityAI pEntity)
Private Attributes
protected const string ANIM_PHASE_TRIGGER = "trigger"
protected bool m_LED
protected ref RemotelyActivatedItemBehaviour m_RAIB
Detailed Description
Definition at line 46 of file RemoteDetonator.c.
Constructor & Destructor Documentation
RemoteDetonatorTrigger()
void RemoteDetonatorTrigger () inline private
Definition at line 53 of file RemoteDetonator.c.
References EnumTools::GetEnumSize(), m_LastLEDState, m_RAIB, and UpdateLED().
Member Function Documentation
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 81 of file RemoteDetonator.c.
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
GetControlledDevice()
EntityAI GetControlledDevice () inline private
Definition at line 149 of file RemoteDetonator.c.
References RemotelyActivatedItemBehaviour::GetPairDevice(), and m_RAIB.
Referenced by ActionCondition(), ActionTriggerRemotely::ActionCondition(), OnActivatedByItem(), OnCEUpdate(), and ActionTriggerRemotely::OnExecuteServer().
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour () inline private
Definition at line 91 of file RemoteDetonator.c.
References m_RAIB.
IsConnected()
bool IsConnected () inline private
Definition at line 144 of file RemoteDetonator.c.
References RemotelyActivatedItemBehaviour::IsPaired(), and m_RAIB.
Referenced by ActionCondition(), ActionTriggerRemotely::ActionCondition(), OnCEUpdate(), and ActionTriggerRemotely::OnExecuteServer().
IsKit()
override bool IsKit () inline private
Definition at line 64 of file RemoteDetonator.c.
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 124 of file RemoteDetonator.c.
References vector::DistanceSq(), UAMaxDistances::EXPLOSIVE_REMOTE_ACTIVATION, GetControlledDevice(), GetGame(), GetPosition, RemotelyActivatedItemBehaviour::IsPaired(), IsRuined(), m_RAIB, and Math::SqrFloat().
OnAnimationPhaseStarted()
override void OnAnimationPhaseStarted (string animSource, float phase) inline private
Definition at line 182 of file RemoteDetonator.c.
References ANIM_PHASE_TRIGGER, and UpdateLED().
OnCEUpdate()
override void OnCEUpdate () inline private
Definition at line 96 of file RemoteDetonator.c.
References vector::DistanceSq(), UAMaxDistances::EXPLOSIVE_REMOTE_ACTIVATION, GetControlledDevice(), GetPosition, IsConnected(), IsRuined(), Math::SqrFloat(), and UpdateLED().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Definition at line 69 of file RemoteDetonator.c.
References m_LastLEDState, m_RAIB, RemotelyActivatedItemBehaviour::OnVariableSynchronized(), and UpdateLED().
PairRemote()
override void PairRemote (notnull EntityAI trigger) inline private
Definition at line 113 of file RemoteDetonator.c.
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
Referenced by OnEndServer().
SetActions()
override void SetActions () inline private
Definition at line 193 of file RemoteDetonator.c.
References ActionAttachExplosivesTrigger(), ActionDisarmExplosiveWithRemoteDetonator(), AddAction(), and RemoveAction().
SetControlledDevice()
void SetControlledDevice (EntityAI pDevice) inline private
Definition at line 139 of file RemoteDetonator.c.
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
Referenced by ClaymoreMine::OnDebugSpawn(), OnEndServer(), and ClaymoreMine::OnPlacementComplete().
SpawnInPlayerHands()
static RemoteDetonatorTrigger SpawnInPlayerHands (notnull EntityAI pEntity) inline static private
item replaced, use different IK
Definition at line 154 of file RemoteDetonator.c.
Referenced by CreateRemoteDetonatorReceiverAsAttachment(), and ClaymoreMine::OnPlacementComplete().
UnpairRemote()
override void UnpairRemote () inline private
Definition at line 118 of file RemoteDetonator.c.
References m_RAIB, RemotelyActivatedItemBehaviour::Unpair(), and UpdateLED().
Field Documentation
ANIM_PHASE_TRIGGER
protected const string ANIM_PHASE_TRIGGER = "trigger" private
Definition at line 48 of file RemoteDetonator.c.
Referenced by OnAnimationPhaseStarted().
m_LED
protected bool m_LED private
Definition at line 50 of file RemoteDetonator.c.
m_RAIB
protected ref RemotelyActivatedItemBehaviour m_RAIB private
Definition at line 51 of file RemoteDetonator.c.
Referenced by EEItemLocationChanged(), GetControlledDevice(), GetRemotelyActivatedItemBehaviour(), IsConnected(), OnActivatedByItem(), OnVariablesSynchronized(), PairRemote(), RemoteDetonatorTrigger(), SetControlledDevice(), and UnpairRemote().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ExplosivesBase/RemoteDetonator.c