DayZ Scripts: ColorManager Class Reference
ColorManager Class Reference
Private Member Functions
void ColorManager ()
void SetColor (Widget w, int color)
int GetItemColor (ItemBase item)
Static Private Member Functions
static ColorManager GetInstance ()
Static Private Attributes
private static ref ColorManager m_Instance
static int COLOR_NORMAL_TEXT = ARGB(255, 255, 255, 255)
static int COLOR_NORMAL_PANEL = ARGB(140, 0, 0, 0)
static int COLOR_HIGHLIGHT_TEXT = ARGB(255, 200, 0, 0)
static int COLOR_HIGHLIGHT_PANEL = ARGB(255, 0, 0, 0)
static int COLOR_SELECTED_TEXT = ARGB(255, 255, 255, 255)
static int COLOR_SELECTED_PANEL = ARGB(255, 200, 0, 0)
static int COLOR_DISABLED_TEXT = ARGB(100, 255, 255, 255)
static int COLOR_DISABLED_PANEL = ARGB(140, 0, 0, 0)
static int ITEM_BACKGROUND_COLOR = ARGB(50, 255, 255, 255)
static int BASE_COLOR = ARGB(10, 255, 255, 255)
static int RED_COLOR = ARGB(150, 255, 1, 1)
static int GREEN_COLOR = ARGB(150, 1, 255, 1)
static int SWAP_COLOR = ARGB(150, 135, 206, 250)
static int FSWAP_COLOR = ARGB(150, 35, 106, 150)
static int COMBINE_COLOR = ARGB(150, 255, 165, 0)
Detailed Description
Definition at line 1 of file ColorManager.c.
Constructor & Destructor Documentation
ColorManager()
void ColorManager () inline private
Definition at line 22 of file ColorManager.c.
References m_Instance.
Member Function Documentation
GetInstance()
static ColorManager GetInstance () inline static private
Definition at line 27 of file ColorManager.c.
References m_Instance.
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), ItemManager::SetIconTemperature(), ItemManager::SetTemperature(), and Icon::ShowActionMenuCombine().
GetItemColor()
int GetItemColor (ItemBase item) inline private
Definition at line 50 of file ColorManager.c.
References ItemManager::GetDraggedItem(), GetGame(), ItemManager::GetInstance(), GetPlayer(), and GetTemperatureColor().
Referenced by ItemManager::SetIconTemperature(), and ItemManager::SetTemperature().
SetColor()
void SetColor (Widget w, int color) inline private
Definition at line 32 of file ColorManager.c.
References name, and string::Replace().
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), and Icon::ShowActionMenuCombine().
Field Documentation
BASE_COLOR
int BASE_COLOR = ARGB(10, 255, 255, 255) static private
Definition at line 15 of file ColorManager.c.
Referenced by Icon::CreateWhiteBackground(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), ClosableContainer::DropReceived(), and ItemManager::SetIconTemperature().
COLOR_DISABLED_PANEL
int COLOR_DISABLED_PANEL = ARGB(140, 0, 0, 0) static private
Definition at line 12 of file ColorManager.c.
COLOR_DISABLED_TEXT
int COLOR_DISABLED_TEXT = ARGB(100, 255, 255, 255) static private
Definition at line 11 of file ColorManager.c.
Referenced by UIScriptedMenu::ColorDisable(), ColorDisable(), ServerBrowserTab::ColorDisable(), UIScriptedMenu::ColorDisabled(), and UIScriptedMenu::ColorWhite().
COLOR_HIGHLIGHT_PANEL
int COLOR_HIGHLIGHT_PANEL = ARGB(255, 0, 0, 0) static private
Definition at line 8 of file ColorManager.c.
COLOR_HIGHLIGHT_TEXT
int COLOR_HIGHLIGHT_TEXT = ARGB(255, 200, 0, 0) static private
Definition at line 7 of file ColorManager.c.
COLOR_NORMAL_PANEL
int COLOR_NORMAL_PANEL = ARGB(140, 0, 0, 0) static private
Definition at line 6 of file ColorManager.c.
COLOR_NORMAL_TEXT
int COLOR_NORMAL_TEXT = ARGB(255, 255, 255, 255) static private
Definition at line 5 of file ColorManager.c.
Referenced by UIScriptedMenu::ColorNormal(), and UIScriptedMenu::ColorWhite().
COLOR_SELECTED_PANEL
int COLOR_SELECTED_PANEL = ARGB(255, 200, 0, 0) static private
Definition at line 10 of file ColorManager.c.
COLOR_SELECTED_TEXT
int COLOR_SELECTED_TEXT = ARGB(255, 255, 255, 255) static private
Definition at line 9 of file ColorManager.c.
COMBINE_COLOR
int COMBINE_COLOR = ARGB(150, 255, 165, 0) static private
Definition at line 20 of file ColorManager.c.
Referenced by Icon::DraggingOver(), PlayerContainer::DraggingOver(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), and Icon::ShowActionMenuCombine().
FSWAP_COLOR
int FSWAP_COLOR = ARGB(150, 35, 106, 150) static private
Definition at line 19 of file ColorManager.c.
Referenced by Icon::DraggingOver(), and Icon::DraggingOverSwap().
GREEN_COLOR
int GREEN_COLOR = ARGB(150, 1, 255, 1) static private
Definition at line 17 of file ColorManager.c.
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), AttachmentCategoriesRow::DraggingOverGrid(), ClosableContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), and VicinityContainer::DraggingOverHeader().
ITEM_BACKGROUND_COLOR
int ITEM_BACKGROUND_COLOR = ARGB(50, 255, 255, 255) static private
Definition at line 14 of file ColorManager.c.
m_Instance
private static ref ColorManager m_Instance static private
Definition at line 3 of file ColorManager.c.
Referenced by ColorManager(), and GetInstance().
RED_COLOR
int RED_COLOR = ARGB(150, 255, 1, 1) static private
Definition at line 16 of file ColorManager.c.
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), AttachmentCategoriesRow::DraggingOverGrid(), ClosableContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), and Icon::ShowActionMenuCombine().
SWAP_COLOR
int SWAP_COLOR = ARGB(150, 135, 206, 250) static private
Definition at line 18 of file ColorManager.c.
Referenced by Icon::DraggingOver(), PlayerContainer::DraggingOver(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), and Icon::DraggingOverSwap().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/ColorManager.c