DayZ Scripts: SoundObjectBuilder Class Reference
SoundObjectBuilder Class Reference
Private Member Functions
void SoundObjectBuilder (SoundParams soundParams)
SoundObject BuildSoundObject ()
proto native void Initialize (SoundParams soundParams)
proto native void AddEnvSoundVariables (vector position)
proto native void AddVariable (string name, float value)
proto void AddVariables (notnull array< string > names, array< float > values=null)
void UpdateEnvSoundControllers (vector position)
Deprecated - same functionality, just poor naming.
void SetVariable (string name, float value)
Deprecated - same functionality, just poor naming.
Constructor & Destructor Documentation
SoundObjectBuilder()
void SoundObjectBuilder (SoundParams soundParams) private
Member Function Documentation
AddEnvSoundVariables()
proto native void AddEnvSoundVariables (vector position) private
Referenced by EntityAI::PlayImpactSound(), DayZCreature::ProcessSoundEvent(), DayZPlayer::ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), EffectSound::SoundLoadEx(), EffectSound::SoundPlayEx(), and UpdateEnvSoundControllers().
AddVariable()
proto native void AddVariable (string name, float value) private
Referenced by DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder(), EntityAI::PlayImpactSound(), DayZPlayer::ProcessVoiceEvent(), DayZPlayer::ProcessWeaponEvent(), SetVariable(), and DayZPlayer::SetVariablesLadderSoundObjectBuilder().
AddVariables()
proto void AddVariables (notnull array< string > names, array< float > values = null) private
BuildSoundObject()
SoundObject BuildSoundObject () inline private
References GetGame(), and CGame::GetSoundScene().
Referenced by DayZPlayer::HandleView(), DayZPlayer::OnStepEvent(), EntityAI::PlayImpactSound(), MissionBase::PlayMusic(), EntityAI::PlaySoundByAnimEvent(), DynamicMusicPlayer::PlayTrack(), DayZPlayer::ProcessAttachmentEvent(), DayZCreature::ProcessSoundEvent(), DayZPlayer::ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), DayZPlayer::ProcessVoiceEvent(), DayZInfected::ProcessVoiceFX(), DayZPlayer::ProcessWeaponEvent(), EffectSound::SoundLoadEx(), and EffectSound::SoundPlayEx().
Initialize()
proto native void Initialize (SoundParams soundParams) private
SetVariable()
void SetVariable (string name, float value) inline private
Deprecated - same functionality, just poor naming.
References AddVariable(), and name.
UpdateEnvSoundControllers()
void UpdateEnvSoundControllers (vector position) inline private
Deprecated - same functionality, just poor naming.
References AddEnvSoundVariables().
The documentation for this class was generated from the following file:
P:/scripts/3_game/sound.c