DayZ Scripts: PlayerSpawnHandler Class Reference
PlayerSpawnHandler Class Reference
Static Private Member Functions
static bool LoadData ()
static bool IsInitialized ()
static PlayerSpawnPreset GetRandomCharacterPreset ()
static bool ProcessEquipmentData (PlayerBase player, PlayerSpawnPreset data)
equips character with the chosen preset
static private void ProcessSlotsEquipment (PlayerBase player, PlayerSpawnPreset data)
iterates over each object and spawns alternatives
static private bool SelectAndSpawnSlotEquipment (PlayerBase player, PlayerSpawnPresetSlotData slotData)
selects weighted slot equipment variant
static private void ProcessCargoEquipment (PlayerBase player, PlayerSpawnPreset data)
chooses one object from the array
static private bool SelectAndSpawnCargoSet (PlayerBase player, PlayerSpawnPreset data)
static private bool SpawnDiscreteCargoItemSet (PlayerBase player, PlayerSpawnPresetDiscreteCargoSetData csd)
static private bool SpawnDiscreteSlotItemSet (PlayerBase player, PlayerSpawnPresetDiscreteItemSetSlotData dis, int slotID)
static private bool SpawnComplexChildrenItems (EntityAI parent, notnull PlayerSpawnPresetItemSetBase data)
could spawn other items recursively. Parent item is guaranteed here.
static private bool SpawnSimpleChildrenItems (EntityAI parent, PlayerSpawnPresetItemSetBase data)
static private void HandleNewItem (notnull ItemBase item, PlayerSpawnPresetItemSetBase data)
static private EntityAI CreateChildItem (EntityAI parent, string type)
static private void ApplyAttributes (ItemBase item, PlayerSpawnAttributesData attributes)
Static Private Attributes
static private bool m_Initialized
static ref PlayerSpawnJsonData m_Data = new PlayerSpawnJsonData()
Member Function Documentation
ApplyAttributes()
static private void ApplyAttributes (ItemBase item, PlayerSpawnAttributesData attributes) inline static private
References Math::Lerp(), Math::RandomFloatInclusive(), and Math::Round().
Referenced by HandleNewItem(), and SpawnSimpleChildrenItems().
CreateChildItem()
static private EntityAI CreateChildItem (EntityAI parent, string type) inline static private
References Class::CastTo(), CFG_MAGAZINESPATH, GetGame(), and Debug::Log().
Referenced by SpawnComplexChildrenItems(), and SpawnSimpleChildrenItems().
GetRandomCharacterPreset()
static PlayerSpawnPreset GetRandomCharacterPreset () inline static private
References PlayerSpawnPreset::IsValid(), m_Data, and PlayerSpawnPreset::spawnWeight.
Referenced by MissionBase::OnClientNewEvent().
HandleNewItem()
static private void HandleNewItem (notnull ItemBase item, PlayerSpawnPresetItemSetBase data) inline static private
References ApplyAttributes(), PlayerSpawnPresetItemSetBase::attributes, Class::CastTo(), PlayerSpawnPresetItemSetBase::GetQuickbarIdx(), SpawnComplexChildrenItems(), and SpawnSimpleChildrenItems().
Referenced by SpawnComplexChildrenItems(), and SpawnDiscreteSlotItemSet().
IsInitialized()
static bool IsInitialized () inline static private
References m_Initialized.
Referenced by MissionBase::OnClientNewEvent().
LoadData()
static bool LoadData () inline static private
References ErrorEx, CfgGameplayHandler::GetPlayerSpawnGearPresetFiles(), m_Data, m_Initialized, and path.
Referenced by MissionBase::OnInit().
ProcessCargoEquipment()
static private void ProcessCargoEquipment (PlayerBase player, PlayerSpawnPreset data) inline static private
chooses one object from the array
References PlayerSpawnPreset::HasDiscreteUnsortedItemSetsDefined(), Debug::Log(), and SelectAndSpawnCargoSet().
Referenced by ProcessEquipmentData().
ProcessEquipmentData()
static bool ProcessEquipmentData (PlayerBase player, PlayerSpawnPreset data) inline static private
equips character with the chosen preset
References PlayerSpawnPreset::IsValid(), ProcessCargoEquipment(), and ProcessSlotsEquipment().
Referenced by MissionBase::OnClientNewEvent().
ProcessSlotsEquipment()
static private void ProcessSlotsEquipment (PlayerBase player, PlayerSpawnPreset data) inline static private
iterates over each object and spawns alternatives
References PlayerSpawnPreset::attachmentSlotItemSets, PlayerSpawnPreset::HasAttachmentSlotSetsDefined(), Debug::Log(), and SelectAndSpawnSlotEquipment().
Referenced by ProcessEquipmentData().
SelectAndSpawnCargoSet()
static private bool SelectAndSpawnCargoSet (PlayerBase player, PlayerSpawnPreset data) inline static private
References PlayerSpawnPreset::discreteUnsortedItemSets, and SpawnDiscreteCargoItemSet().
Referenced by ProcessCargoEquipment().
SelectAndSpawnSlotEquipment()
static private bool SelectAndSpawnSlotEquipment (PlayerBase player, PlayerSpawnPresetSlotData slotData) inline static private
selects weighted slot equipment variant
References PlayerSpawnPresetDiscreteItemSetSlotData::IsValid(), and SpawnDiscreteSlotItemSet().
Referenced by ProcessSlotsEquipment().
SpawnComplexChildrenItems()
static private bool SpawnComplexChildrenItems (EntityAI parent, notnull PlayerSpawnPresetItemSetBase data) inline static private
could spawn other items recursively. Parent item is guaranteed here.
References Class::CastTo(), CreateChildItem(), HandleNewItem(), and Debug::Log().
Referenced by HandleNewItem(), and SpawnDiscreteCargoItemSet().
SpawnDiscreteCargoItemSet()
static private bool SpawnDiscreteCargoItemSet (PlayerBase player, PlayerSpawnPresetDiscreteCargoSetData csd) inline static private
References SpawnComplexChildrenItems(), and SpawnSimpleChildrenItems().
Referenced by SelectAndSpawnCargoSet().
SpawnDiscreteSlotItemSet()
static private bool SpawnDiscreteSlotItemSet (PlayerBase player, PlayerSpawnPresetDiscreteItemSetSlotData dis, int slotID) inline static private
References string::Empty, InventorySlots::GetSlotName(), HandleNewItem(), PlayerSpawnPresetDiscreteItemSetSlotData::itemType, and Debug::Log().
Referenced by SelectAndSpawnSlotEquipment().
SpawnSimpleChildrenItems()
static private bool SpawnSimpleChildrenItems (EntityAI parent, PlayerSpawnPresetItemSetBase data) inline static private
References ApplyAttributes(), PlayerSpawnPresetItemSetBase::attributes, Class::CastTo(), CreateChildItem(), Empty, Debug::Log(), PlayerSpawnPresetItemSetBase::simpleChildrenTypes, and PlayerSpawnPresetItemSetBase::simpleChildrenUseDefaultAttributes.
Referenced by HandleNewItem(), and SpawnDiscreteCargoItemSet().
Field Documentation
m_Data
ref PlayerSpawnJsonData m_Data = new PlayerSpawnJsonData() static private
Referenced by GetRandomCharacterPreset(), and LoadData().
m_Initialized
private bool m_Initialized static private
Referenced by IsInitialized(), and LoadData().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerGearSpawn/CfgPlayerSpawnHandler.c