DayZ Scripts: ZombieContainer Class Reference
ZombieContainer Class Reference
Private Member Functions
void ZombieContainer (LayoutHolder parent, int sort=-1)
void ~ZombieContainer ()
void SetEntity (EntityAI zombie_entity)
override void UpdateRadialIcon ()
override bool IsItemWithQuantityActive ()
bool IsContainerWithCargoActive ()
bool IsItemWithAttachmentsActive ()
bool IsZombieEquipmentActive ()
bool IsItemWithContainerActive ()
bool IsEmptyItemActive ()
override void ExpandCollapseContainer ()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromGhostArea (Widget w, int x, int y, Widget receiver)
void SetHeaderName ()
void ItemAttached (EntityAI item, string slot_name)
void ItemDetached (EntityAI item, string slot_name)
override bool CanOpenCloseContainerEx (EntityAI focusedEntity)
void ToggleContainer (Widget w)
SlotsIcon GetSlotsIcon (int row, int column)
void InitGhostSlots ()
void AddSlotsContainer (int row_count)
Widget GetWidgetSlot (int slot_number)
void DoubleClick (Widget w, int x, int y, int button)
override void CollapseButtonOnMouseButtonDown (Widget w)
override bool SplitItem ()
override bool EquipItem ()
override bool TransferItem ()
override bool Select ()
override bool TransferItemToVicinity ()
Private Attributes
protected ref AttachmentsGroupContainer m_Container
protected ref ContainerWithCargo m_CargoGrid
protected ref map< int, SlotsIcon > m_InventorySlots
protected ref map< EntityAI, ref Container > m_ShowedItems = new ref map<EntityAI, ref Container>
protected EntityAI m_ZombieEntity
Detailed Description
Definition at line 1 of file ZombieContainer.c.
Constructor & Destructor Documentation
ZombieContainer()
void ZombieContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 9 of file ZombieContainer.c.
References CollapsibleContainer::GetHeader(), WidgetEventHandler::GetInstance(), m_Container, m_InventorySlots, m_RootWidget, WidgetEventHandler::RegisterOnChildAdd(), WidgetEventHandler::RegisterOnChildRemove(), AttachmentsGroupContainer::SetHeader(), CollapsibleContainer::SetHeader(), and SetHeaderName().
~ZombieContainer()
void ~ZombieContainer () inline private
Definition at line 28 of file ZombieContainer.c.
References ItemAttached(), ItemDetached(), and m_ZombieEntity.
Member Function Documentation
AddSlotsContainer()
void AddSlotsContainer (int row_count) inline private
Definition at line 482 of file ZombieContainer.c.
References m_Container, and m_ZombieEntity.
Referenced by InitGhostSlots().
CanOpenCloseContainerEx()
override bool CanOpenCloseContainerEx (EntityAI focusedEntity) inline private
Definition at line 321 of file ZombieContainer.c.
References SlotsIcon::GetContainer(), ClosableContainer::IsDisplayable(), and m_ShowedItems.
CollapseButtonOnMouseButtonDown()
override void CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 566 of file ZombieContainer.c.
DoubleClick()
void DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 497 of file ZombieContainer.c.
References g_Game, GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), InventoryLocation::GetSlot(), InventoryMenu(), MENU_INVENTORY, name, and string::Replace().
DraggingOverHeader()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 134 of file ZombieContainer.c.
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), name, and string::Replace().
EquipItem()
override bool EquipItem () inline private
Definition at line 581 of file ZombieContainer.c.
References Container::GetFocusedItem(), GetGame(), and CGame::GetPlayer().
ExpandCollapseContainer()
override void ExpandCollapseContainer () inline private
Definition at line 93 of file ZombieContainer.c.
References IsZombieEquipmentActive(), and ToggleContainer().
GetSlotsIcon()
SlotsIcon GetSlotsIcon (int row, int column) inline private
Definition at line 371 of file ZombieContainer.c.
References Container::Get(), SlotsContainer::GetSlotIcon(), and m_Container.
Referenced by InitGhostSlots().
GetWidgetSlot()
Widget GetWidgetSlot (int slot_number) inline private
Definition at line 489 of file ZombieContainer.c.
References Container::Get(), ITEMS_IN_ROW, and m_Container.
InitGhostSlots()
void InitGhostSlots () inline private
Definition at line 376 of file ZombieContainer.c.
References AddSlotsContainer(), SlotsIcon::Clear(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), GetGame(), SlotsIcon::GetGhostSlot(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), SlotsIcon::GetRadialIcon(), SlotsIcon::GetRadialIconPanel(), InventorySlots::GetSlotDisplayName(), InventorySlots::GetSlotIdFromString(), GetSlotsIcon(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, ItemAttached(), ITEMS_IN_ROW, m_CargoGrid, m_Container, m_InventorySlots, m_ShowedItems, m_ZombieEntity, path, WidgetEventHandler::RegisterOnDoubleClick(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), WidgetEventHandler::RegisterOnMouseButtonUp(), SlotsIcon::SetContainer(), SlotsIcon::SetSlotDisplayName(), SlotsIcon::SetSlotID(), and StaticGUIUtils::VerifyIconImageString().
Referenced by SetEntity().
IsContainerWithCargoActive()
bool IsContainerWithCargoActive () inline private
Definition at line 67 of file ZombieContainer.c.
IsEmptyItemActive()
bool IsEmptyItemActive () inline private
Definition at line 88 of file ZombieContainer.c.
References Container::GetFocusedItem().
IsItemWithAttachmentsActive()
bool IsItemWithAttachmentsActive () inline private
Definition at line 72 of file ZombieContainer.c.
IsItemWithContainerActive()
bool IsItemWithContainerActive () inline private
Definition at line 82 of file ZombieContainer.c.
References Container::GetFocusedItem().
IsItemWithQuantityActive()
override bool IsItemWithQuantityActive () inline private
Definition at line 61 of file ZombieContainer.c.
References Container::GetFocusedItem(), and QuantityConversions::HasItemQuantity().
IsZombieEquipmentActive()
bool IsZombieEquipmentActive () inline private
Definition at line 77 of file ZombieContainer.c.
References m_Container.
Referenced by ExpandCollapseContainer().
ItemAttached()
void ItemAttached (EntityAI item, string slot_name) inline private
Definition at line 245 of file ZombieContainer.c.
References CGame::ConfigIsExisting(), GetGame(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), SlotsIcon::GetRadialIcon(), SlotsIcon::GetRadialIconClosed(), SlotsIcon::GetRadialIconPanel(), InventorySlots::GetSlotIdFromString(), SlotsIcon::Init(), ClosableContainer::IsOpened(), m_InventorySlots, m_ShowedItems, name, CollapsibleContainer::Refresh(), and WidgetEventHandler::RegisterOnMouseButtonUp().
Referenced by InitGhostSlots(), SetEntity(), and ~ZombieContainer().
ItemDetached()
void ItemDetached (EntityAI item, string slot_name) inline private
Definition at line 297 of file ZombieContainer.c.
References SlotsIcon::Clear(), InventorySlots::GetSlotIdFromString(), Inventory(), m_InventorySlots, m_ShowedItems, CollapsibleContainer::Refresh(), and CollapsibleContainer::Remove().
Referenced by SetEntity(), and ~ZombieContainer().
OnDropReceivedFromGhostArea()
void OnDropReceivedFromGhostArea (Widget w, int x, int y, Widget receiver) inline private
Definition at line 169 of file ZombieContainer.c.
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), m_ZombieEntity, name, and string::Replace().
OnDropReceivedFromHeader()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 102 of file ZombieContainer.c.
References GetGame(), ItemPreviewWidget::GetItem(), CGame::GetPlayer(), m_ZombieEntity, name, and string::Replace().
Select()
override bool Select () inline private
Definition at line 634 of file ZombieContainer.c.
References GameInventory::CanSwapEntitiesEx(), Container::GetFocusedItem(), GetGame(), ItemManager::GetInstance(), InventoryLocation::GetParent(), CGame::GetPlayer(), GetPlayer(), ItemManager::GetSelectedIcon(), ItemManager::GetSelectedItem(), SlotsIcon::IsOutOfReach(), m_ZombieEntity, and ItemManager::SetSelectedItem().
SetEntity()
void SetEntity (EntityAI zombie_entity) inline private
Definition at line 37 of file ZombieContainer.c.
References InitGhostSlots(), ItemAttached(), ItemDetached(), m_Parent, and m_ZombieEntity.
Referenced by VicinityContainer::UpdateInterval().
SetHeaderName()
void SetHeaderName () inline private
Definition at line 240 of file ZombieContainer.c.
References CollapsibleContainer::m_CollapsibleHeader, and Header::SetName().
Referenced by ZombieContainer().
SplitItem()
override bool SplitItem () inline private
Definition at line 571 of file ZombieContainer.c.
ToggleContainer()
void ToggleContainer (Widget w) inline private
Definition at line 346 of file ZombieContainer.c.
References SlotsIcon::GetContainer(), SlotsIcon::GetEntity(), and m_ShowedItems.
Referenced by ExpandCollapseContainer().
TransferItem()
override bool TransferItem () inline private
Definition at line 599 of file ZombieContainer.c.
References Container::GetFocusedItem(), GetGame(), GetParent(), and CGame::GetPlayer().
TransferItemToVicinity()
override bool TransferItemToVicinity () inline private
Definition at line 701 of file ZombieContainer.c.
References Container::GetFocusedItem(), GetGame(), and CGame::GetPlayer().
UpdateRadialIcon()
override void UpdateRadialIcon () inline private
Definition at line 46 of file ZombieContainer.c.
References CollapsibleContainer::IsHidden(), and m_ZombieEntity.
Field Documentation
m_CargoGrid
protected ref ContainerWithCargo m_CargoGrid private
Definition at line 4 of file ZombieContainer.c.
Referenced by InitGhostSlots().
m_Container
protected ref AttachmentsGroupContainer m_Container private
Definition at line 3 of file ZombieContainer.c.
Referenced by AddSlotsContainer(), GetSlotsIcon(), GetWidgetSlot(), InitGhostSlots(), IsZombieEquipmentActive(), and ZombieContainer().
m_InventorySlots
protected ref map<int, SlotsIcon> m_InventorySlots private
Definition at line 5 of file ZombieContainer.c.
Referenced by InitGhostSlots(), ItemAttached(), ItemDetached(), and ZombieContainer().
m_ShowedItems
protected ref map<EntityAI, ref Container> m_ShowedItems = new ref map<EntityAI, ref Container> private
Definition at line 6 of file ZombieContainer.c.
Referenced by CanOpenCloseContainerEx(), InitGhostSlots(), ItemAttached(), ItemDetached(), and ToggleContainer().
m_ZombieEntity
protected EntityAI m_ZombieEntity private
Definition at line 7 of file ZombieContainer.c.
Referenced by AddSlotsContainer(), InitGhostSlots(), OnDropReceivedFromGhostArea(), OnDropReceivedFromHeader(), Select(), SetEntity(), UpdateRadialIcon(), and ~ZombieContainer().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Inherited/ZombieContainer.c