DayZ Scripts: NoiseSystem Class Reference
NoiseSystem Class Reference
Private Member Functions
private void NoiseSystem ()
private void ~NoiseSystem ()
proto void AddNoise (EntityAI source_entity, NoiseParams noise_params, float external_strenght_multiplier=1.0)
proto void AddNoisePos (EntityAI source_entity, vector pos, NoiseParams noise_params, float external_strenght_multiplier=1.0)
proto void AddNoiseTarget (vector pos, float lifetime, NoiseParams noise_params, float external_strength_multiplier=1.0)
Will make a noise at that position which the AI will "see" for the duration of 'lifetime'.
Detailed Description
Definition at line 1 of file Noise.c.
Constructor & Destructor Documentation
NoiseSystem()
private void NoiseSystem () inline private
Definition at line 3 of file Noise.c.
~NoiseSystem()
private void ~NoiseSystem () inline private
Definition at line 4 of file Noise.c.
Member Function Documentation
AddNoise()
proto void AddNoise (EntityAI source_entity, NoiseParams noise_params, float external_strenght_multiplier = 1.0) private
Referenced by DayZPlayer::AddNoise(), DayZCreature::ProcessSoundEvent(), DayZPlayer::ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), and DayZInfected::ProcessSoundVoiceEvent().
AddNoisePos()
proto void AddNoisePos (EntityAI source_entity, vector pos, NoiseParams noise_params, float external_strenght_multiplier = 1.0) private
Referenced by CGame::CloseCombatEffects(), Heating(), ActionCloseDoors::OnEndServer(), ActionCloseFence::OnEndServer(), ActionOpenDoors::OnEndServer(), ActionOpenFence::OnEndServer(), OnWork(), and OnWorkStart().
AddNoiseTarget()
proto void AddNoiseTarget (vector pos, float lifetime, NoiseParams noise_params, float external_strength_multiplier = 1.0) private
Will make a noise at that position which the AI will "see" for the duration of 'lifetime'.
Referenced by CGame::ExplosionEffectsEx(), CGame::FirearmEffects(), GenerateAINoiseAtPosition(), GenerateCarHornAINoise(), AlarmClock_ColorBase::OnUpdate(), and KitchenTimer::OnUpdate().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Noise.c