DayZ Scripts: GeyserTrigger Class Reference
GeyserTrigger Class Reference
Private Member Functions
void GeyserTrigger ()
override void EEInit ()
override void EEDelete (EntityAI parent)
override void OnEnterServerEvent (TriggerInsider insider)
override void OnLeaveServerEvent (TriggerInsider insider)
override void OnEnterClientEvent (TriggerInsider insider)
override void OnLeaveClientEvent (TriggerInsider insider)
override void OnVariablesSynchronized ()
protected void UpdateGeyserState ()
protected void RandomizeMouthPos ()
protected vector GetAdjustedPosition (float height=0)
void StopEffects ()
void AddGeyserState (EGeyserState state)
void RemoveGeyserState (EGeyserState state)
EGeyserState GetGeyserState ()
bool IsSubmerged ()
Private Attributes
const float MOUTH_ADJUST_RADIUS = 0.2
const string SOUND_BUBBLING = "Boiling_Done_SoundSet"
const string SOUND_ERUPTION = "pour_Water_Pot_SoundSet"
const string SOUND_ERUPTION_TALL = "pour_Water_WatterBottle_SoundSet"
protected bool m_bIsDormant
protected bool m_bIsErupting
protected bool m_bIsEruptingTall
protected float m_AdjustedX
protected float m_AdjustedY
protected vector m_DefaultPosition
protected EGeyserState m_GeyserState = EGeyserState.DORMANT
protected ParticleSource m_GeyserParticle
protected ParticleSource m_GeyserTallParticle
protected EffectSound m_SoundBubbling
protected EffectSound m_SoundEruption
protected EffectSound m_SoundEruptionSecondary
Constructor & Destructor Documentation
GeyserTrigger()
void GeyserTrigger () inline private
Member Function Documentation
AddGeyserState()
void AddGeyserState (EGeyserState state) inline private
References m_GeyserState.
Referenced by TickState().
EEDelete()
override void EEDelete (EntityAI parent) inline private
References StopEffects().
EEInit()
override void EEInit () inline private
References GetGame(), GetPosition, m_bIsDormant, m_bIsErupting, m_bIsEruptingTall, m_DefaultPosition, RandomizeMouthPos(), and CGame::SurfaceY().
GetAdjustedPosition()
protected vector GetAdjustedPosition (float height = 0) inline private
References IsSubmerged(), m_AdjustedX, m_AdjustedY, and m_DefaultPosition.
Referenced by UpdateGeyserState().
GetGeyserState()
EGeyserState GetGeyserState () inline private
References m_GeyserState.
Referenced by TickState().
IsSubmerged()
bool IsSubmerged () inline private
Referenced by GetAdjustedPosition(), and UpdateGeyserState().
OnEnterClientEvent()
override void OnEnterClientEvent (TriggerInsider insider) inline private
OnEnterServerEvent()
override void OnEnterServerEvent (TriggerInsider insider) inline private
References TriggerInsider::GetObject(), and m_GeyserState.
OnLeaveClientEvent()
override void OnLeaveClientEvent (TriggerInsider insider) inline private
OnLeaveServerEvent()
override void OnLeaveServerEvent (TriggerInsider insider) inline private
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References UpdateGeyserState().
RandomizeMouthPos()
protected void RandomizeMouthPos () inline private
References m_AdjustedX, m_AdjustedY, m_DefaultPosition, MOUTH_ADJUST_RADIUS, and Math::RandomFloat().
Referenced by EEInit(), and UpdateGeyserState().
RemoveGeyserState()
void RemoveGeyserState (EGeyserState state) inline private
References m_GeyserState.
Referenced by TickState().
StopEffects()
void StopEffects () inline private
References m_bIsDormant, m_bIsErupting, m_bIsEruptingTall, m_GeyserParticle, m_GeyserTallParticle, m_SoundBubbling, m_SoundEruption, m_SoundEruptionSecondary, EffectSound::Stop(), and ParticleSource::StopParticle().
Referenced by EEDelete(), and EEDelete().
UpdateGeyserState()
protected void UpdateGeyserState () inline private
References GetAdjustedPosition(), ParticleList::GEYSER_NORMAL, ParticleList::GEYSER_STRONG, IsSubmerged(), m_bIsDormant, m_bIsErupting, m_bIsEruptingTall, m_GeyserParticle, m_GeyserState, m_GeyserTallParticle, m_SoundBubbling, m_SoundEruption, m_SoundEruptionSecondary, ParticleManager(), SEffectManager::PlaySound(), RandomizeMouthPos(), SOUND_BUBBLING, SOUND_ERUPTION, SOUND_ERUPTION_TALL, EffectSound::Stop(), and ParticleSource::StopParticle().
Referenced by OnVariablesSynchronized().
Field Documentation
m_AdjustedX
protected float m_AdjustedX private
Referenced by GetAdjustedPosition(), and RandomizeMouthPos().
m_AdjustedY
protected float m_AdjustedY private
Referenced by GetAdjustedPosition(), and RandomizeMouthPos().
m_bIsDormant
protected bool m_bIsDormant private
Referenced by EEInit(), StopEffects(), and UpdateGeyserState().
m_bIsErupting
protected bool m_bIsErupting private
Referenced by EEInit(), StopEffects(), and UpdateGeyserState().
m_bIsEruptingTall
protected bool m_bIsEruptingTall private
Referenced by EEInit(), StopEffects(), and UpdateGeyserState().
m_DefaultPosition
protected vector m_DefaultPosition private
Referenced by EEInit(), GetAdjustedPosition(), and RandomizeMouthPos().
m_GeyserParticle
protected ParticleSource m_GeyserParticle private
Referenced by StopEffects(), and UpdateGeyserState().
m_GeyserState
protected EGeyserState m_GeyserState = EGeyserState.DORMANT private
Referenced by AddGeyserState(), GetGeyserState(), OnEnterServerEvent(), RemoveGeyserState(), and UpdateGeyserState().
m_GeyserTallParticle
protected ParticleSource m_GeyserTallParticle private
Referenced by StopEffects(), and UpdateGeyserState().
m_SoundBubbling
protected EffectSound m_SoundBubbling private
Referenced by StopEffects(), and UpdateGeyserState().
m_SoundEruption
protected EffectSound m_SoundEruption private
Referenced by StopEffects(), and UpdateGeyserState().
m_SoundEruptionSecondary
protected EffectSound m_SoundEruptionSecondary private
Referenced by StopEffects(), and UpdateGeyserState().
MOUTH_ADJUST_RADIUS
const float MOUTH_ADJUST_RADIUS = 0.2 private
Referenced by RandomizeMouthPos().
SOUND_BUBBLING
const string SOUND_BUBBLING = "Boiling_Done_SoundSet" private
Referenced by UpdateGeyserState().
SOUND_ERUPTION
const string SOUND_ERUPTION = "pour_Water_Pot_SoundSet" private
Referenced by UpdateGeyserState().
SOUND_ERUPTION_TALL
const string SOUND_ERUPTION_TALL = "pour_Water_WatterBottle_SoundSet" private
Referenced by UpdateGeyserState().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ScriptedEntities/Triggers/GeyserTrigger.c