DayZ Scripts: TemperatureAccessComponent Class Reference
TemperatureAccessComponent Class Reference
Private Member Functions
void TemperatureAccessComponent (EntityAI owner)
bool TryAccessSource (TemperatureData data)
protected bool PriorityCheck (TemperatureData data)
protected bool CheckAccessTimeout (TemperatureData data)
Private Attributes
protected EntityAI m_Owner
protected TemperatureAccessTypeBase m_AccessDataCurrent
protected float m_LastAccessTime
Constructor & Destructor Documentation
TemperatureAccessComponent()
void TemperatureAccessComponent (EntityAI owner) inline private
References m_Owner.
Member Function Documentation
CheckAccessTimeout()
protected bool CheckAccessTimeout (TemperatureData data) inline private
References GetGame(), CGame::GetTickTime(), m_LastAccessTime, and TemperatureData::m_UpdateTimeInfo.
Referenced by TryAccessSource().
PriorityCheck()
protected bool PriorityCheck (TemperatureData data) inline private
References TemperatureAccessTypeBase::GetPriority(), TemperatureAccessManager::GetTAData(), m_AccessDataCurrent, and TemperatureData::m_AccessType.
Referenced by TryAccessSource().
TryAccessSource()
bool TryAccessSource (TemperatureData data) inline private
References CheckAccessTimeout(), GetGame(), TemperatureAccessManager::GetTAData(), CGame::GetTickTime(), m_AccessDataCurrent, TemperatureData::m_AccessType, m_LastAccessTime, and PriorityCheck().
Field Documentation
m_AccessDataCurrent
protected TemperatureAccessTypeBase m_AccessDataCurrent private
Referenced by PriorityCheck(), and TryAccessSource().
m_LastAccessTime
protected float m_LastAccessTime private
Referenced by CheckAccessTimeout(), and TryAccessSource().
m_Owner
protected EntityAI m_Owner private
Referenced by TemperatureAccessComponent().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/TemperatureAccess/TemperatureAccessComponent.c