DayZ Scripts: RightArea Class Reference
RightArea Class Reference
Private Member Functions
void RightArea (LayoutHolder parent)
PlayerContainer GetPlayerContainer ()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override bool Select ()
override bool SelectItem ()
override bool Combine ()
override bool SplitItem ()
override bool EquipItem ()
override bool TransferItem ()
override bool InspectItem ()
override bool TransferItemToVicinity ()
override void UnfocusGrid ()
bool HasEntityContainerVisible (EntityAI entity)
void SwapItemsInOrder (int slot1, int slot2)
bool IsPlayerEquipmentActive ()
override void ExpandCollapseContainer ()
override void Refresh ()
override void SetLayoutName ()
override void SetParentWidget ()
override void OnShow ()
override void UpdateInterval ()
void MoveUpDownIcons ()
override ScrollWidget GetScrollWidget ()
override void UpdateSelectionIcons ()
float GetCurrentContainerTopY ()
float GetCurrentContainerBottomY ()
Private Attributes
ref PlayerContainer m_PlayerContainer
protected Widget m_ContentParent
protected ScrollWidget m_ScrollWidget
protected Widget m_UpIcon
protected Widget m_DownIcon
protected ref SizeToChild m_ContentResize
protected bool m_ShouldChangeSize = true
protected bool m_ProcessGridMovement
Detailed Description
Definition at line 1 of file RightArea.c.
Constructor & Destructor Documentation
RightArea()
void RightArea (LayoutHolder parent) inline private
Definition at line 14 of file RightArea.c.
References GetGame(), GetPlayer(), m_DownIcon, m_PlayerContainer, m_ProcessGridMovement, m_RootWidget, m_ScrollWidget, m_UpIcon, and PlayerContainer::SetPlayer().
Member Function Documentation
Combine()
override bool Combine () inline private
Definition at line 54 of file RightArea.c.
References PlayerContainer::Combine(), and m_PlayerContainer.
Referenced by UpdateInterval().
DraggingOverHeader()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 39 of file RightArea.c.
References PlayerContainer::DraggingOverHeader(), m_PlayerContainer, x, and y.
Referenced by DraggingOverRightPanel().
EquipItem()
override bool EquipItem () inline private
Definition at line 64 of file RightArea.c.
References PlayerContainer::EquipItem(), and m_PlayerContainer.
Referenced by UpdateInterval().
ExpandCollapseContainer()
override void ExpandCollapseContainer () inline private
Definition at line 104 of file RightArea.c.
References PlayerContainer::ExpandCollapseContainer(), and m_PlayerContainer.
Referenced by UpdateInterval().
GetCurrentContainerBottomY()
float GetCurrentContainerBottomY () inline private
Definition at line 218 of file RightArea.c.
References Container::GetFocusedContainerHeight(), Container::GetFocusedContainerYScreenPos(), x, and y.
Referenced by MoveUpDownIcons().
GetCurrentContainerTopY()
float GetCurrentContainerTopY () inline private
Definition at line 208 of file RightArea.c.
References Container::GetFocusedContainerYScreenPos(), x, and y.
Referenced by MoveUpDownIcons().
GetPlayerContainer()
PlayerContainer GetPlayerContainer () inline private
Definition at line 34 of file RightArea.c.
References m_PlayerContainer.
GetScrollWidget()
override ScrollWidget GetScrollWidget () inline private
Definition at line 195 of file RightArea.c.
References m_ScrollWidget.
HasEntityContainerVisible()
bool HasEntityContainerVisible (EntityAI entity) inline private
Definition at line 89 of file RightArea.c.
References PlayerContainer::HasEntityContainerVisible(), and m_PlayerContainer.
InspectItem()
override bool InspectItem () inline private
Definition at line 74 of file RightArea.c.
References PlayerContainer::InspectItem(), and m_PlayerContainer.
Referenced by UpdateInterval().
IsPlayerEquipmentActive()
bool IsPlayerEquipmentActive () inline private
Definition at line 99 of file RightArea.c.
References PlayerContainer::IsPlayerEquipmentActive(), and m_PlayerContainer.
MoveUpDownIcons()
void MoveUpDownIcons () inline private
Definition at line 156 of file RightArea.c.
References Math::Clamp(), GetCurrentContainerBottomY(), GetCurrentContainerTopY(), m_DownIcon, m_IsActive, m_UpIcon, x, and y.
Referenced by UpdateSelectionIcons().
OnShow()
override void OnShow () inline private
Definition at line 142 of file RightArea.c.
References Refresh().
Refresh()
override void Refresh () inline private
Definition at line 109 of file RightArea.c.
References m_PlayerContainer, m_ScrollWidget, m_ShouldChangeSize, and PlayerContainer::Refresh().
Referenced by OnShow(), Refresh(), and Reset().
Select()
override bool Select () inline private
Definition at line 44 of file RightArea.c.
References m_PlayerContainer, and PlayerContainer::Select().
Referenced by UpdateInterval().
SelectItem()
override bool SelectItem () inline private
Definition at line 49 of file RightArea.c.
References m_PlayerContainer, and Container::SelectItem().
Referenced by EnableMicromanagement().
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 116 of file RightArea.c.
References InventoryMenu(), WidgetLayoutName::RightAreaMedium, WidgetLayoutName::RightAreaNarrow, WidgetLayoutName::RightAreaWide, and WidgetLayoutName::RightAreaXbox.
SetParentWidget()
override void SetParentWidget () inline private
Definition at line 137 of file RightArea.c.
References m_Parent, and m_ParentWidget.
SplitItem()
override bool SplitItem () inline private
Definition at line 59 of file RightArea.c.
References m_PlayerContainer, and PlayerContainer::SplitItem().
Referenced by UpdateInterval().
SwapItemsInOrder()
void SwapItemsInOrder (int slot1, int slot2) inline private
Definition at line 94 of file RightArea.c.
References m_PlayerContainer, and PlayerContainer::SwapItemsInOrder().
TransferItem()
override bool TransferItem () inline private
Definition at line 69 of file RightArea.c.
References m_PlayerContainer, and PlayerContainer::TransferItem().
TransferItemToVicinity()
override bool TransferItemToVicinity () inline private
Definition at line 79 of file RightArea.c.
References m_PlayerContainer, and PlayerContainer::TransferItemToVicinity().
Referenced by UpdateInterval().
UnfocusGrid()
override void UnfocusGrid () inline private
Definition at line 84 of file RightArea.c.
References m_PlayerContainer.
Referenced by MoveFocusByArea(), ResetFocusedContainers(), and UpdateInterval().
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 148 of file RightArea.c.
References m_PlayerContainer, and PlayerContainer::UpdateInterval().
Referenced by UpdateInterval().
UpdateSelectionIcons()
override void UpdateSelectionIcons () inline private
Definition at line 200 of file RightArea.c.
References MoveUpDownIcons().
Field Documentation
m_ContentParent
protected Widget m_ContentParent private
Definition at line 4 of file RightArea.c.
m_ContentResize
protected ref SizeToChild m_ContentResize private
Definition at line 10 of file RightArea.c.
m_DownIcon
protected Widget m_DownIcon private
Definition at line 8 of file RightArea.c.
Referenced by MoveUpDownIcons(), and RightArea().
m_PlayerContainer
ref PlayerContainer m_PlayerContainer private
Definition at line 3 of file RightArea.c.
Referenced by Combine(), DraggingOverHeader(), EquipItem(), ExpandCollapseContainer(), GetPlayerContainer(), HasEntityContainerVisible(), InspectItem(), IsPlayerEquipmentActive(), Refresh(), RightArea(), Select(), SelectItem(), SplitItem(), SwapItemsInOrder(), TransferItem(), TransferItemToVicinity(), UnfocusGrid(), and UpdateInterval().
m_ProcessGridMovement
protected bool m_ProcessGridMovement private
Definition at line 12 of file RightArea.c.
Referenced by RightArea().
m_ScrollWidget
protected ScrollWidget m_ScrollWidget private
Definition at line 6 of file RightArea.c.
Referenced by GetScrollWidget(), Refresh(), and RightArea().
m_ShouldChangeSize
protected bool m_ShouldChangeSize = true private
Definition at line 11 of file RightArea.c.
Referenced by Refresh().
m_UpIcon
protected Widget m_UpIcon private
Definition at line 7 of file RightArea.c.
Referenced by MoveUpDownIcons(), and RightArea().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Areas/RightArea.c