DayZ Scripts: P:/scripts/4_world/entities/manbase/dayzplayer/dayzplayercfgbase.c File Reference
dayzplayercfgbase.c File Reference
Data Structures
class DayZPlayerTypeUtils
class HumanItemBehaviorCfg
Functions
void DayZPlayerTypeCreate (DayZPlayerType pType)
void DayZPlayerTypeInitMovement (DayZPlayerType pType)
class DayzPlayerItemBehaviorCfg extends HumanItemBehaviorCfg RegisterEmptyHanded (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void DayzPlayerItemBehaviorCfg ()
void SetIKTwoHanded ()
void SetIKPoleArms ()
void SetPistols ()
void SetFirearms ()
void SetEmptyHanded ()
void SetTwoHanded ()
void SetToolsOneHanded ()
void SetRestrained ()
void SetSurrender ()
void SetHeavyItems ()
void SetPoleArms ()
void RegisterOneHanded (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void RegisterTwoHanded (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void RegisterRestrained (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void RegisterSurrender (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void RegisterHeavy (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void RegisterPistol (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void RegisterFireArms (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void RegisterArcheryItem (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void RegisterPoleArms (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void RegisterLauncher (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
void RegisterCustom (DayZPlayerType pType)
void CustomBoneRemapping (DayZPlayerType pType)
void DayZPlayerTypeRegisterItems (DayZPlayerType pType)
Variables
class DayZPlayerTypeUtils EMPTYHANDED
class DayZPlayerTypeUtils ONEHANDED
class DayZPlayerTypeUtils TWOHANDED
class DayZPlayerTypeUtils PISTOLS
class DayZPlayerTypeUtils FIREARMS
class DayZPlayerTypeUtils HEAVY
class DayZPlayerTypeUtils POLEARMS
Function Documentation
CustomBoneRemapping()
void CustomBoneRemapping (DayZPlayerType pType)
DayzPlayerItemBehaviorCfg()
void DayzPlayerItemBehaviorCfg ()
per item camera user data to be uninitialized
rotational delay to camera direction in move only (filter)
Referenced by DayZPlayerTypeRegisterItems().
DayZPlayerTypeCreate()
void DayZPlayerTypeCreate (DayZPlayerType pType)
References DayZPlayerTypeUtils::DayZPlayerTypeCreate().
DayZPlayerTypeInitMovement()
void DayZPlayerTypeInitMovement (DayZPlayerType pType)
References DayZPlayerTypeUtils::DayZPlayerTypeInitMovement(), and DayZPlayerTypeRegisterItems().
DayZPlayerTypeRegisterItems()
void DayZPlayerTypeRegisterItems (DayZPlayerType pType)
behaviour
set the default - use default instance set + default behaviour - empty hands
reset previous setup
custom emptyhanded - really needed?
complete root of any item not specified here
Pistols (RH,LH IK)
Firearms (RH,LH IK)
Shotguns
Launchers
Archery (RH,LH IK)
Bows
Arrows
Arrows
Launchers
pType.AddItemInHandsProfile("GP25Base", "dz/anims/workspaces/player/player_main/weapons/player_main_m72law.asi", launcherItemBehaviour);
pType.AddItemInHandsProfile("LAWBase", "dz/anims/workspaces/player/player_main/weapons/player_main_m72law.asi", launcherItemBehaviour); pType.AddItemInHandsProfile("M203Base", "dz/anims/workspaces/player/player_main/weapons/player_main_m72law.asi", launcherItemBehaviour); pType.AddItemInHandsProfile("RPG7Base", "dz/anims/workspaces/player/player_main/weapons/player_main_m72law.asi", launcherItemBehaviour);
Ammunition
Boxes
Loose Rounds
Attachments
light
magazine
muzzle
optic
support
Explosives
Tools
Tools two handed
Camping
Camping 1handed
Camping 2handed
Camping heavy
Vehicles
Vehicles 1handed
Vehicles 2handed
Vehicles Heavy
Vehicles heavy
Hatchback
v3s
sedan
Hatchback_02
sedan_02
offroad_02
Consumables
Consumables two handed
Containers
Containers - 2handed
Containers - Heavy
Cooking
Cooking two handed
Crafting
Crafting 2hd
Cultivation
Drinks
Food
Food animal corpses
Food cans
Food fruits
Food meats
Food mushrooms
Food basic
Medical
Medical two handed
Navigation
Optic
Radio
Radio heavy
Traps
Traps two handed
Clothes
Headgear
Belts
Gloves
Shoe
Vest
Clothing attachments (holsters, plates)
Others
Restrained items
Surrender items (dummy!)
custom one handed
custom two handed
custom pole arms
custom restrained
custom surrender - really needed?
custom heavy
custom behaviours
===========================================================
===========================================================
References DayzPlayerItemBehaviorCfg(), GetGame(), CGame::ProfilerStart(), and CGame::ProfilerStop().
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeCreate(), and DayZPlayerTypeInitMovement().
RegisterArcheryItem()
void RegisterArcheryItem (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
RegisterCustom()
void RegisterCustom (DayZPlayerType pType)
RegisterEmptyHanded()
class DayzPlayerItemBehaviorCfg extends HumanItemBehaviorCfg RegisterEmptyHanded (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
RegisterFireArms()
void RegisterFireArms (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
RegisterHeavy()
void RegisterHeavy (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
RegisterLauncher()
void RegisterLauncher (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
RegisterOneHanded()
void RegisterOneHanded (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
RegisterPistol()
void RegisterPistol (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
RegisterPoleArms()
void RegisterPoleArms (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
RegisterRestrained()
void RegisterRestrained (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
RegisterSurrender()
void RegisterSurrender (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
RegisterTwoHanded()
void RegisterTwoHanded (DayZPlayerType pType, DayzPlayerItemBehaviorCfg pBehavior)
SetEmptyHanded()
void SetEmptyHanded ()
SetFirearms()
void SetFirearms ()
SetHeavyItems()
void SetHeavyItems ()
References m_iType, HumanItemBehaviorCfg::SetIK(), HumanItemBehaviorCfg::SetIKMelee(), and HumanItemBehaviorCfg::SetIKStance().
SetIKPoleArms()
void SetIKPoleArms ()
SetIKTwoHanded()
void SetIKTwoHanded ()
SetPistols()
void SetPistols ()
SetPoleArms()
void SetPoleArms ()
SetRestrained()
void SetRestrained ()
SetSurrender()
void SetSurrender ()
SetToolsOneHanded()
void SetToolsOneHanded ()
SetTwoHanded()
void SetTwoHanded ()
Variable Documentation
EMPTYHANDED
class DayZPlayerTypeUtils EMPTYHANDED
FIREARMS
class DayZPlayerTypeUtils FIREARMS
HEAVY
class DayZPlayerTypeUtils HEAVY
ONEHANDED
class DayZPlayerTypeUtils ONEHANDED
PISTOLS
class DayZPlayerTypeUtils PISTOLS
POLEARMS
class DayZPlayerTypeUtils POLEARMS
TWOHANDED
class DayZPlayerTypeUtils TWOHANDED