DayZ Scripts: Hit_Rubber Class Reference
Hit_Rubber Class Reference
Private Member Functions
void Hit_Rubber ()
Constructor & Destructor Documentation
Hit_Rubber()
void Hit_Rubber () inline private
References ParticleList::IMPACT_RUBBER_ENTER, ParticleList::IMPACT_RUBBER_EXIT, ParticleList::IMPACT_RUBBER_RICOCHET, EffBulletImpactBase::SetEnterParticle(), EffBulletImpactBase::SetExitParticle(), and EffBulletImpactBase::SetRicochetParticle().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Effects/EffectParticle/BulletImpactBase/Hit_Rubber.c