DayZ Scripts: CargoBase Class Reference
CargoBase Class Reference
represents base for cargo storage for entities
Private Member Functions
proto native EntityAI GetCargoOwner ()
get the entity that owns the cargo
proto native int GetOwnerCargoIndex ()
proto native bool IsProxyCargo ()
proto native int GetItemCount ()
proto native EntityAI GetItem (int index)
proto native int GetWidth ()
proto native int GetHeight ()
proto bool GetItemRowCol (int index, out int row, out int col)
proto bool GetItemSize (int index, out int w, out int h)
proto native int FindEntityInCargo (notnull EntityAI e)
private void CargoBase ()
private void ~CargoBase ()
bool CanReceiveItemIntoCargo (EntityAI item)
condition EntityAI::CanReceiveItemIntoCargo for Cargo.
bool CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity)
condition EntityAI::CanSwapItemInCargo for Cargo.
proto native int GetUserReservedLocationCount ()
proto bool GetUserReservedLocation (int index, out EntityAI eai, out int row, out int col, out int w, out int h, out int flp)
proto native void SetUserReservedLocation (notnull EntityAI eai)
proto native void ClearUserReservedLocation (notnull EntityAI eai)
Detailed Description
represents base for cargo storage for entities
@NOTE: rows == y axis
Constructor & Destructor Documentation
CargoBase()
private void CargoBase () private
~CargoBase()
private void ~CargoBase () private
Member Function Documentation
CanReceiveItemIntoCargo()
CanReceiveItemIntoCargo (EntityAI item) inline private
condition EntityAI::CanReceiveItemIntoCargo for Cargo.
Returns
true if cargo can be added, false otherwise
CanSwapItemInCargo()
CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity) inline private
condition EntityAI::CanSwapItemInCargo for Cargo.
Returns
true if cargo can be added, false otherwise
ClearUserReservedLocation()
proto native void ClearUserReservedLocation (notnull EntityAI eai) private
FindEntityInCargo()
FindEntityInCargo (notnull EntityAI e) private
Returns
find internal index of the entity in cargo or -1 if not found
GetCargoOwner()
GetCargoOwner () private
get the entity that owns the cargo
Returns
cargo owner
Referenced by VicinityContainer::UpdateInterval().
GetHeight()
GetHeight () private
Returns
height of the cargo
Referenced by ClosableContainer::DraggingOverGrid(), AttachmentCategoriesRow::DraggingOverGrid(), ClosableContainer::DraggingOverGrid(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), ClosableContainer::DropReceived(), and Container::GetMaxCargoCapacity().
GetItem()
GetItem (int index) private
Returns
get item at specific index
Referenced by Container::AddedToCargoEx(), BurnItemsInFireplace(), CookWithEquipment(), InventoryItem::EEHealthLevelChanged(), Container::GetIcon(), Entity::GetInventoryAndCargoWeight(), GetItemTypeFromCargo(), ActionUnpackGift::OnFinishProgressServer(), Container::RemovedFromCargo(), Container::SetEntity(), and TerminateCookingSounds().
GetItemCount()
GetItemCount () private
Returns
number of items in cargo
Referenced by Container::AddedToCargoEx(), ActionTargetsCursor::AttachmentsWithInventoryOrCargoCount(), BurnItemsInFireplace(), InventoryItem::CanReceiveAttachment(), CookWithEquipment(), ClosableContainer::DraggingOverGrid(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), ClosableContainer::DropReceived(), InventoryItem::EEHealthLevelChanged(), Container::GetCargoCapacity(), Container::GetIcon(), Entity::GetInventoryAndCargoWeight(), GetItemTypeFromCargo(), Entity::HasAnyCargo(), ActionUnpackGift::OnFinishProgressServer(), Container::RemovedFromCargo(), Container::SetEntity(), and TerminateCookingSounds().
GetItemRowCol()
GetItemRowCol (int index, out int row, out int col) private
Parameters
[out] row returned row of the item at internal index
[out] col returned col. 0 on xbox
GetItemSize()
GetItemSize (int index, out int w, out int h) private
Parameters
[out] w returned width of the item at internal index
[out] h returned height of the item at internal index
Referenced by Container::GetCargoCapacity().
GetOwnerCargoIndex()
proto native int GetOwnerCargoIndex () private
Referenced by VicinityContainer::UpdateInterval().
GetUserReservedLocation()
GetUserReservedLocation (int index, out EntityAI eai, out int row, out int col, out int w, out int h, out int flp) private
Parameters
[in] idx index of the user reserved location
[out] eai returned entity of the user reservation at internal index
[out] row returned row of the user reservation at internal index
[out] col returned col
[out] w returned width of the user reservation at internal index
[out] h returned height of the user reservation at internal index
[out] flp returned flip
Returns
true if record found, false otherwise
GetUserReservedLocationCount()
proto native int GetUserReservedLocationCount () private
GetWidth()
GetWidth () private
Returns
width of the cargo
Referenced by ClosableContainer::DraggingOverGrid(), AttachmentCategoriesRow::DraggingOverGrid(), ClosableContainer::DraggingOverGrid(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), ClosableContainer::DropReceived(), and Container::GetMaxCargoCapacity().
IsProxyCargo()
IsProxyCargo () private
Returns
true if cargo is in proxy object
SetUserReservedLocation()
proto native void SetUserReservedLocation (notnull EntityAI eai) private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/Inventory/Cargo.c