DayZ Scripts: P:/scripts/4_World/Static/Liquid.c File Reference
Liquid.c File Reference
Data Structures
class LiquidInfo
Functions
static string GetLiquidClassname (int liquid_type)
static bool InitAllLiquids ()
static void Transfer (ItemBase source_ent, ItemBase target_ent, float quantity=-1)
static bool CanTransfer (ItemBase source_ent, ItemBase target_ent)
static void FillContainer (ItemBase container, int liquid_type, float amount)
static void FillContainerEnviro (ItemBase container, int liquid_type, float amount, bool inject_agents=true)
static void AffectContainerOnFill (ItemBase container, int liquid_type, float amount)
static bool IsLiquidDrinkWater (int liquidType)
static int TranslateLiquidType (int liquidType)
Translates 'administrative' liquid types into liquid types with valid config class.
static bool CanFillContainer (ItemBase container, int liquid_type, bool ignore_fullness_check=false)
static float GetLiquidTypeEnviroTemperature (int liquidType)
Gets liquid temperature from the enviroment.
static private string GetLiquidConfigProperty (int liquid_type, string property_name, bool is_nutrition_property=false)
static NutritionalProfile GetNutritionalProfileByType (int liquid_type)
static NutritionalProfile GetNutritionalProfileByName (string class_name)
static NutritionalProfile SetUpNutritionalProfile (int liquid_type, string liquid_class_name)
static int GetAgents (int liquid_type)
static float GetToxicity (int liquid_type)
static float GetWaterContent (int liquid_type)
static float GetEnergy (int liquid_type)
static float GetNutritionalIndex (int liquid_type)
static string GetDisplayName (int liquid_type)
static float GetFlammability (int liquid_type)
static float GetFullness (int liquid_type)
static float GetDigestibility (int liquid_type)
static float GetFreezeThreshold (int liquid_type)
static float GetThawThreshold (int liquid_type)
static float GetBoilThreshold (int liquid_type)
static string GetName (int liquid_type)
Variables
class LiquidInfo int
class LiquidInfo m_AllLiquidsByType = new map<int, ref NutritionalProfile>
static ref map< string, ref NutritionalProfile > m_AllLiquidsByName = new map<string, ref NutritionalProfile>
static ref map< int, ref LiquidInfo > m_LiquidInfosByType = new map<int, ref LiquidInfo>
static ref map< string, ref LiquidInfo > m_LiquidInfosByName = new map<string, ref LiquidInfo>
static bool m_Init = InitAllLiquids()
Function Documentation
AffectContainerOnFill()
static void AffectContainerOnFill (ItemBase container, int liquid_type, float amount) static
Referenced by FillContainerEnviro().
CanFillContainer()
static bool CanFillContainer (ItemBase container, int liquid_type, bool ignore_fullness_check = false) static
Referenced by CanTransfer(), and FillContainer().
CanTransfer()
static bool CanTransfer (ItemBase source_ent, ItemBase target_ent) static
References CanFillContainer(), and Barrel_ColorBase::IsOpen().
FillContainer()
static void FillContainer (ItemBase container, int liquid_type, float amount) static
References CanFillContainer().
Referenced by FillContainerEnviro().
FillContainerEnviro()
static void FillContainerEnviro (ItemBase container, int liquid_type, float amount, bool inject_agents = true) static
References AffectContainerOnFill(), AGT_NONE, AGT_SNOW, AGT_WATER_HOT_SPRING, AGT_WATER_POND, FillContainer(), GetLiquidTypeEnviroTemperature(), GetPlugin(), LIQUID_FRESHWATER, LIQUID_HOTWATER, LIQUID_RIVERWATER, LIQUID_SNOW, LIQUID_STILLWATER, and TranslateLiquidType().
GetAgents()
static int GetAgents (int liquid_type) static
References m_LiquidInfosByType.
GetBoilThreshold()
static float GetBoilThreshold (int liquid_type) static
References m_LiquidInfosByType.
GetDigestibility()
static float GetDigestibility (int liquid_type) static
References m_LiquidInfosByType.
GetDisplayName()
static string GetDisplayName (int liquid_type) static
References m_LiquidInfosByType.
Referenced by CheckContactCache(), ManBase::EEHitBy(), and Entity::InitDamageZoneDisplayNameMapping().
GetEnergy()
static float GetEnergy (int liquid_type) static
References m_LiquidInfosByType.
GetFlammability()
static float GetFlammability (int liquid_type) static
References m_LiquidInfosByType.
GetFreezeThreshold()
static float GetFreezeThreshold (int liquid_type) static
References m_LiquidInfosByType.
GetFullness()
static float GetFullness (int liquid_type) static
References m_LiquidInfosByType.
GetLiquidClassname()
static string GetLiquidClassname (int liquid_type) static
References LiquidInfo::m_LiquidClassName, and m_LiquidInfosByType.
GetLiquidConfigProperty()
static private string GetLiquidConfigProperty (int liquid_type, string property_name, bool is_nutrition_property = false) static
References CGame::ConfigGetChildName(), CGame::ConfigGetInt(), CGame::ConfigGetText(), g_Game, and GetGame().
GetLiquidTypeEnviroTemperature()
static float GetLiquidTypeEnviroTemperature (int liquidType) static
Gets liquid temperature from the enviroment.
Parameters
[in] liquidType Type of liquid.
References GetGame(), WorldData::GetLiquidTypeEnviroTemperature(), CGame::GetMission(), and Mission::GetWorldData().
Referenced by FillContainerEnviro().
GetName()
static string GetName (int liquid_type) static
GetNutritionalIndex()
static float GetNutritionalIndex (int liquid_type) static
References m_LiquidInfosByType.
GetNutritionalProfileByName()
static NutritionalProfile GetNutritionalProfileByName (string class_name) static
References class_name, m_LiquidInfosByName, and LiquidInfo::m_NutriProfile.
GetNutritionalProfileByType()
static NutritionalProfile GetNutritionalProfileByType (int liquid_type) static
References m_LiquidInfosByType, and LiquidInfo::m_NutriProfile.
GetThawThreshold()
static float GetThawThreshold (int liquid_type) static
References m_LiquidInfosByType.
GetToxicity()
static float GetToxicity (int liquid_type) static
References m_LiquidInfosByType.
GetWaterContent()
static float GetWaterContent (int liquid_type) static
References m_LiquidInfosByType.
InitAllLiquids()
static bool InitAllLiquids () static
References CGame::ConfigGetChildName(), CGame::ConfigGetInt(), g_Game, GetGame(), m_AllLiquidsByName, m_AllLiquidsByType, m_LiquidInfosByName, m_LiquidInfosByType, and SetUpNutritionalProfile().
IsLiquidDrinkWater()
static bool IsLiquidDrinkWater (int liquidType) static
References LIQUID_GROUP_DRINKWATER.
Referenced by TranslateLiquidType().
SetUpNutritionalProfile()
static NutritionalProfile SetUpNutritionalProfile (int liquid_type, string liquid_class_name) static
References NutritionalProfile::MarkAsLiquid().
Referenced by InitAllLiquids().
Transfer()
static void Transfer (ItemBase source_ent, ItemBase target_ent, float quantity = -1) static
References AGT_TRANSFER_COPY, Math::Clamp(), GetPlugin(), and Math::Min().
TranslateLiquidType()
static int TranslateLiquidType (int liquidType) static
Translates 'administrative' liquid types into liquid types with valid config class.
References IsLiquidDrinkWater(), and LIQUID_WATER.
Referenced by FillContainerEnviro().
Variable Documentation
int
class LiquidInfo int
m_AllLiquidsByName
ref map<string, ref NutritionalProfile> m_AllLiquidsByName = new map<string, ref NutritionalProfile> static
Referenced by InitAllLiquids().
m_AllLiquidsByType
class LiquidInfo m_AllLiquidsByType = new map<int, ref NutritionalProfile>
Referenced by InitAllLiquids().
m_Init
bool m_Init = InitAllLiquids() static
m_LiquidInfosByName
ref map<string, ref LiquidInfo> m_LiquidInfosByName = new map<string, ref LiquidInfo> static
Referenced by GetNutritionalProfileByName(), and InitAllLiquids().
m_LiquidInfosByType
ref map<int, ref LiquidInfo> m_LiquidInfosByType = new map<int, ref LiquidInfo> static
Referenced by GetAgents(), GetBoilThreshold(), GetDigestibility(), GetDisplayName(), GetEnergy(), GetFlammability(), GetFreezeThreshold(), GetFullness(), GetLiquidClassname(), GetNutritionalIndex(), GetNutritionalProfileByType(), GetThawThreshold(), GetToxicity(), GetWaterContent(), and InitAllLiquids().