DayZ Scripts: Ammo_40mm_Explosive Class Reference
Ammo_40mm_Explosive Class Reference
Private Member Functions
override bool ShootsExplosiveAmmo ()
override void OnActivatedByItem (notnull ItemBase item)
override void EEKilled (Object killer)
override void OnDamageDestroyed (int oldLevel)
Member Function Documentation
EEKilled()
override void EEKilled (Object killer) inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and GetPosition.
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item) inline private
References GetGame().
OnDamageDestroyed()
override void OnDamageDestroyed (int oldLevel) inline private
References ClearFlags().
ShootsExplosiveAmmo()
override bool ShootsExplosiveAmmo () inline private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Magazine/AmmunitionPiles.c