DayZ Scripts: UndergroundAreaLoader Class Reference
UndergroundAreaLoader Class Reference
Static Private Member Functions
static JsonUndergroundTriggers GetData ()
static void SpawnAllTriggerCarriers ()
static void SpawnTriggerCarrier (int index, JsonUndergroundAreaTriggerData data)
static void SyncDataSend (PlayerIdentity identity)
static void OnRPC (ParamsReadContext ctx)
Static Private Attributes
static private string m_Path = "$mission:cfgundergroundtriggers.json"
static ref JsonUndergroundTriggers m_JsonData
Member Function Documentation
GetData()
static JsonUndergroundTriggers GetData () inline static private
References ErrorEx, FileExist(), string::Format(), GetGame(), CGame::GetWorldName(), m_Path, and PrintToRPT().
Referenced by SpawnAllTriggerCarriers().
OnRPC()
static void OnRPC (ParamsReadContext ctx) inline static private
References ErrorEx, m_JsonData, and Serializer::Read().
Referenced by CGame::OnRPC().
SpawnAllTriggerCarriers()
static void SpawnAllTriggerCarriers () inline static private
References GetData(), m_JsonData, SpawnTriggerCarrier(), and JsonUndergroundTriggers::Triggers.
Referenced by MissionBase::OnInit().
SpawnTriggerCarrier()
static void SpawnTriggerCarrier (int index, JsonUndergroundAreaTriggerData data) inline static private
References ECE_NONE, GetGame(), JsonUndergroundAreaTriggerData::GetOrientation(), and JsonUndergroundAreaTriggerData::GetPosition().
Referenced by SpawnAllTriggerCarriers().
SyncDataSend()
static void SyncDataSend (PlayerIdentity identity) inline static private
References GetGame(), m_JsonData, and CGame::RPCSingleParam().
Referenced by MissionBase::OnEvent().
Field Documentation
m_JsonData
ref JsonUndergroundTriggers m_JsonData static private
Referenced by UndergroundTriggerCarrierBase::CanSpawnTrigger(), OnRPC(), SpawnAllTriggerCarriers(), UndergroundTriggerCarrierBase::SpawnTrigger(), and SyncDataSend().
m_Path
private string m_Path = "$mission:cfgundergroundtriggers.json" static private
Referenced by GetData().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/UndergroundAreaLoader.c