DayZ Scripts: ReplaceSoundEventBase Class Reference
ReplaceSoundEventBase Class Reference
Private Member Functions
override protected void SelectSoundID ()
override protected void SelectSoundID ()
ESoundEventType GetSoundEventType ()
EReplaceSoundEventID GetSoundEventID ()
int GetSoundAnimEventClassID ()
void Init (PlayerBase player)
bool Play ()
protected void SelectSoundID ()
Private Attributes
protected ESoundEventType m_EventType
protected EReplaceSoundEventID m_ID
protected int m_SoundAnimEventClassID
protected int m_ReplacedSoundAnimID
protected string m_UserString
protected PlayerBase m_Player
Member Function Documentation
GetSoundAnimEventClassID()
int GetSoundAnimEventClassID () inline private
References m_SoundAnimEventClassID.
Referenced by RegisterEvent().
GetSoundEventID()
EReplaceSoundEventID GetSoundEventID () inline private
References m_ID.
Referenced by GetSoundEventID().
GetSoundEventType()
ESoundEventType GetSoundEventType () inline private
References m_EventType.
Referenced by RegisterEvent().
Init()
void Init (PlayerBase player) inline private
References m_Player.
Referenced by PlayReplaceSound().
Play()
bool Play () inline private
References m_EventType, m_Player, m_ReplacedSoundAnimID, m_UserString, and SelectSoundID().
Referenced by PlayReplaceSound().
SelectSoundID() [1/3]
override protected void SelectSoundID () inline private
References CGame::ConfigGetInt(), GetGame(), DayZPlayer::GetSurfaceType(), m_ID, and m_Player.
Referenced by Play().
SelectSoundID() [2/3]
override protected void SelectSoundID () inline private
References CGame::ConfigGetInt(), GetGame(), DayZPlayer::GetSurfaceType(), m_ID, and m_Player.
SelectSoundID() [3/3]
protected void SelectSoundID () private
Field Documentation
m_EventType
protected ESoundEventType m_EventType private
Referenced by GetSoundEventType(), and Play().
m_ID
protected EReplaceSoundEventID m_ID private
Referenced by GetSoundEventID().
m_Player
protected PlayerBase m_Player private
Referenced by Init(), and Play().
m_ReplacedSoundAnimID
protected int m_ReplacedSoundAnimID private
Referenced by Play().
m_SoundAnimEventClassID
protected int m_SoundAnimEventClassID private
Referenced by GetSoundAnimEventClassID().
m_UserString
protected string m_UserString private
Referenced by Play().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/SoundEvents/ReplaceSoundEvents/Events/ActionSurfaceEvents.c
P:/scripts/4_World/Classes/SoundEvents/ReplaceSoundEvents/ReplaceSoundEventBase.c