DayZ Scripts: ContaminatedArea_Dynamic Class Reference
ContaminatedArea_Dynamic Class Reference
Private Member Functions
void ContaminatedArea_Dynamic ()
override void EEOnCECreate ()
float GetRemainingTime ()
float GetStartDecayLifetime ()
float GetFinishDecayLifetime ()
override void Tick ()
void SetDecayState (int newState)
override void EEInit ()
override void InitZone ()
override void InitZoneServer ()
void SpawnItems ()
override void InitZoneClient ()
override void OnParticleAllocation (ParticleManager pm, array< ParticleSource > particles)
override void CreateTrigger (vector pos, int radius)
void PlayFX ()
void PlayExplosionLight ()
void PlayFlareVFX ()
override void EEDelete (EntityAI parent)
override void OnVariablesSynchronized ()
Private Attributes
protected ref Timer m_StartupTimer
protected ref Timer m_FXTimer
protected FlareLight m_FlareLight
protected ShellLight m_ShellLight
protected vector m_OffsetPos
protected int m_DecayState = eAreaDecayStage.INIT
const int AIRBORNE_EXPLOSION_DELAY = 20
const int AREA_SETUP_DELAY = 10
const float AIRBORNE_FX_OFFSET = 50
const float ARTILLERY_SHELL_SPEED = 100
const float DECAY_START_PART_SIZE = 32
const int DECAY_START_PART_BIRTH_RATE = 1
const float DECAY_END_PART_SIZE = 17
const int DECAY_END_PART_BIRTH_RATE = 1
const float START_DECAY_LIFETIME = 900
const float FINISH_DECAY_LIFETIME = 300
const ref array< string > SPAWN_ITEM_TYPE = {"Grenade_ChemGas"}
const ref array< int > SPAWN_ITEM_COUNT = {Math.RandomIntInclusive(2,5)}
const ref array< float > SPAWN_ITEM_RAD_MIN = {5}
const ref array< float > SPAWN_ITEM_RAD_MAX = {15}
Detailed Description
Definition at line 31 of file ContaminatedArea_Dynamic.c.
Constructor & Destructor Documentation
ContaminatedArea_Dynamic()
void ContaminatedArea_Dynamic () inline private
Definition at line 61 of file ContaminatedArea_Dynamic.c.
Member Function Documentation
CreateTrigger()
override void CreateTrigger (vector pos, int radius) inline private
Definition at line 289 of file ContaminatedArea_Dynamic.c.
References ContaminatedTrigger_Dynamic(), EffectArea::m_AroundParticleID, m_DecayState, EffectArea::m_PPERequesterIdx, EffectArea::m_TinyParticleID, and EffectArea::m_Trigger.
EEDelete()
override void EEDelete (EntityAI parent) inline private
Definition at line 341 of file ContaminatedArea_Dynamic.c.
EEInit()
override void EEInit () inline private
Definition at line 170 of file ContaminatedArea_Dynamic.c.
References AIRBORNE_FX_OFFSET, GetGame(), GetPosition, InitZone(), InitZoneClient(), m_DecayState, EffectArea::m_InnerRings, EffectArea::m_InnerSpacing, EffectArea::m_Name, EffectArea::m_NegativeHeight, m_OffsetPos, EffectArea::m_OuterRingOffset, EffectArea::m_OuterSpacing, EffectArea::m_PositiveHeight, EffectArea::m_Radius, EffectArea::m_ToxicClouds, EffectArea::m_TriggerType, EffectArea::m_Type, and PlayFlareVFX().
EEOnCECreate()
override void EEOnCECreate () inline private
Definition at line 66 of file ContaminatedArea_Dynamic.c.
References AIRBORNE_EXPLOSION_DELAY, AIRBORNE_FX_OFFSET, AREA_SETUP_DELAY, ARTILLERY_SHELL_SPEED, CALL_CATEGORY_GAMEPLAY, vector::Distance(), vector::DistanceSq(), WorldData::GetArtyFiringPos(), GetGame(), CGame::GetMission(), GetPosition, EffectArea::GetRequesterIndex(), Mission::GetWorldData(), m_DecayState, m_FXTimer, m_OffsetPos, EffectArea::m_PPERequesterIdx, EffectArea::m_PPERequesterType, m_StartupTimer, and CGame::RPC().
GetFinishDecayLifetime()
float GetFinishDecayLifetime () inline private
Definition at line 135 of file ContaminatedArea_Dynamic.c.
References FINISH_DECAY_LIFETIME.
Referenced by Tick().
GetRemainingTime()
float GetRemainingTime () inline private
Definition at line 125 of file ContaminatedArea_Dynamic.c.
Referenced by Tick().
GetStartDecayLifetime()
float GetStartDecayLifetime () inline private
Definition at line 130 of file ContaminatedArea_Dynamic.c.
References START_DECAY_LIFETIME.
Referenced by Tick().
InitZone()
override void InitZone () inline private
Definition at line 216 of file ContaminatedArea_Dynamic.c.
References m_DecayState.
Referenced by EEInit().
InitZoneClient()
override void InitZoneClient () inline private
Definition at line 256 of file ContaminatedArea_Dynamic.c.
References GetWorldPosition(), EffectArea::m_InnerRings, EffectArea::m_InnerSpacing, EffectArea::m_OuterRingOffset, EffectArea::m_OuterRingToggle, EffectArea::m_OuterSpacing, EffectArea::m_ParticleID, EffectArea::m_Radius, EffectArea::m_ToxicClouds, and EffectArea::PlaceParticles().
Referenced by EEInit(), and OnVariablesSynchronized().
InitZoneServer()
override void InitZoneServer () inline private
Definition at line 224 of file ContaminatedArea_Dynamic.c.
References CreateTrigger(), EffectArea::m_Position, EffectArea::m_Radius, EffectArea::m_TriggerType, and SpawnItems().
OnParticleAllocation()
override void OnParticleAllocation (ParticleManager pm, array< ParticleSource > particles) inline private
Definition at line 267 of file ContaminatedArea_Dynamic.c.
References DECAY_END_PART_BIRTH_RATE, DECAY_END_PART_SIZE, DECAY_START_PART_BIRTH_RATE, DECAY_START_PART_SIZE, and m_DecayState.
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Definition at line 346 of file ContaminatedArea_Dynamic.c.
References DECAY_END_PART_BIRTH_RATE, DECAY_END_PART_SIZE, DECAY_START_PART_BIRTH_RATE, DECAY_START_PART_SIZE, InitZoneClient(), m_DecayState, EffectArea::m_ToxicClouds, and PlayExplosionLight().
PlayExplosionLight()
void PlayExplosionLight () inline private
Definition at line 324 of file ContaminatedArea_Dynamic.c.
References m_OffsetPos, m_ShellLight, and ShellLight().
Referenced by OnVariablesSynchronized().
PlayFlareVFX()
void PlayFlareVFX () inline private
Definition at line 329 of file ContaminatedArea_Dynamic.c.
References ECE_LOCAL, ECE_SETUP, GetGame(), m_FlareLight, and m_OffsetPos.
Referenced by EEInit().
PlayFX()
void PlayFX () inline private
Definition at line 302 of file ContaminatedArea_Dynamic.c.
References GetGame(), m_DecayState, m_OffsetPos, CGame::RPC(), and vector::Zero.
SetDecayState()
void SetDecayState (int newState) inline private
Definition at line 156 of file ContaminatedArea_Dynamic.c.
References ContaminatedTrigger_Dynamic(), m_DecayState, and EffectArea::m_Trigger.
Referenced by Tick().
SpawnItems()
void SpawnItems () inline private
Definition at line 234 of file ContaminatedArea_Dynamic.c.
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), EffectArea::m_Position, Math3D::MatrixIdentity4(), vector::RandomDir2D(), Math::RandomFloatInclusive(), SPAWN_ITEM_COUNT, SPAWN_ITEM_RAD_MAX, SPAWN_ITEM_RAD_MIN, and SPAWN_ITEM_TYPE.
Referenced by InitZoneServer().
Tick()
override void Tick () inline private
Definition at line 140 of file ContaminatedArea_Dynamic.c.
References GetFinishDecayLifetime(), GetRemainingTime(), GetStartDecayLifetime(), and SetDecayState().
Field Documentation
AIRBORNE_EXPLOSION_DELAY
const int AIRBORNE_EXPLOSION_DELAY = 20 private
Definition at line 41 of file ContaminatedArea_Dynamic.c.
Referenced by EEOnCECreate().
AIRBORNE_FX_OFFSET
const float AIRBORNE_FX_OFFSET = 50 private
Definition at line 43 of file ContaminatedArea_Dynamic.c.
Referenced by EEInit(), and EEOnCECreate().
AREA_SETUP_DELAY
const int AREA_SETUP_DELAY = 10 private
Definition at line 42 of file ContaminatedArea_Dynamic.c.
Referenced by EEOnCECreate().
ARTILLERY_SHELL_SPEED
const float ARTILLERY_SHELL_SPEED = 100 private
Definition at line 44 of file ContaminatedArea_Dynamic.c.
Referenced by EEOnCECreate().
DECAY_END_PART_BIRTH_RATE
const int DECAY_END_PART_BIRTH_RATE = 1 private
Definition at line 50 of file ContaminatedArea_Dynamic.c.
Referenced by OnParticleAllocation(), and OnVariablesSynchronized().
DECAY_END_PART_SIZE
const float DECAY_END_PART_SIZE = 17 private
Definition at line 49 of file ContaminatedArea_Dynamic.c.
Referenced by OnParticleAllocation(), and OnVariablesSynchronized().
DECAY_START_PART_BIRTH_RATE
const int DECAY_START_PART_BIRTH_RATE = 1 private
Definition at line 48 of file ContaminatedArea_Dynamic.c.
Referenced by OnParticleAllocation(), and OnVariablesSynchronized().
DECAY_START_PART_SIZE
const float DECAY_START_PART_SIZE = 32 private
Definition at line 47 of file ContaminatedArea_Dynamic.c.
Referenced by OnParticleAllocation(), and OnVariablesSynchronized().
FINISH_DECAY_LIFETIME
const float FINISH_DECAY_LIFETIME = 300 private
Definition at line 52 of file ContaminatedArea_Dynamic.c.
Referenced by GetFinishDecayLifetime().
m_DecayState
protected int m_DecayState = eAreaDecayStage.INIT private
Definition at line 38 of file ContaminatedArea_Dynamic.c.
Referenced by CreateTrigger(), EEInit(), EEOnCECreate(), InitZone(), OnParticleAllocation(), OnVariablesSynchronized(), PlayFX(), and SetDecayState().
m_FlareLight
protected FlareLight m_FlareLight private
Definition at line 35 of file ContaminatedArea_Dynamic.c.
Referenced by PlayFlareVFX().
m_FXTimer
protected ref Timer m_FXTimer private
Definition at line 34 of file ContaminatedArea_Dynamic.c.
Referenced by EEOnCECreate().
m_OffsetPos
protected vector m_OffsetPos private
Definition at line 37 of file ContaminatedArea_Dynamic.c.
Referenced by EEInit(), EEOnCECreate(), PlayExplosionLight(), PlayFlareVFX(), and PlayFX().
m_ShellLight
protected ShellLight m_ShellLight private
Definition at line 36 of file ContaminatedArea_Dynamic.c.
Referenced by PlayExplosionLight().
m_StartupTimer
protected ref Timer m_StartupTimer private
Definition at line 33 of file ContaminatedArea_Dynamic.c.
Referenced by EEOnCECreate().
SPAWN_ITEM_COUNT
const ref array<int> SPAWN_ITEM_COUNT = {Math.RandomIntInclusive(2,5)} private
Definition at line 56 of file ContaminatedArea_Dynamic.c.
Referenced by SpawnItems().
SPAWN_ITEM_RAD_MAX
const ref array<float> SPAWN_ITEM_RAD_MAX = {15} private
Definition at line 58 of file ContaminatedArea_Dynamic.c.
Referenced by SpawnItems().
SPAWN_ITEM_RAD_MIN
const ref array<float> SPAWN_ITEM_RAD_MIN = {5} private
Definition at line 57 of file ContaminatedArea_Dynamic.c.
Referenced by SpawnItems().
SPAWN_ITEM_TYPE
const ref array<string> SPAWN_ITEM_TYPE = {"Grenade_ChemGas"} private
Definition at line 55 of file ContaminatedArea_Dynamic.c.
Referenced by SpawnItems().
START_DECAY_LIFETIME
const float START_DECAY_LIFETIME = 900 private
Definition at line 51 of file ContaminatedArea_Dynamic.c.
Referenced by GetStartDecayLifetime().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/ContaminatedArea/ContaminatedArea_Dynamic.c