DayZ Scripts: ServerBrowserTabPc Class Reference
ServerBrowserTabPc Class Reference
Private Member Functions
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type)
protected override void LoadExtraEntries (int index)
override void RefreshList ()
private string GetConnEndPoint (CachedServerInfo cachedInfo)
private string GetQueryEndPoint (CachedServerInfo cachedInfo)
Private Attributes
private ref array< ref CachedServerInfo > m_CachedFavoriteServerInfo
Detailed Description
Definition at line 1 of file ServerBrowserFavoritesTabPc.c.
Member Function Documentation
Construct()
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type) inline private
Definition at line 6 of file ServerBrowserFavoritesTabPc.c.
GetConnEndPoint()
private string GetConnEndPoint (CachedServerInfo cachedInfo) inline private
Definition at line 88 of file ServerBrowserFavoritesTabPc.c.
Referenced by LoadExtraEntries().
GetQueryEndPoint()
private string GetQueryEndPoint (CachedServerInfo cachedInfo) inline private
Definition at line 95 of file ServerBrowserFavoritesTabPc.c.
LoadExtraEntries()
protected override void LoadExtraEntries (int index) inline private
Definition at line 14 of file ServerBrowserFavoritesTabPc.c.
References GetConnEndPoint(), m_CachedFavoriteServerInfo, m_Menu, m_OnlineFavServers, m_PageIndex, and m_TotalLoadedServers.
Referenced by ServerBrowserTab::UpdateServerList().
RefreshList()
override void RefreshList () inline private
Definition at line 76 of file ServerBrowserFavoritesTabPc.c.
References AddFavoritesToFilter(), OnlineServices::GetCachedFavServerInfo(), OnlineServices::LoadServers(), m_CurrentFilterInput, m_OnlineFavServers, and GetServersInput::SetFavorited().
Referenced by ServerBrowserTab::ApplyFilters(), and ServerBrowserTab::OnClick().
Field Documentation
m_CachedFavoriteServerInfo
private ref array<ref CachedServerInfo> m_CachedFavoriteServerInfo private
Definition at line 4 of file ServerBrowserFavoritesTabPc.c.
Referenced by LoadExtraEntries().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/NewUI/ServerBrowserMenu/ServerBrowserFavoritesTabPc.c