DayZ Scripts: RecipeCacheData Class Reference
RecipeCacheData Class Reference
Private Member Functions
void RecipeCacheData (int mask)
int GetMask ()
int GetBitCount ()
void SetMask (int mask)
Private Attributes
int m_Mask
int m_BitCount
Constructor & Destructor Documentation
RecipeCacheData()
void RecipeCacheData (int mask) inline private
References SetMask().
Member Function Documentation
GetBitCount()
int GetBitCount () inline private
References m_BitCount.
Referenced by GetBitCountByRecipeID().
GetMask()
int GetMask () inline private
References m_Mask.
Referenced by GetMaskByRecipeID(), and UpdateMask().
SetMask()
void SetMask (int mask) inline private
References Math::GetNumberOfSetBits(), m_BitCount, and m_Mask.
Referenced by RecipeCacheData(), and UpdateMask().
Field Documentation
m_BitCount
int m_BitCount private
Referenced by DebugPrint(), GetBitCount(), and SetMask().
m_Mask
int m_Mask private
Referenced by DebugPrint(), GetMask(), and SetMask().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/Recipes/CacheObject.c