DayZ Scripts: CAContinuousMineRock Class Reference
CAContinuousMineRock Class Reference
Private Member Functions
void CAContinuousMineRock (float time_between_drops)
override bool GetMiningData (ActionData action_data)
Constructor & Destructor Documentation
CAContinuousMineRock()
void CAContinuousMineRock (float time_between_drops) inline private
References CAContinuousMineWood::m_TimeBetweenMaterialDrops.
Member Function Documentation
GetMiningData()
override bool GetMiningData (ActionData action_data) inline private
References Class::CastTo(), RockBase::GetAmountOfDrops(), RockBase::GetDamageToMiningItemEachDrop(), RockBase::GetMaterialAndQuantityMap(), CABase::m_Action, CAContinuousMineWood::m_AdjustedDamageToMiningItemEachDrop, CAContinuousMineWood::m_AmountOfDrops, CAContinuousMineWood::m_DamageToMiningItemEachDrop, ActionData::m_MainItem, CAContinuousMineWood::m_MaterialAndQuantityMap, ActionData::m_Player, and ActionData::m_Target.
The documentation for this class was generated from the following file:
4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousMineRock.c