DayZ Scripts: ActionUncoverHeadBase Class Reference
ActionUncoverHeadBase Class Reference
Private Member Functions
void UncoverHead (PlayerBase target, PlayerBase source)
Member Function Documentation
UncoverHead()
void UncoverHead (PlayerBase target, PlayerBase source) inline private
References Class::CastTo(), HumanInventory::CreateInHands(), ECE_IN_INVENTORY, GameInventory::LocationCreateEntity(), m_SpecialtyWeight, RF_DEFAULT, and InventoryLocation::SetGround().
Referenced by OnFinishProgressServer(), and ActionUncoverHeadTarget::OnFinishProgressServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionUncoverHeadSelf.c