DayZ Scripts: HandEventRemove Class Reference
HandEventRemove Class Reference
Private Member Functions
void HandEventDrop (Man p=null, InventoryLocation src=null)
override void ReadFromContext (ParamsReadContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
override bool CheckRequestEx (InventoryValidation validation)
override bool CanPerformEventEx (InventoryValidation validation)
void HandEventThrow (Man p=null, InventoryLocation src=null)
override void ReadFromContext (ParamsReadContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
void SetForce (vector force)
vector GetForce ()
Private Attributes
bool m_CanPerformDrop
vector m_Force
Member Function Documentation
CanPerformEventEx()
override bool CanPerformEventEx (InventoryValidation validation) inline private
On multiplayer client, if this is the initial call then we are waiting for the server to setup this event still
Singleplayer or server was initial caller
References GetDst(), GetGame(), GetSrcEntity(), InventoryValidation::m_IsJuncture, InventoryValidation::m_IsRemote, m_Player, InventoryValidation::m_Reason, and GameInventory::SetGroundPosByOwner().
CheckRequestEx()
override bool CheckRequestEx (InventoryValidation validation) inline private
Check to see if this is the initial call from the server (but the event originated from a client)
References GetSrcEntity(), IsAuthoritative(), InventoryValidation::m_IsJuncture, m_Player, InventoryValidation::m_Reason, and GameInventory::SetGroundPosByOwner().
GetForce()
vector GetForce () inline private
References m_Force.
HandEventDrop()
void HandEventDrop (Man p = null, InventoryLocation src = null) inline private
References m_EventID.
HandEventThrow()
void HandEventThrow (Man p = null, InventoryLocation src = null) inline private
References Error(), GetSrcEntity(), and m_EventID.
ReadFromContext() [1/2]
override void ReadFromContext (ParamsReadContext ctx) inline private
References OptionalLocationReadFromContext(), and Serializer::Read().
ReadFromContext() [2/2]
override void ReadFromContext (ParamsReadContext ctx) inline private
References Serializer::Read(), InventoryLocation::ReadFromContext(), x, and y.
SetForce()
void SetForce (vector force) inline private
WriteToContext() [1/2]
override void WriteToContext (ParamsWriteContext ctx) inline private
References OptionalLocationWriteToContext(), and Serializer::Write().
WriteToContext() [2/2]
override void WriteToContext (ParamsWriteContext ctx) inline private
References Serializer::Write().
Field Documentation
m_CanPerformDrop
bool m_CanPerformDrop private
m_Force
vector m_Force private
Referenced by GetForce().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/Inventory/Hand_Events.c