DayZ Scripts: 4_World/Entities/Building/Specific/AnniversaryMusicSource.c File Reference
AnniversaryMusicSource.c File Reference
Enumerations
enum EAnniversaryMusicStates { INVALID , LIGHT , INTENSE }
Functions
void AnniversaryMusicSource ()
override void EEDelete (EntityAI parent)
override void OnVariablesSynchronized ()
void UpdateMusic ()
void SetIntenseServer ()
void SetLightServer ()
void SetInvalidServer ()
void PlayIntense ()
void PlayLight ()
void StopAllMusic ()
Variables
enum EAnniversaryMusicStates SOUND_INTENSE = "AnniversaryMusic_Intense_SoundSet"
private const string SOUND_LIGHT = "AnniversaryMusic_Light_SoundSet"
protected EffectSound m_LightAmbientSound
protected EffectSound m_IntenseAmbientSound
protected int m_MusicState
protected int m_MusicStateLocal
Enumeration Type Documentation
EAnniversaryMusicStates
enum EAnniversaryMusicStates
Enumerator
INVALID
LIGHT
INTENSE
Function Documentation
AnniversaryMusicSource()
void AnniversaryMusicSource ()
References EnumTools::GetEnumSize(), m_MusicState, and m_MusicStateLocal.
EEDelete()
override void EEDelete (EntityAI parent)
References SEffectManager::DestroyEffect(), m_IntenseAmbientSound, and m_LightAmbientSound.
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
References m_MusicState, m_MusicStateLocal, and UpdateMusic().
PlayIntense()
void PlayIntense ()
References m_IntenseAmbientSound, m_LightAmbientSound, EffectSound::SoundPlay(), and EffectSound::SoundStop().
Referenced by UpdateMusic().
PlayLight()
void PlayLight ()
References m_IntenseAmbientSound, m_LightAmbientSound, EffectSound::SoundPlay(), and EffectSound::SoundStop().
Referenced by UpdateMusic().
SetIntenseServer()
void SetIntenseServer ()
References m_MusicState.
SetInvalidServer()
void SetInvalidServer ()
References m_MusicState.
SetLightServer()
void SetLightServer ()
References m_MusicState.
StopAllMusic()
void StopAllMusic ()
References m_IntenseAmbientSound, m_LightAmbientSound, and EffectSound::SoundStop().
Referenced by UpdateMusic().
UpdateMusic()
void UpdateMusic ()
References SEffectManager::CreateSound(), GetPosition, m_IntenseAmbientSound, m_LightAmbientSound, m_MusicState, PlayIntense(), PlayLight(), SOUND_INTENSE, SOUND_LIGHT, and StopAllMusic().
Referenced by OnVariablesSynchronized(), and ScriptedWidgetEventHandler::OptionsMenuSounds().
Variable Documentation
m_IntenseAmbientSound
protected EffectSound m_IntenseAmbientSound
Referenced by EEDelete(), PlayIntense(), PlayLight(), StopAllMusic(), and UpdateMusic().
m_LightAmbientSound
protected EffectSound m_LightAmbientSound
Referenced by EEDelete(), PlayIntense(), PlayLight(), StopAllMusic(), and UpdateMusic().
m_MusicState
protected int m_MusicState
Referenced by AnniversaryMusicSource(), OnVariablesSynchronized(), SetIntenseServer(), SetInvalidServer(), SetLightServer(), and UpdateMusic().
m_MusicStateLocal
protected int m_MusicStateLocal
Referenced by AnniversaryMusicSource(), and OnVariablesSynchronized().
SOUND_INTENSE
enum EAnniversaryMusicStates SOUND_INTENSE = "AnniversaryMusic_Intense_SoundSet"
Referenced by UpdateMusic().
SOUND_LIGHT
private const string SOUND_LIGHT = "AnniversaryMusic_Light_SoundSet"
Referenced by UpdateMusic().