DayZ Scripts: ServerBrowserTabConsolePages Class Reference
ServerBrowserTabConsolePages Class Reference
Private Member Functions
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type)
override void OnLoadServersAsyncFinished ()
protected override void LoadEntries (int cur_page_index, GetServersResultRowArray page_entries)
protected override void LoadExtraEntries (int index)
override void RefreshList ()
override bool PassFilter (GetServersResultRow result)
override void PressY ()
override void PressX ()
override void SetFocusFilters ()
Detailed Description
Definition at line 1 of file ServerBrowserFavoritesTabConsolePages.c.
Member Function Documentation
Construct()
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type) inline private
Definition at line 3 of file ServerBrowserFavoritesTabConsolePages.c.
References m_Root.
LoadEntries()
protected override void LoadEntries (int cur_page_index, GetServersResultRowArray page_entries) inline private
Definition at line 20 of file ServerBrowserFavoritesTabConsolePages.c.
References m_OnlineFavServers.
Referenced by ServerBrowserTab::OnLoadServersAsyncConsole().
LoadExtraEntries()
protected override void LoadExtraEntries (int index) inline private
Definition at line 30 of file ServerBrowserFavoritesTabConsolePages.c.
References Math::Ceil(), GetCurrentPage(), m_EntriesSorted, m_EntryWidgets, m_Menu, m_OnlineFavServers, m_SortType, m_TabType, SERVER_BROWSER_PAGE_SIZE, and string::Split().
Referenced by ServerBrowserTab::LoadEntries().
OnLoadServersAsyncFinished()
override void OnLoadServersAsyncFinished () inline private
Definition at line 12 of file ServerBrowserFavoritesTabConsolePages.c.
References m_Menu, and m_TotalLoadedServers.
Referenced by ServerBrowserTab::OnLoadServersAsyncConsole().
PassFilter()
override bool PassFilter (GetServersResultRow result) inline private
Definition at line 110 of file ServerBrowserFavoritesTabConsolePages.c.
References m_Menu, and m_TabType.
Referenced by ServerBrowserTab::LoadEntries().
PressX()
override void PressX () inline private
Definition at line 140 of file ServerBrowserFavoritesTabConsolePages.c.
References GetGame(), GetTime(), and SetCurrentPage().
Referenced by ServerBrowserTab::OnClick().
PressY()
override void PressY () inline private
Definition at line 123 of file ServerBrowserFavoritesTabConsolePages.c.
References m_SelectedPanel.
RefreshList()
override void RefreshList () inline private
Definition at line 100 of file ServerBrowserFavoritesTabConsolePages.c.
References AddFavoritesToFilter(), OnlineServices::LoadServers(), m_CurrentFilterInput, and GetServersInput::SetFavorited().
Referenced by ServerBrowserTab::ApplyFilters(), ServerBrowserTab::LeftRelease(), ServerBrowserTab::OnClick(), ServerBrowserTab::PressX(), and ServerBrowserTab::RightRelease().
SetFocusFilters()
override void SetFocusFilters () inline private
Definition at line 149 of file ServerBrowserFavoritesTabConsolePages.c.
References m_Menu.
Referenced by ServerBrowserTab::Construct(), ServerBrowserTab::Focus(), ServerBrowserTab::OnLoadServersAsyncConsole(), ServerBrowserTab::PressSholderLeft(), and ServerBrowserTab::PressSholderRight().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/NewUI/ServerBrowserMenu/ServerBrowserFavoritesTabConsolePages.c