DayZ Scripts: DayZPlayerImplementJumpClimb Class Reference
DayZPlayerImplementJumpClimb Class Reference
Private Member Functions
void DayZPlayerImplementJumpClimb (DayZPlayerImplement pPlayer)
void JumpOrClimb ()
void CheckAndFinishJump (int pLandType=0)
private bool Climb (SHumanCommandClimbResult pClimbRes)
private void Jump ()
private int GetClimbType (float pHeight)
Private Attributes
bool m_bIsJumpInProgress = false
private DayZPlayerImplement m_Player
Detailed Description
Definition at line 1 of file DayZPlayerImplementJumpClimb.c.
Constructor & Destructor Documentation
DayZPlayerImplementJumpClimb()
void DayZPlayerImplementJumpClimb (DayZPlayerImplement pPlayer) inline private
Definition at line 3 of file DayZPlayerImplementJumpClimb.c.
References m_Player.
Member Function Documentation
CheckAndFinishJump()
void CheckAndFinishJump (int pLandType = 0) inline private
Definition at line 45 of file DayZPlayerImplementJumpClimb.c.
References m_bIsJumpInProgress, and m_Player.
Climb()
private bool Climb (SHumanCommandClimbResult pClimbRes) inline private
Definition at line 54 of file DayZPlayerImplementJumpClimb.c.
References GetClimbType(), and m_Player.
Referenced by JumpOrClimb().
GetClimbType()
private int GetClimbType (float pHeight) inline private
Definition at line 76 of file DayZPlayerImplementJumpClimb.c.
Referenced by Climb(), and JumpOrClimb().
Jump()
private void Jump () inline private
Definition at line 66 of file DayZPlayerImplementJumpClimb.c.
References m_bIsJumpInProgress, and m_Player.
Referenced by JumpOrClimb().
JumpOrClimb()
void JumpOrClimb () inline private
Definition at line 8 of file DayZPlayerImplementJumpClimb.c.
References Climb(), HumanCommandClimb::DoClimbTest(), GetClimbType(), Jump(), m_Player, and SHumanCommandClimbSettings().
Field Documentation
m_bIsJumpInProgress
bool m_bIsJumpInProgress = false private
Definition at line 90 of file DayZPlayerImplementJumpClimb.c.
Referenced by CheckAndFinishJump(), and Jump().
m_Player
private DayZPlayerImplement m_Player private
Definition at line 93 of file DayZPlayerImplementJumpClimb.c.
Referenced by CheckAndFinishJump(), Climb(), DayZPlayerImplementJumpClimb(), Jump(), and JumpOrClimb().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/DayZPlayerImplementJumpClimb.c