DayZ Scripts: ActionCraftBoltsFeather Class Reference
ActionCraftBoltsFeather Class Reference
Private Member Functions
void ActionCraftBoltsFeather ()
override void CreateConditionComponents ()
protected bool IsFeatherType (string itemInHandsType)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Private Attributes
protected bool m_IsFeatherInHands
protected Ammunition_Base m_ResultEntity
Detailed Description
Definition at line 11 of file ActionCraftBoltsFeather.c.
Constructor & Destructor Documentation
ActionCraftBoltsFeather()
void ActionCraftBoltsFeather () inline private
Definition at line 16 of file ActionCraftBoltsFeather.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 39 of file ActionCraftBoltsFeather.c.
References IsFeatherType().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 28 of file ActionCraftBoltsFeather.c.
References m_ConditionItem, and m_ConditionTarget.
IsFeatherType()
protected bool IsFeatherType (string itemInHandsType) inline private
Definition at line 34 of file ActionCraftBoltsFeather.c.
Referenced by ActionCondition(), and OnStartServer().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 61 of file ActionCraftBoltsFeather.c.
References m_IsFeatherInHands, ActionData::m_MainItem, ActionData::m_Player, m_ResultEntity, and ActionData::m_Target.
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
Definition at line 55 of file ActionCraftBoltsFeather.c.
References IsFeatherType(), m_IsFeatherInHands, ActionData::m_MainItem, and m_ResultEntity.
Field Documentation
m_IsFeatherInHands
protected bool m_IsFeatherInHands private
Definition at line 13 of file ActionCraftBoltsFeather.c.
Referenced by OnFinishProgressServer(), and OnStartServer().
m_ResultEntity
protected Ammunition_Base m_ResultEntity private
Definition at line 14 of file ActionCraftBoltsFeather.c.
Referenced by OnFinishProgressServer(), and OnStartServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionCraftBoltsFeather.c