DayZ Scripts: BleedingSourceZone Class Reference
BleedingSourceZone Class Reference
Private Member Functions
void BleedingSourceZone (string selection_name, int bit, vector offset, vector orientation, string bone, int max_time, float flow_modifier, string particle_name)
void SetInvLocation (int inv_slot)
int GetInvLocation ()
void ~BleedingSourceZone ()
string GetSelectionName ()
int GetMaxTime ()
string GetParticleName ()
int GetBit ()
float GetFlowModifier ()
vector GetOrientation ()
vector GetOffset ()
string GetBoneName ()
Private Attributes
string m_FireSelectionName
int m_Bit
vector m_EmitterOffset
vector m_EmitterOrientation
string m_Bone
float m_FlowModifier
int m_MaxTime
string m_ParticleName
int m_InventorySlotLocation
Detailed Description
Definition at line 1 of file BleedingSourceZone.c.
Constructor & Destructor Documentation
BleedingSourceZone()
void BleedingSourceZone (string selection_name, int bit, vector offset, vector orientation, string bone, int max_time, float flow_modifier, string particle_name) inline private
Definition at line 13 of file BleedingSourceZone.c.
References m_Bit, m_Bone, m_EmitterOffset, m_EmitterOrientation, m_FireSelectionName, m_FlowModifier, m_MaxTime, and m_ParticleName.
~BleedingSourceZone()
void ~BleedingSourceZone () inline private
Definition at line 36 of file BleedingSourceZone.c.
Member Function Documentation
GetBit()
int GetBit () inline private
Definition at line 56 of file BleedingSourceZone.c.
References m_Bit.
GetBoneName()
string GetBoneName () inline private
Definition at line 76 of file BleedingSourceZone.c.
References m_Bone.
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
GetFlowModifier()
float GetFlowModifier () inline private
Definition at line 61 of file BleedingSourceZone.c.
References m_FlowModifier.
Referenced by BleedingSourcesManagerBase::AddBleedingSource(), and BleedingSourcesManagerBase::GetMostSignificantBleedingSource().
GetInvLocation()
int GetInvLocation () inline private
Definition at line 31 of file BleedingSourceZone.c.
References m_InventorySlotLocation.
Referenced by BleedingSourcesManagerBase::AddBleedingSource(), BleedingSourcesManagerBase::DisplayDebug(), and BleedingSourcesManagerBase::RemoveBleedingSource().
GetMaxTime()
int GetMaxTime () inline private
Definition at line 46 of file BleedingSourceZone.c.
References m_MaxTime.
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
GetOffset()
vector GetOffset () inline private
Definition at line 71 of file BleedingSourceZone.c.
References m_EmitterOffset.
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
GetOrientation()
vector GetOrientation () inline private
Definition at line 66 of file BleedingSourceZone.c.
References m_EmitterOrientation.
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
GetParticleName()
string GetParticleName () inline private
Definition at line 51 of file BleedingSourceZone.c.
References m_ParticleName.
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
GetSelectionName()
string GetSelectionName () inline private
Definition at line 41 of file BleedingSourceZone.c.
References m_FireSelectionName.
SetInvLocation()
void SetInvLocation (int inv_slot) inline private
Definition at line 26 of file BleedingSourceZone.c.
References m_InventorySlotLocation.
Field Documentation
m_Bit
int m_Bit private
Definition at line 4 of file BleedingSourceZone.c.
Referenced by BleedingSourceZone(), and GetBit().
m_Bone
string m_Bone private
Definition at line 7 of file BleedingSourceZone.c.
Referenced by BleedingSourceZone(), and GetBoneName().
m_EmitterOffset
vector m_EmitterOffset private
Definition at line 5 of file BleedingSourceZone.c.
Referenced by BleedingSourceZone(), and GetOffset().
m_EmitterOrientation
vector m_EmitterOrientation private
Definition at line 6 of file BleedingSourceZone.c.
Referenced by BleedingSourceZone(), and GetOrientation().
m_FireSelectionName
string m_FireSelectionName private
Definition at line 3 of file BleedingSourceZone.c.
Referenced by BleedingSourceZone(), and GetSelectionName().
m_FlowModifier
float m_FlowModifier private
Definition at line 8 of file BleedingSourceZone.c.
Referenced by BleedingSourceZone(), and GetFlowModifier().
m_InventorySlotLocation
int m_InventorySlotLocation private
Definition at line 11 of file BleedingSourceZone.c.
Referenced by GetInvLocation(), and SetInvLocation().
m_MaxTime
int m_MaxTime private
Definition at line 9 of file BleedingSourceZone.c.
Referenced by BleedingSourceZone(), and GetMaxTime().
m_ParticleName
string m_ParticleName private
Definition at line 10 of file BleedingSourceZone.c.
Referenced by BleedingSourceZone(), and GetParticleName().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/BleedingSources/BleedingSourceZone.c