DayZ Scripts: CrashSoundSets Class Reference
CrashSoundSets Class Reference
Static Private Member Functions
static void RegisterSoundSet (string sound_set)
static string GetSoundSetByHash (int hash)
Static Private Attributes
static ref map< int, string > m_Mappings = new map<int, string>
Detailed Description
Definition at line 44 of file DayZGame.c.
Member Function Documentation
GetSoundSetByHash()
static string GetSoundSetByHash (int hash) inline static private
Definition at line 53 of file DayZGame.c.
References m_Mappings.
Referenced by CGame::OnRPC().
RegisterSoundSet()
static void RegisterSoundSet (string sound_set) inline static private
Definition at line 48 of file DayZGame.c.
References string::Hash(), and m_Mappings.
Referenced by House::Init().
Field Documentation
m_Mappings
ref map<int, string> m_Mappings = new map<int, string> static private
Definition at line 46 of file DayZGame.c.
Referenced by GetSoundSetByHash(), and RegisterSoundSet().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/DayZGame.c