DayZ Scripts: ActionUnfoldMapCB Class Reference
ActionUnfoldMapCB Class Reference
Private Member Functions
void ActionUnfoldMapCB ()
void ~ActionUnfoldMapCB ()
override void SetActionData (ActionData action_data)
bool CancelCondition ()
override void OnStateChange (int pOldState, int pCurrentState)
override void OnAnimationEvent (int pEventID)
override void OnFinish (bool pCanceled)
void PerformMapChange ()
bool StateCheck ()
Private Attributes
bool m_MapFolding
bool m_HasReceivedEvent
bool m_CancelCondition
int m_InitMovementState
int m_FinalMovementState
Constructor & Destructor Documentation
ActionUnfoldMapCB()
void ActionUnfoldMapCB () inline private
References EnableCancelCondition(), EnableStateChangeCallback(), RegisterAnimationEvent(), and UA_ANIM_EVENT.
~ActionUnfoldMapCB()
void ~ActionUnfoldMapCB () inline private
References GetGame(), CGame::GetMission(), CfgGameplayHandler::GetUse3DMap(), ActionBaseCB::m_ActionData, Mission::RemoveActiveInputExcludes(), and Mission::RemoveActiveInputRestriction().
Member Function Documentation
CancelCondition()
bool CancelCondition () inline private
References m_CancelCondition.
OnAnimationEvent()
override void OnAnimationEvent (int pEventID) inline private
References ActionBaseCB::m_ActionData, m_CancelCondition, m_FinalMovementState, m_HasReceivedEvent, PerformMapChange(), StateCheck(), and UA_ANIM_EVENT.
OnFinish()
override void OnFinish (bool pCanceled) inline private
References ActionUnfoldMap(), UIManager::FindMenu(), GetGame(), CGame::GetUIManager(), ActionBaseCB::m_ActionData, m_FinalMovementState, m_InitMovementState, and MENU_MAP.
OnStateChange()
override void OnStateChange (int pOldState, int pCurrentState) inline private
References ActionBaseCB::m_ActionData, m_CancelCondition, m_HasReceivedEvent, STATE_LOOP_IN, and STATE_LOOP_LOOP.
PerformMapChange()
void PerformMapChange () inline private
References Mission::AddActiveInputExcludes(), Mission::AddActiveInputRestriction(), UIManager::CloseAll(), UIManager::EnterScriptedMenu(), GetGame(), CGame::GetMission(), CGame::GetUIManager(), CfgGameplayHandler::GetUse3DMap(), UIScriptedMenu::InitMapItem(), UIScriptedMenu::LoadMapMarkers(), ActionBaseCB::m_ActionData, m_CancelCondition, m_MapFolding, and MENU_MAP.
Referenced by OnAnimationEvent().
SetActionData()
override void SetActionData (ActionData action_data) inline private
References ActionBaseCB::m_ActionData, and m_InitMovementState.
StateCheck()
bool StateCheck () inline private
References m_FinalMovementState, and m_InitMovementState.
Referenced by OnAnimationEvent().
Field Documentation
m_CancelCondition
bool m_CancelCondition private
Referenced by CancelCondition(), OnAnimationEvent(), OnStateChange(), and PerformMapChange().
m_FinalMovementState
int m_FinalMovementState private
Referenced by OnAnimationEvent(), OnFinish(), and StateCheck().
m_HasReceivedEvent
bool m_HasReceivedEvent private
Referenced by OnAnimationEvent(), and OnStateChange().
m_InitMovementState
int m_InitMovementState private
Referenced by OnFinish(), SetActionData(), and StateCheck().
m_MapFolding
bool m_MapFolding private
Referenced by PerformMapChange().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionUnfoldMap.c