DayZ Scripts: InputUtils Class Reference
InputUtils Class Reference
Static Private Member Functions
static string GetButtonNameFromInput (string pInputName, int pInputDeviceType)
static map< int, ref TStringArray > GetComboButtonNamesFromInput (string pInputName, int pInputDeviceType)
returns a map of button names, combo or not
static array< string > GetButtonIconPathFromInput (notnull UAInput pInput, int pInputDeviceType=EUAINPUT_DEVICE_CONTROLLER)
static array< string > GetButtonIconPathFromInput (string pInputName, int pInputDeviceType)
static void GetImagesetAndIconFromInputAction (notnull UAInput pInput, int pInputDeviceType, out array< string > pImageSet, out array< string > pIconName)
static void GetImagesetAndIconFromInputAction (string pInputAction, int pInputDeviceType, out array< string > pImageSet, out array< string > pIconName)
static string GetRichtextButtonIconFromInputAction (notnull UAInput pInput, string pLocalizedDescription, int pInputDeviceType=EUAINPUT_DEVICE_CONTROLLER, float pScale=ICON_SCALE_NORMAL, bool pVertical=false)
static string GetRichtextButtonIconFromInputAction (string pInputAction, string pLocalizedDescription, int pInputDeviceType=EUAINPUT_DEVICE_CONTROLLER, float pScale=ICON_SCALE_NORMAL, bool pVertical=false)
static void UpdateConsolePresetID ()
static int GetConsolePresetID ()
static map< int, ref array< int > > GetInputActionSortingMap ()
static array< int > GetUnsortedInputActions ()
static bool InitInputMetadata ()
Static Private Attributes
static const string PRESET_OLD = "#STR_UAPRESET_0"
static const string PRESET_NEW = "#STR_UAPRESET_1"
static const int VARIANT_OLD = 0
static const int VARIANT_NEW = 1
static int m_CurrentPresetIDConsole = -1
static protected ref map< int, ref array< int > > m_InputActionSortingMap
static protected ref array< int > m_UnsortedInputActions
static const float ICON_SCALE_NORMAL = 1.21
static const float ICON_SCALE_TOOLBAR = 1.81
Member Function Documentation
GetButtonIconPathFromInput() [1/2]
static array< string > GetButtonIconPathFromInput (notnull UAInput pInput, int pInputDeviceType = EUAINPUT_DEVICE_CONTROLLER) inline static private
References GetUApi().
Referenced by GetButtonIconPathFromInput(), and GetImagesetAndIconFromInputAction().
GetButtonIconPathFromInput() [2/2]
static array< string > GetButtonIconPathFromInput (string pInputName, int pInputDeviceType) inline static private
References GetButtonIconPathFromInput(), UAInputAPI::GetInputByName(), and GetUApi().
GetButtonNameFromInput()
static string GetButtonNameFromInput (string pInputName, int pInputDeviceType) inline static private
References UAInput::AlternativeCount(), UAInput::CheckBindDevice(), UAInput::GetBindKey(), UAInputAPI::GetButtonName(), UAInputAPI::GetInputByName(), GetUApi(), and UAInput::SelectAlternative().
Referenced by ActionTargetsCursor::SetInteractActionIcon().
GetComboButtonNamesFromInput()
static map< int, ref TStringArray > GetComboButtonNamesFromInput (string pInputName, int pInputDeviceType) inline static private
returns a map of button names, combo or not
References UAInput::AlternativeCount(), UAInput::Binding(), UAInput::BindingCount(), UAInput::CheckBindDevice(), UAInput::GetBindKey(), UAInputAPI::GetInputByName(), GetUApi(), UAInput::IsCombo(), and UAInput::SelectAlternative().
Referenced by GetBoundButtonText().
GetConsolePresetID()
static int GetConsolePresetID () inline static private
References m_CurrentPresetIDConsole.
Referenced by UIScriptedMenu::UpdateTabContent().
GetImagesetAndIconFromInputAction() [1/2]
static void GetImagesetAndIconFromInputAction (notnull UAInput pInput, int pInputDeviceType, out array< string > pImageSet, out array< string > pIconName) inline static private
Asia vs Europe/N.America controller layout
References GetButtonIconPathFromInput(), GetGame(), and GetInput().
Referenced by GetImagesetAndIconFromInputAction(), GetRichtextButtonIconFromInputAction(), and GetRichtextButtonIconFromInputAction().
GetImagesetAndIconFromInputAction() [2/2]
static void GetImagesetAndIconFromInputAction (string pInputAction, int pInputDeviceType, out array< string > pImageSet, out array< string > pIconName) inline static private
References GetImagesetAndIconFromInputAction(), UAInputAPI::GetInputByName(), and GetUApi().
GetInputActionSortingMap()
static map< int, ref array< int > > GetInputActionSortingMap () inline static private
References m_InputActionSortingMap.
Referenced by array::AddSubgroup(), array::CreateSubgroups(), and UIScriptedMenu::CreateTabs().
GetRichtextButtonIconFromInputAction() [1/2]
static string GetRichtextButtonIconFromInputAction (notnull UAInput pInput, string pLocalizedDescription, int pInputDeviceType = EUAINPUT_DEVICE_CONTROLLER, float pScale = ICON_SCALE_NORMAL, bool pVertical = false) inline static private
first element is already taken
References string::Format(), and GetImagesetAndIconFromInputAction().
Referenced by GetRichtextButtonIconFromInputAction(), Init(), LoginScreenBase::Init(), UIScriptedMenu::Init(), Inventory(), ActionTargetsCursor::SetControllerIcon(), ScriptedWidgetEventHandler::SetControllerIcon(), UIScriptedMenu::UpdateControlsElements(), WarningMenuBase::UpdateControlsElements(), ScriptedWidgetEventHandler::UpdateControlsElements(), and UIScriptedMenu::UpdateInfoPanelText().
GetRichtextButtonIconFromInputAction() [2/2]
static string GetRichtextButtonIconFromInputAction (string pInputAction, string pLocalizedDescription, int pInputDeviceType = EUAINPUT_DEVICE_CONTROLLER, float pScale = ICON_SCALE_NORMAL, bool pVertical = false) inline static private
References GetImagesetAndIconFromInputAction(), UAInputAPI::GetInputByName(), GetRichtextButtonIconFromInputAction(), and GetUApi().
GetUnsortedInputActions()
static array< int > GetUnsortedInputActions () inline static private
References m_UnsortedInputActions.
Referenced by array::AddSubgroup(), array::CreateSubgroups(), and UIScriptedMenu::CreateTabs().
InitInputMetadata()
static bool InitInputMetadata () inline static private
References UAInputAPI::GetActiveInputs(), UAInputAPI::GetInputByID(), GetUApi(), UAInput::HasSorting(), m_InputActionSortingMap, m_UnsortedInputActions, and UAInputAPI::SortingCount().
Referenced by UIScriptedMenu::InitInputSortingMap().
UpdateConsolePresetID()
static void UpdateConsolePresetID () inline static private
References GetGame(), CGame::GetInput(), Input::GetProfileName(), GetUApi(), m_CurrentPresetIDConsole, PRESET_OLD, VARIANT_NEW, and VARIANT_OLD.
Referenced by UIScriptedMenu::ComposeData(), and UIScriptedMenu::PerformSwitchPreset().
Field Documentation
ICON_SCALE_NORMAL
const float ICON_SCALE_NORMAL = 1.21 static private
ICON_SCALE_TOOLBAR
const float ICON_SCALE_TOOLBAR = 1.81 static private
Referenced by Init(), LoginScreenBase::Init(), UIScriptedMenu::Init(), UIScriptedMenu::UpdateControlsElements(), WarningMenuBase::UpdateControlsElements(), ScriptedWidgetEventHandler::UpdateControlsElements(), and UIScriptedMenu::UpdateInfoPanelText().
m_CurrentPresetIDConsole
int m_CurrentPresetIDConsole = -1 static private
Referenced by GetConsolePresetID(), and UpdateConsolePresetID().
m_InputActionSortingMap
protected ref map<int, ref array<int> > m_InputActionSortingMap static private
Referenced by GetInputActionSortingMap(), and InitInputMetadata().
m_UnsortedInputActions
protected ref array<int> m_UnsortedInputActions static private
Referenced by GetUnsortedInputActions(), and InitInputMetadata().
PRESET_NEW
const string PRESET_NEW = "#STR_UAPRESET_1" static private
Referenced by UIScriptedMenu::UpdateToolbarText().
PRESET_OLD
const string PRESET_OLD = "#STR_UAPRESET_0" static private
Referenced by UpdateConsolePresetID(), and UIScriptedMenu::UpdateToolbarText().
VARIANT_NEW
const int VARIANT_NEW = 1 static private
Referenced by UpdateConsolePresetID().
VARIANT_OLD
const int VARIANT_OLD = 0 static private
Referenced by UpdateConsolePresetID().
The documentation for this class was generated from the following file:
P:/scripts/3_game/tools/inpututils.c