DayZ Scripts: ActionContinuousBase Class Reference
ActionContinuousBase Class Reference
Private Member Functions
void ActionContinuousBase ()
override void OnEndInput (ActionData action_data)
bool HasAlternativeInterrupt ()
override GetInputType ()
override int GetActionCategory ()
void OnStartAnimationLoop (ActionData action_data)
void OnEndAnimationLoop (ActionData action_data)
void OnFinishProgress (ActionData action_data)
protected void OnStartAnimationLoopServer (ActionData action_data)
protected void OnStartAnimationLoopClient (ActionData action_data)
protected void OnEndAnimationLoopServer (ActionData action_data)
protected void OnEndAnimationLoopClient (ActionData action_data)
protected void OnFinishProgressServer (ActionData action_data)
protected void OnFinishProgressClient (ActionData action_data)
Private Attributes
PluginAdminLog m_AdminLog
Detailed Description
Definition at line 131 of file ActionContinuousBase.c.
Constructor & Destructor Documentation
ActionContinuousBase()
void ActionContinuousBase () inline private
Definition at line 135 of file ActionContinuousBase.c.
References GetGame(), GetPlugin(), m_AdminLog, AnimatedActionBase::m_CallbackClass, and AnimatedActionBase::m_CommandUID.
Member Function Documentation
GetActionCategory()
override int GetActionCategory () inline private
Definition at line 168 of file ActionContinuousBase.c.
References AC_CONTINUOUS.
GetInputType()
override GetInputType () inline private
Definition at line 163 of file ActionContinuousBase.c.
References ContinuousDefaultActionInput().
HasAlternativeInterrupt()
bool HasAlternativeInterrupt () inline private
Definition at line 158 of file ActionContinuousBase.c.
Referenced by ActionContinuousBaseCB::EndActionComponent(), and EndActionComponent().
OnEndAnimationLoop()
void OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 191 of file ActionContinuousBase.c.
References Debug::ActionLog(), GetGame(), LogManager::IsActionLogEnable(), ActionData::m_Player, ActionData::m_WasExecuted, OnEndAnimationLoopClient(), and OnEndAnimationLoopServer().
Referenced by ActionContinuousBaseCB::CancelCondition().
OnEndAnimationLoopClient()
protected void OnEndAnimationLoopClient (ActionData action_data) inline private
Definition at line 244 of file ActionContinuousBase.c.
Referenced by OnEndAnimationLoop().
OnEndAnimationLoopServer()
protected void OnEndAnimationLoopServer (ActionData action_data) inline private
Definition at line 241 of file ActionContinuousBase.c.
Referenced by OnEndAnimationLoop().
OnEndInput()
override void OnEndInput (ActionData action_data) inline private
Definition at line 146 of file ActionContinuousBase.c.
References Class::CastTo(), ActionData::m_Callback, and ActionContinuousBaseCB::UserEndsAction().
OnFinishProgress()
void OnFinishProgress (ActionData action_data) inline private
Definition at line 208 of file ActionContinuousBase.c.
References Debug::ActionLog(), GetGame(), LogManager::IsActionLogEnable(), m_AdminLog, ActionData::m_Player, ActionData::m_WasExecuted, OnFinishProgressClient(), and OnFinishProgressServer().
Referenced by CAContinuousBase::OnCompletePogress().
OnFinishProgressClient()
protected void OnFinishProgressClient (ActionData action_data) inline private
Definition at line 252 of file ActionContinuousBase.c.
Referenced by OnFinishProgress().
OnFinishProgressServer()
protected void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 248 of file ActionContinuousBase.c.
Referenced by OnFinishProgress().
OnStartAnimationLoop()
void OnStartAnimationLoop (ActionData action_data) inline private
Definition at line 173 of file ActionContinuousBase.c.
References Debug::ActionLog(), GetGame(), LogManager::IsActionLogEnable(), ActionData::m_Player, ActionData::m_WasExecuted, OnStartAnimationLoopClient(), and OnStartAnimationLoopServer().
Referenced by ActionContinuousBaseCB::CancelCondition().
OnStartAnimationLoopClient()
protected void OnStartAnimationLoopClient (ActionData action_data) inline private
Definition at line 236 of file ActionContinuousBase.c.
References ActionData::m_WasActionStarted.
Referenced by OnStartAnimationLoop().
OnStartAnimationLoopServer()
protected void OnStartAnimationLoopServer (ActionData action_data) inline private
Definition at line 231 of file ActionContinuousBase.c.
References ActionData::m_WasActionStarted.
Referenced by OnStartAnimationLoop().
Field Documentation
m_AdminLog
PluginAdminLog m_AdminLog private
Definition at line 133 of file ActionContinuousBase.c.
Referenced by ActionContinuousBase(), and OnFinishProgress().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/ActionContinuousBase.c