DayZ Scripts: WeaponDebug Class Reference
WeaponDebug Class Reference
Private Member Functions
Weapon GetWeaponInHands ()
void WeaponDebug ()
void ~WeaponDebug ()
void RemoveAllShapes (bool is_exit=false)
void OnCommandHandlerUpdate ()
void OnKeyDown (KeyCode key)
void CycleDebugMode ()
void OnPostFrameUpdate ()
void DrawBarrelMemoryPoints (vector begin_point, vector end_point)
void DrawLineOfFire (vector begin_point, vector end_point)
void AddPosToCyclicBuffer (vector pos)
void OrderTrailArray ()
void DrawEyePoint (Weapon weapon)
vector GetEyePointPosition (Weapon weapon)
void DisplayGeneralInfo ()
void DisplayTargetInfo ()
void DrawLineOfFireMuzzleToHit (vector begin_point, vector camera_dir, vector camera_pos)
void DrawLineOfFireCameraHybrid (vector usti_hlavne_position, vector camera_dir, vector camera_pos, vector konec_hlavne_position)
Private Attributes
const int BUFFER_SIZE = 1000
const float COLLISIONS_DISTANCE_TOLERANCE = 0.01
const float MAX_MUZZLE_DISTANCE_TOLERANCE = 20
const float CAMERA_BULLET_ORIGIN_OFFSET = 1
const float CAMERA_TRACE_MIN_DISTANCE_TOLERANCE = 0.3
Weapon m_WeaponInHands
int m_BufferIndex
bool m_IsDrawKeyHeldDown
bool m_IsLMBPressed
bool m_IsToggleKeyPressed
bool m_IsFireKeyPressed
float m_TargetDistance
eDebugMode m_CurrentMode
vector m_AimTrailCyclic [BUFFER_SIZE]
vector m_AimTrailOrdered [BUFFER_SIZE]
ref map< int, string > m_DebugModesNames = new map<int, string>
Shape m_Shape_usti
Shape m_Shape_konec
Shape m_ShapeFireDirection1
Shape m_ShapeFireDirection2
Shape m_HitShape
Shape m_ShapeEye
Shape m_ShapeTrailLines
Shape m_ShapeFireDirCamera
Shape m_HitShape2
Shape m_HitShape3
Shape m_HitShape4
Shape m_PermanentLine1
Shape m_PermanentLine2
Shape m_PermanentShape1
Shape m_PermanentShape2
Detailed Description
Definition at line 11 of file WeaponDebug.c.
Constructor & Destructor Documentation
WeaponDebug()
void WeaponDebug () inline private
Definition at line 61 of file WeaponDebug.c.
References m_DebugModesNames.
~WeaponDebug()
void ~WeaponDebug () inline private
Definition at line 68 of file WeaponDebug.c.
References RemoveAllShapes().
Member Function Documentation
AddPosToCyclicBuffer()
void AddPosToCyclicBuffer (vector pos) inline private
Definition at line 241 of file WeaponDebug.c.
References BUFFER_SIZE, m_AimTrailCyclic, and m_BufferIndex.
Referenced by OnPostFrameUpdate().
CycleDebugMode()
void CycleDebugMode () inline private
Definition at line 146 of file WeaponDebug.c.
References m_CurrentMode.
Referenced by OnCommandHandlerUpdate().
DisplayGeneralInfo()
void DisplayGeneralInfo () inline private
Definition at line 285 of file WeaponDebug.c.
References DbgUI::Begin(), DbgUI::End(), GetGame(), GetPlayer(), m_CurrentMode, m_DebugModesNames, DbgUI::Text(), and float::ToString().
Referenced by OnPostFrameUpdate().
DisplayTargetInfo()
void DisplayTargetInfo () inline private
Definition at line 299 of file WeaponDebug.c.
References DbgUI::Begin(), DbgUI::End(), m_TargetDistance, DbgUI::Text(), and float::ToString().
Referenced by OnPostFrameUpdate().
DrawBarrelMemoryPoints()
void DrawBarrelMemoryPoints (vector begin_point, vector end_point) inline private
Definition at line 206 of file WeaponDebug.c.
References Debug::DrawSphere(), Colors::GREEN, m_IsDrawKeyHeldDown, m_Shape_konec, and m_Shape_usti.
Referenced by OnPostFrameUpdate().
DrawEyePoint()
void DrawEyePoint (Weapon weapon) inline private
Definition at line 266 of file WeaponDebug.c.
References COLOR_BLUE, Debug::DrawSphere(), GetEyePointPosition(), and m_ShapeEye.
Referenced by OnPostFrameUpdate().
DrawLineOfFire()
void DrawLineOfFire (vector begin_point, vector end_point) inline private
Definition at line 216 of file WeaponDebug.c.
References COLOR_RED, Debug::DrawLine(), Debug::DrawSphere(), m_HitShape, m_IsFireKeyPressed, m_PermanentLine1, m_ShapeFireDirection1, m_ShapeFireDirection2, vector::Normalized(), DayZPhysics::RaycastRV(), Colors::RED, and Debug::RemoveShape().
Referenced by OnPostFrameUpdate().
DrawLineOfFireCameraHybrid()
void DrawLineOfFireCameraHybrid (vector usti_hlavne_position, vector camera_dir, vector camera_pos, vector konec_hlavne_position) inline private
Definition at line 354 of file WeaponDebug.c.
References CAMERA_BULLET_ORIGIN_OFFSET, CAMERA_TRACE_MIN_DISTANCE_TOLERANCE, Class::CastTo(), Math::Clamp(), vector::Distance(), Debug::DrawLine(), Debug::DrawSphere(), GetGame(), CGame::GetPlayer(), Colors::GREEN, Math::InverseLerp(), Math::Lerp(), m_HitShape, m_HitShape4, m_IsFireKeyPressed, m_PermanentLine1, m_PermanentLine2, m_PermanentShape1, m_TargetDistance, MAX_MUZZLE_DISTANCE_TOLERANCE, vector::Normalize(), PrintString(), DayZPhysics::RaycastRV(), Colors::RED, and Debug::RemoveShape().
Referenced by OnPostFrameUpdate().
DrawLineOfFireMuzzleToHit()
void DrawLineOfFireMuzzleToHit (vector begin_point, vector camera_dir, vector camera_pos) inline private
Definition at line 307 of file WeaponDebug.c.
References Class::CastTo(), COLOR_RED, vector::Distance(), Debug::DrawLine(), Debug::DrawSphere(), GetGame(), CGame::GetPlayer(), Colors::GREEN, m_HitShape2, m_HitShape3, m_IsFireKeyPressed, m_PermanentLine1, m_PermanentLine2, m_ShapeFireDirCamera, m_TargetDistance, DayZPhysics::RaycastRV(), Colors::RED, and Debug::RemoveShape().
Referenced by OnPostFrameUpdate().
GetEyePointPosition()
vector GetEyePointPosition (Weapon weapon) inline private
Definition at line 272 of file WeaponDebug.c.
Referenced by DrawEyePoint().
GetWeaponInHands()
Weapon GetWeaponInHands () inline private
Definition at line 52 of file WeaponDebug.c.
References Class::CastTo(), GetGame(), and GetPlayer().
Referenced by OnPostFrameUpdate().
OnCommandHandlerUpdate()
void OnCommandHandlerUpdate () inline private
Definition at line 98 of file WeaponDebug.c.
References ClearKey(), CycleDebugMode(), GetMouseState(), KeyState(), m_IsDrawKeyHeldDown, m_IsFireKeyPressed, m_IsLMBPressed, and OnKeyDown().
OnKeyDown()
void OnKeyDown (KeyCode key) inline private
Definition at line 139 of file WeaponDebug.c.
Referenced by OnCommandHandlerUpdate().
OnPostFrameUpdate()
void OnPostFrameUpdate () inline private
Definition at line 156 of file WeaponDebug.c.
References AddPosToCyclicBuffer(), BUFFER_SIZE, COLOR_YELLOW, DisplayGeneralInfo(), DisplayTargetInfo(), DrawBarrelMemoryPoints(), DrawEyePoint(), DrawLineOfFire(), DrawLineOfFireCameraHybrid(), DrawLineOfFireMuzzleToHit(), Debug::DrawLines(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), GetWeaponInHands(), m_AimTrailOrdered, m_CurrentMode, m_IsDrawKeyHeldDown, m_ShapeTrailLines, OrderTrailArray(), and RemoveAllShapes().
OrderTrailArray()
void OrderTrailArray () inline private
Definition at line 251 of file WeaponDebug.c.
References BUFFER_SIZE, m_AimTrailCyclic, m_AimTrailOrdered, and m_BufferIndex.
Referenced by OnPostFrameUpdate().
RemoveAllShapes()
void RemoveAllShapes (bool is_exit = false) inline private
Definition at line 74 of file WeaponDebug.c.
References m_HitShape, m_HitShape2, m_HitShape3, m_HitShape4, m_PermanentLine1, m_PermanentLine2, m_PermanentShape1, m_PermanentShape2, m_Shape_konec, m_Shape_usti, m_ShapeEye, m_ShapeFireDirCamera, m_ShapeFireDirection1, m_ShapeFireDirection2, m_ShapeTrailLines, and Debug::RemoveShape().
Referenced by OnPostFrameUpdate(), and ~WeaponDebug().
Field Documentation
BUFFER_SIZE
const int BUFFER_SIZE = 1000 private
Definition at line 13 of file WeaponDebug.c.
Referenced by AddPosToCyclicBuffer(), OnPostFrameUpdate(), and OrderTrailArray().
CAMERA_BULLET_ORIGIN_OFFSET
const float CAMERA_BULLET_ORIGIN_OFFSET = 1 private
Definition at line 16 of file WeaponDebug.c.
Referenced by DrawLineOfFireCameraHybrid().
CAMERA_TRACE_MIN_DISTANCE_TOLERANCE
const float CAMERA_TRACE_MIN_DISTANCE_TOLERANCE = 0.3 private
Definition at line 17 of file WeaponDebug.c.
Referenced by DrawLineOfFireCameraHybrid().
COLLISIONS_DISTANCE_TOLERANCE
const float COLLISIONS_DISTANCE_TOLERANCE = 0.01 private
Definition at line 14 of file WeaponDebug.c.
m_AimTrailCyclic
vector m_AimTrailCyclic[BUFFER_SIZE] private
Definition at line 27 of file WeaponDebug.c.
Referenced by AddPosToCyclicBuffer(), and OrderTrailArray().
m_AimTrailOrdered
vector m_AimTrailOrdered[BUFFER_SIZE] private
Definition at line 28 of file WeaponDebug.c.
Referenced by OnPostFrameUpdate(), and OrderTrailArray().
m_BufferIndex
int m_BufferIndex private
Definition at line 20 of file WeaponDebug.c.
Referenced by AddPosToCyclicBuffer(), and OrderTrailArray().
m_CurrentMode
eDebugMode m_CurrentMode private
Definition at line 26 of file WeaponDebug.c.
Referenced by CycleDebugMode(), DisplayGeneralInfo(), and OnPostFrameUpdate().
m_DebugModesNames
ref map<int, string> m_DebugModesNames = new map<int, string> private
Definition at line 30 of file WeaponDebug.c.
Referenced by DisplayGeneralInfo(), and WeaponDebug().
m_HitShape
Shape m_HitShape private
Definition at line 38 of file WeaponDebug.c.
Referenced by DrawLineOfFire(), DrawLineOfFireCameraHybrid(), and RemoveAllShapes().
m_HitShape2
Shape m_HitShape2 private
Definition at line 42 of file WeaponDebug.c.
Referenced by DrawLineOfFireMuzzleToHit(), and RemoveAllShapes().
m_HitShape3
Shape m_HitShape3 private
Definition at line 43 of file WeaponDebug.c.
Referenced by DrawLineOfFireMuzzleToHit(), and RemoveAllShapes().
m_HitShape4
Shape m_HitShape4 private
Definition at line 44 of file WeaponDebug.c.
Referenced by DrawLineOfFireCameraHybrid(), and RemoveAllShapes().
m_IsDrawKeyHeldDown
bool m_IsDrawKeyHeldDown private
Definition at line 21 of file WeaponDebug.c.
Referenced by DrawBarrelMemoryPoints(), OnCommandHandlerUpdate(), and OnPostFrameUpdate().
m_IsFireKeyPressed
bool m_IsFireKeyPressed private
Definition at line 24 of file WeaponDebug.c.
Referenced by DrawLineOfFire(), DrawLineOfFireCameraHybrid(), DrawLineOfFireMuzzleToHit(), and OnCommandHandlerUpdate().
m_IsLMBPressed
bool m_IsLMBPressed private
Definition at line 22 of file WeaponDebug.c.
Referenced by OnCommandHandlerUpdate().
m_IsToggleKeyPressed
bool m_IsToggleKeyPressed private
Definition at line 23 of file WeaponDebug.c.
m_PermanentLine1
Shape m_PermanentLine1 private
Definition at line 46 of file WeaponDebug.c.
Referenced by DrawLineOfFire(), DrawLineOfFireCameraHybrid(), DrawLineOfFireMuzzleToHit(), and RemoveAllShapes().
m_PermanentLine2
Shape m_PermanentLine2 private
Definition at line 47 of file WeaponDebug.c.
Referenced by DrawLineOfFireCameraHybrid(), DrawLineOfFireMuzzleToHit(), and RemoveAllShapes().
m_PermanentShape1
Shape m_PermanentShape1 private
Definition at line 49 of file WeaponDebug.c.
Referenced by DrawLineOfFireCameraHybrid(), and RemoveAllShapes().
m_PermanentShape2
Shape m_PermanentShape2 private
Definition at line 50 of file WeaponDebug.c.
Referenced by RemoveAllShapes().
m_Shape_konec
Shape m_Shape_konec private
Definition at line 35 of file WeaponDebug.c.
Referenced by DrawBarrelMemoryPoints(), and RemoveAllShapes().
m_Shape_usti
Shape m_Shape_usti private
Definition at line 34 of file WeaponDebug.c.
Referenced by DrawBarrelMemoryPoints(), and RemoveAllShapes().
m_ShapeEye
Shape m_ShapeEye private
Definition at line 39 of file WeaponDebug.c.
Referenced by DrawEyePoint(), and RemoveAllShapes().
m_ShapeFireDirCamera
Shape m_ShapeFireDirCamera private
Definition at line 41 of file WeaponDebug.c.
Referenced by DrawLineOfFireMuzzleToHit(), and RemoveAllShapes().
m_ShapeFireDirection1
Shape m_ShapeFireDirection1 private
Definition at line 36 of file WeaponDebug.c.
Referenced by DrawLineOfFire(), and RemoveAllShapes().
m_ShapeFireDirection2
Shape m_ShapeFireDirection2 private
Definition at line 37 of file WeaponDebug.c.
Referenced by DrawLineOfFire(), and RemoveAllShapes().
m_ShapeTrailLines
Shape m_ShapeTrailLines private
Definition at line 40 of file WeaponDebug.c.
Referenced by OnPostFrameUpdate(), and RemoveAllShapes().
m_TargetDistance
float m_TargetDistance private
Definition at line 25 of file WeaponDebug.c.
Referenced by DisplayTargetInfo(), DrawLineOfFireCameraHybrid(), and DrawLineOfFireMuzzleToHit().
m_WeaponInHands
Weapon m_WeaponInHands private
Definition at line 19 of file WeaponDebug.c.
MAX_MUZZLE_DISTANCE_TOLERANCE
const float MAX_MUZZLE_DISTANCE_TOLERANCE = 20 private
Definition at line 15 of file WeaponDebug.c.
Referenced by DrawLineOfFireCameraHybrid().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/WeaponDebug.c