DayZ Scripts: PPERequester_GameplayBase Class Reference
PPERequester_GameplayBase Class Reference
base, not to be used directly, would lead to layering collisions!
Private Member Functions
void SetBloodLossLevel (float level)
override protected void OnStart (Param par=null)
override protected void OnStop (Param par=null)
void SetValuesOptics (out array< float > mask_array, out array< float > lens_array, float gauss=0.0)
void SetValuesIronsights (out array< float > DOF_array)
override protected void OnStop (Param par=null)
protected void SetNVMode (int mode)
override protected void OnStart (Param par=null)
override protected void OnStop (Param par=null)
void SetUndergroundExposureCoef (float coef)
override protected void OnStart (Param par=null)
override protected void OnUpdate (float delta)
override void OnStop (Param par=null)
protected float FadeColourMult (float x, float y, float deltaT)
override protected void OnStart (Param par=null)
override protected void OnStart (Param par=null)
override protected void OnUpdate (float delta)
void SetStamina01 (float stamina01)
void SetFeverIntensity (float intensity)
override protected void OnStart (Param par=null)
override protected void OnStop (Param par=null)
override protected void OnUpdate (float delta)
void SetFlashbangIntensity (float intensity, float daytime_toggle)
override protected void OnStart (Param par=null)
override protected void OnStart (Param par=null)
override protected void OnStart (Param par=null)
override protected void OnStart (Param par=null)
void SetHitIntensity (float intensity)
override protected void OnStart (Param par=null)
void SetRadialBlur (float power_x, float power_y, float offset_x, float offset_y, float pixel_scale=0.5)
override protected void OnStart (Param par=null)
override protected void OnStart (Param par=null)
override protected void OnStart (Param par=null)
void SetEyeAccommodation (float value)
Private Attributes
protected int m_CurrentMode
protected float m_UGExposureCoef = 1.0
protected vector m_StartRGB = vector.Zero
protected float m_AccumulatedTime = 0
protected bool m_FadeIn = false
protected bool m_FadeOut = false
const float FADE_TIME = 3
const float R_TARGET = 0.142
const float G_TARGET = 0.15
const float B_TARGET = 0.44
protected float m_Value
private float m_EffectPhase = 0
private float m_Magnitude = 0
private float m_MinMagnitude = 0.3
private float m_MaxMagnitude = 0.3
private float m_Frequency = 5
private float m_Stamina01
const float VAL_FACTOR = 0.85
const float EXPOSURE_MAX = 50
protected float m_Exposure
protected float m_Intensity
const float INTENSITY_MULT = 6.0
protected float m_Gauss
protected float m_VignetteIntensity
protected float m_OverlayFactor
protected ref array< float > m_OverlayColor
Static Private Attributes
static const int NV_NO_BATTERY = 0
static const int NV_DEFAULT_OPTICS = 1
static const int NV_DEFAULT_GLASSES = 2
static const int NV_PUMPKIN = 3
static const int NV_TRANSITIVE = 4
static const int NV_DAYTIME_OPTICS = 5
Detailed Description
base, not to be used directly, would lead to layering collisions!
Definition at line 1 of file PPERBloodLoss.c.
Member Function Documentation
FadeColourMult()
protected float FadeColourMult (float x, float y, float deltaT) inline private
Definition at line 77 of file PPERContaminated.c.
References Easing::EaseInOutSine(), Math::Lerp(), x, and y.
Referenced by OnUpdate().
OnStart() [1/14]
override protected void OnStart (Param par = null) inline private
Definition at line 3 of file PPERBurlapSack.c.
References GameplayEffectWidgets_base::AddSuspendRequest(), Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), PPEExposureNative::L_0_BURLAP, PPEEyeAccomodationNative::L_0_BURLAP, PPEGlow::L_25_BURLAP, PPEGlow::L_26_BURLAP, PPEExposureNative::PARAM_INTENSITY, PPEEyeAccomodationNative::PARAM_INTENSITY, PPEGlow::PARAM_VIGNETTE, PPEGlow::PARAM_VIGNETTECOLOR, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [2/14]
override protected void OnStart (Param par = null) inline private
Definition at line 73 of file PPERCameraNV.c.
References SetNVMode().
OnStart() [3/14]
override protected void OnStart (Param par = null) inline private
Definition at line 15 of file PPERContaminated.c.
References PPEFilmGrain::L_1_TOXIC_TINT, PPEFilmGrain::L_2_TOXIC_TINT, PPEFilmGrain::PARAM_GRAINSIZE, PPEFilmGrain::PARAM_SHARPNESS, and SetTargetValueFloat().
OnStart() [4/14]
override protected void OnStart (Param par = null) inline private
Definition at line 5 of file PPERDeathDarkening.c.
References Easing::EaseInCubic(), PPEExposureNative::L_0_DEATH, Math::Lerp(), m_Value, PPEExposureNative::PARAM_INTENSITY, and SetTargetValueFloat().
OnStart() [5/14]
override protected void OnStart (Param par = null) inline private
Definition at line 10 of file PPERDrowningEffect.c.
OnStart() [6/14]
override protected void OnStart (Param par = null) inline private
Definition at line 8 of file PPERFlashbangEffects.c.
References GameplayEffectWidgets_base::AddActiveEffects(), Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), and m_IsRunning.
OnStart() [7/14]
override protected void OnStart (Param par = null) inline private
Definition at line 5 of file PPERGlasses.c.
References PPEGodRays::L_0_GLASSES, PPEGlow::L_23_GLASSES, PPEGlow::PARAM_COLORIZATIONCOLOR, PPEGodRays::PARAM_INTENSITY, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [8/14]
override protected void OnStart (Param par = null) inline private
Definition at line 31 of file PPERGlasses.c.
References PPEGodRays::L_0_GLASSES, PPEGlow::L_23_GLASSES, PPEGlow::PARAM_COLORIZATIONCOLOR, PPEGodRays::PARAM_INTENSITY, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [9/14]
override protected void OnStart (Param par = null) inline private
Definition at line 53 of file PPERGlasses.c.
References PPEGodRays::L_0_GLASSES, PPEGlow::L_23_GLASSES, PPEGlow::PARAM_COLORIZATIONCOLOR, PPEGodRays::PARAM_INTENSITY, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [10/14]
override protected void OnStart (Param par = null) inline private
Definition at line 74 of file PPERGlasses.c.
References PPEGodRays::L_0_GLASSES, PPEGlow::L_23_GLASSES, PPEGlow::PARAM_COLORIZATIONCOLOR, PPEGodRays::PARAM_INTENSITY, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [11/14]
override protected void OnStart (Param par = null) inline private
Definition at line 3 of file PPERInventoryBlur.c.
References PPEGaussFilter::L_0_INV, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
OnStart() [12/14]
override protected void OnStart (Param par = null) inline private
Definition at line 8 of file PPERShockHit.c.
References PPEGaussFilter::L_0_SHOCK, PPEGlow::L_20_SHOCK, PPEGlow::L_21_SHOCK, PPEGlow::L_25_SHOCK, PPEGaussFilter::PARAM_INTENSITY, PPEGlow::PARAM_OVERLAYCOLOR, PPEGlow::PARAM_OVERLAYFACTOR, PPEGlow::PARAM_VIGNETTE, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [13/14]
override protected void OnStart (Param par = null) inline private
Definition at line 5 of file PPERTunnel.c.
References PPEGlow::L_25_TUNNEL, PPEGlow::L_26_TUNNEL, PPEGlow::PARAM_VIGNETTE, PPEGlow::PARAM_VIGNETTECOLOR, SetTargetValueColor(), and SetTargetValueFloat().
OnStart() [14/14]
override protected void OnStart (Param par = null) inline private
Definition at line 5 of file PPERUnconEffects.c.
References PPEGlow::L_25_UNCON, PPEGlow::L_26_UNCON, PPEGlow::PARAM_VIGNETTE, PPEGlow::PARAM_VIGNETTECOLOR, SetTargetValueColor(), and SetTargetValueFloat().
OnStop() [1/5]
override protected void OnStop (Param par = null) inline private
Definition at line 18 of file PPERBurlapSack.c.
References Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), and GameplayEffectWidgets_base::RemoveSuspendRequest().
OnStop() [2/5]
override protected void OnStop (Param par = null) inline private
Definition at line 53 of file PPERCameraADS_Opt.c.
References GetGame(), and CGame::ResetPPMask().
OnStop() [3/5]
override protected void OnStop (Param par = null) inline private
Definition at line 81 of file PPERCameraNV.c.
OnStop() [4/5]
override void OnStop (Param par = null) inline private
Definition at line 62 of file PPERContaminated.c.
References Class::CastTo().
OnStop() [5/5]
override protected void OnStop (Param par = null) inline private
Definition at line 19 of file PPERFlashbangEffects.c.
References Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), and GameplayEffectWidgets_base::RemoveActiveEffects().
OnUpdate() [1/3]
override protected void OnUpdate (float delta) inline private
Definition at line 28 of file PPERContaminated.c.
References B_TARGET, FadeColourMult(), G_TARGET, PPEGlow::L_23_TOXIC_TINT, PPEGlow::PARAM_COLORIZATIONCOLOR, R_TARGET, SetTargetValueColor(), and Stop().
OnUpdate() [2/3]
override protected void OnUpdate (float delta) inline private
Definition at line 18 of file PPERDrowningEffect.c.
References Easing::EaseInExpo(), PPEGodRays::L_0_GLASSES, PPEGlow::L_23_GLASSES, Math::Lerp(), m_IsRunning, m_MaxMagnitude, m_MinMagnitude, PPEGlow::PARAM_VIGNETTE, PPEGlow::PARAM_VIGNETTECOLOR, SetTargetValueColor(), SetTargetValueFloat(), and Math::Sin().
OnUpdate() [3/3]
override protected void OnUpdate (float delta) inline private
Definition at line 30 of file PPERFlashbangEffects.c.
References Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), and GameplayEffectWidgets_base::UpdateWidgets().
SetBloodLossLevel()
void SetBloodLossLevel (float level) inline private
Definition at line 3 of file PPERBloodLoss.c.
References PPEGlow::L_22_BLOODLOSS, PPEGlow::PARAM_SATURATION, and SetTargetValueFloat().
SetEyeAccommodation()
void SetEyeAccommodation (float value) inline private
Definition at line 3 of file PPERUndergroundAcco.c.
References PPEEyeAccomodationNative::L_0_UNDERGROUND, PPEEyeAccomodationNative::PARAM_INTENSITY, and SetTargetValueFloat().
SetFeverIntensity()
void SetFeverIntensity (float intensity) inline private
Definition at line 3 of file PPERFever.c.
References PPEGaussFilter::L_0_FEVER, PPEGaussFilter::PARAM_INTENSITY, and SetTargetValueFloat().
SetFlashbangIntensity()
void SetFlashbangIntensity (float intensity, float daytime_toggle) inline private
Definition at line 41 of file PPERFlashbangEffects.c.
References Math::Clamp(), Easing::EaseInQuart(), PPEExposureNative::L_0_FLASHBANG, PPEGaussFilter::L_0_FLASHBANG, PPEGlow::L_20_FLASHBANG, PPEGlow::L_21_FLASHBANG, PPEExposureNative::PARAM_INTENSITY, PPEGaussFilter::PARAM_INTENSITY, PPEGlow::PARAM_OVERLAYCOLOR, PPEGlow::PARAM_OVERLAYFACTOR, SetTargetValueColor(), and SetTargetValueFloat().
SetHitIntensity()
void SetHitIntensity (float intensity) inline private
Definition at line 5 of file PPERHealthHit.c.
References PPEGlow::L_20_HIT, PPEGlow::L_21_HIT, PPEGlow::PARAM_OVERLAYCOLOR, PPEGlow::PARAM_OVERLAYFACTOR, SetTargetValueColor(), and SetTargetValueFloat().
SetNVMode()
protected void SetNVMode (int mode) inline private
Definition at line 13 of file PPERCameraNV.c.
References PPELightIntensityParamsNative::L_0_NVG, PPEEyeAccomodationNative::L_0_NVG_GENERIC, PPEExposureNative::L_0_NVG_GOGGLES, PPEExposureNative::L_0_NVG_OPTIC, PPELightIntensityParamsNative::L_1_NVG, PPEFilmGrain::L_1_NVG, PPEGlow::L_23_NVG, PPEFilmGrain::L_2_NVG, m_CurrentMode, NV_DAYTIME_OPTICS, NV_DEFAULT_GLASSES, NV_DEFAULT_OPTICS, NV_NO_BATTERY, NV_PUMPKIN, NV_TRANSITIVE, PPEGlow::PARAM_COLORIZATIONCOLOR, PPEFilmGrain::PARAM_GRAINSIZE, PPEExposureNative::PARAM_INTENSITY, PPEEyeAccomodationNative::PARAM_INTENSITY, PPELightIntensityParamsNative::PARAM_LIGHT_MULT, PPELightIntensityParamsNative::PARAM_NOISE_MULT, PPEFilmGrain::PARAM_SHARPNESS, SetTargetValueColor(), SetTargetValueFloat(), and SetTargetValueFloatDefault().
Referenced by OnStart(), and SetUndergroundExposureCoef().
SetRadialBlur()
void SetRadialBlur (float power_x, float power_y, float offset_x, float offset_y, float pixel_scale = 0.5) inline private
Definition at line 3 of file PPERPain.c.
References PPERadialBlur::L_0_PAIN_BLUR, PPERadialBlur::PARAM_OFFSETX, PPERadialBlur::PARAM_OFFSETY, PPERadialBlur::PARAM_PIXELSCALE, PPERadialBlur::PARAM_POWERX, PPERadialBlur::PARAM_POWERY, and SetTargetValueFloat().
SetStamina01()
void SetStamina01 (float stamina01) inline private
Definition at line 37 of file PPERDrowningEffect.c.
SetUndergroundExposureCoef()
void SetUndergroundExposureCoef (float coef) inline private
Definition at line 86 of file PPERCameraNV.c.
References m_CurrentMode, m_IsRunning, and SetNVMode().
SetValuesIronsights()
void SetValuesIronsights (out array< float > DOF_array) inline private
Definition at line 30 of file PPERCameraADS_Opt.c.
References GetGame(), PPEDOF::L_0_ADS, PPEDOF::L_1_ADS, PPEDOF::L_2_ADS, PPEDOF::L_3_ADS, PPEDOF::L_4_ADS, PPEDOF::L_5_ADS, PPEDOF::PARAM_BLUR, PPEDOF::PARAM_ENABLE, PPEDOF::PARAM_FOCUS_DEPTH_OFFSET, PPEDOF::PARAM_FOCUS_DIST, PPEDOF::PARAM_FOCUS_LEN, PPEDOF::PARAM_FOCUS_LEN_NEAR, PPEGaussFilter::PARAM_INTENSITY, PPEGlow::PARAM_LENSCENTERX, PPEGlow::PARAM_LENSCENTERY, PPEGlow::PARAM_LENSDISTORT, PPEGlow::PARAM_MAXCHROMABBERATION, CGame::ResetPPMask(), SetTargetValueBool(), SetTargetValueFloat(), and SetTargetValueFloatDefault().
SetValuesOptics()
void SetValuesOptics (out array< float > mask_array, out array< float > lens_array, float gauss = 0.0) inline private
Definition at line 3 of file PPERCameraADS_Opt.c.
References CGame::AddPPMask(), GetGame(), PPEGaussFilter::L_0_ADS, PPEGlow::L_27_ADS, PPEGlow::L_28_ADS, PPEGlow::L_29_ADS, PPEGlow::L_30_ADS, PPEDOF::PARAM_ENABLE, PPEGaussFilter::PARAM_INTENSITY, PPEGlow::PARAM_LENSCENTERX, PPEGlow::PARAM_LENSCENTERY, PPEGlow::PARAM_LENSDISTORT, PPEGlow::PARAM_MAXCHROMABBERATION, CGame::ResetPPMask(), SetTargetValueBoolDefault(), and SetTargetValueFloat().
Field Documentation
B_TARGET
const float B_TARGET = 0.44 private
Definition at line 13 of file PPERContaminated.c.
Referenced by OnUpdate().
EXPOSURE_MAX
const float EXPOSURE_MAX = 50 private
Definition at line 4 of file PPERFlashbangEffects.c.
FADE_TIME
const float FADE_TIME = 3 private
Definition at line 9 of file PPERContaminated.c.
G_TARGET
const float G_TARGET = 0.15 private
Definition at line 12 of file PPERContaminated.c.
Referenced by OnUpdate().
INTENSITY_MULT
const float INTENSITY_MULT = 6.0 private
Definition at line 3 of file PPERHealthHit.c.
m_AccumulatedTime
protected float m_AccumulatedTime = 0 private
Definition at line 5 of file PPERContaminated.c.
m_CurrentMode
protected int m_CurrentMode private
Definition at line 10 of file PPERCameraNV.c.
m_EffectPhase
private float m_EffectPhase = 0 private
Definition at line 3 of file PPERDrowningEffect.c.
m_Exposure
protected float m_Exposure private
Definition at line 5 of file PPERFlashbangEffects.c.
m_FadeIn
protected bool m_FadeIn = false private
Definition at line 6 of file PPERContaminated.c.
m_FadeOut
protected bool m_FadeOut = false private
Definition at line 7 of file PPERContaminated.c.
m_Frequency
private float m_Frequency = 5 private
Definition at line 7 of file PPERDrowningEffect.c.
m_Gauss
protected float m_Gauss private
Definition at line 3 of file PPERShockHit.c.
m_Intensity
protected float m_Intensity private
Definition at line 6 of file PPERFlashbangEffects.c.
m_Magnitude
private float m_Magnitude = 0 private
Definition at line 4 of file PPERDrowningEffect.c.
m_MaxMagnitude
private float m_MaxMagnitude = 0.3 private
Definition at line 6 of file PPERDrowningEffect.c.
Referenced by OnUpdate().
m_MinMagnitude
private float m_MinMagnitude = 0.3 private
Definition at line 5 of file PPERDrowningEffect.c.
Referenced by OnUpdate().
m_OverlayColor
protected ref array<float> m_OverlayColor private
Definition at line 6 of file PPERShockHit.c.
m_OverlayFactor
protected float m_OverlayFactor private
Definition at line 5 of file PPERShockHit.c.
m_Stamina01
private float m_Stamina01 private
Definition at line 8 of file PPERDrowningEffect.c.
m_StartRGB
protected vector m_StartRGB = vector.Zero private
Definition at line 4 of file PPERContaminated.c.
m_UGExposureCoef
protected float m_UGExposureCoef = 1.0 private
Definition at line 11 of file PPERCameraNV.c.
m_Value
protected float m_Value private
Definition at line 3 of file PPERDeathDarkening.c.
m_VignetteIntensity
protected float m_VignetteIntensity private
Definition at line 4 of file PPERShockHit.c.
NV_DAYTIME_OPTICS
const int NV_DAYTIME_OPTICS = 5 static private
Definition at line 8 of file PPERCameraNV.c.
Referenced by SetNVMode().
NV_DEFAULT_GLASSES
const int NV_DEFAULT_GLASSES = 2 static private
Definition at line 5 of file PPERCameraNV.c.
Referenced by SetNVMode().
NV_DEFAULT_OPTICS
const int NV_DEFAULT_OPTICS = 1 static private
Definition at line 4 of file PPERCameraNV.c.
Referenced by SetNVMode().
NV_NO_BATTERY
const int NV_NO_BATTERY = 0 static private
Definition at line 3 of file PPERCameraNV.c.
Referenced by SetNVMode().
NV_PUMPKIN
const int NV_PUMPKIN = 3 static private
Definition at line 6 of file PPERCameraNV.c.
Referenced by SetNVMode().
NV_TRANSITIVE
const int NV_TRANSITIVE = 4 static private
Definition at line 7 of file PPERCameraNV.c.
Referenced by SetNVMode().
R_TARGET
const float R_TARGET = 0.142 private
Definition at line 11 of file PPERContaminated.c.
Referenced by OnUpdate().
VAL_FACTOR
const float VAL_FACTOR = 0.85 private
Definition at line 3 of file PPERFlashbangEffects.c.
The documentation for this class was generated from the following files:
P:/scripts/3_Game/PPEManager/Requesters/PPERBloodLoss.c
P:/scripts/3_Game/PPEManager/Requesters/PPERCameraNV.c
P:/scripts/3_Game/PPEManager/Requesters/PPERContaminated.c
P:/scripts/3_Game/PPEManager/Requesters/PPERDeathDarkening.c
P:/scripts/3_Game/PPEManager/Requesters/PPERDrowningEffect.c
P:/scripts/3_Game/PPEManager/Requesters/PPERFlashbangEffects.c
P:/scripts/3_Game/PPEManager/Requesters/PPERHealthHit.c
P:/scripts/3_Game/PPEManager/Requesters/PPERShockHit.c
P:/scripts/3_Game/PPEManager/Requesters/PPERTunnel.c
P:/scripts/3_Game/PPEManager/Requesters/PPERUnconEffects.c
P:/scripts/3_Game/PPEManager/Requesters/PPERBurlapSack.c
P:/scripts/3_Game/PPEManager/Requesters/PPERCameraADS_Opt.c
P:/scripts/3_Game/PPEManager/Requesters/PPERFever.c
P:/scripts/3_Game/PPEManager/Requesters/PPERGlasses.c
P:/scripts/3_Game/PPEManager/Requesters/PPERInventoryBlur.c
P:/scripts/3_Game/PPEManager/Requesters/PPERPain.c
P:/scripts/3_Game/PPEManager/Requesters/PPERUndergroundAcco.c