DayZ Scripts: ActionDeployHuntingTrap Class Reference
ActionDeployHuntingTrap Class Reference
Private Member Functions
void ActionDeployHuntingTrap ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateConditionComponents ()
override bool ActionConditionContinue (ActionData action_data)
override void MoveEntityToFinalPosition (ActionData action_data, vector position, vector orientation)
Constructor & Destructor Documentation
ActionDeployHuntingTrap()
void ActionDeployHuntingTrap () inline private
References AnimatedActionBase::m_CommandUID, m_Sound, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References ItemBase::CanBePlaced(), and GetGame().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
References ItemBase::CanBePlaced(), GetGame(), CGame::IsClient(), ActionData::m_MainItem, and ActionData::m_Player.
CreateConditionComponents()
override void CreateConditionComponents () inline private
References m_ConditionItem, and m_ConditionTarget.
MoveEntityToFinalPosition()
override void MoveEntityToFinalPosition (ActionData action_data, vector position, vector orientation) inline private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/DeployActions/ActionDeployHuntingTrap.c