DayZ Scripts: ActionRepairPart Class Reference
ActionRepairPart Class Reference
Private Member Functions
void ActionRepairPart ()
override void CreateConditionComponents ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override string GetText ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
protected override void SetBuildingAnimation (ItemBase item)
override ActionData CreateActionData ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
protected bool RepairCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check)
override string GetAdminLogMessage (ActionData action_data)
Detailed Description
Definition at line 39 of file ActionRepairPart.c.
Constructor & Destructor Documentation
ActionRepairPart()
void ActionRepairPart () inline private
Definition at line 41 of file ActionRepairPart.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 81 of file ActionRepairPart.c.
References RepairCondition().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
Definition at line 90 of file ActionRepairPart.c.
References ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, and RepairCondition().
CreateActionData()
override ActionData CreateActionData () inline private
Definition at line 137 of file ActionRepairPart.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 52 of file ActionRepairPart.c.
References UAMaxDistances::BASEBUILDING, m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string GetAdminLogMessage (ActionData action_data) inline private
Definition at line 237 of file ActionRepairPart.c.
References ActionData::m_MainItem, and ActionData::m_Target.
GetText()
override string GetText () inline private
Definition at line 64 of file ActionRepairPart.c.
References GetGame(), ConstructionPart::GetName(), GetPlayer(), and ConstructionActionData::GetTargetPart().
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 176 of file ActionRepairPart.c.
References RepairPartActionReciveData::m_ComponentIndexRecived.
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 58 of file ActionRepairPart.c.
References ConstructionPart::GetName(), ConstructionActionData::GetTargetPart(), and m_Text.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 95 of file ActionRepairPart.c.
References Class::CastTo(), Construction(), GetPlugin(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, ActionData::m_Target, and UADamageApplied::REPAIR.
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 155 of file ActionRepairPart.c.
References HasTarget(), RepairPartActionReciveData::m_ComponentIndexRecived, and Serializer::Read().
RepairCondition()
protected bool RepairCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check) inline private
Definition at line 184 of file ActionRepairPart.c.
References Construction(), GetGame(), ConstructionPart::GetMainPartName(), BaseBuildingBase::HasProperDistance(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), ConstructionActionData::SetTargetPart(), GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
Referenced by ActionCondition(), and ActionConditionContinue().
SetBuildingAnimation()
protected override void SetBuildingAnimation (ItemBase item) inline private
Definition at line 118 of file ActionRepairPart.c.
References AnimatedActionBase::m_CommandUID.
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 143 of file ActionRepairPart.c.
References Class::CastTo(), HasTarget(), ActionData::m_Target, and Serializer::Write().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionRepairPart.c