DayZ Scripts: PluginDayzPlayerDebug_OtherCmds Class Reference
PluginDayzPlayerDebug_OtherCmds Class Reference
Private Member Functions
void PluginDayzPlayerDebug_OtherCmds (Widget pMainWnd)
void ~PluginDayzPlayerDebug_OtherCmds ()
void CreateModuleWidgets ()
void DestroyModuleWidgets ()
bool OnClick (Widget w, int x, int y, int button)
buttons clicks
void CommandHandler ()
void Death_Start ()
void Hit_Start ()
void Uncon_Start ()
void Uncon_End ()
Private Attributes
Widget m_MainWnd
XComboBoxWidget m_DeathTypeCB
EditBoxWidget m_DeathDirectionEdit
ButtonWidget m_DeathStartButton
XComboBoxWidget m_HitTypeCB
ButtonWidget m_HitStartButton
XComboBoxWidget m_UnconTypeCB
ButtonWidget m_UnconStartButton
ButtonWidget m_UnconEndButton
bool m_CH_DeathStart = false
bool m_CH_HitStart = false
bool m_CH_UnconStart = false
bool m_CH_UnconEnd = false
Constructor & Destructor Documentation
PluginDayzPlayerDebug_OtherCmds()
void PluginDayzPlayerDebug_OtherCmds (Widget pMainWnd) inline private
References CreateModuleWidgets(), and m_MainWnd.
~PluginDayzPlayerDebug_OtherCmds()
void ~PluginDayzPlayerDebug_OtherCmds () inline private
References DestroyModuleWidgets().
Member Function Documentation
CommandHandler()
void CommandHandler () inline private
References Death_Start(), Hit_Start(), m_CH_DeathStart, m_CH_HitStart, m_CH_UnconEnd, m_CH_UnconStart, Uncon_End(), and Uncon_Start().
Referenced by CommandHandler().
CreateModuleWidgets()
void CreateModuleWidgets () inline private
References m_DeathDirectionEdit, m_DeathStartButton, m_DeathTypeCB, m_HitStartButton, m_HitTypeCB, m_MainWnd, m_UnconEndButton, m_UnconStartButton, and m_UnconTypeCB.
Referenced by PluginDayzPlayerDebug_OtherCmds().
Death_Start()
void Death_Start () inline private
References GetGame(), GetPlayer(), m_DeathDirectionEdit, and m_DeathTypeCB.
Referenced by CommandHandler().
DestroyModuleWidgets()
void DestroyModuleWidgets () inline private
Referenced by ~PluginDayzPlayerDebug_OtherCmds().
Hit_Start()
void Hit_Start () inline private
References GetGame(), GetPlayer(), m_DeathDirectionEdit, and m_HitTypeCB.
Referenced by CommandHandler().
OnClick()
bool OnClick (Widget w, int x, int y, int button) inline private
buttons clicks
References m_CH_DeathStart, m_CH_HitStart, m_CH_UnconEnd, m_CH_UnconStart, m_DeathStartButton, m_HitStartButton, m_UnconEndButton, m_UnconStartButton, and Print().
Uncon_End()
void Uncon_End () inline private
References GetGame(), GetPlayer(), and HumanCommandUnconscious::WakeUp().
Referenced by CommandHandler().
Uncon_Start()
void Uncon_Start () inline private
References GetGame(), GetPlayer(), and m_UnconTypeCB.
Referenced by CommandHandler().
Field Documentation
m_CH_DeathStart
bool m_CH_DeathStart = false private
Referenced by CommandHandler(), and OnClick().
m_CH_HitStart
bool m_CH_HitStart = false private
Referenced by CommandHandler(), and OnClick().
m_CH_UnconEnd
bool m_CH_UnconEnd = false private
Referenced by CommandHandler(), and OnClick().
m_CH_UnconStart
bool m_CH_UnconStart = false private
Referenced by CommandHandler(), and OnClick().
m_DeathDirectionEdit
EditBoxWidget m_DeathDirectionEdit private
Referenced by CreateModuleWidgets(), Death_Start(), and Hit_Start().
m_DeathStartButton
ButtonWidget m_DeathStartButton private
Referenced by CreateModuleWidgets(), and OnClick().
m_DeathTypeCB
XComboBoxWidget m_DeathTypeCB private
Referenced by CreateModuleWidgets(), and Death_Start().
m_HitStartButton
ButtonWidget m_HitStartButton private
Referenced by CreateModuleWidgets(), and OnClick().
m_HitTypeCB
XComboBoxWidget m_HitTypeCB private
Referenced by CreateModuleWidgets(), and Hit_Start().
m_MainWnd
Widget m_MainWnd private
Referenced by CreateModuleWidgets(), and PluginDayzPlayerDebug_OtherCmds().
m_UnconEndButton
ButtonWidget m_UnconEndButton private
Referenced by CreateModuleWidgets(), and OnClick().
m_UnconStartButton
ButtonWidget m_UnconStartButton private
Referenced by CreateModuleWidgets(), and OnClick().
m_UnconTypeCB
XComboBoxWidget m_UnconTypeCB private
Referenced by CreateModuleWidgets(), and Uncon_Start().
The documentation for this class was generated from the following file:
4_World/Plugins/PluginBase/PluginDayzPlayerDebug_OtherCmds.c