DayZ Scripts: World Class Reference
World Class Reference
Private Member Functions
proto void CheckSoundObstruction (EntityAI source, bool inSource, out float obstruction, out float occlusion)
proto native void GetPlayerList (out array< Man > players)
proto native void SetTimeMultiplier (float timeMultiplier)
Sets the world time acceleration, overriding config. Mostly used for debug purposes.
proto void GetDate (out int year, out int month, out int day, out int hour, out int minute)
Get actual ingame world time.
proto native void SetDate (int year, int month, int day, int hour, int minute)
Sets actual ingame world time.
proto native float GetLatitude ()
proto native float GetLongitude ()
proto native float GetMoonIntensity ()
proto native float GetSunOrMoon ()
proto native bool IsNight ()
proto native float GetEyeAccom ()
proto native void SetEyeAccom (float eyeAccom)
proto native void StartFpsBenchmark (int sectorsCount, float preloadDistance, float fpsLimitRed, float fpsLimitGreen, float fpsLimitBlue, float minX, float minY, float maxX, float maxY)
proto native void StartFpsBenchmarkWithMask (float preloadDistance, float fpsLimitRed, float fpsLimitGreen, float fpsLimitBlue)
proto native void StartFpsBenchmarkViews (string xmlFileName, float preloadDistance)
proto native void SetBuldozerWaterEnabled (bool enable)
proto native void SetPreferredViewDistance (float distance)
Sets preferred view distance, which persists between game sessions.
proto native void SetViewDistance (float distance)
proto native void SetObjectViewDistance (float distance)
proto native void SetExplicitVolumeFactor_EnvSounds2D (float factor, float fadeTime)
proto native void AddEnvShootingSource (vector position, float shootingValDecrease)
Affects env sound controller value 'Shooting'.
proto int GetWorldSize ()
proto void GetGridCoords (vector pos, float gridSize, out int gridX, out int gridZ)
Translates world coordinates to a grid coordinates(map grid)
proto native void LoadNewLightingCfg (string path)
proto native void LoadUserLightingCfg (string path, string name)
proto native void SetUserLightingLerp (float val)
proto native AIWorld GetAIWorld ()
proto native void UpdatePathgraphDoorByAnimationSourceName (notnull Object object, string animSourceName)
proto native void MarkObjectForPathgraphUpdate (Object object)
proto native void ProcessMarkedObjectsForPathgraphUpdate ()
proto native Material GetMaterial (string materialName)
proto native void SetCameraPostProcessEffect (int cam, int ppEffect, string effectName, string materialName)
void SetAperture (float invDiameter)
proto native bool Is3rdPersonDisabled ()
proto native bool IsCrosshairDisabled ()
proto native bool IsMouseAndKeyboardEnabledOnServer ()
proto native int GetPingWarningThreshold ()
proto native int GetPingCriticalThreshold ()
proto native float GetServerFpsWarningThreshold ()
proto native float GetServerFpsCriticalThreshold ()
proto native void DisableTransmitVoN (bool disable)
proto native bool DisableReceiveVoN (bool disable)
proto native bool IsDisabledTransmitingVoN ()
proto native bool IsDisabledReceivingVoN ()
proto void SetVoiceOn (bool listening, bool toggled=false)
proto native void FlattenGrassSphere (float x, float z, float radius, float centerLerp01, float timeDown01, float maxHeight01)
proto native void FlattenGrassEllipse (float x, float z, float sideX, float sideZ, float offset, float angleRAD, float centerLerp01, float timeDown01, float maxHeight01)
proto native void FlattenGrassBox (float x, float z, float side, float angleRAD, float centerLerp01, float timeDown01, float maxHeight01)
proto native void FlattenGrassRect (float x, float z, float sideX, float sideZ, float offset, float angleRAD, float centerLerp01, float timeDown01, float maxHeight01)
Member Function Documentation
AddEnvShootingSource()
proto native void AddEnvShootingSource (vector position, float shootingValDecrease) private
Affects env sound controller value 'Shooting'.
Parameters
sound position
relative value (0..1) - how much should be value decreased
CheckSoundObstruction()
proto void CheckSoundObstruction (EntityAI source, bool inSource, out float obstruction, out float occlusion) private
DisableReceiveVoN()
proto native bool DisableReceiveVoN (bool disable) private
enable/disable receiving all voice over network globally
Parameters
disable if true, then player is not able listen any voice from VoN
Returns
true if mute request was sent successfully to server. If false, then was problem with sent request or missing player idendity.
Referenced by OnlineServices::OnLoadVoicePrivilege().
DisableTransmitVoN()
proto native void DisableTransmitVoN (bool disable) private
enable/disable transmiting voice over network globally
Parameters
disable if true, then VoN is no more usable for transmiting voice
Referenced by OnlineServices::OnLoadVoicePrivilege().
FlattenGrassBox()
proto native void FlattenGrassBox (float x, float z, float side, float angleRAD, float centerLerp01, float timeDown01, float maxHeight01) private
create box
Parameters
worldX world X of touch with ground
worldZ world X of touch with ground
sideSize size of side
angleRAD rotation
centerLerp01 lerp of values inside rasterization
timeDown01 relative speed of going down, 1 is usually 0.5secs
maxHeight01 maximum relative height of flattening, 0 = no flatten
FlattenGrassEllipse()
proto native void FlattenGrassEllipse (float x, float z, float sideX, float sideZ, float offset, float angleRAD, float centerLerp01, float timeDown01, float maxHeight01) private
create ellipse
Parameters
worldX world X of touch with ground
worldZ world X of touch with ground
radiusX radius in X coord before rotate
radiusZ radius in Z coord before rotate
offset offset, 0 = default center, <-1, 1>
angleRAD rotation
centerLerp01 lerp of values inside rasterization
timeDown01 relative speed of going down, 1 is usually 0.5secs
maxHeight01 maximum relative height of flattening, 0 = no flatten
FlattenGrassRect()
proto native void FlattenGrassRect (float x, float z, float sideX, float sideZ, float offset, float angleRAD, float centerLerp01, float timeDown01, float maxHeight01) private
create rectangle
Parameters
worldX world X of touch with ground
worldZ world X of touch with ground
sideXSize size of side in X
sideZSize size of side in Z
offset offset, 0 = default center, <-1, 1>
angleRAD rotation
centerLerp01 lerp of values inside rasterization
timeDown01 relative speed of going down, 1 is usually 0.5secs
maxHeight01 maximum relative height of flattening, 0 = no flatten
FlattenGrassSphere()
proto native void FlattenGrassSphere (float x, float z, float radius, float centerLerp01, float timeDown01, float maxHeight01) private
create sphere
Parameters
worldX world X of touch with ground
worldZ world X of touch with ground
radius radius
centerLerp01 lerp of values inside rasterization
timeDown01 relative speed of going down, 1 is usually 0.5secs
maxHeight01 maximum relative height of flattening, 0 = no flatten
GetAIWorld()
proto native AIWorld GetAIWorld () private
returns reference to AIWorld
GetDate()
proto void GetDate (out int year, out int month, out int day, out int hour, out int minute) private
Get actual ingame world time.
Parameters
year
month in range <1, 12>
day in range <1, 31>
hour in range <0, 23>
minute in range <0, 59>
int year, month, day, hour, minute;
GetGame().GetWorld().GetDate(year, month, day, hour, minute);
Referenced by GetAlarmInMin(), WorldData::GetDaytime(), ScriptConsoleGeneralTab::Init(), PluginConfigHandler::LoadSceneSettings(), UIPopupScript::OnOpen(), AlarmClock_ColorBase::OnUpdate(), UIPopupScript::ResetSliders(), SetAlarmInXMins(), WorldData::UpdateBaseEnvTemperature(), and WorldData::WeatherOnBeforeChange().
GetEyeAccom()
proto native float GetEyeAccom () private
GetGridCoords()
proto void GetGridCoords (vector pos, float gridSize, out int gridX, out int gridZ) private
Translates world coordinates to a grid coordinates(map grid)
Parameters
pos
size of grid in meters
x grid position result [out]
z grid position result [out]
int x,z;
GetGame().GetWorld().GetGridCoords(GetGame().GetPlayer().GetPosition(), 100, x, z);
Referenced by OrderedPositionNumbersFromGridCoords().
GetLatitude()
proto native float GetLatitude () private
GetLongitude()
proto native float GetLongitude () private
GetMaterial()
proto native Material GetMaterial (string materialName) private
Material matColors = GetGame().GetWorld().GetMaterial("postprocess/glow");
SetMaterialParam(matColors, "Saturation", 0.8);
float color[4];
color[0] = 0.5;
color[1] = 0.8;
color[2] = 0.7;
color[3] = 0.6;
SetMaterialParam(matColors, "OverlayColor", color);
Referenced by PPEClassBase::CreateMaterial(), PPEffects::Init(), PPEffects::SetBlur(), and PPEffects::SetNVParams().
GetMoonIntensity()
proto native float GetMoonIntensity () private
GetPingCriticalThreshold()
proto native int GetPingCriticalThreshold () private
Returns the value set in server config for notifying high ping
GetPingWarningThreshold()
proto native int GetPingWarningThreshold () private
Returns the value set in server config for notifying high ping
GetPlayerList()
proto native void GetPlayerList (out array< Man > players) private
Referenced by ItemBase::FullyBuild(), and MissionBase::TickScheduler().
GetServerFpsCriticalThreshold()
proto native float GetServerFpsCriticalThreshold () private
Returns the value set in server config for notifying low server fps
GetServerFpsWarningThreshold()
proto native float GetServerFpsWarningThreshold () private
Returns the value set in server config for notifying low server fps
GetSunOrMoon()
proto native float GetSunOrMoon () private
GetWorldSize()
proto int GetWorldSize () private
Is3rdPersonDisabled()
proto native bool Is3rdPersonDisabled () private
checks if 3rd person camera is disabled from server
Referenced by DayZPlayer::DayZPlayerImplement().
IsCrosshairDisabled()
proto native bool IsCrosshairDisabled () private
checks if crosshair is disabled from server
IsDisabledReceivingVoN()
proto native bool IsDisabledReceivingVoN () private
Returns
true, if receiving voice over network is disabled, so player can not listen anybody
Referenced by UIScriptedMenu::Init(), and UIScriptedMenu::Refresh().
IsDisabledTransmitingVoN()
proto native bool IsDisabledTransmitingVoN () private
Returns
true if transmiting voice over network is disabled, so player can not talking
IsMouseAndKeyboardEnabledOnServer()
proto native bool IsMouseAndKeyboardEnabledOnServer () private
checks if mouse and keyboard is enabled from server (only on console)
Referenced by ScriptedWidgetEventHandler::OptionsMenuControls().
IsNight()
proto native bool IsNight () private
LoadNewLightingCfg()
proto native void LoadNewLightingCfg (string path) private
load light config
Referenced by WorldLighting::SetGlobalLighting().
LoadUserLightingCfg()
proto native void LoadUserLightingCfg (string path, string name) private
load user light config (just first item is used)
Referenced by UndergroundHandlerClient().
MarkObjectForPathgraphUpdate()
proto native void MarkObjectForPathgraphUpdate (Object object) private
ProcessMarkedObjectsForPathgraphUpdate()
proto native void ProcessMarkedObjectsForPathgraphUpdate () private
Referenced by ObjectSpawnerHandler::OnGameplayDataHandlerLoad().
SetAperture()
void SetAperture (float invDiameter) inline private
References SetEyeAccom().
SetBuldozerWaterEnabled()
proto native void SetBuldozerWaterEnabled (bool enable) private
SetCameraPostProcessEffect()
proto native void SetCameraPostProcessEffect (int cam, int ppEffect, string effectName, string materialName) private
set new PP effect and its material
Parameters
camera number of camera
effectIndex index of effect
effectName name of effect
matName name of material
SetDate()
proto native void SetDate (int year, int month, int day, int hour, int minute) private
Sets actual ingame world time.
Parameters
year
month in range <1, 12>
day in range <1, 31>
hour in range <0, 23>
minute in range <0, 59>
int year = 2016;
int month = 5;
int day = 4;
int hour = 14;
int minute = 57;
GetGame().GetWorld().SetDate(year, month, day, hour, minute);
Referenced by DayZIntroScene::DayZIntroScene(), PluginBase::HandleSetTime(), UIPopupScript::OnChange(), UIPopupScript::OnClick(), UIPopupScript::OnClose(), SceneData::SetInitDay(), SceneData::SetInitHour(), SceneData::SetInitMinute(), SceneData::SetInitMonth(), SceneData::SetInitYear(), and ScriptConsoleGeneralTab::UpdateTime().
SetExplicitVolumeFactor_EnvSounds2D()
proto native void SetExplicitVolumeFactor_EnvSounds2D (float factor, float fadeTime) private
Referenced by ProcessSound(), and ~UndergroundHandlerClient().
SetEyeAccom()
proto native void SetEyeAccom (float eyeAccom) private
Referenced by SetAperture().
SetObjectViewDistance()
proto native void SetObjectViewDistance (float distance) private
SetPreferredViewDistance()
proto native void SetPreferredViewDistance (float distance) private
Sets preferred view distance, which persists between game sessions.
Parameters
distance
SetTimeMultiplier()
proto native void SetTimeMultiplier (float timeMultiplier) private
Sets the world time acceleration, overriding config. Mostly used for debug purposes.
Parameters
timeMultiplier 0-64 acceleration value, -1 to reset back
SetUserLightingLerp()
proto native void SetUserLightingLerp (float val) private
set lerp to user lighting cfg
Referenced by OnUndergroundPresenceUpdate(), ProcessLighting(), and ~UndergroundHandlerClient().
SetViewDistance()
proto native void SetViewDistance (float distance) private
SetVoiceOn()
proto void SetVoiceOn (bool listening, bool toggled = false) private
enables/disables player's voice communication
Parameters
listening enable or disable microphone
toggled enable or disable PTT/Voice activation
Referenced by DayZPlayer::HandleDeath().
StartFpsBenchmark()
proto native void StartFpsBenchmark (int sectorsCount, float preloadDistance, float fpsLimitRed, float fpsLimitGreen, float fpsLimitBlue, float minX, float minY, float maxX, float maxY) private
StartFpsBenchmarkViews()
proto native void StartFpsBenchmarkViews (string xmlFileName, float preloadDistance) private
StartFpsBenchmarkWithMask()
proto native void StartFpsBenchmarkWithMask (float preloadDistance, float fpsLimitRed, float fpsLimitGreen, float fpsLimitBlue) private
UpdatePathgraphDoorByAnimationSourceName()
proto native void UpdatePathgraphDoorByAnimationSourceName (notnull Object object, string animSourceName) private
For entities that aren't a house, any animation source that contains "door" is treated as a door by the pathgraph. Using the phase value where 0=CLOSED, 1=OPENED, we can update the state of the door without regenerating the tile
Referenced by Land_Underground_EntranceBase::OnUpdateServer().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Global/World.c