DayZ Scripts: P:/scripts/5_Mission/GUI/InventoryNew/Inventory.c File Reference
Inventory.c File Reference
Enumerations
enum Direction { RIGHT , LEFT , UP , DOWN }
Functions
void Inventory (LayoutHolder parent)
void InitInputWrapperData ()
protected void OnInputPresetChanged ()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
static Inventory GetInstance ()
void Serialize ()
void Deserialize ()
static int GetPlayerAttachmentIndex (string slot_name)
static int GetPlayerAttachmentIndex (int slot_id)
protected void LoadPlayerAttachmentIndexes ()
static void MoveAttachmentUp (int slot_id)
static void MoveAttachmentDown (int slot_id)
protected int GetProperControllerStickAngle (int angle)
protected int AngleToDirection (int angle)
void TimerEnd ()
bool Controller (Widget w, int control, int value)
void DraggingOverHandsPanel (Widget w, int x, int y, Widget receiver)
void OnHandsPanelDropReceived (Widget w, int x, int y, Widget receiver)
void OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver)
void OnRightPanelDropReceived (Widget w, int x, int y, Widget receiver)
void OnCenterPanelDropReceived (Widget w, int x, int y, Widget receiver)
void DraggingOverLeftPanel (Widget w, int x, int y, Widget receiver)
void DraggingOverRightPanel (Widget w, int x, int y, Widget receiver)
void DraggingOverCenterPanel (Widget w, int x, int y, Widget receiver)
void Update (float timeslice)
override void UpdateInterval ()
void AddQuickbarItem (InventoryItem item, int index)
void EnableMicromanagement ()
void DisableMicromanagement ()
override void SetLayoutName ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void Reset ()
void ResetFocusedContainers ()
override void OnShow ()
override void OnHide ()
void UpdateSpecialtyMeter ()
override void Refresh ()
void RefreshQuickbar ()
string ConsoleToolbarTypeToString (int console_toolbar_type)
void UpdateConsoleToolbar ()
string GetStringVariant (string pInputAction, notnull array< string > variants)
Picks from the strings by active input limiter variant in order: {click,hold,doubleclick}. Intended for inputs that check 'LocalPress' exclusively!!
void MoveFocusByContainer (int direction)
Shifts between containers vertically.
void MoveFocusByArea (int direction)
Shifts between vicinity-hands-player.
void InventoryMovementButtonTickHandler (float timeslice)
Variables
enum Direction PLAYER_EQUIPMENT_SLOTS_ITEM
enum Direction PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_CARGO
enum Direction PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_QUANTITY
enum Direction PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_ATTACHMENTS
enum Direction PLAYER_EQUIPMENT_SLOTS_ITEM_FREE
enum Direction PLAYER_CARGO_CONTAINER_EMPTY_CONTAINER
enum Direction PLAYER_CARGO_CONTAINER_ITEM
enum Direction PLAYER_CARGO_CONTAINER_ITEM_NO_EQUIP
enum Direction PLAYER_CARGO_CONTAINER_ITEM_WITH_QUANTITY
enum Direction PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS
enum Direction PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS_NO_EQUIP
enum Direction PLAYER_ITEM_WITH_ATTACHMENTS_CONTAINER_ITEM
enum Direction VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM
enum Direction VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_CARGO
enum Direction VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_ATTACHMENTS
enum Direction VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM_FREE
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_EMPTY_CONTAINER
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_ITEM
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_ITEM_NO_EQUIP
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_ITEM_WITH_QUANTITY
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS_NO_EQUIP
enum Direction VICNITY_PLAYER_ITEM_WITH_ATTACHMENTS_CONTAINER_ITEM
enum Direction VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM
enum Direction VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM_WITH_CARGO
enum Direction VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM_WITH_ATTACHMENTS
enum Direction VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM_FREE
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_EMPTY_CONTAINER
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_NO_EQUIP
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_WITH_QUANTITY
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS_NO_EQUIP
enum Direction VICNITY_ZOMBIE_ITEM_WITH_ATTACHMENTS_CONTAINER_ITEM
enum Direction HANDS_ITEM
enum Direction HANDS_ITEM_NO_EQUIP
enum Direction HANDS_ITEM_WITH_QUANTITY
enum Direction HANDS_ITEM_EMPTY
enum Direction VICINITY_CONTAINER_LIST_ITEM_WITH_CONTAINER
enum Direction VICINITY_CONTAINER_LIST_ITEM_WITH_CONTAINER_NO_EQUIP
enum Direction VICINITY_CONTAINER_LIST_ITEM
enum Direction VICINITY_CONTAINER_LIST_ITEM_NO_EQUIP
enum Direction VICINITY_CONTAINER_LIST_ITEM_WITH_QUANTITY
enum Direction VICINITY_CONTAINER_LIST_HEADER
enum Direction VICINITY_CONTAINER_LIST_EMPTY_ITEM
enum Direction VICINITY_CONTAINER_DETAILS_EMPTY
enum Direction VICINITY_CONTAINER_DETAILS_ITEM
enum Direction VICINITY_CONTAINER_DETAILS_ITEM_NO_EQUIP
enum Direction m_LeftArea
protected ref RightArea m_RightArea
protected ref HandsArea m_HandsArea
protected ref PlayerPreview m_PlayerPreview
protected ref InventoryQuickbar m_Quickbar
protected Widget m_QuickbarWidget
protected Widget m_SpecializationPanel
protected Widget m_SpecializationIcon
protected Widget m_TopConsoleToolbarVicinity
protected Widget m_TopConsoleToolbarHands
protected Widget m_TopConsoleToolbarEquipment
protected Widget m_BottomConsoleToolbar
protected RichTextWidget m_BottomConsoleToolbarRichText
protected ref ContextMenu m_ContextMenu
static protected ref map< string, int > m_PlayerAttachmentsIndexes
protected bool m_HadFastTransferred
protected bool m_HadInspected
static protected Inventory m_Instance
protected int m_ControllerAngle
protected int m_ControllerTilt
protected bool m_ControllerRightStickTimerEnd = true
protected ref Timer m_ControllerRightStickTimer
protected bool m_HoldingQB
protected InventoryItem m_QBHoveredItems
const float BT_REPEAT_DELAY = 0.35
const float BT_REPEAT_TIME = 0.09
const float BT_THRESHOLD_VALUE = 0.8
const int INV_MOV_LEFT = 0
const int INV_MOV_RIGHT = 1
const int INV_MOV_UP = 2
const int INV_MOV_DOWN = 3
protected ref array< string > m_InvInputNames = {"UAUILeftInventory","UAUIRightInventory","UAUIUpInventory","UAUIDownInventory"}
protected ref array< UAIDWrapper > m_InvInputWrappers
protected ref array< float > m_InvInputTimes
protected int m_InvInputWrappersCount
protected float m_SensitivityThreshold = 0.0
UAInput m_InvUAInput
int m_InvInputActive = 0
UAInput m_InpInp = null
Enumeration Type Documentation
Direction
enum Direction
Enumerator
RIGHT
LEFT
UP
DOWN
Definition at line 1 of file Inventory.c.
Function Documentation
AddQuickbarItem()
void AddQuickbarItem (InventoryItem item, int index)
Definition at line 1077 of file Inventory.c.
References GetGame(), GetPlayer(), InventoryMenu(), and MENU_INVENTORY.
Referenced by UpdateInterval().
AngleToDirection()
protected int AngleToDirection (int angle)
Definition at line 357 of file Inventory.c.
Referenced by Controller().
ConsoleToolbarTypeToString()
string ConsoleToolbarTypeToString (int console_toolbar_type)
Definition at line 1283 of file Inventory.c.
References string::Format(), InputUtils::GetRichtextButtonIconFromInputAction(), GetStringVariant(), and InputUtils::ICON_SCALE_TOOLBAR.
Referenced by UpdateConsoleToolbar().
Controller()
bool Controller (Widget w, int control, int value)
Definition at line 384 of file Inventory.c.
References AngleToDirection(), GetProperControllerStickAngle(), m_ControllerAngle, m_ControllerRightStickTimer, m_ControllerRightStickTimerEnd, m_ControllerTilt, and UpdateConsoleToolbar().
Deserialize()
void Deserialize ()
Definition at line 248 of file Inventory.c.
References ItemManager::DeserializeDefaultHeaderOpenStates(), ItemManager::DeserializeDefaultOpenStates(), and ItemManager::GetInstance().
Referenced by OnShow().
DisableMicromanagement()
void DisableMicromanagement ()
Definition at line 1116 of file Inventory.c.
References ItemManager::GetInstance(), ItemManager::IsMicromanagmentMode(), ItemManager::SetItemMicromanagmentMode(), ItemManager::SetSelectedItem(), and UpdateConsoleToolbar().
Referenced by UpdateInterval().
DraggingOverCenterPanel()
void DraggingOverCenterPanel (Widget w, int x, int y, Widget receiver)
Definition at line 568 of file Inventory.c.
References GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), InventoryLocation::GetType(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), InventoryLocation::IsValid(), name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), and ItemManager::ShowSourceDropzone().
DraggingOverHandsPanel()
void DraggingOverHandsPanel (Widget w, int x, int y, Widget receiver)
Definition at line 414 of file Inventory.c.
References HandsArea::DraggingOverHandsPanel(), ItemManager::GetInstance(), ItemManager::HideDropzones(), m_HandsArea, x, and y.
DraggingOverLeftPanel()
void DraggingOverLeftPanel (Widget w, int x, int y, Widget receiver)
Definition at line 558 of file Inventory.c.
References m_LeftArea, x, and y.
DraggingOverRightPanel()
void DraggingOverRightPanel (Widget w, int x, int y, Widget receiver)
Definition at line 563 of file Inventory.c.
References RightArea::DraggingOverHeader(), m_RightArea, x, and y.
EnableMicromanagement()
void EnableMicromanagement ()
Definition at line 1093 of file Inventory.c.
References ItemManager::GetInstance(), ItemManager::IsMicromanagmentMode(), m_HandsArea, m_LeftArea, m_RightArea, RightArea::SelectItem(), Container::SelectItem(), ItemManager::SetItemMicromanagmentMode(), and UpdateConsoleToolbar().
Referenced by Update(), and UpdateInterval().
GetInstance()
static Inventory GetInstance () static
Definition at line 237 of file Inventory.c.
References m_Instance.
GetPlayerAttachmentIndex() [1/2]
static int GetPlayerAttachmentIndex (int slot_id) static
Definition at line 259 of file Inventory.c.
References GetPlayerAttachmentIndex(), and InventorySlots::GetSlotName().
GetPlayerAttachmentIndex() [2/2]
static int GetPlayerAttachmentIndex (string slot_name) static
Definition at line 254 of file Inventory.c.
References m_PlayerAttachmentsIndexes.
Referenced by GetPlayerAttachmentIndex(), MoveAttachmentDown(), and MoveAttachmentUp().
GetProperControllerStickAngle()
protected int GetProperControllerStickAngle (int angle)
Definition at line 351 of file Inventory.c.
Referenced by Controller().
GetStringVariant()
string GetStringVariant (string pInputAction, notnull array< string > variants)
Picks from the strings by active input limiter variant in order: {click,hold,doubleclick}. Intended for inputs that check 'LocalPress' exclusively!!
Definition at line 1831 of file Inventory.c.
References ErrorEx, UAInputAPI::GetInputByName(), GetUApi(), UAInput::IsClickLimit(), UAInput::IsDoubleClickLimit(), UAInput::IsHoldBeginLimit(), UAInput::IsHoldLimit(), and UAInput::IsLimited().
Referenced by ConsoleToolbarTypeToString(), and UpdateConsoleToolbar().
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
pre-init arrays
Definition at line 1153 of file Inventory.c.
InitInputWrapperData()
void InitInputWrapperData ()
Definition at line 194 of file Inventory.c.
References GetUApi(), m_InvInputNames, m_InvInputTimes, m_InvInputWrappers, and m_InvInputWrappersCount.
Referenced by Inventory().
Inventory()
void Inventory (LayoutHolder parent)
Definition at line 127 of file Inventory.c.
References FindAnyWidget(), GetGame(), WidgetEventHandler::GetInstance(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), Mission::GetOnInputPresetChanged(), GetPlugin(), InputUtils::GetRichtextButtonIconFromInputAction(), CGame::GetUIManager(), InitInputWrapperData(), ScriptInvoker::Insert(), LoadPlayerAttachmentIndexes(), m_BottomConsoleToolbar, m_BottomConsoleToolbarRichText, m_ControllerRightStickTimer, m_HandsArea, m_Instance, m_LeftArea, m_PlayerPreview, m_Quickbar, m_QuickbarWidget, m_RightArea, m_SpecializationIcon, m_SpecializationPanel, m_TopConsoleToolbarEquipment, m_TopConsoleToolbarHands, m_TopConsoleToolbarVicinity, OnInputDeviceChanged(), OnInputPresetChanged(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), ResetFocusedContainers(), UIManager::ShowUICursor(), and UpdateConsoleToolbar().
Referenced by HandsContainer::AttachmentAdded(), ClosableContainer::AttachmentAddedEx(), HandsContainer::AttachmentRemoved(), ClosableContainer::AttachmentRemoved(), HandsPreview::CreateNewIcon(), HandsPreview::DeleteIcon(), InventoryMenu(), PlayerContainer::ItemAttached(), PlayerContainer::ItemDetached(), ZombieContainer::ItemDetached(), Container::MoveContainerDown(), Container::MoveContainerUp(), LayoutHolder::MoveGridCursor(), ClosableContainer::MoveGridCursor(), HandsContainer::OnSelectButton(), VicinityContainer::UpdateInterval(), and Container::UpdateSelection().
InventoryMovementButtonTickHandler()
void InventoryMovementButtonTickHandler (float timeslice)
Definition at line 1953 of file Inventory.c.
References BT_REPEAT_DELAY, BT_REPEAT_TIME, BT_THRESHOLD_VALUE, UAInput::LocalPress(), UAInput::LocalValue(), m_InvInputActive, m_InvInputTimes, m_InvInputWrappers, m_InvInputWrappersCount, m_InvUAInput, and m_SensitivityThreshold.
Referenced by Update().
LoadPlayerAttachmentIndexes()
protected void LoadPlayerAttachmentIndexes ()
Definition at line 264 of file Inventory.c.
References CGame::ConfigGetTextArray(), string::Get(), GetGame(), InventorySlots::GetSlotIdFromString(), m_PlayerAttachmentsIndexes, string::Replace(), and CGame::SetProfileString().
Referenced by Inventory().
MoveAttachmentDown()
static void MoveAttachmentDown (int slot_id) static
Definition at line 323 of file Inventory.c.
References GetGame(), CGame::GetPlayer(), GetPlayerAttachmentIndex(), InventorySlots::GetSlotIdFromString(), InventorySlots::GetSlotName(), m_Instance, and m_PlayerAttachmentsIndexes.
MoveAttachmentUp()
static void MoveAttachmentUp (int slot_id) static
Definition at line 295 of file Inventory.c.
References GetGame(), CGame::GetPlayer(), GetPlayerAttachmentIndex(), InventorySlots::GetSlotIdFromString(), InventorySlots::GetSlotName(), m_Instance, and m_PlayerAttachmentsIndexes.
MoveFocusByArea()
void MoveFocusByArea (int direction)
Shifts between vicinity-hands-player.
Definition at line 1876 of file Inventory.c.
References GetGame(), ItemManager::GetInstance(), GetPlayer(), ItemManager::IsMicromanagmentMode(), m_HandsArea, m_LeftArea, m_RightArea, Container::SetActive(), RightArea::UnfocusGrid(), and UpdateConsoleToolbar().
Referenced by UpdateInterval().
MoveFocusByContainer()
void MoveFocusByContainer (int direction)
Shifts between containers vertically.
Definition at line 1857 of file Inventory.c.
References m_HandsArea, m_LeftArea, and m_RightArea.
Referenced by UpdateInterval().
OnCenterPanelDropReceived()
void OnCenterPanelDropReceived (Widget w, int x, int y, Widget receiver)
Definition at line 463 of file Inventory.c.
References ActionTarget, GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), InventoryLocation::GetType(), InventoryLocation::IsValid(), name, ActionManagerClient::PerformActionStart(), string::Replace(), SplitItemUtils::TakeOrSplitToInventoryLocation(), and vector::Zero.
OnHandsPanelDropReceived()
void OnHandsPanelDropReceived (Widget w, int x, int y, Widget receiver)
Definition at line 420 of file Inventory.c.
References m_HandsArea, HandsArea::OnHandsPanelDropReceived(), x, and y.
OnHide()
override void OnHide ()
Definition at line 1218 of file Inventory.c.
References GetGame(), Mission::GetHud(), ItemManager::GetInstance(), CGame::GetMission(), mission, Serialize(), and ItemManager::SetSelectedItem().
OnInputDeviceChanged()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
Definition at line 216 of file Inventory.c.
References GetGame(), GetInput(), m_BottomConsoleToolbar, m_TopConsoleToolbarEquipment, m_TopConsoleToolbarHands, m_TopConsoleToolbarVicinity, and UpdateConsoleToolbar().
Referenced by ScriptedWidgetEventHandler::ActionTargetsCursor(), ServerBrowserTab::Construct(), UIScriptedMenu::InGameMenuXbox(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), Inventory(), ScriptedWidgetEventHandler::ItemActionsWidget(), and MissionBase::OnInit().
OnInputPresetChanged()
protected void OnInputPresetChanged ()
Definition at line 209 of file Inventory.c.
References UpdateConsoleToolbar().
Referenced by ScriptedWidgetEventHandler::ActionTargetsCursor(), UIScriptedMenu::GesturesMenu(), UIScriptedMenu::InGameMenuXbox(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), Inventory(), ScriptedWidgetEventHandler::ItemActionsWidget(), and UIScriptedMenu::RadialQuickbarMenu().
OnLeftPanelDropReceived()
void OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver)
Definition at line 425 of file Inventory.c.
References m_LeftArea, x, and y.
OnRightPanelDropReceived()
void OnRightPanelDropReceived (Widget w, int x, int y, Widget receiver)
Definition at line 430 of file Inventory.c.
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), name, string::Replace(), and SplitItemUtils::TakeOrSplitToInventory().
OnShow()
override void OnShow ()
Definition at line 1180 of file Inventory.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, Deserialize(), CGame::GetCallQueue(), GetGame(), Mission::GetHud(), CGame::GetMission(), GetPlayer(), m_HadFastTransferred, m_HadInspected, m_PlayerPreview, mission, PlayerPreview::RefreshPlayerPreview(), RefreshQuickbar(), ResetFocusedContainers(), SetFocus(), UpdateConsoleToolbar(), UpdateInterval(), and UpdateSpecialtyMeter().
Refresh()
override void Refresh ()
Definition at line 1255 of file Inventory.c.
References m_HandsArea, m_LeftArea, m_RightArea, HandsArea::Refresh(), RightArea::Refresh(), RefreshQuickbar(), and UpdateConsoleToolbar().
RefreshQuickbar()
void RefreshQuickbar ()
Definition at line 1265 of file Inventory.c.
References GetGame(), GetInput(), m_Quickbar, and m_QuickbarWidget.
Reset()
void Reset ()
Definition at line 1155 of file Inventory.c.
References m_HandsArea, m_LeftArea, m_RightArea, HandsArea::Refresh(), and RightArea::Refresh().
Referenced by Update().
ResetFocusedContainers()
void ResetFocusedContainers ()
Definition at line 1162 of file Inventory.c.
References m_HandsArea, m_LeftArea, m_RightArea, Container::SetActive(), and RightArea::UnfocusGrid().
Referenced by Inventory(), and OnShow().
Serialize()
void Serialize ()
Definition at line 242 of file Inventory.c.
References ItemManager::GetInstance(), ItemManager::SerializeDefaultHeaderOpenStates(), and ItemManager::SerializeDefaultOpenStates().
Referenced by OnHide().
SetLayoutName()
override void SetLayoutName ()
Definition at line 1127 of file Inventory.c.
References WidgetLayoutName::InventoryMedium, InventoryMenu(), WidgetLayoutName::InventoryNarrow, and WidgetLayoutName::InventoryWide.
TimerEnd()
void TimerEnd ()
Definition at line 378 of file Inventory.c.
References m_ControllerRightStickTimer, m_ControllerRightStickTimerEnd, and Timer::Stop().
Update()
void Update (float timeslice)
Definition at line 638 of file Inventory.c.
References EnableMicromanagement(), GetUApi(), INV_MOV_DOWN, INV_MOV_LEFT, INV_MOV_RIGHT, INV_MOV_UP, InventoryMovementButtonTickHandler(), m_HandsArea, m_InvInputActive, m_LeftArea, m_RightArea, and UpdateInterval().
UpdateConsoleToolbar()
void UpdateConsoleToolbar ()
Definition at line 1402 of file Inventory.c.
References Container::CanCombine(), PlayerContainer::CanCombine(), VicinitySlotsContainer::CanCombine(), Container::CanCombineAmmo(), VicinitySlotsContainer::CanCombineAmmo(), Container::CanEquip(), VicinitySlotsContainer::CanEquip(), ConsoleToolbarTypeToString(), RightArea::GetPlayerContainer(), InputUtils::GetRichtextButtonIconFromInputAction(), GetStringVariant(), VicinityContainer::GetVicinityIconsContainer(), InputUtils::ICON_SCALE_TOOLBAR, PlayerContainer::IsContainerWithCargoActive(), VicinityContainer::IsContainerWithCargoActive(), ZombieContainer::IsContainerWithCargoActive(), Container::IsEmpty(), PlayerContainer::IsEmptyItemActive(), VicinitySlotsContainer::IsEmptyItemActive(), ZombieContainer::IsEmptyItemActive(), AttachmentCategoriesContainer::IsHeaderActive(), Container::IsItemActive(), PlayerContainer::IsItemActive(), VicinitySlotsContainer::IsItemActive(), PlayerContainer::IsItemWithAttachmentsActive(), VicinityContainer::IsItemWithAttachmentsActive(), ZombieContainer::IsItemWithAttachmentsActive(), PlayerContainer::IsItemWithContainerActive(), VicinitySlotsContainer::IsItemWithContainerActive(), ZombieContainer::IsItemWithContainerActive(), Container::IsItemWithQuantityActive(), PlayerContainer::IsItemWithQuantityActive(), VicinitySlotsContainer::IsItemWithQuantityActive(), RightArea::IsPlayerEquipmentActive(), PlayerContainer::IsPlayerEquipmentActive(), VicinitySlotsContainer::IsTakeable(), VicinityContainer::IsVicinityContainerIconsActive(), IsVisible(), ZombieContainer::IsZombieEquipmentActive(), m_BottomConsoleToolbarRichText, m_HandsArea, m_LeftArea, m_RightArea, m_TopConsoleToolbarEquipment, m_TopConsoleToolbarHands, and m_TopConsoleToolbarVicinity.
Referenced by Controller(), DisableMicromanagement(), EnableMicromanagement(), Inventory(), MoveFocusByArea(), OnInputDeviceChanged(), OnInputPresetChanged(), OnShow(), Refresh(), and UpdateInterval().
UpdateInterval()
override void UpdateInterval ()
Definition at line 720 of file Inventory.c.
References AddQuickbarItem(), Container::CanCombine(), Container::CanCombineAmmo(), RightArea::Combine(), DisableMicromanagement(), EnableMicromanagement(), RightArea::EquipItem(), Container::EquipItem(), RightArea::ExpandCollapseContainer(), ItemManager::GetDraggedItem(), Container::GetFocusedItem(), GetGame(), ItemManager::GetHoveredItem(), ItemManager::GetInstance(), CGame::GetInventoryItemSize(), GetPlayer(), GetUApi(), Mission::HideInventory(), RightArea::InspectItem(), ItemManager::IsMicromanagmentMode(), IsVisible(), m_HadFastTransferred, m_HadInspected, m_HandsArea, m_HoldingQB, m_LeftArea, m_PlayerPreview, m_QBHoveredItems, m_RightArea, MENU_INVENTORY, MENU_RADIAL_QUICKBAR, mission, MoveFocusByArea(), MoveFocusByContainer(), RightArea::Select(), Container::Select(), Container::SetActive(), RightArea::SplitItem(), Container::SplitItem(), Container::TransferItem(), RightArea::TransferItemToVicinity(), Container::TransferItemToVicinity(), RightArea::UnfocusGrid(), UpdateConsoleToolbar(), HandsArea::UpdateInterval(), RightArea::UpdateInterval(), and PlayerPreview::UpdateInterval().
Referenced by OnShow(), and Update().
UpdateSpecialtyMeter()
void UpdateSpecialtyMeter ()
Definition at line 1235 of file Inventory.c.
References GetGame(), Mission::GetHud(), CGame::GetMission(), GetPlayer(), m_SpecializationIcon, mission, x, and y.
Referenced by OnShow().
Variable Documentation
BT_REPEAT_DELAY
const float BT_REPEAT_DELAY = 0.35
Definition at line 112 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler().
BT_REPEAT_TIME
const float BT_REPEAT_TIME = 0.09
Definition at line 113 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler().
BT_THRESHOLD_VALUE
const float BT_THRESHOLD_VALUE = 0.8
Definition at line 114 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler().
HANDS_ITEM
enum Direction HANDS_ITEM
HANDS_ITEM_EMPTY
enum Direction HANDS_ITEM_EMPTY
HANDS_ITEM_NO_EQUIP
enum Direction HANDS_ITEM_NO_EQUIP
HANDS_ITEM_WITH_QUANTITY
enum Direction HANDS_ITEM_WITH_QUANTITY
INV_MOV_DOWN
const int INV_MOV_DOWN = 3
Definition at line 118 of file Inventory.c.
Referenced by Update().
INV_MOV_LEFT
const int INV_MOV_LEFT = 0
Definition at line 115 of file Inventory.c.
Referenced by Update().
INV_MOV_RIGHT
const int INV_MOV_RIGHT = 1
Definition at line 116 of file Inventory.c.
Referenced by Update().
INV_MOV_UP
const int INV_MOV_UP = 2
Definition at line 117 of file Inventory.c.
Referenced by Update().
m_BottomConsoleToolbar
protected Widget m_BottomConsoleToolbar
Definition at line 92 of file Inventory.c.
Referenced by Inventory(), and OnInputDeviceChanged().
m_BottomConsoleToolbarRichText
protected RichTextWidget m_BottomConsoleToolbarRichText
Definition at line 93 of file Inventory.c.
Referenced by Inventory(), and UpdateConsoleToolbar().
m_ContextMenu
protected ref ContextMenu m_ContextMenu
Definition at line 95 of file Inventory.c.
m_ControllerAngle
protected int m_ControllerAngle
Definition at line 103 of file Inventory.c.
m_ControllerRightStickTimer
protected ref Timer m_ControllerRightStickTimer
Definition at line 106 of file Inventory.c.
Referenced by Controller(), Inventory(), and TimerEnd().
m_ControllerRightStickTimerEnd
protected bool m_ControllerRightStickTimerEnd = true
Definition at line 105 of file Inventory.c.
Referenced by Controller(), and TimerEnd().
m_ControllerTilt
protected int m_ControllerTilt
Definition at line 104 of file Inventory.c.
m_HadFastTransferred
protected bool m_HadFastTransferred
Definition at line 98 of file Inventory.c.
Referenced by OnShow(), and UpdateInterval().
m_HadInspected
protected bool m_HadInspected
Definition at line 99 of file Inventory.c.
Referenced by OnShow(), and UpdateInterval().
m_HandsArea
protected ref HandsArea m_HandsArea
Definition at line 82 of file Inventory.c.
Referenced by DraggingOverHandsPanel(), EnableMicromanagement(), Inventory(), MoveFocusByArea(), MoveFocusByContainer(), OnHandsPanelDropReceived(), Refresh(), Reset(), ResetFocusedContainers(), Update(), UpdateConsoleToolbar(), and UpdateInterval().
m_HoldingQB
protected bool m_HoldingQB
Definition at line 108 of file Inventory.c.
Referenced by UpdateInterval().
m_InpInp
UAInput m_InpInp = null
Definition at line 719 of file Inventory.c.
m_Instance
protected Inventory m_Instance static
Definition at line 101 of file Inventory.c.
m_InvInputActive
int m_InvInputActive = 0
Definition at line 125 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler(), and Update().
m_InvInputNames
protected ref array<string> m_InvInputNames = {"UAUILeftInventory","UAUIRightInventory","UAUIUpInventory","UAUIDownInventory"}
Definition at line 119 of file Inventory.c.
Referenced by InitInputWrapperData().
m_InvInputTimes
protected ref array<float> m_InvInputTimes
Definition at line 121 of file Inventory.c.
Referenced by InitInputWrapperData(), and InventoryMovementButtonTickHandler().
m_InvInputWrappers
protected ref array<UAIDWrapper> m_InvInputWrappers
Definition at line 120 of file Inventory.c.
Referenced by InitInputWrapperData(), and InventoryMovementButtonTickHandler().
m_InvInputWrappersCount
protected int m_InvInputWrappersCount
Definition at line 122 of file Inventory.c.
Referenced by InitInputWrapperData(), and InventoryMovementButtonTickHandler().
m_InvUAInput
UAInput m_InvUAInput
Definition at line 124 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler().
m_LeftArea
enum Direction m_LeftArea
Referenced by DraggingOverLeftPanel(), EnableMicromanagement(), Inventory(), MoveFocusByArea(), MoveFocusByContainer(), OnLeftPanelDropReceived(), Refresh(), Reset(), ResetFocusedContainers(), Update(), UpdateConsoleToolbar(), and UpdateInterval().
m_PlayerAttachmentsIndexes
protected ref map<string, int> m_PlayerAttachmentsIndexes static
Definition at line 96 of file Inventory.c.
Referenced by GetPlayerAttachmentIndex(), LoadPlayerAttachmentIndexes(), MoveAttachmentDown(), and MoveAttachmentUp().
m_PlayerPreview
protected ref PlayerPreview m_PlayerPreview
Definition at line 83 of file Inventory.c.
Referenced by Inventory(), OnShow(), and UpdateInterval().
m_QBHoveredItems
protected InventoryItem m_QBHoveredItems
Definition at line 109 of file Inventory.c.
Referenced by UpdateInterval().
m_Quickbar
protected ref InventoryQuickbar m_Quickbar
Definition at line 84 of file Inventory.c.
Referenced by Hud::InitQuickbar(), Inventory(), RefreshQuickbar(), and Hud::RefreshQuickbar().
m_QuickbarWidget
protected Widget m_QuickbarWidget
Definition at line 86 of file Inventory.c.
Referenced by Hud::Init(), Hud::InitQuickbar(), Inventory(), RefreshQuickbar(), Hud::RefreshQuickbar(), and Hud::RefreshQuickbarVisibility().
m_RightArea
protected ref RightArea m_RightArea
Definition at line 81 of file Inventory.c.
Referenced by DraggingOverRightPanel(), EnableMicromanagement(), Inventory(), MoveFocusByArea(), MoveFocusByContainer(), Refresh(), Reset(), ResetFocusedContainers(), Update(), UpdateConsoleToolbar(), and UpdateInterval().
m_SensitivityThreshold
protected float m_SensitivityThreshold = 0.0
Definition at line 123 of file Inventory.c.
Referenced by InventoryMovementButtonTickHandler().
m_SpecializationIcon
protected Widget m_SpecializationIcon
Definition at line 88 of file Inventory.c.
Referenced by Hud::Init(), Inventory(), UpdateSpecialtyMeter(), and Hud::UpdateSpecialtyMeter().
m_SpecializationPanel
protected Widget m_SpecializationPanel
Definition at line 87 of file Inventory.c.
Referenced by Inventory().
m_TopConsoleToolbarEquipment
protected Widget m_TopConsoleToolbarEquipment
Definition at line 91 of file Inventory.c.
Referenced by Inventory(), OnInputDeviceChanged(), and UpdateConsoleToolbar().
m_TopConsoleToolbarHands
protected Widget m_TopConsoleToolbarHands
Definition at line 90 of file Inventory.c.
Referenced by Inventory(), OnInputDeviceChanged(), and UpdateConsoleToolbar().
m_TopConsoleToolbarVicinity
protected Widget m_TopConsoleToolbarVicinity
Definition at line 89 of file Inventory.c.
Referenced by Inventory(), OnInputDeviceChanged(), and UpdateConsoleToolbar().
PLAYER_CARGO_CONTAINER_EMPTY_CONTAINER
enum Direction PLAYER_CARGO_CONTAINER_EMPTY_CONTAINER
PLAYER_CARGO_CONTAINER_ITEM
enum Direction PLAYER_CARGO_CONTAINER_ITEM
PLAYER_CARGO_CONTAINER_ITEM_NO_EQUIP
enum Direction PLAYER_CARGO_CONTAINER_ITEM_NO_EQUIP
PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS
enum Direction PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS
PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS_NO_EQUIP
enum Direction PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS_NO_EQUIP
PLAYER_CARGO_CONTAINER_ITEM_WITH_QUANTITY
enum Direction PLAYER_CARGO_CONTAINER_ITEM_WITH_QUANTITY
PLAYER_EQUIPMENT_SLOTS_ITEM
enum Direction PLAYER_EQUIPMENT_SLOTS_ITEM
PLAYER_EQUIPMENT_SLOTS_ITEM_FREE
enum Direction PLAYER_EQUIPMENT_SLOTS_ITEM_FREE
PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_ATTACHMENTS
enum Direction PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_ATTACHMENTS
PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_CARGO
enum Direction PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_CARGO
PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_QUANTITY
enum Direction PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_QUANTITY
PLAYER_ITEM_WITH_ATTACHMENTS_CONTAINER_ITEM
enum Direction PLAYER_ITEM_WITH_ATTACHMENTS_CONTAINER_ITEM
VICINITY_CONTAINER_DETAILS_EMPTY
enum Direction VICINITY_CONTAINER_DETAILS_EMPTY
VICINITY_CONTAINER_DETAILS_ITEM
enum Direction VICINITY_CONTAINER_DETAILS_ITEM
VICINITY_CONTAINER_DETAILS_ITEM_NO_EQUIP
enum Direction VICINITY_CONTAINER_DETAILS_ITEM_NO_EQUIP
VICINITY_CONTAINER_LIST_EMPTY_ITEM
enum Direction VICINITY_CONTAINER_LIST_EMPTY_ITEM
VICINITY_CONTAINER_LIST_HEADER
enum Direction VICINITY_CONTAINER_LIST_HEADER
VICINITY_CONTAINER_LIST_ITEM
enum Direction VICINITY_CONTAINER_LIST_ITEM
VICINITY_CONTAINER_LIST_ITEM_NO_EQUIP
enum Direction VICINITY_CONTAINER_LIST_ITEM_NO_EQUIP
VICINITY_CONTAINER_LIST_ITEM_WITH_CONTAINER
enum Direction VICINITY_CONTAINER_LIST_ITEM_WITH_CONTAINER
VICINITY_CONTAINER_LIST_ITEM_WITH_CONTAINER_NO_EQUIP
enum Direction VICINITY_CONTAINER_LIST_ITEM_WITH_CONTAINER_NO_EQUIP
VICINITY_CONTAINER_LIST_ITEM_WITH_QUANTITY
enum Direction VICINITY_CONTAINER_LIST_ITEM_WITH_QUANTITY
VICNITY_PLAYER_CARGO_CONTAINER_EMPTY_CONTAINER
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_EMPTY_CONTAINER
VICNITY_PLAYER_CARGO_CONTAINER_ITEM
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_ITEM
VICNITY_PLAYER_CARGO_CONTAINER_ITEM_NO_EQUIP
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_ITEM_NO_EQUIP
VICNITY_PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS
VICNITY_PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS_NO_EQUIP
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS_NO_EQUIP
VICNITY_PLAYER_CARGO_CONTAINER_ITEM_WITH_QUANTITY
enum Direction VICNITY_PLAYER_CARGO_CONTAINER_ITEM_WITH_QUANTITY
VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM
enum Direction VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM
VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM_FREE
enum Direction VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM_FREE
VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_ATTACHMENTS
enum Direction VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_ATTACHMENTS
VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_CARGO
enum Direction VICNITY_PLAYER_EQUIPMENT_SLOTS_ITEM_WITH_CARGO
VICNITY_PLAYER_ITEM_WITH_ATTACHMENTS_CONTAINER_ITEM
enum Direction VICNITY_PLAYER_ITEM_WITH_ATTACHMENTS_CONTAINER_ITEM
VICNITY_ZOMBIE_CARGO_CONTAINER_EMPTY_CONTAINER
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_EMPTY_CONTAINER
VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM
VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_NO_EQUIP
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_NO_EQUIP
VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS
VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS_NO_EQUIP
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_WITH_ATTACHMENTS_NO_EQUIP
VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_WITH_QUANTITY
enum Direction VICNITY_ZOMBIE_CARGO_CONTAINER_ITEM_WITH_QUANTITY
VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM
enum Direction VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM
VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM_FREE
enum Direction VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM_FREE
VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM_WITH_ATTACHMENTS
enum Direction VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM_WITH_ATTACHMENTS
VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM_WITH_CARGO
enum Direction VICNITY_ZOMBIE_EQUIPMENT_SLOTS_ITEM_WITH_CARGO
VICNITY_ZOMBIE_ITEM_WITH_ATTACHMENTS_CONTAINER_ITEM
enum Direction VICNITY_ZOMBIE_ITEM_WITH_ATTACHMENTS_CONTAINER_ITEM