DayZ Scripts: WeaponEventBase Class Reference
WeaponEventBase Class Reference
signalize mechanism manipulation
Private Member Functions
void WeaponEventBase (DayZPlayer p=NULL, Magazine m=NULL)
WeaponEventID GetEventID ()
returns id from enum WeaponEventID
WeaponEvents GetAnimEvent ()
returns animation event from anim engine,
int GetPackedType ()
returns eventID in upper 16 bits and AnimEvent in lower 16 bits
void ReadFromContext (ParamsReadContext ctx)
void WriteToContext (ParamsWriteContext ctx)
string DumpToString ()
void WeaponEventMechanism (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventTrigger (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventTriggerToJam (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventTriggerAutoStart (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventTriggerAutoEnd (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventLoad1Bullet (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventContinuousLoadBulletStart (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventContinuousLoadBulletEnd (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventUnjam (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventAttachMagazine (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventUnjammingFailedTimeout (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventUnjammingTimeout (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventDetachMagazine (DayZPlayer p=NULL, Magazine m=NULL, InventoryLocation il=NULL)
override void ReadFromContext (ParamsReadContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
void WeaponEventSwapMagazine (DayZPlayer p=NULL, Magazine m=NULL, InventoryLocation il=NULL)
override void ReadFromContext (ParamsReadContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
void WeaponEventHumanCommandActionFinished (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventHumanCommandActionAborted (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventReloadTimeout (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventDryFireTimeout (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventSetNextMuzzleMode (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventAnimation (DayZPlayer p=NULL, Magazine m=NULL)
animation event from Human.WeaponEvents
override int GetAnimEvent ()
Private Attributes
int m_eventID
DayZPlayer m_player
Magazine m_magazine
ref InventoryLocation m_dst
WeaponEvents m_type
Detailed Description
signalize mechanism manipulation
represents event that triggers transition from state to state
triggered when dry fire timer expires
triggered when reload timer expires
triggered when animation action aborts
triggered when animation action finishes
event when user wants to swap magazine
event when user wants to detach magazine
triggered when unjamming failed timer expires
triggered when unjamming timer expires
event when user wants to attach magazine
event when user wants to unjam weapon
event when user wants to end loading of bullets
event when user wants to load N bullets
event when user wants to load 1 bullet
event when trigger pressed
Parameters
dst inventory location where the magazine will be stored
Definition at line 34 of file Events.c.
Constructor & Destructor Documentation
WeaponEventBase()
void WeaponEventBase (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 40 of file Events.c.
References m_eventID, m_magazine, and m_player.
Member Function Documentation
DumpToString()
string DumpToString () inline private
Definition at line 62 of file Events.c.
References GetEventID(), m_magazine, and m_player.
Referenced by DeferredWeaponFailed(), HandleWeaponEvents(), and PostWeaponEvent().
GetAnimEvent() [1/2]
WeaponEvents GetAnimEvent () inline private
returns animation event from anim engine,
See also
WeaponEvents
Definition at line 44 of file Events.c.
Referenced by GetPackedType().
GetAnimEvent() [2/2]
override int GetAnimEvent () inline private
Definition at line 219 of file Events.c.
GetEventID()
WeaponEventID GetEventID () inline private
returns id from enum WeaponEventID
Definition at line 42 of file Events.c.
References m_eventID.
Referenced by DumpToString(), OnEventForRemoteWeapon(), Weapon::ProcessWeaponEvent(), and Weapon::SyncEventToRemote().
GetPackedType()
int GetPackedType () inline private
returns eventID in upper 16 bits and AnimEvent in lower 16 bits
Definition at line 46 of file Events.c.
References GetAnimEvent(), and m_eventID.
Referenced by WriteToContext().
ReadFromContext() [1/3]
void ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 53 of file Events.c.
Referenced by CreateWeaponEventFromContext().
ReadFromContext() [2/3]
override void ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 152 of file Events.c.
References m_dst, and InventoryLocation::ReadFromContext().
ReadFromContext() [3/3]
override void ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 171 of file Events.c.
References m_dst, and InventoryLocation::ReadFromContext().
WeaponEventAnimation()
void WeaponEventAnimation (DayZPlayer p = NULL, Magazine m = NULL) inline private
animation event from Human.WeaponEvents
Definition at line 218 of file Events.c.
WeaponEventAttachMagazine()
void WeaponEventAttachMagazine (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 130 of file Events.c.
WeaponEventContinuousLoadBulletEnd()
void WeaponEventContinuousLoadBulletEnd (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 118 of file Events.c.
WeaponEventContinuousLoadBulletStart()
void WeaponEventContinuousLoadBulletStart (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 112 of file Events.c.
WeaponEventDetachMagazine()
void WeaponEventDetachMagazine (DayZPlayer p = NULL, Magazine m = NULL, InventoryLocation il = NULL) inline private
Definition at line 150 of file Events.c.
References m_dst.
WeaponEventDryFireTimeout()
void WeaponEventDryFireTimeout (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 205 of file Events.c.
WeaponEventHumanCommandActionAborted()
void WeaponEventHumanCommandActionAborted (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 193 of file Events.c.
WeaponEventHumanCommandActionFinished()
void WeaponEventHumanCommandActionFinished (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 187 of file Events.c.
WeaponEventLoad1Bullet()
void WeaponEventLoad1Bullet (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 106 of file Events.c.
WeaponEventMechanism()
void WeaponEventMechanism (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 76 of file Events.c.
WeaponEventReloadTimeout()
void WeaponEventReloadTimeout (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 199 of file Events.c.
WeaponEventSetNextMuzzleMode()
void WeaponEventSetNextMuzzleMode (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 212 of file Events.c.
WeaponEventSwapMagazine()
void WeaponEventSwapMagazine (DayZPlayer p = NULL, Magazine m = NULL, InventoryLocation il = NULL) inline private
Definition at line 169 of file Events.c.
References m_dst.
WeaponEventTrigger()
void WeaponEventTrigger (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 82 of file Events.c.
WeaponEventTriggerAutoEnd()
void WeaponEventTriggerAutoEnd (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 100 of file Events.c.
WeaponEventTriggerAutoStart()
void WeaponEventTriggerAutoStart (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 94 of file Events.c.
WeaponEventTriggerToJam()
void WeaponEventTriggerToJam (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 88 of file Events.c.
WeaponEventUnjam()
void WeaponEventUnjam (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 124 of file Events.c.
WeaponEventUnjammingFailedTimeout()
void WeaponEventUnjammingFailedTimeout (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 136 of file Events.c.
WeaponEventUnjammingTimeout()
void WeaponEventUnjammingTimeout (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 142 of file Events.c.
WriteToContext() [1/3]
void WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 54 of file Events.c.
References GetPackedType(), m_magazine, m_player, and Serializer::Write().
Referenced by Weapon::SyncEventToRemote().
WriteToContext() [2/3]
override void WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 158 of file Events.c.
References m_dst, and InventoryLocation::WriteToContext().
WriteToContext() [3/3]
override void WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 177 of file Events.c.
References m_dst, and InventoryLocation::WriteToContext().
Field Documentation
m_dst
ref InventoryLocation m_dst private
Definition at line 149 of file Events.c.
m_eventID
int m_eventID private
Definition at line 36 of file Events.c.
Referenced by GetEventID(), GetPackedType(), and WeaponEventBase().
m_magazine
Magazine m_magazine private
Definition at line 38 of file Events.c.
Referenced by DumpToString(), WeaponGuardBase::GuardCondition(), WeaponStateBase::OnEntry(), Weapon::SyncEventToRemote(), WeaponEventBase(), and WriteToContext().
m_player
DayZPlayer m_player private
Definition at line 37 of file Events.c.
Referenced by DumpToString(), WeaponGuardBase::GuardCondition(), WeaponStateBase::OnAbort(), WeaponChambering_Base::OnAbort(), OnAbort(), WeaponStateBase::OnEntry(), WeaponStartAction::OnEntry(), WeaponFire::OnEntry(), OnEntry(), WeaponStateBase::OnExit(), Weapon::SyncEventToRemote(), WeaponEventBase(), and WriteToContext().
m_type
WeaponEvents m_type private
Definition at line 217 of file Events.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Firearms/FSM/Events.c