DayZ Scripts: PPEClassBase Class Reference
PPEClassBase Class Reference
Created once, on manager init. Script-side representation of C++ material class, separate handling.
Private Member Functions
void PPEClassBase (string mat_path_override="")
protected void Init (string mat_path_override="")
protected void CreateMaterial ()
Material GetMaterial ()
protected void CreateDataStructure ()
protected void RegisterMaterialParameters ()
inserted into associative array by parameter int value, parameter registration order does not matter (still ordered, though)
protected void RegisterParameterScalarBool (int idx, string parameter_name, bool default_value)
protected void RegisterParameterScalarInt (int idx, string parameter_name, int default_value, int min, int max)
protected void RegisterParameterScalarFloat (int idx, string parameter_name, float default_value, float min, float max)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
protected void RegisterParameterScalarFloatEx (int idx, string parameter_name, float default_value, float min, float max, typename type)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
protected void RegisterParameterColor (int idx, string parameter_name, float r, float g, float b, float a)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
protected void RegisterParameterColorEx (int idx, string parameter_name, float r, float g, float b, float a, typename type)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
protected void RegisterParameterVector (int idx, string parameter_name, array< float > default_values)
protected void RegisterParameterTexture (int idx, string parameter_name, string default_path)
protected void RegisterParameterResource (int idx, string parameter_name, string default_path)
void InsertParamValueData (PPERequestParamDataBase request_data)
Distributes requester data to the material class structure and links them to appropriate parameter.
void RemoveRequest (int req_idx)
unused, see 'RemoveActiveRequestFromMaterials' for more info
void OnUpdate (float timeslice, int order)
generic update method, take care when overriding!
void SetFinalParameterValue (int parameter_idx)
Clamps the values being set to defaults, if there is no request setting non-zero values on the parameter.
void ApplyValueChanges ()
protected void InsertUpdatedParameter (int mat_id)
void ParamUpdateRemove (int parameter_idx)
Queue selected parameter for removal from the update queue.
void SetParameterUpdating (int order, int parameter_id)
Queue specific parameter of this material to update.
protected void ParamUpdateQueueCleanup (int order)
string GetDefaultMaterialPath ()
override this if you want to use different path by default; '.emat' is appended automatically
void ChangeMaterialPathUsed (string path)
string GetCurrentMaterialPath ()
int GetPostProcessEffectID ()
Overriden in all material classes!
PPEMatClassParameterCommandData GetParameterCommandData (int parameter_idx)
Some PP effects are handled as hard-coded exceptions, outside of material system. Default == PPEExceptions.NONE (systemic behaviour)
void DbgPrnt (string text)
Private Attributes
protected PPEManager m_Manager
protected string m_MaterialPath = ""
protected Material m_Material
protected ref map< int, ref array< int > > m_ParameterUpdateQueueMap
protected ref array< int > m_ParameterRemovalQueue
protected ref array< int > m_UpdatedParameters
protected ref map< int, ref PPEMatClassParameterCommandData > m_MaterialParamMapStructure
Detailed Description
Created once, on manager init. Script-side representation of C++ material class, separate handling.
Definition at line 2 of file PPEMatClassesBase.c.
Constructor & Destructor Documentation
PPEClassBase()
void PPEClassBase (string mat_path_override = "") inline private
Definition at line 14 of file PPEMatClassesBase.c.
References CreateDataStructure(), CreateMaterial(), Init(), and RegisterMaterialParameters().
Member Function Documentation
ApplyValueChanges()
void ApplyValueChanges () inline private
Definition at line 269 of file PPEMatClassesBase.c.
References m_UpdatedParameters, and SetFinalParameterValue().
Referenced by ProcessApplyValueChanges().
ChangeMaterialPathUsed()
void ChangeMaterialPathUsed (string path) inline private
Definition at line 326 of file PPEMatClassesBase.c.
References CreateMaterial(), m_Material, m_MaterialPath, and path.
Referenced by ChangePPEMaterial().
CreateDataStructure()
protected void CreateDataStructure () inline private
Definition at line 47 of file PPEMatClassesBase.c.
References m_MaterialParamMapStructure, m_ParameterRemovalQueue, m_ParameterUpdateQueueMap, and m_UpdatedParameters.
Referenced by PPEClassBase().
CreateMaterial()
protected void CreateMaterial () inline private
Definition at line 35 of file PPEMatClassesBase.c.
References GetGame(), World::GetMaterial(), CGame::GetWorld(), m_Material, and m_MaterialPath.
Referenced by ChangeMaterialPathUsed(), and PPEClassBase().
DbgPrnt()
void DbgPrnt (string text) inline private
Definition at line 380 of file PPEMatClassesBase.c.
GetCurrentMaterialPath()
string GetCurrentMaterialPath () inline private
Definition at line 333 of file PPEMatClassesBase.c.
References m_MaterialPath.
GetDefaultMaterialPath()
string GetDefaultMaterialPath () private
override this if you want to use different path by default; '.emat' is appended automatically
Referenced by Init().
GetMaterial()
Material GetMaterial () inline private
Definition at line 41 of file PPEMatClassesBase.c.
References m_Material.
Referenced by ChangePPEMaterial().
GetParameterCommandData()
PPEMatClassParameterCommandData GetParameterCommandData (int parameter_idx) inline private
Some PP effects are handled as hard-coded exceptions, outside of material system. Default == PPEExceptions.NONE (systemic behaviour)
Definition at line 350 of file PPEMatClassesBase.c.
References m_MaterialParamMapStructure.
Referenced by GetPostProcessCurrentValues(), GetPostProcessDefaultValues(), PPEDOF::SetFinalParameterValue(), PPEExposureNative::SetFinalParameterValue(), PPEEyeAccomodationNative::SetFinalParameterValue(), PPELightIntensityParamsNative::SetFinalParameterValue(), and SetFinalParameterValue().
GetPostProcessEffectID()
int GetPostProcessEffectID () inline private
Overriden in all material classes!
Definition at line 339 of file PPEMatClassesBase.c.
Referenced by InsertParamValueData(), OnUpdate(), RegisterParameterColor(), RegisterParameterColorEx(), RegisterParameterResource(), RegisterParameterScalarBool(), RegisterParameterScalarFloat(), RegisterParameterScalarFloatEx(), RegisterParameterScalarInt(), RegisterParameterTexture(), RegisterParameterVector(), and RegisterPPEClass().
Init()
protected void Init (string mat_path_override = "") inline private
Definition at line 22 of file PPEMatClassesBase.c.
References GetDefaultMaterialPath(), PPEManagerStatic::GetPPEManager(), m_Manager, and m_MaterialPath.
InsertParamValueData()
void InsertParamValueData (PPERequestParamDataBase request_data) inline private
Distributes requester data to the material class structure and links them to appropriate parameter.
Definition at line 151 of file PPEMatClassesBase.c.
References Error(), PPERequestParamDataBase::GetParameterID(), GetPostProcessEffectID(), PPERequestParamDataBase::GetRequesterIDX(), PPEMatClassParameterCommandData::InsertRequestData(), m_MaterialParamMapStructure, PPERequestParamDataBase::SetDataActive(), and PPERequestParamDataBase::SetUpdatingDataValues().
Referenced by SendMaterialValueData().
InsertUpdatedParameter()
protected void InsertUpdatedParameter (int mat_id) inline private
Definition at line 281 of file PPEMatClassesBase.c.
References m_UpdatedParameters.
Referenced by OnUpdate().
OnUpdate()
void OnUpdate (float timeslice, int order) inline private
generic update method, take care when overriding!
Definition at line 201 of file PPEMatClassesBase.c.
References Count, GetPostProcessEffectID(), InsertUpdatedParameter(), m_Manager, m_MaterialParamMapStructure, m_ParameterUpdateQueueMap, and ParamUpdateQueueCleanup().
Referenced by ProcessMaterialUpdates().
ParamUpdateQueueCleanup()
protected void ParamUpdateQueueCleanup (int order) inline private
Definition at line 308 of file PPEMatClassesBase.c.
References Count, m_ParameterRemovalQueue, and m_ParameterUpdateQueueMap.
Referenced by OnUpdate().
ParamUpdateRemove()
void ParamUpdateRemove (int parameter_idx) inline private
Queue selected parameter for removal from the update queue.
Definition at line 288 of file PPEMatClassesBase.c.
References m_ParameterRemovalQueue.
RegisterMaterialParameters()
protected void RegisterMaterialParameters () private
inserted into associative array by parameter int value, parameter registration order does not matter (still ordered, though)
Referenced by PPEClassBase().
RegisterParameterColor()
protected void RegisterParameterColor (int idx, string parameter_name, float r, float g, float b, float a) inline private
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
Definition at line 102 of file PPEMatClassesBase.c.
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
Referenced by PPEColors::RegisterMaterialParameters(), and PPEGlow::RegisterMaterialParameters().
RegisterParameterColorEx()
protected void RegisterParameterColorEx (int idx, string parameter_name, float r, float g, float b, float a, typename type) inline private
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
Definition at line 111 of file PPEMatClassesBase.c.
References Class::CastTo(), GetPostProcessEffectID(), and m_MaterialParamMapStructure.
Referenced by PPEColors::RegisterMaterialParameters(), and PPEGlow::RegisterMaterialParameters().
RegisterParameterResource()
protected void RegisterParameterResource (int idx, string parameter_name, string default_path) inline private
Definition at line 141 of file PPEMatClassesBase.c.
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
RegisterParameterScalarBool()
protected void RegisterParameterScalarBool (int idx, string parameter_name, bool default_value) inline private
Definition at line 59 of file PPEMatClassesBase.c.
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
Referenced by PPEDOF::RegisterMaterialParameters(), PPEDepthOfField::RegisterMaterialParameters(), PPEFilmGrain::RegisterMaterialParameters(), PPEGlow::RegisterMaterialParameters(), and PPEHBAO::RegisterMaterialParameters().
RegisterParameterScalarFloat()
protected void RegisterParameterScalarFloat (int idx, string parameter_name, float default_value, float min, float max) inline private
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
Definition at line 77 of file PPEMatClassesBase.c.
References GetPostProcessEffectID(), m_MaterialParamMapStructure, and PPEMatClassParameterFloat().
Referenced by PPEDOF::RegisterMaterialParameters(), PPEExposureNative::RegisterMaterialParameters(), PPEEyeAccomodationNative::RegisterMaterialParameters(), PPELightIntensityParamsNative::RegisterMaterialParameters(), PPEChromAber::RegisterMaterialParameters(), PPEColors::RegisterMaterialParameters(), PPEDepthOfField::RegisterMaterialParameters(), PPEDynamicBlur::RegisterMaterialParameters(), PPEFilmGrain::RegisterMaterialParameters(), PPEGaussFilter::RegisterMaterialParameters(), PPEGlow::RegisterMaterialParameters(), PPEGodRays::RegisterMaterialParameters(), PPEHBAO::RegisterMaterialParameters(), PPERadialBlur::RegisterMaterialParameters(), PPERain::RegisterMaterialParameters(), PPERotBlur::RegisterMaterialParameters(), PPESSAO::RegisterMaterialParameters(), PPEUnderWater::RegisterMaterialParameters(), and PPEWetDistort::RegisterMaterialParameters().
RegisterParameterScalarFloatEx()
protected void RegisterParameterScalarFloatEx (int idx, string parameter_name, float default_value, float min, float max, typename type) inline private
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
Definition at line 87 of file PPEMatClassesBase.c.
References Class::CastTo(), GetPostProcessEffectID(), m_MaterialParamMapStructure, and PPEMatClassParameterFloat().
Referenced by PPEColors::RegisterMaterialParameters(), and PPEGlow::RegisterMaterialParameters().
RegisterParameterScalarInt()
protected void RegisterParameterScalarInt (int idx, string parameter_name, int default_value, int min, int max) inline private
Definition at line 67 of file PPEMatClassesBase.c.
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
Referenced by PPEDepthOfField::RegisterMaterialParameters(), PPEFXAA::RegisterMaterialParameters(), PPEGlow::RegisterMaterialParameters(), PPEHBAO::RegisterMaterialParameters(), PPEMedian::RegisterMaterialParameters(), PPESMAA::RegisterMaterialParameters(), PPESSAO::RegisterMaterialParameters(), and PPEWetDistort::RegisterMaterialParameters().
RegisterParameterTexture()
protected void RegisterParameterTexture (int idx, string parameter_name, string default_path) inline private
Definition at line 133 of file PPEMatClassesBase.c.
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
RegisterParameterVector()
protected void RegisterParameterVector (int idx, string parameter_name, array< float > default_values) inline private
Definition at line 124 of file PPEMatClassesBase.c.
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
Referenced by PPEColors::RegisterMaterialParameters(), and PPEGlow::RegisterMaterialParameters().
RemoveRequest()
void RemoveRequest (int req_idx) inline private
unused, see 'RemoveActiveRequestFromMaterials' for more info
Definition at line 170 of file PPEMatClassesBase.c.
Referenced by RemoveActiveRequestFromMaterials().
SetFinalParameterValue()
void SetFinalParameterValue (int parameter_idx) inline private
Clamps the values being set to defaults, if there is no request setting non-zero values on the parameter.
Definition at line 228 of file PPEMatClassesBase.c.
References PPEMatClassParameterCommandData::GetCurrentValues(), GetParameterCommandData(), PPEMatClassParameterCommandData::GetParameterVarType(), m_Material, Param::param1, and Material::SetParamByIndex().
Referenced by ApplyValueChanges().
SetParameterUpdating()
void SetParameterUpdating (int order, int parameter_id) inline private
Queue specific parameter of this material to update.
Definition at line 295 of file PPEMatClassesBase.c.
References m_ParameterUpdateQueueMap.
Referenced by SetMaterialParamUpdating().
Field Documentation
m_Manager
protected PPEManager m_Manager private
Definition at line 4 of file PPEMatClassesBase.c.
Referenced by Init(), and OnUpdate().
m_Material
protected Material m_Material private
Definition at line 6 of file PPEMatClassesBase.c.
Referenced by ChangeMaterialPathUsed(), CreateMaterial(), GetMaterial(), and SetFinalParameterValue().
m_MaterialParamMapStructure
protected ref map<int,ref PPEMatClassParameterCommandData> m_MaterialParamMapStructure private
Definition at line 12 of file PPEMatClassesBase.c.
Referenced by CreateDataStructure(), GetParameterCommandData(), InsertParamValueData(), OnUpdate(), RegisterParameterColor(), RegisterParameterColorEx(), RegisterParameterResource(), RegisterParameterScalarBool(), RegisterParameterScalarFloat(), RegisterParameterScalarFloatEx(), RegisterParameterScalarInt(), RegisterParameterTexture(), and RegisterParameterVector().
m_MaterialPath
protected string m_MaterialPath = "" private
Definition at line 5 of file PPEMatClassesBase.c.
Referenced by ChangeMaterialPathUsed(), CreateMaterial(), GetCurrentMaterialPath(), and Init().
m_ParameterRemovalQueue
protected ref array<int> m_ParameterRemovalQueue private
Definition at line 9 of file PPEMatClassesBase.c.
Referenced by CreateDataStructure(), ParamUpdateQueueCleanup(), and ParamUpdateRemove().
m_ParameterUpdateQueueMap
protected ref map<int, ref array<int> > m_ParameterUpdateQueueMap private
Definition at line 8 of file PPEMatClassesBase.c.
Referenced by CreateDataStructure(), OnUpdate(), ParamUpdateQueueCleanup(), and SetParameterUpdating().
m_UpdatedParameters
protected ref array<int> m_UpdatedParameters private
Definition at line 10 of file PPEMatClassesBase.c.
Referenced by PPEDOF::ApplyValueChanges(), PPELightIntensityParamsNative::ApplyValueChanges(), ApplyValueChanges(), CreateDataStructure(), and InsertUpdatedParameter().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/PPEManager/Materials/PPEMatClassesBase.c