DayZ Scripts: SpookyEventBase Class Reference
SpookyEventBase Class Reference
Private Member Functions
void SpookyEventBase ()
protected void Init ()
protected vector GetMatchingSurfacePos (TStringArray surfaces, TStringVectorMap gatheredSurfaces)
protected void SetCoolDown (float secs)
protected bool HasSurfaces ()
protected bool CanDo (PlayerBase player, TStringVectorMap surfaceTypes)
protected void Do (PlayerBase player)
bool CanPerform (PlayerBase player, float currentTime, TStringVectorMap surfaceTypes)
void Perform (PlayerBase player, float currentTime, TStringVectorMap gatheredSurfaces)
protected vector GetSoundPos (PlayerBase player)
Private Attributes
protected float m_PerformedTimestamp
protected int m_Cooldown
protected string m_SoundSet
protected ref TStringArray m_Surfaces
protected vector m_MatchingSurfacePos
Constructor & Destructor Documentation
SpookyEventBase()
void SpookyEventBase () inline private
References Init().
Member Function Documentation
CanDo()
protected bool CanDo (PlayerBase player, TStringVectorMap surfaceTypes) inline private
Referenced by CanPerform().
CanPerform()
bool CanPerform (PlayerBase player, float currentTime, TStringVectorMap surfaceTypes) inline private
References CanDo(), GetMatchingSurfacePos(), HasSurfaces(), m_Cooldown, m_MatchingSurfacePos, m_PerformedTimestamp, m_Surfaces, and vector::Zero.
Do()
protected void Do (PlayerBase player) private
Referenced by Perform().
GetMatchingSurfacePos()
protected vector GetMatchingSurfacePos (TStringArray surfaces, TStringVectorMap gatheredSurfaces) inline private
References string::Contains(), and vector::Zero.
Referenced by CanPerform().
GetSoundPos()
protected vector GetSoundPos (PlayerBase player) inline private
References HasSurfaces(), m_MatchingSurfacePos, vector::RandomDir2D(), and Math::RandomFloatInclusive().
Referenced by Perform().
HasSurfaces()
protected bool HasSurfaces () inline private
References m_Surfaces.
Referenced by CanPerform(), and GetSoundPos().
Init()
protected void Init () private
Referenced by SpookyEventBase().
Perform()
void Perform (PlayerBase player, float currentTime, TStringVectorMap gatheredSurfaces) inline private
References Do(), Debug::DrawSphere(), DiagMenu::GetBool(), GetSoundPos(), m_PerformedTimestamp, m_SoundSet, SEffectManager::PlaySound(), Print(), EffectSound::SetAutodestroy(), and Colors::YELLOW.
Referenced by SelectEvent().
SetCoolDown()
protected void SetCoolDown (float secs) inline private
References m_Cooldown.
Referenced by SpookyEventWind::Init(), and SpookyEventSteps::Init().
Field Documentation
m_Cooldown
protected int m_Cooldown private
Referenced by CanPerform(), and SetCoolDown().
m_MatchingSurfacePos
protected vector m_MatchingSurfacePos private
Referenced by CanPerform(), and GetSoundPos().
m_PerformedTimestamp
protected float m_PerformedTimestamp private
Referenced by CanPerform(), and Perform().
m_SoundSet
protected string m_SoundSet private
Referenced by SpookyEventWind::Init(), SpookyEventSteps::Init(), and Perform().
m_Surfaces
protected ref TStringArray m_Surfaces private
Referenced by CanPerform(), HasSurfaces(), and SpookyEventSteps::Init().
The documentation for this class was generated from the following file:
P:/scripts/4_world/classes/contaminatedarea/spookyareamisc.c