DayZ Scripts: ScriptConsoleVicinityTab Class Reference
ScriptConsoleVicinityTab Class Reference
Private Member Functions
void ScriptConsoleVicinityTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent=null)
override void OnSelected ()
void RenderList ()
void UpdateSelected ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
void OnSelectAction (EntityAI ent, int actionId)
Private Attributes
protected TextListboxWidget m_VicinityListbox
protected ButtonWidget m_WatchItem
protected EditBoxWidget m_DistanceWidget
protected ref array< Object > m_VicinityItems = new array<Object>
protected ref ContextMenu m_ContextMenu
Static Private Attributes
static protected float m_Distance = 30
static protected Object m_Selected = null
Constructor & Destructor Documentation
ScriptConsoleVicinityTab()
void ScriptConsoleVicinityTab (Widget root, ScriptConsole console, Widget button, ScriptConsoleTabBase parent = null) inline private
References m_ContextMenu, m_Distance, m_DistanceWidget, m_VicinityListbox, m_WatchItem, RenderList(), and float::ToString().
Member Function Documentation
OnChange()
override bool OnChange (Widget w, int x, int y, bool finished) inline private
References m_Distance, m_DistanceWidget, RenderList(), UpdateSelected(), x, and y.
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References m_Selected, m_VicinityItems, m_VicinityListbox, m_WatchItem, UpdateSelected(), x, and y.
OnSelectAction()
void OnSelectAction (EntityAI ent, int actionId) inline private
References GetGame(), and GetPlayer().
OnSelected()
override void OnSelected () inline private
References UpdateSelected().
RenderList()
void RenderList () inline private
References vector::Distance(), CGame::GetCurrentCameraPosition(), GetGame(), CGame::GetObjectsAtPosition3D(), m_DistanceWidget, m_Selected, m_VicinityItems, m_VicinityListbox, float::ToString(), UpdateSelected(), and x.
Referenced by OnChange(), and ScriptConsoleVicinityTab().
UpdateSelected()
void UpdateSelected () inline private
References m_ContextMenu, m_Selected, m_VicinityItems, and m_VicinityListbox.
Referenced by OnChange(), OnClick(), OnSelected(), and RenderList().
Field Documentation
m_ContextMenu
protected ref ContextMenu m_ContextMenu private
Referenced by ScriptConsoleVicinityTab(), and UpdateSelected().
m_Distance
protected float m_Distance = 30 static private
Referenced by OnChange(), and ScriptConsoleVicinityTab().
m_DistanceWidget
protected EditBoxWidget m_DistanceWidget private
Referenced by OnChange(), RenderList(), and ScriptConsoleVicinityTab().
m_Selected
protected Object m_Selected = null static private
Referenced by OnClick(), RenderList(), and UpdateSelected().
m_VicinityItems
protected ref array<Object> m_VicinityItems = new array<Object> private
Referenced by OnClick(), RenderList(), and UpdateSelected().
m_VicinityListbox
protected TextListboxWidget m_VicinityListbox private
Referenced by OnClick(), RenderList(), ScriptConsoleVicinityTab(), and UpdateSelected().
m_WatchItem
protected ButtonWidget m_WatchItem private
Referenced by OnClick(), and ScriptConsoleVicinityTab().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptConsoleVicinityTab.c