DayZ Scripts: P:/scripts/4_World/Classes/UndergroundHandlerClient.c File Reference
UndergroundHandlerClient.c File Reference
Enumerations
enum EUndergroundPresence { NONE , OUTER , TRANSITIONING , FULL }
Functions
void UndergroundHandlerClient (PlayerBase player)
void ~UndergroundHandlerClient ()
protected PPERUndergroundAcco GetRequester ()
void OnTriggerEnter (UndergroundTrigger trigger)
void OnTriggerLeave (UndergroundTrigger trigger)
protected void CalculateEyeAccoTarget ()
protected void ProcessEyeAcco (float timeSlice)
protected void ProcessLighting (float timeSlice)
protected void ProcessSound (float timeSlice)
void Tick (float timeSlice)
protected void ApplyEyeAcco ()
protected void UpdateNVGRequester (float value)
protected bool CalculateEyeAcco (float timeSlice)
protected void OnTriggerInsiderUpdate ()
protected void SetUndergroundPresence (UndergroundTrigger trigger)
protected void EnableLights (bool enable)
void OnUpdateTimerEnd ()
void OnUpdateTimerIn ()
void OnUpdateTimerOut ()
protected void OnUndergroundPresenceUpdate (EUndergroundPresence newPresence, EUndergroundPresence oldPresence)
Variables
enum EUndergroundPresence LIGHT_BLEND_SPEED_IN = 5
const float LIGHT_BLEND_SPEED_OUT = 1.75
const float MAX_RATIO = 0.9
const float RATIO_CUTOFF = 0
const float DISTANCE_CUTOFF = 5
const float ACCO_MODIFIER = 1
const float DEFAULT_INTERPOLATION_SPEED = 7
const string UNDERGROUND_LIGHTING = "dz\\data\\lighting\\lighting_underground.txt"
protected ref AnimationTimer m_AnimTimerLightBlend
protected PlayerBase m_Player
protected PPERUndergroundAcco m_Requester
protected PPERequester_CameraNV m_NVRequester
protected ref set< UndergroundTrigger > m_InsideTriggers = new set<UndergroundTrigger>()
protected float m_EyeAccoTarget = 1
protected float m_AccoInterpolationSpeed
protected float m_EyeAcco = 1
protected float m_LightingLerpTarget
protected float m_LightingLerp
protected EffectSound m_AmbientSound
protected UndergroundTrigger m_TransitionalTrigger
Enumeration Type Documentation
EUndergroundPresence
enum EUndergroundPresence
Enumerator
NONE
OUTER
TRANSITIONING
FULL
Function Documentation
ApplyEyeAcco()
protected void ApplyEyeAcco ()
References DiagMenu::GetBool(), GetDayZGame(), GetRequester(), m_EyeAcco, m_LightingLerp, and UpdateNVGRequester().
Referenced by ProcessEyeAcco().
CalculateEyeAcco()
protected bool CalculateEyeAcco (float timeSlice)
References Math::AbsFloat(), m_AccoInterpolationSpeed, m_EyeAcco, m_EyeAccoTarget, m_Player, and m_TransitionalTrigger.
Referenced by ProcessEyeAcco().
CalculateEyeAccoTarget()
protected void CalculateEyeAccoTarget ()
References ACCO_MODIFIER, ARGB(), COLOR_RED, vector::Distance(), DISTANCE_CUTOFF, Debug::DrawLine(), Debug::DrawSphere(), DiagMenu::GetBool(), GetGame(), CGame::GetPlayer(), m_EyeAccoTarget, m_Player, m_TransitionalTrigger, MAX_RATIO, RATIO_CUTOFF, and DayZPhysics::RayCastBullet().
Referenced by ProcessEyeAcco().
EnableLights()
protected void EnableLights (bool enable)
Referenced by OnUndergroundPresenceUpdate().
GetRequester()
protected PPERUndergroundAcco GetRequester ()
References m_Requester.
Referenced by ApplyEyeAcco(), ProcessEyeAcco(), and Managed::RegisterRequester().
OnTriggerEnter()
void OnTriggerEnter (UndergroundTrigger trigger)
References m_InsideTriggers, and OnTriggerInsiderUpdate().
OnTriggerInsiderUpdate()
protected void OnTriggerInsiderUpdate ()
References DEFAULT_INTERPOLATION_SPEED, m_AccoInterpolationSpeed, m_EyeAccoTarget, m_InsideTriggers, m_TransitionalTrigger, and SetUndergroundPresence().
Referenced by OnTriggerEnter(), and OnTriggerLeave().
OnTriggerLeave()
void OnTriggerLeave (UndergroundTrigger trigger)
References m_InsideTriggers, and OnTriggerInsiderUpdate().
OnUndergroundPresenceUpdate()
protected void OnUndergroundPresenceUpdate (EUndergroundPresence newPresence, EUndergroundPresence oldPresence)
References EnableLights(), GetGame(), CGame::GetWeather(), CGame::GetWorld(), LIGHT_BLEND_SPEED_IN, LIGHT_BLEND_SPEED_OUT, m_AmbientSound, m_AnimTimerLightBlend, m_LightingLerp, m_Player, AnimationTimer::Run(), World::SetUserLightingLerp(), and Weather::SuppressLightningSimulation().
Referenced by SetUndergroundPresence().
OnUpdateTimerEnd()
void OnUpdateTimerEnd ()
OnUpdateTimerIn()
void OnUpdateTimerIn ()
References Easing::EaseInQuint(), AnimationTimer::GetValue(), m_AnimTimerLightBlend, and m_LightingLerp.
OnUpdateTimerOut()
void OnUpdateTimerOut ()
References Easing::EaseOutCubic(), AnimationTimer::GetValue(), m_AnimTimerLightBlend, and m_LightingLerp.
ProcessEyeAcco()
protected void ProcessEyeAcco (float timeSlice)
References ApplyEyeAcco(), CalculateEyeAcco(), CalculateEyeAccoTarget(), GetRequester(), m_Player, and UpdateNVGRequester().
Referenced by Tick().
ProcessLighting()
protected void ProcessLighting (float timeSlice)
References DiagMenu::GetBool(), GetGame(), CGame::GetWorld(), m_LightingLerp, and World::SetUserLightingLerp().
Referenced by Tick().
ProcessSound()
protected void ProcessSound (float timeSlice)
References GetGame(), CGame::GetWorld(), m_AmbientSound, m_EyeAcco, m_Player, World::SetExplicitVolumeFactor_EnvSounds2D(), and EffectSound::SetSoundVolume().
SetUndergroundPresence()
protected void SetUndergroundPresence (UndergroundTrigger trigger)
References m_Player, and OnUndergroundPresenceUpdate().
Referenced by OnTriggerInsiderUpdate().
Tick()
void Tick (float timeSlice)
References DiagMenu::GetBool(), GetGame(), m_LightingLerp, m_Player, ProcessEyeAcco(), ProcessLighting(), and ProcessSound().
UndergroundHandlerClient()
void UndergroundHandlerClient (PlayerBase player)
References GetGame(), CGame::GetWorld(), World::LoadUserLightingCfg(), m_NVRequester, m_Player, and UNDERGROUND_LIGHTING.
Referenced by ManBase::GetUndergroundHandler(), OnEnterClientEvent(), and OnLeaveClientEvent().
UpdateNVGRequester()
protected void UpdateNVGRequester (float value)
References m_NVRequester.
Referenced by ApplyEyeAcco(), and ProcessEyeAcco().
~UndergroundHandlerClient()
void ~UndergroundHandlerClient ()
References GetGame(), CGame::GetWeather(), CGame::GetWorld(), m_AmbientSound, World::SetExplicitVolumeFactor_EnvSounds2D(), World::SetUserLightingLerp(), EffectSound::Stop(), and Weather::SuppressLightningSimulation().
Variable Documentation
ACCO_MODIFIER
const float ACCO_MODIFIER = 1
Referenced by CalculateEyeAccoTarget().
DEFAULT_INTERPOLATION_SPEED
const float DEFAULT_INTERPOLATION_SPEED = 7
Referenced by OnTriggerInsiderUpdate().
DISTANCE_CUTOFF
const float DISTANCE_CUTOFF = 5
Referenced by CalculateEyeAccoTarget().
LIGHT_BLEND_SPEED_IN
enum EUndergroundPresence LIGHT_BLEND_SPEED_IN = 5
Referenced by OnUndergroundPresenceUpdate().
LIGHT_BLEND_SPEED_OUT
const float LIGHT_BLEND_SPEED_OUT = 1.75
Referenced by OnUndergroundPresenceUpdate().
m_AccoInterpolationSpeed
protected float m_AccoInterpolationSpeed
Referenced by CalculateEyeAcco(), and OnTriggerInsiderUpdate().
m_AmbientSound
protected EffectSound m_AmbientSound
Referenced by OnUndergroundPresenceUpdate(), ProcessSound(), and ~UndergroundHandlerClient().
m_AnimTimerLightBlend
protected ref AnimationTimer m_AnimTimerLightBlend
Referenced by OnUndergroundPresenceUpdate(), OnUpdateTimerIn(), and OnUpdateTimerOut().
m_EyeAcco
protected float m_EyeAcco = 1
Referenced by ApplyEyeAcco(), CalculateEyeAcco(), and ProcessSound().
m_EyeAccoTarget
protected float m_EyeAccoTarget = 1
Referenced by CalculateEyeAcco(), CalculateEyeAccoTarget(), and OnTriggerInsiderUpdate().
m_InsideTriggers
protected ref set<UndergroundTrigger> m_InsideTriggers = new set<UndergroundTrigger>()
Referenced by OnTriggerEnter(), OnTriggerInsiderUpdate(), and OnTriggerLeave().
m_LightingLerp
protected float m_LightingLerp
Referenced by ApplyEyeAcco(), OnUndergroundPresenceUpdate(), OnUpdateTimerIn(), OnUpdateTimerOut(), ProcessLighting(), and Tick().
m_LightingLerpTarget
protected float m_LightingLerpTarget
m_NVRequester
protected PPERequester_CameraNV m_NVRequester
Referenced by UndergroundHandlerClient(), and UpdateNVGRequester().
m_Player
protected PlayerBase m_Player
m_Requester
protected PPERUndergroundAcco m_Requester
Referenced by GetRequester(), SymptomBase::OnGetDeactivatedClient(), SymptomBase::OnInit(), and SymptomBase::OnUpdateClient().
m_TransitionalTrigger
protected UndergroundTrigger m_TransitionalTrigger
Referenced by CalculateEyeAcco(), CalculateEyeAccoTarget(), and OnTriggerInsiderUpdate().
MAX_RATIO
const float MAX_RATIO = 0.9
Referenced by CalculateEyeAccoTarget().
RATIO_CUTOFF
const float RATIO_CUTOFF = 0
Referenced by CalculateEyeAccoTarget().
UNDERGROUND_LIGHTING
const string UNDERGROUND_LIGHTING = "dz\\data\\lighting\\lighting_underground.txt"
Referenced by UndergroundHandlerClient().