DayZ Scripts: EmoteConstructor Class Reference
EmoteConstructor Class Reference
Private Member Functions
bool ConstructEmotes (PlayerBase player, out map< int, ref EmoteBase > emoteMap)
void RegisterEmotes (TTypenameArray emotes)
Member Function Documentation
ConstructEmotes()
bool ConstructEmotes (PlayerBase player, out map< int, ref EmoteBase > emoteMap) inline private
References ErrorEx, RegisterEmotes(), Sort(), Spawn(), and ToString().
Referenced by ConstructData().
RegisterEmotes()
void RegisterEmotes (TTypenameArray emotes) inline private
References EmoteCampfireSit(), EmoteClap(), EmoteCome(), EmoteDance(), EmoteFacepalm(), EmoteGetDown(), EmoteGreeting(), EmoteHeart(), EmoteHold(), EmoteListening(), EmoteLookAtMe(), EmoteLyingDown(), EmoteMove(), EmoteNod(), EmotePoint(), EmotePointSelf(), EmoteRPSPaper(), EmoteRPSRandom(), EmoteRPSRock(), EmoteRPSScisors(), EmoteSalute(), EmoteShake(), EmoteShrug(), EmoteSilent(), EmoteSitA(), EmoteSitB(), EmoteSOS(), EmoteSuicide(), EmoteSurrender(), EmoteTaunt(), EmoteTauntElbow(), EmoteTauntKiss(), EmoteTauntThink(), EmoteThroat(), EmoteThumb(), EmoteThumbDown(), EmoteTimeout(), EmoteVomit(), and EmoteWatching().
Referenced by ConstructEmotes().
The documentation for this class was generated from the following file:
P:/scripts/4_world/classes/emoteconstructor.c