DayZ Scripts: Analytics Class Reference
Analytics Class Reference
Static Private Member Functions
static void PlayerDeath (StatsEventDeathData data)
static void PlayerScoredKill (StatsEventScoredKillData data)
static void PlayerDisconnected (StatsEventDisconnectedData data)
static void PlayerMeasures (StatsEventMeasuresData data)
static void PlayerSpawned (StatsEventSpawnedData data)
Member Function Documentation
PlayerDeath()
static void PlayerDeath (StatsEventDeathData data) inline static private
PlayerDisconnected()
static void PlayerDisconnected (StatsEventDisconnectedData data) inline static private
Referenced by ManBase::OnDisconnect(), and CGame::OnEvent().
PlayerMeasures()
static void PlayerMeasures (StatsEventMeasuresData data) inline static private
Referenced by ManBase::UpdatePlayerMeasures().
PlayerScoredKill()
static void PlayerScoredKill (StatsEventScoredKillData data) inline static private
PlayerSpawned()
static void PlayerSpawned (StatsEventSpawnedData data) inline static private
Referenced by CGame::OnEvent().
The documentation for this class was generated from the following file:
3_Game/Analytics/ScriptAnalytics.c