DayZ Scripts: P:/scripts/4_World/Entities/Effects/BoatWaterEffects.c File Reference
BoatWaterEffects.c File Reference
Data Structures
class EffectBoatWaterBack
class EffectBoatWaterBase
Enumerations
enum EBoatSpeed {
UNSET , SLOWEST , SLOW , MEDIUM ,
FAST
}
Functions
void EffectBoatWaterFront ()
override protected void UpdateSpeedState (Particle ptc, float speed)
override void Update ()
void EffectBoatWaterSide ()
Variables
enum EBoatSpeed EMITORS_FAST = 9
Enumeration Type Documentation
EBoatSpeed
enum EBoatSpeed
Enumerator
UNSET
SLOWEST
SLOW
MEDIUM
FAST
Function Documentation
EffectBoatWaterFront()
void EffectBoatWaterFront ()
References ParticleList::BOAT_WATER_FRONT, and EffectBoatWaterBase::SetParticleState().
Referenced by BoatScript::BoatScript().
EffectBoatWaterSide()
void EffectBoatWaterSide ()
References ParticleList::BOAT_WATER_SIDE, and EffectBoatWaterBase::SetParticleState().
Referenced by BoatScript::BoatScript().
UpdateSpeedState()
override protected void UpdateSpeedState (Particle ptc, float speed)
References EffectBoatWaterBase::EnableEmitor(), EffectBoatWaterBase::m_EmitorCount, and EffectBoatWaterBase::m_SpeedState.
Variable Documentation
EMITORS_FAST
EffectBoatWaterBack EMITORS_FAST = 9