DayZ Scripts: EffCoolantSteam Class Reference
EffCoolantSteam Class Reference
Private Member Functions
override void SetParticleStateLight ()
override void SetParticleStateHeavy ()
void UpdateParticle ()
Member Function Documentation
SetParticleStateHeavy()
override void SetParticleStateHeavy () inline private
References ParticleList::HATCHBACK_COOLANT_OVERHEATED, EffVehicleSmoke::SetParticleState(), and UpdateParticle().
SetParticleStateLight()
override void SetParticleStateLight () inline private
References ParticleList::HATCHBACK_COOLANT_OVERHEATING, EffVehicleSmoke::SetParticleState(), and UpdateParticle().
UpdateParticle()
void UpdateParticle () inline private
References GetAttachmentParent(), EffectParticle::GetParticle(), Particle::ScaleParticleParamFromOriginal(), and Particle::SetParticleParam().
Referenced by SetParticleStateHeavy(), and SetParticleStateLight().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Effects/EffectParticle/VehicleSmoke/CoolantSteam.c