DayZ Scripts: P:/scripts/4_World/Classes/ContaminatedArea/GeyserArea.c File Reference
GeyserArea.c File Reference
Enumerations
enum EGeyserState { DORMANT = 0 , ERUPTION_SOON = 1 , ERUPTING_PRIMARY = 2 , ERUPTING_SECONDARY = 4 }
Functions
override void EEDelete (EntityAI parent)
override void InitZoneServer ()
void TickState ()
void KillEntitiesInArea ()
Variables
enum EGeyserState UPDATE_RATE = 1000
protected const float PRE_ERUPTION_DURATION = 5
protected int m_TimeElapsed
protected float m_RandomizedInterval
protected float m_RandomizedDuration
protected GeyserTrigger m_GeyserTrigger
Enumeration Type Documentation
EGeyserState
enum EGeyserState
Enumerator
DORMANT
ERUPTION_SOON
ERUPTING_PRIMARY
ERUPTING_SECONDARY
Function Documentation
EEDelete()
override void EEDelete (EntityAI parent)
References GetGame(), m_GeyserTrigger, and GeyserTrigger::StopEffects().
InitZoneServer()
override void InitZoneServer ()
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CreateTrigger(), CGame::GetCallQueue(), GetGame(), m_GeyserTrigger, m_Position, m_Radius, m_RandomizedInterval, Math::RandomInt(), TickState(), and UPDATE_RATE.
KillEntitiesInArea()
void KillEntitiesInArea ()
References GetGame(), CGame::GetObjectsAtPosition(), m_Position, and m_Radius.
Referenced by TickState().
TickState()
void TickState ()
References GeyserTrigger::AddGeyserState(), GeyserTrigger::GetGeyserState(), KillEntitiesInArea(), m_GeyserTrigger, m_RandomizedDuration, m_RandomizedInterval, m_TimeElapsed, PRE_ERUPTION_DURATION, Math::RandomBool(), Math::RandomInt(), GeyserTrigger::RemoveGeyserState(), and UPDATE_RATE.
Referenced by InitZoneServer().
Variable Documentation
m_GeyserTrigger
protected GeyserTrigger m_GeyserTrigger
Referenced by EEDelete(), InitZoneServer(), and TickState().
m_RandomizedDuration
protected float m_RandomizedDuration
Referenced by TickState().
m_RandomizedInterval
protected float m_RandomizedInterval
Referenced by InitZoneServer(), and TickState().
m_TimeElapsed
protected int m_TimeElapsed
Referenced by TickState().
PRE_ERUPTION_DURATION
protected const float PRE_ERUPTION_DURATION = 5
Referenced by TickState().
UPDATE_RATE
enum EGeyserState UPDATE_RATE = 1000
Referenced by InitZoneServer(), and TickState().