DayZ Scripts: GardenBase Class Reference
GardenBase Class Reference
Private Member Functions
void GardenPlot ()
override void EEInit ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void EEDelete (EntityAI parent)
override bool IsInventoryVisible ()
override int GetGardenSlotsCount ()
void RefreshSlots ()
override void OnPlacementStarted (Man player)
override void OnHologramBeingPlaced (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool CanBePlaced (Man player, vector position)
Private Attributes
Object m_ClutterCutter
private const int GARDEN_SLOT_COUNT = 9
Member Function Documentation
CanBePlaced()
override bool CanBePlaced (Man player, vector position) inline private
References GetGame(), CGame::IsSurfaceFertile(), and CGame::SurfaceGetType3D().
EEDelete()
override void EEDelete (EntityAI parent) inline private
References GetGame(), m_ClutterCutter, and CGame::ObjectDelete().
EEInit()
override void EEInit () inline private
GardenPlot()
void GardenPlot () inline private
GetGardenSlotsCount()
override int GetGardenSlotsCount () inline private
References GARDEN_SLOT_COUNT.
Referenced by ItemBase::CheckRainTick(), ItemBase::GardenBase(), ItemBase::GetNearestSlotIDByState(), ItemBase::InitializeSlots(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::SyncSlots(), and ItemBase::UpdateTexturesOnAllSlots().
IsInventoryVisible()
override bool IsInventoryVisible () inline private
OnHologramBeingPlaced()
override void OnHologramBeingPlaced (Man player) inline private
References RefreshSlots().
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, m_ClutterCutter, and CGame::ObjectDelete().
OnPlacementStarted()
override void OnPlacementStarted (Man player) inline private
References RefreshSlots().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), GetOrientation(), GetPosition, and m_ClutterCutter.
RefreshSlots()
void RefreshSlots () inline private
Referenced by OnHologramBeingPlaced(), and OnPlacementStarted().
Field Documentation
GARDEN_SLOT_COUNT
private const int GARDEN_SLOT_COUNT = 9 private
Referenced by GetGardenSlotsCount().
m_ClutterCutter
Object m_ClutterCutter private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/GardenBase/GardenPlot.c