DayZ Scripts: Debug utilities
Debug utilities
Modules
Debug UI API
Immediate mode debug UI APIPer frame usage example:
Debug Shape API definition
Enumerations
enum ErrorExSeverity
Functions
proto void DumpStack ()
Prints current call stack (stack trace)
proto void DumpStackString (out string stack)
Prints current call stack (stack trace) to given output.
proto void DebugBreak (bool condition=true, void param1=NULL, void param2=NULL, void param3=NULL, void param4=NULL, void param5=NULL, void param6=NULL, void param7=NULL, void param8=NULL, void param9=NULL)
Triggers breakpoint in C++ in run time(when app is running in debug enviroment)
void CompileBreak ()
Triggers breakpoint in C++ in compile time(when app is running in debug enviroment)
proto void DPrint (string var)
Prints content of variable to console/log. Should be used for critical messages so it will appear in debug log.
enum ErrorExSeverity ErrorEx (string err, ErrorExSeverity severity=ErrorExSeverity.ERROR)
Error message, prefixed by method name, above 'INFO' will show a messagebox.
proto void ErrorExString (string err, out string str, ErrorExSeverity severity=ErrorExSeverity.ERROR)
proto native void Error2 (string title, string err)
Messagebox with error message.
void Error (string err)
Messagebox with error message.
proto void Print (void var)
Prints content of variable to console/log.
proto void PrintToRPT (void var)
Prints content of variable to RPT file (performance warning - each write means fflush! use with care)
proto void PrintFormat (string fmt, void param1=NULL, void param2=NULL, void param3=NULL, void param4=NULL, void param5=NULL, void param6=NULL, void param7=NULL, void param8=NULL, void param9=NULL)
Prints formated text to console/log.
Detailed Description
Enumeration Type Documentation
ErrorExSeverity
enum ErrorExSeverity
Function Documentation
CompileBreak()
void CompileBreak ()
Triggers breakpoint in C++ in compile time(when app is running in debug enviroment)
DebugBreak()
proto void DebugBreak (bool condition = true, void param1 = NULL, void param2 = NULL, void param3 = NULL, void param4 = NULL, void param5 = NULL, void param6 = NULL, void param7 = NULL, void param8 = NULL, void param9 = NULL)
Triggers breakpoint in C++ in run time(when app is running in debug enviroment)
DPrint()
proto void DPrint (string var)
Prints content of variable to console/log. Should be used for critical messages so it will appear in debug log.
Referenced by ActionManagerClient::ActionStart(), ComponentEnergyManager::CanWork(), ActionDefibrilateBase::DefibrillateServer(), ComponentEnergyManager::Event_OnAwake(), and ItemBase::SetFuel().
DumpStack()
proto void DumpStack ()
Prints current call stack (stack trace)
Returns
void
DumpStack();
    Output:
        -- Stack trace --
       SaveFile() Scripts\Entities\Modules\ModuleBase\ModuleFileHandler.c : 51
       SaveConfigToFile() Scripts\Entities\Modules\ModuleBase\ModuleFileHandler\ModuleLocalProfile.c : 114
       SaveParameterArray() Scripts\Entities\Modules\ModuleBase\ModuleFileHandler\ModuleLocalProfile.c : 133
       SetParameterArray() Scripts\Entities\Modules\ModuleBase\ModuleFileHandler\ModuleLocalProfile.c : 231
       PresetAdd() Scripts\Entities\Modules\ModuleBase\ModuleFileHandler\ModuleLocalProfile\ModuleLocalProfileUI.h : 46
       OnKeyPress() Scripts/mission/missionGameplay.c : 215
       OnKeyPress() Scripts/DayZGame.c : 334
       -----------------
Referenced by GetPlugin(), Entity::GetWeightEx(), DebugPrint::LogMessage(), and Entity::SetWeightDirty().
DumpStackString()
proto void DumpStackString (out string stack)
Prints current call stack (stack trace) to given output.
Returns
void
string tmp;
    DumpStackString(tmp);
Print(tmp);
    Output:
      SaveFile() Scripts\Entities\Modules\ModuleBase\ModuleFileHandler.c : 51
      SaveConfigToFile() Scripts\Entities\Modules\ModuleBase\ModuleFileHandler\ModuleLocalProfile.c : 114
      SaveParameterArray() Scripts\Entities\Modules\ModuleBase\ModuleFileHandler\ModuleLocalProfile.c : 133
      SetParameterArray() Scripts\Entities\Modules\ModuleBase\ModuleFileHandler\ModuleLocalProfile.c : 231
      PresetAdd() Scripts\Entities\Modules\ModuleBase\ModuleFileHandler\ModuleLocalProfile\ModuleLocalProfileUI.h : 46
      OnKeyPress() Scripts/mission/missionGameplay.c : 215
      OnKeyPress() Scripts/DayZGame.c : 334
Error()
void Error (string err)
Messagebox with error message.
References Error2().
Referenced by HandEventBase::AcquireInventoryJunctureFromServer(), HandActionBase::Action(), StaminaHandler::ActivateDepletionModifier(), StaminaHandler::ActivateRecoveryModifier(), ManBase::AddActiveNV(), Trigger::AddInsider(), AddModifier(), BotStateBase::AddTransition(), HandStateBase::AddTransition(), WeaponStateBase::AddTransition(), Managed::CharacterLoad(), RecipeBase::CheckRecipe(), Chemlight_ColorBase::Chemlight_ColorBase(), ServerBrowserTab::Construct(), ManBase::Consume(), MissionBase::ControlPersonalLight(), CreateHandEventFromContext(), GameInventory::CreateInInventory(), EntityLightSource::CreateLight(), Particle::CreateOnObject(), CreateParticle(), EffectAreaLoader::CreateZones(), ManBase::DecreaseAntibioticsCount(), DeferredWeaponFailed(), HumanInventory::DropEntity(), GameInventory::DropEntity(), GameInventory::DropEntityInBounds(), GameInventory::DropEntityWithTransform(), Entity::EEItemLocationChanged(), ejectBulletAndStoreInMagazine(), ComponentEnergyManager::Event_OnAwake(), ReplaceItemWithNewLambdaBase::Execute(), HumanInventory::ForceSwapEntities(), EntityAI::Get3rdPersonCameraType(), EntityAI::GetAnimInstance(), OnlineServices::GetClientServices(), KazuarOptic::GetCurrentNVType(), StarlightOptic::GetCurrentNVType(), PoweredOptic_Base::GetCurrentNVType(), AreaDamageComponentRaycasted::GetFallbackHitZone(), PluginFileHandler::GetFileName(), GetInjuryValue(), MissionBase::GetIntroScenePC(), MissionBase::GetIntroSceneXbox(), ManBase::GetItemOnSlot(), Chemlight_ColorBase::GetMaterialForDamageState(), BotStateBase::GetNextSlot(), GetProperties(), PPERequesterBase::GetRequestData(), Managed::GetRequester(), EntityAI::GetSeatAnimationType(), Selection::GetVertexPosition(), HandGuardBase::GuardCondition(), HandSelectAnimationOfForceSwapInHandsEvent::GuardCondition(), WeaponGuardBase::GuardCondition(), HandEventFactory(), HandEventRemove::HandEventThrow(), HandleDropMagazine(), HandleForceSwapEntities(), HandleHandEvent(), HandleReciveData(), HandleSwapEntities(), HandleTakeToDst(), ScriptedWidgetEventHandler::Init(), InitPlayerComponentCollisions(), PPEClassBase::InsertParamValueData(), InventoryItem::IsServerCheck(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadAndSetCurrentFSMState(), WeaponStateBase::LoadCurrentFSMState(), LoadCurrentFSMState(), Weapon::LoadCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadCurrentUnstableFSMState(), InventoryItem::LoadParticleConfigOnOverheating(), HumanInventory::LocalDestroyEntity(), GameInventory::LocalDestroyEntity(), MoveEquipToExistingItemAndDestroyOldRootLambda(), ManBase::NeedInventoryJunctureFromServer(), WeaponStateBase::OnAbort(), WeaponChambering_Base::OnAbort(), OnAbort(), ActionCarDoors::OnEnd(), BotStateBase::OnEntry(), HandStateBase::OnEntry(), HandStartAction::OnEntry(), WeaponStateBase::OnEntry(), WeaponChambering_Base::OnEntry(), OnEventForRemoteWeapon(), WeaponStateBase::OnExit(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnFailThresholdBreached(), ActionRestrainTarget::OnFinishProgressServer(), MenuData::OnGetDefaultCharacter(), DayZPlayer::OnInputForRemote(), DayZPlayer::OnInputFromServer(), WeaponManager::OnInputUserDataProcess(), DayZPlayer::OnInputUserDataReceived(), RecipeBase::OnSelectedRecipe(), GameInventory::OnServerInventoryCommandStatic(), MenuData::OnSetDefaultCharacter(), Weapon::OnStoreLoad(), ChainedDropAndRestrainLambda::OnSuccess(), CraftingManager::OnUpdate(), Entity::OnVariablesSynchronized(), OpenItem::OpenAndSwitch(), OptionalLocationReadFromContext(), OptionalLocationWriteToContext(), OptionSelector::OptionSelectorMultistate(), RecipeBase::PerformRecipe(), PluginRecipesManagerBase::PerformRecipeServer(), EffectArea::PlaceParticles(), Play(), PlayRequestEx(), FlashbangEffect::PlaySound(), PostWeaponEvent(), ReplaceItemWithNewLambdaBase::PrepareLocations(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessCompletionTransitions(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ProcessEvent(), ProcessInputData(), HandGuardBase::ProcessSwapEvent(), pushToChamberFromAttachedMagazine(), pushToChamberFromInnerMagazine(), HandEventBase::ReadFromContext(), BleedingSourcesManagerBase::RegisterBleedingZoneEx(), RegisterItself(), PluginRecipesManagerBase::RegisterRecipe(), SymptomManager::RegisterSymptom(), ManBase::RemoveActiveNV(), BleedingSourcesManagerBase::RemoveBleedingSource(), ReplaceItemWithNewLambdaBase::RemoveOldItemFromLocation(), Edible_Base::ReplaceEdibleWithNew(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), HumanInventory::ReplaceItemInHandsWithNewImpl(), GameInventory::ReplaceItemWithNew(), ErrorModuleHandler::SafeAddModule(), ErrorModuleHandler::SafeRemoveModule(), ErrorModuleHandler::SafeRemoveModule(), WeaponStateBase::SaveCurrentFSMState(), SaveCurrentFSMState(), Weapon::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentUnstableFSMState(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), SetDamageComponentType(), SetDeferDuration(), SetHitZones(), SetLoopInterval(), SetRaycastSources(), SetRaycastSourcesVector(), RecipeBase::SpawnItems(), SymptomManager::SpawnSymptom(), Bot::Start(), WeaponManager::StartPendingAction(), HumanInventory::SwapEntities(), EntityAI::SwapEntitiesImpl(), HumanInventory::TakeEntityAsAttachmentEx(), GameInventory::TakeEntityAsTargetAttachmentEx(), HumanInventory::TakeEntityToCargoEx(), GameInventory::TakeEntityToCargoEx(), HumanInventory::TakeEntityToInventory(), GameInventory::TakeEntityToInventory(), GameInventory::TakeEntityToTargetCargoEx(), GameInventory::TakeEntityToTargetInventory(), SplitItemUtils::TakeOrSplitToInventoryLocation(), HumanInventory::ThrowEntity(), TransformRestrainItem(), ReplaceItemWithNewLambdaBase::UndoRemoveOldItemFromLocation(), FlashbangEffect::Update(), PPEMatClassParameterCommandData::Update(), Update(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ValidateAndRepairHelper(), ValidateDestroy(), ValidateHandEvent(), ValidateSwap(), ValidateSyncMove(), WoundInfectionMdfr::WoundInfectionMdfr(), HandEventBase::WriteToContext(), and InventoryLocation::WriteToContext().
Error2()
proto native void Error2 (string title, string err)
Messagebox with error message.
Referenced by Error().
ErrorEx()
enum ErrorExSeverity ErrorEx (string err, ErrorExSeverity severity = ErrorExSeverity.ERROR)
Error message, prefixed by method name, above 'INFO' will show a messagebox.
Note
Format: [className%::methodName%] :: [severity%] :: errString%
Parameters
p string Error message to use
class ErrorExTest
{
    void ThrowWarning()
    {
        // [ErrorExTest::ThrowWarning] :: [WARNING] :: This is a warning.
        ErrorEx("This is a warning.", ErrorExSeverity.WARNING);
    }
}
ErrorExString()
proto void ErrorExString (string err, out string str, ErrorExSeverity severity = ErrorExSeverity.ERROR)
Print()
proto void Print (void var)
Prints content of variable to console/log.
Referenced by WeaponActionBase::Action(), ActionAttachWheels::ActionCondition(), actionDebugPrint(), Actions_Start(), Chat::Add(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::AddTransition(), WorldData::BaseTempDebug(), PluginBase::BroadcastString(), Achievements::CheckError(), PluginBase::CheckInit(), SEffectManager::Cleanup(), PluginDayzPlayerDebug_Weapons::CommandHandler(), CopyOldPropertiesToNew(), ManBase::CreateCopyOfItemInInventory(), CreateMission(), DayZPlayerCameraBase::DayZPlayerCamera1stPerson(), DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPersonErcSpr(), DayZPlayerCameraBase::DayZPlayerCameraIronsights(), DayZPlayerImplementAiming::DbgPrintAimingImplement(), DbgPrintTargetDump(), DbgShowBoneName(), array< Class T >::Debug(), set< Class T >::Debug(), Hud::Debug(), DebugPrint(), RecipeBase::Do(), MenuDefaultCharacterData::DumpAttMapContents(), MissionBaseWorld::DumpCurrentUILayout(), ScriptConsoleConfigTab::DumpParam(), MissionBaseWorld::DumpWidget(), ManBase::EEHitBy(), End(), ReplaceItemWithNewLambdaBase::Execute(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::GetCurrentStableStateID(), ActionSawPlanksCB::GetDefaultTime(), CAContinuousTime::GetProgress(), SceneObject::GetSize(), Entity::GetWeightEx(), GameplayEffectWidgets_base::InitWidgetSet(), Weapon::LiftWeaponCheck(), DebugPrint::LogMessage(), ReplaceItemWithNewLambdaBase::OnAbort(), JsonApiStruct::OnBoolean(), BackendApi::OnCannotInitiate(), BackendApi::OnCannotShutdown(), PluginDayzPlayerDebug_Ctrl::OnChange(), PluginDayzPlayerDebug_Ctrl::OnClick(), PluginDayzPlayerDebug_OtherCmds::OnClick(), PluginDayzPlayerDebug_Weapons::OnClick(), ScriptedWidgetEventHandler::OnClick(), ScriptConsoleConfigTab::OnClick(), MissionBase::OnClientDisconnectedEvent(), BackendCallback::OnDataReceive(), JsonApiStruct::OnEndArray(), WeaponStateBase::OnEntry(), WeaponStateJammed::OnEntry(), BackendCallback::OnError(), RestCallback::OnError(), ErrorHandlerModule::OnErrorThrown(), CGame::OnEvent(), MissionBase::OnEvent(), BackendApi::OnFail(), RestCallback::OnFileCreated(), ActionRestrainTarget::OnFinishProgressServer(), JsonApiStruct::OnFloat(), PointLightBase::OnFrameLightSource(), Backlit::OnInit(), JsonApiStruct::OnInteger(), JsonApiStruct::OnItemBoolean(), JsonApiStruct::OnItemFloat(), JsonApiStruct::OnItemInteger(), JsonApiStruct::OnItemObject(), JsonApiStruct::OnItemString(), JsonApiStruct::OnItemVector(), MapHandler::OnKeyDown(), JsonApiStruct::OnObject(), UIPopupScript::OnOpen(), JsonApiStruct::OnPack(), AIBehaviourHLDataZombie2::OnParseConfig(), BiosPrivacyService::OnPermissions(), JsonApiStruct::OnStartArray(), OnStoreLoad(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnStoreLoad(), ItemBase::OnStoreLoad(), ManBase::OnStoreLoad(), ItemBase::OnStoreSave(), JsonApiStruct::OnString(), BackendCallback::OnSuccess(), RestCallback::OnSuccess(), BackendApi::OnSuccess(), BackendCallback::OnTimeout(), RestCallback::OnTimeout(), BotStateBase::OnUpdate(), JsonApiStruct::OnVector(), WeightDebugData::Output(), SpookyEventBase::Perform(), MissionBase::PlayerDisconnected(), RecoilBase::PostInit(), EntityAI::PredictiveDropEntity(), EntityAI::PredictiveForceSwapEntities(), EntityAI::PredictiveMoveItemFromHandsToInventory(), EntityAI::PredictiveSwapEntities(), ManBase::PredictiveSwapEntities(), EntityAI::PredictiveTakeEntityAsAttachment(), EntityAI::PredictiveTakeEntityAsAttachmentEx(), EntityAI::PredictiveTakeEntityToCargo(), EntityAI::PredictiveTakeEntityToHands(), EntityAI::PredictiveTakeEntityToInventory(), EntityAI::PredictiveTakeEntityToTargetAttachment(), EntityAI::PredictiveTakeEntityToTargetAttachmentEx(), EntityAI::PredictiveTakeEntityToTargetCargo(), EntityAI::PredictiveTakeEntityToTargetCargoEx(), EntityAI::PredictiveTakeEntityToTargetInventory(), EntityAI::PredictiveTakeToDst(), Canvas::PrintOut(), ScriptConsoleEnfScriptTab::PrintS(), PrintString(), PrintUpdate(), ItemBase::PrintValues(), DayZCreature::RegisterAnimEvents(), SyncEvents::RegisterEvents(), CGame::ReloadMission(), ReplaceItemWithNewLambdaBase::RemoveOldItemFromLocation(), ResavePlugin::Resave(), ScriptedWidgetEventHandler::ResizeParentToChild(), SVNDiffPlugin::Run(), TFModule::Run(), SaveLog(), PluginLocalProfile::SceneSave(), SelectEvent(), Tabber::SelectTab(), PPEffects::SetBlurValue(), PPEffects::SetChromAbbValue(), PPEffects::SetColorValue(), UIScriptedMenu::SetHintText(), SetPlayerLifespanLevel(), ActionRepackTent::SetupAnimation(), PPEffects::SetVignetteEffectValue(), Entity::SetWeightDirty(), SQFPrint(), SynchBeardVisual(), ScriptInvokerTests::TestInsertRunning(), PluginDayzPlayerDebug_Weapons::Tick(), ReplaceItemWithNewLambdaBase::UndoRemoveOldItemFromLocation(), Bouncer::Update(), UpdateCommandModifiers(), PluginDayzPlayerDebug_Weapons::WeaponsStartAction(), and CGame::~DayZGame().
PrintFormat()
proto void PrintFormat (string fmt, void param1 = NULL, void param2 = NULL, void param3 = NULL, void param4 = NULL, void param5 = NULL, void param6 = NULL, void param7 = NULL, void param8 = NULL, void param9 = NULL)
Prints formated text to console/log.
string c = "Peter";
PrintFormat("Hello %1, how are you?", c); // prints "Hello 'Peter', how are you?"
PrintToRPT()
proto void PrintToRPT (void var)
Prints content of variable to RPT file (performance warning - each write means fflush! use with care)
Referenced by actionDebugPrint(), ActionLog(), BaseBuildingLog(), BleedingChancesLog(), botDebugPrint(), botDebugSpam(), EffectAreaLoader::CreateZones(), fsmbDebugPrint(), fsmbDebugSpam(), fsmDebugPrint(), fsmDebugSpam(), UndergroundAreaLoader::GetData(), hndDebugPrint(), hndDebugSpam(), hndDebugSpamALot(), inventoryDebugPrint(), InventoryHFSMLog(), InventoryMoveLog(), InventoryReservationLog(), Log(), LogArrayInt(), LogArrayString(), LogError(), LogInfo(), LogWarning(), MeleeLog(), ParticleLog(), Play(), QuickbarLog(), ReceivedLogMessageFromServer(), ObjectSpawnerHandler::SpawnObject(), SymptomLog(), syncDebugPrint(), TFLog(), TriggerLog(), CfgGameplayHandler::ValidateItems(), WeatherLog(), wpnDebugPrint(), wpnDebugSpam(), wpnDebugSpamALot(), and wpnPrint().