DayZ Scripts: SewingKit Class Reference
SewingKit Class Reference
Private Member Functions
override void SetActions ()
override float GetInfectionChance (int system=0, Param param=null)
override bool CanBeDisinfected ()
override void OnCombine (ItemBase other_item)
Member Function Documentation
CanBeDisinfected()
override bool CanBeDisinfected () inline private
GetInfectionChance()
override float GetInfectionChance (int system = 0, Param param = null) inline private
References m_Cleanness.
OnCombine()
override void OnCombine (ItemBase other_item) inline private
References m_Cleanness, and SetCleanness().
SetActions()
override void SetActions () inline private
References ActionSewSelf(), ActionSewTarget(), and AddAction().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Gear/Tools/SewingKit.c