DayZ Scripts: Bolt_Base Class Reference
Bolt_Base Class Reference
Private Member Functions
override bool IsInventoryVisible ()
override bool CanBeActionTarget ()
override void EEParentedTo (EntityAI parent)
override void EEParentedFrom (EntityAI parent)
Detailed Description
Definition at line 90 of file AmmunitionPiles.c.
Member Function Documentation
CanBeActionTarget()
override bool CanBeActionTarget () inline private
Definition at line 98 of file AmmunitionPiles.c.
References GetParent().
Referenced by IsInventoryVisible().
EEParentedFrom()
override void EEParentedFrom (EntityAI parent) inline private
Definition at line 123 of file AmmunitionPiles.c.
References ArrowManagerBase::RemoveArrow().
EEParentedTo()
override void EEParentedTo (EntityAI parent) inline private
Definition at line 111 of file AmmunitionPiles.c.
References ArrowManagerBase::AddArrow().
IsInventoryVisible()
override bool IsInventoryVisible () inline private
omitted super call is intended
Definition at line 92 of file AmmunitionPiles.c.
References CanBeActionTarget().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Magazine/AmmunitionPiles.c