DayZ Scripts: Edible_Base Class Reference
Edible_Base Class Reference
Private Member Functions
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
void BoxCerealCrunchin ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsFruit ()
override bool CanDecay ()
bool ConditionAttach (EntityAI parent)
bool ConditionDetach (EntityAI parent)
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsCorpse ()
override bool CanDecay ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override void SetActions ()
override void OnConsume (float amount, PlayerBase consumer)
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsCorpse ()
override bool CanDecay ()
override bool CanBeSkinned ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override void InitItemVariables ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override float GetDisinfectQuantity (int system=0, Param param1=null)
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override void SetActions ()
void HumanSteakMeat ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsCorpse ()
override bool CanDecay ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override void SetActions ()
override void OnConsume (float amount, PlayerBase consumer)
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsCorpse ()
override bool CanDecay ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsFruit ()
override bool CanDecay ()
bool ConditionAttach (EntityAI parent)
bool ConditionDetach (EntityAI parent)
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override void SetActions ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool IsMeat ()
override bool CanDecay ()
override void SetActions ()
override bool CanBeCookedOnStick ()
override bool CanBeCooked ()
override bool IsMeat ()
Detailed Description
Definition at line 1 of file BearSteakMeat.c.
Member Function Documentation
BoxCerealCrunchin()
void BoxCerealCrunchin () inline private
Definition at line 3 of file BoxCerealCrunchin.c.
CanBeCooked() [1/25]
override bool CanBeCooked () inline private
Definition at line 3 of file BearSteakMeat.c.
Referenced by ProcessItemToCook().
CanBeCooked() [2/25]
override bool CanBeCooked () inline private
Definition at line 8 of file Bitterlings.c.
CanBeCooked() [3/25]
override bool CanBeCooked () inline private
Definition at line 3 of file BoarSteakMeat.c.
CanBeCooked() [4/25]
override bool CanBeCooked () inline private
Definition at line 3 of file CaninaBerry.c.
CanBeCooked() [5/25]
override bool CanBeCooked () inline private
Definition at line 8 of file Carp.c.
CanBeCooked() [6/25]
override bool CanBeCooked () inline private
Definition at line 3 of file CarpFilletMeat.c.
CanBeCooked() [7/25]
override bool CanBeCooked () inline private
Definition at line 8 of file Chicken_ColorBase.c.
CanBeCooked() [8/25]
override bool CanBeCooked () inline private
Definition at line 3 of file ChickenBreastMeat.c.
CanBeCooked() [9/25]
override bool CanBeCooked () inline private
Definition at line 3 of file CowSteakMeat.c.
CanBeCooked() [10/25]
override bool CanBeCooked () inline private
Definition at line 3 of file DeerSteakMeat.c.
CanBeCooked() [11/25]
override bool CanBeCooked () inline private
Definition at line 3 of file FoxSteakMeat.c.
CanBeCooked() [12/25]
override bool CanBeCooked () inline private
Definition at line 3 of file GoatSteakMeat.c.
CanBeCooked() [13/25]
override bool CanBeCooked () inline private
Definition at line 8 of file HumanSteakMeat.c.
CanBeCooked() [14/25]
override bool CanBeCooked () inline private
Definition at line 3 of file Lard.c.
CanBeCooked() [15/25]
override bool CanBeCooked () inline private
Definition at line 8 of file Mackerel.c.
CanBeCooked() [16/25]
override bool CanBeCooked () inline private
Definition at line 3 of file MackerelFilletMeat.c.
CanBeCooked() [17/25]
override bool CanBeCooked () inline private
Definition at line 3 of file MouflonSteakMeat.c.
CanBeCooked() [18/25]
override bool CanBeCooked () inline private
Definition at line 3 of file PigSteakMeat.c.
CanBeCooked() [19/25]
override bool CanBeCooked () inline private
Definition at line 8 of file Rabbit.c.
CanBeCooked() [20/25]
override bool CanBeCooked () inline private
Definition at line 3 of file RabbitLegMeat.c.
CanBeCooked() [21/25]
override bool CanBeCooked () inline private
Definition at line 3 of file SambucusBerry.c.
CanBeCooked() [22/25]
override bool CanBeCooked () inline private
Definition at line 8 of file Sardines.c.
CanBeCooked() [23/25]
override bool CanBeCooked () inline private
Definition at line 3 of file SheepSteakMeat.c.
CanBeCooked() [24/25]
override bool CanBeCooked () inline private
Definition at line 3 of file WolfSteakMeat.c.
CanBeCooked() [25/25]
override bool CanBeCooked () inline private
Definition at line 8 of file Worm.c.
CanBeCookedOnStick() [1/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file BearSteakMeat.c.
Referenced by ActionCookOnStick::ActionCondition(), and CookOnStick().
CanBeCookedOnStick() [2/25]
override bool CanBeCookedOnStick () inline private
Definition at line 3 of file Bitterlings.c.
CanBeCookedOnStick() [3/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file BoarSteakMeat.c.
CanBeCookedOnStick() [4/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file CaninaBerry.c.
CanBeCookedOnStick() [5/25]
override bool CanBeCookedOnStick () inline private
Definition at line 3 of file Carp.c.
CanBeCookedOnStick() [6/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file CarpFilletMeat.c.
CanBeCookedOnStick() [7/25]
override bool CanBeCookedOnStick () inline private
Definition at line 3 of file Chicken_ColorBase.c.
CanBeCookedOnStick() [8/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file ChickenBreastMeat.c.
CanBeCookedOnStick() [9/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file CowSteakMeat.c.
CanBeCookedOnStick() [10/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file DeerSteakMeat.c.
CanBeCookedOnStick() [11/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file FoxSteakMeat.c.
CanBeCookedOnStick() [12/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file GoatSteakMeat.c.
CanBeCookedOnStick() [13/25]
override bool CanBeCookedOnStick () inline private
Definition at line 13 of file HumanSteakMeat.c.
CanBeCookedOnStick() [14/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file Lard.c.
CanBeCookedOnStick() [15/25]
override bool CanBeCookedOnStick () inline private
Definition at line 3 of file Mackerel.c.
CanBeCookedOnStick() [16/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file MackerelFilletMeat.c.
CanBeCookedOnStick() [17/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file MouflonSteakMeat.c.
CanBeCookedOnStick() [18/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file PigSteakMeat.c.
CanBeCookedOnStick() [19/25]
override bool CanBeCookedOnStick () inline private
Definition at line 3 of file Rabbit.c.
CanBeCookedOnStick() [20/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file RabbitLegMeat.c.
CanBeCookedOnStick() [21/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file SambucusBerry.c.
CanBeCookedOnStick() [22/25]
override bool CanBeCookedOnStick () inline private
Definition at line 3 of file Sardines.c.
CanBeCookedOnStick() [23/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file SheepSteakMeat.c.
CanBeCookedOnStick() [24/25]
override bool CanBeCookedOnStick () inline private
Definition at line 8 of file WolfSteakMeat.c.
CanBeCookedOnStick() [25/25]
override bool CanBeCookedOnStick () inline private
Definition at line 3 of file Worm.c.
CanBeSkinned()
override bool CanBeSkinned () inline private
Definition at line 23 of file Chicken_ColorBase.c.
CanDecay() [1/24]
override bool CanDecay () inline private
Definition at line 18 of file BearSteakMeat.c.
CanDecay() [2/24]
override bool CanDecay () inline private
Definition at line 18 of file Bitterlings.c.
CanDecay() [3/24]
override bool CanDecay () inline private
Definition at line 18 of file BoarSteakMeat.c.
CanDecay() [4/24]
override bool CanDecay () inline private
Definition at line 18 of file CaninaBerry.c.
CanDecay() [5/24]
override bool CanDecay () inline private
Definition at line 18 of file Carp.c.
CanDecay() [6/24]
override bool CanDecay () inline private
Definition at line 18 of file CarpFilletMeat.c.
CanDecay() [7/24]
override bool CanDecay () inline private
Definition at line 18 of file Chicken_ColorBase.c.
CanDecay() [8/24]
override bool CanDecay () inline private
Definition at line 18 of file ChickenBreastMeat.c.
CanDecay() [9/24]
override bool CanDecay () inline private
Definition at line 18 of file CowSteakMeat.c.
CanDecay() [10/24]
override bool CanDecay () inline private
Definition at line 18 of file DeerSteakMeat.c.
CanDecay() [11/24]
override bool CanDecay () inline private
Definition at line 18 of file FoxSteakMeat.c.
CanDecay() [12/24]
override bool CanDecay () inline private
Definition at line 18 of file GoatSteakMeat.c.
CanDecay() [13/24]
override bool CanDecay () inline private
Definition at line 23 of file HumanSteakMeat.c.
CanDecay() [14/24]
override bool CanDecay () inline private
Definition at line 18 of file Lard.c.
CanDecay() [15/24]
override bool CanDecay () inline private
Definition at line 18 of file Mackerel.c.
CanDecay() [16/24]
override bool CanDecay () inline private
Definition at line 18 of file MackerelFilletMeat.c.
CanDecay() [17/24]
override bool CanDecay () inline private
Definition at line 18 of file MouflonSteakMeat.c.
CanDecay() [18/24]
override bool CanDecay () inline private
Definition at line 18 of file PigSteakMeat.c.
CanDecay() [19/24]
override bool CanDecay () inline private
Definition at line 18 of file Rabbit.c.
CanDecay() [20/24]
override bool CanDecay () inline private
Definition at line 18 of file RabbitLegMeat.c.
CanDecay() [21/24]
override bool CanDecay () inline private
Definition at line 18 of file SambucusBerry.c.
CanDecay() [22/24]
override bool CanDecay () inline private
Definition at line 18 of file Sardines.c.
CanDecay() [23/24]
override bool CanDecay () inline private
Definition at line 18 of file SheepSteakMeat.c.
CanDecay() [24/24]
override bool CanDecay () inline private
Definition at line 18 of file WolfSteakMeat.c.
CanDetachAttachment() [1/3]
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 49 of file DisinfectantSpray.c.
CanDetachAttachment() [2/3]
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 42 of file Guts.c.
CanDetachAttachment() [3/3]
override bool CanDetachAttachment (EntityAI parent) inline private
Definition at line 42 of file SmallGuts.c.
CanPutAsAttachment() [1/3]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 10 of file DisinfectantSpray.c.
CanPutAsAttachment() [2/3]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file Guts.c.
CanPutAsAttachment() [3/3]
override bool CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file SmallGuts.c.
ConditionAttach() [1/2]
bool ConditionAttach (EntityAI parent) inline private
Definition at line 23 of file CaninaBerry.c.
References Barrel_ColorBase::IsOpen().
ConditionAttach() [2/2]
bool ConditionAttach (EntityAI parent) inline private
Definition at line 23 of file SambucusBerry.c.
References Barrel_ColorBase::IsOpen().
ConditionDetach() [1/2]
bool ConditionDetach (EntityAI parent) inline private
Definition at line 39 of file CaninaBerry.c.
References Barrel_ColorBase::IsOpen().
ConditionDetach() [2/2]
bool ConditionDetach (EntityAI parent) inline private
Definition at line 39 of file SambucusBerry.c.
References Barrel_ColorBase::IsOpen().
GetDisinfectQuantity()
override float GetDisinfectQuantity (int system = 0, Param param1 = null) inline private
Definition at line 74 of file DisinfectantSpray.c.
References GetQuantityMax().
HumanSteakMeat()
void HumanSteakMeat () inline private
Definition at line 3 of file HumanSteakMeat.c.
References InsertAgent().
InitItemVariables()
override void InitItemVariables () inline private
Definition at line 4 of file DisinfectantSpray.c.
References can_this_be_combined.
IsCorpse() [1/4]
override bool IsCorpse () inline private
Definition at line 13 of file Carp.c.
Referenced by ItemBase::ProcessDecay().
IsCorpse() [2/4]
override bool IsCorpse () inline private
Definition at line 13 of file Chicken_ColorBase.c.
IsCorpse() [3/4]
override bool IsCorpse () inline private
Definition at line 13 of file Mackerel.c.
IsCorpse() [4/4]
override bool IsCorpse () inline private
Definition at line 13 of file Rabbit.c.
IsFruit() [1/2]
override bool IsFruit () inline private
Definition at line 13 of file CaninaBerry.c.
Referenced by ActionEatFruit::ActionCondition(), and ItemBase::ProcessDecay().
IsFruit() [2/2]
override bool IsFruit () inline private
Definition at line 13 of file SambucusBerry.c.
IsMeat() [1/19]
override bool IsMeat () inline private
Definition at line 13 of file BearSteakMeat.c.
Referenced by ActionEatMeat::ApplyModifiers(), CAContinuousTimeCooking::Execute(), and ItemBase::ProcessDecay().
IsMeat() [2/19]
override bool IsMeat () inline private
Definition at line 13 of file Bitterlings.c.
IsMeat() [3/19]
override bool IsMeat () inline private
Definition at line 13 of file BoarSteakMeat.c.
IsMeat() [4/19]
override bool IsMeat () inline private
Definition at line 13 of file CarpFilletMeat.c.
IsMeat() [5/19]
override bool IsMeat () inline private
Definition at line 13 of file ChickenBreastMeat.c.
IsMeat() [6/19]
override bool IsMeat () inline private
Definition at line 13 of file CowSteakMeat.c.
IsMeat() [7/19]
override bool IsMeat () inline private
Definition at line 13 of file DeerSteakMeat.c.
IsMeat() [8/19]
override bool IsMeat () inline private
Definition at line 13 of file FoxSteakMeat.c.
IsMeat() [9/19]
override bool IsMeat () inline private
Definition at line 13 of file GoatSteakMeat.c.
IsMeat() [10/19]
override bool IsMeat () inline private
Definition at line 18 of file HumanSteakMeat.c.
IsMeat() [11/19]
override bool IsMeat () inline private
Definition at line 13 of file Lard.c.
IsMeat() [12/19]
override bool IsMeat () inline private
Definition at line 13 of file MackerelFilletMeat.c.
IsMeat() [13/19]
override bool IsMeat () inline private
Definition at line 13 of file MouflonSteakMeat.c.
IsMeat() [14/19]
override bool IsMeat () inline private
Definition at line 13 of file PigSteakMeat.c.
IsMeat() [15/19]
override bool IsMeat () inline private
Definition at line 13 of file RabbitLegMeat.c.
IsMeat() [16/19]
override bool IsMeat () inline private
Definition at line 13 of file Sardines.c.
IsMeat() [17/19]
override bool IsMeat () inline private
Definition at line 13 of file SheepSteakMeat.c.
IsMeat() [18/19]
override bool IsMeat () inline private
Definition at line 13 of file WolfSteakMeat.c.
IsMeat() [19/19]
override bool IsMeat () inline private
Definition at line 13 of file Worm.c.
OnConsume() [1/2]
override void OnConsume (float amount, PlayerBase consumer) inline private
Definition at line 11 of file CharcoalTablets.c.
Referenced by ItemBase::Consume().
OnConsume() [2/2]
override void OnConsume (float amount, PlayerBase consumer) inline private
Definition at line 11 of file PainkillerTablets.c.
SetActions() [1/26]
override void SetActions () inline private
Definition at line 23 of file BearSteakMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [2/26]
override void SetActions () inline private
Definition at line 23 of file Bitterlings.c.
References ActionForceFeed, and AddAction().
SetActions() [3/26]
override void SetActions () inline private
Definition at line 23 of file BoarSteakMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [4/26]
override void SetActions () inline private
Definition at line 7 of file BoxCerealCrunchin.c.
References ActionForceFeed, and AddAction().
SetActions() [5/26]
override void SetActions () inline private
Definition at line 55 of file CaninaBerry.c.
References ActionForceFeed, and AddAction().
SetActions() [6/26]
override void SetActions () inline private
Definition at line 23 of file CarpFilletMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [7/26]
override void SetActions () inline private
Definition at line 3 of file CharcoalTablets.c.
References ActionForceConsumeSingle(), and AddAction().
SetActions() [8/26]
override void SetActions () inline private
Definition at line 23 of file ChickenBreastMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [9/26]
override void SetActions () inline private
Definition at line 23 of file CowSteakMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [10/26]
override void SetActions () inline private
Definition at line 23 of file DeerSteakMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [11/26]
override void SetActions () inline private
Definition at line 79 of file DisinfectantSpray.c.
References ActionDisinfectSelf(), and AddAction().
SetActions() [12/26]
override void SetActions () inline private
Definition at line 23 of file FoxSteakMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [13/26]
override void SetActions () inline private
Definition at line 23 of file GoatSteakMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [14/26]
override void SetActions () inline private
Definition at line 67 of file Guts.c.
References ActionForceFeed, and AddAction().
SetActions() [15/26]
override void SetActions () inline private
Definition at line 28 of file HumanSteakMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [16/26]
override void SetActions () inline private
Definition at line 23 of file Lard.c.
References ActionForceFeed, and AddAction().
SetActions() [17/26]
override void SetActions () inline private
Definition at line 23 of file MackerelFilletMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [18/26]
override void SetActions () inline private
Definition at line 23 of file MouflonSteakMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [19/26]
override void SetActions () inline private
Definition at line 3 of file PainkillerTablets.c.
References ActionForceConsumeSingle(), and AddAction().
SetActions() [20/26]
override void SetActions () inline private
Definition at line 23 of file PigSteakMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [21/26]
override void SetActions () inline private
Definition at line 23 of file RabbitLegMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [22/26]
override void SetActions () inline private
Definition at line 55 of file SambucusBerry.c.
References ActionForceFeed, and AddAction().
SetActions() [23/26]
override void SetActions () inline private
Definition at line 23 of file Sardines.c.
References ActionForceFeed, and AddAction().
SetActions() [24/26]
override void SetActions () inline private
Definition at line 23 of file SheepSteakMeat.c.
References ActionForceFeed, and AddAction().
SetActions() [25/26]
override void SetActions () inline private
Definition at line 67 of file SmallGuts.c.
References ActionForceFeed, and AddAction().
SetActions() [26/26]
override void SetActions () inline private
Definition at line 23 of file WolfSteakMeat.c.
References ActionForceFeed, and AddAction().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/Edible_Base/BearSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Bitterlings.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/BoarSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/BoxCerealCrunchin.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/CaninaBerry.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Carp.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/CarpFilletMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/CharcoalTablets.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Chicken_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/ChickenBreastMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/CowSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/DeerSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/DisinfectantSpray.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/FoxSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/GoatSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Guts.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/HumanSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Lard.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Mackerel.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/MackerelFilletMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/MouflonSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/PainkillerTablets.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/PigSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Rabbit.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/RabbitLegMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/SambucusBerry.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Sardines.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/SheepSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/SmallGuts.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/WolfSteakMeat.c
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Worm.c