DayZ Scripts: FilteringBottle Class Reference
FilteringBottle Class Reference
Private Member Functions
override string GetPouringSoundset ()
override string GetEmptyingLoopSoundsetHard ()
override string GetEmptyingLoopSoundsetSoft ()
override string GetEmptyingLoopSoundsetWater ()
override string GetEmptyingEndSoundsetHard ()
override string GetEmptyingEndSoundsetSoft ()
override string GetEmptyingEndSoundsetWater ()
override bool CanPutInCargo (EntityAI parent)
override bool IsOpen ()
override int FilterAgents (int agentsIn)
override void OnConsume (float amount, PlayerBase consumer)
protected void DamageBottleConsume (float amount, PlayerBase consumer)
override void AffectLiquidContainerOnFill (int liquid_type, float amount)
override float GetItemOverheatThreshold ()
disregards liquid boil threshold if filled
override void OnItemOverheat (float deltaTime)
Private Attributes
const float DAMAGE_CONSUME_PER_ML = 0.01
const float DAMAGE_OVERHEAT_PER_S = 1
const float DAMAGE_ENVIRO_LIQUID_COEF_MIN = 1
const float DAMAGE_ENVIRO_LIQUID_COEF_MAX = 1.5
const float DAMAGE_ENVIRO_TEMPDIFF_MIN = 80
const float DAMAGE_ENVIRO_TEMPDIFF_MAX = 10
Member Function Documentation
AffectLiquidContainerOnFill()
override void AffectLiquidContainerOnFill (int liquid_type, float amount) inline private
References Math::Clamp(), DAMAGE_ENVIRO_LIQUID_COEF_MAX, DAMAGE_ENVIRO_LIQUID_COEF_MIN, DAMAGE_ENVIRO_TEMPDIFF_MAX, DAMAGE_ENVIRO_TEMPDIFF_MIN, GetGame(), WorldData::GetLiquidTypeEnviroTemperature(), CGame::GetMission(), GetQuantityMax(), Mission::GetWorldData(), Math::InverseLerp(), and Math::Lerp().
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
DamageBottleConsume()
protected void DamageBottleConsume (float amount, PlayerBase consumer) inline private
References DAMAGE_CONSUME_PER_ML.
Referenced by OnConsume().
FilterAgents()
override int FilterAgents (int agentsIn) inline private
GetEmptyingEndSoundsetHard()
override string GetEmptyingEndSoundsetHard () inline private
GetEmptyingEndSoundsetSoft()
override string GetEmptyingEndSoundsetSoft () inline private
GetEmptyingEndSoundsetWater()
override string GetEmptyingEndSoundsetWater () inline private
GetEmptyingLoopSoundsetHard()
override string GetEmptyingLoopSoundsetHard () inline private
GetEmptyingLoopSoundsetSoft()
override string GetEmptyingLoopSoundsetSoft () inline private
GetEmptyingLoopSoundsetWater()
override string GetEmptyingLoopSoundsetWater () inline private
GetItemOverheatThreshold()
override float GetItemOverheatThreshold () inline private
disregards liquid boil threshold if filled
GetPouringSoundset()
override string GetPouringSoundset () inline private
IsOpen()
override bool IsOpen () inline private
OnConsume()
override void OnConsume (float amount, PlayerBase consumer) inline private
References DamageBottleConsume().
OnItemOverheat()
override void OnItemOverheat (float deltaTime) inline private
References DAMAGE_OVERHEAT_PER_S.
Field Documentation
DAMAGE_CONSUME_PER_ML
const float DAMAGE_CONSUME_PER_ML = 0.01 private
Referenced by DamageBottleConsume().
DAMAGE_ENVIRO_LIQUID_COEF_MAX
const float DAMAGE_ENVIRO_LIQUID_COEF_MAX = 1.5 private
Referenced by AffectLiquidContainerOnFill().
DAMAGE_ENVIRO_LIQUID_COEF_MIN
const float DAMAGE_ENVIRO_LIQUID_COEF_MIN = 1 private
Referenced by AffectLiquidContainerOnFill().
DAMAGE_ENVIRO_TEMPDIFF_MAX
const float DAMAGE_ENVIRO_TEMPDIFF_MAX = 10 private
Referenced by AffectLiquidContainerOnFill().
DAMAGE_ENVIRO_TEMPDIFF_MIN
const float DAMAGE_ENVIRO_TEMPDIFF_MIN = 80 private
Referenced by AffectLiquidContainerOnFill().
DAMAGE_OVERHEAT_PER_S
const float DAMAGE_OVERHEAT_PER_S = 1 private
Referenced by OnItemOverheat().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Edible_Base/Bottle_Base/FilteringBottle.c