DayZ Scripts: RainProcurementManager Class Reference
RainProcurementManager Class Reference
Private Member Functions
void RainProcurementManager (ItemBase procuring_item)
void InitRainProcurement ()
void RainProcurementCheck ()
bool IsRunning ()
void StopRainProcurement ()
Private Attributes
protected ItemBase m_ProcuringItem
protected int m_IsUnderRoof
protected ref Timer m_UpdateTimer
protected const int RAIN_COEFFICIENT = 10
Detailed Description
Definition at line 1 of file RainProcurementManager.c.
Constructor & Destructor Documentation
RainProcurementManager()
void RainProcurementManager (ItemBase procuring_item) inline private
Definition at line 8 of file RainProcurementManager.c.
References m_ProcuringItem.
Member Function Documentation
InitRainProcurement()
void InitRainProcurement () inline private
Definition at line 14 of file RainProcurementManager.c.
References m_IsUnderRoof, m_ProcuringItem, and m_UpdateTimer.
Referenced by Barrel_ColorBase::Open(), and Barrel_ColorBase::OpenLoad().
IsRunning()
bool IsRunning () inline private
Definition at line 70 of file RainProcurementManager.c.
References m_UpdateTimer.
Referenced by Barrel_ColorBase::Close(), and Barrel_ColorBase::CloseLoad().
RainProcurementCheck()
void RainProcurementCheck () inline private
Definition at line 28 of file RainProcurementManager.c.
References Liquid::FillContainerEnviro(), WeatherPhenomenon::GetActual(), GetGame(), Weather::GetRain(), CGame::GetWeather(), LIQUID_WATER, m_ProcuringItem, RAIN_COEFFICIENT, and StopRainProcurement().
StopRainProcurement()
void StopRainProcurement () inline private
Definition at line 75 of file RainProcurementManager.c.
References m_IsUnderRoof, m_UpdateTimer, and Timer::Stop().
Referenced by Barrel_ColorBase::Close(), Barrel_ColorBase::CloseLoad(), and RainProcurementCheck().
Field Documentation
m_IsUnderRoof
protected int m_IsUnderRoof private
Definition at line 4 of file RainProcurementManager.c.
Referenced by InitRainProcurement(), and StopRainProcurement().
m_ProcuringItem
protected ItemBase m_ProcuringItem private
Definition at line 3 of file RainProcurementManager.c.
Referenced by InitRainProcurement(), RainProcurementCheck(), and RainProcurementManager().
m_UpdateTimer
protected ref Timer m_UpdateTimer private
Definition at line 5 of file RainProcurementManager.c.
Referenced by InitRainProcurement(), IsRunning(), and StopRainProcurement().
RAIN_COEFFICIENT
protected const int RAIN_COEFFICIENT = 10 private
Definition at line 6 of file RainProcurementManager.c.
Referenced by RainProcurementCheck().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/RainProcurementManager.c