DayZ Scripts: FirearmActionAttachMagazine Class Reference
FirearmActionAttachMagazine Class Reference
Private Member Functions
void FirearmActionAttachMagazine ()
override int GetActionCategory ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override ActionData CreateActionData ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool Post_SetupAction (ActionData action_data)
override bool InventoryReservation (ActionData action_data)
override void Start (ActionData action_data)
override bool CanBePerformedFromInventory ()
override bool CanBePerformedFromQuickbar ()
Constructor & Destructor Documentation
FirearmActionAttachMagazine()
void FirearmActionAttachMagazine () inline private
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References HumanCommandWeapons::GetRunningAction().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
CanBePerformedFromInventory()
override bool CanBePerformedFromInventory () inline private
CanBePerformedFromQuickbar()
override bool CanBePerformedFromQuickbar () inline private
CreateActionData()
override ActionData CreateActionData () inline private
GetActionCategory()
override int GetActionCategory () inline private
References AC_SINGLE_USE.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
References ActionTarget, AttachMagazineActionReciveData::m_ilOldMagazine, ActionData::m_MainItem, ActionData::m_Target, and vector::Zero.
InventoryReservation()
override bool InventoryReservation (ActionData action_data) inline private
References GameInventory::c_InventoryReservationTimeoutMS, IsInstant(), IsLocal(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_ReservedInventoryLocations, ActionData::m_Target, InventoryLocation::SetAttachment(), InventoryLocation::SetHands(), and UseAcknowledgment().
Referenced by Start().
Post_SetupAction()
override bool Post_SetupAction (ActionData action_data) inline private
References GetGame(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
References AttachMagazineActionReciveData::m_ilOldMagazine, and InventoryLocation::ReadFromContext().
Start()
override void Start (ActionData action_data) inline private
References ClearInventoryReservationEx(), InventoryReservation(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Weapons/FirearmActionAttachMagazine.c