DayZ Scripts: Math library
Math library
Data Structures
class Math
Functions
private void Math ()
private void ~Math ()
static proto int GetNumberOfSetBits (int i)
returns the number of bits set in a bitmask i
static proto int GetNthBitSet (int value, int n)
returns the the index of n-th bit set in a bit mask counting from the right, for instance, in a mask ..0110 1000 , the 0th set bit(right-most bit set to 1) is at 3th position(starting at 0), 1st bit is at 5th position, 2nd bit is at 6th position etc..
static proto int RandomInt (int min, int max)
Returns a random int number between and min [inclusive] and max [exclusive].
static int RandomIntInclusive (int min, int max)
Returns a random int number between and min [inclusive] and max [inclusive].
static bool RandomBool ()
Returns a random bool .
static proto float RandomFloat (float min, float max)
Returns a random float number between and min[inclusive] and max[exclusive].
static float RandomFloatInclusive (float min, float max)
Returns a random float number between and min [inclusive] and max [inclusive].
static float RandomFloat01 ()
Returns a random float number between and min [inclusive] and max [inclusive].
static proto int Randomize (int seed)
Sets the seed for the random number generator.
static proto float NormalizeAngle (float ang)
Normalizes the angle (0...360)
static proto float DiffAngle (float angle1, float angle2)
Return relative difference between angles.
static proto float Pow (float v, float power)
Return power of v ^ power.
static proto float ModFloat (float x, float y)
Returns the floating-point remainder of x/y rounded towards zero.
static proto float RemainderFloat (float x, float y)
Returns the floating-point remainder of x/y rounded to nearest.
static proto float AbsFloat (float f)
Returns absolute value.
static proto int AbsInt (int i)
Returns absolute value.
static proto float SignFloat (float f)
Returns sign of given value.
static proto int SignInt (int i)
Returns sign of given value.
static proto float SqrFloat (float f)
Returns squared value.
static proto int SqrInt (int i)
Returns squared value.
static proto float Sqrt (float val)
Returns square root.
static proto float Log2 (float x)
Returns the binary (base-2) logarithm of x.
static proto float Sin (float angle)
Returns sinus of angle in radians.
static proto float Cos (float angle)
Returns cosinus of angle in radians.
static proto float Tan (float angle)
Returns tangent of angle in radians.
static proto float Asin (float s)
Returns angle in radians from sinus.
static proto float Acos (float c)
Returns angle in radians from cosinus.
static proto float Atan (float x)
Returns angle in radians from tangent.
static proto float Atan2 (float y, float x)
Returns angle in radians from tangent.
static proto float Round (float f)
Returns mathematical round of value.
static proto float Floor (float f)
Returns floor of value.
static proto float Ceil (float f)
Returns ceil of value.
static proto float WrapFloat (float f, float min, float max)
Returns wrap number to specified interval [min, max[.
static proto float WrapFloatInclusive (float f, float min, float max)
Returns wrap number to specified interval, inclusive [min, max].
static proto float WrapFloat0X (float f, float max)
Returns wrap number to specified interval [0, max[.
static proto float WrapFloat0XInclusive (float f, float max)
Returns wrap number to specified interval, inclusive [0, max].
static proto int WrapInt (int i, int min, int max)
Returns wrap number to specified interval [min, max[.
static proto int WrapInt0X (int i, int max)
Returns wrap number to specified interval [0, max[.
static proto float Clamp (float value, float min, float max)
Clamps 'value' to 'min' if it is lower than 'min', or to 'max' if it is higher than 'max'.
static proto float Min (float x, float y)
Returns smaller of two given values.
static proto float Max (float x, float y)
Returns bigger of two given values.
static proto bool IsInRange (float v, float min, float max)
Returns if value is between min and max (inclusive)
static proto bool IsInRangeInt (int v, int min, int max)
Returns if value is between min and max (inclusive)
static proto float Lerp (float a, float b, float time)
Linearly interpolates between 'a' and 'b' given 'time'.
static proto float InverseLerp (float a, float b, float value)
Calculates the linear value that produces the interpolant value within the range [a, b], it's an inverse of Lerp.
static proto float AreaOfRightTriangle (float s, float a)
Returns area of a right triangle.
static proto float HypotenuseOfRightTriangle (float s, float a)
Returns hypotenus of a right triangle.
static proto bool IsPointInCircle (vector c, float r, vector p)
Returns if point is inside circle.
static proto bool IsPointInRectangle (vector mi, vector ma, vector p)
Returns if point is inside rectangle.
static proto float SmoothCD (float val, float target, inout float velocity[], float smoothTime, float maxVelocity, float dt)
Does the CD smoothing function - easy in | easy out / S shaped smoothing.
static float SmoothCDPI2PI (float val, float target, inout float velocity[], float smoothTime, float maxVelocity, float dt)
static float Poisson (float mean, int occurences)
occurences values above '12' will cause Factorial to overflow int.
static int Factorial (int val)
values above '12' will cause int overflow
static vector CenterOfRectangle (vector min, vector max)
Variables
static const float EULER = 2.7182818284590452353
static const float PI = 3.14159265358979
static const float PI2 = 6.28318530717958
static const float PI_HALF = 1.570796326794
static const float RAD2DEG = 57.2957795130823208768
static const float DEG2RAD = 0.01745329251994329577
Detailed Description
Function Documentation
AbsFloat()
static proto float AbsFloat (float f) static private
Returns absolute value.
Parameters
f float Value
Returns
float - Absolute value
Print(Math.AbsFloat(-12.5));
>> 12.5
Referenced by ActionCondition(), ActionFillBrakes::ActionCondition(), ActionEnterLadder::ActionCondition(), SoftSkillsManager::AddSpecialty(), DayZPlayerImplementAiming::ApplyHorizontalNoise(), WorldData::CalcBaseEnvironmentTemperature(), CalculateEyeAcco(), CCTWaterSurface::Can(), DebugMonitorValues::CheckBlood(), Managed::CheckBlood(), DebugMonitorValues::CheckHealth(), Managed::CheckHealth(), BaseBuildingBase::CheckMemoryPointVerticalDistance(), DayZPlayerImplementHeading::ClampAngle(), Cooling(), DayZIntroScenePC::DayZIntroScenePC(), StaminaHandler::DepleteStamina(), EOnPostSimulate(), EvaluateComponentEx(), EvaluateHit_Player(), EntityLightSource::FadeBrightnessTo(), EntityLightSource::FadeRadiusTo(), DayZInfected::FightLogic(), FilterObstructedObjectsByGrouping(), DayZInfected::GetAttackPitch(), GetCollisionBoxSize(), Environment::GetEnvironmentTemperature(), GetMeleeTargetEx(), ActionTargetsCursor::GetOnScreenPosition(), SoftSkillsManager::GetPreciseRoughLevels(), GetRadius(), Transport::GetSpeedometerAbsolute(), DayZInfected::HandleMove(), DayZPlayer::HandleView(), InitData(), AttachmentsOutOfReach::IsAttachmentReachable(), Hologram::IsBaseFlat(), Hologram::IsCollidingAngle(), BaseBuildingBase::IsFacingPlayer(), ManBase::IsFacingTarget(), IsPlayerOrientedTowardPos(), PointLightBase::OnFrameLightSource(), InventoryActionHandler::OnUpdate(), DayZPlayerImplementAiming::ProcessAimFilters(), Environment::ProcessHeatComfort(), Set(), Weapon_Base::SetCylinderRotationAnimationPhase(), EntityLightSource::SetDancingShadowsAmplitude(), EntityLightSource::SetDancingShadowsMovementSpeed(), PPERequester_GameplayBase::SetEffectProgress(), EntityLightSource::SetFlickerAmplitude(), Hologram::SmoothProjectionMovement(), EnProfilerTests::TestClassTimeData(), EnProfilerTests::TestFuncTimeData(), AnimationTimer::Tick(), AnimatorTimer::Tick(), ScriptedWidgetEventHandler::Update(), WeaponManager::Update(), UIScriptedMenu::Update(), UpdateLRAngleUnlocked(), BoatHud::UpdateSpeedPointer(), UpdateUDAngle(), UpdateUDAngleUnlocked(), UniversalTemperatureSourceLambdaBaseImpl::UpdateVicinityTemperatureRecursive(), and UniversalTemperatureSourceLambdaBaseImpl::WarmAndCoolItemsInVicinity().
AbsInt()
static proto int AbsInt (int i) static private
Returns absolute value.
Parameters
i int Value
Returns
int - Absolute value
Print(Math.AbsInt(-12));
>> 12
Referenced by PluginBase::ActivateModifier(), SoftSkillsManager::AddExponentialPrecise(), SoftSkillsManager::AddExponentialRough(), ManBase::CanChangeStance(), BoatScript::CheckContactCache(), CheckContactCache(), PluginBase::DeactivateModifier(), Hud::DisplayNotifier(), ManBase::GetBrokenLegs(), GetTemperatureColor(), DayZInfected::HandleOrientation(), DayZPlayer::HandleView(), PluginBase::IsModifierLocked(), PluginBase::LockModifier(), HealthMdfr::OnTick(), OrderedPositionNumbersFromGridCoords(), Hud::RefreshVehicleHud(), CarHud::RefreshVehicleHud(), PlayerAgentPool::RemoteGrowRequestDebug(), PluginBase::RequestDetailedInfo(), AutoHeightSpacer::Update(), ManBase::UpdateCorpseState(), and ManBase::UpdateCorpseStateVisual().
Acos()
static proto float Acos (float c) static private
Returns angle in radians from cosinus.
Parameters
c float Cosinus
Returns
float - Angle in radians
Print(Math.Acos(0.707107)); // (cosinus 45)
>> 0.785398
Referenced by ActionCreateIndoorFireplace::ActionCondition(), ActionCreateIndoorOven::ActionCondition(), ActionPlaceFireplaceIndoor::ActionCondition(), ActionPlaceOvenIndoor::ActionCondition(), DayZInfected::ComputeHitDirectionAngle(), DayZCreatureAI::ComputeHitDirectionAngleDeg(), DayZInfected::ComputeHitDirectionAngleEx(), DropAllItemsInInventoryInBounds(), DayZPlayer::EvaluateDamageHitAnimation(), DayZPlayer::EvaluateDeathAnimation(), IsEntityBehindEntityInAngle(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), IsPlayerOrientedTowardPos(), Weapon::LiftWeaponCheck(), and OnAttachmentRuined().
AreaOfRightTriangle()
static proto float AreaOfRightTriangle (float s, float a) static private
Returns area of a right triangle.
Parameters
s float Length of adjacent leg
a float Angle of corner bordering adjacent which is not the right corner (in radians)
Returns
float - Area
Asin()
static proto float Asin (float s) static private
Returns angle in radians from sinus.
Parameters
s float Sinus
Returns
float - Angle in radians
Print(Math.Asin(0.707107)); // (sinus 45)
>> 0.785398
Referenced by Easing::EaseInElastic(), Easing::EaseInOutElastic(), Easing::EaseOutElastic(), and Weapon::LiftWeaponCheck().
Atan()
static proto float Atan (float x) static private
Returns angle in radians from tangent.
Parameters
x float Tangent
Returns
float - Angle in radians
Referenced by PPERequester_GameplayBase::SetEffectProgress().
Atan2()
static proto float Atan2 (float y, float x) static private
Returns angle in radians from tangent.
Parameters
y float Tangent
x float Tangent
Returns
float - Angle in radians
Print (Math.Atan2(1, 1));
>> 0.785398
Referenced by DayZIntroScene::DayZIntroScene(), GetMousePointerAngle(), DayZInfected::HandleOrientation(), MeleeTargetSettings(), and PluginBase::OnUpdate().
Ceil()
static proto float Ceil (float f) static private
Returns ceil of value.
Parameters
f float Value
Returns
float - Ceil of value
Print(Math.Ceil(5.3));
Print(Math.Ceil(5.8));
>> 6
>> 6
Referenced by ActionTargetsCursor::BuildFloatingCursor(), BleedChanceData::CalculateBleedChance(), CAContinuousMineWood::CreateSecondaryItems(), RecipeBase::Do(), CatchingContextPoissonBase::GetSignalMax(), ItemBase::Init(), Attachments::InitAttachmentGrid(), ServerBrowserTabConsolePages::LoadExtraEntries(), UIScriptedMenu::NextPrevPage(), ScriptedWidgetEventHandler::OnUpdate(), UIScriptedMenu::ProcessDistanceAndUnits(), ServerBrowserTab::UpdatePageButtons(), Container::UpdateRowVisibility(), and FlammableBase::Upgrade().
CenterOfRectangle()
static vector CenterOfRectangle (vector min, vector max) inline static private
References Vector(), and x.
Referenced by RefreshTracksCache().
Clamp()
static proto float Clamp (float value, float min, float max) static private
Clamps 'value' to 'min' if it is lower than 'min', or to 'max' if it is higher than 'max'.
Parameters
value float Value
min float Minimum value
max float Maximum value
Returns
float - Clamped value
Print(Math.Clamp(-0.1, 0, 1));
Print(Math.Clamp(2, 0, 1));
Print(Math.Clamp(0.5, 0, 1));
>> 0
>> 1
>> 0.5
Referenced by Chat::Add(), ComponentEnergyManager::AddEnergy(), SoftSkillsManager::AddExponentialPrecise(), SoftSkillsManager::AddExponentialRough(), IEntity::AddHealthLevel(), SoftSkillsManager::AddLinearPrecise(), SoftSkillsManager::AddLinearRough(), BaseBuildingBase::AddRefresherTime01(), AddWetnessToFireplace(), AddWetnessToItem(), AdjustCameraParameters(), ItemBase::AdjustDetectionRange(), ActionRepairVehiclePartBase::AdjustVehicleHealthServer(), FilteringBottle::AffectLiquidContainerOnFill(), Bottle_Base::AffectLiquidContainerOnFill(), Hologram::AlignProjectionOnTerrain(), BaseBuildingBase::AnimateFlagEx(), RecoilBase::ApplyCamOffset(), RecoilBase::ApplyHandsOffset(), RecoilBase::ApplyMouseOffset(), InfluenzaAgent::AutoinfectCheck(), HitDirectionEffectBase::CalculateArrowPosition(), GameplayEffectWidgets_base::CalculateBreathEffect(), UndergroundBunkerHandlerClient::CalculateEyeAcco(), PluginBase::CalculateHealth(), DayZPlayerImplementAiming::CalculateSwayMultiplier(), WorldData::CalculateVolFog(), EnochData::CalculateVolFog(), RecipeBase::CanDo(), Managed::CheckBlood(), DayZPlayerImplementHeading::ClampAngle(), Barrel_ColorBase::ColourClothes(), WorldData::ComputeSnowflakeScale(), DamageCrew(), DecreaseCookedItemQuantity(), UIScriptedMenu::DeleteKeyframe(), StaminaHandler::DepleteStamina(), WrittenNoteData::DepleteWritingImplement(), InjurySoundHandlerBase::DetermineInjuryZone(), Hud::DisplayNotifier(), Hud::DisplayTendencyNormal(), RecipeBase::Do(), WeaponDebug::DrawLineOfFireCameraHybrid(), UniversalTemperatureSourceLambdaBaseImpl::DryItemsInVicinity(), EOnPostSimulate(), ItemBase::Fertilize(), PPEffects::FlashbangEffect(), ManBase::FreezeCheck(), ConstructionActionData::GetActualAttachmentToDetach(), GetAirResistanceForSmokeParticles(), CatchingContextFishingRodAction::GetBaitLossChanceModifierClamped(), ItemBase::GetFuel(), ManBase::GetHealthRegenSpeed(), CatchingContextFishingRodAction::GetHookLossChanceModifierClamped(), ManBase::GetImmunity(), CAContinuousQuantityEdible::GetProgress(), Hologram::GetProjectionEntityPosition(), SoundHandlerBase::GetStaminaState(), GetTemperatureColor(), UIScriptedMenu::GetTotalTime(), GetZone(), PlayerAgentPool::GrowAgents(), HandleFallDamage(), Entity::HandleFreezingProgression(), Entity::HandleItemOverheating(), GameplayEffectWidgets_base::HandleWidgetRoot(), PPEffects::HitEffect(), HitDirectionEffectBase::Init(), Entity::InitItemVariables(), Weapon::LiftWeaponCheck(), ScriptedWidgetEventHandler::LoadEntries(), DayZCreature::ModCommandHandlerBefore(), RightArea::MoveUpDownIcons(), Environment::NormalizedTemperature(), ItemBase::OnAction(), BaseBuildingBase::OnCEUpdate(), ActionRefuelTorch::OnExecuteServer(), Grenade_Base::OnExplosionEffects(), ActionRepairCarPart::OnFinishProgressServer(), CarScript::OnSound(), BleedingSourcesManagerBase::OnTick(), OnTick(), ModifierBase::OnTick(), CommonColdMdfr::OnTick(), InfluenzaMdfr::OnTick(), HeatComfortMdfr::OnTick(), ShockDamageMdfr::OnTick(), TimerBase::OnUpdate(), DayZPlayerCamera3rdPersonErc::OnUpdate(), SymptomBase::OnUpdateClient(), BoatScript::OnVehicleJumpOutServer(), OnVehicleJumpOutServer(), GameplayEffectWidgets_base::OnVoiceEvent(), FlashbangEffect::PlaySound(), DayZPlayerImplementAiming::ProcessAimFilters(), RainProcurementHandler::ProcessBatch(), Environment::ProcessHeatComfort(), BleedingSourcesManagerBase::ProcessHit(), ProcessNoiseComponents(), MissionBase::RandomArtillery(), ScriptedWidgetEventHandler::RandomizePageIndex(), PlayerAgentPool::ReduceAgent(), ReduceContents(), PPERequesterBase::RelativizeValue(), PPERequester_GameplayBase::ReSampleChannels(), SanitizeString(), PluginBase::SelectedObjectSetDamage(), Managed::SendInitValues(), CatchingResultBasic::SetCatchChance(), InventoryItem::SetCleanness(), UniversalTemperatureSourceLambdaFireplace::SetCurrentTemperature(), PPEffects::SetDeathDarkening(), PPERequester_GameplayBase::SetEffectProgress(), PPERequester_GameplayBase::SetFlashbangIntensity(), PPERequester_GameplayBase::SetInitialLenseOffset(), Entity::SetItemOverheatProgress(), CAContinuousRepeatFishing::SetNewSignalData(), CatchingResultBasic::SetQuality(), InventoryItem::SetQuantity(), InventoryItem::SetQuantityNormalized(), BaseBuildingBase::SetRefreshTimer01(), StaminaHandler::SetStamina(), PluginBase::SetStamina(), Entity::SetTemperatureDirect(), Entity::SetTemperatureEx(), PlayerAgentPool::SetTemporaryResistance(), InventoryItem::SetWet(), ShockDealtEffect::ShockDealtEffect(), Hud::ShowPlayerTag(), ManBase::SimplifyShock(), SnapOnObject(), Transfer(), TruncateVec(), DamageDealtEffect::Update(), FlashbangEffect::Update(), ShockDealtEffect::Update(), NotificationUI::Update(), HitDirectionEffectBase::Update(), PPEMatClassParameterCommandData::Update(), RecoilBase::Update(), CatchingContextTrapsBase::UpdateBaseProbability(), UpdateCookingState(), IngameHudHeatBuffer::UpdateEffect(), LeftArea::UpdateSelectionIcons(), UpdateSize(), BoatHud::UpdateSpeedPointer(), BleedingIndicatorDropData::UpdateTransform(), and ValueToBar().
Cos()
static proto float Cos (float angle) static private
Returns cosinus of angle in radians.
Parameters
angle float Angle in radians
Returns
float - Cosinus of angle
Print(Math.Cos(0.785398)); // (45)
>> 0.707107
Referenced by ItemBase::CalcDamageAreaRotation(), HitDirectionEffectBase::CalculateArrowPosition(), Debug::DrawCone(), DropAllItemsInInventoryInBounds(), Easing::EaseInOutSine(), Easing::EaseInSine(), FilterObstructedObjectsByGrouping(), HitDirectionEffectBase::FinalizePositionCalculation(), FlareSimulation::FlareParticleUpdate(), GetHeadingVector(), GetRandomizedPosition(), DayZInfected::HandleOrientation(), OnAttachmentRuined(), PointLightBase::OnFrameLightSource(), EntityPlacementCallback::OnSetup(), PPERequester_GameplayBase::ProcessSimulation(), Refresh(), VicinityItemManager::RefreshVicinityItems(), vector::RotateAroundZeroDeg(), vector::RotateAroundZeroRad(), BleedingIndicatorDropData::ScatterPosition(), and PPERequester_GameplayBase::SetEffectProgress().
DiffAngle()
static proto float DiffAngle (float angle1, float angle2) static private
Return relative difference between angles.
Parameters
angle1 float
angle2 float
Returns
float Difference between angles (angle1 - angle2)
Print(Math.DiffAngle(-45, 45));
Print(Math.DiffAngle(90, 80));
>> -90
>> 10
Factorial()
static int Factorial (int val) inline static private
values above '12' will cause int overflow
References ErrorEx.
Referenced by Poisson().
Floor()
static proto float Floor (float f) static private
Returns floor of value.
Parameters
f float Value
Returns
float - Floor of value
Print(Math.Floor(5.3));
Print(Math.Floor(5.8));
>> 5
>> 5
Referenced by WorldData::CalcBaseEnvironmentTemperature(), BleedChanceData::CalculateBleedChance(), DayZIntroScenePC::CharacterRotate(), CreateItemBasePiles(), CreateMagazinePiles(), CreateMagazinePilesFromBullet(), FishYieldItemBase::GetCycleTimeForYieldItem(), HasMaterials(), UIScriptedMenu::ProcessDistanceAndUnits(), IngameHudHeatBuffer::SetBaseAlpha(), VicinitySlotsContainer::ShowItemsInContainers(), MissionBase::SortedInsert(), ServerBrowserTab::SortedInsertAsc(), ServerBrowserTab::SortedInsertDesc(), ServerBrowserTab::SortedInsertEx(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), SpawnItems(), InventoryItem::SplitItem(), InventoryItem::SplitItemToInventoryLocation(), TakeMaterialsServer(), Barrel_ColorBase::TanPelts(), TruncateVec(), and ScriptedWidgetEventHandler::TutorialKeybinds().
GetNthBitSet()
static proto int GetNthBitSet (int value, int n) static private
returns the the index of n-th bit set in a bit mask counting from the right, for instance, in a mask ..0110 1000 , the 0th set bit(right-most bit set to 1) is at 3th position(starting at 0), 1st bit is at 5th position, 2nd bit is at 6th position etc..
Referenced by AreaExposureMdfr::BleedingSourceCreateCheck(), PluginBase::InjectAgentsWithPlayer(), and PluginBase::InjectAgentsWithPlayerCount().
GetNumberOfSetBits()
static proto int GetNumberOfSetBits (int i) static private
returns the number of bits set in a bitmask i
Referenced by AreaExposureMdfr::BleedingSourceCreateCheck(), GetNumberOfSetBits(), PluginBase::InjectAgentsWithPlayer(), PluginBase::InjectAgentsWithPlayerCount(), Land_WarheadStorage_PowerStation::OnLeverToggled(), and RecipeCacheData::SetMask().
HypotenuseOfRightTriangle()
static proto float HypotenuseOfRightTriangle (float s, float a) static private
Returns hypotenus of a right triangle.
Parameters
s float Length of adjacent leg
a float Angle of corner bordering adjacent which is not the right corner (in radians)
Returns
float - hypotenus
InverseLerp()
static proto float InverseLerp (float a, float b, float value) static private
Calculates the linear value that produces the interpolant value within the range [a, b], it's an inverse of Lerp.
Parameters
a float Start
b float End
value float value
Returns
float - the time given the position between 'a' and 'b' given 'value', there is no clamp on 'value', to stay between [0..1] use 'value' between 'a' and 'b'
Print(Math.InverseLerp(3, 7, 5));
>> 0.5
Referenced by ItemBase::AdjustDetectionRange(), FilteringBottle::AffectLiquidContainerOnFill(), Bottle_Base::AffectLiquidContainerOnFill(), RecoilBase::ApplyCamOffset(), Environment::CalcTemperatureFromTemperatureSource(), PluginBase::CalcTemperatureFromTemperatureSource(), BleedChanceData::CalculateBleedChance(), GameplayEffectWidgets_base::CalculateBreathEffect(), UndergroundBunkerHandlerClient::CalculateEyeAcco(), DebugMonitor::CalculateMapTile(), Managed::CheckBlood(), WorldData::ComputeSnowflakeScale(), ConvertMins12hToAlarmHand01(), DamageCrew(), BroomBase::DebugSetHealthAndEnergy(), WeaponDebug::DrawLineOfFireCameraHybrid(), CGame::ExplosionEffects(), ManBase::FreezeCheck(), HeatComfortAnimHandler::GetEventTime(), Mask_Base::GetFilterQuantity01(), ManBase::GetHealthRegenSpeed(), GetNormalized(), InventoryItem::GetQuantityNormalized(), ManBase::GetStatLevelBorders(), GetVolumeContainingAgent01(), GetZone(), BoatScript::HandleBoatSplashSound(), HandleFallDamage(), MaskMdfr::HandleSounds(), Weapon::LiftWeaponCheck(), Environment::NormalizedTemperature(), ManBase::OnReceivedHit(), CGame::OnRPC(), BoatScript::OnSound(), BleedingSourcesManagerBase::OnTick(), ModifierBase::OnTick(), PoisoningMdfr::OnTick(), HeatComfortMdfr::OnTick(), ShockDamageMdfr::OnTick(), OnUpdate(), OnVariablesSynchronized(), BoatScript::OnVehicleJumpOutServer(), OnVehicleJumpOutServer(), Environment::ProcessHeatBuffer(), ScriptConsoleGeneralTab::RefreshDateWidgets(), PPERequesterBase::RelativizeValue(), KitchenTimer::SecondsTo01(), Managed::SendInitValues(), Update(), EffectBoatWaterBack::Update(), KuruShake::Update(), DamageDealtEffect::Update(), Update(), FlashbangEffect::Update(), ShockDealtEffect::Update(), HitDirectionEffectBase::Update(), RecoilBase::Update(), ScriptConsoleWeatherTab::UpdateSliderValues(), BoatHud::UpdateSpeedPointer(), BleedingIndicatorDropData::UpdateTransform(), and UniversalTemperatureSourceLambdaBaseImpl::WarmAndCoolItemsInVicinity().
IsInRange()
static proto bool IsInRange (float v, float min, float max) static private
Returns if value is between min and max (inclusive)
Parameters
v float Value
min float Minimum value
max float Maximum value
Returns
bool - if value is within range [min,max]
Print(Math.IsInRange(6.9, 3.6, 9.3));
>> true
IsInRangeInt()
static proto bool IsInRangeInt (int v, int min, int max) static private
Returns if value is between min and max (inclusive)
Parameters
v int Value
min int Minimum value
max int Maximum value
Returns
bool - if value is within range [min,max]
Print(Math.IsInRangeInt(6, 3, 9));
>> true
IsPointInCircle()
static proto bool IsPointInCircle (vector c, float r, vector p) static private
Returns if point is inside circle.
Parameters
c vector Center of circle ([0] and [2] will be used, as a circle is 2D)
r float Radius of circle
p vector Point ([0] and [2] will be used, as a circle is 2D)
Returns
bool - True when point is in circle
IsPointInRectangle()
static proto bool IsPointInRectangle (vector mi, vector ma, vector p) static private
Returns if point is inside rectangle.
Parameters
mi vector Minimums of rectangle ([0] and [2] will be used, as a rectangle is 2D)
ma vector Maximums of rectangle ([0] and [2] will be used, as a rectangle is 2D)
p vector Point ([0] and [2] will be used, as a rectangle is 2D)
Returns
bool - True when point is in rectangle
Referenced by PlayerInsideOfLocationFilter(), and PlayerInsideOfLocationFilter().
Lerp()
static proto float Lerp (float a, float b, float time) static private
Linearly interpolates between 'a' and 'b' given 'time'.
Parameters
a float Start
b float End
time float Time [value needs to be between 0..1 for correct results, no auto clamp applied]
Returns
float - The interpolated result between the two float values.
Print(Math.Lerp(3, 7, 0.5));
>> 5
Referenced by BleedingIndicatorDropData::AdjustColorSaturation(), ItemBase::AdjustDetectionRange(), FilteringBottle::AffectLiquidContainerOnFill(), Bottle_Base::AffectLiquidContainerOnFill(), PlayerSpawnHandler::ApplyAttributes(), DayZPlayerImplementAiming::ApplyBreathingPattern(), RecoilBase::ApplyCamOffset(), DayZPlayerImplementAiming::ApplyHorizontalNoise(), WorldData::CalcBaseEnvironmentTemperature(), BleedChanceData::CalculateBleedChance(), GameplayEffectWidgets_base::CalculateBreathEffect(), CalculateLinePointFade(), DayZPlayerImplementAiming::CalculateSwayMultiplier(), WorldData::CalculateVolFog(), EnochData::CalculateVolFog(), SakhalData::CalculateVolFog(), WorldData::ComputeSnowflakeScale(), ConvertAlarmHand01ToMins(), ConvertAlarmHand01ToMins12h(), DamageCrew(), StaminaHandler::DepleteStamina(), DetermineSpecificFinisherType(), WeaponDebug::DrawLineOfFireCameraHybrid(), EOnPostSimulate(), CGame::ExplosionEffects(), PPERequester_GameplayBase::FadeColourMult(), PPEffects::FlashbangEffect(), ManBase::FreezeCheck(), FishYieldItemBase::GetCycleTimeForYieldItem(), HeatComfortAnimHandler::GetEventTime(), ManBase::GetHealthRegenSpeed(), GetMeleeTargetEx(), InventoryItem::GetTemperatureFreezeTime(), InventoryItem::GetTemperatureThawTime(), Entity::HandleFreezingProgression(), Entity::HandleItemOverheating(), MaskMdfr::HandleSounds(), PPEffects::HitEffect(), KuruShake::KuruShake(), ShockHandler::LerpVignette(), PPEMatClassParameterColor::ModifyResultValues(), PlayerSoundEventBase::OnPlay(), PPERequester_GameplayBase::OnStart(), ModifierBase::OnTick(), PoisoningMdfr::OnTick(), HeatComfortMdfr::OnTick(), ShockDamageMdfr::OnTick(), ManBase::OnUnconsciousUpdate(), TimerBase::OnUpdate(), PPERequester_GameplayBase::OnUpdate(), GameplayEffectWidgets_base::OnVoiceEvent(), PPERequester_GameplayBase::ProcessSimulation(), PPERequester_GameplayBase::ReSampleChannels(), IngameHudHeatBuffer::SetBaseAlpha(), PPERequester_GameplayBase::SetEffectProgress(), ComponentEnergyManager::SetEnergy0To1(), InventoryItem::SetQuantityNormalized(), ManBase::SimplifyShock(), Hologram::SmoothProjectionMovement(), ManBase::SpawnDrowningBubbles(), KitchenTimer::Time01ToSeconds(), DamageDealtEffect::Update(), ShockDealtEffect::Update(), HitDirectionEffectBase::Update(), PPEMatClassParameterCommandData::Update(), BleedingIndicatorDropData::UpdateAlpha(), IngameHudHeatBuffer::UpdateEffect(), BoatHud::UpdateSpeedPointer(), ScriptConsoleGeneralTab::UpdateTime(), BleedingIndicatorDropData::UpdateTransform(), HudDebugWinBase::UpdateValues(), and ValueToBar().
Log2()
static proto float Log2 (float x) static private
Returns the binary (base-2) logarithm of x.
Parameters
x float Value whose logarithm is calculated.
Returns
float The binary logarithm of x: log2x.
If x is negative, it causes a domain error:
If x is zero, it may cause a pole error (depending on the library implementation).
Print(Math.Log2(1.0));
>> 0.0
Referenced by DigestAgents(), and PluginRecipesManagerBase::SortIngredientsInRecipe().
Math()
private void Math () inline private
Max()
static proto float Max (float x, float y) static private
Returns bigger of two given values.
Parameters
x float Value
y float Value
Returns
float - max value
Print(Math.Max(5.3, 2.8));
>> 5.3
Referenced by BleedingIndicatorDropData::BleedingIndicatorDropData(), Environment::CalcTemperatureFromTemperatureSource(), PluginBase::CalcTemperatureFromTemperatureSource(), BleedChanceData::CalculateBleedChance(), CheckBaitCompatibility(), ReplaceItemWithNewLambda::CopyOldPropertiesToNew(), StaminaHandler::DepleteStamina(), UniversalTemperatureSourceLambdaBaseImpl::DryItemsInVicinity(), WorldData::GetBaseEnvTemperatureAtPosition(), Weapon::GetEffectiveAttachmentLength(), CfgGameplayHandler::GetMovementRotationSpeedJog(), CfgGameplayHandler::GetMovementRotationSpeedSprint(), CfgGameplayHandler::GetMovementTimeToSprint(), CfgGameplayHandler::GetMovementTimeToStrafeJog(), CfgGameplayHandler::GetMovementTimeToStrafeSprint(), InventoryItem::GetTemperatureFreezeTime(), Environment::GetTemperatureHeightCorrection(), InventoryItem::GetTemperatureThawTime(), Environment::GetWetDelta(), Entity::HandleFreezingProgression(), Entity::HandleItemOverheating(), HasMaterials(), ManBase::Init(), ItemOptics::InitCameraOverrideProperties(), InventoryItem::ItemBase(), PPEMatClassParameterColor::ModifyResultValues(), ScriptConsoleGeneralTab::OnDoubleClick(), CholeraMdfr::OnTick(), OnTick(), HeavyMetalPhase2Mdfr::OnTick(), Environment::ProcessItemsDryness(), Ammunition_Base::SetFromProjectile(), Hologram::SetOnGround(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), TakeMaterialsServer(), PluginBase::TransmitAgentsEx(), StaminaHandler::Update(), PPEMatClassParameterCommandData::Update(), Update(), BroomBase::UpdateParticle(), Container::UpdateRowVisibility(), FlammableBase::Upgrade(), PlayerRestrictedAreaInstance::ValidatePlayerRestrictedAreaPositions(), and UniversalTemperatureSourceLambdaBaseImpl::WarmAndCoolItemsInVicinity().
Min()
static proto float Min (float x, float y) static private
Returns smaller of two given values.
Parameters
x float Value
y float Value
Returns
float - min value
Print(Math.Min(5.3, 2.8));
>> 2.8
Referenced by Container::AddedToCargoEx(), BleedingIndicatorDropData::AdjustColorSaturation(), StaminaHandler::ApplyExhaustion(), StaminaHandler::CalcStaminaGainBonus(), BleedChanceData::CalculateBleedChance(), BroomBase::CalculateQuantity(), StaminaHandler::DepleteStamina(), InjuredLegNotfr::DisplayBadge(), CGame::GetFOVByZoomType(), GetParentMinSize(), CatchingContextFishingRodAction::InitItemValues(), OnGUI_AnimEvents(), Container::RemovedFromCargo(), ComponentEnergyManager::SetEnergy(), CAContinuousRepeatFishing::SetNewSignalData(), CAContinuousDisinfectPlant::Setup(), CAContinuousFertilizeGardenSlot::Setup(), CAContinuousFill::Setup(), CAContinuousFillCoolant::Setup(), CAContinuousFillFuel::Setup(), CAContinuousFillPowerGenerator::Setup(), CAContinuousQuantityLiquidTransfer::Setup(), CAContinuousTransferQuantity::Setup(), CAContinuousWaterPlant::Setup(), CAContinuousWaterSlot::Setup(), ServerBrowserTab::SortedInsertEx(), MissionBase::TickScheduler(), Transfer(), HudDebugWinBase::Update(), StaminaHandler::Update(), PPEMatClassParameterCommandData::Update(), Update(), updateSlotsCount(), FlammableBase::Upgrade(), and PlayerRestrictedAreaInstance::ValidatePlayerRestrictedAreaPositions().
ModFloat()
static proto float ModFloat (float x, float y) static private
Returns the floating-point remainder of x/y rounded towards zero.
Parameters
x float Value of the quotient numerator
y float Value of the quotient denominator
Returns
float - The remainder of dividing the arguments
Print(Math.ModFloat(5.3, 2));
Print(Math.ModFloat(18.5, 4.2));
>> 1.3
>> 1.7
Referenced by HitDirectionEffectBase::CalculateArrowPosition(), and FModulus().
NormalizeAngle()
static proto float NormalizeAngle (float ang) static private
Normalizes the angle (0...360)
Parameters
ang float Angle for normalizing
Returns
float - Normalized angle
Print(Math.NormalizeAngle(390));
Print(Math.NormalizeAngle(-90));
>> 30
>> 270
Referenced by HitDirectionEffectBase::CalculateArrowPosition(), and DayZInfected::HandleOrientation().
Poisson()
static float Poisson (float mean, int occurences) inline static private
occurences values above '12' will cause Factorial to overflow int.
References EULER, Factorial(), and Pow().
Referenced by GameplayEffectsData::BuildProbabilityData(), and CatchingContextPoissonBase::ModifySignalProbability().
Pow()
static proto float Pow (float v, float power) static private
Return power of v ^ power.
Parameters
v float Value
power float Power
Returns
float - The result of raising v to the given power
Print(Math.Pow(2, 4)); // (2*2*2*2)=16
>> 16
Referenced by AreaExposureMdfr::BleedingSourceCreateCheck(), AgentBase::CalculateAutoinfectProbability(), CombinationLock(), DayZIntroScenePC::DayZIntroScenePC(), StaminaHandler::DepleteStamina(), BleedingSourcesManagerBase::DisplayDebug(), Easing::EaseInElastic(), Easing::EaseInExpo(), Easing::EaseInOutElastic(), Easing::EaseInOutExpo(), Easing::EaseOutElastic(), Easing::EaseOutExpo(), BleedingSourcesManagerBase::GetBleedingSourceCountRemote(), MessageReceiverBase::GetCompareMask(), RecipeBase::GetIngredientMaskForItem(), ScriptConsoleConfigTab::Init(), HitDirectionEffectBase::Init(), PluginBase::InjectAgentsWithPlayer(), PluginBase::InjectAgentsWithPlayerCount(), CatchingContextTrapsBase::ModifySignalProbability(), ScriptConsoleItemsTab::OnChange(), ScriptConsoleConfigTab::OnClick(), OnStoreLoad(), Poisson(), RandomFloatInclusive(), PluginRecipesManagerBase::ResolveIngredients(), ItemBase::SetMaxWaterStateVal(), TruncateVec(), PluginRecipesManagerBase::WalkRecipes(), and ItemBase::WaterAllSlots().
RandomBool()
static bool RandomBool () inline static private
Returns a random bool .
Returns
bool - Random bool either 0 or 1
Print(Math.RandomBool());
Print(Math.RandomBool());
Print(Math.RandomBool());
>> true
>> true
>> false
References RandomIntInclusive().
Referenced by TickState().
RandomFloat()
static proto float RandomFloat (float min, float max) static private
Returns a random float number between and min[inclusive] and max[exclusive].
Parameters
min float Range starts [inclusive]
max float Range ends [exclusive]
Returns
float - Random number in range
Print(Math.RandomFloat(0,1));
Print(Math.RandomFloat(0,2));
>> 0.597561
>> 1.936456
Referenced by Grenade_Base::ActivateRandomTime(), ApplyForce(), Hit_MeatBones::BloodSplatGround(), EffBulletImpactBase::CalculateStoppingForce(), CGame::CloseCombatEffects(), CreateOrgan(), StaminaHandler::DepleteStamina(), RecipeBase::Do(), ItemBase::DoMeasurement(), ManBase::DropItem(), InventoryItemSuper::EEKilled(), Apple::EEOnCECreate(), Bottle_Base::EEOnCECreate(), GreenBellPepper::EEOnCECreate(), Pear::EEOnCECreate(), Plum::EEOnCECreate(), Potato::EEOnCECreate(), Tomato::EEOnCECreate(), Zucchini::EEOnCECreate(), BoatScript::EEOnCECreate(), EEOnCECreate(), EOnPostSimulate(), InventoryItem::ExplodeAmmo(), EntityLightSource::HandleDancingShadows(), EntityLightSource::HandleFlickering(), WorldData::Init(), EnochData::Init(), SakhalData::Init(), KuruShake::KuruShake(), LeakFluid(), ActionWringClothes::OnFinishProgressServer(), BrainDiseaseMdfr::OnTick(), SymptomBase::OnUpdateClient(), GeyserTrigger::RandomizeMouthPos(), Particle::RandomizeOrientation(), ParticleSource::RandomizeOrientation(), GameInventory::SetGroundPosByOwnerBounds(), DeveloperTeleport::SetPlayerPosition(), Particle::SetWiggle(), SpawnDecal(), FlammableBase::StandUp(), ThrowAllItemsInInventory(), CameraShake::Update(), and SakhalData::WeatherOnBeforeChange().
RandomFloat01()
static float RandomFloat01 () inline static private
Returns a random float number between and min [inclusive] and max [inclusive].
Returns
float - Random number in range 0.0 .. 1.0
Print(Math.RandomFloat01());  // 0.0 .. 1.0
>> 0.3
>> 1.0
References RandomFloatInclusive().
Referenced by AgentBase::AutoinfectCheck(), AreaExposureMdfr::BleedingSourceCreateCheck(), ItemBase::CheckRainTick(), ChooseAttack(), CreateParticle(), PluginBase::DetermineChanceToTransmit(), GetRandomizedPosition(), GetRandomPos(), PluginBase::GiveWormsToPlayer(), Edible_Base::HandleFoodStageChangeAgents(), ItemBase::InfestationTimerTick(), AreaExposureMdfr::OnTick(), PoisoningMdfr::OnTick(), BrainDiseaseMdfr::OnTick(), CommonColdMdfr::OnTick(), HeavyMetalPhase2Mdfr::OnTick(), InfluenzaMdfr::OnTick(), PneumoniaMdfr::OnTick(), Edible_Base::ProcessDecay(), ManBase::ProcessFeetDamageServer(), ManBase::ProcessHandDamage(), BleedingSourcesManagerBase::ProcessHit(), ScriptedWidgetEventHandler::RandomizePageIndex(), BleedingSourcesManagerBase::RemoveBleedingSource(), CatchingResultBasic::RollChance(), ManBase::SpreadAgentsEx(), and Managed::Update().
RandomFloatInclusive()
static float RandomFloatInclusive (float min, float max) inline static private
Returns a random float number between and min [inclusive] and max [inclusive].
Parameters
min float Range starts [inclusive]
max float Range ends [inclusive]
Returns
float - Random number in range
Print(Math.RandomFloatInclusive(0, 1));   // 0.0 .. 1.0
Print(Math.RandomFloatInclusive(1, 2));   // 1.0 .. 2.0
>> 0.3
>> 2.0
References Pow(), and RandomInt().
Referenced by ActionRepairVehiclePartBase::AdjustVehicleHealthServer(), PlayerSpawnHandler::ApplyAttributes(), AttachBleedingToZonesByHeight(), InfluenzaAgent::AutoinfectCheck(), WorldData::CalculateWind(), EnochData::CalculateWind(), SakhalData::CalculateWind(), RecipeBase::Do(), PrepareAnimal::Do(), GameplayEffectsData::GenerateSequenceRandomPosition(), FireworksLauncher::GetEventDelay(), HeatComfortAnimHandler::GetEventTime(), FireworksLauncherClientEvent::GetExplosionDelay(), FireworksLauncherClientEvent::GetExplosionDistance(), GetExplosionDistance(), GetQualityModifier(), Math3D::GetRandomDir(), FireworksLauncherClientEvent::GetShotDispersionAngle(), SpookyEventBase::GetSoundPos(), ItemBase::GetTemperatureValue(), GetWaitTimeForCategory(), HitDirectionEffectBase::Init(), Init(), BleedingIndicatorDropData::InitImageScale(), AreaExposureMdfr::OnActivate(), ContaminationStage2Mdfr::OnActivate(), OnActivate(), WoundInfectStage2Mdfr::OnActivate(), ActionEatCereal::OnFinishProgressServer(), ActionRepairCarPart::OnFinishProgressServer(), FireworksLauncherClientEvent::OnFired(), AreaExposureMdfr::OnTick(), FeverMdfr::OnTick(), ContaminationStage2Mdfr::OnTick(), OnTick(), HeavyMetalPhase2Mdfr::OnTick(), SalmonellaMdfr::OnTick(), WoundInfectStage2Mdfr::OnTick(), SymptomBase::OnUpdateClient(), PlateCarrierVest::OnWasAttached(), ProcessSound(), InjurySoundHandlerBase::ProcessSound(), vector::RandomDir(), vector::RandomDir2D(), RandomFloat01(), Randomize(), Particle::RandWiggleFloat(), BleedingIndicatorDropData::ScatterPosition(), ItemBase::SetActive(), InventoryItem::SetCEBasedQuantity(), ContaminatedArea_Dynamic::SpawnItems(), BleedingIndicatorDropData::StartDrop(), WorldData::WeatherOnBeforeChange(), EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
RandomInt()
static proto int RandomInt (int min, int max) static private
Returns a random int number between and min [inclusive] and max [exclusive].
Parameters
min int Range starts [inclusive]
max int Range ends [exclusive]
Returns
int - Random number in range
Print(Math.RandomInt(0, 1));  // only 0
Print(Math.RandomInt(0, 2));  // 0 or 1
>> 0
>> 1
Referenced by AttachBleedingToZonesByHeight(), WorldData::CalculateVolFog(), EnochData::CalculateVolFog(), Catching(), Managed::CreateNewCharacterRandom(), DayZIntroSceneXbox::CreateRandomCharacter(), CreditsLoader::CreateTestJson(), SymptomManager::CreateUniqueID(), InventoryItem::DamageItemAttachments(), InventoryItem::DamageItemInCargo(), DayZIntroScene::DayZIntroScene(), InventoryItem::DoAmmoExplosion(), InventoryItem::EEHitBy(), Apple::EEOnCECreate(), GreenBellPepper::EEOnCECreate(), Pear::EEOnCECreate(), Plum::EEOnCECreate(), Potato::EEOnCECreate(), Tomato::EEOnCECreate(), Zucchini::EEOnCECreate(), MushroomBase::EEOnCECreate(), DayZInfected::EOnInit(), FireworksLauncher::FireworksLauncher(), FishPull(), BloodTypes::GenerateBloodType(), RemotelyActivatedItemBehaviour::GeneratePersistentID(), GameplayEffectsData::GenerateSequenceRandomPosition(), AreaDamageBase::GetRandomHitZone(), array< Class T >::GetRandomIndex(), GetRandomLoadingBackground(), SoundLookupTable::GetSoundBuilder(), ItemBase::GrowthTimerTick(), HandleSoundEffectsPipeCreaking(), Init(), ItemBase::Init(), InitZoneServer(), WeaponParticlesBase::OnActivate(), MapHandler::OnDoubleClick(), ActionUnrestrainSelf::OnFinishProgressServer(), OnSteppedOn(), CholeraMdfr::OnTick(), CommonColdMdfr::OnTick(), HeavyMetalPhase2Mdfr::OnTick(), InfluenzaMdfr::OnTick(), PneumoniaMdfr::OnTick(), SalmonellaMdfr::OnTick(), OnVehicleJumpOutServer(), ItemBase::PlantBase(), ActionBase::PlayActionSound(), PlayPipeCreakingSoundOnLocation(), BleedingSourcesManagerBase::ProcessHit(), RandomFloatInclusive(), RandomIntInclusive(), UIScriptedMenu::RandomizeCharacter(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::RandomizeFSMStateEx(), BetaSound::SaySound(), DayZAIHitComponentHelpers::SelectMostProbableHitComponent(), SelectRandomTrackIndexFromCategory(), SendEmoteRequestSync(), OptionSelector::SetRandomValue(), ShuffleLock(), ItemBase::SoundCollision(), BarbedWireTrigger::SoundCollision(), ItemBase::SoundCut(), ItemBase::SoundElectricShock(), BarbedWireTrigger::SoundElectricShock(), ItemBase::SoundSpark(), TickState(), WorldData::WeatherOnBeforeChange(), EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
RandomIntInclusive()
static int RandomIntInclusive (int min, int max) inline static private
Returns a random int number between and min [inclusive] and max [inclusive].
Parameters
min int Range starts [inclusive]
max int Range ends [inclusive]
Returns
int - Random number in range
Print(Math.RandomIntInclusive(0, 1)); // 0 or 1
Print(Math.RandomIntInclusive(0, 2)); // 0, 1, 2
>> 1
>> 2
References RandomInt().
Referenced by AreaExposureMdfr::BleedingSourceCreateCheck(), WorldData::CalculateVolFog(), EnochData::CalculateVolFog(), WorldData::CalculateWind(), EnochData::CalculateWind(), SakhalData::CalculateWind(), DamageHands(), CAContinuousMineWood::DamagePlayersHands(), RecipeBase::Do(), PrepareAnimal::Do(), Weapon::FillChamber(), Weapon::FillInnerMagazine(), FireworksLauncher::FireworksLauncher(), AreaDamageComponentRaycasted::GetFallbackHitZone(), GetRandomizedPosition(), AreaDamageBase::GetRaycastedHitZone(), FireworksLauncherClientEvent::GetSecondaryExplosionDelay(), DayZInfected::HandleDamageHit(), HitDirectionEffectBase::Init(), CholeraMdfr::OnActivate(), OnFinishProgressServer(), ActionPackGift::OnFinishProgressServer(), TrapBase::OnServerSteppedOn(), OnSteppedOn(), CholeraMdfr::OnTick(), ToxicityMdfr::OnTick(), OnVehicleJumpOutServer(), OpenItem::OpenAndSwitch(), Edible_Base::ProcessDecay(), MissionBase::RandomArtillery(), RandomBool(), Randomize(), RandomizedDeviation(), HitDirectionImagesBase::RandomizeImageIdx(), ScriptedWidgetEventHandler::RandomizePageIndex(), CrashBase::RandomizePosition(), SelectEvent(), HitDirectionEffectBase::SetIndicatorRotation(), Weapon::SpawnAttachedMagazine(), CrashBase::SpawnRandomDeers(), HotSpringTrigger::SpawnVaporEffect(), VolcanicTrigger::SpawnVaporEffect(), WorldData::WeatherOnBeforeChange(), EnochData::WeatherOnBeforeChange(), and SakhalData::WeatherOnBeforeChange().
Randomize()
static proto int Randomize (int seed) static private
Sets the seed for the random number generator.
Parameters
seed int New seed for the random number generator, -1 will use time
Returns
int - Returns new seed
Print(Math.Randomize(5));
>> 5
Referenced by AttachBleedingToZonesByHeight(), CGame::CGame(), ChooseAttack(), AreaDamageBase::GetRandomHitZone(), GetRandomLoadingBackground(), KuruShake::KuruShake(), CGame::OnAfterCreate(), FireworksLauncher::OnVariablesSynchronized(), Randomize(), RandomizedDeviation(), and ScriptedWidgetEventHandler::RandomizePageIndex().
RemainderFloat()
static proto float RemainderFloat (float x, float y) static private
Returns the floating-point remainder of x/y rounded to nearest.
Parameters
x float Value of the quotient numerator
y float Value of the quotient denominator
Returns
float - The remainder of dividing the arguments
Print(Math.RemainderFloat(5.3, 2));
Print(Math.RemainderFloat(18.5, 4.2));
>> -0.7
>> 1.7
Round()
static proto float Round (float f) static private
Returns mathematical round of value.
Parameters
f float Value
Returns
float - closest whole number to 'f'
Print(Math.Round(5.3));
Print(Math.Round(5.8));
>> 5
>> 6
Referenced by AddAgent(), ScriptedWidgetEventHandler::AddItem(), BaseBuildingBase::AddRefresherTime01(), BaseBuildingBase::AnimateFlagEx(), PlayerSpawnHandler::ApplyAttributes(), DayZPlayerImplementAiming::ApplyShakes(), InventoryItem::CombineItems(), CreateOrgan(), Entity::DeSerializeNumericalVars(), InventoryItem::DeSerializeNumericalVars(), DetermineSpecificFinisherType(), RecipeBase::Do(), PoweredOptic_Base::DoMeasurement(), Inventory_Base::EmptySeedPack(), Environment::GetApplicableHeatbuffer(), ScriptedWidgetEventHandler::GetDistanceString(), ComponentEnergyManager::GetEnergy0To100(), VicinitySlotsContainer::GetItemQuantityText(), FlammableBase::GetRagQuantity(), ItemBase::GetTemperatureValue(), EntityLightSource::HandleBlinking(), DayZInfected::HandleOrientation(), UIScriptedMenu::NextPrevPage(), BaseBuildingBase::OnCEUpdate(), Battery9V::OnEnergyAdded(), VehicleBattery::OnEnergyAdded(), Battery9V::OnEnergyConsumed(), Chemlight_ColorBase::OnEnergyConsumed(), VehicleBattery::OnEnergyConsumed(), ModifierBase::OnTick(), OnUpdate(), OrderedAltitudeNumbersPosition(), UIScriptedMenu::ProcessDistanceAndUnits(), Environment::ProcessHeatComfort(), ProcessNoiseComponents(), ScriptedWidgetEventHandler::RefreshItemVariables(), ScriptedWidgetEventHandler::RefreshQuickbarItemVariables(), ScriptedWidgetEventHandler::RemoveItem(), ScriptedWidgetEventHandler::ResetItem(), Set(), ScriptedWidgetEventHandler::SetItem(), ScriptedWidgetEventHandler::SetItemColor(), ActionTargetsCursor::SetItemQuantity(), ScriptedWidgetEventHandler::SetItemQuantity(), Icon::SetQuantity(), SlotsIcon::SetQuantity(), InventoryItem::SetQuantityNormalized(), BaseBuildingBase::SetRefreshTimer01(), UIScriptedMenu::Update(), UIScriptedMenu::UpdateItemInfoQuantity(), UIScriptedMenu::UpdateItemInfoWeight(), ServerBrowserTab::UpdatePageButtons(), ScriptedWidgetEventHandler::UpdateQuantityItems(), UIScriptedMenu::UpdateQuickbarItemCard(), ScriptedWidgetEventHandler::UpdateTemperatureItems(), HudDebugWinBase::UpdateValues(), UpdateZones(), and ValueToBar().
SignFloat()
static proto float SignFloat (float f) static private
Returns sign of given value.
Parameters
f float Value
Returns
float - Sign of given value
Print(Math.SignFloat(-12.0));
Print(Math.SignFloat(0.0));
Print(Math.SignFloat(12.0));
>> -1.0
>> 0
>> 1.0
SignInt()
static proto int SignInt (int i) static private
Returns sign of given value.
Parameters
i int Value
Returns
int - Sign of given value
Print(Math.SignFloat(-12));
Print(Math.SignFloat(0));
Print(Math.SignFloat(12));
>> -1
>> 0
>> 1
Sin()
static proto float Sin (float angle) static private
Returns sinus of angle in radians.
Parameters
angle float Angle in radians
Returns
float - Sinus of angle
Print(Math.Sin(0.785398)); // (45)
>> 0.707107
Referenced by DayZPlayerImplementAiming::ApplyBreathingPattern(), Bobbing(), ItemBase::CalcDamageAreaRotation(), HitDirectionEffectBase::CalculateArrowPosition(), Debug::DrawCone(), DropAllItemsInInventoryInBounds(), Easing::EaseInElastic(), Easing::EaseInOutElastic(), Easing::EaseOutElastic(), Easing::EaseOutSine(), FilterObstructedObjectsByGrouping(), HitDirectionEffectBase::FinalizePositionCalculation(), FlareSimulation::FlareParticleUpdate(), GetHeadingVector(), GetRandomizedPosition(), EntityLightSource::HandleBlinking(), DayZInfected::HandleOrientation(), OnAttachmentRuined(), PointLightBase::OnFrameLightSource(), EntityPlacementCallback::OnSetup(), ManBase::OnUnconsciousUpdate(), PPERequester_GameplayBase::OnUpdate(), DayZPlayerCameraBase::OnUpdate(), SymptomBase::OnUpdateClient(), PPERequester_GameplayBase::ProcessSimulation(), Refresh(), VicinityItemManager::RefreshVicinityItems(), PPERequester_GameplayBase::ReSampleChannels(), vector::RotateAroundZeroDeg(), vector::RotateAroundZeroRad(), PPERequester_GameplayBase::SampleChannels(), BleedingIndicatorDropData::ScatterPosition(), PPERequester_GameplayBase::SetEffectProgress(), and AnimatorTimer::Tick().
SmoothCD()
static proto float SmoothCD (float val, float target, inout float velocity[], float smoothTime, float maxVelocity, float dt) static private
Does the CD smoothing function - easy in | easy out / S shaped smoothing.
Parameters
val actual value
target value we are reaching for -> Target
velocity float[1] - array of ONE member - some kind of memory and actual accel/decel rate, need to be zeroed when filter is about to be reset
smoothTime smoothing parameter, 0.1 .. 0.4 are resonable values, 0.1 is sharp, 0.4 is very smooth
maxVelocity maximal value change when multiplied by dt
dt delta time
Returns
float smoothed/filtered value
val = EnfMath.SmoothCD(val, varTarget, valVelocity, 0.3, 1000, dt);
Referenced by DayZPlayerImplementAiming::ApplyHorizontalNoise(), HitDirectionEffectBase::CalculateArrowPosition(), DayZPlayerCameraBase::HoldBreathFOVEffect(), HoldBreathFOVEffect(), DayZPlayerCameraBase::OnUpdate(), OnUpdate(), DayZPlayerImplementAiming::ProcessStealthFilters(), SmoothCDPI2PI(), StdFovUpdate(), NotificationUI::Update(), UpdateLRAngle(), UpdateLRAngleLookAt(), UpdateLRAngleUnlocked(), UpdateUDAngle(), and UpdateUDAngleUnlocked().
SmoothCDPI2PI()
static float SmoothCDPI2PI (float val, float target, inout float velocity[], float smoothTime, float maxVelocity, float dt) inline static private
References PI, PI2, and SmoothCD().
Referenced by OnUpdate().
SqrFloat()
static proto float SqrFloat (float f) static private
Returns squared value.
Parameters
f float Value
Returns
float - Squared value
Print(Math.SqrFloat(12.5));
>> 156.25
Referenced by ActionTriggerRemotely::ActionCondition(), EvaluateComponentEx(), Environment::GatherTemperatureSources(), GetAttackTypeByDistanceToTarget(), HitZoneSelectionRaycast(), IsPlaceable(), MeleeTargetSettings(), RemoteDetonatorTrigger::OnActivatedByItem(), OnCEUpdate(), RemoteDetonatorTrigger::OnCEUpdate(), Grenade_Base::OnExplosionEffects(), PluginBase::ProcessUniversalTemperatureSources(), and TargetSelection().
SqrInt()
static proto int SqrInt (int i) static private
Returns squared value.
Parameters
i int Value
Returns
int - Squared value
Print(Math.SqrInt(12));
>> 144
Sqrt()
static proto float Sqrt (float val) static private
Returns square root.
Parameters
val float Value
Returns
float - Square of value
Print(Math.Sqrt(25));
>> 5
Referenced by SoftSkillsManager::AddExponentialPrecise(), SoftSkillsManager::AddExponentialRough(), DayZIntroScenePC::DayZIntroScenePC(), Easing::EaseInCirc(), Easing::EaseInOutCirc(), Easing::EaseOutCirc(), CGame::OnRPC(), and UIScriptedMenu::Update().
Tan()
static proto float Tan (float angle) static private
Returns tangent of angle in radians.
Parameters
angle float Angle in radians
Returns
float - Tangens of angle
Print(Math.Tan(0.785398)); // (45)
>> 1
Referenced by GetMeleeTarget(), GetMeleeTargetEx(), and PointLightBase::OnFrameLightSource().
WrapFloat()
static proto float WrapFloat (float f, float min, float max) static private
Returns wrap number to specified interval [min, max[.
Parameters
f float Value
min float Minimum
max float Maximum
Returns
float - number in specified interval [min, max[
Print(Math.WrapFloat(9.0, 1.0, 9.0));
>> 1.0
WrapFloat0X()
static proto float WrapFloat0X (float f, float max) static private
Returns wrap number to specified interval [0, max[.
Parameters
f float Value
max float Maximum
Returns
float - number in specified interval [0, max[
Print(Math.WrapFloat0X(9.0, 9.0));
>> 0.0
WrapFloat0XInclusive()
static proto float WrapFloat0XInclusive (float f, float max) static private
Returns wrap number to specified interval, inclusive [0, max].
Parameters
f float Value
max float Maximum
Returns
float - number in specified interval [0, max]
Print(Math.WrapFloat0XInclusive(9.0, 9.0));
>> 9.0
WrapFloatInclusive()
static proto float WrapFloatInclusive (float f, float min, float max) static private
Returns wrap number to specified interval, inclusive [min, max].
Parameters
f float Value
min float Minimum
max float Maximum
Returns
float - number in specified interval [min, max]
Print(Math.WrapFloatInclusive(9.0, 1.0, 9.0));
>> 9.0
WrapInt()
static proto int WrapInt (int i, int min, int max) static private
Returns wrap number to specified interval [min, max[.
Parameters
i int Value
min float Minimum
max int Maximum
Returns
int - number in specified interval [min, max[
Print(Math.WrapInt(9, 1, 9));
>> 1
Referenced by WeaponStateBase::FindNextFreeMuzzle().
WrapInt0X()
static proto int WrapInt0X (int i, int max) static private
Returns wrap number to specified interval [0, max[.
Parameters
i int Value
max int Maximum
Returns
int - number in specified interval [0, max[
Print(Math.WrapInt0X(9, 9));
>> 0
~Math()
private void ~Math () inline private
Variable Documentation
DEG2RAD
const float DEG2RAD = 0.01745329251994329577 static private
Referenced by ItemBase::CalcDamageAreaRotation(), HitDirectionEffectBase::CalculateArrowPosition(), DayZPlayerImplementHeading::ClampAngle(), FlareSimulation::FlareParticleUpdate(), GetMeleeTarget(), DayZInfected::HandleOrientation(), InitData(), Weapon::LiftWeaponCheck(), MeleeTargetSettings(), DayZCreature::ModCommandHandlerBefore(), OnUpdate(), VicinityItemManager::RefreshVicinityItems(), vector::RotateAroundZeroDeg(), and UIScriptedMenu::SetCameraData().
EULER
const float EULER = 2.7182818284590452353 static private
Referenced by Poisson().
PI
const float PI = 3.14159265358979 static private
Referenced by HitDirectionEffectBase::CalculateArrowPosition(), DayZPlayerImplementHeading::ClampHeading(), Easing::EaseInElastic(), Easing::EaseInOutElastic(), Easing::EaseInOutSine(), Easing::EaseInSine(), Easing::EaseOutElastic(), Easing::EaseOutSine(), fixAngle_PI_PI(), InitData(), SymptomBase::OnUpdateClient(), Refresh(), PPERequester_GameplayBase::ReSampleChannels(), DayZPlayerImplementHeading::RotateOrient(), DeveloperTeleport::SetPlayerPosition(), SmoothCDPI2PI(), and SpawnDecal().
PI2
const float PI2 = 6.28318530717958 static private
Referenced by HitDirectionEffectBase::CalculateArrowPosition(), ManBase::CheckAnimationOverrides(), DayZPlayerImplementHeading::ClampHeading(), fixAngle_PI_PI(), InitData(), DayZCreature::ModCommandHandlerBefore(), PointLightBase::OnFrameLightSource(), DayZPlayerCameraBase::OnUpdate(), DayZPlayerImplementHeading::RotateOrient(), BleedingIndicatorDropData::ScatterPosition(), SmoothCDPI2PI(), and AnimatorTimer::Tick().
PI_HALF
const float PI_HALF = 1.570796326794 static private
Referenced by DayZPlayerImplementHeading::ClampHeading(), GetHeadingVector(), EntityPlacementCallback::OnSetup(), DayZPlayerImplementHeading::RotateOrient(), PPERequester_GameplayBase::SampleChannels(), and PPERequester_GameplayBase::SetEffectProgress().
RAD2DEG
const float RAD2DEG = 57.2957795130823208768 static private
Referenced by ActionCreateIndoorFireplace::ActionCondition(), ActionCreateIndoorOven::ActionCondition(), ActionPlaceFireplaceIndoor::ActionCondition(), ActionPlaceOvenIndoor::ActionCondition(), AddArrow(), DayZInfected::AddArrow(), ManBase::AddArrow(), DayZInfected::ComputeHitDirectionAngle(), DayZCreatureAI::ComputeHitDirectionAngleDeg(), DayZInfected::ComputeHitDirectionAngleEx(), DayZIntroScene::DayZIntroScene(), DayZSpectator::EOnFrame(), EvaluateComponentEx(), DayZPlayer::EvaluateDamageHitAnimation(), DayZPlayer::EvaluateDeathAnimation(), EvaluateHit_Player(), DayZInfected::FightLogic(), FloatingCrossHair(), GetAngleInDegrees(), GetMeleeTargetEx(), DayZInfected::HandleOrientation(), IsEntityBehindEntityInAngle(), IsPlayerOrientedTowardPos(), Weapon::LiftWeaponCheck(), PluginBase::OnUpdate(), DayZPlayerCameraBase::OnUpdate(), OnUpdate(), HitDirectionEffectBase::SetIndicatorRotation(), DeveloperTeleport::SetPlayerPosition(), SpawnDecal(), UpdataControllerInput(), Rotator::Update(), ScriptedWidgetEventHandler::Update(), RadialProgressBar::UpdateChild(), UpdateLRAngle(), UpdateLRAngleLookAt(), UpdateLRAngleUnlocked(), ScriptConsoleSoundsTab::UpdateMousePos(), UpdateUDAngle(), and UpdateUDAngleUnlocked().