DayZ Scripts: PPERequestParamDataBase Class Reference
PPERequestParamDataBase Class Reference
Data for one material parameter, requester side.
Private Member Functions
void PPERequestParamDataBase (int requester_idx, int mat_id, int param_id, int data_type=0, int priority=0, int mask=PPOperators.SET)
void InitValues ()
void SetUpdatingDataValues (bool state)
bool GetUpdatingDataValues ()
void SetDataActive (bool state)
bool IsDataActive ()
void SetSettingDefaultValues (bool state)
bool IsSettingDefaultValues ()
int GetRequesterIDX ()
int GetMaterialID ()
int GetParameterID ()
int GetVarType ()
void SetInteractionMask (int mask)
int GetInteractionMask ()
void SetPriorityLayer (int priority)
int GetPriorityLayer ()
void PPERequestParamDataInt (int requester_idx, int mat_id, int param_id, int data_type=0, int priority=0, int mask=PPOperators.SET, bool relative=false)
void PPERequestParamDataColor (int requester_idx, int mat_id, int param_id, int data_type=0, int priority=0, int mask=PPOperators.SET, bool relative=false)
override void InitValues ()
Private Attributes
PPERequesterBase m_Requester
protected bool m_UpdatingDataValues
protected bool m_IsActive
protected bool m_SettingDefaultValues
protected int m_MaterialID
protected int m_ParameterID
protected int m_VariableType
protected int m_RequesterIDX
protected int m_InteractionMask
protected int m_Priority
int m_IntTarget
int m_IntCurrent
int m_IntLast
ref array< float > m_ColorTarget
ref array< float > m_ColorCurrent
ref array< float > m_ColorLast
ref array< float > m_ColorFormerTarget
ref array< float > m_ColorStart
Detailed Description
Data for one material parameter, requester side.
Definition at line 2 of file PPERequestData.c.
Constructor & Destructor Documentation
PPERequestParamDataBase()
void PPERequestParamDataBase (int requester_idx, int mat_id, int param_id, int data_type = 0, int priority = 0, int mask = PPOperators.SET) inline private
Definition at line 16 of file PPERequestData.c.
References InitValues(), m_InteractionMask, m_IsActive, m_MaterialID, m_ParameterID, m_Priority, m_RequesterIDX, m_SettingDefaultValues, m_UpdatingDataValues, and m_VariableType.
Member Function Documentation
GetInteractionMask()
int GetInteractionMask () inline private
Definition at line 89 of file PPERequestData.c.
References m_InteractionMask.
GetMaterialID()
int GetMaterialID () inline private
Definition at line 69 of file PPERequestData.c.
References m_MaterialID.
Referenced by SendMaterialValueData(), and PPERequesterBase::SetDefaultValuesAll().
GetParameterID()
int GetParameterID () inline private
Definition at line 74 of file PPERequestData.c.
References m_ParameterID.
Referenced by PPEClassBase::InsertParamValueData(), SendMaterialValueData(), and PPERequesterBase::SetDefaultValuesAll().
GetPriorityLayer()
int GetPriorityLayer () inline private
Definition at line 99 of file PPERequestData.c.
References m_Priority.
GetRequesterIDX()
int GetRequesterIDX () inline private
Definition at line 64 of file PPERequestData.c.
References m_RequesterIDX.
Referenced by PPEClassBase::InsertParamValueData(), and PPEMatClassParameterCommandData::InsertRequestData().
GetUpdatingDataValues()
bool GetUpdatingDataValues () inline private
Definition at line 39 of file PPERequestData.c.
References m_UpdatingDataValues.
GetVarType()
int GetVarType () inline private
Definition at line 79 of file PPERequestData.c.
References m_VariableType.
Referenced by PPERequesterBase::SetDefaultValuesAll().
InitValues() [1/2]
void InitValues () inline private
Definition at line 30 of file PPERequestData.c.
Referenced by PPERequestParamDataBase().
InitValues() [2/2]
override void InitValues () inline private
Definition at line 171 of file PPERequestData.c.
IsDataActive()
bool IsDataActive () inline private
Definition at line 49 of file PPERequestData.c.
References m_IsActive.
Referenced by PPERequesterBase::SetDefaultValuesAll().
IsSettingDefaultValues()
bool IsSettingDefaultValues () inline private
Definition at line 59 of file PPERequestData.c.
References m_SettingDefaultValues.
PPERequestParamDataColor()
void PPERequestParamDataColor (int requester_idx, int mat_id, int param_id, int data_type = 0, int priority = 0, int mask = PPOperators.SET, bool relative = false) inline private
Definition at line 166 of file PPERequestData.c.
PPERequestParamDataInt()
void PPERequestParamDataInt (int requester_idx, int mat_id, int param_id, int data_type = 0, int priority = 0, int mask = PPOperators.SET, bool relative = false) inline private
Definition at line 125 of file PPERequestData.c.
SetDataActive()
void SetDataActive (bool state) inline private
Definition at line 44 of file PPERequestData.c.
References m_IsActive.
Referenced by PPEClassBase::InsertParamValueData().
SetInteractionMask()
void SetInteractionMask (int mask) inline private
Definition at line 84 of file PPERequestData.c.
References m_InteractionMask.
SetPriorityLayer()
void SetPriorityLayer (int priority) inline private
Definition at line 94 of file PPERequestData.c.
References m_Priority.
SetSettingDefaultValues()
void SetSettingDefaultValues (bool state) inline private
Definition at line 54 of file PPERequestData.c.
References m_SettingDefaultValues.
SetUpdatingDataValues()
void SetUpdatingDataValues (bool state) inline private
Definition at line 34 of file PPERequestData.c.
References m_UpdatingDataValues.
Referenced by PPEClassBase::InsertParamValueData().
Field Documentation
m_ColorCurrent
ref array<float> m_ColorCurrent private
Definition at line 160 of file PPERequestData.c.
m_ColorFormerTarget
ref array<float> m_ColorFormerTarget private
Definition at line 163 of file PPERequestData.c.
m_ColorLast
ref array<float> m_ColorLast private
Definition at line 161 of file PPERequestData.c.
m_ColorStart
ref array<float> m_ColorStart private
Definition at line 164 of file PPERequestData.c.
m_ColorTarget
ref array<float> m_ColorTarget private
Definition at line 159 of file PPERequestData.c.
m_IntCurrent
int m_IntCurrent private
Definition at line 122 of file PPERequestData.c.
m_InteractionMask
protected int m_InteractionMask private
Definition at line 13 of file PPERequestData.c.
Referenced by GetInteractionMask(), PPERequestParamDataBase(), and SetInteractionMask().
m_IntLast
int m_IntLast private
Definition at line 123 of file PPERequestData.c.
m_IntTarget
int m_IntTarget private
Definition at line 121 of file PPERequestData.c.
m_IsActive
protected bool m_IsActive private
Definition at line 6 of file PPERequestData.c.
Referenced by IsDataActive(), PPERequestParamDataBase(), and SetDataActive().
m_MaterialID
protected int m_MaterialID private
Definition at line 9 of file PPERequestData.c.
Referenced by GetMaterialID(), and PPERequestParamDataBase().
m_ParameterID
protected int m_ParameterID private
Definition at line 10 of file PPERequestData.c.
Referenced by GetParameterID(), and PPERequestParamDataBase().
m_Priority
protected int m_Priority private
Definition at line 14 of file PPERequestData.c.
Referenced by GetPriorityLayer(), PPERequestParamDataBase(), and SetPriorityLayer().
m_Requester
PPERequesterBase m_Requester private
Definition at line 4 of file PPERequestData.c.
Referenced by PPERequesterBase::GetRequestData().
m_RequesterIDX
protected int m_RequesterIDX private
Definition at line 12 of file PPERequestData.c.
Referenced by GetRequesterIDX(), and PPERequestParamDataBase().
m_SettingDefaultValues
protected bool m_SettingDefaultValues private
Definition at line 7 of file PPERequestData.c.
Referenced by IsSettingDefaultValues(), PPERequestParamDataBase(), and SetSettingDefaultValues().
m_UpdatingDataValues
protected bool m_UpdatingDataValues private
Definition at line 5 of file PPERequestData.c.
Referenced by GetUpdatingDataValues(), PPERequestParamDataBase(), and SetUpdatingDataValues().
m_VariableType
protected int m_VariableType private
Definition at line 11 of file PPERequestData.c.
Referenced by GetVarType(), and PPERequestParamDataBase().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/PPEManager/PPERequestData.c