DayZ Scripts: AnimSoundObjectBuilderBank Class Reference
AnimSoundObjectBuilderBank Class Reference
Private Member Functions
void AnimSoundObjectBuilderBank ()
SoundObjectBuilder GetBuilder (string soundSetName)
Static Private Member Functions
static AnimSoundObjectBuilderBank GetInstance ()
Private Attributes
private autoptr map< int, ref SoundObjectBuilder > m_pBuilders
Static Private Attributes
static private ref AnimSoundObjectBuilderBank m_instance
Constructor & Destructor Documentation
AnimSoundObjectBuilderBank()
void AnimSoundObjectBuilderBank () inline private
References m_pBuilders.
Referenced by GetInstance().
Member Function Documentation
GetBuilder()
SoundObjectBuilder GetBuilder (string soundSetName) inline private
Referenced by SoundLookupTable::LoadTable().
GetInstance()
static AnimSoundObjectBuilderBank GetInstance () inline static private
References AnimSoundObjectBuilderBank(), and m_instance.
Referenced by EntityAI::InitImpactSoundData(), and SoundLookupTable::LoadTable().
Field Documentation
m_instance
private ref AnimSoundObjectBuilderBank m_instance static private
Referenced by GetInstance().
m_pBuilders
private autoptr map<int, ref SoundObjectBuilder> m_pBuilders private
Referenced by AnimSoundObjectBuilderBank().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/DayZAnimEventMaps.c