DayZ Scripts: Liquid Class Reference
Liquid Class Reference
Static Private Member Functions
static string GetLiquidClassname (int liquid_type)
static bool InitAllLiquids ()
static void Transfer (ItemBase source_ent, ItemBase target_ent, float quantity=-1)
static bool CanTransfer (ItemBase source_ent, ItemBase target_ent)
static void FillContainer (ItemBase container, int liquid_type, float amount)
static void FillContainerEnviro (ItemBase container, int liquid_type, float amount, bool inject_agents=false)
static bool CanFillContainer (ItemBase container, int liquid_type, bool ignore_fullness_check=false)
static private string GetLiquidConfigProperty (int liquid_type, string property_name, bool is_nutrition_property=false)
static NutritionalProfile GetNutritionalProfileByType (int liquid_type)
static NutritionalProfile GetNutritionalProfileByName (string class_name)
static NutritionalProfile SetUpNutritionalProfile (int liquid_type, string liquid_class_name)
static int GetAgents (int liquid_type)
static float GetToxicity (int liquid_type)
static float GetWaterContent (int liquid_type)
static float GetEnergy (int liquid_type)
static float GetNutritionalIndex (int liquid_type)
static string GetName (int liquid_type)
static float GetFlammability (int liquid_type)
static float GetFullness (int liquid_type)
static float GetDigestibility (int liquid_type)
Static Private Attributes
static ref map< int, ref NutritionalProfile > m_AllLiquidsByType = new map<int, ref NutritionalProfile>
static ref map< string, ref NutritionalProfile > m_AllLiquidsByName = new map<string, ref NutritionalProfile>
static bool m_Init = InitAllLiquids()
Detailed Description
Definition at line 1 of file Liquid.c.
Member Function Documentation
CanFillContainer()
static bool CanFillContainer (ItemBase container, int liquid_type, bool ignore_fullness_check = false) inline static private
Definition at line 148 of file Liquid.c.
Referenced by ActionWorldLiquidActionSwitch::ActionCondition(), CanTransfer(), FillContainer(), and ActionFillBottleBase::GetLiquidType().
CanTransfer()
static bool CanTransfer (ItemBase source_ent, ItemBase target_ent) inline static private
Definition at line 84 of file Liquid.c.
References CanFillContainer(), and Barrel_ColorBase::IsOpen().
Referenced by ActionDrainLiquid::ActionCondition(), ActionPourLiquid::ActionCondition(), ActionTransferLiquid::ActionCondition(), RecipeBase::CanDo(), and Transfer().
FillContainer()
static void FillContainer (ItemBase container, int liquid_type, float amount) inline static private
Definition at line 126 of file Liquid.c.
References CanFillContainer().
Referenced by FillContainerEnviro(), and Transfer().
FillContainerEnviro()
static void FillContainerEnviro (ItemBase container, int liquid_type, float amount, bool inject_agents = false) inline static private
Definition at line 138 of file Liquid.c.
References AGT_WATER_POND, FillContainer(), and GetPlugin().
Referenced by CAContinuousFill::CalcAndSetQuantity(), RainProcurementComponentBase::ProcureLiquid(), and RainProcurementManager::RainProcurementCheck().
GetAgents()
static int GetAgents (int liquid_type) inline static private
Definition at line 241 of file Liquid.c.
References GetLiquidConfigProperty(), and string::ToInt().
GetDigestibility()
static float GetDigestibility (int liquid_type) inline static private
Definition at line 281 of file Liquid.c.
References GetLiquidConfigProperty(), and string::ToFloat().
Referenced by SetUpNutritionalProfile().
GetEnergy()
static float GetEnergy (int liquid_type) inline static private
Definition at line 256 of file Liquid.c.
References GetLiquidConfigProperty(), and string::ToFloat().
GetFlammability()
static float GetFlammability (int liquid_type) inline static private
Definition at line 271 of file Liquid.c.
References GetLiquidConfigProperty(), and string::ToFloat().
GetFullness()
static float GetFullness (int liquid_type) inline static private
Definition at line 276 of file Liquid.c.
References GetLiquidConfigProperty(), and string::ToFloat().
Referenced by SetUpNutritionalProfile().
GetLiquidClassname()
static string GetLiquidClassname (int liquid_type) inline static private
Definition at line 8 of file Liquid.c.
References NutritionalProfile::GetLiquidClassname(), and m_AllLiquidsByType.
Referenced by ManBase::Consume().
GetLiquidConfigProperty()
static private string GetLiquidConfigProperty (int liquid_type, string property_name, bool is_nutrition_property = false) inline static private
Definition at line 187 of file Liquid.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetInt(), CGame::ConfigGetText(), g_Game, and GetGame().
Referenced by GetAgents(), GetDigestibility(), GetEnergy(), GetFlammability(), GetFullness(), GetName(), GetNutritionalIndex(), GetToxicity(), and GetWaterContent().
GetName()
static string GetName (int liquid_type) inline static private
Definition at line 266 of file Liquid.c.
References GetLiquidConfigProperty().
GetNutritionalIndex()
static float GetNutritionalIndex (int liquid_type) inline static private
Definition at line 261 of file Liquid.c.
References GetLiquidConfigProperty(), and string::ToFloat().
Referenced by SetUpNutritionalProfile().
GetNutritionalProfileByName()
static NutritionalProfile GetNutritionalProfileByName (string class_name) inline static private
Definition at line 222 of file Liquid.c.
References class_name, and m_AllLiquidsByName.
Referenced by AddToStomach().
GetNutritionalProfileByType()
static NutritionalProfile GetNutritionalProfileByType (int liquid_type) inline static private
Definition at line 217 of file Liquid.c.
References m_AllLiquidsByType.
GetToxicity()
static float GetToxicity (int liquid_type) inline static private
Definition at line 246 of file Liquid.c.
References GetLiquidConfigProperty(), and string::ToFloat().
Referenced by SetUpNutritionalProfile().
GetWaterContent()
static float GetWaterContent (int liquid_type) inline static private
Definition at line 251 of file Liquid.c.
References GetLiquidConfigProperty(), and string::ToFloat().
Referenced by SetUpNutritionalProfile().
InitAllLiquids()
static bool InitAllLiquids () inline static private
Definition at line 19 of file Liquid.c.
References CGame::ConfigGetChildName(), CGame::ConfigGetInt(), g_Game, GetGame(), m_AllLiquidsByName, m_AllLiquidsByType, and SetUpNutritionalProfile().
SetUpNutritionalProfile()
static NutritionalProfile SetUpNutritionalProfile (int liquid_type, string liquid_class_name) inline static private
Definition at line 227 of file Liquid.c.
References GetAgents(), GetDigestibility(), GetEnergy(), GetFullness(), GetNutritionalIndex(), GetToxicity(), GetWaterContent(), and NutritionalProfile::MarkAsLiquid().
Referenced by InitAllLiquids().
Transfer()
static void Transfer (ItemBase source_ent, ItemBase target_ent, float quantity = -1) inline static private
Definition at line 39 of file Liquid.c.
References AGT_TRANSFER_COPY, CanTransfer(), Math::Clamp(), FillContainer(), and GetPlugin().
Referenced by CAContinuousQuantityLiquidTransfer::CalcAndSetQuantity(), and RecipeBase::Do().
Field Documentation
m_AllLiquidsByName
ref map<string, ref NutritionalProfile> m_AllLiquidsByName = new map<string, ref NutritionalProfile> static private
Definition at line 4 of file Liquid.c.
Referenced by GetNutritionalProfileByName(), and InitAllLiquids().
m_AllLiquidsByType
ref map<int, ref NutritionalProfile> m_AllLiquidsByType = new map<int, ref NutritionalProfile> static private
Definition at line 3 of file Liquid.c.
Referenced by GetLiquidClassname(), GetNutritionalProfileByType(), and InitAllLiquids().
m_Init
bool m_Init = InitAllLiquids() static private
Definition at line 6 of file Liquid.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Static/Liquid.c