DayZ Scripts: SceneObject Class Reference
SceneObject Class Reference
Private Member Functions
SceneObject Init (string obj_name, vector pos)
EntityAI GetObject ()
string GetName ()
bool IsPlayer ()
string GetInitScript ()
void SetInitScript (string init_script)
void EditorShapeUpdatePos ()
void EditorShapeSetColor (int color)
void EditorShapeSelect ()
void EditorShapeDeselect ()
vector GetSize ()
void EditorShapeAdd ()
void EditorShapeRemove ()
void EditorLineRemove (SceneObject obj)
void EditorLineAdd (SceneObject obj)
void LinkEntityAI (EntityAI e)
bool IsLinkedWithSceneObject (SceneObject scene_object)
void LinkSceneObject (SceneObject scene_object, bool draw_line=true)
void UnlinkSceneObject (SceneObject scene_object)
void UnlinkAll ()
array< SceneObject > GetLinkedSceneObjects ()
int GetLinkedSceneObjectsCount ()
SceneObject GetLinkedSceneObject (int i)
EntityAI GetLinkedObject (int i)
void ~SceneObject ()
string GetTypeName ()
void PlaceOnSurface ()
void SetPosition (vector pos)
vector GetPosition ()
float GetHealth ()
float GetMaxHealth ()
void SetHealth (float value)
string GetPositionAsString ()
void SetPositionAsString (string string_pos)
float GetRotation ()
void SetRotation (float rot)
void SceneObjectSynch (Param p)
void AddRotation (float add_rot)
void AddAttachment (string att_name)
bool CanAttachment (EntityAI e)
void RemoveAttachment (EntityAI e)
array< EntityAI > GetAttachments ()
TStringArray GetConfigAttachments ()
override bool IsPlayer ()
Private Attributes
protected EntityAI m_ObjectPtr
protected Shape m_DebugShapeBBox
protected string m_InitScript
protected string m_ObjectName
protected string m_ObjectNameOrigin
protected ref array< SceneObject > m_LinkedSceneObjects
protected ref map< SceneObject, Shape > m_LinkedSceneObjectsShapes
ref array< int > m_LinkedSceneObjectsIndices
Static Private Attributes
static const int COLOR_OBJ_BBOX_NORMAL = 0x00000000
static const int COLOR_OBJ_BBOX_SELECT = 0x1f007C00
Detailed Description
Definition at line 1 of file SceneObject.c.
Constructor & Destructor Documentation
~SceneObject()
void ~SceneObject () inline private
Definition at line 356 of file SceneObject.c.
References EditorLineRemove(), EditorShapeRemove(), GetGame(), GetPlayer(), m_LinkedSceneObjects, m_ObjectPtr, and CGame::ObjectDelete().
Member Function Documentation
AddAttachment()
void AddAttachment (string att_name) inline private
Definition at line 546 of file SceneObject.c.
References GetObject().
Referenced by PluginBase::SelectedObjectDuplicate().
AddRotation()
void AddRotation (float add_rot) inline private
Definition at line 523 of file SceneObject.c.
References EditorShapeUpdatePos(), GetGame(), m_ObjectPtr, and SceneObjectSynch().
CanAttachment()
bool CanAttachment (EntityAI e) inline private
Definition at line 554 of file SceneObject.c.
References GetObject().
EditorLineAdd()
void EditorLineAdd (SceneObject obj) inline private
Definition at line 232 of file SceneObject.c.
References Debug::DrawArrow(), EditorLineRemove(), GetObject(), GetSize(), and m_LinkedSceneObjectsShapes.
Referenced by PluginBase::EditorUpdate(), and LinkSceneObject().
EditorLineRemove()
void EditorLineRemove (SceneObject obj) inline private
Definition at line 216 of file SceneObject.c.
References m_LinkedSceneObjectsShapes.
Referenced by EditorLineAdd(), PluginBase::EditorUpdate(), UnlinkSceneObject(), and ~SceneObject().
EditorShapeAdd()
void EditorShapeAdd () inline private
Definition at line 169 of file SceneObject.c.
References Debug::DrawBox(), EditorShapeDeselect(), EditorShapeUpdatePos(), GetSize(), and m_DebugShapeBBox.
Referenced by PluginBase::EditorUpdate().
EditorShapeDeselect()
void EditorShapeDeselect () inline private
Definition at line 135 of file SceneObject.c.
References COLOR_OBJ_BBOX_NORMAL, and EditorShapeSetColor().
Referenced by EditorShapeAdd(), and PluginBase::EditorUpdate().
EditorShapeRemove()
void EditorShapeRemove () inline private
Definition at line 204 of file SceneObject.c.
References m_DebugShapeBBox.
Referenced by PluginBase::EditorUpdate(), and ~SceneObject().
EditorShapeSelect()
void EditorShapeSelect () inline private
Definition at line 127 of file SceneObject.c.
References COLOR_OBJ_BBOX_SELECT, and EditorShapeSetColor().
Referenced by PluginBase::EditorUpdate().
EditorShapeSetColor()
void EditorShapeSetColor (int color) inline private
Definition at line 116 of file SceneObject.c.
References m_DebugShapeBBox.
Referenced by EditorShapeDeselect(), and EditorShapeSelect().
EditorShapeUpdatePos()
void EditorShapeUpdatePos () inline private
Definition at line 99 of file SceneObject.c.
References GetObject(), and m_DebugShapeBBox.
Referenced by AddRotation(), EditorShapeAdd(), SetPosition(), and SetRotation().
GetAttachments()
array< EntityAI > GetAttachments () inline private
Definition at line 570 of file SceneObject.c.
References GetObject().
Referenced by PluginBase::SelectedObjectDuplicate().
GetConfigAttachments()
TStringArray GetConfigAttachments () inline private
Definition at line 585 of file SceneObject.c.
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, CGame::ConfigGetTextArray(), GetGame(), and GetTypeName().
Referenced by UIScriptedMenu::Refresh().
GetHealth()
float GetHealth () inline private
Definition at line 433 of file SceneObject.c.
References m_ObjectPtr.
Referenced by UIScriptedMenu::Refresh(), and PluginConfigHandler::SaveSceneObjects().
GetInitScript()
string GetInitScript () inline private
Definition at line 83 of file SceneObject.c.
References m_InitScript.
Referenced by PluginBase::ExecuteInitScripts(), UIPopupScript::OnOpen(), and PluginConfigHandler::SaveSceneObjects().
GetLinkedObject()
EntityAI GetLinkedObject (int i) inline private
Definition at line 348 of file SceneObject.c.
References GetLinkedSceneObject(), and GetObject().
GetLinkedSceneObject()
SceneObject GetLinkedSceneObject (int i) inline private
Definition at line 340 of file SceneObject.c.
References m_LinkedSceneObjects.
Referenced by GetLinkedObject(), and UnlinkAll().
GetLinkedSceneObjects()
array< SceneObject > GetLinkedSceneObjects () inline private
Definition at line 324 of file SceneObject.c.
References m_LinkedSceneObjects.
Referenced by PluginBase::EditorUpdate(), and PluginConfigHandler::SaveSceneObjects().
GetLinkedSceneObjectsCount()
int GetLinkedSceneObjectsCount () inline private
Definition at line 332 of file SceneObject.c.
References m_LinkedSceneObjects.
Referenced by UnlinkAll().
GetMaxHealth()
float GetMaxHealth () inline private
Definition at line 443 of file SceneObject.c.
References m_ObjectPtr.
GetName()
string GetName () inline private
Definition at line 67 of file SceneObject.c.
References m_ObjectName.
GetObject()
EntityAI GetObject () inline private
Definition at line 59 of file SceneObject.c.
References m_ObjectPtr.
Referenced by AddAttachment(), CanAttachment(), PluginBase::DeleteSceneObject(), EditorLineAdd(), EditorShapeUpdatePos(), PluginBase::ExecuteEnforceScript(), GetAttachments(), GetLinkedObject(), PluginBase::GetSceneObjectByEntity(), GetSize(), PluginConfigHandler::LoadSceneObjects(), PluginConfigHandler::SaveSceneObjects(), PluginBase::SelectedObjectDuplicate(), and PluginBase::SelectedObjectSetDamage().
GetPosition()
vector GetPosition () inline private
Definition at line 423 of file SceneObject.c.
References m_ObjectPtr, and Vector().
Referenced by UIScriptedMenu::Refresh(), PluginBase::SelectedObjectDuplicate(), PluginBase::SelectedObjectFocus(), PluginBase::SelectedObjectSetPosX(), PluginBase::SelectedObjectSetPosY(), and PluginBase::SelectedObjectSetPosZ().
GetPositionAsString()
string GetPositionAsString () inline private
Definition at line 472 of file SceneObject.c.
References m_ObjectPtr, vector::ToString(), and Vector().
Referenced by PluginConfigHandler::SaveSceneObjects().
GetRotation()
float GetRotation () inline private
Definition at line 490 of file SceneObject.c.
References m_ObjectPtr.
Referenced by UIScriptedMenu::Refresh(), PluginConfigHandler::SaveSceneObjects(), and PluginBase::SelectedObjectDuplicate().
GetSize()
vector GetSize () inline private
Definition at line 143 of file SceneObject.c.
References GetObject(), m_ObjectNameOrigin, Print(), and Vector().
Referenced by EditorLineAdd(), EditorShapeAdd(), and PluginBase::SelectedObjectFocus().
GetTypeName()
string GetTypeName () inline private
Definition at line 375 of file SceneObject.c.
References m_ObjectPtr.
Referenced by GetConfigAttachments(), UIScriptedMenu::GetFiltredSceneObjects(), UIScriptedMenu::Refresh(), PluginConfigHandler::SaveSceneObjects(), PluginLocalProfile::SceneSave(), PluginBase::SelectedObjectDuplicate(), and UIScriptedMenu::UpdateListObjects().
Init()
SceneObject Init (string obj_name, vector pos) inline private
Definition at line 20 of file SceneObject.c.
References GetGame(), GetPlugin(), CGame::IsKindOf(), LinkEntityAI(), m_LinkedSceneObjects, m_LinkedSceneObjectsIndices, m_LinkedSceneObjectsShapes, m_ObjectName, m_ObjectNameOrigin, and STRING_EMPTY.
Referenced by SceneData::AddObject(), and SceneData::CreateSceneObject().
IsLinkedWithSceneObject()
bool IsLinkedWithSceneObject (SceneObject scene_object) inline private
Definition at line 264 of file SceneObject.c.
References m_LinkedSceneObjects.
Referenced by PluginBase::AreSceneObjectsLinked(), and LinkSceneObject().
IsPlayer() [1/2]
bool IsPlayer () inline private
Definition at line 75 of file SceneObject.c.
Referenced by SceneData::AddObject(), PluginBase::DeleteSelectedObject(), and PluginBase::Event_OnClickMiddle().
IsPlayer() [2/2]
override bool IsPlayer () inline private
Definition at line 6 of file ScenePlayer.c.
LinkEntityAI()
void LinkEntityAI (EntityAI e) inline private
Definition at line 256 of file SceneObject.c.
References m_ObjectPtr.
Referenced by SceneData::AddObject(), and Init().
LinkSceneObject()
void LinkSceneObject (SceneObject scene_object, bool draw_line = true) inline private
Definition at line 280 of file SceneObject.c.
References EditorLineAdd(), IsLinkedWithSceneObject(), and m_LinkedSceneObjects.
Referenced by PluginBase::LinkSceneObjects(), and PluginBase::RestoreSceneObjectsLinks().
PlaceOnSurface()
void PlaceOnSurface () inline private
Definition at line 383 of file SceneObject.c.
References GetGame(), m_ObjectPtr, and SceneObjectSynch().
Referenced by SetPosition().
RemoveAttachment()
void RemoveAttachment (EntityAI e) inline private
Definition at line 562 of file SceneObject.c.
References GetGame(), and CGame::ObjectDelete().
SceneObjectSynch()
void SceneObjectSynch (Param p) inline private
Definition at line 515 of file SceneObject.c.
References GetGame(), GetPlayer(), and CGame::RPCSingleParam().
Referenced by AddRotation(), PlaceOnSurface(), SetHealth(), and SetPosition().
SetHealth()
void SetHealth (float value) inline private
Definition at line 453 of file SceneObject.c.
References GetGame(), m_ObjectPtr, and SceneObjectSynch().
Referenced by PluginConfigHandler::LoadSceneObjects(), and PluginBase::SelectedObjectSetDamage().
SetInitScript()
void SetInitScript (string init_script) inline private
Definition at line 91 of file SceneObject.c.
References m_InitScript.
Referenced by PluginConfigHandler::LoadSceneObjects(), and UIPopupScript::OnClick().
SetPosition()
void SetPosition (vector pos) inline private
Definition at line 402 of file SceneObject.c.
References EditorShapeUpdatePos(), GetGame(), m_ObjectPtr, PlaceOnSurface(), and SceneObjectSynch().
Referenced by PluginBase::SelectedObjectSetPosX(), PluginBase::SelectedObjectSetPosY(), PluginBase::SelectedObjectSetPosZ(), and SetPositionAsString().
SetPositionAsString()
void SetPositionAsString (string string_pos) inline private
Definition at line 482 of file SceneObject.c.
References SetPosition(), and string::ToVector().
SetRotation()
void SetRotation (float rot) inline private
Definition at line 504 of file SceneObject.c.
References EditorShapeUpdatePos(), and m_ObjectPtr.
Referenced by PluginConfigHandler::LoadSceneObjects(), and PluginBase::SelectedObjectDuplicate().
UnlinkAll()
void UnlinkAll () inline private
Definition at line 308 of file SceneObject.c.
References GetLinkedSceneObject(), and GetLinkedSceneObjectsCount().
Referenced by PluginBase::DeleteSceneObject().
UnlinkSceneObject()
void UnlinkSceneObject (SceneObject scene_object) inline private
Definition at line 295 of file SceneObject.c.
References EditorLineRemove(), and m_LinkedSceneObjects.
Referenced by PluginBase::UnlinkSceneObjects().
Field Documentation
COLOR_OBJ_BBOX_NORMAL
const int COLOR_OBJ_BBOX_NORMAL = 0x00000000 static private
Definition at line 3 of file SceneObject.c.
Referenced by EditorShapeDeselect().
COLOR_OBJ_BBOX_SELECT
const int COLOR_OBJ_BBOX_SELECT = 0x1f007C00 static private
Definition at line 4 of file SceneObject.c.
Referenced by EditorShapeSelect().
m_DebugShapeBBox
protected Shape m_DebugShapeBBox private
Definition at line 7 of file SceneObject.c.
Referenced by EditorShapeAdd(), EditorShapeRemove(), EditorShapeSetColor(), and EditorShapeUpdatePos().
m_InitScript
protected string m_InitScript private
Definition at line 8 of file SceneObject.c.
Referenced by GetInitScript(), and SetInitScript().
m_LinkedSceneObjects
protected ref array<SceneObject> m_LinkedSceneObjects private
Definition at line 12 of file SceneObject.c.
Referenced by GetLinkedSceneObject(), GetLinkedSceneObjects(), GetLinkedSceneObjectsCount(), Init(), IsLinkedWithSceneObject(), LinkSceneObject(), UnlinkSceneObject(), and ~SceneObject().
m_LinkedSceneObjectsIndices
ref array<int> m_LinkedSceneObjectsIndices private
Definition at line 15 of file SceneObject.c.
Referenced by Init(), PluginConfigHandler::LoadSceneObjects(), and PluginBase::RestoreSceneObjectsLinks().
m_LinkedSceneObjectsShapes
protected ref map<SceneObject, Shape> m_LinkedSceneObjectsShapes private
Definition at line 13 of file SceneObject.c.
Referenced by EditorLineAdd(), EditorLineRemove(), and Init().
m_ObjectName
protected string m_ObjectName private
Definition at line 9 of file SceneObject.c.
Referenced by GetName(), and Init().
m_ObjectNameOrigin
protected string m_ObjectNameOrigin private
Definition at line 10 of file SceneObject.c.
Referenced by GetSize(), and Init().
m_ObjectPtr
protected EntityAI m_ObjectPtr private
Definition at line 6 of file SceneObject.c.
Referenced by AddRotation(), GetHealth(), GetMaxHealth(), GetObject(), GetPosition(), GetPositionAsString(), GetRotation(), GetTypeName(), LinkEntityAI(), PlaceOnSurface(), SetHealth(), SetPosition(), SetRotation(), and ~SceneObject().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/SceneEditor/SceneObject.c
P:/scripts/4_World/Classes/SceneEditor/ScenePlayer.c