DayZ Scripts: P:/scripts/4_World/Classes/ContaminatedArea/ContaminatedArea.c File Reference
ContaminatedArea.c File Reference
Data Structures
class ContaminatedArea_Base
Functions
ContaminatedArea_Base EffectArea SetupZoneData (EffectAreaParams params)
override void OnPlayerEnterServer (PlayerBase player, EffectTrigger trigger)
override void OnPlayerExitServer (PlayerBase player, EffectTrigger trigger)
override void InitZoneClient ()
override void EEDelete (EntityAI parent)
override void EEInit ()
override void InitZoneServer ()
Function Documentation
EEDelete()
override void EEDelete (EntityAI parent)
EEInit()
override void EEInit ()
InitZoneClient()
override void InitZoneClient ()
References EffectArea::InitZone(), and Debug::Log().
InitZoneServer()
override void InitZoneServer ()
References CreateTrigger(), m_Position, and m_Radius.
OnPlayerEnterServer()
override void OnPlayerEnterServer (PlayerBase player, EffectTrigger trigger)
OnPlayerExitServer()
override void OnPlayerExitServer (PlayerBase player, EffectTrigger trigger)
SetupZoneData()
ContaminatedArea_Base EffectArea SetupZoneData (EffectAreaParams params)