DayZ Scripts: Bot Class Reference
Bot Class Reference
Private Member Functions
void Bot (PlayerBase ow)
void SetInstanceType (DayZPlayerInstanceType t)
void Start (bool use_trigger, BotTrigger trigger=null)
void DelayedStart (float ms)
protected void OnDelayedStart ()
void Stop ()
protected void OnTrigger ()
void OnUpdate (float dt)
void OnTimer ()
bool ProcessEvent (BotEventBase e)
void InitFSM ()
Private Attributes
PlayerBase m_Owner = null
protected ref Timer m_Timer = new Timer
protected const float c_TriggerTimeoutMS = 1000.0
protected const float c_UpdateMS = 16.0
protected ref BotFSM m_FSM = null
protected bool m_UseTrigger = false
protected bool m_Triggered = false
protected DayZPlayerInstanceType m_InstanceType = DayZPlayerInstanceType.INSTANCETYPE_CLIENT
protected ref BotTrigger m_BotTrigger = null
protected ref BotStateBase m_BotTest = null
Constructor & Destructor Documentation
Bot()
void Bot (PlayerBase ow) inline private
References m_Owner.
Member Function Documentation
DelayedStart()
void DelayedStart (float ms) inline private
References m_Timer.
InitFSM()
void InitFSM () inline private
transition table
References m_BotTest, and m_FSM.
Referenced by Start().
OnDelayedStart()
protected void OnDelayedStart () inline private
References m_Owner, m_UseTrigger, ProcessEvent(), and Start().
OnTimer()
void OnTimer () inline private
OnTrigger()
protected void OnTrigger () inline private
References botDebugPrint(), c_TriggerTimeoutMS, c_UpdateMS, BotTrigger::CheckTrigger(), m_BotTrigger, m_Owner, m_Timer, m_Triggered, ProcessEvent(), and Timer::Stop().
Referenced by OnUpdate().
OnUpdate()
void OnUpdate (float dt) inline private
References m_FSM, and OnTrigger().
ProcessEvent()
bool ProcessEvent (BotEventBase e) inline private
References botDebugSpam(), and m_FSM.
Referenced by OnDelayedStart(), and OnTrigger().
SetInstanceType()
void SetInstanceType (DayZPlayerInstanceType t) inline private
References m_InstanceType.
Start()
void Start (bool use_trigger, BotTrigger trigger = null) inline private
References botDebugPrint(), c_TriggerTimeoutMS, c_UpdateMS, Error(), InitFSM(), m_BotTrigger, m_Owner, m_Timer, m_Triggered, and m_UseTrigger.
Stop()
void Stop () inline private
References m_FSM, m_Timer, m_Triggered, and Timer::Stop().
Field Documentation
c_TriggerTimeoutMS
protected const float c_TriggerTimeoutMS = 1000.0 private
Referenced by OnTrigger(), and Start().
c_UpdateMS
protected const float c_UpdateMS = 16.0 private
Referenced by OnTrigger(), and Start().
m_BotTest
protected ref BotStateBase m_BotTest = null private
Referenced by InitFSM().
m_BotTrigger
protected ref BotTrigger m_BotTrigger = null private
Referenced by OnTrigger(), and Start().
m_FSM
protected ref BotFSM m_FSM = null private
Referenced by InitFSM(), OnUpdate(), ProcessEvent(), and Stop().
m_InstanceType
protected DayZPlayerInstanceType m_InstanceType = DayZPlayerInstanceType.INSTANCETYPE_CLIENT private
Referenced by SetInstanceType().
m_Owner
PlayerBase m_Owner = null private
Referenced by Bot(), BotStateIdle::BotStateIdle(), OnDelayedStart(), OnTrigger(), and Start().
m_Timer
protected ref Timer m_Timer = new Timer private
Referenced by DelayedStart(), OnTrigger(), Start(), and Stop().
m_Triggered
protected bool m_Triggered = false private
Referenced by OnTrigger(), Start(), and Stop().
m_UseTrigger
protected bool m_UseTrigger = false private
Referenced by OnDelayedStart(), and Start().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Systems/Bot/Bot.c