DayZ Scripts: CatchYieldBank Class Reference
CatchYieldBank Class Reference
Private Member Functions
void CatchYieldBank ()
protected void Init ()
YieldsMap GetYieldsMap ()
void RegisterYieldItem (YieldItemBase data)
void UnregisterYieldItem (string yieldType)
void ClearAllRegisteredItems ()
nucular option
YieldItemBase GetYieldItemByIdx (int idx)
Private Attributes
protected ref YieldsMap m_AllYieldsMap
private ref array< int > m_OrderedHashes
Constructor & Destructor Documentation
CatchYieldBank()
void CatchYieldBank () inline private
References Init().
Member Function Documentation
ClearAllRegisteredItems()
void ClearAllRegisteredItems () inline private
nucular option
References m_AllYieldsMap.
Referenced by EnochData::InitYieldBank(), and SakhalData::InitYieldBank().
GetYieldItemByIdx()
YieldItemBase GetYieldItemByIdx (int idx) inline private
References m_AllYieldsMap, and m_OrderedHashes.
Referenced by ItemBase::PlayCatchEffectsClient(), and ItemBase::PlayCatchEffectsServer().
GetYieldsMap()
YieldsMap GetYieldsMap () inline private
References m_AllYieldsMap.
Referenced by Init().
Init()
protected void Init () inline private
References m_AllYieldsMap, and m_OrderedHashes.
Referenced by CatchYieldBank().
RegisterYieldItem()
void RegisterYieldItem (YieldItemBase data) inline private
References YieldItemBase::GetType(), string::Hash(), m_AllYieldsMap, m_OrderedHashes, and YieldItemBase::SetRegistrationIdx().
Referenced by MissionBaseWorld::InitWorldYieldDataDefaults(), EnochData::InitYieldBank(), and SakhalData::InitYieldBank().
UnregisterYieldItem()
void UnregisterYieldItem (string yieldType) inline private
References string::Hash(), and m_AllYieldsMap.
Field Documentation
m_AllYieldsMap
protected ref YieldsMap m_AllYieldsMap private
Referenced by ClearAllRegisteredItems(), GetYieldItemByIdx(), GetYieldsMap(), Init(), RegisterYieldItem(), and UnregisterYieldItem().
m_OrderedHashes
private ref array<int> m_OrderedHashes private
Referenced by GetYieldItemByIdx(), Init(), and RegisterYieldItem().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/AnimalCatching/CatchYieldBank.c