DayZ Scripts: TelescopicBaton Class Reference
TelescopicBaton Class Reference
Private Member Functions
void TelescopicBaton ()
override void Open ()
override void Close ()
override bool IsOpen ()
protected void UpdateVisualState ()
override int GetMeleeMode ()
override int GetMeleeHeavyMode ()
override int GetMeleeSprintMode ()
override void OnVariablesSynchronized ()
override void SetActions ()
Private Attributes
protected int m_MeleeMode
protected int m_MeleeHeavyMode
protected int m_MeleeSprintMode
protected ref OpenableBehaviour m_Openable
Constructor & Destructor Documentation
TelescopicBaton()
void TelescopicBaton () inline private
set default melee modes on init
References m_MeleeHeavyMode, m_MeleeMode, m_MeleeSprintMode, m_Openable, and UpdateVisualState().
Member Function Documentation
Close()
override void Close () inline private
sets different set of melee modes for closed state
References OpenableBehaviour::Close(), m_MeleeHeavyMode, m_MeleeMode, m_MeleeSprintMode, m_Openable, and UpdateVisualState().
GetMeleeHeavyMode()
override int GetMeleeHeavyMode () inline private
References m_MeleeHeavyMode.
GetMeleeMode()
override int GetMeleeMode () inline private
References m_MeleeMode.
GetMeleeSprintMode()
override int GetMeleeSprintMode () inline private
References m_MeleeSprintMode.
IsOpen()
override bool IsOpen () inline private
References OpenableBehaviour::IsOpened(), and m_Openable.
Referenced by UpdateVisualState().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References UpdateVisualState().
Open()
override void Open () inline private
sets different set of melee modes for opened state
References m_MeleeHeavyMode, m_MeleeMode, m_MeleeSprintMode, m_Openable, OpenableBehaviour::Open(), and UpdateVisualState().
SetActions()
override void SetActions () inline private
References AddAction().
UpdateVisualState()
protected void UpdateVisualState () inline private
References IsOpen().
Referenced by Close(), OnVariablesSynchronized(), Open(), and TelescopicBaton().
Field Documentation
m_MeleeHeavyMode
protected int m_MeleeHeavyMode private
Referenced by Close(), GetMeleeHeavyMode(), Open(), and TelescopicBaton().
m_MeleeMode
protected int m_MeleeMode private
Referenced by Close(), GetMeleeMode(), Open(), and TelescopicBaton().
m_MeleeSprintMode
protected int m_MeleeSprintMode private
Referenced by Close(), GetMeleeSprintMode(), Open(), and TelescopicBaton().
m_Openable
protected ref OpenableBehaviour m_Openable private
Referenced by Close(), IsOpen(), Open(), and TelescopicBaton().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/TelescopicBaton.c