DayZ Scripts: ScientificBriefcase Class Reference
ScientificBriefcase Class Reference
Private Member Functions
override void InitItemVariables ()
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool IsOpen ()
override void Open ()
override void Close ()
Private Attributes
protected ref OpenableBehaviour m_Openable
Member Function Documentation
CanReceiveItemIntoCargo()
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
References IsOpen(), and GameConstants::STATE_RUINED.
Close()
override void Close () inline private
References OpenableBehaviour::Close(), and m_Openable.
Referenced by RecipeBase::Do(), and OnStoreLoad().
InitItemVariables()
override void InitItemVariables () inline private
References m_Openable.
IsOpen()
override bool IsOpen () inline private
References OpenableBehaviour::IsOpened(), and m_Openable.
Referenced by RecipeBase::CanDo(), and CanReceiveItemIntoCargo().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References Close(), Open(), and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
References OpenableBehaviour::IsOpened(), m_Openable, and Serializer::Write().
Open()
override void Open () inline private
References m_Openable, and OpenableBehaviour::Open().
Referenced by RecipeBase::Do(), and OnStoreLoad().
Field Documentation
m_Openable
protected ref OpenableBehaviour m_Openable private
Referenced by Close(), InitItemVariables(), IsOpen(), OnStoreSave(), and Open().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/ScientificBriefcase.c