DayZ Scripts: LeftArea Class Reference
LeftArea Class Reference
Private Member Functions
void LeftArea (LayoutHolder parent)
override void UnfocusGrid ()
override bool IsActive ()
override void SetActive (bool active)
override ScrollWidget GetScrollWidget ()
override void UpdateSelectionIcons ()
float GetCurrentContainerTopY ()
float GetCurrentContainerBottomY ()
override void ExpandCollapseContainer ()
void OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override void SetLayoutName ()
override EntityAI GetFocusedItem ()
VicinityContainer GetVicinityContainer ()
override void SetParentWidget ()
override void OnShow ()
override void Refresh ()
override void UpdateInterval ()
override bool OnChildRemove (Widget w, Widget child)
override bool OnChildAdd (Widget w, Widget child)
Private Attributes
protected Widget m_UpIcon
protected Widget m_DownIcon
protected Widget m_ContentParent
protected ref VicinityContainer m_VicinityContainer
protected ScrollWidget m_ScrollWidget
protected ref SizeToChild m_ContentResize
protected bool m_ShouldChangeSize = true
protected bool m_IsProcessing = false
Constructor & Destructor Documentation
LeftArea()
void LeftArea (LayoutHolder parent) inline private
References WidgetEventHandler::GetInstance(), m_ContentParent, m_ContentResize, m_DownIcon, m_RootWidget, m_ScrollWidget, m_UpIcon, m_VicinityContainer, WidgetEventHandler::RegisterOnChildAdd(), and WidgetEventHandler::RegisterOnChildRemove().
Member Function Documentation
DraggingOverHeader()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
References VicinityContainer::DraggingOverHeader(), m_VicinityContainer, x, and y.
ExpandCollapseContainer()
override void ExpandCollapseContainer () inline private
References Refresh().
GetCurrentContainerBottomY()
float GetCurrentContainerBottomY () inline private
References Container::GetFocusedContainerHeight(), Container::GetFocusedContainerYScreenPos(), x, and y.
Referenced by UpdateSelectionIcons().
GetCurrentContainerTopY()
float GetCurrentContainerTopY () inline private
References Container::GetFocusedContainerYScreenPos(), x, and y.
Referenced by UpdateSelectionIcons().
GetFocusedItem()
override EntityAI GetFocusedItem () inline private
GetScrollWidget()
override ScrollWidget GetScrollWidget () inline private
References m_ScrollWidget.
GetVicinityContainer()
VicinityContainer GetVicinityContainer () inline private
References m_VicinityContainer.
IsActive()
override bool IsActive () inline private
OnChildAdd()
override bool OnChildAdd (Widget w, Widget child) inline private
References m_IsProcessing, and Refresh().
OnChildRemove()
override bool OnChildRemove (Widget w, Widget child) inline private
References m_IsProcessing, and Refresh().
OnLeftPanelDropReceived()
void OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver) inline private
References m_VicinityContainer, VicinityContainer::OnLeftPanelDropReceived(), x, and y.
OnShow()
override void OnShow () inline private
References Refresh().
Refresh()
override void Refresh () inline private
References m_RootWidget, m_ScrollWidget, m_ShouldChangeSize, and UpdateSelectionIcons().
Referenced by ExpandCollapseContainer(), OnChildAdd(), OnChildRemove(), and OnShow().
SetActive()
override void SetActive (bool active) inline private
References UpdateSelectionIcons().
SetLayoutName()
override void SetLayoutName () inline private
References InventoryMenu(), WidgetLayoutName::LeftAreaMedium, WidgetLayoutName::LeftAreaNarrow, WidgetLayoutName::LeftAreaWide, and WidgetLayoutName::LeftAreaXbox.
SetParentWidget()
override void SetParentWidget () inline private
References m_Parent, and m_ParentWidget.
UnfocusGrid()
override void UnfocusGrid () inline private
UpdateInterval()
override void UpdateInterval () inline private
References m_ContentParent, m_ContentResize, m_IsProcessing, m_RootWidget, m_ScrollWidget, m_ShouldChangeSize, x, and y.
UpdateSelectionIcons()
override void UpdateSelectionIcons () inline private
References Math::Clamp(), GetCurrentContainerBottomY(), GetCurrentContainerTopY(), m_DownIcon, m_IsActive, m_UpIcon, x, and y.
Referenced by Refresh(), and SetActive().
Field Documentation
m_ContentParent
protected Widget m_ContentParent private
Referenced by LeftArea(), and UpdateInterval().
m_ContentResize
protected ref SizeToChild m_ContentResize private
Referenced by LeftArea(), and UpdateInterval().
m_DownIcon
protected Widget m_DownIcon private
Referenced by LeftArea(), and UpdateSelectionIcons().
m_IsProcessing
protected bool m_IsProcessing = false private
Referenced by OnChildAdd(), OnChildRemove(), and UpdateInterval().
m_ScrollWidget
protected ScrollWidget m_ScrollWidget private
Referenced by GetScrollWidget(), LeftArea(), Refresh(), and UpdateInterval().
m_ShouldChangeSize
protected bool m_ShouldChangeSize = true private
Referenced by Refresh(), and UpdateInterval().
m_UpIcon
protected Widget m_UpIcon private
Referenced by LeftArea(), and UpdateSelectionIcons().
m_VicinityContainer
protected ref VicinityContainer m_VicinityContainer private
Referenced by DraggingOverHeader(), GetVicinityContainer(), LeftArea(), and OnLeftPanelDropReceived().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Areas/LeftArea.c