DayZ Scripts: InventoryItemSuper Class Reference
InventoryItemSuper Class Reference
Private Member Functions
proto native void SetNextChannel ()
proto native void SetPrevChannel ()
proto native float GetTunedFrequency ()
proto native void EnableBroadcast (bool state)
proto native void EnableReceive (bool state)
proto native bool IsBroadcasting ()
proto native bool IsReceiving ()
proto native int GetTunedFrequencyIndex ()
proto native void SetFrequencyByIndex (int index)
proto native bool CanSpeak ()
proto native void SetCanSpeak (bool onOff)
bool IsTurnedOn ()
override void OnInventoryEnter (Man player)
override void OnInventoryExit (Man player)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnInventoryEnter (Man player)
override void OnInventoryExit (Man player)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
proto native float GetRadius ()
Returns current wheel radius.
proto native float GetWidth ()
Returns wheel width.
override bool DisplayNameRuinAttach ()
override bool ShowZonesHealth ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override int GetMeleeTargetType ()
override void SetActions ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override bool CanDetachAttachment (EntityAI parent)
override int GetMeleeTargetType ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override bool DisplayNameRuinAttach ()
override bool ShowZonesHealth ()
override void SetActions ()
override bool DisplayNameRuinAttach ()
override bool ShowZonesHealth ()
override void EEKilled (Object killer)
override void SetActions ()
override void SetActions ()
proto native bool SetPinned ()
sets grenade to state GR_PINNED (if the state transition is possible)
proto native bool SetUnpinned ()
sets grenade to state GR_UNPINNED (if the state transition is possible)
proto native bool SetIgnited ()
sets grenade to state GR_TRIGGERED (if the state transition is possible)
proto native bool IsPinned ()
proto native bool IsActivated ()
void ItemMap ()
void InitMapState ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
void SetMapStateOpen (bool state, PlayerBase player)
displays open/closed selections; 1 == opened
bool GetMapStateAnimation ()
void SyncMapMarkers ()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override bool NameOverride (out string output)
override bool DescriptionOverride (out string output)
void InsertMarker (vector pos, string text, int color, int idx)
array< ref MapMarker > GetMarkerArray ()
void ItemOptics ()
proto native bool EnterOptics ()
switches to optics mode if possible
proto native bool IsInOptics ()
is weapon in optics mode or not
proto native bool ExitOptics ()
switches out of optics mode (if possible)
proto native bool HasWeaponIronsightsOverride ()
is weapon in optics mode or not
proto native bool UseWeaponIronsightsOverride (bool state)
switches into ironsights override settings
proto native bool IsUsingWeaponIronsightsOverride ()
is optics using ironsights override settings or not
proto native int GetStepFOVCount ()
returns number of configured steps
proto native int GetStepFOVIndex ()
returns index of currently used value in 'discretefov' config array
proto native bool SetStepFOVIndex (int step)
sets zoom to fov value defined at given in 'discretefov' config array
proto native bool StepFOVUp ()
sets zoom to next defined (respective to current) value in zoom fov config array
proto native bool StepFOVDown ()
sets zoom to previous (respective to current) defined value in zoom fov config array
proto native float GetCurrentStepFOV ()
returns fov value at current index, or 'OpticsInfo.opticsZoomInit' config value (non-zooming optics)
proto native int GetStepZeroing ()
returns position of currently used value in zeroing config array
proto native bool SetStepZeroing (int step)
proto native bool StepZeroingUp ()
sets zeroing to next defined (respective to current) value in zeroing config array
proto native bool StepZeroingDown ()
sets zeroing to previous (respective to current) defined value in zeroing config array
proto native void GetCameraPoint (out vector pos, out vector dir)
proto native float GetZoomInit ()
gets FOV value, when entering optics
proto native float GetZoomMin ()
gets FOV minimum
proto native float GetZoomMax ()
gets FOV maximum
proto native float GetZeroingDistanceZoomMin ()
Gets Zeroing distance at opticsZoomMin.
proto native float GetZeroingDistanceZoomMax ()
Gets Zeroing distance at opticsZoomMax.
proto native void SetZeroingClampDist (float dist)
Sets zeroing clamp for the optics and updates the clamp if dist > 0. Used when attached to weapon.
override void OnWorkStart ()
override void OnWorkStop ()
bool IsWorking ()
void UpdateOpticsReddotVisibility ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnInventoryExit (Man player)
override void OnStoreSave (ParamsWriteContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnVariablesSynchronized ()
void InitReddotData ()
void ShowReddot (bool state)
void InitOpticsPPInfo ()
bool InitDOFAvailability ()
optics with more than 1x zoom do not allow DOF changes
void InitOpticsPP (out array< float > mask_array, out array< float > lens_array, out float blur_float)
initializes values for optics' post-processes
void InitCameraOverrideProperties ()
bool InitOpticsDOFProperties (out array< float > temp_array)
Initializes DOF properties for optic's alternate ironsights (ACOG etc.)
bool AllowsDOF ()
returns 'true' for non-magnifying optics
bool IsNVOptic ()
int GetCurrentNVType ()
void SetCurrentOpticMode (int mode)
int GetCurrentOpticMode ()
void OnOpticModeChange ()
optic-specific behaviour to be defined here (override)
void OnOpticEnter ()
void OnOpticExit ()
ref array< float > GetOpticsDOF ()
ref array< float > GetOpticsPPMask ()
ref array< float > GetOpticsPPLens ()
float GetOpticsPPBlur ()
float GetNearPlaneValue ()
void Init2DPreloadType ()
void InitOpticMode ()
void UpdateSelectionVisibility ()
override void SetActions ()
override bool IsWeapon ()
proto native void Synchronize ()
Force synchronizes the weapon state from Server to Client. Use with caution.
proto native int GetMuzzleCount ()
proto native int GetSlotFromMuzzleIndex (int muzzleIndex)
conversion muzzleIndex -> slotId
proto native int GetCurrentMuzzle ()
proto native void SetCurrentMuzzle (int muzzleIndex)
sets index of active muzzle
proto native int GetMuzzleModeCount (int muzzleIndex)
proto native void SetMuzzleMode (int muzzleIndex, int modeIndex)
proto native void SetNextMuzzleMode (int muzzleIndex)
proto native int GetCurrentModeBurstSize (int muzzleIndex)
proto native bool GetCurrentModeAutoFire (int muzzleIndex)
proto native int GetCurrentMode (int muzzleIndex)
proto native void SetCurrentMode (int muzzleIndex, int mode)
proto native owned string GetCurrentModeName (int muzzleIndex)
proto native bool CanFire (int muzzleIndex)
query whether the weapon can be fired or not
proto native bool Fire (int muzzleIndex, vector pos, vector dir, vector speed)
proto native bool DryFire (int muzzleIndex)
proto native bool DryDryFire (int muzzleIndex)
proto native bool EjectCasing (int muzzleIndex)
ejects casing from chamber
proto native bool CreateRound (int muzzleIndex)
proto native bool IsChamberEmpty (int muzzleIndex)
detects empty chamber
proto native bool IsChamberFiredOut (int muzzleIndex)
detects presence of fired out casing in chamber
proto native bool IsChamberJammed (int muzzleIndex)
detects presence of damaged cartridge in chamber
proto native bool IsChamberEjectable (int muzzleIndex)
detects presence of ejectable cartridge in muzzle's chamber
proto native bool IsChamberFull (int muzzleIndex)
maximum number of cartridges in chamber
bool IsChamberFullEx (int muzzleIndex)
proto native bool HasInternalMagazine (int muzzleIndex)
proto native int GetInternalMagazineCartridgeCount (int muzzleIndex)
proto native int GetInternalMagazineMaxCartridgeCount (int muzzleIndex)
bool IsInternalMagazineFull (int muzzleIndex)
maximum number of cartridges in internal magazine
proto native int GetTotalCartridgeCount (int muzzleIndex)
proto native int GetTotalMaxCartridgeCount (int muzzleIndex)
proto native owned string GetRandomChamberableAmmoTypeName (int muzzleIndex)
proto native owned string GetChamberAmmoTypeName (int muzzleIndex)
proto bool GetCartridgeInfo (int muzzleIndex, out float ammoDamage, out string ammoTypeName)
get info about the cartridge in the chamber of a muzzle
proto bool GetInternalMagazineCartridgeInfo (int muzzleIndex, int cartridgeIndex, out float ammoDamage, out string ammoTypeName)
get info about the cartridge in the internal magazine of a muzzle
proto bool PopCartridgeFromChamber (int muzzleIndex, out float ammoDamage, out string ammoTypeName)
removes cartridge from chamber
proto native bool PushCartridgeToChamber (int muzzleIndex, float ammoDamage, string ammoTypeName)
push cartridge to chamber
proto native void EffectBulletShow (int muzzleIndex, float dmg, string type)
push effect cartridge to Weapon
proto native void EffectBulletHide (int muzzleIndex)
reset effect cartridge in weapon
proto native void SetGroundAnimFrameIndex (int groundAnimFrameIndex)
sets animation frame for ground state when animation is specified in config
proto bool PopCartridgeFromInternalMagazine (int muzzleIndex, out float ammoDamage, out string ammoTypeName)
removes top-most cartridge from internal magazine
proto native bool PushCartridgeToInternalMagazine (int muzzleIndex, float ammoDamage, string ammoTypeName)
push cartridge into internal magazine
proto native bool CanAttachMagazine (int muzzleIndex, Magazine mag)
query if a magazine can be attached to weapon
proto native bool TestAttachMagazine (int muzzleIndex, Magazine mag, bool do_occupancy_test, bool do_script_check)
query if a magazine can be attached to weapon
proto native bool AttachMagazine (int muzzleIndex, Magazine mag)
perform attachment of a magazine to weapon
proto native Magazine GetMagazine (int muzzleIndex)
proto native float GetReloadTime (int muzzleIndex)
defines time from one shot to another
proto native bool CanChamberFromMag (int muzzleIndex, Magazine mag)
query if a bullet from magazine can be loaded into chamber
proto native owned string GetChamberedCartridgeMagazineTypeName (int muzzleIndex)
query the type of magazine the cartridge can be unloaded to
proto native owned string GetRandomMagazineTypeName (int muzzleIndex)
proto native owned string GetMaxMagazineTypeName (int muzzleIndex)
proto native int GetMagazineTypeCount (int muzzleIndex)
proto native bool EnterOptics ()
proto native bool IsInOptics ()
proto native bool ExitOptics ()
proto native float GetZoom ()
returns current percentage of zoom
proto native bool SetZoom (float percent)
sets current zoom (in %)
proto native bool ZoomIn ()
moves current zoom by 1% up
proto native bool ZoomOut ()
moves current zoom by 1% down
proto native int GetStepZoom ()
returns position of currently used value in zoom config array
proto native bool SetStepZoom (int step)
sets zoom to fov value defined at given position in zoom fov config array
proto native bool StepZoomIn ()
sets zoom to next defined (respective to current) value in zoom fov config array
proto native bool StepZoomOut ()
sets zoom to previous (respective to current) defined value in zoom fov config array
proto native int GetStepZeroing (int muzzleIndex=0)
proto native bool SetStepZeroing (int muzzleIndex, int step)
proto native bool StepZeroingUp (int muzzleIndex=0)
proto native bool StepZeroingDown (int muzzleIndex=0)
proto native float GetCurrentZeroing (int muzzleIndex=0)
returns currently used value of zeroing in config array of weapon or attached optics
proto native float GetZeroingClamp (int muzzleIndex=0)
returns maximum allowed discrete distance for the muzzle. Limits attached optics zeroing only! '0' if unclamped
proto native bool FlashlightOn ()
attempt to turn on flashlight
proto native bool FlashlightOff ()
attempt to turn off flashlight
proto native bool IsFlashlightOn ()
query state of flashlight
proto native UnderSlugLauncher GetAttachedLauncher ()
proto native ItemOptics GetAttachedOptics ()
proto native ItemSuppressor GetAttachedSuppressor ()
proto native void GetCameraPoint (int muzzleIndex, out vector pos, out vector dir)
proto native float GetZoomInit (int muzzleIndex)
proto native float GetZoomMin (int muzzleIndex)
proto native float GetZoomMax (int muzzleIndex)
proto native float GetZeroingDistanceZoomMin (int muzzleIndex)
proto native float GetZeroingDistanceZoomMax (int muzzleIndex)
proto native void SelectionBulletShow ()
proto native void SelectionBulletHide ()
proto native void SelectionMagazineShow ()
proto native void SelectionMagazineHide ()
void StepZeroingUpAllMuzzles ()
void StepZeroingDownAllMuzzles ()
override event bool OnUseFromInventory (Man owner)
override bool HasFlammableMaterial ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
Private Attributes
protected string m_AttachSound = "Offroad_Wheel_Attach_SoundSet"
protected string m_DetachSound = "Offroad_Wheel_Remove_SoundSet"
protected ref array< ref MapMarker > m_MapMarkerArray
string m_TextureClosed
string m_TextureOpened
string m_TextureLegend
string m_DisplayName
string m_Description
bool m_data_set
bool m_allowsDOF
bool m_reddot_displayed bool m_isNVOptic = false
int m_CurrentOpticMode
int m_CurrentOpticModeLocal
int m_reddot_index
float m_blur_float
float m_nearplane_override
string m_optic_sight_texture
string m_optic_sight_material
string m_2D_preload_type
ref array< float > m_mask_array
ref array< float > m_lens_array
ref array< float > m_OpticsDOFProperties
Member Function Documentation
AllowsDOF()
bool AllowsDOF () inline private
returns 'true' for non-magnifying optics
AttachMagazine()
AttachMagazine (int muzzleIndex, Magazine mag) private
perform attachment of a magazine to weapon
Parameters
[in] muzzleIndex
[in] mag magazine to attach
Returns
true if magazine was attached
CanAttachMagazine()
CanAttachMagazine (int muzzleIndex, Magazine mag) private
query if a magazine can be attached to weapon
Parameters
[in] muzzleIndex
[in] mag magazine to attach
Returns
true if magazine can be attached
CanBeIgnitedBy()
override bool CanBeIgnitedBy (EntityAI igniter = NULL) inline private
CanChamberFromMag()
CanChamberFromMag (int muzzleIndex, Magazine mag) private
query if a bullet from magazine can be loaded into chamber
Parameters
[in] muzzleIndex
[in] mag magazine to load from
Returns
true if cartidge from mag can be put into chamber
CanDetachAttachment()
override bool CanDetachAttachment (EntityAI parent) inline private
References CarScript::GetCarDoorsState(), InventoryLocation::GetSlot(), and InventorySlots::GetSlotName().
CanFire()
CanFire (int muzzleIndex) private
query whether the weapon can be fired or not
Returns
true if fire possible
CanIgniteItem()
override bool CanIgniteItem (EntityAI ignite_target = NULL) inline private
CanSpeak()
proto native bool CanSpeak () private
CreateRound()
proto native bool CreateRound (int muzzleIndex) private
DescriptionOverride()
override bool DescriptionOverride (out string output) inline private
References m_Description.
DisplayNameRuinAttach() [1/3]
override bool DisplayNameRuinAttach () inline private
DisplayNameRuinAttach() [2/3]
override bool DisplayNameRuinAttach () inline private
DisplayNameRuinAttach() [3/3]
override bool DisplayNameRuinAttach () inline private
DryDryFire()
proto native bool DryDryFire (int muzzleIndex) private
DryFire()
proto native bool DryFire (int muzzleIndex) private
EEHealthLevelChanged() [1/2]
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
References GetChildren(), GetSibling(), GetType(), RemoveChild(), ReplaceWheelLambda(), GameConstants::STATE_RUINED, and UnlockFromParent().
EEHealthLevelChanged() [2/2]
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
References m_Initialized, and GameConstants::STATE_RUINED.
EEKilled()
override void EEKilled (Object killer) inline private
References Class::CastTo(), GetGame(), and Math::RandomFloat().
EffectBulletHide()
EffectBulletHide (int muzzleIndex) private
reset effect cartridge in weapon
Parameters
[in] muzzleIndex
EffectBulletShow()
EffectBulletShow (int muzzleIndex, float dmg, string type) private
push effect cartridge to Weapon
Parameters
[in] muzzleIndex
[in] ammoDamage damage of the ammo
[in] ammoTypeName type name of the ammo
EjectCasing()
EjectCasing (int muzzleIndex) private
ejects casing from chamber
EnableBroadcast()
proto native void EnableBroadcast (bool state) private
EnableReceive()
proto native void EnableReceive (bool state) private
EnterOptics() [1/2]
EnterOptics () private
switches to optics mode if possible
Returns
true if success, false otherwise
EnterOptics() [2/2]
proto native bool EnterOptics () private
ExitOptics() [1/2]
ExitOptics () private
switches out of optics mode (if possible)
Returns
true if success, false otherwise
ExitOptics() [2/2]
proto native bool ExitOptics () private
Fire()
proto native bool Fire (int muzzleIndex, vector pos, vector dir, vector speed) private
FlashlightOff()
FlashlightOff () private
attempt to turn off flashlight
Returns
true if on -> off, false otherwise (no flashlight, no power, etc, already off)
FlashlightOn()
FlashlightOn () private
attempt to turn on flashlight
Returns
true if set on, false otherwise (no flashlight, no power, etc)
GetAttachedLauncher()
GetAttachedLauncher () private
Returns
returns attached launcher or null
GetAttachedOptics()
GetAttachedOptics () private
Returns
returns attached optics or null
GetAttachedSuppressor()
GetAttachedSuppressor () private
Returns
returns attached suppressor or null
GetCameraPoint() [1/2]
proto native void GetCameraPoint (int muzzleIndex, out vector pos, out vector dir) private
GetCameraPoint() [2/2]
proto native void GetCameraPoint (out vector pos, out vector dir) private
GetCartridgeInfo()
GetCartridgeInfo (int muzzleIndex, out float ammoDamage, out string ammoTypeName) private
get info about the cartridge in the chamber of a muzzle
Parameters
[in] muzzleIndex
[out] ammoDamage damage of the ammo
[out] ammoTypeName type name of the ejected ammo
Returns
true if info retrieved
GetChamberAmmoTypeName()
GetChamberAmmoTypeName (int muzzleIndex) private
Parameters
[in]
return returns name of i-th ammo type for chambering
GetChamberedCartridgeMagazineTypeName()
GetChamberedCartridgeMagazineTypeName (int muzzleIndex) private
query the type of magazine the cartridge can be unloaded to
Parameters
[in] muzzleIndex
Returns
entity type name
GetCurrentMode()
proto native int GetCurrentMode (int muzzleIndex) private
GetCurrentModeAutoFire()
proto native bool GetCurrentModeAutoFire (int muzzleIndex) private
GetCurrentModeBurstSize()
proto native int GetCurrentModeBurstSize (int muzzleIndex) private
GetCurrentModeName()
proto native owned string GetCurrentModeName (int muzzleIndex) private
GetCurrentMuzzle()
GetCurrentMuzzle () private
Returns
returns index of current muzzle
GetCurrentNVType()
int GetCurrentNVType () inline private
GetCurrentOpticMode()
int GetCurrentOpticMode () inline private
GetCurrentStepFOV()
GetCurrentStepFOV () private
returns fov value at current index, or 'OpticsInfo.opticsZoomInit' config value (non-zooming optics)
GetCurrentZeroing()
GetCurrentZeroing (int muzzleIndex = 0) private
returns currently used value of zeroing in config array of weapon or attached optics
Returns
currently used value in zeroing
GetInternalMagazineCartridgeCount()
proto native int GetInternalMagazineCartridgeCount (int muzzleIndex) private
GetInternalMagazineCartridgeInfo()
GetInternalMagazineCartridgeInfo (int muzzleIndex, int cartridgeIndex, out float ammoDamage, out string ammoTypeName) private
get info about the cartridge in the internal magazine of a muzzle
Parameters
[in] muzzleIndex
[in] cartridgeIndex has to be 0 <= cartridgeIndex < GetInternalMagazineCartridgeCount()
[out] ammoDamage damage of the ammo
[out] ammoTypeName type name of the ejected ammo
Returns
true if info retrieved
GetInternalMagazineMaxCartridgeCount()
proto native int GetInternalMagazineMaxCartridgeCount (int muzzleIndex) private
GetMagazine()
GetMagazine (int muzzleIndex) private
Parameters
[in] muzzleIndex
Returns
attached magazine
GetMagazineTypeCount()
GetMagazineTypeCount (int muzzleIndex) private
Parameters
[in]
return returns the number of magazines in 'magazines' in config
GetMapStateAnimation()
bool GetMapStateAnimation () inline private
GetMarkerArray()
array< ref MapMarker > GetMarkerArray () inline private
GetMaxMagazineTypeName()
GetMaxMagazineTypeName (int muzzleIndex) private
Parameters
[in]
return returns the typename of the magazine in 'magazines' in config with highest capacity
GetMeleeTargetType() [1/2]
override int GetMeleeTargetType () inline private
GetMeleeTargetType() [2/2]
override int GetMeleeTargetType () inline private
GetMuzzleCount()
GetMuzzleCount () private
Returns
number of muzzles
GetMuzzleModeCount()
proto native int GetMuzzleModeCount (int muzzleIndex) private
GetNearPlaneValue()
float GetNearPlaneValue () inline private
GetOpticsDOF()
ref array< float > GetOpticsDOF () inline private
GetOpticsPPBlur()
float GetOpticsPPBlur () inline private
GetOpticsPPLens()
ref array< float > GetOpticsPPLens () inline private
GetOpticsPPMask()
ref array< float > GetOpticsPPMask () inline private
GetRadius()
proto native float GetRadius () private
Returns current wheel radius.
GetRandomChamberableAmmoTypeName()
GetRandomChamberableAmmoTypeName (int muzzleIndex) private
Parameters
[in]
return returns the typename of a random ammo registered in 'chamberableFrom' in config
GetRandomMagazineTypeName()
GetRandomMagazineTypeName (int muzzleIndex) private
Parameters
[in]
return returns the typename of a random magazine in 'magazines' in config
GetReloadTime()
GetReloadTime (int muzzleIndex) private
defines time from one shot to another
Parameters
[in] muzzleIndex
Returns
reload time in seconds
GetSlotFromMuzzleIndex()
GetSlotFromMuzzleIndex (int muzzleIndex) private
conversion muzzleIndex -> slotId
Parameters
[in] muzzleIndex muzzle index
Returns
slotId on success, -1 otherwise
GetStepFOVCount()
GetStepFOVCount () private
returns number of configured steps
GetStepFOVIndex()
GetStepFOVIndex () private
returns index of currently used value in 'discretefov' config array
Returns
index of currently used value in 'discretefov' config array
GetStepZeroing() [1/2]
GetStepZeroing () private
returns position of currently used value in zeroing config array
Returns
position of currently used value in zeroing config array
GetStepZeroing() [2/2]
proto native int GetStepZeroing (int muzzleIndex = 0) private
GetStepZoom()
GetStepZoom () private
returns position of currently used value in zoom config array
Returns
position of currently used value in zoom config array
GetTotalCartridgeCount()
GetTotalCartridgeCount (int muzzleIndex) private
Returns
returns number of available cartridges in chamber + internal magazine
GetTotalMaxCartridgeCount()
GetTotalMaxCartridgeCount (int muzzleIndex) private
Returns
returns number of max cartridges in chamber + internal magazine
GetTunedFrequency()
proto native float GetTunedFrequency () private
GetTunedFrequencyIndex()
proto native int GetTunedFrequencyIndex () private
GetWidth()
proto native float GetWidth () private
Returns wheel width.
GetZeroingClamp()
GetZeroingClamp (int muzzleIndex = 0) private
returns maximum allowed discrete distance for the muzzle. Limits attached optics zeroing only! '0' if unclamped
Returns
maximum allowed discrete distance for the muzzle
GetZeroingDistanceZoomMax() [1/2]
GetZeroingDistanceZoomMax () private
Gets Zeroing distance at opticsZoomMax.
GetZeroingDistanceZoomMax() [2/2]
proto native float GetZeroingDistanceZoomMax (int muzzleIndex) private
GetZeroingDistanceZoomMin() [1/2]
GetZeroingDistanceZoomMin () private
Gets Zeroing distance at opticsZoomMin.
GetZeroingDistanceZoomMin() [2/2]
proto native float GetZeroingDistanceZoomMin (int muzzleIndex) private
GetZoom()
GetZoom () private
returns current percentage of zoom
Returns
current percentage of zoom
GetZoomInit() [1/2]
GetZoomInit () private
gets FOV value, when entering optics
GetZoomInit() [2/2]
proto native float GetZoomInit (int muzzleIndex) private
GetZoomMax() [1/2]
GetZoomMax () private
gets FOV maximum
GetZoomMax() [2/2]
proto native float GetZoomMax (int muzzleIndex) private
GetZoomMin() [1/2]
GetZoomMin () private
gets FOV minimum
GetZoomMin() [2/2]
proto native float GetZoomMin (int muzzleIndex) private
HasFlammableMaterial()
override bool HasFlammableMaterial () inline private
HasInternalMagazine()
HasInternalMagazine (int muzzleIndex) private
Note
passing in -1 will check all muzzles
Returns
true if weapon has an internal magazine
HasWeaponIronsightsOverride()
HasWeaponIronsightsOverride () private
is weapon in optics mode or not
Returns
true if optics has defined override optics info for weapon
Init2DPreloadType()
void Init2DPreloadType () inline private
References CGame::ConfigGetText(), GetGame(), GetType(), and path.
InitCameraOverrideProperties()
void InitCameraOverrideProperties () inline private
References DayZPlayerCameraOptics(), GetGame(), GetType(), Math::Max(), and path.
InitDOFAvailability()
bool InitDOFAvailability () inline private
optics with more than 1x zoom do not allow DOF changes
References CGame::ConfigGetFloat(), GameConstants::DZPLAYER_CAMERA_FOV_IRONSIGHTS, GetGame(), GetType(), and path.
InitMapState()
void InitMapState () inline private
References CGame::ConfigGetText(), GetGame(), CGame::GetWorldName(), m_Description, and path.
InitOpticMode()
void InitOpticMode () inline private
References GameConstants::OPTICS_STATE_DAY.
InitOpticsDOFProperties()
bool InitOpticsDOFProperties (out array< float > temp_array) inline private
Initializes DOF properties for optic's alternate ironsights (ACOG etc.)
References CGame::ConfigGetFloatArray(), GetGame(), and GetType().
InitOpticsPP()
void InitOpticsPP (out array< float > mask_array, out array< float > lens_array, out float blur_float) inline private
initializes values for optics' post-processes
References CGame::ConfigGetFloat(), CGame::ConfigGetFloatArray(), GetGame(), GetType(), and path.
InitOpticsPPInfo()
void InitOpticsPPInfo () inline private
InitReddotData()
void InitReddotData () inline private
References CGame::ConfigGetText(), GetGame(), GetType(), and path.
InsertMarker()
void InsertMarker (vector pos, string text, int color, int idx) inline private
IsActivated()
IsActivated () private
Returns
true if grenade is GR_TRIGGERED or GR_EXPLODED
IsBroadcasting()
proto native bool IsBroadcasting () private
IsChamberEjectable()
IsChamberEjectable (int muzzleIndex) private
detects presence of ejectable cartridge in muzzle's chamber
Returns
true if eject-able
IsChamberEmpty()
IsChamberEmpty (int muzzleIndex) private
detects empty chamber
Returns
true if no cartridge in chamber
IsChamberFiredOut()
IsChamberFiredOut (int muzzleIndex) private
detects presence of fired out casing in chamber
Returns
true if casing in chamber
IsChamberFull()
IsChamberFull (int muzzleIndex) private
maximum number of cartridges in chamber
Returns
true if full
IsChamberFullEx()
bool IsChamberFullEx (int muzzleIndex) inline private
References IsChamberFull().
IsChamberJammed()
IsChamberJammed (int muzzleIndex) private
detects presence of damaged cartridge in chamber
Returns
true if jammed
IsFlashlightOn()
IsFlashlightOn () private
query state of flashlight
Returns
true if set on
IsInOptics() [1/2]
IsInOptics () private
is weapon in optics mode or not
Returns
true if in optics mode, false otherwise
IsInOptics() [2/2]
proto native bool IsInOptics () private
IsInternalMagazineFull()
IsInternalMagazineFull (int muzzleIndex) inline private
maximum number of cartridges in internal magazine
Returns
true if full
IsNVOptic()
bool IsNVOptic () inline private
IsPinned()
IsPinned () private
Returns
true if grenade is pinned
IsReceiving()
proto native bool IsReceiving () private
IsThisIgnitionSuccessful()
override bool IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
IsTurnedOn()
bool IsTurnedOn () inline private
Referenced by OnInventoryEnter(), and OnWasAttached().
IsUsingWeaponIronsightsOverride()
IsUsingWeaponIronsightsOverride () private
is optics using ironsights override settings or not
Returns
true if optics is using ironsights override settings
IsWeapon()
override bool IsWeapon () inline private
IsWorking()
bool IsWorking () inline private
ItemMap()
void ItemMap () inline private
ItemOptics()
void ItemOptics () inline private
NameOverride()
override bool NameOverride (out string output) inline private
OnIgnitedTarget()
override void OnIgnitedTarget (EntityAI ignited_item) inline private
OnIgnitedThis()
override void OnIgnitedThis (EntityAI fire_source) inline private
OnInventoryEnter() [1/2]
override void OnInventoryEnter (Man player) inline private
References IsTurnedOn().
OnInventoryEnter() [2/2]
override void OnInventoryEnter (Man player) inline private
OnInventoryExit() [1/3]
override void OnInventoryExit (Man player) inline private
OnInventoryExit() [2/3]
override void OnInventoryExit (Man player) inline private
OnInventoryExit() [3/3]
override void OnInventoryExit (Man player) inline private
References SetTakeable().
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
OnOpticEnter()
void OnOpticEnter () inline private
References GetGame(), and ItemOptics::HideSelection().
OnOpticExit()
void OnOpticExit () inline private
References GetGame(), and ItemOptics::ShowSelection().
OnOpticModeChange()
void OnOpticModeChange () inline private
optic-specific behaviour to be defined here (override)
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
References Serializer::Read().
OnStoreLoad() [1/2]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References Serializer::Read().
OnStoreLoad() [2/2]
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References m_IsStoreLoad, and Serializer::Read().
OnStoreSave() [1/2]
override void OnStoreSave (ParamsWriteContext ctx) inline private
References Serializer::Write().
OnStoreSave() [2/2]
override void OnStoreSave (ParamsWriteContext ctx) inline private
References Serializer::Write().
OnUseFromInventory()
override event bool OnUseFromInventory (Man owner) inline private
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
OnWasAttached() [1/4]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
References IsTurnedOn().
OnWasAttached() [2/4]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
OnWasAttached() [3/4]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
OnWasAttached() [4/4]
override void OnWasAttached (EntityAI parent, int slot_id) inline private
References Class::CastTo(), and SetTakeable().
OnWasDetached() [1/4]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
OnWasDetached() [2/4]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
OnWasDetached() [3/4]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
OnWasDetached() [4/4]
override void OnWasDetached (EntityAI parent, int slot_id) inline private
References Class::CastTo(), and SetTakeable().
OnWorkStart()
override void OnWorkStart () inline private
References GetGame().
OnWorkStop()
override void OnWorkStop () inline private
References GetGame().
PopCartridgeFromChamber()
PopCartridgeFromChamber (int muzzleIndex, out float ammoDamage, out string ammoTypeName) private
removes cartridge from chamber
PopCartridgeFromInternalMagazine()
PopCartridgeFromInternalMagazine (int muzzleIndex, out float ammoDamage, out string ammoTypeName) private
removes top-most cartridge from internal magazine
PushCartridgeToChamber()
PushCartridgeToChamber (int muzzleIndex, float ammoDamage, string ammoTypeName) private
push cartridge to chamber
PushCartridgeToInternalMagazine()
PushCartridgeToInternalMagazine (int muzzleIndex, float ammoDamage, string ammoTypeName) private
push cartridge into internal magazine
SelectionBulletHide()
proto native void SelectionBulletHide () private
SelectionBulletShow()
proto native void SelectionBulletShow () private
SelectionMagazineHide()
proto native void SelectionMagazineHide () private
SelectionMagazineShow()
proto native void SelectionMagazineShow () private
SetActions() [1/5]
override void SetActions () inline private
References ActionDetach(), and AddAction().
SetActions() [2/5]
override void SetActions () inline private
References ActionDetach(), and AddAction().
SetActions() [3/5]
override void SetActions () inline private
References ActionDetach(), and AddAction().
SetActions() [4/5]
override void SetActions () inline private
References AddAction().
SetActions() [5/5]
override void SetActions () inline private
References AddAction().
SetCanSpeak()
proto native void SetCanSpeak (bool onOff) private
SetCurrentMode()
proto native void SetCurrentMode (int muzzleIndex, int mode) private
SetCurrentMuzzle()
SetCurrentMuzzle (int muzzleIndex) private
sets index of active muzzle
Parameters
[in] muzzleIndex
SetCurrentOpticMode()
void SetCurrentOpticMode (int mode) inline private
SetFrequencyByIndex()
proto native void SetFrequencyByIndex (int index) private
SetGroundAnimFrameIndex()
SetGroundAnimFrameIndex (int groundAnimFrameIndex) private
sets animation frame for ground state when animation is specified in config
SetIgnited()
SetIgnited () private
sets grenade to state GR_TRIGGERED (if the state transition is possible)
Returns
true if state already set or if state transition performed, false otherwise
SetMapStateOpen()
void SetMapStateOpen (bool state, PlayerBase player) inline private
displays open/closed selections; 1 == opened
SetMuzzleMode()
proto native void SetMuzzleMode (int muzzleIndex, int modeIndex) private
SetNextChannel()
proto native void SetNextChannel () private
SetNextMuzzleMode()
proto native void SetNextMuzzleMode (int muzzleIndex) private
SetPinned()
SetPinned () private
sets grenade to state GR_PINNED (if the state transition is possible)
Returns
true if state already set or if state transition performed, false otherwise
SetPrevChannel()
proto native void SetPrevChannel () private
SetStepFOVIndex()
SetStepFOVIndex (int step) private
sets zoom to fov value defined at given in 'discretefov' config array
Parameters
[in] index of configured step, range [0..cfg_max]
Returns
true if zoom set
SetStepZeroing() [1/2]
proto native bool SetStepZeroing (int muzzleIndex, int step) private
SetStepZeroing() [2/2]
proto native bool SetStepZeroing (int step) private
SetStepZoom()
SetStepZoom (int step) private
sets zoom to fov value defined at given position in zoom fov config array
Parameters
[in] index of configured step, range [0..cfg_max]
Returns
true if zoom set
SetUnpinned()
SetUnpinned () private
sets grenade to state GR_UNPINNED (if the state transition is possible)
Returns
true if state already set or if state transition performed, false otherwise
SetZeroingClampDist()
SetZeroingClampDist (float dist) private
Sets zeroing clamp for the optics and updates the clamp if dist > 0. Used when attached to weapon.
SetZoom()
SetZoom (float percent) private
sets current zoom (in %)
Parameters
[in] percent zoom to set in range [0.0f .. 100.0f]
Returns
true if zoom set
ShowReddot()
void ShowReddot (bool state) inline private
References ErrorEx, and GetGame().
ShowZonesHealth() [1/3]
override bool ShowZonesHealth () inline private
ShowZonesHealth() [2/3]
override bool ShowZonesHealth () inline private
ShowZonesHealth() [3/3]
override bool ShowZonesHealth () inline private
StepFOVDown()
StepFOVDown () private
sets zoom to previous (respective to current) defined value in zoom fov config array
Returns
true if zoom set
StepFOVUp()
StepFOVUp () private
sets zoom to next defined (respective to current) value in zoom fov config array
Returns
true if zoom set
StepZeroingDown() [1/2]
StepZeroingDown () private
sets zeroing to previous (respective to current) defined value in zeroing config array
Returns
true if zeroing set
StepZeroingDown() [2/2]
proto native bool StepZeroingDown (int muzzleIndex = 0) private
StepZeroingDownAllMuzzles()
void StepZeroingDownAllMuzzles () inline private
StepZeroingUp() [1/2]
StepZeroingUp () private
sets zeroing to next defined (respective to current) value in zeroing config array
Returns
true if zeroing set
StepZeroingUp() [2/2]
proto native bool StepZeroingUp (int muzzleIndex = 0) private
StepZeroingUpAllMuzzles()
void StepZeroingUpAllMuzzles () inline private
StepZoomIn()
StepZoomIn () private
sets zoom to next defined (respective to current) value in zoom fov config array
Returns
true if zoom set
StepZoomOut()
StepZoomOut () private
sets zoom to previous (respective to current) defined value in zoom fov config array
Returns
true if zoom set
Synchronize()
Synchronize () private
Force synchronizes the weapon state from Server to Client. Use with caution.
SyncMapMarkers()
void SyncMapMarkers () inline private
References GetGame(), and CGame::IsServer().
TestAttachMagazine()
TestAttachMagazine (int muzzleIndex, Magazine mag, bool do_occupancy_test, bool do_script_check) private
query if a magazine can be attached to weapon
Parameters
[in] muzzleIndex
[in] mag magazine to attach
[in] do_occupancy_test if false, skips test for presence of another magazine in weapon
[in] do_script_check if false, skips script conditions
Returns
true if magazine can be attached
UpdateOpticsReddotVisibility()
void UpdateOpticsReddotVisibility () inline private
UpdateSelectionVisibility()
void UpdateSelectionVisibility () inline private
UseWeaponIronsightsOverride()
UseWeaponIronsightsOverride (bool state) private
switches into ironsights override settings
Returns
true if switching was successful
ZoomIn()
ZoomIn () private
moves current zoom by 1% up
Returns
true if zoom set
ZoomOut()
ZoomOut () private
moves current zoom by 1% down
Returns
true if zoom set
Field Documentation
m_2D_preload_type
string m_2D_preload_type private
m_allowsDOF
bool m_allowsDOF private
m_AttachSound
protected string m_AttachSound = "Offroad_Wheel_Attach_SoundSet" private
m_blur_float
float m_blur_float private
m_CurrentOpticMode
int m_CurrentOpticMode private
m_CurrentOpticModeLocal
int m_CurrentOpticModeLocal private
m_data_set
bool m_data_set private
m_Description
string m_Description private
m_DetachSound
protected string m_DetachSound = "Offroad_Wheel_Remove_SoundSet" private
m_DisplayName
string m_DisplayName private
m_isNVOptic
bool m_reddot_displayed bool m_isNVOptic = false private
m_lens_array
ref array<float> m_lens_array private
m_MapMarkerArray
protected ref array<ref MapMarker> m_MapMarkerArray private
m_mask_array
ref array<float> m_mask_array private
m_nearplane_override
float m_nearplane_override private
m_optic_sight_material
string m_optic_sight_material private
m_optic_sight_texture
string m_optic_sight_texture private
m_OpticsDOFProperties
ref array<float> m_OpticsDOFProperties private
m_reddot_index
int m_reddot_index private
m_TextureClosed
string m_TextureClosed private
m_TextureLegend
string m_TextureLegend private
m_TextureOpened
string m_TextureOpened private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Core/Inherited/InventoryItem.c
P:/scripts/4_World/Entities/Core/Inherited/ItemOptics.c
P:/scripts/4_World/Entities/Core/Inherited/Weapon.c
P:/scripts/4_World/Entities/ItemBase/ItemBook.c