DayZ Scripts: SmokeGrenadeBase Class Reference
SmokeGrenadeBase Class Reference
Private Member Functions
void M18SmokeGrenade_ColorBase ()
void ~M18SmokeGrenade_ColorBase ()
void RDG2SmokeGrenade_ColorBase ()
void ~RDG2SmokeGrenade_ColorBase ()
Private Attributes
const string SOUND_SMOKE_START = "SmokegGrenades_M18_start_loop_SoundSet"
const string SOUND_SMOKE_LOOP = "SmokegGrenades_M18_active_loop_SoundSet"
const string SOUND_SMOKE_END = "SmokegGrenades_M18_end_loop_SoundSet"
Detailed Description
Definition at line 1 of file M18SmokeGrenade_ColorBase.c.
Constructor & Destructor Documentation
~M18SmokeGrenade_ColorBase()
void ~M18SmokeGrenade_ColorBase () inline private
Definition at line 16 of file M18SmokeGrenade_ColorBase.c.
~RDG2SmokeGrenade_ColorBase()
void ~RDG2SmokeGrenade_ColorBase () inline private
Definition at line 17 of file RDG2SmokeGrenade_ColorBase.c.
Member Function Documentation
M18SmokeGrenade_ColorBase()
void M18SmokeGrenade_ColorBase () inline private
Definition at line 7 of file M18SmokeGrenade_ColorBase.c.
References SetAmmoType(), SetSoundSmokeEnd(), SetSoundSmokeLoop(), SetSoundSmokeStart(), SOUND_SMOKE_END, SOUND_SMOKE_LOOP, and SOUND_SMOKE_START.
RDG2SmokeGrenade_ColorBase()
void RDG2SmokeGrenade_ColorBase () inline private
Definition at line 7 of file RDG2SmokeGrenade_ColorBase.c.
References SetAmmoType(), SetParticlePosition(), SetSoundSmokeEnd(), SetSoundSmokeLoop(), SetSoundSmokeStart(), SOUND_SMOKE_END, SOUND_SMOKE_LOOP, and SOUND_SMOKE_START.
Field Documentation
SOUND_SMOKE_END
const string SOUND_SMOKE_END = "SmokegGrenades_M18_end_loop_SoundSet" private
Definition at line 5 of file M18SmokeGrenade_ColorBase.c.
SOUND_SMOKE_LOOP
const string SOUND_SMOKE_LOOP = "SmokegGrenades_M18_active_loop_SoundSet" private
Definition at line 4 of file M18SmokeGrenade_ColorBase.c.
SOUND_SMOKE_START
const string SOUND_SMOKE_START = "SmokegGrenades_M18_start_loop_SoundSet" private
Definition at line 3 of file M18SmokeGrenade_ColorBase.c.
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Grenade_Base/M18SmokeGrenade_ColorBase.c
P:/scripts/4_World/Entities/Grenade_Base/RDG2SmokeGrenade_ColorBase.c