DayZ Scripts: P:/scripts/3_Game/Hive/Hive.c File Reference
Hive.c File Reference
Data Structures
class Hive
Functions
proto native Hive CreateHive ()
proto native void DestroyHive ()
proto native Hive GetHive ()
Function Documentation
CreateHive()
proto native Hive CreateHive ()
DestroyHive()
proto native void DestroyHive ()
GetHive()
proto native Hive GetHive ()
Referenced by ManBase::EEKilled(), MissionBase::OnClientDisconnectedEvent(), MissionBase::OnClientPrepareEvent(), ManBase::OnStoreLoad(), MissionBase::PlayerDisconnected(), and ManBase::Save().