DayZ Scripts: DayZPlayerTypeStepSoundLookupTable Class Reference
DayZPlayerTypeStepSoundLookupTable Class Reference
Private Member Functions
SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
void DayZPlayerTypeStepSoundLookupTableImpl ()
override SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
Static Private Member Functions
static DayZPlayerTypeStepSoundLookupTableImpl GetInstance ()
Private Attributes
private autoptr map< int, ref StepSoundLookupTable > m_pSoundTableInstances
private autoptr map< int, StepSoundLookupTable > m_pSoundTables
Static Private Attributes
static private ref DayZPlayerTypeStepSoundLookupTableImpl m_instance
Member Function Documentation
DayZPlayerTypeStepSoundLookupTableImpl()
void DayZPlayerTypeStepSoundLookupTableImpl () inline private
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), CGame::ConfigGetText(), GetGame(), string::Hash(), m_pSoundTableInstances, m_pSoundTables, and StepSoundLookupTable().
Referenced by GetInstance().
GetInstance()
static DayZPlayerTypeStepSoundLookupTableImpl GetInstance () inline static private
References DayZPlayerTypeStepSoundLookupTableImpl(), m_instance, and m_instance.
Referenced by DayZPlayerTypeRegisterSounds().
GetSoundBuilder() [1/2]
SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots) inline private
Referenced by DayZPlayer::OnStepEvent().
GetSoundBuilder() [2/2]
override SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots) inline private
References SoundObjectBuilder::AddVariable(), SoundLookupTable::GetSoundBuilder(), and m_pSoundTables.
Field Documentation
m_instance
private ref DayZPlayerTypeStepSoundLookupTableImpl m_instance static private
Referenced by GetInstance().
m_pSoundTableInstances
private autoptr map<int, ref StepSoundLookupTable> m_pSoundTableInstances private
m_pSoundTables
private autoptr map<int, StepSoundLookupTable> m_pSoundTables private
The documentation for this class was generated from the following files:
P:/scripts/3_Game/dayzplayer.c
P:/scripts/4_World/Entities/ManBase/DayZPlayer/DayZPlayerCfgSounds.c