DayZ Scripts: ConstructionBoxTrigger Class Reference
ConstructionBoxTrigger Class Reference
Private Member Functions
void SetPartName (string part_name)
string GetPartName ()
override protected void UpdateInsiders (int timeout)
bool IsColliding ()
Private Attributes
string m_PartName
Detailed Description
Definition at line 1319 of file Construction.c.
Member Function Documentation
GetPartName()
string GetPartName () inline private
Definition at line 1328 of file Construction.c.
References m_PartName.
Referenced by CreateCollisionTrigger().
IsColliding()
bool IsColliding () inline private
Definition at line 1338 of file Construction.c.
References Count, and Trigger::GetInsiders().
Referenced by IsTriggerColliding().
SetPartName()
void SetPartName (string part_name) inline private
Definition at line 1323 of file Construction.c.
References m_PartName.
Referenced by CreateCollisionTrigger().
UpdateInsiders()
override protected void UpdateInsiders (int timeout) inline private
Definition at line 1333 of file Construction.c.
Field Documentation
m_PartName
string m_PartName private
Definition at line 1321 of file Construction.c.
Referenced by GetPartName(), and SetPartName().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/BaseBuilding/Construction.c