DayZ Scripts: House Class Reference
House Class Reference
Private Member Functions
override void EEOnCECreate ()
void RequestSoundEvent ()
string GetSoundSet ()
override void EEInit ()
override void EEDelete (EntityAI parent)
void House ()
void ChristmasTree ()
override void EEInit ()
override void EEDelete (EntityAI parent)
Static Private Member Functions
static bool Init ()
Private Attributes
Particle m_ParticleEfx
XmasTreeLight m_TreeLight
EffectSound m_AmbientSoundLoop
const string LOOP_SOUND = "ChristmasMusic_SoundSet"
Static Private Attributes
static bool m_Init = Init()
Constructor & Destructor Documentation
House()
void House () inline private
Member Function Documentation
ChristmasTree()
void ChristmasTree () inline private
References GetGame().
EEDelete() [1/2]
override void EEDelete (EntityAI parent) inline private
References GetGame(), and Particle::Stop().
EEDelete() [2/2]
override void EEDelete (EntityAI parent) inline private
References SEffectManager::DestroyEffect(), and GetGame().
EEInit() [1/2]
override void EEInit () inline private
References GetGame(), GetPosition, CrashBase::GetSoundSet(), SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
EEInit() [2/2]
override void EEInit () inline private
References GetGame().
EEOnCECreate()
override void EEOnCECreate () inline private
GetSoundSet()
string GetSoundSet () inline private
Init()
static bool Init () inline static private
References CrashSoundSets::RegisterSoundSet().
RequestSoundEvent()
void RequestSoundEvent () inline private
References GetGame(), GetPosition, CrashBase::GetSoundSet(), and CGame::RPCSingleParam().
Field Documentation
LOOP_SOUND
const string LOOP_SOUND = "ChristmasMusic_SoundSet" private
m_AmbientSoundLoop
EffectSound m_AmbientSoundLoop private
m_Init
bool m_Init = Init() static private
m_ParticleEfx
Particle m_ParticleEfx private
m_TreeLight
XmasTreeLight m_TreeLight private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/Building/CrashBase.c
P:/scripts/4_World/Entities/WoodBase/ChristmasTree.c
P:/scripts/4_World/Entities/Game/Super/Building.c