DayZ Scripts: EnochData Class Reference
EnochData Class Reference
Private Member Functions
override void Init ()
override void InitYieldBank ()
override void SetupWeatherSettings ()
override void SetupLiquidTemperatures ()
override bool WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time)
protected override void CalculateWind (int newWeather, bool suddenChange, out float magnitude, out float direction)
protected override void CalculateVolFog (float lerpValue, float windMagnitude, float changeTime)
bool LogWeatherData ()
Private Attributes
const int CLEAR_WEATHER = 1
DEPRECATED (see WorldDataWeatherConstants)
const int CLOUDY_WEATHER = 2
const int BAD_WEATHER = 3
const int OVERCAST_MIN_TIME = 600
DEPRECATED (see WorldDataWeatherSettings)
const int OVERCAST_MAX_TIME = 900
const float RAIN_THRESHOLD = 0.6
const int RAIN_TIME_MIN = 60
const int RAIN_TIME_MAX = 120
const float STORM_THRESHOLD = 0.85
protected int m_clearWeatherChance = m_ClearWeatherChance
protected int m_badWeatherChance = m_BadWeatherChance
protected int m_sameWeatherCnt = m_SameWeatherCnt
protected int m_stepValue = m_StepValue
protected int m_chance = m_Chance
protected int m_choosenWeather = m_ChoosenWeather
protected int m_lastWeather = m_LastWeather
Static Private Attributes
static protected const ref array< vector > LIVONIA_ARTY_STRIKE_POS
Member Function Documentation
CalculateVolFog()
protected override void CalculateVolFog (float lerpValue, float windMagnitude, float changeTime) inline private
References Math::Clamp(), World::GetDate(), Weather::GetDynVolFogHeightBias(), GetGame(), Weather::GetWindMaximumSpeed(), CGame::GetWorld(), Math::Lerp(), WorldDataWeatherSettings::m_DefaultHeigthBias, WorldDataWeatherSettings::m_FoggyMorningHeigthBiasLowLimit, WorldData::m_Weather, WorldData::m_WeatherDefaultSettings, Math::RandomInt(), Math::RandomIntInclusive(), Weather::SetDynVolFogDistanceDensity(), Weather::SetDynVolFogHeightBias(), and Weather::SetDynVolFogHeightDensity().
Referenced by Init(), and WeatherOnBeforeChange().
CalculateWind()
protected override void CalculateWind (int newWeather, bool suddenChange, out float magnitude, out float direction) inline private
References WeatherPhenomenon::GetActual(), WeatherPhenomenon::GetForecast(), Weather::GetOvercast(), WorldDataWeatherSettings::m_StormThreshold, WorldData::m_Weather, WorldData::m_WeatherDefaultSettings, Math::RandomFloatInclusive(), and Math::RandomIntInclusive().
Referenced by WeatherOnBeforeChange().
Init()
override void Init () inline private
References CalculateVolFog(), Count, CfgGameplayHandler::GetEnvironmentMaxTemps(), CfgGameplayHandler::GetEnvironmentMinTemps(), GetGame(), Weather::GetOvercast(), Weather::GetWindSpeed(), LIVONIA_ARTY_STRIKE_POS, WorldData::m_CloudsTemperatureEffectModifier, WorldDataWeatherSettings::m_DefaultHeigthBias, WorldData::m_FiringPos, WorldData::m_MaxTemps, WorldData::m_MinTemps, WorldData::m_Sunrise_Jan, WorldData::m_Sunrise_Jul, WorldData::m_Sunset_Jan, WorldData::m_Sunset_Jul, WorldData::m_TemperaturePerHeightReductionModifier, WorldData::m_UniversalTemperatureSourceCapModifier, WorldData::m_Weather, WorldData::m_WeatherDefaultSettings, WorldData::m_WorldWindCoef, Math::RandomFloat(), WeatherPhenomenon::Set(), and Weather::SetDynVolFogHeightBias().
InitYieldBank()
override void InitYieldBank () inline private
References CatchYieldBank::ClearAllRegisteredItems(), WorldData::m_YieldBank, and CatchYieldBank::RegisterYieldItem().
LogWeatherData()
bool LogWeatherData () inline private
SetupLiquidTemperatures()
override void SetupLiquidTemperatures () inline private
References LIQUID_CLEANWATER, LIQUID_FRESHWATER, LIQUID_RIVERWATER, LIQUID_SALTWATER, LIQUID_STILLWATER, LIQUID_WATER, and WorldData::m_LiquidSettings.
SetupWeatherSettings()
override void SetupWeatherSettings () inline private
References WorldDataWeatherSettings::m_BadWeatherChance, WorldDataWeatherSettings::m_BadWeatherSuddenChance, WorldDataWeatherSettings::m_ClearWeatherChance, and WorldData::m_WeatherDefaultSettings.
WeatherOnBeforeChange()
override bool WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time) inline private
References CalculateVolFog(), CalculateWind(), CloseFile(), FPrintln(), g_Game, WeatherPhenomenon::GetActual(), World::GetDate(), Weather::GetFog(), WeatherPhenomenon::GetForecast(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), Weather::GetWindDirection(), Weather::GetWindMagnitude(), CGame::GetWorld(), IDC_MAIN_QUIT, WorldData::m_BadWeatherChance, WorldDataWeatherSettings::m_BadWeatherChance, WorldDataWeatherSettings::m_CalmAfterStormTimeMax, WorldDataWeatherSettings::m_CalmAfterStormTimeMin, WorldData::m_Chance, WorldData::m_ChoosenWeather, WorldData::m_ClearWeatherChance, WorldDataWeatherSettings::m_ClearWeatherChance, WorldDataWeatherSettings::m_GlobalSuddenChance, WorldData::m_IsSuddenChange, WorldData::m_LastWeather, WorldDataWeatherSettings::m_OvercastMaxLength, WorldDataWeatherSettings::m_OvercastMaxTime, WorldDataWeatherSettings::m_OvercastMinLength, WorldDataWeatherSettings::m_OvercastMinTime, WorldDataWeatherSettings::m_RainLengthMax, WorldDataWeatherSettings::m_RainLengthMin, WorldDataWeatherSettings::m_RainThreshold, WorldDataWeatherSettings::m_RainTimeMax, WorldDataWeatherSettings::m_RainTimeMin, WorldData::m_SameWeatherCnt, WorldData::m_StepValue, WorldDataWeatherSettings::m_StormThreshold, WorldData::m_Weather, WorldData::m_WeatherDefaultSettings, OpenFile(), Math::RandomFloatInclusive(), Math::RandomInt(), Math::RandomIntInclusive(), WeatherPhenomenon::Set(), Weather::SetRainThresholds(), Weather::SetStorm(), Weather::SetWindMaximumSpeed(), WorldData::SUDDENCHANGE_LENGTH_MULTIPLIER, WorldData::SUDDENCHANGE_TIME_MULTIPLIER, Debug::WeatherLog(), WorldData::WIND_DIRECTION_TIME_MULTIPLIER, and WorldData::WIND_MAGNITUDE_TIME_MULTIPLIER.
Field Documentation
BAD_WEATHER
const int BAD_WEATHER = 3 private
CLEAR_WEATHER
const int CLEAR_WEATHER = 1 private
DEPRECATED (see WorldDataWeatherConstants)
CLOUDY_WEATHER
const int CLOUDY_WEATHER = 2 private
LIVONIA_ARTY_STRIKE_POS
protected const ref array<vector> LIVONIA_ARTY_STRIKE_POS static private
Initial value:
=
    {
        "7440.00 417.00 -500.00",
        "-500.00 276.00 5473.00",
        "-500.00 265.00 9852.00",
        "4953.00 240.00 13300.00",
        "9620.00 188.00 13300.00",
        "13300.00 204.00 10322.00",
        "13300.00 288.00 6204.00",
        "13300.00 296.00 -500.00"
    }
Referenced by Init().
m_badWeatherChance
protected int m_badWeatherChance = m_BadWeatherChance private
m_chance
protected int m_chance = m_Chance private
m_choosenWeather
protected int m_choosenWeather = m_ChoosenWeather private
m_clearWeatherChance
protected int m_clearWeatherChance = m_ClearWeatherChance private
m_lastWeather
protected int m_lastWeather = m_LastWeather private
m_sameWeatherCnt
protected int m_sameWeatherCnt = m_SameWeatherCnt private
m_stepValue
protected int m_stepValue = m_StepValue private
OVERCAST_MAX_TIME
const int OVERCAST_MAX_TIME = 900 private
OVERCAST_MIN_TIME
const int OVERCAST_MIN_TIME = 600 private
DEPRECATED (see WorldDataWeatherSettings)
RAIN_THRESHOLD
const float RAIN_THRESHOLD = 0.6 private
RAIN_TIME_MAX
const int RAIN_TIME_MAX = 120 private
RAIN_TIME_MIN
const int RAIN_TIME_MIN = 60 private
STORM_THRESHOLD
const float STORM_THRESHOLD = 0.85 private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/Worlds/Enoch.c