DayZ Scripts: InventoryGridController Class Reference
InventoryGridController Class Reference
Private Member Functions
void InventoryQuickbar (Widget quickbarGridWidget)
void ~InventoryQuickbar ()
void UpdateItems (Widget quickbarGridWidget)
void Remove (InventoryItem itemToRemove)
override void OnItemEnter (InventoryGrid grid, Widget w, int row, int col)
override void OnItemLeave (InventoryGrid grid, Widget w)
override void OnItemDraggingOver (InventoryGrid grid, Widget w, int row, int col)
override void OnItemDropReceived (InventoryGrid grid, Widget w, int row, int col)
override void OnItemDrop (InventoryGrid grid, Widget w, int row, int col)
override void OnItemDrag (InventoryGrid grid, Widget w, int row, int col)
override int GetQuickbarItemColor (InventoryGrid grid, InventoryItem item)
override int HasItemQuantity (InventoryItem item)
override string GetItemQuantityText (InventoryItem item)
override float GetItemQuantity (InventoryItem item)
override int GetItemQuantityMax (InventoryItem item)
override int GetItemCount (InventoryItem item)
override bool CanAddItemInHandToInventory ()
Private Attributes
protected ref TItemsMap m_Items
protected InventoryGrid m_Grid
protected int m_DraggingIndex
Constructor & Destructor Documentation
~InventoryQuickbar()
void ~InventoryQuickbar () inline private
Member Function Documentation
CanAddItemInHandToInventory()
override bool CanAddItemInHandToInventory () inline private
References GetGame(), and GetPlayer().
Referenced by ScriptedWidgetEventHandler::UpdateQuickbarItems().
GetItemCount()
override int GetItemCount (InventoryItem item) inline private
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetItemQuantity()
override float GetItemQuantity (InventoryItem item) inline private
References QuantityConversions::GetItemQuantity().
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetItemQuantityMax()
override int GetItemQuantityMax (InventoryItem item) inline private
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetItemQuantityText()
override string GetItemQuantityText (InventoryItem item) inline private
References QuantityConversions::GetItemQuantityText().
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetQuickbarItemColor()
override int GetQuickbarItemColor (InventoryGrid grid, InventoryItem item) inline private
References GameInventory::CanSwapEntitiesEx(), GetGame(), and GetPlayer().
Referenced by ScriptedWidgetEventHandler::RefreshQuickbarItemVariables().
HasItemQuantity()
override int HasItemQuantity (InventoryItem item) inline private
References QuantityConversions::HasItemQuantity().
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
InventoryQuickbar()
void InventoryQuickbar (Widget quickbarGridWidget) inline private
References INDEX_NOT_FOUND, and UpdateItems().
OnItemDrag()
override void OnItemDrag (InventoryGrid grid, Widget w, int row, int col) inline private
References GetGame(), and GetPlayer().
Referenced by ScriptedWidgetEventHandler::OnDrag().
OnItemDraggingOver()
override void OnItemDraggingOver (InventoryGrid grid, Widget w, int row, int col) inline private
References ARGB(), ItemPreviewWidget::GetItem(), name, and string::Replace().
Referenced by ScriptedWidgetEventHandler::OnDraggingOver().
OnItemDrop()
override void OnItemDrop (InventoryGrid grid, Widget w, int row, int col) inline private
References GetGame(), ItemManager::GetInstance(), GetPlayer(), ItemManager::HideDropzones(), INDEX_NOT_FOUND, InventoryMenu(), MENU_INVENTORY, and Remove().
Referenced by ScriptedWidgetEventHandler::OnDrop().
OnItemDropReceived()
override void OnItemDropReceived (InventoryGrid grid, Widget w, int row, int col) inline private
References ItemManager::GetDraggedItem(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), INDEX_NOT_FOUND, InventoryMenu(), MENU_INVENTORY, name, and string::Replace().
Referenced by ScriptedWidgetEventHandler::OnDropReceived().
OnItemEnter()
override void OnItemEnter (InventoryGrid grid, Widget w, int row, int col) inline private
Referenced by ScriptedWidgetEventHandler::OnMouseEnter().
OnItemLeave()
override void OnItemLeave (InventoryGrid grid, Widget w) inline private
Referenced by ScriptedWidgetEventHandler::OnMouseLeave().
Remove()
void Remove (InventoryItem itemToRemove) inline private
References GetGame(), and GetPlayer().
Referenced by OnItemDrop().
UpdateItems()
void UpdateItems (Widget quickbarGridWidget) inline private
References Widget::Clear(), GetGame(), GetPlayer(), and Vector().
Referenced by InventoryQuickbar().
Field Documentation
m_DraggingIndex
protected int m_DraggingIndex private
m_Grid
protected InventoryGrid m_Grid private
m_Items
protected ref TItemsMap m_Items private
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/Inventory/InventoryQuickbar.c