DayZ Scripts: Tabber Class Reference
Tabber Class Reference
Private Member Functions
void OnWidgetScriptInit (Widget w)
override bool OnClick (Widget w, int x, int y, int button)
protected void SelectTab (int index)
Private Attributes
Widget ButtonsPanel
Widget ContentPanel
reference int SelectedTab
Detailed Description
Definition at line 2 of file Tabber.c.
Member Function Documentation
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
Definition at line 16 of file Tabber.c.
References ButtonsPanel, SelectedTab, and SelectTab().
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w) inline private
Definition at line 9 of file Tabber.c.
References SelectedTab, and SelectTab().
SelectTab()
protected void SelectTab (int index) inline private
Definition at line 36 of file Tabber.c.
References ContentPanel, and Print().
Referenced by OnClick(), and OnWidgetScriptInit().
Field Documentation
ButtonsPanel
Widget ButtonsPanel private
Definition at line 4 of file Tabber.c.
Referenced by OnClick().
ContentPanel
Widget ContentPanel private
Definition at line 5 of file Tabber.c.
Referenced by SelectTab().
SelectedTab
reference int SelectedTab private
Definition at line 6 of file Tabber.c.
Referenced by OnClick(), and OnWidgetScriptInit().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/GUI/Tabber.c