DayZ Scripts: P:/scripts/4_World/Entities/ScriptedEntities/Triggers/TrapTrigger.c File Reference
TrapTrigger.c File Reference
Data Structures
class TrapTrigger
Trigger used by traps.
Functions
TrapTrigger Trigger OnEnterServerEvent (TriggerInsider insider)
void TrapTrigger ()
void SetParentObject (TrapBase obj)
override protected bool CanAddObjectAsInsider (Object object)
override protected void OnLeaveServerEvent (TriggerInsider insider)
void SetEnabled ()
prevents insider adding in the wrong position, HOTFIX
Variables
bool m_Enabled = false
TrapBase m_ParentObj
Function Documentation
CanAddObjectAsInsider()
override protected bool CanAddObjectAsInsider (Object object)
OnEnterServerEvent()
TrapTrigger Trigger OnEnterServerEvent (TriggerInsider insider)
OnLeaveServerEvent()
override protected void OnLeaveServerEvent (TriggerInsider insider)
SetEnabled()
void SetEnabled ()
prevents insider adding in the wrong position, HOTFIX
Referenced by EntityLightSource::CheckIfParentIsInCargo(), EntityLightSource::Destroy(), SpotLightBase::PerformVisibilityCheck(), and EntityLightSource::ScriptedLightBase().
SetParentObject()
void SetParentObject (TrapBase obj)
TrapTrigger()
void TrapTrigger ()
Variable Documentation
m_Enabled
bool m_Enabled = false
Referenced by ScriptedWidgetEventHandler::Disable(), ScriptedWidgetEventHandler::Enable(), OptionSelectorBase::IsSelectorEnabled(), and OptionSelectorBase::OptionSelector().
m_ParentObj
TrapBase m_ParentObj
Referenced by Trigger::OnEnter(), Trigger::OnLeave(), and Trigger::SetParentObject().