DayZ Scripts: CAContinuousWaterSlot Class Reference
CAContinuousWaterSlot Class Reference
Private Member Functions
void CAContinuousWaterSlot (float quantity_used_per_second)
override void Setup (ActionData action_data)
override int Execute (ActionData action_data)
override float GetProgress ()
Private Attributes
protected float m_PlantThirstyness
protected float m_TimeToComplete
protected float m_SpentQuantityTotal
protected float m_StartQuantity
protected Slot m_Slot
Detailed Description
Definition at line 1 of file CAContinuousWaterSlot.c.
Constructor & Destructor Documentation
CAContinuousWaterSlot()
void CAContinuousWaterSlot (float quantity_used_per_second) inline private
Definition at line 9 of file CAContinuousWaterSlot.c.
References CAContinuousQuantity::m_QuantityUsedPerSecond.
Member Function Documentation
Execute()
override int Execute (ActionData action_data) inline private
Definition at line 59 of file CAContinuousWaterSlot.c.
References CalcAndSetQuantity(), Class::CastTo(), CABase::m_Action, CAContinuousQuantity::m_ItemMaxQuantity, CAContinuousQuantity::m_ItemQuantity, ActionData::m_MainItem, ActionData::m_Player, CAContinuousQuantity::m_QuantityUsedPerSecond, m_Slot, CAContinuousQuantity::m_SpentQuantity, m_SpentQuantityTotal, ActionData::m_Target, CAContinuousBase::OnCompletePogress(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float GetProgress () inline private
Definition at line 100 of file CAContinuousWaterSlot.c.
References CAContinuousQuantity::m_ItemQuantity, m_SpentQuantityTotal, and m_StartQuantity.
Setup()
override void Setup (ActionData action_data) inline private
Definition at line 14 of file CAContinuousWaterSlot.c.
References Class::CastTo(), CAContinuousQuantity::m_ItemQuantity, ActionData::m_MainItem, m_PlantThirstyness, CAContinuousQuantity::m_QuantityUsedPerSecond, m_Slot, CAContinuousQuantity::m_SpentQuantity, CAContinuousQuantity::m_SpentUnits, m_StartQuantity, ActionData::m_Target, m_TimeToComplete, and Math::Min().
Field Documentation
m_PlantThirstyness
protected float m_PlantThirstyness private
Definition at line 3 of file CAContinuousWaterSlot.c.
Referenced by Setup().
m_Slot
protected Slot m_Slot private
Definition at line 7 of file CAContinuousWaterSlot.c.
Referenced by Execute(), and Setup().
m_SpentQuantityTotal
protected float m_SpentQuantityTotal private
Definition at line 5 of file CAContinuousWaterSlot.c.
Referenced by Execute(), and GetProgress().
m_StartQuantity
protected float m_StartQuantity private
Definition at line 6 of file CAContinuousWaterSlot.c.
Referenced by GetProgress(), and Setup().
m_TimeToComplete
protected float m_TimeToComplete private
Definition at line 4 of file CAContinuousWaterSlot.c.
Referenced by Setup().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousWaterSlot.c