DayZ Scripts: Plastic_Explosive Class Reference
Plastic_Explosive Class Reference
Private Member Functions
void Plastic_Explosive ()
override void EOnInit (IEntity other, int extra)
override void EEKilled (Object killer)
special behaviour - do not call super from ExplosivesBase
override bool HasLockedTriggerSlots ()
override void LockTriggerSlots ()
override void UnlockTriggerSlots ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanDisplayAttachmentSlot (int slot_id)
override bool IsTakeable ()
override bool IsDeployable ()
override void SetActions ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override bool EEOnDamageCalculated (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
override void PairRemote (notnull EntityAI trigger)
override EntityAI GetPairDevice ()
override bool CanBeArmed ()
override bool CanBeDisarmed ()
override void OnActivatedByItem (notnull ItemBase item)
override void OnDisarmed (bool pWithTool)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void UpdateLED (int pState)
protected void OnTriggerAttached (EntityAI entity)
protected void OnTriggerDetached (EntityAI entity)
protected void UpdateVisuals (EntityAI entity)
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override protected bool UsesGlobalDeploy ()
Private Attributes
protected const string SLOT_TRIGGER = "TriggerRemoteDetonator_Receiver"
protected const string ANIM_PHASE_TRIGGER_REMOTE = "TriggerRemote"
protected bool m_UsedAsCharge
protected ref RemotelyActivatedItemBehaviour m_RAIB
Constructor & Destructor Documentation
Plastic_Explosive()
void Plastic_Explosive () inline private
References m_RAIB, ParticleList::PLASTIC_EXPLOSION, SetAmmoType(), and SetParticleExplosion().
Member Function Documentation
CanBeArmed()
override bool CanBeArmed () inline private
References GetArmed(), and HasLockedTriggerSlots().
CanBeDisarmed()
override bool CanBeDisarmed () inline private
References GetArmed().
CanDisplayAttachmentSlot()
override bool CanDisplayAttachmentSlot (int slot_id) inline private
References InventorySlots::GetSlotName(), SLOT_TRIGGER, and slotName.
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId) inline private
References ClockBase(), GetArmed(), and InventoryLocation::GetType().
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
References GetGame(), SetArmed(), SetTakeable(), and GameConstants::STATE_RUINED.
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name) inline private
References OnTriggerAttached(), and SLOT_TRIGGER.
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name) inline private
References OnTriggerDetached(), and SLOT_TRIGGER.
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
EEKilled()
override void EEKilled (Object killer) inline private
special behaviour - do not call super from ExplosivesBase
References CGame::GetAnalyticsServer(), GetGame(), and AnalyticsManagerServer::OnEntityKilled().
EEOnDamageCalculated()
override bool EEOnDamageCalculated (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
ignores explosion damage from other Plastic_Explosive that are used as charge(like 2 PE fired via IED)
References m_UsedAsCharge.
EOnInit()
override void EOnInit (IEntity other, int extra) inline private
References g_Game, and LockTriggerSlots().
GetDeploySoundset()
override string GetDeploySoundset () inline private
GetLoopDeploySoundset()
override string GetLoopDeploySoundset () inline private
GetPairDevice()
override EntityAI GetPairDevice () inline private
References RemotelyActivatedItemBehaviour::GetPairDevice(), and m_RAIB.
Referenced by OnActivatedByItem().
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour () inline private
References m_RAIB.
HasLockedTriggerSlots()
override bool HasLockedTriggerSlots () inline private
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGER.
Referenced by CanBeArmed().
IsDeployable()
override bool IsDeployable () inline private
References GetArmed().
IsTakeable()
override bool IsTakeable () inline private
References GetArmed().
LockTriggerSlots()
override void LockTriggerSlots () inline private
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGER.
Referenced by EOnInit(), OnDisarmed(), and OnStoreSave().
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item) inline private
References GetArmed(), GetGame(), GetPairDevice(), InitiateExplosion(), RemotelyActivatedItemBehaviour::IsPaired(), m_RAIB, and GameConstants::STATE_RUINED.
OnDisarmed()
override void OnDisarmed (bool pWithTool) inline private
References LockTriggerSlots(), SetTakeable(), UnpairRemote(), and UpdateVisuals().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGER.
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx) inline private
References LockTriggerSlots().
OnTriggerAttached()
protected void OnTriggerAttached (EntityAI entity) inline private
References Arm(), UpdateLED(), and UpdateVisuals().
Referenced by EEItemAttached().
OnTriggerDetached()
protected void OnTriggerDetached (EntityAI entity) inline private
References UpdateLED(), and UpdateVisuals().
Referenced by EEItemDetached().
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References InventorySlots::GetSlotIdFromString(), m_RAIB, RemotelyActivatedItemBehaviour::OnVariableSynchronized(), SLOT_TRIGGER, and UpdateVisuals().
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
References ExplosivesBase(), and m_UsedAsCharge.
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id) inline private
References ExplosivesBase(), and m_UsedAsCharge.
PairRemote()
override void PairRemote (notnull EntityAI trigger) inline private
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
SetActions()
override void SetActions () inline private
References ActionDeployObject(), and AddAction().
UnlockTriggerSlots()
override void UnlockTriggerSlots () inline private
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGER.
UpdateLED()
override void UpdateLED (int pState) inline private
References RemoteDetonatorReceiver(), and SLOT_TRIGGER.
Referenced by OnTriggerAttached(), and OnTriggerDetached().
UpdateVisuals()
protected void UpdateVisuals (EntityAI entity) inline private
References ANIM_PHASE_TRIGGER_REMOTE.
UsesGlobalDeploy()
override protected bool UsesGlobalDeploy () inline private
Field Documentation
ANIM_PHASE_TRIGGER_REMOTE
protected const string ANIM_PHASE_TRIGGER_REMOTE = "TriggerRemote" private
Referenced by UpdateVisuals().
m_RAIB
protected ref RemotelyActivatedItemBehaviour m_RAIB private
Referenced by EEItemLocationChanged(), GetPairDevice(), GetRemotelyActivatedItemBehaviour(), OnActivatedByItem(), OnVariablesSynchronized(), PairRemote(), and Plastic_Explosive().
m_UsedAsCharge
protected bool m_UsedAsCharge private
Referenced by EEOnDamageCalculated(), OnWasAttached(), and OnWasDetached().
SLOT_TRIGGER
protected const string SLOT_TRIGGER = "TriggerRemoteDetonator_Receiver" private
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), EEItemDetached(), HasLockedTriggerSlots(), LockTriggerSlots(), OnStoreLoad(), OnVariablesSynchronized(), UnlockTriggerSlots(), and UpdateLED().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ExplosivesBase/Plastic_Explosive.c