DayZ Scripts: MissionBase Class Reference
MissionBase Class Reference
Private Member Functions
void MissionGameplay ()
void ~MissionGameplay ()
InventoryMenu GetInventory ()
override void OnInit ()
UIManager GetUIManager ()
override void OnMissionStart ()
void InitInventory ()
void TickScheduler (float timeslice)
void SendMuteListToServer (map< string, bool > mute_list)
override void UpdateInputDevicesAvailability ()
override void OnMissionFinish ()
override void OnUpdate (float timeslice)
override void OnKeyPress (int key)
override void OnKeyRelease (int key)
override void OnEvent (EventType eventTypeId, Param params)
override void OnItemUsed (InventoryItem item, Man owner)
override void PlayerControlEnable (bool bForceSupress)
Deprecated; removes last input exclude and associated controls restrictions.
override void PlayerControlDisable (int mode)
Deprecated; simple input restrictions.
override void RemoveActiveInputExcludes (array< string > excludes, bool bForceSupress=false)
Removes one or more exclude groups and refreshes excludes.
override void RemoveActiveInputRestriction (int restrictor)
Removes one restriction (specific behaviour oudside regular excludes, defined below)
override void AddActiveInputExcludes (array< string > excludes)
Adds one or more exclude groups to disable and refreshes excludes.
override void AddActiveInputRestriction (int restrictor)
Adds one input restriction (specific behaviour oudside regular excludes, defined below)
override void RefreshExcludes ()
queues refresh of input excludes
protected void PerformRefreshExcludes ()
applies queued excludes (0 == clear excludes)
override void EnableAllInputs (bool bForceSupress=false)
Removes all active input excludes and restrictions.
override bool IsControlDisabled ()
returns if ANY exclude groups, restriction (or deprecated disable, if applicable) is active
override bool IsInputExcludeActive (string exclude)
Returns true if the particular input exclude group had been activated via script and is active.
override bool IsInputRestrictionActive (int restriction)
Returns true if the particular 'restriction' (those govern special behaviour outside regular input excludes, EInputRestrictors) is active.
override int GetControlDisabledMode ()
(mostly)DEPRECATED; only set on the old 'PlayerControlDisable' method
void CloseAllMenus ()
void DestroyAllMenus ()
void MoveHudForInventory (bool inv_open)
override void ShowInventory ()
override void HideInventory ()
void DestroyInventory ()
override void ResetGUI ()
override void ShowChat ()
override void HideChat ()
void ShowVehicleInfo ()
void HideVehicleInfo ()
override Hud GetHud ()
HudDebug GetHudDebug ()
override void RefreshCrosshairVisibility ()
override void HideCrosshairVisibility ()
override bool IsPaused ()
override void Pause ()
override void Continue ()
override bool IsMissionGameplay ()
override void AbortMission ()
override void CreateLogoutMenu (UIMenuPanel parent)
override void StartLogoutMenu (int time)
override void CreateDebugMonitor ()
override void HideDebugMonitor ()
protected void HandleMapToggleByKeyboardShortcut (Man player)
protected bool IsMapUnfoldActionRunning (ActionBase pAction)
void UpdateDebugMonitor ()
void SetActionDownTime (int time_down)
void SetActionUpTime (int time_up)
int LocalPressTime ()
int LocalReleaseTime ()
float GetHoldActionTime ()
void DisplayHairDebug ()
void ShowHairDebugValues (bool state)
override void UpdateVoiceLevelWidgets (int level)
override ImageWidget GetMicrophoneIcon ()
override WidgetFadeTimer GetMicWidgetFadeTimer ()
override map< int, ImageWidget > GetVoiceLevelWidgets ()
override map< int, ref WidgetFadeTimer > GetVoiceLevelTimers ()
override bool IsVoNActive ()
override void SetVoNActive (bool active)
override void HideVoiceLevelWidgets ()
override UIScriptedMenu GetNoteMenu ()
override void SetNoteMenu (UIScriptedMenu menu)
override void OnPlayerRespawned (Man player)
override void SetPlayerRespawning (bool state)
override bool IsPlayerRespawning ()
override array< vector > GetActiveRefresherLocations ()
override void SetRespawnModeClient (int mode)
override int GetRespawnModeClient ()
override GameplayEffectWidgets GetEffectWidgets ()
ScriptInvoker GetConnectivityInvoker ()
override void OnInit ()
override void Reset ()
DayZIntroScenePC GetIntroScenePC ()
DayZIntroSceneXbox GetIntroSceneXbox ()
void CreateIntroScene ()
override void UpdateInputDevicesAvailability ()
override void OnMissionStart ()
override void OnMissionFinish ()
override void OnUpdate (float timeslice)
void OnMenuEnter (int menu_id)
void OnInputDeviceChanged (int device)
int SortedInsert (array< int > list, int number)
void PlayMusic ()
void StopMusic ()
AbstractWave GetMenuMusic ()
void MissionServer ()
void ~MissionServer ()
override void OnInit ()
override void OnMissionStart ()
override void OnUpdate (float timeslice)
override void OnGameplayDataHandlerLoad ()
void RandomArtillery (float deltaTime)
override bool IsServer ()
override bool IsPlayerDisconnecting (Man player)
void UpdatePlayersStats ()
protected void AddNewPlayerLogout (PlayerBase player, notnull LogoutInfo info)
void UpdateLogoutPlayers ()
override void OnEvent (EventType eventTypeId, Param params)
void InvokeOnConnect (PlayerBase player, PlayerIdentity identity)
void InvokeOnDisconnect (PlayerBase player)
void OnClientPrepareEvent (PlayerIdentity identity, out bool useDB, out vector pos, out float yaw, out int preloadTimeout)
void ControlPersonalLight (PlayerBase player)
void SyncGlobalLighting (PlayerBase player)
bool ProcessLoginData (ParamsReadContext ctx)
returns whether received data is valid, ctx can be filled on client in StoreLoginData()
PlayerBase CreateCharacter (PlayerIdentity identity, vector pos, ParamsReadContext ctx, string characterName)
void EquipCharacter (MenuDefaultCharacterData char_data)
Spawns character equip from received data. Checks validity against config, randomizes if invalid value and config array not empty.
void StartingEquipSetup (PlayerBase player, bool clothesChosen)
can be overriden to manually set up starting equip. 'clothesChosen' is legacy parameter, does nothing.
bool VerifyAttachmentType (int slot_ID, string attachment_type)
PlayerBase OnClientNewEvent (PlayerIdentity identity, vector pos, ParamsReadContext ctx)
void OnClientReadyEvent (PlayerIdentity identity, PlayerBase player)
void OnClientRespawnEvent (PlayerIdentity identity, PlayerBase player)
void OnClientReconnectEvent (PlayerIdentity identity, PlayerBase player)
void OnClientDisconnectedEvent (PlayerIdentity identity, PlayerBase player, int logoutTime, bool authFailed)
void PlayerDisconnected (PlayerBase player, PlayerIdentity identity, string uid)
bool ShouldPlayerBeKilled (PlayerBase player)
void HandleBody (PlayerBase player)
void TickScheduler (float timeslice)
override bool InsertCorpse (Man player)
void UpdateCorpseStatesServer ()
override void SyncRespawnModeInfo (PlayerIdentity identity)
override RainProcurementHandler GetRainProcurementHandler ()
Private Attributes
int m_LifeState
bool m_Initialized
protected UIManager m_UIManager
Widget m_HudRootWidget
ImageWidget m_MicrophoneIcon
ref InventoryMenu m_InventoryMenu
ref Chat m_Chat
ref ActionMenu m_ActionMenu
ref IngameHud m_Hud
ref HudDebug m_HudDebug
ref LogoutMenu m_Logout
ref DebugMonitor m_DebugMonitor
protected ref ScriptInvoker m_OnConnectivityChanged
protected ref GameplayEffectWidgets m_EffectWidgets
ref Timer m_ChatChannelHideTimer
ref WidgetFadeTimer m_ChatChannelFadeTimer
ref WidgetFadeTimer m_MicFadeTimer
Widget m_ChatChannelArea
TextWidget m_ChatChannelText
NoteMenu m_Note
protected ref Timer m_ToggleHudTimer
protected const int HOLD_LIMIT_TIME = 300
protected int m_ActionDownTime
protected int m_ActionUpTime
protected bool m_InitOnce
protected bool m_ControlDisabled
protected int m_ControlDisabledMode
protected ref array< string > m_ActiveInputExcludeGroups
protected ref array< int > m_ActiveInputRestrictions
protected bool m_ProcessInputExcludes
protected bool m_QuickbarHold
protected bool m_PlayerRespawning
protected int m_RespawnModeClient
protected bool m_PauseQueued
protected bool m_VoNActive
protected Widget m_VoiceLevels
protected ref map< int, ImageWidget > m_VoiceLevelsWidgets
protected ref map< int, ref WidgetFadeTimer > m_VoiceLevelTimers
private UIScriptedMenu m_mainmenu
private CreditsMenu m_CreditsMenu
private ref DayZIntroScenePC m_IntroScenePC
private ref DayZIntroSceneXbox m_IntroSceneXbox
bool m_NoCutscene
private AbstractWave m_MenuMusic
ref array< Man > m_Players
ref array< ref CorpseData > m_DeadPlayersArray
ref map< PlayerBase, ref LogoutInfo > m_LogoutPlayers
ref map< PlayerBase, ref LogoutInfo > m_NewLogoutPlayers
ref RainProcurementHandler m_RainProcHandler
const int SCHEDULER_PLAYERS_PER_TICK = 5
int m_currentPlayer
int m_RespawnMode
private float m_ArtyBarrageTimer = 0
protected bool m_PlayArty = false
protected float m_ArtyDelay = 0
protected int m_MinSimultaneousStrikes = 0
protected int m_MaxSimultaneousStrikes = 0
protected ref array< vector > m_FiringPos
protected const ref array< vector > CHERNARUS_STRIKE_POS
protected const ref array< vector > LIVONIA_STRIKE_POS
PlayerBase m_player
MissionBase m_mission
PluginAdditionalInfo m_moduleDefaultCharacter
Constructor & Destructor Documentation
~MissionGameplay()
void ~MissionGameplay () inline private
References Continue(), DestroyInventory(), and g_Game.
~MissionServer()
void ~MissionServer () inline private
References CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), and ScriptCallQueue::Remove().
Member Function Documentation
AbortMission()
override void AbortMission () inline private
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, g_Game, CGame::GetCallQueue(), GetGame(), and IDC_MAIN_QUIT.
Referenced by CreateLogoutMenu().
AddActiveInputExcludes()
override void AddActiveInputExcludes (array< string > excludes) inline private
Adds one or more exclude groups to disable and refreshes excludes.
References GetUApi(), RefreshExcludes(), and UAInputAPI::SupressNextFrame().
Referenced by OnUpdate(), Pause(), PlayerControlDisable(), ShowChat(), and ShowInventory().
AddActiveInputRestriction()
override void AddActiveInputRestriction (int restrictor) inline private
Adds one input restriction (specific behaviour oudside regular excludes, defined below)
References UAInput::ForceEnable(), GetGame(), UAInputAPI::GetInputByID(), GetPlayer(), and GetUApi().
Referenced by OnUpdate(), Pause(), PlayerControlDisable(), and ShowInventory().
AddNewPlayerLogout()
protected void AddNewPlayerLogout (PlayerBase player, notnull LogoutInfo info) inline private
CloseAllMenus()
void CloseAllMenus () inline private
References UIManager::CloseAll(), and GetUIManager().
Referenced by OnUpdate(), and Pause().
Continue()
override void Continue () inline private
References UIManager::CloseMenu(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), GetUIManager(), IsPaused(), MENU_INGAME, MENU_LOGOUT, MENU_RESPAWN_DIALOGUE, RemoveActiveInputExcludes(), and RemoveActiveInputRestriction().
Referenced by OnUpdate(), and ~MissionGameplay().
ControlPersonalLight()
void ControlPersonalLight (PlayerBase player) inline private
References Error(), GetGame(), CGame::RPCSingleParam(), and CGame::ServerConfigGetInt().
Referenced by OnEvent().
CreateCharacter()
PlayerBase CreateCharacter (PlayerIdentity identity, vector pos, ParamsReadContext ctx, string characterName) inline private
References Class::CastTo(), CGame::CreatePlayer(), GetGame(), m_player, m_player, and CGame::SelectPlayer().
Referenced by OnClientNewEvent().
CreateDebugMonitor()
override void CreateDebugMonitor () inline private
CreateIntroScene()
void CreateIntroScene () inline private
Referenced by OnInit(), and Reset().
CreateLogoutMenu()
override void CreateLogoutMenu (UIMenuPanel parent) inline private
References AbortMission(), UIMenuPanel::EnterScriptedMenu(), GetGame(), GetPlayer(), and MENU_LOGOUT.
DestroyAllMenus()
void DestroyAllMenus () inline private
References UIManager::CloseAll(), DestroyInventory(), GetUIManager(), and UIManager::HideDialog().
Referenced by MissionGameplay(), OnEvent(), and OnMissionFinish().
DestroyInventory()
void DestroyInventory () inline private
References GetUIManager().
Referenced by DestroyAllMenus(), ResetGUI(), and ~MissionGameplay().
DisplayHairDebug()
void DisplayHairDebug () inline private
References DiagMenu::GetBool(), and ShowHairDebugValues().
Referenced by OnUpdate().
EnableAllInputs()
override void EnableAllInputs (bool bForceSupress = false) inline private
Removes all active input excludes and restrictions.
References GetUApi(), RemoveActiveInputRestriction(), UAInputAPI::SupressNextFrame(), and UAInputAPI::UpdateControls().
Referenced by OnMissionFinish().
EquipCharacter()
void EquipCharacter (MenuDefaultCharacterData char_data) inline private
Spawns character equip from received data. Checks validity against config, randomizes if invalid value and config array not empty.
References Count, MenuDefaultCharacterData::GetAttachmentMap(), m_player, GameConstants::RESPAWN_MODE_CUSTOM, and StartingEquipSetup().
Referenced by OnClientNewEvent().
GetActiveRefresherLocations()
override array< vector > GetActiveRefresherLocations () inline private
GetConnectivityInvoker()
ScriptInvoker GetConnectivityInvoker () inline private
References m_OnConnectivityChanged.
GetControlDisabledMode()
override int GetControlDisabledMode () inline private
(mostly)DEPRECATED; only set on the old 'PlayerControlDisable' method
References m_ControlDisabledMode.
GetEffectWidgets()
override GameplayEffectWidgets GetEffectWidgets () inline private
References m_EffectWidgets.
GetHoldActionTime()
float GetHoldActionTime () inline private
References LocalPressTime(), and LocalReleaseTime().
GetHud()
override Hud GetHud () inline private
References m_Hud.
Referenced by HideVehicleInfo(), MoveHudForInventory(), and ShowVehicleInfo().
GetHudDebug()
HudDebug GetHudDebug () inline private
References m_HudDebug.
Referenced by HideCrosshairVisibility(), and RefreshCrosshairVisibility().
GetIntroScenePC()
DayZIntroScenePC GetIntroScenePC () inline private
References Error(), and m_IntroScenePC.
GetIntroSceneXbox()
DayZIntroSceneXbox GetIntroSceneXbox () inline private
References Error(), and m_IntroSceneXbox.
GetInventory()
InventoryMenu GetInventory () inline private
References m_InventoryMenu.
GetMenuMusic()
AbstractWave GetMenuMusic () inline private
References m_MenuMusic.
GetMicrophoneIcon()
override ImageWidget GetMicrophoneIcon () inline private
References m_MicrophoneIcon.
GetMicWidgetFadeTimer()
override WidgetFadeTimer GetMicWidgetFadeTimer () inline private
References m_MicFadeTimer.
GetNoteMenu()
override UIScriptedMenu GetNoteMenu () inline private
References m_Note.
GetRainProcurementHandler()
override RainProcurementHandler GetRainProcurementHandler () inline private
References m_RainProcHandler.
GetRespawnModeClient()
override int GetRespawnModeClient () inline private
References m_RespawnModeClient.
GetUIManager()
UIManager GetUIManager () inline private
References m_UIManager.
Referenced by CloseAllMenus(), Continue(), DestroyAllMenus(), DestroyInventory(), HideInventory(), InitInventory(), OnEvent(), OnItemUsed(), OnMenuEnter(), OnMissionFinish(), OnMissionStart(), OnUpdate(), Pause(), ShowInventory(), and UpdateVoiceLevelWidgets().
GetVoiceLevelTimers()
override map< int, ref WidgetFadeTimer > GetVoiceLevelTimers () inline private
References m_VoiceLevelTimers.
GetVoiceLevelWidgets()
override map< int, ImageWidget > GetVoiceLevelWidgets () inline private
References m_VoiceLevelsWidgets.
HandleBody()
void HandleBody (PlayerBase player) inline private
References ShouldPlayerBeKilled().
Referenced by PlayerDisconnected().
HandleMapToggleByKeyboardShortcut()
protected void HandleMapToggleByKeyboardShortcut (Man player) inline private
References Mission::AddActiveInputExcludes(), Mission::AddActiveInputRestriction(), UIManager::CloseAll(), UIManager::EnterScriptedMenu(), GetGame(), CGame::GetMission(), CGame::GetUIManager(), CfgGameplayHandler::GetUse3DMap(), UIManager::IsMenuOpen(), and MENU_MAP.
Referenced by OnUpdate().
HideChat()
override void HideChat () inline private
References RemoveActiveInputExcludes().
HideCrosshairVisibility()
override void HideCrosshairVisibility () inline private
References GetHudDebug().
HideDebugMonitor()
override void HideDebugMonitor () inline private
HideInventory()
override void HideInventory () inline private
References GetGame(), VicinityItemManager::GetInstance(), GetPlayer(), GetUIManager(), UIManager::HideScriptedMenu(), RemoveActiveInputExcludes(), RemoveActiveInputRestriction(), and VicinityItemManager::ResetRefreshCounter().
Referenced by OnUpdate().
HideVehicleInfo()
void HideVehicleInfo () inline private
References GetHud(), and Hud::HideVehicleInfo().
HideVoiceLevelWidgets()
override void HideVoiceLevelWidgets () inline private
Referenced by OnInit().
InitInventory()
void InitInventory () inline private
References GetUIManager(), InventoryMenu(), and MENU_INVENTORY.
Referenced by ResetGUI(), and ShowInventory().
InsertCorpse()
override bool InsertCorpse (Man player) inline private
References GetGame(), and GetTime().
InvokeOnConnect()
void InvokeOnConnect (PlayerBase player, PlayerIdentity identity) inline private
References Debug::Log(), and ToString().
Referenced by OnEvent().
InvokeOnDisconnect()
void InvokeOnDisconnect (PlayerBase player) inline private
References Debug::Log(), and ToString().
Referenced by PlayerDisconnected().
IsControlDisabled()
override bool IsControlDisabled () inline private
returns if ANY exclude groups, restriction (or deprecated disable, if applicable) is active
References INPUT_EXCLUDE_ALL.
IsInputExcludeActive()
override bool IsInputExcludeActive (string exclude) inline private
Returns true if the particular input exclude group had been activated via script and is active.
Referenced by OnUpdate().
IsInputRestrictionActive()
override bool IsInputRestrictionActive (int restriction) inline private
Returns true if the particular 'restriction' (those govern special behaviour outside regular input excludes, EInputRestrictors) is active.
Referenced by OnUpdate().
IsMapUnfoldActionRunning()
protected bool IsMapUnfoldActionRunning (ActionBase pAction) inline private
References ActionUnfoldMap().
Referenced by OnUpdate().
IsMissionGameplay()
override bool IsMissionGameplay () inline private
IsPaused()
override bool IsPaused () inline private
References GetGame(), CGame::GetUIManager(), UIManager::IsMenuOpen(), and MENU_INGAME.
Referenced by Continue(), OnUpdate(), and Pause().
IsPlayerDisconnecting()
override bool IsPlayerDisconnecting (Man player) inline private
IsPlayerRespawning()
override bool IsPlayerRespawning () inline private
References m_PlayerRespawning.
IsServer()
override bool IsServer () inline private
Referenced by MissionBaseWorld::OnLog().
IsVoNActive()
override bool IsVoNActive () inline private
References m_VoNActive.
LocalPressTime()
int LocalPressTime () inline private
References m_ActionDownTime.
Referenced by GetHoldActionTime().
LocalReleaseTime()
int LocalReleaseTime () inline private
References m_ActionUpTime.
Referenced by GetHoldActionTime().
MissionGameplay()
void MissionGameplay () inline private
References CALL_CATEGORY_GUI, DestroyAllMenus(), m_Hud, m_Initialized, and SyncEvents::RegisterEvents().
MissionServer()
void MissionServer () inline private
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and UpdatePlayersStats().
MoveHudForInventory()
void MoveHudForInventory (bool inv_open) inline private
References GetHud().
OnClientDisconnectedEvent()
void OnClientDisconnectedEvent (PlayerIdentity identity, PlayerBase player, int logoutTime, bool authFailed) inline private
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), GetHive(), PlayerIdentityBase::GetId(), GetTime(), PlayerDisconnected(), Print(), and CGame::SendLogoutTime().
Referenced by OnEvent().
OnClientNewEvent()
PlayerBase OnClientNewEvent (PlayerIdentity identity, vector pos, ParamsReadContext ctx) inline private
References CreateCharacter(), CGame::CreateRandomPlayer(), Empty, EquipCharacter(), ErrorEx, MenuDefaultCharacterData::GenerateRandomEquip(), MenuDefaultCharacterData::GetCharacterType(), GetGame(), CGame::GetMenuDefaultCharacterData(), PlayerSpawnHandler::GetRandomCharacterPreset(), PlayerSpawnPreset::GetRandomCharacterType(), PlayerSpawnHandler::IsInitialized(), PlayerSpawnPreset::IsValid(), m_player, m_player, PlayerSpawnHandler::ProcessEquipmentData(), ProcessLoginData(), and GameConstants::RESPAWN_MODE_CUSTOM.
Referenced by OnEvent().
OnClientPrepareEvent()
void OnClientPrepareEvent (PlayerIdentity identity, out bool useDB, out vector pos, out float yaw, out int preloadTimeout) inline private
References GetHive().
Referenced by OnEvent().
OnClientReadyEvent()
void OnClientReadyEvent (PlayerIdentity identity, PlayerBase player) inline private
References GetGame(), CGame::RPCSingleParam(), and CGame::SelectPlayer().
Referenced by OnEvent().
OnClientReconnectEvent()
void OnClientReconnectEvent (PlayerIdentity identity, PlayerBase player) inline private
Referenced by OnEvent().
OnClientRespawnEvent()
void OnClientRespawnEvent (PlayerIdentity identity, PlayerBase player) inline private
References GetGame(), and CGame::RPCSingleParam().
Referenced by OnEvent().
OnEvent() [1/2]
override void OnEvent (EventType eventTypeId, Param params) inline private
References ChatChannelEventTypeID, ChatMessageEventTypeID, DestroyAllMenus(), GetGame(), CGame::GetPlayer(), GetPlugin(), GetUIManager(), InventoryMenu(), m_Hud, MENU_CHAT_INPUT, Hud::OnResizeScreen(), and SetFreeCameraEventTypeID.
OnEvent() [2/2]
override void OnEvent (EventType eventTypeId, Param params) inline private
References Class::CastTo(), ClientDisconnectedEventTypeID, ClientNewEventTypeID, ClientPrepareEventTypeID, ClientReadyEventTypeID, ClientReconnectEventTypeID, ClientRespawnEventTypeID, ControlPersonalLight(), PlayerIdentityBase::GetId(), InvokeOnConnect(), Debug::Log(), LogoutCancelEventTypeID, OnClientDisconnectedEvent(), OnClientNewEvent(), OnClientPrepareEvent(), OnClientReadyEvent(), OnClientReconnectEvent(), OnClientRespawnEvent(), Print(), SyncEvents::SendPlayerList(), UndergroundAreaLoader::SyncDataSend(), CfgGameplayHandler::SyncDataSendEx(), and SyncGlobalLighting().
OnGameplayDataHandlerLoad()
override void OnGameplayDataHandlerLoad () inline private
References CfgGameplayHandler::GetDisableRespawnDialog(), GetGame(), and CGame::SetDebugMonitorEnabled().
OnInit() [1/3]
override void OnInit () inline private
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetUIManager(), CGame::GetWorkspace(), HideVoiceLevelWidgets(), HudDebug(), PPEffects::Init(), MapMarkerTypes::Init(), Hud::Init(), LogManager::IsLogsEnable(), CfgGameplayHandler::LoadData(), m_Hud, m_Initialized, and UndergroundAreaLoader::SpawnAllTriggerCarriers().
OnInit() [2/3]
override void OnInit () inline private
References CreateIntroScene(), g_Game, MENU_MAIN, MENU_TITLE_SCREEN, and OnInputDeviceChanged().
OnInit() [3/3]
override void OnInit () inline private
References CfgGameplayHandler::LoadData(), PlayerSpawnHandler::LoadData(), and UndergroundAreaLoader::SpawnAllTriggerCarriers().
OnInputDeviceChanged()
void OnInputDeviceChanged (int device) inline private
OnItemUsed()
override void OnItemUsed (InventoryItem item, Man owner) inline private
References GetUIManager(), and MENU_BOOK.
OnKeyPress()
override void OnKeyPress (int key) inline private
References Hud::KeyPress(), and m_Hud.
OnKeyRelease()
override void OnKeyRelease (int key) inline private
OnMenuEnter()
void OnMenuEnter (int menu_id) inline private
References GetGame(), GetUIManager(), and MENU_CREDITS.
OnMissionFinish() [1/2]
override void OnMissionFinish () inline private
References DestroyAllMenus(), EnableAllInputs(), g_Game, GetGame(), GetPlayer(), PPEManagerStatic::GetPPEManager(), GetUIManager(), UIManager::HideDialog(), and m_HudRootWidget.
OnMissionFinish() [2/2]
override void OnMissionFinish () inline private
References UIManager::CloseAll(), g_Game, GetGame(), and CGame::GetUIManager().
OnMissionStart() [1/3]
override void OnMissionStart () inline private
Only once the game is loaded should we take control of the cursor
References g_Game, GetUIManager(), and UIManager::ShowUICursor().
OnMissionStart() [2/3]
override void OnMissionStart () inline private
References ProgressAsync::DestroyAllPendingProgresses(), and g_Game.
OnMissionStart() [3/3]
override void OnMissionStart () inline private
References EffectAreaLoader::CreateZones().
OnPlayerRespawned()
override void OnPlayerRespawned (Man player) inline private
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, g_Game, CGame::GetCallQueue(), GetGame(), and CGame::GetSoundScene().
OnUpdate() [1/3]
override void OnUpdate (float timeslice) inline private
References ActionBase(), AddActiveInputExcludes(), AddActiveInputRestriction(), DbgUI::Begin(), CloseAllMenus(), Continue(), Input::DisableKey(), DisplayHairDebug(), DbgUI::End(), SEffectManager::Event_OnFrameUpdate, UIManager::FindMenu(), g_Game, DiagMenu::GetBool(), GetGame(), CGame::GetInput(), UAInputAPI::GetInputByID(), VONManager::GetInstance(), ItemManager::GetInstance(), CfgGameplayHandler::GetMapIgnoreMapOwnership(), UIManager::GetMenu(), CGame::GetPlayer(), ItemManager::GetSelectedItem(), GetUApi(), GetUIManager(), CfgGameplayHandler::GetUse3DMap(), VONManagerBase::HandleInput(), HandleMapToggleByKeyboardShortcut(), HideInventory(), INPUT_ACTION_TYPE_DOUBLETAP, INPUT_ACTION_TYPE_DOWN_EVENT, INPUT_DEVICE_MOUSE, INPUT_DEVICE_MOUSE_AXIS, InventoryMenu(), IsCLIParam(), UIManager::IsDialogVisible(), Input::IsEnabledMouseAndKeyboardEvenOnServer(), Hud::IsHideHudPlayer(), Hud::IsHideQuickbarPlayer(), IsInputExcludeActive(), IsInputRestrictionActive(), IsLocked(), IsMapUnfoldActionRunning(), UIScriptedMenu::IsMenuClosing(), IsPaused(), UAInput::Lock(), m_Hud, m_InventoryMenu, MENU_CHAT, MENU_GESTURES, MENU_INSPECT, MENU_INVENTORY, MENU_NOTE, MENU_RADIAL_QUICKBAR, Pause(), PerformRefreshExcludes(), RefreshExcludes(), UIManager::ScreenFadeOut(), ShowChat(), Hud::ShowHudPlayer(), Hud::ShowHudUI(), ShowInventory(), Hud::ShowQuickbarPlayer(), UIManager::ShowUICursor(), DbgUI::Text(), TickScheduler(), UAInput::Unlock(), UpdateDebugMonitor(), UIScriptedMenu::UseKeyboard(), UIScriptedMenu::UseMouse(), and Hud::ZeroingKeyPress().
OnUpdate() [2/3]
override void OnUpdate (float timeslice) inline private
References g_Game.
OnUpdate() [3/3]
override void OnUpdate (float timeslice) inline private
References RandomArtillery(), TickScheduler(), and UpdateLogoutPlayers().
Pause()
override void Pause () inline private
References AddActiveInputExcludes(), AddActiveInputRestriction(), CloseAllMenus(), UIManager::EnterScriptedMenu(), g_Game, GetGame(), GetID(), GetPlayer(), GetUIManager(), IsPaused(), and MENU_INGAME.
Referenced by OnUpdate().
PerformRefreshExcludes()
protected void PerformRefreshExcludes () inline private
applies queued excludes (0 == clear excludes)
References UAInputAPI::ActivateExclude(), GetUApi(), and UAInputAPI::UpdateControls().
Referenced by OnUpdate().
PlayerControlDisable()
override void PlayerControlDisable (int mode) inline private
Deprecated; simple input restrictions.
References AddActiveInputExcludes(), AddActiveInputRestriction(), GetGame(), GetPlayer(), INPUT_EXCLUDE_ALL, INPUT_EXCLUDE_INVENTORY, INPUT_EXCLUDE_MAP, INPUT_EXCLUDE_MOUSE_ALL, INPUT_EXCLUDE_MOUSE_RADIAL, and Debug::Log().
PlayerControlEnable()
override void PlayerControlEnable (bool bForceSupress) inline private
Deprecated; removes last input exclude and associated controls restrictions.
References GetGame(), GetPlayer(), INPUT_EXCLUDE_ALL, INPUT_EXCLUDE_INVENTORY, INPUT_EXCLUDE_MAP, INPUT_EXCLUDE_MOUSE_ALL, INPUT_EXCLUDE_MOUSE_RADIAL, HumanInputController::LimitsDisableSprint(), RemoveActiveInputExcludes(), and RemoveActiveInputRestriction().
PlayerDisconnected()
void PlayerDisconnected (PlayerBase player, PlayerIdentity identity, string uid) inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), Hive::CharacterExit(), CGame::DisconnectPlayer(), CGame::GetCallQueue(), GetGame(), GetHive(), HandleBody(), InvokeOnDisconnect(), Print(), and SyncEvents::SendPlayerList().
Referenced by OnClientDisconnectedEvent(), and UpdateLogoutPlayers().
PlayMusic()
void PlayMusic () inline private
References SoundObjectBuilder::BuildSoundObject(), GetGame(), CGame::GetSoundScene(), AbstractWave::Loop(), AbstractWave::Play(), and SoundObject().
ProcessLoginData()
bool ProcessLoginData (ParamsReadContext ctx) inline private
returns whether received data is valid, ctx can be filled on client in StoreLoginData()
References MenuDefaultCharacterData::DeserializeCharacterData(), GetGame(), and CGame::GetMenuDefaultCharacterData().
Referenced by OnClientNewEvent().
RandomArtillery()
void RandomArtillery (float deltaTime) inline private
References Math::Clamp(), GetGame(), Math::RandomIntInclusive(), and CGame::RPC().
Referenced by OnUpdate().
RefreshCrosshairVisibility()
override void RefreshCrosshairVisibility () inline private
References GetHudDebug().
RefreshExcludes()
override void RefreshExcludes () inline private
queues refresh of input excludes
Referenced by AddActiveInputExcludes(), OnUpdate(), and RemoveActiveInputExcludes().
RemoveActiveInputExcludes()
override void RemoveActiveInputExcludes (array< string > excludes, bool bForceSupress = false) inline private
Removes one or more exclude groups and refreshes excludes.
References GetUApi(), RefreshExcludes(), and UAInputAPI::SupressNextFrame().
Referenced by Continue(), HideChat(), HideInventory(), and PlayerControlEnable().
RemoveActiveInputRestriction()
override void RemoveActiveInputRestriction (int restrictor) inline private
Removes one restriction (specific behaviour oudside regular excludes, defined below)
References UAInput::ForceEnable(), UAInputAPI::GetInputByID(), and GetUApi().
Referenced by Continue(), EnableAllInputs(), HideInventory(), and PlayerControlEnable().
Reset()
override void Reset () inline private
References CreateIntroScene(), m_IntroScenePC, and m_IntroSceneXbox.
ResetGUI()
override void ResetGUI () inline private
References DestroyInventory(), and InitInventory().
SendMuteListToServer()
void SendMuteListToServer (map< string, bool > mute_list) inline private
References ScriptRPC::Send(), and Serializer::Write().
SetActionDownTime()
void SetActionDownTime (int time_down) inline private
SetActionUpTime()
void SetActionUpTime (int time_up) inline private
SetNoteMenu()
override void SetNoteMenu (UIScriptedMenu menu) inline private
SetPlayerRespawning()
override void SetPlayerRespawning (bool state) inline private
SetRespawnModeClient()
override void SetRespawnModeClient (int mode) inline private
SetVoNActive()
override void SetVoNActive (bool active) inline private
ShouldPlayerBeKilled()
bool ShouldPlayerBeKilled (PlayerBase player) inline private
Referenced by HandleBody().
ShowChat()
override void ShowChat () inline private
References AddActiveInputExcludes(), UIManager::EnterScriptedMenu(), GetGame(), CGame::GetVoiceLevel(), MENU_CHAT_INPUT, and UpdateVoiceLevelWidgets().
Referenced by OnUpdate().
ShowHairDebugValues()
void ShowHairDebugValues (bool state) inline private
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), DbgUI::EndCleanupScope(), GetPlugin(), DiagMenu::GetValue(), and DbgUI::Text().
Referenced by DisplayHairDebug().
ShowInventory()
override void ShowInventory () inline private
References AddActiveInputExcludes(), AddActiveInputRestriction(), GetGame(), UIManager::GetMenu(), GetPlayer(), GetUIManager(), InitInventory(), MENU_INVENTORY, and UIManager::ShowScriptedMenu().
Referenced by OnUpdate().
ShowVehicleInfo()
void ShowVehicleInfo () inline private
References GetHud(), and Hud::ShowVehicleInfo().
SortedInsert()
int SortedInsert (array< int > list, int number) inline private
References Math::Floor().
StartingEquipSetup()
void StartingEquipSetup (PlayerBase player, bool clothesChosen) inline private
can be overriden to manually set up starting equip. 'clothesChosen' is legacy parameter, does nothing.
Referenced by EquipCharacter().
StartLogoutMenu()
override void StartLogoutMenu (int time) inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
StopMusic()
void StopMusic () inline private
References AbstractWave::Stop().
SyncGlobalLighting()
void SyncGlobalLighting (PlayerBase player) inline private
References GetGame(), CGame::RPCSingleParam(), and CGame::ServerConfigGetInt().
Referenced by OnEvent().
SyncRespawnModeInfo()
override void SyncRespawnModeInfo (PlayerIdentity identity) inline private
References ScriptRPC::Send(), and Serializer::Write().
TickScheduler() [1/2]
void TickScheduler (float timeslice) inline private
References GetGame(), and GetPlayer().
Referenced by OnUpdate().
TickScheduler() [2/2]
void TickScheduler (float timeslice) inline private
References GetGame(), World::GetPlayerList(), CGame::GetWorld(), and Math::Min().
UpdateCorpseStatesServer()
void UpdateCorpseStatesServer () inline private
References GetGame(), CGame::GetTime(), CorpseData::m_bUpdate, CorpseData::m_iLastUpdateTime, CorpseData::m_Player, and CorpseData::UpdateCorpseState().
Referenced by UpdatePlayersStats().
UpdateDebugMonitor()
void UpdateDebugMonitor () inline private
References DebugMonitorValues::GetBlood(), GetGame(), DebugMonitorValues::GetHealth(), DebugMonitorValues::GetLastDamage(), and GetPlayer().
Referenced by OnUpdate().
UpdateInputDevicesAvailability() [1/2]
override void UpdateInputDevicesAvailability () inline private
References g_Game.
Referenced by MissionBaseWorld::MissionBase().
UpdateInputDevicesAvailability() [2/2]
override void UpdateInputDevicesAvailability () inline private
References g_Game.
UpdateLogoutPlayers()
void UpdateLogoutPlayers () inline private
References GetGame(), GetTime(), and PlayerDisconnected().
Referenced by OnUpdate().
UpdatePlayersStats()
void UpdatePlayersStats () inline private
References Class::CastTo(), GetGame(), CGame::GetPlayers(), GetPlugin(), PluginLifespan(), AnalyticsManagerServer::STAT_DISTANCE, AnalyticsManagerServer::STAT_PLAYTIME, and UpdateCorpseStatesServer().
Referenced by MissionServer().
UpdateVoiceLevelWidgets()
override void UpdateVoiceLevelWidgets (int level) inline private
References GetUIManager(), and MENU_CHAT_INPUT.
Referenced by ShowChat().
VerifyAttachmentType()
bool VerifyAttachmentType (int slot_ID, string attachment_type) inline private
Field Documentation
CHERNARUS_STRIKE_POS
protected const ref array<vector> CHERNARUS_STRIKE_POS private
Initial value:
=
    {
        "-500.00 165.00 5231.69",
        "-500.00 300.00 9934.41",
        "10406.86 192.00 15860.00",
        "4811.75 370.00 15860.00",
        "-500.00 453.00 15860.00"
    }
HOLD_LIMIT_TIME
protected const int HOLD_LIMIT_TIME = 300 private
LIVONIA_STRIKE_POS
protected const ref array<vector> LIVONIA_STRIKE_POS private
Initial value:
=
    {
        "7440.00 417.00 -500.00",
        "-500.00 276.00 5473.00",
        "-500.00 265.00 9852.00",
        "4953.00 240.00 13300.00",
        "9620.00 188.00 13300.00",
        "13300.00 204.00 10322.00",
        "13300.00 288.00 6204.00",
        "13300.00 296.00 -500.00"
    }
m_ActionDownTime
protected int m_ActionDownTime private
Referenced by LocalPressTime().
m_ActionMenu
ref ActionMenu m_ActionMenu private
m_ActionUpTime
protected int m_ActionUpTime private
Referenced by LocalReleaseTime().
m_ActiveInputExcludeGroups
protected ref array<string> m_ActiveInputExcludeGroups private
m_ActiveInputRestrictions
protected ref array<int> m_ActiveInputRestrictions private
m_ArtyBarrageTimer
private float m_ArtyBarrageTimer = 0 private
m_ArtyDelay
protected float m_ArtyDelay = 0 private
m_Chat
ref Chat m_Chat private
m_ChatChannelArea
Widget m_ChatChannelArea private
m_ChatChannelFadeTimer
ref WidgetFadeTimer m_ChatChannelFadeTimer private
m_ChatChannelHideTimer
ref Timer m_ChatChannelHideTimer private
m_ChatChannelText
TextWidget m_ChatChannelText private
m_ControlDisabled
protected bool m_ControlDisabled private
m_ControlDisabledMode
protected int m_ControlDisabledMode private
Referenced by GetControlDisabledMode().
m_CreditsMenu
private CreditsMenu m_CreditsMenu private
m_currentPlayer
int m_currentPlayer private
m_DeadPlayersArray
ref array<ref CorpseData> m_DeadPlayersArray private
m_DebugMonitor
ref DebugMonitor m_DebugMonitor private
m_EffectWidgets
protected ref GameplayEffectWidgets m_EffectWidgets private
Referenced by GetEffectWidgets().
m_FiringPos
protected ref array<vector> m_FiringPos private
m_Hud
ref IngameHud m_Hud private
Referenced by GetHud().
m_HudDebug
ref HudDebug m_HudDebug private
Referenced by GetHudDebug().
m_HudRootWidget
Widget m_HudRootWidget private
Referenced by OnMissionFinish().
m_Initialized
bool m_Initialized private
m_InitOnce
protected bool m_InitOnce private
m_IntroScenePC
private ref DayZIntroScenePC m_IntroScenePC private
Referenced by GetIntroScenePC(), and Reset().
m_IntroSceneXbox
private ref DayZIntroSceneXbox m_IntroSceneXbox private
Referenced by GetIntroSceneXbox(), and Reset().
m_InventoryMenu
ref InventoryMenu m_InventoryMenu private
Referenced by GetInventory(), and OnUpdate().
m_LifeState
int m_LifeState private
m_Logout
ref LogoutMenu m_Logout private
m_LogoutPlayers
ref map<PlayerBase, ref LogoutInfo> m_LogoutPlayers private
m_mainmenu
private UIScriptedMenu m_mainmenu private
m_MaxSimultaneousStrikes
protected int m_MaxSimultaneousStrikes = 0 private
m_MenuMusic
private AbstractWave m_MenuMusic private
DEPRECATED
Referenced by GetMenuMusic().
m_MicFadeTimer
ref WidgetFadeTimer m_MicFadeTimer private
Referenced by GetMicWidgetFadeTimer().
m_MicrophoneIcon
ImageWidget m_MicrophoneIcon private
Referenced by GetMicrophoneIcon().
m_MinSimultaneousStrikes
protected int m_MinSimultaneousStrikes = 0 private
m_mission
MissionBase m_mission private
m_moduleDefaultCharacter
PluginAdditionalInfo m_moduleDefaultCharacter private
m_NewLogoutPlayers
ref map<PlayerBase, ref LogoutInfo> m_NewLogoutPlayers private
m_NoCutscene
bool m_NoCutscene private
m_Note
NoteMenu m_Note private
Referenced by GetNoteMenu().
m_OnConnectivityChanged
protected ref ScriptInvoker m_OnConnectivityChanged private
Referenced by GetConnectivityInvoker().
m_PauseQueued
protected bool m_PauseQueued private
m_PlayArty
protected bool m_PlayArty = false private
m_player
PlayerBase m_player private
Referenced by CreateCharacter(), and OnClientNewEvent().
m_PlayerRespawning
protected bool m_PlayerRespawning private
Referenced by IsPlayerRespawning().
m_Players
ref array<Man> m_Players private
m_ProcessInputExcludes
protected bool m_ProcessInputExcludes private
m_QuickbarHold
protected bool m_QuickbarHold private
m_RainProcHandler
ref RainProcurementHandler m_RainProcHandler private
Referenced by GetRainProcurementHandler().
m_RespawnMode
int m_RespawnMode private
m_RespawnModeClient
protected int m_RespawnModeClient private
Referenced by GetRespawnModeClient().
m_ToggleHudTimer
protected ref Timer m_ToggleHudTimer private
m_UIManager
protected UIManager m_UIManager private
Referenced by GetUIManager().
m_VoiceLevels
protected Widget m_VoiceLevels private
m_VoiceLevelsWidgets
protected ref map<int,ImageWidget> m_VoiceLevelsWidgets private
Referenced by GetVoiceLevelWidgets().
m_VoiceLevelTimers
protected ref map<int,ref WidgetFadeTimer> m_VoiceLevelTimers private
Referenced by GetVoiceLevelTimers().
m_VoNActive
protected bool m_VoNActive private
Referenced by IsVoNActive().
SCHEDULER_PLAYERS_PER_TICK
const int SCHEDULER_PLAYERS_PER_TICK = 5 private
The documentation for this class was generated from the following files:
P:/scripts/5_Mission/mission/missionGameplay.c
P:/scripts/5_Mission/mission/missionMainMenu.c
P:/scripts/5_Mission/mission/missionServer.c