DayZ Scripts: CfgPlayerRestrictedAreaHandler Class Reference
CfgPlayerRestrictedAreaHandler Class Reference
Static Private Member Functions
static bool LoadData ()
static bool IsInitialized ()
static void SyncDataSend (notnull PlayerIdentity identity)
static void OnRPC (ParamsReadContext ctx)
static bool IsPointInPlayerRestrictedAreaClosest (vector point, out PlayerRestrictedAreaInstance hitArea)
static bool IsPointInPlayerRestrictedArea (vector point, out PlayerRestrictedAreaInstance hitArea)
static private PlayerRestrictedAreaInstance GetClosestArea (vector point)
static private bool IsCylinderInAreaBox (notnull PlayerRestrictedAreaInstance area, vector point, float cylinderRadius=0.25, float cylinderHeight=1)
default cylinder values sufficient for player detection
static private bool IsPointInAreaPolygon (notnull PlayerRestrictedAreaInstance area, vector point)
static void DrawBoxesDebug (bool draw)
static void DrawPolygonLinesDebug (bool draw)
Static Private Attributes
static private bool m_Initialized
static ref TStringArray m_PRAFiles = new TStringArray()
static ref CfgPlayerRestrictedAreaJsonData m_Data = new CfgPlayerRestrictedAreaJsonData()
static private ref array< Shape > m_DbgShapesBoxes
static private ref array< Shape > m_DbgShapesPolygonLines
Member Function Documentation
DrawBoxesDebug()
static void DrawBoxesDebug (bool draw) inline static private
References Debug::DrawBox(), IsInitialized(), m_Data, m_DbgShapesBoxes, CfgPlayerRestrictedAreaJsonData::m_ValidatedAreas, and Shape.
DrawPolygonLinesDebug()
static void DrawPolygonLinesDebug (bool draw) inline static private
References COLOR_RED, COLOR_WHITE, Debug::DrawLine(), GetGame(), IsInitialized(), m_Data, m_DbgShapesPolygonLines, CfgPlayerRestrictedAreaJsonData::m_ValidatedAreas, Shape, and Vector().
GetClosestArea()
static private PlayerRestrictedAreaInstance GetClosestArea (vector point) inline static private
References vector::DistanceSq(), m_Data, and CfgPlayerRestrictedAreaJsonData::m_ValidatedAreas.
Referenced by IsPointInPlayerRestrictedAreaClosest().
IsCylinderInAreaBox()
static private bool IsCylinderInAreaBox (notnull PlayerRestrictedAreaInstance area, vector point, float cylinderRadius = 0.25, float cylinderHeight = 1) inline static private
default cylinder values sufficient for player detection
References Math3D::IntersectCylinderOBB(), and Math3D::MatrixIdentity4().
Referenced by IsPointInPlayerRestrictedArea(), and IsPointInPlayerRestrictedAreaClosest().
IsInitialized()
static bool IsInitialized () inline static private
References m_Initialized.
Referenced by ManBase::AfterStoreLoad(), DrawBoxesDebug(), DrawPolygonLinesDebug(), IsPointInPlayerRestrictedArea(), and IsPointInPlayerRestrictedAreaClosest().
IsPointInAreaPolygon()
static private bool IsPointInAreaPolygon (notnull PlayerRestrictedAreaInstance area, vector point) inline static private
References Math2D().
Referenced by IsPointInPlayerRestrictedArea(), and IsPointInPlayerRestrictedAreaClosest().
IsPointInPlayerRestrictedArea()
static bool IsPointInPlayerRestrictedArea (vector point, out PlayerRestrictedAreaInstance hitArea) inline static private
References IsCylinderInAreaBox(), IsInitialized(), IsPointInAreaPolygon(), m_Data, and CfgPlayerRestrictedAreaJsonData::m_ValidatedAreas.
Referenced by ManBase::AfterStoreLoad().
IsPointInPlayerRestrictedAreaClosest()
static bool IsPointInPlayerRestrictedAreaClosest (vector point, out PlayerRestrictedAreaInstance hitArea) inline static private
References GetClosestArea(), IsCylinderInAreaBox(), IsInitialized(), and IsPointInAreaPolygon().
LoadData()
static bool LoadData () inline static private
References ErrorEx, FileExist(), string::Format(), g_Game, GetGame(), CfgGameplayHandler::GetPlayerRestrictedAreaFiles(), CGame::GetWorldName(), CfgPlayerRestrictedAreaJsonData::InitializeAreas(), CfgPlayerRestrictedAreaJsonData::m_Areas, m_Data, m_Initialized, m_PRAFiles, and path.
Referenced by MissionBase::OnInit().
OnRPC()
static void OnRPC (ParamsReadContext ctx) inline static private
References ErrorEx, m_Data, m_Initialized, CfgPlayerRestrictedAreaJsonData::m_ValidatedAreas, and Serializer::Read().
Referenced by CGame::OnRPC().
SyncDataSend()
static void SyncDataSend (notnull PlayerIdentity identity) inline static private
References GetGame(), m_Data, and CGame::RPCSingleParam().
Referenced by MissionBase::OnEvent().
Field Documentation
m_Data
ref CfgPlayerRestrictedAreaJsonData m_Data = new CfgPlayerRestrictedAreaJsonData() static private
Referenced by DrawBoxesDebug(), DrawPolygonLinesDebug(), GetClosestArea(), IsPointInPlayerRestrictedArea(), LoadData(), OnRPC(), and SyncDataSend().
m_DbgShapesBoxes
private ref array<Shape> m_DbgShapesBoxes static private
Referenced by DrawBoxesDebug().
m_DbgShapesPolygonLines
private ref array<Shape> m_DbgShapesPolygonLines static private
Referenced by DrawPolygonLinesDebug().
m_Initialized
private bool m_Initialized static private
Referenced by IsInitialized(), LoadData(), and OnRPC().
m_PRAFiles
ref TStringArray m_PRAFiles = new TStringArray() static private
Referenced by LoadData().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/CfgPlayerRestrictedAreaHandler.c