DayZ Scripts: ActionSewTarget Class Reference
ActionSewTarget Class Reference
Private Member Functions
void ActionSewTarget ()
override void CreateConditionComponents ()
override void OnFinishProgressServer (ActionData action_data)
override void ApplyBandage (ItemBase item, PlayerBase player)
Detailed Description
Definition at line 9 of file ActionSewTarget.c.
Constructor & Destructor Documentation
ActionSewTarget()
void ActionSewTarget () inline private
Definition at line 11 of file ActionSewTarget.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_MEDIUM.
Member Function Documentation
ApplyBandage()
override void ApplyBandage (ItemBase item, PlayerBase player) inline private
Definition at line 48 of file ActionSewTarget.c.
References AGT_ITEM_TO_FLESH, and GetPlugin().
Referenced by OnFinishProgressServer().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 22 of file ActionSewTarget.c.
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 34 of file ActionSewTarget.c.
References ApplyBandage(), CanReceiveAction(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/Medical/ActionSewTarget.c