DayZ Scripts: PoisoningMdfr Class Reference
PoisoningMdfr Class Reference
Private Member Functions
override void Init ()
override string GetDebugText ()
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnActivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Static Private Attributes
static const int AGENT_THRESHOLD_ACTIVATE = 150
static const int AGENT_THRESHOLD_DEACTIVATE = 0
static const int VOMIT_OCCURRENCES_PER_HOUR_MIN = 60
static const int VOMIT_OCCURRENCES_PER_HOUR_MAX = 120
static const int WATER_DRAIN_FROM_VOMIT = 70
static const int ENERGY_DRAIN_FROM_VOMIT = 55
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
References AGENT_THRESHOLD_ACTIVATE.
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
References AGENT_THRESHOLD_DEACTIVATE.
GetDebugText()
override string GetDebugText () inline private
References AGENT_THRESHOLD_ACTIVATE, and AGENT_THRESHOLD_DEACTIVATE.
Init()
override void Init () inline private
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, m_ID, m_IsPersistent, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void OnActivate (PlayerBase player) inline private
OnDeactivate()
override void OnDeactivate (PlayerBase player) inline private
OnReconnect()
override void OnReconnect (PlayerBase player) inline private
References OnActivate().
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
References Easing::EaseInCirc(), ENERGY_DRAIN_FROM_VOMIT, Math::InverseLerp(), Math::Lerp(), m_Player, Math::RandomFloat01(), SymptomBase::SetDuration(), VOMIT_OCCURRENCES_PER_HOUR_MAX, VOMIT_OCCURRENCES_PER_HOUR_MIN, and WATER_DRAIN_FROM_VOMIT.
Field Documentation
AGENT_THRESHOLD_ACTIVATE
const int AGENT_THRESHOLD_ACTIVATE = 150 static private
Referenced by ActivateCondition(), and GetDebugText().
AGENT_THRESHOLD_DEACTIVATE
const int AGENT_THRESHOLD_DEACTIVATE = 0 static private
Referenced by DeactivateCondition(), and GetDebugText().
ENERGY_DRAIN_FROM_VOMIT
const int ENERGY_DRAIN_FROM_VOMIT = 55 static private
Referenced by OnTick().
VOMIT_OCCURRENCES_PER_HOUR_MAX
const int VOMIT_OCCURRENCES_PER_HOUR_MAX = 120 static private
Referenced by OnTick().
VOMIT_OCCURRENCES_PER_HOUR_MIN
const int VOMIT_OCCURRENCES_PER_HOUR_MIN = 60 static private
Referenced by OnTick().
WATER_DRAIN_FROM_VOMIT
const int WATER_DRAIN_FROM_VOMIT = 70 static private
Referenced by OnTick().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/conditions/Poisoning.c