DayZ Scripts: CarchingResultFishingAction Class Reference
CarchingResultFishingAction Class Reference
Private Member Functions
override EntityAI SpawnAndSetup (out int yItemIdx, vector v=vector.Zero)
float GetCurrentCycleTime (CatchingContextFishingRodAction ctx)
Member Function Documentation
GetCurrentCycleTime()
float GetCurrentCycleTime (CatchingContextFishingRodAction ctx) inline private
References FishYieldItemBase::GetCycleTimeForYieldItem(), and CatchingResultBasic::m_YItem.
Referenced by CatchingContextFishingRodAction::GetActionCycleTime().
SpawnAndSetup()
override EntityAI SpawnAndSetup (out int yItemIdx, vector v = vector.Zero) inline private
References Class::CastTo(), and CatchingResultBasic::m_Quality.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Systems/AnimalCatchingSystem/CatchingResultStructures/CarchingResultFishingAction.c