DayZ Scripts: ActionInteractLoopBaseCB Class Reference
ActionInteractLoopBaseCB Class Reference
Private Member Functions
bool CancelCondition ()
override void CreateActionComponent ()
override void InitActionComponent ()
Member Function Documentation
CancelCondition()
bool CancelCondition () inline private
References DefaultCancelCondition(), AnimatedActionBase::Do(), GetState(), ActionBaseCB::m_ActionData, ActionBaseCB::m_Interrupted, STATE_LOOP_LOOP, and STATE_LOOP_LOOP2.
CreateActionComponent()
override void CreateActionComponent () inline private
References ActionBaseCB::m_ActionData.
InitActionComponent()
override void InitActionComponent () inline private
References EnableCancelCondition().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/ActionInteractLoopBase.c