DayZ Scripts: P:/scripts/3_Game/Systems/TFTests/EnProfilerTests.c File Reference
EnProfilerTests.c File Reference
Data Structures
class EnProfilerTests
Functions
EnProfilerTests TestFramework Sleep2 (float timeS)
void EnProfilerTests ()
void ~EnProfilerTests ()
TFResult TestToggling ()
TFResult TestTogglingImmediate ()
TFResult TestSetFlags ()
TFResult TestClearFlags ()
TFResult TestAddFlags ()
TFResult TestModule ()
TFResult TestClassTimeData ()
TFResult TestClassCountData ()
TFResult TestFuncTimeData ()
TFResult TestFuncCountData ()
float Sleep (float timeS)
float StringFormat ()
float StringConcat ()
void TestFuncCountDataHelper ()
static void TestFuncCountDataHelperStatic ()
float SleepAgain (float timeS)
float DoEverything ()
Variables
bool m_bWasProfilerEnabled
Remember this, so we can restore the previous state before the test!
Function Documentation
DoEverything()
float DoEverything ()
Definition at line 784 of file EnProfilerTests.c.
References GetGame(), CGame::GetTickTime(), and Sleep2().
EnProfilerTests()
void EnProfilerTests ()
Definition at line 770 of file EnProfilerTests.c.
Sleep()
float Sleep (float timeS)
Definition at line 1468 of file EnProfilerTests.c.
Sleep2()
EnProfilerTests TestFramework Sleep2 (float timeS)
Definition at line 1 of file EnProfilerTests.c.
Referenced by DoEverything().
SleepAgain()
float SleepAgain (float timeS)
Definition at line 773 of file EnProfilerTests.c.
References GetGame(), and CGame::GetTickTime().
StringConcat()
float StringConcat ()
Definition at line 1495 of file EnProfilerTests.c.
StringFormat()
float StringFormat ()
Definition at line 1481 of file EnProfilerTests.c.
TestAddFlags()
TFResult TestAddFlags ()
Definition at line 918 of file EnProfilerTests.c.
TestClassCountData()
TFResult TestClassCountData ()
Definition at line 1190 of file EnProfilerTests.c.
TestClassTimeData()
TFResult TestClassTimeData ()
Definition at line 1142 of file EnProfilerTests.c.
TestClearFlags()
TFResult TestClearFlags ()
Definition at line 881 of file EnProfilerTests.c.
TestFuncCountData()
TFResult TestFuncCountData ()
Definition at line 1305 of file EnProfilerTests.c.
TestFuncCountDataHelper()
void TestFuncCountDataHelper ()
Definition at line 1509 of file EnProfilerTests.c.
TestFuncCountDataHelperStatic()
static void TestFuncCountDataHelperStatic () static
Definition at line 1516 of file EnProfilerTests.c.
TestFuncTimeData()
TFResult TestFuncTimeData ()
Definition at line 1242 of file EnProfilerTests.c.
TestModule()
TFResult TestModule ()
Definition at line 950 of file EnProfilerTests.c.
TestSetFlags()
TFResult TestSetFlags ()
Definition at line 828 of file EnProfilerTests.c.
TestToggling()
TFResult TestToggling ()
Definition at line 798 of file EnProfilerTests.c.
TestTogglingImmediate()
TFResult TestTogglingImmediate ()
Definition at line 813 of file EnProfilerTests.c.
~EnProfilerTests()
void ~EnProfilerTests ()
Definition at line 789 of file EnProfilerTests.c.
Variable Documentation
m_bWasProfilerEnabled
bool m_bWasProfilerEnabled
Remember this, so we can restore the previous state before the test!
Definition at line 765 of file EnProfilerTests.c.