DayZ Scripts: ScriptInputUserData Class Reference
ScriptInputUserData Class Reference
Private Member Functions
void ScriptInputUserData ()
void ~ScriptInputUserData ()
proto native void Reset ()
proto native void Send ()
proto native bool CopyFrom (ParamsReadContext other)
Static Private Member Functions
proto static native bool CanStoreInputUserData ()
Detailed Description
Definition at line 120 of file gameplay.c.
Constructor & Destructor Documentation
ScriptInputUserData()
void ScriptInputUserData () private
~ScriptInputUserData()
void ~ScriptInputUserData () private
Member Function Documentation
CanStoreInputUserData()
proto static native bool CanStoreInputUserData () static private
Referenced by ActionManagerClient::ActionStart(), ManBase::CloseMapEx(), InventoryItem::CombineItemsClient(), HandleInventoryManipulation(), ActionBaseCB::Interrupt(), ManBase::OnQuickBarSingleUse(), InventoryItem::OnRightClick(), EntityAI::PredictiveDropEntity(), EntityAI::PredictiveForceSwapEntities(), EntityAI::PredictiveMoveItemFromHandsToInventory(), EntityAI::PredictiveSwapEntities(), EntityAI::PredictiveTakeEntityAsAttachment(), EntityAI::PredictiveTakeEntityAsAttachmentEx(), EntityAI::PredictiveTakeEntityToCargo(), EntityAI::PredictiveTakeEntityToHands(), EntityAI::PredictiveTakeEntityToInventory(), EntityAI::PredictiveTakeEntityToTargetAttachment(), EntityAI::PredictiveTakeEntityToTargetAttachmentEx(), EntityAI::PredictiveTakeEntityToTargetCargo(), EntityAI::PredictiveTakeEntityToTargetCargoEx(), EntityAI::PredictiveTakeEntityToTargetInventory(), EntityAI::PredictiveTakeToDst(), ActionManagerClient::ProcessActionInputEnd(), ActionManagerClient::ProcessActionRequestEnd(), ActionManagerClient::RequestInterruptAction(), ManBase::RequestResetADSSync(), SendEmoteRequestSync(), ManBase::SendLiftWeaponSync(), SetEntityShortcut(), InventoryItem::SplitIntoStackMaxCargoClient(), InventoryItem::SplitIntoStackMaxClient(), InventoryItem::SplitIntoStackMaxHandsClient(), InventoryItem::SplitIntoStackMaxToInventoryLocationClient(), WeaponManager::StartAction(), ScriptedWidgetEventHandler::ToggleMute(), ManBase::TogglePlacingLocal(), HumanInventory::Update(), and Update().
CopyFrom()
proto native bool CopyFrom (ParamsReadContext other) private
Referenced by ProcessInputData().
Reset()
proto native void Reset () private
Send()
proto native void Send () private
Referenced by ActionManagerClient::ActionStart(), InventoryItem::CombineItemsClient(), ActionBaseCB::Interrupt(), OnlineServices::MutePlayer(), InventoryItem::OnRightClick(), OnUpdate(), ActionManagerClient::ProcessActionInputEnd(), ActionManagerClient::ProcessActionRequestEnd(), ActionManagerClient::RequestInterruptAction(), ManBase::RequestResetADSSync(), SendEmoteRequestSync(), InventoryInputUserData::SendInputUserDataDestroy(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), ManBase::SendLiftWeaponSync(), SetEntityShortcut(), InventoryItem::SplitIntoStackMaxCargoClient(), InventoryItem::SplitIntoStackMaxClient(), InventoryItem::SplitIntoStackMaxHandsClient(), InventoryItem::SplitIntoStackMaxToInventoryLocationClient(), WeaponManager::Synchronize(), ManBase::TogglePlacingLocal(), HumanInventory::Update(), and Update().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/gameplay.c