DayZ Scripts: ActionCraftBolts Class Reference
ActionCraftBolts Class Reference
Private Member Functions
void InitCuttingTypes ()
void ActionCraftBolts ()
override void CreateConditionComponents ()
protected bool IsCuttingType (Object item)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Private Attributes
const ref set< string > CUTTING_TYPES = new set<string>()
protected bool m_IsKnifeInHands
protected Ammunition_Base m_ResultEntity
Detailed Description
Definition at line 11 of file ActionCraftBolts.c.
Constructor & Destructor Documentation
ActionCraftBolts()
void ActionCraftBolts () inline private
Definition at line 42 of file ActionCraftBolts.c.
References InitCuttingTypes(), AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 66 of file ActionCraftBolts.c.
References IsCuttingType().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 55 of file ActionCraftBolts.c.
References m_ConditionItem, and m_ConditionTarget.
InitCuttingTypes()
void InitCuttingTypes () inline private
Definition at line 18 of file ActionCraftBolts.c.
References CUTTING_TYPES.
Referenced by ActionCraftBolts().
IsCuttingType()
protected bool IsCuttingType (Object item) inline private
Definition at line 61 of file ActionCraftBolts.c.
References CUTTING_TYPES.
Referenced by ActionCondition(), and OnStartServer().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 89 of file ActionCraftBolts.c.
References m_IsKnifeInHands, ActionData::m_MainItem, ActionData::m_Player, m_ResultEntity, and ActionData::m_Target.
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
Definition at line 83 of file ActionCraftBolts.c.
References IsCuttingType(), m_IsKnifeInHands, ActionData::m_MainItem, and m_ResultEntity.
Field Documentation
CUTTING_TYPES
const ref set<string> CUTTING_TYPES = new set<string>() private
Definition at line 13 of file ActionCraftBolts.c.
Referenced by InitCuttingTypes(), and IsCuttingType().
m_IsKnifeInHands
protected bool m_IsKnifeInHands private
Definition at line 15 of file ActionCraftBolts.c.
Referenced by OnFinishProgressServer(), and OnStartServer().
m_ResultEntity
protected Ammunition_Base m_ResultEntity private
Definition at line 16 of file ActionCraftBolts.c.
Referenced by OnFinishProgressServer(), and OnStartServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionCraftBolts.c