DayZ Scripts: AttachmentCategoriesRow Class Reference
AttachmentCategoriesRow Class Reference
Private Member Functions
void AttachmentCategoriesRow (LayoutHolder parent, int sort=-1)
string GetCategoryIdentifier ()
int GetFocusedSlot ()
override bool Select ()
override bool TransferItem ()
override bool TransferItemToVicinity ()
override bool Combine ()
override bool CanSplitEx (EntityAI focusedItem)
override bool SplitItem ()
override bool EquipItem ()
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override void UnfocusAll ()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void DoubleClick (Widget w, int x, int y, int button)
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo)
void DropReceived (Widget w, int x, int y, CargoContainer cargo)
EntityAI GetItemPreviewItem (Widget w)
override void Refresh ()
void RefreshAllSlots ()
void RefreshSlot (int row, int column, int slot_id, string slot_name)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
void Init (int attachments_categories_count, int i, string attachment_category, string config_path_attachment_categories, EntityAI entity, int parent_m_Body_count)
override void UpdateInterval ()
Private Attributes
protected string m_CategoryIdentifier
protected string m_RowConfigPath
protected bool m_Refreshing
protected ref AttachmentsGroupContainer m_AttachmentsContainer
protected ref map< int, ref ContainerWithCargo > m_AttachmentCargos
Detailed Description
Definition at line 1 of file AttachmentCategoriesRow.c.
Constructor & Destructor Documentation
AttachmentCategoriesRow()
void AttachmentCategoriesRow (LayoutHolder parent, int sort = -1) inline private
Definition at line 10 of file AttachmentCategoriesRow.c.
References m_AttachmentCargos, m_AttachmentsContainer, and m_Refreshing.
Member Function Documentation
CanCombine()
override bool CanCombine () inline private
Definition at line 237 of file AttachmentCategoriesRow.c.
References ItemBase::CanBeCombined(), GetFocusedSlot(), GetGame(), CGame::GetPlayer(), InventoryLocation::GetSlot(), InventorySlots::GetStackMaxForSlotId(), SlotsIcon::IsOutOfReach(), and m_Entity.
CanCombineAmmo()
override bool CanCombineAmmo () inline private
Definition at line 282 of file AttachmentCategoriesRow.c.
CanSplitEx()
override bool CanSplitEx (EntityAI focusedItem) inline private
Definition at line 222 of file AttachmentCategoriesRow.c.
Combine()
override bool Combine () inline private
Definition at line 161 of file AttachmentCategoriesRow.c.
References ItemBase::CanBeCombined(), GameInventory::CanSwapEntitiesEx(), GetFocusedSlot(), GetGame(), CGame::GetPlayer(), InventoryLocation::GetSlot(), InventorySlots::GetStackMaxForSlotId(), SlotsIcon::IsOutOfReach(), m_AttachmentCargos, m_Entity, and SplitItemUtils::TakeOrSplitToInventory().
DoubleClick()
void DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 492 of file AttachmentCategoriesRow.c.
References g_Game, GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), m_Entity, name, and string::Replace().
DraggingOverGrid()
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo) inline private
Definition at line 572 of file AttachmentCategoriesRow.c.
References CargoBase::GetHeight(), GetItemPreviewItem(), CargoBase::GetWidth(), ColorManager::GREEN_COLOR, name, ColorManager::RED_COLOR, string::Replace(), x, and y.
DraggingOverHeader()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 412 of file AttachmentCategoriesRow.c.
References ItemBase::CanBeCombined(), GameInventory::CanSwapEntitiesEx(), ColorManager::COMBINE_COLOR, ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::GetLeftDropzone(), SlotsIcon::GetSlotID(), InventorySlots::GetStackMaxForSlotId(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_Entity, name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and ColorManager::SWAP_COLOR.
DropReceived()
void DropReceived (Widget w, int x, int y, CargoContainer cargo) inline private
Definition at line 635 of file AttachmentCategoriesRow.c.
References ColorManager::BASE_COLOR, GetGame(), CargoBase::GetHeight(), GetItemPreviewItem(), GetPlayer(), CargoBase::GetWidth(), Icon::Refresh(), Refresh(), Icon::RefreshPos(), InventoryLocation::SetCargoAuto(), SplitItemUtils::TakeOrSplitToInventoryLocation(), x, and y.
EquipItem()
override bool EquipItem () inline private
Definition at line 232 of file AttachmentCategoriesRow.c.
GetCategoryIdentifier()
string GetCategoryIdentifier () inline private
Definition at line 23 of file AttachmentCategoriesRow.c.
References m_CategoryIdentifier.
Referenced by AttachmentCategoriesContainer::CanDisplayAnyCategory(), and AttachmentCategoriesContainer::UpdateInterval().
GetFocusedSlot()
int GetFocusedSlot () inline private
Definition at line 28 of file AttachmentCategoriesRow.c.
References SlotsIcon::GetSlotID().
Referenced by CanCombine(), and Combine().
GetItemPreviewItem()
EntityAI GetItemPreviewItem (Widget w) inline private
Definition at line 686 of file AttachmentCategoriesRow.c.
References ItemPreviewWidget::GetItem(), name, and string::Replace().
Referenced by DraggingOverGrid(), DropReceived(), and OnDropReceivedFromHeader().
Init()
void Init (int attachments_categories_count, int i, string attachment_category, string config_path_attachment_categories, EntityAI entity, int parent_m_Body_count) inline private
Definition at line 882 of file AttachmentCategoriesRow.c.
References CGame::ConfigGetText(), CGame::ConfigGetTextArray(), Container::Get(), GetGame(), SlotsIcon::GetGhostSlot(), GetHeader(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), InventorySlots::GetSlotDisplayName(), SlotsContainer::GetSlotIcon(), InventorySlots::GetSlotIdFromString(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, ITEMS_IN_ROW, m_AttachmentsContainer, m_CategoryIdentifier, m_Entity, m_RowConfigPath, path, RefreshAllSlots(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDrop(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), AttachmentsGroupContainer::SetHeader(), Header::SetName(), SlotsIcon::SetSlotDisplayName(), SlotsIcon::SetSlotID(), and StaticGUIUtils::VerifyIconImageString().
Referenced by AttachmentCategoriesContainer::InitGhostSlots().
IsItemActive()
override bool IsItemActive () inline private
Definition at line 287 of file AttachmentCategoriesRow.c.
References SlotsIcon::IsOutOfReach().
IsItemWithQuantityActive()
override bool IsItemWithQuantityActive () inline private
Definition at line 293 of file AttachmentCategoriesRow.c.
References SlotsIcon::IsOutOfReach().
OnDropReceivedFromHeader()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 300 of file AttachmentCategoriesRow.c.
References GameInventory::CanSwapEntitiesEx(), Class::CastTo(), CombineItemsClient(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), GetItemPreviewItem(), CGame::GetPlayer(), GetPlayer(), InventoryLocation::GetSlot(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), ItemManager::HideDropzones(), SlotsIcon::IsReserved(), m_Entity, and ItemManager::SetIsDragging().
OnMouseButtonDown()
override bool OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 847 of file AttachmentCategoriesRow.c.
References Container::Close(), SlotsIcon::GetContainer(), GetDayZGame(), SlotsIcon::GetItem(), Container::Open(), x, and y.
Refresh()
override void Refresh () inline private
Definition at line 706 of file AttachmentCategoriesRow.c.
References m_Refreshing, and RefreshAllSlots().
Referenced by DropReceived().
RefreshAllSlots()
void RefreshAllSlots () inline private
Definition at line 718 of file AttachmentCategoriesRow.c.
References AttachmentsGroupContainer::GetColumnCountForRow(), AttachmentsGroupContainer::GetRowCount(), m_AttachmentsContainer, m_Refreshing, and RefreshSlot().
Referenced by Init(), Refresh(), and UpdateInterval().
RefreshSlot()
void RefreshSlot (int row, int column, int slot_id, string slot_name) inline private
Definition at line 736 of file AttachmentCategoriesRow.c.
References SlotsIcon::Clear(), ClosableContainer::ContainerWithCargo(), ItemManager::GetDraggedItem(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), SlotsIcon::GetMountedWidget(), SlotsIcon::GetOutOfReachWidget(), CGame::GetPlayer(), SlotsIcon::GetRadialIconPanel(), SlotsIcon::GetRender(), SlotsIcon::GetSlotID(), InventorySlots::GetSlotName(), AttachmentsGroupContainer::GetSlotsIcon(), SlotsIcon::Init(), AttachmentsOutOfReach::IsAttachmentReachable(), m_AttachmentCargos, m_AttachmentsContainer, m_Entity, SlotsIcon::Refresh(), Remove(), and SlotsIcon::SetContainer().
Referenced by RefreshAllSlots().
Select()
override bool Select () inline private
Definition at line 38 of file AttachmentCategoriesRow.c.
References GameInventory::CanSwapEntitiesEx(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), ItemManager::GetSelectedItem(), InventoryLocation::GetSlot(), SlotsIcon::GetSlotID(), InventorySlots::GetStackMaxForSlotId(), SlotsIcon::IsOutOfReach(), m_AttachmentCargos, m_Entity, EntityAI::PredictiveSwapEntities(), Container::Select(), and SplitItemUtils::TakeOrSplitToInventory().
SplitItem()
override bool SplitItem () inline private
Definition at line 227 of file AttachmentCategoriesRow.c.
TransferItem()
override bool TransferItem () inline private
Definition at line 131 of file AttachmentCategoriesRow.c.
References GetGame(), CGame::GetPlayer(), GetPlayer(), and SlotsIcon::IsOutOfReach().
TransferItemToVicinity()
override bool TransferItemToVicinity () inline private
Definition at line 144 of file AttachmentCategoriesRow.c.
References GetGame(), GetPlayer(), and SlotsIcon::IsOutOfReach().
UnfocusAll()
override void UnfocusAll () inline private
Definition at line 393 of file AttachmentCategoriesRow.c.
References Count, Get(), ITEMS_IN_ROW, and m_AttachmentCargos.
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 958 of file AttachmentCategoriesRow.c.
References RefreshAllSlots().
Referenced by AttachmentCategoriesContainer::UpdateInterval().
Field Documentation
m_AttachmentCargos
protected ref map<int, ref ContainerWithCargo> m_AttachmentCargos private
Definition at line 8 of file AttachmentCategoriesRow.c.
Referenced by AttachmentCategoriesRow(), Combine(), RefreshSlot(), Select(), and UnfocusAll().
m_AttachmentsContainer
protected ref AttachmentsGroupContainer m_AttachmentsContainer private
Definition at line 7 of file AttachmentCategoriesRow.c.
Referenced by AttachmentCategoriesRow(), Init(), RefreshAllSlots(), and RefreshSlot().
m_CategoryIdentifier
protected string m_CategoryIdentifier private
Definition at line 3 of file AttachmentCategoriesRow.c.
Referenced by GetCategoryIdentifier(), and Init().
m_Refreshing
protected bool m_Refreshing private
Definition at line 5 of file AttachmentCategoriesRow.c.
Referenced by AttachmentCategoriesRow(), Refresh(), and RefreshAllSlots().
m_RowConfigPath
protected string m_RowConfigPath private
Definition at line 4 of file AttachmentCategoriesRow.c.
Referenced by Init().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Inherited/AttachmentCategoriesRow.c