DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionPushCar.c File Reference
ActionPushCar.c File Reference
Data Structures
class ActionPushCarDataReceiveData
class CAContinuousRepeatPushCar
class ActionPushCar
Functions
override void CreateActionComponent ()
override void ProgressActionComponent ()
override void EndActionComponent ()
protected void ApplyForce (ActionPushCarData actionData)
Variables
ActionPushCarDataReceiveData m_PushDirection = -1
int m_EndType = 0
float m_HorizontalDirectionRandom = 1.0
float m_VerticalDirectionRandom = 1.0
vector m_Origin = "0 0 0"
bool m_NeedUpdate
CarScript m_Car
CAContinuousRepeatPushCar PUSH_FORCE_IMPULSE_INCREMENT = 200.0
private ActionPushCarData m_ActionDataPushCar
Function Documentation
ApplyForce()
protected void ApplyForce (ActionPushCarData actionData)
References dBodyApplyImpulseAt(), dBodyGetMass(), Easing::EaseInOutSine(), CarScript::GetPushForceCoefficientMultiplier(), PUSH_FORCE_IMPULSE_INCREMENT, and Math::RandomFloat().
Referenced by ProgressActionComponent().
CreateActionComponent()
override void CreateActionComponent ()
EndActionComponent()
override void EndActionComponent ()
References ActionContinuousBase::HasAlternativeInterrupt(), m_ActionDataPushCar, ActionBaseCB::SetCommand(), UA_CANCEL, and UA_FINISHED.
ProgressActionComponent()
override void ProgressActionComponent ()
References ApplyForce().
Variable Documentation
m_ActionDataPushCar
private ActionPushCarData m_ActionDataPushCar
Referenced by EndActionComponent().
m_Car
CarScript m_Car
m_EndType
int m_EndType = 0
m_HorizontalDirectionRandom
float m_HorizontalDirectionRandom = 1.0
m_NeedUpdate
bool m_NeedUpdate
m_Origin
vector m_Origin = "0 0 0"
m_PushDirection
ActionPushCarDataReceiveData m_PushDirection = -1
m_VerticalDirectionRandom
float m_VerticalDirectionRandom = 1.0
PUSH_FORCE_IMPULSE_INCREMENT
CAContinuousRepeatPushCar PUSH_FORCE_IMPULSE_INCREMENT = 200.0
Referenced by ApplyForce().