DayZ Scripts: CAContinuousBase Class Reference
CAContinuousBase Class Reference
Private Member Functions
override bool IsContinuousAction ()
void OnCompletePogress (ActionData action_data)
Member Function Documentation
IsContinuousAction()
override bool IsContinuousAction () inline private
OnCompletePogress()
void OnCompletePogress (ActionData action_data) inline private
References ActionContinuousBase::OnFinishProgress().
Referenced by CAContinuousCraft::Execute(), CAContinuousDisinfectPlant::Execute(), CAContinuousEmpty::Execute(), CAContinuousEmptyMagazine::Execute(), CAContinuousFertilizeGardenSlot::Execute(), CAContinuousFill::Execute(), CAContinuousFillBrakes::Execute(), CAContinuousFillCoolant::Execute(), CAContinuousFillFuel::Execute(), CAContinuousFillOil::Execute(), CAContinuousFillPowerGenerator::Execute(), CAContinuousMineWood::Execute(), CAContinuousQuantity::Execute(), CAContinuousQuantityLiquidTransfer::Execute(), CAContinuousQuantityRepeat::Execute(), CAContinuousRepeat::Execute(), CAContinuousRepeatFishing::Execute(), CAContinuousRepeatStartEngine::Execute(), CAContinuousTime::Execute(), CAContinuousTimeCooking::Execute(), CAContinuousTransferQuantity::Execute(), CAContinuousWaterPlant::Execute(), CAContinuousWaterSlot::Execute(), CAContinuousWringClothes::Execute(), and CAContinuousRepeatPushObject::Execute().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/ActionComponents/CAContinuousBase.c