DayZ Scripts: PlayerPreview Class Reference
PlayerPreview Class Reference
Private Member Functions
void PlayerPreview (LayoutHolder parent)
void RefreshPlayerPreview ()
void UpdateRotation (int mouse_x, int mouse_y, bool is_dragging)
void UpdateScale ()
bool MouseButtonDown (Widget w, int x, int y, int button)
bool MouseWheel (Widget w, int x, int y, int wheel)
override void UpdateInterval ()
Private Attributes
protected ref PlayerPreviewWidget m_CharacterPanelWidget
protected int m_CharacterRotationX
protected int m_CharacterRotationY
protected int m_CharacterScaleDelta
protected vector m_CharacterOrientation
protected bool m_IsHolding
Constructor & Destructor Documentation
PlayerPreview()
void PlayerPreview (LayoutHolder parent) inline private
References GetGame(), WidgetEventHandler::GetInstance(), GetPlayer(), m_CharacterPanelWidget, m_CharacterScaleDelta, m_Parent, WidgetEventHandler::RegisterOnMouseButtonDown(), WidgetEventHandler::RegisterOnMouseWheel(), PlayerPreviewWidget::SetModelPosition(), PlayerPreviewWidget::SetPlayer(), and UpdateScale().
Member Function Documentation
MouseButtonDown()
bool MouseButtonDown (Widget w, int x, int y, int button) inline private
References GetMousePos(), m_CharacterRotationX, m_CharacterRotationY, and m_IsHolding.
MouseWheel()
bool MouseWheel (Widget w, int x, int y, int wheel) inline private
References m_CharacterScaleDelta, and UpdateScale().
RefreshPlayerPreview()
void RefreshPlayerPreview () inline private
References m_CharacterPanelWidget, and PlayerPreviewWidget::Refresh().
Referenced by OnShow().
UpdateInterval()
override void UpdateInterval () inline private
References PlayerPreviewWidget::GetDummyPlayer(), GetGame(), GetMousePos(), GetMouseState(), GetPlayer(), HumanCommandAdditives(), m_CharacterPanelWidget, m_IsHolding, PlayerPreviewWidget::UpdateItemInHands(), and UpdateRotation().
Referenced by UpdateInterval().
UpdateRotation()
void UpdateRotation (int mouse_x, int mouse_y, bool is_dragging) inline private
References m_CharacterOrientation, m_CharacterPanelWidget, m_CharacterRotationX, and PlayerPreviewWidget::SetModelOrientation().
Referenced by UpdateInterval().
UpdateScale()
void UpdateScale () inline private
References m_CharacterPanelWidget, and m_CharacterScaleDelta.
Referenced by MouseWheel(), and PlayerPreview().
Field Documentation
m_CharacterOrientation
protected vector m_CharacterOrientation private
Referenced by UpdateRotation().
m_CharacterPanelWidget
protected ref PlayerPreviewWidget m_CharacterPanelWidget private
Referenced by PlayerPreview(), RefreshPlayerPreview(), UpdateInterval(), UpdateRotation(), and UpdateScale().
m_CharacterRotationX
protected int m_CharacterRotationX private
Referenced by MouseButtonDown(), and UpdateRotation().
m_CharacterRotationY
protected int m_CharacterRotationY private
Referenced by MouseButtonDown().
m_CharacterScaleDelta
protected int m_CharacterScaleDelta private
Referenced by MouseWheel(), PlayerPreview(), and UpdateScale().
m_IsHolding
protected bool m_IsHolding private
Referenced by MouseButtonDown(), and UpdateInterval().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/PlayerPreview.c