DayZ Scripts: NotifierBase Class Reference
NotifierBase Class Reference
Private Member Functions
void NotifierBase (NotifiersManager manager)
bool IsTimeToTick (int current_time)
VirtualHud GetVirtualHud ()
int GetNotifierType ()
string GetName ()
bool IsActive ()
void SetActive (bool state)
void DisplayTendency (float delta)
void AddToCyclicBuffer (float value)
float ReadFromCyclicBuffer (int index)
float GetDeltaAvaraged ()
void SmoothOutFloatValues (array< float > values)
void OnTick (float current_time)
protected int CalculateTendency (float delta, float inctresholdlow, float inctresholdmed, float inctresholdhigh, float dectresholdlow, float dectresholdmed, float dectresholdhigh)
protected eBadgeLevel DetermineBadgeLevel (float value, float lvl_1, float lvl_2, float lvl_3)
protected void DisplayBadge ()
protected void HideBadge ()
protected float GetObservedValue ()
Private Attributes
float m_DeltaT
ref Timer m_Timer1
PlayerBase m_Player
int m_Type
NotifiersManager m_Manager
int m_TendencyBufferSize = 3
const int TENDENCY_BUFFER_SIZE = 30
bool m_ShowTendency
bool m_Active
int m_TickInterval
int m_TickIntervalLastTick
float m_TendencyBuffer [TENDENCY_BUFFER_SIZE]
int m_TendencyBufferWriteIterator
float m_LastTendency
float m_LastMA
bool m_FirstPass = true
PluginPlayerStatus m_ModulePlayerStatus
Detailed Description
Definition at line 1 of file NotifierBase.c.
Constructor & Destructor Documentation
NotifierBase()
void NotifierBase (NotifiersManager manager) inline private
Definition at line 31 of file NotifierBase.c.
References GetNotifierType(), GetPlugin(), m_Active, m_Manager, m_ModulePlayerStatus, m_Player, and m_TickInterval.
Member Function Documentation
AddToCyclicBuffer()
void AddToCyclicBuffer (float value) inline private
Definition at line 79 of file NotifierBase.c.
References m_ShowTendency, m_TendencyBuffer, m_TendencyBufferSize, and m_TendencyBufferWriteIterator.
Referenced by OnTick().
CalculateTendency()
protected int CalculateTendency (float delta, float inctresholdlow, float inctresholdmed, float inctresholdhigh, float dectresholdlow, float dectresholdmed, float dectresholdhigh) inline private
Definition at line 171 of file NotifierBase.c.
References TENDENCY_DEC_HIGH, TENDENCY_DEC_LOW, TENDENCY_DEC_MED, TENDENCY_INC_HIGH, TENDENCY_INC_LOW, TENDENCY_INC_MED, and TENDENCY_STABLE.
Referenced by BloodNotfr::DisplayTendency(), HealthNotfr::DisplayTendency(), HungerNotfr::DisplayTendency(), ThirstNotfr::DisplayTendency(), and WarmthNotfr::DisplayTendency().
DetermineBadgeLevel()
protected eBadgeLevel DetermineBadgeLevel (float value, float lvl_1, float lvl_2, float lvl_3) inline private
Definition at line 185 of file NotifierBase.c.
Referenced by InjuredLegNotfr::DisplayBadge(), and StuffedNotfr::DisplayBadge().
DisplayBadge()
protected void DisplayBadge () inline private
Definition at line 195 of file NotifierBase.c.
Referenced by OnTick().
DisplayTendency()
void DisplayTendency (float delta) inline private
Definition at line 75 of file NotifierBase.c.
Referenced by OnTick().
GetDeltaAvaraged()
float GetDeltaAvaraged () inline private
Definition at line 100 of file NotifierBase.c.
References m_FirstPass, m_LastMA, m_TendencyBufferSize, and ReadFromCyclicBuffer().
Referenced by OnTick().
GetName()
string GetName () inline private
Definition at line 59 of file NotifierBase.c.
GetNotifierType()
int GetNotifierType () inline private
Definition at line 54 of file NotifierBase.c.
References m_Type.
Referenced by NotifierBase().
GetObservedValue()
protected float GetObservedValue () inline private
Definition at line 203 of file NotifierBase.c.
Referenced by OnTick().
GetVirtualHud()
VirtualHud GetVirtualHud () inline private
Definition at line 49 of file NotifierBase.c.
References m_Player.
Referenced by BleedingNotfr::DisplayBadge(), FracturedLegNotfr::DisplayBadge(), HeartbeatNotfr::DisplayBadge(), InjuredLegNotfr::DisplayBadge(), PillsNotfr::DisplayBadge(), SickNotfr::DisplayBadge(), StuffedNotfr::DisplayBadge(), WetnessNotfr::DisplayBadge(), BloodNotfr::DisplayTendency(), HealthNotfr::DisplayTendency(), HungerNotfr::DisplayTendency(), ThirstNotfr::DisplayTendency(), WarmthNotfr::DisplayTendency(), BleedingNotfr::HideBadge(), FracturedLegNotfr::HideBadge(), HeartbeatNotfr::HideBadge(), InjuredLegNotfr::HideBadge(), PillsNotfr::HideBadge(), SickNotfr::HideBadge(), StuffedNotfr::HideBadge(), and WetnessNotfr::HideBadge().
HideBadge()
protected void HideBadge () inline private
Definition at line 199 of file NotifierBase.c.
Referenced by SetActive().
IsActive()
bool IsActive () inline private
Definition at line 64 of file NotifierBase.c.
References m_Active.
IsTimeToTick()
bool IsTimeToTick (int current_time) inline private
Definition at line 43 of file NotifierBase.c.
References m_TickInterval, and m_TickIntervalLastTick.
OnTick()
void OnTick (float current_time) inline private
Definition at line 156 of file NotifierBase.c.
References AddToCyclicBuffer(), DisplayBadge(), DisplayTendency(), GetDeltaAvaraged(), GetObservedValue(), m_ShowTendency, and m_TickIntervalLastTick.
ReadFromCyclicBuffer()
float ReadFromCyclicBuffer (int index) inline private
Definition at line 90 of file NotifierBase.c.
References m_TendencyBuffer, m_TendencyBufferSize, and m_TendencyBufferWriteIterator.
Referenced by GetDeltaAvaraged().
SetActive()
void SetActive (bool state) inline private
Definition at line 69 of file NotifierBase.c.
References HideBadge(), and m_Active.
Referenced by ActivateByType(), and DeactivateByType().
SmoothOutFloatValues()
void SmoothOutFloatValues (array< float > values) inline private
Definition at line 140 of file NotifierBase.c.
Field Documentation
m_Active
bool m_Active private
Definition at line 12 of file NotifierBase.c.
Referenced by BleedingNotfr::BleedingNotfr(), FeverNotfr::FeverNotfr(), FracturedLegNotfr::FracturedLegNotfr(), HeartbeatNotfr::HeartbeatNotfr(), InjuredLegNotfr::InjuredLegNotfr(), IsActive(), NotifierBase(), PillsNotfr::PillsNotfr(), SetActive(), SickNotfr::SickNotfr(), StuffedNotfr::StuffedNotfr(), and WetnessNotfr::WetnessNotfr().
m_DeltaT
float m_DeltaT private
Definition at line 4 of file NotifierBase.c.
m_FirstPass
bool m_FirstPass = true private
Definition at line 26 of file NotifierBase.c.
Referenced by GetDeltaAvaraged().
m_LastMA
float m_LastMA private
Definition at line 25 of file NotifierBase.c.
Referenced by GetDeltaAvaraged().
m_LastTendency
float m_LastTendency private
Definition at line 24 of file NotifierBase.c.
m_Manager
NotifiersManager m_Manager private
Definition at line 8 of file NotifierBase.c.
Referenced by NotifierBase().
m_ModulePlayerStatus
PluginPlayerStatus m_ModulePlayerStatus private
Definition at line 29 of file NotifierBase.c.
Referenced by NotifierBase().
m_Player
PlayerBase m_Player private
Definition at line 6 of file NotifierBase.c.
Referenced by HeartbeatNotfr::DisplayBadge(), InjuredLegNotfr::DisplayBadge(), StuffedNotfr::DisplayBadge(), ThirstNotfr::DisplayBadge(), BloodNotfr::DisplayTendency(), HealthNotfr::DisplayTendency(), HungerNotfr::DisplayTendency(), ThirstNotfr::DisplayTendency(), BloodNotfr::GetObservedValue(), HealthNotfr::GetObservedValue(), HungerNotfr::GetObservedValue(), ThirstNotfr::GetObservedValue(), WarmthNotfr::GetObservedValue(), GetVirtualHud(), and NotifierBase().
m_ShowTendency
bool m_ShowTendency private
Definition at line 11 of file NotifierBase.c.
Referenced by AddToCyclicBuffer(), and OnTick().
m_TendencyBuffer
float m_TendencyBuffer[TENDENCY_BUFFER_SIZE] private
Definition at line 22 of file NotifierBase.c.
Referenced by AddToCyclicBuffer(), and ReadFromCyclicBuffer().
m_TendencyBufferSize
int m_TendencyBufferSize = 3 private
Definition at line 9 of file NotifierBase.c.
Referenced by AddToCyclicBuffer(), BleedingNotfr::BleedingNotfr(), GetDeltaAvaraged(), HealthNotfr::HealthNotfr(), ReadFromCyclicBuffer(), and WarmthNotfr::WarmthNotfr().
m_TendencyBufferWriteIterator
int m_TendencyBufferWriteIterator private
Definition at line 23 of file NotifierBase.c.
Referenced by AddToCyclicBuffer(), and ReadFromCyclicBuffer().
m_TickInterval
int m_TickInterval private
Definition at line 20 of file NotifierBase.c.
Referenced by HealthNotfr::HealthNotfr(), IsTimeToTick(), and NotifierBase().
m_TickIntervalLastTick
int m_TickIntervalLastTick private
Definition at line 21 of file NotifierBase.c.
Referenced by IsTimeToTick(), and OnTick().
m_Timer1
ref Timer m_Timer1 private
Definition at line 5 of file NotifierBase.c.
m_Type
int m_Type private
Definition at line 7 of file NotifierBase.c.
Referenced by GetNotifierType().
TENDENCY_BUFFER_SIZE
const int TENDENCY_BUFFER_SIZE = 30 private
Definition at line 10 of file NotifierBase.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerNotifiers/NotifierBase.c