DayZ Scripts: EntityLightSource Class Reference
EntityLightSource Class Reference
Private Member Functions
void ScriptedLightBase ()
Constructor. Everything here is executed before the constructor of all children.
void ~ScriptedLightBase ()
override void EOnInit (IEntity other, int extra)
override bool IsScriptedLight ()
void UpdateMode ()
private void UpdateLightMode (string slotName)
private void DeleteLightWithDelay ()
Correct way of deleting light from memory. It is necesarry to have this delay due to hierarchy.
private void DeleteLightNow ()
void AttachOnObject (Object parent, vector local_pos="0 0 0", vector local_ori="0 0 0")
Attaches this light on the parent entity, with optional position and orientation offset.
Object GetAttachmentParent ()
Returns attachment parent.
void AttachOnMemoryPoint (Object parent, string memory_point_start, string memory_point_target="")
Attaches this light on the parent entity's memory point, with optional direction target memory point.
void DetachFromParent ()
Detaches this light from its parent entity.
void SetBrightnessTo (float value)
Sets the brightness of the light.
void CorrectLightPulseDuringDaylight ()
Call this after using SetBrightness(...) to fix light's intensity during daytime.
void FadeBrightnessTo (float value, float time_in_s)
Fades the brightness of the light to the given value.
void SetRadiusTo (float value)
Sets the radius of the light.
void FadeRadiusTo (float value, float time_in_s)
Fades the radius of the light to the given value.
void Destroy ()
Switches off the light and deletes it from memory.
void SetLifetime (float life_in_s)
Makes the light destroy itself after the given time in seconds. The light will fade out if it's set to do so with SetFadeOutTime(...)
void SetFadeOutTime (float time_in_s)
Sets the fade out time in seconds. Fade out begins automatically as the light nears the end of its life time, or when method FadeOut() is called.
void FadeOut (float time_in_s=-1)
Starts the fade out process and destroys the light when its done. Optional parameter allows you to set time of this fade out in seconds. If not set, then default value (from SetFadeOutTime(...)) is used.
void FadeIn (float time_in_s)
Makes the light fade into existence. Works only at the moment the light is created. Consider using FadeBrightnessTo(...) and FadeRadiusTo(...) at anytime later during lifetime.
void AddLifetime (float life_in_s)
Prolongs the lifetime of the light in seconds. Use negative number to shorten its lifetime.
void OnFrameLightSource (IEntity other, float timeSlice)
Override this for custom functionality.
override void EOnFrame (IEntity other, float timeSlice)
On frame event. If you want to control your light within your own rules then override the event OnFrameLightSource and put your code there.
void SetDancingShadowsAmplitude (float max_deviation_in_meters)
Sets the maximum range of the point light within the dancing shadows effect.
void SetDancingShadowsMovementSpeed (float speed_in_meters_per_frame)
Sets the maximum speed of the point light within the dancing shadows effect.
float GetDancingShadowsAmplitude ()
Returns max movement range of pointlight within the dancing shadow effect.
float GetDancingShadowsMovementSpeed ()
Returns max movement speed of pointlight within the dancing shadow effect.
void EnableDebug (bool state)
Enables some debug functionality of this light.
void HandleDancingShadows (float time, float timeSlice)
void HandleFlickering (float time, float timeSlice)
void SetFlickerSpeed (float speed)
Sets speed of light flickering (random brightness coefficient change per second)
void SetFlickerAmplitude (float coef)
Sets the change coefficient of flickering light. (0.0 - 1.0 values, result of greater values are period time of light off)
void SetFlickerAmplitudeMax (float coef)
void SetFlickerAmplitudeMin (float coef)
float GetFlickerSpeed ()
Returns flicker speed.
float GetFlickerAmplitudeCoefMax ()
Returns flicker amplitude maximum.
float GetFlickerAmplitudeCoefMin ()
Returns flicker amplitude minimum.
void TryShadowOptimization ()
Optimizes shadows by disabling them on this light source while it's within the given radius around the camera.
void SetDisableShadowsWithinRadius (float radius_in_m)
When the light source gets within this radius (radius_in_m) around the camera, then it's shadows are disabled.
float GetDisableShadowsWithinRadius ()
Returns the range you put inside SetDisableShadowsWithinRadius(...)
void CheckIfParentIsInCargo ()
private bool CheckLifetime (int current_time)
private void CheckFadeOut (int current_time)
private void HandleBrightnessFadeing (float timeSlice)
private void HandleRadiusFadeing (float timeSlice)
void SetBlinkingSpeed (float _speed)
Sets blinking speed (no blinking if speed <= 0)
float GetBlinkingSpeed ()
Returns the speed of blinks.
private void HandleBlinking (float time)
Static Private Member Functions
static ScriptedLightBase CreateLightAtObjMemoryPoint (typename name, notnull Object target, string memory_point_start, string memory_point_target="", vector global_pos="0 0 0", float fade_in_time_in_s=0)
static ScriptedLightBase CreateLight (typename name, vector global_pos="0 0 0", float fade_in_time_in_s=0)
Creates an instance of light on the given position. Optionally, use fade_in_time_in_s parameter to make the light fade into existence.
Private Attributes
float m_LifetimeStart
float m_LifetimeEnd = -1
float m_FadeOutTime = -1
float m_FadeInTime = -1
float m_Radius
float m_RadiusTarget
float m_Brightness
float m_BrightnessPulse
float m_BrightnessPulseSpeed
float m_BrightnessPulseAmplitudeMax
float m_BrightnessPulseAmplitudeMin
float m_BrightnessTarget
float m_BrightnessSpeedOfChange = 1
float m_RadiusSpeedOfChange = 1
float m_OptimizeShadowsRadius = 0
float m_DancingShadowsAmplitude
float m_DancingShadowsSpeed
float m_BlinkingSpeed
bool m_IsDebugEnabled = false
Object m_Parent
vector m_LocalPos
vector m_LocalOri
vector m_DancingShadowsLocalPos
ref Timer m_DeleteTimer
Static Private Attributes
static ref set< ScriptedLightBase > m_NightTimeOnlyLights = new set<ScriptedLightBase>()
Detailed Description
Definition at line 10 of file ScriptedLightBase.c.
Constructor & Destructor Documentation
~ScriptedLightBase()
void ~ScriptedLightBase () inline private
Definition at line 53 of file ScriptedLightBase.c.
Member Function Documentation
AddLifetime()
void AddLifetime (float life_in_s) inline private
Prolongs the lifetime of the light in seconds. Use negative number to shorten its lifetime.
Definition at line 374 of file ScriptedLightBase.c.
AttachOnMemoryPoint()
void AttachOnMemoryPoint (Object parent, string memory_point_start, string memory_point_target = "") inline private
Attaches this light on the parent entity's memory point, with optional direction target memory point.
Definition at line 160 of file ScriptedLightBase.c.
References vector::Direction(), ErrorEx, m_LocalPos, and vector::VectorToAngles().
AttachOnObject()
void AttachOnObject (Object parent, vector local_pos = "0 0 0", vector local_ori = "0 0 0") inline private
Attaches this light on the parent entity, with optional position and orientation offset.
Definition at line 125 of file ScriptedLightBase.c.
References m_LocalOri, m_LocalPos, m_Parent, SetOrientation(), and SetPosition().
CheckFadeOut()
private void CheckFadeOut (int current_time) inline private
Definition at line 626 of file ScriptedLightBase.c.
CheckIfParentIsInCargo()
void CheckIfParentIsInCargo () inline private
Definition at line 574 of file ScriptedLightBase.c.
References GameInventory::IsInCargo(), and m_Parent.
CheckLifetime()
private bool CheckLifetime (int current_time) inline private
Definition at line 614 of file ScriptedLightBase.c.
References Destroy().
CorrectLightPulseDuringDaylight()
void CorrectLightPulseDuringDaylight () inline private
Call this after using SetBrightness(...) to fix light's intensity during daytime.
Definition at line 262 of file ScriptedLightBase.c.
CreateLight()
static ScriptedLightBase CreateLight (typename name , vector global_pos = "0 0 0", float fade_in_time_in_s = 0) inline static private
Creates an instance of light on the given position. Optionally, use fade_in_time_in_s parameter to make the light fade into existence.
Definition at line 222 of file ScriptedLightBase.c.
References Error(), GetGame(), name, and string::ToString().
CreateLightAtObjMemoryPoint()
static ScriptedLightBase CreateLightAtObjMemoryPoint (typename name , notnull Object target, string memory_point_start, string memory_point_target = "", vector global_pos = "0 0 0", float fade_in_time_in_s = 0) inline static private
Definition at line 210 of file ScriptedLightBase.c.
References CreateLight(), and name.
DeleteLightNow()
private void DeleteLightNow () inline private
Definition at line 119 of file ScriptedLightBase.c.
References GetGame(), and CGame::ObjectDelete().
DeleteLightWithDelay()
private void DeleteLightWithDelay () inline private
Correct way of deleting light from memory. It is necesarry to have this delay due to hierarchy.
Definition at line 104 of file ScriptedLightBase.c.
References CALL_CATEGORY_SYSTEM, GetGame(), and m_DeleteTimer.
Destroy()
void Destroy () inline private
Switches off the light and deletes it from memory.
Definition at line 321 of file ScriptedLightBase.c.
References m_Parent.
DetachFromParent()
void DetachFromParent () inline private
Detaches this light from its parent entity.
Definition at line 190 of file ScriptedLightBase.c.
References GetParent(), m_LocalOri, m_LocalPos, m_Parent, ToDelete(), and Vector().
EnableDebug()
void EnableDebug (bool state) inline private
Enables some debug functionality of this light.
Definition at line 438 of file ScriptedLightBase.c.
EOnFrame()
override void EOnFrame (IEntity other, float timeSlice) inline private
On frame event. If you want to control your light within your own rules then override the event OnFrameLightSource and put your code there.
Definition at line 386 of file ScriptedLightBase.c.
References GetGame(), CGame::GetTime(), and m_Radius.
EOnInit()
override void EOnInit (IEntity other, int extra) inline private
Definition at line 65 of file ScriptedLightBase.c.
References GetGame(), and GetPlayer().
FadeBrightnessTo()
void FadeBrightnessTo (float value, float time_in_s) inline private
Fades the brightness of the light to the given value.
Definition at line 283 of file ScriptedLightBase.c.
References Math::AbsFloat().
FadeIn()
void FadeIn (float time_in_s) inline private
Makes the light fade into existence. Works only at the moment the light is created. Consider using FadeBrightnessTo(...) and FadeRadiusTo(...) at anytime later during lifetime.
Definition at line 366 of file ScriptedLightBase.c.
FadeOut()
void FadeOut (float time_in_s = -1) inline private
Starts the fade out process and destroys the light when its done. Optional parameter allows you to set time of this fade out in seconds. If not set, then default value (from SetFadeOutTime(...)) is used.
Definition at line 345 of file ScriptedLightBase.c.
FadeRadiusTo()
void FadeRadiusTo (float value, float time_in_s) inline private
Fades the radius of the light to the given value.
Definition at line 306 of file ScriptedLightBase.c.
References Math::AbsFloat(), and m_Radius.
GetAttachmentParent()
Object GetAttachmentParent () inline private
Returns attachment parent.
Definition at line 154 of file ScriptedLightBase.c.
References m_Parent.
GetBlinkingSpeed()
float GetBlinkingSpeed () inline private
Returns the speed of blinks.
Definition at line 710 of file ScriptedLightBase.c.
GetDancingShadowsAmplitude()
float GetDancingShadowsAmplitude () inline private
Returns max movement range of pointlight within the dancing shadow effect.
Definition at line 426 of file ScriptedLightBase.c.
GetDancingShadowsMovementSpeed()
float GetDancingShadowsMovementSpeed () inline private
Returns max movement speed of pointlight within the dancing shadow effect.
Definition at line 432 of file ScriptedLightBase.c.
GetDisableShadowsWithinRadius()
float GetDisableShadowsWithinRadius () inline private
Returns the range you put inside SetDisableShadowsWithinRadius(...)
Definition at line 569 of file ScriptedLightBase.c.
GetFlickerAmplitudeCoefMax()
float GetFlickerAmplitudeCoefMax () inline private
Returns flicker amplitude maximum.
Definition at line 533 of file ScriptedLightBase.c.
GetFlickerAmplitudeCoefMin()
float GetFlickerAmplitudeCoefMin () inline private
Returns flicker amplitude minimum.
Definition at line 539 of file ScriptedLightBase.c.
GetFlickerSpeed()
float GetFlickerSpeed () inline private
Returns flicker speed.
Definition at line 527 of file ScriptedLightBase.c.
HandleBlinking()
private void HandleBlinking (float time) inline private
Definition at line 716 of file ScriptedLightBase.c.
References Math::Round(), and Math::Sin().
HandleBrightnessFadeing()
private void HandleBrightnessFadeing (float timeSlice) inline private
Definition at line 640 of file ScriptedLightBase.c.
References Destroy().
HandleDancingShadows()
void HandleDancingShadows (float time, float timeSlice) inline private
Definition at line 444 of file ScriptedLightBase.c.
References ParticleList::DEBUG_DOT, GetPosition, m_LocalPos, m_Parent, ParticleManager(), Math::RandomFloat(), Particle::SetParticleParam(), SetPosition(), and Vector().
HandleFlickering()
void HandleFlickering (float time, float timeSlice) inline private
Definition at line 484 of file ScriptedLightBase.c.
References Math::RandomFloat().
HandleRadiusFadeing()
private void HandleRadiusFadeing (float timeSlice) inline private
Definition at line 673 of file ScriptedLightBase.c.
References Destroy(), and m_Radius.
IsScriptedLight()
override bool IsScriptedLight () inline private
Definition at line 76 of file ScriptedLightBase.c.
OnFrameLightSource()
void OnFrameLightSource (IEntity other, float timeSlice) inline private
Override this for custom functionality.
Definition at line 380 of file ScriptedLightBase.c.
ScriptedLightBase()
void ScriptedLightBase () inline private
Constructor. Everything here is executed before the constructor of all children.
Definition at line 45 of file ScriptedLightBase.c.
References GetGame(), and CGame::GetTime().
SetBlinkingSpeed()
void SetBlinkingSpeed (float _speed) inline private
Sets blinking speed (no blinking if speed <= 0)
Definition at line 704 of file ScriptedLightBase.c.
SetBrightnessTo()
void SetBrightnessTo (float value) inline private
Sets the brightness of the light.
Definition at line 253 of file ScriptedLightBase.c.
SetDancingShadowsAmplitude()
void SetDancingShadowsAmplitude (float max_deviation_in_meters) inline private
Sets the maximum range of the point light within the dancing shadows effect.
Definition at line 414 of file ScriptedLightBase.c.
References Math::AbsFloat().
SetDancingShadowsMovementSpeed()
void SetDancingShadowsMovementSpeed (float speed_in_meters_per_frame) inline private
Sets the maximum speed of the point light within the dancing shadows effect.
Definition at line 420 of file ScriptedLightBase.c.
References Math::AbsFloat().
SetDisableShadowsWithinRadius()
void SetDisableShadowsWithinRadius (float radius_in_m) inline private
When the light source gets within this radius (radius_in_m) around the camera, then it's shadows are disabled.
Definition at line 563 of file ScriptedLightBase.c.
SetFadeOutTime()
void SetFadeOutTime (float time_in_s) inline private
Sets the fade out time in seconds. Fade out begins automatically as the light nears the end of its life time, or when method FadeOut() is called.
Definition at line 339 of file ScriptedLightBase.c.
SetFlickerAmplitude()
void SetFlickerAmplitude (float coef) inline private
Sets the change coefficient of flickering light. (0.0 - 1.0 values, result of greater values are period time of light off)
Definition at line 510 of file ScriptedLightBase.c.
References Math::AbsFloat().
SetFlickerAmplitudeMax()
void SetFlickerAmplitudeMax (float coef) inline private
Definition at line 516 of file ScriptedLightBase.c.
SetFlickerAmplitudeMin()
void SetFlickerAmplitudeMin (float coef) inline private
Definition at line 521 of file ScriptedLightBase.c.
SetFlickerSpeed()
void SetFlickerSpeed (float speed) inline private
Sets speed of light flickering (random brightness coefficient change per second)
Definition at line 504 of file ScriptedLightBase.c.
SetLifetime()
void SetLifetime (float life_in_s) inline private
Makes the light destroy itself after the given time in seconds. The light will fade out if it's set to do so with SetFadeOutTime(...)
Definition at line 332 of file ScriptedLightBase.c.
References GetGame(), and CGame::GetTime().
SetRadiusTo()
void SetRadiusTo (float value) inline private
Sets the radius of the light.
Definition at line 298 of file ScriptedLightBase.c.
References m_Radius.
TryShadowOptimization()
void TryShadowOptimization () inline private
Optimizes shadows by disabling them on this light source while it's within the given radius around the camera.
Definition at line 545 of file ScriptedLightBase.c.
References vector::Distance(), GetGame(), and GetPosition.
UpdateLightMode()
private void UpdateLightMode (string slotName) private
UpdateMode()
void UpdateMode () inline private
Definition at line 81 of file ScriptedLightBase.c.
References InventoryLocation::GetSlot(), InventorySlots::GetSlotName(), InventoryLocation::GetType(), and m_Parent.
Field Documentation
m_BlinkingSpeed
float m_BlinkingSpeed private
Definition at line 31 of file ScriptedLightBase.c.
m_Brightness
float m_Brightness private
Definition at line 18 of file ScriptedLightBase.c.
m_BrightnessPulse
float m_BrightnessPulse private
Definition at line 19 of file ScriptedLightBase.c.
m_BrightnessPulseAmplitudeMax
float m_BrightnessPulseAmplitudeMax private
Definition at line 21 of file ScriptedLightBase.c.
m_BrightnessPulseAmplitudeMin
float m_BrightnessPulseAmplitudeMin private
Definition at line 22 of file ScriptedLightBase.c.
m_BrightnessPulseSpeed
float m_BrightnessPulseSpeed private
Definition at line 20 of file ScriptedLightBase.c.
m_BrightnessSpeedOfChange
float m_BrightnessSpeedOfChange = 1 private
Definition at line 24 of file ScriptedLightBase.c.
m_BrightnessTarget
float m_BrightnessTarget private
Definition at line 23 of file ScriptedLightBase.c.
m_DancingShadowsAmplitude
float m_DancingShadowsAmplitude private
Definition at line 28 of file ScriptedLightBase.c.
m_DancingShadowsLocalPos
vector m_DancingShadowsLocalPos private
Definition at line 38 of file ScriptedLightBase.c.
m_DancingShadowsSpeed
float m_DancingShadowsSpeed private
Definition at line 29 of file ScriptedLightBase.c.
m_DeleteTimer
ref Timer m_DeleteTimer private
Definition at line 40 of file ScriptedLightBase.c.
m_FadeInTime
float m_FadeInTime = -1 private
Definition at line 15 of file ScriptedLightBase.c.
m_FadeOutTime
float m_FadeOutTime = -1 private
Definition at line 14 of file ScriptedLightBase.c.
m_IsDebugEnabled
bool m_IsDebugEnabled = false private
Definition at line 33 of file ScriptedLightBase.c.
m_LifetimeEnd
float m_LifetimeEnd = -1 private
Definition at line 13 of file ScriptedLightBase.c.
m_LifetimeStart
float m_LifetimeStart private
Definition at line 12 of file ScriptedLightBase.c.
m_LocalOri
vector m_LocalOri private
Definition at line 37 of file ScriptedLightBase.c.
m_LocalPos
vector m_LocalPos private
Definition at line 36 of file ScriptedLightBase.c.
m_NightTimeOnlyLights
ref set<ScriptedLightBase> m_NightTimeOnlyLights = new set<ScriptedLightBase>() static private
Definition at line 42 of file ScriptedLightBase.c.
m_OptimizeShadowsRadius
float m_OptimizeShadowsRadius = 0 private
Definition at line 26 of file ScriptedLightBase.c.
m_Parent
Object m_Parent private
Definition at line 35 of file ScriptedLightBase.c.
m_Radius
float m_Radius private
Definition at line 16 of file ScriptedLightBase.c.
m_RadiusSpeedOfChange
float m_RadiusSpeedOfChange = 1 private
Definition at line 25 of file ScriptedLightBase.c.
m_RadiusTarget
float m_RadiusTarget private
Definition at line 17 of file ScriptedLightBase.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ScriptedLightBase.c