DayZ Scripts: EffectAreaLoader Class Reference
EffectAreaLoader Class Reference
Static Private Member Functions
static void CreateZones ()
static JsonDataContaminatedAreas GetData ()
Static Private Attributes
static private string m_Path = "$mission:cfgEffectArea.json"
Detailed Description
Definition at line 2 of file ContaminatedAreaLoader.c.
Member Function Documentation
CreateZones()
static void CreateZones () inline static private
Definition at line 6 of file ContaminatedAreaLoader.c.
References JsonDataContaminatedAreas::Areas, JsonDataPlayerData::AroundPartName, Class::CastTo(), ECE_NONE, ECE_PLACE_ON_SURFACE, Error(), FileExist(), string::Format(), GetData(), GetGame(), ParticleList::GetParticleID(), CGame::GetWorldName(), JsonDataAreaData::InnerPartDist, JsonDataAreaData::InnerRingCount, m_Path, JsonDataAreaData::NegHeight, JsonDataAreaData::OuterOffset, JsonDataAreaData::OuterPartDist, JsonDataAreaData::OuterRingToggle, JsonDataAreaData::ParticleName, JsonDataAreaData::Pos, JsonDataAreaData::PosHeight, JsonDataPlayerData::PPERequesterType, PrintToRPT(), JsonDataAreaData::Radius, EffectArea::SetupZoneData(), CGame::SurfaceRoadY(), JsonDataPlayerData::TinyPartName, Vector(), JsonDataAreaData::VerticalLayers, and JsonDataAreaData::VerticalOffset.
Referenced by MissionBase::OnMissionStart().
GetData()
static JsonDataContaminatedAreas GetData () inline static private
Definition at line 98 of file ContaminatedAreaLoader.c.
References m_Path.
Referenced by CreateZones(), and AreaExposureMdfr::OnActivate().
Field Documentation
m_Path
private string m_Path = "$mission:cfgEffectArea.json" static private
Definition at line 4 of file ContaminatedAreaLoader.c.
Referenced by CreateZones(), and GetData().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/ContaminatedArea/ContaminatedAreaLoader.c