DayZ Scripts: Boat_01_ColorBase Class Reference
Boat_01_ColorBase Class Reference
Private Member Functions
void Boat_01 ()
override void EEInit ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override int GetAnimInstance ()
override int GetSeatAnimationType (int posIdx)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayCargo ()
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override void OnDamageDestroyed (int oldLevel)
override void OnDebugSpawn ()
Private Attributes
protected ref UniversalTemperatureSource m_UTSource
protected ref UniversalTemperatureSourceSettings m_UTSSettings
protected ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine
Member Function Documentation
Boat_01()
void Boat_01 () inline private
CanDisplayAttachmentCategory()
override bool CanDisplayAttachmentCategory (string category_name) inline private
CanDisplayCargo()
override bool CanDisplayCargo () inline private
CanReachSeatFromSeat()
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
CanReleaseAttachment()
override bool CanReleaseAttachment (EntityAI attachment) inline private
EEInit()
override void EEInit () inline private
References GetGame(), GameConstants::ITEM_TEMPERATURE_NEUTRAL_ZONE_MIDDLE, UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureItemCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, m_UTSSettings, and UniversalTemperatureSourceLambdaEngine().
EOnPostSimulate()
override void EOnPostSimulate (IEntity other, float timeSlice) inline private
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
GetAnimInstance()
override int GetAnimInstance () inline private
GetSeatAnimationType()
override int GetSeatAnimationType (int posIdx) inline private
OnDamageDestroyed()
override void OnDamageDestroyed (int oldLevel) inline private
OnDebugSpawn()
override void OnDebugSpawn () inline private
Field Documentation
m_UTSLEngine
protected ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine private
Referenced by EEInit(), and EOnPostSimulate().
m_UTSource
protected ref UniversalTemperatureSource m_UTSource private
Referenced by EEInit(), and EOnPostSimulate().
m_UTSSettings
protected ref UniversalTemperatureSourceSettings m_UTSSettings private
Referenced by EEInit(), and EOnPostSimulate().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Vehicles/InheritedBoats/Boat_01.c