DayZ Scripts: DayZPlayerImplementThrowing Class Reference
DayZPlayerImplementThrowing Class Reference
Private Member Functions
void DayZPlayerImplementThrowing (DayZPlayer pPlayer)
void HandleThrowing (HumanInputController pHic, HumanCommandWeapons pHcw, EntityAI pEntityInHands, float pDt)
void ResetState ()
void SetThrowingModeEnabled (bool enable)
bool IsThrowingModeEnabled ()
bool IsThrowingInProgress ()
Throwing wind-up only (button hold)
bool IsThrowingAnimationPlaying ()
Throwing animation after button release.
bool CanChangeThrowingStance (HumanInputController pHic)
bool CanContinueThrowing (HumanInputController pHic)
bool CanContinueThrowingEx (HumanInputController pHic, EntityAI pEntityInHands)
bool CheckFreeSpace ()
Private Attributes
private DayZPlayer m_Player
private bool m_bThrowingModeEnabled
private bool m_bThrowingInProgress
private bool m_bThrowingAnimationPlaying
private float m_fThrowingForce01
private const float c_fThrowingForceMin = 20.0
private const float c_fThrowingForceMax = 90.0
private const float c_fThrowingForceCoef = 1.0
Constructor & Destructor Documentation
DayZPlayerImplementThrowing()
void DayZPlayerImplementThrowing (DayZPlayer pPlayer) inline private
References m_Player, ResetState(), and SetThrowingModeEnabled().
Member Function Documentation
CanChangeThrowingStance()
bool CanChangeThrowingStance (HumanInputController pHic) inline private
References CheckFreeSpace(), HumanInputController::IsStanceChange(), HumanInputController::IsWeaponRaised(), HumanItemBehaviorCfg::m_iType, and m_Player.
Referenced by HandleThrowing().
CanContinueThrowing()
bool CanContinueThrowing (HumanInputController pHic) inline private
References CheckFreeSpace(), HumanInputController::IsWeaponRaised(), HumanItemBehaviorCfg::m_iType, m_Player, and UAInterface::SyncedPress().
Referenced by CanContinueThrowingEx().
CanContinueThrowingEx()
bool CanContinueThrowingEx (HumanInputController pHic, EntityAI pEntityInHands) inline private
References CanContinueThrowing().
Referenced by HandleThrowing().
CheckFreeSpace()
bool CheckFreeSpace () inline private
References vector::Forward, and m_Player.
Referenced by CanChangeThrowingStance(), and CanContinueThrowing().
HandleThrowing()
void HandleThrowing (HumanInputController pHic, HumanCommandWeapons pHcw, EntityAI pEntityInHands, float pDt) inline private
current state
handle mode change
handle action
cancel throwing in case of raising hands or heavy item in hands
check event for throw
handle throw force
References vector::AnglesToVector(), c_fThrowingForceCoef, c_fThrowingForceMax, c_fThrowingForceMin, CanChangeThrowingStance(), CanContinueThrowingEx(), HumanCommandWeapons::GetBaseAimingAngleLR(), HumanCommandWeapons::GetBaseAimingAngleUD(), HumanInputController::IsAttackButton(), HumanCommandMove::IsStandingFromBack(), HumanCommandWeapons::IsThrowingMode(), HumanInputController::IsThrowingModeChange(), m_bThrowingAnimationPlaying, m_bThrowingInProgress, m_bThrowingModeEnabled, m_fThrowingForce01, HumanItemBehaviorCfg::m_iType, m_Player, ResetState(), HumanCommandWeapons::SetActionProgressParams(), HumanCommandWeapons::SetThrowingMode(), SetThrowingModeEnabled(), HumanCommandWeapons::ThrowItem(), and HumanCommandWeapons::WasItemLeaveHandsEvent().
IsThrowingAnimationPlaying()
bool IsThrowingAnimationPlaying () inline private
Throwing animation after button release.
References m_bThrowingAnimationPlaying.
Referenced by ActionPossibilityCheck().
IsThrowingInProgress()
bool IsThrowingInProgress () inline private
Throwing wind-up only (button hold)
References m_bThrowingInProgress.
IsThrowingModeEnabled()
bool IsThrowingModeEnabled () inline private
References m_bThrowingModeEnabled.
Referenced by CanPlayEmote().
ResetState()
void ResetState () inline private
References m_bThrowingAnimationPlaying, m_bThrowingInProgress, and m_fThrowingForce01.
Referenced by DayZPlayerImplementThrowing(), and HandleThrowing().
SetThrowingModeEnabled()
void SetThrowingModeEnabled (bool enable) inline private
References m_bThrowingModeEnabled, and m_Player.
Referenced by DayZPlayerImplementThrowing(), and HandleThrowing().
Field Documentation
c_fThrowingForceCoef
private const float c_fThrowingForceCoef = 1.0 private
Referenced by HandleThrowing().
c_fThrowingForceMax
private const float c_fThrowingForceMax = 90.0 private
Referenced by HandleThrowing().
c_fThrowingForceMin
private const float c_fThrowingForceMin = 20.0 private
Referenced by HandleThrowing().
m_bThrowingAnimationPlaying
private bool m_bThrowingAnimationPlaying private
Referenced by HandleThrowing(), IsThrowingAnimationPlaying(), and ResetState().
m_bThrowingInProgress
private bool m_bThrowingInProgress private
Referenced by HandleThrowing(), IsThrowingInProgress(), and ResetState().
m_bThrowingModeEnabled
private bool m_bThrowingModeEnabled private
Referenced by HandleThrowing(), IsThrowingModeEnabled(), and SetThrowingModeEnabled().
m_fThrowingForce01
private float m_fThrowingForce01 private
Referenced by HandleThrowing(), and ResetState().
m_Player
private DayZPlayer m_Player private
Referenced by CanChangeThrowingStance(), CanContinueThrowing(), CheckFreeSpace(), DayZPlayerImplementThrowing(), HandleThrowing(), and SetThrowingModeEnabled().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/DayZPlayerImplementThrowing.c