DayZ Scripts: DayZPlayerImplementSwimming Class Reference
DayZPlayerImplementSwimming Class Reference
Private Member Functions
void DayZPlayerImplementSwimming (DayZPlayer pPlayer)
float GetWaterDepth ()
float GetCharacterDepth ()
bool CheckSwimmingStart (out vector waterLevel)
bool HandleSwimming (int pCurrentCommandID, HumanCommandMove pCMove, HumanMovementState pState)
ha
Private Attributes
DayZPlayer m_pPlayer
SHumanCommandSwimSettings m_pSettings
bool m_bWasSwimming = false
Detailed Description
Definition at line 2 of file DayZPlayerImplementSwimming.c.
Constructor & Destructor Documentation
DayZPlayerImplementSwimming()
void DayZPlayerImplementSwimming (DayZPlayer pPlayer) inline private
Definition at line 9 of file DayZPlayerImplementSwimming.c.
References m_pPlayer, and m_pSettings.
Member Function Documentation
CheckSwimmingStart()
bool CheckSwimmingStart (out vector waterLevel) inline private
Definition at line 31 of file DayZPlayerImplementSwimming.c.
References DayZPlayerUtils(), and m_pPlayer.
Referenced by HandleSwimming().
GetCharacterDepth()
float GetCharacterDepth () inline private
Definition at line 23 of file DayZPlayerImplementSwimming.c.
References HumanCommandSwim(), and m_pPlayer.
GetWaterDepth()
float GetWaterDepth () inline private
Definition at line 15 of file DayZPlayerImplementSwimming.c.
References HumanCommandSwim(), and m_pPlayer.
Referenced by HandleSwimming().
HandleSwimming()
bool HandleSwimming (int pCurrentCommandID, HumanCommandMove pCMove, HumanMovementState pState) inline private
ha
get water level
now movement
handled !
Definition at line 37 of file DayZPlayerImplementSwimming.c.
References CheckSwimmingStart(), DayZPlayerUtils(), HumanCommandMove::ForceStanceUp(), GetWaterDepth(), HumanCommandSwim(), m_bWasSwimming, SHumanCommandSwimSettings::m_fToCrouchLevel, SHumanCommandSwimSettings::m_fToErectLevel, SHumanCommandSwimSettings::m_fWaterLevelOut, HumanMovementState::m_iStanceIdx, m_pPlayer, m_pSettings, DayZPlayer::SetCurrentWaterLevel(), and HumanCommandMove::SetCurrentWaterLevel().
Field Documentation
m_bWasSwimming
bool m_bWasSwimming = false private
Definition at line 7 of file DayZPlayerImplementSwimming.c.
Referenced by HandleSwimming().
m_pPlayer
DayZPlayer m_pPlayer private
Definition at line 5 of file DayZPlayerImplementSwimming.c.
Referenced by CheckSwimmingStart(), DayZPlayerImplementSwimming(), GetCharacterDepth(), GetWaterDepth(), and HandleSwimming().
m_pSettings
SHumanCommandSwimSettings m_pSettings private
Definition at line 6 of file DayZPlayerImplementSwimming.c.
Referenced by DayZPlayerImplementSwimming(), and HandleSwimming().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/DayZPlayerImplementSwimming.c