DayZ Scripts: P:/scripts/3_game/aibehaviour.c File Reference
aibehaviour.c File Reference
Data Structures
class AIBehaviourHLData
class AIBehaviourHLZombie2
class AIBehaviourHLDataZombie2
Functions
private void AIBehaviourHLData ()
private void ~AIBehaviourHLData ()
void OnParseConfig ()
proto native void ParseBehaviourSlot (string name)
proto native void ParseAlertLevel (string name)
proto native float ReadParamValue (string paramName, float defValue)
private void ~AIBehaviourHL ()
proto native AIBehaviourHLData GetTemplateData ()
void OnInit ()
void Simulate (float timeDelta)
void OnDamage (float damage, EntityAI source)
void OnDamageInflicted ()
void OnAnimationEvent (int nameCrc)
proto native void SetNextBehaviour (int BehaviourCrc)
proto native void SwitchToNextBehaviour ()
static proto void RegAIBehaviour (string behname, typename behClass, typename behClassData)
Variables
AIBehaviourHLZombie2 AIBehaviourHL
Detailed Description
this file is interface to AI Behaviour
Function Documentation
AIBehaviourHLData()
private void AIBehaviourHLData ()
GetTemplateData()
proto native AIBehaviourHLData GetTemplateData ()
Referenced by AIBehaviourHLZombie2::GetData().
OnAnimationEvent()
void OnAnimationEvent (int nameCrc)
OnDamage()
void OnDamage (float damage, EntityAI source)
OnDamageInflicted()
void OnDamageInflicted ()
OnInit()
void OnInit ()
Referenced by AnimationTimer::AnimationTimer(), TimerBase::Timer(), and TimerBase::WidgetFadeTimer().
OnParseConfig()
void OnParseConfig ()
ParseAlertLevel()
proto native void ParseAlertLevel (string name)
ParseBehaviourSlot()
proto native void ParseBehaviourSlot (string name)
ReadParamValue()
proto native float ReadParamValue (string paramName, float defValue)
RegAIBehaviour()
static proto void RegAIBehaviour (string behname, typename behClass , typename behClassData) static
SetNextBehaviour()
proto native void SetNextBehaviour (int BehaviourCrc)
Referenced by AIBehaviourHLZombie2::OnInit().
Simulate()
void Simulate (float timeDelta)
SwitchToNextBehaviour()
proto native void SwitchToNextBehaviour ()
Referenced by AIBehaviourHLZombie2::OnInit().
~AIBehaviourHL()
private void ~AIBehaviourHL ()
~AIBehaviourHLData()
private void ~AIBehaviourHLData ()
Variable Documentation
AIBehaviourHL
class AIBehaviourHLData AIBehaviourHL