DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionUnfoldMap.c File Reference
ActionUnfoldMap.c File Reference
Data Structures
class ActionUnfoldMapCB
Functions
ActionUnfoldMapCB ActionBaseCB ActionUnfoldMap ()
void ActionUnfoldMapCB ()
void ~ActionUnfoldMapCB ()
override void SetActionData (ActionData action_data)
bool CancelCondition (bool pEnable)
override void OnStateChange (int pOldState, int pCurrentState)
override void OnAnimationEvent (int pEventID)
override void OnFinish (bool pCanceled)
void PerformMapChange ()
bool StateCheck ()
override bool IsInstant ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override int GetActionCategory ()
override void OnStartClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnEndRequest (ActionData action_data)
override void Interrupt (ActionData action_data)
void OpenMap (ActionData action_data)
Variables
bool m_MapFolding
bool m_HasReceivedEvent
bool m_CancelCondition
int m_InitMovementState
int m_FinalMovementState
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 189 of file ActionUnfoldMap.c.
ActionUnfoldMap()
ActionUnfoldMapCB ActionBaseCB ActionUnfoldMap ()
Definition at line 1 of file ActionUnfoldMap.c.
Referenced by MissionBase::IsMapUnfoldActionRunning(), ActionUnfoldMapCB::OnFinish(), ActionConstructor::RegisterActions(), and ItemMap::SetActions().
ActionUnfoldMapCB()
void ActionUnfoldMapCB ()
Definition at line 175 of file ActionUnfoldMap.c.
CancelCondition()
bool CancelCondition (bool pEnable)
Definition at line 210 of file ActionUnfoldMap.c.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 178 of file ActionUnfoldMap.c.
References m_ConditionItem, and m_ConditionTarget.
GetActionCategory()
override int GetActionCategory ()
Definition at line 198 of file ActionUnfoldMap.c.
References AC_SINGLE_USE.
HasTarget()
override bool HasTarget ()
Definition at line 184 of file ActionUnfoldMap.c.
Interrupt()
override void Interrupt (ActionData action_data)
Definition at line 221 of file ActionUnfoldMap.c.
References ActionData::m_Player.
IsInstant()
override bool IsInstant ()
Definition at line 173 of file ActionUnfoldMap.c.
OnAnimationEvent()
override void OnAnimationEvent (int pEventID)
Definition at line 226 of file ActionUnfoldMap.c.
OnEndRequest()
override void OnEndRequest (ActionData action_data)
Definition at line 215 of file ActionUnfoldMap.c.
References ActionData::m_Callback, ActionData::m_State, and UA_FINISHED.
OnFinish()
override void OnFinish (bool pCanceled)
Definition at line 250 of file ActionUnfoldMap.c.
References GetStanceMask(), and ActionData::m_Player.
OnStartClient()
override void OnStartClient (ActionData action_data)
Definition at line 203 of file ActionUnfoldMap.c.
OnStartServer()
override void OnStartServer (ActionData action_data)
Definition at line 208 of file ActionUnfoldMap.c.
OnStateChange()
override void OnStateChange (int pOldState, int pCurrentState)
Definition at line 215 of file ActionUnfoldMap.c.
OpenMap()
void OpenMap (ActionData action_data)
Definition at line 243 of file ActionUnfoldMap.c.
References ActionData::m_Player.
Referenced by SetActionData().
PerformMapChange()
void PerformMapChange ()
Definition at line 279 of file ActionUnfoldMap.c.
SetActionData()
override void SetActionData (ActionData action_data)
Definition at line 204 of file ActionUnfoldMap.c.
References OpenMap().
StateCheck()
bool StateCheck ()
Definition at line 326 of file ActionUnfoldMap.c.
~ActionUnfoldMapCB()
void ~ActionUnfoldMapCB ()
Definition at line 182 of file ActionUnfoldMap.c.
Variable Documentation
m_CancelCondition
bool m_CancelCondition
Definition at line 171 of file ActionUnfoldMap.c.
m_FinalMovementState
int m_FinalMovementState
Definition at line 173 of file ActionUnfoldMap.c.
m_HasReceivedEvent
bool m_HasReceivedEvent
Definition at line 170 of file ActionUnfoldMap.c.
m_InitMovementState
int m_InitMovementState
Definition at line 172 of file ActionUnfoldMap.c.
m_MapFolding
bool m_MapFolding
Definition at line 169 of file ActionUnfoldMap.c.