DayZ Scripts: ActionSkinning Class Reference
ActionSkinning Class Reference
Private Member Functions
void ActionSkinning ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
vector GetRandomPos (vector body_pos)
private void DropArrows (EntityAI body)
ItemBase CreateOrgan (PlayerBase player, vector body_pos, string item_to_spawn, string cfg_skinning_organ_class, ItemBase tool)
override void OnFinishProgressClient (ActionData action_data)
Detailed Description
Definition at line 29 of file ActionSkinning.c.
Constructor & Destructor Documentation
ActionSkinning()
void ActionSkinning () inline private
Definition at line 31 of file ActionSkinning.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_MEDIUM.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 48 of file ActionSkinning.c.
References Class::CastTo(), and GetGame().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 42 of file ActionSkinning.c.
References m_ConditionItem, and m_ConditionTarget.
CreateOrgan()
ItemBase CreateOrgan (PlayerBase player, vector body_pos, string item_to_spawn, string cfg_skinning_organ_class, ItemBase tool) inline private
Definition at line 299 of file ActionSkinning.c.
References Class::CastTo(), CGame::ConfigGetFloat(), CGame::ConfigGetFloatArray(), ECE_PLACE_ON_SURFACE, g_Game, GetGame(), GetRandomPos(), GetSpecialtyWeight(), Math::RandomFloat(), and Math::Round().
Referenced by OnFinishProgressServer().
DropArrows()
private void DropArrows (EntityAI body) inline private
Definition at line 272 of file ActionSkinning.c.
References ArrowManagerBase::GetArrow(), ArrowManagerBase::GetArrowsCount(), GetRandomPos(), and Math3D::MatrixIdentity4().
Referenced by OnFinishProgressServer().
GetRandomPos()
vector GetRandomPos (vector body_pos) inline private
Definition at line 267 of file ActionSkinning.c.
References Math::RandomFloat01(), and Vector().
Referenced by CreateOrgan(), and DropArrows().
OnFinishProgressClient()
override void OnFinishProgressClient (ActionData action_data) inline private
Definition at line 365 of file ActionSkinning.c.
References CGame::GetAnalyticsClient(), GetGame(), ActionData::m_Target, and AnalyticsManagerClient::OnActionFinishedGutDeer().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 72 of file ActionSkinning.c.
References Class::CastTo(), CGame::ConfigGetFloat(), CGame::ConfigGetFloatArray(), CGame::ConfigGetTextArray(), CreateOrgan(), GameConstants::DAMAGE_BADLY_DAMAGED_VALUE, GameConstants::DAMAGE_DAMAGED_VALUE, GameConstants::DAMAGE_RUINED_VALUE, GameConstants::DAMAGE_WORN_VALUE, DropArrows(), Math::Floor(), g_Game, GetCEApi(), GetGame(), GetPlugin(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, ActionData::m_Target, CGame::ObjectDelete(), PluginLifespan(), UADamageApplied::SKINNING, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionSkinning.c