DayZ Scripts: BleedingSourcesManagerBase Class Reference
BleedingSourcesManagerBase Class Reference
Private Member Functions
void BleedingSourcesManagerBase (PlayerBase player)
protected void Init ()
protected void SetItem (ItemBase item)
set< int > GetBleedingSourcesLocations ()
int GetBleedingSourceBitsByInvLocation (int inv_location)
int GetFreeBleedingSourceBitsByInvLocation (int inv_location)
bool IsBleedingSourceActive (string name)
protected int GetBitFromSelectionID (int id)
protected BleedingSourceZone GetBleedingSourceMeta (int bit)
int GetRegisteredSourcesCount ()
protected void RegisterBleedingZoneEx (string name, int max_time, string bone="", vector orientation="0 0 0", vector offset="0 0 0", float flow_modifier=1, string particle_name="BleedingSourceEffect", int inv_location=0)
protected void RegisterBleedingZone (string name, int max_time, string bone="", vector orientation="0 0 0", vector offset="0 0 0", float flow_modifier=1, string particle_name="BleedingSourceEffect")
void RemoveAllSources ()
protected int GetBitFromSelectionName (string name)
protected string GetSelectionNameFromBit (int bit)
bool AttemptAddBleedingSource (int component)
bool AttemptAddBleedingSourceBySelection (string selection_name)
bool AttemptAddBleedingSourceDirectly (int bit, eBleedingSourceType type=eBleedingSourceType.NORMAL, int context=0)
protected bool CanAddBleedingSource (int bit)
protected void AddBleedingSourceEx (int bit, eBleedingSourceType type=eBleedingSourceType.NORMAL, int context=0)
protected void AddBleedingSource (int bit)
int GetBleedingSourceActiveTime (int bit)
void SetBleedingSourceActiveTime (int bit, int time)
void SetBleedingSourceType (int bit, eBleedingSourceType type)
eBleedingSourceType GetBleedingSourceType (int bit)
protected bool RemoveBleedingSource (int bit)
int GetBleedingSourcesCount ()
override protected void Init ()
override protected void RegisterBleedingZoneEx (string name, int max_time, string bone="", vector orientation="0 0 0", vector offset="0 0 0", float flow_modifier=1, string particle_name="BleedingSourceEffect", int inv_location=0)
void OnVariablesSynchronized (int current_bits)
void Reload ()
override protected void AddBleedingSource (int bit)
override protected bool RemoveBleedingSource (int bit)
void OnBleedingBitsUpdate (int old_mask, int new_mask)
int GetBleedingSourceCountRemote ()
void SetDiag (bool value)
void OnUpdate ()
void DisplayDebug ()
void CleanDebug ()
void DisplayVisualDebug ()
void CleanVisualDebug ()
protected BleedingSourceZone GetBleedingSourceZone (int bit)
int GetStorageVersion ()
void RequestDeletion (int bit)
override protected void AddBleedingSource (int bit)
override protected bool RemoveBleedingSource (int bit)
void RemoveAnyBleedingSource ()
void RemoveMostSignificantBleedingSource ()
void RemoveMostSignificantBleedingSourceEx (ItemBase item)
int GetMostSignificantBleedingSource ()
void OnTick (float delta_time)
void ActivateAllBS ()
void ProcessHit (float damage, EntityAI source, int component, string zone, string ammo, vector modelPos)
void DebugActivateBleedingSource (int source)
void SetBloodLoss (bool status)
void OnStoreSave (ParamsWriteContext ctx)
bool OnStoreLoad (ParamsReadContext ctx, int version)
void ~BleedingSourcesManagerServer ()
Private Attributes
ref map< int, ref BleedingSource > m_BleedingSources = new map<int, ref BleedingSource>
ref map< string, ref BleedingSourceZone > m_BleedingSourceZone = new map<string, ref BleedingSourceZone>
ref map< int, int > m_BleedingSourcesByLocation = new map<int, int>
ItemBase m_Item
PlayerBase m_Player
ref map< int, string > m_BitToFireGeom = new map<int, string>
protected int m_Bit
int m_BitOffset = 0
int m_BleedingBits
bool m_ShowDiag
bool m_ShowingDiag
bool m_ShowingDiagDraw
Shape m_Point
bool m_EnableHitIndication = false
const float TICK_INTERVAL_SEC = 3
float m_Tick
bool m_DisableBloodLoss = false
ref array< int > m_DeleteList = new array<int>
const int STORAGE_VERSION = 103
Static Private Attributes
static ref map< int, int > m_BleedingSourcesZonesMaskByLocation = new map<int, int>
static ref set< int > m_BleedingSourcesLocationsList = new set<int>
Constructor & Destructor Documentation
BleedingSourcesManagerBase()
void BleedingSourcesManagerBase (PlayerBase player) inline private
References Init(), and m_Player.
~BleedingSourcesManagerServer()
void ~BleedingSourcesManagerServer () inline private
References m_Player, and RemoveAllSources().
Member Function Documentation
ActivateAllBS()
void ActivateAllBS () inline private
References AddBleedingSource(), and CanAddBleedingSource().
AddBleedingSource() [1/3]
protected void AddBleedingSource (int bit) inline private
References BleedingSource(), GetBleedingSourceMeta(), BleedingSourceZone::GetBoneName(), BleedingSourceZone::GetFlowModifier(), BleedingSourceZone::GetInvLocation(), BleedingSourceZone::GetMaxTime(), BleedingSourceZone::GetOffset(), BleedingSourceZone::GetOrientation(), BleedingSourceZone::GetParticleName(), m_BleedingSources, m_BleedingSourcesByLocation, and m_Player.
Referenced by ActivateAllBS(), AddBleedingSourceEx(), AttemptAddBleedingSource(), AttemptAddBleedingSourceBySelection(), DebugActivateBleedingSource(), OnBleedingBitsUpdate(), OnStoreLoad(), and Reload().
AddBleedingSource() [2/3]
override protected void AddBleedingSource (int bit) inline private
References GetGame(), and m_Player.
AddBleedingSource() [3/3]
override protected void AddBleedingSource (int bit) inline private
References m_Player.
AddBleedingSourceEx()
protected void AddBleedingSourceEx (int bit, eBleedingSourceType type = eBleedingSourceType.NORMAL, int context = 0) inline private
References AddBleedingSource(), and m_BleedingSources.
Referenced by AttemptAddBleedingSourceDirectly().
AttemptAddBleedingSource()
bool AttemptAddBleedingSource (int component) inline private
References AddBleedingSource(), CanAddBleedingSource(), component, and GetBitFromSelectionID().
Referenced by ProcessHit().
AttemptAddBleedingSourceBySelection()
bool AttemptAddBleedingSourceBySelection (string selection_name) inline private
References AddBleedingSource(), CanAddBleedingSource(), GetBitFromSelectionName(), and string::ToLower().
AttemptAddBleedingSourceDirectly()
bool AttemptAddBleedingSourceDirectly (int bit, eBleedingSourceType type = eBleedingSourceType.NORMAL, int context = 0) inline private
References AddBleedingSourceEx(), and CanAddBleedingSource().
CanAddBleedingSource()
protected bool CanAddBleedingSource (int bit) inline private
References GetBleedingSourceMeta(), and m_Player.
Referenced by ActivateAllBS(), AttemptAddBleedingSource(), AttemptAddBleedingSourceBySelection(), AttemptAddBleedingSourceDirectly(), DebugActivateBleedingSource(), and OnStoreLoad().
CleanDebug()
void CleanDebug () inline private
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), and DbgUI::EndCleanupScope().
Referenced by OnUpdate().
CleanVisualDebug()
void CleanVisualDebug () inline private
Referenced by OnUpdate().
DebugActivateBleedingSource()
void DebugActivateBleedingSource (int source) inline private
References AddBleedingSource(), CanAddBleedingSource(), and RemoveAllSources().
DisplayDebug()
void DisplayDebug () inline private
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), BIT_INT_SIZE, DbgUI::End(), DbgUI::EndCleanupScope(), GetBleedingSourceMeta(), BleedingSourceZone::GetInvLocation(), GetSelectionNameFromBit(), InventorySlots::GetSlotName(), name, Math::Pow(), and DbgUI::Text().
Referenced by OnUpdate().
DisplayVisualDebug()
void DisplayVisualDebug () inline private
Referenced by OnUpdate().
GetBitFromSelectionID()
protected int GetBitFromSelectionID (int id) inline private
References CachedObjectsArrays::ARRAY_STRING, GetBitFromSelectionName(), and m_Player.
Referenced by AttemptAddBleedingSource().
GetBitFromSelectionName()
protected int GetBitFromSelectionName (string name) inline private
References m_BleedingSourceZone, and name.
Referenced by AttemptAddBleedingSourceBySelection(), GetBitFromSelectionID(), and IsBleedingSourceActive().
GetBleedingSourceActiveTime()
int GetBleedingSourceActiveTime (int bit) inline private
References m_BleedingSources.
Referenced by OnStoreSave().
GetBleedingSourceBitsByInvLocation()
int GetBleedingSourceBitsByInvLocation (int inv_location) inline private
References m_BleedingSourcesByLocation.
Referenced by GetFreeBleedingSourceBitsByInvLocation().
GetBleedingSourceCountRemote()
int GetBleedingSourceCountRemote () inline private
References BIT_INT_SIZE, and Math::Pow().
GetBleedingSourceMeta()
protected BleedingSourceZone GetBleedingSourceMeta (int bit) inline private
References GetSelectionNameFromBit(), and m_BleedingSourceZone.
Referenced by AddBleedingSource(), CanAddBleedingSource(), DisplayDebug(), GetMostSignificantBleedingSource(), and RemoveBleedingSource().
GetBleedingSourcesCount()
int GetBleedingSourcesCount () inline private
References m_BleedingSources.
GetBleedingSourcesLocations()
set< int > GetBleedingSourcesLocations () inline private
References m_BleedingSourcesLocationsList.
GetBleedingSourceType()
eBleedingSourceType GetBleedingSourceType (int bit) inline private
References m_BleedingSources.
Referenced by OnStoreSave().
GetBleedingSourceZone()
protected BleedingSourceZone GetBleedingSourceZone (int bit) inline private
References GetSelectionNameFromBit().
GetFreeBleedingSourceBitsByInvLocation()
int GetFreeBleedingSourceBitsByInvLocation (int inv_location) inline private
References GetBleedingSourceBitsByInvLocation(), and m_BleedingSourcesZonesMaskByLocation.
GetMostSignificantBleedingSource()
int GetMostSignificantBleedingSource () inline private
References BIT_INT_SIZE, GetBleedingSourceMeta(), BleedingSourceZone::GetFlowModifier(), and m_Player.
Referenced by RemoveMostSignificantBleedingSource().
GetRegisteredSourcesCount()
int GetRegisteredSourcesCount () inline private
References m_BitOffset.
GetSelectionNameFromBit()
protected string GetSelectionNameFromBit (int bit) inline private
References m_BitToFireGeom.
Referenced by DisplayDebug(), GetBleedingSourceMeta(), and GetBleedingSourceZone().
GetStorageVersion()
int GetStorageVersion () inline private
References STORAGE_VERSION.
Init() [1/2]
protected void Init () inline private
References PlayerConstants::BLEEDING_SOURCE_DURATION_NORMAL, PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_LOW, PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, and RegisterBleedingZoneEx().
Referenced by BleedingSourcesManagerBase(), and Reload().
Init() [2/2]
override protected void Init () inline private
References Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), and GameplayEffectWidgets_base::RegisterGameplayEffectData().
IsBleedingSourceActive()
bool IsBleedingSourceActive (string name) inline private
References GetBitFromSelectionName(), m_Player, name, and string::ToLower().
OnBleedingBitsUpdate()
void OnBleedingBitsUpdate (int old_mask, int new_mask) inline private
References AddBleedingSource(), and RemoveBleedingSource().
Referenced by OnVariablesSynchronized().
OnStoreLoad()
bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
References AddBleedingSource(), BIT_INT_SIZE, CanAddBleedingSource(), Serializer::Read(), SetBleedingSourceActiveTime(), and SetBleedingSourceType().
OnStoreSave()
void OnStoreSave (ParamsWriteContext ctx) inline private
References BIT_INT_SIZE, GetBleedingSourceActiveTime(), GetBleedingSourceType(), m_Player, and Serializer::Write().
OnTick()
void OnTick (float delta_time) inline private
References PlayerConstants::BLEEDING_LOW_PRESSURE_BLOOD, PlayerConstants::BLEEDING_LOW_PRESSURE_MIN_MOD, PlayerConstants::BLOOD_THRESHOLD_FATAL, Math::Clamp(), Math::InverseLerp(), m_Player, m_Tick, and RemoveBleedingSource().
OnUpdate()
void OnUpdate () inline private
References CleanDebug(), CleanVisualDebug(), DisplayDebug(), and DisplayVisualDebug().
OnVariablesSynchronized()
void OnVariablesSynchronized (int current_bits) inline private
References m_Player, and OnBleedingBitsUpdate().
ProcessHit()
void ProcessHit (float damage, EntityAI source, int component, string zone, string ammo, vector modelPos) inline private
References AttemptAddBleedingSource(), Debug::BleedingChancesLog(), BleedChanceData::CalculateBleedChance(), Math::Clamp(), component, CGame::ConfigGetFloat(), CGame::ConfigGetTextOut(), GetGame(), LogManager::IsBleedingChancesLogEnable(), m_Player, Math::RandomFloat01(), Math::RandomInt(), and float::ToString().
RegisterBleedingZone()
protected void RegisterBleedingZone (string name, int max_time, string bone = "", vector orientation = "0 0 0", vector offset = "0 0 0", float flow_modifier = 1, string particle_name = "BleedingSourceEffect") inline private
References name, and RegisterBleedingZoneEx().
RegisterBleedingZoneEx() [1/2]
protected void RegisterBleedingZoneEx (string name, int max_time, string bone = "", vector orientation = "0 0 0", vector offset = "0 0 0", float flow_modifier = 1, string particle_name = "BleedingSourceEffect", int inv_location = 0) inline private
References BIT_INT_SIZE, Error(), m_Bit, m_BitOffset, m_BitToFireGeom, m_BleedingSourcesLocationsList, m_BleedingSourcesZonesMaskByLocation, m_BleedingSourceZone, name, and string::ToLower().
Referenced by Init(), and RegisterBleedingZone().
RegisterBleedingZoneEx() [2/2]
override protected void RegisterBleedingZoneEx (string name, int max_time, string bone = "", vector orientation = "0 0 0", vector offset = "0 0 0", float flow_modifier = 1, string particle_name = "BleedingSourceEffect", int inv_location = 0) inline private
References Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), m_Bit, name, and GameplayEffectWidgets_base::RegisterGameplayEffectData().
Reload()
void Reload () inline private
References AddBleedingSource(), BIT_INT_SIZE, Init(), and RemoveBleedingSource().
RemoveAllSources()
void RemoveAllSources () inline private
References m_BleedingSources, and RemoveBleedingSource().
Referenced by DebugActivateBleedingSource(), and ~BleedingSourcesManagerServer().
RemoveAnyBleedingSource()
void RemoveAnyBleedingSource () inline private
References m_Player, and RemoveBleedingSource().
RemoveBleedingSource() [1/3]
protected bool RemoveBleedingSource (int bit) inline private
References GetBleedingSourceMeta(), BleedingSourceZone::GetInvLocation(), m_BleedingSources, and m_BleedingSourcesByLocation.
Referenced by OnBleedingBitsUpdate(), OnTick(), Reload(), RemoveAllSources(), RemoveAnyBleedingSource(), and RemoveMostSignificantBleedingSource().
RemoveBleedingSource() [2/3]
override protected bool RemoveBleedingSource (int bit) inline private
References GetGame(), m_Item, and m_Player.
RemoveBleedingSource() [3/3]
override protected bool RemoveBleedingSource (int bit) inline private
References PlayerConstants::BLEEDING_SOURCE_CLOSE_INFECTION_CHANCE, Error(), ItemBase::GetInfectionChance(), m_Item, m_Player, CachedObjectsParams::PARAM1_BOOL, and Math::RandomFloat01().
RemoveMostSignificantBleedingSource()
void RemoveMostSignificantBleedingSource () inline private
References GetMostSignificantBleedingSource(), and RemoveBleedingSource().
Referenced by RemoveMostSignificantBleedingSourceEx().
RemoveMostSignificantBleedingSourceEx()
void RemoveMostSignificantBleedingSourceEx (ItemBase item) inline private
References RemoveMostSignificantBleedingSource(), and SetItem().
RequestDeletion()
void RequestDeletion (int bit) inline private
SetBleedingSourceActiveTime()
void SetBleedingSourceActiveTime (int bit, int time) inline private
References m_BleedingSources.
Referenced by OnStoreLoad().
SetBleedingSourceType()
void SetBleedingSourceType (int bit, eBleedingSourceType type) inline private
References m_BleedingSources.
Referenced by OnStoreLoad().
SetBloodLoss()
void SetBloodLoss (bool status) inline private
SetDiag()
void SetDiag (bool value) inline private
References CGame::CreateObject(), GetGame(), EffectParticle::GetParticle(), m_Player, and SEffectManager::PlayInWorld().
SetItem()
protected void SetItem (ItemBase item) inline private
References m_Item.
Referenced by RemoveMostSignificantBleedingSourceEx().
Field Documentation
m_Bit
protected int m_Bit private
Referenced by RegisterBleedingZoneEx().
m_BitOffset
int m_BitOffset = 0 private
Referenced by GetRegisteredSourcesCount(), and RegisterBleedingZoneEx().
m_BitToFireGeom
ref map<int, string> m_BitToFireGeom = new map<int, string> private
Referenced by GetSelectionNameFromBit(), and RegisterBleedingZoneEx().
m_BleedingBits
int m_BleedingBits private
m_BleedingSources
ref map<int, ref BleedingSource> m_BleedingSources = new map<int, ref BleedingSource> private
Referenced by AddBleedingSource(), AddBleedingSourceEx(), GetBleedingSourceActiveTime(), GetBleedingSourcesCount(), GetBleedingSourceType(), RemoveAllSources(), RemoveBleedingSource(), SetBleedingSourceActiveTime(), and SetBleedingSourceType().
m_BleedingSourcesByLocation
ref map<int, int> m_BleedingSourcesByLocation = new map<int, int> private
Referenced by AddBleedingSource(), GetBleedingSourceBitsByInvLocation(), and RemoveBleedingSource().
m_BleedingSourcesLocationsList
ref set<int> m_BleedingSourcesLocationsList = new set<int> static private
Referenced by GetBleedingSourcesLocations(), and RegisterBleedingZoneEx().
m_BleedingSourcesZonesMaskByLocation
ref map<int, int> m_BleedingSourcesZonesMaskByLocation = new map<int, int> static private
Referenced by GetFreeBleedingSourceBitsByInvLocation(), and RegisterBleedingZoneEx().
m_BleedingSourceZone
ref map<string, ref BleedingSourceZone> m_BleedingSourceZone = new map<string, ref BleedingSourceZone> private
Referenced by GetBitFromSelectionName(), GetBleedingSourceMeta(), and RegisterBleedingZoneEx().
m_DeleteList
ref array<int> m_DeleteList = new array<int> private
m_DisableBloodLoss
bool m_DisableBloodLoss = false private
m_EnableHitIndication
bool m_EnableHitIndication = false private
m_Item
ItemBase m_Item private
Referenced by SetItem().
m_Player
PlayerBase m_Player private
Referenced by AddBleedingSource(), BleedingSourcesManagerBase(), CanAddBleedingSource(), GetBitFromSelectionID(), and IsBleedingSourceActive().
m_Point
Shape m_Point private
m_ShowDiag
bool m_ShowDiag private
m_ShowingDiag
bool m_ShowingDiag private
m_ShowingDiagDraw
bool m_ShowingDiagDraw private
m_Tick
float m_Tick private
STORAGE_VERSION
const int STORAGE_VERSION = 103 private
Referenced by GetStorageVersion().
TICK_INTERVAL_SEC
const float TICK_INTERVAL_SEC = 3 private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/BleedingSources/BleedingSourcesManagerBase.c
P:/scripts/4_World/Classes/BleedingSources/BleedingSourcesManagerRemote.c
P:/scripts/4_World/Classes/BleedingSources/BleedingSourcesManagerServer.c