DayZ Scripts: DayZPlayer Class Reference
DayZPlayer Class Reference
Private Member Functions
void DayZPlayerImplement ()
constructor
DayZPlayerImplementAiming GetAimingModel ()
DayZPlayerImplementMeleeCombat GetMeleeCombat ()
DayZPlayerMeleeFightLogic_LightHeavy GetMeleeFightLogic ()
DayZPlayerImplementThrowing GetThrowing ()
DayZPlayerImplementFallDamage GetFallDamage ()
void ~DayZPlayerImplement ()
override bool IsEyeZoom ()
Legacy.
override int GetEyeZoomLevel ()
override bool IsShootingFromCamera ()
void OverrideShootFromCamera (bool pState)
bool IsInIronsights ()
bool IsInOptics ()
override bool IsInThirdPerson ()
void SetIsInThirdPerson (bool state)
bool IsFireWeaponRaised ()
bool IsTryingHoldBreath ()
bool IsSprintFull ()
void ShowWeaponDebug (bool show)
bool IsWeaponDebugEnabled ()
void SetFallYDiff (float value)
override float GetCurrentWaterLevel ()
override void SetCurrentWaterLevel (float pWaterLevel)
void SetIronsights (bool value)
void SetOptics (bool value)
void ExitSights ()
void SwitchOptics (ItemOptics optic, bool state)
void SetClimbingLadderType (string value)
bool CanConsumeStamina (EStaminaConsumers consumer)
Implementations only! - used on PlayerBase.
bool CanStartConsumingStamina (EStaminaConsumers consumer)
void DepleteStamina (EStaminaModifiers modifier, float dT=-1)
bool IsInVehicle ()
bool IsSwimming ()
bool IsClimbingLadder ()
bool PlaySoundEvent (EPlayerSoundEventID id, bool from_anim_system=false, bool is_from_server=false)
bool PlaySoundEventEx (EPlayerSoundEventID id, bool from_anim_system=false, bool is_from_server=false, int param=0)
bool IsFBSymptomPlaying ()
override string GetDebugText ()
void TriggerPullPlayerOutOfVehicle ()
void TriggerPullPlayerOutOfVehicleImpl ()
override void OnVariablesSynchronized ()
bool HandleDeath (int pCurrentCommandID)
void ResetDeathStartTime ()
int GetTypeOfDeath (int pCurrentCommandID)
void SendDeathJuncture (int pAnimTypeDeath, float pAnimHitDirDeath)
override void EEKilled (Object killer)
void ShowDeadScreen (bool show, float duration)
override void StopDeathDarkeningEffect ()
void SimulateDeath (bool state)
void LockControls (bool state)
void SetDeathDarknessLevel (float duration, float tick_time)
void SendCompleteWeaponRaiseJuncture ()
void CompleteWeaponRaise ()
void ResetWeaponRaiseProgress ()
bool IsWeaponRaiseCompleted ()
DayZPlayerInventory GetDayZPlayerInventory ()
override void OnInputForRemote (ParamsReadContext ctx)
override void OnInputFromServer (ParamsReadContext ctx)
void RequestSoundEvent (EPlayerSoundEventID id, bool from_server_and_client=false)
void RequestSoundEventEx (EPlayerSoundEventID id, bool from_server_and_client=false, int param=0)
protected void SendSoundEvent (EPlayerSoundEventID id)
protected void SendSoundEventEx (EPlayerSoundEventID id, int param=0)
override void OnItemInHandsChanged ()
WeaponManager GetWeaponManager ()
void HandleWeapons (float pDt, Entity pInHands, HumanInputController pInputs, out bool pExitIronSights)
void HandleOptic (notnull ItemOptics optic, bool inHands, HumanInputController pInputs, out bool pExitOptics)
bool HandleDamageHit (int pCurrentCommandID)
bool EvaluateDeathAnimation (int pDamageType, EntityAI pSource, string pAmmoType, out int pAnimType, out float pAnimHitDir)
selects animation type and direction based on damage system data
bool EvaluateDamageHitAnimation (TotalDamageResult pDamageResult, int pDamageType, EntityAI pSource, string pComponent, string pAmmoType, vector pModelPos, out int pAnimType, out float pAnimHitDir, out bool pAnimHitFullbody)
selects animation type and direction based on damage system data
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
event from damage system
override bool HeadingModel (float pDt, SDayZPlayerHeadingModel pModel)
override bool AimingModel (float pDt, SDayZPlayerAimingModel pModel)
bool CanJump ()
bool CanClimb (int climbType, SHumanCommandClimbResult climbRes)
void OnJumpStart ()
void OnJumpEnd (int pLandType=0)
void StopHandEvent ()
void StopWeaponEvent ()
void AbortWeaponEvent ()
void HandleADS ()
void HandleView ()
bool ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
override void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
void HideClothing (ItemOptics optic, bool state)
void CommandHandlerDebug (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
override int CameraHandler (int pCameraMode)
void OnMovementChanged ()
Event, called when HumanMovementState.m_iMovement changes...walk, run, sprint, etc..
void OnSprintStart ()
void OnSprintEnd ()
void OnInputUserDataReceived (ParamsReadContext ctx)
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
AnimBootsType GetBootsType ()
AnimUpperBodyType GetBodyAttachmentType ()
AnimBackType GetBackAttachmentType ()
AnimRangedWeaponType GetShoulderAttachmentType ()
string GetSurfaceType (SurfaceAnimationBone limbType)
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob)
void AddNoise (NoiseParams noisePar, float noiseMultiplier=1.0)
void OnStepEvent (string pEventType, string pUserString, int pUserInt)
void OnSoundEvent (string pEventType, string pUserString, int pUserInt)
void OnParticleEvent (string pEventType, string pUserString, int pUserInt)
void ProcessWeaponEvent (string pEventType, string pUserString, int pUserInt)
void ProcessAttachmentEvent (string pEventType, string pUserString, int pUserInt)
void SetVariablesLadderSoundObjectBuilder (SoundObjectBuilder soundObjectBuilder)
void ProcessSoundEvent (string pEventType, string pUserString, int pUserInt)
AbstractWave ProcessVoiceEvent (string pEventType, string pUserString, int pUserInt)
void ProcessFeetDamageServer (int pUserInt)
bool CheckForTakeItem (EntityAI item)
bool CheckForDropItem (EntityAI item)
bool CheckForRespawn (EntityAI item)
void OverrideSlidePoseAngle (float value)
movement sliding override, originally for FB gestures
float GetSlidePoseAngle ()
void CheckAnimationOverrides ()
bool IsPlayerSelected ()
bool IsRestrained ()
bool IsInFBEmoteState ()
Checks if fullbody animation or specific locked state is active in emote manager.
void SetSuicide (bool state)
bool CommitedSuicide ()
void OnLadder (float delta_time, HumanMovementState pState)
called every command handler tick when player is on ladder
override protected void EOnContact (IEntity other, Contact extra)
protected void AttenuateSoundIfNecessary (SoundObject soundObject)
void CheckLiftWeapon ()
void ProcessLiftWeapon ()
void SetHandheldOpticsInUse (bool state)
bool IsHandheldOpticsInUse ()
bool IsLiftWeapon ()
bool IsRaised ()
bool IsFighting ()
bool CanPickupHeavyItem (notnull EntityAI item)
-------------— Checks if player can pick up heavy item ----------------------—
bool CanPickupHeavyItemSwap (notnull EntityAI item1, notnull EntityAI item2)
void SetReturnToOptics (bool state)
void RunADSTimer ()
void StopADSTimer ()
Private Attributes
ref HumanMovementState m_MovementState = new HumanMovementState()
time step for gradual update of dead screen visibilibty up to full visbility [s]
protected ref DayZPlayerImplementAiming m_AimingModel
protected ref DayZPlayerImplementMeleeCombat m_MeleeCombat
protected ref DayZPlayerMeleeFightLogic_LightHeavy m_MeleeFightLogic
protected ref DayZPlayerImplementSwimming m_Swimming
protected ref DayZPlayerImplementThrowing m_Throwing
protected ref DayZPlayerImplementJumpClimb m_JumpClimb
protected ref DayZPlayerImplementFallDamage m_FallDamage
protected ref PlayerSoundEventHandler m_PlayerSoundEventHandler
protected SHumanCommandMoveSettings m_MoveSettings
protected float m_FallYDiff
protected float m_SprintedTime
protected bool m_SprintFull
protected bool m_IsRaised
protected bool m_ShouldReload
protected bool m_Camera3rdPerson
protected bool m_CameraZoomToggle
protected bool m_bADS
private float m_WeaponRaiseTime
protected bool m_WeaponRaiseCompleted
measures time from the weapon raise start to complete raise (once per)
protected ECameraZoomType m_CameraEyeZoomLevel
protected bool m_WasIronsight
protected bool m_CameraIronsight
protected bool m_CameraOptics
protected float m_DeathDarkeningCurrentTime
protected bool m_IsTryingHoldBreath
protected bool m_IsShootingFromCamera
protected bool m_PlayerSelected
protected bool m_Suicide
protected bool m_IsUnconscious
protected bool m_ShouldBeUnconscious
bool m_UnconsciousDebug
protected int m_LastCommandBeforeUnconscious
ref WeaponDebug m_WeaponDebug
ref DeathEffectTimer m_DeathEffectTimer
ref Timer m_FightEndBlendTimer
protected bool m_ProcessFirearmMeleeHit
protected bool m_ContinueFirearmMelee
protected bool m_LiftWeapon_player
protected bool m_ProcessLiftWeapon
protected bool m_ProcessLiftWeaponState
protected int m_LastSurfaceUnderHash
protected Transport m_TransportCache
protected string m_ClimbingLadderType
bool m_isFBsymptomPlaying
protected bool m_HandheldOpticsInUse
protected bool m_ResetADS
protected int m_StepCounter
protected int m_NextVoNNoiseTime
protected ref array< ref SyncHitInfo > m_SyncedHitDataArray
protected bool m_RaiseStarted = false
protected bool m_AimingFinisherStarted = false
protected bool m_IsWeapon
private float m_CurrentWaterLevel
bool m_WasInVehicle
protected bool m_TriggerPullPlayerOutOfVehicleSynch
protected bool m_PullPlayerOutOfVehicleKeepsInLocalSpace = false
protected int m_PullPlayerOutOfVehicleState = -1
int m_ActionSoundCategoryHash
int m_DeathAnimType = -2
float m_DeathHitDir = 0
bool m_DeathJuctureSent = false
bool m_DamageHitFullbody = false
int m_DamageHitAnimType = -1.0
float m_DamageHitDir = 0.0
float m_DamageHealth = 0.0
float m_fLastHeadingDiff = 0
float m_LastHeadingAngleBlock
float m_LastHeadingAngleBlock2
float m_LastHeadingAngle
int m_LastBackSoundTime
int m_LastBackSoundTime2
float m_SoundOffset
float m_TestDamageCounter = -1
float m_DebugDirectionVal = -180
VKOSTIK - tady dat 0 misto -1.
bool m_DebugTypeVal = false
int m_DebugWeaponChangeStage = 0
string m_DebugWeaponChangeItem
int m_DebugWeaponChangeShowSlot
protected bool m_CameraEyeZoom
ref Timer m_ADSAutomationTimer
protected bool m_ADSTimerLaunched
protected bool m_ProcessWeaponRaiseCompleted
protected bool m_IsFireWeaponRaised
Static Private Attributes
static const int DEAD_SCREEN_DELAY = 1000
static const float DEFAULT_DYING_TIME = 2.5
DEPRECATED.
static const float DYING_PROGRESSION_TIME = 0.05
how long does it take to full death screen [s]
Detailed Description
Definition at line 72 of file DayZPlayerImplement.c.
Constructor & Destructor Documentation
~DayZPlayerImplement()
void ~DayZPlayerImplement () inline private
Definition at line 201 of file DayZPlayerImplement.c.
Member Function Documentation
AbortWeaponEvent()
void AbortWeaponEvent () inline private
Definition at line 1556 of file DayZPlayerImplement.c.
AddNoise()
void AddNoise (NoiseParams noisePar, float noiseMultiplier = 1.0) inline private
Definition at line 2889 of file DayZPlayerImplement.c.
References NoiseSystem::AddNoise(), GetGame(), and CGame::GetNoiseSystem().
AimingModel()
override bool AimingModel (float pDt, SDayZPlayerAimingModel pModel) inline private
This Aiming Model
Definition at line 1439 of file DayZPlayerImplement.c.
References GetCommand_Melee2(), GetMovementState(), HumanCommandMelee2::IsFinisher(), HumanMovementState::IsRaised(), HumanMovementState::m_CommandTypeId, SDayZPlayerAimingModel::m_fCurrentAimY, HumanMovementState::m_iStanceIdx, and m_MovementState.
AttenuateSoundIfNecessary()
protected void AttenuateSoundIfNecessary (SoundObject soundObject) inline private
Definition at line 3431 of file DayZPlayerImplement.c.
References GetGame(), and GetPlayer().
CameraHandler()
override int CameraHandler (int pCameraMode) inline private
This is main camera selection logic
ironsights
get movement state
VKOSTIK: v ostatnich commandech mimo COMMANDID_MOVE je m_MovementState.m_iStanceIdx - DayZPlayerConstants.STANCEIDX_ERECT m_MovementState.m_iMovement = 0 (idle)
COMMANDID_ACTION returns stance right - ERECT/CROUCH
melee camera - not melee - stays in stance camera
Definition at line 2461 of file DayZPlayerImplement.c.
References Class::CastTo(), DayZPlayerCameras::DAYZCAMERA_1ST, DayZPlayerCameras::DAYZCAMERA_1ST_UNCONSCIOUS, DayZPlayerCameras::DAYZCAMERA_1ST_VEHICLE, DayZPlayerCameras::DAYZCAMERA_3RD_CLIMB, DayZPlayerCameras::DAYZCAMERA_3RD_CRO, DayZPlayerCameras::DAYZCAMERA_3RD_CRO_RAISED, DayZPlayerCameras::DAYZCAMERA_3RD_ERC, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_RAISED, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_RAISED_MELEE, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_SPR, DayZPlayerCameras::DAYZCAMERA_3RD_JUMP, DayZPlayerCameras::DAYZCAMERA_3RD_PRO, DayZPlayerCameras::DAYZCAMERA_3RD_PRO_RAISED, DayZPlayerCameras::DAYZCAMERA_IRONSIGHTS, DayZPlayerCameras::DAYZCAMERA_OPTICS, GetCommand_Vehicle(), GetMovementState(), GetParent(), HumanCommandVehicle::GetTransport(), HumanMovementState::m_CommandTypeId, HumanMovementState::m_iMovement, HumanMovementState::m_iStanceIdx, and m_MovementState.
CanClimb()
bool CanClimb (int climbType, SHumanCommandClimbResult climbRes) inline private
Definition at line 1506 of file DayZPlayerImplement.c.
References Class::CastTo(), GetItemAccessor(), IsRaised(), HumanItemBehaviorCfg::m_bJumpAllowed, HumanMovementState::m_iStanceIdx, and m_MovementState.
CanConsumeStamina()
bool CanConsumeStamina (EStaminaConsumers consumer) inline private
Implementations only! - used on PlayerBase.
Definition at line 392 of file DayZPlayerImplement.c.
CanJump()
bool CanJump () inline private
Jump
Definition at line 1483 of file DayZPlayerImplement.c.
References DayZPlayerUtils(), GetItemAccessor(), IsRaised(), HumanItemBehaviorCfg::m_bJumpAllowed, HumanMovementState::m_iStanceIdx, and m_MovementState.
CanPickupHeavyItem()
bool CanPickupHeavyItem (notnull EntityAI item) inline private
-------------— Checks if player can pick up heavy item ----------------------—
Definition at line 3466 of file DayZPlayerImplement.c.
References DayZPlayerUtils().
CanPickupHeavyItemSwap()
bool CanPickupHeavyItemSwap (notnull EntityAI item1, notnull EntityAI item2) inline private
Definition at line 3471 of file DayZPlayerImplement.c.
CanStartConsumingStamina()
bool CanStartConsumingStamina (EStaminaConsumers consumer) inline private
Definition at line 393 of file DayZPlayerImplement.c.
CheckAnimationOverrides()
void CheckAnimationOverrides () inline private
Definition at line 3381 of file DayZPlayerImplement.c.
CheckForDropItem()
bool CheckForDropItem (EntityAI item) inline private
Definition at line 3313 of file DayZPlayerImplement.c.
CheckForRespawn()
bool CheckForRespawn (EntityAI item) inline private
Player respawn
Definition at line 3331 of file DayZPlayerImplement.c.
CheckForTakeItem()
bool CheckForTakeItem (EntityAI item) inline private
anti-cheat condition
Definition at line 3302 of file DayZPlayerImplement.c.
CheckLiftWeapon()
void CheckLiftWeapon () private
CommandHandler()
override void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
This is main command logic
handle all Camera changes, switch + zoom
handle death with high priority
handle finished commands
default behaviou after finish is to start move
debug test script command !PSOVIS
Sprint attack limiting - player has to be in full sprint for at least 0.5s
throwing handling
melee
Definition at line 1959 of file DayZPlayerImplement.c.
References UAInputAPI::ActivateModificator(), AddCommandModifier_Action(), AddNoise(), DayZPlayerImplementFallDamage(), DayZPlayerType(), UAInputAPI::DeactivateModificator(), HumanCommandClimb::DoClimbTest(), ForceStandUpForHeavyItems(), GetCommand_Fall(), GetCommand_Move(), GetCommand_Vehicle(), GetCommandModifier_Additives(), GetCommandModifier_Weapons(), HumanCommandMove::GetCurrentMovementSpeed(), GetDayZPlayerType(), DiagMenu::GetEngineValue(), GetGame(), GetInputController(), GetInstanceType(), GetMovementState(), GetPosition, CGame::GetTime(), GetUApi(), CGame::GetVoiceLevel(), HumanCommandAdditives(), HumanCommandFall(), HumanMovementState::IsInProne(), HumanMovementState::IsInRaisedProne(), HumanInputController::IsJumpClimb(), HumanInputController::IsMeleeWeaponAttack(), IsPlayerSpeaking(), HumanMovementState::IsRaised(), FallDamageData::m_Height, HumanMovementState::m_iMovement, FallDamageData::m_LandType, HumanMovementState::m_LocalMovement, m_MovementState, NoiseParams(), PhysicsIsFalling(), GearChangeActionCallback::SetVehicleCommand(), SHumanCommandClimbSettings(), StartCommand_Fall(), StartCommand_Move(), StartCommand_Swim(), StartCommand_Vehicle(), and HumanCommandVehicle::WasGearChange().
CommandHandlerDebug()
void CommandHandlerDebug (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
debug handling of adding commands
set item in hands
fuj
start show
damage test
Definition at line 2326 of file DayZPlayerImplement.c.
References AddCommandModifier_Damage(), ECE_IN_INVENTORY, GetCommandModifier_Additives(), GetCommandModifier_Weapons(), DiagMenu::GetEngineRangeValue(), GetGame(), GetPlayer(), GetPluginManager(), HumanCommandWeapons::GetRunningAction(), HumanCommandAdditives(), HumanCommandWeapons::IsActionFinished(), HumanCommandWeapons::IsEvent(), PluginDayzPlayerDebug(), RF_DEFAULT, InventoryLocation::SetHands(), HumanCommandWeapons::StartAction(), and StartCommand_Damage().
CommitedSuicide()
bool CommitedSuicide () inline private
Definition at line 3400 of file DayZPlayerImplement.c.
CompleteWeaponRaise()
void CompleteWeaponRaise () inline private
Definition at line 752 of file DayZPlayerImplement.c.
DayZPlayerImplement()
void DayZPlayerImplement () inline private
constructor
Definition at line 145 of file DayZPlayerImplement.c.
References DayZPlayerImplementFallDamage(), DayZPlayerImplementMeleeCombat(), DayZPlayerMeleeFightLogic_LightHeavy(), GetGame(), CGame::GetWorld(), World::Is3rdPersonDisabled(), and m_MeleeCombat.
DepleteStamina()
void DepleteStamina (EStaminaModifiers modifier, float dT = -1) inline private
Definition at line 394 of file DayZPlayerImplement.c.
Referenced by SymptomBase::OnAnimationFinish().
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
event from damage system
Definition at line 1288 of file DayZPlayerImplement.c.
References HumanCommandMelee2::Cancel(), component, GetCommand_Fall(), GetCommand_Melee2(), HumanCommandFall(), and DayZPlayerSyncJunctures::SendDamageHitEx().
EEKilled()
override void EEKilled (Object killer) inline private
Definition at line 625 of file DayZPlayerImplement.c.
EOnContact()
override protected void EOnContact (IEntity other, Contact extra) inline private
Phx contact event
Definition at line 3413 of file DayZPlayerImplement.c.
References GetGame(), and GetParent().
EvaluateDamageHitAnimation()
bool EvaluateDamageHitAnimation (TotalDamageResult pDamageResult, int pDamageType, EntityAI pSource, string pComponent, string pAmmoType, vector pModelPos, out int pAnimType, out float pAnimHitDir, out bool pAnimHitFullbody) inline private
selects animation type and direction based on damage system data
impact from infected attack will be light only
play full body when these coponents were hit
skip evaluation of dmg hit animation
direction
Definition at line 1210 of file DayZPlayerImplement.c.
References Math::Acos(), CGame::ConfigGetInt(), vector::Dot(), GetGame(), TotalDamageResult::GetHighestDamage(), GetMovementState(), GetPosition, m_MovementState, vector::Normalize(), and Math::RAD2DEG.
EvaluateDeathAnimation()
bool EvaluateDeathAnimation (int pDamageType, EntityAI pSource, string pAmmoType, out int pAnimType, out float pAnimHitDir) inline private
selects animation type and direction based on damage system data
direction
Definition at line 1181 of file DayZPlayerImplement.c.
References Math::Acos(), CGame::ConfigGetInt(), vector::Dot(), GetGame(), GetPosition, vector::Normalize(), and Math::RAD2DEG.
ExitSights()
void ExitSights () inline private
Definition at line 331 of file DayZPlayerImplement.c.
References GetCommandModifier_Weapons(), and HumanCommandWeapons::SetADS().
GetAimingModel()
DayZPlayerImplementAiming GetAimingModel () inline private
Definition at line 176 of file DayZPlayerImplement.c.
GetBackAttachmentType()
AnimBackType GetBackAttachmentType () inline private
Definition at line 2792 of file DayZPlayerImplement.c.
GetBodyAttachmentType()
AnimUpperBodyType GetBodyAttachmentType () inline private
Definition at line 2761 of file DayZPlayerImplement.c.
GetBootsType()
AnimBootsType GetBootsType () inline private
Definition at line 2743 of file DayZPlayerImplement.c.
GetCurrentWaterLevel()
override float GetCurrentWaterLevel () inline private
Definition at line 287 of file DayZPlayerImplement.c.
Referenced by InterruptWaterCheck(), and StaminaProcessor_Move().
GetDayZPlayerInventory()
DayZPlayerInventory GetDayZPlayerInventory () inline private
Definition at line 769 of file DayZPlayerImplement.c.
Referenced by ActionPossibilityCheck(), and CanPlayEmote().
GetDebugText()
override string GetDebugText () inline private
Definition at line 429 of file DayZPlayerImplement.c.
References GetParent().
GetEyeZoomLevel()
override int GetEyeZoomLevel () inline private
Definition at line 211 of file DayZPlayerImplement.c.
Referenced by DayZPlayerCameraBase(), HoldBreathFOVEffect(), and StdFovUpdate().
GetFallDamage()
DayZPlayerImplementFallDamage GetFallDamage () inline private
Definition at line 196 of file DayZPlayerImplement.c.
GetMeleeCombat()
DayZPlayerImplementMeleeCombat GetMeleeCombat () inline private
Definition at line 181 of file DayZPlayerImplement.c.
References m_MeleeCombat.
GetMeleeFightLogic()
DayZPlayerMeleeFightLogic_LightHeavy GetMeleeFightLogic () inline private
Definition at line 186 of file DayZPlayerImplement.c.
GetShoulderAttachmentType()
AnimRangedWeaponType GetShoulderAttachmentType () inline private
Definition at line 2814 of file DayZPlayerImplement.c.
GetSlidePoseAngle()
float GetSlidePoseAngle () inline private
Definition at line 3376 of file DayZPlayerImplement.c.
References GetDayZPlayerType().
GetSurfaceType()
string GetSurfaceType (SurfaceAnimationBone limbType) inline private
Definition at line 2864 of file DayZPlayerImplement.c.
References g_Game.
Referenced by GetEmptyingEndSoundset(), and GetEmptyingLoopSoundset().
GetThrowing()
DayZPlayerImplementThrowing GetThrowing () inline private
Definition at line 191 of file DayZPlayerImplement.c.
Referenced by ActionPossibilityCheck(), and CanPlayEmote().
GetTypeOfDeath()
int GetTypeOfDeath (int pCurrentCommandID) inline private
Definition at line 592 of file DayZPlayerImplement.c.
References GetCommand_Unconscious(), HumanCommandUnconscious::IsInWater(), and HumanCommandUnconscious::IsOnLand().
GetWeaponManager()
WeaponManager GetWeaponManager () inline private
Definition at line 838 of file DayZPlayerImplement.c.
Referenced by ActionPossibilityCheck(), CanPlayEmote(), HandsContainer::GetCombinationFlags(), Icon::OnPerformCombination(), HandsContainer::OnPerformCombination(), and ScriptedWidgetEventHandler::SetWeaponModeAndZeroing().
HandleADS()
void HandleADS () inline private
This is main command logic
artificial Auto-ADS delay
if !raised if sprinting
Definition at line 1565 of file DayZPlayerImplement.c.
References GetCommand_Melee2(), GetCommandModifier_Weapons(), GetInputController(), GetItemAccessor(), GetMovementState(), HumanItemAccessor(), IsProcessing(), HumanMovementState::IsRaised(), IsRaised(), HumanMovementState::m_iMovement, m_MovementState, HumanInputController::ResetADS(), HumanInputController::ResetFreeLookToggle(), HumanCommandWeapons::SetADS(), and HumanInputController::WeaponADS().
HandleDamageHit()
bool HandleDamageHit (int pCurrentCommandID) inline private
ignore hit impacts in prone (for now)
Definition at line 1108 of file DayZPlayerImplement.c.
References AddCommandModifier_Damage(), GetCommand_Vehicle(), GetGame(), Mission::GetHud(), CGame::GetMission(), GetPlayer(), PlayerConstants::HEAVY_HIT_THRESHOLD, HumanCommandVehicle::IsGettingIn(), HumanCommandVehicle::IsGettingOut(), HumanMovementState::m_iStanceIdx, m_MovementState, Hud::SpawnHitDirEffect(), and StartCommand_Damage().
HandleDeath()
bool HandleDeath (int pCurrentCommandID) inline private
Can't pull a body out of a car that is in water, don't need to handle that
Definition at line 508 of file DayZPlayerImplement.c.
References Class::CastTo(), g_Game, GetCommand_Vehicle(), GetGame(), GetItemAccessor(), HumanCommandVehicle::GetTransport(), CGame::GetWorld(), HumanCommandVehicle::IsGettingIn(), HumanCommandVehicle::IsGettingOut(), DayZPlayerCommandDeathCallback::m_pPlayer, PhysicsSetSolid(), World::SetVoiceOn(), StartCommand_Death(), and UnlinkFromLocalSpace().
HandleOptic()
void HandleOptic (notnull ItemOptics optic, bool inHands, HumanInputController pInputs, out bool pExitOptics) inline private
Definition at line 1011 of file DayZPlayerImplement.c.
References HumanInputController::ResetFreeLookToggle(), and UAInterface::SyncedPress_ID().
HandleView()
void HandleView () inline private
3rd person camera
Definition at line 1696 of file DayZPlayerImplement.c.
References Math::AbsFloat(), Math::AbsInt(), SoundObjectBuilder::BuildSoundObject(), HumanInputController::CameraViewChanged(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetTextArray(), GetDayZPlayerType(), GetGame(), GetInputController(), HumanInputController::GetMovement(), GetPosition, CGame::GetSoundScene(), CGame::GetTime(), IsPlayerInStance(), HumanMovementState::IsRaised(), IsRaised(), HumanMovementState::IsRaisedInProne(), HumanInputController::IsZoomToggle(), HumanMovementState::m_iMovement, HumanMovementState::m_iStanceIdx, m_MovementState, name, path, AbstractWave::SetStartOffset(), AbstractWave::SetVolumeRelative(), and SoundObject().
HandleWeapons()
void HandleWeapons (float pDt, Entity pInHands, HumanInputController pInputs, out bool pExitIronSights) inline private
HandleWeapons
fire
Definition at line 844 of file DayZPlayerImplement.c.
References Class::CastTo(), GetCommandModifier_Weapons(), GetGame(), GetInput(), GetMovementState(), HumanInputController::IsAttackButton(), HumanInputController::IsAttackButtonDown(), HumanInputController::IsFireModeChange(), HumanInputController::IsHoldBreath(), HumanMovementState::IsRaised(), HumanInputController::IsZeroingDown(), HumanInputController::IsZeroingUp(), m_MovementState, and PlayerConstants::WEAPON_RAISE_BLEND_DELAY.
HeadingModel()
override bool HeadingModel (float pDt, SDayZPlayerHeadingModel pModel) inline private
on ladder - do nothing
if it's standing from prone on back
Definition at line 1360 of file DayZPlayerImplement.c.
References DayZPlayerImplementHeading::ClampHeading(), GetCommand_Move(), GetCommand_Vehicle(), DiagMenu::GetEngineValue(), GetItemAccessor(), GetMovementState(), HumanItemAccessor(), HumanCommandVehicle::IsGettingIn(), HumanCommandVehicle::IsGettingOut(), IsLeavingUncon(), HumanCommandMove::IsStandingFromBack(), HumanMovementState::m_CommandTypeId, HumanMovementState::m_iStanceIdx, m_MovementState, HumanItemBehaviorCfg::m_StanceRotation, DayZPlayerImplementHeading::NoHeading(), and DayZPlayerImplementHeading::RotateOrient().
HideClothing()
void HideClothing (ItemOptics optic, bool state) inline private
Definition at line 2310 of file DayZPlayerImplement.c.
IsClimbingLadder()
bool IsClimbingLadder () inline private
Definition at line 406 of file DayZPlayerImplement.c.
References HumanMovementState::m_CommandTypeId, and m_MovementState.
Referenced by CanPlayEmote().
IsEyeZoom()
override bool IsEyeZoom () inline private
Legacy.
Definition at line 206 of file DayZPlayerImplement.c.
References GetEyeZoomLevel().
IsFBSymptomPlaying()
bool IsFBSymptomPlaying () inline private
Definition at line 415 of file DayZPlayerImplement.c.
IsFighting()
bool IsFighting () private
Referenced by CanPlayEmote().
IsFireWeaponRaised()
bool IsFireWeaponRaised () inline private
Definition at line 246 of file DayZPlayerImplement.c.
References GetMovementState(), HumanMovementState::IsRaised(), and m_MovementState.
IsHandheldOpticsInUse()
bool IsHandheldOpticsInUse () inline private
Definition at line 3451 of file DayZPlayerImplement.c.
IsInFBEmoteState()
bool IsInFBEmoteState () private
Checks if fullbody animation or specific locked state is active in emote manager.
IsInIronsights()
bool IsInIronsights () inline private
Definition at line 226 of file DayZPlayerImplement.c.
Referenced by ApplyExhaustion(), SelectCrossHair(), and ScriptedWidgetEventHandler::Update().
IsInOptics()
bool IsInOptics () inline private
Definition at line 231 of file DayZPlayerImplement.c.
Referenced by ApplyExhaustion(), and SelectCrossHair().
IsInThirdPerson()
override bool IsInThirdPerson () inline private
Definition at line 236 of file DayZPlayerImplement.c.
IsInVehicle()
bool IsInVehicle () inline private
Definition at line 396 of file DayZPlayerImplement.c.
References GetParent(), HumanMovementState::m_CommandTypeId, and m_MovementState.
Referenced by ScriptedWidgetEventHandler::GetActions(), ScriptedWidgetEventHandler::GetTarget(), and ScriptedWidgetEventHandler::Update().
IsLiftWeapon()
bool IsLiftWeapon () private
IsPlayerSelected()
bool IsPlayerSelected () inline private
Definition at line 3385 of file DayZPlayerImplement.c.
Referenced by ScriptedWidgetEventHandler::GetActionManager(), GetActionManager(), Update(), and ScriptedWidgetEventHandler::Update().
IsRaised()
bool IsRaised () inline private
Definition at line 3457 of file DayZPlayerImplement.c.
Referenced by FloatingCrossHair(), SelectCrossHair(), ScriptedWidgetEventHandler::Update(), and ActionManagerClient::Update().
IsRestrained()
bool IsRestrained () private
Referenced by CanPlayEmote(), and Update().
IsShootingFromCamera()
override bool IsShootingFromCamera () inline private
Definition at line 216 of file DayZPlayerImplement.c.
Referenced by OnEmoteEnd(), and StdFovUpdate().
IsSprintFull()
bool IsSprintFull () inline private
Definition at line 260 of file DayZPlayerImplement.c.
IsSwimming()
bool IsSwimming () inline private
Definition at line 401 of file DayZPlayerImplement.c.
References HumanMovementState::m_CommandTypeId, and m_MovementState.
Referenced by CanPlayEmote().
IsTryingHoldBreath()
bool IsTryingHoldBreath () inline private
Definition at line 255 of file DayZPlayerImplement.c.
IsWeaponDebugEnabled()
bool IsWeaponDebugEnabled () inline private
Definition at line 277 of file DayZPlayerImplement.c.
IsWeaponRaiseCompleted()
bool IsWeaponRaiseCompleted () inline private
Definition at line 764 of file DayZPlayerImplement.c.
LockControls()
void LockControls (bool state) inline private
Definition at line 713 of file DayZPlayerImplement.c.
References Input::ChangeGameFocus(), UIManager::CloseDialog(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), INPUT_DEVICE_GAMEPAD, INPUT_DEVICE_KEYBOARD, INPUT_DEVICE_MOUSE, and UIManager::ShowUICursor().
ModCommandHandlerAfter()
bool ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
Definition at line 1947 of file DayZPlayerImplement.c.
ModCommandHandlerBefore()
bool ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
ModOverrides
Definition at line 1937 of file DayZPlayerImplement.c.
ModCommandHandlerInside()
bool ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
Definition at line 1942 of file DayZPlayerImplement.c.
OnInputForRemote()
override void OnInputForRemote (ParamsReadContext ctx) inline private
Definition at line 775 of file DayZPlayerImplement.c.
References Error(), INPUT_UDT_HAND_REMOTE_EVENT, INPUT_UDT_INVENTORY, INPUT_UDT_WEAPON_REMOTE_EVENT, and Serializer::Read().
OnInputFromServer()
override void OnInputFromServer (ParamsReadContext ctx) inline private
Definition at line 801 of file DayZPlayerImplement.c.
References Error(), INPUT_UDT_INVENTORY, and Serializer::Read().
OnInputUserDataProcess()
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx) inline private
Definition at line 2681 of file DayZPlayerImplement.c.
References INPUT_UDT_MELEE_TARGET, m_MeleeCombat, Serializer::Read(), and vector::Zero.
OnInputUserDataReceived()
void OnInputUserDataReceived (ParamsReadContext ctx) inline private
Input userdata
Definition at line 2669 of file DayZPlayerImplement.c.
References Error(), OnInputUserDataProcess(), and Serializer::Read().
OnItemInHandsChanged()
override void OnItemInHandsChanged () inline private
Definition at line 825 of file DayZPlayerImplement.c.
References GetItemAccessor().
Referenced by HandActionBase::Action(), Execute(), NetSyncCurrentStateID(), OnAfterStoreLoad(), and TurnItemIntoItemLambda::OnSuccess().
OnJumpEnd()
void OnJumpEnd (int pLandType = 0) inline private
Definition at line 1542 of file DayZPlayerImplement.c.
OnJumpStart()
void OnJumpStart () inline private
Definition at line 1538 of file DayZPlayerImplement.c.
OnLadder()
void OnLadder (float delta_time, HumanMovementState pState) private
called every command handler tick when player is on ladder
OnMovementChanged()
void OnMovementChanged () inline private
Event, called when HumanMovementState.m_iMovement changes...walk, run, sprint, etc..
Definition at line 2576 of file DayZPlayerImplement.c.
References HumanMovementState::m_iMovement, HumanMovementState::m_LocalMovement, and m_MovementState.
OnParticleEvent()
void OnParticleEvent (string pEventType, string pUserString, int pUserInt) inline private
Definition at line 3050 of file DayZPlayerImplement.c.
OnSoundEvent()
void OnSoundEvent (string pEventType, string pUserString, int pUserInt) inline private
Definition at line 3017 of file DayZPlayerImplement.c.
References GetInstanceType(), and Debug::Log().
OnSprintEnd()
void OnSprintEnd () inline private
Definition at line 2656 of file DayZPlayerImplement.c.
References UAInputAPI::GetInputByID(), GetInstanceType(), GetUApi(), and UAInput::Unlock().
OnSprintStart()
void OnSprintStart () inline private
Definition at line 2647 of file DayZPlayerImplement.c.
References UAInputAPI::GetInputByID(), GetInstanceType(), GetUApi(), and UAInput::Lock().
OnStepEvent()
void OnStepEvent (string pEventType, string pUserString, int pUserInt) inline private
Event Processing
Definition at line 2900 of file DayZPlayerImplement.c.
References AddNoise(), SoundObjectBuilder::BuildSoundObject(), PlayerConstants::CHECK_EVERY_N_STEP, string::Contains(), Count, DayZPlayerType(), VegetationSound::GetAnimEventIds(), GetDayZPlayerType(), GetGame(), GetMovementState(), NoiseAIEvaluate::GetNoiseMultiplier(), GetPlayer(), GetPosition, DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder(), VegetationSound::GetSoundObjectBuilder(), string::Hash(), string::Length(), Debug::Log(), NoiseParams(), PlaySound(), SoundObject(), and Vector().
OnSyncJuncture()
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx) inline private
SyncJunctures
Definition at line 2724 of file DayZPlayerImplement.c.
References DayZPlayerSyncJunctures::ReadDamageHitParamsEx(), DayZPlayerSyncJunctures::ReadDeathParams(), DayZPlayerSyncJunctures::SJ_DAMAGE_HIT, and DayZPlayerSyncJunctures::SJ_DEATH.
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
Definition at line 498 of file DayZPlayerImplement.c.
References GetGame().
OverrideShootFromCamera()
void OverrideShootFromCamera (bool pState) inline private
Definition at line 221 of file DayZPlayerImplement.c.
Referenced by EmoteBase::OnBeforeStandardCallbackCreated(), and OnEmoteEnd().
OverrideSlidePoseAngle()
void OverrideSlidePoseAngle (float value) inline private
movement sliding override, originally for FB gestures
Definition at line 3365 of file DayZPlayerImplement.c.
References GetDayZPlayerType(), and StartCommand_Move().
PlaySound()
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob) inline private
Sounds
Definition at line 2879 of file DayZPlayerImplement.c.
References GetGame(), GetPosition, CGame::GetSoundScene(), and AbstractWave::SetPosition().
PlaySoundEvent()
bool PlaySoundEvent (EPlayerSoundEventID id, bool from_anim_system = false, bool is_from_server = false) inline private
Definition at line 412 of file DayZPlayerImplement.c.
Referenced by InjurySoundHandlerBase::PlaySound(), and StaminaSoundHandlerBase::Update().
PlaySoundEventEx()
bool PlaySoundEventEx (EPlayerSoundEventID id, bool from_anim_system = false, bool is_from_server = false, int param = 0) inline private
Definition at line 413 of file DayZPlayerImplement.c.
Referenced by PlaySound().
ProcessAttachmentEvent()
void ProcessAttachmentEvent (string pEventType, string pUserString, int pUserInt) inline private
Definition at line 3110 of file DayZPlayerImplement.c.
References SoundObjectBuilder::BuildSoundObject(), DayZPlayerType(), GetDayZPlayerType(), DayZPlayerTypeAttachmentSoundLookupTable::GetSoundBuilder(), PlaySound(), SoundObject(), and string::Split().
ProcessFeetDamageServer()
void ProcessFeetDamageServer (int pUserInt) private
ProcessLiftWeapon()
void ProcessLiftWeapon () private
ProcessSoundEvent()
void ProcessSoundEvent (string pEventType, string pUserString, int pUserInt) inline private
Definition at line 3174 of file DayZPlayerImplement.c.
References NoiseSystem::AddNoise(), SoundObjectBuilder::BuildSoundObject(), DayZPlayerType(), GetCommand_Ladder(), GetDayZPlayerType(), GetGame(), CGame::GetNoiseSystem(), GetPosition, PlaySound(), SoundObject(), and SoundObjectBuilder::UpdateEnvSoundControllers().
ProcessVoiceEvent()
AbstractWave ProcessVoiceEvent (string pEventType, string pUserString, int pUserInt) inline private
Definition at line 3213 of file DayZPlayerImplement.c.
References SoundObjectBuilder::BuildSoundObject(), DayZPlayerType(), GetDayZPlayerType(), DayZPlayerTypeVoiceSoundLookupTable::GetSoundBuilder(), string::Hash(), PlaySound(), SoundObjectBuilder::SetVariable(), and SoundObject().
Referenced by Play().
ProcessWeaponEvent()
void ProcessWeaponEvent (string pEventType, string pUserString, int pUserInt) inline private
Definition at line 3056 of file DayZPlayerImplement.c.
References AddNoise(), SoundObjectBuilder::BuildSoundObject(), Class::CastTo(), DayZPlayerType(), GetDayZPlayerType(), GetGame(), InventoryItemType::GetSoundEvent(), CGame::IsDedicatedServer(), PlaySound(), SoundObjectBuilder::SetVariable(), and SoundObject().
RequestSoundEvent()
void RequestSoundEvent (EPlayerSoundEventID id, bool from_server_and_client = false) private
RequestSoundEventEx()
void RequestSoundEventEx (EPlayerSoundEventID id, bool from_server_and_client = false, int param = 0) private
Referenced by DrowningMdfr::PlayDrowningSound().
ResetDeathStartTime()
void ResetDeathStartTime () inline private
Definition at line 587 of file DayZPlayerImplement.c.
References ResetDeathCooldown().
ResetWeaponRaiseProgress()
void ResetWeaponRaiseProgress () inline private
Definition at line 758 of file DayZPlayerImplement.c.
RunADSTimer()
void RunADSTimer () private
SendCompleteWeaponRaiseJuncture()
void SendCompleteWeaponRaiseJuncture () private
SendDeathJuncture()
void SendDeathJuncture (int pAnimTypeDeath, float pAnimHitDirDeath) inline private
Definition at line 616 of file DayZPlayerImplement.c.
References DayZPlayerSyncJunctures::SendDeath().
SendSoundEvent()
protected void SendSoundEvent (EPlayerSoundEventID id) private
SendSoundEventEx()
protected void SendSoundEventEx (EPlayerSoundEventID id, int param = 0) private
SetClimbingLadderType()
void SetClimbingLadderType (string value) inline private
Definition at line 386 of file DayZPlayerImplement.c.
SetCurrentWaterLevel()
override void SetCurrentWaterLevel (float pWaterLevel) inline private
Definition at line 292 of file DayZPlayerImplement.c.
Referenced by DayZPlayerImplementSwimming::HandleSwimming().
SetDeathDarknessLevel()
void SetDeathDarknessLevel (float duration, float tick_time) private
SetFallYDiff()
void SetFallYDiff (float value) inline private
Definition at line 282 of file DayZPlayerImplement.c.
SetHandheldOpticsInUse()
void SetHandheldOpticsInUse (bool state) inline private
Definition at line 3446 of file DayZPlayerImplement.c.
SetIronsights()
void SetIronsights (bool value) inline private
Definition at line 297 of file DayZPlayerImplement.c.
References GetCommandModifier_Weapons(), and HumanCommandWeapons::SetADS().
SetIsInThirdPerson()
void SetIsInThirdPerson (bool state) inline private
Definition at line 241 of file DayZPlayerImplement.c.
SetOptics()
void SetOptics (bool value) inline private
Definition at line 317 of file DayZPlayerImplement.c.
References GetCommandModifier_Weapons(), and HumanCommandWeapons::SetADS().
SetReturnToOptics()
void SetReturnToOptics (bool state) private
SetSuicide()
void SetSuicide (bool state) inline private
Definition at line 3395 of file DayZPlayerImplement.c.
Referenced by CommitSuicide(), and EmoteBase::OnCallbackEnd().
SetVariablesLadderSoundObjectBuilder()
void SetVariablesLadderSoundObjectBuilder (SoundObjectBuilder soundObjectBuilder) inline private
Definition at line 3141 of file DayZPlayerImplement.c.
References SoundObjectBuilder::SetVariable().
ShowDeadScreen()
void ShowDeadScreen (bool show, float duration) inline private
Definition at line 632 of file DayZPlayerImplement.c.
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), CGame::GetUIManager(), UIManager::ScreenFadeIn(), UIManager::ScreenFadeOut(), and OnlineServices::SetMultiplayState().
ShowWeaponDebug()
void ShowWeaponDebug (bool show) inline private
Definition at line 265 of file DayZPlayerImplement.c.
SimulateDeath()
void SimulateDeath (bool state) inline private
Definition at line 674 of file DayZPlayerImplement.c.
References g_Game, GetGame(), and CGame::GetSoundScene().
StopADSTimer()
void StopADSTimer () private
StopDeathDarkeningEffect()
override void StopDeathDarkeningEffect () inline private
Definition at line 665 of file DayZPlayerImplement.c.
Referenced by CGame::OnRespawnEvent().
StopHandEvent()
void StopHandEvent () inline private
Definition at line 1546 of file DayZPlayerImplement.c.
StopWeaponEvent()
void StopWeaponEvent () inline private
Definition at line 1551 of file DayZPlayerImplement.c.
SwitchOptics()
void SwitchOptics (ItemOptics optic, bool state) inline private
Definition at line 360 of file DayZPlayerImplement.c.
TriggerPullPlayerOutOfVehicle()
void TriggerPullPlayerOutOfVehicle () inline private
Definition at line 444 of file DayZPlayerImplement.c.
References Class::CastTo(), GetGame(), and GetParent().
TriggerPullPlayerOutOfVehicleImpl()
void TriggerPullPlayerOutOfVehicleImpl () inline private
Reset the cooldown so simulation doesn't automatically get re-disabled
Synced to re-enable simulation on client as the death processing sets disable simulation to local only
Handle own client animation freeze
Definition at line 478 of file DayZPlayerImplement.c.
References GetInstanceType(), and ResetDeathCooldown().
Field Documentation
DEAD_SCREEN_DELAY
const int DEAD_SCREEN_DELAY = 1000 static private
Definition at line 74 of file DayZPlayerImplement.c.
DEFAULT_DYING_TIME
const float DEFAULT_DYING_TIME = 2.5 static private
DEPRECATED.
Definition at line 75 of file DayZPlayerImplement.c.
DYING_PROGRESSION_TIME
const float DYING_PROGRESSION_TIME = 0.05 static private
how long does it take to full death screen [s]
Definition at line 76 of file DayZPlayerImplement.c.
m_ActionSoundCategoryHash
int m_ActionSoundCategoryHash private
Definition at line 142 of file DayZPlayerImplement.c.
m_ADSAutomationTimer
ref Timer m_ADSAutomationTimer private
Definition at line 3481 of file DayZPlayerImplement.c.
m_ADSTimerLaunched
protected bool m_ADSTimerLaunched private
Definition at line 3482 of file DayZPlayerImplement.c.
m_AimingFinisherStarted
protected bool m_AimingFinisherStarted = false private
Definition at line 133 of file DayZPlayerImplement.c.
m_AimingModel
protected ref DayZPlayerImplementAiming m_AimingModel private
Definition at line 80 of file DayZPlayerImplement.c.
m_bADS
protected bool m_bADS private
Definition at line 96 of file DayZPlayerImplement.c.
m_Camera3rdPerson
protected bool m_Camera3rdPerson private
Definition at line 94 of file DayZPlayerImplement.c.
m_CameraEyeZoom
protected bool m_CameraEyeZoom private
Definition at line 3480 of file DayZPlayerImplement.c.
m_CameraEyeZoomLevel
protected ECameraZoomType m_CameraEyeZoomLevel private
Definition at line 99 of file DayZPlayerImplement.c.
m_CameraIronsight
protected bool m_CameraIronsight private
Definition at line 101 of file DayZPlayerImplement.c.
m_CameraOptics
protected bool m_CameraOptics private
Definition at line 102 of file DayZPlayerImplement.c.
m_CameraZoomToggle
protected bool m_CameraZoomToggle private
Definition at line 95 of file DayZPlayerImplement.c.
m_ClimbingLadderType
protected string m_ClimbingLadderType private
Definition at line 123 of file DayZPlayerImplement.c.
m_ContinueFirearmMelee
protected bool m_ContinueFirearmMelee private
Definition at line 117 of file DayZPlayerImplement.c.
m_CurrentWaterLevel
private float m_CurrentWaterLevel private
Definition at line 136 of file DayZPlayerImplement.c.
m_DamageHealth
float m_DamageHealth = 0.0 private
Definition at line 1106 of file DayZPlayerImplement.c.
m_DamageHitAnimType
int m_DamageHitAnimType = -1.0 private
Definition at line 1104 of file DayZPlayerImplement.c.
m_DamageHitDir
float m_DamageHitDir = 0.0 private
Definition at line 1105 of file DayZPlayerImplement.c.
m_DamageHitFullbody
bool m_DamageHitFullbody = false private
HandleDamageHit
Definition at line 1103 of file DayZPlayerImplement.c.
m_DeathAnimType
int m_DeathAnimType = -2 private
HandleDeath
Definition at line 425 of file DayZPlayerImplement.c.
m_DeathDarkeningCurrentTime
protected float m_DeathDarkeningCurrentTime private
Definition at line 104 of file DayZPlayerImplement.c.
m_DeathEffectTimer
ref DeathEffectTimer m_DeathEffectTimer private
Definition at line 114 of file DayZPlayerImplement.c.
m_DeathHitDir
float m_DeathHitDir = 0 private
Definition at line 426 of file DayZPlayerImplement.c.
m_DeathJuctureSent
bool m_DeathJuctureSent = false private
Definition at line 427 of file DayZPlayerImplement.c.
m_DebugDirectionVal
float m_DebugDirectionVal = -180 private
VKOSTIK - tady dat 0 misto -1.
Definition at line 2318 of file DayZPlayerImplement.c.
m_DebugTypeVal
bool m_DebugTypeVal = false private
Definition at line 2319 of file DayZPlayerImplement.c.
m_DebugWeaponChangeItem
string m_DebugWeaponChangeItem private
Definition at line 2322 of file DayZPlayerImplement.c.
m_DebugWeaponChangeShowSlot
int m_DebugWeaponChangeShowSlot private
Definition at line 2323 of file DayZPlayerImplement.c.
m_DebugWeaponChangeStage
int m_DebugWeaponChangeStage = 0 private
Definition at line 2321 of file DayZPlayerImplement.c.
m_FallDamage
protected ref DayZPlayerImplementFallDamage m_FallDamage private
Definition at line 86 of file DayZPlayerImplement.c.
m_FallYDiff
protected float m_FallYDiff private
Definition at line 89 of file DayZPlayerImplement.c.
m_FightEndBlendTimer
ref Timer m_FightEndBlendTimer private
Definition at line 115 of file DayZPlayerImplement.c.
m_fLastHeadingDiff
float m_fLastHeadingDiff = 0 private
This HeadingModel
Definition at line 1357 of file DayZPlayerImplement.c.
m_HandheldOpticsInUse
protected bool m_HandheldOpticsInUse private
Definition at line 125 of file DayZPlayerImplement.c.
m_isFBsymptomPlaying
bool m_isFBsymptomPlaying private
Definition at line 124 of file DayZPlayerImplement.c.
Referenced by SmptAnimMetaBase::Play(), and SmptAnimMetaBase::~SmptAnimMetaFB().
m_IsFireWeaponRaised
protected bool m_IsFireWeaponRaised private
Definition at line 3484 of file DayZPlayerImplement.c.
m_IsRaised
protected bool m_IsRaised private
Definition at line 92 of file DayZPlayerImplement.c.
m_IsShootingFromCamera
protected bool m_IsShootingFromCamera private
Definition at line 106 of file DayZPlayerImplement.c.
m_IsTryingHoldBreath
protected bool m_IsTryingHoldBreath private
Definition at line 105 of file DayZPlayerImplement.c.
m_IsUnconscious
protected bool m_IsUnconscious private
Definition at line 109 of file DayZPlayerImplement.c.
m_IsWeapon
protected bool m_IsWeapon private
Definition at line 134 of file DayZPlayerImplement.c.
m_JumpClimb
protected ref DayZPlayerImplementJumpClimb m_JumpClimb private
Definition at line 85 of file DayZPlayerImplement.c.
m_LastBackSoundTime
int m_LastBackSoundTime private
Definition at line 1926 of file DayZPlayerImplement.c.
m_LastBackSoundTime2
int m_LastBackSoundTime2 private
Definition at line 1927 of file DayZPlayerImplement.c.
m_LastCommandBeforeUnconscious
protected int m_LastCommandBeforeUnconscious private
Definition at line 112 of file DayZPlayerImplement.c.
m_LastHeadingAngle
float m_LastHeadingAngle private
Definition at line 1925 of file DayZPlayerImplement.c.
m_LastHeadingAngleBlock
float m_LastHeadingAngleBlock private
Definition at line 1923 of file DayZPlayerImplement.c.
m_LastHeadingAngleBlock2
float m_LastHeadingAngleBlock2 private
Definition at line 1924 of file DayZPlayerImplement.c.
m_LastSurfaceUnderHash
protected int m_LastSurfaceUnderHash private
Definition at line 121 of file DayZPlayerImplement.c.
m_LiftWeapon_player
protected bool m_LiftWeapon_player private
Definition at line 118 of file DayZPlayerImplement.c.
m_MeleeCombat
protected ref DayZPlayerImplementMeleeCombat m_MeleeCombat private
Definition at line 81 of file DayZPlayerImplement.c.
m_MeleeFightLogic
protected ref DayZPlayerMeleeFightLogic_LightHeavy m_MeleeFightLogic private
Definition at line 82 of file DayZPlayerImplement.c.
m_MovementState
ref HumanMovementState m_MovementState = new HumanMovementState() private
time step for gradual update of dead screen visibilibty up to full visbility [s]
cached ptr for movement state
Definition at line 79 of file DayZPlayerImplement.c.
m_MoveSettings
protected SHumanCommandMoveSettings m_MoveSettings private
Definition at line 88 of file DayZPlayerImplement.c.
m_NextVoNNoiseTime
protected int m_NextVoNNoiseTime private
Definition at line 128 of file DayZPlayerImplement.c.
m_PlayerSelected
protected bool m_PlayerSelected private
Definition at line 107 of file DayZPlayerImplement.c.
m_PlayerSoundEventHandler
protected ref PlayerSoundEventHandler m_PlayerSoundEventHandler private
Definition at line 87 of file DayZPlayerImplement.c.
m_ProcessFirearmMeleeHit
protected bool m_ProcessFirearmMeleeHit private
Definition at line 116 of file DayZPlayerImplement.c.
m_ProcessLiftWeapon
protected bool m_ProcessLiftWeapon private
Definition at line 119 of file DayZPlayerImplement.c.
m_ProcessLiftWeaponState
protected bool m_ProcessLiftWeaponState private
Definition at line 120 of file DayZPlayerImplement.c.
m_ProcessWeaponRaiseCompleted
protected bool m_ProcessWeaponRaiseCompleted private
Definition at line 3483 of file DayZPlayerImplement.c.
m_PullPlayerOutOfVehicleKeepsInLocalSpace
protected bool m_PullPlayerOutOfVehicleKeepsInLocalSpace = false private
Definition at line 140 of file DayZPlayerImplement.c.
m_PullPlayerOutOfVehicleState
protected int m_PullPlayerOutOfVehicleState = -1 private
Definition at line 141 of file DayZPlayerImplement.c.
m_RaiseStarted
protected bool m_RaiseStarted = false private
Definition at line 132 of file DayZPlayerImplement.c.
m_ResetADS
protected bool m_ResetADS private
Definition at line 126 of file DayZPlayerImplement.c.
m_ShouldBeUnconscious
protected bool m_ShouldBeUnconscious private
Definition at line 110 of file DayZPlayerImplement.c.
m_ShouldReload
protected bool m_ShouldReload private
Definition at line 93 of file DayZPlayerImplement.c.
m_SoundOffset
float m_SoundOffset private
Definition at line 1928 of file DayZPlayerImplement.c.
m_SprintedTime
protected float m_SprintedTime private
Definition at line 90 of file DayZPlayerImplement.c.
m_SprintFull
protected bool m_SprintFull private
Definition at line 91 of file DayZPlayerImplement.c.
m_StepCounter
protected int m_StepCounter private
Definition at line 127 of file DayZPlayerImplement.c.
m_Suicide
protected bool m_Suicide private
Definition at line 108 of file DayZPlayerImplement.c.
m_Swimming
protected ref DayZPlayerImplementSwimming m_Swimming private
Definition at line 83 of file DayZPlayerImplement.c.
m_SyncedHitDataArray
protected ref array<ref SyncHitInfo> m_SyncedHitDataArray private
Definition at line 129 of file DayZPlayerImplement.c.
m_TestDamageCounter
float m_TestDamageCounter = -1 private
This is Debug functionality
Definition at line 2317 of file DayZPlayerImplement.c.
m_Throwing
protected ref DayZPlayerImplementThrowing m_Throwing private
Definition at line 84 of file DayZPlayerImplement.c.
m_TransportCache
protected Transport m_TransportCache private
Definition at line 122 of file DayZPlayerImplement.c.
m_TriggerPullPlayerOutOfVehicleSynch
protected bool m_TriggerPullPlayerOutOfVehicleSynch private
Definition at line 139 of file DayZPlayerImplement.c.
m_UnconsciousDebug
bool m_UnconsciousDebug private
Definition at line 111 of file DayZPlayerImplement.c.
m_WasInVehicle
bool m_WasInVehicle private
Definition at line 138 of file DayZPlayerImplement.c.
m_WasIronsight
protected bool m_WasIronsight private
Definition at line 100 of file DayZPlayerImplement.c.
m_WeaponDebug
ref WeaponDebug m_WeaponDebug private
Definition at line 113 of file DayZPlayerImplement.c.
m_WeaponRaiseCompleted
protected bool m_WeaponRaiseCompleted private
measures time from the weapon raise start to complete raise (once per)
Definition at line 98 of file DayZPlayerImplement.c.
m_WeaponRaiseTime
private float m_WeaponRaiseTime private
Definition at line 97 of file DayZPlayerImplement.c.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/DayZPlayerImplement.c