DayZ Scripts: SpawnDataConverter Class Reference
SpawnDataConverter Class Reference
Utility class that converts init.c format type of spawn commands to a json file, fill in the SpawnInit() with your data and call SpawnDataConverter.SpawnObjects() through script editor console, result is a json file.
Static Private Member Functions
static void SpawnObjects ()
static void SpawnInit ()
static void AddSpawnData (string objectName, vector position, vector orientation)
Static Private Attributes
static ref array< ref ITEM_SpawnerObject > Objects = new array<ref ITEM_SpawnerObject>
static string m_Path = "$mission:MySpawnData.json"
Detailed Description
Utility class that converts init.c format type of spawn commands to a json file, fill in the SpawnInit() with your data and call SpawnDataConverter.SpawnObjects() through script editor console, result is a json file.
Definition at line 60 of file ObjectSpawner.c.
Member Function Documentation
AddSpawnData()
static void AddSpawnData (string objectName, vector position, vector orientation) inline static private
Definition at line 82 of file ObjectSpawner.c.
References ITEM_SpawnerObject::name, Objects, ITEM_SpawnerObject::pos, and ITEM_SpawnerObject::ypr.
Referenced by SpawnInit().
SpawnInit()
static void SpawnInit () inline static private
Definition at line 74 of file ObjectSpawner.c.
References AddSpawnData().
Referenced by SpawnObjects().
SpawnObjects()
static void SpawnObjects () inline static private
Definition at line 65 of file ObjectSpawner.c.
References m_Path, ObjectSpawnerJson::Objects, Objects, and SpawnInit().
Field Documentation
m_Path
string m_Path = "$mission:MySpawnData.json" static private
Definition at line 63 of file ObjectSpawner.c.
Referenced by SpawnObjects().
Objects
ref array<ref ITEM_SpawnerObject> Objects = new array<ref ITEM_SpawnerObject> static private
Definition at line 62 of file ObjectSpawner.c.
Referenced by AddSpawnData(), and SpawnObjects().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/ObjectSpawner.c