DayZ Scripts: BillboardSetHandler Class Reference
BillboardSetHandler Class Reference
Private Member Functions
string GetTextureByType (string type)
void OnRPCIndex (int index)
protected bool LoadBillboardConfigs ()
Static Private Member Functions
static bool ActivateBillboardSet (string setClassName, PlayerIdentity identity)
Private Attributes
protected bool m_BillboardSetIndex = -1
protected ref array< ref BillboardSet > m_BillboardSets
Static Private Attributes
static protected const string ROOT_CLASS = "BillboardPresets"
static protected int m_SetIndexCached = -1
Member Function Documentation
ActivateBillboardSet()
static bool ActivateBillboardSet (string setClassName, PlayerIdentity identity) inline static private
References CGame::ConfigGetChildName(), g_Game, GetGame(), PlayerIdentityBase::GetPlayer(), m_SetIndexCached, ROOT_CLASS, and CGame::RPCSingleParam().
GetTextureByType()
string GetTextureByType (string type) inline private
References BillboardSet(), m_BillboardSetIndex, and m_BillboardSets.
LoadBillboardConfigs()
protected bool LoadBillboardConfigs () inline private
References BillboardSet(), CGame::ConfigGetChildName(), g_Game, GetGame(), m_BillboardSets, path, and ROOT_CLASS.
Referenced by OnRPCIndex().
OnRPCIndex()
void OnRPCIndex (int index) inline private
References LoadBillboardConfigs(), m_BillboardSetIndex, and m_BillboardSets.
Field Documentation
m_BillboardSetIndex
protected bool m_BillboardSetIndex = -1 private
Referenced by GetTextureByType(), and OnRPCIndex().
m_BillboardSets
protected ref array<ref BillboardSet> m_BillboardSets private
Referenced by GetTextureByType(), LoadBillboardConfigs(), and OnRPCIndex().
m_SetIndexCached
protected int m_SetIndexCached = -1 static private
Referenced by ActivateBillboardSet().
ROOT_CLASS
protected const string ROOT_CLASS = "BillboardPresets" static private
Referenced by ActivateBillboardSet(), and LoadBillboardConfigs().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/BillboardSet.c