DayZ Scripts: EnumTools Class Reference
EnumTools Class Reference
Private Member Functions
private void EnumTools ()
private void ~EnumTools ()
Static Private Member Functions
static string EnumToString (typename e, int enumValue)
Return string name of enum value.
static int StringToEnum (typename e, string enumName)
Return enum value from string name.
static int GetEnumSize (typename e)
Return amount of values in enum.
static int GetEnumValue (typename e, int idx)
Return the nth value in the enum.
static int GetLastEnumValue (typename e)
Return amount of values in enum.
Detailed Description
Definition at line 589 of file EnConvert.c.
Constructor & Destructor Documentation
EnumTools()
private void EnumTools () private
~EnumTools()
private void ~EnumTools () private
Member Function Documentation
EnumToString()
static string EnumToString (typename e , int enumValue) inline static private
Return string name of enum value.
DialogPriority prio = DialogPriority.WARNING;
Print(EnumTools.EnumToString(DialogPriority, prio));
Definition at line 601 of file EnConvert.c.
Referenced by Hud::Debug().
GetEnumSize()
static int GetEnumSize (typename e) inline static private
Return amount of values in enum.
Print(EnumTools.GetEnumSize(DialogPriority));
Definition at line 623 of file EnConvert.c.
Referenced by UIScriptedMenu::DrawConnectingLines(), ContentDLC::OwnsAllDLC(), Hud::RefreshVehicleHud(), RemoteDetonatorTrigger::RemoteDetonatorTrigger(), and EnProfilerTests::TestSetFlags().
GetEnumValue()
static int GetEnumValue (typename e , int idx) inline static private
Return the nth value in the enum.
Print(EnumTools.GetEnumValue(DialogPriority, 1));
Definition at line 634 of file EnConvert.c.
Referenced by ContentDLC::OwnsAllDLC(), and EnProfilerTests::TestSetFlags().
GetLastEnumValue()
static int GetLastEnumValue (typename e) inline static private
Return amount of values in enum.
Print(EnumTools.GetLastEnumValue(DialogPriority));
Definition at line 647 of file EnConvert.c.
Referenced by FireworksLauncher::FireworksLauncher(), Hud::InitBadgesAndNotifiers(), and Land_Underground_EntranceBase::Land_Underground_EntranceBase().
StringToEnum()
static int StringToEnum (typename e , string enumName) inline static private
Return enum value from string name.
Print(EnumTools.StringToEnum(DialogPriority, "WARNING"));
Definition at line 612 of file EnConvert.c.
Referenced by EnProfilerTests::TestModule().
The documentation for this class was generated from the following file:
P:/scripts/1_Core/proto/EnConvert.c