DayZ Scripts: ActionOpenDoors Class Reference
ActionOpenDoors Class Reference
Private Member Functions
void ActionOpenDoors ()
override void CreateConditionComponents ()
protected bool CheckIfDoorIsLocked ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnStartServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
Private Attributes
ref NoiseParams m_NoisePar
Detailed Description
Definition at line 1 of file ActionOpenDoors.c.
Constructor & Destructor Documentation
ActionOpenDoors()
void ActionOpenDoors () inline private
Definition at line 5 of file ActionOpenDoors.c.
References AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 23 of file ActionOpenDoors.c.
References Class::CastTo(), CheckIfDoorIsLocked(), UAMaxDistances::DEFAULT, IsBuilding(), and IsInReach().
CheckIfDoorIsLocked()
protected bool CheckIfDoorIsLocked () inline private
Definition at line 18 of file ActionOpenDoors.c.
Referenced by ActionCondition().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 12 of file ActionOpenDoors.c.
References m_ConditionItem, and m_ConditionTarget.
OnEndServer()
override void OnEndServer (ActionData action_data) inline private
Definition at line 74 of file ActionOpenDoors.c.
References NoiseSystem::AddNoisePos(), GetGame(), CGame::GetNoiseSystem(), m_NoisePar, ActionData::m_Player, ActionData::m_Target, and NoiseParams().
OnStartServer()
override void OnStartServer (ActionData action_data) inline private
Definition at line 61 of file ActionOpenDoors.c.
References Class::CastTo(), and ActionData::m_Target.
Field Documentation
m_NoisePar
ref NoiseParams m_NoisePar private
Definition at line 3 of file ActionOpenDoors.c.
Referenced by OnEndServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Interact/ActionOpenDoors.c