DayZ Scripts: Mask_Base Class Reference
Mask_Base Class Reference
gas mask base
Private Member Functions
override void SetActions ()
override void SetActions ()
override protected void InitGlobalExclusionValues ()
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId)
override void SetActions ()
override protected void InitGlobalExclusionValues ()
override bool IsGasMask ()
override array< int > GetEffectWidgetTypes ()
override bool AllowFoodConsumption ()
override void OnDebugSpawn ()
EntityAI GetExternalFilter ()
bool HasValidFilter ()
has either external or integrated non-empty non-ruined filter ?
float GetFilterQuantityMax ()
float GetFilterQuantity ()
float GetFilterQuantity01 ()
bool IsExternalFilterAttached ()
bool HasIntegratedFilter ()
bool CanHaveExternalFilter ()
bool ConsumeQuantity (float quantity, PlayerBase consumer_player)
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player)
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player, float quantity)
override protected void InitGlobalExclusionValues ()
void MouthRag ()
override bool CanDetachAttachment (EntityAI parent)
override bool IsObstructingVoice ()
override int GetVoiceEffect ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnWasAttached (EntityAI parent, int slot_id)
void SetIncomingLambaBool (bool state)
bool GetIncomingLambdaBool ()
override void SetActions ()
override protected void InitGlobalExclusionValues ()
override void SetActions ()
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId)
Private Attributes
float m_LowFilterEventTime
bool m_IncomingLambdaChange
Detailed Description
gas mask base
Member Function Documentation
AllowFoodConsumption()
override bool AllowFoodConsumption () inline private
CanDetachAttachment()
override bool CanDetachAttachment (EntityAI parent) inline private
References m_IncomingLambdaChange.
CanHaveExternalFilter()
bool CanHaveExternalFilter () inline private
ConsumeQuantity()
bool ConsumeQuantity (float quantity, PlayerBase consumer_player) inline private
References GetQuantity(), and HasQuantity().
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
References Class::CastTo(), ECE_PLACE_ON_SURFACE, GetGame(), and RF_DEFAULT.
GetAttachmentExclusionInitSlotValue() [1/2]
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId) inline private
GetAttachmentExclusionInitSlotValue() [2/2]
override protected set< int > GetAttachmentExclusionInitSlotValue (int slotId) inline private
GetEffectWidgetTypes()
override array< int > GetEffectWidgetTypes () inline private
GetExternalFilter()
EntityAI GetExternalFilter () inline private
GetFilterQuantity()
float GetFilterQuantity () inline private
References GetQuantity().
GetFilterQuantity01()
float GetFilterQuantity01 () inline private
References GetQuantity(), GetQuantityMax(), and Math::InverseLerp().
GetFilterQuantityMax()
float GetFilterQuantityMax () inline private
References GetQuantityMax(), and HasQuantity().
GetIncomingLambdaBool()
bool GetIncomingLambdaBool () inline private
References m_IncomingLambdaChange.
GetVoiceEffect()
override int GetVoiceEffect () inline private
HasIntegratedFilter()
bool HasIntegratedFilter () inline private
References HasQuantity().
HasValidFilter()
bool HasValidFilter () inline private
has either external or integrated non-empty non-ruined filter ?
References GetQuantity().
InitGlobalExclusionValues() [1/4]
override protected void InitGlobalExclusionValues () inline private
InitGlobalExclusionValues() [2/4]
override protected void InitGlobalExclusionValues () inline private
InitGlobalExclusionValues() [3/4]
override protected void InitGlobalExclusionValues () inline private
InitGlobalExclusionValues() [4/4]
override protected void InitGlobalExclusionValues () inline private
IsExternalFilterAttached()
bool IsExternalFilterAttached () inline private
IsGasMask()
override bool IsGasMask () inline private
IsObstructingVoice()
override bool IsObstructingVoice () inline private
MouthRag()
void MouthRag () inline private
OnDebugSpawn()
override void OnDebugSpawn () inline private
OnQuantityConsumed() [1/2]
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player) inline private
OnQuantityConsumed() [2/2]
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player, float quantity) inline private
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id) inline private
SetActions() [1/5]
override void SetActions () inline private
References AddAction().
SetActions() [2/5]
override void SetActions () inline private
References AddAction().
SetActions() [3/5]
override void SetActions () inline private
References AddAction().
SetActions() [4/5]
override void SetActions () inline private
References AddAction().
SetActions() [5/5]
override void SetActions () inline private
References AddAction().
SetIncomingLambaBool()
void SetIncomingLambaBool (bool state) inline private
Field Documentation
m_IncomingLambdaChange
bool m_IncomingLambdaChange private
Referenced by CanDetachAttachment(), and GetIncomingLambdaBool().
m_LowFilterEventTime
float m_LowFilterEventTime private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/Clothing/Balaclava3Holes_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MaskBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/MouthRag.c
P:/scripts/4_World/Entities/ItemBase/Clothing/BalaclavaMask_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/Clothing/CrookedNose.c
P:/scripts/4_World/Entities/ItemBase/Clothing/FaceCover_improvised.c
P:/scripts/4_World/Entities/ItemBase/Clothing/HockeyMask.c
P:/scripts/4_World/Entities/ItemBase/Clothing/SantasBeard.c
P:/scripts/4_World/Entities/ItemBase/Clothing/SurgicalMask.c
P:/scripts/4_World/Entities/ItemBase/Clothing_Base.c