DayZ Scripts: HumanCommandMelee2 Class Reference
HumanCommandMelee2 Class Reference
Private Member Functions
private void HumanCommandMelee2 ()
private void ~HumanCommandMelee2 ()
proto native void ContinueCombo (bool pHeavyHit, float pComboValue, EntityAI target=null, vector hitPos=vector.Zero)
marks command to continue to combo
proto native bool IsInComboRange ()
returns true if hit is in range, where person can continue to combo
proto native bool WasHit ()
is true only once after hit event
proto native void Cancel ()
cancels command melee and goes to HumanCommandMove
proto native bool IsOnBack ()
is on back in prone stance?
proto native int GetComboCount ()
proto native int GetCurrentHitType ()
proto native bool IsFinisher ()
Static Private Attributes
static const int HIT_TYPE_LIGHT = 0
static const int HIT_TYPE_HEAVY = 1
static const int HIT_TYPE_FINISHER = 2
static const int HIT_TYPE_FINISHER_NECK = 3
Constructor & Destructor Documentation
HumanCommandMelee2()
private void HumanCommandMelee2 () inline private
~HumanCommandMelee2()
private void ~HumanCommandMelee2 () inline private
Member Function Documentation
Cancel()
proto native void Cancel () private
cancels command melee and goes to HumanCommandMove
Referenced by DayZPlayer::EEHitBy().
ContinueCombo()
proto native void ContinueCombo (bool pHeavyHit, float pComboValue, EntityAI target = null, vector hitPos = vector.Zero) private
marks command to continue to combo
GetComboCount()
proto native int GetComboCount () private
GetCurrentHitType()
proto native int GetCurrentHitType () private
IsFinisher()
proto native bool IsFinisher () private
Referenced by DayZPlayer::AimingModel().
IsInComboRange()
proto native bool IsInComboRange () private
returns true if hit is in range, where person can continue to combo
IsOnBack()
proto native bool IsOnBack () private
is on back in prone stance?
WasHit()
proto native bool WasHit () private
is true only once after hit event
Referenced by HandleHitEvent().
Field Documentation
HIT_TYPE_FINISHER
const int HIT_TYPE_FINISHER = 2 static private
Referenced by DetermineFinisherAnimation().
HIT_TYPE_FINISHER_NECK
const int HIT_TYPE_FINISHER_NECK = 3 static private
Referenced by DetermineFinisherAnimation().
HIT_TYPE_HEAVY
const int HIT_TYPE_HEAVY = 1 static private
HIT_TYPE_LIGHT
const int HIT_TYPE_LIGHT = 0 static private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/human.c