DayZ Scripts: ConsoleToolbarWidgetHandlerBase Class Reference
ConsoleToolbarWidgetHandlerBase Class Reference
Private Member Functions
void OnWidgetScriptInit (Widget w)
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
protected void UpdateControlsElements (EInputDeviceType pInputDeviceType=EInputDeviceType.UNKNOWN)
Private Attributes
Widget m_ToolbarWidget
RichTextWidget m_ToolbarText
Member Function Documentation
OnInputDeviceChanged()
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
References ScriptedWidgetEventHandler::UpdateControlsElements().
Referenced by OnWidgetScriptInit().
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w) inline private
References GetGame(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), ScriptInvoker::Insert(), m_ToolbarText, m_ToolbarWidget, OnInputDeviceChanged(), and ScriptedWidgetEventHandler::UpdateControlsElements().
UpdateControlsElements()
protected void UpdateControlsElements (EInputDeviceType pInputDeviceType = EInputDeviceType.UNKNOWN) inline private
References m_ToolbarWidget.
Field Documentation
m_ToolbarText
RichTextWidget m_ToolbarText private
Referenced by OnWidgetScriptInit().
m_ToolbarWidget
Widget m_ToolbarWidget private
Referenced by OnWidgetScriptInit(), and UpdateControlsElements().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/NewUI/ConsoleToolbarHandler.c