DayZ Scripts: ActionDigInStash Class Reference
ActionDigInStash Class Reference
Private Member Functions
void ActionDigInStash ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void SpawnParticleShovelRaise (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override string GetAdminLogMessage (ActionData action_data)
Static Private Attributes
static float m_DigStashSlopeTolerance = 0.6
Detailed Description
Definition at line 9 of file ActionDigInStash.c.
Constructor & Destructor Documentation
ActionDigInStash()
void ActionDigInStash () inline private
Definition at line 13 of file ActionDigInStash.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
was initialized from inventory?
Check slope angle
Definition at line 29 of file ActionDigInStash.c.
References Class::CastTo(), GetGame(), CGame::GetHighestSurfaceYDifference(), m_DigStashSlopeTolerance, and CGame::SurfaceUnderObject().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 23 of file ActionDigInStash.c.
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string GetAdminLogMessage (ActionData action_data) inline private
Definition at line 165 of file ActionDigInStash.c.
References string::Format(), ActionData::m_Player, and ActionData::m_Target.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
Definition at line 104 of file ActionDigInStash.c.
References SpawnParticleShovelRaise().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
Definition at line 111 of file ActionDigInStash.c.
References GetGame(), and SpawnParticleShovelRaise().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
Definition at line 126 of file ActionDigInStash.c.
References InventoryLocation::DumpToStringNullSafe(), ECE_PLACE_ON_SURFACE, ErrorEx, GetGame(), GameInventory::LocationCanRemoveEntity(), Debug::Log(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
SpawnParticleShovelRaise()
void SpawnParticleShovelRaise (ActionData action_data) inline private
Definition at line 121 of file ActionDigInStash.c.
References ParticleList::DIGGING_STASH, ActionData::m_Player, and ParticleManager().
Referenced by OnExecuteClient(), and OnExecuteServer().
Field Documentation
m_DigStashSlopeTolerance
float m_DigStashSlopeTolerance = 0.6 static private
Definition at line 11 of file ActionDigInStash.c.
Referenced by ActionCondition().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionDigInStash.c