DayZ Scripts: PainKillersMdfr Class Reference
PainKillersMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnReconnect (PlayerBase player)
override string GetDebugText ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const int LIFETIME = 240
const int ACTIVATION_DELAY = 15
Detailed Description
Definition at line 1 of file PainKillersMdfr.c.
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
Definition at line 15 of file PainKillersMdfr.c.
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
Definition at line 56 of file PainKillersMdfr.c.
References GetAttachedTime(), and LIFETIME.
GetDebugText()
override string GetDebugText () inline private
Definition at line 25 of file PainKillersMdfr.c.
References GetAttachedTime(), LIFETIME, and string::ToString().
Init()
override void Init () inline private
Definition at line 5 of file PainKillersMdfr.c.
References DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), m_ID, m_IsPersistent, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void OnActivate (PlayerBase player) inline private
Definition at line 31 of file PainKillersMdfr.c.
References m_Player.
OnDeactivate()
override void OnDeactivate (PlayerBase player) inline private
Definition at line 43 of file PainKillersMdfr.c.
References m_Player.
OnReconnect()
override void OnReconnect (PlayerBase player) inline private
Definition at line 20 of file PainKillersMdfr.c.
References OnActivate().
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
Definition at line 70 of file PainKillersMdfr.c.
References ACTIVATION_DELAY, GetAttachedTime(), and m_Player.
Field Documentation
ACTIVATION_DELAY
const int ACTIVATION_DELAY = 15 private
Definition at line 4 of file PainKillersMdfr.c.
Referenced by OnTick().
LIFETIME
const int LIFETIME = 240 private
Definition at line 3 of file PainKillersMdfr.c.
Referenced by DeactivateCondition(), and GetDebugText().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/PainKillersMdfr.c