DayZ Scripts: ActionToggleNVMode Class Reference
ActionToggleNVMode Class Reference
Private Member Functions
void ActionToggleNVMode ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
void SwitchMode (ActionData action_data)
Detailed Description
Definition at line 2 of file ActionToggleNVMode.c.
Constructor & Destructor Documentation
ActionToggleNVMode()
void ActionToggleNVMode () inline private
Definition at line 4 of file ActionToggleNVMode.c.
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 23 of file ActionToggleNVMode.c.
References Class::CastTo().
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 12 of file ActionToggleNVMode.c.
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool HasTarget () inline private
Definition at line 18 of file ActionToggleNVMode.c.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data) inline private
Definition at line 39 of file ActionToggleNVMode.c.
References SwitchMode().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
Definition at line 34 of file ActionToggleNVMode.c.
References SwitchMode().
SwitchMode()
void SwitchMode (ActionData action_data) inline private
Definition at line 44 of file ActionToggleNVMode.c.
References ActionData::m_MainItem, GameConstants::OPTICS_STATE_DAY, and GameConstants::OPTICS_STATE_NIGHTVISION.
Referenced by OnExecuteClient(), and OnExecuteServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionToggleNVMode.c