DayZ Scripts: Land_Misc_Through_Static Class Reference
Land_Misc_Through_Static Class Reference
Private Member Functions
override EWaterSourceObjectType GetWaterSourceObjectType ()
override int GetLiquidSourceType ()
override void SetActions ()
Member Function Documentation
GetLiquidSourceType()
override int GetLiquidSourceType () inline private
References LIQUID_FRESHWATER.
GetWaterSourceObjectType()
override EWaterSourceObjectType GetWaterSourceObjectType () inline private
SetActions()
override void SetActions () inline private
References ActionWashHandsWell(), AddAction(), and RemoveAction().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Building/Industrial/Misc/Land_Misc_Through_Static.c