DayZ Scripts: FryingPan Class Reference
FryingPan Class Reference
Private Member Functions
void FryingPan ()
DEPRECATED.
void ~FryingPan ()
override bool IsContainer ()
override bool CanHaveTemperature ()
override float GetQuantityNormalizedScripted ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override void SetActions ()
override void EEDelete (EntityAI parent)
void Synchronize ()
override void OnVariablesSynchronized ()
void RemoveAudioVisualsOnClient ()
void RefreshAudioVisualsOnClient (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
void RefreshAudioVisuals (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
void RemoveAudioVisuals ()
void ParticleCookingStart (int particle_id)
void ParticleCookingStop ()
protected void SoundCookingStart (string sound_name)
DEPRECATED.
protected void SoundCookingStop ()
Private Attributes
protected CookingMethodType m_CookingMethod
protected bool m_CookingIsDone
protected bool m_CookingIsEmpty
protected bool m_CookingIsBurned
protected Particle m_ParticleCooking
protected int m_ParticlePlaying = ParticleList.INVALID
protected int PARTICLE_BAKING_START = ParticleList.COOKING_BAKING_START
protected int PARTICLE_BAKING_DONE = ParticleList.COOKING_BAKING_DONE
protected int PARTICLE_DRYING_START = ParticleList.COOKING_DRYING_START
protected int PARTICLE_DRYING_DONE = ParticleList.COOKING_DRYING_DONE
protected int PARTICLE_BURNING_DONE = ParticleList.COOKING_BURNING_DONE
protected SoundOnVehicle m_SoundCooking
protected EffectSound m_SoundEffectCooking
DEPRECATED.
protected string m_SoundPlaying = ""
const string SOUND_BAKING_START = "Baking_SoundSet"
const string SOUND_BAKING_DONE = "Baking_Done_SoundSet"
DEPRECATED.
const string SOUND_DRYING_START = "Drying_SoundSet"
DEPRECATED.
const string SOUND_DRYING_DONE = "Drying_Done_SoundSet"
DEPRECATED.
const string SOUND_BURNING_DONE = "Food_Burning_SoundSet"
DEPRECATED.
Constructor & Destructor Documentation
FryingPan()
void FryingPan () inline private
DEPRECATED.
~FryingPan()
void ~FryingPan () inline private
Member Function Documentation
CanHaveTemperature()
override bool CanHaveTemperature () inline private
CanLoadItemIntoCargo()
override bool CanLoadItemIntoCargo (EntityAI item) inline private
References IsCargoException4x3().
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent) inline private
References IsCargoException4x3().
CanReceiveItemIntoCargo()
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
References IsCargoException4x3().
EEDelete()
override void EEDelete (EntityAI parent) inline private
References RemoveAudioVisuals().
GetQuantityNormalizedScripted()
override float GetQuantityNormalizedScripted () inline private
IsContainer()
override bool IsContainer () inline private
OnVariablesSynchronized()
override void OnVariablesSynchronized () inline private
References m_CookingIsBurned, m_CookingIsDone, m_CookingIsEmpty, m_CookingMethod, RefreshAudioVisuals(), and RemoveAudioVisuals().
ParticleCookingStart()
void ParticleCookingStart (int particle_id) inline private
References GetGame(), m_ParticleCooking, m_ParticlePlaying, particle_id, ParticleCookingStop(), and ParticleManager().
Referenced by RefreshAudioVisuals().
ParticleCookingStop()
void ParticleCookingStop () inline private
References GetGame(), ParticleList::INVALID, m_ParticleCooking, m_ParticlePlaying, and Particle::Stop().
Referenced by ParticleCookingStart(), and RemoveAudioVisuals().
RefreshAudioVisuals()
void RefreshAudioVisuals (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned) inline private
References PARTICLE_BAKING_DONE, PARTICLE_BAKING_START, PARTICLE_BURNING_DONE, PARTICLE_DRYING_DONE, PARTICLE_DRYING_START, and ParticleCookingStart().
Referenced by OnVariablesSynchronized().
RefreshAudioVisualsOnClient()
void RefreshAudioVisualsOnClient (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned) inline private
References m_CookingIsBurned, m_CookingIsDone, m_CookingIsEmpty, m_CookingMethod, and Synchronize().
Referenced by CookWithEquipment().
RemoveAudioVisuals()
void RemoveAudioVisuals () inline private
References ParticleCookingStop().
Referenced by EEDelete(), and OnVariablesSynchronized().
RemoveAudioVisualsOnClient()
void RemoveAudioVisualsOnClient () inline private
References m_CookingMethod, and Synchronize().
Referenced by FireplaceBase::EEItemDetached(), ItemBase::RemoveCookingAudioVisuals(), and StopCooling().
SetActions()
override void SetActions () inline private
References ActionAttach(), ActionDetach(), and AddAction().
SoundCookingStart()
protected void SoundCookingStart (string sound_name) private
DEPRECATED.
SoundCookingStop()
protected void SoundCookingStop () private
Synchronize()
void Synchronize () inline private
References GetGame().
Referenced by RefreshAudioVisualsOnClient(), and RemoveAudioVisualsOnClient().
Field Documentation
m_CookingIsBurned
protected bool m_CookingIsBurned private
Referenced by OnVariablesSynchronized(), and RefreshAudioVisualsOnClient().
m_CookingIsDone
protected bool m_CookingIsDone private
Referenced by OnVariablesSynchronized(), and RefreshAudioVisualsOnClient().
m_CookingIsEmpty
protected bool m_CookingIsEmpty private
Referenced by OnVariablesSynchronized(), and RefreshAudioVisualsOnClient().
m_CookingMethod
protected CookingMethodType m_CookingMethod private
Referenced by OnVariablesSynchronized(), RefreshAudioVisualsOnClient(), and RemoveAudioVisualsOnClient().
m_ParticleCooking
protected Particle m_ParticleCooking private
Referenced by ParticleCookingStart(), and ParticleCookingStop().
m_ParticlePlaying
protected int m_ParticlePlaying = ParticleList.INVALID private
Referenced by ParticleCookingStart(), and ParticleCookingStop().
m_SoundCooking
protected SoundOnVehicle m_SoundCooking private
m_SoundEffectCooking
protected EffectSound m_SoundEffectCooking private
DEPRECATED.
m_SoundPlaying
protected string m_SoundPlaying = "" private
PARTICLE_BAKING_DONE
protected int PARTICLE_BAKING_DONE = ParticleList.COOKING_BAKING_DONE private
Referenced by RefreshAudioVisuals().
PARTICLE_BAKING_START
protected int PARTICLE_BAKING_START = ParticleList.COOKING_BAKING_START private
Referenced by RefreshAudioVisuals().
PARTICLE_BURNING_DONE
protected int PARTICLE_BURNING_DONE = ParticleList.COOKING_BURNING_DONE private
Referenced by RefreshAudioVisuals().
PARTICLE_DRYING_DONE
protected int PARTICLE_DRYING_DONE = ParticleList.COOKING_DRYING_DONE private
Referenced by RefreshAudioVisuals().
PARTICLE_DRYING_START
protected int PARTICLE_DRYING_START = ParticleList.COOKING_DRYING_START private
Referenced by RefreshAudioVisuals().
SOUND_BAKING_DONE
const string SOUND_BAKING_DONE = "Baking_Done_SoundSet" private
DEPRECATED.
SOUND_BAKING_START
const string SOUND_BAKING_START = "Baking_SoundSet" private
SOUND_BURNING_DONE
const string SOUND_BURNING_DONE = "Food_Burning_SoundSet" private
DEPRECATED.
SOUND_DRYING_DONE
const string SOUND_DRYING_DONE = "Drying_Done_SoundSet" private
DEPRECATED.
SOUND_DRYING_START
const string SOUND_DRYING_START = "Drying_SoundSet" private
DEPRECATED.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Inventory_Base/FryingPan.c