DayZ Scripts: ActionRepairVehiclePartBase Class Reference
ActionRepairVehiclePartBase Class Reference
Private Member Functions
override void CreateConditionComponents ()
override void OnFinishProgressServer (ActionData action_data)
protected void AdjustVehicleHealthServer (ActionData action_data)
protected void AdjustItemQuantityServer (ActionData action_data)
override ActionData CreateActionData ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Private Attributes
protected string m_CurrentDamageZone
Member Function Documentation
AdjustItemQuantityServer()
protected void AdjustItemQuantityServer (ActionData action_data) inline private
Referenced by OnFinishProgressServer().
AdjustVehicleHealthServer()
protected void AdjustVehicleHealthServer (ActionData action_data) inline private
References Math::Clamp(), GameConstants::DAMAGE_BADLY_DAMAGED_VALUE, GameConstants::DAMAGE_DAMAGED_VALUE, GameConstants::DAMAGE_RUINED_VALUE, GetGame(), m_CurrentDamageZone, Math::RandomFloatInclusive(), GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
Referenced by OnFinishProgressServer().
CreateActionData()
override ActionData CreateActionData () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References ActionBase::m_ConditionItem, ActionBase::m_ConditionTarget, and UAMaxDistances::REPAIR.
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
References RepairVehiclePartActionReciveData::m_DamageZoneRecived.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References AdjustItemQuantityServer(), and AdjustVehicleHealthServer().
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
References ActionBase::HasTarget(), RepairVehiclePartActionReciveData::m_DamageZoneRecived, and Serializer::Read().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
References Class::CastTo(), ActionBase::HasTarget(), m_CurrentDamageZone, and Serializer::Write().
Field Documentation
m_CurrentDamageZone
protected string m_CurrentDamageZone private
Referenced by ActionRepairBoatChassis::ActionCondition(), ActionRepairCarChassis::ActionCondition(), AdjustVehicleHealthServer(), and WriteToContext().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionRepairVehiclePartBase.c