DayZ Scripts: MouseButtonInfo Class Reference
MouseButtonInfo Class Reference
Private Member Functions
void MouseButtonInfo (int button)
int GetButtonID ()
int GetTimeLastPress ()
int GetTimeLastRelease ()
void Press ()
void Release ()
bool IsButtonDown ()
Private Attributes
private int m_ButtonID
private int m_TimeLastPress
private int m_TimeLastRelease
Constructor & Destructor Documentation
MouseButtonInfo()
void MouseButtonInfo (int button) inline private
References m_ButtonID, m_TimeLastPress, and m_TimeLastRelease.
Member Function Documentation
GetButtonID()
int GetButtonID () inline private
References m_ButtonID.
Referenced by PluginBase::GetMouseButtonInfo(), and PluginBase::OnFrame().
GetTimeLastPress()
int GetTimeLastPress () inline private
References m_TimeLastPress.
Referenced by PluginBase::OnFrame(), and PluginBase::OnMouseButtonRelease().
GetTimeLastRelease()
int GetTimeLastRelease () inline private
References m_TimeLastRelease.
Referenced by PluginBase::OnMouseButtonRelease().
IsButtonDown()
bool IsButtonDown () inline private
References m_TimeLastPress, and m_TimeLastRelease.
Referenced by PluginBase::OnFrame().
Press()
void Press () inline private
References GetGame(), CGame::GetTime(), and m_TimeLastPress.
Referenced by PluginBase::OnMouseButtonPress().
Release()
void Release () inline private
References GetGame(), CGame::GetTime(), and m_TimeLastRelease.
Referenced by PluginBase::OnMouseButtonRelease().
Field Documentation
m_ButtonID
private int m_ButtonID private
Referenced by GetButtonID(), and MouseButtonInfo().
m_TimeLastPress
private int m_TimeLastPress private
Referenced by GetTimeLastPress(), IsButtonDown(), MouseButtonInfo(), and Press().
m_TimeLastRelease
private int m_TimeLastRelease private
Referenced by GetTimeLastRelease(), IsButtonDown(), MouseButtonInfo(), and Release().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/MouseButtonInfo.c