DayZ Scripts: EntityAI Class Reference
EntityAI Class Reference
Private Member Functions
proto native int GetLaddersCount ()
proto native vector GetLadderPosTop (int ladderIndex)
proto native vector GetLadderPosBottom (int ladderIndex)
proto native int GetDoorIndex (int componentIndex)
Gets the index of the door based on the view geometry component index.
proto native int GetDoorCount ()
Returns the number of the doors in the building.
proto native bool IsDoorOpen (int index)
When the door is requested to be fully open (animation wanted phase is greater than 0.5)
proto native bool IsDoorOpening (int index)
When the wanted phase is at the open phase target (1.0)
proto native bool IsDoorOpeningAjar (int index)
When the wanted phase is at the ajar phase target (0.2)
proto native bool IsDoorClosing (int index)
When the wanted phase is at the close phase target (0.0)
proto native bool IsDoorOpened (int index)
When the phase is at the open phase target (1.0)
proto native bool IsDoorOpenedAjar (int index)
When the phase is at the ajar phase target (0.2)
proto native bool IsDoorClosed (int index)
When the phase is at the close phase target (0.0)
proto native bool IsDoorLocked (int index)
When the door is locked.
proto native void PlayDoorSound (int index)
Plays the appropriate sound at the door, based on animation phase and state.
proto native void OpenDoor (int index)
Attempts to open the door.
proto native void CloseDoor (int index)
Attempts to close the door.
proto native void LockDoor (int index, bool force=false)
Locks the door if not already locked, resets the door health. 'force = true' will close the door if open.
proto native void UnlockDoor (int index)
Unlocks the door if locked.
proto native vector GetDoorSoundPos (int index)
Position in world space for where the door sounds are played from.
proto native float GetDoorSoundDistance (int index)
Audible distance for the door sound.
proto native void OutputDoorLog ()
Requires special build as logging is disabled even on internal builds due to memory usage. Used for checking of possible causes of navmesh desync.
int GetNearestDoorBySoundPos (vector position)
Gets the nearest door based on the sound position (quick and dirty function for debugging)
void OnDoorOpenStart (DoorStartParams params)
Event for when the door starts opening.
void OnDoorOpenFinish (DoorFinishParams params)
Event for when the door finishes opening.
void OnDoorOpenAjarStart (DoorStartParams params)
Event for when the door starts opening ajarred (usually after unlock)
void OnDoorOpenAjarFinish (DoorFinishParams params)
Event for when the door finishes opening ajarred (usually after unlock)
void OnDoorCloseStart (DoorStartParams params)
Event for when the door starts closing.
void OnDoorCloseFinish (DoorFinishParams params)
Event for when the door finishes closing.
void OnDoorLocked (DoorLockParams params)
Event for when the door is locked.
void OnDoorUnlocked (DoorLockParams params)
Event for when the door is unlocked.
bool CanDoorBeOpened (int doorIndex, bool checkIfLocked=false)
bool CanDoorBeClosed (int doorIndex)
bool CanDoorBeLocked (int doorIndex)
Check if the door is closed and if the door is unlocked.
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
override bool IsBuilding ()
override bool CanObstruct ()
override bool IsHealthVisible ()
void Building ()
override bool IsInventoryVisible ()
override int GetMeleeTargetType ()
proto native InventoryItemType GetInventoryItemType ()
proto native void SwitchOn (bool onOff)
Some inventoryItem devices can be switched on/off (radios, transmitters)
proto native bool IsOn ()
Some inventoryItem devices can be switched on/off (radios, transmitters)
proto native void EnableCollisionsWithCharacter (bool state)
collisions with character
proto native bool HasCollisionsWithCharacter ()
proto native MeleeCombatData GetMeleeCombatData ()
proto native void ThrowPhysically (DayZPlayer player, vector force, bool collideWithCharacters=true)
proto native void ForceFarBubble (bool state)
Sets the item to use the server configured 'networkRangeFar' instead of 'networkRangeNear'.
void InventoryItem ()
void OnRightClick ()
event bool OnUseFromInventory (Man owner)
string GetTooltip ()
Get tooltip text.
override bool IsInventoryItem ()
int GetMeleeMode ()
int GetMeleeHeavyMode ()
int GetMeleeSprintMode ()
override bool IsMeleeWeapon ()
bool IsMeleeFinisher ()
void PlayImpactSound (float weight, float velocity, int surfaceHash)
protected void InitImpactSoundData ()
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob)
void PlaySoundByAnimEvent (EAnimSoundEventID id)
string GetImpactSurfaceType (IEntity other, Contact impact)
string GetImpactSurfaceTypeEx (IEntity other, Contact impact, out int liquid)
string GetRuinedMeleeAmmoType ()
returns ammo (projectile) used in melee if the item is destroyed. Override higher for specific use
float ProcessImpactSound (IEntity other, Contact extra, float weight, out int surfaceHash)
float ProcessImpactSoundEx (IEntity other, Contact extra, float weight, out int surfaceHash, out int liquidType)
proto native UAInterface GetInputInterface ()
Returns player's input interface.
proto native PlayerIdentity GetIdentity ()
Returns player's identity.
proto native EntityAI GetDrivingVehicle ()
Returns vehicle which this Man object is driving. If this Man object isn't as driver of any vehicle it will return NULL.
proto native owned string GetCurrentWeaponMode ()
proto native void SetSpeechRestricted (bool state)
Set speech restriction.
proto native bool IsSpeechRestricted ()
Check if player has resctricted speech.
proto native void SetFaceTexture (string texture_name)
Texture that is used on the Man's face and hands.
proto native void SetFaceMaterial (string material_name)
Material that is used on the Man's face and hands.
proto native bool IsSoundInsideBuilding ()
proto native bool IsCameraInsideVehicle ()
proto native owned string GetMasterAttenuation ()
proto native void SetMasterAttenuation (string masterAttenuation)
void Man ()
override bool IsMan ()
override bool IsHealthVisible ()
override bool HasFixedActionTargetCursorPosition ()
bool IsUnconscious ()
bool IsUnconsciousStateOnly ()
uncon command might be still in progress but state already changed (for simple checks only - eg.: UI)
int GetPlayerState ()
void AddItemToDelete (EntityAI item)
override bool CanDropEntity (notnull EntityAI item)
void OnItemInHandsChanged ()
bool NeedInventoryJunctureFromServer (notnull EntityAI item, EntityAI currParent, EntityAI newParent)
void LocalDestroyEntityInHands ()
void PredictiveMoveItemFromHandsToInventory ()
void JunctureDeleteItem (EntityAI item)
override bool CanBeSkinned ()
override bool DisableVicinityIcon ()
void UpdateInventoryMenu ()
bool IsInventorySoftLocked ()
void SetInventorySoftLock (bool status)
bool IsInTransport ()
returns true if man is in transport, false otherwise
void StopDeathDarkeningEffect ()
bool PhysicalPredictiveDropItem (EntityAI entity, bool heavy_item_only=true)
void SetProcessUIWarning (bool state)
void OnGameplayDataHandlerSync ()
bool CanPlaceItem (EntityAI item)
void Transport ()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override int GetMeleeTargetType ()
protected override event GetOwnerStateType ()
protected override event GetMoveType ()
proto native void Synchronize ()
Synchronizes car's state in case the simulation is not running.
proto native int CrewSize ()
Returns crew capacity of this vehicle.
proto native int CrewPositionIndex (int componentIdx)
proto native int CrewMemberIndex (Human player)
proto native Human CrewMember (int posIdx)
proto native Human CrewDriver ()
proto void CrewEntry (int posIdx, out vector pos, out vector dir)
Reads entry point and direction into vehicle on given position in model space.
proto void CrewEntryWS (int posIdx, out vector pos, out vector dir)
Reads entry point and direction into vehicle on given position in world space.
proto void CrewTransform (int posIdx, out vector mat[4])
Returns crew transformation indside vehicle in model space.
proto void CrewTransformWS (int posIdx, out vector mat[4])
Returns crew transformation indside vehicle in world space.
proto native void CrewGetIn (Human player, int posIdx)
Performs transfer of player from world into vehicle on given position.
proto native Human CrewGetOut (int posIdx)
Performs transfer of player from vehicle into world from given position.
proto native void CrewDeath (int posIdx)
Handles death of player in vehicle and awakes its physics if needed.
override bool IsTransport ()
override bool IsIgnoredByConstruction ()
override bool IsHealthVisible ()
override bool ShowZonesHealth ()
override int GetHideIconMask ()
float GetMomentum ()
bool IsVitalSparkPlug ()
string GetVehicleType ()
string GetActionCompNameFuel ()
float GetActionDistanceFuel ()
vector GetRefillPointPosWS ()
bool IsAnyCrewPresent ()
float GetTransportCameraDistance ()
void MarkCrewMemberUnconscious (int crewMemberIndex)
void MarkCrewMemberDead (int crewMemberIndex)
protected void HandleByCrewMemberState (ECrewMemberState state)
vector GetTransportCameraOffset ()
int GetAnimInstance ()
int GetSeatAnimationType (int posIdx)
int Get3rdPersonCameraType ()
bool CrewCanGetThrough (int posIdx)
bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
bool CanReachSeatFromDoors (string pSeatSelection, vector pFromPos, float pDistance=1.0)
bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
int GetSeatIndexFromDoor (string pDoorSelection)
bool IsIgnoredObject (Object o)
void SetEngineZoneReceivedHit (bool pState)
bool HasEngineZoneReceivedHit ()
bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight, inout vector extents, out vector transform[4])
bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight=0.5, float horizontalExtents=0.5, float playerHeight=1.7)
Shape DebugFreeAreaAtDoor (int currentSeat, float maxAllowedObjHeight=0.5, float horizontalExtents=0.5, float playerHeight=1.7)
void AdvancedCommunication ()
void TurnOnTransmitter ()
void TurnOffTransmitter ()
void InitializeActions ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
void SetActions ()
void AddAction (typename actionName)
void RemoveAction (typename actionName)
void JunctureTakeEntityToHands (notnull EntityAI item)
hand juncture
void PredictiveTakeEntityToHands (EntityAI item)
void LocalTakeEntityToHands (EntityAI item)
void ServerTakeEntityToHands (EntityAI item)
void TakeEntityToHandsImpl (InventoryMode mode, EntityAI item)
protected bool ReplaceItemWithNewImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
!hand -> !hand replace
bool LocalReplaceItemWithNew (ReplaceItemWithNewLambdaBase lambda)
bool ServerReplaceItemWithNew (ReplaceItemWithNewLambdaBase lambda)
protected bool ReplaceItemElsewhereWithNewInHandsImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
!hand replace -> hand
bool LocalReplaceItemElsewhereWithNewInHands (ReplaceItemWithNewLambdaBase lambda)
bool ServerReplaceItemElsewhereWithNewInHands (ReplaceItemWithNewLambdaBase lambda)
protected bool ReplaceItemInHandsWithNewImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
hand replace
bool LocalReplaceItemInHandsWithNew (ReplaceItemWithNewLambdaBase lambda)
bool ServerReplaceItemInHandsWithNew (ReplaceItemWithNewLambdaBase lambda)
protected bool ReplaceItemInHandsWithNewElsewhereImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
hand replace2
bool LocalReplaceItemInHandsWithNewElsewhere (ReplaceItemWithNewLambdaBase lambda)
bool ServerReplaceItemInHandsWithNewElsewhere (ReplaceItemWithNewLambdaBase lambda)
bool JunctureTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
to inv juncture
override bool PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
override bool LocalTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
override bool ServerTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
protected bool TakeEntityToInventoryImpl (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item)
bool JunctureTakeEntityToCargo (notnull EntityAI item)
to cgo juncture
override bool PredictiveTakeEntityToCargo (notnull EntityAI item)
override bool LocalTakeEntityToCargo (notnull EntityAI item)
override bool ServerTakeEntityToCargo (notnull EntityAI item)
protected bool TakeEntityToCargoImpl (InventoryMode mode, notnull EntityAI item)
bool JunctureTakeEntityAsAttachment (notnull EntityAI item)
as att juncture
override bool PredictiveTakeEntityAsAttachment (notnull EntityAI item)
override bool LocalTakeEntityAsAttachment (notnull EntityAI item)
override bool ServerTakeEntityAsAttachment (notnull EntityAI item)
protected bool TakeEntityAsAttachmentImpl (InventoryMode mode, notnull EntityAI item)
bool JunctureTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
as att ex juncture
override bool PredictiveTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
override bool LocalTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
override bool ServerTakeEntityAsAttachmentEx (notnull EntityAI item, int slot)
protected bool TakeEntityAsAttachmentExImpl (InventoryMode mode, notnull EntityAI item, int slot)
bool JunctureSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
swap juncture
bool PredictiveSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
bool LocalSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
bool ServerSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
protected bool SwapEntitiesImpl (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
bool JunctureForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
ForceSwap juncture.
bool PredictiveForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
bool LocalForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
bool ServerForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
protected bool ForceSwapEntitiesImpl (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
bool JunctureTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
to target inv juncture
override bool PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool PredictiveTakeOrSwapAttachment (notnull EntityAI item)
override bool LocalTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
protected bool TakeEntityToTargetInventoryImpl (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
bool JunctureTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
to target cgo ex juncture
override bool PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
override bool LocalTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
override bool ServerTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
protected bool TakeEntityToTargetCargoExImpl (InventoryMode mode, notnull CargoBase cargo, notnull EntityAI item, int row, int col)
bool JunctureTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
to target cgo juncture
override bool PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
override bool LocalTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
override bool ServerTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
protected bool TakeEntityToTargetCargoImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
bool JunctureTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
to target att ex juncture
override bool PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
override bool LocalTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
override bool ServerTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
protected bool TakeEntityToTargetAttachmentExImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item, int slot)
bool JunctureTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
to target att juncture
override bool PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
override bool LocalTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
override bool ServerTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
protected bool TakeEntityToTargetAttachmentImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
bool JunctureTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
to dst juncture
override bool PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
override bool LocalTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
override bool ServerTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
protected bool TakeToDstImpl (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
proto native bool StatRegister (string name)
proto native float StatGet (string name)
Gets counter value of the specified stat type.
proto void StatGetCounter (string name, out string value)
Gets counter value as string of the specified stat type.
proto void StatGetAsTime (string name, out string value)
Gets counter value as formatted time string of the specified stat type.
proto native void StatUpdate (string name, float value)
Updates stat counter with given value.
proto native void StatUpdateByTime (string name)
Updates stat counter by time.
proto native void StatUpdateByPosition (string name)
Updates stat counter by player's actual position.
proto native void StatUpdateByGivenPos (string name, vector pos)
Updates stat counter by given position.
proto native void StatInvokeUpdate ()
proto native void StatSyncToClient ()
Private Attributes
ref TIntArray m_InteractActions
private SoundLookupTable m_SoundImpactTable
private float m_SoundContactTickTime
private bool m_IsMeleeWeapon = false
ref TIntArray m_SingleUseActions
ref TIntArray m_ContinuousActions
protected bool m_EngineZoneReceivedHit
protected vector m_fuelPos
protected ref set< int > m_UnconsciousCrewMemberIndices
protected ref set< int > m_DeadCrewMemberIndices
TInputActionMap m_InputActionMap
bool m_ActionsInitialize
Static Private Attributes
static private const float SOUND_CONTACT_SKIP = 0.33
static ref map< typename, ref TInputActionMap > m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap>
protected ref ScriptInvoker m_OnItemAddedToHands
protected ref ScriptInvoker m_OnItemRemovedFromHands
HumanInventory GetHumanInventory ()
inventory
ScriptInvoker GetOnItemAddedToHands ()
ScriptInvoker GetOnItemRemovedFromHands ()
void EEItemIntoHands (EntityAI item)
void EEItemOutOfHands (EntityAI item)
bool JunctureDropEntity (notnull EntityAI item)
drop juncture
override bool PredictiveDropEntity (notnull EntityAI item)
override bool LocalDropEntity (notnull EntityAI item)
override bool ServerDropEntity (notnull EntityAI item)
protected bool DropEntityImpl (InventoryMode mode, notnull EntityAI owner, notnull EntityAI item)
Detailed Description
Base native class of all vehicles in game.
Member Function Documentation
AddAction()
void AddAction (typename actionName) inline private
References Debug::ActionLog(), ActionManagerBase(), ActionBase::GetInputType(), LogManager::IsActionLogEnable(), Debug::LogError(), m_ActionsInitialize, and m_InputActionMap.
AddItemToDelete()
void AddItemToDelete (EntityAI item) private
AdvancedCommunication()
void AdvancedCommunication () inline private
References GetGame(), GetPlayer(), and m_ActionsInitialize.
Building()
void Building () inline private
References g_Game, GetType(), and m_InteractActions.
CanBeSkinned()
override bool CanBeSkinned () inline private
CanDoorBeClosed()
bool CanDoorBeClosed (int doorIndex) inline private
References IsDoorOpen().
CanDoorBeLocked()
bool CanDoorBeLocked (int doorIndex) inline private
Check if the door is closed and if the door is unlocked.
References IsDoorLocked(), and IsDoorOpen().
CanDoorBeOpened()
bool CanDoorBeOpened (int doorIndex, bool checkIfLocked = false) inline private
References IsDoorLocked(), and IsDoorOpen().
CanDropEntity()
override bool CanDropEntity (notnull EntityAI item) inline private
CanObstruct()
override bool CanObstruct () inline private
CanPlaceItem()
bool CanPlaceItem (EntityAI item) private
CanReachDoorsFromSeat()
bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
CanReachSeatFromDoors()
bool CanReachSeatFromDoors (string pSeatSelection, vector pFromPos, float pDistance = 1.0) inline private
CanReachSeatFromSeat()
bool CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
CloseDoor()
proto native void CloseDoor (int index) private
Attempts to close the door.
Referenced by OnAction().
CrewCanGetThrough()
bool CrewCanGetThrough (int posIdx) inline private
CrewDeath()
proto native void CrewDeath (int posIdx) private
Handles death of player in vehicle and awakes its physics if needed.
CrewDriver()
proto native Human CrewDriver () private
Returns the driver Null can be returned if no Human is present.
CrewEntry()
proto void CrewEntry (int posIdx, out vector pos, out vector dir) private
Reads entry point and direction into vehicle on given position in model space.
CrewEntryWS()
proto void CrewEntryWS (int posIdx, out vector pos, out vector dir) private
Reads entry point and direction into vehicle on given position in world space.
CrewGetIn()
proto native void CrewGetIn (Human player, int posIdx) private
Performs transfer of player from world into vehicle on given position.
CrewGetOut()
proto native Human CrewGetOut (int posIdx) private
Performs transfer of player from vehicle into world from given position.
CrewMember()
proto native Human CrewMember (int posIdx) private
Returns crew member based on position index. Null can be returned if no Human is present on the given position.
CrewMemberIndex()
proto native int CrewMemberIndex (Human player) private
Returns crew member index based on player's instance. -1 is returned when the player is not isnide.
CrewPositionIndex()
proto native int CrewPositionIndex (int componentIdx) private
Returns crew member index based on action component index. -1 is returned when no crew position corresponds to given component index.
CrewSize()
proto native int CrewSize () private
Returns crew capacity of this vehicle.
CrewTransform()
proto void CrewTransform (int posIdx, out vector mat[4]) private
Returns crew transformation indside vehicle in model space.
CrewTransformWS()
proto void CrewTransformWS (int posIdx, out vector mat[4]) private
Returns crew transformation indside vehicle in world space.
DebugFreeAreaAtDoor()
Shape DebugFreeAreaAtDoor (int currentSeat, float maxAllowedObjHeight = 0.5, float horizontalExtents = 0.5, float playerHeight = 1.7) inline private
References ARGB(), Debug::DrawBox(), Transport::IsAreaAtDoorFree(), and Shape.
DisableVicinityIcon()
override bool DisableVicinityIcon () inline private
Referenced by VicinityContainer::UpdateInterval().
DropEntityImpl()
protected bool DropEntityImpl (InventoryMode mode, notnull EntityAI owner, notnull EntityAI item) inline private
References HumanInventory::DropEntity(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureDropEntity(), LocalDropEntity(), PredictiveDropEntity(), and ServerDropEntity().
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
References component.
EEItemIntoHands()
void EEItemIntoHands (EntityAI item) inline private
EEItemOutOfHands()
void EEItemOutOfHands (EntityAI item) inline private
EnableCollisionsWithCharacter()
proto native void EnableCollisionsWithCharacter (bool state) private
collisions with character
ForceFarBubble()
proto native void ForceFarBubble (bool state) private
Sets the item to use the server configured 'networkRangeFar' instead of 'networkRangeNear'.
ForceSwapEntitiesImpl()
protected bool ForceSwapEntitiesImpl (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline private
References HumanInventory::ForceSwapEntities(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureForceSwapEntities(), LocalForceSwapEntities(), PredictiveForceSwapEntities(), and ServerForceSwapEntities().
Get3rdPersonCameraType()
int Get3rdPersonCameraType () inline private
References Error().
GetActionCompNameFuel()
string GetActionCompNameFuel () inline private
GetActionDistanceFuel()
float GetActionDistanceFuel () inline private
GetActions()
override void GetActions (typename action_input_type , out array< ActionBase_Basic > actions) inline private
References InitializeActions(), m_ActionsInitialize, and m_InputActionMap.
Referenced by ScriptConsoleItemsTab::ListItemRelatedActions().
GetAnimInstance()
int GetAnimInstance () inline private
References Error().
GetCurrentWeaponMode()
proto native owned string GetCurrentWeaponMode () private
GetDebugActions()
override void GetDebugActions (out TSelectableActionInfoArrayEx outputList) inline private
References SAT_DEBUG_ACTION.
GetDoorCount()
proto native int GetDoorCount () private
Returns the number of the doors in the building.
Referenced by GetNearestDoorBySoundPos().
GetDoorIndex()
proto native int GetDoorIndex (int componentIndex) private
Gets the index of the door based on the view geometry component index.
GetDoorSoundDistance()
proto native float GetDoorSoundDistance (int index) private
Audible distance for the door sound.
GetDoorSoundPos()
proto native vector GetDoorSoundPos (int index) private
Position in world space for where the door sounds are played from.
Referenced by GetNearestDoorBySoundPos().
GetDrivingVehicle()
proto native EntityAI GetDrivingVehicle () private
Returns vehicle which this Man object is driving. If this Man object isn't as driver of any vehicle it will return NULL.
GetHideIconMask()
override int GetHideIconMask () inline private
Referenced by VicinitySlotsContainer::ExcludeFromContainer().
GetHumanInventory()
HumanInventory GetHumanInventory () inline private
inventory
Referenced by HandActionBase::Action(), DropEntityImpl(), ForceSwapEntitiesImpl(), InventoryItem::GetRecipesActions(), LocalDestroyEntityInHands(), HandStateBase::OnEntry(), PredictiveMoveItemFromHandsToInventory(), HumanInventory::RedirectToHandEvent(), ReplaceItemElsewhereWithNewInHandsImpl(), ReplaceItemInHandsWithNewElsewhereImpl(), ReplaceItemInHandsWithNewImpl(), ReplaceItemWithNewImpl(), SwapEntitiesImpl(), TakeEntityAsAttachmentExImpl(), TakeEntityAsAttachmentImpl(), TakeEntityToCargoImpl(), TakeEntityToHandsImpl(), TakeEntityToInventoryImpl(), and TakeToDstImpl().
GetIdentity()
proto native PlayerIdentity GetIdentity () private
Returns player's identity.
GetImpactSurfaceType()
string GetImpactSurfaceType (IEntity other, Contact impact) inline private
GetImpactSurfaceTypeEx()
string GetImpactSurfaceTypeEx (IEntity other, Contact impact, out int liquid) inline private
References GetGame(), DayZPhysics::GetHitSurfaceAndLiquid(), vector::Length(), vector::Normalized(), Contact::Position, Contact::RelativeVelocityBefore, and CGame::SurfaceUnderObjectExCorrectedLiquid().
GetInputInterface()
proto native UAInterface GetInputInterface () private
Returns player's input interface.
GetInventoryItemType()
proto native InventoryItemType GetInventoryItemType () private
GetLadderPosBottom()
proto native vector GetLadderPosBottom (int ladderIndex) private
GetLadderPosTop()
proto native vector GetLadderPosTop (int ladderIndex) private
GetLaddersCount()
proto native int GetLaddersCount () private
GetMasterAttenuation()
proto native owned string GetMasterAttenuation () private
GetMeleeCombatData()
proto native MeleeCombatData GetMeleeCombatData () private
GetMeleeHeavyMode()
int GetMeleeHeavyMode () inline private
GetMeleeMode()
int GetMeleeMode () inline private
GetMeleeSprintMode()
int GetMeleeSprintMode () inline private
GetMeleeTargetType() [1/2]
override int GetMeleeTargetType () inline private
Referenced by EvaluateHit(), and DayZInfected::FightLogic().
GetMeleeTargetType() [2/2]
override int GetMeleeTargetType () inline private
GetMomentum()
float GetMomentum () inline private
References dBodyGetMass(), GetVelocity(), and vector::Length().
GetMoveType()
protected override event GetMoveType () inline private
GetNearestDoorBySoundPos()
int GetNearestDoorBySoundPos (vector position) inline private
Gets the nearest door based on the sound position (quick and dirty function for debugging)
References vector::DistanceSq(), GetDoorCount(), and GetDoorSoundPos().
Referenced by OnAction().
GetOnItemAddedToHands()
ScriptInvoker GetOnItemAddedToHands () inline private
References m_OnItemAddedToHands.
GetOnItemRemovedFromHands()
ScriptInvoker GetOnItemRemovedFromHands () inline private
References m_OnItemRemovedFromHands.
GetOwnerStateType()
protected override event GetOwnerStateType () inline private
GetPlayerState()
int GetPlayerState () inline private
GetRefillPointPosWS()
vector GetRefillPointPosWS () inline private
GetRuinedMeleeAmmoType()
string GetRuinedMeleeAmmoType () inline private
returns ammo (projectile) used in melee if the item is destroyed. Override higher for specific use
GetSeatAnimationType()
int GetSeatAnimationType (int posIdx) inline private
References Error().
GetSeatIndexFromDoor()
int GetSeatIndexFromDoor (string pDoorSelection) inline private
GetTooltip()
string GetTooltip () inline private
Get tooltip text.
GetTransportCameraDistance()
float GetTransportCameraDistance () inline private
GetTransportCameraOffset()
vector GetTransportCameraOffset () inline private
GetVehicleType()
string GetVehicleType () inline private
HandleByCrewMemberState()
protected void HandleByCrewMemberState (ECrewMemberState state) private
HasCollisionsWithCharacter()
proto native bool HasCollisionsWithCharacter () private
HasEngineZoneReceivedHit()
bool HasEngineZoneReceivedHit () inline private
HasFixedActionTargetCursorPosition()
override bool HasFixedActionTargetCursorPosition () inline private
InitializeActions()
void InitializeActions () inline private
References m_AdvComTypeActionsMap, m_InputActionMap, SetActions(), and Type.
InitImpactSoundData()
protected void InitImpactSoundData () inline private
References AnimSoundLookupTableBank(), and AnimSoundObjectBuilderBank::GetInstance().
InventoryItem()
void InventoryItem () inline private
IsAnyCrewPresent()
bool IsAnyCrewPresent () inline private
IsAreaAtDoorFree() [1/2]
bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight, inout vector extents, out vector transform[4]) inline private
References GetGame(), CGame::IsBoxColliding(), Math3D::MatrixMultiply4(), Math3D::MatrixToAngles(), vector::RotationMatrixFromAngles(), and vector::Up.
IsAreaAtDoorFree() [2/2]
bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight = 0.5, float horizontalExtents = 0.5, float playerHeight = 1.7) inline private
References Transport::IsAreaAtDoorFree().
IsBuilding()
override bool IsBuilding () inline private
Referenced by PluginBase::SpawnEntityOnCursorDir().
IsCameraInsideVehicle()
proto native bool IsCameraInsideVehicle () private
IsDoorClosed()
proto native bool IsDoorClosed (int index) private
When the phase is at the close phase target (0.0)
IsDoorClosing()
proto native bool IsDoorClosing (int index) private
When the wanted phase is at the close phase target (0.0)
IsDoorLocked()
proto native bool IsDoorLocked (int index) private
When the door is locked.
Referenced by CanDoorBeLocked(), and CanDoorBeOpened().
IsDoorOpen()
proto native bool IsDoorOpen (int index) private
When the door is requested to be fully open (animation wanted phase is greater than 0.5)
Referenced by CanDoorBeClosed(), CanDoorBeLocked(), and CanDoorBeOpened().
IsDoorOpened()
proto native bool IsDoorOpened (int index) private
When the phase is at the open phase target (1.0)
IsDoorOpenedAjar()
proto native bool IsDoorOpenedAjar (int index) private
When the phase is at the ajar phase target (0.2)
IsDoorOpening()
proto native bool IsDoorOpening (int index) private
When the wanted phase is at the open phase target (1.0)
IsDoorOpeningAjar()
proto native bool IsDoorOpeningAjar (int index) private
When the wanted phase is at the ajar phase target (0.2)
IsHealthVisible() [1/3]
override bool IsHealthVisible () inline private
IsHealthVisible() [2/3]
override bool IsHealthVisible () inline private
IsHealthVisible() [3/3]
override bool IsHealthVisible () inline private
IsIgnoredByConstruction()
override bool IsIgnoredByConstruction () inline private
Referenced by IsColliding(), and IsCollidingEx().
IsIgnoredObject()
bool IsIgnoredObject (Object o) inline private
If the player can't interact (hint: collide) with the object, then it is ignored
Ignore any player that is currently in this vehicle
References Class::CastTo(), dBodyGetInteractionLayer(), dGetInteractionLayer(), and HumanCommandVehicle::GetTransport().
IsInTransport()
bool IsInTransport () inline private
returns true if man is in transport, false otherwise
References GetParent().
IsInventoryItem()
override bool IsInventoryItem () inline private
IsInventorySoftLocked()
bool IsInventorySoftLocked () inline private
IsInventoryVisible()
override bool IsInventoryVisible () inline private
Referenced by VicinityContainer::UpdateInterval().
IsMan()
override bool IsMan () inline private
Referenced by ActionBase::Can(), Entity::CanBeTargetedByAI(), Clothing_Base::CanLoadItemIntoCargoClothingConditions(), ClothingBase::CanPutAsAttachment(), Clothing::CanPutInCargo(), Clothing_Base::CanPutInCargoClothingConditions(), Clothing_Base::CanReceiveItemIntoCargoClothingConditions(), VicinityItemManager::ExcludeFromContainer_Phase1(), ActionTargetsCursor::GetItemHealth(), Entity::InitTemperature(), InventoryItem::OnItemLocationChanged(), Clothing_Base::SmershException(), and Entity::UseConfigInitTemperature().
IsMeleeFinisher()
bool IsMeleeFinisher () inline private
IsMeleeWeapon()
override bool IsMeleeWeapon () inline private
Referenced by Achievements::OnPlayerKilled(), and PluginBase::PlayerHitBy().
IsOn()
proto native bool IsOn () private
Some inventoryItem devices can be switched on/off (radios, transmitters)
IsSoundInsideBuilding()
proto native bool IsSoundInsideBuilding () private
IsSpeechRestricted()
proto native bool IsSpeechRestricted () private
Check if player has resctricted speech.
IsTransport()
override bool IsTransport () inline private
IsUnconscious()
bool IsUnconscious () private
IsUnconsciousStateOnly()
bool IsUnconsciousStateOnly () private
uncon command might be still in progress but state already changed (for simple checks only - eg.: UI)
IsVitalSparkPlug()
bool IsVitalSparkPlug () inline private
JunctureDeleteItem()
void JunctureDeleteItem (EntityAI item) inline private
JunctureDropEntity()
bool JunctureDropEntity (notnull EntityAI item) inline private
drop juncture
References DropEntityImpl().
Referenced by PredictiveDropEntity().
JunctureForceSwapEntities()
bool JunctureForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline private
ForceSwap juncture.
References ForceSwapEntitiesImpl().
JunctureSwapEntities()
bool JunctureSwapEntities (notnull EntityAI item1, notnull EntityAI item2) inline private
swap juncture
References SwapEntitiesImpl().
JunctureTakeEntityAsAttachment()
bool JunctureTakeEntityAsAttachment (notnull EntityAI item) inline private
as att juncture
References TakeEntityAsAttachmentImpl().
Referenced by PredictiveTakeEntityAsAttachment().
JunctureTakeEntityAsAttachmentEx()
bool JunctureTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline private
as att ex juncture
References TakeEntityAsAttachmentExImpl().
Referenced by PredictiveTakeEntityAsAttachmentEx().
JunctureTakeEntityToCargo()
bool JunctureTakeEntityToCargo (notnull EntityAI item) inline private
to cgo juncture
References TakeEntityToCargoImpl().
Referenced by PredictiveTakeEntityToCargo().
JunctureTakeEntityToHands()
void JunctureTakeEntityToHands (notnull EntityAI item) inline private
hand juncture
References TakeEntityToHandsImpl().
Referenced by PredictiveTakeEntityToHands().
JunctureTakeEntityToInventory()
bool JunctureTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline private
to inv juncture
References TakeEntityToInventoryImpl().
Referenced by PredictiveTakeEntityToInventory().
JunctureTakeEntityToTargetAttachment()
bool JunctureTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline private
to target att juncture
References TakeEntityToTargetAttachmentImpl().
Referenced by PredictiveTakeEntityToTargetAttachment().
JunctureTakeEntityToTargetAttachmentEx()
bool JunctureTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline private
to target att ex juncture
References TakeEntityToTargetAttachmentExImpl().
Referenced by PredictiveTakeEntityToTargetAttachmentEx().
JunctureTakeEntityToTargetCargo()
bool JunctureTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline private
to target cgo juncture
References TakeEntityToTargetCargoImpl().
Referenced by PredictiveTakeEntityToTargetCargo().
JunctureTakeEntityToTargetCargoEx()
bool JunctureTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline private
to target cgo ex juncture
References TakeEntityToTargetCargoExImpl().
Referenced by PredictiveTakeEntityToTargetCargoEx().
JunctureTakeEntityToTargetInventory()
bool JunctureTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
to target inv juncture
References TakeEntityToTargetInventoryImpl().
Referenced by PredictiveTakeEntityToTargetInventory().
JunctureTakeToDst()
bool JunctureTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline private
to dst juncture
References TakeToDstImpl().
Referenced by PredictiveTakeToDst().
LocalDestroyEntityInHands()
void LocalDestroyEntityInHands () inline private
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::LocalDestroyEntity(), syncDebugPrint(), and UpdateInventoryMenu().
LocalDropEntity()
override bool LocalDropEntity (notnull EntityAI item) inline private
References DropEntityImpl().
Referenced by UnlockServer().
LocalForceSwapEntities()
bool LocalForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline private
References ForceSwapEntitiesImpl().
LocalReplaceItemElsewhereWithNewInHands()
bool LocalReplaceItemElsewhereWithNewInHands (ReplaceItemWithNewLambdaBase lambda) inline private
References ReplaceItemElsewhereWithNewInHandsImpl().
LocalReplaceItemInHandsWithNew()
bool LocalReplaceItemInHandsWithNew (ReplaceItemWithNewLambdaBase lambda) inline private
References ReplaceItemInHandsWithNewImpl().
LocalReplaceItemInHandsWithNewElsewhere()
bool LocalReplaceItemInHandsWithNewElsewhere (ReplaceItemWithNewLambdaBase lambda) inline private
References ReplaceItemInHandsWithNewElsewhereImpl().
LocalReplaceItemWithNew()
bool LocalReplaceItemWithNew (ReplaceItemWithNewLambdaBase lambda) inline private
References ReplaceItemWithNewImpl().
LocalSwapEntities()
bool LocalSwapEntities (notnull EntityAI item1, notnull EntityAI item2) inline private
References SwapEntitiesImpl().
LocalTakeEntityAsAttachment()
override bool LocalTakeEntityAsAttachment (notnull EntityAI item) inline private
References TakeEntityAsAttachmentImpl().
Referenced by ActionAttachWheels::OnExecuteClient(), ActionInsertSparkplug::OnExecuteClient(), ActionAttachWheels::OnExecuteServer(), and ActionInsertSparkplug::OnExecuteServer().
LocalTakeEntityAsAttachmentEx()
override bool LocalTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline private
References TakeEntityAsAttachmentExImpl().
Referenced by ActionAttachWheels::OnExecuteClient(), and ActionAttachWheels::OnExecuteServer().
LocalTakeEntityToCargo()
override bool LocalTakeEntityToCargo (notnull EntityAI item) inline private
References TakeEntityToCargoImpl().
LocalTakeEntityToHands()
void LocalTakeEntityToHands (EntityAI item) inline private
References TakeEntityToHandsImpl().
LocalTakeEntityToInventory()
override bool LocalTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline private
References TakeEntityToInventoryImpl().
LocalTakeEntityToTargetAttachment()
override bool LocalTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline private
References TakeEntityToTargetAttachmentImpl().
LocalTakeEntityToTargetAttachmentEx()
override bool LocalTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline private
References TakeEntityToTargetAttachmentExImpl().
LocalTakeEntityToTargetCargo()
override bool LocalTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline private
References TakeEntityToTargetCargoImpl().
LocalTakeEntityToTargetCargoEx()
override bool LocalTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline private
References TakeEntityToTargetCargoExImpl().
LocalTakeEntityToTargetInventory()
override bool LocalTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
References TakeEntityToTargetInventoryImpl().
LocalTakeToDst()
override bool LocalTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline private
References TakeToDstImpl().
Referenced by DropNonUsableMaterialsServer().
LockDoor()
proto native void LockDoor (int index, bool force = false) private
Locks the door if not already locked, resets the door health. 'force = true' will close the door if open.
Referenced by OnAction().
Man()
void Man () inline private
References SetFlags().
MarkCrewMemberDead()
void MarkCrewMemberDead (int crewMemberIndex) inline private
MarkCrewMemberUnconscious()
void MarkCrewMemberUnconscious (int crewMemberIndex) inline private
NeedInventoryJunctureFromServer()
bool NeedInventoryJunctureFromServer (notnull EntityAI item, EntityAI currParent, EntityAI newParent) inline private
Referenced by PredictiveDropEntity(), PredictiveForceSwapEntities(), PredictiveMoveItemFromHandsToInventory(), PredictiveSwapEntities(), PredictiveTakeEntityAsAttachment(), PredictiveTakeEntityAsAttachmentEx(), PredictiveTakeEntityToCargo(), PredictiveTakeEntityToHands(), PredictiveTakeEntityToInventory(), PredictiveTakeEntityToTargetAttachment(), PredictiveTakeEntityToTargetAttachmentEx(), PredictiveTakeEntityToTargetCargo(), PredictiveTakeEntityToTargetCargoEx(), PredictiveTakeEntityToTargetInventory(), and PredictiveTakeToDst().
OnAction()
override bool OnAction (int action_id, Man player, ParamsReadContext ctx) inline private
References CloseDoor(), GetGame(), GetNearestDoorBySoundPos(), LockDoor(), OpenDoor(), OutputDoorLog(), PlayDoorSound(), and UnlockDoor().
OnDoorCloseFinish()
void OnDoorCloseFinish (DoorFinishParams params) inline private
Event for when the door finishes closing.
OnDoorCloseStart()
void OnDoorCloseStart (DoorStartParams params) inline private
Event for when the door starts closing.
OnDoorLocked()
void OnDoorLocked (DoorLockParams params) inline private
Event for when the door is locked.
OnDoorOpenAjarFinish()
void OnDoorOpenAjarFinish (DoorFinishParams params) inline private
Event for when the door finishes opening ajarred (usually after unlock)
OnDoorOpenAjarStart()
void OnDoorOpenAjarStart (DoorStartParams params) inline private
Event for when the door starts opening ajarred (usually after unlock)
OnDoorOpenFinish()
void OnDoorOpenFinish (DoorFinishParams params) inline private
Event for when the door finishes opening.
OnDoorOpenStart()
void OnDoorOpenStart (DoorStartParams params) inline private
Event for when the door starts opening.
OnDoorUnlocked()
void OnDoorUnlocked (DoorLockParams params) inline private
Event for when the door is unlocked.
OnGameplayDataHandlerSync()
void OnGameplayDataHandlerSync () private
OnItemInHandsChanged()
void OnItemInHandsChanged () inline private
OnRightClick()
void OnRightClick () inline private
OnUseFromInventory()
event bool OnUseFromInventory (Man owner) inline private
OpenDoor()
proto native void OpenDoor (int index) private
Attempts to open the door.
Referenced by OnAction().
OutputDoorLog()
proto native void OutputDoorLog () private
Requires special build as logging is disabled even on internal builds due to memory usage. Used for checking of possible causes of navmesh desync.
Referenced by OnAction().
PhysicalPredictiveDropItem()
bool PhysicalPredictiveDropItem (EntityAI entity, bool heavy_item_only = true) private
PlayDoorSound()
proto native void PlayDoorSound (int index) private
Plays the appropriate sound at the door, based on animation phase and state.
Referenced by OnAction().
PlayImpactSound()
void PlayImpactSound (float weight, float velocity, int surfaceHash) inline private
References SoundObjectBuilder::AddEnvSoundVariables(), SoundObjectBuilder::AddVariable(), SoundObjectBuilder::BuildSoundObject(), GetPosition, SoundLookupTable::GetSoundBuilder(), PlaySound(), and SoundObject().
PlaySound()
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob) inline private
References GetGame(), GetPosition, CGame::GetSoundScene(), and AbstractWave::SetPosition().
PlaySoundByAnimEvent()
void PlaySoundByAnimEvent (EAnimSoundEventID id) inline private
References SoundObjectBuilder::BuildSoundObject(), PlaySound(), and SoundObject().
PredictiveDropEntity()
override bool PredictiveDropEntity (notnull EntityAI item) inline private
References ScriptInputUserData::CanStoreInputUserData(), DropEntityImpl(), JunctureDropEntity(), NeedInventoryJunctureFromServer(), and Print().
PredictiveForceSwapEntities()
bool PredictiveForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline private
References ScriptInputUserData::CanStoreInputUserData(), ForceSwapEntitiesImpl(), NeedInventoryJunctureFromServer(), and Print().
PredictiveMoveItemFromHandsToInventory()
void PredictiveMoveItemFromHandsToInventory () inline private
returns item to previous location, if available
References ScriptInputUserData::CanStoreInputUserData(), GetDebugName(), HumanInventory::GetEntityInHands(), GetHumanInventory(), LogManager::IsSyncLogEnable(), NeedInventoryJunctureFromServer(), Print(), syncDebugPrint(), HumanInventory::TakeEntityToInventory(), TakeToDst(), and UpdateInventoryMenu().
PredictiveSwapEntities()
bool PredictiveSwapEntities (notnull EntityAI item1, notnull EntityAI item2) inline private
References ScriptInputUserData::CanStoreInputUserData(), NeedInventoryJunctureFromServer(), Print(), and SwapEntitiesImpl().
Referenced by PredictiveTakeOrSwapAttachment(), HandsPreview::Select(), and AttachmentCategoriesRow::Select().
PredictiveTakeEntityAsAttachment()
override bool PredictiveTakeEntityAsAttachment (notnull EntityAI item) inline private
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityAsAttachment(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityAsAttachmentImpl().
Referenced by PredictiveTakeOrSwapAttachment().
PredictiveTakeEntityAsAttachmentEx()
override bool PredictiveTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline private
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityAsAttachmentEx(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityAsAttachmentExImpl().
PredictiveTakeEntityToCargo()
override bool PredictiveTakeEntityToCargo (notnull EntityAI item) inline private
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityToCargo(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToCargoImpl().
PredictiveTakeEntityToHands()
void PredictiveTakeEntityToHands (EntityAI item) inline private
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityToHands(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToHandsImpl().
Referenced by OnExecute(), and ActionDetachPowerSourceFromPanel::Process().
PredictiveTakeEntityToInventory()
override bool PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline private
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityToInventory(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToInventoryImpl().
PredictiveTakeEntityToTargetAttachment()
override bool PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline private
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityToTargetAttachment(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToTargetAttachmentImpl().
PredictiveTakeEntityToTargetAttachmentEx()
override bool PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline private
References ScriptInputUserData::CanStoreInputUserData(), GetDebugName(), JunctureTakeEntityToTargetAttachmentEx(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToTargetAttachmentExImpl().
Referenced by ActionAttachOnSelection::OnExecuteServer().
PredictiveTakeEntityToTargetCargo()
override bool PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline private
References ScriptInputUserData::CanStoreInputUserData(), GetDebugName(), JunctureTakeEntityToTargetCargo(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToTargetCargoImpl().
PredictiveTakeEntityToTargetCargoEx()
override bool PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline private
References ScriptInputUserData::CanStoreInputUserData(), GetDebugName(), JunctureTakeEntityToTargetCargoEx(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToTargetCargoExImpl().
PredictiveTakeEntityToTargetInventory()
override bool PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeEntityToTargetInventory(), NeedInventoryJunctureFromServer(), Print(), and TakeEntityToTargetInventoryImpl().
PredictiveTakeOrSwapAttachment()
bool PredictiveTakeOrSwapAttachment (notnull EntityAI item) inline private
References PredictiveSwapEntities(), and PredictiveTakeEntityAsAttachment().
PredictiveTakeToDst()
override bool PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline private
References ScriptInputUserData::CanStoreInputUserData(), JunctureTakeToDst(), NeedInventoryJunctureFromServer(), Print(), and TakeToDstImpl().
Referenced by ManBase::PredictiveTakeToDst().
ProcessImpactSound()
float ProcessImpactSound (IEntity other, Contact extra, float weight, out int surfaceHash) inline private
ProcessImpactSoundEx()
float ProcessImpactSoundEx (IEntity other, Contact extra, float weight, out int surfaceHash, out int liquidType) inline private
References GetGame(), CGame::GetTickTime(), string::Hash(), vector::Length(), and Contact::RelativeVelocityBefore.
RemoveAction()
void RemoveAction (typename actionName) inline private
References GetGame(), ActionBase::GetInputType(), GetPlayer(), and m_InputActionMap.
ReplaceItemElsewhereWithNewInHandsImpl()
protected bool ReplaceItemElsewhereWithNewInHandsImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline private
!hand replace -> hand
References ReplaceItemWithNewLambdaBase::DumpToString(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::ReplaceItemElsewhereWithNewInHands(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by LocalReplaceItemElsewhereWithNewInHands(), and ServerReplaceItemElsewhereWithNewInHands().
ReplaceItemInHandsWithNewElsewhereImpl()
protected bool ReplaceItemInHandsWithNewElsewhereImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline private
hand replace2
References ReplaceItemWithNewLambdaBase::DumpToString(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::ReplaceItemInHandsWithNewElsewhere(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by LocalReplaceItemInHandsWithNewElsewhere(), and ServerReplaceItemInHandsWithNewElsewhere().
ReplaceItemInHandsWithNewImpl()
protected bool ReplaceItemInHandsWithNewImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline private
hand replace
References ReplaceItemWithNewLambdaBase::DumpToString(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::ReplaceItemInHandsWithNew(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by LocalReplaceItemInHandsWithNew(), and ServerReplaceItemInHandsWithNew().
ReplaceItemWithNewImpl()
protected bool ReplaceItemWithNewImpl (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda) inline private
!hand -> !hand replace
References ReplaceItemWithNewLambdaBase::DumpToString(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::ReplaceItemWithNew(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by LocalReplaceItemWithNew(), and ServerReplaceItemWithNew().
ServerDropEntity()
override bool ServerDropEntity (notnull EntityAI item) inline private
References DropEntityImpl().
Referenced by UnlockServer().
ServerForceSwapEntities()
bool ServerForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline private
References ForceSwapEntitiesImpl().
ServerReplaceItemElsewhereWithNewInHands()
bool ServerReplaceItemElsewhereWithNewInHands (ReplaceItemWithNewLambdaBase lambda) inline private
References ReplaceItemElsewhereWithNewInHandsImpl().
ServerReplaceItemInHandsWithNew()
bool ServerReplaceItemInHandsWithNew (ReplaceItemWithNewLambdaBase lambda) inline private
References ReplaceItemInHandsWithNewImpl().
ServerReplaceItemInHandsWithNewElsewhere()
bool ServerReplaceItemInHandsWithNewElsewhere (ReplaceItemWithNewLambdaBase lambda) inline private
References ReplaceItemInHandsWithNewElsewhereImpl().
ServerReplaceItemWithNew()
bool ServerReplaceItemWithNew (ReplaceItemWithNewLambdaBase lambda) inline private
References ReplaceItemWithNewImpl().
ServerSwapEntities()
bool ServerSwapEntities (notnull EntityAI item1, notnull EntityAI item2) inline private
References SwapEntitiesImpl().
ServerTakeEntityAsAttachment()
override bool ServerTakeEntityAsAttachment (notnull EntityAI item) inline private
References TakeEntityAsAttachmentImpl().
ServerTakeEntityAsAttachmentEx()
override bool ServerTakeEntityAsAttachmentEx (notnull EntityAI item, int slot) inline private
References TakeEntityAsAttachmentExImpl().
ServerTakeEntityToCargo()
override bool ServerTakeEntityToCargo (notnull EntityAI item) inline private
References TakeEntityToCargoImpl().
ServerTakeEntityToHands()
void ServerTakeEntityToHands (EntityAI item) inline private
References TakeEntityToHandsImpl().
ServerTakeEntityToInventory()
override bool ServerTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline private
References TakeEntityToInventoryImpl().
ServerTakeEntityToTargetAttachment()
override bool ServerTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline private
References TakeEntityToTargetAttachmentImpl().
ServerTakeEntityToTargetAttachmentEx()
override bool ServerTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline private
References TakeEntityToTargetAttachmentExImpl().
ServerTakeEntityToTargetCargo()
override bool ServerTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline private
References TakeEntityToTargetCargoImpl().
ServerTakeEntityToTargetCargoEx()
override bool ServerTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline private
References TakeEntityToTargetCargoExImpl().
ServerTakeToDst()
override bool ServerTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline private
References TakeToDstImpl().
Referenced by DropNonUsableMaterialsServer(), and ActionUnpackGift::OnFinishProgressServer().
SetActions()
void SetActions () inline private
References AddAction().
SetEngineZoneReceivedHit()
void SetEngineZoneReceivedHit (bool pState) inline private
SetFaceMaterial()
proto native void SetFaceMaterial (string material_name) private
Material that is used on the Man's face and hands.
SetFaceTexture()
proto native void SetFaceTexture (string texture_name) private
Texture that is used on the Man's face and hands.
SetInventorySoftLock()
void SetInventorySoftLock (bool status) private
SetMasterAttenuation()
proto native void SetMasterAttenuation (string masterAttenuation) private
SetProcessUIWarning()
void SetProcessUIWarning (bool state) private
SetSpeechRestricted()
proto native void SetSpeechRestricted (bool state) private
Set speech restriction.
ShowZonesHealth()
override bool ShowZonesHealth () inline private
Referenced by ActionTargetsCursor::GetItemDesc().
StatGet()
proto native float StatGet (string name) private
Gets counter value of the specified stat type.
Parameters
[in] name The name of the stat type.
StatGetAsTime()
proto void StatGetAsTime (string name, out string value) private
Gets counter value as formatted time string of the specified stat type.
Parameters
[in] name The name of the stat type.
[out] value A formatted string containing stat value.
StatGetCounter()
proto void StatGetCounter (string name, out string value) private
Gets counter value as string of the specified stat type.
Parameters
[in] name The name of the stat type.
[out] value A formatted string containing stat value.
StatInvokeUpdate()
proto native void StatInvokeUpdate () private
Invokes read stats from server to client.
Note
Call this on client when you need update stats.
StatRegister()
proto native bool StatRegister (string name) private
Stats Registers new stat type for this player.
Parameters
[in] name The name of the stat type.
StatSyncToClient()
proto native void StatSyncToClient () private
Invokes save stats from server to client.
Note
Call this on server when you need update stats.
StatUpdate()
proto native void StatUpdate (string name, float value) private
Updates stat counter with given value.
Parameters
[in] name The name of the stat type.
[in] value The specified value.
StatUpdateByGivenPos()
proto native void StatUpdateByGivenPos (string name, vector pos) private
Updates stat counter by given position.
Parameters
[in] name The name of the stat type.
[in] pos The specified position.
StatUpdateByPosition()
proto native void StatUpdateByPosition (string name) private
Updates stat counter by player's actual position.
Use this to measure player's travelling distance.
Parameters
[in] name The name of the stat type.
StatUpdateByTime()
proto native void StatUpdateByTime (string name) private
Updates stat counter by time.
Use this to measure play time.
Parameters
[in] name The name of the stat type.
StopDeathDarkeningEffect()
void StopDeathDarkeningEffect () private
SwapEntitiesImpl()
protected bool SwapEntitiesImpl (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2) inline private
References GameInventory::CanSwapEntitiesEx(), Error(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), HumanInventory::SwapEntities(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureSwapEntities(), LocalSwapEntities(), PredictiveSwapEntities(), and ServerSwapEntities().
SwitchOn()
proto native void SwitchOn (bool onOff) private
Some inventoryItem devices can be switched on/off (radios, transmitters)
Referenced by ActionTurnOnSpotlight::OnExecuteServer(), and ActionTurnOnWhileOnGround::OnExecuteServer().
Synchronize()
proto native void Synchronize () private
Synchronizes car's state in case the simulation is not running.
TakeEntityAsAttachmentExImpl()
protected bool TakeEntityAsAttachmentExImpl (InventoryMode mode, notnull EntityAI item, int slot) inline private
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), HumanInventory::TakeEntityAsAttachmentEx(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityAsAttachmentEx(), LocalTakeEntityAsAttachmentEx(), PredictiveTakeEntityAsAttachmentEx(), and ServerTakeEntityAsAttachmentEx().
TakeEntityAsAttachmentImpl()
protected bool TakeEntityAsAttachmentImpl (InventoryMode mode, notnull EntityAI item) inline private
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), GameInventory::TakeEntityAsAttachment(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityAsAttachment(), LocalTakeEntityAsAttachment(), PredictiveTakeEntityAsAttachment(), and ServerTakeEntityAsAttachment().
TakeEntityToCargoImpl()
protected bool TakeEntityToCargoImpl (InventoryMode mode, notnull EntityAI item) inline private
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), GameInventory::TakeEntityToCargo(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToCargo(), LocalTakeEntityToCargo(), PredictiveTakeEntityToCargo(), and ServerTakeEntityToCargo().
TakeEntityToHandsImpl()
void TakeEntityToHandsImpl (InventoryMode mode, EntityAI item) inline private
References GetDebugName(), HumanInventory::GetEntityInHands(), GetGame(), GetHumanInventory(), LogManager::IsSyncLogEnable(), InventoryLocation::SetHands(), syncDebugPrint(), HumanInventory::TakeToDst(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToHands(), LocalTakeEntityToHands(), PerformSwap(), PredictiveTakeEntityToHands(), and ServerTakeEntityToHands().
TakeEntityToInventoryImpl()
protected bool TakeEntityToInventoryImpl (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item) inline private
References GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), HumanInventory::TakeEntityToInventory(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToInventory(), LocalTakeEntityToInventory(), PredictiveTakeEntityToInventory(), and ServerTakeEntityToInventory().
TakeEntityToTargetAttachmentExImpl()
protected bool TakeEntityToTargetAttachmentExImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item, int slot) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToTargetAttachmentEx(), LocalTakeEntityToTargetAttachmentEx(), PredictiveTakeEntityToTargetAttachmentEx(), ServerTakeEntityToTargetAttachmentEx(), and TakeEntityToTargetAttachmentImpl().
TakeEntityToTargetAttachmentImpl()
protected bool TakeEntityToTargetAttachmentImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item) inline private
References InventoryLocation::GetSlot(), and TakeEntityToTargetAttachmentExImpl().
Referenced by JunctureTakeEntityToTargetAttachment(), LocalTakeEntityToTargetAttachment(), PredictiveTakeEntityToTargetAttachment(), and ServerTakeEntityToTargetAttachment().
TakeEntityToTargetCargoExImpl()
protected bool TakeEntityToTargetCargoExImpl (InventoryMode mode, notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToTargetCargoEx(), LocalTakeEntityToTargetCargoEx(), PredictiveTakeEntityToTargetCargoEx(), and ServerTakeEntityToTargetCargoEx().
TakeEntityToTargetCargoImpl()
protected bool TakeEntityToTargetCargoImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToTargetCargo(), LocalTakeEntityToTargetCargo(), PredictiveTakeEntityToTargetCargo(), and ServerTakeEntityToTargetCargo().
TakeEntityToTargetInventoryImpl()
protected bool TakeEntityToTargetInventoryImpl (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
References GetDebugName(), LogManager::IsSyncLogEnable(), syncDebugPrint(), and UpdateInventoryMenu().
Referenced by JunctureTakeEntityToTargetInventory(), LocalTakeEntityToTargetInventory(), and PredictiveTakeEntityToTargetInventory().
TakeToDstImpl()
protected bool TakeToDstImpl (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst) inline private
References InventoryLocation::DumpToStringNullSafe(), GetDebugName(), GetHumanInventory(), LogManager::IsSyncLogEnable(), syncDebugPrint(), HumanInventory::TakeToDst(), and UpdateInventoryMenu().
Referenced by JunctureTakeToDst(), LocalTakeToDst(), PredictiveTakeToDst(), and ServerTakeToDst().
ThrowPhysically()
proto native void ThrowPhysically (DayZPlayer player, vector force, bool collideWithCharacters = true) private
Transport()
void Transport () inline private
TurnOffTransmitter()
void TurnOffTransmitter () inline private
TurnOnTransmitter()
void TurnOnTransmitter () inline private
UnlockDoor()
proto native void UnlockDoor (int index) private
Unlocks the door if locked.
Referenced by OnAction().
UpdateInventoryMenu()
void UpdateInventoryMenu () private
Referenced by DropEntityImpl(), ForceSwapEntitiesImpl(), LocalDestroyEntityInHands(), PredictiveMoveItemFromHandsToInventory(), ReplaceItemElsewhereWithNewInHandsImpl(), ReplaceItemInHandsWithNewElsewhereImpl(), ReplaceItemInHandsWithNewImpl(), ReplaceItemWithNewImpl(), SwapEntitiesImpl(), TakeEntityAsAttachmentExImpl(), TakeEntityAsAttachmentImpl(), TakeEntityToCargoImpl(), TakeEntityToHandsImpl(), TakeEntityToInventoryImpl(), TakeEntityToTargetAttachmentExImpl(), TakeEntityToTargetCargoExImpl(), TakeEntityToTargetCargoImpl(), TakeEntityToTargetInventoryImpl(), and TakeToDstImpl().
Field Documentation
m_ActionsInitialize
bool m_ActionsInitialize private
m_AdvComTypeActionsMap
ref map<typename, ref TInputActionMap> m_AdvComTypeActionsMap = new map<typename, ref TInputActionMap> static private
m_ContinuousActions
ref TIntArray m_ContinuousActions private
m_DeadCrewMemberIndices
protected ref set<int> m_DeadCrewMemberIndices private
m_EngineZoneReceivedHit
protected bool m_EngineZoneReceivedHit private
m_fuelPos
protected vector m_fuelPos private
m_InputActionMap
TInputActionMap m_InputActionMap private
m_InteractActions
ref TIntArray m_InteractActions private
m_IsMeleeWeapon
private bool m_IsMeleeWeapon = false private
m_OnItemAddedToHands
protected ref ScriptInvoker m_OnItemAddedToHands private
Referenced by GetOnItemAddedToHands().
m_OnItemRemovedFromHands
protected ref ScriptInvoker m_OnItemRemovedFromHands private
Referenced by GetOnItemRemovedFromHands().
m_SingleUseActions
ref TIntArray m_SingleUseActions private
m_SoundContactTickTime
private float m_SoundContactTickTime private
m_SoundImpactTable
private SoundLookupTable m_SoundImpactTable private
m_UnconsciousCrewMemberIndices
protected ref set<int> m_UnconsciousCrewMemberIndices private
SOUND_CONTACT_SKIP
private const float SOUND_CONTACT_SKIP = 0.33 static private
The documentation for this class was generated from the following files:
P:/scripts/3_Game/Entities/Building.c
P:/scripts/3_Game/Entities/InventoryItem.c
P:/scripts/3_Game/Entities/Man.c
P:/scripts/3_Game/Vehicles/Transport.c
P:/scripts/4_World/Entities/AdvancedCommunication/AdvancedCommunication.c