DayZ Scripts: ActionBuildPart Class Reference
ActionBuildPart Class Reference
Private Member Functions
void ActionBuildPart ()
override void CreateConditionComponents ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeUsedLeaning ()
override bool CanBeUsedInFreelook ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override string GetSoundCategory (ActionData action_data)
override ActionData CreateActionData ()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
protected void SetBuildingAnimation (ItemBase item)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override string GetAdminLogMessage (ActionData action_data)
Constructor & Destructor Documentation
ActionBuildPart()
void ActionBuildPart () inline private
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, ActionBase::m_FullBody, ActionBase::m_SpecialtyWeight, ActionBase::m_StanceMask, and ActionBase::m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References GetGame(), and ActionBase::m_VariantID.
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
References CollisionCheckData(), Construction(), GetGame(), and string::Insert().
CanBeUsedInFreelook()
override bool CanBeUsedInFreelook () inline private
CanBeUsedLeaning()
override bool CanBeUsedLeaning () inline private
CreateActionData()
override ActionData CreateActionData () inline private
CreateConditionComponents()
override void CreateConditionComponents () inline private
References ActionBase::m_ConditionItem, and ActionBase::m_ConditionTarget.
GetAdminLogMessage()
override string GetAdminLogMessage (ActionData action_data) inline private
GetSoundCategory()
override string GetSoundCategory (ActionData action_data) inline private
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
References BuildPartActionReciveData::m_PartType.
OnActionInfoUpdate()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
References ConstructionActionData::GetBuildPartAtIndex(), ConstructionPart::GetName(), ActionBase::m_Text, and ActionBase::m_VariantID.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References AT_BUILD_PART, UADamageApplied::BUILD, CollisionCheckData(), Construction(), and string::Insert().
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
References BuildPartActionReciveData::m_PartType, and Serializer::Read().
SetBuildingAnimation()
protected void SetBuildingAnimation (ItemBase item) inline private
References AnimatedActionBase::m_CommandUID.
Referenced by SetupAction().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
References ConstructionActionData::GetBuildPartAtIndex(), GetGame(), ConstructionPart::GetPartName(), ActionBase::m_VariantID, and SetBuildingAnimation().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
References Serializer::Write().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionBuildPart.c