DayZ Scripts: Hive Class Reference
Hive Class Reference
Private Member Functions
private void Hive ()
private void ~Hive ()
proto native void InitOnline (string ceSetup, string host="")
proto native void InitOffline ()
proto native void InitSandbox ()
proto native bool IsIdleMode ()
proto native void SetShardID (string shard)
proto native void SetEnviroment (string env)
proto native void CharacterSave (Man player)
proto native void CharacterKill (Man player)
proto native void CharacterExit (Man player)
proto native void CallUpdater (string content)
proto native bool CharacterIsLoginPositionChanged (Man player)
Only valid during login.
Constructor & Destructor Documentation
Hive()
private void Hive () inline private
~Hive()
private void ~Hive () inline private
Member Function Documentation
CallUpdater()
proto native void CallUpdater (string content) private
CharacterExit()
proto native void CharacterExit (Man player) private
Referenced by MissionBase::PlayerDisconnected().
CharacterIsLoginPositionChanged()
proto native bool CharacterIsLoginPositionChanged (Man player) private
Only valid during login.
Referenced by ManBase::OnStoreLoad().
CharacterKill()
proto native void CharacterKill (Man player) private
Referenced by ManBase::EEKilled().
CharacterSave()
proto native void CharacterSave (Man player) private
Referenced by ManBase::Save().
InitOffline()
proto native void InitOffline () private
InitOnline()
proto native void InitOnline (string ceSetup, string host = "") private
InitSandbox()
proto native void InitSandbox () private
IsIdleMode()
proto native bool IsIdleMode () private
SetEnviroment()
proto native void SetEnviroment (string env) private
SetShardID()
proto native void SetShardID (string shard) private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Hive/Hive.c