DayZ Scripts: ZombieMaleBase Class Reference
ZombieMaleBase Class Reference
Base class for eatch Infected type.
Private Member Functions
override bool IsZombieMilitary ()
override bool IsZombieMilitary ()
override bool IsZombieMilitary ()
override bool IsZombieMilitary ()
override bool ResistContaminatedEffect ()
override bool ResistContaminatedEffect ()
override bool IsZombieMilitary ()
override void EEInit ()
void ~ZmbM_Mummy ()
override void OnDamageDestroyed (int oldLevel)
void ChangeVisual ()
override bool ResistContaminatedEffect ()
Private Attributes
protected ZombieMummyLight m_EyeLight
Detailed Description
Base class for eatch Infected type.
Constructor & Destructor Documentation
~ZmbM_Mummy()
void ~ZmbM_Mummy () inline private
References m_EyeLight.
Member Function Documentation
ChangeVisual()
void ChangeVisual () inline private
EEInit()
override void EEInit () inline private
References IsDamageDestroyed(), and m_EyeLight.
IsZombieMilitary() [1/5]
override bool IsZombieMilitary () inline private
IsZombieMilitary() [2/5]
override bool IsZombieMilitary () inline private
IsZombieMilitary() [3/5]
override bool IsZombieMilitary () inline private
IsZombieMilitary() [4/5]
override bool IsZombieMilitary () inline private
IsZombieMilitary() [5/5]
override bool IsZombieMilitary () inline private
OnDamageDestroyed()
override void OnDamageDestroyed (int oldLevel) inline private
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and m_EyeLight.
ResistContaminatedEffect() [1/3]
override bool ResistContaminatedEffect () inline private
ResistContaminatedEffect() [2/3]
override bool ResistContaminatedEffect () inline private
ResistContaminatedEffect() [3/3]
override bool ResistContaminatedEffect () inline private
Field Documentation
m_EyeLight
protected ZombieMummyLight m_EyeLight private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Creatures/Infected/ZombieMaleBase.c