DayZ Scripts: BiosUserManager Class Reference
BiosUserManager Class Reference
Private Member Functions
proto native BiosUser GetTitleInitiator ()
Gets the initiatior of the title.
proto native EBiosError GetUserList (array< ref BiosUser > user_list)
Gets the currently present list of users.
proto native EBiosError LogOnUserAsync (BiosUser user)
Display a system dependant ui for log-on.
proto native EBiosError PickUserAsync ()
Display a system dependant account picket.
proto native EBiosError ParseJoinAsync (string join_data)
Parse the join data from from command line parameters.
proto native EBiosError ParsePartyAsync (string party_data)
Parse the party data from from command line parameters.
proto native void SelectUser (BiosUser user)
Informs the engine about the current selected user.
proto native BiosUser GetSelectedUser ()
Returns the currently selected user.
proto native EBiosError GetUserDatabaseIdAsync ()
Call async function to get database ID.
void SelectUserEx (BiosUser user)
void OnUserDatabaseId (string dbID, EBiosError error)
Callback function.
void OnUserLoggedOn (EBiosError error)
Callback function.
void OnUserPicked (BiosUser user, EBiosError error)
Callback function.
void OnLoggedOn (BiosUser user)
Callback function.
void OnLoggedOff (BiosUser user)
Callback function.
void OnSignedIn (BiosUser user)
Callback function.
void OnSignedOut (BiosUser user)
Callback function.
void OnJoin (EBiosJoinType type, BiosUser joiner, string handle, string joinee, EBiosError error)
Callback function.
void OnPartyHost (BiosUser host, array< string > invitee_list, EBiosError error)
Callback function.
void OnGameNameChanged (BiosUser user)
Callback function.
BiosUser GetUser (string user_id)
Detailed Description
Definition at line 16 of file BiosUserManager.c.
Member Function Documentation
GetSelectedUser()
proto native BiosUser GetSelectedUser () private
Returns the currently selected user.
Returns
BiosUser the selected user. May be NULL.
Referenced by CreateTitleScreen(), OnlineServices::GetClientServices(), DayZIntroScene::GetSelectedUserName(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::IsLocalPlayer(), UIScriptedMenu::IsLocalPlayer(), OnGameNameChanged(), OnLoggedOn(), OnSignedOut(), UIScriptedMenu::Refresh(), SelectGamepad(), SelectUser(), SelectUserEx(), Managed::SetupPlayerName(), and DayZIntroSceneXbox::UpdateSelectedUserName().
GetTitleInitiator()
proto native BiosUser GetTitleInitiator () private
Gets the initiatior of the title.
Returns
BiosUser the initiator. May be NULL.
Referenced by ConnectLaunch(), and MissionLaunch().
GetUser()
BiosUser GetUser (string user_id) inline private
Definition at line 295 of file BiosUserManager.c.
References GetUserList().
GetUserDatabaseIdAsync()
proto native EBiosError GetUserDatabaseIdAsync () private
Call async function to get database ID.
Returns
EBiosError indicating if the async operation is pending. If active user is not set, then return NOT_FOUND
Referenced by OnLoginTimeEvent(), and SelectGamepad().
GetUserList()
proto native EBiosError GetUserList (array< ref BiosUser > user_list) private
Gets the currently present list of users.
Fills in the array. Expected errors: BAD_PARAMETER - user_list is NULL,
Returns
EBiosError indicating if the operation is done.
Referenced by OnlineServices::GetClientServices(), and GetUser().
LogOnUserAsync()
proto native EBiosError LogOnUserAsync (BiosUser user) private
Display a system dependant ui for log-on.
Referenced by OnPartyHost(), and SelectUser().
OnGameNameChanged()
void OnGameNameChanged (BiosUser user) inline private
Callback function.
Called when display info of a signed in user changed.
Parameters
user the user affected by the change.
Definition at line 280 of file BiosUserManager.c.
References g_Game, GetGame(), UIManager::GetMenu(), BiosUser::GetName(), GetSelectedUser(), CGame::GetUIManager(), and UIScriptedMenu::Refresh().
Referenced by OnUserPicked().
OnJoin()
void OnJoin (EBiosJoinType type, BiosUser joiner, string handle, string joinee, EBiosError error) inline private
Callback function.
Called when a join is parsed or when a runtime join is accepted from the system UI.
Parameters
type the type of join. Undefined on error.
joiner the user that is joining. NULL on error.
handle join handle for a session. Empty on error.
joinee uid of the user that is being joined. Empty on error.
error indicating if parsing failed. OK if not a result of ParseJoinAsync.
Definition at line 200 of file BiosUserManager.c.
References UIManager::CloseMenu(), DISCONNECT_SESSION_FLAGS_JOIN, OnlineServices::ErrorCaught(), g_Game, GetGame(), CGame::GetInput(), GetInput(), OnlineServices::GetSession(), CGame::GetUIManager(), Input::IdentifyGamepad(), MENU_TITLE_SCREEN, SelectUserEx(), OnlineServices::SetBiosUser(), and OnlineServices::SetSessionHandle().
OnLoggedOff()
void OnLoggedOff (BiosUser user) inline private
Callback function.
Definition at line 158 of file BiosUserManager.c.
References OnSignedOut().
OnLoggedOn()
void OnLoggedOn (BiosUser user) inline private
Callback function.
Definition at line 151 of file BiosUserManager.c.
References g_Game, GetGame(), GetInput(), and GetSelectedUser().
OnPartyHost()
void OnPartyHost (BiosUser host, array< string > invitee_list, EBiosError error) inline private
Callback function.
Called when a party is parsed or when a party is hosted from the system UI.
Parameters
host the user that is hosting the party. NULL on error.
invitee_list list of party members.
error indicating if parsing failed. OK if not a result of ParsePartyAsync.
Definition at line 239 of file BiosUserManager.c.
References UIManager::CloseMenu(), UIManager::EnterScriptedMenu(), g_Game, GetGame(), GetID(), CGame::GetUIManager(), BiosUser::IsOnline(), LogOnUserAsync(), MENU_MAIN, MENU_TITLE_SCREEN, SelectUserEx(), and OnlineServices::SetPendingInviteList().
OnSignedIn()
void OnSignedIn (BiosUser user) inline private
Callback function.
Called when a new user signed in
Parameters
user the user that signed in. Cannot be NULL.
Definition at line 169 of file BiosUserManager.c.
OnSignedOut()
void OnSignedOut (BiosUser user) inline private
Callback function.
Called when a new user signed out
Parameters
user the user that signed out. Cannot be NULL.
Definition at line 180 of file BiosUserManager.c.
References DISCONNECT_SESSION_FLAGS_FORCE, g_Game, GetGame(), CGame::GetInput(), GetSelectedUser(), Input::ResetActiveGamepad(), and SelectUserEx().
Referenced by OnLoggedOff().
OnUserDatabaseId()
void OnUserDatabaseId (string dbID, EBiosError error) inline private
Callback function.
Parameters
dbID user database ID. If something went wrong, then it is empty string.
error indicating correct state.
Definition at line 107 of file BiosUserManager.c.
References OnlineServices::ErrorCaught(), and g_Game.
OnUserLoggedOn()
void OnUserLoggedOn (EBiosError error) inline private
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 119 of file BiosUserManager.c.
References DISCONNECT_SESSION_FLAGS_FORCE, OnlineServices::ErrorCaught(), g_Game, GetGame(), CGame::GetInput(), and Input::ResetActiveGamepad().
OnUserPicked()
void OnUserPicked (BiosUser user, EBiosError error) inline private
Callback function.
Parameters
user picked user. NULL on fail.
error error indicating success or fail of the async operation.
Definition at line 133 of file BiosUserManager.c.
References OnlineServices::ErrorCaught(), g_Game, GetGame(), CGame::GetInput(), GetInput(), CGame::GetMission(), OnGameNameChanged(), Mission::Reset(), Input::ResetActiveGamepad(), and SelectUserEx().
ParseJoinAsync()
proto native EBiosError ParseJoinAsync (string join_data) private
Parse the join data from from command line parameters.
The async result is returned in the OnJoin callback. The OnJoin callback is called also during runtime when a join is accepted. Expected errors: BAD_PARAMETER - join_data could not be parsed,
Parameters
join_data the startup join data from command line parameters.
Returns
EBiosError indicating if the async operation is pending.
Referenced by JoinLaunch().
ParsePartyAsync()
proto native EBiosError ParsePartyAsync (string party_data) private
Parse the party data from from command line parameters.
The async result is returned in the OnPartyHost callback. The OnPartyHost callback is called also during runtime when a player hosts a game for the party. Expected errors: BAD_PARAMETER - join_data could not be parsed,
Parameters
party_data the startup party data from command line parameters.
Returns
EBiosError indicating if the async operation is pending.
Referenced by PartyLaunch().
PickUserAsync()
proto native EBiosError PickUserAsync () private
Display a system dependant account picket.
Xbox: The async result is returned in the OnUserPicked callback.
Returns
EBiosError indicating if the async operation is pending.
Referenced by SelectUser().
SelectUser()
proto native void SelectUser (BiosUser user) private
Informs the engine about the current selected user.
Must be called to ensure proper authentication etc.
Parameters
user the user to select.
Referenced by SelectUserEx().
SelectUserEx()
void SelectUserEx (BiosUser user) inline private
Definition at line 90 of file BiosUserManager.c.
References DISCONNECT_SESSION_FLAGS_FORCE, g_Game, GetSelectedUser(), and SelectUser().
Referenced by UIScriptedMenu::ChangeAccount(), ConnectLaunch(), DisconnectSessionEx(), MissionLaunch(), OnJoin(), OnPartyHost(), OnSignedOut(), OnUserPicked(), and SelectUser().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Services/BiosUserManager.c