DayZ Scripts: VolcanicTrigger Class Reference
VolcanicTrigger Class Reference
Volcanic area trigger.
Private Member Functions
override void EEInit ()
override void EEDelete (EntityAI parent)
override void OnEnterServerEvent (TriggerInsider insider)
override void OnLeaveServerEvent (TriggerInsider insider)
override void OnEnterClientEvent (TriggerInsider insider)
override void OnLeaveClientEvent (TriggerInsider insider)
protected void SpawnVaporEffect ()
Static Private Member Functions
static void ApplyEffects (PlayerBase player)
Private Attributes
protected ParticleSource m_VaporParticle
Static Private Attributes
static VolcanicTrigger m_SourceDamageInstance
static const float HEAT_DAMAGE_MULTIPLIER = 5
static const float HEAT_DAMAGE_TICK_TIME = 2
Detailed Description
Volcanic area trigger.
Member Function Documentation
ApplyEffects()
static void ApplyEffects (PlayerBase player) inline static private
References HEAT_DAMAGE_MULTIPLIER, and m_SourceDamageInstance.
Referenced by ManBase::OnUpdateEffectAreaServer().
EEDelete()
override void EEDelete (EntityAI parent) inline private
References m_VaporParticle, and Particle::Stop().
EEInit()
override void EEInit () inline private
References EEInit(), GetGame(), m_SourceDamageInstance, and SpawnVaporEffect().
Referenced by EEInit().
OnEnterClientEvent()
override void OnEnterClientEvent (TriggerInsider insider) inline private
References TriggerInsider::GetObject().
OnEnterServerEvent()
override void OnEnterServerEvent (TriggerInsider insider) inline private
References TriggerInsider::GetObject().
OnLeaveClientEvent()
override void OnLeaveClientEvent (TriggerInsider insider) inline private
References TriggerInsider::GetObject().
OnLeaveServerEvent()
override void OnLeaveServerEvent (TriggerInsider insider) inline private
References TriggerInsider::GetObject().
SpawnVaporEffect()
protected void SpawnVaporEffect () inline private
References GetGame(), GetPosition, ParticleSource::IncrementParticleParam(), m_VaporParticle, ParticleManager(), Math::RandomIntInclusive(), CGame::SurfaceY(), and ParticleList::VOLCANO.
Referenced by EEInit().
Field Documentation
HEAT_DAMAGE_MULTIPLIER
const float HEAT_DAMAGE_MULTIPLIER = 5 static private
Referenced by ApplyEffects().
HEAT_DAMAGE_TICK_TIME
const float HEAT_DAMAGE_TICK_TIME = 2 static private
Referenced by ManBase::OnUpdateEffectAreaServer().
m_SourceDamageInstance
VolcanicTrigger m_SourceDamageInstance static private
Referenced by ApplyEffects(), and EEInit().
m_VaporParticle
protected ParticleSource m_VaporParticle private
Referenced by EEDelete(), and SpawnVaporEffect().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ScriptedEntities/Triggers/VolcanicTrigger.c