DayZ Scripts: BloodRegenMdfr Class Reference
BloodRegenMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnActivate (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
float GetRegenModifierWater (float water)
float GetRegenModifierEnergy (float energy)
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
GetRegenModifierEnergy()
float GetRegenModifierEnergy (float energy) inline private
References PlayerConstants::BLOOD_REGEN_MODIFIER_ENERGY_HIGH, PlayerConstants::BLOOD_REGEN_MODIFIER_ENERGY_LOW, PlayerConstants::BLOOD_REGEN_MODIFIER_ENERGY_MID, and m_Player.
Referenced by OnTick().
GetRegenModifierWater()
float GetRegenModifierWater (float water) inline private
References PlayerConstants::BLOOD_REGEN_MODIFIER_WATER_HIGH, PlayerConstants::BLOOD_REGEN_MODIFIER_WATER_LOW, PlayerConstants::BLOOD_REGEN_MODIFIER_WATER_MID, and m_Player.
Referenced by OnTick().
Init()
override void Init () inline private
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void OnActivate (PlayerBase player) inline private
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
References PlayerConstants::BLOOD_REGEN_RATE_PER_SEC, GetRegenModifierEnergy(), and GetRegenModifierWater().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/BloodRegen.c