DayZ Scripts: ProjectileStoppedInfo Class Reference
ProjectileStoppedInfo Class Reference
Private Member Functions
proto native Object GetSource ()
proto native vector GetPos ()
proto native vector GetInVelocity ()
proto native string GetAmmoType ()
proto native float GetProjectileDamage ()
Member Function Documentation
GetAmmoType()
proto native string GetAmmoType () private
Referenced by CGame::OnProjectileStopped(), and Ammunition_Base::SetFromProjectile().
GetInVelocity()
proto native vector GetInVelocity () private
GetPos()
proto native vector GetPos () private
Referenced by CGame::OnProjectileStopped().
GetProjectileDamage()
proto native float GetProjectileDamage () private
Referenced by Ammunition_Base::SetFromProjectile().
GetSource()
proto native Object GetSource () private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/DayZGame.c