DayZ Scripts: UniversalTemperatureSourceLambdaFireplace Class Reference
UniversalTemperatureSourceLambdaFireplace Class Reference
Private Member Functions
void UniversalTemperatureSourceLambdaFireplace ()
void SetSmallFireplaceTemperatureMax (int value)
void SetNormalFireplaceTemperatureMax (int value)
void SetFuelCount (int value)
void SetCurrentTemperature (float temperature)
override void Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues)
Private Attributes
int m_FuelCount
int m_SmallFireplaceTemperatureMax
int m_NormalFireplaceTemperatureMax
float m_Temperature
Detailed Description
Definition at line 1 of file UniversalTemperatureSourceLambdaFireplace.c.
Constructor & Destructor Documentation
UniversalTemperatureSourceLambdaFireplace()
void UniversalTemperatureSourceLambdaFireplace () inline private
Definition at line 8 of file UniversalTemperatureSourceLambdaFireplace.c.
References m_FuelCount, m_NormalFireplaceTemperatureMax, m_SmallFireplaceTemperatureMax, and m_Temperature.
Member Function Documentation
Execute()
override void Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues) inline private
set temperature to the item stat
Definition at line 46 of file UniversalTemperatureSourceLambdaFireplace.c.
References UniversalTemperatureSourceLambdaBase::DryItemsInVicinity(), UniversalTemperatureSourceSettings::m_AffectStat, UniversalTemperatureSourceSettings::m_Parent, and m_Temperature.
SetCurrentTemperature()
void SetCurrentTemperature (float temperature) inline private
Definition at line 31 of file UniversalTemperatureSourceLambdaFireplace.c.
References Math::Clamp(), m_FuelCount, m_NormalFireplaceTemperatureMax, m_SmallFireplaceTemperatureMax, and m_Temperature.
Referenced by AddWetnessToFireplace(), Cooling(), and Heating().
SetFuelCount()
void SetFuelCount (int value) inline private
Definition at line 26 of file UniversalTemperatureSourceLambdaFireplace.c.
References m_FuelCount.
Referenced by AddWetnessToFireplace(), Cooling(), and Heating().
SetNormalFireplaceTemperatureMax()
void SetNormalFireplaceTemperatureMax (int value) inline private
Definition at line 21 of file UniversalTemperatureSourceLambdaFireplace.c.
References m_NormalFireplaceTemperatureMax.
Referenced by EEInit().
SetSmallFireplaceTemperatureMax()
void SetSmallFireplaceTemperatureMax (int value) inline private
Definition at line 16 of file UniversalTemperatureSourceLambdaFireplace.c.
References m_SmallFireplaceTemperatureMax.
Referenced by EEInit().
Field Documentation
m_FuelCount
int m_FuelCount private
Definition at line 3 of file UniversalTemperatureSourceLambdaFireplace.c.
Referenced by SetCurrentTemperature(), SetFuelCount(), and UniversalTemperatureSourceLambdaFireplace().
m_NormalFireplaceTemperatureMax
int m_NormalFireplaceTemperatureMax private
Definition at line 5 of file UniversalTemperatureSourceLambdaFireplace.c.
Referenced by SetCurrentTemperature(), SetNormalFireplaceTemperatureMax(), and UniversalTemperatureSourceLambdaFireplace().
m_SmallFireplaceTemperatureMax
int m_SmallFireplaceTemperatureMax private
Definition at line 4 of file UniversalTemperatureSourceLambdaFireplace.c.
Referenced by SetCurrentTemperature(), SetSmallFireplaceTemperatureMax(), and UniversalTemperatureSourceLambdaFireplace().
m_Temperature
float m_Temperature private
Definition at line 6 of file UniversalTemperatureSourceLambdaFireplace.c.
Referenced by Execute(), SetCurrentTemperature(), and UniversalTemperatureSourceLambdaFireplace().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/UniversalTemperatureSource/UniversalTemperatureSourceLambdaFireplace.c