DayZ Scripts: ActionEmptyMagazine Class Reference
ActionEmptyMagazine Class Reference
Private Member Functions
void ActionEmptyMagazine ()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override bool HasProneException ()
bool CanEmpty (ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool HasTarget ()
override void OnExecuteServer (ActionData action_data)
Detailed Description
Definition at line 14 of file ActionEmptyMagazine.c.
Constructor & Destructor Documentation
ActionEmptyMagazine()
void ActionEmptyMagazine () inline private
Definition at line 16 of file ActionEmptyMagazine.c.
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 63 of file ActionEmptyMagazine.c.
References CanEmpty().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data) inline private
Definition at line 58 of file ActionEmptyMagazine.c.
References CanEmpty(), and ActionData::m_MainItem.
CanEmpty()
bool CanEmpty (ItemBase item) inline private
Definition at line 52 of file ActionEmptyMagazine.c.
References Class::CastTo().
Referenced by ActionCondition(), and ActionConditionContinue().
CreateActionData()
override ActionData CreateActionData () inline private
Definition at line 35 of file ActionEmptyMagazine.c.
CreateConditionComponents()
override void CreateConditionComponents () inline private
Definition at line 41 of file ActionEmptyMagazine.c.
References m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool HasProneException () inline private
Definition at line 47 of file ActionEmptyMagazine.c.
HasTarget()
override bool HasTarget () inline private
Definition at line 69 of file ActionEmptyMagazine.c.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data) inline private
Definition at line 74 of file ActionEmptyMagazine.c.
References Class::CastTo(), CGame::ConfigGetText(), DayZPlayerUtils(), UAMaxDistances::DEFAULT, vector::DistanceSq(), GetGame(), EmptyMagazineActionData::m_magazinePile, ActionData::m_MainItem, and ActionData::m_Player.
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 24 of file ActionEmptyMagazine.c.
References EmptyMagazineActionData::m_magazinePile.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionEmptyMagazine.c