DayZ Scripts: ScriptInvokerTests Class Reference
ScriptInvokerTests Class Reference
Private Member Functions
void ScriptInvokerTests ()
void ~ScriptInvokerTests ()
TFResult TestFirstUnique ()
TFResult TestSecondUnique ()
TFResult TestInsertRemoveUnique ()
TFResult TestInsertUniqueImmediate ()
TFResult TestClearRunning ()
TFResult TestInvokeRunning ()
TFResult TestInsertRunning ()
void InvokeLog (string s)
void InvokeReset ()
void InvokeClear (string s)
void InvokeInvoke (string s)
void InvokeInsert (string s)
Private Attributes
ref ScriptInvoker m_Invoker
int m_InvokeCount
Constructor & Destructor Documentation
ScriptInvokerTests()
void ScriptInvokerTests () inline private
References AddInitTest(), and m_Invoker.
~ScriptInvokerTests()
void ~ScriptInvokerTests () inline private
Member Function Documentation
InvokeClear()
void InvokeClear (string s) inline private
References ScriptInvoker::Clear(), InvokeLog(), and m_Invoker.
Referenced by TestClearRunning().
InvokeInsert()
void InvokeInsert (string s) inline private
References ScriptInvoker::Insert(), InvokeInsert(), InvokeLog(), and m_Invoker.
Referenced by InvokeInsert(), and TestInsertRunning().
InvokeInvoke()
void InvokeInvoke (string s) inline private
References ScriptInvoker::Invoke(), InvokeLog(), and m_Invoker.
Referenced by TestInvokeRunning().
InvokeLog()
void InvokeLog (string s) inline private
References m_InvokeCount.
Referenced by InvokeClear(), InvokeInsert(), InvokeInvoke(), TestClearRunning(), TestFirstUnique(), TestInsertRemoveUnique(), TestInsertUniqueImmediate(), and TestSecondUnique().
InvokeReset()
void InvokeReset () inline private
References ScriptInvoker::Clear(), m_InvokeCount, and m_Invoker.
Referenced by TestClearRunning(), TestFirstUnique(), TestInsertRemoveUnique(), TestInsertRunning(), TestInsertUniqueImmediate(), TestInvokeRunning(), and TestSecondUnique().
TestClearRunning()
TFResult TestClearRunning () inline private
References Assert(), BTFR(), ScriptInvoker::Insert(), ScriptInvoker::Invoke(), InvokeClear(), InvokeLog(), InvokeReset(), m_InvokeCount, and m_Invoker.
TestFirstUnique()
TFResult TestFirstUnique () inline private
References Assert(), BTFR(), ScriptInvoker::Insert(), ScriptInvoker::Invoke(), InvokeLog(), InvokeReset(), m_InvokeCount, and m_Invoker.
TestInsertRemoveUnique()
TFResult TestInsertRemoveUnique () inline private
References Assert(), BTFR(), ScriptInvoker::Insert(), ScriptInvoker::Invoke(), InvokeLog(), InvokeReset(), m_InvokeCount, m_Invoker, and ScriptInvoker::Remove().
TestInsertRunning()
TFResult TestInsertRunning () inline private
References Assert(), BTFR(), ScriptInvoker::Insert(), ScriptInvoker::Invoke(), InvokeInsert(), InvokeReset(), m_InvokeCount, m_Invoker, and Print().
TestInsertUniqueImmediate()
TFResult TestInsertUniqueImmediate () inline private
References Assert(), BTFR(), ScriptInvoker::Insert(), ScriptInvoker::Invoke(), InvokeLog(), InvokeReset(), m_InvokeCount, and m_Invoker.
TestInvokeRunning()
TFResult TestInvokeRunning () inline private
References BTFR(), ScriptInvoker::Insert(), ScriptInvoker::Invoke(), InvokeInvoke(), InvokeReset(), and m_Invoker.
TestSecondUnique()
TFResult TestSecondUnique () inline private
References Assert(), BTFR(), ScriptInvoker::Insert(), ScriptInvoker::Invoke(), InvokeLog(), InvokeReset(), m_InvokeCount, and m_Invoker.
Field Documentation
m_InvokeCount
int m_InvokeCount private
Referenced by InvokeLog(), InvokeReset(), TestClearRunning(), TestFirstUnique(), TestInsertRemoveUnique(), TestInsertRunning(), TestInsertUniqueImmediate(), and TestSecondUnique().
m_Invoker
ref ScriptInvoker m_Invoker private
Referenced by InvokeClear(), InvokeInsert(), InvokeInvoke(), InvokeReset(), ScriptInvokerTests(), TestClearRunning(), TestFirstUnique(), TestInsertRemoveUnique(), TestInsertRunning(), TestInsertUniqueImmediate(), TestInvokeRunning(), and TestSecondUnique().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/TFTests/ScriptInvokerTests.c