DayZ Scripts: ProgressAsync Class Reference
ProgressAsync Class Reference
Static Private Member Functions
static proto native void SetUserData (Widget inst)
static proto native void SetProgressData (Widget inst)
static proto native void DestroyAllPendingProgresses ()
static proto native void StartProgress ()
Detailed Description
Definition at line 1 of file ProgressAsync.c.
Member Function Documentation
DestroyAllPendingProgresses()
static proto native void DestroyAllPendingProgresses () static private
Referenced by CGame::OnEvent(), and MissionBase::OnMissionStart().
SetProgressData()
static proto native void SetProgressData (Widget inst) static private
Referenced by EndLoading(), Hide(), and LoadingScreen().
SetUserData()
static proto native void SetUserData (Widget inst) static private
Referenced by EndLoading(), Hide(), and LoadingScreen().
StartProgress()
static proto native void StartProgress () static private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/ProgressAsync.c