DayZ Scripts: P:/scripts/5_Mission/GUI/ScriptConsole.c File Reference
ScriptConsole.c File Reference
Data Structures
class UIScriptedMenu
class JsonHintsData
Functions
void OnWidgetScriptInit (Widget w)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
protected bool Tick ()
protected void DisplayHint (string message)
protected void HideHint ()
protected string GetMessage ()
protected void HoverSuccess ()
protected void HoverInterrupt ()
Variables
class ScriptConsole extends UIScriptedMenu HintMessage
protected Widget m_Root
protected float m_HoverTime
protected bool m_HoverSuccessTriggered
protected Widget m_CurrentHoverWidget
protected Widget m_HintWidgetRoot
protected ImageWidget m_HintWidgetBackground
protected RichTextWidget m_HintWidget
protected ref Timer m_Timer
Function Documentation
DisplayHint()
protected void DisplayHint (string message)
References WorkspaceWidget::CreateWidgets(), GetGame(), GetMousePos(), GetScreenSize(), CGame::GetWorkspace(), m_HintWidget, m_HintWidgetBackground, and m_HintWidgetRoot.
Referenced by HoverSuccess().
GetMessage()
protected string GetMessage ()
References HintMessage.
Referenced by HoverSuccess().
HideHint()
protected void HideHint ()
References m_HintWidgetRoot.
Referenced by HoverInterrupt().
HoverInterrupt()
protected void HoverInterrupt ()
References HideHint(), m_CurrentHoverWidget, m_HoverSuccessTriggered, m_HoverTime, and m_Timer.
Referenced by OnMouseLeave(), and Tick().
HoverSuccess()
protected void HoverSuccess ()
References DisplayHint(), GetMessage(), and m_HoverSuccessTriggered.
Referenced by Tick().
OnMouseEnter()
override bool OnMouseEnter (Widget w, int x, int y)
References m_CurrentHoverWidget, and m_Timer.
OnMouseLeave()
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
References HoverInterrupt().
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w)
References m_Root.
Tick()
protected bool Tick ()
References HoverInterrupt(), HoverSuccess(), m_CurrentHoverWidget, m_HoverSuccessTriggered, m_HoverTime, and m_Root.
Variable Documentation
HintMessage
class ScriptConsole extends UIScriptedMenu HintMessage
Referenced by GetMessage().
m_CurrentHoverWidget
protected Widget m_CurrentHoverWidget
Referenced by UIScriptedMenu::GetMessage(), HoverInterrupt(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnMouseEnter(), OnMouseEnter(), Tick(), and UIScriptedMenu::Update().
m_HintWidget
protected RichTextWidget m_HintWidget
Referenced by UIScriptedMenu::DisplayHint(), and DisplayHint().
m_HintWidgetBackground
protected ImageWidget m_HintWidgetBackground
Referenced by UIScriptedMenu::DisplayHint(), and DisplayHint().
m_HintWidgetRoot
protected Widget m_HintWidgetRoot
Referenced by UIScriptedMenu::DisplayHint(), DisplayHint(), UIScriptedMenu::HideHint(), HideHint(), UIScriptedMenu::Update(), and UIScriptedMenu::~ScriptConsole().
m_HoverSuccessTriggered
protected bool m_HoverSuccessTriggered
Referenced by UIScriptedMenu::HoverInterrupt(), HoverInterrupt(), UIScriptedMenu::HoverSuccess(), HoverSuccess(), Tick(), and UIScriptedMenu::Update().
m_HoverTime
protected float m_HoverTime
Referenced by UIScriptedMenu::HoverInterrupt(), HoverInterrupt(), Tick(), and UIScriptedMenu::Update().
m_Root
protected Widget m_Root
m_Timer
protected ref Timer m_Timer