DayZ Scripts: SyncedValueModifier Class Reference
SyncedValueModifier Class Reference
Private Member Functions
void SyncedValueModifier (int id, string name, bool active, bool locked)
string GetName ()
int GetID ()
bool GetLocked ()
bool GetActive ()
Private Attributes
string m_Name
int m_ID
bool m_Locked
bool m_Active
Constructor & Destructor Documentation
SyncedValueModifier()
void SyncedValueModifier (int id, string name, bool active, bool locked) inline private
References m_Active, m_ID, m_Locked, m_Name, and name.
Member Function Documentation
GetActive()
bool GetActive () inline private
References m_Active.
Referenced by SetModifiers().
GetID()
int GetID () inline private
References m_ID.
Referenced by SetModifiers().
GetLocked()
bool GetLocked () inline private
References m_Locked.
Referenced by SetModifiers().
GetName()
string GetName () inline private
References m_Name.
Referenced by SetModifiers().
Field Documentation
m_Active
bool m_Active private
Referenced by GetActive(), and SyncedValueModifier().
m_ID
int m_ID private
Referenced by GetID(), and SyncedValueModifier().
m_Locked
bool m_Locked private
Referenced by GetLocked(), and SyncedValueModifier().
m_Name
string m_Name private
Referenced by GetName(), and SyncedValueModifier().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/Modules/SyncedValue.c