DayZ Scripts: PPEMatClassParameterColor Class Reference
PPEMatClassParameterColor Class Reference
Private Member Functions
override void ModifyResultValues (inout Param result_values)
Member Function Documentation
ModifyResultValues()
override void ModifyResultValues (inout Param result_values) inline private
References Easing::EaseOutSine(), PPEManagerStatic::GetPPEManager(), Math::Lerp(), m_ColorDefaults, Math::Max(), and PPEGlow::PARAM_SATURATION.
Referenced by Update().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/PPEManager/Materials/MatParameters/PPEMatClassParameterColor.c