DayZ Scripts: ActionFishingNewCB Class Reference
ActionFishingNewCB Class Reference
Private Member Functions
override void CreateActionComponent ()
override void InitActionComponent ()
override void EndActionComponent ()
override void OnStateChange (int pOldState, int pCurrentState)
void ToggleFishBiting ()
void DestroySplashEffectSynced ()
Destroys the effecter, but lets the rest of the particle play out.
void HandleFishingResultSuccess ()
void HandleFishingResultFailure ()
Private Attributes
FishingActionData m_ActionDataFishing
ref array< string > m_JunkTypes = {}
Member Function Documentation
CreateActionComponent()
override void CreateActionComponent () inline private
References Class::CastTo(), UAFishingConstants::CYCLE_LENGTH_BASE, EnableStateChangeCallback(), ActionBaseCB::m_ActionData, and m_ActionDataFishing.
DestroySplashEffectSynced()
void DestroySplashEffectSynced () inline private
Destroys the effecter, but lets the rest of the particle play out.
References SEffectManager::DestroyEffecterParticleServer(), GetGame(), and m_ActionDataFishing.
Referenced by EndActionComponent().
EndActionComponent()
override void EndActionComponent () inline private
References DestroySplashEffectSynced(), m_ActionDataFishing, ActionBaseCB::m_Canceled, ActionBaseCB::SetCommand(), UA_CANCEL, and UA_FINISHED.
HandleFishingResultFailure()
void HandleFishingResultFailure () private
Referenced by ActionFishingNew::EvaluateFishingResult().
HandleFishingResultSuccess()
void HandleFishingResultSuccess () private
Referenced by ActionFishingNew::EvaluateFishingResult().
InitActionComponent()
override void InitActionComponent () inline private
References UAFishingConstants::EVENT_ANIMATE_ROD_CLOSE, UAFishingConstants::EVENT_SPLASH_SIGNAL, and RegisterAnimationEvent().
OnStateChange()
override void OnStateChange (int pOldState, int pCurrentState) inline private
References m_ActionDataFishing, STATE_LOOP_IN, and STATE_NONE.
ToggleFishBiting()
void ToggleFishBiting () inline private
References GetState(), ActionBaseCB::SetCommand(), STATE_LOOP_LOOP, and STATE_LOOP_LOOP2.
Referenced by ActionFishingNew::OnSignalEnd(), and ActionFishingNew::OnSignalStart().
Field Documentation
m_ActionDataFishing
FishingActionData m_ActionDataFishing private
Referenced by CreateActionComponent(), DestroySplashEffectSynced(), EndActionComponent(), and OnStateChange().
m_JunkTypes
ref array<string> m_JunkTypes = {} private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionFishingNew.c