DayZ Scripts: JsonFileLoader< Class T > Class Reference
JsonFileLoader< Class T > Class Reference
Static Private Member Functions
static bool LoadFile (string filename, out T data, out string errorMessage)
static bool SaveFile (string filename, T data, out string errorMessage)
static bool LoadData (string string_data, out T data, out string errorMessage)
static bool MakeData (T inputData, out string outputData, out string errorMessage, bool prettyPrint=true)
static void JsonLoadFile (string filename, out T data)
#ifndef DIAG_DEVELOPER
static void JsonSaveFile (string filename, T data)
use JsonFileLoader::SaveFile instead
static void JsonLoadData (string string_data, out T data)
use JsonFileLoader::LoadData instead
static string JsonMakeData (T data)
use JsonFileLoader::MakeData instead
Static Private Attributes
static protected ref JsonSerializer m_Serializer = new JsonSerializer()
Member Function Documentation
JsonLoadData()
static void JsonLoadData (string string_data, out T data) inline static private
use JsonFileLoader::LoadData instead
References ErrorEx.
JsonLoadFile()
static void JsonLoadFile (string filename, out T data) inline static private
#ifndef DIAG_DEVELOPER
DEPRECATED
use JsonFileLoader::LoadFile instead
References CloseFile(), ErrorEx, FGets(), FileExist(), and OpenFile().
JsonMakeData()
static string JsonMakeData (T data) inline static private
use JsonFileLoader::MakeData instead
JsonSaveFile()
static void JsonSaveFile (string filename, T data) inline static private
use JsonFileLoader::SaveFile instead
References CloseFile(), FPrint(), and OpenFile().
LoadData()
static bool LoadData (string string_data, out T data, out string errorMessage) inline static private
LoadFile()
static bool LoadFile (string filename, out T data, out string errorMessage) inline static private
References CloseFile(), FGets(), FileExist(), and OpenFile().
MakeData()
static bool MakeData (T inputData, out string outputData, out string errorMessage, bool prettyPrint = true) inline static private
SaveFile()
static bool SaveFile (string filename, T data, out string errorMessage) inline static private
References CloseFile(), FPrint(), and OpenFile().
Field Documentation
m_Serializer
protected ref JsonSerializer m_Serializer = new JsonSerializer() static private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/JsonFileLoader.c