DayZ Scripts: AgentBase Class Reference
AgentBase Class Reference
Private Member Functions
void AgentBase ()
void Init ()
int GetAgentType ()
float GetDieOffSpeedEx (PlayerBase player)
EStatLevels GetPotencyEx (PlayerBase player)
float GetInvasibilityEx (PlayerBase player)
EStatLevels GetPotency ()
float GetDieOffSpeed ()
float GetAntiboticsResistance ()
float GetAntibioticsResistanceEx (PlayerBase player)
float GetInvasibility ()
bool GrowDuringMedicalDrugsAttack (EMedicalDrugsType drugType, PlayerBase player)
should this agent grow based on invasibility even during usage of specific medical drugs attack
float GetDigestibility ()
float CalculateAutoinfectProbability (float userprob)
bool AutoinfectCheck (float deltaT, PlayerBase player)
bool CanAutoinfectPlayer (PlayerBase player)
float GetTransferabilityIn ()
float GetTransferabilityOut ()
float GetTransferabilityAirOut ()
int GetMaxCount ()
int GetAutoinfectCount ()
string GetName ()
bool GrowDuringAntibioticsAttack (PlayerBase player)
should this agent grow based on invasibility even during antibiotics attack
override void Init ()
override void Init ()
override float GetDieOffSpeedEx (PlayerBase player)
override void Init ()
override void Init ()
override void Init ()
override void Init ()
Private Attributes
float m_Type = 0
float m_Invasibility
float m_TransferabilityIn
float m_TransferabilityOut
float m_Digestibility = 0.1
int m_MaxCount = 1
int m_AutoinfectCount = 1
float m_AutoinfectProbability = CalculateAutoinfectProbability(0)
number of agents injected during the autoinfection
float m_TransferabilityAirOut
float m_AntibioticsResistance = 1
EStatLevels m_Potency = EStatLevels.MEDIUM
float m_DieOffSpeed = 1
Constructor & Destructor Documentation
AgentBase()
void AgentBase () inline private
References Init().
Member Function Documentation
AutoinfectCheck()
bool AutoinfectCheck (float deltaT, PlayerBase player) inline private
References CanAutoinfectPlayer(), m_AutoinfectProbability, and Math::RandomFloat01().
Referenced by PlayerAgentPool::SpawnAgents().
CalculateAutoinfectProbability()
float CalculateAutoinfectProbability (float userprob) inline private
References Math::Pow().
CanAutoinfectPlayer()
bool CanAutoinfectPlayer (PlayerBase player) inline private
Referenced by AutoinfectCheck().
GetAgentType()
int GetAgentType () inline private
References m_Type.
Referenced by PluginBase::ConstructSimpleAgentList(), PlayerAgentPool::GetDebugObject(), PluginBase::RegisterAgent(), and PlayerAgentPool::SpawnAgents().
GetAntibioticsResistanceEx()
float GetAntibioticsResistanceEx (PlayerBase player) inline private
References GetAntiboticsResistance().
GetAntiboticsResistance()
float GetAntiboticsResistance () inline private
References m_AntibioticsResistance.
Referenced by GetAntibioticsResistanceEx().
GetAutoinfectCount()
int GetAutoinfectCount () inline private
References m_AutoinfectCount.
Referenced by PlayerAgentPool::SpawnAgents().
GetDieOffSpeed()
float GetDieOffSpeed () inline private
References m_DieOffSpeed.
Referenced by GetDieOffSpeedEx(), HeavyMetalAgent::GetDieOffSpeedEx(), and InfluenzaAgent::GetDieOffSpeedEx().
GetDieOffSpeedEx() [1/2]
float GetDieOffSpeedEx (PlayerBase player) inline private
References GetDieOffSpeed().
GetDieOffSpeedEx() [2/2]
override float GetDieOffSpeedEx (PlayerBase player) inline private
GetDigestibility()
float GetDigestibility () inline private
References m_Digestibility.
GetInvasibility()
float GetInvasibility () inline private
References m_Invasibility.
Referenced by GetInvasibilityEx().
GetInvasibilityEx()
float GetInvasibilityEx (PlayerBase player) inline private
References GetInvasibility().
GetMaxCount()
int GetMaxCount () inline private
References m_MaxCount.
GetName()
string GetName () inline private
Referenced by PluginBase::ConstructSimpleAgentList(), and PlayerAgentPool::GetDebugObject().
GetPotency()
EStatLevels GetPotency () inline private
References m_Potency.
Referenced by GetPotencyEx().
GetPotencyEx()
EStatLevels GetPotencyEx (PlayerBase player) inline private
References GetPotency().
GetTransferabilityAirOut()
float GetTransferabilityAirOut () inline private
References m_TransferabilityAirOut.
GetTransferabilityIn()
float GetTransferabilityIn () inline private
References m_TransferabilityIn.
GetTransferabilityOut()
float GetTransferabilityOut () inline private
References m_TransferabilityOut.
GrowDuringAntibioticsAttack()
bool GrowDuringAntibioticsAttack (PlayerBase player) inline private
should this agent grow based on invasibility even during antibiotics attack
DEPRECATED
GrowDuringMedicalDrugsAttack()
bool GrowDuringMedicalDrugsAttack (EMedicalDrugsType drugType, PlayerBase player) inline private
should this agent grow based on invasibility even during usage of specific medical drugs attack
Referenced by PluginBase::GrowDuringMedicalDrugsAttack().
Init() [1/7]
void Init () private
Referenced by AgentBase().
Init() [2/7]
override void Init () inline private
References m_Type.
Init() [3/7]
override void Init () inline private
References m_Type.
Init() [4/7]
override void Init () inline private
References m_Type.
Init() [5/7]
override void Init () inline private
References m_Type.
Init() [6/7]
override void Init () inline private
References m_Type.
Init() [7/7]
override void Init () inline private
References m_Type.
Field Documentation
m_AntibioticsResistance
float m_AntibioticsResistance = 1 private
Referenced by GetAntiboticsResistance(), HeavyMetalAgent::Init(), InfluenzaAgent::Init(), and WoundAgent::Init().
m_AutoinfectCount
int m_AutoinfectCount = 1 private
Referenced by GetAutoinfectCount(), and InfluenzaAgent::Init().
m_AutoinfectProbability
float m_AutoinfectProbability = CalculateAutoinfectProbability(0) private
number of agents injected during the autoinfection
Referenced by AutoinfectCheck().
m_DieOffSpeed
float m_DieOffSpeed = 1 private
Referenced by GetDieOffSpeed(), InfluenzaAgent::Init(), and WoundAgent::Init().
m_Digestibility
float m_Digestibility = 0.1 private
Referenced by GetDigestibility(), and InfluenzaAgent::Init().
m_Invasibility
float m_Invasibility private
Referenced by GetInvasibility(), InfluenzaAgent::Init(), and WoundAgent::Init().
m_MaxCount
int m_MaxCount = 1 private
Referenced by GetMaxCount(), HeavyMetalAgent::Init(), InfluenzaAgent::Init(), and WoundAgent::Init().
m_Potency
EStatLevels m_Potency = EStatLevels.MEDIUM private
Referenced by GetPotency(), HeavyMetalAgent::GetPotencyEx(), HeavyMetalAgent::Init(), InfluenzaAgent::Init(), and WoundAgent::Init().
m_TransferabilityAirOut
float m_TransferabilityAirOut private
Referenced by GetTransferabilityAirOut(), and InfluenzaAgent::Init().
m_TransferabilityIn
float m_TransferabilityIn private
Referenced by GetTransferabilityIn(), HeavyMetalAgent::Init(), InfluenzaAgent::Init(), and WoundAgent::Init().
m_TransferabilityOut
float m_TransferabilityOut private
Referenced by GetTransferabilityOut(), HeavyMetalAgent::Init(), InfluenzaAgent::Init(), and WoundAgent::Init().
m_Type
float m_Type = 0 private
Referenced by GetAgentType(), HeavyMetalAgent::Init(), InfluenzaAgent::Init(), and WoundAgent::Init().
The documentation for this class was generated from the following files:
P:/scripts/4_World/Classes/TransmissionAgents/Agents/AgentBase.c
P:/scripts/4_World/Classes/TransmissionAgents/Agents/BrainAgent.c
P:/scripts/4_World/Classes/TransmissionAgents/Agents/ChemicalAgent.c
P:/scripts/4_World/Classes/TransmissionAgents/Agents/CholeraAgent.c
P:/scripts/4_World/Classes/TransmissionAgents/Agents/FoodPoisonAgent.c
P:/scripts/4_World/Classes/TransmissionAgents/Agents/NerveAgent.c
P:/scripts/4_World/Classes/TransmissionAgents/Agents/SalmonellaAgent.c