DayZ Scripts: DynamicArea_Flare Class Reference
DynamicArea_Flare Class Reference
Private Member Functions
void DynamicArea_Flare ()
override void EOnFrame (IEntity other, float timeSlice)
override void EEDelete (EntityAI parent)
Private Attributes
const float FALL_SPEED = 0.5
const float LIFETIME = 40000
private Particle m_Particle
Detailed Description
Definition at line 2 of file DynamicArea_Flare.c.
Constructor & Destructor Documentation
DynamicArea_Flare()
void DynamicArea_Flare () inline private
Definition at line 7 of file DynamicArea_Flare.c.
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), ParticleList::FLAREPROJ_ACTIVATE_RED, CGame::GetCallQueue(), GetGame(), LIFETIME, m_Particle, ParticleManager(), and SetFlags().
Member Function Documentation
EEDelete()
override void EEDelete (EntityAI parent) inline private
Definition at line 28 of file DynamicArea_Flare.c.
References m_Particle, and Particle::Stop().
EOnFrame()
override void EOnFrame (IEntity other, float timeSlice) inline private
Definition at line 20 of file DynamicArea_Flare.c.
References FALL_SPEED, GetPosition, and SetPosition().
Field Documentation
FALL_SPEED
const float FALL_SPEED = 0.5 private
Definition at line 4 of file DynamicArea_Flare.c.
Referenced by EOnFrame().
LIFETIME
const float LIFETIME = 40000 private
Definition at line 5 of file DynamicArea_Flare.c.
Referenced by DynamicArea_Flare().
m_Particle
private Particle m_Particle private
Definition at line 6 of file DynamicArea_Flare.c.
Referenced by DynamicArea_Flare(), and EEDelete().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/ContaminatedArea/DynamicArea_Flare.c