DayZ Scripts: AbstractWave Class Reference
AbstractWave Class Reference
Private Member Functions
private void InitEvents ()
void AbstractWave ()
proto void SetUserData (Managed inst)
proto Managed GetUserData ()
proto void Play ()
void PlayWithOffset (float offset)
proto void Stop ()
proto void Restart ()
proto void SetStartOffset (float offset)
proto float GetLength ()
WARNING: Blocking! Waits for header to load.
proto float GetCurrPosition ()
Current position in percentage of total length.
proto void Loop (bool setLoop)
proto float GetVolume ()
proto void SetVolume (float value)
proto void SetVolumeRelative (float value)
proto void SetFrequency (float value)
proto float GetFrequency ()
proto void SetPosition (vector position)
proto void SetFadeInFactor (float volume)
proto void SetFadeOutFactor (float volume)
proto void Skip (float timeSec)
proto bool IsHeaderLoaded ()
AbstractWaveEvents GetEvents ()
void OnPlay ()
void OnStop ()
void OnLoad ()
void OnHeaderLoad ()
void OnEnd ()
Detailed Description
Definition at line 90 of file Sound.c.
Constructor & Destructor Documentation
AbstractWave()
void AbstractWave () inline private
Definition at line 102 of file Sound.c.
References InitEvents().
Member Function Documentation
GetCurrPosition()
proto float GetCurrPosition () private
Current position in percentage of total length.
GetEvents()
AbstractWaveEvents GetEvents () inline private
Definition at line 135 of file Sound.c.
References GetUserData().
Referenced by OnEnd(), OnHeaderLoad(), OnLoad(), OnPlay(), OnStop(), EffectSound::SoundPlayEx(), and EffectSound::ValidateSoundWave().
GetFrequency()
proto float GetFrequency () private
GetLength()
proto float GetLength () private
WARNING: Blocking! Waits for header to load.
Referenced by OnTick(), ManBase::OnVoiceEventPlayback(), and EffectSound::ValidateSoundWave().
GetUserData()
proto Managed GetUserData () private
Referenced by GetEvents(), and Play().
GetVolume()
proto float GetVolume () private
InitEvents()
private void InitEvents () inline private
Definition at line 92 of file Sound.c.
References SetUserData().
Referenced by AbstractWave().
IsHeaderLoaded()
proto bool IsHeaderLoaded () private
Referenced by EffectSound::SoundPlayEx().
Loop()
proto void Loop (bool setLoop) private
Referenced by MissionBase::PlayMusic(), EffectSound::SetSoundLoop(), and SoftStop().
OnEnd()
void OnEnd () inline private
Definition at line 160 of file Sound.c.
References GetEvents().
OnHeaderLoad()
void OnHeaderLoad () inline private
Definition at line 155 of file Sound.c.
References GetEvents().
OnLoad()
void OnLoad () inline private
Definition at line 150 of file Sound.c.
References GetEvents().
OnPlay()
void OnPlay () inline private
Definition at line 140 of file Sound.c.
References GetEvents().
OnStop()
void OnStop () inline private
Definition at line 145 of file Sound.c.
References GetEvents().
Play()
proto void Play () private
Referenced by MissionBase::PlayMusic(), and PlayWithOffset().
PlayWithOffset()
void PlayWithOffset (float offset) inline private
Definition at line 110 of file Sound.c.
References Play(), and SetStartOffset().
Restart()
proto void Restart () private
SetFadeInFactor()
proto void SetFadeInFactor (float volume) private
SetFadeOutFactor()
proto void SetFadeOutFactor (float volume) private
SetFrequency()
proto void SetFrequency (float value) private
SetPosition()
proto void SetPosition (vector position) private
Referenced by OnTick(), DayZCreature::PlaySound(), EntityAI::PlaySound(), DayZPlayer::PlaySound(), and PosUpdate().
SetStartOffset()
proto void SetStartOffset (float offset) private
Referenced by DayZPlayer::HandleView(), and PlayWithOffset().
SetUserData()
proto void SetUserData (Managed inst) private
Referenced by InitEvents().
SetVolume()
proto void SetVolume (float value) private
SetVolumeRelative()
proto void SetVolumeRelative (float value) private
Referenced by DayZPlayer::HandleView(), PlayerSoundEventBase::OnPlay(), EffectSound::SetSoundMaxVolume(), EffectSound::SetSoundVolume(), EffectSound::SoundReset(), and EffectSound::ValidateSoundWave().
Skip()
proto void Skip (float timeSec) private
Stop()
proto void Stop () private
Referenced by EffectSound::Event_OnFrameUpdate(), DayZInfected::OnSoundVoiceEvent(), EffectSound::SoundReset(), EffectSound::SoundStop(), Stop(), SoundEventBase::Stop(), MissionBase::StopMusic(), EffectSound::ValidateSoundWave(), ~InfectedSoundEventBase(), and SoundEventBase::~SoundEventBase().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Sound.c