DayZ Scripts: ActionCreateGreenhouseGardenPlot Class Reference
ActionCreateGreenhouseGardenPlot Class Reference
Private Member Functions
void ActionCreateGreenhouseGardenPlot ()
override void CreateConditionComponents ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
Private Attributes
GardenPlot m_GardenPlot
private const float CAMERA_PITCH_THRESHOLD = -30
Constructor & Destructor Documentation
ActionCreateGreenhouseGardenPlot()
void ActionCreateGreenhouseGardenPlot () inline private
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
References GetGame(), CGame::GetObjectsAtPosition3D(), Land_Misc_Greenhouse(), and Land_Misc_Polytunnel().
CreateConditionComponents()
override void CreateConditionComponents () inline private
References m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data) inline private
References ECE_KEEPHEIGHT, GetGame(), Land_Misc_Greenhouse(), Land_Misc_Polytunnel(), m_GardenPlot, ActionData::m_MainItem, and ActionData::m_Target.
Field Documentation
CAMERA_PITCH_THRESHOLD
private const float CAMERA_PITCH_THRESHOLD = -30 private
m_GardenPlot
GardenPlot m_GardenPlot private
Referenced by OnFinishProgressServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionCreateGreenhouseGardenPlot.c