DayZ Scripts: CharcoalMdfr Class Reference
CharcoalMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override void OnReconnect (PlayerBase player)
override string GetDebugTextSimple ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
float m_Killrate
const int CHARCOAL_LIFETIME = 300
const int CHARCOAL_EFFECT_TIME = 100
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
References CHARCOAL_LIFETIME, and GetAttachedTime().
GetDebugTextSimple()
override string GetDebugTextSimple () inline private
References CHARCOAL_EFFECT_TIME, CHARCOAL_LIFETIME, GetAttachedTime(), ToString(), and string::ToString().
Init()
override void Init () inline private
References DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), m_AnalyticsStatsEnabled, m_ID, m_IsPersistent, m_Killrate, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void OnActivate (PlayerBase player) inline private
OnDeactivate()
override void OnDeactivate (PlayerBase player) inline private
OnReconnect()
override void OnReconnect (PlayerBase player) inline private
References OnActivate().
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
References CHARCOAL_EFFECT_TIME, CHARCOAL_LIFETIME, GetAttachedTime(), and m_Killrate.
Field Documentation
CHARCOAL_EFFECT_TIME
const int CHARCOAL_EFFECT_TIME = 100 private
Referenced by GetDebugTextSimple(), and OnTick().
CHARCOAL_LIFETIME
const int CHARCOAL_LIFETIME = 300 private
Referenced by DeactivateCondition(), GetDebugTextSimple(), and OnTick().
m_Killrate
float m_Killrate private
Referenced by Init(), and OnTick().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/CharcoalMdfr.c