DayZ Scripts: HumanCommandUnconscious Class Reference
HumanCommandUnconscious Class Reference
Private Member Functions
private void HumanCommandUnconscious ()
private void ~HumanCommandUnconscious ()
proto native void WakeUp (int targetStance=-1)
proto native bool IsWakingUp ()
proto native bool IsOnLand ()
proto native bool IsInWater ()
Constructor & Destructor Documentation
HumanCommandUnconscious()
private void HumanCommandUnconscious () inline private
~HumanCommandUnconscious()
private void ~HumanCommandUnconscious () inline private
Member Function Documentation
IsInWater()
proto native bool IsInWater () private
Referenced by ManBase::CommandHandler(), and DayZPlayer::GetTypeOfDeath().
IsOnLand()
proto native bool IsOnLand () private
Referenced by DayZPlayer::GetTypeOfDeath().
IsWakingUp()
proto native bool IsWakingUp () private
Referenced by DayZPlayer::HeadingModel().
WakeUp()
proto native void WakeUp (int targetStance = -1) private
Referenced by ManBase::CommandHandler(), and PluginDayzPlayerDebug_OtherCmds::Uncon_End().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/human.c