DayZ Scripts: P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/diseases/WoundInfection.c File Reference
WoundInfection.c File Reference
Data Structures
class WoundInfectionMdfr
Functions
override void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
override string GetDebugText ()
override protected bool ActivateCondition (PlayerBase player)
override protected void OnActivate (PlayerBase player)
is called when an inactive modifier gets activated during gameplay, is NOT called on activation upon player server connection(see OnReconnect)
override protected void OnDeactivate (PlayerBase player)
override protected bool DeactivateCondition (PlayerBase player)
override protected void OnTick (PlayerBase player, float deltaT)
Variables
WoundInfectionMdfr AGENT_THRESHOLD_ACTIVATE = 1
static const int AGENT_THRESHOLD_DEACTIVATE = 250
static const int AGENT_THRESHOLD_FEVER = 250
static const int PAIN_EVENT_INTERVAL_MIN = 18
static const int PAIN_EVENT_INTERVAL_MAX = 26
protected float m_NextEvent
protected float m_Time
Function Documentation
ActivateCondition()
override protected bool ActivateCondition (PlayerBase player)
References AGENT_THRESHOLD_ACTIVATE.
DeactivateCondition()
override protected bool DeactivateCondition (PlayerBase player)
References ModifierBase::ActivateCondition().
GetDebugText()
override string GetDebugText ()
References AGENT_THRESHOLD_ACTIVATE, and AGENT_THRESHOLD_DEACTIVATE.
Init()
override void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, m_AnalyticsStatsEnabled, m_ID, m_SyncID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override protected void OnActivate (PlayerBase player)
is called when an inactive modifier gets activated during gameplay, is NOT called on activation upon player server connection(see OnReconnect)
References m_NextEvent, PAIN_EVENT_INTERVAL_MAX, PAIN_EVENT_INTERVAL_MIN, and Math::RandomFloatInclusive().
OnDeactivate()
override protected void OnDeactivate (PlayerBase player)
Referenced by Deactivate().
OnTick()
override protected void OnTick (PlayerBase player, float deltaT)
References m_NextEvent, m_Time, Math::Max(), PAIN_EVENT_INTERVAL_MAX, PAIN_EVENT_INTERVAL_MIN, CachedObjectsParams::PARAM1_FLOAT, Math::RandomFloatInclusive(), SymptomBase::SetParam(), VOMIT_EVENT_INTERVAL_MAX, and VOMIT_EVENT_INTERVAL_MIN.
Variable Documentation
AGENT_THRESHOLD_ACTIVATE
WoundInfectionMdfr AGENT_THRESHOLD_ACTIVATE = 1
AGENT_THRESHOLD_DEACTIVATE
const int AGENT_THRESHOLD_DEACTIVATE = 250 static
AGENT_THRESHOLD_FEVER
const int AGENT_THRESHOLD_FEVER = 250 static
m_NextEvent
protected float m_NextEvent
Referenced by OnActivate(), and OnTick().
m_Time
protected float m_Time
Referenced by CarScript(), EOnPostSimulate(), OnTick(), SymptomBase::OnUpdateClient(), UIScriptedMenu::Play(), and UIScriptedMenu::Update().
PAIN_EVENT_INTERVAL_MAX
const int PAIN_EVENT_INTERVAL_MAX = 26 static
Referenced by OnActivate(), and OnTick().
PAIN_EVENT_INTERVAL_MIN
const int PAIN_EVENT_INTERVAL_MIN = 18 static
Referenced by OnActivate(), and OnTick().