DayZ Scripts: StomachItem Class Reference
StomachItem Class Reference
Private Member Functions
void StomachItem (string class_name, float amount, NutritionalProfile profile, int foodstage, int agents)
string GetClassName ()
int GetFoodStage ()
void SetFoodStage (int food_stage)
float GetAmount ()
void AddAmount (float amount)
void AddAgents (int agents)
bool ProcessDigestion (float digestion_points, out float water, out float energy, out float toxicity, out float volume, out int agents, out float consumed_amount)
float GetNutritions (float digestion_points, NutritionalProfile profile, out float water, out float energy, out float toxicity)
Private Attributes
ref NutritionalProfile m_Profile
float m_Amount
int m_FoodStage
string m_ClassName
int m_Agents
Constructor & Destructor Documentation
StomachItem()
void StomachItem (string class_name, float amount, NutritionalProfile profile, int foodstage, int agents) inline private
References class_name, m_Agents, m_Amount, m_ClassName, m_FoodStage, and m_Profile.
Member Function Documentation
AddAgents()
void AddAgents (int agents) inline private
References m_Agents.
Referenced by AddToStomach().
AddAmount()
void AddAmount (float amount) inline private
References m_Amount.
Referenced by AddToStomach().
GetAmount()
float GetAmount () inline private
References m_Amount.
GetClassName()
string GetClassName () inline private
References m_ClassName.
Referenced by AddToStomach().
GetFoodStage()
int GetFoodStage () inline private
References m_FoodStage.
Referenced by AddToStomach().
GetNutritions()
float GetNutritions (float digestion_points, NutritionalProfile profile, out float water, out float energy, out float toxicity) inline private
References NutritionalProfile::GetDigestibility(), NutritionalProfile::GetEnergy(), NutritionalProfile::GetToxicity(), NutritionalProfile::GetWaterContent(), and m_Amount.
Referenced by ProcessDigestion().
ProcessDigestion()
bool ProcessDigestion (float digestion_points, out float water, out float energy, out float toxicity, out float volume, out int agents, out float consumed_amount) inline private
References NutritionalProfile::GetFullnessIndex(), GetNutritions(), m_Agents, m_Amount, and m_Profile.
Referenced by ProcessNutrients().
SetFoodStage()
void SetFoodStage (int food_stage) inline private
References m_FoodStage.
Field Documentation
m_Agents
int m_Agents private
Referenced by AddAgents(), OnStoreSave(), ProcessDigestion(), and StomachItem().
m_Amount
float m_Amount private
Referenced by AddAmount(), GetAmount(), GetNutritions(), OnStoreSave(), ProcessDigestion(), and StomachItem().
m_ClassName
string m_ClassName private
Referenced by GetClassName(), OnStoreSave(), and StomachItem().
m_FoodStage
int m_FoodStage private
Referenced by GetFoodStage(), OnStoreSave(), SetFoodStage(), and StomachItem().
m_Profile
ref NutritionalProfile m_Profile private
Referenced by ProcessDigestion(), and StomachItem().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerStomach.c