DayZ Scripts: P:/scripts/4_World/Classes/UserActionsComponent/Actions/Continuous/ActionBuildStoneCircle.c File Reference
ActionBuildStoneCircle.c File Reference
Data Structures
class ActionBuildStoneCircleCB
Functions
ActionBuildStoneCircleCB ActionContinuousBaseCB ActionBuildStoneCircle ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
Function Documentation
ActionBuildStoneCircle()
ActionBuildStoneCircleCB ActionContinuousBaseCB ActionBuildStoneCircle ()
Definition at line 1 of file ActionBuildStoneCircle.c.
Referenced by ActionConstructor::RegisterActions(), and FireplaceBase::SetActions().
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 39 of file ActionBuildStoneCircle.c.
References FireplaceBase::IsBaseFireplace().
CreateActionComponent()
override void CreateActionComponent ()
Definition at line 12 of file ActionBuildStoneCircle.c.
References m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 22 of file ActionBuildStoneCircle.c.
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType ()
Definition at line 29 of file ActionBuildStoneCircle.c.
HasProgress()
override bool HasProgress ()
Definition at line 34 of file ActionBuildStoneCircle.c.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 56 of file ActionBuildStoneCircle.c.
References ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.