DayZ Scripts: MainMenuButtonEffect Class Reference
MainMenuButtonEffect Class Reference
Private Member Functions
void MainMenuButtonEffect ()
void ~MainMenuButtonEffect ()
void OnWidgetScriptInit (ButtonWidget w)
protected void Update (float tDelta)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
Private Attributes
reference float speed
reference float amount
protected float m_textProportion
protected float m_textProportion2
protected ButtonWidget m_root
protected ref AnimatorTimer m_anim
Constructor & Destructor Documentation
MainMenuButtonEffect()
void MainMenuButtonEffect () inline private
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), and ScriptedWidgetEventHandler::Update().
~MainMenuButtonEffect()
void ~MainMenuButtonEffect () inline private
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Remove(), and ScriptedWidgetEventHandler::Update().
Member Function Documentation
OnFocus()
override bool OnFocus (Widget w, int x, int y) inline private
References AnimatorTimer::Animate(), AnimatorTimer::IsRunning(), m_anim, m_root, m_textProportion, m_textProportion2, and speed.
OnFocusLost()
override bool OnFocusLost (Widget w, int x, int y) inline private
References AnimatorTimer::Animate(), m_anim, and speed.
OnWidgetScriptInit()
void OnWidgetScriptInit (ButtonWidget w) inline private
References m_root.
Update()
protected void Update (float tDelta) inline private
References amount, ARGBF(), AnimatorTimer::GetValue(), m_anim, m_root, and AnimatorTimer::Tick().
Field Documentation
amount
reference float amount private
Referenced by Update().
m_anim
protected ref AnimatorTimer m_anim private
Referenced by OnFocus(), OnFocusLost(), and Update().
m_root
protected ButtonWidget m_root private
Referenced by OnFocus(), OnWidgetScriptInit(), and Update().
m_textProportion
protected float m_textProportion private
Referenced by OnFocus().
m_textProportion2
protected float m_textProportion2 private
Referenced by OnFocus().
speed
reference float speed private
Referenced by OnFocus(), and OnFocusLost().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/GUI/Effects/MainMenuButtonEffect.c