DayZ Scripts: AutoHeightSpacer Class Reference
AutoHeightSpacer Class Reference
Private Member Functions
void Update ()
void OnWidgetScriptInit (Widget w)
override bool OnChildRemove (Widget w, Widget child)
Private Attributes
reference bool AlignChilds
reference int MinHeight
reference int MaxHeight
reference int Gap
reference float Top
protected Widget m_root
Member Function Documentation
OnChildRemove()
override bool OnChildRemove (Widget w, Widget child) inline private
References m_root, and Update().
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w) inline private
References m_root, and Update().
Update()
void Update () inline private
References Math::AbsInt(), AlignChilds, Gap, m_root, MaxHeight, MinHeight, Top, x, and y.
Referenced by AddAgent(), AddModifier(), HudDebugWinBase::AddValue(), OnChildRemove(), NoticeSpacer::OnEvent(), OnWidgetScriptInit(), ScriptedWidgetEventHandler::Show(), and HudDebugWinBase::Update().
Field Documentation
AlignChilds
reference bool AlignChilds private
Referenced by Update().
Gap
reference int Gap private
Referenced by Update().
m_root
protected Widget m_root private
Referenced by OnChildRemove(), OnWidgetScriptInit(), and Update().
MaxHeight
reference int MaxHeight private
Referenced by Update().
MinHeight
reference int MinHeight private
Referenced by Update().
Top
reference float Top private
Referenced by Update().
The documentation for this class was generated from the following file:
3_Game/GUI/Spacers/AutoHeightSpacer.c