DayZ Scripts: AreaDamageBase Class Reference
AreaDamageBase Class Reference
Private Member Functions
void AreaDamageBase (EntityAI parent)
void OnEnter (Object object)
events
void OnEnterClient (Object object)
void OnEnterServer (Object object)
void OnLeave (Object object)
void OnLeaveClient (Object object)
void OnLeaveServer (Object object)
protected void EvaluateDamage_Loop (Object object)
protected void EvaluateDamage_Defer (Object object)
protected void EvaluateDamage_DeferLoop (Object object)
protected void EvaluateDamage (Object object)
protected void EvaluateDamage_Common (Object object, string hitzone)
protected string GetRandomHitZone (array< string > hitzones)
protected string GetRaycastedHitZone (Object victim, array< string > raycast_sources_str)
void AreaDamageOneTime (EntityAI parent)
void ~AreaDamageOneTime ()
override void SetHitZones (array< string > hitzones)
override void OnEnterServer (Object object)
void AreaDamageOneTimeDeferred (EntityAI parent)
void ~AreaDamageOneTimeDeferred ()
override void SetDeferDuration (float time)
override void SetHitZones (array< string > hitzones)
override void OnEnterServer (Object object)
void AreaDamageOneTimeRaycasted (EntityAI parent)
void ~AreaDamageOneTimeRaycasted ()
override void SetRaycastSources (array< string > raycast_sources)
override void OnEnterServer (Object object)
void AreaDamageOneTimeRaycastedDeferred (EntityAI parent)
void ~AreaDamageOneTimeRaycastedDeferred ()
override void SetDeferDuration (float time)
override void SetRaycastSources (array< string > raycast_sources)
override void OnEnterServer (Object object)
void AreaDamageRegular (EntityAI parent)
void ~AreaDamageRegular ()
override void SetLoopInterval (float time)
override void SetHitZones (array< string > hitzones)
override void OnEnterServer (Object object)
void AreaDamageRegularRaycasted (EntityAI parent)
void ~AreaDamageRegularRaycasted ()
override void SetLoopInterval (float time)
override void SetRaycastSources (array< string > raycast_sources)
override void OnEnterServer (Object object)
void AreaDamageRegularRaycastedDeferred (EntityAI parent)
void ~AreaDamageRegularRaycastedDeferred ()
override void SetLoopInterval (float time)
override void SetDeferDuration (float time)
override void SetRaycastSources (array< string > raycast_sources)
override void OnEnterServer (Object object)
Private Attributes
protected AreaDamageBase m_AreaDamage
protected float m_PlayerDamage
protected float m_OthersDamage
protected string m_AmmoName
protected int m_DamageType
protected float m_LoopInterval
protected float m_DeferDuration
protected ref array< string > m_HitZones
protected ref array< string > m_RaycastSources
protected ref array< typename > m_DamageableTypes protected ref Timer m_LoopTimer
protected ref Timer m_DeferTimer
Constructor & Destructor Documentation
AreaDamageBase()
void AreaDamageBase (EntityAI parent) inline private
References CALL_CATEGORY_SYSTEM, m_AmmoName, m_AreaDamage, m_DamageType, m_DeferDuration, m_DeferTimer, m_HitZones, m_LoopInterval, m_LoopTimer, m_OthersDamage, m_PlayerDamage, m_RaycastSources, and m_TriggerBaseClass.
~AreaDamageOneTime()
void ~AreaDamageOneTime () inline private
~AreaDamageOneTimeDeferred()
void ~AreaDamageOneTimeDeferred () inline private
~AreaDamageOneTimeRaycasted()
void ~AreaDamageOneTimeRaycasted () inline private
~AreaDamageOneTimeRaycastedDeferred()
void ~AreaDamageOneTimeRaycastedDeferred () inline private
~AreaDamageRegular()
void ~AreaDamageRegular () inline private
~AreaDamageRegularRaycasted()
void ~AreaDamageRegularRaycasted () inline private
~AreaDamageRegularRaycastedDeferred()
void ~AreaDamageRegularRaycastedDeferred () inline private
Member Function Documentation
AreaDamageOneTime()
void AreaDamageOneTime (EntityAI parent) inline private
AreaDamageOneTimeDeferred()
void AreaDamageOneTimeDeferred (EntityAI parent) inline private
AreaDamageOneTimeRaycasted()
void AreaDamageOneTimeRaycasted (EntityAI parent) inline private
AreaDamageOneTimeRaycastedDeferred()
void AreaDamageOneTimeRaycastedDeferred (EntityAI parent) inline private
AreaDamageRegular()
void AreaDamageRegular (EntityAI parent) inline private
AreaDamageRegularRaycasted()
void AreaDamageRegularRaycasted (EntityAI parent) inline private
AreaDamageRegularRaycastedDeferred()
void AreaDamageRegularRaycastedDeferred (EntityAI parent) inline private
EvaluateDamage()
protected void EvaluateDamage (Object object) inline private
References EvaluateDamage_Common(), GetRandomHitZone(), GetRaycastedHitZone(), m_HitZones, and m_RaycastSources.
Referenced by OnEnterServer().
EvaluateDamage_Common()
protected void EvaluateDamage_Common (Object object, string hitzone) inline private
References m_AmmoName, m_DamageType, m_ParentObject, and PostDamageActions().
Referenced by EvaluateDamage().
EvaluateDamage_Defer()
protected void EvaluateDamage_Defer (Object object) inline private
References m_DeferDuration, and m_DeferTimer.
Referenced by OnEnterServer().
EvaluateDamage_DeferLoop()
protected void EvaluateDamage_DeferLoop (Object object) inline private
References m_DeferDuration, and m_DeferTimer.
Referenced by OnEnterServer().
EvaluateDamage_Loop()
protected void EvaluateDamage_Loop (Object object) inline private
References m_LoopInterval, m_LoopTimer, and array::Run().
Referenced by OnEnterServer().
GetRandomHitZone()
protected string GetRandomHitZone (array< string > hitzones) inline private
common
References Math::RandomInt(), and Math::Randomize().
Referenced by EvaluateDamage().
GetRaycastedHitZone()
protected string GetRaycastedHitZone (Object victim, array< string > raycast_sources_str) inline private
References m_AreaDamageTrigger, Math::RandomIntInclusive(), and DayZPhysics::RaycastRV().
Referenced by EvaluateDamage().
OnEnter()
void OnEnter (Object object) inline private
events
References GetGame(), OnEnterClient(), and OnEnterServer().
OnEnterClient()
void OnEnterClient (Object object) inline private
Referenced by OnEnter().
OnEnterServer() [1/8]
void OnEnterServer (Object object) inline private
Referenced by OnEnter().
OnEnterServer() [2/8]
override void OnEnterServer (Object object) inline private
References EvaluateDamage().
OnEnterServer() [3/8]
override void OnEnterServer (Object object) inline private
References EvaluateDamage_Defer().
OnEnterServer() [4/8]
override void OnEnterServer (Object object) inline private
References EvaluateDamage().
OnEnterServer() [5/8]
override void OnEnterServer (Object object) inline private
References EvaluateDamage_Defer().
OnEnterServer() [6/8]
override void OnEnterServer (Object object) inline private
OnEnterServer() [7/8]
override void OnEnterServer (Object object) inline private
References EvaluateDamage_Loop().
OnEnterServer() [8/8]
override void OnEnterServer (Object object) inline private
References EvaluateDamage_DeferLoop().
OnLeave()
void OnLeave (Object object) inline private
References GetGame(), OnLeaveClient(), and OnLeaveServer().
OnLeaveClient()
void OnLeaveClient (Object object) inline private
Referenced by OnLeave().
OnLeaveServer()
void OnLeaveServer (Object object) inline private
stop all running timers
References m_DeferTimer, m_LoopTimer, and Timer::Stop().
Referenced by OnLeave().
SetDeferDuration() [1/3]
override void SetDeferDuration (float time) inline private
References m_DeferDuration.
SetDeferDuration() [2/3]
override void SetDeferDuration (float time) inline private
References m_DeferDuration.
SetDeferDuration() [3/3]
override void SetDeferDuration (float time) inline private
References m_DeferDuration.
SetHitZones() [1/3]
override void SetHitZones (array< string > hitzones) inline private
SetHitZones() [2/3]
override void SetHitZones (array< string > hitzones) inline private
SetHitZones() [3/3]
override void SetHitZones (array< string > hitzones) inline private
SetLoopInterval() [1/3]
override void SetLoopInterval (float time) inline private
SetLoopInterval() [2/3]
override void SetLoopInterval (float time) inline private
SetLoopInterval() [3/3]
override void SetLoopInterval (float time) inline private
SetRaycastSources() [1/4]
override void SetRaycastSources (array< string > raycast_sources) inline private
SetRaycastSources() [2/4]
override void SetRaycastSources (array< string > raycast_sources) inline private
SetRaycastSources() [3/4]
override void SetRaycastSources (array< string > raycast_sources) inline private
SetRaycastSources() [4/4]
override void SetRaycastSources (array< string > raycast_sources) inline private
Field Documentation
m_AmmoName
protected string m_AmmoName private
Referenced by AreaDamageBase(), and EvaluateDamage_Common().
m_AreaDamage
protected AreaDamageBase m_AreaDamage private
Referenced by AreaDamageBase().
m_DamageType
protected int m_DamageType private
Referenced by AreaDamageBase(), and EvaluateDamage_Common().
m_DeferDuration
protected float m_DeferDuration private
Referenced by AreaDamageBase(), EvaluateDamage_Defer(), and EvaluateDamage_DeferLoop().
m_DeferTimer
protected ref Timer m_DeferTimer private
Referenced by AreaDamageBase(), EvaluateDamage_Defer(), EvaluateDamage_DeferLoop(), and OnLeaveServer().
m_HitZones
protected ref array<string> m_HitZones private
Referenced by AreaDamageBase(), and EvaluateDamage().
m_LoopInterval
protected float m_LoopInterval private
Referenced by AreaDamageBase(), and EvaluateDamage_Loop().
m_LoopTimer
protected ref array<typename> m_DamageableTypes protected ref Timer m_LoopTimer private
Referenced by AreaDamageBase(), EvaluateDamage_Loop(), and OnLeaveServer().
m_OthersDamage
protected float m_OthersDamage private
Referenced by AreaDamageBase().
m_PlayerDamage
protected float m_PlayerDamage private
Referenced by AreaDamageBase().
m_RaycastSources
protected ref array<string> m_RaycastSources private
Referenced by AreaDamageBase(), and EvaluateDamage().
The documentation for this class was generated from the following files:
4_World/Classes/AreaDamage/AreaDamage.c
4_World/Classes/AreaDamage/AreaDamageOneTime.c
4_World/Classes/AreaDamage/AreaDamageOneTimeDeferred.c
4_World/Classes/AreaDamage/AreaDamageOneTimeRaycasted.c
4_World/Classes/AreaDamage/AreaDamageOneTimeRaycastedDeferred.c
4_World/Classes/AreaDamage/AreaDamageRegular.c
4_World/Classes/AreaDamage/AreaDamageRegularRaycasted.c
4_World/Classes/AreaDamage/AreaDamageRegularRaycastedDeferred.c