DayZ Scripts: Backpack_Base Class Reference
Backpack_Base Class Reference
Private Member Functions
override bool IsClothing ()
void LargeTentBackPack ()
void ~LargeTentBackPack ()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
void PlayRepackingLoopSound ()
void StopRepackingLoopSound ()
Private Attributes
ref protected EffectSound m_RepackingLoopSound
Constructor & Destructor Documentation
~LargeTentBackPack()
void ~LargeTentBackPack () inline private
References SEffectManager::DestroyEffect(), and m_RepackingLoopSound.
Member Function Documentation
IsClothing()
override bool IsClothing () inline private
LargeTentBackPack()
void LargeTentBackPack () inline private
References m_RepackingLoopSound.
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
References PlayRepackingLoopSound(), Serializer::Read(), and StopRepackingLoopSound().
PlayRepackingLoopSound()
void PlayRepackingLoopSound () inline private
References GetPosition, m_RepackingLoopSound, and SEffectManager::PlaySound().
Referenced by OnRPC().
StopRepackingLoopSound()
void StopRepackingLoopSound () inline private
References m_RepackingLoopSound.
Referenced by OnRPC().
Field Documentation
m_RepackingLoopSound
ref protected EffectSound m_RepackingLoopSound private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/Clothing/AliceBag_ColorBase.c
P:/scripts/4_World/Entities/ItemBase/TentBase/LargeTentBackPack.c
P:/scripts/4_World/Entities/ItemBase/Clothing/LeatherSack_ColorBase.c