DayZ Scripts: FlareSimulation Class Reference
FlareSimulation Class Reference
Private Member Functions
void FlareSimulation ()
void OnActivation (Entity flare)
void OnTermination (Entity flare)
void OnFire (Entity flare)
void Simulate (Entity flare)
protected void FlareParticleUpdate ()
void CastFlareAINoise (vector position)
void TurnOffDistantLight ()
void ~FlareSimulation ()
Private Attributes
protected Particle m_ParMainFire
protected EffectSound m_BurningSound
protected FlareLight m_FlareLight
float m_LastNoiseTime = -1
float m_NoiseTimer = 0
const float NOISE_DELAY = 5
protected const float FLARE_SPIN_RATE = 1.15
protected const float FLARE_SPIN_RADIUS = 0.18
protected Entity m_Flare
protected vector m_RotationPoint
protected vector m_FlarePosition
protected float m_RotationDegrees
Static Private Attributes
static const float MAX_FARLIGHT_DIST = 40
static const float MIN_FARLIGHT_DIST = 5
static ref NoiseParams m_NoisePar
static protected m_ScriptedLight
static protected int m_ParticleId
Constructor & Destructor Documentation
FlareSimulation()
void FlareSimulation () inline private
References ParticleList::FLAREPROJ_ACTIVATE, m_ParticleId, and m_ScriptedLight.
~FlareSimulation()
void ~FlareSimulation () inline private
References m_BurningSound, m_FlareLight, m_ParMainFire, EffectSound::SoundStop(), and Particle::Stop().
Member Function Documentation
CastFlareAINoise()
void CastFlareAINoise (vector position) inline private
References GetGame(), CGame::GetTime(), m_LastNoiseTime, m_NoisePar, m_NoiseTimer, and NOISE_DELAY.
FlareParticleUpdate()
protected void FlareParticleUpdate () inline private
References Math::Cos(), Math::DEG2RAD, FLARE_SPIN_RATE, GetGame(), m_Flare, m_FlarePosition, m_ParMainFire, m_RotationDegrees, m_RotationPoint, Math::Sin(), CGame::SurfaceY(), and Vector().
Referenced by Simulate().
OnActivation()
void OnActivation (Entity flare) inline private
References FLARE_SPIN_RADIUS, GetGame(), m_BurningSound, m_Flare, m_FlareLight, m_FlarePosition, m_NoisePar, m_ParMainFire, m_ParticleId, m_RotationPoint, m_ScriptedLight, NoiseParams(), ParticleManager(), Particle::Stop(), and Vector().
OnFire()
void OnFire (Entity flare) inline private
OnTermination()
void OnTermination (Entity flare) inline private
Simulate()
void Simulate (Entity flare) inline private
References vector::DistanceSq(), FlareParticleUpdate(), GetGame(), CGame::GetPlayer(), m_ParMainFire, MAX_FARLIGHT_DIST, MIN_FARLIGHT_DIST, Particle::SetParameter(), and TurnOffDistantLight().
TurnOffDistantLight()
void TurnOffDistantLight () inline private
References m_ParMainFire, and Particle::SetParameter().
Referenced by Simulate().
Field Documentation
FLARE_SPIN_RADIUS
protected const float FLARE_SPIN_RADIUS = 0.18 private
Referenced by OnActivation().
FLARE_SPIN_RATE
protected const float FLARE_SPIN_RATE = 1.15 private
Referenced by FlareParticleUpdate().
m_BurningSound
protected EffectSound m_BurningSound private
Referenced by OnActivation(), and ~FlareSimulation().
m_Flare
protected Entity m_Flare private
Referenced by FlareParticleUpdate(), and OnActivation().
m_FlareLight
protected FlareLight m_FlareLight private
Referenced by OnActivation(), and ~FlareSimulation().
m_FlarePosition
protected vector m_FlarePosition private
Referenced by FlareParticleUpdate(), and OnActivation().
m_LastNoiseTime
float m_LastNoiseTime = -1 private
Referenced by CastFlareAINoise().
m_NoisePar
ref NoiseParams m_NoisePar static private
Referenced by CastFlareAINoise(), and OnActivation().
m_NoiseTimer
float m_NoiseTimer = 0 private
Referenced by CastFlareAINoise().
m_ParMainFire
protected Particle m_ParMainFire private
Referenced by FlareParticleUpdate(), OnActivation(), Simulate(), TurnOffDistantLight(), and ~FlareSimulation().
m_ParticleId
protected int m_ParticleId static private
Referenced by FlareSimulation(), and OnActivation().
m_RotationDegrees
protected float m_RotationDegrees private
Referenced by FlareParticleUpdate().
m_RotationPoint
protected vector m_RotationPoint private
Referenced by FlareParticleUpdate(), and OnActivation().
m_ScriptedLight
protected m_ScriptedLight static private
Referenced by FlareSimulation(), and OnActivation().
MAX_FARLIGHT_DIST
const float MAX_FARLIGHT_DIST = 40 static private
Referenced by Simulate().
MIN_FARLIGHT_DIST
const float MIN_FARLIGHT_DIST = 5 static private
Referenced by Simulate().
NOISE_DELAY
const float NOISE_DELAY = 5 private
Referenced by CastFlareAINoise().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/Firearms/FlareSimulation.c