DayZ Scripts: Anniversary_FireworksLauncher Class Reference
Anniversary_FireworksLauncher Class Reference
Private Member Functions
override protected void SetupColorSequences ()
override protected FireworksLauncherClientEventBase SpawnEvent ()
override bool IsTakeable ()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
override bool DisableVicinityIcon ()
override protected int GetMaxShots ()
override protected float GetFuseDelay ()
override protected void OnEventServer (int type)
Called periodically but only after the entity gets ignited.
Private Attributes
int sequence = 0
Member Function Documentation
CanSwapEntities()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination) inline private
DisableVicinityIcon()
override bool DisableVicinityIcon () inline private
GetFuseDelay()
override protected float GetFuseDelay () inline private
GetMaxShots()
override protected int GetMaxShots () inline private
Referenced by OnEventServer().
IsTakeable()
override bool IsTakeable () inline private
OnEventServer()
override protected void OnEventServer (int type) inline private
Called periodically but only after the entity gets ignited.
References FireworksLauncher::GetAmmoType(), FireworksLauncher::GetDamageType(), GetMaxShots(), GetPosition, FireworksLauncher::m_Index, m_TimerEvent, FireworksLauncher::RestartEventTimer(), sequence, and SetState().
SetupColorSequences()
override protected void SetupColorSequences () inline private
References FireworksLauncher::m_ColorSequence.
SpawnEvent()
override protected FireworksLauncherClientEventBase SpawnEvent () inline private
References FireworksLauncher::m_Index.
Field Documentation
sequence
int sequence = 0 private
Referenced by OnEventServer().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Entities/ItemBase/Gear/Tools/FireworksLauncherAnniversary.c