DayZ Scripts: SymptomManager Class Reference
SymptomManager Class Reference
Private Member Functions
void Init ()
int GetStorageVersion ()
void AutoactivateSymptoms ()
void SymptomManager (PlayerBase player)
void OnPlayerKilled ()
SymptomBase GetSymptomByUID (int SYMPTOM_uid)
void ~SymptomManager ()
PlayerBase GetPlayer ()
void RegisterSymptom (SymptomBase Symptom)
void OnAnimationFinished (eAnimFinishType type=eAnimFinishType.SUCCESS)
void OnAnimationStarted ()
int CreateUniqueID ()
bool IsUIDUsed (int uid)
string GetSymptomName (int symptom_id)
SmptAnimMetaBase SpawnAnimMetaObject (int symptom_id)
void RequestSymptomExit (int SYMPTOM_uid)
Exits a specific Symptom with a given UID.
bool IsSymptomPrimary (int symptom_id)
void OnInputUserDataReceived (ParamsReadContext ctx)
int GetCurrentCommandID ()
void OnTick (float deltatime, int pCurrentCommandID, HumanMovementState movement_state)
void SetAnimation (ParamsReadContext ctx)
void UpdateActiveSymptoms (float deltatime)
void OnSymptomExit (SymptomBase Symptom, int uid)
int GetSymptomMaxCount (int symptom_id)
int GetSymptomCount (int symptom_id)
void IncreaseSymptomCount (int symptom_id)
void DecreaseSymptomCount (int symptom_id)
SymptomBase SpawnSymptom (int symptom_id, int uid=-1)
void CleanUpPrimaryQueue ()
SymptomBase QueueUpPrimarySymptom (int symptom_id, int uid=-1)
void QueueUpSecondarySymptom (int symptom_id, int uid=-1)
SymptomBase QueueUpSecondarySymptomEx (int symptom_id, int uid=-1)
void RemoveSecondarySymptom (int symptom_id)
Removes a single Symptom.
SymptomBase GetCurrentPrimaryActiveSymptom ()
int FindFirstAvailableSymptomIndex ()
int ComparePriority (int prio1, int prio2)
int GetSymptomPriority (int symptom_id)
void OnRPC (int rpc_type, ParamsReadContext ctx)
void OnStoreSave (ParamsWriteContext ctx)
bool OnStoreLoad (ParamsReadContext ctx, int version)
Private Attributes
PlayerBase m_Player
ref map< int, ref SymptomBase > m_AvailableSymptoms
ref map< int, int > m_ActiveSymptomTypes
ref array< ref SymptomBase > m_SymptomQueuePrimary
ref array< ref SymptomBase > m_SymptomQueueSecondary
ref map< int, SymptomBase > m_SymptomsUIDs
ref array< ref Param > m_SymptomQueueServerDbg
ref array< ref Param > m_SymptomQueueServerDbgPrimary
ref array< ref Param > m_SymptomQueueServerDbgSecondary
ref Timer m_Timer
int m_ActiveSymptomIndexPrimary = -1
int m_CurrentCommandID
const int STORAGE_VERSION = 121
bool m_ShowDebug = false
bool m_ShowDebug2 = false
ref SmptAnimMetaBase m_AnimMeta
Detailed Description
Definition at line 42 of file StateManager.c.
Constructor & Destructor Documentation
SymptomManager()
void SymptomManager (PlayerBase player) inline private
Definition at line 103 of file StateManager.c.
References AutoactivateSymptoms(), Init(), m_ActiveSymptomTypes, m_AvailableSymptoms, m_Player, m_SymptomQueuePrimary, m_SymptomQueueSecondary, m_SymptomQueueServerDbg, m_SymptomQueueServerDbgPrimary, m_SymptomQueueServerDbgSecondary, and m_SymptomsUIDs.
~SymptomManager()
void ~SymptomManager () inline private
Definition at line 137 of file StateManager.c.
Member Function Documentation
AutoactivateSymptoms()
void AutoactivateSymptoms () inline private
Definition at line 93 of file StateManager.c.
References GetGame(), and QueueUpSecondarySymptom().
Referenced by SymptomManager().
CleanUpPrimaryQueue()
void CleanUpPrimaryQueue () inline private
Definition at line 436 of file StateManager.c.
References m_SymptomQueuePrimary.
Referenced by OnRPC().
ComparePriority()
int ComparePriority (int prio1, int prio2) inline private
Definition at line 536 of file StateManager.c.
Referenced by QueueUpPrimarySymptom().
CreateUniqueID()
int CreateUniqueID () inline private
Definition at line 175 of file StateManager.c.
References CreateUniqueID(), IsUIDUsed(), and Math::RandomInt().
Referenced by CreateUniqueID(), and SpawnSymptom().
DecreaseSymptomCount()
void DecreaseSymptomCount (int symptom_id) inline private
Definition at line 400 of file StateManager.c.
References m_ActiveSymptomTypes.
Referenced by OnSymptomExit().
FindFirstAvailableSymptomIndex()
int FindFirstAvailableSymptomIndex () inline private
Definition at line 524 of file StateManager.c.
References m_SymptomQueuePrimary.
Referenced by OnTick().
GetCurrentCommandID()
int GetCurrentCommandID () inline private
Definition at line 212 of file StateManager.c.
References m_CurrentCommandID.
GetCurrentPrimaryActiveSymptom()
SymptomBase GetCurrentPrimaryActiveSymptom () inline private
Definition at line 507 of file StateManager.c.
References GetGame(), m_ActiveSymptomIndexPrimary, and m_SymptomQueuePrimary.
Referenced by AnimFinished(), OnAnimationStarted(), and UpdateActiveSymptoms().
GetPlayer()
PlayerBase GetPlayer () inline private
Definition at line 141 of file StateManager.c.
References m_Player.
GetStorageVersion()
int GetStorageVersion () inline private
Definition at line 87 of file StateManager.c.
References STORAGE_VERSION.
GetSymptomByUID()
SymptomBase GetSymptomByUID (int SYMPTOM_uid) inline private
Definition at line 131 of file StateManager.c.
References m_SymptomsUIDs.
GetSymptomCount()
int GetSymptomCount (int symptom_id) inline private
Definition at line 380 of file StateManager.c.
References m_ActiveSymptomTypes.
Referenced by QueueUpPrimarySymptom(), and QueueUpSecondarySymptomEx().
GetSymptomMaxCount()
int GetSymptomMaxCount (int symptom_id) inline private
Definition at line 374 of file StateManager.c.
References m_AvailableSymptoms.
Referenced by QueueUpPrimarySymptom(), and QueueUpSecondarySymptomEx().
GetSymptomName()
string GetSymptomName (int symptom_id) inline private
Definition at line 187 of file StateManager.c.
References m_AvailableSymptoms.
GetSymptomPriority()
int GetSymptomPriority (int symptom_id) inline private
Definition at line 549 of file StateManager.c.
References m_AvailableSymptoms.
Referenced by QueueUpPrimarySymptom().
IncreaseSymptomCount()
void IncreaseSymptomCount (int symptom_id) inline private
Definition at line 388 of file StateManager.c.
References m_ActiveSymptomTypes.
Referenced by SpawnSymptom().
Init()
void Init () inline private
Definition at line 70 of file StateManager.c.
References RegisterSymptom().
Referenced by SymptomManager().
IsSymptomPrimary()
bool IsSymptomPrimary (int symptom_id) inline private
Definition at line 203 of file StateManager.c.
References m_AvailableSymptoms.
Referenced by OnStoreLoad().
IsUIDUsed()
bool IsUIDUsed (int uid) inline private
Definition at line 182 of file StateManager.c.
References m_SymptomsUIDs.
Referenced by CreateUniqueID().
OnAnimationFinished()
void OnAnimationFinished (eAnimFinishType type = eAnimFinishType.SUCCESS) inline private
Definition at line 161 of file StateManager.c.
References m_AnimMeta.
Referenced by OnTick(), PlayRequest(), and Update().
OnAnimationStarted()
void OnAnimationStarted () inline private
Definition at line 169 of file StateManager.c.
References SymptomBase::AnimationStart(), and GetCurrentPrimaryActiveSymptom().
Referenced by Update().
OnInputUserDataReceived()
void OnInputUserDataReceived (ParamsReadContext ctx) inline private
Definition at line 208 of file StateManager.c.
OnPlayerKilled()
void OnPlayerKilled () inline private
Definition at line 118 of file StateManager.c.
References m_SymptomQueuePrimary, and m_SymptomQueueSecondary.
OnRPC()
void OnRPC (int rpc_type, ParamsReadContext ctx) inline private
Definition at line 554 of file StateManager.c.
References CleanUpPrimaryQueue(), m_AvailableSymptoms, CachedObjectsParams::PARAM2_INT_INT, QueueUpPrimarySymptom(), QueueUpSecondarySymptom(), Serializer::Read(), and RemoveSecondarySymptom().
OnStoreLoad()
bool OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 610 of file StateManager.c.
References IsSymptomPrimary(), QueueUpPrimarySymptom(), QueueUpSecondarySymptom(), and Serializer::Read().
OnStoreSave()
void OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 587 of file StateManager.c.
References m_SymptomQueuePrimary, m_SymptomQueueSecondary, and Serializer::Write().
OnSymptomExit()
void OnSymptomExit (SymptomBase Symptom, int uid) inline private
Definition at line 327 of file StateManager.c.
References DecreaseSymptomCount(), GetGame(), SymptomBase::GetType(), SymptomBase::IsPrimary(), Debug::LogError(), m_ActiveSymptomIndexPrimary, m_SymptomQueuePrimary, m_SymptomQueueSecondary, and m_SymptomsUIDs.
Referenced by SymptomBase::OnDestructed().
OnTick()
void OnTick (float deltatime, int pCurrentCommandID, HumanMovementState movement_state) inline private
Definition at line 217 of file StateManager.c.
References FindFirstAvailableSymptomIndex(), DiagMenu::GetBool(), m_ActiveSymptomIndexPrimary, m_AnimMeta, m_CurrentCommandID, m_SymptomQueuePrimary, m_SymptomQueueSecondary, m_SymptomQueueServerDbgPrimary, m_SymptomQueueServerDbgSecondary, OnAnimationFinished(), and UpdateActiveSymptoms().
QueueUpPrimarySymptom()
SymptomBase QueueUpPrimarySymptom (int symptom_id, int uid = -1) inline private
Definition at line 445 of file StateManager.c.
References ComparePriority(), GetSymptomCount(), GetSymptomMaxCount(), GetSymptomPriority(), m_SymptomQueuePrimary, MAX_QUEUE_SIZE, and SpawnSymptom().
Referenced by OnRPC(), and OnStoreLoad().
QueueUpSecondarySymptom()
void QueueUpSecondarySymptom (int symptom_id, int uid = -1) inline private
Definition at line 475 of file StateManager.c.
References QueueUpSecondarySymptomEx().
Referenced by AutoactivateSymptoms(), OnRPC(), and OnStoreLoad().
QueueUpSecondarySymptomEx()
SymptomBase QueueUpSecondarySymptomEx (int symptom_id, int uid = -1) inline private
Definition at line 480 of file StateManager.c.
References GetSymptomCount(), GetSymptomMaxCount(), m_AvailableSymptoms, m_SymptomQueueSecondary, and SpawnSymptom().
Referenced by QueueUpSecondarySymptom().
RegisterSymptom()
void RegisterSymptom (SymptomBase Symptom) inline private
Definition at line 146 of file StateManager.c.
References Error(), SymptomBase::GetType(), SymptomBase::Init(), m_AvailableSymptoms, and m_Player.
Referenced by Init().
RemoveSecondarySymptom()
void RemoveSecondarySymptom (int symptom_id) inline private
Removes a single Symptom.
Definition at line 495 of file StateManager.c.
References m_SymptomQueueSecondary.
Referenced by OnRPC().
RequestSymptomExit()
void RequestSymptomExit (int SYMPTOM_uid) inline private
Exits a specific Symptom with a given UID.
Definition at line 198 of file StateManager.c.
References m_SymptomsUIDs.
SetAnimation()
void SetAnimation (ParamsReadContext ctx) inline private
Definition at line 275 of file StateManager.c.
References SmptAnimMetaBase::Init(), m_AnimMeta, m_Player, Serializer::Read(), and SpawnAnimMetaObject().
SpawnAnimMetaObject()
SmptAnimMetaBase SpawnAnimMetaObject (int symptom_id) inline private
Definition at line 192 of file StateManager.c.
References m_AvailableSymptoms.
Referenced by SetAnimation().
SpawnSymptom()
SymptomBase SpawnSymptom (int symptom_id, int uid = -1) inline private
Definition at line 411 of file StateManager.c.
References CreateUniqueID(), Error(), IncreaseSymptomCount(), SymptomBase::Init(), m_AvailableSymptoms, m_Player, and m_SymptomsUIDs.
Referenced by QueueUpPrimarySymptom(), and QueueUpSecondarySymptomEx().
UpdateActiveSymptoms()
void UpdateActiveSymptoms (float deltatime) inline private
Definition at line 296 of file StateManager.c.
References SymptomBase::Activate(), GetCurrentPrimaryActiveSymptom(), m_SymptomQueueSecondary, SymptomBase::Update(), and array::Update().
Referenced by OnTick().
Field Documentation
m_ActiveSymptomIndexPrimary
int m_ActiveSymptomIndexPrimary = -1 private
Definition at line 60 of file StateManager.c.
Referenced by GetCurrentPrimaryActiveSymptom(), OnSymptomExit(), and OnTick().
m_ActiveSymptomTypes
ref map<int, int> m_ActiveSymptomTypes private
Definition at line 46 of file StateManager.c.
Referenced by DecreaseSymptomCount(), GetSymptomCount(), IncreaseSymptomCount(), and SymptomManager().
m_AnimMeta
ref SmptAnimMetaBase m_AnimMeta private
Definition at line 68 of file StateManager.c.
Referenced by OnAnimationFinished(), OnTick(), and SetAnimation().
m_AvailableSymptoms
ref map<int, ref SymptomBase> m_AvailableSymptoms private
Definition at line 45 of file StateManager.c.
Referenced by GetSymptomMaxCount(), GetSymptomName(), GetSymptomPriority(), IsSymptomPrimary(), OnRPC(), QueueUpSecondarySymptomEx(), RegisterSymptom(), SpawnAnimMetaObject(), SpawnSymptom(), and SymptomManager().
m_CurrentCommandID
int m_CurrentCommandID private
Definition at line 61 of file StateManager.c.
Referenced by GetCurrentCommandID(), and OnTick().
m_Player
PlayerBase m_Player private
Definition at line 44 of file StateManager.c.
Referenced by GetPlayer(), RegisterSymptom(), SetAnimation(), SpawnSymptom(), and SymptomManager().
m_ShowDebug
bool m_ShowDebug = false private
Definition at line 65 of file StateManager.c.
m_ShowDebug2
bool m_ShowDebug2 = false private
Definition at line 66 of file StateManager.c.
m_SymptomQueuePrimary
ref array<ref SymptomBase> m_SymptomQueuePrimary private
Definition at line 48 of file StateManager.c.
Referenced by CleanUpPrimaryQueue(), FindFirstAvailableSymptomIndex(), GetCurrentPrimaryActiveSymptom(), OnPlayerKilled(), OnStoreSave(), OnSymptomExit(), OnTick(), QueueUpPrimarySymptom(), and SymptomManager().
m_SymptomQueueSecondary
ref array<ref SymptomBase> m_SymptomQueueSecondary private
Definition at line 49 of file StateManager.c.
Referenced by OnPlayerKilled(), OnStoreSave(), OnSymptomExit(), OnTick(), QueueUpSecondarySymptomEx(), RemoveSecondarySymptom(), SymptomManager(), and UpdateActiveSymptoms().
m_SymptomQueueServerDbg
ref array<ref Param> m_SymptomQueueServerDbg private
Definition at line 54 of file StateManager.c.
Referenced by SymptomManager().
m_SymptomQueueServerDbgPrimary
ref array<ref Param> m_SymptomQueueServerDbgPrimary private
Definition at line 55 of file StateManager.c.
Referenced by OnTick(), and SymptomManager().
m_SymptomQueueServerDbgSecondary
ref array<ref Param> m_SymptomQueueServerDbgSecondary private
Definition at line 56 of file StateManager.c.
Referenced by OnTick(), and SymptomManager().
m_SymptomsUIDs
ref map<int , SymptomBase > m_SymptomsUIDs private
Definition at line 51 of file StateManager.c.
Referenced by GetSymptomByUID(), IsUIDUsed(), OnSymptomExit(), RequestSymptomExit(), SpawnSymptom(), and SymptomManager().
m_Timer
ref Timer m_Timer private
Definition at line 58 of file StateManager.c.
STORAGE_VERSION
const int STORAGE_VERSION = 121 private
Definition at line 63 of file StateManager.c.
Referenced by GetStorageVersion().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerSymptoms/StateManager.c