DayZ Scripts: ShockMdfr Class Reference
ShockMdfr Class Reference
Private Member Functions
override void Init ()
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
float GetRefillSpeed (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
override void OnReconnect (PlayerBase player)
Private Attributes
private const float UNCONSCIOUS_LIMIT = 50
private const float SHOCK_INCREMENT_PER_SEC = 1
Member Function Documentation
ActivateCondition()
override bool ActivateCondition (PlayerBase player) inline private
DeactivateCondition()
override bool DeactivateCondition (PlayerBase player) inline private
GetRefillSpeed()
float GetRefillSpeed (PlayerBase player) inline private
References CfgGameplayHandler::GetShockRefillSpeedConscious(), and CfgGameplayHandler::GetShockRefillSpeedUnconscious().
Referenced by OnTick().
Init()
override void Init () inline private
References DisableDeactivateCheck(), m_ID, m_TickIntervalActive, and m_TickIntervalInactive.
OnActivate()
override void OnActivate (PlayerBase player) inline private
OnDeactivate()
override void OnDeactivate (PlayerBase player) inline private
OnReconnect()
override void OnReconnect (PlayerBase player) inline private
OnTick()
override void OnTick (PlayerBase player, float deltaT) inline private
References CfgGameplayHandler::GetAllowRefillSpeedModifier(), GetGame(), GetRefillSpeed(), GetTime(), and PlayerConstants::SHOCK_REFILL_COOLDOWN_AFTER_HIT.
Field Documentation
SHOCK_INCREMENT_PER_SEC
private const float SHOCK_INCREMENT_PER_SEC = 1 private
UNCONSCIOUS_LIMIT
private const float UNCONSCIOUS_LIMIT = 50 private
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/PlayerModifiers/Modifiers/Shock.c