DayZ Scripts: WrittenNoteData Class Reference
WrittenNoteData Class Reference
Private Member Functions
void WrittenNoteData (ItemBase parent)
void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
void InitNoteInfo (ItemBase pen=null, ItemBase paper=null)
bool GetNoteInfo (out ItemBase pen, out ItemBase paper)
string GetNoteText ()
void SetNoteText (string text)
void DepleteWritingImplement (notnull ItemBase pen, string old_text, string new_text)
Private Attributes
protected ItemBase m_WritingImplement
protected ItemBase m_Paper
protected string m_SimpleText
Constructor & Destructor Documentation
WrittenNoteData()
void WrittenNoteData (ItemBase parent) inline private
Member Function Documentation
DepleteWritingImplement()
void DepleteWritingImplement (notnull ItemBase pen, string old_text, string new_text) inline private
References Math::Clamp(), and string::Length().
Referenced by OnRPC().
GetNoteInfo()
bool GetNoteInfo (out ItemBase pen, out ItemBase paper) inline private
References m_Paper, and m_WritingImplement.
Referenced by OnRPC().
GetNoteText()
string GetNoteText () inline private
References m_SimpleText.
Referenced by ActionReadPaperCB::OnStateChange(), and ActionWritePaperCB::OnStateChange().
InitNoteInfo()
void InitNoteInfo (ItemBase pen = null, ItemBase paper = null) inline private
References m_Paper, and m_WritingImplement.
Referenced by ActionWritePaper::OnStartClient(), and ActionWritePaper::OnStartServer().
OnRPC()
void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
References DepleteWritingImplement(), g_Game, GetGame(), GetNoteInfo(), m_SimpleText, m_WritingImplement, MENU_NOTE, Serializer::Read(), and SetNoteText().
Referenced by InventoryItem::OnRPC().
SetNoteText()
void SetNoteText (string text) inline private
References m_SimpleText.
Referenced by OnRPC().
Field Documentation
m_Paper
protected ItemBase m_Paper private
Referenced by GetNoteInfo(), and InitNoteInfo().
m_SimpleText
protected string m_SimpleText private
Referenced by GetNoteText(), OnRPC(), and SetNoteText().
m_WritingImplement
protected ItemBase m_WritingImplement private
Referenced by GetNoteInfo(), InitNoteInfo(), and OnRPC().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/WrittenNoteData.c