DayZ Scripts: ActionWritePaperCB Class Reference
ActionWritePaperCB Class Reference
Private Member Functions
override void CreateActionComponent ()
override void EndActionComponent ()
override void OnStateChange (int pOldState, int pCurrentState)
Detailed Description
Definition at line 1 of file ActionWritePaper.c.
Member Function Documentation
CreateActionComponent()
override void CreateActionComponent () inline private
Definition at line 3 of file ActionWritePaper.c.
References EnableStateChangeCallback(), ActionData::m_ActionComponent, and ActionBaseCB::m_ActionData.
EndActionComponent()
override void EndActionComponent () inline private
Definition at line 9 of file ActionWritePaper.c.
OnStateChange()
override void OnStateChange (int pOldState, int pCurrentState) inline private
Definition at line 13 of file ActionWritePaper.c.
References UIManager::FindMenu(), GetGame(), WrittenNoteData::GetNoteText(), CGame::GetUIManager(), ItemBase::GetWrittenNoteData(), ActionBaseCB::m_ActionData, ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, MENU_NOTE, STATE_LOOP_LOOP, and STATE_NONE.
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/UserActionsComponent/Actions/SingleUse/ActionWritePaper.c