DayZ Scripts: Container_Base Class Reference
Container_Base Class Reference
Private Member Functions
override bool IsContainer ()
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override void DeferredInit ()
override void EEDelete (EntityAI parent)
override bool IsContainer ()
override bool IsTakeable ()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
override bool CanPutInCargo (EntityAI parent)
override bool DisableVicinityIcon ()
override bool CanDisplayCargo ()
void EmtpyInventory ()
void FillInventory ()
override bool IsContainer ()
override bool CanPutInCargo (EntityAI parent)
void GiftBox_Base ()
override bool CanReceiveItemIntoCargo (EntityAI item)
override void Open ()
override void Close ()
override bool IsOpen ()
override void SetActions ()
override void OnDebugSpawn ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
Private Attributes
private const int SPAWN_SHIRTS_MAX = 60
protected AnniversaryBoxLight m_Light
protected vector m_HalfExtents
protected ref OpenableBehaviour m_Openable
Member Function Documentation
CanDisplayCargo()
override bool CanDisplayCargo () inline private
CanPutInCargo() [1/3]
override bool CanPutInCargo (EntityAI parent) inline private
References GetType().
CanPutInCargo() [2/3]
override bool CanPutInCargo (EntityAI parent) inline private
CanPutInCargo() [3/3]
override bool CanPutInCargo (EntityAI parent) inline private
CanReceiveItemIntoCargo() [1/2]
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
CanReceiveItemIntoCargo() [2/2]
override bool CanReceiveItemIntoCargo (EntityAI item) inline private
References GetGame(), GameInventory::GetInventoryCheckContext(), and IsOpen().
CanSwapEntities()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination) inline private
Close()
override void Close () inline private
DeferredInit()
override void DeferredInit () inline private
References m_Light.
DisableVicinityIcon()
override bool DisableVicinityIcon () inline private
EEDelete()
override void EEDelete (EntityAI parent) inline private
References m_Light.
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
References GetGame(), m_HalfExtents, and GameConstants::STATE_RUINED.
EmtpyInventory()
void EmtpyInventory () inline private
References GetGame().
FillInventory()
void FillInventory () inline private
References GetGame().
GiftBox_Base()
void GiftBox_Base () inline private
References m_HalfExtents, and vector::Zero.
IsContainer() [1/3]
override bool IsContainer () inline private
IsContainer() [2/3]
override bool IsContainer () inline private
IsContainer() [3/3]
override bool IsContainer () inline private
IsOpen()
override bool IsOpen () inline private
Referenced by CanReceiveItemIntoCargo().
IsTakeable()
override bool IsTakeable () inline private
OnDebugSpawn()
override void OnDebugSpawn () inline private
References Class::CastTo().
Open()
override void Open () inline private
SetActions()
override void SetActions () inline private
References AddAction().
Field Documentation
m_HalfExtents
protected vector m_HalfExtents private
m_Light
protected AnniversaryBoxLight m_Light private
m_Openable
protected ref OpenableBehaviour m_Openable private
SPAWN_SHIRTS_MAX
private const int SPAWN_SHIRTS_MAX = 60 private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Entities/ItemBase/Container_Base.c
P:/scripts/4_World/Entities/ItemBase/Container_Base/AnniversaryBox.c
P:/scripts/4_World/Entities/ItemBase/GiftBox_Base.c
P:/scripts/4_World/Entities/ItemBase/Container_Base/EN5C_Bear_ColorBase.c