DayZ Scripts: HandsContainer Class Reference
HandsContainer Class Reference
Private Member Functions
void HandsContainer (LayoutHolder parent)
void ~HandsContainer ()
void ResetContainer ()
override Header GetHeader ()
override bool IsLastIndex ()
void SetFocusToIndex ()
void ScrollToActiveContainer (Container active_container)
override void Insert (LayoutHolder container, int pos=-1, bool immedUpdate=true)
void MouseClick2 (Widget w, int x, int y, int button)
void DraggingOverHeader2 (Widget w, int x, int y, Widget receiver)
override bool TransferItem ()
override bool SplitItem ()
override bool EquipItem ()
override void SetActive (bool active)
override void SetLastActive ()
override void Refresh ()
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override bool IsEmpty ()
override bool TransferItemToVicinity ()
override bool InspectItem ()
override bool OnSelectButton ()
EntityAI GetItemPreviewItem (Widget w)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromHeader2 (Widget w, int x, int y, Widget receiver)
void OnPerformCombination (int combinationFlags)
void ShowActionMenuCombine (EntityAI entity1, EntityAI entity2, int combinationFlags)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
int GetCombinationFlags (EntityAI entity1, EntityAI entity2)
int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2)
void RemoveItem ()
void DestroyAtt ()
override void UnfocusGrid ()
override void UnfocusAll ()
void DestroyCargo ()
void DropReceived (Widget w, int x, int y, CargoContainer cargo)
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo)
void TakeAsAttachment (Widget w, Widget receiver)
void ShowAtt (EntityAI entity)
void RefreshHands ()
void AttachmentAdded (EntityAI item, string slot, EntityAI parent)
void AttachmentRemoved (EntityAI item, string slot, EntityAI parent)
override void UpdateInterval ()
override void SetLayoutName ()
override void OnShow ()
void DoubleClick (Widget w, int x, int y, int button)
void ElectricityIcon ()
void CollapseButtonOnMouseButtonDown (Widget w)
void HideCargo ()
void ShowCargo ()
Private Attributes
protected bool m_Hidden
protected ref HandsHeader m_CollapsibleHeader
protected ref HandsPreview m_HandsPreview
protected ref Attachments m_Atts
protected ref CargoContainer m_CargoGrid
protected ref map< EntityAI, ref CargoContainer > m_AttachmentCargos
protected ref map< EntityAI, AttachmentsWrapper > m_AttachmentAttachmentsContainers
protected ref map< EntityAI, ref Attachments > m_AttachmentAttachments
protected ref array< int > m_AttachmentSlotsSorted
protected int m_StaticAttCount = 0
protected int m_StaticCargoCount = 0
protected ScrollWidget m_ScrollWidget
Detailed Description
Definition at line 1 of file HandsContainer.c.
Constructor & Destructor Documentation
HandsContainer()
void HandsContainer (LayoutHolder parent) inline private
Definition at line 20 of file HandsContainer.c.
References HandsPreview::CreateNewIcon(), GetGame(), ItemManager::GetInstance(), GetPlayer(), m_AttachmentAttachments, m_AttachmentAttachmentsContainers, m_AttachmentCargos, m_CollapsibleHeader, m_HandsPreview, m_RootWidget, m_ScrollWidget, and ItemManager::SetHandsPreview().
~HandsContainer()
void ~HandsContainer () inline private
Definition at line 43 of file HandsContainer.c.
References AttachmentAdded(), AttachmentRemoved(), m_AttachmentAttachments, m_AttachmentAttachmentsContainers, m_AttachmentCargos, m_Entity, and ScriptedWidgetEventHandler::Remove().
Member Function Documentation
AttachmentAdded()
void AttachmentAdded (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 1297 of file HandsContainer.c.
References Container::CargoContainer(), Attachments::GetFalseHeaderTextWidget(), InventorySlots::GetSlotIdFromString(), Attachments::GetWrapper(), Attachments::InitAttachmentGrid(), Insert(), Inventory(), m_AttachmentAttachments, m_AttachmentAttachmentsContainers, m_AttachmentCargos, m_AttachmentSlotsSorted, m_Parent, Attachments::ShowFalseAttachmentsHeader(), and Attachments::UpdateInterval().
Referenced by DestroyAtt(), ShowAtt(), and ~HandsContainer().
AttachmentRemoved()
void AttachmentRemoved (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 1352 of file HandsContainer.c.
References Container::CargoContainer(), InventorySlots::GetSlotIdFromString(), Inventory(), m_AttachmentAttachments, m_AttachmentAttachmentsContainers, m_AttachmentCargos, and m_Parent.
Referenced by DestroyAtt(), ShowAtt(), and ~HandsContainer().
CollapseButtonOnMouseButtonDown()
void CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 1520 of file HandsContainer.c.
References m_Hidden, and m_Parent.
DestroyAtt()
void DestroyAtt () inline private
Definition at line 899 of file HandsContainer.c.
References AttachmentAdded(), AttachmentRemoved(), Attachments::GetWrapper(), m_AttachmentAttachments, m_AttachmentAttachmentsContainers, m_Atts, m_Entity, m_Parent, Refresh(), and ScriptedWidgetEventHandler::Remove().
DestroyCargo()
void DestroyCargo () inline private
Definition at line 964 of file HandsContainer.c.
References Container::CargoContainer(), m_AttachmentCargos, m_CargoGrid, m_Parent, and Refresh().
DoubleClick()
void DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 1432 of file HandsContainer.c.
References Class::CastTo(), g_Game, GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), name, and string::Replace().
DraggingOverGrid()
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo) inline private
Definition at line 1076 of file HandsContainer.c.
References ItemManager::GetCenterDropzone(), GetGame(), ItemManager::GetInstance(), GetItemPreviewItem(), CGame::GetPlayer(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), name, ColorManager::RED_COLOR, string::Replace(), ItemManager::ShowSourceDropzone(), x, and y.
Referenced by Icon::OnDraggingOverBackground().
DraggingOverHeader()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 470 of file HandsContainer.c.
References ItemBase::CanBeCombined(), GameInventory::CanSwapEntitiesEx(), ColorManager::COMBINE_COLOR, ItemManager::GetCenterDropzone(), SlotsIcon::GetEntity(), GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_Entity, name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and ColorManager::SWAP_COLOR.
Referenced by DraggingOverHeader2().
DraggingOverHeader2()
void DraggingOverHeader2 (Widget w, int x, int y, Widget receiver) inline private
Definition at line 210 of file HandsContainer.c.
References DraggingOverHeader(), x, and y.
DropReceived()
void DropReceived (Widget w, int x, int y, CargoContainer cargo) inline private
Definition at line 987 of file HandsContainer.c.
References ColorManager::BASE_COLOR, InventoryLocation::CompareLocationOnly(), InventoryLocation::GetFlip(), GetGame(), CargoBase::GetHeight(), ItemManager::GetInstance(), CargoBase::GetItemCount(), GetItemPreviewItem(), GetPlayer(), CargoBase::GetWidth(), ItemManager::HideDropzones(), InventoryLocation::IsValid(), m_AttachmentCargos, m_CargoGrid, m_Entity, Icon::Refresh(), Refresh(), InventoryLocation::SetCargoAuto(), ItemManager::SetIsDragging(), SplitItemUtils::TakeOrSplitToInventoryLocation(), x, and y.
ElectricityIcon()
void ElectricityIcon () inline private
Definition at line 1497 of file HandsContainer.c.
References FindAnyWidget(), GetGame(), and CGame::GetPlayer().
Referenced by UpdateInterval().
EquipItem()
override bool EquipItem () inline private
Definition at line 257 of file HandsContainer.c.
References GetGame(), and GetPlayer().
GetCombinationFlags()
int GetCombinationFlags (EntityAI entity1, EntityAI entity2) inline private
Definition at line 801 of file HandsContainer.c.
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, ItemBase::CanBeCombined(), ActionManagerClient::CanSetActionFromInventory(), GameInventory::CanSwapEntitiesEx(), WeaponManager::CanSwapMagazine(), Class::CastTo(), InventoryCombinationFlags::COMBINE_QUANTITY2, GetGame(), GetPlayer(), GetRecipeCount(), DayZPlayer::GetWeaponManager(), m_player, InventoryCombinationFlags::RECIPE_ANYWHERE, InventoryCombinationFlags::SET_ACTION, InventoryCombinationFlags::SWAP, and InventoryCombinationFlags::TAKE_TO_HANDS.
GetHeader()
override Header GetHeader () inline private
Definition at line 62 of file HandsContainer.c.
References m_CollapsibleHeader.
Referenced by HandsPreview::CreateNewIcon().
GetItemPreviewItem()
EntityAI GetItemPreviewItem (Widget w) inline private
Definition at line 447 of file HandsContainer.c.
References ItemPreviewWidget::GetItem(), name, and string::Replace().
Referenced by DraggingOverGrid(), DropReceived(), and TakeAsAttachment().
GetRecipeCount()
int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2) inline private
Definition at line 887 of file HandsContainer.c.
References GetGame(), GetPlayer(), and GetPlugin().
Referenced by GetCombinationFlags().
HideCargo()
void HideCargo () inline private
Definition at line 1546 of file HandsContainer.c.
References m_CargoGrid.
Referenced by ShowAtt(), and UpdateInterval().
Insert()
override void Insert (LayoutHolder container, int pos = -1, bool immedUpdate = true) inline private
Definition at line 182 of file HandsContainer.c.
Referenced by AttachmentAdded(), and ShowAtt().
InspectItem()
override bool InspectItem () inline private
Definition at line 395 of file HandsContainer.c.
References GetGame(), GetPlayer(), and InspectItem().
Referenced by InspectItem(), and MouseClick2().
IsEmpty()
override bool IsEmpty () inline private
Definition at line 365 of file HandsContainer.c.
References GetGame(), and GetPlayer().
Referenced by IsItemActive(), and IsItemWithQuantityActive().
IsItemActive()
override bool IsItemActive () inline private
Definition at line 343 of file HandsContainer.c.
References GetGame(), GetPlayer(), QuantityConversions::HasItemQuantity(), and IsEmpty().
IsItemWithQuantityActive()
override bool IsItemWithQuantityActive () inline private
Definition at line 354 of file HandsContainer.c.
References GetGame(), GetPlayer(), QuantityConversions::HasItemQuantity(), and IsEmpty().
IsLastIndex()
override bool IsLastIndex () inline private
Definition at line 67 of file HandsContainer.c.
MouseClick2()
void MouseClick2 (Widget w, int x, int y, int button) inline private
Definition at line 187 of file HandsContainer.c.
References ItemPreviewWidget::GetItem(), InspectItem(), name, and string::Replace().
OnDropReceivedFromHeader()
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 796 of file HandsContainer.c.
References TakeAsAttachment().
OnDropReceivedFromHeader2()
void OnDropReceivedFromHeader2 (Widget w, int x, int y, Widget receiver) inline private
Definition at line 630 of file HandsContainer.c.
References TakeAsAttachment().
OnPerformCombination()
void OnPerformCombination (int combinationFlags) inline private
Definition at line 635 of file HandsContainer.c.
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, WeaponManager::AttachMagazine(), WeaponManager::CanAttachMagazine(), WeaponManager::CanSwapMagazine(), Class::CastTo(), GetGame(), GetPlayer(), DayZPlayer::GetWeaponManager(), Attachments::GetWrapper(), Attachments::InitAttachmentGrid(), InventoryCombinationFlags::LOAD_CHAMBER, WeaponManager::LoadBullet(), m_Atts, m_Parent, m_player, InventoryCombinationFlags::NONE, Refresh(), InventoryCombinationFlags::SWAP, WeaponManager::SwapMagazine(), InventoryCombinationFlags::TAKE_TO_HANDS, and SplitItemUtils::TakeOrSplitToInventory().
OnSelectButton()
override bool OnSelectButton () inline private
Definition at line 414 of file HandsContainer.c.
References Container::GetFocusedItem(), ItemManager::GetInstance(), ItemManager::GetSelectedItem(), Inventory(), ItemManager::IsMicromanagmentMode(), and Container::Select().
OnShow()
override void OnShow () inline private
Definition at line 1422 of file HandsContainer.c.
Referenced by HandsArea::OnShow().
Refresh()
override void Refresh () inline private
Definition at line 337 of file HandsContainer.c.
References m_IsActive, and SetActive().
Referenced by DestroyAtt(), DestroyCargo(), DropReceived(), OnPerformCombination(), RefreshHands(), and ShowAtt().
RefreshHands()
void RefreshHands () inline private
Definition at line 1287 of file HandsContainer.c.
References m_Parent, and Refresh().
RemoveItem()
void RemoveItem () inline private
Definition at line 893 of file HandsContainer.c.
References m_CollapsibleHeader, m_Entity, and HandsHeader::ShowCollapseButtons().
ResetContainer()
void ResetContainer () inline private
Definition at line 56 of file HandsContainer.c.
References m_HandsPreview.
Referenced by ShowAtt().
ScrollToActiveContainer()
void ScrollToActiveContainer (Container active_container) inline private
Definition at line 160 of file HandsContainer.c.
References Container::GetFocusedContainerHeight(), Container::GetFocusedContainerYScreenPos(), m_ScrollWidget, x, and y.
Referenced by SetFocusToIndex().
SetActive()
override void SetActive (bool active) inline private
Definition at line 282 of file HandsContainer.c.
References GetGame(), GetPlayer(), x, and y.
SetFocusToIndex()
void SetFocusToIndex () inline private
Definition at line 72 of file HandsContainer.c.
References Attachments::GetWrapper(), m_AttachmentAttachments, m_AttachmentCargos, m_Atts, m_CargoGrid, m_ScrollWidget, ScrollToActiveContainer(), and Attachments::SetDefaultFocus().
SetLastActive()
override void SetLastActive () inline private
Definition at line 311 of file HandsContainer.c.
References GetGame(), GetPlayer(), x, and y.
SetLayoutName()
override void SetLayoutName () inline private
Definition at line 1417 of file HandsContainer.c.
References WidgetLayoutName::ClosableContainer.
ShowActionMenuCombine()
void ShowActionMenuCombine (EntityAI entity1, EntityAI entity2, int combinationFlags) inline private
Definition at line 737 of file HandsContainer.c.
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, InventoryCombinationFlags::COMBINE_QUANTITY, InventoryCombinationFlags::COMBINE_QUANTITY2, GetContextMenu(), GetGame(), GetMousePos(), InventoryCombinationFlags::LOAD_CHAMBER, InventoryCombinationFlags::NONE, PrintString(), InventoryCombinationFlags::SWAP, and InventoryCombinationFlags::TAKE_TO_HANDS.
ShowAtt()
void ShowAtt (EntityAI entity) inline private
Definition at line 1229 of file HandsContainer.c.
References AttachmentAdded(), AttachmentRemoved(), Container::CargoContainer(), Attachments::GetAttachmentHeight(), InventorySlots::GetSlotName(), Attachments::GetSlotsSorted(), HideCargo(), Attachments::InitAttachmentGrid(), Insert(), m_AttachmentSlotsSorted, m_Atts, m_CargoGrid, m_CollapsibleHeader, m_Entity, m_Parent, m_StaticAttCount, m_StaticCargoCount, Refresh(), ResetContainer(), ShowCargo(), and HandsHeader::ShowCollapseButtons().
ShowCargo()
void ShowCargo () inline private
Definition at line 1555 of file HandsContainer.c.
References m_CargoGrid.
Referenced by ShowAtt(), and UpdateInterval().
SplitItem()
override bool SplitItem () inline private
Definition at line 237 of file HandsContainer.c.
References GetGame(), and GetPlayer().
TakeAsAttachment()
void TakeAsAttachment (Widget w, Widget receiver) inline private
Definition at line 1125 of file HandsContainer.c.
References GameInventory::CanSwapEntitiesEx(), Class::CastTo(), CombineItemsClient(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), GetItemPreviewItem(), CGame::GetPlayer(), GetPlayer(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), ItemManager::HideDropzones(), m_Entity, ItemManager::SetIsDragging(), and SplitItemUtils::TakeOrSplitToInventory().
Referenced by OnDropReceivedFromHeader(), and OnDropReceivedFromHeader2().
TransferItem()
override bool TransferItem () inline private
Definition at line 215 of file HandsContainer.c.
References GetGame(), CGame::GetPlayer(), and GetPlayer().
TransferItemToVicinity()
override bool TransferItemToVicinity () inline private
Definition at line 371 of file HandsContainer.c.
References GetGame(), and GetPlayer().
UnfocusAll()
override void UnfocusAll () inline private
Definition at line 959 of file HandsContainer.c.
References UnfocusGrid().
UnfocusGrid()
override void UnfocusGrid () inline private
Definition at line 929 of file HandsContainer.c.
References Container::CargoContainer(), m_AttachmentAttachments, m_AttachmentCargos, m_Atts, m_CargoGrid, and Attachments::UnfocusAll().
Referenced by UnfocusAll().
UpdateInterval()
override void UpdateInterval () inline private
Definition at line 1381 of file HandsContainer.c.
References ElectricityIcon(), HideCargo(), m_AttachmentCargos, m_Atts, m_CargoGrid, m_CollapsibleHeader, m_Entity, ShowCargo(), Attachments::UpdateInterval(), and HandsHeader::UpdateInterval().
Referenced by HandsArea::UpdateInterval().
Field Documentation
m_AttachmentAttachments
protected ref map<EntityAI, ref Attachments> m_AttachmentAttachments private
Definition at line 12 of file HandsContainer.c.
Referenced by AttachmentAdded(), AttachmentRemoved(), DestroyAtt(), HandsContainer(), SetFocusToIndex(), UnfocusGrid(), and ~HandsContainer().
m_AttachmentAttachmentsContainers
protected ref map<EntityAI, AttachmentsWrapper> m_AttachmentAttachmentsContainers private
Definition at line 11 of file HandsContainer.c.
Referenced by AttachmentAdded(), AttachmentRemoved(), DestroyAtt(), HandsContainer(), and ~HandsContainer().
m_AttachmentCargos
protected ref map<EntityAI, ref CargoContainer> m_AttachmentCargos private
Definition at line 10 of file HandsContainer.c.
Referenced by AttachmentAdded(), AttachmentRemoved(), DestroyCargo(), DropReceived(), HandsContainer(), SetFocusToIndex(), UnfocusGrid(), UpdateInterval(), and ~HandsContainer().
m_AttachmentSlotsSorted
protected ref array<int> m_AttachmentSlotsSorted private
Definition at line 13 of file HandsContainer.c.
Referenced by AttachmentAdded(), and ShowAtt().
m_Atts
protected ref Attachments m_Atts private
Definition at line 7 of file HandsContainer.c.
Referenced by DestroyAtt(), OnPerformCombination(), SetFocusToIndex(), ShowAtt(), UnfocusGrid(), and UpdateInterval().
m_CargoGrid
protected ref CargoContainer m_CargoGrid private
Definition at line 8 of file HandsContainer.c.
Referenced by DestroyCargo(), DropReceived(), HideCargo(), SetFocusToIndex(), ShowAtt(), ShowCargo(), UnfocusGrid(), and UpdateInterval().
m_CollapsibleHeader
protected ref HandsHeader m_CollapsibleHeader private
Definition at line 4 of file HandsContainer.c.
Referenced by GetHeader(), HandsContainer(), RemoveItem(), ShowAtt(), and UpdateInterval().
m_HandsPreview
protected ref HandsPreview m_HandsPreview private
Definition at line 5 of file HandsContainer.c.
Referenced by HandsContainer(), and ResetContainer().
m_Hidden
protected bool m_Hidden private
Definition at line 3 of file HandsContainer.c.
Referenced by CollapseButtonOnMouseButtonDown().
m_ScrollWidget
protected ScrollWidget m_ScrollWidget private
Definition at line 18 of file HandsContainer.c.
Referenced by HandsContainer(), ScrollToActiveContainer(), and SetFocusToIndex().
m_StaticAttCount
protected int m_StaticAttCount = 0 private
Definition at line 15 of file HandsContainer.c.
Referenced by ShowAtt().
m_StaticCargoCount
protected int m_StaticCargoCount = 0 private
Definition at line 16 of file HandsContainer.c.
Referenced by ShowAtt().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/InventoryNew/Containers/HandsContainer.c