DayZ Scripts: ScriptConsoleOutputTab Class Reference
ScriptConsoleOutputTab Class Reference
Private Member Functions
void ScriptConsoleOutputTab (Widget root, ScriptConsole console)
void ~ScriptConsoleOutputTab ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnChange (Widget w, int x, int y, bool finished)
protected void Clear (bool clearFile=false)
protected void Add (string message, bool isReload=false)
protected void ReloadOutput ()
Private Attributes
protected TextListboxWidget m_ClientLogListbox
protected ButtonWidget m_ClientLogClearButton
protected CheckBoxWidget m_ClientLogScrollCheckbox
Constructor & Destructor Documentation
ScriptConsoleOutputTab()
void ScriptConsoleOutputTab (Widget root, ScriptConsole console) inline private
References m_ClientLogClearButton, m_ClientLogListbox, m_ClientLogScrollCheckbox, and ReloadOutput().
~ScriptConsoleOutputTab()
void ~ScriptConsoleOutputTab () inline private
Member Function Documentation
Add()
protected void Add (string message, bool isReload = false) inline private
References m_ClientLogListbox, m_ClientLogScrollCheckbox, and String().
Referenced by ReloadOutput().
Clear()
protected void Clear (bool clearFile = false) inline private
References Debug::ClearLogs(), and m_ClientLogListbox.
Referenced by OnClick(), and ReloadOutput().
OnChange()
override bool OnChange (Widget w, int x, int y, bool finished) inline private
References x, and y.
OnClick()
override bool OnClick (Widget w, int x, int y, int button) inline private
References Clear(), m_ClientLogClearButton, x, and y.
ReloadOutput()
protected void ReloadOutput () inline private
References Add(), Clear(), CloseFile(), FGets(), Debug::GetFileName(), and OpenFile().
Referenced by ScriptConsoleOutputTab().
Field Documentation
m_ClientLogClearButton
protected ButtonWidget m_ClientLogClearButton private
Referenced by OnClick(), and ScriptConsoleOutputTab().
m_ClientLogListbox
protected TextListboxWidget m_ClientLogListbox private
Referenced by Add(), Clear(), and ScriptConsoleOutputTab().
m_ClientLogScrollCheckbox
protected CheckBoxWidget m_ClientLogScrollCheckbox private
Referenced by Add(), and ScriptConsoleOutputTab().
The documentation for this class was generated from the following file:
P:/scripts/5_Mission/GUI/ScriptConsoleOutputTab.c