DayZ Scripts: HandActionBase Class Reference
HandActionBase Class Reference
actions
Private Member Functions
void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
Detailed Description
actions
represents action executed on transition just between OnExit from old state and OnEntry to new state
Member Function Documentation
Action() [1/12]
void Action (HandEventBase e) inline private
Action() [2/12]
override void Action (HandEventBase e) inline private
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [3/12]
override void Action (HandEventBase e) inline private
References HandEventBase::GetDst(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and GameInventory::LocationSyncMoveEntity().
Action() [4/12]
override void Action (HandEventBase e) inline private
References HandEventBase::GetDst(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and GameInventory::LocationSyncMoveEntity().
Action() [5/12]
override void Action (HandEventBase e) inline private
References Error(), HandEventBase::GetDst(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationSyncMoveEntity(), and DayZPlayer::OnItemInHandsChanged().
Action() [6/12]
override void Action (HandEventBase e) inline private
References Error(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), GameInventory::LocationSyncMoveEntity(), and HandEventBase::m_Dst.
Action() [7/12]
override void Action (HandEventBase e) inline private
References GetGame(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and CGame::ObjectDelete().
Action() [8/12]
override void Action (HandEventBase e) inline private
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [9/12]
override void Action (HandEventBase e) inline private
References Error(), HumanInventory::GetEntityInHands(), EntityAI::GetHumanInventory(), Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [10/12]
override void Action (HandEventBase e) inline private
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [11/12]
override void Action (HandEventBase e) inline private
References Error(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and GameInventory::LocationSwap().
Action() [12/12]
override void Action (HandEventBase e) inline private
References Error(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and GameInventory::LocationSwap().
The documentation for this class was generated from the following file:
P:/scripts/3_Game/Systems/Inventory/Hand_Actions.c