DayZ Scripts: PluginConfigHandler Class Reference
PluginConfigHandler Class Reference
Private Member Functions
protected CfgParamArray GetNewCfgParamArray (array< ref CfgParam > params)
protected CfgParamBool GetNewCfgParamBool (bool value)
protected CfgParamFloat GetNewCfgParamFloat (float value)
protected CfgParamInt GetNewCfgParamInt (int value)
protected CfgParamString GetNewCfgParamString (string value)
protected CfgParamArray SetArray (string key, array< ref CfgParam > params)
protected array< ref CfgParam > GetArray (string key)
protected CfgParamBool SetBool (string key, bool value)
protected bool GetBool (string key)
protected CfgParamFloat SetFloat (string key, float value)
protected float GetFloat (string key)
protected CfgParamInt SetInt (string key, int value)
protected int GetInt (string key)
protected CfgParamString SetString (string key, string value)
protected string GetString (string key)
protected void GetSubParametersInStringArray (string setting_name, string sub_param_name, out TStringArray arr)
void PluginConfigDebugProfile ()
array< ref CfgParam > GetDefaultBatchRectParams ()
override void OnInit ()
override string GetFileName ()
override string GetSubFolderName ()
bool GetSceneEditorDrawSelection ()
void SetSceneEditorDrawSelection (bool value)
bool GetSceneEditorLoadPlayerPos ()
void SetSceneEditorLoadPlayerPos (bool value)
int GetSceneEditorRotationAngle ()
void SetSceneEditorRotationAngle (int value)
int GetTabSelected ()
void SetTabSelected (int value)
int GetSpawnLocIndex ()
void SetSpawnLocIndex (int value)
int GetFilterOrderReversed ()
void SetFilterOrderReversed (bool reversed)
string GetDefaultPreset ()
void SetDefaultPreset (string value)
array< ref CfgParam > GetBatchSpawnRectangle ()
void SetBatchSpawnRectangle (int row, int column, float rowStep, float columnStep)
int GetBatchSpawnQuantity ()
void SetBatchSpawnQuantity (int value)
string GetItemSearch ()
void SetItemSearch (string value)
float GetSpawnDistance ()
void SetSpawnDistance (float value)
bool GetLogsEnabled ()
void SetLogsEnabled (bool value)
bool GetCharacterLevelsVisible ()
void SetCharacterLevelsVisible (bool is_visible)
void SetItemDebugPos (vector pos)
vector GetItemDebugPos ()
bool GetCharacterStatsVisible ()
void SetCharacterStatsVisible (bool is_visible)
bool GetCharacterModifiersVisible ()
void SetCharacterModifiersVisible (bool is_visible)
bool GetCharacterAgentsVisible ()
void SetCharacterAgentsVisible (bool is_visible)
bool GetCharacterDebugVisible ()
void SetCharacterDebugVisible (bool is_visible)
bool GetCharacterStomachVisible ()
void SetCharacterStomachVisible (bool is_visible)
bool GetFreeCameraCrosshairVisible ()
void SetFreeCameraCrosshairVisible (bool is_visible)
bool GetVersionVisible ()
void SetVersionVisible (bool is_visible)
bool GetMergeType ()
void SetMergeType (bool is_visible)
string GetSoundsetFilter ()
void SetSoundsetFilter (string content)
bool GetTempVisible ()
void SetTempVisible (bool is_visible)
bool GetHealthVisible ()
void SetHealthVisible (bool is_visible)
bool GetShowItemPreview ()
void SetShowItemPreview (bool show)
int GetConfigClassesFlag ()
void SetConfigClassesFlag (int flag)
int GetItemCategoryFlag ()
void SetItemCategoryFlag (int flag)
bool CustomLocationsAdd (string name, vector position)
void CustomLocationsRemove (string name)
TStringArray GetPresets ()
protected void SetPreset (string preset_name, int index=-1)
protected void RemovePreset (string preset_name)
bool GetPresetItems (string preset_name, out TStringArray arr, string param_name="")
bool PresetAdd (string preset_name)
bool PresetRemove (string preset_name)
bool PresetRename (string old_preset_name, string new_preset_name)
bool ItemAddToPreset (string preset_name, string item_name)
bool ItemRemoveFromPreset (string preset_name, int item_index)
bool SwapItem (string preset_name, int item1_index, int item2_index)
protected array< ref CfgParam > GetItemParams (string preset_name, int item_index)
protected CfgParam GetItemParam (string preset_name, int item_index, string param_name)
float GetItemHealth (string preset_name, int item_index)
bool SetItemHealth (string preset_name, int item_index, float health)
int GetItemQuantity (string preset_name, int item_index)
bool SetItemQuantity (string preset_name, int item_index, int quantity)
bool GetItemWithPhysics (string preset_name, int item_index)
bool SetItemWithPhysics (string preset_name, int item_index, bool with_physics)
void GetLocationsData (out array< ref LocationParams > arr, bool isCustom)
protected CfgParamInt GetNewCfgParamInt (int value)
protected CfgParamInt SetInt (string key, int value)
protected int GetInt (string key)
void PluginConfigEmotesProfile ()
override string GetFileName ()
int GetEmoteSlot1 ()
void SetEmoteSlot1 (int emoted_id)
int GetEmoteSlot2 ()
void SetEmoteSlot2 (int emoted_id)
int GetEmoteSlot3 ()
void SetEmoteSlot3 (int emoted_id)
int GetEmoteSlot4 ()
void SetEmoteSlot4 (int emoted_id)
int GetEmoteSlot5 ()
void SetEmoteSlot5 (int emoted_id)
int GetEmoteSlot6 ()
void SetEmoteSlot6 (int emoted_id)
int GetEmoteSlot7 ()
void SetEmoteSlot7 (int emoted_id)
int GetEmoteSlot8 ()
void SetEmoteSlot8 (int emoted_id)
int GetEmoteSlot9 ()
void SetEmoteSlot9 (int emoted_id)
int GetEmoteSlot10 ()
void SetEmoteSlot10 (int emoted_id)
int GetEmoteSlot11 ()
void SetEmoteSlot11 (int emoted_id)
int GetEmoteFromSlot (string slot)
override void OnInit ()
string GetPathScenes ()
override string GetFileName ()
void SceneRename (string scene_name, string scene_name_new)
void SceneDelete (string scene_name)
void SceneDuplicate (string scene_name)
TStringArray GetSceneList ()
string EncodeInitScript (string script)
string DecodeInitScript (string script)
void SceneDataSave (SceneData scene)
void SaveSceneSettings (SceneData scene)
void SaveSceneWeather (SceneData scene)
void SaveScenePlayer (SceneData scene)
void SaveSceneObjects (SceneData scene)
SceneData SceneDataLoad (string scene_name)
void LoadSceneSettings (SceneData scene)
void LoadSceneWeather (SceneData scene)
void LoadScenePlayer (SceneData scene)
void LoadSceneObjects (SceneData scene)
override void OnInit ()
override string GetFileName ()
string GetSceneEditorName ()
void SetSceneEditorName (string value)
Static Private Member Functions
static PluginConfigDebugProfile GetInstance ()
static PluginConfigEmotesProfile GetInstance ()
static PluginMissionConfig GetInstance ()
Private Attributes
protected const string SCENE_DRAW_SELECTION = "scene_editor_draw_selection"
protected const string SCENE_LOAD_PLAYER_POS = "scene_editor_load_player_pos"
protected const string SCENE_ROTATION_ANGLE = "scene_editor_rotation_angle"
protected const string ITEM_TAB_SELECTED = "console_TabSelected"
protected const string PRESET_LIST = "console_presets"
protected const string PRESET_DEFAULT = "console_preset_default"
protected const string ITEM_SEARCH = "console_ItemSearch"
protected const string SPAWN_DISTANCE = "console_SpawnDistance"
protected const string CHAR_STATS_VIS = "console_character_stats_visible"
protected const string CHAR_LEVELS_VIS = "console_character_levels_visible"
protected const string CHAR_MODIFIERS_VIS = "console_character_modifiers_visible"
protected const string CHAR_AGENTS_VIS = "console_character_agents_visible"
protected const string CHAR_DEBUG_VIS = "console_character_debug_visible"
protected const string CHAR_STOMACH_VIS = "console_character_stomach_visible"
protected const string FREE_CAMERA_CROSSHAIR = "console_free_camera_crosshair_visible"
protected const string VERSION_VIS = "console_version_visible"
protected const string MERGE_TYPE = "category_merge_type"
protected const string TEMP_VIS = "console_temperature_visible"
protected const string HEALTH_VIS = "console_health_visible"
protected const string SUB_PARAM_ITEM = "item"
protected const string SUB_PARAM_ITEM_NAME = "name"
protected const string SUB_PARAM_ITEM_HEALTH = "health"
protected const string SUB_PARAM_ITEM_QUANTITY = "quantity"
protected const string SUB_PARAM_ITEM_WITH_PHYSICS = "with_physics"
protected const string LOGS_ENABLED = "logs_enabled"
protected const string CONFIG_CLASSES_FLAG = "toggled_config_classes_flag"
protected const string ITEM_CATEGORY_FLAG = "toggled_item_categories_flag"
protected const string ITEM_PREVIEW = "show_item_preview"
protected const string BATCH_RECT = "batch_spawn_rect"
protected const string BATCH_QUANT = "batch_spawn_quantity"
protected const string SOUNDFILTER = "soundset_editbox"
protected const string ITEMDEBUG = "item_debug"
protected const string SPAWN_LOC_INDEX = "spawn_loc_index"
protected const string FILTER_REVERSED = "filter_order_reversed"
protected ref map< string, ref CfgParam > m_DefaultValues
protected ref TStringArray m_PresetList
protected const string POSITION_NAME_ROOT = "console_positions_"
protected string FILE_ROOT = "$saves:"
protected const string FILE_ROOT_SCENES = "scenes"
protected const string PARAM_MISSION = "Mission"
protected const string PARAM_TIME = "InitTime"
protected const string PARAM_YEAR = "InitYear"
protected const string PARAM_MONTH = "InitMonth"
protected const string PARAM_DAY = "InitDay"
protected const string PARAM_HOUR = "InitHour"
protected const string PARAM_MINUTE = "InitMinute"
protected const string PARAM_OVERCAST = "WeatherInitOvercast"
protected const string PARAM_RAIN = "WeatherInitRain"
protected const string PARAM_FOG = "WeatherInitFog"
protected const string PARAM_WIND_F = "WeatherInitWindForce"
protected const string PARAM_PLAYER = "Player"
protected const string PARAM_OBJ_COUNT = "SceneObjectsCount"
protected const string PARAM_OBJ_NAME = "SceneObject"
protected const string PARAM_OBJ_ATT = "Att"
protected const string PARAM_OBJ_LNK = "Lnk"
protected const string PARAM_OBJ_TYPE = "type"
protected const string PARAM_OBJ_POS = "position"
protected const string PARAM_OBJ_ROT = "rotation"
protected const string PARAM_OBJ_DMG = "damage"
protected const string PARAM_OBJ_HLT = "health"
protected const string PARAM_OBJ_ISCR = "init_script"
TStringArray m_CfgTemplate
protected string m_FileSceneName
protected const string FILE_NAME = "scene_editor.cfg"
protected const string SCENE_EDITOR_SCENE = "scene_load"
Member Function Documentation
CustomLocationsAdd()
bool CustomLocationsAdd (string name, vector position) inline private
References g_Game, name, PluginConfigDebugProfile::PluginConfigDebugProfileFixed(), string::ToLower(), and vector::ToString().
CustomLocationsRemove()
void CustomLocationsRemove (string name) inline private
References g_Game, name, and string::ToLower().
DecodeInitScript()
string DecodeInitScript (string script) inline private
References string::Replace().
Referenced by LoadSceneObjects(), and LoadScenePlayer().
EncodeInitScript()
string EncodeInitScript (string script) inline private
References string::Replace().
Referenced by SaveSceneObjects(), and SaveScenePlayer().
GetArray()
protected array< ref CfgParam > GetArray (string key) inline private
References CFG_TYPE_ARRAY.
GetBatchSpawnQuantity()
int GetBatchSpawnQuantity () inline private
References GetInt().
GetBatchSpawnRectangle()
array< ref CfgParam > GetBatchSpawnRectangle () inline private
GetBool()
protected bool GetBool (string key) inline private
References CFG_TYPE_BOOL.
GetCharacterAgentsVisible()
bool GetCharacterAgentsVisible () inline private
GetCharacterDebugVisible()
bool GetCharacterDebugVisible () inline private
GetCharacterLevelsVisible()
bool GetCharacterLevelsVisible () inline private
GetCharacterModifiersVisible()
bool GetCharacterModifiersVisible () inline private
GetCharacterStatsVisible()
bool GetCharacterStatsVisible () inline private
GetCharacterStomachVisible()
bool GetCharacterStomachVisible () inline private
GetConfigClassesFlag()
int GetConfigClassesFlag () inline private
References GetInt().
GetDefaultBatchRectParams()
array< ref CfgParam > GetDefaultBatchRectParams () inline private
GetDefaultPreset()
string GetDefaultPreset () inline private
GetEmoteFromSlot()
int GetEmoteFromSlot (string slot) inline private
References GetInt().
GetEmoteSlot1()
int GetEmoteSlot1 () inline private
References GetInt().
GetEmoteSlot10()
int GetEmoteSlot10 () inline private
References GetInt().
GetEmoteSlot11()
int GetEmoteSlot11 () inline private
References GetInt().
GetEmoteSlot2()
int GetEmoteSlot2 () inline private
References GetInt().
GetEmoteSlot3()
int GetEmoteSlot3 () inline private
References GetInt().
GetEmoteSlot4()
int GetEmoteSlot4 () inline private
References GetInt().
GetEmoteSlot5()
int GetEmoteSlot5 () inline private
References GetInt().
GetEmoteSlot6()
int GetEmoteSlot6 () inline private
References GetInt().
GetEmoteSlot7()
int GetEmoteSlot7 () inline private
References GetInt().
GetEmoteSlot8()
int GetEmoteSlot8 () inline private
References GetInt().
GetEmoteSlot9()
int GetEmoteSlot9 () inline private
References GetInt().
GetFileName() [1/4]
override string GetFileName () inline private
References CFG_FILE_DEBUG_PROFILE, FileExist(), and GetSubFolderName().
Referenced by SceneDataLoad().
GetFileName() [2/4]
override string GetFileName () inline private
References CFG_FILE_EMOTES_PROFILE.
GetFileName() [3/4]
override string GetFileName () inline private
References GetPathScenes(), and m_FileSceneName.
GetFileName() [4/4]
override string GetFileName () inline private
References FILE_NAME, and g_Game.
GetFilterOrderReversed()
int GetFilterOrderReversed () inline private
GetFloat()
protected float GetFloat (string key) inline private
References CFG_TYPE_FLOAT.
GetFreeCameraCrosshairVisible()
bool GetFreeCameraCrosshairVisible () inline private
GetHealthVisible()
bool GetHealthVisible () inline private
GetInstance() [1/3]
static PluginConfigDebugProfile GetInstance () inline static private
References GetPlugin().
GetInstance() [2/3]
static PluginConfigEmotesProfile GetInstance () inline static private
References GetPlugin().
GetInstance() [3/3]
static PluginMissionConfig GetInstance () inline static private
References GetPlugin().
GetInt() [1/2]
protected int GetInt (string key) inline private
References CFG_TYPE_INT.
GetInt() [2/2]
protected int GetInt (string key) inline private
References CFG_TYPE_INT, and SetInt().
GetItemCategoryFlag()
int GetItemCategoryFlag () inline private
References GetInt().
GetItemDebugPos()
vector GetItemDebugPos () inline private
GetItemHealth()
float GetItemHealth (string preset_name, int item_index) inline private
GetItemParam()
protected CfgParam GetItemParam (string preset_name, int item_index, string param_name) inline private
GetItemParams()
protected array< ref CfgParam > GetItemParams (string preset_name, int item_index) inline private
GetItemQuantity()
int GetItemQuantity (string preset_name, int item_index) inline private
GetItemSearch()
string GetItemSearch () inline private
GetItemWithPhysics()
bool GetItemWithPhysics (string preset_name, int item_index) inline private
GetLocationsData()
void GetLocationsData (out array< ref LocationParams > arr, bool isCustom) inline private
References g_Game, PluginConfigDebugProfile::PluginConfigDebugProfileFixed(), and string::ToLower().
GetLogsEnabled()
bool GetLogsEnabled () inline private
GetMergeType()
bool GetMergeType () inline private
GetNewCfgParamArray()
protected CfgParamArray GetNewCfgParamArray (array< ref CfgParam > params) inline private
GetNewCfgParamBool()
protected CfgParamBool GetNewCfgParamBool (bool value) inline private
GetNewCfgParamFloat()
protected CfgParamFloat GetNewCfgParamFloat (float value) inline private
GetNewCfgParamInt() [1/2]
protected CfgParamInt GetNewCfgParamInt (int value) inline private
GetNewCfgParamInt() [2/2]
protected CfgParamInt GetNewCfgParamInt (int value) inline private
GetNewCfgParamString()
protected CfgParamString GetNewCfgParamString (string value) inline private
GetPathScenes()
string GetPathScenes () inline private
References FILE_ROOT_SCENES.
Referenced by GetFileName(), GetSceneList(), SceneDelete(), SceneDuplicate(), and SceneRename().
GetPresetItems()
bool GetPresetItems (string preset_name, out TStringArray arr, string param_name = "") inline private
GetPresets()
TStringArray GetPresets () inline private
GetSceneEditorDrawSelection()
bool GetSceneEditorDrawSelection () inline private
GetSceneEditorLoadPlayerPos()
bool GetSceneEditorLoadPlayerPos () inline private
GetSceneEditorName()
string GetSceneEditorName () inline private
References CFG_TYPE_STRING, and STRING_EMPTY.
GetSceneEditorRotationAngle()
int GetSceneEditorRotationAngle () inline private
References GetInt().
GetSceneList()
TStringArray GetSceneList () inline private
References FileExist(), FindFile(), FindNextFile(), GetPathScenes(), string::IndexOf(), MakeDirectory(), and string::Substring().
GetShowItemPreview()
bool GetShowItemPreview () inline private
GetSoundsetFilter()
string GetSoundsetFilter () inline private
GetSpawnDistance()
float GetSpawnDistance () inline private
GetSpawnLocIndex()
int GetSpawnLocIndex () inline private
References GetInt().
GetString()
protected string GetString (string key) inline private
References CFG_TYPE_STRING, and STRING_EMPTY.
GetSubFolderName()
override string GetSubFolderName () inline private
References CFG_FILE_DEBUG_DIR.
GetSubParametersInStringArray()
protected void GetSubParametersInStringArray (string setting_name, string sub_param_name, out TStringArray arr) inline private
GetTabSelected()
int GetTabSelected () inline private
References GetInt().
GetTempVisible()
bool GetTempVisible () inline private
GetVersionVisible()
bool GetVersionVisible () inline private
ItemAddToPreset()
bool ItemAddToPreset (string preset_name, string item_name) inline private
ItemRemoveFromPreset()
bool ItemRemoveFromPreset (string preset_name, int item_index) inline private
LoadSceneObjects()
void LoadSceneObjects (SceneData scene) inline private
References CFG_TYPE_ARRAY, CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, SceneData::CreateSceneObject(), DecodeInitScript(), SceneObject::GetObject(), SceneObject::m_LinkedSceneObjectsIndices, PARAM_OBJ_ATT, SceneObject::SetHealth(), SceneObject::SetInitScript(), SceneObject::SetRotation(), and string::ToString().
Referenced by SceneDataLoad().
LoadScenePlayer()
void LoadScenePlayer (SceneData scene) inline private
References CFG_TYPE_ARRAY, CFG_TYPE_FLOAT, CFG_TYPE_STRING, SceneData::CreateScenePlayer(), DecodeInitScript(), GetGame(), GetPlayer(), and vector::Zero.
Referenced by SceneDataLoad().
LoadSceneSettings()
void LoadSceneSettings (SceneData scene) inline private
References CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, World::GetDate(), GetGame(), CGame::GetWorld(), SceneData::SetInitDay(), SceneData::SetInitHour(), SceneData::SetInitMinute(), SceneData::SetInitMonth(), SceneData::SetInitTime(), SceneData::SetInitYear(), and SceneData::SetNameMission().
Referenced by SceneDataLoad().
LoadSceneWeather()
void LoadSceneWeather (SceneData scene) inline private
References CFG_TYPE_FLOAT, SceneData::SetInitFog(), SceneData::SetInitOvercast(), SceneData::SetInitRain(), and SceneData::SetInitWindForce().
Referenced by SceneDataLoad().
OnInit() [1/3]
override void OnInit () inline private
OnInit() [2/3]
override void OnInit () inline private
References g_Game.
OnInit() [3/3]
override void OnInit () inline private
References CFG_TYPE_STRING, and STRING_EMPTY.
PluginConfigDebugProfile()
void PluginConfigDebugProfile () inline private
PluginConfigEmotesProfile()
void PluginConfigEmotesProfile () inline private
References EmoteConstants::ID_EMOTE_GREETING, EmoteConstants::ID_EMOTE_HEART, EmoteConstants::ID_EMOTE_POINT, EmoteConstants::ID_EMOTE_SOS, EmoteConstants::ID_EMOTE_SUICIDE, EmoteConstants::ID_EMOTE_SURRENDER, EmoteConstants::ID_EMOTE_TAUNT, EmoteConstants::ID_EMOTE_TAUNTELBOW, EmoteConstants::ID_EMOTE_TAUNTKISS, EmoteConstants::ID_EMOTE_THROAT, and EmoteConstants::ID_EMOTE_THUMB.
PresetAdd()
bool PresetAdd (string preset_name) inline private
PresetRemove()
bool PresetRemove (string preset_name) inline private
PresetRename()
bool PresetRename (string old_preset_name, string new_preset_name) inline private
RemovePreset()
protected void RemovePreset (string preset_name) inline private
SaveSceneObjects()
void SaveSceneObjects (SceneData scene) inline private
References CFG_TYPE_ARRAY, CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, EncodeInitScript(), SceneObject::GetHealth(), SceneObject::GetInitScript(), SceneObject::GetLinkedSceneObjects(), SceneObject::GetObject(), SceneObject::GetPositionAsString(), SceneObject::GetRotation(), SceneData::GetSceneObjects(), SceneObject::GetTypeName(), PARAM_OBJ_ATT, PARAM_OBJ_LNK, and string::ToString().
Referenced by SceneDataSave().
SaveScenePlayer()
void SaveScenePlayer (SceneData scene) inline private
References CFG_TYPE_ARRAY, CFG_TYPE_FLOAT, CFG_TYPE_STRING, EncodeInitScript(), and SceneData::GetScenePlayers().
Referenced by SceneDataSave().
SaveSceneSettings()
void SaveSceneSettings (SceneData scene) inline private
References CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, SceneData::GetInitDay(), SceneData::GetInitHour(), SceneData::GetInitMinute(), SceneData::GetInitMonth(), SceneData::GetInitTime(), SceneData::GetInitYear(), and SceneData::GetNameMission().
Referenced by SceneDataSave().
SaveSceneWeather()
void SaveSceneWeather (SceneData scene) inline private
References CFG_TYPE_FLOAT, SceneData::GetInitFog(), SceneData::GetInitOvercast(), SceneData::GetInitRain(), and SceneData::GetInitWindForce().
Referenced by SceneDataSave().
SceneDataLoad()
SceneData SceneDataLoad (string scene_name) inline private
References FileExist(), GetFileName(), LoadSceneObjects(), LoadScenePlayer(), LoadSceneSettings(), LoadSceneWeather(), SceneDataSave(), and SceneData::SetNameScene().
SceneDataSave()
void SceneDataSave (SceneData scene) inline private
References SceneData::GetNameScene(), GetPlugin(), SaveSceneObjects(), SaveScenePlayer(), SaveSceneSettings(), and SaveSceneWeather().
Referenced by SceneDataLoad().
SceneDelete()
void SceneDelete (string scene_name) inline private
References GetPathScenes().
SceneDuplicate()
void SceneDuplicate (string scene_name) inline private
References FileExist(), and GetPathScenes().
SceneRename()
void SceneRename (string scene_name, string scene_name_new) inline private
References GetPathScenes().
SetArray()
protected CfgParamArray SetArray (string key, array< ref CfgParam > params) inline private
References CFG_TYPE_ARRAY.
SetBatchSpawnQuantity()
void SetBatchSpawnQuantity (int value) inline private
SetBatchSpawnRectangle()
void SetBatchSpawnRectangle (int row, int column, float rowStep, float columnStep) inline private
SetBool()
protected CfgParamBool SetBool (string key, bool value) inline private
References CFG_TYPE_BOOL.
SetCharacterAgentsVisible()
void SetCharacterAgentsVisible (bool is_visible) inline private
SetCharacterDebugVisible()
void SetCharacterDebugVisible (bool is_visible) inline private
SetCharacterLevelsVisible()
void SetCharacterLevelsVisible (bool is_visible) inline private
SetCharacterModifiersVisible()
void SetCharacterModifiersVisible (bool is_visible) inline private
SetCharacterStatsVisible()
void SetCharacterStatsVisible (bool is_visible) inline private
SetCharacterStomachVisible()
void SetCharacterStomachVisible (bool is_visible) inline private
SetConfigClassesFlag()
void SetConfigClassesFlag (int flag) inline private
SetDefaultPreset()
void SetDefaultPreset (string value) inline private
SetEmoteSlot1()
void SetEmoteSlot1 (int emoted_id) inline private
References SetInt().
SetEmoteSlot10()
void SetEmoteSlot10 (int emoted_id) inline private
References SetInt().
SetEmoteSlot11()
void SetEmoteSlot11 (int emoted_id) inline private
References SetInt().
SetEmoteSlot2()
void SetEmoteSlot2 (int emoted_id) inline private
References SetInt().
SetEmoteSlot3()
void SetEmoteSlot3 (int emoted_id) inline private
References SetInt().
SetEmoteSlot4()
void SetEmoteSlot4 (int emoted_id) inline private
References SetInt().
SetEmoteSlot5()
void SetEmoteSlot5 (int emoted_id) inline private
References SetInt().
SetEmoteSlot6()
void SetEmoteSlot6 (int emoted_id) inline private
References SetInt().
SetEmoteSlot7()
void SetEmoteSlot7 (int emoted_id) inline private
References SetInt().
SetEmoteSlot8()
void SetEmoteSlot8 (int emoted_id) inline private
References SetInt().
SetEmoteSlot9()
void SetEmoteSlot9 (int emoted_id) inline private
References SetInt().
SetFilterOrderReversed()
void SetFilterOrderReversed (bool reversed) inline private
SetFloat()
protected CfgParamFloat SetFloat (string key, float value) inline private
References CFG_TYPE_FLOAT.
SetFreeCameraCrosshairVisible()
void SetFreeCameraCrosshairVisible (bool is_visible) inline private
SetHealthVisible()
void SetHealthVisible (bool is_visible) inline private
SetInt() [1/2]
protected CfgParamInt SetInt (string key, int value) inline private
References CFG_TYPE_INT.
Referenced by GetInt(), SetEmoteSlot1(), SetEmoteSlot10(), SetEmoteSlot11(), SetEmoteSlot2(), SetEmoteSlot3(), SetEmoteSlot4(), SetEmoteSlot5(), SetEmoteSlot6(), SetEmoteSlot7(), SetEmoteSlot8(), and SetEmoteSlot9().
SetInt() [2/2]
protected CfgParamInt SetInt (string key, int value) inline private
References CFG_TYPE_INT.
SetItemCategoryFlag()
void SetItemCategoryFlag (int flag) inline private
SetItemDebugPos()
void SetItemDebugPos (vector pos) inline private
References vector::ToString().
SetItemHealth()
bool SetItemHealth (string preset_name, int item_index, float health) inline private
SetItemQuantity()
bool SetItemQuantity (string preset_name, int item_index, int quantity) inline private
SetItemSearch()
void SetItemSearch (string value) inline private
SetItemWithPhysics()
bool SetItemWithPhysics (string preset_name, int item_index, bool with_physics) inline private
SetLogsEnabled()
void SetLogsEnabled (bool value) inline private
SetMergeType()
void SetMergeType (bool is_visible) inline private
SetPreset()
protected void SetPreset (string preset_name, int index = -1) inline private
SetSceneEditorDrawSelection()
void SetSceneEditorDrawSelection (bool value) inline private
SetSceneEditorLoadPlayerPos()
void SetSceneEditorLoadPlayerPos (bool value) inline private
SetSceneEditorName()
void SetSceneEditorName (string value) inline private
References CFG_TYPE_STRING.
SetSceneEditorRotationAngle()
void SetSceneEditorRotationAngle (int value) inline private
SetShowItemPreview()
void SetShowItemPreview (bool show) inline private
SetSoundsetFilter()
void SetSoundsetFilter (string content) inline private
SetSpawnDistance()
void SetSpawnDistance (float value) inline private
SetSpawnLocIndex()
void SetSpawnLocIndex (int value) inline private
SetString()
protected CfgParamString SetString (string key, string value) inline private
References CFG_TYPE_STRING.
SetTabSelected()
void SetTabSelected (int value) inline private
SetTempVisible()
void SetTempVisible (bool is_visible) inline private
SetVersionVisible()
void SetVersionVisible (bool is_visible) inline private
SwapItem()
bool SwapItem (string preset_name, int item1_index, int item2_index) inline private
Field Documentation
BATCH_QUANT
protected const string BATCH_QUANT = "batch_spawn_quantity" private
BATCH_RECT
protected const string BATCH_RECT = "batch_spawn_rect" private
CHAR_AGENTS_VIS
protected const string CHAR_AGENTS_VIS = "console_character_agents_visible" private
CHAR_DEBUG_VIS
protected const string CHAR_DEBUG_VIS = "console_character_debug_visible" private
CHAR_LEVELS_VIS
protected const string CHAR_LEVELS_VIS = "console_character_levels_visible" private
CHAR_MODIFIERS_VIS
protected const string CHAR_MODIFIERS_VIS = "console_character_modifiers_visible" private
CHAR_STATS_VIS
protected const string CHAR_STATS_VIS = "console_character_stats_visible" private
CHAR_STOMACH_VIS
protected const string CHAR_STOMACH_VIS = "console_character_stomach_visible" private
CONFIG_CLASSES_FLAG
protected const string CONFIG_CLASSES_FLAG = "toggled_config_classes_flag" private
FILE_NAME
protected const string FILE_NAME = "scene_editor.cfg" private
Referenced by GetFileName().
FILE_ROOT
protected string FILE_ROOT = "$saves:" private
FILE_ROOT_SCENES
protected const string FILE_ROOT_SCENES = "scenes" private
Referenced by GetPathScenes().
FILTER_REVERSED
protected const string FILTER_REVERSED = "filter_order_reversed" private
FREE_CAMERA_CROSSHAIR
protected const string FREE_CAMERA_CROSSHAIR = "console_free_camera_crosshair_visible" private
HEALTH_VIS
protected const string HEALTH_VIS = "console_health_visible" private
ITEM_CATEGORY_FLAG
protected const string ITEM_CATEGORY_FLAG = "toggled_item_categories_flag" private
ITEM_PREVIEW
protected const string ITEM_PREVIEW = "show_item_preview" private
ITEM_SEARCH
protected const string ITEM_SEARCH = "console_ItemSearch" private
ITEM_TAB_SELECTED
protected const string ITEM_TAB_SELECTED = "console_TabSelected" private
ITEMDEBUG
protected const string ITEMDEBUG = "item_debug" private
LOGS_ENABLED
protected const string LOGS_ENABLED = "logs_enabled" private
m_CfgTemplate
TStringArray m_CfgTemplate private
m_DefaultValues
protected ref map< string, ref CfgParam > m_DefaultValues private
m_FileSceneName
protected string m_FileSceneName private
Referenced by GetFileName().
m_PresetList
protected ref TStringArray m_PresetList private
MERGE_TYPE
protected const string MERGE_TYPE = "category_merge_type" private
PARAM_DAY
protected const string PARAM_DAY = "InitDay" private
PARAM_FOG
protected const string PARAM_FOG = "WeatherInitFog" private
PARAM_HOUR
protected const string PARAM_HOUR = "InitHour" private
PARAM_MINUTE
protected const string PARAM_MINUTE = "InitMinute" private
PARAM_MISSION
protected const string PARAM_MISSION = "Mission" private
PARAM_MONTH
protected const string PARAM_MONTH = "InitMonth" private
PARAM_OBJ_ATT
protected const string PARAM_OBJ_ATT = "Att" private
Referenced by LoadSceneObjects(), and SaveSceneObjects().
PARAM_OBJ_COUNT
protected const string PARAM_OBJ_COUNT = "SceneObjectsCount" private
PARAM_OBJ_DMG
protected const string PARAM_OBJ_DMG = "damage" private
PARAM_OBJ_HLT
protected const string PARAM_OBJ_HLT = "health" private
PARAM_OBJ_ISCR
protected const string PARAM_OBJ_ISCR = "init_script" private
PARAM_OBJ_LNK
protected const string PARAM_OBJ_LNK = "Lnk" private
Referenced by SaveSceneObjects().
PARAM_OBJ_NAME
protected const string PARAM_OBJ_NAME = "SceneObject" private
PARAM_OBJ_POS
protected const string PARAM_OBJ_POS = "position" private
PARAM_OBJ_ROT
protected const string PARAM_OBJ_ROT = "rotation" private
PARAM_OBJ_TYPE
protected const string PARAM_OBJ_TYPE = "type" private
PARAM_OVERCAST
protected const string PARAM_OVERCAST = "WeatherInitOvercast" private
PARAM_PLAYER
protected const string PARAM_PLAYER = "Player" private
PARAM_RAIN
protected const string PARAM_RAIN = "WeatherInitRain" private
PARAM_TIME
protected const string PARAM_TIME = "InitTime" private
PARAM_WIND_F
protected const string PARAM_WIND_F = "WeatherInitWindForce" private
PARAM_YEAR
protected const string PARAM_YEAR = "InitYear" private
POSITION_NAME_ROOT
protected const string POSITION_NAME_ROOT = "console_positions_" private
PRESET_DEFAULT
protected const string PRESET_DEFAULT = "console_preset_default" private
PRESET_LIST
protected const string PRESET_LIST = "console_presets" private
SCENE_DRAW_SELECTION
protected const string SCENE_DRAW_SELECTION = "scene_editor_draw_selection" private
SCENE_EDITOR_SCENE
protected const string SCENE_EDITOR_SCENE = "scene_load" private
SCENE_LOAD_PLAYER_POS
protected const string SCENE_LOAD_PLAYER_POS = "scene_editor_load_player_pos" private
SCENE_ROTATION_ANGLE
protected const string SCENE_ROTATION_ANGLE = "scene_editor_rotation_angle" private
SOUNDFILTER
protected const string SOUNDFILTER = "soundset_editbox" private
SPAWN_DISTANCE
protected const string SPAWN_DISTANCE = "console_SpawnDistance" private
SPAWN_LOC_INDEX
protected const string SPAWN_LOC_INDEX = "spawn_loc_index" private
SUB_PARAM_ITEM
protected const string SUB_PARAM_ITEM = "item" private
SUB_PARAM_ITEM_HEALTH
protected const string SUB_PARAM_ITEM_HEALTH = "health" private
SUB_PARAM_ITEM_NAME
protected const string SUB_PARAM_ITEM_NAME = "name" private
SUB_PARAM_ITEM_QUANTITY
protected const string SUB_PARAM_ITEM_QUANTITY = "quantity" private
SUB_PARAM_ITEM_WITH_PHYSICS
protected const string SUB_PARAM_ITEM_WITH_PHYSICS = "with_physics" private
TEMP_VIS
protected const string TEMP_VIS = "console_temperature_visible" private
VERSION_VIS
protected const string VERSION_VIS = "console_version_visible" private
The documentation for this class was generated from the following files:
P:/scripts/4_World/Plugins/PluginBase/PluginFileHandler/PluginConfigHandler/PluginConfigDebugProfile.c
P:/scripts/4_World/Plugins/PluginBase/PluginFileHandler/PluginConfigHandler/PluginConfigEmotesProfile.c
P:/scripts/4_World/Plugins/PluginBase/PluginFileHandler/PluginConfigHandler/PluginConfigScene.c
P:/scripts/4_World/Plugins/PluginBase/PluginFileHandler/PluginConfigHandler/PluginMissionConfig.c