DayZ Scripts: CallQueue Class Reference
CallQueue Class Reference
Tools
DragQueue Class provide callbacks while mouse is dragging. Callback function must have exact arguments:
Private Member Functions
void DragQueue ()
override void Tick ()
System function, don't call it.
Private Attributes
private ref Param3< int, int, bool > m_mouse_params
Detailed Description
DragQueue Class provide callbacks while mouse is dragging. Callback function must have exact arguments:
void AnyFunctionName(int mouse_x, int mouse_y, bool is_dragging);
When mouse button is released, callback function is called one more time with is_dragging = false. Then all callbacks are automatically removed from queue.
usage:
 class XYZ
 {
    void UpdateDrag(int mouse_x, int mouse_y, bool is_dragging);
 }
...
 GetGame().GetDragQueue().Call(this, "UpdateDrag"); // calls "UpdateDrag" function on "this"
Member Function Documentation
DragQueue()
void DragQueue () inline private
Tick()
override void Tick () inline private
System function, don't call it.
References CallQueueContext::CallParams(), Clear(), Count, Get(), GetMousePos(), GetMouseState(), CallQueueContext::IsValid(), and Remove().
Field Documentation
m_mouse_params
private ref Param3<int, int, bool> m_mouse_params private
The documentation for this class was generated from the following file:
P:/scripts/3_Game/tools/tools.c