DayZ Scripts: FireConsumable Class Reference
FireConsumable Class Reference
Private Member Functions
void FireConsumable (ItemBase item, float energy)
ItemBase GetItem ()
float GetEnergy ()
float GetRemainingEnergy ()
void SetRemainingEnergy (float energy)
Private Attributes
ItemBase m_Item
float m_Energy
float m_RemainingEnergy
Detailed Description
Definition at line 1 of file FireConsumable.c.
Constructor & Destructor Documentation
FireConsumable()
void FireConsumable (ItemBase item, float energy) inline private
Definition at line 7 of file FireConsumable.c.
References m_Energy, m_Item, and m_RemainingEnergy.
Member Function Documentation
GetEnergy()
float GetEnergy () inline private
Definition at line 21 of file FireConsumable.c.
References m_Energy.
Referenced by SetItemToConsume(), and SpendFireConsumable().
GetItem()
ItemBase GetItem () inline private
Definition at line 15 of file FireConsumable.c.
References m_Item.
Referenced by RemoveFromFireConsumables(), and SpendFireConsumable().
GetRemainingEnergy()
float GetRemainingEnergy () inline private
Definition at line 27 of file FireConsumable.c.
References m_RemainingEnergy.
Referenced by SpendFireConsumable().
SetRemainingEnergy()
void SetRemainingEnergy (float energy) inline private
Definition at line 32 of file FireConsumable.c.
References m_RemainingEnergy.
Referenced by SpendFireConsumable().
Field Documentation
m_Energy
float m_Energy private
Definition at line 4 of file FireConsumable.c.
Referenced by FireConsumable(), and GetEnergy().
m_Item
ItemBase m_Item private
Definition at line 3 of file FireConsumable.c.
Referenced by FireConsumable(), and GetItem().
m_RemainingEnergy
float m_RemainingEnergy private
Definition at line 5 of file FireConsumable.c.
Referenced by FireConsumable(), GetRemainingEnergy(), and SetRemainingEnergy().
The documentation for this class was generated from the following file:
P:/scripts/4_World/Classes/Cooking/FireConsumable.c