DayZ Scripts: ActionConstructor Class Reference
ActionConstructor Class Reference
Private Member Functions
bool ConstructActions (out array< ref ActionBase > actionsArray, out map< typename, ActionBase > actionNameActionMap)
void RegisterActions (TTypenameArray actions)
Member Function Documentation
ConstructActions()
bool ConstructActions (out array< ref ActionBase > actionsArray, out map< typename, ActionBase > actionNameActionMap) inline private
References ActionBase(), RegisterActions(), Sort(), and Spawn().
Referenced by ActionManagerBase().
RegisterActions()
void RegisterActions (TTypenameArray actions) inline private
References ActionActivateTrap(), ActionArmExplosive(), ActionAttach(), ActionAttachExplosivesTrigger(), ActionBandageSelf(), ActionBandageTarget(), ActionBuildOven(), ActionBuildStoneCircle(), ActionBuryAshes(), ActionCarHornShort(), ActionCraftArmband(), ActionDeCraftDrysackBag(), ActionDeCraftRopeBelt(), ActionDeCraftWitchHoodCoif(), ActionDeployObject(), ActionDetach(), ActionDetachFromTarget_SpecificSlot_MetalSheets(), ActionDetachFromTarget_SpecificSlot_WoodenLogs(), ActionDetachFromTarget_SpecificSlotsCategory_WoodenCrate(), ActionDialCombinationLock(), ActionDialCombinationLockOnTarget(), ActionDigOutStash(), ActionDisarmExplosive(), ActionDisarmExplosiveWithRemoteDetonator(), ActionDisarmExplosiveWithRemoteDetonatorUnpaired(), ActionDisarmMine(), ActionDisinfectSelf(), ActionDismantleOven(), ActionDismantleStoneCircle(), ActionDrinkPondContinuous(), ActionDrinkWellContinuous(), ActionDropItem(), ActionExtinguishFireplaceByExtinguisher(), ActionExtinguishFireplaceByLiquid(), ActionFoldBaseBuildingObject(), ActionForceConsume(), ActionForceConsumeSingle(), ActionForceFeed, ActionGetOutTransport(), ActionLightItemOnFire(), ActionLightItemOnFireWithBlowtorch(), ActionMineTree(), ActionPackTent(), ActionRaiseMegaphone(), ActionRepairCarChassisWithBlowtorch(), ActionRepairCarEngine(), ActionRepairCarEngineWithBlowtorch(), ActionRepairCarPart(), ActionRepairCarPartWithBlowtorch(), ActionRepairItemWithBlowtorch(), ActionResetKitchenTimer(), ActionSewSelf(), ActionSewTarget(), ActionSkinning(), ActionStartEngine(), ActionTuneFrequency(), ActionTuneRadioStation(), ActionTurnOffAlarmClock(), ActionTurnOffTransmitter(), ActionTurnOnAlarmClock(), ActionTurnOnTransmitter(), ActionTurnValve(), ActionTurnValveUndergroundReservoir(), ActionUncoverHeadSelf(), ActionUnfoldMap(), ActionWashHandsWater(), ActionWashHandsWell(), and FirearmActionLoadBulletQuick().
Referenced by ConstructActions().
The documentation for this class was generated from the following file:
P:/scripts/4_world/classes/useractionscomponent/actionconstructor.c